### ISSUE TITLE
[BUG]定时同步，任务通知的弹窗内容有缓存

### ISSUE THREAD

**Issue by jackelchen** [metersphere/metersphere#10003]
**MeterSphere 版本**

v1.16.6-637a179f

**Bug 描述**

多个定时同步任务，分别查看不同任务的任务通知，弹窗都会显示第一个打开的任务的通知配置

**Bug 重现步骤**

1.  创建多个定时任务，分别配置通知配置
2. 重新打开定时同步标签页
3. 查看序号1的任务通知，查看序号2的任务通知，会显示成序号1的配置
4. 

**期待的正确结果**
有配置通知的弹窗正常显示，没配置通知的弹窗显示事件为空

**截图**
![image](https://user-images.githubusercontent.com/15845086/150907446-ecf3629b-0809-4db3-8d60-44b21763b292.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.1已修复
