### ISSUE TITLE
场景中自定义SQL保存后，无法修改

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#1000]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6
**Bug 描述**
简要描述您碰到的问题
场景中自定义SQL保存后，无法修改
**Bug 重现步骤**
1.  在场景中创建SQL
2. 保存后，无法在进行任何修改
![image](https://user-images.githubusercontent.com/30932762/103131666-a03c7c00-46dc-11eb-94d7-64cc592d67db.png)

**期待的正确结果**
1.应该可以进行修改

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已修改，请升级验证
