### ISSUE TITLE
[FEATURE]在场景中创建完请求后，断言无法追加，只能在新建的时候，追加断言

### ISSUE THREAD

**Issue by yixiao1983** [metersphere/metersphere#1003]
**版本**
 v1.6.0-fbda7b42

**请描述您的需求或者改进建议.**
在场景中创建完请求后，断言无法追加，只能在新建的时候，追加断言

**请描述你建议的实现方案**
1.创建完请求后，也可以追加断言
2.在已有的请求中，可以追加多个断言规则(目前只能在新建的断言规则下面追加项目，无法添加第二个断言规则块）

![image](https://user-images.githubusercontent.com/3301966/103144695-cd367080-4768-11eb-9aa5-ec71945fdfc9.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该问题已修复
