### ISSUE TITLE
[BUG]测试计划中的定时任务，配置了失败通知钉钉，但是里边有接口执行失败了也没有通知

### ISSUE THREAD

**Issue by haizi-cui** [metersphere/metersphere#10034]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.6

**Bug 描述**

简要描述您碰到的问题
测试计划中的定时任务，配置了失败通知钉钉，但是里边有接口执行失败了也没有通知
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
测试计划这边是有问题，后面会修复的

**Comment by haizi-cui** [comment]
好的 ，感谢

**Comment by zyyfit** [comment]
1.17.0已统一状态

**Comment by haizi-cui** [comment]
> 1.17.0已统一状态

不对啊现在只能选择执行完成的吗

**Comment by haizi-cui** [comment]
![image](https://user-images.githubusercontent.com/63744634/151355915-2b520280-22af-4da0-974d-c20c81f523ed.png)

**Comment by haizi-cui** [comment]
选不到失败通知或者成功通知了

**Comment by zyyfit** [comment]
> 选不到失败通知或者成功通知了

是的，现在是统一成这样了，您如果有需求，可以提feature

**Comment by haizi-cui** [comment]
最近有迭代可以排进来吗？这个对于我们还是很重要的
