### ISSUE TITLE
[BUG]创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10035]
**MeterSphere 版本**

v1.16.6-637a179f

**Bug 描述**

创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/150935300-0b895d02-21e5-45aa-b250-39863b643fa5.png)

**Comment by zyyfit** [comment]
请问您开启接口url可重复了吗

**Comment by sageonedream** [comment]
开启了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 中午12:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改 (Issue #10035)




 
请问您开启接口url可重复了吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 开启了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月26日(周三) 中午12:07 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [metersphere/metersphere] [BUG]创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改 (Issue #10035) 请问您开启接口url可重复了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

嗯嗯，这个主要是为了让url不重复加的校验，单纯的接口名称重复是没有校验的，所以就是这个提示

**Comment by sageonedream** [comment]
但是现在的场景是，我开启了允许url重复，相同的url，相同的接口名称，报错提示还是接口url已存在，那按理说应该没有这个报错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改 (Issue #10035)




  
开启了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年1月26日(周三) 中午12:07 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [metersphere/metersphere] [BUG]创建同名的API接口时，报错提示有误，应提示为“接口名称已存在”，请修改 (Issue #10035) 请问您开启接口url可重复了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
嗯嗯，这个主要是为了让url不重复加的校验，单纯的接口名称重复是没有校验的，所以就是这个提示
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
1.17.1已修复
