### ISSUE TITLE
[BUG]测试计划报告--性能测试报告：监控信息有误，此显示信息应该没有刷新。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10047]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.6

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

背景：
1、在计划中添加A性能测试，并且也执行了。但是当时系统没有配置监控，所以此无监控信息。
2、配置监控信息后，计划里添加B性能脚本，执行B性能脚本。此有监控信息。
操作：
1、在计划报告里，先点击A性能，查看监控为空；再点击b性能，然后在点击a性能脚本，此监控为b监控信息。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/150941015-f01843a2-9444-4408-8424-1306f7ae2016.png)
![image](https://user-images.githubusercontent.com/78218624/150941203-ae4b8b2e-3113-4b1f-bbff-947b3d1643b9.png)
![image](https://user-images.githubusercontent.com/78218624/150941433-c864becb-4334-45c0-a36f-c204ddd9b7dd.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.1版本已修复
