### ISSUE TITLE
[BUG]测试跟踪-测试计划-关联测试用例，测试用例很多时需要下拉到底才能全部选择，易用性上体验很差

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#1004]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.0
**Bug 描述**
简要描述您碰到的问题
测试跟踪-测试计划-关联测试用例，测试用例很多时需要一直下拉到底才能全部选择，易用性上体验很差，特别是用例多时需要选择时，建议增加按照模块选择添加
**Bug 重现步骤**
1.  用例条数很多时，全部选择，需要下拉到底才能选择全部用例
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
无需下拉到底就可以选择，指定模块的全部用例
**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
![image](https://user-images.githubusercontent.com/41557596/105938661-a8e4f100-6092-11eb-94d1-4d2f1c370e26.png)
你好，这里有全选的按钮，不需要下拉到底吧
