### ISSUE TITLE
[BUG][重新打开]最新版本环境管理绑定hosts之后，接口耗时固定增加（v1.15.4：15s+接口耗时；v1.13.2：30s+接口耗时），降到v1.10.9-lts则正常

### ISSUE THREAD

**Issue by 85899608** [metersphere/metersphere#10041]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.4
v1.13.2

**Bug 描述**
v1.15.4绑hosts前：
2021-12-14 16:21:03,776 [XNIO-1 task-6] INFO i.m.websocket.c.to.c.IndexWebSocket ? - 客户端: [487cbded] : 连接成功！
2021-12-14 16:21:03,820 [XNIO-1 I/O-4] INFO i.m.websocket.c.to.c.IndexWebSocket ? - 服务器收到：[send.487cbded] : {"content":"","reportId":"send.487cbded","toReport":"487cbded"}
v1.15.4绑hosts后：
2021-12-14 16:24:12,075 [XNIO-1 task-6] INFO i.m.websocket.c.to.c.IndexWebSocket ? - 客户端: [70493ff6] : 连接成功！
2021-12-14 16:24:27,079 [XNIO-1 I/O-4] INFO i.m.websocket.c.to.c.IndexWebSocket ? - 服务器收到：[send.70493ff6] : {"content":"","reportId":"send.70493ff6","toReport":"70493ff6"}
v1.13.2：
![image](https://user-images.githubusercontent.com/48941561/150939580-d7548230-a96f-4cf1-a186-3b6160740b84.png)

简要描述您碰到的问题

**Bug 重现步骤**

1.msctl upgrade一键升级版本 or 一键部署最新的版本
2.执行已有的接口用例

**期待的正确结果**
2.正常耗时

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
未绑定hosts
![image](https://user-images.githubusercontent.com/48941561/150939653-30a8cc99-1d19-44f5-b092-800cfee4c26a.png)

绑了hosts耗时很稳定15s+
![image](https://user-images.githubusercontent.com/48941561/150939733-96367e59-c559-4ee1-91a8-e00b8607a785.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
您好，请问您的场景是1个请求用了15s吗

**Comment by 85899608** [comment]
是的，一个接口的耗时，之前已经确认了的，参照：https://github.com/metersphere/metersphere/issues/8466

**Comment by 85899608** [comment]
![image](https://user-images.githubusercontent.com/48941561/151306679-b1cb3385-1851-40f0-8943-a1bc846f5cd3.png)

**Comment by zyyfit** [comment]
嗯嗯，我当时是用的1.16.6版本测试了，没有复现，应该是已经修复了
1.17.0版本测试一个请求的场景是2-3s，开启host也是2-3s，您可以升级试试

**Comment by 85899608** [comment]
你用的是打好镜像的版本吗？目前升级到最新版本：v1.17.1还是这样。
未开启hosts：
![image](https://user-images.githubusercontent.com/48941561/152721095-6e295ac6-2e2b-4773-aae9-0a3e4c45dfcc.png)

开启hosts：
![image](https://user-images.githubusercontent.com/48941561/152721054-5e49141e-d6c6-4772-8d69-3d69d1bc1a26.png)

**Comment by zyyfit** [comment]
> 

是的，我用的就是github上下载的release的安装脚本安装或者升级的，你是用的master吗？你用host正常请求（不通过ms）响应时间是正常的吗？

**Comment by 85899608** [comment]
是master
![image](https://user-images.githubusercontent.com/48941561/152765200-da2a5ded-df99-49b9-88bf-6f1bc5eda8fd.png)

部署服务器使用jmeter带hosts响应时间正常
![image](https://user-images.githubusercontent.com/48941561/152764719-64c72d91-2df1-4101-9020-c66c38c33666.png)

**Comment by zyyfit** [comment]
> 是master ![image](https://user-images.githubusercontent.com/48941561/152765200-da2a5ded-df99-49b9-88bf-6f1bc5eda8fd.png)
> 
> 部署服务器使用jmeter带hosts响应时间正常 ![image](https://user-images.githubusercontent.com/48941561/152764719-64c72d91-2df1-4101-9020-c66c38c33666.png)

您好，我们这边确实没有复现，您可以在我们的企业微信交流群里联系一下我们的工作人员帮你看一下

**Comment by qipeng-li** [comment]
我碰到了同样的问题，接口测试稳定15s才得到返回，我通过抓包发现了ms的主机会去发送一个DNS报文请求，请求我配置的hosts的IP的A记录。我在两个不同的host环境中尝试：1个环境回复了这个DNS报文，因此没有15s延迟，很快就返回了。另外一个环境不会回复这个DNS报文，导致ms发送3次DNS报文，每次5s超时后，最终才建立TCP连接，所以需要15s+的耗时
![b01f0b15bb09bbc125e1e779ca0c4fa](https://user-images.githubusercontent.com/34180511/156683048-9ae6c5a5-d216-464e-bd0f-b82e7128fa81.jpg)
![00a23ead59007ab9731d9c70a1f2bb2](https://user-images.githubusercontent.com/34180511/156683152-3ceea57c-9798-4c88-a6f3-7cb27a865422.jpg)

**Comment by likely0755** [comment]
确实有这个问题，试了v1.18.0，v1.18.1还存在这个问题，不知道什么时候能修复，新版本能不能不发送dns报文，感觉没有发送的必要。
