### ISSUE TITLE
[QUESTION]如何创建关联jira系统的自定义字段，单选下拉框的值如何从jira拉取？

### ISSUE THREAD

**Issue by aragonqu** [metersphere/metersphere#10057]
**请描述您的问题.**
如何创建关联jira系统的自定义字段，单选下拉框的值如何从jira拉取？

**Comment by Hyyfit** [comment]
可以更新到1.17.1，目前已经实现了！
如果需要配置自定义字段，可以参考我们公众号的文章
https://mp.weixin.qq.com/s/QjwsImKG1zVUtnqMGOVrHg
