### ISSUE TITLE
[QUESTION]Jenkins  pipeline问题

### ISSUE THREAD

**Issue by hcw52592** [metersphere/metersphere#10056]
报错：
`workspace=/home/jenkins/agent/workspace/devsfmgn/metersphere
number=28
url=job/devsfmgn/job/metersphere/28/
[MeterSphere] 执行方式: single
[MeterSphere，代码测试]testCaseId=[7558daed-ac8b-4c58-a73d-13c4f72dbfa7]
[MeterSphere，代码测试]222场景测试发生异常:/api/automation/run/jenkins not found.
[MeterSphere] 该测试请求未能通过，登陆MeterSphere网站查看该报告结果`

pipeline流水线：
`node('base') {
    stage ('MeterSphere test') {
          meterSphere msEndpoint: 'http://192.168.125.128:31934/',
          msAccessKey: 'mArzC4agCLbCNQ8b',
          msSecretKey: 'spmIAdFvFVuLrUQ3',
          workspaceId: 'a640a256-7d83-11ec-8168-060842df50f1',
          projectId: '94819510-4331-41a2-a685-9b94c897ac4f',
          method: 'single',
          testCaseId: '7558daed-ac8b-4c58-a73d-13c4f72dbfa7',
          result: 'metersphere'
    }
}`

**Comment by Hyyfit** [comment]
可能是你的metersphere的版本跟jenkins版本不一致导致的，建议升级一下。
