### ISSUE TITLE
[BUG]给用户添加角色时，选择工作空间，会加载已经删除的工作空间

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#1007]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6
**Bug 描述**
简要描述您碰到的问题
给用户添加角色时，选择工作空间，会加载已经删除的工作空间

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/30932762/103163231-6a130f80-4836-11eb-885d-ec241518aeb8.png)
![image](https://user-images.githubusercontent.com/30932762/103163235-7f883980-4836-11eb-91e3-eac67abd0c63.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，没有复现该问题，请升级最新版本验证
