### ISSUE TITLE
chrome录制脚本 没有记录cookie信息

### ISSUE THREAD

**Issue by chenjienn** [metersphere/metersphere#10098]
chrome 版本  91.0.4472.77  x86_64

MeterSphere Recorder 版本 1.2.0  通过chrome应用商店安装

1. 在高级选项中勾选了http request和cookie 
2. 录制导出jmx文件
3. 将jmx文件导入jmeter
4. 在jmeter的Http Cookie Manager中没有相应的cookie信息  运行接口  返回401

**Comment by xulinde** [comment]
您好，最新插件版本是v1.2.4，您可以按图2步骤安装下
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/64065190/170932855-72311cac-7c33-4436-ad64-d5f1717f1563.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/64065190/170932774-02059d7b-f4c9-4072-9fbc-65c862fdcc3f.png">

**Comment by xulinde** [comment]
我用v1.2.4未复现该问题，建议您升级到最新版本
