### ISSUE TITLE
[BUG]采用excel导入自动生成的模块`test_case_node`表当中创建人字段为NULL

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#10091]
**MeterSphere 版本**

1.16.6

**Bug 描述**

采用excel导入自动生成的模块`test_case_node`表当中创建人字段为NULL

**Bug 重现步骤**

1.  功能用例导入
2. 导入成功，自动生成模块
3. `test_case_node`表当中创建人字段为NULL
4. 

**期待的正确结果**
这个模块的创建人不就是当前导入人么

**截图**

![image](https://user-images.githubusercontent.com/19423100/151089111-bf93d670-2d42-4953-ae86-213acac0f16c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，导入后web 显示和数据库中都查了，创建人如果是空，默认为导入人

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.1版本已修改
