### ISSUE TITLE
[FEATURE]角色为“测试员”的用例应禁用测试计划新增、关联/取消关联用例、指派权限

### ISSUE THREAD

**Issue by xmyemail** [metersphere/metersphere#101]
**MeterSphere 版本**
1.0.2

**Bug 描述**
角色为“测试员”的用例可以对测试项目/计划新增、关联/取消关联用例、用例指派编辑；

**Bug 重现步骤**
1.  使用“测试员”的角色账号登录MeterSphere ->测试跟踪；
2.  进行新增项目、测试计划、关联/取消关联用例；

**期待的正确结果**
作为测试员，他们的角色任务是执行计划，应禁用测试项目新增、计划新增、关联/取消关联、指派用例权限，否则反而会干扰管理人员的计划制定，或者说，如果遇到用例执行质量事故，本来是可以追溯到是谁测试的，但结果被人移除计划或改了指派人，那么这个是非常严重的系统漏洞；

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前在这部分功能权限各角色没有区别，我把这个 issue 标签改为需求了，待后续版本优化

**Comment by xulinde** [comment]
1.10版本已支持，自定义权限配置
