### ISSUE TITLE
环境配置中HTTP配置未生效

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1010]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决该问题，请升级验证
