### ISSUE TITLE
[BUG]测试计划报告里的 用例展示的顺序 应该按照 规划里的顺序展示，目前是乱的，还得回到测试计划里查看

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10108]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.6
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/30038088/151098016-e7945c1d-b8d7-44fe-a183-0d6fa0411092.png)

2. 
![image](https://user-images.githubusercontent.com/30038088/151098327-b5cf7690-0f1e-4bdc-a398-ff724076ad25.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。

**Comment by shenkaibo** [comment]
这个问题 解决了么
