### ISSUE TITLE
[BUG]测试计划里的“接口用例”和“场景用例”的“更新时间”实际是“最后一次执行时间”，应该改成“最后一次执行时间”

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10107]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.6
**Bug 描述**

简要描述您碰到的问题
1.测试计划里的“接口用例”和“场景用例” 无法编辑，所以 没有更新时间。
2.在测试计划里 单独执行 接口或者场景，这个 “更新时间” 是否应该 更新？
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，接口用例复现了，场景没有复现，场景是必现的吗
