### ISSUE TITLE
[BUG]缺少公用请求头部配置，供场景下所有接口调用

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1011]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6版本，新接口测试版本

**Bug 描述**
简要描述您碰到的问题
缺少公用请求头部配置，供场景下所有接口调用

**期待的正确结果**
场景中配置增加公共请求头部，供相同请求头部信息的接口调用，类似于旧的接口测试版本

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/69206282/103251782-46c29e80-49b5-11eb-8672-3fd1d95bd850.png

**Comment by wangzhen-fit2cloud** [comment]
v1.6.1 已解决
