### ISSUE TITLE
[BUG]导入录制的jemter脚本，报sql错误，后台日志为 Data too long for column 'name' ....

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#10116]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.16.4-07155cf8

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  导入录制好的jmeter脚本
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
日志报错：
[XNIO-1 task-1] ERROR i.m.c.h.RestControllerExceptionHandler ? - Method[sqlExceptionHandler][Data truncation: Data too long for column 'name' at row 1]
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by liuruibin** [comment]
能否提供录制后的文件，我们来调试看看

**Comment by zyyfit** [comment]
1.19.0已修复，今天发布
