### ISSUE TITLE
[BUG]HTTP接口Basic认证时，密码长度超过50位被截取，导致认证失败

### ISSUE THREAD

**Issue by LiuYj1994** [metersphere/metersphere#10113]
**MeterSphere 版本**

 v1.16.4-07155cf8

**Bug 描述**

通过postman,jmeter均可使用的账号密码，在平台使用时总是401，经排查发现是原密码为64位，在输入密码时被截取成50位。

**Bug 重现步骤**

1.  在需要使用Basic认证的接口进行接口测试；
2. 接口认证配置中`认证方式`选择`Basic Auth`;
3. 配置用户密码长度大于50位的用户账号密码；
4. 剩余接口参数及请求头正常配置；
5. 进行调用后发现未通过认证，401状态码。

**期待的正确结果**

接口应正常通过认证，密码不进行截取50位。

**截图**
![图片](https://user-images.githubusercontent.com/22275710/151099987-a52f6beb-5954-49a0-9027-29dc2a89b5c7.png)
![图片](https://user-images.githubusercontent.com/22275710/151099996-b61fca8a-ee82-4fb8-9b21-19f6535198d1.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化这里

**Comment by zyyfit** [comment]
1.17.2已修复
