### ISSUE TITLE
[FEATURE] 建议对mock增加开关不判断请求触发条件、或者对请求的参数值不进行校验，直接返回mock响应消息

### ISSUE THREAD

**Issue by igotyouu** [metersphere/metersphere#10129]
**请描述您的需求或者改进建议.**
mock的POST请求触发条件，请求体一定要每个参数和值都要一样，才能被调用到吗？不一样就404 ，这样太麻烦了，每写一个接口测试用例，就要写一个对应的mock吗，或者很多时候只是想用一下它的mock响应功能，不需要让它校验我的请求参数，给我返回就行了。
（可不可以不判断请求触发条件、或者对请求的参数值不进行校验，直接返回mock响应消息）

**请描述你建议的实现方案**
在mock配置请求触发条件时，建议增加开关勾选不判断请求触发条件、或者对请求的参数值不进行校验，直接返回mock响应消息

**Comment by Hyyfit** [comment]
感谢反馈，已规划排期，近期会有优化。

**Comment by igotyouu** [comment]
收到

**Comment by luty2018** [comment]
已上线

**Comment by igotyouu** [comment]
收到
