### ISSUE TITLE
[FEATURE]接口定义，接口列表，每个接口右侧增加调试按钮，方便于调试和单接口测试

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1012]
**请描述您的需求或者改进建议.**
接口定义，接口列表，每个接口右侧增加调试按钮，方便于调试和单接口测试

**请描述你建议的实现方案**
接口定义，接口列表，每个接口右侧增加调试按钮，方便于调试和单接口测试
![image](https://user-images.githubusercontent.com/69206282/103251899-c05a8c80-49b5-11eb-82a8-d68a77b12323.png)

**Comment by xulinde** [comment]
v1.8已实现
