### ISSUE TITLE
[BUG]swagger导入接口时，导入的参数类型对不上

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10136]
**MeterSphere 版本**

V1.16.6

**Bug 描述**

简要描述您碰到的问题

swagger导入接口时，导入的参数类型对不上,swagger上的类型为file,导入到MS之后就变为text

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/32027713/151121178-7c8ce57a-862f-4ed5-8b62-a6a2858eb120.png)

swagger上原始截图：
![image](https://user-images.githubusercontent.com/32027713/151121234-20202ff2-01a0-4643-991a-1e5d613e613f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.2已修复
