### ISSUE TITLE
[FEATURE]新版接口定义，调试接口时，可以调用场景中配置的各类变量

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1013]
**请描述您的需求或者改进建议.**
新版接口定义，调试接口时，可以调用场景中配置的各类变量

**请描述你建议的实现方案**
新版接口定义，调试接口时，可以调用场景中配置的各类变量

**Comment by wangzhen-fit2cloud** [comment]
v1.6.1 已解决
