### ISSUE TITLE
新版接口定义去除限制保存相同请求地址

### ISSUE THREAD

**Issue by LEE-lucky** [metersphere/metersphere#1014]
**请描述您的需求或者改进建议.**
我们这边的接口都是请求同一个地址，希望能去掉该限制
![image](https://user-images.githubusercontent.com/56376764/103253217-331a3680-49bb-11eb-8e5c-b3a5607c9681.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，可以先在这个接口下创建不同用例来规避下该问题哈

**Comment by wangzhen-fit2cloud** [comment]
你好，在 v1.6.2 版本中增加配置项
![image](https://user-images.githubusercontent.com/27671436/103747336-728cf680-503d-11eb-8e6d-895ee914376d.png)
可以在编辑项目信息页面控制地址是否可重复
