### ISSUE TITLE
[BUG]接口测试模块，采用键值对的方式提交请求时，如果参数值为空，metersphere发送出去的参数值有误。

### ISSUE THREAD

**Issue by wyp110lq** [metersphere/metersphere#10153]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V16.6

**Bug 描述**

接口测试模块，采用键值对的方式提交请求时，如果参数值为空，metersphere发送出去的参数值有误。
应该是带了特殊字符，比如回车符。

**Bug 重现步骤**
无

**期待的正确结果**
不带其他字符，这样会导致请求发出去的时候，外部系统处理错误。

正确情况下应该是什么样的？
不带其他字符，这样会导致请求发出去的时候，外部系统处理错误。

**截图**

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请上传截图看看吧

**Comment by wyp110lq** [comment]
勾上空值的键，然后发送请求。ms处理的时候，应该是为空的参数赋了特殊字符值，导致查询请求返回的结果就不正确了。

你可以这样复现，弄一个查询请求，有些请求参数为空的情况下，发送下这个请求，然后勾选为空的参数发送，返回的结果和不勾选为空的参数返回的结果是不一样的。

![QQ图片20220128091039](https://user-images.githubusercontent.com/40833400/151469446-6ab4bdbe-7b92-41b7-9dc0-3c24a5d8c080.jpg)

**Comment by zyyfit** [comment]
您好，能截图一下请求内容吗？像这样
![图片](https://user-images.githubusercontent.com/73461316/151526542-decd6bb5-d284-4311-8f83-072a93a5eac5.png)
