### ISSUE TITLE
[BUG]修改完install.conf中的数据库密码和服务器端口，安装后仍然是默认的配置信息

### ISSUE THREAD

**Issue by NewBigBug** [metersphere/metersphere#1015]

**Comment by LimonFHM** [comment]
emmm，执行一下：source install.conf

**Comment by wangzhen-fit2cloud** [comment]
你好，如果是之前有安装过的话，需要修改下 /opt/metersphere/.env 文件中的配置

**Comment by 1312655689** [comment]
mac系统的.env路径地址在：/System/Volumes/Data/Users/{username}/metersphere/.env。
如修改密码前容器已经创建，需要将容器删除后重新创建，否则不会生效。
