### ISSUE TITLE
[BUG]定时同步，连续添加定时任务，导入模块没有保存到

### ISSUE THREAD

**Issue by jackelchen** [metersphere/metersphere#10172]
**MeterSphere 版本**
v1.16.6-637a179f  demo可复现

**Bug 描述**
连续添加多个定时任务到同一个模块，从第2个任务开始页面显示之前选中过的模块，保存后模块是空

**Bug 重现步骤**

1.  新打开定时同步tab添加一个url到模块/11111，保存
2. 页面显示模块还是/111111,添加第2个url，保存
3. 关闭定时同步tab再打开（必须），选第二个任务，模块显示空
4. 

**期待的正确结果**
1.保存时页面显示是自定义模块，保存时应该存成自定义模块
2.切换不同任务点击编辑，切到模块是空的定时任务时，模块显示的是上一个任务的模块

**截图**
![image](https://user-images.githubusercontent.com/15845086/151150927-14e247f0-5a4b-48d8-820f-22617a639ae0.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.1版本已修复
