### ISSUE TITLE
[BUG]从MS提交缺陷至禅道时，上传的图片未能在禅道上正确预览显示，请修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10174]
**MeterSphere 版本**

v1.16.6-637a179f

禅道版本：开源版15.5

**Bug 描述**

从MS提交缺陷至禅道时，上传的图片未能在禅道上正确预览显示，请修复
(备注：为已修复bug再次复现，请确认是否代码被覆盖)

**截图**

![9b8db4dd4e5591ff750f75bd48b67c6](https://user-images.githubusercontent.com/92150453/151152001-5019feb2-aab4-4bf1-9a90-b0dfc0884991.png)
![b3de8889640558b2f7e97e80b21cca1](https://user-images.githubusercontent.com/92150453/151152014-e9bd49b8-bcf3-4e1c-bebb-177c969ab1cf.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.2已修复
