### ISSUE TITLE
[BUG]删除模块及模块下的接口，接口到回收站里，从回收站恢复后，接口只恢复到“未规划接口”得模块里，而之前的模块并未恢复

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10187]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.6
**Bug 描述**

简要描述您碰到的问题
导致后果：
环境里的url 大多按照模块划分，模块下有好多层级，接口恢复后，模块并未恢复，导致之前 维护的模块层级和环境配置 都失效了

**期待的正确结果**

建议用逻辑删除，能够按照 原模块路径进行 恢复，如果出现同名的模块，则提示 是否覆盖（参考 mac 目录删除和恢复）

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
模块并没有做回收站功能，所以如果模块呗删除了，接口恢复的时候找不到模块，只能恢复到未规划模块下
