### ISSUE TITLE
[BUG]接口测试，添加文档断言，检验字段类型，是否必填不准确。响应json数据中包含jsonArray对象中的字段值无法检验。

### ISSUE THREAD

**Issue by kakawaa** [metersphere/metersphere#10194]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.16.5-57db8ebd

**Bug 描述**

简要描述您碰到的问题
接口测试，添加文档断言后构想检验字段类型，是否必填不准确。响应json数据中嵌套jsonArray对象中的字段值无法检验。
**Bug 重现步骤**
响应数据
{
    "result": "success",
    "data": [
        {
            "id": "1486267202672730114",
            "valid": 1,
            "creationTime": 1643188689000,
            "creator": "0",
            "modifiedTime": 1643188689000,
            "modifier": "0",
            "projectId": "Pj7890112334",
            "code": "msshieldMaterial",
            "name": "外壳材质",
            "aliasCode": "ShieldMaterial",
            "aliasName": "外壳材质",
            "classCode": "ACCCWT",
            "groupCode": "SJZDV3",
            "category": "STATIC",
            "firstTag": "技术参数",
            "secondTag": "外壳",
            "priority": "R",
            "inputMode": "D1",
            "dataType": "ENUM",
            "isMultiple": false,
            "isRegion": false,
            "dataSource": [
                {
                    "code": "1",
                    "name": "不锈钢"
                },
                {
                    "code": "2",
                    "name": "塑料"
                },
                {
                    "code": "99",
                    "name": "其他"
                }
            ],
            "remark": "ms",
            "subFlag": false,
            "weakPoint": false,
            "showOrder": 60,
            "sourceFrom": 0
        }
    ],
    "count": 1
}
1.  检验dataSource数组对象中的字段值
2.  勾选响应数据中检验字段类型，是否必填
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.2已修复
