### ISSUE TITLE
[BUG]进行版本对比后，关闭对比窗口，当前场景用例的请求参数栏无法进行编辑，功能实现不合理，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10216]
**MeterSphere 版本**

v1.17.0-31b25364

**Bug 描述**

进行版本对比后，关闭对比窗口，当前场景用例的请求参数栏无法进行编辑，功能实现不合理，建议优化

**截图**
![f05cf3f3a700d51f11cbdbf1aff783d](https://user-images.githubusercontent.com/92150453/151473056-c5a391b8-ad53-4ea5-ac4d-29008ecc7a67.png)
![d8d2a9abb69ec6d32bdb6fba3365280](https://user-images.githubusercontent.com/92150453/151473066-6b2f8145-99ed-4814-aafa-3a066b21dd5f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.1版本已修复
