### ISSUE TITLE
[BUG]测试跟踪-脑图，无法打标签，点击标签，进去后是 备注、前置条件、测试步骤、预期结果

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10213]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/30038088/151348079-28bf9afd-15bd-4661-b149-625be2ed52db.png)
2. 
![image](https://user-images.githubusercontent.com/30038088/151348153-5ba5e320-4203-4a2f-b4f5-d8d9b7655d1f.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.0修改了这个问题，右键标签还是只有4个，但是可以用了，请等1.18.0发布后验证
