### ISSUE TITLE
[BUG]接口自动化场景做调试时，调试成功后循环的结果无法正常显示出来

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10219]
**MeterSphere 版本**
1.17
您所使用的 MeterSphere 版本是？
1.17
**Bug 描述**
接口自动化场景做调试时，调试成功后循环的结果无法正常显示出来

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口自动化场景做调试时，调试成功后循环的结果无法正常显示出来
2. 但是在列表里面执行可以看到执行结果
3. 调试历史里面也可以看到结果
4. 

**期待的正确结果**
接口自动化场景
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![1](https://user-images.githubusercontent.com/83771182/151485165-f035cabc-84f5-4934-b676-bee4d0a72f47.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您的环境里有设置什么操作吗？
![图片](https://user-images.githubusercontent.com/73461316/151512877-44aab0a3-f601-4b0b-a9c8-c12bb74beee1.png)

**Comment by zyyfit** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
