### ISSUE TITLE
[BUG]接口自动化中，对上一个接口进行提参并生成全局变量后，在下一个接口引用该变量，发现引用的参数值不是当前的全局变量值，仍为上一次的全局变量值，功能实现有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10217]
**MeterSphere 版本**

v1.17.0-31b25364

**Bug 描述**

接口自动化中，对上一个接口进行提参并生成全局变量后，在下一个接口引用该变量，发现引用的参数值不是当前的全局变量值，仍为上一次的全局变量值，功能实现有误，请修改

**Bug 重现步骤**

1.  提取JMS登录接口的id值为A，并生成全局环境变量，在下一个接口进行引用；
2.  更改提取JMS登录接口的id值为B，并更新该全局环境变量，在下一个接口进行引用；
3.  查看下一个接口中请求内容的id变量值；

**期待的正确结果**

3. 下一个接口中请求内容的id变量值为最新值：B。

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/92150453/151481542-dc017e30-4460-4731-be5d-d0465b36d585.png)
![image](https://user-images.githubusercontent.com/92150453/151481581-18de488b-7778-4ccd-90f3-4f91c3d6b3a2.png)
![image](https://user-images.githubusercontent.com/92150453/151481636-54219f73-e9ca-4133-99bf-7f6846705001.png)

**Comment by zyyfit** [comment]
您好，我们设置环境参数的模板是这样的 
vars.put(${__metersphere_env_id}+"key","value");
vars.put("key","value")

因为我们在当前场景执行完才会更新环境变量，所以场景内引用的话需要带着下面那一行
