### ISSUE TITLE
[BUG]同一个接口，请求报文使用固定值可请求成功，使用${}参数的话请求失败，结果请求时用了转义

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10237]
**MeterSphere 版本**
1.17
您所使用的 MeterSphere 版本是？
1.17
**Bug 描述**

简要描述您碰到的问题
同一个接口，请求报文使用固定值可请求成功，使用${}参数的话请求失败，结果请求时用了转义
**Bug 重现步骤**

1.  同一个接口，请求报文使用固定值可请求成功
2. 使用${}参数的话请求失败，接口请求时用了转义
3. 参数取值是正确的
4. 报文见附件
**期待的正确结果**
使用${}参数做为报文也能成功

正确情况下应该是什么样的？
使用参数的报文也可请求成功
**截图**

如果有截图，请附上截图.
[接口成功的报文.txt](https://github.com/metersphere/metersphere/files/7957330/default.txt)
[接口请求报错报文.txt](https://github.com/metersphere/metersphere/files/7957332/default.txt)

**Comment by youliyuan-fit2cloud** [comment]
你好，上传请求体的截图，你这个附件是请求结果。
