### ISSUE TITLE
[FEATURE]用例执行时关联已存在bug增加搜索功能

### ISSUE THREAD

**Issue by jinsm01** [metersphere/metersphere#10232]
**请描述您的需求或者改进建议.**

用例执行过程中关联已存在bug，已存在bug弹窗显示bug无序，需要一个个翻页查找。

**请描述你建议的实现方案**

关联已存在bug，已存在bug弹窗增加搜索功能，已存在bug排序可以有规律

**Comment by Hyyfit** [comment]
已规划，待排期。
