### ISSUE TITLE
[BUG]接口用例覆盖率和被场景覆盖率不能跳转筛选到未覆盖接口列表

### ISSUE THREAD

**Issue by xuweiming926** [metersphere/metersphere#10248]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/29728103/151645686-3e81d08a-84fe-4467-8af3-9d951143df11.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
可以统计到并跳转
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，暂时没有这个功能
