### ISSUE TITLE
[BUG]用例评审评论展示错乱

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#10249]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.6
**Bug 描述**
在用例评审时各相关人员评论信息会随着”通过’与“不通过”状态改变查看到的评论混乱
简要描述您碰到的问题

**Bug 重现步骤**

1.  选择一个功能用例
2. 各相关人员填写评论
3. 点击”通过’与“不通过”时评论信息混乱

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下

**Comment by ltfit** [comment]
1.18.1已修复
