### ISSUE TITLE
[BUG]场景变量里面批量添加变量，变量参数在请求时会有/r回车

### ISSUE THREAD

**Issue by xuweiming926** [metersphere/metersphere#10245]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
[BUG]场景变量里面批量添加变量，变量参数在请求时会有/r回车
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请详细说明以下信息：
1.使用版本
2.场景变量的参数，在哪里引用该参数
3.执行结果的请求体和请求结果的截图信息
谢谢~
