### ISSUE TITLE
功能用例查看前后依赖关系报错

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#10250]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.6
**Bug 描述**

简要描述您碰到的问题
创建功能用例时  点击依赖关系时报500错误
**Bug 重现步骤**

1.  点击创建功能用例
2.进入编辑页面后点击依赖关系
3. 点击依赖关系图形 报500错
<img width="1156" alt="截屏2022-01-29 下午12 37 29" src="https://user-images.githubusercontent.com/34637801/151647456-6086782e-3c3b-4217-b4b8-30626867a2fc.png">

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by tzlaosiji** [comment]
好勤劳呀
![图片](https://user-images.githubusercontent.com/57123392/151648298-40524cfc-69e1-4721-877a-59e51d78eef2.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.16.6版本没有复现，清下缓存？再试试？再不行把log发贴上，我们看看

**Comment by ltfit** [comment]
感谢反馈。下个版本 会优化此问题

**Comment by pengzhengyou** [comment]
问题还是存在1.18.0版本
<img width="1285" alt="截屏2022-02-25 下午5 12 52" src="https://user-images.githubusercontent.com/34637801/155688138-b42e7d2a-1f7b-49a3-a0c8-70d9bf75f20d.png">

**Comment by ltfit** [comment]
你好 v1.18.2 已修复此问题
