### ISSUE TITLE
[BUG]场景转性能测试中的前置脚本中没执行http请求

### ISSUE THREAD

**Issue by will0306** [metersphere/metersphere#10261]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.16.2-0b7d1ab8
**Bug 描述**

简要描述您碰到的问题
性能测试中脚本发送http请求失败
![image](https://user-images.githubusercontent.com/13373661/151665020-07c645bc-bf84-4e67-8605-831d2076bccb.png)
![image](https://user-images.githubusercontent.com/13373661/151665014-285d9153-c758-4d12-9241-61efca79025d.png)

**Bug 重现步骤**

1.  场景中新建前置脚本
2. 从前置脚本的语言中选择python
3. API测试->从API定义导入
![image](https://user-images.githubusercontent.com/13373661/151665067-9d006231-fefc-475e-aa33-d1048ce343fc.png)
4. 保存->场景列表->创建性能测试
![image](https://user-images.githubusercontent.com/13373661/151665109-4ff85be2-9e57-448c-a8f8-04ca019d0b96.png)

会发现前置脚本中没执行http请求，可能是python环境缺少依赖，但是在场景、接口定义中测试是没问题的

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本解决这个问题

**Comment by liuruibin** [comment]
我的脚本如下
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/23045261/153143643-8d6da420-e68a-496b-9238-908a7872be79.png">
转出性能测试
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/23045261/153143762-c6c4b6c6-db7c-4682-92d6-7f9859148151.png">
前置脚本执行了

**Comment by will0306** [comment]
docker版本的有没有最新的

**Comment by zyyfit** [comment]
> docker版本的有没有最新的

您如果方便升级系统的话，可以直接执行metersphere的升级命令给整个系统升级
