### ISSUE TITLE
[BUG]性能测试引用自动化场景或者 场景转性能，会 格式化前后置脚本，如果脚本中有注释的话，格式化后 换行 导致脚本报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10263]
**MeterSphere 版本**
V1.17
您所使用的 MeterSphere 版本是？
V1.17
**Bug 描述**

简要描述您碰到的问题

正常脚本
![wecom-temp-3254ad77ef11fa413f81ac046d5033d8](https://user-images.githubusercontent.com/30038088/151689207-728f6505-51bb-4938-bb2d-177fea7c86c5.png)

转性能之后的脚本
![wecom-temp-1995bbe39446f7a54e78b5a7507faa22](https://user-images.githubusercontent.com/30038088/151689130-93c9fbee-06bf-4bbc-936d-69879b3539da.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
@liuruibin

**Comment by youliyuan-fit2cloud** [comment]
后续版本解决这个问题
