### ISSUE TITLE
自动化接口测试： 希望每个场景都可加入到测试计划中，然后在测试计划上设置定时任务，避免重复操作。

### ISSUE THREAD

**Issue by shI799654555** [metersphere/metersphere#1026]
**请描述您的需求或者改进建议.**
自动化接口测试： 希望每个场景都可加入到测试计划中，然后在测试计划上设置定时任务，避免重复操作。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，平台目前已经实现了这两个功能，测试计划可以导入场景用例，并且可以设置定时任务，您可以升级到最新版本体验下
