### ISSUE TITLE
[BUG]接口用例中定义多个断言，结果不正确

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1027]
**MeterSphere 版本**
 1.6

**Bug 描述**
接口用例中，定义2个断言。运行该用例，第一个断言失败，第二个断言成功，展示出来的结果为成功

**期待的正确结果**
应该要展示成失败

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.6.2 中已解决该问题，请升级验证
