### ISSUE TITLE
[BUG]在任务中心查看场景报告，报告展示后，任务列表变成空白

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10286]
**MeterSphere 版本**

1.17.1

**Bug 描述**

![image](https://user-images.githubusercontent.com/88763608/152767041-119ad33a-4bc1-4a4a-9808-a741dae4f7a6.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，不清楚你的问题。。。任务列表哪里变空白了？截图看看吧

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这问题，，你是必现的吗？
