### ISSUE TITLE
[BUG]服务集成>>个人信息设置中：TAPD个人信息少了校验按钮，并且最下有关禅道配置位置与部分没有对齐。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10280]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  服务集成>>个人信息设置中：TAPD个人信息少了校验按钮，并且最下有关禅道配置位置与部分没有对齐。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/152731706-b4611d93-096a-45bf-adee-dcfb6b034e97.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
问题1:tapd设计如此，tapd的昵称不需要校验
问题2：后续优化下

**Comment by zyyfit** [comment]
1.18.0已优化
