### ISSUE TITLE
[FEATURE]【测试跟踪】-【缺陷管理】中根据条件筛选

### ISSUE THREAD

**Issue by zhangjarvis** [metersphere/metersphere#10283]
**请描述您的需求或者改进建议.**
【缺陷管理】功能中希望加入根据创建人、缺陷来源、优先级、处理人、严重程度、状态这些条件进行筛选，方便查看目前bug修改进度

**请描述你建议的实现方案**
能够下拉选择本条件的相关选项，可支持多状态筛选

**Comment by Hyyfit** [comment]
已规划，待排期
