### ISSUE TITLE
[BUG]查看某项测试结果后，接口列表的状态不应该改变

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1028]
**MeterSphere 版本**
1.6

**Bug 描述**
1，接口列表中，增加用例
2，选择好运行环境
3，点击用例的执行按钮，用例会开始执行。
4，执行结束后，点击结果查看，会弹出启动并进入快捷调试页面。
5，点击接口列表，展示是整个列表初始界面。
没有了刚才点击结果的状态，如果我还需要对刚才修改的位置继续修改，会要很多步操作。如果接口有几百个的时候，估计要找到接口也会比较困难。

**期待的正确结果**
保持查看测试结果时的状态。

**Comment by wangzhen-fit2cloud** [comment]
@luty2018 罗老师看下这个吧

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
