### ISSUE TITLE
[BUG]接口自动化--场景用例调试没有展示每条用例的调试结果

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#10295]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**
问题1：接口自动化--场景用例调试没有展示每条用例的调试结果
问题2：接口自动化---运行场景用例，场景用例没有运行
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/18163887/152908898-b7f5ff30-4ba8-4e6a-9bc6-f154f2fda7c4.png)
![image](https://user-images.githubusercontent.com/18163887/152909162-d0a5a2bf-c344-4f4d-8a9a-fdfbfdcc21ed.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把可以复现的场景和场景使用的环境导出来给我们看看吗

**Comment by fangqiuhong** [comment]
重启平台后，问题得到解决，谢谢
