### ISSUE TITLE
[BUG]当性能请求返回数据过大，构建触发后获取的报告地址无法正常打开

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10297]
**MeterSphere 版本**

1.10.8-lts

**Bug 描述**

当性能请求返回数据过大，使用jenkins构建触发后获取的报告地址无法正常打开

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
最新版lts是1.10.11，可以升级到1.10.11试试，如果还不行的话，可以把返回数据贴给我们看看
