### ISSUE TITLE
[BUG] 数值断言结果不正确，请修复

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#10293]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4

**Bug 描述**

简要描述您碰到的问题
返回结果里是0.04，断言设置是大于-1，应该是断言通过的，但实际时段失败了

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![lALPJwY7RbGLodPNAyXNBv4_1790_805](https://user-images.githubusercontent.com/86302975/152899610-3ff116c8-9471-4f05-82aa-f72d8a1c728d.png)

**Comment by qingmu2633** [comment]
![lALPJwnIxFZTvb3NAabNBsQ_1732_422](https://user-images.githubusercontent.com/86302975/152899625-88b08355-87b2-4138-ad97-782c00287cb2.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个版本修复这个问题

**Comment by zyyfit** [comment]
1.18.0已修复
