### ISSUE TITLE
[FEATURE]已执行过的Case中，增加非Pass的状态高亮显示

### ISSUE THREAD

**Issue by xmyemail** [metersphere/metersphere#103]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
Case集成度较高时，一个Case会包含很多检查点，当其中一个被标记为失败、阻塞、跳过时，非Pass的的检查点会有高亮提醒，在审查这些已执行用例时，由于没有颜色标记，得一个一个不步骤去审查问题在哪个步骤出现的，很不方便；
建议加一些高亮提醒，例如圆点；

![r](https://user-images.githubusercontent.com/67886923/86752213-c78d8700-c071-11ea-8b9f-841ce215bf0b.png)

**Comment by youliyuan-fit2cloud** [comment]
您好，暂时没有计划优化这个功能，请您持续关注～
