### ISSUE TITLE
[BUG] jenkins插件，流水线语法生成器生成的脚本执行报错。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#10302]
插件和主程序 都是  1.17.1
、
![企业微信截图_16442901301757](https://user-images.githubusercontent.com/44999044/152924476-4ef97fe9-d99c-4ab8-878b-5621eed8e17f.png)

**Comment by zyyfit** [comment]
您好，您的jenkins是在哪个位置写的什么脚本呢？方便截图给我们看看吗

**Comment by LimonFHM** [comment]
![image](https://user-images.githubusercontent.com/44999044/153097080-093cc762-c725-413a-be50-b8d7e9ed6b30.png)

**Comment by LimonFHM** [comment]
> 您好，您的jenkins是在哪个位置写的什么脚本呢？方便截图给我们看看吗

![image](https://user-images.githubusercontent.com/44999044/153097101-e09b4645-af9a-46ef-888a-009be4f6173a.png)

**Comment by LimonFHM** [comment]
![企业微信截图_16442892348401](https://user-images.githubusercontent.com/44999044/153097170-b6e8f09d-ad01-4a35-abe4-facb498c5de6.png)
![企业微信截图_16442890921718](https://user-images.githubusercontent.com/44999044/153097185-04b4955a-6a68-4aa3-87a5-56309a09333c.png)

**Comment by liuruibin** [comment]
原因是生成脚本后有几个参数没有设置上值导致的，经过调试可行的参数如下：
meterSphere method: 'single', mode: 'serial', msAccessKey: '3gpEjhu6adu5wVJK', msEndpoint: 'http://192.168.200.96:8081', msSecretKey: 'hFtW23PNz2IiRwRg', projectId: '24f84276-888a-11ec-93f1-0242ac1e0a02', resourcePoolId: '', result: 'jenkins', testCaseId: 'b1cbf7eb-375b-4e46-a093-46162dbf8645', testPlanId: '', testPlanName: '', workspaceId: '24f7eaab-888a-11ec-93f1-0242ac1e0a02', logger: null, testId: '',testCaseNodeId:''

**Comment by zyyfit** [comment]
1.18.0已修复
