### ISSUE TITLE
[BUG] 关联禅道后，执行创建缺陷报错

### ISSUE THREAD

**Issue by gcoder5** [metersphere/metersphere#10315]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？v1.17.1

**Bug 描述**

简要描述您碰到的问题
我关联了禅道（版本：15.4），然后点击创建缺陷，报错

**Bug 重现步骤**

1.  在系统设置--服务集成设置禅道的地址和账号密码
2. 在测试跟踪--缺陷管理--创建缺陷，报错
3. 在测试跟踪--缺陷管理--同步缺陷，无反应
4. 

**期待的正确结果**

正确情况下应该是什么样的？正常同步与创建

**截图**
![image](https://user-images.githubusercontent.com/55041518/152954120-a59b066a-9d24-4197-a74c-a4b4122b0099.png)
如果有截图，请附上截图.

**Comment by swmachine1401** [comment]
> 您好，没有复现这个问题，您的禅道上是不是设置了什么必填字段，而ms模版里没有设置呢？

您好，我这里也有这个问题，我是一个空的禅道项目，新建缺陷也是报这个错

**Comment by zyyfit** [comment]
> > 您好，没有复现这个问题，您的禅道上是不是设置了什么必填字段，而ms模版里没有设置呢？
> 
> 您好，我这里也有这个问题，我是一个空的禅道项目，新建缺陷也是报这个错

您的禅道缺陷创建的时候，都有哪些必填字段？在ms平台的缺陷模板里设置的字段是完整的吗？
