### ISSUE TITLE
[BUG]接口返回结果中提取参数，当返回结果中就没有这个字段时，提取出来的参数没法判空

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#10318]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4
**Bug 描述**

简要描述您碰到的问题

接口返回结果中提取参数，当返回结果中就没有这个字段时，提取出来的参数没法判空

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![QQ图片20220208181109](https://user-images.githubusercontent.com/86302975/152966717-21d4e1cc-46b3-4e30-a1a4-bf3bd881f263.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，可能是提取不到的变量都当作 “” 处理了，我加了这个看起来是正常的
![图片](https://user-images.githubusercontent.com/73461316/152971792-3583b2e0-5163-4c2a-9dc9-6a0f4bcf1b15.png)
