### ISSUE TITLE
希望支持类似CSV设置变量，重复执行接口

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1032]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你们现在有在使用 JMeter 吗？

**Comment by AshuaiNe** [comment]
偶尔用，该功能还是蛮实用的。方便大量数据调用接口




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 晚上6:19
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "2818820548"<2818820548@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] 希望支持类似CSV设置变量，重复执行接口 (#1032)





 
你好，请问你们现在有在使用 JMeter 吗？

**Comment by wangzhen-fit2cloud** [comment]
请问在 JMeter 里该场景是怎么用的？ 配置 csv 文件，然后线程组配置多个并发吗？

**Comment by AshuaiNe** [comment]
https://www.cnblogs.com/leebaul/p/10986910.html


大部分会用在性能测试中，但有时候需要批量读取数据，重复执行某接口时，也能用上（好处：无需重复手动添加参数及接口）






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 晚上6:43
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "2818820548"<2818820548@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] 希望支持类似CSV设置变量，重复执行接口 (#1032)





 
请问在 JMeter 里该场景是怎么用的？ 配置 csv 文件，然后线程组配置多个并发吗？

**Comment by xulinde** [comment]
新版本已实现
