### ISSUE TITLE
[FEATURE]缺陷和jira打通不友好

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#10324]
**请描述您的需求或者改进建议.**
1，jira中有很多自定义的字段，例如模块、优先级、经办人等，需要手工把这些字段全部加入到metersphere中，且每个字段的具体值的id也需要手动添加到metersphere中，工作量巨大，且后续jira更新字段，metersphere也需要手动更新
2，jira中很多缺陷是挂在需求下面的例如问题连接、子任务等，这块metersphere应该也是不能实现的
3，jira中的活动日志 注释、工作日志等也没办法同步到metershpere
4，jira中新建的缺陷不能主动同步到metersphere中

**Comment by hefeixiao** [comment]
> phere

第4点，他们收费的企业版有实现，即使这样也不太友好，兄弟，要么自己实现，贡献下经验？

**Comment by Hyyfit** [comment]
第1点，目前已经实现了，可以更新到1.17.1体验，具体的设置方式可以关注我们的公众号文章：https://mp.weixin.qq.com/s/QjwsImKG1zVUtnqMGOVrHg
第2点，metersphere没有需求模块，所以这个功能目前没有规划
第3点，这个问题具体是想实现什么样的效果，可以加一下我，具体沟通一下。
第4点，我们的企业版已经实现了，可以在我们官网申请使用。

**Comment by libb-test123** [comment]
第一点，数据同步过来还是有问题，经办人这些数据同步过来缺失很多，而且不能选择
