### ISSUE TITLE
[BUG]项目设置下新增版本，描述信息太长会导致创建报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10328]
**MeterSphere 版本**

V1.17.1

**Bug 描述**

项目设置下新增版本，描述信息太长会导致创建报错，前端与后端没有加长度校验

**截图**

![image](https://user-images.githubusercontent.com/32027713/153135540-b17aa838-1a47-47a8-82e8-ba52eca77585.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复
