### ISSUE TITLE
[FEATURE]1.17 版本测试计划的定时任务的任务通知只能选择执行完成的类型通知很不合理，大部分情况下我们更需要有用例执行失败后才进行通知

### ISSUE THREAD

**Issue by tinychange** [metersphere/metersphere#10325]
**请描述您的需求或者改进建议.**
[FEATURE]1.17 版本测试计划的定时任务的任务通知只能选择执行完成的类型通知很不合理，大部分情况下我们更需要有用例执行失败后才进行通知，而且现在的通知只有一句文字，之前是会有链接可以直接跳转到执行结果的。
![image](https://user-images.githubusercontent.com/18136625/153114110-08da00c2-d919-4c22-baa0-c4d7499e6ca4.png)

**请描述你建议的实现方案**
建议任务通知类型中增加执行失败的类型（这个失败指的是有用例执行失败或者整个计划执行失败），另外推送的webhook信息中包含测试报告的链接

**Comment by Hyyfit** [comment]
已规划，待排期。
