### ISSUE TITLE
[BUG] 性能测试引入场景转化成jmx的时候将否定的断言错误转成肯定的

### ISSUE THREAD

**Issue by Betrayme** [metersphere/metersphere#10329]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  场景接口有"不等于”的断言
2. 性能测试引用场景
3. 转化成jmx的时候将否定的断言错误转成肯定的

**期待的正确结果**

正确情况下应该是什么样的？
正确转化否定的断言

**截图**

如果有截图，请附上截图.
![YEK~%R}(PQT9T(}MK30%B87](https://user-images.githubusercontent.com/41469910/153142229-238c2666-6af3-43b0-97f2-6c5b604ee9cc.png)
![8(F}B}GA_SXDF{QSKD@R$}B](https://user-images.githubusercontent.com/41469910/153142322-90efac75-9015-4225-8f81-4b267b01804f.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复，相关问题  https://github.com/metersphere/metersphere/issues/4550

**Comment by zyyfit** [comment]
1.19.0已修复，今天发布版本
