### ISSUE TITLE
[BUG]1.17.1对接jira提示问题类型、需求类型不存在

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#10326]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.1

**Bug 描述**

对接jira提示问题类型、需求类型不存在，上方报的是404，打开浏览器f12是报500（服务集成那里连接测试是成功的）
![ce6237b0b75877d70a8d18fdff95269](https://user-images.githubusercontent.com/66759501/153133695-19759997-e25f-4d14-a81e-e9044fc5f29a.png)

另外出于什么考虑将原先服务集成中的类型放到了环境管理这里？

**Comment by hefeixiao** [comment]
> **MeterSphere 版本**
> 
> 您所使用的 MeterSphere 版本是？1.17.1
> 
> **Bug 描述**
> 
> 对接jira提示问题类型、需求类型不存在，上方报的是404，打开浏览器f12是报500（服务集成那里连接测试是成功的） ![ce6237b0b75877d70a8d18fdff95269](https://user-images.githubusercontent.com/66759501/153133695-19759997-e25f-4d14-a81e-e9044fc5f29a.png)
> 
> 另外出于什么考虑将原先服务集成中的类型放到了环境管理这里？

看了下源代码，改到项目管理后，页面展示用的untranslatedName 字段，有些jira系统会是空的，我改成id就可以了

**Comment by jstbw** [comment]
在哪里改

**Comment by hefeixiao** [comment]
> id就可以了
建议你跟踪调试一下这段代码：
![image](https://user-images.githubusercontent.com/59219621/153359184-a64c0704-fc39-452e-95f5-cdc9ebaacf4b.png)


![image](https://user-images.githubusercontent.com/59219621/153358718-c5303134-a8d0-4b4f-b6be-24b05282281a.png)

另外就是在jira里面调一下这个接口：
https://{jira域名}/rest/api/2/issuetype，看下有没有untranslatedName字段
