### ISSUE TITLE
[BUG]用例评审页面，标题较长导致通过、未通过按钮换行；鼠标点击评论编辑框，左右两边页面宽度改变，表现为页面跳动

### ISSUE THREAD

**Issue by 18982185329** [metersphere/metersphere#10336]
**MeterSphere 版本**

版本:   v1.17.1-1ec9c7ce

**Bug 描述**

用例评审页面，标题较长导致通过、未通过按钮换行；鼠标点击评论编辑框，左右两边页面宽度改变，表现为页面跳动

**期待的正确结果**

1、标题长度改变，不影响通过、未通过按钮的位置；
2、鼠标点击评论输入框时，页面不会跳动；

**截图**

![~J 2R@EZ0~RTT~BVNB(5E@G](https://user-images.githubusercontent.com/74221859/153158819-4cb09bf0-dfa3-488c-bc16-a8c6e3f0c0c1.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
最新版1.20.4测试了一下没有这个问题了，您可以升级试试，还有问题的话可以重新打开这个issue或者提一个新的
