### ISSUE TITLE
[BUG]接口自动化场景，引用接口用例后，可以进行编辑并保存

### ISSUE THREAD

**Issue by chenhaoyu0725** [metersphere/metersphere#10335]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题
接口自动化场景，引用接口用例后，可以进行编辑并保存
**Bug 重现步骤**

1. 进入接口自动化页面
2. 新增一个场景
3. 并点击接口列表导入，选接口用例，并且点击引用
4. 引用成功后，对该接口进行编辑，并点击保存

**期待的正确结果**
引用应该无法编辑和保存
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/99321253/153158642-65eb93cf-323c-4973-b657-d13eb0663105.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.17.3已修复
