### ISSUE TITLE
邮件的地址访问不了，还需配置哪里嘛？[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1034]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.0

**Bug 描述**
简要描述您碰到的问题
邮件的地址访问不了，还需配置哪里嘛？

**Bug 重现步骤**
1.  metersphere配好邮件发送
2. 构建Jenkins后收到邮件
3. 点击邮件的链接
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/103405026-a3c67c00-4b90-11eb-93ba-73a8e49511ad.png)
![image](https://user-images.githubusercontent.com/37016695/103405034-a6c16c80-4b90-11eb-8e72-a616d0a2eab7.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请在系统参数设置中配置下当前站点的 URL
