### ISSUE TITLE
[BUG]在脑图模式下-保存子节点为新模块时，出现报错

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#10347]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建模块后-保存
2. 对已有模块增加子节点，并赋值为模块
3. 点击保存

**期待的正确结果**
保存成功

**截图**
![image](https://user-images.githubusercontent.com/44996472/153166257-beb2cb17-28e7-40c9-afda-7aa170d10fa2.png)

**Comment by A616984934** [comment]
![image](https://user-images.githubusercontent.com/44996472/153166523-4bf281a7-5667-4c1e-b3f3-4f750f64640a.png)

**Comment by youliyuan-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/44996472/153166523-4bf281a7-5667-4c1e-b3f3-4f750f64640a.png)

这个图总的最后 “分支主题” 没有添加模块的标签，请设置一个标签后保存

**Comment by A616984934** [comment]
建议加一个toast提示框，不然很难确定问题

**Comment by A616984934** [comment]
![image](https://user-images.githubusercontent.com/44996472/153332690-839fe170-6c94-47c3-b725-bf93b3828798.png)
建立的子节点，加上备注标签后，依然有这个报错

**Comment by A616984934** [comment]
![image](https://user-images.githubusercontent.com/44996472/153332760-3b251d9b-39c6-4920-94a7-5d599ba559c7.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，模块下一级不能有备注，“备注”标签是属于用例里面的内容，但是我们需要优化一下提示信息

**Comment by A616984934** [comment]
提示信息是否优化了呢

**Comment by youliyuan-fit2cloud** [comment]
> 提示信息是否优化了呢
你好，这种情况 当做临时节点保存，且只在脑图上显示
只有打上用例或者模块标签才会去存成模块合用例

**Comment by A616984934** [comment]
不是 希望能加上保存失败的提示信息；不然保存用例的时候 只有控制台看到这个报错；不知道是否保存成功
<img width="503" alt="image" src="https://user-images.githubusercontent.com/44996472/156095644-733682cd-0ffd-4f50-af14-116a2917e5ff.png">
