### ISSUE TITLE
[BUG]消息通知模块里的  测试计划 通知，选 新建 事件，接收人 出现了执行人，选执行完成事件，反而没有 执行人可以选

### ISSUE THREAD

**Issue by chenhaoyu0725** [metersphere/metersphere#10357]
**MeterSphere 版本**
1.17.1
您所使用的 MeterSphere 版本是？

**Bug 描述**
消息通知模块里的  测试计划 通知，选 新建 事件，接收人 出现了执行人，选执行完成事件，反而没有 执行人可以选
简要描述您碰到的问题

**Bug 重现步骤**

1.  进入消息通知模块
2. 选择测试计划类型，点击创建新通知
3. 事件选择 新建
4. 点击接收人

**期待的正确结果**
期望效果：有创建人选项
实际效果：只有执行人选项，执行人是否应该是在  执行完成事件下才能选该类型的接收人呢？
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/99321253/153178519-595694f7-d1a9-45e6-ae92-11ba65930a3e.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化
