### ISSUE TITLE
[BUG]显示设置，上传图片logo 后，显示位置不正确

### ISSUE THREAD

**Issue by pengs** [metersphere/metersphere#1035]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.6.1

**Bug 描述**

**Bug 重现步骤**
1.  系统设置--系统 --系统参数设置，显示设置
2. 上传登录页左上角的logo后，退出重新登录后，图片展示位置不正确
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/8827875/103405096-e4be9080-4b90-11eb-8ccc-b778b8eafba9.png)
![image](https://user-images.githubusercontent.com/8827875/103405137-0cadf400-4b91-11eb-8305-0c00bed9e8a3.png)

**Comment by SloanGao** [comment]
請問你是什麼版本，企業版？我這邊 怎麼沒有 系统设置--系统 --系统参数设置，显示设置

**Comment by liuruibin** [comment]
将在下一个版本中修复

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
