### ISSUE TITLE
[BUG]优化测试报告生成时间

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10364]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题
测试计划串行加资源池执行在测试报告列很快生成报告的记录，
测试计划并行不论是否选择资源池执行都需要加载很久才能在测试报告生成记录，优化保持两种执行方式生成报告时间一致
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.17.2对测试报告存储进行了优化，您可以在1.17.2版本看一下，还是比较慢的话我们再继续优化
