### ISSUE TITLE
[BUG]请求体使用JSON-SCHEMA模式时，参数类型选择boolean类型后，无法从CSV列表中正常取到True值

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10362]
**MeterSphere 版本**
1.17.1
您所使用的 MeterSphere 版本是？

**Bug 描述**
请求体使用JSON-SCHEMA模式时，参数类型选择boolean类型后，无法从CSV列表中正常取到True值

简要描述您碰到的问题

**Bug 重现步骤**

1.  请求体使用JSON-SCHEMA模式时，参数类型选择boolean类型后，无法从CSV列表中正常取到True值
2. 如果直接输入true是可以的
3. 从csv里面读的值都是false
4. 

**期待的正确结果**

正确情况下应该是什么样的？
参数类型选择boolean类型后，可以正常去csv列表中取到true
**截图**

如果有截图，请附上截图.
<img width="499" alt="1" src="https://user-images.githubusercontent.com/83771182/153326435-33a16f49-1eca-49fa-9906-31ddacedd373.png">
<img width="496" alt="6" src="https://user-images.githubusercontent.com/83771182/153326477-7d9a10a1-d69a-46e4-8192-910f774d3708.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.2已修复
