### ISSUE TITLE
[BUG]功能用例的复制导致部分字段的值错误

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10366]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1创建一个功能用例1
2在功能用例列表点击复制功能用例1
3重复多点几次复制
4“用例等级”和“用例状态”的值都不是候选值

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/153333970-00e1aa13-2e0d-4782-8e49-f57115481c52.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本尽量优化下

**Comment by ltfit** [comment]
升级到最新版本
