### ISSUE TITLE
[BUG]脑图修改的模块保存后，无法生效到左侧的模块栏

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#10368]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

脑图修改的模块保存后，无法生效到左侧的模块栏

**Bug 重现步骤**

1.  打开脑图，选择任意模块更改名称
2. 点击保存后，刷新查看左侧模块栏
3. 

**期待的正确结果**

模块栏模块名称更新

**截图**
![image](https://user-images.githubusercontent.com/44996472/153334491-e6e3053c-60ec-4a58-a7cb-9845a8eca711.png)
![image](https://user-images.githubusercontent.com/44996472/153334499-b7d8b820-046a-49d5-8356-ef821b9f756f.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，请说明使用版本，我们没复现这个问题呢，左侧截图也让我们看看？

**Comment by youliyuan-fit2cloud** [comment]
最新版本已修复，请更新一下吧
