### ISSUE TITLE
[BUG]脑图中版本筛选功能失效

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10373]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建用例1
2. 创建用例1的不同版本
3. 切换脑图显示
4. 点击版本筛选

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/153347684-0a37cd53-ab96-4c1d-babf-4b0c842787d2.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts中已实现该功能
