### ISSUE TITLE
[BUG]用例评审添加评论时无规律性在添加评论后自动标记了通过、未通过的状态；

### ISSUE THREAD

**Issue by 18982185329** [metersphere/metersphere#10372]
**MeterSphere 版本**

版本:   v1.17.1-1ec9c7ce

**截图**

![image](https://user-images.githubusercontent.com/74221859/153347295-9d804ee8-8046-4e10-90db-96fb7770614a.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，我们努力修复中.....

**Comment by zyyfit** [comment]
1.19.1已优化
