### ISSUE TITLE
【BUG】脑图模块移动报错

### ISSUE THREAD

**Issue by lei32323** [metersphere/metersphere#10391]
**MeterSphere 版本**

V1.16

**Bug 描述**

脑图拖拽模块到其他模块下，保存报错
**Bug 重现步骤**

1.  脑图新增一个模块(3级模块)
2.  拖拽该模块到其他3级模块下
3. 点击保存，报错

**期待的正确结果**

保存成功

**截图**

![image](https://user-images.githubusercontent.com/16314374/153370272-1e88962f-c8f7-4f62-8d7c-9439fabd9f5a.png)

日志报错
![image](https://user-images.githubusercontent.com/16314374/153370301-a75452af-5549-41dd-9b4e-d0dac56d815e.png)

**报错代码**
![image](https://user-images.githubusercontent.com/16314374/153369713-85e32f9c-7a17-4cce-8b9f-aeab27f38bbd.png)

**Comment by lei32323** [comment]
这里使用split 来截取NodePath为集合，如果level超过NodePath的长度。再去对集合做set的话，肯定会有问题。

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，我们后续版本修复

**Comment by ltfit** [comment]
1.18.1已修复
