### ISSUE TITLE
[BUG]自定义变量无法正确替换到请求URL中

### ISSUE THREAD

**Issue by Paulswith** [metersphere/metersphere#104]
**请描述您的需求或者改进建议.**
接口测试/场景里的自定义变量,  定义了一个接口地址变量如addr=http://10.10.13.13:3212, 当引用到接口的URL中的时候，会自动填入https://,  虽然也可以在此修改为http://,  
但实际我们期望可以自定义环境来测试, 可能是一套是http://, 一套是https://， 所以希望把这个变量抽离到自定义变量`${addr}`里。

看到的只需要是`${addr}/path/to/services`

**请描述你建议的实现方案**
不需要额外的填充，让测试人员自行负责变量的整理

**Comment by wangzhen-fit2cloud** [comment]
你好，我们会在 7 月底的 v1.1 版本中增加环境管理的功能，到时候可以关注下该版本能否解决你的问题。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.1.0 已发布并提供了环境管理功能，欢迎下载试用
