### ISSUE TITLE
[BUG]场景版本对比缺少步骤标号

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10414]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景
2. 进入场景导入接口并保存
3. 进入场景的版本管理中新建一个版本场景
4. 然后对比，发现有一个场景少一个标号

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/153394354-4b472524-abfc-4f8a-8b8b-6ea25c643ebc.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.3已修复
