### ISSUE TITLE
[BUG] jenikns调用api测试计划，无法调用

### ISSUE THREAD

**Issue by yanghuizhi** [metersphere/metersphere#10410]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.10.4-221f275f

**Bug 描述**

简要描述您碰到的问题

铺设jenkins，调用测试计划并执行，返回结果

**Bug 重现步骤**

1.  找不到调用测试计划的接口，
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有理解您的意思，我们有jenkins插件，可以直接调用测试计划、场景和测试用例，如果您想自己配置调用执行测试计划，不知道您找的是不是这个接口 
/test/plan/run
{
    "mode": "serial",
    "reportType": "iddReport",
    "onSampleError": false,
    "runWithinResourcePool": false,
    "resourcePoolId": null,
    "envMap": {},
    "testPlanId": "xx",
    "projectId": "xx,
    "userId": "xx",
    "triggerMode": "MANUAL",
    "environmentType": "JSON",
    "environmentGroupId": "",
    "requestOriginator": "TEST_PLAN"
}

**Comment by yanghuizhi** [comment]
> 

可能是我没说清楚，我在目前的api中没有找到您所说的这个接口，请问您是哪里得到的数据，我希望从swagge中获取执行的数据，

**Comment by zyyfit** [comment]
不好意思，这个接口是后面的新版本增加的，1.10版目前没有这个功能，但是1.10版也是有jenkins插件的，您可以直接使用我们的jenkins插件执行测试计划，我找了个使用教程您可以参考一下是否满足您的需求 https://blog.csdn.net/m0_38039437/article/details/109777823

**Comment by zyyfit** [comment]
这个是有的，可以在这里配置，
选择jenkins运行结果，就是根据Jenkins执行返回结果，只要执行不报错就都是成功，
选择插件运行结果就是根据我们的接口执行结果返回，有失败的就是失败，全都成功就是成功
![图片](https://user-images.githubusercontent.com/73461316/153567843-cdb923a3-74e1-465d-bfb0-517bcc156157.png)

**Comment by yanghuizhi** [comment]
> 这个是有的，可以在这里配置， 选择jenkins运行结果，就是根据Jenkins执行返回结果，只要执行不报错就都是成功， 选择插件运行结果就是根据我们的接口执行结果返回，有失败的就是失败，全都成功就是成功 ![图片](https://user-images.githubusercontent.com/73461316/153567843-cdb923a3-74e1-465d-bfb0-517bcc156157.png)

哇，太感谢你了，我这就去和运维沟通

**Comment by zyyfit** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue

**Comment by fhj-9527** [comment]
> 您好，没有理解您的意思，我们有jenkins插件，可以直接调用测试计划、场景和测试用例，如果您想自己配置调用执行测试计划，不知道您找的是不是这个接口 /test/plan/run { "mode": "serial", "reportType": "iddReport", "onSampleError": false, "runWithinResourcePool": false, "resourcePoolId": null, "envMap": {}, "testPlanId": "xx", "projectId": "xx, "userId": "xx", "triggerMode": "MANUAL", "environmentType": "JSON", "environmentGroupId": "", "requestOriginator": "TEST_PLAN" }

我用的最新版本2.3.0 访问这个接口404 请问一下2.3.0还支持 api方式运行计划吗？
