### ISSUE TITLE
[BUG]场景引用接口用例，请求参数无法同步

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10415]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1存在一个带传参的接口用例
2创建一个场景引用改接口用例
3修改接口用例的请求参数
4场景中引用的接口用例的请求参数没有同步
**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.17.2已修复
