### ISSUE TITLE
[BUG]接口测试响应断言不准确

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10412]
**MeterSphere 版本**
17.7
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创一个可成功响应的接口用例
2. 添加响应断言设置为50ms
3. 运行接口响应时间超过50ms
4. 响应内容断言成功

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把错误的接口信息导出来给我们吗
![图片](https://user-images.githubusercontent.com/73461316/153569401-1c74de56-5cd9-4bdd-91a1-cf44fc88dc29.png)

**Comment by zyyfit** [comment]
复现了，后续版本修复

**Comment by zyyfit** [comment]
1.18.0已修复
