### ISSUE TITLE
[BUG]性能测试报告日志详情中的summary的值比请求统计中的samples的total值小一半

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10429]
**MeterSphere 版本**

1.17.1    1.15.4

**Bug 描述**

性能测试报告日志详情中的summary的值比请求统计中的samples的total值小一半，日志详情中的tps也比测试概览中tps小一半

**Bug 重现步骤**

1.  在接口自动化场景中创建任意场景，比如请求百度
2. 将该场景创建为性能测试，并执行该性能测试
3. 点击测试报告中的下载执行文件
4. 另外创建一个性能测试，将下载的执行文件解压后的jmx文件上传上去，创建性能测试
5. 执行用执行文件创建的性能测试
6. 结果 性能测试报告日志详情中的summary的值比请求统计中的samples的total值小一半，日志详情中的tps也比测试概览中tps小一半

**期待的正确结果**

性能测试报告日志详情中的summary的值与请求统计中的samples的total相同

![image](https://user-images.githubusercontent.com/88763608/153535965-30dba9e2-f54c-46a8-8ab7-44028b6d70ae.png)
![image](https://user-images.githubusercontent.com/88763608/153535990-16667aa9-400c-48cc-a753-ae0f69bb7d59.png)
![image](https://user-images.githubusercontent.com/88763608/153536004-691210e7-246d-495b-8842-6bcdc1dc4b89.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我这边看着都是差不多的

**Comment by zyyfit** [comment]
复现了，后续版本修复
