### ISSUE TITLE
[BUG]优化定时任务保存按钮

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10422]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题
习惯一个页面一个保存按钮，在定时任务页面关闭定时任务时，点击关闭定时任务按钮后，习惯点击保存，导致定时任务关不掉
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.18.0已优化
