### ISSUE TITLE
[FEATURE]以后版本是否会增加WEBUI自动化和APPUI自动化

### ISSUE THREAD

**Issue by HEhunter** [metersphere/metersphere#10428]
**请描述您的需求或者改进建议.**

以后版本是否会增加WEBUI自动化和APPUI自动化

**请描述你建议的实现方案**
以后版本是否会增加WEBUI自动化和APPUI自动化

**Comment by Hyyfit** [comment]
WEBUI自动化，已规划排期，预计4月就会上线啦！
APPUI自动化，暂时不考虑哦
