### ISSUE TITLE
[BUG] 在性能测试中添加自定义参数后执行，检查结果报错

### ISSUE THREAD

**Issue by swmachine1401** [metersphere/metersphere#10431]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题
在性能测试中添加自定义参数后执行，检查结果报错
我在接口自动化中添加了同样的参数，结果是正常的
接口自动化和性能测试的参数名是相同的

**Bug 重现步骤**

![截图_1644559301458](https://user-images.githubusercontent.com/33212266/153544458-3b11cacb-967b-41e2-995f-ab8a26cfb09d.png)
![截图_16445593926607](https://user-images.githubusercontent.com/33212266/153544567-ed2c0a34-f90a-4d95-bcd8-b90757decde4.png)
![截图_16445594123772](https://user-images.githubusercontent.com/33212266/153544592-57449a41-fc01-4049-b5ee-2a2697256a3a.png)
![截图_164455943519](https://user-images.githubusercontent.com/33212266/153544630-0c31d30f-9924-4d12-a5f5-818672c6b793.png)

**期待的正确结果**

正确情况下应该是什么样的？
应该有错误的结果吧

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by liuruibin** [comment]
看起来这个错误是jmx中缺少jar csv等相关文件，可以点击下载执行文件按钮把zip下载下来检查一下
