### ISSUE TITLE
[BUG]页面场景步骤过大，打开页面out of memory 

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10434]
**MeterSphere 版本**

1.10.8-lts  1.17.1

**Bug 描述**

页面场景步骤过大，打开页面out of memory 
1.场景步骤数比较多，并且场景结构复杂的情况下
2.一键展开复杂的场景
3.可能出现卡顿，点击无响应，页面空白，甚至out of memory

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，场景步骤大概多大呢？方便发一下场景脚本吗

**Comment by linfengjjj** [comment]
> 您好，场景步骤大概多大呢？方便发一下场景脚本吗

可以，最新版本还是会卡
[Metersphere_Scenario_b业务测试项目.zip](https://github.com/metersphere/metersphere/files/8478756/Metersphere_Scenario_b.zip)

**Comment by zyyfit** [comment]
这个场景里步骤太多了，加载肯定需要时间的，现在应该极限优化了。后续除非改页面机制，否则没啥太好办法了，改页面机制的话改动比较大 ，暂时先不优化了。可以建议用户把场景分开写
