### ISSUE TITLE
[BUG]在场景中引用的接口用例不能单独添加等待控制器

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10435]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在场景中的引用的接口用例下添加等待控制器，添加失败
2. 在复制的接口用例下可以添加等待控制器，
3. 只有当控制器添加到接口下才只会使当前接口等待
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，引用了接口后，选中这个接口直接添加等待控制器就可以
