### ISSUE TITLE
【建议】测试报告链接不需登录也能直接查看

### ISSUE THREAD

**Issue by sanzuomiangan** [metersphere/metersphere#10449]
**请描述您的需求或者改进建议.**
通过钉钉机器人发送的测试报告链接，点击后还需要登录

**请描述你建议的实现方案**
希望测试报告可以免登，相关人员可以点击链接直接查看

**Comment by Hyyfit** [comment]
您好！我们企业版是支持设置免登录查看报告链接。您可以在交流群联系商务。
