### ISSUE TITLE
[BUG]测试计划中的场景不执行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10448]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景，场景中导入接口用例，不要调试，不选择执行环境
2. 创建一个测试计划关联刚创建的场景
3. 在测试计划列表中执行创建的测试计划
4. 执行完后查看报告，添加的场景报告为空

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，新建场景可以不选择环境，然后测试计划里关联场景的时候是需要选择环境的，不选择环境无法关联，你是这里也没选环境吗？怎么操作的？
