### ISSUE TITLE
点击删除，一直loading[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1044]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.1

**Bug 描述**
简要描述您碰到的问题
点击删除，一直loading

**Bug 重现步骤**
1.  点击删除，一直loading
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
点击删除，删除成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/103507547-6a488600-4e9a-11eb-9895-69853ac773bc.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，未复现该问题
