### ISSUE TITLE
[BUG]对接非SaaS版的jira不能关联需求，且企业版不能推送缺陷到jira

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#10446]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？v1.17.2

**Bug 描述**

简要描述您碰到的问题
1、非SaaS版的jira现在可以获取问题类型，但是同步缺陷的时候不能拉取jira上的缺陷（可以推送缺陷到jira）；
2、需求不能关联

![cd150aca069b509ab8a57a96b535a66](https://user-images.githubusercontent.com/66759501/153562108-638768f5-fb42-4833-9cbb-d7834e4ed2be.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们尽力修复~

**Comment by youliyuan-fit2cloud** [comment]
最新版本已修复，请更新一下吧
