### ISSUE TITLE
[BUG]接口自动化内的场景如果是引用的接口或者case,导出该场景为jmx时，接口的不启用全部变成启用了

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10453]
**MeterSphere 版本**

V1.17.1

**Bug 描述**

接口自动化内的场景如果是引用的接口或者case,导出该场景为jmx时，接口的不启用全部变成启用了

**Comment by zyyfit** [comment]
您好，1.17.2没有复现这个问题，您可以升级试试

**Comment by zyyfit** [comment]
1.18.0已修复
