### ISSUE TITLE
[BUG]当测试资源池下有多个node节点时，有个别节点状态失效，故指定并发到固定可用节点时报node-controller状态无效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10454]
**MeterSphere 版本**

v1.17.1

**Bug 描述**

当测试资源池下有多个node节点时，有个别节点状态失效，故指定并发到固定可用节点时报node-controller状态无效
要么就抛出哪些节点的状态无效，方便去检查；
要么就指定固定节点去运行时，只校验固定节点

**截图**

如果有截图，请附上截图.
![企业微信截图_16445712165694](https://user-images.githubusercontent.com/32027713/153575464-c97b3de5-bee1-4fdc-a52e-4f106b4bb424.png)

**Comment by zyyfit** [comment]
您好，没有理解您的意思，能具体描述一下吗？
执行测试要用测试资源池执行的话是需要手动选择用哪个资源池的
