### ISSUE TITLE
[BUG]在测试计划单独执行接口用例，就一直处于转圈中，单独在接口定义下执行响应很快

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10455]
**MeterSphere 版本**
V1.17.1

**Bug 描述**

在测试计划单独执行接口用例，就一直处于转圈中，单独在接口定义下执行响应很快

**截图**

![image](https://user-images.githubusercontent.com/32027713/153576592-e18e9f2e-f264-4619-9962-dc072a6fccef.png)

**Comment by zyyfit** [comment]
测试计划中是执行的慢但是能出结果吗？
