### ISSUE TITLE
[BUG]jenkins通过插件启动的测试计划没法再统一位置查看结果

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1046]
**MeterSphere 版本**
1.6.1

**Bug 描述**
创建测试计划，关联单接口测试用例和场景测试用例，通过jenkins的插件启动该测试计划。
1，测试结果可以邮件发送，但是邮件中只有一个链接，没有内容
2，到MeterSphere网页上找测试结果，也没法找到单接口用例的测试结果。

**期望结果**
1，邮件中能展示所有测试内容的测试结果页面
2，能有统一的位置展示测试计划的测试所有结果，方便查阅

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改测试计划管理接口和性能测试用例的方式。
