### ISSUE TITLE
[FEATURE]脑图编辑页面，跳转到其他页面提示脑图未保存，点击保存按钮返回页面

### ISSUE THREAD

**Issue by trhleaf** [metersphere/metersphere#10463]
**请描述您的需求或者改进建议.**
脑图编辑页面，跳转到其他页面提示脑图未保存，点击保存按钮返回页面，实际未保存，需单独点击页面上的保存，才有效果

但是，这个会让操作步骤多2步；

![image](https://user-images.githubusercontent.com/53073139/153786066-2bc8ec94-4f36-41e4-8dfa-e69cc2c014d2.png)

**请描述你建议的实现方案**

建议在弹框保存按钮就加上保存功能，再跳转链接

**Comment by Hyyfit** [comment]
您好，没有复现您的情况。
我们弹窗是有保存功能的，同时也支持保存后跳转到下一步的操作。
