### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zplll** [metersphere/metersphere#10465]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

登录session过期，跳转到login页面时，不会带端口号，每次需要手动加上端口号

**Bug 重现步骤**

1.  部署路径带端口号
2. 登录session过期(可以删除cookie中的MS_SESSION_ID模拟)，跳转到login页面，该页面会去掉端口号

**期待的正确结果**

正确情况下应该是什么样的？
login登录页面需要带端口号

![image](https://user-images.githubusercontent.com/15026085/153788014-6eabcdb9-52dd-44ea-873a-74ad7db35d31.png)

**Comment by liuruibin** [comment]
如果是nginx做代理的话需要加上完整端口


proxy_set_header Host $host:$server_port;
