### ISSUE TITLE
[BUG]ms 上创建的BUG，附带图片，同步到禅道后，禅道上的图片和MS上的不一致

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#10473]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17.2
**Bug 描述**
ms 上创建的BUG，附带图片，同步到禅道后，禅道上的图片和MS上的不一致
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![BUG1](https://user-images.githubusercontent.com/61281775/153815982-f206cf80-f301-4ce6-b0e0-3e583e612ed9.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您那边可以稳定复现吗？具体操作步骤是什么呢？比如说，您的图片是复制粘贴上的，还是从本地上传的，还是添加的图片链接呢？禅道请求方式是Path_info还是get？

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #10586
