### ISSUE TITLE
[BUG] 脑图下新增子项点击保存报错

### ISSUE THREAD

**Issue by shesuqin00001** [metersphere/metersphere#10475]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.0.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在任意的模块下新增子项
2. 点击保存，无法保存
3. 查看报错信息如图所示

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/63088648/153818183-4b83f75b-4be0-473b-bb77-903786460989.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.0已修复
