### ISSUE TITLE
重复执行测试计划中的场景测试用例报错

### ISSUE THREAD

**Issue by LEE-lucky** [metersphere/metersphere#1047]
**MeterSphere 版本**
版本: v1.6.1-3cb27580

**Bug 描述**
重复执行测试计划中的场景测试用例报错

### Error updating database. Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '13014461-99bf-4ec7-82b2-f06aa6fa857d' for key 'PRIMARY' ### The error may exist in io/metersphere/base/mapper/ApiScenarioReportMapper.xml ### The error may involve io.metersphere.base.mapper.ApiScenarioReportMapper.insert-Inline ### The error occurred while setting parameters ### SQL: insert into api_scenario_report (id, project_id, `name`, create_time, update_time, `status`, user_id, trigger_mode, execute_type, scenario_name, scenario_id, description ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '13014461-99bf-4ec7-82b2-f06aa6fa857d' for key 'PRIMARY' ; Duplicate entry '13014461-99bf-4ec7-82b2-f06aa6fa857d' for key 'PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '13014461-99bf-4ec7-82b2-f06aa6fa857d' for key 'PRIMARY'

**Bug 重现步骤**
1.  添加场景测试用例后执行两次，第一次正常，第二次报错
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/56376764/103523879-9292ad80-4eb7-11eb-9737-fd1da765216a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，未复现该问题
