### ISSUE TITLE
[BUG]定时任务执行后无法通知到企业微信或邮箱中

### ISSUE THREAD

**Issue by Crush188** [metersphere/metersphere#10486]
您所使用的 MeterSphere 版本是？
 v1.15.1-7769e696

**Bug 描述**
自动化定时任务执行结果无法通知

简要描述您碰到的问题
在接口自动化中设置了定时任务，以及执行成功或失败后在企业微信中的通知。刚开始的几天都是好好的每天执行和通知，从某一天开始就变成只执行、不通知了。添加了邮箱通知，也是无法通知。新增别的定时任务，仍然无法通知。
**BUG复现**
1.创建场景：输入名称和id
2.自定义请求：输入请求地址
3.设置定时任务：生成表达式，时间为每8小时一次
4.设置提醒：执行失败和成功均提醒至企业微信
**期待的正确结果**
![image](https://user-images.githubusercontent.com/66367664/153826544-89b24f8a-f0f8-4b9f-9a19-e50fe3a4535f.png)
日志：
[rizhi_2022-02-14_16_44_58.log](https://github.com/metersphere/metersphere/files/8059225/rizhi_2022-02-14_16_44_58.log)

如果有截图，请附上截图.

**Comment by Crush188** [comment]
[Uploading rizhi.log…]()

**Comment by youliyuan-fit2cloud** [comment]
你好，新版本没有复现这个问题，升级下?

**Comment by TRAC4869** [comment]
重载服务后问题解决了，谢谢
