### ISSUE TITLE
[BUG]接口定义，添加断言后，总是会默认添加一条响应时间的断言

### ISSUE THREAD

**Issue by NewBigBug** [metersphere/metersphere#1048]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.1
**Bug 描述**
简要描述您碰到的问题
接口定义中，添加了一条jsonpath的断言，但是会默认添加一条响应时间的断言
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/29793694/103526132-611be100-4ebb-11eb-842c-5a0442d2fde5.png)

**Comment by xulinde** [comment]
v1.8已优化
