### ISSUE TITLE
[BUG]MS同步缺陷至禅道，在有截图的情况下，禅道上只显示了图片链接，未能解析显示成图片，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10484]
**MeterSphere 版本**

v1.17.2

**Bug 描述**

MS同步缺陷至禅道，在有截图的情况下，禅道上只显示了图片链接，未能解析显示成图片，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/153825368-6b4df787-ae0a-4a06-a9ea-7a4d9aa326fc.png)
![image](https://user-images.githubusercontent.com/92150453/153825398-432c1a50-89aa-4ca0-a6ec-b8b5c51421e6.png)
![image](https://user-images.githubusercontent.com/92150453/153825422-5fff8b0c-0b38-4e2f-9052-2615c557e66b.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问您具体是怎么操作的呢？禅道请求方式是get还是path_info？图片是直接复制粘贴的吗

**Comment by sageonedream** [comment]
请求方式是get，直接截屏复制粘贴的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月14日(周一) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]MS同步缺陷至禅道，在有截图的情况下，禅道上只显示了图片链接，未能解析显示成图片，请修改 (Issue #10484)




 
您好，没有复现这个问题，请问您具体是怎么操作的呢？禅道请求方式是get还是path_info？图片是直接复制粘贴的吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youliyuan-fit2cloud** [comment]
你好，貌似你没升级成功。。1.17.1有这个问题，1.17.2已经解决了，请确认下版本

**Comment by sageonedream** [comment]
好的，我升级最新版本看看，因为之前没看到issues上有单



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 中午11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]MS同步缺陷至禅道，在有截图的情况下，禅道上只显示了图片链接，未能解析显示成图片，请修改 (Issue #10484)




 
你好，貌似你没升级成功。。1.17.1有这个问题，1.17.2已经解决了，请确认下版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
