### ISSUE TITLE
[BUG] jenkins插件调用接口自动化测试没有引用项目的第三方jar包

### ISSUE THREAD

**Issue by Betrayme** [metersphere/metersphere#10485]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  jenkins设置调用接口自动化场景
2. 提示缺少类 NoClassDef，即没有引用项目上传的jar包
3. 在MS上进行改接口自动化无上诉问题

**期待的正确结果**

正确情况下应该是什么样的？
据我了解，接口用例测试在server中运行，性能测试则由controller调用jmeter镜像执行，而jenkins好像是在controller中直接执行
若在controller中执行请引用项目上传的jar包，或者与性能测试的逻辑保持同步

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，我们暂时没复现，建议升级到最新版本的jenkins 和ms试试呢

**Comment by Betrayme** [comment]
@youliyuan-fit2cloud 能否告知，API调用接口自动化场景，是否在node-controller中执行，ms-server和jmeter镜像都自定义了环境都是执行成功的，就API调用方式不行

**Comment by zyyfit** [comment]
> @youliyuan-fit2cloud 能否告知，API调用接口自动化场景，是否在node-controller中执行，ms-server和jmeter镜像都自定义了环境都是执行成功的，就API调用方式不行

如果在Jenkins里选择了资源池，就是在node-controller中执行，没选就不是，然后选择了的话，可以在ms系统的测试资源池配置里，勾选同步jar包，会在每天凌晨，大概2点左右，自动同步jar包到资源池节点
![图片](https://user-images.githubusercontent.com/73461316/155635851-0b4a3236-7587-4d6a-ab1a-0889cdb054b9.png)

**Comment by Betrayme** [comment]
@youliyuan-fit2cloud 非常感谢
