### ISSUE TITLE
[BUG] 接口约束异常测试中，预期的状态码为400，断言也是400，但是报告中该用例结果还是为失败状态，不合理

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#10492]
**MeterSphere 版本**
版本:   v1.16.4-07155cf8
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

1.部分用例就是测试接口异常的，所以预期就是会失败，如果这个时候符合断言规则，应该标记该用例测试结果为成功

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有遇到过这种问题，请问您勾选忽略状态了吗？

**Comment by allinone-1** [comment]
> 您好，没有遇到过这种问题，请问您勾选忽略状态了吗？

请问哪里可以勾选忽略状态？ 没有尝试过

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/154005111-b741fef5-a429-418d-b2a1-5b0467dd52fe.png)

**Comment by allinone-1** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/154005111-b741fef5-a429-418d-b2a1-5b0467dd52fe.png)

只有使用正则表达式的时候才有忽略状态，我们用的是jsonpath的方式，可以怎么处理？

**Comment by youliyuan-fit2cloud** [comment]
> > ![image](https://user-images.githubusercontent.com/54612864/154005111-b741fef5-a429-418d-b2a1-5b0467dd52fe.png)
> 
> 只有使用正则表达式的时候才有忽略状态，我们用的是jsonpath的方式，可以怎么处理？

你好，想问下状态码为啥用jsonpath方式断言？
