### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xizibai** [metersphere/metersphere#1049]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.6.0
**Bug 描述**
简要描述您碰到的问题
删除测试计划报错
**Bug 重现步骤**
1.  点击进入测试计划-全部计划
2. 删除计划
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/30991409/103528342-bc9b9e00-4ebe-11eb-80ec-d9c741ef1d3c.png)

**Comment by xizibai** [comment]
修改标题

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已修改，请升级验证
