### ISSUE TITLE
[BUG]v1.17.2 接口测试-接口自动化-场景列表：创建人显示为id

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#10496]
![image](https://user-images.githubusercontent.com/20641051/153896274-efda79f2-2216-4ada-b983-cc373145d737.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会优化这个问题

**Comment by youliyuan-fit2cloud** [comment]
v1.17.3已修复
