### ISSUE TITLE
[BUG]v1.17.2 测试计划关联接口自动化，创建人显示id，关联列表不显示创建人

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#10497]
1 bug:点击关联测试用例，弹出的接口自动化列表，创建人显示id
![image](https://user-images.githubusercontent.com/20641051/153897755-ed4b46ed-7842-41ab-a2e5-b5cc0c7fee6c.png)

2 bug:关联的接口自动化列表，创建人不显示
![image](https://user-images.githubusercontent.com/20641051/153897927-977e87c4-305f-461d-9c66-64963527d17e.png)

3 优化建议
测试计划中，添加关联用例，建议显示 用例状态，这样可以方便的把 已完成 的用例添加到测试计划

**Comment by youliyuan-fit2cloud** [comment]
问题重复了。。
Duplicate of #10496 #10495
