### ISSUE TITLE
[BUG]v1.17.2测试计划执行报告，创建人不显示

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#10495]
1 创建人不显示， 2 建议 增加 责任人字段，责任人筛选自己负责的用例去分析报告
![image](https://user-images.githubusercontent.com/20641051/153898756-5169c6c6-1ba5-4a70-bcc3-082d0d057952.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化

**Comment by youliyuan-fit2cloud** [comment]
v1.18.0版本 已修复该问题
