### ISSUE TITLE
[BUG]在URL引用的自定义变量,实际请求多带了`[]`

### ISSUE THREAD

**Issue by Paulswith** [metersphere/metersphere#105]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
在URL引用的自定义变量,实际请求多带了`[]`

**Bug 重现步骤**
1.  添加一个自定义变量addr, 表达接口位置
2.  在URL中引用此变量
3. 发送请求, 检查报告

**期待的正确结果**
正确情况下应该是什么样的？
把方括号去掉, 还有最好是把这个 #104    优化下

**截图**
如果有截图，请附上截图.
![自定义变量](https://user-images.githubusercontent.com/24262233/86872831-ae3b1800-c10f-11ea-9f79-aff3e02b5df1.png)

![在URL引用](https://user-images.githubusercontent.com/24262233/86872947-e80c1e80-c10f-11ea-863a-a2d4ad081567.png)

![实际请求解析多带了`[]`](https://user-images.githubusercontent.com/24262233/86873016-11c54580-c110-11ea-9196-9de9af726c36.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们会在 7 月底的 v1.1 版本中增加环境管理的功能，到时候可以关注下该版本能否解决你的问题。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.1.0 已发布并提供了环境管理功能，欢迎下载试用
