### ISSUE TITLE
[BUG]v1.17.2 测试跟踪 用例责任人分布 图形错乱

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#10500]
![image](https://user-images.githubusercontent.com/20641051/153990900-ba601b7c-3472-46fa-a342-c1cc1a6bd792.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会优化一下

**Comment by youliyuan-fit2cloud** [comment]
v.1.17.3版本已优化
