### ISSUE TITLE
[BUG]自动化测试运行环境中添加全局脚本后，接口中的前置脚本设置的变量无法直接在接口入参中使用

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#10502]
**MeterSphere 版本**

1.17.2

**Bug 描述**

运行环境中添加全局脚本后，接口中的前置脚本设置的变量无法直接在接口入参中使用

**Bug 重现步骤**

1.  自动化测试中添加接口，设置前置脚本中的参数，参数以${x}方式入参中调用
2. 添加全局脚本
3. 
4. 

**期待的正确结果**

${x}参数能够在入参中正常调用，未加入全局脚本时可以生效，且全局脚本与入参的${x} 毫不相关

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题呢。请上传相关设置截图，我们再定位一下

**Comment by wszbc** [comment]
> 你好，没有复现这个问题呢。请上传相关设置截图，我们再定位一下

前置脚本设置了变量
![image](https://user-images.githubusercontent.com/40912823/154180623-ffae2fa5-866e-4be9-aed6-cb0d08f76396.png)
入参中的数据
![image](https://user-images.githubusercontent.com/40912823/154180885-c43ec3f7-a34f-416b-8b29-bb4488eda6b1.png)
未设置全局变量时正常转换，变量有效
全局脚本
![image](https://user-images.githubusercontent.com/40912823/154181101-2122424d-d6a4-49f5-a0b0-68c9357f17e8.png)
设置在步骤前置前后都会导致步骤的前置脚本中设置的变量失效，脚本都是执行了的，就是put的变量失效无法在入参中用${}获取到了

**Comment by song-tianyang** [comment]
您好，响应中的控制台有报错吗

**Comment by wszbc** [comment]
> 您好，响应中的控制台有报错吗

没有报错，我本来写到前置的，因为每个接口都要用调试好了搬到全局里面去的
![image](https://user-images.githubusercontent.com/40912823/154185138-70e59fc1-db0d-4689-a4a8-938135ba28cf.png)
单纯的${}获取变量失效

**Comment by wszbc** [comment]
> > 您好，响应中的控制台有报错吗
> 
> 没有报错，我本来写到前置的，因为每个接口都要用调试好了搬到全局里面去的 ![image](https://user-
![image](https://user-images.githubusercontent.com/40912823/154186240-35600af0-d261-4981-bb22-aca4cb4c450e.png)
单纯的${}获取变量失效

**Comment by wszbc** [comment]
> > > 您好，响应中的控制台有报错吗
> > 
> > 
> > 没有报错，我本来写到前置的，因为每个接口都要用调试好了搬到全局里面去的
> > ![image](https://user-images.githubusercontent.com/40912823/154186240-35600af0-d261-4981-bb22-aca4cb4c450e.png)
> > 单纯的${}获取变量失效

**Comment by song-tianyang** [comment]
您好，我仔细按照您的写法试了试。
您一共有两个疑问： 1.为什么json里设置了参数提取但是没有提取到； 2.为什么控制台中也没有打印出来

**1.为什么json设置了参数提取但是没有取到：**
因为您在json设置中使用了双引号。 "workOrderId":"${workOrderId}"。 双引号导致系统将这个变量看做了一个常量。我这里把双引号去掉之后就能正常获取数据了。 虽然json编辑器可能会报错 （因为不符合json数据格式），但是这并不影响变量的提取。

**Comment by song-tianyang** [comment]
您好，我仔细按照您的写法试了试，现在有了结果。
目前一共是两个问题： 1.为什么json里设置了参数提取但是没有提取到； 2.单纯使用${}获取变量失败

**1.为什么json设置了参数提取但是没有取到：**
因为您在json设置中使用了双引号。 "workOrderId":"${workOrderId}"。 双引号导致系统将这个变量看做了一个常量。我这里把双引号去掉之后就能正常获取数据了。 虽然json编辑器可能会报错 （因为不符合json数据格式），但是这并不影响变量的提取。

**2.单纯使用${}获取变量失败**
因为在脚本中不支持单纯的${}获取变量，用引号扩起来的话它代表常量，不用引号扩起来的话不符合脚本规范。
