### ISSUE TITLE
[BUG]事务控制器下添加引用或复制的场景，场景测试报告和性能测试报告看不到事务控制器下的请求

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10504]
**MeterSphere 版本**

1.10.8-lts  1.17.2

**Bug 描述**

事务控制器下添加引用或复制的场景，场景测试报告和性能测试报告看不到事务控制器下的请求

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/88763608/154002356-9f4befb6-c526-4c20-bedd-de9c231813c7.png)
![image](https://user-images.githubusercontent.com/88763608/154002408-37818d19-88c7-45e9-b72c-0604bc1c6aa2.png)
![image](https://user-images.githubusercontent.com/88763608/154002441-6a5373d8-b617-4ede-a5d6-69afb638ff87.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，是v1.17.2 ，还是1.10.8-lts

**Comment by linfengjjj** [comment]
lts版本存在该问题
