### ISSUE TITLE
[BUG]v1.17.2 测试跟踪 和 接口测试 模块首页的 失败用例TOP10 无数据

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#10501]
每天都有定时任务的测试计划，有失败的用例，这边没有展示
![image](https://user-images.githubusercontent.com/20641051/153991093-97cc173e-5a15-4ff3-81e4-485f3235cd32.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题
