### ISSUE TITLE
[BUG]接口自动化中运行的接口返回JOSN响应体包含xml内容时，内容中的“<”及空格之类的会乱码，PostMan调用是正常的

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10517]
**MeterSphere 版本**

V1.17.2

**Bug 描述**

接口自动化中运行的接口返回JOSN响应体包含xml内容时，内容中的“<”及空格之类的会乱码，PostMan调用是正常的

**截图**
MS调用结果：
![image](https://user-images.githubusercontent.com/32027713/154016106-571c454a-aa30-4c8d-9980-791442b92c4e.png)

PostMan调用结果：
![image](https://user-images.githubusercontent.com/32027713/154016169-2f895995-7ef4-40f0-b30a-ea6e3feb6d60.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化下

**Comment by fit2-zhao** [comment]
@dashenyucainiao 请问您的接口返回的是什么编码；现在默认是utf-8 您可以自己转码试试。
