### ISSUE TITLE
[BUG]通过case创建的性能测试会自带RunningDebugSampler，导致性能测试结果不准确

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10516]
**MeterSphere 版本**

V1.17.2

**Bug 描述**

通过case创建的性能测试中，生成的jmx文件会自带RunningDebugSampler，导致性能测试结果不准确

**截图**

<img width="850" alt="image" src="https://user-images.githubusercontent.com/32027713/154015476-5f9604f8-a60a-421c-9d1c-33d7a4b81008.png">

![image](https://user-images.githubusercontent.com/32027713/154015509-d2300014-e136-4ffb-9e88-1474a80f3514.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复！

**Comment by youliyuan-fit2cloud** [comment]
v1.17.3版本有修复！
