### ISSUE TITLE
[FEATURE]使用文档结构校验时，如果结构中，没有勾选必含，断言的字段不存在是否可以忽略掉该字段的断言

### ISSUE THREAD

**Issue by nico18576626619** [metersphere/metersphere#10529]
**请描述您的需求或者改进建议.**
使用文档结构校验时，如果结构中，没有勾选必含，断言的字段不存在是否可以忽略掉该字段的断言
![image](https://user-images.githubusercontent.com/19904099/154034161-e9c43d03-389e-4fd0-95c3-69ca2fa3a26a.png)

否则就会报这种断言错误。。，没办法做数据驱动
![480bec0280cf58e1644ce84baab5ee2](https://user-images.githubusercontent.com/19904099/154034242-6cc57ee2-3293-4a1c-8eb4-b05eb87fcaae.png)

**请描述你建议的实现方案**
没有勾选必含时，如果返回结果有断言的字段则进行断言，如果找不到该字段则忽略该字段的断言
勾选必含时则先断言返回中是否含有该字段，如果不含则断言失败，如果含有则继续该字段断言

**Comment by Hyyfit** [comment]
已规划，待排期
