### ISSUE TITLE
[BUG]对已保存的csv数据编辑时，删除csv文件会报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10526]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  对已保存的csv数据编辑时，删除csv文件会报错
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
删除功能正常
**截图**
![66666](https://user-images.githubusercontent.com/83771182/154031878-222f8b72-34cb-401a-ac2e-f5289eb0cd86.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，1.17.1 版本有修复这个问题啊，你升级成功了吗？
