### ISSUE TITLE
[BUG]接口自动化场景后置脚本导入接口时候，只有一个项目时候，点击目录会查不出来接口

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10530]
**MeterSphere 版本**
1.17.2
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口自动化场景后置脚本导入接口时候，只有一个项目时候，点击目录会查不出来接口信息
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
能查询到接口信息
**截图**

如果有截图，请附上截图.
![777](https://user-images.githubusercontent.com/83771182/154035246-771c7925-246c-4321-9eef-f041cd1e2fe6.png)

**Comment by youliyuan-fit2cloud** [comment]
选择的接口定义里面有没有CASE ？
