### ISSUE TITLE
[BUG]定时测试计划不执行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10544]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建添加接口和场景的测试计划
2. 配置串行和并行，加资源池执行
3. 测试跟踪中的测试报告突然停止，且为空
4. 在接口测试模块的报告后于测试计划的报告停止
**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
没有log ?
