### ISSUE TITLE
[BUG]无法和禅道15.4版本进行缺陷同步

### ISSUE THREAD

**Issue by gongwei2020** [metersphere/metersphere#10540]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  集成了禅道并且校验都通过
2. 提交bug后，未在禅道上体现
3. 同步缺陷也无任何显示。

**Comment by youliyuan-fit2cloud** [comment]
你好，请说明MeterSphere版本，项目中是否使用zentao的缺陷模板，然后如果有截图请上传截图
