### ISSUE TITLE
[BUG]接口自动化场景执行CSV文件数据量太大会导致取值失败，从而导致执行失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10543]
**MeterSphere 版本**

V1.17.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 如果csv里面的变量较多，在执行的时候会丢失，比如有80+的变量（列），我们改成30后，就没有丢失
2. 如果有3000行，执行会失败
3. 3000行拆分成3次执行，每次1000行，就都会成功

**期待的正确结果**

正确情况下应该是什么样的？

能给出具体的数量限制，并在页面给出提示

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把csv文件发过来吗？
