### ISSUE TITLE
[BUG] 缺陷同步到禅道  图片丢失 被更换  紧急P0 bug

### ISSUE THREAD

**Issue by renjinxiao** [metersphere/metersphere#10586]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是 
    1.17.2   禅道版本11.6.1

**Bug 描述**

简要描述您碰到的问题
   MeterSphere提交的缺陷 同步到禅道后，里面的图片所有被变更为同一张以前的图片
**Bug 重现步骤**

1.  meterphere 集成禅道
2. meterphere 提交bug 里面包含图片1
3. 同步到禅道的bug里的图片变成图片2
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
meterphere上的缺陷图片
![image](https://user-images.githubusercontent.com/26789277/154208273-30e20e2e-1790-4204-b4e0-04ae22c142bf.png)
禅道中的缺陷图片
![image](https://user-images.githubusercontent.com/26789277/154208189-8257e7a4-d240-409d-8ac7-bc852c9cf1a0.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们尽全力修复中。。。
