### ISSUE TITLE
[FEATURE]建议在测试跟踪里面的测试用例模块前面加上方案设计，没有经过测试方案设计的用例是不饱满的，覆盖度上也做不到

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#10594]
**请描述您的需求或者改进建议.**
建议增加“测试方案”模块，
方案偏面，用例偏点，方案笼统，用例细致
一般这块灵活性可以给大点，允许xmind 思维导图，不强求格式，主要是分析出我们要测试软件的主要方面
一般是不可能直接上来就写用例的，用例也不是想到哪儿写到哪儿，也是根据方案来细化的
方案主要是从大的方面系统的罗列出我们要测试的内容，但是用例就不一样，需要有具体的执行步骤，预期产出，前置条件；用例的原子性比较重要，所以方案和用例是1：N的关系，N（用例）是通过1 按照测试设计方法编写出来的
没有方案的后期用例设计，肯定漏洞百出
![Uploading 123.png…]()

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
目前测试方案可以在脑图模式下设计，我们目前是支持的
