### ISSUE TITLE
[FEATURE]测试跟踪—测试计划—查看测试报告页面，报告总结需要支持上传附件，目前平台的测试报告是简陋的，作为一版计划的完毕，有些统计，平台是做不全的，可以用附件补充，强化测试报告的归档及QA审计

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#10598]
**请描述您的需求或者改进建议.**
[FEATURE]测试跟踪—测试计划—查看测试报告页面，报告总结需要支持上传附件，目前平台的测试报告是简陋的，作为一版计划的完毕，有些统计，平台是做不全的，可以用附件补充，强化测试报告的归档及QA审计

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
感谢建议，我们会对报告做一个优化，目前已经在规划这个了
