### ISSUE TITLE
[BUG]导入测试案例，用例等级未填写，报错的行数错误

### ISSUE THREAD

**Issue by zhulu0912** [metersphere/metersphere#10593]
**MeterSphere 版本**
1.17.2

**Bug 描述**

![image](https://user-images.githubusercontent.com/51916017/154222577-a1cbe797-5adb-43d9-a321-d53026b580d1.png)
![image](https://user-images.githubusercontent.com/51916017/154222600-c826def2-47cf-4504-9457-00f496c7ca83.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，应该取掉了表头那一行，实际的用例行数是对的吧
