### ISSUE TITLE
[BUG]接口测试或者自动化测试中，认证设置如果误选了“No Auth”，会导致接口运行报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10601]
**MeterSphere 版本**

V1.17.2

**Bug 描述**
接口测试或者自动化测试中，认证设置如果误选了“No Auth”，会导致接口运行报错，也没办法切换到啥都不选

**截图**

![image](https://user-images.githubusercontent.com/32027713/154226432-5b3718f1-e154-4efd-93fa-4dc29f8faae4.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化下，可以为空

**Comment by youliyuan-fit2cloud** [comment]
v1.18.0版本中已优化！
