### ISSUE TITLE
[BUG]性能测试高级配置添加自定义变量后会报错，无法解析JMX文件

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10619]
**MeterSphere 版本**

1.17.2

**Bug 描述**

性能测试高级配置添加自定义变量后会报错，无法解析JMX文件
![image](https://user-images.githubusercontent.com/88763608/154260939-613f22f1-da9d-4d13-a6fc-8104102a0900.png)

![image](https://user-images.githubusercontent.com/88763608/154260870-7510a950-3f9c-4c76-b87b-5215a8ff0548.png)

**Comment by zyyfit** [comment]
重复bug https://github.com/metersphere/metersphere/issues/10431，
1.17.3已修复，请升级到最新版再试试
