### ISSUE TITLE
[BUG]场景引用接口无法直接查看接口的子步骤

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10610]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景
2. 创景中引用一个带子步骤的接口用例
3. 查看引用接口的子步骤，发现打不开
4. 只有保存场景后，退出重新进入场景才能打开引用的场景的子步骤

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
我们没复现。。。兄弟，请上传相关截图
