### ISSUE TITLE
[BUG]【接口自动化】在循环控制器里面嵌套另一个循环控制器，里面这个循环控制器的超时时间，每次外面的循环再次循环时，不是重置，而是累加的，保存场景也报错

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#10628]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 v1.16.5-57db8ebd
**Bug 描述**

简要描述您碰到的问题
![44e0ad1d1087f4e1e5ff90e576cfd3a](https://user-images.githubusercontent.com/97216833/154393557-5100e3f0-71b4-42ec-b971-63f40fd93a45.png)
![9776de45598dc384a842da998b18686](https://user-images.githubusercontent.com/97216833/154393671-ee25a7a6-14eb-4fc0-be18-7f9e097e7f93.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/97216833/154393046-649e93b8-8799-4abb-8842-5ecd31629b85.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下
