### ISSUE TITLE
[BUG]功能用例模版添加字段的顺序保存后会自动改变

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10627]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个用例模版
2. 手动添加几个字段
3. 点击保存
4. 查看创建的模版发现字段顺序与添加的顺序不一致

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![wecom-temp-83de6d7e97551f7bdf6fbf1f8c6106b6](https://user-images.githubusercontent.com/36387811/154393000-7631eadc-9ca0-4e5e-95bc-7de6e769fe61.png)

**Comment by youliyuan-fit2cloud** [comment]
后续版本优化下

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复！
