### ISSUE TITLE
[BUG]测试跟踪高级查询出来的结果点击编辑无效

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#10647]
**MeterSphere 版本**

1.17.3

**Bug 描述**
测试跟踪高级查询出来的结果点击编辑无效

**Bug 重现步骤**

1.  测试跟踪--高级查询出来的结果
2. 点击编辑
3. 无效，必须再点一次
4. 

**期待的正确结果**

正确弹出编辑界面

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，测试跟踪-高级查询什么？功能用例吗？ 如果是，没有复现该问题，是否100%出现？

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/154597903-978ff561-739c-4937-8de3-f00193f77d1c.png)
上图区域

**Comment by youliyuan-fit2cloud** [comment]
v1.18.1中已修复
