### ISSUE TITLE
[BUG]OIDC过来的用户邮箱没做重复校验，修改时候添加手机号就会报错了，不能保存

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10641]
**MeterSphere 版本**
V1.17.2

**Bug 描述**
OIDC过来的用户邮箱没做重复校验，修改时候添加手机号就会报错了，不能保存

**截图**

如果有截图，请附上截图.
<img width="836" alt="企业微信截图_16450669122003" src="https://user-images.githubusercontent.com/32027713/154399890-cbfa66f2-35c0-4d72-8e8b-053ac4a6cd3f.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
最新版本已优化，请更新一下吧
