### ISSUE TITLE
[QUESTION]MS在公司推广遇到的问题

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#10646]
**请描述您的问题.**
目前在推广这个软件，但是员工跟领导反馈存在以下问题：
【P0】9986   评审通过得用例进行编辑时，状态未变更为未评审
已经在排期了（1.18.0没有，至少放再这个版本或者提前，不然不利于部门本年度工作安排。这个太影响这个软件的推广了），请问何时，这个功能很重要，直接影响测试跟踪模块的使用。因为迭代过程经常发生用例变更，而且需要评审，现在不支持。此功能直接影响使用非常大。本来打算使用这个做用例评审的，结果还不如excel+GIT组合方式
【P0】9799【重要】功能用例无法满足产品迭代使用
场景：A模块发生了需求变更，存在很多新增用例和修改用例，目前没有便捷方式快速修改。之前使用excel整体还是直观的。所以提可这个9799，就按模块生成excel，然后直接编辑、修改、新增、删除。保存之后就是现在的列表，同时修改的都是未评审的用例，跟9986情况结合起来
【P1】9564 海量用例当中插入一条用例体验极差【重要】
在列表模式任一个位置新增一条用例这种场景很多，目前支持拖拽，建议最直接还是在任一位置新增（脑图新增插入责任人取值有缺陷，还要就是很多字段操作不连续，使用不好）

**Comment by legend818** [comment]
能来个人交流交流么

**Comment by luty2018** [comment]
【P0】9986 评审通过得用例进行编辑时，状态未变更为未评审
-- 这个问题我们目前是用版本来解决的，版本在我们企业版，你可以申请试用
【P0】9799【重要】功能用例无法满足产品迭代使用
--你可以导出成Excel修改再导入系统，你描述的方式是个很好的创意，但是我们暂时还没有规划要做
【P1】9564 海量用例当中插入一条用例体验极差【重要】
--这个可以先支持
