### ISSUE TITLE
[BUG]npm run build occurs erros.

### ISSUE THREAD

**Issue by mfwildfire** [metersphere/metersphere#10665]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是1.17分支

**Bug 描述**

[INFO] --- frontend-maven-plugin:1.9.1:npm (npm run build) @ frontend ---
[INFO] Running 'npm run build' in C:\github\metersphere\frontend
[INFO] 
[INFO] > vue-demo@0.1.0 build C:\github\metersphere\frontend
[INFO] > export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build
[INFO] 
[INFO] 'export' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
[INFO] ���������ļ���
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the vue-demo@0.1.0 build script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\ruijie\AppData\Roaming\npm-cache\_logs\2022-02-17T06_44_54_906Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for metersphere 1.17:
[INFO] 
[INFO] metersphere ........................................ SUCCESS [  0.003 s]
[INFO] frontend ........................................... FAILURE [01:11 min]
[INFO] backend ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Bug 重现步骤**

1.  mvn compile
2. 
3. 
4. 

**期待的正确结果**

mvn编译成功

**截图**

![image](https://user-images.githubusercontent.com/97585957/154422232-10e6b230-15cc-4355-841f-161a65e4b37b.png)

**Comment by mfwildfire** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\github\\metersphere\\frontend\\node\\node.exe',
1 verbose cli   'C:\\github\\metersphere\\frontend\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v16.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-demo@0.1.0~prebuild: vue-demo@0.1.0
6 info lifecycle vue-demo@0.1.0~build: vue-demo@0.1.0
7 verbose lifecycle vue-demo@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-demo@0.1.0~build: PATH: C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\github\metersphere\frontend\node_modules\.bin;C:\github\metersphere\frontend\node;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\ruijie\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\ruijie\AppData\Local\Programs\Python\Python39\;C:\Users\ruijie\AppData\Local\Microsoft\WindowsApps;C:\Users\ruijie\AppData\Roaming\npm;
9 verbose lifecycle vue-demo@0.1.0~build: CWD: C:\github\metersphere\frontend
10 silly lifecycle vue-demo@0.1.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build'
10 silly lifecycle ]
11 silly lifecycle vue-demo@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle vue-demo@0.1.0~build: Failed to exec build script
13 verbose stack Error: vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:390:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:390:28)
13 verbose stack     at maybeClose (node:internal/child_process:1064:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14 verbose pkgid vue-demo@0.1.0
15 verbose cwd C:\github\metersphere\frontend
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\github\\metersphere\\frontend\\node\\node.exe" "C:\\github\\metersphere\\frontend\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v16.10.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
22 error Exit status 1
23 error Failed at the vue-demo@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by liuruibin** [comment]
下载项目后在工程目录中执行 mvn package, 这样会使用我们pom里指定的node和npm来下载前端的依赖包，执行时间看网络情况。执行完成后就能看到前后端都构建完成，idea中用main方法启动后端，npm run 启动前端就可以使用了

**Comment by mfwildfire** [comment]
![image](https://user-images.githubusercontent.com/97585957/154624520-049b331d-cea9-48e1-a7e3-e351484cf6f2.png)
backend pom中部分插件显示notf found，是否有影响，如何修复。

**Comment by mfwildfire** [comment]
> 下载项目后在工程目录中执行 mvn package, 这样会使用我们pom里指定的node和npm来下载前端的依赖包，执行时间看网络情况。执行完成后就能看到前后端都构建完成，idea中用main方法启动后端，npm run 启动前端就可以使用了。有些包需要镜像下载可以自己配置

同意你说的操作，应该是按照操作能顺利完成才对，但我这边记录的现象，就是mvn package后frontend那步都没有过，错误如最上面描述。我这边网络github都没问题，npm和node都可以完成，npm run build那步骤报错，如图
![image](https://user-images.githubusercontent.com/97585957/154625503-12b5d6bc-4765-4be0-b309-46f1499debb1.png)
你看是否和工程里这些插件报错有关系
![image](https://user-images.githubusercontent.com/97585957/154625547-5be04764-5f8e-4716-bc65-38f103962a09.png)
但我又不知道如何解决，ideaj清缓存，mvn reload都试过了。

**Comment by mfwildfire** [comment]
另外backend这些没引进来的插件，是否因为maven setting的影响，能给我贴一份maven setting参考吗

**Comment by mfwildfire** [comment]
我尝试修复了这个问题，原来的pom里plugin中有的没有指定版本，有的没有groupid ：（，指定后修复了图中问题
![image](https://user-images.githubusercontent.com/97585957/154636528-6c53ae82-e3ce-4910-b075-eaf4f84c51ba.png)

但是，工程根目录，mvn clean package -U，frontend编译仍然报错，还是上面记录的那个错误
![image](https://user-images.githubusercontent.com/97585957/154636528-6c53ae82-e3ce-4910-b075-eaf4f84c51ba.png)

**Comment by liuruibin** [comment]
这些版本不需要指定，左边有个蓝色的标记表示这个插件是继承过来的，当然你指定具体的版本也可以
<img width="844" alt="image" src="https://user-images.githubusercontent.com/23045261/154644266-57a360f5-2b66-4c76-8122-fdb94654ff6c.png">

**Comment by mfwildfire** [comment]
使用mvnw之前保证工程干净，.m2下也清空，执行./mvnw.cmd，网络翻墙，可以连接github，可以看到从repo.maven下载，存到.m2下的repo，前面一切顺利，直到下面的错误出现，和之前现象基本一样。
 --- frontend-maven-plugin:1.9.1:npm (npm run build) @ frontend ---
[INFO] Running 'npm run build' in C:\github\metersphere\frontend
[INFO]
[INFO] > vue-demo@0.1.0 build C:\github\metersphere\frontend
[INFO] > export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build
[INFO]
[INFO] 'export' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
[INFO] ▒▒▒▒▒▒▒▒▒ļ▒▒▒
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR!
[INFO] npm ERR! Failed at the vue-demo@0.1.0 build script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\ruijie\AppData\Roaming\npm-cache\_logs\2022-02-18T15_18_04_976Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for metersphere 1.17:
[INFO]
[INFO] metersphere ........................................ SUCCESS [ 54.736 s]
[INFO] frontend ........................................... FAILURE [03:34 min]
[INFO] backend ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:06 min
[INFO] Finished at: 2022-02-18T23:18:04+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:npm (npm run build) on project frontend: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by liuruibin** [comment]
> 另外backend这些没引进来的插件，是否因为maven setting的影响，能给我贴一份maven setting参考吗

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <localRepository>${user.home}/.m2/repository</localRepository>
  <pluginGroups>
    <pluginGroup>com.spotify</pluginGroup>
  </pluginGroups>

  <profiles>
    <profile>
      <id>jdk-1.8</id>
      <activation>
        <activeByDefault>true</activeByDefault>
        <jdk>1.8</jdk>
      </activation>
      <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.compilerVersion>1.8</maven.compiler.compilerVersion>
      </properties>
    </profile>


  </profiles>
  <activeProfiles>
    <activeProfile>jdk-1.8</activeProfile>
  </activeProfiles>

**Comment by mfwildfire** [comment]
嗯嗯，maven插件这个应该是和setting.xml有关，我给你一份我的。
<?xml version="1.0" encoding="UTF-8"?>

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  
  <localRepository>C:\repository</localRepository>
  
  <mirrors>
    
    <mirror>
        <id>alimaven</id>
        <mirrorOf>central</mirrorOf>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/repositories/central/</url>
    </mirror>
    <mirror>
        <id>alimaven</id>
        <name>aliyun maven</name>
        <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
    <mirror>
        <id>central</id>
        <name>Maven Repository Switchboard</name>
        <url>http://repo1.maven.org/maven2/</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
    <mirror>
        <id>repo2</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://repo2.maven.org/maven2/</url>
    </mirror>
    <mirror>
        <id>ibiblio</id>
        <mirrorOf>central</mirrorOf>
        <name>Human Readable Name for this Mirror.</name>
        <url>http://mirrors.ibiblio.org/pub/mirrors/maven2/</url>
    </mirror>
    <mirror>
        <id>jboss-public-repository-group</id>
        <mirrorOf>central</mirrorOf>
        <name>JBoss Public Repository Group</name>
        <url>http://repository.jboss.org/nexus/content/groups/public</url>
    </mirror>
    <mirror>
        <id>google-maven-central</id>
        <name>Google Maven Central</name>
        <url>https://maven-central.storage.googleapis.com
        </url>
        <mirrorOf>central</mirrorOf>
    </mirror>
    
    <mirror>
        <id>maven.net.cn</id>
        <name>oneof the central mirrors in china</name>
        <url>http://maven.net.cn/content/groups/public/</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
  <profiles>
  </profiles>
</settings>

**Comment by mfwildfire** [comment]
![image](https://user-images.githubusercontent.com/97585957/154874368-d27a6b2d-d18a-427b-a674-157fcf61a322.png)
![image](https://user-images.githubusercontent.com/97585957/154874390-85aed02a-ddef-4eeb-ba26-32b672c7df75.png)

**Comment by mfwildfire** [comment]
更改为你给的maven setting后，terminal执行mvnw命令 ./mvnw clean compile
![image](https://user-images.githubusercontent.com/97585957/154874939-1d8ae6f4-4e90-4654-a593-ee6308927785.png)
log文件内容如下：
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\github\\metersphere\\frontend\\node\\node.exe',
1 verbose cli   'C:\\github\\metersphere\\frontend\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v16.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-demo@0.1.0~prebuild: vue-demo@0.1.0
6 info lifecycle vue-demo@0.1.0~build: vue-demo@0.1.0
7 verbose lifecycle vue-demo@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-demo@0.1.0~build: PATH: C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\github\metersphere\frontend\node_modules\.bin;C:\github\metersphere\frontend\node;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\maven\bin\;C:\Program Files\Java\jdk1.8.0_321\bin\;C:\Program Files\Java\jdk1.8.0_321\jre\bin\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\ruijie\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\ruijie\AppData\Local\Programs\Python\Python39\;C:\Users\ruijie\AppData\Local\Microsoft\WindowsApps;C:\Users\ruijie\AppData\Roaming\npm;C:\Users\ruijie\AppData\Local\Programs\Microsoft VS Code\bin;
9 verbose lifecycle vue-demo@0.1.0~build: CWD: C:\github\metersphere\frontend
10 silly lifecycle vue-demo@0.1.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build'
10 silly lifecycle ]
11 silly lifecycle vue-demo@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle vue-demo@0.1.0~build: Failed to exec build script
13 verbose stack Error: vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:390:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\github\metersphere\frontend\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:390:28)
13 verbose stack     at maybeClose (node:internal/child_process:1064:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
14 verbose pkgid vue-demo@0.1.0
15 verbose cwd C:\github\metersphere\frontend
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\github\\metersphere\\frontend\\node\\node.exe" "C:\\github\\metersphere\\frontend\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v16.10.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error vue-demo@0.1.0 build: `export NODE_OPTIONS=--max_old_space_size=4096 && vue-cli-service build`
22 error Exit status 1
23 error Failed at the vue-demo@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mfwildfire** [comment]
![image](https://user-images.githubusercontent.com/97585957/154876137-9a73737e-1d1a-42f9-83a3-0737d1cdfbcf.png)
我怀疑是构建过程依赖与linux系统特有的export，而windows平台没有，从而后续报错，你觉得呢？

**Comment by liuruibin** [comment]
windows 的话你试试
<img width="953" alt="image" src="https://user-images.githubusercontent.com/23045261/155076448-b21590b7-e0da-4903-b271-0dcde61a902c.png">
这个

**Comment by mfwildfire** [comment]
![image](https://user-images.githubusercontent.com/97585957/155168362-8a314027-1443-4f10-94d5-644e96ee8878.png)
感谢帮助，试了一下，前端目录，使用npm run build-win可以构建成功

那程序默认是npm run build
![image](https://user-images.githubusercontent.com/97585957/155168582-6de15aa5-c78e-45ff-983a-4d6f45ff6b48.png)
metersphere应该在哪里做怎样的修改呢，根据系统来判定执行指令？你们更新分支，我再拉取最新代码？：）

**Comment by liuruibin** [comment]
这里应该不会再进行修改了，以前没有 export 和 set 只有后面的 vue-cli-service build, 这样在一些配置比较差的电脑上会构建失败，之后加上了启动配置

**Comment by mfwildfire** [comment]
那为什么windows系统没有识别后，走set进行处理呢，而走export，这个逻辑好像有问题
