### ISSUE TITLE
[BUG]手动使用jmeter命令行启动压测可以到16w，但是ms启动压测只能到1w左右

### ISSUE THREAD

**Issue by hlf3300** [metersphere/metersphere#10673]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？ 1.17.2

**Bug 描述**

简要描述您碰到的问题
手动使用jmeter命令行启动压测可以到16w，但是ms启动压测只能到1w左右
![image](https://user-images.githubusercontent.com/10719065/154437391-9db7c0b5-d5ed-412e-b2a4-48062498f491.png)
![image](https://user-images.githubusercontent.com/10719065/154437420-e31b33eb-eda9-4171-81ba-8c96bfb14149.png)

同样的压测客户端、并发数、服务端；

**Bug 重现步骤**

1.  看问题描述；
2.  实际排查的时候 用ms启动的jmeter java进程无法用jstack查看
![image](https://user-images.githubusercontent.com/10719065/154437695-f4dc36f3-c651-4b71-b3d4-1bd38b11190a.png)

3. 
4. 

**期待的正确结果**

ms启动压测与手动启动jmeter压测，结果应该一致；

**截图**

如果有截图，请附上截图.

**Comment by hlf3300** [comment]
推测可能的原因：
ms启动和手动启动的差异在于采集性能指标，
ms启动是要将性能数据存储到kafka，推测是不是收集性能数据影响了jmeter压测线程的调度，导致压力上不来；

**Comment by liuruibin** [comment]
我们采用了后置监听器来处理实时报告，如果响应很快的话，kafka很快就成为瓶颈，如果继续这种模式可以增加kafka集群和data-streaming的数量来扩展。我们在企业版中提供了本地计算结果的模式，去掉后置监听的kafka，性能和本地执行几乎没有差别。你可以先试用企业版看看效果
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/23045261/154458299-7d9d0a0e-0c91-4854-a6fe-b65c15f9890e.png">
选择关闭后置监听器是企业版的功能
