### ISSUE TITLE
[BUG]自定义请求将请求头作为query参数

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10683]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
17.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建自定义请求1，添加提取参数1
2. 提取的参数作为第二个自定义接口的请求头参数
3. 执行后发现第二个自定义请求的请求内容错误
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/154446276-bc58add1-50e3-469c-983e-4322ed0580d7.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现啊。

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
