### ISSUE TITLE
[BUG]性能执行过程中，执行时长，开始时间显示异常

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#10684]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.2

**Bug 描述**

简要描述您碰到的问题
性能执行过程中，执行时长，开始时间显示异常
![image](https://user-images.githubusercontent.com/5198427/154446142-c9c665da-6ea1-4d95-bc11-f3b116f9188d.png)

**Bug 重现步骤**

1.  jmeter创建性能测试脚本demo.jmx包含CSV配置元件，并设置需要读取的文件“data.txt”
2. 上传步骤1中的demo.jmx到MeterSphere平台，但不上传数据文件data.txt
3. 创建一个性能测试任务，选择步骤2中的demo.jmx脚本
4. 保存执行性能测试
jmeter脚本截图如下所示：
![image](https://user-images.githubusercontent.com/5198427/154447282-e7298c1f-e548-448d-b48a-62c87f1711ee.png)
补充说明：上传的demo.jmx脚本中实际请求中无需读取数据文件data.txt，另外在本地删除CSV配置元件后，重新上传该脚本
能正常执行并显示时间。
**期待的正确结果**

正确情况下应该是什么样的？
性能测试正常执行，执行时长，开始时间显示正常
**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下，提示缺陷csv文件
