### ISSUE TITLE
[BUG]上传用例维护人为jsjolene，提示该工作空间下无该用户

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#1068]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.0
**Bug 描述**
简要描述您碰到的问题
上传用例维护人为jsjolene，提示该工作空间下无该用户，其他用户可以正常操作
**Bug 重现步骤**
1.  上传用例
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
上传成功
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，用例模板中的维护人需要是当前工作空间中的已有用户
