### ISSUE TITLE
[BUG] 1.17分支下载源码部署后，控制台出现大量VUE组件未注册的告警

### ISSUE THREAD

**Issue by starztp** [metersphere/metersphere#10699]
**MeterSphere 版本**

1.17以及master分支

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  从https://github.com/metersphere/metersphere上clone代码，分支切到1.17
2. 按照官方文档https://metersphere.io/docs/dev_manual/提供的操作步骤，后端服务启动后进入项目的frontend页面执行npm install,npm run serve启动前端服务
3. 打开chrome控制台，访问接口测试-接口自动化以及接口测试-接口定义页面（其它页面没有检查），发现控制台有大量的VUE组件报错，如图
![image](https://user-images.githubusercontent.com/25835562/154483364-c44de37a-01e8-46c3-9696-801a7de136d5.png)

附上相关代码，我观察到的未注册的组件都是基于这种xpack的写法，希望能对你们有所帮助
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25835562/154484263-d0f792fd-f29b-4089-9ecb-d0a31afb6d60.png">

**Comment by zyyfit** [comment]
您好，我们的最新release版本没有复现这个问题，master分支以及其他非release分支都是不稳定版本，建议您使用release版本

**Comment by starztp** [comment]
下载最新的https://github.com/metersphere/metersphere/releases/tag/v1.17.3 release分支代码压缩包部署后仍会出现这个问题

**Comment by zyyfit** [comment]
您好，您如果是直接安装使用我们的系统，可以使用我们的安装脚本直接进行安装部署，
如果您想使用我们的代码运行进行二次开发等操作，可以添加我们的企业微信群，联系一下工作人员，他们会给你处理方式

**Comment by starztp** [comment]
不止我一个人有这样的问题，社区群里也有其它人在反馈，希望官方能深入排查一下造成这个问题的原因，我用的是mac系统

**Comment by zhouluowu** [comment]
你好，有解决嘛
