### ISSUE TITLE
导入大量excel用例，后台报错过多导致服务宕机

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10698]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
<img width="1255" alt="b08b9b6c-f7c8-41e1-bdfd-96139740b915" src="https://user-images.githubusercontent.com/88763608/154475146-634182e3-070d-4307-82ad-aef8ce6264d5.png">

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1、这个报错是插入操作日志的报错，已经发现了这个问题，后续版本修复
2、导入大量excel用例，具体是指多少呢？
