### ISSUE TITLE
[BUG]接口自动化-场景里面,把接口关闭再调试,会一直loading

### ISSUE THREAD

**Issue by jackelchen** [metersphere/metersphere#10695]
**MeterSphere 版本**

v1.17.2-067bbbdc

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/15845086/154463389-9bd3afe3-4ad8-4055-bb19-b5ee907daa6c.png)

**Comment by zyyfit** [comment]
1.18.0已修复
