### ISSUE TITLE
[BUG]源代码clone后部署完成，出现静态资源缺失

### ISSUE THREAD

**Issue by starztp** [metersphere/metersphere#10700]
**MeterSphere 版本**

1.17，master

**Bug 描述**

源代码clone后部署完成，出现静态资源缺失,1.17和master分支都有这个问题

**Bug 重现步骤**

1.  从https://github.com/metersphere/metersphere上clone代码，分支切到1.17
2. 照官方文档[https://metersphere.io/docs/dev_manual/提供的操作步骤，后端服务启动后进入项目的frontend页面执行npm install,npm run serve启动前端服务
3. 服务启动后发现登陆界面缺少图片，登陆后在左上角也缺失相应图片，如图

![image](https://user-images.githubusercontent.com/25835562/154486599-98224b57-df7f-41b3-8219-eff8e4171660.png)
![image](https://user-images.githubusercontent.com/25835562/154486659-ceafad7f-9b0c-43ee-818c-557e55663c15.png)

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/10699

**Comment by starztp** [comment]
下载最新的https://github.com/metersphere/metersphere/releases/tag/v1.17.3 release分支代码压缩包部署后仍会出现这个问题

**Comment by zyyfit** [comment]
您好，您如果是直接安装使用我们的系统，可以使用我们的安装脚本直接进行安装部署，
如果您想使用我们的代码运行进行二次开发等操作，可以添加我们的企业微信群，联系一下工作人员，他们会给你处理方式

**Comment by starztp** [comment]
不止我一个人有这样的问题，社区群里也有其它人在反馈，希望官方能深入排查一下造成这个问题的原因，我用的是mac系统
