### ISSUE TITLE
[BUG]离线安装完成之后,重启服务器就启动不来了

### ISSUE THREAD

**Issue by ikenneth** [metersphere/metersphere#10704]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是:v1.17.3-1acdbd2e

**Bug 描述**

离线安装完成之后,重启服务器就启动不来了,后面是通过手动启动对用的docker容器解决，不过以后重启还是会出这个问题。
而且安装的docker没有做开机启动

**Bug 重现步骤**

1.  新服务器离线安装完成之后登陆成功
2. 重启服务器
3. docker服务没有自动启动
4. 配置了docker开机启动，容器服务自动启动也会报错

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="955" alt="image" src="https://user-images.githubusercontent.com/7484551/154525540-cf08f7d3-dc6a-4f87-a713-85806f745267.png">

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，目前没有设置重启服务器后自动重启MeterSphere服务，需要手动启动，如果这个诉求的用户比较多我们会考虑优化的

**Comment by youliyuan-fit2cloud** [comment]
v1.19以上版本，重启服务器可以自启动了，但是要注意docker要先起来
