### ISSUE TITLE
[BUG]1.17分支下载源码部署后，创建场景保存失败

### ISSUE THREAD

**Issue by starztp** [metersphere/metersphere#10701]
**MeterSphere 版本**

1.17（切到Master分支没有这个问题）

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  从https://github.com/metersphere/metersphere上clone代码，分支切到1.17
2. 按照官方文档[https://metersphere.io/docs/dev_manual/提供的操作步骤，后端服务启动后进入项目的frontend页面执行npm install,npm run serve启动前端服务
3. 在默认项目中创建一级模块“数据资产”和二级模块“变量管理”
4. 在模块“变量管理”下创建场景，输入场景名称“变量不可重复”，点击保存，出现前端报错，如图
![image](https://user-images.githubusercontent.com/25835562/154488783-c6e58a8d-ccfc-49f0-a008-7a92824efc23.png)

定位到报错行号，加了日志
<img width="906" alt="image" src="https://user-images.githubusercontent.com/25835562/154488986-b6d2ee5e-ef47-4dd4-bf9e-56fd3bbc9d97.png">

看控制台输出日志发现这个currentVersion对象就是undefined
![image](https://user-images.githubusercontent.com/25835562/154489046-662848a4-969e-440f-9b17-bf0935636372.png)

**Comment by zyyfit** [comment]
跟前两个问题一样，建议您使用最新release版本，根据我们的部署文档进行部署
![image](https://user-images.githubusercontent.com/73461316/154501174-b01709e0-3fcc-4ea1-836b-a85750aa7c7d.png)

**Comment by zyyfit** [comment]
您好，您如果是直接安装使用我们的系统，可以使用我们的安装脚本直接进行安装部署，
如果您想使用我们的代码运行进行二次开发等操作，可以添加我们的企业微信群，联系一下工作人员，他们会给你处理方式

**Comment by starztp** [comment]
不止我一个人有这样的问题，社区群里也有其它人在反馈，希望官方能深入排查一下造成这个问题的原因，我用的是mac系统

**Comment by zyyfit** [comment]
> 不止我一个人有这样的问题，社区群里也有其它人在反馈，希望官方能深入排查一下造成这个问题的原因，我用的是mac系统

我们交流群里有售后团队专门处理这种问题，你在哪个交流群？方便艾特我一下吗？我群里帮你问问

**Comment by shenkaibo** [comment]
拉一下 V1.18 分支代码试试
