### ISSUE TITLE
[BUG]LDAP已经配置成功,登录报错

### ISSUE THREAD

**Issue by ikenneth** [metersphere/metersphere#10703]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是:v1.17.3-1acdbd2e

**Bug 描述**

LDAP已经配置成功连接成功,登录的时候提示报错

**Bug 重现步骤**

1. 直接用测试登录就报错了

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="792" alt="image" src="https://user-images.githubusercontent.com/7484551/154523733-8f5c9e83-1204-4ade-93ec-cb231eb294b0.png">
<img width="813" alt="image" src="https://user-images.githubusercontent.com/7484551/154523787-83d99499-77d7-4d0e-89d9-9bae4883298f.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我们这里是可以的，是不是ou或者其他地方配置不对呢
![图片](https://user-images.githubusercontent.com/73461316/154608530-fc44ad19-b628-41e5-a496-63f9fa27bcb6.png)

**Comment by ikenneth** [comment]
我是在jumpserver上面复制过来的，jumpserver上面是可以正常使用

**Comment by zyyfit** [comment]
> 我是在jumpserver上面复制过来的，jumpserver上面是可以正常使用

jumpserver和metersphere还是有一定的区别的，我们的产品没有统一处理。。

**Comment by yjjejek** [comment]
> 我是在jumpserver上面复制过来的，jumpserver上面是可以正常使用

那应该是过滤器的问题了，把过滤器改掉，改成: uid={0} 就可以了

jumpserver的过滤器有区别
