### ISSUE TITLE
[BUG]在接口自动化中可以写入到服务器的文件，转成性能测试就无法写入

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10705]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建场景用例
2. 添加接口
3. 添加后置脚本
4. 执行后可以写入在安装ms的服务器，转成性能测试后无法写入文件

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

String recode = vars.get("recode");
String msg = vars.get("msg");

if(recode.equals("-505")){
    String id = vars.get("id");
    log.info("id=====" +id);
    FileWriter fstream = new FileWriter("/opt/metersphere/data/cmq/personId.txt", true);
    try{
        BufferedWriter bstream = new BufferedWriter(fstream);
        //bstream.write("");
        bstream.write(id +"---" +msg +"\n");
        bstream.close();
    }catch (IOException e){
        e.printStackTrace();
    }
    fstream.close();
}

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
性能测试使用新启动的容器来执行，容器相互隔离，写入的文件只能在性能测试运行时的容器里找到，执行结束后容器删除，文件就找不到了
