### ISSUE TITLE
[BUG]存在多个自定义请求与场景组合的接口自动化场景，自定义请求的提参在下个自定义请求中获取的不是最新的提参值，请定位并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10702]
**MeterSphere 版本**

v1.17.2

**Bug 步骤及描述**

1.单点登录获取token的CASE，由3个自定义请求组成，，单独执行这个CASE，3个自定义语句都成功
2.当两个场景组合，【登录获取token】的第2，3个自定义一直失败，查看了第2个自定义请求的参数，发现它使用的是自定义语句1缓存的state和Client参数，并不是自定义请求1最新一次返回的参数

**截图**
自由自定义请求时，各请求均成功：
![image](https://user-images.githubusercontent.com/92150453/154507038-f8a2f07e-f8fd-4618-89cc-48828296848a.png)

自定义请求1：
![image](https://user-images.githubusercontent.com/92150453/154507299-c19caaba-5a60-454b-937f-eb0a0c1b987e.png)
![image](https://user-images.githubusercontent.com/92150453/154507439-e650118e-38e0-4746-873f-0b222782c92f.png)

自定义请求2：
![image](https://user-images.githubusercontent.com/92150453/154507455-e0c32d85-f0e9-46f0-b5db-90bc5342c8c2.png)
![image](https://user-images.githubusercontent.com/92150453/154507500-215ab156-5147-4ac2-ba47-a53b076a318f.png)

自定义请求3：
![image](https://user-images.githubusercontent.com/92150453/154507544-b0f862f4-dcb1-4dee-8876-74ff9dba5f18.png)
![image](https://user-images.githubusercontent.com/92150453/154507565-f6fb10d9-33c7-45d6-bf54-73c72430d3ca.png)

两个场景组合时：
![image](https://user-images.githubusercontent.com/92150453/154508337-98538672-7b6e-488b-8398-2e67e6fedc49.png)

**Comment by sageonedream** [comment]
原始场景我稍后和客户沟通下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月18日(周五) 上午10:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]存在多个自定义请求与场景组合的接口自动化场景，自定义请求的提参在下个自定义请求中获取的不是最新的提参值，请定位并修改 (Issue #10702)




 
您好，我在1.17.3版本没有复现这个问题，您可以升级到1.17.3试试，或者您方便把这两个原始场景导出来给我们看看吗？可以把url地址删掉或者随便填一个
 
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sageonedream** [comment]
用户的原始场景文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]存在多个自定义请求与场景组合的接口自动化场景，自定义请求的提参在下个自定义请求中获取的不是最新的提参值，请定位并修改 (Issue #10702)





 
好的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
1.18.0已修复
