### ISSUE TITLE
[BUG]回收站选中所有数据，批量删除只删除10条数据

### ISSUE THREAD

**Issue by xingchun-chen** [metersphere/metersphere#10726]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17.2
**Bug 描述**

回收站选中所有数据，批量删除只删除10条数据

**Bug 重现步骤**

<img width="557" alt="image" src="https://user-images.githubusercontent.com/55787491/154635597-578e648d-432d-4fb9-bd54-1d63a68dca0b.png">
<img width="522" alt="image" src="https://user-images.githubusercontent.com/55787491/154635647-a0628214-6e0c-4db1-a521-42aabea28bc0.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题

**Comment by youliyuan-fit2cloud** [comment]
最新版本已修复，更新一下吧
