### ISSUE TITLE
[BUG]采用JIRA自己的缺陷模板创建缺陷，JIRA管理员可以成功，JIRA项目管理员创建失败并报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10722]
**MeterSphere 版本**

V1.17.3

**Bug 描述**
采用JIRA自己的缺陷模板创建缺陷，
1、不绑定个人账号，采用JIRA管理员可以成功
2、采用个人账号且角色为JIRA项目管理员创建失败并报错

主要集中在“报告人”这个字段，报错如下：
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/32027713/154629927-eb7a1fcf-eb74-4d0c-bb9d-463ae09e4240.png">

**截图**

如果有截图，请附上截图.
JIRA系统管理员登录后查看字段：
![image](https://user-images.githubusercontent.com/32027713/154630259-dffd37a2-33b7-4ce7-a1d9-9bd41c2d5ca5.png)

JIRA项目管理员登录后查看字段：
![image](https://user-images.githubusercontent.com/32027713/154630276-f0ea679c-2345-4e18-b2e4-cbfffbabceba.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.18.0中已优化，建议升级一下
