### ISSUE TITLE
[BUG]JIRA配置好之后，缺陷可以同步到，但是需求拉不到数据

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#10723]
**MeterSphere 版本**
V1.17.3

**Bug 描述**

JIRA配置好之后，缺陷可以同步到，但是需求拉不到数据

**截图**

如果有截图，请附上截图.
<img width="842" alt="image" src="https://user-images.githubusercontent.com/32027713/154630458-7ae78bad-a4ad-4ae7-9f44-12b4ab984f7e.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/32027713/154630484-57b4607e-3378-4ad8-9c53-56e0f5db3047.png">

<img width="561" alt="image" src="https://user-images.githubusercontent.com/32027713/154630512-ccb4daf5-9765-47cf-8179-0c489660da74.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下

**Comment by youliyuan-fit2cloud** [comment]
最新版本已修复，请更新一下吧
