### ISSUE TITLE
[v1.6]

### ISSUE THREAD

**Issue by ed-NCC-1701-B** [metersphere/metersphere#1073]
**问题/需求描述**
简要描述您碰到的问题或您面临的需求

创建新场景，步骤为空的时候点击调试，会弹出报告页面，一直空转。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/73098982/103747822-3312da00-503e-11eb-9ec5-f69c7aa9d5e6.png)
![屏幕快照 2021-01-06 下午4 35 21](https://user-images.githubusercontent.com/73098982/103747840-37d78e00-503e-11eb-979f-ce4c5c9a2024.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已修复该问题
