### ISSUE TITLE
[FEATURE]接口自动化场景中建议增加集合

### ISSUE THREAD

**Issue by jackelchen** [metersphere/metersphere#10739]
**请描述您的需求或者改进建议.**
在场景中可能有大量接口,调试的时候为了效率想只运行几个有关联接口,如果要手动把其他接口一个一个关闭很废操作

**请描述你建议的实现方案**
1.接口自动化里面的场景步骤建议增加一个类似文件夹的组件,方便把接口请求简单归类并用开关控制是否执行
2.各种控制器增加名称

**Comment by Hyyfit** [comment]
我们下一个版本会做场景自动化使用的优化，可以实现批量开启关闭
