### ISSUE TITLE
[BUG]swagger通过json导入，导入不成功

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10747]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  swagger通过json导入，导入不成功
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
导入成功
**截图**
<img width="960" alt="1111" src="https://user-images.githubusercontent.com/83771182/154656028-a08ea04f-99f5-4517-8c4f-2c266d588ef8.png">

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，请提供ms版本，swagger版本，log
