### ISSUE TITLE
[BUG]全局变量和自定义脚本设置的变量重名时，不应该全局变量生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10746]
**MeterSphere 版本**

1.17.3

**Bug 描述**

全局变量和自定义脚本设置的变量重名时，全局变量优先了
应该按照就近原则，自定义脚本里的变量优先生效

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，貌似你说的有点道理，我们讨论下

**Comment by linfengjjj** [comment]
已关闭
