### ISSUE TITLE
【报表相关】测试结果中可以展示jenkins编译的job名称及build-id

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1077]
**请描述您的需求或者改进建议.**
从jenkins触发测试，测试次数比较多时，查看某次测试报告时，希望定位是哪次jenkins build，然后定位版本发布信息。目前是无法反过来定位的，只能通过大致的时间点来推测。

希望能在结果中显示jenkins的job名称以及jenkins的build-id，可以反向查找到jenkins 的 build

**Comment by ed-NCC-1701-B** [comment]
测试报告中添加触发者相关信息，邮件通知标题正文显示触发者信息；
