### ISSUE TITLE
有重定向的接口cookie无法返回到页面（貌似没有jmeter中cookie管理的功能）

### ISSUE THREAD

**Issue by lanlan2019** [metersphere/metersphere#10776]
使用场景：接口a的参数中包含密钥以及重定向的地址。该接口使用jmeter以及postman工具调用都是可以正常跨过登陆页面。但是使用metersphere【接口自动化】中的功能调用该接口，同样的内容，返回的结果没有跨过登录页面。metersphere【跟随重定向】【共享cookie】功能均开启。以下为截图：
jmeter：
<img width="1133" alt="企业微信截图_4f8e97f2-a4df-4f0c-a2f3-b838fde71228" src="https://user-images.githubusercontent.com/46410533/154805868-724b9bd4-2cb4-4416-a6dc-4da60cbd0be2.png">
![image](https://user-images.githubusercontent.com/46410533/154805869-f2dad2ff-13c1-41d5-8455-5dfedb28cf7c.png)
metersphere:
<img width="882" alt="wecom-temp-a3a510144fca81b2b8f5d75e172d756c" src="https://user-images.githubusercontent.com/46410533/154805882-94affac1-88b4-4056-a46a-fd5bd685ccb8.png">
希望可以得到官方的帮助！！

**Comment by zyyfit** [comment]
您好，您可以看一下这个请求头中是否带上了cookie，带的cookie信息是否完整，如果共享cookie提取的cookie不完整，您可以手动提取一下cookie，添加到后续接口的请求头中

**Comment by lanlan2019** [comment]
您好，我看了一下不可以呢。重定向后的请求头里面的cookie是空的。
![Uploading image.png…]()
如果您说手动提取cookie。我这都是一个接口触发的我怎么操作呢？是一个接口中包含重定向，jmeter工具里面自动的将cookie-set到了管理器，所以重定向会成功。但是metersphere平台应该怎么排查，怎么去做提取呢。

**Comment by zyyfit** [comment]
您可以把这个场景导出来给我们看看吗？我们排查一下问题
然后手动提取就是您在登录接口里用提取参数把cookie提取出来，手动添加到下一个接口或者场景变量里试试

**Comment by lanlan2019** [comment]
您好，我们自己封装jar包实现了。

**Comment by zyyfit** [comment]
> 您好，我们自己封装jar包实现了。

好的，感谢支持
