### ISSUE TITLE
[BUG]不同模块的测试用例ID相同时，不能保存

### ISSUE THREAD

**Issue by xingchun-chen** [metersphere/metersphere#10783]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.17.2

**Bug 描述**

不同模块的测试用例ID相同时，不能保存，建议测试用例ID只判断当前模块唯一
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

建议测试用例ID只判断当前模块唯一，不同模块使用相同ID时，可正常保存

**截图**

<img width="619" alt="image" src="https://user-images.githubusercontent.com/55787491/154880594-b1062912-13f5-43c5-8e5f-24c12bb7e5ac.png">

**Comment by zyyfit** [comment]
您好，我们的测试用例ID目前是根据项目进行唯一判断的，根据模块的话，如果用例移动到其他模块，会出现同一个模块里有重复ID的情况
