### ISSUE TITLE
[FEATURE] 删除缺陷没有二次提醒，直接就删除了；缺陷希望提供回收站功能。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10780]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG] 删除缺陷没有二次提醒，直接就删除了；缺陷希望提供回收站功能。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。
