### ISSUE TITLE
[BUG]postman 导入时，会把默认设置的${url}导入到链接里

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#10789]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**
postman 导入时，会把默认设置的${url}导入到链接里
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/45531073/154883111-e28d724d-f4b4-4a1a-a438-c31fe471c410.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的，没有去掉url里的变量
