### ISSUE TITLE
[BUG] 接口测试，提取的参数，在后置脚本中获取不到。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#10797]
1.17.3

1. 提取参数
![企业微信截图_16451742054544](https://user-images.githubusercontent.com/44999044/154891891-adf498fe-d86a-4d95-9bd8-e04b7ebda5d2.png)

2. 提取成功
![企业微信截图_16451742346831](https://user-images.githubusercontent.com/44999044/154891846-b3c4bf7f-6100-47e1-93ab-952b464ebcbb.png)

3. 输出打印（打印失败）
![企业微信截图_16451744197103](https://user-images.githubusercontent.com/44999044/154891932-84a0ed06-8eda-4b27-908b-e1cc397f9e7f.png)

![企业微信截图_16451742267150](https://user-images.githubusercontent.com/44999044/154891920-21925f90-308e-4cbd-a320-b6fc3c377649.png)

**Comment by zyyfit** [comment]
您好，这个提取的参数，在jmeter里要使用${} 来获取，因为我们是用jmeter执行的，所以也要这样获取
![图片](https://user-images.githubusercontent.com/73461316/154896521-54159a91-6ebe-4586-845c-458f39c4c4d5.png)

**Comment by LimonFHM** [comment]
> 您好，这个提取的参数，在jmeter里要使用${} 来获取，因为我们是用jmeter执行的，所以也要这样获取 ![图片](https://user-images.githubusercontent.com/73461316/154896521-54159a91-6ebe-4586-845c-458f39c4c4d5.png)

您好，我都是试过的，不然我不会提这个问题。

![image](https://user-images.githubusercontent.com/44999044/154897111-06085654-d949-4af6-b714-6bad349f66f7.png)

**Comment by LimonFHM** [comment]
![image](https://user-images.githubusercontent.com/44999044/154898078-354ba82b-5ac5-4e35-a6ec-db7c06c49557.png)

**Comment by zlv2s** [comment]
> 1.17.3
> 
> 1. 提取参数
>    ![企业微信截图_16451742054544](https://user-images.githubusercontent.com/44999044/154891891-adf498fe-d86a-4d95-9bd8-e04b7ebda5d2.png)
> 2. 提取成功
>    ![企业微信截图_16451742346831](https://user-images.githubusercontent.com/44999044/154891846-b3c4bf7f-6100-47e1-93ab-952b464ebcbb.png)
> 3. 输出打印（打印失败）
>    ![企业微信截图_16451744197103](https://user-images.githubusercontent.com/44999044/154891932-84a0ed06-8eda-4b27-908b-e1cc397f9e7f.png)
> 
> ![企业微信截图_16451742267150](https://user-images.githubusercontent.com/44999044/154891920-21925f90-308e-4cbd-a320-b6fc3c377649.png)

你好，这个weixinIds是一个列表吗？vars.get()好像只能获取字符串，vars.getObject()可以吗

**Comment by LimonFHM** [comment]
> 你好，这个weixinIds是一个列表吗？vars.get()好像只能获取字符串，vars.getObject()可以吗


![image](https://user-images.githubusercontent.com/44999044/155058050-db8fc5bb-b10f-4eef-8b7d-77e01b4e42c4.png)
![image](https://user-images.githubusercontent.com/44999044/155058105-63a79900-1091-436e-8537-772c79a935c5.png)


不可以，获取的是null。

**Comment by zyyfit** [comment]
> ![image](https://user-images.githubusercontent.com/44999044/154898078-354ba82b-5ac5-4e35-a6ec-db7c06c49557.png)

你这个是提取了多条，要全部打印的话要用 ${xxx_ALL}，要打印某一条的话要用${xxx_1}，你可以仔细看一下我的脚本，我是写的 ${name_ALL}

**Comment by LimonFHM** [comment]
> > ![image](https://user-images.githubusercontent.com/44999044/154898078-354ba82b-5ac5-4e35-a6ec-db7c06c49557.png)
> 
> 你这个是提取了多条，要全部打印的话要用 ${xxx_ALL}，要打印某一条的话要用${xxx_1}，你可以仔细看一下我的脚本，我是写的 ${name_ALL}

好的，谢谢
