### ISSUE TITLE
[BUG]我的代办 接口定义下的接口 所属项目没数据

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#10791]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**
我的代办 接口定义下的接口 所属项目没数据

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/45531073/154883260-9698486d-7408-47ca-9ebc-89bc93d012be.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.17.3没有复现这个问题，您是哪个版本呀

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by liushuneng** [comment]
1.17.3 版本就有这个

**Comment by liushuneng** [comment]
![image](https://user-images.githubusercontent.com/45531073/154898559-d2f27de7-a7ef-4588-b4c8-cc5bd4950607.png)

**Comment by liushuneng** [comment]
![image](https://user-images.githubusercontent.com/45531073/154898643-06028037-7f59-4bd0-91ca-6c899be1fd87.png)
