### ISSUE TITLE
【消息提醒】邮件发送的报告，直接展示概览，链接跳转至详情报告

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1080]
**请描述您的需求或者改进建议.**
1.6.1版本通过jenkins触发的测试，测试结束后会发邮件。但是邮件的内容只有一个简单的链接。

希望能在邮件内容中能增加测试的大致结果概览，有详细报告链接

**Comment by ed-NCC-1701-B** [comment]
邮件内容包含：测试结果、成功失败情况、执行时间、触发情况等；
