### ISSUE TITLE
[BUG]脑图导入xmind时，显示数据不正确

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#10809]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.3

**Bug 描述**

简要描述您碰到的问题
1.导入本地的xmind文件，一样层级的case，有的被标记成用例，有的被标记成模块
2.在页面上想把case的标记由模块变成用例，无法更改
**Bug 重现步骤**

1.  打开测试跟踪
2. 导入用例
3. 选择思维导图
4. 

**期待的正确结果**

正确情况下应该是什么样的？
1.导入本地的xmind文件，一样层级的case，显示数据一致
2.导入的脑图在页面上可以修改数据
**截图**
![image](https://user-images.githubusercontent.com/45531073/154907572-7b40ab5d-5f2a-4a74-9d1b-202c024320cf.png)

![image](https://user-images.githubusercontent.com/45531073/154907537-15d5f37a-6ccc-4f92-accd-995de370e48a.png)

如果有截图，请附上截图.
[Uploading 新建文件夹.zip…]()

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~

**Comment by youliyuan-fit2cloud** [comment]
1.导入本地的xmind文件，一样层级的case，有的被标记成用例，有的被标记成模块
----是不是没有安装导入模板编写xmind文件？
2.在页面上想把case的标记由模块变成用例，无法更改
----已经是模块了，不能直接改成用例
