### ISSUE TITLE
[BUG].用例评审 切换评审名称，右侧的模块树信息没有刷新。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10800]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用例评审 切换评审名称，右侧的模块树信息没有刷新。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/154896745-3590b04a-9013-412c-b69c-ec6d542566c4.png)
![image](https://user-images.githubusercontent.com/78218624/154897053-2a67835e-6f22-45f8-b68a-b27fc6b1bafa.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
