### ISSUE TITLE
接口强制大小写转换[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#1083]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2

**Bug 描述**
简要描述您碰到的问题
在接口定义是，如果接口有大写字母，会自动转换为小写

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/30932762/103754105-e089eb80-5046-11eb-8ce3-59add5adef3e.png)

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，我们会尽快排期修改

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 已修改
