### ISSUE TITLE
[BUG]场景添加条件控制器，条件控制器中的步骤未执行，场景测试报告中的却显示为error

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10830]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
1.  
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/30038088/154963428-47942106-c0fc-4781-9a84-895eada38a6c.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题

**Comment by zyyfit** [comment]
1.19.0增加了未执行状态
