### ISSUE TITLE
[BUG]场景的条件控制器下只有断言脚本时，报告中不展示不执行

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10844]
**MeterSphere 版本**

1.10.11-lts

**Bug 描述**

场景的条件控制器下只有断言脚本时，报告中不展示不执行
既然条件控制器下可以单独添加断言，就应该展示
条件控制器下放断言有客户实际应用场景：
条件前面一般都放事务，事务里面都放循环，循环一个接口，超时后这个接口，或在规定时间内这个接口成功响应啦的值，拿到后面做条件判断，条件判断里面就放断言
<img width="671" alt="b785d7ba832af64a85f3a0cf3487210" src="https://user-images.githubusercontent.com/88763608/155074279-c5c2f2ad-5bd2-43fb-b7a1-330f674ea62f.png">
![image](https://user-images.githubusercontent.com/88763608/155074306-2e664488-c48f-41a1-afd3-960ddaa816a4.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
我们看了一下，jmeter里也是这种结果，一般情况下我们和jmeter保持一致，所以暂时不修改这个地方
