### ISSUE TITLE
[BUG]性能测试阶梯加压，测试详情中用户数存在小数

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#10841]
**MeterSphere 版本**

1.17.3

**Bug 描述**

简要描述您碰到的问题

<img width="918" alt="5cf48efe25304b03712140f5cc0a5d2" src="https://user-images.githubusercontent.com/88763608/155072646-25bde597-e9f1-4a3e-901f-649985614b79.png">

正确情况下应该是什么样的？
用户数一定为整数

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
这个是计算了平均值，是正常的
