### ISSUE TITLE
[BUG]复制功能用例后标签是隐藏的

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10859]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.创建一条功能用例添加标签
2.复制创建的用例
3.发现弹出测复制界面标签栏是空的
4.点击保存后，发现功能用例列表复制产生的用例标签又不是空的

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.0已修复
