### ISSUE TITLE
[QUESTION] 拉取dev分支代码启动后提示要配置redis

### ISSUE THREAD

**Issue by ikenneth** [metersphere/metersphere#10858]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/7484551/155103053-68c88a09-999f-4c8c-b3f6-1d798cc62185.png)

项目里面有用到redis吗？我看启动的demo没有用到redis，怎么配置呢？

**Comment by liuruibin** [comment]
dev分支属于开发中的分支包括还未发布的代码，你可以先用本地配置的方式启动。v1.18发布之后会提供redis
```
spring.session.store-type=redis
spring.redis.host=
spring.redis.port=
spring.redis.database=0
spring.redis.password=
```

**Comment by ikenneth** [comment]
好的 可以了 ths
