### ISSUE TITLE
[FEATURE]缺陷管理-“平台状态”和“状态”两个字段重复，平台字段无法删除，且不支持修改

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10857]
**MeterSphere 版本**
V1.17.3
您所使用的 MeterSphere 版本是？
V1.17.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.缺陷模版里没有“平台状态”字段，“平台状态” 字段为模版默认值
![image](https://user-images.githubusercontent.com/30038088/155098073-714b20fa-59a3-4b10-8088-783e79f24b6b.png)
2.
![image](https://user-images.githubusercontent.com/30038088/155099162-2d986784-d25e-418f-8d41-1f18a6fc9870.png)
3. 编辑缺陷，无法修改 “平台状态”
![image](https://user-images.githubusercontent.com/30038088/155099544-45a05f13-e888-49c8-a1c0-b0e23bf3de9b.png)

4. 修改 第三方缺陷 平台 “状态”，点击会同步 “平台状态” 
**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by luty2018** [comment]
已排期
