### ISSUE TITLE
[v1.6]项目管理页面建议放到二级菜单

### ISSUE THREAD

**Issue by miller-shan** [metersphere/metersphere#1086]
**问题/需求描述**
项目管理页面建议放到二级菜单，跟接口测试放在一起，而不是系统设置页面，调转到系统设置页面之后来回切换页面操作不方便。

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，因为测试跟踪、性能测试都需要用到项目相关配置，所以把这个单独放到了系统设置页面当中
