### ISSUE TITLE
[BUG]接口测试参数变量的优先级不是内部变量>场景变量>环境变量。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10860]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口测试参数变量的优先级不是内部变量>场景变量>环境变量。
2. 设置项目环境》》添加环境变量：如：testBL
2. 在接口场景里添加场景变量，变量名和环境变量名一样。如testBL
3. 在自动化场景接口a里设置变量，变量名相同。testBL
3. 在场景中a后面的接口里使用此变量，变量值为环境变量的值。
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/155107310-90250c6a-1867-4f2d-9fd7-183dacb40090.png)
![image](https://user-images.githubusercontent.com/78218624/155107389-d8c97e64-7bb7-44b5-b70f-e678a8bd32a0.png)
![image](https://user-images.githubusercontent.com/78218624/155107467-a80570bd-50f3-4e53-8d2f-bc909c30fa87.png)
![image](https://user-images.githubusercontent.com/78218624/155107590-ba6a2605-5c77-4c9d-9140-51ed2eba6e90.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前的逻辑是，如果是场景A引用了场景B，场景A和场景B里都设置了场景变量token，同时场景里的接口提取了或者是脚本设置了变量token，环境里也设置了变量token，这时引用顺序是：
场景B里优先级，场景B的token > 环境token > 场景A的token > 场景B的接口/脚本的token > 场景A的接口/脚本的token
场景A里优先级，环境token > 场景A的token > 场景A的接口/脚本的token

**Comment by zyyfit** [comment]
1.18.0已修复
