### ISSUE TITLE
[FEATURE]建议接口测试报告直观显示断言结果。

### ISSUE THREAD

**Issue by ddxflqm** [metersphere/metersphere#10879]
**请描述您的需求或者改进建议.**
现状：
进入测试报告，存在失败接口，需要找到对应的失败接口后，再点击断言才能看到具体的失败内容；

**请描述你建议的实现方案**
建议：将断言结果直接展示出来，比如Excel格式展示所有断言的预期结果和实际结果，在测试报告最外层就能直观的看到失败内容；

**Comment by Hyyfit** [comment]
已规划，待排期
