### ISSUE TITLE
[FEATURE]性能测试资源文件不支持dcm格式

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#10878]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.3
**Bug 描述**
性能测试资源文件不支持dcm格式
简要描述您碰到的问题

**Bug 重现步骤**

1.  新建性能测试任务
2. 上传资源文件，选择dcm格式（医疗行业的影像文件常用.dcm格式）
3. 点击保存并运行，报错
![dd294ef26b9721a3b96ac23d7023ced](https://user-images.githubusercontent.com/5198427/155247396-aa35ac38-890e-4b88-a9c0-f5b80a7b18e2.png)

**期待的正确结果**

正确情况下应该是什么样的？
性能测试资源文件支持dcm格式
**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，附件支持的文件格式类型会开放支持多做类型

**Comment by xieqione** [comment]
目前还是不支持dcm格式呢
