### ISSUE TITLE
[FEATURE]功能用例与需求的关联关系，自动同步回需求管理平台

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#10886]
**请描述您的需求或者改进建议.**
当前在MS的功能用例中关联其他需求管理平台的需求（如tfs、jira等），仅在ms中保存了该关联信息，无法通过需求向下追溯至相关的功能用例，不便于进行管理与统计。

**请描述你建议的实现方案**
1、关联关系建立时，向对应平台发送通知消息，将关联信息同步至需求管理平台。
2、在MS中增加  需求>>功能用例  的关系视图，能够方便的筛选或查询出某个需求相关的用例。

**Comment by luty2018** [comment]
有规划 会先做tfs的
