### ISSUE TITLE
[FEATURE]在编辑用例模板时，无法删除系统字段用例等级，且无法进行字段内容的编辑，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#10880]
**MeterSphere 版本**

v1.17.3

**Bug 描述**

在编辑用例模板时，无法删除系统字段用例等级，且无法进行字段内容的编辑，建议优化
（系统字段支持可编辑，或者支持新增同名自定义字段，且能在编辑用例模板时移除系统字段）

**截图**
![image](https://user-images.githubusercontent.com/92150453/155252633-8fad74aa-db35-4748-b108-e33f671f22b1.png)

**Comment by luty2018** [comment]
暂不支持
