### ISSUE TITLE
[BUG]个人信息接口-越权访问

### ISSUE THREAD

**Issue by ramontest** [metersphere/metersphere#1089]
**MeterSphere 版本**
版本: v1.6.1-3cb27580

**Bug 描述**
个人信息接口越权访问，非管理员账号通过接口越权访问管理员账号信息。

接口信息：
接口1：
GET 
/user/info/admin  HTTP/1.1
Host: 192.168.0.200:8081

操作步骤：
访问接口
原始：
![image](https://user-images.githubusercontent.com/38151722/103759411-a58bb600-504e-11eb-944e-8fd8c9953dc8.png)
 
![image](https://user-images.githubusercontent.com/38151722/103759477-c05e2a80-504e-11eb-94f8-99b5b7fc235c.png)

 
![image](https://user-images.githubusercontent.com/38151722/103759543-dcfa6280-504e-11eb-9307-93c328312f2a.png)

 
测试：使用普通账号cookie,访问管理员账号个人信息接口，cookie改为：MS_SESSION_ID=68216139-c520-4211-af3d-fb12a5e038a8
 
![image](https://user-images.githubusercontent.com/38151722/103759743-25b21b80-504f-11eb-9229-efc0c2b04313.png)

补充说明：

修复建议：
1、此接口涉及到系统中的管理员账号的信息，建议对此接口中传入的cookie信息进行校验，非管理员账号cookie不能请求此接口。

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，我们会尽快排期修改
