### ISSUE TITLE
[FEATURE]版本管理功能，建议参照Git打TAG方式，通过测试计划关联关系，自动为用例新建版本标签。

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#10890]
**请描述您的需求或者改进建议.**
当前版本管理功能开启后，需要对单个用例点进去编辑页面后，手动添加一个新版本。这种方式1是操作麻烦，2是手工操作容易出错。

**请描述你建议的实现方案**
建议参照git版本管理的理念，通过标记方式自动打tag。
提供一个思路，测试计划与版本号建立强依赖关系，在版本发布后，自动为关联至测试计划下的所有用例打版本标签。

**Comment by Hyyfit** [comment]
已规划，待排期
