### ISSUE TITLE
[BUG]带参数的post请求，参数不能使用上一个接口的提取参数

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#109]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.2
**Bug 描述**
简要描述您碰到的问题
带参数的post请求，参数不能使用上一个接口的提取参数

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应该可以使用

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/86995774-8b2a6a00-c1dc-11ea-80d3-b4c075811a7c.png)

**Comment by AgAngle** [comment]
v1.0.3 版本已修复
