### ISSUE TITLE
如果开启了误报库功能，接口自动化转性能测试会带有误报断言，压测的时候导致大量错误[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#10919]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1。17.3

**Bug 描述**
如果开启了误报库功能，接口自动化转性能测试会带有误报断言，压测的时候导致大量错误
简要描述您碰到的问题

**Bug 重现步骤**

1.  添加误报库，code：404
2. 一个正常的接口自动化脚本转成性能测试后开始压测
3.压测结果显示全部错误，如下
![image](https://user-images.githubusercontent.com/30932762/155280412-ff01ea66-6465-4048-91d6-668586182f58.png)
![image](https://user-images.githubusercontent.com/30932762/155280436-41e0822e-b505-4b1d-95c7-d573343c07a4.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
