### ISSUE TITLE
[BUG]上传jmx到性能测试场景，执行报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#10926]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  上传jmx到性能测试场景
2. 执行时失败
3. 详见错误日志
4. 脚本见附件

**期待的正确结果**

正确情况下应该是什么样的？
执行成功
**截图**

如果有截图，请附上截图.
<img width="526" alt="111" src="https://user-images.githubusercontent.com/83771182/155281275-63bc3174-63ef-4508-9440-286660c1dba9.png">
<img width="768" alt="222" src="https://user-images.githubusercontent.com/83771182/155281844-f7aa4da9-61ee-475c-a5a1-7c6e92e1d7b4.png">

[sha.zip](https://github.com/metersphere/metersphere/files/8122728/sha.zip)

**Comment by zyyfit** [comment]
您好，没有复现这个问题
![图片](https://user-images.githubusercontent.com/73461316/155310001-1d5fff5d-2ab1-46de-8ffb-a5ef9809c81e.png)
![图片](https://user-images.githubusercontent.com/73461316/155310015-8f142267-760f-4c59-a61f-afcf0f3ed21d.png)
