### ISSUE TITLE
[BUG]接口测试>>接口定义>>API>>选择创建接口，然后保存。系统提示保存成功。但是左侧模块统计的接口数量没有更新，只能刷新页面，左侧模块上的统计数量才更新

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#10933]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG]接口测试>>接口定义>>API>>选择创建接口，然后保存。系统提示保存成功。但是左侧模块统计的接口数量没有更新，只能刷新页面，左侧模块上的统计数量才更新
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/155283365-ff64173c-565d-4c33-a01c-0985d4949dff.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.1已修复
