### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lanlan2019** [metersphere/metersphere#10959]
**请描述您的需求或者改进建议.**
你们好，目前公司内的系统环境都是多个，测试环境，仿真环境，开发环境等等，不同的环境对应的数据库不同。使用该平台配置测试计划时，选择好了场景后，只能修改场景下内容的执行环境，但是场景内涉及到的数据库相关的断言验证的环境改不了。希望得到官方的回复。

**请描述你建议的实现方案**

**Comment by lanlan2019** [comment]
以下是相关截图，在case层有多个环境可选，但是在测试计划层只能选择运行环境，
case层
<img width="1385" alt="wecom-temp-27a209e38df4bfbee3c45be28c6477ea" src="https://user-images.githubusercontent.com/46410533/155313174-4e612634-d1e0-467f-b8c8-d2438d8d9c4d.png">
测试计划
<img width="1063" alt="wecom-temp-6308d235a9c2a2e9ec69386288b7aad8" src="https://user-images.githubusercontent.com/46410533/155313181-80d28b9f-8786-4933-b50a-f1df6bc30b85.png">

**Comment by luty2018** [comment]
是的， 1.20 会先解决单数据源的切换问题
