### ISSUE TITLE
【权限相关】管理者看报告一个结果，需要到对应的组织、空间当中进行查看；没有看所有测试结果的地方

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1096]
**请描述您的需求或者改进建议.**
当前的权限管理状态下，要同时看所有工作空间的测试结果，必须按个切换工作空间，每次只能看一个工作空间内的测试报告。
希望能有个能列出所有测试报告的入口。

**Comment by ed-NCC-1701-B** [comment]
可能需要一个独立的报告中心；
