### ISSUE TITLE
[BUG]场景统计的请求数和步骤数不对

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#10966]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.17.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  请求数不对

![92821645627712_ pic](https://user-images.githubusercontent.com/30038088/155453235-2cb2c17a-775c-44ba-b3ca-2d14d92f8a46.jpg)

2. 步骤数不对
![image](https://user-images.githubusercontent.com/30038088/155453366-81827023-319e-4fa0-96a4-728ead999239.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by sunnyyxy** [comment]
1、请求数不对问题在最新版本未复现，建议升级到 v1.18版本尝试
2、步骤数统计的是场景下一级节点的数量-是正确的
