### ISSUE TITLE
[BUG]swagger带basePath会导致导入接口重复basePath

### ISSUE THREAD

**Issue by ikenneth** [metersphere/metersphere#10967]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

导入swagger的URL如图:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/7484551/155347771-59bf6bde-1a4a-4626-9a11-e673bf6e91c7.png">

swagger的json:
<img width="561" alt="image" src="https://user-images.githubusercontent.com/7484551/155348951-35f0a69f-adda-41ba-9098-24da85512198.png">

导入之后的效果:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/7484551/155348093-4a6d2819-0f78-4d68-8836-0451f89e6ded.png">

**Bug 重现步骤**

1.  

**期待的正确结果**
不要自动获取url 的 basePath ，导入的时候可以选择不带basePath，可以在环境哪里设置URL是否带basePath，现在导入自动带上basePath在接口定义里面会导致每次更新都要修改接口地址

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by sunnyyxy** [comment]
1、目前swagger导入含basePath-导入后会自动带上basePath，不支持导入不带basePath的相关设置
2、paths中如果不含有basePath路径-导入后是不会重复的
