### ISSUE TITLE
[BUG]metersphere性能测试自定义参数，添加的位置也不对，导致Java sampler取不到这些参数

### ISSUE THREAD

**Issue by daviadong** [metersphere/metersphere#10968]
**MeterSphere 版本**

1.17.3

**Bug 描述**

在ms的性能测试高级配置，自定义参数里 添加了几个参数，metersphere没有替换Java sampler 自定义参数，添加的位置也不对，导致Java sampler取不到这些参数

**Bug 重现步骤**

1.  在性能测试高级配置-自定义变量添加变量

**期待的正确结果**

可以检测下用户的自定义配置，如果用户已经自定义了，那么只要把这些自定义变量添加到已有的自定义集合里，这样可以保证不会有问题

**截图**
我在自定义参数里添加的参数
![121645629314_ pic_hd](https://user-images.githubusercontent.com/51897467/155350335-89201a76-a1e3-473e-bbc7-1d16d3ebbc2d.jpg)

这是Java sampler 自定义参数的位置
![51645624312_ pic](https://user-images.githubusercontent.com/51897467/155350513-9fbedea2-7dd3-445b-8c2d-6b010b854f74.jpg)

metersphere帮我添加的位置
![111645629215_ pic_hd](https://user-images.githubusercontent.com/51897467/155350611-69a75c9f-4be4-47b9-87a7-be944a5f0cff.jpg)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我们目前是默认放在用户自定义的变量组件里的，然后我测试了一下，是可以取到值的，不过要保证在性能测试里添加的变量名和脚本里的变量名是一样的
后期会优化性能测试这部分的使用体验
如果您那边不可以的话，您方便把您的性能测试脚本和性能测试执行文件发给我们看看吗？
