### ISSUE TITLE
[BUG]测试跟踪-功能用例，经常提示在临时节点无法建用例。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#10965]
**MeterSphere 版本**

1.16

**Bug 描述**

测试跟踪-功能用例，经常提示在临时节点无法建用例。

**Bug 重现步骤**

1.  建立两个节点，
2. 第一个设为模块，
3. 后面一个先设其他（模块，备注，前置条件），再改为用例，
4. 保存就报错。 你们试着这样复现一下。

![image](https://user-images.githubusercontent.com/10231088/155337306-a0493af7-2d0b-4f90-b591-e3d050ce7263.png)
![image](https://user-images.githubusercontent.com/10231088/155337367-38afe3dd-5743-4456-8bfd-6520973ecb96.png)

**期待的正确结果**

正常使用

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈，后续版本修复会修复该问题

**Comment by ltfit** [comment]
1.20 已修复
