### ISSUE TITLE
[BUG]数据库错误模式

### ISSUE THREAD

**Issue by ramontest** [metersphere/metersphere#1097]
**MeterSphere 版本**
版本: v1.6.1-3cb27580

**Bug 描述**
发现数据库错误模式，可能会查看、修改或删除数据库条目和表。

接口信息：
接口1：
POST 
/test/case/review/project  HTTP/1.1
Host: 192.168.0.200:8081

{
	"id": "c6f30ea0-3104-41f4-8225-2870b191dad2';"
} 

接口2：
GET 
/project/delete/310c2f81-04a8-41b7-94ff-d6397161ea57?DEBUG=ON HTTP/1.1
Host: 192.168.0.200:8081

操作步骤：
功能：【WEB端】-【测试跟踪】-【测试用例评审】
原始：
 
![image](https://user-images.githubusercontent.com/38151722/103764051-bc81d680-5055-11eb-9a90-ed3797083c13.png)

测试："id"”的值设置为“ProbePhishing”
 
![image](https://user-images.githubusercontent.com/38151722/103764071-c4da1180-5055-11eb-98dc-568e0ff41b4f.png)

补充说明：
 
![image](https://user-images.githubusercontent.com/38151722/103764092-cc99b600-5055-11eb-924b-ea05127c2fb8.png)
![image](https://user-images.githubusercontent.com/38151722/103764108-d4595a80-5055-11eb-94a0-c02b2f8f62fe.png)

 
修复建议：
1. 建议对后端的报错信息进行过滤控制，对一些敏感的底层信息不让其直接抛出在前端中展示或在接口中返回。

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，我们会尽快排期修改

**Comment by liuruibin** [comment]
将在新版中处理
