### ISSUE TITLE
[BUG]用户列表页面-发现可能的性能问题

### ISSUE THREAD

**Issue by ramontest** [metersphere/metersphere#1098]
**MeterSphere 版本**
版本: v1.6.1-3cb27580

**Bug 描述**
用户列表页面按用户数请求多次，当用户数较多时可能会存在性能问题。

接口信息：
接口1：
GET 
/user/special/user/role/11111 HTTP/1.1
Host: 192.168.0.200:8081

操作步骤：
访问接口
原始：
 
 
![image](https://user-images.githubusercontent.com/38151722/103764251-197d8c80-5056-11eb-8609-01ab3762f2e4.png)
![image](https://user-images.githubusercontent.com/38151722/103764276-24382180-5056-11eb-9711-52cf07f3998a.png)

测试：无 
补充说明

修复建议：
1、建议此接口进行重新设计，不要按用户数多次请求用户数据。

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，我们会尽快排期修改

**Comment by liuruibin** [comment]
用户角色信息是先出现用户列表之后再执行查询的，这样可以缓解一次查询带来的耗时问题。用户列表是分页获取的，多次各自查询角色信息也是合理的。
