### ISSUE TITLE
[BUG]测试计划关联功能用例直接点确定会报错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#10985]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.创建一个测试计划
2.进入测试计划，点击关联功能用例，不选择功能用例，直接点击确定
3.报错“SQL error happened, please check logs.”
4.建议在不选择用例时点击确定弹出“请选择测试用例”的提示

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by litao3214** [comment]
感谢反馈，后续版本修复该问题

**Comment by ltfit** [comment]
1.18.1 已修复
