### ISSUE TITLE
[BUG]测试计划关联功能用例，点执行时，执行次数不改变

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#10984]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.3
**Bug 描述**

简要描述您碰到的问题
测试计划关联功能用例，点执行时，执行次数不改变
**Bug 重现步骤**

1.  创建测试计划
2. 关联功能测试用例（该功能用例未关联任何测试）
3. 点执行进入测试计划界面
4. 修改功能用例执行结果

**期待的正确结果**

正确情况下应该是什么样的？
执行次数不改变
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/45531073/155469309-257384b4-3b34-44f8-ac98-32fad534db96.png)
![image](https://user-images.githubusercontent.com/45531073/155469357-ddc07d17-f80c-4d2d-828a-ac73e8d343ca.png)
![image](https://user-images.githubusercontent.com/45531073/155469391-10e386d6-e732-41e4-a81a-89731bba9cf0.png)
![image](https://user-images.githubusercontent.com/45531073/155469428-7557ba2c-87c0-4e53-9680-fc7b3890441a.png)
![image](https://user-images.githubusercontent.com/45531073/155469452-43f2e5fe-f0f6-4f6a-b412-9a8549b5a5f1.png)

**Comment by ltfit** [comment]
@liushuneng 您好 目前 执行功能用例是不会改变 测试计划次数的
