### ISSUE TITLE
[BUG]接口调试选择环境不生效

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#10991]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.3
**Bug 描述**

简要描述您碰到的问题
接口调试选择环境不生效
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![9adb8cd3c62296075b9cc7ebe9fbcb4](https://user-images.githubusercontent.com/45531073/155490511-7fd19290-6785-492c-9374-c4056e40f94b.png)

**Comment by fit2-zhao** [comment]
@liushuneng  您好，调试需要输入完整url 不会使用右侧环境。
