### ISSUE TITLE
【测试计划】实现各项目计划之间的继承（复制后编辑）与关联（自定义筛选生成新计划）

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1099]
**请描述您的需求或者改进建议.**

希望，
1，能对已经测试过的测试计划进行继承，生成新的测试计划。且可以对新的测试计划进行编辑。
2，增加规则选择供用户选，用于生成新计划，比如：所有p0优先级的用例，所有失败的用例等

**Comment by ed-NCC-1701-B** [comment]
对已存在测试计划可一键全量（或按用户指定过滤规则选定）复制，并进行编辑生成全新测试计划；
