### ISSUE TITLE
admin账号密码无法修改

### ISSUE THREAD

**Issue by SuperLandy** [metersphere/metersphere#11]
修改admin账号输入初始密码metersphere时，提示旧密码格式不正确，点击确定无响应

![image](https://user-images.githubusercontent.com/44797172/84720787-8d205500-afb1-11ea-96ca-61632f25eed3.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们的默认密码和密码策略冲突了，这个问题会在 v1.0.1 版本中修复

**Comment by wangzhen-fit2cloud** [comment]
v1.0.1 版本中已修复
