### ISSUE TITLE
[FEATURE]测试NG时应该可以上传图片

### ISSUE THREAD

**Issue by mengshuai85** [metersphere/metersphere#110]
**请描述您的需求或者改进建议.**

在测试CASE，测试NG的时候，应该可以上传图片进行佐证，
现在测试结果及 提交bug项中，都不能进行图片上传

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
您好，感谢您的反馈，后续会持续优化

**Comment by xulinde** [comment]
1.10版本已支持
