### ISSUE TITLE
【测试计划】能够自定义测试计划的通过标准，eg：100 case中，90%通过，视为本次计划通过

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1100]
**请描述您的需求或者改进建议.**
当前判断测试计划是否pass的规制是固定的，所有用例pass才算pass。实际上，case很多的时候，应该不需要case 100%pass 也能判断整体pass。
希望能增加判断测试计划是否pass的规则给用户填写和选择。

**Comment by ed-NCC-1701-B** [comment]
不仅是通过百分比，还可包括case级别判定条件，如p1 100%通过、p2 90%通过；
