### ISSUE TITLE
【接口定义】接口断言可以进行范围性的数值校验（返回上一值的某个正负区间值）

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1101]
**请描述您的需求或者改进建议.**

希望API测试中，断言能增加数值区间的判断。比如对参数 num 进行断言(num > 50 , num < 99)

**Comment by ed-NCC-1701-B** [comment]
两种数值区间表达模式：1最大值最小值区间；2中值+波动百分比；
