### ISSUE TITLE
[BUG]jenkins执行接口自动化后，meterSphere显示状态为success ，但jenkins获取到的状态是 失败  Bug 重现步骤

### ISSUE THREAD

**Issue by zsminiyijl** [metersphere/metersphere#11015]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.2

**Bug 描述**

1，jenkins执行接口自动化后，meterSphere显示状态为success ，但jenkins获取到的状态是 失败

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
<img width="910" alt="4f0512bd2e9871ac00313509fb2bb0f" src="https://user-images.githubusercontent.com/45551155/155644550-6d657324-7aac-4b35-91a6-c251f04ec856.png">
<img width="360" alt="84a241900e26306fbed528533a896c0" src="https://user-images.githubusercontent.com/45551155/155644584-04f0afec-0b0f-499b-8a7d-b4f99e9a96d3.png">

**Comment by zrfit** [comment]
最新版本未复现该问题，建议更新MeterSphere和jenkins插件到最新版本尝试

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
