### ISSUE TITLE
【FEATURE】支持设置jira自定义字段

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1102]
jira系统中，一般会有新定义的必填的字段，比如 优先级，紧急程度等，如果jira定义的必须字段不填写，就无法生成issue。
希望能给用户自定义字段

**Comment by xchnshi** [comment]
这个社区目前有计划支持吗？

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，目前有计划优化集成缺陷管理工具，包括JIRA/Tapd/禅道，请持续关注后续版本～

**Comment by wangzhen-fit2cloud** [comment]
你好，计划在 1.9 版本支持该功能。

**Comment by t880216t** [comment]
自己动手丰衣足食。https://testerhome.com/topics/29702

**Comment by xulinde** [comment]
1.10版本已支持该功能

**Comment by xchnshi** [comment]
@xulinde 楼上@t880216t同学的关联已有issue，非常合适，请问社区会支持吗？
https://testerhome.com/uploads/photo/2021/272e0013-9825-474c-9a70-0088302e441c.jpg!large

**Comment by xchnshi** [comment]
> @xulinde 楼上@t880216t同学的关联已有issue，非常合适，请问社区会支持吗？
> https://testerhome.com/uploads/photo/2021/272e0013-9825-474c-9a70-0088302e441c.jpg!large

另外，是否可以每个用户配置自己的token，这样新创建jira issue实际是测试人员的用户信息，还非统一的管理员创建
