### ISSUE TITLE
[BUG]调试接口自动化部分步骤不执行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11021]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1场景中有三个步骤，每个步骤单个能调试有响应结果
2点击调试场景，只有第三个步骤执行，前两个步骤未执行

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/155648021-85558e57-0db6-41cd-968b-73a1b7223414.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #10830

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，生成报告的步骤顺序和实际场景不一致导致的。下个小版本修复~
