### ISSUE TITLE
[QUESTION]  资源池选择疑惑

### ISSUE THREAD

**Issue by Betrayme** [metersphere/metersphere#11023]
**请描述您的问题.**
为什么
我通过jenkins插件选择资源池
![8 XP31)QNKJVQK`VJ%GQPB4](https://user-images.githubusercontent.com/41469910/155650426-42d6f9d0-4f94-4fd0-a2ab-7e6e9d21c4ec.png)，则在node-controller执行

而性能测试选择资源池
![X1LI`G8SANZ`}4_Q7)WFDT](https://user-images.githubusercontent.com/41469910/155650505-160f92cd-ca06-4554-897a-95cd96899674.png)，却要额外拉出一个jmeter镜像来执行

**Comment by liuruibin** [comment]
接口测试由于本身特性需要及时返回适合使用已经启动的jvm来快速执行，性能测试则不需要，并且性能测试并发数增大后会导致容器oom退出，如果还用已有的jvm执行的话不是很稳妥
