### ISSUE TITLE
[BUG]场景引用导入接口用例报错java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11022]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.场景1引用场景2，删除场景2，并从回收站删除
2.在场景1中删除引用的场景2这个步骤，然后引用导入接口用例点击保存报错

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="995" alt="image" src="https://user-images.githubusercontent.com/36387811/155650347-e31e3a03-6b79-43fc-9194-9dcdd41d9fab.png">

**Comment by zrfit** [comment]
最新版本上按上述步骤尝试多次未复现该问题，能否导出场景用例我们再试下
