### ISSUE TITLE
单接口编辑用例编辑可视化区域过小

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1103]
单接口编辑用例时，可视区域比较小，感觉很局促

**Comment by wangzhen-fit2cloud** [comment]
你好，弹出的用例编辑页面可以拖动调整大小
![image](https://user-images.githubusercontent.com/27671436/103766572-010f7100-505a-11eb-9d7a-df869e1bd493.png)
你可以试着调一下看在哪个位置合适，我们重新调整下默认的弹出高度

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 版本中增加了全屏按钮，可以全屏编辑单接口用例。
