### ISSUE TITLE
[BUG] 接口 /test/plan/report/db/{reportId} 返回的 passCount值不准确

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11039]
**MeterSphere 版本**

1.17.3

**Bug 描述**
1. 接口 /test/plan/report/db/{reportId} 
    通过数量 执行数量 和用例数量 (无用例数量时应该为0，不是null)

3. 接口 /test/plan/report/db/{reportId} 返回的 passCount值为0，不是真实的值

![image](https://user-images.githubusercontent.com/24548477/155684969-953a6647-34e4-4204-bee1-6bb5340a694d.png)

**Bug 重现步骤**

1.  
2. 
4. 
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
查询测试计划报告时使用这个数据结构作为载体往前端传输数据的。在这个过程中通过率和通过数量已经算出来了，前台暂时用不到这两个字段，这两个字段就作为冗余字段传过来了，不代表真实的通过数量。
