### ISSUE TITLE
[BUG] 接口定义模块中上传图片接口运行正常，场景运行中该接口运行时系统提示查询不到文件位置

### ISSUE THREAD

**Issue by zl007434** [metersphere/metersphere#11041]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.18.0-9c635160

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

前置条件： 图片上传接口上传单张图片
1. 接口定义模块调试单个接口，功能运行正常
2. 将接口引用入场景中，运行时其他接口运行正常，图片上传接口报错，
系统提示：查询不到图片位置

**期待的正确结果**

正确情况下应该是什么样的？
下图所示
**截图**
![image](https://user-images.githubusercontent.com/73602782/155690485-77bc6af8-95e4-465f-bbeb-17be2abe7a01.png)
![image](https://user-images.githubusercontent.com/73602782/155691044-d8af2147-06cc-479a-a3b6-641acf650a39.png)

如果有截图，请附上截图.

**Comment by zrfit** [comment]
最新版本未复现该问题，能否导出该接口和场景我们尝试复现
