### ISSUE TITLE
[BUG]升级到1.18.0碰到问题，回退到1.17.3，报SQL错误“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#11047]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

1.17.3

**Bug 描述**

升级到1.18.0碰到问题，回退到1.17.3，报SQL错误“SQL error happened, please check logs.”

**Bug 重现步骤**

1.  升级到1.18.0碰到问题
2. 回退到1.17.3
3. 进入测试跟踪，报错，如图

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/51286902/155845067-030fbec2-ade2-4d22-ae0b-61eb5c6335e3.png)

**Comment by ltfit** [comment]
感谢反馈 下个小版本会优化

**Comment by ltfit** [comment]
您好 升级后是遇到了什么问题呢

**Comment by ltfit** [comment]
升级之后不建议回退
