### ISSUE TITLE
[BUG]一键安装后，添加环境配置时接口返回后台不存在此请求

### ISSUE THREAD

**Issue by vanglis** [metersphere/metersphere#1104]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2
**Bug 描述**
一键安装后，添加环境配置时接口返回后台不存在此请求

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/3435616/103777783-5c4a5f00-506c-11eb-9349-f25a42ce1368.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们系统中没有类似这样的提示信息，请检查下是否有配置负载均衡或前端代理服务器，并检查下相应日志。
