### ISSUE TITLE
[FEATURE]Enhancement - 测试页面，建议提供折叠功能

### ISSUE THREAD

**Issue by Jarod-Guo** [metersphere/metersphere#11055]
在做接口测试中，测试页面有4部分内容:
 - 基础信息
 - 请求参数
 - 响应内容
 - 步骤
 建议提供针对以上各部分内容的折叠功能，以便用户可以:
1. 在填写参数时，折叠起其他内容，如“响应内容”，“步骤”，以节省页面空间；
2. 在填写步骤时，折叠起其他内容，如“请求参数”，“响应内容”，进而节省页面空间，用户专注填写步骤
3. 以此类推，节省空间，用户有更大页面空间查看检查“响应内容”

![image](https://user-images.githubusercontent.com/55393693/155939453-774f3772-34d9-438f-b9bd-4ed3619c3fbf.png)

**Comment by Hyyfit** [comment]
1.19版本已规划。
