### ISSUE TITLE
[BUG]接口自动化页面执行一个场景，完成后状态信息没有更新

### ISSUE THREAD

**Issue by Jetdachui** [metersphere/metersphere#11053]
**MeterSphere 版本**
v1.18.0-b2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 接口自动化页面执行一个场景 
2. 执行完成后状态没有更新
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![企业微信截图_16460221713885](https://user-images.githubusercontent.com/74963743/155923843-4b6c5ad7-c82e-4ad9-b008-5aa46b63296a.png)

**Comment by zrfit** [comment]
最新版本未复现该问题，能否导出场景我们去尝试复现
