### ISSUE TITLE
[FEATURE]测试计划里能否加上导出用例的功能

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#11064]
**请描述您的需求或者改进建议.**
因为需要将测试用例分类，在功能用例模块选择的话，比较多

因此希望 测试计划加上导出用例功能

**请描述你建议的实现方案**

**Comment by A616984934** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/44996472/156095586-a4f749f8-99a5-4de2-a436-132de0d8a86f.png">

**Comment by Hyyfit** [comment]
您好，我们的用例分类可以通过左侧模块管理实现，也可以通过版本管理来实现。
您的这个需求通过版本管理应该是可以实现的，版本管理是我们企业版的功能，可以在交流群里联系我们的商务体验。
