### ISSUE TITLE
[BUG] Azure Devops 提交缺陷 ，不支持上传图片

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11072]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建缺陷，上传图片
![image](https://user-images.githubusercontent.com/30038088/156112390-0515e12b-8c55-40d2-920a-65607101b5be.png)

3. 在Azure Devops 缺陷列表不显示图片
![image](https://user-images.githubusercontent.com/30038088/156112489-3e7e2aa1-fb23-42ba-9d84-79deab263d3a.png)

5. 
6. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
1.19.1 修复该问题  缺陷在附件中查看
