### ISSUE TITLE
[BUG] 接口用例新建无法保存

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#11073]
**MeterSphere 版本**

1.18

**Bug 描述**

接口用例新建无法保存

**Bug 重现步骤**

1.  新建接口用例，点击保存

**期待的正确结果**

保存成功

**截图**

![56e21775d2b95153167782d3596e3d8](https://user-images.githubusercontent.com/22763910/156113351-d82cca53-110e-4bcb-8bd3-79fe903db43d.png)

**Comment by zrfit** [comment]
最新版本未复现该问题，请提供更详细的复现步骤

**Comment by liuqiao1995** [comment]
使用开源版本的的分支保存一下

**Comment by liuqiao1995** [comment]
> 最新版本未复现该问题，请提供更详细的复现步骤

可以使用开源版本的分支复测一下
