### ISSUE TITLE
[BUG]可以在ms上修改缺陷的“平台状态”

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#11078]
**请描述您的需求或者改进建议.**
当前企业版支持缺陷的双向同步，可以拉取jira上缺陷的状态但是不能在ms上修改缺陷的状态再推送到jira上，流程这块不满足业务使用
![45929737faeb4f65b97b29b46ff3a2b](https://user-images.githubusercontent.com/66759501/156116705-3b0f4bb1-58c0-428f-8a45-fa9196558433.png)
想通过自定义字段来实现，但是在form data里找不到状态的编码或其他信息

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
@zyyfit 如果 不能修改提缺陷

**Comment by zyyfit** [comment]
已转需求

**Comment by zyyfit** [comment]
1.20.5版本增加了这个功能，请发版后验证
