### ISSUE TITLE
[BUG]选择脑图添加用例增加模块的时候，未选择模块类型，点击保存，toast提示不能在临时节点下增加用例；接着继续操作选择模块类型，点击保存，还是相同提示； 理论上来说我选择模块类型以后，就不算临时节点了

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#11080]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18.0
**Bug 描述**
选择脑图添加用例增加模块的时候，未选择模块类型，点击保存，toast提示不能在临时节点下增加用例；接着继续操作选择模块类型，点击保存，还是相同提示；
理论上来说我选择模块类型以后，就不算临时节点了
简要描述您碰到的问题

**Bug 重现步骤**

1.  在用例前面加上级主题
2. 没有选择模块类型直接点击保存
3. 报错后，选择模块类型，还是报错
<img width="632" alt="12345" src="https://user-images.githubusercontent.com/61281775/156122823-4fae0f68-aa8f-44c7-aa8c-b2ddf5915d58.png">

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈，此问题会在下个版本修复

**Comment by ltfit** [comment]
1.20 已修复
