### ISSUE TITLE
[FEATURE]能否增加HTTP、DUBBO接口的初始值配置

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#11083]
**请描述您的需求或者改进建议.**
能否增加一个功能，HTTP、DUBBO接口支持初始值配置，例如dubbo接口，在实际使用中，每次新增接口，都要修改Config Center、Register Center、Consumer & Service，如果有初始值的话，就只需要填写接口和参数，可以大幅度提升编写效率，降低测试同学的使用成本
![image](https://user-images.githubusercontent.com/42166114/156122622-e9dd3f33-d7f0-445e-a9b3-fb810ffa0dee.png)

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期
