### ISSUE TITLE
[FEATURE]功能用例回收站无法查看同个用例的多个版本

### ISSUE THREAD

**Issue by chenhaoyu0725** [metersphere/metersphere#11090]
**MeterSphere 版本**
1.18

您所使用的 MeterSphere 版本是？

**Bug 描述**

功能用例回收站无法查看同个用例的多个版本
简要描述您碰到的问题

**Bug 重现步骤**

1.  在功能用例页面，对同个功能用例新建多个版本
2. 将该功能用例全部版本都删除到回收站
3. 去回收站差看该功能用例

**期待的正确结果**

预期结果：点击切换版本，能看到该用例的多个版本

实际结果：回收站只能看到该用例一个版本，没法切换其他版本查看

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我看目前功能用例的回收站也是有切换版本功能的，并且也可以筛选版本，点击用例查看详情，您是怎么操作的呢？
![图片](https://user-images.githubusercontent.com/73461316/156506484-f4b75fa0-ea81-44fb-b51c-0cda57fe09bf.png)
