### ISSUE TITLE
[BUG]性能测试多场景保存后，顺序会变

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11095]
**MeterSphere 版本**

1.10.11-lts

**Bug 描述**

性能测试每次引用一个自动化场景，分两次引用，保存后执行，执行完再打开性能测试，就发现顺序变了，查看JTL，顺序也跟保存的时候顺序不一致

或者：性能点保存之后刷新一下，场景顺序也会变

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 后续版本会修复
