### ISSUE TITLE
[BUG]场景自动化报告失败场景计数不正确

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#11097]
**MeterSphere 版本**

1.18.0

**Bug 描述**
场景自动化生成报告执行，执行后无任何失败，未勾选失败继续，但报告中失败场景有计数

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确显示各类型数量

**截图**

![image](https://user-images.githubusercontent.com/40912823/156280384-3fd8200e-fcb1-4b16-9fa5-a2fda470fb3e.png)

**Comment by wszbc** [comment]
> 最新版本未复现该问题，是否能导出场景我们去尝试复现

分析了下应该是含有if场景的时候没有进的场景就判断为失败了，比如if a ，if b ，ifc，三个场景，现在判断进了b，那么ac没进这时报告判断了 ac为失败计数，报告内接口状态是未执行。

**Comment by zrfit** [comment]
未执行场景目前版本统计到失败中，后续版本我们会优化，把未执行作为单独的状态进行统计展示

**Comment by zrfit** [comment]
v1.19版本已增加未执行状态，未执行、失败、成功单独统计。
