### ISSUE TITLE
[BUG]配置数据库前后置SQL连接数据库失败

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11098]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  配置好环境中的数据库连接
2. 添加SQL接口使用配置好的数据库连接环境可以连接数据库
3. 在http协议的接口用例中添加前后置SQL使用相同的数据库环境执行时报错
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![截屏2022-03-01 16 28 13](https://user-images.githubusercontent.com/36387811/156281822-84d1372d-6f3b-4169-af06-28580cb25afc.png)

**Comment by zrfit** [comment]
未复现该问题，请检查数据库连接池是否已满，导致连接数据库报错。
