### ISSUE TITLE
[BUG]性能测试没有按照计划时间运行

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#1109]
1.6.2
1.   6个线程组都是：200用户并发，每一个都是运行120s

按道理总时间一起运行120s就完毕，但是运行了6min还在运行，停不下来的节奏

每个线程组里面大概5个http请求组件；
无奈之下只有停止运行；
![image](https://user-images.githubusercontent.com/43331464/103855801-61e88900-50ee-11eb-9a46-be25bdf47a52.png)

**Comment by 52testing** [comment]
难道是算的总和时间？6x120s？=12分钟？

**Comment by 52testing** [comment]
运行了1分钟的看，当前执行时长：6 分钟 18 秒

**Comment by 52testing** [comment]
而却计算的3000多个用户是咋来的？？
3577 VU
Max Users

**Comment by wangzhen-fit2cloud** [comment]
你好，如果是通过接口测试创建的性能测试，原有接口测试每个场景对应一个线程组，多个线程组间是串行执行的关系。
按照这个配置转成性能测试后，也会是串行的关系，前一个线程组的所有现成跑完之后，后续线程组再开始。
所以总的执行时间会是多个线程组配置的持续时间之和。
