### ISSUE TITLE
[BUG]删除模块和测试用例之后，再次上传相同名字和路径的用例，提示重复

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#11107]
**MeterSphere 版本**

1.17

**Bug 描述**

删除模块和测试用例之后，再次上传相同名字和路径的用例，提示重复 无法上传

**Bug 重现步骤**

1.  上传测试用例
2. 删除的用例
3. 再次上传

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="677" alt="image" src="https://user-images.githubusercontent.com/44996472/156308015-56b827f4-092c-4bff-84e1-40bfaf135e66.png">

**Comment by ltfit** [comment]
您好最新版本未复现该问题 建议升级最新的版本
