### ISSUE TITLE
[BUG]GET请求无法在URL中携带query参数

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#11106]
**MeterSphere 版本**
V1.18.0

**Bug 描述**

简要描述您碰到的问题

GET请求无法在URL中携带参数

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="230" alt="企业微信截图_16461901134073" src="https://user-images.githubusercontent.com/32027713/156291760-ac0cafe6-11b7-4e9e-99b6-cc42d665d4cf.png">

![image](https://user-images.githubusercontent.com/32027713/156291809-af00dac8-4904-4e15-bf9b-41490f337b79.png)

**Comment by zrfit** [comment]
用上述接口请求上传query参数，请求地址中包含qurey参数，未复现该问题
