### ISSUE TITLE
[FEATURE]测试报告邮件通知中，建议增加pdf附件，方便在手机端或者非公司内网中也可以查看执行结果

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#11109]
**请描述您的需求或者改进建议.**
测试报告邮件通知中，建议增加pdf附件，方便在手机端或者非公司内网中也可以查看执行结果。

**请描述你建议的实现方案**
测试报告邮件通知中，建议增加pdf附件

**Comment by luty2018** [comment]
已采纳 待排期处理
