### ISSUE TITLE
[BUG]测试计划报告中出现重复执行和统计的情况

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#11102]
**MeterSphere 版本**
1.17.3

执行测试计划，查看测试计划报告，有一些老版本创建的接口自动化用例在执行时步骤出现重复执行和统计

![image](https://user-images.githubusercontent.com/51286902/156284293-1a9aa059-a2d2-49ba-b48c-c279aab34339.png)

不应该出现重复执行和统计的情况，请重视历史数据兼容问题

**Comment by warmmilk** [comment]
单独调试用例时一切正常，提供截图中的用例，供参考
[Metersphere_Scenario.zip](https://github.com/metersphere/metersphere/files/8166284/Metersphere_Scenario.zip)

**Comment by ltkk753698** [comment]
您好  新版本没有复现此问题  升级到最新版本 尝试下
