### ISSUE TITLE
[BUG]切换环境执行用例时，数据源名称会默认新环境的第一个数据库，预期结果：应该是新环境保存的指定数据库

### ISSUE THREAD

**Issue by xuweiming926** [metersphere/metersphere#11105]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.3-d6a494c8
**Bug 描述**
切换环境执行用例时，数据源名称会默认新环境的第一个数据库，预期结果：应该是新环境保存的指定数据库
简要描述您碰到的问题

**Bug 重现步骤**
测试用例在demo环境里，你们复现看看
在线体验环境:
https://demo.metersphere.com/ 
账号：demo 密码：P@ssw0rd123..
1.  
2. 
3. 
4. 

**期待的正确结果**
切换环境执行应该也是执行该环境下之前用户保存的数据库源，而不是切换执行环境后就默认第一个数据库源了
正确情况下应该是什么样的？
![gif](https://user-images.githubusercontent.com/29728103/156290774-7a86ff75-1821-403e-90f2-f4db3626af67.gif)

**截图**
![928248e5d754d9c9e31f842dd43279c](https://user-images.githubusercontent.com/29728103/156290811-bc649b86-1600-4591-8caa-3d4c17d45bde.png)

如果有截图，请附上截图.

**Comment by zrfit** [comment]
目前产品设计如此，切换环境后，就会默认取对应环境配置的第一个数据库。

**Comment by Hyyfit** [comment]
已规划，待排期。
