### ISSUE TITLE
[FEATURE]缺陷管理这块，建议增加按照「创建人」或者「处理人」进行筛选

### ISSUE THREAD

**Issue by fyxgit** [metersphere/metersphere#11103]
**请描述您的需求或者改进建议.**

缺陷管理这块，建议增加按照「创建人」或者「处理人」进行筛选

**请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/25633990/156287472-43e6033a-bf3e-4da9-a9f9-475432b068bd.png)

**Comment by Hyyfit** [comment]
您好，我们新版本会优化高级搜索功能，支持自定义字段的搜索。
