### ISSUE TITLE
[FEATURE]测试报告邮件通知的正文中建议将 控制台 信息也显示出来，方便在第一时间看到最关心的信息

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#11110]
**请描述您的需求或者改进建议.**
测试报告邮件通知的正文中建议将 控制台 信息也显示出来，方便在第一时间看到最关心的信息（尤其是执行失败时）。

**请描述你建议的实现方案**
测试报告邮件通知的正文中建议将 控制台 信息也显示出来。多场景或者多接口测试计划中，可以将失败节点的控制台信息显示出来。

**Comment by Hyyfit** [comment]
已规划，待排期
