### ISSUE TITLE
[BUG]接口定义高级搜索创建人查询无效

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#11114]
**MeterSphere 版本**

1.18.0

**Bug 描述**

接口定义高级搜索创建人查询无效

**Bug 重现步骤**

1.  接口定义--高级搜索---创建人--选择张三 
2. 查询无效
3. 
4. 

**期待的正确结果**

正确查询张三创建的接口  

**截图**

![image](https://user-images.githubusercontent.com/19423100/156331199-b499e5ff-49b8-4c3f-b594-fc3e59df777a.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，接口定义 没有创建人字段了，改为责任人，高级搜索这块漏掉没同步修改，下个版本修复！

**Comment by ltfit** [comment]
新版本已修复
