### ISSUE TITLE
[BUG]帮助文档中 内置函数 中，函数名点击后无法正常跳转

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#11116]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？ v1.16.5

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  帮助文档中 内置函数 中，函数名点击后无法正常跳转
2. 
3. 
4. 

**期待的正确结果**
可以正常跳转，并解释该内置函数的使用说明。
或者在metersphere平台上增加类似jmeter的函数助手功能。

正确情况下应该是什么样的？

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/100331967/156339829-879f1a6c-81ce-418b-b58e-96de824ac740.png)

**Comment by luty2018** [comment]
这里只是参考的作用， 没有跳转的功能呢。
