### ISSUE TITLE
[FEATURE]接口场景自动化测试中的循环控制器，选择次数循环类型时，建议其中的 循环次数的数值 可以参数化配置

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#11111]
**请描述您的需求或者改进建议.**
接口场景自动化测试中的循环控制器，选择次数循环类型时，建议其中的 循环次数的数值 可以参数化配置（因为这个数量经常是动态的）。

**请描述你建议的实现方案**
接口场景自动化测试中的循环控制器，选择次数循环类型时，建议其中的 循环次数的数值 可以参数化配置。

**Comment by Hyyfit** [comment]
已规划，待排期。
