### ISSUE TITLE
关于场景断言和步骤断言优先级的建议

### ISSUE THREAD

**Issue by MaxLyl** [metersphere/metersphere#11112]
**请描述您的需求或者改进建议.**
版本：V1.16.4，
模块：接口自动化，设置了场景断言和步骤断言，步骤断言通过，场景断言不通过此时接口判误为失败；

**请描述你建议的实现方案**
[建议，将步骤断言的优先级提高，作为接口判误的依据

**Comment by Hyyfit** [comment]
您好，我们新版本会优化场景自动化的编辑部分。
