### ISSUE TITLE
[BUG]使用jira缺陷模板，获取字段不全

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#11127]
**MeterSphere 版本**
1.18.0
**Bug 描述**

简要描述您碰到的问题
使用jira缺陷模板，选择问题类型后，创建缺陷，提示某些字段不能为空，但实际这个字段未在界面上出现
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

显示对应需填写字段

**截图**
![image](https://user-images.githubusercontent.com/40912823/156485262-8c2f295a-4cac-4ba5-bea7-45689f1c58b0.png)

**Comment by zyyfit** [comment]
您好，请问您这个字段在jira里是个什么类型的字段呢？能否把jira里的字段信息给我们看一下？

**Comment by wszbc** [comment]
> 您好，请问您这个字段在jira里是个什么类型的字段呢？能否把jira里的字段信息给我们看一下？
![image](https://user-images.githubusercontent.com/40912823/156692778-e77176de-a975-430e-8cb7-98719be86d84.png)
![image](https://user-images.githubusercontent.com/40912823/156693166-ebea4da7-238b-4ada-bd66-657befc18132.png)
填入的值是一个jira里的story

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by AgAngle** [comment]
> > 您好，请问您这个字段在jira里是个什么类型的字段呢？能否把jira里的字段信息给我们看一下？
> > ![image](https://user-images.githubusercontent.com/40912823/156692778-e77176de-a975-430e-8cb7-98719be86d84.png)
> > ![image](https://user-images.githubusercontent.com/40912823/156693166-ebea4da7-238b-4ada-bd66-657befc18132.png)
> > 填入的值是一个jira里的story

你好，请问你这个自定义字段是什么类型的，我这里不太好复现你的场景
![image](https://user-images.githubusercontent.com/41557596/173544473-a12fdac4-beba-4306-a91e-ad16d9893428.png)
