### ISSUE TITLE
[FEATURE]断言规则优化建议

### ISSUE THREAD

**Issue by ZhouHuTao** [metersphere/metersphere#11122]
**请描述您的需求或者改进建议.**
断言规则建议能够直接判断比对某个变量值，而不是固定在判断响应内容，因为有时是请求接口后，要取数据库表的字段值来判断执行结果是否成功。目前似乎是只能够通过脚本来断言，有点不方便。

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
设计如此
