### ISSUE TITLE
[BUG]旧版接口测试Query参数获取不到变量值

### ISSUE THREAD

**Issue by LEE-lucky** [metersphere/metersphere#1112]
**MeterSphere 版本**
v1.6.2-e012d438

**Bug 描述**
简要描述您碰到的问题
旧版接口测试Query参数获取不到变量值

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/56376764/103860523-b8f25c00-50f6-11eb-802c-a26355d6519c.png)
![image](https://user-images.githubusercontent.com/56376764/103860714-18e90280-50f7-11eb-917a-51f5045da985.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，建议使用改版后的接口测试功能，在 1.7 版本中会增加旧版向新版的数据迁移功能，旧版本的页面将逐渐不再维护并逐步弃用
