### ISSUE TITLE
[BUG]接口测试-首页，覆盖率和未覆盖接口显示有误

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#11132]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.3

**Bug 描述**

接口测试首页，接口用例数量统计，显示覆盖率为98.7%，有3个接口未覆盖，但点数字3进入未覆盖接口列表时无数据。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![50d989c0a65fcaa4c26c62d0cdc8166](https://user-images.githubusercontent.com/22739229/156489886-2afbcd21-75a4-4e7a-b62e-63e155505a1a.jpg)
![91414f4404723757929eb8b5a17ee51](https://user-images.githubusercontent.com/22739229/156489896-3d19f929-5b3a-4d5c-81de-cd2345993a99.jpg)

**Comment by zyyfit** [comment]
您好，我看接口覆盖率 98.4% 没有错呀，您是觉得哪里有问题呢？
点击跳转的问题后续版本修复

**Comment by GITMrzk** [comment]
> 

因为其实所有的都覆盖了，应该是100%才对

**Comment by yuanchenhuan** [comment]
![image](https://user-images.githubusercontent.com/22749362/161374052-c87fdd8e-fbb7-4c27-844f-2ffb054a99bc.png)

**Comment by yuanchenhuan** [comment]
@zrfit

**Comment by youliyuan-fit2cloud** [comment]
fixed on v1.19.2
