### ISSUE TITLE
[BUG]xpath提取参数不需要解析<![CDATA[]]>

### ISSUE THREAD

**Issue by LEE-lucky** [metersphere/metersphere#1113]
**MeterSphere 版本**
v1.6.2-e012d438

**Bug 描述**

xpath提取用<![CDATA[]]>包裹的数据数据多了[""]，1.6.1之前的版本提取时没有这几个符号

响应结果格式：
<response>
 <resultCode>
  <![CDATA[0]]>
 </resultCode>
 <resultDesc>
  <![CDATA[]]>
 </resultDesc>
 <result>
  <patId>
   <![CDATA[3385]]>
  </patId>
 </result>
</response>

**期待的正确结果**
提取结果没有[""]，或“”
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/56376764/103861779-f1933500-50f8-11eb-819d-85a88c378563.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，未复现该问题

**Comment by LEE-lucky** [comment]
> **MeterSphere 版本**
> v1.6.2-e012d438
> 
> **Bug 描述**
> 
> xpath提取用包裹的数据数据多了[""]，1.6.1之前的版本提取时没有这几个符号
> 
> 响应结果格式：
> 
> **期待的正确结果**
> 提取结果没有[""]，或“”
> **截图**
> 如果有截图，请附上截图.
> ![image](https://user-images.githubusercontent.com/56376764/103861779-f1933500-50f8-11eb-819d-85a88c378563.png)



> 你好，未复现该问题



> 你好，未复现该问题
接口响应数据格式
![image](https://user-images.githubusercontent.com/56376764/103865742-9ca6ed00-50ff-11eb-9c6b-8f1d5df8da8c.png)
