### ISSUE TITLE
[BUG]接口场景用例批量执行，当场景用例中存在复制引入的场景时，会不执行

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#11136]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.3

**Bug 描述**

场景用例中通过复制引入其他场景（例如登录场景）时，手工单个执行该用例可以通过；但批量执行时，该复制场景会始终显示为【未执行】状态。

**Bug 重现步骤**

1.  场景用例中，通过复制方式引入一个场景，再串联其他api
2. 通过批量执行方式，生成聚合报告，执行该场景用例
3. 查看报告，报告中，引用场景会显示结果为【未执行】
4. 

**期待的正确结果**

执行被引用的场景

**截图**

如果有截图，请附上截图.
<img width="851" alt="dcb5085b479b419196ab7be06c7f31e" src="https://user-images.githubusercontent.com/22739229/156491364-85af9c23-66bb-41a0-87a2-1f3f5866c1d9.png">

<img width="388" alt="c7aa0bc4f00b2c2013b0ca0106c1faa" src="https://user-images.githubusercontent.com/22739229/156509996-c8b32895-6c4e-4f1c-8044-3d4aa3c833f1.png">

**Comment by zrfit** [comment]
在最新版本未复现该问题，建议升级到最新版本尝试。

**Comment by GITMrzk** [comment]
@zrfit 看一下https://demo.metersphere.com/#/api/automation/report/view/740544ff-599b-4056-a241-e0931397e2d1

**Comment by zrfit** [comment]
最新版本也未复现该问题。
