### ISSUE TITLE
[FEATURE]接口测试聚合报告，场景数量统计逻辑有误，会将场景中复制的场景也统计进来

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#11133]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.17.3

**Bug 描述**

批量执行接口场景用例，生成聚合报告，实际引用了15个场景用例，但这15个用例中存在通过复制方式引入的其他场景用例（登录场景），因此聚合报告中显示的场景数为31。

**Bug 重现步骤**

1.  场景用例中通过复制方式引入一个其他场景
2. 批量执行，生成聚合报告
3. 场景数量统计时，会将引入的场景也计算次数
4. 

**期待的正确结果**

正确情况下应该是什么样的？
引入的场景不应当被统计到本次报告中。

**截图**

如果有截图，请附上截图.

<img width="738" alt="952e524a50e07ea1963976ec216e51f" src="https://user-images.githubusercontent.com/22739229/156490769-182627c7-6edb-4065-ac2f-5fdfba5b66e7.png">

**Comment by zyyfit** [comment]
您好，我们目前就是这样设计的，场景统计的时候，当前场景算1个，当前场景里引用或者复制一个场景会+1，如果引用或者复制的场景里包含复制或者引用的子场景，场景数量会再+1，举个例子

当前场景A，引用了场景B，场景B里有复制导入的场景C，这样执行场景A的时候，场景数量是3

**Comment by GITMrzk** [comment]
> 

但这样对于本次执行批次的通过率计算会有很大影响，比如我就执行了10个场景，9个过了1个挂了，通过率应该是90%。但如果把引用的场景都算上，这个值就完全不一样了

**Comment by luty2018** [comment]
设计如此
