### ISSUE TITLE
[FEATURE]用例中前后置SQL的运行环境为预设值，无法与场景用例运行环境匹配，建议解耦

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#11137]
**请描述您的需求或者改进建议.**
当前前置、后置SQL配置时，需要在用例中预先设置好运行环境和数据源名称，导致对运行环境切换的支持性很差。
比如我在案例中配置了前后置sql链接dev环境数据库，在dev环境中该用例可以顺利执行；一旦切换至test环境测试，该前后置sql无法自动切换为test环境数据库，会导致案例失败。

**请描述你建议的实现方案**
应当将sql运行环境从前后置步骤中抽离出，改为在运行环境中配置或直接自动匹配，以便数据库链接能够随着整体执行环境切换。

**Comment by luty2018** [comment]
确实存在这个问题，主要是会存在多数据源的情况，可能不太好切换， 1.20会保证单数据源能正确切换
