### ISSUE TITLE
[BUG] 旧版 post请求以拼接字符串的方式会自动 uriencode

### ISSUE THREAD

**Issue by Bbbixia** [metersphere/metersphere#1114]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本 1.6.2
旧版接口测试
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
需要做能够获取到变量

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/50947686/103876625-d6cbbb00-510e-11eb-8f33-85b50da628fe.png)
![image](https://user-images.githubusercontent.com/50947686/103876701-f4992000-510e-11eb-92d1-b4ec87a69d93.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，旧版本的接口测试我们将逐渐不再维护，建议升级并迁移至新版。
