### ISSUE TITLE
[BUG]metersphere对接禅道提交带有图片的缺陷同步至禅道后图片打不开

### ISSUE THREAD

**Issue by wholegale39** [metersphere/metersphere#11147]
**MeterSphere 版本**
Metersphere：v1.18.0-82ba1b94

**Bug 描述**
metersphere配置对接禅道，提交普通的缺陷可以正常同步至禅道，且打开无任何异常，但是在metersphere中提交带有图片的缺陷，同步至禅道，禅道打开该缺陷后，图片挂掉了

**期待的正确结果**
metersphere提交带有图片的缺陷同步至禅道后能正常查看；

**截图**
![972f05e2e55c820af8070e40c49dd30](https://user-images.githubusercontent.com/17040470/156521838-2b055bff-f43a-478d-81f3-125c0ae1d54e.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现，你这个上传的图片是什么格式？

**Comment by wholegale39** [comment]
就是简单的微信截图，直接ctrl+v粘贴到metersphere提交缺陷的输入框中，提交成功后在metersphere可以预览到图片，但是禅道就是挂掉的

**Comment by youliyuan-fit2cloud** [comment]
了解了，zentao 版本具体是？我们再排查一下

**Comment by wholegale39** [comment]
禅道版本为专业版9.0.3

**Comment by shiziyuan9527** [comment]
> 禅道版本为专业版9.0.3

v1.18不可以，以前的版本可以吗，另外是不是切换过请求方式呢

**Comment by wholegale39** [comment]
1.18版本之前还没对接过禅道，请求方式一直都是PATH_INFO，这样吧，明天我部署一个开源版禅道再对接试试

**Comment by wholegale39** [comment]
metersphere对接开源版本禅道16.4是可以正常推送带有图片的缺陷过去，且展示正常
![image](https://user-images.githubusercontent.com/17040470/156956195-6cd688d8-dbea-4e0d-a3ca-a59c517da7a9.png)

**Comment by wholegale39** [comment]
下图为metersphere v18.0对接专业版本禅道9.0.3，推送带有图片的缺陷过去，无法正常展示
![image](https://user-images.githubusercontent.com/17040470/156957339-92828994-33f3-4235-bf75-b9614e8795a4.png)

**Comment by youliyuan-fit2cloud** [comment]
非常感谢您的验证反馈，我们会尽快修复企业版问题~

**Comment by ltfit** [comment]
您好 升级到新版本 在尝试下

**Comment by wholegale39** [comment]
已升级1.19.0版本，试了推送带有图片的缺陷至禅道专业版9.0.3版本，还是不显示图片

![image](https://user-images.githubusercontent.com/17040470/160046939-c86ddbdf-aa57-4c10-9fa0-9486bc2757f9.png)

**Comment by wholegale39** [comment]
已升级1.19.1版本，试了推送带有图片的缺陷至禅道专业版9.0.3版本，还是不显示图片
![image](https://user-images.githubusercontent.com/17040470/161913364-9de87242-aaa8-45dc-9358-715b96b4b246.png)

**Comment by wholegale39** [comment]
已升级1.19.2版本，推送带有图片的缺陷至禅道专业版9.0.3版本，还还还还是不显示图片
![image](https://user-images.githubusercontent.com/17040470/162654690-85d153fc-a2f4-4fb0-b3da-d3d4e1ae1ee6.png)

![image](https://user-images.githubusercontent.com/17040470/162654624-2989f42b-5ae1-41af-9610-1d69da5a97c2.png)

**Comment by wholegale39** [comment]
已升级1.19.3版本，推送带有图片的缺陷至禅道专业版9.0.3版本，还还还还还是不显示图片
![image](https://user-images.githubusercontent.com/17040470/163529358-34985e45-b10e-4e1e-bcdb-429c5db5a6d0.png)

目前发现是因为路径中缺少了/pro
无法正常访问图片的路径：http://192.168.x.xxx:82/file-read-69492.png
可以正常访问图片的路径：http://192.168.x.xxx:82/pro/file-read-69492.png

**Comment by luty2018** [comment]
> 已升级1.19.3版本，推送带有图片的缺陷至禅道专业版9.0.3版本，还还还还还是不显示图片 ![image](https://user-images.githubusercontent.com/17040470/163529358-34985e45-b10e-4e1e-bcdb-429c5db5a6d0.png)
> 
> 目前发现是因为路径中缺少了/pro 无法正常访问图片的路径：http://192.168.x.xxx:82/file-read-69492.png 可以正常访问图片的路径：http://192.168.x.xxx:82/pro/file-read-69492.png

麻烦加下我的企业微信，因为没有你这个环境，需要你协助测试一下。
