### ISSUE TITLE
[BUG]在线升级请求路径错误

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11145]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/156517988-8fc3fdbe-e62c-421a-a85c-2b63b18ac0c6.png)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/156521032-780c9d7c-babc-4179-99b3-4062fdb32b06.png)

网络不通导致的...
