### ISSUE TITLE
[BUG]接口自动化引用接口用例，用例中的步骤可以编辑，实际不生效

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#11156]
**MeterSphere 版本**

1.18

**Bug 描述**

接口自动化引用接口用例，用例中的步骤可以编辑，实际不生效

**Bug 重现步骤**

1.  接口自动化引用接口用例，接口用例带断言步骤
2. 场景中将引用的接口用例步骤关闭
3. 执行后，关闭的步骤仍然执行

**期待的正确结果**

引用的接口用例不可编辑。

**截图**
<img width="982" alt="image" src="https://user-images.githubusercontent.com/89773363/156530061-d40783c3-e02b-4d95-8c9f-19c3d19731eb.png">

**Comment by zyyfit** [comment]
1.18.1已修复
