### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1116]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.62
**Bug 描述**
简要描述您碰到的问题
弹框右侧有很大块空白，建议输入框可以往右拉长点

![image](https://user-images.githubusercontent.com/69206282/103883515-45614680-5118-11eb-9977-1775a5cacf3f.png)

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 已修改
