### ISSUE TITLE
[BUG] 关联jira后，一些信息拿不全，如关联需求，报告人等只有部分

### ISSUE THREAD

**Issue by z-ab** [metersphere/metersphere#11176]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.3

**Bug 描述**

关联jira的需求的时候，jira的任务只显示部分，同时选择报告人的时候，报告人也只是jira中字母靠前的人，后边的不显示

**Bug 重现步骤**

1.  jira中报告人或者需求添加很多
2. 后边的就看不到啦
3. 这个应该是分页的问题，有想法解决这个问题吗
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by z-ab** [comment]
正常我报告人有100个，显示100个，或者可以查询到报告人，现在看到的，只有20个，其他的没法选择
<img width="997" alt="image" src="https://user-images.githubusercontent.com/1701441/156707649-966f7d2e-d0d6-4bba-82f0-f2a1d56c4d91.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by qiangyonglong** [comment]
同样的问题 +1
