### ISSUE TITLE
[BUG]环境里配置全局前置脚本-单个请求步骤前执行-过滤请求类型选择‘HTTP’ ，执行http接口未生效

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11174]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.
![image](https://user-images.githubusercontent.com/30038088/156689932-91e0970d-7a59-4255-a4c5-534034d553bf.png)
2.
![image](https://user-images.githubusercontent.com/30038088/156689970-045ed4a5-40bb-4bd1-9288-562ad446f057.png)
3.不选 “过滤请求类型”
![image](https://user-images.githubusercontent.com/30038088/156690073-8f707287-294d-4f7a-9b76-027616391f3c.png)
4.
![image](https://user-images.githubusercontent.com/30038088/156690254-6ddfa124-8f5b-40af-ab70-3efd3b4bc99e.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
产品设计如此，如果环境配置-全局前置脚本配置-过滤请求类型选择了http，则执行http接口的时候，全局脚本不会生效。此处的过滤请求类型的含义是：对该请求类型不生效。
