### ISSUE TITLE
[BUG]环境里设置全局前置脚本-所有请求步骤前执行，设置脚本，调试单接口 未生效。

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11177]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.
![image](https://user-images.githubusercontent.com/30038088/156696393-3f8e3ef1-c299-45d0-911a-d0519617a22b.png)
2.
![image](https://user-images.githubusercontent.com/30038088/156696467-c2375f88-7720-4419-b5e1-dcd62fc9bfe5.png)

3. 未打印出 全局前置脚本-所有请求步骤前执行 里加的日志 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by honglianglv0917** [comment]
上次看1.18.2 刚才升级了 发现没解决 看又改到了19.0版本

**Comment by honglianglv0917** [comment]
这个问题 还往后面放呀。就等着这个功能 升级呢。接口定义没有这个功能 有啥用？？？

**Comment by luty2018** [comment]
> 这个问题 还往后面放呀。就等着这个功能 升级呢。真正用接口测试的,这个功能 是P0级需求,希望可以尽快修复,团队还是想用新功能,一直不敢升级。多谢

【所有请求步骤前执行】这一功能，是为场景用例设计的。

在场景用例中，每一个接口都看作一个步骤。在场景执行中开启“所有请求步骤前执行”的前后置脚本，就会在该场景的所有步骤的前/后执行一次脚本。

接口用例中并没有“步骤”这一概念，也并不需要这一概念。 针对接口用例，“单个请求步骤”的脚本可以覆盖你目前的需求。

**Comment by honglianglv0917** [comment]
> > 这个问题 还往后面放呀。就等着这个功能 升级呢。真正用接口测试的,这个功能 是P0级需求,希望可以尽快修复,团队还是想用新功能,一直不敢升级。多谢
> 
> 【所有请求步骤前执行】这一功能，是为场景用例设计的。
> 
> 在场景用例中，每一个接口都看作一个步骤。在场景执行中开启“所有请求步骤前执行”的前后置脚本，就会在该场景的所有步骤的前/后执行一次脚本。
> 
> 接口用例中并没有“步骤”这一概念，也并不需要这一概念。 针对接口用例，“单个请求步骤”的脚本可以覆盖你目前的需求。

嗯,本身你说的没问题,说说具体场景
我们定义,接口定义里面的API,TESTCASE的作用是,先定义接口,然后写接口用例. 预期的效果是:接口定义和用例 可以直接执行,这就需要封装前置脚本比如token,签名之类的。
我理解你的意思是让我们新建一个项目环境,把这个前置脚本放到单个请求步骤区分其他项目环境,这样项目环境就会很多。
