### ISSUE TITLE
[FEATURE]进行接口和CASE调试的时候响应时间过长>3s

### ISSUE THREAD

**Issue by zengli136742681** [metersphere/metersphere#11175]
**请描述您的需求或者改进建议.**
在接口定义模块进行API和CASE执行的时候(非快捷调试)，获取响应结果在大概5秒左右
在ApiReportWebSocket这个类里，onOpen时创建了3s的timer task，这个3s的逻辑是否可以优化下
`    /**
     * 开启连接的操作
     */
    @OnOpen
    public void onOpen(@PathParam("reportId") String reportId, @PathParam("runMode") String runMode, Session session) {
        Timer timer = new Timer(true);
        ApiReportTask task = new ApiReportTask(session, reportId, runMode);
        timer.schedule(task, 0, 3 * 1000);
        refreshTasks.putIfAbsent(session, timer);
    }`

**Comment by youliyuan-fit2cloud** [comment]
最新版本v1.20.5-lts已优化该问题，请升级一下吧
