### ISSUE TITLE
[BUG]message from server: "Too many connections"

### ISSUE THREAD

**Issue by redgra0315** [metersphere/metersphere#11189]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
metersphere v1.17.3 版本
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  使用metersphere-offline-installer-v1.17.3 进行安装
2. 服务启动之后登陆8081 端口页面为空，查看后端服务，registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v1.17.3报错如下
3. 在容器里面登陆mysql 数据库，提示如下
4. 
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/48678307/156729183-3062bba6-aea3-4509-af7b-2adb3d838542.png)
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/48678307/156729324-0d9a79bb-aaf6-48bb-a100-376236943644.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/48678307/156729495-f3ac3dc6-fa1e-4cf5-9884-141239d8b7aa.png">

**Comment by redgra0315** [comment]
centos 7.8  操作系统

**Comment by redgra0315** [comment]
docker 20.10.12

**Comment by redgra0315** [comment]
Docker Compose version v2.2.2

**Comment by liuruibin** [comment]
编辑 `/opt/metersphere/conf/my.cnf` 把连接数增大试试看

**Comment by redgra0315** [comment]
默认是2000，我增加到6000 也有这个问题

**Comment by liuruibin** [comment]
升级到新版试试有没有改善
