### ISSUE TITLE
[BUG]在MS提交缺陷后，没有把自定义的字段同步到jira，且报告人读取的是MS中服务集成时配置的jira用户名

### ISSUE THREAD

**Issue by xingchun-chen** [metersphere/metersphere#11184]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18.0

**Bug 重现步骤**
1、在MS中jira模板新增jira字段：报告人、经办人、状态、优先级，Sprint
2、在MS提交缺陷后，没有把自定义的字段同步到jira，且报告人读取的是MS中服务集成时配置的jira用户名

![image](https://user-images.githubusercontent.com/55787491/156712148-36cc0f51-557e-4b92-944a-9b7f71e1216f.png)
<img width="919" alt="image" src="https://user-images.githubusercontent.com/55787491/156712257-8dd1aa62-5de0-4438-a05a-eb8b75188971.png">
![image](https://user-images.githubusercontent.com/55787491/156712868-3d8bf7aa-4df4-4e34-882a-e47729196cf6.png)

**期待的正确结果**

1、在MS提交缺陷后，把自定义的字段同步到jira,
2、点击“同步缺陷”后，将jira的报告人、经办人、状态、优先级，Sprint也同步到MS

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好 检查下配置是否正确呢
模板添加自定义字段，填写api字段名，api字段名同上的选项值
Jira提交缺陷接口： https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post

**Comment by xingchun-chen** [comment]
我配置了几个jira的api字段，提交缺陷都报错了，有没有jira常用字段的api字段配置参考一下

**Comment by ltfit** [comment]
https://blog.fit2cloud.com/?p=2683

**Comment by xingchun-chen** [comment]
设置了api字段，但增加缺陷仍报错，报错如下图
![image](https://user-images.githubusercontent.com/55787491/159866417-f37fcec3-47fe-4375-acb3-2a8e46443019.png)

**Comment by ltfit** [comment]
感谢反馈 后续版本修复
