### ISSUE TITLE
[BUG]对接禅道时，上传的图片在禅道显示为链接，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11180]
**MeterSphere 版本**

MS版本：v1.18.0
禅道版本：专业版 12.5
禅道请求方式：PATH_INFO

**Bug 描述**
在禅道请求方式默认为PATH_INFO时，对接禅道并提交BUG至禅道时，图片未能正确显示，请修改。
（后台更改禅道请求方式为GET，并对接成功后，图片显示正常）

**Comment by ltfit** [comment]
感谢反馈 后续版本会优化

**Comment by ltfit** [comment]
您好 升级到v1.18.1 在尝试下
