### ISSUE TITLE
[QUESTION]想使用外部Prometheus，但是配置后无法使用

### ISSUE THREAD

**Issue by HakureiAlice** [metersphere/metersphere#11185]
操作：
1.将系统参数设置中的Prometheus地址修改为同一台服务器上另外一个自己以前部署的Prometheus容器的地址（http://prometheus:9090），运行性能测试，可以正常查看监控详情
2.将地址修改：宿主机ip:映射端口号（http://172.30.10.1:8060）之后，无法查看监控详情
3.将地址改回http://prometheus:9090之后，停用ms-prometheus容器，无法查看监控详情

在安装时修改install.conf文件中Prometheus 配置也试过，但是没有效果
想请问下如何正确配置外部Prometheus

**Comment by liuruibin** [comment]
1. 修改外部Prometheus服务器的prometheus.yml
<img width="409" alt="image" src="https://user-images.githubusercontent.com/23045261/157806807-7f849001-ac12-4f68-aaad-db50f312a69f.png">
指向ms的地址
2. 修改ms系统里的Prometheus地址
<img width="598" alt="image" src="https://user-images.githubusercontent.com/23045261/157806898-3a2061f6-01d0-4c2f-92cb-c2837f3a0e01.png">
