### ISSUE TITLE
[BUG]文件上传接口调试，文件上传到服务器指定目录后，jmeter无法读取（jmeter读取目录与服务器存储文件目录不一致）

### ISSUE THREAD

**Issue by wangzhigg** [metersphere/metersphere#1118]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by ningfdx** [comment]
发生了同样的问题
![image](https://user-images.githubusercontent.com/17705801/103974409-b3efe400-51ac-11eb-818c-abef86b84b81.png)
