### ISSUE TITLE
[BUG] SMTP设置连接测试失败

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11198]
**MeterSphere 版本**

v1.18.0
SMTP服务器：Microsoft ESMTP

**Bug 描述**

SMTP支持匿名访问（提供用户名，但不需要密码），以下为命令行测试的验证结果，供参考：

1. 使用员工邮箱，只指定smtp-user （不指定smtp-password）
  echo "Mail Content" | mail -v -s "Mail Subject" -S smtp=smtp://<mail-server-ip>:25 -S smtp-user=abc@company.com receiver@company.com
测试结果：邮箱receiver@company.com 成功收到邮件

2. smtp-user为功能账号(不带后缀 @company.com)
  echo "Mail Content" | mail -v -s "Mail Subject" -S smtp=smtp://<mail-server-ip>:25 -S smtp-user=FunctionId  receiver@company.com
测试结果：邮箱receiver@company.com 成功收到邮件

3. 在提供smtp-user功能账号的同时，带上smtp-password参数（该功能账号为匿名账号，只有用户名，无密码）
  echo "Mail Content" | mail -v -s "Mail Subject" -S smtp=smtp://<mail-server-ip>:25 -S smtp-user=FunctionId  -S smtp-password=  receiver@company.com
测试结果：邮箱receiver@company.combu  没收到邮件

4. 在提供smtp-user的同时，带上smtp-password参数，随意指定密码
  echo "Mail Content" | mail -v -s "Mail Subject" -S smtp=smtp://<mail-server-ip>:25 -S smtp-user=FunctionId  -S smtp-password=abc123  receiver@company.com
测试结果：邮箱receiver@company.combu没收到邮件

以上组合，在MeterSphere的邮件配置中，测试连接均为失败，info.log提示"Authentication Unsuccessful"

**Bug 重现步骤**

1.  
4. 
5. 
6. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/24548477/156876647-e39cf959-a057-49fb-95e3-3fecd4b0aaeb.png)

![image](https://user-images.githubusercontent.com/24548477/156877158-5ef5c69d-d5f8-4f7d-88ee-3d8e4f57fc94.png)

**Comment by xyziven** [comment]
另外，建议提供debug选项，以便在测试连接时能打印更详细的信息

**Comment by xyziven** [comment]
不确定是否跟NTLM 有关
https://stackoverflow.com/questions/50913198/javax-mail-535-5-7-3-authentication-unsuccessful-due-to-javax-mail-upgrade

**Comment by Ycr123888** [comment]
Bug 验证步骤：
1、设置auth为FALSE/注释auth，后台报错AuthenticationFailedException
![image](https://user-images.githubusercontent.com/103925124/196844895-b3853312-234c-4b06-b8fe-ca00cd4a9ec0.png)
2、注释auth和setpassword,后台报错AuthenticationFailedException

3、auth正常开启，注释setpassword，后台报错AuthenticationFailedException
4、注释auth和用户名密码，还是报连接失败后台空指针无AuthenticationFailedException报错【70行空指针】（来源）
![1090c9a8be07a01a0785f01ced63ef2](https://user-images.githubusercontent.com/103925124/196847138-8544d241-14b3-4d48-97ba-0946022d079d.jpg)

**Comment by shenkaibo** [comment]
不确定是不是 和 javamail 的版本有关系，我们用的1.6.7，有其他系统用 1.4.1 是可以实现的，看 javamail 的更新日志 [javaee.github.io/javamail/docs/CHANGES.txt](https://javaee.github.io/javamail/docs/CHANGES.txt)  1.4.3 增加了 NTLM

**Comment by shenkaibo** [comment]
![image](https://user-images.githubusercontent.com/30038088/201260787-0a1be627-6e5b-4ecf-89a0-27e0458480cf.png)
已验证通过，需要 注释掉 props.put("mail.smtp.auth", "true") ，默认是 false ，然后 前端 页面如果不填 密码，后台 需设置为null,
不能设置 为 空字符串（“”），空字符串 依然会校验密码

**Comment by shenkaibo** [comment]
判断是否需要执行auth login操作验证用户名和密码的源码逻辑如下
 if ((useAuth || (user != null && passwd != null)) &&
		  (supportsExtension("AUTH") ||
		   supportsExtension("AUTH=LOGIN"))) {
		connected = authenticate(user, passwd);
如果我们不去设置mail.smtp.auth参数（那么它默认就是false），只要将用户名和密码设置为null或者非null，即可让java决定是否需要执行login操作；所以建议不要设置mail.smtp.auth参数，只使用用户名和密码来控制是否执行login操作；
注意 用户名和密码 必须设置 为null 才会判断是否执行login ,不能是 空字符串

**Comment by fit2cloud-yaochunrong** [comment]
2.10.0-lts版本代码如下，未将密码设置为null，还是空字符串，需要改下 @youliyuan-fit2cloud 
![image](https://github.com/metersphere/metersphere/assets/103925124/41718e4d-809c-4683-b8b4-d3a22aaf09e5)

**Comment by xeasonx** [comment]
Mantis有类似问题。
公司内部邮箱使用的自生成证书所致，系统无法验证证书有效性，所以SMTP使用SSL时连接测试失败，修改相关代码后可以正常收发邮件。
可否增加忽略SSL证书验证的选项？
