### ISSUE TITLE
[BUG] 接口测试执行无法正常结束

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11197]
**MeterSphere 版本**

v1.18.0

**Bug 描述**

 接口测试，无论是通过测试计划执行、调试执行、还是流水线外部触发，测试本身的执行（含场景）能执行，且能收到响应结果，但是任务无法正常结束：没收到结束的消息，日志里没没打印结束的信息。表现为任务“卡住”，无法结束。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

 测试任务应该正常结束

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
@fit2-zhao

**Comment by shenkaibo** [comment]
调试场景无法结束，实际已经执行完成（接口已经拿到响应信息），查看日志初步分析是因为 websocket 一直没收到 结束的 消息（ms-jemter-run-log没有打印出结束的日志），所以没有触发结束的动作 ，直到 websocket 连接 超时，强制断开。

**Comment by fit2-zhao** [comment]
已经修复 @shenkaibo

**Comment by ltfit** [comment]
1.19版本修复
