### ISSUE TITLE
[BUG]接口测试执行后，前端页面一直转圈

### ISSUE THREAD

**Issue by lede-zr** [metersphere/metersphere#1119]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5
**Bug 描述**
接口测试执行后，查询info日志，执行完了，跟正常的对比，少了一行worker ended，然后前端页面一直在转圈页面。
执行7次，然后过了一段时间，突然生产了一个测试报告，包含了之前的7次执行结果，然后又正常了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35915210/103969989-260efb80-51a2-11eb-8d12-6a2e8e7805dc.png)

![image](https://user-images.githubusercontent.com/35915210/103970001-2d360980-51a2-11eb-931d-57ab152c11a5.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，推荐升级到最新版本使用。
