### ISSUE TITLE
[BUG]接口请求参数后面被默认拼接&

### ISSUE THREAD

**Issue by black-cmd** [metersphere/metersphere#112]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.3
**Bug 描述**
post请求后,被默认拼接 & 符号

**Bug 重现步骤**

**期待的正确结果**
配置参数了拼接,未配置不拼接 &

**截图**
json?access_token=48e64e99ca244e8788c4cb524444446cbe2fe8&ewerw=绕弯儿翁r&绕弯儿无=rwerwer&

**Comment by wangzhen-fit2cloud** [comment]
已在新版本中修复
