### ISSUE TITLE
[BUG]使用mock服务，如果只设置了query参数，跑TEST会导致空指针异常

### ISSUE THREAD

**Issue by owen0204** [metersphere/metersphere#11200]
**MeterSphere 版本**

1.18.1

**Bug 描述**

使用mock服务，如果只设置了query参数，跑TEST会导致空指针异常

**Bug 重现步骤**

1. 只设置了query参数，没有body设置的时候，paramJson为空导致requestMockParams无法setBodyParams
2. 导致MockConfigService 383行为空
3. 导致MockConfigService 393行checkParamsCompliance函数空指针异常

**期待的正确结果**

应该能够返回正确设置的mock期望结果

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.19.0已修复
