### ISSUE TITLE
[BUG]脑图编写用例，模块没有打上标记进行保存，前端不会给出任何报错信息

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#11201]
**MeterSphere 版本**

v1.17.1

**Bug 描述**
使用脑图编写测试用例，如果模块没有打上标记，点击保存，前端没有任何报错信息，很难去排查用例保存不成功的原因
![image](https://user-images.githubusercontent.com/67257251/156913785-53386b9e-514a-4f0d-bdf9-0e6321213eb9.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/10475
1.18.0已修复
