### ISSUE TITLE
[BUG] 设置了Mock后 字段 为什么是null值？

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [metersphere/metersphere#11208]
**MeterSphere 版本**
1.18.1

**Bug 描述**
设置了Mock后 字段 为什么是null值？

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

mock随机值返回

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/43517569/156963953-9e99a086-09af-49aa-addc-240526a09130.png)
![image](https://user-images.githubusercontent.com/43517569/156963977-5777859c-79aa-4077-805e-a653e9a65066.png)

**Comment by zrfit** [comment]
mock响应体字段不支持jmeter内置函数，优化为去掉下拉选择内置函数操作-可输入值。
