### ISSUE TITLE
[BUG] v1.14.0 升级v1.18.1 后，ms-server 启动报数据库错误

### ISSUE THREAD

**Issue by Hooyh110** [metersphere/metersphere#11202]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是v1.14.0

**Bug 描述**

简要描述您碰到的问题
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-06 23:54:19,310 ERROR g.springframework.boot.SpringApplication: 819 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerStarter': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 2 !

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by liuruibin** [comment]
官网的常见问题里安装部署那里处理方式 https://metersphere.io/docs/faq/installation/

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/23045261/156975353-08906cfb-c52a-4174-8570-71a4a8f93657.png">
