### ISSUE TITLE
[BUG]【接口测试】添加json断言，断言正确时，抛空指针异常

### ISSUE THREAD

**Issue by wangzhigg** [metersphere/metersphere#1120]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请再执行下 msctl upgrade 命令升级验证

**Comment by wangzhigg** [comment]
已解决，ms体验很好~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 下午2:00
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"都是憨熊"<2437490586@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]【接口测试】添加json断言，断言正确时，抛空指针异常 (#1120)





 
你好，请再执行下 msctl upgrade 命令升级验证
