### ISSUE TITLE
[BUG]SQL中使用upadate语句无法执行成功，日志会报sql有语法错误

### ISSUE THREAD

**Issue by zengjin55** [metersphere/metersphere#1121]
**MeterSphere 版本**
v1.5-0abd7209

**Bug 描述**
SQL中使用upadate语句无法执行成功，日志会报sql有语法错误

**Bug 重现步骤**
1. 场景中 添加SQL请求
2. SQL语句中填写update语句，如：`UPDATE user SET status=0 WHERE status=1;`
3. 保存并执行场景

**期待的正确结果**
SQL执行成功，数据库数据正确修改，正确断言无报错

**截图**
![image](https://user-images.githubusercontent.com/33446797/103972022-0c23e780-51a7-11eb-924f-57f50c17da91.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改，请升级验证。
