### ISSUE TITLE
【接口测试】导入请求体格式是json的jmx格式的接口，导入后默认请求体格式是raw；自定义脚本修改成json格式后导入默认请求体格式是x-www-form-urlencoded

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#11218]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  导入请求体格式是json的jmx格式的接口
2. 自定义脚本修改成json格式后导入
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
导入后默认请求体格式是json
**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
请问第二步自定义脚本修改成json格式后导入是具体什么操作？是在接口编辑页面修改为json格式后导出再导入吗？

**Comment by zhangyafan188** [comment]
> 请问第二步自定义脚本修改成json格式后导入是具体什么操作？是在接口编辑页面修改为json格式后导出再导入吗？

是直接编辑脚本，把raw格式改成json格式
