### ISSUE TITLE
[FEATURE]测试跟踪----缺陷管理，查询增加处理人查询功能

### ISSUE THREAD

**Issue by zhongfuchao** [metersphere/metersphere#11212]
**请描述您的需求或者改进建议.**
目前提供了ID和名称查询，但是实际使用过程中，开发都很少用这个去查询，建议增加一个“处理人”的查询功能

**请描述你建议的实现方案**

**Comment by zhongfuchao** [comment]
![image](https://user-images.githubusercontent.com/45380139/156968418-9fdbc766-0ac6-41f9-a63c-5a97f90022bf.png)

**Comment by luty2018** [comment]
这里会增加高级搜索，预计1.20
