### ISSUE TITLE
[BUG]脑图编写用例 Firefox浏览器不会成功

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#11229]
**MeterSphere 版本**

v1.17.1

**Bug 描述**

使用Firefox浏览器 使用脑图编写用例，点击保存后，切换回列表 ，发现新增的用例消失

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好 建议用chrome浏览器
