### ISSUE TITLE
[BUG]接口测试-接口定义，请求体和响应体关闭json-schema再打开后会清空json的描述信息

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#11228]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.0
**Bug 描述**

简要描述您碰到的问题
请求体关闭json-shema后再打开会清空掉之前在json中填写的字段描述信息。
**Bug 重现步骤**

1.  编辑接口定义
2. json-schema开启状态下编辑请求体信息，填写字段的描述
3. 关闭json-schema
4. 开启json-schema，查看第二步骤填写的信息。描述信息被清空了
5. 

**期待的正确结果**

正确情况下应该是什么样的？
保留描述信息。由于无法限制点击json-schema的开关，经常出现填写好的描述信息在误点击了json-schema开关后被清除
**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，目前设计如此。
1、打开 json-schema 开关后，输入描述信息点击保存-描述信息实际已经保存成功。
2、填写描述信息后，关闭 json-schema 开关，返回展示json格式，只展示key-value，无描述信息，此时再打开开关，数据获取的是json格式的数据，所以此时不会显示描述字段内容，重新编辑此接口则会显示步骤1中的描述的字段内容。
3、在json格式和打开 json-schema 开关后均可添加字段并实现双向同步。所以如果经常使用描述信息字段的话，则不用频繁切换json-schema 开关，在json-schema 模式下可编辑查看描述信息也可以增加字段。如果关闭了json-schema 开关，再查看描述信息的话，重新进入接口编辑页面即可查看。

**Comment by zcyuefan** [comment]
如果关闭了json-schema 开关，再查看描述信息的话，重新进入接口编辑页面即可查看。--重新进入编辑页面，描述信息会丢失的。反正重新打开schema开关后描述信息怎么也找不回来了。你可以复现一下

**Comment by zrfit** [comment]
您好，json-schema 开启后-填写描述信息-点击保存按钮-描述信息保存成功。然后关闭接口编辑页面，再重新进入接口编辑页面-描述信息是存在的。如果接口编辑页面填写描述信息后未保存，描述字段填写切换json-schema 开关，描述信息时不会保存的。
