### ISSUE TITLE
[BUG]性能测试：脚本使用CSV分割多节点压测异常,每个节点目前都会从头开始重复取值CSV中的数据,通过数据库错误日志查看，确认同一值被重复多次调用

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#11235]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题

**Comment by zyyfit** [comment]
使用用户提供的数据复现了，后续版本修复
