### ISSUE TITLE
[BUG]性能测试当上传的jmx脚本上包含某些管理器时，生成报告报错

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#11248]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.1（我在https://demo.metersphere.com/环境测试有此问题）
v1.16.5（我本地部署的环境也有同样的问题）
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  本地jmeter运行.jmx执行成功，上传到ms上执行完生成报告报错
2. 经过测试，是.jmx脚本中的某些管理器会导致生成报告失败，详细见截图

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![e2f17a19dfac75377d4bcb0c31ccbc9](https://user-images.githubusercontent.com/5198427/157153264-98b71d0b-92ca-4317-8be8-7975dd8cfde7.png)
![48bad3a49862b1388cb9a89e18771ba](https://user-images.githubusercontent.com/5198427/157153284-b95f7d9c-7406-4602-a553-b12fdfac5dde.png)

当脚本中增加如下几个管理器就会导致生成报告报错
![1861458205e3716bb49f9ce7621a36e](https://user-images.githubusercontent.com/5198427/157153421-eff885b5-5a23-4575-802c-dcb875ebeef4.png)

**Comment by xieqione** [comment]
[](url)

**Comment by xieqione** [comment]
点错关闭了，重新打开

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您还记得demo环境能复现的测试是在哪个工作空间的哪个项目吗？我去看看
