### ISSUE TITLE
[BUG]版本更新后，性能测试报告-请求统计中执行的顺序显示乱了

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#11242]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/97216833/157015807-b0c32302-9f60-45b7-9cdf-dd3386e5c452.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
