### ISSUE TITLE
测试用例按思维导图导出有问题，操作步骤和预期结果没有显示[BUG]

### ISSUE THREAD

**Issue by 735670042** [metersphere/metersphere#11259]
**MeterSphere 版本**

1、当前demo环境版本

**Bug 描述**

1、编写测试用例
2、导出为思维导图
3、思维导图中操作步骤和预期结果没有显示

**期待的正确结果**

1、按规范正确显示用例内容

**截图**

<img width="746" alt="0652f1373c2d4c5143865685609dda7" src="https://user-images.githubusercontent.com/30249764/157161355-3e9b1288-58bc-4ae2-b4bb-2829b775ddc6.png">

<img width="746" alt="b49dc792b80f11d494db34d0df52f09" src="https://user-images.githubusercontent.com/30249764/157161436-cffbf3a3-a5e8-441e-aabe-88a1a376b8ec.png">

![image](https://user-images.githubusercontent.com/30249764/157161454-9960552f-14df-4c34-ab4a-3529dc83324c.png)

**Comment by ltfit** [comment]
您好 建议下载最新版本

**Comment by 735670042** [comment]
是最新版本，https://demo.metersphere.com/ 上的版本

**Comment by ltfit** [comment]
您好 步骤信息为文本描述 目前是不支持导出xmind的
