### ISSUE TITLE
[BUG]本地导入swagger接口响应体中的字段的描述没有导入

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11268]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  本地导入swagger接口
2. 查看响应内容，点击json 开启json-chema
4. 查看响应字段的描述没有导入
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/157187680-3f0779ac-601d-4913-9c02-97c1bbaedff7.png)

<img width="525" alt="image" src="https://user-images.githubusercontent.com/36387811/157187038-7ea660be-1e7b-4d71-b15b-1c0b0d827206.png">

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by zyyfit** [comment]
1.19.1已修复
