### ISSUE TITLE
[BUG]接口的QUERY参数的value中填写带有空格的值， 接口会报错

### ISSUE THREAD

**Issue by z-y-h** [metersphere/metersphere#11275]
**MeterSphere 版本**

v1.18.1-72533db2

**Bug 描述**

接口自动化和接口定义中，接口QUERY参数的value中填写带有空格的值，
接口会报错：Non HTTP response code: java.net.URISyntaxException

**Bug 重现步骤**

1.  在接口自动化和接口定义中，QUERY参数的value中填写带有空格的值
2. 调试或者运行
3. 接口未返回任何response，连状态码都没返回
4. 报错：Non HTTP response code: java.net.URISyntaxException

**期待的正确结果**

正常返回接口信息

**截图**
<img width="685" alt="image" src="https://user-images.githubusercontent.com/50519771/157285418-0140f4f8-c058-4297-8ef4-ebe72ce522f9.png">

<img width="966" alt="image" src="https://user-images.githubusercontent.com/50519771/157285715-3b1bfbbf-a9aa-42af-9b49-3c10ae38e2c0.png">

**Comment by zrfit** [comment]
您好，接口QUERY参数的value中填写带有空格的值，需要进行编码设置，请设置后查看请求是否正常。
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/99731894/157395730-7d4bf97a-9658-48d4-95e5-f6e3a3d5634c.png">

**Comment by z-y-h** [comment]
好的谢谢 ，设置编码后可以了
