### ISSUE TITLE
[BUG]场景里 json-shema 设置 array 参数读取csv ，读取到是 [] 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11270]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
v1.18
**Bug 重现步骤**

1.
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/30038088/157195898-d11696c6-3f9b-4160-a6e0-88e891336674.png">
2.
<img width="789" alt="image" src="https://user-images.githubusercontent.com/30038088/157195931-6372b2a4-257f-471c-9cec-55306e32e7b8.png">
3.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/30038088/157195958-67f3c639-63ca-4c03-b6f7-92c154b32841.png">

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/30038088/157196254-de0d0fe8-fa79-4bb1-bc91-b28ef27ebfbe.png">
还是正常 array 的情况下 不允许设置值 ？如果是这样的话，先设置成 string ,就不能再切换成 array 了

**Comment by zrfit** [comment]
1、选择了array类型-是不允许设置值的，要在array的节点下添加值。
2、如果先设置成string-再想设置成array，那么就把string对应的值清空 然后再选择array就行了。
