### ISSUE TITLE
【FEATURE】测试跟踪-缺陷管理模块建议加筛选功能

### ISSUE THREAD

**Issue by lixintester** [metersphere/metersphere#11276]
**请描述您的需求或者改进建议.**
测试跟踪-缺陷管理模块建议增加筛选条件，便于创建人和处理人对问题进行筛选
根据测试常用的项，如：按状态、处理人、严重程度、创建时间

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已规划，预计1.20上
