### ISSUE TITLE
[BUG] REST 参数里变量 带 ‘-’ 的话，识别不到

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11298]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/30038088/157408621-69caa77f-fc5f-45d2-bbf2-89b8a48b8d5c.png">
2.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/30038088/157408700-2b3b23a8-134e-400c-b1e3-e5cff10fe603.png">

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，变量不支持 ”-“ 正常写法 v_xx 或 遵循java 驼峰命名都可以。

**Comment by shenkaibo** [comment]
好的 这个是我们 写法不规范导致
