### ISSUE TITLE
[FEATURE]LADP登录时，获取域账户信息映射缺少判空处理

### ISSUE THREAD

**Issue by greedygod** [metersphere/metersphere#1129]
**请描述您的需求或者改进建议.**
LADP登录时，获取域账户信息映射缺少判空处理。
——ldap获取用户OU时，如果对应人员的邮箱在域账户中未填写，会导致因为mail取值

**请描述你建议的实现方案**
我司域控约有7000人员信息，部分人员入职时，仅填写了用户名，（邮箱和手机等为非必填）。
但metersphere集成ldap时，email name username这三项必须通过映射获取。如果取值为空则无法创建账号，影响使用
建议修改：
 - 方式1 ：读取LDAP映射关系时，除username之外的取值改为允许为空（或对空值处理赋予一个默认取值），以保障账号可成功创建，相关空值允许登录后通过用户信息修改补充。
 - 方式2： 修改LDAP映射取值实现，改为允许读取静态文本值或拼接解析（目前全部是作为key名称去OU查找)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续版本会优化这部分功能，请持续关注～
