### ISSUE TITLE
[BUG]执行Case时消息中心提示的是另外一个人的账号

### ISSUE THREAD

**Issue by hcccl** [metersphere/metersphere#11299]
**MeterSphere 版本**

版本:   v1.18.1-72533db2

**Bug 描述**

执行Case时消息中心提示的是另外一个人的账号，消息设置设置提醒的是创建人接收消息通知

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/23255732/157411622-9d4857b1-fd92-4a50-aa41-ae7137fd56f3.png)
![image](https://user-images.githubusercontent.com/23255732/157412130-b2d0e03f-659a-4df8-b3d6-82a11f9bb3de.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，浏览器只登录了一个账号吗？
![image](https://user-images.githubusercontent.com/54612864/157434185-b1216544-6830-4f52-9a14-f9ce0981f9a5.png)

系统通知中这个”执行人“和当前登录系统 执行接口case的账号不是一个是吗？
