### ISSUE TITLE
[FEATRUE]接口自动化场景失败用例ID无便捷查询方式

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#11307]
**MeterSphere 版本**

1.18.0

**Bug 描述**

接口自动化场景失败用例ID无便捷查询方式

**Bug 重现步骤**

1.  接口自动化--选择一场景执行
2. 失败的用例case不能便捷查询 
3. 
4. 

**期待的正确结果**
能看到失败case的id，应该和添加一样能看到caseid

**截图**

![image](https://user-images.githubusercontent.com/19423100/157568629-d41b840a-bfa7-4d1b-916b-109e7cb55946.png)

**Comment by luty2018** [comment]
已采纳 待排期处理
