### ISSUE TITLE
[BUG]请问为什么环境内规则为模块。但是对应模块下有部分接口取不到环境域名呢？

### ISSUE THREAD

**Issue by lanlan2019** [metersphere/metersphere#11301]
**MeterSphere 版本** 

您所使用的 MeterSphere 版本是？
v1.18.0-82ba1b94

**Bug 描述**

简要描述您碰到的问题

您好，请问为什么环境内规则为模块。但是对应模块下有部分接口取不到环境域名呢？
**Bug 重现步骤**

1.  请问为什么环境内规则为模块。但是对应模块下有部分接口取不到环境域名呢？
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1100" alt="wecom-temp-cf1eedc09a588e93b01745f0e6b5eb68" src="https://user-images.githubusercontent.com/46410533/157413142-ef221920-7bb3-4518-8c4e-d0ff7d79dd4a.png">

<img width="1424" alt="wecom-temp-c5908c174f0c12014c7ee6359bfc40dc" src="https://user-images.githubusercontent.com/46410533/157413119-f7cfaaaf-ae09-4cec-b84e-60032b22cc7f.png">

**Comment by zrfit** [comment]
您好，未复现该问题，能否把对应接口case导出我们尝试复现。
