### ISSUE TITLE
[FEATURE]接口自动化场景显示被删除的case

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#11308]
**MeterSphere 版本**
1.18.0

**Bug 描述**

接口自动化场景显示被删除的case

**Bug 重现步骤**

1.  接口自动化场景引用-接口case（注意是引用）
2. 接口定义当中去删除case
3. 对接口自动化场景不影响
4. 

**期待的正确结果**

引用的场景应该是不显示在接口自动化当中的，以及统计项

**截图**

![image](https://user-images.githubusercontent.com/19423100/157574910-0e600c37-0d23-41cf-ba6d-8b2d4dea2ffe.png)

见接口场景当中
![image](https://user-images.githubusercontent.com/19423100/157575049-8eef792a-1f82-4535-bb14-8c3d50e3183a.png)

**Comment by luty2018** [comment]
非常抱歉现在才回复。
我没太明白你的问题是什么， 烦请进一步描述，谢谢。
