### ISSUE TITLE
[BUG]接口自动化场景“一键收起”旁边的“禁用”按钮点击后，接口步骤执行报错

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#11302]
**MeterSphere 版本**
v1.18.1

您所使用的 MeterSphere 版本是？
v1.18.1

**Bug 描述**
接口自动化场景“一键收起”旁边的“禁用”按钮点击后，接口步骤执行报错

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
接口步骤需要能正常执行
正确情况下应该是什么样的？

**截图**
<img width="883" alt="WechatIMG4645" src="https://user-images.githubusercontent.com/18387151/157414442-d75bcf7e-0dc4-4ba2-b351-67b295c4de6b.png">
<img width="835" alt="WX20220309-174137@2x" src="https://user-images.githubusercontent.com/18387151/157415300-6a89ea64-f3d7-4885-bac9-8bfb84c7f611.png">
这个图中的测试报告是正常的，没有问题

![WechatIMG4648](https://user-images.githubusercontent.com/18387151/157414484-808af8f8-c905-4455-9f7a-80a0a9d41f57.jpeg)
![WechatIMG4649](https://user-images.githubusercontent.com/18387151/157414491-b5b5f54d-3e6a-4efe-9fa1-82d208edec3f.jpeg)
这个图中的测试报告显示，第一个接口步骤没有正常提取到参数
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
最新版更改了场景步骤的显示布局，没有这个启用禁用按钮了
