### ISSUE TITLE
[BUG]TCP请求，同样的参数在接口定义、快捷调试和接口自动化中的响应结果不一样，并且把场景中的TCP请求另存为接口存在显示问题

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11306]
**MeterSphere 版本**

1.18.1

复现步骤：
1.在TCP接口定义中创建TCP接口，在raw格式中使用xml格式的请求体，TCPClient选择LengthPrefixedBinaryTCPClientImpl，控制台报错
![binary-digit报错](https://user-images.githubusercontent.com/88763608/157453317-86c53221-5e89-4e34-891b-926e0f2f363e.jpg)
![digit](https://user-images.githubusercontent.com/88763608/157453405-8e995599-25d1-4859-846d-fdf6f93e2d9e.jpg)
2.在接口自动化中导入TCP请求的JMX文件，TCP接口请求内容跟在接口调试中保持一致，能正确返回响应
3.把接口自动化中的TCP请求另存为接口定义，可以执行成功，但是TCPClient名称显示错误
![另存为接口成功](https://user-images.githubusercontent.com/88763608/157454584-3c0a7ac1-58f6-4a2a-8964-adac5bc3ef0c.jpg)
<img width="327" alt="另存为接口定义Bug" src="https://user-images.githubusercontent.com/88763608/157454733-bee444ea-968c-4cd4-af01-dea6ed8a4d83.png">

4.把以上另存为接口定义中显示错误的TCPClient重新选择为LengthPrefixedBinaryTCPClientImpl，再次执行报错
![另存后再选报错](https://user-images.githubusercontent.com/88763608/157454787-b2e37141-d612-424c-a114-91cdff2b88f1.jpg)

5.总结：该接口 快捷调试和直接创建接口不能成功，导入接口自动化能成功，接口自动化另存接口定义能成功，但是不知道区别在哪里

**Comment by zyyfit** [comment]
最终解决情况：
1、以前选 LengthPrefixedBinaryTCPClientImpl 格式（需要传16进制格式请求），发送16进制报文控制台会报错（因为带上了行尾字节值），目前已修复
2-3、jmx场景里的tcp请求另存为接口定义后，tcp client 名字没变成系统里对应的名称，写的时候需要写成跟系统里一样的
4、同1
5、没有复现
