### ISSUE TITLE
[FEATURE]测试计划的任务通知过于简单

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#11319]
**MeterSphere 版本**

1.18.0

**Bug 描述**

测试计划的任务通知过于简单

**Bug 重现步骤**

1.  测试跟踪-测试计划--
2. 定时任务--任务通知--设置邮箱接收
3. 
4. 

**期待的正确结果**

邮箱接收的内容太过于简单，建议将报告之类的一起发

**截图**
![image](https://user-images.githubusercontent.com/19423100/157602171-69545da7-b9e2-4693-8cfa-6ab7203cad29.png)

![image](https://user-images.githubusercontent.com/19423100/157601918-74a5acf7-61f8-4b31-b253-228e001934ce.png)

**Comment by legend818** [comment]
你至少将上图当中一些执行结果一起发了啊

**Comment by Hyyfit** [comment]
已规划，待排期
