### ISSUE TITLE
[BUG]测试计划里面无法筛选失败的测试结果用例

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#11310]
**MeterSphere 版本**
 v1.18.0
**Bug 描述**
 测试计划 规划详情里面，测试结果栏筛选失败的用例无效
**Bug 重现步骤**

**期待的正确结果**
可以正常筛选出失败的测试用例
**截图**
![image](https://user-images.githubusercontent.com/37204403/157576088-8ff5f45f-5cfe-4009-a664-f30766c63a69.png)
![image](https://user-images.githubusercontent.com/37204403/157576480-df8dbe29-c557-4404-b9db-c5531dcdf8a6.png)

**Comment by ltfit** [comment]
感谢反馈后续版本会修复

**Comment by ltfit** [comment]
1.19版本已修复此问题
