### ISSUE TITLE
[BUG]性能测试执行后日志详情有时候会没有日志，刷新一下页面后会显示出来

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#11315]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  场景创建性能测试
2. 点击“保存并执行”按钮
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/97216833/157584238-f8a21746-4bf6-454f-8083-8f633d3be6a6.png)
![image](https://user-images.githubusercontent.com/97216833/157584297-94a87954-f600-4c54-bb3e-4e3bb176ad98.png)
![image](https://user-images.githubusercontent.com/97216833/157584337-bb3f7f1b-bce3-4c5b-9694-75577847daa0.png)

**Comment by ltfit** [comment]
您好 没有复现这种问题  出现的频率高吗 能否导出下文件 我这边复现下

**Comment by zhangzhaox** [comment]
大概率是数据库性能问题，查询的慢，导致看到的现象
