### ISSUE TITLE
[BUG] 进行压测后，使用kafka对数据回写到数据库中时候会经常锁死表而更新或者插入report数据失败

### ISSUE THREAD

**Issue by owen0204** [metersphere/metersphere#11316]
**MeterSphere 版本**

1.18.1

**Bug 描述**

进行压测后，使用kafka对数据回写到数据库中时候会经常锁死表而更新或者插入report数据失败

**Bug 重现步骤**

1.  使用docker节点压测
2. kafka回写report数据
3. ### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
### The error may exist in io/metersphere/streaming/base/mapper/LoadTestReportResultMapper.xml
4. 因为没有数据无法在页面展示图形

**期待的正确结果**

应该数据被插入正确

**截图**

![image](https://user-images.githubusercontent.com/35062109/157596210-21975ed9-51b4-44c2-baa0-93cc9fdf3c02.png)

**Comment by liuruibin** [comment]
部署方式是什么呢 并发数 机器配置什么的方便提供吗

**Comment by owen0204** [comment]
![image](https://user-images.githubusercontent.com/35062109/157798994-79c95737-c4ed-4c6d-bc45-dcd7e0de4ffb.png)

这是我的部署环境配置
window10环境下的
metersphere-server 和 node-controller 和 data-streaming都是在本地环境启动
jmeter服务在docker环境运行的
zookeeper和kafka也都是在本机运行的

**Comment by lmtoc** [comment]
请问这个问题有结论了吗 我们运行性能压测也遇到了一样的问题 数据库是外部部署的
