### ISSUE TITLE
[BUG]python生成的变量给HTTP配置的headers使用，拿不到value

### ISSUE THREAD

**Issue by 735670042** [metersphere/metersphere#11322]
**MeterSphere 版本**

V1.18.1

**Bug 描述**

python生成的token给HTTP配置里面的headers使用，执行用例时，headers里面取不到token

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="204" alt="09a97a734d9ab2755612c5ce2d68366" src="https://user-images.githubusercontent.com/30249764/157619837-69fa1bb4-21d5-429f-b1b5-4f0c52013400.png">

<img width="334" alt="50b46945b9c0b0082c56509f4556014" src="https://user-images.githubusercontent.com/30249764/157619858-a7a4123b-83a1-4c19-b329-a7764d7eac8b.png">

<img width="583" alt="797f8e053ec9214f12349f69127001c" src="https://user-images.githubusercontent.com/30249764/157619935-f228e7d6-7fe6-4034-87c2-05ba55e2f6a5.png">

**Comment by 735670042** [comment]
现在demo环境也是同样的问题，请问现在这块是有什么特殊处理吗？

**Comment by 735670042** [comment]
![image](https://user-images.githubusercontent.com/30249764/157621889-558d6162-102f-4a3e-aa41-c126b4ea0a61.png)
![image](https://user-images.githubusercontent.com/30249764/157621935-87e953c6-0c20-46a7-ba08-099119ac295c.png)
这样去执行case的时候headers里面也是拿不到对于的value

**Comment by zrfit** [comment]
接口case的执行-所有请求步骤的脚本未执行，后续版本优化。

**Comment by zyyfit** [comment]
最新逻辑：case执行时，所有请求步骤的脚本不生效，单个请求步骤的脚本才会生效。所有请求步骤的脚本只针对场景。
