### ISSUE TITLE
[BUG]测试计划中的功能测试用例列表 分页无效

### ISSUE THREAD

**Issue by renjinxiao** [metersphere/metersphere#11324]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是 1.18.0

**Bug 描述**

简要描述您碰到的问题:测试计划中的功能测试用例列表 分页无效

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26789277/157627553-e213dda8-dd13-459f-9c43-f6b57eb20ef3.png)

**Comment by ltfit** [comment]
感谢反馈 后续优化

**Comment by ltfit** [comment]
您好 我这边没有复现  方便导出用例吗 我这便尝试下

**Comment by renjinxiao** [comment]
版本：1.18.1
步骤：
&nbsp; &nbsp;1、路径 【测试跟踪】【测试计划】 点击测试计划进入测试计划管理页面
&nbsp; &nbsp;2、在测试计划管理页面，点击功能测试用例
&nbsp; &nbsp;3、在功能测试用例右下角 选择5条/页&nbsp; &nbsp; 查询失效
&nbsp; &nbsp;4、在功能测试用例右下角 点击第2 3 4&nbsp; &nbsp; 查询失效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]测试计划中的功能测试用例列表 分页无效 (Issue #11324)





 
您好 我这边没有复现  方便导出用例吗 我这便尝试下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltfit** [comment]
升级到最新版本再试下
