### ISSUE TITLE
[BUG]执行接口case成功后，删除该测试报告，接口case执行结果又变成“未执行”，执行结果选择“未执行”筛选不出来，选择“通过”才能筛选出来

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#11320]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在接口定义-case列表中执行接口case成功
2. 在测试报告列表中删除该测试报告
3. 查看接口case执行结果
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/97216833/157602704-99b1e0a2-f511-4f9a-8034-96b786c20684.png)
![image](https://user-images.githubusercontent.com/97216833/157603028-8c633114-7e57-4390-8a63-c43c6594afe5.png)
![image](https://user-images.githubusercontent.com/97216833/157603074-801d406e-f2f5-4e7c-b30f-a36f9308f4f6.png)
![image](https://user-images.githubusercontent.com/97216833/157603131-9fbc14ea-f0bc-4ca3-b918-9da8ef84b5a1.png)

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
