### ISSUE TITLE
[BUG] 性能测试报告--监控详情 没有数据，v1.16.6

### ISSUE THREAD

**Issue by mingregister** [metersphere/metersphere#11329]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？v1.16.6

**Bug 描述**

简要描述您碰到的问题
   性能测试报告--监控详情 没有数据 
**Bug 重现步骤**

1.  配置性能测试
2.  配置性能测试--高级配置--监控--添加--监控配置(IP尝试填写节点池ip及prometheus ip)
3.  "保存并执行"性能测试
4. 等待测试结果

**期待的正确结果**

正确情况下应该是什么样的？   性能测试报告--监控详情 有数据

**截图**
![image](https://user-images.githubusercontent.com/27017675/157639243-ad685f03-a75d-4a3a-915b-0644ebce2292.png)

如果有截图，请附上截图.

**Comment by liuruibin** [comment]
可以在prometheus的后台看看有没有上报上去，如果是all-in-one安装的话，prom的端口是9090，可以在浏览器中打开对应的地址找到http://ip:9090/targets 看看有么有这个资源池的数据
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/23045261/157797698-fa26bd29-97d7-4dec-829b-318416675029.png">
如果状态是down，可以在后台执行

```
docker stop nodeexporter
docker rm nodeexporter
msctl reload
```

**Comment by mfanoffice** [comment]
在下遇到同样问题，但经过排查，发现监控指标的计算公式有问题：
只要公式中带有时间段就获取不到结果，如下图：
<img width="936" alt="图片" src="https://user-images.githubusercontent.com/48307752/158308889-7917159d-eafb-437c-bc06-05e8c90bb7ae.png">
<img width="1363" alt="图片" src="https://user-images.githubusercontent.com/48307752/158308900-cd51bea9-b6d6-48d3-b17d-dbfd4dbd7dbb.png">
 
memory和disk没有带[1m], 所以可以有数据，当然等再长时间也只有这两个指标的数据。
