### ISSUE TITLE
[BUG] CAS认证所记录的用户名不是CAS Server返回的值

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11328]
**MeterSphere 版本**

1.18.1

**Bug 描述**

MS配置CAS认证后，所保存的用户名 并非由CAS server返回的值，而直接保存用户在登录框输入的用户名。
由于手工输入可能会存在大小写字母的问题，因此会导致同一个用户可能在MS产生“不同”的用户名，比如：
ABCDE
Abcde
abcde
使CAS 用户名产生混乱。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
我们的表基本上都是忽略大小写的，只有user表的id字段是区分的，可以执行 ALTER TABLE user
MODIFY id VARCHAR(50) COLLATE utf8mb4_general_ci;
