### ISSUE TITLE
[BUG]正常操作中的页面有时候会提示认证信息已过期，请重新登录

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#11338]
**MeterSphere 版本**

1.18.1

**Bug 描述**

正常操作中的页面有时候会提示认证信息已过期，请重新登录

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

不应该用着用着突然退出登录了

**截图**

![image](https://user-images.githubusercontent.com/40912823/157660940-0820da40-c770-48c7-890c-441522234cc7.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有遇到这个问题，同一浏览器没有登录其他账号吗？或者有log日志发下我们看看
