### ISSUE TITLE
[BUG]使用火狐浏览器登录MeterSphere时，前端页面报错导致无法登录

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11332]
**MeterSphere 版本**

V1.18.1
火狐版本：52.2.0

**Bug 描述**

使用火狐浏览器登录MeterSphere时，前端页面报错导致无法登录
报错信息:TypeError: vt[e].push is not a function

**截图**
![c4068432d060f5512e23130ebe85f4a](https://user-images.githubusercontent.com/92150453/157643146-e5cc3b7c-538d-4c35-91a5-be0c9e3a8124.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这种环境比较不常见，我们准备下环境，看是否复现

**Comment by youliyuan-fit2cloud** [comment]
你这 火狐浏览器版本过低了，升级下版本试试？

**Comment by sageonedream** [comment]
ok，有空我用高版本验证下，之前是用镜像里自带的火狐



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月11日(周五) 中午11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]使用火狐浏览器登录MeterSphere时，前端页面报错导致无法登录 (Issue #11332)




 
你这 火狐浏览器版本过低了，升级下版本试试？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
