### ISSUE TITLE
MeterSphere v1.19.0 版本规划 （2022-03-24）

### ISSUE THREAD

**Issue by luty2018** [metersphere/metersphere#11341]
![image](https://user-images.githubusercontent.com/36292514/157792915-e9ebcb99-6b6a-4f43-8f90-c71ddf3e9ed9.png)

**Comment by maninhill** [comment]
强，加油。

**Comment by GITMrzk** [comment]
模板管理调整，希望能考虑到组织级需要统一模板的需求，现在工作空间级别还比较好调整，如果下沉到项目级，还要一个个字段配置，那就太麻烦了。

**Comment by Hyyfit** [comment]
已规划，待优化。
