### ISSUE TITLE
[BUG]  v1.18.1【接口定义/TEST】页面，POST接口，执行时却提示是GET接口

### ISSUE THREAD

**Issue by jinwu18** [metersphere/metersphere#11344]
![微信图片_20220311112110](https://user-images.githubusercontent.com/20297570/157795993-039c8aa1-a21a-474c-ab8c-cd21243ddd29.png)
![微信图片_20220311112110](https://user-images.githubusercontent.com/20297570/157795994-0d922c00-0a27-4aab-ae62-f56cea39ac3f.png)
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  快速创建一个post接口，执行时返回正常结果
2. 保存后，进入【接口定义/TEST】页面列表，执行刚保存的接口，提示当前接口不支持GET请求，实际接口类型是POST

**期待的正确结果**
正常调试接口

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，未复现该问题，能否导出接口我们尝试复现。

**Comment by xzd** [comment]
@jinwu18 可以看下你的测试环境，可能是因为没有选择 https 协议
