### ISSUE TITLE
[BUG]性能测试执行存在问题

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11346]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个包含登录退出的场景，场景调试没有报错
2. 将创建的场景添加到性能测试
3. 使用local资源池执行 ，压测用户5，持续时间20秒，保存并执行
4. 发现结果中，各接口均存在报错error%   75%
5. 关闭场景中的退出接口，添加到性能测试执行
6. 查看结果所有接口均正确error%为0

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好 我这边没有复现该问题  是否有特殊的配置

**Comment by liuruibin** [comment]
并发用户为1来测试没有任何问题，这相当于线性流程

我用两个并发用户来测试，就会出现登录接口调用两次的情况，这时候退出第一个就会失败，并发用户数继续增多会出现同一个用户登录多次，而退出接口只能退出最后一次登录的那个token

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/23045261/158003945-4c25a616-89ae-4f44-9e2c-5a0fd0abc28b.png">

这种情况建议用setup和teardown线程组来执行登录和退出
<img width="978" alt="image" src="https://user-images.githubusercontent.com/23045261/158004164-cc010c48-14b6-435b-882b-2392da92a253.png">
