### ISSUE TITLE
[BUG]性能测试执行的文件不是加载的文件

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11347]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建性能测试
2. 点击引用自动化场景，添加两个场景
3. 选择local资源池，并发用户5压测20s，保存并执行
4. 查看结果执行的文件不是加载的文件

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="974" alt="图片1" src="https://user-images.githubusercontent.com/36387811/157798129-0115189c-c4a5-490d-a98c-693dce713bc6.png">
<img width="942" alt="图片2" src="https://user-images.githubusercontent.com/36387811/157798156-5f44898f-2e72-4668-8342-890c98daf611.png">
![图片3](https://user-images.githubusercontent.com/36387811/157798167-1acf3478-3487-48fa-ba8f-a6212eea8134.png)

**Comment by ltfit** [comment]
您好 能否导出下 文件我这边尝试复现下

**Comment by ltfit** [comment]
您好 我这边多次尝试没有复现 您这边是每次都会出现这种问题吗

**Comment by ltfit** [comment]
您好 请求统计的显示的是 接口的名称 不是场景的名称
