### ISSUE TITLE
[BUG]swagger导入接口请求参数是否必选没有导入

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11343]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  本地导入swagger接口 swagger2.0
2. 查看请求内容 json-schema 看到请求参数是否必选框没有勾选上
3. 
4. 
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![wecom-temp-843439c4e7066317bf9b15ab127edc9d](https://user-images.githubusercontent.com/36387811/157795916-a4e57fb0-2d29-430b-bed8-c6965fc40468.jpg)

**Comment by zrfit** [comment]
v1.19版本已修复改问题。
