### ISSUE TITLE
[BUG]v1.18.1版本升级后，出现场景用例和接口定义缺失

### ISSUE THREAD

**Issue by tina1993tina** [metersphere/metersphere#11357]
您所使用的 MeterSphere 版本是？
V1.18.1
**Bug 描述**
v1.14版本升级到v1.18.1版本后，出现2个场景用例和接口定义缺失，因列表内找不到的接口定义和场景，就去操作日志看一下是不是被删除了 。没有找到被删除的日志，就从标题点进去，点进去后跳转到页面，点击保存 ，接口列表数据全部无法显示

**Bug 重现步骤**
1.出现场景用例和接口定义缺失
2.系统设置-操作日志内，从标题连接进入
![微信图片_20220311141313](https://user-images.githubusercontent.com/101318817/157814944-1ba5e3ab-df54-4a18-ad15-f75a5a79c594.png)
3.连接跳转后，点击保存，接口定义列表数据全部无法显示

![Snipaste_2022-03-11_14-39-04](https://user-images.githubusercontent.com/101318817/157815683-875735d1-b136-4a3c-bdbf-187664b0d87c.png)
4.重新从操作日志内标题进入，点击保存

![微信图片_20220311141531](https://user-images.githubusercontent.com/101318817/157815770-0d4b741f-b735-4a55-b4aa-0bd223998b58.png)

5.查看日志，当前时间点并没有什么错误日志
![20220311-144402](https://user-images.githubusercontent.com/101318817/157816332-5e7cf152-3925-4a27-8fa8-e63413233883.png)

**期待的正确结果**
首先不应该出现场景用例和接口定义的缺失，缺失原因不明，场景用例操作日志链接点击进去保存，都提示“已存在”，但是保存后列表内也显示不出来。其次接口定义 操作日志链接点击进去保存，接口定义全部无法显示，判断是数据库依然存在，只是界面展示问题。希望尽快定位问题修复，我们用例涉及比较大量。

**Comment by tina1993tina** [comment]
版本回退到1.14，数据库是1.18的，则不展示的数据都可以展示，是否是前端问题？

**Comment by zrfit** [comment]
您好，因为每个升级版本都有对数据库的升级操作，有些版本中这些操作会花费一定时间。
跨四个版本升级的话升级脚本运行时间可能会过长，导致部分脚本运行超时，然后就会出现各种问题。
建议您升级的时候按照大版本升级。从15、16等大版本逐步升级上来。如果遇到困难可以联系交流群中的申凯波。
