### ISSUE TITLE
[BUG]配置运行环境中的数据库连接报错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11353]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在运行环境中添加数据库配置
2. 数据库配置正确，数据库的版本是8.0，连接的数据库不是metersphere的

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1361" alt="截屏2022-03-10 17 38 19" src="https://user-images.githubusercontent.com/36387811/157810194-1293199c-fa17-483b-a329-9054a95241de.png">

**Comment by liuruibin** [comment]
我自己用1.18.1来连接8.0的数据库没有问题
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/23045261/157820792-ba26743a-fa6c-498e-9f30-8136e7eb2810.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/23045261/157820882-8fe47456-7523-4441-bb98-8aed3c8bb99b.png">
