### ISSUE TITLE
[BUG]MS脑图点一次保存能正常保存，再点一次保存或者再多点几次保存后最新写的用例就没有了

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#11356]
1.18.2

![MS保存bug](https://user-images.githubusercontent.com/44999044/157813270-6d3535e3-a646-4152-bf6d-482dafac87f2.gif)

**Comment by ltfit** [comment]
您好 我这边没有复现。 用例能否导出下 我这边尝试复现下

**Comment by LimonFHM** [comment]
> 您好 我这边没有复现。 用例能否导出下 我这边尝试复现下

是不容易复现，也不知道如何复现，但是7个组员都碰到过这种情况，刻意去重现又重现不了。

**Comment by LimonFHM** [comment]
> 您好 我这边没有复现。 用例能否导出下 我这边尝试复现下

最直观的就是：写着写着 丢两条用例

**Comment by libb-test123** [comment]
这个问题我们的测试团队也遇到了，感觉问题还挺严重的。

**Comment by libb-test123** [comment]
基本上是100%复现，使用的版本是v1.18.0

https://user-images.githubusercontent.com/67257251/160823116-449f0e1e-e589-4fec-be0d-365cdd5581f5.mp4

**Comment by bellsy** [comment]
同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了

**Comment by libb-test123** [comment]
> 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了


> 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了
可以升级到V1.19.1我们团队升级到这个版本已经一段时间了

**Comment by bellsy** [comment]
> > 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了
> > 可以升级到V1.19.1我们团队升级到这个版本已经一段时间了

目前用的V1.19.3  问题依旧出现

**Comment by bellsy** [comment]
> > 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了
> > 可以升级到V1.19.1我们团队升级到这个版本已经一段时间了

目前用的V1.19.3  问题依旧出现

**Comment by ltfit** [comment]
> > > 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了
> > > 可以升级到V1.19.1我们团队升级到这个版本已经一段时间了
> 
> 目前用的V1.19.3 问题依旧出现

您好 这个问题在1.19.1修复过了，您这边是有什么特殊操作么。我这边尝试还是复现不了

**Comment by bellsy** [comment]
> > > > 同样遇到这个问题，保存提示成功了，但是用例没有。模块都丢失了
> > > > 可以升级到V1.19.1我们团队升级到这个版本已经一段时间了
> > 
> > 
> > 目前用的V1.19.3 问题依旧出现
> 
> 您好 这个问题在1.19.1修复过了，您这边是有什么特殊操作么。我这边尝试还是复现不了

用思维导图直接写用例，点击保存提示成功，但是页面刷新后直接没了  模块也没有了。  偶现

**Comment by Yo00Yo** [comment]
我也遇到了同样的问题，目前发现必现规律是，思维导出到第四级的时候 ，增加的同级 就会丢失

**Comment by ltfit** [comment]
> 我也遇到了同样的问题，目前发现必现规律是，思维导图到第四级的时候 ，再增加的同级 保存后出去再进来 就会丢失 版本是v1.19.3

你好 到了用例级别后，如果打了用例标签，用例下面只能保存两级，一级是步骤，第二级是预期，再往下就不保存了，你截个图我看下你写的用例
