### ISSUE TITLE
[FEATURE]企业微信消息按场景发送，消息太多，不好识别失败的通知

### ISSUE THREAD

**Issue by xqwbmw** [metersphere/metersphere#11355]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.17.2-067bbbdc

**Bug 描述**
之前是一个计划企业微信收到一条报告，后来升级过一次后
目前只是给Jenkins任务通知配置了企微的1个成功，1个失败，其他任务通知都是默认的站内通知，场景本身也没有配置，
现在的情况是一个计划里面有10个场景，就会收到10条通知，经常群里炸锅，不好识别失败的

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

一个计划收到一个整体的汇总报告，不然群里很多消息会很乱（同事希望，能将成功显示为绿色，失败显示为红色，并提升出那个场景哪一步失败了）

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期
