### ISSUE TITLE
[BUG]场景变量没有大于全局变量

### ISSUE THREAD

**Issue by tina1993tina** [metersphere/metersphere#11350]
您所使用的 MeterSphere 版本是？
v1.18.1
**Bug 描述**
场景变量没有大于全局变量

**Bug 重现步骤**
1.  设置全局变量A=11111
2. 设置场景变量A=22222
3. 场景内请求引用变量${A}
4. 获取的是A=1111

**期待的正确结果**
预期获取的是A=2222

v1.17版本出现的问题是全局变量>场景变量>内部变量，后V1.18版本说修改成正确的内部变量> 场景变量>全局变量，但是没有修改完全，场景变量依然没有大于全局变量。

**Comment by zrfit** [comment]
v1.19版本已解决。
