### ISSUE TITLE
[BUG]功能用例的单个步骤如果有换行，在导出成xls文件，再导入后，会变成两个步骤

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#11377]
**MeterSphere 版本**
v1.18.1

您所使用的 MeterSphere 版本是？
v1.18.1

**Bug 描述**
功能用例的单个步骤如果有换行，在导出成xls文件，再导入后，会变成两个步骤

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
<img width="1061" alt="WechatIMG649" src="https://user-images.githubusercontent.com/18387151/157848031-953a379a-c356-41f2-9799-529e90d83218.png">
<img width="933" alt="WechatIMG650" src="https://user-images.githubusercontent.com/18387151/157848041-4a89acb8-2e0c-431d-8ebf-2c700dfc221c.png">

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by zyyfit** [comment]
导出的单个步骤含有换行符，我们导入逻辑认为有换行就是一个新的步骤，逻辑有冲突，现在已修改为导出时如果单个用例有换行，去掉换行符

**Comment by zyyfit** [comment]
1.20.7版本发布，请等待发版后验证
