### ISSUE TITLE
msctl start 后ms-data-streaming&ms-server&nodeexporter都提示error怎么办

### ISSUE THREAD

**Issue by songxin6** [metersphere/metersphere#11385]
**请描述您的问题.**
问题如下
![image](https://user-images.githubusercontent.com/51051155/158001627-24cdbaf3-acc7-4aba-8f57-a14480170cd4.png)

**Comment by liuruibin** [comment]
能看到各个容器的详细日志吗 docker logs -f ms-server 执行看看

**Comment by songxin6** [comment]
@liuruibin 
![image](https://user-images.githubusercontent.com/51051155/160320798-355cdf81-6b6b-4172-9019-807704d59d60.png)
