### ISSUE TITLE
[BUG]测试计划场景用例，关联测试用例中环境列表未显示

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11380]
**MeterSphere 版本**
1.18.2

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试计划
2. 接口用例
3. 场景用例
4. 关联测试用例中环境列表未显示

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/20190050/157857382-33f24027-5b5a-4f00-a615-5ab254920c92.png)

**Comment by ltfit** [comment]
您好 这个需要选中用例之后才会显示

**Comment by 472173257dl** [comment]
> 您好 这个需要选中用例之后才会显示
选择后也没显示
![image](https://user-images.githubusercontent.com/20190050/157858269-c1b5f776-885d-4940-8cd4-ddf804c02e39.png)

**Comment by ltfit** [comment]
您在接口测试中 是否可以执行呢

**Comment by 472173257dl** [comment]
> 您在接口测试中 是否可以执行呢

接口测试中可以选择到对应环境列表

**Comment by ltfit** [comment]
您好 ，能否导出下用例我这边尝试复现下
