### ISSUE TITLE
[BUG] CAS的不同用户属性登录后会保存为两个不同的MS用户

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11386]
**MeterSphere 版本**

v1.18.1

**Bug 描述**

在配置了CAS认证后，用户在登录MS时，既可以选择<员工号+密码> 登录，也可以通过<用户名+密码>登录。
但是在登录后，MS会保存为两个不同的用户，造成很大困扰。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

无论用户选择哪个属性登录，MS应该视为同一用户。

**截图**

如果有截图，请附上截图.

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
