### ISSUE TITLE
[BUG]性能测试测试详情左边的标签栏，点击后展开没有数据，只有报告结束后才能展示

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11383]
**MeterSphere 版本**

1.18.1

**Bug 描述**

性能测试测试详情左边的标签栏，点击后展开没有数据，只有报告结束后才能展示.
既然显示了标签，应该任何时候展示都要有数据，展开是空白的没有意义，且容易误解
![image](https://user-images.githubusercontent.com/88763608/157998371-71f1a980-64fa-412a-8e0c-361cf0435007.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
可以考虑优化，待排期。
