### ISSUE TITLE
[BUG]升级到最新版后所有用例执行均报sql错误

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11388]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
最新版1.18.2

![image](https://user-images.githubusercontent.com/20190050/158090188-9dc7210a-e4e1-4099-81b5-415aeeb326b5.png)

**Comment by 472173257dl** [comment]
问题是从这次提交后出现的
![image](https://user-images.githubusercontent.com/20190050/158094785-2b846ec9-9f51-4687-baa8-5a071854f4d0.png)
并且这次提交新增了迁移，但执行时报错
![image](https://user-images.githubusercontent.com/20190050/158094865-5494cd28-2b61-4dbd-81fe-94161272bb69.png)

**Comment by zrfit** [comment]
您好，未复现该问题，是否有其它步骤测操作吗？接口信息有特殊配置吗？

**Comment by xiaomeinvG** [comment]
红线圈住的是未发布的代码，建议您用1.18分支的代码
