### ISSUE TITLE
[BUG] 自定义jar包中引用的第三方jar无法处理

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11387]
**MeterSphere 版本**

v1.18.1

**Bug 描述**

自己写了个自定义jar包，用来连接oracle数据库做测试数据的准备工作，该.jar包引用了orai18n.jar，在原生JMeter中能正常运行，但上传至MeterSphere上后抛异常：
org.dbunit.DatabaseUnitException: Exception while checking the schema for validity
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)

在前置脚本中的语句为：
 import com.cocs4cloud.xxx.data1.DataInit;
 DataInit dataInit = new DataInit(<database connection information>);

将orai18n.jar通过“上传自定义jar包”的功能上传后，依然未能解决。
目前只能将本地JMeter的lib目录复制到ms-server容器内的 /opt/jmeter/lib目录下临时解决，但是如果执行msctl reload或者升级，又会丢失。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

 希望：
1. 能支持此类情况
2. 提供更友好的调试和日志打印，支持用户自己的调试
3. 明确日志什么情况下打印在 docker logs 中什么时候打印在页面控制台

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。
