### ISSUE TITLE
[BUG]创建场景用例接口不存在，导致无法保存场景用例

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11396]
**MeterSphere 版本**
1.18.2

![image](https://user-images.githubusercontent.com/20190050/158111482-cba00ce9-2d57-41fb-95a5-137b15e7a661.png)

![image](https://user-images.githubusercontent.com/20190050/158111521-1d3867d6-7b3c-4e73-b7e1-b6725d355a6f.png)

**Comment by 472173257dl** [comment]
新建的空间下新建项目然后创建接口可复现

**Comment by song-tianyang** [comment]
您好，1.18.2版本源码未发现此问题

**Comment by song-tianyang** [comment]
您好，这个接口真实存在，是您的搜索方式有问题。您如果仔细看的话，在Controller里面会有更详细的接口。
在1.18.2分支的代码也没发现您说的这种问题，可能您更新的1.18分支是处于小版本迭代中

**Comment by song-tianyang** [comment]
您好，这个接口真实存在，是您的搜索方式有问题。您如果仔细看的话，在Controller里面会有更详细的接口。

在1.18.2分支的代码也没发现您说的这种问题，可能您更新的1.18分支是处于小版本迭代过程中的代码，会有还未经过测试的缺陷。您可以根据1.18.2的tag来check out代码
