### ISSUE TITLE
[BUG]缺陷管理这里少了几个重要字段的筛选功能,状态 、严重程度 、处理人

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11395]
**MeterSphere 版本**

1.18.1

**Bug 描述**

这个缺陷管理这里少了几个重要字段的筛选功能

1、状态
2、严重程度
3、处理人
希望能加上筛选功能

不然，缺陷数量较多了，查找自己需要负责的缺陷 或者查看优先级等，就不方便
<img width="1435" alt="bug" src="https://user-images.githubusercontent.com/88763608/158102644-93e62245-3f5c-43b3-812e-334c61563511.png">

**Comment by zyyfit** [comment]
1.19.0会增加自定义筛选功能

**Comment by zyyfit** [comment]
1.19.0没加，可能会1.20或者再后面加
