### ISSUE TITLE
接口请求失败，建议可以设置超时返回

### ISSUE THREAD

**Issue by zhuangjd** [metersphere/metersphere#114]
**请描述您的需求或者改进建议.**

接口请求失败，等待超时返回时间比较久，需要几十秒时间，一直在加载，页面可以控制让后端请求加载，状态类似为“请求中。。。"，不用在前端页面等待处理完成

**请描述你建议的实现方案**
在添加接口的时候可以增加设置超时选项，或者全局变量控制选项也可以

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
