### ISSUE TITLE
[BUG]升级至最新版本后，平台打开自动化场景用例非常卡

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#11402]
**MeterSphere 版本**
1.18.2
您所使用的 MeterSphere 版本是？
1.18.2
**Bug 描述**
升级至最新版本后，平台打开自动化场景用例非常卡
简要描述您碰到的问题

**Bug 重现步骤**

1.  
![f0d72fbfc788ea82d62d52b033ba2f5](https://user-images.githubusercontent.com/18163887/158125317-9e31a333-e815-4399-a1e8-28038db3d4da.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
最新版本v1.20.5已优化，建议升级
