### ISSUE TITLE
[BUG]请求后右上角成功失败通知，人名错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11408]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  系统操作只有一个账号一个用户
2. 在系统消息通知里的用户名称有时是错误的
3. 备注：：：客户系统的消息中心，客户信息有误，我这里没有复现，但是在客户系统里可以出现。
4. 
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，未复现该问题，能否提供详细的操作步骤，还有对应截图。
