### ISSUE TITLE
[BUG]点击测试报告邮件中链接跳转至平台页面提示：报告已删除

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#11406]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是：1.18.1

**Bug 描述**

点击测试报告邮件中链接跳转至平台页面提示：报告已删除

**Bug 重现步骤**

1.  点击测试报告邮件中链接

**期待的正确结果**
测试报告邮件中链接跳转至测试报告页面

**Comment by ltfit** [comment]
您好 具体配置的那个消息通知呢

**Comment by kusotest** [comment]
场景用例的定时任务



***@***.***
 
发件人： ltfit
发送时间： 2022-03-14 19:57
收件人： metersphere/metersphere
抄送： kusotest; Author
主题： Re: [metersphere/metersphere] [BUG]点击测试报告邮件中链接跳转至平台页面提示：报告已删除 (Issue #11406)
您好 具体配置的那个消息通知呢
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltfit** [comment]
![Uploading image.png…]()
是配置的这个字段吗

**Comment by ltfit** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/99794211/158191601-16a9102b-e695-491b-a9fe-c9105a951fd3.png">
是配置的这个字段吗

**Comment by kusotest** [comment]
设置的接口自动化场景用例的定时任务



***@***.***
 
发件人： ltfit
发送时间： 2022-03-14 22:20
收件人： metersphere/metersphere
抄送： kusotest; Author
主题： Re: [metersphere/metersphere] [BUG]点击测试报告邮件中链接跳转至平台页面提示：报告已删除 (Issue #11406)

是配置的这个字段吗
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltfit** [comment]
您好 我这边尝试了下 是可以跳转  建议升级到1.18.2 再尝试下

**Comment by kusotest** [comment]
测试报告邮件链接：#/api/automation/report/view/442f3853-bf62-479a-aef3-bad607201707
实际测试报告链接：#/api/automation/report/view/8a13a41e-e5ec-4185-8f7e-c62c063c9dfd

测试报告邮件中链接参数与实际不一致导致点击测试报告邮件链接提示：测试报告已删除



***@***.***
 
发件人： ltfit
发送时间： 2022-03-14 22:20
收件人： metersphere/metersphere
抄送： kusotest; Author
主题： Re: [metersphere/metersphere] [BUG]点击测试报告邮件中链接跳转至平台页面提示：报告已删除 (Issue #11406)

是配置的这个字段吗
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltfit** [comment]
您好 v1.18.3版本已修复
