### ISSUE TITLE
[BUG]性能测试没有结果

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11401]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  场景执行没问题，创建性能测试，保存并执行，界面没报错，一致没结果
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/36387811/158117435-1d19ca12-0a53-4250-a65f-9ca5507db5e5.png">

**Comment by ltfit** [comment]
您好 能否提供下具体的场景脚本

**Comment by ltfit** [comment]
您好 我这边没有复现 能否提供下具体的场景脚本 我这边复现下
