### ISSUE TITLE
[BUG]环境配置--数据库配置校验报错

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#11410]
**MeterSphere 版本**
1.18.2
您所使用的 MeterSphere 版本是？
1.18.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![645e7f9bd238ad4b5fac5da5d41989d](https://user-images.githubusercontent.com/18163887/158149360-8859773f-4c62-48df-a242-3c87873ca3b5.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，是不是你改选 过“数据库驱动”，建议取消，重新进入该页面添加数据库再校验

**Comment by fangqiuhong** [comment]
> 你好，是不是你改选 过“数据库驱动”，建议取消，重新进入该页面添加数据库再校验

我没有改过数据库驱动，就是升级之后发现不能用了

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，是不是你改选 过“数据库驱动”，建议取消，重新进入该页面添加数据库再校验
> 
> 我没有改过数据库驱动，就是升级之后发现不能用了

建议取消校验，重新打开环境配置页面，更新下数据库驱动后校验 ？
如果还是报错，请把log截图我们看一下

**Comment by fangqiuhong** [comment]
> 

![image](https://user-images.githubusercontent.com/18163887/158291389-f4e90044-f5a0-4af6-be4a-5692d20b7761.png)
嗯，还是有报错，麻烦帮忙看看呢

**Comment by fangqiuhong** [comment]
> > > 你好，是不是你改选 过“数据库驱动”，建议取消，重新进入该页面添加数据库再校验
> > 
> > 
> > 我没有改过数据库驱动，就是升级之后发现不能用了
> 
> 建议取消校验，重新打开环境配置页面，更新下数据库驱动后校验 ？ 如果还是报错，请把log截图我们看一下

![image](https://user-images.githubusercontent.com/18163887/158296386-408779ec-97ec-47cc-9cde-9b0db0ffea4b.png)
嗯，还是有报错，麻烦帮忙看看呢

**Comment by youliyuan-fit2cloud** [comment]
你好，你这种情况我们估计是数据库url不对，数据库配置截图方便发一下吗？？

**Comment by fangqiuhong** [comment]
> 你好，你这种情况我们估计是数据库url不对，数据库配置截图方便发一下吗？？

![image](https://user-images.githubusercontent.com/18163887/158949971-452b5509-473a-4107-b3db-5ecb64380a93.png)
是平台的这个配置？

**Comment by fangqiuhong** [comment]
连接URL加上ssl配置后，正常了
