### ISSUE TITLE
[BUG]环境配置HTTP配置，导出配置后，发现无此配置

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#11427]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18.0
**Bug 描述**

简要描述您碰到的问题
环境配置HTTP配置，例如：https://centertest6.....，导出配置后，发现无此配置
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，导出环境配置后，http配置中url地址没了？json文件是空的？还是什么情况？

**Comment by fanyulei1223** [comment]
如图所配置
![image](https://user-images.githubusercontent.com/42166114/158290218-55adc275-b8a5-49bf-b024-387b347a5ff6.png)

导出后如下图，无环境域名配置
![image](https://user-images.githubusercontent.com/42166114/158290217-b01d362c-1126-480c-b6d1-e96cc2a69cbe.png)

**Comment by youliyuan-fit2cloud** [comment]
哦哦，是这样的你这个环境域名选择了启用条件是匹配”模块“了，然后导入到其他项目的话，模块名很可能不存在，我们当前设计不会导出这种匹配模块的环境

**Comment by fanyulei1223** [comment]
能否优化一下呢，关联的模块不导出可以理解，但是域名的配置不导出，配置起来比较麻烦，奇奇怪怪的域名/ip有很多个，加上环境数量也不少，手动配置比较花费时间

**Comment by youliyuan-fit2cloud** [comment]
我们内部讨论一下，目前没有好的解决方法
