### ISSUE TITLE
[FEATURE]测试计划列表中建议增加用例详情查看功能

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11428]
**请描述您的需求或者改进建议.**

测试计划中建议增加用例详情查看功能

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/20190050/158289298-6e5ae4be-0065-4259-b131-1a85686e912d.png)

**Comment by Hyyfit** [comment]
已规划，待排期。
