### ISSUE TITLE
[BUG]【接口自动化】点击场景用例【编辑】icon导致报错：内存溢出

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#11421]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是：1.18.1

**Bug 描述**

【接口自动化】点击场景用例【编辑】icon导致报错：内存溢出

**Bug 重现步骤**

1.  【接口自动化】点击场景用例【编辑】icon

**期待的正确结果**
进入场景用例编辑页面

**截图**

![image](https://user-images.githubusercontent.com/46745316/158160099-1cbaafc5-cbe7-4826-a638-5bc0e70046e7.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们在努力修复中，会尽快发个小版本~

**Comment by ltfit** [comment]
最新版本已修复  升级下
