### ISSUE TITLE
[BUG]测试计划中引入ID为个位数的用例时，启用ID排序功能，个位数ID显示有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11433]
**MeterSphere 版本**

V1.18.1

**Bug 描述**

测试计划中引入ID为个位数的用例时，启用ID排序功能，个位数ID显示有误，且无法选择升序，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/158306517-709124a5-36f0-4de9-b080-76e21687077d.png)
![image](https://user-images.githubusercontent.com/92150453/158306571-c5df2e9a-91d1-42e5-b9af-d55537bd4c60.png)

**Comment by ltfit** [comment]
您好 具体是哪里显示有误呢 我这边试了下可以升序

**Comment by ltfit** [comment]
您好 个位数id具体指的哪里显示有误呢。我这边试了下可以选择升序  可以升级最新版本再看下

**Comment by sageonedream** [comment]
在1.18.2能正常显示，并升序排列吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月15日(周二) 下午3:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]测试计划中引入ID为个位数的用例时，启用ID排序功能，个位数ID显示有误，且无法选择升序，请修改 (Issue #11433)




 
您好 个位数id具体指的哪里显示有误呢。我这边试了下可以选择升序  可以升级最新版本再看下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltfit** [comment]
可以升序排列

**Comment by sageonedream** [comment]
经确认可以升降序，但存在个位数ID时，升降序用例排序存在问题
https://user-images.githubusercontent.com/92150453/158333916-105a4348-02ee-4ce1-bf85-d31329746aa4.mp4

**Comment by ltfit** [comment]
这个自定义ID可以输入任意字符，排序规则是默认的。如果想按照数字顺序，必须长度一致，100001 100002
