### ISSUE TITLE
[BUG]单场景下包含过多的用例，使用卡顿

### ISSUE THREAD

**Issue by qwerrewq1** [metersphere/metersphere#11431]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是?
v1.18.0-9c635160

**Bug 描述**

简要描述您碰到的问题

       在接口自动化的场景，单场景下包含过多的用例（一百多个），加载会特别的慢；在调试的时候，页面卡顿，页面功能按钮无法点击，然后页面可能会停掉。
**Bug 重现步骤**

1. 创建场景，添加接口或用例（一百多个）
2. 点击调试 观察

**期待的正确结果**

优化下使用体验，内容的加载和场景的调试流畅一些。

**截图**
![image](https://user-images.githubusercontent.com/84369119/158296711-d18d667d-b048-44cc-9587-abff780a7a20.png)

![image](https://user-images.githubusercontent.com/84369119/158296561-4d9b293f-3726-404e-a92a-4f97b8f3a0a1.png)

![image](https://user-images.githubusercontent.com/84369119/158297191-6b706446-581f-4954-8f6f-ec8a063f7bbc.png)

**Comment by youliyuan-fit2cloud** [comment]
1.18.3已优化
