### ISSUE TITLE
[FEATURE]接口鉴权功能太弱不能满足使用要求

### ISSUE THREAD

**Issue by greedygod** [metersphere/metersphere#1143]
**请描述您的需求或者改进建议.**
目前MS接口测试支持的认证方式仅有basic一种。
无认证或者basic认证，只在本地调试或临时小范围才考虑用，达不到实际大型生产工作和安全标准的要求。

例如我司情况：接口开发使用RESTful规范，其中认证部分要求采用oauth2.0的client_credentials方式.
实际调用过程：需先通过系统的鉴权接口获取access_token，并在接口请求头中添加Authorization:bearer+${access_token｝
且token存在有效期限制。

[参考：RFC6749-4.4章节](https://tools.ietf.org/html/rfc6749#section-4.4)
ps：参考yapi中我们为此进行的二次开发，环境配置中添加了接口自动鉴权的设置项。
![image](https://user-images.githubusercontent.com/7498123/104000322-0a731780-51d9-11eb-896f-0a113618ebbf.png)

**请描述你建议的实现方案**
——请考虑增加其他更健壮的认证方式支持功能，或提供对应的前置步骤来支持人工获取并设置Authorization，否则接口无法通过认证。

**Comment by jjjttp** [comment]
+1，同样的需求。
鉴权功能做到“环境配置”中，生成的token可以在同一个环境中复用，而无需在每个接口用例编辑中添加前置。
