### ISSUE TITLE
[BUG]场景里的顺序和报告的顺序不一致

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11430]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   在场景中导入多个接口,为引用
2. 在场景中点击生成报告
3. 看到报告中接口的顺序和场景步骤顺序不一致
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/158293470-47cf7d54-ac84-48fc-92d3-0849edd84f49.png)
![image](https://user-images.githubusercontent.com/36387811/158293546-9abf57f4-8f8d-4043-a1f0-b099ddb3941c.png)

**Comment by zrfit** [comment]
最新版本已解决该问题，建议升级到最新版本。
