### ISSUE TITLE
[BUG]jsonpath断言在结果中没有体现出来实际填写的断言类型

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11432]
**MeterSphere 版本**

1.18.2

**Bug 描述**

jsonpath断言在结果中没有体现出来断言类型
比如：
不等于要加 un
小于要体现<   等等

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/20190050/158302499-a1409c4e-19e5-4731-9ab0-8ece1ddf5fff.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，目前产品设计如此，接口执行的时候调用jmeter插件，jmeter设置的jsonpath断言返回结果也无大于、等于等条件，mstersphere为了良好的用户体验，支持用户在设置断言的时候可以设置条件，但是响应结果-断言-内容列并未展示具体条件。如果觉得这个展示很重要，可以后续沟通我们工作人员，再反馈给产品沟通是否后续版本优化。
