### ISSUE TITLE
响应的Json格式，却提示不是[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1144]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/104014764-8deb3380-51ee-11eb-8cb8-248ba561955f.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
