### ISSUE TITLE
[BUG] 接口自动化测试定时任务配置邮件通知，收到的链接有误

### ISSUE THREAD

**Issue by renren2022** [metersphere/metersphere#11444]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？  --v1.18.0

**Bug 描述**

简要描述您碰到的问题

接口自动化测试定时任务配置邮件通知，收到的链接有误，点击链接跳转到页面后，提示报告已删除
（原因：每次定时任务触发收到邮件通知中的链接一直不变）

**Bug 重现步骤**

1.  进入接口自动化测试，配置定时任务
2.  配置任务通知（邮件）
3.  等待定时任务执行，触发发送邮件
4.  点击邮件中报告链接地址

**期待的正确结果**

正确情况下应该是什么样的？  --跳转到正确报告的页面

**截图**

![image](https://user-images.githubusercontent.com/100106457/158329981-55bf04e3-1b61-43fc-963d-c77d559f8c0a.png)

**Comment by ltfit** [comment]
感谢反馈。下个版本修复

**Comment by ltfit** [comment]
您好 v1.18.3版本已修复
