### ISSUE TITLE
[BUG]性能测试设置并发数 10000，点击保存执行，自动重置到 5000

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11455]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   性能测试设置的并发数为 10000
2.  资源池中俩个节点设置的并发各为 10000
3.  配额设置无限
4. 点击保存并执行，查看报告中的压力配置并发数改成了 5000

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好，两个节点按照最大并发数的比例来分配10000 ，1:1 就是每个5000

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by ltfit** [comment]
新版本已修复
