### ISSUE TITLE
[BUG]信息测试时，系统弹出错误提示，但是提示信息中提供的参考文档地址有问题。地址最后的#url是什么

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11472]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG]信息测试时，系统弹出错误提示，但是提示信息中提供的参考文档地址有问题。地址最后的#url是什么
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/158364378-8b65194c-3562-47f9-9711-428070476937.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
https://metersphere.io/docs/faq/load_test/#url
可以打开看下，是具体当前站点的url配置说明的链接
