### ISSUE TITLE
[BUG]测试计划中翻页数据不更新

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11486]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.创建一个测试计划
2.往测试计划中添加功能用例
3.存在足够多数据，点击翻页，发现数据不更新

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好 此问题在v1.18.2 修复了
