### ISSUE TITLE
[BUG]通过前后置脚本设置环境变量在性能测试中不生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11487]
**MeterSphere 版本**

1.10.11-lts
在场景A中通过后置脚本设置环境变量，在场景B中引用
将A B场景引用为性能测试，顺序执行A B，结果A B都没有引用到设置的环境变量
![image](https://user-images.githubusercontent.com/88763608/158504271-d6b33a4c-50da-4b23-83a3-42c61725ebda.png)
![image](https://user-images.githubusercontent.com/88763608/158504296-57acced7-ce38-4bfd-abef-e74ac8b72885.png)
![image](https://user-images.githubusercontent.com/88763608/158504354-eb9e06c3-dda3-42ea-8006-e87d16ece301.png)

**Comment by zrfit** [comment]
你好，未复现该问题，能否把场景导出我们尝试复现。
