### ISSUE TITLE
[BUG]TCP接口测试中在请求体前手动添加报文长度，选择TCPCLIENTIMPL可以执行成功，转成性能测试结果没有数据

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11485]
**MeterSphere 版本**

1.18.1
TCP接口测试中在请求体前手动添加报文长度，选择TCPCLIENTIMPL可以执行成功
![报文](https://user-images.githubusercontent.com/88763608/158498894-51f7258e-676e-4306-88fc-7dd2370eb99e.jpg)
![成功](https://user-images.githubusercontent.com/88763608/158498901-f21161d1-3807-4cd7-9632-5c5fd1ce56aa.jpg)
转成性能测试结果没有数据
![性能报错](https://user-images.githubusercontent.com/88763608/158498922-d8085562-0556-4cef-87aa-679ded4cbd72.jpg)

**Comment by zrfit** [comment]
您好，我们本地最新版本未复现该问题，能否导出接口数据我们尝试复现或者升级到最新版本尝试。

**Comment by zyyfit** [comment]
1.20.4已修复
