### ISSUE TITLE
[FEATURE]提需求缺陷时，增加上传图片功能到jira的issus里

### ISSUE THREAD

**Issue by fan01xiao** [metersphere/metersphere#1149]
**请描述您的需求或者改进建议.**
在提缺陷的描述框内可以直接拖拉图片或者附件，这些附件可上传至关联的jira里。因为大多数问题都会配上截图，没有截图提的bug仍需线下沟通，效率受阻。
![image](https://user-images.githubusercontent.com/76150609/104143681-72a14380-53fb-11eb-9a3a-8f369d0d2488.png)

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
#1279 问题相同
