### ISSUE TITLE
[FEATURE]场景用例导入进行压测时不支持设置前置脚本仅执行一次

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11497]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
场景用例导入进行压测时不支持设置前置脚本仅执行一次，导致需要登录状态的接口反复先调用前置登录接口在测试后续接口的情况，即在jmeter中的仅一次控制器

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
