### ISSUE TITLE
[BUG]文档结构断言在jmeter压测中无法正确断言

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11493]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.2

**Bug 描述**

文档结构断言在jmeter压测中无法正确断言
在自动化用例中可以正常断言

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/20190050/158510972-4d914878-bbaf-4352-b57a-e924ca8c839c.png)

![image](https://user-images.githubusercontent.com/20190050/158511148-68135ced-8303-45bc-adc3-db7fcc826cf5.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
