### ISSUE TITLE
[FEATURE]某个接口中提取的变量可作为全局变量使用

### ISSUE THREAD

**Issue by xinglei1** [metersphere/metersphere#115]
**请描述您的需求或者改进建议.**

大部分接口需要登陆后才能访问，所有的接口在请求头中添加同一个变量操作繁琐。
**请描述你建议的实现方案**
建议直接在环境变量中定义，然后登陆接口完成后进行提取赋值

**Comment by luty2018** [comment]
1.1 版本已支持环境配置和全局变量，请更新体验
