### ISSUE TITLE
[FEATURE] 测试用例执行时 通过/失败等按钮可以悬浮在界面上

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#11509]
这几个button如果能悬浮在界面就好了，现在当用例稍微长一点滚到底部执行完用例后，还需要在滚到顶部点击 通过
![image](https://user-images.githubusercontent.com/67257251/158544658-0ee66998-0bf1-49bc-b73a-997bb664daf5.png)

**Comment by Hyyfit** [comment]
已规划，待排期。
