### ISSUE TITLE
[BUG] har 格式接口导入，请求体参数 的类型不对，应该是 x-www-form-urlencoded ，实际导入后变成了 form-data

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11508]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/30038088/158541089-99214f73-f019-459c-b686-f34b0c568f39.png">

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/167081268-7b3b2ab2-eaf7-4720-a3b7-21c8e0c23bfc.png)
Har中的content type 就是form-data类型的
