### ISSUE TITLE
[BUG]接口 case执行完，接口列表显示还在执行中

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11534]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   在接口测试模块编辑一个接口定义，不要关闭 tab 页
2. 然后点击模块随便选中一个接口点击接口case列表，在列表中点击 case 的执行按钮
3. 点击编辑可以看到用例已经执行完，但是列表中用例状态测试中
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/36387811/158577737-0e54a9d9-bbab-443a-9730-e2a5b5b08b87.png">

**Comment by zrfit** [comment]
您好，未复现该问题，能否导出该case我们尝试复现。
