### ISSUE TITLE
[BUG]在接口自动化里中的场景不会同步我在接口定义里的接口修改

### ISSUE THREAD

**Issue by JackieLi001** [metersphere/metersphere#1153]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是：
v1.6.1-b6

**Bug 描述**
简要描述您碰到的问题
在接口自动化里中的场景不会同步我在接口定义里的接口修改；

**Bug 重现步骤**
1. 接口自动化添加场景，场景导入接口定义里的接口；
2. 对接口定义里的接口做一定修改；
3. 接口自动化里场景中接口信息没有更新；

**期待的正确结果**
在接口自动化里中的场景会同步我在接口定义里的接口修改；

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前在场景中添加接口定义是复制的方式添加的，如果添加的是接口用例可以使用引用的方式，接口用例有修改在场景中的引用会对应修改。
对于接口定义修改后是否自动修改接口用例和场景中添加的请求，我们后续会进一步完善这里的处理策略。
