### ISSUE TITLE
[BUG]接口用例执行人不是实际执行人

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11535]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

 1.在接口 case 列表点击执行按钮
2.执行完后右上角弹窗用例执行成功，但是不是当前执行人
3.消息设置是默认的没有修改

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，未复现该问题，能提供详细的信息吗？比如消息配置的接收人，还有case的创建人，和执行的站内通知截图，便于我们去尝试复现。

**Comment by happyend1709** [comment]
> 您好，未复现该问题，能提供详细的信息吗？比如消息配置的接收人，还有case的创建人，和执行的站内通知截图，便于我们去尝试复现。

消息设置是默认设置，create_user_id 和 update_user_id都是当前登录用户，查看任务中心执行记录也是正确的
![image](https://user-images.githubusercontent.com/36387811/159606658-2ca38327-bd68-4eec-975c-893af166e0c5.png)

**Comment by zrfit** [comment]
v1.20.4lts已修复该问题。
