### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by icegreen77** [metersphere/metersphere#1155]
**请描述您的问题.**
我的性能测试脚本有两个场景：
1、一个线程组下面有多个接口
2、多个线程组

结果：
1、场景一 报Non HTTP response code: java.net.SocketTimeoutException
2、场景二 报QueueWaits: 7260; QueueWaitTime: 9792880887300 (nanoseconds), you may need to increase queue capacity, see property 'backend_queue_capacity'

资源池设置的最大并发数是1000，场景一并发数设置的1000，场景二并发数设置的每个线程组200

**Comment by youliyuan-fit2cloud** [comment]
您好，该问题没有复现，请提供详细的log信息或检查您的脚本信息
