### ISSUE TITLE
[BUG]变量不合法，保存后恢复初始值

### ISSUE THREAD

**Issue by bxh111** [metersphere/metersphere#1156]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  修改随机变量，未加引号
2. 点击保存调试
3. 未保存成功，恢复初始值

**期待的正确结果**
随机变量不需要加引号，正常保存

**截图**
"xxx": ${__Random(0,60,)}  保存无效,恢复初始值
"XXX": "${__Random(0,60,)}"  正常保存

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
