### ISSUE TITLE
[BUG]后置脚本批量执行SQL, 报错 

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#11564]
**MeterSphere 版本**
 MeterSphere 版本是v1.18.1

**Bug 描述**

接口自动化， 前后置SQL，批量执行多条SQL， 报错

**Bug 重现步骤**

1.  配置数据源，配置allowMultiQueries=true
![1647496803(1)](https://user-images.githubusercontent.com/30264974/158746598-b3fdce19-1762-4429-9774-3365b051ca15.jpg)

2. 接口自动化中， 添加后置SQL, 执行多条SQL
![1647496893(1)](https://user-images.githubusercontent.com/30264974/158746764-0c990edd-0323-473e-902a-ce1dda62646d.jpg)

3. 调试生成报告， 出现以下报错
2022-03-17 14:03:24 WARN 9fcc08a9 1-1 SQL Problem in VV: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delete from user where id = 'XXX'' at line 2
![1647497068(1)](https://user-images.githubusercontent.com/30264974/158747085-e0381011-b116-4571-9131-82b366602163.jpg)

**截图**

如果有截图，请附上截图.

**Comment by fitcloud-zaopengguo** [comment]
如无法重现，内部联系郭灶鹏

**Comment by youliyuan-fit2cloud** [comment]
检查下mysql版本和你这个sql语句是不是一致
