### ISSUE TITLE
[BUG]导出API为json文件后再导入时仅导入目录结构树（未导入目录下API）

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#11574]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是：1.18.2

**Bug 描述**

导出API为json文件后再导入时仅导入目录结构树（未导入API）

**Bug 重现步骤**

1.  选择API导出json文件；
2. 再选择导入json文件则仅导入目录结构树未导入目录下对应API。

**期待的正确结果**

导出API为json文件后再导入时应导入目录结构树（包含导入API）

**截图**

![image](https://user-images.githubusercontent.com/46745316/158753732-00b71810-0ce8-41de-90b4-edeb03c1a2cc.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，导出后是导入同一个项目里面吗？如果是这样是只是覆盖原来的接口
