### ISSUE TITLE
[BUG]创建新项目编辑-描述输入框无法换行

### ISSUE THREAD

**Issue by GuoTy-Bro** [metersphere/metersphere#1158]
**MeterSphere 版本**
版本: v1.6.0-fbda7b42

**Bug 描述**
创建新项目编辑-描述输入框无法换行
**Bug 重现步骤**
1.  创建项目，点击编辑
2. 描述输入框中，点击ctrl+enter
3. 弹窗消失，提示成功 
4. 无法完成换行输入操作

**期待的正确结果**
正常换行输入

**截图**
![image](https://user-images.githubusercontent.com/67869369/104294664-6f40b180-54fa-11eb-8150-fff83e0a9f13.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
