### ISSUE TITLE
[BUG]导入第三方库无法找不到模块

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11596]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  python2.7，pip20.1 安装 requests1.27 成功
2. 在 Metersphere 的前置脚本中找不到模块

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="677" alt="图片4" src="https://user-images.githubusercontent.com/36387811/158921874-bea8d962-dd3a-4490-90e4-1b63113f9a75.png">
<img width="697" alt="图片5" src="https://user-images.githubusercontent.com/36387811/158921888-ea24fde4-0d84-4210-b835-200b1ccff0a3.png">
<img width="666" alt="图片6" src="https://user-images.githubusercontent.com/36387811/158921902-6b2a26fa-a775-44ec-900c-dcc61fe8a540.png">

**Comment by youliyuan-fit2cloud** [comment]
这种问题，我们也不太好处理~
