### ISSUE TITLE
[BUG]1.18.2 mock服务选择相应为xml格式时，version="1.0" encoding="UTF-8"无法修改或删除。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#11597]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.2

**Bug 描述**接口测试-API-MOCK设置-mock响应内容选择为xml格式时，version="1.0" encoding="UTF-8"无法修改或删除。

简要描述您碰到的问题

**Bug 重现步骤**

1.  登录MS平台。
2.  接口测试。
3. 接口定义。
4. 选择某个API接口。
5. 选择mock
6. 新增
7. 设置响应内容。
8. 设置为XML格式。
9. version="1.0" encoding="UTF-8" 是输入框。
10. 以上内容无法修改删除并保存。
11. 
12. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
v1.19版本已修复该问题。

**Comment by billguo** [comment]
版本：1.9.0
XML的响应内容，仍然无法删除呀。
![XML响应内容无法删除呀](https://user-images.githubusercontent.com/14307013/160070047-973d6e0e-2edb-4d38-b8fc-bd08ca306f2c.png)
