### ISSUE TITLE
[BUG]新的工作空间， 没有项目，点击项目设置， 弹出框的提示优化

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#11603]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是1.18

**Bug 描述**

新增一个工作空间，然后切换过去，再点击导航栏[项目设置] ，就会出现这个报错

**期待的正确结果**

希望修改这个弹出框的提醒， 提醒新建项目。 不然使用者以为是系统出问题了
<img width="960" alt="09a8e067af22d57742744212fcbe6df" src="https://user-images.githubusercontent.com/30264974/158929150-7f8e93ff-a7b4-4ea8-92af-26a78c506f9e.png">

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
1.19版本修复
