### ISSUE TITLE
[BUG]Jmeter测试计划里的自定义变量导入ms失效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11608]
**MeterSphere 版本**

1.18.2

Jmeter测试计划里的自定义变量导入ms失效
![image](https://user-images.githubusercontent.com/88763608/158934522-b017c52f-ad6a-414a-a5dc-32410b7a0efe.png)
<img width="741" alt="446b4e4222553878e755c256e3513f7" src="https://user-images.githubusercontent.com/88763608/158934529-c2305bd8-dc07-41e1-b189-ec33c8025424.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，没复现，Jmeter里面调试没问题吗？

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
