### ISSUE TITLE
[BUG]页面偶现报错,cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11601]
1.18.1

![6ea47a5a513f5ae3e77705f9b6fcc14](https://user-images.githubusercontent.com/88763608/158925567-34221398-d7b0-4601-8b16-826a7665df8e.png)

这个是客户问题，希望检查下，有无方法避免

**Comment by ltfit** [comment]
感谢反馈 后续版本修复
