### ISSUE TITLE
[BUG] 接口责任人无故被重置

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#11604]
**MeterSphere 版本**

1.18.1

**Bug 描述**

手动从swagger导入覆盖接口列表后，接口责任人被重置成导入人（如Administrator）。
定时任务从swagger导入覆盖接口列表后，接口责任人被重置成定时任务创建人（如Administrator）。

**Bug 重现步骤**

1.  同上

**期待的正确结果**

接口责任人不应该被重置，如有变化，可以事后批量设置。

**截图**

略

**Comment by zrfit** [comment]
v1.19版本已修复该问题。

**Comment by genezx** [comment]
感谢修复，v1.19.0问题已解决。
