### ISSUE TITLE
接口测试支持用例跳过或者失败重跑吗

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1161]
**请描述您的问题.**

**Comment by wangzhen-fit2cloud** [comment]
请详细描述下你的场景。
目前支持条件判断控制和循环控制，可以在满足特定条件时才执行某些请求，或者重复某个请求直到成功，不知道你想要的是不是这样的功能。

**Comment by youliyuan-fit2cloud** [comment]
@Grant2108 您好，问题长时间未收到您反馈，我们将关闭该issue，如果有问题请您联系我们～
