### ISSUE TITLE
[BUG]首次进入页面，或者页面刷新后，编辑项目时，不能选择缺陷模板

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#11612]
**MeterSphere 版本**

v 1.18.2

**Bug 描述**

首次进入页面，或者页面刷新后，编辑项目时，不能选择缺陷模板

**Bug 重现步骤**

1.  系统设置-工作空间-项目管理-编辑项目
2. 缺陷模板没有可以选择的内容，已经创建了缺陷模板
3. 
4. 

**期待的正确结果**

有默认的模板和已创建的模板可以选择

**截图**

![image](https://user-images.githubusercontent.com/89773363/158947914-4cb93caf-0a2f-4bc7-9a32-392eae5b93e4.png)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/158973751-52148928-9504-4b00-9af4-ea5f635093e3.png)

你们没有开启第三方缺陷平台的权限吗？需要先选第三方平台
