### ISSUE TITLE
[BUG]测试计划执行后，导出报告看不到关联的缺陷内容

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#11615]
**MeterSphere 版本**

v1.18.0

**Bug 描述**

测试计划执行后，导出报告看不到关联的缺陷内容

**Bug 重现步骤**

1.  执行测试计划，查看报告
2. 点击导出，导出html报告
3. 打开导出的报告，看不到关联的缺陷内容
4. 

**期待的正确结果**

导出的报告也能看到关联的缺陷内容

**截图**
在线可以看到缺陷内容
![image](https://user-images.githubusercontent.com/89773363/158950660-6d3448d0-c918-4e0c-9d71-0cbaa5617d76.png)

打开导出的报告，看不到缺陷内容
![image](https://user-images.githubusercontent.com/89773363/158950756-070adecb-0d14-4465-97de-afcc146a33e5.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续版本修复该问题
