### ISSUE TITLE
[BUG]性能测试 CSV 文件执行重复

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11627]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.一共两个节点，开启 CSV 分割
2.执行性能测试后查看日志发现有一个数据被执行两次

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="864" alt="image" src="https://user-images.githubusercontent.com/36387811/158966140-7c6f84ed-434b-4a46-bf4f-38b993b27352.png">

**Comment by youliyuan-fit2cloud** [comment]
副老师说改过了。。等着个版本吧

**Comment by zyyfit** [comment]
1.19.1已修复
