### ISSUE TITLE
[FEATURE] 用例执行界面，操作步骤跟预期结果展示的太紧凑，使用上并不方便

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#11621]
**请描述您的需求或者改进建议.**
执行测试用例的界面，操作步骤跟预期结果展示的太紧凑，使用上并不方便，遇到步骤长或者预期结果较多的时候，还需要手动放大显示框
![image](https://user-images.githubusercontent.com/67257251/158954165-45022822-7cd9-4261-bb83-333376e73528.png)

**请描述你建议的实现方案**
用例执行页面整体空间浪费太多了，很多不常用的功能占用太多空间，导致核心用例展示的较为紧凑。希望能够调整一下空间布局，把空间留给核心功能。

**Comment by Hyyfit** [comment]
已规划，待排期。

**Comment by libb-test123** [comment]
@Hyyfit  请问这个需求大概哪个版本会上？或者大致时间？
