### ISSUE TITLE
[BUG]jmeter接口导入到 Metersphere 请求体格式改变

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11626]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.在 jmeter中创建post接口，输入请求参数导出
2.在 Metersphere 创建同样的接口
3.在 Metersphere 导入 jmx 接口 
4.导入的 jmx 接口会变成 Metersphere 接口的用例
5.查看请求体的格式为x-www-formurlencoded

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
按步骤操作未复现，经沟通是jmeter忘记添加请求头导致，非缺陷。
