### ISSUE TITLE
[BUG] 测试计划-功能测试用例-高级搜索 输入参数点击搜索报错 e is not function

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#11620]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17.1
**Bug 描述**

报错 e is not function

**Bug 重现步骤**

测试计划-功能测试用例-高级搜索 输入参数点击搜索报错 e is not function

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/67257251/158952512-f7536e55-e705-4df6-bced-887056cfdf28.png)
![image](https://user-images.githubusercontent.com/67257251/158952558-b8031d3b-e4d4-4033-93cd-75d92928de94.png)

**Comment by libb-test123** [comment]
浏览器版本： 94.0.4606.81

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复这个问题

**Comment by ltfit** [comment]
您好升级到最新版本 已修复此问题
