### ISSUE TITLE
[FEATURE]希望JSR223PreProcessor支持JavaScript

### ISSUE THREAD

**Issue by kira5271** [metersphere/metersphere#1163]
**请描述您的需求或者改进建议.**
登录接口需要前端先进行rsa非对称加密，希望MeterSphere能支持JavaScript脚本，这样就不用重写加密接口了

**请描述你建议的实现方案**

**Comment by greedygod** [comment]
+1 js我还用到一个比较老旧的转码问题，\u00f3这种unicode风格的urlencode

别的语言都得单独写算法转换，js有个现成的escape/unescape可以转换
