### ISSUE TITLE
[BUG] 测试跟踪的报告列表中，能够编辑但是不能保存

### ISSUE THREAD

**Issue by leoyip** [metersphere/metersphere#11636]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.18.0-7662880d

**Bug 描述**

测试跟踪的报告列表中，能够编辑但是不能保存。

**Bug 重现步骤**

1.  进入"测试跟踪—报告"，选择某一报告，查看测试报告。
2. 在报告总结处，点击编辑。
3. 输入编辑内容

**期待的正确结果**

正确情况下应该填完内容可以保存。实际上没有保存按钮。

**截图**

![image](https://user-images.githubusercontent.com/16930670/158974411-fef185d6-3897-4468-bd62-135b58800e4b.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
已知问题，后续版本会优化这里
