### ISSUE TITLE
[BUG]测试计划里的 场景 读取 csv , 报告里的步骤 读取的顺序不对（不必现）

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#11630]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.18
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
1.
![image](https://user-images.githubusercontent.com/30038088/158965771-db896f35-606e-42ed-af1d-2e8fc72c5fb4.png)
2.实际第一步 读取的csv 第3行
![image](https://user-images.githubusercontent.com/30038088/158966490-600229f1-c706-4582-9020-e3c8464f2e36.png)
3.实际第四步 读取的csv 第2行
![image](https://user-images.githubusercontent.com/30038088/158971722-d599dec0-1207-4bb3-be30-04c6a3c7cfb1.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
暂时没有复现，有空了再尝试复现哈

**Comment by shenkaibo** [comment]
这个可以让开发 看一下代码逻辑，我这边 复现 概率 挺高的

**Comment by youliyuan-fit2cloud** [comment]
> 这个可以让开发 看一下代码逻辑，我这边 复现 概率 挺高的

已经提了。
