### ISSUE TITLE
[BUG]修改接口请求方法，点击保存，无法保存

### ISSUE THREAD

**Issue by peterzhanghao** [metersphere/metersphere#1164]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.6.2-e012d438
**Bug 描述**
简要描述您碰到的问题
新版中，请求方法是PUT，点击保存，提示错误，修改为POST才能正常保存
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
可以任意修改请求方法中的GET , PUT, POST, DELETE

**截图**

https://user-images.githubusercontent.com/61137241/104420400-c905b200-55b4-11eb-90de-5b0d7eacee16.mp4

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
