### ISSUE TITLE
[QUESTION]JMeter内置函数如何使用?

### ISSUE THREAD

**Issue by jixiang823** [metersphere/metersphere#11656]
JMeter内置函数如何使用? 
例如以下代码, 在JMeter能运行成功,但在ms似乎不行.
`String timestamp = "${__time(,)}";
vars.put("timestamp",timestamp);`
请求参数使用${timestamp}, 没有得到时间戳.
ms版本号1.18.3

**Comment by Hyyfit** [comment]
可以在前后置脚本中设置 
<img width="809" alt="image" src="https://user-images.githubusercontent.com/95834771/159197025-2f6fdf2a-7afd-42dc-a48e-39a98f7c87cb.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/95834771/159197047-0e656d54-12cc-4149-90ec-16e01d11f137.png">

**Comment by jixiang823** [comment]
本地搭建的开发环境, 函数没有生效, 不知道是什么原因.
<img width="1184" alt="111" src="https://user-images.githubusercontent.com/41544435/159340428-49a529f3-dc4c-48d9-a982-d6d68abbed9d.png">

**Comment by jixiang823** [comment]
`JMeterService.getJmeterHome()`获取的JMeterHome路径不对, 把路径改为`/opt/jmeter`后可正常使用内置函数.
<img width="1405" alt="path" src="https://user-images.githubusercontent.com/41544435/159436555-c2e3a73d-5e62-4567-9dff-c31d7050a25f.png">
