### ISSUE TITLE
[BUG]性能测试压力预估图和实际压力结果不一致

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11657]
1.8.3
两个场景，阶梯加压，分别分五次加压到5个用户，总共10个用户

实际上一致在5个用户和10个用户中交替

压力配置
![image](https://user-images.githubusercontent.com/88763608/159195598-d8e69793-0b66-4ee5-9f85-581bde7bb32a.png)
压力结果
![image](https://user-images.githubusercontent.com/88763608/159195617-decda351-a8f9-44d4-971f-44d206b7b2e4.png)

**Comment by ltfit** [comment]
感谢反馈 后续版本修复下

**Comment by ltfit** [comment]
实际运行图的粒度是随执行时长变化的，预热时间短的话可能在实际图表里只有一个点就能完成预热
