### ISSUE TITLE
[BUG]  场景变量CSV读取时出现EOF问题

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#11655]
**MeterSphere 版本**

v1.18.1

**Bug 描述**

在循环中读取CSV文件时，会随机出现EOF问题。可以参考下面两个链接的处理方法
https://stackoverflow.com/questions/35478261/jmeter-while-loop-does-not-detect-eof
https://www.blazemeter.com/blog/using-while-controller-jmeter

根据链接中的描述，需要在CSV配置中增加以下2个配置：
Recycle on EOF = False
Stop thread on EOF = True

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

可以看到JMeter中是带有这2个配置的：

![image](https://user-images.githubusercontent.com/24548477/159170572-f32a0da9-bb4e-4c30-9ed2-94bbe060d6ba.png)

建议MS中也增加这2个配置：
![image](https://user-images.githubusercontent.com/24548477/159170587-6b2b9337-2cb9-4cd1-8000-3cc3bd7a958d.png)

**Comment by fit2-zhao** [comment]
@xyziven  这个设置不太合理吧，如果Stop thread 其他请求就无法执行了。

**Comment by xyziven** [comment]
> @xyziven 这个设置不太合理吧，如果Stop thread 其他请求就无法执行了。

JMeter原生就有这两个参数，也有其道理。对于有些测试，可能就需要这么设置。

**Comment by zyyfit** [comment]
> > @xyziven 这个设置不太合理吧，如果Stop thread 其他请求就无法执行了。
> 
> JMeter原生就有这两个参数，也有其道理。对于有些测试，可能就需要这么设置。

目前不支持
