### ISSUE TITLE
[BUG]手动选择【接口测试】>>【创建接口】：手动创建接口完成后，点击保存，提示保存成功。但是左侧的接口统计没有改变。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11662]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  手动选择【接口测试】>>【创建接口】：手动创建接口完成后，点击保存，提示保存成功。但是左侧的接口统计没有改变。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/159199178-9af0b2a0-465f-4da5-85eb-cc03bdf84ccb.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
左侧-“更多操作” 下拉菜单的  “创建接口”  添加后没有更新左侧树，后续版本修复

**Comment by zyyfit** [comment]
1.19.1已修复
