### ISSUE TITLE
[BUG]定时任务报错

### ISSUE THREAD

**Issue by bxh111** [metersphere/metersphere#1167]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**

**Bug 重现步骤**
1.设置定时任务  

**期待的正确结果**
定时任务可以跨天  不会报错
![image](https://user-images.githubusercontent.com/77323173/104445176-c6668500-55d3-11eb-9446-1c949c4ea5e0.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，计划在 1.8 版本中解决该问题。

**Comment by xulinde** [comment]
已修复
