### ISSUE TITLE
[QUESTION]接口自动化如何在场景执行之前设置统一的前置处理

### ISSUE THREAD

**Issue by zhouanqi** [metersphere/metersphere#1168]
**请描述您的问题.**
需求：在执行接口自动化场景之前希望添加一个统一的前置处理，可以使用beanshell和Python的脚本，方便处理需要统一处理的数据。
目前这个功能没有找到，不知道是使用问题还是缺少该功能

**Comment by youliyuan-fit2cloud** [comment]
您好，目前我们支持场景内部的请求添加前后置脚本,包括beanshell，python，groovy,js,我理解您的需要是场景之前?目前还不支持

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/107188593-e21e4900-6a22-11eb-9b18-1aec4b630e8c.png)

您好！目前我们场景之间是可以添加的前后置脚本的，参考上图中的添加自定义脚本～！
