### ISSUE TITLE
[BUG]性能测试的JMX文件在jmeter更新后，再重新上传，页面刷新了，但是性能测试中的场景没有刷新

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11699]
1.18.3
首次上传的场景JMX，部分场景启用
![image](https://user-images.githubusercontent.com/88763608/159224859-0e45656e-46c6-48df-8c6f-efeb6220a281.png)
在jmeter更新后的场景JMX，改为索引场景都启用
![image](https://user-images.githubusercontent.com/88763608/159225045-3c4b7419-3d8e-4d29-a32e-404c15ce3a12.png)
重新上传
![image](https://user-images.githubusercontent.com/88763608/159225143-f9a53840-18cf-4fd9-b057-9bdce9dda546.png)
页面自动刷新后，场景状态还是跟原来一致，没有更新
![image](https://user-images.githubusercontent.com/88763608/159225230-d1771054-a6e2-43bc-8165-3a07b341f9a5.png)

**Comment by liuruibin** [comment]
如果在系统里改过配置，那么系统里的优先级更高一些

**Comment by linfengjjj** [comment]
刘工 这个是没有上传到接口自动化修改的，是创建性能测试，直接上传JMX文件出现的问题
