### ISSUE TITLE
[BUG]定时任务生成表达式页面，指定小时下拉框列表显示内容不正确

### ISSUE THREAD

**Issue by dugangandy** [metersphere/metersphere#1169]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.6.2-b4

**Bug 描述**
接口测试->接口自动化->编辑定时任务，生成表达式页面中指定小时的下拉框显示内容为0~59，应该是0~23

**Bug 重现步骤**
1.  依次点击：接口测试->接口自动化->定时任务
2. 点击【生成表达式】
3. 点击【小时】，选择【指定】下拉框

**期待的正确结果**
下拉框应该显示0~23

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/13115769/104541709-235a4d80-565d-11eb-976c-1e572f1a2e76.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
