### ISSUE TITLE
[FEATURE]站内信的规则与消息通知的规划冲突

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#11701]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.2

**!消息通知，设置了以站内信的方式给创建用例的创建人推送通知，但却因为创建人是自己而不能收到通知，这个规则与消息通知设置的规则矛盾**

简要描述您碰到的问题

**Bug 重现步骤**

1. 设置消息能知，新建用例给创建人发站内信
2. 创建用例
3. 收不到站内信通知
4. 

**期待的正确结果**

正确情况下应该是什么样的？
正确应该按通知规则执行，如果设置了通知创建人，那么自己创建了用例应该也会通知。

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。
