### ISSUE TITLE
[BUG]jmeter里设置的断言规则和数量导入到metersphere后不正确

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#11700]
1.18.3

这是jmeter里面的响应断言
![image](https://user-images.githubusercontent.com/88763608/159227516-dd0d6987-3a97-467e-aec0-3af655f3d9bf.png)
这是导入到metersphere后的响应断言，只剩一条了
![image](https://user-images.githubusercontent.com/88763608/159227619-17786f50-a1cf-4575-ba57-02e7650c4bbf.png)
[script1.zip](https://github.com/metersphere/metersphere/files/8315160/script1.zip)

> 复现脚本为啥不直接传上来？还是倒一手？

已经上传了，原谅我以为不能上传文件

**Comment by linfengjjj** [comment]
我有客户的复现脚本，需要可以找我

**Comment by youliyuan-fit2cloud** [comment]
复现脚本为啥不直接传上来？还是倒一手？

**Comment by linfengjjj** [comment]
已经上传了，原谅我以为不能上传文件

**Comment by youliyuan-fit2cloud** [comment]
收到，已复现，下个版本修复~

**Comment by zrfit** [comment]
v.1.19已修复该问题。
