### ISSUE TITLE
[BUG]GET请求QUERY和REST同时有参数时，query参数不生效,POST是生效的

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#11718]
**MeterSphere 版本**
V1.18.3

**Bug 描述**

简要描述您碰到的问题
GET请求QUERY和REST同时有参数时，query参数不生效,POST是生效的

**截图**

如果有截图，请附上截图.
GET请求：
![image](https://user-images.githubusercontent.com/32027713/159243159-e06961be-626b-4efb-b984-63c52058252a.png)

POST请求：
![image](https://user-images.githubusercontent.com/32027713/159243308-cda6cd51-fa73-49b9-8714-a94e0c71efa1.png)

**Comment by youliyuan-fit2cloud** [comment]
没复现呢，
![image](https://user-images.githubusercontent.com/54612864/159249749-ab8c3bd3-5862-4fdf-b53b-fcc486b53aaa.png)

**Comment by zyyfit** [comment]
get 请求，不是同时有 query 和 rest 时 query 不生效，是query 和 body 同时存在时，query 不生效，就是这样设计的
