### ISSUE TITLE
[BUG]测试计划关联 2 千条功能用例，打开测试计划页面崩溃

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11717]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   创建一个测试计划
2. 关联 2000 条功能用例
3. 打开创建的测试计划
4. 浏览器页面崩溃，内存占用持续飙升 内存为 8G，需要优化

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
v1.18.3还有这个问题？
