### ISSUE TITLE
[QUESTION]请求体为json时，无法mock数据

### ISSUE THREAD

**Issue by xiaoting09** [metersphere/metersphere#1172]
**请描述您的问题.**
版本 v1.6.2-e012d438
当我请求体为json时，传递json参数，如果使用如@date 等方式提交参数时，请求值还是为@date，无法生成模拟数据
请问有什么办法可以自动生成模拟数据
![微信截图_20210114161920](https://user-images.githubusercontent.com/15009828/104563730-fe79d080-5684-11eb-9c7e-99b6bf07cd6b.png)
![微信截图_20210114161955](https://user-images.githubusercontent.com/15009828/104563741-020d5780-5685-11eb-922e-17bd0a6dce62.png)

**Comment by youliyuan-fit2cloud** [comment]
您好，可以在请求参数的QUERY参数添加@date获取数据，也可以使用jmeter自带的函数获取数据~
![image](https://user-images.githubusercontent.com/54612864/107192411-88208200-6a28-11eb-8aa6-1bbbcfaa2651.png)

**Comment by youliyuan-fit2cloud** [comment]
1.
