### ISSUE TITLE
[QUESTION]项目环境中配置的全局断言选择应用场景

### ISSUE THREAD

**Issue by Ybump14** [metersphere/metersphere#11732]
**项目环境配置中，配置了全局断言，但是这个断言仅想用于接口场景中的HTTP接口，目前没有看到这一设置方法，不知道是有没有地方可以设置，或者是说后续是否考虑这样的功能**

场景需求：
在一个接口自动化场集中，可能集合了多个HTTP请求，且插入了自定义的SQL请求，这种情况下若环境配置中，配置了全局断言，会导致SQL请求的断言不通过报错

**Comment by Hyyfit** [comment]
目前的设计如此，后续会考虑优化。
