### ISSUE TITLE
[FEATURE]环境配置中的全局断言无法在实际接口自动化场景中被覆盖

### ISSUE THREAD

**Issue by Ybump14** [metersphere/metersphere#11733]
**假设特殊业务接口暴露的响应码等自定义字段的返回与标准的返回格式不一，但应用了同一个返回字段名称，此时在已有全局断言的情况下，在接口自动化场景中使用相同字段的断言，无法覆盖全局断言.**

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期
