### ISSUE TITLE
[BUG] 单接口用例转换为性能测试用例并进行压测时，http-domain环境信息未对应同步，导致压测报错HTTP无响应，请修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11742]
**MeterSphere 版本**

v1.18.3

**Bug 描述**

单接口用例转换为性能测试用例并进行压测时，http-domain环境信息未对应同步，导致压测报错HTTP无响应，请修复

**截图**
![d117f53a122fc78eb4f3f79fa6d3921](https://user-images.githubusercontent.com/92150453/159398977-32b4082d-3c9e-4eda-b6e9-ad66939f8801.png)
![image](https://user-images.githubusercontent.com/92150453/159398943-c756b1f6-4595-4f1d-8693-a07fa061c337.png)
![ec2d80a947b38468440a6767f2e445f](https://user-images.githubusercontent.com/92150453/159398998-37e17a92-2237-49bb-a202-68f908494b67.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现啊，接口case转性能测试？环境选成功了是吗？

**Comment by sageonedream** [comment]
选成功的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月22日(周二) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG] 单接口用例转换为性能测试用例并进行压测时，http-domain环境信息未对应同步，导致压测报错HTTP无响应，请修复 (Issue #11742)




 
你好，没有复现啊，接口case转性能测试？环境选成功了是吗？

**Comment by youliyuan-fit2cloud** [comment]
你这个接口上传上来，我们研究一下？

**Comment by sageonedream** [comment]
经确认，之前选择的环境中没有配置url信息，非问题
