### ISSUE TITLE
[FEATURE]压测存在报错时，无法查看详细的入参报文，还需要通过下载执行文件，在Jmeter上执行去进一步排查，建议能在MS性能测试的日志中查看到请求体的入参信息

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11744]
**MeterSphere 版本**

v1.18.3

**Bug 描述**

压测存在报错时，无法查看详细的入参报文，还需要通过下载执行文件，在Jmeter上执行去进一步排查，建议能在MS性能测试的日志中查看到请求体的入参信息

**截图**
![image](https://user-images.githubusercontent.com/92150453/159401096-19254ece-71f2-49f0-9231-085f215010c6.png)

**Comment by zhangzhaox** [comment]
全部打印请求入参影响性能，可以通过响应断言或beanshell断言输出断言失败事务请求 入参 或响应的关键信息日志打印

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
