### ISSUE TITLE
消息设置，同样设置情况下，测试报告消息通知能成功，接口自动化执行消息通知失败，飞书和站内通知方式都是如此

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#11746]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
[1。18.2](url)
**Bug 描述**

简要描述您碰到的问题
消息设置，同样设置情况下，测试报告消息通知能成功，接口自动化执行消息通知失败，飞书和站内通知方式都是如此
**Bug 重现步骤**

1.  消息设置，同样设置情况下，测试报告消息通知能成功，接口自动化执行消息通知失败，飞书和站内通知方式都是如此
2. 
3. 
4. 

**期待的正确结果**
接口自动化执行消息通知应给可以成功
正确情况下应该是什么样的？
同样设置情况下，消息通知应该都可成功
**截图**
![1](https://user-images.githubusercontent.com/83771182/159403534-434d34ed-0685-447d-96cd-4bb6c616783c.png)
![2](https://user-images.githubusercontent.com/83771182/159403554-41355a38-0963-4f2f-b7ec-a63fb790de94.png)
如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本中已经修复

**Comment by ltfit** [comment]
1.19版本已修复
