### ISSUE TITLE
[BUG]接口自动化，状态码为401，无任何断言，自动化执行结果为失败

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#1174]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
![image](https://user-images.githubusercontent.com/17491657/104581874-245da000-569a-11eb-9f6a-781a8717cf83.png)

2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
