### ISSUE TITLE
[BUG]单接口用例转换为性能测试用例时，请求统计中的用例名称建议显示为原单接口用例名称，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11743]
**MeterSphere 版本**

v1.18.3

**Bug 描述**

单接口用例转换为性能测试用例时，请求统计中的用例名称建议显示为原单接口用例名称，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/159399388-09e6a2d9-9222-4e07-9957-93650e93f09a.png)
![image](https://user-images.githubusercontent.com/92150453/159399544-f6e45b06-4fc7-46ff-9e98-3ce781b62ea1.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢，后续版本优化一下

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
