### ISSUE TITLE
[FEATURE]用例标题的UI设计，同字号不好区分、颜色比普通文本浅、行距也没有拉开，评论输入框显示区域模糊用户很难找到位置

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#11745]
1.建议优化一下用例标题的UI设计，同字号不好区分、颜色比普通文本浅、行距也没有拉开，用户评审用例时还是比较关注标题的，建议居中一些
2.输入框建议拉高，且增加类似“请输入...”字样的placeholder

**Comment by Hyyfit** [comment]
感谢反馈，后续我们会对平台UI设计及、交互进行优化。
