### ISSUE TITLE
[BUG] 测试计划中执行自动化场景接口测试用例，部分用例执行超时，且步骤数量显示错误

### ISSUE THREAD

**Issue by GavinGu123456** [metersphere/metersphere#11758]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.3

**Bug 描述**

简要描述您碰到的问题
测试计划中执行自动化场景接口测试用例，有很多测试用例超时，且用例执行步骤显示错误

**Bug 重现步骤**

1.  进入测试跟踪->测试计划
2. 关联接口自动化场景测试用例
3. 执行测试计划
4. 观察测试计划测试报告

**期待的正确结果**

正确情况下应该是什么样的？
用例执行成功或失败，不会显示超时；测试报告中执行步骤显示正确

**截图**

如果有截图，请附上截图.
![20220322132437](https://user-images.githubusercontent.com/102133964/159413818-434bfacf-1a9f-4e2c-b194-753a1c65e95b.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复

**Comment by GavinGu123456** [comment]
> 左侧这个步骤数是这场景中的步骤数量包括禁用状态的，还有单个步骤中可能是一个场景，这个场景中包含多个子请求， 然后 右侧这个请求数是 包括所有子请求的统计 当然还是有点问题，右侧 21 17 4 这个统计应该有问题，我们后续版本修复

超时的问题比较严重，这个是什么原因导致的吗

**Comment by youliyuan-fit2cloud** [comment]
场景报告出现大量Timeout 状态 ,检查执行队列是否有排队情况；如果有可以修改 “系统设置-系统参数设置-并发数” 改成系统能并发的最佳数量（并发数对应= 场景/用例 执行数量；所以场景多的 并发数设置小一些，用例执行多的 并发数可相对设置大一些）

**Comment by youliyuan-fit2cloud** [comment]
https://kb.fit2cloud.com/archives/46
