### ISSUE TITLE
[FEATURE]用例管理，批量操作中，增加批量增加标签的功能

### ISSUE THREAD

**Issue by richard-sysout** [metersphere/metersphere#11761]
**请描述您的需求或者改进建议.**
常规的测试用例添加，后期可能会有对某些之前已添加的测试用例进行标签的批量添加的需求
有了批量添加的标签之后，可以对这部分标签进行筛选，进一步操作这部分标签对应的用例
可以考虑设计在【批量操作】中

**请描述你建议的实现方案**
1.利用当前存在的多选功能，可以选择自己需要操作的一批用例
2.在【批量操作】中，可以在【批量编辑】中选择【更新x个用例的属性】增加【添加标签】的选项
3.【属性值】输入对应的标签值
4.完成对已选中该部分用例的标签的添加

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
