### ISSUE TITLE
[BUG]域控中用户OU信息中mail为空时，无法通过LDAP创建账号

### ISSUE THREAD

**Issue by greedygod** [metersphere/metersphere#1177]
**MeterSphere 版本**
1.6.2

**Bug 描述**
公司域账户中存的用户信息不全，有的人没写邮箱地址。
而配置LDAP映射中要求三个必填项：用户名、姓名、邮箱
例如：` {"username":"sAMAccountName","name":"cn","email":"mail","phone":"phone"}`
对于信息完整的用户可以正常登录，但有人没留邮箱，则通过用户OU读取到邮箱为空值时会报错：
![image](https://user-images.githubusercontent.com/7498123/104678102-ab0b8f00-5725-11eb-80c9-05a6e34c468e.png)

**Bug 重现步骤**
域账户信息中，部分用户信息不全，例如未填写邮箱
配置导入ldap时，有邮箱信息的用户登录时会失败：

**期待的正确结果**
对LDAP映射仅检查username非空即可创建账号
允许解析name和mail为空值
——由于ms确实需要这两项信息非空，可在解析到null时做转换赋缺省值，例如姓名也取username、邮箱默认取username+"@localhost.localhost",这样用户登录后可以再自行修改）

**Comment by greedygod** [comment]
ps：客户运维方表示不会考虑对历史账号做矫正补充填全信息，只能咱们考虑提高LDAP健壮性了。
诸如gitlab等也支持ldap就没有这个问题。。。

**Comment by wangzhen-fit2cloud** [comment]
你好，已规划在 1月份的 1.17 版本解决该问题，请持续关注我们的更新日志。
