### ISSUE TITLE
[BUG]接口测试-首页，场景用例数量统计不正确

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1178]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.6.2-e012d438
**Bug 描述**
简要描述您碰到的问题

接口自动化中只有4个场景，首页场景用例数量统计-通过率中的数据统计不正确，通过率中显示（未执行1，未通过1，已通过5）

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/104694957-f1251a80-5746-11eb-8bfa-cd8db6788412.png)
![image](https://user-images.githubusercontent.com/54024064/104695021-0a2dcb80-5747-11eb-922f-c4511774ce48.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改。
