### ISSUE TITLE
[BUG]启动frontend模块 npm run serve 出现截图中的错误

### ISSUE THREAD

**Issue by leiqu** [metersphere/metersphere#1179]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
master
**Bug 描述**
简要描述您碰到的问题
启动frontend模块 npm run serve 出现截图中的错误
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，
![捕获](https://user-images.githubusercontent.com/8588677/104698039-aeb20c80-574b-11eb-8305-0f4ae7174d22.PNG)
请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请在 `frontend/src/business/components/` 目录下新建 `xpack` 子目录后再次运行。
