### ISSUE TITLE
[BUG]helm install metersphere metersphere/metersphere 安装后pod 状态pending

### ISSUE THREAD

**Issue by Moonmin** [metersphere/metersphere#11792]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

helm install metersphere metersphere/metersphere 安装后pod 状态pending
![image](https://user-images.githubusercontent.com/24285723/159440329-1e10c548-d55b-437a-8d55-f8da4f44b73a.png)

**Bug 重现步骤**

1.  helm install metersphere metersphere/metersphere 安装后
2. pod状态为pending
3.pod状态描述
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  88s (x308 over 5h11m)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

**Comment by wangzhen-fit2cloud** [comment]
你好，chart 当中默认使用了名称为 default 的 StorageClass 来创建 pvc (https://github.com/metersphere/helm-chart/blob/9c1b53eab18aecdd9c1854ffa1a5f30023c50d36/charts/metersphere/values.yaml#L15 )，该问题大概率为你的 k8s 环境中没有该 StorageClass 导致的。
可以通过 `kubectl get sc` 命令来查询可用的 StorageClass，如果 StorageClass 名称为 sc1，可以使用下面的命令在安装时指定该参数
```bash
helm install metersphere metersphere/metersphere --set common.storageClass=sc1
```
