### ISSUE TITLE
[BUG]运行环境的全局后置脚本设置所有请求后执行未生效，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#11795]
**MeterSphere 版本**

v1.18.3

**Bug 描述**

运行环境的全局后置脚本设置所有请求后执行未生效，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/159441875-c70540b0-f118-440d-9e88-604b908d96c9.png)
![f583342bbc78772f8a50d6fd78b31fe](https://user-images.githubusercontent.com/92150453/159442995-7b05318e-6f3f-4119-a0da-e1d3fe899cca.png)

**Comment by youliyuan-fit2cloud** [comment]
重新看了一下你这个是在调试的时候单个请求里面的控制台结果不会有所有的后置脚本结果，是在调试-生成报告里面 的控制台会看到所有前后置脚本

**Comment by sageonedream** [comment]
已确认，非问题
