### ISSUE TITLE
[BUG]接口请求内容首次进入时，缺少参数类型的焦点

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#118]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.3

**Bug 描述**
简要描述您碰到的问题
接口请求内容首次进入时，缺少参数类型的焦点

**Bug 重现步骤**
1.  首次进入没有焦点，点击后出现参数焦点
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
每次都有焦点

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/87266226-5299d180-c4f7-11ea-8b03-af23687716b8.png)

**Comment by wangzhen-fit2cloud** [comment]
已在新版本中修复
