### ISSUE TITLE
[FEATURE]增加jmeter中用的比较常用的一些功能，计数器、循环控制器等

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#1181]
**请描述您的需求或者改进建议.**
增加jmeter中用的比较常用的一些功能，计数器、循环控制器等

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，我们平台场景自动化那里已经增加了这两个功能，您可以升级到最新版本体验下
