### ISSUE TITLE
[BUG]测试跟踪-测试计划-报告统计当中的失败用例列表创建人是添加到测试计划当中的人不合理

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#11828]
**MeterSphere 版本**

1.18.2

**Bug 描述**

测试跟踪-测试计划-报告统计当中的失败用例列表创建人是添加到测试计划当中的人不合理

**Bug 重现步骤**

1.  测试跟踪-测试计划-报告统计
2. 当中的失败用例列表创建人是添加到测试计划当中的人不合理
3. 
4. 

**期待的正确结果**

建议方案：
保留当前的实现方式，新增一个责任人，理由：这是一个平台化的产品，添加到测试计划的可能是某一个人，但是这个接口不一定是他在维护。所以有责任人，基本是责任人在维护这个用例本身，所以加上责任人

**截图**

![image](https://user-images.githubusercontent.com/19423100/159615418-a83018ef-266d-4382-aee4-06397258cd9b.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.20.1-lts版本中已修复

**Comment by legend818** [comment]
我问一下这里的优化是优化什么了，新增了责任人 还是？？ 1.20.1没有看到效果

**Comment by youliyuan-fit2cloud** [comment]
创建人就是实际有用例的创建人
