### ISSUE TITLE
[BUG]性能测试脚本在jmeter里能正常执行，并且有相关测试数据。但是JMX脚本在导入到性能测试后，性能测试执行完毕没有任何数据

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11821]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG]性能测试脚本在jmeter里能正常执行，并且有相关测试数据。但是JMX脚本在导入到性能测试后，性能测试执行完毕没有任何数据
2.  日志里有错误信息。
3. 如果需要脚本和日志文件可以联系我（黄新娥）
4. 
5. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/78218624/159611614-90698660-fb85-4237-b90f-cdb5c7175774.png)

**Comment by zyyfit** [comment]
我看这个jxm里有csv文件，上传jmx文件后有没有上传csv文件？如果没上传的话请上传csv文件试试
