### ISSUE TITLE
[BUG]【大益】接口测试用例，执行或者调试时，一直在转，在列表看状态一直是测试中，都一个小时了，还是这样。并且后台日志有错误。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11831]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  【大益】接口测试用例，执行或者调试时，一直在转，在列表看状态一直是测试中，都一个小时了，还是这样。并且后台日志有错误。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/78218624/159620366-c34624e8-4070-41e1-9d0e-22e959bfe0fe.png)
![image](https://user-images.githubusercontent.com/78218624/159620403-b9fe242c-2601-4bad-b569-9eb85e07a2bb.png)
![image](https://user-images.githubusercontent.com/78218624/159620455-45ec2696-342d-4f76-a186-228813c8fa57.png)

**Comment by huangxine** [comment]
此接口是：你就创建一个接口用例，访问百度就行；https://www.baidu.com；然后点击执行；然后就一直执行了，无法停止

**Comment by zrfit** [comment]
您好，未复现该问题，能上传对应的接口case吗？我们去尝试复现。

**Comment by fit2cloud-yangxiaoyan** [comment]
问题已解决，客户使用了nginx
