### ISSUE TITLE
[BUG]用Jmeter写的接口测试用例里有beanshell写的脚本，在MS系统选择接口测试》接口定义》》导入：导入此Jmx文件，但是导入的接口测试用例没有把脚本导进来，接口用例的‘步骤’里是空的

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11849]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG]用Jmeter写的接口测试用例里有beanshell写的脚本，在MS系统选择接口测试》接口定义》》导入：导入此Jmx文件，但是导入的接口测试用例没有把脚本导进来，接口用例的‘步骤’里是空的
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/159640440-26a4efb9-808b-4756-88ff-a4a4d3d20ec4.png)
![image](https://user-images.githubusercontent.com/78218624/159640548-e0237221-f868-4734-8b7d-c8ab4c7a760c.png)
![image](https://user-images.githubusercontent.com/78218624/159640747-5dcca687-d8e9-4543-a479-726cda0f0a1e.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
我们系统里用的是 JSR233 脚本，你换这个导入试试
