### ISSUE TITLE
[BUG]接口管理，请求参数请求体json注释，保存不生效

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1185]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26756176/104703854-d5277600-5752-11eb-831a-4037b954f643.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
