### ISSUE TITLE
[QUESTION]运行安装脚本install.sh后，所有应用都是unhealthy

### ISSUE THREAD

**Issue by helloworld1314** [metersphere/metersphere#11860]
linux安装v1.18.3，使用默认安装脚本，执行install.sh脚本结果
<img width="978" alt="企业微信20220323-161329@2x" src="https://user-images.githubusercontent.com/13231644/159653340-cba7b668-c12a-45a8-b0dc-4d2fbfcbd2a7.png">

**Comment by zhangdahai112** [comment]
具体问题的看下，你的 cpu 内存资源是否足够哈
