### ISSUE TITLE
[BUG]api 和 case 列表偏移

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11871]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 18.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.创建场景，点击从接口列表导入，弹出 api 和 case 列表 多选框偏移
2.创建测试计划，关联用例，弹出 api 和 case 列表 多选框偏移

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/36387811/159671867-ab3636e1-0117-4fcc-8866-e4e4449a4639.png">
![图片7](https://user-images.githubusercontent.com/36387811/159672031-64b4433b-77cc-4474-8df1-aa1b64180190.png)

**Comment by ltfit** [comment]
最新版修复该问题
