### ISSUE TITLE
[BUG]v1.18.1数据库数据源切换环境没有跟着变化

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#11870]
**MeterSphere 版本** v1.18.1

**Bug 描述**

环境A复制成环境B，并修改环境B中的数据源，实际执行时选择了环境B，实际上使用的还是环境A中的数据源。
将复制来的数据源删除，重新创建，则没有此类问题

**Bug 重现步骤**
1、复制已有环境作为新的环境
![1](https://user-images.githubusercontent.com/101856439/159661256-a22d3e25-7416-4696-b016-8c12cff3a733.png)
2、把新环境中的老数据库连接URL直接修改为新的数据库连接URL，并且点击更新
![2](https://user-images.githubusercontent.com/101856439/159661555-5b78bacb-360e-4d8d-bb89-0060133be38c.png)
![3](https://user-images.githubusercontent.com/101856439/159661581-b14e191c-1514-4070-bd6f-e6014b184bd3.png)
3、选择新环境进行调试，查看SQL响应头
![4](https://user-images.githubusercontent.com/101856439/159661712-7750b24d-3110-406c-902b-40e948e206d3.png)
此时请求地址为老数据库URL
![5](https://user-images.githubusercontent.com/101856439/159662057-8ca2c4c6-bc9d-4eb4-8538-c24cce048bb8.png)
4、删除新环境中所有的数据库配置
![6](https://user-images.githubusercontent.com/101856439/159662804-ae08da85-6e6d-4398-a0dd-da1f63be5324.png)
5、添加新的数据库配置
![7](https://user-images.githubusercontent.com/101856439/159663187-9eeedb7f-2d0d-4213-8e66-04390af2c34f.png)
6、选择新环境进行调试，查看SQL响应头
此时请求地址为新数据库URL
![8](https://user-images.githubusercontent.com/101856439/159663351-1f7de5d5-1cda-4cfe-84ed-175fb3e28cfe.png)

**Comment by ltfit** [comment]
1.19.1 修复该问题  升级下
