### ISSUE TITLE
[BUG] （大益）测试用例列表页面，第一行中文，下面的英文

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11882]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试用例列表页面，第一行中文，下面的英文
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/159682265-3e48dc3b-7771-4721-b3ce-a9905af39f55.png)

如果有截图，请附上截图.

**Comment by ltfit** [comment]
你好 这边用例能否提供下 我这边看下你的模版

**Comment by ltfit** [comment]
您好 这个是模版导入进去的吗

**Comment by huangxine** [comment]
不是模板导入的

**Comment by ltfit** [comment]
有什么特殊的操作么

**Comment by fit2cloud-yangxiaoyan** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/72729206/160379543-62f883e4-1e27-41a0-9739-1bd8e93c0332.png">
已复现，见图片，所以编辑保存后都是name

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
v1.20.8-lts版本已优化此问题
