### ISSUE TITLE
[BUG]（大益）接口测试执行状态一直是运行，后台日志包异常。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11880]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个接口用例，访问百度就行。https://www.baidu.com
2. 然后点击执行。。
3. 然后页面一直在转圈就一直执行了，无法停止
4.  查看日志，发现有错误信息。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/159680465-497174f2-7b91-41dc-a872-fa5e5f120a37.png)
![image](https://user-images.githubusercontent.com/78218624/159680533-aacd0e24-5ce5-4a63-bc85-e38798312e0b.png)
![image](https://user-images.githubusercontent.com/78218624/159680784-d5b0ab3f-b83b-4f8d-9528-5d1a72d2bb15.png)

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，未复现该问题，是否有其它特殊配置或者操作？
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/159909756-c352328a-82fd-4e8e-b756-ab36356d57cd.png">

**Comment by fit2cloud-yangxiaoyan** [comment]
问题已解决，客户使用了nginx
