### ISSUE TITLE
[BUG]（dayi）性能测试执行一直在打转，查看后台一直在打印错误日志，ms服务器的cpu资源被耗完了，最后系统都登录不了了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#11881]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个接口访问百度的接口。
2. 一键转性能测试
3. 然后执行性能测试。
4. 一直是运行状态，所有页面都进不去了，最后系统都登录不了了。
5. 查看日志有错误信息。后台一直重试报错，一直打印日志
6. 并且查看资源，ms服务器的cpu资源被耗完了 发现性能测试已经把cup沾满了

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/159681449-d7afb3bc-2898-4f0f-94ed-eb4d841a2f30.png)
![image](https://user-images.githubusercontent.com/78218624/159681624-387c1acc-8955-4662-b28d-647ef755de8d.png)
![image](https://user-images.githubusercontent.com/78218624/159681733-97b54aed-b57a-4c3e-b3a4-0d3459fde56f.png)

如果有截图，请附上截图.

**Comment by ltfit** [comment]
您好 是不是有具体的配置 执行文件能否上传下 我这边复现下

**Comment by fit2cloud-yangxiaoyan** [comment]
问题已解决
