### ISSUE TITLE
[BUG]复制测试计划不会复制场景的运行环境

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#11890]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
18.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

 1.创建一个测试计划，添加一个场景，选择运行环境
2.在测试计划列表，复制创建的测试计划
3.打开复制的测试计划，查看到复制的测试计划的场景运行环境为空

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢 反馈 下个版本修复
