### ISSUE TITLE
[FEATURE] 系统信息、故障排除和技术支持工具

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#11894]
**请描述您的需求或者改进建议.**

很多时候，用户的问题其实是其自身环境的原因。我们希望，他向我们提交问题的时候，能够使用我们系统内置的【系统信息】及【故障排除】工具进行检测，以便于快速定位问题，及帮忙我们更快的解决问题。

**请描述你建议的实现方案**

我建议借鉴 Confluence Wiki 的实现，可以参考如下截图。

**1.  系统信息**

![image](https://user-images.githubusercontent.com/41712985/159823023-5d444457-8a70-4b95-856b-599a6afcff3b.png)

![image](https://user-images.githubusercontent.com/41712985/159823083-9184044c-ddee-4df6-ada8-e32d54c66cda.png)

**2. 故障排除工具**

![image](https://user-images.githubusercontent.com/41712985/159823183-c55f78e2-9d94-4b56-84ad-a6e647357460.png)

![image](https://user-images.githubusercontent.com/41712985/159823228-e76798b9-e105-4ba8-9fe8-4622ada09b2f.png)

**Comment by maninhill** [comment]
尤其是性能测试模块，因为是一个分布式的架构，涉及的节点很多，任何一个点出问题，都会导致问题。

**Comment by legend818** [comment]
@Hyyfit 这个主意不错

**Comment by Hyyfit** [comment]
感谢反馈，这个功能还需要我们技术人员调研，后续再进行规划。

**Comment by JohnNiang** [comment]
Hi @Hyyfit ，如果这个 issue 并没有被解决，建议保留 open 的状态。

/reopen
