### ISSUE TITLE
[BUG]接口测试-接口定义模块-接口另存为时SQL报错，主键重复

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1189]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述**
接口测试-接口定义模块-接口另存为时SQL报错，主键重复

**截图**
<img width="1338" alt="WX20210118-105558@2x" src="https://user-images.githubusercontent.com/21210217/104867995-2155fe80-597d-11eb-85ae-6d92bdccf083.png">

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
