### ISSUE TITLE
[BUG]MeterSphere 文档没有及时更新

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#119]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.3

**Bug 描述**
简要描述您碰到的问题
程序已经发布了1.0.3的版本，但是MeterSphere 文档没有及时更新

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/87267423-3b101800-c4fa-11ea-9e50-854fe96cd110.png)

**Comment by wangzhen-fit2cloud** [comment]
感谢提醒，文档已更新
