### ISSUE TITLE
[BUG]場景變量和自定義腳本變量重名時，變量未生效

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#11932]
**MeterSphere 版本**
   v1.18.3

**Bug 描述**
   場景A定義一個場景變量a="-"，且場景中新增自定義腳本及自定義請求，自定義腳本中會修改變量a的值等於null，自定義請求裡面會使用變量a，運行場景A時，取的是最新值null。若場景B引用場景A，運行場景B時，變量a取的不是最新腳本修改後的值，而是場景A中場景變量值

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
場景B引用場景A，運行場景B時，變量a應該取最新值null

**截图**

![image](https://user-images.githubusercontent.com/37204403/159865140-03e4b071-cdc0-4014-a6c1-6a9d7e5070a5.png)
![image](https://user-images.githubusercontent.com/37204403/159865259-8ffa4162-e2d8-4ef7-9f0d-35c27d873ef8.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
