### ISSUE TITLE
[BUG]接口自动化模块前置脚本插入自定义代码片段时，有时代码片段查询列表内容为空，关闭后再打开又有数据，偶发问题

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#11951]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口自动化模块前置脚本插入自定义代码片段时，有时代码片段查询列表内容为空，关闭后再打开又有数据，偶发问题
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
数据查询正常显示
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
自定义代码片段会根据当前步骤所选的语言进行过滤，比如前置脚本选了beanshell语言，插入代码片段的时候就会只显示beanshell的，请确认一下这里是不是因为被筛选了所以没显示？
