### ISSUE TITLE
[FEATURE] 随着公司组织架构调整，已存在的历史项目需要同步变更组织信息

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#11952]
需求：
随着公司组织架构调整，已存在的历史项目需要同步变更组织信息

期望：
可以变更历史项目的组织信息

**Comment by Hyyfit** [comment]
感谢建议，可以考虑增加变更组织信息的功能，已规划，待排期。

**Comment by Hyyfit** [comment]
您好，我们准备对这个需求进行排期。
这个需求的意思是：原工作空间下的项目，需要调整到新的工作空间吗？
麻烦您加一下我的企业微信，跟您确认一下需求。

**Comment by Hyyfit** [comment]
<img width="321" alt="image" src="https://user-images.githubusercontent.com/95834771/162893660-aa525337-0181-42a7-a2e6-e397980c0848.png">

**Comment by zhangzhaox** [comment]
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/95834771/162893660-aa525337-0181-42a7-a2e6-e397980c0848.png">

是的

**Comment by zhangzhaox** [comment]
> 您好，我们准备对这个需求进行排期。 这个需求的意思是：原工作空间下的项目，需要调整到新的工作空间吗？ 麻烦您加一下我的企业微信，跟您确认一下需求。

是的，非常感谢

**Comment by Hyyfit** [comment]
已规划，待排期。
