### ISSUE TITLE
[BUG]1.19.0 mock服务选择相应为xml格式时，version="1.0" encoding="UTF-8"无法删除。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#11969]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.9.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
1， 登录MS平台。
2， 接口测试。
3， 接口定义。
4， 选择某个API接口。
5， 选择mock
6， 新增
7， 设置响应内容。
8， 设置为XML格式。
version="1.0" encoding="UTF-8" 是输入框。
以上内容删除并保存。

**期待的正确结果**

正确情况下应该是什么样的？
![XML响应内容无法删除呀](https://user-images.githubusercontent.com/14307013/160072426-f9e4eea2-a229-46bd-a639-e984548d7180.png)

**截图**

如果有截图，请附上截图.

**Comment by billguo** [comment]
升级到1.19.1版本，还是无法删除呀。。。没有解决呀。

**Comment by billguo** [comment]
让然是无法删除。。。保存后，默认值就弹出来了。

**Comment by zyyfit** [comment]
> 让然是无法删除。。。保存后，默认值就弹出来了。

不好意思，理解错了，下个版本改这里，会改成默认带着 version 和 enconding 信息，可删除

**Comment by youliyuan-fit2cloud** [comment]
fixed on v1.19.2
