### ISSUE TITLE
[BUG]1.19.0 将mock服务的响应数据设置为jmeter（比如${__UUID}）服务，请求该mock服务后，响应内容直接显示为${__UUID}

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#11978]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.19.0
**Bug 描述**

简要描述您碰到的问题：将mock服务的响应数据设置为jmeter（比如${__UUID}）服务，请求该mock服务后，响应内容直接显示为${__UUID}

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zrfit** [comment]
您好，目前产品设计mock不支持jmeter内置函数，感谢反馈，如果有使用上的建议，可以提需求哈。
