### ISSUE TITLE
[BUG]用例评审的用例详情页，字段的描述太长时换行显示有问题

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#11998]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题：用例评审的用例详情页，字段的描述太长时换行显示有问题

**Bug 重现步骤**

1.  测试跟踪 - 用例评审 - 关联用例
2.  进入肜例详情页，用例的字段描述太长
3.  换行展示有问题
4. 

**期待的正确结果**

正确情况下应该是什么样的？正确应该有一个标准且美观的格式处理换行问题

**截图**
<img width="706" alt="企业微信截图_16482221953459" src="https://user-images.githubusercontent.com/77324661/160151840-7b202e12-8c23-482b-b632-cd82e378602c.png">

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，用例模板这块后续会优化一下
