### ISSUE TITLE
[BUG]接口定义查找自定义代码片段为空，这个现象偶尔出现

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#11996]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题：在接口定义的TEST标签下，使用前后置脚本插入自定义代码片断，偶尔会出现点击插件代码片断后，代码片断不显示的问题，这是偶尔出现，不是必现。

**Bug 重现步骤**

1.  接口定义 - 选择一个接口 - 进入 TEST标签下
2. 点击前后置脚本，选择插件自定义代码片断
3. 打开弹窗后，偶尔显示为空，未显示已有的代码片断
4. 

**期待的正确结果**

正确情况下应该是什么样的？应该正常显示已添加的自定义代码片断

**截图**
![image](https://user-images.githubusercontent.com/77324661/160148833-d75503c9-579d-404c-81a3-843460852923.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，没有切换项目吧？或者浏览器其他tab页切换了项目或工作空间，然后当前页面没更新？
