### ISSUE TITLE
[BUG]接口自动化场景里步骤多，且返回报文大时，一键展开和一键收起功能失效，页面会卡死

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#11999]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题：接口自动化场景里步骤多，且返回报文特别大时，一键展开和一键收起功能失效，页面会卡死；以及使用JSON SCHEMA模式时，也会非常慢

**Bug 重现步骤**

1.  接口测试模块 - 场景
2.  执行场景自动化，当返回报文特别大的时候
3.  使用场景一键展开和一键收起功能失效，页面会卡死
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本我们会优化性能的问题

**Comment by youliyuan-fit2cloud** [comment]
v1.20.0 中已优化，建议升级一下
