### ISSUE TITLE
[BUG]执行单接口用例时，执行结果经常提示“测试中”，页面卡顿，需要刷新才能恢复

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#11997]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3

**Bug 描述**

简要描述您碰到的问题：执行单接口用例时，执行结果经常提示“测试中”，页面卡顿，需要刷新才能恢复。可能跟返回报文内容太多有关系，需要优化性能。

**Bug 重现步骤**

1.  接口定义 - 执行接口用例
2.  执行结果经常提示“测试中”，页面卡顿现象
3.  需要刷新页面才能恢复，严重影响执行效率和体验
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
建议升级到最新v1.19版本
