### ISSUE TITLE
使用外部的MySQL无法生效

### ISSUE THREAD

**Issue by huangzgx** [metersphere/metersphere#12]
使用外部的MySQL不能读取install.conf里面的主机地址信息，读取的是当前宿主机的IP地址

**Comment by wangzhen-fit2cloud** [comment]
你好，可否贴一下安装过程中的截图，已经安装目录下（默认 /opt/metersphere）.env 文件的内容

**Comment by meiweig** [comment]
#
![259EB672-CE30-498f-9A3A-D01DFA300D50](https://user-images.githubusercontent.com/62678272/84971321-07d2a700-b14f-11ea-9705-c7e06c36c66c.png)

**Comment by mhjlpp** [comment]
![259EB672-CE30-498f-9A3A-D01DFA300D50](https://user-images.githubusercontent.com/57063070/84974794-88e16c80-b156-11ea-92e0-0eed7610ed6e.png)

**Comment by huangzgx** [comment]
> 你好，可否贴贴安装过程中的截图，已经安装目录下（或/opt/metersphere）.env文件的内容

我后面改为了默认安装的数据库了，现在无法复现该问题
