### ISSUE TITLE
[BUG]接口测试页面，"···"里的报告没有分页，导致页面显示过长

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#120]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.3

**Bug 描述**
简要描述您碰到的问题
接口测试页面，"···"里的报告没有分页，导致页面显示过长

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/87267482-698df300-c4fa-11ea-8a0f-257d5c03858f.png)

**Comment by xulinde** [comment]
您好，这个月26号发布的v1.5版本将会会增加分页，您到时候直接升级下就可以了。
