### ISSUE TITLE
[QUESTION]为API配置前/后置接口的作用是什么?

### ISSUE THREAD

**Issue by jixiang823** [metersphere/metersphere#12000]
新增API时添加依赖关系, 此功能的作用是什么?
例如`API_B`添加`API_A`为前置接口, 是不是可以理解为在执行`API_B`前, 会先去执行`API_A`? 
实际未看到此效果, 是否我的理解有误?
<img width="914" alt="image" src="https://user-images.githubusercontent.com/41544435/160176484-e3cd05a3-3dea-47e7-9568-f595d638299c.png">

**Comment by Hyyfit** [comment]
目前设计如此，主要是体现了接口之间的关系，添加依赖关系后，在企业版可以可以看到接口之间的关系图。
