### ISSUE TITLE
[BUG]api列表用例数排序错误

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12012]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.18.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   存在多个接口定义，一个接口定义下存在 107 接口 case，一个接口下存在 11 个接口 case
2.  在API列表按照用例数排序从小到大排序
3.  107 排在 11 前面
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/160314958-1c3eae3f-9551-4195-a578-5eca3ec17f64.png)

**Comment by ltfit** [comment]
1.19,1 修复该问题 升级下
