### ISSUE TITLE
[BUG]导入场景执行没有响应内容

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12014]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 1.19.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.   导入Metersphere 导出的场景，提示原始 case 不存在
2. 调试执行显示请求成功
3. 响应内容为空
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/36387811/160315544-cc78e6e1-0905-42e5-96fb-2dce27b051be.png">

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by zyyfit** [comment]
1.19.1已修复
