### ISSUE TITLE
[FEATURE]1.19.0 在MOCK服务中，响应数据设置为jmeter内置函数，不支持。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#12011]
**请描述您的需求或者改进建议.**
1.19.0 在MOCK服务中，响应数据设置为jmeter内置函数，不支持。

**请描述你建议的实现方案**
![UUID替换](https://user-images.githubusercontent.com/14307013/160310852-e4b1d0a9-b1dc-431b-8f09-c7d6a7b26284.png)

**Comment by billguo** [comment]
MOCK服务中的以下内容都不支持。
@boolean 布尔值 示例：true
@natural 自然数 示例：72834
@integer 整数 示例：79750
@float 浮点数 示例：24.2
@character 字符 示例：k
@string 字符串 示例：hello
@range 范围 示例：org.mozilla.javascript.NavicatArray@1739f809
@date 日期 示例：1973-01-08
@time 时间 示例：06:15:27
@datetime 日期时间 示例：1975-10-12 02:32:04

**Comment by Hyyfit** [comment]
mock服务是我们系统自己开发处理的，跟jmeter没关系，系统里没处理，所以不支持。
后续会规划，优化这一部分

**Comment by luty2018** [comment]
mockjs 生成测试数据， 是jmeter在运行的时候动态生成然后开始发送出去的，响应数据这里处理不了mock函数，建议使用高级设置来生成一些基础数据。
![image](https://user-images.githubusercontent.com/36292514/163534362-5233f3fa-07a9-4030-9575-b2ae73a3b208.png)
