### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by karencaiyuping** [metersphere/metersphere#12017]
**请描述您的需求或者改进建议.**

希望功能测试用例导出时可以导出执行结果，发报告的时候可以统计进去

**请描述你建议的实现方案**
就是导出的时候增加一个执行结果导出字段

**Comment by Hyyfit** [comment]
目前设计如此。用户对用例的导入导出，主要是用例迁移，如果有执行结果了，容易产生误解。所以目前是这样设计的。
不过后续会考虑自定义导出的字段，到时候可以添加执行结果字段。
