### ISSUE TITLE
[BUG]接口自动化中，打开组件栏(即点击"+"图标)，并进行接口请求的页签切换时，组件栏各组件消失，但组件栏仍显示为开启状态，功能实现不友好，请修改 

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#12015]
**MeterSphere 版本**

v1.19.0

**Bug 描述**

接口自动化中，打开组件栏(即点击"+"图标)，并进行接口请求的页签切换时，组件栏各组件消失，但组件栏仍显示为开启状态，功能实现不友好，请修改 

**期待的正确结果**

进行页签切换时，组件栏正常显示。或者消失时，组件栏状态对应变更为未启用，即显示为"+"图标状态。

**截图**
![image](https://user-images.githubusercontent.com/92150453/160317023-123e062d-604a-4e82-927e-b86635027b48.png)
![image](https://user-images.githubusercontent.com/92150453/160317158-b5cbe130-f9fa-4ec0-a9de-8e3d92777c7f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.19.1已修复
