### ISSUE TITLE
[FEATURE]误报库增加针对某个接口实列的设置条件

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12019]
**请描述您的需求或者改进建议.**
1.设置了全局断言，但是存在部分接口实列的断言不符合全局断言；
2.误报库无法设置针对具体实列进行设置，来指定某个用例；
因此希望增加类似环境设置的地址那样可以针对具体的用例来规避掉全局断言；

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期。
