### ISSUE TITLE
[BUG]我的工作台》》我的创建：列表信息显示的人员名称不一致，有的是中文有的是用户ID。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#12026]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.19

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  我的工作台》》我的创建：列表信息显示的人员名称不一致，有的是中文有的是用户ID。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/160353197-98df4067-0cb3-4a13-8de2-3a98953032a4.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.19.1已修复
