### ISSUE TITLE
【需求/缺陷】缺陷管理处不能添加接口用例的缺陷

### ISSUE THREAD

**Issue by helenls** [metersphere/metersphere#12020]
比如功能用例那边的执行失败会有个添加缺陷的按钮，但是接口用例这边，接口执行失败，我要提bug，不能关联接口。
跟客服确认过，目前缺陷只支持关联功能用例，不过功能用例可以关联接口用例，但是提个bug还得先去关联功能用例，再关联接口用例，再提bug太麻烦

**Comment by Hyyfit** [comment]
目前的设计如此，后续会考虑优化。
