### ISSUE TITLE
[FEATURE]建议添加场景断言

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12027]
**请描述您的需求或者改进建议.**
由于部分查询性接口会有多种结果，所以断言会存在多种情况，为了保证接口脚本最大的复用性，都是进行引用，所以无法在接口去进行断言，在整个场景结束后进行各种结果数据的组合进行断言，那么就需要一个对引用场景进行断言的控件。

**请描述你建议的实现方案**
之前自定义脚本控件中可以添加断言，所以这边每次都是在场景后添加一个空的自定义脚本然后再添加断言，但现在自动化ui改变了，自定义脚本没有断言这个功能了，导致无法实现场景层的断言，可否考虑增加回来

**Comment by Hyyfit** [comment]
已规划，待排期。
