### ISSUE TITLE
[BUG]场景批量导入接口 case 顺序与勾选时不一致

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12025]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
19.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.创建一个场景，从接口列表导入，按照列排序
2.勾选多个 case，点击复制或者引用
3.查看场景中接口 case 的顺序与导入时不一致

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
v1.19.3已修复
