### ISSUE TITLE
[BUG]http请求结果为网页内容时，xpath提取器提取不到内容

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1203]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述**
http请求结果为网页内容时，xpath提取器提取不到内容

**Bug 重现步骤**
1.  请求https://www.baidu.com/
2. 在提取中使用xpath提取器，表达式为//input[@name='tn']/@value 
3. 查看提取结果

**期待的正确结果**
1、未提取到结果
2、在jmeter中使用//input[@name='tn']/@value，勾选“use Tity”时能够匹配到内容，而在平台下此功能无法正常使用

**截图**
<img width="1102" alt="222" src="https://user-images.githubusercontent.com/21210217/104886767-3e9ec300-59a5-11eb-9576-168f519eba93.png">

**Comment by zyyfit** [comment]
当前版本暂时不支持提取html格式的数据，xpath可提取xml格式的返回信息 @nawentao
