### ISSUE TITLE
[BUG]火狐浏览器，脑图 复制 多个 用例并修改名称，点击保存后，新复制的会替换之前的用例，只保留最新复制的那条用例。

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12036]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.19
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/30038088/160387560-7e90dcd9-104c-4273-b1d9-d6552730fe3c.png">

复制了2个 点击保存后 实际模块显示是还是3个。刷新之后 又变成 3个 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
引用的三方组件自身对火狐兼容性不佳，建议用谷歌浏览器
