### ISSUE TITLE
[BUG]升级脚本，建议增加个 my.cnf 的授权 (chmod 655 {MS_BASE}/metersphere/conf/my.cnf)

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12035]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.19
**Bug 描述**
如果服务器 默认没有 655 权限，每次升级 默认替换 my.cnf ，会因为 新替换的 my.cnf 权限不足，升级后 my.cnf 配置不生效，
mysql 按照默认配置启动，flyway 很容易执行因为字符集等原因而导致执行失败，或者连接数问题 dao导致服务异常。

简要描述您碰到的问题

**Bug 重现步骤**
<img width="803" alt="wecom-temp-f1b0384617a47bc23ca6741aad54e878" src="https://user-images.githubusercontent.com/30038088/160386302-1e160bcd-e447-4d50-88e2-5ab5d50abad2.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by liuruibin** [comment]
这个已经在1.19.1小版本中发布
