### ISSUE TITLE
v1.20.0 LTS 发布规划

### ISSUE THREAD

**Issue by luty2018** [metersphere/metersphere#12037]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/36292514/160391061-e71b7f0b-066e-4024-8197-f86255fbea72.png">

**Comment by lijinzhou2016** [comment]
这个版本大概什么时候发布

**Comment by maninhill** [comment]
> 这个版本大概什么时候发布

4月28日。

**Comment by diduweiwu** [comment]
1.19上出现了个 "我的工作台" 属于企业版的功能,有办法隐藏去掉吗?不升级企业版就强制显示在那里么?还是说1.20时候有配置的方法呢??

**Comment by maninhill** [comment]
> 

这个是bug，会修复的。
