### ISSUE TITLE
[BUG]接口返回结果为unicode编码

### ISSUE THREAD

**Issue by niu476806865** [metersphere/metersphere#12049]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
结果应该是utf8编码
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

我做了如下修改,不知道是否合理

io.metersphere.api.jmeter.APISingleResultListener

@Override
    public void handleTeardownTest(ResultDTO dto, Map<String, Object> kafkaConfig) {
        resultToUtf8(dto);
        LoggerUtil.info("处理单条执行结果报告【" + dto.getReportId() + " 】,资源【 " + dto.getTestId() + " 】");
        dto.setConsole(FixedCapacityUtils.getJmeterLogger(dto.getReportId()));
        CommonBeanFactory.getBean(TestResultService.class).saveResults(dto);
    }

    public void resultToUtf8(ResultDTO dto){
        if(dto == null || dto.getRequestResults() == null){
            return;
        }
        for(RequestResult requestResult : dto.getRequestResults()){
            if(requestResult.getResponseResult() == null){
                continue;
            }
            String body = requestResult.getResponseResult().getBody();
            if(body == null || body.equals("")){
                continue;
            }
            body = unicodeToUtf8(body);
            requestResult.getResponseResult().setBody(body);
        }
    }

    public String unicodeToUtf8(String theString){
        char aChar;
        int len = theString.length();
        StringBuffer outBuffer = new StringBuffer(len);
        for (int x = 0; x < len;) {
            aChar = theString.charAt(x++);
            if (aChar == '\\') {
                aChar = theString.charAt(x++);
                if (aChar == 'u') {
                    // Read the xxxx
                    int value = 0;
                    for (int i = 0; i < 4; i++) {
                        aChar = theString.charAt(x++);
                        switch (aChar) {
                            case '0':
                            case '1':
                            case '2':
                            case '3':
                            case '4':
                            case '5':
                            case '6':
                            case '7':
                            case '8':
                            case '9':
                                value = (value << 4) + aChar - '0';
                                break;
                            case 'a':
                            case 'b':
                            case 'c':
                            case 'd':
                            case 'e':
                            case 'f':
                                value = (value << 4) + 10 + aChar - 'a';
                                break;
                            case 'A':
                            case 'B':
                            case 'C':
                            case 'D':
                            case 'E':
                            case 'F':
                                value = (value << 4) + 10 + aChar - 'A';
                                break;
                            default:
                                throw new IllegalArgumentException(
                                        "Malformed   \\uxxxx   encoding.");
                        }
                    }
                    outBuffer.append((char) value);
                } else {
                    if (aChar == 't')
                        aChar = '\t';
                    else if (aChar == 'r')
                        aChar = '\r';
                    else if (aChar == 'n')
                        aChar = '\n';
                    else if (aChar == 'f')
                        aChar = '\f';
                    outBuffer.append(aChar);
                }
            } else
                outBuffer.append(aChar);
        }
        return outBuffer.toString();
    }

**Comment by fit2-zhao** [comment]
@niu476806865  这种建议写到 有需要的后置脚本中吧。
