### ISSUE TITLE
[BUG]配置kafka Backend Listener的Queue Size不生效

### ISSUE THREAD

**Issue by rijian** [metersphere/metersphere#12040]
**MeterSphere 版本**

1.18.3

**Bug 描述**

配置kafka Backend Listener的Queue Size不生效

**Bug 重现步骤**

1.  性能测试提示“QueueWaits: 79916; QueueWaitTime: 99676073376030 (nanoseconds), you may need to increase queue capacity, see property 'backend_queue_capacity'”
2. 根据提示修改性能测试的JMeter Properties，添加backend_queue_capacity，值为50000
3. 重新执行性能测试，仍显示Backend Listener: Starting worker with class: class io.github.rahulsinghai.jmeter.backendlistener.kafka.KafkaBackendClient and queue capacity: 20000

**期待的正确结果**

queue capacity为配置的值50000

**截图**

![image](https://user-images.githubusercontent.com/5071298/160392689-c4efd036-168d-4b82-a9f4-901035e1ff03.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，方便描述一下这个复现的场景吗？

**Comment by zhangzhaox** [comment]
根据提示修改性能测试的JMeter Properties，添加backend_queue_capacity，值为50000
这个调整的方法 在MS里 适用吗？ 原生配置文件里没有这个变量

**Comment by liuruibin** [comment]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/23045261/160750534-6a35ba46-76a9-4a10-8962-7d34ff7789c6.png">
在这里设置
docker-compose-server.yml

**Comment by rijian** [comment]
> <img alt="image" width="967" src="https://user-images.githubusercontent.com/23045261/160750534-6a35ba46-76a9-4a10-8962-7d34ff7789c6.png">
> 
> 在这里设置 docker-compose-server.yml

这个方法可以，3ks~
