### ISSUE TITLE
[BUG] 企业版的误报库菜单不见了

### ISSUE THREAD

**Issue by renren2022** [metersphere/metersphere#12048]
**MeterSphere 版本**

V1.19.0

**Bug 描述**

企业版的误报库菜单不见了。

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/100106457/160514199-2dabb543-965c-4467-9487-b75469a956ee.png)

**Comment by zyyfit** [comment]
看看用户组与权限里，是否勾选了误报库的权限，可能是因为默认没开启权限导致的
