### ISSUE TITLE
[BUG]新建接口定义的用例、新建场景时，编辑后点击关闭按钮时未弹出提示保存的弹窗

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#12044]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.18.3-1.19.0

**Bug 描述**

简要描述您碰到的问题：新建接口定义的用例、新建场景时，编辑后点击关闭按钮时未弹出提示保存的弹窗，导至编辑好的场景不小心全都没有了

**Bug 重现步骤**

1.  新建接口用例或场景 
2.  编辑用例或编辑场景，输入基本信息及接口信息，未保存
3.  点击关闭用例或场景的tab标签
4.  直接关闭标签，没有提示保存，编辑的内容全都没有了

**期待的正确结果**

正确情况下应该是什么样的？希望自动实时保存，或者关闭tab标签时提示保存弹窗

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，场景用例编辑后不保存，关闭时是有提示的，没有复现你的问题，把你修改的详细信息截图看下，
接口case的未保存关闭的提示还没有做，这个需求我们后续版本会优化。
