### ISSUE TITLE
[BUG]tcp协议的接口定义在新建接口用例时，请求参数为空

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#12046]
**MeterSphere 版本**
v1.19

您所使用的 MeterSphere 版本是？
v1.19

**Bug 描述**
tcp协议的接口定义在新建接口用例时，请求参数为空
实际上接口定义之前的请求参数是有数据的

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="927" alt="WX20220328-222241@2x" src="https://user-images.githubusercontent.com/18387151/160419736-8064723b-d334-4fc6-b3f1-8345db89c1e8.png">
<img width="1011" alt="WX20220328-222256@2x" src="https://user-images.githubusercontent.com/18387151/160419760-abc6e316-61d1-472d-9fe9-f5319091889a.png">
<img width="926" alt="WX20220328-222314@2x" src="https://user-images.githubusercontent.com/18387151/160419768-78928717-6aa4-4c35-bd77-91c24942fd93.png">

**Comment by zyyfit** [comment]
1.19.1已修复
