### ISSUE TITLE
[BUG] 添加用例到公共用例库失败，提示：未开启公共库用例配置

### ISSUE THREAD

**Issue by renren2022** [metersphere/metersphere#12057]
**MeterSphere 版本**

V1.19.0（企业版）

**Bug 描述**

在功能用例模块中选择用例，点击“批量添加到公共用例库”，添加失败，提示：未开启公共库用例配置
（系统中并未有开启公共库用例配置的设置）

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/100106457/160521447-33707a97-34b9-4f70-9611-05aff8a136f9.png)

**Comment by ltfit** [comment]
您好 在系统设置-系统-用户组权限 配置下
![image](https://user-images.githubusercontent.com/99794211/160558698-76b3af1a-8bf3-4ef3-a8ea-075247aeb594.png)
然后在项目设置-应用管理 开启下 公共用例库
