### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by niu476806865** [metersphere/metersphere#12051]
**请描述您的需求或者改进建议.**
在使用git下载源码，自行打jar，然后运行时，出现加载python环境出错问题。
启动报错：java.lang.IllegalArgumentException: URI is not hierarchical

该问题原因为，将jython-standalone.jar 放入在backend-1.18.jar中是有问题的。路径加载问题
相应的处理办法为：
        1.在pom中配置unpack。 我试过，没有成功
        2.在打包时，排除org.python依赖。在启动命令中 加入参数
             java -Dloader.path=lib/ -jar backend-1.18.jar --spring.profiles.active=prod
          如此配置后，启动没有错误

请官方支持一下自行部署。

**请描述你建议的实现方案**

**Comment by zhangdahai112** [comment]
你可以试试 把  jar 包放在 src/main/resources/jmeter/lib/ext 这个路径下
