### ISSUE TITLE
[BUG]非管理员用户，在主页点：个人信息，弹出空白页

### ISSUE THREAD

**Issue by niu476806865** [metersphere/metersphere#12050]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.18.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
提示无权限 or 显示正确信息
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 后续版本优化下
