### ISSUE TITLE
[BUG]自定义脚本上的断言没了

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12052]
**MeterSphere 版本**

1.19.0

**Bug 描述**

自定义脚本之前是可以添加断言的，我写了很多，新ui后自定义脚本没有新增和修改断言的位置了，导致我原有的断言无法修改，也没法去加新的断言

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

自定义脚本恢复添加修改断言

**截图**

**Comment by youliyuan-fit2cloud** [comment]
感谢你的反馈，我们会尽快修复这个问题

**Comment by zyyfit** [comment]
1.19.1已修复
