### ISSUE TITLE
[BUG]请求结果跟随重定向时，测试报告中的请求结果会重复显示

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1207]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述**
请求结果跟随重定向时，测试报告中的请求结果会重复显示

**Bug 重现步骤**
1.  请求一个结果为302重定向的url
2. 
3. 
4. 

**期待的正确结果**
不重复显示请求结果

**截图**
<img width="1078" alt="33333" src="https://user-images.githubusercontent.com/21210217/104899316-a957fa80-59b5-11eb-8329-918ff050b039.png">

**Comment by zyyfit** [comment]
已修复
