### ISSUE TITLE
[FEATURE]测试跟踪—测试计划—接口测试，场景化中的场景用例在执行的时候，是乱序的，没法按照ID顺序执行，建议补充一个执行顺序的设计，更人性化

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#12089]
**请描述您的需求或者改进建议.**

[FEATURE]测试跟踪—测试计划—接口测试，场景化中的场景用例在执行的时候，是乱序的，没法按照ID顺序执行，建议补充一个执行顺序的设计，更人性化

**请描述你建议的实现方案**
[FEATURE]测试跟踪—测试计划—接口测试，场景化中的场景用例在执行的时候，是乱序的，没法按照ID顺序执行，建议补充一个执行顺序的设计，更人性化

**Comment by Hyyfit** [comment]
已规划，待排期。

**Comment by Hyyfit** [comment]
执行的顺序是按照加入的顺序执行，加入的页面支持拖动排序
