### ISSUE TITLE
[FEATURE]接口自动化中创建场景，接口列表导入的时候没有按照接口ID排序，是乱的，比较难编辑，编辑个几百个接口，特别麻烦，还得重排。这块建议优化下

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#12088]
**请描述您的需求或者改进建议.**

接口自动化中创建场景，接口列表导入的时候没有按照接口ID排序，是乱的，比较难编辑，编辑个几百个接口，特别麻烦，还得排。这块建议优化下

**请描述你建议的实现方案**
接口自动化中创建场景，接口列表导入的时候没有按照接口ID排序，是乱的，比较难编辑，编辑个几百个接口，特别麻烦，还得排。这块建议优化下

**Comment by Hyyfit** [comment]
感谢建议，已规划，待排期

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本中已优化
