### ISSUE TITLE
[BUG]接口测试-接口自动化，无法创建场景，点击【创建场景】页面无法正常加载！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#12090]
**MeterSphere 版本**

 版本:   v1.19.0-a2928346

**Bug 描述**

[BUG]接口测试-接口自动化，无法创建场景，点击【创建场景】页面无法正常加载！

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/54024064/160581126-92438f11-6282-4402-b22d-4b12b779652a.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版的版本号是 v1.19.0-1727df14，如果版本号不一致的话，可以用 msctl reload 命令重新拉取一下最新镜像试试
