### ISSUE TITLE
[FEATURE]想在API接口中多加一个字段显示该API是否被自动化场景覆盖

### ISSUE THREAD

**Issue by Clared1** [metersphere/metersphere#12095]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/47734806/160582582-61fea2a8-49af-43b7-b34e-42208eb75454.png)
现在只能看到自动化场景的覆盖率，但看不到针对接口层面的覆盖情况，我们希望能看到不同接口是否被覆盖

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/47734806/160582946-cb6b2579-293a-48af-b9e5-77677263caa6.png)
在接口定义界面多显示1个多加一个字段显示该API是否被自动化场景覆盖

**Comment by Hyyfit** [comment]
感谢建议，已规划，待排期。
