### ISSUE TITLE
[BUG]数据库用navicat可以查到数据，用metersphere不可以查到数据

### ISSUE THREAD

**Issue by bxh111** [metersphere/metersphere#1209]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述
数据库用navicat可以查到数据，用metersphere不可以查到数据

**Bug 重现步骤**
1.  选择数据库连接，查询内容引用变量，结果提取不到

**期待的正确结果**
可以检索到数据
**截图**
![企业微信截图_16109626097919](https://user-images.githubusercontent.com/77323173/104907167-9ea26300-59bf-11eb-8dd4-e88ffdc1e653.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请提供下 metersphere 上请求结果的完整截图。
