### ISSUE TITLE
[BUG]修改脑图设计的用例后保存 出现操作日志写入异常 版本号1.19

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#12099]
**MeterSphere 版本**
1.19
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
脑图用例调整顺序偶现调整顺序不准确，
日志显示写入异常
**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![89c1a26b8da377ad352a61825c9371c](https://user-images.githubusercontent.com/101856439/160594505-283e2cf5-cf26-46ed-ba0d-b20c64a15b1f.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
