### ISSUE TITLE
[BUG]接口测试-接口自动化，get请求路径含全局环境中配置的变量情况下，query参数无法拼接到接口路径后面。

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#12091]
**MeterSphere 版本**

版本:   v1.19.0-a2928346

**Bug 描述**

[BUG]接口测试-接口自动化，get请求路径含全局环境中配置的变量情况下，query参数无法拼接到接口路径后面。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.19.1已修复
