### ISSUE TITLE
关于接口使用python脚本

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1210]
**请描问题.**述您的
你好，接口测试中支持python脚本，请问下有文档吗，没看到案例，想看下具体要怎么使用

**Comment by youliyuan-fit2cloud** [comment]
您好！可以参考下面链接，功能和具体步骤类似
https://metersphere.io/docs/tutorial/pre_processor/

**Comment by jia-xf221** [comment]
您好，请问测试中前置脚本支持python，有没有python案例，想看一下具体怎么用
