### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nsq714328535** [metersphere/metersphere#12118]
**MeterSphere 版本**
v1.19.0-a2928346
您所使用的 MeterSphere 版本是？

**Bug 描述**

jmeter和postman提交form-data的post请求，返回成功
metersphere配置完提交失败
对比了请求内容是一样的

**Bug 重现步骤**

1.metersphere
![image](https://user-images.githubusercontent.com/33176667/160760047-1d8b6155-cef9-4c3d-9635-9c9730228d25.png)
![image](https://user-images.githubusercontent.com/33176667/160760142-c9e0820d-dbbf-4614-9f7e-69125698f5dd.png)
![image](https://user-images.githubusercontent.com/33176667/160760338-58150feb-eb1c-451e-8e6e-142cfb86b729.png)

jmeter
![image](https://user-images.githubusercontent.com/33176667/160760200-53c68a47-7e01-43bd-bb2f-da614dc0bd7f.png)
![image](https://user-images.githubusercontent.com/33176667/160760235-906075d8-edf1-418e-ad6a-50473d231dbe.png)
![image](https://user-images.githubusercontent.com/33176667/160760283-b2d37add-c434-40e6-970e-7a8f6353613c.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
![图片](https://user-images.githubusercontent.com/73461316/161041933-9e7ffcc8-f327-4d82-9d46-0377ac727f29.png)
这里填 application/json 试试，不行的话上面那个参数的请求类型也填一下试试

**Comment by shenkaibo** [comment]
用 x-www-form-urlencoded  试一下 ？
