### ISSUE TITLE
[BUG] 测试计划里的接口用例，在接口迁移模块，再迁移回原模块后，在接口模块单独调试接口是可以的，在测试计划里调试接口 读取不到环境信息

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12128]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v.1.19.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试计划关联一个接口用例A（A原先在接口列表A模块，环境配置按模块已选A模块），在测试计划处和接口列表处调试A接口，均没问题。
![image](https://user-images.githubusercontent.com/30038088/160785651-70585953-d43f-488a-94fe-3f0991029ee9.png)

2. 调整接口用例A到B模块，保存，再调整回A模块。
3. 在接口模块 执行接口用例A，可以正常执行。
![image](https://user-images.githubusercontent.com/30038088/160785884-bf9a861d-aef4-46be-aba2-0e89dc3f190a.png)

4. 在测试计划里执行接口用例A，读取不到 环境的 url 信息。
![image](https://user-images.githubusercontent.com/30038088/160785944-7fb0410c-a71a-4386-a01e-3484f71f2184.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是必现的吗？没有复现这个问题

**Comment by shenkaibo** [comment]
是必现的

**Comment by zyyfit** [comment]
经确认是早起版本创建的case数据问题

**Comment by shenkaibo** [comment]
复制一个 新的 case 可以解决此问题
