### ISSUE TITLE
接口测试中，TCP测试环境引用无效[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#1212]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2

**Bug 描述**
简要描述您碰到的问题
在1.6.2版本中，创建TCP的接口测试，然后编辑用例，用例运行时选择环境，但是环境加载了http信息，无法使用tcp信息
![image](https://user-images.githubusercontent.com/30932762/104920593-f5fdfe80-59d2-11eb-81a7-a8556f770ad7.png)

**Bug 重现步骤**
1.  创建TCP接口，其中服务器，端口等都是必填内容，但是不填写也可以保存
2. 基于接口创建用例，用例执行选择环境，但是测试无法引用环境信息

**期待的正确结果**
正确情况下应该是什么样的？
类似http接口，可以引用环境中配置的信息

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
