### ISSUE TITLE
[BUG]GET请求参数未拼装到URL中

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#12133]
**MeterSphere 版本**

v1.18.1-72533db2

**Bug 描述**

接口测试中，配置请求方法为GET时，QUERY参数未被配置到URL中

**期待的正确结果**
QUERY参数拼装到URL中

**截图**
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/34698664/160789533-4d25bc28-601a-45c1-9f50-c99b659f08eb.png">

**Comment by genezx** [comment]
请求体选择form-data就正常，选择JSON时就有这个BUG。根据HTTP规范，GET请求不能带请求体，所以请求体应全部拼到Query参数中而请求体类型应被忽略。

**Comment by Saco93** [comment]
> 请求体选择form-data就正常，选择JSON时就有这个BUG。根据HTTP规范，GET请求不能带请求体，所以请求体应全部拼到Query参数中而请求体类型应被忽略。

确实是这样，所以这个问题是因为没有忽略请求体类型，反而Query参数的拼装收到了请求体类型的影响了。

**Comment by youliyuan-fit2cloud** [comment]
设计如此，get 有query和请求体时，只保留请求体
