### ISSUE TITLE
[BUG]用户无性能测试权限依然可以跳转到性能测试页面

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#12149]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.19.0
**Bug 描述**
用户无性能测试权限依然可以跳转到性能测试页面
简要描述您碰到的问题

**Bug 重现步骤**

1.  去掉用户组的性能测试相关权限
2. 在该用户组的用户点击接口或者场景的创建性能测试
3. 跳转到性能测试页面
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="933" alt="截屏2022-03-30 下午11 42 45" src="https://user-images.githubusercontent.com/34637801/160875688-d8d9cc87-d624-49d0-911a-ead40f98dde7.png">
<img width="1309" alt="截屏2022-03-30 下午11 42 57" src="https://user-images.githubusercontent.com/34637801/160875726-389a6015-a6fd-47c4-becb-66be658a9ccb.png">

**Comment by Hyyfit** [comment]
已规划，待排期
