### ISSUE TITLE
[BUG]脑图新增用例后，多次点击保存，新增的用例100%出现丢失

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#12143]
**MeterSphere 版本**
v1.18.0

**Bug 描述**
脑图新增用例后，多次点击保存，新增的用例100%出现丢失

https://user-images.githubusercontent.com/67257251/160823462-3b4c0cb3-d8c6-419c-acdc-b8a75d067fbf.mp4

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by libb-test123** [comment]
请问这个问题会在v1.18.0和v1.19.0版本上做修复吗？这样我们在不升级最新版本的情况下也能使用这个优化后的功能，防止新版本不稳定带来的其他问题。

**Comment by ltfit** [comment]
会尽快修复 暂不确定

**Comment by ltfit** [comment]
1.19.1修复该问题 升级下
