### ISSUE TITLE
[BUG] 性能测试-请求很多的时候，图标鼠标悬停显示不全

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#1214]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2

**Bug 描述**
如题

**Bug 重现步骤**
1.  性能脚本请求很多
2.  开始测试
3.  鼠标悬停在图标上

**期待的正确结果**
正确情况下应该是什么样的？
显示完整，请求名称过长的可以用省略号

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44999044/104979697-dbae3a00-5a3f-11eb-945c-8e0c7bad18fb.png)

**Comment by xulinde** [comment]
已修复，升级到最新版本即可
