### ISSUE TITLE
[BUG]xpath断言失败问题

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#12155]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.19.0
**Bug 描述**

简要描述您碰到的问题
使用百度网站作为接口，使用xpath进行断言报错，相同语句在Jmeter中可以正常断言；
**Bug 重现步骤**

1.  接口定义中创建/接口
2. 环境使用https://www.baidu.com
3. 增加一个xpath断言
4. //meta[@name='referrer']

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1161" alt="截屏2022-03-31 上午11 28 27" src="https://user-images.githubusercontent.com/34637801/160970572-2b31e6a3-251d-4248-b88c-334af9e718c0.png">

**Comment by zyyfit** [comment]
jmeter 也是这样的，我们目前和 jmeter 保持一致
![图片](https://user-images.githubusercontent.com/73461316/161043859-658cc8bc-0bd5-4ede-a0bb-595bfea7aed5.png)
