### ISSUE TITLE
[BUG]功能用例脑图特殊字符转译问题

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#12153]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.19.0
**Bug 描述**

简要描述您碰到的问题
功能用例脑图步骤中带">"字符，导入MeterSphere后，字符变成&gt
**Bug 重现步骤**

1.  在功能用例脑图中编写步骤；
2. 在步骤中写入字符>；
3. 导入MeterSphere中；
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="657" alt="截屏2022-03-31 上午11 05 34" src="https://user-images.githubusercontent.com/34637801/160968161-3c44b91b-fe2d-4463-8ab8-9e1ae4ff6bd8.png">

**Comment by ltfit** [comment]
升级新版本再看下
