### ISSUE TITLE
支持接口批量测试和测试计划生成的报告中失败的case或场景可以直接在报告中跳转到对应的Case和场景中

### ISSUE THREAD

**Issue by kakawaa** [metersphere/metersphere#12162]
**请描述您的需求或者改进建议.**

批量测试和测试计划生成的报告中失败的case不能直接查看对应的case
**请描述你建议的实现方案**
支持接口批量测试和测试计划生成的报告中失败的case或场景可以直接在报告中跳转到对应的Case和场景中，方便定位失败的case和场景

**Comment by Hyyfit** [comment]
感谢建议，已规划，待排期。
