### ISSUE TITLE
[BUG]环境配置中，配置了环境变量，http配置请求头，测试时并没有自动添加请求头

### ISSUE THREAD

**Issue by Snuger** [metersphere/metersphere#1217]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
环境配置中，配置了环境变量，http配置请求头，测试时并没有自动添加请求头

**Bug 重现步骤**
1.  添加接口
2. 配置开发环境，http配置，添加请求头，Authorization，保存
3. 接口页面，填写参数，点击测试
4. 请求的header并没有添加此项

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33015003/105015904-0074d280-5a7d-11eb-8325-1f75eefff16d.png)

![image](https://user-images.githubusercontent.com/33015003/105015984-14b8cf80-5a7d-11eb-8952-163dba5978e6.png)

**Comment by AgAngle** [comment]
你好请问你是什么版本啊，最新的1.6.2应该已经解决了这个问题

**Comment by Snuger** [comment]
> 你好请问你是什么版本啊，最新的1.6.2应该已经解决了这个问题

1.6.0我尝试升级
