### ISSUE TITLE
[BUG] POST接口JSON数组里面的字符串类型错误

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#12179]
**MeterSphere 版本**

1.19

**Bug 描述**

接口测试POST JSON请求时，数组里面的字符串类型错误

**Bug 重现步骤**

1. 接口测试--接口定义--创建接口或编辑接口
2. 点击TEST，请求选择POST，URL随意
3. 请求体--请求参数选择JSON，导入以下内容：{"test":["0001"]}，确保第三行“0”这行的类型是string而不是number或integer
4. 点击测试按钮
5. 点击响应内容--请求内容查看发送的JSON请求

**错误的结果**

POST data:
{
  "test": [
    1
  ]
}

**期待的正确结果**

POST data:
{
  "test": [
    "0001"
  ]
}

**截图**

略

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是必现的吗？如果是的话方便把您的接口导出ms格式给我们吗？
![图片](https://user-images.githubusercontent.com/73461316/161044903-e9866ae6-7104-4dc1-a2a3-d17e478acede.png)

**Comment by genezx** [comment]
是的，稳定复现。

[Metersphere_Api_默认项目.7z.zip](https://github.com/metersphere/metersphere/files/8394193/Metersphere_Api_.7z.zip)

![1](https://user-images.githubusercontent.com/31116612/161182063-e6bd8245-cea0-4170-a76d-c7f3000af920.png)

![a](https://user-images.githubusercontent.com/31116612/161182075-c3576be0-7526-4b63-8860-0a18a044ad59.png)

**Comment by zyyfit** [comment]
知道了，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.19.2中已修复
