### ISSUE TITLE
[BUG]断言显示不全

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#12176]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.19

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  设置了20几个断言，在执行后，在断言页签，即使拖动滚动条也无法显示全部断言。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/161005136-2b3c0334-63cf-4244-9d00-f2ee5a255e48.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.19.3已修复
