### ISSUE TITLE
[BUG]接口定义casetab建议加一些高级搜索功能

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#12178]
**MeterSphere 版本**

1.19.0

**Bug 描述**

接口定义casetab建议加一些高级搜索功能

**Bug 重现步骤**

1.  接口定义---case---tab
2. 无法实现高级搜索
3. 
4. 

**期待的正确结果**

建议加一些高级搜索功能，测试跟踪--测试计划--接口用例关联用例页面就有高级检索

**截图**

![image](https://user-images.githubusercontent.com/19423100/161008599-33d20d6c-9f51-44c3-b367-cf48e07f18cf.png)
![image](https://user-images.githubusercontent.com/19423100/161008986-0165844b-163e-46af-a5c0-86df09a118f0.png)

**Comment by Hyyfit** [comment]
已重新规划了高级搜索的优化，预计1.21版本会上线
