### ISSUE TITLE
[FEATURE] 若功能用例关联接口测试相关用例后，在功能用例列表是否能实现区分有实现API自动化？

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12177]
**请描述您的需求或者改进建议.**
某个功能用例已实现API自动化测试，在维护功能用例的时候关联API自动化测试用例。建议在功能用例列表中有筛选或者展示改功能用例已实现API自动化测试，这样可以区分哪些是自动化测试用例，哪些是手工测试用例，从目前来看，是无法区分的，只能打开具体用例才能看到是否有关联API自动化测试

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期。
