### ISSUE TITLE
接口定义和接口自动化测试可导入最好

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1218]
**请描述您的需求或者改进建议.**
想在接口定义和接口自动化测试加入导入，最好支持jmx 和csv（这个需要定义模板）

**请描述你建议的实现方案**
在界面通过提供的插件录制好后，在jmeter的改好name,写好断言等等，然后传入接口自动化自动解析后在界面展示，这样会方便好多。

**Comment by xulinde** [comment]
1.9.0已支持
