### ISSUE TITLE
[FEATURE] 全局函数

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#12180]
**请描述您的需求或者改进建议.**
目前在很多应用场景里，有些接口请求是需要进行md5签名的。有没有什么简便一点的方法实现这个功能？
我目前是在场景步骤里面写签名脚本，然后有几个接口请求就复制几次相同的签名脚本，这样后期完全没法维护签名脚本，且后续万一修改了签名算法那将是一场噩梦。

**请描述你建议的实现方案**
有没有办法做一个全局函数功能，写一次签名函数就可以用在所有请求上？以后维护也方便。当然还要可以自定义输入输出绑定的场景变量什么的才能用。

**Comment by Hyyfit** [comment]
可以环境配置的全局脚本中添加

![image](https://user-images.githubusercontent.com/95834771/161369810-9931ce5b-850e-4c7c-8871-2f696250e237.png)

**Comment by genezx** [comment]
感谢解答，“单个请求步骤前执行”可以满足要求。

另外，我在环境配置的全局脚本里面的“所有场景步骤前执行”这一块里面加了一堆给脚本用的公共函数，可是在接口自动化的场景里面的自定义脚本里面并不能调用这些函数。好像是只要是分开编写的两块脚本，就不能A脚本调用B脚本里面的函数，可是我想A调B，请问这个情况要怎么办？
