### ISSUE TITLE
[FEATURE] 项目环境全局HTTP头

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#12181]
**请描述您的需求或者改进建议.**
在流行的微服务框架下面，一个项目中可能存在几十个微服务，而它们的IP端口路径均不同。目前可以在环境->HTTP配置项下面配置特定路径对应的微服务的IP、端口和HTTP头，但唯独缺少针对所有微服务路径全局生效的HTTP头的配置。如果单独为每个微服务路径配置一遍全局HTTP头，那将是一场噩梦，且后续维护添加删除全局HTTP头都将是地狱模式。

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期
