### ISSUE TITLE
[BUG]前置脚本导入jar包，一直无法导入

### ISSUE THREAD

**Issue by lulucky515a** [metersphere/metersphere#12197]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  IDEA 打包
2. 进入meterspere，上传jar包
3. 在前置脚本中导入jar路径
4. 显示错误提示

**期待的正确结果**
应该可以正常导入成功

**截图**

如果有截图，请附上截图.
<img width="1130" alt="截屏2022-03-31 下午7 07 22" src="https://user-images.githubusercontent.com/45556675/161042436-c4f501f9-7780-4074-8efc-b9b693e49114.png">
<img width="1398" alt="截屏2022-03-31 下午7 12 20" src="https://user-images.githubusercontent.com/45556675/161042513-f107b8fe-437c-4329-9ef8-3cdb57f9618f.png">
<img width="930" alt="截屏2022-03-31 下午7 15 28" src="https://user-images.githubusercontent.com/45556675/161043147-39b9b8e9-0c02-4e4c-b1a9-805b58629a82.png">
<img width="961" alt="截屏2022-03-31 下午7 17 06" src="https://user-images.githubusercontent.com/45556675/161043310-557a7c54-245c-4f21-9cc2-f36fad1e56e8.png">

2022-03-31 19:15:34 ERROR 3688ab61 1-1 Problem in JSR223 script, JSR223PreProcessor
In file: inline evaluation of: ``//1、引用jar包  import main.java.*;  //2、获取场景变量中的参数reg  String reg=vars.get("工资"); l . . . '' Encountered "vars" at line 35, column 1.
 in inline evaluation of: ``//1、引用jar包  import main.java.*;  //2、获取场景变量中的参数reg  String reg=vars.get("工资"); l . . . '' at line number 35
javax.script.ScriptException

**Comment by zyyfit** [comment]
这个是脚本错误吧？显示35行出错了，你用jmeter试试报错吗？我们用的是jmeter 里的 jsr233 组件
![图片](https://user-images.githubusercontent.com/73461316/161045384-7b9af287-4c40-4526-ba83-208920d83569.png)
