### ISSUE TITLE
[BUG]用例列表，脑图切换导致乱序及用例编写偶发被删直接去到回收站

### ISSUE THREAD

**Issue by jiming-liu** [metersphere/metersphere#12194]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.19
**Bug 描述**
1. 用例脑图编写后，切换至列表，在切回脑图时，顺序全乱了
2. 用例脑图编写时，点击保存后会偶发出现用例直接被删除，去到回收站的情况（有切换模块的操作，暂时找不到规律）

简要描述您碰到的问题

**Bug 重现步骤**

1.  
4. 
5. 
6. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 后续版本修复
