### ISSUE TITLE
[BUG] 导出的环境文件导入后，domain信息丢失

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12207]
**MeterSphere 版本**
1.17.3
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
这个问题我验证过了，tapd上提无效，github上再提一次
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
没有复现，请详细描述一下复现步骤，或者贴一下复现文件
