### ISSUE TITLE
[BUG]在A场景里引用B场景，B场景如果放在A场景上面，且B场景里有用到场景变量，这个时候再执行，循环取出来的值都是一样的

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#12201]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.19.0

**Bug 描述**

简要描述您碰到的问题：在A场景里引用B场景，B场景如果放在A场景上面，且B场景里有用到场景变量，这个时候再执行，循环取出来的值都是一样的

**Bug 重现步骤**

1.  A场景里使用循环控制器，次数查询CSV里面的数值
2. 在A场景里引用B场景，放到循环控制器步骤上面；前提是B场景内有使用任意的场景变量
3. 在A场景里执行，原循环控制器的次数循环执行有错误，查出来的都是第一个数值
4. 

**期待的正确结果**

正确情况下应该是什么样的？次数循环正确查出不同的数值

**截图**
"![Uploading 2d70288e83f39166e33a3b36e108698.jpg…]()"
"![Uploading 6be62157cbeb50da9c4d2697ac21bcc.jpg…]()"

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.19.2中已修复
