### ISSUE TITLE
[BUG] 1.8.2 性能测试报告 导出来 格式变形了

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12205]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/76033005/161074266-0e5b0ca3-8a84-45e7-89a8-227dd49e564b.png)

如果有截图，请附上截图.

**Comment by ltfit** [comment]
你好 你这个是每个性能报告都是会变形吗
