### ISSUE TITLE
接口采用JSON-SCHEMA搭配mockjs或者函数类型，关掉JSON-SCHEMA后会数据会错误[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#12200]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.19
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  采用JSON-SCHEMA编写测试JSON

![image](https://user-images.githubusercontent.com/30932762/161059299-9a6b153b-0ec2-4d43-ac4a-7ebf01167f10.png)

2. 关闭JSON-SCHEMA后，请求提会自动变成带有{__MOCK(xxxx)}
![image](https://user-images.githubusercontent.com/30932762/161059560-b5e1533e-a0f5-4fff-ad9a-d3931a00bbed.png)

3.然后在开启JSON-SCHEMA，发现数据已经变了
![image](https://user-images.githubusercontent.com/30932762/161060071-23913156-b01f-4067-a56e-9fbaa7f762b0.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，这个转换是这样的，取值都是正常的，只是json-schema转换成json后会显示出函数原来的样子，再转换回来就不会变回来了
