### ISSUE TITLE
[BUG][旻一]有的接口json请求体里使用函数不生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#12203]
**MeterSphere 版本**

1.19

在ms上手写的json请求体里使用函数是生效的，但是有一串Jmeter里复制过来的参数，函数在里面就不生效了

具体请求体如下：
POST data:
{"area":"东城区","country":"","city":"北京市","openid":"oi4ZD5C5HguT9jBL_l2oQHQmo${_Random(100,999)","sex":0,"mobile":"176${__Random(10000000,99999999,)}","randCode":"wZyjHajc","avatar":"https://thirdwx.qlogo.cn/mmopen/vi_32/vib6CNBXrDLYuBuOibctvdJFj5apEshR4JdjAaLw5GT5hib8ZeYrT4FFdB0FvNpOl2UeMs4f2lRNJfJ162YmqBqAQ/132","areacode":"110101","province":"北京市","countryCode":86,"nickname":"热心市民57550","_":"1648554153305"}

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.19.3已修复
