### ISSUE TITLE
[BUG] MS导出的jmx因为断言没有设置正则在jmeter中无法执行 

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12208]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/76033005/161077516-58dda030-09dd-493f-bbaf-7156e110be7f.png)
![image](https://user-images.githubusercontent.com/76033005/161077515-54b25ae0-b135-41e5-b2a9-230a54c6afaa.png)

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
我导出来是有的，1.19.0，用户是否没选正则匹配
![图片](https://user-images.githubusercontent.com/73461316/161224497-de7ee3f0-e1c4-4153-a8db-583a42214a79.png)

![图片](https://user-images.githubusercontent.com/73461316/161224188-750ea430-1e4f-4c77-a998-da5fcdf7e9bb.png)
