### ISSUE TITLE
[BUG][1.16.5][接口测试] 接口列表中显示的数据不正确

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12209]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

[Geminiapp]
1. API接口的用例执行状态显示不正确，用例已经执行并通过，API列表中显示为’未执行‘
![image.png](/resource/md/get?fileName=629f78da_image.png)
1.1 通过率如何计算？
2. 用例的测试结果是通过的，但是通过率不是100%
![image.png](/resource/md/get?fileName=2c681cf1_image.png)
3. 用例通过率和记录不匹配
![image.png](/resource/md/get?fileName=f49145ef_image.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1. api是否有多个case？有一个case未执行，api的状态就是未执行的
2. 用例 通过率 = 当前用例执行通过的次数 / 总的执行次数
3. 看不到你的图片，没有复现，执行历史里目前是显示5条执行记录，并不是所有的执行记录
