### ISSUE TITLE
[BUG]对于Test plan名的长度需要加长， 目前的长度不够，需要加到150 

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12204]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**
客户那边 计划名称比较长，对于Test plan名的长度需要加长， 目前的长度不够，需要加到150 
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期
