### ISSUE TITLE
[1.18.2] [BUG] API Plan执行性能很差，只有一个场景用例的plan，场景执行时间1分钟，但是plan的执行时间是10分钟 -- 已经提交MS[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12211]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/76033005/161177284-d1659379-63b3-4c39-bc7f-437cf5c3b4cb.png)
![image](https://user-images.githubusercontent.com/76033005/161177296-e0a732d0-e20c-409e-805e-0cfdaa018c79.png)

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/12230

**Comment by zyyfit** [comment]
1.19.1对测试执行进行了优化，可以升级看看
