### ISSUE TITLE
[1.18.2] [优化] 环境配置页面选择模块目录图标优化：如果子目录有没有选择的父目录的选择图标需要有区别[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12213]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/76033005/161177403-ad5cf1d6-9985-44f2-a4e2-56fb53abe2f2.png)

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期

**Comment by 35plus** [comment]
帮忙给一个排期
