### ISSUE TITLE
[BUG] swagger的定时同步需要先认证通过，应该如何处理？

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#12212]
**MeterSphere 版本**
1.16
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 访问 swagger URL 需要认证通过后才可访问，导致定时同步失败
2. 
3. 
4. 

**期待的正确结果**
支持调用接口认证后，使用URL 同步
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
目前只支持添加token，定时同步的话，好像没什么好的处理方法
![图片](https://user-images.githubusercontent.com/73461316/161226931-97a9ef58-2d49-40fe-bee7-71003c019f4c.png)
