### ISSUE TITLE
[BUG]功能测试用例-附件里不能上传视频。---非常重要

### ISSUE THREAD

**Issue by superkaka8145** [metersphere/metersphere#12218]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.19.0-1727df14

**Bug 描述**

简要描述您碰到的问题
在测试用例附件里不能上传视频。
我们对比较负责的需求不光写case，还会有对应的视频教学，想一一对应，做沉淀让新人更好的学习。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。
