### ISSUE TITLE
[FEATURE]接口测试：不能测试XMPP消息发送的接口。

### ISSUE THREAD

**Issue by superkaka8145** [metersphere/metersphere#12219]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.19.0-1727df14

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
感谢反馈，目前暂不支持，等调研后再进行规划排期。
