### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LsdtkDds** [metersphere/metersphere#1221]
**MeterSphere 版本**
版本: v1.6.2-e012d438

**Bug 描述**
请求加完“https”后会自动清空“https”

**Bug 重现步骤**
1.  打开 接口定义
2. 创建接口
3. 输入 请求地址
4. 请求地址前有“https”,点击保存

**期待的正确结果**
保存有“https”的完整路径
***实际结果**
没有保存“https”
**截图**
![image](https://user-images.githubusercontent.com/77710632/105122768-ca356280-5b11-11eb-9736-323d614b27be.png)

**Comment by wangzhen-fit2cloud** [comment]
接口定义的作用类似于接口文档，在定义中不需要包含域名信息哈，这样就可以把接口定义好之后，在多个环境中进行测试。
