### ISSUE TITLE
[FEATURE]【优化】“未规划接口”不要统计到面板数据

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12217]
**请描述您的需求或者改进建议.**

“未规划接口”不要统计到面板数据
进一步要求：
可以通过folder统计：API数，API case数，场景数，通过率（环境相关）

针对该需求，如有任何问题，请联系 Xin.zhang@ebaotech.com

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
目前设计如此，未规划的接口也是属于接口部分，所以也会统计。
后期会考虑配置首页统计类别来处理这个问题。
