### ISSUE TITLE
[BUG][1.18.2] report需要英文翻译和繁体翻译，导出的报告（测试计划报告，性能测试报告）

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12210]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
感谢反馈 后续版本优化下

**Comment by ltfit** [comment]
1.20 已修复
