### ISSUE TITLE
[BUG][优化] 缺陷模块需要添加附件功能，易保

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12215]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期
