### ISSUE TITLE
[1.18.2] 易保，测试计划与环境分离，另外调用接口的时候传入项目与环境信息触发plan执行不成功，页面是可以的[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12214]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/76033005/161177494-1157397c-c93c-4627-855f-b39b03168dd7.png)

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by ltfit** [comment]
没太明白描述的意思 再详细描述下吧
