### ISSUE TITLE
[BUG]测试计划点击负责人筛选键，出现报错

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#12226]
**MeterSphere 版本**

1.19.0

**Bug 描述**

测试计划点击负责人筛选键，出现报错

**Bug 重现步骤**

1.  测试计划tab
2. 选择负责人，点击筛选
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="658" alt="image" src="https://user-images.githubusercontent.com/44996472/161189121-6f0843b2-741c-42d0-8879-9d759aaba3cf.png">

**Comment by ltfit** [comment]
感谢反馈 下个版本修复
