### ISSUE TITLE
[BUG] 接口自动化开启定时任务后，无法取消任务，会一直生成测试报告，删除场景后任务不会停止

### ISSUE THREAD

**Issue by IceFoxs** [metersphere/metersphere#1222]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.6.2-e012d438
**Bug 描述**
简要描述您碰到的问题
定时任务开启后，无法停止，希望可以取消定时任务
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望有取消任务的按钮
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26451038/105138119-69b51e00-5b2f-11eb-9b93-cca2e3d86c9e.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，可以在 接口测试-首页 看到当前配置的定时任务，并关闭定时任务。
![Uploading image.png…]()

**Comment by IceFoxs** [comment]
> 你好，可以在 接口测试-首页 看到当前配置的定时任务，并关闭定时任务。
> ![image](https://user-images.githubusercontent.com/27671436/105670987-f3446180-5f1c-11eb-9436-5e970d680abf.png)

谢谢您，知道了，没有注意面板定时任务功能

**Comment by wangzhen-fit2cloud** [comment]
好的，这个 issue 先关掉了，后面我们会再优化下体验及文档。
