### ISSUE TITLE
[QUESTION]要做环境迁移，数据库等已经搞定，不清楚上传的附件放到了哪个服务目录下了

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#12221]
**请描述您的问题.**
不清楚上传的附件放到了哪个服务目录下了
![image](https://user-images.githubusercontent.com/67257251/161183901-d9feb8c2-9c6f-4897-aa39-8e314f0da2e0.png)

**Comment by luty2018** [comment]
这个是存在数据库里的

**Comment by libb-test123** [comment]
哪个数据库，MySQL这些数据库还能存储文件类型的数据吗？
