### ISSUE TITLE
[BUG]场景用例 测试计划报告，接口用例分析，场景标题有时无超链接

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#12223]
**MeterSphere 版本**
1.16.1

**Bug 描述**

场景用例 测试计划报告，接口用例分析，场景标题有时无超链接

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/20641051/161187159-994af9c3-4434-440e-92d7-0925c0d06467.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，具体是怎么操作的？
