### ISSUE TITLE
[BUG] 用例模板、缺陷模板页面，点帮助图标后 ，弹出的帮助文档未置顶，点击帮助之后，点返回才能看到文档

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12235]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
打开用例模板、缺陷模板的帮助文档未置顶，点击帮助图标“？”之后，点返回才能看到文档。

应该是用户 点击 ？后，直接弹出来帮助文档
1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没理解你说的哪里的帮助？请上传截图
