### ISSUE TITLE
[QUESTION]xpack包下没内容，导致找不到类

### ISSUE THREAD

**Issue by youpanpan** [metersphere/metersphere#12231]
**请描述您的问题.**
下载源码包metersphere-1.20.0-rc，编译的时候发现缺少io.metersphere.xpack包下的类

例如：
import io.metersphere.xpack.ui.impl.CommandConfig;

**Comment by AgAngle** [comment]
你好，这个 xpack 是企业版涉及的代码，需要权限，看了下代码，主要涉及到的是 UITest ，我们删一下这个类啊，建议你先使用已经发布的最新的分支 1.19
