### ISSUE TITLE
[BUG]环境配置中，HTTP配置，启用条件选择 模块，在场景中有时加载不，概率很大

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#12232]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

[BUG]环境配置中，HTTP配置，启用条件选择 模块，在场景中有时加载不，概率很大

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，执行了50次，没有复现，能描述一下具体操作步骤吗
