### ISSUE TITLE
[BUG]若步驟或者預期結果存在子項時，導入時會當成一個大步驟

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12246]
**MeterSphere 版本**
   v1.18.3

**Bug 描述**
  若步驟或者預期結果存在子項時，導入時會當成一個大步驟

**Bug 重现步骤**
   如下用例，在平台上維護以後，導出到Excel正常，重新導入到平台後，展示佈局錯亂：
    測試步驟
       1.测试已开始；
       2.测试进行中；
       3.测试已完成
    預期結果
       1.测试结果1
       2.测试结果2：
          1）检查数据1
          2）检查数据2
       3.测试结果3

**期待的正确结果**
  正確結果 重新導入以後，應該如下圖所示：
![image](https://user-images.githubusercontent.com/37204403/161220096-44da6f35-03c8-4e39-b08f-5c9b46a76057.png)

**截图**

![image](https://user-images.githubusercontent.com/37204403/161219730-a2ae54e1-ea88-492f-8d8d-9e823465a8ec.png)

**Comment by ltfit** [comment]
感谢反馈  后续版本修复

**Comment by zyyfit** [comment]
导出的单个步骤含有换行符，我们导入逻辑认为有换行就是一个新的步骤，逻辑有冲突，现在已修改为导出时如果单个用例有换行，去掉换行符
1.20.7版本发布，请等待发布后验证
