### ISSUE TITLE
[BUG]yapi支持导入的swagger格式，ms不支持

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#12256]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

yapi支持导入的swagger格式，ms不支持

https://sandbox.platform.moxigame.cn/dev/platapidoc/CEndDocs/swagger.json

### 重现步骤

用上卖弄的连接导入yapi和ms

**Comment by zyyfit** [comment]
原因是导入的swagger文件里的 请求方式 POST 大写了，改成小写就可以了
