### ISSUE TITLE
[FEATURE] 在Case搜索中加上路径匹配

### ISSUE THREAD

**Issue by Clared1** [metersphere/metersphere#12252]
### MeterSphere 版本

v1.19.0

### 请描述您的需求或者改进建议

为什么API高级搜索的时候包括路径匹配，而Case搜索的时候不包括，强烈建议在Case搜索中加上路径匹配。
![Kza7x4r73z](https://user-images.githubusercontent.com/47734806/161241590-c50df461-85fc-4b73-88bf-6dfd16d982b9.png)

API高级搜索：
![XJjtUGP5YH](https://user-images.githubusercontent.com/47734806/161241645-78a1db10-d83e-4a90-b99d-8149bbe9b0bb.png)

Case高级搜索：
![fEjGWcsUxd](https://user-images.githubusercontent.com/47734806/161241701-4bb6e60a-2ed4-4b08-8e47-cf4bd9681c6b.png)

### 请描述你建议的实现方案

建议在Case高级搜索中加上路径匹配

**Comment by Hyyfit** [comment]
高级搜索已规划了优化，能满足对路径搜素的需求，预计是在1.21版本会上线。
