### ISSUE TITLE
[BUG]批量执行接口场景测试时，会出现将原有14个步骤的用例执行处3000步的效果

### ISSUE THREAD

**Issue by zengyihuan** [metersphere/metersphere#12251]
### MeterSphere 版本

v1.18.0-82ba1b94

### 使用外置数据库

否

### 问题描述

1、单个执行同一个场景没有问题
2、批量执行or定时任务执行测试计划，会出现场景内步骤被重复执行的现象，控制台显示为在同一个时间戳启动了多个线程

### 重现步骤

概率出现，批量执行800个场景大概会有100多个这样的情况。。

### 附加信息

![WX20220401-172251](https://user-images.githubusercontent.com/12249448/161235508-feb23466-5207-4e7d-8ff2-9a95123f3a43.png)
![WX20220401-172042](https://user-images.githubusercontent.com/12249448/161235537-3a58b850-7360-4cb8-b20e-b4fb306f0917.png)
![WX20220401-172030](https://user-images.githubusercontent.com/12249448/161235557-94b5cc18-0425-42ee-90b9-b77a2ad8937d.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没遇到这个问题，场景方便发给我们复现一下吗？

**Comment by youliyuan-fit2cloud** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
