### ISSUE TITLE
[BUG]当场景引用用例后  删除改场景  用例查看引用时 还是会有该场景的展示

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#12258]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

当场景引用用例后  删除改场景  用例查看引用时 还是会有该场景的展示
![image](https://user-images.githubusercontent.com/88763608/161246933-3446d4a3-abef-4e86-8d87-f1de6caddf6f.png)

### 重现步骤

当场景引用用例后  删除改场景  用例查看引用时 还是会有该场景的展示

**Comment by zyyfit** [comment]
是因为删除后的场景在回收站里，没有真的删除，后续版本优化

**Comment by zyyfit** [comment]
1.19.3已修复
