### ISSUE TITLE
[FEATURE]功能用例导入导出后，用例执行结果的状态丢失了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#12254]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

功能用例导入导出后，执行结果的状态丢失了

### 重现步骤

功能用例导出再导入

### 期待的正确结果

执行结果应该要保留做为参考

**Comment by zyyfit** [comment]
原因是导入的swagger文件里的 请求方式 POST 大写了，改成小写就可以了

**Comment by Hyyfit** [comment]
目前设计如此
