### ISSUE TITLE
[BUG]脑图，列表切换后，脑图用例顺序全乱

### ISSUE THREAD

**Issue by jiming-liu** [metersphere/metersphere#12269]
### MeterSphere 版本

v1.19

### 使用外置数据库

否

### 问题描述

在脑图中编写用例，再切换到列表，再次切回脑图时，脑图所写的用例全乱序了

### 重现步骤

1. 脑图编写好用例后，切换到列表
2. 再次切回脑图，此时脑图顺序全乱了

### 期待的正确结果

脑图顺序保持原有的

**Comment by liuruibin** [comment]
脑图创建用例的顺序是按照节点产生的顺序来排序的，节点产生后再修改顺序并不能改变保存次序。另外创建用例后可以在列表页调整排序，脑图的顺序会和列表保持一致

**Comment by lrh1234** [comment]
@youliyuan-fit2cloud 你好，我现在用1.20版本，该问题还是存在，用例保存之后，顺序就乱了

**Comment by youliyuan-fit2cloud** [comment]
> @youliyuan-fit2cloud 你好，我现在用1.20版本，该问题还是存在，用例保存之后，顺序就乱了

我们再优化下，可以先在列表页排序，脑图和列表排序是一致的

**Comment by lrh1234** [comment]
大概什么时候能优化好呢？我们这边比较着急这个功能，列表没有脑图方便写，对我们造成了比较大的困扰，辛苦大佬了

**Comment by lrh1234** [comment]
> 

@youliyuan-fit2cloud  你好，辛苦看看什么时候能优化好呢，我们这边比较着急这个功能呢？列表还是没有脑图方便的写东西

**Comment by youliyuan-fit2cloud** [comment]
> > 
> 
> @youliyuan-fit2cloud 你好，辛苦看看什么时候能优化好呢，我们这边比较着急这个功能呢？列表还是没有脑图方便的写东西

好消息，今天发布的1.20.3-lts已经修复了，升级一下
