### ISSUE TITLE
[BUG] 将一个带有 “”接口用例且接口用例里面有环境配置 “” 的接口 导出来，然后 导入另外一个项目，再创建接口用例，配置环境，有时候出现新接口用例使用的是旧的环境，根本原因是  接口导出的竟然把 对应用例的环境 ID给导出来。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12267]
### MeterSphere 版本

1.19.0

### 使用外置数据库

否

### 问题描述

[BUG] 将一个带有 “”接口用例且接口用例里面有环境配置 “” 的接口 导出来(metersphere格式)，然后 导入另外一个项目，再创建接口用例，配置环境，有时候出现新接口用例使用的是旧的环境，根本原因是  接口导出的竟然把 对应用例的环境 ID给导出来。

![1648863107](https://user-images.githubusercontent.com/76033005/161360541-8ed0be5c-9e19-42f6-b637-2f884b955f9c.png)

让开发在导出接口的时候 不要把 接口 下面的用例 所 用的环境ID也给导出来，不然会有奇奇怪怪的错误，导出接口定义成metersphere格式，不应该把 接口下面的 用例的 环境id带出来。

如果不明白该缺陷，请联系 王进 jin.wang@fit2cloud.com，或者 客户 Xin.zhang@ebaotech.com

### 重现步骤

[BUG] 将一个带有 “”接口用例且接口用例里面有环境配置 “” 的接口 导出来(metersphere格式)，然后 导入另外一个项目，再创建接口用例，配置环境，有时候出现新接口用例使用的是旧的环境，根本原因是  接口导出的竟然把 对应用例的环境 ID给导出来。

![1648863107](https://user-images.githubusercontent.com/76033005/161360541-8ed0be5c-9e19-42f6-b637-2f884b955f9c.png)

让开发在导出接口的时候 不要把 接口 下面的用例 所 用的环境ID也给导出来，不然会有奇奇怪怪的错误，导出接口定义成metersphere格式，不应该把 接口下面的 用例的 环境id带出来。

如果不明白该缺陷，请联系 王进 jin.wang@fit2cloud.com，或者 客户 Xin.zhang@ebaotech.com

![02b8383e6bbc72615399f7a548b7fac](https://user-images.githubusercontent.com/76033005/161360687-7692c2a9-ea58-47d9-aa12-9725dba6efa8.png)

### 期待的正确结果

导出接口定义成metersphere格式，不应该把 接口下面的 用例的 环境id带出来。

**Comment by youliyuan-fit2cloud** [comment]
fixed on v1.19.2
