### ISSUE TITLE
[BUG]【跪求1.7版本能够解决】sql类型的请求选择数据源保存后无法成功保存，点击编辑后查看为空，需要再次选择。导致导入场景后无法直接执行场景

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#1226]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.6.1-3cb27580
**Bug 描述**
简要描述您碰到的问题
sql类型的请求选择数据源保存后无法成功保存，点击编辑后查看为空，需要再次选择。导致导入场景后无法直接执行场景
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
数据源可以成功保存，无需再次点击编辑进行选择
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/77233754/105141618-65d7ca80-5b34-11eb-9519-ca654495b5ef.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 版本已修复该问题。
