### ISSUE TITLE
[BUG]msctl upgrade 和 msctl upgrade v1.XX 报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12271]
### MeterSphere 版本

v1.19

### 使用外置数据库

否

### 问题描述

msctl upgrade 和 msctl upgrade v1.XX 报错

### 重现步骤

1.msctl upgrade 在线升级 获取不到域名
![image](https://user-images.githubusercontent.com/30038088/161362634-1974623f-31b2-4544-bb43-7588d823f2b1.png)
2.msctl upgrade v1.19.1 下载的文件有误 ，文件大小为0
<img width="689" alt="image" src="https://user-images.githubusercontent.com/30038088/161362699-a603441b-2b38-41f3-a914-530dffe0450f.png">

**Comment by youliyuan-fit2cloud** [comment]
1.17以上版本升级到最新的吗？如果还是有问题，可以下载在线安装的包，手动升级 
例如：wget https://github.com/metersphere/metersphere/releases/download/v1.19.1/metersphere-online-installer-v1.19.1.tar.gz
tar zxvf metersphere-online-installer-v1.19.1.tar.gz
cd metersphere-online-installer-v1.19.1
/bin/bash install.sh
