### ISSUE TITLE
[BUG]接口测试模块，JSON请求体是大报文时（报文见附件），选择JSON-SCHEMA模式系统会卡死

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#12273]
### MeterSphere 版本

1.19.0

### 使用外置数据库

否

### 问题描述

接口测试模块，JSON请求体是大报文时（报文见附件），选择JSON-SCHEMA模式系统会卡死

### 重现步骤

使用附件中的报文做为请求体，选择JSON-SCHEMA模式

### 期待的正确结果

选择JSON-SCHEMA模式后系统正常运行
<img width="758" alt="1" src="https://user-images.githubusercontent.com/83771182/161363726-95baa198-1ad5-4917-ae20-f7d7ee1a576e.png">
<img width="476" alt="2" src="https://user-images.githubusercontent.com/83771182/161363730-be80139b-ca43-45d2-87f1-a4396d5f23a7.png">

**Comment by yaoyi111** [comment]
[acctgSystemId.docx](https://github.com/metersphere/metersphere/files/8401701/acctgSystemId.docx)

**Comment by youliyuan-fit2cloud** [comment]
fixed on v1.19.2
