### ISSUE TITLE
[BUG]接口自动化用例取消了原场景环境，数据库配置未启用新环境地址

### ISSUE THREAD

**Issue by Wind-Liv5** [metersphere/metersphere#12274]
### MeterSphere 版本

v1.19.1-4fb56789

### 使用外置数据库

否

### 问题描述

接口自动化用例取消了原场景环境，数据库配置未启用新环境地址

### 重现步骤

![image](https://user-images.githubusercontent.com/70939960/161363993-cfc5a322-755d-40a6-8d05-fc9ad3e2d67f.png)

如上配置，数据库配置还是引用原项目环境配置

### 期待的正确结果

取消原环境后，应该默认取当前项目环境数据库配置

**Comment by youliyuan-fit2cloud** [comment]
fixed on v1.19.2
