### ISSUE TITLE
[FEATURE]通过上传插件，WebSocket协议等暂不支持性能测试，请修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#12272]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

通过上传插件，使用的MQTT、WebSocket协议等暂不支持性能测试，请修复

### 重现步骤

配置MQTT接口自动化测试用例，执行成功后，转为性能测试用例，并执行性能测试

### 期待的正确结果

性能测试执行成功

### 附加信息

![6dd122e23a5924f241e1c3f05fdc32f](https://user-images.githubusercontent.com/92150453/161363322-e4b1be00-d1e3-4d1b-8fa6-d5d3087bf2b1.png)
![68784e45413561ed8b883f305ac8dd7](https://user-images.githubusercontent.com/92150453/161363325-24078d88-7584-4cb6-9305-3e485aa6901e.png)

**Comment by Wind-Liv5** [comment]
https://mp.csdn.net/mp_blog/creation/editor/120510507
可以通过把JAR包上传到jmeter 容器目录即可临时使用，每次升级 重启容器需要重新复制一下

**Comment by sageonedream** [comment]
这只是临时处理办法，需要保持和我们http接口转性能一样才行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月2日(周六) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]通过上传插件，使用的MQTT、WebSocket协议等暂不支持性能测试，请修复 (Issue #12272)




 
https://mp.csdn.net/mp_blog/creation/editor/120510507
 可以通过把JAR包上传到jmeter 容器目录即可临时使用，每次升级 重启容器需要重新复制一下

**Comment by Wind-Liv5** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我有事不在，无法亲自回复您的邮件。我将在阅读后，尽快给您回复。

**Comment by youliyuan-fit2cloud** [comment]
MQTT支持转性能测试，但是需要用户自己吧jar包上传到性能测试用例里面
WebSocket协议暂不支持转性能测试

**Comment by Wind-Liv5** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我有事不在，无法亲自回复您的邮件。我将在阅读后，尽快给您回复。
