### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ayayayayayayayayayaysdfklsldfsdkjflsdf** [metersphere/metersphere#12270]
### MeterSphere 版本

16.5

### 请描述您的需求或者改进建议

接口测试-用例-如果原来的“部分”用例要迁移到新接口，只能重新添加，很不友好

### 请描述你建议的实现方案

如果可以只改一下所属接口，或者可以复制用例到新接口，是不是更合理？

**Comment by ayayayayayayayayayaysdfklsldfsdkjflsdf** [comment]
接口测试-用例-如果原来接口的“部分”用例要迁移到新接口，只能重新添加，很不友好

**Comment by ayayayayayayayayayaysdfklsldfsdkjflsdf** [comment]
接口测试-用例-如果原来的“部分”用例要迁移到新接口，只能重新添加，很不友好

**Comment by Hyyfit** [comment]
已规划，待排期
