### ISSUE TITLE
[BUG] 断言文字不能全选

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12290]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

断言文字不能全选，使用不便

### 重现步骤

在接口用例中添加断言，输入表达式，由于拖动导致输入框不能全选，全选输入框会拖动整个步骤

### 附加信息

<img width="879" alt="image" src="https://user-images.githubusercontent.com/36387811/161373383-256f2085-5b00-4844-8494-bb0e9276cb3f.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.2-lts中已修复
