### ISSUE TITLE
增加全局变量功能[FEATURE]

### ISSUE THREAD

**Issue by sanxun0325** [metersphere/metersphere#123]
**请描述您的需求或者改进建议.**
增加类似于postman 中的全局变量功能，变量可以作用在请求中，例如路径，参数，请求体。

**请描述你建议的实现方案**
可以包装 接口返回的提取功能，将提取功能中的变量提出来，可展示 可维护。

参考：
![image](https://user-images.githubusercontent.com/28588342/87409116-13eb4080-c5f7-11ea-8064-4f40e0c5d660.png)

**Comment by luty2018** [comment]
1.1版本已支持 请更新体验
