### ISSUE TITLE
[BUG]性能测试添加自定义指标 监控，点击 自定义指标 的监控 没反应

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12303]
### MeterSphere 版本

v1.19

### 使用外置数据库

否

### 问题描述

性能测试添加自定义指标 监控，点击 自定义指标 的监控 没反应

### 重现步骤

1.性能测试场景中，点击高级配置 ，添加 自定义监控指标和pmsql ,点击 执行测试
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/30038088/161379309-c677f63c-e8a4-476c-b64b-fd2640f64850.png">

2.性能测试报告。监控页面，选择 自定义监控的tab, 点击 没反应
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/30038088/161379292-2d2b8ecb-b544-455c-93d0-d8d9f0a99ee3.png">

**Comment by youliyuan-fit2cloud** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
