### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dongyangguo2021** [metersphere/metersphere#12314]
### MeterSphere 版本

1.18.3

### 请描述您的需求或者改进建议

1.用例评审-评论输入框颜色不明显，不易找到;
2.导出报告支持word格式;
3.评审未通过的测试用例也可以执行，没有强关联性，只是形式性评审;
4.项目设置--操作日志，日期查询控件不友好，查询当天的记录还需要手动输入;

**Comment by Hyyfit** [comment]
感谢建议，后续会对使用做一个大的优化。
