### ISSUE TITLE
Mac安装部署不成功

### ISSUE THREAD

**Issue by zoushibo123** [metersphere/metersphere#12319]
### 请描述您的问题

mac环境， install.sh注释掉docker-compose 版本比较，可以拉取镜像了，但还是会报错

bogon:metersphere-offline-installer-v1.19.1-arm64 root# sh install.sh
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
存在已安装的 MeterSphere, 安装目录为 /opt/metersphere, 执行升级流程
-e [MeterSphere Log]: 拷贝安装文件到目标目录 
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
-e [MeterSphere Log]: ======================= 开始安装 ======================= 
-e [MeterSphere Log]: 检测到 Docker 已安装，跳过安装步骤 
-e [MeterSphere Log]: 启动 Docker  
install.sh: line 72: service: command not found
-e [MeterSphere Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
chmod: /opt/metersphere/conf/my.cnf: No such file or directory
chmod: -R: No such file or directory
-e [MeterSphere Log]: 加载镜像 
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.3-ms4-jdk8
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/kafka:2
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v1.19.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-data-streaming:v1.19.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.19.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/mysql:5.7.33
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/prometheus:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/redis:6.2.6
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/standalone-chrome:4.1.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/zookeeper:3
-e [MeterSphere Log]: 启动服务 

stat /opt/metersphere/docker-compose-base.yml: no such file or directory

stat /opt/metersphere/docker-compose-base.yml: no such file or directory

stat /opt/metersphere/docker-compose-base.yml: no such file or directory
-e ======================= 安装完成 =======================

-e 请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
-e 您可以使用命令 'msctl status' 检查服务运行情况.

**Comment by liuruibin** [comment]
我们支持的arm版本只是linux-arm版本，mac m1 没有进行适配

**Comment by zoushibo123** [comment]
> 我们支持的版本只是linux-arm，mac m1没有进行版本支持

哦哦，好吧，请问以后有计划发布OS版本吗。

**Comment by Hyyfit** [comment]
暂时没有规划。
