### ISSUE TITLE
[BUG]共享cookie功能无效

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#12325]
### MeterSphere 版本

1.18.2，1.19.1

### 使用外置数据库

是

### 问题描述

“共享cookie”功能已开，前一个接口生成响应头生成cookie，无法带入后一个接口

### 重现步骤

复刻1.17.3版本可正常使用的接口自动化用例（oidc鉴权）
cookie无法自动带入下一个接口。

**Comment by zyyfit** [comment]
没有复现这个问题，方便把你的场景导出来给我们看看吗

**Comment by warmmilk** [comment]
已升级到1.19.3，无此问题
