### ISSUE TITLE
[QUESTION]如果在前置脚本中修改请求的url呢？

### ISSUE THREAD

**Issue by 277169949** [metersphere/metersphere#12323]
### 请描述您的问题

目前，执行用例只能通过选择环境，但是环境中的url不能动态设置变量，文档中也没看到url会读取哪个变量？
有些场景需要在运行前动态获取url，这种要怎么处理呢？

**Comment by Hyyfit** [comment]
不太明白你的描述。
目前是支持提取变量，也支持${}的方式引用变量。

**Comment by 277169949** [comment]
是支持变量提取，但是提取之后只能动态指定ip，不能动态指定端口，动态指定端口的话，拿到的值是一个数组形式的拼接到了url那里。

**Comment by Hyyfit** [comment]
提取的时候，是不是勾选了匹配多条？匹配多条是会返回一个数组的。
有没有截图，贴一下，这样描述很难理解。
或者你在不在我们的交流群里，你可以联系一下我。看一下具体的问题。
<img width="309" alt="image" src="https://user-images.githubusercontent.com/95834771/162113707-1497d3a9-f72e-42a3-8713-a55c0c82ab7c.png">
