### ISSUE TITLE
[BUG] 关联用例页面 左边的树状，还有列表页，有性能问题，需要改成懒加载

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12335]
### MeterSphere 版本

1.19.1

### 使用外置数据库

是

### 问题描述

![Uploading 1649217912.png…]()

### 重现步骤

随着东区ms数据量增加，关联用例 页面 左边的 树状 目录树，还有右边的列表，性能越来越差

需要开发同学改成懒加载，我看了列表页，一次把所有 场景，接口用例 都 load出来了。

王进

**Comment by ltfit** [comment]
有多大的数据量呢。图片看不到
