### ISSUE TITLE
[BUG] 东区 demo 环境 api列表页一直转圈圈，提示有错误

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12330]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

![api 列表](https://user-images.githubusercontent.com/76033005/161870825-036a3121-0fc9-4a6e-a407-24943fa0a059.png)
![Uploading 控制台错误.png…]()

### 重现步骤

请看问题截图

**Comment by youliyuan-fit2cloud** [comment]
报错的图片 看不到啊，重新上传看看？

**Comment by zrfit** [comment]
是升级后造成的吗？清空本地缓存试下。
