### ISSUE TITLE
[BUG]缺陷关联的用例数一直是 0

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12347]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

缺陷关联了用例，在缺陷管理列表查看缺陷用例关联数，一直为 0

### 重现步骤

1.创建一个测试计划
2.测试计划关联功能用例
3 执行测试计划，添加缺陷
4 查看缺陷管理列表缺陷的用例数

### 附加信息
![1649236724991](https://user-images.githubusercontent.com/36387811/161941994-98dfaa8a-1787-47d0-9d02-9a67d9212e93.jpg)

_No response_

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.19.2已修复
