### ISSUE TITLE
[BUG]测试计划统计场景用例数一直为 0

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12341]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

测试计划里添加场景用例，在测试计划列表查看到场景用例数为 0

### 重现步骤

1.创建一个测试计划
2.往创建的测试计划添加场景用例
3.在测试计划列表查看场景用例数为 0

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.19.2已修复
