### ISSUE TITLE
[BUG]場景變量設置一個變量值為空值時，通過vars.get獲取到的是null?

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12350]
### MeterSphere 版本

V1.18.3

### 使用外置数据库

否

### 问题描述

在場景變量中設置一個變量，值默認不填寫(空值)，在腳本裡面通過vars.get獲取值為null

### 重现步骤

1.設置變量a，值默認空
2.在腳本裡面獲取變量a的值

### 期待的正确结果

獲取值為空，不應該為null，通過JMETER測試結果是非null，返回就是空值
![image](https://user-images.githubusercontent.com/37204403/161951673-d3c5083d-cd8e-41d3-96ca-dcb87b58b8db.png)

### 附加信息

![image](https://user-images.githubusercontent.com/37204403/161951475-c8fafb51-7dfd-4b3c-a2bf-8183ec59118b.png)

**Comment by zrfit** [comment]
最新版本v1.20已解决该问题
