### ISSUE TITLE
[BUG]重要企业客户，在接口定义里面，post请求，请求体 选择 form-data, 详细字段是data={ head{.....}, body{.....}}，data字段对应的值是json格式，内容非常大

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12351]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

重要企业客户，在接口定义里面，post请求，请求体 选择 form-data, 详细字段是data={ head{.....}, body{.....}}，data字段对应的值是json格式，内容非常大，在 值框里 编辑 实在太不方便了。

为了方便内容编辑，点json ，然后开启json schema编辑 ，在json视图编辑 后的内容 保存后，再切换 到form-data视图，

form-data视图里面的内容，没有 和 json视图里面的内容 同步。 

整个企业客户团队开发人员 都在 ms里面 维护 接口。

### 重现步骤

重要企业客户，在接口定义里面，post请求，请求体 选择 form-data, 详细字段是data={ head{.....}, body{.....}}，data字段对应的值是json格式，内容非常大，在 值框里 编辑 实在太不方便了。

为了方便内容编辑，点json ，然后开启json schema编辑 ，在json视图编辑 后的内容 保存后，再切换 到form-data视图，

form-data视图里面的内容，没有 和 json视图里面的内容 同步。 

整个企业客户团队开发人员 都在 ms里面 维护 接口。

**Comment by luty2018** [comment]
设计如此
