### ISSUE TITLE
[BUG]场景自动化定时任务报告，用例数显示不准，失败用例丢失

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#12368]
### MeterSphere 版本

1.16.6

### 使用外置数据库

是

### 问题描述

场景自动化定时任务75条用例，执行完成，查看报告，失败两条用例无显示

### 重现步骤

场景自动化定时任务75条用例，执行完成，查看报告，失败两条用例无显示

### 附加信息

![image](https://user-images.githubusercontent.com/20641051/162106690-d227f89e-5152-401c-95db-18f4d20d96aa.png)

**Comment by zrfit** [comment]
您好，场景用例数量确认是75吗？75是总用例数 ，是否还包含单接口用例数？
