### ISSUE TITLE
[BUG]在接口名稱裡面使用變量未生效

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12373]
### MeterSphere 版本

V1.18.3

### 使用外置数据库

否

### 问题描述

如下圖所示：接口名稱使用變量，執行測試報告裡面展示的 步驟中 仍展示變量
![image](https://user-images.githubusercontent.com/37204403/162115106-d8c2d5ab-5557-46cc-bc93-ad53871ea38f.png)

### 重现步骤

無

### 期待的正确结果

以前是可以正常展示 變量值 在測試報告步驟中

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，请先确认一下这个变量是否有值

**Comment by SloanGao** [comment]
> 你好，没有复现，请先确认一下这个变量是否有值

你好，變量是有值的，如下場景，直接在場景變量中定義變量也是沒有：
![1649384280(1)](https://user-images.githubusercontent.com/37204403/162350265-3e690c47-7887-4840-9395-0cd25edb69dc.png)
![1649384356(1)](https://user-images.githubusercontent.com/37204403/162350313-42e7ece8-bfc8-452e-835c-41e04f10f0a7.png)

**Comment by SloanGao** [comment]
補充說明，我上面有變量的測試步驟是從其他地方引用過來的，變量未生效(早期版本是正常的)，現在以前的這種場景用例變量都沒有將值帶過來。
另外單獨驗證在一個場景裡面添加請求，名稱包含變量是OK的

**Comment by SloanGao** [comment]
補充說明，我上面有變量的測試步驟是從其他地方引用過來的，變量未生效(早期版本是正常的)，現在以前的這種場景用例變量都沒有將值帶過來。
另外單獨驗證在一個場景裡面添加請求，名稱包含變量是OK的

**Comment by youliyuan-fit2cloud** [comment]
方便把你这个场景导出来吗？我们还是没有复现呢。
一----“現在以前的這種場景用例變量都沒有將值帶過來。”----->以前的这个场景指的是哪个MeterSphere版本的数据呢？我们看看是不是旧数据的问题

**Comment by SloanGao** [comment]
> 方便把你这个场景导出来吗？我们还是没有复现呢。 一----“現在以前的這種場景用例變量都沒有將值帶過來。”----->以前的这个场景指的是哪个MeterSphere版本的数据呢？我们看看是不是旧数据的问题

如下圖所示：
我的意思是第二張圖里面 被引用的場景名稱裡面的變量未生效，以前場景名稱和請求接口名稱變量是都生效的
![image](https://user-images.githubusercontent.com/37204403/164586222-8c4d8da1-377f-4af4-acda-a542013d836b.png)
![image](https://user-images.githubusercontent.com/37204403/164586407-d6023fa8-5af7-414e-9cf9-0760dab344e0.png)

**Comment by youliyuan-fit2cloud** [comment]
> > 方便把你这个场景导出来吗？我们还是没有复现呢。 一----“現在以前的這種場景用例變量都沒有將值帶過來。”----->以前的这个场景指的是哪个MeterSphere版本的数据呢？我们看看是不是旧数据的问题
> 
> 如下圖所示： 我的意思是第二張圖里面 被引用的場景名稱裡面的變量未生效，以前場景名稱和請求接口名稱變量是都生效的 ![image](https://user-images.githubusercontent.com/37204403/164586222-8c4d8da1-377f-4af4-acda-a542013d836b.png) ![image](https://user-images.githubusercontent.com/37204403/164586407-d6023fa8-5af7-414e-9cf9-0760dab344e0.png)

了解了，最新版本不支持场景的名称 是变量。。。你说之前好使是哪个版本呢？

**Comment by SloanGao** [comment]
> 了解了，最新版本不支持场景的名称 是变量。。
具体那个版本也不记得了，之前用是一直都可以的，后面升级到1.18.3后发现没有了
