### ISSUE TITLE
[BUG]接口定义，使用批量添加的参数，执行时url拼接的参数都会添加上换行符

### ISSUE THREAD

**Issue by howrain** [metersphere/metersphere#12376]
### MeterSphere 版本

v1.19.1

### 使用外置数据库

是

### 问题描述

从postman复制出来的Query Params
在接口定义或者创建接口case使用批量添加，执行后，在响应体中url参数的拼接会带上换行符

### 重现步骤

actualIdSY:101315632152
actualIdJQ:
businessNo:6605212022110104000021
productCode:0521
outputType:pdf
printType:Pt
solutionId:undefined
visaCode:undefined
syFF:0
platePrintType:00

接口定义中批量添加上面的参数，或者从postman中复制出Query Params的key:value批量添加

### 期待的正确结果

拼接的url不带换行符

### 附加信息

![image](https://user-images.githubusercontent.com/29175296/162131058-a90aac24-02f4-4c2b-a7d7-deef0c9189e3.png)

![image](https://user-images.githubusercontent.com/29175296/162131282-79479ffa-0318-423a-8091-4387169d7345.png)

![image](https://user-images.githubusercontent.com/29175296/162131807-1a898bae-eb10-45ca-87e7-574f9b0cee06.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，方便把这个接口导出来吗？

**Comment by howrain** [comment]
[Metersphere_Api.zip](https://github.com/metersphere/metersphere/files/8440833/Metersphere_Api.zip)
只能上传zip了，解压看下吧，我在json中看value也是包含/r的
![image](https://user-images.githubusercontent.com/29175296/162150973-c26ff6ff-2649-4e8d-b541-e08054e49c3f.png)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题

**Comment by z2x-code** [comment]
> 即将发布的v1.20.0中已修复该问题

v2.3.0-f7d4cc4e 版本中该问题又出现了，从postman的body里复制过来的参数，在metersphere批量添加后，参数后默认被加上了 \r
