### ISSUE TITLE
[BUG]postman文件上传，导入失败，提示插入DB，超过path最长长度限制

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#1237]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6

postman文件上传，导入失败，提示插入DB，超过path最长长度限制

**截图**
![image](https://user-images.githubusercontent.com/17491657/105440995-989fd100-5ca2-11eb-9458-af67c0e67972.png)

**Comment by wangzhen-fit2cloud** [comment]
@AgAngle 建星确认下这个

**Comment by wangzhen-fit2cloud** [comment]
你好，是否可以提供下该 postman 文件？

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
