### ISSUE TITLE
[BUG]接口自动化中导入JMX文件生成场景用例时，自定义请求未能做到url补全，在选择运行环境并勾选引用环境时，api_url参数被清空，功能实现有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#12382]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

接口自动化中导入JMX文件生成场景用例时，自定义请求未能做到url补全，在选择运行环境并勾选引用环境时，api_url参数被清空，功能实现有误，请修改

### 重现步骤

1.在MS中导入jmx文件，生成接口自动化用例，查看生成的自定义请求url是否完整，包含http地址；
2.若未包含url地址，在配置运行环境后，勾选引用环境，查看原api_url是否仍正常显示；

### 期待的正确结果

1.在jmx文件中有配置http信息时，生成的自定义请求，能获取http信息，进行url补全；（建议以此种方式进行实现）
2.勾选引用环境时，原api_url能正常显示；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/162139254-213b7e2a-6964-4435-bb13-239cb1165f5c.png)
![image](https://user-images.githubusercontent.com/92150453/162139316-78dce340-eaa9-493b-81ca-ff48186cbb3e.png)

**Comment by sageonedream** [comment]
[接口导入验证1.txt](https://github.com/metersphere/metersphere/files/8440407/1.txt)
(备注：需更改后缀格式为jmx)

**Comment by zrfit** [comment]
1、导入jmx文件后，自定义请求未能做到url补全 这个没看明白 jmx文件导入jmeter后本身就没看到对应的域名地址信息 且路径为参数 ，导入到ms后也显示的是jmx文件对应的数据
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/99731894/162381073-1de1ff3d-2687-411a-af67-845d5a0148ab.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/162381291-f415f8b6-62ba-4227-8263-fcb8cbaf5d83.png">
如果jmx文件中含有协议，服务器端口信息 则导入ms中url数据是补全显示的
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/99731894/162386026-c8082c03-924c-46eb-b688-2da336dfc84a.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/99731894/162386311-0f73d867-7326-4190-b39b-10994782b8e7.png">
2、在选择运行环境并勾选引用环境时，api_url参数被清空 设计如此
选择环境-引用环境后-域名地址自动填充  路径地址需要根据需要自行填写  
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/99731894/162382584-e8e32204-e7ab-4493-9117-c6baef8a6365.png">

**Comment by sageonedream** [comment]
经验证为非问题，验证不充分导致
