### ISSUE TITLE
[FEATURE]接口测试响应体固定宽度展示支持灵活配置，响应体支持字段筛选

### ISSUE THREAD

**Issue by jiming-liu** [metersphere/metersphere#12395]
### MeterSphere 版本

v19.1

### 请描述您的需求或者改进建议

1. 这块区域能否调整，自定义宽度或调大宽度，就这么一小块看起来很费劲
2. 响应里能否增加字段的筛选，返回数据较多时要找很久才能找到对应字段信息
3. 
![image](https://user-images.githubusercontent.com/43609732/162353105-9597ab73-ba1d-44a2-8c20-91a15a33edf6.png)

### 请描述你建议的实现方案

1. 这块区域能否调整，自定义宽度或调大宽度，就这么一小块看起来很费劲
2. 响应里能否增加字段的筛选，返回数据较多时要找很久才能找到对应字段信息
![Uploading image.png…]()

**Comment by Hyyfit** [comment]
感谢建议，已规划，待排期
