### ISSUE TITLE
[BUG]部分步驟未執行

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12397]
### MeterSphere 版本

V1.18.3

### 使用外置数据库

否

### 问题描述

測試場景，多個步驟時，出現部分步驟未執行情況
控制台報如下信息：
![1649389387(1)](https://user-images.githubusercontent.com/37204403/162358419-90f50232-0d31-4dec-b414-5ed622afc044.png)
![1649389417(1)](https://user-images.githubusercontent.com/37204403/162358469-c12a751e-ac84-4fab-84ba-c7352bda8ce5.png)

### 重现步骤

無

**Comment by youliyuan-fit2cloud** [comment]
建议升级到最新版本1.19.2试试吧？
