### ISSUE TITLE
[BUG]数据库连接不上

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12392]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

正常输入数据库连接相关信息，报错，同样信息在jmeter中是可以正常连接

### 重现步骤

环境配置中，正常输入数据库连接相关信息，点击校验

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/162199660-6d8d2f27-18bf-49fa-b0dc-db9b83aeb1cb.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？

**Comment by wszbc** [comment]
> 你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？

5.6.29-mycat-1.6.7.1-release-20190627191042 版本是这个，url和密码是对的我直接在jmeter工具里是可以连上的

**Comment by wszbc** [comment]
> > 你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？
> 
> 5.6.29-mycat-1.6.7.1-release-20190627191042 版本是这个，url和密码是对的

**Comment by youliyuan-fit2cloud** [comment]
> > > 你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？
> > 
> > 
> > 5.6.29-mycat-1.6.7.1-release-20190627191042 版本是这个，url和密码是对的

我们支持mysql 5.7 以上呢 ……

**Comment by wszbc** [comment]
> > > > 你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？
> > > 
> > > 
> > > 5.6.29-mycat-1.6.7.1-release-20190627191042 版本是这个，url和密码是对的
> 
> 我们支持mysql 5.7 以上呢 ……

那我可以通过上传低版本连接的jar包解决这个问题么？

**Comment by youliyuan-fit2cloud** [comment]
> > > > > 你好，我们没有复现，先确认下你的这个mysql 版本是多少？url和密码是正确的吧？
> > > > 
> > > > 
> > > > 5.6.29-mycat-1.6.7.1-release-20190627191042 版本是这个，url和密码是对的
> > 
> > 
> > 我们支持mysql 5.7 以上呢 ……
> 
> 那我可以通过上传低版本连接的jar包解决这个问题么？

不得行....
