### ISSUE TITLE
[QUESTION]请问导入jmx文件后，测试状态一直是starting该如何排查

### ISSUE THREAD

**Issue by VanLiuZhi** [metersphere/metersphere#1239]
dockers的日志也没找到什么报错

jmx我用jmeter可以打开，也可以跑压测。非要说问题的话，就是打开会弹窗提示 Unexpected error - see log for details

但是不影响jmeter的使用

![image](https://user-images.githubusercontent.com/22883555/105457602-0d363800-5cc2-11eb-85d7-36b0e9f646a8.png)

请问我该如何排查问题，docker容器也没什么报错，各个服务都查看了

**Comment by wangzhen-fit2cloud** [comment]
你好，请检查下系统设置中的站点 URL 有没有配置，启动性能测试时需要通过该地址下载资源，测试资源池中的节点需要能访问到该 URL
