### ISSUE TITLE
[BUG] 版本1.19 。功能：测试跟踪-用例评审-评审结果筛选条件 切换页面后重新进入 筛选条件前端传值review_status没有进行初始化

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#12393]
### MeterSphere 版本

版本1.19

### 使用外置数据库

否

### 问题描述

在测试跟踪下的用例评审功能的评审结果，勾选过筛选结果例如：未评审。关闭用例评审页面切换到其他页面例如：功能用例页面后在返回之前的用例评审页面，出现筛选结果选项没有初始化带着之前的数据。包括切换项目也出现直接显示筛选后的用例。

### 重现步骤

1.进入到用例评审页面
2勾选评审结果：未评审
3.切换到其他页面：功能用例
4.点击用例评审切换回评审列表页面
5.评审结果仍显示之前勾选过的结果
6.刷新页面 f5这个筛选数据才会被清空

### 期待的正确结果

重新进入到用例评审列表页面数据应该初始化、
review_status: ["Pass"]
0: "Pass"
前端字段参数参入应该为空

### 附加信息

![image](https://user-images.githubusercontent.com/101856439/162350145-3856b889-54f9-47b3-9f9c-ccbc8f980bc0.png)

![image](https://user-images.githubusercontent.com/101856439/162350055-01784586-b39d-4f0d-83bc-d39470fe8f5a.png)

**Comment by ltfit** [comment]
这个后续优化下

**Comment by ltfit** [comment]
这个目前的交互就是这样的
