### ISSUE TITLE
[BUG] 1.19.2, 手动指定Content-Type为multipart/form-data;boundary=OVQ.....  ，postman里实测结果是手动设定的boundary会覆盖自动生成，ms里面是 “即使手动指定boundary，但是发出去的请求里依然是自动产生的boundary”

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12394]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

[BUG] 1.19.2, 手动指定Content-Type为multipart/form-data;boundary=OVQ.....  ，postman里实测结果是手动设定的boundary会覆盖自动生成，ms里面是 “即使手动指定boundary，但是发出去的请求里依然是自动产生的boundary”

下图为ms实测结果：
![image](https://user-images.githubusercontent.com/76033005/162352293-1c8bd163-d5aa-4326-b280-3e86148fc84e.png)

### 重现步骤

重现步骤，请看下面这个截图，应该就完全明白了。

![image](https://user-images.githubusercontent.com/76033005/162352410-c48905b0-0e12-4af6-b315-916df08e2c07.png)

### 期待的正确结果

当用户手动在header里Content-type指定multipart/form-data和boundary字符串时，应该用手动设定的boundary，而不是MS自动生成的boundary。

如有任何问题可以联系 Xin.zhang@ebaotech.com，或jin.wang@fit2cloud.com

**Comment by zyyfit** [comment]
首先，我们是使用的jmeter执行的，跟 jmeter 的一致性更高一些，我在jmeter里测试了一下，和我们系统的结果是一致的
其次，如果使用form data 格式的话，请求头里不需要填写content-type。在请求体里填就可以了
![图片](https://user-images.githubusercontent.com/73461316/162678451-049b860c-29ed-40c3-9f73-08681a1e0855.png)
