### ISSUE TITLE
[FEATURE]功能用例编写后能够改变顺序

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12396]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

功能用例编写新用例自动到最后一行，希望可以改变顺序，在测试计划中进行顺序改变有点鸡肋，因为计划还是要在总用例里面去找，总用例顺序存在问题的话，计划中用例多了改变顺序找起来也会很麻烦

### 请描述你建议的实现方案

功能用例中能够像测试计划中一样随意拖动用例的位置改变顺序

**Comment by Hyyfit** [comment]
您好，现在在功能用例列表是支持拖动排序的。注意ID列表不要选择排序。
功能用例新增通常是新增到第一行，功能用例拖动排序后，会同步到测试计划中的。
<img width="434" alt="image" src="https://user-images.githubusercontent.com/95834771/162898475-ccaf3745-c096-4b9e-ae65-72fe108a5428.png">

**Comment by wszbc** [comment]
> 您好，现在在功能用例列表是支持拖动排序的。注意ID列表不要选择排序。 功能用例新增通常是新增到第一行，功能用例拖动排序后，会同步到测试计划中的。 <img alt="image" width="434" src="https://user-images.githubusercontent.com/95834771/162898475-ccaf3745-c096-4b9e-ae65-72fe108a5428.png">

![image](https://user-images.githubusercontent.com/40912823/163344507-a609240d-250d-444e-b428-1616c01ffb08.png)
我为啥没有你这个位置拖动的控件，请问下怎么设置？
