### ISSUE TITLE
[FEATURE]新增测试用例添加tag功能

### ISSUE THREAD

**Issue by techzealot** [metersphere/metersphere#124]
**请描述您的需求或者改进建议.**
测试用例标记多个tag可以方便的按照tag进行分组查询，以及根据多个tag生成某个功能模块的新用例组

**请描述你建议的实现方案**
新增tag表，新增用例-tag关联表

**Comment by youliyuan-fit2cloud** [comment]
您好！v1.7版本已实现该功能，请持续关注～
