### ISSUE TITLE
[BUG]1.19.2，已复测，post请求，请求体json类型，当属性名称为@type，值为正常的字符串，保存出现 http 500

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12403]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

下面这种情况可以保存成功：
![1649394052(1)](https://user-images.githubusercontent.com/76033005/162368055-b34ea862-a48e-415b-971d-51bd3377ea09.png)

但是 下面 这种情况保存 出现http 500错误
![1649394128(1)](https://user-images.githubusercontent.com/76033005/162368154-550b96b0-2936-47b3-bca1-cdcf3a442c37.png)

ms成功组已复测，问题属实

### 重现步骤

复测步骤简单，参照问题描述中的截图。
1. 接口自动化新建一个场景。
2. 然后添加一个post请求，json请求体
3. 参照问题描述里的截图输入@type名称，以及对应值，保存

### 附加信息
如有任何问题可以联系 [Xin.zhang@ebaotech.com](mailto:Xin.zhang@ebaotech.com)，或[jin.wang@fit2cloud.com](mailto:jin.wang@fit2cloud.com)

_No response_

**Comment by youliyuan-fit2cloud** [comment]
v1.19.3已修复

**Comment by xiaomeinvG** [comment]
由于fastjson里面@type为关键字，暂不支持@type的写法，我们正在等待fastJson的解决

**Comment by fit2-zhao** [comment]
@35plus  改动略大暂时不会合并到小版本，请暂且忍忍，测试好了会放到1.20 里面解决。
