### ISSUE TITLE
[BUG]“接口定义”是通过postman导入，修改模块名称，保存时API返回500

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#1240]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6

**Bug 描述**
“接口定义”是通过postman导入，修改模块名称，保存时API返回500

**Bug 重现步骤**
1.  打开“接口定义”页面
2. 通过postman导入接口信息
3. 待导入成功后，在页面修改模块名称，保存

**期待的正确结果**
保存成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/17491657/105458625-e842c480-5cc3-11eb-8c54-4159fe897d35.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请提供下后端日志报错，可以通过 docker logs ms-server 查看或查看 /opt/metersphere/logs/metersphere/info.log
