### ISSUE TITLE
[BUG]大量数据库连接没有被释放导致数据库无法连接

### ISSUE THREAD

**Issue by viviandfcao** [metersphere/metersphere#12419]
### MeterSphere 版本

v1.19.2-e180194f

### 使用外置数据库

否

### 问题描述

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/9986048/162394091-fc819e38-c0cd-4ce3-9e16-573c1348c394.png">
大量的数据库连接没有及时释放，导致数据库连接不上，重启服务也没用

### 重现步骤

可能和定时任务有关，但是在删除定时任务后，依旧无效

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by ririliu** [comment]
> 您好，我们目前是这样设计的，默认有400条休眠的连接，从图来看这是连接池启动的休眠线程链接是属于正常现象；请筛选出有异常的线程；可以参考： http://blog.chinaunix.net/uid-134240-id-220211.html

连接池默认最小值400条连接？也太夸张了，这个在哪里能配置？我们这边估计连接池最小有10条连接就足够了

**Comment by zyyfit** [comment]
在 /metersphere/conf/metersphere.properties 文件里可以配置

spring.datasource.hikari.maximum-pool-size=x
spring.datasource.quartz.hikari.maximum-pool-size=x
