### ISSUE TITLE
[BUG]无法删除测试计划

### ISSUE THREAD

**Issue by viviandfcao** [metersphere/metersphere#12420]
### MeterSphere 版本

v1.19.2-e180194f

### 使用外置数据库

否

### 问题描述

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/9986048/162395358-f59dd5a8-6fd5-4f7e-987f-f4b0d07ba402.png">
<img width="257" alt="image" src="https://user-images.githubusercontent.com/9986048/162395400-9c723af6-c591-40b7-b67f-e51875f8f771.png">
无法删除测试计划

### 重现步骤

1. 选择需要删除的测试计划，提示【SQL error happened, please check logs.】

### 相关日志输出

```shell
日志请参考上图
```

**Comment by ltfit** [comment]
先查下 表存不存在  如果存在是不是大小写问题。 权限看下是不是655
