### ISSUE TITLE
测试用例自定义字段没有筛选功能

### ISSUE THREAD

**Issue by suipiangggg** [metersphere/metersphere#12422]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

用例模板添加属性为单选下拉列表的字段，测试用例页面的表头，不能根据下拉列表中填的默认值筛选（比如添加 能否自动化 字段，不能根据能或否筛选同一类型用例）

### 请描述你建议的实现方案

自定义字段 也有筛选功能

**Comment by Hyyfit** [comment]
已规划，待排期
