### ISSUE TITLE
[QUESTION]访问需要配置vpn连接的地址，一直在加载中

### ISSUE THREAD

**Issue by lulucky515a** [metersphere/metersphere#12431]
### 请描述您的问题

在metersphere中进行接口测试，但是需要连接vpn才能访问，配置ip地址之后，一直在加载无法请求成功。
除了配置环境地址，还需要配置什么参数呢？
<img width="903" alt="截屏2022-04-08 下午8 15 05" src="https://user-images.githubusercontent.com/45556675/162433869-028fc4d2-03e6-4a9a-9dab-4f8a359e886c.png">

**Comment by lulucky515a** [comment]
postman是可以正常访问的，但是metersphere就不行

**Comment by fit2-zhao** [comment]
@lulucky515a  确认一下是否是网络问题；postman 应该是你本机上安装；metersphere 应该部署在某台服务器吧，确认部署的这台服务器是否能连通被测系统。
