### ISSUE TITLE
[BUG]接口自动化时,发现接口配置后,无法修改或添加断言

### ISSUE THREAD

**Issue by sos269** [metersphere/metersphere#1244]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.6.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  在接口测试中, 配置接口用例后
2. 接口自动化,+接口后发现断言无法添加及修改
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问添加接口用例是通过复制还是引用的方式添加的呢？
