### ISSUE TITLE
[BUG]模版管理里新增了自定义字段，在用例这边没有显示

### ISSUE THREAD

**Issue by waris0361** [metersphere/metersphere#12441]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/51395871/162561174-d6223853-fcfd-4dfd-acad-7a7393facc65.png)
![image](https://user-images.githubusercontent.com/51395871/162561197-86e5aec9-d424-48d9-be7f-8bbe7f9f6e1b.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/51395871/162561174-d6223853-fcfd-4dfd-acad-7a7393facc65.png)
![image](https://user-images.githubusercontent.com/51395871/162561197-86e5aec9-d424-48d9-be7f-8bbe7f9f6e1b.png)

**Comment by ltfit** [comment]
感谢反馈 后续优化下

**Comment by ltfit** [comment]
你好 先在项目设置点击确认下 就显示了    后续我们优化下
![image](https://user-images.githubusercontent.com/99794211/162698111-d01c85fa-7482-47b1-886c-b7ca33452280.png)
