### ISSUE TITLE
swagger url导入接口文档部分字段描述丢失[QUESTION]

### ISSUE THREAD

**Issue by fybSeven** [metersphere/metersphere#12447]
### MeterSphere 版本

1.18.3

### 使用外置数据库

否

### 问题描述

swagger导入接口文档部分字段描述丢失了

### 重现步骤

接口描述-->接口定义-->更多操作-->导入-->swagger使用url导入 覆盖

### 期待的正确结果

导入后部分字段描述丢失

### 附加信息

![image](https://user-images.githubusercontent.com/32318706/162655007-6950ebef-6517-4d79-ad58-2f93d98f9b91.png)
![image](https://user-images.githubusercontent.com/32318706/162655066-d750c0e9-65a6-4871-b9b1-a6c888a1d3d6.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.19.3中已修复
