### ISSUE TITLE
[FEATURE]在新场景中导入被引用场景，被导入【复制】场景里面对应的场景变量是否可以带过来？

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12450]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

最近在给客户做自动化，因为是金融行业，注册场景，就有七八个步骤，还有五六个场景变量。 

注册是一个通用场景，需要被导入【复制】到 绑卡场景，还有其它业务场景。

注册场景被导入[【复制】后，目前是手动把 注册场景里面的参数给手动拷贝到新场景，是否可以在【复制】情况下，把 被复制场景的变量以及参数文件，都一并复制过来？

请产品评估！

如有任何问题，可以随时联系 王进 jin.wang@fit2cloud.com

### 请描述你建议的实现方案

请产品评估 把被复制场景变量一并复制到新场景的可行性。

**Comment by Hyyfit** [comment]
如果带入场景变量，可以用【引用】的方式
