### ISSUE TITLE
[BUG]1.6.2版本接口自动化,定时任务只有设置后, 没有关闭按钮

### ISSUE THREAD

**Issue by sos269** [metersphere/metersphere#1245]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口自动化,配置接口任务调试后,
2. 设定定时任务验证完成
3. 想要关闭定时任务
4. 发现不能情况,定时任务表达式,也没有关闭定时任务按钮

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/51393321/105568195-76758400-5d72-11eb-810d-2788b5da9a76.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
