### ISSUE TITLE
[BUG]【测试跟踪>>测试用例】选择【附件】： 上传附件后；再 点击查看，显示图片不全。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#12456]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

1.[BUG]【测试跟踪>>测试用例】选择【附件】： 上传附件后，在这里 点击查看，显示图片不全.
2.好像是概率性问题 有时候图片显示不全， 有时候可以。下图是点击查查显示一部分，图片大小也不是很大，才7M多。

### 重现步骤

1.【测试跟踪>>测试用例】选择【附件】：上传图片，并能正常上传和保存。
2.【测试跟踪>>测试用例】选择【附件】：点击查看已经上传的图片。
3.有时候图片显示不全， 有时候可以

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/162664243-ef0a1349-24f7-47c3-a56c-49b23156041c.png)

**Comment by ltfit** [comment]
你好 应该是网速问题
