### ISSUE TITLE
[BUG]mqtt接口自动化 修改步骤名字后，点调试和下拉小箭头 修改内容不生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#12457]
### MeterSphere 版本

1。19

### 使用外置数据库

否

### 问题描述

mqtt接口协议修改名字后，点调试和下拉小箭头 修改内容不生效

### 重现步骤

mqtt接口自动化场景：
1、接口列表步骤修改名称，然后点击接口下拉箭头调试   此时修改内容消失
2、修改接口步骤名字，直接 点击保存、调试   此时修改内容消失

### 期待的正确结果

修改内容保存生效

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/162666906-084a1b27-6f06-47fb-82c8-69378949479b.png)
![image](https://user-images.githubusercontent.com/43202800/162666935-d343177b-4048-4fb8-a063-c040a3679a89.png)
![image](https://user-images.githubusercontent.com/43202800/162666947-5b7d888c-659c-4590-8e73-ed96c10946cf.png)

**Comment by zyyfit** [comment]
没有复现这个问题，最新版是1.19.2，建议您升级试试

**Comment by xhy12** [comment]
> 没有复现这个问题，最新版是1.19.2，建议您升级试试
复现，见录

https://user-images.githubusercontent.com/43202800/164197845-56ac4cde-8d71-4e18-9ec3-efa4c4e276bf.mp4

屏

**Comment by zyyfit** [comment]
收到

**Comment by zyyfit** [comment]
最新版mqtt插件-1.2.4 已修复这个问题，更新插件时需要先把旧版的插件删除，然后重启ms服务，然后上传新的插件

**Comment by xhy12** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]mqtt接口自动化 修改步骤名字后，点调试和下拉小箭头 修改内容不生效 (Issue #12457)





 
最新版mqtt插件-1.2.4 已修复这个问题，更新插件时需要先把旧版的插件删除，然后重启ms服务，然后上传新的插件
