### ISSUE TITLE
[BUG]接口-接口定义执行的case在任务中心提示不正确

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#12468]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

接口-接口定义执行的case在任务中心提示不正确

### 重现步骤

1、接口-接口定义执行的case--自己创建，责任人是自己
2、在任务中心提示操作人不是自己

### 期待的正确结果

争取提示操作人，此问题在历来版本都存在

### 附加信息

这个是case的 执行历史点出来的
![image](https://user-images.githubusercontent.com/19423100/162699065-58194d77-37bd-45d4-a1bd-0866700a2aac.png)
这个是左上角的任务中心点出来的
![image](https://user-images.githubusercontent.com/19423100/162699161-4a4b64e8-104b-4ad5-8aaf-f7abb0d406b7.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.0-lts版本中已修复
