### ISSUE TITLE
[BUG]创建用户时，用户组一旦选定不可更改

### ISSUE THREAD

**Issue by TigeagleAn** [metersphere/metersphere#12470]
### MeterSphere 版本

  v1.19.2-e180194f

### 使用外置数据库

否

### 问题描述

创建用户时，选择用户组，一旦选定将无法修改，如果不小心选错了只能取消创建，重新开始，带来不便利性。

### 重现步骤

1、系统设置→系统→用户→创建用户，填入基本信息，选中用户组后，将无法变更，如果不小心选错呢？
建议在提交前，可以对用户组进行变更。

### 期待的正确结果

提交前，可以对用户组进行变更。

### 附加信息

![用户创建](https://user-images.githubusercontent.com/71053062/162704061-b5373675-93e1-4cbc-ab85-1256355634dc.png)

**Comment by zyyfit** [comment]
对，就是这样设计的，你要改的话，就再添加一个用户组，然后把这个用户组删掉
