### ISSUE TITLE
[FEATURE]Datatable的显示 支持自定义列

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#1249]
**请描述您的需求或者改进建议.**
Datatable的显示 支持自定义列

**请描述你建议的实现方案**
如“测试跟踪”的“测试用例"Datatable 的显示，支持自定义列；如：用户可以按需选择，只想要显示的列

**Comment by youliyuan-fit2cloud** [comment]
您好，计划v1.8 中实现该功能，请您持续关注～

**Comment by youliyuan-fit2cloud** [comment]
#264 问题重复，关闭该issue
