### ISSUE TITLE
[BUG]性能测试下载文件报错

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#12494]
### MeterSphere 版本

v1.19.2

### 使用外置数据库

否

### 问题描述

1、Jmeter下载文件，本地调试通过，可以正常下载文件到指定路径
2、修改文件下载路径为服务器上路径后（/opt/metersphere/data/）执行脚本报错，文件无法下载

### 重现步骤

1、Jmeter下载文件，本地调试通过，可以正常下载文件到指定路径，如下图所示
![image](https://user-images.githubusercontent.com/5198427/162873437-88f463a1-6323-4fcf-b799-e0aea2e7bf08.png)
2、修改文件下载路径，指定为服务器上路径（/opt/metersphere/data/）如下图所示
![image](https://user-images.githubusercontent.com/5198427/162873604-1a02235f-afa7-4dfa-a417-9a3c4add57d1.png)
3、上传步骤2中修改后的脚本到MeterSphere平台，运行性能测试
![image](https://user-images.githubusercontent.com/5198427/162874285-63350533-5c7f-4005-b6fc-161979f25a54.png)

### 期待的正确结果

文件下载成功，保存到服务器上指定路径下

**Comment by ltfit** [comment]
你好 没有复现 这个脚本发我下把
