### ISSUE TITLE
[BUG]场景报告中统计的请求数把环境中针对场景生效的全局前后置脚本算在内了

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12497]
### MeterSphere 版本

v1.19.2

### 使用外置数据库

否

### 问题描述

1.场景报告中统计的请求数不对，把环境中针对场景生效的全局前后置脚本算在内了。
2.全局前后置脚本中的内容，如果加上注释，报告统计依然会 统计成一个请求。

### 重现步骤

1.在环境中设置针对场景的全局前后置脚本（开启关联场景结果）
<img width="649" alt="image" src="https://user-images.githubusercontent.com/30038088/162877959-3bf32713-ed8f-4c51-8c75-3c6d795cc77f.png">
2.执行场景 ，查看报告
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/30038088/162878898-1c31e48c-3803-49dd-97b6-66eaad3e441c.png">
3.注释掉 前置脚本的内容
<img width="945" alt="image" src="https://user-images.githubusercontent.com/30038088/162878975-294f6836-4476-4e0b-a2e6-274ae81a495e.png">
4.执行场景 ，查看报告
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/30038088/162885932-f97af2d8-c858-4104-9e4b-d5559f902d08.png">

### 期待的正确结果

1.场景报告中统计的请求数不应该把全局前后置脚本的请求 统计在内
2.脚本内容 注释掉后，场景报告中 也不应该 把全局前后置脚本的请求 统计在内

**Comment by zyyfit** [comment]
没有复现这个问题，方便把复现场景和环境导出来给我们吗

**Comment by zyyfit** [comment]
1.20.0已修复
