### ISSUE TITLE
[BUG] 前置操作、后置操作和断言规则中的文本框不支持鼠标拖动选择文本

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12490]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

接口测试中前置操作、后置操作和断言规则这几个tab里面的文本框，不支持鼠标拖动选择部分文本。
比如一个文本框有 `name1,name2,name3,name4`，我想拖动光标选中 `name4`，会出现拖拽移动该步骤的效果。

### 重现步骤

1. 前置操作，后置操作和断言规则里添加一个 前置sql，后置sql，或者断言
2. 在任意文本框中输入name1, name2, name3, name4
3. 单击激活文本框，按住鼠标拖动光标

### 期待的正确结果

可以通过拖动光标选中部分文本

### 相关日志输出

无

### 附加信息

![image](https://user-images.githubusercontent.com/27671436/162860151-071b2cd7-9ccd-42fb-a485-8dc424238121.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.8-lts中已优化该问题，请升级一下吧
