### ISSUE TITLE
[FEATURE]开发者文档中的小问题

### ISSUE THREAD

**Issue by caichangchun** [metersphere/metersphere#125]
**请描述您的需求或者改进建议.**
1、错别字
![image](https://user-images.githubusercontent.com/26024107/87500066-38462c00-c68e-11ea-9a79-7a274e0b5468.png)
2、文档中给出的默认metersphere.properties配置文件中连接的数据库名与建表语句中的数据库名不一致，导致第一次起项目时报错
![image](https://user-images.githubusercontent.com/26024107/87500282-abe83900-c68e-11ea-995c-865bf20bca73.png)
![image](https://user-images.githubusercontent.com/26024107/87500322-bf939f80-c68e-11ea-9b0e-4f69cf55c430.png)
![image](https://user-images.githubusercontent.com/26024107/87500353-d20dd900-c68e-11ea-96ab-93e82eb72c2e.png)

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，已修改更新文档
