### ISSUE TITLE
[BUG]场景变量引用不对

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12512]
### MeterSphere 版本

 1.19.2

### 使用外置数据库

否

### 问题描述

多个场景存在同名变量，引用混乱

### 重现步骤

1 .创建场景 1，场景 1 中存在一个接口（复制）
2.创建场景 2、场景 3，分别 导入（复制）场景 1  
3.场景 2、场景 3 分别创建同名不同值的场景变量，
4.场景 4 导入（复制）场景 2和场景 3，场景 4 创建与场景 2、3 同名不同值的场景变量
5.执行场景 4，场景 2 和场景 3 分别使用各自场景变量，变量引用正确
6.执行场景 4，场景 2 和场景 3 都不勾选原场景变量，变量引用正确
7.执行场景 4，场景 2 使用原场景变量，场景 3 不使用原场景变量，执行结果 场景 2 中接口引用场景 2 的变量值，场景 3 引用的也是场景 2 的变量值

### 期待的正确结果

场景 3 应该引用场景 4 变量值

### 附加信息

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/36387811/162894391-ca4a06ff-31a3-4b49-a344-3766da2fc9f1.png">

**Comment by zyyfit** [comment]
目前是，被引用的场景跟步骤平级，场景中的场景变量也跟步骤变量平级，所以如果步骤中的场景里变量设置了值，就优先取步骤中的场景变量，
优先级排序：环境变量 < 整体的场景变量 < 步骤内变量（包括步骤提取、设置的变量、作为步骤的场景中的场景变量、作为步骤的场景中的步骤内变量）
暂时不做修改

**Comment by luty2018** [comment]
> 目前是，被引用的场景跟步骤平级，场景中的场景变量也跟步骤变量平级，所以如果步骤中的场景里变量设置了值，就优先取步骤中的场景变量， 优先级排序：环境变量 < 整体的场景变量 < 步骤内变量（包括步骤提取、设置的变量、作为步骤的场景中的场景变量、作为步骤的场景中的步骤内变量） 暂时不做修改

如果引用/复制的场景勾选了原场景变量，那么原场景变量优先级最高
环境变量 < 整体的场景变量 < 步骤内变量< 步骤原场景变量（如勾选）

**Comment by zyyfit** [comment]
1.20.0已修复
