### ISSUE TITLE
[QUESTION]响应结果怎么修改为UTF-8的编码

### ISSUE THREAD

**Issue by ssgitou** [metersphere/metersphere#1251]
**响应结果怎么修改为UTF-8的编码.**

**Comment by wangzhen-fit2cloud** [comment]
你好，我们默认就是采用的 utf 编码，请问响应在我们页面上是怎样的呢？

**Comment by ssgitou** [comment]
> 你好，我们默认就是采用的 utf 编码，请问响应在我们页面上是怎样的呢？

"data": {
        "error": "IP\u9650\u5236"
    },

**Comment by youliyuan-fit2cloud** [comment]
您好～，我们没有复现这个问题，请发一下详细的请求参数,方便做进一步验证
