### ISSUE TITLE
[FEATURE]建议场景中导入的子场景，允许修改子场景的名称

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#1253]
**请描述您的需求或者改进建议.**
在一个场景中导入子场景后，很多情况下需要修改子场景的名称来适应场景，故建议支持编辑子场景名称。

**请描述你建议的实现方案**

**Comment by lishushi-310** [comment]
建议可以修改子场景名称

**Comment by wangzhen-fit2cloud** [comment]
收到你的反馈，我们会尽快讨论排期实现
