### ISSUE TITLE
[BUG]mock使用query参数的方式触发，没有返回响应体

### ISSUE THREAD

**Issue by fybSeven** [metersphere/metersphere#12559]
### MeterSphere 版本

1.18.3

### 使用外置数据库

否

### 问题描述

mock接口使用query参数的方式触发没有返回定义的响应体，使用请求体的方式触发正常返回

### 重现步骤

接口测试-->接口定义-->创建接口
创建后在mock下选择添加，使用query参数的方式设置触发条件，保存后点击触发，执行成功但是没有返回响应体
![image](https://user-images.githubusercontent.com/32318706/163094210-9f0371b5-2430-4b1d-9a7b-f6dcde2e2d72.png)
![image](https://user-images.githubusercontent.com/32318706/163094238-b28622a0-bea4-444c-9da4-7a5762a07dff.png)
![image](https://user-images.githubusercontent.com/32318706/163094291-42f9bdfa-8b37-469c-bb44-4426ed9973bc.png)
![image](https://user-images.githubusercontent.com/32318706/163094367-e4ba46c8-9e12-4e37-a748-5780b8c6eac4.png)
同样的方式使用请求体触发，响应正常返回
![image](https://user-images.githubusercontent.com/32318706/163094521-065f8959-21cf-407e-a51e-af1643b0b1ca.png)
![image](https://user-images.githubusercontent.com/32318706/163094546-7de26c08-86cf-4d92-82e9-11f20c36c0db.png)

### 期待的正确结果

query参数方式触发也正常返回响应体

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v1.19.2没有这个问题了，建议升级一些
