### ISSUE TITLE
[FEATURE]性能测试结果，需要支持请求失败的取样器，能查看完整的请求、响应的内容

### ISSUE THREAD

**Issue by fengzhizi8080** [metersphere/metersphere#12551]
### MeterSphere 版本

v1.19.2-e180194f

### 请描述您的需求或者改进建议

性能测试结果，不支持请求失败的取样器，查看请求、响应的内容
【下载JTL】的jtl文件、报告的“日志详情”，均没有相关的内容，不方便测试、开发通过日志定位性能问题

### 请描述你建议的实现方案

性能测试报告，至少需支持请求失败的取样器，页面查看/下载的形式，能查看完整的请求、响应的内容，以便测试、开发去分析定位性能问题

### 附加信息

![E`Q5U`V20RK~ERFQ H _I2H](https://user-images.githubusercontent.com/103510030/162969722-70f1e72a-72b1-40bb-ba9f-084a689aaf61.png)

**Comment by zhangzhaox** [comment]
通过响应断言  事务失败时输入关键变量的信息和失败时的 请求 响应报文

**Comment by fengzhizi8080** [comment]
你的意思是在响应断言的“自定义失败消息”里加变量？会输出到测试报告的JTL文件吗？
麻烦发一个具体的操作说明，谢谢

**Comment by zhangzhaox** [comment]
完整的请求报文body信息输出用beanshell响应断言  事务失败时输出日志文件，在MS的日志详细里可看到
大多数情况下可在响应断言里输出 请求报文中的关键变量信息  
${__log(=======备件销售确认失败=========${msg_error_1}====${USER_NAME}==${salesOrderId}====,ERROR,,)}
