### ISSUE TITLE
[QUESTION]自定义变量内的函数表达式没有生效

### ISSUE THREAD

**Issue by ssgitou** [metersphere/metersphere#1256]
**
1、我在全局变量里面定义了两个变量分别为cash1和cash2
2、在自定义变量里面使用${__RandomFromMultipleVars(cash1|cash2)}这个函数，没有生效，这个函数在jmeter上正常使用的

.**

**Comment by youliyuan-fit2cloud** [comment]
您好，我们这边没有复现您问题～
测试结果如下：
![image](https://user-images.githubusercontent.com/54612864/107183247-67046500-6a19-11eb-9db3-17cf0686b682.png)

![image](https://user-images.githubusercontent.com/54612864/107183228-5bb13980-6a19-11eb-8191-46a3dac3072a.png)

![image](https://user-images.githubusercontent.com/54612864/107183233-61a71a80-6a19-11eb-9a45-67854efb8ade.png)
