### ISSUE TITLE
[FEATURE]增加点击失败时自动新增bug正文的功能

### ISSUE THREAD

**Issue by waveboy800** [metersphere/metersphere#12569]
### MeterSphere 版本

1.19.3

### 请描述您的需求或者改进建议

在执行用例时,如果针对某个步骤生产bug的话,希望自动生成bug正文,而不是当前手动输入.

### 请描述你建议的实现方案

在执行用例时,如果针对某个步骤生产bug的话,希望自动生成bug正文,而不是当前手动输入.

**Comment by Hyyfit** [comment]
麻烦详细描述一下您的问题。是在哪个测试下的？截图是怎样的？
