### ISSUE TITLE
[BUG]【接口测试>>case】:进入case详情，点击执行，然后在修改接口，紧接着点击保存，系统没有任何提示信息

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#12573]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

【接口测试>>case】:进入case详情，点击执行，然后在修改接口，紧接着点击保存，系统没有任何提示信息
注意：步骤顺序不要乱了，一定是先执行（run），然后修改接口参数信息；紧接着直接再点击【保存】。你会发现
1、系统没有任何提示信息

### 重现步骤

【接口测试>>case】:
1、进入case详情，点击执行，等待系统正常执行，结果为通过。
2、然后在修改接口参数体信息。比如我这里修改参数name的值从a改为b
3、紧接着点击保存。

**注意：**步骤顺序不要乱了，一定是先执行（run），然后修改接口参数信息；紧接着直接再点击【保存】。你会发现
1、系统没有任何提示信息

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/163116981-0a8cc9f5-762d-410c-bde0-4359f1de1d8a.png)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
