### ISSUE TITLE
接口自动化中，编辑 场景-基础信息中的描述信息无法保存

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1258]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2
**Bug 描述**
简要描述您碰到的问题
接口自动化中，编辑 场景-基础信息中的描述信息无法保存
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![微信图片_20210125170159](https://user-images.githubusercontent.com/22139528/105683875-1aa42a00-5f2f-11eb-992d-2eba0fb9467b.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，该问题会在 v1.7.0 版本中进行修复，请持续关注。
