### ISSUE TITLE
[BUG]Post请求体form-data，字段类型json，data={复杂json内容}，点字段编辑图标，然后在弹窗开启json schema，描述里 输入的描述内容不会被保存。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12587]
### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

[BUG] Post请求体form-data，字段类型json，data={复杂json内容}，点字段编辑图标，然后在弹窗开启json schema，描述里 输入的描述内容不会被保存。
![990eb07365e819e740729362ebb241f](https://user-images.githubusercontent.com/76033005/163129905-cad15c21-4c76-4da4-964c-c1e315ee26a5.jpg)
![0d894241ed65b29459301d2b117d318](https://user-images.githubusercontent.com/76033005/163129924-891bde90-09a7-40b8-92b1-c165f9828546.jpg)

### 重现步骤

1. 新建post api
2. 请求体选form-data
3. 字段类型选json
4. 输入data
5. 在值字段输入 一段json格式请求体
6. 点 铅笔图标
7. 在弹窗页面开启json-schema
8. 在 描述 字段输入描述，关闭 弹窗，描述未被保存，正常字段属性修改都被保存了。
9. 

### 期待的正确结果

描述字段的值也需要被保存，这边企业客户开发 接口定义现在搬迁到metersphere了，需要描述去备注 接口字段

### 附加信息

任何问题可以联系jin.wang@fit2cloud.com

**Comment by youliyuan-fit2cloud** [comment]
你好，经开发确认 该json的格式为kv格式无法存储描述字段
