### ISSUE TITLE
[QUESTION] 请问 MeterSphere 有技术支持 QQ 群 和 微信群 吗？

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#1259]
**请描述您的问题.**

如题。

**Comment by wangzhen-fit2cloud** [comment]
你好，可以在我们的官网最下方的 `联系我们` 中看到 QQ 及微信群的二维码。
https://metersphere.io/#contact
![image](https://user-images.githubusercontent.com/27671436/105701914-fbfd5d80-5f45-11eb-9cab-d68b5c825dc4.png)
