### ISSUE TITLE
[FEATURE]接口测试里面增加不同模块里面接口定义的名称可以相同的功能

### ISSUE THREAD

**Issue by LoveELF** [metersphere/metersphere#12605]
### MeterSphere 版本

1.9.2

### 请描述您的需求或者改进建议

在接口测试里面-接口定义页面。新建了多个模块，每个模块里面导入或者新建path相同且名称相同的接口。现在在设置里面只能打开path相同不校验，期望可以也有个开关控制接口名称也可以相同。
场景：
大型项目的场景下，不同模块里面对应的服务是不同的，每个服务里面可能定义相同名称和path的接口，这样会导致导入或者同步swagger的接口出现部分模块里面没有的情况。

### 请描述你建议的实现方案

在项目设置中添加接口定义的名称也可以重复的开关，类似现有的url可重复开关
![image](https://user-images.githubusercontent.com/635336/163152328-4343f401-fd8b-4c5a-bdff-70381cc94894.png)

**Comment by Hyyfit** [comment]
您好，接口定义的名称是可以重复的。
如果开启了url可重复开关。校验的是“名称-url” 不可重复。在实际的测试场景中，不会存在名称和url同时重复的情况
<img width="692" alt="image" src="https://user-images.githubusercontent.com/95834771/163154135-c43afd61-460e-45f4-af23-c82ffa0ddc6d.png">

**Comment by LoveELF** [comment]
我使用的是swagger同步的功能，把开关打开之后，部分相同的接口无法导入

**Comment by LoveELF** [comment]
> 如果开启了url可重复开关。校验的是“名称-url” 不可重复。在实际的测试场景中，不会存在名称和url同时重复的情况

实际情况下是可能出现的，比如大型系统，每个模块都是一个单独的服务。
比如健康检查的接口，每个服务都有一份，但是我导入的时候只能剩下其中一个
