### ISSUE TITLE
[bug]通过脑图编辑多个用例顺序失败

### ISSUE THREAD

**Issue by RubyClx** [metersphere/metersphere#12618]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

使用脑图编写用例，保存后，用例的顺序是错乱的
手动尝试更改，保存后打开仍是乱的
注：如果只更改一个顺序，没有问题

### 重现步骤

使用脑图编写五个以上用例
保存后，顺序乱的
通过拖动阴影改变顺序，

此时保存后再打开，是乱掉的顺序

### 期待的正确结果

多个用例存在时，通过阴影调整顺序，仍可以保存更改后的用例顺序

### 附加信息

图一是手动调整后的顺序，
![image](https://user-images.githubusercontent.com/103616851/163300009-88b55959-599c-47d1-937e-93eef03cf362.png)
图二是错误顺序，保存后再打开，顺序错误
![07757c7bfb0ed93c75fbf40d99e51a6](https://user-images.githubusercontent.com/103616851/163299788-0039eff3-7ed5-41b6-8ed2-9d5a6af5a809.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #12269
