### ISSUE TITLE
[BUG]误报规则匹配有误，误报规则应该只有在请求失败或者断言失败的情况下才会生效

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12616]
### MeterSphere 版本

v1.19.2

### 使用外置数据库

否

### 问题描述

误报规则匹配有误，误报规则应该只有在请求失败或者断言失败的情况下才会生效

### 重现步骤

1.创建一个误报规则
<img width="999" alt="image" src="https://user-images.githubusercontent.com/30038088/163166678-5ebd8a5b-9385-4508-b3a8-ef2f0c246762.png">
2.创建一个登录接口，接口执行成功/断言成功，依然会命中误报规则
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/30038088/163167971-6374c1ee-90ff-4f34-83db-6050c82b6cbf.png">

**Comment by youliyuan-fit2cloud** [comment]
这个误报功能重构了。。。请更新到v1.20吧
![image](https://user-images.githubusercontent.com/54612864/165480991-37039361-4029-4ad8-b206-94675cb8c331.png)
