### ISSUE TITLE
[FEATURE]接口测试中建议增加多种认证方式，如RSA证书认证

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#1261]
**请描述您的需求或者改进建议.**

目前接口测试中只支持basic auth账号密码认证，建议增加多种认证方式，如RSA证书认证

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢反馈，我们会尽快规划实现。

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/1261

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/3642
