### ISSUE TITLE
[BUG]在测试计划中打开测试用例无法执行也无法提交

### ISSUE THREAD

**Issue by Anduin-Zhu** [metersphere/metersphere#1262]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.6.2-e012d438
**Bug 描述**
在测试计划中打开测试用例无法执行也无法提交
**Bug 重现步骤**
1.  打开测试计划
2. 点击已关联的用例
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
用例可执行，可提交BUG
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/29295893/105796316-8f2ba700-5fc9-11eb-8f29-124bda030fcd.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请点击用例操作列中的编辑按钮，直接点击用例的话是只读模式。
