### ISSUE TITLE
[FEATURE]mock优化

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12643]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

mock功能是否可以将真实环境地址也设置进去，然后通过接口的状态来识别是否调入mock，例如接口状态为进行中就调入mock，已完成就直接调入真实环境地址。这样可以让整个测试环境只对接一个地址，并且能够快速切换是否需要mock，让测试更便捷

**Comment by Hyyfit** [comment]
目前的设计如此。
我们接口用例执行时，选择环境有3种方式：
第一种是在批量执行用例时，可以选择【运行环境】。如果不选择环境，则按照编辑用例的环境执行；如果选择环境，则按照选择的真实环境批量执行。
![image](https://user-images.githubusercontent.com/95834771/163511062-5cfe8114-5624-465f-b16b-044f153f1d84.png)

第二种是在加入测试计划时，可以选择给用例配置不同的环境，这里配置后，接口用例的运行环境会以计划里配置的为准。
![image](https://user-images.githubusercontent.com/95834771/163511203-5f7d37a3-d0f6-47b4-9ae7-567e3c820e71.png)

第三种是在执行测试计划的时候，可以选择环境，如果这里不选择运行环境，则按照加入测试计划的环境运行。如果选择环境，则按照选择的环境运行。
![image](https://user-images.githubusercontent.com/95834771/163513291-ee0c7e1a-c4a0-4ac9-ade5-4423ed687eb9.png)


例如在测试计划中添加接口用例，用例A选择的mock环境，用例B选择的是真实的环境。
那么在执行整个测试计划的时候，如果不选择【运行环境】，则按照配置的部分接口用例是mock环境运行，部分接口是真实环境运行。如果选择了【运行环境】，则所有的用例都按照选择的真实环境执行。这样通过测试计划可以实现快速切换是否需要mock环境。

**Comment by wszbc** [comment]
> 目前的设计如此。 我们接口用例执行时，选择环境有3种方式： 第一种是在批量执行用例时，可以选择【运行环境】。如果不选择环境，则按照编辑用例的环境执行；如果选择环境，则按照选择的真实环境批量执行。 ![image](https://user-images.githubusercontent.com/95834771/163511062-5cfe8114-5624-465f-b16b-044f153f1d84.png)
> 
> 第二种是在加入测试计划时，可以选择给用例配置不同的环境，这里配置后，接口用例的运行环境会以计划里配置的为准。 ![image](https://user-images.githubusercontent.com/95834771/163511203-5f7d37a3-d0f6-47b4-9ae7-567e3c820e71.png)
> 
> 第三种是在执行测试计划的时候，可以选择环境，如果这里不选择运行环境，则按照加入测试计划的环境运行。如果选择环境，则按照选择的环境运行。 ![image](https://user-images.githubusercontent.com/95834771/163513291-ee0c7e1a-c4a0-4ac9-ade5-4423ed687eb9.png)
> 
> 例如在测试计划中添加接口用例，用例A选择的mock环境，用例B选择的是真实的环境。 那么在执行整个测试计划的时候，如果不选择【运行环境】，则按照配置的部分接口用例是mock环境运行，部分接口是真实环境运行。如果选择了【运行环境】，则所有的用例都按照选择的真实环境执行。这样通过测试计划可以实现快速切换是否需要mock环境。

有点不一样，我的意思是我服务端整个测试系统会调到mock地址，那么我只对接mock地址，如果需要切换到真实地址，就要重新改配置重启，或者重新打包。如果能mock自己做转发到真实地址这样其实会更方便，加速测试。你得解决方案是基于metesphere的用例层，自身是发起方控制了调用的地址。我这说的是我自己的服务去调metersphere的mock
