### ISSUE TITLE
[FEATURE]接口自动化循环控制器中的循环次数可以填入参数，根据参数来进行循环次数

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12641]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

接口自动化循环控制器中的循环次数可以填入参数，根据参数来进行循环次数

### 请描述你建议的实现方案

循环次数中能够填写设置的参数，现在只能写数字

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。

**Comment by luty2018** [comment]
已实现
