### ISSUE TITLE
[BUG]接口自动化场景，复制 方式导入两个项目 接口自动化场景或接口用例，且 这两个项目创建的环境变量名称一样，属性一样，导致 有一个环境变量属性在新场景里失效。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12656]
### 联系方式

王进

### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

接口自动化场景，复制 方式导入两个项目 接口自动化场景或接口用例，且 这两个项目创建的环境变量名称一样，属性一样，导致 有一个环境变量属性在新场景里失效。

备注：客户不是故意这样用，客户这边光一套场景，可能就得测试几十个环境，主要是面向很多不同的客户。之前tapd提过。

![image](https://user-images.githubusercontent.com/76033005/163371479-53769597-bbe6-4cc4-b705-a2e97148ffe4.png)

### 重现步骤

过程比较复杂：
1. 在一个项目里，定义接口，设计一个用例，header里指定一个属性msid，值为${msid}
![1649933369(1)](https://user-images.githubusercontent.com/76033005/163376748-5433608d-8610-4f1e-807a-bbe9c3319c71.png)

![01](https://user-images.githubusercontent.com/76033005/163376184-07e52bab-de0a-4852-be95-a1d7b67c925e.png)

2. 创建一个环境变量ebao, ip 指定为 baidu.com，通用配置添加变量msid，值为ms
![1649933283(1)](https://user-images.githubusercontent.com/76033005/163376500-6dce3208-666f-4546-8240-d3e7a6e3893c.png)
![1649933308(1)](https://user-images.githubusercontent.com/76033005/163376561-2160ad47-c84d-4c9d-b4a5-e778cba63a2c.png)

3. 创建一个用例，选定环境ebao，保存，执行，
    **header里面的msid带出的值是 ms**

4. 在一个新的项目，定义接口，设计一个用例，header里指定一个属性msid，值为${msid}

5.  创建一个环境变量ebao, ip 指定为 baidu.com或者其他任意值，通用配置添加变量msid，值为 **jms**
![1649933895(1)](https://user-images.githubusercontent.com/76033005/163377983-7f1c79c0-b4b5-4ced-a078-a75474981f6d.png)
![1649933926(1)](https://user-images.githubusercontent.com/76033005/163378128-e4535cb5-604c-4055-8c41-94408c10b2bf.png)

![02](https://user-images.githubusercontent.com/76033005/163377771-98dad1c4-8e3f-4786-85fe-b0549197ea55.png)

7. 创建一个用例，选定环境ebao，保存，执行，
    **header里面的msid带出的值是 jms**

9, 在第一个项目里创建一个场景，把之前步骤里创建的 接口用例导进来，选择好环境，执行。
![1649934127(1)](https://user-images.githubusercontent.com/76033005/163378572-48686d1b-f697-4770-8941-31df6dce1d4c.png)

10. 检查这两个请求发出去的 header内容
这两个请求发出去的header里的msid都是jms。

备注：客户不是故意这样测，而是他们有真实的业务这样跑。

### 期待的正确结果

两个请求里面的header 字段 不应该都是jms，应该是一个是ms，一个是jms

**Comment by 35plus** [comment]
![1649934572(1)](https://user-images.githubusercontent.com/76033005/163379404-894f8d2f-b37d-4a99-b10b-ca565349bb60.png)

![1649934572(1)](https://user-images.githubusercontent.com/76033005/163379648-2a680fb5-10bd-45a1-842e-808cfc0b504b.png)
![1649934638(1)](https://user-images.githubusercontent.com/76033005/163379647-4a21c4fc-192c-4434-a8cc-b9c136143a2a.png)

刚刚三张截图上传失败，再次补进来

**Comment by youliyuan-fit2cloud** [comment]
如果引用/复制的场景勾选了原场景变量，那么原场景变量优先级最高
环境变量 < 整体的场景变量 < 步骤内变量< 步骤原场景变量（如勾选）

**Comment by luty2018** [comment]
目前变量值做了场景间的隔离，步骤间没有隔离，jmeter原生甚至场景间都没有隔离，如果添加步骤间的变量隔离可能引起未知问题，建议从设计场景上绕开这种情况。
