### ISSUE TITLE
[FEATURE]测试跟踪-测试用例显示用例条数

### ISSUE THREAD

**Issue by heshaol** [metersphere/metersphere#1266]
**请描述您的需求或者改进建议.**
测试用例显示对应的条数
XXX用例（已评审用例数/总用例数）

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/72126159/105822001-77b6e300-5ff6-11eb-828c-e6223fd47148.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢反馈，我们会尽快评估并排期实现。

**Comment by xulinde** [comment]
列表下方是可以看的，如图
![image](https://user-images.githubusercontent.com/64065190/118214382-31509b80-b4a2-11eb-98e5-c23fd800963d.png)
