### ISSUE TITLE
[BUG]JSON结构断言，预期结果使用${__BeanShell(,)}函数返回值，断言失败

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12677]
### MeterSphere 版本

V1.18.3

### 使用外置数据库

否

### 问题描述

使用JSON结构断言，预期结果使用${__BeanShell(,)}函数返回值，断言失败
![1649992717(1)](https://user-images.githubusercontent.com/37204403/163512857-7e2f4a46-0831-4f39-b17b-4a25163c2db8.png)
![1649992750(1)](https://user-images.githubusercontent.com/37204403/163512896-7474d3d1-3e3c-4e07-bb6b-79e84967f70b.png)

### 重现步骤

无

### 期待的正确结果

断言校验成功

**Comment by SloanGao** [comment]
不知道是不是类型问题，已经试了上面那种先定义boolean变量，然后再根据if结果返回该变量值，断言失败。也是了直接返回true or false,还是失败，如：${__BeanShell(if(vars.get("preferentialType").equals("9"))return true;return false;)}

**Comment by youliyuan-fit2cloud** [comment]
你好，建议用断言-脚本方式吧，
json 文档结果断言的”值“直接输入 这个不太行，”${__BeanShell(if(vars.get("preferentialType").equals("9"))return true;return false;)}“
