### ISSUE TITLE
[FEATURE]Jenkins插件提供测试失败后的处理方案

### ISSUE THREAD

**Issue by heshaol** [metersphere/metersphere#1267]
**请描述您的需求或者改进建议.**
目前Jenkins插件针对触发的测试结果没有后续处理方案

**请描述你建议的实现方案**
建议增加Jenkins插件调用测试后如果测试不通过，需要增加处理方案：停止，回退，继续等

**Comment by wangzhen-fit2cloud** [comment]
你好，能否描述下完整的场景，停止和回退是针对的 Jenkins 任务吗？
