### ISSUE TITLE
[BUG]项目组成员有第三方平台tab权限，但是个人设置无法查看到

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#12676]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

1、项目组成员有第三方平台tab权限
2、登录账户查看个人信息
3、个人设置无法查看到第三方平台tab

### 重现步骤

1、项目组成员有第三方平台tab权限
2、登录账户查看个人信息
3、个人设置无法查看到第三方平台tab

### 期待的正确结果

正确查看设置

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/163511867-ce20d597-0013-4e27-b856-8bb899e4a189.png)

![image](https://user-images.githubusercontent.com/19423100/163512142-bf862410-5f9a-4faf-bb83-d726aec31c85.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，是不是服务集成没有添加过第三方平台？

**Comment by legend818** [comment]
集成了禅道

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/167373407-339eece8-0d2c-4fce-99be-0b54c5723558.png)之前禅道的bug都能同步，之前的版本是好的具体什么时候不行 就不知道了，现在新增人员发现问题的

**Comment by youliyuan-fit2cloud** [comment]
该新用户的权限是不是没打开，请查看如下图所示的位置是否开启个人信息权限
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/54612864/167383078-8bd59011-e19e-491c-89bb-9e82bda96159.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，确实bug，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
这个问题已优化，升级到最新版本吧
