### ISSUE TITLE
语法错误

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#12698]
### 联系方式

2818820548@qq.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述
点击修改用户会出现语法异常
![Uploading image.png…]()

### 重现步骤

![Uploading image.png…]()

### 附加信息

![image](https://user-images.githubusercontent.com/33744331/163533032-37c1dc0a-8083-4c5e-b6d4-5f785d55f3c3.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，你这个图片看不了，请重新描述一下你遇到的问题

**Comment by AshuaiNe** [comment]
附加信息的能打开






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月15日(星期五) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] 语法错误 (Issue #12698)





 
你好，你这个图片看不了，请重新描述一下你遇到的问题

**Comment by youliyuan-fit2cloud** [comment]
> 附加信息的能打开
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年4月15日(星期五) 下午3:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [metersphere/metersphere] 语法错误 (Issue #12698) 你好，你这个图片看不了，请重新描述一下你遇到的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

附加信息是能看到，但是不知道是怎么复现的,请重新描述一下复现步骤
