### ISSUE TITLE
[BUG]功能用例中无法移动测试用例顺序

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12695]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

根据官方文档看功能用例中的测试用例可以上下调整顺序，但我的功能用例里面没有这个功能无法调整顺序

### 重现步骤

正常创建项目，创建多条测试用例，无法调整用例顺序

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/163530199-58d873b7-0c88-42d7-bf87-baab9a0cc668.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，如果用例列表的表头有任何排序操作是不能拖动的，请清空排序 ，再尝试 拖拽用例

如下如所示的 六个点...
![image](https://user-images.githubusercontent.com/54612864/163560869-c4ca2580-6ac8-473f-942f-82948701bd75.png)
