### ISSUE TITLE
[QUESTION]请问场景变量中的请求头在场景的接口中如何使用？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#12690]
### 请描述您的问题

根据metersphere文档，关于场景变量中的请求头，描述为：场景变量也支持配置请求头参数。
场景详情如下：

- 场景变量中的请求头定义： 
key   value
token ${token}
- 场景步骤：
① 登录接口
登录的后置操作是通过jsonpath提取路径$.token中的token值存储到变量token中
② 查询接口（需要用到token）
接口的请求参数页面的请求头中有Content-Type；如果在该接口的请求参数页的请求头tag里面 定义了token：
    - 值没有填，那么运行场景后的请求信息中token为空，
    - 如果值填为${token}，那么运行之后的请求信息中token为字符串”${token}“而不是第一步中返回的token的值。

如果没有定义token，那么运行场景之后的请求信息中连token这个键都没有

请问场景变量中定义的请求头应该怎么使用？为什么在场景下面的接口中执行请求时，没有自动放置到请求头信息中？在官方文档以及网上都没有找到具体的使用方法，请问哪里有具体的使用方法？

**Comment by Hyyfit** [comment]
1.先检查一下登录接口的提取数据中，是否正常的提取出了token
2.在场景变量中的请求头已经配置了token，在查询接口中请求头不需要再次定义token
步骤： 
第一步场景变量中定义好需要用到的参数，我以cookie为例
![image](https://user-images.githubusercontent.com/95834771/163534749-0bd9d198-61c0-4a3b-b9a0-c0d279b176de.png)
第二步 登录接口中提取到了需要用到的值
![image](https://user-images.githubusercontent.com/95834771/163535285-14325cf6-80b4-4fab-a779-4f305f6275d7.png)

**Comment by Faerie1999** [comment]
您好，谢谢您的解答，我发现问题出现这里：
当场景A 引用了场景B ，而场景B 中存在场景变量，那么场景A 中的场景变量将不起效，不可用（不管是请求头还是自定义变量），只会引用场景B 中的场景变量。

以上可验证，请问该功能是否存在缺陷？
比如以下情况：
场景B 为场景A 和场景C 的前置场景，而场景B 拥有场景变量（比如登录名和密码），场景A 和场景C 有各自的用例（比如场景A 用到的CSV和场景C 用到的CSV不一样，但是里面可能存在重合的参数名称），这种情况如果将csv变量全部置于场景B 的场景变量中，将会产生冲突，并且针对不同的场景进行复用的难度增加了。（如果举例不够清晰请见谅）

这种情况应该怎么使用呢？

**Comment by Hyyfit** [comment]
如果引用的场景b，也有场景变量的情况下，可以设置是否使用原场景变量。
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/95834771/164400487-5807ec67-993e-4aa0-b0b8-26df10a7160c.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/95834771/164400571-2408d8e3-847c-4a17-a065-cc1274fe5039.png">

**Comment by Faerie1999** [comment]
明白了，谢谢您的耐心解答
