### ISSUE TITLE
接口测试，建议添加两个功能，一个功能是测试前准备数据，包括支持mysql,oracle,hbase,es,hive,

### ISSUE THREAD

**Issue by xiuchunhuang** [metersphere/metersphere#127]
**请描述您的需求或者改进建议.**
接口测试，建议添加两个功能，
功能一：是测试前准备数据，包括支持mysql,oracle,hbase,es,hive,
功能二：测试后添加一个数据库断言，响应断言与数据库断言通过以后才能算测试通过。

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
