### ISSUE TITLE
[BUG]条件控制器下无法放入等待控制器

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#12707]
### MeterSphere 版本

 v1.19.1-4fb56789

### 使用外置数据库

否

### 问题描述

在条件控制器下放入等待控制器，无法拖拽进去

### 重现步骤

在条件控制器下放入等待控制器，无法拖拽进去

**Comment by qingmu2633** [comment]
![b3b20ebe2a0188968bffff671bf2fa1](https://user-images.githubusercontent.com/86302975/163550342-8353e6c5-076d-4c30-8abd-16d5912be4a2.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，是不允许的呀，条件控制器下面不能直接加等待控制器，如下操作可以
![image](https://user-images.githubusercontent.com/54612864/163561399-5dd163d6-352d-4527-b549-d57658f6fc56.png)
