### ISSUE TITLE
[BUG]测试用例关联测试场景，查询数据问题

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#12708]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

A用例关联自动化场景C，然后B用例去关联自动化测试场景C，查询的时候会发现有两个C场景，每多关联一次后面查询就会多一个

### 重现步骤

A用例关联自动化场景C，然后B用例去关联自动化测试场景C，查询的时候会发现有两个C场景

### 期待的正确结果

查询的时候只出现一个C场景

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/163552332-0d8ddbbf-9957-471f-94f1-ffe3930e2811.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~
