### ISSUE TITLE
[BUG]接口自动化-条件控制器判断不正确

### ISSUE THREAD

**Issue by couplie** [metersphere/metersphere#1272]
**MeterSphere 版本**
1.6.2

**Bug 描述**
条件控制器执行判断不正确

**Bug 重现步骤**
1.根据上个请求获取token
2.如果token为空则不执行后续请求

**期待的正确结果**
正常情况应该执行两个请求

**截图**
![image](https://user-images.githubusercontent.com/10140862/105940810-12ff9500-6097-11eb-9a54-46424708f8b3.png)
![image](https://user-images.githubusercontent.com/10140862/105940857-26aafb80-6097-11eb-97bf-556fcb66571a.png)
![image](https://user-images.githubusercontent.com/10140862/105940819-15fa8580-6097-11eb-8407-eb95d8ce23fd.png)
![image](https://user-images.githubusercontent.com/10140862/105940828-185cdf80-6097-11eb-86d2-d6f9ec6e46e1.png)
![image](https://user-images.githubusercontent.com/10140862/105940839-1e52c080-6097-11eb-9ac9-42de67f1c0d7.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请查看下第一个请求的结果部分中的提取页面，看下 token 是否正常提取到了。

**Comment by couplie** [comment]
> 你好，请查看下第一个请求的结果部分中的提取页面，看下 token 是否正常提取到了。

![image](https://user-images.githubusercontent.com/10140862/105964790-a6e45780-60bd-11eb-9093-77c71fcc8e7a.png)
正常提取

**Comment by wangzhen-fit2cloud** [comment]
收到，我们尽快处理下。

**Comment by xulinde** [comment]
感谢您的反馈，该问题已修复，后面发布1.8.0版本您升级下就可以了
