### ISSUE TITLE
[BUG][BUG] 读取CSV数据出现EOF

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#12721]
### MeterSphere 版本

1.19.2

### 使用外置数据库

是

### 问题描述

1、在场景变量中上传csv文件 
2、预览数据正常显示 是自己编辑数据
3、实际执行测试 循环获取csv内容数据，随机数据某条数据为显示为EOF
4、提示错误： Non HTTP response code: java.net.URISyntaxException 

### 重现步骤

1.创景场景 变量使用csv驱动
2.创建测试计划添加创建的场景
3.环境配置开启误报功能
4.设定定时任务自动执行
5.查看报告命中误报case 显示读取csv EOF

### 附加信息

![image](https://user-images.githubusercontent.com/101856439/163564029-b56abd2f-0b06-4b2f-86fd-a11daf6f4b7d.png)
![image](https://user-images.githubusercontent.com/101856439/163564043-2f58444f-10e6-4cdf-9cbe-e540a495e076.png)
![image](https://user-images.githubusercontent.com/101856439/163564050-a20402b8-1721-4910-9b64-473255e8ecda.png)
![image](https://user-images.githubusercontent.com/101856439/163564075-49252e04-73d5-4384-a5c6-8640518782d8.png)
![image](https://user-images.githubusercontent.com/101856439/163564108-03619d92-a187-4eb2-9226-7b667e872cb2.png)
[日志.txt](https://github.com/metersphere/metersphere/files/8495629/default.txt)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #11655

**Comment by youliyuan-fit2cloud** [comment]
升级到最新版本v1.19.3试试吧，我们有优化这个问题
