### ISSUE TITLE
[BUG]场景的接口覆盖率不能按照api_scenario_reference_id 的api 的id 统计

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12735]
### 联系方式

shenkaibo

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

场景的接口覆盖率不能按照api_scenario_reference_id 的api 的id 统计，
因为场景 复制 API 接口，在场景里可以修改path地址，原API的path 也可以修改，
但是id不变，这样会导致 覆盖率计算不准确。

### 重现步骤

新建场景，导入2个API接口，选择复制，保存。查看 api_scenario_reference_id  有2条记录。
修改场景步骤里的 path 地址，查看 api_scenario_reference_id  有2条记录 没有任何变化。
删除 API，查看 api_scenario_reference_id  还是 有2条记录

### 期待的正确结果
如果修改 计算覆盖率 逻辑的话，需要考虑 处理下历史数据
_No response_

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
