### ISSUE TITLE
[BUG]一个资源池里有两个压力节点时，性能测试中有两个场景分别使用阶梯加压，分六步加压到目标并发，报告中三步就达到了目标并发

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#12731]
### 联系方式

蒋林峰

### MeterSphere 版本

1.19.2

### 使用外置数据库

是

### 问题描述

1.资源池里面设置两个压力节点
2.创建性能测试，引用两个接口自动化场景
3.场景都使用阶梯加压线程组
4.每个线程组测试时间6分钟，目标并发6个用户，ram-up时间360，steps为6.。。两个线程组总共并发用户为12
5.选择包含两个压力节点的资源池，保存并执行
6.结果性能测试报告显示分成三步阶梯加压到了12个用户

### 重现步骤

1.资源池里面设置两个压力节点
<img width="745" alt="e48c65aae06cedf24645f279c1abfe1" src="https://user-images.githubusercontent.com/88763608/163664555-3966bc80-9f54-4d60-82aa-1b0addc16652.png">

2.创建性能测试，引用两个接口自动化场景
3.场景都使用阶梯加压线程组
<img width="910" alt="359030e3d2596412f4961a904d8ea4c" src="https://user-images.githubusercontent.com/88763608/163664565-693a3a0d-4be0-4bf5-8dd8-d80a347b7e16.png">

4.每个线程组测试时间6分钟，目标并发6个用户，ram-up时间360，steps为6.。。两个线程组总共并发用户为12
<img width="919" alt="29e9a7cea9793a0a0fee3d2c326c14b" src="https://user-images.githubusercontent.com/88763608/163664568-47159ecf-91ae-4d3d-82d9-e76ac0576a5f.png">

5.选择包含两个压力节点的资源池，保存并执行
6.结果性能测试报告显示分成三步阶梯加压到了12个用户
<img width="936" alt="7a2d2d314f4b5d8c39d958995a5ec3b" src="https://user-images.githubusercontent.com/88763608/163664608-30a4844a-958b-498b-a097-b281b49cd089.png">

### 期待的正确结果

以下是资源池里只有一个压力节点的测试报告，正常分成了6个step
<img width="943" alt="95900d80772241417a49a7dc03be04e" src="https://user-images.githubusercontent.com/88763608/163664585-a3670ea0-f47e-4df3-b8b5-4c080e2aa670.png">

**Comment by liuruibin** [comment]
我这里没有复现出来

**Comment by linfengjjj** [comment]
我们内部有复现环境，可以通过内部VPN连接
http://10.1.11.194:8081  账号密码：admin/metersphere,用我们的vpn连接就可以了，在”演示工作空间“-”默认项目“-性能测试”-“验证阶梯加压”
