### ISSUE TITLE
[QUESTION]项目设置-文件管理，上传的jar包，接口测试调用不了

### ISSUE THREAD

**Issue by fengzhizi8080** [metersphere/metersphere#12736]
### 请描述您的问题

1.项目设置-文件管理，上传jar包
2.项目设置-项目环境-配置环境-全局前置脚本，单个请求步骤前执行，输入调用jar包的代码；接口用例执行后，控制台没有调用
![image](https://user-images.githubusercontent.com/103510030/163718628-bd01f2f1-89f3-4edb-8062-4f44821efb66.png)
3.接口测试-接口定义-CASE-编辑-前置操作，输入调用jar包的代码；接口用例执行后，控制台输出调用失败
![image](https://user-images.githubusercontent.com/103510030/163718555-cbccea39-219f-4010-b680-b6a13393ec38.png)

该sign签名的jar包，同样的调用代码。性能测试可以，接口测试不可以。会是什么原因呢？

**Comment by Hyyfit** [comment]
您好，在最新的版本上还有这个问题吗？
您可以在交流群里加一下我的企业微信，发一下脚本，看看具体是什么问题。
<img width="320" alt="image" src="https://user-images.githubusercontent.com/95834771/168574682-08925d0b-3e17-477e-90f3-47b0159350fd.png">
