### ISSUE TITLE
[FEATURE]导入接口时自动生成接口用例

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1273]
**请描述您的需求或者改进建议.**
通过swagger或者Postman导入时只生成了接口定义，需手动为每个接口创建接口用例

**请描述你建议的实现方案**
导入时可以直接生成接口用例，测试数据可以根据接口描述里抽取有用信息自动生成，也可以外部文件一起导入或者用假数据让用户自己修改，可在界面上用选项控制是否自动生成接口用例，也可以在接口列表页面加入自动生成用例按钮。

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢你的反馈，我们会优先处理 postman 文件导入时自动创建用例的场景，后续也会去扩展基于已有接口定义，自动组合参数生成测试用例的场景。

**Comment by net2817** [comment]
目前这块进度如何了，1.8.2版本里实现了吗？有没有示例。

**Comment by luty2018** [comment]
已经实现， 导入postman文件会同步生成对应的测试用例
