### ISSUE TITLE
在接口自动化删除已经触发定时任务的场景时，对应的定时触发的场景未被删除

### ISSUE THREAD

**Issue by xmhawxp** [metersphere/metersphere#12745]
### 联系方式

15001148204

### MeterSphere 版本

1.9.2

### 使用外置数据库

否

### 问题描述

在接口自动化删除已经触发定时任务的场景时，对应的定时触发的场景未被删除

### 重现步骤

1、在接口自动化创建场景
2、在第1步创建的场景设置定时器
3、等定时器确定触发后，再删除已经触发定时任务的场景

### 期待的正确结果

在接口测试的测试报告里，删除的场景不再触发定时任务

### 附加信息

![c2da8e82369e7c32c9cefe0a949c016](https://user-images.githubusercontent.com/30286457/163749021-d844c5c9-8883-4220-8a82-2081fba10597.png)
![74a8a4abdd7965ec91815215a377b8a](https://user-images.githubusercontent.com/30286457/163749039-1f3d916a-95a4-4c9d-9658-9ff2c1ec81c1.png)
![da7953862a8352e5363b1a90bbf2c3a](https://user-images.githubusercontent.com/30286457/163749057-8c7efa95-e1b7-4d25-9508-ca1025870f54.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个删除的场景在回收站里面还存在，应该是没有关掉定时任务，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
