### ISSUE TITLE
[FEATURE]可以将jmeter的响应断言加上吗

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1274]
**请描述您的需求或者改进建议.**
可以将jmeter的响应断言加上吗

**请描述你建议的实现方案**
加一个响应断言，我们主要用来比对返回的json数据和我们预期是是否一致，我们可以直接copy一份数据用字符串比对就可以了。
现在的不管是jsonpath还是正则，不能完全使用字符串匹配，如果有特殊字符，需要转义才可以，非常麻烦。

**Comment by wangzhen-fit2cloud** [comment]
你好，目前我们的正则就是通过响应断言实现的，能否截一下你们在 JMeter 中配置断言的截图，我们优化下这里的配置方式。
