### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1275]
**请描述您的问题.**
接口参数中有特殊字符串时，会自动进行urlencode编码，请求接口会报错，这个可以控制吗
接口中拼接参数后，会自动编码，但这个时候我请求是不成功的;
我把这个链接解码后，再去访问，才会成功。
有什么办法让他不自动编码吗
![微信图片_20210127184154](https://user-images.githubusercontent.com/22139528/105980043-5a097c80-60cf-11eb-830c-ba2ff10556fd.png)
![微信图片_20210127184148](https://user-images.githubusercontent.com/22139528/105980047-5b3aa980-60cf-11eb-993c-158e0ee9fc8e.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问是如何解决的？
