### ISSUE TITLE
[BUG]SQL請求數據源 編輯保存以後，自動被還原，不能更新

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#12752]
### MeterSphere 版本

V1.19.3

### 使用外置数据库

否

### 问题描述

SQL請求數據源 編輯保存以後，自動被還原，不能更新
![1650253400(1)](https://user-images.githubusercontent.com/37204403/163751187-f37789bd-0227-4ab1-9409-b9e150716ce2.png)
![1650253511(1)](https://user-images.githubusercontent.com/37204403/163751237-87665e7b-a676-4ef9-9184-a4b5435ff3b7.png)

### 重现步骤

如上圖所示，升級之前數據源是MOTODB，升級以後自動變成了HotelDB，重新編輯修改成MOTODB，再次編輯打開又變成了HotelDB。
註：HotelDB默認維護數據庫連接的第一個

**Comment by SloanGao** [comment]
可以尽快帮忙看一下？这个比较急，以前维护的很多场景都无法跑成功了

**Comment by youliyuan-fit2cloud** [comment]
已修复
