### ISSUE TITLE
[BUG]优化场景变量保存提示

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12753]
### MeterSphere 版本

 1.19.3

### 使用外置数据库

否

### 问题描述

接口自动化--场景变量  每次打开没有做任何变更，关闭都会提示保存成功以及更新最后更新时间，还以为自己不小心动到哪里了，这个地方可以优化下吗，以便这里的更新是真实的更新

### 重现步骤

1.进入包含场景变量的场景
2.点击场景变量
3.关闭场景变量弹窗
4.提示保存成功

### 期待的正确结果

修改了场景变量，关闭会提示保存成功，没有修改，不提示保存成功

### 附加信息

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/36387811/163755686-8daad69f-c3c8-44fa-911a-36a0f7afceb1.png">

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
