### ISSUE TITLE
[BUG]编辑接口用例时，ESB格式的TCP请求参数显示不全

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#12778]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v1.19.1

### 使用外置数据库

否

### 问题描述

编辑接口用例时，ESB格式的TCP请求参数显示不全

### 重现步骤

由于ESB文件属于客户内部资料，不方便在这里提供重现步骤
我本地有完整的复现视频，请与我单独联系

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
