### ISSUE TITLE
[FEATURE] 脑图用例切换为列表用例后在切换回去，顺序错乱

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#12774]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v19.1

### 使用外置数据库

否

### 问题描述

先编写脑图用例，关闭用例后再进入脑图用例，发现顺序与之前写的不一致

### 重现步骤

先编写脑图用例，关闭用例后再进入脑图用例，发现顺序与之前写的不一致

### 期待的正确结果

列表用例和脑图用例分别存储自己的顺序，并且对列表用例来说顺序是可以通过字段排序的(默认可以按照id排序)。但是脑图排序是没办法手动排的。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #12269
