### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Boylijun** [metersphere/metersphere#12775]
### 请描述您的问题

1.9.3离线部署，什么也不修改，为啥server容器没有创建成功啊 
![image](https://user-images.githubusercontent.com/21175004/163779396-0c2436c1-9591-4e4c-a76f-03a90576dac7.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，版本是1.19.3？ 看下日志吧，你这个截图看不出啥。。。
