### ISSUE TITLE
接口测试--步骤、参数构造多、批量操作时浏览器会出现崩溃

### ISSUE THREAD

**Issue by liangweijie99** [metersphere/metersphere#1277]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/74578958/106081177-68997780-6153-11eb-8a57-77738e4ad81c.png)

**Comment by fit2-zhao** [comment]
这个问题在1.7.2 已经优化过

**Comment by liangweijie99** [comment]
请关注，内存溢出问题 #1438
