### ISSUE TITLE
[BUG]已提交至禅道的缺陷，再次预览或编辑，缺陷内图片无法查看且禅道处理人丢失

### ISSUE THREAD

**Issue by aboutsome** [metersphere/metersphere#12779]
### 联系方式

MeterSphere 交流群4

### MeterSphere 版本

v1.19.3

### 使用外置数据库

否

### 问题描述

通过ms提交缺陷至禅道，预览或查看缺陷内容，缺陷图片丢失，无法正常查看。
![image](https://user-images.githubusercontent.com/11850951/163785376-23de7ed6-a4f9-466b-bbc6-7d7a8388fef4.png)
![image](https://user-images.githubusercontent.com/11850951/163786041-ffeb650e-763d-4203-89e2-dc1f53d06158.png)

### 重现步骤

1、正常提交缺陷至禅道，缺陷内容包括图片、文字、禅道处理人
2、再次查看已提交的缺陷，预览或编辑，发现图片无法查看，禅道处理人丢失

### 期待的正确结果

正常查看历史缺陷提交记录，可正常展示缺陷图片及禅道处理人

**Comment by youliyuan-fit2cloud** [comment]
你好，使用的禅道版本是多少？企业版？or开源版？
