### ISSUE TITLE
[BUG]在禅道上已创建的缺陷，MS上点击“同步缺陷”，未成功同步

### ISSUE THREAD

**Issue by aboutsome** [metersphere/metersphere#12780]
### 联系方式

MeterSphere 交流群4

### MeterSphere 版本

v1.19.3

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/11850951/163786805-04706609-a026-43aa-809a-d766637a0a94.png)
点击“同步缺陷”，第三方平台禅道的数据，未成功同步。

### 重现步骤

1、项目设置内，禅道项目已正确配置，且检查通过；
2、点击“同步缺陷”，第三方平台禅道的数据，未成功同步。

### 期待的正确结果

在禅道创建了缺陷后，可以正确同步至MS

**Comment by youliyuan-fit2cloud** [comment]
你好，使用的禅道版本是多少？企业版？or开源版？

**Comment by luty2018** [comment]
从禅道提交的缺陷同步是企业版功能，开源版只支持从MS提交到禅道的缺陷进行双向同步
