### ISSUE TITLE
[FEATURE]增加提缺陷贴图功能

### ISSUE THREAD

**Issue by Anduin-Zhu** [metersphere/metersphere#1279]
**请描述您的需求或者改进建议.**

增加提缺陷贴图功能
![image](https://user-images.githubusercontent.com/29295893/106119133-cfd51d00-618f-11eb-857f-06d3b7b2228e.png)
可以直接通过粘贴添加截图，

**请描述你建议的实现方案**
参考禅道

**Comment by xulinde** [comment]
1.10版本已支持
