### ISSUE TITLE
[BUG]接口自动化导入jmx文件， 第一次执行，接口请求返回404

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#12793]
### 联系方式

内部 郭灶鹏

### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

接口自动化导入jmx 文件后， 前端页面不展开场景步骤， 执行，接口返回404， 打开测试报告发现获取不到请求路径。
手动展开场景步骤，  打开请求详情， 再次执行，接口调用成功。

### 重现步骤

1、  根据接口请求的内容， 配置mock请求。
2、 编辑jmx 文件， 修改内网IP-HttpSampler ,   修改为mock 的ip 和端口
3、 接口自动化导入jmx 文件，导入csv 文件， 指定随意的测试环境
4、 第一次执行，提示：
![1650338910(1)](https://user-images.githubusercontent.com/30264974/163914856-9fc81d4d-1b6c-4b6a-b5c8-47d6c1043e61.jpg)
5、手动展开场景步骤，  打开请求详情， 再次执行，接口调用成功
<img width="797" alt="1650338949(1)" src="https://user-images.githubusercontent.com/30264974/163914907-d067d6ed-fc85-4207-8372-21beacb262f0.png">

### 期待的正确结果
导入之后，无需手动展开请求详情， 就能成功执行接口自动化
_No response_

**Comment by fitcloud-zaopengguo** [comment]
jmx 文件内部联系郭灶鹏

**Comment by youliyuan-fit2cloud** [comment]
1.20.0-lts版本已修复
