### ISSUE TITLE
[BUG]接口自动化-数据库操作，编辑时数据源变更为配置的数据源列表的第一个，导致查询异常

### ISSUE THREAD

**Issue by haitest** [metersphere/metersphere#12790]
### 联系方式

hai_test@sina.com

### MeterSphere 版本

v1.19.2-e180194f

### 使用外置数据库

是

### 问题描述

项目环境配置多个数据源的时候，在接口自动化场景案例设置的前后置SQL的数据源在编辑的时候默认为数据源列表的第一个，导致数据查询异常

### 重现步骤

1.配置环境-数据库配置，如图
![image](https://user-images.githubusercontent.com/33622764/163911494-96b8e5cd-48e8-4ba7-9f98-977a87a4c02c.png)
2.接口测试-接口自动化，创景场景A，添加后置SQL操作
![image](https://user-images.githubusercontent.com/33622764/163911732-976dea49-f5fa-4d63-8e5d-0fc51a0955cf.png)
3.点击调试，查询数据库正常
4.保存场景A
5.关闭场景A
6.编辑场景A，查看后置SQL
![image](https://user-images.githubusercontent.com/33622764/163912067-0329a6d1-aa22-477d-b91f-cd3201030c77.png)
7.点击调试，数据库执行异常
![image](https://user-images.githubusercontent.com/33622764/163912147-2f082792-d41d-495a-ab86-be0304a9f1eb.png)

### 期待的正确结果

1.编辑时后置SQL展示的数据源应该为创建是选择的数据源
2.执行数据库操作正常

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #12752
