### ISSUE TITLE
1、单独提取url，2、单接口调试功能，3、支持上传文件接口，4、支持连接数据库操作，5、接口报告的结果建议使用断言判断

### ISSUE THREAD

**Issue by scelery** [metersphere/metersphere#128]
1、单独提取url，2、单接口调试功能，3、支持上传文件接口，4、支持连接数据库操作，5、接口报告的结果建议使用断言判断

**Comment by wangzhen-fit2cloud** [comment]
后续建议每个需求单独提一个 issue @scelery 
1. 请详细描述下该需求详情和使用场景
3. 与 #121 重复
5. 目前结果是会根据断言是否成功进行判断的，如果你测试的结果不符合这个预期，请详细描述下并提供下截图信息。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
