### ISSUE TITLE
[QUESTION] 性能测试处理starting，无其它反应

### ISSUE THREAD

**Issue by DLChenMR** [metersphere/metersphere#1280]
**请描述您的问题.**

版本：v1.6.2

操作：上传jmx后，保存并执行，测试一直处于 "开始状态"，无其它反应

PS：已在[系统设置]-[系统参数设置]-[基本配置]中设置了站点URL

**Comment by wangzhen-fit2cloud** [comment]
你好，请更新下 1.7.0 再尝试下。

**Comment by DLChenMR** [comment]
> 你好，请更新下 1.7.0 再尝试下。

更新到 1.7.0 ，但还是一样处于 starting。

系统使用docker部署的（用quick_start.sh），我将系统参数的设置中的站点URL设为：http://ms-server:8081，但还是不行。（之前URL使用的是 “宿主机IP+ms-server暴露的PORT”，但提示的是“无法运行测试，请检查当前站点配置”）

原本想在 https://demo.metersphere.com/ 上试一下的，还好像由于你们的安全考虑，试不了。

**Comment by LimonFHM** [comment]
一般是有报错，jmeter容器执行的时候报错，导致容器直接退出了。
可以尝试：在点执行后，立刻docker ps 查看生成的jmeter容器id，然后快速执行docker logs 容器id....          

@wangzhen-fit2cloud    错误提示很关键！！   遇到脚本错误，容器直接退出了，导致界面就一直starting，让人一头雾水。

**Comment by youliyuan-fit2cloud** [comment]
您好，v1.7.2版本未复现该问题，请更新后再重新执行性能测试，如仍遇到该问题请再联系我们～
