### ISSUE TITLE
接口定义，讲版本修改为1.0.1 保存后不生效 列表版本还是1.0.0

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#12804]
### MeterSphere 版本

 v1.19.1-4fb56789

### 使用外置数据库

否

### 问题描述

接口定义，讲版本修改为1.0.1 保存后不生效 列表版本还是1.0.0
![image](https://user-images.githubusercontent.com/43202800/163962077-38110795-33c5-4236-ac57-faac205dd7b2.png)

### 重现步骤

1、接口列表修改版本信息，从1.0.0切换为1.0.1，保存
2、问题：进入接口列表保存 接口版本还是1.0.0  修改不生效

### 期待的正确结果

修改之后版本显示为1.0.1

**Comment by youliyuan-fit2cloud** [comment]
你好，请检查一下 项目设置-版本管理-当前最新版本是不是v1.0.1 ?如果不是的话，列表显示的最新版本的
![image](https://user-images.githubusercontent.com/54612864/164134860-2b6af7e3-992d-4cf4-ab7d-2bcbe21217db.png)

**Comment by xhy12** [comment]
收到，修改了显示正常了。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月20日(星期三) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 接口定义，讲版本修改为1.0.1 保存后不生效 列表版本还是1.0.0 (Issue #12804)





 
你好，请检查一下 项目设置-版本管理-当前最新版本是不是v1.0.1 ?如果不是的话，列表显示的最新版本的
