### ISSUE TITLE
[FEATURE]接口测试-接口定义，模块树建议增加批量删除模块功能

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1281]
**请描述您的需求或者改进建议.**

接口测试-接口定义，模块树建议增加批量删除模块功能

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/54024064/106133198-e5524300-619f-11eb-8167-6761dec66b7b.png)

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们回尽快评估并增加该功能。

**Comment by xulinde** [comment]
1.8版本已优化，导入的时候必须选模块，然后直接删模块就可以了
![image](https://user-images.githubusercontent.com/64065190/112439654-5b2ff080-8d84-11eb-8159-1bab894ee3c8.png)
