### ISSUE TITLE
[BUG] 某特定get请求在 MS 接口定义>快捷调试和接口用例测试 这个地方执行的结果 和postman里不一样，和场景里 勾选共享cookie后的结果也不一样。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12817]
### 联系方式

王进

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

[BUG] 某特定get请求在 MS 接口定义>快捷调试和接口用例测试 这个地方执行的结果 和postman里不一样，和场景里 勾选共享cookie后的结果也不一样。

### 重现步骤

1. 下面这个get请求是客户发给我们的，可以先在postman里执行一次，并查看结果
https://wap-test.pharmakeyring.com/wsc/thirdLogin/loginToModule10019.json?appKey=xingzhou-pharmakey&appType=&module=8484&channelCode=yaoguanai&ud=d2gdMs3w9btJOE1KWfTAx2E%2BzplbRyx3CNJ1Ces8eilk8crIT90CfWSX5ulBVEOsJk4IuygjCExb2wJCxofASRV78vtj73VRW5vxXXS6DghXh8YvYi%2F40qFg5tNVWcEKTdUKpDe3kh2ZzYAq4IyBPc5T5cjrdVG0rrYLEjYpjBbIZZ1omCFO5stuPvOrUtPPftGkIRhf0F3%2BQjyObVxIinDTCGl30ytokOHT69bh6Wc%3D
![cc73f5b21eb9c29a62c20ec71b9c37d](https://user-images.githubusercontent.com/76033005/164145382-c73570fa-3f75-4b1a-a00a-c282fb5b3e59.png)

2. 进入MS，选择接口定义，输入上面信息，保存，点击测试tab，配置好环境，测试，观察 MS返回的结果，跟随重定向也勾选了。结果和postman不一样。接口用例的结果也是错的。
![c1c60ab8c2d16926191d25c24d883d5](https://user-images.githubusercontent.com/76033005/164145262-91b39bce-4e8f-4673-bd14-b90e233b62b5.png)

3.  如果新建一个场景，把接口用例导入到场景，勾选共享cookie，这个时候执行的结果就是正确的，和postman一样
<img width="992" alt="ebd1123330fd8f2f7d63f78c54cff16" src="https://user-images.githubusercontent.com/76033005/164145527-eefaa823-7309-4212-9ff5-98a186c019dc.png">

### 期待的正确结果

在接口定义下面的调试结果，测试结果，和postman里一样

### 相关日志输出

```shell
见重现步骤
```

**Comment by zrfit** [comment]
您好，感谢您的反馈，case执行的时候  会跳转到别的页面，也就是重定向，但是重定向的时候会需要cookie进行当前页面的验证，case执行的时候无法把cookie带过去，所以无法验证通过；场景中执行时，勾选上共享cookie ，会把cookie带过去方便重定向的时候验证，ms后端是通过jmeter调用的，用jmeter调用该接口也是未返回结果，所以暂不支持。
