### ISSUE TITLE
[BUG]接口导入 swagger url 定时同步报错

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1282]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.0-3c6a4849
**Bug 描述**
简要描述您碰到的问题
进入 接口测试-接口定义-执行【导入】接口操作，选择Swagger-开启使用URL导入，填入正确的url，开启“定时同步”开关时候，系统提示“Value for moduleId cannot be null”，无法使用定时同步接口功能！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/106133450-3feb9f00-61a0-11eb-98a0-912097a2517a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
