### ISSUE TITLE
[BUG]测试跟踪 --用例模板上传的用例；用例名称和内容是空的

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#12826]
### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪 --用例模板上传的用例；用例名称和内容是空的

<img width="928" alt="Snipaste_2022-04-20_17-10-30" src="https://user-images.githubusercontent.com/43202800/164194496-de3decf4-2264-4ebe-917b-15de428cdc2b.png">

### 重现步骤

测试跟踪 --上传本地的用例模板；上传后查看用例名称和内容是空的

有录屏

### 期待的正确结果

用例名称和步骤可以保存

### 附加信息

<img width="928" alt="Snipaste_2022-04-20_17-10-30" src="https://user-images.githubusercontent.com/43202800/164194831-5e6980f9-679a-4095-8ce0-5da97ad59e40.png">

https://user-images.githubusercontent.com/43202800/164194881-71a623e3-bb89-440f-a179-ff328fbfddb9.mp4

**Comment by xhy12** [comment]
[Metersphere_case.xlsx](https://github.com/metersphere/metersphere/files/8520177/Metersphere_case.xlsx)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
