### ISSUE TITLE
[BUG]接口定义-重复点击编辑按钮，会重复打开多个接口编辑页面

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1283]
**MeterSphere 版本**
v1.7

**Bug 描述**
重复点击编辑按钮，会重复打开多个接口编辑页面

**期待的正确结果**
已经打开一个编辑页面时，如果点击列表重新点击编辑按钮，不应该重新打开页面(可以直接切换到已打开的编辑页面，或点击无效)

**截图**
<img width="663" alt="11111" src="https://user-images.githubusercontent.com/21210217/106144318-fe162500-61ae-11eb-98f4-cde50f13d4be.png">

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快确认并修复该问题。
