### ISSUE TITLE
[BUG]创建缺陷-关联用例-同一条用例只能被关联一次，如果再想关联这条用例需要退出重新登录

### ISSUE THREAD

**Issue by peggytest** [metersphere/metersphere#12851]
### 联系方式

172276028@qq.com

### MeterSphere 版本

1.18.0

### 使用外置数据库

否

### 问题描述

如题目

### 重现步骤

1. 创建缺陷-关联用例-关联用例A
2. 再次创建缺陷-关联用例-关联用例A

### 期待的正确结果

允许再次关联

**Comment by ltfit** [comment]
感谢反馈 下个版本修复
