### ISSUE TITLE
[BUG]Jmeter函数在请求体被拆分

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12852]
### MeterSphere 版本

19.3

### 使用外置数据库

否

### 问题描述

请求体为 json ，参数值为 jmeter 函数，输入后切换到 raw，看以看到 jmeter 函数被拆分

### 重现步骤

1.在场景中导入一个接口
2.接口请求体中请求参数值为 jmeter 函数
3.切换格式为 raw
4.jmeter 函数被拆分

### 期待的正确结果

jmeter 函数格式不变，在一行显示

### 附加信息

![image](https://user-images.githubusercontent.com/36387811/164357080-2bc70b70-689a-4a40-8cf0-dcc0c6bf8e3f.png)
![image](https://user-images.githubusercontent.com/36387811/164357099-7cea226a-9d14-4e6f-9943-c4b461a71dc7.png)

**Comment by zrfit** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/99731894/164474677-7f9e19da-98a2-465a-b700-f2a6f3461038.png">
您好，json请求体中函数用""引上 切换raw后在切换为json  函数就不会拆分了
