### ISSUE TITLE
[BUG]脑图模式复制A用例,粘贴-修改保存新用例时，覆盖A用例

### ISSUE THREAD

**Issue by Wind-Liv5** [metersphere/metersphere#12861]
### 联系方式

694082030@qq.com

### MeterSphere 版本

 v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

脑图模式复制A用例,粘贴-修改保存新用例时，覆盖A用例

### 重现步骤

1、脑图模式编辑用例：Ctrl+C复制A用例
2、Ctrl粘贴为新用例，**只编辑文字，不改变用例等级**，保存后又覆盖了原A用例

### 期待的正确结果

复制粘贴的用例，都能保存新用例

**Comment by ltfit** [comment]
您好 我这边没有复现这种问题 ，能否把用例导出我这边尝试复现下

**Comment by Wind-Liv5** [comment]
> 您好 我这边没有复现这种问题 ，还有别的特殊操作么；能否把用例导出我这边看下

Ctrl+C复制 Ctrl+v粘贴 直接保存不做修改 就会出现新复制的不见了

**Comment by ltfit** [comment]
您好 我尝试了很多次 复现不了。能否录个视频我看下

**Comment by ltfit** [comment]
您好 我尝试了很多次 复现不了。能否录个视频我看下

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue

**Comment by Wind-Liv5** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我有事不在，无法亲自回复您的邮件。我将在阅读后，尽快给您回复。
