### ISSUE TITLE
[BUG]缺陷关联测试用例-无法选择之前选择的用例

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#12865]
### 联系方式

254052917@qq.com

### MeterSphere 版本

v1.19.0-1727df14

### 使用外置数据库

否

### 问题描述

缺陷关联测试用例-无法选择刚刚创建缺陷时选择过的用例

### 重现步骤

1.进入缺陷管理模块，创建缺陷，关联测试用例100001
2.创建成功后，立马再创建第二条缺陷，点击关联用例时看不到 100001 的用例数据了，不过模块右侧是有用例数量的
3.刷新页面后再创建缺陷，点击关联用例，可以看到 100001 的用例数据

怀疑是缓存的因素导致的
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/89765365/164369272-2997764a-754c-45ef-88c0-d28e063fd08b.png">

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/12851
