### ISSUE TITLE
[BUG]jenkins开放配置-选插件结果没有生效

### ISSUE THREAD

**Issue by AH2000141** [metersphere/metersphere#12874]
### MeterSphere 版本

v1.19.0

### 使用外置数据库

是

### 问题描述

jenkins 查看执行，选择开放配置，两种方式ms失败jenkins还是成功

### 重现步骤

无

### 期待的正确结果

希望jenkins结果也是失败

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by LizardYang** [comment]
> 感谢反馈，后续版本修复

请问这个问题什么时候会修复呢

**Comment by zyyfit** [comment]
目前这个功能没有什么作用了，已经去掉了，消息通知增加了执行成功和执行失败的通知，可以根据通知判断成功和失败
