### ISSUE TITLE
[BUG]接口自动化-添加场景变量过程中，输入变量名称后再输入变量值。此时焦点会立即切换到变量名称

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1287]
**MeterSphere 版本**
v1.7

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快确认并修复该问题。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
