### ISSUE TITLE
[BUG]接口定义-将接口另存为新用例后，方法名会被前端自动替换为协议

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1288]
**MeterSphere 版本**
v1.7

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
<img width="1492" alt="2222" src="https://user-images.githubusercontent.com/21210217/106156344-5f90c080-61bc-11eb-9f29-0af3e5e4f59b.png">

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快确认并修复该问题。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
