### ISSUE TITLE
[BUG] 导入从yapi导出的Swagger文件后，所有参数必填非必填状态未被保存，全成了非必填，所有请求参数都添加了json请求方式，导致get\put等请求错误

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#12888]
### 联系方式

18323056969

### MeterSphere 版本

V1.18.3

### 使用外置数据库

否

### 问题描述

[swagger.json.zip](https://github.com/metersphere/metersphere/files/8529729/swagger.json.zip)

以上文件是从yapi导出后并调整为正确的swagger格式后 导入metersphere，所有请求都变成了json,且参数必填非必填没有有效保存，所有参数都变为了非必填

<img width="726" alt="image" src="https://user-images.githubusercontent.com/13564069/164426761-d19a7044-ff3b-4416-a6e9-d977e9c5cf9e.png">

会导致后续用例请求失败

### 重现步骤

1

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/164608816-757ffbb4-ae92-458e-b8e6-c7245d0c8bc7.png)
swagger2.0 会根据参数的consumes属性有无判断参数格式，如果有，就根据文档的描述查参数格式。如果没有会设置成json格式
