### ISSUE TITLE
[BUG]缺陷管理模块关联用例数显示有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#12894]
### MeterSphere 版本

1.19

### 使用外置数据库

否

### 问题描述

在提交缺陷并关联用例的情况下，缺陷列表中该缺陷的用例数始终显示为0；

### 重现步骤

1.提交1个缺陷，并关联2条用例，查看缺陷列表中该缺陷的用例数显示；

### 期待的正确结果

1.显示为2；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/164438677-ad6902d3-5646-4a18-b638-8ee3bebdcb15.png)
![image](https://user-images.githubusercontent.com/92150453/164439142-d913f351-c88b-4edf-9be9-4ab00c57ba4d.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，你这个版本是1.19.几？

**Comment by sageonedream** [comment]
1.19.1的，经确认1.19.3无此问题…



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月21日(周四) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]缺陷管理模块关联用例数显示有误，请修改 (Issue #12894)




 
你好，没有复现该问题，你这个版本是1.19.几？
