### ISSUE TITLE
[BUG]性能测试：修改归属项目后，导致脚本消失

### ISSUE THREAD

**Issue by liuzhiming1988** [metersphere/metersphere#12890]
### 联系方式

554050110@qq.com

### MeterSphere 版本

1.19.1

### 使用外置数据库

否

### 问题描述

性能测试：修改归属项目后，导致脚本消失，在原项目和新项目中都不可见

### 重现步骤

1.在性能测试-测试列表中，点击一个脚本，进入编辑页面
2.修改左上角的项目为另外一个项目，点击保存
3.返回列表，原项目找不到此脚本，切换到新项目，新项目中也无此脚本

**Comment by youliyuan-fit2cloud** [comment]
你好，没太理解你说的问题。。性能测试列表页面-编辑也脚本？是编辑一个性能测试用例吗？
请上传操作页面截图吧
