### ISSUE TITLE
[FEATURE]1.7新版接口测试里面加载jar包无界面入口

### ISSUE THREAD

**Issue by xianshancom** [metersphere/metersphere#1289]
**请描述您的需求或者改进建议.**
1.7新版接口测试里面加载jar包无界面入口
1.7新版性能测试里面可以上传jar包，但接口测试界面却无上传jar包的入口，显得非常割裂。

【补充】
系统设置 项目管理里面上传jar包，太隐蔽了。。。。
**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，请问有什么具体建议吗？
由于现在接口测试实现的问题，上传到 Jar 包不能做到完全隔离，所以放在了一个公共的位置。

**Comment by xianshancom** [comment]
接口测试里面加载jar包也加个菜单跳转过去吧，系统设置->项目管理里面上传jar包比较隐蔽。

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快优化下。
