### ISSUE TITLE
[接口自动化]接口自动化测试模块在批量执行场景时，建议可以增加运行环境的选择

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1290]
如果一套接口场景需要适配多个测试环境，而每个环境业务相同，仅仅是环境参数不同，按照目前metersphere的实现，如果环境有3个，就要复制3套相同的测试场景，在每个场景里选择环境配置，这样很不方便，而且不利于用例的维护和管理。所以，建议在批量运行场景时可以提供给用户一个入口，让用户可以选择场景需要运行的实际测试环境，这样就不会造成测试用例的冗余。

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快排期优化。

**Comment by xulinde** [comment]
1.10版本已实现
