### ISSUE TITLE
在frontend 下的components下新建了目录 和文件，运行的时候没找到相应的文件

### ISSUE THREAD

**Issue by FishBlanche** [metersphere/metersphere#12902]
### 请描述您的问题

在frontend 下的components下新建了目录 和文件，运行的时候没找到相应的文
![截图1](https://user-images.githubusercontent.com/19261291/164463493-981fa624-1082-47d2-b32f-911084a430d3.png)
![截图2](https://user-images.githubusercontent.com/19261291/164463500-9a7a01f6-3699-4ec0-81aa-d090080117af.png)
件

**Comment by AgAngle** [comment]
你好，你是指的在开发环境中运行吗？如果是的话，还麻烦自己排查下是哪里写的不对，具体啥问题我们也没办法给具体看噢
