### ISSUE TITLE
[BUG]csv文件内引号获取不准确

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#12920]
### 联系方式

xufu.yang@fit2cloud.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

问题：
场景变量csv配置 是否允许带引号：true
1、csv文件内容是  "测试" 在配置预览显示 测试 没有引号                           "测试"----->测试
2、csv文件内容是  “"测试"” 在配置预览显示 “测试”“   引号引用不准确      ""测试""  --->"测试""
3、接口内引用时显示变量是EOF

### 重现步骤

问题复现：
1、csv文件内容
![image](https://user-images.githubusercontent.com/101856439/164444349-210d1adb-cde2-41c1-9b49-3edb9f0e465a.png)
[test1.csv](https://github.com/metersphere/metersphere/files/8530368/test1.csv)
2、场景变量引用 配置
![image](https://user-images.githubusercontent.com/101856439/164444565-1a47c845-7fd6-408d-ab88-e86082f7e6ca.png)
3、对比csv文件和配置预览
![image](https://user-images.githubusercontent.com/101856439/164444822-c8bd472f-aa9c-4123-96d5-9f6d8dce419e.png)
4、mock调试
![image](https://user-images.githubusercontent.com/101856439/164444961-44f51ada-0c7e-44f8-8132-39189df4f68e.png)
![image](https://user-images.githubusercontent.com/101856439/164445044-02cf8c51-62c1-41a7-95c0-bb3f05ce8703.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，metersphere-接口自动化-场景-用您的文件引用确实获取不到变量，用jmeter引用这个文件也是返回同样的结果。

用文本编辑器打开该文件，重新编辑后保存-再次上传csv文件则显示和请求都正常，所以判断是您的文件格式问题。

修改文件编辑后上传jmeter调用结果：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/167047608-11551233-28d7-46f4-afbe-d0498dc1b807.png">
修改文件编辑后metersphere调用结果：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/167047690-48436b5a-bab6-4426-a996-fb31b559fb90.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/167047725-c420fb57-c5fe-4ac1-9b86-ef6e639b5c76.png">
