### ISSUE TITLE
[FEATURE] 表单类型请求数据的描述被隐藏了起来，使用上感受放出来更好，可以一眼看见参数含义

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#12928]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

感觉还是以前放出来好点，可以一眼就知道参数的含义是什么，现在还得点开看，不然都不知道参数时干什么的
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/13564069/164645932-4135959b-ac77-4692-9d3a-c963315a976d.png">
<img width="992" alt="image" src="https://user-images.githubusercontent.com/13564069/164646012-b058a89f-cac9-4e64-bcd6-39628c1ca6ee.png">

建议都放外面会比较好

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
