### ISSUE TITLE
[BUG]公共用例库删除全部只会删除 10 条

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#12933]
### MeterSphere 版本

19.2

### 使用外置数据库

否

### 问题描述

公共用例库全选数据，每页显示 10 条，批量删除全部，结果只删除 10 条

### 重现步骤

1.每页显示 10 条
2.批量选择全部数据，大于 10 条
3.点击批量删除

### 期待的正确结果

删除所有用例

### 附加信息

<img width="771" alt="image" src="https://user-images.githubusercontent.com/36387811/164689496-03312057-1e7f-4bfd-803b-bd5a581f3d73.png">

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
新版本已修复
