### ISSUE TITLE
接口自动化中创建步骤和测试报告步骤不一致

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#1294]
**请描述您的需求或者改进建议.**
1.在接口中引入了逻辑控制器比如如下图：
![image](https://user-images.githubusercontent.com/30932762/106230466-838aeb00-622a-11eb-88de-1e51da4cbb0c.png)
2.执行后结果报告如下：
![image](https://user-images.githubusercontent.com/30932762/106230484-8f76ad00-622a-11eb-8d07-a63390ae915e.png)

在场景中如果有if控制器，场景步骤是第五步，但是测试报告里面的测试步骤会按照执行从新排序，变成了4

**请描述你建议的实现方案**
测试报告显示的步骤和场景一致

**Comment by youliyuan-fit2cloud** [comment]
v1.7.1 已修复
