### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by xucw** [metersphere/metersphere#12947]
### 请描述您的问题

node controller项目中的FileUtils类中有三个字符串常量：
public static final String BODY_FILE_DIR = "/opt/metersphere/data/body";
public static final String JAR_FILE_DIR = "/opt/metersphere/data/node/jar";
public static final String JAR_PLUG_FILE_DIR = "/opt/metersphere/data/node/plug/jar";
请问：这三个目录下分别是什么文件/jar包？能否提供一下？

**Comment by AgAngle** [comment]
分别是接口测试发送请求中文件参数所对应的文件，还有自行上传的jar包等，可以直接在服务器的对应目录查看
