### ISSUE TITLE
[FEATURE]使用SQL进行前后置按列存储变量时，返回的结果为非标准格式JSON，自定义脚本处理不便

### ISSUE THREAD

**Issue by Fit2CloundGhh** [metersphere/metersphere#12966]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

[场景描述]
当使用SQL进行后置处理，按列存储变量时，获取到的变量（JSONArray）值为非标准Json数据，需要自定义脚本进行额外的处理，并且对于一般使用用户来说处理起来不是很方便。

[操作步骤]
1、通过sql后置操作按列存储变量
![image](https://user-images.githubusercontent.com/92966838/164960111-eb1e7f7c-722e-4dae-a069-b948874d2e49.png)
2、自定义脚本获取变量并进行其他业务操作时，变量值为非标准的JsonArray数据，需要脚本进行额外的数据处理
![image](https://user-images.githubusercontent.com/92966838/164960169-931d81a1-4b60-4748-9738-586a744e7853.png)

[改进建议]
方案一：在步骤1中，按列存储变量的时候，是否可以在ms后台将数据Json格式化，用户获取到的数据即为可以直接操作的Json数据
方案二：如果依旧需要用户自行处理，是否可以在右侧语法建议栏汇总给出代码示例建议。

### 请描述你建议的实现方案

方案一：在步骤1中，按列存储变量的时候，是否可以在ms后台将数据Json格式化，用户获取到的数据即为可以直接操作的Json数据
方案二：如果依旧需要用户自行处理，是否可以在右侧语法建议栏汇总给出代码示例建议。

**Comment by Hyyfit** [comment]
感谢反馈，已规划排期。
