### ISSUE TITLE
能否支持自定义扩展mockjs

### ISSUE THREAD

**Issue by xujiesh0510** [metersphere/metersphere#1296]
**请描述您的需求或者改进建议.**

能否支持自定义扩展mockjs, 自定义mockjs 的变量

**请描述你建议的实现方案**

提供一个界面，填写 mockjs 变量名称 , 扩展js 内容。保存后即可 使用 @xxx  的变量

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快排期实现，同时不仅针对 mockjs ，针对其他语言的前后置脚本也可以提供类似的函数扩展机制。

**Comment by xujiesh0510** [comment]
谢谢。主要是因为 测试人员水平参差不齐，不一定会写java, 但是js 应该基本都会写写.
