### ISSUE TITLE
[BUG]系统设置-用户-选择当前页所有用户，批量添加用户组无效

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#12967]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

系统设置-用户-选择当前页所有用户，批量添加用户组无效，有的用户能添加上项目，有的加不上，或者只能加上部分项目；

### 重现步骤

1. 系统设置-用户
2. 选择当前页所有用户，点击“批量添加用户组”
3. 添加用户组
4. 返回用户页面查看，并未成功添加项目，当前页里有的添加成功了，有点没成功，有点只添加成功了部分项目

### 期待的正确结果

1. 不管是为当前页面用户还是全部用户批量添加用户组及用户组下面的项目，都应该添加成功

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/164960647-9a2fd670-af9a-4e7b-8891-3d821fe2e36f.png)
![image](https://user-images.githubusercontent.com/77324661/164960708-0ccc2a76-60b0-45f9-9bfa-36ec8af6a251.png)

![image](https://user-images.githubusercontent.com/77324661/164960747-146e958c-03d2-4185-8976-6a854a416ecb.png)

**Comment by youliyuan-fit2cloud** [comment]
没有复现，请描述这个PM用户组是什么类型？系统，工作空间还是项目类型？工作空间和项目类型 的话所属工作空间是哪个？

**Comment by binbin0406** [comment]
这个是偶现发生的，麻烦多试几次，从我的截图可以看出确实是有问题的，客户也复现了。

**Comment by binbin0406** [comment]
https://user-images.githubusercontent.com/77324661/165510233-2a17818a-f175-410d-b048-ab1db140fec6.mp4

**Comment by binbin0406** [comment]
以上为问题复现的视频，请关注视频中用户的“用户组2”，这个用户组原本有2个项目，后来批量添加了多个项目后提示成功，但回到用户页面查看还是原来的2个项目，并未新增。

**Comment by zyyfit** [comment]
操作了很多次，也没有复现，能否给一个可以复现的环境？

**Comment by zyyfit** [comment]
这个问题跟用户远程看过了，用户以为这个操作是xx功能的，其实我们系统里是不支持这个功能的，属于用户对系统理解的问题
