### ISSUE TITLE
[FEATURE]测试用例导出xmind，打开后拓扑[1]结构变更、[2]展示与在线编辑页有所出入

### ISSUE THREAD

**Issue by Fit2CloundGhh** [metersphere/metersphere#12970]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

**[场景描述]**
测试用例导出xmind格式文件，在本地使用xmind软件打开后，脑图拓扑结构以及标签、id等属性展示有所出入，可读性较差。

**[场景步骤]**
1、导出用例列表为xmind文件，使用本地xmind软件打开

- MS在线编辑界面，脑图展示
![image](https://user-images.githubusercontent.com/92966838/164965413-55196b10-fc62-41e7-a61e-70e17f3138ab.png)

- 本地Xmind软件打开，脑图展示
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/92966838/164965436-2f9ed5ef-0838-4bc8-8a83-fac78754c4fb.png">

**[建议方案]**
1、理想情况下，能够保证和在线的页面一致是最好的情况。
2、考虑xmind的兼容性问题，保证一致也许有点困难，但是至少需要：

- 将英文字符，能够配合使用中文清晰展示
- **用例步骤**不建议和 标签、id等属性同级别展示，希望能够单独级别展示用例步骤

### 请描述你建议的实现方案

1、理想情况下，能够保证和在线的页面一致是最好的情况。
2、考虑xmind的兼容性问题，保证一致也许有点困难，但是至少需要：

- 将英文字符，能够配合使用中文清晰展示
- **用例步骤**不建议和 标签、id等属性同级别展示，希望能够单独级别展示用例步骤

**Comment by Hyyfit** [comment]
感谢反馈，目前设计如此，主要是考虑到有些用户是脑图上编辑用例导入到ms中，能在ms中正常展示用例，所以需要有特定的英文标识标题、id等。
“用例步骤单独级别展示”，这里可以考虑优化，待开发调研后规划。感谢您的反馈。
