### ISSUE TITLE
 状态码 非 200的 接口测试用例 都是  执行结果：未通过

### ISSUE THREAD

**Issue by xujiesh0510** [metersphere/metersphere#1297]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.0-3c6a4849
**Bug 描述**
  状态码 非 200的 接口测试用例 ，未添加任何断言 ，都是  执行结果：未通过
对于restful 风格的接口，并不能按照 状态码 不等于200 就是错误来判断

**Comment by wangzhen-fit2cloud** [comment]
你好，请问状态码具体是多少呢？

**Comment by xujiesh0510** [comment]
400

**Comment by xujiesh0510** [comment]
我觉得应该让用户判断非200的状态码，来决定案例的成功与否。用户通过增加非200的状态码的断言来覆盖 系统默认的判断逻辑

**Comment by xujiesh0510** [comment]
@wangzhen-fit2cloud  我更新了详细

**Comment by wangzhen-fit2cloud** [comment]
你好，可以按如下方式添加断言。
![image](https://user-images.githubusercontent.com/27671436/107001103-05978880-67c4-11eb-8547-6ed03d0dfdb3.png)
