### ISSUE TITLE
[BUG]关闭windows服务器，监控详情显示被监控操作系统的指标数值

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#12985]
### 联系方式

ylc163@126.com

### MeterSphere 版本

v19.2

### 使用外置数据库

否

### 问题描述

关闭windows服务器，监控详情显示被监控操作系统的指标数值

### 重现步骤

1、关闭windows服务器，运行性能测试计划；
2、监控详情显示被监控操作系统的指标数值
![image](https://user-images.githubusercontent.com/46479742/164975141-3375ce94-63f4-4b5e-8791-40e6e7daf082.png)

### 期待的正确结果

监控详情显示被监控操作系统的指标数值

**Comment by liuruibin** [comment]
这个表格显示有缓存，如果图表没有数据的时候显示的是上一个图表的数据
