### ISSUE TITLE
[BUG]性能测试模块，自定义监控不支持windows服务器

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#12984]
### 联系方式

ylc163@126.com

### MeterSphere 版本

v19.2

### 使用外置数据库

否

### 问题描述

1、https://github.com/prometheus-community/windows_exporter/releases下载最新版windows监控组件；
2、将windows监控组件上传至服务器，并安装运行；
3、ms性能测试模块，高级配置添加监控；
4、运行性能测试

### 重现步骤

性能测试模块，自定义监控支持windows服务器

### 期待的正确结果

自定义监控支持windows服务器

### 附加信息

<img width="960" alt="24089c321c0da4e8bdf2af151ef3bc8" src="https://user-images.githubusercontent.com/46479742/164974860-6f4efa6f-9d2f-4fd1-8f55-743e5ea5a2ad.png">

**Comment by liuruibin** [comment]
默认提供的promQL是linux的，windows 的需要自行查询来写。我用这条语句来查询windows的cpu使用率: `100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle", instance="%1$s"}[1m])) * 100)` 其中 `%1$s` 是被监控节点的ip和端口，上面这条语句在执行时会变成 `100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle", instance="172.16.10.54:9182"}[1m])) * 100)`

**Comment by suifengylc** [comment]
我已经在高级配置里添加了具体的监控项，还是不显示具体指标
100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle", instance="192.168.190.131:9182"}[1m])) * 100)
![image](https://user-images.githubusercontent.com/46479742/164981673-7a9739e1-18ef-494c-b0bc-a2fbe017ff0b.png)
![image](https://user-images.githubusercontent.com/46479742/164981566-1cc81594-2b64-4b12-8955-13efe25de617.png)
或者
100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle", instance="%1$s"}[1m])) * 100)
![image](https://user-images.githubusercontent.com/46479742/164981787-800c3efa-f471-4342-93e7-b8ddd0f010b7.png)
![image](https://user-images.githubusercontent.com/46479742/164981818-88399235-551f-4993-af6f-288a2ca4d37f.png)
