### ISSUE TITLE
[BUG]系统所有的输入框都无法全选复制

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1298]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
系统所有的输入框都无法全选复制
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望能全选复制  这会方便好多。。
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问具体是哪里的输入框？经测试大部分输入框都可以全选并复制。
