### ISSUE TITLE
CSV文件设置变量，无法取到值

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1299]
**MeterSphere 版本**
版本: v1.7.0-3c6a4849

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
value = vars.get("uid");
result = value != void && value.length() > 0;
if (!result){
	msg = "assertion [${uid} is not empty]: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
}
![image](https://user-images.githubusercontent.com/33744331/106246141-990f0d80-6248-11eb-8664-ce70fd649b60.png)
![image](https://user-images.githubusercontent.com/33744331/106246188-adeba100-6248-11eb-94a4-9f8907920cd4.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，已确认该问题，我们会尽快修复。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
