### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by chyi-blip** [metersphere/metersphere#12993]
### MeterSphere 版本

1.9

### 请描述您的需求或者改进建议

当前接口测试只能分享单个接口的文档，不能按组或者按项目分享，希望能丰富进来。目前apifox和apipost这方面做的很好，支持各种方式分享导出

**Comment by Hyyfit** [comment]
是支持单个接口和多多接口的展示和分析分享。分组是根据左侧模块树来分组。


<img width="1145" alt="image" src="https://user-images.githubusercontent.com/95834771/167354589-52efebdd-3a1f-46a8-adc1-0ea45181398b.png">
