### ISSUE TITLE
[BUG]测试计划执行，测试报告中 场景用例 出现超时! 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#12995]
### 联系方式

shenkaibo

### MeterSphere 版本

1.19.2

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/30038088/165012528-46a9b3fa-206c-44f9-a948-38eb2a46f9a1.png)

测试计划报告id: b2287b04-7b42-4734-b843-25546e6806fe
最近的那条超时 场景报告id: ea611e13-4ad1-43a3-96e3-be7dce219159
测试计划 开始 结束时间 ： 2022-04-22 09:51:06 ~ 2022-04-22 10:54:00
执行方式：串行
触发方式：API 调用
![image](https://user-images.githubusercontent.com/30038088/165012645-def60aff-f780-41b7-9db7-46eadeb994f7.png)
这个是该测试计划中最后一个有场景信息的日志，在测试计划报告中是显示执行成功的，之后的场景 都是超时。
![image](https://user-images.githubusercontent.com/30038088/165012655-cc29cd90-f0a0-401f-b94e-ff0ac8a196f3.png)

![image](https://user-images.githubusercontent.com/30038088/165013818-b8b00046-4b91-46dd-b1fb-cbfadebb31a4.png))

在 api_scenario_report_result 表中 查不到 超时的场景的记录 

### 重现步骤

测试计划关联几十个场景，点击执行，选择串行执行，测试计划报告中 会出现 超时的 场景（不必现，出现概率很高）

### 期待的正确结果

测试计划正常执行，测试报告中 无超时场景。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本修改了，升级一下吧

**Comment by shenkaibo** [comment]
已升级完成，目前观察 正常
