### ISSUE TITLE
[BUG]测试计划，没有执行完成的 "测试计划", 点击report 进去后看到执行率是100%

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#12996]
### 联系方式

王进

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

测试计划，没有执行完成的 "测试计划", 点击report 进去后看到执行率是100%
![11fc23a165855fc050b6d2d592eac83](https://user-images.githubusercontent.com/76033005/165013220-4dee92ed-497b-4e80-9092-a3ccf03ceb26.jpg)

### 重现步骤

1. 创建一个测试计划，关联若干场景用例
2. 执行
3. 在执行结束前，点击报告图标 

### 期待的正确结果

要么给一个准确的值，要么告诉用户 “测试计划正在执行中，请等待”

**Comment by youliyuan-fit2cloud** [comment]
v1.20版本中已修复
