### ISSUE TITLE
自定义安装目录失败

### ISSUE THREAD

**Issue by ningdaqing** [metersphere/metersphere#13]
修改install.conf配置文件中的MS_BASE=/opt/metersphere目录。在安装的时候不会自动创建该目录。导致不能正常找到docker-compose文件

**Comment by wangzhen-fit2cloud** [comment]
收到，感谢。将在下个版本解决。
@AgAngle

**Comment by wangzhen-fit2cloud** [comment]
v1.0.1 版本中已修复
