### ISSUE TITLE
[BUG]接口测试请求超时，服务器后台测试正常

### ISSUE THREAD

**Issue by Richard-chenbin** [metersphere/metersphere#130]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/68156947/87617999-59b91d80-c74b-11ea-98bc-f65015a22ae1.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题现在还存在吗？
