### ISSUE TITLE
[BUG] [测试计划]下的[功能测试用例]左侧模块树目录消失

### ISSUE THREAD

**Issue by DLChenMR** [metersphere/metersphere#1300]
**MeterSphere 版本**
v1.7.0

**Bug 描述**
【测试计划】下的 【功能测试用例】 左侧模块树目录消失

**Bug 重现步骤**
1. 点击【测试跟踪】->选择【测试计划】列表中已经创建的计划
2. 进入“自己创建的计划”页面，发现【功能测试用例】左侧树目录没问题
3. 点击【接口测试用例】选项卡，再点击（切回）【功能测试用例】选项卡，发现其左侧树目录不见了
4. 在【功能测试用例】选项卡页面下，刷新页面，左侧树目录恢复

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/23427952/106250677-f0b07780-624e-11eb-946d-56fb8bf83e86.png)

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快确认并修复该问题。

**Comment by xulinde** [comment]
您好，该问题已修复，您直接升级到当前最新版本1.7.2就可以
