### ISSUE TITLE
[BUG]将用例树中的用例添加至公共用例库后，对用例库中该用例进行编辑并保存时，公共用例库中添加的用例被自动移除，功能实现有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13004]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

将用例树中的用例添加至公共用例库后，对用例库中该用例进行编辑并保存时，公共用例库中添加的用例被自动移除，功能实现有误，请修改

### 重现步骤

1.选定一条用例，添加至公共用例库；
2.添加成功后，编辑用例树中该用例，点击保存，查看保存结果；

### 期待的正确结果

2.保存成功，且公共用例库中被添加的用例不发生变化。

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/165029323-ccee76dd-4f16-46a1-9201-19af6fda3f85.png)
![image](https://user-images.githubusercontent.com/92150453/165029366-ea09ae8f-1bc6-4e77-91ec-5eb727e8a5df.png)
![image](https://user-images.githubusercontent.com/92150453/165029476-eb0794d7-8073-412f-a2b8-e3632ac0eefb.png)
![image](https://user-images.githubusercontent.com/92150453/165029497-8f9bae9f-cb68-4b9d-8456-0967424c3bad.png)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
