### ISSUE TITLE
[FEATURE]目前平台不支持WCF這類請求

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#13028]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

建议可以支持WCF请求，如下图所示，目前JMETER有一个空间 WebService(SOAP) request 支持这类的请求
![image](https://user-images.githubusercontent.com/37204403/165064188-d5f94af8-9050-45c4-bb51-6769ffb7dec1.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，带排期。
