### ISSUE TITLE
[BUG]写了好久的脚本或者接口文档，最后显示认证过期，数据没有保存

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1303]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
写了好久的脚本或者接口文档，最后显示认证过期，数据没有保存
**Bug 重现步骤**
1.  登录写脚本
2. 等待认证过期
3. 再写脚本，然后点击保存结果显示认证过期，数据消失
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们系统session过期时间默认是12h，正常应该不会出现认证过期，是不是您有其他操作引起的呢

**Comment by xulinde** [comment]
和issue#1473重复
