### ISSUE TITLE
[BUG] 自动化场景中对接口的覆盖率，统计不准确，该问题可复现

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13038]
### 联系方式

王进

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

自动化场景中对接口的覆盖率，统计不准确，接口已经被场景引用，但是覆盖率还是0%

### 重现步骤

1. 新建一个项目，维护 几个接口，添加几个场景
2. 创建一个场景，把所有接口导入到该场景，执行。
3. 至此，场景的接口覆盖率应该是 100%。但是还是0

看如下截图
![微信截图_20220426095415](https://user-images.githubusercontent.com/76033005/165204813-6c1d258b-f330-4b07-90ec-c40930c2e3bd.png)

![微信截图_20220426095954](https://user-images.githubusercontent.com/76033005/165204900-88c7499b-158c-4d5d-8ccc-1db4bf381857.png)

### 期待的正确结果

场景的接口覆盖率好像没有动态更新，需要优化成动态更新

### 附加信息

客户发现的问题，实测有效。

**Comment by youliyuan-fit2cloud** [comment]
这个问题1.20中没有复现了，等发布新版本再升级试试看

**Comment by 35plus** [comment]
liyuan，这个问题 1.20还有，复现步骤比较简单。
1. 新建一个全新的项目
2. 添加几个接口定义
3. 创建一个场景，引用 步骤2里面的接口
4. 执行，执行完成后，查看统计数据。 下面是刚刚的复测结果
![df67d06be0f332c16a759393230a96d](https://user-images.githubusercontent.com/76033005/165900610-029096c2-827b-4a95-bbc9-cb6780071b2e.png)
