### ISSUE TITLE
[BUG]跨項目應用場景，在被引用場景裡查看場景引用，顯示空

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#13039]
### MeterSphere 版本

V1.19.3

### 使用外置数据库

否

### 问题描述

跨項目應用場景，在被引用場景裡查看場景引用，顯示空
![image](https://user-images.githubusercontent.com/37204403/165205416-23a12493-2053-4262-b5ad-0e8f195d9631.png)

### 重现步骤

無

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.0中已修复该问题
