### ISSUE TITLE
[BUG]接口定义，请求路径包含空格，提示路径无效

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13036]
### 联系方式

王进

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

接口定义，请求路径包含空格，提示路径无效

### 重现步骤

1. 看一眼截图就明白了，新建一个接口，请求路径里输入URL，URL包含空格
2. 
![3825a5879693678c5624b7ae01721a4](https://user-images.githubusercontent.com/76033005/165199823-7d9b27f9-77bb-4828-9ce4-30f040f9bd4c.png)
![Uploading 1650935920(1).png…]()

### 附加信息

我查了一下，还真有 URL里包含空格的情况。

**Comment by youliyuan-fit2cloud** [comment]
这种定义不规范，暂不支持

**Comment by 35plus** [comment]
liyuan, 这个问题是这样的，就是客户这边 是保险行业，有get请求的场景，传进来的 参数 最后一个 是 保单 数据，有的保险公司  他的保单 确实是有空格的。帮忙请开发处理！感谢！

**Comment by youliyuan-fit2cloud** [comment]
v1.20.2-lts中已修复
