### ISSUE TITLE
[BUG]项目设置添加成员勾选后前端应该显示内容是name

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#13047]
### 联系方式

xufu.yang@fit2cloud.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

1、在项目设置中添加成员
2、返回list数据包括id和name
3、实际勾选成员前端输入框内应该显示是name字段更合理不是id字段  其他用户在进入看到信息如果是id其实不是很理解成员是谁
![image](https://user-images.githubusercontent.com/101856439/165214373-eb42e334-d516-4812-bba4-90c93e5762b2.png)

### 重现步骤

1、项目成员添加成员
2、勾选成员 检查 list接口信息 输入框内信息与id是一致的 

### 期待的正确结果

成员输入框应该显示name用户名

**Comment by Hyyfit** [comment]
感谢反馈，id是唯一的不可重复，name可重复，存在重名的情况下，无法判断是哪一位成员，所以显示的是id。
