### ISSUE TITLE
[BUG]postman导入的API中，如果在path中包含有变量，导入后再path中存在${xx},修改成{xx}后无法编辑。退出后再进入才可以编辑。API Case也是一样。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13042]
### 联系方式

王进

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

postman导入的API中，如果在path中包含有变量，导入后再path中存在${xx},修改成{xx}后无法编辑。退出后再进入才可以编辑。API Case也是一样。

简单来说就是 如果在path中包含有变量，导入后，第一次打开，无法编辑，需要保存，然后再进入，再次编辑。

有录屏，有测试文件，但是github没办法传

### 重现步骤

1. 导入 path中含有变量的postman文件
2. 在MS里面path中存在${xx},修改成{xx}后，尝试编辑rest页面字段，比如新增
3. 无法编辑，退出后再进入才可以编辑。API Case也是一样。

有录屏，有测试文件，但是github没办法传

### 期待的正确结果

可以正常编辑，目前可以绕过去这个问题，但是还是不方便

### 附加信息

早上提了一遍，但是找不到了，可能网络不好，没提成功。有录屏，有测试文件，但是github没办法传，如果需要可以随时联系。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.0已修复
