### ISSUE TITLE
[BUG]在性能测试报错的接口，下载 jtl 文件导入 jmeter，查看请求内容为空

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#13048]
### MeterSphere 版本

19.3

### 使用外置数据库

否

### 问题描述

在 Metersphere 执行性能测试，有报错的接口，导出jtl文件，在jmeter 中导入，查看到错误的接口的请求内容为空

### 重现步骤

1.执行性能测试（存在错误请求）
2.下载jtl 文件
3.在 jmeter 中创建线程组，添加查看结果树
4.导入从 Metersphere 下载的 jtl 文件
5.查看错误的接口信息

### 附加信息

![WechatIMG937](https://user-images.githubusercontent.com/36387811/165215511-7904af67-93f4-4ee1-80e7-457261054780.png)

**Comment by zhangxiang01** [comment]
这个问题已经修复了么
