### ISSUE TITLE
[BUG]第一次写脚本 不小心点击到其他地方，脚本数据全部丢失。

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1304]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
第一次写脚本 不小心点击到其他地方，脚本数据全部丢失。
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，未复现您说的问题，可以详细说下操作步骤吗
