### ISSUE TITLE
[BUG]接口测试创建场景报错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#13057]
### MeterSphere 版本

19.3

### 使用外置数据库

否

### 问题描述

在接口测试自动化页面，创建场景，弹出报错信息，不能创建场景

### 重现步骤

1.在接口自动化页面，点击“更多操作”，选择“创建场景”
2.填写完场景名称，点击确定，弹出报错信息

### 附加信息

<img width="1013" alt="截屏2022-04-26 下午2 43 17" src="https://user-images.githubusercontent.com/36387811/165238924-eea5a4e8-4dce-47f3-8650-bbd4c07e7a0a.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已修复，等新版本发布吧

**Comment by zrfit** [comment]
最新版本v1.20已解决
