### ISSUE TITLE
一键部署后无法正常启动

### ISSUE THREAD

**Issue by gtgbx** [metersphere/metersphere#1305]
在虚机上一键部署，只启动了ms-node-controller、mysql、kafka，docker容器也只有这三个，其余的都没有创建。

msctl start或stop时会报：libgcc_s.so.1 must be installed for pthread_cancel to work。

**Comment by wangzhen-fit2cloud** [comment]
你好，该问题应该是 docker 兼容性问题，请尝试升级下内核版本后再次启动。
