### ISSUE TITLE
[FEATURE]测试计划自动化定时任务不自动结束计划

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#13069]
### MeterSphere 版本

1.19.3

### 请描述您的需求或者改进建议

测试计划中定时任务去跑接口自动化是一个长期过程，不应该跑一次计划就结束掉，可以创建一个任务类型或者开关，不要执行完一次就更新计划状态为已完成

**Comment by Hyyfit** [comment]
您好，目前设计如此。
测试计划状态一共是有5个，定时任务执行的时候会自动切换状态，如果是通过的，则显示“已完成”。如果有未通过的，则显示“已结束”。如果不需要再执行的测试计划，可以切换到已归档中。
<img width="133" alt="image" src="https://user-images.githubusercontent.com/95834771/165423596-e512421f-6c47-4ad2-9753-a34d92eeea71.png">
