### ISSUE TITLE
[BUG] 场景用例点击‘调试’后页面显示前3步没有执行，只执行了后2步

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13095]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/165316000-2d0b30c9-860a-4570-9008-f4991087857c.png)
![image](https://user-images.githubusercontent.com/103017812/165316500-8f30c702-03f5-4187-a5f0-1ef730e59ec3.png)

### 重现步骤

1. 进入场景用例
2. 点击‘调试’
这个问题偶发性出现
3. 点击查看调试历史，发现5步都执行了

### 期待的正确结果

页面应正确的显示调试状态和结果

**Comment by zyyfit** [comment]
您好，没有复现这个问题，也没有遇到过这种问题，您的场景里前面几步是否有前后置步骤呢？方便把场景给我们看看吗？

**Comment by sac911** [comment]
这个场景的步骤就是截图里面那几步，没有前置和后置的步骤。这个问题也是偶发的，不是很稳定会出现。如何给你场景？

**Comment by sac911** [comment]
我感觉是否是更新不完整？在任务中心或者report里面看到的状态是对的。
有时候测试结果更新也是任务中心里面先更新，但是调试页面还没有结束。

**Comment by zyyfit** [comment]
调试应该不会生成报告，也不会在任务中心显示执行记录，调试-生成报告才会。
偶发的话，是无法再次复现了呢，还是可以复现，但是执行几次才会出现一次呢？

**Comment by sac911** [comment]
多执行几次就会有，1.20上就有。我有录屏，但是git上不能上传

**Comment by sac911** [comment]
![image](https://user-images.githubusercontent.com/103017812/165936228-c401816b-cc16-44af-9b18-6189c837aee0.png)
补充一下复现的截图

**Comment by zyyfit** [comment]
您好，我测试了一百多次，没有出现这种情况，您方便把可以复现的场景导出来给我们看看吗

**Comment by sac911** [comment]
不好意思，这个问题是偶发的，不是确定某个场景会出现，是任何场景都有可能遇到。另外我还遇到一个问题应该和这个问题是相同原因造成的：场景调试历史中看触发的调试已经完成了，但是场景用例页面没有任何的反应，‘调试’这个按钮一直在‘停止’状态。
![image](https://user-images.githubusercontent.com/103017812/167093984-da968897-1765-47f3-a576-70768deff258.png)

**Comment by zyyfit** [comment]
> 不好意思，这个问题是偶发的，不是确定某个场景会出现，是任何场景都有可能遇到。另外我还遇到一个问题应该和这个问题是相同原因造成的：场景调试历史中看触发的调试已经完成了，但是场景用例页面没有任何的反应，‘调试’这个按钮一直在‘停止’状态。 ![image](https://user-images.githubusercontent.com/103017812/167093984-da968897-1765-47f3-a576-70768deff258.png)

我知道你的意思，但是我们这边复现不出来，也没有办法排查问题呀，万一是跟场景有关系呢，就是你如果有一个场景能复现，你可以导出来，我用你能复现的这个场景试试，如果还是不能复现的话，再想别的办法

**Comment by 35plus** [comment]
zyyfit，情况是这样的，张总这边部署的环境是在新加坡的aws上，有的用户在国内，有的用户在国外。之前张总跟我沟通了情况，我也没复现出来。我的理解是：当用户点【调试】后，服务端执行，执行完返回到前端，然后前端渲染展示，我估计是前端页面等待后端结果 超时了，因为网络不稳定，导致前面几步执行了，但是结果没有展示出来。

这个问题社区和其他企业用户都没有反馈过。

**Comment by zyyfit** [comment]
> 

收到

**Comment by zyyfit** [comment]
1.20.4已修复，请等待发版后验证
