### ISSUE TITLE
[FEATURE] 场景用例编辑页面期望有多选checkbox

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13098]
### MeterSphere 版本

1.19.3

### 请描述您的需求或者改进建议

在场景用例编辑页面期望可以有多选步骤的方式，方便批量删除或者编辑
![image](https://user-images.githubusercontent.com/103017812/165326705-4d86c997-27f9-4b23-86c2-1357e95ebb19.png)

**Comment by Hyyfit** [comment]
目前的功能有批量的操作
<img width="128" alt="image" src="https://user-images.githubusercontent.com/95834771/165422862-dc9df101-7de4-43d1-a4ac-370cb9609c8a.png">
