### ISSUE TITLE
[BUG]测试跟踪>>测试用例：左侧模块选择最后一个层级。测试用例列表信息显示正常，点击“脑图”，报错。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#13109]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>测试用例：左侧模块选择最后一个层级。测试用例列表信息显示正常，点击“脑图”，报错。

### 重现步骤

前提条件：
1、用户权限已检测没有问题，属于项目管理员，所有项目管理员内所有功能权限。
2、测试用例的创建都是用列表模式创建的，不是脑图模式创建的。

复现：
1、选择：测试跟踪>>测试用例页签
2、左侧模块树状列表：选择树状模块的最低节点，右侧用例列表显示正常
3、点击【脑图】，系统出现错误提示。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/165431913-6306e96a-cd1c-4bac-b648-bbbe3a3d8195.png)

**Comment by ltfit** [comment]
你好 没有复现 是否有其他的特殊操作

**Comment by huangxine** [comment]
没有特殊操作。这个是客户的系统，当时交流时，客户的系统必现，也检查了相关项目和权限的配置，都没有发现问题

**Comment by youliyuan-fit2cloud** [comment]
> 没有特殊操作。这个是客户的系统，当时交流时，客户的系统必现，也检查了相关项目和权限的配置，都没有发现问题

测试用例是否方便导出来？可能用例有什么特殊格式
