### ISSUE TITLE
[BUG]测试跟踪>>测试用例>>更多操作>>新建用例：用此方法创建的用例，里面的【描述】字段输入信息后确定，此字段在什么都地方都查看不到。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#13110]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>测试用例>>更多操作>>新建用例：用此方法创建的用例，里面的【描述】字段输入信息后确定，此字段在什么都地方都查看不到。

### 重现步骤

1、测试跟踪>>测试用例>>更多操作>>新建用例：
2、在新弹窗测试用例界面，输入相关信息，点击确认。但是里面的【描述】字段输入信息后确定，此字段在什么都地方都查看不到。
3、并且也查看了MS底层数据库设置，测试用例表里都没有描述这个字段。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/165432165-d8bb6997-6847-4d0d-80e3-907f7779bc30.png)
![image](https://user-images.githubusercontent.com/78218624/165432801-7c43b184-7489-4cd3-946a-26d7ce4f1107.png)

**Comment by huangxine** [comment]
![image](https://user-images.githubusercontent.com/78218624/165433087-d3f7d45d-a9eb-429e-b27a-0df49b408d08.png)

**Comment by ltfit** [comment]
感谢反馈 后续版本媳妇

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已修复
