### ISSUE TITLE
[BUG]工作空间的操作日志，加载太慢了，超过一分钟以上

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13123]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

工作空间的操作日志，添加任何筛选条件搜索时加载太慢了，超过一分钟以上

### 重现步骤

1. 进入系统设置-工作空间-操作日志
2. 添加任意筛选条件，进行搜索
3. 一直加载中，需要刷新页面才可恢复

### 期待的正确结果

希望加载时长在可接受范围内（几秒）

### 附加信息

<img width="955" alt="5f769b8897100991f9a364bb09ac75f" src="https://user-images.githubusercontent.com/77324661/165445943-8aa69db4-68a1-49b3-b56e-3a20811be2f2.png">

**Comment by zyyfit** [comment]
没有复现，目前测试几十万条数据确实比较慢，但是几千条还是很快的，我的测试环境测试6000+条，没超过1秒
