### ISSUE TITLE
[BUG]工作空间和项目设置的操作日志，通过添加操作对象搜索条件，无法正确查出对应数据

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13126]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

工作空间和项目设置的操作日志，通过添加操作对象搜索条件，无法正确查出对应数据

### 重现步骤

1. 进入工作空间-操作日志、项目设置-操作日志
2. 添加操作对象搜索条件
3. 无法正确查出对应数据

### 期待的正确结果

应该可以根据操作对象搜索出对应的日志记录

### 附加信息

<img width="945" alt="6d507f66eeb6a9bed1dc3ad6034941e" src="https://user-images.githubusercontent.com/77324661/165446542-2c2369ea-36ea-4a93-9d52-ebff9f30ac40.png">
<img width="952" alt="88a4a83f098e69535061c519e82f858" src="https://user-images.githubusercontent.com/77324661/165446572-d6814a10-4076-4de5-993d-26943e26c94c.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.1已修复
