### ISSUE TITLE
[BUG]新建/保存环境时，保存后环境域名被清空

### ISSUE THREAD

**Issue by Xy-pinko** [metersphere/metersphere#13120]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

新建环境时填写了环境域名，保存后发现环境域名为空

### 重现步骤

新建环境

### 期待的正确结果

可以成功为环境添加域名

### 附加信息

![image](https://user-images.githubusercontent.com/62093362/165439730-abedf201-f419-4aa0-958f-3276b3b80fc8.png)

**Comment by Xy-pinko** [comment]
XUX 原来是要点添加才可以
![image](https://user-images.githubusercontent.com/62093362/165440208-af3105fa-0cec-42e3-9255-b84ab86269bc.png)

**Comment by wp-jackliu** [comment]
我勒个去，原来真需要这么操作。。。谁能想到会有这种变态的操作。
