### ISSUE TITLE
[BUG]工作空间的操作日志，总条数和按项目筛选的条数，总数对不上

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13129]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

工作空间的操作日志，总条数和按项目筛选后的条数，总数对不上

### 重现步骤

1 进入系统设置-工作空间-操作日志
2. 未添加筛选条件时查看总日志条数
3. 按项目分别筛选日志条数
4. 将所有项目下日志条数相加，与总日志条数不一致

### 期待的正确结果

工作空间下的总日志条数应与空间下所有项目的日志条数总和一致

### 附加信息

<img width="921" alt="64471880a12abd37c9b0298cf2b37b8" src="https://user-images.githubusercontent.com/77324661/165447310-b353f9f6-56e2-4613-902a-f693937ed491.png">
<img width="940" alt="ba755b26a35bf902cfb77db1996d6a3" src="https://user-images.githubusercontent.com/77324661/165447453-8b61fe9a-81c1-4a47-b202-d716d8914c25.png">
<img width="930" alt="89f949c8b9184254cea0cbddae96cb4" src="https://user-images.githubusercontent.com/77324661/165447511-c1e4dde0-627e-454c-bd9b-3f4c27bf72e9.png">

![Uploading b7cfce43c70caaf773481c8be786dca.png…]()

**Comment by binbin0406** [comment]
<img width="943" alt="b7cfce43c70caaf773481c8be786dca" src="https://user-images.githubusercontent.com/77324661/165448089-8da97865-a59d-4f67-9dd4-291155b2b210.png">

**Comment by zyyfit** [comment]
有的日志是不带项目的，比如登录
