### ISSUE TITLE
任务中心全部停止接口响应时间太长

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#13137]
### 联系方式

杨晓燕

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

1、跑一个测试计划后，点击全部停止，接口的响应时间在4min，这就导致测试计划已经执行完成了，还没有停止
2、换了几个环境测试，都是非必现，qa环境在20多秒（也挺慢的），但是客户环境是必现的

### 重现步骤

1、创建一个可以跑10分钟的测试计划
2、点击 全部停止
3、看network响应时间
4、4分钟左右接口回来，测试计划停止，但是任务管理的状态仍然显示success

### 期待的正确结果

1、缩短响应时间
2、任务管理的状态显示stopped

### 附加信息

<img width="1439" alt="1" src="https://user-images.githubusercontent.com/72729206/165435963-7cbd4968-8ea1-4aa6-80ea-703f874c7a9a.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/72729206/165459737-a1a5936e-84e5-40dc-b07f-8ad6de859365.png">

**Comment by fit2cloud-yangxiaoyan** [comment]
版本为1.19.3和1.20.0

**Comment by youliyuan-fit2cloud** [comment]
v1.20.1-lts已经优化这个问题
