### ISSUE TITLE
[BUG] 场景用例通过率显示为乱码

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13139]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

![Uploading image.png…]()

### 重现步骤

打开场景用例列表

**Comment by zrfit** [comment]
您好，看不到图片，能重新上传下吗？我们未复现该问题，能否导出场景我们尝试复现下。

**Comment by 35plus** [comment]
![image](https://user-images.githubusercontent.com/76033005/167355397-7cd96350-1ee2-42c4-b446-784b62635793.png)

这个是客户这边看到的，不太好复现。 我这边测试没有出现过。
