### ISSUE TITLE
jenkins运行测试后，MS后台没有生产报告[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1313]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.0-3c6a4849

**Bug 描述**
简要描述您碰到的问题
jenkins运行测试后，MS后台没有生产报告

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/106373444-77cb3000-63b4-11eb-8109-2293f58efa1f.png)
![image](https://user-images.githubusercontent.com/37016695/106373460-acd78280-63b4-11eb-975d-e502a9d5fb80.png)

![image](https://user-images.githubusercontent.com/37016695/106373454-992c1c00-63b4-11eb-8c5d-173d0a00ec00.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.1 版本已修复。

**Comment by G291131988** [comment]
> 你好，v1.7.1版本已修复。

我更新1.7.1回归发现，并没有修复哦，是我没更新好吗？
![image](https://user-images.githubusercontent.com/37016695/106576251-e4425c80-6577-11eb-9e1d-553997d2b756.png)
![image](https://user-images.githubusercontent.com/37016695/106576355-fd4b0d80-6577-11eb-8df5-0c17d1ecd958.png)

**Comment by xulinde** [comment]
需要下载最新的jenkins插件
