### ISSUE TITLE
[BUG]工作空间和项目设置的操作日志，功能用例从回收站恢复后，未展示对应的操作信息

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13132]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

工作空间和项目设置的操作日志，功能用例从回收站恢复后，未展示对应的操作信息

### 重现步骤

1. 进入工作空间-操作日志、项目管理-操作日志
2. 将功能用例从回收站恢复
3. 工作空间-操作日志、项目管理-操作日志，未展示对应的操作信息

### 期待的正确结果

正确显示从回收站恢复用例的操作日志

### 附加信息

<img width="950" alt="f185a41ba83b4bb3ad25606e94074af" src="https://user-images.githubusercontent.com/77324661/165449757-1fa82df2-fb4c-4c18-ba4a-4c986e393bf0.png">

**Comment by ltfit** [comment]
感谢反馈下个版本优化

**Comment by ltfit** [comment]
新版本已修复
