### ISSUE TITLE
[BUG]分享出来的接口没有描述信息 json结构图多了个"0"

### ISSUE THREAD

**Issue by nunter** [metersphere/metersphere#13138]
### 联系方式

lx.vs@qq.com

### MeterSphere 版本

 v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/10915931/165459948-3e3ddda5-15ca-4e7d-886c-8ced976260fc.png">

### 重现步骤

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/10915931/165460041-3233f145-e9b2-4e10-833c-e794c28f60b4.png">

### 期待的正确结果

json与备注正常显示，或者优化一下分享接口的界面（感觉不是很直观）
bug：https://github.com/metersphere/metersphere/issues/13003  的新增

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
