### ISSUE TITLE
选择了“执行方式”为执行测试计划中用例后，保存成功，再次打开编辑，回显没展示已选中的选项[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1314]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/106373494-0344c100-63b5-11eb-98ef-3b006e383ac1.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
