### ISSUE TITLE
[BUG]接口自动化场景导入，可以复制或引用场景本身

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#13155]
### 联系方式

ylc163@126.com

### MeterSphere 版本

v19.2

### 使用外置数据库

否

### 问题描述

之前的版本，接口自动化场景导入，是不可以复制或引用场景本身，现在可以了，但是引用或复制场景本身又没数据，这是需求调整了，还是...
![image](https://user-images.githubusercontent.com/46479742/165488684-7ab5507e-373c-4c04-9e9a-d8e8ab6fb3c9.png)

### 重现步骤

之前的版本，在接口自动化导入场景时，是不可以复制或引用场景本身。
现在可以，但是引用或复制场景本身又没数据

### 期待的正确结果

场景导入不支持复制或引用场景本身

**Comment by zrfit** [comment]
你好，接口自动化场景导入，是不可以复制或引用场景本身的，最新版本没有这个问题，可升级下。
