### ISSUE TITLE
[feature]环境配置完成以后，点击确定建议自动关闭弹窗

### ISSUE THREAD

**Issue by dragonhaimax** [metersphere/metersphere#1315]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
环境配置完成以后，点击确定建议自动关闭弹窗

**Bug 重现步骤**
1.  接口定义
2. 接口测试进行环境配置
3. 环境配置完成以后，点击确定。页面需要手动点击X 关闭弹窗
4. 

**期待的正确结果**
正确情况下应该是什么样的？
自动关闭弹窗

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/18454230/106379903-145bf500-63ea-11eb-9930-cfc1b2b94638.png)

![image](https://user-images.githubusercontent.com/18454230/106379893-fe4e3480-63e9-11eb-8067-d0d68713a1fd.png)

**Comment by dragonhaimax** [comment]
![image](https://user-images.githubusercontent.com/18454230/106380391-dc09e600-63ec-11eb-96bb-c8656b73a93a.png)
这里建议，创建模块的时候可以像创建标签的时候一样用键盘回车键进行完成输入。不是额外的再点击+号完成模块命名

**Comment by wangzhen-fit2cloud** [comment]
> **MeterSphere 版本**
> 您所使用的 MeterSphere 版本是？
> 1.7
> **Bug 描述**
> 简要描述您碰到的问题
> 环境配置完成以后，点击确定建议自动关闭弹窗
> 
> **Bug 重现步骤**
> 
> 1. 接口定义
> 2. 接口测试进行环境配置
> 3. 环境配置完成以后，点击确定。页面需要手动点击X 关闭弹窗
> 
> **期待的正确结果**
> 正确情况下应该是什么样的？
> 自动关闭弹窗
> 
> **截图**
> 如果有截图，请附上截图.
> ![image](https://user-images.githubusercontent.com/18454230/106379903-145bf500-63ea-11eb-9930-cfc1b2b94638.png)
> 
> ![image](https://user-images.githubusercontent.com/18454230/106379893-fe4e3480-63e9-11eb-8067-d0d68713a1fd.png)

因为可能在该页面一次性配置多个环境信息，点击确定后仅保存了当前编辑的环境，没有关闭弹窗。暂时不做修改。

**Comment by wangzhen-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/18454230/106380391-dc09e600-63ec-11eb-96bb-c8656b73a93a.png)
> 这里建议，创建模块的时候可以像创建标签的时候一样用键盘回车键进行完成输入。不是额外的再点击+号完成模块命名

请跟踪 #1413
