### ISSUE TITLE
[BUG]部分用例已经提交，下次进行回归测试的时候，发现附件丢失 ，偶现问题

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#13160]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v19.1

### 使用外置数据库

否

### 问题描述

偶现问题
有时候上传的附件确认已经存在了，但下次回归执行的时候还是会没有掉

### 重现步骤

偶现问题
猜测：编辑的时候，对方可能也在编辑，导致冲掉了
但是在环境中手动复现，一个浏览器打开脑图进行编辑，另一个浏览器使用列表用例上传附件。先进行脑图保存，附件存在。上传附件在保存脑图，也依然存在。

### 期待的正确结果

可以保证附件或者用例的存在，不会出现丢失情况

**Comment by ltfit** [comment]
你好  是什么格式的附件 呢，能否提供更详细的信息

**Comment by libb-test123** [comment]
.txt的文件
