### ISSUE TITLE
[BUG]性能测试添加自定义监控，在获取不到数据的情况下，图标没数据，表格里依然有数据，且错误的显示到了上一个节点的监控表格数据

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#13167]
### 联系方式

shenkaibo

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

性能测试添加自定义监控，在获取不到数据的情况下，图标没数据，表格里依然有数据，且错误的显示到了上一个节点的监控表格数据

### 重现步骤

![029b83e3a9b7737f453afc4ecbf6fc1](https://user-images.githubusercontent.com/30038088/165526047-6afe3b3a-785b-417c-ac79-e9f97af6dc9c.jpg)

**Comment by zyyfit** [comment]
没有出现这种图表没数据的情况，也没有复现表格里显示上一个监控节点的问题，能详细描述一下操作步骤吗
