### ISSUE TITLE
[FEATURE]功能用例导入时，责任人（ID）判断了大小写 期望修改成不判断大小写

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#13179]
### 联系方式

xufu.yang@fit2cloud.com

### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

1、创建用户的时候大小写忽略判断，但是在实际导入功能用例时大小写处理识别成两个用户
![image](https://user-images.githubusercontent.com/101856439/165690414-2272fb48-f55b-4b0b-b4d4-97edf3cb78d5.png)
![image](https://user-images.githubusercontent.com/101856439/165690542-ec9b6c46-7ab9-4b23-8761-042310d6ac6c.png)

账号一般不区分大小写
![58b9a4db29623f79c7f4a5f4b60f2bb](https://user-images.githubusercontent.com/101856439/165690652-d7a35f5c-d9ce-4205-8f9e-f2f437507818.jpg)
使用邮箱试过改大小写不同登陆后时同一用户

### 重现步骤

导入功能用例责任人 使用跟用户id一样但大小写不同 点击上传提示

### 期待的正确结果

1、上传成功
2、不提示该项目下没有用户

**Comment by ltfit** [comment]
nihao 我试了下 没有区分啊。
![image](https://user-images.githubusercontent.com/99794211/165725242-4641856c-0fe3-493c-93f1-2e2bb8ddae99.png)

**Comment by fit2cloud-yangxufu** [comment]
> 

应该是不区分的  大写跟小写是一个用户

**Comment by youliyuan-fit2cloud** [comment]
> > 
> 
> 应该是不区分的 大写跟小写是一个用户

目前设计如此，我们转需求了

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。

**Comment by luty2018** [comment]
已经修改成不区分大小写，但是仅对新安装系统生效，考虑到历史数据会有重名情况。
可以检查是否存在重名，如不存在可以执行以下SQL
ALTER TABLE USER CHANGE id id VARCHAR ( 50 ) COLLATE utf8mb4_general_ci;
