### ISSUE TITLE
[BUG]接口用postman可以调通，用metersphere 试用平台发送接口请求后，一直在转圈

### ISSUE THREAD

**Issue by cheese-jie** [metersphere/metersphere#13170]
[QUESTION]接口用postman可以调通，用metersphere 试用平台发送接口请求后，一直在转圈，请求不成功，是什么问题呢
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/61402953/165671790-8be5feb6-85cd-4b6a-be43-6318f9952a9d.png">

**Comment by zyyfit** [comment]
应该是网络不通吧，建议改成本机 ip 试试

**Comment by cheese-jie** [comment]
换成ip也不行～

**Comment by zyyfit** [comment]
不通的话应该就是网络问题，如果你是在本地部署的，建议直接用在线/离线包部署

**Comment by sac911** [comment]
有可能是代理的原因。我以前也遇到过，去掉代理就可以了。我们内网代理会block websocket。
