### ISSUE TITLE
[BUG]功能用例，新建用例操作，用例名称输入1，然后直接点击“保存”，报错。如图所示

### ISSUE THREAD

**Issue by NickLans** [metersphere/metersphere#13187]
### 联系方式

Lans007@126.com

### MeterSphere 版本

版本:   v1.18.2-f641f6f6

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/104554834/165698917-40cedffa-2f44-4b82-abe2-6d415f0f52b1.png)

### 重现步骤

1、点击顶部导航：测试跟踪-功能用例
![image](https://user-images.githubusercontent.com/104554834/165699843-92a5d49d-95b5-428c-93a5-8d26933811e6.png)

2、然后新建用例，用例名称输入：1，直接点击“保存”，就报错了
![image](https://user-images.githubusercontent.com/104554834/165700014-a03d7615-8568-46a2-b180-b5e26e350cae.png)

**Comment by NickLans** [comment]
用例名称输入正常的内容（不是“输入1才会出现这个情况”），直接点保存，报错

**Comment by ltfit** [comment]
你好我这边没有复现 升级到最新版本尝试下呢
