### ISSUE TITLE
[BUG]场景公共自定义变量配置，变量框可以拉宽一些，把右侧空白区域填满，数据展示更全，更美观

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1318]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
场景公共自定义变量配置，变量框可以拉宽一些，把右侧空白区域填满，数据展示更全，更美观

**Comment by wangzhen-fit2cloud** [comment]
你好，你好，v1.7.2 已修改
