### ISSUE TITLE
[FEATURE]接口测试报告不显示总览

### ISSUE THREAD

**Issue by LizardYang** [metersphere/metersphere#13184]
### 联系方式

lizard@sztus.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

接口测试报告生成后进行导出，导出后的文档无总览情况

### 重现步骤

1.接口测试执行后生成测试报告
2.查看测试报告显示正确，如下图：
![image](https://user-images.githubusercontent.com/46311914/165697975-95f04345-92c9-4c50-bca2-023671d0348e.png)
3.导出测试报告，无总览情况显示，如下图：
![image](https://user-images.githubusercontent.com/46311914/165698113-1a7f9a41-6c2f-425f-9937-48a17d8dbc37.png)

### 期待的正确结果

显示接口测试执行后总览情况

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
