### ISSUE TITLE
[BUG]编辑窗口界面滑动鼠标窗口会消失

### ISSUE THREAD

**Issue by zjj0425** [metersphere/metersphere#132]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.0.2

**Bug 描述**
编辑窗口界面鼠标左或右滑动，窗口会消失

**Bug 重现步骤**
1.  切换到系统设置模块
2. 点击用户->创建用户，弹出创建用户窗口
3. 用鼠标左或右滑动

**期待的正确结果**
鼠标左滑动或右滑动，编辑窗口不会消失

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
应该是左右滑的操作触发了浏览器的回退/前进操作，我们优化下这个地方

**Comment by luty2018** [comment]
下周的版本会上，请留意交流群版本更新通知

**Comment by wangzhen-fit2cloud** [comment]
@zjj0425 你好，可否提供下你的邮箱地址
