### ISSUE TITLE
[BUG] xmind上传没有预期结果的步骤，导出excel版本用例，该步骤显示成null

### ISSUE THREAD

**Issue by guojiex** [metersphere/metersphere#13201]
### 联系方式

1036479561@qq.com

### MeterSphere 版本

看不到。。

### 使用外置数据库

否

### 问题描述

用xmind模板，如果测试用例的步骤，只有一项（用例步骤），没有预期结果项，上传系统，页面显示没有问题
但是把用例导出成excel，对应的预期结果就会变成

"1.null
2.null
3.前端会报错，整个操作失败"

### 重现步骤

用xmind模板，如果测试用例的步骤，只有一项（用例步骤），没有预期结果项，上传系统，页面显示没有问题
但是把用例导出成excel，对应的预期结果就会变成

"1.null
2.null
3.前端会报错，整个操作失败"

### 期待的正确结果

"1.前端会报错，整个操作失败"

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by ltfit** [comment]
此问题在1.20.2-lts版本修复
