### ISSUE TITLE
[FEATURE]操作日志显示具体修改内容不明显

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#13227]
### 联系方式

xufu.yang@fit2cloud.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

平台变更记录功能展示内容以文件代码形式展示内容
只知道对什么对象做过操作但不知道干了什么
比如说新添加了一个csv文件 或删除
新添加一个接口 或删除接口里某一个参数
用户只看到一个修改对象记录  对于后面维护人员部署开发或技术人员很难理解这里操作是什么
![image](https://user-images.githubusercontent.com/101856439/165939654-9c40c685-83b8-4dec-822a-73daebab27ff.png)

### 重现步骤

创建场景case并保存
修改其中某些内容 后查看日志
![image](https://user-images.githubusercontent.com/101856439/165939898-674f9daa-345c-4fac-b004-c7306b7e2d5a.png)

### 期待的正确结果

显示内容更易理解 即使不是技术人员也能看懂

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
