### ISSUE TITLE
[FEATURE]接口自动化场景用例编写界面，一键展开或缩起功能按钮较实用

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#13223]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

接口自动化场景用例编写界面，批量缩起功能按钮较实用

### 请描述你建议的实现方案

接口自动化场景用例编写界面，批量缩起功能按钮较实用

之前版本是有场景步骤一键展开和缩起的功能

**Comment by Hyyfit** [comment]
功能是有的

<img width="134" alt="image" src="https://user-images.githubusercontent.com/95834771/167351488-96272604-3a29-4b72-9a10-448c92dffd08.png">
