### ISSUE TITLE
[BUG] 在项目上无法将平台已有的用户加为项目成员

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13225]
### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

在项目成员设置页面，检索不出用户
1. 检索平台用户，用户已存在
![image](https://user-images.githubusercontent.com/103017812/165925438-9305128b-7c0d-4752-a0f6-93eec5c0b381.png)

2. 在项目添加成员页面检索不到用户（1.20版本遇到，之前版本是好的）
![image](https://user-images.githubusercontent.com/103017812/165925644-1aa09a0a-7d55-4326-965b-e35742f56ef6.png)

### 重现步骤

1. 检索平台用户，用户已存在
2. 在项目添加成员页面检索不到用户（1.20版本遇到，之前版本是好的）

### 期待的正确结果

可以检索出平台已经存在的用户

**Comment by zyyfit** [comment]
您好，您需要先把这个用户添加到当前工作空间，项目可以添加的成员都是当前工作空间下的
