### ISSUE TITLE
[FEATURE]数据驱动测试用例支持

### ISSUE THREAD

**Issue by fightingplane** [metersphere/metersphere#1322]
**请描述您的需求或者改进建议.**
目前无法支持数据驱动测试用例，在设计测试用例时会有重复劳动。

**请描述你建议的实现方案**
可参考RobotFramework的数据驱动

**Comment by wangzhen-fit2cloud** [comment]
你好，能否再详细描述下？

**Comment by fightingplane** [comment]
比如用户登录，需要输入用户名、密码
所以用户名和密码就是数据输入项
这个时候一般会根据等价类设计正确和错误输入的用例
用户名                            密码
正确用户名                     正确密码
正确用户名                     错误密码
错误用户名                     错误密码
这样只需要设计一个用例，以数据的形式执行多个测试用例，减少重复劳动
