### ISSUE TITLE
[QUESTION]账号和密码不正确？这是什么情况

### ISSUE THREAD

**Issue by liufei96** [metersphere/metersphere#13232]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/38318090/166098556-9deb4815-1cbb-4c5f-b2de-2f4dbf14f5c0.png)

**Comment by Hyyfit** [comment]
https://metersphere.io/docs/faq/system_management/
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/95834771/167350498-aa13fc6a-ca93-47c3-9976-2347ecbc79b2.png">
