### ISSUE TITLE
[BUG]测试计划列表-当前状态字段，已完成和已结束状态更新有问题；以及测试进度计算错误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13230]
### 联系方式

张树彬

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

1. 测试计划中全部用例执行完成后，测试计划列表的当前状态未更新为“已完成”，且测试进度未显示100%
2. 测试计划中全部用例执行完成后，且已到达计划结束时间，测试计划列表的当前状态未更新为“已结束”，且测试进度未显示100% 

### 重现步骤

1. 测试计划中关联功能用例
2. 所有用例全部执行完成
3. 测试计划列表当前状态仍显示进行中，且测试进度未显示100%
4. 所有用例全部执行完成，且已到达计划结束时间，测试计划列表当前状态仍显示进行中，且测试进度未显示100%

### 期待的正确结果

按规则正确显示当前状态及按执行情况正确计算测试计划

**Comment by youliyuan-fit2cloud** [comment]
清下缓存再试试

**Comment by binbin0406** [comment]
清缓存试过了，还是有问题，必现

**Comment by binbin0406** [comment]
这个是百分百复制的，可以在测试计划里添加5条功能用例，先执行2条，测试进度就是错的，剩下3条全执行完，测试进度也是错的，而且也不会变成已完成状态

**Comment by zyyfit** [comment]
按照

> 这个是百分百复制的，可以在测试计划里添加5条功能用例，先执行2条，测试进度就是错的，剩下3条全执行完，测试进度也是错的，而且也不会变成已完成状态

按照这个步骤也还是没复现

**Comment by zyyfit** [comment]
您长时间未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
