### ISSUE TITLE
[BUG]进入测试计划，在功能用例列表中直接更改“执行结果”字段状态后，测试计划列表中的'当前状态"应该联动更新

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13231]
### 联系方式

张树彬

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

进入测试计划，在功能用例列表中直接更改未执行用例的“执行结果”字段状态，应该与测试计划列表中的“当前状态”字段联动

### 重现步骤

*前置条件：测试计划内只关联了功能用例
1. 当测试计划的当前状态为“未开始”，在测试计划里的功能用例列表将”执行结果“字段状态从“未开始”改为任意执行结果状态后，测试计划的当前状态应该变更为”进行中“，但现在没有联动改变。
2. 当测试计划的当前状态为“进行中”，在测试计划里的功能用例列表将所有用例”执行结果“字段状态选择任意执行结果状态后，测试计划的当前状态应该变更为”已完成“，但现在没有联动改变。

### 期待的正确结果

通过操作测试计划里用例列表上”执行结果“字段状态，能够按规则与测试计划的当前状态进行联动

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/165983383-c836e703-d229-4833-bc98-bbd66244c4cc.png)
![image](https://user-images.githubusercontent.com/77324661/165983554-781615c5-1b20-4739-bdba-40ef95619290.png)

**Comment by youliyuan-fit2cloud** [comment]
清下缓存再测试一下吧

**Comment by binbin0406** [comment]
清缓存试了，必现。而且不止我的环境，客户的环境也一样有问题

**Comment by binbin0406** [comment]
那先改2吧

**Comment by zyyfit** [comment]
问题2 在1.20.2版本已修复，在1.20.2中也没有复现问题1
