### ISSUE TITLE
[FEATURE]接口自动化场景变量CSV“变量名”易产生歧义

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13236]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 请描述您的需求或者改进建议

接口测试-接口自动化-场景变量，添加CSV类型变量的时候，“变量名”填写项容易产生误导（如果不仔细看用户手册的话），以为是引用的CSV中的变量名，希望在输入的地方能加个提示（如：“CSV 文件的名称，仅起到标记作用，无法在场景步骤中通过 ${varName} 的形式引用该变量”）或改下字段名子，以提升用户体验。
![image](https://user-images.githubusercontent.com/18514555/166132647-308fb13a-b5f2-4856-aaf2-f1409c3d1a4d.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
