### ISSUE TITLE
[BUG]DELETE方法接口使用变量作为域名的场景URL拼接错误

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#13239]
### MeterSphere 版本

1.20.0

### 使用外置数据库

否

### 问题描述

URL中使用变量作为域名
Method为DELETE的接口，URL拼接错误，如图：

![image](https://user-images.githubusercontent.com/51286902/166451286-89371c52-ce4a-41ba-b903-b0b07fcf2bf1.png)

### 重现步骤

1.URL中使用变量作为域名
2.Method为DELETE的接口调试

### 期待的正确结果

拼接不应出现如图错误，已确认其他的Method类型无此问题。

**Comment by youliyuan-fit2cloud** [comment]
没有复现，你这个变量哪里添加的？

**Comment by warmmilk** [comment]
![image](https://user-images.githubusercontent.com/51286902/166849895-09b511b5-ff19-4ac7-bfab-853e31a1051e.png)
域名是通过变量带入的（如上图）
环境信息里面没有配置域名（如下图）
![image](https://user-images.githubusercontent.com/51286902/166850061-475e04e1-1a45-475d-93ee-deaa1076158b.png)

**Comment by warmmilk** [comment]
如下图，在场景里面用脚本定义的变量，应该算是变量提取类型。

![image](https://user-images.githubusercontent.com/51286902/166861038-bb81bec4-6bd9-4c4e-937e-ba9dda0ac1cc.png)

**Comment by warmmilk** [comment]
做了如下对照试验，注释掉原来的变量，将变量在全局变量中进行定义，结果相同

![image](https://user-images.githubusercontent.com/51286902/166861660-7fadfcfd-d8ea-495a-a1cf-8bcd4329bcee.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.1-lts中已修复
