### ISSUE TITLE
[BUG]测试计划发邮件运行报告链接丢失，如图

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#13237]
### 联系方式

410782876@qq.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

测试计划发邮件运行报告链接丢失

### 重现步骤

定时任务测试计划

### 期待的正确结果

附带测试报告链接

### 相关日志输出

```shell
无
```

### 附加信息

![1651404956(1)](https://user-images.githubusercontent.com/25195509/166144101-575129ff-f980-407a-aec4-36dcb53850cd.png)

**Comment by youliyuan-fit2cloud** [comment]
开源版本不支持了
