### ISSUE TITLE
[BUG]DELETE方法的接口，body体无效

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#13240]
### MeterSphere 版本

1.20.0

### 使用外置数据库

否

### 问题描述

Method为delete的接口使用数组类型作为body体执行批量删除，但是body体无效
![image](https://user-images.githubusercontent.com/51286902/166457230-09eadc2e-7364-42ec-b174-0ebb3203304a.png)

### 重现步骤

1.Method为delete的接口使用数组类型作为body体执行批量删除
2.接口调试失败，提示缺少有效的body体

如上图，body体没有出现在调试信息中

### 期待的正确结果

DELETE方法也能够使用body体带入参数执行批量删除

**Comment by youliyuan-fit2cloud** [comment]
你确定你写的body 里面格式正确吗？
看第一个截图格式都没有校验通过啊

**Comment by warmmilk** [comment]
这种方式在其他方法实测是允许的。
好吧，我改用常量，也是同样的结果，没有body体。请确认1.20.0，是否DELETE方法忽略了body体。
![image](https://user-images.githubusercontent.com/51286902/166850741-6d0d786d-692c-4c20-bb71-19dd960968bb.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.1-lts中已修复
