### ISSUE TITLE
[BUG]导出的配置再导进来,之前用例关联的数据库连接配置相关都会失效掉

### ISSUE THREAD

**Issue by a3436281** [metersphere/metersphere#13253]
### 联系方式

421486833@qq.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

导出的配置再导进来,之前用例关联的数据库连接配置相关都会失效掉，把用例中需要用到的数据库连接信息如：导入的前置SQL重新删除后再新建一个，就可以查询成功

### 重现步骤

![1@LIR2$LXH7D6`_~AKFE3PR](https://user-images.githubusercontent.com/49898349/166857511-4a55674d-7422-4bdf-93df-a3e4512b7d9e.png)

**Comment by youliyuan-fit2cloud** [comment]
没太理解你的问题，请详细描述一下复现步骤和相关截图，谢谢~
