### ISSUE TITLE
[FEATURE]建议开源版也支持web自动化

### ISSUE THREAD

**Issue by tygk** [metersphere/metersphere#13262]
### MeterSphere 版本

v1.19.3-b1

### 请描述您的需求或者改进建议

个人感觉开源版也应该支持web自动化，毕竟现在成熟的自动化框架基本都会涵盖web自动化，接口自动化，这是做自动化必不可少的2个方向，企业版可以限制节点数，资源数以及使用人数这些方面，如果连web自动化都不支持的话，相信不少人会弃用的

**Comment by maninhill** [comment]
感谢您的关注。飞致云旗下还有多个开源项目，比如 MeterSphere、JumpServer、DataEase等，我们一贯坚持开源优先，尽最大努力平衡好开源版和企业版。在目前MeterSphere 现有的几大功能中，我们选择最后发布的 UI 模块作为企业版功能，就是平衡的结果，请大家理解。
