### ISSUE TITLE
v2.0.0（2022-7-28） 版本发布计划

### ISSUE THREAD

**Issue by luty2018** [metersphere/metersphere#13263]
### 请描述您的问题

<img width="949" alt="image" src="https://user-images.githubusercontent.com/36292514/166871444-696f76c0-49e2-4f01-a60e-c870fbfc1b89.png">

**Comment by maninhill** [comment]
MeterSphere 版本号命名规则为：v大版本.功能版本.Bug修复版本。比如：

- v1.0.1 是 v1.0.0 之后的Bug修复版本；
- v1.1.0 是 v1.0.0 之后的功能版本。

像其它优秀开源项目一样，MeterSphere 将按月发布功能版本、按年度发布 LTS（Long Term Support）版本。

MeterSphere 的最新 LTS 版本为 v1.20 LTS。MeterSphere 下一个 LTS 版本为 v2.10 LTS，预计在 2023 年第二季度发布。

**Comment by maninhill** [comment]
6月份我们将把精力放在1.20-lts 版本的bug修复和优化上。

**Comment by wudamyw** [comment]
测试计划支持添加UI自动化用例。这个得赶紧啊，不然哪叫自动化？一个一个点 ：）

**Comment by whthomas** [comment]
请问1.X会支持迁移到2.X吗？

**Comment by Evan-guo131** [comment]
目前缺陷管理缺少缺陷状态筛选功能，开发和测试要查找未关闭的缺陷很麻烦，随着缺陷越来越多，经常要漏掉一些未关闭的缺陷。还有缺陷管理不能根据处理人进行筛选，对应的开发也很难找到自己所负责的缺陷，使用起来很不方便。希望能增加缺陷状态的筛选和根据处理人进行筛选

**Comment by TesterYu** [comment]
导入导出为什么不能批量，还有用例为啥不支持复制啊
