### ISSUE TITLE
[BUG]性能测试，测试报告版本对比功能，存在测试报告缺失或多显的问题，且排序混乱

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#13273]
### 联系方式

ylc163@126.com

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

性能测试，测试报告版本对比功能，存在测试报告缺失或多显的问题，且排序混乱
报告缺失
![image](https://user-images.githubusercontent.com/46479742/166891445-4bc102dd-1dd5-498e-97d9-0294bec846d6.png)
![image](https://user-images.githubusercontent.com/46479742/166891595-70db390f-556d-4651-af46-241798375264.png)
多显
![image](https://user-images.githubusercontent.com/46479742/166891871-7f409471-864c-43db-aab3-ad514bcf703a.png)
![image](https://user-images.githubusercontent.com/46479742/166891994-c81b2f9f-3c32-425c-be6b-3ca55cde694f.png)
排序混乱
![image](https://user-images.githubusercontent.com/46479742/166892136-bcde5010-41f9-4222-b59c-7a21caf72169.png)

### 重现步骤

性能测试，测试报告版本对比功能，存在测试报告缺失或多显的问题，
报告缺失
![image](https://user-images.githubusercontent.com/46479742/166891445-4bc102dd-1dd5-498e-97d9-0294bec846d6.png)
![image](https://user-images.githubusercontent.com/46479742/166891595-70db390f-556d-4651-af46-241798375264.png)
多显
![image](https://user-images.githubusercontent.com/46479742/166891871-7f409471-864c-43db-aab3-ad514bcf703a.png)
![image](https://user-images.githubusercontent.com/46479742/166891994-c81b2f9f-3c32-425c-be6b-3ca55cde694f.png)
排序混乱
![image](https://user-images.githubusercontent.com/46479742/166892136-bcde5010-41f9-4222-b59c-7a21caf72169.png)

### 期待的正确结果

性能测试，测试报告版本对比功能，显示正常且排序正确

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by ltfit** [comment]
新版本已修复
