### ISSUE TITLE
[BUG]条件控制器判断为空时不能进入循环

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13270]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20-lts

### 使用外置数据库

否

### 问题描述

1.上一个请求提取变量值为空
2.使用条件控制器，当变量值为空时进入循环
3.调试场景

### 重现步骤

1.上一个请求提取变量值为空
2.使用条件控制器，当变量值为空时进入循环
3.调试场景
4.条件控制器内的请求竟然没有执行
![image](https://user-images.githubusercontent.com/88763608/166883192-617c5d22-1708-4b25-9cc8-46b122201e83.png)

### 期待的正确结果

调试控制器内的请求会执行

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.2已修复
