### ISSUE TITLE
[BUG]性能测试报告对比，在性能测试报告列表页，选择了n个报告，但是对比报告页面可能是M个报告。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13278]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

性能测试报告对比，在性能测试报告列表页，选择了n个报告，但是对比报告页面可能是M个报告。
比如下面这个报告对比页面，我只选了4个，但是展示了超过4个

![1651741410(1)](https://user-images.githubusercontent.com/76033005/166892929-ad79126f-6055-488e-8eea-363b8bd88e7f.png)

### 重现步骤

问题的重现，可能需要用我们的测试环境和账号：
1.  登录，https://east-ms.fit2cloud.com/， 选普通账号
    wangjin/1qaz@WSX
2.  导航到 性能测试》报告
3.  任选一个个28号的报告，“性能测试demo” （这些报告都是一个测试跑出来的）
4.  点击报告对比图标，弹出一个页面，把页面改成显示20条报告记录
5.  在该页面上选择  两个28号的报告，再选一个27号的，再选一个其它日期的，对比报告。
6.  多试几次，有时候 对比报告页面显示的报告比选择的少，有时候 比用户手动选择的多。

### 期待的正确结果

选几个展示几个

### 附加信息

客户那里1.19.3有这个问题，我们在1.20也复现出来了。

**Comment by 35plus** [comment]
这个bug是某企业客户的，基金公司，客户这边比较急。帮忙尽快安排修复！

**Comment by ltfit** [comment]
你好 登录该账号 尝试多次没有复现 是有别的其他操作么
