### ISSUE TITLE
对接JIRA，问题类型选择子任务的时候，提交缺陷会报错[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#13284]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

对接JIRA，问题类型选择子任务的时候，提交缺陷会报错，"问题类型是一个子任务，但未指定父问题关键字或id“

### 重现步骤

1、正常对接Jira
2、使用Jira缺陷模板，问题类型选择子任务
![image](https://user-images.githubusercontent.com/35896106/166902677-b619329b-29b9-4a1c-81ee-86b8f5d08c09.png)
3、测试跟踪-缺陷管理-创建缺陷
![4d8853cf599f19223c8f74fe6651ab1](https://user-images.githubusercontent.com/35896106/166903031-34f6248e-194f-4992-ae6f-47d8c073fd8b.png)

### 期待的正确结果

可以正常提交子任务类型的缺陷

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
不好意思，目前我们不支持子任务作为缺陷
