### ISSUE TITLE
[BUG]新场景的变量跟旧场景是一样，使用的是旧场景的变量

### ISSUE THREAD

**Issue by zhujiayizjy** [metersphere/metersphere#13289]
### 联系方式

290847134

### MeterSphere 版本

v1.19.3-b1

### 使用外置数据库

否

### 问题描述

在新的接口流程中，引用别的流程，在新的场景中赋予相同名称的变量，引用的变量仍是引用的流程中旧的变量。

### 重现步骤

新场景的变量跟旧场景是一样，使用的是旧场景的变量

### 期待的正确结果

新场景的变量跟旧场景是一样，使用的是新场景的变量

**Comment by zyyfit** [comment]
1.20.5版本修复这个问题，请等待发版后验收
