### ISSUE TITLE
[FEATURE]增加错误报告中，针对错误时的response的内容查询

### ISSUE THREAD

**Issue by ted-zhu** [metersphere/metersphere#13286]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 请描述您的需求或者改进建议

<img width="909" alt="image" src="https://user-images.githubusercontent.com/58538139/166903640-bb524a7a-6c33-4ea2-b73b-882877dbac0b.png">
测试报告中只显示了错误500, 404, 麻烦增加可以查看具体错误的内容

**Comment by Hyyfit** [comment]
感谢反馈，目前设计如此，请求失败的情况下，是看不了的。
