### ISSUE TITLE
[FEATURE] Helm Chart 仓库补充部署文档说明

### ISSUE THREAD

**Issue by sekfung** [metersphere/metersphere#13285]
### MeterSphere 版本

v1.20.0-lts

### 请描述您的需求或者改进建议

Helm 部署如何使用外部服务，如kafka，zookeeper。麻烦补充文档说明一下，谢谢

**Comment by shenkaibo** [comment]
你好，可以在values.yaml中将kafka.enabled 和 zookeeper.enabled 改成 false，不安装 kafka 和 zookeeper。
![image](https://user-images.githubusercontent.com/30038088/167057917-694fadd9-6c94-4800-a769-8537bb308bcc.png)
然后 在values.yaml中将common.kafka.host、common.kafka.port 等信息改成外部地址

**Comment by shenkaibo** [comment]
文档已补充，请参考：https://metersphere.io/docs/installation/kubernetes_installation/
