### ISSUE TITLE
[BUG] postman中导入接口API中已有的接口，接口列表中API和CASE中删除对应的接口，但场景中对应的接口没有自动更新删除

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1330]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
接口列表中API和CASE中删除对应的接口，场景中对应的接口没有自动更新删除
**Bug 重现步骤**
1.  从postman中导入接口API中已有的接口，导入时选择全量覆盖
2. 接口列表中【API】【case】中接口被删除
3. 接口自动化 场景中该接口没有删除

**期待的正确结果**
正确情况下应该是什么样的？
场景中对应的接口自动更新删除
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106425354-c523cc00-649e-11eb-95d9-4a8cc61125f7.png)
![image](https://user-images.githubusercontent.com/55734318/106425594-0ae09480-649f-11eb-8a4e-a2a090ac7717.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，场景中如果选择复制的方式添加接口，确实是不会被删除的。
