### ISSUE TITLE
[BUG]通过excel导入的功能用例，脑图查看报错

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#13306]
### 联系方式

ylc163@126.com

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

通过excel导入的功能用例，脑图查看报错

### 重现步骤

功能用例导入选择excel模板，然后切换至脑图查看功能用例，选择导入的功能用例模块，展开查看，报错“Cannot read properties of undefined (reading 'renderNode')“
![image](https://user-images.githubusercontent.com/46479742/167084896-6ea123a4-eedd-49a5-bb5d-2af60ffed340.png)
![image](https://user-images.githubusercontent.com/46479742/167084667-004742ce-a9c3-4945-b223-844de75dd57f.png)

### 期待的正确结果

脑图可以正常查看excel模板导入的用例

**Comment by suifengylc** [comment]
你可以用excel维护几条用例，再导入，导入之后切换至脑图查看导入的用例

**Comment by suifengylc** [comment]
你导入的是哪个模块，就点击那个模块前面的加号展开
![image](https://user-images.githubusercontent.com/46479742/167126783-1553416b-81c8-464e-90b8-772d97d17f5d.png)

**Comment by ltfit** [comment]
是的 我这是正常的。你把你的用例导出下 我这边看下 
![image](https://user-images.githubusercontent.com/99794211/167234089-2ee13dee-127b-4a11-b233-1498124c8a56.png)

**Comment by suifengylc** [comment]
给我一个邮箱，我发你

**Comment by ltfit** [comment]
tao.li@fit2cloud.com

**Comment by suifengylc** [comment]
已发，看看收没收到

**Comment by ltfit** [comment]
收到了 看了下 模版格式不对 邮件已回复

**Comment by suifengylc** [comment]
这个问题应该很多人遇到过，既然能导入成功就不是格式问题，建议对此处进行充分的测试，在进行优化

**Comment by ltfit** [comment]
感谢反馈 后续优化下这个问题

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已优化
