### ISSUE TITLE
[BUG]UI测试-元素库模块，更改封装关键字的所属目录时，对应所属目录下的元素数量未同步更新，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13310]
### MeterSphere 版本

1.20lts

### 使用外置数据库

否

### 问题描述

UI测试-元素库模块，更改封装关键字的所属目录时，对应所属目录下的元素数量未同步更新，请修改

### 重现步骤

1.UI测试-元素库模块，更改封装关键字的所属目录为UI测试，查看UI测试目录的元素数量统计情况；

### 期待的正确结果

1.UI测试目录的元素数量统计正确显示为1；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/167090880-91473323-2313-46d9-9d1b-140f7f1ce220.png)

**Comment by ltfit** [comment]
已知问题 下个版本修复

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已修复
