### ISSUE TITLE
[BUG] 元素操作时有遮挡，建议优化一下

### ISSUE THREAD

**Issue by liyi594100909** [metersphere/metersphere#13320]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

https://i.postimg.cc/wTVhY7cw/20220506171347.png

### 重现步骤

1、点击“+”，展开操作动作
2、添加前置步骤或后置步骤

**Comment by zrfit** [comment]
您好，点击+是展开步骤添加选项，添加步骤后点击X，则可收起选项。
感谢您的反馈，如后续还是觉得使用不便，我们会收集意见反馈给产品人员，根据反馈意见再进行优化方案的设计。
