### ISSUE TITLE
[BUG] 报名统计中删除预留模块

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13331]
### 联系方式

lsj

### MeterSphere 版本

1.20.0-lts

### 使用外置数据库

否

### 问题描述

请见截图：
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/41712985/167148448-97d2343f-4819-4fcf-9ae6-4aeaf34a90b7.png">

### 重现步骤

请参考截图。

**Comment by ltfit** [comment]
感谢反馈 后续优化下

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已修复
