### ISSUE TITLE
[BUG] 页面显示小问题

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13330]
### 联系方式

lsj

### MeterSphere 版本

1.20.0-lts

### 使用外置数据库

否

### 问题描述

请见图：

<img width="843" alt="image" src="https://user-images.githubusercontent.com/41712985/167148112-3fa688a3-9b94-4644-a2c3-9f5add8c1929.png">

### 重现步骤

请参考截图。

### 期待的正确结果

无滚动条。

**Comment by ltfit** [comment]
感谢反馈 下个版本优化修复下

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已修复
