### ISSUE TITLE
[BUG] 测试跟踪页面显示小问题

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13332]
### 联系方式

lsj

### MeterSphere 版本

1.20.0-lts

### 使用外置数据库

否

### 问题描述

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/41712985/167149179-98e16d80-21ec-4802-8eca-fb410472cbfa.png">

### 重现步骤

请参考截图。

**Comment by ltfit** [comment]
感谢反馈 后续版本优化下
