### ISSUE TITLE
[BUG] 提示文案的颜色问题

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13333]
### 联系方式

lsj

### MeterSphere 版本

1.20.0-lts

### 使用外置数据库

否

### 问题描述

<img width="721" alt="image" src="https://user-images.githubusercontent.com/41712985/167149961-8fc65b76-bf42-4ccf-baf2-e410546a8e9f.png">

### 重现步骤

请参考截图。

**Comment by ltfit** [comment]
感谢反馈，下个版本优化下

**Comment by ltfit** [comment]
1.20.2-lts 这个版本已修复
