### ISSUE TITLE
[QUESTION]集成禅道关联项目时提示“ID不存在或其它错误”

### ISSUE THREAD

**Issue by Roger535** [metersphere/metersphere#13339]
### 请描述您的问题
metersphere设置集成禅道bug
<img width="749" alt="截屏2022-05-07 上午10 36 39" src="https://user-images.githubusercontent.com/18340418/167234680-b4d3000e-efc3-4370-a551-f3cf6ebf897c.png">
这里设置已完成

<img width="765" alt="截屏2022-05-07 上午10 25 22" src="https://user-images.githubusercontent.com/18340418/167234572-d37be655-c52c-42bb-a669-8946eab557d8.png">
但是设置关联项目ID时提示"ID不存在或其它错误"，项目id，产品id都试过了，都是这个提示，请问下这个是什么问题

**Comment by zrfit** [comment]
您好，请检查下禅道系统中项目ID是否存在，如果不存在则会报这个提示，如果存在则点击检查按钮提示OK。

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/167244204-c42fb089-b19d-49ae-a980-378780c151dc.png">

**Comment by Roger535** [comment]
<img width="1061" alt="截屏2022-05-07 下午3 58 29" src="https://user-images.githubusercontent.com/18340418/167245271-95ab74e3-4de3-4535-b706-404126f81159.png">
<img width="663" alt="截屏2022-05-07 下午4 00 11" src="https://user-images.githubusercontent.com/18340418/167245307-c8c2924c-d1ea-4860-a229-c054f4b7e12e.png">
看提示信息我这个是要填写产品id的，不过我都试过了，都是提示“ID不存在或其它错误”

**Comment by zrfit** [comment]
您好，我的意思是您**禅道系统的项目列表中是否含有015这个ID？** 可以截图看看吗？

**Comment by youliyuan-fit2cloud** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/54612864/167250564-444b69b4-ebc0-4b94-af3a-bda056a876ab.png">

这个地方有没有添加账号，可以试试

**Comment by ousinka** [comment]
1.20.1-lts版本，在集成验证通过和第三方账号填写正确的前提下：
填写 项目id，任务id，需求id，bug id，均提示“ID不存在或其它错误”。
