### ISSUE TITLE
性能测试报告未自动刷新页面数据

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1333]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33744331/106443398-674fae00-64b7-11eb-92f9-41f2a108ad79.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，能否再详细描述下该问题？没有明白具体是什么现象。

**Comment by xyziven** [comment]
我也遇到了，在性能测试执行过程中，报告页面没有任何刷新，当手动刷新可以看到报告的最新数据。

**Comment by AshuaiNe** [comment]
在性能测试过程中，性能报告数据未自动刷新，每次需要手动刷新页面，尝试一下跑性能测试就看得出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2021年2月1日(星期一) 晚上7:33
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "2818820548"<2818820548@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] 性能测试报告未自动刷新页面数据 (#1333)





 
你好，能否再详细描述下该问题？没有明白具体是什么现象。

**Comment by wangzhen-fit2cloud** [comment]
你好，请问是否有配置nginx反向代理。

**Comment by zyyfit** [comment]
已在1.7.2版本验证通过
