### ISSUE TITLE
[BUG]UI自动化里添加javascript脚本后，无法正常执行场景

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13345]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20-lts

### 使用外置数据库

否

### 问题描述

1.创建UI自动化场景
2.在某个步骤，添加简单的javascript脚本
3.执行脚本后没有正常执行生成报告

### 重现步骤

1.创建UI自动化场景
2.在某个步骤，添加简单的断言和javascript脚本
![image](https://user-images.githubusercontent.com/88763608/167240416-e469fa27-8757-431e-a35c-9e5b3bc0c087.png)
3.执行脚本后没有正常执行生成报告
![image](https://user-images.githubusercontent.com/88763608/167240435-bb2efd42-b822-4ad1-af29-6d92b7f9b177.png)
4.禁用后置脚本后，又可以正常执行了
![image](https://user-images.githubusercontent.com/88763608/167240470-ac4f091d-27e2-40a3-beef-f94aa957ca55.png)

### 附加信息

[Metersphere_Ui_UItest (2).zip](https://github.com/metersphere/metersphere/files/8644557/Metersphere_Ui_UItest.2.zip)

**Comment by zrfit** [comment]
您好，v1.20.3-lts版本已修复。
