### ISSUE TITLE
能不能改善下接口里面的case UI交互？

### ISSUE THREAD

**Issue by xujiesh0510** [metersphere/metersphere#1334]
**请描述您的需求或者改进建议.**

 
![image](https://user-images.githubusercontent.com/10271679/106448642-05467700-64be-11eb-8bb2-1212c5ff41af.png)

这个 交互好难用， 测试用例都在下方，并且面积比较小，给人一种压迫感，每次都要低头去屏幕下方去找案例。
**请描述你建议的实现方案**
能不能改成 左右格式的，并且铺满浏览器。 
![image](https://user-images.githubusercontent.com/10271679/106449088-91589e80-64be-11eb-82f6-39be348c90cc.png)

就像上图 一样。  左边是 测试用例名称列表，点一下名称，右边是 案例的内容。这样展示空间大，方便操作

**Comment by wangzhen-fit2cloud** [comment]
你好，接口用例的弹出列表现在增加了全屏按钮，可以先用全屏的编辑模式，我们在后续的版本再进一步优化下这里的交互。
