### ISSUE TITLE
[BUG]v1.20.0-lts-c599aa69 版本的数据库驱动 无法连接 mysql 5.6版本 

### ISSUE THREAD

**Issue by caixiaocai** [metersphere/metersphere#13342]
### 联系方式

MeterSphere 交流群28--昵称：will

### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

rds：5.6.16-log
![image](https://user-images.githubusercontent.com/24862236/167235350-73cc9a2e-5bbc-43ff-adf7-5a65c15935eb.png)

### 重现步骤

本地尝试不用版本的jdbc复现问题：

![image](https://user-images.githubusercontent.com/24862236/167235542-6ff86cab-b27f-48c3-8e3f-e194a1352d26.png)

### 期待的正确结果

![image](https://user-images.githubusercontent.com/24862236/167235509-60db32c5-ac99-49cf-8a87-0d92a17617e1.png)

**Comment by youliyuan-fit2cloud** [comment]
支持mysql5.7以上版本~
