### ISSUE TITLE
[FEATURE]删除组织，工作空间不要删除关联内容

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1335]
**请描述您的需求或者改进建议.**
删除组织后相关用例都被删除无法恢复

**请描述你建议的实现方案**
删除组织、工作空间无需在数据库中删除关联用例或者相关数据

**Comment by wangzhen-fit2cloud** [comment]
你好，删除组织、工作空间时已经给出了提醒，目前我们的设计中所有资源都需要归属于某个组织下的工作空间。请问如果保留相关数据，该数据的归属问题你这边有什么建议吗？

**Comment by xiongxiaoqing614** [comment]
可以类似放入回收站然后有个功能专门来清除，我看你们有把模块删除的时候就有放入回收站的功能，没必要在删除某个组织的时候硬删除DB里关联的数据，因为关联性复杂的情况可能会有人考虑不够周全，不删除还有补救的可能，或者mysql db默认开启备份

**Comment by xiongxiaoqing614** [comment]
删除接口定义里面的模块好像没放到回收站。。。
