### ISSUE TITLE
执行单条用例详情界面，当点击向上/向下箭头切换用例之后，当条用例的执行人变成了自己，建议执行人不要变化

### ISSUE THREAD

**Issue by norry2022** [metersphere/metersphere#13366]
### MeterSphere 版本

 v1.19.1-4fb56789

### 请描述您的需求或者改进建议

执行单条用例详情界面，当点击向上/向下箭头切换用例之后，当条用例的执行人变成了自己，建议执行人不要变化

**Comment by Hyyfit** [comment]
感谢反馈，已规划优化，待排期。
