### ISSUE TITLE
执行测试用例界面，建议增加显示执行进度

### ISSUE THREAD

**Issue by norry2022** [metersphere/metersphere#13365]
### MeterSphere 版本

v1.19.1-4fb56789

### 请描述您的需求或者改进建议

执行用例过程中，不论是执行”我的用例”还是“所有用例”，建议在”关联测试用例“右边的空白处（也可以是在底部条数左边空白处），显示当前测试用例的执行情况，包括进度，通过多少，fail多少等等信息

**Comment by Hyyfit** [comment]
在测试计划的报告统计中，有展示当前计划的执行情况。
<img width="464" alt="image" src="https://user-images.githubusercontent.com/95834771/167349754-1b92c992-9e60-4972-a6df-a1660622b06f.png">
