### ISSUE TITLE
安装报错 ： 从非LTS版本升级到LTS版本后，后续将只能升级新的LTS版本，无法再自动升级到非LTS版本

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#13369]
### 请描述您的问题

 curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh
![image](https://user-images.githubusercontent.com/5927005/167246971-fd7c8a7c-99de-4871-9801-739c25ca8b54.png)

**Comment by seasoncool** [comment]
同问。
请问 1.9.3 如何【安全】升级到 1.20.1-lts 的版本？

1. ./msctl upgrade ?
2. 下载离线包？
3. 其它？

**Comment by AgAngle** [comment]
从非LTS版本升级到LTS，直接升级既可；从LTS升级到非LTS目前来说是不会有兼容性问题，但是安装脚本里有检查，可以注释掉install.sh 中对应的内容；如果后续LTS升级涉及到兼容性问题，官网文档应该会说明如何处理

**Comment by AgAngle** [comment]
另外说明下，目前是LTS的版本，用upgrade 命令只能升级到当前LTS的最新版本，要升级最新非LTS的版本，需要下载在线或者离线安装包下载

**Comment by seasoncool** [comment]
谢谢，已下载离线包，解决 非LTS -> LTS 升级问题。
