### ISSUE TITLE
[BUG]测试计划j里执行功能用例后，在功能用例列表没有更新执行结果

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13363]
### 联系方式

张树彬

### MeterSphere 版本

1.20.1

### 使用外置数据库

否

### 问题描述

测试计划j里执行功能用例后，在功能用例列表没有更新执行结果

### 重现步骤

1. 测试计划里关联功能用例
2. 执行用例，选择任意执行结果
3. 切换到功能用例列表查看该用例的执行结果字段状态仍未“未执行”

### 期待的正确结果

功能用例列表用例的执行结果状态应与测试计划的用例执行结果状态同步更新

### 附加信息

![Uploading 7b950a44b10cad70b0a75b3cbfa8081.jpg…]()![Uploading 7b950a44b10cad70b0a75b3cbfa8081.jpg…]()
![569415412e2ff6d50c2bfed4a4c90bf](https://user-images.githubusercontent.com/77324661/167245421-891f8716-757f-45c0-af3e-dadc924b7638.jpg)

**Comment by ltfit** [comment]
感谢反馈 下个版本修复下
