### ISSUE TITLE
[BUG]场景用例未执行用例数字不对

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1336]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7

**Bug 描述**
简要描述您碰到的问题
未执行数量不对

**Bug 重现步骤**
1.  执行场景用例
2.  查看接口测试首页上场景用例图表
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
未执行的数量应该是0

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72964047/106459095-51001d00-64cc-11eb-881c-1ad7b0e77593.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.1 版本已修复。
