### ISSUE TITLE
[BUG]测试计划里功能用例的执行人为A时，B用户批量更改用例的执行结果后，执行人未变更为A

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13364]
### 联系方式

张树彬

### MeterSphere 版本

1.20.1

### 使用外置数据库

否

### 问题描述

测试计划里功能用例的执行人为A时，B用户批量更改用例的执行结果后，执行人未变更为A

### 重现步骤

1. 测试计划里关联功能用例，A用户为用例选择了执行结果
2. B用户在测试计划功能列表批量更改用例执行结果
3. 用例执行人未变更为B；但B用户在单个用例的详情页重新选择执行结果后，执行人就会变更

### 期待的正确结果

不同账号批量编辑用例执行结果后，应该同步更新执行人

### 附加信息

![1651911754(1)](https://user-images.githubusercontent.com/77324661/167245917-dd373c86-5135-466c-a8a0-221480be4a2e.jpg)
![image](https://user-images.githubusercontent.com/77324661/167245916-a70a1517-989c-4568-a5e9-12fb11f56bd9.png)

**Comment by ltfit** [comment]
下个版本修复
