### ISSUE TITLE
[功能用例]测试跟踪下的功能用例组合查询条件建议增加“执行结果”；

### ISSUE THREAD

**Issue by shuangshuang2022** [metersphere/metersphere#13370]
### MeterSphere 版本

版本:   v1.19.1-4fb56789

### 请描述您的需求或者改进建议

进入测试跟踪->功能用例->高级搜索，组合查询条件建议增加“执行结果”；

### 附加信息

![image](https://user-images.githubusercontent.com/105104358/167247433-17f9385c-05c5-4977-9884-c1b86a953a99.png)
![image](https://user-images.githubusercontent.com/105104358/167247445-e5e1f01d-9a28-4b7f-b78a-e61ee7d45c72.png)

**Comment by Hyyfit** [comment]
下一个版本的功能：高级搜索支持自定义字段搜索，可以实现添加“执行结果”为搜索条件。
目前正在开发，v2.0.0版本（6月23日）就上线了～
