### ISSUE TITLE
[BUG] 性能测试JTL下载提示OutOfMemory

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#1337]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2

**Bug 描述**
简要描述您碰到的问题
性能测试运行24小时后，下载jtl时失败，提示OutOfMemory，查询数据库提示jtl大小约为1GB

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.1 版本已修复。
