### ISSUE TITLE
[BUG][接口测试导入模块]，通过postman/swagger导入成功后，test模块无法调试

### ISSUE THREAD

**Issue by lanlan2019** [metersphere/metersphere#13378]
### MeterSphere 版本

 v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

[接口测试导入模块]，通过postman/swagger导入成功后，配置好环境后，test模块无法调试成功，只能重新生成case，在case层没问题。

### 重现步骤

1.导入接口-swagger模式
2.导入成功后，点击接口编辑进入到【test】模块
3.进行环境配置
4.选择对应的环境，在test模块中调试case，失败。获取不到环境。或者页面无响应

### 期待的正确结果

可以正常调试case

**Comment by zrfit** [comment]
您好，感谢您的反馈，通过swagger和postman导入接口到metersphere均可test调试成功，未复现该问题，能否把对应接口文件上传下并截图看下对应环境配置和test执行报错，便于我们进行复现定位，感谢！
