### ISSUE TITLE
[FEATURE]性能测试自动带出引用的外部jar包

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13377]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

**建议：** 通过接口case或接口自动化场景创建性能测试时，希望能够自动带出case或自动化场景中已引用的jar包。
**场景：** 在做接口测试时，有时要引用自定义的jar包工具，所以在“项目设置”-“文件管理中”上传了自己的jar包，测试没问题。但是创建性能测试时，还需要在“资源文件”中再从本地上传一遍jar包，略显麻烦。

### 请描述你建议的实现方案

方案一：通过接口case或接口自动化场景创建性能测试时，最好能自动带出引用的jar包。
方案二：通过接口case或接口自动化场景创建性能测试时，提示用户手工选择项目文件中已有的jar包。
方案三：”场景配置“-“资源文件”旁增加文案提示用户需要手工上传自己引用的jar，并且点击“加载文件”时能直接选择项目文件中已存在的jar包。

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
