### ISSUE TITLE
[BUG] 性能测试Response Time图表显示数据不全

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#1338]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2 

**Bug 描述**
简要描述您碰到的问题
性能测试运行12或24小时后，X轴时间显示不准确，缺少部分数据

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

![图片](https://user-images.githubusercontent.com/24548477/106464263-6298f300-64d3-11eb-99e9-433f4772512d.png)

![图片](https://user-images.githubusercontent.com/24548477/106464195-48f7ab80-64d3-11eb-8cf9-51c8a83de988.png)

**Comment by xulinde** [comment]
感谢反馈，我们会在1.8.0修复该问题。

**Comment by xulinde** [comment]
执行时间经过夜里12点，显示图的时候对时间排序了，导致00:00:00在最前面
