### ISSUE TITLE
[BUG] cookie取了全局变量和局部变量叠加值

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#13385]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

cookie取了全局变量和局部变量叠加值

### 重现步骤

全局有设置cookie
![image](https://user-images.githubusercontent.com/23476281/167289443-0e4c14b8-3439-4afd-a69b-f840929da07e.png)

局部也有设置cookie
![image](https://user-images.githubusercontent.com/23476281/167289472-c6ff16a1-a6de-4e22-8395-e5ea776d022b.png)

请教的cookie取了全局和局部的叠加
![image](https://user-images.githubusercontent.com/23476281/167289494-1956d3b7-2532-41c7-ab36-d77477b53eb9.png)

### 期待的正确结果

局部也设置了cookie,请求只取局部的cookie的值

**Comment by zrfit** [comment]
你好，经沟通，设计如此，postman有限制请求头的参数只能唯一 只有cookie可以录多条，所以我们也只处理cookie合并。
