### ISSUE TITLE
[BUG]报告分享链接配置没有生效

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13387]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

项目设置-应用管理-测试跟踪/接口测试/性能测试-报告分享链接配置开关变更后，虽然页面提示“保存成功”，但实际未生效，没有修改成功。

### 重现步骤

1、修改配置开关，从开启到关闭
![image](https://user-images.githubusercontent.com/18514555/167291555-36df7a76-7d81-4ee4-9144-fea83a4438a0.png)

2、切换到其他页面
![image](https://user-images.githubusercontent.com/18514555/167291338-ae8c46e2-03b8-4f24-b3c0-408b0876efbd.png)

3、再切换回应用管理，发现开关还是启动的
![image](https://user-images.githubusercontent.com/18514555/167291596-610c7668-d574-4dd3-9e42-58c41c84440f.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，点击关闭是进入编辑模式，点击开启是保存配置-不可编辑。
后续版本对点击关闭是进入编辑模式的提示信息进行优化，不再提示保存成功，避免造成歧义。
点击关闭-提示进入编辑模式，如果没有点击开启，进行页面切换，则编辑信息不保存，仍显示之前的配置信息，页面切换回来后开关默认是开启。
点击开启-退出编辑模式，配置信息保存成功。

**Comment by zrfit** [comment]
您好，感谢您的反馈，点击关闭是进入编辑模式，点击开启是保存配置-不可编辑。
后续版本对点击关闭是进入编辑模式的提示信息进行优化，不再提示保存成功，避免造成歧义。
点击关闭-提示进入编辑模式，如果没有点击开启，进行页面切换，则编辑信息不保存，仍显示之前的配置信息，页面切换回来后开关默认是开启。
点击开启-退出编辑模式，配置信息保存成功。

**Comment by xkmyf** [comment]
> 

嗯嗯，了解。现在主要的问题就是想关闭分享链接功能的话，是关不掉的。 @zrfit

**Comment by zrfit** [comment]
分享链接目前不能关闭的，默认开启24小时有效，分享链接的关闭按钮就是进入编辑链接有效期配置，开启就是保存配置生效。
