### ISSUE TITLE
[FEATURE]  query请求个rest请求将描述隐藏了起来，但是实际用的过程中，比较关注参数对应的含义，现在隐藏起来每次都需要点设置打开查看

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#13391]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

query及rest请求  目前需要点击设置弹出页面才能看到参数的含义描述，测试时都要打开看 不是很方便
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/13564069/167332931-23eca9d8-9073-4b6b-9afb-2282771b29c6.png">

类似于json请求这种都放在前面会感觉比较好
<img width="984" alt="image" src="https://user-images.githubusercontent.com/13564069/167332975-bc676421-d05b-43ab-8840-665b5cf586ee.png">

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
