### ISSUE TITLE
[BUG] 从swagger导入接口定义时所指定的“导入模块”不生效

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#13390]
### MeterSphere 版本

 cloud.metersphere.com/v1.20.1-lts-64d951ea

### 使用外置数据库

是

### 问题描述

在导入接口定义时，选择swagger格式，指定“导入模块”，并提供swagger URL。
所导入的接口定义仍然在“未规划接口” 模块下。

### 重现步骤

1. 接口定义下创建新的模块
2. 导入接口定义，选择swagger---> 指定步骤#1中创建的模块r--->使用URL导入
3. 填入swagger URL 
4. 保存

### 期待的正确结果

所导入的接口定义应该在步骤#2中指定的模块下。

### 附加信息
导入设置：
![image](https://user-images.githubusercontent.com/24548477/167324996-c16830a0-e884-4b22-ac26-7976c69e82ca.png)

实际都放到了“未规划接口”下
![image](https://user-images.githubusercontent.com/24548477/167325451-6c91b6b2-9a7f-45b8-86b6-d4a77f6b9520.png)

**Comment by zrfit** [comment]
您好，未复现该问题，新建模块-swagger导入后导入到了对应模块下，是否操作顺序上有不同？
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/167339002-ab0a2e6f-1ecb-4fad-ac17-f720e27513ce.png">

**Comment by xyziven** [comment]
有可能，当时有可能先不小心导入到了“未规划模块”下，然后又批量删除。
再次重新导入到指定模块，还是会导入到“未规划”下。

**Comment by zrfit** [comment]
已排期，v2.0.0接口导入逻辑统一优化。

**Comment by zrfit** [comment]
v1.20.10-lts版本已优化，接口导入-增加了同步覆盖API模块相关逻辑。
<img width="747" alt="image" src="https://user-images.githubusercontent.com/99731894/179195572-74686ca2-c9b5-4dd2-abbf-7d5f15c7bc1e.png">
