### ISSUE TITLE
[BUG] 急急急，求修复！接口测试用例，Python写断言脚本，运行的时候，是按照Beanshell运行的，会报错

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#1339]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？v1.7.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口测试用例，Python写断言脚本，运行

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
@AgAngle  建星改下这个吧

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
