### ISSUE TITLE
[BUG]创建用户时，手机号不支持电信153号段

### ISSUE THREAD

**Issue by weizhengxia** [metersphere/metersphere#1340]
**MeterSphere 版本**
v1.7.0-b4

**Bug 描述**
创建用户时，手机号不支持电信153号段

**Bug 重现步骤**
1.  在创建用户页面，电话号码输入153号段的电信手机号
2. 
3. 
4. 

**期待的正确结果**
手机号格式校验成功

**截图**
![image](https://user-images.githubusercontent.com/41425792/106540587-28633c00-653b-11eb-92a7-284906003f2b.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.1 版本已修复。
