### ISSUE TITLE
[BUG]UI自动化中，通过元素对象进行业务编排，并保存成功后，再次编辑时，各步骤的元素对象所选择元素显示为空，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13400]
### MeterSphere 版本

1.20lts

### 使用外置数据库

否

### 问题描述

UI自动化中，通过元素对象进行业务编排，并保存成功后，再次编辑时，各步骤的元素对象所选择元素显示为空，请修改

### 重现步骤

1.创建UI场景用例，在业务编排时，各步骤通过元素对象，引用已封装好的元素库，并保存；
2.再次编辑该场景用例，查看各步骤显示情况；

### 期待的正确结果

2.各步骤下操作对象内容显示正确；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/167347424-1a30c8a3-7f56-43ae-b9c4-78a611cb5615.png)

**Comment by zrfit** [comment]
您好，最新版本未复现该问题，是否有其它操作？
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/99731894/167355090-45946c6c-738f-45ae-8523-05e426976ee6.png">

**Comment by sageonedream** [comment]
已与大海老师反馈确认，当元素库目录存在多层级时，此问题必现
