### ISSUE TITLE
[BUG]下拉框元素操作无法定位到元素，选定需要的选项值，请确认并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13409]
### MeterSphere 版本

1.20lts

### 使用外置数据库

否

### 问题描述

下拉框元素操作无法定位到元素，选定需要的选项值，请确认并修改

### 重现步骤

1.在定位下拉框选项的元素时，选择下拉框操作，设置好xpath定位后，填写正确的子选项，查看操作情况；

### 期待的正确结果

1.未能选定下拉框的子选项值。

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/167383677-9c4aa9c1-aad0-441d-a12d-8ed39c5ee6e9.png)
（已与大海老师沟通确认，已知问题，issue跟踪记录，非原生html不支持）

**Comment by ltfit** [comment]
非原生下拉框目前不支持
