### ISSUE TITLE
[BUG]系统设置-工作空间-项目管理，添加项目成员时，已添加到项目的成员没有标识区分

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13415]
### 联系方式

张树彬

### MeterSphere 版本

1.19.

### 使用外置数据库

否

### 问题描述

系统设置-工作空间-项目管理，添加项目成员时，已添加到项目的成员没有标识区分，导致不知道当前项目成员是谁；另外在同时添加多个成员时，如果添加的成员已是该项目成员，则提示“该用户已存在于当前成员列表中”，但又无法很直观看到该用户是谁，导致批量添加成员时很不方便。

### 重现步骤

1. 进入系统设置-工作空间-项目管理，项目已添加了成员
2. 给项目增加成员，点击成员下拉框，无法识别哪些成员已被添加到项目中
3. 批量选择要添加到项目的成员，提示“该用户已存在于当前成员列表中”
4. 在当前添加成员下拉框中无法看出已添加为项目成员的名单

### 期待的正确结果

在添加成员下拉框中，对于已添加到项目中的成员显示对勾的标签

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/167411427-8c55ca73-5f0d-42f2-b150-1c7630fc5980.png)
![image](https://user-images.githubusercontent.com/77324661/167412572-3c98f55c-263e-4e9b-b590-75a6a22b93b3.png)
![image](https://user-images.githubusercontent.com/77324661/167413324-4f5c89c4-65b4-4def-8b64-ee47a1fda499.png)
![image](https://user-images.githubusercontent.com/77324661/167413600-b4f8a6f4-3d9d-47e4-a2e3-eb363c72173a.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
