### ISSUE TITLE
[BUG]接口自动化结果报告控制台日志错误

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#13421]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

多个不同项目，每个项目有自己的测试计划，定时同一时间跑所有计划下的接口自动化，打开其中一个结果报告，进入控制台，显示了其它项目中的控制台日志

### 重现步骤

多个不同项目，每个项目有自己的测试计划，定时同一时间跑所有计划下的接口自动化，打开其中一个结果报告，进入控制台，显示了其它项目中的控制台日志

### 期待的正确结果

各个项目中的自动化控制台日志，各自显示各自的做到分离

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/167537359-8234cbf6-7aae-435d-9443-b56488ed50b7.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，与研发沟通日志信息无法做到隔离。
