### ISSUE TITLE
[FEATURE]自定义代码片段实现跨项目使用

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13425]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

目前项目设置中自定义代码片段只能在本项目下使用，不能跨项目使用，这样一些通用的代码片段就无法跨项目或跨工作空间复用。
希望能增加全局的自定义代码片段，或添加自定义代码片段的时候能够选择是否作为通用配置。

另外：例如项目设置-文件管理中上传jar包就是跨项目且跨工作空间的。感觉这些配置的东西作用范围（或者说项目之间的隔离）不太规范和明确。

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
