### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#13423]
### MeterSphere 版本

版本迭代过程中，1.13版本导出的文件导入到1.19版本，操作步骤的样式都变了

### 请描述您的需求或者改进建议

测试跟踪-功能用例，由原来的1.13版本导出的文件导入到1.19版本，操作步骤的样式都变了，与1.13版本展示的不相符。

![image](https://user-images.githubusercontent.com/104960608/167541665-cca69a4a-40d0-4ab6-b8f2-553064a0cf22.png)

### 请描述你建议的实现方案

希望让导进去的内容，一个框内的1、2、3、4按编号换行。

### 附加信息

<img width="127" alt="1652156040" src="https://user-images.githubusercontent.com/104960608/167541352-d2f3e9c8-ba8a-4cb2-9047-8689f0d9dde8.png">

**Comment by Hyyfit** [comment]
您好，我们正在规划excel表导入功能用例的优化，您加一下我的企业微信，具体提一下您的需求。
<img width="321" alt="image" src="https://user-images.githubusercontent.com/95834771/167765377-57f49e80-4bb4-4618-9d7e-7f2294a0df16.png">
