### ISSUE TITLE
[BUG]接口定义模块，在case编写的前后置脚本，切换到API后， 再切换回来，脚本被清零

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [metersphere/metersphere#13427]
### 联系方式

内部郭灶鹏

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

1、接口测试-接口定义，编辑任意一个接口
2、在TEST 这里， 编写前后置脚本
3、切换到API这里， 再切换回TEST , 发现之前编辑的前后置脚本被清零了。
<img width="427" alt="企业微信截图_16521712007337" src="https://user-images.githubusercontent.com/30264974/167585980-ba5c92d7-6d2a-4b42-b872-fce9d92ce18a.png">

### 重现步骤

如问题描述

### 期待的正确结果

在接口编辑的页面， 从TEST 切换到API , TEST这里填写的表单 前端进行缓存。

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
