### ISSUE TITLE
[BUG]脑图数据丢失(必现),V1.20

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#13428]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

编写脑图用例时，新增了模块后，后续数据没有机上用例标签，再切换到新增加的模块下，数据丢失

### 重现步骤

1，新增加一个test-libb模块,并打上模块标签
2，新增二级和三级数据,点击保存
3，点击左侧列表，切换到test-libb模块，二级和三级数据丢失

![image](https://user-images.githubusercontent.com/67257251/167599064-9b58a409-5f31-4a4e-beed-edf67b33b8dc.png)
![image](https://user-images.githubusercontent.com/67257251/167599157-5ba8dd83-1f04-472f-b57c-989b138cd7ad.png)

### 期待的正确结果

切换也不会出现数据丢失

**Comment by ltfit** [comment]
你好 二三 级数据  需要添加标签  ，不然没有意义；你点击模块 可以显示出来二三级数据，这个后续优化下
