### ISSUE TITLE
[BUG]参数化文件应用 baolu-csv-data-file-config插件 本地调试OK，MS运行启动时下载工程文件错误

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#13422]
### 联系方式

zhangzhaox@szlanyou.com

### MeterSphere 版本

V.1.17.3

### 使用外置数据库

是

### 问题描述

https://github.com/LeeBaul/baolu-csv-data-file-config
JMX工程文件中应用了baolu-csv-data-file-config组件，本地调试OK，三方组件jar也上传了，性能测试执行时，查看ms-jmeter的运行日志，node节点下载工程文件失败，导致不能正常运行

![image](https://user-images.githubusercontent.com/82088551/167539794-115365f1-b1b0-4a08-babe-57f4bd05bb09.png)

![image](https://user-images.githubusercontent.com/82088551/167539617-ba826095-efb9-40eb-902f-5b8f7d31db69.png)

### 重现步骤

1、调试好本地jmx脚本 应用https://github.com/LeeBaul/baolu-csv-data-file-config

2、MS上传运行错误

**Comment by zrfit** [comment]
您好，感谢您的反馈，请上传下jmx文件。

**Comment by zhangzhaox** [comment]
@zrfit JMX文件已提供给刘瑞斌了，感谢！

**Comment by zrfit** [comment]
您好，用您的jmx导入到我本地的jmeter报错
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/99731894/167785288-b9ecaa98-f447-477c-8e97-53d0abf1bd84.png">
导入到ms执行也报错
是否有其它配置文件需要添加或者其它操作步骤请详细说明。
![Uploading image.png…]()

**Comment by zhangzhaox** [comment]
bzm - Random CSV Data Set Config  脚本中的这个 删除  或者补充下载对应的jar

**Comment by zrfit** [comment]
您好，导入到jmeter后运行仍失败 这里的key.txt文件是否也需要上传 ？还有自定义变量中的value值为空 我看下面的接口中有一个地方有用到？
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/168229315-c666ff4f-c621-4141-a5df-ebe117ab4037.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/168229972-774b6f9e-ec08-4e07-b036-3d3985c70587.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/168230157-7a04922f-9d6e-4bca-8fe6-dab196d5be9e.png">

**Comment by zhangzhaox** [comment]
[key.txt](https://github.com/metersphere/metersphere/files/8712389/key.txt)
