### ISSUE TITLE
[BUG]只读用户也能编辑修改API/CASE/接口自动化场景

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13424]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

没有编辑权限的只读用户也能编辑修改API/CASE/接口自动化场景，通过ctrl+s快捷键能保存成功。

### 重现步骤

1、创建一个新用户，添加到系统预置的“只读用户(系统)”用户组中；
![image](https://user-images.githubusercontent.com/18514555/167559628-92fc3e79-8864-4c1c-89b7-c64803a37a0f.png)
只读用户组并没有编辑权限：
![image](https://user-images.githubusercontent.com/18514555/167559813-fffbef89-f5f5-4722-9bc6-0b92962ae2d3.png)

2、点击ID，进入CASE详情页面
![image](https://user-images.githubusercontent.com/18514555/167560052-01b1f671-bc65-4731-8718-a1e74ef3cde2.png)

3、修改body内容，并按快捷键 ctrl+s，页面提示”保存成功“
![image](https://user-images.githubusercontent.com/18514555/167560381-43699d9d-5009-4345-97f0-88ec6640464f.png)

4、重新进入上述的CASE中，或通过其他用户查看上述CASE，发现内容已被修改，操作日志也有体现
![image](https://user-images.githubusercontent.com/18514555/167560886-9c26095f-f605-467d-93a1-3da9b2a5548d.png)

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
此问题 在1.20.2-lts 修复
