### ISSUE TITLE
[BUG]运行环境中一个环境列表中配置多个数据源，在步骤中选择第二个保存后还是第一个

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#13437]
### 联系方式

410782876@qq.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

运行环境中一个环境列表中配置多个数据源，在步骤中选择第二个保存后还是第一个

### 重现步骤

运行环境中一个环境列表中配置多个数据源，在步骤中选择第二个保存后还是第一个

### 期待的正确结果

选择哪个一个数据源正常保存运行

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://user-images.githubusercontent.com/25195509/167753870-cd47d180-8fe9-4f2b-82ca-3f5e8d3e51b5.png)

**Comment by zrfit** [comment]
您好，如果只修改步骤的数据源后保存，是可以保存成功的，显示的数据源就是保存的数据源，如果是切换了运行环境，会默认显示这个环境下的第一个数据源，您的具体复现步骤请描述下，多谢！
