### ISSUE TITLE
接口自动化测试中引入套件的概念

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1344]
**请描述您的需求或者改进建议.**
目前接口自动化测试中，只支持到单个场景的自动化，相当于每个场景是一个用例，如果要设置定时任务，需要给每个场景（用例）去设置。希望可以引入套件的概念。

**请描述你建议的实现方案**
在接口自动化中，现有的有 单个接口、场景的概念，希望引入套件概念，即多个场景组成1个套件，可以一键运行，设置定时任务后，可以自动执行套件内的所有场景。
目前是不是通过子场景可以实现此功能？

**Comment by wangzhen-fit2cloud** [comment]
你好，目前可以通过场景中引用多个其他场景，或者将需要执行的场景添加到一个测试计划中的方式来实现。
