### ISSUE TITLE
P0：接口定义里面的单个接口测试无法进行接口依赖

### ISSUE THREAD

**Issue by HEhunter** [metersphere/metersphere#13440]
### 联系方式

1505831195@qq.com

### MeterSphere 版本

最新版本

### 使用外置数据库

是

### 问题描述

1、A接口进行提取参数
2、B接口拿A接口提取的参数进行传参
3、B接口无法拿到A接口提取的参数
不能进行上下接口依赖

### 重现步骤

1、A接口进行提取参数
2、B接口拿A接口提取的参数进行传参
3、B接口无法拿到A接口提取的参数
不能进行上下接口依赖

### 期待的正确结果

上下接口可以正常依赖

### 相关日志输出

```shell
1、A接口进行提取参数
2、B接口拿A接口提取的参数进行传参
3、B接口无法拿到A接口提取的参数
不能进行上下接口依赖
```

### 附加信息

1、A接口进行提取参数
2、B接口拿A接口提取的参数进行传参
3、B接口无法拿到A接口提取的参数
不能进行上下接口依赖

**Comment by zrfit** [comment]
您好，如果A接口只提取了参数没将参数设置为环境变量，B接口是无法直接引用A接口提取的参数的，需要将A接口提取的参数通过后置脚本设置为环境变量，然后B接口执行引用环境变量，就可以了。
