### ISSUE TITLE
[BUG]接口自动化测试报告邮件中的查看报告链接，点击进入平台后，提示“测试报告不存在”

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1346]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6.2
**Bug 描述**
简要描述您碰到的问题
接口自动化测试报告邮件中的查看报告链接，点击进入平台后，提示“测试报告不存在”
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
目前的组织、工作空间、项目切换机制存在缺陷，需要通过 URL 直接进入正确的项目中
@AgAngle @liuruibin

**Comment by xulinde** [comment]
感谢反馈，我们会在1.8.0修复该问题

**Comment by zh417233956** [comment]
#1465
