### ISSUE TITLE
接口自动化场景变量添加5种不同的类型变量保存后，查看场景变量会多出一个常量类型且删除后再打开也如此，且“”场景变量“”行没有对齐

### ISSUE THREAD

**Issue by liangch888** [metersphere/metersphere#1347]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.1版本
**Bug 描述**
简要描述您碰到的问题
接口自动化场景变量添加5种不同的类型变量保存后，查看场景变量会多出一个常量类型且删除后再打开也如此，且“”场景变量“”行没有对齐
**Bug 重现步骤**
1.  进去接口自动化模块
2. 点击场景编辑一场景变量
3. 添加5种不同的类型变量关闭此时页面
4. 查看场景变量会多出一个常量类型且删除后再打开也如此
5. “”场景变量“”行没有对齐

**期待的正确结果**
1、添加5种不同的类型变量保存不会添加多余的变量类型
2、“”场景变量“”行要对齐

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/57386396/106571825-9aa34300-6572-11eb-973c-9330256e9372.png)

![image](https://user-images.githubusercontent.com/57386396/106571803-92e39e80-6572-11eb-94d7-bd47b756754b.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，打开改列表是自动添加一个新条目便于增加新变量，如果不填写变量名和值的话并不会进行保存。
