### ISSUE TITLE
[BUG]UI测试涉及到光标移动操作时，无法直接通过定位光标元素，坐标移动的方式实现拖移，需要配合鼠标长按+鼠标移动才可实现，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13476]
### MeterSphere 版本

1.20lts

### 使用外置数据库

否

### 问题描述

涉及到光标移动操作时，无法直接通过定位光标元素，坐标移动的方式实现拖移，需要配合鼠标长按+鼠标移动才可实现，建议优化

### 重现步骤

1.MS-Cloud环境注册页面，进行光标移动，在UI中需通过两步操作来实现，希望能通过鼠标拖拽或者光标拖拽的封装关键字，进行一步实现

### 附加信息

![7c77ed1a073897a68a73ea429aaf326](https://user-images.githubusercontent.com/92150453/167825816-2ef17c22-a83b-49b8-8543-8ab997d43e8e.png)

**Comment by sageonedream** [comment]
[光标移动测试.txt](https://github.com/metersphere/metersphere/files/8668984/default.txt)
备注：重命名为.side格式即可

**Comment by Hyyfit** [comment]
感谢反馈，我们后面会开放自定义指令，用户可以自行封装这样的组合指令。
