### ISSUE TITLE
[BUG]接口定时同步时，将已存在接口中的描述信息给覆盖了，且看不到操作日志

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#13498]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

接口定时同步时，将已存在接口中的描述信息给覆盖了，且看不到操作日志。导致测试过程中记录的描述信息都找不到了。

### 重现步骤

1.对平台上已有接口A添加 描述信息，并保存。
2.新增定时同步任务，且其中对应的接口A没有变化。
3.定时同步完成后，查看接口A，发现其描述信息给覆盖了，且看不到操作日志。

### 期待的正确结果

除非同步的接口中存在非空的描述信息，否则原描述信息不能被覆盖清空。同时历史记录中应该保留记录。

**Comment by youliyuan-fit2cloud** [comment]
1.20版本修复这个问题，升级一下吧
