### ISSUE TITLE
[BUG]将场景导出后，导入到另一个项目的场景列表中，将引用的场景修改并保存后，再次点入，发现修改失败

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#13497]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.2

### 使用外置数据库

是

### 问题描述

将所有场景列表从项目A 导出，导入到项目B 中；

此时，项目B中的场景里面显示的引用的场景，都是引用的项目A的场景。
将项目B中的场景中的引用场景改为引用项目B的场景后，提示“保存成功”，但是再次点进去之后发现还是引用的项目A的场景。

### 重现步骤

- 项目A： 场景get_information，引用了场景login，这两个场景都是项目A 里面的。
- 将项目A中场景列表导出 文件名Metersphere_Scenario_A.json
- 切换到项目B
- 在项目B中导入Metersphere_Scenario_A.json到场景列表中
- 发现场景get_information中，引用场景login的步骤旁边写着一个项目A，说明是引用的项目A的场景
- 将引用的场景login删除，改为引用项目B的场景login，保存成功，调试也成功
- 保存后，从场景列表点击进入场景get_information，发现还是引用的是项目A的场景login，而不是项目B 的。

### 期待的正确结果

能够修改通过文件导入进来的场景的引用。

**Comment by youliyuan-fit2cloud** [comment]
最新版本没有复现该问题，建议升级一下

**Comment by Faerie1999** [comment]
> 最新版本没有复现该问题，建议升级一下

你们提供的在线demo应该是最新版本： v1.20.1-lts-64d951ea
但是我试了，仍然存在这个问题。

![WeChatfb369bea3ab1461e2d5dd6a0ff61b7ef](https://user-images.githubusercontent.com/31870788/168199838-bd831329-a38f-40c4-985c-81c1e5906e02.png)

![WeChat4656977e5396491de255b1b637e8e0d9](https://user-images.githubusercontent.com/31870788/168200555-ab1a06e0-01f7-431d-ad38-a6676f6e7540.png)


![WeChatafcf6fdff3ff1b0c5d1490e0870b5d48](https://user-images.githubusercontent.com/31870788/168200344-e7066d64-d2fd-4af2-8cfc-e2bf928d5c3a.png)

**Comment by Faerie1999** [comment]
> 最新版本没有复现该问题，建议升级一下

经升级为v1.20.2，仍可以复现这个问题，请问是否步骤与上述不一致？确实可以保存成功（出现toast），但是重新进入该场景后，仍然是引用之前项目的场景。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts版本中已修复
