### ISSUE TITLE
[BUG]接口的返回报文设置了提取某个字段，报文发送成功了，没有提取到要保存的值。

### ISSUE THREAD

**Issue by Richard-chenbin** [metersphere/metersphere#135]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/68156947/87636951-1aeb8d80-c774-11ea-8af6-babba1b03ef6.png)

**Comment by wangzhen-fit2cloud** [comment]
你的意思是没有成功提取到变量呢，还是保存这个接口测试的时候添加的变量提取的配置内容没有保存下来？
@Richard-chenbin
