### ISSUE TITLE
[BUG]接口测试的query参数会一直重复填写

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13519]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.1-lts

### 使用外置数据库

否

### 问题描述

用鼠标重复点击url输入框和query参数标签，接口测试的query参数会一直重复填写
![image](https://user-images.githubusercontent.com/88763608/168003526-715b5525-4094-4f7d-89f8-882b5a7aed55.png)

### 重现步骤

可以看下附件视频，比较简单

### 附加信息

[重复参数.zip](https://github.com/metersphere/metersphere/files/8675390/default.zip)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本已修复，请升级一下吧
