### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lixiup** [metersphere/metersphere#13511]
### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 请描述您的需求或者改进建议

接口文档的分享只支持单接口分享，建议可以支持所有接口/选择部分接口进行接口文档导出

### 附加信息

![image](https://user-images.githubusercontent.com/50001937/167991829-b29cf421-99e7-4f16-93d5-e3ffa1e0c0e3.png)

**Comment by YellCatt** [comment]
我也需要，特别是单个接口页面，也需要文档按钮

**Comment by Hyyfit** [comment]
您好，多个接口的文档的分享是企业版的功能，具体您可在我们微信交流群里联系我们的商务
