### ISSUE TITLE
[BUG]接口自动化-场景步骤-请求参数中的参数值为空时会提示空指针，建议按空字符串处理(参考jmeter)

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1351]
**MeterSphere 版本**
v1.7.1

**Bug 描述**
1、请求参数中的参数值为空时会抛出空指针

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
<img width="1220" alt="111111111111" src="https://user-images.githubusercontent.com/21210217/106596986-ba496400-6590-11eb-8407-7f662d39bcd6.png">

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
