### ISSUE TITLE
[BUG]接口模块-删除的项目下的计划仍会显示在首页看版中

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1354]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
<img width="716" alt="22222222" src="https://user-images.githubusercontent.com/21210217/106611577-19b06f80-65a3-11eb-93f9-93365797e1cf.png">

**Comment by xulinde** [comment]
感谢您的反馈，该问题已修复。1.8.0发布后您直接升级下就可以了
