### ISSUE TITLE
[BUG]接口测试，请求体在json-schema中选择整型，参数值以获取变量的方式定义时，查看实际请求的参数字符类型仍为字符串类型，需修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13547]
### MeterSphere 版本

1.20.1lts

### 使用外置数据库

否

### 问题描述

接口测试，请求体在json-schema中选择整型，参数值以获取变量的方式定义时，查看实际请求的参数字符类型仍为字符串类型，需修改

### 重现步骤

1.接口测试，请求体选择json-schema，请求参数定义为interger类型，参数值以获取变量的方式定义，查看参数的请求类型；

### 期待的正确结果

1.参数请求类型为整型；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/168049910-56acf5ca-7e82-423d-8030-7554979091cc.png)
![image](https://user-images.githubusercontent.com/92150453/168050100-1925f46d-6cfe-4478-8ad7-c755a81838e2.png)

**Comment by zrfit** [comment]
您好，v1.20.3-lts版本已修复。
