### ISSUE TITLE
[BUG]编写接口case，请求体中的值，无法从参数设置中保存带过来

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#13540]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

编写接口case，请求体中的 值，无法从 参数设置 中保存带过来。
![image](https://user-images.githubusercontent.com/100331967/168043726-4089aa2d-7d39-4102-ba9d-7a34dcd1713e.png)
![image](https://user-images.githubusercontent.com/100331967/168043749-06f47cb1-faec-4e80-86b6-3e49082e9182.png)

### 重现步骤

1.编写接口case，请求体中的 值，采用 参数设置 方式；
2.在参数设置页面预览后，点击保存；
3.在case编写页面，请求体中的 值，仍然是空的。

### 期待的正确结果

可以从参数设置中保存带过来

**Comment by youliyuan-fit2cloud** [comment]
你这个参数设置不对，前面必须有“@”

**Comment by youliyuan-fit2cloud** [comment]
#13537已经提过相同的问题
关闭该问题
