### ISSUE TITLE
[QUESTION]请问为啥引用了某些场景之后，使用循环控制器+计数器时，计数器会失效？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#13557]
### 请描述您的问题

使用foreach 循环控制器，计数器的信息如下：
![image](https://user-images.githubusercontent.com/31870788/168193295-5e6a442f-0a8b-4b1a-868c-e7611b1b4030.png)

场景大概如下：
步骤一：引用了某个场景
步骤二：循环控制器，循环上面的sceneList列表，请求的是www.baidu.com。其请求参数为wd=${page}

当禁用掉前面的场景，调试该循环控制时，会发现三次循环中，wd依次为1,2,3
![image](https://user-images.githubusercontent.com/31870788/168195655-29a83e60-b272-45de-8420-d9317c3eb9a9.png)

当启用前面的场景，调试该场景时，会发现三次循环wd都为0：
![1652406865535](https://user-images.githubusercontent.com/31870788/168195995-31c74f0d-9f80-4048-9b6f-bd28c88eb867.jpg)

但是有的场景下，循环控制器无论启用前面的场景还是禁用，都是正常的1,2,3（暂时不知道这些场景有什么区别，可能需要去看源代码，是否存在特殊条件判断）

**Comment by Hyyfit** [comment]
有可能是前面的场景中对变量重新定义了。
从描述的情况来看，很难排查问题。你可以加一下我的企业微信，把脚本发我，这样比较好排查问题。
<img width="325" alt="image" src="https://user-images.githubusercontent.com/95834771/168244159-c1e6afdc-4bc7-4697-89ec-14dbfc1b87bc.png">
