### ISSUE TITLE
[BUG]定时任务，有多个定时任务时，通知人会互相影响，设置一个定时任务的通知人会更改到其他的定时任务，最后所有的定时任务都是发送一样的人

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#1355]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？ --------1.7.0

**Bug 描述**
定时任务中的任务通知
**Bug 重现步骤**
1.  新建多个测试场景
2. 点击定时任务
3. 选择任务通知，设置成员
4. 多个定时任务中重复1-3，但是选择不同成员
5. 最后查看每个定时任务的成员

**期待的正确结果**
每个定时任务通知成员不同，为设置的成员

**Comment by Anduin-Zhu** [comment]
我的问题应该跟你的类似

[步骤]
1.计划A添加任务通知（通知1）并保存
2.F5刷新页面
3.查看计划A
4.查看计划B（计划B未创建通知）

[结果]
计划A为通知1，计划B也是通知1

[期望]
计划A为通知1，计划B为空

**Comment by zyyfit** [comment]
已在1.7.2版本验证通过
