### ISSUE TITLE
[BUG]测试计划中的场景只执行了部分，部分未执行

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#13558]
### 联系方式

410782876@qq.com

### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

测试计划中的场景只执行了部分，部分未执行

### 重现步骤

测试计划中的场景只执行了部分，部分未执行

### 期待的正确结果

正常全部执行

### 相关日志输出

```shell
如图
```

### 附加信息

![image](https://user-images.githubusercontent.com/25195509/168198083-64fcd6eb-c037-44eb-9fc3-93cd7d8d19cc.png)

**Comment by xulinde** [comment]
您好，我使用1.19.3版本没复现。您的场景有设置条件控制器吗？是不是没触发条件所以没执行，排查下
