### ISSUE TITLE
[FEATURE] 一些使用后的需求建议

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13554]
### MeterSphere 版本

v1.20.2-lts

### 请描述您的需求或者改进建议
1. 项目组内没有权限管理，在企业内无法使测试和开发同时使用ms平台，测试维护测试用例，开发维护api接口和文档的编写
2. 无法通过访问接口，快速生成测试用例，比如我访问search接口，返回给我用户的信息，我看了一遍了，是否自动帮我生成一个全部断言的测试用例
3. 添加接口也同上，通过访问接口，一键自动生成接口信息
4. 接口case和api添加，没有审核机制
5. 没有类似gitlab一样的私有库和公有库的机制，多人编写的测试用例都混在一起，无法较好的维护

**Comment by Hyyfit** [comment]
感谢反馈
