### ISSUE TITLE
[QUESTION]电脑配置运行ms的问题

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13555]
### 请描述您的问题

我想用酷睿四代i5双核低压处理器和8G内存，320G的硬盘，是否可以运行ms平台？

**Comment by zhangdahai112** [comment]
当然没有问题，但是我还是列出我自己的配置你看下，平时开发刚好够用
![image](https://user-images.githubusercontent.com/46101698/168242535-6607492e-a27e-4c4b-bd1b-4552cc69ed00.png)

**Comment by YellCatt** [comment]
> 没有自己的问题，但我还是用我的系列配置你看下，平时当然刚好够用 ![图片](https://user-images.githubusercontent.com/46101698/168242535-6607492e-a27e-4c4b-bd1b-4552cc69ed00.png)

你的CPU配置只是刚好够用吗？我是测试，我就是想每天定期跑测试用例就行，因为我看到你用了11代的处理器，说的好像只是刚刚好满足你的要求而已，你做压力测试吗？
