### ISSUE TITLE
[BUG]导出的自动化测试报告中请求、响应大小都为0，断言也没有显示

### ISSUE THREAD

**Issue by lixiup** [metersphere/metersphere#13566]
### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

导出的自动化测试报告中请求、响应大小都为0，断言也没有显示

### 重现步骤

导出自动化测试报告为pdf格式

![image](https://user-images.githubusercontent.com/50001937/168220230-ee2653a7-ec52-4c9e-98a4-5ec8f8fc67df.png)

**Comment by zyyfit** [comment]
1.20.3已修复，请等待发布后验收

**Comment by JohnNiang** [comment]
> 1.20.3已修复，请等待发布后验收

具体是在哪个 PR 修复的呢？
