### ISSUE TITLE
[BUG] 新建测试用例，建议增加基础信息宽度，减少步骤信息宽度

### ISSUE THREAD

**Issue by zuozuo0320** [metersphere/metersphere#13572]
### 联系方式

北方区交流群

### MeterSphere 版本

 v1.20.2-lts-b9564d5c

### 使用外置数据库

否

### 问题描述

觉得当前宽度太小，影响使用
style="width: 300px; margin-left: 0px; height: 787px;"
![image](https://user-images.githubusercontent.com/55780527/168243969-8eee7e70-f2b4-4965-84f8-25a0e51e85a8.png)

### 重现步骤

跳转到新建用例页面即可，我觉得当前宽度太小，影响使用

### 期待的正确结果

推荐固定宽度：width: 555px; margin-left: 0px; height: 787px;
![image](https://user-images.githubusercontent.com/55780527/168243466-e3fae1a7-5f76-4473-a56b-bb93007db2d6.png)

### 附加信息

期望下个版本能够得到解决，感谢

**Comment by zrfit** [comment]
您好，感谢您的反馈，目前我们产品设计如此，基础信息只展示一些主要的基础字段，下拉选择后者字段内容比较简洁，如果要想扩大基础信息的宽度，可手动拖动右移增加基础信息的宽度。
