### ISSUE TITLE
[BUG]更新至1.20.2版本后内置函数不支持历史数据（应强制更新处理）

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#13571]
### MeterSphere 版本

v1.20.2-lts

### 使用外置数据库

否

### 问题描述

1.20.2版本内置函数不支持历史数据，如历史数据传参中含有内置函数，如${__time(yyyyMMdd,)}；则在请求时不生效；
需要手动重新输入方可生效。

### 重现步骤

1.20.2版本内置函数不支持历史数据，如历史数据传参中含有内置函数，如${__time(yyyyMMdd,)}；则在请求时不生效；
需要手动重新输入方可生效。

### 期待的正确结果

内置函数支持历史数据传参

**Comment by xulinde** [comment]
您是从哪个版本升级上来的？
