### ISSUE TITLE
CSV设置变量后，在循环迭代里面取值会自动跳过第二行，取第三行数据（尝试一下就会复现）

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1358]
**MeterSphere 版本**
版本: v1.7.1-66e9f091

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
从第二行开始取值

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33744331/106689050-4a77bf80-660a-11eb-97c5-d1fb5407878f.png)

**Comment by guozhiyuanasd** [comment]
![image](https://user-images.githubusercontent.com/6678556/106886973-7c2e7a80-671f-11eb-9359-13dd72791b32.png)
通过设置不同shareModle可以解决

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
