### ISSUE TITLE
[FEATURE]在登录页面提供一个快速测试的功能，类似postman调用一下接口，看看访问值

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13588]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

在登录页面提供一个快速测试的功能，类似postman调用一下接口，看看访问值
不要登录进去了，跳转在接口界面，点击+才能快捷调试，步骤太多了

**Comment by Hyyfit** [comment]
您好，不太明白你的表述。可以在具体一点吗？最好附上截图。
你的操作流程是怎样的？期望是怎样的？

**Comment by YellCatt** [comment]
> 您好，不太明白你的表述。可以在具体一点吗？最好附上截图。 你的操作流程是怎样的？期望是怎样的？

就像微信可以不用登录就传文件一样，快速调试这个功能很常用，能不能把层级提高？现在做的太隐蔽了

**Comment by Hyyfit** [comment]
1.如果退出前是在接口定义的页面，那么下次进入也是会直接进入到接口定义的页面的。

2.在接口定义的页面，我们有快捷调试的入口，可以快速的调试接口
<img width="611" alt="image" src="https://user-images.githubusercontent.com/95834771/168763610-5bc36ddd-b2aa-4435-a4e0-e56da54ab615.png">
