### ISSUE TITLE
[BUG]进行版本升级后，概率性出现以前添加的运行环境在执行接口测试时无法使用的情况，请定位并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13582]
### MeterSphere 版本

1.20.1lts

### 使用外置数据库

否

### 问题描述

进行版本升级后，概率性出现以前添加的运行环境在执行接口测试时无法使用的情况，请定位并修改

### 重现步骤

1.在版本未升级前，新增有运行环境A，在环境域名填写正确，能正常执行接口调测的情况下，升级至1.20.1lts版本后，执行接口调测，调测失败并报错：连接超时；
2.再次新增相同配置的运行环境B，执行接口调测，调试成功。

### 期待的正确结果
1.升级版本后，原运行环境A能正常使用。

_No response_

### 附加信息

![a10b42c5396649bc957603b51bf4cf5](https://user-images.githubusercontent.com/92150453/168267018-db40378d-72ff-43e0-9550-8673a65a3545.png)
![3b31f7cf4c9812c111e1dc42b37ebd7](https://user-images.githubusercontent.com/92150453/168267025-43857f09-b428-4e76-ad1c-a4bb11daf953.png)
![3e16df5e35b1578c5fd5a3479685f1b](https://user-images.githubusercontent.com/92150453/168267030-043e08d3-aa27-46f2-8716-0904ac38caa8.png)
![3a6906d0e06257b3835e4fc139ed580](https://user-images.githubusercontent.com/92150453/168267039-ce1b6af8-d61b-4d1e-8aa5-f79d862297fd.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，是不是网络问题？

PS：建议：“请定位并修复”在标题中 字样去掉 。。。。

**Comment by sageonedream** [comment]
首先这个问题不是必现的，我在标题中有说明，其次这个是以前的已知问题，当时是说修复了，现在又复现了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月15日(周日) 下午2:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]进行版本升级后，概率性出现以前添加的运行环境在执行接口测试时无法使用的情况，请定位并修改 (Issue #13582)




 
你好，没有复现，是不是网络问题？
 
PS：建议：“请定位并修复”在标题中 字样去掉 。。。。

**Comment by youliyuan-fit2cloud** [comment]
> 首先这个问题不是必现的，我在标题中有说明，其次这个是以前的已知问题，当时是说修复了，现在又复现了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月15日(周日) 下午2:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [metersphere/metersphere] [BUG]进行版本升级后，概率性出现以前添加的运行环境在执行接口测试时无法使用的情况，请定位并修改 (Issue #13582) 你好，没有复现，是不是网络问题？ PS：建议：“请定位并修复”在标题中 字样去掉 。。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我这边确实没复现。。。你遇到的时候没有相关log 吗？之前的出现的版本是哪个？
