### ISSUE TITLE
[BUG]kafka容器消耗大量CPU资源

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13589]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.2-lts-b9564d5c

### 使用外置数据库

否

### 问题描述

MeterSphere并没有执行接口自动化或性能任务，但是kafka容器一直在消耗大量CPU资源。初步定位是kafka中kafka.admin.ConsumerGroupCommand进程相关逻辑导致，可能是因为旧版本kafka本身的bug引起的。
目前容器内kafka是2.5.0版本，而kafka在2.5.1版本修复了如下bug
https://issues.apache.org/jira/browse/KAFKA-10134
https://issues.apache.org/jira/browse/KAFKA-10254
建议将kafka升级到最新版本

### 重现步骤

1：通过 docker stats 查看CPU使用量，发现kafka不断的占用大量CPU资源（宿主机2CPU的场景）
![docker-stats](https://user-images.githubusercontent.com/18514555/168321061-63b4912b-c151-4152-b790-c32c7943ef64.gif)

2：通过 docker exec -it kafka /bin/bash 进入kafka容器内用top查看
![image](https://user-images.githubusercontent.com/18514555/168322196-302e07f6-6612-45b0-b659-34f823e18073.png)

3：通过ps- ef | grep java查看具体java进程
![image](https://user-images.githubusercontent.com/18514555/168322826-cd8506ce-7e23-41ca-9196-6a34965d348b.png)

**Comment by liuruibin** [comment]
我们的Kafka 用的是2.8.1版本，Kafka作为优秀的中间件你也可以搭建自己的集群，只需要将配置文件中的地址和端口改成你需要的即可

**Comment by xkmyf** [comment]
> 我们的Kafka 用的是2.8.1版本，Kafka作为优秀的中间件你也可以搭建自己的集群，只需要将配置文件中的地址和端口改成你需要的即可

我看镜像用的是2.5.0版本的
![image](https://user-images.githubusercontent.com/18514555/168406563-6b9b57de-1c87-4fb7-baa3-9bda3cae2f18.png)
进入容器内查看libs中也是2.5.0
![image](https://user-images.githubusercontent.com/18514555/168406677-66a86cae-4545-488a-876c-5d3f59b01731.png)
@liuruibin

**Comment by liuruibin** [comment]
你可以手动改tag，这个2没有指向最新的2.8.1，我们后面会更新tag
registry.cn-qingdao.aliyuncs.com/metersphere/kafka:2.8.1

**Comment by xkmyf** [comment]
> 你可以手动改tag，这个2没有指向最新的2.8.1，我们后面会更新tag registry.cn-qingdao.aliyuncs.com/metersphere/kafka:2.8.1

好的

**Comment by xkmyf** [comment]
目前kafka已使用的是2.8.1版本，且部署在了新的机器上测试了下还是kafka频繁消耗大量CPU，怀疑是其他组件调用kafka逻辑有问题，希望能够排查优化下。

**Comment by xkmyf** [comment]
> 我在测试中并没有出现长期占用cpu的情况，只是在healthcheck的时候cpu会突然升高一下。这是正常现象，你如果很介意这个可以自己部署kafka

好的，感谢，验证了下，确实是healthcheck导致的；
docker-compose-kafka.yml中默认配置的healthcheck节点每6秒启动一次java服务(kafka.admin.ConsumerGroupCommand)做健康检查
![image](https://user-images.githubusercontent.com/18514555/168967542-1557b434-52b9-4603-9fe2-dfe4713016f4.png)

我手动改interval=300s后，对于4CPU的机器，CPU(usage-user)**平均使用**率从12%下降到了2%
![image](https://user-images.githubusercontent.com/18514555/168968678-32ccd2f3-e249-4a4f-906b-a497f833a5d2.png)

建议更换下检查程序（test: ["CMD", "kafka-consumer-groups.sh", "--bootstrap-server", "localhost:9093", "--list"]），作为一个频繁执行的检查任务，太耗资源了。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们需要再研究一下是否采纳您的建议~
