### ISSUE TITLE
[BUG]测试计划中场景报告详情显示成功，只是无结束时间，但是场景状态显示 超时状态

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#13581]
### 联系方式

shenkaibo

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

截图如下：
![image](https://user-images.githubusercontent.com/30038088/168260335-8116bd05-388b-4df3-98ec-dd0f606790d0.png)

### 重现步骤

测试计划配置如下：
1.关联87个场景用例
2.手动触发执行，选择 资源池（有一台执行机），并行执行

**Comment by youliyuan-fit2cloud** [comment]
不是最新版本1.20.2-lts复现的？

**Comment by shenkaibo** [comment]
这个是 没有收到结束标识 导致，1.20.3-lts 优化超时问题之后，这个问题 不存在了

**Comment by karhow** [comment]
> 这个是 没有收到结束标识 导致，1.20.3-lts 优化超时问题之后，这个问题 不存在了

可以看看优化超时的mr吗？使用的老版本也出现这个问题了
