### ISSUE TITLE
[BUG]接口定义-TEST-加载用例只显示最新的一条

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13585]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.2-lts-b9564d5c

### 使用外置数据库

否

### 问题描述

接口定义-TEST-加载用例时只显示最新的一条，没有显示该接口下所有用例。

### 重现步骤

进入接口定义，前提是接口下包含多条case
![image](https://user-images.githubusercontent.com/18514555/168282205-4c154f76-de76-4d51-a970-6aef9f20e97b.png)

进入TEST，点击加载用例
![image](https://user-images.githubusercontent.com/18514555/168282667-9599b716-7288-4705-8a8e-be91ef374895.png)

只显示最近的一条
![image](https://user-images.githubusercontent.com/18514555/168282895-9b1d4e97-3160-40c4-8555-88437954a460.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复这个问题

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本已修复，请升级一下吧
