### ISSUE TITLE
[BUG]从项目A导出场景为metersphere格式，在项目B 接口自动化 下面导入，配置并选择环境，点调试后环境未生效

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13599]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

从项目A导出场景为metersphere格式，在项目B 接口自动化 下面导入，配置并选择环境，点调试后环境未生效

### 重现步骤

1. 在metersphere上 项目A下面，建一个场景，只有一个请求也行(get/post都行），配置好环境，调试通过。
2. 导出该场景
3. 在项目B下面，导入该场景，导入成功。
4. 在项目B下面，新导入场景，打开，配置一个新的环境
5. 点击调试
6. 请求内容里host为空。

### 期待的正确结果

在项目B下面，调试场景，环境变量可以正常使用。

**Comment by youliyuan-fit2cloud** [comment]
请说明 你这个场景里的请求是
 1.自定义请求；2.还是引用接口CASE;
3.还是复制接口case;
4.还是复制的接口 ？
请上传截图
请上传截图
请上传截图

**Comment by 35plus** [comment]
链接: https://pan.baidu.com/s/1qYtA4oEm7hfekC-Uvo-xiw 提取码: kab6 
测试文件

**Comment by zrfit** [comment]
您好，未复现该问题，是否有其它操作步骤？

**Comment by zrfit** [comment]
与用户确认该问题已不存。
