### ISSUE TITLE
[QUESTION]配置环境中的全局前置脚本和全局后置脚本和case的前置脚本和后置脚本的关系

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13594]
### 请描述您的问题

全局前置脚本和全局后置脚本和case的前置脚本和后置脚本的关系问题
1. 如果我在这个环境中设置了全局前置脚本和全局后置脚本，是否每个运行这个环境的case都会执行？
2. 这个环境中设置了全局前置脚本和全局后置脚本，case中也有前置脚本和后置脚本，case中的前置脚本和后置脚本是否还会生效？还是case中有前置脚本和后置脚本就全局前置脚本和全局后置脚本就不会生效？
3. 单个case中有前置脚本，接口访问，断言规则，后置脚本，那么执行的顺序是1.前置脚本，2.接口访问，3断言规则，4.后置脚本，是这样吗？因为我在单个case里发现是不能像场景测试一样调整顺序的

**Comment by Hyyfit** [comment]
1. 是的 
2. 都会生效，执行的顺序是全局前置脚本->前置脚本->后置脚本->全局后置脚本
3. 顺序是 前置脚本->接口访问->后置脚本->断言规则 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/95834771/168572651-c9462af6-f764-4b83-b805-bece73770331.png">
