### ISSUE TITLE
[BUG]JSON-SCHEMA按钮在切换的时候，会造成字段的描述消失

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13596]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/38156471/168416368-2d3c41fe-5ae8-40d2-8d8e-597fe061448d.png)
JSON-SCHEMA按钮在切换的时候，会把字段的描述内容置空，我也没有办法限制其他人不用这个功能，造成我还是需要在其他地方备份一套接口文档来说明字段的意思。

### 重现步骤

1. 可以复现，在任意接口有json格式的数据下切换JSON-SCHEMA按钮就出现这种情况了

### 期待的正确结果

切换不会造成描述消失，置空

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #12587
