### ISSUE TITLE
[BUG] 环境配置，使用模块方式匹配域名失败

### ISSUE THREAD

**Issue by ckelsel** [metersphere/metersphere#13597]
### MeterSphere 版本

版本:   v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

日志显示是 http:/area/，连最基本的https都没有选对

![image](https://user-images.githubusercontent.com/4329188/168419782-a46003c5-3b23-4a7a-ad47-2b9b44ac6758.png)

![image](https://user-images.githubusercontent.com/4329188/168419678-83dfcd93-1383-4509-b977-a88c8449fe6b.png)

### 重现步骤

偶然出现

**Comment by xkmyf** [comment]
HTTP配置页，右下角需要点下“添加”按钮 @ckelsel ，不点添加就会这样。
这块感觉他们需要优化下交互了。

**Comment by ckelsel** [comment]
更新现有的，也点了更新，还是不行

**Comment by zyl1012** [comment]
这个问题我也遇到了，情况是这样的：
我用swagger导入的接口，一开始有部分接口可以按模块读取到HTTP环境配置， 后来导入的接口都不行了。
或者本身可以正常读取环境配置的接口 使用swagger方式导出，把可以用的接口删除，再导入。这样后面导入的接口就变成不能用了。

临时有个解决办法：
任意更新一下接口的任意属性，就又变成可以正常读取到HTTP环境配置了。

**Comment by xulinde** [comment]
感谢反馈，我们尝试复现下

**Comment by xulinde** [comment]
> 这个问题我也遇到了，情况是这样的： 我用swagger导入的接口，一开始有部分接口可以按模块读取到HTTP环境配置， 后来导入的接口都不行了。 或者本身可以正常读取环境配置的接口 使用swagger方式导出，把可以用的接口删除，再导入。这样后面导入的接口就变成不能用了。
> 
> 临时有个解决办法： 任意更新一下接口的任意属性，就又变成可以正常读取到HTTP环境配置了。
> 
> PS: 如果批量导入非常多的接口，每个接口需要编辑一下才能正常用，也是很恶心的。。。

导入后模块就变了需要重新选择
