### ISSUE TITLE
[BUG]执行接口用例时，mock数据在发起接口请求前没有被转化

### ISSUE THREAD

**Issue by qiaoming8006** [metersphere/metersphere#13598]
### 联系方式

qiaoming8006@aliyun.com

### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

执行接口用例时，mock数据在发起接口请求前没有被转化

### 重现步骤

![image](https://user-images.githubusercontent.com/32956089/168420300-95daf274-37c5-46f1-ae96-70e63bd992ab.png)

### 期待的正确结果

执行接口用例时，mock数据在发起接口请求前是被转化了的
期望值："name": "Jack Zhang"
实际值："name": "${__Mock(@name)}"

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v1.20.2-lts修复该问题，升级一下吧

ps：后续提bug请添加标题~~~
