### ISSUE TITLE
[FEATURE]UI自动化测试不支持键盘的功能键输入

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13595]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

UI自动化测试不支持键盘的功能键输入，比如Enter键，页面也没有提示怎么输入。

**Comment by Hyyfit** [comment]
如果需要输入Enter，可以通过${KEY_ENTER} 来输入
感谢您的反馈，我们会加入说明文档，说明功能键的输入。
