### ISSUE TITLE
[QUESTION]接口CASE删除后没有在回收站中体现数量

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13605]
### 请描述您的问题

接口定义中删除CASE后，回收站目录没有统计数量，误以为CASE删除后没有进回收站。
请问回收站目录的数量只统计接口API的吗？
![image](https://user-images.githubusercontent.com/18514555/168427223-66160ae9-ca09-4e32-b06a-7e9c81426e65.png)

**Comment by Hyyfit** [comment]
是的，目前的设计是只展示api的数量。
