### ISSUE TITLE
[BUG]UI测试报告中的截图也太小了，根本无法分辨是否操作成功

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13604]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

![Uploading image.png…]()

### 重现步骤

重新跑一次就可以出现了

### 期待的正确结果

将截图显示在下放的操作中

**Comment by zrfit** [comment]
您好，您的图片看不到，点击报告中的截图是可以放大查看的。
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/99731894/168511608-90e0b18f-f54c-4686-a52e-ed5c7b395f47.png">

**Comment by YellCatt** [comment]
> 您好，您的图片看不到，点击报告中的截图是可以放大查看的。 <img alt="image" width="1297" src="https://user-images.githubusercontent.com/99731894/168511608-90e0b18f-f54c-4686-a52e-ed5c7b395f47.png">

是能放大，但是能不能直接点啊，就直接显示大图？

**Comment by zrfit** [comment]
您好，您的问题是：UI测试报告中的截图也太小了，根本无法分辨是否操作成功，鼠标放到截图上就弹出缩略图，点击缩略图可查看截图的放大图片，即可看到对应的结果。
您的意思是要点击截图就弹出大图吗？

**Comment by YellCatt** [comment]
> 您好，您的问题是：UI测试报告中的截图也太小了，根本无法分辨是否操作成功，鼠标放到截图上就弹出缩略图，点击缩略图可查看截图的放大图片，即可看到对应的结果。 您的意思是要点击截图就弹出大图吗？

我的意思是小图很不方便，能不能直接点，可以弹出大图，也可以就在下面展示大图，可以参考下airtest的测试报告啊

**Comment by zrfit** [comment]
您好，感谢您的反馈，这个意见我们会反馈给产品人员再决定是否优化。

**Comment by zrfit** [comment]
v2.1.0已优化，鼠标悬浮在截图上不显示小图，点击截图-直接弹出展示大图。
