### ISSUE TITLE
[BUG]设置使用外部kafka，将zookeeper.enabled 和 kafka.enabled 改为 false，还是会安装zk和kafka

### ISSUE THREAD

**Issue by jiaxinonly** [metersphere/metersphere#13609]
### 联系方式

1094630886@qq.com

### MeterSphere 版本

1.20.1-lts

### 使用外置数据库

是

### 问题描述

使用helm安装chart metersphere-1.1.2，设置使用外部kafka，将zookeeper.enabled 和 kafka.enabled 改为 false，还是会安装zk和kafka

### 重现步骤

1.修改kafka地址为外部kafka地址
2.将zookeeper.enabled 和 kafka.enabled 改为 false
3.部署

**Comment by liuruibin** [comment]
已修复，更新repo后使用

**Comment by jiaxinonly** [comment]
使用1.1.4版本的chart，确实没有再创建kakfa和zk，另外我使用的1.23版本的k8s，集群ingress api还存在一些问题
![03XW(QX8E22M_B@7EPRY(GK](https://user-images.githubusercontent.com/57223696/169454572-396e85fb-05fe-42eb-8197-80dc1e81de0a.png)
版本信息如下：
```
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```
最后建议能够在chart中指定mysql数据库，很多情况下一般由管理员使用root账号创建数据库和用户，在给程序使用

**Comment by jiaxinonly** [comment]
另外还存在一个致命的bug，在集群中部署，未创建account metersphere
![image](https://user-images.githubusercontent.com/57223696/169463621-073bbd76-0e7d-4d97-bbc7-112981a2acda.png)
我觉得这不应该是一个发布出来的chart
