### ISSUE TITLE
[BUG]脚本断言弹窗，鼠标不小心一滑动，弹窗就消失了，可稳定复现

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13608]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

脚本断言弹窗，弱不禁风，鼠标不小心一滑动，弹窗就消失了，可稳定复现

### 重现步骤

1. 新建一个场景
2. 导入一个接口
3. 在断言tab，新增一个脚本断言
    
![1652586848(1)](https://user-images.githubusercontent.com/76033005/168456477-8051ed15-e3fa-4c77-87c4-3bff9941f0bb.png)

5.  点编辑
![1652586898(1)](https://user-images.githubusercontent.com/76033005/168456492-fc6cdb5b-5117-442a-8ead-61a51fc3ea21.png)
6.按照下图注释，操作一下，即可看到现象。好几种情况都会触发弹窗消失，这种情况可以稳定复现。 这个问题，让用户非常painful。
![1652586985(1)](https://user-images.githubusercontent.com/76033005/168456532-eda1e5db-721d-46df-9cfa-c4ef2b1884b8.png)

**Comment by youliyuan-fit2cloud** [comment]
可以优化，
PS：虽然应该优化这个问题，但是看到你的标题写的有点让我们不想优化了。。。。。下次请仅描述问题即可，不要说无用的词，比如：“弱不禁风”，这个词多形容女人。。。感谢~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本中已修复
