### ISSUE TITLE
[FEATURE]UI测试中的元素库描述是否可以上传一张截图说明，而不是单传的靠文字描述

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13603]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/38156471/168426636-35765b68-a30c-4a98-ad0c-85cdbc30fc79.png)
是否可以上传一张截图说明，而不是靠文字描述

**Comment by Hyyfit** [comment]
感谢反馈，元素这里我们还在优化，后续会支持显示元素的预览图。
