### ISSUE TITLE
[FEATURE]接口测试响应的内容无法在一页中看到，测试发现接口有问题，发给开发都要截两张图

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13602]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/38156471/168426475-921efb9e-408b-4ae9-8e5e-abd3f6584702.png)
响应的内容无法在一页中看到，测试发现接口有问题，发给开发都要截两张图

**Comment by Hyyfit** [comment]
感谢反馈，这里我们已规划了优化，支持调整大小。
