### ISSUE TITLE
[QUESTION]UI自动化无法断言最后的结果是否成立

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13601]
### 请描述您的问题

UI自动化无法断言最后的结果是否成立
![image](https://user-images.githubusercontent.com/38156471/168426420-bcc9e427-3466-4e0f-9262-f93731f84e1c.png)

**Comment by Hyyfit** [comment]
在高级设置--后置操作---断言
<img width="470" alt="image" src="https://user-images.githubusercontent.com/95834771/168562616-ff882291-3689-4e4d-9601-ff066e5c6e3d.png">
