### ISSUE TITLE
[QUESTION]MS专业测试云是企业版本吗？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13612]
### 请描述您的问题

MS专业测试云是企业版本吗？如果是，为什么没有接口文档的导出功能，我提过这个问题，工作人员回复我多个接口的文档分享是企业版功能？
如果不是，为什么专业测试云有企业版本的UI测试功能？
我不太理解。

**Comment by maninhill** [comment]
专业测试云包括企业版 X-Pack 功能增强包的功能。

**Comment by YellCatt** [comment]
> 专业测试云包括企业版 X-Pack 功能增强包的功能。

你的意思是专业测试云包含X-Pack 功能增强包的功能，但是并没有企业版的接口文档导出功能吗？

**Comment by wangzhen-fit2cloud** [comment]
功能都是有的，不知道你指的接口文档导出功能没有，具体是哪里。
![image](https://user-images.githubusercontent.com/27671436/168470175-a34ab5a7-6f48-49d8-a2bc-9a63d1d2daff.png)

**Comment by YellCatt** [comment]
> 功能都是有的，不知道你指的接口文档导出功能没有，具体是哪里。 ![image](https://user-images.githubusercontent.com/27671436/168470175-a34ab5a7-6f48-49d8-a2bc-9a63d1d2daff.png)
接口文档是用来给第三方的开发人员或者测试用来测试接口使用的，你这个接口的导出是用来重新导入的ms平台的，你自己导出看看，都是一堆的代码

**Comment by YellCatt** [comment]
>

**Comment by wangzhen-fit2cloud** [comment]
分享功能的话，也是有的
![image](https://user-images.githubusercontent.com/27671436/168470779-f4985a88-5aa3-4659-ad7d-73821e6314bc.png)

**Comment by YellCatt** [comment]
> 分享功能的话，也是有的 ![image](https://user-images.githubusercontent.com/27671436/168470779-f4985a88-5aa3-4659-ad7d-73821e6314bc.png)

我问的一直是导出接口的文档，而不是分享啊，你分享文档，你打算给现场的人用，给第三方的开发人员用，还是给测试人员用？

**Comment by wangzhen-fit2cloud** [comment]
接口文档导出功能，目前支持截图中的两种格式（https://github.com/metersphere/metersphere/issues/13612#issuecomment-1126913950），没有 markdown、word 等文档格式。

**Comment by YellCatt** [comment]
> 接口文档导出功能，目前支持截图中的两种格式（[https://github.com/metersphere/metersphere/issues/13612#issuecomment-1126913950），没有](https://github.com/metersphere/metersphere/issues/13612#issuecomment-1126913950%EF%BC%89%EF%BC%8C%E6%B2%A1%E6%9C%89) markdown、word 等文档格式。

这不是接口文档导出啊，哪有接口文档导出是为了导入使用的？

**Comment by wangzhen-fit2cloud** [comment]
很抱歉，目前是没有这个功能呢。
