### ISSUE TITLE
[FEATURE]接口测试用例页面中，前置脚本编辑器中，选择BeanShell后，点击右侧的快捷提示动作时，生成的代码末尾加分号

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#13613]
### MeterSphere 版本

v1.20.1

### 请描述您的需求或者改进建议

场景：
前置脚本编辑器中，选择BeanShell后，点击右侧的快捷提示动作时，生成的代码末尾没有分号，如下面所示，如果用户增加了多行脚本代码，因不熟悉或忘记加分号，就会报错
vars.get("variable_name")
例如，改成如下脚本内容后，执行时就会报错
dbname=vars.get("dbname")
log.info("dbname="+dbname)
查错后，报错原因是，BeanShell脚本中，语法要求每行代码末尾使用分号结束。

<img width="845" alt="Screen Shot 2022-05-16 at 1 28 45 AM" src="https://user-images.githubusercontent.com/9998431/168485933-919617bf-08e2-41ee-ba3f-a6522ad914d0.png">

<img width="849" alt="Screen Shot 2022-05-16 at 1 30 02 AM" src="https://user-images.githubusercontent.com/9998431/168485991-1f133139-155e-4da6-a510-bfca0ce869af.png">

<img width="789" alt="Screen Shot 2022-05-16 at 1 30 12 AM" src="https://user-images.githubusercontent.com/9998431/168485995-a90e7bac-d119-43f0-af63-137162694c7f.png">

### 请描述你建议的实现方案

期望：生成的代码末尾加分号，提升用户体验，避免没加分号报错，查错
如: vars.get("variable_name");

**Comment by jason-fit2cloud** [comment]
python类型的，加分号后，不会影响报错

**Comment by jason-fit2cloud** [comment]
建议在快捷操作里增加【打印变量到控制台】，这个也是调试脚本时常用的

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
