### ISSUE TITLE
[BUG] 各个模块的首页页面布局间距不一样

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13616]
### 联系方式

lsj

### MeterSphere 版本

1.20.2-lts

### 使用外置数据库

否

### 问题描述

请参考截图：

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/41712985/168508760-c6c369d8-39d6-4ba3-85dd-7aa75d872ea7.png">
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/41712985/168508824-872c44d7-9fdd-415a-a866-08c9f0438150.png">
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/41712985/168508910-d2eda540-ca9c-46f4-a7ef-fb62a96c8997.png">
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/41712985/168509002-b848ea09-dd65-4322-b6b4-249ff81a850e.png">

### 重现步骤

请参考截图。

### 期待的正确结果

希望各个模块布局间距等保持一致。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复~
