### ISSUE TITLE
[BUG]新建場景，導入子場景后，無法刪除子場景

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1361]
**MeterSphere 版本**
    MeterSphere v1.7
**Bug 描述**
简要描述您碰到的问题
  新建場景，導入子場景后，無法刪除引用的子場景
**Bug 重现步骤**

**期待的正确结果**
   可以正常刪除子場景

**截图**
如果有截图，请附上截图.

**Comment by xulinde2** [comment]
您好，v1.7.1版本已修复该问题，您直接升级下就可以了

**Comment by xulinde** [comment]
您好，v1.7.1版本已修复该问题，您直接升级下就可以了
