### ISSUE TITLE
[QUESTION]mock没有成功

### ISSUE THREAD

**Issue by NickLans** [metersphere/metersphere#13610]
### 请描述您的问题

mock的设置如图1。测试结果如图2。想问下我哪里设置错了吗，为什么没有返回我想要的响应结果
![image](https://user-images.githubusercontent.com/104554834/168461542-86e74749-df87-4731-8ffd-a3cb2b83cca1.png)
![image](https://user-images.githubusercontent.com/104554834/168461620-0b9dc588-1006-4677-b7ef-80ffe6471723.png)

**Comment by NickLans** [comment]
请求内容如图
![image](https://user-images.githubusercontent.com/104554834/168461801-8df2dd0b-951e-4c81-ac91-6c2f0280de20.png)

**Comment by Hyyfit** [comment]
您好，您用的是哪个版本的？
我这边测试 是可以的
首先要确保mock的状态是启用的
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/95834771/168561116-4b148b65-388e-4ce0-b65c-3d3abe10d6fe.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/95834771/168560767-5c750b8c-da3a-4d9c-85ad-08510d86efda.png">

**Comment by NickLans** [comment]
版本:   v1.18.2-f641f6f6
mock的状态是启用的

**Comment by Hyyfit** [comment]
您加一下我的企业微信。脚本发我看看哈
<img width="317" alt="image" src="https://user-images.githubusercontent.com/95834771/170626464-9feef519-6e17-4f3d-89be-b8416e4dc4ae.png">
