### ISSUE TITLE
[FEATURE] [企业用户] 断言中如果字符过长显示不全，期望有悬浮显示的功能

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13627]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/103017812/168535071-30409b78-fbf5-4c23-b8ba-8b905d87b1c9.png)

### 请描述你建议的实现方案

鼠标悬停是可以显示全量信息

**Comment by Hyyfit** [comment]
感谢您的反馈，已规划，待排期。

**Comment by 35plus** [comment]
帮忙给一个排期。
