### ISSUE TITLE
[FEATURE]SMTP设置账户和发件人分开设置

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#1362]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
当邮件配置的SMTP账户和发送邮件人不一样时，无法发送邮件。
**Bug 重现步骤**
1.  邮件配置处填写一个不是邮箱地址的SMTP账户
2.然后进行一个定时任务，邮件不能发送

**期待的正确结果**
正确情况下应该是什么样的？
应该将SMTP账户和发送邮件人分开，不应将他们放在一起
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/51906428/106707762-b8cd7980-662c-11eb-8ab7-fa74ea62f7f7.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，近期版本考虑优化下~

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
