### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by coolbadger** [metersphere/metersphere#13638]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

接口测试或调试过程中，如果出现请求结果错误，现在无法直接保存这个错误请求结果用于排查接口问题。

### 请描述你建议的实现方案

在场景调试的响应内容页，增加一个保存为测试用例的按钮，把结果保存至对应的接口用例列表中。

### 附加信息
![image ](https://designorder-cdn.oss-cn-shanghai.aliyuncs.com/user-guid/issue/81B60BF1-FAB0-44ae-9514-148A49C57FBC.png)

**Comment by Hyyfit** [comment]
您好，目前的设计是这样的。
如果需要查看之前的运行结果来排查问题，可以通过调试历史，查看之前运行结果
<img width="532" alt="image" src="https://user-images.githubusercontent.com/95834771/168557692-119d0e69-b3e7-40fa-a676-adc8745c2d6b.png">
