### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#1363]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题
在SQL脚本窗口写完SQL执行成功后再修改SQL语句再次执行，响应内容没有任何变化
**Bug 重现步骤**
1.  接口测试-接口定义 选择SQL
2. 在SQL脚本窗口写SQL执行成功返回响应内容后，再次修改SQL语句点击测试按钮
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
在SQL脚本窗口写完SQL执行成功后再修改SQL语句再次执行，响应内容跟随变化
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
