### ISSUE TITLE
[BUG][企业客户] 断言用使用‘文档’结构校验‘当json较大是有性能问题导致平台页面奔溃

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13633]
### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

断言用使用‘文档’结构校验‘当json较大是有性能问题导致平台页面奔溃
![image](https://user-images.githubusercontent.com/103017812/168545402-c4dbad71-4827-4e66-8fff-d8a9125642b6.png)
文档结构见重现步骤

### 重现步骤

{
    "extendedProps": {
        
    },
    "policyType": 1,
    "applyDate": "2022-05-16T00:00:00.000+0800",
    "submissionDate": "2022-05-16T00:00:00.000+0800",
    "nextDueDate": "2023-05-16T00:00:00.000+0800",
    "riskStatusDate": "2022-05-16T00:00:00.000+0800",
    "inceptionDate": "2022-05-16T00:00:00.000+0800",
    "issueDate": "2022-05-16T15:55:41.000+0800",
    "expiryDate": "9999-09-09T08:00:00.000+0800",
    "policyNumber": "0000083997",
    "proposalNumber": "0000083997",
    "quotationCode": "20220516155539610",
    "salesChannelCode": "1",
    "deliverType": "M",
    "discountType": "2",
    "currency": 1,
    "backdatingIndi": "N",
    "installPrem": 31000.00,
    "riskStatus": 1,
    "assignmentType": "0",
    "proposalInfo": {
        "proposalStatus": "85"
    },
    "coverages": [
        {
            "extendedProps": {
                "productCode": "RegularILP_PayWL_ByPrem",
                "isInvestLinkedCoverage": "true",
                "productName": "Regular Premium Investment Linked Product"
            },
            "coverageNo": "72366795",
            "chargePeriod": "3",
            "chargeYear": 80,
            "coveragePeriod": "1",
            "coverageYear": 0,
            "riskCommencementDate": "2022-05-16T00:00:00.000+0800",
            "riskStatusDate": "2022-05-16T00:00:00.000+0800",
            "bonusSa": 0.00,
            "expiryDate": "9999-09-09T08:00:00.000+0800",
            "paidupDate": "2081-05-15T00:00:00.000+0800",
            "riskStatus": 1,
            "premStatus": 1,
            "inceptionDate": "2022-05-16T00:00:00.000+0800",
            "productCode": "RegularILP_PayWL_ByPrem",
            "productId": 4000764,
            "renewDecision": "0",
            "waitPeriod": 0,
            "waiverExt": {
                "waiver": "N",
                "waivedSa": 0.00,
                "waivAnulPrem": 0
            },
            "currentPremium": {
                "countWay": "2",
                "paymentFreq": "1",
                "paymentMethod": 1,
                "sumAssured": 20000.00,
                "premium": 20000.000000,
                "grossPremium": 20000.000000,
                "unit": 0.00,
                "premiumAn": 20000.000000,
                "discntedPremAn": 20000.000000,
                "totalPremAf": 20000.000000,
                "policyFeeAn": 0.000000,
                "extraPremAn": 0.000000,
                "extraPremAf": 0.000000,
                "stdPremAf": 20000.000000
            },
            "nextPremium": {
                "countWay": "2",
                "paymentFreq": "1",
                "paymentMethod": 1,
                "sumAssured": 20000.00,
                "premium": 20000.000000,
                "grossPremium": 20000.000000,
                "unit": 0.00,
                "premiumAn": 20000.000000,
                "discntedPremAn": 20000.000000,
                "totalPremAf": 20000.000000,
                "policyFeeAn": 0.000000,
                "extraPremAn": 0.000000,
                "extraPremAf": 0.000000,
                "stdPremAf": 20000.000000
            },
            "coverageAgents": [
                {
                    "extendedProps": {
                        
                    },
                    "assignRate": 1.0000
                }
            ],
            "payPlans": [
                
            ],
            "insureds": [
                {
                    "extendedProps": {
                        
                    },
                    "insuredPartyId": "72367070",
                    "orderId": 1,
                    "occupationClass": 0,
                    "age": 21,
                    "entryAgeMonth": 0
                }
            ],
            "premInvestRates": [
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund001",
                    "assignRate": 0.40000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund002",
                    "assignRate": 0.60000000
                }
            ],
            "recurringTopup": {
                "extendedProps": {
                    
                },
                "topupAmount": 1000.00,
                "topupStartDate": "2022-05-16T00:00:00.000+0800",
                "investRates": [
                    {
                        "extendedProps": {
                            
                        },
                        "fundCode": "Fund003",
                        "assignRate": 0.20000000
                    },
                    {
                        "extendedProps": {
                            
                        },
                        "fundCode": "Fund004",
                        "assignRate": 0.80000000
                    }
                ]
            },
            "contractInvests": [
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund001",
                    "accumUnits": 0.000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund002",
                    "accumUnits": 0.000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund003",
                    "accumUnits": 0.000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund004",
                    "accumUnits": 0.000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund005",
                    "accumUnits": 0.000000
                },
                {
                    "extendedProps": {
                        
                    },
                    "fundCode": "Fund006",
                    "accumUnits": 0.000000
                }
            ],
            "mortgageRates": [
                
            ],
            "extraPrems": [
                {
                    "extendedProps": {
                        
                    },
                    "listId": 72366798,
                    "endDate": "2081-05-15T00:00:00.000+0800",
                    "extraArith": "4",
                    "extraPara": 0.100000,
                    "extraType": "A",
                    "startDate": "2022-05-16T00:00:00.000+0800",
                    "extraPrem": 0.00,
                    "extraPremAn": 0.00,
                    "extraStatus": "0",
                    "nextExtraPara": 0.100000,
                    "nextExtraPrem": 0.00,
                    "nextExtraPremAn": 0.00,
                    "reCalcIndi": "N"
                }
            ],
            "flightExt": {
                "oneWayIndi": "N"
            },
            "mortgageExt": {
                "extendedProps": {
                    
                },
                "mortgageRepayFrequency": "4",
                "deferPeriodOption": "0",
                "deferPeriod": 0
            },
            "saSchedules": [
                
            ],
            "coverageLiabilities": [
                
            ],
            "premStreams": [
                {
                    "extendedProps": {
                        
                    },
                    "totalPremAf": 20000.00,
                    "premMonths": 12,
                    "startDate": "2022-05-16T00:00:00.000+0800",
                    "nextTotalPremAf": 20000.00,
                    "activeIndi": "Y"
                }
            ],
            "coverageExtend": {
                "extendedProps": {
                    
                },
                "itemId": 72366795,
                "dueDate": "2023-05-16T00:00:00.000+0800",
                "policyId": 72366787,
                "policyPeriod": 1,
                "policyYear": 1,
                "premStatus": 1,
                "saDueDate": "2023-05-16T00:00:00.000+0800",
                "strgyDueDate": "2023-05-16T00:00:00.000+0800",
                "billingDate": "2023-05-09T00:00:00.000+0800",
                "indxDueDate": "2022-05-16T00:00:00.000+0800",
                "indxReject": 0
            },
            "policyFundCharges": [
                {
                    "extendedProps": {
                        
                    },
                    "listId": 72367138,
                    "chargeCode": "5",
                    "chargeDueDate": "2022-05-16T00:00:00.000+0800",
                    "coverageId": 72366795,
                    "policyId": 72366787,
                    "productId": 4000764
                },
                {
                    "extendedProps": {
                        
                    },
                    "listId": 72367139,
                    "chargeCode": "6",
                    "chargeDueDate": "2022-05-16T00:00:00.000+0800",
                    "coverageId": 72366795,
                    "policyId": 72366787,
                    "productId": 4000764
                }
            ],
            "riskCommenceDate": "2022-05-16T00:00:00.000+0800"
        }
    ],
    "policyHolder": {
        "extendedProps": {
            
        },
        "partyId": "72367063",
        "policyCustomer": {
            "extendedProps": {
                
            },
            "partyType": 1,
            "person": {
                "gender": "M",
                "birthdate": "2001-11-02T00:00:00.000+0800",
                "certiType": 1,
                "certiCode": "PHILPID20220516155539610",
                "firstName": "PHILPTEST20220516155539610",
                "lastName": "PHILPTESTL20220516155539610",
                "nationality": "99",
                "preferredLifeIndi": "0",
                "smoking": "N",
                "occupationCode": "2",
                "marriageStatus": "6",
                "employedIndi": "N"
            },
            "organization": {
                
            },
            "partyContact": {
                "mobileTel": "1234567890",
                "email": "e-mail@test.com"
            },
            "address": {
                "extendedProps": {
                    
                },
                "address1": "Shanghai",
                "address2": "",
                "address3": "",
                "address4": "eBao",
                "postCode": "222222",
                "addressId": 72367069
            }
        },
        "relationToLA": 3
    },
    "insureds": [
        {
            "extendedProps": {
                
            },
            "partyId": "72367070",
            "policyCustomer": {
                "extendedProps": {
                    
                },
                "partyType": 1,
                "person": {
                    "gender": "M",
                    "birthdate": "2001-11-02T00:00:00.000+0800",
                    "certiType": 1,
                    "certiCode": "LAILPID20220516155539610",
                    "firstName": "LAILPTEST20220516155539610",
                    "lastName": "LAILPTESTL20220516155539610",
                    "nationality": "99",
                    "preferredLifeIndi": "0",
                    "smoking": "N",
                    "occupationCode": "2",
                    "marriageStatus": "6",
                    "employedIndi": "N"
                },
                "organization": {
                    
                },
                "partyContact": {
                    "mobileTel": "1234567890",
                    "email": "e-mail@test.com"
                },
                "address": {
                    "extendedProps": {
                        
                    },
                    "address1": "Shanghai",
                    "address2": "",
                    "address3": "",
                    "address4": "eBao",
                    "postCode": "222222",
                    "addressId": 72367076
                }
            },
            "relationToPH": 3,
            "relationToMainInsured": 1,
            "medicalIndi": "N",
            "socialSecurityIndi": "N",
            "medicalExamIndi": "N",
            "preferredLifeIndi": "0",
            "activeStatus": "1",
            "addressId": 72367076,
            "policyCustomerId": 72366789,
            "birthDate": "2001-11-02T00:00:00.000+0800",
            "emValue": 0,
            "gender": "M",
            "housekeeper": "N",
            "liveRange": "0",
            "moveRange": "0",
            "occupCate": 2,
            "parentSa": 0.00,
            "retiredFlag": "W",
            "smokerStatus": "N",
            "standLifeIndi": "Y",
            "policyRoleType": "9"
        }
    ],
    "beneficiaries": [
        {
            "extendedProps": {
                
            },
            "partyId": "72367063",
            "policyCustomer": {
                "extendedProps": {
                    
                },
                "partyType": 1,
                "person": {
                    "gender": "M",
                    "birthdate": "2001-11-02T00:00:00.000+0800",
                    "certiType": 1,
                    "certiCode": "PHILPID20220516155539610",
                    "firstName": "PHILPTEST20220516155539610",
                    "lastName": "PHILPTESTL20220516155539610",
                    "nationality": "99",
                    "preferredLifeIndi": "0",
                    "smoking": "N",
                    "occupationCode": "2",
                    "marriageStatus": "6",
                    "employedIndi": "N"
                },
                "organization": {
                    
                },
                "partyContact": {
                    "mobileTel": "1234567890",
                    "email": "e-mail@test.com"
                },
                "address": {
                    "extendedProps": {
                        
                    },
                    "address1": "Shanghai",
                    "address2": "",
                    "address3": "",
                    "address4": "eBao",
                    "postCode": "222222",
                    "addressId": 72367069
                }
            },
            "beneNo": 72366792,
            "beneType": "2",
            "designation": 1,
            "insuredPartyId": "72367070",
            "shareOrder": 1,
            "shareRate": 1.000000
        }
    ],
    "payerAccounts": [
        {
            "extendedProps": {
                
            },
            "ddaMandateIndi": "W",
            "nextDdaMandateIndi": "W",
            "paymentMethod": 1,
            "paymentMethodNext": 1,
            "payerPartyId": "72367063"
        }
    ],
    "declarations": [
        
    ],
    "agentDeclarations": [
        
    ],
    "premTaxes": [
        
    ],
    "payers": [
        {
            "extendedProps": {
                
            },
            "partyId": "72367063",
            "policyCustomer": {
                "extendedProps": {
                    
                },
                "partyType": 1,
                "person": {
                    "gender": "M",
                    "birthdate": "2001-11-02T00:00:00.000+0800",
                    "certiType": 1,
                    "certiCode": "PHILPID20220516155539610",
                    "firstName": "PHILPTEST20220516155539610",
                    "lastName": "PHILPTESTL20220516155539610",
                    "nationality": "99",
                    "preferredLifeIndi": "0",
                    "smoking": "N",
                    "occupationCode": "2",
                    "marriageStatus": "6",
                    "employedIndi": "N"
                },
                "organization": {
                    
                },
                "partyContact": {
                    "mobileTel": "1234567890",
                    "email": "e-mail@test.com"
                },
                "address": {
                    "extendedProps": {
                        
                    },
                    "address1": "Shanghai",
                    "address2": "",
                    "address3": "",
                    "address4": "eBao",
                    "postCode": "222222",
                    "addressId": 72367069
                }
            },
            "payerNo": 72366793,
            "activeStatus": "1",
            "shareRate": 1.000000,
            "relationToPH": 1
        }
    ],
    "policyAccounts": [
        
    ],
    "assignees": [
        
    ],
    "suspend": "N",
    "pendingPolicyAlterationsList": [
        {
            "extendedProps": {
                
            },
            "changeId": 72366819,
            "changeType": "1",
            "changeSource": "4",
            "finishTime": "2022-05-16T15:55:41.000+0800",
            "changeStatus": 4,
            "alterationItems": [
                {
                    "extendedProps": {
                        
                    },
                    "policyChgId": 72366820,
                    "serviceId": 32,
                    "validateTime": "2022-05-16T00:00:00.000+0800",
                    "applyTime": "2022-05-16T15:55:40.000+0800",
                    "orderId": 1,
                    "policyChgStatus": 2,
                    "changeSequence": 0,
                    "subServiceId": 32,
                    "fundTransactionRequests": [
                        {
                            "applyId": 72367145,
                            "fundCode": "Fund001",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 3200.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "1",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366827,
                            "premType": 2
                        },
                        {
                            "applyId": 72367146,
                            "fundCode": "Fund002",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 4800.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "1",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366827,
                            "premType": 2
                        },
                        {
                            "applyId": 72367147,
                            "fundCode": "Fund003",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 190.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "53",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366831,
                            "premType": 3
                        },
                        {
                            "applyId": 72367148,
                            "fundCode": "Fund004",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 760.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "53",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366831,
                            "premType": 3
                        },
                        {
                            "applyId": 72367149,
                            "fundCode": "Fund005",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 950.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "3",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366807,
                            "premType": 4
                        },
                        {
                            "applyId": 72367150,
                            "fundCode": "Fund006",
                            "policyId": 72366787,
                            "productId": 4000764,
                            "transCode": 1,
                            "applyAmount": 8550.00000,
                            "applyUnits": 0.000000,
                            "applyTime": "2022-05-16T15:55:41.000+0800",
                            "currencyId": 1,
                            "transChargeFee": 0.00,
                            "itemId": 72366795,
                            "processStatus": "0",
                            "capitalChgId": 72366820,
                            "distriType": "3",
                            "applicationDate": "2022-05-16T15:55:42.000+0800",
                            "realApplyTime": "2022-05-16T00:00:00.000+0800",
                            "targetDate": "2022-05-16T15:55:41.000+0800",
                            "streamId": 72366807,
                            "premType": 4
                        }
                    ],
                    "fundTrans": [
                        
                    ]
                }
            ]
        }
    ],
    "miscDebt": 0.00,
    "organId": 70686567,
    "branchId": 70686567
}

**Comment by zrfit** [comment]
您好，该问题v1.20.7-lts已修复。
