### ISSUE TITLE
[BUG]接口或者场景中请求体JSONSchema中的root采用array类型发起的请求参数有误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#13646]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.2-LTS

### 使用外置数据库

否

### 问题描述

接口或者场景中请求体JSONSchema中的root采用array类型发起的请求参数有误,导致发起的请求失败

### 重现步骤

1、创建一个POST请求
2、请求体打开JSONSchema
3、root类型选择array
4、添加几个参数
5、打开预览
6、发起请求
7、实际发起请求内容与预览中的数据不一致

### 附加信息

JsonSchema：
![image](https://user-images.githubusercontent.com/32027713/168605816-4474365c-8f5a-4f4b-bf3e-efd8dfad2760.png)
预览：
<img width="840" alt="image" src="https://user-images.githubusercontent.com/32027713/168605936-668f98af-f9a5-4b80-9ca7-405d2990e4b4.png">

实际发出请求：
![image](https://user-images.githubusercontent.com/32027713/168605902-1ea5c132-eba1-404e-bd60-388cdcfd5d09.png)

**Comment by 35plus** [comment]
链接: https://pan.baidu.com/s/18Kq8aPE8BhAmHCm1fJE8bQ 提取码: njsp 
客户给的测试文件

**Comment by youliyuan-fit2cloud** [comment]
下个小版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本中已修复
