### ISSUE TITLE
[BUG]【接口自动化】执行场景用例导致崩溃

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#13641]
### MeterSphere 版本

v1.20.2-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】执行场景用例过程中导致页面卡死崩溃

### 重现步骤

【接口自动化】执行场景用例过程中导致页面卡死崩溃

### 相关日志输出

```shell
错误代码：RESULT_CODE_HUNG
```

**Comment by zyyfit** [comment]
您好，能详细描述一下吗？是什么场景导致了崩溃呢？方便把可以复现的场景给我们看看吗
