### ISSUE TITLE
[BUG]metersphere平台的编码结果存在问题，编码的时候把@符号也一并编码了

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#13642]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

metersphere平台的编码结果有问题。编码的时候把@符号也一并编码了。
![image](https://user-images.githubusercontent.com/100331967/168570025-51d364b5-c817-4d2a-87fc-7355d62652af.png)
![image](https://user-images.githubusercontent.com/100331967/168570039-35bafa6e-6401-49c1-b789-689cbee2486b.png)

### 重现步骤

1.在参数设置里面，选择base64编码方式，录入的编码原文是123456a
2.点击预览，预览出的结果与其他base64在线编译工具的结果不一致。经尝试验证，发现是多编译了@符号

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/13537
