### ISSUE TITLE
[BUG]测试计划定时任务执行场景，偶发场景中case无法正确引用环境参数

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#13651]
### MeterSphere 版本

v1.19

### 使用外置数据库

是

### 问题描述

测试计划定时任务执行时（频率五分钟一次）大批量执行时，其中发现两份报告中，场景中的case 部分请求头变量，无法正确的引用到对应的环境参数，引用到的值为空，导致接口请求失败；
1.环境参数
<img width="860" alt="截屏2022-05-17 下午12 34 28" src="https://user-images.githubusercontent.com/34637801/168729731-b6b8500d-b713-4e34-84f0-04ea6f22defb.png">
2.接口case引用参数为空
<img width="964" alt="截屏2022-05-17 下午12 45 59" src="https://user-images.githubusercontent.com/34637801/168731030-d53b1ac2-8622-4fe5-8061-d19dac4a83a4.png">

### 重现步骤

1.创建两个环境，并设置通用配置的环境参数；
2.创建一个场景，场景中的case的请求头中的多个变量引用了上一步骤中设置的环境参数；
3.创建一个测试计划，开启重复引用场景的设置；
4.重复关联该场景，并使用不同的环境；
5.开启测试计划定时任务，执行频率为5分钟执行一次；

补充说明：该缺陷暂时无法稳定复现；

### 期待的正确结果

1场景中的case请求头中的变量能正确引用到环境参数，保障场景中的接口case请求成功；

**Comment by zyyfit** [comment]
我定时执行了几个测试计划，5分钟一次，一共90多个场景，虽然没有1600个场景那么多，没有复现这个问题
