### ISSUE TITLE
安装启动完成后，ms-server一直是starting状态，无法访问

### ISSUE THREAD

**Issue by astroxing** [metersphere/metersphere#13659]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/65709435/168775794-2cf1990f-3e78-466b-8e8b-4ca3e68537e3.png)

**Comment by youliyuan-fit2cloud** [comment]
贴一下log吧 ：
docker logs ms-server

**Comment by astroxing** [comment]
> 贴一下log吧 ： docker logs ms-server
[log.txt](https://github.com/metersphere/metersphere/files/8708232/log.txt)

**Comment by youliyuan-fit2cloud** [comment]
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/54612864/168817321-f7ba35dc-8a3b-4142-9107-4b4e769f47d3.png">

redis server 是单独的？检查一下MS 机器和这个redis server 的网络

**Comment by astroxing** [comment]
> <img alt="image" width="1074" src="https://user-images.githubusercontent.com/54612864/168817321-f7ba35dc-8a3b-4142-9107-4b4e769f47d3.png">
> 
> redis server 是单独的？检查一下MS 机器和这个redis server 的网络

redis不是单独安装的，由docker统一安装的。还有就是这个无法连接，会不会是redis密码的问题。

**Comment by astroxing** [comment]
从外面能telnet通redis这个IP和端口，但是还是报这个错误，求解答

**Comment by liuruibin** [comment]
redis 能使用别的客户端工具连进去吗

**Comment by AgAngle** [comment]
![image](https://user-images.githubusercontent.com/41557596/169301347-df530d80-92e5-43df-a6b4-3c6909fe37af.png)
容器里访问不到这个端口，如果是用的默认安装的redis，修改下 .env 文件，改成 redis ，然后 msctl reload

**Comment by casezhao** [comment]
这个问题解决了嘛，我也遇到了同样的问题
