### ISSUE TITLE
[BUG]测试计划包含场景，选择资源池+并行的执行模式存在场景的报告状态错误的情况

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#13658]
### MeterSphere 版本

v1.19

### 使用外置数据库

否

### 问题描述

测试计划包含了接口场景，定时任务执行时（频率为5分钟一次），部分场景报告的状态为success，场景中包含的接口状态为“失败”，失败原因是断言失败；

场景报告的状态为”success“：
<img width="1287" alt="截屏2022-05-17 下午5 07 39" src="https://user-images.githubusercontent.com/34637801/168774533-9d86173f-1f76-4fb4-a235-0b7c5ae60ccf.png">

场景报告的详情中包含断言失败的接口case：
<img width="1086" alt="截屏2022-05-17 下午5 06 37" src="https://user-images.githubusercontent.com/34637801/168774313-5dd95cfa-5173-4bde-af85-ba8dec77a392.png">

### 重现步骤

1.环境：MeterSphere的配置文件 /opt/metersphere/.env的 image_tag设置为1.19 ,然后执行msctl reload;
2.创建一个场景包含一个执行正常的接口case和一个断言失败的接口case；
3.创建一个测试计划关联该场景；
4.启动该测试计划的定时任务，设置执行频率为5分钟；
5.可以看到部分的场景报告为”success“状态，大部分的报告为”error“状态；

### 期待的正确结果

1.期望所有的场景报告的状态都为”error“；

**Comment by youliyuan-fit2cloud** [comment]
升级新版本后没有复现该问题，关闭
