### ISSUE TITLE
[BUG]接口请求body为json格式，当json的value值是数组里嵌套链表时，填入之后打开JSON-SCHEMA发现value为空，点击预览，value也为空。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#13655]
### MeterSphere 版本

1.20.1

### 使用外置数据库

否

### 问题描述

接口请求body为json格式，当json的value值是数组里嵌套链表时，填入之后打开JSON-SCHEMA发现value为空，点击预览，value也为空。如下图：
![11](https://user-images.githubusercontent.com/104960608/168750874-977f5f08-7abf-4b97-85ea-e69e4117d29c.png)
![22](https://user-images.githubusercontent.com/104960608/168750927-26a5331b-f629-4e6c-b18a-30ca11adb9d7.png)

### 重现步骤

请求参数-请求体-json
填写json数据后，放开JSON-SCHEMA，模版/预览里数据

**Comment by zrfit** [comment]
您好，最新版本未复现该问题，是有特定操作顺序吗？ 或尝试升级后验证。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/168782776-2f860d16-86c3-4154-a22a-1e41616a79cf.png">
