### ISSUE TITLE
[MeterSphere Log]:从非LTS版本升级到LTS版本后，后续将只能升级新的LTS版本，无法再自动升级到非LTS版本

### ISSUE THREAD

**Issue by astroxing** [metersphere/metersphere#13656]
### 请描述您的问题

一键安装遇到这个问题，请问怎么解决

**Comment by weifengyang** [comment]
这个提示不用管了

**Comment by astroxing** [comment]
> 这个提示不用管了

但是这个会导致我没有完成安装，控制台如下：

安装目录为 /opt/metersphere, 开始进行安装
[MeterSphere Log]: 从非LTS版本升级到LTS版本后，后续将只能升级新的LTS版本，无法再自动升级到非LTS版本 
退出安装...

**Comment by astroxing** [comment]
改为手动安装了，成功了
