### ISSUE TITLE
[BUG]自动化场景中对接口的覆盖率，统计不准确

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#13667]
### MeterSphere 版本

1.19.3

### 使用外置数据库

是

### 问题描述

场景用例里面的覆盖率算的不对，总覆盖率是33.6，接口用例对应的是13.3，那场景覆盖的至少也要20.3吧，但是页面显示的只有5.3.
![image](https://user-images.githubusercontent.com/100331967/168790068-27b7fb05-40ab-40bb-844f-68e74f63e18f.png)

### 重现步骤

场景用例里面的覆盖率算的不对，总覆盖率是33.6，接口用例对应的是13.3，那场景覆盖的至少也要20.3吧，但是页面显示的只有5.3.

**Comment by zrfit** [comment]
您好，接口统计中的接口覆盖率并完全直等于接口用例数量中的覆盖率和场景用例数量中的覆盖率之和。
1、接口数量统计中的接口覆盖率=存在用例或被场景步骤包含的接口/接口总数*100%
2、接口用例数量统计中的接口覆盖率=有用例的接口/接口总数*100%
3、场景用例数量统计中的接口覆盖率=被场景步骤包含的接口/接口总数*100%
所以确认下3被场景步骤中包含的接口数量实际有多少？不同场景步骤包含了相同的接口-会去重。

**Comment by zrf87** [comment]
这就是我后来提的优化，没有办法直观的看到现在场景步骤中具体用到了哪些接口。
我理解接口数量统计中的接口覆盖率，计算时也是去过重的，所以单纯从计算角度看
②接口用例+③场景用例 应该大于等于 ①总
另外截图上场景用例有26个，去掉重复的接口，差不多也有20个以上不同接口。

**Comment by zrfit** [comment]
您好，按这种计算逻辑①<②+③是一种情况，但是我这边没有复现该问题，覆盖率统计是正确的，所以我让您确认下26个场景下去重后的接口是有多少个？ 或者新建项目再看下是否也能复现该问题，我们好近一步去跟进。
