### ISSUE TITLE
[BUG]新增快捷调试提示报错

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#1366]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题
新增快捷调试提示报错，但依然添加成功了
**Bug 重现步骤**
1.  接口测试-接口定义 HTTP  快捷调试
2.  填写完必填参数后点击保存报错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
填写完必填参数后点击保存不报错
**截图**
如果有截图，请附上截图.
![111](https://user-images.githubusercontent.com/29306248/106722634-297e9100-6641-11eb-83a4-fdc6ad157f77.jpg)

**Comment by zhao103804** [comment]
![111](https://user-images.githubusercontent.com/29306248/106722704-3a2f0700-6641-11eb-9b6a-21c2e2ae03d5.jpg)

**Comment by wangzhen-fit2cloud** [comment]
你好，快捷调试页面没有保存按钮，具体是点击哪里报错呢？
