### ISSUE TITLE
[BUG]POST上传接口请求体中以binary传输json文件后，服务端无法解析json文件内容

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#13668]
### 联系方式

844177611@qq.com

### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

一个上传接口（POST方法）使用postman和jmeter上传后，json文件内容均可被服务解析，但同样的接口导入平台后，上传的json文件内容无法被解析（com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value at [Source: (byte[])"）

### 重现步骤

1. 一个上传接口（POST方法）
request header: content-type=application/json
request body: binary, json文件
2. 使用postman上传，查看服务的解析结果
![image](https://user-images.githubusercontent.com/57786489/168790533-20cfbff1-bbaf-4499-8108-6a1018830782.png)
![image](https://user-images.githubusercontent.com/57786489/168790564-b03c94f1-9637-4073-8131-1cde8c429907.png)

3. 接口导入平台，进行同样的操作后，服务报错
![image](https://user-images.githubusercontent.com/57786489/168790650-a079fc4e-2a31-4fac-bbe9-0ddc98e73605.png)
![image](https://user-images.githubusercontent.com/57786489/168790692-1a89e0d2-21e3-4d5b-907f-9f2c75e15095.png)

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value at [Source: (byte[])"

### 期待的正确结果

同样的接口使用平台上传成功后，能被服务正确解析

### 相关日志输出

```shell
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value at [Source: (byte[])"
```

**Comment by zrfit** [comment]
您好，方便上传下json文件吗？

**Comment by meifeifei** [comment]
> 您好，方便上传下json文件吗？和jmeter运行的截图。
因为不支持上传json，就把json内容贴进来了
{
	"id": "nYeldssxEemBrBheDxK4cA",
	"type": "DELETE_TILES",
	"p_id": 103,
	"deletions": [
		557042475,
		557017790
	]
}
![image](https://user-images.githubusercontent.com/57786489/169271156-0f6e502b-401f-41a6-ad4e-6c1f9e88734c.png)

**Comment by zrfit** [comment]
您好，最新版本未复现该问题呢，建议升级到最新版本尝试，或者将您的api导出我们再尝试看能复现不。
