### ISSUE TITLE
[BUG]测试用例中的变更记录没有按时间排序

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#13672]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v19.1

### 使用外置数据库

否

### 问题描述

测试用例中的变更记录没有按时间排序

### 重现步骤

1，点击进入任意一个测试用例
2，点击变更记录
3，发现变更记录没有按照时间排序
![image](https://user-images.githubusercontent.com/67257251/168797318-a07f0324-51e0-4db3-8433-65395da46af6.png)

### 期待的正确结果

用例变更的记录可以按照时间进行排序

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本1.20.2-lts 中没有复现，升级一下~
<img width="950" alt="image" src="https://user-images.githubusercontent.com/54612864/168802320-085e3f8e-d48b-4541-a0cd-77524d28f202.png">
