### ISSUE TITLE
[BUG]【接口测试-接口定义】执行用例时，按照用例等级排序，从高到低（实际按照从 P3 -> P2 ->P1 这样排的）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1367]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 **版本: v1.7-f84f5fbb**

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  进入 接口测试-接口定义 模块
2. 执行用例时，按照用例等级排序，从高到低
3. 
4. 

**期待的正确结果**
从 P1 -> P2 ->P3 这样排

实际结果：
从 P3 -> P2 ->P1 这样排的

**截图**
![image](https://user-images.githubusercontent.com/11580681/106724725-867b4680-6643-11eb-8a97-69b7add82d32.png)

**Comment by fit2-zhao** [comment]
1.7.2 修复
