### ISSUE TITLE
[BUG]测试用例附件丢失-必现

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#13671]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v19.1

### 使用外置数据库

否

### 问题描述

1，测试用例中上传的附件，下次打开发现附件没有了

### 重现步骤

1，打开一个测试用例，点击附件
2，上传一个txt或者其他类型的附件
3，后点击保存后，关闭用例编辑
4，重新打开该用例(不要点击 附件按钮)，随便改一个内容(例如责任人)或者什么都不改，点击保存
5，关闭用例编辑，再次打开用例，点击附件按钮
6，发现附件出现丢失
![image](https://user-images.githubusercontent.com/67257251/168796471-86c3228a-0655-4844-967a-bf2bcae60e36.png)
![image](https://user-images.githubusercontent.com/67257251/168796821-00de09d2-f72d-4737-ae1d-595865f79f7c.png)

### 期待的正确结果

不应该出现附件丢失的情况

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
