### ISSUE TITLE
[BUG] UI自动化场景中步骤名称无法修改

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#13679]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.2-LTS

### 使用外置数据库

否

### 问题描述

创建或者编辑UI自动化场景，里面的场景步骤名称无法修改或者重命名

### 重现步骤

1、创建或者修改UI自动化场景
2、打开场景步骤
3、选择其中某些步骤进行修改名称
4、此时步骤名称变为空白，无法输入

### 附加信息

修改之前：
<img width="749" alt="image" src="https://user-images.githubusercontent.com/32027713/168937837-f53a234b-872d-41d9-a32a-465946a68a57.png">

点击“修改”按钮之后，无法修改

<img width="765" alt="image" src="https://user-images.githubusercontent.com/32027713/168937916-bb087858-9739-4c58-a5bb-f2378d6b183e.png">

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是必现的吗？具体操作步骤是什么呢

**Comment by zyyfit** [comment]
用户反馈1.20.3没复现了，关掉了
