### ISSUE TITLE
[BUG]上传文件接口无反应

### ISSUE THREAD

**Issue by windy0122** [metersphere/metersphere#13673]
### 请描述您的问题

上传文件，form-data类型，选择file文件上传excel，点击运行，没有请求数据

![image](https://user-images.githubusercontent.com/42708033/168800831-1f8a0662-00dc-4b0e-a541-9c09ffa4be65.png)

**Comment by windy0122** [comment]
版本v1.19.0-1727

**Comment by zrfit** [comment]
您好，最新版本未复现该问题，可升级后尝试，是否方便发下xlsx文件？
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/99731894/168946200-39185842-1b12-4ab2-83a0-ac16d6ed7c9d.png">

**Comment by windy0122** [comment]
没问题了，原来的接口是用jmeter写的，然后导入到平台上的，就出现了我这种问题，后来我自己新建了一个一模一样的接口，就没问题了
