### ISSUE TITLE
[BUG] UI测试--在选择下拉框操作--子选择的值失败

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13670]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

版本:   v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

目录：UI测试--UI自动化--新建场景--下拉框操作--子选项
描述：
1.子选择，“选项Option”，值=下拉框里面内容，或者用xpath都不行
2.子选择，“值(value)”，值=下拉框里面内容，或者用xpath都不行
**如果不是这操作，请问怎么操作才能得到下拉框子选项

### 重现步骤

![image](https://user-images.githubusercontent.com/15188833/168792138-af32a754-faf4-44ad-9858-1b399886f8e5.png)
![image](https://user-images.githubusercontent.com/15188833/168792509-68a07804-3b7a-49e7-b6a5-68a7902f4259.png)

**Comment by zyyfit** [comment]
这个下拉框是针对 select 元素以及 它下面的 option选项使用的，ms系统不是用的原生js，直接用鼠标移动-移入元素，和鼠标点击这两个命令就可以了
