### ISSUE TITLE
[FEATURE]建议在项目环境-通用配置中增加变量管理功能

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#13686]
### MeterSphere 版本

v1.20.2-lts

### 请描述您的需求或者改进建议

建议在项目环境-通用配置中增加变量管理功能：例如：变量都在哪些具体位置使用，点击变量可以定位至使用位置，如多个位置使用则提供选择位置跳转；这样便于将冗余变量删除以节省空间。

### 请描述你建议的实现方案

建议在项目环境-通用配置中增加变量管理功能：例如：变量都在哪些具体位置使用，点击变量可以定位至使用位置，如多个位置使用则提供选择位置跳转；这样便于将冗余变量删除以节省空间。

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/186129158-ebcf49e9-8a82-498f-adbb-ebebc22aec53.png)
![image](https://user-images.githubusercontent.com/82088551/186129185-545d308e-f90a-4fdf-b9b8-76224915eff6.png)
友商的场景上下文变量管理功能，仅供参考

另外场景中的变量 在from表单使用时可自动提示，方便记忆使用
