### ISSUE TITLE
[BUG]通过metersphere平台创建缺陷，同步至禅道缺陷之后，meterphere点击【同步缺陷】，禅道缺陷同步失败

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#13685]
### 联系方式

企业微信：MeterSphere 交流群35；李彬

### MeterSphere 版本

v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

禅道缺陷的图片同步metersphere失败

### 重现步骤

1、新增或者编辑缺陷，上传图片正常同步到禅道
2、在Metersphere平台点击【同步缺陷】按钮，同步禅道数据到Metersphere，图片就是错误的
<img width="687" alt="0fa1cbe46d72b3df5fdb9027a58e0218" src="https://user-images.githubusercontent.com/102306978/168944364-f92db1dc-e98e-4fa5-a6be-fff9e3ed9f2c.png">

![禅道](https://user-images.githubusercontent.com/102306978/168946714-c8bb6df0-0eca-42f4-8874-6b51f113b41d.png)

### 期待的正确结果

metersphere和禅道图片展示正确

**Comment by youliyuan-fit2cloud** [comment]
你好，使用的开源版MeterSphere 吗？开源版同步缺陷 不可用。。。你咋同步过来的额 ？

**Comment by hongnini** [comment]
> 你好，使用的开源版MeterSphere 吗？开源版同步缺陷 不可用。。。你咋同步过来的额 ？

是开源版。我是在metersphere平台创建的缺陷同步到禅道的，并不是禅道创建的缺陷同步至metersphere。

**Comment by youliyuan-fit2cloud** [comment]
禅道是什么版本？企业版？专业版？

**Comment by hongnini** [comment]
> 禅道是什么版本？企业版？专业版？

专业版
[Designed by 艾体验](https://api.zentao.net/goto.php?item=aiux)   [ 禅道12.5.2](https://www.zentao.net/)

**Comment by youliyuan-fit2cloud** [comment]
开源版，不支持从禅道同步到MeterSphere，所以你是在禅道系统修改了图片，然后MS这边同步缺陷吧？这样开源版不支持的，即使是MS创建的缺陷

**Comment by youliyuan-fit2cloud** [comment]
你这个是双向同步

**Comment by hongnini** [comment]
> 开源版，不支持从禅道同步到MeterSphere，所以你是在禅道系统修改了图片，然后MS这边同步缺陷吧？这样开源版不支持的，即使是MS创建的缺陷

并没有在禅道这边修改图片。
MS创建缺陷时添加的图片，禅道处只是更新了状态，通过点击ms同步缺陷按钮

按照你说的不支持双向同步，那就是禅道除了状态其他内容都不应该同步的。但是目前实际结果是把禅道的content也同步过来了，这就不对了

<img width="1362" alt="企业微信20220524-113626@2x" src="https://user-images.githubusercontent.com/102306978/169944524-1b1b5640-fcbd-477c-ae6f-aa2721152f7d.png">

<img width="603" alt="企业微信20220524-113653@2x" src="https://user-images.githubusercontent.com/102306978/169944892-15cb8d7e-0d35-43a5-8eb8-b7ef95a6cdba.png">

<img width="832" alt="企业微信20220524-113952@2x" src="https://user-images.githubusercontent.com/102306978/169944927-4dfe43a5-fc25-4fef-b30d-eca79199ee94.png">

<img width="1334" alt="企业微信20220524-114126@2x" src="https://user-images.githubusercontent.com/102306978/169944958-56d14584-6fb0-49f5-8657-8bf64bcf2b49.png">

<img width="866" alt="企业微信20220524-114222@2x" src="https://user-images.githubusercontent.com/102306978/169944981-8fadc8e6-9840-41a0-93ca-9594456a44f6.png">

**Comment by youliyuan-fit2cloud** [comment]
收到，已复现该问题，我们后续版本修复！

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts版本中已修复
