### ISSUE TITLE
[BUG] 【接口测试-接口自动化】csv 场景变量使用时，放入循环迭代器中，第一次循环取到了第二条数据值（预期：取第一条数据值）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1368]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？  v1.7-f84f5fbb

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  进入 接口测试-接口自动化
2. csv 场景变量使用时，放入循环迭代器中
3. 设置循环迭代器执行 3 次
4. 运行

**期待的正确结果**
正确情况下应该是什么样的？
预期：取第一条数据值
实际：第一次循环取到了第二条数据值

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/106727996-00f99580-6647-11eb-8253-c17050c36cc4.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们产品应该已经跟你沟通过了，这个 issue 我先关掉了。
