### ISSUE TITLE
[BUG] 《我的工作台-我的仪表盘》UI 优化

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#13695]
### 联系方式

lsj

### MeterSphere 版本

1.20.2-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/41712985/168961761-d2cbef06-7d28-4f93-9225-56001f1a6a4e.png)

### 重现步骤

见截图。

### 期待的正确结果

各个模块中的首页中，各个显示框的高度尽量保持一致。

**Comment by maninhill** [comment]
目前的几个模块中，接口测试的首页布局是最合理和美观的，其他模块尽快跟接口测试保持一致。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts 修改了一版，请看下是否满足您的预期~
