### ISSUE TITLE
[BUG]MQTT sub到的响应体为JSON时，无法使用JSONPath进行参数提取

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#13699]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.2-LTS     MQTT插件版本为：mqtt-v1.2.4

### 使用外置数据库

否

### 问题描述

MQTT sub到的响应体为JSON时，无法使用JSONPath进行参数提取
显示为：“请先执行调试获取响应结果”

### 重现步骤

1、创建MQTT连接，PUB   ,SUB，DISCONNECT

2、将PUB的请求内容设置为JSON

3、sub接收到消息之后添加后置操作

4、后置操作为参数提取，点击“JSONPath”提取，即可复现

### 附加信息

显示截图：
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/32027713/168974564-df09ad55-d02d-4885-9597-82089fd34052.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts版本中已修复
