### ISSUE TITLE
如何把接口自动化 发布成API

### ISSUE THREAD

**Issue by chensongmol** [metersphere/metersphere#13696]
### 请描述您的问题

如何把接口自动化编排的接口 发布成API给第三方系统调用

**Comment by Hyyfit** [comment]
调用我们平台执行接口自动化的api就可以了，具体可以看一下swagger文档或者参考浏览器的参数调试。

**Comment by chensongmol** [comment]
> 调用我们平台执行接口自动化的api就可以了，具体可以看一下swagger文档或者参考浏览器的参数调试。

 调用接口：api-automation-controller/runDebug ，但是如何获取最后一个接口的返回值？

**Comment by Hyyfit** [comment]
您好，我们这个是异步执行，没有回调的机制，只能一段时间后，轮询报告里的结果。
