### ISSUE TITLE
[BUG]接口自动化场景，特定json请求体 json-schema异常问题，可稳定复现

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13700]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

接口自动化场景，特定用户碰到的特定json请求体异常问题，可稳定复现，详情参见重现步骤

### 重现步骤

1. 下载下面的场景导出文件
链接: https://pan.baidu.com/s/1CGRB8ZbIW9tQ5CT9uGEx2Q 提取码: gefg 
2. 在接口自动化，场景列表，导入该场景文件
3. 导入后打开场景
4. 该场景只有一个步骤，复制该步骤
![1652855929(1)](https://user-images.githubusercontent.com/76033005/168973888-6ccbfa21-1bce-47d9-9e2a-4c26dc5349bf.png)
5. 点击新复制后的步骤，点请求体，可以看到是json请求体内容
6. 然后用下面这段内容替换请求体里面的内容。（我用https://www.bejson.com/校验过，下面内容是正确的JSON格式）
   实际请求内容 请下载 链接: https://pan.baidu.com/s/1wCvhdd6P9FqBCoJg4gk3DA 提取码: ih4x 

8. 点击json schema，就能看到问题了，不勾选json-schema，发现内容变了。

### 期待的正确结果

目前看应该是json-schema没有正确格式化 新替换的内容

### 附加信息

重要潜在客户反馈的问题！

**Comment by 35plus** [comment]
{
	"channel": "tk",
	"userNo": "9d0a68a8025145f38df64851ea782afd",
	"uniqueNo": "",
	"extParams": "{\"planCode\":\"\"}"
}

奇怪，github把 \"  给存丢了
重现步骤里面的第6步，实际内容如下：
链接: https://pan.baidu.com/s/1wCvhdd6P9FqBCoJg4gk3DA 提取码: ih4x

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复
