### ISSUE TITLE
[BUG] 场景自动化，场景步骤，后置SQL，一个环境有多个数据源，选择一个数据源后，点击前置操作，再回到后置SQL，发现之前选的数据源变了

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13707]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

场景自动化，场景步骤，后置SQL，一个环境有多个数据源，选择一个数据源后，点击前置操作，然后再点击后置操作，再回到后置SQL，发现之前选的数据源变了。

这个问题东区两个客户这里都有碰到。 
在1.19.1,  1.20.2上都有

### 重现步骤

1.  一个环境下面建四五个数据源
2. 新建一个场景，添加一个http请求
3. 添加后置sql
4. 选择一个环境，选择一个数据源ecif
![1652858266(1)](https://user-images.githubusercontent.com/76033005/168980439-9b981def-be8d-430a-858d-ebcf6a2aaed2.png)

5. 然后点击前置操作，点击完成后，再点击后置操作，回到刚刚建的后置sql，点开，查看数据源，不是刚刚选择的。
![1652858458(1)](https://user-images.githubusercontent.com/76033005/168980769-df10c211-957c-433c-9a51-63b0391d5d10.png)

### 期待的正确结果

再次回到后置sql，应该看到的数据源是ecif

### 相关日志输出

```shell
这个是前端的问题
```

### 附加信息

另外一个潜在客户也碰到了完全类似的问题，该客户是 1.20.2.

**Comment by fangqiuhong** [comment]
> 没有复现，是偶发的吗？

这个问题，我1.19.1版本，前置SQL配置，也出现了

**Comment by 35plus** [comment]
瑞，这个问题是必现的，我可以 在客户的环境演示给你看看哈。

**Comment by youliyuan-fit2cloud** [comment]
请更新到1.20.3-lts~
