### ISSUE TITLE
[BUG]接口自动化测试带证书的接口，返回接口不稳定

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#13706]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

1、在环境配置证书，创建一个场景，选用这个该环境，点调试，有时候跑异常，有时候200，但是控制台显示没有加载到证书
2、个人理解就是证书存在问题，那我们执行多少次返回的结果都应该是一样的
3、qa环境可复现

### 重现步骤

1、配置带有证书的环境
<img width="930" alt="image" src="https://user-images.githubusercontent.com/72729206/168978451-e5a7479d-f237-4389-98f5-0ea351271e7f.png">
2、点击调试，提示异常
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/72729206/168978189-c26f313f-67cd-4137-b7d1-1ff7fc668fa3.png">
控制台日志
<img width="991" alt="image" src="https://user-images.githubusercontent.com/72729206/168978326-101c0b99-36cb-4206-aaaa-688ddd54b4f4.png">
3、在连续点几次调试，状态码就是200
<img width="966" alt="image" src="https://user-images.githubusercontent.com/72729206/168978612-aa1d4a04-d9e4-4f06-9302-d844f83e4313.png">
控制台日志，看起来证书没加载成功
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/72729206/168978707-780ebc64-69db-427a-86de-5f4d9c86a95f.png">

========================分界线====================

1、在场景列表刷新页面后点执行，异常
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/72729206/168979014-516839e9-697d-40c9-9cd2-88bce9d2c633.png">
2、关闭报告，重新点几次，成功
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/72729206/168979161-6f3f71d0-da12-47a2-85f5-f35f88d397ca.png">

### 期待的正确结果

无论执行多少次返回的结果都应该是一样的

**Comment by fit2cloud-yangxiaoyan** [comment]
经过多次测试发现，
1、导入多个证书，问题必现
2、导入一个，正常
3、导入一个文件有多个证书，不稳定

**Comment by zyyfit** [comment]
相关问题 
https://github.com/metersphere/metersphere/issues/9639

**Comment by zyyfit** [comment]
1.20.4已修复，请发版后验证
