### ISSUE TITLE
jmeter 内置方法优化，支持自定义脚本引用内置方法

### ISSUE THREAD

**Issue by xujiesh0510** [metersphere/metersphere#1370]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.1
**Bug 描述**
简要描述您碰到的问题

 
 
${__RandomString(22)}  乱码,  看了看 jemeter 官方文档，的确是可能出现乱码，能处理下么？
另外自定义脚本里面好像是没法引用这些函数的，很不方便，有任何解决办法么？比如出个java类 封装以下这些方法 

![image](https://user-images.githubusercontent.com/10271679/106733290-acf1af80-664c-11eb-9d8c-eb4dc33b8323.png)

另外自定义脚本里面好像是没法引用这些函数的，有任何替代的办法么？

**Comment by wangzhen-fit2cloud** [comment]
你好，在自定义脚本中是可以使用内置方法的，请问具体脚本内容是如何写的呢？
```
log.info("=====")
log.info("${__RandomString(22,abcdefghijklmn)}")
log.info("=====")
```
![image](https://user-images.githubusercontent.com/27671436/106835919-27fda900-66d3-11eb-882f-1fe9b652643b.png)
![image](https://user-images.githubusercontent.com/27671436/106835952-32b83e00-66d3-11eb-9a61-3d3df842550f.png)

**Comment by xujiesh0510** [comment]
学习了。感谢点拨，需要引用在 字符串里面
