### ISSUE TITLE
[BUG]项目环境-通用配置：删除变量后再次执行接口未重新生成变量值

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#13705]
### MeterSphere 版本

v1.20.2-lts

### 使用外置数据库

否

### 问题描述

项目环境-通用配置：删除变量后再次执行接口应重新生成变量值

### 重现步骤

1. 执行接口生成变量
2. 项目环境-通用配置：删除变量
3. 再次执行接口后查看项目环境-通用配置的变量

### 期待的正确结果

项目环境-通用配置：删除变量后再次执行接口应重新生成变量值存储

**Comment by youliyuan-fit2cloud** [comment]
是不是在环境配置里面通用配置-删除变量值吧？
请上传截图吧，这样比较好理解，感谢！

**Comment by kusotest** [comment]
项目环境--通用配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]项目环境-通用配置：删除变量后再次执行接口未重新生成变量值 (Issue #13705)





 
是不是在环境配置里面通用配置-删除变量值吧？
 请上传截图吧，这样比较好理解，感谢！

**Comment by youliyuan-fit2cloud** [comment]
> 项目环境--通用配置
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2022年5月18日(星期三) 下午5:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]项目环境-通用配置：删除变量后再次执行接口未重新生成变量值 (Issue #13705) 是不是在环境配置里面通用配置-删除变量值吧？ 请上传截图吧，这样比较好理解，感谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

（~~）？
