### ISSUE TITLE
[FEATURE]希望测试用例执行的界面字段可以自定义

### ISSUE THREAD

**Issue by barnett8622** [metersphere/metersphere#13719]
### MeterSphere 版本

v1.20.2-lts-b9564d5c

### 请描述您的需求或者改进建议

目前测试用例执行页面重点不突出,比如步骤和结果是最重点的,但确显示的最小, 右边的评论占了很大一块地方,但其实是最没用的,包括责任人等,希望这个界面可以自定义展示字段,或者评论那一块可以折叠不展示
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/105485809/169031033-1d69947c-a0ba-4272-bf3e-4bb0e7683ef3.png">

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
