### ISSUE TITLE
[FEATURE]提取参数的jsonpath提取可以增加对多个不同的路径的集合的支持

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#13713]
### MeterSphere 版本

v1.20.2

### 请描述您的需求或者改进建议

比如：
`
{
    "elements":[
            {
                  "firstName": "John",
                  "lastName" : "doe",
                  "age"      : 26,
                  "phoneNumbers": [
                          {
                            "type"  : "iPhone",
                            "number": "0123-4567-8888"
                          },
                          {
                            "type"  : "home",
                            "number": "0123-4567-8910"
                          }
                   ]
              },
            {
                  "firstName": "John1",
                  "lastName" : "doe1",
                  "age"      : 23,
                  "phoneNumbers": [
                          {
                            "type"  : "home",
                            "number": "0123-4567-8888"
                          },
                          {
                            "type"  : "home",
                            "number": "0123-4567-8910"
                          }
                   ]
              }
     ]
}
`
如果想要提取的信息只有 firstName和type为’home‘的phoneNumber
期望的结果是：提取出来elements中只有这两个字段，且只提取type为home的phoneNumbers所有的element：[
{
          "firstName": "John",
          "phoneNumbers": [
            {
              "type"  : "home",
              "number": "0123-4567-8910"
            }
          ]
},
...
]

那么就提取需要两条路径的集合，且允许其中的路径存在条件，可以列为以下方式，类似：
$['elements'][@.firstName, @.phoneNumbers[?(@.type == ’home‘)]]
或者类似[JsonMatch](https://github.com/sanity-io/go-jsonmatch)

### 请描述你建议的实现方案

[JsonMatch](https://github.com/sanity-io/go-jsonmatch)

**Comment by Hyyfit** [comment]
如果jsonpath不支持这样的提取，我们没有做额外的处理，也就不支持了。
如果需要用到这样的组合型数据，可以通过后置脚本的方式实现。
