### ISSUE TITLE
[BUG] 接口定义 新增一个接口点击保存后，服务器后台有空指针错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#1371]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.6.2版本

**Bug 描述**
1、接口--新建接口，添加必要信息后，点击保存
2、提示500错误，查看日志发现有空指针

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/106738834-65baed00-6653-11eb-8408-5b30840c4483.png)
![image](https://user-images.githubusercontent.com/78218624/106738947-884d0600-6653-11eb-8bbd-c4b1e46b0fe8.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请升级下最新版本。
