### ISSUE TITLE
[BUG] API CASE或者自动化场景请求体JSON-SCHEMA打开-关闭导致编辑好的请求内容发生变化

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#13712]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.2-LTS

### 使用外置数据库

否

### 问题描述

API 的CASE或者自动化场景请求体JSON-SCHEMA打开-关闭，导致原来编辑好的JSON请求体被还原为API定义的里面的请求体内容，调试出错。

### 重现步骤

1、创建一个POST请求，请求体内定义内容如下（示例）然后保存：
{
    "orderType": 0,
    "supplierId": 0,
    "internationalCode": "",
    "customsClearanceNo": "",
    "orderStatus": 0,
    "refundStatus": 0,
    "openPage": false,
    "purchaseOrderNo": "",
    "current": 0,
    "orderTimeEnd": 0,
    "supplierName": "",
    "goodsBusinessCommodityCode": "",
    "logisticsOrderId": "",
    "batchNo": "",
    "receiverName": "",
    "merchantNum": "",
    "orderTimeStart": 0,
    "receiverMobile": "",
    "start": 0,
    "userId": 0,
    "purchaseOrderNoList": [
        ""
    ],
    "size": 0,
    "trackingNo": "",
    "exportType": "",
    "platformOrderNo": ""
}

2、基于步骤一的API创建一个新的CASE,点击请求体，将下述内容替换到请求体，然后保存：
{
    "size": 10,
    "current": 1,
    "purchaseOrderNo": "PO1000000068106",
    "orderTimeStart": 1650211200000,
    "orderTimeEnd": 1652889599470
}

3、打开JSON-SCHEMA，发现被替换的请求体又变成API定义的内容了

4、再关闭JSON_SCHEMA，则请求体显示的内容为API定义的中的请求体

### 附加信息

API内容：
<img width="974" alt="image" src="https://user-images.githubusercontent.com/32027713/169002408-53af80cc-1e9a-445b-b36b-a7f5d7314779.png">

CASE中定义请求体的内容：
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/32027713/169002701-86121ea5-eda3-4a73-9ae5-db7a5d904092.png">

打开SCHEMA:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/32027713/169002856-9bf4a10c-b6b5-4022-b6e3-80f7f034e9a4.png">

关闭SCHEMA:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/32027713/169002978-53d644a8-c031-40f0-b9d2-1a8edd45af00.png">

**Comment by zrfit** [comment]
v1.20.4-lts已修复。
