### ISSUE TITLE
[BUG]性能测试一个任务多个报告，历史的报告下载的也是最新的 jmx 执行文件 

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#13720]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

性能测试一个任务多个报告，历史的报告下载的也是最新的 jmx 执行文件 

### 重现步骤

1、创建一个性能测试，传入一个脚本
<img width="982" alt="image" src="https://user-images.githubusercontent.com/72729206/169035623-ecc42e2b-7360-4932-b329-c22892b56b56.png">
2、执行后，下载执行文件，打开jmx
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/72729206/169035965-c7b31370-6142-496d-96d4-70df13fcbd69.png">
3、重新修改该测试，换一个脚本
<img width="625" alt="image" src="https://user-images.githubusercontent.com/72729206/169036162-cff3facc-f0c4-45b0-b73c-136f350d4b22.png">
4、执行后，有两个报告
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/72729206/169036286-97211574-dbf8-4848-b678-69447ed2db05.png">
5、下载第一个报告的执行文件，打开jmx
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/72729206/169036402-a0c2b800-0250-4df0-8f4c-d2b4f9cb4f37.png">
6、下载第二个报告的执行文件，打开jmx，发现和第一个一样
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/72729206/169036675-96408c3c-6c9e-4135-b9ee-e015815bf51e.png">

### 期待的正确结果

根据当前的报告下载对应的执行文件

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
