### ISSUE TITLE
[BUG]调试接口定义，出现卡死的现象（页面一直loading，不是websocket问题，不必现，出现概率很高）

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#13725]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.2-lts

### 使用外置数据库

否

### 问题描述

1.创建一个访问百度的接口，点击调试，出现卡死现象
![7c5e926715fe7ee12d0b0d85972662a](https://user-images.githubusercontent.com/30038088/169088224-e019ebd0-bf2b-43e5-b8c4-4c7d8ce9ccf4.png)

2.执行成功的ms-jmeter-run-log日志
![49770e7fbee6858efdcc5feeec005c7](https://user-images.githubusercontent.com/30038088/169088237-f82d9797-fc07-4185-becb-cd7eefad17a4.png)

3.执行失败的ms-jmeter-run-log日志
![42077e5acd763edb4269a6a27988038](https://user-images.githubusercontent.com/30038088/169088252-d2a24651-45bc-4d31-a7ff-8c0c2ce88abb.png)

执行成功的和失败的 ms-jmeter-run-log日志 一模一样 

### 重现步骤

创建一个访问百度的接口，点击调试，重复多试几次（3-5次），会出现卡死的现象，

**Comment by shenkaibo** [comment]
> 在 MeterSphere Cloud版 上可以类似重现吗？
也有这个问题，试了几次 都是卡死，一直loading。

**Comment by zyyfit** [comment]
1.20.3已修复，请等发布后验收
