### ISSUE TITLE
[BUG]UI自动化中，更改了元素库中元素所属的模块位置，在场景中进行后置操作，断言元素信息时，元素找不到

### ISSUE THREAD

**Issue by Eric-Hyiboo** [metersphere/metersphere#13724]
### 联系方式

yibo.huang@fit2cloud.com

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

UI自动化中，更改了元素库中元素所属的模块位置，在场景中进行后置操作，断言元素信息时，元素找不到；但元素位置不变，修改了名称，还是可以找到元素。

### 重现步骤

UI自动化，在场景中操断言操作，“更改元素库中元素所属的模块位置”，“不改变元素位置，修改元素名称“查看在场景中操作，是否可以找到元素位置。

### 期待的正确结果

以上两种步骤，都能找到相关元素

### 附加信息

![WechatIMG1285](https://user-images.githubusercontent.com/83943743/169059730-dbb34a28-4e84-403f-938e-51ffa0cb0daa.jpeg)

**Comment by ltfit** [comment]
感谢反馈 下个版本修复下

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts中已修复~
