### ISSUE TITLE
[BUG]测试跟踪测试计划接口用例失败用例判断异常

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#13728]
### MeterSphere 版本

20.2

### 使用外置数据库

否

### 问题描述

全局断言脚本不准确

### 重现步骤

测试跟踪--测试计划--查看测试报告--失败脚本
1、接口返回正常、断言正常，但是显示却是失败用例（见图）
全局断言脚本如下

`import org.json.*;

//获取上一个请求的返回
String jsonString = prev.getResponseDataAsString();
JSONObject responseJson = new JSONObject(jsonString);

String fbpcontent = responseJson.getString("message");

value = fbpcontent;
//result = value.contains("成功");
result = value.contains("成功")||value.contains("已下发");
if (!result){
    
	msg = "assertion [" + value + " contains '成功']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
// else if
}`

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/169181047-8e48a1f0-ad05-41c7-afe8-7e846334a80e.png)
断言
![image](https://user-images.githubusercontent.com/19423100/169181102-7b7e8544-485a-4764-b401-67e089597bb4.png)

**Comment by legend818** [comment]
我找到问题不一致了，这个是接口测试-case页面的历史执行记录，如果是这个结果那么失败是正确的，但是报告的是有问题的
![image](https://user-images.githubusercontent.com/19423100/169200821-f1ef3bf3-ab74-44b9-be17-013f6808e2ce.png)

**Comment by legend818** [comment]
看我的备注：  这个是定时任务触发的，我的备注贴图上面显示2022-05-18 20：00：00 定时任务 error  这个是在接口视图的-case 历史记录当中的。 但是在测试跟踪--测试计划报告中显示失败，但是断言等都是成功的，这个与这里是矛盾的。

**Comment by legend818** [comment]
看半天没有回复：
1、测试跟踪--测试计划--新增接口用例（这些用例我加了很久了）--设置定时任务晚上20点执行
2、第二天到测试跟踪--测试计划--报告--查看失败用例，发现接口返回正确，断言正确（采取全局脚本断言，上面已经发了）
    这里就不对了，都正确了，怎么还是失败

自己动手分析问题：于是，我到接口测试-case下执行该失败用例，成功。查看接口返回正确、断言正确，接口正常。但是在这里有一个该case的历史执行情况，发现改接口昨晚20：00：00的定时任务是error，发现接口返回错误，断言错误。那么这不就找到问题了。
分析结果：

说明接口应该是真的失败了，那说明测试跟踪--测试计划--报告--查看失败用例的接口返回和断言有问题，因为两边不一致了

**Comment by zyyfit** [comment]
我按照你的描述，没有复现你这个问题，我的步骤是这样的，你看看跟你的操作有没有差异，然后你也看你一下你这个问题能不能稳定复现
1、先用定时任务执行了测试计划，结果是失败的，然后查看测试计划报告，是正常的，结果显示失败，接口详情也是失败，断言也是失败
2、然后去接口测试模块，手动执行了这个接口case，让这个接口case的结果是成功的，查看接口模块的case执行结果，正常
3、返回测试跟踪模块，查看测试计划报告里的接口case执行结果，还是失败的，执行详情也是失败的，没有变成成功

**Comment by legend818** [comment]
1、测试跟踪--测试计划--接口-case我加了900多，每天晚上20：00定时执行，这个出现异常的**接口不是固定**的
2、测试跟踪--测试计划--报告--错误  下图，这个异常情况，应该是问题。失败接口返回和断言都提示正常，肯定矛盾
![image](https://user-images.githubusercontent.com/19423100/169725015-40c2dd04-8e74-4060-a3f8-de23727e257a.png)
![image](https://user-images.githubusercontent.com/19423100/169725061-89738819-304f-45e8-9c50-2c69f1e4b4a3.png)
3、为了定位这个问题，协助咱们来分析【其实从这一点你们都可以忽略，这个是我来协助定位问题的】
我找到一个异常的接口，在测试接口--case的执行历史来分析，不管是手动执行、还是定时执行这里有记录（对吧）
![image](https://user-images.githubusercontent.com/19423100/169725168-25006d82-74c6-4e55-b3fd-c045fcd93835.png)
这里显示断言失败
![image](https://user-images.githubusercontent.com/19423100/169725260-178d7200-0a66-4211-94d6-b7a00eef2041.png)
返回数据异常
![image](https://user-images.githubusercontent.com/19423100/169725387-f0039179-fa7b-411d-9591-7cee89fc37a2.png)

通过上面执行的历史，我判断历史记录是正确的，然后就是测试跟踪--测试计划--报告-失败哪里异常，因为两边不一致。我建议测试人员找开发看一下

**Comment by legend818** [comment]
就是说我不需要去手动执行，我主要到执行历史去找到20：00定时执行的执行记录。你没有出现，是不是因为数据量的问题，我每天接近1000的接口定时执行

**Comment by legend818** [comment]
我觉得研发是不是可以在某个版本加个日志输出，我配合你们将定位的日志反馈给你们

**Comment by zyyfit** [comment]
> 我觉得研发是不是可以在某个版本加个日志输出，我配合你们将定位的日志反馈给你们

要不您先在用户群里联系一下我们的工作人员吧

**Comment by legend818** [comment]
升级到1.20.4 好了

**Comment by allinone-1** [comment]
> 
请问demo环境无法访问了吗? 提示账户名密码错误，想体验下
