### ISSUE TITLE
[BUG]接口自动化，导入jmx文件， 导进去的场景所在的模块 与 导入选择的模块不一致

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [metersphere/metersphere#13723]
### 联系方式

内部郭灶鹏

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

 接口自动化导入jmx  文件， 无论导入的时候选择的是哪个 模块， 都只会去到和jmx脚本里面 和测试计划名同名  的模块下面

### 重现步骤

1、 jmx 脚本类似如下的结构
<img width="439" alt="1652879795(1)" src="https://user-images.githubusercontent.com/30264974/169047707-389fa389-1de1-4628-bb6d-e735531f0ce0.png">

2、 接口自动化，新建一个模块，导入jmx 文件到该模块下面 （这一步操作应该是正常的）
3、 再导入jmx 文件到未规划场景里面（或者其他模块下面），可以看到 场景没有成功导入到指定的模块下。

**Comment by fitcloud-zaopengguo** [comment]
可否考虑在导入的时候，  说明这个导入的逻辑

**Comment by zrfit** [comment]
v2.0版本导入逻辑统一优化。

**Comment by zrfit** [comment]
已排期，v2.0.0接口&接口自动化导入逻辑统一优化。

**Comment by fitcloud-zaopengguo** [comment]
感谢感谢

**Comment by zrfit** [comment]
v1.20.10-lts版本已优化，增加了同步覆盖场景模块逻辑。
<img width="695" alt="image" src="https://user-images.githubusercontent.com/99731894/179196516-351a4f73-828f-4a12-9e1b-f13a1bf28dee.png">
