### ISSUE TITLE
[BUG] 在接口自动化设置场景的场景变量时，【参数设置】对话框中，【变量】标签应显示为【JMeter函数】，这样概念上更清楚一些

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#13727]
### MeterSphere 版本

v1.20.2

### 使用外置数据库

否

### 问题描述

建议：
1. 【Mock数据】标签名 改为 【Mock函数】
2. 【变量】标签名 改为 【JMeter函数】
<img width="758" alt="Screen Shot 2022-05-19 at 1 12 07 AM" src="https://user-images.githubusercontent.com/9998431/169102909-b47edc06-d1fd-4c30-89da-e94856800277.png">

同时
在添加Mock接口时，【参数设置】对话框中，同样也把
1. 【Mock数据】标签名 改为 【Mock函数】
2. 【JMeter方法】标签名 改为 【JMeter函数】
<img width="710" alt="Screen Shot 2022-05-19 at 1 17 54 AM" src="https://user-images.githubusercontent.com/9998431/169103505-b5d596e0-6255-42a8-98ca-b239b0f80564.png">

把门户中参数设置对话框都检查统一修改一下，概念上统一显示明确一下

### 重现步骤

N/A

**Comment by zhangzhaox** [comment]
这个提议很好
