### ISSUE TITLE
[BUG] 断言写错了但是平台没有正常报错，只是执行状态一直没有改变（测试中）

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13726]
### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

![Uploading image.png…]()

### 重现步骤

断言里面写两个jsonpath使用分号隔开：
$..[?(@.fundCode=='Fund001')].applyTime;$..[?(@.fundCode=='Fund001')].itemId
点击调试

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把复现场景上传一下吗
