### ISSUE TITLE
[BUG]当接口的Query参数值为空时，接口URL为空

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#1373]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.1

**Bug 描述**
简要描述您碰到的问题
当接口的Query参数值为空时，场景中执行时，接口URL为空，提示“Non http response code: java.lang.NullPointerException”

**Bug 重现步骤**
1.  接口Query参数为非必填，且默认值为空
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/24548477/106767767-2e116c80-6676-11eb-885b-8a53e5b5d97d.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
