### ISSUE TITLE
[BUG]接口编辑页面--基础信息：模块搜索框输入字母无法搜索到结果（实际存在）

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#13738]
### MeterSphere 版本

v1.20.2-lts

### 使用外置数据库

否

### 问题描述

接口编辑页面--基础信息：模块搜索框输入字母无法搜索到结果（实际存在）

### 重现步骤

接口编辑页面--基础信息：模块搜索框输入字母无法搜索到结果（实际存在）

### 期待的正确结果

接口编辑页面--基础信息：模块搜索框输入字母可以搜索到已存在模块名称

### 附加信息

![image](https://user-images.githubusercontent.com/46745316/169198143-9676a2f3-f030-460b-951c-71c2b8051973.png)

**Comment by ltfit** [comment]
感谢反馈 下个版本修复下

**Comment by ltfit** [comment]
你好 v1.20.4-lts  此版本已解决该问题   升级下
