### ISSUE TITLE
[BUG]jenkins的metersphere插件漏洞

### ISSUE THREAD

**Issue by LizardYang** [metersphere/metersphere#13749]
### 联系方式

lizard@sztus.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

![7ba479c7df18549b77d466fdf006f32](https://user-images.githubusercontent.com/46311914/169228062-5f72a6ad-1c33-4bbb-a1af-bb31c9222b44.png)
![image](https://user-images.githubusercontent.com/46311914/169232239-58935011-6c1b-49d6-97f7-b5c7709248bc.png)

![d0b6afc52a01acbe7f213a9f53fcf16](https://user-images.githubusercontent.com/46311914/169232101-a16277ac-c4b2-4999-a813-f3d9147d1970.png)
此漏洞于2020年披露
Jenkins的metersphere插件有此漏洞，并导致我司jenkins被黑客攻击挖矿

### 重现步骤

麻烦尽快修复

**Comment by maninhill** [comment]
感谢反馈，我们抓紧修复。

**Comment by luty2018** [comment]
如果发现了新的漏洞请使用以下渠道反馈，感谢！
![image](https://user-images.githubusercontent.com/36292514/169251454-987d7f12-52d1-4c0d-9a91-1c5c1c08e939.png)
