### ISSUE TITLE
[BUG]在UI模块下进行项目切换时，页面刷新未显示在UI模块页面，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13750]
### MeterSphere 版本

1.20.2lts

### 使用外置数据库

否

### 问题描述

在UI模块下进行项目切换时，页面刷新未显示在UI模块页面，建议优化

### 重现步骤

1.在UI模块下进行项目切换时，查看切换后页面显示情况；

### 期待的正确结果

1.切换项目后，页面仍显示在UI模块页面；(实际显示至测试跟踪模块页面)

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/169238107-d3c2bb00-1ab7-46f2-bd80-f1bef83edffd.png)

**Comment by ltfit** [comment]
感谢反馈 下个版本优化下
