### ISSUE TITLE
[BUG]断言规则-"禁用"功能无法正常保存【必现】

### ISSUE THREAD

**Issue by MoseChen** [metersphere/metersphere#13753]
### 联系方式

864706976@qq.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

"禁用"某条断言规则后，保存自动化用例，重新打开后发现该断言规则仍处于"启用状态"

### 重现步骤

复现步骤：
1. 禁用断言规则后，保存场景自动化用例，提示保存成功；
2. 重新打开该自动化用例，进入断言规则列表页面，发现上一步被禁用的断言规则仍然处于"启用"状态，即"禁用"操作无法保存
![image](https://user-images.githubusercontent.com/11345202/169238314-e745d4ff-d34b-4032-a4de-124b47960074.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #12904
