### ISSUE TITLE
[BUG]dubbo测试失败，提示无provider

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#13759]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

本地启动了服务，在dubbo-admin可以看到消费者和提供者都存在，但是dubbo测试的时候报了没有提供者
![image](https://user-images.githubusercontent.com/58592452/169273125-235cbec8-db41-4a09-a6f5-a6d71811535c.png)
![image](https://user-images.githubusercontent.com/58592452/169273142-f197b61a-9007-440b-96a2-1742ddc752ee.png)
![image](https://user-images.githubusercontent.com/58592452/169273158-a710dea7-de0d-48a3-8742-d00e07e67e59.png)

### 重现步骤

本地启动了服务，在dubbo-admin可以看到消费者和提供者都存在，但是dubbo测试的时候报了没有提供者
![image](https://user-images.githubusercontent.com/58592452/169273125-235cbec8-db41-4a09-a6f5-a6d71811535c.png)
![image](https://user-images.githubusercontent.com/58592452/169273142-f197b61a-9007-440b-96a2-1742ddc752ee.png)
![image](https://user-images.githubusercontent.com/58592452/169273158-a710dea7-de0d-48a3-8742-d00e07e67e59.png)

**Comment by shenkaibo** [comment]
你好，jemter  有分组dubbo接口请求内容
可以在Consumer & Service里面的group 加sdb，且Registry Center 里面的group不需求加sdb

**Comment by juanmaocxy** [comment]
> 
我都没有加group，因为我在选择interface里加了group了，目前都试了还是不行。

**Comment by shenkaibo** [comment]
Consumer & Service里还是要加的，Registry Center 里 不用加

**Comment by juanmaocxy** [comment]
> Consumer & Service里还是要加的，Registry Center 里 不用加

已解决，group不应该加在interface里，要加在consumer&service。感谢
