### ISSUE TITLE
[BUG]缺陷管理汇总问题123

### ISSUE THREAD

**Issue by xiangxiang19872222222** [metersphere/metersphere#13760]
### 联系方式

15151812035

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

是

### 问题描述

缺陷管理汇总问题汇总：
1、经办人和报告人展示的是id，不是用户名称
2、创建的时候忘记添加图片，编辑的时候去添加，则无法再同步到jira
3、双向同步缺陷后，同步过来的历史bug创建人不能选登录metersphere账号，要能够同步jira中的创建人

### 重现步骤

1、
![image](https://user-images.githubusercontent.com/105849509/169281815-d4de64b7-b1bd-4824-9760-da59948555bc.png)
2、meterspere先创建一个bug，未添加图片同步成功至jira，然后编辑bug添加图片，再次点击同步，结果jira那边未同步成功图片
3、双向同步缺陷后，同步过来的历史bug创建人不能选登录metersphere账号，要能够同步jira中的创建人

### 期待的正确结果

1、metersphere中创建的bug，经办人和报告人应该是jira中的用户名称，而不是ID
2、编辑bug时，添加的图片能够再次同步到jira中去
3、双向同步缺陷时，创建人字段应该取jira中的创建人，而不是去metersphere登录账号

**Comment by ltfit** [comment]
感谢反馈  1 暂时没有复现    是有别的操作么
 2 3 问题下个版本修复

**Comment by ltfit** [comment]
这个第一个展示的是用户名 第二个多次保存会重复传附件，已修复 第三个就是这么设计的
