### ISSUE TITLE
[BUG]【接口测试>>接口自动化测试】场景变量里添加多个CVS时，预览页的信息没有及时清空。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#13766]
### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

[BUG]【接口测试>>接口自动化测试】场景变量里添加多个CVS时，预览页的信息没有及时清空。

### 重现步骤

1、选择【接口测试>>接口自动化测试】，打开自动化场景的【场景变量】，在这里需要添加多个CVS文件
2、添加第一个CVS文件，上传成功后，添加【预览】，能正常显示CVS文件，查看无误后，点击【确认】。CVS变量被添加到左侧变量列表中。
3、点击右上角【添加】继续添加CVS变量。CVS配置页签为空，等待添加文件。但是【预览】页签没有被刷新，依旧是上一个文件的内容。

### 期待的正确结果

添加第二个cvs文件是，清空预览页签的内容，否则会给操作者造成歧义。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/169315041-6828c164-8c40-4ad3-a21d-4aae31749c99.png)
![image](https://user-images.githubusercontent.com/78218624/169317691-35432036-31e8-46ce-b4d4-27600d451a17.png)

**Comment by zyyfit** [comment]
最新版没有复现这个问题，请升级试试

**Comment by huangxine** [comment]
目前版本是1.20.3，问题是必须的

**Comment by zyyfit** [comment]
1.20.4已修复，请等待版本发布后验证
