### ISSUE TITLE
[BUG]sql前置脚本自定义变量，取随机值失败

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#13765]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.2

### 使用外置数据库

是

### 问题描述

sql前置脚本自定义变量，取随机值，例如：@guid，在http请求中，获取的不是随机值，是“@guid”

### 重现步骤

1.sql前置脚本自定义变量，取随机值，例如：@guid
2.http请求中使用改变量，执行，响应请求内容中查看是否取值成功

### 期待的正确结果

能取到函数值

### 附加信息

![ee63a5b5eee39fb186fd67bee704504](https://user-images.githubusercontent.com/103627487/169305765-047cf9ef-2611-45a1-ae69-fc6aad426997.jpg)
![b4e567537c82c032e549c4d5b0bd3e8](https://user-images.githubusercontent.com/103627487/169305860-594670b6-f4a5-4f2d-a822-f3e697c0a4d6.jpg)
![2fa41f30a96930dfd2bdf06fa31b36e](https://user-images.githubusercontent.com/103627487/169305979-10f69aa5-5c09-46da-8e6f-f9d851ee5d01.jpg)

**Comment by zrfit** [comment]
v1.20.4-lts已修复
