### ISSUE TITLE
[BUG]手动方式新建JIRA字段，提交BUG可成功同步至JIRA，但在MS上点击同步缺陷后，部分JIRA同步过来的字段内容会被清空，重新编辑再保存也会报错

### ISSUE THREAD

**Issue by norry2022** [metersphere/metersphere#13768]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 使用外置数据库

是

### 问题描述

手动方式新建JIRA字段，提交BUG可成功同步至JIRA，但在MS上点击同步缺陷后，自建的字段内容会被清空，重新编辑再保存也会报错

### 重现步骤

前提：勾选”使用JIRA默认模板“
1. 在MS上提交缺陷，可成功同步至JIRA
2. 在MS上缺陷界面点击”同步缺陷“，缺陷列表界面的部分JIRA字段内容会被清空
3. 点击该缺陷进去后查看，自定义字段内容被清空，需要重新填写/选择再保存.

### 期待的正确结果

同步缺陷后，不应该清空字段内容；

**Comment by zrfit** [comment]
您好，最新版本未复现该问题，请升级到最新版本尝试。

**Comment by norry2022** [comment]
![同步后编辑](https://user-images.githubusercontent.com/105103343/169998679-6100308c-795f-4869-b181-a3fcdcc2098b.png)
![提交](https://user-images.githubusercontent.com/105103343/169998635-dd5fcef7-e122-4543-8146-1f98bf3323ee.png)

**Comment by norry2022** [comment]
![提交](https://user-images.githubusercontent.com/105103343/169998767-f401b6c8-8293-4c78-be29-1a1f15fde350.png)

编写BUG时候的截图

**Comment by norry2022** [comment]
![同步后编辑](https://user-images.githubusercontent.com/105103343/169998839-4205bb0f-05d0-4a09-a836-b2862ae29c74.png)

编写后保存，可以同步zhi至JIRA，再点击同步缺陷的按钮后，点击编辑BUG按钮，显示的内容如上截图，部分栏位内容消失

**Comment by zrfit** [comment]
您好，我也是这么操作的，并没有复现，您把metersphere中项目管理-模版管理-缺陷模版的配置截图和编辑项目的截图发下看看。

**Comment by norry2022** [comment]
我是使用的JIRA默认模板

![1](https://user-images.githubusercontent.com/105103343/170977441-16071450-6b68-4f8b-8fe8-6a40c3aa9fc9.png)
![2](https://user-images.githubusercontent.com/105103343/170977455-c88104ee-5493-4692-8b24-967134b72527.png)

**Comment by zrfit** [comment]
您好，我这边还是没有复现，您的jira是什么版本？能将jira上这2个字段（影响版本、操作系统版本）的字段设置信息截图吗？我们看下是什么类型的字段，排查下是否是某种类型的字段没处理。

**Comment by norry2022** [comment]
![编辑界面](https://user-images.githubusercontent.com/105103343/171345031-7846aa02-80be-475c-988c-8b7ea6ff0824.png)
![操作系统版本字段](https://user-images.githubusercontent.com/105103343/171345048-d9393a71-9462-44ea-8388-de05e4e921c5.png)
![影响版本字段](https://user-images.githubusercontent.com/105103343/171345063-cfefc9ba-6068-4fd3-a438-2cb27668fb0e.png)

不知道是不是你要的jira界面。编辑界面中，影响版本是多选下拉列表类型；操作系统版本是单选下拉列表类型

**Comment by norry2022** [comment]
JIRA v6.3.6

增加一个信息：同步缺陷后，在MS上提交BUG时上传的图片也不见了.

**Comment by zrfit** [comment]
您好，第一个问题仍未能复现，第二个图片问题复现了，后续版本我们会进行修复。

**Comment by zrfit** [comment]
v1.20.7-lts版本已修复图片同步问题。
