### ISSUE TITLE
[BUG]JSONPath提取参数不支持key里面含有小数点的情况

### ISSUE THREAD

**Issue by tongjun741** [metersphere/metersphere#1376]
**MeterSphere 版本**
 v1.7.1-66e9f091

**Bug 描述**
JSONPath提取参数不支持key里面含有小数点的情况。
接口返回的格式为：
```
{
"a.b":333
}
```
试过了以下几种情况都不可用：
```
$.a.b
$[a.b]
$.[a.b]
```
但在https://jsonpath.com/ 中测试是可以用$[a.b]匹配到的：
![image](https://user-images.githubusercontent.com/6827111/106836121-82970500-66d3-11eb-9341-a819916e00a8.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请通过 `$.['a.b']` 这样的格式提取。

**Comment by tongjun741** [comment]
测了可行，谢谢！响应真快！
