### ISSUE TITLE
[FEATURE]测试跟踪功能用例和缺陷管理模块优化建议

### ISSUE THREAD

**Issue by xiangxiang19872222222** [metersphere/metersphere#13761]
### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 请描述您的需求或者改进建议

1、功能用例部分：需要解决公共用例库能够被不同项目导入里面的用例；或者解决同一个空间下，不同项目直接用例可以互相引用
2、创建一个用例时，可以支持关联用例，能够选到其他用例
3、公共用例能够创建不同的分级模块，批量选择不同用例加入公共用例时，能够添加到不同目录层级中去存档，而不是按照项目纬度存档
4、缺陷管理：企业版同步缺陷是双向的，从而需要能够设置同步什么时间段的bug，以及什么样的状态bug，不接受全量同步
5、缺陷管理：创建缺陷不支持上传视频格式（低优先级）

### 请描述你建议的实现方案

1、功能用例部分：需要解决公共用例库能够被不同项目导入里面的用例；或者解决同一个空间下，不同项目直接用例可以互相引用
2、创建一个用例时，可以支持关联用例，能够选到其他用例
3、公共用例能够创建不同的分级模块，批量选择不同用例加入公共用例时，能够添加到不同目录层级中去存档，而不是按照项目纬度存档
4、缺陷管理：企业版同步缺陷是双向的，从而需要能够设置同步什么时间段的bug，以及什么样的状态bug，不接受全量同步
5、缺陷管理：创建缺陷支持上传视频格式

**Comment by Hyyfit** [comment]
感谢您的反馈。
1.目前公共用例库已经支持了，需要在项目设置里启用。
![image](https://user-images.githubusercontent.com/95834771/169462530-703276e1-b863-4441-b722-18c3368fc94e.png)
2.关联测试支持关联接口/性能等用例；依赖关系可以设置前后置的功能用例，也是可以设置关联关系的。
![image](https://user-images.githubusercontent.com/95834771/169463108-17e4491e-7a1c-46d6-86ba-ce850508259b.png)
3.缺陷同步可设置，这个已经规划了，正在等待排期。
4.v2.0的版本就会上线附件支持视频格式啦～。在功能用例和缺陷管理上传附件都支持了。
