### ISSUE TITLE
[BUG] 性能问题：【接口测试>>接口自动化测试】场景变量里的cvs文件比较大时，点击【预览】页签没有数据，并且系统就卡死了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#13767]
### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

【接口测试>>接口自动化测试】场景变量里的cvs文件比较大时，点击【预览】页签没有数据

### 重现步骤

1、在自动化场景变量里添加了多个CVS文件，并且这些CVS文件里的数据比较多，大约都有1w-2w条数据。此文件也添加成功。
2、关闭此自动化场景
3、重新打开此自动化脚本，点击【场景变量】，
4、选择左侧变量的第一个CVS文件变量，点击右侧【预览】页签。显示无数据。
5、有时需要等待几秒能显示，有时等待几分钟也不显示，重新刷新页面也不显示。

### 期待的正确结果

希望优化此预览信息性能。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/169322655-0c58cd97-2d5b-4678-a3f2-a7874b8fd018.png)

**Comment by zyyfit** [comment]
我添加了一个25000条数据的csv文件，见附件，文件大小 6.73 M，预览没有卡死，可以正常预览，你的文件多大？电脑是Windows还是mac？配置怎么样呢？

[test1.csv](https://github.com/metersphere/metersphere/files/8737603/test1.csv)

**Comment by huangxine** [comment]
我是上传了好几个大的cvs文件，就出现这个问题。你可以试一下。电脑是windows的。没有做其他特殊配置，就是上传了3个特别大的cvs文件到场景变量里

**Comment by zyyfit** [comment]
我在一个场景里传了几个csv文件，没出现这种卡死的问题，最大的一个有26M，10w数据，现在限制了默认预览前500条数据，应该不会特别卡，我预览大概是3秒左右
