### ISSUE TITLE
[FEATURE]UI测试--UI使用场景优化，场景步骤  可以 上下移动，切换

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13773]
### MeterSphere 版本

版本:   v1.20.2-lts-0f489ee9

### 请描述您的需求或者改进建议

路径：UI测试--UI自动化--场景步骤
描述：
1.场景步骤出现混乱时，目前只能通过删除，然后在新增一个进行操作
建议：增加一个步骤 上移/下移 的操作按钮，可以在步骤左边增加2个按钮

![image](https://user-images.githubusercontent.com/15188833/169442934-852ccd01-e188-4ec4-8367-e464a4018ea4.png)

**Comment by Hyyfit** [comment]
您好，我们的步骤是支持自由拖动的
![image](https://user-images.githubusercontent.com/95834771/169459944-e52c6516-e238-4d90-a3d5-5af3846d444c.png)
