### ISSUE TITLE
[BUG]服务调用dubbo失败，会无限请求

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#13777]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

本地起了服务，调用线上容器的dubbo会由于网络问题调用失败，正常应该重试三次，但实际请求了无限次数，导致metersphere无法正常使用,网页停止也不生效

### 重现步骤

1、在dubbo测试页面配置了dubbo方法，没有加分组，请求到了线上容器的节点
2、consumer&service重试次数配了3次
3、请求几分钟网页一直处于加载状态，此时停止，但是服务端还是在请求

### 附加信息

![image](https://user-images.githubusercontent.com/58592452/169453357-c1e70bf5-171d-4928-a40a-ca8354b96edd.png)
![image](https://user-images.githubusercontent.com/58592452/169453454-7d693863-9d11-4995-8a45-863438bbd1a8.png)
![image](https://user-images.githubusercontent.com/58592452/169453521-e4b391f1-3cdb-4af8-8afa-1c0f41aa0d3b.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您可以使用在线或者离线安装包安装试试，代码调试的话可能有其他因素导致失败

**Comment by juanmaocxy** [comment]
> 您好，没有复现这个问题，您可以使用在线或者离线安装包安装试试，代码调试的话可能有其他因素导致失败

我使用的是dev分支本地调试的，刚才使用1.20发现拉不到io.metersphere:ms-jmeter-core:pom:1.1.8

**Comment by zyyfit** [comment]
这个是在线安装脚本

![image](https://user-images.githubusercontent.com/73461316/169493436-d0833396-6a9e-40b1-8a55-d453bda08793.png)
