### ISSUE TITLE
[QUESTION] 请问下如何提高更多的并发数（比如到1000），目前是最高限制 50

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#13780]
### 请描述您的问题

请问下如何提高更多的并发数，比如到1000

谢谢

![image](https://user-images.githubusercontent.com/5927005/169446915-f4a6b4f8-d3ce-4056-ae2d-16dc98714966.png)

**Comment by Hyyfit** [comment]
您好，我们这个是支持配置的，在系统设置里可以配置。
![image](https://user-images.githubusercontent.com/95834771/169466634-1b23f4a4-5ef5-4c60-98e4-8a60464c744b.png)
