### ISSUE TITLE
[BUG]  [测试跟踪] 脑图新增用例操作步骤后，已经保存的标签会被清除

### ISSUE THREAD

**Issue by hejiong19860303** [metersphere/metersphere#13783]
### MeterSphere 版本

V1.19.3

### 使用外置数据库

否

### 问题描述

[测试跟踪] -【功能用例】使用脑图新增用例操作步骤后，已经保存的标签会被清除

### 重现步骤

1：表格编写一条case，标签test
2：在脑图中对该条用例新增操作步骤test1，预期结果“成功“
3：点击保存

### 期待的正确结果

脑图用例保存后，之前case的标签不会被清除

**Comment by ltfit** [comment]
你好 v1.20.4 -lts 已修复该问题 可以升级下
