### ISSUE TITLE
批量修改场景的环境配置后，场景内部的sql请求的环境配置未修改

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1378]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.0-3c6a4849
**Bug 描述**
简要描述您碰到的问题
批量修改场景的环境配置后，场景内部的sql请求的环境配置未修改

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
该场景下涉及到运行环境相关的同步调整

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
非常感谢您的反馈，我们会在1.8.0修复该问题
