### ISSUE TITLE
[QUESTION]接口请求支持设置代理服务器吗？

### ISSUE THREAD

**Issue by lonytese** [metersphere/metersphere#13794]
### 请描述您的问题

接口请求支持设置代理服务器吗？
我有些接口需要通过代理服务器才能正常请求

**Comment by Hyyfit** [comment]
支持的，在环境配置里的通用配置里，开启host就可以配置代理服务器了。
![image](https://user-images.githubusercontent.com/95834771/169501669-21637cfc-c6fb-4794-859c-2aca8ff84543.png)

**Comment by Hyyfit** [comment]
不好意思，理解错了，hosts是配置域名解析的。
代理服务器目前还不支持，我们会尽快排期。
