### ISSUE TITLE
[BUG]【接口测试>>接口自动化场景】在场景中引用其他子场景时，点击场景设置，选择子原场景环境，会弹出系统异常

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#13799]
### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

[BUG]【接口测试>>接口自动化场景】在场景中引用其他子场景时，点击场景设置，选择子原场景环境，会弹出系统异常

### 重现步骤

1、【接口测试>>接口自动化场景】选择具体场景，然后在场景中选择引用模式添加一个子场景
2、选择这个子场景的【环境设置】，在【环境设置】弹窗中，选择使用【原场景环境变量】。关闭弹窗。
3、系统出现错误提示

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/169499388-a97f4281-8ee5-4ab7-a71c-c59b2494cec9.png)
![image](https://user-images.githubusercontent.com/78218624/169499619-08be5b48-7ed3-4077-935e-cebbdc78ef26.png)

![image](https://user-images.githubusercontent.com/78218624/169498374-dde389d4-0b09-451b-a58d-46d543f8e6f0.png)

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/13793
