### ISSUE TITLE
[BUG]无法使用引用的场景的“原场景环境”

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#13793]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.3

### 使用外置数据库

是

### 问题描述

在场景中引用其他场景时，点击场景设置，选择原场景环境，会弹出这个toast：{ "timestamp": 1653027229791, "status": 500, "error": "Internal Server Error", "path": "/api/automation/setDomain" }
如图：
![image](https://user-images.githubusercontent.com/31870788/169487523-c0c6c910-1b0d-4bb9-a4f6-08583865a9b4.png)

### 重现步骤

引入其他场景 -> 点击其他场景右上角的场景设置 -> 选择原场景环境设置 -> 出现toast提示500报错 ；
经群里的小伙伴提醒，查看了服务器上面的报错信息/opt/metersphere/logs/metersphere/info.log：

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.ClassCastException: class java.lang.String cannot be cast to class com.alibaba.fastjson.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; com.alibaba.fastjson.JSONObject is in unnamed module of loader 'app')
```

### 期待的正确结果

可以使用被引用场景的原场景环境

### 相关日志输出

```shell
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.ClassCastException: class java.lang.String cannot be cast to class com.alibaba.fastjson.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; com.alibaba.fastjson.JSONObject is in unnamed module of loader 'app')
```

**Comment by Faerie1999** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/31870788/169488381-d22f74fc-bb22-4e80-bd52-88d4fe0c078e.png">

**Comment by Faerie1999** [comment]
我在[demo](https://demo.metersphere.com/#/api/automation)上面试了：
可以看项目test-jml下面的场景 wwww（ID：111111122），引用了三个场景，想要设置引用场景的原场景环境，发现只有 项目升级系统 下面的场景（ID: 100007）,会报这个错，说明这个错并非必定出现。

**Comment by Faerie1999** [comment]
我在[demo](https://demo.metersphere.com/#/api/automation)上面试了：
可以看项目test-jml下面的场景 wwww（ID：111111122），引用了三个场景，想要设置引用场景的原场景环境，发现只有 项目升级系统 下面的场景（ID: 100007）,会报这个错，说明这个错并非必定出现。

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题，看看是数据问题还是bug

**Comment by zyyfit** [comment]
您好，现在demo环境复现不了了，能再操作一下复现吗？或者描述一下复现步骤？

**Comment by Faerie1999** [comment]
***@***.***”；
我以帮您复现场景，请进入项目“电商后台”，场景名称为：复现bug无法使用引用的场景的“原场景环境” ；
里面已经引用了一个场景“查询优惠券”，当您放到引用场景右上角的三个点，点击场景设置，再点击“原场景环境”时，就会出现该错误toast；
如果有时间的话，麻烦您尽快处理这个bug，因为目前我们公司的工作由于该问题暂时停滞，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月23日(星期一) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]无法使用引用的场景的“原场景环境” (Issue #13793)





 
您好，现在demo环境复现不了了，能再操作一下复现吗？或者描述一下复现步骤？

**Comment by zyyfit** [comment]
> 电商后台

您好，我看您这个复现的场景里面，引用的这个 查询优惠券 场景，选择的环境是 知乎，但是这个环境没有域名呀，所以这个报错应该是引用原场景环境，但是环境没找到域名导致的，您先给那个环境添加个域名试试，看还报不报错，我们这边也优化一下提示信息

**Comment by zyyfit** [comment]
1.20.4已修复，请等待版本发布后验证
