### ISSUE TITLE
[BUG]接口测试执行报告中的执行结果展示错误

### ISSUE THREAD

**Issue by yintest** [metersphere/metersphere#13797]
### MeterSphere 版本

 v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

1.接口执行状态码和断言成功，接口用例的执行结果展示失败

### 重现步骤

1.将接口用例关联到测试计划中，定期执行

### 期待的正确结果

展示成功

### 附加信息

![06b2cf5637610206ff0d334c1ab553d](https://user-images.githubusercontent.com/26396361/169495966-e88be10c-186b-4243-b316-2c6dd25e8161.png)

**Comment by zrfit** [comment]
您好，未复现该问题，是否有其它特殊配置和操作步骤，如方便可将api文件导出我们尝试复现。
