### ISSUE TITLE
[FEATURE]1.经试用，提出以下问题望采纳；

### ISSUE THREAD

**Issue by lisiyao1988** [metersphere/metersphere#138]
1.参数化相关问题：日常测试场景中，常会出现流水号、时间戳等参数化需求，jmeter函数助手中有众多的参数化方式，建议参考实现；
![image](https://user-images.githubusercontent.com/64162722/87739090-96e7e300-c811-11ea-9d80-810c7ce86f3c.png)

2.数据库问题：
1.流程测试中需要对数据库落库情况进行断言，或取值建议实现（db2，mysql，oracle）；
3.BeanShell PostProcessor+BeanShell 断言：建议加入增强自定义扩展；
4.增加全局变量，ip、端口号、请求头等信息无需重复操作

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
