### ISSUE TITLE
场景变量设置计数器后，配上循环控制器，计数器不递增，始终是开始默认的那个

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1380]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.0-3c6a4849

**Bug 描述**
简要描述您碰到的问题
场景变量设置计数器后，配上循环控制器，计数器不递增，始终是开始默认的那个

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
根据循环的次数，计数器根据设置的递增数进行递增

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
