### ISSUE TITLE
[BUG] 从报告中点击场景用例link进入场景用例页面，页面显示模块信息丢失

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13809]
### MeterSphere 版本

1.21

### 使用外置数据库

否

### 问题描述

从报告中点击场景用例link进入场景用例页面，页面显示模块信息丢失
此问题不是每次都会出现
![image](https://user-images.githubusercontent.com/103017812/169542615-df4c88cf-f98f-4996-8334-b14aaffed305.png)

### 重现步骤

打开报告
点击场景用例链接

**Comment by ltfit** [comment]
感谢反馈 后续修复下 这个是切换项目模块导致的

**Comment by ltfit** [comment]
你好  v1.20.6-lts版本已修复
