### ISSUE TITLE
[BUG] MS的get请求方式，参数带数组，访问失败（案例从postman导出到MS，postman访问成功，MS失败）

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13803]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

场景：
在Postman里面，用get请求方式，成功，其中一个参数值是 数组类型

导出到MeterSphere里面，提示URL异常

在Jmeter里面运行，也是失败，提示URL异常

### 重现步骤

postman结果展示：
![image](https://user-images.githubusercontent.com/15188833/169506557-e1283c14-834e-49e6-aa95-090a3e5f325b.png)

MeterSphere结果展示：
![image](https://user-images.githubusercontent.com/15188833/169506558-4fda2aae-e97d-4509-9f16-c8ff43dc3fc5.png)

Jmeter访问结果：
![image](https://user-images.githubusercontent.com/15188833/169506689-44517bbb-a9c5-4fcf-8d4b-f804d1c45c9a.png)
![image](https://user-images.githubusercontent.com/15188833/169506633-6ad7b46a-d57c-48a6-8abf-93500c309748.png)

**Comment by zrfit** [comment]
您好，我们目前测试引擎是jmeter ，目前请求返回都和jmeter 保持一致。
感谢您的反馈，如果后续这种场景用的比较多，影响较大，我们也可反馈给产品人员，进行调研，看是否进行优化。

**Comment by startpjx** [comment]
解决了，转义下就OK了，
方法 ： %22 代替 "
