### ISSUE TITLE
[FEATURE]是否可以Mock的右边的位置添加一个文档按钮，一般开发写好api后，会看一眼文档是否正确，放在这里比较方便

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13812]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

![QQ拼音截图未命名](https://user-images.githubusercontent.com/38156471/169636139-57c0220a-3e49-4abc-9aac-f72560f8acca.jpg)
是否可以在圈出的位置添加文档，一般开发写好api后，会看一眼文档是否正确，放在这里比较方便

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
