### ISSUE TITLE
[BUG]功能用例，系统未对导入的用例判断ID大小写

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13815]
### 联系方式

张树彬

### MeterSphere 版本

1.20.1

### 使用外置数据库

否

### 问题描述

功能用例exce里有两个用例的ID除大小写外，其他都一致，导入时系统未判断ID大小写，导入后在线编辑提示ID已存在。

### 重现步骤

操作步骤：

1. 本地exce用例里有两条用例ID分别为：ABC123、abc123

2. 上传excel用例，可正常导入

3. 导入后在线编辑ABC123、abc123任意一条用例ID时，提示ID已存在

结论：导入时未校验ID大小写，在线编辑或创建用例会校验ID大小写；希望统一标准。

### 期待的正确结果

导入时校验ID大小写，无论在线创建用例还是导入用例，对于ID大小写的要求保持一致

**Comment by ltfit** [comment]
后续优化下

**Comment by ltfit** [comment]
你好 v1.20.4 -lts 已修复该问题 可以升级下
