### ISSUE TITLE
[QUESTION]原先参数最右边都有描述的文本框的，现在的版本没有了，是优化掉了吗？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13825]
### 请描述您的问题

![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/169673173-7050705c-65b0-4ac4-a59c-5c9c02d8efac.jpg)
原先参数最右边都有描述的文本框的，现在的版本没有了，是优化掉了吗？

**Comment by Hyyfit** [comment]
还在的。
这里我们后续还会再优化，会改成可配置的，如果需要描述，就展示，不需要描述可以配置不展示。
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/95834771/169729679-cbc2253a-babd-41a1-88a4-bfe6df5c42ca.png">
