### ISSUE TITLE
[BUG]UI自动化-场景，在场景里导入其他场景后，被导入场景的“场景设置”弹窗无法自动打开

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13822]
### 联系方式

张树彬

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

UI自动化-场景，在场景里导入其他场景后，被导入场景的“场景设置”弹窗无法自动打开

### 重现步骤

1. 创建UI自动化场景
2. 在该场景中导入其他场景
3. 查看被导入场景的“场景设置”
4. 无法自动打开弹窗，需要鼠标点击空白处后显示

### 期待的正确结果

点击“场景设置”选项后，立刻打开该弹窗

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/169654032-41e32049-685d-440e-9758-688623abb2db.png)

**Comment by ltfit** [comment]
你好 我这边多次尝试正常 还有别的特殊操作么

**Comment by binbin0406** [comment]
可以加我微信，我录个视频给你

**Comment by ltfit** [comment]
下个版本修复下

**Comment by ltfit** [comment]
你好 v1.20.4-lts  此版本已解决该问题   升级下
