### ISSUE TITLE
无法通过响应内容进行断言

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1382]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
可以根据响应内容的内容进行判断正确性

**Comment by xulinde** [comment]
您好，我们平台目前是支持对返回内容为 JSON 的请求进行断言的，在添加断言页面还推荐 jsonpath 断言功能，点击某个字段旁的按钮可以自动添加针对该字段的断言
![image](https://user-images.githubusercontent.com/64065190/107207028-c2931a80-6a3a-11eb-8968-8f080ef0775a.png)

**Comment by xulinde** [comment]
同时我们也支持正则、xpath以及自己写脚本等各种断言类型
