### ISSUE TITLE
[BUG]UI自动化-创建/编辑场景，创建新场景或编辑已有场景，点击关闭按钮时未提示保存弹窗。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13823]
### 联系方式

张树彬

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

UI自动化-创建/编辑场景，创建新场景或编辑已有场景，点击关闭按钮时未提示保存弹窗。

### 重现步骤

1. 创建新场景，或编辑已有场景
2. 在场景内任意编辑后，点击关闭场景按钮
3. 直接关闭场景，未出现保存提醒弹窗
* 我记得1.20.2版本还有这个弹窗，并且之前在功能和接口模块提过此问题的BUG

### 期待的正确结果

点击关闭场景按钮后，出现保存提醒弹窗

**Comment by ltfit** [comment]
下个版本优化下

**Comment by ltfit** [comment]
你好 v1.20.6-lts已修复此问题
