### ISSUE TITLE
[BUG]测试计划-报告，连续打开多个不同的测试计划报告，报告里的数据都显示的第一次打开报告的数据

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13824]
### 联系方式

张树彬

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

测试计划-报告，连续打开多个不同的测试计划报告，报告里的数据都显示的第一次打开报告的数据；现在需要每打开一个报告都手动刷新页面，才能避免这个问题。（测试前已清理浏览器缓存）

### 重现步骤

1. 打开任意测试计划，进入报告
2. 再次点击测试计划列表，点击另一个测试计划，会直接进入该计划的报告页
3. 第二次测试计划报告里功能、接口、性能几个区域的数据统计错误，全都显示的是第一个报告的数据

### 期待的正确结果

打开不同的测试计划报告，显示对应的正确的数据

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/169656342-20a9cbf5-e76f-4c1c-b516-dad498cf118a.png)
![1653142981(1)](https://user-images.githubusercontent.com/77324661/169656345-2e53405b-9859-40aa-9441-0ac30c3ddee7.jpg)

**Comment by ltfit** [comment]
感谢反馈 下个版本修复

**Comment by ltfit** [comment]
你好 v1.20.4-lts  此版本已解决该问题   升级下
