### ISSUE TITLE
[FEATURE]建测试任务的时候，希望在选择用例的时候可以按照模块来选择用例

### ISSUE THREAD

**Issue by lrh1234** [metersphere/metersphere#13839]
### MeterSphere 版本

 v1.20.3-lts

### 请描述您的需求或者改进建议

在建测试任务的时候，希望加一个可以按照选模块来选择的用例的功能
![image](https://user-images.githubusercontent.com/73111478/169743399-22649ce2-4c2c-4490-b0fa-af806ee4aeaa.png)
![02C3B717-30D4-40CA-82C4-9C5EBC55C0C1](https://user-images.githubusercontent.com/73111478/169743449-323070ba-1a29-47dc-8700-ff165f28d661.png)

### 附加信息

辛苦看看哈

**Comment by Hyyfit** [comment]
您好，测试计划里是支持按模块选择的呀

**Comment by lrh1234** [comment]
>不支持的，我试了不行 只能按点击模块之后，最多50条现在，我如果是需要整个模块的用例就不行

**Comment by lrh1234** [comment]
@Hyyfit

**Comment by Hyyfit** [comment]
这里可以选择模块下的所有用例
![image](https://user-images.githubusercontent.com/95834771/169935128-52528cfd-86bd-4acd-9c8d-046d2e4fe1bb.png)

**Comment by lrh1234** [comment]
> 这里可以选择模块下的所有用例 ![图片](https://user-images.githubusercontent.com/95834771/169935128-52528cfd-86bd-4acd-9c8d-046d2e4fe1bb.png)

好的，感谢
