### ISSUE TITLE
[BUG]禅道在PATH_INFO下，项目集成失败

### ISSUE THREAD

**Issue by ousinka** [metersphere/metersphere#13832]
### MeterSphere 版本

v.1.20.1-lts

### 使用外置数据库

是

### 问题描述

禅道在PATH_INFO下，项目集成失败，查看项目代码，原因为ZentaoClient在代码抽象里，只改变了url内容，没有改变请求方式。
在PATH_INFO下，部分接口测试正常，原因为部分接口使用了POST调用方式。
具体请见ZentaoClient代码。

### 重现步骤

禅道集成后，关联项目。必现

### 期待的正确结果

禅道PATH_INFO下，各功能正常

### 相关日志输出

```shell
ZentaoClient.java 204 行 
LogUtil.info("query zentao product info error. product id: " + relateId);
```

### 附加信息

无

**Comment by ltfit** [comment]
你好 以下这些配置正常不
配置文件路径：/opt/zbox/app/zentao/config/my.php
修改$config-&gt;requestType     = 'PATH_INFO';
禅道重启命令 /opt/zbox/zbox restart

**Comment by ousinka** [comment]
将ZentaoClient中的GET方法，调整成POST，替换class，在$config->requestType = 'PATH_INFO'; 模式下目前使用正常（关联项目不再提示：ID不存在或其它错误。缺陷同步正常）。

**Comment by ltfit** [comment]
ok

**Comment by AgAngle** [comment]
你好，我们'PATH_INFO'模式下测试没发现问题，请问你禅道是什么版本的？
