### ISSUE TITLE
[FEATURE] 点击 用例列表 和具体用例的时候保持绝对位置不变，可通过固定左侧的模块实现

### ISSUE THREAD

**Issue by qclforever** [metersphere/metersphere#13833]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/44964749/169735650-f6480168-0386-4607-a97d-c9b82def7ed6.png)

点击 用例列表，左侧会有 模块；
点击 具体用例，左侧模块小时，整个界面向左移=====》导致总是需要不停移动鼠标

### 请描述你建议的实现方案

固定左侧的模块

**Comment by Hyyfit** [comment]
感谢反馈，目前的设计如此。考虑到左侧模块树在编辑用例的时候，基本不使用。为了可以更大程度的展示用例相关的信息，设计上是隐藏了左侧模块树。
