### ISSUE TITLE
[BUG]ES的api请求中有批量添加数据的方法，需要使用到binary的数据，上传一个文件，但是请求直接就报异常，找不到数据

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13849]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

ES的api请求中有批量添加数据的方法，需要使用到binary的数据，上传一个文件，但是请求直接就报异常，找不到数据
![QQ拼音截图未命名3](https://user-images.githubusercontent.com/38156471/169768577-34e1c51c-32e1-48bb-bd8f-84220dc572cc.jpg)

### 重现步骤

文件无法找到

### 期待的正确结果

可以请求成功啊

### 附加信息

![QQ拼音截图未命名3](https://user-images.githubusercontent.com/38156471/169768681-be68dbe1-aa68-42a8-9560-41a400cbc594.jpg)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复~
