### ISSUE TITLE
建议添加场景可以按照一定的顺序执行

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1384]
**请描述您的需求或者改进建议.**
如果全部场景一起执行，数据库的数据或者接口执行会报错，比如A接口执行之前需要去数据库标记数据，需要拿着标记的数据作为接口的入参，接口B也需要先在数据库标记后，再拿着作为接口的入参

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已计划下个版本优化该功能，请持续关注～

**Comment by youliyuan-fit2cloud** [comment]
v1.8版本已修复
