### ISSUE TITLE
[BUG]UI自动化场景，设置场景变量后，再输入框中引用，值没有带过去

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#13846]
### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

前置条件：UI自动化场景A引用了一个登录场景B；登录场景B设置的变量{用户名、密码}可以引用。

问题：场景A设置了个变量。输入操作用${name}方式引用变量，实际调试时，引用不生效；

### 重现步骤

前置条件：UI自动化场景A引用了一个登录场景B；登录场景B设置的变量{用户名、密码}可以引用。

问题：场景A设置了个变量。输入操作用${name}方式引用变量，实际调试时，引用不生效；

一、引用场景B的变量可以正常获取
<img width="960" alt="输入" src="https://user-images.githubusercontent.com/43202800/169756191-1cef86b5-3328-4a7f-a3d3-47a74a96c6d5.png">
二、场景A设置变量后，运行不能获取到值
<img width="960" alt="设置变量" src="https://user-images.githubusercontent.com/43202800/169756309-6b59b35a-3b12-4cdc-8275-1fd6abee2e05.png">
<img width="759" alt="Snipaste_2022-05-23_13-52-33" src="https://user-images.githubusercontent.com/43202800/169756320-51ccc313-9186-4a23-8d7c-d685c75f60a5.png">

### 期待的正确结果

场景B可以获取到变量值

**Comment by zyyfit** [comment]
没有复现这个问题，您引用的场景B，查看一下有没有勾选使用原场景变量
![image](https://user-images.githubusercontent.com/73461316/169766218-5f5568ce-8590-481d-a9de-1facbf95345a.png)

**Comment by xhy12** [comment]
> 没有复现这个问题，您引用的场景B，查看一下有没有勾选使用原场景变量 ![image](https://user-images.githubusercontent.com/73461316/169766218-5f5568ce-8590-481d-a9de-1facbf95345a.png)
1、场景B变量是勾选了的 
2、是当前这个场景A里面，设置新的变量进行引用。
<img width="953" alt="场景A里面新设置场景变量，引用不生效" src="https://user-images.githubusercontent.com/43202800/170170719-30de967c-4eab-4584-82ca-5c772811fb00.png">

**Comment by xhy12** [comment]
https://user-images.githubusercontent.com/43202800/170170927-3adc0567-cf32-4396-a88d-d9007289cf8a.mp4

**Comment by zyyfit** [comment]
好的，复现了，后续版本修复

**Comment by zyyfit** [comment]
另外，如果您着写脚本的话，可以先用这种方式设置变量
![image](https://user-images.githubusercontent.com/73461316/170242544-1f70e4ed-a076-440a-ac5c-688865c7d2e5.png)

**Comment by zyyfit** [comment]
1.20.4已修复
