### ISSUE TITLE
[FEATURE]和禅道集成时项目ID验证失败

### ISSUE THREAD

**Issue by lixiup** [metersphere/metersphere#13842]
### MeterSphere 版本

 v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

 禅道改版了，现在是产品-项目作为整体，bug不是和“产品或项目”挂钩，而是“产品和项目”挂钩
目前使用的禅道版本为16.5

### 重现步骤

 禅道改版了，现在是产品-项目作为整体，bug不是和“产品或项目”挂钩，而是“产品和项目”挂钩

### 附加信息

![image](https://user-images.githubusercontent.com/50001937/169734467-05023c66-bcab-48ba-a3a0-488587bc355f.png)

**Comment by ltfit** [comment]
您好 没太看明白的描述

**Comment by dashenyucainiao** [comment]
禅道开源版15.7同样有这个问题

[info.log](https://github.com/metersphere/metersphere/files/8753622/info.log)

**Comment by ltfit** [comment]
最新开源版有此问题 等后续修复下
