### ISSUE TITLE
[BUG]快速点击多次接口自动化调试，自定义请求会产生循环

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13851]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

1.创建接口自动化场景
2.添加自定义请求
3.快速多次点击调试
4.自定义请求会产生循环

### 重现步骤

1.创建接口自动化场景
2.添加自定义请求
3.快速多次点击调试
4.自定义请求会产生循环
![image](https://user-images.githubusercontent.com/88763608/169772388-80c280fb-ea3e-4046-a2e9-7ca328e2e8f8.png)

### 期待的正确结果

1.不需要产生循环

### 附加信息

[Metersphere_Scenario_新的项目.zip](https://github.com/metersphere/metersphere/files/8752623/Metersphere_Scenario_.zip)

**Comment by youliyuan-fit2cloud** [comment]
你为啥要这么操作？@~@

**Comment by linfengjjj** [comment]
有的用户手快，习惯性双击23333

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复
