### ISSUE TITLE
[FEATURE]断言中没有“为空”和“不为空”的判断，是否有方法用正则判断，或者能否添加这两个判断？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13850]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

![QQ拼音截图未命名2](https://user-images.githubusercontent.com/38156471/169769083-1780bc90-c8be-4338-b1e8-64885e93cde0.jpg)
断言中没有“为空”和“不为空”的判断，是否有方法用正则判断，或者能否添加这两个判断？

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
