### ISSUE TITLE
[BUG]CASE用例无法批量编辑状态

### ISSUE THREAD

**Issue by yiguming** [metersphere/metersphere#13867]
### 联系方式

13818775694

### MeterSphere 版本

  v1.20.1-lts-rc-f42dbe5d

### 使用外置数据库

否

### 问题描述

接口中点击CASE ，点击批量编辑，应该可以批量编辑用例的状态，否则单独改的话很不方便

### 重现步骤

接口中点击CASE ，点击批量编辑，应该可以批量编辑用例的状态，否则单独改的话很不方便

### 期待的正确结果

![image](https://user-images.githubusercontent.com/5902679/169804249-e8b0088a-1b6f-4f18-826b-a9feb4298a6a.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
