### ISSUE TITLE
[BUG] [接口测试] 在用例中添加文档结构断言，选择跟随API定义时，不能将API定义中的内容获取过来，导致断言不生效

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#13861]
### 联系方式

18323056969

### MeterSphere 版本

V1.19.3

### 使用外置数据库

否

### 问题描述

在case中不能使用跟随API定义的文档结构断言

### 重现步骤

前提：存在有效API且包含返回体
步骤：
  1、新增该API用例-》填写参数-》添加断言
  2、选择文档结构断言-》跟随API定义-》查看断言内容
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/13564069/169788983-95036d43-851f-443c-95c2-21fe269bcdfb.png">

### 期待的正确结果

可以将api的返回体获取过来并针对进行断言设置

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts 中已修复
