### ISSUE TITLE
[BUG]环境配置-全局前置和后置脚本未生效

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#13862]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

环境配置-全局前置或后置脚本未生效，没有执行。

### 重现步骤

接口测试-接口定义-CASE，点击编辑CASE，在编辑页面右上边环境下拉列表点击“环境配置”，脚本内容是打印一行日志，点击确定；
![image](https://user-images.githubusercontent.com/18514555/169794719-a197ee1b-59ae-4d4c-aa8e-7c6e608e1e0c.png)

点击执行按钮，查看控制台输出，并没有打印脚本处理结果
![image](https://user-images.githubusercontent.com/18514555/169794789-4e5a237a-6a28-4449-b05b-640586a280d3.png)
![image](https://user-images.githubusercontent.com/18514555/169796239-77766d7a-450f-45bf-b94d-4af6cba66471.png)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/169945007-177318a9-421c-4ed1-9d11-019d0e8be9f7.png)
这个过滤HTTP请求就是 http的请求不打印。。。
你这个请求是不是HTTP？

**Comment by xkmyf** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/169945007-177318a9-421c-4ed1-9d11-019d0e8be9f7.png) 这个过滤HTTP请求就是 http的请求不打印。。。 你这个请求是不是HTTP？

是http的。我理解有误了，以为是筛选的请求类型才执行全局脚本，没想到是排除的。
