### ISSUE TITLE
[BUG] 最新版本：测试计划--报告，状态为Running是，报告里面没有具体信息

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13866]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

目录：测试计划--报告
版本：从1.19升级到1.20.3最新版
描述：最新版本，报告里面，状态为 Running时，和之前版本对比，测试报告里面没有具体信息

### 重现步骤

新版本状态为 running 的报告截图展示：
![image](https://user-images.githubusercontent.com/15188833/169798737-2ee5fd1f-7fd0-4d1c-94b0-d3327fcaa340.png)

报告结果：
![image](https://user-images.githubusercontent.com/15188833/169798854-8daee30f-079a-4a78-bab1-119d00c9ad59.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题
请确认这个测试计划里面关联的接口/场景，或性能用例是否被取消关联或者被删除？
