### ISSUE TITLE
[BUG]当JMX中请求子级下有CSV时，导入MS接口自动化，将请求另存为接口定义，产生的接口定义和接口CASE执行会报CSV文件不存在

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13863]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

1.JMX中http请求下级包含CSV文件设置
2.将JMX导入MS接口自动化
3.将请求另存为接口定义，产生一个接口定义和接口CASE
4执行接口定义和接口CASE，均报错 CSV文件不存在

### 重现步骤

1.JMX中http请求下级包含CSV文件设置
2.将JMX导入MS接口自动化
3.将请求另存为接口定义，产生一个接口定义和接口CASE
![image](https://user-images.githubusercontent.com/88763608/169796818-97a95f13-f958-4686-942f-9ced90bb3807.png)

4执行接口定义和接口CASE，均报错 CSV文件不存在（可以用附件信息中的JMX进行测试）
<img width="792" alt="da47a864f352c0f341e2572185161e7" src="https://user-images.githubusercontent.com/88763608/169796690-917e14d8-59a5-4e9e-9c2d-36e3ea39d19d.png">
<img width="944" alt="87ce93e28b8bbc01886e7bc11a968d7" src="https://user-images.githubusercontent.com/88763608/169796694-452c93ed-4127-4762-841e-86c4eccd4b0e.png">

### 期待的正确结果

希望不会报错，因为接口定义和接口CASE页面上并未展示任何CSV相关配置

### 附加信息

[复现另存为问题.zip](https://github.com/metersphere/metersphere/files/8753662/default.zip)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，会尽快修复该问题

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复~
