### ISSUE TITLE
[FEATURE]项目管理中缺陷模板最新版无默认值，属于必填但无特殊显示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#13874]
### MeterSphere 版本

1.20.。3

### 请描述您的需求或者改进建议

新建项目时缺陷模板系统逻辑为必填，页面无必填标识，表单无验证不能为空

### 请描述你建议的实现方案

新建/修改项目时缺陷模板提示为必填，有默认值，表单验证缺陷模板不能为空
当用户无须指定的缺陷模板时，有默认值，无须选择

### 附加信息

<img width="1150" alt="e4cb06fc26b5fba95314872f83d75fd" src="https://user-images.githubusercontent.com/103925124/169851770-3123ce05-97f3-4e0f-bd97-d3513a293ac3.png">
<img width="683" alt="b558448b24de5d1f1b431bc50a36caa" src="https://user-images.githubusercontent.com/103925124/169851836-e46cca6d-143a-4f96-b7e7-141e023b9a15.png">

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
