### ISSUE TITLE
[BUG]验证上传文件接口的上传文件功能时，对比MS与Jmeter，MS接口调测失败

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#13881]
### MeterSphere 版本

1.20.2lts

### 使用外置数据库

否

### 问题描述

验证上传文件接口的上传文件功能时，对比MS与Jmeter，MS接口调测失败

### 重现步骤

1.调测验证客户系统的上传文件接口，基于JMeter、Postman均能调测通过；
2.使用MS调测验证，在请求参数相同的情况下，调测失败(设置Content-Type与JMeter一致时仍请求失败)；

### 期待的正确结果

2.在MS上调测客户系统的文件上传接口成功。

### 附加信息

![de262b4d0b87e79cddf35727d6aeff8](https://user-images.githubusercontent.com/92150453/169938728-4fab6818-0fb3-4a28-928c-9b773104dafd.png)
![8bff024c4c5e349de529746bf14ae0e](https://user-images.githubusercontent.com/92150453/169938739-84dc53ae-64f8-4628-a870-9593219e2773.png)
![8fd07e1f27fef15c3a0b5c9a9abe8d3](https://user-images.githubusercontent.com/92150453/169938756-d3f0608c-c3a6-4900-818d-284f2a1ea48a.png)
![7d030a1188d4d19018d043c5cf655fa](https://user-images.githubusercontent.com/92150453/169938769-126d694a-f284-4773-abdd-306b28e80fee.png)
![99c29afa18b584e2055a6c5b824030e](https://user-images.githubusercontent.com/92150453/169938885-6d574aac-2236-4b30-9b20-3c23c78bbb8e.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复~
