### ISSUE TITLE
[BUG]case请求中引用变量值修改，接口自动化场景中引用的变量请求中的变量已更新，但执行完场景用例，测试报告中的值还是原来的值，没有更新

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1388]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091

**Bug 描述**
简要描述您碰到的问题
case请求中引用变量值修改，接口自动化场景中引用的变量请求中的变量已更新，
但执行完场景用例，测试报告中的值还是原来的值，没有时时更新
**Bug 重现步骤**
1.  修改【接口测试-接口定义-case】里变量引用
2. 【接口自动化】场景步骤中引用变量已更新，执行该场景
3. 查看测试报告中该变量值是否正确
4. 

**期待的正确结果**
正确情况下应该是什么样的？
场景中引用变量的值要时时更新

实际情况：场景中引用的变量值没有时时更新，需要重新删除该case引用，然后再重新导入。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106839049-621d7980-66d8-11eb-92fb-2179e4702223.png)

![image](https://user-images.githubusercontent.com/55734318/106839008-487c3200-66d8-11eb-95ef-b4842286ee34.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
