### ISSUE TITLE
[BUG]接口自动化， 添加自定义请求， 调试自定义请求报错

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#13885]
### 联系方式

内部郭灶鹏

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

接口自动化添加自定义请求， 调试自定义请求时， 系统报错

### 重现步骤

1、新建场景， 新建一个自定义请求。
2、在自定义请求中， 添加一个前置脚本，一个后置脚本（脚本内容为空，不写入脚本内容） ，点击保存场景
3、 点击调试自定义请求， 页面报错。
![6ae36adc4c68464adfcea8a07122b7f](https://user-images.githubusercontent.com/30264974/169942917-a60272d4-773e-443d-bbcf-29f6d4522b58.png)
[info(3).log](https://github.com/metersphere/metersphere/files/8759337/info.3.log)

**Comment by youliyuan-fit2cloud** [comment]
已修复，等发小版本吧~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts中已修复
