### ISSUE TITLE
[FEATURE]UI自动化测试的断言不好用

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13887]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

![QQ拼音截图未命名4](https://user-images.githubusercontent.com/38156471/169948252-d43a5ccd-e914-4502-9ed3-7794c49b1279.jpg)
![QQ拼音截图未命名5](https://user-images.githubusercontent.com/38156471/169948260-205118b3-6ab9-46e2-9333-632afeb855c3.jpg)
我这是在断言弹窗的文本内容，但是我无论判断它为什么值都不对，是否可以在报告中告诉我系统检测到的值是什么嘛，目前UI自动化测试断言非常不好用啊

**Comment by Hyyfit** [comment]
您好，这个应该不是弹窗吧？

**Comment by YellCatt** [comment]
> 您好，这个应该不是弹窗吧？

这不是弹窗是什么？

**Comment by Hyyfit** [comment]
我们弹窗断言是针对alert和Confirmation类型的原生弹窗。
你看一下你这个弹窗能不能元素定位，如果可以的话，就不是弹窗，可以通过元素断言的方式断言。
