### ISSUE TITLE
[FEATURE]CASE里无法填写备注，无法说明这个CASE是为了测试那些内容存在的

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13886]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

![QQ拼音截图未命名6](https://user-images.githubusercontent.com/38156471/169947039-b9cc2232-9c71-4bc5-a7a5-4d7b2385f8ed.jpg)
CASE里无法填写备注，无法说明这个CASE是为了测试那些内容存在的

**Comment by Hyyfit** [comment]
通常会用CASE名称来表达测试重点

**Comment by YellCatt** [comment]
> 通常会用CASE名称来表达测试重点

是可以用来表达测试的重点，但是如果能够详细说明一些，不是也挺好的吗？，难道名称要写的特别长才比较好？

**Comment by Hyyfit** [comment]
感谢反馈，也可以加一个描述，已规划，待排期。
