### ISSUE TITLE
[BUG]metersphere idea插件，客户是5个服务，同步到ms的接口信息基本都是错的，少字段，有的请求体完全就是错的

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13882]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

metersphere idea插件，客户是5个服务，同步到ms的接口信息基本都是错的，少字段，有的请求体完全就是错的

### 重现步骤

无法重现，我们初步分析下来和客户这边项目源码特殊的编码风格有关

链接: https://pan.baidu.com/s/1klcl5Uf_XCeh6vVt0ZuqgA 提取码: ny3q 

问题录屏，目前5个服务，我们全部手动录入，插件同步的都是错的。
 
我们初步分析下来，应该是和客户的特殊的编码风格有关。
![1653362320(1)](https://user-images.githubusercontent.com/76033005/169941978-b87d4d69-38ac-4ed3-b933-2cfa8f043fc3.png)

客户的项目源码不可以外泄。 

### 期待的正确结果

接口同步，字段信息

**Comment by zhangdahai112** [comment]
![image](https://user-images.githubusercontent.com/46101698/169942159-eb09b297-bee4-485c-ba02-908ff6f22b24.png)
大括号的问题可以试试增加对象解析深度

**Comment by zhangdahai112** [comment]
![image](https://user-images.githubusercontent.com/46101698/169942250-a1b96892-3c03-470a-966d-b0931cbe14a3.png)
大括号的问题可以试试增加对象解析深度看看
