### ISSUE TITLE
[BUG]批量执行case控制台异常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#13891]
### 联系方式

18311441708

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

批量执行case后查看控制台出现异常情况
①控制台一片白（单独执行不为空）
②控制台异常error和空指针（单独执行无）
③单独执行单用例和批量执行case的状态码显示不一致

### 重现步骤

选择三个以上case，批量执行
选择并行，独立报告执行
点击case详情，查看控制台

### 期待的正确结果

批量执行case控制台和单独执行case控制台一致或无错误，用户可理解无接口本身异常
批量执行case和单独执行case接口状态码一致

### 附加信息

批量执行case后查看控制台
<img width="932" alt="476a937b32f9ca0fad00941e497d11b" src="https://user-images.githubusercontent.com/103925124/169961646-11902172-4447-4376-8173-55a1e29552f9.png">
单执行case控制台
<img width="929" alt="ada3ddeb3e3377c38dd5fd6ba8885a8" src="https://user-images.githubusercontent.com/103925124/169961659-a1fed7ad-b4ef-484d-900a-41d27f696dbe.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts 中已修复
