### ISSUE TITLE
[BUG]TCP接口定义多次切换运行环境后，实际请求时使用了未被选中的环境中的TCP配置

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13898]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

背景：TCP接口定义有test栏可以测试，在基础信息和右上角都可以配置环境信息，正常来说，应该以基础信息配置的环境为准，基础信息未配置时，右上角的环境配置会同步到基础信息环境这边
问题：有两个环境A、B，在TCP接口定义test中的基础信息和右上角环境配置中多次切换选择，最终两边都选择了环境B，但是测试时，通过控制台发现请求实际上使用的TCP配置是环境A

### 重现步骤

1.有两个环境A、B，在TCP接口定义test中的基础信息和右上角环境配置中多次切换选择
2.每次选择环境都，都点击测试
3.多次切换环境后，发现基础信息和右上角都选择了环境B，但是控制台中发现实际上请求使用了环境A的TCP配置
4.具体操作过程可以参考附件视频
![image](https://user-images.githubusercontent.com/88763608/169980694-c484213c-7855-465b-b596-9c58547f080e.png)

### 附加信息

[TCP环境配置不对.zip](https://github.com/metersphere/metersphere/files/8760711/TCP.zip)

**Comment by zyyfit** [comment]
1.20.4修复了几个tcp的问题，这个问题应该也一起修了，等升级后再试试还会不会复现
相关问题 https://github.com/metersphere/metersphere/issues/13897
