### ISSUE TITLE
[BUG]TCP接口定义中的环境信息过一段时间会失效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13897]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

TCP接口定义中的环境信息过一段时间会失效

### 重现步骤

1.新建TCP接口，有两个运行环境，每个环境中都有TCP配置，分别使用3000和5000端口
2.一开始调试正常，使用了选择的TCP配置
3.过一段时间再重新打开接口定义，在test中直接测试
4.明明基础信息和右上角都有环境信息，但是测试的时候，控制台显示没有带上任何TCP的IP和端口信息
![image](https://user-images.githubusercontent.com/88763608/169979280-ebfdfc97-3169-42f5-8544-1e924560969b.png)

### 期待的正确结果

使用基础信息中选择的环境中的TCP请求配置

**Comment by zyyfit** [comment]
过一段时间大概是过了多久呢？确定中间没有其他人动过这个环境吗？

**Comment by zyyfit** [comment]
好像是复现了

**Comment by zyyfit** [comment]
1.20.4已修复，请升级后验证
