### ISSUE TITLE
自定义脚本中的回调方法得不到执行，或者只能执行一部分？

### ISSUE THREAD

**Issue by MoseChen** [metersphere/metersphere#13890]
### 请描述您的问题

ATT。
怀疑是当前BeanShell执行完成(注册了回调)后，其BshScriptEngine所在的的容器被销毁；导致后续虽然有事件发生，但是对应的回调句柄已不存在。

如下图，line73注册回调成功后，当前步骤(自定义脚本)执行完成。后续步骤虽然触发了事件，但是对应的回调方法中的信息(line65，line66)无法输出到控制台中，line65偶发性可以输出。
![image](https://user-images.githubusercontent.com/11345202/169951609-c47c7fb9-7a1a-4a20-8e03-e3db39d42508.png)

**Comment by fit2-zhao** [comment]
@MoseChen 看一下控制台是否有错误信息；应该是某行异常了吧。
