### ISSUE TITLE
[BUG]在前置处理器中，通过sampler.getArguments()获取Get方法的Query参数获取不到

### ISSUE THREAD

**Issue by taizione** [metersphere/metersphere#13892]
### 联系方式

taizione@gmail.com

### MeterSphere 版本

latest

### 使用外置数据库

否

### 问题描述

import org.apache.jmeter.config.Arguments;
import java.util.Map.Entry;
下面的脚本在Jmeter上可以获取到Get方法时Query的参数的，但是在ms的前置处理器上获取不到
Arguments args = sampler.getArguments();
Map map = args.getArgumentsAsMap();
log.info("======="+map.size());
log.info("==============:"+args.getClass().toString());
Iterator itor = map.entrySet().iterator();
while(itor.hasNext()){
	 Entry entry = (Entry) itor.next();
	 log.info("==========key:"+entry.getKey());  
}

### 重现步骤

见问题描述

**Comment by zrfit** [comment]
您好，是否可以将接口文件导出我们尝试复现。
