### ISSUE TITLE
[BUG] [企业用户] 方法是DELETE时，发送请求会丢失body

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13905]
### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/170001955-95650a8e-d3e8-48c8-9874-f8ba686aaa9e.png)
![image](https://user-images.githubusercontent.com/103017812/170001971-da820096-d039-4713-b0fc-a80d58507256.png)
![image](https://user-images.githubusercontent.com/103017812/170001991-51e0f5d5-ee6c-4008-a9b8-7ec7ef890d6b.png)

### 重现步骤

API用例和场景用例都有此类问题！

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts没有复现，请升级到最新版本试试吧

**Comment by sac911** [comment]
升级到1.20.3测试没有这个问题了。请关闭。
