### ISSUE TITLE
[BUG]场景接口里面的自定义变量重复，值错误覆盖

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#13902]
### 联系方式

18311441708

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

场景中，前置/后置sql中自定义变量的变量名一致，值将错误覆盖，没有做到接口变量隔离，非全局变量

### 重现步骤

<img width="911" alt="1653383236(1)" src="https://user-images.githubusercontent.com/103925124/169994950-5497afaa-156a-4807-9250-543dea0e808c.png">
某一场景中
某一接口前置sql，自定义变量为id 值为aaaa
某一接口前置sql，自定义变量为id 值为bbbb
某接口请求体中引用此变量：
<img width="553" alt="1653383497(1)" src="https://user-images.githubusercontent.com/103925124/169995838-1ea7d3e9-fa88-4565-886e-f65c256ca35c.png">
此时该接口请求内容中id为最终覆盖值
<img width="718" alt="1653383558(1)" src="https://user-images.githubusercontent.com/103925124/169996010-77328d62-e25b-455b-b250-0b2dae002b3b.png">

### 期待的正确结果

前置/后置sql中自定义的变量，不被覆盖，被应用于本接口

**Comment by zyyfit** [comment]
您好，虽然是在前后置脚本中各自设置了变量，但是这是在一个场景中，目前一个场景里不支持设置同名变量
另外，如果是在单条用例中，也是不支持这样同名不同值的变量的
