### ISSUE TITLE
[QUESTION]1.7.1release版本升级backend数据migrationV68错误

### ISSUE THREAD

**Issue by password36** [metersphere/metersphere#1390]
**请描述您的问题.**
升级1.7.1离线安装版本，执行数据库升级SQL错误导致升级失败，server容器无法启动。
版本：1.7.1离线全量安装版本，使用外部mysql数据库，数据库表全清空的情况下安装也无法成功。
看报错sql是子查询groupby的问题，这个有什么方法能修改下让升级通过么。
Migration V68__modify_api_test_case.sql failed
o.f.c.i.s.DefaultSqlScriptExecutor ? - DB: 'metersphere.api_definition_exec_result.status' isn't in GROUP BY (SQL State: 42000 - Error Code: 1055)
错误SQL：
----------------------------------------------
SQL State  : 42000
Error Code : 1055
Message    : 'metersphere.api_definition_exec_result.status' isn't in GROUP BY
Location   : db/migration/V68__modify_api_test_case.sql (/deployments/file:/opt/apps/backend-1.7.jar!/BOOT-INF/classes!/db/migration/V68__modify_api_test_case.sql)
Line       : 4
Statement  : UPDATE api_test_case tt
INNER JOIN (
        SELECT
                atc.id,
                ader.id AS result_id
        FROM
                api_test_case atc
                LEFT JOIN USER u1 ON atc.create_user_id = u1.id
                LEFT JOIN USER u2 ON atc.update_user_id = u2.id
                LEFT JOIN (
                **SELECT
                        max( create_time ) create_time,
                        STATUS,
                        id,
                        resource_id
                FROM
                        api_definition_exec_result
                GROUP BY
                        resource_id**
                ) AS ader ON atc.id = ader.resource_id
        ) tc
        SET tt.last_result_id = tc.result_id
WHERE
        tt.id = tc.id

**Comment by password36** [comment]
这个修复了么？V1.7.3得离线安装包还是报数据合并V68得错误。，离线安装包没法升级到最新版本

**Comment by wangzhen-fit2cloud** [comment]
你好，数据库配置变更失败需要手动处理。请确保 https://github.com/metersphere/metersphere/blob/master/backend/src/main/resources/db/migration/V68__modify_api_test_case.sql 中的 SQL 执行成功后，连接数据库，执行如下 SQL 后重启服务。
```sql
update metersphere_version set success='1' where version='68';
```

**Comment by password36** [comment]
升级V1.7.3版本后 io/metersphere/base/mapper/ext/ExtApiDefinitionExecResultMapper.xml里面的findFaliureCaseInfoByProjectIDAndExecuteTimeAndLimitNumber这个SQL多处GROUP BY都缺少字段，在新版主界面就报错了。
金融行业相关，无法使用在线版本，只能通过离线升级，是否是离线升级包和在线下载的编译方式不同导致？
