### ISSUE TITLE
UI自动化使用本地模式调试场景涉及到输入本地文件时无法识别[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#13904]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

UI 自动化使用本地模式调试场景涉及到输入本地文件时无法识别，报错如下
![image](https://user-images.githubusercontent.com/35896106/169997878-da9d27bd-fb31-4665-9cfc-ab8585f01065.png)
使用 Selenium ide是可以自动识别的，如下：
![image](https://user-images.githubusercontent.com/35896106/169998253-c5a9f256-6ad9-4d80-b151-467b7c4e94d6.png)

### 重现步骤

1、导入通过Selenium ide录制好的场景
2、不勾选性能模式，通过本地模式调试模式执行此场景
3、勾选性能模式，通过本地模式调试模式执行此场景
4、查看执行结果，发现两种模式下涉及到输入本地文件的都无法识别文件路径

### 期待的正确结果

可以正常识别本地文件

### 附加信息

附：导出的场景文件
[导出场景文件.zip](https://github.com/metersphere/metersphere/files/8761377/default.zip)

**Comment by zrfit** [comment]
v1.20.5-lts版本已修复该问题。
