### ISSUE TITLE
[BUG]ms-ui自动化性能模式不支持只对失败的步骤进行截图

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#13901]
### 联系方式

guoweikang@weilaninfo.com

### MeterSphere 版本

1.20.3

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/85992665/169995899-00258bb3-c851-468e-b2b7-4965e302f2f7.png)

### 重现步骤

ms-ui自动化性能模式不支持只对失败的步骤进行截图

**Comment by zrfit** [comment]
您好，图片看不清，请重新上传下，并且问题描述：ms-ui自动化性能模式不支持只对失败的步骤进行截图
没看明白，ui自动化勾选性能模式后，运行报告结果是不展示步骤截图的。

**Comment by Sensivitiry** [comment]
![image](https://user-images.githubusercontent.com/85992665/170158613-15f83e20-4913-4731-b700-9abd8784cfa1.png)

我更新了图片，你看下

**Comment by Sensivitiry** [comment]
没有勾选的

**Comment by Hyyfit** [comment]
感谢反馈，我们目前有在规划截图可配置的功能，后续会支持 全部步骤截图/失败截图/配置关键节点截图等

**Comment by zrfit** [comment]
v2.1.0已经增加截图配置，可根据场景需要配置截图方式。
