### ISSUE TITLE
[BUG]升级到最新版本，Redis的key会失效，需要重新msctl reload才正常

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13913]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

升级问题：升级到最新版本，Redis的key失效，需要卸载，然后在msctl reload 才正常

### 重现步骤

升级报错截图：
![image](https://user-images.githubusercontent.com/15188833/170023935-1035060e-069f-47c9-bbaa-727a150b9f5b.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，不需要卸载啥。。
在redis里面执行如下命令即可：
docker exec -it redis bash
redlis-cli auth _redis密码_ flushdb
