### ISSUE TITLE
[BUG]接口定义，在接口里使用前置脚本提取QUERY参数无效

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#13918]
### 联系方式

张树彬

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

接口定义，在接口和CASE里使用前置脚本提取QUERY参数无效；但使用快捷调试是有效的

### 重现步骤

1. 新建接口，保存
2. 添加正确的前置脚本提取QUERY参数
3. 执行结果未成功提取到QUERY参数
注：同样的接口、同样的脚本，在快捷调试里是可以成功取到的

脚本如下：
import org.apache.jmeter.config.Argument;
import org.apache.jmeter.config.Arguments;

Arguments args = sampler.getArguments();

it = args.iterator();

while(it.hasNext()){
    
    argument = it.next();
     
    String pair = argument.toString();
    
    log.info("----111111----"+pair);
}htt

### 期待的正确结果

除快捷调试外，在接口和CASE里也可以成功能使前置脚本取到QUERY参数

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/170055806-efe88503-2af9-485c-b190-2c9d785bae80.png)
![image](https://user-images.githubusercontent.com/77324661/170056176-575d0547-43d2-4bb8-97d4-d74476d19811.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个问题在后续版本有优化，query参数我们加到url里面的，需要解析url 提取，前置脚本得改下

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts已修改
