### ISSUE TITLE
[FEATURE]在未来有没有可能把UI自动化的基础功能下放给社区版本？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13919]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

在未来有没有可能把UI自动化的基础功能下放给社区版本？
我目前对UI自动化的需求是可编写，可管理，可定时运行就行，未来有可能下放功能给社区版本吗？

**Comment by Hyyfit** [comment]
UI是我们今年的一个大的功能，还在完善中，所以暂时还没有计划开源，以后企业版的功能有可能会开源。
