### ISSUE TITLE
[BUG]ui-场景执行关闭了性能测试模式，执行页面任务等很久就不出报告，查看任务中心实际已经执行完了

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#13927]
### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

问题：ui-场景执行关闭了性能测试模式，执行页面任务等很久就不出报告，查看任务中心实际已经执行完了

### 重现步骤

如图：ui自动化选择场景步骤较长（二十几个步骤）的用例执行，执行页面一直在转圈登录3min也不出来，查看任务中心实际已经执行成功了
<img width="959" alt="一直在执行转圈圈" src="https://user-images.githubusercontent.com/43202800/170169356-7c82dcf0-a53c-4e6f-9352-61306a6f60f3.png">
<img width="960" alt="实际已经执行成功了" src="https://user-images.githubusercontent.com/43202800/170169653-b766042d-0c6b-4330-a67e-48dc5e23def3.png">

### 期待的正确结果

执行完之后输出报告

**Comment by xhy12** [comment]
脚本见附件


Flakes
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]ui-场景执行关闭了性能测试模式，执行页面任务等很久就不出报告，查看任务中心实际已经执行完了 (Issue #13927)





 
您好，未复现该问题，能否将场景导出我们尝试复现。

**Comment by xhy12** [comment]
请用qq邮箱看下，这个.side文件传不上git





Flakes
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月31日(星期二) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]ui-场景执行关闭了性能测试模式，执行页面任务等很久就不出报告，查看任务中心实际已经执行完了 (Issue #13927)





 
没看到有附件文件呢，请再上传下。

**Comment by zrfit** [comment]
该问题已复现，后续版本修复。
