### ISSUE TITLE
[BUG]ui自动化，场景A引用了一个步骤场景B,点击查看B的场景设置有蒙层不加载内容

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#13928]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

ui自动化，场景A引用了一个步骤场景B,点击查看B的场景设置有蒙层不加载内容

### 重现步骤

ui自动化，场景A引用了一个步骤场景B,点击查看B的场景设置有蒙层不加载内容

见录屏
<img width="960" alt="点场景变量不加载" src="https://user-images.githubusercontent.com/43202800/170171266-aea606e5-85fb-4b92-b0b4-ef2df5a55a31.png">

https://user-images.githubusercontent.com/43202800/170171227-616e4441-7ca8-4056-9a47-7efe73b190a7.mp4

**Comment by ltfit** [comment]
感谢反馈 已知问题 下个版本会修复

**Comment by ltfit** [comment]
你好 v1.20.4-lts  此版本已解决该问题   升级下
