### ISSUE TITLE
目前最新版本的metersphere平台UI测试模块的功能新增建议

### ISSUE THREAD

**Issue by Cody6S** [metersphere/metersphere#13926]
### MeterSphere 版本

版本:   v1.20.2-lts-0f489ee9

### 请描述您的需求或者改进建议

关于ui测试目前来说一些基础的元素定位可以实现无误，但是关于有些存在于其他frame的元素目前无法进行识别，建议在右侧操作栏新增切换frame的功能（绝大多数WEB端都会涉及到frame切换定位的问题）。希望尽快完成功能新增！！！！

祝metersphere平台越来越好！

**Comment by Hyyfit** [comment]
您好，目前已经有frame功能，在浏览器操作--选择内嵌网页 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/95834771/170169508-4b6ae741-c5d9-44b7-a27e-fb9cf30876bb.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/95834771/170169631-db590d6c-1e61-43ea-b1bf-daaebdf21c37.png">

**Comment by Cody6S** [comment]
非常感谢！！
