### ISSUE TITLE
[BUG]测试跟踪-测试计划-报告失败用例右侧信息显示空白

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#13923]
### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划-报告失败用例右侧信息显示空白
晚上20：00：00的定时任务执行。900多用例成功70多，剩下全失败，失败原因看不到

### 重现步骤

测试跟踪-测试计划-报告失败用例右侧信息显示空白
晚上20：00：00的定时任务执行。900多用例成功70多，剩下全失败，失败原因看不到

### 期待的正确结果

正确

### 附加信息

![WVRDL6RALD_%Y3`J5%Q3MN9](https://user-images.githubusercontent.com/19423100/170154685-5b6dd7ce-1ef8-4f12-be91-a4543dde0a42.png)

**Comment by ltfit** [comment]
感谢反馈，下个版本修复

**Comment by ltfit** [comment]
感谢反馈 后续修复下

**Comment by ltfit** [comment]
你好 v1.20.4-lts  此版本已解决该问题   升级下
