### ISSUE TITLE
api修改路径后，用例路径也随之修改了，但是在case执行的时候还是原先的路径

### ISSUE THREAD

**Issue by xuewuhe** [metersphere/metersphere#1392]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.1v1.7.1
**Bug 描述**
简要描述您碰到的问题
api修改路径后，用例路径也随之修改了，但是在case执行的时候还是原先的路径
**Bug 重现步骤**
1.  修改api 路径
2. 执行用例
3. 查看请求内容
4. 请求路径是修改之前的路径

**期待的正确结果**
正确情况下应该是什么样的？
执行case的路径应该是修改之后的路径
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/64074745/106841809-c1ca5380-66dd-11eb-93ac-e4173d26baeb.png)

**Comment by Dyc2333** [comment]
同样的，希望可以提供同步按钮，将接口的改动同步到它的用例上。

**Comment by xulinde** [comment]
您好，接口定义变更，用例是不会变更的，接口用例那里有一个批量编辑的功能，可以单独对用例做变更
