### ISSUE TITLE
[BUG]接口自动化测试一直是执行失败，但是我手动点击可以执行成功

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13922]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

定时自动的执行结果：
![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/170075455-0bb78975-053e-41de-b230-c52164a9fdf8.jpg)
![QQ拼音截图未命名2](https://user-images.githubusercontent.com/38156471/170075508-0b703817-bd66-4e35-81e7-f51022b17eed.jpg)
手动的执行结果：
![QQ拼音截图未命名4](https://user-images.githubusercontent.com/38156471/170075562-ea9faebb-f7bd-49c0-8016-de68c4b8bac5.jpg)

### 重现步骤

每天定时都会收到失败的消息

### 期待的正确结果

定时自动像手动一样执行成功啊

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我看您是在saas版测试的吧，我在单机版环境和saas版都试了一下，是正常的，是所有场景都会这样吗？
![image](https://user-images.githubusercontent.com/73461316/170237978-4aefd33d-218c-4397-aaa1-84dfc5aa4fb5.png)

**Comment by YellCatt** [comment]
> 您好，没有复现这个问题，我看您是在saas版测试的吧，我在单机版环境和saas版都试了一下，是正常的，是所有场景都会这样吗？
> ![image](https://user-images.githubusercontent.com/73461316/170237978-4aefd33d-218c-4397-aaa1-84dfc5aa4fb5.png)

我只有一个场景，前几天一直出现这个问题，昨天晚上开始没有出现这种情况了
