### ISSUE TITLE
[QUESTION]如果MS版本升级，有没有一个全局的备份，之后我升级完，如果项目内容丢失，我直接导入就可以了？现在如果升级版本，需要做哪些备份工作？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13921]
### 请描述您的问题

如果MS版本升级，有没有一个全局的备份，之后我升级完，如果项目内容丢失，我直接导入就可以了？现在如果升级版本，需要做哪些备份工作？

**Comment by Hyyfit** [comment]
没有备份，升级版本不会丢失数据的。
如果有需要的话，也可以选择先备份数据库再升级。

**Comment by Hyyfit** [comment]
这个可以自己百度搜一下文档。
