### ISSUE TITLE
[FEATURE]把【参数设置】对话框中，MockJS方法和JMeter函数的列表选项显示区域扩展为一页，现在是半页

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#13933]
### MeterSphere 版本

v1.20.3

### 请描述您的需求或者改进建议

1. 扩展显示一页后，页面中不用拉下拉条就可以看到更多的选项。
2. 从显示的效果上，显示区域撑满1页，效果也会好些。

建议显示区域请见下图黑框标示区域。

<img width="868" alt="Screen Shot 2022-05-25 at 12 06 43 PM" src="https://user-images.githubusercontent.com/9998431/170264449-1d85a6e0-33a4-4cf5-add2-5fba0c469c96.png">

**Comment by Hyyfit** [comment]
您好呀，图片展示失败。麻烦再发一下图片

**Comment by Hyyfit** [comment]
感谢反馈，已规划优化。
