### ISSUE TITLE
[BUG]性能测试报告对比时，右侧Y轴的数据标尺不一致

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13948]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

性能测试报告对比时，左右两侧Y轴的数据标尺不一致，导致两份报告实际上数据差很多，但是曲线看起来差不多，为了方便对比，Y轴刻度应该尽量保持一致
![image](https://user-images.githubusercontent.com/88763608/170198428-9189f7d3-472c-4d92-a2a0-88bc3ac039aa.png)

### 重现步骤

1.分别执行两次性能测试，其中一次删除了jar包有报错，tps会比较低
2.将两次报告对比
3.发现TPS的Y轴刻度不一致，导致从曲线图不能直观的看出差距，还要通过对比Y轴刻度

### 期待的正确结果

报告对比时，左右Y轴刻度都应该尽量保持一致，这样对比效果更好。
问题来源：企业用户在对比时，看曲线还以为数据是差不多的，看到右边的Y轴才发现TPS相差挺大，下图是客户那边的对比效果
![12952ccb5b83df1893ad23f3abe2a92](https://user-images.githubusercontent.com/88763608/170199202-9e5a4ba5-41a1-44f9-b180-26e4e92cda44.jpg)

**Comment by ltfit** [comment]
感谢反馈 这个优化下

**Comment by liuruibin** [comment]
图表的绘制都是echarts自动进行的，如果我们固定x或y轴的显示范围会使图表显示很紧，对比差异较大的情况下显示很难看这个使用自适应的显示更加美观
