### ISSUE TITLE
关于UI测试运行完毕之后的步骤结果展示界面建议

### ISSUE THREAD

**Issue by Cody6S** [metersphere/metersphere#13944]
### MeterSphere 版本

版本:   v1.20.2-lts-0f489ee9

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/105691386/170192062-f8fe77ea-3cd5-4d26-80ef-4c66056c4ef6.png)

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/105691386/170192506-f2f660a2-3606-4802-a305-ff4742a2f2c1.png)

**Comment by Hyyfit** [comment]
非常感谢您的反馈，好的哦，在页面展示这一块，我们尽快优化～

**Comment by Cody6S** [comment]
握手~
