### ISSUE TITLE
[BUG]接口自动化中只要使用了groovy脚本，做性能测试必报“加载jar失败”

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#13947]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

否

### 问题描述

接口自动化或jmeter中使用groovy脚本，即使groovy脚本为空，导入性能测试也会报“加载jar失败”
可能原因：加载groovy某个内置方法失败了，附件有复现的接口自动化脚本

### 重现步骤

1.新建接口自动化场景，在场景中加任意请求，在请求前置脚本中添加空的groovy脚本
![image](https://user-images.githubusercontent.com/88763608/170196520-2395cd39-988e-461e-8cb6-f72a2dd78548.png)

2.一键转成性能测试，保存并执行
3.查看性能测试日志详情，每次执行线程都会报“加载jar失败”
<img width="847" alt="9f493f3e03d5fec6ac9b9d6bea43fa2" src="https://user-images.githubusercontent.com/88763608/170196080-f904765a-7890-4122-a1bf-cd990dc1628d.png">

### 期待的正确结果

不报错

### 附加信息

[Metersphere_Scenario_默认项目.zip](https://github.com/metersphere/metersphere/files/8768522/Metersphere_Scenario_.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
