### ISSUE TITLE
[BUG]mock环境请求体中Array未显示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#13952]
### 联系方式

18311441708

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

使用JSON-SCHEMA添加请求体内容，中包含array，保存好mock数据后，执行调试，返回的请求体中数据未包含array数据
<img width="960" alt="1653465357(1)" src="https://user-images.githubusercontent.com/103925124/170211133-c43926b8-397a-4631-80c6-de50a88d4cd4.png">
<img width="960" alt="1653465836(1)" src="https://user-images.githubusercontent.com/103925124/170212727-a30bfcdc-ad9b-41f8-8f6c-34bb322c2cfe.png">
![Uploading 1653465881(1).png…]()

### 重现步骤

随意选择一个接口，构造mock数据，包含array数据，保存后，进行接口调试，返回请求体中未包含array数据
刷新请求，刷新系统链接，均未显示
发给其他人查看是否有array数据，同事反馈，“不稳定，刚开始有几次也是没有array数据，后几次就有了”

### 期待的正确结果

如实际mock请求体中数据返回

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复，如果您着急用的话，可以在添加完mock期望的响应体后，把json-schema关掉。

**Comment by zyyfit** [comment]
1.20.5版本修复，请等待版本发布后验收
