### ISSUE TITLE
[BUG]断言响应体中array数据小于某数报错，断言失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#13953]
### 联系方式

18311441708

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

调试接口，增加JSONPath断言信息为  返回值中的array.size()<100,报错，断言失败
<img width="700" alt="5a407e021dba1d223ec5d9695fd8188" src="https://user-images.githubusercontent.com/103925124/170214678-9dfad751-4eb0-418f-96f7-16c0e0036928.png">

### 重现步骤

在接口或者场景增加JSONPath断言，JSONPath断言信息为  返回值中的array.size()<100,报错，断言失败

### 期待的正确结果

JSONPath断言信息为  返回值中的array.size()<100,不报错，断言成功

### 附加信息

JSONPath断言信息为  返回值中的array.size()=2  断言成功
JSONPath断言信息为  返回值中的array.size()>1  断言成功

只有小于是失败

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.6-lts版本中已修复
