### ISSUE TITLE
[BUG]设置接口URL不可重复，重复导入时接口用例重复生成

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1395]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091

**Bug 描述**
简要描述您碰到的问题
设置接口URL不可重复，重复导入时API未重复导入，CASE重复生成

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
是导入的postman吗
