### ISSUE TITLE
[BUG]执行性能测试，状态一直显示“Sarting”

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#13964]
### MeterSphere 版本

v1.18.2

### 使用外置数据库

否

### 问题描述

近期，有些用户反馈，执行性能测试，状态一直显示“Sarting”
![aebf835d0ae6df3b4d1e22c57108f55](https://user-images.githubusercontent.com/46479742/170228765-9e552df9-4b27-4b77-965a-5414b090b581.jpg)

### 重现步骤

![aebf835d0ae6df3b4d1e22c57108f55](https://user-images.githubusercontent.com/46479742/170228785-57768819-9ae8-4adb-b03b-d3bee38d6991.jpg)

**Comment by youliyuan-fit2cloud** [comment]
请先看下log 日志，ms-jmeter-run-log.log,info.log都看看，还不确定，把log上传上来，我们看看。
使用的是什么资源池？local，还是node ？

**Comment by Boylijun** [comment]
我昨天部署了1.19.3，用的同一台服务器的节点，也是一直显示starting，看了info是获取报告时空指针
13 - Method[getContent][get report result error]
2022-05-27 01:08:20,599 [XNIO-1 task-9] WARN  i.m.p.s.PerformanceReportService 113 - Method[getContent][get report result error]
2022-05-27 01:08:20,599 [XNIO-1 task-6] WARN  i.m.p.s.PerformanceReportService 113 - Method[getContent][get report result 
 Exception handling request to /performance/report/content/24317cae-c7bd-40bb-833e-ba3c71a9df48
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
