### ISSUE TITLE
[QUESTION]性能测试-可以链接压测节点的kafka成功，执行压测报错 Failed to connect to Kafka

### ISSUE THREAD

**Issue by fangfei8809** [metersphere/metersphere#13969]
### 请描述您的问题

]性能测试-可以链接压测节点的kafka成功，执行压测报错 Failed to connect to Kafka
![image](https://user-images.githubusercontent.com/106237521/170231749-0d71cbf6-59eb-4769-bef0-91e8768878af.png)
![image](https://user-images.githubusercontent.com/106237521/170231867-3f6c2e79-b1e1-4ee9-aae3-49a7be0316d5.png)
![image](https://user-images.githubusercontent.com/106237521/170232534-6ba081b8-006e-434b-be88-dacbdb3deeb7.png)

**Comment by youliyuan-fit2cloud** [comment]
请参考该文档排查一下：https://metersphere.io/docs/faq/load_test/#kafka
