### ISSUE TITLE
[BUG]请求体JSON数据带有转义符，使用变量会导致发出的请求体发生变化，导致请求失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#13967]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.3-LTS

### 使用外置数据库

否

### 问题描述

请求体JSON数据带有转义符，使用变量会导致发出的请求体发生变化，导致请求失败

### 重现步骤

1、发起一个POST类型的CASE或者接口
2、请求体使用JSON，并加上一个字段为：
"orderLineFeatures": "{\"CHANNEL_BUY_COUNT_INFO\":\"{\\\"buyInfo\\\":{\\\"121337-K\\\":2}}\"}",
3、场景或者环境配置中定义一个变量
4、在第二步中某个字段使用3中定义的变量
5、发起请求，观察请求内容
6、把变量用常量替换，发起请求，观察请求内容
7、对比第五步和第六步的请求内容即可

### 附加信息

注意反斜杠

JSON请求体中使用变量时：

<img width="913" alt="image" src="https://user-images.githubusercontent.com/32027713/170249578-4fa14d17-4b33-456c-9f14-b4c18b0aa90d.png">

JSON请求体使用常量时：
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/32027713/170249785-5a8b65ad-7688-4122-b91e-f5631357ecab.png">

**Comment by fit2-zhao** [comment]
@dashenyucainiao  您好，阅读了您的问题后，不太清楚您使用场景是什么，如果是为了转译 引号 一个“ \“ 就可以；如果为了把 \ 也当成字符放到请求中 可以使用变量方式；Jmeter 测试引擎变量方式入参数会完整放到请求中。
