### ISSUE TITLE
[BUG]脑图的放大缩小功能，现在是反向操作（双指往外拉是缩小，往内拉是放大）

### ISSUE THREAD

**Issue by caozhengbo** [metersphere/metersphere#13963]
### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

脑图的放大缩小功能，现在是反向操作（双指往外拉是缩小，往内拉是放大）
![Uploading image.png…]()

### 重现步骤

使用用例列表中的脑图功能，在mac触控板上进行缩放
现在是反向操作，触控板放大脑图会缩小，触控板缩小脑图会放大

**Comment by youliyuan-fit2cloud** [comment]
@ ~ @ 这都被发现了。。。后续版本优化一下子

**Comment by caozhengbo** [comment]
哈哈哈 辛苦大佬

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts 中已修复
