### ISSUE TITLE
[BUG] 接口测试-断言接送jsonpath 失效

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#13961]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

描述：场景  case使用断言：jsonPath 大于时 判断失效

### 重现步骤

result返回结果展示：

![image](https://user-images.githubusercontent.com/15188833/170226064-1a8c5e9b-6db0-4e04-9640-7e530a8f9821.png)

2个场景断言：
    A场景：
![image](https://user-images.githubusercontent.com/15188833/170226236-1e3405d8-14b5-45f2-8651-1d0348f2b98a.png)

   B场景：
![image](https://user-images.githubusercontent.com/15188833/170226289-4e4d4f3b-3ee0-4845-8783-5fc13fd103cc.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.6-lts版本中已修复
