### ISSUE TITLE
[BUG]测试场景中，若请求循环次数大于CSV文件中数据，则CSV文件中数据最后一条数据取不到值

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1396]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题
接口自动化场景中,变量从csv文件中取值，
当请求中设置的循环次数大于csv中的数据，则取不到最后一条数据
当请求中设置的循环次数=csv文件中的数据数+1，则可以取到最后一条
如： 
csv中数据是5条，循环次数设置4，最后一条可以取到
csv中数据是5条，循环次数设置8，最后一条取不到（csv中第5条数据）

**Bug 重现步骤**
1.  执行接口自动化场景（场景中引用idNum变量，idNum数据从csv读取）
2. 查看测试报告
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
循环次数大于CSV中数据，则最后一条可以取到值

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106855614-28f50180-66f8-11eb-9f5e-b85ce1b88d97.png)
![image](https://user-images.githubusercontent.com/55734318/106855713-5c379080-66f8-11eb-8f4a-9021da484afa.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
