### ISSUE TITLE
测试计划里面，用例的表头字段能自己添加吗。

### ISSUE THREAD

**Issue by astroxing** [metersphere/metersphere#13972]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/65709435/170234288-aa501588-2288-422a-8292-f1837367ae3a.png)

**Comment by Hyyfit** [comment]
测试计划暂不支持自定义字段。
后续会支持自定义字段，已规划，待排期哦

**Comment by Hyyfit** [comment]
不可以的，暂不支持自定义字段

**Comment by astroxing** [comment]
> 不可以的，暂不支持自定义字段

好的，谢谢
