### ISSUE TITLE
[QUESTION]自動化執行腳本，生成的報告中展示的步驟不是有序的？

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1397]
**请描述您的问题.**
比如場景A包含兩個子場景：
      場景1
           步驟1.1
           步驟1.2
      場景2
           步驟2.1
           步驟2.2
在另一個場景B中連續執行兩次場景A，最後報告展示的內容是
場景1
    步驟1.1
    步驟1.2
    步驟1.1
    步驟1.2

場景2
    步驟2.1
    步驟2.2
    步驟2.1
    步驟2.2

而不是如下按執行順序？
場景1
    步驟1.1
    步驟1.2
場景2
    步驟2.1
    步驟2.2
場景1
    步驟1.1
    步驟1.2
場景2
    步驟2.1
    步驟2.2

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现该问题，预计下个版本v1.8解决。

**Comment by xulinde** [comment]
和#1399重复
