### ISSUE TITLE
[BUG][cloud]执行测试计划，使用默认资源池执行不符合预期，不使用资源池执行通过

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#13977]
### MeterSphere 版本

cloud环境 v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

使用cloud版本，执行测试计划（测试计划中只有单接口测试用例），选择默认资源池执行会失败，失败原因是：该接口请求的数据是需要上一个接口返回的数据（将该字段已经存为环境变量），但是实际拿起请求的值不是本次执行拿到的结果，而是之前执行存的结果。如果不用资源池运行就正常可以通过

1.使用默认资源池运行
<img width="533" alt="image" src="https://user-images.githubusercontent.com/104493699/170245051-e175642d-070d-4461-a1f6-c48e7f184bf1.png">
2.请求返回的id
<img width="942" alt="image" src="https://user-images.githubusercontent.com/104493699/170245071-b1bfac49-e1c4-4d77-bb47-dfe650784a27.png">
这个接口的执行时间
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/104493699/170245111-662c68ab-9578-498a-8d52-278c425368b2.png">
3.修改文章草稿为发布状态会拿到这个id当请求参数，但是实际用的是21，不是上一次请求存的环境变量
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/104493699/170245150-de99b559-b0d6-4fd2-9b12-758fafc11114.png">
这个接口的执行时间
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/104493699/170245173-df3bc4a0-fb77-4a74-8da6-ea5794697fc7.png">
4.不使用资源池，可执行成功
<img width="999" alt="image" src="https://user-images.githubusercontent.com/104493699/170245203-37457f10-3e23-4db2-bf02-5aa60a5b1450.png">
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/104493699/170245196-cacfcdc3-e88b-437a-b708-57abd0c606ac.png">

### 重现步骤

【cloud环境--空间【F2C-South】
测试计划：jenkins调用测试计划
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/104493699/170245784-238a42f1-8db6-4746-b48f-e483870d10c7.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.4-lts版本中已修复
