### ISSUE TITLE
[FEATURE]接口测试CASE中，返回值是否可以全部一键全部断言？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#13982]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

我的需求是这样的，我的接口返回的数据的字段特别多，可能有几十个，又涉及集合，都需要断言，是否可以添加一个按钮，让返回值是否可以全部一键全部断言？

**Comment by Hyyfit** [comment]
可以用json-文档结构断言
<img width="937" alt="image" src="https://user-images.githubusercontent.com/95834771/170404506-ddd8e0e2-60cb-4dc3-adcb-9e6b92c126b9.png">
