### ISSUE TITLE
[BUG]ui自动化执行失败，测试报告日志里显示“OK”

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#13983]
### MeterSphere 版本

v1.20.3

### 使用外置数据库

否

### 问题描述

ui自动化执行失败，测试报告日志里显示“OK”

### 重现步骤

UI 自动化执行步骤，元素定位写错了，导致执行停止，查看测试报告，日志显示“OK”
![image](https://user-images.githubusercontent.com/46479742/170396266-0c747a51-deea-41b0-aa5b-b5aa1e65e284.png)

**Comment by ltfit** [comment]
你好 你的文件能否导出下 我这边复现下
