### ISSUE TITLE
[FEATURE] 父目录下的用例无法单独显示

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13981]
### MeterSphere 版本

1.20.3

### 请描述您的需求或者改进建议

用例目录下无法单独显示父目录下的用例，也就是说这些用例和父目录下子目录中的case混合在一起显示。
这里会造成混乱。

**Comment by Hyyfit** [comment]
目前的设计如此。可以将再建一个目录将用例放进去，就不会混乱了。
