### ISSUE TITLE
[BUG]接口自动化定时任务偶有接口未被执行

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#13984]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

定时任务执行后，偶现接口未被执行的情况，单独调试或重新执行是正常可以全执行。

### 重现步骤

多个项目都创建测试计划，计划中启动接口自动化定时任务，每天定时同一时间串行执行，部分场景中某些接口未被执行。

### 期待的正确结果

所有接口根据场景正常执行

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/170401303-a6576e01-fce6-472f-9af6-9669e7b7509f.png)
![image](https://user-images.githubusercontent.com/40912823/170401382-55487946-87e3-4cd9-93a9-6026fe431552.png)

**Comment by zyyfit** [comment]
您好，我用最新版设置了几个测试计划每天同一时间定时执行，没有出现不执行某个用例的问题，您看看场景里是否有什么特殊配制？或者升级到最新版试试？升级之前请做好备份

**Comment by wszbc** [comment]
> 您好，我用最新版设置了几个测试计划每天同一时间定时执行，没有出现不执行某个用例的问题，您看看场景里是否有什么特殊配制？或者升级到最新版试试？升级之前请做好备份

没有什么特殊配置，不是一定出现，我这也是偶尔出现，看了下日志，不执行时的日志里面一定会出现global_lock_a45d1fa1这一类日志，之前的图里也有，不知道这个警告为什么会出现，单独跑不会出现，感觉还是并发导致了系统层出现了某种锁导致的

**Comment by zyyfit** [comment]
> > 您好，我用最新版设置了几个测试计划每天同一时间定时执行，没有出现不执行某个用例的问题，您看看场景里是否有什么特殊配制？或者升级到最新版试试？升级之前请做好备份
> 
> 没有什么特殊配置，不是一定出现，我这也是偶尔出现，看了下日志，不执行时的日志里面一定会出现Lock global_lock_a45d1fa1这一类日志，之前的图里也有，不知道这个警告为什么会出现，单独跑不会出现，感觉还是并发导致了系统层出现了某种锁导致的

我们的同事说这个问题解决了，请升级到最新版1.20.4吧
