### ISSUE TITLE
[FEATURE]建议支持多场景批量执行及场景执行顺序设置

### ISSUE THREAD

**Issue by Big9Sun** [metersphere/metersphere#13985]
### MeterSphere 版本

v1.20.1-lts-64d951ea

### 请描述您的需求或者改进建议

UI自动化里期望多选多个场景批量执行，挨个点击场景去执行其实也耗费不少人力
另外，批量选择的场景建议支持设置每个场景的执行顺序，因为有时候不同场景之间存在顺序上的要求

### 附加信息

![image](https://user-images.githubusercontent.com/52018828/170406862-08c9ef7e-431b-42f3-a175-39171ba8a46f.png)

**Comment by Hyyfit** [comment]
您好，我们2.0的功能会上线UI批量执行及UI加入测试计划中。在测试计划中执行可以调整顺序，我们的执行方式是按顺序串行执行。
