### ISSUE TITLE
[BUG] [企业用户] 导入场景用例，如果被导入项目中有与被导入用例同名的文件夹，导入的用例会进入非指定文件夹

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#13980]
### MeterSphere 版本

1.20.3

### 使用外置数据库

是

### 问题描述

1. 指定导入文件夹
2. 导入场景用例
3. 指定文件夹中有部分用例丢失（整个文件夹）
4. 检测场景用例目录，发现丢失的文件夹被导入到同名的文件夹下（非指定）

### 重现步骤

1. 指定导入文件夹
2. 导入场景用例
3. 指定文件夹中有部分用例丢失（整个文件夹）
4. 检测场景用例目录，发现丢失的文件夹被导入到同名的文件夹下（非指定）

**Comment by youliyuan-fit2cloud** [comment]
你好，导入的逻辑是会先找到有没有同名且同级别的模块，如果有，就用找到的，即使选择了其它模块，也会导入到已存在的模块下。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #13723
