### ISSUE TITLE
[BUG]ui自动化 执行结果是成功的，但是列表显示失败

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#13995]
### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

ui自动化 执行结果是成功的，但是列表显示失败

### 重现步骤

ui自动化 执行结果是成功的，但是列表显示失败

该脚本调试过几次。中途有失败但是最终是调通的

间录屏
<img width="955" alt="执行结果是成功的，但是列表显示失败" src="https://user-images.githubusercontent.com/43202800/170425631-73095e5e-225b-480b-9bd6-239dbcb254c4.png">

https://user-images.githubusercontent.com/43202800/170425577-61677c49-4acd-4d03-820f-73bb0e5df9f6.mp4

### 期待的正确结果

执行完成全部通过 状态应该成功

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
经过排查我们发现这种情况应该是场景里有前后置脚本，执行失败了，然后步骤没有失败的，所以报告就显示成了失败。
1.20.5版本把报告状态和步骤状态统一了，就是如果有前后置脚本失败，只要步骤没有失败的，报告就会显示成功。请等待发版后验收。
后面的版本还会对前后置脚本的状态显示进行优化。
