### ISSUE TITLE
[BUG]測試報告展示順序問題

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1399]
**MeterSphere 版本**
   MeterSphere v1.7.1

**Bug 描述**
  自動化執行報告與實際場景執行順序不一致

**Bug 重现步骤**
    場景1
    場景2 引用 場景1
    場景3 引用 場景2
    場景4 引用 場景3
    場景5 引用 場景4
    最後執行場景5，執行報告展示的順序如下：
    場景1
    場景2
    場景3
    場景5
    場景4

**期待的正确结果**
    場景1
    場景2
    場景3
    場景4
    場景5

**截图**
如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
@SloanGao 您好，假如场景1 下有多个请求，场景2 引用1 ，场景3引用2 以此类推 都只是 引用 ，在2，3 场景中 没有其他请求，那么最终结果其实只有 场景1 下所有请求结果，不会呈现成 1，2，3，4，5 这种 顺序。
