### ISSUE TITLE
性能测试->测试报告数据不准确

### ISSUE THREAD

**Issue by Eric-Hyiboo** [metersphere/metersphere#13994]
### 联系方式

yibo.huang@fit2cloud.com

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

性能测试->测试报告中，测试详情与请求统计中，同一请求的同一字段数值有时候会不一致

### 重现步骤

创建一个性能测试，执行完成之后查看测试报告，查看测试详情与请求统计中同一请求的响应数值。

### 期待的正确结果

同一请求的响应数值在测试详情与请求统计中的统计结果一样
<img width="1906" alt="WechatIMG468" src="https://user-images.githubusercontent.com/83943743/170421860-02b5dfe9-0569-41ad-9a37-0fabd5497149.png">
<img width="1881" alt="WechatIMG30" src="https://user-images.githubusercontent.com/83943743/170422145-dfe213f3-0638-4cbf-95a6-3eb7c96a61fa.png">

### 相关日志输出

```shell
--
```

### 附加信息

![WechatIMG13432](https://user-images.githubusercontent.com/83943743/170421585-cfbc6fda-5ad8-45f9-93ec-d59382018e31.png)
![WechatIMG13433](https://user-images.githubusercontent.com/83943743/170421599-842d3f89-7c73-4730-8bd2-cdd2fc7fa303.png)

**Comment by liuruibin** [comment]
请求统计中的数据是直接用jmeter的jtl计算出的，图表下的表格数据是图标数值计算的二阶数据，两者确实存在误差。
