### ISSUE TITLE
[FEATURE]metersphere访问方式及账号密码

### ISSUE THREAD

**Issue by ningdaqing** [metersphere/metersphere#14]
**请描述您的需求或者改进建议.**
1）官网上没有安装后访问方式和默认的访问
2）安装出错后，排查问题访问方式不会在屏幕回显

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，已在文档中增加默认的访问方式提示

**Comment by wangzhen-fit2cloud** [comment]
v1.0.1 版本中已修复
