### ISSUE TITLE
[FEATURE]helm chart包中busybox和kubectl镜像更改建议

### ISSUE THREAD

**Issue by mfanoffice** [metersphere/metersphere#14002]
### MeterSphere 版本

v1.20.3-lts

### 请描述您的需求或者改进建议

使用helm chart在离线环境k8s中部署时，经常会遇到无法找到busybox和kubectl镜像的报错，这时需要将busybox和kubectl镜像上传到每个k8s节点，或者修改每个chart包中的yaml。

### 请描述你建议的实现方案

建议将busybox和kubectl镜像通过变量统一定义镜像地址，如果离线环境只需修改一个位置即可。

**Comment by Hyyfit** [comment]
感谢反馈，待调研后确定。

**Comment by Hyyfit** [comment]
感谢反馈，我们还需要调研讨论一下。
