### ISSUE TITLE
[BUG]用例评审，超过10条用例，第10条用例评审通过，无法自动加载下一条

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#14003]
### MeterSphere 版本

v1.20.3

### 使用外置数据库

否

### 问题描述

用例评审，超过10条用例，第10条用例评审通过，无法自动加载下一条

### 重现步骤

用例评审，超过10条用例，第10条用例评审通过，无法自动加载下一条

### 期待的正确结果

用例评审，评审用例超过10条，第10条用例评审通过，第11条用例无法自动加载，需要手动点击下一条才能正常评审

**Comment by ltfit** [comment]
感谢反馈  下个版本修复下

**Comment by ltfit** [comment]
你好 v1.20.4 此版本已解决该问题   升级下
