### ISSUE TITLE
新建环境和接口测试用例保存后，后续修改环境的域名，然后之前保存的接口用例没有同步环境域名，还是用了修改之前的域名。。[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1400]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.7.1-66e9f091

**Bug 描述**
简要描述您碰到的问题
新建环境和接口测试用例保存后，然后修改环境的域名和环境名称，然后之前保存的接口用例没有同步环境域名和环境名称，还是用了修改之前的域名。。

**Bug 重现步骤**
1. 新建环境和接口测试用例保存后，然后修改环境的域名，然后之前保存的接口用例没有同步环境域名，还是用了修改之前的域名。。 也就是重新手动选择环境，重新保存，修改后的环境域名才会生效
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应该引用修改之后的环境域名，不然之前的接口用例都要手动修改

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
