### ISSUE TITLE
[BUG]测试用例更新覆盖问题汇总

### ISSUE THREAD

**Issue by xiangxiang19872222222** [metersphere/metersphere#14015]
### 联系方式

15151812035

### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 使用外置数据库

是

### 问题描述

1、测试用例步骤和测试用例结果无法通过用例更新修改成功（TEXT的方式）
2、测试用例导入更新后，需要退出登录或者切换不同目录后，才能看到更新内容

### 重现步骤

1、测试用例步骤和测试用例结果无法通过用例更新修改成功
2、测试用例导入更新后，需要退出登录或者切换不同目录后，才能看到更新内容

### 期待的正确结果

1、用例导入覆盖更新，步骤和结果也能够被修改成功
2、覆盖更新成功后，页面可以自动刷新，看到最新的修改

**Comment by ltfit** [comment]
你好 我这边没有 复现，用例能否导出下 ，或者可以升级到最新版本在看下
