### ISSUE TITLE
[BUG]SQL中新增API时，保存了一次，但新增了两条数据

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1401]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题
SQL中新增API时，保存1次，但新增了两条数据
**Bug 重现步骤**
1.  【*项目】-【SQL】-【新增api】
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106859696-593f9e80-66fe-11eb-9d97-13309e72b1aa.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改
