### ISSUE TITLE
[BUG]sql对API接口编辑后，更新为新接口时，保存报错 Error updating database

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1403]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  sql接口定义
2. 对定义完的接口，编辑-保存，在【测试】中选择“更新为新接口”
3. 在新的页面，点击 保存 按钮
4. 

**期待的正确结果**
正确情况下应该是什么样的？
sql请求 更新为新接口时，保存成功 

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106868842-3e732700-670a-11eb-9f73-4077a677291b.png)
![image](https://user-images.githubusercontent.com/55734318/106868972-5e0a4f80-670a-11eb-836a-5ad159e4b0c4.png)

**Comment by xulinde** [comment]
感谢您的反馈，这个问题已修复，1.8.0发布后您升级下就可以了
