### ISSUE TITLE
[FEATURE]接口测试中，对于必填的参数在参数表中是否可以置顶？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14032]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

接口测试中，对于必填的参数在参数表中是否可以置顶？
![QQ拼音截图未命名2](https://user-images.githubusercontent.com/38156471/170494625-9dd1bd09-d967-498a-a252-3c5e4c2a234a.jpg)

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
