### ISSUE TITLE
[FEATURE]UI测试在编写Case的时候步骤目录是否可以展示“断言”为二级目录？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14031]
### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 请描述您的需求或者改进建议

UI测试在编写Case的时候步骤目录是否可以展示“断言”为二级目录
![QQ拼音截图未命名](https://user-images.githubusercontent.com/38156471/170494406-bc8ef61c-880d-40ae-876c-782709faec5c.jpg)
？

**Comment by Hyyfit** [comment]
感谢反馈，目前的设计如此。
1.左侧树主要是展示步骤/场景的名称，我们的场景步骤都是可以多级展示，如果高级设置里的名称也再左侧展示，会有些凌乱。是否将高级设置里的操作也放在左侧，这里我们还得在调研一下。
2. 高级设置里操作可自定义名称，这个功能已经规划了，预计在近期的1、2个版本里会发布。
