### ISSUE TITLE
[BUG]单项同步（MS创建的缺陷同步禅道）-缺陷模版上有添加关联字段，MS更新缺陷状态同步失败，更新就直接更新状态为【激活】状态

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#14036]
### 联系方式

企业微信：MeterSphere 交流群35；李彬

### MeterSphere 版本

v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

1、MS创建的缺陷同步禅道成功，且状态更新为【激活】状态
2、MS更新缺陷状态为【已关闭】或者【已解决】，同步禅道失败，禅道缺陷状态就直接更新为【激活】状态。每次在MS更新任何数据，同步至禅道都是将bug状态更新为【激活】状态

## 前置条件
1、MS已连接禅道成功
2、禅道缺陷模版已设置关联字段

<img width="337" alt="2" src="https://user-images.githubusercontent.com/102306978/170607228-b8c942d3-7ea7-4b35-a631-32341a456989.png">

<img width="1093" alt="1" src="https://user-images.githubusercontent.com/102306978/170607244-6e3865b3-982f-4b96-8a56-b2302a37f782.png">

<img width="655" alt="3" src="https://user-images.githubusercontent.com/102306978/170607262-979cb85b-f42a-4dfa-bb45-73d233ee868d.png">

## 环境
禅道版本：开源版
[Designed by 艾体验](https://api.zentao.net/goto.php?item=aiux) [禅道12.5.2](https://www.zentao.net/)

### 重现步骤

1、在MS平台创建缺陷，且正常同步禅道，状态为【激活】状态
2、在MS平台只更新缺陷状态：将【激活】改为【已关闭】或者【已解决】
3、确认同步禅道bug更新数据包括状态

## 期望结果

禅道BUG状态更新为【已关闭】或者【已解决】

## 实际结果

禅道BUG状态更新为【激活】

**Comment by ltfit** [comment]
感谢反馈 后续版本修复下
