### ISSUE TITLE
[BUG]测试跟踪-->测试计划--->任务通知，添加钉钉机器人无法发送通知

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#14049]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

v1.20-ef632ef7

### 使用外置数据库

否

### 问题描述

路径：测试跟踪--测试计划-定时任务--任务通知
描述：
场景1：任务通知里面添加钉钉机器人，无法发送通知
场景2：项目设置--消息通知--测试计划，创建新通知：钉钉接收成功

### 重现步骤

场景1：测试计划里钉钉机器人配置--钉钉接收失败：
![image](https://user-images.githubusercontent.com/15188833/170640650-d1cb9dad-4637-41ca-8e11-2d4dba2cbe25.png)

场景2：项目设置--消息通知--测试计划，创建新通知：钉钉接收成功：
![image](https://user-images.githubusercontent.com/15188833/170640482-1fcd6b1a-f5b7-4586-9b51-39411940d86a.png)

**Comment by youliyuan-fit2cloud** [comment]
你好， 确认一下，项目设置里面的消息通知是测试计划定时任务的执行报告吗？怀疑在测试计划-定时任务-任务通知这里设置的定时任务没有正常开启

**Comment by startpjx** [comment]
明白了，测试计划里面的“任务通知”必须得添加定时任务才会有消息

**Comment by startpjx** [comment]
明白了，测试计划里面的“任务通知”必须得添加定时任务才会有消息
