### ISSUE TITLE
[BUG] UI-定位到的滑动条无法拖动

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#14042]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

客户登陆页面有个滑动条验证，登陆时要拖动滑动条验证通过，才能登陆
问题：
用selenium ide录制脚本，或者浏览器抓包元素定位到滑动条，做拖动无法验证通过

### 重现步骤

[](url)
![image](https://user-images.githubusercontent.com/45531073/170619281-f4a2cd2c-6fbb-4dbe-a9ad-a21d55909c15.png)

**Comment by ltfit** [comment]
你好 这个网站能否提供下 我这边尝试下

**Comment by Cody6S** [comment]
用seleniumIDE重现运行本地可以跑通吗？

**Comment by liushuneng** [comment]
可以

**Comment by liushuneng** [comment]
这个是企业用户的，不方便发出来，脚本和网址都给张杨杨了，你可以找她用，或者微信找我

**Comment by ltfit** [comment]
好的

**Comment by ltfit** [comment]
坐标需要手动调下 已于本人联系
