### ISSUE TITLE
[BUG]接口自动化，场景变量统计错误

### ISSUE THREAD

**Issue by suifengylc** [metersphere/metersphere#14047]
### MeterSphere 版本

v1.20.3

### 使用外置数据库

否

### 问题描述

接口自动化，场景变量统计错误
![image](https://user-images.githubusercontent.com/46479742/170626532-5b775d15-3d9a-4344-90c9-5eaa7cbe5328.png)

### 重现步骤

点击场景变量，查看场景变量
![image](https://user-images.githubusercontent.com/46479742/170626628-ec29faf1-f8c4-42de-acd9-eb16a48d9fc7.png)

**Comment by zrfit** [comment]
您好，未复现该问题，是否有其它操作步骤？或者把这个场景导出我们本地复现下。
