### ISSUE TITLE
[BUG]功能用例-左侧模块 移动文件夹报错：同层级下已存在该模块名称；实际上不存在同名模块

### ISSUE THREAD

**Issue by qclforever** [metersphere/metersphere#14048]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

功能用例-左侧模块 拖动文件夹报错：同层级下已存在该模块名称；实际上同一父目录下不存在同名模块

（如果是指的不同父目录下的同名模块，就更不合理了）

![image](https://user-images.githubusercontent.com/44964749/170637544-f6083f04-3756-4216-905d-06852adc05bf.png)

![image](https://user-images.githubusercontent.com/44964749/170636971-ec5b5d74-a014-4f7d-93cc-ccc86576a741.png)

### 重现步骤

-

**Comment by ltfit** [comment]
你好 这个问题你在最新版本修复了改问题，建议升级下
