### ISSUE TITLE
[BUG]从项目A导出的场景，导入到项目B，新建环境，输入URL，选择启用模块，在可选路径里，没有被导入场景所在模块路径。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#14046]
### 联系方式

王进

### MeterSphere 版本

1.20.3

### 使用外置数据库

否

### 问题描述

从项目A导出的场景，导入到项目B，新建环境，输入URL，选择启用模块，在可选路径里，没有被导入场景所在模块路径。

### 重现步骤

1. 下载下面的场景导出文件
链接: https://pan.baidu.com/s/1IaCvg6fABnhk_qHQS0gZhw 提取码: dcgu 
2. 打开ms，选择接口自动化，导入文件
![1653623793(1)](https://user-images.githubusercontent.com/76033005/170626323-abb24261-8cbb-4402-a594-da01a73cac2d.png)

3. 打开导入后的场景，选择环境配置，配置一个新环境
4. 输入url后，选择启用模块，然后检查可选模块路径，会发现没有 ebao等模块，可是在场景列表页左边可以看到有这些模块。
![1653623702](https://user-images.githubusercontent.com/76033005/170626088-0f30b58b-1f8a-4830-9565-e222c72cc9f9.png)

**Comment by zrfit** [comment]
您好，创建环境-模块中对应的模块树目录获取的是接口定义中的模块树的目录。
