### ISSUE TITLE
[BUG]建议【SQL】API和CASE列表中请求中去掉“列表”字段

### ISSUE THREAD

**Issue by ypyyx** [metersphere/metersphere#1405]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/55734318/106870927-a591db00-670c-11eb-98e4-40969ea45420.png)
![image](https://user-images.githubusercontent.com/55734318/106871033-c0fce600-670c-11eb-83fe-be7da2425613.png)

**Comment by xulinde** [comment]
您可以自定义表头字段，设置路径不显示在列表中
