### ISSUE TITLE
[BUG]接口定义下面的用例，若更改了接口定义中的路径，再执行用例，使用的请求路径仍是旧的

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1406]
**MeterSphere 版本**
   MeterSphere v1.7.1

**Bug 描述**
  更改了接口定义中的路径，再执行用例，使用的请求路径仍是旧的

**Bug 重现步骤**
1.  维护接口 和 用例
2. 更新接口路径
3. 执行接口下面的用例

**期待的正确结果**
 使用新的接口路径

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.2 已修改

**Comment by SloanGao** [comment]
已升級到1.7.3 還是有問題
