### ISSUE TITLE
[BUG]Jenkins指定计划里的任务为批量执行，但是实际运行结果是串行。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#14065]
### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

[BUG]Jenkins指定计划里的任务为批量执行，但是实际运行结果，应该还是串行。

### 重现步骤

1、Jenkins中指定计划任务为并行执行。如下图1。
2、任务执行，发现不是并行，还是串行。如下图2。

其他系统设置如下：如图3

### 期待的正确结果

Jenkins指定并行的任务，能并行执行。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/170659028-edc374ae-cc39-42dc-ba79-d22f7c351af0.png)

![image](https://user-images.githubusercontent.com/78218624/170659249-c5d918a2-7833-4da3-85df-d2b78db6a85c.png)

![image](https://user-images.githubusercontent.com/78218624/170659674-d3c0015c-c82b-4aee-920a-b0086bcb15fc.png)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.5-lts中修复了该问题~
