### ISSUE TITLE
[BUG]接口测试的断言中，当断言方式为JSONPath，断言关系为“包括”或“不成功”，断言结果不正确

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#14086]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.3

### 使用外置数据库

是

### 问题描述

在接口的断言功能中：同样的响应结果，同样的JSONPath，同样的值，当中间的断言关系为”包含“和”不包含“时，最后的断言结果都显示成功

### 重现步骤

请求方法：get 
URL: https://suggest.taobao.com/sug?q=a&code=utf-8
请求参数：如上
响应结果：{"result":[["安全裤","358303.9456514978"],["安踏","88232.75126638959"],["奥特曼","196593.49968624336"],["阿迪达斯","193772.62886884424"],["奥特曼卡片","63323.064103169454"],["airpods保护套","51105.23923858966"],["aj","81088.30624640429"],["奥特曼玩具","196639.995111886"],["a字裙","131668.50331362657"],["a字连衣裙","57212.73487756814"]]}

提取JSONPath为 `$.result[*][0]` 的结果如下：
![image](https://user-images.githubusercontent.com/31870788/170696186-9e8bf638-116e-413c-99b6-41efbbbd6847.png)

在断言TAG中：
第一次执行测试：断言关系为JSONPath为 `$.result[*][0]` 的值 不包含 aj
![image](https://user-images.githubusercontent.com/31870788/170696904-613a7d18-21f8-4170-bb50-4a81b91cdb27.png)

第二次执行测试：断言关系为JSONPath为 `$.result[*][0]` 的值 包含 aj
![image](https://user-images.githubusercontent.com/31870788/170696517-50d3c8fe-18e8-4a20-8245-216794114c18.png)

两次断言，都显示测试通过

### 期待的正确结果

断言关系为JSONPath为 `$.result[*][0]` 的值 不包含 aj时，断言结果应为失败

**Comment by youliyuan-fit2cloud** [comment]
v1.20.6-lts版本中已修复

**Comment by Faerie1999** [comment]
后续版本仍然存在这个问题
