### ISSUE TITLE
[BUG] 场景用例，调试页面接口返回时间超过设置的超时时间，但是一直是‘测试中‘

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14085]
### MeterSphere 版本

1.20.3

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/170691876-8f56c239-b601-421c-a6ef-f090daad2e7d.png)

### 重现步骤

场景用例，调试页面接口返回时间超过设置的超时时间，但是一直是‘测试中‘

**Comment by youliyuan-fit2cloud** [comment]
最新版本1.20.4-lts没有复现。升级一下吧

**Comment by 35plus** [comment]
liyuan，张总这边的情况是ms部署在新加坡aws上，测试有一部分在上海，有时候从上海到新加坡的网络响应波动幅度比较大，导致偶尔会出现请求发出去了，但是响应可能延迟比较长。ms接口自动化执行的时候，前端应该是有获取接口结果然后实时更新，但是当后端响应超时，那场景里步骤那个地方的结果就不会刷新。前端的同事应该知道这个事情。张总这边也不是必现，偶尔。 

帮忙问一下开发，这种情况应该怎么来提升用户体验。  每个场景步骤有连接超时和响应超时时间，如果都去设置可能用户体验太差了。看看开发有没有好的建议。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/174738137-57e6e413-c1be-4f3f-8ec2-418f6242eb02.png)

环境中可以设置全局响应超时时间
