### ISSUE TITLE
[BUG]场景用例执行过程中有较大概率卡死崩溃

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#14089]
### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

场景用例执行过程中有较大概率导致页面卡死崩溃
初步定位原因如下：
1. 场景用例较多，导致性能问题
2. 接口请求时间较长时较容易出现页面卡死崩溃

### 重现步骤

场景用例执行过程中有较大概率导致页面卡死崩溃
初步定位原因如下：
1. 场景用例较多，导致性能问题
2. 接口请求时间较长时较容易出现页面卡死崩溃

### 附加信息

![8ad17f7e8781cd5c820d968d32cbab9](https://user-images.githubusercontent.com/46745316/170722577-d589ee5e-bef9-4015-8eb8-e320e2ccea3b.png)

**Comment by youliyuan-fit2cloud** [comment]
最新版本1.20.4-lts没有遇到过，建议升级一下再试试，如果还有问题，请上传log并说明一下场景详情
