### ISSUE TITLE
[BUG]接口自动化中数据库请求的运行环境未与整个场景的运行环境联动改变

### ISSUE THREAD

**Issue by LizardYang** [metersphere/metersphere#14080]
### 联系方式

lizard@sztus.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

1.接口自动化中修改场景运行环境，该场景中数据库请求的运行环境未随之改变
![63cdcae358697df742c116f1baa077f](https://user-images.githubusercontent.com/46311914/170678664-b7e12179-0130-4cee-9581-7d80537b4d48.png)
![a36da0e29007fbff1f90758655c0237](https://user-images.githubusercontent.com/46311914/170678635-f71330a4-f9f2-48ac-a5e5-12dee843729b.png)
2.测试计划选择运行环境，对应场景数据库请求的运行环境依旧未变更
![image](https://user-images.githubusercontent.com/46311914/170679271-7b3f97e7-984e-47e3-8fa8-164bee7ee402.png)

### 重现步骤

接口测试-接口自动化-场景-添加自定义请求(SQL)-更改整个场景的运行环境-此自定义请求的运行环境未随之更新

### 期待的正确结果

数据库请求的运行环境能和整个场景的运行环境联动改变

**Comment by youliyuan-fit2cloud** [comment]
建议升级到最新版本1.20.4-lts吧，已修复该问题

**Comment by LizardYang** [comment]
已更新到最新版本 问题仍然存在

PS：若数据库连接未跟随场景环境联动，测试计划执行时选择环境就没有意义

**Comment by LizardYang** [comment]
> 建议升级到最新版本1.20.4-lts吧，已修复该问题

已更新到最新版本 问题仍然存在

PS：若数据库连接未跟随场景环境联动，测试计划执行时选择环境就没有意义

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/170922164-6a9f199c-1ac8-47e8-b693-0bd85eeab644.png)
