### ISSUE TITLE
[BUG]场景用例设置为关闭状态，再次编辑时仍为开启状态

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#14091]
### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

场景用例设置为关闭状态，再次编辑时仍为开启状态

### 重现步骤

1. 场景用例设置为关闭状态
2. 再次编辑时查看场景用例状态

### 期待的正确结果

场景用例设置为关闭状态，再次编辑时应为关闭状态

**Comment by youliyuan-fit2cloud** [comment]
没有复现，请贴上具体信息的棘突截图看下
