### ISSUE TITLE
[BUG]删除引用的数据源接口a或场景用例b时应同步删除场景用例A中引用的接口a或场景用例b

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#14090]
### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

[BUG]删除引用的数据源接口a或场景用例b时应同步删除场景用例A中引用的接口a或场景用例b

### 重现步骤

[BUG]
1. 删除引用的数据源接口a或场景用例b
2. 查看场景用例A中的引用的接口a或场景用例b

### 期待的正确结果

删除引用的数据源接口a或场景用例b时应同步删除场景用例A中引用的接口a或场景用例b

**Comment by youliyuan-fit2cloud** [comment]
目前设计如此，回收站也删除了吗？
