### ISSUE TITLE
[FEATURE]请考虑增加API 测试用例的文件夹管理功能

### ISSUE THREAD

**Issue by Jarod-Guo** [metersphere/metersphere#14099]
### MeterSphere 版本

 v1.20.2-lts-0f489ee9

### 请描述您的需求或者改进建议

鉴于某些api接口的测试用例会有多层级，且数量比较多，如100+；建议增加在某api接口下测试用例的文件夹功能。

**Comment by Hyyfit** [comment]
感谢反馈。
如果要实现分类的作用，可以给用例添加标签。
