### ISSUE TITLE
[BUG]metersphere 发送请求到 vpn 连接的接口时，平台一直报超时，无法正常发报文。点击保存并执行后，屏幕不段的闪，最后报超时。

### ISSUE THREAD

**Issue by Richard-chenbin** [metersphere/metersphere#141]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/68156947/87739263-052ca580-c812-11ea-948d-c0358379e9bb.png)

**Comment by wangzhen-fit2cloud** [comment]
执行接口测试时该域名解析到的 IP 地址与期望不符，后续考虑增加自定义的域名解析配置来解决该问题

**Comment by wangzhen-fit2cloud** [comment]
1.3 版本后已支持配置 hosts
