### ISSUE TITLE
[FEATURE]元素定位，路径框太短。查看很不方便，建议占一整行，拉长。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#14101]
### MeterSphere 版本

cloud

### 请描述您的需求或者改进建议

元素定位，路径框太短。查看很不方便，建议占一整行，拉长。

### 请描述你建议的实现方案

元素定位，路径框太短。查看很不方便，建议占一整行，拉长。
![66561653715437_ pic](https://user-images.githubusercontent.com/10231088/170811611-8f5f2f41-47aa-4d32-a621-d68ccc87bfe7.jpg)

### 附加信息

元素定位，路径框太短。查看很不方便，建议占一整行，拉长。

**Comment by Hyyfit** [comment]
感谢反馈，因为元素定位的长度不好控制，单纯的拉长长度也可能会无法全部展示。
这里可以优化悬停展示全部完整的路径。
另外我们也更推荐使用元素对象的方式进行定位，元素对象的话，在高级设置里的元素库，可以展示更多的详细信息。

**Comment by wudamyw** [comment]
> 感谢反馈，因为元素定位的长度不好控制，单纯的拉长长度也可能会无法全部展示。 这里可以优化悬停展示全部完整的路径。 另外我们也更推荐使用元素对象的方式进行定位，元素对象的话，在高级设置里的元素库，可以展示更多的详细信息。

当然不能绝对，但可以满足大部分。悬浮显示还是的鼠标放到上面，无法进行其他操作。真心希望能解决，尽量默认显示完全
