### ISSUE TITLE
[FEATURE]用例模版

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#1410]
**请描述您的需求或者改进建议.**
1、页面上有对用例增加标签的功能，请在用例模版文件中也增加“标签”字段上传
2、用例和用例模版可否增加一下Jira 号？
3、用例列表可否保存用户设置的列宽？比如我想看完整的用例名，但是宽度太小，每次进入系统都要重新设置，不太方便。
    要是能自定义显示的列，就更好了。
**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.用例模版已添加“标签”字段；
2.暂不支持；
3.已支持自定义表头显示字段，但是还不能保存设置的列宽
