### ISSUE TITLE
[BUG]性能测试平均响应时间计算不正确

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#14105]
### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

性能测试平均响应时间计算不正确

### 重现步骤

性能测试过程中，取样请求根本没有提交到服务器，但是还算到了平均响应时间中

### 期待的正确结果

期望测试结果中可以筛选成功的请求统计的聚合报告

**Comment by zyyfit** [comment]
请问具体是什么请求呢？是请求返回500等错误状态码了，还是没有执行这个请求？另外，方便贴个请求统计的截图吗？

**Comment by luman2013** [comment]
去服务器查看日志请求数是不包含失败的，请求没有状态码的
失败提示如下：








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]性能测试平均响应时间计算不正确 (Issue #14105)





 
请问具体是什么请求呢？是请求返回500等错误状态码了，还是没有执行这个请求？另外，方便贴个请求统计的截图吗？

**Comment by zyyfit** [comment]
邮件回复的信息不完整，方便的话请登录github回复一下，如果是失败的请求的话，是会统计的，在jmeter里也是统计的，未执行的接口不统计
