### ISSUE TITLE
支持更改“未规划用例”名称

### ISSUE THREAD

**Issue by cjwts** [metersphere/metersphere#14109]
### MeterSphere 版本

v1.20.4-lts-ec540937

### 请描述您的需求或者改进建议

目前测试跟踪→用例资产树那里，会自动生成初始的“未规划用例”文件夹，目前无法删除或者修改。

### 请描述你建议的实现方案

即使支持删除，也能给用户修改名字，否则用户看起来会很别扭

**Comment by Hyyfit** [comment]
感谢反馈，目前的设计如此。
考虑到实际使用的场景，会存在新创建的用例，还没想好放在那个分类下，如果没有这样的文件夹存在，一级目录下的未分类的用例就无法统计出来了。
