### ISSUE TITLE
[BUG]导出的测试报告底部有一片空白的局域

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14104]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

导出的测试报告底部有一片空白的局域
![QQ拼音截图未命名](https://user-images.githubusercontent.com/38156471/170813886-7258dba4-192b-4754-9ff1-bbc621730e0e.jpg)

### 重现步骤

导出测试计划的报告

**Comment by zrfit** [comment]
您好，感谢您的反馈，将右侧滚动条拉到底部，则可以展示全部报告，底部留白，未影响使用，如果觉得不美观，后续我们可以统一反馈给产品人员，调研后再决定是否做页面上的统一优化。

**Comment by YellCatt** [comment]
你导出的报告是否有双下拉条？里面的那条能到页面底部吗？

**Comment by zrfit** [comment]
导出是这样的，点击右侧滚动条下拉到底可查看全部报告内容。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/99731894/170939862-ef09c0dd-32ec-4526-a9b9-b68ce05091e3.png">
