### ISSUE TITLE
[BUG] 前置脚本“vars.put("userId","${__Mock(@increment)}");”会递增2，而不是期望的1

### ISSUE THREAD

**Issue by qiaoming8006** [metersphere/metersphere#14107]
### 联系方式

qiaoming8006@aliyun.com

### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

前置脚本“vars.put("userId","${__Mock(@increment)}");”会递增2，而不是期望的1

### 重现步骤

**用例设计如下：**
1 前置操作添加前置脚本如下图所示：
![image](https://user-images.githubusercontent.com/32956089/170827365-c6ed8b25-f079-4713-bfb3-e60d1657124e.png)
2 请求体如下图所示
![image](https://user-images.githubusercontent.com/32956089/170827443-c1fb6c92-d303-41f0-a3a5-c63cd8af97d8.png)
**执行结果：**
执行第一次如下图：
![image](https://user-images.githubusercontent.com/32956089/170827654-cfdbfcbb-01d5-4693-82eb-4d7396a09f78.png)
执行第二次如下图：
![image](https://user-images.githubusercontent.com/32956089/170827714-f8a62291-103f-4e28-a913-13a5f54cf6ae.png)

### 期待的正确结果

实际结果：
第一次执行数字是73，第二次执行数字是75，递增了2
期待结果：
第一次执行数字是73，第二次执行数字是74，递增1

**Comment by zyyfit** [comment]
感谢反馈，但是在单个case调用这个产生的数字应该是随机的，我们先研究一下应该是随机执行还是顺序递增吧，修复完成的时候会在这里评论最终逻辑的

**Comment by zyyfit** [comment]
另外，在场景里，使用次数循环、或者直接多次引用这个case执行，目前都是+1递增的

**Comment by zyyfit** [comment]
暂时保持原样，case执行的时候mock数据没有关联性
