### ISSUE TITLE
[FEATURE]接口用例，添加用例类别、备注字段。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#14100]
### MeterSphere 版本

1.19.1

### 请描述您的需求或者改进建议

现在一条接口用例信息有限，希望能加用例类别，对用例进行归类。第二是增加备注字段，以说明用例，比如特殊的账号，数据等。

### 请描述你建议的实现方案

现在一条接口用例信息有限，希望能加用例类别，对用例进行归类。第二是增加备注字段，以说明用例，比如特殊的账号，数据等。

**Comment by Hyyfit** [comment]
感谢反馈。
1. 用例的类别可以通过添加标签的方式进行分类。
2. 用例添加备注字段，这个可以优化，已规划，待排期。
