### ISSUE TITLE
[BUG]接口自动化创建了的性能测试，脚本及文件内容更新后，性能测试的没有跟着更新

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#14106]
### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

接口自动化创建了的性能测试，脚本及文件内容更新后，性能测试的没有跟着更新

### 重现步骤

1、接口自动化场景创建了性能测试
2、再次更新接口自动化脚本或者脚本中的文件内容有更新
3、再次执行之前脚本创建的性能测试

### 期待的正确结果

再次执行性能测试，脚本及脚本中的文件内容应该按更新后的执行

**Comment by youliyuan-fit2cloud** [comment]
暂时不支持，转性能测试的时候生成的jmx文件就是当前的配置，之后再修改接口这边对性能测试无效

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/170903634-2bdcbebf-c571-43c6-80a0-ee93fed01c5f.png)

性能测试这里手动同步一下
