### ISSUE TITLE
[FEATURE]测试报告中对于失败用例给出的信息不足

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14116]
### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/38156471/170880942-0447982d-364c-4ca8-9246-4854ab147010.png)
我觉得测试报告中接口用例给出的信息不够多，如果我是一个开发，看到接口测试的内容后，首先是希望复现去看日志，但是你这边都没有环境前置脚本，用例前置脚本，环境后置脚本，用例后置脚本，如果要复现，还需要去case里看详细情况

**Comment by Hyyfit** [comment]
感谢反馈，目前的设计如此。
