### ISSUE TITLE
[BUG]更新或修改配置环境时“链接超时”前后端都没有进行校验。

### ISSUE THREAD

**Issue by yongye101** [metersphere/metersphere#14112]
### 联系方式

953883765@qq.com

### MeterSphere 版本

master

### 使用外置数据库

否

### 问题描述

更新或修改配置环境时“链接超时”前后端都没有进行校验。可以输入负数
![SYY U$5ZJ9`XT$YR(L46`EW](https://user-images.githubusercontent.com/106467108/170858846-733b1f57-4277-486e-81ce-f46a3d50cd8d.png)
在添加数据库配置时同样出现判断失误，允许输入小数：
![K~T{G3T02F)(WH_6M(FY2GH](https://user-images.githubusercontent.com/106467108/170858858-44a39f53-f086-495c-a1ce-90740e74eb18.png)

### 重现步骤

如上方在问题描述中所示

### 期待的正确结果

希望能够在前后端进行相关信息验证。

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v1.20.5-lts版本中修复该问题
