### ISSUE TITLE
[BUG] 添加tag解析错误

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14113]
### MeterSphere 版本

1.20.4

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/170862614-fe66d34d-b582-43ec-84b9-9bb873f8d265.png)

### 重现步骤

tag解析错误，请处理特殊字符

**Comment by sac911** [comment]
![image](https://user-images.githubusercontent.com/103017812/170862647-e70812f5-24c6-478a-9b90-cb00b9f3c1fc.png)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/170901065-b01b51a9-4287-4f68-8c6c-389542787c2f.png)

没有复现。。或者你把你复现的tag内容贴一下吧，
