### ISSUE TITLE
[BUG]测试跟踪里的测试计划，在已授权账号里点击报告，提示403 Forbidden无法查看

### ISSUE THREAD

**Issue by geyesheng** [metersphere/metersphere#14117]
### MeterSphere 版本

v1.20.3-lts-f5223bb5

### 使用外置数据库

是

### 问题描述

新建分组和设置权限，
![image](https://user-images.githubusercontent.com/38676947/170637848-797e8828-3c9e-41ec-8ec8-1506c14cf846.png)
![image](https://user-images.githubusercontent.com/38676947/170637949-a47b39d8-a560-4dc0-9e3b-584152d6eac4.png)

然后新增账号赋予新增的分组和权限，选择测试跟踪对应的测试计划执行后的报告查看

![image](https://user-images.githubusercontent.com/38676947/170900707-b17b1e0d-6d73-4a10-8f11-b2cde0f3b588.png)
跳转非报告页，显示的为系统数据，按F12调试出现403错误
![image](https://user-images.githubusercontent.com/38676947/170900769-72d5a06a-d210-40ff-aa33-79d6d91e2b8a.png)

### 重现步骤

测试跟踪里的测试计划，在已授权账号里点击报告，提示403 Forbidden无法查看

**Comment by ltfit** [comment]
感谢反馈 后续版本修复
