### ISSUE TITLE
[FEATURE]我的服务器联网，但是没有动态域名，我在局域网外想看测试报告，有没有办法设置MS平台通过企业微信或者邮件直接发我一份？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14111]
### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 请描述您的需求或者改进建议

我的服务器联网，但是没有动态域名，我在局域网外想看测试报告，有没有办法设置MS平台通过企业微信或者邮件直接发我一份？

**Comment by Hyyfit** [comment]
我们的报告是支持分享和导出的
![image](https://user-images.githubusercontent.com/95834771/170904494-ea588f35-233c-4ada-9347-f03498d28775.png)

**Comment by YellCatt** [comment]
> 我们的报告是支持分享和导出的
> ![image](https://user-images.githubusercontent.com/95834771/170904494-ea588f35-233c-4ada-9347-f03498d28775.png)

能自动发吗？

**Comment by Hyyfit** [comment]
如果要自动发送要在消息设置中配置，测试计划是支持发送报告的链接
![image](https://user-images.githubusercontent.com/95834771/170906317-c4db3f2b-34d0-4cb4-bd34-99f86abdeee4.png)

**Comment by YellCatt** [comment]
> 如果要自动发送要在消息设置中配置，测试计划是支持发送报告的链接
> ![image](https://user-images.githubusercontent.com/95834771/170906317-c4db3f2b-34d0-4cb4-bd34-99f86abdeee4.png)

我是希望能自动把报告发给我，连接没有用啊，我在外网的情况下，不可能打开家里的局域网吧

**Comment by Hyyfit** [comment]
好的吧，我们现在是只支持分享报告的，不支持自动化直接发送报告。
