### ISSUE TITLE
升级到1.20-lts版本后同一个项目产生多个“未规划用例”文件夹

### ISSUE THREAD

**Issue by cjwts** [metersphere/metersphere#14110]
### 联系方式

junjie.du@fit2cloud.com

### MeterSphere 版本

v1.20.4-lts-ec540937

### 使用外置数据库

否

### 问题描述

1.19版本升级到了lts，然后数据库里出现了多条“未规划用例”的文件夹，前端也显示有两个
![ab49e68dc187f84b89e605c11f8e9bc](https://user-images.githubusercontent.com/30405402/170852080-c2a724ab-eb37-4d3c-8941-088c5390dfd1.png)
![e1a03cfe984c904a03e239addaa13dc](https://user-images.githubusercontent.com/30405402/170852085-45efb258-1a92-4135-b2ad-b48d8f9a94ae.png)

### 重现步骤

1.19版本升级到了lts，然后数据库里出现了多条“未规划用例”的文件夹，前端也显示有两个

### 期待的正确结果

只有一个“为规划用例”文件夹

**Comment by ltfit** [comment]
你好 我这边升级了下 没有复现。是有其他别的操作么

**Comment by xulinde** [comment]
v1.20.7已修复，建议您升级至最新版本
