### ISSUE TITLE
[BUG]测试跟踪-用例评审-编辑用例，无法关联用例信息，提示错误

### ISSUE THREAD

**Issue by Boylijun** [metersphere/metersphere#14127]
### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

测试跟踪-用例评审-编辑用例，无法关联用例信息，提示错误

### 重现步骤

![129EEFBE-47DA-4129-9D52-E2C8A5FA1B07](https://user-images.githubusercontent.com/21175004/170912371-f8204c4a-2a10-422a-b248-02fb150d4e3e.png)
![E37E800F-89B3-44db-871D-51338333E483](https://user-images.githubusercontent.com/21175004/170912413-86bd581e-d051-454a-ae47-74e41a412d17.png)

**Comment by youliyuan-fit2cloud** [comment]
最新版本 1.20.4-lts没有复现。建议升级一下吧

**Comment by Boylijun** [comment]
暂时升级不了啊   先摆烂吧

**Comment by youliyuan-fit2cloud** [comment]
贴下前端控制台的日志，然后可以重新关联下试试

**Comment by Boylijun** [comment]
![Uploading 782C00F9-3B3C-45a2-BF1E-731208E52247.png…]()

**Comment by Boylijun** [comment]
![782C00F9-3B3C-45a2-BF1E-731208E52247](https://user-images.githubusercontent.com/21175004/170957371-0aab821c-69c8-41a9-9646-5f01272d3fd3.png)

**Comment by Boylijun** [comment]
https://cdnjs.cloudflare.com都要访问这个网站，我们内网是不能访问外网的 ，有关系不

**Comment by youliyuan-fit2cloud** [comment]
你的意思是我们MeterSphere系统要先访问这个网站？
还有你控制台没截全，还是看不出来啥原因。

**Comment by Boylijun** [comment]
![8E5BE611-F9B8-49a9-84F1-B15B3174BD21](https://user-images.githubusercontent.com/21175004/170974859-b696a128-405c-4922-a33c-72ac21fabfde.png)
报错信息都是图片里面的  都是前端信息 后端接口没有报错

**Comment by AgAngle** [comment]
![image](https://user-images.githubusercontent.com/41557596/171079704-0ade89df-00fa-4a18-b89d-cd002476cab7.png)
你好，取消关联，重新添加下，还是有问题吗？是个别用例有问题，还是都有问题？个别有问题的话，能大概排查总结下什么情况下有问题吗？

**Comment by Boylijun** [comment]
大家一起摆烂吧，别解决了
