### ISSUE TITLE
[BUG]导出的测试报告中没有报告总结没有断言数据

### ISSUE THREAD

**Issue by QAceshi** [metersphere/metersphere#14123]
### 联系方式

13655190967@sina.cn

### MeterSphere 版本

1.20.2

### 使用外置数据库

是

### 问题描述

导出的测试报告中没有报告总结没有断言数据

### 重现步骤

导出测试报告

**Comment by youliyuan-fit2cloud** [comment]
你好，测试报告指的是哪里的，测试计划的报告还是接口自动化测试的报告？

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/170940923-bfee9ca6-7510-466c-8f62-0f3bb1660e71.png)
场景断言结果在每个请求的断言中可以看到结果
