### ISSUE TITLE
[BUG]接口用例在前置脚本中设置一个环境变量，然后放到请求头和请求体中去请求，结果请求的内容还是变量名称

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#14122]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

 v1.20.4-lts

### 使用外置数据库

否

### 问题描述

在前置脚本中设置一个环境变量，然后放到请求头和请求体中去请求，结果请求的内容还是变量名称，查看环境变量中的变量，发现存进去了，再次执行这个用例变量内容就正常了

### 重现步骤

1.在前置脚本中设置一个环境变量
<img width="785" alt="image" src="https://user-images.githubusercontent.com/104493699/170679538-abe45afc-74bb-4b31-8a95-deebee2c1305.png">
2.将这个环境变量放到请求头和请求体当中去请求
<img width="756" alt="image" src="https://user-images.githubusercontent.com/104493699/170679649-30d6554f-bf85-4b89-bf3e-b67b8ad6af8c.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/104493699/170679709-0bee85ca-b51b-4432-b7e7-40054e9c717b.png">
3.请求完查看请求内容，变量的值还是${key}
<img width="556" alt="image" src="https://user-images.githubusercontent.com/104493699/170679837-9f5a507c-eed7-41ff-8c83-906fdf015a2f.png">
4.去环境变量中查看，这个环境变量存进去了，然后第二次执行的时候值是正常的
<img width="550" alt="image" src="https://user-images.githubusercontent.com/104493699/170679921-f189386a-6975-4e1c-a63e-05381c494826.png">

**Comment by youliyuan-fit2cloud** [comment]
这个逻辑是对的，第一次执行的时候，当前还没执行这个接口用例获取不到这个变量值吧，只能是第二次时候

**Comment by youliyuan-fit2cloud** [comment]
我们的项目环境设置 的参数是俩。你咋变成一个了
vars.put(${__metersphere_env_id}+"key","value");
vars.put("key","value")
