### ISSUE TITLE
[BUG]项目设置-模板管理，自定义用例模板连续添加了两个名字一样的字段。测试跟踪导出的excel用例模板标题自动合并了

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#14165]
### MeterSphere 版本

v1.20.2-lts-0f489ee9

### 使用外置数据库

否

### 问题描述

项目设置-模板管理，自定义用例模板连续添加了两个名字一样的字段。测试跟踪导出的excel用例模板标题自动合并了

### 重现步骤

1、项目设置-模板管理，自定义用例模板连续添加了两个名字一样的字段。
2、测试跟踪导出的excel用例模板标题自动合并了

<img width="894" alt="模板管理添加字段" src="https://user-images.githubusercontent.com/43202800/170977534-ee0bbcaa-a687-4ffa-8fc7-73a538af7a22.png">
<img width="960" alt="自定义 用例模板，添加的两个同名字段靠在一起时，导出的" src="https://user-images.githubusercontent.com/43202800/170977556-29ac712c-88e2-4754-8202-fcc29efe375b.png">

### 期待的正确结果

添加的字段不自动合并

**Comment by youliyuan-fit2cloud** [comment]
了解一下，用相同字段的场景是什么？

**Comment by xhy12** [comment]
> 
客户打算把powerproject、leangoo上的数据打通，两个系统的自定义字段是重名的。现在是两个字段靠在一起就重叠

**Comment by youliyuan-fit2cloud** [comment]
> > 
> 
> 客户打算把powerproject、leangoo上的数据打通，两个系统的自定义字段是重名的。现在是两个字段靠在一起就重叠

了解了，我们先内部讨论下，是否支持这个需求，请关注后续反馈，谢谢~

**Comment by youliyuan-fit2cloud** [comment]
后续这里优化自定义字段不能重复~
