### ISSUE TITLE
[BUG]断言有误

### ISSUE THREAD

**Issue by cheese-jie** [metersphere/metersphere#14161]
### MeterSphere 版本

v1.20.4-lts

### 使用外置数据库

否

### 问题描述

响应结果：
<img width="313" alt="ca793aee4ae11e937a038ffc0416487" src="https://user-images.githubusercontent.com/61402953/170970793-89ccd48d-acc8-4e3d-94ca-008667f3788a.png">
断言内容：
<img width="671" alt="3befc1bdbe3e9e7b07d824627241297" src="https://user-images.githubusercontent.com/61402953/170970854-2c0c7f1e-d693-40e2-8910-176637dd442d.png">

校验的是数组，但是如上断言 断言成功了，理论来说应该断言失败

### 重现步骤

如上

### 期待的正确结果

断言失败

**Comment by zyyfit** [comment]
您好，没看懂您这个为什么应该是失败，我测试了一下，成功和失败都是正常的
![image](https://user-images.githubusercontent.com/73461316/171090354-f6cfe5dc-235b-4140-8890-a29632092579.png)
![image](https://user-images.githubusercontent.com/73461316/171090376-7b6a1e10-2fd8-4c42-851a-ab2adb9a7b0a.png)
