### ISSUE TITLE
[BUG]创建代码片段，从API定义导入，导入的代码没有自动填充请求体参数

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14178]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

创建代码片段，从API定义导入，导入的代码没有自动填充请求体参数
这是入参：
{"index":{"_id":"A001","_type":"_doc"}}
{"pcode":"A","parentPath":"A","sign":"我不是我！！！","parentLevel":"1","mobilephone":15021342292,"policeType":"无","extendDataFromCode_name":"自建","createdTime":1653782274335,"id":"A001","approvalBy":"系统","deviceType":"kaps_user","updatedTime":1653782274335,"updatedBy":"system","nickName":"ADP01","isAudit":"1","deptId":"A","deptId_name":"一级部门A","telephone":"88888888","isWebpage":1,"sequence":"1","name":"A部门人员01","updaterName":"system","extendDataFromCode":"0","userType":"3","position":"职员","dataFromCode_name":"自建","status":"1","birthday":1651420800000,"code":"A001","operationFrom":"1","sortIndex":1,"creatorName":"system","remark":"A部门人员01ADP01","showInAddressBook":"1","identity":"330304199307082717","headPortrait":"DEFAULTHEADPORTRAITURL","email":"768305875@qq.com","rootDeptId":"A","address":"上海市嘉定区吴杨东路","dataFromCode":"0","isLeader":"0","status_name":"有效","policeNo":"A001","sex":"0","isPolice_name":"不是","userType_name":"其他","shortNo":"130","officeAddress":"上海市徐汇区协土街道","isLeader_name":"不是","isAudit_name":"已审核","isPolice":"0","sex_name":"女","createdBy":"system","showInAddressBook_name":"是","operation":"ADD"}
接口截图：
![QQ拼音截图未命名4](https://user-images.githubusercontent.com/38156471/171002566-3e507850-7ca8-4253-bf1d-eceb4f0d22e3.jpg)
python代码截图：
![QQ拼音截图未命名3](https://user-images.githubusercontent.com/38156471/171002616-2a62eb5d-c715-4d28-ad81-a39da9d3de29.jpg)
js代码截图：
![QQ拼音截图未命名5](https://user-images.githubusercontent.com/38156471/171002647-23b5735e-9af1-4af7-bcaa-9d0e4af8a8eb.jpg)

### 重现步骤

创建代码片段，从API定义导入，导入的代码没有自动填充请求体参数
这是入参：
{"index":{"_id":"A001","_type":"_doc"}}
{"pcode":"A","parentPath":"A","sign":"我不是我！！！","parentLevel":"1","mobilephone":15021342292,"policeType":"无","extendDataFromCode_name":"自建","createdTime":1653782274335,"id":"A001","approvalBy":"系统","deviceType":"kaps_user","updatedTime":1653782274335,"updatedBy":"system","nickName":"ADP01","isAudit":"1","deptId":"A","deptId_name":"一级部门A","telephone":"88888888","isWebpage":1,"sequence":"1","name":"A部门人员01","updaterName":"system","extendDataFromCode":"0","userType":"3","position":"职员","dataFromCode_name":"自建","status":"1","birthday":1651420800000,"code":"A001","operationFrom":"1","sortIndex":1,"creatorName":"system","remark":"A部门人员01ADP01","showInAddressBook":"1","identity":"330304199307082717","headPortrait":"DEFAULTHEADPORTRAITURL","email":"768305875@qq.com","rootDeptId":"A","address":"上海市嘉定区吴杨东路","dataFromCode":"0","isLeader":"0","status_name":"有效","policeNo":"A001","sex":"0","isPolice_name":"不是","userType_name":"其他","shortNo":"130","officeAddress":"上海市徐汇区协土街道","isLeader_name":"不是","isAudit_name":"已审核","isPolice":"0","sex_name":"女","createdBy":"system","showInAddressBook_name":"是","operation":"ADD"}
接口截图：
![QQ拼音截图未命名4](https://user-images.githubusercontent.com/38156471/171002566-3e507850-7ca8-4253-bf1d-eceb4f0d22e3.jpg)
python代码截图：
![QQ拼音截图未命名3](https://user-images.githubusercontent.com/38156471/171002616-2a62eb5d-c715-4d28-ad81-a39da9d3de29.jpg)
js代码截图：
![QQ拼音截图未命名5](https://user-images.githubusercontent.com/38156471/171002647-23b5735e-9af1-4af7-bcaa-9d0e4af8a8eb.jpg)

### 期待的正确结果

希望能自动填充请求体参数

**Comment by zyyfit** [comment]
您好，目前我们只支持了json参数，其他类型的参数是否支持还需要等待产品调研后再确认

**Comment by zyyfit** [comment]
1.20.8版本已支持导入其他参数，请升级使用
