### ISSUE TITLE
[BUG]功能用例列表按ID排序时，有时候会出现排序错乱的现象

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14177]
### 联系方式

张树彬

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

普通版本1.19.3，功能用例列表按ID排序时，有时候会出现排序错乱的现象。偶现

### 重现步骤

1. 进入功能用例列表
2. 点击ID排序按钮 
3. 偶现用例按ID排序顺序错乱

### 期待的正确结果

按正序或倒序顺序排列

### 附加信息

![8f68c79c5d77308a0bf27da8a4c972c](https://user-images.githubusercontent.com/77324661/170998995-456dec68-b45a-4fe8-906b-b36b02046020.jpg)

**Comment by ltfit** [comment]
你好 这个是正常的 自定义id排序 是按字符串排序来的
