### ISSUE TITLE
[BUG] 接口定义-接口测试，另存为新的接口后，发现原接口被更改了（预期：新增一个接口，原接口不受影响）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1417]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？ 1.7.2

**Bug 描述**
简要描述您碰到的问题
接口定义-接口测试，另存为新的接口后，发现原接口被更改了（预期：新增一个接口，原接口不受影响）

**Bug 重现步骤**
1.  接口定义-接口测试，进行接口测试
2. 另存为新的接口
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
预期：新增一个接口，原接口不受影响
实际：原接口被更改

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/107134609-a73ae900-692e-11eb-941b-87867e4a0aad.png)

**Comment by xulinde** [comment]
您好，该问题已修复。1.8.0发布后您升级下就可以了
