### ISSUE TITLE
[QUESTION]JSON-文档接口校验 这个功能怎么使用？我好像无论怎么返回都不会报错，断言里也没有对应的信息返回？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14179]
### 请描述您的问题

![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/171003441-d94ca0e1-44a7-4791-89ec-662f6e9df9e0.jpg)
JSON-文档接口校验 这个功能怎么使用？我好像无论怎么返回都不会报错，断言里也没有对应的信息返回？

**Comment by Hyyfit** [comment]
![image](https://user-images.githubusercontent.com/95834771/171082412-331cb5e2-ffbc-415f-afc1-b5bd8ee95ca9.png)
