### ISSUE TITLE
[FEATURE]写入变量的值不支持针对于全列表，目前只针对于列表单个值

### ISSUE THREAD

**Issue by waveboy800** [metersphere/metersphere#14193]
### MeterSphere 版本

V1.20.4 lts

### 请描述您的需求或者改进建议

写入变量的值不支持针对于全列表，目前只针对于列表单个值，希望后续加上针对于全列表

**Comment by Hyyfit** [comment]
您好，看不懂您这边的需求是什么？哪里写入的变量？具体是什么的全列表？
