### ISSUE TITLE
[BUG] UI自动化场景内批量操作步骤，启用、禁用等操作无效、页面无反应

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14198]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.4-LTS

### 使用外置数据库

否

### 问题描述

UI自动化场景内，编辑某一个场景步骤，批量操作步骤，启用、禁用等操作无效、页面无反应

### 重现步骤

1、UI自动化场景内，编辑某一个场景步骤，
2、多选左侧步骤批量操作步骤，启用、禁用等操作
3、运行场景查看效果

### 附加信息

<img width="494" alt="image" src="https://user-images.githubusercontent.com/32027713/171095542-0c1a41e8-f921-443f-ac8c-0de68cb748a3.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts中已修复
