### ISSUE TITLE
[BUG]csv+循环控制器，循环控制器将不会一行一行读取csv中的值，而是隔一行读取

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#14207]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.4

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/31870788/171110557-a36466e7-b506-4c80-b849-29cc0f23ee7e.png)
![image](https://user-images.githubusercontent.com/31870788/171110578-86826aec-90c1-4fea-b9c4-28d91f365421.png)
![image](https://user-images.githubusercontent.com/31870788/171110596-1ec76235-4841-4238-a76a-798b37dbb7ff.png)

### 重现步骤

循环控制器里面改成自定义请求也一样

![image](https://user-images.githubusercontent.com/31870788/171110673-2ef03123-f7d8-43e4-ab31-d04cb8eacfe5.png)
![image](https://user-images.githubusercontent.com/31870788/171110687-070b18f4-164a-4aa2-bc45-9ab7da692dc3.png)
![image](https://user-images.githubusercontent.com/31870788/171110702-d5ad8d36-5c1b-45d7-a895-3d842efa4079.png)
![image](https://user-images.githubusercontent.com/31870788/171110715-df72a96e-74a2-47c7-a11e-005ab907fff0.png)

### 期待的正确结果

感觉是比较严重的bug，这种比较常用的功能，应该在新版本出来之前就测出来，而不是用户在使用的时候测半天，以为自己脚本错了，之后才发现，一个是比较浪费使用者的时间和影响工作进度，导致后续不再想使用，一个是很影响对metersphere的印象和体验，新版本在出来之前可以测一下基本功能的。（题外话

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们下个小版本修复该问题，也感谢提出的建议，我们后续一个月的规划是持续改进质量，只修复问题，不新增需求。也请继续关注我们~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts版本中已修复
