### ISSUE TITLE
[BUG] 性能测试运行失败

### ISSUE THREAD

**Issue by YongShuaiJi** [metersphere/metersphere#1420]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7

**Bug 描述**
新版本改的代码和之前的SQL之间不匹配，导致运行性能测试的时候出错

**Bug 重现步骤**

之前的SQL是这样的：
INSERT into system_parameter values('base.url', 'http://localhost:8081', 'text', 1);
新版本的代码是这样的：
![image](https://user-images.githubusercontent.com/28250542/107137895-b2504200-694b-11eb-8de4-de3d3e274bf3.png)

**期待的正确结果**
修改代码，正常运行性能测试

**截图**
提示：无法运行测试，请检查当前站点配置

**Comment by liuruibin** [comment]
这个站点配置用来发送邮件的连接和资源池下载文件用的，是安装后的实际地址。如果有域名配置，也可以是域名。这里需要安装后自行修改

**Comment by liuruibin** [comment]
性能测试通过启动容器来执行，容器启动时会下载需要的文件。这时候localhost指向了容器本身，这是不能下载文件的。这里配置了ms-server的实际地址。
