### ISSUE TITLE
[BUG]新版接口上传图片报错，老版不报错

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#1421]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.1

**Bug 描述**
新版接口上传图片报错，老版不报错

**Bug 重现步骤**
1. 在请求体 栏位 选择 file类型，后上传一个 jpg的图片格式
2. 填完上传所需字段信息
3. 直接点击运行

**期待的正确结果**
图片正常上传

**截图**
实际返回结果为：Failed to parse multipart servlet request; nested exception is java.io.IOException

**Comment by xulinde** [comment]
感谢反馈，按照您的复现步骤，我们没复现该问题
![image](https://user-images.githubusercontent.com/64065190/107187013-4390e880-6a20-11eb-8c5d-326aa9a79bf9.png)
