### ISSUE TITLE
[FEATURE] 缺陷管理需求

### ISSUE THREAD

**Issue by liming245** [metersphere/metersphere#14210]
### MeterSphere 版本

 v1.20.4-lts-5b8b8d82

### 请描述您的需求或者改进建议

1、缺陷管理自定义字段是否允许增加搜索和排序
![image](https://user-images.githubusercontent.com/16378691/171111403-48a4f72f-d622-4d60-8c72-1cf117e5597b.png)
2、缺陷状态变更为已关闭状态，是否只有管理员能修改，项目成员不让修改

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
