### ISSUE TITLE
[FEATURE]当循环控制器进行多次请求时最终返回结果是成功的时候，建议循环控制器返回success而非error

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#14227]
### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 请描述您的需求或者改进建议

接口测试->接口自动化->新建测试场景
场景1：
①接口1 （异步接口）
②循环控制器  （次数循环，10次）
    接口2 （查询接口1处理结果，结果字段status返回为SUCCESS时为成功）
    
点击调试结果：
①接口1                                                                                            success
②循环控制器  （次数循环，10次）                                                error
    接口2                                                                                            error
        ......
        响应内容
        循环1 （error）                                                 循环2（success）
        200（status不等于SUCCESS，断言失败）        200（断言成功）

建议改进结果：
①接口1                                                                                            success
②循环控制器  （3种循环条件任一种）                                           success 2次
    接口2                                                                                            success
        ......
        响应内容
        循环1 （error）                                                 循环2（success）
        200（status不等于SUCCESS，断言失败）        200（断言成功）

### 请描述你建议的实现方案

![Uploading image.png…]()

**Comment by meifeifei** [comment]
![image](https://user-images.githubusercontent.com/57786489/171138806-f52889ef-0d72-4636-a08f-b55401bc135d.png)

**Comment by meifeifei** [comment]
测试报告的优化建议：
循环第2次才成功，生成的测试报告也是失败的；建议报告要是在多次循环成功后，报告最终的状态也应该是success的

**Comment by Hyyfit** [comment]
感谢反馈，目前设计如此。
如果选用的是次数循环，每次都成功，则展示success，如果出现了error，则为error。
按照您描述的场景，需要的是“最终的请求成功”，这种场景建议使用while循环。

**Comment by meifeifei** [comment]
> 感谢反馈，目前设计如此。 如果选用的是次数循环，每次都成功，则展示success，如果出现了error，则为error。 按照您描述的场景，需要的是“最终的请求成功”，这种场景建议使用while循环。

使用while循环有同样的问题，有一次error了结果就是error
