### ISSUE TITLE
[BUG]测试报告中场景id缺失

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#14224]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.4

### 使用外置数据库

否

### 问题描述

测试报告中场景id缺失:计划关联场景的时候有id，计划执行后测试报告场景id缺失，多次执行该计划，均是某固定场景id缺失，缺失id场景未做变动。

### 重现步骤

1.新建测试计划
2.关联多个场景
3.执行测试计划查看报告

### 附加信息

![20220531-162834](https://user-images.githubusercontent.com/103627487/171128826-0c35ecbf-5fef-4c0f-af94-9f1c897556f6.jpg)
![微信图片_20220531163844](https://user-images.githubusercontent.com/103627487/171130824-5b5e1655-0a28-4e8f-a27c-1388ec8ca29c.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~

**Comment by ltfit** [comment]
1.20.5-lts 版本修复
