### ISSUE TITLE
[上传文件接口失败]测试上传文件接口时，状态码处报Non HTTP response code: java.lang.IllegalArgumentException错误

### ISSUE THREAD

**Issue by susan20150801** [metersphere/metersphere#1423]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.2-bd12a36a
**Bug 描述**
简要描述您碰到的问题
测试上传文件接口，状态码返回错误。（在postman和jmeter调试通过）
**Bug 重现步骤**
1.  编辑上传文件接口；
2. 测试该接口；
3. 观察状态码

**期待的正确结果**
正确情况下应该是什么样的？
可以正常响应
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40201838/107139745-812a3e80-6958-11eb-877a-dc6d00f64d6d.png)

**Comment by xulinde** [comment]
感谢反馈，根据您的复现步骤，我们没复现该问题
![image](https://user-images.githubusercontent.com/64065190/107183768-57395080-6a1a-11eb-9257-1578da10470b.png)
