### ISSUE TITLE
[FEATURE]用户组与权限设置权限处，UI测试菜单可做配置（当前为固定写死，但又需要企业版本才可使用）

### ISSUE THREAD

**Issue by geyesheng** [metersphere/metersphere#14232]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 请描述您的需求或者改进建议

用户组与权限设置权限处，UI测试未做配置
![image](https://user-images.githubusercontent.com/38676947/171136928-691930d5-c07f-44f5-8cf0-d940f39be96f.png)

![image](https://user-images.githubusercontent.com/38676947/171147197-795dab29-74e5-4179-baae-652132114816.png)

### 请描述你建议的实现方案

UI测试菜单可做配置
![image](https://user-images.githubusercontent.com/38676947/171146924-c9285272-1ea8-4667-abbf-d41297bf5f78.png)
![image](https://user-images.githubusercontent.com/38676947/171147013-293731d9-ac6c-4a14-a885-37d696f6a9b2.png)

**Comment by Hyyfit** [comment]
感谢反馈。这个是推广需要，主要是方便用户了解我们metersphere的全部功能。
