### ISSUE TITLE
[Jmeter中Critical section Controller元件]导入的Jmeter脚本中含有Critical section Controller元件，在性能测试时，提示Lock 'global_lock' not released in: Critical Section Controller, releasing in threadFinished

### ISSUE THREAD

**Issue by susan20150801** [metersphere/metersphere#1424]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.2-bd12a36a
**Bug 描述**
简要描述您碰到的问题
导入的Jmeter脚本中含有Critical section Controller元件，在性能测试时，提示Lock 'global_lock' not released in: Critical Section Controller, releasing in threadFinished
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
可以兼容Critical section Controller元件
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40201838/107139821-0ada0c00-6959-11eb-91e6-2a1db3cd49fd.png)

**Comment by xulinde** [comment]
现在还有此问题吗

**Comment by youliyuan-fit2cloud** [comment]
没有复现该问题，close~
