### ISSUE TITLE
[BUG][企业用户] 参数替换有错误的换行导致用例执行失败

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14243]
### MeterSphere 版本

1.20.4

### 使用外置数据库

是

### 问题描述

参数替换有错误的换行导致用例执行失败
![image](https://user-images.githubusercontent.com/103017812/171155379-1dd7abb3-e012-4202-9ee9-fb1615d6fee4.png)
![image](https://user-images.githubusercontent.com/103017812/171155403-131d64f0-37c0-4e3b-b762-65c5d2c8d2a8.png)

### 重现步骤

环境变量中定义的参数，在case执行时变量末尾多了一个换行

**Comment by zyyfit** [comment]
请问您是怎么操作出这种带换行的数据的？我测试了一下，环境通用配置里的变量没有带上换行

**Comment by sac911** [comment]
实话说我也不是太清楚怎么会产生换行，我专门看了变量，特意去看看结尾是否有空格或者换行。这个变量我是通过批量录入的方式录入的，不是在表格里面一个一个录入的，所以我猜测是否和录入方式有关系（批量的最后一个数据是不是自动带了一个换行）？

**Comment by zyyfit** [comment]
> 实话说我也不是太清楚怎么会产生换行，我专门看了变量，特意去看看结尾是否有空格或者换行。这个变量我是通过批量录入的方式录入的，不是在表格里面一个一个录入的，所以我猜测是否和录入方式有关系（批量的最后一个数据是不是自动带了一个换行）？

我测试过批量添加，也没有出现换行，我也试了多加一行空的，没有出现过这种情况。。

**Comment by zyyfit** [comment]
那你试试重新填写一下这个变量的值还有问题吗？
