### ISSUE TITLE
[BUG] 开始用例评审，对用例进行评审结果筛选，评审页面用例条数显示不正确

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#14253]
### 联系方式

18311441708

### MeterSphere 版本

1.20.3.lts

### 使用外置数据库

否

### 问题描述

规划用例评审页面，添加了440条功能用例后，开始用例评审，用例条数显示正常

---------------------------------------------------------------------------------------------------------
筛选评审状态后，开始用例评审，当前用例总条数和总用例条数关系和跳转上下后显示错误
<img width="662" alt="1654051573(1)" src="https://user-images.githubusercontent.com/103925124/171318217-bb0e86be-7aa0-4400-be49-03963a16cb9c.png">

<img width="852" alt="1654051853(1)" src="https://user-images.githubusercontent.com/103925124/171318093-261088ef-85b2-4b0c-acae-668220193049.png">

### 重现步骤

规划用例评审页面，添加数据量大一些的用例后，筛选用例评审状态后，开始用例评审，当前用例总条数和总用例条数关系和跳转上下后显示错误（需要多点一点跳转上下）筛选完初次开始用例评审页面出现此问题概率大，初次后在点击开始评审，此问题出现概率小

### 期待的正确结果

当前用例总条数和总用例条数关系和跳转上下后显示正常

### 附加信息

https://user-images.githubusercontent.com/103925124/171318619-617719e9-77a9-4317-8256-953712d5e694.mp4

**Comment by ltfit** [comment]
在最新版本v1.20.7-lts中已修复~
