### ISSUE TITLE
[BUG]参数为文件时，运行系统错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#1425]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.7

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口用例如下
2. 
![image](https://user-images.githubusercontent.com/78218624/107140900-57751580-6960-11eb-9adf-88c48abe463d.png)

2. 运行结果错误
3. 
![image](https://user-images.githubusercontent.com/78218624/107140917-64920480-6960-11eb-954a-bc5d3a0c38e4.png)

3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们会在1.8.0修复该问题
