### ISSUE TITLE
[QUESTION]dubbo测试可以支持直接配提供方ip么，不配置注册中心地址

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#14267]
### 请描述您的问题

dubbo测试可以支持直接配提供方ip么，不配置注册中心地址

**Comment by Hyyfit** [comment]
感谢反馈，暂不支持。

**Comment by juanmaocxy** [comment]
> 感谢反馈，暂不支持。

我这边查了一下 Registry Center的Protocol填none；Registry Center的address填提供者ip加端口就可以，但是jmeter-plugin-dubbo里有个空指针的问题，修复完就可以

**Comment by Hyyfit** [comment]
您好，目前的设计如此。
根据我们的调研，一般使用dubbo也都是通过配置注册中心的方式来实现的。直接配提供方ip，使用起来并不方便。

**Comment by juanmaocxy** [comment]
> 您好，目前的设计如此。 根据我们的调研，一般使用dubbo也都是通过配置注册中心的方式来实现的。直接配提供方ip，使用起来并不方便。

确实，正常来说一般都是通过配置注册中心进行实现，这个有一个前提就是ms-server跟dubbo部署在一个环境，现在我是本地通过代理访问线上容器里的dubbo，所以比较特殊，jmeter的jar包其实支持了直连的形式，只是有一个空指针的问题，下图是修复后的代码
![image](https://user-images.githubusercontent.com/58592452/172127091-9b49ff2b-3fa9-4cc0-b340-12d9cf99f79b.png)
