### ISSUE TITLE
[BUG] Tag显示需要有分隔

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14266]
### MeterSphere 版本

1.20.4

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/171331047-24ba0690-817a-4256-b037-ba7915de2518.png)

### 重现步骤

浮动框显示多个tag中间没有分隔

**Comment by ltfit** [comment]
后续优化下

**Comment by 35plus** [comment]
ltfit，这个小细节优化，帮忙排期优先级高点，张总这边平台用户是海外用户，包括印度用户。

**Comment by ltfit** [comment]
你好 v1.20.6-lts 接口列表已修复此问题
