### ISSUE TITLE
[BUG]场景a引用场景b，场景b的变量引用不生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#14272]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

场景a引用场景b，场景b的变量引用不生效

### 重现步骤

场景a引用场景b，场景b的自带的变量引用不生效；原场景变量已勾选
![image](https://user-images.githubusercontent.com/43202800/171339483-620cb4a3-a8e7-421e-a1fd-c7aa2cbe32f1.png)

<img width="960" alt="场景a引用场景b，场景b的变量引用不生效" src="https://user-images.githubusercontent.com/43202800/171339396-97fbb9c7-440a-4471-8d96-31b55dd6c49b.png">

### 期待的正确结果

正常引用原场景变量{1.20.3是好的}

**Comment by ltfit** [comment]
已知问题 此问题会在1.20.5版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.5-lts已修复
