### ISSUE TITLE
[BUG]接口测试用例调试成功后，加入到接口自动化场景里，运行报错。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#1428]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.7

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口测试用例调试成功后，加入到接口自动化场景里，运行报错。
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/107141652-34993000-6965-11eb-9da3-705ca057d1ab.png)

**Comment by xulinde** [comment]
您好，未复现您的问题，用例具体有什么配置呢？
