### ISSUE TITLE
【jenkins配置metersphere的job构建失败，报告无法正常生成】

### ISSUE THREAD

**Issue by shpddzj** [metersphere/metersphere#14286]
### MeterSphere 版本

v1.20.4 

### 使用外置数据库

是

### 问题描述

【jenkins配置metersphere的job构建失败，报告无法正常生成】 metersphere版本- v1.20.4  jenkins插件1.20.4
k8s中ms-sever日志中没有jenkins的调用日志

### 重现步骤

【jenkins配置metersphere的job构建失败，报告无法正常生成】 metersphere版本- v1.20.4  jenkins插件1.20.4
k8s中ms-sever日志中没有jenkins的调用日志

**Comment by ltfit** [comment]
你好 你更新1.20.5插件尝试下 最新版本看是生成报告正常
