### ISSUE TITLE
[BUG]用例执行完成后，系统通知中的用户名和当前测试的用户名不一致

### ISSUE THREAD

**Issue by Fit2CloundGhh** [metersphere/metersphere#14291]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

在测试跟踪——>接口Case——>点击执行按钮，用例执行完成之后，系统通知中展示的用户名（为项目管理员的用户名）与当前所登录的用户名（项目成员）不一致，但是“操作日志”处的“操作人”字段是正确的。

### 重现步骤

1、当前操作人角色为项目成员
2、在测试跟踪——>接口Case——>点击执行按钮

### 附加信息

https://user-images.githubusercontent.com/92966838/171384635-71949a90-5cac-421a-9b0c-b1303b8a7bd0.mp4

**Comment by zrfit** [comment]
您好，接口case执行-系统通知名称和执行人不符的问题在最新版本v1.20.5lts版本已修复。
注意：当执行人的名称有变更/新增的成员-执行case时，要强刷下页面，系统通知的名称才会同步更新为执行人的名称，目前暂未做到个人信息名称更新后直接执行case名称实时同步。

**Comment by Fit2CloundGhh** [comment]
收到，给产品组点赞
