### ISSUE TITLE
[QUESTION] 对于MS集成Jira的疑问

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#14301]
### 请描述您的问题

对于MS集成Jira的问题
默认的模板能拿到枚举值，但是不支持自定义字段
自定义的模板支持自定义字段，但是无法拿到枚举值
请问在jira中有自定义字段怎么才能与Jira集成并在提交bug时 获取自定义字段枚举（字段枚举值会增加）

**Comment by Hyyfit** [comment]
“请问在jira中有自定义字段怎么才能与Jira集成并在提交bug时 获取自定义字段枚举（字段枚举值会增加）”
这个问题需要自己抓包看文档，手动配置自定义字段的枚举值。

**Comment by zhouxiongjie1997** [comment]
能自动拿取到枚举值吗，目前自定义的是发布版本号，会根据时间变化而增加枚举项，需要每次都抓包手动添加自定义字段的枚举值吗？
