### ISSUE TITLE
[BUG] [企业用户] 经常被莫名其妙的被登出

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14306]
### MeterSphere 版本

1.20.4

### 使用外置数据库

是

### 问题描述

1.20版本之后，经常遇到正常情况下被系统强制登出的情况，非常不清楚认证信息过期的时间和规律！以前版本没有这么频繁被登出！
![image](https://user-images.githubusercontent.com/103017812/171439340-78007ae6-3c29-4078-955c-6544f589397b.png)

### 重现步骤

没有规律，每天会遇到十几次，有时候时间长有时候时间短！

**Comment by youliyuan-fit2cloud** [comment]
你好，确认一下您这边是不是用了外部不同版本的redis，还有部署机器配置是？我们看下是不是这些原因，谢谢~！

**Comment by 35plus** [comment]
liyuan，客户这边是标准安装，未使用外部redis。这个问题我们在别的客户那里也有碰到。
