### ISSUE TITLE
[BUG]断言空列表为空不成功

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#14300]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

是

### 问题描述

断言空列表为空不成功

### 重现步骤

![image](https://user-images.githubusercontent.com/23476281/171402117-97484388-819d-40b9-990b-ffd81d54a7cf.png)

**Comment by zrfit** [comment]
你好，未复现该问题，空列表可断言成功呢，您执行断言失败的报错是什么？响应内容的断言tab页截图看看，将响应josn体复制粘贴出来我们mock下试试。
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/99731894/171572777-c23a5ae2-29df-46ec-b937-677f4206c9a7.png">

**Comment by chase001** [comment]
请用以下返回数据格式：断言： "tsPavilionVOList": [
                
            ]

{
    "code": "200",
    "msg": "success",
    "data": [
        {
            "tradeshowId": 2808800066303,
            "tsName": "Consumer Electronics Show",
            "tsShortName": "HONGKONG-ELECTONICS-2022-OCT",
            "tsLocation": "AsiaWorld-Expo",
            "tsCountryCode": "HK",
            "tsCountryDesc": "",
            "tsStartDate": 1665417600000,
            "tsEndDate": 1665676800000,
            "tsGrpId": 2808800066303,
            "tsGrpCode": "EC",
            "tsLogoUrl": "",
            "tsImageUrl": "",
            "tsIds": "",
            "tsPavilionVOList": [
                
            ]
        },
        {
            "tradeshowId": 2808800066329,
            "tsName": "Mobile Electronics Show",
            "tsShortName": "HONGKONG-MOBILE-ELECTONICS-2022-OCT",
            "tsLocation": "AsiaWorld-Expo",
            "tsCountryCode": "HK",
            "tsCountryDesc": "",
            "tsStartDate": 1666022400000,
            "tsEndDate": 1666281600000,
            "tsGrpId": 2808800066329,
            "tsGrpCode": "ME",
            "tsLogoUrl": "",
            "tsImageUrl": "",
            "tsIds": "",
            "tsPavilionVOList": [
                
            ]
        },
        {
            "tradeshowId": 2808800066337,
            "tsName": "Smart Home & Appliances Show",
            "tsShortName": "HONGKONG-SMART-HOME-APPLIANCES-2022-OCT",
            "tsLocation": "AsiaWorld-Expo",
            "tsCountryCode": "HK",
            "tsCountryDesc": "",
            "tsStartDate": 1666022400000,
            "tsEndDate": 1666281600000,
            "tsGrpId": 2808800066337,
            "tsGrpCode": "SHA",
            "tsLogoUrl": "",
            "tsImageUrl": "",
            "tsIds": "",
            "tsPavilionVOList": [
                
            ]
        },
        {
            "tradeshowId": 2808800066352,
            "tsName": "Home & Kitchen Show",
            "tsShortName": "HONGKONG-HOME-KITCHEN-2022-OCT",
            "tsLocation": "AsiaWorld-Expo",
            "tsCountryCode": "HK",
            "tsCountryDesc": "",
            "tsStartDate": 1666022400000,
            "tsEndDate": 1666281600000,
            "tsGrpId": 2808800066352,
            "tsGrpCode": "HK",
            "tsLogoUrl": "",
            "tsImageUrl": "",
            "tsIds": "",
            "tsPavilionVOList": [
               
            ]
        },
        {
            "tradeshowId": 2808800067384,
            "tsName": "Fashion show",
            "tsShortName": "HONGKONG-FASHION-2022-OCT",
            "tsLocation": "ASIA-WORLD EXPO",
            "tsCountryCode": "HK",
            "tsCountryDesc": "",
            "tsStartDate": 1666627200000,
            "tsEndDate": 1666800000000,
            "tsGrpId": 2808800067384,
            "tsGrpCode": "FA",
            "tsLogoUrl": "",
            "tsImageUrl": "",
            "tsIds": "",
            "tsPavilionVOList": [
                
            ]
        }
    ],
    "timestamp": "2022-06-06 16:28:18"
}

**Comment by zrfit** [comment]
您好，最新版本用您的数据进行断言也是可以成功的。
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/99731894/172147564-86e046b7-1c8e-45d2-b6b5-157b4bb4d76e.png">

**Comment by chase001** [comment]
版本:   v1.20.5-lts-9fe3acfd
是断言不为空，断言不等于

![image](https://user-images.githubusercontent.com/23476281/172333884-c1445ed5-3575-4933-bc09-8822f9fff672.png)

![image](https://user-images.githubusercontent.com/23476281/172333921-3a24ded3-2c98-496b-8df9-18059956e73a.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，开始理解错了，已经反馈给研发，后续版本修复。

**Comment by zrfit** [comment]
您好，经过和研发沟通：
1、数组不应该当成字符断言校验
2、如果非要当字符串判断，等于是完全匹配，不需要加 \ 来做转译

**Comment by chase001** [comment]
还是不成功，麻烦给确认法说

![image](https://user-images.githubusercontent.com/23476281/172652071-ba104586-d793-419e-819f-f497b74c18e5.png)

![image](https://user-images.githubusercontent.com/23476281/172651988-d12375a9-fc85-4494-91ac-20dde51b1178.png)

**Comment by zrfit** [comment]
您好，其实数组不应该当成字符断言校验的，非要这么断言的话，后续版本我们优化下不等于[]，断言失败。

**Comment by zrfit** [comment]
v1.20.7-lts已修复。
