### ISSUE TITLE
[FEATURE] 消息提醒：批量执行很多场景时，有一个场景失败，那这个场景之后执行的消息提醒都是失败的（哪怕是成功的）

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#14307]
### 联系方式

Limon

### MeterSphere 版本

1.20.4-lts

### 使用外置数据库

否

### 问题描述

消息提醒：批量执行很多场景时，有一个场景失败，那这个场景之后执行的消息提醒都是失败的（哪怕是成功的）

### 重现步骤

前提：配置消息提醒，模板如下：
【失败】场景名称：\\${name}，步骤总数：\\${stepTotal}，通过率：\\${passRate}，模块路径：\\${modulePath}，执行人：\\${operator}，查看详情：\\${reportUrl}

1. 在接口自动化中，选择多个场景（这个场景里至少有一个失败）
2. 批量执行场景

### 期待的正确结果

成功的用例标记为成功，失败的就是失败！

### 附加信息

![image](https://user-images.githubusercontent.com/44999044/171524085-05056783-6dec-4aa4-bc68-df241c784443.png)

**Comment by zyyfit** [comment]
这个是因为你生成了一个集合报告，然后整个集合报告里只要有一个场景是失败的，这个集合报告就是失败的，然后这些场景获取的报告状态都是这个集合报告的状态，所以就都是失败了

**Comment by LimonFHM** [comment]
> 这个是因为你生成了一个集合报告，然后整个集合报告里只要有一个场景是失败的，这个集合报告就是失败的，然后这些场景获取的报告状态都是这个集合报告的状态，所以就都是失败了

但是消息提醒里面是场景名称，然后测试结果又是集合结果，不是很矛盾么。而且是有一部分是正常，一部分是失败，这里面逻辑应该是有问题的。希望修复

**Comment by Hyyfit** [comment]
已规划，待排期。
