### ISSUE TITLE
[BUG] 浏览器缩放后页面排版异常（主要是放大）

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#14313]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

浏览器缩放设置成105%，直接打开MeterSphere部分页面显示排版异常，看着别扭。
浏览器默认缩放可能会越来越常见，屏幕大小不变，分辨率越高，不缩放一下，有的文字图案就显示的越小

### 重现步骤

电脑屏幕分辨率1920*1080，360浏览器（13.1.5360.0），平时浏览器是设置的105%缩放，直接打开MeterSphere的话，像接口定义》接口列表，这个位置，操作栏一列，显示的排版有问题；如果变成正常的100%，会显示正常，如果再放大到105%，排版就是正常的。从去年10版本乃至更早，一直到最近几天下载的新版本，都有这个问题。

### 期待的正确结果

能像先100%，打开页面后，调整到105%一样正常显示。

### 附加信息

105%直接打开：
![image](https://user-images.githubusercontent.com/42863606/171545679-c890afe9-a68b-4dc5-9c8c-c6b632daf25a.png)

还原到100%，打开后，再调整到105%：
![image](https://user-images.githubusercontent.com/42863606/171545723-fe3d7b37-2a3f-49db-ae18-f799758ebbce.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这个问题我们内部讨论了一下，暂时不处理。
因为页面布局是考虑到大部分用户的使用习惯，默认按照100%来设置操作列的宽度。 
为了方便用户操作，MS表格中有很多操作列是采用了冻结的交互设计。
这种交互设计使得操作列需要一个列宽，满足“默认情况下不会影响样式错位”和“尽可能更多的展示其余列数据”两种要求。 这样的情况下改变页面的缩放比例确实有可能出现这样的事情。
同时我们以chrome浏览器作为主流浏览器，发现chrome浏览器设置110%是不会引起换行的。如有需要可以更换chrome浏览器
