### ISSUE TITLE
[BUG]通过Jenkins执行测试计划，MeterSphere中测试报告中测试结果统计的用例状态错误

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1431]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.7.2-bd12a36a
Jenkins插件版本1.7.2
**Bug 描述**

简要描述您碰到的问题
通过Jenkins执行测试计划，MeterSphere中测试报告中测试结果统计的用例状态错误

**Bug 重现步骤**
1.  在测试跟踪中新建测试计划，并关联场景测试用例
2. 在Jenkins中配置执行该测试计划
3. 执行完成后回到MeterSphere的测试跟踪/测试报告中查看生成的测试报告
4. 测试结果统计 中 场景测试用例的状态一直为“进行中”

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/57166905/107143310-5eefeb00-696f-11eb-9d0b-c3fe2217fb87.png)

**Comment by xulinde** [comment]
您好，按照您的复现步骤，我们没复现该问题

**Comment by xulinde** [comment]
![Uploading image.png…]()

**Comment by cyw16076** [comment]
Jenkins执行测试计划后，会在【测试跟踪/测试报告】中生成一个测试计划的报告并在【接口测试/测试报告】中每个测试场景生成一个报告，后者展示正常，前者存在本bug描述的问题

**Comment by xulinde** [comment]
和issue#1528重复
