### ISSUE TITLE
[BUG]【测试跟踪>>测试用例详情】维护用例“后置用例”，点击【依赖关系图】系统异常，有空指针

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#14318]
### MeterSphere 版本

1.20.4

### 使用外置数据库

否

### 问题描述

[BUG]【测试跟踪>>测试用例详情】维护用例“后置用例”，点击【依赖关系图】系统异常，有空指针

### 重现步骤

1、测试跟踪>>功能测试用例：选择一个测试用例，此测试用例没有维护前后置用例
2、维护该测试用例后置用例
3、点击依赖关系图，系统出现异常
4、查看后台日志，有空指针

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/171552104-24b5b93b-1b70-41fa-af66-13d0781e719c.png)
![image](https://user-images.githubusercontent.com/78218624/171552143-137a3b41-55bf-4441-a56b-bd2b8ad79902.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请检查一下 浏览器控制台信息，如下图，
![image](https://user-images.githubusercontent.com/54612864/171562777-86c887f6-65ad-4074-aed4-3ac6a81f73ef.png)

如果100%复现，请上传控制台的截图信息，谢谢~
