### ISSUE TITLE
[FEATURE]metersphere数据操作没有防并发设计

### ISSUE THREAD

**Issue by QPY7** [metersphere/metersphere#14327]
### MeterSphere 版本

<modelVersion>4.0.0</modelVersion>     <groupId>io.metersphere</groupId>     <artifactId>metersphere-server</artifactId>     <version>1.9</version>     <packaging>pom</packaging>

### 请描述您的需求或者改进建议

针对同一数据，多个tab页打开，很容易造成数据被误操作覆盖的情况

### 请描述你建议的实现方案

1. 一个数据，不允许多个tab页面打开。在次点击数据，跳转到已打开的tab页面。但是这个解决不了多浏览器/多人同时操作相同数据的情况。
2. 数据库字段中加version字段，用乐观锁来控制并发

**Comment by liqiang-fit2cloud** [comment]
感谢建议。
目前MeterSphere的处理逻辑跟其他大部分系统一样，一个数据可以在多个tab或者多人同时打开，先保存的会被后保存的覆盖，数据以最后一次保存操作为准。
目前还没有计划优化这个逻辑。

**Comment by QPY7** [comment]
了解，不过还是建议可以先优化下体验，就是一个数据只能一个tab打开。这是我目前在设计复杂自动化用例时，遇到的一个体验上痛点

**Comment by QPY7** [comment]
为什么我提到防并发的想法。 其实是为了达到自动化用例参数化，模块化，可复用等目标，我需要编写大量的自定义脚本。而体验上以及防并发的问题，我的脚本会被覆盖，影响了我的工作。目前我可以通过改变我的习惯，来适应平台。可是，后续如果我要在公司内部进行推广，可能这类问题会成为一定的阻碍。 
当然我还是希望如果你们有什么好的复杂场景的自动化实践，可以分享到你们的使用文档中，让大家来进行参考和学习~
