### ISSUE TITLE
关于请求数量的问题

### ISSUE THREAD

**Issue by suyehen** [metersphere/metersphere#14323]
### 请描述您的问题

你好，我使用ms做发压，仅压测一个无逻辑的get接口，以100的并发数运行了20s，其发出请求的数量是在20w左右。
但是在同一台发压机器上面，我们使用wrk，以32线程100连接数压测20s，wrk在运行完成后一共发压了234w的请求数量。
在使用不同压测工具的情况下，产生了10倍以上的差距，请问一下这种差距是由什么情况造成的
![微信截图_20220602145620](https://user-images.githubusercontent.com/56217825/171571381-7046d25c-2beb-434e-b8e5-77b5cb87336b.png)
![微信截图_20220602145639](https://user-images.githubusercontent.com/56217825/171571389-aabd3676-bf2c-4600-8cae-759500f52983.png)
![微信截图_20220602145650](https://user-images.githubusercontent.com/56217825/171571393-24cdf288-da33-42fd-b6d1-8f20ba355a83.png)

**Comment by liuruibin** [comment]
我们后台使用JMeter作为压测引擎，开源版使用后置监听器(BackendListener)采集结果，这种方式在接口响应短的情况下会使得数据处理成为瓶颈。你可以试用企业版，资源池关闭后置监听器再进行测试
