### ISSUE TITLE
[BUG]接口提取参数匹配多条，场景中循环执行该接口，每次循环后的${varName_matchNr}都是一样的

### ISSUE THREAD

**Issue by wly6** [metersphere/metersphere#14333]
### 联系方式

交流群39

### MeterSphere 版本

1.19.3

### 使用外置数据库

否

### 问题描述

接口提取参数匹配多条，场景中循环执行该接口，每次循环后的${varName_matchNr}都是一样的

### 重现步骤

操作：
1.【接口测试】》【接口定义】：在接口的后置操作中提取参数varName并匹配多条
2.【接口测试】》【接口自动化】：设置场景为循环执行该接口
现象：
每次循环后的`${varName_matchNr}`跟循环1的`${varName_matchNr}`是一样的

### 附加信息

![企业微信截图_16541566201563](https://user-images.githubusercontent.com/24427809/171589192-6739c9ce-cf4e-4478-bdcf-d12feab797df.png)
![企业微信截图_16541566392586](https://user-images.githubusercontent.com/24427809/171589212-28cb867e-357a-44c9-9887-66e516fb02e5.png)

**Comment by zyyfit** [comment]
如果这个接口每次提取到的varName数量都是一样的，那每次的${varName_matchNr}也是一样的。
我试了一下最新版1.20.5是正常的，如果1.19.3有问题的话建议升级版本。

**Comment by wly6** [comment]
> 如果这个接口每次提取到的varName数量都是一样的，那每次的${varName_matchNr}也是一样的。 我试了一下最新版1.20.5是正常的，如果1.19.3有问题的话建议升级版本。

升级到2.0.0版本了，还是有此问题
