### ISSUE TITLE
[FEATURE]服务集成-缺陷管理平台，建议增加redmine选项

### ISSUE THREAD

**Issue by geyesheng** [metersphere/metersphere#14332]
### MeterSphere 版本

v1.20.5-lts-9fe3acfd

### 请描述您的需求或者改进建议

服务集成-缺陷管理平台，建议增加redmine选项
![image](https://user-images.githubusercontent.com/38676947/171584482-e541a9be-3653-44a0-9d63-29232932a2c9.png)

**Comment by Hyyfit** [comment]
感谢您的反馈，是否集成redmine 还需要调研。
