### ISSUE TITLE
[BUG]Jenkins构建成功发送邮件中报告链接错误

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1434]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.2-bd12a36a
Jenkins插件版本  v1.7.2

**Bug 描述**
简要描述您碰到的问题
Jenkins构建成功发送邮件中报告链接错误

**Bug 重现步骤**
1.  Jenkins中配置执行测试计划，并在MeterSphere中配置Jenkins构建成功后发送邮件
2. Jenkins中构建
3. 访问发送邮件中的测试报告页面的链接
4. 

**期待的正确结果**
正确情况下应该是什么样的？
正确打开测试报告，实际提示测试报告不存在

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/57166905/107167070-d87ced00-69f2-11eb-92d7-a8bd0e24e4a2.png)
![image](https://user-images.githubusercontent.com/57166905/107167118-f5b1bb80-69f2-11eb-82e2-8173e7a91dc7.png)

**Comment by xulinde** [comment]
感谢您的反馈，这个问题会在1.8.0修复

**Comment by xulinde** [comment]
执行的新版测试，要点击新版报告链接，不是点击旧版本链接
