### ISSUE TITLE
[BUG]自定义代码片段运行，无法打印出中文

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14349]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

自定义代码片段运行，无法打印出中文
![QQ拼音截图未命名3 (1)](https://user-images.githubusercontent.com/38156471/171757724-aa46aebc-10dc-42ec-93ba-f6f6306bbd40.jpg)

### 重现步骤

自定义代码片段运行，无法打印出中文
![QQ拼音截图未命名3 (1)](https://user-images.githubusercontent.com/38156471/171757724-aa46aebc-10dc-42ec-93ba-f6f6306bbd40.jpg)

### 期待的正确结果

支持中文打印

**Comment by youliyuan-fit2cloud** [comment]
端午还卷呢😅

**Comment by zyyfit** [comment]
这种问题可以在脚本里手动处理一下，有以下几种解决方法：
1、在中文前面加上个小u标记，如：s = u"中文"
2、中文内容强制转换为unicode编码，如：
s = "中文"
u = s.decode('utf-8')

**Comment by YellCatt** [comment]
> 这种问题可以在脚本里手动处理一下，有以下几种解决方法：
> 1、在中文前面加上个小u标记，如：s = u"中文"
> 2、中文内容强制转换为unicode编码，如：
> s = "中文"
> u = s.decode('utf-8')

好的，感谢
