### ISSUE TITLE
[BUG]IntelliJ IDEA 2022.1.2 (Community Edition) 无法安装MeterSphere IDEA插件。

### ISSUE THREAD

**Issue by whthomas** [metersphere/metersphere#14353]
### 联系方式

whthomas@163.com

### MeterSphere 版本

 v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

IntelliJ IDEA 2022.1.2 (Community Edition) 无法安装MeterSphere IDEA插件。

### 重现步骤

从磁盘安装会有以下提示:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/4974467/172038762-26060361-dde3-4583-881b-d3d2bf85edec.png">

**Comment by zrfit** [comment]
您好，提示信息已经提示您不兼容了，请下载最新版本1.0.5安装。
