### ISSUE TITLE
[BUG]接口用例界面没有高级搜索按钮,原来的版本有的

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#14351]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

接口用例界面没有高级搜索按钮,原来的版本有的 

### 重现步骤

接口测试,case ta
<img width="1349" alt="WeChat8faa651eef8ae202c1a44d34eadea310" src="https://user-images.githubusercontent.com/10231088/171986716-f0d967ef-fb81-46b7-880c-19e6e8109cb4.png">
b

**Comment by zyyfit** [comment]
您好，我看1.18和1.19版本都没有高级搜索，您是说哪个版本有呢？

**Comment by zyyfit** [comment]
刚跟产品经理确认了，2.0版本会增加高级搜索功能

**Comment by wudamyw** [comment]
> 您好，我看1.18和1.19版本都没有高级搜索，您是说哪个版本有呢？

最早的版本是有的，忘记哪个版本了

**Comment by youliyuan-fit2cloud** [comment]
v2.0.0中已实现该功能。
