### ISSUE TITLE
[BUG]在CASE中设置两个前置脚本，第二个脚本运行的时候报错

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14350]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

代码片段代码和结果
![代码片段代码](https://user-images.githubusercontent.com/38156471/171759056-c85ba595-653e-489c-bdc7-5aa181fa081c.jpg)
![代码片段代码执行结果](https://user-images.githubusercontent.com/38156471/171759065-dac5e341-f187-4b06-a248-faf0a22e8cc0.jpg)

CASE代码片段代码和结果
![CASE代码片段代码](https://user-images.githubusercontent.com/38156471/171759110-2032519c-1872-4f9c-b016-729b5a6f3ff5.jpg)
![CASE代码片段代码执行结果](https://user-images.githubusercontent.com/38156471/171759128-9e4d9647-5d65-4727-a072-bf16c34b84a4.jpg)

### 重现步骤

代码片段代码和结果
![代码片段代码](https://user-images.githubusercontent.com/38156471/171759056-c85ba595-653e-489c-bdc7-5aa181fa081c.jpg)
![代码片段代码执行结果](https://user-images.githubusercontent.com/38156471/171759065-dac5e341-f187-4b06-a248-faf0a22e8cc0.jpg)

CASE代码片段代码和结果
![CASE代码片段代码](https://user-images.githubusercontent.com/38156471/171759110-2032519c-1872-4f9c-b016-729b5a6f3ff5.jpg)
![CASE代码片段代码执行结果](https://user-images.githubusercontent.com/38156471/171759128-9e4d9647-5d65-4727-a072-bf16c34b84a4.jpg)

**Comment by zyyfit** [comment]
您好，最新版1.20.5没有复现这个问题，您可以升级试试，如果还是报错的话，可以把第一个脚本的内容贴上来看看吗？
![image](https://user-images.githubusercontent.com/73461316/172100204-8c58a48a-3b9f-4a48-90ce-cf222c5ffc26.png)

**Comment by YellCatt** [comment]
> 您好，最新版1.20.5没有复现这个问题，您可以升级试试，如果还是报错的话，可以把第一个脚本的内容贴上来看看吗？ ![image](https://user-images.githubusercontent.com/73461316/172100204-8c58a48a-3b9f-4a48-90ce-cf222c5ffc26.png)
[新建文本文档.txt](https://github.com/metersphere/metersphere/files/8845426/default.txt)

**Comment by zyyfit** [comment]
你贴的这个链接点过去之后是not found，重新上传一下吧，等上传加载完再点提交，或者如果脚本内容没有转义的话，可以直接贴到评论里

**Comment by YellCatt** [comment]
> 你贴的这个链接点过去之后是not found，重新上传一下吧，等上传加载完再点提交，或者如果脚本内容没有转义的话，可以直接贴到评论里

[7.8.1.txt](https://github.com/metersphere/metersphere/files/8851824/7.8.1.txt)

**Comment by YellCatt** [comment]
> > 你贴的这个链接点过去之后是not found，重新上传一下吧，等上传加载完再点提交，或者如果脚本内容没有转义的话，可以直接贴到评论里
> 
> [7.8.1.txt](https://github.com/metersphere/metersphere/files/8851824/7.8.1.txt)

提交了

**Comment by zyyfit** [comment]
直接使用你文件里的脚本执行会报这个错误，我改了一下执行是正常的
_socket.gaierror: [Errno 8] nodename nor servname provided, or not known in <script> at line number 63

![image](https://user-images.githubusercontent.com/73461316/172363122-b3ba6687-532b-4c37-9cf2-1e4fc0bc66a8.png)

**Comment by YellCatt** [comment]
> 直接使用你文件里的脚本执行会报这个错误，我改了一下执行是正常的 _socket.gaierror: [Errno 8] nodename nor servname provided, or not known in <script> at line number 63
> 
> ![image](https://user-images.githubusercontent.com/73461316/172363122-b3ba6687-532b-4c37-9cf2-1e4fc0bc66a8.png)

你修改了什么才能让脚本正常？

**Comment by zyyfit** [comment]
我把脚本1改成这样了，脚本2没改，而且既然你脚本1里的import time没报错的话，脚本2里应该也可以正常执行的
[脚本1.txt](https://github.com/metersphere/metersphere/files/8852587/1.txt)

**Comment by YellCatt** [comment]
> > 我把脚本1改成这样了，脚本2没改，而且既然你脚本1里的import time没报错的话，脚本2里应该也可以正常执行的
> > [脚本1.txt](https://github.com/metersphere/metersphere/files/8852587/1.txt)
> 
> 可以说明下为什么那么修改吗？我是用自动生成的代码做稍微的修改，也不应该会报错啊


> 我把脚本1改成这样了，脚本2没改，而且既然你脚本1里的import time没报错的话，脚本2里应该也可以正常执行的
> [脚本1.txt](https://github.com/metersphere/metersphere/files/8852587/1.txt)

而且我也是在代码片段里运行过没有问题，才放在里面的

**Comment by YellCatt** [comment]
> > 我把脚本1改成这样了，脚本2没改，而且既然你脚本1里的import time没报错的话，脚本2里应该也可以正常执行的
> > [脚本1.txt](https://github.com/metersphere/metersphere/files/8852587/1.txt)
> 
> 可以说明下为什么那么修改吗？我是用自动生成的代码做稍微的修改，也不应该会报错啊

而且我两个脚本合并在一起，是可以执行通的

**Comment by zyyfit** [comment]
我不懂python，就是看报错里显示这一行有报错，就直接把方法体里的内容都拿出来了。。。

**Comment by YellCatt** [comment]
> 我不懂python，就是看报错里显示这一行有报错，就直接把方法体里的内容都拿出来了。。。

我自己再次试了下，其实就是不支持在多个脚本中使用函数

**Comment by zyyfit** [comment]
> > 我不懂python，就是看报错里显示这一行有报错，就直接把方法体里的内容都拿出来了。。。
> 
> 我自己再次试了下，其实就是不支持在多个脚本中使用函数

哦哦，那这个问题就是解决了？还有其他问题吗？
