### ISSUE TITLE
[BUG] 测试计划中的StandardJMeterEngine关闭报错

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#14359]
### MeterSphere 版本

v1.20.2-lts-0f489ee9

### 使用外置数据库

是

### 问题描述

2022-06-04 17:00:24 WARN StandardJMeterEngine Error encountered during shutdown of org.apache.jmeter.testelement.TestPlan@5ef09458
null
java.lang.NullPointerException

### 重现步骤

测试计划执行

### 相关日志输出

```shell
2022-06-04 17:00:24 WARN StandardJMeterEngine Error encountered during shutdown of org.apache.jmeter.testelement.TestPlan@5ef09458
null
java.lang.NullPointerException
```

### 附加信息

![vc2oJHN7sU](https://user-images.githubusercontent.com/25195509/172083120-c74bdc2d-c597-44cb-8f87-7d0374f1af83.png)

**Comment by ltfit** [comment]
你好 你更新到1.20.5 最新版本尝试下 我在新版本测试正常

**Comment by ltfit** [comment]
你好，你这个是什么场景出现的问题呢

**Comment by feng2076** [comment]
测试计划的定时任务运行后

**Comment by ltfit** [comment]
这个测试计划 具体里面的场景提供下吧

**Comment by feng2076** [comment]
![image](https://user-images.githubusercontent.com/25195509/172272432-db83b9cf-4974-4a1f-a6f7-70beb8b5e235.png)
任意接口自动化场景，手动执行也会复现

**Comment by ltfit** [comment]
你好 升级到1.20.5-lts  最新版本修复了
