### ISSUE TITLE
[BUG]全局环境变量中不能使用:冒号，不然在前置脚本运行中会出现报错

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14357]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

全局环境变量中不能使用:冒号，不然在前置脚本中会出现报错
![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/172059651-486d3d72-5dec-4e5b-a509-3b88d630171f.jpg)
![QQ拼音截图未命名](https://user-images.githubusercontent.com/38156471/172059665-afe38a0d-d77f-4982-8d2a-6d1fb6712b10.jpg)

### 重现步骤

全局环境变量中不能使用:冒号，不然在前置脚本中会出现报错
![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/172059651-486d3d72-5dec-4e5b-a509-3b88d630171f.jpg)
![QQ拼音截图未命名](https://user-images.githubusercontent.com/38156471/172059665-afe38a0d-d77f-4982-8d2a-6d1fb6712b10.jpg)

### 期待的正确结果

可以在环境变量中使用任何特殊符号

**Comment by zrfit** [comment]
您好，python脚本错误，应该是host = "${es_host}"

**Comment by zrfit** [comment]
您好，python脚本错误，应该是host = "${es_host}"

**Comment by YellCatt** [comment]
> 您好，python脚本错误，应该是host = "${es_host}"

我引用的是环境变量啊，不是我在代码中创建的变量啊

**Comment by YellCatt** [comment]
> 但是实际你这个环境变量最终也是个字符串，python语法中字符串就是要用“”或‘’括起来。
> 或者脚本中你非要这么写的话，那么环境变量配置中的字符串值用“”或‘’括起来也能调用成功。

谢了，可以用了
