### ISSUE TITLE
[BUG]测试计划运行后，报告状态始终是running，但是实质上已经运行完毕，大概五次出现一次

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14356]
### 联系方式

768305875@qq.com

### MeterSphere 版本

 v1.20.4-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

测试计划运行后，状态始终是running，但是实质上已经运行完毕，大概五次出现一次
![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/172059504-6d4f3bda-0af7-4f40-9865-2e21ecd89837.jpg)
![QQ拼音截图未命名2](https://user-images.githubusercontent.com/38156471/172059508-ec706c40-500b-4e95-8404-63509074b75a.jpg)

### 重现步骤

测试计划运行后，状态始终是running，但是实质上已经运行完毕，大概五次出现一次
![QQ拼音截图未命名1](https://user-images.githubusercontent.com/38156471/172059504-6d4f3bda-0af7-4f40-9865-2e21ecd89837.jpg)
![QQ拼音截图未命名2](https://user-images.githubusercontent.com/38156471/172059508-ec706c40-500b-4e95-8404-63509074b75a.jpg)

### 期待的正确结果

最好是没有运行完毕，就不要出现报告了

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
