### ISSUE TITLE
[BUG]UI自动化用例执行时，经常一直转圈也不报错不结束。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#14352]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

UI自动化用例执行时，经常一直转圈也不报错不结束。

### 重现步骤

UI自动化用例执行时，经常一直转圈也不报错不结束
<img width="1538" alt="WeChat942f922ad78b0a806c2c43f35414d255" src="https://user-images.githubusercontent.com/10231088/171995440-47c962ae-4578-4bb4-ba9b-5f5d2be2e578.png">
。

**Comment by zrfit** [comment]
您好，未复现该问题，是否方便讲场景导出我们尝试复现。

**Comment by wudamyw** [comment]
可以故意把一些步骤的xpath 写为其他页面的路径，尝试一下。其实就是对每一步的异常情况有没有都处理

**Comment by zrfit** [comment]
您好，这边尝试多次未复现，xpath错误会进入超时判断的逻辑，场景下每个步骤是有异常处理的：高级设置：1、错误处理 2、其它设置-等待元素超时-默认15s，这2个设置均对步骤的异常情况进行了处理。
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/99731894/174520116-decf1820-2300-4fa2-87e4-5847b8ccc8cd.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/99731894/174520254-95e5ecb1-316a-4585-b4ef-7f41cc7202bb.png">
您的场景有什么操作步骤？操作步骤下又有什么配置？最好能导出场景，我们尝试复现。

**Comment by wudamyw** [comment]
> 您好，这边尝试多次未复现，xpath错误会进入超时判断的逻辑，场景下每个步骤是有异常处理的：高级设置：1、错误处理 2、其它设置-等待元素超时-默认15s，这2个设置均对步骤的异常情况进行了处理。 <img alt="image" width="1151" src="https://user-images.githubusercontent.com/99731894/174520116-decf1820-2300-4fa2-87e4-5847b8ccc8cd.png"> <img alt="image" width="1163" src="https://user-images.githubusercontent.com/99731894/174520254-95e5ecb1-316a-4585-b4ef-7f41cc7202bb.png"> 您的场景有什么操作步骤？操作步骤下又有什么配置？最好能导出场景，我们尝试复现。

你们交付和客服知道。我用的企业版。

**Comment by zrfit** [comment]
已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.10-lts已修复。
