### ISSUE TITLE
kubernetes 部署metersphere提示Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.3-ms5-jdk11

### ISSUE THREAD

**Issue by 10779164** [metersphere/metersphere#14363]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/25604376/172086886-1f3e5d98-197e-41f8-9a7a-13d9606b8f82.png)

参考官方文档使用helm部署的metersphere，创建测试、点击保存 提示图片中的错误 ；

**Comment by 10779164** [comment]
已解决 ； 在node所部署的节点 手动pull该镜像即可

**Comment by bruseebins** [comment]
咋处理的啊，处理步骤能分享吗
