### ISSUE TITLE
[BUG]性能测试24小时稳定性的报告时间缺少8小时

### ISSUE THREAD

**Issue by hmilyjch** [metersphere/metersphere#1437]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.1-66e9f091
**Bug 描述**
24小时稳定性场景
“测试概览”曲线图缺少8小时左右的时间

**Bug 重现步骤**
1.  运行24小时性能测试场景
2. 查看“测试报告”，测试概览中各趋势图中缺少了8小时左右的记录

**期待的正确结果**
显示所有时间段的测试趋势图

**截图**
如果有截图，请附上截图.
![微信图片_20210208110943](https://user-images.githubusercontent.com/43428113/107171775-8b9f1380-69fe-11eb-9bef-ced8de394c3f.png)

**Comment by liuruibin** [comment]
执行时间在凌晨零点的时候变成了 00:00:00 在排序的时候放到了前面，这里会把执行日期加上方便查看
