### ISSUE TITLE
[BUG]导入接口自动化用例，在原用例场景变量中有添加csv变量时(导入生成的用例中未上传csv)，点击调试按钮报错后，调试按钮应仍显示为调试，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#14372]
### MeterSphere 版本

1.20.5lts

### 使用外置数据库

否

### 问题描述

导入接口自动化用例，在原用例场景变量中有添加csv变量时(导入生成的用例中未上传csv)，点击调试按钮报错后，调试按钮应仍显示为调试，请修改

### 重现步骤

1.在新项目/新环境上上传接口自动化用例(原用例中有csv场景变量)，导入成功后，配置好运行环境，点击调试；

### 期待的正确结果

1.调试报错缺少csv文件，实际调试未执行，调试按钮仍显示为：调试；

### 附加信息

![bd50320e36bcf4e20fde1a6c8ed4986](https://user-images.githubusercontent.com/92150453/172101586-51f815e6-fb8a-4f4a-a57b-f96bcf37454f.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，下个小版本修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.6-lts版本中已修复
