### ISSUE TITLE
关于metersphereUI测试脚本编写完成之后，如何定时执行（与统一执行）的问题

### ISSUE THREAD

**Issue by Cody6S** [metersphere/metersphere#14373]
### 请描述您的问题

步骤重现：
1.点击全部场景
![image](https://user-images.githubusercontent.com/105691386/172103105-0a6532a6-6dc1-4e57-9085-97b9dad1f5e8.png)
图二（对比接口测试场景）：
![image](https://user-images.githubusercontent.com/105691386/172103188-6578594d-996e-4635-ab47-bd1d182a5a67.png)
目前使用过程中没有发现可以一并执行或者定时执行的按钮。
若metersphere平台包含以上功能，请指示

**Comment by Hyyfit** [comment]
感谢反馈，该功能还未上线。
我们已规划了2.0版本，UI可支持批量执行；也支持加入到测试计划中，支持测试计划的定时执行。到时候可以体验哈～

**Comment by Cody6S** [comment]
目前我的版本为:   v1.20.4-lts-5b8b8d82

**Comment by Cody6S** [comment]
可以在更新这个功能后发我邮箱通知一下吗？我非常需要这个功能，希望第一时间进行更新并使用！！！

**Comment by Cody6S** [comment]
因为我不清楚你们这边哪个版本会更新更新此功能（一般小版本我们运维这边不会更新）

**Comment by Hyyfit** [comment]
好的。

**Comment by Cody6S** [comment]
非常感谢！

**Comment by Cody6S** [comment]
1163753544@qq.com
