### ISSUE TITLE
[BUG]测试计划执行用例时，查看依赖关系页面展示有问题，出现了编辑框

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14378]
### 联系方式

张树彬

### MeterSphere 版本

1.20.4

### 使用外置数据库

否

### 问题描述

测试计划执行用例时，查看依赖关系页面展示有问题，出现了编辑框

### 重现步骤

1. 测试计划-功能用例列表
2. 点击任意功能用例进入执行页面
3. 点击依赖关系拓扑图
4. 页面显示有问题，出现了编辑框

### 期待的正确结果

页面正常显示，不展示除依赖关系图形外的内容

### 附加信息

![1654500388514](https://user-images.githubusercontent.com/77324661/172115449-e8df9280-ddd0-4576-978f-a5d837844f9a.jpg)

**Comment by ltfit** [comment]
后续修复下

**Comment by zyyfit** [comment]
1.20.7版本修复，请等待版本发布后验证
