### ISSUE TITLE
接口测试模块--接口自动化，执行场景时，会出现内存溢出，整个平台环境崩溃打不开了

### ISSUE THREAD

**Issue by liangweijie99** [metersphere/metersphere#1438]
**MeterSphere 版本**

v1.7.2 

**Bug 描述**

执行场景时，会出现内存溢出，整个平台环境崩溃打不开了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![Dingtalk_20210208113440](https://user-images.githubusercontent.com/74578958/107173395-a83d4a80-6a02-11eb-859e-8ac0739cdf3a.jpg)
![Dingtalk_20210208113510](https://user-images.githubusercontent.com/74578958/107173416-b12e1c00-6a02-11eb-9005-20925e9c067e.jpg)
![Dingtalk_20210208113536](https://user-images.githubusercontent.com/74578958/107173430-b8edc080-6a02-11eb-8746-b370315302be.jpg)
![Dingtalk_20210208113547](https://user-images.githubusercontent.com/74578958/107173433-bd19de00-6a02-11eb-9510-93a09d8bf4df.jpg)

**Comment by fit2-zhao** [comment]
@liangweijie99  请问有多少个步骤，是否有循环步骤，或者有引用场景步骤，（如果有，被引用场景步骤有多少）

**Comment by liangweijie99** [comment]
一个18个场景，共有216接口 。


![Dingtalk_20210208150041](https://user-images.githubusercontent.com/74578958/107186076-8fdb2900-6a1e-11eb-8c19-5eff05e829a4.jpg)
![Dingtalk_20210208150058](https://user-images.githubusercontent.com/74578958/107186085-949fdd00-6a1e-11eb-8557-21a4b234fdf0.jpg)

**Comment by fit2-zhao** [comment]
@liangweijie99  收到，这块的性能问题会尽快优化。

**Comment by xulinde** [comment]
v1.8已优化
