### ISSUE TITLE
[BUG]idea插件，在setting>>metersphere里配置好连接信息后，当用户右击项目里面的文件或文件夹然后选择export to ms菜单，最好可以让用户在弹窗里选择ms端模块路径

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#14393]
### 联系方式

王进

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

idea插件，在setting>>metersphere里配置好连接信息后，当用户右击项目里面的文件或文件夹然后选择export to ms菜单，最好可以让用户在弹窗里选择ms端模块路径

### 重现步骤

无需重现，这是一个使用优化需求，大海同意优化。

### 期待的正确结果

无需重现，这是一个使用优化需求，大海同意优化。

### 附加信息

帮忙把该需求同步给大海，大海已经答应优化。

**Comment by Hyyfit** [comment]
具体的实现还需要待开发调研。
待调研可行性以及必要性后，再回复您是否做这个需求。
