### ISSUE TITLE
[BUG]新建分组（类型为：项目），设置分组权限（如：测试跟踪/接口测试），关联项目后，使用新增用户打开项目提示404错误(/case/node/publicCount/接口报错)

### ISSUE THREAD

**Issue by geyesheng** [metersphere/metersphere#14397]
### MeterSphere 版本

v1.20.5-lts-9fe3acfd

### 使用外置数据库

是

### 问题描述

1.新建分组
![image](https://user-images.githubusercontent.com/38676947/172126370-c675075c-4916-4434-ab22-280f6a250398.png)
2.设置权限
![image](https://user-images.githubusercontent.com/38676947/172126451-aa643223-a22b-4b5a-a73a-bff443ec3aa2.png)
3.创建项目
![image](https://user-images.githubusercontent.com/38676947/172126611-490fa440-e050-436a-993f-4286e60665db.png)
4.新增用户及关联项目
![image](https://user-images.githubusercontent.com/38676947/172126790-dadda9d7-dafa-4c33-8711-edae3781107c.png)
5.使用新增的用户，然后选择项目提示404错误(/case/node/publicCount/接口报错)
![image](https://user-images.githubusercontent.com/38676947/172127068-8b8b3a9e-d98f-428e-b865-99f3b0424407.png)
![image](https://user-images.githubusercontent.com/38676947/172134648-555ca0b8-15b9-4f59-815f-900ac7d84707.png)
![image](https://user-images.githubusercontent.com/38676947/172134804-05a6d27e-8ccf-4146-8e83-6ff695a44fc6.png)

### 重现步骤

新建分组（类型为：项目），设置分组权限（如：测试跟踪/接口测试），关联项目后，使用新增用户打开项目提示404错误

### 期待的正确结果

正常打开，无任何报错，如权限不够则不显示对应的菜单

### 相关日志输出

```shell
info打印日志
2022-06-06 16:42:50,099 [XNIO-1 task-9] INFO  i.m.commons.utils.SessionUtils ? - Method[getCurrentWorkspaceId][WORKSPACE: ]
2022-06-06 16:43:02,416 [XNIO-1 task-9] INFO  i.m.commons.utils.SessionUtils ? - Method[getCurrentWorkspaceId][WORKSPACE: ]
error无错误日志
```

**Comment by ltfit** [comment]
你好 按你的权限配置下 没有复现 ，是有别的权限勾选 图片截全么

**Comment by geyesheng** [comment]
1.权限设置
![image](https://user-images.githubusercontent.com/38676947/172286620-3c7c39e7-b365-4107-a258-8226c286a6a9.png)
![image](https://user-images.githubusercontent.com/38676947/172286671-729e31f1-f5ff-4452-8ad9-0aae3d4d35ec.png)
![image](https://user-images.githubusercontent.com/38676947/172286693-9d12fc35-ffc0-430c-9d4f-255f24db8f8e.png)
2.用户分组设置
![image](https://user-images.githubusercontent.com/38676947/172286848-cba72e24-5acd-447f-aac9-b28ed237e9e0.png)
3.设置项目后对应进入为系统数据
![image](https://user-images.githubusercontent.com/38676947/172286940-77d14718-db13-41d3-b6a2-ec6441cc596a.png)
4.项目有勾选，然后才是切项目（路径：系统跟踪--功能用例--项目:xxx））只是我涂抹脱敏了
![image](https://user-images.githubusercontent.com/38676947/172287234-9be5da17-f8ac-4c64-a8f7-f7c185cba4c0.png)
5.报错（切换任一项目都会报错），或者刷新页面都会弹toast
![image](https://user-images.githubusercontent.com/38676947/172287426-3e779cdf-2e97-428e-8739-d670595b9100.png)

**Comment by geyesheng** [comment]
> 你好 按你的权限配置下 没有复现 ，是有别的权限勾选 图片没有截全么 看报错是没有选中工作空间

看我的备注

**Comment by ltfit** [comment]
还是没有复现 工作空间成员的权限我看下

**Comment by geyesheng** [comment]
工作空间成员(系统)权限：
![image](https://user-images.githubusercontent.com/38676947/172583513-af2c77da-ac25-49e7-966a-798b932ff024.png)
![image](https://user-images.githubusercontent.com/38676947/172583542-eb82387c-cf32-4414-b8be-4a7213234197.png)

**Comment by geyesheng** [comment]
> 还是没有复现 工作空间成员的权限我看下

看提交备注，如还无法复现，建议加微信沟通，我加你

**Comment by ltfit** [comment]
13131900266

**Comment by geyesheng** [comment]
> 13131900266

已加，注意最近添加人
