### ISSUE TITLE
[BUG]TCP接口定义导入JMX生成的接口，在test页面点击测试，页面无响应

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#14394]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.5-lts

### 使用外置数据库

否

### 问题描述

导入JMX生成的TCP接口定义，点击test的测试，页面没有响应

### 重现步骤

1.在接口定义模块，切换到TCP
2.选择jmeter导入，上传JMX文件，导入后生成TCP接口定义和接口CASE
3.点击接口定义，测试接口定义，发现测试按钮点击无反应
![image](https://user-images.githubusercontent.com/88763608/172124870-44710108-6449-4eab-8a44-568db4344535.png)
4.可以使用附件复现

### 期待的正确结果

点击测试，可以发送请求

### 附加信息

[TCP.zip](https://github.com/metersphere/metersphere/files/8842987/TCP.zip)

**Comment by zyyfit** [comment]
这个是因为jmx文件里的tcp client 没填，导入后的tcpclient也是空的，调试的时候其它设置里面提示了，不过不切换到其它设置页面看不到这个提示，后续版本优化一下这里
![image](https://user-images.githubusercontent.com/73461316/172144236-e2afccd6-df34-4f6c-a354-8d10906599ef.png)

**Comment by zyyfit** [comment]
1.20.6已修复，请等待发版后验证
