### ISSUE TITLE
[BUG]场景自动化公共参数csv文件，json取值错误

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1439]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
未复现，建议升级1.8以上版本
