### ISSUE TITLE
qps数据和jmeter差距大

### ISSUE THREAD

**Issue by suyehen** [metersphere/metersphere#14402]
### 请描述您的问题

我在同一台机器上面部署了ms和jmeter，用ms对单接口压测20s 200用户数，然后以相同的配置用jmeter进行压测，发现jmeter压测后的qps是ms的很多倍，jmeter有6w多的qps，而ms只有1w的qps

**Comment by roc23333** [comment]
插眼

**Comment by Hyyfit** [comment]
您好，确实会有点差距，ms上可能会涉及比较多的调用，如果配置的合理，正常是可以到2/3左右的差距。

**Comment by suyehen** [comment]
> 您好，确实会有点差距，ms上可能会涉及比较多的调用，如果配置的合理，正常是可以到2/3左右的差距。

我们现在的被压测项目响应时间<1ms，按照之前看到的如果接口响应特别快的话，压测的瓶颈就会出现在kafka和data-streaming，我已经在网上找到了如何部署kafka集群的教程，那该如何部署DS的集群呢

**Comment by suyehen** [comment]
> 插眼

https://github.com/metersphere/metersphere/issues/10673，你可以参考下这个，不过后置监听器这个东西是企业版的内容

**Comment by liuruibin** [comment]
> > 您好，确实会有点差距，ms上可能会涉及比较多的调用，如果配置的合理，正常是可以到2/3左右的差距。
> 
> 我们现在的被压测项目响应时间<1ms，按照之前看到的如果接口响应特别快的话，压测的瓶颈就会出现在kafka和data-streaming，我已经在网上找到了如何部署kafka集群的教程，那该如何部署DS的集群呢

找到docker-compose-server.yml 把 ms-data-streaming 部分单独部署在不同的机器上，连接相同的数据库就可以
<img width="1636" alt="image" src="https://user-images.githubusercontent.com/23045261/172286899-5db3999e-f99d-4033-a4df-a7abe9ca64df.png">

**Comment by suyehen** [comment]
> > > 您好，确实会有点差距，ms上可能会涉及比较多的调用，如果配置的合理，正常是可以到2/3左右的差距。
> > 
> > 
> > 我们现在的被压测项目响应时间<1ms，按照之前看到的如果接口响应特别快的话，压测的瓶颈就会出现在kafka和data-streaming，我已经在网上找到了如何部署kafka集群的教程，那该如何部署DS的集群呢
> 
> 找到docker-compose-server.yml 把 ms-data-streaming 部分单独部署在不同的机器上，连接相同的数据库就可以 <img alt="image" width="1636" src="https://user-images.githubusercontent.com/23045261/172286899-5db3999e-f99d-4033-a4df-a7abe9ca64df.png">

在其他机器部署DS的话是直接修改install.conf中的MS_INSTALL_MODE就行是嘛，是应该从allinone改成什么呢，还是说是要用别的方式安装DS部分
