### ISSUE TITLE
[FEATURE]增加redis的配置和查询

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#14405]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

可以在环境变量中配置多个redis，使用的时候指定redis进行使用，因为一个环境会有多个redis db进行使用

**Comment by Hyyfit** [comment]
您好，感谢反馈，您说的是部署的redis吗？如果是部署配置redis，没有必要配置多个。

**Comment by juanmaocxy** [comment]
> 您好，感谢反馈，您说的是部署的redis吗？如果是部署配置redis，没有必要配置多个。

是指项目环境变量里配置redis，因为有些接口测试依赖redis的数据

**Comment by Hyyfit** [comment]
我们公众号有发过对Redis的操作，可以看一下。
https://mp.weixin.qq.com/s/1qYjCURaVXMioM1EwMHQIw

**Comment by juanmaocxy** [comment]
> 我们公众号有发过对Redis的操作，可以看一下。 https://mp.weixin.qq.com/s/1qYjCURaVXMioM1EwMHQIw

好的，感谢，那后续不直接集成到ms-server里了是吧

**Comment by Hyyfit** [comment]
是的
