### ISSUE TITLE
[BUG]当断言关系为“包含”和“不包含”，自动生成断言脚本的代码有问题

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#14418]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.4

### 使用外置数据库

是

### 问题描述

断言方式： 脚本
脚本语言：python
脚本中的断言关系： 包含

如下图所示，自动生成断言脚本如下：
![image](https://user-images.githubusercontent.com/31870788/172153995-087e2993-6a52-4298-a1ef-d7e5f412e1a2.png)

如图所示：
当期望的断言关系是 【list 中的文本包含 变量element的值】时，将会返回 变量element的值 在字符串list中的索引，因此 value.find("${element}") 一定不等于-1，但是脚本中，当list 中的文本包含 变量element的值，脚本会报错。因此这个脚本自动生成的代码有误

### 重现步骤

如上，在接口及场景的断言tag中，点击断言方式为脚本时，即可重现。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.6版本已修复，请等待发版后验证
