### ISSUE TITLE
[BUG]旧版数据接口的taskid太长；导致任务通知无法新建

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1441]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.7.2

**Bug 描述**
从旧版导入到新版本的接口，在接口自动化中->创建任务时，接口的taskid变长了；导致，任务通知无法新建，错误如图

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/22386206/107181641-3969ec80-6a16-11eb-93d9-2d982fb4e358.png)

**Comment by xulinde** [comment]
感谢您的反馈，我们会在1.8.0修复该问题

**Comment by xulinde** [comment]
已修复
