### ISSUE TITLE
[BUG]接口定义-sql 接口测试，无法直接引用环境变量（预期：可以在 sql 中直接使用环境变量）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1442]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.2

**Bug 描述**
简要描述您碰到的问题
接口定义-sql 接口测试，无法直接引用环境变量

**Bug 重现步骤**
1.  进入接口定义，新建 sql 接口测试
2. sql 中引用一个环境变量
3. 执行测试
4. 

**期待的正确结果**
正确情况下应该是什么样的？
预期：可以在 sql 中直接使用环境变量
实际：无法识别引用的变量（注：**接口自动化模块，尝试相同操作，可以引用**）

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/107201813-7349eb80-6a34-11eb-986e-c4a66b609875.png)

**Comment by xulinde** [comment]
感谢您的反馈，1.8.0版本会修复该问题

**Comment by xulinde** [comment]
v1.8已修复

**Comment by Betrayme** [comment]
重现：v1.10.11-lts-c237e249 @xulinde
