### ISSUE TITLE
[FEATURE] /project/listAll  需要支持 带jirakey/tapdId等的高级查询

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#14443]
### MeterSphere 版本

v1.20.5-lts

### 使用外置数据库

是

### 问题描述

/project/listAll 需要支持 带jirakey/tapdId 等的高级查询

背景描述（以jira为例）：
JIRA调用MS api创建测试计划与测试评审，其中的接口/test/plan/add 与 /test/case/review/save 需要指定projectId与workspaceId。
为此，需要先通过/project/listAll 接口查询、并获取projectId与workspaceId。

但是/project/listAll 目前只能返回“所有的”MS 项目，然后自己再通过循环逐个匹配过滤，去筛选出所需的、带有指定jirakey的projectId和workspaceId。

### 重现步骤

1. 获取accessKey, secretKey
2. 写前置脚本计算出signature
3.  调用 /prooject/listAll 接口
4. 获取MS返回的project List

### 期待的正确结果

调用 /project/listAll 支持查询参数，比如提供jirakey（tapdId/zentaoId/azureDevopsId同）的情况下，
只返回该jirakey指定的MS项目信息的 json，而非“全量”项目列表。

好处：1. 这样可以避免每次调MS“创建测试计划/评审” 前，先获取 “全量” 项目列表然后再循环匹配，从而避免较多的额外开销。
           2.  未来在网页交互上，也可以快速标识或列出与第三方平台集成的MS项目

**Comment by zyyfit** [comment]
可以提取参数呀，可以看看这个文章，jsonpath提取用法，很全

https://www.cnblogs.com/poloyy/p/13177102.html

**Comment by xyziven** [comment]
> 可以提取参数呀，可以看看这个文章，jsonpath提取用法，很全
> 
> https://www.cnblogs.com/poloyy/p/13177102.html

提取jsonpath没问题，问题是要提取具有指定key=value的jsonpath，如下面的json，要从返回的大json串中，提取jirakey=MD的id和workspaceId

{
    "success": true,
    "message": null,
    "data": [
        {
            **"id": "06eabf70-a0ef-44c7-8287-e1b4f0d88716",
            "workspaceId": "65b44e98-b571-464f-a8c3-1f705147968d",**
            "name": "MeterSphere-Hobin",
            "description": null,
            "createTime": 1651901369980,
            "updateTime": 1653633331600,
            "tapdId": null,
            **"jiraKey": "MD",**
            "zentaoId": null,
            "azureDevopsId": null,
            "caseTemplateId": "b395d8fe-2ad6-4de7-81d3-2006b53a97c8",
            "issueTemplateId": "5d7c87d2-f405-4ec1-9a3d-71b514cdfda3",
            "createUser": null,
            "systemId": null,
            "azureFilterId": null,
            "platform": "Jira",
            "thirdPartTemplate": false,
            "versionEnable": null,
            "issueConfig": "{\"jiraIssueTypeId\":\"10003\",\"jiraStoryTypeId\":\"10001\"}",
            "workspaceName": "MyWorkspace",
            "createUserName": "Hobin"
        },
        {
            "id": "a1020d30-84a7-4128-9d1c-afc9e9e0a282",
            "workspaceId": "65b44e98-b571-464f-a8c3-1f705147968d",
            "name": "演示项目",
            "description": "由saas创建完成",
            "createTime": 1651210429671,
            "updateTime": 1651210429671,
            "tapdId": null,
            "jiraKey": null,
            "zentaoId": null,
            "azureDevopsId": null,
            "caseTemplateId": null,
            "issueTemplateId": null,
            "createUser": null,
            "systemId": null,
            "azureFilterId": null,
            "platform": "Local",
            "thirdPartTemplate": false,
            "versionEnable": null,
            "issueConfig": null,
            "workspaceName": "myWorkspace",
            "createUserName": null
        }
    ]
}

**Comment by zyyfit** [comment]
对啊，可以用提取的方式来过滤，比如你贴的这段，想提取jirakey=MD的id和workspaceId，可以这样写，我之前发的那个链接里都有的
$.data[?(@.jiraKey=="MD")].id
$.data[?(@.jiraKey=="MD")].workspaceId

**Comment by 2lipan** [comment]
可以在后置脚本中获取响应内容，然后使用python脚本利用正则将id提取出来。
![image](https://user-images.githubusercontent.com/104960608/172626611-987f8aab-7799-4c20-aad6-efe1bef913d7.png)
![image](https://user-images.githubusercontent.com/104960608/172626659-063fcd4d-48ee-4d44-8f63-b0946f804a25.png)

**Comment by xyziven** [comment]
通过JMeter或java提取本身不是问题，都很方便。两个因素：
1.  每次查询没必要返回全量
2. 有些语言，比如类shell的SIL处理起来没那么便捷

**Comment by Hyyfit** [comment]
感谢反馈，暂不支持。
如果需要增加这个功能，还需要调研可行性。

**Comment by song-cc-rock** [comment]
项目管理查询接口优化支持第三方平台项目参数JiraKey, ZendaoId...等, 来进行过滤
![image](https://user-images.githubusercontent.com/40567414/175893845-074e7f38-2ee4-4ea9-9f70-de34594053b8.png)
