### ISSUE TITLE
[BUG]Beanshell脚本调用${__Random(,)}方法报错

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#14450]
### 联系方式

Saco@微信交流群24/QQ交流群

### MeterSphere 版本

v1.20.0-eb0e2483

### 使用外置数据库

否

### 问题描述

前置Beanshell脚本内容
```beanshell
import org.apache.commons.codec.binary.Base64;

import java.util.*;
import java.text.SimpleDateFormat;

String num = (${__Random(1000,9000)}).toString();
log.info("Should print" + num);
String code = "code"+num;
String name = "name"+num;

String dt_now = (new SimpleDateFormat("yyyy-MM-dd")).format(new Date());

vars.put("code",code);
vars.put("name",name);
vars.put("dt_now", dt_now);

```
执行测试报错（见底部报错日志）

### 重现步骤

见描述

### 期待的正确结果

正常执行前置脚本

### 相关日志输出

```shell
2022-06-07 16:30:52 ERROR ThreadGroup 1-1 Problem in JSR223 script, JSR223PreProcessor
Sourced file: inline evaluation of: ``import org.apache.commons.codec.binary.Base64;    import java.util.*;  import ja . . . '' : Typed variable declaration : Attempt to access property on undefined variable or class name : at Line: 6 : in file: inline evaluation of: ``import org.apache.commons.codec.binary.Base64;    import java.util.*;  import ja . . . '' : { 
 in inline evaluation of: ``import org.apache.commons.codec.binary.Base64;    import java.util.*;  import ja . . . '' at line number 6
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:253)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:981)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

### 附加信息

<img width="1926" alt="image" src="https://user-images.githubusercontent.com/34698664/172331396-a72c68fb-5cfd-4e9a-b32b-53462ad55e13.png">
![企业微信截图_16524259348459](https://user-images.githubusercontent.com/34698664/172331641-a72168e6-b02d-4e5b-b2a4-a071cb85adcb.png)

**Comment by Saco93** [comment]
> 您好，最新版本未复现该问题，脚本执行正常-请尝试升级或者将api导出提供下我们看是否能复现。 脚本运行控制器台返回正常 2022-06-07 20:02:25 INFO StandardJMeterEngine Running the test! 2022-06-07 20:02:25 INFO StandardJMeterEngine List of sample_variables: [] 2022-06-07 20:02:25 INFO StandardJMeterEngine 2f531192_431c265c-b33d-20d5-5598-d689b9f77b72: Starting worker with class: class io.metersphere.jmeter.MsBackendListenerClient and queue capacity: 5000 2022-06-07 20:02:25 INFO StandardJMeterEngine 2f531192_431c265c-b33d-20d5-5598-d689b9f77b72: Started worker with class: class io.metersphere.jmeter.MsBackendListenerClient 2022-06-07 20:02:26 INFO StandardJMeterEngine Starting ThreadGroup: 1 : ThreadGroup 2022-06-07 20:02:26 INFO StandardJMeterEngine Starting 1 threads for group ThreadGroup. 2022-06-07 20:02:26 INFO StandardJMeterEngine Thread will continue on error 2022-06-07 20:02:26 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false 2022-06-07 20:02:26 INFO StandardJMeterEngine Started thread group number 1 2022-06-07 20:02:26 INFO StandardJMeterEngine All thread groups have been started 2022-06-07 20:02:26 INFO ThreadGroup 1-1 Thread started: ThreadGroup 1-1 2022-06-07 20:02:26 INFO ThreadGroup 1-1 Should print6301
[Metersphere_Api_人事V2.0.json.zip]

导出的接口如下
(https://github.com/metersphere/metersphere/files/8857647/Metersphere_Api_.V2.0.json.zip)

**Comment by zrfit** [comment]
您好，导入接口增加前置脚本执行仍运行正常，未复现。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/172540646-11ef8a25-7c27-4fd7-9ad5-46c3fd8f4085.png">

**Comment by zhangzhaox** [comment]
String num = "${__Random(1000,9000)})";
@Saco93
