### ISSUE TITLE
[BUG]从测试跟踪-测试计划 入口，选择某个测试计划关联接口测试用例，无法关联接口自动化案例！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1445]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.2-bd12a36a
**Bug 描述**
简要描述您碰到的问题

从测试跟踪-测试计划 入口，选择某个测试计划关联接口测试用例，无法关联接口自动化案例！

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，未复现该问题，有报错日志或者报错截图吗

**Comment by feiyu0316** [comment]
—————————————————&nbsp;&nbsp;

许小梅&nbsp;&nbsp;手机:13625082301&nbsp; &nbsp;QQ:1339979149




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 中午11:06
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"许小梅"<1339979149@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]从测试跟踪-测试计划 入口，选择某个测试计划关联接口测试用例，无法关联接口自动化案例！ (#1445)





 
您好，未复现该问题，有报错日志或者报错截图吗

**Comment by xulinde** [comment]
邮件内容是空的
