### ISSUE TITLE
[BUG]在接口定义里新增了用例的全局变量可更新到环境配置中，接口自动化引用了此用例，运行后环境变量不更新

### ISSUE THREAD

**Issue by zx950723** [metersphere/metersphere#14465]
### 联系方式

1337209238@qq.com，交流群43号（昵称：没名字）

### MeterSphere 版本

版本:   v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

在接口定义里新增了用例的全局变量可更新到环境配置中，接口自动化引用了此用例，运行后环境变量不更新

### 重现步骤

1、在接口定义中新增接口A，接口A下有用例1，并用脚本设置了全局变量，运行用例1后环境配置中可看到全局变量生效
2、在接口自动化场景中直接导入用例1，不做修改，运行接口自动化中的用例1，环境配置中的全局变量未更新

### 期待的正确结果

接口定义的用例中和接口自动化中，均可使全局变量生效/更新

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by zyyfit** [comment]
在场景中，整个场景执行完成后才会更新环境变量，单独调试接口是不会更新的
