### ISSUE TITLE
[FEATURE]Jenkins插件，执行方式的配置，无法将接口自动化案例批量配置进来！建议Jenkins插件支持配置接口自动化案例，支持接口自动化案例批量执行~

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1446]
**请描述您的需求或者改进建议.**

Jenkins插件，执行方式的配置，无法将接口自动化案例批量配置进来！建议Jenkins插件支持配置接口自动化案例，支持接口自动化案例批量执行~

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
该功能已实现，操作方法：
1.测试计划关联自动化案例
2.jenkins选择该计划
