### ISSUE TITLE
[BUG]自动化场景编辑时，导入新场景存在导入重复问题

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14460]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

自动化场景编辑时，导入新场景存在导入重复问题

### 重现步骤

1、编辑某个自动化场景
2、导入其他场景（复制或者引用都可以）
3、选择其中一个场景进行复制或者引用
4、再次导入场景，一个场景都不选，点击复制或者引用
5、发现被编辑的场景中第三3步骤导入或者复制的场景，在第4步操作之后又会被复制或者引用一次

可能原因：在第一次场景被导入之后，CheckBox里面的值没有清理掉，导致第二次不选直接点“复制”或者“引用”会再次被加入到场景内

### 附加信息

第一次复制或者引用：
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/32027713/172348353-17370a44-69e9-4de8-8371-94f46d5c8177.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/32027713/172348389-a88fbc6f-a856-4d06-9794-fdff3366d058.png">

再次点击“复制”或“引用”：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32027713/172348746-92c9c99a-22ab-4359-990e-5148d7497148.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32027713/172348619-ca1eb5a8-2599-468d-937c-29c07dd52785.png">

**Comment by zrfit** [comment]
你好，该问题v1.20.6已修复。
