### ISSUE TITLE
[BUG]数据源下拉框回显失败

### ISSUE THREAD

**Issue by charlie-ch** [metersphere/metersphere#14475]
### 联系方式

434534658@qq.com

### MeterSphere 版本

v1.19.3

### 使用外置数据库

是

### 问题描述

当环境中有多个数据源且ip不同，名字不同时。在自动化下选择数据源后，点击保存，仍然回显原值，一般为排序第一个的值。

### 重现步骤

1.环境中配置多个数据源，ip不同，名字不同。
2.接口测试--接口自动化--新建场景，场景中点击+，然后选择自定义请求，选择sql协议，保存。
3.更改上一步sql请求的数据源，点击折叠按钮，再展开，数据源却恢复了旧值（一般为第一个）。
4.点击保存按钮，刷新，依然显示旧值。

### 期待的正确结果

1.点击折叠按钮，再展开，显示新值。
2.点击保存，刷新，显示新值。

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by xulinde** [comment]
您好，按照您的步骤操作了下，最新版本v1.20.5不存在该问题，建议您升级到最新版本
