### ISSUE TITLE
[BUG]接口断言jsonpath，断言带()的有问题

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1448]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26756176/107328152-3d1a7380-6ae9-11eb-9638-d66f267e6969.png)

**Comment by xulinde** [comment]
感谢反馈，我们试着复现下

**Comment by meihaoyidian** [comment]
![Uploading image.png…]()

**Comment by meihaoyidian** [comment]
![image](https://user-images.githubusercontent.com/26756176/108700418-89ca6980-7541-11eb-87f7-99e5ebdb0d50.png)

**Comment by xulinde** [comment]
1.8.0修复

**Comment by xulinde** [comment]
v1.8已修复
