### ISSUE TITLE
[BUG]性能测试--首页--运行中的任务，展示为空

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#14481]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

路径：性能测试--首页--运行中的任务
描述：执行性能测试，running状态下案例，在运行中的任务栏，都无法展示（定个任务和手动触发都不行）

### 重现步骤

手动触发：
![image](https://user-images.githubusercontent.com/15188833/172518589-f6b37a69-05fb-40d4-841b-f911e3d10e7a.png)

定时任务：
![image](https://user-images.githubusercontent.com/15188833/172518658-deea02c8-1265-4968-995d-3036c1edc7c3.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，首页这个 运行中的任务，只显示性能测试定时任务列表
性能测试用例的定时任务开启后，这里可以正常看到，请确认你的定时任务是否开启，第二图触发方式怎么是 ”计划定时任务“
![image](https://user-images.githubusercontent.com/54612864/172524409-d40fc591-b90e-4a8c-bff0-161720081f63.png)
