### ISSUE TITLE
[FEATURE]接口测试首页中统计的接口覆盖率，希望按照接口ID统计覆盖率

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#14493]
### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

目前接口定义列表中，有两个相同URL的接口定义，在场景中引用了其中一个接口定义的case，首页中显示接口覆盖率为100%，实际应该是为50%；
<img width="927" alt="截屏2022-06-08 上午11 34 09" src="https://user-images.githubusercontent.com/34637801/172526122-e4088ac1-a387-4a7b-bd73-c4e58bea9f94.png">
<img width="1273" alt="截屏2022-06-08 上午11 35 40" src="https://user-images.githubusercontent.com/34637801/172526273-dea69328-ee3b-4e21-91b1-62d3afe60a0b.png">
建议使用接口定义ID+URL 来作为统计的方法 

### 重现步骤

1.创建一个接口定义；
2.复制该接口定义；
3.分别为这两个接口定义创建相应case；
4.在接口自动化中创建一个场景，引用其中的某个接口定义的case；

### 期待的正确结果

1.期待接口测试 首页的接口覆盖率为50%

**Comment by zyyfit** [comment]
现在场景这边显示的覆盖率是按url和请求类型统计的

**Comment by Hyyfit** [comment]
已规划，待排期。
