### ISSUE TITLE
[BUG]接口测试转性能测试的时候，自动把域名替换成了ip，由于domain不一致，导致cookie没法保存

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#14499]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.5-lts

### 使用外置数据库

否

### 问题描述

之前因为自定义DNS组件的bug，在接口测试转性能测试的时候，自动把域名替换成了ip，当时觉得没问题，但实际上是不行的。由于domain不一致，cookie没法保存

### 重现步骤

场景用例的环境设置了hosts，场景转性能测试，运行性能测试

日志中有大量的，Illegal 'domain' attribute "**.com.cn". Domain of origin: "10.11.*.*"
domain和origin不一致，导致cookie无法保存，使得后续的过程全都失败了

**Comment by shenkaibo** [comment]
@liuruibin

**Comment by xulinde** [comment]
使用v1.20.5版本未复现。方便把您的场景发下吗
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/64065190/172539133-1d5309ed-7cad-4439-86fb-fcb71055751c.png">
<img width="929" alt="image" src="https://user-images.githubusercontent.com/64065190/172539184-7842613b-78fb-457b-bbf3-1777329ccdf5.png">

**Comment by shenkaibo** [comment]
1.真实访问的接口是通过网关转发，域名对应IP是网关的IP，场景里一共2个接口，一个登录接口，一个业务接口，场景选择 共享cookie
2.环境选择 域名，可正常登录，业务接口 正常返回。
3.环境选择 IP,可正常登录，业务接口 返回异常，报 “非法请求，请求过期”

具体复现如下
[msip域名问题 (2).zip](https://github.com/metersphere/metersphere/files/8897237/msip.2.zip)

**Comment by shenkaibo** [comment]
补一张 ，通过ip访问登录接口， 响应头里的cookie中的domain 包含 域名信
![ip方式登录相应头](https://user-images.githubusercontent.com/30038088/173534522-a97042c1-b0c9-4972-8d5c-d03acc37fe94.png)
息

**Comment by shenkaibo** [comment]
1.20.7-lts 已修复
