### ISSUE TITLE
[QUESTION] jenkins验证metersphre账号失败

### ISSUE THREAD

**Issue by marshuanggang** [metersphere/metersphere#14490]
### 请描述您的问题

【ENV】
jenkins： 2.328
metersphere  hpi: 1.20.5

【QUESTION】
我在jenkins上添加了metersphere插件，配置ms账号验证时提示
“验证MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败”

ms地址/key都是正确的

请问，这个是什么原因呢
多谢

**Comment by Hyyfit** [comment]
您好，可以在我们的微信交流群内，@我们的技术人员，远程帮您排查问题。

**Comment by codergu64** [comment]
我也遇到同样的问题：“验证MeterSphere帐号失败！java.lang.NullPointerException,null”

**Comment by ShuaiqiDuan** [comment]
我也遇到这个问题了，请问该怎么解决。（jenkins版本2.332.1，ms版本1.17.1，插件也是1.17.1）

**Comment by codergu64** [comment]
调整下ms所在服务器的时间和jenkins所在服务器一致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月4日(周五) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [QUESTION] jenkins验证metersphre账号失败 (Issue #14490)




 
我也遇到这个问题了，请问该怎么解决。（jenkins版本2.332.1，ms版本1.17.1，插件也是1.17.1）
