### ISSUE TITLE
[BUG]接口自动化数据转为新版后，提取参数的数据正常展示，断言的数据没有展示

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#1449]
**MeterSphere 版本**
v1.4.3升级到v1.6.2，然后再升级到v1.7.2
![image](https://user-images.githubusercontent.com/49089965/107328289-7652e380-6ae9-11eb-9232-fe60ac825bb8.png)

**Bug 描述**
接口自动化数据转为新版后，提取参数的数据正常展示，断言的数据没有展示

这个问题应该是 Assertions 这个数据块下面少了 xpath2 这个key，前端有用这个key，然后报错了。可以麻烦大佬反馈下吗，不知道是后端返回数据的问题，还是前端的问题。

我这边的用例数据都是 v1.4.3 版本的存量数据，我看了老的数据，断言的数据结构里就没 xpath 字段，然后你们这边是在 v1.5.0 这个版本才新增的这个字段

我建议你们要复现的话，可以先装 v1.5.0 之前的版本，新建接口自动化的用例，然后升级到新版，应该就能复现我的问题

**截图**
![image](https://user-images.githubusercontent.com/49089965/107328370-92568500-6ae9-11eb-87e8-093130081e8d.png)
![image](https://user-images.githubusercontent.com/49089965/107328377-95ea0c00-6ae9-11eb-88e3-64852a9144ac.png)
![image](https://user-images.githubusercontent.com/49089965/107328387-997d9300-6ae9-11eb-8ba2-ceab918ea77b.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已复现该问题，计划下个版本修复，请持续关注～

**Comment by xulinde** [comment]
已修复
