### ISSUE TITLE
[BUG]TCP在接口定义这边导入包含http的JMX后，http的API关联的模块ID不对

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#14497]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.5-lts

### 使用外置数据库

否

### 问题描述

在TCP那边导入了包含http的jmx，然后切换到http这边，刚切换过来能看到http的API和CASE，但是选择左边的模块后右边就没有数据了。
可能原因，在TCP那边导入的时候，API和CASE关联上了TCP那边的模块ID，导致在http页面，选择左边模块后就查询不出来了

### 重现步骤

1.切换到tcp 接口定义
2.导入包含http请求的JMX（客户的JMX同时包含TCP和http）
3.切换到http，能看到导入的API和CASE
![image](https://user-images.githubusercontent.com/88763608/172529376-4198b74d-ec74-47fd-a99c-e934f407ae69.png)

4.选择左边的模块后，右边就看不到数据了
![image](https://user-images.githubusercontent.com/88763608/172529320-babc7213-75f9-47c3-a37b-408a7776756f.png)

### 附加信息
[TCP和HTTP请求.zip](https://github.com/metersphere/metersphere/files/8858215/TCP.HTTP.zip)
_No response_

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
现在这个没有模块的问题已经修复了，不过后面的版本还会统一修改一下逻辑
