### ISSUE TITLE
[BUG]测试用例主页面左右固定，希望可以伸缩。用例名字过短，字段布局可以再优化下

### ISSUE THREAD

**Issue by dahuachao** [metersphere/metersphere#145]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/68523338/87891352-3c968e80-ca6c-11ea-8131-1310a0e6874d.png)

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 您所使用的 MeterSphere 版本是？
> 
> **Bug 描述**
> 简要描述您碰到的问题
> 
> **Bug 重现步骤**
> 1.
> 2.
> 3.
> 4.
> 
> **期待的正确结果**
> 正确情况下应该是什么样的？
> 
> **截图**
> 如果有截图，请附上截图.
> ![image](https://user-images.githubusercontent.com/68523338/87891352-3c968e80-ca6c-11ea-8131-1310a0e6874d.png)

会在最近的一个版本上线， 请留意交流群版本更新通知
