### ISSUE TITLE
[BUG]用例评审脑图无法按照关联的用例顺序展示；

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#14505]
### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

用例评审时，按照一定的逻辑顺序关联功能用例，使用脑图的评审方式，发现用例的顺序不是关联的顺序；
<img width="1080" alt="截屏2022-06-08 下午12 01 20" src="https://user-images.githubusercontent.com/34637801/172528805-9166f499-4aa3-46b8-b40e-4e42ef9fad98.png">

<img width="789" alt="截屏2022-06-08 下午12 03 10" src="https://user-images.githubusercontent.com/34637801/172528984-c581d247-3498-4a20-a497-6d85aeaa084e.png">

### 重现步骤

1.创建一个用例评审；
2.按照业务逻辑选择关联对应的功能用例；
3.使用脑图进行评审；

### 期待的正确结果

1.脑图中的用例顺序和关联顺序保持一致；

**Comment by ltfit** [comment]
脑图是先展示模块再展示用例，加载过程也是点击一个模块展示获取一个模块下的数据，只保证同一个模块下的用例顺序；另外如果A模块顺序是在B模块的上面，A模块下用例顺序是在B模块用例的下面，这个顺序就不好保证了 ，并且影响性能，就不做额外的复杂设计来保证不同模块下的用例顺序了
