### ISSUE TITLE
使用只读用户登录MS，点击【接口自动化-场景列表】中的复制/查看引用按钮，页面直接跳转至了【系统设置】页签下

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1450]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.0-3c6a4849

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/107456159-ad2d0600-6b8a-11eb-8f4e-31bb2ebdb8d5.png)
![image](https://user-images.githubusercontent.com/78518076/107456200-b918c800-6b8a-11eb-90a6-908b14184315.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该问题在v1.7.2版本中未复现，更新到最新版本试试吧～
