### ISSUE TITLE
新版接口测试，修改了接口，接口所对应的case相关信息并没有修改

### ISSUE THREAD

**Issue by cjwts** [metersphere/metersphere#1452]
**MeterSphere 版本**
1.7.1

**Bug 描述**
新版接口测试，将API的请求方式从Get修改为了Post，接口所对应的case的apiUI信息也更改成了Post，但仍是执行的Get。请求头等也是同样现象

**Bug 重现步骤**
1.  修改API的请求方式从Get为Post
2. 执行API下的case
3. 
4. 

**期待的正确结果**
API信息修改，case的相关信息也同步修改

**截图**
![image](https://user-images.githubusercontent.com/30405402/107461207-82e04600-6b94-11eb-8b83-b4c2e6798605.png)

**Comment by xulinde** [comment]
您好，接口定义变更，用例是不会变更的，接口用例那有批量编辑的功能，可以单独对用例做变更

**Comment by cjwts** [comment]
修改了API get为post，case那边也显示为post了，只是执行的时候仍是get形式，要么是UI bug，要么是功能BUG
