### ISSUE TITLE
[FEATURE]希望可以在步骤中屏蔽环境变量中的全局断言，会有很少一部分接口不应适用全局断言

### ISSUE THREAD

**Issue by QAceshi** [metersphere/metersphere#14535]
### MeterSphere 版本

1.20.2

### 请描述您的需求或者改进建议

会有很少一部分接口不应适用全局断言，比如：一部分接口返回状态就不是200 或者msg不是OK

### 请描述你建议的实现方案

希望可以在步骤中有个开关之类的可以屏蔽全局变量，或者支持重写断言来覆盖全局断言

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。

**Comment by nakaDH** [comment]
请问下这个issue 已经开发解决了嘛。有链接教程嘛
