### ISSUE TITLE
[FEATURE]强烈请愿！可以直接【链接】JIRA缺陷编号

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#1453]
**请描述您的需求或者改进建议.**
在**功能**或者**接口**测试 的执行页面，可以直接链接 既有的 JIRA 编号。

**请描述你建议的实现方案**
testlink中可以直接链接jira 现成的 编号，并可以输出到 缺陷报告中。谢谢

![image](https://user-images.githubusercontent.com/6467295/108295409-8c1e7380-718f-11eb-99df-3cad6ba32057.png)

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中
