### ISSUE TITLE
[FEATURE]希望对metersphere与jira需求关联功能进行优化

### ISSUE THREAD

**Issue by sephirothgao** [metersphere/metersphere#14532]
### MeterSphere 版本

1.19

### 请描述您的需求或者改进建议

1、metersphere与jira的需求进行关联，是基于测试用例级别的，这样操作比较麻烦，效率很低。比如一个需求与100条测试用例有关，那么就得把这个需求和这100条用例一一进行关联，费时费力。
建议：测试用例可以独立进行编写和管理，在使用的时候，jira中的需求与测试计划进行关联，而测试计划肯定是和测试用例关联的，这样就可以通过测试计划将jira需求与测试用例关联，且这样的关联省时省力。可以支持1对多关联，或者多对1关联。
2、在项目管理中，需求类型只能选择成任务，故事，长篇故事中的一种，但实际的需求中，可能包含多种类型。
建议：是否可以关联多种需求类型？
<img width="436" alt="image" src="https://user-images.githubusercontent.com/11827528/172555803-59b7fad7-c8a5-489f-a9ab-f659f11c0fe7.png">

3、目前的jira需求与metersphere进行关联后，通过这个关联可以进一步做什么事，或者实现什么功能，还不是很明确，只知道关联了，但关联了又能做什么呢？希望能给出解答。

**Comment by Hyyfit** [comment]
感谢反馈。
1.在功能用例的批量操作中，支持批量关联需求，可以实现1个需求一次关联上100条用例，功能在版本2.0会上。
2. 目前设计如此，不支持关联多种需求。
3. 我们平台对需求并没有进行管理，在管理用例的时候，需要知道该用例具体是哪个需求的用例，需要有这样的关联关系。
