### ISSUE TITLE
[FEATURE]针对三方接口调用过程中，希望能加上mock功能

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1454]
**请描述您的需求或者改进建议.**
针对第三方的接口，尤其是微信支付/支付宝支付；在接口测试/场景自动化过程中，加上mock功能

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后续版本我们会添加mock功能，请持续关注

**Comment by xulinde** [comment]
1.9.0已支持
