### ISSUE TITLE
[BUG]功能用例进行批量修改责任人，数据库对应的字段未被修改成功

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14556]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

功能用例进行批量修改责任人，数据库对应的字段未被修改成功

### 重现步骤

1、在功能用例列表中选择多个用例进行批量操作
2、更新用例属性"责任人"
3、确定之后，发现页面上的责任人确实发生变化，但是实际test_case表中的责任人字段并未发生变化
4、第3步操作导致测试跟踪首页的“用例责任人”表格中的数据也没有发生变化，显示数据是错误的
5、重新编辑上述被修改的用例，不修改任何信息，直接保存，首页及数据库数据发生变化

涉及到的后台sql为：
  select count(tc.id) as countNumber, user.name as groupField from test_case tc right join user on tc.maintainer = user.id
        where tc.project_id = #{projectId} and tc.status != 'Trash' and tc.latest = 1
        group by tc.maintainer

### 附加信息

1、批量修改责任人为“李四”
![image](https://user-images.githubusercontent.com/32027713/172591924-2b07d2f7-c11c-479a-af12-3a120c7946d6.png)
2、显示修改成功：
![image](https://user-images.githubusercontent.com/32027713/172592030-f314498b-22fb-4546-8275-5701399d9393.png)
3、实际首页内容：
![image](https://user-images.githubusercontent.com/32027713/172592130-2db95eab-1b1f-4904-af6d-677e7ee9414a.png)
4、实际数据库内容：
![image](https://user-images.githubusercontent.com/32027713/172592230-707a4938-733f-4ee6-85df-8ef284587e60.png)

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
在最新版本v1.20.7-lts中已修复~
