### ISSUE TITLE
[BUG][企业用户] 循环测试的次数和数据文件中的用例条数不一致

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14568]
### MeterSphere 版本

1.20.4

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/172641199-2c2df26e-185d-43e9-bfbb-7ca80622643b.png)

### 重现步骤

1. 上传数据文件csv，有28行记录
2. 设置循环条件
![image](https://user-images.githubusercontent.com/103017812/172641083-4d8a4499-315c-4287-bac9-0efa0c47045a.png)
3. 执行测试，结果只跑了14次
![Uploading image.png…]()

**Comment by youliyuan-fit2cloud** [comment]
已修复，请升级到v1.20.5-lts以上版本，感谢~
