### ISSUE TITLE
[BUG]测试计划执行完成，用例有失败的用例，测试报告通知是：***测试计划运行成功

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#14569]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

是

### 问题描述

测试计划执行完成，用例有失败的用例，测试报告通知是：***测试计划运行成功

![image](https://user-images.githubusercontent.com/23476281/172739281-ee1e8d2a-4cc4-47f9-8d93-ca4475085d80.png)

### 重现步骤

测试计划执行完成，用例有失败的用例，测试报告通知是：***测试计划运行成功

**Comment by youliyuan-fit2cloud** [comment]
你好，这个消息通知添加是执行完成的消息通知吧，测试计划运行成功指的是执行该测试计划的任务执行完成了，
可以添加测试计划“执行成功”或“执行失败”的消息通知，如下图
![image](https://user-images.githubusercontent.com/54612864/172754825-993b5a4e-d8a9-42a4-b428-1261c4aa94fe.png)

**Comment by chase001** [comment]
有添加这些报告好像没有发出来，升级到v1.20.0-lts-c599aa69之前是好的，现在是没有收到这些报告
![image](https://user-images.githubusercontent.com/23476281/172816558-69047576-adef-4a80-9bc6-17c3cf2d5950.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这里确实有问题，我们后续版本修复~

**Comment by chase001** [comment]
麻烦尽快修复，每天都要看测试报告

**Comment by youliyuan-fit2cloud** [comment]
后天就发布啦

**Comment by youliyuan-fit2cloud** [comment]
在最新版本v1.20.7-lts中已修复~
