### ISSUE TITLE
ms-server 、 ms-node-controller 、 ms-data-streaming 一直重启，root用户下提示权限不够

### ISSUE THREAD

**Issue by muyan001** [metersphere/metersphere#14574]
### 请描述您的问题

ms-server 、 ms-node-controller 、 ms-data-streaming 一直重启，root用户下提示权限不够

Caused by: java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/metersphere/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/metersphere/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/metersphere/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/error.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/metersphere/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/warn.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[backendApiAppender] - openFile(/opt/metersphere/logs/metersphere/api/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/api/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoTestPlanAppender] - openFile(/opt/metersphere/logs/metersphere/testPlan/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/testPlan/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - openFile(/opt/metersphere/logs/metersphere/ms-jmeter-run-log.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/ms-jmeter-run-log.log (Permission denied)

**Comment by Hyyfit** [comment]
您好，可以在我们的微信交流群内，@我们的技术人员，帮您远程协助排查问题。
