### ISSUE TITLE
[BUG]“我的工作台”页面中“我的仪表盘”待办的功能用例点击跳转到编辑页面，模块信息丢失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14583]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

“我的工作台”页面中“我的仪表盘”待办的功能用例点击跳转到编辑页面，模块信息丢失，提示用户“请选择模块”，而该用例不属于当前项目，下拉出来的模块也是当前项目的模块树，保存之后就变成当前项目的用例了

### 重现步骤

1、打开“我的工作台”，找到“我的仪表盘”
2、查看“我的待办”，类型选择“功能用例”
3、选择其中一条功能用例进行点击
4、跳转到该功能用例的编辑页面，发现模块信息丢失

### 附加信息

1、选择功能用例：
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/32027713/172770460-77938455-d8e9-4512-a875-4090f00e4f73.png">

2、点击该功能用例：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32027713/172770549-343fda08-c906-470e-8f45-aa16af5a80e0.png">

**Comment by ltfit** [comment]
已知问题，后续版本修复

**Comment by ltfit** [comment]
在最新版本v1.20.7-lts中已修复~
