### ISSUE TITLE
[BUG]在接口自动化里直接创建性能测试，http+dubbo场景的下载jmx文件，jmeter5.3打不开

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1458]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/26756176/108447885-aba2c280-729b-11eb-945e-a1b11bb40fbf.png)

**Comment by xulinde** [comment]
收到，我们试着复现下

**Comment by xulinde** [comment]
您好，您这个是因为没有dubbo插件
