### ISSUE TITLE
[BUG]测试计划修改当前状态无效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14587]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

测试计划修改当前状态后，重新进如测试计划，发现状态修改无效

### 重现步骤

1、编辑一个已存在的测试计划，修改其状态，然后点击保存
2、保存成功之后，再点击测试计划名称进入测试计划内，什么不操作
3、然后再重新进入测试列表，发现被修改的状态又被重置回修改前的状态

### 附加信息

1、相关视频：

https://user-images.githubusercontent.com/32027713/172777164-657be790-9b51-4eea-999d-c9d2ee7b04b9.mp4

**Comment by ltfit** [comment]
你好 这个是根据计划里用例状态自动更新的
