### ISSUE TITLE
[QUESTION]query请求的变量会变成%0d之类的转义符

### ISSUE THREAD

**Issue by Grandlulu** [metersphere/metersphere#1459]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/26474753/108482682-c3e30380-72d4-11eb-9b46-d35550772a17.png)

**Comment by zyyfit** [comment]
这种情况应该是没引用到变量，在url中会把特殊字符这样显示，请您再确认一下变量引用是否正确

**Comment by Grandlulu** [comment]
排查了一下，应该是批量添加功能的格式问题，希望能够完善批量添加时回车的自动转义
