### ISSUE TITLE
[BUG]功能用例“自定义ID”在“我的工作台”显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14592]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

功能用例“自定义ID”在“我的工作台”中我的待办下显示错误

### 重现步骤

1、项目设置--》应用管理--》测试用例自定义ID 打开
2、创建一个新的责任人为本人的用例，状态为“未完成”
3、在我的工作台中的仪表盘看“我的待办”，观察ID与功能用例列表中ID进行比对

实际显示应该是数据库中的“custom_num”字段值，而系统显示的是数据库中的num值

### 附加信息

1、功能用例列表：
![image](https://user-images.githubusercontent.com/32027713/172782389-aaac0947-f9a2-4fbf-8aa3-510eaf256041.png)

2、仪表盘显示：
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/32027713/172782602-6f496241-152a-4789-ba3d-433381464e7b.png">

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.7已修复，建议您升级至最新版本
