### ISSUE TITLE
请问如何在windows下运行项目

### ISSUE THREAD

**Issue by rainbowsky911** [metersphere/metersphere#14596]
### 请描述您的问题

我在本地运行项目启动日志没有报错，自己写了个http接口测试，shiro设置匿名访问，但是接口访问不到，控制台日志也没有输出，我不知道项目是启动成功了还是没有启动成功
![image](https://user-images.githubusercontent.com/16053250/172787664-2728428f-9349-4460-bcfe-dcdfd47c09e3.png)

**Comment by Hyyfit** [comment]
您好，可以在我们的微信交流群里@我们的技术人员，远程帮您排查问题。
