### ISSUE TITLE
[BUG]不同的状态码对应不同的Schema时，响应内容显示有误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14609]
### 联系方式

张树彬

### MeterSphere 版本

1.20.4

### 使用外置数据库

否

### 问题描述

接口定义，不同的状态码对应不同的Schema时，响应内容显示有误；我可以提供脚本

### 重现步骤

1. swagger接口导入MS接口定义
2. 查看接口响应内容-响应体，分别选择json和raw格式查看
3. 当接口不同的状态码对应不同的Schema时，响应内容显示有误

### 期待的正确结果

当接口不同的状态码对应不同的Schema时，响应内容显示正确

### 附加信息

![a66e72c28a187028b520de8d717cd57](https://user-images.githubusercontent.com/77324661/172805543-75c24c49-b713-4b89-8ce2-f31c5b626e40.png)
![1654764602809](https://user-images.githubusercontent.com/77324661/172806284-0cf4edf2-8dfa-4aa7-86ee-941cca2d1044.png)
![fcae1788bb9f580023fdfdaa046e718](https://user-images.githubusercontent.com/77324661/172806358-f81f8029-2b6d-4d48-b4a0-af2269e453c6.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.7已修复，建议您升级至最新版本
