### ISSUE TITLE
[BUG]自动化场景里单独运行接口，请求信息无法进行复制

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#1460]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.72
**Bug 描述**
自动化场景里单独运行接口，请求信息无法进行复制

**期待的正确结果**
可以进行复制
![image](https://user-images.githubusercontent.com/69206282/108579966-5a123a80-7364-11eb-9a06-ee9ef374f768.png)

**Comment by xulinde** [comment]
感谢反馈，我们计划下个版本采纳您的建议，请持续关注MeterSphere~

**Comment by xulinde** [comment]
和issue#1466重复
