### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1461]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.2-bd12a36a

**Bug 描述**
简要描述您碰到的问题
导入csv文件后，偶尔会出现network error，但不影响其它页面

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，能详细描述下必现步骤吗
