### ISSUE TITLE
[FEATURE]接口测试--接口定义-API/CASE，没有使用到--运行环境，可以隐藏掉

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#14618]
### MeterSphere 版本

1.20.5

### 请描述您的需求或者改进建议

路径1：接口测试--接口定义--API/CASE
路径2：接口测试--接口定义--快捷调试

描述：环境下拉框  使用不到，建议隐藏，而且容易误导用户；隔壁老王接口自动化就没有 环境下拉框，看着清爽

### 请描述你建议的实现方案

页面上，类似于：环境下拉框 用不到的，可以隐藏掉，如果不隐藏，容易出现误导，增加使用难度和降低用户体验感。

接口定义页面：
![image](https://user-images.githubusercontent.com/15188833/172816907-e8d38b67-e88b-4c22-9bd5-104594aad114.png)

接口自动化：就一个搜索框，简洁
![image](https://user-images.githubusercontent.com/15188833/172816975-79642f0a-ff88-4018-a083-35b628762efb.png)

**Comment by Hyyfit** [comment]
感谢反馈，设计如此。
使用场景是，在编辑case的时候，没有添加环境。
对列表中的case，需要切不同的环境调试。列表页面选择了环境，可以减少用户进入到用例编辑页面切换环境的操作。
