### ISSUE TITLE
[BUG]前置脚本里加一个groovy的脚本和一个python的，两个的启用状态都是开启的，请求体里就没法拿到py的变量了，随便post请求一个接口。

### ISSUE THREAD

**Issue by LeungJingna** [metersphere/metersphere#14627]
### 联系方式

微信号：644167986

### MeterSphere 版本

版本:   v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

前置脚本里加一个groovy的脚本和一个python的，两个的启用状态都是开启的，请求体里就没法拿到py的变量了，随便post请求一个接口。

### 重现步骤

前置脚本里加一个groovy的脚本和一个python的，两个的启用状态都是开启的，请求体里就没法拿到py的变量了，随便post请求一个接口。
请求体：
{
    "signature": "${signature}"
}
前置脚本一、groovy的：
import org.apache.jmeter.config.Arguments;
import org.apache.jmeter.config.Argument;
Arguments arguments = sampler.getArguments();
Argument requestbody = arguments.getArgument(0);
def requestBody_data = requestbody.getValue();
vars.put("requestBody_data",requestBody_data); 

前置脚本二、py的：
sign='111111111111'
vars.put("sign", sign);

### 期待的正确结果

两个脚本都开启情况下，且先执行goovy脚本再执行py脚本，请求时，请求体能够读取到py脚本里的变量sign

### 附加信息

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/85165471/172832245-5afec5d7-1bb7-4772-8a5b-df9d2eea9bae.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，由于jmeter不支持这种操作，所以目前我们平台也不支持
