### ISSUE TITLE
[BUG]同一个API导入到不同模块时，提示导入成功，但在页面未出现该 API

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14621]
### 联系方式

张树彬

### MeterSphere 版本

1.20.4

### 使用外置数据库

否

### 问题描述

同一个API导入到不同模块时，只有导入第一个模块成功，后面再导入其他模块都提示导入成功，但在页面未出现该API

### 重现步骤

1. API脚本导入到A模块，导入成功
2. 相同的API脚本导入到B模块，提示导入成功，但页面并未显示API，实际导入失败

### 期待的正确结果

相同API导入到多个模块下，如果提示导入成功，应该真正的导入成功，而不是只有提示导入成功

### 附加信息

<img width="458" alt="6bf888e43906854aa1535d08970fda5" src="https://user-images.githubusercontent.com/77324661/172822142-4e2751e6-a01e-4caf-9504-516f4808e5f3.png">

**Comment by zrfit** [comment]
您好，api导入的逻辑是：
<img width="902" alt="image" src="https://user-images.githubusercontent.com/99731894/172828980-f14b33b1-7b49-4d8c-8f13-95fca6279ffb.png">
api路径已经存在且无数据变更-即使选择了其它模块，也不会再重新导入到该模块下，原模块下数据保持不变。

**Comment by zrfit** [comment]
您好，api导入的逻辑是：
<img width="902" alt="image" src="https://user-images.githubusercontent.com/99731894/172828980-f14b33b1-7b49-4d8c-8f13-95fca6279ffb.png">
api路径已经存在且无数据变更-即使选择了其它模块，也不会再重新导入到该模块下，原模块下数据保持不变。

**Comment by zrfit** [comment]
v2.0.0接口导入逻辑统一优化，可以指定选择是否覆盖api模块。

**Comment by binbin0406** [comment]
那是不是改一下 导入其他模块时 不要提示导入成功了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："zrfit ***@***.***&gt;;
发送时间：2022年6月9日(星期四) 晚上6:51
收件人："metersphere/metersphere" ***@***.***&gt;;
抄送："张树彬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [metersphere/metersphere] [BUG]同一个API导入到不同模块时，提示导入成功，但在页面未出现该 API (Issue #14621)
-----------------------------------

 

 
您好，api导入的逻辑是：
 
 api路径已经存在且无数据变更-即使选择了其它模块，也不会再重新导入到该模块下，原模块下数据保持不变。
