### ISSUE TITLE
[BUG]无法登陆，一直弹出“认证信息已过期”的提示框

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1462]
**MeterSphere 版本**
1.7.3

**Bug 描述**
登陆界面一直弹框，提示“认证信息已过期，请重新登录”

**Bug 重现步骤**
1.  打开网址首页就会弹出，其他同事也是一样的。

**截图**
附上截图
![弹框](https://user-images.githubusercontent.com/39483734/108586820-cce2dc00-738b-11eb-9b26-a4e470c03928.png)

![隐藏后可以正常登陆](https://user-images.githubusercontent.com/39483734/108586776-8e4d2180-738b-11eb-92af-cc6ca7fa29f8.png)
隐藏这两个控件后，可以正常登陆。

**Comment by xulinde** [comment]
和issue#1473重复
