### ISSUE TITLE
[FEATURE]公共用例库里面的用例目前只有用例创建人可以删除，希望admin也可以删除，方便对应人员离职后进行管理

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14638]
### MeterSphere 版本

1.20.5-LTS

### 请描述您的需求或者改进建议

公共用例库里面的用例目前只有用例创建人可以删除，希望admin也可以删除，方便对应人员离职后进行管理

### 请描述你建议的实现方案

只需要admin可以删除删除就OK，其他人员角色不做要求

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
