### ISSUE TITLE
[BUG]测试跟踪-功能用例-用例列表-脑图，“展开”下拉框，点击“展开到第六级节点”后，点击列表，页面会有报错提示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#14635]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例-用例列表-脑图，“展开”下拉框，点击“展开到第六级节点”后，点击列表，页面会有报错提示。
![image](https://user-images.githubusercontent.com/104960608/172853489-dd6c206c-82d6-48a6-8a98-204e0c50b764.png)
![image](https://user-images.githubusercontent.com/104960608/172853751-58b815f6-5db8-4a38-94be-5a50ea769a77.png)

### 重现步骤

1.测试跟踪-功能用例-用例列表-脑图，“展开”下拉框
2.点击“展开到第六级节点”
3.切换到"列表"，页面会有报错提示。

**Comment by ltfit** [comment]
感谢反馈  后续优化下 是快速切换脑图和用例列表会出现这问题 偶发

**Comment by ltfit** [comment]
v 1.20.6-lts已修复
