### ISSUE TITLE
接口自动化--点击执行按钮会提示“xxx Is Running!”，无法执行自动化场景测试

### ISSUE THREAD

**Issue by liangweijie99** [metersphere/metersphere#1463]
**MeterSphere 版本**
v1.7.3

**Bug 描述**

接口自动化--点击执行按钮会提示“xxx Is Running!”，无法执行自动化场景测试

**Bug 重现步骤**
1.  登录系统，打开接口自动化页面；
2. 选择一个场景，右侧行项目上点击执行按钮；
3. 出现报错提示, 提示“xxx Is Running!”；
4. 查看测试报告可知，没有正在运行的场景。

**期待的正确结果**
正确情况下应该是什么样的？

**截图**

<img width="847" alt="DA5DBAA6-EED7-448c-8F8F-8C33006906C1" src="https://user-images.githubusercontent.com/74578958/108588403-01f32c80-7394-11eb-9660-eb90d0b4ffbc.png">

<img width="876" alt="7865161A-A2DA-46ac-B662-13A493EBE7E2" src="https://user-images.githubusercontent.com/74578958/108588412-10414880-7394-11eb-956f-35af7bf8cd3e.png">

**Comment by xulinde** [comment]
感谢反馈，我们试着复现下
