### ISSUE TITLE
[BUG] ms和jira创建缺陷时候添加api字段提示错误

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#14649]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

版本:   v1.20.5-lts-9fe3acfd

### 使用外置数据库

是

### 问题描述

设置好缺陷模板添加了两个api字段报错如图
![image](https://user-images.githubusercontent.com/39703025/172983493-c0da0a3b-62b1-4ea2-974e-b8378f66a604.png)
实际需求是想创建缺陷时候能设置这两个字段
![image](https://user-images.githubusercontent.com/39703025/172983609-e7bf8300-abdd-4eda-8aa2-873a9310de90.png)
模块的字段是component 另一个字段是sprint
![image](https://user-images.githubusercontent.com/39703025/172983792-71596761-1772-4d77-b439-3c2805cb9511.png)

### 重现步骤

项目设置-模板管理中新建jira模板在模板中添加以下字段
![image](https://user-images.githubusercontent.com/39703025/172983246-456b5a7d-e7c7-4fb7-a619-68dc14278656.png)
然后再测试跟踪-缺陷管理中创建缺陷
![image](https://user-images.githubusercontent.com/39703025/172983413-f92c92a7-6cd0-4726-b047-1aeb2665bd5e.png)

### 期待的正确结果

![image](https://user-images.githubusercontent.com/39703025/172983831-5af3a27c-d2db-415d-874f-7219c55f9875.png)
正确结果是创建完是这个样子的

### 相关日志输出

```shell
400 : "{"errorMessages":[],"errors":{"component":"Field 'component' cannot be set. It is not on the appropriate screen, or unknown.","Sprint":"Field 'Sprint' cannot be set. It is not on the appropriate screen, or unknown."}}"
```

### 附加信息

截图已经写在步骤中

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by shiziyuan9527** [comment]
@a760097644 
- component 对应的 api 字段名是 components，类型使用多选下拉列表。
- sprint 在 jira 是自定义字段，具体名称可以在 JIRA设置 -> 自定义字段 列表中找到该字段，查看该字段信息，可以在地址栏中找到其名称，并将其转化为对应的 api 字段名。

![image](https://user-images.githubusercontent.com/58418919/174548434-9c6eec61-2043-4330-b2a9-8244681d2d6c.png)
![image](https://user-images.githubusercontent.com/58418919/174548536-ed09c8cb-eaf6-4538-b995-0674e37f6d23.png)
![image](https://user-images.githubusercontent.com/58418919/174547014-fafde58d-cd08-4f6b-9ae8-5c780765b461.png)
