### ISSUE TITLE
[BUG]接口测试，在前置脚本设置环境变量第一次接口请求时请求体拿不到环境变量，再次请求后才能拿到上一次的环境变量

### ISSUE THREAD

**Issue by LeungJingna** [metersphere/metersphere#14640]
### 联系方式

微信号：644167986

### MeterSphere 版本

版本:   v1.20.3-lts-f5223bb5

### 使用外置数据库

否

### 问题描述

[BUG]接口测试，在前置脚本设置环境变量第一次接口请求时请求体拿不到环境变量，再次请求后才能那到。

### 重现步骤

[BUG]接口测试，设置两个前置脚本，第一个是groovy、第二个是python，两个脚本的状态都是开启的。
第二个python脚本里设置环境变量。
第一次发起post请求测试，请求体拿不到python脚本里设置的环境变量（日志打印变量信息是正常的）；
第二次发起post请求测试，请求体才能拿到上一次python脚本里设置的环境变量。

### 期待的正确结果

请求体能正常拿到环境变量

**Comment by zyyfit** [comment]
设置环境变量的代码有下面这2行，请检查一下是否缺少代码，如果代码完整，请上传一下接口/场景
vars.put(${__metersphere_env_id}+"key","value");
vars.put("key","value");

**Comment by LeungJingna** [comment]
> 设置环境变量的代码有下面这2行，请检查一下是否缺少代码，如果代码完整，请上传一下接口/场景 vars.put(${__metersphere_env_id}+"key","value"); vars.put("key","value");

接口与场景：
1、post请求任意一个接口；
2、请求体：
{
    "signature": "${signature}"
}
3、前置脚本一，groovy脚本：
import org.apache.jmeter.config.Arguments;
import org.apache.jmeter.config.Argument;
import groovy.json.JsonSlurper;
Arguments arguments = sampler.getArguments();
Argument requestbody = arguments.getArgument(0);
def requestBody_data = requestbody.getValue();
vars.put("requestBody_data",requestBody_data); 
4、前置脚本二，python脚本：
signature="xxxxxxxxxxx"
vars.put(${__metersphere_env_id}+"signature",signature);
5、结果：请求体拿不到signature的值。

**Comment by LeungJingna** [comment]
> 1、两个前置脚本里获取不到变量的这个问题，jmeter也有这个问题，我们暂时和jmeter保持一致，不改动jmeter源码 2、你的设置全局变量的脚本少了一行，这里要写两行 ![image](https://user-images.githubusercontent.com/73461316/174056438-c21b367f-5770-42cf-9285-5f7bdbd3ab33.png)
“2、你的设置全局变量的脚本少了一行，这里要写两行”，试过有加这两行，但一样是不行。

**Comment by zyyfit** [comment]
还有 1 呢。。。就是你这样写两个脚本，第二个脚本里获取不到变量的问题，jmeter 也是这样的，可能是jmeter的一个bug，我们暂时不改动jmeter的源码，你可以用一个脚本处理这些
