### ISSUE TITLE
[BUG]项目设置-模板管理-缺陷模板管理：系统自带的状态字段-添加了自定义字段应用到default缺陷模板中，新增字段未同步

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#14654]
### MeterSphere 版本

 v1.20.5-lts-9fe3acfd

### 使用外置数据库

否

### 问题描述

项目设置-模板管理-缺陷模板管理：系统自带的状态字段-添加了自定义字段应用到default缺陷模板中，新增字段未同步

### 重现步骤

项目设置-模板管理-缺陷模板管理：系统自带的状态字段-添加了自定义字段应用到default缺陷模板中，新增字段未同步

如图：
<img width="516" alt="系统自带的状态字段-添加了自定义字段" src="https://user-images.githubusercontent.com/43202800/172992573-eaff2e3e-953f-4bb6-8dd2-63a57c242142.png">

### 期待的正确结果

添加的字段同步到创建缺陷- ”状态“  字段下

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.8已修复，建议您升级
