### ISSUE TITLE
[FEATURE]接口测试url链接分享问题，希望能够通过url方式分享

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1465]
**请描述您的需求或者改进建议.**
接口测试url链接分享问题，希望能够通过url方式分享
![image](https://user-images.githubusercontent.com/22386206/108643823-39beb900-74e7-11eb-9f59-cfce6258f23b.png)

**请描述你建议的实现方案**
在以前的版本中key通过url携带测试id来分享，希望在新版本中可以支持分享测试场景接口
![image](https://user-images.githubusercontent.com/22386206/108643890-77234680-74e7-11eb-8d7a-53bccf4befda.png)

**Comment by wsnsnsns** [comment]
+1

**Comment by wsnsnsns** [comment]
这个在旧版中,可以实现的...
新版中,无法实现....

**Comment by zh417233956** [comment]
#1346

**Comment by zh417233956** [comment]
@fit2cloudrd 工作空间,接口定义的url分享外链通过地址栏的方式传递，这个需求太强烈了，希望能够支持

**Comment by zh417233956** [comment]
版本: v1.9.3,已修复

**Comment by zh417233956** [comment]
#4718
