### ISSUE TITLE
[FEATURE]执行测试后响应内容中请求内容/响应头等无法选中文本进行复制

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1466]
**请描述您的需求或者改进建议.**

执行测试后响应内容中，请求内容、响应头等内容无法复制
![image](https://user-images.githubusercontent.com/22386206/108644682-07af5600-74eb-11eb-8dfa-71ea2478443a.png)

**请描述你建议的实现方案**
希望可以支持选择文本，进行复制

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们计划下个版本采纳您的建议，请持续关注MeterSphere~

**Comment by xulinde** [comment]
v1.8已优化
