### ISSUE TITLE
[BUG]测试计划中增加定时任务，设置运行场景用例失败时，发通知到企业微信失败

### ISSUE THREAD

**Issue by luck-dyl** [metersphere/metersphere#14664]
### 联系方式

luckydengyalong@wghl.wecom.work

### MeterSphere 版本

版本:   v1.20.5-lts-9fe3acfd

### 使用外置数据库

否

### 问题描述

测试计划中增加定时任务，设置运行场景用例失败时，发通知到企业微信失败
![image](https://user-images.githubusercontent.com/58102925/173012791-b3dad3d8-8f1a-4059-b823-fc63e070d463.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/58102925/173012862-8ea9927f-a906-45ed-b04b-97f6ff4f1cad.png)
测试计划中增加定时任务，设置运行场景用例失败时，发通知到企业微信

### 期待的正确结果

企业微信群，收到运行失败的通知

### 附加信息

![image](https://user-images.githubusercontent.com/58102925/173013425-246f3efa-ab66-4a07-a622-acd8c27b79f6.png)

**Comment by youliyuan-fit2cloud** [comment]
在最新版本v1.20.7-lts中已修复~
