### ISSUE TITLE
[BUG]初次登录MS，未修改密码和已修改密码，选择环境下拉框位置发送变化

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#14660]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

路径：接口测试--接口定义
描述：没有修改密码时，环境下拉框和已经修改密码位置发送变化

### 重现步骤

未修改密码：
![image](https://user-images.githubusercontent.com/15188833/173000787-4b004ad8-8745-40b1-8280-03d5fe862f83.png)

改完密码：
![image](https://user-images.githubusercontent.com/15188833/173000821-9c114000-a884-4e88-9af3-080301a8f7c9.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复
