### ISSUE TITLE
[BUG]火狐浏览器，接口自动化场景页，鼠标无法选中请求参数

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14667]
### 联系方式

张树彬

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

火狐浏览器，接口自动化场景页，鼠标无法选中接口的请求参数

### 重现步骤

1. 火狐浏览器打开MS
2. 接口测试-接口自动化-选择任意场景
3. 点击场景内任意接口，用鼠标选择参数失败，会变成拖动的效果

### 期待的正确结果

可以正常用鼠标选中参数

### 附加信息

![1654847773231](https://user-images.githubusercontent.com/77324661/173018751-4729bcf7-f729-4958-a472-2f5ccc2645c3.jpg)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
开发的同事评估了一下，暂时不支持浏览器兼容问题，需要修改点太多
