### ISSUE TITLE
[BUG]自定义缺陷模板，新建了一个模板A，然后再项目管理创建项目 缺陷模板绑定不上 模板A

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#14661]
### MeterSphere 版本

v1.20.5-lts-9fe3acfd

### 使用外置数据库

否

### 问题描述

自定义缺陷模板，新建了一个模板A，然后再项目管理创建项目 缺陷模板绑定不上 模板A

### 重现步骤

自定义缺陷模板，新建了一个模板A，然后再项目管理创建项目 缺陷模板绑定不上 模板A

如图：
<img width="960" alt="微信图片_20220610135723" src="https://user-images.githubusercontent.com/43202800/173000748-eb67c13e-017d-47aa-96d3-e6fc21ccb648.png">

### 期待的正确结果

项目-缺陷模板可以选择自定义的-metersphere平台缺陷模板

**Comment by ltfit** [comment]
你好 看着你的第三方平台没有选择上

**Comment by ltfit** [comment]
![image](https://user-images.githubusercontent.com/99794211/175012861-72266074-0aa0-4dcf-a562-e59eff588b89.png)
这里没选上

**Comment by xhy12** [comment]
已沟通，处理
