### ISSUE TITLE
希望支持（接口定义和接口自动化）导入非本项目接口（更加灵活多变，用户无需局限在本项目，跨项目灵活多变）

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1468]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，接口定义支持导入任何项目的接口，可以先把项目A导出，然后导入到项目B；接口自动化下个版本会支持导入场景用例。

**Comment by AshuaiNe** [comment]
这样导入比较不灵活，如果用户只需要项目中一个接口，就不太灵活




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "youliyuan-fit2cloud"<notifications@github.com&gt;; 
发送时间: 2021年2月23日(星期二) 中午1:37
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "2818820548"<2818820548@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] 希望支持（接口定义和接口自动化）导入非本项目接口（更加灵活多变，用户无需局限在本项目，跨项目灵活多变） (#1468)





 
感谢反馈，接口定义支持导入任何项目的接口，可以先把项目A导出，然后导入到项目B；接口自动化下个版本会支持导入场景用例。

**Comment by youliyuan-fit2cloud** [comment]
了解～，我们内部讨论下

**Comment by xulinde** [comment]
1.9.0已支持
