### ISSUE TITLE
[FEATURE]建议导入测试用例可以增加一个版本字段

### ISSUE THREAD

**Issue by heshiqi1** [metersphere/metersphere#1469]
**请描述您的需求或者改进建议.**
建议导入测试用例可以增加一个版本字段，方便用于区分不同的版本，或者是为了满足区分不同测试用例的需求。

**请描述你建议的实现方案**
方案一：把现有的“”标签“”字段开放出来，支持用户在本地excel编辑该字段后导入
方案二：专门给exicel导入新增一个“”版本“”字段

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该需求已在计划中，请持续关注～

**Comment by xulinde** [comment]
是希望测试用例增加一个历史版本回溯的功能吗。和issue#1248重复
