### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by ArmandHe-China** [metersphere/metersphere#14704]
### 请描述您的问题

本地通过源码搭建环境是出现这个问题
![image](https://user-images.githubusercontent.com/63539861/173195896-c71b0aad-2cc5-4428-8d60-59068a963c64.png)
网上找了很多方法都没有解决，希望官方给出建议

**Comment by ArmandHe-China** [comment]
我是在widows搭建的开发环境，没有安装kafka与redis。sql配置文件设置了sql_mode，但是下一行的skip-name-resolve没有设置设置了之后会导致mysql启动失败。其他都是按照要求配置的

**Comment by Hyyfit** [comment]
您好，可以在我们的微信交流群内，@我们的技术人员，帮您远程协助排查问题。
