### ISSUE TITLE
[BUG]我在本地部署了最新的MS平台，从导出的文件导入了接口和环境，但是CASE无法运行，报错

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14708]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

我在本地部署了最新的MS平台，从导出的文件导入了接口和环境，但是CASE无法运行，报错
![1](https://user-images.githubusercontent.com/38156471/173243386-09b97daa-4d8f-4d29-954b-f5437e870921.png)
![2](https://user-images.githubusercontent.com/38156471/173243388-17b9d262-4622-4a89-8161-26c7ecee9a93.jpg)

### 重现步骤

我在本地部署了最新的MS平台，从导出的文件导入了接口和环境，但是CASE无法运行，报错
![1](https://user-images.githubusercontent.com/38156471/173243386-09b97daa-4d8f-4d29-954b-f5437e870921.png)
![2](https://user-images.githubusercontent.com/38156471/173243388-17b9d262-4622-4a89-8161-26c7ecee9a93.jpg)

### 期待的正确结果

接口和环境文件就可以运行CASE

**Comment by YellCatt** [comment]
> 看报错是域名解析失败了，不开hosts，直接用域名/ip执行报错吗

直接用域名报错，我没有ip地址

**Comment by YellCatt** [comment]
有什么办法可以解决吗？都部署两天了，还没用上，心烦

**Comment by YellCatt** [comment]
> > > > 看报错是域名解析失败了，不开hosts，直接用域名/ip执行报错吗
> > > 
> > > 
> > > 直接用域名报错，我没有ip地址
> > 
> > 
> > ![8B09B6E7-2C89-4AC6-9851-0830381BB37E](https://user-images.githubusercontent.com/38156471/173365096-51cbded2-ad9c-4fab-a412-9a3a9ee62682.jpeg) 容器没ping 不通外网
> 
> hosts 我不清楚ip的情况下，用了ping 出的地址，连接超时

![image](https://user-images.githubusercontent.com/38156471/173452322-c7be6a32-1702-4842-b301-eac51030e224.png)
网络是通的

**Comment by YellCatt** [comment]
> > > > > 看报错是域名解析失败了，不开hosts，直接用域名/ip执行报错吗
> > > > 
> > > > 
> > > > 直接用域名报错，我没有ip地址
> > > 
> > > 
> > > ![8B09B6E7-2C89-4AC6-9851-0830381BB37E](https://user-images.githubusercontent.com/38156471/173365096-51cbded2-ad9c-4fab-a412-9a3a9ee62682.jpeg) 容器没ping 不通外网
> > 
> > 
> > hosts 我不清楚ip的情况下，用了ping 出的地址，连接超时
> 
> ![image](https://user-images.githubusercontent.com/38156471/173452322-c7be6a32-1702-4842-b301-eac51030e224.png) 网络是通的
[新建文件夹.zip](https://github.com/metersphere/metersphere/files/8894783/default.zip)
这是日志

**Comment by xulinde** [comment]
你这个是容器里访问不到域名，可以关闭下selinux，或者在容器里配下hosts。这种网络情况可以找运维处理下

**Comment by xulinde** [comment]
沟通后，暂时判断用户接口问题，无需修改程序
