### ISSUE TITLE
[BUG]MS上传文件报错，但是JMETER可以正常上传，请定位确认。

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#14707]
### 联系方式

qq：258800240

### MeterSphere 版本

1.20.4, 1.20.6

### 使用外置数据库

否

### 问题描述

相同的请求头
![image](https://user-images.githubusercontent.com/51286902/173242229-fcc04e72-92aa-4a1f-aaf7-fdc2941c3143.png)
相同的请求体
![image](https://user-images.githubusercontent.com/51286902/173242198-2d737003-6fc2-4b50-8173-b7535b77c188.png)
不同的响应结果
![image](https://user-images.githubusercontent.com/51286902/173242273-b9b157a9-3e8f-4bd8-8373-81f9a844394a.png)

### 重现步骤

接口配置：
![image](https://user-images.githubusercontent.com/51286902/173242386-959ebee7-a8b4-44be-8f16-af5a678dab85.png)

### 期待的正确结果

文件上传成功并返回路径

**Comment by warmmilk** [comment]
如果需要token用于复现问题，请qq联系我，谢谢。

**Comment by warmmilk** [comment]
较早版本可以正确响应（1.18.x）

**Comment by xulinde** [comment]
加不上您qq
<img width="384" alt="image" src="https://user-images.githubusercontent.com/64065190/173293060-490591fc-f353-4599-a0f8-65377e100776.png">

**Comment by warmmilk** [comment]
已临时开通映射

POST http://218.2.113.170:1119/ChestPain/OpenAPI/Attachment/UploadAttachmentResources
Token：ew0KICAiYWxnIjogIkhTMjU2IiwNCiAgInR5cCI6ICJKV1QiDQp9.eyJNb2JpbGUiOiIiLCJSb2xlcyI6WyJTYSIsIlh0R3VhbkxpWXVhbiIsIkN6R3VhbkxpWXVhbiIsIkp6R3VhbkxpWXVhbiIsIkNzR3VhbkxpWXVhbiJdLCJQbGF0Zm9ybUlkIjowLCJUZW5hbnRJZCI6MCwiS2V5IjoiODI0MDUxYzktMmFjYi00NWUzLTliNjktNjE4MzBmY2Y3YWFiIiwiSWQiOjMwMDkwMDAwMSwiTmFtZSI6Iui2hee6p-euoeeQhuWRmCIsIkxvZ2luTmFtZSI6ImNwYyIsIlR5cGUiOjB9.7TJAqjXU0fXr7EkYBdO78Yl5h3DhO-ZvmXnhp4uJ08Q

**Comment by warmmilk** [comment]
公司服务器断网，请稍候

**Comment by warmmilk** [comment]
已经恢复，请协助定位，谢谢。😁

**Comment by xulinde** [comment]
接口方便导出来发下吗

**Comment by warmmilk** [comment]
不会发附件，直接发一个metersphere格式的json，见谅。

**Comment by xulinde** [comment]
您可以直接扫码进我们企业微信群，沟通会更方便些～
![image](https://user-images.githubusercontent.com/64065190/173529913-7a207eb1-826c-40bc-972b-045fb9201f18.png)

**Comment by xulinde** [comment]
您可以扫码加下我们的企业微信群，沟通更方便些～
![image](https://user-images.githubusercontent.com/64065190/173532826-e451f135-7828-4a77-9a95-30b53325ac5b.png)

**Comment by xulinde** [comment]
您企业微信名字是？我私聊您沟通细节

**Comment by warmmilk** [comment]
此处多了一个charset=UTF-8
![image](https://user-images.githubusercontent.com/51286902/173993619-c5a521aa-1251-4783-9033-542f1c90c8bf.png)
应该和ms-jmeter-core仓库的HTTPHC4Impl.java的变更有关，清排查。

**Comment by warmmilk** [comment]
修改并手动编译ms-jmeter-core.jar替换解决了
