### ISSUE TITLE
[BUG][企业用户] Plan测试报告通过率显示错误

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14714]
### MeterSphere 版本

1.20.6

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/173270960-76cc340b-739e-4338-ab3b-c78b0a482146.png)
![image](https://user-images.githubusercontent.com/103017812/173270975-b11489aa-63b0-4e56-ac75-d598d4d9cecd.png)

### 重现步骤

第一次打开report页面时显示的通过率和report详情页中显示的不一致。
![image](https://user-images.githubusercontent.com/103017812/173271000-7340b5ba-d2e5-43e1-a2ef-e9f6dcfe2afa.png)
![image](https://user-images.githubusercontent.com/103017812/173271038-8e6630a0-6e83-41f0-a00b-9bd6c9b65288.png)
F5刷新页面后，report结果列表中的通过率才与详情页中的一致
![image](https://user-images.githubusercontent.com/103017812/173271134-019f2a07-b1a3-4212-87f7-724f28a452f1.png)

**Comment by 35plus** [comment]
MS研发同事，这个问题，可能复现不出来，我刚刚试了，但是确实在客户的测试环境里出现了，帮忙 转给看看。

**Comment by 35plus** [comment]
之前年初的时候也是相同客户，出现了类似问题，当时内部无法复现，后来再三邀请开发看一下客户现象，当时太明显了，开发修复了一次，时隔3个多月，类似问题又出现了。
