### ISSUE TITLE
[FEATURE]功能用例新增位置优化

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#14716]
### MeterSphere 版本

1.19.3

### 请描述您的需求或者改进建议

新增功能用例的时候，新增成功的用例能够显示在当前用例查询页的一条上，方便用例新增。因为我有100条用例后想在50处新增一条，新增的会显示到整个用例第一条的位置，移动到50处其实还是非常不方便，如果能在当前页的第一条相对就方便多了，当然最好的做法还是可以在任意位置进行插入用例

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
