### ISSUE TITLE
[FEATURE]建议优化接口自动化的测试报告和消息通知模版

### ISSUE THREAD

**Issue by HEhunter** [metersphere/metersphere#1471]
**请描述您的需求或者改进建议.**
1、建议接口自动化测试中的测试报告可以进行自我编辑，可以丰富一下测试报告的内容，简单地说希望可以和测试计划中的测试报告一样 ，可以看到是用例的模块
2、优化一下邮件和钉钉机器发送消息的模板，最好可以做到自定义，或者可以做到，运维人员看到哪条接口报错，你需要在进入系统里面查看测试报告里面的接口

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，我们内部讨论下～
