### ISSUE TITLE
[FEATURE]（建议增加功能）统计A项目调用了B项目的哪些接口

### ISSUE THREAD

**Issue by panny92** [metersphere/metersphere#1472]
**请描述您的需求或者改进建议.**
背景【加急】

- 1）目前项目间来回调用的接口比较多，其中一个系统中的接口改变了，未及时通知其他系统上线后会出现问题。

- 2）提供接口方不知道哪些接口被哪些系统调用了，没有一个地方维护

需求【加急】
不同项目间，调用其他项目接口，支持提供一个维护其他项目接口的地方，提供接口方接口改变后，调用方的接口支持同步修改。

**请描述你建议的实现方案**

可在【接口定义】模块，跨项目引用接口

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们内部讨论下～

**Comment by panny92** [comment]
你好，内部讨论怎么样了，有啥结论不

**Comment by youliyuan-fit2cloud** [comment]
> 你好，内部讨论怎么样了，有啥结论不

你好，最近的版本没有计划，但是已经提到需求里面，时间安排可能推后一些
