### ISSUE TITLE
[BUG]增加保持登录功能 -- 每天都要重复登录很多次，特别麻烦

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#1473]
**请描述您的需求或者改进建议.**
测试的过程中，不可能一直在操作metersphere系统，当测试结束，需要去记录测试结果时，系统就自动退出了，又需要刷新系统，重新登录

**请描述你建议的实现方案**
登录时增加保持登录功能，如有勾选，则不要自动退出系统。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，默认设置12小时超期，我们已复现该问题，下个版本修复

**Comment by xulinde** [comment]
配置文件默认时长2h，您可以手动修改配置。操作方法：
1.进入配置文件/opt/metersphere/docker-compose-server.yml,修改SESSION_TIMEOUT值
2.重启ms服务，msctl reload
后续版本我们会将配置文件的默认时长修改为6h

**Comment by zyyfit** [comment]
默认时长已修改为12h
