### ISSUE TITLE
[BUG]接口自动化中，去掉事务控制器Generate Parent Sample和Include Timers勾选状态，点击保存后退出，再进来还是勾选状态

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#14739]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v1.20.5-lts

### 使用外置数据库

否

### 问题描述

接口自动化中，去掉事务控制器Generate Parent Sample和Include Timers勾选状态，点击保存后退出，再进来还是勾选状态

### 重现步骤

1.进入接口自动化场景中
2.在场景中加入事务控制器
![image](https://user-images.githubusercontent.com/104493699/173301857-92e4fd7a-5063-4a66-91de-e9983c680dec.png)
3.去除勾选状态，点击保存后退出
![image](https://user-images.githubusercontent.com/104493699/173301983-cf5fbb00-8772-46f0-84bb-049377a6b129.png)
4.再次进入，发现又变为勾选状态了
![image](https://user-images.githubusercontent.com/104493699/173302138-8894a8c3-c4e9-4960-9878-90283916a1a1.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.7已修复，建议您升级至最新版本
