### ISSUE TITLE
[FEATURE]测试计划定时任务设置串行，实际上会并行

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#14738]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.6-lts

### 使用外置数据库

否

### 问题描述

测试计划定时任务设置串行，实际上会并行

### 重现步骤

1.创建测试计划，关联三个性能测试
2.设置测试计划的定时任务，并选择串行
<img width="941" alt="20252481361f200c55d2e11227c8a19" src="https://user-images.githubusercontent.com/88763608/173301733-3752c436-747d-4b67-aa9b-28f601b02d64.png">

3.到达时间后，性能测试没有串行，而是并行了
<img width="952" alt="6eb986919ceb460ab6bdd2790ca1456" src="https://user-images.githubusercontent.com/88763608/173301765-a4c171d0-60cb-44ca-a134-e9f115ccf1f7.png">
<img width="338" alt="a64131b1ef49c9161e12ce813be1ddd" src="https://user-images.githubusercontent.com/88763608/173301785-a447d2fc-d53a-4f6f-9699-718f4ead99e0.png">

### 期待的正确结果

应该串行

**Comment by youliyuan-fit2cloud** [comment]
执行测试计划时选择的串行和并行只针对接口和场景用例，对性能用例无作用。设计如此，已转产品研究一下。
