### ISSUE TITLE
[BUG]MeterSphere浏览器录制的接口，修改lable后，导出为JSON格式名称没有正确修改，导出JMX名称正确修改了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#14743]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.6-lts

### 使用外置数据库

否

### 问题描述

MeterSphere浏览器录制的接口，修改lable后，导出为JSON格式名称没有正确修改，导出JMX名称正确修改了

### 重现步骤

1.使用浏览器插件录制接口
2.修改接口的lable名称
![image](https://user-images.githubusercontent.com/88763608/173305695-35d849fe-673b-43a9-919c-e4ecfebcc659.png)

3.导出为JSON格式
4.将JSON导入MeterSphere接口定义，名称没有修改
![image](https://user-images.githubusercontent.com/88763608/173305784-7d584b7f-7bd0-4153-bf1b-5e11feec5635.png)
5.以下是插件接口导出JMX格式再导入MeterSphere的效果
![image](https://user-images.githubusercontent.com/88763608/173305961-ebec5916-1b96-4998-90f9-eb4c5c6804cf.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这个导入后接口名称是按照path和method来当作借口名的，如果json里出现重复的label，jmeter不能区分出来。
