### ISSUE TITLE
[BUG]操作日志查询过滤问题

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#14741]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

  v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

系统设置-系统-操作日志，只填写”操作人“的情况下，查询的结果是多个人，并未过滤出填写的操作人；当填写”操作人“+”工作空间“两项时，能正常过滤结果。

### 重现步骤

1、只填写操作人的情况下，查询结果是多个人
![image](https://user-images.githubusercontent.com/18514555/173304464-c5be3341-184e-4816-968b-26e4402573d5.png)

2、填写操作人+工作空间的情况下，查询结果正常
![image](https://user-images.githubusercontent.com/18514555/173304706-4b89b753-08f1-481f-99f9-69bcb0b27a61.png)

**Comment by ltfit** [comment]
已知问题 下个版本修复

**Comment by ltfit** [comment]
在最新版本v1.20.7-lts中已修复~
