### ISSUE TITLE
[BUG]接口自动化-接口列表导入-复制dubbo接口后，接口的协议会自动从dubbo://变为DUBBO

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1475]
**MeterSphere 版本**
v1.7.3
**Bug 描述**
复制dubbo接口后，接口的协议会自动从dubbo://变为DUBBO
缺陷类似之前这个bug
https://github.com/metersphere/metersphere/issues/1288

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
协议不应该发生变化

**截图**
<img width="1328" alt="ms20210222" src="https://user-images.githubusercontent.com/21210217/108692508-a6fa3a80-7537-11eb-896b-51fbf736bd6c.png">

**Comment by xulinde** [comment]
感谢反馈，后面版本我们会优化下

**Comment by xulinde** [comment]
v1.8已优化
