### ISSUE TITLE
[BUG] jenkins触发的测试计划的API测试结果有问题

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1476]
**MeterSphere 版本**
1.7.3

**Bug 描述**
我们在1.5上通过调用meterSphere的api实现对所有项目API测试结果的统计，并对有问题的测试结果自动提交bug 到 jira。但是在1.7上无法实现自动提交bug，因为以下原因：

1 测试计划的测试结果没有url可以定位
2 测试计划中包含的api case的测试结果，没有保存历史记录，只有最新的一次的结果
3 测试计划中包含的场景测试的测试结果，没有url可以定位

**Comment by xulinde** [comment]
感谢反馈，我们内部讨论下
