### ISSUE TITLE
[FEATURE]sql后置/前置脚本中，多个sql语句不能按结果存储为多个变量

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#14773]
### MeterSphere 版本

v1.20.6

### 请描述您的需求或者改进建议

在前置sql或后置sql中，当sql脚本里面包含多个sql语句时，比如

```
select count(id) from table_stu;
select sum(score) from table_score;
```

不能按结果将两个结果存储为变量。
希望可以每个sql语句可以按结果存储为一个结果变量。

**Comment by ruibaby** [comment]
@Faerie1999 Hello，建议完善一下这个 issue 的 title 描述，目前在 issues 列表无法直观的查看。

**Comment by Faerie1999** [comment]
已补充

**Comment by Hyyfit** [comment]
您好感谢反馈，默认是存储最后一个查询的结果。
如果两个结果有关联的，可以通过连查的方式存储为一个结果变量；
如果两个结果没有关联，可以添加多条sql脚本；
