### ISSUE TITLE
[BUG]测试跟踪，功能用例，上移下移调整分支顺序，保存后还是原来的顺序。调整无效

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#14774]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

测试跟踪，功能用例，上移下移调整分支顺序，保存后还是原来的顺序。调整无效

### 重现步骤

测试跟踪，功能用例，上移下移调整分支顺序，保存后还是原来的顺序。调整无效

**Comment by youliyuan-fit2cloud** [comment]
你好，上移下移什么，用例吗？还是移动功能用例左侧的模块？
请上传相关截图，详细说明遇到的问题，感谢~
