### ISSUE TITLE
[BUG]定时任务保存问题

### ISSUE THREAD

**Issue by a6106526** [metersphere/metersphere#14795]
### 联系方式

870416257@qq.com

### MeterSphere 版本

1.20.6lts

### 使用外置数据库

否

### 问题描述

配置定时任务
点重置没清空定时任务里的选项，包括时分秒日月等各个tab的指定选项
点了保存好像有没保存到的情况，设置好了保存，再点自动生成进去还是跟以前一样

### 重现步骤

![a2e48565304d2b9db5af4c221558443](https://user-images.githubusercontent.com/15136557/173507848-8dccbf50-89ba-41d2-afff-b66086fef12c.png)

![98b2812997fad70b35679badeb260c1](https://user-images.githubusercontent.com/15136557/173506526-75a7a3ee-6baa-4011-94b1-9e967af8b0f7.png)
![9505f2bf251ffafd473126eb372c24b](https://user-images.githubusercontent.com/15136557/173506539-89b7f1f2-3d9d-418a-90cc-2b51ffd15a37.png)
![25fb197d960d15402832f76c0cf8555](https://user-images.githubusercontent.com/15136557/173506562-31fd2c06-1469-429f-a865-afb1b125af98.png)
保存了再点自动生成进去还是跟以前一样
![5bbb72ce95fbe3d8846ea764dbf465d](https://user-images.githubusercontent.com/15136557/173506590-a86d2154-35f1-4c22-ad86-5bdb0b4acbed.png)
![dd512a55ef2cdfdc06e5a2f9ca11d3e](https://user-images.githubusercontent.com/15136557/173506601-21abe8f7-7554-4240-8ce3-4ba3e3a5f562.png)

**Comment by xulinde** [comment]
按您的步骤未复现该问题，您那是必现吗

**Comment by a6106526** [comment]
是的&nbsp; &nbsp;必现&nbsp; &nbsp;升级的最新版本，自动生成cron表达式里选的从xx开始每x小时执行一次，选满24小时&nbsp; &nbsp;30天之类的&nbsp; 保存&nbsp; &nbsp;然后点开重置&nbsp; &nbsp; &nbsp;日月时分秒几个tab这一项都不会重置&nbsp; &nbsp; &nbsp;容易导致保存出现偏差


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]定时任务保存问题 (Issue #14795)





 
按您的步骤未复现该问题，您那是必现吗
