### ISSUE TITLE
【建议添加】接口自动化中ForEach功能支持读取csv、excel文件

### ISSUE THREAD

**Issue by lhrrhl16** [metersphere/metersphere#1479]
**请描述您的需求或者改进建议.**
当前版本是v1.7.3
测试时，针对同一个接口请求我有大量的测试情况和测试数据需要测试，想用csv或者excel来管理测试数据，但是现在只能用次数循环来读取csv里的数据，这个不是很方便，如果改变了csv里的测试数据，还要手动修改 次数循环 里的次数

**请描述你建议的实现方案**
希望能在while循环和foreach循环方法里都支持对csv文件的读取

如果能支持excel再好不过

**Comment by xulinde** [comment]
感谢反馈，我们内部讨论下后续是否支持，请持续关注
