### ISSUE TITLE
[BUG] 非admin账号进入【系统设置】失败，URL一直跳转http://127.0.0.1:8081/#/setting/project/:type

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#14802]
### 联系方式

企业微信：MeterSphere 交流群35；李彬

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

进入系统设置页面失败

一直http://127.0.0.1:8081/#/setting
来回切换跳转http://127.0.0.1:8081/#/setting/project/:type

### 重现步骤

1、普通用户（非admin）账号登录Metersphere平台
2、顶部菜单选择【系统设置】，进入系统设置界面

### 期待的正确结果

正常进入系统设置界面

**Comment by youliyuan-fit2cloud** [comment]
你好，普通用户权限是什么？默认用户组是哪个？

**Comment by hongnini** [comment]
> 你好，普通用户权限是什么？默认用户组是哪个？

用户组与权限控制处，该用户在【工作空间成员(系统)】这个分组里
![20220616112810](https://user-images.githubusercontent.com/102306978/173984946-0e8e4bee-d1bd-4d88-97b3-950f3be2ee2e.jpg)

登录该用户，点击顶部菜单选择【系统设置】，进入系统设置界面

**Comment by youliyuan-fit2cloud** [comment]
在最新版本v1.20.7-lts中已修复~
