### ISSUE TITLE
[BUG]允许URL重复，导入已存在的接口定义，会生成空目录

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#14814]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.6-lts

### 使用外置数据库

否

### 问题描述

允许URL重复，导入已存在的接口定义，会生成空目录

### 重现步骤

1.接口定义允许url重复
2.将一个接口导出为JSON格式
3.将该接口移动到另外一个模块
4.将JSON导入原来的模块中，选择不覆盖
5.结果原来的模块生成了空模块，没有生成接口
6.具体操作可以看下附件视频

### 期待的正确结果

导入成功接口，不生成多余的模块

### 附加信息

[BUG.zip](https://github.com/metersphere/metersphere/files/8898105/BUG.zip)

**Comment by zyyfit** [comment]
后续版本统一优化这个问题，最晚是2.0版本发布
