### ISSUE TITLE
[FEATURE]建议增加对变量的json提取功能

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#14830]
### MeterSphere 版本

1.20.6

### 请描述您的需求或者改进建议

建议增加对变量的json提取功能

![image](https://user-images.githubusercontent.com/51286902/173556813-a540c840-8aad-4566-ab8d-e7304055f83d.png)

### 请描述你建议的实现方案

建议增加对变量的json提取功能，解决提取一组内多值问题

**Comment by Hyyfit** [comment]
感谢反馈，平台json提取器可以“匹配多条”来实现提取多条数据。
![image](https://user-images.githubusercontent.com/95834771/173731099-80c36acb-2063-405e-b453-d0a8be4bd87c.png)

不知道这个是否符合您的需求，如果还不能满足的话，您可以加一下我的微信，详细描述一下您的需求。
<img width="317" alt="image" src="https://user-images.githubusercontent.com/95834771/173731228-48d4c1ba-668a-4467-a503-0e19652faf53.png">
