### ISSUE TITLE
怎么修改性能测试报告趋势图的时间展示粒度？[QUESTION]

### ISSUE THREAD

**Issue by ShiHongyuan** [metersphere/metersphere#1483]
**请描述您的问题.**
v1.7怎么修改性能测试报告趋势图的时间展示粒度呢，jmeter有相关的参数（jmeter.reportgenerator.overall_granularity）在user.properties里可以设置，但是我在/opt/metersphere/conf/metersohere.properties里设置后重启服务没有生效

**Comment by ShiHongyuan** [comment]
以及metersohere.properties里能够配置的jmeter相关设置参数有哪里呢，有参照列表吗？

**Comment by xulinde** [comment]
jmeter.report.granularity=10000（10s），是这样修改的吗
