### ISSUE TITLE
[QUESTION]metersohere.properties里能够配置的jmeter相关设置参数有哪里呢，有参照列表吗？

### ISSUE THREAD

**Issue by ShiHongyuan** [metersphere/metersphere#1484]
**请描述您的问题.**
不太清楚metersohere.properties里关于jmeter的配置项能够修改哪些内容，因为我有的参数设置了未生效

**Comment by xulinde** [comment]
没有列表，jmeter相关的就jmeter.report.granularity=10000和jmeter.heap=-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m这两个参数

**Comment by Dyc2333** [comment]
我也关注此问题，我们需要配置ssl证书，在没有证书管理器的情况下，只能通过配置jmeter的properties相关文件来配置，但不知道这个文件在哪配置？
