### ISSUE TITLE
[BUG]性能测试刷新频率修改为其他秒值不生效，还是10秒一刷新。

### ISSUE THREAD

**Issue by tianyihuhu** [metersphere/metersphere#14846]
### 联系方式

huxueyan_will@126.com

### MeterSphere 版本

v1.18.3-9f76f55d

### 使用外置数据库

是

### 问题描述

性能测试刷新频率修改为其他秒值不生效，还是10秒一刷新。

### 重现步骤

性能测试刷新频率修改为其他秒值不生效，还是10秒一刷新。

### 附加信息

![30e84e344c7b1867a544b2f6d29cd82](https://user-images.githubusercontent.com/16482933/173721349-57164f9d-ffd8-42bf-bd4d-0edf62d460aa.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v1.20.6-lts没有复现该问题，建议升级一下。

**Comment by liuruibin** [comment]
性能测试计算报告是后台自动计算的，页面上配置的这个值只是页面查询数据库的频率。也就是说如果后台计算比较慢，这里的时间间隔较小的话是不能看到图表的改动的
