### ISSUE TITLE
[FEATURE]建议在接口测试-首页 的统计信息的接口用例数量统计、场景用例数量统计中增加显示 断言数量

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1485]
基于1.7.3
现在接口测试 - 首页 上统计的信息没有断言的统计

建议：
1，接口用例数量统计 中增加断言数量
2，场景用例数量统计 中增加断言数量

建议理由：
被测系统稍微稳定后，api测试可能会很久都不会发现fail。这个时候，会更想知道，我们写的case是不是没有加断言；如果加了断言，整体断言数是否够；如果断言数量比较多，那么基本判断被测系统测试到的点应该都是稳定的。

**Comment by chujidiy** [comment]
另外，建议把场景测试的总体步骤数量也再首页上显示出来。假设20个场景一共有50个步骤，一看就能基本判断这些场景太简单

**Comment by xulinde** [comment]
收到，我们内部讨论下后续是否增加该功能

**Comment by luty2018** [comment]
步骤数和断言数在报告中已经添加了
