### ISSUE TITLE
[BUG]功能用例中的用例状态筛选，筛选结果未完全生效

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#14851]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

功能用例中的用例状态按照已完成筛选，筛选结果中含有未开始
![image](https://user-images.githubusercontent.com/67257251/173724406-ab2d8340-fd9a-4471-a881-a3388d647525.png)

### 重现步骤

1，选择一个测试用例比较多的目录
2，用例状态点击已完成，点击筛选
3，分页展示50条，下拉发现未开始也会展示（如果分页不选择，选择后面页面例如第五页，也会出现未开始状态的用例）

### 期待的正确结果

按照正确的筛选出来

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本1.20.6-lts中已修复，建议升级一下
