### ISSUE TITLE
[BUG][企业用户]翻译问题

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#14869]
### MeterSphere 版本

1.20.6

### 使用外置数据库

是

### 问题描述

没有翻译：
![image](https://user-images.githubusercontent.com/103017812/173760922-93180aa6-4da8-4190-bb0f-9aea1bdacf28.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103017812/173760968-40b69215-bcf1-4322-8a34-cd0f432a0533.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个小版本修复~

**Comment by youliyuan-fit2cloud** [comment]
在最新版本v1.20.7-lts中已修复~
