### ISSUE TITLE
[QUESTION]添加修改请求数据，响应数据脚本功能

### ISSUE THREAD

**Issue by gq-guo** [metersphere/metersphere#1486]
**请描述您的问题.**
如何对请求数据，响应数据进行修改
比如在进行某些接口测试时，请求格式json
参数中的时间，等要求唯一性，在不删除原有测试数据的情况下，能否在发送请求前，使用脚本对请求数据进行处理
现有的前置脚本中没有提供类似的功能

**Comment by wangzhen-fit2cloud** [comment]
你好，可以使用多种方式解决该问题。
1. 在请求体参数值中使用内置函数，例如 ${__time()} 函数生成时间戳
2. 在请求体参数值中使用变量，例如 ${timestamp}，同时在前置脚本中通过 `vars.put("timestamp","1516540541")` 对变量进行赋值，参考 [](https://metersphere.io/docs/tutorial/pre_processor/)
3. 在前置脚本中通过 sampler 对象的方法获取并设置 `sampler.getArguments().getArgument(0).getValue()`，参考 [](https://jmeter.apache.org/api/org/apache/jmeter/protocol/http/sampler/HTTPSamplerProxy.html)
