### ISSUE TITLE
[BUG] msctl reload 后，卡住不动了，见图

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#14868]
### 请描述您的问题

为了节省磁盘空间，做过
rm -rf /opt/metersphere/data/kafka/kafka/data/JMETER_METRICS-0/*.log
rm -rf  /opt/metersphere/data/mysql/mysql-bin.000*
![image](https://user-images.githubusercontent.com/5927005/173757759-30fe4823-e3e2-426e-9937-2108ccbf88eb.png)

然后
msctl reload 后，卡住了

![image](https://user-images.githubusercontent.com/5927005/173755584-4596e78d-ad95-4e8b-8971-7d8c6162ba7f.png)

![image](https://user-images.githubusercontent.com/5927005/173757159-d514003d-c086-4f93-8dec-0cce449caa30.png)

![image](https://user-images.githubusercontent.com/5927005/173755712-f23a0509-b281-42b1-93b5-28c5936a87e0.png)

**Comment by zrfit** [comment]
您好，这2个系统文件是不能删除的。
请执行如下命令：
docker stop kafka
docker stop zookeeper
docker rm kafka
docker rm zookeeper
rm -rf /opt/metersphere/data/kafka/kafka
rm -rf /opt/metersphere/data/zookeeper/zookeeper
msctl reload
