### ISSUE TITLE
[BUG]jmeter脚本的beanshell语法导入平台后，有问题

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#14873]
### MeterSphere 版本

v1.20.5

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/57786489/173762044-3c3ca59b-808d-46ff-ad42-cf1a42f2c260.png)

### 重现步骤

请参考截图，当url分为ip+port和域名的时候做if分支

### 期待的正确结果

当满足if条件后，获取参数值应该正确

**Comment by zyyfit** [comment]
您好，我测试了一下，url = null 的时候不行， url = "" 可以，因为我们用的是jmeter里的插件，这可能是beanshell的语法吧
![image](https://user-images.githubusercontent.com/73461316/174057434-bb2b089d-cbd1-4342-9a82-a41ba133da39.png)

**Comment by zyyfit** [comment]
另外，我也测试了jmeter里，beanshll前置脚本这样写没问题，但是jsr233脚本不行，因为我们要支持多种语言，所以用的是jsr233脚本

**Comment by meifeifei** [comment]
没明白，前面你说jsr233脚本不行，后面说支持多种语言 ，所以用的是jsr233

想表达什么呢？

发件人: zyyfit ***@***.***>
发送时间: 2022年6月16日 19:14
收件人: metersphere/metersphere ***@***.***>
抄送: 梅菲06578 ***@***.***>; Author ***@***.***>
主题: Re: [metersphere/metersphere] [BUG]jmeter脚本的beanshell语法导入平台后，有问题 (Issue #14873)


另外，我也测试了jmeter里，beanshll前置脚本这样写没问题，但是jsr233脚本不行，因为我们要支持多种语言，所以用的是jsr233脚本

**Comment by zyyfit** [comment]
你在jmeter里添加一个jsr233脚本就知道了，就是jsr233脚本虽然他支持beanshell语法，但是url = null就没有输出结果，url = "" 就可以

**Comment by meifeifei** [comment]
请仔细看问题截图，if走的是第一个条件，获取的url并不为null或者“”，但继续后面的语句打印url就没有值了，同样的beanshell脚本在jmeter里面是ok的。

发件人: zyyfit ***@***.***>
发送时间: 2022年6月16日 19:09
收件人: metersphere/metersphere ***@***.***>
抄送: 梅菲06578 ***@***.***>; Author ***@***.***>
主题: Re: [metersphere/metersphere] [BUG]jmeter脚本的beanshell语法导入平台后，有问题 (Issue #14873)


您好，我测试了一下，url = null 的时候不行， url = "" 可以，因为我们用的是jmeter里的插件，这可能是beanshell的语法吧
[图像已被发件人删除。 image]<https://user-images.githubusercontent.com/73461316/174057434-bb2b089d-cbd1-4342-9a82-a41ba133da39.png>
