### ISSUE TITLE
[BUG]jmeter脚本导入后，外部层级的步骤无法拖到内部层级，只能平级拖动

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#14874]
### MeterSphere 版本

v1.20.5

### 使用外置数据库

否

### 问题描述

![Uploading image.png…]()

### 重现步骤

1. 本地编写jmeter脚本，多层级
2. 导入平台后，进行编辑拖拽

### 期待的正确结果

jmeter导入的接口或者元器件的拖拽应该和平台自己的保持一致，都能进行自由拖拽

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前不支持这种拖动。

**Comment by meifeifei** [comment]
后续不会考虑支持吗？

发件人: MatataYou ***@***.***>
发送时间: 2022年6月15日 15:41
收件人: metersphere/metersphere ***@***.***>
抄送: 梅菲06578 ***@***.***>; Author ***@***.***>
主题: Re: [metersphere/metersphere] [BUG]jmeter脚本导入后，外部层级的步骤无法拖到内部层级，只能平级拖动 (Issue #14874)


感谢反馈，目前不支持这种拖动。
