### ISSUE TITLE
项目集成不支持多选问题类型和需求类型

### ISSUE THREAD

**Issue by a574676848** [metersphere/metersphere#14878]
### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/15767357/173764701-1fb5250d-b4f0-485b-9fd4-36f430a08bb0.png)
项目集成不支持多选问题类型和需求类型

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
