### ISSUE TITLE
[FEATURE]接口请求的请求参数建议做成可收缩，太占用页面空间

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#14870]
### MeterSphere 版本

v1.20.5-lts-b2

### 请描述您的需求或者改进建议

![1655275651](https://user-images.githubusercontent.com/57786489/173760844-0eb24033-8b6b-4a4e-85ae-0d2efc81da0f.png)

**Comment by Hyyfit** [comment]
感谢反馈，后续会优化界面，已规划，待排期。
