### ISSUE TITLE
[BUG]接口自动化场景测试报告看不到条件控制器下加请求

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1489]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
正常是可以的，是不是条件控制器加的不对

**Comment by meihaoyidian** [comment]
应该怎么正确加呢

xulinde <notifications@github.com> 于2021年2月24日周三 下午4:56写道：

**Comment by xulinde** [comment]
类似这样，把请求加到条件控制器里面
![image](https://user-images.githubusercontent.com/64065190/108988965-08eda800-76d0-11eb-86b3-386657c860fa.png)

**Comment by meihaoyidian** [comment]
我这边现在是这样的   实际产生的测试结果报告里 看不到接口列表导入的数据

xulinde <notifications@github.com> 于2021年2月24日周三 下午6:43写道：

**Comment by Betrayme** [comment]
> 类似这样，把请求加到条件控制器里面 ![image](https://user-images.githubusercontent.com/64065190/108988965-08eda800-76d0-11eb-86b3-386657c860fa.png)

@xulinde 
版本V1.19.1
自动化执行成功后（条件控制器也执行成功），测试报告中，不显示条件控制器及子项的所有内容
