### ISSUE TITLE
[BUG]接口自动化中前置操作sql取出的列名变量，后置脚本中取不到相应的值

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#14904]
### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

前置操作sql设置了列名变量，后置操作取不到对应的值
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/39123539/173782443-3e4135ed-7d91-4db4-a22a-54dcb477c749.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/39123539/173782979-302a363b-b71a-46cd-80aa-50e197ed871d.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/39123539/173783174-c732a326-d4d8-45c2-8ea9-6c86f2d1d3e0.png">
整个结果的可以取到，如下：
<img width="846" alt="image" src="https://user-images.githubusercontent.com/39123539/173783696-e47dd25c-8f90-444e-9f9f-2b702d8de486.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/39123539/173783783-69c3af64-14b9-45fb-af24-5b2a83103840.png">

### 重现步骤

1、普通接口配置前置sql操作查询sql，配置按列存储
2、配置后置脚本去获取前置sql中的列变量对应的值

### 期待的正确结果

能取到name的值

**Comment by youliyuan-fit2cloud** [comment]
你这个打印的变量写的不对吧，
参考如下试试
log.info("++++++++++"+vars.get("name_1"));
