### ISSUE TITLE
性能测试不支持不同网段的性能测试吗？[QUESTION]

### ISSUE THREAD

**Issue by ShiHongyuan** [metersphere/metersphere#1490]
**请描述您的问题.**
主网站的机器是阿里云的，以allinone方式安装，另一个节点是腾讯云的，以node-controller方式安装，安装方式为在线安装，按照使用手册安装，在allinone节点的性能测试资源池添加腾讯云的node-controller节点可以连接成功，但是运行性能测试时，报错无法连接kafka

两个节点均使用公网ip，可以互相ping通，已查看所有容器状态健康，node-controller节点上使用docker exec ms-node-controller nc -zv [allinone节点的公网ip] 19092查看为open状态
运行测试时node-controller节点的/opt/metersphere/logs/node-controller/error.log日志如下：
2021-02-24 10:26:02,599 [qtp453523494-19] ERROR i.m.n.service.JmeterOperateService 141 - Method[checkKafka][java.net.SocketTimeoutException: connect timed out]

**Comment by xulinde** [comment]
检查下，安装node-controller的容器是否能连接上kafka

**Comment by abcanqi** [comment]
我也遇到了，查了半天，解决方法是

将部署 node-controller 的机器的 hostname 配置到部署 ms-server 机器的 /etc/hosts 文件里。

例如：
```vim
127.0.0.1 xxxx
```

真他妈的
