### ISSUE TITLE
[BUG]自动化场景引入其他场景后，被引入的场景步骤复制的API或者CASE可以打开或关闭，但是不起作用

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#14918]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.5-LTS

### 使用外置数据库

否

### 问题描述

自动化场景引入其他场景后，被引入的场景步骤复制的API或者CASE可以打开或关闭，但是不起作用；
希望可以把被引入步骤下的子步骤的开关按钮给禁掉，否则可用户产生歧义，认为仍然可以编辑，但是实际保存刷新或者执行并没有实际效果

### 重现步骤

1、创建新的自动化场景
2、引用其他自动化场景
3、被引入的场景下的子步骤中，复制的API或者CASE可以打开关闭
4、保存之后，再刷新场景发现没有修改成功

### 期待的正确结果

希望被引用的场景下的子步骤开关按钮置灰，不能点击，否则产生很多歧义，引起不必要的解释和时间浪费

### 附加信息

![image](https://user-images.githubusercontent.com/32027713/173796891-12badddd-f33a-401a-abb7-269d02adf510.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续会优化

**Comment by youliyuan-fit2cloud** [comment]
v1.20.8-lts中已优化该问题，请升级一下吧
