### ISSUE TITLE
[BUG]UI自动化，选择后端调试，执行失败的步骤结果时有时无

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#14919]
### 联系方式

张树彬

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

UI自动化，选择后端调试，执行失败的步骤结果时有时无

### 重现步骤

1. UI自动化场景
2. 选择后端调试
3. 出现执行失败的步骤，步骤结果那个菜单时有时无

### 期待的正确结果

每次执行后端调试，如出现执行失败的步骤，都应该显示步骤结果菜单及信息

### 附加信息

![5e57e1ab9061099e468a5478bdfe2da](https://user-images.githubusercontent.com/77324661/173799494-caf6c8d7-a031-4492-ad5c-ee4bd32bbed4.png)

**Comment by zrfit** [comment]
您好，已知问题，v1.20.7-lts会修复。

**Comment by zrfit** [comment]
v1.20.7-lts已修复。
