### ISSUE TITLE
[QUESTION]v1.20分支构建mvnd构建失败

### ISSUE THREAD

**Issue by dapangyu-fish** [metersphere/metersphere#14917]
### 请描述您的问题

我在最新的v1.20分支执行./nvmw clean package -e 报错
![221655284264_ pic](https://user-images.githubusercontent.com/68261559/173796553-7511506d-93d1-4c6d-acfd-bfae174df511.jpg)
![231655284264_ pic](https://user-images.githubusercontent.com/68261559/173796567-a5b811f1-3641-4e54-a884-47f68aba49d9.jpg)

**Comment by Hyyfit** [comment]
您好，可以在我们的微信交流群内，@我们的技术人员，帮您远程协助排查问题。
