### ISSUE TITLE
[FEATURE]建议加上自动化用例的定时任务

### ISSUE THREAD

**Issue by liangzeliang** [metersphere/metersphere#14928]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 请描述您的需求或者改进建议

建议加上自动化用例的定时任务

**Comment by Hyyfit** [comment]
您好，麻烦详细描述您的需求。我们有定时任务的功能

**Comment by liangzeliang** [comment]
创建测试计划后，可以定时执行计划里面的接口自动化用例，但是无法将ui自动化用例关联到计划里面，所以就无法定时执行自动化用例

**Comment by ruibaby** [comment]
@liangzeliang Hello，建议完善一下这个 issue 的 title 描述，目前在 issues 列表无法直观的查看。

**Comment by Hyyfit** [comment]
感谢反馈，UI自动化用例加入测试计划中的功能已规划，2.0版本上线。
