### ISSUE TITLE
[BUG]旧版本场景转换及新版本场景引用头部信息丢失，新版本添加引用其他场景也无法使用头部信息

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#1492]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.3

**Bug 描述**
简要描述您碰到的问题
问题1：
切换至旧版本，旧版本的多个场景中有头部信息，进行场景转换到新版本后，执行时未解析到头部信息，同时针对引用的场景
![image](https://user-images.githubusercontent.com/9674075/108953414-1e4ddc80-76a6-11eb-9fc8-1cc81f07e1af.png)
下图无法查看红框中场景的头部信息，只有最上方变量针对所有场景的公共头部信息
![image](https://user-images.githubusercontent.com/9674075/108953483-3a517e00-76a6-11eb-9e02-afb084e957ed.png)
原因是在旧版本转换数据过程中，针对复制场景中的单个场景未设置头部信息，导致数据丢失，如下图。
![image](https://user-images.githubusercontent.com/9674075/108953580-6a991c80-76a6-11eb-8bd1-8d06772670f3.png)

问题2：
在新版本中，引用其他场景（包含头部信息）后，在新场景保存时无header信息保存下来（设计中不存在该部分信息），因此与问题1中部分情形类似，子场景头部信息失败设计，无法引用到其他场景。

**期待的正确结果**
正确情况下应该是什么样的？

**Comment by xulinde** [comment]
收到，我们复现下

**Comment by xulinde** [comment]
v1.8已修复
