### ISSUE TITLE
[BUG]测试报告导出成html后，本地打开html文件无法显示“功能用例统计分析”目录及数据

### ISSUE THREAD

**Issue by wjjoai** [metersphere/metersphere#14922]
### MeterSphere 版本

1.20.5以及1.20.6

### 使用外置数据库

是

### 问题描述

测试报告导出成html后，本地打开html文件无法显示“功能用例统计分析”目录及数据
平台中的报告如下：
![image](https://user-images.githubusercontent.com/28913533/173807240-7f965490-9be3-4fc9-9385-bb99c9fd73b6.png)

本地打开html格式报告如下：
![image](https://user-images.githubusercontent.com/28913533/173807367-c62f1ada-394e-4df8-a59d-b2f6642379ee.png)

### 重现步骤

1、在测试跟踪里面将测试报告导出
2、本地打开导出的html报告

**Comment by youliyuan-fit2cloud** [comment]
在最新版本v1.20.7-lts中已修复~
