### ISSUE TITLE
[BUG]form-data数据的接口，ms平台与postman访问后的结果不同，ms平台报错，postman正常，服务日志显示是file丢失

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#14923]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

[BUG]form-data数据的接口，ms平台与postman访问后的接口不同，ms平台报错，postman正常，服务日志显示是file丢失
![微信截图_20220615202050](https://user-images.githubusercontent.com/38156471/173830404-b84d56b2-6c6f-458a-ade8-9c756a631445.png)
![微信截图_20220615202110](https://user-images.githubusercontent.com/38156471/173830418-44ef2f94-d762-442c-af06-311c59758b73.png)
![微信截图_20220615202123](https://user-images.githubusercontent.com/38156471/173830422-083fb635-bf50-4216-9a39-45848cdea54c.png)
![微信截图_20220615202131](https://user-images.githubusercontent.com/38156471/173830426-2fa20012-845d-4ecb-8345-a8d80c20c422.png)
![微信截图_20220615204432](https://user-images.githubusercontent.com/38156471/173830428-5156b5e3-5cc6-4a4a-b4c9-6f28d3bccbfb.png)

### 重现步骤

[BUG]form-data数据的接口，ms平台与postman访问后的接口不同，ms平台报错，postman正常，服务日志显示是file丢失
![微信截图_20220615202050](https://user-images.githubusercontent.com/38156471/173830404-b84d56b2-6c6f-458a-ade8-9c756a631445.png)
![微信截图_20220615202110](https://user-images.githubusercontent.com/38156471/173830418-44ef2f94-d762-442c-af06-311c59758b73.png)
![微信截图_20220615202123](https://user-images.githubusercontent.com/38156471/173830422-083fb635-bf50-4216-9a39-45848cdea54c.png)
![微信截图_20220615202131](https://user-images.githubusercontent.com/38156471/173830426-2fa20012-845d-4ecb-8345-a8d80c20c422.png)
![微信截图_20220615204432](https://user-images.githubusercontent.com/38156471/173830428-5156b5e3-5cc6-4a4a-b4c9-6f28d3bccbfb.png)

### 期待的正确结果

与postman一样就可以了，下方附有接口信息和文件

### 附加信息

http://zdhcs.bestkunlun.com/kaps-server/importExcel/kaps_dept
jwt-token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrZWRhIiwiZXhwIjoxNjU1MjgzMjY2LCJ1c2VybmFtZSI6ImthcHNfYWRtaW4ifQ.M2mqZTI1qGokurEJ999cnLqEAyqaZ2zCzyBfrotQni4
Content-Type  multipart/form-data; boundary=----WebKitFormBoundaryfUn0YEELpa5JVFGV
[8000条部门.csv](https://github.com/metersphere/metersphere/files/8909390/8000.csv)

**Comment by zyyfit** [comment]
1、我们执行接口是用的jmeter，所以如果postman和jmeter有冲突，我们一般和jmeter保持一致
2、没有复现这个问题，可以检查一下这个接口里的文件在服务器上还在吗，不在的话重新上传一下试试
![image](https://user-images.githubusercontent.com/73461316/174059548-1011b13d-18de-4a16-84ca-4d1939327b26.png)

**Comment by zyyfit** [comment]
这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？

**Comment by YellCatt** [comment]
> 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊

**Comment by YellCatt** [comment]
> > 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
> > 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
> > 网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊

网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊

**Comment by YellCatt** [comment]
> > > 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
> > > 这个报错是超时了，请排查一下超时原因，比如ms和被测系统网络通吗？被测接口能正常响应吗？
> > > 网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊
> 
> 网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊

网络是通的，接口能正常响应，我都给你那么多截图了，都是一个接口在MS平台上访问，都有问题，你请求下我这个接口不就清楚了吗？我服务一直正常运行，如果你觉得不是ms的问题，你可以直接加我访问，你可以直接加我QQ768305875,再次确认下问题，gitlab上交流真累啊

**Comment by zyyfit** [comment]
用jmeter测试了也是一样的情况，如果postman和jmeter有冲突的话，我们暂时与 jmeter 保持一致

**Comment by 20170916** [comment]
v1.20.12-lts 版本依然有这个问题
