### ISSUE TITLE
Jenkins自动构建问题

### ISSUE THREAD

**Issue by ituta-git** [metersphere/metersphere#1496]
【问题】Jenkins触发接口测试执行时，接口头部信息不是最新的
  描述：1、metersphere定时任务A修改环境信息的头部，每半小时执行一次
           （ 调用metersphere的 "/api/environment/update" 接口实现）
             2、Jenkins每日触发接口用例执行，时间为定时任务A执行后10分钟
  结果：用例执行失败
  原因：Jenkins触发执行 取的不是 定时任务A执行后 最新的头部信息
  图片：
  ![image](https://user-images.githubusercontent.com/57891222/108973017-e0a97d80-76be-11eb-9b88-86e3a7469b54.png)
 ![image](https://user-images.githubusercontent.com/57891222/108973098-f28b2080-76be-11eb-8926-c33ce0fa19de.png)

【问题】Jenkins触发执行测试计划后，报告中执行结果一直为进行中
  图片：
![image](https://user-images.githubusercontent.com/57891222/108976840-e7d28a80-76c2-11eb-97e1-6d79ce0f128e.png)

【建议】Jenkins触发执行测试计划，每条用例会发一条通知消息 --- 建议合并发送一条信息
  图片：
![image](https://user-images.githubusercontent.com/57891222/108973365-3716bc00-76bf-11eb-89db-4ef3e19806f5.png)

**Comment by xulinde** [comment]
收到，我们复现下
