### ISSUE TITLE
[BUG]环境配置里面--前局前置脚本没有生效

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#14966]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

在环境配置里面，设置 全局前置脚本没有生效

### 重现步骤

![image](https://user-images.githubusercontent.com/15188833/174029838-e83fd4f9-94a0-44c9-9d27-9b45e51592c2.png)

**Comment by youliyuan-fit2cloud** [comment]
全局前置脚本设置 中 ，过滤请求类型，如果选了http，就不再该协议的请求结果控制台中了....

**Comment by startpjx** [comment]
社区反馈版本：1.20.4  同一个环境
case：前局前置脚本，返回失败  
![image](https://user-images.githubusercontent.com/15188833/174771701-958090c9-6972-4c17-8469-2859939306e0.png)
自动化场景：
![image](https://user-images.githubusercontent.com/15188833/174771826-0e219518-bd3f-4299-b986-255f96051cff.png)
