### ISSUE TITLE
[BUG]执行UI测试时，有时会报SQL Occured报错，页面上一直打转（偶发）

### ISSUE THREAD

**Issue by cjwts** [metersphere/metersphere#14960]
### 联系方式

junjie.du@fit2cloud.com

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

MeterSphere为本地部署，机器规格为4C8G，自从升级到1.20.4版本后，每隔两天左右，执行测试时前端会报“SQL error happened，please check logs”，然后页面就一直转圈，也不会报错退出，刷新页面后，页面无变化，初步判断任务并未开始执行。
报错截图如下：
![2b2846ceeec88df029cae26a338a059](https://user-images.githubusercontent.com/30405402/174021136-26a37ce8-fcea-4938-a8ca-e05708247533.png)
一旦重启ms服务，再重新执行测试，则能够正常执行，下图为同一UI场景测试，服务重启后重新执行截图，可以看到执行成功。
![image](https://user-images.githubusercontent.com/30405402/174021341-5e953627-e9d3-4814-ac6a-5c4015abb8a5.png)

报错后在mysql执行show processlist，会看到部分query进程卡死。截图等现象下次出现时再补充到评论中，这次急于恢复，未来得及截图

重启后再执行相同命令，则未看到卡死进程。
![image](https://user-images.githubusercontent.com/30405402/174023169-466700fc-1a72-444f-bc11-ecf19a9d51ee.png)

### 重现步骤

暂未得出能稳定重现的执行步骤，只知道是基本两到三天就会出现一次，这之中也未有大量数据创建及执行的操作

### 期待的正确结果

如出现SQL Error执行相关的报错，可在报错中加上执行错误的日志，目前只要是涉及到SQL相关的日志，除非是明确哪些表格不存在类型的错误，其他只能去数据库进行排查，无法确定报错sql

**Comment by zrfit** [comment]
您好，暂时未复现该问题，后续会支持关注下，如果再次遇到及时截图下后端报错，多谢您。
