### ISSUE TITLE
[QUESTION]针对每个接口写测试用例时，如何获取cookie

### ISSUE THREAD

**Issue by Anduin-Zhu** [metersphere/metersphere#1497]
**请描述您的问题.**
针对导入的接口，单一接口进行测试用例编写，
比如获取项目列表接口（此接口需要cookie），如何获取？
![image](https://user-images.githubusercontent.com/29295893/108975646-adb4b900-76c1-11eb-9712-dbe91f12805f.png)

**Comment by Anduin-Zhu** [comment]
当接口A传参需要接口B返回的信息，对接口A写测试用例时，如何获取接口B的信息，是不是只能用场景的方式来实现
![image](https://user-images.githubusercontent.com/29295893/108981740-fec7ab80-76c7-11eb-88b0-ab6d61165600.png)

**Comment by xulinde** [comment]
是的，目前只能把两个接口组合成一个场景实现
