### ISSUE TITLE
代码片段执行时如果有个一直没有返回，其他的代码片段也无法执行[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#14981]
### 联系方式

dongxue.liu@fit2cloud.com

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

代码片段执行时如果有个一直没有返回，其他的代码片段也无法执行。必须要刷新浏览器才行。

### 重现步骤

1.第一个代码片段，在执行中无返回
![image](https://user-images.githubusercontent.com/30932762/174075577-5fa055b7-9c73-4bb0-9231-b894edfc2796.png)
2.打开其他的代码片段也无法执行
![image](https://user-images.githubusercontent.com/30932762/174075696-0ba1ecae-a0ef-4e48-a8c4-adf89ba400c7.png)

### 期待的正确结果

不同代码片段的界面执行应该是互不影响菜单

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.20.8版本发布，请等待发版后验证
