### ISSUE TITLE
[BUG]通过Jenkins执行从csv文件中取数的场景时，从第二次循环开始取不到数

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1498]
**MeterSphere 版本**
v1.7.3-2b9713b1

**Bug 描述**
通过Jenkins执行从csv文件中取数的场景时，从第二次循环开始取不到数

**Bug 重现步骤**
1.  新建一个测试场景，测试步骤中有一个循环控制器，循环控制器下引用的接口用例进行了参数化
2. 场景变量中新建一个CSV变量，上传的CSV文件中有多条数据
3. 设定循环控制器为次数循环
4. 测试跟踪中新建测试计划，该计划包含上述步骤新建的测试场景以及其它场景
5. Jenkins中执行该测试计划

**期待的正确结果**
带有循环控制器的场景能够按照顺序依次取数用于请求的发送

**实际的结果**
第一次循环取数正常，第二次取不到数

**其它说明**
如果测试计划中只有复现步骤的那一个带有循环控制器的场景的话，是可以正常执行成功的。但是，再加上其它的测试场景的话，就会执行失败！

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/57166905/108975584-9c6bac80-76c1-11eb-9cba-f6c9843778f6.png)
![image](https://user-images.githubusercontent.com/57166905/108976245-45b2a280-76c2-11eb-9cf8-c0681aac737c.png)
![image](https://user-images.githubusercontent.com/57166905/108976534-95916980-76c2-11eb-871f-b89edcf977bc.png)
![image](https://user-images.githubusercontent.com/57166905/108976729-c70a3500-76c2-11eb-8551-32e2d6b34a52.png)

**Comment by xulinde** [comment]
感谢反馈，我们复现下

**Comment by zyyfit** [comment]
您好，您可以升到最新版试一下，应该没有这个问题了
