### ISSUE TITLE
[FEATURE] 新增case,场景引用看不到自己新增的case

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#14996]
### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

新增case,场景引用看不到自己新增的case，需要切换到api,再切回到case列表，才能看到

### 重现步骤

1.创建一个场景
2.引用case
3.点击case的id进入case页面
4.关闭当前case，复制一个新case并保存
5.在原场景引用新复制的case

### 期待的正确结果

点接口列表导入时，能看到新增加的case

### 附加信息

https://user-images.githubusercontent.com/45531073/174219047-8a2ded00-422b-47d4-a8b9-b44b82b32ded.mp4

**Comment by youliyuan-fit2cloud** [comment]
你好，场景用例这边没有一直编辑状态，再次打开还是上一次的case列表，关掉场景再次编辑或者切换一下api和case页面就可以了，个人认为不需要优化

**Comment by luty2018** [comment]
在导入页面增加刷新按钮，已转需求处理
