### ISSUE TITLE
[BUG]从旧版接口测试转到新版的场景自动化测试无法正常编辑

### ISSUE THREAD

**Issue by likewyz** [metersphere/metersphere#1499]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
从旧版接口测试转到新版的场景自动化测试无法正常编辑

**Bug 重现步骤**

**期待的正确结果**
正确情况下应该是什么样的？
由于转换过来的sql请求没有数据源，需要手动配置，但是由于无法正常编辑导致原本的请求无法正常运行，希望可以尽快处理

**截图**
如果有截图，请附上截图.
查看源码之后，猜测可能存在的原因
io.metersphere.api.dto.definition.request.MsTestElement#getRefElement

![image](https://user-images.githubusercontent.com/31504416/108982230-87dee280-76c8-11eb-8ccc-03e03ab6c2ce.png)
此方法中没有使用入参的element 的id去取数据

**Comment by xulinde** [comment]
没有复现您的问题，控制台或者日志有报错截图吗

**Comment by likewyz** [comment]
> 没有复现您的问题，控制台或者日志有报错截图吗

控制台没有报错，其实接口返回也是正常的，update成功了，但其实数据里无论填了还是没填，都是保存成功

**Comment by wangzhen-fit2cloud** [comment]
@fit2-zhao  勇哥确认下吧

**Comment by likewyz** [comment]
![image](https://user-images.githubusercontent.com/31504416/109005884-6c360500-76e5-11eb-8f6c-c3175649aa3b.png)
两个场景步骤，根据后面的观察，数据库中只更新了第一条
![image](https://user-images.githubusercontent.com/31504416/109006029-8e2f8780-76e5-11eb-8d60-e5f56ab9c7b0.png)
而没有更新第二条和第三条，但数据步骤数据却又是从第二条第三条拿的

**Comment by fit2-zhao** [comment]
@likewyz 您好，引用场景不能修改，您可以到引用的源头修改，比如当前场景引用了A,B 两个场景步骤，如果想调整这两个步骤到 A ｜ B 场景编辑进去修改。
这里引用功能会在1.8 优化一下，引用场景或 接口 编辑按钮不能操作。

**Comment by likewyz** [comment]
> @likewyz 您好，引用场景不能修改，您可以到引用的源头修改，比如当前场景引用了A,B 两个场景步骤，如果想调整这两个步骤到 A ｜ B 场景编辑进去修改。
> 这里引用功能会在1.8 优化一下，引用场景或 接口 编辑按钮不能操作。

问题是，转换过来的sql请求需要配置运行环境和数据源，不配置就没法执行，不得不尝试去修改

**Comment by fit2-zhao** [comment]
@likewyz 可以到引用的那个场景上改，不要在当前场景步骤修改

![image](https://user-images.githubusercontent.com/70558837/109255358-c8587080-782e-11eb-95ed-12dafdf7f3bb.png)
![image](https://user-images.githubusercontent.com/70558837/109255430-efaf3d80-782e-11eb-9bd9-07d8b4354a02.png)

**Comment by likewyz** [comment]
> @likewyz 可以到引用的那个场景上改，不要在当前场景步骤修改
> 
> ![image](https://user-images.githubusercontent.com/70558837/109255358-c8587080-782e-11eb-95ed-12dafdf7f3bb.png)
> ![image](https://user-images.githubusercontent.com/70558837/109255430-efaf3d80-782e-11eb-9bd9-07d8b4354a02.png)

你的意思是在原本的接口里改？可是原本的接口是旧版的接口，并不支持去改每个sql请求的环境和数据源呀

**Comment by leopardxu** [comment]
升级了新的版本（新版UI），老的接口测试数据没有加载上来~~  ，返回旧版UI 数据正常，什么原因？
