### ISSUE TITLE
[BUG]在场景中复制接口导入，调试完成后接口没有响应结果，导致无法使用推荐jsonpath断言

### ISSUE THREAD

**Issue by Anduin-Zhu** [metersphere/metersphere#1501]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.0-3c6a4849
**Bug 描述**
简要描述您碰到的问题
在场景中复制接口导入，调试完成后接口没有响应结果，导致无法使用推荐jsonpath断言
**Bug 重现步骤**
1.  调试结果显示通过，并有数据
![image](https://user-images.githubusercontent.com/29295893/109092332-4e05ee80-7751-11eb-9633-0ce52c73b58f.png)

2. 

2. 查看接口的xiang响应结果xianshi为空

![image](https://user-images.githubusercontent.com/29295893/109092383-6249eb80-7751-11eb-8cf9-988ef1951501.png)

3. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前单个步骤中的响应内容需要点击该步骤上的执行按钮才会有，点击场景的调试按钮不会更新响应内容。
我们会在后续的版本中优化下这个地方。
