### ISSUE TITLE
[BUG] 并发测试时个别接口 1000次成功会出现一次 （Non HTTP response code: javax.net.ssl.SSLHandshakeException）异常

### ISSUE THREAD

**Issue by Yule-Momoko** [metersphere/metersphere#15022]
### 联系方式

1129032101@qq.com

### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

 并发测试时个别接口 1000次成功,但会出现一次 （Non HTTP response code: javax.net.ssl.SSLHandshakeException）错误

会出现以下两种类型错误
Non HTTP response code: javax.net.ssl.SSLHandshakeException
Non HTTP response code: java.net.ConnectException

### 重现步骤

 并发测试时个别接口 1000次成功,但会出现一次 （Non HTTP response code: javax.net.ssl.SSLHandshakeException）错误

会出现以下两种类型错误
Non HTTP response code: javax.net.ssl.SSLHandshakeException
Non HTTP response code: java.net.ConnectException

**Comment by zyyfit** [comment]
您好，这个问题是不是网站的防刷机制呢？就是连续压测多次，系统自动拒绝访问之类的
