### ISSUE TITLE
[BUG]执行接口自动化，耗时特别长

### ISSUE THREAD

**Issue by limaomaoyyds** [metersphere/metersphere#15031]
### MeterSphere 版本

1.20.7

### 使用外置数据库

否

### 问题描述

如题

### 重现步骤

如题

**Comment by youliyuan-fit2cloud** [comment]
你好，请详细说明接口自动化场景配置，方便的话把场景用例导出来我们复现看看

**Comment by limaomaoyyds** [comment]
不好意思，数据不太方便导出来，场景配置挺简单，不超过10条接口。我有两套运行环境，有一套执行还挺快，另一个很慢

**Comment by youliyuan-fit2cloud** [comment]
> 不好意思，数据不太方便导出来，场景配置挺简单，不超过10条接口。我有两套运行环境，有一套执行还挺快，另一个很慢

运行环境 开启了host ？关闭host 试试吧，我们这边也尝试复现

**Comment by limaomaoyyds** [comment]
对，有开host  我关掉试试

**Comment by xulinde** [comment]
您好，1.请检查下运行环境是否配置了证书，加载证书过程略慢，属于正常现象；2.host我们这边测试正常，请再检查下您网络的dns 解析
