### ISSUE TITLE
[接口用例]修改接口定义后，之前在接口定义下写的测试用例没有自动更新

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1504]
**MeterSphere 版本**
v1.7.3

**Bug 描述**
修改接口定义后，之前在接口定义下写的测试用例没有自动更新

**Bug 重现步骤**
1.  新增一个接口定义
2. 为接口定义创建测试用例
3. 保存测试用例后，修改接口定义中的path路径，请求体，并保存
4. 定义修改前保存的测试用例的path路径和参数没有自动update

**期待的正确结果**
接口定义更新后，case应该自动更新

**Comment by gq-guo** [comment]
相同问题

**Comment by xulinde** [comment]
您好，接口定义变更，用例是不会变更的，接口用例有批量编辑的功能，可以单独对用例做变更
