### ISSUE TITLE
[BUG] Windows谷歌浏览器sql脚本输入框看不到

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#15044]
### 联系方式

18311441708

### MeterSphere 版本

1.20.5.lts

### 使用外置数据库

否

### 问题描述

Windows谷歌浏览器比例百分百看不到，百分之百以下可以看到sql脚本内容
百分百比例
<img width="864" alt="1655465038(1)" src="https://user-images.githubusercontent.com/103925124/174289285-b07f44f3-ae72-4704-8169-fe98ccafebf2.png">

百分之90
<img width="750" alt="1655464326(1)" src="https://user-images.githubusercontent.com/103925124/174288148-d4f3f53e-3d4d-4ea1-962d-3863743b4ad3.png">

![1655464552(1)](https://user-images.githubusercontent.com/103925124/174288087-89c4b2a5-2ec6-4ba5-a67b-31dcbb1ed418.jpg)

sql脚本输入框看不到，且没有下拉框可以调试到

### 重现步骤

Windows11

分辨率 1920*1080

谷歌浏览器比例百分百

前后置sql里面的sql脚本看不到

### 附加信息

https://user-images.githubusercontent.com/103925124/174288584-f9246973-dd73-4961-8818-a31a7d3d435d.mp4

**Comment by zyyfit** [comment]
您好，暂时不支持非100%比例的兼容性问题

**Comment by zyyfit** [comment]
另外，您为什么要缩小比例呢？是有什么内容在正常比例下展示不完整吗？

**Comment by ruibaby** [comment]
> 另外，您为什么要缩小比例呢？是有什么内容在正常比例下展示不完整吗？

这个 issue 说的是在正常情况下（分辨率 1080P，浏览器没有设置缩放）的时候无法正常显示 SQL 脚本内容。在缩放浏览器的时候才能正常显示。

这应该是一个前端分辨率适配的问题。

**Comment by zyyfit** [comment]
1.20.8优化了这个问题，请等待版本发布后验证@ruibaby @Ycr123888

**Comment by ruibaby** [comment]
> 1.20.8优化了这个问题，请等待版本发布后验证@ruibaby @Ycr123888 

@zyyfit Hello，能否关联一下具体修复这个问题的 PR 或者 commit 呢？

**Comment by wangzhen-fit2cloud** [comment]
> > 另外，您为什么要缩小比例呢？是有什么内容在正常比例下展示不完整吗？
> 
> 这个 issue 说的是在正常情况下（分辨率 1080P，浏览器没有设置缩放）的时候无法正常显示 SQL 脚本内容。在缩放浏览器的时候才能正常显示。
> 
> 这应该是一个前端分辨率适配的问题。

#15222
