### ISSUE TITLE
[BUG]场景用例执行成功后，等待控制器会变成英文

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#15047]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/38156471/174411573-2aad4ba5-5c7b-4d95-9d8b-57df00e9d8cb.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/38156471/174411573-2aad4ba5-5c7b-4d95-9d8b-57df00e9d8cb.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本优化下

**Comment by xulinde** [comment]
v1.20.8已修复，建议您升级
