### ISSUE TITLE
[接口用例]接口用例点击执行后，会把详情页自动收缩

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1505]
**MeterSphere 版本**
V1.7.3

**Bug 描述**
接口用例点击执行后，会把详情页自动收缩，需要再点击一次展开按钮才能看到执行情况

**Bug 重现步骤**
1.  创建一个接口定义
2. 在接口定义下编写一条测试用例并执行
3. 执行以后，测试用例的详情页会自动收缩，导致无法直接观看运行情况

**期待的正确结果**
执行用例后，不需要自动收缩页面

**Comment by xulinde** [comment]
点击执行结果会自动展开，可以查看执行情况
![image](https://user-images.githubusercontent.com/64065190/109134145-b6c08b80-7790-11eb-9267-aae6768127c7.png)
