### ISSUE TITLE
[QUESTION] 如何定义并生效自增 ID

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15057]
### 请描述您的问题

如何定义变量，定义一个自增 ID， 

![image](https://user-images.githubusercontent.com/5927005/174482700-761dd110-f971-44cb-bf07-2b797320952d.png)
![image](https://user-images.githubusercontent.com/5927005/174482725-b0d7c85a-af74-4b35-bbeb-019a577530a0.png)

**Comment by Hyyfit** [comment]
您好，可以通过场景自动化实现。
首先是场景变量中 添加 “计数器”，然后选择‘条件控制器’，通过次数循环或while循环的方式，实现自增id
