### ISSUE TITLE
[BUG]环境变量放在场景测试中的url中带有中括号

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#15056]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.7-lts

### 使用外置数据库

否

### 问题描述

环境变量放在场景测试中的url中带有中括
![微信截图_20220618222331](https://user-images.githubusercontent.com/38156471/174465312-42bae9db-2567-44ac-bfcc-ea9bf9d81b10.png)
![微信截图_20220618222359](https://user-images.githubusercontent.com/38156471/174465316-b7777e07-c1de-46f8-a895-98a2c2f161e6.png)
号

### 重现步骤

环境变量放在场景测试中的url中带有中括
![微信截图_20220618222331](https://user-images.githubusercontent.com/38156471/174465312-42bae9db-2567-44ac-bfcc-ea9bf9d81b10.png)
![微信截图_20220618222359](https://user-images.githubusercontent.com/38156471/174465316-b7777e07-c1de-46f8-a895-98a2c2f161e6.png)
号

### 期待的正确结果

没有括号

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
经过排查，发现这个问题是jmeter的一个bug，然后我们测试了一下，这个变量带端口号的话，就会带上 [ ] ，不带端口号就是正常的。目前我们不对jmeter的源码进行修改，您先把地址和端口号分开写吧
