### ISSUE TITLE
[BUG] 接口定义页面无法导入 sawgger，找不到 swagger

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15062]
### MeterSphere 版本

版本:   v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

![Uploading image.png…]()

### 重现步骤

![image](https://user-images.githubusercontent.com/5927005/174519293-58f30f07-9aa3-47e4-9b6c-5542b05e7c7c.png)

**Comment by youliyuan-fit2cloud** [comment]
使用什么浏览器啊？chrome还是firefox都没问题。

**Comment by matthewxuda** [comment]
![image](https://user-images.githubusercontent.com/5927005/174524763-edf9a53d-b29a-4384-ade1-1fbee4f7986b.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，左侧选择SQL协议的时候不支持导入swagger...
