### ISSUE TITLE
[FEATURE] 建议邮件报告可根据不同的项目进行定制化，且报告内容丰富

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#15066]
### MeterSphere 版本

版本:   v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

建议邮件报告可根据不同的项目进行定制化，且报告内容丰富一些

### 请描述你建议的实现方案

建议邮件报告可根据不同的项目进行定制化，且报告内容丰富一些

**Comment by luty2018** [comment]
能否具体说明下如何定制化，目前已经是按项目隔离，自定义报告以及内容
