### ISSUE TITLE
[BUG] 版本:   v1.20.1-lts-64d951ea 不支持 swagger 导入了

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15061]
### MeterSphere 版本

 v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

不支持 swagger 导入了

![image](https://user-images.githubusercontent.com/5927005/174517231-4c3ec580-497c-4c11-a7f8-02ad2b9bba5f.png)
![image](https://user-images.githubusercontent.com/5927005/174517268-f6d67077-ad9e-465d-a568-53f9578b34f7.png)

### 重现步骤

不支持 swagger 导入了

![image](https://user-images.githubusercontent.com/5927005/174517231-4c3ec580-497c-4c11-a7f8-02ad2b9bba5f.png)
![image](https://user-images.githubusercontent.com/5927005/174517268-f6d67077-ad9e-465d-a568-53f9578b34f7.png)

### 期待的正确结果

支持

**Comment by youliyuan-fit2cloud** [comment]
你好，你这里是场景。。导入swagger是接口定义页面。
