### ISSUE TITLE
[FEATURE] jira缺陷双向同步功能建议添加至开源版本，提升用户体验

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#15065]
### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

jira缺陷双向同步功能建议添加至开源版本，提升用户体验

### 请描述你建议的实现方案

jira缺陷双向同步功能建议添加至开源版本，提升用户体验

**Comment by luty2018** [comment]
目前双向同步是企业版功能，后续会考虑将部分企业版功能开源出去
