### ISSUE TITLE
[BUG]测试计划-测试用例已经执行完了，点击通过还是提示下一条  应该提示执行完成

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#15075]
### MeterSphere 版本

v1.20.5-lts-9fe3acfd

### 使用外置数据库

否

### 问题描述

测试计划-测试用例已经执行完了，点击通过还是提示下一条  应该提示执行完成

### 重现步骤

测试计划-关联功能用例
点击用例执行时候，点击最后一条，标记通过一直提示下一条。

<img width="960" alt="测试计划-测试用例已经执行完了，点击通过还是提示下一条" src="https://user-images.githubusercontent.com/43202800/174533787-2f68a812-f22b-466e-ba20-ac4160317390.png">

### 期待的正确结果

 应该提示执行完成

**Comment by ltfit** [comment]
下个版本优化下

**Comment by ltfit** [comment]
v1.20.8-lts已优化此问题
