### ISSUE TITLE
[BUG]  MQTT压力测试停不下来

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15076]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.7-LTS

### 使用外置数据库

否

### 问题描述

MQTT压力测试停不下来:
1、设置了自动停止，也不会停止；
2、页面报告一直处于running状态，且jmeter-master容器也一直处于运行中
3、需要手动停止才能停止成功

### 重现步骤

1、创建一个MQTT场景，调试通过之后转化为压力测试
2、上传对应的1.2.4版本的插件包
3、设置压力参数，运行

### 附加信息

1、设置的压力参数：
![image](https://user-images.githubusercontent.com/32027713/174534870-d20a6b29-e4e4-4eb3-95a1-a07e9318dfd8.png)

![image](https://user-images.githubusercontent.com/32027713/174534912-8f01b093-80f1-47b1-a817-cb2980ec1a2f.png)

2、运行过程：
运行到16秒时，就卡住了：
![image](https://user-images.githubusercontent.com/32027713/174535003-2a8e976c-6891-4a96-8099-7b8ee5156d40.png)

3、jmeter容器
![image](https://user-images.githubusercontent.com/32027713/174535174-26fa2cc6-6041-42b9-abf6-8069a7e6f8ac.png)

**Comment by sageonedream** [comment]
在页面上无法进行手动停止操作：
1.在测试报告页面无法点击立即停止按钮；
2.任务中心立即停止点击报错，无法生效；
![b3f165430d4c71def7e095caa208e57](https://user-images.githubusercontent.com/92150453/174535901-823ae272-bc3f-410c-8162-a08fcc1187d5.png)

**Comment by dashenyucainiao** [comment]
暂时先关闭
