### ISSUE TITLE
[BUG]连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by linda0007** [metersphere/metersphere#15077]
### 联系方式

微信：xyl1262486659  邮箱：xieyl01@mingyuanyun.com

### MeterSphere 版本

v1.20.3-lts-b3

### 使用外置数据库

是

### 问题描述

配置环境，进行数据库配置，数据库连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required，具体查看附件图片

### 重现步骤

配置环境，进行数据库配置，数据库连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required

### 期待的正确结果

配置环境，进行数据库配置，数据库连接主机名=dproxy.in.myspacex.cn时，连接成功

### 附加信息

![image](https://user-images.githubusercontent.com/20278174/174535270-daf31216-8620-48b7-a97c-0ce4a223efb6.png)

**Comment by xulinde** [comment]
看报错像是mysql版本不兼容，我们支持的mysql版本是8.0.16

**Comment by linda0007** [comment]
支持mysql版本8.0.16和以下的版本吗，目前mysql版本是5.6



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月20日(周一) 下午3:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required (Issue #15077)




 
看报错像是mysql版本不兼容，我们支持的mysql版本是8.0.16

**Comment by xulinde** [comment]
> 目前

不支持

**Comment by xulinde** [comment]
> 支持mysql版本8.0.16和以下的版本吗，目前mysql版本是5.6
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月20日(周一) 下午3:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [metersphere/metersphere] [BUG]连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required (Issue #15077) 看报错像是mysql版本不兼容，我们支持的mysql版本是8.0.16 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不支持哦

**Comment by linda0007** [comment]
那是支持mysql版本8.0.16和8.0.16以上的版本吗？

**Comment by linda0007** [comment]
而且相同的mysql版本，使用主机名=ywy-test-mysql-external.myysq.com.cn 就可以正常使用，使用代理的主机名：dproxy.in.myspacex.cn就连接数据库失败 。但是不管是哪种主机名，通过Navicat都可以正常连接成功。
麻烦帮忙处理一下这个问题，公司安全升级，统一使用代理的主机名进行连接数据库，如果ms无法支持，接口自动化就无法开展了
