### ISSUE TITLE
[BUG][接口定义]导入swaggerjson时，如果参数为object[]类型时无法导入参数

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1508]
**MeterSphere 版本**
V1.7.3

**Bug 描述**
导入swaggerjson时，如果参数为object[]类型时无法导入参数

**Bug 重现步骤**
1.  在yapi系统中创建接口文档
2. 以swaggerjson方式导出接口文档
3. 在metersphere的接口定义模块中导入该文件
4. 若接口中参数类型为object[]时，无法导入该参数

**期待的正确结果**
支持该参数类型导入

![image](https://user-images.githubusercontent.com/77767149/109120533-09924700-7781-11eb-82bb-2ad5127d0443.png)

**Comment by xulinde** [comment]
您好，是否方便提供下swagger文件
