### ISSUE TITLE
[BUG]并行处理器插件在页面保存再另打开后，会自动带出场景断言组件，功能实现有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15083]
### MeterSphere 版本

1.20.5lts

### 使用外置数据库

否

### 问题描述

并行处理器插件在页面保存再另打开后，会自动带出场景断言组件，功能实现有误，请修改

### 重现步骤

在接口自动化中添加并行控制器，并将需要的请求拖拽至并行控制器下，保存场景用例，关闭页面后重现打开，查看各请求步骤显示是否正确；

### 期待的正确结果

显示正确

### 相关日志输出

```shell
实际结果：
并行控制器下多出冗余的：场景断言步骤。
```

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/174538610-5e11b64c-d932-42cc-a45c-5b6f6cc3145d.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.8已修复，建议您升级
