### ISSUE TITLE
[BUG] text/json 请求体中 无法获取预脚本中的变量

### ISSUE THREAD

**Issue by git-yueyi** [metersphere/metersphere#1509]
**MeterSphere 版本**
v1.7

**Bug 描述**
1.在预脚本中执行如下脚本 
2.在text/json 中无法获取"${sign}"字段
```
import org.apache.jmeter.config.Arguments;
String value  = sampler.getArguments().getArgument(0).getValue();
log.info("value:"+value);
vars.put("sign","11sss");
```

**Bug 重现步骤**
1.  在预脚本中执行如下脚本 
```
import org.apache.jmeter.config.Arguments;
String value  = sampler.getArguments().getArgument(0).getValue();
log.info("value:"+value);
//模拟签名
vars.put("sign","ABCD");
```
2. 在text/json 中无法获取"${sign}"字段：
{“data”:“1000001”,"sign":"${sign}"}

**期待的正确结果**
正常应该 在发送的请求体内，将${sign}替换为预脚本的变量值：ABCD
{“data”:“1000001”,"sign":"ABCD"}

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/8520881/109120750-4eb67900-7781-11eb-8cee-e9b16f067651.png)
![image](https://user-images.githubusercontent.com/8520881/109120814-6261df80-7781-11eb-86e0-fdbab8684659.png)
![image](https://user-images.githubusercontent.com/8520881/109120838-6db50b00-7781-11eb-92e6-745d7b7e954a.png)

**Comment by xulinde** [comment]
问题复现，下个版本修复

**Comment by xulinde** [comment]
可能是脚本报错了，控制台这里有报错日志吗
![image](https://user-images.githubusercontent.com/64065190/109259157-977c3980-7836-11eb-9cb1-f30d69146afb.png)
