### ISSUE TITLE
[BUG][接口用例]接口定义中测试用例数不一致

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1510]
**MeterSphere 版本**
V1.7.3

**Bug 描述**
接口定义中测试用例数不一致

**Bug 重现步骤**
1.  创建一个接口定义
2. 为接口创建若干测试用例
3. 接口列表中显示的用例数与页面下方的测试用例数不一致

**期待的正确结果**
测试用例数保持一致

![image](https://user-images.githubusercontent.com/77767149/109128022-051e5c00-778a-11eb-9b9a-2031193f2ded.png)

**Comment by xulinde** [comment]
没有复现呢，有什么必现步骤吗，请详细描述下
![image](https://user-images.githubusercontent.com/64065190/109130307-8a0a7500-778c-11eb-9029-66905dc1f4d9.png)
