### ISSUE TITLE
【测试计划 - 失败】的【任务通知】接收人设置无效，实际接收的人是"最后保存修改【测试计划】的人”

### ISSUE THREAD

**Issue by luck-dyl** [metersphere/metersphere#15103]
### 联系方式

luckydengyalong@wghl.wecom.work

### MeterSphere 版本

版本:   v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

【测试计划 - 失败】的【任务通知】接收人设置无效，实际接收的人是"最后保存修改【测试计划】的人”

### 重现步骤

![image](https://user-images.githubusercontent.com/58102925/174558140-a37d4eca-cb9c-42d6-ae57-cc2daa8c3b8d.png)
1、小白登录》创建测试计划（失败时）》设置定时》通知任务》 接收人：小明

### 期待的正确结果

1、小明收到 “测试计划执行失败”的任务通知

【实际结果】： 小白收到了““测试计划执行失败”的任务通知”。 ？？？what? 前面才提了个bug, 修复完直接又送一个。 额， 这个 @@！！

### 附加信息

![image](https://user-images.githubusercontent.com/58102925/174558316-e78a5142-2f85-4536-a098-b92bf519ad53.png)

**Comment by ltfit** [comment]
你好 这个是xx完成了执行的测试计划 ，xx指的是执行人 ；在个人信息页面配置上企业微信的手机号就可以@接受人了
<img width="989" alt="image" src="https://user-images.githubusercontent.com/99794211/174577320-8b26dd5e-4a2d-4fa5-825f-1510c5eb2459.png">
