### ISSUE TITLE
[BUG][企业客户] 使用json schema后json丢失

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#15118]
### MeterSphere 版本

1.20.7

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/174584412-4a85665c-97f7-498e-9a6c-b30117f5bab6.png)

### 重现步骤

写好报文，切换到json-schema模式，丢失报文

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您的json字符串是什么呢？
![image](https://user-images.githubusercontent.com/73461316/174770306-12963a3a-6d01-4aef-b167-c9cab5353d74.png)

**Comment by sac911** [comment]
和json内容无关，贴如json，然后手工切换到JSON-SCHEMA，就会清空。

**Comment by zyyfit** [comment]
> 和json内容无关，贴如json，然后手工切换到JSON-SCHEMA，就会清空。
我这边没有复现

https://user-images.githubusercontent.com/73461316/176400916-880aff84-c350-48ef-816e-85e7932d04ce.mov
