### ISSUE TITLE
[FEATURE]接口测试结果应以断言是否通过判断

### ISSUE THREAD

**Issue by gq-guo** [metersphere/metersphere#1511]
**请描述您的需求或者改进建议.**
现在进行接口测试时，如通过id查询数据
当测试id值为错误数据，资源不存在，接口应该返回404，断言验证响应码为404，那么该结果符合预期，测试结果应该是通过
现在当结果为4**，5**时，测试用例执行结果为失败，不合理

**请描述你建议的实现方案**
应以每条测试用例的断言结果来判断该条用例的执行结果

**Comment by xulinde** [comment]
这种场景您可以设置断言忽略状态，则执行结果会根据断言来判断
![image](https://user-images.githubusercontent.com/64065190/109130988-4c5a1c00-778d-11eb-8ebd-390db98803ab.png)
