### ISSUE TITLE
[数据库配置]配置sqlserver 链接报错

### ISSUE THREAD

**Issue by zihui1** [metersphere/metersphere#15139]
### 联系方式

602208333@qq.com

### MeterSphere 版本

版本:   v1.20.4-lts

### 使用外置数据库

否

### 问题描述

配好sqlserver数据库后点击校验报错，从版本v1.20.3之后一直存在此问题。
如下图：

![image](https://user-images.githubusercontent.com/31397092/174702529-6ac8c865-e334-4926-974d-586eb5984f29.png)

### 重现步骤

1.配置sqlserver数据库
2.点击校验

### 期待的正确结果

正常链接

**Comment by zrfit** [comment]
v1.20.8-lts已修复。
