### ISSUE TITLE
[BUG]UI自动化断言期望值不能识别变量，接口自动化是可以的

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#15136]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

否

### 问题描述

UI自动化断言的期望值填写变量，不能识别，接口自动化是可以使用变量的
<img width="575" alt="c46c624b2ec16f23c5a271312be9835" src="https://user-images.githubusercontent.com/88763608/174701479-62a70000-2fa4-404f-bfe4-b0cace514eee.png">

### 重现步骤

1.创建UI自动化场景，在后置操作中使用断言期望值
2.期望值中引用变量
<img width="915" alt="05b0d4dd298ff6dea1468cfcaa33bc9" src="https://user-images.githubusercontent.com/88763608/174702096-64494c4f-8f5c-4067-991a-7edfd8bf0d71.png">

3.执行测试
4.结果没用把变量转换成值
![image](https://user-images.githubusercontent.com/88763608/174702612-4d9f77e5-b02a-435c-8ccd-dfbbd3db9e99.png)

### 期待的正确结果

跟接口自动化一致

**Comment by zrfit** [comment]
已经和林峰沟通，使用问题，断言是可以引用环境变量的，通过断言值进行断言的时候，变量名称必须填写该场景下正确且存在的变量名称，断言值再通过${变量名}进行引用，是可以断言成功的。
