### ISSUE TITLE
[FEATURE]测试跟踪-功能用例

### ISSUE THREAD

**Issue by solicitous1106** [metersphere/metersphere#15141]
### MeterSphere 版本

v1.19.1-4fb56789

### 请描述您的需求或者改进建议

在编写用例的时候能不能对比较关键的词或者句子做加粗或者变色或者字体的编辑，之后在评审的时候可以显示之后以防错过。
现在文本类型看似可以，但是实际使用并不方便，而且代码那边不可编辑，要取消标题也不知道要怎么点（用的谷歌最新版本浏览器）

### 附加信息

![Uploading image.png…]()

**Comment by luty2018** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/36292514/174727539-9264bfbb-b37f-4297-9407-24cb692de8fe.png">
目前可以实现你要的效果
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/36292514/174727674-d4397e18-44cb-457a-81f8-8ab635dda94d.png">
编辑的时候打开预览模式

**Comment by solicitous1106** [comment]
![image](https://user-images.githubusercontent.com/19722721/174773206-43a2319f-b54f-4c00-98b3-946515d88d11.png)
![image](https://user-images.githubusercontent.com/19722721/174773319-b51cc9b4-cd09-43c4-b701-604a6efde8dd.png)
额是什么关键字触发了变粗的状态呀~
