### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by solicitous1106** [metersphere/metersphere#15155]
### 请描述您的问题

怎么体现关联用例是要并且还是或的关系？目前似乎都是单个的关联~但是有时候是要多个用例都满足了才能执行下面那个应该要怎么操作体现呢

**Comment by luty2018** [comment]
目前关联用例只是一个标记的作业，代表这个功能用例有相关联的自动化或性能用例，你可以把你的想法描述清楚提需求过来。

**Comment by solicitous1106** [comment]
比如：一个会议，你约成功一个需求评审的会议人们接受这个会议且这个人在会议有效的时间内认证参加了这个会议，和你约成功一个用例评审的会议人们接受这个会议且这个人在回忆有效的时间内认证参加了这个会议，都后续是对会议本身的用例。都是会议本身用例的前置入口不是，满足任何一个他都能开展会议……有的比如我要满足前端提测且后端提测才能做整个项目的功能测试他需要同时满足2个，才可以进入测试的入口开展测试……大概就是这个意思。现在似乎这个标记没有标记是并且还是或者的
