### ISSUE TITLE
[BUG]MQTT在订阅消息时，手动停止任务，后台仍能接收到订阅

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15158]
### MeterSphere 版本

1.20.7lts

### 使用外置数据库

否

### 问题描述

MQTT在订阅消息时，手动停止任务，后台仍能接收到订阅

### 重现步骤

1.MQTT接口自动化，添加：建立MQTT连接，sub组件获取订阅，MQTT断开连接3个步骤；
2.设置sub订阅超时时间在60S左右，在执行场景测试时手动停止任务，并通过MQTT后台继续发布消息，查看ms-server能否继续接受消息；

### 期待的正确结果

2.在手动停止任务后，ms-server后台无法继续接收该任务下的MQTT发布的消息；

### 相关日志输出

```shell
实际结果：
ms-server后台仍能继续订阅到MQTT发布的消息
(详细操作步骤可查看录制视频)
```

### 附加信息

-----视频链接-----
链接：https://pan.baidu.com/s/19uLTLaCEqtuSmRNCrkRQqw?pwd=kc9w 
提取码：kc9w

**Comment by zrfit** [comment]
v1.20.9-lts已修复。

**Comment by sageonedream** [comment]
1.20.9lts版本未解决
