### ISSUE TITLE
[BUG]在Jenkins里触发，两个自动化场景在同时执行时，若果选择串行是可以执行成功的，若是选择并行就会报错，

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#15152]
### 联系方式

lisa.huang@fit2clou.com

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

在Jenkins中：
1、执行方式选择计划。此计划中直接关联附件中提供的自动化场景。（自动化脚本微信已发）
2、第一次运行：运行模式，选择串行是可以执行成功的
3、第二次运行：运行模式，修改为并行就会报错，

### 重现步骤

在Jenkins中：
1、执行方式选择计划。此计划中直接关联附件中提供的自动化场景。（自动化脚本微信已发）
2、第一次运行：运行模式，选择串行是可以执行成功的
3、第二次运行：运行模式，修改为并行就会报错，

### 相关日志输出
[H5主流程控制台输出报文.txt](https://github.com/metersphere/metersphere/files/8947783/H5.txt)

_No response_

**Comment by huangxine** [comment]
补充一下，是在Jenkins里触发的

**Comment by huangxine** [comment]
完整的日志文件
[Uploading MS_2022-06-23_18-30-35(1).log…]()

**Comment by ryanrain2016** [comment]
我感觉这个要考虑下你的场景是否支持并发，比如有几个场景涉及同一块功能的，并发会导致提取的值状态已改变什么的

**Comment by huangxine** [comment]
找了多个系统都无法复现，建议客户使用串行模式，后续会继续关注相关问题。
