### ISSUE TITLE
[BUG]循环控制器点击添加自定义请求，不是作为循环控制器的子类

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#1516]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.3-2b9713b1
**Bug 描述**
简要描述您碰到的问题
循环循环控制器点击添加自定义请求，不是作为循环编辑器的子类
**Bug 重现步骤**
1.  新增循环编辑器
2. 点击添加自定义请求

**期待的正确结果**
正确情况下应该是什么样的？
作为子类在循环控制器中展示
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/25195509/109247849-9d1a5500-781f-11eb-8d68-361ca3b60ddd.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本会修复

**Comment by xulinde** [comment]
v1.8已修复
