### ISSUE TITLE
[BUG]性能测试时接口读取csv不能按顺序读取

### ISSUE THREAD

**Issue by joyslxd** [metersphere/metersphere#15167]
### 联系方式

liuxiaodi@meifute.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

接口场景中添加csv作为获取token的场景变量，csv中包含4000个token;
该场景中压测的接口有重复请求限制，在10s内不能用同一个token请求超过一次；
性能测试中引用该场景；
压力下接口的返回时间在4s左右，我们准备4000个token预计可以在并发200的情况下持续20s请求不会token重复，再下一个20s的请求中就可以重复使用token请求该接口；
在jemter中上述场景按照预期请求没有报错，但在metersphere中错误率50%，错误原因为该接口10s内用同一token重复请求；

### 重现步骤

接口场景中添加csv作为获取token的场景变量，csv中包含4000个token;
该场景中压测的接口有重复请求限制，在10s内不能用同一个token请求超过一次；
性能测试中引用该场景；
错误率50%；

### 期待的正确结果

token的取值顺序是按照csv顺序进行

### 附加信息

![U

**Comment by zyyfit** [comment]
请问您选择的资源池是什么类型的呢？如果资源池有多个节点的话，需要重新考虑一下多个节点共用一套csv的问题
另外，我们最新版已经是1.20.7了，请升级使用最新版，我们修复问题的话，也是在后面的新版本修复的，不会在1.19版本修复了

**Comment by joyslxd** [comment]
> 

那多个节点有解决方案吗？单节点压力过大的话还是要用多节点的

**Comment by zyyfit** [comment]
> > 
> 
> 那多个节点有解决方案吗？单节点压力过大的话还是要用多节点的

那可以在性能测试的高级配置里，开启csv分割，然后多准备点测试数据
![image](https://user-images.githubusercontent.com/73461316/174778042-6d872134-439a-49db-82c7-be34209f97ab.png)

**Comment by zyyfit** [comment]
csv分割的时候，是有几个节点就把csv里的数据均分成几份，然后每个节点使用自己分到的那部分数据

**Comment by joyslxd** [comment]
> csv分割的时候，是有几个节点就把csv里的数据均分成几份，然后每个节点使用自己分到的那部分数据

多节点添加了高级配置csv分割，仍是出现相同问题；把资源池改为一个节点，也还是出现相同问题

**Comment by zyyfit** [comment]
> > csv分割的时候，是有几个节点就把csv里的数据均分成几份，然后每个节点使用自己分到的那部分数据
> 
> 多节点添加了高级配置csv分割，仍是出现相同问题；把资源池改为一个节点，也还是出现相同问题

那你升级一下版本吧，我用1.20.7测试没有出现这个问题

**Comment by zhangzhaox** [comment]
@joyslxd jmeter的原始csv元件不能保证 唯一性的取值，即时是仅执行一次也不是百分百，而且还由设置要求

**Comment by zhangzhaox** [comment]
https://github.com/LeeBaul/baolu-csv-data-file-config  该插件可满足唯一性取值要求
![image](https://user-images.githubusercontent.com/82088551/176861452-de5f8bd9-88e8-421d-a897-c070e6044549.png)
@joyslxd

**Comment by zhangzhaox** [comment]
@zyyfit 这不是MS平台的问题  倒是可以考虑是否进一步优化 且集成该插件https://github.com/LeeBaul/baolu-csv-data-file-config

**Comment by zyyfit** [comment]
> @zyyfit 这不是MS平台的问题 倒是可以考虑是否进一步优化 且集成该插件https://github.com/LeeBaul/baolu-csv-data-file-config

您好，暂时没有继承这个插件的计划
