### ISSUE TITLE
[BUG] 接口自动化场景-获取的接口参数，在不同接口下引用，部分接口可以引用成功，部分接口无法引用成功

### ISSUE THREAD

**Issue by zhangzjf** [metersphere/metersphere#15163]
### 联系方式

zjf1197559302@163.com

### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/66944035/174740036-f901bbb7-004c-452f-a834-2e4674c10973.png)
![image](https://user-images.githubusercontent.com/66944035/174740059-0d02115f-9115-49fa-b8c3-9c1311728849.png)

### 重现步骤

跨项目下关键接口自动化场景，使用接口A中的返回值，在b项目中可以成功引用，在a项目中无法获取到对应的返回值

### 期待的正确结果

可以正常引用成功，

**Comment by xulinde** [comment]
跟您确认下，是这样一个操作场景吗。我按以下操作未复现
1.提取A接口的返回值；
2.同项目a引用接口A的返回值，没有引用用
3.跨项目b引用接口A的返回值，可以引用到

**Comment by zhangzjf** [comment]
是这样的场景，我目前场景还是不行，在A项目中通过查询SQL提取到姓名身份证号，然后串联场景B项目引用提取的身份证号和姓名可以正常使用，在导入场景A项目，引用对应的姓名身份证号，发现不能提取成功











在 2022-06-22 11:10:29，"xulinde" ***@***.***> 写道：

跟您确认下，是这样一个操作场景吗。我按以下操作未复现
1.提取A接口的返回值；
2.同项目a引用接口A的返回值，没有引用用
3.跨项目b引用接口A的返回值，可以引用到

**Comment by zhangzjf** [comment]
在没有升级之前是可以正常使用，在版本升级后就不能这样使用了

**Comment by xulinde** [comment]
我这还是没复现，方便把你的场景导出来吗
