### ISSUE TITLE
[BUG]接口自动化测试报告中，没有显示条件控制器的请求

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#15189]
### MeterSphere 版本

 v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

自动化脚本中有条件控制器，执行过程中可以看到请求。但是执行结束后，在报告中，却完全看不到条件控制器的请求
执行中：
![image](https://user-images.githubusercontent.com/33340720/174930654-b9e58c44-bcab-4f31-b444-e94f184a993f.png)

报告：
![image](https://user-images.githubusercontent.com/33340720/174930773-fd160ac9-e0eb-4b90-9a99-b722ed3ab4d7.png)
脚本模版：
![image](https://user-images.githubusercontent.com/33340720/174930843-338e29b7-4f1d-437d-b15d-1c5ac2a01eb1.png)

### 重现步骤

循环设置while循环，设置条件控制器

**Comment by xulinde** [comment]
v1.20.8已修复，建议您升级
