### ISSUE TITLE
[FEATURE]UI自动化中有没有办法执行完某一个步骤程序休眠几秒钟的时间？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#15185]
### MeterSphere 版本

v1.20.7-lts

### 请描述您的需求或者改进建议

UI自动化中有没有办法执行完某一个步骤程序休眠几秒钟的时间？无论是通过代码或者页面步骤实现都可以

**Comment by Hyyfit** [comment]
您好，可以通过“后置脚本-->等待时间”，实现步骤后的休眠时间。
