### ISSUE TITLE
[BUG]关联禅道（v12.5.3）需求 保存功能用例后，提示bad request 400

### ISSUE THREAD

**Issue by Fit2CloundGhh** [metersphere/metersphere#15184]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.4-lts

### 使用外置数据库

否

### 问题描述

在功能用例详情界面，点击关联需求，并选中需要关联的需求，点击保存之后，提示 400 bad Request
![image](https://user-images.githubusercontent.com/92966838/174794837-4f116b21-00be-47a3-bcb5-d74d4492c6a7.png)

### 重现步骤

1.打开功能用例详情界面
2.点击关联需求，并选中需求（测试了任意选中一条）
3.右上角点击“保存”功能用例
4.提示报错

### 期待的正确结果

关联需求后，能够正常保存用例

### 相关日志输出

```shell
见附件截图
```

### 附加信息

![image](https://user-images.githubusercontent.com/92966838/174800917-475e329e-76b3-4b8a-b940-824e10ec22c4.png)

**Comment by AgAngle** [comment]
你好，整个日志可以发下吗 /opt/metersphere/logs/metersphere/info.log

**Comment by ltfit** [comment]
用户项目id 填错了
