### ISSUE TITLE
[BUG]缺陷管理中的缺陷状态无法进行筛选

### ISSUE THREAD

**Issue by panjunwei** [metersphere/metersphere#15186]
### MeterSphere 版本

v1.20.7-lts

### 使用外置数据库

否

### 问题描述

缺陷管理中的缺陷状态无法进行筛选,这个是一个很基本的功能，没有这个功能给使用人员无形中增加了很大的工作量，希望尽快修复这个功能

### 重现步骤

缺陷管理中的缺陷状态无法进行筛选,这个是一个很基本的功能，没有这个功能给使用人员无形中增加了很大的工作量，希望尽快修复这个功能

### 期待的正确结果

缺陷管理中的缺陷状态无法进行筛选,这个是一个很基本的功能，没有这个功能给使用人员无形中增加了很大的工作量，希望尽快修复这个功能

**Comment by luty2018** [comment]
已经优化了，2.0上
