### ISSUE TITLE
[BUG]升级后，beanshell脚本中，定义的字符串变量没初始化时，系统不能识别变量类型

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#15190]
### MeterSphere 版本

 v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

自动化测试脚本是在版本  v1.20.2 中编写 的。昨天升级到新版本后，执行报错。
======new trade begin !!!!!!
2022-06-22 10:35:20 INFO acf6acd9 1-1 trade date=T+1
2022-06-22 10:35:20 ERROR acf6acd9 1-1 Problem in JSR223 script trade date process, message: {}
Sourced file: inline evaluation of: ``import java.io.*; import java.util.*; import java.text.*;  log.info("======new t . . . '' : Undefined argument: vdDate  : at Line: 36 : in file: inline evaluation of: ``import java.io.*; import java.util.*; import java.text.*;  log.info("======new t . . . '' : ( "tradeDate" , vdDate ) 
 in inline evaluation of: ``import java.io.*; import java.util.*; import java.text.*;  log.info("======new t . . . '' at line number 36
检查发现，第36行是vars.put("tradeDate",vdDate);
而前面的定义是 String vdDate;
将定义改为String vdDate=“”;后，报错消失。

### 重现步骤

定义变量aa
执行如下代码，报错
String vdDate;
String xx=vars.get("aa");
if(xx.length()>1){
    vdDate=xx;
}else{
    vdDate="2";
}

log.info("vdDate="+vdDate);
vars.put("vdDate",vdDate);

控制台报错：
2022-06-22 10:48:04 INFO 9ec54862 1-1 Thread started: 9ec54862 1-1
2022-06-22 10:48:04 INFO 9ec54862 1-1 vdDate=void
2022-06-22 10:48:04 ERROR 9ec54862 1-1 Problem in JSR223 script test, message: {}
Sourced file: inline evaluation of: ``String vdDate; String xx=vars.get("aa"); if(xx.length()>1){     vdDate=xx; }else . . . '' : Undefined argument: vdDate  : at Line: 10 : in file: inline evaluation of: ``String vdDate; String xx=vars.get("aa"); if(xx.length()>1){     vdDate=xx; }else . . . '' : ( "vdDate" , vdDate ) 
 in inline evaluation of: ``String vdDate; String xx=vars.get("aa"); if(xx.length()>1){     vdDate=xx; }else . . . '' at line number 10
javax.script.ScriptException

初始化改为String vdDate="";
再次执行，则无报错，一切正常了。

### 期待的正确结果

String vdDate;已经指明了类型，无需一定要初始化一个值。

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
您好，这个是因为之前用的jdk8，后来升级jdk11后，不支持这样写了，需要初始化一下变量
