### ISSUE TITLE
[BUG]接口定义中的API删除、更新操作后，没有站内通知(配置过)

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#15191]
### 联系方式

交流群37群，健康

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

1、配置好了接口定义，API更新、删除会进行一个站内通知；配置如下图：
<img width="1435" alt="bug-01" src="https://user-images.githubusercontent.com/39123539/174934232-46506545-ba52-4b9e-91de-db21790a9f55.png">
2、进行删除接口定义API操作
<img width="1439" alt="bug-02" src="https://user-images.githubusercontent.com/39123539/174934302-ccfadb00-90ac-42e3-b315-236f91b2469c.png">
3、提示删除成功；但消息中心查看无任何通知
<img width="1439" alt="bug-03" src="https://user-images.githubusercontent.com/39123539/174934355-a7106690-f4f4-4227-b8c7-ed0a740f76b3.png">
<img width="1431" alt="bug-04" src="https://user-images.githubusercontent.com/39123539/174934369-9f317c33-a318-4616-8649-4cd7e00162cc.png">

### 重现步骤

参考问题描述即可重现

### 期待的正确结果

消息中心能看到通知信息

**Comment by zyyfit** [comment]
您好，如果操作人是自己，消息通知人也是自己，是不会发送站内信的
