### ISSUE TITLE
[BUG] 持续使用下凭证超时被强制登出

### ISSUE THREAD

**Issue by stwater20** [metersphere/metersphere#152]
**MeterSphere 版本**

v1.0.3
**Bug 描述**

我在写测试用例时,写到一半跳出登入时间过期之类的讯息,被强制登出,还没存档的数据就遗失了,怎么还在使用的情况下还会计算凭证超时?

**Bug 重现步骤**
1.  在测试跟踪撰写测试用例
2. 三十分钟内皆在操作该软体
3. 凭证超时被强制登出

**期待的正确结果**
仍然在操作时不该计算待机时间

**截图**
数据就不见了
但在交流群有对话

Ryan Chen:

我在写测试用例时,写到一半跳出登入时间过期之类的讯息,被强制登出,还没存档的数据就遗失了,怎么还在使用的情况下还会计算凭证超时?

涛声依旧:
bug

Ryan Chen:
那请问目前来说,登入后几分钟会被强制登出?

罗婷:
半小时

罗婷:
这里我们改一下

**Comment by wangzhen-fit2cloud** [comment]
你好，目前的超时机制还是以首次登录时间为基准，在 v1.1.0 版本中我们增加了 session.timeout 配置参数，并且默认配置了两小时的超时时间，你可以根据自己的需求修改下这个参数。
超时时间根据有无操作来判断考虑在后续版本提供。
