### ISSUE TITLE
[BUG]接口自动化，将JSON串里面的id值提取为数组，使用循环控制器foreach遍历无法进入循环

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#15204]
### MeterSphere 版本

  v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

接口自动化，将JSON串里面的id值提取为数组，使用循环控制器foreach遍历无法进入循环

### 重现步骤

1、接口A返回json串；需要提取成数组
![image](https://user-images.githubusercontent.com/43202800/174965746-c5de1f5e-a69d-47df-a0e6-224447ac41aa.png)

2、代码处理后，将数组放入循环控制器，实际无法进入循环

<img width="951" alt="获取json串的id,转成数组" src="https://user-images.githubusercontent.com/43202800/174965958-647dd90b-7ac4-4954-9ee5-b586c59f2321.png">
<img width="695" alt="11" src="https://user-images.githubusercontent.com/43202800/174966024-2ecb3dcb-24a7-4eb9-8b96-27ec209e3446.png">

3、${lt_1}也取不到数据

### 期待的正确结果

数组数据 应该可以进入循环，正常取数据

**Comment by xulinde** [comment]
确认下，i是您循环中的请求变量名吗

**Comment by xhy12** [comment]
是的，改成我定义场景变量的列表就能跑，提取的列表跑不起来

**Comment by xhy12** [comment]
您是用的脚本提取的方式么？

**Comment by xulinde** [comment]
好的，我们再看下～

**Comment by xulinde** [comment]
和研发沟通，回复：“暂不支持这种用法，目前我们用的测试引擎Jmeter 不支持这种用法”

**Comment by xhy12** [comment]
那如果需要提取json为数组 遍历循环应该怎么处理呢
