### ISSUE TITLE
[FEATURE]建议增加JDBC前后置脚本

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1520]
**请描述您的需求或者改进建议.**
因为有些断言的期望结果需要查询数据库，所以期望能够加上JDBC前后置脚本

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
脚本类型断言，可以对数据库结果进行断言。是否能满足您需求

**Comment by xulinde** [comment]
目前sql类型请求，是可以添加前后置脚本的
