### ISSUE TITLE
[BUG]有时候出现接口访问timeout的情况，造成测试计划一直处于running的状态

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#15208]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.7-lts

### 使用外置数据库

否

### 问题描述

有时候出现接口访问timeout的情况，造成测试计划一直处于running的状态
![微信截图_20220620061653](https://user-images.githubusercontent.com/38156471/174984608-aa0a51d8-89fe-4382-a7c2-8847b49d4585.png)
![微信截图_20220620061729](https://user-images.githubusercontent.com/38156471/174984618-7aa375dc-78af-45f3-9952-05cb31ce653f.png)
[日志.zip](https://github.com/metersphere/metersphere/files/8955973/default.zip)

### 重现步骤

有时候出现接口访问timeout的情况，造成测试计划一直处于running的状态
![微信截图_20220620061653](https://user-images.githubusercontent.com/38156471/174984608-aa0a51d8-89fe-4382-a7c2-8847b49d4585.png)
![微信截图_20220620061729](https://user-images.githubusercontent.com/38156471/174984618-7aa375dc-78af-45f3-9952-05cb31ce653f.png)
[日志.zip](https://github.com/metersphere/metersphere/files/8955973/default.zip)

**Comment by zyyfit** [comment]
您好，看日志里，是执行的时候重启了服务，导致的测试报告一直是running状态，正常执行是不会一直running的超时的请求状态也不是time out。
日志里还显示redis连接超时了，不知道是哪里的redis，可以排查一下

**Comment by YellCatt** [comment]
> 您好，看日志里，是执行的时候重启了服务，导致的测试报告一直是running状态，正常执行是不会一直running的超时的请求状态也不是time out。 日志里还显示redis连接超时了，不知道是哪里的redis，可以排查一下

redis肯定是本机的，不清楚为什么会重启服务，资源不够吗？我就一个人使用啊，弄了一个定时任务，串行，290个测试用例

**Comment by YellCatt** [comment]
> 您好，看日志里，是执行的时候重启了服务，导致的测试报告一直是running状态，正常执行是不会一直running的超时的请求状态也不是time out。
> 日志里还显示redis连接超时了，不知道是哪里的redis，可以排查一下

集中发生在接口测试定时任务中，手动启动测试计划一般不会出现这个问题

**Comment by zyyfit** [comment]
好的，我们排查一下

**Comment by zyyfit** [comment]
您好，1.20.10版本对着这个问题做了优化，您最近再观察一下，看看还会不会出现

**Comment by YellCatt** [comment]
> 您好，1.20.10版本对着这个问题做了优化，您最近再观察一下，看看还会不会出现

还是依旧有timeout的情况发生

**Comment by YellCatt** [comment]
[日志.zip](https://github.com/metersphere/metersphere/files/9127619/default.zip)

**Comment by zyyfit** [comment]
好的，我们再看看

**Comment by GGBond-CN** [comment]
ms平台还是挺好的，虽然有些小的问题需要慢慢改进；这个问题我们也遇到了，请问这个在哪个版本里面修好了吗，如果timeout的话，还有一个问题就是重试会让当前的case 出来几百条执行记录

**Comment by zyyfit** [comment]
> ms平台还是挺好的，虽然有些小的问题需要慢慢改进；这个问题我们也遇到了，请问这个在哪个版本里面修好了吗，如果timeout的话，还有一个问题就是重试会让当前的case 出来几百条执行记录

这个问题可以新提一个issue详细描述一下吗？

**Comment by zyyfit** [comment]
这个问题我用我们部署的ms系统执行你的接口，选择的local资源池，可以正常执行了，然后不选资源池的时候是有问题的，不过这个问题暂时不好处理，等后期有时间的时候再做优化，可以先用资源池执行，如果资源池执行也有问题的话，可以单独部署一个机器作为资源池，或者ms机器上不要运行太多其他软件，保证系统执行所需的资源
