### ISSUE TITLE
[FEATURE]建议定义一个菜单专门定义标签，所有case中不能输入标签只能选已有标签

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1521]
MeterSphere V1.7

当前状态：接口测试-接口自动化，编辑具体case时，可以写入多个标签名字。

建议： 专门定义一个系统级的菜单，用来定义所有标签。在编辑具体case时，只能选择一个或者多个已有的标签

理由： 标签最后会作为关键字来拉取相关的用例，目前在用例中随意手动填写，可能会出现笔误、写错字的情况，写错了还非常难发现。比如如果把“主页上按钮”写成“主页上的按钮”，就变成了两个标签了，而且还很难发现。

**Comment by xulinde** [comment]
感谢反馈，我们先内部讨论下。
