### ISSUE TITLE
[BUG]连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required 

### ISSUE THREAD

**Issue by linda0007** [metersphere/metersphere#15213]
### 联系方式

微信：xyl1262486659  邮箱：xieyl01@mingyuanyun.com

### MeterSphere 版本

v1.20.3-lts-b3

### 使用外置数据库

是

### 问题描述

相同的mysql版本5.6，使用主机名=ywy-test-mysql-external.myysq.com.cn 就可以正常使用，使用代理的主机名：dproxy.in.myspacex.cn就连接数据库失败 。但是不管是哪种主机名，通过Navicat都可以正常连接成功。
麻烦帮忙处理一下这个问题，公司安全升级，统一使用代理的主机名进行连接数据库，如果ms无法支持，接口自动化就无法开展了

### 重现步骤

配置环境，进行数据库配置，数据库连接主机名=dproxy.in.myspacex.cn时，数据库报错：CLIENT_PLUGIN_AUTH is required

### 期待的正确结果

配置环境，进行数据库配置，数据库连接主机名=dproxy.in.myspacex.cn时，连接成功

### 附加信息

![image](https://user-images.githubusercontent.com/20278174/174990117-dcab6743-5657-43e4-af2d-c34f04202151.png)

**Comment by xulinde** [comment]
您好，您可以扫码进入我们用户交流群，找我们同事远程协助您解决
![image](https://user-images.githubusercontent.com/64065190/174997400-3edcefbf-ad27-41b7-8207-d84153ce76b7.png)
