### ISSUE TITLE
[BUG]场景用例中设置了一分钟的等待控制器，结果整个场景用例跑下来需要半个小时

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#15230]
### 联系方式

768305875@qq.com

### MeterSphere 版本

v1.20.7-lts

### 使用外置数据库

否

### 问题描述

场景用例中设置了一分钟的等待控制器，结果整个场景用例跑下来需要半个小时
![49573e7fd632ba96458f701194c2722](https://user-images.githubusercontent.com/38156471/175057905-23e64ef7-2cde-4005-a44e-70d6963d10be.png)
![caf54fd54c7108a8c0ac6860b42125d](https://user-images.githubusercontent.com/38156471/175057920-1b2d966e-8669-4859-9aa9-74a117f132c4.png)
[日志.zip](https://github.com/metersphere/metersphere/files/8958712/default.zip)

### 重现步骤

场景用例中设置了一分钟的等待控制器，结果整个场景用例跑下来需要半个小时
![49573e7fd632ba96458f701194c2722](https://user-images.githubusercontent.com/38156471/175057905-23e64ef7-2cde-4005-a44e-70d6963d10be.png)
![caf54fd54c7108a8c0ac6860b42125d](https://user-images.githubusercontent.com/38156471/175057920-1b2d966e-8669-4859-9aa9-74a117f132c4.png)
[日志.zip](https://github.com/metersphere/metersphere/files/8958712/default.zip)

### 期待的正确结果

只等待1分10秒

### 相关日志输出

```shell
11
```

### 附加信息

11

**Comment by xulinde** [comment]
您好，场景中的等待控制器是全局的，添加后，对每个请求都生效，如果您想给单个用例设置等待控制器，可以通过如下方式添加
<img width="845" alt="image" src="https://user-images.githubusercontent.com/64065190/175190875-dff7df15-a36c-4d72-b505-68f232d6b5a7.png">
