### ISSUE TITLE
[BUG]循环控制器中循环设置环境变量取值问题

### ISSUE THREAD

**Issue by feng2076** [metersphere/metersphere#1523]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.3-2b9713b1
**Bug 描述**
简要描述您碰到的问题
循环控制器中循环设置环境变量如a_0,a_1,a_2，在自定义脚本中获取第二个变量a_1取值为空，如果按照a_2,a_3,a_4定义就能正确的获取第二个变量a_3的值
**Bug 重现步骤**
1.  新增一个场景变量num，初始值为0
2. 新增循环控制器，循环3次,num++;
3. 每次循环赋值变量a_${num}
4. 新增一个自定义脚本控制器获取a_0,a_1,a_2的值

**期待的正确结果**
正确情况下应该是什么样的？
正常获取到值，而不是null
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/25195509/109268670-5f7cf280-7846-11eb-9ec2-cb92fb550c3f.png)
![image](https://user-images.githubusercontent.com/25195509/109268677-61df4c80-7846-11eb-8d9e-7ecd92d59967.png)
![image](https://user-images.githubusercontent.com/25195509/109268682-6441a680-7846-11eb-80c3-b92d1af2acc2.png)
![image](https://user-images.githubusercontent.com/25195509/109268696-67d52d80-7846-11eb-8e32-d002591a7b7b.png)

**Comment by xulinde** [comment]
收到，我们复现后再反馈
