### ISSUE TITLE
[BUG] swagger导入之后，只有最后一个tag中有接口，其余的都被放到了未分配接口tag中

### ISSUE THREAD

**Issue by 1023277973** [metersphere/metersphere#15239]
### 联系方式

jht9866@sina.cn

### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

接口定义->导入->选择swagger 上传json文件，导入成功之后只有json中最后一个tag中有接口，其余的都在未规划接口中。
![image](https://user-images.githubusercontent.com/50948975/175220200-4a5aba9b-b562-4998-8e4a-4b1c0ab2ed88.png)

### 重现步骤

1.新建项目
2.进入项目，在左上角更多操作中点击导入
3.在导入窗口中选择swagger，并上传文件，然后点击保存。（上传的swagger文件如下）、
[swagger.pdf](https://github.com/metersphere/metersphere/files/8964190/swagger.pdf)

### 期待的正确结果

能够正确的将接口放到对应的tag，类似下图意思
![image](https://user-images.githubusercontent.com/50948975/175220709-ca0c9295-434a-4386-b15f-b8460339c841.png)

**Comment by zyyfit** [comment]
已知问题，后续版本优化

**Comment by zyyfit** [comment]
1.20.10已修复
