### ISSUE TITLE
脑图模式下评审用例时，插入的说明或者评审结果，保存后结果丢失[BUG]对工作过程中造成很大的效率困扰，非常影响它的推广

### ISSUE THREAD

**Issue by Yo00Yo** [metersphere/metersphere#15236]
### 联系方式

huangyuanbo914@163.com

### MeterSphere 版本

v1.20.5-lts

### 使用外置数据库

否

### 问题描述

以脑图模式下进行用例评审，插入评审时的内容或者标上审核结果，保存后，再次进来结果 丢失

### 重现步骤

以脑图模式下进行用例评审，插入分支主题，输入相关描述
或者 对用例步骤 进行标上审核结果 。保存后，再次进来查查
实际结果 ：内容丢失

### 期待的正确结果

内容保存正常

### 附加信息

第一个视频 是编写用例过程中，操作步骤丢失问题：
https://user-images.githubusercontent.com/103110409/175194079-a18500e4-a25b-4c67-8552-6e12ada15728.mp4

第二个视频是 脑力模式下，输入内容及评审结果 丢失问题
https://user-images.githubusercontent.com/103110409/175194371-2086d933-e515-4979-89ef-1acd8dc24c59.mp4

**Comment by ltfit** [comment]
你好 这个用例评审这块只是 用来评审的,插入的数据目前是不支持的；需要在功能用例那边编辑好关联到这块

**Comment by Yo00Yo** [comment]
> 你好 这个用例评审这块只是用来评审的,插入的数据目前是不支持的；需要在功能用例那边编辑好关联到这块

请看视频中，它是支持插入下级主题的，
两段视频中，总共有三个问题：
1、脑图模式下进行用例编写，保存操作步骤后会丢失操作步骤；
2、脑图模式下进行用例评审， 
     2.1：对操作步骤标志评审结果保存后，结果丢失；
     2.2：对用例进行插入评论或者说明，保存后也丢失；

**Comment by Yo00Yo** [comment]
且在你们的回复中，1.20.4版本已经支持该功能
![image](https://user-images.githubusercontent.com/103110409/175205583-5d8c14f9-dbb1-434f-a762-a9d73cdb51f7.png)

**Comment by ltfit** [comment]
> 且在你们的回复中，1.20.4版本已经支持该功能 ![image](https://user-images.githubusercontent.com/103110409/175205583-5d8c14f9-dbb1-434f-a762-a9d73cdb51f7.png)

这个是目前测试计划支持的 用例评审目前还不支持，这个应该是回复错了

**Comment by ltfit** [comment]
> > 你好 这个用例评审这块只是用来评审的,插入的数据目前是不支持的；需要在功能用例那边编辑好关联到这块
> 
> 请看视频中，它是支持插入下级主题的， 两段视频中，总共有三个问题： 1、脑图模式下进行用例编写，保存操作步骤后会丢失操作步骤； 2、脑图模式下进行用例评审， 2.1：对操作步骤标志评审结果保存后，结果丢失； 2.2：对用例进行插入评论或者说明，保存后也丢失；

第一个问题 我这边没有复现，你加下我微信我这边看下 13131900266；第2个问题，2.1 这个评审结果只是对用例进行评审，步骤目前不支持 ，2.2目前是不支持的，这些可以给产品提下；

**Comment by Hyyfit** [comment]
感谢反馈，待调研后设计。
