### ISSUE TITLE
[FEATURE]场景自动化可以勾选多个环境么

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#15244]
### MeterSphere 版本

1.20.6

### 请描述您的需求或者改进建议

场景自动化目前只能选择一个环境进行，能否改成多个环境执行

**Comment by Hyyfit** [comment]
您好，可以在多环境里执行。
如果场景自动化里的CASE是不同环境的，支持多环境允许。
<img width="387" alt="image" src="https://user-images.githubusercontent.com/95834771/175848982-5a04522f-551c-4d33-af03-4987a238721f.png">

如果是同一个CASE，在不同的环境中执行，可以通过测试计划或批量执行的方式，切换环境执行
