### ISSUE TITLE
相关组件错误，请问怎么解决呀，谢谢

### ISSUE THREAD

**Issue by xiahongyuan** [metersphere/metersphere#15243]
### 请描述您的问题

Unknown custom element: <relationship-graph-drawer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by xiahongyuan** [comment]
<relationship-graph-drawer>

**Comment by xiahongyuan** [comment]
relationship-graph-drawer

**Comment by xiahongyuan** [comment]
relationship-graph-drawer 提示这个组件，在项目里面找不到这个组件

**Comment by Hyyfit** [comment]
您好，您可以在我们的交流群内联系技术支持人员，可以远程帮您排查问题。
