### ISSUE TITLE
[BUG][企业用户] report下载时间太长，report的size太大

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#15249]
### MeterSphere 版本

1.20.7

### 使用外置数据库

是

### 问题描述

测试完毕后在report页面点击‘导出’，耗时200秒
![5f15c62aef525975d5bbac1ed13bebc](https://user-images.githubusercontent.com/103017812/175254836-453c8f21-9a8a-463d-a809-e2fac930f483.png)
另外report有17M大，需要瘦身，很多内部邮件无法发送原始报告，只能压缩。

### 重现步骤

测试完毕后在report页面点击‘导出’，耗时200秒

**Comment by ltfit** [comment]
你好 这块后续会优化下 已经排期

**Comment by youliyuan-fit2cloud** [comment]
该问题在较新版本中已优化，建议升级一下。
