### ISSUE TITLE
[FEATURE]metersphere用户可以独立配置jira账号

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#1524]
目前metersphere和jira集成的账号只有一个，所有测试人员只能通过一个jira账号去提交缺陷表单，建议能够设计成，每个metersphere用户能在平台上配置自己的个人jira账号，这样的话，提交缺陷表单后，在jira系统里的bug reporter就是提交账户的本人，而不是metersphere里集成的统一账号

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中

**Comment by guhan121** [comment]
@jakubik1986 如果jira的bug可以指定执行人就可以了

**Comment by t880216t** [comment]
@guhan121  @jakubik1986  看看能帮到你不。https://testerhome.com/topics/29702
