### ISSUE TITLE
[BUG]浏览器录制插件JMX导入接口定义，没有校验重复的url

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#15242]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

否

### 问题描述

1.用浏览器插件录制了接口，有重复的接口，导出为JMX
2.将jmx导入metersphere接口定义
3.发现有重复的，并且平台没有开启允许接口url重复
![image](https://user-images.githubusercontent.com/88763608/175239783-73a03eb9-ac95-48e8-b856-ac7303b7910b.png)

### 重现步骤

1.用浏览器插件录制了接口，有重复的接口，导出为JMX
2.将jmx导入metersphere接口定义
3.发现有重复的，并且平台没有开启允许接口url重复
![image](https://user-images.githubusercontent.com/88763608/175239783-73a03eb9-ac95-48e8-b856-ac7303b7910b.png)

### 期待的正确结果

应该正常校验重复

**Comment by linfengjjj** [comment]
[测试文件4.zip](https://github.com/metersphere/metersphere/files/8964977/4.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.10版本更新了导入规则，1.20.11做了优化补充，请升级后使用
