### ISSUE TITLE
条件判断 变量是list  报An error occurred while evaluating the expression

### ISSUE THREAD

**Issue by hejiong19860303** [metersphere/metersphere#1525]
**MeterSphere 版本**
1.7.3

**Bug 描述**

条件判断 变量是list  报An error occurred while evaluating the expression
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/49967806/109412026-c209f600-79e0-11eb-989c-1e1e4c2b72a5.png)
![image](https://user-images.githubusercontent.com/49967806/109412055-d3530280-79e0-11eb-8126-eaa72ce4193a.png)
.

**Comment by xulinde** [comment]
未复现该问题，请检查下设置条件控制器前，list变量提取成功了吗
