### ISSUE TITLE
批量编辑CASE不支持修改运行环境

### ISSUE THREAD

**Issue by windy0122** [metersphere/metersphere#15253]
### MeterSphere 版本

v1.19.0-1727df14

### 请描述您的需求或者改进建议

现在case批量编辑只支持修改用例等级，希望可以支持修改运行环境，不然一个一个的修改太麻烦了，

**Comment by Hyyfit** [comment]
感谢反馈，目前设计如此。
平台目前是支持切换环境运行。批量执行时，选择运行环境，会根据选择的环境执行。
