### ISSUE TITLE
[FEATURE]修复场景导入多出步骤问题引起的历史数据是否能够统一处理

### ISSUE THREAD

**Issue by yunkk0309** [metersphere/metersphere#15260]
### MeterSphere 版本

v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议

fix(接口测试): 修复场景导入多出步骤问题
该问题导致已创建的场景里多出步骤，保存、执行场景时失败报错，是否能够将已创建过场景里多出来的步骤进行统一删除处理？

**Comment by Hyyfit** [comment]
感谢反馈，这个数据处理不了。
可以重新导入，覆盖之前导入错误的那一批数据。
