### ISSUE TITLE
在当前项目下创建测试计划关联项目时，无法选择当前项目

### ISSUE THREAD

**Issue by Kevin-liutianping** [metersphere/metersphere#1526]
**MeterSphere 版本**
版本: v1.7.3

**Bug 描述**
在当前项目下创建测试计划关联项目时，无法选择当前项目，但是为空提交后，测试计划回显的关联项目又是当前项目

**Bug 重现步骤**
1.点击创建测试计划

**期待的正确结果**
在关联项目时，可以选择当前项目

**截图**
![image](https://user-images.githubusercontent.com/40854706/109413241-524b3980-79e7-11eb-95fe-25399264eb5f.png)

**Comment by youliyuan-fit2cloud** [comment]
您好，默认设置是已选择该项目~，确定之后看一下吧
