### ISSUE TITLE
[BUG]执行场景自动化过程中，停留在某个Case，提示“测试中”

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15269]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.6-lts

### 使用外置数据库

否

### 问题描述

- 执行场景自动化过程中（100个左右的case），停留在某个Case，提示“测试中”

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/92966838/175510466-349385b0-e559-4f17-85e3-71a833f50251.png">

- 查看jmeter-run-log发现线程池可用线程数资源不足
![image](https://user-images.githubusercontent.com/92966838/175510712-958008a2-9e60-4ca2-b465-b9e97756ffd9.png)

### 重现步骤

1、客户环境，正常的执行接口自动化
2、ms服务器为4C8G

### 期待的正确结果

线程池相关配置 是否可以自定义配置，并能够正常执行接口自动化

### 相关日志输出

```shell
见附件
```

### 附加信息

[info.log](https://github.com/metersphere/metersphere/files/8975239/info.log)
[ms-jmeter-run-log.log](https://github.com/metersphere/metersphere/files/8975241/ms-jmeter-run-log.log)

**Comment by youliyuan-fit2cloud** [comment]
请参考下这个链接自行排查下问题吧
https://wiki.fit2cloud.com/pages/viewpage.action?pageId=76715237
