### ISSUE TITLE
[BUG]关联禅道（12.5.3）需求，展示带有长文本的需求列表时，无法完整查看需求

### ISSUE THREAD

**Issue by Fit2CloundGhh** [metersphere/metersphere#15268]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.4-lts

### 使用外置数据库

否

### 问题描述

关联禅道需求，展示带有长文本的需求列表时，无法完整查看需求
![image](https://user-images.githubusercontent.com/92966838/175507573-8ad46d4e-e3ec-40d8-932d-65838a6d1715.png)
![image](https://user-images.githubusercontent.com/92966838/175507616-87634d3c-7003-471d-b60a-761a1d357df7.png)

### 重现步骤

1、维护好禅道配置（12.5.3）
2、在功能用例处点击关联需求
3、弹出的需求列表

### 期待的正确结果

正常展示需求列表

**Comment by ltfit** [comment]
你好 升级到最新版本已修复此问题

**Comment by Fit2CloundGhh** [comment]
好的 感谢
