### ISSUE TITLE
[BUG]jsonpath提取数值过长会自动转成科学计数法表示

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#15263]
### 联系方式

交流群32，健康

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

接口响应体中的一些参数值过长，使用jsonpath提取出来会自动转成科学计数法表示，而不是原数值

响应数据如下：
{
    "code": 1,
    "message": "success",
    "data": [
        {
            "yearNo": 2021,
            "quarterNo": null,
            "monthNo": null,
            "weekNo": null,
            "dayNo": null,
            "orderNum": 3590,
            "teuNum": null,
            "grossWeight": 5396530.000000,
            "volume": 90718761.200000,
            "chargeQty": 144718761.200000
        },
        {
            "yearNo": 2022,
            "quarterNo": null,
            "monthNo": null,
            "weekNo": null,
            "dayNo": null,
            "orderNum": 3650,
            "teuNum": 816,
            "grossWeight": 6814550.000000,
            "volume": 55503270.000000,
            "chargeQty": 55503270.000000
        },
        {
            "yearNo": 2023,
            "quarterNo": null,
            "monthNo": null,
            "weekNo": null,
            "dayNo": null,
            "orderNum": 3650,
            "teuNum": 802,
            "grossWeight": 8146800.000000,
            "volume": 63275130.000000,
            "chargeQty": 63275130.000000
        }
    ],
    "timestamp": 1656050215151,
    "executeTime": 40
}

使用jsonpath提取：
<img width="892" alt="jsonpath-01" src="https://user-images.githubusercontent.com/39123539/175487363-0089aee4-22fa-40d7-b7d0-0117a29d0916.png">

### 重现步骤

参考问题描述

### 期待的正确结果

展示原本的数值

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
您好，目前我们用的测试引擎是Jmeter ，Jmeter不支持这种用法
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/64065190/175898952-28bc9401-ce5b-4e68-80d0-d84596d0e958.png">
