### ISSUE TITLE
[BUG]创建缺陷时截至日期字段（日期选择器）传值错误

### ISSUE THREAD

**Issue by zihui1** [metersphere/metersphere#15267]
### 联系方式

602208333@qq.com

### MeterSphere 版本

版本:   v1.20.8-lts

### 使用外置数据库

否

### 问题描述

创建缺陷有配置截止日期字段，截止日期配置时间选择器错误
传值如下：
\"name\":\"截止日期\",\"value\":\"2022-06-23T16:00:00.000Z\",

### 重现步骤

缺陷管理创建缺陷选择日期选择器保存缺陷

### 期待的正确结果

禅道接口对接的字段：   截止日期 日期格式：YY-mm-dd，如：2019-01-01*必填

### 相关日志输出

```shell
{ "timestamp": 1656061041327, "status": 500, "error": "Internal Server Error", "path": "/issues/add" }
```

**Comment by zihui1** [comment]
日期时间选择器也有该问题

**Comment by ltfit** [comment]
你好 你是禅道那个版本呢 目前我们支持开源版12.5.3 最好用此版本，其他版本目前还未兼容

**Comment by zihui1** [comment]
对接得格式一直是这个啊， 现在我们传得是这种格式\"name\":\"截止日期\",\"value\":\"2022-06-23T16:00:00.000Z\",




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月24日(星期五) 晚上7:01
***@***.***&gt;;
抄送:&nbsp;"。王先生 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]创建缺陷时截至日期字段（日期选择器）传值错误 (Issue #15267)





 
你好 你是禅道那个版本呢 目前我们支持开源版12.5.3 最好用此版本，其他版本目前还未兼容

**Comment by ltfit** [comment]
2.0版本会兼容禅道16.0以上版本
