### ISSUE TITLE
[BUG]认证配置无法使用（Basic Auth）

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#1527]
**MeterSphere 版本**
1.7.1

**Bug 描述**
认证配置中，输入了正确的账密，接口依旧无法获取登录 token，并报错。
postman可使用。

**期待的正确结果**
认证登录成功，并返回 token

**截图**
![image](https://user-images.githubusercontent.com/6467295/109443534-b6dfb600-7a32-11eb-8c14-890a480fe8d1.png)

**Comment by xulinde** [comment]
未复现该问题，请再次检查下您的url以及basic auth的用户名密码是否正确
![image](https://user-images.githubusercontent.com/64065190/109485631-dfac8d80-7abc-11eb-8190-0c0060985e03.png)

**Comment by seasoncool** [comment]
@xulinde 
感谢您的回复。
我在微信群里面反应了该问题，得到 飞致云的同事【赵勇】的确认，确实有认证配置的问题，您能帮我与该同事确认下么？

**Comment by xulinde** [comment]
v1.8已修复
