### ISSUE TITLE
[BUG] 接口场景自动化调试问题

### ISSUE THREAD

**Issue by ryanrain2016** [metersphere/metersphere#15273]
### 联系方式

ryan@top365.ml

### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

是

### 问题描述

1. 接口场景自动化调试的时候，偶现（高频率）环境下拉框会转圈圈，特别是点了调试提示没有设置环境后
2. 有时候编辑了场景后保存，环境又变成了未设置的状态
3. 偶现后置脚本断言的脚本名不能修改，在输入框中敲键盘没有反应
4. 调试的时候不能执行环境中配置的全局的前置脚本，我要批量的设置一个头，每个都要手动加
5. 调试时有时候会卡住，需要手动停止或者刷新才能继续

### 重现步骤

1. 接口场景自动化调试的时候，偶现（高频率）环境下拉框会转圈圈，特别是点了调试提示没有设置环境后
2. 有时候编辑了场景后保存，环境又变成了未设置的状态
3. 偶现后置脚本断言的脚本名不能修改，在输入框中敲键盘没有反应
4. 调试的时候不能执行环境中配置的全局的前置脚本，我要批量的设置一个头，每个都要手动加
5. 调试时有时候会卡住，需要手动停止或者刷新才能继续

**Comment by zyyfit** [comment]
您好，下面这几个问题需要确认一下，
问题1、遇到过，不过转圈应该是加载慢，转圈之后环境列表就显示出来了，您是转圈之后也加载不出来吗？还是转圈之后能显示环境信息？
问题2、遇到过，没有找到复现步骤，您那边有复现步骤吗？
问题3、没复现，有复现步骤吗？
问题4、没复现，全局前置脚本是怎么配置的呢？是否配置了忽略请求？（忽略请求是指不执行的请求类型）
问题5、没复现，卡住的场景方便上传一下吗

**Comment by ryanrain2016** [comment]
问题1、转圈之后环境没有加载出来，请求已经返回但是控制台有报错：
chunk-common.7d5ad18e.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at a.init (chunk-common.7d5ad18e.js:1:4474)
    at a.open (chunk-common.7d5ad18e.js:1:5213)
    at a.openEnvSelect (chunk-common.7d5ad18e.js:1:12831)
    at chunk-d93598e2.ac56df77.js:2:137641
问题2、这个偶现，已知步骤： 
1. 进入接口自动化；
2. 进入场景编辑
3. 点击保存，点击调试，这时会提示没有环境了，再次点击保存 这是保存的就是没有环境的
问题3、没有再次遇到
问题4、是我理解的问题，我勾选了过滤HTTP请求，其实我是想要HTTP请求时生效
问题5、没有再次遇到

**Comment by ryanrain2016** [comment]
第一个问题我自己找到了，前端问题：这个文件 /frontend/src/business/components/api/automation/scenario/EnvSelect.vue   119行，多了一个斜杠
```this.$get('/project/getOwnerProjectIds/', res => {```
改为：
```this.$get('/project/getOwnerProjectIds', res => {```

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
第二个问题修复了，请等待1.20.10版本发布后验证
第一个问题开发说不是这里的原因，这里只是不太规范，先看看第二个问题修复后第一个问题还会不会出现吧

**Comment by zyyfit** [comment]
1.20.10已发布

**Comment by ryanrain2016** [comment]
问题1. 又遇到了，还是同样的问题：
/frontend/src/business/components/track/common/EnvSelect.vue  173行 还是有个斜杠，还是会触发
这里不是不规范的问题，可以给你对比：
这里是有斜杠的返回值：
![image](https://user-images.githubusercontent.com/22925589/179656310-7675b0ac-4d51-4fb4-94e3-d65a3c96cd2e.png)
这里是同一个请求没有斜杠的返回值：
![image](https://user-images.githubusercontent.com/22925589/179656608-1a534c51-fc89-49b8-a4f3-d4bdc47f8961.png)
给你们前端提个建议，这种调用api不应该写到一起，然后用的时候导入吗？这样改没完啊，并且下次写还是容易出错

**Comment by zyyfit** [comment]
> @zyyfit 这个是关了，不改了吗？
不好意思，没看到您的回复，已经被关闭的issue如果还有问题的话可以重新打开或者重新提交一个，在这里回复不容易被看到。
然后关于前端代码写法这个问题，是不修改的，而且我在ms部署服务器上请求，带不带斜杠都是很快返回的，并且浏览器devtools里查看也是没带斜杠的

![image](https://user-images.githubusercontent.com/73461316/181448442-8ce33f79-5e8c-4771-b6cb-3d5fadb2951b.png)

![image](https://user-images.githubusercontent.com/73461316/181448422-920bb23a-3c18-4a06-ae2b-de47288be481.png)
