### ISSUE TITLE
[FEATURE]功能测试计划执行，增加失败用例的单独回归（当前只支持复制计划但无记录失败用例，状态为未开始，无法回归失败用例）

### ISSUE THREAD

**Issue by geyesheng** [metersphere/metersphere#15284]
### MeterSphere 版本

v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议

1.新增用例-评审-计划（关联用例），然后执行用例得出结果
![image](https://user-images.githubusercontent.com/38676947/175871695-85c19a48-9d34-40ed-aa69-49214605c07c.png)
2.针对测试失败用例，当前需做该部分的回归，当前只能在原计划里选择筛选和复制计划
![image](https://user-images.githubusercontent.com/38676947/175871910-6b61d6fb-447a-4b75-8ef7-5a6818ceae3c.png)
![image](https://user-images.githubusercontent.com/38676947/175871972-34112ada-767a-47f5-b795-e20efa46c9df.png)
3.进入新的计划查看显示，无获取失败的用例（显示的为所有，筛选需重置状态且全部显示为未开始，不满足失败用例的回归）
![image](https://user-images.githubusercontent.com/38676947/175872197-9530f089-257b-4e8a-a111-1dbbe97fdb14.png)
![image](https://user-images.githubusercontent.com/38676947/175872288-10a21971-3b6a-4f89-8180-93923f402894.png)

### 请描述你建议的实现方案

功能测试计划执行，增加失败用例的单独计划用于回归（当前只支持复制计划但无记录失败用例，状态为未开始，无法回归失败用例）
![image](https://user-images.githubusercontent.com/38676947/175872540-c3121e2a-c639-492e-9a2b-6f3a6ed67133.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划功能“测试计划关联功能用例时，支持按执行结果筛选用例”；可以将第一次执行失败的用例添加到新的计划中，回归执行。该功能已在开发中。
