### ISSUE TITLE
[BUG]测试计划经Jenkins构建成功后，状态展示不正常

### ISSUE THREAD

**Issue by jiangrry** [metersphere/metersphere#1528]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？    ---    V1.7.3

**Bug 描述**
简要描述您碰到的问题。 
测试计划经Jenkins构建成功后，状态展示不正常；
测试跟踪-首页-我的计划，测试进度为零、已测用例为0；
测试跟踪-报告中展现状态为“进行中”（构建后测试跟踪-首页-我的计划，展示“已完成”）；
推送邮件也没有发送（邮件推送设置正常）;

**Bug 重现步骤**
1. 设置组织-消息设置，接收邮件前提和对象；
2. 创建测试计划，选择测试报告，关联测试的场景用例；
3. Jenkins 使用 构建执行方式是 “执行测试计划中用例”，选择新增计划
4. 执行构建，并查看构建结果
5. 根据构建结果，查看内容包含：1、测试跟踪-首页-我的计划；2、测试跟踪-报告；3、登录被推送邮箱，查看收件状况

**期待的正确结果**
正确情况下应该是什么样的？
1、平台-测试跟踪-首页-我的计划-状态（由“未开始”变更“已完成”）并且测试进度（100%）以及测试用例 1/1
2、跑完Jenkins后，根据设置的前提，推送邮件。
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/6359046/109447743-4f9c2300-7a7f-11eb-9c5c-3c9a38b75829.png)
![image](https://user-images.githubusercontent.com/6359046/109448195-58d9bf80-7a80-11eb-9ab7-26006a7195cd.png)
![image](https://user-images.githubusercontent.com/6359046/109448206-5ecfa080-7a80-11eb-9258-93f7cdeb3300.png)
![image](https://user-images.githubusercontent.com/6359046/109448220-6abb6280-7a80-11eb-9d37-579ef9690bbc.png)
![image](https://user-images.githubusercontent.com/6359046/109448295-93435c80-7a80-11eb-9b26-ecb2091ae822.png)

**Comment by seasoncool** [comment]
1.7.1版本，同样有该问题。

**Comment by xulinde** [comment]
感谢您的反馈
问题一：测试跟踪-首页-我的计划，测试进度为零、已测用例为0。下个版本会修复；
问题二：测试跟踪-报告中展现状态为“进行中”（构建后测试跟踪-首页-我的计划，展示“已完成”）。下个版本会修复
问题三：推送邮件也没有发送。未复现，请检查下发件人和收件人是否设置正确且能连接成功

**Comment by xulinde** [comment]
1.9.0已修复
