### ISSUE TITLE
[BUG]UI自动化列表通过率显示有问题

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15292]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.8-LTS

### 使用外置数据库

否

### 问题描述

UI自动化列表通过率显示有问题

### 重现步骤

1、执行几个UI自动化场景
2、刷新列表，有部分执行通过的，显示的通过率为NaN

### 附加信息

![image](https://user-images.githubusercontent.com/32027713/175885853-2d204aef-2efa-4c45-b0a7-73c582ebc783.png)

**Comment by zyyfit** [comment]
您好，可以把ui场景的side文件发一下吗
