### ISSUE TITLE
[FEATURE]建议增加数据导入功能、环境配置功能

### ISSUE THREAD

**Issue by zclucky** [metersphere/metersphere#153]
**请描述您的需求或者改进建议.**

1、建议增加数据导入功能，把测试用例或者接口测试的数据导入进去，类似chrome的har数据，减轻手动添加测试的时间。
2、建议增加环境配置功能，跑自动化测试的时候可能会切换多个环境。

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
收到，多谢您的反馈，我们内部讨论下再反馈。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新发布的 v1.1.0 版本中已经增加了环境管理和接口导入的功能，欢迎下载试用
@zclucky
