### ISSUE TITLE
[FEATURE]建议自动化场景可以批量创建定时任务

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#1530]
**请描述您的需求或者改进建议.**

需求：10个自动化测试场景，我需要在每天的10点都执行一遍
解决：每一个场景分别添加定时任务

**请描述你建议的实现方案**
建议自动化场景可以批量创建定时任务，10个场景只创建一遍定时任务

**Comment by xulinde** [comment]
可以把这10个场景添加成一个测试计划，然后给测试计划设置定时任务即可
