### ISSUE TITLE
[QUESTION] metersphere mysql 的账户密码是多少，我要进去操作一下

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15307]
### 请描述您的问题

metersphere mysql 的账户密码是多少，我要进去操作一下

**Comment by Hyyfit** [comment]
![image](https://user-images.githubusercontent.com/95834771/176076864-5ac2e58b-fe82-434e-aa98-c07ef5e1f711.png)
您好，您还可以在我们官方文档上查阅到部署相关的其他信息：https://metersphere.io/docs/installation/online_installation/
