### ISSUE TITLE
[BUG]UI自动化多次执行之后出现错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15305]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.8-LTS

### 使用外置数据库

否

### 问题描述

UI自动化多次执行之后出现错误

### 重现步骤

1、某一个UI自动化场景，步骤大约20上下，重复执行3次左右会出现固定的错误:
unknown error: session deleted because of page crash
from tab crashed
  (Session info: headless chrome=102.0.5005.61)

2、出现频率较高，cloud版本也同样如此，可能和k8s部署的selenium有关

3、经过查询发现：shm_size大小问题，也就是设置容器 /dev/shm 分区的大小
但是在修改之后仍然会出现这个问题

### 附加信息

![image](https://user-images.githubusercontent.com/32027713/175925775-adb8bd15-babe-4a7c-af01-71d1e4ad0b5b.png)

**Comment by ltfit** [comment]
你好 文件提供下吧

**Comment by wudamyw** [comment]
有没有提高优先级尽快解决啊

**Comment by gengxiaoxiaoxin** [comment]
可以尝试以下几个方案：
- chrome_options.add_argument('--no-sandbox')     
- 如果使用的Docker容器，则可以尝试增加 共享内存大小
 here [docker-selenium](https://github.com/SeleniumHQ/docker-selenium#quick-start)
`docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-firefox:4.3.0-20220726`
> ☝️ When executing for an image that contains a browser please use the flag to use the host's shared memory.docker run--shm-size=2g

- 或者禁止Chrome使用内存文件系统（可能会影响性能）
   chrome_options.add_argument('--disable-dev-shm-usage')

All can be found [here](https://stackoverflow.com/a/53970825/19526752)

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
