### ISSUE TITLE
[BUG] get请求参数中到有“#”号时，接口无法请求

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#15304]
### 联系方式

18323056969

### MeterSphere 版本

V1.20.6

### 使用外置数据库

否

### 问题描述

请求：
GET https://www.xxxxx?name=测试#测试&pageSize=10&pageNum=1

返回结果：
<img width="434" alt="image" src="https://user-images.githubusercontent.com/13564069/175925606-d9b04ff2-5d9f-48fc-9e3f-0cc13f8f849d.png">

实际上应该可以调用成功，本地postman可以调用成功

### 重现步骤

1、get请求 需要传参的参数，包含# 号内容

### 期待的正确结果

可以请求

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，您这个我看是显示参数非法，您可以看看是不是接口本身不支持，或者设置query参数编码
![image](https://user-images.githubusercontent.com/73461316/176108508-bde91f19-8078-4040-949b-6b523c1e8837.png)
