### ISSUE TITLE
[BUG] get请求接口，参数带#号时，MS平台不能正常请求

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#15306]
### 联系方式

18323056969

### MeterSphere 版本

V1.20.6

### 使用外置数据库

否

### 问题描述

请求：
GET https://www.xxxxx?name=测试#测试&pageSize=10&pageNum=1

返回结果：
<img width="434" alt="image" src="https://user-images.githubusercontent.com/13564069/175925606-d9b04ff2-5d9f-48fc-9e3f-0cc13f8f849d.png">

实际上应该可以调用成功，本地postman可以调用成功

### 重现步骤

1、get类型接口请求，请求入参待#号

### 期待的正确结果

可以正常请求数据

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/15304
