### ISSUE TITLE
从YAPI里面的接口以swaggerjson格式导入到MS上出现重定向都是取消勾选的问题

### ISSUE THREAD

**Issue by renhao-hao** [metersphere/metersphere#15318]
### 联系方式

424097687@qq.com

### MeterSphere 版本

版本:   v1.20.8-lts-hotfix-cabd3acc

### 使用外置数据库

否

### 问题描述

1.现公司目前用的YAPI接口管理工具，迁移到MS平台上，我目前在YAPI里面通过swaggerjson的格式导出，然后导入到MS上，每个接口里面的其他设置跟随重定向都是取消勾选的，你们平台的技术说这都是默认勾选的，接口比较多，如果我单个每个去打开去勾选是比较麻烦的。

### 重现步骤

无

### 期待的正确结果

![image](https://user-images.githubusercontent.com/108327264/176122610-b08a2e42-9566-47d9-96d7-dbf5c7e99a26.png)

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://user-images.githubusercontent.com/108327264/176122312-bb247e57-3cac-49a2-9c92-143073c91780.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.10版本修复，请等待版本发布后验证
