### ISSUE TITLE
[BUG] 使用思维导图导入功能用例，功能列表数据显示是思维导图的倒序数据

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#15312]
### 联系方式

18311441708

### MeterSphere 版本

1.20.7.lts

### 使用外置数据库

是

### 问题描述

使用思维导图导入功能用例，功能列表数据显示是思维导图的倒序数据

### 重现步骤

使用如下图的xmind
![1656388241(1)](https://user-images.githubusercontent.com/103925124/176088131-e7b7b068-6cd4-4a47-9472-97603327f911.png)
导入功能用例列表后
![企业微信截图_16563888499337](https://user-images.githubusercontent.com/103925124/176089175-ae347b2d-aa90-4cbe-a6b0-5d3b7064b25c.png)

### 期待的正确结果

导入后，功能用例列表和xmind中用例顺序一致

### 相关日志输出

```shell
无
```

**Comment by ltfit** [comment]
感谢反馈 后续版本修复下

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
