### ISSUE TITLE
[BUG][企业用户] Plan中的用来参数化没有替换，但是在场景用来和API Case中执行时成功的

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#15314]
### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

plan执行失败，用来参数化没有替换
![image](https://user-images.githubusercontent.com/103017812/176092341-0e7e6674-f215-4e01-bbf9-a774f3c784cf.png)
但是相同的用例在场景用例执行时成功的
![image](https://user-images.githubusercontent.com/103017812/176092445-95a5a1ac-71a0-4b9e-ab2b-52819b79a210.png)
在API 用例执行，也是成功的
![Uploading image.png…]()

### 重现步骤

见问题描述

**Comment by zyyfit** [comment]
没有复现这个问题，请详细描述一下操作步骤，包括在场景里还是在测试环境里添加的参数，接口测试那边使用的环境和测试计划使用的环境是否一致等问题
![image](https://user-images.githubusercontent.com/73461316/176413694-ccd3908d-0697-4227-825d-2d00c6273f3e.png)

**Comment by sac911** [comment]
场景里面被引用的API Case的参数化没有替换，但是同样的用例如果是复制的就没有此类问题。
这个问题在我们环境中每天的定时任务里面都有发生，已经严重影响到平台的准确性和公信力，麻烦帮忙解决。实在不行是否可以代码走读一下？

**Comment by zyyfit** [comment]
您好，我还是没有复现，您可以联系交流群里的工作人员帮您看一下
![image](https://user-images.githubusercontent.com/73461316/178393877-ff717210-bf8c-43e4-8a5b-7c3f9159fe7c.png)
