### ISSUE TITLE
[FEATURE]测试计划关联用例时，没有了高级搜索，难以查找出想要的用例

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#15319]
### MeterSphere 版本

 v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

在旧版本中，1.20.4，关联用例时还有高级搜索功能。升级到新版本后，这个功能突然没有了。导致我们新一轮的测试计划要关联用例时，很难去找出自己刚刚上传的新用例。

### 请描述你建议的实现方案

建议：恢复测试计划关联用例的高级搜索功能

**Comment by Hyyfit** [comment]
感谢反馈，高级搜索功能已改版，关联用例的高级搜索功能也同步会优化，预计2.0的版本会发布。

**Comment by Donly16** [comment]
请问2.0版本大约什么时候可以发布呢？
