### ISSUE TITLE
[BUG] 同步jira缺陷，缺陷中描述字段 图片未显示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#15321]
### 联系方式

18311441708

### MeterSphere 版本

1.20.7.lts

### 使用外置数据库

否

### 问题描述

jira项目中某缺陷描述有文字有图片
![企业微信截图_16564079762383](https://user-images.githubusercontent.com/103925124/176142966-d85669a0-2528-4e06-a42f-bef85899bf93.png)

点击同步缺陷后，在列表查看描述字段，只显示文字部分，未显示图片,不能预览

![image](https://user-images.githubusercontent.com/103925124/176141968-6c5d4bfd-c71b-4b24-b579-4d6bc1832eac.png)

其中  缺陷描述字段文字和图片均可显示

![image](https://user-images.githubusercontent.com/103925124/176151020-fca30b05-d803-4f9a-8653-59f4225edecc.png)

### 重现步骤

jira项目中某缺陷描述有文字有图片
![企业微信截图_16564079762383](https://user-images.githubusercontent.com/103925124/176142966-d85669a0-2528-4e06-a42f-bef85899bf93.png)

点击同步缺陷后，在列表查看描述字段，只显示文字部分，未显示图片

### 期待的正确结果

![879408603286562004](https://user-images.githubusercontent.com/103925124/176150882-b3911f01-f1af-4f7f-87c8-bed1d53ab0fd.jpg)

_No response_

**Comment by ltfit** [comment]
你好 v1.20.8-lts已修复此问题 升级下

**Comment by Ycr123888** [comment]
使用v1.20.8-lts已修复此问题，感谢回复
