### ISSUE TITLE
[BUG]截图模式下，大概率不执行用例

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#15324]
### MeterSphere 版本

1.20.8

### 使用外置数据库

否

### 问题描述

UI 自动化
1）打开截图模式（不勾选性能模式）
2）执行用例

结果：大概率不执行用例，或者一直处于运行状态，不报错不结束。

![WechatIMG42](https://user-images.githubusercontent.com/10231088/176259163-30b7e39c-0765-419e-b888-2c7b13559eb5.jpeg)
![WechatIMG61](https://user-images.githubusercontent.com/10231088/176259177-6d302f2b-fc59-4662-afb3-9c6293e1b772.jpeg)

### 重现步骤

见描述

### 附加信息

已和交付团队沟通。企业版用户。 与#15305 可能有关类似

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.10已修复
