### ISSUE TITLE
[FEATURE]消息设置以工作空间粒度为单位通知

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#1532]
**请描述您的需求或者改进建议.**
目前消息设置生效的粒度以组织为单位，对于大型的组织或项目，消息比较多，难以精准处理。
希望可能以工作空间为粒度设置生效

![image](https://user-images.githubusercontent.com/9674075/109467504-3b1f5100-7aa6-11eb-8501-caa28a28514f.png)

**请描述你建议的实现方案**

**Comment by xchnshi** [comment]
或者可以通过开关控制，生效的粒度（组织还是工作空间）

**Comment by xulinde** [comment]
收到，感谢您的建议，我们内部讨论下再反馈。

**Comment by zcyuefan** [comment]
建议组织-空间-项目三层消息设置。空间继承组织的设置并能够自定义，项目继承空间的设置并能够自定义，消息触发时就可以优先读取项目的设置。这样的话大型项目（同一个工作空间）中各个小的项目中就可以互相不干扰。
