### ISSUE TITLE
[BUG]在测试用例多选时选中【所有数据】后，翻页发现并没有选中后续页面

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#1533]
**MeterSphere 版本**
1.7.2

**Bug 描述**
如题，在测试用例多选时，多选范围选中【选择所有数据】，但翻页后发现第2页之后的数据并没有被选中，选中效果实际和【选中当前页面数据】的效果是一样的
这个全部数据选中失效的bug，还会导致导出用例时也只能导出第一页的数据

**Bug 重现步骤**
见描述

**期待的正确结果**
如果多选的数据范围为【选择所有数据】，则应该翻页后的数据也是选中状态，且导出用例时能导出所有页数下的数据，而非只有第一页

**截图**

**Comment by xulinde** [comment]
您好，选择数据这个功能仅用于批量操作。您如果是想导出用例，需要以下操作：
1.不勾选，点击导出是默认导出所有用例
2.勾选用例，点击导出是导出已勾选的用例
![image](https://user-images.githubusercontent.com/64065190/109483978-d4f0f900-7aba-11eb-8e9d-1cc43cd20d8d.png)

**Comment by xulinde** [comment]
“在测试用例多选时，多选范围选中【选择所有数据】，但翻页后发现第2页之后的数据并没有被选中，选中效果实际和【选中当前页面数据】的效果是一样的“关于这个问题，我们会在后续版本优化下

**Comment by xulinde** [comment]
1.9.0已优化
