### ISSUE TITLE
[BUG] v1.20.8 引用的场景，无法新增断言

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15331]
### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

引用的场景，无法新增断言

### 重现步骤

1 打开场景用例中的引用场景
2 新增断言模块，为灰色不可编辑状态
3 偶现可编辑，但是保存刷新后，依然没有

### 期待的正确结果

引用的场景，可以正常新增断言规则

### 附加信息

![image](https://user-images.githubusercontent.com/20641051/176349648-e67ebb5d-dbec-4ccf-b9a8-1369f53da0d5.png)

**Comment by xulinde** [comment]
引用的case无法编辑，复制的可以，设计如此。

**Comment by lijinzhou2016** [comment]
1.16版本可以的

**Comment by xulinde** [comment]
那可能是当时版本有缺陷，正常情况下是无法新增的
