### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by meimeiaiceshi** [metersphere/metersphere#15333]
### MeterSphere 版本

1

### 请描述您的需求或者改进建议

问题：目前在发送自动化定时报告的时候：是一个链接的方式，不利于领导和其他同事在手机查看。需要点击链接后才能查看具体的自动化报告内容。
修改原因：自动化报告一般会设置早上6点钟发送，对应的负责人看到后，不够直观。还需要点击链接，不方面。
建议：可以输出一个基础的页面展示，方便使用查看。

### 请描述你建议的实现方案

建议：可以输出一个基础的页面展示，方便使用查看。

### 附加信息

1.目前在公司推广，针对自动化的效果，需要通过邮件的方式，输出给领导，如果只是一个链接的报告，很难发给领导看。所以可以考虑，有基础页面的方式展示。
2，目前rf或者其他的工具已经都有页面展示，是基础配置。希望重点考虑，早点发版，谢谢。

**Comment by meimeiaiceshi** [comment]
![报告1](https://user-images.githubusercontent.com/30189632/176364385-5803c580-c373-4e3a-b99c-5647d655100c.png)

**Comment by meimeiaiceshi** [comment]
![rf报告](https://user-images.githubusercontent.com/30189632/176364542-580f8fe4-01ef-4d59-a510-1088b00d5ac5.png)
目前使用的自动化报告：希望可以做成这样，或者类似。有页面展示。谢谢

**Comment by Hyyfit** [comment]
感谢反馈，待规划设计。
