### ISSUE TITLE
[BUG]使用错误的beanshell脚本进程一直卡在运行中

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15337]
### 联系方式

mryu168@163.com

### MeterSphere 版本

1.2.0

### 使用外置数据库

否

### 问题描述

使用错误的beanshell脚本进程一直卡在运行中
![image](https://user-images.githubusercontent.com/40486003/176374769-07e15e5d-db8f-41cf-bc3c-4e44df7ff588.png)

### 重现步骤

使用最简单不合规的数据
vars.put("channel_id","${__intSum(1,2,3)}");

### 期待的正确结果

console里需要返回对应的错误信息、并终止调试工作

**Comment by xulinde** [comment]
v1.20.8版本未复现该问题，您用的是1.2.0版本？建议升级到最新版本
