### ISSUE TITLE
[BUG] V1.20.8 引用的步骤，无法操作 启用/禁用 功能

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15330]
### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

引用的步骤，无法操作 启用/禁用 功能

### 重现步骤

场景用例中
引用别的场景，引用的场景又引用了别的场景
里面的场景，无法操作 启用/禁用 功能
控制器下面的引用，也无法操作 启用/禁用 功能

### 期待的正确结果

可以正常开启或关闭 启用/禁用 按钮

### 附加信息

![image](https://user-images.githubusercontent.com/20641051/176349107-5661954f-153d-41d9-80b8-2e80aeec9d6f.png)

**Comment by zhangzhaox** [comment]
这不是问题好不，最外层的是可以禁用 启用

**Comment by xulinde** [comment]
> 这不是问题好不，最外层的是可以禁用 启用

是这样的～

**Comment by lijinzhou2016** [comment]
OK，麻烦看下这种情况，控制器下面，引用case，引用过来后，就无法删除和启动禁用操作
![image](https://user-images.githubusercontent.com/20641051/176376222-88f3caf5-64d1-4cb9-8829-93b725b2b89b.png)
