### ISSUE TITLE
[FEATURE]引用的case，在不同的场景可以新增不同的断言

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15346]
### MeterSphere 版本

1.20.8

### 请描述您的需求或者改进建议

1 在case中，不应该做断言，只是简单的包装请求
2 在不同的场景中，需要断言不同的字段，即使同一个字段，在不同的场景也有不同的值
3 如果在case中做断言，事先无法枚举出所有场景，且有些场景断言相互冲突
4 如果维护不同的case，则需要维护大量case，这就失去了case的意义

### 请描述你建议的实现方案

1 在case中，不应该做断言，只是简单的包装请求
2 在不同的场景中，需要断言不同的字段，即使同一个字段，在不同的场景也有不同的值

**Comment by Hyyfit** [comment]
感谢反馈，设计如此。
1.在case中添加断言主要是做通用性的断言。
2.场景自动化主要是做流程性的用例，涉及到多接口组合的场景，当场景中的case断言与case中原有的断言冲突时，以场景中的断言为准。
3.“如果维护不同的case，则需要维护大量case，这就失去了case的意义”，这种情况是单接口根据入参不同，覆盖不同的场景，建议可以将入参设置成变量，通过场景变量中的csv数据文件管理和循环控制器来实现，不需要维护大量的case。

**Comment by lijinzhou2016** [comment]
好的，感谢
场景断言，我们测试的，
1 一个场景只能有一个场景断言
2 而且断言的步骤，在场景里的每一个步骤都生效
请问下是这样用的吗，还是我们用的不对。
如果是这样用的话，会有两个问题
1 断言和步骤就脱离了，不是太友好，几十步的场景用例，所有断言都写在一个断言里，不是太好维护
2 所有断言对所有步骤都生效，这样就冲突了
