### ISSUE TITLE
[FEATURE]项目-环境配置-HTTP配置能否有多个

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1534]
**现象**
HTTP配置能否有多个，一套环境只能配置一个url地址；配置完bos请求地址后，我加了一个agw的restful发包工具的请求地址，在环境里面做成了第二个环境的配置；

**请描述您的需求或者改进建议.**
HTTP配置能否有多个，一套环境可能存在多个HTTP请求地址

拿证券行业低延时项目来说：它包含OSS、BSS两个web请求地址，agw、dxs、dxs兜底、agw适配器、dxs适配器也会有自己的web请求地址。我们是用springboot项目包装linux下c++动态链接库来简化前端请求的难度，提高系统的可测试性，降低系统对测试人员的使用难度；使用类似postman、jmeter工具发送restful接口，测试二进制agw、kcxp接口；

BOS
BSS
AGW发单工具
DXS发单工具
DXS兜底发单工具

一套环境至少有个http请求的url地址

**请描述你建议的实现方案**

**Comment by du0506** [comment]
同求增加这个功能，可以将用例分组配置单独的运行环境，然后整个场景中的cookie是共享的；
我们场景是登录获取token服务在**A服务器**，程序逻辑在**B服务器**，我们测试逻辑时必须**先去A服务器获取token**,然后在**去B服务器测试接口**，不知道在现有功能上能不能满足这个场景？
期待回复，感谢！

**Comment by wangzhen-fit2cloud** [comment]
你好，目前有个大概的想法是这样的。
- 在环境配置中的 HTTP 配置里，支持配置多个 HTTP 配置。
- 每条 HTTP 配置在现有配置项基础上增加匹配规则的设定，匹配规则可以是 默认 | 特定模块 | 特定 URL
- 在场景中添加接口或用例，或添加自定义请求时，根据所选环境中 HTTP 配置的规则使用不同的域名。

**Comment by t880216t** [comment]
> 你好，目前有个大概的想法是这样的。
> 
> * 在环境配置中的 HTTP 配置里，支持配置多个 HTTP 配置。
> * 每条 HTTP 配置在现有配置项基础上增加匹配规则的设定，匹配规则可以是 默认 | 特定模块 | 特定 URL
> * 在场景中添加接口或用例，或添加自定义请求时，根据所选环境中 HTTP 配置的规则使用不同的域名。

之前开发类似的功能，我的实现方式是：
* 每个httpsample支持自定义请求的协议和域名，是否有端口可从域名地址字段解析出来。
* 整个任务的可以指定环境域名，配置最终生成jmx时是放在全局请求头中的，没有配置host的httpsample默认会自动走这个。

**Comment by xulinde** [comment]
1.10已实现该功能
