### ISSUE TITLE
Swagger定时同步和手动导入报错[BUG]

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#15355]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.4

### 使用外置数据库

否

### 问题描述

1.Swagger定时导入未成功同步，Swagger URL在浏览器能正常打开，，在服务器上telnet  Swagger URL地址也是通的，看日志报错如下图。
![165e43de52c79a1276a65aada42275a](https://user-images.githubusercontent.com/103627487/176421023-be8c7cf5-7482-4422-ad84-ab9831ff30d0.jpg)
2.保存为文件手动导入，报数据解析错误，报错日志如下图
![origin_img_v2_b1e54d04-ceed-4fa7-8beb-8547de78c35g](https://user-images.githubusercontent.com/103627487/176422200-baf5acac-963d-4f57-bfa4-a6fb00e66e26.jpg)

### 重现步骤

1.Swagger定时导入

### 期待的正确结果

能正常同步和导入

### 附加信息

![origin_img_v2_67b94afc-a55f-4521-940a-fc0fd3c645cg](https://user-images.githubusercontent.com/103627487/176424074-08c6f57d-6729-4244-b40f-3965818a7525.jpg)
图中 1，3 定时任务均不能正常导入，2可以正常导入

**Comment by zyyfit** [comment]
数据解析错误一般是文件内容格式或者其他地方不对，请问1和3返回的数据是完整的swagger文件吗？方便把1或者3的返回数据上传一下吗？

**Comment by zyyfit** [comment]
经排查，是用户文件的json格式不对，多了许多不应该有的逗号
![image](https://user-images.githubusercontent.com/73461316/176641877-d2931325-743c-45e4-b2b7-f57a8131e909.png)
![image](https://user-images.githubusercontent.com/73461316/176641900-3c7aac98-7ebb-49cc-8b00-b2612bc44f18.png)
![image](https://user-images.githubusercontent.com/73461316/176641916-2c04f08b-b1b7-45ce-81a7-0ab3608340a7.png)
