### ISSUE TITLE
[FEATURE]接口测试中的调试无法查看历史记录和结果

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1535]
**请描述您的需求或者改进建议.**
#804 

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
前单个步骤中的响应内容需要点击该步骤上的执行按钮才会有，点击场景的调试按钮不会更新响应内容。我们会在后续的版本中优化下这个地方。

**Comment by xulinde** [comment]
目前，接口自动化的执行是可以保存每次的测试报告的
![image](https://user-images.githubusercontent.com/64065190/109619921-46d94900-7b74-11eb-8878-f32630273e90.png)

**Comment by zh417233956** [comment]
> 目前，接口自动化的执行是可以保存每次的测试结果的
> ![image](https://user-images.githubusercontent.com/64065190/109619921-46d94900-7b74-11eb-8878-f32630273e90.png)

这个可以参考一下postman,在postman中进行调试或者请求后，是有console记录的，可以很方便的查看之前的结果相关的信息

**Comment by zh417233956** [comment]
> 目前，接口自动化的执行是可以保存每次的测试结果的
> ![image](https://user-images.githubusercontent.com/64065190/109619921-46d94900-7b74-11eb-8878-f32630273e90.png)

**Comment by zh417233956** [comment]
> 目前，接口自动化的执行是可以保存每次的测试结果的

这个可以参考一下postman,在postman中进行调试或者请求后，是有console记录的，可以很方便的查看之前的结果相关的信息

**Comment by zh417233956** [comment]
跟进一下

**Comment by zh417233956** [comment]
继续跟进

**Comment by xulinde** [comment]
1.10版本新增变更历史，您看下是否满足了您的需求

**Comment by zh417233956** [comment]
@xulinde 依然需要手动保存，没有实现历史记录的功能

**Comment by zh417233956** [comment]
@xulinde 操作日志，很不错，还可以再完善一下细节，把操作对象不同类型的操作结果可以进行一下关联
比如：接口自动化，测试完是有测试报告的记录信息，只需要关联一下报告ID，在日志详情就可以实现查看报告ID,希望能支持
![image](https://user-images.githubusercontent.com/22386206/127438895-87b48ee5-5642-4c1d-aaad-49b3e86d8d52.png)
