### ISSUE TITLE
计数器顺序读取不对[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#15358]
### 联系方式

dongxue.liu@fit2cloud.com

### MeterSphere 版本

 v1.20.8-lts-hotfix-cabd3acc    CLOUD 版本

### 使用外置数据库

是

### 问题描述

采用for循环100次，每次做了计数标识，循环读取csv文件，最后报告选啥循环是乱的

### 重现步骤

1.添加计数器
![image](https://user-images.githubusercontent.com/30932762/176443959-a963cc6d-d4e3-4aed-a26f-540c77622e68.png)
2.上传cvs
3.编写场景，如下
![image](https://user-images.githubusercontent.com/30932762/176444037-ce04ea8a-26db-426c-83cd-f614537afdc0.png)
4.运行报告里面显示的计数是乱的，如下
![Uploading image.png…]()

### 期待的正确结果

按照循环的顺序，依次显示1-100

### 相关日志输出

```shell
无
```

### 附加信息

cloud 版本，用户id:7fdd2583-04f6-4295-9c1d-0c1d0231ed66

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.9-lts已修复，请等待发版后验证
