### ISSUE TITLE
[BUG]后置提取参数为null时使用${var_Name}参数合并有误

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15352]
### 联系方式

mryu168@163.com

### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/40486003/176416671-13938625-2a0e-438f-93ee-6144d0dd73b0.png)
后置提取参数为null时使用${var_Name}参数合并有误

### 重现步骤

已知接口A对应的response={"a":null,"b":1}
将a提取出来$.a赋值给varNameA
后续再创建一个B接口、方式使用json传递、body={"a":${varNameA},"b":1}
这个时候发现body = {"a":, "b":1}

**Comment by zyyfit** [comment]
因为a没有值，所以赋值后的变量也没有值，引用过去就是空的，您希望有什么效果呢

**Comment by kamalyes** [comment]
application/json时是否可以保存为null呢、不然认定这不是一个有效的json

**Comment by zyyfit** [comment]
暂时不支持，jmeter里也是这样的，由于我们执行接口，提取脚本等操作是用jmeter执行的，所以目前是和jmeter保持一致，您可以先写脚本处理一下

**Comment by zhangzhaox** [comment]
@kamalyes 脚本做判断，这属于脚本补严谨的一种形式，如果提取之为空 就不执行后面的操作
