### ISSUE TITLE
[QUESTION]如何自定义statuscode效验呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15353]
### 请描述您的问题

例如：已知场景A下触发的statuscode!=200、这个时候认定为失败了不通过。实际需要的结果就是非200的异常值

**Comment by Hyyfit** [comment]
您好，可以通过正则的方式进行断言。
<img width="853" alt="image" src="https://user-images.githubusercontent.com/95834771/176602000-c72e0d71-8205-4fa2-8bf8-ac15de9870c4.png">

**Comment by kamalyes** [comment]
![image](https://user-images.githubusercontent.com/40486003/176836329-d1022fc8-29bc-4c29-b73b-a620f5774ea1.png)
这种场景下状态还是未通过呢。实际它就是一个有效的异常用例
