### ISSUE TITLE
[QUESTION][数据库连接数挤满连接池问题]

### ISSUE THREAD

**Issue by ZhouHuTao** [metersphere/metersphere#15369]
### 请描述您的问题

使用外部数据库，部署后产生大量的sleep连接，导致挤满连接池，但外部数据库又不止metersphere一个库，影响到其它服务的使用，且不好直接设置wait_timeout处理。麻烦看下是什么原因导致连接数这么多且会不断新增这些sleep连接？
![image](https://user-images.githubusercontent.com/55977225/176587188-c3f98240-87de-483d-b0b2-bfa0c9890c01.png)
![image](https://user-images.githubusercontent.com/55977225/176587195-48612a74-da06-499d-9d76-df8993aa4d1b.png)

**Comment by Hyyfit** [comment]
感谢反馈，您可以在我们的微信交流群联系我们的技术人员，远程帮你排查问题。
