### ISSUE TITLE
[FEATURE]UI测试模块没有做权限控制

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#15361]
### MeterSphere 版本

v1.20.7

### 请描述您的需求或者改进建议

UI测试模块没有做权限控制

### 请描述你建议的实现方案

增加对UI模块的权限控制功能

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/176579820-4621a8fa-bae9-433a-aede-4e17416674a1.png)
![image](https://user-images.githubusercontent.com/5198427/176579883-56f84ccc-fe31-42a9-80bd-63c055655278.png)

**Comment by Hyyfit** [comment]
您好，有权限控制的，您这个是试用版吧？可以在微信交流群联系我们的技术人员，体验企业版的功能。
<img width="923" alt="image" src="https://user-images.githubusercontent.com/95834771/176601211-4bc87b32-ea1d-4a78-80a8-1b9d685dec70.png">
