### ISSUE TITLE
【测试用例评审需求】建议项目配置或者其他模块价格功能权限，测试用例评审阶段允许用户编辑，不然每次评审完得去看用例评论一个个修改，易用性很低

### ISSUE THREAD

**Issue by TesterYu** [metersphere/metersphere#15360]
### MeterSphere 版本

版本:   v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

【测试用例评审需求】建议项目配置或者其他模块价格功能权限，测试用例评审阶段允许用户编辑，不然每次评审完得去看用例评论一个个修改，易用性很低

### 请描述你建议的实现方案

【测试用例评审需求】建议项目配置或者其他模块价格功能权限，测试用例评审阶段允许用户编辑，不然每次评审完得去看用例评论一个个修改，易用性很低

**Comment by Hyyfit** [comment]
感谢反馈，已规划用例评审优化，待排期。
