### ISSUE TITLE
[BUG]脑图界面编写用例，新增模块时界面错乱

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#15367]
### MeterSphere 版本

v1.20.8-lts-ba947709

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/42445400/176584643-deb89899-c62b-442e-bea4-3368d4e9d729.png)
脑图界面编写用例，新增模块时界面错乱，如图

### 重现步骤

1.脑图编写用例
2.模块数量较多时（7-8个）
3.选择其中一个模块新增多个子模块，就会出现

### 期待的正确结果

界面正常显示

**Comment by ltfit** [comment]
你好 方便录个屏吗 我没复现出来
