### ISSUE TITLE
[BUG]在用例模板这边新增了一个自定义字段，在导出脑图的时候，这个字段好像带不出来欸

### ISSUE THREAD

**Issue by zjy0504** [metersphere/metersphere#15374]
### 联系方式

290847134@qq.com

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

否

### 问题描述

在用例模板这边新增了一个自定义字段，在导出脑图的时候，这个字段好像带不出来欸

### 重现步骤

1.项目设置，用例模板设置增加自定义字段名为：版本信息；
2.新增用例，填写字段模板信息值为p1；
3.保存，导出脑图，模板信息和值未被导出至脑图中。

**Comment by zjy0504** [comment]
![image](https://user-images.githubusercontent.com/81353011/176612809-ebdfd396-7c1c-4459-8464-7b56c2249259.png)
![image](https://user-images.githubusercontent.com/81353011/176612846-bacb7343-0eb0-4777-a122-9a4bbd5b8a95.png)
![image](https://user-images.githubusercontent.com/81353011/176612860-70da64a9-ba9d-4c9b-ab11-6e00e66c8d4f.png)

**Comment by zjy0504** [comment]
麻烦问一下，会排到近期的需求里嘛？

**Comment by Hyyfit** [comment]
近期没有。脑图的功能会做统一的优化，还需要等待排期。
