### ISSUE TITLE
[BUG]接口自动化场景用例直接执行正常，但是关联到测试计划中后就不执行，控制台也没有任何反馈

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#15372]
### 联系方式

18660359795

### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

接口自动化场景用例直接执行正常，但是关联到测试计划中后就不执行，控制台也没有任何反馈。

### 重现步骤

该场景包含两步，第一步获取授权码，第二步拿着这个授权码登录。
场景用例执行正常：
![image](https://user-images.githubusercontent.com/100331967/176609712-67ed0d14-e952-4a15-a6aa-3783ac383e0a.png)

测试计划执行时直接不执行：
<img width="839" alt="cc636fd7a1335239ce74d59cea906a9" src="https://user-images.githubusercontent.com/100331967/176609967-adc0c7a3-8bd3-477b-8d7c-8169bc10895c.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现您的问题，请参考如下链接排查一下吧
https://kb.fit2cloud.com/archives/46
