### ISSUE TITLE
[BUG] 性能测试，数据库表字段不够长导致报错

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#15389]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.8-lts

### 使用外置数据库

否

### 问题描述

1、性能测试，load_test_report_result_realtime表report_value字段不够长导致报错

### 重现步骤

1、跑一个时间长一点的性能测试
2、error日志
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/72729206/176676386-1c301598-3132-43a2-a55a-5cf7f379a0e5.png">

### 期待的正确结果

1、长度够长，不报错

**Comment by liuruibin** [comment]
如何能在我们的环境里复现这个问题，现在这个字段长度是64k
