### ISSUE TITLE
[FEATURE]UI自动化，场景步骤当前步骤的颜色太浅看不出来，后端调试时能否每步成功后有标志？

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#15386]
### MeterSphere 版本

1.20.8

### 请描述您的需求或者改进建议

[FEATURE]UI自动化，场景步骤当前步骤的颜色太浅看不出来，后端调试时能否每步成功后有标志？

**Comment by Hyyfit** [comment]
您好，运行结束后，每步的调试结果会在步骤前展示
<img width="66" alt="image" src="https://user-images.githubusercontent.com/95834771/176811683-e025c732-9aa5-4be1-bbb6-3e53bc43ba80.png">
