### ISSUE TITLE
[BUG]场景内添加api接口，通过搜索查询到api接口后，需要勾选两次才可以添加

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15381]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.8-LTS

### 使用外置数据库

否

### 问题描述

场景入参中增加api接口，通过搜索查询到api接口后，需要勾选两次才可以添加

### 重现步骤

1、场景入参中增加api接口
2、通过搜索查询到目标api
3、勾选目标API,发现需要点击两次才可以被选中

### 附加信息

1、搜索API
![image](https://user-images.githubusercontent.com/32027713/176626429-377e3901-ac84-476f-a18e-2215a6789abb.png)

2、点击添加目标API,需要点击两次复选框
![image](https://user-images.githubusercontent.com/32027713/176626547-154487d5-2a8c-4bc7-9184-dfdb5a55beff.png)

**Comment by zyyfit** [comment]
1.20.10版本修复，请等待版本发布后验证
