### ISSUE TITLE
[FEATURE]docker打包时能映射内网宿主机/etc/hosts文件

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1538]
**请描述您的需求或者改进建议.**
很多公司测试环境是内网环境不能连外网并且内网测试区没有DNS解析功能；
像metersphere工具一般是办公类支持系统，部署在办公支撑区，测试区和办公支撑区不是一个网段且需要过墙；
metersphere使用办公支撑区的jira等系统，需要通过域名解析，但是测试区没有域名解析；

**请描述你建议的实现方案**
ms-server不支持内部域名系统解析，需要手工进入docker添加hosts文件，docker重启之后解析会消失，需要重新加hosts解析；
这样我们只要修改宿主机/etc/hosts文件映射即可，即便ms-serer容器重启也没有关系

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/109605460-27d0bc00-7b60-11eb-947a-f5b32893a7ff.png)
你好，可以通过在项目的环境配置中配置 hosts 方式来实现静态域名解析。
