### ISSUE TITLE
[FEATURE]希望场景或者API CASE内的断言新增复制功能

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15382]
### MeterSphere 版本

1.20.8-LTS

### 请描述您的需求或者改进建议

1、当场景或者case内需要添加多个断言时，需要一个一个手动添加，无法复用写好的断言，比较浪费时间
2、希望添加后可以提升效率，这些细节方面的优化或者小功能的添加可以逐步提升整个系统的用户体验

**Comment by Hyyfit** [comment]
感谢反馈，场景自动化里有提供“场景断言”，是对场景里所有的请求生效的。

**Comment by dashenyucainiao** [comment]
1、你这里指的是场景断言，会对场景内的所有请求生效，没有理解上文的所说的意思
2、这里的断言复制是针对某些接口需要的断言非常多（比如说接口返回字段与数据库查询字段做比对），且断言类型一致，希望可以在当前接口下进行复制微调即可使用，和场景断言没有什么关系

**Comment by Hyyfit** [comment]
感谢反馈，这个可以加，已规划。
