### ISSUE TITLE
[QUESTION] metersphere 能否像 jmeter 一样使用 KafkaPrducerConfig

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15390]
### 请描述您的问题

metersphere 能否像 jmeter 一样使用 KafkaPrducerConfig

![image](https://user-images.githubusercontent.com/5927005/176728407-09aad62e-7286-49ec-9ca6-367c8c28eb66.png)

**Comment by Hyyfit** [comment]
不支持哦。
