### ISSUE TITLE
[BUG]  变更历史无法记录用例-基础信息的更新操作

### ISSUE THREAD

**Issue by chenrikang** [metersphere/metersphere#15394]
### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例-变更历史   无法查看修改或记录错误的操作信息

### 重现步骤

点击测试跟踪-功能用例   修改某一条用例后   点击变更历史   发现记录信息为空或者记录错误

**Comment by zyyfit** [comment]
最新版1.20.9-lts未复现这个问题，请升级到最新版试试
