### ISSUE TITLE
[BUG]调试执行API用例，系统通知信息错位（检查了配置该场景未配置该提示人）

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#15392]
### 联系方式

14群-亲山留水

### MeterSphere 版本

v.1.19.3

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/176801894-4bd158cd-0e2e-49ab-a780-d02d8a4b93ea.png)

### 重现步骤

系统消息提示人信息显示不正确

**Comment by zyyfit** [comment]
1.20版本修复过这个问题了，请升级到最新版使用
