### ISSUE TITLE
[FEATURE]测试用例不同资料夹内的用例名称能改成可重复

### ISSUE THREAD

**Issue by stwater20** [metersphere/metersphere#154]
**请描述您的需求或者改进建议.**
测试用例不同资料夹内的用例名称能改成可重复吗?
实际写用例的时候，有一些通用的，统一项目，不同的模块有可能会重复

**请描述你建议的实现方案**

同一项目 但不同资料夹的用例名称可重复

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 测试用例不同资料夹内的用例名称能改成可重复吗?
> 实际写用例的时候，有一些通用的，统一项目，不同的模块有可能会重复
> 
> **请描述你建议的实现方案**
> 
> 同一项目 但不同资料夹的用例名称可重复

已规划，将于最近1周发布，请关注交流群版本更新通知
