### ISSUE TITLE
[BUG]场景用例中间夹着条件控制器时无法使用推荐jsonpan断言

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15406]
### 联系方式

mryu168@163.com

### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/40486003/176848841-58110afe-2edb-49bc-825e-28368c1ad5e4.png)

### 重现步骤

多个接口中加一个条件控制器调试后再次点击【推荐jsonpan断言】

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现。返回的是json格式吗？方便把这个场景导出来我们看看？

**Comment by kamalyes** [comment]
@youliyuan-fit2cloud 场景导出来可能执行不了走的内网 返回的格式是json的，后面的case也执行了 但点击【推荐JSONpath】说没有执行过

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.10-lts已修复～
