### ISSUE TITLE
[BUG] 服务器无法识别该请求？

### ISSUE THREAD

**Issue by liuchengxu11** [metersphere/metersphere#15407]
### MeterSphere 版本

 v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33363646/176853295-86f7c0fa-398a-4034-8e32-934e51751179.png)

<img width="930" alt="image" src="https://user-images.githubusercontent.com/33363646/176853356-9dd34bb6-f7d6-4091-a09f-0d710f9a3ec8.png">
为何 QUERY 以及REST 这边在url后面传参数的时候都会报这个错误

400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

### 重现步骤

就是正常的接口请求

**Comment by xulinde** [comment]
看报错像是网络问题，ms-server容器能ping通你的服务器地址吗？
