### ISSUE TITLE
推荐断言自动关闭

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#1540]
**请描述您的需求或者改进建议.**
点击推荐断言后，这个页面建议点击该页面区域外的位置自动关闭。每次需要点击关闭按钮比较繁琐

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/34681889/109583767-643df100-7b3b-11eb-825e-5f92c9f51b89.png)

**Comment by xulinde** [comment]
如果设置好几个断言，每次设置完自动关闭的话是不是不太方便

**Comment by xiaoguiliu** [comment]
嗯，还是保持现在的交互吧。
