### ISSUE TITLE
[QUESTION]循环控制器里如何记住变量呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15402]
### 请描述您的问题

您好！请问下在循环控制器中需要操作n次、但每次都是一样${varName}存储、又想把里面的值给存起来给循环控制器外的场景使用、有何种方式可以去实现？（如下图）
![image](https://user-images.githubusercontent.com/40486003/176838691-c31f01f0-84b5-4af1-b5c6-a10680775277.png)

**Comment by Hyyfit** [comment]
您好呀，您可以在微信交流群里联系技术支持人员，会有开发小哥哥给您解答问题，也会帮您远程排查错误。
