### ISSUE TITLE
[FEATURE]场景中单独调用是否可以把变量存起来做全局使用呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15416]
### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议

场景中单独调用是否可以把变量存起来做全局使用呢？
![image](https://user-images.githubusercontent.com/40486003/176864053-05adcc0e-f3ca-443c-93f8-1fb9d8b7036d.png)

### 请描述你建议的实现方案

单独点击调试所提取出的变量可以适配全局

**Comment by Hyyfit** [comment]
暂不考虑该功能。
您可以先将其他请求禁用（通过批量禁用的方式），单独调试A、B请求。
