### ISSUE TITLE
[BUG]环境自定义变量和数据源名称都是c1db，引用数据源的时候填写数据源名称c1db取的是变量名称

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1541]
**MeterSphere 版本**
1.7.3

**Bug 描述**
环境自定义变量和数据源名称都是c1db，引用数据源的时候填写数据源名称c1db取的是变量名称,没有用${}引用应该作为字符串访问才对

**Bug 重现步骤**
1. 在环境和数据源里面同时定义c1db
2. 引用数据源c1db，发现取的是变量c1db内容

**期待的正确结果**
正确情况下应该是什么样的？
数据源引用是字符串引用，变量引用是${}引用

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，能否提供下变量和数据源定义及引用的截图？

**Comment by wangzhen-fit2cloud** [comment]
@xulinde
