### ISSUE TITLE
[FEATURE]是否可以增强复制请求参数的功能呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15418]
### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议
![image](https://user-images.githubusercontent.com/40486003/177068355-3dfaaa17-0e41-44db-a31e-8c12450182b1.png)
![image](https://user-images.githubusercontent.com/40486003/177068233-4189bf83-10eb-4b3c-ab8e-2830316a0afe.png)

**Comment by Hyyfit** [comment]
您好呀，不理解您的问题/需求是什么，请描述清楚。

**Comment by kamalyes** [comment]
标题复制错了，这个问题应该是JSR223PostProcessor脚本中不支持console以及print日志输出
