### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by T-tang-tao** [metersphere/metersphere#15415]
### MeterSphere 版本

 v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

当场景执行时，控制器拦截生效时，仅显示IfController。

### 请描述你建议的实现方案

执行生成测试报告时，可以将条件控制器备注信息，展示在测试报告中，不仅仅是组件名字，到底是何种原因，测试报告错误原因更加直观

**Comment by Hyyfit** [comment]
感谢反馈，暂不支持该功能。
