### ISSUE TITLE
[FEATURE]是否可以增强复制请求参数的功能呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15419]
### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议

例如可以复制如下内容、便于在其他终端上也可以调用
![image](https://user-images.githubusercontent.com/40486003/176865486-e363d278-867d-4432-b713-c685cac5eb7f.png)

**Comment by Hyyfit** [comment]
暂不考虑该功能
