### ISSUE TITLE
[FEATURE]部分属性在列表查询的时候是否可以增强下拉框选择呢？

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15420]
### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 请描述您的需求或者改进建议

这几个属性在列表查询的时候是否可以增强下拉框选择呢？
![image](https://user-images.githubusercontent.com/40486003/176868573-ca259579-55ed-42e3-b709-13504a5f15a2.png)
在列表就可以选择对应的值，类似于
![image](https://user-images.githubusercontent.com/40486003/176868864-1de1c5a7-f037-4996-bfdf-0aea5a70fafc.png)

**Comment by Hyyfit** [comment]
功能正在开发中，2.0的版本会上线～～

**Comment by Hyyfit** [comment]
已规划，待排期。
