### ISSUE TITLE
[BUG]平台oracle驱动兼容性问题

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1542]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
平台oracle驱动对select * from v$Version不支持，报ORA-00911:invalid charactor
平台oracle驱动对分号不支持（select * from hs_user.sysarg;），报ORA-00911:invalid charactor

**Bug 重现步骤**
1. select * from v$Version
2. select * from hs_user.sysarg;

**期待的正确结果**
正确情况下应该是什么样的？
plsql是支持的

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
收到，我们排查下问题

**Comment by xulinde** [comment]
目前不支持这个驱动
