### ISSUE TITLE
[BUG]测试计划报告，分享报告，点击目录的链接，显示异常

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [metersphere/metersphere#15439]
### 联系方式

内部郭灶鹏

### MeterSphere 版本

1.20.9LTS

### 使用外置数据库

否

### 问题描述

测试计划生成的报告 
1、点击分享  
2、打开分享报告的链接；
3、点击左侧目录里面的子项
异常结果：  无法实现快速跳转。
![1656831057984](https://user-images.githubusercontent.com/30264974/177028595-ff57ee5f-32e1-4628-abc6-ea1d756947af.jpg)
![1656831179413](https://user-images.githubusercontent.com/30264974/177028687-4ec29854-af57-491d-80d4-3e0e7e4c9853.jpg)
![1656831179426](https://user-images.githubusercontent.com/30264974/177028694-7810bec4-1b01-45c1-b6bd-f0f6d008e49e.jpg)

### 重现步骤

如上，问题描述

**Comment by ltfit** [comment]
感谢反馈 这个后续优化下

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
