### ISSUE TITLE
[BUG]使用JavaScript去处理数据再使用putObject参数不对

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15443]
### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 使用外置数据库

是

### 问题描述

使用如下脚本后在引用发现请求参数不对
![image](https://user-images.githubusercontent.com/40486003/177068960-a9e09225-400a-4841-86ca-2a31dd3f6c6e.png)
![image](https://user-images.githubusercontent.com/40486003/177068942-291f419c-8bd9-421c-abeb-1dfe7c2aedff.png)

### 重现步骤

```JavaScript
var ShopInfoList = [{"shop_id": "CX0004","shop_name": ""},{"shop_id": "AA0193","shop_name": ""}];
for (let index = 0; index < ShopInfoList.length; index++) {
    shop_info = ShopInfoList[index]
    if (shop_info["shop_id"] == "CX0004"){
        delete ShopInfoList[index];
    }
}
// console.info(ShopInfoList)
vars.putObject("ShopInfoList",ShopInfoList)
```

**Comment by zyyfit** [comment]
这应该是引用到了吧，只是他是一个对象，所以输出成那样了，你要作为字符串引用的话，也要处理一下
![image](https://user-images.githubusercontent.com/73461316/177125316-90ec1067-3c4f-4bf9-ad78-e95491dc1826.png)
