### ISSUE TITLE
[BUG]稳定性测试，按迭代次数，持续4个小时，data-streamig 出现瓶颈，同一任务越往后汇总一条数据耗时越长，实际收集完报告需要15个小时

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15442]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

是

### 问题描述

现象1：跑一个持续4个小时的稳定性测试，16点开始跑，到第二天凌晨6点，查看data-streamig日志，依然在计算和汇总报告，同一任务越往后汇总一条数据耗时越长。

<img width="1439" alt="截图" src="https://user-images.githubusercontent.com/30038088/177045849-fcf1a52f-9e9f-4c1c-8077-7133523998a2.png">

现象2：期间开始了 mysql 慢查询日志，查看慢查询日志，发现有 耗时 十几秒的 慢sql ，但是 复制该sql直接到数据库里查询，实际查询时间很短。
![image](https://user-images.githubusercontent.com/30038088/177046222-d731236a-6cc9-44b1-8338-2284a9f77dec.png)

### 重现步骤

环境：
3个 kafka，配置 32c48g
5个 data-streaming 配置 32c48g,其中3个和 kafka 在一台机器上

**Comment by zhangzhaox** [comment]
环境：
3个 kafka，配置 32c48g
5个 data-streaming 配置 32c48g,其中3个和 kafka 在一台机器上
@shenkaibo 这个架构 如何配置   并行或集群?

**Comment by shenkaibo** [comment]
> 环境： 3个 kafka，配置 32c48g 5个 data-streaming 配置 32c48g,其中3个和 kafka 在一台机器上 @shenkaibo 这个架构 如何配置 并行或集群?

集群可以参考在线文档 https://metersphere.io/docs/installation/pre_work/

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by luty2018** [comment]
配置不对导致
