### ISSUE TITLE
[FEATURE]建议加trim、ltrim、rtrim等常用函数

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1544]
**请描述您的需求或者改进建议.**
ms自带的是jmeter函数助手，函数里面一些常用的功能还需要加强，比如trim、ltrim、rtrim等；
目前只能通过beanshell来做，对于外包测试人员来说难度有点大；需要平台赋能给无代码能力的测试人员；

**请描述你建议的实现方案**
1.trim场景
cust_id 03440215987456321空格
CustID  03440215987456321
必须trim后比较字符串

${cust_id} == '${CustID}'函数定义：
value = vars.get("cust_id").trim();//只能自己先用beanshell做
result = "${CustID}".equals(value);
if (!result){
	msg = "assertion [${cust_id} == '${CustID}']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
}

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中

**Comment by luty2018** [comment]
很抱歉长时间没有回复， 目前系统有支持自定义代码片段， 类似这样的功能是否由有脚本能力的同学写到自定义代码片段里， 其他同学直接调用就行。
