### ISSUE TITLE
[BUG]CAS后边对应的登录认证系统的用户名不区分大小写，MS 平台登录区分用户名大小写，导致输入大写的用户名可以正常登录，但是权限不对

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15455]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

否

### 问题描述

CAS后边对应的登录认证系统的用户名不区分大小写，MS 平台登录区分用户名大小写，导致输入大写的用户名可以正常登录，但是权限不对

### 重现步骤

1.集成CAS，CAS 后边的登录认证 不区分用户名的大小写
2.CAS 默认创建的用户是小写（比如：kaibo），给该用户设置 系统管理员 权限，工作空间、项目管理员权限
3.在MS 登录界面，输入 Kaibo ，选择 CAS 登录，可以正常登录，但是 登录进去之后 只有系统管理员 权限，没有工作空间、项目的权限。

**Comment by zyyfit** [comment]
已确认忽略此问题
![image](https://user-images.githubusercontent.com/73461316/177133489-7929d3b9-0af5-40b8-b273-7450bd12fddb.png)
