### ISSUE TITLE
[FEATURE]函数助手添加format函数功能

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1545]
**现象**
请求OrderPrice 18.5
应答price 18.5000

如何对请求OrderPrice和应答price进行精准校验

**请描述您的需求或者改进建议.**

beanshell不支持String.format，需要用DecimalFormat类做格式化；建议平台加一个beanshell调试功能，我们都是在jmeter上调试beanshell脚本，但是发现“result = strPrice.equals(strOrderPrice);
if (!result){
	msg = "assertion ['${price}' == '${OrderPrice}']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
}” 这块jmeter不支持，贴到metersphere才支持；
于是就有个现象：在jmeter里面调试复杂的beanshell脚本，调试通后再贴到平台，如果平台能包一些函数，扩展函数助手，这样才能降低测试人员使用平台的难度。

**请描述你建议的实现方案**

import java.text.DecimalFormat;

DecimalFormat df = new DecimalFormat( "0.00000" );//只能自己先用beanshell做
value = vars.get("price");
Float price = Float.parseFloat(vars.get("price").trim());
Float orderPrice = Float.parseFloat(vars.get("OrderPrice").trim());
String strPrice = df.format(price);
String strOrderPrice = df.format(orderPrice);

result = strPrice.equals(strOrderPrice);
if (!result){
	msg = "assertion ['${price}' == '${OrderPrice}']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
}

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中

**Comment by luty2018** [comment]
建议升级到v3.0使用， 谢谢！
