### ISSUE TITLE
[BUG]Jmeter进程和计算小程序进程都还在（不采用后置监听），但是 jmeter 日志不更新了，导致收集了一堆空 content 的消息到kafka里边，data-streaming 也持续的消费，报告也无法结束

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15451]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.7-lts

### 使用外置数据库

否

### 问题描述

Jmeter进程和计算小程序进程都还在（不采用后置监听），但是 jmeter 日志不更新了，导致收集了一堆空 content 的消息到kafka里边，data-streaming 也持续的消费，报告也无法结束

### 重现步骤

1.4个线程组，每个线程组300并发，迭代100000次，持续4个小时
![image](https://user-images.githubusercontent.com/30038088/177075994-6277a46c-3443-4801-a87d-6e377948da3a.png)
2.开始时间：2022-07-04 00:08:02
到 2022-07-04 11:24 看 jmeter 容器依然在，
![image](https://user-images.githubusercontent.com/30038088/177076129-7471c1f4-df4a-4ce4-bb10-a01db106bf59.png)
3.进到jmeter 内部 查看 jmeter 进程和计算小程序进程 都在
![image](https://user-images.githubusercontent.com/30038088/177076577-bdbd1495-c75e-4a45-9f79-88351a91af2b.png)

4.查看 jmeter 日志，到2022-07-04 04:09:35 日志不再更新，可见 jmeter 正常执行结束，但是进程没有删除、
![image](https://user-images.githubusercontent.com/30038088/177076594-b2ac0a7c-622c-4a23-80c7-bc13752e935d.png)

**Comment by fit2cloud-yangxiaoyan** [comment]
[带事务通多个.jmx.zip](https://github.com/metersphere/metersphere/files/9037901/jmx.zip)
发现问题的脚本

**Comment by zyyfit** [comment]
2.4.0版本已解决
