### ISSUE TITLE
[BUG]测试计划定时执行，场景报告running状态结束不了

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#15467]
### MeterSphere 版本

v1.20.9lts

### 使用外置数据库

是

### 问题描述

有18个测试计划，定时执行，执行周期分为1分钟、3分钟和五分钟，18个测试计划一共关联了1600个场景，执行过程发现有场景报告一直处于running状态无法结束的情况：
1.场景报告截图：
<img width="803" alt="截屏2022-07-04 下午10 00 56" src="https://user-images.githubusercontent.com/34637801/177170230-0aff3116-e7f8-4467-846f-462f56552c3a.png">
2.node-controller的ms-jmeter-run-log.log截图:
<img width="1122" alt="截屏2022-07-04 下午4 53 04" src="https://user-images.githubusercontent.com/34637801/177119404-18dbb7c5-0aed-4ff7-a8d4-6d7e761ecec0.png">
<img width="1188" alt="截屏2022-07-04 下午4 54 01" src="https://user-images.githubusercontent.com/34637801/177119572-f81a663c-1a08-4b6d-9d56-df4838b82d34.png">
<img width="1104" alt="截屏2022-07-04 下午4 54 40" src="https://user-images.githubusercontent.com/34637801/177119731-ee928526-e1fa-46df-ba9b-f5b8e96a6e3c.png">
<img width="1164" alt="截屏2022-07-04 下午4 55 02" src="https://user-images.githubusercontent.com/34637801/177119788-b454b662-c306-443d-a074-d56fb4455b30.png">
<img width="1206" alt="截屏2022-07-04 下午4 55 20" src="https://user-images.githubusercontent.com/34637801/177119840-2340d657-6d3c-460c-a9cc-877237f65816.png">
3.ms-server的ms-jmeter-run-log.log截图:
<img width="1023" alt="截屏2022-07-04 下午4 57 15" src="https://user-images.githubusercontent.com/34637801/177120224-ed6ba81c-3c29-4c24-ac9c-4c9f9a31d59f.png">

### 重现步骤

1.准备500个场景
2.准备18个测试计划分别重复关联这500个场景，达到18个计划关联的总量为1600个左右；
3.执行时间为2个测试计划为2分钟执行一次，10个测试计划为3分钟执行一次，8个测试计划执行时间为5分钟执行一次
注意：该问题无法稳定复现

### 期待的正确结果

场景正常执行，报告状态正常结束；

**Comment by zyyfit** [comment]
重复，另外，无法停止这个问题我们复现过，正在修复中
https://github.com/metersphere/metersphere/issues/15438

**Comment by pengzhengyou** [comment]
和15438 这个问题不是同一个问题 这个running结果后 等待几个小时后 报告里的内容是正确的 但是15438这个问题  是报告内容为空 请仔细看清问题描述

**Comment by zyyfit** [comment]
已修复
