### ISSUE TITLE
[FEATURE]jenkins插件传参支持

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1546]
**请描述您的需求或者改进建议.**
目前jenkins插件只是简单的调用，不支持传参调用，建议加一下比如 系统日期 sysdate

证券交易系统每天需要切日，需要从平台获取系统日期；或者通过jenkins传递的日期来切日；

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
收到，感谢您的建议，我们内部讨论下再反馈。
