### ISSUE TITLE
[FEATURE]ms平台连接数据库兼容性不够，导致相同的数据库版本，一个可以连接成功一个连接不上

### ISSUE THREAD

**Issue by linda0007** [metersphere/metersphere#15468]
### MeterSphere 版本

v1.20.3-lts-b3

### 请描述您的需求或者改进建议

和Navicat一致，Navicat可以连接成功的数据库，ms也可以连接成功

### 请描述你建议的实现方案

和Navicat一致，使用Navicat一样的数据库驱动

### 附加信息

ms连接数据库失败的报错日志：[ms.txt](https://github.com/metersphere/metersphere/files/9037997/ms.txt)
ms连接数据库失败的截图：
![企业微信截图_1655434722500](https://user-images.githubusercontent.com/20278174/177120881-dad372a1-5dda-4283-9e8b-b0f1dccb7d4f.png)
ms连接数据库失败的数据库版本截图：![image](https://user-images.githubusercontent.com/20278174/177121299-011e33cb-6890-44b5-bce2-15860020dbe0.png)
ms连接数据库成功的数据库版本截图：
![image](https://user-images.githubusercontent.com/20278174/177121438-b7e740d9-5598-415d-8415-ed1c024e2da5.png)

**Comment by Hyyfit** [comment]
您好哦，MySQL的5.6，5.7，8.0版本的是支持的。

**Comment by linda0007** [comment]
我看现在ms是v1.20.9-lts，没有8.0版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月6日(周三) 上午10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]ms平台连接数据库兼容性不够，导致相同的数据库版本，一个可以连接成功一个连接不上 (Issue #15468)




 
您好哦，MySQL的5.6，5.7，8.0版本的是支持的。

**Comment by Hyyfit** [comment]
您好呀～
1.回复里的版本指的是MySQL的版本。my对MySQL的5.6、5.8、8.0的版本是支持的；
2.您截图的两个版本是一样的，都是5.6，所以连接失败可能是其他的差异导致的；
3.如果还需要更多的技术支持，可以在微信交流群联系我们的技术支持人员，协助您排查问题。

**Comment by linda0007** [comment]
就是需要你们支持才提的需求呀，群里问了说是需求范围，不属于bug，现在又让我群里去问，处处踢皮球，所以这个问题是无解了是吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月7日(周四) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]ms平台连接数据库兼容性不够，导致相同的数据库版本，一个可以连接成功一个连接不上 (Issue #15468)




 
您好呀～
 1.回复里的版本指的是MySQL的版本。my对MySQL的5.6、5.8、8.0的版本是支持的；
 2.您截图的两个版本是一样的，都是5.6，所以连接失败可能是其他的差异导致的；
 3.如果还需要更多的技术支持，可以在微信交流群联系我们的技术支持人员，协助您排查问题。

**Comment by Hyyfit** [comment]
您好，根据您提供的信息，无法确认是什么问题导致的失败；
您加一下我的微信，我这边帮您看一下，如果确定不支持的功能，会按需求处理的。
<img width="318" alt="image" src="https://user-images.githubusercontent.com/95834771/177683503-2be07642-561a-4e2a-9349-956477782178.png">
