### ISSUE TITLE
[FEATURE]平台能否支持thrift协议的测试

### ISSUE THREAD

**Issue by xinmingwanjob** [metersphere/metersphere#1547]
**描述**
Thrift 是一个软件框架（远程过程调用框架），用来进行可扩展且跨语言的服务的开发。它结合了功能强大的软件堆栈和代码生成引 擎，以构建在 C++, Java, Python, PHP, Ruby, Erlang, Perl, Haskell, C#, Cocoa, JavaScript, Node.js, Smalltalk, and OCaml 这些编程语言间无缝结合的、高效的服务。

thrift最初由facebook开发，07年四月开放源码，08年5月进入apache孵化器，现在是 Apache 基金会的顶级项目

thrift允许你定义一个简单的定义文件中的数据类型和服务接口，以作为输入文件，编译器生成代码用来方便地生成RPC客户端和服务器通信的无缝跨编程语言。。

著名的 Key-Value 存储服务器 Cassandra 就是使用 Thrift 作为其客户端API的。

**请描述您的需求或者改进建议.**

目前证券行业已有使用thrift进行新一代系统设计，需要平台支持

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
收到，感谢您的建议，我们内部讨论下再反馈。
