### ISSUE TITLE
[FEATURE] 性能测试场景高级设置建议超时时间参考浏览器默认时间设置120秒默认值

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#15477]
### MeterSphere 版本

v.1.19.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/82088551/177135577-3dbc127a-4bee-4183-af59-9f63517e5f60.png)
建议设置常规浏览器的默认超时时间，避免大多数情况没有设置的情况

**Comment by Hyyfit** [comment]
感谢反馈，待规划设计。
