### ISSUE TITLE
[QUESTION]数据库执行SQL查询时间，耗时

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#15474]
### 请描述您的问题

连接本地SQL，执行select  current_timestamp;  耗时118ms
最终查询结果时间和日志展示时间对比：操作时间（系统-操作日志）和查询出来的时间对不上
![image](https://user-images.githubusercontent.com/15188833/177126991-0e93c402-1e3b-4d5a-9e0f-1596dbfe0833.png)

执行时间：
![image](https://user-images.githubusercontent.com/15188833/177127095-419e0789-c7dc-475a-aed5-824529301ab5.png)

**Comment by Hyyfit** [comment]
这个是正常的。操作时间记录的是平台上的时间；系统返回的执行时间，是实际数据库执行的时间。所以会有时间上的差异。
