### ISSUE TITLE
[BUG] 接口定义的接口json-schema维护描述，在接口文档无显示

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#15476]
### MeterSphere 版本

1.20.4

### 使用外置数据库

否

### 问题描述

接口定义的接口json-schema维护描述，在接口文档无显示

### 重现步骤

1.接口定义维护好接口
2.在json-schema维护字段描述
3.切换接口文档无显示

### 期待的正确结果

切换接口文档会显示字段维护信息

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/177135217-3d6d6072-3e95-425c-8875-d9b21a50d91c.png)

![image](https://user-images.githubusercontent.com/45531073/177135062-acea7d6f-444b-4ec2-8d1c-3ab7e699111c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题已修复，请升级到较新版本
