### ISSUE TITLE
性能测试页存在极多项目名称，详见附件图

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#1549]
**MeterSphere 版本**
 MeterSphere 版本V1.7.3

**Bug 描述**
性能测试页存在极多项目名称

**期待的正确结果**
性能测试页只需接口名，无需项目名称

**截图**
![图片](https://user-images.githubusercontent.com/74084897/109610104-438b9080-7b67-11eb-9102-7b43d9af16d3.png)
![图片](https://user-images.githubusercontent.com/74084897/109610122-47b7ae00-7b67-11eb-83a1-8df17ac22dce.png)

**Comment by xulinde** [comment]
收到，后面版本优化下这里

**Comment by xulinde** [comment]
未复现该问题
