### ISSUE TITLE
[FEATURE]Class path contains multiple SLF4J bindings，建议保留logback，去除slf4j

### ISSUE THREAD

**Issue by imath60** [metersphere/metersphere#155]
**请描述您的需求或者改进建议.**
问题描述：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/imathliu/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/imathliu/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/imathliu/.m2/repository/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
改进建议：
保留logback,去除slf4j

**请描述你建议的实现方案**
pom.xml使用<exclusion>去除slf4j

**Comment by liuruibin** [comment]
POM已修改
