### ISSUE TITLE
[FEATURE]建议chrome录制插件增加对响应结果的录制

### ISSUE THREAD

**Issue by cyw16076** [metersphere/metersphere#1550]
**请描述您的需求或者改进建议.**
chrome录制插件录制时只录制了请求，导入系统后，不方便增加断言，尤其是需要登录状态的一些接口

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，该功能已在后续版本规划中

**Comment by wangzhen-fit2cloud** [comment]
由于 chrome 接口的限制，只有在开启了开发者工具的情况下才能获取到响应结果。暂时放弃该功能的规划。
