### ISSUE TITLE
[BUG] 同步jira缺陷后，环境中的图片预览未显示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#15514]
### 联系方式

18311441708

### MeterSphere 版本

1.20.9.lts

### 使用外置数据库

否

### 问题描述

同步jira缺陷后，环境中的图片预览未显示
![image](https://user-images.githubusercontent.com/103925124/177298681-98ebc248-03aa-49ee-9c5b-97e4487d88e4.png)
![1657013815(1)](https://user-images.githubusercontent.com/103925124/177298824-95f9b3f3-b4f7-468a-8e73-4c6933f22d3f.png)

### 重现步骤

使用jira-企业版 缺陷详情添加环境中有图片有文字

在ms中进行同步，预览环境，图片未显示

### 期待的正确结果

使用jira-企业版 同步缺陷后，预览环境，图片和文字均可渲染

**Comment by ltfit** [comment]
后续版本修复

**Comment by ltfit** [comment]
目前没有接口获取JIra富文本框的图片

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
