### ISSUE TITLE
[BUG]带事务控制器的脚本，按迭代次数跑，次数到了没有停止，实际按压测时长停止的

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#15528]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

带事务控制器的脚本，按迭代次数跑，次数到了没有停止，是按设置的压测的测试时长停止的

### 重现步骤

1、准备一个带事务控制器的脚本
2、一个并发迭代100次，压测时长设置10分钟
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/72729206/177458620-8d1bdd7b-c249-45f6-bc08-d61db5751ed3.png">
3、执行后看结果
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/72729206/177458644-23ee41b6-6a09-4d87-9068-e52b8ab58af0.png">

### 期待的正确结果

1、迭代次数和压测时长满足其中一个条件停止

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by zhangzhaox** [comment]
时长优先原则，覆盖循环次数
