### ISSUE TITLE
导入Postman脚本存在的问题

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#1552]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
简要描述您碰到的问题
postman取变量方式不是通用的，导入没有做相应转换
**Bug 重现步骤**
1.  导入Postman Collection v2.1 格式的 json 文件

**期待的正确结果**
正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/35896106/109633703-59a74a00-7b83-11eb-97b3-08cf2f10af08.png)

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35896106/109633720-63c94880-7b83-11eb-9302-5510721b0c87.png)

**Comment by xulinde** [comment]
收到，我们复现后再反馈
