### ISSUE TITLE
[BUG] 我的工作台/我的待办/缺陷管理 无法展示指派给当前MS账号的禅道缺陷（已将缺陷同步至测试跟踪缺陷管理）

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15527]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

问题描述：
我的工作台/我的待办/缺陷管理 无法展示指派给当前MS账号的禅道缺陷（已将缺陷同步至测试跟踪缺陷管理）

详情见下图：

- 已进行缺陷双向同步

![image](https://user-images.githubusercontent.com/92966838/177453741-932b68c9-306e-4611-aeb8-1fb14bf5ee6d.png)

- 缺陷已指定指派人为当前ms账号
![image](https://user-images.githubusercontent.com/92966838/177453943-7f3d9bce-8bb0-425e-9a3f-9d1eda7dd640.png)

- 当前ms账号个人信息中以配置禅道关联账号，并检验通过
![image](https://user-images.githubusercontent.com/92966838/177454056-4af5e200-e79a-41ed-bba5-d471c4f6162f.png)

- 我的工作台/我的待办/缺陷管理 无法展示指派给当前MS账号的禅道缺陷
![image](https://user-images.githubusercontent.com/92966838/177454153-4bc8dfb5-9b02-4adc-b9d2-ebf0ab4a6f0a.png)

### 重现步骤

1. 项目关联了禅道平台（开源版本 16.5）
2. ms和禅道缺陷已经进行双向同步
3. 缺陷指定指派人为当前ms账号/对应禅道账号
4. 查看我的待办/缺陷管理 无数据

### 期待的正确结果

能在待办列表中展示指派给当前账号的缺陷

**Comment by ltfit** [comment]
感谢反馈 后续版本修复下

**Comment by youliyuan-fit2cloud** [comment]
admin和administer 是两个用户，我的待办缺陷展示的是当前用户的
