### ISSUE TITLE
[BUG]导出的Excel用例没有执行后的结果

### ISSUE THREAD

**Issue by dfdfsxfdg** [metersphere/metersphere#15529]
### 联系方式

MeterSphere 交流群45

### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

导出测试用例没有执行结果、评审结果

### 重现步骤

执行或评审测试用例后，导出测试用例

### 期待的正确结果

导出的Excel中有用例的执行结果，评审结果

### 附加信息

![image](https://user-images.githubusercontent.com/108777713/177459718-05b3b80d-80cd-4732-b79b-20c579c1c8b2.png)

**Comment by ltfit** [comment]
你好 目前还不支持这些字段
