### ISSUE TITLE
postman中定义了全局变量，是否可以导入进来

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#1553]
**请描述您的需求或者改进建议.**

postman中定义了全局变量，是否可以导入进来

**请描述你建议的实现方案**
postman本身是可以支持全局变量导出为json文件的，MS平台项目环境配置里面增加一个导入按钮
![image](https://user-images.githubusercontent.com/35896106/109634721-8c057700-7b84-11eb-87ca-9dfdf76644ab.png)

![image](https://user-images.githubusercontent.com/35896106/109634618-68dac780-7b84-11eb-9c7c-ab75acdc5848.png)

**Comment by xulinde** [comment]
感谢您的建议，已在后续版本规划中
