### ISSUE TITLE
[BUG]通过Postman导入的接口自动化用例，在有前置脚本的情况下，导入至MS平台，显示的脚本类型为不存在的rhino

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15535]
### MeterSphere 版本

1.20.9lts

### 使用外置数据库

否

### 问题描述

通过Postman导入的接口自动化用例，在有前置脚本的情况下，导入至MS平台，显示的脚本类型为不存在的rhino

### 重现步骤

1.在postman上编写接口用例，用例中有存在前置脚本，并将编写好的用例保存并上传至MS平台，查看MS导入postman用例的导入详情；

### 期待的正确结果

1.导入成功后，前置操作脚本类型显示为：javascript；
（备注：在前置脚本导入平台未作转换时，建议增加“不同平台语法存在不兼容”的提示，便于用户提前识别）具体见截图二

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/177464752-91fd575c-cbe3-475d-9d52-f4b74a94f545.png)

![image](https://user-images.githubusercontent.com/92150453/177464698-e17f0e0f-3c13-4d02-b398-b08e185d8e56.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.10-lts已优化～ms平台不支持运行postman的脚本，现已去除解析psotman的前后置脚本和断言的方法
