### ISSUE TITLE
[BUG]添加接口测试断言脚本的时候输入框只显示一个小条条

### ISSUE THREAD

**Issue by strawberry-user** [metersphere/metersphere#1554]
**MeterSphere 版本**
v1.7.3-2b9713b1

**Bug 描述**
添加接口测试断言脚本的时候输入框只显示一个小条条

**Bug 重现步骤**
添加接口测试断言脚本

**期待的正确结果**
输入框正常显示

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/63221605/109660330-ad299000-7ba3-11eb-8a57-c982cbd8fb0a.png)

**Comment by xulinde** [comment]
您好，未复现该问题。请升级到最新版本复测下
![image](https://user-images.githubusercontent.com/64065190/109745237-8785a080-7c0e-11eb-98bd-4d8a6069c092.png)
