### ISSUE TITLE
[BUG] TEST TCP请求时，请求内容无法正确展示请求地址等

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15549]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

问题描述：
TEST TCP请求时，请求内容无法正确展示请求地址等

截图：
环境配置
![image](https://user-images.githubusercontent.com/92966838/177491413-abd7287b-b4fd-488c-85a9-f4171c496c0c.png)

响应码提示200，但是请求内容中无法展示当前的运行环境地址
![image](https://user-images.githubusercontent.com/92966838/177491262-ce251424-9d6e-4748-86e7-30a0a3860335.png)

### 重现步骤

1.配置tcp环境变量
2.发起tcp调试
3.查看本次请求的请求内容

### 期待的正确结果

正确展示tcp的地址以及完整的请求内容

**Comment by xulinde** [comment]
jmeter就是只展示了请求内容，我们底层用的jmeter
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/64065190/177525657-e6c9bd17-9290-4f28-aaf5-450161f4ee48.png">

**Comment by Fit2CloundGhh** [comment]
咱们考虑在这块做补充吗，就跟咱们http的展示一样，不然用户这边使用起来 基本上都会有这个疑问。jmeter的结果树 虽然也没有，但是他们的ui操作起来，不会让人有误解
             
         
     
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Jul 6, 2022 06:06 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] [BUG] TEST TCP请求时，请求内容无法正确展示请求地址等 (Issue #15549)

&nbsp;



 
jmeter就是只展示了请求内容，我们底层用的jmeter

**Comment by gaohonghai** [comment]
咱们不考虑基于Jmeter优化一下吗【期待脸】，希望能和http这块的展示一致，体验起来怪怪的

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
