### ISSUE TITLE
[BUG]【企业用户】SQL中使用表名大小写导致外置数据库查询出错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#15550]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.8-LTS

### 使用外置数据库

是

### 问题描述

使用自己DBA提供的数据库，无法设置忽略表名大小写，而某些接口对应的sql中表名采用大写的，导致查询失败
例如：
/api/testcase/list/1/10

### 重现步骤

使用自己DBA提供的数据库，无法设置忽略表名大小写，而某些接口对应的sql中表名采用大写的，导致查询失败
例如：
/api/testcase/list/1/10

### 附加信息

<img width="770" alt="image" src="https://user-images.githubusercontent.com/32027713/177491928-b285bf47-ccbf-437c-8c7d-7adaf390d224.png">

**Comment by dashenyucainiao** [comment]
sql是在代码里面的,我如何修改sql呢？

**Comment by maninhill** [comment]
@fit2-zhao 这个帮忙统一检查下，统一解决。后面统一规范，sql 语句全部小写。

**Comment by xulinde** [comment]
v1.20.10-lts已优化，统一成小写
