### ISSUE TITLE
[BUG]禅道缺陷平台状态置为“已关闭”之后，ms无法进行状态同步

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15551]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

- 问题描述：

禅道缺陷平台状态置为“已关闭”之后，ms无法进行状态同步

- 禅道版本
开源版 12.5.3、开源版 16.5

### 重现步骤

1. 已成功进行双向同步
![image](https://user-images.githubusercontent.com/92966838/177496484-112a3ba5-20b1-479b-9e24-cd58db70d2aa.png)
![image](https://user-images.githubusercontent.com/92966838/177496535-31260283-db53-4b46-b2e3-67bf75522593.png)

2.在禅道上将缺陷置为“已解决”，ms通过“同步缺陷”按钮可以成功同步缺陷状态
![image](https://user-images.githubusercontent.com/92966838/177497139-83433d7d-fc9b-41ff-805a-0cb61403585b.png)
![image](https://user-images.githubusercontent.com/92966838/177497201-ec228a63-59fd-463e-b526-7ef8582f8e23.png)

3.在禅道上将缺陷置为“已关闭”，ms无法同步成功
![image](https://user-images.githubusercontent.com/92966838/177497926-b544d430-9a5c-4c35-aee6-e2c3ae82c372.png)
![image](https://user-images.githubusercontent.com/92966838/177498010-886dd8ab-5c9d-43f2-99f9-a35239f12b24.png)

### 期待的正确结果

能够成功同步禅道修改后的缺陷状态

**Comment by ltfit** [comment]
你好，我这边测试开源版12.5.3同步关闭状态是正常的，我联系你确认下。
