### ISSUE TITLE
[BUG]接口自动化批量生成依赖关系图时，当选择所有数据时，生成失败并报错

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15559]
### MeterSphere 版本

1.20.9lts

### 使用外置数据库

否

### 问题描述

接口自动化批量生成依赖关系图时，当选择所有数据时，生成失败并报错

### 重现步骤

1.在接口测试-接口自动化页面，勾选“选择所有数据”，并点击“生成依赖关系”；

### 期待的正确结果

1.依赖关系图打开成功并显示正确；

### 附加信息

![1657101458438](https://user-images.githubusercontent.com/92150453/177524639-3e25d104-0370-4bf4-81ae-1f0fd0e642ba.jpg)
![1657101458453](https://user-images.githubusercontent.com/92150453/177524655-5c63663b-6b50-49a2-9eb2-0a2e739d6e98.jpg)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.20.10-lts已修复～
