### ISSUE TITLE
[FEATURE]增加基于失败的自动化用例创建缺陷的功能

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#15552]
### MeterSphere 版本

1.20.5

### 请描述您的需求或者改进建议

当前仅支持基于功能用例创建bug，对于接口/UI/性能等自动化用例，无法基于它们执行失败的结果创建缺陷，而实际中是存在这个使用场景的，自动化执行失败测试人员分析后认为是代码问题，创建缺陷并指派开发人员分析解决。

### 请描述你建议的实现方案

建议增加基于自动化测试用例执行结果创建bug的功能，并且创建的bug能够自动采集一些执行结果信息填充到bug描述中，便于后续开发人员排查。

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
