### ISSUE TITLE
[BUG] 无法上传postman保存的v2.1 collection json文件

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1555]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
本地部署方式： 1.7.3 (v1.7.3-2b9713b1)
helm chart 部署方式： registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:master  (master-bab80c4e)

**Bug 描述**
都无法上传postman保存的v2.1 collection json文件

**Bug 重现步骤**
1.  从postman 导出v2.1 collection json 
2. 尝试导入到metersphere
3. 导入失败报错： Parse data error.

**期待的正确结果**
成功导入

**截图**
![image](https://user-images.githubusercontent.com/38770463/109734199-9151d880-7bfb-11eb-8daf-b89211e808b9.png)

**Comment by wonderfulwxw** [comment]
可能的原因： 是否跟带有前后置脚本有关？

试了下 用不带前后置脚本的collection，可以上传成功。

**Comment by xulinde** [comment]
您好，未复现该问题，文件是带前后置脚本的。方便发下您的文件，我们复现下吗

**Comment by wonderfulwxw** [comment]
collectoion里有超过100条接口，由于涉及安全问题，不方便发与你。
这是日志：（但看不出具体是由于什么解析出错）
![image](https://user-images.githubusercontent.com/38770463/110106709-f7e61a80-7de4-11eb-8dbe-6eb1d2cf2a17.png)
![image](https://user-images.githubusercontent.com/38770463/110106816-19470680-7de5-11eb-8c2c-3eefa2ce53f3.png)

**Comment by wonderfulwxw** [comment]
再次查了一下
我的collection是之前导出的，怀疑是旧版postman 导出的，上传会失败。

我又导出了一个新的进行对比（目前postman是8.0）， 发现新的collection json中对每个请求加了一个id, raw -option，protocolProfileBehavior 等字段

![image](https://user-images.githubusercontent.com/38770463/110109495-81e3b280-7de8-11eb-9762-70c30714cbd3.png)

![image](https://user-images.githubusercontent.com/38770463/110109442-6aa4c500-7de8-11eb-9208-c77e1b51a6d3.png)

![image](https://user-images.githubusercontent.com/38770463/110109463-73959680-7de8-11eb-847a-6cfab438363d.png)
