### ISSUE TITLE
[BUG]请求头中的Content-Type未正常设置

### ISSUE THREAD

**Issue by forestyoung23** [metersphere/metersphere#15566]
### MeterSphere 版本

v1.20.4-lts

### 使用外置数据库

是

### 问题描述

使用JMeter格式导入接口后，在没有全局设置项目环境请求头的情况下，添加接口请求头执行请求，并未按设置的请求头发送请求
<img width="1827" alt="image" src="https://user-images.githubusercontent.com/62150631/177534216-aa38f1e9-ea68-407e-bd65-e7ebf38e0c94.png">

### 重现步骤

**该问题为通过JMeter格式导入的接口case出现，其它场景暂未测试**
1.添加接口请求头为Content-Type=application/json
2.最终发起请求的接口的请求头Content-Type: text/plain; charset=UTF-8

**Comment by xulinde** [comment]
使用v1.20.9未复现该问题，建议您升级到最新版本，如有问题再反馈～
