### ISSUE TITLE
[BUG]性能测试beanshell断言，失败后，错误记录返回的引号显示为&quot

### ISSUE THREAD

**Issue by hmilyjch** [metersphere/metersphere#1556]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.1-66e9f091
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  jmeter脚本使用beanshell取交易的返回
2.  返回内容包含双引号
3.  在页面中type of error中，显示为&quot

**期待的正确结果**
希望这里显示为正常的引号

**截图**
![image](https://user-images.githubusercontent.com/43428113/109738379-b0079d80-7c02-11eb-8593-caf29e66c2ce.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，我们下个版本修复该问题~

**Comment by youliyuan-fit2cloud** [comment]
v1.8版本已修复
