### ISSUE TITLE
[BUG]jmeter禁用的线程组上传后显示不正确

### ISSUE THREAD

**Issue by hmilyjch** [metersphere/metersphere#1557]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.1-66e9f091
**Bug 描述**
jmeter禁用的线程组上传后显示为启用

**Bug 重现步骤**
1.  jmeter有多个线程组
2. 禁用部分线程组
3. 上传后变启用【还有的线程组上传后页面不显示了，如图，第一个线程组】

**期待的正确结果**
正确情况下应该是什么样的？
上传后，禁用用灰色显示，有按钮可以控制禁用还是启用

**截图**
![image](https://user-images.githubusercontent.com/43428113/109740907-024abd80-7c07-11eb-99c5-0954b5a415b3.png)

**Comment by hmilyjch** [comment]
第一个是setup线程组，是否setup线程组不显示呢？

**Comment by zyyfit** [comment]
您好，最新的1.9.0已有新版接口界面，也支持setUp线程组导入了
