### ISSUE TITLE
[BUG]管理员账号——当新增加一个项目后，管理员账号看不到该项目，必须要手动给管理员添加该项目权限才可看到，不合理应该默认所有，新增项目自动增加权限

### ISSUE THREAD

**Issue by chasshenzhen1995** [metersphere/metersphere#15578]
### 联系方式

979608943@qq.com

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

当新增加一个项目后，管理员账号看不到该项目，必须要手动给管理员添加该项目权限才可看到，不合理应该默认所有，新增项目自动增加权限

### 重现步骤

新增一个项目，管理器去操作该项目

### 期待的正确结果

应该默认所有，新增项目自动增加权限

**Comment by youliyuan-fit2cloud** [comment]
你好，admin管理员是系统级角色的系统管理员，项目级角色的权限包括项目管理员和项目成员，还有工作空间级角色，三者之间虽然是层级关系，但是权限设置是不同的。
系统级的权限只是包括系统设置中的权限，例如，创建用户，创建工作空间等；
工作空间权限用户只包括工作空间下的设置权限。
同样的，项目级的用户只能操作项目内可以做的事。
任何项目都需要手动添加成员到该项目中，成为项目管理员或项目成员。
