### ISSUE TITLE
[BUG]测试跟踪——功能用例——脑图编写后，保存。之后重新打开就乱了，并没有按照编写脑图时顺序展示

### ISSUE THREAD

**Issue by chasshenzhen1995** [metersphere/metersphere#15589]
### 联系方式

979608943@qq.com

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

脑图编写后，保存。之后重新打开就乱了，并没有按照编写脑图时顺序展示，目前脑图展示都是乱的

### 重现步骤

如标题

### 期待的正确结果

按照脑图的顺序 ，保持原样

**Comment by ltfit** [comment]
你好我这边没有复现出来，方便录个视频吗，或者升级到最新版本在看下。

**Comment by ltfit** [comment]
qq联系你了通过下
