### ISSUE TITLE
[BUG]TCP 请求 选择 GBK 编码进行调试，编码未生效

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15582]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

问题描述：
TCP 请求 TEST 选择 GBK 编码未生效，发出的请求报文仍是 utf-8 编码格式，导致 server 端 报文解析失败

### 重现步骤

1、设置请求编码格式，并发起请求
![image](https://user-images.githubusercontent.com/92966838/177702774-12bab35e-ed92-41e3-aa29-73feb5659fe5.png)

2、server端报错
![image](https://user-images.githubusercontent.com/92966838/177702850-689feb09-7d48-4723-9665-7ac5cc274e97.png)

### 期待的正确结果

以选择的编码进行报文编码

**Comment by youliyuan-fit2cloud** [comment]
你好，这个控制台日志是 平台的编码格式utf-8，是正确的。
服务端日志是xml格式错误，和这个编码没关系。

**Comment by gaohonghai** [comment]
同样的脚本在jmeter是可以的，而且同样的控制台日志，jmeter的编码提示的是GBK：
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/92966838/177905589-bea59113-92e5-4603-b1ed-767cc526ebd0.png">
详情如下：

ms详细步骤：
1、tcp请求的前置处理
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/92966838/177904099-0418df79-8de7-4cc8-bb5d-0f4e799a59c9.png">

2、引用参数
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/92966838/177904976-7fbbbb1d-304e-4727-a73b-25552e12651c.png">

3、发起tcp请求后的请求内容（已经成功取到参数）
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/92966838/177904251-ee8c771c-d263-4ebf-a9ae-0a97e72332a2.png">

4、控制台报错
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/92966838/177903928-503f01e8-b23a-4e3c-8bae-af586bf6d739.png">

Jmeter详细步骤：
1、tcp请求的前置处理
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/92966838/177904580-e9666f1a-8822-48b4-bfeb-f3c110de3259.png">

2、引用参数
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/92966838/177904917-a41df8fd-e25f-4205-bd2c-44cea4c3b913.png">

3、发起tcp请求的请求内容
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/92966838/177905076-9af0f777-ebfe-4f37-94e7-106845b74b6d.png">

4、控制台正确返回值，**同时提示平台编码为GBK**
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/92966838/177905155-f544593c-333a-4b4e-8c78-795204b221f6.png">

Jmeter和MS请求参数中的xml文件经过比对 没有问题
jmeter：
`<?xml version="1.0" encoding="utf-8"?>

<INSU>
  <MAIN>
    <BANK_DATE>20220704</BANK_DATE>
    <BANK_CODE>05</BANK_CODE>
    <ZONENO>11</ZONENO>
    <BRNO>3110010101</BRNO>
    <TELLERNO>20220525</TELLERNO>
    <TRANSRNO>CIB1656917144256</TRANSRNO>
    <FUNCTIONFLAG>10</FUNCTIONFLAG>
    <INSUID>0026Test</INSUID>
    <INSUTYPE/>
    <BRNONAME>兴业银行总行营业部Test</BRNONAME>
    <BRNOCERTCODE/>
    <MARKETER_ID/>
    <MARKETER_NAME/>
    <MARKETER_CERTCODE/>
    <MARKETER_CERTEXPIRY/>
    <CHANNEL>4</CHANNEL>
    <APPLYNO/>
    <TB_DATE>20220704</TB_DATE>
    <PAYNAME>远远</PAYNAME>
    <PAYACC>62148357196100579</PAYACC>
    <PAYMETHOD/>
    <PAYMODE/>
    <SENDMETHOD/>
    <INSU_SPEC/>
    <PASSWORD/>
    <BD_PRINT_NO/>
    <FP_PRINT_NO/>
    <TEMP/>
    <REMARK/>
  </MAIN>
  <HEALTH_NOTICE>
    <CAREER_ITEM/>
    <HEALTHY_ITEM/>
    <NOTICE_ITEM>0</NOTICE_ITEM>
  </HEALTH_NOTICE>
  <PRODUCTS>
    <PRODUCT>
      <PRODUCTID>NW0090</PRODUCTID>
      <MAINPRODUCTID>NW0090</MAINPRODUCTID>
      <AMT_UNIT/>
      <CHARGE_PERIOD>2</CHARGE_PERIOD>
      <CHARGE_YEAR>5</CHARGE_YEAR>
      <COVERAGE_PERIOD>1</COVERAGE_PERIOD>
      <COVERAGE_YEAR/>
      <PREMIUM>300000</PREMIUM>
      <AMNT/>
      <DVDMETHOD>2</DVDMETHOD>
      <ALFLAG>2</ALFLAG>
      <PT_TEMP/>
      <PT_REMARK/>
    </PRODUCT>
  </PRODUCTS>
  <TBR>
    <TBR_TAX_CLASSIFICATION/>
    <TBR_TAX_RSN/>
    <TBR_NATIVEPLACE>344</TBR_NATIVEPLACE>
    <TBR_BBR_RELA>1</TBR_BBR_RELA>
    <TBR_OCCUTYPE>H0101003</TBR_OCCUTYPE>
    <TBR_DOSMOKE/>
    <TBR_NAME>远远</TBR_NAME>
    <TBR_SEX>0</TBR_SEX>
    <TBR_BIRTH>1994-08-23</TBR_BIRTH>
    <TBR_IDTYPE>6</TBR_IDTYPE>
    <TBR_IDNO>810000199408230021</TBR_IDNO>
    <TBR_IDEFFSTARTDATE>20220704</TBR_IDEFFSTARTDATE>
    <TBR_IDEFFENDDATE>20220803</TBR_IDEFFENDDATE>
    <TBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</TBR_ADDR>
    <TBR_POSTCODE>000000</TBR_POSTCODE>
    <TBR_MOBILE>13543339240</TBR_MOBILE>
    <TBR_REVENUE>500000</TBR_REVENUE>
    <TBR_RESIDENTS/>
    <TBR_TEMP>13543339249@139.com</TBR_TEMP>
    <TBR_REMARK/>
    <TBR_TEL/>
    <TBR_HOMEINCOME>1000000</TBR_HOMEINCOME>
    <TBR_WORK_UNIT/>
    <TBR_HEIGHT/>
    <TBR_WEIGHT/>
    <TBR_OPENBANK/>
    <TBR_STATEMENT>1</TBR_STATEMENT>
    <INSPREM_BDGT_AMT/>
    <TBR_MARRY_STS/>
  </TBR>
  <BBR>
    <BBR_NATIVEPLACE>344</BBR_NATIVEPLACE>
    <BBR_OCCUTYPE>H0101003</BBR_OCCUTYPE>
    <BBR_DOSMOKE/>
    <BBR_NAME>远远</BBR_NAME>
    <BBR_SEX>0</BBR_SEX>
    <BBR_BIRTH>1994-08-23</BBR_BIRTH>
    <BBR_AGE>27</BBR_AGE>
    <BBR_IDTYPE>6</BBR_IDTYPE>
    <BBR_IDNO>810000199408230021</BBR_IDNO>
    <BBR_IDEFFSTARTDATE>20220704</BBR_IDEFFSTARTDATE>
    <BBR_IDEFFENDDATE>20220803</BBR_IDEFFENDDATE>
    <BBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</BBR_ADDR>
    <BBR_POSTCODE>000000</BBR_POSTCODE>
    <BBR_MOBILE>13543339240</BBR_MOBILE>
    <BBR_REVENUE>500000</BBR_REVENUE>
    <BBR_REGISTER/>
    <BBR_TEL/>
    <BBR_TEMP/>
    <BBR_WORK_UNIT/>
    <BBR_HEIGHT/>
    <BBR_WEIGHT/>
    <BBR_MARRY_STS/>
    <BBR_REMARK/>
  </BBR>
  <SYRS>
    <SYR>
      <SYR_NAME>蹦蹦</SYR_NAME>
      <SYR_SEX>1</SYR_SEX>
      <SYR_PCT>100</SYR_PCT>
      <SYR_BBR_RELA>0</SYR_BBR_RELA>
      <SYR_BIRTH>19720101</SYR_BIRTH>
      <SYR_IDTYPE>1</SYR_IDTYPE>
      <SYR_IDNO>110101197201010993</SYR_IDNO>
      <SYR_IDEFFSTARTDATE/>
      <SYR_IDEFFENDDATE>20240101</SYR_IDEFFENDDATE>
      <SYR_NATIVEPLACE/>
      <SYR_TEMP>1</SYR_TEMP>
      <SYR_REMARK/>
    </SYR>
  </SYRS>
</INSU>
`

metersphere：
`<?xml version="1.0" encoding="utf-8"?>

<INSU>
  <MAIN>
    <BANK_DATE>20220704</BANK_DATE>
    <BANK_CODE>05</BANK_CODE>
    <ZONENO>11</ZONENO>
    <BRNO>3110010101</BRNO>
    <TELLERNO>20220525</TELLERNO>
    <TRANSRNO>CIB1656917144256</TRANSRNO>
    <FUNCTIONFLAG>10</FUNCTIONFLAG>
    <INSUID>0026Test</INSUID>
    <INSUTYPE/>
    <BRNONAME>兴业银行总行营业部Test</BRNONAME>
    <BRNOCERTCODE/>
    <MARKETER_ID/>
    <MARKETER_NAME/>
    <MARKETER_CERTCODE/>
    <MARKETER_CERTEXPIRY/>
    <CHANNEL>4</CHANNEL>
    <APPLYNO/>
    <TB_DATE>20220704</TB_DATE>
    <PAYNAME>远远</PAYNAME>
    <PAYACC>62148357196100579</PAYACC>
    <PAYMETHOD/>
    <PAYMODE/>
    <SENDMETHOD/>
    <INSU_SPEC/>
    <PASSWORD/>
    <BD_PRINT_NO/>
    <FP_PRINT_NO/>
    <TEMP/>
    <REMARK/>
  </MAIN>
  <HEALTH_NOTICE>
    <CAREER_ITEM/>
    <HEALTHY_ITEM/>
    <NOTICE_ITEM>0</NOTICE_ITEM>
  </HEALTH_NOTICE>
  <PRODUCTS>
    <PRODUCT>
      <PRODUCTID>NW0090</PRODUCTID>
      <MAINPRODUCTID>NW0090</MAINPRODUCTID>
      <AMT_UNIT/>
      <CHARGE_PERIOD>2</CHARGE_PERIOD>
      <CHARGE_YEAR>5</CHARGE_YEAR>
      <COVERAGE_PERIOD>1</COVERAGE_PERIOD>
      <COVERAGE_YEAR/>
      <PREMIUM>300000</PREMIUM>
      <AMNT/>
      <DVDMETHOD>2</DVDMETHOD>
      <ALFLAG>2</ALFLAG>
      <PT_TEMP/>
      <PT_REMARK/>
    </PRODUCT>
  </PRODUCTS>
  <TBR>
    <TBR_TAX_CLASSIFICATION/>
    <TBR_TAX_RSN/>
    <TBR_NATIVEPLACE>344</TBR_NATIVEPLACE>
    <TBR_BBR_RELA>1</TBR_BBR_RELA>
    <TBR_OCCUTYPE>H0101003</TBR_OCCUTYPE>
    <TBR_DOSMOKE/>
    <TBR_NAME>远远</TBR_NAME>
    <TBR_SEX>0</TBR_SEX>
    <TBR_BIRTH>1994-08-23</TBR_BIRTH>
    <TBR_IDTYPE>6</TBR_IDTYPE>
    <TBR_IDNO>810000199408230021</TBR_IDNO>
    <TBR_IDEFFSTARTDATE>20220704</TBR_IDEFFSTARTDATE>
    <TBR_IDEFFENDDATE>20220803</TBR_IDEFFENDDATE>
    <TBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</TBR_ADDR>
    <TBR_POSTCODE>000000</TBR_POSTCODE>
    <TBR_MOBILE>13543339240</TBR_MOBILE>
    <TBR_REVENUE>500000</TBR_REVENUE>
    <TBR_RESIDENTS/>
    <TBR_TEMP>13543339249@139.com</TBR_TEMP>
    <TBR_REMARK/>
    <TBR_TEL/>
    <TBR_HOMEINCOME>1000000</TBR_HOMEINCOME>
    <TBR_WORK_UNIT/>
    <TBR_HEIGHT/>
    <TBR_WEIGHT/>
    <TBR_OPENBANK/>
    <TBR_STATEMENT>1</TBR_STATEMENT>
    <INSPREM_BDGT_AMT/>
    <TBR_MARRY_STS/>
  </TBR>
  <BBR>
    <BBR_NATIVEPLACE>344</BBR_NATIVEPLACE>
    <BBR_OCCUTYPE>H0101003</BBR_OCCUTYPE>
    <BBR_DOSMOKE/>
    <BBR_NAME>远远</BBR_NAME>
    <BBR_SEX>0</BBR_SEX>
    <BBR_BIRTH>1994-08-23</BBR_BIRTH>
    <BBR_AGE>27</BBR_AGE>
    <BBR_IDTYPE>6</BBR_IDTYPE>
    <BBR_IDNO>810000199408230021</BBR_IDNO>
    <BBR_IDEFFSTARTDATE>20220704</BBR_IDEFFSTARTDATE>
    <BBR_IDEFFENDDATE>20220803</BBR_IDEFFENDDATE>
    <BBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</BBR_ADDR>
    <BBR_POSTCODE>000000</BBR_POSTCODE>
    <BBR_MOBILE>13543339240</BBR_MOBILE>
    <BBR_REVENUE>500000</BBR_REVENUE>
    <BBR_REGISTER/>
    <BBR_TEL/>
    <BBR_TEMP/>
    <BBR_WORK_UNIT/>
    <BBR_HEIGHT/>
    <BBR_WEIGHT/>
    <BBR_MARRY_STS/>
    <BBR_REMARK/>
  </BBR>
  <SYRS>
    <SYR>
      <SYR_NAME>蹦蹦</SYR_NAME>
      <SYR_SEX>1</SYR_SEX>
      <SYR_PCT>100</SYR_PCT>
      <SYR_BBR_RELA>0</SYR_BBR_RELA>
      <SYR_BIRTH>19720101</SYR_BIRTH>
      <SYR_IDTYPE>1</SYR_IDTYPE>
      <SYR_IDNO>110101197201010993</SYR_IDNO>
      <SYR_IDEFFSTARTDATE/>
      <SYR_IDEFFENDDATE>20240101</SYR_IDEFFENDDATE>
      <SYR_NATIVEPLACE/>
      <SYR_TEMP>1</SYR_TEMP>
      <SYR_REMARK/>
    </SYR>
  </SYRS>
</INSU>
`

**Comment by gaohonghai** [comment]
Jmeter和MS请求参数中的xml文件经过比对 没有问题
jmeter：
<?xml version="1.0" encoding="utf-8"?>

<INSU>
  <MAIN>
    <BANK_DATE>20220704</BANK_DATE>
    <BANK_CODE>05</BANK_CODE>
    <ZONENO>11</ZONENO>
    <BRNO>3110010101</BRNO>
    <TELLERNO>20220525</TELLERNO>
    <TRANSRNO>CIB1656917144256</TRANSRNO>
    <FUNCTIONFLAG>10</FUNCTIONFLAG>
    <INSUID>0026Test</INSUID>
    <INSUTYPE/>
    <BRNONAME>兴业银行总行营业部Test</BRNONAME>
    <BRNOCERTCODE/>
    <MARKETER_ID/>
    <MARKETER_NAME/>
    <MARKETER_CERTCODE/>
    <MARKETER_CERTEXPIRY/>
    <CHANNEL>4</CHANNEL>
    <APPLYNO/>
    <TB_DATE>20220704</TB_DATE>
    <PAYNAME>远远</PAYNAME>
    <PAYACC>62148357196100579</PAYACC>
    <PAYMETHOD/>
    <PAYMODE/>
    <SENDMETHOD/>
    <INSU_SPEC/>
    <PASSWORD/>
    <BD_PRINT_NO/>
    <FP_PRINT_NO/>
    <TEMP/>
    <REMARK/>
  </MAIN>
  <HEALTH_NOTICE>
    <CAREER_ITEM/>
    <HEALTHY_ITEM/>
    <NOTICE_ITEM>0</NOTICE_ITEM>
  </HEALTH_NOTICE>
  <PRODUCTS>
    <PRODUCT>
      <PRODUCTID>NW0090</PRODUCTID>
      <MAINPRODUCTID>NW0090</MAINPRODUCTID>
      <AMT_UNIT/>
      <CHARGE_PERIOD>2</CHARGE_PERIOD>
      <CHARGE_YEAR>5</CHARGE_YEAR>
      <COVERAGE_PERIOD>1</COVERAGE_PERIOD>
      <COVERAGE_YEAR/>
      <PREMIUM>300000</PREMIUM>
      <AMNT/>
      <DVDMETHOD>2</DVDMETHOD>
      <ALFLAG>2</ALFLAG>
      <PT_TEMP/>
      <PT_REMARK/>
    </PRODUCT>
  </PRODUCTS>
  <TBR>
    <TBR_TAX_CLASSIFICATION/>
    <TBR_TAX_RSN/>
    <TBR_NATIVEPLACE>344</TBR_NATIVEPLACE>
    <TBR_BBR_RELA>1</TBR_BBR_RELA>
    <TBR_OCCUTYPE>H0101003</TBR_OCCUTYPE>
    <TBR_DOSMOKE/>
    <TBR_NAME>远远</TBR_NAME>
    <TBR_SEX>0</TBR_SEX>
    <TBR_BIRTH>1994-08-23</TBR_BIRTH>
    <TBR_IDTYPE>6</TBR_IDTYPE>
    <TBR_IDNO>810000199408230021</TBR_IDNO>
    <TBR_IDEFFSTARTDATE>20220704</TBR_IDEFFSTARTDATE>
    <TBR_IDEFFENDDATE>20220803</TBR_IDEFFENDDATE>
    <TBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</TBR_ADDR>
    <TBR_POSTCODE>000000</TBR_POSTCODE>
    <TBR_MOBILE>13543339240</TBR_MOBILE>
    <TBR_REVENUE>500000</TBR_REVENUE>
    <TBR_RESIDENTS/>
    <TBR_TEMP>13543339249@139.com</TBR_TEMP>
    <TBR_REMARK/>
    <TBR_TEL/>
    <TBR_HOMEINCOME>1000000</TBR_HOMEINCOME>
    <TBR_WORK_UNIT/>
    <TBR_HEIGHT/>
    <TBR_WEIGHT/>
    <TBR_OPENBANK/>
    <TBR_STATEMENT>1</TBR_STATEMENT>
    <INSPREM_BDGT_AMT/>
    <TBR_MARRY_STS/>
  </TBR>
  <BBR>
    <BBR_NATIVEPLACE>344</BBR_NATIVEPLACE>
    <BBR_OCCUTYPE>H0101003</BBR_OCCUTYPE>
    <BBR_DOSMOKE/>
    <BBR_NAME>远远</BBR_NAME>
    <BBR_SEX>0</BBR_SEX>
    <BBR_BIRTH>1994-08-23</BBR_BIRTH>
    <BBR_AGE>27</BBR_AGE>
    <BBR_IDTYPE>6</BBR_IDTYPE>
    <BBR_IDNO>810000199408230021</BBR_IDNO>
    <BBR_IDEFFSTARTDATE>20220704</BBR_IDEFFSTARTDATE>
    <BBR_IDEFFENDDATE>20220803</BBR_IDEFFENDDATE>
    <BBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</BBR_ADDR>
    <BBR_POSTCODE>000000</BBR_POSTCODE>
    <BBR_MOBILE>13543339240</BBR_MOBILE>
    <BBR_REVENUE>500000</BBR_REVENUE>
    <BBR_REGISTER/>
    <BBR_TEL/>
    <BBR_TEMP/>
    <BBR_WORK_UNIT/>
    <BBR_HEIGHT/>
    <BBR_WEIGHT/>
    <BBR_MARRY_STS/>
    <BBR_REMARK/>
  </BBR>
  <SYRS>
    <SYR>
      <SYR_NAME>蹦蹦</SYR_NAME>
      <SYR_SEX>1</SYR_SEX>
      <SYR_PCT>100</SYR_PCT>
      <SYR_BBR_RELA>0</SYR_BBR_RELA>
      <SYR_BIRTH>19720101</SYR_BIRTH>
      <SYR_IDTYPE>1</SYR_IDTYPE>
      <SYR_IDNO>110101197201010993</SYR_IDNO>
      <SYR_IDEFFSTARTDATE/>
      <SYR_IDEFFENDDATE>20240101</SYR_IDEFFENDDATE>
      <SYR_NATIVEPLACE/>
      <SYR_TEMP>1</SYR_TEMP>
      <SYR_REMARK/>
    </SYR>
  </SYRS>
</INSU>


metersphere：
<?xml version="1.0" encoding="utf-8"?>

<INSU>
  <MAIN>
    <BANK_DATE>20220704</BANK_DATE>
    <BANK_CODE>05</BANK_CODE>
    <ZONENO>11</ZONENO>
    <BRNO>3110010101</BRNO>
    <TELLERNO>20220525</TELLERNO>
    <TRANSRNO>CIB1656917144256</TRANSRNO>
    <FUNCTIONFLAG>10</FUNCTIONFLAG>
    <INSUID>0026Test</INSUID>
    <INSUTYPE/>
    <BRNONAME>兴业银行总行营业部Test</BRNONAME>
    <BRNOCERTCODE/>
    <MARKETER_ID/>
    <MARKETER_NAME/>
    <MARKETER_CERTCODE/>
    <MARKETER_CERTEXPIRY/>
    <CHANNEL>4</CHANNEL>
    <APPLYNO/>
    <TB_DATE>20220704</TB_DATE>
    <PAYNAME>远远</PAYNAME>
    <PAYACC>62148357196100579</PAYACC>
    <PAYMETHOD/>
    <PAYMODE/>
    <SENDMETHOD/>
    <INSU_SPEC/>
    <PASSWORD/>
    <BD_PRINT_NO/>
    <FP_PRINT_NO/>
    <TEMP/>
    <REMARK/>
  </MAIN>
  <HEALTH_NOTICE>
    <CAREER_ITEM/>
    <HEALTHY_ITEM/>
    <NOTICE_ITEM>0</NOTICE_ITEM>
  </HEALTH_NOTICE>
  <PRODUCTS>
    <PRODUCT>
      <PRODUCTID>NW0090</PRODUCTID>
      <MAINPRODUCTID>NW0090</MAINPRODUCTID>
      <AMT_UNIT/>
      <CHARGE_PERIOD>2</CHARGE_PERIOD>
      <CHARGE_YEAR>5</CHARGE_YEAR>
      <COVERAGE_PERIOD>1</COVERAGE_PERIOD>
      <COVERAGE_YEAR/>
      <PREMIUM>300000</PREMIUM>
      <AMNT/>
      <DVDMETHOD>2</DVDMETHOD>
      <ALFLAG>2</ALFLAG>
      <PT_TEMP/>
      <PT_REMARK/>
    </PRODUCT>
  </PRODUCTS>
  <TBR>
    <TBR_TAX_CLASSIFICATION/>
    <TBR_TAX_RSN/>
    <TBR_NATIVEPLACE>344</TBR_NATIVEPLACE>
    <TBR_BBR_RELA>1</TBR_BBR_RELA>
    <TBR_OCCUTYPE>H0101003</TBR_OCCUTYPE>
    <TBR_DOSMOKE/>
    <TBR_NAME>远远</TBR_NAME>
    <TBR_SEX>0</TBR_SEX>
    <TBR_BIRTH>1994-08-23</TBR_BIRTH>
    <TBR_IDTYPE>6</TBR_IDTYPE>
    <TBR_IDNO>810000199408230021</TBR_IDNO>
    <TBR_IDEFFSTARTDATE>20220704</TBR_IDEFFSTARTDATE>
    <TBR_IDEFFENDDATE>20220803</TBR_IDEFFENDDATE>
    <TBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</TBR_ADDR>
    <TBR_POSTCODE>000000</TBR_POSTCODE>
    <TBR_MOBILE>13543339240</TBR_MOBILE>
    <TBR_REVENUE>500000</TBR_REVENUE>
    <TBR_RESIDENTS/>
    <TBR_TEMP>13543339249@139.com</TBR_TEMP>
    <TBR_REMARK/>
    <TBR_TEL/>
    <TBR_HOMEINCOME>1000000</TBR_HOMEINCOME>
    <TBR_WORK_UNIT/>
    <TBR_HEIGHT/>
    <TBR_WEIGHT/>
    <TBR_OPENBANK/>
    <TBR_STATEMENT>1</TBR_STATEMENT>
    <INSPREM_BDGT_AMT/>
    <TBR_MARRY_STS/>
  </TBR>
  <BBR>
    <BBR_NATIVEPLACE>344</BBR_NATIVEPLACE>
    <BBR_OCCUTYPE>H0101003</BBR_OCCUTYPE>
    <BBR_DOSMOKE/>
    <BBR_NAME>远远</BBR_NAME>
    <BBR_SEX>0</BBR_SEX>
    <BBR_BIRTH>1994-08-23</BBR_BIRTH>
    <BBR_AGE>27</BBR_AGE>
    <BBR_IDTYPE>6</BBR_IDTYPE>
    <BBR_IDNO>810000199408230021</BBR_IDNO>
    <BBR_IDEFFSTARTDATE>20220704</BBR_IDEFFSTARTDATE>
    <BBR_IDEFFENDDATE>20220803</BBR_IDEFFENDDATE>
    <BBR_ADDR>浙江省宁波市丰台区横一条加油站街道社区7号楼1单元203</BBR_ADDR>
    <BBR_POSTCODE>000000</BBR_POSTCODE>
    <BBR_MOBILE>13543339240</BBR_MOBILE>
    <BBR_REVENUE>500000</BBR_REVENUE>
    <BBR_REGISTER/>
    <BBR_TEL/>
    <BBR_TEMP/>
    <BBR_WORK_UNIT/>
    <BBR_HEIGHT/>
    <BBR_WEIGHT/>
    <BBR_MARRY_STS/>
    <BBR_REMARK/>
  </BBR>
  <SYRS>
    <SYR>
      <SYR_NAME>蹦蹦</SYR_NAME>
      <SYR_SEX>1</SYR_SEX>
      <SYR_PCT>100</SYR_PCT>
      <SYR_BBR_RELA>0</SYR_BBR_RELA>
      <SYR_BIRTH>19720101</SYR_BIRTH>
      <SYR_IDTYPE>1</SYR_IDTYPE>
      <SYR_IDNO>110101197201010993</SYR_IDNO>
      <SYR_IDEFFSTARTDATE/>
      <SYR_IDEFFENDDATE>20240101</SYR_IDEFFENDDATE>
      <SYR_NATIVEPLACE/>
      <SYR_TEMP>1</SYR_TEMP>
      <SYR_REMARK/>
    </SYR>
  </SYRS>
</INSU>

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复
