### ISSUE TITLE
[FEATURE]接口自动化测试分层

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#1558]
**请描述您的需求或者改进建议.**
将自动化测试用例进行分层处理，更方便用例的维护和复用，操作和展示更人性化。虽然现在有引用但是在操作上还是有很多局限。

**请描述你建议的实现方案**
可主要分为3层
第1层操作层，切分每个接口级别的基本操作；
第2层流程层，可通过各种基本操作进行组合，也可加入独立的接口；
第3层用例层，根据各种流程进行组合，然后通过输入参数来决定用例走向，数据与脚本分离；
这样可以最大限度的提高脚本的可维护性，大大提高脚本的复用性，那么最后统计数据也应该只需要统计第3层的用例数据即可。

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，我们内部讨论下
