### ISSUE TITLE
[BUG] 使用非local资源池进行性能压测，报Failed to connect to Kafka

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#15587]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20.3-lts

### 使用外置数据库

否

### 问题描述

新增了一个性能资源池，页面校验通过，在ms机器上Telnet ip+端口也是正常的
![image](https://user-images.githubusercontent.com/67257251/177707117-16237a84-f90e-436d-ba9f-d34f21f6044c.png)
当选择这个资源池进行压测的时候会报Failed to connect to Kafka
![image](https://user-images.githubusercontent.com/67257251/177707324-8c087b5d-24b8-49c3-a7e8-a1154f5c5463.png)
error日志如下：
![image](https://user-images.githubusercontent.com/67257251/177707505-67a2ce39-bfb8-444f-9384-31a414bde1b2.png)
通过机器上看kafka状态，zookeeper状态都正常，kafka  ip+端口telnet也是通的

### 重现步骤

使用local资源池是正确的，但是使用非local资源池失败

**Comment by youliyuan-fit2cloud** [comment]
你好，请参考下图，排查问题。
也可以查看下我们常见问题的文档：https://metersphere.io/docs/faq/load_test/#kafka
![image](https://user-images.githubusercontent.com/54612864/177713140-a8955c45-9d8c-4097-9e60-de1de471fb2f.png)

**Comment by libb-test123** [comment]
通过ms 的指令连接了kafka是open的

**Comment by youliyuan-fit2cloud** [comment]
> 通过ms 的指令连接了kafka是open的

![image](https://user-images.githubusercontent.com/54612864/177717373-934f235c-4534-4e71-b5ee-519664eca7d2.png)

**Comment by libb-test123** [comment]
![image](https://user-images.githubusercontent.com/67257251/177718401-ef757c7e-cd9b-4a8a-814e-64cc63919dba.png)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/177740022-7a63fc8e-85c3-49ca-bceb-fc58619afc37.png)

node资源池没有镜像吧，手动pull吧，然后添加到上图镜像中

**Comment by libb-test123** [comment]
可以跑通了，感谢
