### ISSUE TITLE
[BUG]单向同步（MS创建的缺陷同步禅道）-缺陷模版上有添加关联字段，MS更新缺陷状态同步失败，状态字段未变更

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#15590]
### 联系方式

企业微信：MeterSphere 交流群35；李彬

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

缺陷状态同步失败【原[v1.20.6](https://github.com/metersphere/metersphere/milestone/67) 已修复缺陷返租】

### 重现步骤

1、MS创建缺陷 ->同步至关联禅道，成功
2、在MS变更缺陷内容，能正常同步
3、在MS变更缺陷状态，再次点击【同步缺陷】按钮

### 附加信息

具体配置相关数据，可以参考https://github.com/metersphere/metersphere/issues/14036

**Comment by ltfit** [comment]
你好 请在缺陷编辑中检查下同步状态是否更改了，这个必须修改状态后才能同步更新
<img width="861" alt="image" src="https://user-images.githubusercontent.com/99794211/177720189-c0133426-b7c0-4ec2-b661-9990da7f5178.png">

**Comment by hongnini** [comment]
> 你好，请在缺陷编辑页面中检查下同步状态是否更改了，这个必须修改状态后才能同步更新 <img alt="image" width="861" src="https://user-images.githubusercontent.com/99794211/177720189-c0133426-b7c0-4ec2-b661-9990da7f5178.png">

了解了，确实是更新【平台状态】就可以了
