### ISSUE TITLE
[BUG]Jmeter 函数 ${javaScript} 无法执行，导致其他参数获取变量

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#15599]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

Jmeter 函数 ${javaScript} 无法执行，导致其他参数获取变量失败

函数：`${__javaScript("${email}".substring(1\,3),)}`

### 重现步骤

1. MeterSphere
![image](https://user-images.githubusercontent.com/92966838/177755107-44cf3ad0-bb4c-477f-b850-93f5cff0ee3e.png)

2. Jmeter
![image](https://user-images.githubusercontent.com/92966838/177755439-5a993cb5-300b-425b-a3ae-ad2e3ea565bd.png)

![image](https://user-images.githubusercontent.com/92966838/177755240-fb7210ed-d489-4c7b-9115-e2cd8465c081.png)

### 期待的正确结果

以正确引用变量

**Comment by gaohonghai** [comment]
函数被 md 解析了，补充一下：${__javaScript("${email}".substring(1\,3),)}"

**Comment by gaohonghai** [comment]
> 函数被 md 解析了，补充一下： `${__javaScript("${email}".substring(1\,3),)}"`

**Comment by zyyfit** [comment]
您好，我在jmeter里测试了一下，这个变量也不能使用，您在jmeter里是否添加了外部jar包？如果有的话，在ms里也需要添加
这是带转义的
![image](https://user-images.githubusercontent.com/73461316/177905465-2264ca3f-7162-4a22-8120-8a1df2e00295.png)
这是不带转义的
![image](https://user-images.githubusercontent.com/73461316/177905562-70b2264c-65f2-49b8-991f-3de825756c49.png)
![image](https://user-images.githubusercontent.com/73461316/177905562-70b2264c-65f2-49b8-991f-3de825756c49.png)

**Comment by zyyfit** [comment]
不对，刚刚看错了，在ms里测试了一下，是可以的
![image](https://user-images.githubusercontent.com/73461316/177906370-a139c624-197d-4c01-bf9f-83107f22233d.png)

**Comment by gaohonghai** [comment]
对 我也试了下，那应该是确认有如下两个问题：
1、关闭 json-schema 后，请求参数自动添加了转义（因为）
2、已文本的形式编辑 带有 javaScript 函数的参数，会有json格式错误的提示
![image](https://user-images.githubusercontent.com/92966838/177908708-6842a97e-9fc9-48e1-a4ee-f8d224df4064.png)

**Comment by zyyfit** [comment]
格式错误的这个提示没有影响的，这样写确实是个错误的json格式

**Comment by gaohonghai** [comment]
确实，我在postman测了 也会有语法报错，那就是第一点问题

**Comment by zhangzhaox** [comment]
URL转码时 也存在 from表单 \,引发的问题，解决时麻烦同步关注下 谢谢！

**Comment by zyyfit** [comment]
> URL转码时 也存在 from表单 ,引发的问题，解决时麻烦同步关注下 谢谢！

您好，请提交一个issue详细描述一下

**Comment by zyyfit** [comment]
这个问题1.20.10版本修复，请等待发版后验证

**Comment by gaohonghai** [comment]
好的 感谢
