### ISSUE TITLE
[BUG]postman导入接口用例，断言部分会丢失

### ISSUE THREAD

**Issue by xiaoyaoruchen** [metersphere/metersphere#15603]
### 联系方式

412628588@qq.com

### MeterSphere 版本

v1.20.7-lts

### 使用外置数据库

否

### 问题描述

[BUG]postman导入接口用例，断言部分会丢失

### 重现步骤

[BUG]postman导入接口用例，断言部分会丢失

**Comment by zyyfit** [comment]
您好，目前不支持postman导入前置脚本和断言
