### ISSUE TITLE
[BUG]添加了用例模板，在新增用例的时候，没有选模板的地方

### ISSUE THREAD

**Issue by hdlk510** [metersphere/metersphere#15615]
### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

模板管理里面，添加了用例模板，在新增用例的时候，没有选模板的地方

### 重现步骤

新增一个用例模板，然后新增用例，没有可以选模板的地方

**Comment by ltfit** [comment]
你好，在项目设置-项目信息-用例模版选择
![image](https://user-images.githubusercontent.com/99794211/177932029-f52f5304-49a3-4138-934f-b596667877bc.png)
