### ISSUE TITLE
[BUG]后置超过sql超过十个以后第1,10,11会优先执行

### ISSUE THREAD

**Issue by zihui1** [metersphere/metersphere#15616]
### 联系方式

602208333@qq.com

### MeterSphere 版本

版本:   v1.20.8-lts

### 使用外置数据库

否

### 问题描述

后置超过sql超过十个以后第1,10,11会优先执行，会导致前面如果写的是查询sql会为空

### 重现步骤

插入15条后置sql运行操作

### 期待的正确结果

根据序号优先级顺序执行后置操作

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
