### ISSUE TITLE
[BUG]接口自动化转性能测试，在有使用csv未嵌套循环控制器时，性能测试取值有误

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15628]
### MeterSphere 版本

1.20.9lts

### 使用外置数据库

否

### 问题描述

接口自动化转性能测试，在有使用csv未嵌套循环控制器时，性能测试取值有误

### 重现步骤

场景一：
1.创建一个接口场景用例，请求参数通过csv取变量的方式获取(未嵌套循环控制器)，调试成功后，转为性能测试用例，并执行压测，查看压测执行情况；
场景二：
1.创建一个接口场景用例，嵌套循环控制器，请求参数通过csv取变量的方式获取(变量值存在"-"字符，具体可见下图)，调试成功后，转为性能测试用例，并执行压测，查看压测执行情况；
（备注：使用常量时，转换为性能用例，进行压测，能正常运行，无请求报错）

### 期待的正确结果

场景一：
预期结果：压测执行完成后，在网络正常的情况下，错误率为0；
实际结果：压测执行完成后，请求错误率为100%，请求入参变量值未获取到；
场景二：
预期结果：压测执行完成后，在网络正常的情况下，错误率为0；
实际结果：压测执行完成后，请求错误率为100%，请求入参变量值未正确获取，根据断言日志报错提示：入参有误；

### 相关日志输出
[请求参数填变量.log](https://github.com/metersphere/metersphere/files/9070907/default.log)
[请求参数填常量.log](https://github.com/metersphere/metersphere/files/9070908/default.log)

_No response_

### 附加信息

![948ab9d6515a502ba1b82b3cb012493](https://user-images.githubusercontent.com/92150453/177965326-345b61f4-c5c7-47b4-8dcd-c27886b4d6cb.png)
![beb62880b89384840f9297da63a4797](https://user-images.githubusercontent.com/92150453/177965346-218d9d6d-792b-4f6c-8e8c-5a6b54e340df.png)
![0c3553eb760a9664d5d6a8c9483bdd9](https://user-images.githubusercontent.com/92150453/177965415-f23697df-da1b-4478-b7df-8f788d5a7b90.png)
![4db2cc152c3a0a404d12143799e92e3](https://user-images.githubusercontent.com/92150453/177965604-2ea5ce04-2948-4564-9c6a-175e417a329c.png)
请求入参设置为常量时的压测：
![043a0b42cc6c6ba189dc4c70e69ff9c](https://user-images.githubusercontent.com/92150453/177965742-4b224d83-a01f-4304-8abe-5147b07ac775.png)
![a4239f65ad398d852bde24f87809e1f](https://user-images.githubusercontent.com/92150453/177965772-bddec8f1-f67e-4c20-a7b5-e5345e84133d.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您可以把变量放到url上，然后看一下性能测试执行完的jtl文件里，取值是否正确
![image](https://user-images.githubusercontent.com/73461316/177978776-05d2ad06-e70b-486e-b1f3-3917b00ed0ff.png)

**Comment by sageonedream** [comment]
> 您好，没有复现这个问题，您可以把变量放到url上，然后看一下性能测试执行完的jtl文件里，取值是否正确 ![image](https://user-images.githubusercontent.com/73461316/177978776-05d2ad06-e70b-486e-b1f3-3917b00ed0ff.png)

验证的场景不对，请通过请求体变量来进行验证

**Comment by zyyfit** [comment]
在请求体里也没有问题，这时性能测试报告和执行性能测试（登录接口）产生的登录日志
![image](https://user-images.githubusercontent.com/73461316/178656546-fc47f073-3be1-455e-80df-8d9600449423.png)
![image](https://user-images.githubusercontent.com/73461316/178656636-d86a73f2-f773-4183-af47-3c6d2df50465.png)
