### ISSUE TITLE
[BUG]导入5层结构下的接口会自动导入到未规划接口目录下

### ISSUE THREAD

**Issue by zihui1** [metersphere/metersphere#15627]
### 联系方式

602208333@qq.com

### MeterSphere 版本

版本:   v1.20.8-lts

### 使用外置数据库

否

### 问题描述

导入5层结构下的接口会自动导入到未规划接口目录下

### 重现步骤

项目同步，页面导入五层结构接口

### 期待的正确结果

接口正常归属到对应的目录

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，下个版本会修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
