### ISSUE TITLE
[BUG]报表统计-项目报表，已创建的报表更改图表类型后，点击保存失败，而是变成了另存为

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#15634]
### 联系方式

张树彬

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

报表统计-项目报表，已创建的报表更改图表类型后，点击保存失败，而是变成了另存为

### 重现步骤

1. 创建一个项目报表，保存
2. 选择这个项目报表，修改图给类型，比如把柱状图入为饼状图，点击保存
3. 点击保存后未覆盖更改，而是打开另存为一个项目报表的弹窗

### 期待的正确结果

点击保存应该只是保存对当前项目报表的修改，点击另存为才是存成一个新的项目报表

### 附加信息

<img width="944" alt="d2c499793f7f57bf46653f95a819c73" src="https://user-images.githubusercontent.com/77324661/178017540-135d819f-4eb9-4063-91ff-2d424e6c06a5.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
