### ISSUE TITLE
[BUG] 操作日志缺少【登录】操作日志

### ISSUE THREAD

**Issue by guilin-f2c** [metersphere/metersphere#15635]
### 联系方式

guilin@fit2cloud.com 

### MeterSphere 版本

v1.20.4-LTS 

### 使用外置数据库

否

### 问题描述

在操作日志页面搜索不到任何“登录”日志（尽管我有登录操作）

### 重现步骤

1）登录MS系统
2）到操作日志页面进行查询 （选择类型为“登录”）
3）查看登录日志查询结果

### 期待的正确结果

在操作日志页面能够查询到登录日志

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.20.9-lts中没有复现，请升级到最新版本吧~
