### ISSUE TITLE
[FEATURE]自动化接口测试环境配置多地址

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#1563]
**请描述您的需求或者改进建议.**
在自动化用例执行时能够使用多个不同环境域名

**请描述你建议的实现方案**
由于每个接口使用的域名不同，现在统一一个环境域名，导致用例无法执行
可以在每个接口处设置执行域名，统一位置不变，单独设置了的优先执行
还可以域名处可以输入变量，那么输入的变量就是你设置的域名，更加灵活

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue #1534 重复，请关注 #1534
