### ISSUE TITLE
[BUG]创建用例评审不能关联当前项目

### ISSUE THREAD

**Issue by aidaijinxi** [metersphere/metersphere#1564]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7-4eedac40（demo线上测试环境）

**Bug 描述**
创建用例评审不能关联当前项目

**Bug 重现步骤**
1.  创建用例评审
2. 关联项目

**期待的正确结果**
可关联当前项目（ps：默认选中当前项目最好）

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35913169/109771724-21157800-7c38-11eb-98dd-ed6dd6fab669.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，默认选择当前项目，请创建用例评审后查看结果~
