### ISSUE TITLE
[BUG]【测试计划-关联测试用例 】不能按照 标签 搜索用例

### ISSUE THREAD

**Issue by qcl1024** [metersphere/metersphere#15641]
### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

【测试计划-关联测试用例 】不能按照 标签 搜索用例，之前某个版本是可以的，最新版本反而不支持了

### 重现步骤

【测试计划】-【关联测试用例 】

### 期待的正确结果

支持按照 标签 关联测试用例

### 附加信息

![image](https://user-images.githubusercontent.com/44964749/178179961-bac1e25b-5a6b-4963-b970-71a0a3991e07.png)

**Comment by ltfit** [comment]
感谢反馈，后续版本修复

**Comment by ltfit** [comment]
v1.20.10-lts中已修复~
