### ISSUE TITLE
[BUG]添加断言规则，会多出一个响应时间断言栏

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#1565]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
在接口自动化栏目中，给接口增加一个正则断言后，会多出一个响应时间断言控件，但实际响应时间断言是没有生效的

**Bug 重现步骤**
1.  接口自动化中新增接口
2. 给接口加上正则断言，点击保存
3. 退出当前选项卡
4. 从场景列表进入刚才的场景，点开接口显示

**期待的正确结果**
不应该出现响应时间断言控件

**截图**
![image](https://user-images.githubusercontent.com/40912823/109772298-c9c3d780-7c38-11eb-9715-663d7158ce56.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续版本优化这个问题

**Comment by zyyfit** [comment]
v1.8.0 已修复
