### ISSUE TITLE
[QUESTION]metersphere提交禅道缺陷，禅道缺陷模版，应如何设置禅道中的字段，所属项目、所属模块，所属项目和所属模块都是随时新增

### ISSUE THREAD

**Issue by lijianguo1103** [metersphere/metersphere#15651]
### 请描述您的问题

metersphere提交禅道缺陷
禅道缺陷模版，应如何设置禅道中的字段，所属项目、所属模块，所属项目和所属模块都是随时新增，如果设置为下拉列表定义字段，会导致新增项目或新增模块后，定义的字段值就会变更了，可否在提交缺陷时，新增禅道 所属项目和禅道 所属模块，类似现禅道 影响版本一样
或者有另外的方法进行同步所属项目和所属模块

**Comment by Hyyfit** [comment]
感谢反馈，待调研后规划。
