### ISSUE TITLE
[BUG]接口测试，https请求，且服务器不支持http，接口使用cookie中的token鉴权时，校验不通过

### ISSUE THREAD

**Issue by goblinintree** [metersphere/metersphere#15654]
### 联系方式

官网微信群

### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 使用外置数据库

否

### 问题描述

ms对比jmeter情况：同版本+同JDK(11)+同请求+https协议+cookie相同, jmeter可以，ms不可以
 

### 重现步骤

ms 配置访问https的请求， 服务器必须不支持http, 且接口需要cookie中token鉴权，此时 ms一直提示校验不通过，jmeter登录状态是可以校验通过的。

**Comment by youliyuan-fit2cloud** [comment]
你好，方便上传场景配置截图吗？我们没有遇到类似问题， 可能是操作步骤哪里不一样，所以强烈建议上传详细的信息。谢谢~

**Comment by goblinintree** [comment]
原因已经找到了，是 部署机器 访问服务被 限制，IP被限制。与MS无关。
