### ISSUE TITLE
[BUG]接口测试，Basic Auth 认证没生效

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15669]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

接口测试，Basic Auth 认证没生效

### 重现步骤

调试接口，选择 Basic Auth ，输入用户名、密码，点击调试
![437a9337777469d4a25773d1be0cccd](https://user-images.githubusercontent.com/30038088/178249973-0be148fe-90a0-46ec-bd64-043aa1d80f40.png)
没有自动在 header 里加 Authorization

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
