### ISSUE TITLE
[FEATURE]测试跟踪，查看报告慢sql

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#15674]
### MeterSphere 版本

V1.19.3

### 请描述您的需求或者改进建议

![1657593657111](https://user-images.githubusercontent.com/26110332/178396936-171bd008-61dc-4948-85fd-e7471ac72198.png)

912条用例结果，打开测试跟踪报告，需要23S，时间有点长

### 请描述你建议的实现方案

建议分页处理，查看是加快速度

导出时，可以接受慢点

**Comment by Hyyfit** [comment]
您好，没有复现这个问题。

**Comment by JackieShangJie** [comment]
![image](https://user-images.githubusercontent.com/26110332/182565779-41906c4c-baa3-4c3c-90a2-9f0b445e28d4.png)
在我这边是一个必现的问题，方便的话可以远程看看
