### ISSUE TITLE
[BUG]开源代码找不到UI测试包，导致编译不通过

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#15670]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

开源代码找不到UI测试包，导致编译不通过

### 重现步骤

1、直接下载源码，用IDEA打开后
<img width="1439" alt="Pasted Graphic 25" src="https://user-images.githubusercontent.com/72729206/178251485-197814bf-e619-4c9f-92ba-a36dd6181815.png">
2、直接删除报红的地方后，编译打包均正常

### 期待的正确结果

1、直接下载的源码就可以正常编译、打包、启动

**Comment by zhangdahai112** [comment]
重新拉下代码就行
