### ISSUE TITLE
[FEATURE]场景用例setup和teardown

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15695]
### MeterSphere 版本

v1.20.8-lts

### 请描述您的需求或者改进建议

需求
希望增加场景用例的setup和teardown功能

**Comment by Hyyfit** [comment]
您好，在环境配置中通过设置全局前后置的脚本，可实现setup和teardown的功能。
![image](https://user-images.githubusercontent.com/95834771/178466692-15aedec0-4086-42ff-b2ad-af926c7cab76.png)
