### ISSUE TITLE
[BUG]云测试-性能测试，无法监控压测机器

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#15713]
### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

云测试-性能测试，无法监控压测机器

### 重现步骤

云测试-性能测试配置服务器监控信息，压测执行完后 监控详情没有数据

### 期待的正确结果

显示监控数据

### 附加信息

<img width="960" alt="微信图片_20220701173835" src="https://user-images.githubusercontent.com/43202800/178461967-7bdeba3b-1ab9-44fb-a07e-393a3c45a63e.png">

**Comment by wangzhen-fit2cloud** [comment]
你好，这里添加的监控需要能被云环境服务器访问到，即通过公网可以访问才能获取到监控数据。

**Comment by zhangzhaox** [comment]
@xhy12 MS平台的性能测试监控 仅展示，数据源还是需要部署配置，可使用外部数据源
