### ISSUE TITLE
[FEATURE]数据库sql查询，响应体中，对于查询结果，选择table形式展示时，最多只能显示110条，超出的显示不出来

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#15711]
### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

数据库sql查询，响应体中，对于查询结果，选择table形式展示时，最多只能显示110条，超出的显示不出来。

<img width="806" alt="b227c2f3188aec7dbefb76eacf5931c" src="https://user-images.githubusercontent.com/100331967/178442986-cc3a3f46-75be-4c56-9297-e0478247e1cd.png">

### 重现步骤

1.自定义sql查询。
2.响应体中，对于查询结果，选择table形式展示。

现状：查询结果有150多条，默认的text形式能全部显示出结果，但是选择table形式时，差不多就显示了110条，超出的显示不出来。

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
