### ISSUE TITLE
[BUG]场景断言，可以新增多个

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#15731]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.9 和cloud版本

### 使用外置数据库

否

### 问题描述

前提：如果最外面有场景断言删除掉
在原来的场景里面，再复制一个场景，可以新增多个场景断言

![image](https://user-images.githubusercontent.com/15188833/178660072-d6a029eb-da3a-4751-932a-a86844940da2.png)

### 重现步骤

上次不支持josn格式，我在word里面另存为word格式
[Metersphere_Scenario_演示项目--1.docx](https://github.com/metersphere/metersphere/files/9099263/Metersphere_Scenario_.--1.docx)

**Comment by youliyuan-fit2cloud** [comment]
在v1.20.11-lts版本中已修复。
