### ISSUE TITLE
[FEATURE]接口测试参数提取增加更新到环境变量功能

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [metersphere/metersphere#15733]
### MeterSphere 版本

v1.20.9-lts

### 请描述您的需求或者改进建议

在接口测试的参数提取后置操作中，添加参数提取步骤后，在参数提取配置中可以直接通过勾选的方式将该变量添加/更新到环境变量中去，不需要再通过后置脚本的方式进行处理。

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/27671436/178664523-e4abafba-f8aa-4070-9436-deef5be5bddc.png)
在每一条提取变量的配置后增加 `更新到环境变量` 选项，勾选该选项以后，测试执行完成后便会将提取到的变量添加、更新到对应的环境配置当中。与在后置脚本中通过 `vars.put(${__metersphere_env_id}+"key","value");` 方式处理效果相同。

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。

**Comment by wan92hen** [comment]
你好，请问这个功能规划有什么新的进展吗？
