### ISSUE TITLE
[FEATURE]建议增加总的所有项目的接口汇总信息一览表

### ISSUE THREAD

**Issue by kaixinpianzi** [metersphere/metersphere#15732]
### MeterSphere 版本

v1.20.4-lts 

### 请描述您的需求或者改进建议

建议增加总的所有项目的接口汇总信息一览表，同时可以筛选我最近新增的用例总数，执行次数等等信息

### 请描述你建议的实现方案

增加后台管理

**Comment by Hyyfit** [comment]
感谢反馈，待调研后，规划排期。
