### ISSUE TITLE
[QUESTION] 对于 vue项目中./display的东西还有后端 xpack的东西你们是故意删除了吧

### ISSUE THREAD

**Issue by repetition** [metersphere/metersphere#15735]
### 请描述您的问题

我自己在运行源码的时候,  一直往 ./display找东西, 看代码中也引入的这个里面的东西
`const requireComponent = require.context('@/business/components/xpack/', true, /\.vue$/);
const header = requireComponent.keys().length > 0 ? requireComponent("./license/LicenseMessage.vue") : {};
const display = requireComponent.keys().length > 0 ? requireComponent("./display/Display.vue") : {};
const theme = requireComponent.keys().length > 0 ? requireComponent("./display/Theme.vue") : {};`

`  <img :src="'/display/file/loginLogo'" alt="">`

**Comment by Hyyfit** [comment]
xpack是我们企业版的代码。
