### ISSUE TITLE
[QUESTION]linux部署完，8081无法访问

### ISSUE THREAD

**Issue by jianghaohaohao** [metersphere/metersphere#15738]
### 请描述您的问题

linux部署完，8081无法访问

**Comment by rainbowshine521** [comment]
遇到了同样的问题

请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
您可以使用命令 'msctl status' 检查服务运行情况.


root@arm-20220714-1645:~# msctl status

WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
NAME                 COMMAND                  SERVICE              STATUS               PORTS
kafka                "/opt/bitnami/script…"   kafka                running (healthy)    0.0.0.0:9092->9092/tcp, :::9092->9092/tcp
ms-data-streaming    "/deployments/run-ja…"   ms-data-streaming    running (healthy)    
ms-node-controller   "/deployments/run-ja…"   ms-node-controller   running (healthy)    0.0.0.0:8082->8082/tcp, 0.0.0.0:9100->9100/tcp, :::8082->8082/tcp, :::9100->9100/tcp
ms-prometheus        "/bin/prometheus --c…"   prometheus           running (healthy)    0.0.0.0:9090->9090/tcp, :::9090->9090/tcp
ms-server            "/deployments/run-ja…"   ms-server            running (starting)   0.0.0.0:8081->8081/tcp, 0.0.0.0:10000-10010->10000-10010/tcp, :::8081->8081/tcp, :::10000-10010->10000-10010/tcp
mysql                "docker-entrypoint.s…"   mysql                running (healthy)    0.0.0.0:3307->3306/tcp, :::3307->3306/tcp
nodeexporter         "/bin/node_exporter …"   nodeexporter         running (healthy)    
redis                "docker-entrypoint.s…"   redis                running (healthy)    0.0.0.0:6379->6379/tcp, :::6379->6379/tcp
zookeeper            "/opt/bitnami/script…"   zookeeper            running (healthy)    8080/tcp

**Comment by Hyyfit** [comment]
没访问错吧，是ip地址加8081对吧？会不会是网络问题，有没有稍微排查下，另外看这个日志显示的是启动中，是不是还没启动完成呢，重点关注下ms-server容器的状态，有问题可以看下容器日志docker logs --tail 10 -f ms-server


![image](https://user-images.githubusercontent.com/95834771/180172691-4e96c404-6a55-4022-a183-7025823371b0.png)
