### ISSUE TITLE
[BUG] 字符串限制长度不一致

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1574]
**MeterSphere 版本**
1.7

**Bug 描述**
前置条件和备注这两块，上传时限制1000个字符，但web端限制500个字符，导致上传成功，但无法编辑保存。

**Bug 重现步骤**
1.  上传一个用例带1000字符以内且大于500字符的备注或前置条件
2.  上传成功后查看case
3.  点击确定并保存
4.  报错提示限制500字符长度

**期待的正确结果**
统一的限制字符长度

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/38770463/109927006-9481bd00-7cfe-11eb-82c4-6f326122bc1c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，未复现该问题，请升级到v1.7.3版本测试一下吧

**Comment by wonderfulwxw** [comment]
已更新到1.7.3 
![image](https://user-images.githubusercontent.com/38770463/110076994-649aee00-7dc0-11eb-968e-2afeff0ce439.png)

同样的问题


请用以下字符串放入备注或前置条件中测试。

```
askldfjslkdfj:

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by youliyuan-fit2cloud** [comment]
非常感谢，复现该问题，如果字符在500~1000会报错，如果>1000,会提示前置条件长度需要在0和1000之间; 
已计划下个版本修复
