### ISSUE TITLE
[BUG] v1.20.4-lts导出接口自动化案例导入到v1.20.9-lts 案例报  原始场景不存在

### ISSUE THREAD

**Issue by kkg039** [metersphere/metersphere#15743]
### 联系方式

kkg039@163.com

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

v1.20.4-lts导出接口自动化案例导入到v1.20.9-lts 案例报  原始场景不存在
![1](https://user-images.githubusercontent.com/109209906/178694070-5a291552-9877-421d-b0eb-91d82979c2c7.gif)

### 重现步骤

v1.20.4-lts导出接口自动化案例导入到v1.20.9-lts 案例报  原始场景不存在

### 期待的正确结果

场景案例正常执行

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个是已知问题，后续版本修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
