### ISSUE TITLE
[BUG]手动/定时执行测试计划，部分测试结果会出现java.net.UnknownHostException。单独执行场景是正常

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#15746]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.8

### 使用外置数据库

否

### 问题描述

手动/定时执行测试计划，部分测试结果会出现java.net.UnknownHostException。单独执行场景是正常

### 重现步骤

手动/定时执行测试计划，部分测试结果会出现java.net.UnknownHostException。单独执行场景是正常
1、在测试计划中配置定时任务；
2、点击定时任务执行结果；打开后发现除了自定义脚本外的接口都出现java.net.UnknownHostException，看附图；

### 期待的正确结果

测试计划能正常执行

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/178709413-52996e6b-7b2d-414c-9adb-7529c52f5fb9.png)

**Comment by liushuneng** [comment]
![origin_img_v2_a1628e23-c14c-45ea-a3c6-1f3ba576814g](https://user-images.githubusercontent.com/45531073/178713546-1934f70a-deb5-4be1-bd80-96d15345c105.jpg)

**Comment by xulinde** [comment]
v1.20.9-lts未复现该问题，java.net.UnknownHostException这个报错一般是连接问题，或域名解析错误，自行检查下吧～

**Comment by 35plus** [comment]
v1.20.9-lts未复现该问题，java.net.UnknownHostException这个报错一般是连接问题，或域名解析错误，自行检查下吧～
---不在测试计划里执行，是完全OK的。 测试计划这个地方前天天阳刚修复了一个问题，也是无法复现的。
这个问题 之前 在东区社区用户也碰到了，现在碰到问题的是企业客户。 
这是修复这个问题的难得机会。

**Comment by liushuneng** [comment]
1.客户被服务是容器部署，IP是会被的，所以未配置HOST
2.
测试计划执行失败，报错信息如下：
java.net.UnknownHostException: bigbang-order-service.bigbang-test-service.svc.cluster.bbmall
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$JMeterDefaultHttpClientConnectionOperator.connect(HTTPHC4Impl.java:404)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:935)
        at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:646)
        at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:119)
        at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
        at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
        at java.base/java.lang.Thread.run(Thread.java:829)


3. 测试计划执行请求内容如下：
请求地址 :http://bigbang-order-service.bigbang-test-service.svc.cluster.bbmall:8080/order/transaction/placeOrder
请求头 :Connection: keep-alive
locale: 
token: 
Content-Type: application/json
Content-Length: 6670
Host: bigbang-order-service.bigbang-test-service.svc.cluster.bbmall:8080
User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.14)
Cookies :
Body :POST http://bigbang-order-service.bigbang-test-service.svc.cluster.bbmall:8080/order/transaction/placeOrder

POST data:
{
    "routeAdaptorDTO": {
        "userServiceRouteCode": "default",
        "itemServiceRouteCode": "blank",
        "stockServiceRouteCode": "blank",
        "tenantRouteCode": null
    },
    "source": 1,
    "tenantId": 1,
    "orderToken": "327131210828165120",
    "from": null,
    "mergePay": false,
    "preProducePayInfo": false,
    "placeOrderRequests": [
        {
            "idempotentKey": "f2B3c1C1-1861-CF6F-5edE-Ffc8cDF7fb2C",
            "orderNo": null,
            "orderChannel": null,
            "tpOrderNo": "f2B3c1C1-1861-CF6F-5edE-Ffc8cDF7fb2C",
            "shopId": 7679,
            "sellerId": 7678,
            "shopName": "深圳伊利有限公司",
            "buyerId": 2420001418,
            "supplierId": null,
            "orderAmountExtensionDTO": {
                "orderAmount": {
                    "currencyCode": "CNY",
                    "cent": 17500,
                    "origin": 175.00
                },
                "payAmount": {
                    "currencyCode": "CNY",
                    "cent": 17500,
                    "origin": 175.00
                },
                "goodsAmount": {
                    "currencyCode": "CNY",
                    "cent": 17500,
                    "origin": 175.00
                },
                "shippingFee": null,
                "taxFee": null,
                "insuranceFee": null,
                "discountFee": null,
                "discountFeeDetail": [

                ],
                "features": {

                }
            },
            "payChannel": null,
            "payWay": null,
            "orderItemSkuRequests": [
                {
                    "channel": null,
                    "channelGroup": null,
                    "itemId": 129024,
                    "itemCode": "129024-W",
                    "skuId": 188226,
                    "skuCode": "188226-W",
                    "spuId": 189741,
                    "cspuId": 200046,
                    "quantity": 2,
                    "title": "欧井测试商品",
                    "imageUrl": "http://img.league-test.xyb2b.com/gsp/9aac68feac7cbb6cfcd71b8cced031c6.png",
                    "internationalCode": "ou2022061601",
                    "packageLength": null,
                    "packageWidth": null,
                    "packageHeight": null,
                    "packageWeight": null,
                    "attribute": "16G",
                    "skuTitle": "欧井测试商品 16G",
                    "originPrice": {
                        "currencyCode": "CNY",
                        "cent": 17500,
                        "origin": 175.00
                    },
                    "salePrice": {
                        "currencyCode": "CNY",
                        "cent": 17500,
                        "origin": 175.00
                    },
                    "purchasePrice": {
                        "currencyCode": "CNY",
                        "cent": 17500,
                        "origin": 175.00
                    },
                    "orderAmountExtensionDTO": {
                        "orderAmount": {
                            "currencyCode": "CNY",
                            "cent": 17500,
                            "origin": 175.00
                        },
                        "payAmount": null,
                        "goodsAmount": {
                            "currencyCode": "CNY",
                            "cent": 17500,
                            "origin": 175.00
                        },
                        "shippingFee": null,
                        "taxFee": null,
                        "insuranceFee": null,
                        "discountFee": null,
                        "discountFeeDetail": null,
                        "features": null
                    },
                    "supplierId": null,
                    "skuBatchNo": null,
                    "batchType": null,
                    "warehouseCode": null,
                    "features": "{}",
                    "orderLineFeatures": null,
                    "taxRate": null,
                    "gift": null,
                    "skuImage": null,
                    "settlementDTO": null
                }
            ],
            "orderType": 5,
            "virtual": 1,
            "cbOrderType": 1,
            "lockStock": null,
            "deductStock": null,
            "fulfillmentOrderCreate": null,
            "buyerRemark": null,
            "sellerRemark": null,
            "customOrderStatus": null,
            "bizScene": "801",
            "orderFrom": 1,
            "features": null,
            "bizFeatures": {
                "tradeTerm": "FAS",
                "tradeMode": "1"
            },
            "orderReceiverDTO": {
                "addressId": null,
                "customerName": "12",
                "receiverName": "12",
                "receiverMobile": "13565456678",
                "addr": "北京北京市东城区12",
                "countryCode": "1",
                "countryDesc": "中国",
                "provinceId": "110000",
                "province": "北京",
                "cityId": "110100",
                "city": "北京市",
                "regionId": "110101",
                "region": "东城区",
                "townId": null,
                "town": null,
                "villageId": null,
                "village": null,
                "idCardNo": null,
                "idCardFront": null,
                "idCardNegative": null,
                "postalCode": "000000",
                "tenantId": null,
                "createId": null,
                "updateId": null,
                "warehouseCode": null,
                "warehouseName": null,
                "source": null,
                "features": null
            },
            "plusSecond2AutoCancel": null,
            "orderSolutionDTO": {
                "lockStock": "NONE",
                "deductStock": "NONE",
                "fulfillmentOrderCreate": "NONE",
                "paymentOrderCreate": "NONE",
                "needPlatformPay": true,
                "plusSecond2AutoCancel": null,
                "orderAutoConfirm": 0,
                "plusSecond2AutoConfirm": null,
                "payRatio": 0,
                "needSellerConfirmNegotiation": false,
                "needNegotiate": null,
                "placeOrderForBuyer": true
            },
            "deliveryType": null,
            "exchangeRate": 2.121
        }
    ],
    "channelOrderList": [

    ]
}

[no cookies]

4.  单独执行执行结果如下：
请求
![origin_img_v2_3c11aa05-654c-4cae-98f9-fe1cb3a3c7bg](https://user-images.githubusercontent.com/45531073/179132630-741ee2f0-2a5a-437f-b226-000e38f222e4.jpg)

响应
![origin_img_v2_b8634be5-2cae-4676-9655-c21b614082ag](https://user-images.githubusercontent.com/45531073/179132600-a50be8ac-f932-476e-ac91-d44c1409191d.jpg)

在客户环境是必现的，如果有需要可以去客户环境验证

**Comment by liushuneng** [comment]
日志
[info.log](https://github.com/metersphere/metersphere/files/9117118/info.log)
[error.log](https://github.com/metersphere/metersphere/files/9117119/error.log)

**Comment by liushuneng** [comment]
进入ms-server容器，ping 和curl域名是正常,网络未发现问题
![origin_img_v2_e48a7948-4af2-4237-91d5-952303a8b9fg](https://user-images.githubusercontent.com/45531073/179175531-7705724c-a628-4ce1-9619-c4609d500303.jpg)
![origin_img_v2_4ae4e51d-936e-4b5a-9a13-7ba1c1cc34eg](https://user-images.githubusercontent.com/45531073/179175537-f59ffe88-9de1-4d66-9ed5-fc1b51cd87ca.jpg)

**Comment by liushuneng** [comment]
客户环境问题
