### ISSUE TITLE
[BUG]测试用例评审任务中测试用例评审结果通过的状态在升级版本后变为未评审

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#15758]
### 联系方式

交流群5王佳信

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

升级后查看测试用例评审结果
经查，数据库中存储的状态无误，前端页面展示错误

### 重现步骤

升级lts版本

### 期待的正确结果

正常显示

### 相关日志输出

```shell
1
```

### 附加信息

![image](https://user-images.githubusercontent.com/46660929/178880448-463ff4ef-a428-4b9e-84f2-d0bb7b5a712c.png)

**Comment by ltfit** [comment]
你好，你是从哪个版本升级的，我这边没有复现
