### ISSUE TITLE
[BUG]已有的API场景用例，再次打开无法显示断言的内容

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1575]
**MeterSphere 版本**
v1.7.3

**Bug 描述**
接口测试-接口自动化，新建一条场景用例，步骤中增加断言，保存。
退出后再次进入查看场景用例，打开场景的详细步骤，发现看不到断言内容。

**Comment by youliyuan-fit2cloud** [comment]
您好，我们没有复现该问题，请查看是否是引用的场景用例，如果是引用不能添加断言
