### ISSUE TITLE
[BUG]无法给用户组批量分配项目。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#15756]
### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

1、选择：系统>>系统设置>>用户组与权限，选中多个用户组。
2、选择批量操作：选择‘批量添加到项目’
3、在弹出的页面上，选择‘工作空间’，系统直接发送跳转，无法进行批量分配项目设置

### 重现步骤

1、选择：系统>>系统设置>>用户组与权限，选中多个用户组。
2、选择批量操作：选择‘批量添加到项目’
3、在弹出的页面上，选择‘工作空间’，系统直接发送跳转，无法进行批量分配项目设置

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/178744177-34d6b61d-3d2c-4aaa-a3f0-c64e45a45b8b.png)

![image](https://user-images.githubusercontent.com/78218624/178743678-56eead30-1b6e-40b6-b66b-2f0d8e2826d3.png)

**Comment by youliyuan-fit2cloud** [comment]
1、选择：系统>>系统设置>>用户组与权限，选中多个用户组。
上诉描述错误------->是系统设置-用户-批量添加到项目
