### ISSUE TITLE
[BUG]缺陷管理列表信息显示有问题

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#15757]
### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

[BUG]缺陷管理列表信息显示有问题

### 重现步骤

[BUG]缺陷管理列表信息显示有问题

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/178862676-264a321a-72d6-4291-aff2-3ff4429de6fe.png)

**Comment by youliyuan-fit2cloud** [comment]
请详细描述下你的用例模板信息！

**Comment by ltfit** [comment]
已知问题 1.20.10会修复

**Comment by ltfit** [comment]
v1.20.10-lts中已修复~
