### ISSUE TITLE
[BUG]场景导出JMX或者转成性能测试后，提取默认勾选上了 “匹配多条”

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15751]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

场景导出JMX或者转成性能测试后，提取默认勾选上了 “匹配多条”

### 重现步骤

1.创建一个场景
2.提取一个数组中的某个值，不勾选 “匹配多条”
![image](https://user-images.githubusercontent.com/30038088/178731012-71e29adc-560e-46ea-8ad5-f28176812456.png)

3.导出JMX或者转成性能测试后 下载执行文件，导入到MS场景里，查看提取，“匹配多条” 勾选上了
![image](https://user-images.githubusercontent.com/30038088/178731363-e2d1191e-2fa4-4811-9423-c16b5e0c3e84.png)

![image](https://user-images.githubusercontent.com/30038088/178731459-dbbc4b99-98f3-48f4-a445-a3e1e38e5f0d.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~
