### ISSUE TITLE
[BUG]性能测试-高级配置，配置 “自定义响应码” ，执行性能测试，报告中所有请求报空指针

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#15754]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

性能测试-高级配置，配置 “自定义响应码” ，执行性能测试，报告中所有请求报空指针

### 重现步骤

1.性能测试-高级配置，配置 “自定义响应码”
![image](https://user-images.githubusercontent.com/30038088/178740257-caaa63ea-f7fb-4dad-aa5d-e72bf4653e0c.png)
2.查看报告
![image](https://user-images.githubusercontent.com/30038088/178740365-f7f03f4a-6f59-41ce-a02d-78bca755a212.png)
![image](https://user-images.githubusercontent.com/30038088/178740388-9442046c-8d1a-4f5b-a8ab-dd422ac0b1fe.png)
![image](https://user-images.githubusercontent.com/30038088/178740412-c52a7c0d-14b3-40d1-9ea7-7ae933c637e7.png)

**Comment by youliyuan-fit2cloud** [comment]
已修复，请升级到1.20.17-lts 以上版本。
