### ISSUE TITLE
[BUG]带中文的CSV读取后为乱码

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#15755]
### 联系方式

撼地神牛

### MeterSphere 版本

Cloud MS

### 使用外置数据库

是

### 问题描述

场景参数上传带有中文的CSV，读取后显示乱码。在场景中使用也是乱码

### 重现步骤

1.上传带有中文的CSV
2.预览显示乱码
![image](https://user-images.githubusercontent.com/30932762/178740361-db00c7c6-e01b-4a4e-801c-13ed47f9e113.png)
![image](https://user-images.githubusercontent.com/30932762/178740390-e570dfa0-144f-4f5f-a6b9-0690f5246d7f.png)
3.在场景接口使用参数，请求的报文也是乱码，导致请求失败
![Uploading image.png…]()

### 期待的正确结果

CSV能够准确显示和使用中文

### 附加信息

CSV文件如下
![image](https://user-images.githubusercontent.com/30932762/178741370-a1255f28-8889-4a29-84ef-2435d8032534.png)

**Comment by fit2-zhao** [comment]
你的文件是 ：城市.csv: text/csv; charset=iso-8859-1
