### ISSUE TITLE
[FEATURE]用例评审结果汇总

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#15763]
### MeterSphere 版本

v1.20.8-lts

### 请描述您的需求或者改进建议

用例评审结果汇总（用来了解用例编写质量）
1.目前用例评审只能通过筛选评审结果为失败的用例查看用例评审情况
2.评审结果备注只能添加在用例评论里面，无法收集所有的评论

### 请描述你建议的实现方案

建议：
1.对评审结果通过、失败进行汇总
2.对评审的评论进行汇总

**Comment by Hyyfit** [comment]
感谢反馈，待调研后，规划排期。

**Comment by Hyyfit** [comment]
您好呀，这个需求想跟您确认一下，您加一下我微信
<img width="320" alt="image" src="https://user-images.githubusercontent.com/95834771/185362101-39419685-3ecc-437f-8a46-caedffb4282e.png">
