### ISSUE TITLE
[BUG]请求参数是file的时候，上传中文名的附件，请求过去的文件名是乱码

### ISSUE THREAD

**Issue by isologue** [metersphere/metersphere#15764]
### 联系方式

179040754@qq.com

### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

请求参数是file的时候，上传中文名的附件，请求过去的文件名是乱码
![2be8691ee5592a9ac30663dc236afb5](https://user-images.githubusercontent.com/73510356/178888398-2de55a7c-bca5-44c2-9f3a-bfad971247f6.png)

### 重现步骤

请求参数是file的时候，上传中文名的附件，查看请求头的文件名是乱码

### 期待的正确结果

预期是中文名的附件传过去还是中文

**Comment by xulinde** [comment]
这个是jmeter的bug，暂时不处理～
