### ISSUE TITLE
[BUG]已删除的用例（在回收站），在用例评审--脑图界面还能看得到该用例

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#15762]
### MeterSphere 版本

v1.20.8-lts-ba947709

### 使用外置数据库

否

### 问题描述

已删除的用例（在回收站），在用例评审--脑图界面还能看得到该用例

### 重现步骤

创建用例评审--关联测试用例--到功能用例 用例列表界面删除部分用例--评审测试用例 使用脑图方式评审，能看到被删除的用例（列表方式评审则看不到被删除的用例）

### 期待的正确结果

用例评审-脑图方式评审，过滤已被删除的用例

**Comment by ltfit** [comment]
感谢反馈 后续版本修复

**Comment by ltfit** [comment]
v1.20.10-lts中已修复~
