### ISSUE TITLE
[BUG]请求体采用'x-www-form-urlencoded'形式，在请求内容里中文乱码及符号不正常显示

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#15779]
### 联系方式

飞致云-任建康

### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

接口的请求体选择'x-www-form-urlencoded'格式的，中文会乱码(高级设置中编码'是'，'否'都一样)，标点符号没有正常显示
详情如下图：
<img width="1428" alt="x-www-form-01" src="https://user-images.githubusercontent.com/39123539/178910374-c302364e-2d4f-4366-81be-02c5926ffff2.png">

### 重现步骤

接口的请求体选择'x-www-form-urlencoded'格式，内容可以如下：
值内容：{"status":300,"message":"FAIL","devMessage":"哈哈哈哈哈"}

### 期待的正确结果

在请求内容中正常显示，如下图：
<img width="558" alt="postman-x-www-form-01" src="https://user-images.githubusercontent.com/39123539/178910802-7e73651a-9004-47c0-92e0-8a4b860d443b.png">

**Comment by xulinde** [comment]
这个不是乱码，是编码了。您这种请求直接用form-data格式就可以～

**Comment by R8619** [comment]
企业客户那边，他们form-data格式用不了，只能用x-www-form-urlencoded格式的

**Comment by R8619** [comment]
企业客户那边，他们form-data格式用不了，只能用x-www-form-urlencoded格式的

**Comment by fit2-zhao** [comment]
请了解下form-data 和 x-www-form-urlencoded 的区别。
