### ISSUE TITLE
[BUG] v1.7.3 【场景用例】引用环境后，环境配置的头部信息 会覆盖 自定义接口头部信息；编辑报错

### ISSUE THREAD

**Issue by ituta-git** [metersphere/metersphere#1577]
**MeterSphere 版本**
 v1.7.3

**Bug 描述**
bug1：【场景用例】引用环境后，环境头部信息会覆盖 自定义接口头部信息
**bug2：v1.7.3代码编译报错**

** 重现步骤**
Bug1：
      1).  【场景用例】引用环境信息，添加自定义接口，并且自定义接口有自己的头部信息
      2).   执行场景用例，接口请求时头部信息错误，导致接口执行失败

**期待的正确结果**
 优先级：场景中接口自带头部信息 > 引用环境的头部新

**截图**
 bug1截图:
![xx1](https://user-images.githubusercontent.com/57891222/109950535-9441eb80-7d17-11eb-801c-f7f55386cb84.png)
![xx2](https://user-images.githubusercontent.com/57891222/109950558-9c019000-7d17-11eb-9d17-bce06b0600fa.png)

### **bug2截图**
![image](https://user-images.githubusercontent.com/57891222/109951084-3661d380-7d18-11eb-9051-8dc670bb68d7.png)
**少一个参数**
![image](https://user-images.githubusercontent.com/57891222/109951242-6ad58f80-7d18-11eb-8260-01822b40cef1.png)
**找不到方法**
![image](https://user-images.githubusercontent.com/57891222/109951444-aec89480-7d18-11eb-8400-2a7ae243995b.png)

**Comment by fit2-zhao** [comment]
@ituta-git  请问缺陷1 的日志信息有吗，贴一张图；缺陷2 在1.8 版本修复。
