### ISSUE TITLE
[BUG]case用例执行时间太长，进而断言失败导致执行失败-偶现问题

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#15787]
### 联系方式

飞致云-任建康

### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

是

### 问题描述

问题现象：
客户在7.13日中午14:31分左右执行的case，有很多报错，每个场景的报告开始时间是31分，结束时间是38分。31分请求返回的当前刷新时间没问题，但是在38分才做断言，导致行情刷新时间超过5分钟，断言失败进而导致执行结果失败。

报告截图如下：
<img width="1286" alt="case-执行太久-00" src="https://user-images.githubusercontent.com/39123539/178930537-af63ce7b-c825-4774-aa76-db0c3a37eac1.png">

此case正常情况下一般都是毫秒级

### 重现步骤

非必现问题，在客户的环境发生。排查问题时查看过logs目录下全部日志文件所有那个时间段的日志，没有发现异常报错信息。若后续再出现同样的问题，能否帮忙提供些排查思路？

**Comment by fit2-zhao** [comment]
请检查下系统并发数，如果并发数设置太小同时执行任务过多，出现排队情况了。
