### ISSUE TITLE
引入测试套件概念，可以组合场景，各场景分布式执行

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1579]
**请描述您的需求或者改进建议.**

引入测试套件概念，可以组合场景，各场景分布式执行

**请描述你建议的实现方案**
这个可以实现吗

**Comment by wangzhen-fit2cloud** [comment]
你好，目前还没有分布式执行的能力，接口测试都是在本机执行的。
测试套件的场景可以通过`测试跟踪`->`测试计划`功能，将多个接口自动化场景添加进来批量执行。
后续会为测试计划增加执行节点功能，执行时可以选择一个或多个执行节点执行接口测试。
