### ISSUE TITLE
[FEATURE]【接口测试】接口测试建议弄一个其他平台中类似于测试集的功能，用于批量执行多个测试场景

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#158]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
收到，多谢您的反馈，我们内部讨论下再反馈。

**Comment by wangzhen-fit2cloud** [comment]
你好，其实现在一个接口测试就相当于一个测试集的概念，里面是可以包含多个测试场景的
@Ammyz

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> **请描述你建议的实现方案**

V1.1 版本上线了Jenkins插件，可以选择多个测试，批量执行，可以暂时到达这个效果，你说的基于平台的测试集功能，下个版本会规划

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.7版本已实现该功能，请持续关注～
