### ISSUE TITLE
[BUG]场景变量，没有默认类型，点击添加无反应

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#15806]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

路径：接口自动化--场景变量
描述：可以使用一种默认类型，或者“添加”按钮提示为“请先选择类型”

### 重现步骤

![image](https://user-images.githubusercontent.com/15188833/178955743-0ffa6e96-32aa-42aa-b794-2dc0ca423a20.png)

**Comment by xulinde** [comment]
v1.20.10-lts已优化～默认类型是常量
