### ISSUE TITLE
[FEATURE]执行用例的时候，应允许编辑备注和附件

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#1580]
**请描述您的需求或者改进建议.**
在执行用例时，有时需要对用例进行一些备注说明，或上传测试结果附件，但是现在这些都不允许在执行用例的时候操作。只能回到用例管理页面编辑，不太方便使用。

**请描述你建议的实现方案**
执行用例时，可以做用例编辑

**Comment by xulinde** [comment]
收到，已在后续版本规划中

**Comment by xulinde** [comment]
1.9.0已优化
