### ISSUE TITLE
[项目设置] 环境配置保存按钮文案建议优化以区分请求头添加按钮功能

### ISSUE THREAD

**Issue by Flash0313** [metersphere/metersphere#15803]
### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 请描述您的需求或者改进建议

环境配置保存时，容易混淆 请求头 『批量添加』 和环境 『添加』 按钮；
<img width="243" alt="image" src="https://user-images.githubusercontent.com/10867083/178950146-00f20aaa-7805-48ea-adb9-fc1551352b0b.png">

### 请描述你建议的实现方案

建议保存环境添加按钮文案改成 『保存』之类，区分不同操作

**Comment by Hyyfit** [comment]
感谢反馈，已规划，待排期。
