### ISSUE TITLE
[FEATURE]用例关联测试计划后，执行人变了

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#1581]
**请描述您的需求或者改进建议.**

用户A添加的测试用例，用户B将A的用例关联进测试计划后，测试计划中的执行人变成了B。

**请描述你建议的实现方案**
关联用例后，不应该变更用例的执行人，应维持维护人不变。

**Comment by xulinde** [comment]
收到，后面版本优化下这里

**Comment by xulinde** [comment]
经过讨论，关联之后的执行人还是执行关联的人，但是加一个维护人字段，便于辨识用例原本的维护人，也便与筛选批量修改
