### ISSUE TITLE
[BUG]测试跟踪-测试计划失败用例缺少失败执行功能

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#15814]
### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划按定时任务进行了执行，发现用例失败，需要验证是否真正失败或者其他原因，我需要重新执行一下。
发现这个界面没有入口

### 重现步骤

查看执行报告，失败用例不便捷重新执行

### 期待的正确结果

是否在报告界面--失败用例处，新增一个失败执行的入口或者按钮

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/179128244-dfa6bfdd-a592-4558-8275-63ed4a5a59c7.png)

![image](https://user-images.githubusercontent.com/19423100/179128559-ff14dfe7-1a47-471b-9fcd-674ca842bc0a.png)

**Comment by zyyfit** [comment]
2.0版本将增加失败重试功能

**Comment by zyyfit** [comment]
2.0.0版本已增加此功能
