### ISSUE TITLE
[BUG]试跟踪-测试计划-报告--失败用例tab获取创建人不合理

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#15815]
### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

试跟踪-测试计划-报告--失败用例tab获取创建人不合理

### 重现步骤

1、测试跟踪-测试计划-报告--点击失败用例
2、tab获取创建人不合理

### 期待的正确结果

显示责任人或者新增责任人列

场景：ms是平台化产品，张三创建了case，张三换岗了、离职了。但是用例继续在执行
         李四是新接班人，但是那每次显示都是张三，或者王五等，他如何快速找出自己的用例去找问题呢

**Comment by legend818** [comment]
同行们没有这种问题么？

**Comment by zrfit** [comment]
您好，与产品沟通计划在v2.X版本优化，具体版本带排期。

**Comment by legend818** [comment]
这个功能的应用场景是经常性的，建议提早实现将创建人改成责任人

**Comment by Hyyfit** [comment]
我们需要等微服务改造完成后才可以做这样的优化。
微服务是在10月完成。我们预计排期是到2.3或2.4的版本实现这个优化。

**Comment by legend818** [comment]
我能理解排期、技术改造等。这个功能需求是一个应用场景很大的，平台化的产品就是面对多人的协调操作，适用于体系大，人员多的团队去协同。每天执行定时任务自动化执行就是为了简化人员操作，针对出现的问题需要专人去解决，那么人员可能是变动的，所以这里加载责任人是最佳的

**Comment by Hyyfit** [comment]
这个需求是合理的，我们已经规划了。
因为我们现在正进行架构升级，这里也涉及测试计划的现有功能。需要完成了升级后，才能做优化，希望您可以理解。

**Comment by legend818** [comment]
2.3 2.4的版本好像没有看到这个功能实现
