### ISSUE TITLE
建议加个字段“序号”，方便管理和维护[FEATURE]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#1583]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/37016695/110091924-f9f3ad80-7dd3-11eb-9ab2-211e8a3082d9.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by xulinde** [comment]
1.10已实现该功能
