### ISSUE TITLE
[BUG]UI测试报告与实际执行时机不一致

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#15830]
### MeterSphere 版本

 v1.20.7-lts-4d988ef3

### 使用外置数据库

否

### 问题描述

UI测试报告截图与实际执行过程的时机对应不上，具体如下：
1、第二步已经切换页面并且设置断言新元素定位都成功了，但是截图仍停留在第一步的截图
2、步骤执行成功且断言成功，但截图显示空白

### 重现步骤

![image](https://user-images.githubusercontent.com/89765365/179182256-7e2696ea-2149-4aa4-959b-f8dc161c8f7d.png)

**Comment by zrfit** [comment]
已经问题，需求规划中，后续版本优化。

**Comment by zrfit** [comment]
v2.1.0已优化该问题，增加截图配置。
