### ISSUE TITLE
[BUG]接口定义，在已有接口上用JSON格式新增字段，保存后切换到JSON-SCHEMA格式，新增的字段未增加

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#15843]
### 联系方式

张树彬

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

1. 接口定义，在已有接口上用JSON格式新增字段，保存后切换到JSON-SCHEMA格式，新增的字段未增加；
2. 在JSON格式删除字段保存后，切换到JSON-SCHEMA格式，删除的字段未被删除，只能在JSON-SCHEMA模式下删除保存才会生效

### 重现步骤

情况1
1. 新建一个接口定义
2. 在原接口上用JSON格式增加字段，保存后切换JSON-SCHEMA格式，新增字段未显示；

情况2
1. 新建一个接口定义
2. 在原接口上用JSON格式删除字段，保存后切换JSON-SCHEMA格式，删除的字段仍存在；

### 期待的正确结果

用JSON格式新增或减少字段，保存后切换到JSON-SCHEMA格式下都同步更新

### 附加信息

![7b3af98b1f4db4c6ce1392011967b49](https://user-images.githubusercontent.com/77324661/179217852-1fe20794-8012-4045-9ceb-195573e4cddc.png)
![735b82e2a77ec0f9b823e9349f5af3f](https://user-images.githubusercontent.com/77324661/179217871-0e35ea2b-d328-45a5-aa25-d3d2ba0d3fbf.png)

**Comment by youliyuan-fit2cloud** [comment]
情况1 未复现，建议升级到最新的v1.20.10-lts
情况2 复现了，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
情况2即将发布的版本v1.20.11-lts和v2.0中已修复
