### ISSUE TITLE
[BUG]接口测试>>导入接口：导入接口后，接口参数中的描述显示位置异常，只能在高级设置里参看。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#15844]
### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>导入接口：导入接口后，接口参数中的描述显示位置异常，只能在高级设置里参看。此描述应该在参数定义中显示吧。

### 重现步骤

[BUG]接口测试>>导入接口：导入接口后，接口参数中的描述显示位置异常，只能在高级设置里参看。此描述应该在参数定义中显示吧。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/179336797-7ce1602e-9669-46ad-b86b-ffabd48fbb91.png)

**Comment by zyyfit** [comment]
没有复现这个问题，方便把复现文件上传一下吗

**Comment by huangxine** [comment]
![image](https://user-images.githubusercontent.com/78218624/180110501-e5305d4e-3b1d-4a7c-85c3-a4c073bb96cc.png)

**Comment by zyyfit** [comment]
> ![image](https://user-images.githubusercontent.com/78218624/180110501-e5305d4e-3b1d-4a7c-85c3-a4c073bb96cc.png)

这个页面上就没设计显示描述字段，要看描述肯定要打开设置按钮看呀
