### ISSUE TITLE
[BUG]后置操作：prev.setResponseMessage,message没有修改

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#15849]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

在后置脚本里面：
prev.setResponseMessage("你好");
log.info(prev.getResponseMessage());

但是，响应体里面还是没有修改

### 重现步骤

后置脚本：
![image](https://user-images.githubusercontent.com/15188833/179437281-b4d8150d-64c3-43ea-962c-cec069d89ceb.png)

控制台：
![image](https://user-images.githubusercontent.com/15188833/179437322-ee15c014-6643-4dd2-a173-46209416da7c.png)

响应体：
![image](https://user-images.githubusercontent.com/15188833/179437369-eed13a79-1e54-4175-9ce7-201dd78ac971.png)

**Comment by zyyfit** [comment]
您好，jmeter也是这样的，您可以查一下 prev.setResponseMessage() 这个方法的用法

**Comment by startpjx** [comment]
jmeter 里面，在取样器有显示，但是ms 好像没有对jmete r做对接
脚本：
![image](https://user-images.githubusercontent.com/15188833/179648275-a87e4494-049f-4690-9c35-7e40c7aaecb5.png)

取样器结果展示：
![image](https://user-images.githubusercontent.com/15188833/179648398-d7ee509d-239c-4166-860e-0841298748ce.png)

**Comment by zyyfit** [comment]
这个地方是取样器结果，并不是请求结果，请求结果在 响应数据里展示，我们系统执行测试是使用的jmeter执行，只是没显示取样器结果，直接展示了请求结果
