### ISSUE TITLE
[BUG]UI测试报告里面的测试截图跟实际被测系统的系统文字不一样，被测试系统文字是中文，测试报告里面的测试截图是英文。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#15845]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

UI测试报告里面的测试截图跟实际被测系统的系统文字不一样，被测试系统中文，测试报告里面的测试截图是英文。
测试报告截图如下
![25880c22621f29cf830949af2228695](https://user-images.githubusercontent.com/83771182/179391555-c94f8fbe-7302-48a0-a1df-b193735a405b.png)
被测系统截图如下
![bf6abe784a33af2d7912b130d83da53](https://user-images.githubusercontent.com/83771182/179391689-bc89e2ae-41a7-4d73-8d37-cbb8fb2963bc.png)

### 重现步骤

录制ui脚本进行测试，选择后台执行，UI测试报告里面的测试截图跟实际被测系统的系统文字不一样，被测试系统中文，测试报告里面的测试截图是英文。

### 期待的正确结果

UI测试报告里面的测试截图跟实际被测系统的系统文字应一样

**Comment by zyyfit** [comment]
1.20.11已修复
