### ISSUE TITLE
[BUG] Can't stop task

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#15846]
### MeterSphere 版本

版本:   v1.20.1-lts-64d951ea

### 使用外置数据库

否

### 问题描述

![Uploading image.png…]()

### 重现步骤

start task
stop task

![image](https://user-images.githubusercontent.com/5927005/179403761-d92c5329-b95c-4ecc-9f98-78c074967357.png)

**Comment by zyyfit** [comment]
There is no operation problem. Is it convenient to upload JMX files ？

**Comment by matthewxuda** [comment]
It will fill up my computer resources

**Comment by zyyfit** [comment]
> It will fill up my computer resources

Can you upload the jmx file in this test ?

**Comment by matthewxuda** [comment]
It will fill up my computer resources when I stop the performance test, and after I remove the report, it is OK now
