### ISSUE TITLE
[BUG]未设置标签，点击保存后，用例全没了

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#15841]
### MeterSphere 版本

v1.20.8-lts-ba947709

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/42445400/179209591-d801a039-01f3-4809-ad19-b6714df0a9d3.png)
![image](https://user-images.githubusercontent.com/42445400/179210330-3b7813ca-e9e8-4d47-b103-dbc6024b8e52.png)
未设置用例标签，点击保存，提示保存成功，但是用例全没了

### 重现步骤

1.脑图编写用例，添加二级子模块
2.在二级子模块添加用例（未设置用例标签）
3.点击保存按钮
![image](https://user-images.githubusercontent.com/42445400/179209591-d801a039-01f3-4809-ad19-b6714df0a9d3.png)

### 期待的正确结果

不允许保存，或者数据正常显示

**Comment by zrfit** [comment]
未复现该问题，保存后再次点击二级模块的展开按钮可查看保存的数据。
<img width="997" alt="image" src="https://user-images.githubusercontent.com/99731894/179215136-8055700e-4fbd-4622-b299-105272a97841.png">

**Comment by lyxlin** [comment]
未复现该问题，保存后再次点击二级模块的展开按钮可查看保存的数据。
======================================================
保存后刷新页面或切换其他模块
再切换回该模块可复现

**Comment by zrfit** [comment]
最新版本无该问题，未带用例标签保存后-刷新页面/可换tab页再返回查看-仍可看到脑图添加的数据，可升级下。

**Comment by lyxlin** [comment]
![image](https://user-images.githubusercontent.com/42445400/179894609-9a8ffca9-adc0-4773-8e43-7e6b88c7195f.png)

1.手动展开节点可以，但是每个模块的用例只剩一条
![image](https://user-images.githubusercontent.com/42445400/179894510-60966da9-22c3-4253-817b-36fc44960d18.png)

2.左上角的展开按钮一键展开则无法展开
![image](https://user-images.githubusercontent.com/42445400/179894536-787e9025-2ae4-46e8-8cc6-e56f1651622f.png)

**Comment by zrfit** [comment]
您好，最新版本v1.20.10-lts不存在该问题，可升级下。

**Comment by lyxlin** [comment]
已更新到最新版本，还是有问题

https://user-images.githubusercontent.com/42445400/180676683-3784d391-5ab2-4130-bf81-c8539c0e25d7.mp4

**Comment by zyyfit** [comment]
1.20.11修复，请等待版本发布后验证
