### ISSUE TITLE
[BUG]请求体为json的入参，当value的字段很长时，光标对应不正确

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#15854]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.9-lts

### 使用外置数据库

否

### 问题描述

1、请求体为json的入参，当value的字段很长时，光标对应不正确，输入的字符不在光标展示的位置，而是后面的某个字符开始
2、cloud环境可复现

### 重现步骤

1、接口请求快捷调试，入参选择请求体的json
2、找一张图片，转成base64
3、写一个json，将base64的字符串复制到value，然后拖动下面的滚动条到后面，选择一个点进行输入字符
<img width="1438" alt="1" src="https://user-images.githubusercontent.com/72729206/179442936-1193cb5a-fc8b-4708-8f0c-2278a835872c.png">
4、可以发现，我在1位置（YW之间）开始打字符，结果字符出现在2的位置，然后光标出现在3的位置了
5、json-schema是正常的，只是json格式存在这个问题

### 期待的正确结果

1、在选择的光标后面出现输入的字符

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
研发说这是组件的问题，这个问题如果影响不严重的话就暂时先不改了？

**Comment by fit2cloud-yangxiaoyan** [comment]
> 研发说这是组件的问题，这个问题如果影响不严重的话就暂时先不改了？

好的
