### ISSUE TITLE
[BUG]测试跟踪-测试用例-选择左边某个目录，导出的用例为全部用例

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#1585]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
测试跟踪-测试用例-选择左边某个目录，导出的用例为全部用例
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
导出用例应该为选择的某个目录下的用用例
**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
目前是以勾选为准，后续会优化下这里
