### ISSUE TITLE
[BUG]接口测试，当Content-Type: application/x-www-form-urlencoded时，每个参数后面会自动拼接%0D

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#15851]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

接口测试，当Content-Type: application/x-www-form-urlencoded时，每个参数后面会自动拼接%0D，导致请求不成功。
![image](https://user-images.githubusercontent.com/104960608/179441320-15cab362-3f32-46e2-b76f-e6d3ab4af68d.png)

![image](https://user-images.githubusercontent.com/104960608/179440727-f5172837-224c-41cc-ba71-81a2418743b6.png)

### 重现步骤

1.定义接口，在 请求体 选择 x-www-form-urlencoded 
2.将参数批量添加
`
PageIndex:1
QTendProjectNameNo:
TenderName:
QTendWays:0
IsOpenBid:0
QMenuName:全部
QOpenBidStratTime:
QOpenBidEndTime:
IsUseCA:2
ProjectStateType:0
QueryType:0
`
3.点击发送，在请求内容处看看，是否有%0D出现

**Comment by zyyfit** [comment]
您好。也是批量添加的，没有复现这个问题，您是不是用什么文本编辑器复制的，导致有换行或者什么看不到的字符？可以手动换行试试。
![image](https://user-images.githubusercontent.com/73461316/179499954-73099929-1ba8-4d75-996b-d7bce2551585.png)

**Comment by zhangzhaox** [comment]
我之前也出现了这个问题现象，%0D 这个字符是啥也不知道，  怀疑是复制字符串是带入的特殊字符

**Comment by zhangzhaox** [comment]
@2lipan 你的参数 是从别的地方复制过来的吧，我这边之前也出现过这个现象，手动书写下参数字符就可以了
