### ISSUE TITLE
[FEATURE]用例执行模块，执行详情页，建议将 用例标题 放出全文显示，不要 使用...省略

### ISSUE THREAD

**Issue by goblinintree** [metersphere/metersphere#15867]
### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

执行详情页，建议将 用例标题 放出全文显示，不要 使用...省略

### 附加信息

<img width="546" alt="image" src="https://user-images.githubusercontent.com/5347862/179470120-75d567dc-dfa5-4d5f-806c-3fcb17ad4ce1.png">

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
