### ISSUE TITLE
[BUG] UI自动化脚本，后端调试运行通过，换成生成报告运行，最后一步移除小票断言失败，两个种运行结果不一致

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#15861]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

创建UI自动化脚本，后端调试运行通过，换成生成报告运行，最后一步移除小票断言失败，两种运行结果不一致

后端调式 执行结果
![image](https://user-images.githubusercontent.com/45531073/179453900-2c2dbc34-0a09-42ed-bd48-e29366b64faa.png)

生成报告 执行结果
![image](https://user-images.githubusercontent.com/45531073/179453934-5c1915bb-28f0-48ac-bbc7-79c95874ddfb.png)

报错信息如下：
<html>
<body>

sent | Expected condition failed: waiting for presence of any elements located by By.xpath: //*[@id="SeaBookingBookingWorkspaceCargoLeftRightResizeElTabsElTabPaneTabBookingMasterCargoAgGride"]/div/div[2]/div[2]/div[3]/div[2]/div/div/div[1]/div[1]/div/div/div/div[2]/input (tried for 15 second(s) with 500 milliseconds interval) Build info: version: '4.1.4', revision: '535d840ee2' System info: host: 'metersphere-server-689c647f5c-zwlm4', ip: '172.16.1.60', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.el7.x86_64', java.version: '11.0.14' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: /tmp/.com.google.Chrome.op43Um}, goog:chromeOptions: {debuggerAddress: localhost:33953}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: ANY, platformName: ANY, proxy: Proxy(system), se:cdp: ws://172.16.0.61:4444/sessi..., se:cdpVersion: 103.0.5060.53, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, version: , webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Session ID: 83748d4e012d5e0cb61fb457fc09db08
-- | --

</body>
</html>

### 重现步骤

1.导入UI自动化脚本
2.使用后端调试运行，查看运行结果
3.使用生成报告运行，查看运行结果

### 期待的正确结果

后端调试和生成报告运行结果一致，后端调试通过，生成报告运行也是通过的

### 附加信息
自动化脚本
[Uploading Metersphere_Ui_CARGOWARE (9).side…]()

**Comment by zrfit** [comment]
您好，您的文件未上传成功，企业微信私聊您了，单独发我下吧。

**Comment by liushuneng** [comment]
文件私聊发你了

**Comment by zyyfit** [comment]
1.20.11版本和2.0.1版本都会修复这个问题，请等待版本发布后验证
