### ISSUE TITLE
[BUG]事务控制器下添加事务控制器，场景调试内层事务控制器下步骤调试一直测试中，测试报告显示未执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#15873]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.10

### 使用外置数据库

否

### 问题描述

1.事务控制器下添加事务控制器，场景调试内层事务控制器下步骤调试一直测试中
![测试中](https://user-images.githubusercontent.com/103627487/179479042-34141b82-671e-4ba1-91e0-197828a91f39.png)

2.执行场景，场景未执行结束之前内层事务控制器下步骤测试报告显示成功，执行结束内层事务控制器下步骤测试报告回显未执行。
![6OU7HMePBl](https://user-images.githubusercontent.com/103627487/179479339-e7a8bb83-eb54-4bf9-b6fc-0d1a438bb4e0.jpg)
![VHFJaGCMSF](https://user-images.githubusercontent.com/103627487/179479406-0a2f7ed4-bbc7-4de3-aa39-db62593e49df.jpg)

### 重现步骤

1.在场景中添加事务控制器
2.在事务控制器的下面添加事务控制器
3.点击调试
4.执行场景，查看报告

### 期待的正确结果

场景调试正常，报告正常展示

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~
