### ISSUE TITLE
[QUESTION] 能否支持自定义case id

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1588]
**请描述您的需求或者改进建议.**
**请描述你建议的实现方案**

隐藏库唯一id, 增加对自定义 case id的支持
![image](https://user-images.githubusercontent.com/38770463/110264117-79ab9300-7ff3-11eb-83a5-d4a036fbc034.png)

**Comment by xulinde** [comment]
收到，我们内部讨论下再反馈

**Comment by wonderfulwxw** [comment]
@xulinde 主要是case导入后是乱序的， 其实一般来说以表格形式记录的case是按照特定顺序记录的，方便查阅且是有意义的。

能否以表格记录的条目顺序导入。

或者> 

支持自定义case id 列来进行排序。

希望能支持。 谢谢。

**Comment by xulinde** [comment]
1.9.0支持自用例id
