### ISSUE TITLE
[BUG]无法向“循环控制器”中拖动场景，循环控制器中须有接口api后，场景才可以拖动到循环控制器中

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#1590]
**MeterSphere 版本**
版本: v1.7.3-2b9713b1

**Bug 描述**
如题，无法向“循环控制器”中拖动场景，循环控制器中须有接口api后，场景才可以拖动到循环控制器中

**Bug 重现步骤**
1.  建立一个场景A
2. 再新建一个场景B，放入“循环控制器”，然后拖动场景A到循环控制器下

**期待的正确结果**
正确结果：可以拖动场景A到循环控制器下。

测试结果：无法拖动场景A到循环控制器下。
**截图**
如附件
![tmp](https://user-images.githubusercontent.com/5140999/110326210-50225400-8053-11eb-929c-ff5035862a3f.png)

**Comment by xulinde** [comment]
收到，下个版本修复

**Comment by xulinde** [comment]
v1.8已修复
