### ISSUE TITLE
[BUG]场景断言，在外层组件已禁用的情况下，脚本断言功能仍生效，功能实现有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#15901]
### MeterSphere 版本

1.20.9lts

### 使用外置数据库

否

### 问题描述

添加场景断言，并设置脚本断言，在外层场景断言组件已禁用的情况下，脚本断言功能仍生效

### 重现步骤

1.添加场景断言组件，并设置脚本断言，设置完成后，禁用该场景断言，执行接口自动化测试，查看测试情况；

### 期待的正确结果

1.该接口测试自动化测试无断言判断；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/179651774-10864d89-0166-4b2b-99be-9bb75270d1d4.png)
![image](https://user-images.githubusercontent.com/92150453/179651835-bd370657-46c8-4660-8cf2-ef26c0ac9781.png)

**Comment by youliyuan-fit2cloud** [comment]
请用最新版本尝试复现~
你这个场景怎么实现？请描述下条件控制器里面怎么添加的场景断言，而且条件控制器下面的循环控制器？

**Comment by sageonedream** [comment]
在1.20.10lts版本中场景断言已无法在条件控制器下添加，以前的版本存在此问题，且升级过来时，此问题仍然会保留并存在
(备注：此问题现在变成历史遗留问题，在当前最新版本，可以默认为非问题，但不建议以非问题关闭)
![image](https://user-images.githubusercontent.com/92150453/179881309-f4d7f07b-b39b-4041-b487-26e2419bcffe.png)

**Comment by xulinde** [comment]
1.场景断言已禁用，脚本断言仍生效，这个是缺陷；
2.条件控制器下可以添加场景断言，这个应该是历史版本的缺陷，您这条属于脏数据可以删除重新创建

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~
