### ISSUE TITLE
[FEATURE]测试跟踪-功能用例-用例列表：搜索出来的用例无法使用脑图查看

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#15926]
### MeterSphere 版本

v1.20.8-lts

### 请描述您的需求或者改进建议

用例列表使用搜索或高级搜索，筛选出来的用例只能通过列表的方式查看，希望切换到脑图模式也展示对应筛选出来的用例

**Comment by Hyyfit** [comment]
感谢反馈，待调研后，规划排期。
