### ISSUE TITLE
[v1.6]

### ISSUE THREAD

**Issue by TangYouLong** [metersphere/metersphere#1592]
1.在模块选择时，在没有建立模块的情况下，点击去添加按钮

![image](https://user-images.githubusercontent.com/47670867/110413217-71715780-80c8-11eb-9b3d-0357faa8372c.png)

2.提示请输入名称
![image](https://user-images.githubusercontent.com/47670867/110413278-8c43cc00-80c8-11eb-9e3b-0a1dc43fef28.png)

**Comment by xulinde** [comment]
这里的提示是指左边模块树未输入名称
![image](https://user-images.githubusercontent.com/64065190/110457447-9cc66780-8105-11eb-8481-1f01001e5f93.png)
