### ISSUE TITLE
[BUG]v1.20.10 环境配置 - http配置 - 启用条件选择模块 - 选择模块保存后无法删除

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15958]
### MeterSphere 版本

v1.20.8 v1.20.10

### 使用外置数据库

是

### 问题描述

环境配置 - http配置 - 启用条件选择模块 - 选择模块保存后无法删除

### 重现步骤

环境配置 
http配置
启用条件选择模块 
选择模块保存
然后重新编辑选择的模块，删除一些模块
点击更新、保存，不生效

### 期待的正确结果

正常删除模块

### 附加信息

![image](https://user-images.githubusercontent.com/20641051/179731241-6e6d9cdf-6404-4071-81d7-6301d95d6fd6.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，在即将发布的v1.20.11-lts和v2.0版本中已修复。
