### ISSUE TITLE
[BUG] v1.20.8 连续两个小时以上编写调试自动化用例后，websocket connect fail

### ISSUE THREAD

**Issue by lijinzhou2016** [metersphere/metersphere#15959]
### MeterSphere 版本

v1.20.8

### 使用外置数据库

是

### 问题描述

连续两个小时以上编写调试自动化用例后，websocket connect fail
点击调试按钮则看不到响应

### 重现步骤

连续两个小时以上编写调试自动化脚本

### 附加信息

![image](https://user-images.githubusercontent.com/20641051/179731912-fed58c4c-a7ee-46d4-80eb-775cb42a2a15.png)

**Comment by 35plus** [comment]
这是一个挺好的场景下的问题

**Comment by zhangzhaox** [comment]
这会不会跟 偶发的 执行单步测试用例，一直转圈撒
