### ISSUE TITLE
[BUG] 环境配置，通用配置，如果定义很多的变量，比如30~50个，会出现测试计划里批量跑场景时，比如上百个场景，偶现有些场景里的变量没有被替换。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#15975]
### 联系方式

王进

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

环境配置，通用配置，如果定义很多的变量，比如30~50个，会出现测试计划里批量跑场景时，比如一个计划里上百个场景，每个场景十几步，偶现有些场景里的变量没有被替换。

### 重现步骤

这是一个偶发的问题。客户这边的情况：
1. 定义了大量的环境，（客户是国际化团队，不同环境应对不同国家客户的测试），每个环境里，通用配置下面定义了一长串变量，金融行业，比较常见。
2. 创建了140个场景，每个场景步骤也比较复杂，动不动几百行场景变量，行业特性。
3. 测试计划里有140个场景。
4. 每天定时跑，时不时出现，一部分场景失败，一排查，是 环境配置下面的通用配置下面的变量 没有被替换，而且只是某几个变量没有被替换，比如 邮箱的变量。

### 附加信息

这个问题，内部复现有难度，希望开发 就像解决上次 测试报告 统计错误那样，看一下 这块的设计思路，结合用户的场景，做一些优化。不然这个问题会永远困扰客户。

**Comment by xulinde** [comment]
我们先试着内部复现下～

**Comment by fit2-zhao** [comment]
感谢您的反馈，开发并未发现该问题，希望能提供更多线索，比如相关日志，执行方式等，都需要描述清楚，这样便于开发排查。

**Comment by 35plus** [comment]
好的，我再联系客户看看
