### ISSUE TITLE
[FEATURE]编辑测试用例标签时，应加入已有标签搜索联想功能

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#1597]
使用的版本：1.7.2

**请描述您的需求或者改进建议.**
1.7版本后允许为测试用例添加标签，但在添加时，无法快速搜索到已新建过的标签，不太方便

**请描述你建议的实现方案**
希望能在添加标签时自动展示匹配关键字的已有标签推荐
![图片](https://user-images.githubusercontent.com/11419548/110568597-2faae480-818e-11eb-9c8e-5ffe15874d54.png)

**Comment by xulinde** [comment]
感谢反馈，我们内部讨论下再反馈
