### ISSUE TITLE
[BUG]脚本的代码模版错误

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1598]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
脚本的代码模版错误
**Bug 重现步骤**
1.  添加自定义脚本或者前置后置脚本
2. 选择语言不是beanshell
3. 点选任意模版名称
4. 脚本依然是beanshell的

**期待的正确结果**
正确情况下应该是什么样的？
各语言模版正确可用
**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
收到，下个版本会修复

**Comment by xiongxiaoqing614** [comment]
月底的1.8会修复吗？

**Comment by zyyfit** [comment]
v1.8.0版本已修复，请升级到v1.8.0再试一下

**Comment by xiongxiaoqing614** [comment]
1.8.0仍然存在，选择python后输出的还是beanshell的脚本
![image](https://user-images.githubusercontent.com/72964047/112982347-f5ca6e00-918e-11eb-880b-7e2b9368b60e.png)

**Comment by zyyfit** [comment]
隐藏报文长度这块内置代码是针对tcp请求的groovy脚本，目前已经关掉了python里的入口
