### ISSUE TITLE
[BUG]执行场景用例时，后置脚本不小心写了个while死循环，虽然点击了 停止，但是之后的用例执行，控制台输出一直是空白

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#15983]
### MeterSphere 版本

1.20.8

### 使用外置数据库

是

### 问题描述

执行场景用例时，后置脚本不小心写了个while死循环，虽然点击了 停止，但是之后的用例执行，控制台输出一直是空白，重启服务后才好了，怀疑 停止运行，并不能停止死循环执行。

### 重现步骤

1.执行场景用例时，后置脚本不小心写了个while死循环。
2.点击 停止 执行；

结果：之后所有的用例执行，控制台输出一直是空白，重启服务后才好了，怀疑 停止运行，并不能停止死循环执行。
<img width="383" alt="022961ad5bc460cad9701c2f656f0af" src="https://user-images.githubusercontent.com/100331967/179921775-48567a72-3c5c-47fe-88c8-15d5a6266e84.png">

**Comment by xulinde** [comment]
已经加入线程中的无法强制停止，while 死循环由超时时间控制，建议使用时 超时时间不要搞太大，贴合自身业务设置。
