### ISSUE TITLE
[FEATURE] 测试计划里面，失败/阻塞的用例，可以直接打标签，以提供下一次迭代做参考/再次执行

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1599]
**请描述您的需求或者改进建议.**
测试计划里面，失败/阻塞的用例，需要重点关注，比如下一次迭代回归测试用。但目前给用例打标签，需要回到测试用例管理页，找到这个用例，打标签，步骤比较繁琐

**请描述你建议的实现方案**
1. 测试计划里面，失败/阻塞的用例，可以直接打标签，以提供下一次迭代做参考/再次执行
2. 可以加一个跳转，回到用例编辑页

![image](https://user-images.githubusercontent.com/11580681/110571301-53702980-8192-11eb-95c6-e3e7d8ab3a11.png)

**Comment by xulinde** [comment]
收到，后面版本优化下这里

**Comment by xulinde** [comment]
1.10已优化
