### ISSUE TITLE
[FEATURE]响应内容针对不同类型 提供选项进行格式化

### ISSUE THREAD

**Issue by wjangelking** [metersphere/metersphere#16]
**请描述您的需求或者改进建议.**
![微信图片_20200617124840](https://user-images.githubusercontent.com/17584830/84856305-ef07ba00-b098-11ea-89f3-4d864a58b7c3.png)

响应内容不能针对不同类型进行格式化

**请描述你建议的实现方案**

响应内容针对不同类型 提供选项进行格式化

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
