### ISSUE TITLE
[BUG] 接口路径修改后，case可以修改，但被场景引用后，再次修改case请求接口，场景中接口路径没有同步更新

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1600]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7
**Bug 描述**
简要描述您碰到的问题
接口路径修改后，case可以修改，但被场景引用后，再次修改case请求接口，场景中接口路径没有同步更新
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
可以批量编辑变更用例路径，然后场景那里引用用例，能满足你的需求
![image](https://user-images.githubusercontent.com/64065190/110741888-5fcab400-8270-11eb-8fe2-8f55a8e419f8.png)
