### ISSUE TITLE
[BUG]场景导入到项目，”引用“标签发生改变

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16013]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

cloud

### 使用外置数据库

否

### 问题描述

目录：接口定义--接口自动化
描述：
1.在A项目把场景导出，导入到B项目，场景里面的标签”引用“--A项目，到了B项目是”复制“

### 重现步骤

A项目：引用
![image](https://user-images.githubusercontent.com/15188833/179940940-7784dfc5-3500-4ca8-815b-528e753611eb.png)

B项目：复制
![image](https://user-images.githubusercontent.com/15188833/179941076-a75989cb-13e7-4c4c-bb0b-5c58f6b1f7cf.png)

**Comment by xulinde** [comment]
设计如此～
<img width="870" alt="image" src="https://user-images.githubusercontent.com/64065190/180127582-e597406c-6062-4433-ab79-681d4e9f4941.png">
