### ISSUE TITLE
性能测试导入时增加更多文件格式

### ISSUE THREAD

**Issue by galyin** [metersphere/metersphere#1603]
**请描述您的需求或者改进建议.**
性能测试时，由于metersphere的独立jmeter调用，对于额外配置文件的引用一般通过随脚本一起导入实现，而目前导入脚本时只支持jmx和csv等有限的文件格式，对于xml等文件则无法导入。

**请描述你建议的实现方案**
希望在导入页面，增加更多的导入格式

**Comment by luty2018** [comment]
@liuruibin 去掉文件格式限制吧
