### ISSUE TITLE
[BUG]带响应断言的jmx文件传到平台后，断言逻辑就错了

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16041]
### 联系方式

MeterSphere交流群14 范德华力

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

![6d0d03bf10f2476928215dbd00f12f4](https://user-images.githubusercontent.com/33822034/180112786-bc5f0215-9f62-4ccf-b6ce-0397a415eb62.png)
上面三个断言是从jmeter直接过来的，jmeter里设置的效果等同于平台上最后一个断言

### 重现步骤

jmeter里添加响应断言，效果是，报500，502，504的都抛出错误提示

**Comment by xulinde** [comment]
我没太明白您想反馈啥问题，能详细描述下，重现步骤、预期结果、实际结果吗？

**Comment by nobody1121** [comment]
我在本地jmeter断言里实现了这个效果(?s)^((?!504).)*$，但导入到ms平台后，就变成了504，这样就导致断言失败了

**Comment by xulinde** [comment]
明白了，我用v1.20.10-lts试了下是正常的，建议您升级下版本～

**Comment by nobody1121** [comment]
好，等我验证没问题了回来关掉bug
