### ISSUE TITLE
[FEATURE]文件夹不能批量操作

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16045]
### MeterSphere 版本

v1.20.9-lts

### 请描述您的需求或者改进建议

图片中的文件夹，不能批量删除和移动，不方便，希望同级的文件夹可以批量操作
![列表文件夹](https://user-images.githubusercontent.com/75236887/180113897-7cdb4399-83b9-48af-90e2-928ca6c6430a.png)

**Comment by Hyyfit** [comment]
感谢反馈，暂不考虑该功能。
