### ISSUE TITLE
[FEATURE]用例模板中，已选字段功能下面选择的系统字段、自定义字段不能按需要设置在用例中的显示顺序

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16043]
### MeterSphere 版本

v1.20.9-lts 

### 请描述您的需求或者改进建议

用例模板中，已选字段功能下面选择的系统字段、自定义字段不能按需要设置在用例中的显示顺序，希望可以按需要设置显示顺序
![用例截图](https://user-images.githubusercontent.com/75236887/180113518-9903bcba-b967-4564-8479-b0596abd105a.png)

### 请描述你建议的实现方案

在用例模板中的排序显示

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
