### ISSUE TITLE
[FEATURE]建议提供一个类似YApiUpload的插件，供研发使用将接口自动同步到meterSphere

### ISSUE THREAD

**Issue by panny92** [metersphere/metersphere#1604]
**请描述您的需求或者改进建议.**

开发人员不支持用swagger，对代码有侵入

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/13617590/110586078-917a4700-81ac-11eb-91e6-74656b02fd92.png)

YApiUpload

**Comment by panny92** [comment]
可以说一下啥时候能上线吗

**Comment by pencui** [comment]
> 可以说一下啥时候能上线吗
大佬，这个插件源码好像没有上传全吧，编译不通过啊，原作者认识吗

**Comment by zyyfit** [comment]
1.15.0已经增加了这个功能
