### ISSUE TITLE
[FEATURE]最后的测试报告耗时没有加上等待控制器的时间

### ISSUE THREAD

**Issue by laovvvcom** [metersphere/metersphere#16044]
### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 请描述您的需求或者改进建议

建议最后的耗时加上sleeptime，接口测试的耗时不是压测的响应时间，可以加上sleeptime

**Comment by Hyyfit** [comment]
感谢反馈，设计如此。
