### ISSUE TITLE
[BUG] 模块下有子模块时swagger重新导入不会覆盖子模块

### ISSUE THREAD

**Issue by ryanrain2016** [metersphere/metersphere#16052]
### 联系方式

ryan@top365.ml

### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

是

### 问题描述

模块下有子模块时swagger重新导入不会覆盖子模块

### 重现步骤

1. 接口导入是使用swagger url导入，swagger中包含分组
2. 第一次导入接口，正常保存，每个分组会创建为子模块
3. 开发人员开发了新的接口，创建了新的分组，再次导入该swagger， 选择覆盖导入
4. 会出现新的分组会创建为子模块，但是新分组下的接口，全部没有导入成功
5. 发现导入成功了，但是会到未规划的接口中

### 期待的正确结果

导入时新分组也能正常覆盖导入到相应的子模块

**Comment by zyyfit** [comment]
1.20.10优化了导入逻辑，请升级后使用
