### ISSUE TITLE
[FEATURE]测试集里有一个error，整个报告就是error

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16053]
### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/33822034/180119052-0fe3a671-4ac2-4d0a-a900-8ee3ebc9e1f8.png)
不能因为只有少数error，整个报告状态就显示error，不实际也不美观

**Comment by Hyyfit** [comment]
感谢反馈，目前设计如此。
