### ISSUE TITLE
[BUG]自定义的用例模板创建的用例，用脑图模式报错打不开

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16056]
### 联系方式

yujie@swirecocacola.com

### MeterSphere 版本

v1.20.9-lts 

### 使用外置数据库

否

### 问题描述

使用自定义的用例模板创建的用例，用脑图模式报错打不开，自定义模板里面加了8个自定义字段
![报错](https://user-images.githubusercontent.com/75236887/180136731-b900929e-648d-48d3-9473-7694e5d18f2b.png)
![模板](https://user-images.githubusercontent.com/75236887/180136801-836cc0ed-d200-4e43-af67-cd164799ffb6.png)

### 重现步骤

1.创建自定义用例模板，添加自定义字段，有多选、单选、单选框、文本框、输入框等属性的
2.将项目使用的用例模板设置为自定义的这个
3.创建用例，自定义字段非必填的不填写，用例写好后保存
4.使用脑图功能查看刚才编辑的文件夹，报错

### 期待的正确结果

可以正常显示脑图模式

**Comment by yujie2011** [comment]
自定义模板内容：
![模板2](https://user-images.githubusercontent.com/75236887/180137437-93ac96a4-5497-40bc-9b64-1a60e8ed5e9d.png)

**Comment by yujie2011** [comment]
报错的用例详情：
![用例](https://user-images.githubusercontent.com/75236887/180137630-abfa1413-3e6b-4937-8c91-1662d00a64e7.png)

**Comment by xulinde** [comment]
v1.20.10-lts未复现该问题，建议您升级到最新版本～
