### ISSUE TITLE
[BUG]模板管理模块编辑测试用例模板时，将已添加的自定字段删除后，再次添加和已删除自定义字段名字相同的字段时，会添加失败。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#16066]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

模板管理模块编辑测试用例模板时，设置自定义字段时添加名字为123的字段后，删除该字段，再次添加名字一样的123字段，会提示该字段已存在。
![image](https://user-images.githubusercontent.com/83771182/180141205-1f2081af-f1fc-4900-b1cc-0fa86d9c88ed.png)

### 重现步骤

设置自定义字段添加字段后，删除该字段，再次添加名字一样字段，会提示该字段已存在。导致该字段无法添加成功。

### 期待的正确结果

已添加的自定字段删除后，可添加和已删除字段名字相同的字段。

**Comment by xulinde** [comment]
这里只是取消关联，删除的话需要去【自定义字段】列表那里删
