### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by kingkiller2022** [metersphere/metersphere#16061]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

缺少邮件阅读者取样器，无法从邮箱获取验证码
![af098f919f7588f54bdabc0c81c9f6e](https://user-images.githubusercontent.com/109718057/180140723-30d9db85-bb8e-447b-b9b3-21b77514e45d.png

不能真实的实现现实中获取验证码  注册完成的操作

**Comment by Hyyfit** [comment]
感谢反馈，待调研后规划。

**Comment by kingkiller2022** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
