### ISSUE TITLE
[BUG]接口-快捷调试，另存为新用例，在另存为新用例页面，在前置脚本中贴代码，点击保存，保存不成功。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#16078]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

接口-快捷调试时，点击另存为新用例，在另存为新用例页面，在前置脚本中贴入代码，点击保存，页面提示有报错，保存不成功。
![image](https://user-images.githubusercontent.com/104960608/180156219-b0c5a4a9-5321-4c9d-bd5b-9da2b12878fd.png)

### 重现步骤

1.接口-快捷调试，点击 另存为新用例 
![image](https://user-images.githubusercontent.com/104960608/180155323-3eddb7d2-5cc5-45e0-aea4-550e7150c81c.png)

2.在该页面，前置操作里贴入如下脚本
`
import org.apache.jmeter.config.Arguments;
import java.util.Map.Entry;
import cn.vpclub.ubp.UbpSecret;
import cn.vpclub.sst.SstSecret;
import cn.vpclub.ubp.UbpSign;
import cn.vpclub.sst.SstSign;

log.info(vars.get("sign"));
Arguments arguments = sampler.getArguments(); // 调用时注意sampler小写
String body = arguments.getArgument(0).getValue();
log.info("获取请求体:\n{}",body)
String reqEncryptStr = SstSecret.requestEncrypt(body);  //随身厅
//String reqEncryptStr = UbpSecret.requestEncrypt(body);   //网格通
log.info("加密报文{}",reqEncryptStr);

//对body体进行赋值
arguments.getArgument(0).setValue(reqEncryptStr);
String secBody = arguments.getArgument(0).getValue();
log.info("加密后请求值{}",secBody);

String clientIp="127.0.0.1";
String version ="1.0.0";
String appId ="100000054";
String timestamp = String.valueOf(System.currentTimeMillis());

vars.put("clientIp", clientIp);
vars.put("version", version);
vars.put("timestamp", timestamp);
vars.put("appId", appId);

// SstSign 随身厅
String sign = SstSign.builder().clientIp(clientIp)
                .timestamp(timestamp)
                .version(version)
                .appId(appId)
                .requestBody(reqEncryptStr)
                .build().generate();
//UbpSign 网格通
/**
String sign = UbpSign.builder().clientIp(clientIp)
                .timestamp(timestamp)
                .version(version)
                .requestBody(reqEncryptStr)
                .build().generate();
*/
log.info("随身厅请求签名生成功{}",sign);

vars.put("sign", sign);
`
![image](https://user-images.githubusercontent.com/104960608/180155718-8d35b7a8-0da6-42d8-85e6-a0487f08ca25.png)

3.输入用例名称，选择环境，点击保存，会出现错误提示
![image](https://user-images.githubusercontent.com/104960608/180156377-49d073fe-5450-40f1-b43a-89d42d511c90.png)

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
