### ISSUE TITLE
[BUG] 编辑参数值页面，添加函数后，不能取消添加函数，再次点击添加函数，出现多个函数列表

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16074]
### 联系方式

18311441708

### MeterSphere 版本

1.20.10.lts

### 使用外置数据库

否

### 问题描述

![dae9da893080d919054d5ab6595229b](https://user-images.githubusercontent.com/103925124/180148835-2b7fbd91-7152-4d16-a4de-38f0119ea3b5.png)
去掉红框部分后，点击预览，带函数的会刷新回来，没有联动
![image](https://user-images.githubusercontent.com/103925124/180149380-145d74ef-78b9-438e-bf94-8b1022c39f06.png)

### 重现步骤

 ①编辑参数值页面，点击添加函数，选中函数后，再次点击添加函数，可出现2列函数列表
②添加的函数不能取消，文本框去掉函数内容后，点击预览，带函数的文本会刷新回来

### 期待的正确结果

不可添加多次函数；
添加的函数可取消

**Comment by xulinde** [comment]
企业微信已回复
