### ISSUE TITLE
[BUG]接口数量用例统计，相同的接口累加统计了

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16090]
### 联系方式

MeterSphere交流群14 范德华力

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33822034/180163301-70ef6f39-84ff-48ea-9f64-5eceb6e0f2f0.png)
328正确，544是连覆盖导入的用例也加了进去，没有去重

### 重现步骤

328正确，544是连覆盖导入的用例也加了进去，没有去重

**Comment by xulinde** [comment]
v1.20.10-lts未复现该问题，建议您升级到最新版本～
