### ISSUE TITLE
[BUG] 使用外部数据库时报错 Specified key was too long

### ISSUE THREAD

**Issue by wjangelking** [metersphere/metersphere#161]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.1.0

**Bug 描述**

使用外部数据库时报错 Specified key was too long

**Bug 重现步骤**

1.  安装前配置数据库为外部数据库（数据库为阿里云RDS，5.7版本）
2. 执行安装脚本
3. 查看 ms-server 日志

**期望结果**

优化索引字段长度

**截图**

Migration V5__schedule.sql failed
SQL State  : 42000
Error Code : 1071
Message    : Specified key was too long; max key length is 767 bytes
Location   : db/migration/V5__schedule.sql (/deployments/file:/opt/apps/backend-1.1.jar!/BOOT-INF/classes!/db/migration/V5__schedule.sql)
Line       : 1
Statement  : -- quartz start
CREATE TABLE `qrtz_job_details` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `JOB_NAME` varchar(200) NOT NULL,
  `JOB_GROUP` varchar(200) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `JOB_CLASS_NAME` varchar(250) NOT NULL,
  `IS_DURABLE` varchar(1) NOT NULL,
  `IS_NONCONCURRENT` varchar(1) NOT NULL,
  `IS_UPDATE_DATA` varchar(1) NOT NULL,
  `REQUESTS_RECOVERY` varchar(1) NOT NULL,
  `JOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`),
  KEY `IDX_QRTZ_J_REQ_RECOVERY` (`SCHED_NAME`,`REQUESTS_RECOVERY`),
  KEY `IDX_QRTZ_J_GRP` (`SCHED_NAME`,`JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

![image](https://user-images.githubusercontent.com/17584830/88358061-1cced580-cda0-11ea-82c7-af55e07ccd4f.png)

**Comment by naah69** [comment]
mysql的参数`innodb_large_prefix ` 设置为ON
