### ISSUE TITLE
[BUG].jmx里含content-type为multipart/form-data的请求时，导到平台请求体不是form-data

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16100]
### 联系方式

MeterSphere交流群14 范德华力

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33822034/180171010-18148415-8acf-456e-af9e-bd168b31f90d.png)

### 重现步骤

.jmx里含content-type为multipart/form-data的请求时，导到平台请求体默认不是form-data

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
