### ISSUE TITLE
[FEATURE]form-data的文件一旦导入到ms平台，能不能重定向

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16101]
### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 请描述您的需求或者改进建议

本地假设form-data的文件路径我设为D:\\1.txt
我把脚本导入到ms平台，再去看文件路径还是D:\\1.txt，这样就引用不了
能不能帮忙重定向到正确的路径

**Comment by Hyyfit** [comment]
您好，这个是必须要先手动上传的到服务器才行的。
