### ISSUE TITLE
[BUG]邮件报告链接错误

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1610]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
简要描述您碰到的问题
定时任务发送的邮件报告，里面的链接一个是老版本的无效链接，一个链接跳转的页面不是报告的页面
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
邮件里的链接正确
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72964047/110622768-d9ae5f00-81d6-11eb-9e3e-c1ee47ab0581.png)

**Comment by xulinde** [comment]
1.8版本会修复

**Comment by zyyfit** [comment]
v1.8.0已修复，目前会显示新旧两个连接，请根据自己使用的版本点击对应的连接
