### ISSUE TITLE
[FEATURE]接口文档分享不方便

### ISSUE THREAD

**Issue by DsJay** [metersphere/metersphere#16113]
### MeterSphere 版本

v1.20

### 请描述您的需求或者改进建议

现在在平台上写好接口，生成文档后，没法很方便的通过copy链接等方式分享给同学查看，希望可以增加类似一键分享功能。便于大家协作，也更符合平台“一站式”的定位。

类似接口文档分享，平台上的很多地方也没法通过分享来直接到达，比如场景编排等。

希望可以支持这样的功能！

**Comment by maninhill** [comment]
这个需求我也觉得比较通用。

**Comment by zhangzhaox** [comment]
1、测试团队间的协同很有必要，如A同学编写某自动化场景时遇到了困难，B同学可通过场景URL连接的方式一键访问并协助

2、结合一站式、持续测试平台的定位是否可考虑增加更多的API导出格式，如word、Html、md等实现方式，便于引导开发同事使用该平台

**Comment by Hyyfit** [comment]
1.这个需求我们有在规划的。
2.其他格式我们不支持，我们现在已经有分享的功能的。
<img width="867" alt="image" src="https://user-images.githubusercontent.com/95834771/184135733-e8610c1d-58ab-40c1-939e-f3245726742c.png">

**Comment by DsJay** [comment]
> 1.这个需求我们有在规划的。 2.其他格式我们不支持，我们现在已经有分享的功能的。 <img alt="image" width="867" src="https://user-images.githubusercontent.com/95834771/184135733-e8610c1d-58ab-40c1-939e-f3245726742c.png">

感谢感谢！
