### ISSUE TITLE
[BUG]接口URL可重复选项不工作

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1611]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
简要描述您碰到的问题
没有勾选接口URL可重复，但展示了重复的接口
可重复的 URL 项目， 导入之后，发现后面的接口会覆盖前面的相同导入接口
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，建议您升级到v1.8再验证下
