### ISSUE TITLE
[FEATURE]接口测试-测试报告导出的2个建议

### ISSUE THREAD

**Issue by nobody1121** [metersphere/metersphere#16121]
### MeterSphere 版本

版本:   v1.20.10-lts-787c5294

### 请描述您的需求或者改进建议

1.接口测试-测试报告希望能加入批量导出的功能
2.导出报告时默认名字希望直接拿平台上报告的名字，而不是默认的MeterSphere

**Comment by luty2018** [comment]
感谢你的建议，我们会尽快排期
