### ISSUE TITLE
[BUG]测试跟踪>>功能测试>>测试用例列表：选择表头【用例状态=”未开始、进行中”】，点击筛选。筛选的结果不对，当前页或者下一页的列表中，包含了状态为“已完成”的记录

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#16134]
### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

测试跟踪>>功能测试>>测试用例列表：选择表头【用例状态=”未开始、进行中”】，点击筛选。筛选的结果不对，当前页或者下一页的列表中，包含了状态为“已完成”的记录

### 重现步骤

测试跟踪>>功能测试>>测试用例列表：
选择表头【用例状态=”未开始、进行中”】，
点击筛选。
筛选的结果不对，当前页或者下一页的列表中，包含了状态为“已完成”的记录

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/180358215-b2df460d-8317-4f0c-83d4-27a4a8123103.png)

![image](https://user-images.githubusercontent.com/78218624/180358399-8236845b-194a-4fbd-b466-1b53035c7570.png)

**Comment by youliyuan-fit2cloud** [comment]
即将发布的版本中会修复该问题~
