### ISSUE TITLE
[BUG]API文档-Swagger上的接口参数，与实际在浏览器上抓到的请求参数不一致。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#16135]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

swagger上的/api/definition/update接口，与实际在浏览器上抓到的不一样，实际抓包抓到的，多了后面这三个参数
![image](https://user-images.githubusercontent.com/104960608/180373942-abc897e1-d8f2-439e-b32b-ec61b9dfa2de.png)

### 重现步骤

1.点击 API文档，进入Swagger 接口页面，找到 /api/definition/update 接口
2.在接口定义页面，点击某一接口编辑按钮，打开F12-network页面，点击保存
3.比较这两个接口的请求参数，发现实际的接口参数多了这三项
![image](https://user-images.githubusercontent.com/104960608/180373991-9b5c0cd9-b4b1-43f6-91fe-c557c9a9e626.png)

### 期待的正确结果

Swagger上的接口参数内容与实际浏览器F12-network里的一致。
实际接口变动，Swagger上的能及时更新。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我们看了一下，这几个参数是前端传递的，在接口里实际是不生效的，接口参数以swagger里显示的为准就可以

**Comment by 2lipan** [comment]
可是没有这几个参数，接口跑不通。

**Comment by zyyfit** [comment]
测试过了，这几个参数不是必填的，不填也可以
![image](https://user-images.githubusercontent.com/73461316/186307295-3ebebe2f-e5b3-4ebd-a236-115e714dbaef.png)

**Comment by 2lipan** [comment]
没有这三个参数，接口跑不通，状态码为400。后面我将这三个参数加上，接口就能正常跑通了。
<img width="959" alt="52073239d82b424743e83ee264bcaf5" src="https://user-images.githubusercontent.com/104960608/186387523-8236b0a6-c8bd-4ec6-9bd0-7576dc76cbad.png">
