### ISSUE TITLE
[BUG] 接口自动化，场景名称过长时，看不到ID号和版本号[指定分辨率下]

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16147]
### 联系方式

18311441708

### MeterSphere 版本

1.20.7.lts

### 使用外置数据库

否

### 问题描述

![155805680276549898](https://user-images.githubusercontent.com/103925124/180395445-2a097bcb-c37a-4198-9726-004736e4e861.jpg)
接口自动化，场景名称过长时，看不到ID号和版本号

### 重现步骤

查看下图

![293147072920820481](https://user-images.githubusercontent.com/103925124/180399121-deb5297f-de41-40ab-9127-7ce020ad6f24.jpg)
![131639616903083991](https://user-images.githubusercontent.com/103925124/180399134-769473ef-72a1-4b81-8942-77bafd719969.jpg)

### 期待的正确结果

场景名称过长时，可看到ID号和版本号

### 相关日志输出

```shell
无
```

### 附加信息
华为浏览器.chrom浏览器

**Comment by xulinde** [comment]
查看名称支持左右滑动

**Comment by Ycr123888** [comment]
![企业微信截图_16589185009065](https://user-images.githubusercontent.com/103925124/181228054-718a0a3b-9e84-48da-932b-6b065facb3c7.png)
绿框部分可左右滑动，这个bug是蓝框部分ID号和版本号[指定分辨率下]显示不全

**Comment by xulinde** [comment]
蓝框部分也可以滑动

**Comment by Ycr123888** [comment]
你指的是编辑接口名称的框里可以滑动是么?
我的问题在于非编辑，显示不全问题呢

**Comment by Ycr123888** [comment]
此显示可滑动，非显示不全问题
