### ISSUE TITLE
[FEATURE]没有案例的文件夹不能导出

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16142]
### MeterSphere 版本

v1.20.9-lts

### 请描述您的需求或者改进建议

没有案例的文件夹不能导出，当列表中文件夹也就是模块很多时，不一定都写了案例，想导出所有文件夹就导出不了，看不了整体架构，希望没有案例的文件夹也能导出

**Comment by Hyyfit** [comment]
不太明白具体是什么意思。我们左侧的模块树，并不是文件夹
