### ISSUE TITLE
[FEATURE]建议测试 计划中，关联的 接口测试用例，以及场景测试，性能测试 设置单独的TAB页面(可能更直观)

### ISSUE THREAD

**Issue by goblinintree** [metersphere/metersphere#16156]
### MeterSphere 版本

v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

建议 编辑测试计划表单中，关联的 接口测试用例，以及场景测试，性能测试 设置单独的TAB页面(可能更直观)

### 附加信息

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/5347862/180417711-c98c3f5b-8125-441e-8964-eb826049156e.png">

**Comment by luty2018** [comment]
感谢你的建议，我们参考一下。
