### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by casezhao** [metersphere/metersphere#16158]
### 请描述您的问题

连接不上外部redis
![image](https://user-images.githubusercontent.com/42054068/180421296-c3dbc24d-6ad4-4ba5-bb37-0b7a47ec9829.png)
ms-server所在服务器通过redis-cli是可以访问目标redis的
![image](https://user-images.githubusercontent.com/42054068/180421538-49a1da9e-9add-4b87-a3f5-8e9f0bff7aff.png)
![image](https://user-images.githubusercontent.com/42054068/180421642-e7a19bf5-c319-4177-b98b-fbad3baa3666.png)

**Comment by casezhao** [comment]
现象和[13659](https://github.com/metersphere/metersphere/issues/13659#issue-1238331865)表现一致

**Comment by Hyyfit** [comment]
问题解决了吗？如果还没有解决，可以加我微信
<img width="305" alt="image" src="https://user-images.githubusercontent.com/95834771/190996605-f2ac71e5-c508-400f-ba20-0b615aee8d6c.png">
