### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by casezhao** [metersphere/metersphere#16157]
### 联系方式

1149854480@qq.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/42054068/180420369-5e50a043-c11a-4f76-bb95-909c942c2fd7.png)
连接外部redis失败；ms-server所在机器是能通过redis-cli访问redis的

### 重现步骤

手动安装

**Comment by aspirin420** [comment]
+1 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/32863315/188822858-6bd6a57b-f3b4-43e5-b0e1-4373c8de874f.png">
按照这个方式配置，启动也是报错 Unable to connect to Redis server，版本号： v1.20.13-lts

**Comment by aspirin420** [comment]
@youliyuan-fit2cloud

**Comment by youliyuan-fit2cloud** [comment]
> +1 <img alt="image" width="340" src="https://user-images.githubusercontent.com/32863315/188822858-6bd6a57b-f3b4-43e5-b0e1-4373c8de874f.png"> 按照这个方式配置，启动也是报错 Unable to connect to Redis server，版本号： v1.20.13-lts

你好，也是外部redis ？
配置文件脱敏截图看看吧

**Comment by aspirin420** [comment]
![image](https://user-images.githubusercontent.com/32863315/189050567-4a0fd3be-4b25-4951-a975-200c8c18aeef.png)


 @youliyuan-fit2cloud

**Comment by aspirin420** [comment]
是外部 redis

**Comment by youliyuan-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/32863315/189050567-4a0fd3be-4b25-4951-a975-200c8c18aeef.png)
> 
> @youliyuan-fit2cloud

不是应该把redis的配置开放吗？ 然后修改为你自己的redis信息。你这个文件里面没有开启啊。

**Comment by liuruibin** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/23045261/189322275-adf01ed5-4a9b-4b6a-aaeb-97d90c47557d.png">
请按照官方文档修改

**Comment by aspirin420** [comment]
> 。

实际是开放的 @youliyuan-fit2cloud

**Comment by aspirin420** [comment]
> 

外接的 redis MS_EXTERNAL_REDIS=true 这样吗？
@liuruibin

**Comment by aspirin420** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/32863315/189324297-15eeb66a-7c46-485e-a21a-73d8a917a2da.png">
![image](https://user-images.githubusercontent.com/32863315/189324520-158cc92f-ca57-4571-ac14-87ddcf044d96.png)

**Comment by aspirin420** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/32863315/189327420-f086542a-0bcf-476a-8d26-67572d25ef3a.png">

是不是 k8s 的部署文档里面少了类似  MS_EXTERNAL_REDIS=true 这个配置了？

**Comment by liuruibin** [comment]
> <img alt="image" width="955" src="https://user-images.githubusercontent.com/32863315/189327420-f086542a-0bcf-476a-8d26-67572d25ef3a.png">
> 
> 是不是 k8s 的部署文档里面少了类似 MS_EXTERNAL_REDIS=true 这个配置了？

k8s 不需要这个配置，输入真实可达的地址就好

**Comment by aspirin420** [comment]
> > <img alt="image" width="955" src="https://user-images.githubusercontent.com/32863315/189327420-f086542a-0bcf-476a-8d26-67572d25ef3a.png">
> > 是不是 k8s 的部署文档里面少了类似 MS_EXTERNAL_REDIS=true 这个配置了？
> 
> k8s 不需要这个配置，输入真实可达的地址就好

但按照这个配置还是无法连接，在容器内部是可以 telnet 通 ip+port 的

**Comment by aspirin420** [comment]
![image](https://user-images.githubusercontent.com/32863315/189329641-d6530c9a-c8ea-454e-bc8a-c2f5f9351a25.png)

**Comment by aspirin420** [comment]
@liuruibin
