### ISSUE TITLE
[BUG]删除已经关联到测试计划中的api场景，jenkins触发测试计划会出现奇怪现象

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#1616]
**MeterSphere 版本**
1.7.3

**Bug 描述**
从旧版本中选择api测试，转场景到新版本中。创建测试计划，关联这些转过来的api场景。然后删除这些场景。
从jenkins触发这个测试计划，执行的是旧版本中的api测试。但是进入测试计划，看详情，却没有任何关联的api测试场景。

**Comment by xulinde** [comment]
按照您提供的复现步骤，未复现该问题，建议您升级下jenkins版本
