### ISSUE TITLE
[BUG]【接口自动化】编辑「环境配置」后，弹出的窗口中，默认选中的不是当前的配置，容易导致环境配置错误

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1617]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
【接口自动化】编辑「环境配置」后，弹出的窗口中，默认选中的不是当前的配置，容易导致环境配置错误

**Bug 重现步骤**
1.  进入「接口自动化」模块
2. 编辑「环境配置」
3. 检查是否默认选中当前的环境配置
4. 

**期待的正确结果**
正确情况下应该是什么样的？
预期：默认选中当前环境配置
实际：默认选中第一条

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/110744176-3875e600-8274-11eb-9aee-b6773062389b.png)

![image](https://user-images.githubusercontent.com/11580681/110744217-488dc580-8274-11eb-8047-a7c1ced0246b.png)

**Comment by xulinde** [comment]
未复现该问题，默认是保留最后一次执行时选择的环境变量，是不是选了环境后没保存

**Comment by xulinde** [comment]
感谢反馈，后面版本会优化在这里

**Comment by xulinde** [comment]
v1.8已优化
