### ISSUE TITLE
[FEATURE]部分页面加载缓慢

### ISSUE THREAD

**Issue by wang-qa** [metersphere/metersphere#1618]
![image](https://user-images.githubusercontent.com/58168764/110758701-c60f0100-8287-11eb-8aac-9297cceb58c1.png)
![image](https://user-images.githubusercontent.com/58168764/110758760-d7f0a400-8287-11eb-865e-43b0df834e91.png)
页面在 测试报告 首页中加载感觉很慢

**Comment by xulinde** [comment]
测试发现只有demo环境有此问题，需要研发同事排查下原因
