### ISSUE TITLE
[QUESTION] 请问为什么用beanshell 引入包都会报错呢

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1619]
**请描述您的问题.**

![image](https://user-images.githubusercontent.com/38770463/110774609-f612d000-8298-11eb-8947-ac7eced93728.png)

**Comment by xulinde** [comment]
报错截个图吧

**Comment by wonderfulwxw** [comment]
截图里 有控制台报错的图，请看第一张。

**Comment by xulinde** [comment]
方便上传下jar包吗

**Comment by guhan121** [comment]
@xulinde #1623
