### ISSUE TITLE
[FEATURE] 在LDAP没有配置之前，建议不要显示LDAP登录选项

### ISSUE THREAD

**Issue by wjangelking** [metersphere/metersphere#162]
![image](https://user-images.githubusercontent.com/17584830/88359542-93ba9d00-cda5-11ea-8efd-d85ecb6e3ba0.png)

**请描述你建议的实现方案**

 建议配置并启用了LDAP之后，登录时不需要选择登录方式，由后端逻辑处理

**Comment by maninhill** [comment]
收到，感谢您的建议。

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.1.1 中实现
