### ISSUE TITLE
Swagger url导入,报解析数据出错(url地址中带中文)[BUG]

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#16202]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.9-lts 

### 使用外置数据库

否

### 问题描述

1.Swagger url导入,报解析数据出错,url地址中带中文,url地址中中文为urlencode编码后的,例如:http://10.50.67.22:8088/tgwb/v2/api-docs?group=%E6%89%98%E7%AE%A1%E5%A4%96%E5%8C%85
![b21e86b87f5e19d53bd45c664703042](https://user-images.githubusercontent.com/103627487/180639450-69153cb0-fd06-445e-a4e8-6a706efd8d97.jpg)
![a4e27d189a4a8df8bd143aa6df57ccd](https://user-images.githubusercontent.com/103627487/180639470-b0ca9214-3853-405d-bb51-fd852deca40e.jpg)
![6777bd73189d63eb0b710906de84e5d](https://user-images.githubusercontent.com/103627487/180639480-15892ffb-6dcc-4226-a732-35ab12fd30c6.jpg)
2.url浏览器直接访问、服务器上请求均能正常返回
![638d71c0df91a06d17322d7b9491369](https://user-images.githubusercontent.com/103627487/180639580-68042eb7-96f5-4d04-a839-d77a86b17aea.jpg)
3.用Swagger url导入的时候报错，保存为文件导入能正常导入
4.Swagger url导入，url地址直接用中文，不编码，例如：http://10.50.67.22:8088/tgwb/v2/api-docs?group=托管外包，页面报连接超时，docker容器里，info和error均没有日志，应该是没有到后端
![766b1dfa3936ffb7376b23f15919dc6](https://user-images.githubusercontent.com/103627487/180639835-060c7f69-c353-41e0-8256-e6b680c2c38c.jpg)
![9a629e7cd27c4d4516b713298483899](https://user-images.githubusercontent.com/103627487/180639848-45786aec-0d68-4529-980a-6377e81c2e55.jpg)

### 重现步骤

Swagger url导入url地址中带中文

### 期待的正确结果

可以正常导入

**Comment by zyyfit** [comment]
您好，1.20.10对导入功能做了整体优化，在1.20.10版本没有复现这个问题，建议您升级后再试试
