### ISSUE TITLE
[BUG]定时任务执行报错

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1621]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是：1.7.2

**Bug 描述**
对接口设置定时任务，跑了几天，然后突然发生异常，日志如图

**截图**
![image](https://user-images.githubusercontent.com/22386206/110903526-8e18c400-8342-11eb-9c2d-c28261819b61.png)
![image](https://user-images.githubusercontent.com/22386206/110903961-36c72380-8343-11eb-91f0-9e6cedfbf527.png)

**Comment by xulinde** [comment]
您设置的定时任务时间间隔是多久，我们复现下

**Comment by zh417233956** [comment]
> 您设置的定时任务时间间隔是多久，定时执行的是性能还是接口测试，我们复现下

这个是设置的1分钟一次，跑了几天，然后异常了，正常的接口测试

**Comment by zh417233956** [comment]
@xulinde 这个是设置的1分钟一次，跑了几天，然后异常了，正常的接口测试

**Comment by xulinde** [comment]
还是没复现呢，建议您升级到v1.8再验证下

**Comment by zh417233956** [comment]
@xulinde 已升级到1.8.0后续再跟进，有问题再反馈
