### ISSUE TITLE
[BUG]UI元素定位菜单，鼠标点击方式为 “点击“ 执行失败，切换成 “按下“ 后可正常执行（用 selenium 回放没问题，且实际鼠标操作是“点击“）

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#16210]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.5-lts

### 使用外置数据库

否

### 问题描述

UI元素定位菜单，鼠标点击方式为 “点击“ 无效，切换成 “按下“ 后可正常执行（用 selinum 回放没问题，且实际鼠标操作是“点击“）

### 重现步骤

![微信图片编辑_20220725110051](https://user-images.githubusercontent.com/30038088/180690578-89f932f2-cb74-46e1-b962-062bb6f3cc41.jpg)
源码如下：
![微信截图_20220725110309](https://user-images.githubusercontent.com/30038088/180690651-6dae5307-6555-4a61-b8c6-6841196bd436.png)

### 期待的正确结果

UI测试可正常执行

**Comment by shenkaibo** [comment]
已反馈给 @zhangdahai112

**Comment by xulinde** [comment]
我这没复现这个问题，感觉跟你测试的网站有关系
![image](https://user-images.githubusercontent.com/64065190/180752787-deeaf4b3-9a23-4474-b5e9-6d4d020887c7.png)

**Comment by shenkaibo** [comment]
是的 测我们环境没问题，客户环境有问题，而且 客户环境用 selenium 录制回放 都没问题

**Comment by shenkaibo** [comment]
用 js 调用 selenium driver 可以，具体脚本如下:
![image](https://user-images.githubusercontent.com/30038088/185282314-6ca3449b-ec79-44bd-aa27-6e9a03b9e727.png)

**Comment by shenkaibo** [comment]
[v2.1.1](https://github.com/metersphere/metersphere/milestone/81) 已修复！
