### ISSUE TITLE
[BUG] 无测试计划时查看场景引用报错

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1622]
**MeterSphere 版本**
1.7.3

**Bug 描述**
### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Table 'metersphere.TEST_PLAN' doesn't exist ### The error may exist in io/metersphere/base/mapper/ext/ExtTestPlanMapper.xml ### The error may involve io.metersphere.base.mapper.ext.ExtTestPlanMapper.selectTestPlanByRelevancy-Inline ### The error occurred while setting parameters ### SQL: SELECT * FROM TEST_PLAN p LEFT JOIN test_plan_project t ON t.test_plan_id=p.id WHERE (t.project_id = ? or p.project_id = ?) AND p.id IN (SELECT test_plan_id FROM test_plan_api_scenario WHERE api_scenario_id = ? ) ### Cause: java.sql.SQLSyntaxErrorException: Table 'metersphere.TEST_PLAN' doesn't exist ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'metersphere.TEST_PLAN' doesn't exist

**Bug 重现步骤**
1.  安装后；不创建测试计划
2. 创建一个测试场景
3. 在测试场景的更多操作查看场景引用
4. 报错

**期待的正确结果**
显示无引用

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/5517369/110938834-6db32e80-836f-11eb-8930-d758f6a473bd.png)

**Comment by xulinde** [comment]
未复现该问题，是用的最新版本吗

**Comment by guhan121** [comment]
@xulinde 最新发布版本
