### ISSUE TITLE
[BUG]接口自动化场景导入CASE时，检索CASE名称失效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#16228]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.10-LTS

### 使用外置数据库

否

### 问题描述

接口自动化场景导入CASE时，检索CASE名称失效。

### 重现步骤

1、创建接口自动化场景
2、导入case
3、在列表中右上角按名称检索
4、输入已有的名称去检索，发现搜索不到CASE

### 附加信息

检索之前：
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/32027713/180705983-f322eed7-798e-44b4-9678-2932acaa1a29.png">
检索之后：
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/32027713/180706052-98828c84-1222-4e50-b679-72f9f850441a.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~
