### ISSUE TITLE
[FEATURE]UI 自动化每个步骤的错误处理，有的步骤是可选，如果失败了继续执行，能否结果不包含这个可选的失败步骤？

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#16232]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

UI 自动化每个步骤的错误处理，有的步骤是可选，如果失败了继续执行，但整个用例是通过的。能否加个选项兼顾这种场景？
现在的失败继续，但用例还是算失败

### 请描述你建议的实现方案

错误处理加一个选项

### 附加信息
企业版用户

_No response_

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
