### ISSUE TITLE
[BUG] 为项目上传的jar包无法在groovy脚本中使用

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1623]
**MeterSphere 版本**
1.7.3

**Bug 描述**
为项目上传的jar包无法在场景测试中使用

**Bug 重现步骤**
1.  创建新项目；为项目上传必要的测试用jar包。play-1.0.0.jar
2.  创建场景测试；增加一个自定义请求；给其增加前置脚本groovy
```groovy
import groovy.io.FileType
def tmpDir = System.getProperty("jmeter.home","");// Allow override $NON-NLS-1$ $NON-NLS-2$
if (tmpDir.length() == 0) {
    File userDir = new File(System.getProperty("user.dir"));// $NON-NLS-1$
    tmpDir = userDir.getAbsoluteFile().getParent();
}
def libDir = new File(tmpDir + File.separator + "lib" + File.separator + "ext")
libDir.eachFileRecurse (FileType.FILES) { it ->
  log.info( "jar: " + it.getName());
}

```
3. 输出结果
![image](https://user-images.githubusercontent.com/5517369/111016589-cb845c80-83e9-11eb-9083-480ad608b760.png)

4. 

**期待的正确结果**
期待增加的jar包在场景测试中也能使用

**截图**
![image](https://user-images.githubusercontent.com/5517369/111016589-cb845c80-83e9-11eb-9083-480ad608b760.png)
![image](https://user-images.githubusercontent.com/5517369/111016629-fa9ace00-83e9-11eb-81de-0c86617f9f38.png)

**Comment by xulinde** [comment]
方便发下jar包吗，我们复现下

**Comment by guhan121** [comment]
[pay_grrovy_utils-0.0.1-all.jar.zip](https://github.com/metersphere/metersphere/files/6156269/pay_grrovy_utils-0.0.1-all.jar.zip)
@xulinde

**Comment by guhan121** [comment]
@fit2cloudrd 
应用脚本的方式是这样
```
import groovy.json.JsonOutput 
import paytest.*

def bizJosn=[a:"a"]
log.info JsonOutput.toJson(bizJosn)
log.info BodySign.rsa256Sign(bizJosn)
```
