### ISSUE TITLE
[BUG]谷歌浏览器录制插件导出的JMX接口URL参数多了个 amp; 导致性能测试接口请求失败

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#1625]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.73
**Bug 描述**
简要描述您碰到的问题
谷歌浏览器录制插件，导出的JMX脚本，录制的接口参数有误。
**Bug 重现步骤**
1.   点击开始录制
2.  执行创建操作
3.  分别导出JSON文件和JMX文件
4. 导出的JMX接口URL参数多了个 amp; 导致性能测试接口请求失败。
![image](https://user-images.githubusercontent.com/30038088/111072159-421d7900-8514-11eb-9556-99ebf9e3129a.png)
![image](https://user-images.githubusercontent.com/30038088/111072194-6da06380-8514-11eb-95b3-d8d0a1b09d1c.png)

**期待的正确结果**
正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/30038088/111072204-7a24bc00-8514-11eb-8678-3d5d9d48eeae.png)

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们修复下

**Comment by youliyuan-fit2cloud** [comment]
v1.8.1 版本修改该问题，请关注最近版本发布~
