### ISSUE TITLE
[FEATURE]自动化场景中步骤较多的情况下，在未断言识别到的情况下，不能通过搜索变量变量的方式定位到具体哪个请求

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#16257]
### MeterSphere 版本

v.1.19.3

### 请描述您的需求或者改进建议

自动化场景中步骤较多的情况下，通过后面的变量应用请求发现该变量未提取到值，此时就需要确定该变量是属于前面那个请求的提取变量
1、目前仅能逐个打开前面请求的控制台，逐个查看检查，步骤较多或业务不熟悉的情况下效率较低。
2、当前调试运行报告页面不能满足变量名称全局搜索(响应报文或提取变量名)的情况下，是否考虑有其他的临时方案？

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
