### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#1626]
**请描述您的需求或者改进建议.**
是否有执行用例的时把评论功能也放出来

**请描述你建议的实现方案**
 用例执行失败可以用评论做个记录，下次查看就知道用例执行失败的原因

**Comment by Evan-guo131** [comment]
是否有执行用例的时把评论功能也放出来

**Comment by xulinde** [comment]
收到，后面可以优化下这里

**Comment by xulinde** [comment]
1.9.0已支持
