### ISSUE TITLE
[FEATURE]UI 自动化调试中，每个步骤的执行结果能否标注，方便看进度。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#16264]
### MeterSphere 版本

1.20

### 请描述您的需求或者改进建议

UI 自动化调试中，每个步骤的执行结果能否标注，方便看进度。 目前界面上啥也看不到，有时候卡在中间，啥反应没有，也不知道哪一步问题。（企业版用户）

**Comment by Hyyfit** [comment]
您好，调试页面是有展示每一步的调试结果的。
![image](https://user-images.githubusercontent.com/95834771/182106697-6b68dcbd-da9d-4af6-9265-21b65ffc5ba5.png)

**Comment by wudamyw** [comment]
这个是执行完了才展示，看不到进度的。
