### ISSUE TITLE
[BUG]v1.20.10-lts-787c5294版本在禅道缺陷编辑后，在metersphere中同步缺陷会导致图片无法预览

### ISSUE THREAD

**Issue by wholegale39** [metersphere/metersphere#16273]
### 联系方式

微信MeterSphere 交流群13 Celtics

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

否

### 问题描述

1、v1.20.10-lts-787c5294版本创建带有图片的缺陷，并同步至禅道，禅道正常展示图片；
2、禅道缺陷编辑后，在metersphere中同步缺陷会导致图片无法预览；

### 重现步骤

[禅道专业版 9.0.3]
1、v1.20.10-lts-787c5294版本创建带有图片的缺陷，并同步至禅道，禅道正常展示图片；
2、禅道缺陷编辑后，在metersphere中同步缺陷会导致图片无法预览；

### 期待的正确结果

1、禅道编辑缺陷后，metersphere同步缺陷后也可正常预览图片

### 附加信息

![image](https://user-images.githubusercontent.com/17040470/180735445-85288da2-f08d-45dc-9087-332b8e865787.png)

**Comment by xulinde** [comment]
v1.20.11-lts已修复～

**Comment by wholegale39** [comment]
> v1.20.11-lts已修复～

升级到v1.20.11-lts版本后，重新按上述步骤操作，仍然存在同样的问题，图片url中了多了pro%2F
http://192.168.1.1:8081/resource/md/get/url?url=http%3A%2F%2F192.168.1.2%3A82%2Fpro%2Fpro%2Ffile-read-72561.png
