### ISSUE TITLE
[BUG] 定时任务执行测试计划时服务端报错

### ISSUE THREAD

**Issue by icegreen77** [metersphere/metersphere#1628]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
定时任务执行测试计划时服务端报错，在更新到最新版本之前该功能时正常的，更新后出错
![错误](https://user-images.githubusercontent.com/18401588/111116972-cd911b80-85a1-11eb-9953-efdaaa2a503c.png)

**Bug 重现步骤**
1.  创建测试计划
2.  设置定时任务执行时间和邮件通知
3.  等待任务执行
4. 

**期待的正确结果**
正确情况下应该是什么样的？
收到邮件提醒

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
是哪个版本升级上来的

**Comment by xulinde** [comment]
开发目前已经定位到问题，正在修改，预计下个版本修复

**Comment by icegreen77** [comment]
好的，谢谢。我是从1.7.0版本升级上来的



~无尾熊先森是77

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG] 定时任务执行测试计划时服务端报错 (#1628)





 
开发目前已经定位到问题，正在修改，预计下个版本修复

**Comment by xulinde** [comment]
1.9.2已修复
