### ISSUE TITLE
定时任务，设置通知邮箱时，能支持自定义邮箱吗

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1629]
**请描述您的需求或者改进建议.**

定时任务，设置通知邮箱时，只能设置平台注册用户关联的邮箱，不能自定义输入邮箱地址

**请描述你建议的实现方案**

邮箱地址不与平台用户强关联，支持输入任意邮箱地址

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中
