### ISSUE TITLE
[BUG]配置环境设置了两个参数，再次修改环境配置新的参数保存后不成功

### ISSUE THREAD

**Issue by zhangceng666** [metersphere/metersphere#163]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.1.0-rc1-b421
**Bug 描述**
简要描述您碰到的问题
配置环境设置了两个参数，再次修改环境配置新的参数保存后不成功

**Bug 重现步骤**
1.配置环境设置了两个参数，如参数a，b
2.引用环境进行接口调用
3.修改环境的参数，新增一个参数C，点击保存
4.再次打开环境查看时，参数C没有保存上 

**期待的正确结果**
正确情况下应该是什么样的？
能够灵活修改环境变更等信息

**截图**
如果有截图，请附上截图.

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 您所使用的 MeterSphere 版本是？
> 版本: v1.1.0-rc1-b421
> **Bug 描述**
> 简要描述您碰到的问题
> 配置环境设置了两个参数，再次修改环境配置新的参数保存后不成功
> 
> **Bug 重现步骤**
> 1.配置环境设置了两个参数，如参数a，b
> 2.引用环境进行接口调用
> 3.修改环境的参数，新增一个参数C，点击保存
> 4.再次打开环境查看时，参数C没有保存上
> 
> **期待的正确结果**
> 正确情况下应该是什么样的？
> 能够灵活修改环境变更等信息
> 
> **截图**
> 如果有截图，请附上截图.

无法重现哦，我这边按你的步骤操作，成功保存了3个参数，如果有复现，可以在群里@罗婷 哈
