### ISSUE TITLE
[BUG]【接口测试】>>【接口测试用例】：接口请求体为Json格式，当参数有数值型时，变量对其赋值存在存在两个问题。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#16319]
### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

[BUG]【接口测试】>>【接口测试用例】：接口请求体为Json格式，当参数有数值型时，变量赋值存在存在两个问题。
问题1：Json模式：有数值型的参数无法赋值为数值，系统直接提示书写错误。

问题2：切换成“JSON-SCHEM”形式赋值，可以赋值为数值，但是点击执行后，查看系统请求内容，该参数自动处理为字符串。

### 重现步骤

[BUG]【接口测试】>>【接口测试用例】：接口请求体为Json格式，存在两个问题。
问题1：Json模式：有数值型的参数无法赋值为数值，系统直接提示书写错误。

问题2：切换成“JSON-SCHEM”形式赋值，可以赋值为数值，但是点击执行后，查看系统请求内容，该参数自动处理为字符串。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/180790275-c0c54345-34ff-408f-9ac5-d86a1f9da335.png)
![image](https://user-images.githubusercontent.com/78218624/180792546-d8f94c86-277a-4b2f-b465-55c55fb122b6.png)

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/180901214-5054f99f-4dc6-409f-9e24-6e252f75faf5.png)
这个图片的提示是没用问题的，标准的json 格式提示，其他专业json格式化插件也是一样，目前该提示不影响实际使用

**Comment by huangxine** [comment]
![image](https://user-images.githubusercontent.com/78218624/180907575-ed97ac3c-4ac2-44d3-9b95-a1154f0cd085.png)

“JSON-SCHEM”模式下的赋值不能接受数值型的吗？这个是否正常?

**Comment by zyyfit** [comment]
第一个是bug，后面的版本修复，第二个只是显示问题，不影响使用

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/15760
