### ISSUE TITLE
希望能够增加日报功能，即通过配置，每天能够自动发送当前的测试进度的报告邮件

### ISSUE THREAD

**Issue by shuchengxiang** [metersphere/metersphere#1632]
**请描述您的需求或者改进建议.**
需要自动发送日报邮件以通知各方测试进度

**请描述你建议的实现方案**
增加发送日报功能

**Comment by xulinde** [comment]
已在后续版本规划中，请持续关注

**Comment by luty2018** [comment]
v2.7功能支持定时发送项目报告，可以看看是否满足你的需求。
