### ISSUE TITLE
[BUG]导入使用Swagger格式导入json文件   body参数没导进去

### ISSUE THREAD

**Issue by zihui1** [metersphere/metersphere#16329]
### 联系方式

602208333@qq.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

使用导入功能进行Swagger格式导入接口数据，导入成功后请求参数中的body没导入成功

### 重现步骤

1.页面导入Swagger类型文件
2.导入成功后查看post请求接口 请求方式中body文件

### 期待的正确结果

2.正常显示导入文件中body参数

### 附加信息

{
	"openapi": "3.0.3",
	"info": {
		"title": "haier-demo API",
		"termsOfService": "https://www.baidu.net/",
		"contact": {
			"name": "导入测试",
			"url": "https://www.baidu.net",
			"email": "openapi@baidu.net"
		},
		"version": "1.0"
	},
	"servers": [
		{
			"url": "http://10.330.0.6:9092",
			"description": "Inferred Url"
		}
	],
	"tags": [
		{
			"name": "名称Api服务",
			"description": "Name Controller"
		},
		{
			"name": "测试Api服务",
			"description": "Test Controller"
		}
	],
	"paths": {
		"/api/test/postData": {
			"post": {
				"tags": [
					"测试Api服务"
				],
				"summary": "提交数据",
				"description": "提交数据",
				"operationId": "postDataUsingPOST_1",
				"requestBody": {
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/TestRequest"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"*/*": {
								"schema": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"TestRequest": {
				"title": "TestRequest",
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"description": "描述"
					},
					"name": {
						"type": "string",
						"description": "名称"
					}
				},
				"description": "保存名称"
			}
		}
	}
}

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。
请确认一下该项目下接口定义中已存在该接口，导入时是否选择了覆盖原来的接口？

**Comment by zihui1** [comment]
请使用附加信息中的json

**Comment by youliyuan-fit2cloud** [comment]
> 请使用附加信息中的json

我们测试的时候是使用贴在issue的swagger json文件

**Comment by zihui1** [comment]
![image](https://user-images.githubusercontent.com/31397092/181156523-93279e98-21b9-445d-8224-f574f98c2af0.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已修改，请关注下新版本发布~

**Comment by liuyuliang1108** [comment]
我也是 v2.0.0版本还是没修复 我现在导入后 请求体内数据全丢失了

**Comment by zihui1** [comment]
&nbsp;更新最新版本，已经修复了。




。王先生&nbsp;????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午2:26
***@***.***&gt;;
抄送:&nbsp;"。王先生 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]导入使用Swagger格式导入json文件   body参数没导进去 (Issue #16329)





 
我也是 v2.0.0版本还是没修复 我现在导入后 请求体内数据全丢失了

**Comment by zyyfit** [comment]
> 我也是 v2.0.0版本还是没修复 我现在导入后 请求体内数据全丢失了

您可以把您的swagger文件上传一下看看吗

**Comment by zihui1** [comment]
bug记录里有， gethub不支持文件上传




。王先生&nbsp;????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午5:37
***@***.***&gt;;
抄送:&nbsp;"。王先生 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]导入使用Swagger格式导入json文件   body参数没导进去 (Issue #16329)





  
我也是 v2.0.0版本还是没修复 我现在导入后 请求体内数据全丢失了
  
您可以把您的swagger文件上传一下看看吗

**Comment by zyyfit** [comment]
@zihui1 不是，我是说 liuyuliang1108，您不是说已经修复了吗

**Comment by zihui1** [comment]
是的， 最新版本已经修复了。


。王先生&nbsp;????
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午5:49
***@***.***&gt;;
抄送:&nbsp;"。王先生 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]导入使用Swagger格式导入json文件   body参数没导进去 (Issue #16329)





 
@zihui1 不是，我是说 liuyuliang1108，您不是说已经修复了吗
