### ISSUE TITLE
[FEATURE]批量执行自动化用例能否添加指定顺序 方便自己选择把初始化的用例添加到前后位置

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#16325]
### MeterSphere 版本

版本:   v1.19.3-df1d5d76

### 请描述您的需求或者改进建议

接口自动化批量执行的时候，有些初始化的功能，基本上所有的用例都需要执行，所以添加起来比较频繁，能否设置自动化用例的自动执行的阶段，设置指定优先运行哪些接口自动化用例以及最后执行哪些用例的功能，方便把初始化放在一起做

### 请描述你建议的实现方案

定时任务执行的时候 添加相关设置 指定运行的自动化用例顺序 用户自己选择把初始化的用例添加到前后位置
![image](https://user-images.githubusercontent.com/26948634/180904913-28a5bd90-1dc9-4603-a289-c8b77709fb8f.png)

**Comment by Hyyfit** [comment]
您好，可以通过环境里的全局配置来实现。
<img width="952" alt="image" src="https://user-images.githubusercontent.com/95834771/182106320-6180017c-acef-4496-bf0e-6570eadf6d19.png">
