### ISSUE TITLE
[BUG]测试跟踪-功能用例：脑图-外观样式设置了字体和样式未生效

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#16328]
### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

脑图-外观样式设置了字体和样式未生效

### 重现步骤

脑图-外观样式，设置字号24

新增节点--文字还是默认字号

脑图全选设置字号32，保存，刷新页面--又被还原成默认字号了

### 期待的正确结果

外观样式能正常使用，保存后能生效

**Comment by zyyfit** [comment]
脑图外观功能暂时是没有作用的，就只是展示
