### ISSUE TITLE
[BUG] 自定义拼接请求，中间又自动加了“/”，导致请求链接是 中间出事“//”

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#16324]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

v1.20.10-lts-e16cf617

### 使用外置数据库

是

### 问题描述

[BUG] 自定义拼接请求，中间又自动加了“/”，导致请求链接是 中间出事“//”

### 重现步骤

![image](https://user-images.githubusercontent.com/23476281/180897672-67818cbc-0342-4f2c-88e3-332936b9883d.png)

### 期待的正确结果

自定请求链接中间不要自动“//”要是用户期望中间多个“/”,现在强制添加了导致域名后面的链接为“//”

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~

**Comment by chase001** [comment]
请问你们是怎么确认解决问题的？版本:   v1.20.11-lts-1f22fc0e 仍然存在问题

![image](https://user-images.githubusercontent.com/23476281/188523223-269c231e-d23c-4fc3-bd07-482f780dea29.png)
