### ISSUE TITLE
[BUG] [UI测试] 修改元素库元素的模块-UI自动化场景引用该元素需要重新选择元素

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16330]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

1.维护元素库，创建自动化场景引用这些元素，修改元素库模块，自动化场景需要重新选择

### 重现步骤

1.维护元素库
2.创建UI自动化场景
3.引用元素库元素
4.保存
5.修改元素库的元素模块
6.重新打开自动化场景

### 期待的正确结果

1.修改元素库模块后，自动化场景不需要重新选择元素

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/180917982-7a942fee-1828-4351-b441-033f7c4cc367.png)
![image](https://user-images.githubusercontent.com/45531073/180918085-f0fa797b-a968-4d09-8837-3edb8855c873.png)
![image](https://user-images.githubusercontent.com/45531073/180918141-265b0f89-ada6-40b5-a55d-e4b09cf68f98.png)

![image](https://user-images.githubusercontent.com/45531073/180917981-cf2db73d-79a6-4a63-ba4a-1eb2f1b87a48.png)

**Comment by zyyfit** [comment]
1.20.11版本和2.0.1版本都会修复这个问题，请等待版本发布后验证
