### ISSUE TITLE
[BUG]场景中复制和引用场景，场景变量取值问题

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#16331]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.9

### 使用外置数据库

否

### 问题描述

1.场景中复制场景，场景设置取原场景变量的值，原场景变量中的值删除后，复制的场景还能取到原场景变量的值。
2.场景中先复制场景，后引用场景，场景设置取原场景变量的值，原场景变量中的值删除后，下面引用的场景会跟随复制的场景取到原场景中的值。
![origin_img_v2_0d14b2ca-61d0-48a4-9e56-decb3635182g](https://user-images.githubusercontent.com/103627487/180918850-d6f0b0ca-6c71-4586-a37b-780cfd9fe7b7.jpg)

### 重现步骤

1.创建场景，复制场景
2.引用场景
3.删除原场景变量的值

**Comment by xulinde** [comment]
删除原场景变量，复制的场景可以看到原场景变量的值，引用的不会看到

**Comment by meijieDouDou** [comment]
2.场景中先复制场景，后引用场景，场景设置取原场景变量的值，原场景变量中的值删除后，下面引用的场景会跟随复制的场景取到原场景中的值。
这个还有问题，先复制场景，再引用场景，原场景变量中的值删除后，引用的场景还能取到值。

**Comment by xulinde** [comment]
> 

我用v1.20.10-lts没复现，建议升级下看

**Comment by xulinde** [comment]
> 我用v1.20.10-lts没复现，建议升级下看



> 2.场景中先复制场景，后引用场景，场景设置取原场景变量的值，原场景变量中的值删除后，下面引用的场景会跟随复制的场景取到原场景中的值。 这个还有问题，先复制场景，再引用场景，原场景变量中的值删除后，引用的场景还能取到值。
我用v1.20.10-lts没复现，建议升级下看
