### ISSUE TITLE
请问在测试过程中可以实现回调接口吗？

### ISSUE THREAD

**Issue by rainbowshine521** [metersphere/metersphere#16350]
### 请描述您的问题

我在发送请求后，响应结果获取到一个url，但是这个url访问时必须有回调接口接收访问后的响应信息，请问如何实现呢？

**Comment by fit2-zhao** [comment]
@rainbowshine521  您好，请问 “url访问时必须有回调接口接收访问后的响应信息” 这段描述的具体使用场景是什么？如果只是获取请求结果中的某个信息，可以通过 “后置操作-提取参数” 去实现。
