### ISSUE TITLE
[BUG]回收站选择所有数据，批量恢复用例，每次只恢复10条，且用例被恢复到未规划用例模块

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#16367]
### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/42445400/180998097-2dbbb72e-026e-41c6-8fc2-5eb3d2f7ed8a.png)

### 重现步骤

删除多个模块用例
到回收站
选择所有数据（23条），点击恢复

### 期待的正确结果

1.恢复所有用例
2.用例模块信息保持不变

**Comment by youliyuan-fit2cloud** [comment]
问题2 用例被恢复到未规划用例模块是设计这样的，因为删除后用例不属于任何模块了，原模块信息被移除，所以都恢复到未规划模块中。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~
