### ISSUE TITLE
【bug】接口定义，重复导入相同的接口

### ISSUE THREAD

**Issue by wangeqi** [metersphere/metersphere#1636]
前提：接口定义中已有相应接口。
操作：swagger重复导入相同的接口。
结果：接口原模块文件夹会变空，且接口会保存到全部用例文件夹下。
备注：新建项目后导入重复接口，接口也会关联到之前的项目，并没有在新项目中。

**Comment by xulinde** [comment]
感谢反馈，我们后面会优化下这里

**Comment by xulinde** [comment]
1.9.0已优化
