### ISSUE TITLE
[BUG]测试计划里只包含功能用例，在页面无法执行，但是调用API可以执行，且可正常生成报告,报告里无任何信息

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#16371]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

测试计划里只包含功能用例，在页面无法执行，但是调用API可以执行，且可正常生成报告,报告里无任何信息。

### 重现步骤

1.创建一个测试计划，只关联功能用例
2.右上角点击 我的信息-API文档，找到 test/plan/run 接口，输入 csrf-token 和参数信息
![image](https://user-images.githubusercontent.com/30038088/181005699-02f41085-0476-4a85-8559-a0963eeadf84.png)
3.点击执行，API 可正常调用成功，且成功生成报告，但是报告里没有任何信息。

### 期待的正确结果

应该 不可执行，或者 返回 异常信息，且报告不应该生成。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.11-lts中已修复~
