### ISSUE TITLE
[BUG] 性能测试添加JMX和CSV文件后，执行完成后，压测报告一直无法生成

### ISSUE THREAD

**Issue by tody0330** [metersphere/metersphere#1637]
**MeterSphere 版本**
 v1.7.3
**Bug 描述**
性能测试添加JMX和CSV文件后，执行完成后，压测报告一直无法生成
**Bug 重现步骤**
1.  点击性能测试模块
2. 上传jmx文件和csv文件
3. 执行测试
4.查看测试报告

**期待的正确结果**
正常生成报告结果

**截图**
![image](https://user-images.githubusercontent.com/53678289/111142699-ef999680-85bf-11eb-9544-ef2b726fa50c.png)

**Comment by xulinde** [comment]
删掉再重新执行一次还有这个问题吗

**Comment by tody0330** [comment]
> 删掉再重新执行一次还有这个问题吗

尝试多次，仍然报错。
同一个接口，不使用csv数据文件，则执行正常

**Comment by xulinde** [comment]
方便发下您的csv文件我们复现下问题吗

**Comment by tody0330** [comment]
> 

> 方便发下您的csv文件我们复现下问题吗

**Comment by tody0330** [comment]
[Uploading mobile.zip…]()

**Comment by prozyworld** [comment]
遇到了同样的问题 压测日志的报错是找不到文件 单独执行接口正常

**Comment by prozyworld** [comment]
StringFromFile 方式单独执行也正常 压测读出的文件内容都是**

**Comment by zyyfit** [comment]
1.9.2版本已修复这个问题，请更新到最新版查看一下
