### ISSUE TITLE
[FEATURE]脑图界面能展示用例标签，支持添加自定义标签

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#16370]
### MeterSphere 版本

v1.20.10-lts

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/42445400/181003108-07fa0568-1ae1-4f32-b1d1-19bc72affbdf.png)
只有列表方式新建用例能设置标签，脑图方式新建用例无法设置标签，也不展示标签

### 请描述你建议的实现方案

脑图界面增加自定义标签功能

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
