### ISSUE TITLE
[BUG]接口自动化，上游接口提取出来的参数，比如截图中的access_token，在下游接口进行调用时，未能传入提取出的值（目前是传入的空值）。

### ISSUE THREAD

**Issue by diaohanji** [metersphere/metersphere#16398]
### 联系方式

微信群昵称：刁寒极

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

否

### 问题描述

上游接口提取出来的参数，比如截图中的access_token，在下游接口进行调用时，未能传入提取出的值（目前是传入的空值）。

### 重现步骤

上游接口提取出来的参数，比如截图中的access_token，在下游接口进行调用时，未能传入提取出的值（目前是传入的空值）。

### 附加信息

![image](https://user-images.githubusercontent.com/43695413/181176522-30cf2fac-c594-4365-870f-654229e6395a.png)
![image](https://user-images.githubusercontent.com/43695413/181176578-6d43e531-c664-4bd9-91b6-0167ce4e7713.png)

**Comment by xulinde** [comment]
未复现该问题，方便把场景文件导出来吗？

**Comment by diaohanji** [comment]
> 未复现该问题，方便把场景文件导出来吗？
[Metersphere_Scenario_财资资产系统.zip](https://github.com/metersphere/metersphere/files/9206395/Metersphere_Scenario_.zip)

**Comment by xulinde** [comment]
环境方便导一份吗，不然场景运行不起来。
