### ISSUE TITLE
[创建接口]创建接口时，模块位置的【无数据，去添加】，点击后提示请输入名称

### ISSUE THREAD

**Issue by chileeb** [metersphere/metersphere#1639]
**请描述您的需求或者改进建议.**

弹出一个输入某块的页面，输入后保存呀。

**请描述你建议的实现方案**

弹出个输入窗口，可以保存。

**Comment by xulinde** [comment]
左侧模块树，会自动创建模块，只需输入模块名称即可
![image](https://user-images.githubusercontent.com/64065190/111289405-14554300-8680-11eb-97c9-45d7c6182ead.png)

**Comment by xulinde** [comment]
1.9.0已优化
