### ISSUE TITLE
[FEATURE]有新版本可用时，界面上可以提示并可一键升级

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#164]
比如假设我现在的版本是 v1.0.3, 当 v1.1.0 发布后，我在界面上会看到提醒，并类似手机 Apps 升级一样，可以一键升级。

**Comment by luty2018** [comment]
> 比如假设我现在的版本是 v1.0.3, 当 v1.1.0 发布后，我在界面上会看到提醒，并类似手机 Apps 升级一样，可以一键升级。

这个是内网部署的，版本更新可以加入我们的交流群或关注GitHub更新动态哈， 升级要在安装的服务器上执行在线安装脚本，做不到web页面上一键升级。
