### ISSUE TITLE
[FEATURE]建测试计划时没有地方可以选择执行人

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16419]
### MeterSphere 版本

v1.20.9-lts

### 请描述您的需求或者改进建议

每个测试计划的执行人可能不同的，现在执行人默认都是用例里的责任人，建测试计划的时候没有地方可以设置执行人，建议在测试计划这里做个批量设置执行人的功能，一个计划里面可能有不同的执行人，一个用例可以多个执行人，请考虑

**Comment by Hyyfit** [comment]
已经有这个功能了：
<img width="189" alt="image" src="https://user-images.githubusercontent.com/95834771/182124648-b7e45751-2936-45dd-96f4-e9b327c8428d.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/95834771/182124700-a7f8b468-9d63-4171-8f81-dab02e807d91.png">
