### ISSUE TITLE
[BUG]集成禅道正常后，禅道的项目id最大只能填到270，超过了就会报错 如271，填写 1-270时正常

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#16414]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.09

### 使用外置数据库

否

### 问题描述

集成禅道后设置正常后，项目ID最大只能到270，超过270后报错。1-270正常，提交缺陷时候能够看到禅道里的成员等信息。
![af99f51328898a25fd9b1a4a8beb988](https://user-images.githubusercontent.com/83771182/181413782-86bd50e8-97d4-4587-9499-72a724c17b17.jpg)

### 重现步骤

项目ID设置271，超过270后会报错

### 期待的正确结果

可以设置270以上的id号

### 相关日志输出

```shell
日志见附件
```

### 附加信息

[info.log](https://github.com/metersphere/metersphere/files/9205102/info.log)

**Comment by shiziyuan9527** [comment]
您好，根据日志显示，好像该禅道环境并不存在271项目。如果您确认271项目存在，请提供下禅道的具体版本。

**Comment by xulinde** [comment]
v1.20.10-lts未复现，建议升级下版本～
<img width="789" alt="image" src="https://user-images.githubusercontent.com/64065190/182096263-0e50afbb-947c-45b9-b3c0-befa19d35564.png">

**Comment by xulinde** [comment]
大致原因如下，请排查～

1.没有对应产品或者项目的权限，或者有权限但是需要填产品ID，结果填了项目ID
2.缺少配置 $config->features->apiGetModel
3.襌道里api超级调用模式有没有授权
