### ISSUE TITLE
[BUG]同一条SQL，MS只是SQL和Navicat执行结果不同

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16411]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

描述：同一条SQL，MS只是SQL和Navicat执行结果不同

### 重现步骤

ms执行结果：
![image](https://user-images.githubusercontent.com/15188833/181236902-fe00e273-ddec-4e38-92e5-bc6d441589a2.png)

Navicat执行结果：
![image](https://user-images.githubusercontent.com/15188833/181237004-ab7ae77c-ddf0-410f-973e-fda94f187d63.png)

**Comment by xulinde** [comment]
v1.20.10-lts未复现该问题，建议您升级下到最新版本
![image](https://user-images.githubusercontent.com/64065190/181408664-f99c3fe7-4018-439b-ae90-34ea5350dfc2.png)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/64065190/181408719-e86abc57-c9af-4a42-b6f0-af7b42e0efd4.png">
