### ISSUE TITLE
[BUG] 导出用例默认格式为txt格式

### ISSUE THREAD

**Issue by wch352136** [metersphere/metersphere#1641]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
我在Windows的子系统（Ubuntu）内搭建的MS，目前试用的时候，导出用例发现导出的是一个文本文档，打开全是16进制的文本。看了以前的更新以后猜测此文档原格式应该是xlsx或者xls，遂直接改了后缀名，然后可以用Excel打开。

**期待的正确结果**
下载的文件应该直接是xlsx格式，以后更新导出xmind格式也类似。

**截图**
![image](https://user-images.githubusercontent.com/17609338/111251606-8a3eb780-864a-11eb-8a4c-6ba6ac29f76c.png)

**Comment by xulinde2** [comment]
这个是不是跟浏览器设置有关，确认下

**Comment by wch352136** [comment]
> 这个是不是跟浏览器设置有关，确认下

我是在edge下(chromium)下载的，昨天您提示了以后找了Chrome试了一下，确实正确导出来Excel表格。我再看看为什么edge会出现这个问题。
