### ISSUE TITLE
[BUG] 首次添加场景变量csv本地文件，设置是否允许带引号为TRUE，保存后仍为False；非首次正常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16410]
### 联系方式

18311441708

### MeterSphere 版本

1.20.10.lts

### 使用外置数据库

否

### 问题描述

首次添加场景变量csv本地文件，设置是否允许带引号为TRUE，保存后仍为False；非首次正常
点击图1为首次添加设置TRUE后点击确认会出现图2
![企业微信截图_16589182114629](https://user-images.githubusercontent.com/103925124/181227158-103a92dc-0a81-4cd1-8a27-cbe55ee39058.png)

![1658918172(1)](https://user-images.githubusercontent.com/103925124/181227046-98460d81-39df-491e-bb52-efbaddc1aa31.png)

### 重现步骤

首次添加场景变量csv本地文件，设置是否允许带引号为TRUE，保存后仍为False；非首次正常

### 期待的正确结果

首次添加场景变量csv本地文件，设置是否允许带引号为TRUE，保存后为TRUE

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
