### ISSUE TITLE
[FEATURE]建议跳转到其他菜单时，未保存的新建用例有缓存或自动保存的功能

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16412]
### MeterSphere 版本

v1.20.9-lts

### 请描述您的需求或者改进建议

目前如果用例建到一半没保存，去“项目设置”等其他菜单，那这个用例就会被清掉，建议有自动保存的功能，或者回到测试跟踪，这个窗口依然开着，数据做个缓存

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
