### ISSUE TITLE
[BUG]后置脚本：python，出现乱码

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16421]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

后置脚本，使用python，打印内容包含 中文，控制台就乱码
脚本：
coulist = ['0022202207191439570000']
args =[[999,1],[888,1],[777,1]]
assert len(coulist) <= len(args), "arges len short"
coupons = []
a =u"测试"
for i in range(int(len(coulist))):
    cou = {"prizeName": "你好" + str(i + 1), "couponId": coulist[i], "sum": args[i][0], "claimsNum": args[i][1]}
    coupons.append(cou)
    

coupons = str(coupons)
vars.put("coupons", coupons)
coupons=coupons.decode("utf8")

log.info(coupons)
log.info(a)

### 重现步骤

控制台输出结果：
![image](https://user-images.githubusercontent.com/15188833/181430639-00866a3c-a0b7-4aec-ab20-ab08bbbab4ee.png)

**Comment by xulinde** [comment]
jmeter机制就是这样，我们底层用的jmeter～
![image](https://user-images.githubusercontent.com/64065190/181485969-15c7d7a2-5f0f-4c7f-867f-a6917a770988.png)
