### ISSUE TITLE
[BUG]执行UI自动化场景测试时，页面偶发报错提示"SQL error happened，please check logs"

### ISSUE THREAD

**Issue by R8619** [metersphere/metersphere#16429]
### 联系方式

飞致云-任建康

### MeterSphere 版本

v1.20.6-lts-1e3d1547

### 使用外置数据库

否

### 问题描述

在执行UI自动化测试场景时，页面偶尔会报错提示"SQL error happened，please check logs"。使用时，关闭了性能模式，选择的chrome，以生成报告的方式执行。
页面报错信息如下：
<img width="1274" alt="国信-UI执行-sql-error-00" src="https://user-images.githubusercontent.com/39123539/181441198-bcb46155-a434-4d9b-8ad9-97b1fd800474.png">

根据提示，在MS服务器上查看selenium容器日志没有看到明显报错新。但查看metersphere目录下的info.log以及error.log。查看那个时间点的日志，有如下报错信息。
<img width="1414" alt="国信-ms-logs-error-00" src="https://user-images.githubusercontent.com/39123539/181444243-1a1cb568-66e9-4b39-b90a-2c4989937e0b.png">
<img width="1398" alt="国信-ms-logs-error-01" src="https://user-images.githubusercontent.com/39123539/181445897-f4961721-e473-436f-bf9d-1ecdfd4a9462.png">

上面截图第二个中的request time out的报错在error.log中很常见，统计了一下上百个。
<img width="814" alt="国信-ms-error-统计" src="https://user-images.githubusercontent.com/39123539/181446108-3a38e555-d5cb-4ecb-af8d-2ce2d3c181b9.png">

排查时，查看了一下mysql库的一个连接数情况如下：
<img width="344" alt="国信-ms-数据库-连接数" src="https://user-images.githubusercontent.com/39123539/181446310-07cf717b-b568-447e-8b33-bd8e547fc878.png">

在排查问题时，又发现点击UI测试模块的测试报告，页面也存在类似报错信息，页面转圈的时间动不动就几分钟。
页面报错如下：
<img width="985" alt="国信-UI-测试报告-sql-error-00" src="https://user-images.githubusercontent.com/39123539/181446582-3078e791-7543-46e2-9b7c-883efcea8043.png">

查看metersphere的error.log日志，只看到如下报错信息：
<img width="1424" alt="国信-ms-log-error-timeout" src="https://user-images.githubusercontent.com/39123539/181451625-9f4f3861-ec81-448d-a852-28e843ac1294.png">

### 重现步骤

1、创建UI自动化场景，场景可以包含打开网页、输入账号、密码，最后点击登录。
2、执行时不勾选性能模式，选择"生成报告"，直接执行即可。
注：不是每次都能复现出来

### 期待的正确结果

1、正常执行，无类似报错信息。
2、如何能暂时解决此问题？
3、后续问题再现时，有没有别的排查问题的方式？需要再查看哪些日志信息？

**Comment by xulinde** [comment]
v1.20.10-lts未复现该问题，升级下版本吧
