### ISSUE TITLE
[BUG]测试用例模板中部分字段未标注是否为必填字段及如何填写，请优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#16420]
### MeterSphere 版本

1.20.10lts

### 使用外置数据库

否

### 问题描述

测试用例模板中编辑模式、用例等级、用例状态、责任人(ID)字段未标注是否为必填字段及如何填写，请优化

### 重现步骤

1.在未开启功能用例ID自定义的情况下，下载用例模板，查看模板下各字段说明情况；

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/181429973-9034c49b-ef17-4b18-a724-f03596a98ece.png)

**Comment by xulinde** [comment]
把鼠标放上去就可以看到的～
<img width="869" alt="image" src="https://user-images.githubusercontent.com/64065190/181481114-4d0558a4-22cb-417a-8fce-77abce095593.png">

**Comment by xulinde** [comment]
v1.20.13-lts已修复～
