### ISSUE TITLE
[BUG]meterspere与gitlab oidc集成时scope错误

### ISSUE THREAD

**Issue by zhengm09** [metersphere/metersphere#16428]
### 联系方式

zhengming@gitsec.cloud

### MeterSphere 版本

v1.20.x-lts 

### 使用外置数据库

否

### 问题描述

gitlab提供的oidc服务在与metersphere联通时传递的scope参数多了一个offline_access，导致获取授权时提示授权错误。手动在浏览器跳转url中删除+offline_access则授权通过

### 重现步骤

添加有效的gitlab服务端信息，进行oidc登录

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
