### ISSUE TITLE
[BUG]接口自动化，自定义接口dubbo请求有consumer&Serive是全的，但是编辑显示不全

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#1642]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26756176/111254180-75b0ee00-864f-11eb-8367-1bd18c0c4b0f.png)
![image](https://user-images.githubusercontent.com/26756176/111254191-7c3f6580-864f-11eb-8897-f315f6e604dd.png)

**Comment by xulinde** [comment]
收到，我们修复下

**Comment by zyyfit** [comment]
1.8.0已修复
