### ISSUE TITLE
[BUG]测试计划关联场景执行时间存在报告执行时间拉长的情况

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#16427]
### MeterSphere 版本

v1.20

### 使用外置数据库

是

### 问题描述

环境背景：
三台MS机器：8C、16G、500G。
部署架构：Redis和kafka部署在一台机器上，使用外部数据库。
运行情况：有18个测试计划，定时执行，执行周期分为1分钟、3分钟和五分钟，18个测试计划一共关联了1600个场景。
问题：
测试计划关联的场景定时任务执行时，大部分时间执行时间均在200S以内，小部分时间执行时间达到400S-500S左右，具体情况如下图所示：
1.场景报告截图：
<img width="879" alt="截屏2022-07-28 下午2 44 56" src="https://user-images.githubusercontent.com/34637801/181438717-c542fa1e-8a22-4d6a-adce-c0b898825611.png">

### 重现步骤

1.准备500个场景。
2.准备18个测试计划分别重复关联这500个场景，达到18个计划关联的总量为1600个左右。
3.执行时间为2个测试计划为2分钟执行一次，10个测试计划为3分钟执行一次，8个测试计划执行时间为5分钟执行一次。
注意：该问题无法稳定复现。

### 期待的正确结果

1.测试计划关联的场景报告执行时间希望能相对稳定，因为在1.19版本执行了4个月时间，未发生这样的情况，升级至1.20LTS后存在场景时间执行时间不稳定的情况。

**Comment by youliyuan-fit2cloud** [comment]
该问题已在较新版本中已优化，请升级后尝试一下。
