### ISSUE TITLE
[BUG]测试计划定时任务执行存在部分关联的场景报告状态错误

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#16426]
### MeterSphere 版本

v1.20

### 使用外置数据库

是

### 问题描述

环境背景：
三台MS机器：8C、16G、500G。
部署架构：Redis和kafka部署在一台机器上，使用外部数据库。
运行情况：有18个测试计划，定时执行，执行周期分为1分钟、3分钟和五分钟，18个测试计划一共关联了1600个场景。
问题：
测试计划关联的场景存在部分报告状态error的状态，但是进入报告详情里看，未发现任何错误，运维部分，在报告的对应时间点发出了数据库锁的告警，具体截图说明如下所示：
1.场景报告截图：
<img width="1189" alt="截屏2022-07-28 下午2 37 35" src="https://user-images.githubusercontent.com/34637801/181437455-fc01e061-b292-4691-b346-15e1d8793a5f.png">
2.数据库锁的告警图：
<img width="288" alt="截屏2022-07-28 下午2 39 04" src="https://user-images.githubusercontent.com/34637801/181437691-8578fa3b-fe30-4d36-9cdf-73cff2f7f819.png">

### 重现步骤

1.准备500个场景。
2.准备18个测试计划分别重复关联这500个场景，达到18个计划关联的总量为1600个左右。
3.执行时间为2个测试计划为2分钟执行一次，10个测试计划为3分钟执行一次，8个测试计划执行时间为5分钟执行一次。
注意：该问题无法稳定复现。

### 期待的正确结果

1.测试计划关联的场景报告状态与实际情况相符。

**Comment by zyyfit** [comment]
1.20.11已修复，请等待小版本发布
