### ISSUE TITLE
[BUG] 全局header参数在文档中没体现

### ISSUE THREAD

**Issue by magicpose** [metersphere/metersphere#16434]
### MeterSphere 版本

v2.0.0

### 使用外置数据库

是

### 问题描述

全局参数本身也是接口的一部分，文档里面没有体现不合理

![1658995239117](https://user-images.githubusercontent.com/7636934/181453575-b30cf99a-7f8c-4f57-8bed-dd8d91286963.png)

![1658995285312](https://user-images.githubusercontent.com/7636934/181453745-4f88b7e4-6f07-4e77-8a42-09dd114839e9.png)

### 重现步骤

见上“问题描述”

**Comment by xulinde** [comment]
接口文档展示的是接口信息，不同环境的独有配置是环境里的信息，不属于接口的基本信息

**Comment by magicpose** [comment]
> 接口文档展示的是接口信息，不同环境的独有配置是环境里的信息，不属于接口的基本信息

那比如说认证的token参数，每个接口都需要，让每个接口都单独在自己的header里面定义一次吗？有没有全局参数

**Comment by xulinde** [comment]
文档显示的是接口基本信息。我们认为您举的例子更偏向于接口运行时所需要的信息～
