### ISSUE TITLE
[FEATURE] 文档优化建议

### ISSUE THREAD

**Issue by magicpose** [metersphere/metersphere#16430]
### MeterSphere 版本

v2.0.0

### 请描述您的需求或者改进建议

接口文档这块页面html元素太多，有点杂乱，可否参考apipost的设计，页面易用清爽一点
![1658994869739](https://user-images.githubusercontent.com/7636934/181452515-9180ce6a-371b-4fac-a69f-7e73d97aa3ee.png)

**Comment by Hyyfit** [comment]
感谢反馈，近期有在规划这一步分的内容。
排期是先支持高级设置里的里的内容在文档页面可以展示，后续再优化整个文档的展示效果。
![image](https://user-images.githubusercontent.com/95834771/184132470-e12e5d66-09ba-4569-8c5e-0ad01f074e06.png)

**Comment by magicpose** [comment]
> 感谢反馈，近期有在规划这一步分的内容。 排期是先支持高级设置里的里的内容在文档页面可以展示，后续再优化整个文档的展示效果。 ![image](https://user-images.githubusercontent.com/95834771/184132470-e12e5d66-09ba-4569-8c5e-0ad01f074e06.png)

持续关注
