### ISSUE TITLE
[FEATURE]2.0接口测试-首页统计优化建议

### ISSUE THREAD

**Issue by magicpose** [metersphere/metersphere#16435]
### MeterSphere 版本

v2.0.0

### 请描述您的需求或者改进建议

2.0版本接口测试-首页的这些统计，堆叠在一起一眼看过去很混乱。细节上接口覆盖率是不是应该在接口通过率上面合理一点
![1658996165226](https://user-images.githubusercontent.com/7636934/181456663-b1ed7dc7-3e6a-445b-8b7a-aa3991c1979c.jpg)

**Comment by luty2018** [comment]
页面交互体验会在下半年重点优化，敬请关注哈

**Comment by magicpose** [comment]
> 页面交互体验会在下半年重点优化，敬请关注哈

好的
