### ISSUE TITLE
[BUG]性能测试报告数据比较大，点击导出报告，后台报错Operation timed out

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#16447]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

性能测试执行了十几个小时，没办法导出报告

### 重现步骤

1.性能测试执行十几个小时
2.点击导出报告
![image](https://user-images.githubusercontent.com/88763608/181469885-32b184fa-a820-4d15-9026-ccec103ad955.png)
3.后台报错 操作超时
![image](https://user-images.githubusercontent.com/88763608/181469925-10611737-d4b6-4fa0-997b-3071d8d05cef.png)

### 期待的正确结果

1.希望可以优化下，越是这种数据量大的报告，越需要导出。因为很占数据库容量，跑十几个小时，需要占用几十G到100G，如果能导出，就可以把数据库清理了

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，修改方案我们需要点时间讨论。
