### ISSUE TITLE
[BUG]性能测试报告导出PDF跟页面不一致

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#16442]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

导出的性能测试报告，部分内容之间冲突覆盖了，导致展示不了

### 重现步骤

1.查看在线性能测试报告
![image](https://user-images.githubusercontent.com/88763608/181463232-5dc0b9fb-47d9-483e-bd91-ef59b7e6aa5f.png)
2.导出性能测试报告对比
![image](https://user-images.githubusercontent.com/88763608/181463422-28ff8b0f-b85a-41c7-9962-5c85b2dfaa74.png)
error统计里面，混入了监控详情

### 期待的正确结果

跟在线的测试报告保持一致

**Comment by zyyfit** [comment]
2.0.0已修复
