### ISSUE TITLE
[BUG]性能测试报告点击停止，后台报错load test report time info is null

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#16443]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

1.性能测试实际上执行了26个小时，点击停止报告后，报告显示只执行了400多分钟

### 重现步骤

1.性能测试实际上执行了26个小时，点击停止报告后，报告显示只执行了400多分钟
![image](https://user-images.githubusercontent.com/88763608/181464983-6cc37cca-7720-434c-b3c0-0d0812767c8c.png)
2.查看日志发现，获取测试报告时间信息出错
![1658998532216](https://user-images.githubusercontent.com/88763608/181465121-2ec95e98-bc30-4a49-b15e-e29cfe8e5625.jpg)
load test report time info is null

### 期待的正确结果

不报错，报告执行时间正确

**Comment by zyyfit** [comment]
是服务器上的时间被更改过吗？

**Comment by linfengjjj** [comment]
没有修改过 性能测试几十分钟 几小时还是正常的 十几个小时的性能测试，手动点停止，时间就不对了

**Comment by linfengjjj** [comment]
昨天晚上看日志的时候，又发现了一个日志，报告时间的空指针
![4388bfe22b55b611f9b21933b5c6dca](https://user-images.githubusercontent.com/88763608/181672428-814ecee0-a2d1-4590-bf7e-c09850d1e159.jpg)

**Comment by linfengjjj** [comment]
发现kafka容器内部时间跟外部不一致，我先修改下，看是不是这个原因导致

**Comment by zyyfit** [comment]
> 发现kafka容器内部时间跟外部不一致，我先修改下，看是不是这个原因导致

好的
