### ISSUE TITLE
[BUG]SQL查询数据库查询结果是0被转换成为了false

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#16453]
### 联系方式

780368096@qq.com

### MeterSphere 版本

版本:   v2.0.0-9e3627ae

### 使用外置数据库

是

### 问题描述

链接数据库查询，查询结果为0被转换成为了false,导致接口自动化断言失败了，已经确认数据库字段类型为tinyint(1),另外查询所有数据是正常的

### 重现步骤

1、添加SQL的接口连接外置数据库，查询指定字段，eg:SELECT allocation_channel,real_inventory FROM `omsext`.`busi_presourcing_shipments` WHERE `orderid` = 'TC220728000850757';

### 期待的正确结果

查询结果显示为正确的0或者1

### 附加信息

![image](https://user-images.githubusercontent.com/26948634/181495756-a044e02f-dfbc-45a4-a3cc-60b103e4fe5e.png)
![image](https://user-images.githubusercontent.com/26948634/181495789-9da24ce1-a61e-4e51-b417-05b3141bf00c.png)
![image](https://user-images.githubusercontent.com/26948634/181497040-6b7c004b-0173-44d2-be87-094cd49da7ae.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您的mysql版本是多少？我们目前只支持mysql5.7，对其他版本没有做兼容处理

**Comment by Xin7S** [comment]
经过请教开发确认 是tinyint(1) 对于 java来说就是 boolean 类型，不会当做数字，不是bug
![image](https://user-images.githubusercontent.com/26948634/182518492-7d6021e0-8b9e-43d8-a432-e7f8264e6709.png)
![image](https://user-images.githubusercontent.com/26948634/182520046-56bbadd8-5c9f-4c7c-9d2a-c31d69099897.png)
