### ISSUE TITLE
[BUG]环境配置中将域名引用变量时，发送请求时，url格式拼接错误

### ISSUE THREAD

**Issue by 277169949** [metersphere/metersphere#16455]
### 联系方式

MeterSphere 交流群45

### MeterSphere 版本

v2.0

### 使用外置数据库

是

### 问题描述

发送请求时，url中的ip地址和端口被拼接加了一个[]导致请求发送失败：
![Uploading image.png…]()

### 重现步骤

1、在环境配置中将域名配置为一个变量：
![image](https://user-images.githubusercontent.com/5958875/181661076-58a96ae5-7a35-4f9e-8ea1-cf77056f586a.png)
2、对变量赋值：
![image](https://user-images.githubusercontent.com/5958875/181661111-5cc46fb5-c012-4f44-a4e3-4ec5aebf8933.png)
3、在用例中引用环境进行用例调试：
![image](https://user-images.githubusercontent.com/5958875/181661198-a66d15dc-2624-4870-8732-c845da6bf295.png)

### 期待的正确结果

希望拼接的url正确，可以正确发送请求

**Comment by yuanchenhuan** [comment]
非常简单，直接 core包修改一下sample取样器的url的规则，开发者修改下

**Comment by xulinde** [comment]
jmeter机制就是这样，我们底层用的jmeter～
![image](https://user-images.githubusercontent.com/64065190/181700564-19564729-4ffc-4a4d-9da3-b46f0e8a6b97.png)

**Comment by 277169949** [comment]
改下jmeter源码呗

**Comment by xulinde** [comment]
暂时不做改动哈～

**Comment by jgq2008303393** [comment]
> 暂时不做改动哈～

@xulinde 遇到相同的问题，有临时办法绕过吗？

**Comment by youliyuan-fit2cloud** [comment]
> jgq2008303393

你好，最新版本v2.10.2-lts解决了这个问题，建议升级一下吧。
