### ISSUE TITLE
[FEATURE]希望增加一个复制断言的功能

### ISSUE THREAD

**Issue by 277169949** [metersphere/metersphere#16456]
### MeterSphere 版本

v2.0

### 请描述您的需求或者改进建议

希望增加一个复制断言的功能

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/5958875/181663680-7db32ab5-28f8-45b6-9b1e-dcc934fa3853.png)

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
