### ISSUE TITLE
[BUG]首页关联用例数量统计与已覆盖数量不一致

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#16454]
### 联系方式

780368096@qq.com

### MeterSphere 版本

版本:   v2.0.0-9e3627ae

### 使用外置数据库

否

### 问题描述

首页关联用例数量统计与已覆盖数量不一致

### 重现步骤

不清楚

### 附加信息

![03](https://user-images.githubusercontent.com/26948634/181497330-8a1dee26-60ee-4d02-a2ef-e6fb9c3e568c.png)

**Comment by zyyfit** [comment]
这里的已覆盖指的是功能用例数量，是说有多少个功能用例关联了接口/场景/性能用例
