### ISSUE TITLE
[BUG]升级到v2.0.0版本后，脑图新增用例保存报错500，后台服务日志报NullPointerException

### ISSUE THREAD

**Issue by LianWilliam** [metersphere/metersphere#16457]
### 联系方式

交流群46

### MeterSphere 版本

v2.0.0

### 使用外置数据库

否

### 问题描述

升级到v2.0.0版本后，脑图新增用例保存报错500

![48da98436a543bf276e48077945a13c](https://user-images.githubusercontent.com/35838730/181667210-5c6bfd2d-8dc0-4a14-bad2-b7740d396828.jpg)

### 重现步骤

![005928813adb3092a2d28c85d19ee8c](https://user-images.githubusercontent.com/35838730/181667121-52283ee2-311e-482b-9109-a847f86e60d7.jpg)

### 期待的正确结果

帮忙看看，有没有临时的解决方法，目前脑图新增不了用例，谢谢！

**Comment by youliyuan-fit2cloud** [comment]
你好，创建的时候添加一个附件可以成功，我们也会尽快发布小版本，谢谢~

**Comment by xulinde** [comment]
您可以先在列表那添加用例～

**Comment by LianWilliam** [comment]
> 您可以先在列表那添加用例～

**Comment by LianWilliam** [comment]
> 您可以先在列表那添加用例～

对，目前只能通过表格写，表格写用例有点麻烦，脑图写用例比较直观

**Comment by xulinde** [comment]
这个只是临时解决方案，下周我们会发v2.0.1，修复该缺陷

**Comment by xulinde** [comment]
> > 您可以先在列表那添加用例～
> 
> 对，目前只能通过表格写，表格写用例有点麻烦，脑图写用例比较直观
这个只是临时解决方案，下周我们会发v2.0.1，修复该缺陷～

**Comment by LianWilliam** [comment]
> 这个只是临时解决方案，下周我们会发v2.0.1，修复该缺陷

我看这个问题标记为关闭了，我升级哪个版本可以修复这个问题呢？

**Comment by youliyuan-fit2cloud** [comment]
> > 这个只是临时解决方案，下周我们会发v2.0.1，修复该缺陷
> 
> 我看这个问题好像解决了，我升级哪个版本可以修复这个问题呢？

>请升级到 v2.0.1。
