### ISSUE TITLE
[BUG]UI测试，添加if、else条件判断，修改if名称后无法执行

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#16450]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

在UI测试中，场景中添加if和else，然后修改if的名称，点击执行不会正常执行

### 重现步骤

1.在UI场景中添加if和else
![image](https://user-images.githubusercontent.com/104493699/181484670-bb5e3b1d-039e-44d8-b997-1147a29d2fd7.png)
2.修改if的名称
![image](https://user-images.githubusercontent.com/104493699/181485501-4250c3bc-23fd-489e-a81b-518f0f8b1786.png)
3.点击生成报告
![image](https://user-images.githubusercontent.com/104493699/181485919-df878b17-8746-4d65-81f0-e80607b6d6a3.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
