### ISSUE TITLE
[BUG]ForEach循环列表语言选择groovy,只能取到列表第一个值

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#16458]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.10

### 使用外置数据库

否

### 问题描述

1.ForEach循环列表语言选择groovy,只能取到列表第一个值

### 重现步骤

1.创建场景，设置列表
![image](https://user-images.githubusercontent.com/103627487/181670180-4cb634ec-59b8-497d-898f-8f3f71ae8ee9.png)
2.设置ForEach循环，语言选择groovy
![image](https://user-images.githubusercontent.com/103627487/181670314-59aae84c-e2fd-42b3-9ede-6fd6ff5d3e4a.png)
3.控制台打印结果
![image](https://user-images.githubusercontent.com/103627487/181670422-282fac66-b3cc-4b6c-91bc-af0d69904967.png)

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
