### ISSUE TITLE
[BUG]环境配置新增了一个operation环境，发送请求时，域名没有自动赋值

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#16452]
### 联系方式

1136912596@qq.com

### MeterSphere 版本

v2.0.0-b4

### 使用外置数据库

否

### 问题描述

1、我这边环境配置新增了一个operation环境，发送请求时，域名没有自动赋值
![42fc96bc9d4ac73357204a97830ce01](https://user-images.githubusercontent.com/75885014/181493561-eb4166f0-8a1a-40cd-8c7b-49ee28b6a60e.jpg)
![Uploading 5f603679ced328d34880d8a1beb50b5.jpg…]()
![Uploading 3577113123f834f43a1942846f63019.jpg…]()

2、对比了下，发现使用自定义请求时才会出现上述问题，使用其他如接口列表导入，不会出现指定环境的域名没有赋值到请求中

### 重现步骤

如问题描述1、2

### 期待的正确结果

自定义请求也能一视同仁

**Comment by xulinde** [comment]
需要勾选“引用环境”
<img width="956" alt="image" src="https://user-images.githubusercontent.com/64065190/181672504-9fd19ca4-abc0-48a4-b9e5-f82f2aa9d730.png">
