### ISSUE TITLE
[BUG]脑图写测试用例，点击用例图标，保存时报错

### ISSUE THREAD

**Issue by qiaowenjuan123456** [metersphere/metersphere#16468]
### MeterSphere 版本

2.0

### 使用外置数据库

是

### 问题描述

脑图用例，点击用例图标后，点击保存，报错

### 重现步骤

脑图用例，点击用例图标后，点击保存，报错
![25f8771eae93f6b76a4e7af00613b2f](https://user-images.githubusercontent.com/110219188/181692467-562646c3-8555-4aa8-a9b7-e4f9941ccd27.jpg)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #16457
