### ISSUE TITLE
[BUG]【功能用例-回收站】测试用例恢复失败

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#16462]
### 联系方式

交流群45，付世鹏，andy.fu@31huiyi.com

### MeterSphere 版本

v2.0.0-9e3627ae

### 使用外置数据库

是

### 问题描述

回收站里的功能用例恢复失败，页面报错：{ "timestamp": 1659064806628, "status": 500, "error": "Internal Server Error", "path": "/test/case/reduction" }

### 重现步骤

1、进入功能用例-回收站页面。
2、点击列表操作列的恢复。

### 期待的正确结果

用例恢复成功，页面不报错。

### 相关日志输出

```shell
报错接口：/test/case/reduction

接口响应内容：
{timestamp: 1659064833818, status: 500, error: "Internal Server Error", path: "/test/case/reduction"}
error: "Internal Server Error"
path: "/test/case/reduction"
status: 500
timestamp: 1659064833818
```

### 附加信息

![企业微信截图_20220729112235](https://user-images.githubusercontent.com/110213256/181676146-80bb13d8-d218-472e-aba2-45cd69d5c53e.png)

**Comment by youliyuan-fit2cloud** [comment]
在最新版本 v2.0.1中已修复~
