### ISSUE TITLE
[BUG]通过接口测试/接口自动化创建性能测试，所属项目错误，且无法执行

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#1647]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
[BUG]通过接口测试/接口自动化创建性能测试，所属项目错误，且无法执行

**Bug 重现步骤**
1.  在接口测试/接口自动化设置好测试用例
2. 点击...创建性能测试
3. 设置参数后，点击保存并执行
4. 所属项目错误，且报error（节点状态都正常）

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/111403124-6f7e4880-8707-11eb-952d-c1834551e5cb.png)

![image](https://user-images.githubusercontent.com/12756697/111403320-b66c3e00-8707-11eb-87d8-5340ae2568a7.png)

![image](https://user-images.githubusercontent.com/12756697/111403328-b9ffc500-8707-11eb-9d4d-a3240cfb987f.png)

**Comment by xulinde** [comment]
执行性能测试过程中，node-controller 节点需要通过 系统-系统设置-系统参数设置 中配置的 当前站点 URL 下载相关文件。出现该问题时用户需要检查该配置参数，确保 node-controller 节点可以正常访问到该 URL。

URL 地址一般为通过浏览器访问 MeterSphere 的地址，例如 https://demo.metersphere.com
