### ISSUE TITLE
[BUG]环境配置中全局前置无法执行

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16484]
### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

接口中编写前置脚本通过http获取了一个cookie，同样代码搬到全局前置中（所有场景步骤前执行）无法执行也无报错信息，搬到全局前置中（单个请求步骤前执行）也是可以正常执行的

### 重现步骤

接口中编写前置脚本通过http获取了一个cookie，同样代码搬到全局前置中（所有场景步骤前执行）无法执行也无报错信息，搬到全局前置中（单个请求步骤前执行）也是可以正常执行的

### 期待的正确结果

能够正确执行前置脚本

**Comment by youliyuan-fit2cloud** [comment]
你好，根据目前您的貌似无法复现，请上传全局前置页面的配置截图和接口中的配置截图，方面我们复现问题，感谢~

**Comment by wszbc** [comment]
> 你好，根据目前您的描述无法复现，请上传全局前置页面的配置截图和接口中的配置截图，方面我们复现问题，感谢~

import java.net.URI;
import org.apache.jmeter.config.*;
import org.apache.http.client.CookieStore;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.*;
import org.apache.commons.text.StringEscapeUtils;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.client.protocol.HttpClientContext;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.impl.client.HttpClients.*;
import org.apache.http.util.EntityUtils;
import org.apache.http.entity.StringEntity;
import org.apache.jmeter.protocol.http.control.Cookie;
import org.apache.jmeter.protocol.http.control.CookieManager;
import org.apache.http.message.BasicNameValuePair;
HttpClientContext context = HttpClientContext.create();
// 创建Httpclient对象
CloseableHttpClient httpclient = HttpClients.createDefault();
// 定义请求的参数
URI uri = new URIBuilder().setScheme("http").setHost("oms-lppz-backend-test.lp.com").setPath("/pages/login/login-admin.jsp").build();
// 创建http请求
HttpGet get = new HttpGet(uri);
//response 对象
CloseableHttpResponse response = null;
response = httpclient.execute(get,context);
// 判断返回状态是否为200
if (response.getStatusLine().getStatusCode() == 200) {
    String content = EntityUtils.toString(response.getEntity(), "UTF-8");
}
// 获取Cookies
String Cookie="";
CookieStore cookieStore = context.getCookieStore();
List cookies = cookieStore.getCookies();
Iterator cookiesItr = cookies.iterator();
// 遍历Cookies；
while (cookiesItr.hasNext()) {
    cookieImp = cookiesItr.next();
    if (cookieImp.getName().equalsIgnoreCase("sid")) {
        Cookie = cookieImp.getValue();
    }
}
log.info(Cookie);
//定义Cookie对象，其中参数：cookie的名称, cookie值, cookie域, 路径, 安全
Cookie cookie = new Cookie("sid",Cookie,"oms-lppz-backend-test.lp.com","/",false,-1);
CookieManager manager = ctx.getCurrentSampler().getCookieManager();
manager.add(cookie);
log.info(manager.getCookieCount().toString());
// log.info("Cookie added: "+cookie);
// 创建Httpclient对象
// CloseableHttpClient httpclient = HttpClients.createDefault();
// 参数
String payload = "username=admin&password=admin&authEnable=false";
// List<NameValuePair> nvp = new ArrayList<>();
// nvp.add(new BasicNameValuePair("username", "admin"));
// nvp.add(new BasicNameValuePair("password", "admin"));
// nvp.add(new BasicNameValuePair("authEnable", "false"));
// 定义请求的参数
URI uri1 = new URIBuilder()
                .setScheme("http")
                .setHost("oms-lppz-backend-test.lp.com")
                .setPath("/auth/account/login")
                // .setPort() // int类型端口
                .build();
// 创建http请求
HttpPost post = new HttpPost(uri1);
post.setHeader("Content-Type", "application/x-www-form-urlencoded");
post.setHeader("Cookie","sid="+Cookie);
post.setEntity(new StringEntity(payload));
//response 对象
CloseableHttpResponse responsepost = null;
log.info(post.getEntity().toString());
responsepost = httpclient.execute(post,context);
URI uri2 = new URIBuilder().setScheme("http").setHost("oms-lppz-backend-test.lp.com").setPath("/pages/index.jsp ").build();
// 创建http请求
HttpGet get1 = new HttpGet(uri);
//response 对象
CloseableHttpResponse response = null;
response = httpclient.execute(get1,context);

这个是登陆为了获取cookie全局使用，放在后续接口的前置中没问题，放在全局前置中（单个请求步骤前执行）也是可以正常执行的，全局前置中（所有场景步骤前执行）就不行了，每次我都是单独开启一个前置来跑的

**Comment by youliyuan-fit2cloud** [comment]
这里加上呢?
![image](https://user-images.githubusercontent.com/54612864/181722454-19bf2857-748e-4ae4-ac33-720cb1c62f1c.png)

**Comment by wszbc** [comment]
> 这里加上呢? ![image](https://user-images.githubusercontent.com/54612864/181722454-19bf2857-748e-4ae4-ac33-720cb1c62f1c.png)

我这个方式相当于你们那个共享cookie按钮的功能，不需要特意去取参数，使用的是cookie管理器Cookie cookie = new Cookie("sid",Cookie,"XXXX","/",false,-1);
CookieManager manager = ctx.getCurrentSampler().getCookieManager();
manager.add(cookie);，如果直接用传参我就需要每个接口里面都去获取这个参数那应该是可以的，我就是不想每个接口都去加这个参数，接口太多了。

**Comment by wszbc** [comment]
> > 这里加上呢? ![image](https://user-images.githubusercontent.com/54612864/181722454-19bf2857-748e-4ae4-ac33-720cb1c62f1c.png)
> 
> 我这个方式相当于你们那个共享cookie按钮的功能，不需要特意去取参数，使用的是cookie管理器Cookie cookie = new Cookie("sid",Cookie,"XXXX","/",false,-1); CookieManager manager = ctx.getCurrentSampler().getCookieManager(); manager.add(cookie);，如果直接用传参我就需要每个接口里面都去获取这个参数那应该是可以的，我就是不想每个接口都去加这个参数，接口太多了。看起来应该是所有场景步骤前执行这个情况有问题，其它前置都是ok的

**Comment by song-tianyang** [comment]
您好，您这个是接口用例还是场景用例？

**Comment by wszbc** [comment]
> 您好，您这个是接口用例还是场景用例？

场景用例，目的就是为了把登陆操作放到环境全局前置中实现，功能类似于共享cookie按钮，不用去指定传参，代码应该是没有问题另外几个位置都能够跑，唯独所有场景步骤前执行这个位置不行
