### ISSUE TITLE
[BUG]刷新浏览器会导致模块展示丢失

### ISSUE THREAD

**Issue by ryanrain2016** [metersphere/metersphere#16499]
### 联系方式

ryan@top365.ml

### MeterSphere 版本

v2.0.0-9e3627ae

### 使用外置数据库

是

### 问题描述

在接口自动化页刷新浏览器后进入接口定义，接口定义的模块不显示

### 重现步骤

1. 进入【接口测试】-【接口自动化】菜单页面
2. 刷新浏览器
3. 进入【接口测试】-【接口定义】菜单页面， 这时大概率会出现接口定义没有显示任何已保存的模块

### 期待的正确结果

接口定义稳定展示正确的模块

**Comment by ryanrain2016** [comment]
好像是没有默认选择协议的原因

**Comment by xulinde** [comment]
是不是页面加载的慢，过一会能看到吗？方便录个视频看下吗？

**Comment by ryanrain2016** [comment]
这里发现不是必现，直接刷新就有几率复现，看请求就是协议是undefined；还有个小问题刷新有一定几率会跳转到首页
![image](https://user-images.githubusercontent.com/22925589/182056424-92b53de5-af2c-454b-87dc-14b75ae03e18.png)

**Comment by xulinde** [comment]
> 还有

这两个问题都没复现，直接录屏吧，看下你的操作

**Comment by xulinde** [comment]
> 这两个问题都没复现，直接录屏吧，看下你的操作



> 这里发现不是必现，直接刷新就有几率复现，看请求就是协议是undefined；还有个小问题刷新有一定几率会跳转到首页 ![image](https://user-images.githubusercontent.com/22925589/182056424-92b53de5-af2c-454b-87dc-14b75ae03e18.png)

这两个问题都没复现，直接录屏吧，看下你的操作

**Comment by xulinde** [comment]
> 这里发现不是必现，直接刷新就有几率复现，看请求就是协议是undefined；还有个小问题刷新有一定几率会跳转到首页 ![image](https://user-images.githubusercontent.com/22925589/182056424-92b53de5-af2c-454b-87dc-14b75ae03e18.png)

这两个问题都没复现，直接录屏吧，看下你的操作

**Comment by ryanrain2016** [comment]
![chrome_yAyt4BCbe9](https://user-images.githubusercontent.com/22925589/182273631-5543c167-ff7d-43b6-80bf-d0f9a1c51bde.gif)

**Comment by ryanrain2016** [comment]
偶尔会出现这种情况

**Comment by ryanrain2016** [comment]
偶现的要多试几次才会出来
![chrome_UG4bLsBHQm](https://user-images.githubusercontent.com/22925589/182274083-03f65313-4c65-4cb2-b601-263ec155481e.gif)

**Comment by xulinde** [comment]
尝试多次仍未复现～

https://user-images.githubusercontent.com/64065190/182578925-71c6d19e-1a3a-4fd5-a63f-7af785b502e3.mov
