### ISSUE TITLE
[BUG]断言使用脚本，切换为其他语言，在自动化场景调用后，自动变为了beanshell，会导致脚本运行报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#1649]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V。73
**Bug 描述**
简要描述您碰到的问题
断言使用脚本，切换为其他语言，在自动化场景调用后，自动变为了beanshell，会导致脚本运行报错
**Bug 重现步骤**
1.  自动化场景里接口使用脚本方式添加断言，修改脚本语言未python
2. 在自动化场景调用后，自动变为了beanshell执行，会导致脚本运行报错
3.
![image](https://user-images.githubusercontent.com/30038088/111409198-727e3680-8711-11eb-8a48-664ba168c1e3.png)
4. 
![image](https://user-images.githubusercontent.com/30038088/111409025-203d1580-8711-11eb-9f3b-e077bbc55994.png)

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
这个问题下个版本会修复

**Comment by xulinde** [comment]
v1.8已修复
