### ISSUE TITLE
[BUG]导入录制json格式文件时，Post请求里的body如是对象时，代码强转数组失败！

### ISSUE THREAD

**Issue by binbin199604** [metersphere/metersphere#165]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
master
**Bug 描述**
简要描述您碰到的问题
录制脚本后，有些请求包含body属性是对象，但是代码是所有body强转成数组，导致报错
**Bug 重现步骤**
1.  录制脚本
2. 编辑脚本，导出成json格式
3. 导入接口测试
4. 提示失败，日志报错为JSON强转数组失败

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
JSON脚本：
![image](https://user-images.githubusercontent.com/36029918/88498001-8515f500-cff4-11ea-80fb-75f8e476ac33.png)
代码：
1.io.metersphere.api.parse.MsParser#parsePluginFormat
2.com.alibaba.fastjson.JSONObject#getJSONArray
3.com.alibaba.fastjson.JSON#toJSON(java.lang.Object)

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.1.2  中修复
