### ISSUE TITLE
[FEATURE]接口测试-接口自动化页面，场景详情页-场景步骤中的复制按钮，复制的**用例**放在被复制用例的下方；建议接口测试-接口自动化页面的场景列表中的复制按钮，复制的**场景**放在被复制场景的下方

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#1650]
**请描述您的需求或者改进建议.**
接口测试-接口自动化页面，场景详情页-场景步骤中的复制按钮，复制的**用例**放在被复制用例的下方；建议接口测试-接口自动化页面的场景列表中的复制按钮，复制的**场景**放在被复制场景的下方

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/30038088/111409465-f2a49c00-8711-11eb-9167-c141d8f803d6.png)

**Comment by xulinde** [comment]
感谢反馈，这个后面版本可以优化下

**Comment by xulinde** [comment]
1.10已优化
