### ISSUE TITLE
[BUG]-缺陷管理-同步缺陷：执行缺陷同步之后，custom_field_issues表存储错误，导致缺陷列表处自定义字段展示错误

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#16508]
### 联系方式

企业微信：MeterSphere 交流群35；李彬

### MeterSphere 版本

版本:   v2.0.0-81da75b6

### 使用外置数据库

否

### 问题描述

执行缺陷同步之后，custom_field_issues表存储错误，导致缺陷列表处自定义字段展示错误

#### 创建缺陷
![ms_1](https://user-images.githubusercontent.com/102306978/182005552-595305c3-9801-4bd7-901d-d62d7630fe25.jpg)

![ms_创建完成1](https://user-images.githubusercontent.com/102306978/182005694-a4922139-fc98-47d5-9e6b-9a7d89c1040b.jpg)

#### 同步缺陷

![ms_同步之后数据库存储](https://user-images.githubusercontent.com/102306978/182005559-b0cac91d-336b-48a8-a0c2-8756dd3d709b.jpg)

![ms_同步完成之后展示](https://user-images.githubusercontent.com/102306978/182005705-f83825e8-5ae2-4025-ac6b-e5383e86917f.jpg)

### 重现步骤

1. 设置缺陷自定义字段，并且关联到禅道缺陷模版上
2. 在MS平台创建禅道缺陷，创建成功
3. 点击【同步缺陷】按钮

#### 禅道版本
开源版
[Designed by 艾体验](https://api.zentao.net/goto.php?item=aiux) [禅道12.5.2](https://www.zentao.net/)

### 期待的正确结果

正常展示

![ms_创建完成1](https://user-images.githubusercontent.com/102306978/182005694-a4922139-fc98-47d5-9e6b-9a7d89c1040b.jpg)

**Comment by youliyuan-fit2cloud** [comment]
今天发布的v2.0.1中已修复。
