### ISSUE TITLE
[FEATURE]测试计划能否单独模块？现在的逻辑有的怪，用起来不顺手。

### ISSUE THREAD

**Issue by wudamyw** [metersphere/metersphere#16507]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

测试计划能否单独模块？现在的逻辑有的怪，用起来不顺手。一个测试计划包含接口，UI，性能，功能的情况不多吧。（企业用户）

**Comment by Hyyfit** [comment]
您好，目前的设计如此。
