### ISSUE TITLE
[BUG]场景执行断言失败，状态未更改

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16501]
### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

场景结尾中的脚本断言失败，但场景执行状态还是成功未变成失败

### 重现步骤

场景结尾中的脚本断言失败，但场景执行状态还是成功未变成失败

### 期待的正确结果

场景状态能够正常更新为失败

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/181734829-7bce2af1-a5ea-4fad-b4b2-2f8b9ff93d90.png)

**Comment by xulinde** [comment]
自定义脚本和场景内其他步骤是独立的，只会对该脚本的请求结果做判断～
