### ISSUE TITLE
[BUG]python脚本涉及IO模块引用时，无法正常使用

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#16500]
### MeterSphere 版本

1.20.10lts

### 使用外置数据库

否

### 问题描述

jython解释器存在bug，在引用io包时，无法正确识别

### 重现步骤

相关脚本：
import sys
sys.path.append("/opt/metersphere/data/python/lib/python2.7/site-packages")
from faker import Faker

fake = Faker()
name = fake.name()

报错信息：
AttributeError: 'javapackage' object has no attribute 'BufferedIOBase' in <script> at line number 3

参考链接：
https://github.com/jython/jython/issues/64

**Comment by youliyuan-fit2cloud** [comment]
https://github.com/PyTables/PyTables/issues/505
请参考该链接看看
