### ISSUE TITLE
[BUG] 导入jmeter文件Parameter使用URL Encode时, 导入后没有勾选上Encode

### ISSUE THREAD

**Issue by C370228492** [metersphere/metersphere#16513]
### 联系方式

44群, 最, dalidong2009@163.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

导入jmeter文件, 导入前Parameter使用URL Encode时, 导入后没有勾选上Encode

### 重现步骤

在jmeter添加一个http request, Parameter指定某个参数使用URL Encode
保存
把 .jmx文件导入MS
对应参数吗没有Encode

### 附加信息

Jmeter的版本4.4.3

**Comment by xulinde** [comment]
v1.20.11-lts已修复～
