### ISSUE TITLE
[FEATURE]请问怎么样可以快捷或者批量修改接口CASE的状态。

### ISSUE THREAD

**Issue by pda37** [metersphere/metersphere#16512]
### MeterSphere 版本

v1.20.10-lts-787c5294

### 请描述您的需求或者改进建议

请问怎么样可以快捷或者批量修改CASE的状态。目前只看到可以批量修改用例等级。

**Comment by Hyyfit** [comment]
感谢反馈，现在在我的工作台，可以批量更新状态
<img width="787" alt="image" src="https://user-images.githubusercontent.com/95834771/182288832-6274618b-ef01-42ba-b7c3-cef8fbd5a41c.png">

后续版本会在接口CASE的列表页面加这个功能。
