### ISSUE TITLE
[BUG] query参数包括 ${xx} 然后指定URL编码后URISyntaxException

### ISSUE THREAD

**Issue by C370228492** [metersphere/metersphere#16514]
### 联系方式

44群, 最, dalidong2009@163.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

在query参数使用${}读取多个变量，然后再设置urlencode，执行时报URISyntaxException。
jmeter支持这个操作

### 重现步骤

1. 前置操作设置

vars.put("a", "a");
vars.put("b", "a");
vars.put("c", "a");
vars.put("d", "a");

2. query 参数 名称 a 值  ` {"${a}":${b},"${c}":"${d}"} `   ，并且选项编码 是

3. 执行
4. 控制台打印：__urlencode called with wrong number of parameters. Actual: 2. Expected: 1.
org.apache.jmeter.functions.InvalidVariableException  ；  请求内容 ： http://xxx/?a=${__urlencode({"${a}":${b},"${c}":"${d}"})}

**Comment by xulinde** [comment]
未复现该问题，方便把您的场景导出来吗？
<img width="938" alt="image" src="https://user-images.githubusercontent.com/64065190/182066014-67ed0969-2453-45e8-9fd1-301adf2ec344.png">

**Comment by xulinde** [comment]
这个函数不支持 json格式数据编码，jmeter也是如此～

**Comment by xulinde** [comment]
, 要转义 \,

**Comment by C370228492** [comment]
> <img alt="image" width="100" src="https://user-images.githubusercontent.com/64065190/182114104-0421d790-d01b-497b-bdaa-65a8c3a7a09b.png">

thx， 这个办法可以
