### ISSUE TITLE
[FEATURE]当没有配置selenium地址的时候，执行UI测试，虽然有提示，但页面一直转圈

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16520]
### MeterSphere 版本

v1.20.10-lts

### 请描述您的需求或者改进建议

当没有配置selenium地址的时候，执行UI测试，虽然有提示，但页面一直转圈。体验不太好。
![image](https://user-images.githubusercontent.com/33945037/182059307-50d8f23d-d684-4485-a106-a21598edaa81.png)

### 请描述你建议的实现方案

页面关闭掉不要一直转或者直接给提示框。

**Comment by zhangdahai112** [comment]
后面版本可以优化
