### ISSUE TITLE
[BUG] jmx文件断言功能，导入MS后不能完全正确解析

### ISSUE THREAD

**Issue by C370228492** [metersphere/metersphere#16521]
### 联系方式

44群, 最, dalidong2009@163.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

在jmeter使用jsonpath断言某个值**存在** ，导入MS后会被认为是使用正则匹配空字符

### 重现步骤

1.  在jmeter使用jsonpath断言某个值**存在**
2. 导入MS
3. 查看响应的断言

**Comment by xulinde** [comment]
jmeter的jsonpath断言不能选择匹配方式，导入到MS默认是正则匹配方式～
