### ISSUE TITLE
[BUG] tcp 带中文的返回值经过 gbk 编码后，在ms上展示解析为乱码

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#16526]
### 联系方式

18159668371

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

tcp 带中文的返回值经过 gbk 编码后，在ms上展示解析为乱码

ms附图：
![image](https://user-images.githubusercontent.com/92966838/182060208-a66c6b0f-1f43-4ce7-8abf-b027d1233fdb.png)

jmeter附图：
![image](https://user-images.githubusercontent.com/92966838/182060397-1706fb42-f20c-48b9-b927-24b912c6b252.png)

### 重现步骤

1. 配置tcp请求，请求编码方式选择GBK，并进行调试
2. 返回值可以成功收到响应体，说明请求体已经被tcp服务端解析
3. tcp服务端处理请求，并返回由gbk编码的响应体
4. ms响应体中文展示乱码

客户的tcp数据流流程图如下所示：
![image](https://user-images.githubusercontent.com/92966838/182061391-cb0fc49e-ef90-4279-996d-6ae2da794f2b.png)

### 期待的正确结果

gbk编码的带中文的响应体可以正常展示在ms上

**Comment by gaohonghai** [comment]
使用下述的后置脚本进行处理，展示还是乱码，希望可以给一些意见:
```
String resultStr = prev.getResponseDataAsString();

byte[] resultBytes = resultStr.getBytes("utf-8");

String gbkStr = new String(resultBytes, "gbk");

log.info("bgk编码结果,{}", gbkStr)
```

**Comment by xulinde** [comment]
v1.20.13-lts已修复～

**Comment by gaohonghai** [comment]
@youliyuan-fit2cloud 咱们v2.2版本又复现了这个问题，之前已经在v2.1修复了。
![image](https://user-images.githubusercontent.com/92966838/194682289-3005e518-fc74-4cd0-9cda-9d978a4dde58.png)
![image](https://user-images.githubusercontent.com/92966838/194682303-c81851b5-bdaa-4aa4-8857-7d986e3967b2.png)
