### ISSUE TITLE
[BUG][UI自动化]  UI自动化---点击后端调试--与生成报告执行结果不一致

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16523]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

升级到2.0，UI自动化点击后端调试，长时间处于执行中 无反应，生成报告很快就执行完了

### 重现步骤

1.上传UI自动化脚本
2.点击后端执行（卡住，无反应）
3.生成报告-（脚本全部通过）
4.对比两者执行结果

### 期待的正确结果

1.后端调试能成功执行完，能看到报错信息
2.生成报告和后端调试执行结果要一致

### 相关日志输出

```shell
:03:47,266  INFO openqa.selenium.remote.ProtocolHandshake:  66 - Detected dialect: W3C
Warning: Nashorn engine is planned to be removed from a future JDK release




2022-08-01 09:27:33,563  INFO openqa.selenium.remote.ProtocolHandshake:  66 - Detected dialect: W3C
Warning: Nashorn engine is planned to be removed from a future JDK release
```

### 附加信息

1.后端调试结果
![image](https://user-images.githubusercontent.com/45531073/182059143-977fed60-b2d7-42ba-8486-da60cb988b93.png)

2.生成报告结果
![image](https://user-images.githubusercontent.com/45531073/182059076-63bf1b95-4973-48cb-a823-7e77578b69f4.png)
![image](https://user-images.githubusercontent.com/45531073/183573954-7d381d93-7e37-4092-8dad-c9a69dcaa471.png)

[脚本]
[Metersphere_Ui_CARGOWARE (12).zip](https://github.com/metersphere/metersphere/files/9230401/Metersphere_Ui_CARGOWARE.12.zip)

 最新脚本
[Metersphere_Ui_CARGOWARE地.zip](https://github.com/metersphere/metersphere/files/9287287/Metersphere_Ui_CARGOWARE.zip)

**Comment by wudamyw** [comment]
来自企业用户的呼声，这个很严重，尽快修复。

**Comment by wudamyw** [comment]
附加信息，有的用例放一晚上都一直在运行，也不完成也没有什么错误反馈。
1，对任何异常要有处理有反馈。
2，为什么会异常？客服说加大等待时间可能可以，这也是问题，为什么需要那么久？生成报告模式很快都执行完了。

**Comment by liushuneng** [comment]
2.0.1问题已解决

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
