### ISSUE TITLE
[BUG]接口测试模块，入参使用QUERY参数，输入特殊符号，报错

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16522]
### 联系方式

452988409@qq.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

接口测试模块，入参使用QUERY参数，输入特殊符号，报错.

![image](https://user-images.githubusercontent.com/33945037/182059563-953882e3-2c31-40a2-ad09-83e0c4b50940.png)

### 重现步骤

1. 进入接口测试模块
2. 使用QUERY模式
3. 入参输入：abc|edf|ffff （只要有特殊符号 ' | ' 就会报错 ）

### 期待的正确结果

不应该报错

**Comment by C370228492** [comment]
点击右侧高级设置小图标，有个"编码"下拉框 选择 “是”

**Comment by xulinde** [comment]
如图操作～
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/64065190/182091923-c9b0fa6f-610e-4e9b-9d93-8cda58ed6596.png">
