### ISSUE TITLE
后续接入前后台角色后，建议规划一下接口文档规范化

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1653]
**请描述您的需求或者改进建议.**
1、前后端主要以接口文档，所以接口搜索、规范、文档化（需要更加直观）
2、接入类似Swagger直接生成接口

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.8版本接口定义会增加api文档功能

**Comment by idlqy** [comment]
附议，建议在接口定义中增加对接口文档的管理，支持自己添加一些md格式的接口的备注说明信息，这样前后端都可以通过这个平台来工作了

**Comment by xulinde** [comment]
v1.8已实现
