### ISSUE TITLE
[BUG] [测试计划]  测试计划-关联UI自动化场景-定时任务配置钉钉消息通知-定时任务执行完成 钉钉未收到消息

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16539]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

定时任务执行测试计划，设置钉钉接收消息，定时任务执行完未收到消息

### 重现步骤

1.创建一个测试计划
2.关联UI自动化
3.设置定时任务
4.设置任务通知为钉钉通知
5.执行完观察钉钉是否接收到消息

### 期待的正确结果

1.定时任务执行完，钉钉接收到消息

### 相关日志输出

```shell
无
```

### 附加信息

1.创建测试计划
![image](https://user-images.githubusercontent.com/45531073/182081032-b951af2e-5faf-411f-be74-2a47dfb89e35.png)

2.创建定时任务
![image](https://user-images.githubusercontent.com/45531073/182080902-4e846156-6dbf-484b-91a6-1a92d44db361.png)
3.设置消息通知
![image](https://user-images.githubusercontent.com/45531073/182080957-73047e4c-8df3-4c57-9972-782223b16cb3.png)
4. 定时任务执行完，钉钉未收到消息
![image](https://user-images.githubusercontent.com/45531073/182081126-f7ca1f70-681b-482c-adb5-20ab49c07fd5.png)

**Comment by wudamyw** [comment]
来自企业用户的呼声，自动化场景很重要的一环，希望尽快修复。

**Comment by zyyfit** [comment]
没有复现，请检查机器人过滤关键词是否正确
![image](https://user-images.githubusercontent.com/73461316/183580339-e956c306-8a3c-406d-a185-c1fb2e0f3795.png)

**Comment by zyyfit** [comment]
只有UI测试用例时能复现

**Comment by zyyfit** [comment]
2.1.0已修复
