### ISSUE TITLE
[BUG] [测试计划] 测试计划-关联UI自动化-点执行-报告状态显示不对

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16531]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

 测试计划-关联UI自动化-点执行-状态显示不对

### 重现步骤

1.创建一个测试计划
2.关联UI自动化场景
3.点串行执行
4.报告-查看状态

### 期待的正确结果

正在执行的报告，显示执行中

**Comment by liushuneng** [comment]
测试计划报告
![测试计划](https://user-images.githubusercontent.com/45531073/182065751-080d6545-8418-46eb-aaa8-0283ec548471.png)

**Comment by zyyfit** [comment]
没有复现这个问题，执行弹框是怎么配置的？截图给我看看
