### ISSUE TITLE
[BUG]接口自动化，场景，接口列表导入，选CASE tab页，按照名称搜索，搜索无效

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#16533]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud

### 使用外置数据库

否

### 问题描述

接口自动化，场景，接口列表导入，选CASE tab页，按照名称搜索，搜索无效

### 重现步骤

1. cloud版和私有部署都有这个问题。
2. 打开一个场景，选择接口列表导入，在弹窗页面选择CASE，按照用例名称搜索。会发现搜索无效。

**Comment by xulinde** [comment]
已知问题，v1.20.11-lts会修复

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/16228
