### ISSUE TITLE
[BUG]  [测试计划] 测试计划-关联UI自动化-点执行-报告成功率显示不对

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16534]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

测试计划-关联UI自动化-点执行-执行完查看报告成功率显示不对

### 重现步骤

1.创建一个测试计划
2.关联UI自动化场景
3.点串行执行
4.报告-查看成功率(测试计划完）

### 期待的正确结果

报告里成功率显示正确

### 附加信息

1.报告成功率
![Uploading image.png…]()

2.报告详情成功率
![Uploading image.png…]()

**Comment by liushuneng** [comment]
1.报告成功率
![image](https://user-images.githubusercontent.com/45531073/182076057-0526d099-464a-41ed-adbc-0d0560457ea4.png)
2.报告详情通过率
![image](https://user-images.githubusercontent.com/45531073/182076141-3436051b-65a4-447d-a877-725bdb3133b9.png)
需要点报告详情界面，重新进入报告模块才能显示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
今天发布的v2.0.1中已修复。
