### ISSUE TITLE
[QUESTION] metersphere 如何连接 kafka 

### ISSUE THREAD

**Issue by matthewxuda** [metersphere/metersphere#16540]
### 请描述您的问题

metersphere 如何连接 kafka

**Comment by Hyyfit** [comment]
可以看我们的官方文档：
https://metersphere.io/docs/installation/build_kafka/

**Comment by matthewxuda** [comment]
用 metersphere 的 beanshell 可以连接 kafka 吗

**Comment by Hyyfit** [comment]
理论上是可以的，上传对应的jar包，编写你想要的代码
