### ISSUE TITLE
[BUG] 接口导入->postman导入，导入接口出现嵌套展示

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16549]
### 联系方式

452988409@qq.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

接口测试模块
1. 接口定义
2. 导入接口-》postman格式导入。
3. 列表嵌套异常

![image](https://user-images.githubusercontent.com/33945037/182097403-79737adb-8349-443c-9bc0-655006240146.png)

### 重现步骤

1. 在项目中的controller中，直接通过ms的idea插件导出即可。

**Comment by hao65103940** [comment]
同样的数据格式，在MS的2.0里面是没有问题的

**Comment by zyyfit** [comment]
您好，我看您截图里的目录没有重复的，是不是在postman里就是这样的格式的？
还有，您标题里写的是postman导入，步骤里写的是idea插件导入，这是两种不同的导入方式，请具体描述一下操作步骤、哪里不对，并上传一下复现文件

**Comment by hao65103940** [comment]
idea插件源码里面，选择metersphere和postman方式是一样的。只有idea插件是这样导入的。所以如果要复现的话，页面上postman导入就可以复现。
可以试下测试文件：
[fg-xianshang-fix.txt](https://github.com/metersphere/metersphere/files/9336680/fg-xianshang-fix.txt)

**Comment by zyyfit** [comment]
我用这个文件导入postman失败了，有报错信息，是不是文件格式不对？
![image](https://user-images.githubusercontent.com/73461316/184783948-ae5cd29f-b298-4c32-9e01-81b3647609db.png)

**Comment by hao65103940** [comment]
我看到新版本 v1.20.12-lts-2297374a  已经修复了。 我这边导入没问题了。谢谢
