### ISSUE TITLE
[BUG]测试计划关联 功能、ui、接口测试用例 ，执行完成之后接口测试成功了但是提示error ui测试不执行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#16553]
### MeterSphere 版本

 v2.0.0-81da75b6

### 使用外置数据库

否

### 问题描述

测试计划关联 功能、ui、接口测试用例 ，执行完成之后接口测试成功了但是提示error ui测试不执行

### 重现步骤

1、该测试计划是历史测试计划，升级后关联了ui测试用例，执行就报错

2、若是新建测试计划关联相关用例则不复现

### 期待的正确结果

历史数据执行正常

### 相关日志输出

```shell
有error.log  见附件 执行时间：15点45左右
```

### 附加信息

<img width="775" alt="Snipaste_2022-08-01_15-57-42" src="https://user-images.githubusercontent.com/43202800/182103601-48a3b44d-fe01-46ff-a360-fb28b5a7f54c.png">
<img width="765" alt="Snipaste_2022-08-01_15-59-05" src="https://user-images.githubusercontent.com/43202800/182103608-96bfbdb4-4f7b-4a74-974d-c674492d949a.png">
<img width="769" alt="Snipaste_2022-08-01_15-59-28" src="https://user-images.githubusercontent.com/43202800/182103617-c4a201e1-c44d-4ec3-ac0d-d5693e6bae00.png">
<img width="922" alt="接口测试" src="https://user-images.githubusercontent.com/43202800/182103775-3cd95a83-94f6-46d7-9881-ccc82c61766a.png">
<img width="960" alt="测试计划批量执行接口 ui测试" src="https://user-images.githubusercontent.com/43202800/182103781-7f69b96d-ec7b-4312-95eb-10672780a3d4.png">

[error.log](https://github.com/metersphere/metersphere/files/9232140/error.log)

**Comment by xhy12** [comment]
校正：如果是新建的测试计划，关联的ui测试还是不执行，在ui自动化列表跑单个用例可以执行~
<img width="926" alt="如果是单个ui测试就会执行" src="https://user-images.githubusercontent.com/43202800/182105466-b7ee6eaa-3c99-4d54-9353-c6ada3b3aa96.png">

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您的ui场景导出side文件上传一下吗？

**Comment by xhy12** [comment]
side文件上传不了，

**Comment by zyyfit** [comment]
> side文件上传不了，

你改一下文件后缀，改成txt上传就可以，我下载后再改回来

**Comment by xhy12** [comment]
[Metersphere_Ui_测试项目323新建.txt](https://github.com/metersphere/metersphere/files/9238549/Metersphere_Ui_.323.txt)

**Comment by zyyfit** [comment]
收到，后续版本修复

**Comment by zyyfit** [comment]
2.0.1已修复，请等待明天版本发布后验证
