### ISSUE TITLE
[FEATURE]无论是在接口测试->场景测试中还是在测试跟踪->测试计划中多选用例后“批量执行”都没有选择“运行环境”的选项

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#1655]
**请描述您的需求或者改进建议.**

如题，无论是在接口测试->场景测试中还是在测试跟踪->测试计划中多选用例后“批量执行”都没有选择“运行环境”的选项，在有多个运行环境的情况下，无法直观确认是用的哪一套运行环境，

**请描述你建议的实现方案**

希望添加个选项，在批量执行时，能够选择或确认当前试用的哪一套运行环境

**Comment by xulinde** [comment]
1.8会增加批量修改运行环境的功能

**Comment by xulinde** [comment]
已支持
