### ISSUE TITLE
[FEATURE] 工作台看板优化

### ISSUE THREAD

**Issue by Clared1** [metersphere/metersphere#16550]
### MeterSphere 版本

v1.19.0

### 请描述您的需求或者改进建议

我们现在有个需求，希望工作台里面的接口覆盖率、场景覆盖率指标能多加个按照同个项目下建立的不同子模块来统计，类似树形结构图，叶子节点储存每个接口，非叶子节点储存每个模板，希望能在工作台看到这个功能。
![image](https://user-images.githubusercontent.com/47734806/182099548-3000a383-5c54-47ce-a290-e4604fbbb1d8.png)
![image](https://user-images.githubusercontent.com/47734806/182099193-644838a9-68a5-4921-ab35-7fd47af01ae6.png)
![image](https://user-images.githubusercontent.com/47734806/182099802-7eb09b20-2195-40d4-937a-cb6d2a547c64.png)

**Comment by luty2018** [comment]
了解，是个合理的需求，我们尽快排期
