### ISSUE TITLE
[QUESTION]上传jar插件，提示"解析插件失败，未找到入口配置"

### ISSUE THREAD

**Issue by NEOOOOOOOOOO** [metersphere/metersphere#16571]
### 请描述您的问题

版本：v1.19.2-b1

接口path：/plugin/add

步骤：
1. 进入系统设置-插件管理页面
2. 上传jar包并点击确定

结果：
接口响应： {"success":false,"message":"解析插件失败，未找到入口配置","data":null}

期望：
正常上传插件

**Comment by luty2018** [comment]
jar包是在项目设置-文件管理中上传。
