### ISSUE TITLE
[BUG] 建议不要从1.20lts升级到2.0 ，升级2.0，会导致系统直接挂掉，无法还原，一定要备份！！！

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#16577]
### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

 

现象：

mysql启动不了，系统直接挂了，然后这时我还原上一个版本的yml等文件，mysql依旧启动不了。

经初步判断，发现2.0mysql升级到了8.0, 但是旧版本的5.7生成的文件还在，8.0和5.7用同一个挂载路径.. 

### 重现步骤

1.20.10lts版本直接执行  msctl upgrade v2.0.0

**Comment by youliyuan-fit2cloud** [comment]
你好，lts版本升级到2.0.0版本需要下载安装包（在线或离线安装包都行），手动安装升级到最新的版本，具体步骤如下所示：
# wget https://github.com/metersphere/metersphere/releases/download/v2.0.0/metersphere-online-installer-v2.0.0.tar.gz
# tar zxvf metersphere-online-installer-v2.0.0.tar.gz
# cd metersphere-online-installer-v2.0.0
#  /bin/bash install.sh

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/182326195-79bae766-1645-44d3-9015-3734dbbb4638.png)

升级提示信息是否有关注？

**Comment by LimonFHM** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/182326195-79bae766-1645-44d3-9015-3734dbbb4638.png)
> 
> 升级提示信息是否有关注？

全部都执行了。

**Comment by LimonFHM** [comment]
> Reference in new issu


![image](https://user-images.githubusercontent.com/44999044/182531377-71de3b31-8833-4568-8f06-3e85383306aa.png)

**Comment by LimonFHM** [comment]
幸好mysql有备份，不然本次升级会导致所有数据丢失。特此提醒贵司自测升级！

**Comment by youliyuan-fit2cloud** [comment]
> 幸好mysql有备份，不然本次升级会导致所有数据丢失。特此提醒贵司自测升级！

我们当然自测啦，mysql从5.7迁移到8.0需要点时间，当时您升级的时候是多久没启动起来然后回退的？

**Comment by LimonFHM** [comment]
> > 幸好mysql有备份，不然本次升级会导致所有数据丢失。特此提醒贵司自测升级！
> 
> 我们当然自测啦，mysql从5.7迁移到8.0需要点时间，当时您升级的时候是多久没启动起来然后回退的？

所有程序都启动了，唯独mysql一直是unhelath 状态，查mysql日志  是shutdown状态。然后mysql容器不停重启。
