### ISSUE TITLE
[BUG] 用例新建子文件夹时候太难受了

### ISSUE THREAD

**Issue by Jacksonluang** [metersphere/metersphere#1658]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

1.用例树，不支持回车确认，体验真的很难受

**期待的正确结果**
正确情况下应该是什么样的？
输入文本后，按回车，提示新建好，并且目录不要收起来，新建多个子文件夹时太难受了
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/22166503/111581519-599a8180-87f4-11eb-998b-912d30edb0d8.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本会优化下这里

**Comment by youliyuan-fit2cloud** [comment]
v1.8版本已修复
