### ISSUE TITLE
[BUG]文件上传失败

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16583]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

描述：
在jmeter里面，场景运行成功，jmeter里面包含文件上传接口
但是把jmeter接口导出，然后导入到ms，文件上传接口执行失败

备注：**jmx文件不支持上传，我另存为word格式**

### 重现步骤

[Metersphere_Scenario_DevSecOps.docx](https://github.com/metersphere/metersphere/files/9238670/Metersphere_Scenario_DevSecOps.docx)

[任务导入模板.xls](https://github.com/metersphere/metersphere/files/9238816/default.xls)

ms运行结果：
![image](https://user-images.githubusercontent.com/15188833/182285504-c85f3f61-8f67-40da-bb5b-80491c8b6929.png)

Jmeter运行结果：
![image](https://user-images.githubusercontent.com/15188833/182285526-23c299be-b580-424c-929e-5380f3c09c14.png)

**Comment by zyyfit** [comment]
您好，系统没报错，而是您的接口返回了响应的错误信息，应该就不是excel文件上传问题，因为您的环境我们也没办法排查，您可以看一下请求信息是否正确，然后根据接口返回的错误信息，看看是什么问题导致的
