### ISSUE TITLE
[BUG] 前置脚本 vars.put 不成功

### ISSUE THREAD

**Issue by LinJie-Guo** [metersphere/metersphere#16581]
### 联系方式

a0s@foxmail.com

### MeterSphere 版本

 v1.20.5-lts-9fe3acfd

### 使用外置数据库

是

### 问题描述

前置脚本 vars.put 不成功

### 重现步骤

![image](https://user-images.githubusercontent.com/9551095/182283476-e9eae3ac-70e1-435d-b58a-821e7d5180db.png)
第9行可以设置成功（注释第12行，启用第9行 可以成功。 注释第9行，启用第12行设置失败）
![image](https://user-images.githubusercontent.com/9551095/182283587-27c60b58-ed00-4ecc-a021-a9a486d64f2c.png)

### 期待的正确结果

正确输出

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您的接口上传一下我们看看吗？
![image](https://user-images.githubusercontent.com/73461316/182352099-eead85ba-eece-492a-864f-b7dcb9e57efa.png)

![image](https://user-images.githubusercontent.com/73461316/182351999-5f670439-d6f2-49d7-9fba-eddb4470d3f6.png)

**Comment by zyyfit** [comment]
![image](https://user-images.githubusercontent.com/73461316/182352378-75393248-721d-479f-87ba-e333eadda2ee.png)
![image](https://user-images.githubusercontent.com/73461316/182352453-8677b37b-8fc4-4427-b30f-51936827dbb8.png)

**Comment by zyyfit** [comment]
另外，1.20最新版本是1.20.10了，马上要发1.20.11了，建议您升级试试

**Comment by LinJie-Guo** [comment]
> 另外，1.20最新版本是1.20.10了，马上要发1.20.11了，建议您升级试试

应该问题的行数 10， 你把第10行的代码加上去 
![image](https://user-images.githubusercontent.com/9551095/182353239-e0c2a697-871c-41e9-93c4-1ebe3ca752cc.png)

**Comment by zyyfit** [comment]
只加第十行肯定会报错呀，前面没定义arguments。。。
你看看你的控制台日志里有没有报错，如果没有的话，可以把完整的脚本代码复制一下贴上来

**Comment by LinJie-Guo** [comment]
> 只加第十行肯定会报错呀，前面没定义arguments。。。 你看看你的控制台日志里有没有报错，如果没有的话，可以把完整的脚本代码复制一下贴上来

`import httplib
import json
import hashlib

# 参数获取
arguments = sampler.getArguments(); 

secret = vars.get("secret")

arg = arguments.getArgumentsAsMap();

vars.put("sign", "aaaaaa")
`

**Comment by zyyfit** [comment]
好的，后续版本修复

**Comment by zyyfit** [comment]
您好，我们排查后发现jmeter里这样使用也不行，但是把 arg = arguments.getArgumentsAsMap() 这一行删除或者放到put后面就可以正常引用到；
由于我们目前使用jmeter执行接口请求，并且修改jmeter的源码影响比较大，所以暂时和jmeter保持一致
