### ISSUE TITLE
[FEATURE] json字符串设置变量， value值不能写成${xxx}，必须加""，加了后就是字符串，不是整形了，后台有规则限定整型。

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#16595]
### MeterSphere 版本

v2.0.0-b4

### 请描述您的需求或者改进建议

在request请求中，请求体json引用变量${xx},加了双引号就是字符串了，有些value值必须是int，就冲突了。

### 请描述你建议的实现方案

建议在json中增加一个转换函数，如int（）,先把${xx}转换成整形，再使用json去request。

**Comment by Hyyfit** [comment]
不加引号就可以了呀，是可以发送的成功的。

<img width="631" alt="image" src="https://user-images.githubusercontent.com/95834771/182305146-897504b0-aa07-4b50-913c-f0fc12f71c21.png">

**Comment by bobo-wk** [comment]
我这边试了下，确实可以，好的，辛苦
