### ISSUE TITLE
自动化测试支持控制台独立窗口或可调整展示位置

### ISSUE THREAD

**Issue by 710850609** [metersphere/metersphere#16596]
### MeterSphere 版本

v1.20.10-lts-b5

### 请描述您的需求或者改进建议

问题： 
接口自动化编写的时候，需要编写脚本、调试。调试依赖控制台输出日志定位问题。控制台和脚本上下展示距离不能在普通显示器（19-21寸）一屏展示，需要不断上下滚动页面，造成调试的额外操作，操作不流畅。

建议：
控制台支持独立小窗口运行。或是控制台支持类似浏览器开发者模式一样支持靠左边或右边展示。
期望控制台能和脚本在一个屏幕展示。

### 请描述你建议的实现方案

控制台支持独立小窗口运行。或是控制台支持类似浏览器开发者模式一样支持靠左边或右边展示。
期望控制台能和脚本在一个屏幕展示。

### 附加信息

![aac441e201bfecf4256134cc44e968a](https://user-images.githubusercontent.com/9523566/182304757-de3f803f-0556-47a0-9d64-3331c3760349.jpg)

**Comment by Hyyfit** [comment]
后续可以规划调整请求和响应窗口的大小，可以实现一屏同时展示两个部分的数据。
