### ISSUE TITLE
[QUESTION] quartz-spring-boot-starter，这个jar引入失败，搜索也是404

### ISSUE THREAD

**Issue by AmongZ** [metersphere/metersphere#166]
**请描述您的问题.**
        <dependency>
            <groupId>com.fit2cloud</groupId>
            <artifactId>quartz-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-autoconfigure</artifactId>
                </exclusion>
            </exclusions>
            <version>0.0.4</version>
        </dependency>
无法引入

**Comment by MadelS-F** [comment]
后端项目中依赖了该 Github 项目 https://github.com/fit2cloud/quartz-spring-boot-starter/packages/300609 ，开发者可按照 Github Maven 仓库的使用指导添加 Maven 仓库地址，自动下载该依赖包。

**Comment by wangzhen-fit2cloud** [comment]
挺多人有反馈这个问题，在 1.1.1 中我们会去掉 github 的仓库，把这两个依赖包传到 Maven 的 central 库中
