### ISSUE TITLE
[BUG]sql协议，有两个环境，都有A/B/C三套数据源，由A环境切换到B环境，之前A环境下的数据源为A/B/C，此时都变成了B环境下的数据源A了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#16606]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

sql协议，有两个环境，都有A/B/C三套数据源，由A环境切换到B环境，之前A环境下的数据源为A/B/C，此时都变成了B环境下的数据源A了。

场景中复制sql接口，在A环境下数据源是B和C
![image](https://user-images.githubusercontent.com/104960608/182312068-fe917e0c-6008-4e69-9b9a-a8717989addf.png)
![image](https://user-images.githubusercontent.com/104960608/182309071-c4484e2b-5543-49b4-9d45-7cd36c26496f.png)

选择运行环境为B环境后，数据源都会变成A
![image](https://user-images.githubusercontent.com/104960608/182312499-49186236-02f4-482a-9999-7c3d43e4d070.png)
![image](https://user-images.githubusercontent.com/104960608/182312411-33d8384e-545b-4d7d-bddf-e6ebeb8b3aa3.png)

### 重现步骤

1.新建两套 sql 环境，都含有A/B/C数据源
2.新建3个 sql 接口，选择好环境及对应的A/B/C数据源
3.在接口自动化-场景中，接口列表导入这3个 sql 接口
4.运行环境，选择另外一个 sql 环境，可看到下面接口对应的数据源都变成A了。

**Comment by youliyuan-fit2cloud** [comment]
你好，这个逻辑有什么问题？如果导入的sql接口想用自己的数据源可以手动再改一下，场景的运行环境切换后所有的接口环境都会随之变更。

**Comment by 2lipan** [comment]
A环境切换成B环境，使用A环境中的数据源应该与B环境的数据源保持一致，而不是单独手动修改。
如: 使用A环境中的数据源mysqlA/mysqlB/mysqlC，切换到B环境，也应该使用mysqlA/mysqlB/mysqlC，而不是都是mysqlA。

**Comment by youliyuan-fit2cloud** [comment]
没复现这个问题啊，会记录上一次同名的数据源。清下缓存 ？
