### ISSUE TITLE
[QUESTION] 运行性能测试kafka占用内存过大，内存溢出。

### ISSUE THREAD

**Issue by YongShuaiJi** [metersphere/metersphere#1660]
**请描述您的问题.**
性能测试 kafka服务运行占用内存过大
![image](https://user-images.githubusercontent.com/28250542/111588883-18f43580-87ff-11eb-9619-e3c1e6e4d636.png)

![image](https://user-images.githubusercontent.com/28250542/111589701-278f1c80-8800-11eb-86b4-0b6ab5668db5.png)

为什么会占用这么大内存

**Comment by xulinde** [comment]
是用的1.7.3版本吗，这个问题之前修复过的
