### ISSUE TITLE
[BUG]点击API模块，报错提示：network error，并且ms-server 挂掉了

### ISSUE THREAD

**Issue by yanyufeng1996** [metersphere/metersphere#16617]
### 联系方式

微信：言语风

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

点击API模块，报错提示：network error，并且ms-server 挂掉了

### 重现步骤

点击API模块，报错提示：network error，并且ms-server 挂掉了

**Comment by youliyuan-fit2cloud** [comment]
请登录MS服务器，查看ms-server的log，排查一下问题。
或者重启msclt restart 服务试试看吧。
