### ISSUE TITLE
[BUG]自动化执行项目间日志错乱

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16626]
### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

执行a项目自动化场景的同时，b项目也在执行，此时a项目控制台偶尔会打印出b项目的报错信息

### 重现步骤

执行a项目自动化场景的同时，b项目也在执行，此时a项目控制台偶尔会打印出b项目的报错信息

### 期待的正确结果

项目间能够隔离互不干扰

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，但目前日志无法隔离，执行日志是获取jmeter 自身打印的日志。
