### ISSUE TITLE
[QUESTION]请问怎么在接口的【TEST】或【CASE】功能中将提取的数据存储为变量

### ISSUE THREAD

**Issue by pda37** [metersphere/metersphere#16624]
### 请描述您的问题

例如：在登录接口调试时通过正则提取出响应中的Cookie，然后在阅读历史接口中引用这个Cookie，我虽然提取出来了，但是并不知道怎么设置成变量，然后引用。
后来发现在使用【接口自动化】功能时，将多个接口设置为一个场景，这些接口之间可以直接引用提取到的变量来实现接口关联。也可以直接勾选【共享cookie】。
![image](https://user-images.githubusercontent.com/67259090/182396009-5bd876b6-3912-474b-9a0a-fd7eb82f8797.png)

**Comment by Hyyfit** [comment]
![image](https://user-images.githubusercontent.com/95834771/182545354-81ae6ae1-daa2-46c2-ad1c-c0fce4359dc8.png)
详细的可以参考我们https://metersphere.io/docs/user_manual/api_test/api_step/?h=%E6%8F%90%E5%8F%96#16官方文档：
