### ISSUE TITLE
[BUG] 场景变量csv只添加变量名，未添加csv文件，场景内接口不执行，生成报告也无步骤数，场景数

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16644]
### 联系方式

18311441708

### MeterSphere 版本

1.20.10.lts

### 使用外置数据库

否

### 问题描述

场景变量csv只添加变量名，未添加csv文件，场景内接口不执行，生成报告也无步骤数，场景数
![1659507207(1)](https://user-images.githubusercontent.com/103925124/182537362-e4c9780a-44bc-4073-8640-47a3d6eeadd1.png)
![1659507421(1)](https://user-images.githubusercontent.com/103925124/182537495-59b1ed34-3149-40d1-9384-4e436a373b6f.png)
![Uploading 1659507438(1).png…]()

### 重现步骤

场景变量csv只添加变量名，未添加csv文件，执行场景---接口不执行，生成报告也无步骤数，场景数

### 期待的正确结果

场景变量csv只添加变量名，未添加csv文件，点击确认时报错，未上传csv

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.20.12版本已修复，请等待版本发布后验证
