### ISSUE TITLE
[FEATURE]测试计划关联测试用例，高级搜索条件里建议增加”用例等级“筛选条件

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#16660]
### MeterSphere 版本

v2.0.0-9e3627ae

### 请描述您的需求或者改进建议

测试计划关联测试用例，高级搜索条件里没有”用例等级“筛选条件。

### 请描述你建议的实现方案

测试计划关联测试用例，高级搜索条件里增加”用例等级“筛选条件。

### 附加信息

![image](https://user-images.githubusercontent.com/110213256/182588915-9197fff2-08a0-445f-8420-a302e782f086.png)

**Comment by Hyyfit** [comment]
列表页有用例等级的筛选，可以对搜索结果再进行筛选 
![image](https://user-images.githubusercontent.com/95834771/184130589-a60d6750-7eb3-486b-bb31-7ad87a9009f0.png)
