### ISSUE TITLE
[BUG]接口测试模块执行脚本是，ms自带的包中包含bcprov-jdk15on-1.70 jar包，但在性能测试执行时系统不自带bcprov-jdk15on-1.70 jar包

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#16661]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

接口测试模块执行脚本是，ms自带的包中包含bcprov-jdk15on-1.70，但在性能测试执行时不自带bcprov-jdk15on-1.70包。
这样会造成一个需要bcprov-jdk15on-1.70的脚本，导入到接口自动化中不需要导入jar包也正常运行。但会出现该脚本转换到性能测试后却无法正常执行的情况。

### 重现步骤

将一个需要bcprov-jdk15on-1.70 jar包的脚本导入到接口自动化模块内执行。不上传jar包也可正常执行。然后转换到性能测试场景，执行会失败，必须要手动上传bcprov-jdk15on-1.70 jar包才可以。

### 期待的正确结果

接口自动化和性能测试默认自带的jar包应该一样

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化一下，目前可以手动上传jar包到性能测试里面。

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
