### ISSUE TITLE
[QUESTION] ms 2.0.0  ms-server 一直重启 

### ISSUE THREAD

**Issue by sunny5156** [metersphere/metersphere#16664]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/2882717/182746899-5dc06df8-4cf4-4f33-9199-a2f3b38d5220.png)

================= 应用启动 =================
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/opt/jmeter/lib/ext/jython-standalone.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
sys.path: /opt/jmeter
Terminating due to java.lang.OutOfMemoryError: Java heap space

**Comment by sunny5156** [comment]
![image](https://user-images.githubusercontent.com/2882717/182750399-8330f0ea-a33b-4318-984e-9336f0c035f3.png)

**Comment by chengchengD** [comment]
你好，请问解决了嘛?  我的也是一直在重启
![CAF2C4AC-2864-4b0c-9A75-D9726E700B3A](https://user-images.githubusercontent.com/110531455/183374008-14e675a5-cba5-45f4-846f-84922013f686.png)

**Comment by zhangzhaox** [comment]
我也出现了类似情况 2.0.0版本
