### ISSUE TITLE
[BUG] 新建模块导入接口后，删除模块，再次导入，默认还是已删除的模块，导入成功在全部接口下

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16674]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

新建模块导入接口后，删除模块，再次导入，默认还是已删除的模块
![image](https://user-images.githubusercontent.com/103925124/182765637-e6b07dac-897f-4460-a3bf-82c7208d0cfc.png)
![1659588945(1)](https://user-images.githubusercontent.com/103925124/182766198-83eea9cc-78a7-4f63-8d03-aa1505bb5cb4.png)
![image](https://user-images.githubusercontent.com/103925124/182766208-c477cbb8-5c4d-4182-9d75-dd6bef5a2702.png)

### 重现步骤

新建模块导入接口后，删除模块，再次导入，默认还是已删除的模块，导入成功在全部接口下

### 期待的正确结果

导入时重新刷新模块，如上次导入模块已删除，显示默认模块（未规划接口）

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.1.0版本已修复，请等待版本发布后验证
