### ISSUE TITLE
[BUG]执行测试计划，对用例里的部分步骤选择测试结果后，用例的执行结果还是未开始，未更新成进行中

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16671]
### 联系方式

yujie@swirecocacola.com

### MeterSphere 版本

v2.0

### 使用外置数据库

否

### 问题描述

执行测试计划，对用例里的部分步骤选择测试结果后，用例的执行结果还是未开始，未更新成进行中，计划的状态已经变成进行中了
![状态问题1](https://user-images.githubusercontent.com/75236887/182756234-8fee2e19-4970-40bd-bfd9-cec5f65c9252.png)
![状态问题2](https://user-images.githubusercontent.com/75236887/182756251-6360b8dd-1b4c-451d-9ec0-37f3a988a2d2.png)

### 重现步骤

1.新建测试计划，选择用例
2.执行一个用例，对其中部分步骤选择测试结果，并保存
3.返回查看用例的执行状态还是未开始
4.查看计划的状态已更新为进行中

**Comment by zyyfit** [comment]
您好，这个是因为我们去掉了用例的进行中状态，只保留了未开始状态
