### ISSUE TITLE
[FEATURE] 场景编译不方便

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1667]
**请描述您的问题.**
场景用例有一下问题：
1.  基础信息占用屏幕空间太大；可见标红区域
![image](https://user-images.githubusercontent.com/5517369/111718776-8357b500-8895-11eb-888c-1ef3856fcad7.png)
2. 新增接口断言前置脚本时建议跳转到新增的位置。
3. 接口信息填写空间占用位置太大；可见标红区域
![image](https://user-images.githubusercontent.com/5517369/111719014-f82aef00-8895-11eb-9434-e183fa42201a.png)
4. 场景测试后请求内容没法复制
5. 场景测试后控制台输出没法复制；输出太长需要左右拖动
![image](https://user-images.githubusercontent.com/5517369/111719163-4cce6a00-8896-11eb-83a5-81ca21ce3871.png)

5. 请求体内不能软换行；需要左右拖动才能看完整行。
6. 脚本编辑页面需要改进。
![image](https://user-images.githubusercontent.com/5517369/111719300-8bfcbb00-8896-11eb-8849-c0eabdf18be3.png)

   1. 参考文档建议移到右侧；
   2. 没有快捷的方式扩展编辑区域的高度；也不能自适应输入的高度；看代码很费力
   3. 上下占用空余位置太多。浪费空间

**Comment by ferryzhou2021** [comment]
之前用旧版编写了290+接口测试用例，最近切换到新版。。。。。。。内心非常崩溃
新版真的好难用啊，查看断言、提取等，还要动不动就点开收起，各种不方便。
但是公司要求要用新版，赶紧优化吧，救救孩子

**Comment by guhan121** [comment]
> 之前用旧版编写了290+接口测试用例，最近切换到新版。。。。。。。内心非常崩溃
> 新版真的好难用啊，查看断言、提取等，还要动不动就点开收起，各种不方便。
> 但是公司要求要用新版，赶紧优化吧，救救孩子

我目前还在选型阶段 一堆的问题啊；天天上来提bug...

**Comment by wangzhen-fit2cloud** [comment]
辛苦各位了，感谢大家的反馈，我们会尽快进行修改

**Comment by luty2018** [comment]
> 之前用旧版编写了290+接口测试用例，最近切换到新版。。。。。。。内心非常崩溃
> 新版真的好难用啊，查看断言、提取等，还要动不动就点开收起，各种不方便。
> 但是公司要求要用新版，赶紧优化吧，救救孩子

马上救你

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/111953643-dd6caa80-8b21-11eb-9faa-87dc364bd231.png)

看看我这个界面；脚本那一栏只有7.8行；写脚本写的我好累。
@wangzhen-fit2cloud 
@luty2018 
@ferryzhou2021

**Comment by luty2018** [comment]
> **请描述您的问题.**
> 场景用例有一下问题：
> 
> 1. 基础信息占用屏幕空间太大；可见标红区域
>    ![image](https://user-images.githubusercontent.com/5517369/111718776-8357b500-8895-11eb-888c-1ef3856fcad7.png)
> 2. 新增接口断言前置脚本时建议跳转到新增的位置。
> 3. 接口信息填写空间占用位置太大；可见标红区域
>    ![image](https://user-images.githubusercontent.com/5517369/111719014-f82aef00-8895-11eb-9434-e183fa42201a.png)
> 4. 场景测试后请求内容没法复制
> 5. 场景测试后控制台输出没法复制；输出太长需要左右拖动
>    ![image](https://user-images.githubusercontent.com/5517369/111719163-4cce6a00-8896-11eb-83a5-81ca21ce3871.png)
> 6. 请求体内不能软换行；需要左右拖动才能看完整行。
> 7. 脚本编辑页面需要改进。
>    ![image](https://user-images.githubusercontent.com/5517369/111719300-8bfcbb00-8896-11eb-8849-c0eabdf18be3.png)
>    
>    1. 参考文档建议移到右侧；
>    2. 没有快捷的方式扩展编辑区域的高度；也不能自适应输入的高度；看代码很费力
>    3. 上下占用空余位置太多。浪费空间

4 没有重现，其他均已纳入排期

**Comment by guhan121** [comment]
@luty2018 
我的意思是在API测试后之后 只有响应体的那个tab里面可以复制。
其他 响应头 控制台 提取 和 请求内容没法选择后复制。
![image](https://user-images.githubusercontent.com/5517369/112076276-16099400-8bb5-11eb-90d4-17d0a0eb91ad.png)
图中这些灰底的位置都是没办法选择复制.
