### ISSUE TITLE
[BUG] 首次添加场景变量csv本地文件，设置分隔符为；保存后仍为，非首次正常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16675]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

![1659589496(1)](https://user-images.githubusercontent.com/103925124/182767242-1d4d3b85-ea11-4d68-a234-5ba45d6c9d83.png)
![企业微信截图_16595895504746](https://user-images.githubusercontent.com/103925124/182767250-c5b96b91-031c-4a20-b61d-45f017e1fc0d.png)

### 重现步骤

首次添加场景变量csv本地文件，设置分隔符为；保存后仍为，非首次正常

### 期待的正确结果

首次添加场景变量csv本地文件，设置分隔符为；保存后回显为；

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20版本和2.0版本都已修复，请等待版本发布后验证
