### ISSUE TITLE
[FEATURE]接口自动化定时任务设置 任务通知，需要登录查看测试报告

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16679]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

背景：
1.在接口定义模块，接口自动化里，设置定时任务和任务通知，在企业微信机器人/飞书机器人，消息通知，链接都是非免登录 查看测试报告。

2.在测试计划里面，设置定时任务和任务通知，企业微信机器人/飞书机器人的通知 ，免登录   查看测试报告。

### 重现步骤

接口自动化：
定时任务设置：
![image](https://user-images.githubusercontent.com/15188833/182773921-ba005b02-39ac-4bc1-84b2-ce5150fce87e.png)
![image](https://user-images.githubusercontent.com/15188833/182773920-53313069-4407-4c20-83fc-821d1e9ff764.png)

飞书机器人：
![image](https://user-images.githubusercontent.com/15188833/182774326-3ae6654c-b2dc-4e5e-99d2-0d0c2faf6a0a.png)
页面调整：
![image](https://user-images.githubusercontent.com/15188833/182774388-69965844-159c-4d66-a693-973739c0da5b.png)

### 期待的正确结果

希望 接口自动化 和 测试计划 ，设置定时任务和任务通知，报告都可以 免登录 查看测试报告详情

**Comment by zyyfit** [comment]
现在是分享的链接可以免登录查看，通知里的现在还不可以

**Comment by startpjx** [comment]
后期会有这个规划吗？
测试计划里面，设置定时任务和任务通知，在飞书通知群里面的链接是免登录查看的，测试计划的定时任务可以免登录，为什么接口自动化的定时任务不行？
