### ISSUE TITLE
[BUG] 【版本管理】 项目管理-版本管理-切换版本-  接口列表页面与修改接口页面版本未变化

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16689]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

想在版本管理页面，切换接口版本，接口列表与修改接口页面显示的版本未变化

### 重现步骤

1.开始接口版本管理
2.进入项目管理-版本管理页面
3.切换接口版本
4.进入接口列表和接口修改页面，观察版本是否有变化

### 期待的正确结果

切换接口版本时，接口列表和接口修改页面的版本会换成切换的版本

### 附加信息

1.切换版本
![image](https://user-images.githubusercontent.com/45531073/182984698-8303158e-1de3-4f15-9a91-229f1e4da6d8.png)
2.接口列表
![image](https://user-images.githubusercontent.com/45531073/182984795-ba987126-e245-4186-8dbf-5af652e2184f.png)
3.编辑接口列表页面
![image](https://user-images.githubusercontent.com/45531073/182984851-d816b894-eab5-4107-9f1d-db7ce2fe77b5.png)

**Comment by xulinde** [comment]
理解有误哦，不是切换版本，只是设置成最新版本。如果需要在新版本创建接口，按如下操作～
<img width="744" alt="image" src="https://user-images.githubusercontent.com/64065190/183017322-78f504aa-14e1-42a7-8a42-8aaf4f215d5b.png">
