### ISSUE TITLE
[BUG] 【测试跟踪】 用例评审-脑图批量评审- 用例状态未改变

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16680]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

是

### 问题描述

  用例在线评审时，切换成脑图批量评审，用例状态未改变

### 重现步骤

1.用例评审-创建用例评审
2.关联功能用例
3.切换到脑图评审
4.选择最上面模块-点通过
5.保存

### 期待的正确结果

点批量通过时，所有用例状态都变为通过

### 附加信息

1.保存用例
![image](https://user-images.githubusercontent.com/45531073/182795626-c2bd5403-70a4-433c-a743-5d1497cfee12.png)

2.用例状态未改变
![image](https://user-images.githubusercontent.com/45531073/182794703-e739c4da-5f2a-4fa3-828d-a69b086e465a.png)

**Comment by xulinde** [comment]
v2.1.0已修复，建议您升级下～
