### ISSUE TITLE
[BUG] swagger导入URL中有中文，报错链接超时，urlencode转码中文部分，替换URL中文部分后进行导入

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16684]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

![企业微信截图_16596067235692](https://user-images.githubusercontent.com/103925124/182818701-28b33c96-3c44-4e46-bb9e-108e6e3df471.png)
http://localhost:8036/v3/api-docs?group=测试组测试组测试组测试组

http://localhost:8036/v3/api-docs?group=%E6%B5%8B%E8%AF%95%E7%BB%84%E6%B5%8B%E8%AF%95%E7%BB%84%E6%B5%8B%E8%AF%95%E7%BB%84%E6%B5%8B%E8%AF%95%E7%BB%84

可导入

### 重现步骤

导入swagger URL中带中文

### 期待的正确结果

swageer不转码仍可导入

**Comment by youliyuan-fit2cloud** [comment]
你好，建议升级到1.20.10-lts以上版本，对导入问题做了很多改动和优化。

**Comment by Ycr123888** [comment]
不好意思，写错了，用的是最新版本1.20.11-lts

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉，长时间未反馈该问题，考虑到该问题的优先级暂时不支持，后续版本会规划。
