### ISSUE TITLE
[FEATURE]关联需求，并能按照需求的状态筛选。管理bug 的生命周期和状态

### ISSUE THREAD

**Issue by flightefore** [metersphere/metersphere#16692]
### MeterSphere 版本

v1.20.x-lts 

### 请描述您的需求或者改进建议

1.关联第三方需求的软件，现在是吧所有需求都列了出来，没有按照状态筛选。希望能按照状态筛选，并能查看里里面需求的具体内容。
2.能管理缺陷，bug 的生命周期，现在只能删除缺陷。希望能有缺陷的生命周期管理

**Comment by luty2018** [comment]
关联第三方需求我们目前只能做到展示标题，如果要展示内容，这里要解析的东西比较多，暂时还没有这个计划。
