### ISSUE TITLE
[BUG] 导入postman文件只能导入最后一个api接口

### ISSUE THREAD

**Issue by sundafa** [metersphere/metersphere#16696]
### 联系方式

MeterSphere 交流群47

### MeterSphere 版本

v2.0.0

### 使用外置数据库

否

### 问题描述

导入postman文件只能导入最后一个api接口

### 重现步骤

v2.0.0 导入 postman 文件测试

### 期待的正确结果

导入全部api接口

### 附加信息

![image](https://user-images.githubusercontent.com/24621599/182997324-812283ec-9804-47d9-ba90-f7133e82d539.png)
![image](https://user-images.githubusercontent.com/24621599/182997334-a259cd74-3ab7-4687-ba95-485c3e70a961.png)

**Comment by sundafa** [comment]
https://documenter.getpostman.com/view/4117254/ethereum-json-rpc/RVu7CT5J
postman 文件

**Comment by zyyfit** [comment]
您好，您这个地址不能导入postman保存成postman文件，方便把postman导出的文件上传一下吗？可以把文件后缀改成txt上传

**Comment by sundafa** [comment]
@zyyfit 已经导出文件，你可以尝试导入自己的系统上

[Ethereum JSON-RPC.postman_collection.txt](https://github.com/metersphere/metersphere/files/9267340/Ethereum.JSON-RPC.postman_collection.txt)

**Comment by zyyfit** [comment]
好的，复现了，感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，这里有个bug，下个版本会修复

不过我看您这个文件里的请求，url都是一样的是吗，如果是这样的话，修复后，导入的时候会去重，如果不开启url可重复，确实是只会导入一个接口；开启url可重复后，可以正常导入

您还有什么问题的话，可以企业微信交流群里 @张杨杨
![image](https://user-images.githubusercontent.com/73461316/183341145-b4fff6bd-1187-4c8a-8fdc-b0fde7609378.png)

**Comment by sundafa** [comment]
开启后可以导入多个了，导入示例文件格式提示错误问题等之后解决了

**Comment by zyyfit** [comment]
1.20 和 2.0 版本都已修复，请等待版本发布后验证
