### ISSUE TITLE
[BUG]基于helm在K8S部署安装MS2.0，安装失败，数据库报错Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#16697]
### MeterSphere 版本

V2.0

### 使用外置数据库

否

### 问题描述

基于helm在K8S部署安装MS2.0，安装失败，数据库报错Public Key Retrieval is not allowed

### 重现步骤

基于helm在K8S部署安装MS2.0，安装失败，数据库报错Public Key Retrieval is not allowed

### 附加信息

![822a5a5f8034b99095eae89dae49374](https://user-images.githubusercontent.com/92150453/182998292-b7ac9aa2-a7ff-4441-b122-50c14f4c31c9.jpg)
![3ce4987c1ce61e6bd0544f7690b7ece](https://user-images.githubusercontent.com/92150453/182998301-b3a35500-35e5-4a7a-8655-c93597cd4326.jpg)
[ms-server.log](https://github.com/metersphere/metersphere/files/9265097/ms-server.log)

**Comment by wan92hen** [comment]
你好，该问题可以在部署时使用的 values 文件中修改 server.properties 中的 jdbc 连接串，增加 `&allowPublicKeyRetrieval=true` 参数。
同时 helm chart 已更新，也可以直接更新 chart 再次尝试安装。
