### ISSUE TITLE
[BUG]请求参数为multipart/form-data--文件，返回非正常结果（同样的参数，postman返回正常结果）

### ISSUE THREAD

**Issue by ferryzhou2021** [metersphere/metersphere#1669]
**MeterSphere 版本**
v1.7.3-2b9713b1

**Bug 描述**
1、上传头像，请求参数为multipart/form-data--文件

**Bug 重现步骤**
1.  请求参数定义如下
![image](https://user-images.githubusercontent.com/80932210/111722230-670b4680-889c-11eb-86bb-0c0c9c974d57.png)

2. metersphere接口测试用例信息如下
![image](https://user-images.githubusercontent.com/80932210/111722321-9752e500-889c-11eb-974d-d06948354c4a.png)
![image](https://user-images.githubusercontent.com/80932210/111722349-a76ac480-889c-11eb-86d0-d0df56bd66ee.png)
返回结果
![image](https://user-images.githubusercontent.com/80932210/111722401-bfdadf00-889c-11eb-8190-9661e50b8e7b.png)

3. postman接口测试用例信息如下
![image](https://user-images.githubusercontent.com/80932210/111722459-dbde8080-889c-11eb-8bfc-82e97b86f856.png)
![image](https://user-images.githubusercontent.com/80932210/111722474-e39e2500-889c-11eb-9130-08dcb239ab8a.png)
返回结果
![image](https://user-images.githubusercontent.com/80932210/111722507-f153aa80-889c-11eb-98d8-347189def5fd.png)

4. 

**期待的正确结果**
与postman返回结果一致

建议：下图上传文件的位置可以往前挪
![image](https://user-images.githubusercontent.com/80932210/111722588-1cd69500-889d-11eb-90ce-41445cb9ccf8.png)

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
这个问题没复现，您是用的最新版本吗
