### ISSUE TITLE
[BUG]测试跟踪-用例评审 从列表评审界面进入编辑用例，模块信息丢失

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#16699]
### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/42445400/183014198-3c2f95be-3725-4401-bdeb-120bd4914e3a.png)
列表评审界面，点击用例标题进入编辑用例
![image](https://user-images.githubusercontent.com/42445400/183014347-3d51e378-9cda-4d9c-b73f-2ba3023701dc.png)

### 重现步骤

1创建评审，关联用例
2开始评审用例
3列表评审界面，点击用例标题进入编辑用例

### 期待的正确结果

模块信息正常显示

**Comment by xulinde** [comment]
这个没有复现，是不是那个用例本身就没有模块？

**Comment by lyxlin** [comment]
有模块
![20220810140112](https://user-images.githubusercontent.com/42445400/183826789-5c9622ec-d5c4-4459-814e-09742761b89b.gif)

**Comment by xulinde** [comment]
是个别用例还是所有用例有这个问题呢，您版本是最新的1.20.12-lts吗？我这边还是未能复现
https://user-images.githubusercontent.com/64065190/185079406-2af775cb-4eaf-4225-9343-f312bcba68aa.mov
