### ISSUE TITLE
[BUG]接口用例数量统计中，用例通过率统计错误

### ISSUE THREAD

**Issue by pingchaodeng** [metersphere/metersphere#16698]
### MeterSphere 版本

v2.0.0-81da75b6

### 使用外置数据库

否

### 问题描述

接口用例数量统计中，用例通过率应统计 本次用例执行成功数/用例总数；错误统计为：本次用例执行成功数/用例历史总执行次数

### 重现步骤

接口用例数量统计中，用例通过率应统计 本次用例执行成功数/用例总数；错误统计为：本次用例执行成功数/用例历史总执行次数

**Comment by zyyfit** [comment]
您好，我们的接口用例通过率是这样算的：最后一次执行成功的用例 / 用例总数*100%，就是统计里的 已通过的用例数量 / 用例总数
![image](https://user-images.githubusercontent.com/73461316/183020081-3eaa3a4e-779a-4653-8eb4-193f9bc26401.png)
