### ISSUE TITLE
[BUG]接口自动化，场景中包含“文件上传”，上传失败

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16700]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

      在接口定义模块，接口自动化里面，新增场景包含“文件上传”步骤，请求体类型为“file",在场景中“调试”，直接提示：{ "timestamp": 1659679641633, "status": 500, "error": "Internal Server Error", "path": "/api/automation/run/debug" }。请求体类型缓存“text”，“调试”，场景可以运行，但是接口执行失败。
    接口自动化文件上传场景，是从JMeter导入到MS，在JMeter运行没问题。

### 重现步骤

MS接口自动化场景调试：file类型
![image](https://user-images.githubusercontent.com/15188833/183013612-ceec6f3e-0188-4fa1-9c03-e4893bb88eb0.png)

JMeter运行结果：
![image](https://user-images.githubusercontent.com/15188833/183013819-5ae37a11-ca2a-4835-a06b-7ee768f97e7d.png)

jmx文件不支持上传，我把脚本改为txt类型。
[Import.txt](https://github.com/metersphere/metersphere/files/9265937/Import.txt)
[importAgentUserFile2.xlsx](https://github.com/metersphere/metersphere/files/9265939/importAgentUserFile2.xlsx)

**Comment by zyyfit** [comment]
这个是2.0.0的问题，2.0.1版本已经修复了
![image](https://user-images.githubusercontent.com/73461316/183020823-3ba7c754-48f4-48e6-8411-dc2c57274f29.png)
