### ISSUE TITLE
[FEATURE]建议增加功能测试用例自定义字段值的导入和导出功能

### ISSUE THREAD

**Issue by zhangshihao930112** [metersphere/metersphere#16703]
### MeterSphere 版本

v2.0.0-9e3627ae

### 请描述您的需求或者改进建议

无法将自定义字段用例的值进行导入和导出

### 请描述你建议的实现方案

用例设置自定义字段后，可以导入导出自定义字段的值

### 附加信息

![微信截图_20220805144721](https://user-images.githubusercontent.com/85295604/183018465-b56c666e-1272-4ebd-b21f-79c78481b7dc.png)

**Comment by Hyyfit** [comment]
功能已规划了，2.1的版本会上线
