### ISSUE TITLE
[BUG]在环境配置获取一个参数，只传递给了一个接口使用

### ISSUE THREAD

**Issue by ferryzhou2021** [metersphere/metersphere#1670]
**MeterSphere 版本**
 v1.7.3-2b9713b1

**Bug 描述**
同一个场景中，在环境配置请求头获取一个参数，该参数只传递给了一个接口使用

**Bug 重现步骤**
1.在在环境配置获取一个参数
![image](https://user-images.githubusercontent.com/80932210/111723695-f0bc1380-889e-11eb-963f-4303b045aa02.png)
2.
该场景中有1个以上接口请求头需要该参数
![image](https://user-images.githubusercontent.com/80932210/111724005-6fb14c00-889f-11eb-9882-5d4e68d3a049.png)

提取参数
![image](https://user-images.githubusercontent.com/80932210/111724385-1ac20580-88a0-11eb-9816-c58d5cdc3ded.png)

3.该参数只传递给了第二个接口
![image](https://user-images.githubusercontent.com/80932210/111724161-b8690500-889f-11eb-9ea4-a007defaf927.png)

第四个接口请求内容
![image](https://user-images.githubusercontent.com/80932210/111724205-cdde2f00-889f-11eb-94a0-d9bf0834f7ca.png)

**期待的正确结果**
统一场景中的所有接口都可以获取该参数
（旧版可以正常使用）

另一小问题：环境配置---通用配置描述显示不全
![image](https://user-images.githubusercontent.com/80932210/111724822-e864d800-88a0-11eb-9bcf-12df35bd53d3.png)

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
好的，我们复现下再反馈

**Comment by xulinde** [comment]
未复现该问题
