### ISSUE TITLE
[FEATURE]同一个空间下不同项目的自定义用例模板，无法进行复用

### ISSUE THREAD

**Issue by zhangshihao930112** [metersphere/metersphere#16718]
### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

同一个空间下不同项目的用例模板，无法进行复用自定定义用来模板

### 重现步骤

同一个空间下
在A项目自定义了一个用例模板，B项目无法使用A项目的用例模板，也没有复制功能

### 期待的正确结果

同一个空间下，所有自定义的用例模板应该都能进行复用

**Comment by Hyyfit** [comment]
我们2.1的版本会上同一个工作空间下，缺陷模版的复制。
用例模版的复制也有在规划中的，等排期哈。
