### ISSUE TITLE
[BUG]使用jira缺陷模板提交bug时，如果jira中的自定义字段有一对多的情况，保存时系统会报错

### ISSUE THREAD

**Issue by zhangshihao930112** [metersphere/metersphere#16711]
### MeterSphere 版本

 v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

使用jira缺陷模板提交bug时，如果jira中的自定义字段有一对多的情况，保存时系统会报错

### 重现步骤

1.编辑项目时，缺陷模板勾选使用jira缺陷模板
2.提交bug，保存时系统异常

### 期待的正确结果

可以正常将bug提交到jira系统中

### 附加信息

![1659683545392](https://user-images.githubusercontent.com/85295604/183024564-d72d0892-0168-4b26-a2fd-bb36c53461cf.jpg)

**Comment by xulinde** [comment]
使用自定义字段，字段类型“多选成员”，未复现该问题。请详细描述用的哪种类型的字段？
