### ISSUE TITLE
环境配置，全局前后置脚本没有分模块处理

### ISSUE THREAD

**Issue by ousinka** [metersphere/metersphere#16719]
### MeterSphere 版本

1.20.x

### 请描述您的需求或者改进建议

目前环境配置中，可以设置全局前置或后置脚本，但粒度比较粗，不能单独处理或排除个别接口，希望可以参考服务器，进行分模块处理。

### 请描述你建议的实现方案

可以参考服务器，进行分模块处理。

### 附加信息

无

**Comment by luty2018** [comment]
这是个很好的建议，我们会尽快排期！
