### ISSUE TITLE
[FEATURE]希望可以在UI测试中新增证书相关功能

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#16714]
### MeterSphere 版本

1.20.11-LTS

### 请描述您的需求或者改进建议

因企业用户使用UI测试的时候，打开页面需要证书，否则无法进行下去：

1、新增忽略证书的功能；

2、提供方案，可以在selenium或者MS里面配置证书的地方；

3、其他临时解决方案亦可。

**Comment by Hyyfit** [comment]
这个功能可以实现的，我们后续会支持
