### ISSUE TITLE
[BUG]测试报告中的接口用例统计分析点击名称没有跳转到对应的场景用例页面

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#16713]
### MeterSphere 版本

版本:   v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

测试报告中的接口用例统计分析点击名称没有跳转到对应的场景用例页面，之前点击之后是可以直接跳转到对应的场景用例详情页的

### 重现步骤

1、点击测试跟踪、报告
2、查看测试报告
3、在接口用例统计分析，选择一条用例，在右侧点击对应的用例标题

### 期待的正确结果

跳转到对应的那一条用例

### 附加信息

![image](https://user-images.githubusercontent.com/26948634/183043223-71799119-e7b9-40ea-abfb-3d375a55f9d5.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
