### ISSUE TITLE
[QUESTION]跑所有jmeter脚本报这个错Non HTTP response code: org.apache.http.client.ClientProtocolException

### ISSUE THREAD

**Issue by xiecq1** [metersphere/metersphere#16725]
### 请描述您的问题

matersphere上面跑所有jmeter脚本报这个错Non HTTP response code: org.apache.http.client.ClientProtocolException
，在脚本里客户端实现选择java上传再执行就不报错了 ，怎么解决

**Comment by luty2018** [comment]
请问当前使用的MeterSphere是什么版本？可能需要你这边提供一下测试脚本给我们看看。

**Comment by kevinboxz** [comment]
@xiecq1 我也遇到类似问题，请问在你的场景下，是如何解决的？
