### ISSUE TITLE
[FEATURE]脑图界面-双击空白处定位到根节点功能屏蔽

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#16729]
### MeterSphere 版本

v1.20.11-lts

### 请描述您的需求或者改进建议

双击节点有时候会双击到空白处，就会定位到根节点，脑图内容较多时找会原来的位置需要浪费很多时间

### 请描述你建议的实现方案

双击脑图空白处无任何效果

**Comment by Hyyfit** [comment]
设计如此，是为了实现内容多的时候，方便快速定位到根节点。
如果是为了方便查看，脑图左侧模块树有筛选的功能，脑图内容比较多，详细内容可以通过模块的方式查看，另外，我们还有缩略图，也可以实现快速的定位。
![image](https://user-images.githubusercontent.com/95834771/184126810-54c20c5b-3c1f-4408-b6c3-102f74a4ce36.png)
