### ISSUE TITLE
支持全局自定义脚本

### ISSUE THREAD

**Issue by ousinka** [metersphere/metersphere#16720]
### MeterSphere 版本

1.20.x

### 请描述您的需求或者改进建议

目前自定义代码片段，只能在一个项目中共享，如果要在多个项目中跨项目使用，需要重新编写，希望可以增加全局脚本属性。方便多个项目共享使用。

### 请描述你建议的实现方案

在自定义脚本中，增加全局脚本属性。或增加全局脚本模块。

**Comment by luty2018** [comment]
这是个非常好的建议，我们会尽快排期！
