### ISSUE TITLE
[BUG]【用例评审】脑图模式下，未选中用例时不应该能操作”通过“和”不通过“

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#16721]
### 联系方式

交流群45，付世鹏，andy.fu@31huiyi.com

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

是

### 问题描述

用例评审脑图模式下，未选中用例时点击”通过“和”不通过“后，全部用例都被更改评审结果了。

### 重现步骤

1、进入用例评审的脑图模式。
2、不去选中用例时，点击“通过”或“不通过”的操作图标

### 期待的正确结果

未选中用例时，不可以点击“通过”和“不通过”的操作图标。

### 附加信息

![image](https://user-images.githubusercontent.com/110213256/183325763-498754b9-e1b7-49f3-8ec6-02d952d6a685.png)

**Comment by xulinde** [comment]
您是选中的模块吗？选中模块，是可以点击“通过”和“不通过”的，相当于是批量编辑用例状态
