### ISSUE TITLE
[BUG]缺陷从MS上提交，然后缺陷同步到jira后，在jira上进行编辑后又同步到MS上，在ms上点编辑进入编辑页面，缺陷信息未能正常回显

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#16726]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.8

### 使用外置数据库

否

### 问题描述

缺陷从MS上提交，然后缺陷同步到jira后，在jira上进行编辑后又同步到MS上，在ms缺陷管理点编辑进入编辑页面，缺陷信息未能正常回显。

### 重现步骤

1、缺陷从MS上提交，然后缺陷同步到jira后
2、在jira上进行编辑后又同步到MS上
3、在ms上点编辑进入编辑页面，缺陷信息未能正常回显
![0f7ed62e4c7de334210218b5f5276c7](https://user-images.githubusercontent.com/83771182/183330990-d3e53903-2770-42d6-8559-121b87f6c2fb.jpg)
![86705d0799a52efce7fe34affc3e17e](https://user-images.githubusercontent.com/83771182/183331002-937860fb-6d79-4b89-b313-46d246db0339.jpg)

### 期待的正确结果

缺陷信息正常回显

### 相关日志输出

```shell
无
```

**Comment by xulinde** [comment]
v1.20.12已修复～

**Comment by yaoyi111** [comment]
升级1.20.12后点击同步缺陷按钮后，问题依旧，不显示后面红框中的部分。
<img width="707" alt="0cb63732ec15db860f47c34031d0c49" src="https://user-images.githubusercontent.com/83771182/186886810-152aaf1a-13be-4784-bc1d-f4c741105224.png">
