### ISSUE TITLE
[BUG] json文档结构校验导入，修改/更新导入json内容后，点击确认，未重新刷新json结构字段

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16728]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

①json文档结构校验导入，修改/更新导入json内容后，不会重新刷新json结构字段
②删除json字段，重新点击导入json框的确认，也不会重新生成json结构字段

### 重现步骤

![企业微信截图_16599304851751](https://user-images.githubusercontent.com/103925124/183335132-b6728019-fb9d-4e87-868a-5cfaf15fc82c.png)
![企业微信截图_16599305184741](https://user-images.githubusercontent.com/103925124/183335211-0d979896-d57a-4611-9f7d-520cb6bec781.png)
首次导入后可正常刷新字段
![企业微信截图_16599305353422](https://user-images.githubusercontent.com/103925124/183335238-adea0cd7-8a29-4a89-a874-754bd4e3b226.png)

修改导入json内容,后点击确认
![企业微信截图_16599306091608](https://user-images.githubusercontent.com/103925124/183335354-9c1c63d7-f563-4a84-9b04-e26261644c67.png)
校验字段无更新
![企业微信截图_16599306589464](https://user-images.githubusercontent.com/103925124/183335444-0e653b14-cb44-4b92-9fef-2baab595a270.png)

### 期待的正确结果

①json文档结构校验导入，修改/更新导入json内容后，点击确认会重新刷新json结构字段
②删除json字段，重新点击导入json框的确认，可以重新生成json结构字段

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20 和 2.0 版本都已修复，请等待版本发布后验证
