### ISSUE TITLE
[BUG]【用例评审】列表模式下，选择所有用例批量编辑评审结果失败，页面报错提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#16722]
### 联系方式

交流群45，付世鹏，andy.fu@31huiyi.com

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

是

### 问题描述

用例评审列表评审模式下，选择所有用例批量编辑评审结果失败，页面报错提示“SQL error happened, please check logs.”

### 重现步骤

1、进入用例评审的列表评审页。
2、列表按ID排序。
3、选择所有数据。
4、批量编辑“评审结果”。

### 期待的正确结果

用例成功更新评审结果。

### 附加信息

![image](https://user-images.githubusercontent.com/110213256/183326598-00d6bff5-06fe-4e18-8953-1668d5167f11.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
