### ISSUE TITLE
[BUG]  场景中条件控制器下接口，添加断言-json文档结构校验字段，执行后无断言，保存后重新编辑，此字段未空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16734]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

场景中条件控制器下接口，添加断言-json文档结构校验字段，执行后无断言，保存后重新编辑，此字段未空

### 重现步骤

![企业微信截图_1659939234304](https://user-images.githubusercontent.com/103925124/183351345-0e8af362-6e59-4764-b1ab-3563ecf5eb44.png)
添加条件控制器，后添加json文档结构校验字段
![1659939400(1)](https://user-images.githubusercontent.com/103925124/183351693-7807d01d-14ad-4f31-b049-560de165f045.png)
执行，无断言
![1659939682](https://user-images.githubusercontent.com/103925124/183352409-0b72f8aa-4f19-4140-b6a3-0ebdb036213c.png)
保存后重新查看json文档结构校验字段
![1659939708(1)](https://user-images.githubusercontent.com/103925124/183352574-d116097b-0f75-418b-bc21-a82b45d664b9.png)

### 期待的正确结果

场景中条件控制器下接口，添加断言-json文档结构校验字段，执行后有断言，保存后重新编辑，此字段可正常展示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20 和 2.0 版本都已修复，请等待版本发布后验证
不过需要把之前添加的没生效的文档结构断言删掉重新添加
