### ISSUE TITLE
[BUG]测试用例编写时顺序和关联到测试计划里看到的用例顺序不一致

### ISSUE THREAD

**Issue by lvwenyan1988** [metersphere/metersphere#16736]
### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

测试用例编写时顺序和关联到测试计划里看到的用例顺序不一致

### 重现步骤

1、功能用例里通过脑图添加用例
2、测试计划里关联功能用例
3、测试计划里查看脑图用例，用例的顺序与功能用例里不一致
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/52227960/183357631-54cfd18d-5e85-4026-aae3-3f5c7e4dde89.png">

### 期待的正确结果

测试计划里的用例顺序查看时与之前写的一致，不会打乱。

**Comment by xulinde** [comment]
感谢反馈，后面版本可以做下优化～

**Comment by xulinde** [comment]
目前是按照加到测试计划里的时间排序的，也可以拖拽排序
