### ISSUE TITLE
[FEATURE]自定义字段文本格式在页面显示太小，希望可以调整文本框大小

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16733]
### MeterSphere 版本

v2.0

### 请描述您的需求或者改进建议

[FEATURE]自定义字段文本格式在页面显示太小，当输入文字较多时，只能看两行，希望可以调整文本框大小，这样查看更方便一点
![企业微信截图_16599372227861](https://user-images.githubusercontent.com/75236887/183349644-717be091-6a3a-4227-83f5-4d66281483cc.png)

**Comment by Hyyfit** [comment]
这里已经在规划了，等排期哈～～。
