### ISSUE TITLE
[FEATURE]  测试跟踪首页 遗留缺陷统计 加说明计算规则

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16737]
### MeterSphere 版本

1.20.11.lts

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/103925124/183357817-8dca49d3-a67a-420a-b1c9-9c9fba73011c.png)

### 请描述你建议的实现方案

加计算规则说明

**Comment by luty2018** [comment]
遗留缺陷统计的是未关闭的测试计划中产生的状态为未关闭的缺陷数之和，我们也在页面上加一下统计说明哈。
