### ISSUE TITLE
[BUG] 【UI测试】UI自动化场景-复制-新复制的场景无创建人信息

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#16732]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

点击复制，新复制的场景无创建人信息

### 重现步骤

1.进入UI测试-UI自动化页面
2.点击复制按钮，复制已有场景
3.点击确定

### 附加信息

1.报错信息
![image](https://user-images.githubusercontent.com/45531073/183347993-310ef63f-7028-46d2-8f9e-122db11ee990.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是必现的吗？或者不是直接点复制？
![image](https://user-images.githubusercontent.com/73461316/183402418-b9a82001-6a4d-4120-8502-28ef142b91cb.png)

**Comment by zyyfit** [comment]
复现步骤：使用跟创建人不同的账号复制

**Comment by wudamyw** [comment]
抓包返回为空，实际好像是有的，在测试报告结果也可以看到。   

   "description":null,
                "useUrl":null,
                "environmentJson":null,
                "projectName":"CARGOWARE",
                "userName":null,
                "creatorName":null,
                "principalName":"chunhuaqiao",
                "tagNames":null,
                "deleteUser":null,

**Comment by zyyfit** [comment]
2.0版本已修复，请等待2.0新版本发布后验证
