### ISSUE TITLE
[BUG]用例的自定义字段不能导出

### ISSUE THREAD

**Issue by yujie2011** [metersphere/metersphere#16739]
### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

用例的自定义字段不能导出
![企业微信截图_16599424616419](https://user-images.githubusercontent.com/75236887/183367279-407874bb-7c6f-4d1f-89d3-4d1715c6e827.png)

### 重现步骤

默认模板加入自定义字段，类型有文本、多选框、单选框等，写了几个case后，系统从1.20.10升级到2.0.0，发现导出的excel里面自定义字段和用例步骤结果为空，再升级到2.0.1，发现导出的excel里面自定义字段还是不显示，步骤和结果显示了

**Comment by xulinde** [comment]
v2.1会支持

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
