### ISSUE TITLE
[BUG]多个场景， 列表勾选多选框， 全部勾选， --批量执行 串行， 任务中心点击全部停止，实际并没有停止。

### ISSUE THREAD

**Issue by chuwenyuan** [metersphere/metersphere#16738]
### 联系方式

530437008@qq.com

### MeterSphere 版本

 v1.20.8-lts-ba947709

### 使用外置数据库

否

### 问题描述

1.接口自动化中， 选中多个场景， 批量执行， 选择串行
2.任务中心点击【全部停止】
 3.实际接口依然在调用执行
Stopped状态会变成Eroor后才停止

### 重现步骤

多个场景， 列表勾选多选框， 全部勾选， --批量执行  串行， 任务中心点击全部停止，实际并没有停止。

### 期待的正确结果

批量执行 点击全部停止后， 场景可停止运行

**Comment by zyyfit** [comment]
您好，没有复现这个问题，
没有停止是指一个都没停止吗？任务中心是每10s刷新一次的，点击停止时看到的未执行场景有可能有的已经在执行中了，然后执行中的场景是会执行完成的，没执行的场景会停止
![image](https://user-images.githubusercontent.com/73461316/183404519-63ef908a-243b-413c-a378-8ed86d6224d7.png)
