### ISSUE TITLE
[BUG]官网https://metersphere.io/docs/user_manual/api_test/home/页面不停地闪

### ISSUE THREAD

**Issue by AimeeLee23** [metersphere/metersphere#1673]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  机型：MacBook Pro (16-inch, 2019)，操作系统：10.15.7 (19H114)，浏览器：safari版本14.0.3；
2. 使用访问`https://metersphere.io/docs/user_manual/api_test/home/`页面；

**期待的正确结果**
页面正常显示

**截图**

https://user-images.githubusercontent.com/28869268/111738340-24f1fd00-88bc-11eb-827f-9384676b0545.mp4

**Comment by xulinde** [comment]
我用safari是正常的，您这边是一直这样吗
