### ISSUE TITLE
[BUG]API 导出 Swagger 格式的接口，再导入到模块，报“数据解析” 错误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#16742]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.11-lts

### 使用外置数据库

否

### 问题描述

API 导出 Swagger 格式的接口，再导入到模块，报“数据解析” 错误

### 重现步骤

1.到API列表，选择部分接口，导出 Swagger 格式接口。
![image](https://user-images.githubusercontent.com/30038088/183398758-30376f7b-ee0f-4367-8a48-f925e419e8a1.png)
2.选择模块，导入，报 “数据解析” 错误
![image](https://user-images.githubusercontent.com/30038088/183398918-c74c67e0-68b1-4c36-a662-48bef6d2cfb2.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.20 版本 和 2.1 版本都已修复，请等待版本发布后验证
