### ISSUE TITLE
[BUG] 新增测试用例时，发现另一个用例的评审结果也会展示在旁边

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#1674]
**MeterSphere 版本**
1.7.2

**Bug 描述**
如题，新增另一个测试用例时，发现老用例的评审结果会展示在旁边

**Bug 重现步骤**
1.  编辑某个旧用例A，该用例有一些评审评论，编辑完成后关闭
2.  点击【新增用例】，发现之前A用例的评审评论也展示在了旁边

**期待的正确结果**
新增用例应该不展示其他用例的评审评论

**截图**
![bug-评审评论](https://user-images.githubusercontent.com/11419548/111740976-a9467f00-88c0-11eb-84d3-32ad0a5a1ab9.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本会修复

**Comment by xulinde** [comment]
v1.8，新版本新建用例时无评论部分
