### ISSUE TITLE
[FEATURE]自动化场景用例支持反向查询关联到了哪条功能测试用例

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16750]
### MeterSphere 版本

2.0.1

### 请描述您的需求或者改进建议

当前只能正向查看功能用例关联到了哪条自动化场景，希望自动化场景能够反向去查找到关联的功能用例，因为这样当自动化场景出错后能够快速去找到功能用例，可以去确认一些细节问题。用例多了以后不一定记得自动化场景对应的是哪条功能，这个反查还是很需要的

**Comment by luty2018** [comment]
自动化步骤的描述不能让用户知道是什么功能吗？

**Comment by wszbc** [comment]
> 自动化步骤的描述不能让用户知道是什么功能吗？

主要是关联到功能用例里面有功能中描述的细节，不然那不是要把整个功能用例的内容又写到自动化的描述中？而且没法知道我哪些自动化已经被关联过了，

**Comment by luty2018** [comment]
> > 自动化步骤的描述不能让用户知道是什么功能吗？
> 
> 主要是关联到功能用例里面有功能中描述的细节，不然那不是要把整个功能用例的内容又写到自动化的描述中？而且没法知道我哪些自动化已经被关联过了，我这边功能用例是分模块的，自动化可能横跨几个模块，那么就有可能几个功能用例都关联的相同的自动化用例，如果能反向查找会更方便操作

了解了，我们尽快规划
