### ISSUE TITLE
[QUESTION]请问接口在上传文件时，如果需要文件内容的md5应该怎么办？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#16759]
### 请描述您的问题

采用multipart/form-data进行文件上传时，有时需要请求头填入文件内容的md5

Content-Md5 | 内容md5

但是文件一般是由本地测试机点击接口的请求体tag -> form-data -> 选择film -> 选择本地文件 上传的，而服务器和测试机并非一台的情况下，前置脚本只能获取到服务机的文件的信息，因此测试机上传的文件的md5如何获得？

**Comment by zhangdahai112** [comment]
你可以在上传的时候把文件的md5在你自己的电脑上面算出来再添加到 header 里面

**Comment by Faerie1999** [comment]
？

**Comment by Faerie1999** [comment]
> 

那这样的话，每次只能上传同一个文件，即覆盖上传，请问没有其他方法了吗？

**Comment by zhangdahai112** [comment]
额，我有点蒙了，不知道你们的系统怎么设计的，能否加我们群里的支持小哥详细了解一下？
