### ISSUE TITLE
[BUG]接口自动化请求应用环境通用配置后出现多余的“http:/”

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#16752]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.11-LTS

### 使用外置数据库

是

### 问题描述

1、版本由原来的1.20.5-LTS升级到1.20.11-LTS版本

2、接口自动化下场景内采用环境通用配置的变量作为请求地址

3、1.20.5-LTS是可以正常请求，1.20.11-LTS之后就会多出来http:/

### 重现步骤

1、接口自动化下场景内采用环境通用配置的变量作为请求地址

2、请求发出后，查看请求内容就会多出来http:/

### 附加信息

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/32027713/183553359-7a859d77-5a8e-4bd9-be62-5c6505337f5f.png">

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/32027713/183553464-0940cc3b-ad0a-4e49-a463-f3282bc7f85b.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.12-lts中已解决该问题。
