### ISSUE TITLE
[BUG]helm 模板，部署 2.0 报 Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#16763]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

![b9b3174d69232c1ddc7aff5e9e5df6f](https://user-images.githubusercontent.com/30038088/183578463-cc36fbef-7e6d-4373-bb5c-360c4c225274.png)

### 重现步骤

helm 模板，部署 2.0 报 Public Key Retrieval is not allowed

原因：
helm 模板里 数据库连接参数 缺少 allowPublicKeyRetrieval=true 参数

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #16697
