### ISSUE TITLE
[BUG]  导入包含csv的场景，点击运行，提示csv文件不存在，csv下载后无内容

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16765]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts

### 使用外置数据库

否

### 问题描述

导入包含csv的场景，点击运行，提示csv文件不存在，csv下载后无内容

### 重现步骤

导出带有csv文件的场景
![1660028848(1)](https://user-images.githubusercontent.com/103925124/183586238-9cd48f9b-8821-49b4-b75f-a95d6040b901.png)
更多操作导入到另外一套系统
![企业微信截图_16600288991043](https://user-images.githubusercontent.com/103925124/183586416-6e06d17b-cb2e-43d3-ab39-0212fb05fbb2.png)
运行时报错
![企业微信截图_16600290383270](https://user-images.githubusercontent.com/103925124/183586836-c43aeb25-b5a2-431b-bc46-0bcdef6c345a.png)
点击下载后此文件内容为空
![企业微信截图_16600290631802](https://user-images.githubusercontent.com/103925124/183587089-dc8ea21b-5a8e-438a-a119-26eb6b958046.png)

### 期待的正确结果
运行时不报错，点击下载后此文件内容正常
_No response_

**Comment by xulinde** [comment]
csv需要重新上传
