### ISSUE TITLE
[FEATURE]功能用例自定义字段和自定义模板缺少基础功能

### ISSUE THREAD

**Issue by 1ToKiSa** [metersphere/metersphere#16767]
### MeterSphere 版本

2.0.1

### 请描述您的需求或者改进建议

前提：由于被测的系统含有30+个模块，所以使用判定表用例，如用例“新增输入异常字符”，我们会自定义模板，加上自定义字段“条件、动作、通用结果”，然后在用例步骤写上所有的模块名称，实际执行时，在每个模块的期望写上“通用结果”或“不符合条件无需测试”，以此来减少用例编写工作量，防止每个模块都写一遍相同的用例。问题如下，
1、功能测试，自定义用例模板，自定义字段，现象：由于新加入了自定义字段“条件、动作、通用结果”，用例编写时，顺序、大小、突出显示都没有，需要时刻提醒员工注意，但还是会有员工看错；
2、由于“条件、动作”多种多样，会导致文本量和行数过多，文本框默认大小太小，导致执行用例时，测试人员每个都拉开，每个都调整，十分繁琐；
3、由于新的自定义字段，且含有多次换行，导致用例导入到另一个项目时，数据丢失。

### 请描述你建议的实现方案

对应以上问题编号
1、期望在自定义字段时和自定义模板时，加上文本框大小、顺序、高亮的选项设置；
2、期望没有定义大小的文本框在文本过多时，能适当加长；
3、建议导入时，加上模板格式校验，并给出对应提示，或者校验到模板不匹配直接自动新建模板再执行导入
4、由3问题引申，期望一个项目能同时设置多个模板，配合使用

### 附加信息

![3adb2cb3d33c5c81d56b07a5b99e5a8](https://user-images.githubusercontent.com/110890934/183590659-3898a874-314d-42b6-b1ab-b690d9827708.jpg)
![d687cc60c26a863c8f31cff6b75150a](https://user-images.githubusercontent.com/110890934/183590770-1864958d-a1ed-4908-8493-4e332f05abe7.jpg)

**Comment by Hyyfit** [comment]
第1、2个问题，后续会考虑优化，可以做到有明显的提示，这个还需要再规划一下。
第3、4的问题，不太清楚你具体的应用场景，你可以加一下我的微信，再详细沟通一下
<img width="316" alt="image" src="https://user-images.githubusercontent.com/95834771/184129081-ebf5ba78-b323-4cd2-b4e3-28a84a2d6aaf.png">
