### ISSUE TITLE
测试计划里面的测试报告与测试计划目录下的测试报告结果不一致[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1676]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.7.3-2b9713b1
**Bug 描述**
简要描述您碰到的问题
测试计划里面的测试报告与测试计划目录下的测试报告结果不一致
**Bug 重现步骤**
1.  进入测试计划，点击某个进入测试计划，执行功能用例与接口用例
2. 返回测试计划目录，点击报告
3. 点击进入刚执行的测试计划，查看报告统计
4. 对比两者之间的结果是否一致

**期待的正确结果**
正确情况下应该是什么样的？
结果一致
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/80814232/111762416-f2f09300-88db-11eb-8ec4-72cf16dd4d9d.png)
![image](https://user-images.githubusercontent.com/80814232/111762437-fa17a100-88db-11eb-9d26-b93719f6ab5d.png)
![image](https://user-images.githubusercontent.com/80814232/111762464-00a61880-88dc-11eb-9e50-fc8083402ed9.png)

**Comment by guoxin92** [comment]
测试计划目录那边的报告缺少了接口部分的结果

**Comment by xulinde** [comment]
没复现呢，是不是没保存测试报告

**Comment by guoxin92** [comment]
保存了

**Comment by guoxin92** [comment]
我现在这边还可以复现

**Comment by xulinde** [comment]
建议您升级到v1.8再验证下

**Comment by zyyfit** [comment]
这个问题已在v1.8.0版本修复了
