### ISSUE TITLE
[FEATURE] 场景内多接口参数去冗余定义，可重新引用已定义参数，非重新定义

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16776]
### MeterSphere 版本

1.20.11.lts

### 请描述您的需求或者改进建议

需求背景:复杂场景，且参数N个且有交叉
需求出现：第一个接口20个参数，第二个接口入参要用到18个。可以不去把第一个接口的18个参数都去定义一遍

### 请描述你建议的实现方案

比如在一个场景中下个接口要调用之前步骤的入参，调用时可通过步骤序号+字段来定位调用，或者是ID+字段的方式来调用调用方式如:@parameter("001","name")
调用例子1：
接口4 age = @parameter("003","age")
接口7 age = @parameter("001","age")
接口9 name = @parameter("002","name")
调用例子2：
十多个接口，参数中一共有 三个name

定义后的引用例如：
接口4 age = @parameter("003","age")
接口7 age = @parameter("001","age")
接口9 name = @parameter("002","name")

### 附加信息
使用场景变量定义/后置脚本提取接口参数后引用可达到取值需求，但从业务层面如可直接引用，会更清晰一些~
_No response_

**Comment by luty2018** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/36292514/184127215-d1d77642-fc59-4ca1-a376-b237d159c3d7.png">
在需要引用前置提取的参数点击小铅笔可以在下面菜单中快捷引用前置请求中的提取参数，请问这个功能是否能覆盖你的场景呢
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/36292514/184127141-76b8b760-cd46-4287-85c2-2fe1811ca3ff.png">
