### ISSUE TITLE
[FEATURE] 建议文件管理和资源文件支持dll、so格式文件上传，用于解决依赖dll和so方法调用问题

### ISSUE THREAD

**Issue by cui369680775** [metersphere/metersphere#16782]
### MeterSphere 版本

2.0.0

### 请描述您的需求或者改进建议

建议文件管理和资源文件支持dll、so格式文件上传，用于解决依赖dll和so方法调用问题

**Comment by luty2018** [comment]
已规划在2.1版本，上传文件不限制文件类型。
