### ISSUE TITLE
[BUG]测试计划，定时任务，邮件模板，${executionTimes}这个变量没取到值

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#16783]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud

### 使用外置数据库

否

### 问题描述

测试计划，定时任务，邮件模板，${executionTimes}这个变量没取到值

### 重现步骤

1. 登录到MS
2. 创建或者选择一个测试计划
3. 创建定时任务，选择邮件通知，
4. 配置邮件内容，选择${executionTimes}
5. 定时任务执行，查看邮件通知，${executionTimes}取值为0

**Comment by youliyuan-fit2cloud** [comment]
这个字段已经没有了，模块里面没有同步更新。
