### ISSUE TITLE
[FEATURE]断言规则，新版本后无法编辑断言名称

### ISSUE THREAD

**Issue by 12abxs1** [metersphere/metersphere#16784]
### MeterSphere 版本

v2.0.1

### 请描述您的需求或者改进建议

断言规则，新版本后无法编辑断言名称。当一个请求下有多个断言时，不便于区分其作用

### 请描述你建议的实现方案

添加断言名称的编辑入口，一个断言对一个名称

**Comment by luty2018** [comment]
非常理解你说的场景，这里也解释下为什么我们会这么处理，主要是考虑到之前的展现形式需要不停的展开折叠，比较影响页面加载，我们可以在添加断言参数的地方增加一个备注是否能满足你的场景呢
