### ISSUE TITLE
[BUG]测试计划-功能用例排序不正确

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#16785]
### MeterSphere 版本

v2.0.0-9e3627ae

### 使用外置数据库

否

### 问题描述

测试计划-功能测试用例根据ID排序未排序成功

### 重现步骤

1、打开测试计划-功能测试用例
2、点击 ID 升序倒序未按照正确顺序排列
<img width="738" alt="image" src="https://user-images.githubusercontent.com/89765365/183800540-29d90f44-721d-4245-b304-eb359da83d41.png">

### 期待的正确结果

按照正确顺序排列

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
