### ISSUE TITLE
[BUG] 功能用例里，更多操作里的新建用例报错

### ISSUE THREAD

**Issue by cui369680775** [metersphere/metersphere#16793]
### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

功能用例里，更多操作里的新建用例报错

![image](https://user-images.githubusercontent.com/12082798/183830420-faf2d5f1-dd12-4789-b901-f5f8d1ffd1e6.png)

### 重现步骤

1、打开测试跟踪->功能用例->模块搜索里的 更多操作 项
2、新建测试用例，输入内容，点确认提示错误

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，在v2.0.1中已修复该问题，升级一下吧。
