### ISSUE TITLE
[BUG]场景中提取响应体中多个id为数组，提取成功后，打印数组不成功，导致foreach不成功

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16799]
### 联系方式

18311441708

### MeterSphere 版本

1.20.11.lts/v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

场景中提取响应体中多个id为数组，提取成功后，打印数组不成功，导致foreach不成功

### 重现步骤

接口响应体内容为：提取下图中多个id为数组
![企业微信截图_16601122098862](https://user-images.githubusercontent.com/103925124/183836799-edf6426a-f14c-45fe-a54c-b97495b53e3e.png)
下图为提取成功
![企业微信截图_16601152945766](https://user-images.githubusercontent.com/103925124/183837383-0b3184ae-9708-40c6-9722-d5188dadbfc9.png)
下图为打印数组
![企业微信截图_16601154268970](https://user-images.githubusercontent.com/103925124/183837730-fa5c8494-7ba0-43d3-a5de-b9d4a11c4727.png)

### 期待的正确结果

![image](https://user-images.githubusercontent.com/103925124/183837826-16196521-4a60-4528-b8c5-177442c12c3f.png)

**Comment by zyyfit** [comment]
没有复现，你logl里引用的时候跟提取的时候是一起运行的吗？可以上传一下复现场景
![image](https://user-images.githubusercontent.com/73461316/183885451-4a02e7f5-62f7-481c-a011-7ed8cf1d66d0.png)

**Comment by Ycr123888** [comment]
非问题
