### ISSUE TITLE
[BUG] 功能用例导出xmind 缺少前提和操作步骤

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16800]
### 联系方式

18311441708

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

功能用例导出xmind 缺少前提和操作步骤

### 重现步骤

选择用例后导出为xmind文件
![企业微信截图_1660117142695](https://user-images.githubusercontent.com/103925124/183843169-8e12c09c-1b73-45a6-803e-e698d6ac6972.png)
此用例下有操作步骤和前提
![企业微信截图_16601172049577](https://user-images.githubusercontent.com/103925124/183843367-62ff0408-0dab-4459-a4e3-f790433a6227.png)
查看xmind文件无操作步骤和前提
![企业微信截图_16601172536199](https://user-images.githubusercontent.com/103925124/183843505-a500eca2-e1f9-4fa8-9c4d-07d749f7ebd3.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
