### ISSUE TITLE
[BUG]接口定义中query参数批量添加，希望过滤掉\r

### ISSUE THREAD

**Issue by xianwq** [metersphere/metersphere#1680]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3

**Bug 描述**
简要描述您碰到的问题
我在notepad++中编辑好参数后，复制到批量编辑框中后保存，发送请求后会带着\r字符，查看数据库发现入库的时候就存在
**Bug 重现步骤**
第一步：在notepad++中编辑好参数
第二步：复制到批量编辑框中
![image](https://user-images.githubusercontent.com/45792060/111777334-1fada600-88ee-11eb-8b36-a2e24bc1707d.png)
第三步：保存后，数据库的数据截图如下：
![image](https://user-images.githubusercontent.com/45792060/111777485-51bf0800-88ee-11eb-9f4c-cc32c565e7d7.png)

**期待的正确结果**
正确情况下应该是什么样的？
希望能过滤掉\r字符

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们复现下在反馈

**Comment by xulinde** [comment]
您好，这种的我们没法直接处理，您可以粘到txt
