### ISSUE TITLE
[BUG]性能测试webSocket请求，kafka字节字数超出最大值

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16811]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

接口定义--接口自动化，使用webSocket请求，执行成功，

但是接口自动化转性能测试，也加载webSocket插件，webSocket请求无反应，查看kafka日志，docker-composer-kafka.yml配置：KAFKA_CFG_MESSAGE_MAX_BYTES超出，设置了几次参数都不行，本地为复现。

### 重现步骤

接口自动化：
![image](https://user-images.githubusercontent.com/15188833/183878491-4e5dc135-98c3-4056-990c-4a6064fc686a.png)

性能测试文件加载：
![image](https://user-images.githubusercontent.com/15188833/183879890-696a6445-92db-4798-8bb8-7a39a8003e9c.png)

服务器上kafka配置：
![image](https://user-images.githubusercontent.com/15188833/183878573-3d74780c-cba1-4ee7-952f-0e5e4beed27f.png)

kafka异常提示：
![image](https://user-images.githubusercontent.com/15188833/183878648-defe2df5-c0c5-4ee4-a1b0-1334b3b6b9ce.png)

**Comment by liuruibin** [comment]
docker stop kafka
docker stop zookeeper
docker rm kafka
docker rm zookeeper
rm -rf /opt/metersphere/data/kafka/kafka
rm -rf /opt/metersphere/data/zookeeper/zookeeper
msctl reload

**Comment by startpjx** [comment]
按照上面方式执行，还是不行
![image](https://user-images.githubusercontent.com/15188833/184093042-4bcaae87-b9d8-4fac-a3d2-c88d1f23e5bb.png)

**Comment by youliyuan-fit2cloud** [comment]
感觉设置还是未生效。

**Comment by chenbingjie-98** [comment]
websocket插件是哪种？现在支持自己上传websocket插件了吗
