### ISSUE TITLE
[BUG] 通过postman的数据格式导入接口，导入模式为覆盖，报空指针异常

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16817]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

v1.20.11-lts  版本    
同样的数据格式，新增导入成功，再次导入选择的覆盖，导入失败。
<img width="731" alt="image" src="https://user-images.githubusercontent.com/33945037/183878805-ffb266de-4b7a-47b8-ba72-f37f8162e326.png">
报错
<img width="739" alt="image" src="https://user-images.githubusercontent.com/33945037/183878990-161eba0b-7825-4b3e-a5bb-4f06fb05ef3b.png">

看后台日志：
<img width="936" alt="image" src="https://user-images.githubusercontent.com/33945037/183879085-1a67cd91-cc1e-4c16-b5fb-1879b91f593e.png">

### 重现步骤

1. 先导入到MS当中
2. 再次导入，选择覆盖，报错。
3. 测试附件，可以复现。
[local-api-export.txt](https://github.com/metersphere/metersphere/files/9299254/local-api-export.txt)

**Comment by zyyfit** [comment]
没有复现呢，你们的环境能复现吗？
![image](https://user-images.githubusercontent.com/73461316/183886710-7bdae2f5-c894-4063-9f59-b761d8b5fc06.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20 和 2.0版本已修复，请等待版本发布后验证
