### ISSUE TITLE
[BUG]性能测试jmx文件，执行完性能测试，在项目设置--文件管理无法删除

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#16813]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.11

### 使用外置数据库

否

### 问题描述

在性能测试模块，执行一个性能测试场景，执行完，在项目设置--文件管理--上传新文件，无法进行删除。

### 重现步骤

项目设置--文件管理：
![image](https://user-images.githubusercontent.com/15188833/183880951-71331484-4655-421e-8f12-48d58aa84fa6.png)

性能测试执行完成：
![image](https://user-images.githubusercontent.com/15188833/183881066-737fae06-7a95-4e5b-9510-f49de1f3200f.png)

**Comment by youliyuan-fit2cloud** [comment]
这个设计如此，被性能测试用例使用的文件不能删除。
