### ISSUE TITLE
[BUG]前后置脚本，类型选择 python，写入代码，控制台出现ImportError错误

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#16818]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

前后置脚本，类型选择 python，写入代码，控制台出现ImportError错误，ImportError: cannot import name create_string_buffer in <script> at line number 6
![image](https://user-images.githubusercontent.com/104960608/184054619-15ee38be-0f23-4c07-8d79-f927ddab86d1.png)
![image](https://user-images.githubusercontent.com/104960608/184054663-18e430ce-3a55-4b09-8601-618f96919175.png)

同样的内容进入到 python2 中正常执行。
![image](https://user-images.githubusercontent.com/104960608/184054900-f587f51c-c230-4d56-9fed-2f3dd64764cf.png)

### 重现步骤

1.按照 https://metersphere.io/docs/tutorial/use_python/文档，创建虚拟环境
2.使用 pip install pycryptodome -i https://pypi.douban.com/simple/ 安装pycryptodome
3.在前置脚本中输入如下代码:
`
import sys
#映射路径
sys.path.append('/opt/metersphere/data/python/lib/python2.7/site-packages')
from Crypto.PublicKey import RSA
from Crypto import Random
from Crypto.Cipher import PKCS1_v1_5
import base64,json

def encrypt(plaintext, pub_key):
    cipher_pub = PKCS1_v1_5.new(RSA.importKey(pub_key))
    ciphertext = cipher_pub.encrypt(plaintext.encode("utf-8"))
    ciphertext_base64 = base64.b64encode(ciphertext)
    return ciphertext_base64
`
4.看到控制台会有ImportError: cannot import name create_string_buffer in <script> at line number 6报错情况
![image](https://user-images.githubusercontent.com/104960608/184056595-700cdba6-6e60-40b5-84e2-56d6727a3a5f.png)
5.来到ms服务器，输入 python 进入 python2.7 环境，将上面代码贴入 python 中，发现并不报错。
![image](https://user-images.githubusercontent.com/104960608/184056570-53cf4a3b-ac6d-4bb4-8dee-2a89ae57bc10.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，python的扩展包暂时不支持，需要自己尝试研究一下。
