### ISSUE TITLE
[BUG]测试计划中自动化场景定时任务结果报告数据丢失

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16825]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

部分接口执行记录为空，但看起来是有运行过

### 重现步骤

多个项目分别建立测试计划中的自动化，同一时间定时运行。

### 期待的正确结果

能够正常输出报告中的运行结果

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/184061989-2b93826f-a99b-403f-b968-a19aa12bb969.png)
![image](https://user-images.githubusercontent.com/40912823/184062065-ab6c7722-bf13-4026-abd9-ce91bc8e2c06.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先尝试复现一下

**Comment by zyyfit** [comment]
您好，没有复现这个问题，如果您那边还是不正常的话，可以在我们的企业微信交流群里询问一下工作人员
