### ISSUE TITLE
[BUG]swagger导入后响应无法解析

### ISSUE THREAD

**Issue by KOMKZ** [metersphere/metersphere#1682]
**MeterSphere 版本**
1.7.3

**Bug 描述**
swagger导入后响应无法解析

**Bug 重现步骤**
1、将文件导入到接口定义中 https://petstore.swagger.io/v2/swagger.json
2、查看相关接口的响应体的定义，发想关联的对象无法正确解析，为空，swagger-ui上是可以解析的。
3、看截图

**期待的正确结果**
应该能够显示

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，方便提供下您的swagger文件吗，我们复现下问题

**Comment by KOMKZ** [comment]
> 未复现该问题，方便提供下您的swagger文件吗，我们复现下问题

https://petstore.swagger.io/v2/swagger.json  这个就是说swagge文件
