### ISSUE TITLE
[FEATURE]  接口定义中，当打开很多接口的时候，希望有个全部关闭，或者关闭左侧或右侧的选项。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16822]
### MeterSphere 版本

v1.20.11-lts

### 请描述您的需求或者改进建议

1. 在接口定义中，当接口列表中有大量数据的情况下，打开很多接口，接口列表文字描述同行的后面会出现很多tab，这个时候想在切回接口列表就必须一点一点往前翻，希望可以加一个，右键当前tab，关闭当前页/关闭当前页左边/关闭当前页右边的选项。可以一键关闭。 
2. 每次关闭一个tab，就会刷新左侧的列表树，太过于频繁。

### 请描述你建议的实现方案

1. 在接口定义中，当接口列表中有大量数据的情况下，打开很多接口，接口列表文字描述同行的后面会出现很多tab，这个时候想在切回接口列表就必须一点一点往前翻，希望可以加一个，右键当前tab，关闭当前页/关闭当前页左边/关闭当前页右边的选项。可以一键关闭。 
如图：当打开很多的时候，会无限往后扩展。关闭的时候必须的一个一个关闭。
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/33945037/184061061-38e0273c-15c2-4179-a25f-a1cea38014fe.png">

3. 每次关闭一个tab，就会刷新左侧的列表树，太过于频繁。

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/184124399-4023b89a-6658-43f5-811a-af4bba9279d3.png)
点击+ 这里可以全部关闭

**Comment by Hyyfit** [comment]
感谢反馈，一键关闭的功能，待规划排期。
左侧刷新的问题，会考虑优化。
