### ISSUE TITLE
[BUG]项目设置模板管理-模板字段：用例等级，系统自带的等级不能修改删除

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#16821]
### MeterSphere 版本

v2.0.0-81da75b6

### 使用外置数据库

否

### 问题描述

项目设置模板管理-模板字段：用例等级，系统自带的等级不能修改删除

### 重现步骤

项目设置模板管理-模板字段：用例等级，系统自带的等级不能修改删除

### 期待的正确结果

系统自带的等级能修改删除

### 附加信息

![微信图片_20220811113022](https://user-images.githubusercontent.com/43202800/184060897-d15bb96c-ae72-4fd8-9749-d79b0a420c53.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。
