### ISSUE TITLE
[QUESTION]尝试自动化POST创建功能用例，遇到问题

### ISSUE THREAD

**Issue by GenjiCy** [metersphere/metersphere#16834]
### 请描述您的问题

尝试POST /test/case/add 去创建功能用例，返回http错误代码400、415。
限定的content-type似乎是multipart/form-data，不知道怎么去写这个body才能成功post，目前各种返回400代码，
![{352fc011-9c38-4850-9406-190dc65a0648}](https://user-images.githubusercontent.com/40905444/184092524-1208a403-3544-49bb-835a-7d9a2b1a60f4.png)
*
![{a91990b5-fdf0-4476-926f-7602990386cb}](https://user-images.githubusercontent.com/40905444/184092946-8b6e5823-35b2-4fbb-b031-de4b92c4c889.png)
**

**Comment by wan92hen** [comment]
你好，这个接口需要试用 multipart/form-data 方式传入 request、file 两个参数，其中 request 参数值为文档格式中的 json，file 参数值为需要上传的附件文件。
![image](https://user-images.githubusercontent.com/27671436/184126957-0d9856f0-26dd-4e5d-9879-a956c8c52eab.png)

**Comment by GenjiCy** [comment]
在页面端成功创建后，拿取上图中的负载数据明文，使用postman进行测试，得到错误400
![{e6e6ec9b-7cdd-4e64-9c30-73fa77420fad}](https://user-images.githubusercontent.com/40905444/184269696-1f5a6e7a-2d0a-4fb0-bfb9-0d713702677f.png)
![{77540ca1-227d-4c3c-8bd9-2628b8a36962}](https://user-images.githubusercontent.com/40905444/184269718-c7023014-8da4-48a0-bdee-5382f02e1221.png)

**Comment by wan92hen** [comment]
你好，根据截图来看使用了 file 参数但是没有选择文件，如果不需要上传文件的话，可以不填写 file 参数。

**Comment by GenjiCy** [comment]
> 你好，根据截图来看使用了 file 参数但是没有选择文件，如果不需要上传文件的话，可以不填写 file 参数。

勾选掉了file，还是400错误。
利用之前成功创建的信息，我去使用了/test/case/save接口，在以json格式存放request中信息的情况下，成功生成了同名的第二个功能用例。这里有两个问题：
1.save与add的差别在哪里
2.创建信息是全部需要填写吗？支持自动补全吗？

**Comment by AgAngle** [comment]
你好我这里测试了一下，这样写是可以成功的，可以检查下json串是不是格式不对，另外请求头不要加 Content-Type
![image](https://user-images.githubusercontent.com/41557596/184274609-14485887-09ea-473c-9120-ecaa50f9fd32.png)

**Comment by GenjiCy** [comment]
> 你好我这里测试了一下，这样写是可以成功的，可以检查下json串是不是格式不对，另外请求头不要加 Content-Type ![image](https://user-images.githubusercontent.com/41557596/184274609-14485887-09ea-473c-9120-ecaa50f9fd32.png)

postman成功post了，但是其自动生成的代码在python中并不能运行。
python的request库在遇到form-data格式时有一些模糊的地方，请问你们有相关的python代码示例吗
