### ISSUE TITLE
[BUG] 环境配置中，ip:port参数话，请求地址引用后，出现异常中括号

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16839]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

环境配置中，ip:port参数后，请求地址错误加中括号

### 重现步骤

环境通用配置如下
![image](https://user-images.githubusercontent.com/103925124/184099471-a6d2357d-149d-4922-9fae-bd74bd00727f.png)
HTTP配置如下
![image](https://user-images.githubusercontent.com/103925124/184099514-ddb7849f-1543-4afd-a66c-400e8ba90e0e.png)
打印ip无问题
![企业微信截图_16602085427540](https://user-images.githubusercontent.com/103925124/184099747-15f78842-3eb2-43ff-9653-a2ec90e6ef44.png)
请求地址加了[]
![image](https://user-images.githubusercontent.com/103925124/184099821-7e4af354-6a1b-460a-8d89-b0d8ae7023ab.png)

**Comment by zyyfit** [comment]
jmeter中也是这样的，暂时不支持
