### ISSUE TITLE
[BUG]自动化场景变量表格偶尔会出现偏移

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#16830]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

点击场景变量，整个表格会出现偏移现象

### 重现步骤

偶现，但可以反复点击打开，时不时就会出现偏移情况

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/184078208-dd3bb10e-acd1-40b8-9adc-620b345294ed.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #16735
