### ISSUE TITLE
[BUG]禅道信息填写正确时候，测试链接提示验证失败，后台报错Invalid mime type

### ISSUE THREAD

**Issue by ZHIGAOwang** [metersphere/metersphere#1683]
**MeterSphere 版本**
MeterSphere 版本：v1.7.3-2b9713b1
禅道版本：12.3.2

**Bug 描述**
禅道信息填写正确时候，测试链接提示验证失败，后台报错Invalid mime type

**Bug 重现步骤**
1.正常添加集成禅道信息
2.点击测试链接
3.提示验证失败

**截图**
![image](https://user-images.githubusercontent.com/33215154/111945866-68937380-8b15-11eb-8d0c-95295c2df5e2.png)
![image](https://user-images.githubusercontent.com/33215154/111945879-70531800-8b15-11eb-9b5f-c20499eb2bed.png)
![image](https://user-images.githubusercontent.com/33215154/111945913-84971500-8b15-11eb-8165-17b3063eaa76.png)

**Comment by xulinde** [comment]
地址类似
http://xxx/biz/
这样的吗

**Comment by ZHIGAOwang** [comment]
![image](https://user-images.githubusercontent.com/33215154/112112620-b92bcf00-8bf0-11eb-8a4c-69dd1e060fa1.png)
就算我的账号密码填错了也不至于500把

**Comment by ZHIGAOwang** [comment]
> 1.账号密码确认无误
> 2.地址格式正确，类似http://xxx/biz/
> 请确认下

**Comment by xulinde** [comment]
是否方便进企业微信对外群和研发同事进行沟通呢？
![image](https://user-images.githubusercontent.com/64065190/112450047-eca46000-8d8e-11eb-95bb-3111f460c2ae.png)
