### ISSUE TITLE
[FEATURE] [优化]使用外置redis服务，不能使用指定用户登录redis服务，希望脚本支持~

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16842]
### MeterSphere 版本

v1.20.11-lts

### 请描述您的需求或者改进建议

使用外置redis服务，不能使用指定用户登录redis服务，希望脚本支持~

### 请描述你建议的实现方案

增加命令里redis密码
![企业微信截图_16602116162614](https://user-images.githubusercontent.com/103925124/184108578-775c350e-d5e0-4cb9-8a92-a5292e7ed6d6.png)
增加密码参数值
![企业微信截图_16602116447202](https://user-images.githubusercontent.com/103925124/184108650-000a104b-6854-4e8b-b401-b4965127d06b.png)

内置的用default即可

**Comment by zhangdahai112** [comment]
redisson-spring-boot-starter 可以去查询这个的 spring 配置
