### ISSUE TITLE
[BUG]压测接口时报错

### ISSUE THREAD

**Issue by qiaowenjuan123456** [metersphere/metersphere#16854]
### MeterSphere 版本

2.0.0.1

### 使用外置数据库

是

### 问题描述

登录接口，50个线程，持续1分钟压测，metershpere后端log报错且性能测试报告出错
![Uploading lQLPJxaVXSAbmBTNBAbNB4CwucCrqjt5UewC9ciuCYBUAA_1920_1030.png…]()

### 重现步骤

![a30a0c3ac48e1e05c55d0e4b462d788](https://user-images.githubusercontent.com/110219188/184298134-966aa184-dfa3-468a-959f-c8ea34ff3d51.jpg)
![ab61fe2c5176613b9892aca06ad1d79](https://user-images.githubusercontent.com/110219188/184298152-39dd4d50-5fd3-4dbd-8d96-02acbe0b5f31.jpg)

**Comment by silvia-zhou123456** [comment]
您好，请问一下您的版本是v2.0.1版本还是 v2.0.0？
