### ISSUE TITLE
[FEATURE]自定义脚本可以支持python3吗？

### ISSUE THREAD

**Issue by DsJay** [metersphere/metersphere#16859]
### MeterSphere 版本

v1.20

### 请描述您的需求或者改进建议

python2确实够用，但是大家现在更习惯写python3的代码，所以我想，是否可以提供python3的支持。

**Comment by luty2018** [comment]
暂时不支持，目前jmeter官方插件仅支持Python2.7

**Comment by DsJay** [comment]
> 暂时不支持，目前jmeter官方插件仅支持Python2.7

哦~  明白了
