### ISSUE TITLE
[BUG] K8s Helm Charts 部署kafka无法连接

### ISSUE THREAD

**Issue by espooky** [metersphere/metersphere#16855]
### 联系方式

18133639761

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

metersphere server启动之后报错
1、mysql中metersphere库生成之后，排序规则不是utf8mb4_general_ci，导致flywaydb初始化数据库脚本时报错。
2、metersphere-server启动出现Public-Key Retrieval is not allowed，在jdbc连接后加上【&allowPublicKeyRetrieval=true
】即可。
2、metersphere-server 启动后会提示找不到kafka.bootstrap-server
（删除metersphere-server yaml中的kafka.bootstrap-server 关于env的映射 ，启动成功）

### 重现步骤

我是在kubesphere中通过helm安装最新版的metersphere，部署后，metersphere server启动报错

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #16697
