### ISSUE TITLE
[BUG]只是使用自定义脚本，执行这个简单脚本，耗时3s

### ISSUE THREAD

**Issue by cixiafeibixia** [metersphere/metersphere#16860]
### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/32405820/184312777-fe68a89c-1bb1-4791-8aba-386a466dfb1e.png)
只是使用自定义脚本，执行这个简单脚本，耗时3s，时间太久了

### 重现步骤

接口自动化 -> 场景 -> 添加自定义脚本 -> 脚本内容如图：
仅如图脚本，其他内容均无，
点击调试，必现

**Comment by zyyfit** [comment]
您好，虽然执行报错了，但是没有出现这种情况
![image](https://user-images.githubusercontent.com/73461316/184577431-0bc0408d-0f3c-4107-b7d3-7cd5316a034d.png)
