### ISSUE TITLE
[BUG] 接口导入，Swagger，使用URL导入，增加请求头 里增加的请求头 未被导入

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#16869]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud

### 使用外置数据库

否

### 问题描述

接口导入，Swagger，使用URL导入，增加请求头 里增加的请求头 未被导入

### 重现步骤

1. 参照下图即可
![5823c9469a69850e8aa44ee48c968e8](https://user-images.githubusercontent.com/76033005/184473690-f1b9c892-90a0-4f8e-89a6-fc3c271aa27a.png)

**Comment by zyyfit** [comment]
请求头不是导入的时候放到接口里的，是swagger url 验证权限用的，不会同步到接口定义里

**Comment by 35plus** [comment]
那这个功能 怎么 叫 “添加请求参数呢”？

“请求头不是导入的时候放到接口里的，是swagger url 验证权限用的，不会同步到接口定义里” --你说的，和我们看到的，感觉有点不匹配。

**Comment by zyyfit** [comment]
> 那这个功能 怎么 叫 “添加请求参数呢”？
> 
> “请求头不是导入的时候放到接口里的，是swagger url 验证权限用的，不会同步到接口定义里” --你说的，和我们看到的，感觉有点不匹配。

那你给产品提优化需求呀

**Comment by 35plus** [comment]
感谢
