### ISSUE TITLE
[BUG]部署时，MYSQL密码包含半角符号，会导致安装报错退出

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#16866]
### 联系方式

蒋林峰

### MeterSphere 版本

2.0.1

### 使用外置数据库

是

### 问题描述

客户使用外置数据库，数据库密码比较复杂，包含半角符号：^a~n(k_5&1
在安装过程中会直接报错，配置文件中的变量加载到MYSQL密码时就会报错停止安装，还没走到创建服务这一步就终止了。

用户的密码要求比较高，不支持修改密码，目前是通过以下方式临时绕过解决的：
先使用不带半角符号的密码，等服务起来了，再修改.env文件里，改成正确的密码

### 重现步骤

1.设置Install.conf文件里Mysql密码为^a~n(k_5&1
2.执行安装脚本 /bin/bash install.sh
3.安装报错
![image](https://user-images.githubusercontent.com/88763608/184468950-5b90b4f5-bdd7-4ed0-9597-edbece07cd83.png)

### 期待的正确结果

最好是安装脚本有处理这种符号的方法

**Comment by zyyfit** [comment]
.env 文件里改密码的时候这个复杂密码需要用单引号引起来

**Comment by linfengjjj** [comment]
![9cf96bf8ab7928c1dbf2803b801d7dc](https://user-images.githubusercontent.com/88763608/188827470-772bca50-bc0a-48fa-be21-3693bbdbf207.jpg)
![b7ce0dd845575560f0aacc4a6f89eb3](https://user-images.githubusercontent.com/88763608/188827486-3181f09c-15d0-4992-9ce1-45c5b5aac9ea.jpg)
![f16d0ef4f184654caf4e27272fc57e1](https://user-images.githubusercontent.com/88763608/188827502-0bf252f0-fac4-4928-8337-c5378b12c799.jpg)

2.1.0版本，.env文件密码加单引号会导致连接失败

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/14586

**Comment by zyyfit** [comment]
2.1版本的ms有问题

**Comment by linfengjjj** [comment]
由老师 这个bug已经很久了，之前跟杨杨沟通过，确实存在这个问题，之前规划到2.3.0，怎么现在又改成无法复现了？我录制了复现视频，但是太大了，上传不了，我私聊你吧

**Comment by youliyuan-fit2cloud** [comment]
> 由老师 这个bug已经很久了，之前跟杨杨沟通过，确实存在这个问题，之前规划到2.3.0，怎么现在又改成无法复现了？我录制了复现视频，但是太大了，上传不了，我私聊你吧

通过远程链接用户环境，没有复现该问题，如果下次出现请再次确认吧。
