### ISSUE TITLE
[BUG]接口自动化调试页面，部分场景的环境列表中突然出现其他项目，导致如果不选一个环境，则该场景都无法调试了

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#16868]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.0.0

### 使用外置数据库

否

### 问题描述

之前接口自动化场景的环境列表中只有本项目的环境
后来项目A的某个场景使用测试计划运行过、也使用场景调试来运行过
于此同时项目B的某个场景是定时任务运行的

现象：
后来项目A的该场景再去场景调试时，发现环境列表里多了项目B，导致调试时一定要选一个项目B的环境
但是使用资源池运行的时候，环境列表里又是正确的，是只能看到本项目的环境

突然出现的该问题，也不知道是不是上述操作导致，环境重启、redis清理都不能解决，求解决方案，或者提供sql查询定位问题

### 重现步骤

之前接口自动化场景的环境列表中只有本项目的环境
后来项目A的某个场景使用测试计划运行过、也使用场景调试来运行过
于此同时项目B的某个场景是定时任务运行的

现象：
后来项目A的该场景再去场景调试时，发现环境列表里多了项目B，导致调试时一定要选一个项目B的环境
但是使用资源池运行的时候，环境列表里又是正确的，是只能看到本项目的环境

突然出现的该问题，也不知道是不是上述操作导致，环境重启、redis清理都不能解决，求解决方案，或者提供sql查询定位问题

### 期待的正确结果

求解决方案，或者提供sql查询定位问题

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by xulinde** [comment]
没有复现该问题，能否详细描述下必现步骤，不然开发也不好定位问题，无法给出解决方案
