### ISSUE TITLE
[BUG]install.conf文件中密码包含$符号，会将$符号后面的密码识别成函数，加载到变量中密码就缺少了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#16867]
### 联系方式

蒋林峰

### MeterSphere 版本

2.0.1

### 使用外置数据库

是

### 问题描述

客户的redis密码包含$符号，结果安装时连接失败。
查看.env文件发现，密码中$和$之后的密码字符，都缺失了

### 重现步骤

1.install.conf文件中redis使用密码：123456$oienflk
![cbefbfe29f62db2963d7e00328efc66](https://user-images.githubusercontent.com/88763608/184469270-6cb43c62-8c31-4cf4-856f-43c1db0991ac.jpg)
2.执行安装脚本，/bin/bash install.sh
3.查看/opt/metersphere/.env文件，发现密码只加载了位于$符号之前的数据
![d9032a91e31868d3865d142fdd320c3](https://user-images.githubusercontent.com/88763608/184469274-07ed1614-5b4e-4830-b38c-5ff259b79bc7.jpg)

### 期待的正确结果

把$当成普通字符处理就行。

目前的临时解决方法是，服务起来之后，再去修改.env文件，客户觉得很麻烦，需要处理下

**Comment by zyyfit** [comment]
.env 文件里改密码的时候这个复杂密码需要用单引号引起来

**Comment by linfengjjj** [comment]
![9cf96bf8ab7928c1dbf2803b801d7dc](https://user-images.githubusercontent.com/88763608/188827876-3263bbb7-13af-4d5b-a082-59849ad48fa9.jpg)
![b7ce0dd845575560f0aacc4a6f89eb3](https://user-images.githubusercontent.com/88763608/188827901-423f9ea8-fb5f-42cd-b5c1-46c01cd0ffca.jpg)
![f16d0ef4f184654caf4e27272fc57e1](https://user-images.githubusercontent.com/88763608/188827914-2afe81a8-8e41-406e-88f2-aa3fe9b4f3b6.jpg)


2.1.0版本，.env文件密码加单引号会导致连接失败

**Comment by zyyfit** [comment]
![image](https://user-images.githubusercontent.com/73461316/188833952-2a426027-d851-40eb-973e-52b36caca01d.png)

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/14586
