### ISSUE TITLE
[BUG]从metersphere 导出的 swagger 不是标准格式，放置到swagger编辑上，提示很多错误

### ISSUE THREAD

**Issue by Calaoye** [metersphere/metersphere#16879]
### 联系方式

15920378176

### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 使用外置数据库

是

### 问题描述

从metersphere 导出的 swagger 不是标准格式的，放置到 https://editor.swagger.io/  swagger编辑上提示一堆的错误

### 重现步骤

1.在metersphere 编辑完接口，导出swagger3.0格式。
2.将导出的内容复制到  https://editor.swagger.io/，提示一堆的错误。（导出的格式不是标准格式）

可以将测试数据 拷贝至 https://editor.swagger.io/ 查看：
{"openapi":"3.0.1","info":{"version":null,"title":null,"description":null,"termsOfService":null},"externalDocs":{},"servers":[],"tags":[],"paths":{"/eventCase":{"get":{"summary":"事件编排列表","requestBody":{"content":{"multipart/form-data":{"schema":{"properties":{}}}}},"description":"事件编排列表","responses":{"[{\"valid\":false,\"file\":false,\"enable\":true,\"urlEncode\":false,\"required\":true}]":{"headers":{"":{"schema":{"type":"string"},"example":""},"Content-Type":{"schema":{"type":"string"},"example":"application/json"}},"description":"","content":{"application/json":{"schema":{"type":"string","example":"{\n    \"a\": 11111111,\n    \"b\": 22222222,\n    \"c\": {\n        \"b\": 3333333333\n    }\n}"}}}}},"parameters":[{"in":"query","name":"pageSize","description":"页码大小","required":true,"example":"null"},{"in":"query","name":"page","description":"当前页码","required":true,"example":"null"},{"in":"query","name":"name","description":"名称","required":false,"example":"null"},{"in":"query","name":"typeId","description":"类型id，支持多个, 用\",\"隔开","required":false,"example":"null"},{"in":"query","name":"status","description":"状态，1.启用 2.禁用","required":false,"example":"null"}],"tags":["事件编排"]}}},"components":{}}

### 期待的正确结果

Metersphere 和 Swagger 3.0格式要统一，方便推广

**Comment by xiaomeinvG** [comment]
您好，感谢您的反馈，建议您这边使用新版的编辑器 https://editor-next.swagger.io/ 可以很好的解决您说的问题
