### ISSUE TITLE
[BUG]  场景接口中设置参数为__setProperty函数取值，函数未返回值

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16872]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

![企业微信截图_16604508432575](https://user-images.githubusercontent.com/103925124/184522363-5b551145-6358-49f0-a46f-b33a2a9fb452.png)

正确请求内容;?name=23232

${__setProperty(property name, property value, True/False)}
该函数用来给JMeter属性设置值，默认返回值为空字符串，所以函数在任何地方被调用都是有效的
Property Name：要设置的属性名，必要属性
Property Value：要设置的属性的值，必要属性
True/False：原值是否要返回，非必要属性；当设置为“true”，将返回原始值
注：该函数的参数无需使用双引号引用

### 重现步骤

见上图

**Comment by xulinde** [comment]
这是jmeter里设置全局变量的吧，MS里设置全局变量就是设置环境参数，

**Comment by Ycr123888** [comment]
不是，是ms里面参数支持的${__setProperty函数用法
需求：这里设置完，有返回值，下面接口可以使用

**Comment by zyyfit** [comment]
我们系统里，一个场景就是对应jmeter里的一个测试计划，或者单独执行接口的时候，一个接口就是一个测试计划，
这个函数是用于测试计划中跨线程组设置和调用变量的，所以在我们系统里可以调用这个函数，但是意义不大
要是想跨场景引用或者单独调试接口在其他接口里引用，就用环境变量
