### ISSUE TITLE
[FEATURE]  编辑测试计划报告的编辑框高亮显示，保存按钮功能提示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16870]
### MeterSphere 版本

v1.20.11-lts

### 请描述您的需求或者改进建议

![企业微信截图_16604491065025](https://user-images.githubusercontent.com/103925124/184521717-81386f55-a622-45ab-af2c-b88007a79d07.png)
编辑框没有高亮显示，不知道报告可以编辑
点击保存后，提示保存成功，用户以为是已经保存为本地文件了

### 请描述你建议的实现方案

功能框显示优化

**Comment by luty2018** [comment]
在编辑那里加个小铅笔引导一下吧，保存的话就保留现状了。
