### ISSUE TITLE
[BUG]V1.19.3升级到V1.20.11 API自动化场景覆盖率清零

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#16873]
### 联系方式

14群-亲山留水

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/184529141-e2721d7a-fd22-41ed-ba80-c3ecfb16ead2.png)
1.19.3 版本升级至v1.20.11-lts API自动化场景覆盖率清零

新增的用例自动化场景有体现，历史数据覆盖率清理

### 重现步骤

1.19.3 版本升级至v1.20.11-lts API自动化场景覆盖率清零
1.19.3版本确实有新增API自动化用例，但覆盖率不变的bug，升级后该bug已修复，但历史覆盖率数据清零

### 期待的正确结果

项目历史API自动化场景的API覆盖率不应该清零

**Comment by xulinde** [comment]
没有复现该问题，有必现步骤吗，请详细描述下～

**Comment by zhangzhaox** [comment]
V1.19.3版本升级之前 是70%多的覆盖率  ，V1.19.3版本 新项目新增的自动化场景用例覆盖率一直都是0的bug 升级后该bug修复了，但出现现在的历史项目清零的情况 
能否提供一个检查分析的思路或者SQL 我先检查核对一下

**Comment by xulinde** [comment]
稍后技术同事会帮您处理～

**Comment by zhangzhaox** [comment]
目前得应对解决方案 重新保存一下自动化用例即恢复覆盖率统计
