### ISSUE TITLE
[FEATURE]测试报告列表中支持显示断言结果

### ISSUE THREAD

**Issue by wangyuwei18** [metersphere/metersphere#16889]
### MeterSphere 版本

v1.19.1-4fb56789

### 请描述您的需求或者改进建议

有很多case写的就是异常场景，加入断言之后断言成功，希望返回的结果也是成功，不是失败，但是报告列表中显示都是失败，不太好通过通知区分是接口出了问题还是本来就是异常场景

**Comment by luty2018** [comment]
能举个具体的例子吗，如果是因为状态码导致最后结果判断为失败，可以在断言的时候选中忽略状态。

**Comment by wangyuwei18** [comment]
就是case会写必填字段如果为空的验证，那么这个返回的状态码就一定是被判为失败的，我断言里写的就是提示不能为空，那么断言结果就是成功。怎么能在报告列表中显示成功呢

**Comment by luty2018** [comment]
> 就是case会写必填字段如果为空的验证，那么这个返回的状态码就一定是被判为失败的，我断言里写的就是提示不能为空，那么断言结果就是成功。怎么能在报告列表中显示成功呢

<img width="833" alt="image" src="https://user-images.githubusercontent.com/36292514/184794546-50e047f0-837a-45e4-931b-5535dff20378.png">
加一条正则并且忽略状态
