### ISSUE TITLE
[BUG] 接口参数中使用${__split}函数未生效，脚本中使用可实现

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16884]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述
![image](https://user-images.githubusercontent.com/103925124/184589529-ead765ac-88fe-4eb3-97a8-0306b27e061f.png)

取不到导致 地址异常
![企业微信截图_16605455092905](https://user-images.githubusercontent.com/103925124/184588096-bc9b80ff-b934-419e-8809-cfc4dab38130.png)
使用脚本可以分割：
![image](https://user-images.githubusercontent.com/103925124/184588801-c89a93b5-5f98-4830-8f62-fa2d93353e16.png)
循环可正常取到值：
![image](https://user-images.githubusercontent.com/103925124/184588946-7eed8eb6-eb63-4932-b3e9-b5449eaaed55.png)

### 重现步骤

见上图

### 附加信息
![image](https://user-images.githubusercontent.com/103925124/184590017-2bf55941-8bed-403d-8b79-95cf139b1852.png)

_No response_

**Comment by zyyfit** [comment]
你在请求里用的时候，中间的var后面多写了个 ） 
![image](https://user-images.githubusercontent.com/73461316/184785374-172cbfac-f512-4489-beac-c5926de1d24c.png)
