### ISSUE TITLE
[BUG]接口定义，如果接口名称很长，处在编辑状态时，整个接口名称会被显示出来，接口tab标题很长，影响易用性。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#16883]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud

### 使用外置数据库

否

### 问题描述

接口定义，如果接口名称很长，处在编辑状态时，整个接口名称会被显示出来，接口tab标题很长，影响使用
![Uploading d1991e477f49a9b279fc71ab2210b3d.jpg…]()

### 重现步骤

1. 定义一个名称比较长的接口（真有用户这么使用）。
2. 编辑该接口。
![d1991e477f49a9b279fc71ab2210b3d](https://user-images.githubusercontent.com/76033005/184582749-13358f5f-f5f6-461a-a38b-9ce55dbf0fe6.jpg)

### 附加信息

当接口名称很长时，接口编辑tab标题只显示固定的前多少个字符。

**Comment by xulinde** [comment]
v1.20.13-lts已优化～
