### ISSUE TITLE
[BUG] 环境变量显示不全

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1688]
**MeterSphere 版本**
1.7.3

**Bug 描述**
![image](https://user-images.githubusercontent.com/5517369/112082822-f5473b80-8bc0-11eb-9df9-a8fde05871f1.png)
通用变量输入了26个字符 实际上只显示一个；

**Bug 重现步骤**

**期待的正确结果**
正常情况建议显示26个字符

希望能将 “环境配置”的model的宽度设置大一点 显示出所有的环境变量.

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，是不是还有其他操作呢
![image](https://user-images.githubusercontent.com/64065190/112139670-079b9680-8c0e-11eb-8c5d-0b3f5f637c7f.png)

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/112241666-a6afa500-8c85-11eb-9097-6e763047f0ff.png)
@xulinde

**Comment by song-tianyang** [comment]
你好，环境配置的入口有很多， 我们从系统设置-项目管理-环境配置、 接口定义页面-设置案例-环境配置、 接口自动化-场景修改-环境配置 这几个入口都没发现这样的情况。 您是从哪个页面进行的环境配置操作呢？

**Comment by guhan121** [comment]
@song-tianyang 
在mac 14寸屏幕上；从场景的调试按钮左边 选择环境的最后一个环境配置

**Comment by song-tianyang** [comment]
您好！ 我们在1.7.3版本已经发现了这个问题，感谢您的帮助！我们看了很多地方结果忽略了这里

1.8版本我们重新设计了环境配置的设置和交互方式，在1.8目前的内部测试环境中发现这里显示正常了。

非常感谢！

**Comment by song-tianyang** [comment]
您好！ 我们在1.7.3版本已经发现了这个问题，感谢您的帮助！

1.8版本我们重新设计了环境配置的设置和交互方式，在1.8目前的内部测试环境中发现这里显示正常了。发布后您可以进行版本升级，验证一下。

非常感谢你的耐心与帮助！

**Comment by zyyfit** [comment]
1.8.0已修复
