### ISSUE TITLE
[BUG] jemter函数${__V拼接计数器为接口参数值，异常带[

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16887]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/103925124/184592357-fb051e65-ec00-479b-a4ea-e09b83367088.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/184592605-37cc7332-a096-4386-9b58-c10a3835ca77.png)
![image](https://user-images.githubusercontent.com/103925124/184592631-72335b06-4d0c-455c-81f6-c4f137ac4dcb.png)

**Comment by zyyfit** [comment]
列表变量不需要带 [ ] ，你在变量里带[]，取值的时候当然也带[] ，直接写就可以 ，这样
![image](https://user-images.githubusercontent.com/73461316/184786594-1ea9e6fe-8bca-479f-8c6a-729e5513c75e.png)
