### ISSUE TITLE
[FEATURE]提取参数-匹配多条的结果不支持python2random choice选择吗

### ISSUE THREAD

**Issue by wangyuwei18** [metersphere/metersphere#16892]
### MeterSphere 版本

v1.19.1-4fb56789

### 请描述您的需求或者改进建议

上一个接口提取参数-匹配多条，在后面的接口中使用python 的 random choice居然无法选择其中一个，请求内容显示变量没有取到（找客服小东看过了，确实不太行，说是要用别的办法）

**Comment by luty2018** [comment]
麻烦提供一下测试脚本给我们
