### ISSUE TITLE
[BUG] 计数器不生效?

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1689]
**MeterSphere 版本**
1.7.3

**Bug 描述**
场景变量设置计数器；场景里面有两个请求都需要用到msgId; 希望是生成uuid+submsgId组合的消息ID；可以跟踪消息顺序。实际上发现消息ID相同了.

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/5517369/112084616-12313e00-8bc4-11eb-8116-161b7d70e28e.png)
![image](https://user-images.githubusercontent.com/5517369/112084739-4c9adb00-8bc4-11eb-8789-03e39abd3359.png)

**Comment by xulinde** [comment]
收到，我们先复现下在反馈

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能详细描述一下复现过程吗
