### ISSUE TITLE
[BUG]历史压测报告监控详情数据无法查看

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#16893]
### 联系方式

xkmyf@qq.com

### MeterSphere 版本

v1.20.12-lts-2297374a

### 使用外置数据库

否

### 问题描述

性能测试-报告-监控详情，历史报告的监控数据看不到了（当时测试的时候是能看到的）。
![image](https://user-images.githubusercontent.com/18514555/184599847-3c7b6ae1-a9e7-4c42-8957-e5095d67caac.png)

### 重现步骤

升级新版本，查看历史压测报告（我的最近历史报告是6月30日的）监控详情数据。

**Comment by silvia-zhou123456** [comment]
感谢您的反馈，该问题我们正在解决并将在下个版本发布前修复完成，敬请期待

**Comment by liuruibin** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/23045261/185337079-3ca7d44b-4101-4c07-9f7f-f54410097f12.png">
我们自己的prometheus保存时间为200H，过期会自动清理，如果您有需求看历史报告可以修改报告保留时间

**Comment by xkmyf** [comment]
> 

请问如果修改storage.tsdb.retention参数例如365d并重启容器。后续通过msctl upgrade升级版本时（因为升级会覆盖yml文件并重新生成容器）会造成历史数据丢失吗？如果会造成数据丢失，如何在升级时不影响原有配置呢？

**Comment by silvia-zhou123456** [comment]
您好，每次升级会覆盖成原始值 若把保存时间由小改大，历史数据不会丢失；但是将保存时间由大改小，则会删除老数据。至于如何在升级时不影响原有配置，因为我们的文件夹里有备份的文件及相关日期，打开/opt/metersphere 您就可看到具体的情况
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/110455682/185738114-6810ae3e-0629-4ba2-bfbc-ac31d72140fb.png">
