### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by darcyc-chen** [metersphere/metersphere#16899]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

模板管理中的用例等级模板无法修改或者新增选项。
我们公司没有P0等级，想把所有的P0改成P1, P1 改成P2以此类推。

如果新增一个自定义模板，由于默认的用例等级无法删除，会导致页面上有2个用例等级，已忽略此方案。
最好可以提供修改默认用例等级模板的方法。

**Comment by luty2018** [comment]
用例等级在脑图模式也是基础字段，这里没有放开编辑主要考虑的是修改以后会导致脑图功能出现异常，所以暂时不能放开，但是我们是有规划解决这个问题的。
