### ISSUE TITLE
[BUG]  用例评审列表，当拖动用例的时候，必须刷新页面才能显示拖动后的结果。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16897]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.11-lts，v2.0.0

### 使用外置数据库

否

### 问题描述

用例评审列表，当拖动用例的时候，必须刷新页面才能显示拖动后的结果。

### 重现步骤

进入用例评审列表，然后推动用例。当即不会显示推动后的结果，然后刷新浏览器，即可看到结果

### 期待的正确结果

应该实时显示拖动结果

**Comment by xulinde** [comment]
v2.1.0已修复～
