### ISSUE TITLE
[QUESTION] 安装报错

### ISSUE THREAD

**Issue by hawking-lab** [metersphere/metersphere#169]
**请描述您的问题.**

curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh
sh: line 12: wget: command not found
tar (child): metersphere-release-v1.1.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sh: line 15: cd: metersphere-release-v1.1.0: No such file or directory
sed: can't read install.conf: No such file or directory
sed: can't read install.conf: No such file or directory
/bin/bash: install.sh: No such file or directory

**Comment by wangzhen-fit2cloud** [comment]
请问是用的什么操作系统安装的？

**Comment by hawking-lab** [comment]
这个问题已经解决了，是因为我系统里没有安装wget , 建议在安装脚本里做一个判断增加一个wget 安装操作
