### ISSUE TITLE
[BUG]jsonpath提取响应体里面的数组，foreach循环去遍历这个数组，不能循环遍历

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#16906]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.11

### 使用外置数据库

否

### 问题描述

1.jsonpath提取响应体里面的数组，foreach循环去遍历这个数组，不能循环遍历
![2b0cb7fae69a641e30ac77a41d1f2c8](https://user-images.githubusercontent.com/103627487/184664834-34185b4a-9766-4812-83fc-3c759a32c162.jpg)
![af96a86adef5feed2083dccda6f4686](https://user-images.githubusercontent.com/103627487/184664881-fb10d8cc-11ce-4c66-a233-d18009ff5f0c.jpg)
![b802ede9fe7425bb99bbddf41c03f03](https://user-images.githubusercontent.com/103627487/184664915-04c5e08a-79f6-4126-a28c-62414fb96aeb.jpg)

### 重现步骤

1.响应体中含有数组，可以用下面响应体mock,
{
    "code": 0,
    "data": [
        {
            "year": "2022",
            "dateList": [
                "06-30",
                "06-24",
                "06-17",
                "06-10",
                "05-31",
                "05-27",
                "05-20",
                "05-13",
                "04-30",
                "04-22",
                "04-15",
                "04-08",
                "03-31",
                "03-25",
                "03-18",
                "03-11",
                "02-28",
                "02-18",
                "02-11",
                "01-31"
            ]
        },
        {
            "year": "2021",
            "dateList": [
                "12-31",
                "12-20",
                "11-30",
                "10-31",
                "09-30",
                "08-31",
                "07-31",
                "06-30",
                "05-31",
                "04-30",
                "03-31",
                "02-28",
                "01-31"
            ]
        },
        {
            "year": "2020",
            "dateList": [
                "05-10",
                "04-18",
                "04-11",
                "03-31",
                "03-21",
                "03-10",
                "02-18",
                "02-11",
                "01-31",
                "01-21"
            ]
        }
    ],
    "msg": ""
}
2.提取响应体中数组

![af96a86adef5feed2083dccda6f4686](https://user-images.githubusercontent.com/103627487/184666956-536e28b2-ade8-4921-8cde-7eee96b2dfaf.jpg)
![b802ede9fe7425bb99bbddf41c03f03](https://user-images.githubusercontent.com/103627487/184667057-9e1613ba-4fa8-410b-b4b3-995c52dd17fc.jpg)

3.foreach循环遍历这个数组

### 期待的正确结果

foreach能正常循环遍历响应体中提取到数组

**Comment by zyyfit** [comment]
没复现这个问题，你提取的时候没勾选匹配多条，提出来是一个变量值，不是说你提取一个数组作为一个变量，这个变量就是数组类型的
![image](https://user-images.githubusercontent.com/73461316/184839276-26707ce6-54f8-4616-b9b6-bd82f91f76d2.png)
