### ISSUE TITLE
[BUG] 场景用例编辑异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1690]
**MeterSphere 版本**
1.7.3

**Bug 描述**
简要描述您碰到的问题
1. 批量移动**多个场景用例**时丢失了用例名称
2. 子模块包含用例时；无法重命名模块名称；页面显示错误提示3
![image](https://user-images.githubusercontent.com/5517369/112088739-507e2b80-8bcb-11eb-87f9-89df194e07e1.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，您这边是偶现还是必现的，必现的话请详细描述下复现步骤

**Comment by guhan121** [comment]
@xulinde 我今天移动用例的时候又出现问题了

在场景列表中 勾选多个用例；然后批量移动到其他模块.

**Comment by zyyfit** [comment]
第二个问题已在1.8.1版本中修复，第一个问题还是没有复现
