### ISSUE TITLE
[QUESTION]场景自动化中，如果有前置脚本报错，整个场景测试都会被判定为失败

### ISSUE THREAD

**Issue by DsJay** [metersphere/metersphere#16907]
### 请描述您的问题

请问这样设计的目的是什么呢? 条件控制器内为执行的用例应该是预期内的呀？

**Comment by luty2018** [comment]
你是用的什么版本呢

**Comment by DsJay** [comment]
> 你是用的什么版本呢

您好，我应该是比较新的1.20版本，前两周升级的。
我又仔细观察了下，发现不是因为条件控制器，而是我步骤内有前置脚本内部报错，虽然所有接口都成功了，但是最后报告展示的是ERROR

**Comment by song-tianyang** [comment]
您好，根据您的描述我并没有复现这个问题。

我在场景正常返回的步骤的前置脚本里放了一段编译失败的脚本，控制台也抛出了错误，但是这个场景的执行结果依然是成功的

![image](https://user-images.githubusercontent.com/75963100/185029532-91480e0b-a2c1-4c0d-b9ae-4466593d14fe.png)

![image](https://user-images.githubusercontent.com/75963100/185029583-8c971911-f421-421e-9b45-294b0b9332e4.png)
![image](https://user-images.githubusercontent.com/75963100/185029619-641780e8-2c32-4e8f-b42e-09aa49f9e628.png)

附本次的场景报告连接：
https://cloud.metersphere.com/shareApiReport?shareId=a80872b0-7eae-4163-9fcb-094f1cb3385b

**Comment by DsJay** [comment]
> 您好，根据您的描述我并没有复现这个问题。
> 
> 我在场景正常返回的步骤的前置脚本里放了一段编译失败的脚本，控制台也抛出了错误，但是这个场景的执行结果依然是成功的
> 
> ![image](https://user-images.githubusercontent.com/75963100/185029532-91480e0b-a2c1-4c0d-b9ae-4466593d14fe.png)
> 
> ![image](https://user-images.githubusercontent.com/75963100/185029583-8c971911-f421-421e-9b45-294b0b9332e4.png) ![image](https://user-images.githubusercontent.com/75963100/185029619-641780e8-2c32-4e8f-b42e-09aa49f9e628.png)
> 
> 附本次的场景报告连接： https://cloud.metersphere.com/shareApiReport?shareId=a80872b0-7eae-4163-9fcb-094f1cb3385b

我仔细看了下，我的是全局脚本报错，还设置了关联结果，所以报告显示ERROR，没有问题！感谢回答！
![image](https://user-images.githubusercontent.com/22111572/185039573-cc8455fd-76b8-454d-9cf9-4e24c0ede8da.png)
