### ISSUE TITLE
[FEATURE]接口自动化任务通知

### ISSUE THREAD

**Issue by pozhenzi** [metersphere/metersphere#16902]
### MeterSphere 版本

 v1.20.7-lts-f835cdf2

### 请描述您的需求或者改进建议

背景：当前接口自动化执行后的任务通知，只能打开报告链接后才能查看详细信息，但手机打开链接后不方便查看和操作。
改进建议：接口自动化的任务通知模板增加请求地址、请求入参、响应信息三个变量。方便在企业微信、钉钉、飞书机器人直观查看具体接口的信息。
困难点：当前任务通知是针对一个场景的，并不是针对单个接口。所以我自己也不是太明确这个建议是否合理。或者说如果在接口层级也做任务通知也能满足我的要求。

**Comment by Hyyfit** [comment]
目前设计是这样的
如果场景内的接口是失败继续，那么场景执行失败了，就会有非常多信息出来，反倒没办法快速的定位到问题。
所以暂不考虑做场景内的case的通知。
