### ISSUE TITLE
[BUG]一键部署提示找不到目录，是404

### ISSUE THREAD

**Issue by chenjiadong19951207** [metersphere/metersphere#16905]
### MeterSphere 版本

latest

### 使用外置数据库

否

### 问题描述

curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh

### 重现步骤

用ubantu，sudo curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh 提示404找不到路径cat: /tmp/ms_latest_release: 没有那个文件或目录

已发出 HTTP 请求，正在等待回应... 404 Not Found
2022-08-15 23:26:22 错误 404：Not Found。

tar (child): metersphere-online-installer-.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
bash: 第 78 行： cd: metersphere-online-installer-: 没有那个文件或目录
sed: 无法读取 install.conf: 没有那个文件或目录
sed: 无法读取 install.conf: 没有那个文件或目录
/bin/bash: install.sh: 没有那个文件或目录

**Comment by zyyfit** [comment]
这是网络不好，访问github时经常容易出现这种问题，可以多试几次，也可以在我们的官网下载离线包进行离线安装
