### ISSUE TITLE
[BUG] 接口定义，请求体开启JSON-Schema的时候，当点击请求的时候，请求内容中显示的请求体没办法转化Integer类型。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16912]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33945037/184794714-029d681a-c731-47c9-8408-96790b5216f8.png)

请求内容中的，还是String类型。上面已经选择是Integer类型的。

### 重现步骤

请求体开启Json-Schema，选择类型为Integer类型，点击请求。
在响应内容中的请求内容中可查看。

### 期待的正确结果

应该是Integer类型才对

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/15760
