### ISSUE TITLE
[BUG]上传按钮前的图标错误，如图

### ISSUE THREAD

**Issue by TestCorn** [metersphere/metersphere#16910]
### MeterSphere 版本

u2.0.0

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/24605571/184790732-8b2c44ec-a04b-4035-a6f6-2a9b12b78248.png)

### 重现步骤

系统设置-插件管理 页面

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
2.1.0版本已修复，请等待版本发布后验证
