### ISSUE TITLE
[BUG]  批量添加场景变量，列表添加后类型显示为常量

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16911]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/103925124/184794019-1eeeba0c-303a-440c-b9b4-c2377f869ea7.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/184794019-1eeeba0c-303a-440c-b9b4-c2377f869ea7.png)

### 期待的正确结果

可批量添加列表

**Comment by xulinde** [comment]
批量添加默认是常量，只能添加常量

**Comment by Ycr123888** [comment]
给个提示吧，不然输入全靠猜和尝试

**Comment by xulinde** [comment]
v2.1.0已添加提示信息
