### ISSUE TITLE
[FEATURE]优化建议：测试计划：用例执行失败添加了bug就不能标记为通过，只有当测试回归bug解决了再自动标记用例通过（测试活动中常见场景）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#16913]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

测试计划：用例执行失败添加了bug就不能标记为通过，只有当测试回归bug解决了再自动标记用例通过（测试活动中常见场景）

### 请描述你建议的实现方案

期望：用例执行和缺陷状态做关联：用例有缺陷数据无法标记通过，缺陷状态关闭后自动识别用例为通过状态

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/184800151-4633978e-e90e-4fc0-9d62-e0dec333c72b.png)

**Comment by luty2018** [comment]
可以考虑做成配置项 @Hyyfit
