### ISSUE TITLE
[BUG] 批量添加场景变量，未处理换行符号，导致取值异常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16928]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

编辑器中编写一下参数，使用ctrl+a全选后进行批量导入
![image](https://user-images.githubusercontent.com/103925124/184814476-b2bd3f1f-cb01-43f6-970f-939a7233d1fb.png)
执行导入
![image](https://user-images.githubusercontent.com/103925124/184814643-0561fafc-5a34-4e6f-b7e1-d7ceedb88174.png)

参数取值有换行符号导致URISyntaxException
![image](https://user-images.githubusercontent.com/103925124/184815134-5dc37a2f-2f7b-41dd-81eb-ab80b0601734.png)
参数取值有换行符号导致数据库查不到数据
![image](https://user-images.githubusercontent.com/103925124/184815329-a733ad6b-3664-49c1-a30b-00e70881e9ff.png)

且批量导入页面换行会产生空白行
![image](https://user-images.githubusercontent.com/103925124/184814724-f455c3e0-1f43-4e50-9eb3-4c6a5b2748c8.png)

### 重现步骤

见上述调用

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
