### ISSUE TITLE
[FEATURE]建议接口自动化场景里支持统一断言，比如校验返回code

### ISSUE THREAD

**Issue by jaychang1989** [metersphere/metersphere#1692]
**请描述您的需求或者改进建议.**
接口自动化场景里支持统一断言，比如校验返回code
![image](https://user-images.githubusercontent.com/2285653/112114144-ac0fdf80-8bf2-11eb-889c-93d4024462da.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
现在也是支持的，可以先往请求里加个断言，然后拖拽到场景

**Comment by jaychang1989** [comment]
> 现在也是支持的，可以先往请求里加个断言，然后拖拽到场景

是可以，没想到这样使用，谢谢
