### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1693]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
简要描述您碰到的问题
组织和空间名过长显示不正确
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72964047/112135700-07e56300-8c09-11eb-834b-0b6a1e319c3e.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xiongxiaoqing614** [comment]
Bug仍然存在
