### ISSUE TITLE
[BUG] windows下不同分辨率下测试跟踪和接口测试首页显示乱

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#16934]
### 联系方式

18311441708

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

分辨率1920×1080显示效果：  浏览器比例尺：100%
![image](https://user-images.githubusercontent.com/103925124/184818197-76b917fd-345c-400e-88a7-4241c74c6e9f.png)
![image](https://user-images.githubusercontent.com/103925124/184818292-77c3e4a4-8289-449b-b342-f54fb232c47e.png)

分辨率2520*1440显示效果：  浏览器比例尺：100%
![image](https://user-images.githubusercontent.com/103925124/184818564-b531c648-990b-48d9-9d30-255da6093ea1.png)

### 重现步骤

查看各模块下首页

**Comment by youliyuan-fit2cloud** [comment]
没有复现，说明什么浏览器和浏览器版本？

**Comment by Ycr123888** [comment]
两个电脑：
谷歌浏览器-版本 100.0.4896.127（正式版本） （64 位）      分辨率 2520*1440显示效果： 浏览器比例尺：100%
谷歌浏览器-版本 103.0.5060.53（正式版本） （64 位）分辨率2520*1440显示效果： 浏览器比例尺：100%
效果图描述中有

**Comment by youliyuan-fit2cloud** [comment]
使用Chrome 版本 104.0.5112.81（正式版本） （64 位）没有复现。请更新下版本并浏览器是全屏打开。

**Comment by Ycr123888** [comment]
浏览器已全屏打开，浏览器不好更新，需要ui测试

**Comment by luty2018** [comment]
v2.7版本的测试跟踪已经调整为自适应， 可以升级看看。
