### ISSUE TITLE
[BUG] 代码片段中导入python ssl模块在升级到2.0.1后执行出错

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#16945]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

在MSy由1.20.9 LTS 升级到2.0.1后，原先代码片段中的代码执行报错
----------------------------------------------------
代码片段中import ssl模块：
   import ssl
   context = ssl._create_unverified_context()

----------------------------------------------------
出错信息：

2022-08-16 16:15:11 ERROR ThreadGroup 1-1 Problem in JSR223 script JSR223Processor, message: {}
In file: inline evaluation of: ``   import ssl    context = ssl._create_unverified_context();'' Encountered "ssl context" at line 1, column 11.
 in inline evaluation of: ``   import ssl    context = ssl._create_unverified_context();'' at line number 1
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:82)

----------------------------------------------------
出错截图：

<img width="434" alt="image" src="https://user-images.githubusercontent.com/24548477/184831473-30bc2bad-83b4-4f9e-b7a0-30b3f95b0fde.png">

### 重现步骤

1. 在代码片段添加以下2行代码
   import ssl
   context = ssl._create_unverified_context()

2. 执行 （点击测试）

### 期待的正确结果

执行成功（1.20.9 LTS  & 1.20.11 LTS）

![image](https://user-images.githubusercontent.com/24548477/184832125-63781566-598f-4697-a989-a3c6b6a243ef.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
