### ISSUE TITLE
对每个用例进行评审时，点击添加图片链接 ，页面展示异常[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#16952]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

对每个用例进行评审时，点击添加图片链接  页面展示如下：
![image](https://user-images.githubusercontent.com/35896106/184843856-19b2d398-8e59-4a42-9f86-fbc2b43086f8.png)

![image](https://user-images.githubusercontent.com/35896106/184843792-bc61807a-27cf-4c2a-97c1-74e4aba42f4c.png)

### 重现步骤

1、在用例评审功能下发起用例评审
2、点击添加图片链接

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复~

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
