### ISSUE TITLE
[BUG]foreach中因为开启了"如果可能，缓存编译脚本"导致异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1695]
**MeterSphere 版本**
1.7.3
**Bug 描述**
1. 在foreach中增加自定义请求；输出变量为"inputA"
2. 给自定义请求增加前置脚本；
3. 运行脚本；inputA值始终为第一个值。

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
每次可以获取到最新的遍历值。

分析原因，生成脚本用jmeter打开；关闭掉脚本编译缓存一切正常。
![image](https://user-images.githubusercontent.com/5517369/112264036-387dd900-8cab-11eb-9a3b-190361dd1d53.png)

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
@wangzhen-fit2cloud 

1. 在foreach中添加自定义请求
2. 给自定义请求添加前置脚本。
3. vars.put("currenttimestamp","${__time(yyyyMMddHHmmss,)}") //生成秒数
4. log.info(vars.get("currenttimestamp"))
5. 运行后输出的时间戳值未发生变化。

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们确认下这个问题。

**Comment by guhan121** [comment]
@wangzhen-fit2cloud https://stackoverflow.com/questions/46418275/jmeter-when-not-to-use-cache-compiled-script-if-available

**Comment by guhan121** [comment]
https://jmeter.apache.org/usermanual/best-practices.html#jsr223

**Comment by zyyfit** [comment]
未复现该问题，v1.8.0已发布，您可以升到1.8.0看一下是否还有这个问题
