### ISSUE TITLE
[FEATURE]版本选择栏建议能同时支持手动输入，进行快速搜索匹配

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#16960]
### MeterSphere 版本

V2.0.1

### 使用外置数据库

否

### 问题描述

版本选择栏建议能同时支持手动输入，进行快速搜索匹配
背景：部分客户在使用版本管理功能，进行不同版本切换时，可能存在几十上百个分支版本，仅通过下拉框查看，会比较耗时不便利
涉及修改点：功能用例列表、测试计划关联用例栏、接口定义列表、接口自动化列表、性能测试测试列表

### 重现步骤

无

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/184853895-c96978ab-3872-443c-96e5-05a3c559e653.png)

**Comment by luty2018** [comment]
我们尽快安排
