### ISSUE TITLE
[QUESTION]在接口定义定时同步时，同步任务通知是否有新增接口和修改接口的详细信息呢？

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#16973]
### 请描述您的问题

目前配置的任务通知只有执行成功与失败，但是在产品迭代的过程中，经常性会有新增和修改接口的情况，此时又无法得知新增接口和修改的接口是哪些，无法在迭代过程中针对性的对新增和修改的接口做自动化
希望能在任务通知中通知新增接口信息和修改的接口信息或以其他表现形式体现

**Comment by luty2018** [comment]
你可以配置接口更新通知

**Comment by zhouxiongjie1997** [comment]
> 你可以配置接口更新通知
你是指二次开发吗？目前通知只有导入成功和失败。定时同步覆盖模式的更新时间又全部会变，不覆盖又不确定哪些是废弃的接口

**Comment by zhouxiongjie1997** [comment]
已在项目中看到通知
