### ISSUE TITLE
[BUG] 缺陷管理的高级搜索中创建人无法列出所有项目成员

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#16974]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

缺陷管理中，在高级搜索里，通过“创建人“ 进行搜索，无法列出所有项目成员（只列出部分用户）
![image](https://user-images.githubusercontent.com/24548477/184895406-601023a4-4819-4809-a8fe-4f8970ed99ef.png)

同时，“处理人” 字段可以列出所有用户（作为对比）
![image](https://user-images.githubusercontent.com/24548477/184895618-c8e7b814-3365-4a90-a874-e744bf4a09f0.png)

实际上，所有用户都创建了缺陷
![image](https://user-images.githubusercontent.com/24548477/184895783-d476e22a-f246-47bc-a78b-ae9a2f6738cd.png)

### 重现步骤

1. 在项目中添加多个成员
2. 通过不同成员创建多个缺陷
3. 在“缺陷管理”页面，选择“高级搜索”，在“创建人”字段中，检查所列出的用户列表

### 期待的正确结果

希望搜索时，“创建人” 字段 与 “处理人” 字段一样，能列出所有项目成员。

### 附加信息

根据验证，当用户只属于“项目成员”时，会出现该问题。
尽管在新版本中，手工创建用户时，选择“项目成员”时，会自动带出“工作空间成员”，但目前“创建人”的列出逻辑应该与“处理人”保持一致。且通过API创建用户后，批量添加用户组时，是可以只添加“项目成员”这个组的。

![image](https://user-images.githubusercontent.com/24548477/184896771-5433aadc-30f7-42c5-9521-ce6721eed992.png)

**Comment by xulinde** [comment]
1.创建人目前查的工作空间下的，后面版本会改成项目下的，和处理人逻辑保持一致；
2.通过API创建的用户，然后批量添加用户组，没有默认加工作空间角色，后端这里目前没加判断

**Comment by xyziven** [comment]
嗯，#1的处理逻辑可以。
#2 可以暂时不加判断。

**Comment by xyziven** [comment]
嗯，#1的处理逻辑可以。
#2 可以暂时不加判断。
