### ISSUE TITLE
[BUG]接口测试>>接口自动化>>导入：同样的导入文件；当【导入模块】选择“为规划场景”时，导入系统异常；当【导入模块】选择“空”时，能正常导入。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#16975]
### MeterSphere 版本

V.1.20.12-lts

### 使用外置数据库

否

### 问题描述

条件：导入的文件是从其他MS导出的json文件。

操作：
1、接口测试>>接口自动化>>导入：在弹出的导入页面中【导入模块】选择“为规划场景”，选择文件，然后点击保存。系统出现错误异常。如下图1
2、接口测试>>接口自动化>>导入：在弹出的导入页面中【导入模块】选择“空”，选择文件（同一个文件），然后点击保存。系统能正常导入。如下图2

### 重现步骤

条件：导入的文件是从其他MS导出的json文件。

操作：
1、接口测试>>接口自动化>>导入：在弹出的导入页面中【导入模块】选择“为规划场景”，选择文件，然后点击保存。系统出现错误异常。如下图1
2、接口测试>>接口自动化>>导入：在弹出的导入页面中【导入模块】选择“空”，选择文件（同一个文件），然后点击保存。系统能正常导入。如下图2

### 附加信息

![1660656881806](https://user-images.githubusercontent.com/78218624/184893682-01bc0635-683b-4e8b-9e69-1a8c1df113ba.jpg)

![Uploading 1660658172713.png…]()

**Comment by zyyfit** [comment]
没有复现，方便把场景文件上传一下吗

**Comment by huangxine** [comment]
[Metersphere_Scenario_Huang勿动.zip](https://github.com/metersphere/metersphere/files/9372200/Metersphere_Scenario_Huang.zip)

你找一个项目接口场景里为空的，没有任何数据和模块。你按上面的操作是一下。

**Comment by zyyfit** [comment]
收到，复现了

**Comment by zyyfit** [comment]
1.20 版本和 2.1 版本都已修复，请等待版本发布后验证
