### ISSUE TITLE
[BUG]对接禅道首次同步缺陷时，创建人全是同步的MeterSphere当前用户

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#16978]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

是

### 问题描述

对接禅道首次同步缺陷时，创建人全是同步的MeterSphere当前用户，而非禅道用户，如下图
![image](https://user-images.githubusercontent.com/35896106/185013765-02417ae6-e3d2-4be6-9a0b-4941789f644f.png)

### 重现步骤

1、服务集成对接禅道，验证成功
2、 MeterSphere 项目中手动关联 ID/key 和缺陷模板
3、个人信息绑定禅道账户
4、测试跟踪-缺陷管理点击同步缺陷

### 附加信息

禅道版本：开源版15.7.1

**Comment by luty2018** [comment]
1.服务集成里面填的是admin吧，所以同步过来创建人是admin，这里是admin去调的接口，所以展示没有问题
2.在模板里面添加一个禅道创建人的字段，跟禅道的缺陷创建人字段做映射，在MS列表这里展示禅道创建人就行。

**Comment by weishuo6** [comment]
好的，可以了，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月17日(周三) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]对接禅道首次同步缺陷时，创建人全是同步的MeterSphere当前用户 (Issue #16978)




 
1.服务集成里面填的是admin吧，所以同步过来创建人是admin，这里是admin去调的接口，所以展示没有问题
 2.在模板里面添加一个禅道创建人的字段，跟禅道的缺陷创建人字段做映射，在MS列表这里展示禅道创建人就行。
