### ISSUE TITLE
[BUG] 创建用例时的用例状态保存不成功

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#16976]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

在测试跟踪里，新创建用例，将用例状态设置为“进行中” 或 “已完成”。保存用例后，在列表页面仍显示为“未开始”

### 重现步骤

1. 新建用例，将用例状态设置为“进行中” 或 “已完成”

![image](https://user-images.githubusercontent.com/24548477/184901939-68c60bfb-8bdf-4d5d-b0c2-bcfe96e69b70.png)

2. 保存后，用例列表中还是显示为“未开始”
![image](https://user-images.githubusercontent.com/24548477/184902534-c79b51da-8ee3-4143-a1d5-dbf3a12c3181.png)

### 期待的正确结果

应保存创建时设定的用例状态

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
