### ISSUE TITLE
[BUG] 测试跟踪-功能用例-以xmind的方式导出用例，没有导出用例中的步骤

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#16986]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts，v2.0.1

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例
以xmind的方式导出用例，没有导出用例中的用例步骤和预期结果。
![image](https://user-images.githubusercontent.com/33945037/185022703-f0acdfeb-13e1-4d8f-93d8-300402435cb2.png)
![image](https://user-images.githubusercontent.com/33945037/185022733-9fe28c49-982d-4f70-9fa8-4133c823e21d.png)

### 重现步骤

测试跟踪-功能用例
以xmind的方式导出用例，没有导出用例中的步骤。

### 期待的正确结果

应该跟导入的模板一样才对。

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/16800
