### ISSUE TITLE
[BUG] 筛选后模块显示的用例数不准确

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#16994]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

在测试跟踪页面，根据“用例状态”进行筛选。
筛选后，左侧 模块 对应显示的用例数也会变化(实际上不应该变化）

![image](https://user-images.githubusercontent.com/24548477/185030988-3ad90194-2364-448b-9ae7-fe98b35dcf8a.png)

### 重现步骤

1. 进入测试跟踪页面
2. 根据用例状态进行筛选
3. 筛选后，模块显示的数字会变化
4. 在用例列表页面，设置每页显示50条，可以看到实际用例数量跟模块显示数字不一致

### 期待的正确结果

模块显示的用例数量不应该伴随着筛选变化

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会改为左侧模块树统计和右侧数量一致。

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
