### ISSUE TITLE
[BUG]文件夹用例自动被删除(偶现)

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#16998]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20.3-lts-b3

### 使用外置数据库

否

### 问题描述

一个文件夹下的所有用例都消失了

### 重现步骤

操作流程：
1.在临时文件夹下新建了一个需求文件夹，进入脑图模式，编写用例，编写完成，保存
2.进入测试计划，创建一个新的测试计划，将刚刚编写的P1用例关联
3.回到步骤1中的脑图模式，修改用例优先级，发现修改失败，刷新页面，临时文件夹就没了
因为问题也是偶现的，暂时没找到必现的步骤
![image](https://user-images.githubusercontent.com/67257251/185050993-70ccece2-67a8-45fa-9ab4-49e174f0b536.png)

### 相关日志输出

```shell
完整的info日志如下，发现11点的时候有很多的error，和文件夹消失的时间比较重合，不知道是否有关联
```

### 附加信息

[info.20220816-0.log](https://github.com/metersphere/metersphere/files/9357017/info.20220816-0.log)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，开发同学看过日志，和这个问题没关系。建议升级到最新版本 v1.20.12-lts。如果还会遇到请随时联系我们。

**Comment by libb-test123** [comment]
后面发现这写用例的所属模块在数据库中从level1 被改成了level2，且有一个父目录。重新修改了数据库这儿的数据，数据就恢复了。但是这个现象还是很奇怪的，测试用例的数据都有，但是模块目录被改动了。

**Comment by youliyuan-fit2cloud** [comment]
> 后面发现这写用例的所属模块在数据库中从level1 被改成了level2，且有一个父目录。重新修改了数据库这儿的数据，数据就恢复了。但是这个现象还是很奇怪的，测试用例的数据都有，但是模块目录被改动了。

了解了，如果再次复现请随时联系我们，附上log和数据库信息，感谢~

**Comment by libb-test123** [comment]
再次出现了这个问题，目录的level被从2改成了3，更新时间上看是没有任何操作的。麻烦再帮忙看一下
![image](https://user-images.githubusercontent.com/67257251/186367942-7c17d121-3ee0-42d4-9415-53cb1e49e384.png)
![image](https://user-images.githubusercontent.com/67257251/186372255-cf416602-55bd-4746-8de3-899b347c4484.png)
![image](https://user-images.githubusercontent.com/67257251/186372310-2a47ef83-fffa-47f3-8599-815ff801a156.png)
![image](https://user-images.githubusercontent.com/67257251/186372377-f612ab9a-05e4-476a-8829-8b3c971bf2c5.png)

**Comment by libb-test123** [comment]
info.log日志如下文件
[info.log](https://github.com/metersphere/metersphere/files/9415767/info.log)

**Comment by xulinde** [comment]
> 再次出现了这个问题，目录的level被从2改成了3，更新时间上看是没有任何操作的。麻烦再帮忙看一下 ![image](https://user-images.githubusercontent.com/67257251/186367942-7c17d121-3ee0-42d4-9415-53cb1e49e384.png) ![image](https://user-images.githubusercontent.com/67257251/186372255-cf416602-55bd-4746-8de3-899b347c4484.png) ![image](https://user-images.githubusercontent.com/67257251/186372310-2a47ef83-fffa-47f3-8599-815ff801a156.png) ![image](https://user-images.githubusercontent.com/67257251/186372377-f612ab9a-05e4-476a-8829-8b3c971bf2c5.png)
用例跳转，所属模块为空，这个用例是跨项目的还是本项目的？如果是跨项目，是已知问题，后续版本修复；如果是本项目，我们这边没遇到过，可以录个操作视频看下

**Comment by xulinde** [comment]
> 是本项目的，我也没有复现，这个问题是偶现的。

用例被自动删除这个问题也未复现
