### ISSUE TITLE
[BUG]功能用例关联场景自动化用例后，在测试计划中执行该场景用例，会一致卡在执行中。

### ISSUE THREAD

**Issue by darcyc-chen** [metersphere/metersphere#16999]
### 联系方式

523867558@qq.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

功能用例关联场景自动化用例后，在测试计划中执行该场景用例，会一致卡在执行中。

### 重现步骤

1. 功能用例关联一个场景自动化用例。
2. 创建测试计划关联该功能用例（场景自动化用例会自动关联）
3. 执行该测试计划。

### 期待的正确结果

预期：测试计划执行成功，场景用例完成后会自动标记功能用例结果。

实际：场景用例一致卡在执行中。

**Comment by xulinde** [comment]
没有复现该问题，单独执行场景可以成功吗？
