### ISSUE TITLE
[BUG] [测试跟踪] 无法筛选出指定状态的用例

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#16991]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

测试跟踪页面，在“用例状态”列，指定状态进行筛选，结果其他状态的用例也能显示在页面上

### 重现步骤

1. 创建足够多的用例（太少无法重现），需要几十条（本次验证有58条）
2. 在“用例状态”列，指定状态（如“进行中”）进行筛选
![image](https://user-images.githubusercontent.com/24548477/185028316-025658f1-8178-47d4-a9c4-fd04fbffd899.png)

3. 实际上其他状态的用例也显示在页面上
![image](https://user-images.githubusercontent.com/24548477/185028638-05a85907-4f30-4cb9-bade-276790bd72eb.png)

### 期待的正确结果

能筛选出指定状态的用例

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
