### ISSUE TITLE
[FEATURE]压测报告发送到邮箱

### ISSUE THREAD

**Issue by wjangelking** [metersphere/metersphere#17]
**请描述您的需求或者改进建议.**

目前压测报告不发送到邮箱

**请描述你建议的实现方案**

压测报告发送到邮箱作为可配置项

**Comment by 2115055005** [comment]
建议定时跑批测试，出现异常触发发送异常到指定的邮箱（支持选择多个邮箱）

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
