### ISSUE TITLE
[BUG]用例名称字段显示长度太短了，建议占一行。

### ISSUE THREAD

**Issue by dahuachao** [metersphere/metersphere#170]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
在新版本中增加了列表宽度调节功能
