### ISSUE TITLE
[FEATURE]测试计划-功能用例执行时，添加的缺陷不能编辑修改、删除（存在误添加的情况）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17003]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

测试计划-功能用例执行时，添加的缺陷不能编辑修改、删除（存在误添加的情况）

### 请描述你建议的实现方案

测试计划--执行功能用例执行时可以对添加的缺陷做删除、删除操作

### 附加信息

<img width="960" alt="tapd_33805590_base64_1655705621_62" src="https://user-images.githubusercontent.com/43202800/185061725-8ec17fd6-0272-416f-9adf-7e5bb3368abf.png">

**Comment by luty2018** [comment]
这个可以加 @Hyyfit
