### ISSUE TITLE
[FEATURE]单接口调试，有时候需要使用从其他接口获取的前置参数。目前只能通过写脚本获取，希望添加自定义请求通过jsonpath提取

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17005]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

单接口调试，有时候需要使用从其他接口获取的前置参数。目前只能通过写脚本获取，希望添加自定义请求通过jsonpath提取

### 请描述你建议的实现方案

期望 单接口参数调试也可以添加类似自定义请求通过jsonpath提取 目标参数

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/185064486-38c34e48-2b5d-45bc-b84f-ef3a3432a69e.png)

**Comment by luty2018** [comment]
这个我们需要调研一下
