### ISSUE TITLE
[BUG]MS插件json文件导入API接口，未按照自定义事务生成对应目录，且未生成单API的case用例

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#17017]
### 联系方式

14群-亲山留水

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

是

### 问题描述

MS插件json文件导入API接口，未按照自定义事务生成对应目录，且未生成单API的case用例

### 重现步骤

MS插件录制API，包含自定义事务
json文件导入API,未生成自定义事务目录和单API用例

### 期待的正确结果

生成自定义事务目录和单API用例，v1.19.3版本的该功能是好的

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把MS插件的json文件发我们试试吗 ？

**Comment by zhangzhaox** [comment]
[RECORD-2022-08-19-10-43.zip](https://github.com/metersphere/metersphere/files/9378833/RECORD-2022-08-19-10-43.zip)
包含2个事务 test1 test2

**Comment by xiaomeinvG** [comment]
您好，你说的生成自定义目录是值接口的模块吗？

**Comment by zhangzhaox** [comment]
> 您好，你说的生成自定义目录是指接口的模块吗？是的

**Comment by zyyfit** [comment]
1.20.14版本已修复，请等待版本发布后验证
