### ISSUE TITLE
[QUESTION] 请问metersphere有根据接口参数自动生成用例的功能吗？

### ISSUE THREAD

**Issue by TesterPi** [metersphere/metersphere#17022]
### 请描述您的问题

对单个接口测试的本质是通过测试参数的排列组合验证返回值是否符合预期，接口参数的排列组合，人工转换成自动化测试用例，会耗费测试人员大量的时间。请问metersphere有根据接口参数自动生成用例的功能吗？

**Comment by luty2018** [comment]
在我们企业版有根据参数规则生成测试数据的功能，满足测试需要可以另存为测试用例

**Comment by TesterPi** [comment]
> 在我们企业版有根据参数规则生成测试数据的功能，满足测试需要可以另存为测试用例

请问根据参数规则生成测试数据的原理是通过PICT工具实现的吗？

**Comment by luty2018** [comment]
目前不是，可以参考PIPC去做，或者你有什么更好的建议吗，欢迎与我取得联系！
<img width="449" alt="image" src="https://user-images.githubusercontent.com/36292514/191225824-756ad9cf-8580-4825-859d-98ea2c68ed05.png">
