### ISSUE TITLE
[BUG]断言规则问题

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1702]
**MeterSphere 版本**
1.7.3

**Bug 描述**
在网关模块处理数据时；如果数据不合法；返回响应码是500；返回的响应体是json;
对返回做断言 断言返回码为500的时候为pass.
实际上在报告中该请求还是被统计到fail里面

看样子是有一个默认的断言 要求返回值不能是500？
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/5517369/112414872-c87c5b00-8d5d-11eb-8515-af778683b6c4.png)

![image](https://user-images.githubusercontent.com/5517369/112415105-30cb3c80-8d5e-11eb-8c4c-a512b97a004f.png)

**Comment by xulinde** [comment]
可以勾选忽略状态，则执行结果根据断言来判断
![image](https://user-images.githubusercontent.com/64065190/112452842-03988180-8d92-11eb-89c2-3dd2b2094f85.png)
