### ISSUE TITLE
[BUG]后置脚本，用正则方式提取参数失败

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17036]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.10

### 使用外置数据库

否

### 问题描述

接口case执行成功，使用正则表达式进行参数提取，提取为空。

用正则表达式在线测试工具，同一个返回结果，同一个表达式，参数提取成功。

### 重现步骤

ms参数提取：
![image](https://user-images.githubusercontent.com/15188833/185276534-7fd547b9-6efd-4b5c-a3e9-459becead848.png)

在线正则表达式工具结果1：
![image](https://user-images.githubusercontent.com/15188833/185275898-74b430e0-9293-4024-aa97-8b0264651f15.png)

在线正则表达式工具结果结果2：
![image](https://user-images.githubusercontent.com/15188833/185276588-ccc75ede-d836-4690-97b4-ff27bfcd2456.png)

返回结果，你可以mock请求，把返回结果复制进去，用正则表达式进行参数提取试下。
[新建文本文档.txt](https://github.com/metersphere/metersphere/files/9367092/default.txt)

**Comment by zyyfit** [comment]
我们的接口是用jmeter执行的，正则表达式我们的 模板值 默认填了 $1$，然后你这条提取结果没有g1 的值，所以返回了空，你可以先试试换一个写法，然后我们也看看这里有没有更好的处理方式

正则表达式使用可以参考这个文章
https://blog.csdn.net/u011441473/article/details/124826760
![image](https://user-images.githubusercontent.com/73461316/185535541-c733f305-2b2e-4f01-9213-d9e039e0fc14.png)

**Comment by startpjx** [comment]
还是不行，试了好几种方式，获取不到
![image](https://user-images.githubusercontent.com/15188833/185553522-64553d7b-3216-4e1b-b53e-87e9fa6d1c12.png)

**Comment by zyyfit** [comment]
> 

你想提取的值是什么呢？

**Comment by startpjx** [comment]
响应体里面的值：
![image](https://user-images.githubusercontent.com/15188833/187333520-aad92a39-5549-41ae-a124-60dbe7f8e311.png)
