### ISSUE TITLE
[BUG] 测试计划通知执行完成和执行成功集成了通知到飞书机器人，实际没有消息通知

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#17034]
### 联系方式

3095500370@qq.com

### MeterSphere 版本

 v1.20.12-lts-2297374a

### 使用外置数据库

否

### 问题描述

在项目消息设置中配置了测试计划删除，执行完成，执行成功通知到飞书
![image](https://user-images.githubusercontent.com/49423711/185111847-af82f650-5c18-4880-9691-a14a5d9c902d.png)
实际只有删除的有通知到飞书

### 重现步骤

1. 在项目中添加删除，执行成功，执行完成的通知到飞书
2. 新建测试计划，添加一条用例，执行用例为完成
3. 手动修改测试计划状态为已完成
4. 飞书群无法收到通知

### 期待的正确结果

配置的执行完成在测试计划完成状态通知到飞书群
执行成功无法确定是测试用例还是测试计划状态的变更会通知，目前两者状态变更都未进行通知

**Comment by xulinde** [comment]
通过测试计划执行接口或性能用例才会触发消息通知，手动修改计划状态不会触发通知
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/64065190/185557535-83e856c7-2b05-467a-af18-d7670f885d44.png">
