### ISSUE TITLE
[BUG]应用管理-接口测试，设置保留最近15天报告，仍存在前两个月的报告

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#17035]
### 联系方式

1136912596@qq.com

### MeterSphere 版本

v2.0.0-b4

### 使用外置数据库

否

### 问题描述

设置保留最近15天报告，已保留该设置近一周
![image](https://user-images.githubusercontent.com/75885014/185271675-298ef3cc-e4d5-4b9e-ae2e-4c0f0c8a79a0.png)

系统仍然保留了15天之前的报告
![image](https://user-images.githubusercontent.com/75885014/185271772-81ff8ffc-9a61-42c9-9f6c-3990ddbc9000.png)

### 重现步骤

如问题秒速

### 期待的正确结果

仅保留最近15天的报告

**Comment by zyyfit** [comment]
您好，方便提供一下最近几天的日志吗？

**Comment by bobo-wk** [comment]
> 您好，方便提供一下最近几天的日志吗？
如下，8月15-8月19号日志
[bug17053日志.zip](https://github.com/metersphere/metersphere/files/9390847/bug17053.zip)

**Comment by zyyfit** [comment]
收到

**Comment by shiziyuan9527** [comment]
@bobo-wk 您好，根据日志显示，磁盘空间不足导致删除报告失败，先检查下磁盘空间吧。
