### ISSUE TITLE
[BUG] 【测试计划】测试计划-关联功能用例-执行人默认是执行人

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#17043]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

用其它用户登陆metersphere创建测试计划，在测试计划关联功能用例，执行人显示是admin

### 重现步骤

1.用非admin用户登陆
2.进入测试跟踪-测试计划界面，点击创建测试计划
3.填写相关信息，点击规划&执行
4.关联功能用例
5.点确定

### 期待的正确结果

1.期待关联用例的执行人是责任人

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/185282991-2176e000-bf26-4ddb-85c9-d18769ae7411.png)
![image](https://user-images.githubusercontent.com/45531073/185283086-20ce395d-00a2-446f-9e59-0212af1dee7f.png)

**Comment by xulinde** [comment]
已知问题，后续版本会修复～

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
