### ISSUE TITLE
[FEATURE]让接口测试可以选择资源池节点

### ISSUE THREAD

**Issue by shorile** [metersphere/metersphere#1705]
**请描述您的需求或者改进建议.**
在多个公有云及私有云都在使用的情况下，各个云都有自己的内网，网络之间存在隔离。
在每个云上部署一个资源池节点，metersphere与每个资源池节点打通网络，就可以选择各个云上的资源池节点进行性能测试。
但接口测试没有选择资源池的功能，metersphere无法对部署在其它云上的应用进行内部接口测试。

**请描述你建议的实现方案**
需要metersphere的接口测试中能够提供选择资源池节点的功能

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中

**Comment by seasoncool** [comment]
@xulinde 
强烈推荐，接口测试 可以选择资源池，来降低宿主机的压力。
请问，会在本月的版本更新进去吗 ？

**Comment by xulinde** [comment]
v1.10.2版本已支持
