### ISSUE TITLE
[BUG]大量执行dubbo接口自动化场景时，java.util.concurrent.ConcurrentHashMap会占用大量的内存资源无法释放，导致gc无法正常回收，cpu资源占满

### ISSUE THREAD

**Issue by wangjqi** [metersphere/metersphere#17055]
### 联系方式

wangjunq@homeking365.com

### MeterSphere 版本

v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

大量执行dubbo接口自动化场景时，java.util.concurrent.ConcurrentHashMap会占用大量的内存资源无法释放，导致gc无法正常回收，cpu资源占满

### 重现步骤

1.创建测试计划，关联大量的dubbo自动化场景（60多个场景）
![image](https://user-images.githubusercontent.com/50005529/185308380-7739b9dc-d4d9-4e5c-b4f7-4860d325eade.png)
2.定时执行完dubbo接口自动化场景后cpu资源会被占满
![origin_img_v2_7012dcc8-3cd9-45e7-a652-020ce4ff71cg](https://user-images.githubusercontent.com/50005529/185308456-fb21af0d-7194-46a0-945e-a2fd3f4a6b62.jpg)

### 期待的正确结果

执行dubbo接口自动化场景后，资源能正常释放

**Comment by zyyfit** [comment]
您好，大量执行是大概多少个接口呢？我们先尝试复现一下

**Comment by zyyfit** [comment]
好的，我们先尝试复现一下

**Comment by zyyfit** [comment]
2.1.0已修复，请等待版本发布后验证

**Comment by KyleWong2007** [comment]
> 2.1.0已修复，请等待版本发布后验证

怎么修复的，请教您，感谢！
