### ISSUE TITLE
[FEATURE]建议增加测试用例自定义字段的录入、导出

### ISSUE THREAD

**Issue by jennie26** [metersphere/metersphere#1706]
**请描述您的需求或者改进建议.**
1. 测试用例增加自定义字段
2. 导出时可以导出含自定义字段的用例表格

**请描述你建议的实现方案**
1. 用例点击操作后，可以添加字段、增加添加字段的显示 
![image](https://user-images.githubusercontent.com/47876700/112438924-70f0e600-8d83-11eb-8d6a-cb71f8653eb8.png)
2. 导出成excel格式时，增加的字段可以一同导出。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
