### ISSUE TITLE
[BUG]性能测试脚本中包含js附件，执行压测报错

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#17066]
### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

否

### 问题描述

性能测试脚本中包含js附件，执行压测报错

### 重现步骤

1、jmeter中新建JSR223 Sampler，内容如下
![image](https://user-images.githubusercontent.com/5198427/185346611-22f83eb4-2783-46f8-9eac-435445711302.png)
2、本地调试通过，引入的js文件是一个求和函数
![image](https://user-images.githubusercontent.com/5198427/185346881-f216e91e-e6db-4f65-b98d-f6e57fe69aa1.png)
![image](https://user-images.githubusercontent.com/5198427/185346822-ee2231c5-d786-49d2-b772-d1256cdcb8aa.png)
3、上传jmeter脚本和test.js文件到MS平台，执行压测报错，错误如下
![image](https://user-images.githubusercontent.com/5198427/185347100-5b9f27b7-a552-43cf-8f43-36d70398d154.png)

### 期待的正确结果

MS能正确执行包含JS文件的性能测试

**Comment by silvia-zhou123456** [comment]
感谢您的反馈，经验证该问题确实存在，我们将尽快解决。

**Comment by silvia-zhou123456** [comment]
解决办法见上述描述
