### ISSUE TITLE
[QUESTION]如何删除上传的 jmx 文件或 jar 文件？

### ISSUE THREAD

**Issue by abcanqi** [metersphere/metersphere#1707]
版本: `v1.8.0-21bf611d`
操作：上传 jar 文件或 jmx 文件后，未找到删除的地方
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/36783970/112443569-11490980-8d88-11eb-8a57-74ed96947eb0.png">

**Comment by xulinde** [comment]
删除jar文件：系统设置-项目管理-jar包管理
删除jmx文件：系统管理-项目管理-选择项目-操作-资源文件

**Comment by abcanqi** [comment]
谢谢，解决了我的问题👍
