### ISSUE TITLE
[BUG]表格用例导入更新，提示更新成功，但是内容没有更新

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17077]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.12-lts

### 使用外置数据库

否

### 问题描述

将表格用例导出，修改内容后再导入更新，但是内容没有更新

### 重现步骤

1.新建用例，导出用例表格文件
2.修改用例表格文件的用例步骤内容
3.导入更新的表格用例
4.提示导入成功，但实际上用例内容没有更新
5.操作视频参考附件

### 期待的正确结果

用例内容会更新

### 附加信息

[表格用例导入更新.zip](https://github.com/metersphere/metersphere/files/9372207/default.zip)

**Comment by xulinde** [comment]
没有复现，你看下我的操作视频

https://user-images.githubusercontent.com/64065190/185554207-518cddcd-b5c7-489c-8302-00869a986548.mov

**Comment by linfengjjj** [comment]
> 没有复现，你看下我的操作视频
> 
>  2022-08-19.2.01.55.mov

试试文本描述，我的复现视频里用例内容是用的文本描述，不是步骤描述

**Comment by xulinde** [comment]
v1.20.14-lts已修复～
