### ISSUE TITLE
[FEATURE]  场景次数循环，次数框提示毫秒

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17074]
### MeterSphere 版本

v1.20.11-lts

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/103925124/185356524-1d641300-ce8d-451f-be72-3a795a1fc685.png)

改为参数说明或案例

**Comment by Hyyfit** [comment]
好的，小版本会优化的
