### ISSUE TITLE
[BUG]循环执行步骤，步骤中包含前置sql，循环只能成功一次

### ISSUE THREAD

**Issue by jazhao88** [metersphere/metersphere#17086]
### 联系方式

136718816@qq.com

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

是

### 问题描述

测试场景中，添加循环控制器，循环控制器下添加用例步骤（步骤中包含前置sql）。执行场景后，只能执行1次循环

### 重现步骤

1、创建场景
2、添加循环控制器，设置10次
3、添加用例步骤，步骤中设置有前置sql
4、执行场景

### 期待的正确结果

4、执行10次循环

**Comment by silvia-zhou123456** [comment]
您好，您在执行完该测试场景后，测试报告中，您添加的循环控制器是否已触发执行？
