### ISSUE TITLE
[BUG]执行sql失败，报：String index out of range: -1

### ISSUE THREAD

**Issue by jazhao88** [metersphere/metersphere#17085]
### 联系方式

136718816@qq.com

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/51432833/185376195-d069a441-8088-45cf-9ac8-da578fab3d16.png)
执行sql时，报错：String index out of range: -1
原始sql：
Body :
[Callable Statement] 
"SELECT t3.biz_id FROM study_question.question t1, study_question.question_category t2, study_base.category t3 WHERE t1.biz_id=t2.question_id AND t2.category_id=t3.biz_id AND t1.type=0 AND t1.`status`=0 AND t1.deleted=0 AND t3.deleted=0 AND t3.active=0 AND t1.tenant_id=100000825009 LIMIT 10"

### 重现步骤

执行sql

### 期待的正确结果

获取到数据

**Comment by silvia-zhou123456** [comment]
您好，“String index out of range: -1”是您写的这段sql中出现了字符串索引越界，建议您优化下您的sql语句并和您项目中的开发同学联调下相关sql语句；建议在您电脑中先使用Navicat调试下相关sql语句，再放入到MeterSphere中执行。通常情况下，若是您调试的语句没问题，放入到MeterSphere中也能正常执行
