### ISSUE TITLE
资源池的并发数限制没有生效[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1708]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8
**Bug 描述**
简要描述您碰到的问题
在资源池配置并发数，然后性能测试配置超过资源池限制的最大并发数，依然可以保存成功
**Bug 重现步骤**
1.  在资源池配置并发数
2. 然后性能测试配置超过资源池限制的最大并发数
3. 依然可以保存成功

**期待的正确结果**
正确情况下应该是什么样的？
提示超出最大并发数异常
![image](https://user-images.githubusercontent.com/80814232/112450918-dba81e80-8d8f-11eb-90d0-b4a4f78e5027.png)
![image](https://user-images.githubusercontent.com/80814232/112450953-e4005980-8d8f-11eb-9c58-d9c723a6652d.png)

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，v1.8.1会修复
