### ISSUE TITLE
[QUESTION] 请问metersphere有参数化的功能吗？

### ISSUE THREAD

**Issue by TesterPi** [metersphere/metersphere#17080]
### 请描述您的问题

接口中可能有一些参数想参数化的方式执行，请问metersphere支持上传csv文件进行参数化执行用例吗？

**Comment by zhangzhaox** [comment]
必须的啊，没有找到位置？
![image](https://user-images.githubusercontent.com/82088551/185532484-93c2f14c-db96-4526-87c2-a63e64f32532.png)
原则上能不用参数化就不用，入参提供了丰富的函数生成数据
