### ISSUE TITLE
[BUG]只读用户使用CTRL+R快捷键可以执行用例

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17099]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.12-lts
2.0.1
### 使用外置数据库

否

### 问题描述

只读用户使用CTRL+R快捷键可以执行用例

### 重现步骤

1.只读用户点击进入场景详情
2.点击CTRL+R
3.接口自动化场景竟然执行了

### 期待的正确结果

不能执行

### 附加信息

[只读用户CTRL+R执行场景.zip](https://github.com/metersphere/metersphere/files/9378651/CTRL%2BR.zip)

**Comment by youliyuan-fit2cloud** [comment]
只读用户没有编辑接口场景的权限，你怎么做到查看详情的？

**Comment by linfengjjj** [comment]
我是给的用户只读用户的权限，只读用户组的权限我没修改过，就是我们的默认配置。
可能：1.我们只读用户的查询场景的权限包含查询场景列表和查看场景详情
           2.可能这是另外一个bug
















在 2022-08-20 12:25:56，"MatataYou" ***@***.***> 写道：

只读用户没有编辑接口场景的权限，你怎么做到查看详情的？

**Comment by youliyuan-fit2cloud** [comment]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/54612864/185731034-b9dbeef8-4464-4464-8ab6-a384b9f5c9f5.png">

只读用户的页面不是这样的？

**Comment by linfengjjj** [comment]
列表页面是这样的没错，但是是可以进入详情的，比如你点击任意一条场景用例的名称，就可以进入详情页面。然后，在详情页面不可以修改，只能查看。但是，通过ctrl+r可以使场景执行，这就是问题所在

在 2022-08-20 13:50:33，MatataYou ***@***.***> 写道：


只读用户的页面不是这样的？

**Comment by xulinde** [comment]
v1.20.13-lts已修复～
