### ISSUE TITLE
[BUG]功能用例列表想要复制用例的名称信息，即使是鼠标长按选中用例名称也判定为点击事件了，接口测试列表中并没有这个问题。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17096]
### MeterSphere 版本

V1.20.11

### 使用外置数据库

否

### 问题描述

[BUG]功能用例列表想要复制用例的名称信息，即使是鼠标长按选中用例名称也判定为点击事件了，接口测试列表中并没有这个问题。

### 重现步骤

[BUG]功能用例列表想要复制用例的名称信息，即使是鼠标长按选中用例名称也判定为点击事件了，接口测试列表中并没有这个问题。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/185520530-87a21cf9-9452-4929-bd73-4212e1729f6f.png)

**Comment by xulinde** [comment]
v1.20.13-lts已优化～
