### ISSUE TITLE
[FEATRUE]接口场景中导入 JMeter 文件，JMeter 中的前置处理器BeanShell PreProcessor未解析到前置脚本中

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#17103]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

接口场景中导入 JMeter 文件，JMeter 中的前置处理器BeanShell PreProcessor未解析到 MeterSphere 的前置脚本中

### 重现步骤

1.将jmx文件（附件已上传）导入到MeterSphere
<img width="871" alt="image" src="https://user-images.githubusercontent.com/104493699/185538786-7d917484-26ff-4ccc-953f-b71d1c6e7d6d.png">
2.BeanShell PreProcessor脚本不在前置脚本中
![image](https://user-images.githubusercontent.com/104493699/185538999-ac83cac5-ef38-488f-ba82-8b27512a9de4.png)

jmx文件可以联系我

**Comment by zhangzhaox** [comment]
调整原始脚本 使用JSR223组件即可
