### ISSUE TITLE
[BUG]通过快捷调试另存为新用例报错

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#1710]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.7.3
**Bug 描述**
简要描述您碰到的问题
通过快捷调试另存为新用例报错
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37541195/112453566-cd0f3680-8d92-11eb-992f-d128eeace680.png)

**Comment by Dyc2333** [comment]
可以邮件diyuchen@esunny.cc，我会回复详细错误日志

**Comment by xulinde** [comment]
未复现该问题，建议您升级到v1.8再试下

**Comment by Dyc2333** [comment]
问题偶发无法复现，日志文件已发 @shenkaibo @shenkaibo
