### ISSUE TITLE
[BUG]定时任务加到测试场景上，可以发送消息，但是定时任务加到测试计划上，消息就不发送了

### ISSUE THREAD

**Issue by zhang-hui123** [metersphere/metersphere#17108]
### 联系方式

70242128@qq.com

### MeterSphere 版本

 v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

1、在测试计划里添加了接口场景，并设置了定时任务，然后添加了微信消息机器人，但是测试定时执行了，机器人没有发送消息
2、手动执行的可以发送成功
3、定时任务加到测试场景上，可以发送消息

### 重现步骤

1、在测试计划里添加了接口场景，并设置了定时任务，然后添加了微信消息机器人，但是测试定时执行了，机器人没有发送消息
2、手动执行的可以发送成功
3、定时任务加到测试场景上，可以发送消息

### 附加信息

![1](https://user-images.githubusercontent.com/86909327/185543099-22e58eee-5c43-4c7a-8a15-6501afa618b9.jpg)
![2](https://user-images.githubusercontent.com/86909327/185543105-cfb261a8-d7e3-48cc-977b-6381a0aea8d8.jpg)

**Comment by youliyuan-fit2cloud** [comment]
你好，和你确认一下，测试计划的定时任务消息通知是否在下图中设置了？
ps：项目管理-消息设置里面的通知仅是手动执行的消息通知。
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/54612864/185731688-0614d11a-ec99-4928-af3b-0c88dc95ebad.png">
