### ISSUE TITLE
[BUG]在接口自动化-场景测试中，无法通过后置脚本将数据写入 Metersphere 环境变量

### ISSUE THREAD

**Issue by liufei20151013** [metersphere/metersphere#17102]
### 联系方式

15505608861

### MeterSphere 版本

v1.20.12-lts-2297374a

### 使用外置数据库

否

### 问题描述

在接口自动化-场景测试中，无法通过后置脚本将获取的数据写入 Metersphere 环境变量，而是将参数名写入环境变量的参数值。
<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/15103510/185532336-e1afb3ea-3344-467a-a813-710a4fee173a.png">
<img width="1437" alt="图片" src="https://user-images.githubusercontent.com/15103510/185532256-572f0461-1124-4eef-b840-d6b59f61921a.png">

### 重现步骤

不想写

**Comment by youliyuan-fit2cloud** [comment]
你好，请参考下图方式写入环境变量
<img width="851" alt="image" src="https://user-images.githubusercontent.com/54612864/185730934-60650257-eefb-4eb7-94cf-eae6fe097b08.png">
