### ISSUE TITLE
[BUG]调用接口成功后，返回报文中某个返回值是100.00，推荐断言显示的是100，断言判断的是100.0

### ISSUE THREAD

**Issue by zhang-hui123** [metersphere/metersphere#17107]
### 联系方式

70242128@qq.com

### MeterSphere 版本

 v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

调用接口成功后，返回报文中某个返回值是100.00，推荐断言显示的是100，断言判断的是100.0

### 重现步骤

调用接口成功后，返回报文中某个返回值是100.00，推荐断言显示的是100，断言判断的是100.0

### 期待的正确结果

应返回100.00

### 附加信息

![3](https://user-images.githubusercontent.com/86909327/185542479-85b6d421-cf1b-448e-8512-35c4ce30b899.jpg)
![4](https://user-images.githubusercontent.com/86909327/185542510-b736f540-5b42-42ed-b837-17f227cb5c5f.jpg)
![5](https://user-images.githubusercontent.com/86909327/185542560-a6b2bef4-403e-4494-9a56-b92d9cce13dc.jpg)

**Comment by zhang-hui123** [comment]
![6](https://user-images.githubusercontent.com/86909327/185542696-c5c1d240-90bb-4afa-9499-8391137d5c7b.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，计划下个版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/186364200-31a7db7b-89c7-4621-b562-e4b60e3ac669.png)
推荐Jsonpath结果已修改，jsonpath的断言结果是JMeter的缺陷，暂时没有解决方案。
