### ISSUE TITLE
[QUESTION]执行性能测试报错：Check node-controller /etc/hosts, `127.0.0.1 ${hostname}` must be contained. Please delete the report and rerun.

### ISSUE THREAD

**Issue by abcanqi** [metersphere/metersphere#1711]
提示信息为：Check node-controller /etc/hosts, `127.0.0.1 ${hostname}` must be contained. Please delete the report and rerun.
我尝试进入 node-controller 容器，修改了hosts文件为：
```vim
127.0.0.1 localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.22.0.2      a50b9e5d03bc
```
但是还是不能解决我的问题

**Comment by liuruibin** [comment]
1.8 版本改成了host网络来启动jmeter容器，需要在部署node-controller的机器上修改hosts

**Comment by abcanqi** [comment]
> 1.8 版本改成了host网络来启动jmeter容器，需要在部署node-controller的机器上修改hosts

谢谢你的回答，请教一下我该如何修改，才可以满足执行的条件呢？

**Comment by abcanqi** [comment]
我当前服务器的 `/etc/hosts` 配置文件为：
```vim
127.0.0.1       localhost
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.120.20.219 gitlab.lenovo.com
10.110.149.133 nginx111
```
并且修改完成后，通过`msctl restart`命令重启了服务，但是执行时依然报同样的错误。

**Comment by liuruibin** [comment]
我的环境是这样的
![image](https://user-images.githubusercontent.com/23045261/112459891-49a51380-8d99-11eb-94f5-b50644919a2c.png)
我的hosts是这样的
![image](https://user-images.githubusercontent.com/23045261/112460074-7c4f0c00-8d99-11eb-995f-6f763132263b.png)

**Comment by abcanqi** [comment]
> 我的环境是这样的
> ![image](https://user-images.githubusercontent.com/23045261/112459891-49a51380-8d99-11eb-94f5-b50644919a2c.png)
> 我的hosts是这样的
> ![image](https://user-images.githubusercontent.com/23045261/112460074-7c4f0c00-8d99-11eb-995f-6f763132263b.png)

谢谢，按照你的提示，我把`hostname`配置进 `/etc/hosts`后，就可以执行性能测试了。


#### 遇到相同问题的同学，可以进行如下配置
1. 在部署 `node-controller` 的机器上，使用`hostname`命令获取主机名
```shell
[root@nginx metersphere-release-v1.8.0]# hostname
nginx.novalocal
```

2. 将获取到的主机名`nginx.novalocal`配置到 `/etc/hosts` 文件中，配置完成效果如下：
* 配置前
  ```vim
  127.0.0.1       localhost
  ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
  10.110.149.133 nginx111
  ```
* 配置后
  ```vim
  127.0.0.1       localhost
  127.0.0.1       nginx.novalocal
  ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
  10.110.149.133 nginx111
  ```
