### ISSUE TITLE
[FEATURE] bug与需求自动关联

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#1712]
**请描述您的需求或者改进建议.**
在需求与用例有关联的前提下，MS创建的bug能自动跟需求关联。这样每个需求对应的测试，及由测试发现的bug都与该需求关联在一起。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
v1.8已实现该功能

**Comment by xyziven** [comment]
@xulinde 貌似还不支持bug与需求的自动关联
