### ISSUE TITLE
[BUG]测试跟踪-功能用例的脑图模式下，在主题A为编辑状态的时候点击主题B，有时候会把主题B的内容删掉

### ISSUE THREAD

**Issue by liuli02** [metersphere/metersphere#17129]
### MeterSphere 版本

v1.18.0-82ba1b94

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例的脑图模式下，在主题A为编辑状态的时候点击主题B，有时候会把主题B的内容删掉

### 重现步骤

测试跟踪-功能用例的脑图模式下，在主题A为编辑状态的时候点击主题B，有时候会把主题B的内容删掉

### 期待的正确结果

不要把主题B的内容删掉

**Comment by liuli02** [comment]
[

https://user-images.githubusercontent.com/94596144/185571832-f590ab85-8c5e-4fac-863f-7e4f9b667996.mp4

](url)

**Comment by youliyuan-fit2cloud** [comment]
我们最新版本没有这个问题，你目前的v1.18版本有点旧了，建议升级到最新的1.20.12-lts版本试试看吧。
ps：显示器下面的玩偶很可耐~
