### ISSUE TITLE
建议移除接口测试中保存功能，防止手误

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1713]
**请描述您的需求或者改进建议.**
V1.8

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/33744331/112568113-ef4d9680-8e1c-11eb-8d45-b8d987f9f2b5.png)

**Comment by zyyfit** [comment]
您好，能具体描述一下吗？没理解您的意思
