### ISSUE TITLE
[BUG]基于jmeter-grpc-request开发的ms插件，运行时会报出Unable to execute protoc binary

### ISSUE THREAD

**Issue by ZengminLiu** [metersphere/metersphere#17137]
### 联系方式

微信号：18817464652

### MeterSphere 版本

v1.20.9

### 使用外置数据库

否

### 问题描述

基于jmeter-grpc-request开发的ms插件，运行时会报出Unable to execute protoc binary。经过排查后发现，原因是docker镜像中使用的Linux版本为alpine linux，不支持运行exe。

### 重现步骤

将插件jar上传后调试，jar包可以联系我提供。

### 期待的正确结果

使docker中的linux版本支持运行exe

### 相关日志输出

```shell
java.io.IOException: Cannot run program "/root/protocjar5555376202649058674/bin/protoc.exe": error=2, No such file or directory
（并非文件不存在，实际上是protoc.exe不能在alpine linux系统中运行才报错）
```

### 附加信息

![2e097fb9805113867200073c06b7386](https://user-images.githubusercontent.com/44204401/185578046-decc6d47-24a8-4dfe-8181-65cb29bb65e8.png)
![701cac9a5e3f0fad6f2607962039bd4](https://user-images.githubusercontent.com/44204401/185578081-4a8feb3f-77f0-474e-867d-51649b79bbeb.png)

**Comment by youliyuan-fit2cloud** [comment]
你好， 我们的镜像基于linux系统的，exe是windows里面执行，暂时没办法支持。有用户尝试过自己做windows的镜像，可以试试。

**Comment by youliyuan-fit2cloud** [comment]
> 



> 请问是否有制作镜像的教程或者文档？镜像制作完成后如何部署使用？
> 
> > 你好， 我们的镜像基于linux系统的，exe是windows里面执行，暂时没办法支持。有用户尝试过自己做windows的镜像，可以试试。

抱歉，还没有文档。如果后续有相关文档会在官网文档中更新。

**Comment by peterZhang000** [comment]
alpine linux--这个是系统的问题，可以按照对应的类库就ok了，apk add glibc-2.35-r1.apk  apk add gcompat 并且版本给到3.11.4  就ok已经调试完成
