### ISSUE TITLE
[BUG]【系统设置】-【系统】-【用户组与权限】页面，系统管理员的【设置权限】处，【项目设置】功能菜单下的【用户组与权限】多余

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17147]
### 联系方式

lipan@fzy.welcom.work

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

【系统设置】-【系统】-【用户组与权限】页面，系统管理员【设置权限】时，【项目设置】功能菜单下的【用户组与权限】，即使勾选也不再【项目设置】下出现，这是不是多余的，是不是可以删掉。
![image](https://user-images.githubusercontent.com/104960608/185593341-ffb86478-8229-4fc1-8701-7ba364467117.png)

### 重现步骤

1.进入【系统设置】-【系统】-【用户组与权限】页面，找到【系统管理员】，点击【设置权限】
2.勾选【项目设置】功能菜单下的【用户组与权限】
3.在【项目设置】菜单看是否有【用户组与权限】这个二级菜单。

**Comment by 2lipan** [comment]
在【系统设置-系统-用户组与权限】页面，搜索框中输入【系统管理员】，点击【设置权限】，发现【用户组与权限】在【项目设置】菜单下，但是【项目设置】下【用户组与权限】这个二级菜单了是没有的，已经被移除了。
![image](https://user-images.githubusercontent.com/104960608/185836533-ff0d1cff-1522-4c16-820a-a26a127cf971.png)

**Comment by 2lipan** [comment]
在【系统设置】-【系统】-【用户组与权限】处，将项目管理员的【项目设置】-【用户组与权限】都勾上，但是【项目设置】-【用户组与权限】页面，这几个按钮还是显示无权限。
![image](https://user-images.githubusercontent.com/104960608/185886650-526b8889-a513-4c11-8f0a-4c31352b8814.png)

![image](https://user-images.githubusercontent.com/104960608/185886144-5fd1c7cc-921b-48d8-99d6-9cfc26a6e819.png)

**Comment by youliyuan-fit2cloud** [comment]
这几个是系统自带的用户组，用户自建的用户组可以操作-编辑等操作。
