### ISSUE TITLE
[FEATURE] 测试跟踪-缺陷管理：查看缺陷详情每次就需要点编辑希望有个预览态

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17144]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

测试跟踪-缺陷管理：查看用例详情每次就需要点编辑希望有个预览态

### 请描述你建议的实现方案

希望在查看bug的时候有个预览态，（主要了解bug修改进度之类的）

**Comment by luty2018** [comment]
需求反馈给正友
