### ISSUE TITLE
[FEATURE]UI测试--参数化配置及断言希望可以断言数据库里面查询的数据

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17146]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

UI测试--参数化配置及断言希望可以断言数据库里面查询的数据

### 请描述你建议的实现方案

参数化配置及断言希望可以断言数据库里面查询的数据

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/185595041-b2913a15-3548-4c67-a72f-8ca750b4ca38.png)

**Comment by xhy12** [comment]
客户背景：ui测试过程希望将页面操作的业务数据 通过数据库里面实际查询出来的数据做对比断言  确保数据测试准确性

**Comment by Hyyfit** [comment]
这个需要等UI和接口的打通，打通后可以支持
