### ISSUE TITLE
[FEATURE]我的工作台：缺陷统计图表希望可以增加配置项，比如按缺陷修改人、缺陷上报周期做筛选统计

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17145]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

背景：日常使用过程需要针对提交的缺陷做数据分析优化研发流程，（比如为什么会产生这么多缺陷，是否研发代码质量有问题等等）

我的工作台：缺陷统计图表希望可以增加配置项，比如按缺陷修改人、缺陷上报周期做筛选统计

### 请描述你建议的实现方案

缺陷统计图表希望可以增加配置项，比如按缺陷修改人、缺陷上报周期做筛选统计

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/185594212-cc2c5c7f-f60c-4f58-bfb6-74b4aa92e20d.png)

**Comment by luty2018** [comment]
需求录入战区TAPD，排期要求反馈给正友
