### ISSUE TITLE
[BUG]【工作台】-【我的仪表盘】-【我创建的缺陷】展示状态只有【新建】，【测试跟踪】-【缺陷管理】处的【已解决】和【已关闭】状态也被当做【新建】状态被展示

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17150]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

【测试跟踪】-【缺陷管理】处的【已解决】和【已关闭】状态，在【工作台】-【我创建的缺陷】全部被当成【新建】状态被展示。
![image](https://user-images.githubusercontent.com/104960608/185598908-452a1330-7599-42b2-89ab-98e236342a81.png)

![image](https://user-images.githubusercontent.com/104960608/185599489-6f2fae17-7e0c-486a-a2c8-42c9cc79f716.png)

### 重现步骤

1.在【测试跟踪】-【缺陷管理】处新建【已解决】和【已关闭】状态，或者将测试用例的【新建】状态改为【已解决】【已关闭】状态
2.看看【工作台】-【我的仪表盘】-【我创建的缺陷】展示的效果都为【新建】

**Comment by youliyuan-fit2cloud** [comment]
v2.1.1版本中已修复该问题。
