### ISSUE TITLE
[BUG]功能用例，导出用例模板（表格文件），Office打开无法查看批注

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17152]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.10

### 使用外置数据库

否

### 问题描述

功能用例，导出用例模板（表格文件），Office打开无法查看批注，wps打开可以
1.office打开
<img width="696" alt="9399b33d8090409b4525bb301cd5c54" src="https://user-images.githubusercontent.com/103627487/185602202-599da0b6-69f3-425d-9dc3-f96fc671e00a.png">
2.wps打开
![07e5fad1ecc948af752b89f59e7a9ff](https://user-images.githubusercontent.com/103627487/185602284-036757f4-5aed-45ee-b7bb-d8da189be2d6.jpg)

### 重现步骤

功能用例，导出用例模板（表格文件），Office打开，查看批注
![image](https://user-images.githubusercontent.com/103627487/185602390-1967c848-bd8d-4d1a-bb13-af7a45f758eb.png)

### 期待的正确结果

office打开也可以正常查看批注

**Comment by youliyuan-fit2cloud** [comment]
你好，office是啥版本？

**Comment by meijieDouDou** [comment]
Microsoft Office 2016

**Comment by meijieDouDou** [comment]
Microsoft Office 2019 也不行，也看不了批注

**Comment by youliyuan-fit2cloud** [comment]
v1.20.12-lts中已修复，升级一下。
