### ISSUE TITLE
[BUG]在ms容器内运行二进制文件出现：not found

### ISSUE THREAD

**Issue by WYM201** [metersphere/metersphere#17159]
### 联系方式

微信号：18817464652

### MeterSphere 版本

v1.20.9

### 使用外置数据库

否

### 问题描述

在ms容器内运行二进制文件出现not found的问题，排查后发现是因为docker镜像使用了alpine linux，不支持运行二进制文件

### 重现步骤

将某个可在linux下运行的二进制文件复制进容器中，进入ms容器，运行该文件，会发现无法运行

### 期待的正确结果

希望修改dockerfile或者别的什么，让容器内支持二进制文件的运行

### 相关日志输出

```shell
/bin/sh: /wym/protoc: not found
```

### 附加信息

在自己的linux服务器上（版本为redhat7）运行一个二进制文件，结果如下：
![2 1JCJ$ZHK O3AWR81A@PT9](https://user-images.githubusercontent.com/62410391/185738524-f72eb7c0-225b-4988-bc88-30aa2808be93.png)
用docker cp将该二进制文件复制到ms-server容器中运行，报错not found:
![0NM_I(XQX54PY03C8%JI$C7](https://user-images.githubusercontent.com/62410391/185738703-2a8cd4c4-5bfc-4431-b981-af580044cf6b.png)

**Comment by liqiang-fit2cloud** [comment]
Hi,
MeterSphere用的是原生alpine linux，未做任何更改。
我们测试了一些二进制文件，都能正常运行。
麻烦确认一下你的二进制文件权限什么的对不对，或者架构对不对，x86还是arm的，或者是不是要有其他依赖。

**Comment by WYM201** [comment]
> Hi, MeterSphere用的是原生alpine linux，未做任何更改。 我们测试了一些二进制文件，都能正常运行。 麻烦确认一下你的二进制文件权限什么的对不对，或者架构对不对，x86还是arm的，或者是不是要有其他依赖。

确认过不是权限或者架构的问题，具体的二进制文件可以在https://github.com/protocolbuffers/protobuf/releases 下载
![ace829bf2afebd2c7e21410b67be1f9](https://user-images.githubusercontent.com/62410391/185905358-eedc55c9-aed3-440f-8dd0-d241ed95f04b.png)
选择这个版本，解压选择/bin/protoc这个文件，该文件在linux上可以正常运行，在ms容器中不可以

**Comment by liqiang-fit2cloud** [comment]
看起来protoc在alpine linux运行确实有问题，建议你去protoc社区或者alpine社区问一下，或者关注这些线索。
https://stackoverflow.com/questions/64447731/protoc-not-found-on-an-alpine-based-docker-container-running-protocol-buffers
https://github.com/bazelbuild/rules_closure/issues/228

MeterSphere运行只依赖jdk，原生alpine linux已满足需要。如果你需要在ms容器里运行其他程序，请自行安装其他依赖或者自己构建镜像。

**Comment by WYM201** [comment]
> 看起来protoc在alpine linux运行确实有问题，建议你去protoc社区或者alpine社区问一下，或者关注这些线索。 https://stackoverflow.com/questions/64447731/protoc-not-found-on-an-alpine-based-docker-container-running-protocol-buffers [bazelbuild/rules_closure#228](https://github.com/bazelbuild/rules_closure/issues/228)
> 
> MeterSphere运行只依赖jdk，原生alpine linux已满足需要。如果你需要在ms容器里运行其他程序，请自行安装其他依赖或者自己构建镜像。

请问自行构建镜像后，换掉离线安装包中原先的镜像再进行部署，这个方案是否可行？有没有相应的替换镜像的教程或者手册？

**Comment by liqiang-fit2cloud** [comment]
这是Metersphere的Dockerfile，你换个基础镜像构建就行吧。
https://github.com/metersphere/metersphere/blob/dev/Dockerfile
https://github.com/metersphere/fabric8-java-alpine-openjdk11-jre/blob/master/Dockerfile

**Comment by WYM201** [comment]
> 这是Metersphere的Dockerfile，你换个基础镜像构建就行吧。 https://github.com/metersphere/metersphere/blob/dev/Dockerfile https://github.com/metersphere/fabric8-java-alpine-openjdk11-jre/blob/master/Dockerfile

感谢指导，只是我还不太明白，自行镜像之后，如何将镜像应用于ms服务器的部署呢？

**Comment by liqiang-fit2cloud** [comment]
在安装目录的这个文件里改成你自己的镜像吧。
https://github.com/metersphere/installer/blob/main/metersphere/docker-compose-server.yml#L4

**Comment by WYM201** [comment]
> 在安装目录的这个文件里改成你自己的镜像吧。 https://github.com/metersphere/installer/blob/main/metersphere/docker-compose-server.yml#L4

我选择的是离线安装，是否需要替换安装包中的其他内容？

**Comment by WYM201** [comment]
> 在安装目录的这个文件里改成你自己的镜像吧。 https://github.com/metersphere/installer/blob/main/metersphere/docker-compose-server.yml#L4

请问这部分代码是不开源吗？源码里没有，build也不行。
![6ceb0adcc50e6bb30a1e89c06872fa7](https://user-images.githubusercontent.com/62410391/188045013-b594edf3-4dbe-4e9a-8b65-65f9c6bc8255.png)
