### ISSUE TITLE
[BUG]【测试跟踪】-【测试计划】页面，点击列表某一测试计划，切到【报告统计】页面，发现左侧菜单处出现样式问题

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17151]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

【测试跟踪】-【测试计划】页面，点击列表某一测试计划，切到【报告统计】页面，发现左侧菜单处出现样式问题
![image](https://user-images.githubusercontent.com/104960608/185601051-24e039ba-c9be-471f-8618-8b6c68f50044.png)

### 重现步骤

1.进入【测试跟踪】-【测试计划】页面，点击某一测试计划
2.点击【报告统计】页面，发现左侧菜单处有样式问题

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
