### ISSUE TITLE
[BUG]JMX中PortNumber没有被导入

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1716]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.0
**Bug 描述**
简要描述您碰到的问题
JMeter中设置HTTP Request中的Port number为自定义变量，没有被导入进Metersphere中
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72964047/112572019-3a1edc80-8e24-11eb-93e8-ec036d5d0a87.png)
![image](https://user-images.githubusercontent.com/72964047/112572079-60dd1300-8e24-11eb-892f-9d4452d8662d.png)

**Comment by zyyfit** [comment]
v1.8.0已修改了导入方式，建议您升级到v1.8.0再试一下
