### ISSUE TITLE
[FEATURE]接口测试导入页面显示优化

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#17167]
### MeterSphere 版本

2.0

### 请描述您的需求或者改进建议

浏览器：chrome
显示器分辨率：MacBook Pro 13.3英寸(2560 × 1600)

1、建议接口导入页面中数据格式选项间隔可以更大一些。
目前看起来上一个 radio 的文本与下一个radio完全连接在一起了，非常不美观。

2、建议接口导入页面弹出时，可以根据主流分辨率尽可能地调整显示位置，并在一个完整的屏幕内显示，以便减少不必要的操作。
目前的显示效果来看至少会增加一步滚动操作，也不够简洁。

### 请描述你建议的实现方案

![6591661091576_ pic](https://user-images.githubusercontent.com/46042812/185796210-9a0b6d30-05a5-473e-bddc-1d2f8fd84dc6.jpg)
![6601661092301_ pic](https://user-images.githubusercontent.com/46042812/185796212-4babd151-bb80-4d5c-a80c-486556c4e7e6.jpg)

**Comment by luty2018** [comment]
我们尽快优化
