### ISSUE TITLE
[FEATURE]模块创建和管理

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1717]
**请描述您的需求或者改进建议.**
现在导入的时候需要指定模块，如果没有必须手动创建一个。

**请描述你建议的实现方案**
1.8.0之前不需要指定一个模块，可以仍然用这种方式导入到根目录。或者在选择模块的下拉框中输入一个没有的模块名的方式创建一个新的模块。

**Comment by xulinde** [comment]
1.9.0已优化，模块不是必选项
