### ISSUE TITLE
[BUG]JMeter脚本导入到MS中，执行时没有解析到端口号

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#17184]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

JMeter脚本导入到MS中，执行时没有解析到端口号

### 重现步骤

1.jmx执行时可以在请求内容中看到端口号
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/104493699/185836863-b1ea97d7-0f3a-4420-8aad-af9c6bd06d96.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/104493699/185836835-b4d9bfad-6520-4d70-af12-8417f2aa87d8.png">
2.导入到MS执行时看不到端口号
<img width="498" alt="image" src="https://user-images.githubusercontent.com/104493699/185837296-1df2e60b-bf1b-4b98-a958-5791103aae2b.png">

**Comment by zyyfit** [comment]
jmeter脚本里环境如果是变量的话，导入ms应该不会带地址吧，你需要自己在环境中配置请求地址，然后引用环境
