### ISSUE TITLE
[BUG]测试计划中添加了接口自动化的场景，对该计划设置定时任务，并未执行

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1719]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版1.8
**Bug 描述**
简要描述您碰到的问题

测试计划中添加了接口自动化的场景，对该计划设置定时任务，并未执行，查看报告也未生成

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
收到邮件，生成接口自动化测试报告

**截图**
如果有截图，请附上截图.
定时任务中显示执行了，但报告中并没有，还是我之前测试的报告。接口报告中也没有。
![image](https://user-images.githubusercontent.com/22139528/112596427-c5a96500-8e46-11eb-9365-28639329f519.png)
![image](https://user-images.githubusercontent.com/22139528/112596479-d659db00-8e46-11eb-9d88-7af63e19c2f3.png)

**Comment by zyyfit** [comment]
测试计划定时任务执行的问题将在v1.8.1修复，感谢您的关注
