### ISSUE TITLE
[BUG]从全部测试计划的页面点击某个自己建的测试计划，去添加东西，会报权限错误

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#1720]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版1.8
**Bug 描述**
简要描述您碰到的问题

从全部测试计划的页面点击某个自己建的测试计划，去添加东西，会报权限错误

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/22139528/112596665-1456ff00-8e47-11eb-8d74-67542d90eb6e.png)
![image](https://user-images.githubusercontent.com/22139528/112596707-2042c100-8e47-11eb-912f-5d9089ac2c8e.png)

**Comment by zyyfit** [comment]
能否说一下您使用的这个账号有几个组织和工作空间的权限？分别是什么角色？
