### ISSUE TITLE
[BUG]执行SQL，ROUND函数保留小数，未生效。

### ISSUE THREAD

**Issue by dengbing-mm** [metersphere/metersphere#17216]
### 联系方式

交流群43群 邓兵 dengbing@dcmp.cn

### MeterSphere 版本

v1.20.5-lts-9fe3acfd

### 使用外置数据库

否

### 问题描述

执行SQL，ROUND函数保留小数，未生效。
在Navicat中执行是可以的，在MS执行未生效

### 重现步骤

执行一条查询SQL，并且使用ROUND函数，查看是否保留正确

### 期待的正确结果

执行一条查询SQL，并且使用ROUND函数，正确保留所需要的小数

### 相关日志输出

```shell
无
```

### 附加信息

![企业微信截图_1661155561532](https://user-images.githubusercontent.com/84009197/185876786-43b3d62b-414a-4a0f-90c9-7e7ea6d0371a.png)
![企业微信截图_16611555739248](https://user-images.githubusercontent.com/84009197/185876803-e25b233b-a164-42bc-b28f-16e438984401.png)

**Comment by zyyfit** [comment]
jmeter也是这样的，如果查询的数字本身是不到2位的小数，就是保留1位，如果是超过2位的，就是正常保留2位，
我在ms和jmeter里都试了，是一样的效果，你试试2位以上的小数是不是正常的吧
![image](https://user-images.githubusercontent.com/73461316/185968914-be438437-96cc-46a3-88cb-088056b2fdec.png)
![image](https://user-images.githubusercontent.com/73461316/185968965-f1ad516b-2f59-42c1-b3cb-05a389d0ef9b.png)
