### ISSUE TITLE
[BUG]1.8 版本 用例添加了评论，但编辑的时候看不到

### ISSUE THREAD

**Issue by jaqueliao** [metersphere/metersphere#1721]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8
**Bug 描述**
简要描述您碰到的问题
用例添加了评论，但编辑的时候看不到
**Bug 重现步骤**
1.  给某个用例添加评论（编辑时或者评审时添加）
2. 进入用例管理，编辑此用例，评论未显示出来

**期待的正确结果**
正确情况下应该是什么样的？
正常展示所有评论

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，这个问题计划在v1.8.1版本修复

**Comment by zyyfit** [comment]
最新版1.8.2已修复
