### ISSUE TITLE
CSV文件地址错误，导致无法找到文件

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1722]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33744331/112601100-00160080-8e4d-11eb-9d76-86b0c52e3274.png)

**Comment by zyyfit** [comment]
感谢反馈，这个问题计划在v1.8.1版本修复
