### ISSUE TITLE
[BUG]接口自动化-场景-变更记录，查询数据过大导致系统崩溃

### ISSUE THREAD

**Issue by rechin-zhou** [metersphere/metersphere#17232]
### MeterSphere 版本

v1.19.0-1727df14

### 使用外置数据库

否

### 问题描述

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/39108921/185902240-148424da-dd92-4c09-ab13-ea74ce5c062b.png">

数据过大，导致查询崩溃。是否可以考虑分页查询

### 重现步骤

1. 接口自动化场景中进行多次编辑，（变更记录过多）
2. 点击变更记录

出现服务器崩溃：Bad Gateway

### 期待的正确结果

可能是我们服务器配置不高的原因，但是这儿还是可以优化一下

### 相关日志输出

```shell
拿不到
```

**Comment by youliyuan-fit2cloud** [comment]
你好，这个v1.19.0-1727df14 版本有点旧了，建议升级到最新的1.20.12-lts版本试试。
