### ISSUE TITLE
[BUG]linux v2.0.1离线安装部署不上

### ISSUE THREAD

**Issue by chenjiadong19951207** [metersphere/metersphere#17240]
### 联系方式

QQ：729208005

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

[MeterSphere Log]: ======================= 开始安装 ======================= 
[MeterSphere Log]: 检测到 Docker 已安装，跳过安装步骤 
[MeterSphere Log]: 启动 Docker  
[MeterSphere Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
[MeterSphere Log]: 加载镜像 
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms1-jdk11
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/kafka:3.2.0
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v2.0.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-data-streaming:v2.0.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v2.0.1
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.28
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/prometheus:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/redis:6.2.6
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/seleniarm-grid-all:4.1.4-20220519
[MeterSphere Log]: 启动服务 

The HOSTNAME variable is not set. Defaulting to a blank string.
Removing network metersphere_ms-network
Network metersphere_ms-network not found.
Removing volume metersphere_ms-conf
Volume metersphere_ms-conf not found.
Removing volume metersphere_ms-logs
Volume metersphere_ms-logs not found.
Removing volume metersphere_ms-data
Volume metersphere_ms-data not found.
Removing volume metersphere_ms-mysql-data
Volume metersphere_ms-mysql-data not found.
Removing volume metersphere_ms-prometheus-data
Volume metersphere_ms-prometheus-data not found.
Removing volume metersphere_ms-prometheus-conf
Volume metersphere_ms-prometheus-conf not found.
Removing volume metersphere_ms-redis-data
Volume metersphere_ms-redis-data not found.

The HOSTNAME variable is not set. Defaulting to a blank string.
Creating network "metersphere_ms-network" with driver "bridge"
Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-02da5351fca1 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))

Name   Command   State   Ports
------------------------------
======================= 安装完成 =======================

请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
您可以使用命令 'msctl status' 检查服务运行情况.

### 重现步骤

install.conf更改

# 数据库密码
MS_MYSQL_PASSWORD=之前自己在docker安装的mysql5.7的密码；其它项无变动

**Comment by liuruibin** [comment]
https://www.cnblogs.com/pxblog/p/14955420.html
这里有一个处理方式
