### ISSUE TITLE
[FEATURE]建议增加用例排序功能

### ISSUE THREAD

**Issue by PolkFan** [metersphere/metersphere#1724]
**请描述您的需求或者改进建议.**
在用例管理中建议增加用例排序功能。目前用例仅可按id、更新时间排序，而在补充、更新后排列顺序就不可控，无法按照测试流程正常排列，添加至测试计划中也是同样的顺序。

**请描述你建议的实现方案**
建议在管理用例列表中增加拖动排序功能

**Comment by xulinde** [comment]
1.10版本已支持

**Comment by PolkFan** [comment]
请问测试跟踪的用例如何操调整用例顺序呢？没找到调整排序的方法诶
