### ISSUE TITLE
[BUG]metersphere上的接口定义导出为swagger后，再导入metersphere，有参数丢失了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17243]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

metersphere上的接口定义导出为swagger后，再导入metersphere，有参数丢失了

### 重现步骤

1.metersphere手动创建接口定义，设置请求参数
![image](https://user-images.githubusercontent.com/88763608/186056668-5ce772ee-0bf8-4e43-8de1-9d4df703966a.png)
2.导出为swagger
3.讲metersphere原本的接口定义删除掉，再导入上一步导出的swagger文件
4.结果少了之前定义的参数
![image](https://user-images.githubusercontent.com/88763608/186057492-af86b6aa-da3e-466c-95dd-b5032bb9f105.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20 和 2.1 都已修复
