### ISSUE TITLE
[BUG]idea插件不支持导出带JSONObject的接口

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17256]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

idea插件最新版不支持导出带JSONObject的接口
idea版本：2021的版本
idea插件版本：1.0.9

### 重现步骤

1.接口带JSONObject
2.点击export to metersphere
3.页面报错JSONObject is in unnamed module of loader
![f7bc5b499570c964dc9841269493902](https://user-images.githubusercontent.com/88763608/186063883-823e1036-6547-4cf0-9c23-1e60a2b31e88.jpg)

**Comment by zrfit** [comment]
该问题已修复，插件下载地址：https://plugins.jetbrains.com/
