### ISSUE TITLE
[BUG]idea插件不支持idea community 2022.2的版本

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17255]
### 联系方式

蒋林峰

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

idea插件不支持idea community 2022.2的版本

### 重现步骤

1.idea安装MS最新的插件
2.点击export to metersphere
3.页面报错
export to metersphere fail! Cannot invoke psitype.getcanonicaltext() because the return value is null 
4.已跟大老师沟通，可能是idea插件使用的 api 在 idea 2022.2 community上面变更了导致的 bug，老师说下个版本支持2022.2 idea

### 期待的正确结果

期待能支持2022.2版本

**Comment by zrfit** [comment]
该问题已修复，插件下载地址：https://plugins.jetbrains.com/
