### ISSUE TITLE
[BUG]任务状态本就是关闭，想要打开，点击后，仍然弹出“关闭任务”的弹框。

### ISSUE THREAD

**Issue by Brucise** [metersphere/metersphere#17263]
### 联系方式

317084719@qq.com

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

任务状态本就是关闭，想要打开，点击后，仍然弹出“关闭任务”的弹框。
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/18108038/186076203-8bd91c15-50ce-46bc-97c4-bf1eecc118fe.png">

### 重现步骤

1、新建定时同步任务。
2、关闭定时同步任务。
3、打开定时同步任务。

### 期待的正确结果

弹出“关闭任务”的弹框。

**Comment by xulinde** [comment]
这里提示信息有点问题，不影响正常使用，您点击确定就可以打开任务。

**Comment by xulinde** [comment]
v2.1.0已优化提示，建议您升级下～
