### ISSUE TITLE
[FEATURE]mock服务，不能支撑json格式的参数正则匹配，只能写死等于某一个值

### ISSUE THREAD

**Issue by luoxiangfei** [metersphere/metersphere#17269]
### MeterSphere 版本

v1.20.12-lts 

### 请描述您的需求或者改进建议

mock服务中query和rest相关参数以及body中的data和urlencoded方式都能够加入当前参数的匹配值，但是json格式不行，正常情况下，大部分接口还是json格式的，所以需要json能够使用参数支持正则匹配

### 附加信息

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/46469855/186082394-4a63c35d-df5f-4ed0-8120-2de7632b87d4.png">

**Comment by Hyyfit** [comment]
可以做的，这个我们调研一下具体的实现方案。

**Comment by leoxyz** [comment]
我们也有这个需求，计划做吗？在哪个版本发布？

**Comment by Hyyfit** [comment]
还在规划中，你可以在交流群里加一下我的微信，具体沟通一下这个需求。
<img width="318" alt="image" src="https://user-images.githubusercontent.com/95834771/192931511-5d439909-1c30-45f2-adf3-18f510af1909.png">
