### ISSUE TITLE
[FEATURE]压测报告-监控详情数据保存时长优化

### ISSUE THREAD

**Issue by xkmyf** [metersphere/metersphere#17262]
### MeterSphere 版本

v1.20.12-lts-2297374a

### 请描述您的需求或者改进建议

性能测试-报告-监控详情，这部分监控数据默认保存200小时（从之前反馈的问题中得知 https://github.com/metersphere/metersphere/issues/16893 ），而系统页面或操作文档中并没有对此进行说明。
在项目设置中也有对报告定期清理的相关配置，这两个地方保存策略不同造成数据保存不完整，希望能对报告数据完整保存和统一控制保存时长。
![image](https://user-images.githubusercontent.com/18514555/186066582-a8f82c56-dd91-40bb-aee0-97915f9c2a1d.png)

**Comment by liuruibin** [comment]
prometheus 的保留时长是启动时配置的，您也可以把prometheus部署在其他地方。系统内不支持修改这个配置，需要您手动配置

**Comment by xkmyf** [comment]
> prometheus 的保留时长是启动时配置的，您也可以把prometheus部署在其他地方。系统内不支持修改这个配置，需要您手动配置

好的。然后我的想法是压测监控数据作为报告的一部分，保存到平台的MySQL数据库中是否更合适呢？
