### ISSUE TITLE
[BUG] report 对象未判空

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1726]
report 对象未判空

https://github.com/metersphere/metersphere/blob/0e1991ae281f734fecbd8d6499fed8b4a15975c7/backend/src/main/java/io/metersphere/api/jmeter/APIBackendListenerClient.java#L250

**Comment by fit2-zhao** [comment]
@guhan121  请问在什么情况下 report 为空了，按目前逻辑 这个对象应该不会为空，除非执行过程发生了bug，您是在接口定义/ 接口自动化/测试计划 / 那个模块执行的。
