### ISSUE TITLE
[BUG]接口场景和测试计划使用资源池运行失败，同时jenkins使用资源池运行也失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17288]
### 联系方式

张树彬

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

接口场景和测试计划使用资源池运行失败，同时jenkins使用资源池运行也失败

### 重现步骤

1. 创建测试计划或者接口场景，关联接口CASE
2. 在MS上使用资源池执行该计划或该场景，无法完成执行
3. 在jenkins上使用资源池执行该计划或该场景，无法完成执行
4. 在MS上或jenkins上不使用资源池执行廖计划或场景，很快就能执行完成

### 期待的正确结果

在MS和jenkins上使用资源池，可正常执行

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/186109676-e92148c7-96fd-470f-a5f0-14a5ef9698ff.png)

**Comment by xulinde** [comment]
没有复现，用的什么资源池，版本确定是v2.0.1吗？
