### ISSUE TITLE
[QUESTION]执行dockfile文件的时候，抄不到里面的dependcy文件夹，这个是什么时间出现的

### ISSUE THREAD

**Issue by dingjunxin** [metersphere/metersphere#17297]
### 请描述您的问题

执行docker build命令，查询不到dependcy文件夹,这个文件夹是什么时间创建的呢？

**Comment by liqiang-fit2cloud** [comment]
看这里。
https://github.com/metersphere/metersphere/blob/dev/.github/workflows/build-push.yml#L55
