### ISSUE TITLE
[BUG] 数据源配置中的插件 MybatisInterceptor 中的 interceptorConfigMap 理论上会将所有的Mapper层的返回都记录

### ISSUE THREAD

**Issue by wangzherongyaoo** [metersphere/metersphere#17299]
### MeterSphere 版本

全部

### 使用外置数据库

否

### 问题描述

数据源配置中的插件 MybatisInterceptor 中的 interceptorConfigMap 理论上会将所有的Mapper层的返回都记录

### 重现步骤

数据源配置中的插件 MybatisInterceptor 中的 interceptorConfigMap 理论上会将所有的Mapper层的返回都记录

**Comment by liuruibin** [comment]
这个是mybatis提供出来的拦截器，主要目的是对数据库表内容和model映射进行一些通用处理，例如某个字段的加解密，解压缩
