### ISSUE TITLE
[FEATURE]  UI测试预计什么时候可以上线呢？会采用什么样的框架呢？

### ISSUE THREAD

**Issue by hawking-lab** [metersphere/metersphere#173]
**请描述您的问题.**

[FEATURE]  UI测试预计什么时候可以上线呢？会采用什么样的框架呢？

**Comment by wangzhen-fit2cloud** [comment]
目前还没有想好，大概率会基于 selenium 来做，但也不排除用一些其他框架，想 playwright、testcafe 之类的

**Comment by LinuxSuRen** [comment]
可以考虑采用我封装的一个基于 Selenium 的框架。这个框架也是 Java 语言实现的，如果有改动的话，我可以参与一起开发。

https://github.com/LinuxSuRen/phoenix.webui.framework
