### ISSUE TITLE
[BUG] 功能用例导出为xmind，打开后缺少步骤、预期结果、前置条件、备注信息。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#17305]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/44999044/186125302-bb51c771-9f60-41b9-93ab-9f94ea5462bf.png)

### 重现步骤

选择用例，导出为xmind格式

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/16800
