### ISSUE TITLE
[BUG]场景自动化中修改cron表达式后，页面卡死

### ISSUE THREAD

**Issue by leoyip** [metersphere/metersphere#17304]
### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

场景自动化中修改cron表达式后，页面卡死，无法做任何操作，需要刷新页面恢复。

### 重现步骤

1. 进入接口测试-接口自动化-设置场景定时任务
2. 点击自动生成cron表达式【000/1**？】，确认
3. 手动修改cron表达式，【000/0**？】，网页卡住，无法操作

![15001661245029_ pic](https://user-images.githubusercontent.com/16930670/186123726-4a31b950-8b84-46cf-a8d9-b7b14e373417.jpg)

### 期待的正确结果

可以正常修改cron表达式，不会出现页面卡死

**Comment by zyyfit** [comment]
页面卡死是个问题，不过 0 0 0/0 * * ？ 这个表达式不对哦

**Comment by leoyip** [comment]
> 页面卡死是个问题，不过 0 0 0/0 * * ？ 这个表达式不对哦

还没有到输入错误表达式这一步，删除“1”页面就会卡死了

**Comment by zyyfit** [comment]
> > 页面卡死是个问题，不过 0 0 0/0 * * ？ 这个表达式不对哦
> 
> 还没有到输入错误表达式这一步，删除“1”页面就会卡死了

只是删除 1 的话我这边没有卡住，然后填0/0会卡死是使用的插件的漏洞，后续考虑更换插件
