### ISSUE TITLE
[BUG] 接口自动化中，多个项目切换不同环境，导致不同环境数据库配置发生变化。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#17311]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

具体问题:
1. 当添加第二个接口的时候，并没有配置环境，但前置sql的环境配置默认是第一个的。
2. 当第二个环境配置过的时候，必须刷新页面才能刷新前置sql里面的环境配置。
3. 当配置了两个同名数据库不同环境，进行切换的时候，第一次切换，数据库选择第二个，第二次切换，数据库就选择第一个了。（正确结果应该为第二个，因为数据库同名）

https://user-images.githubusercontent.com/33945037/186136074-b627543d-bf38-4d6b-a445-cec13fd026d5.mp4

### 重现步骤

1. 两个项目，每个项目配置两个一模一样的数据库环境配置。
2. 接口自动化，复制接口定义。
3. 添加前置sql脚本，切换不同的环境，即可复现。

https://user-images.githubusercontent.com/33945037/186137085-ff153245-a01d-4f6a-919b-388f40bef3f8.mp4

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这里的逻辑再说明一下，
项目A里面有环境1，数据源1
项目B里面有环境2，数据源2
在项目A里创建场景，引用或者复制项目A的接口1和项目B的接口2
在场景里，
这两个项目都没选环境的时候，给接口1和接口2添加前后置sql脚本，默认数据源都是空的
项目A选了环境1，项目B没选环境的时候，给接口1和接口2添加前后置sql脚本，默认数据源都是 环境1的数据源1
项目B选了环境2，项目A没选环境的时候，给接口1和接口2添加前后置sql脚本，默认数据源是，接口1为空，接口2为数据源2

**Comment by zyyfit** [comment]
1.20版本和2.1版本都已修复
