### ISSUE TITLE
[FEATURE] 场景不支持多域名

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1731]
**请描述您的需求或者改进建议.**
在多域名的场景中需要多个域名
于是使用了${gateway}来控制访问域名；
但是在接口定义中这样的写法是错误的。

![image](https://user-images.githubusercontent.com/5517369/112777455-de975d80-9074-11eb-9956-89fcb8cae3fd.png)

**请描述你建议的实现方案**

接口定义直接参数定义；
然后即使接口case也支持运行环境；环境中带有域名

**Comment by zyyfit** [comment]
您好，这个功能内部评审后再回复您
