### ISSUE TITLE
[BUG]【接口自动化】查看自动化报告后出现控件滑落

### ISSUE THREAD

**Issue by yptest111** [metersphere/metersphere#1732]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.0-21bf611d
**Bug 描述**
简要描述您碰到的问题
在接口自动化页面，查看自动化执行结果的报告，不下载，关闭页面后出现如图所示问题
**Bug 重现步骤**
在接口自动化页面，查看自动化执行结果的报告，不下载，关闭页面后出现如图所示问题

**期待的正确结果**
页面不会出现混乱

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/81546368/112784815-21f9c800-9085-11eb-9bcc-6082cfc526ff.png)

**Comment by zyyfit** [comment]
感谢反馈，这个问题将在v1.8.1修复
