### ISSUE TITLE
[FEATURE]在CASE里增加用例描述

### ISSUE THREAD

**Issue by cixiafeibixia** [metersphere/metersphere#17338]
### MeterSphere 版本

v1.20.12-lts-2297374a

### 请描述您的需求或者改进建议

需求：在CASE里增加用例描述：
背景：
用例（文字版）设计人员A跟  用例转换（变成接口脚本）  人员B不是同一个人；
需要有个地方可以让A先写文字版用例，后续B根据A设计的转换接口用例

### 请描述你建议的实现方案

在CASE里增加一个地方，用于写这些信息
![image](https://user-images.githubusercontent.com/32405820/186309783-34b6345d-4c4e-4249-8f2f-f38d60330993.png)

**Comment by Hyyfit** [comment]
这个可以支持的，后续在CASE里新增一个 “描述”字段
