### ISSUE TITLE
[BUG]【接口定义】频繁切换页签报错

### ISSUE THREAD

**Issue by yptest111** [metersphere/metersphere#1733]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.0-21bf611d
**Bug 描述**
简要描述您碰到的问题
在接口定义页面，频繁切换三个页签或者快速切换。会有报错应该是来不及页面渲染
**Bug 重现步骤**
接口定义页面，三个页签频繁切换或者快速切换
**期待的正确结果**
不会报错

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/81546368/112785057-b532fd80-9085-11eb-8cfc-8741f4fad02f.png)

**Comment by zyyfit** [comment]
感谢反馈，请等待v1.8.1版本发布后再查看一下这个问题
