### ISSUE TITLE
[BUG]接口自动化中后置sql提取出来的类型为datetime的变量，日期和时间中间会多一个T

### ISSUE THREAD

**Issue by Thisisasnail** [metersphere/metersphere#17341]
### 联系方式

交流群47-柚子，邮箱liuyoushun@aliyun.com

### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 使用外置数据库

否

### 问题描述

![a05bdd6b52af07a34476d0381e24f29](https://user-images.githubusercontent.com/63831219/186312397-bf1a8d07-dba4-469c-bba7-0e70f2027e24.png)
![125710376dd3783b9544ffdb0be05d0](https://user-images.githubusercontent.com/63831219/186312419-ace8bb48-515d-4ce5-af0a-e53f015f209d.png)
如上面两个图。

### 重现步骤

详见问题描述

### 期待的正确结果

实际应该为下面这个图
![19080b835f69e4c42ac503731f97da3](https://user-images.githubusercontent.com/63831219/186312947-681cb8cd-f35a-4a30-9794-8cb69a786267.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
我们排查了一下，发现是因为我们使用的数据库连接驱动是8.0的，然后8.0的驱动jar包会有这个问题，5.x的版本没问题，所以这个是驱动的问题，暂时不处理了，然后如果需要正常格式的数据，可以使用下面这个格式化 sql 自己格式化一下
DATE_FORMAT(time, '%Y-%m-%d %H:%i:%s')

**Comment by Thisisasnail** [comment]
嗯嗯，之前已经用 DATE_FORMAT(time, '%Y-%m-%d %H:%i:%s')在sql中进行格式化了
