### ISSUE TITLE
[BUG]性能测试脚本使用了prev.setResponseMessage()方法更新ResponseMessage，但是生成的JTL中ResponseMessage还是默认的值“OK”，没有获取更新后的值

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17345]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

性能测试脚本使用了prev.setResponseMessage()方法更新ResponseMessage，但是生成的JTL中ResponseMessage还是默认的值“OK”，没有获取更新后的值

### 重现步骤

1.创建接口自动化场景，在后置脚本中使用prev.setResponseMessage()，在接口自动化中这个方法生效了
![image](https://user-images.githubusercontent.com/88763608/186315761-99ac83de-971c-4762-a167-508281904db5.png)
2.将该场景转为性能测试，下载报告的JTL文件，发现JTL文件中的值还是默认的OK，没有更新
![7c939bc180a0a6105378547f554dc3a](https://user-images.githubusercontent.com/88763608/186318036-9e619b05-2f22-4af7-90c0-8b2c24eafdba.jpg)
3.jmeter验证：将MS的场景导出到jmeter执行，jmeter生成的JTL文件中responseMessage是正常更新了的
![09051b38a0b685e07e1502c8cfa3b42](https://user-images.githubusercontent.com/88763608/186368558-b04eb9f2-d533-4329-98fb-c7aa0b4cc17a.jpg)

### 期待的正确结果

跟jmeter保持一致，JTL中responseMessage能正常更新。
实际上prev.setResponseMessage()这个方法在自动化生效了，只是性能测试里可能没生效

**Comment by zyyfit** [comment]
我们的jtl里的responsemessage是后来处理过的，跟jmeter里不一样
