### ISSUE TITLE
[FEATURE]建议在项目设置-配置环境中，可以类似接口自动化中的接口那样、添加多个前置脚本和前置sql。

### ISSUE THREAD

**Issue by Thisisasnail** [metersphere/metersphere#17344]
### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 请描述您的需求或者改进建议

![4653d7ab2f1b1f25c8ea2beca3847e5](https://user-images.githubusercontent.com/63831219/186316776-3dd75c41-8b87-438c-811c-dc15f34ab54d.png)

![image](https://user-images.githubusercontent.com/63831219/186317831-9e03f158-86ab-401f-a68a-73f22349fe7e.png)
建议在项目设置-配置环境中，可以类似接口自动化中的添加多个前置脚本和前置sql。
因为很多场景需要，从数据库查询出来一些接口通用的请求参数，其实配在环境中比较好。如果配在某个场景的接口下，多个场景执行起来很麻烦，必须选择已配置的那个场景一起执行。

### 请描述你建议的实现方案

建议在项目设置-配置环境中，可以类似接口自动化中的添加多个前置脚本和前置sql。

**Comment by Hyyfit** [comment]
全局前置里是没有限制的，可以添加多个的

**Comment by Thisisasnail** [comment]
环境配置中的全局前置脚本只能添加一个啊，不能添加多个啊
