### ISSUE TITLE
[BUG]升级v1.8以后，之前维护的JSONPath断言 等于 全部变成正则匹配，导致所有用例断言失败

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1735]
**MeterSphere 版本**
  MeterSphere v1.8

**Bug 描述**
  升级v1.8以后，之前维护的JSONPath断言 等于 全部变成正则匹配，导致所有用例断言失败

**Bug 重现步骤**

**期待的正确结果**

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37204403/112793146-54acbc00-9097-11eb-8596-8fb38f764e02.png)

**Comment by SloanGao** [comment]
目前以前所有维护用例都跑失败

**Comment by wangzhen-fit2cloud** [comment]
你好，经测试没有复现这样的情况。
在旧版本创建的 jsonpath 断言，升级后匹配方式改为正则匹配后也可以断言成功，而且旧版本断言期望值其实也是正则表达式匹配的方式。
![image](https://user-images.githubusercontent.com/27671436/112797969-c9372900-909e-11eb-872e-4e2a3173a9ec.png)

**Comment by SloanGao** [comment]
你好，如果一个响应结果里面有很多JSON结构体，要判断每个结构体指定的参数结果是否匹配，会有问题，如下：
另外为何以前维护的 等于会全部变成 正则表达？是特意修改的？
{
    "code": 0,
    "msg": null,
    "data": [
        {
            "updateUser": "JMETER",
            "createUser": "JMETER",
            "updateTime": "2021-03-29T17:23:30.223",
            "createTime": "2021-03-29T17:23:30.083",
            "id": 3071,
            "code": "JMETER13152428",
            "title": "接口自動化測試",
            "type": 0,
            "terms": "",
            "enabled": true,
            "draft": false,
        }
    ],
    "success": true
}
![image](https://user-images.githubusercontent.com/37204403/112923151-4ebee580-9140-11eb-84f6-8c991f94a479.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，之前的期望值内容也是填写正则，为了做判断的时候更易用一些，我们在这个版本增加了匹配方式选择。目前的情况的话可以把匹配方式改成包含，断言就可以成功。
