### ISSUE TITLE
[BUG]场景列表执行场景用例，获取运行环境和路径失败

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#1736]
**MeterSphere 版本**
   MeterSphere v1.8

**Bug 描述**
  在场景列表执行场景用例，获取运行环境和路径失败

**Bug 重现步骤**

**期待的正确结果**
 

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37204403/112793753-6f336500-9098-11eb-8055-ddaa9760ea16.png)

**Comment by zyyfit** [comment]
感谢反馈，能具体描述一下复现步骤吗？比如接口是在metersphere里创建的还是导入的，直接在场景列表执行还是批量执行的？

**Comment by SloanGao** [comment]
我之前是在场景列表中单独执行一个场景用例，接口都是导入的。然后创建运行环境，不过我今天重试了一下没有复现，昨天运行多次都是上面截图那样，后面旧没关注

**Comment by SloanGao** [comment]
我這邊重新驗證了一下，應該是升級以後有些腳本獲取不到環境變量，如下圖：實際是存在環境變量的(需要重新調試才會出現環境變量配置選項)
![image](https://user-images.githubusercontent.com/37204403/113798511-e1d1ce00-9785-11eb-8e40-8eecdd78c5df.png)

**Comment by Boylijun** [comment]
场景--编辑接口--调试，为啥老是拿不到配置的运行环境，请求地址老是http：/ 。这个debug了好久，

**Comment by zyyfit** [comment]
您好，目前最新版本是1.9.3，解决了一些无法获取到环境的问题，请升级一下看看您的问题是否已解决

**Comment by Boylijun** [comment]
您好，bug我们已经修复，暂时无法升级到1.9.3，还是感谢

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zyyfit ***@***.***&gt;
发送时间: 2021年5月19日 23:15
收件人: metersphere/metersphere ***@***.***&gt;
抄送: Boylijun ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[metersphere/metersphere] [BUG]场景列表执行场景用例，获取运行环境和路径失败 (#1736)





 
您好，目前最新版本是1.9.3，解决了一些无法获取到环境的问题，请升级一下看看您的问题是否已解决
