### ISSUE TITLE
压测时间刻度不对[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1737]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.0
**Bug 描述**
简要描述您碰到的问题
压测时间刻度不对
**Bug 重现步骤**
1.  压测时间设置300，其他参数均正常设置，然后运行
2. 然后观察压测配置

**期待的正确结果**
正确情况下应该是什么样的？
时间刻度正常
**截图**
![image](https://user-images.githubusercontent.com/80814232/112803929-62b60900-90a6-11eb-9b13-f61221b6e26b.png)

如果有截图，请附上截图.

**Comment by liuruibin** [comment]
在1.8版本中压力预览没有采用连续的时间轴设计，原因是当输入数字过大时图表渲染很慢，并在此版本中提供时间单位配置可以灵活配置
