### ISSUE TITLE
[FEATURE]建议测试用例支持导出脑图格式

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1738]
**请描述您的需求或者改进建议.**

建议测试用例支持导出脑图格式

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
您好，脑图格式可以导出的，具体步骤如下：

![image](https://user-images.githubusercontent.com/73461316/112827832-76bb3400-90c1-11eb-89e7-e57aa0e73224.png)

选择导出格式为 .md
![image](https://user-images.githubusercontent.com/73461316/112827854-7cb11500-90c1-11eb-8024-31da29a5e2bf.png)
