### ISSUE TITLE
[FEATURE]用例列表和测试计划关联用例中，建议增加优先级和关键词查询功能。

### ISSUE THREAD

**Issue by dahuachao** [metersphere/metersphere#174]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/68523338/88766368-7b35f280-d1aa-11ea-820d-40221fdbc19c.png)

![image](https://user-images.githubusercontent.com/68523338/88766205-35792a00-d1aa-11ea-8d27-d2eab5974a19.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在 v1.1.0 版本中增加了高级搜索功能，可以更新试用一下
