### ISSUE TITLE
[BUG]Swagger导入报解析数据错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17404]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.12

### 使用外置数据库

是

### 问题描述

Swagger导入报解析数据错误
![origin_img_v2_44c01af3-a8b4-4792-b0ba-b1ac2d237edg](https://user-images.githubusercontent.com/103627487/186558100-83415cda-0ffa-4c2f-bfad-808dc66e19f0.jpg)

### 重现步骤

接口列表-Swagger导入

**Comment by xulinde** [comment]
v1.20.13-lts已修复～
