### ISSUE TITLE
[BUG]测试计划 页面，列表“测试进度”和“通过率”值一致，所有用例执行完成后，“测试进度”应该为100%，不能受“通过率”影响

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#1740]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.8.0-21bf611d
**Bug 描述**
简要描述您碰到的问题
[BUG]测试计划 页面，列表“测试进度”和“通过率”值一致，所有用例执行完成后，“测试进度”应该为100%，不能受“通过率”影响
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/112808743-e6bebf80-90ab-11eb-9af9-aedc0697c6ab.png)

**Comment by zyyfit** [comment]
您好，后续版本会优化这个问题

**Comment by jhong123** [comment]
有类似问题 
![Uploading image.png…]()

**Comment by zyyfit** [comment]
您好，v1.10.0版本已优化了这个问题

> 有类似问题
> 
> ![image](https://user-images.githubusercontent.com/11580681/117630361-b2abe380-b1ad-11eb-9b92-86c176df28a5.png)
