### ISSUE TITLE
[FEATURE] 建议加大case review中comment的长度限制，目前60字符太短了。

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1742]
**请描述您的需求或者改进建议.**
case review中 comment 限制太短了。

![image](https://user-images.githubusercontent.com/38770463/112814930-5df75200-90b2-11eb-89ff-d10242f2b138.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈

**Comment by zyyfit** [comment]
已在1.8.2版本优化了这个问题，感谢使用
