### ISSUE TITLE
[BUG] 测试计划113个UI自动化场景，每天早上5点执行，最近每次都会出现2个场景所有步骤和断言都是成功的，但是UI自动化场景状态显示为失败。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17425]
### 联系方式

王进

### MeterSphere 版本

 v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

测试计划113个UI自动化场景，每天早上5点执行，最近每次都会出现2个场景所有步骤和断言都是成功的，但是UI自动化场景状态显示为失败。
![1661393694803](https://user-images.githubusercontent.com/76033005/186558669-4563b220-70e8-411c-9b56-f7cdc65de684.png)

### 重现步骤

1. 用户创建了一个全量的UI自动化回归测试计划
2. 添加了113个UI自动化场景
3. 每天早上定时回归。
4. 查看报告
![1661393839039](https://user-images.githubusercontent.com/76033005/186558941-174eb570-6d35-4fca-a42d-92bf62022d81.png)

### 附加信息

这种场景很难内部复测，但是在客户环境确实碰到了，客户环境的访问权限已给到开发。

**Comment by xulinde** [comment]
v2.1.1已修复～
