### ISSUE TITLE
[BUG] [测试跟踪] 在“高级搜索”中通过"用例等级"进行的筛选结果不准确

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#17421]
### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

在测试跟踪中，在“高级搜索”中通过"用例等级"进行筛选，得到的结果不准确

### 重现步骤

1. 进入测试跟踪--功能用例 页面
2. 直接在“用例等级” 列，进行筛选
![image](https://user-images.githubusercontent.com/24548477/186546296-1b1113fc-63b0-452d-a767-905b457cb3c6.png)

3. 结果显示有5行
![image](https://user-images.githubusercontent.com/24548477/186546378-8068b7cf-daf6-4f64-9da2-348636577602.png)

4. 再通过“高级搜索”进行筛选
![image](https://user-images.githubusercontent.com/24548477/186546470-1fcbe411-8400-4912-a2df-0dd34efa9158.png)

5. 结果显示“无数据”
![image](https://user-images.githubusercontent.com/24548477/186546563-39af9f46-4a29-4277-8b84-5d4f4bd1262d.png)

### 期待的正确结果

高级搜索应该与普通筛选得到的结果一致

**Comment by youliyuan-fit2cloud** [comment]
v2.1.0 版本中已修复。
