### ISSUE TITLE
[BUG] 测试计划-功能用例-按更新时间筛选-用例数量不对

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#17428]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

测试计划关联功能用例后，按更新时间筛选用例，数量数量不对上

### 重现步骤

1.进入测试跟踪-测试计划-创建新测试计划
2.关联功能用例
3.高级搜索-按更新时间筛选用例
4.检查筛选的用例数量是否致

### 期待的正确结果

按更新时间筛选用例数量是对的

### 附加信息

1.更新的用例
![image](https://user-images.githubusercontent.com/45531073/186562758-e4e649f6-c47d-4060-8737-88f8031b7dfd.png)
2.按更新时间搜索
![image](https://user-images.githubusercontent.com/45531073/186562759-404f7702-383d-432d-9c97-8b74944e1c21.png)
3.搜索结果
![image](https://user-images.githubusercontent.com/45531073/186562851-e3a8eae3-ad67-4899-bd26-34e243a93983.png)

**Comment by xulinde** [comment]
v2.1.1已修复～
