### ISSUE TITLE
[FEATURE] 登录页面选择OIDC后，取消，默认还是选中OIDC，想重新登录OIDC，需切到别处，再点OIDC，操作过于冗余

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17434]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

登录页面选择OIDC后，取消，默认选中普通登录进行兜底
非选中OIDC单选框
![image](https://user-images.githubusercontent.com/103925124/186569076-7487c76b-6d48-4420-85be-f439fd8cc9da.png)

**Comment by Hyyfit** [comment]
您好，没有复现你说的这个问题，取消后，依然是选中OIDC的状态。

**Comment by Ycr123888** [comment]
![image](https://user-images.githubusercontent.com/103925124/187114110-96054c90-d4dd-46c2-a298-fcc0ad337252.png)
点击取消后，还是选中OIDC的状态。

**Comment by Ycr123888** [comment]
有复现嘛

**Comment by Hyyfit** [comment]
没有，你直接微信联系我吧
