### ISSUE TITLE
[BUG]性能测试引用多个接口自动化场景时，排序随机，不便于按顺序执行的使用场景

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17433]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

性能测试一次性添加引用多个接口自动化场景，多个接口自动化场景在性能测试中的排序是无规律的。
对于需要按顺序执行的场景，有很大影响

### 重现步骤

1.创建ABCDEFG7个场景
2.创建性能测试
3.性能测试引用接口自动化场景，依次勾选ABCDEFG7个场景，点击确定
4.结果7个场景在性能测试中排序是无规律的，跟我选择的顺序不一致，跟在场景列表中的顺序也不一致
5.我录了个视频在附件

### 附加信息

[验证排序.zip](https://github.com/metersphere/metersphere/files/9420982/default.zip)

**Comment by zyyfit** [comment]
这里如果同时选多个一起导入的话，是不会区分先后顺序的，要想区分先后顺序，可以一个一个的引用
