### ISSUE TITLE
[BUG]场景中有FOREACH循环控制器，报告中动态展示循环中的步骤名称时存在问题

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17445]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

场景中有FOREACH循环控制器，报告中动态展示循环中的步骤名称时存在问题

### 重现步骤

1.在场景列表中创建列表变量
![1661411908232](https://user-images.githubusercontent.com/88763608/186600544-834b0ded-065f-49ea-b2e5-6f273621ed94.jpg)
2.场景中添加循环控制器，循环控制器下添加请求，请求名称引用foreach循环的变量
![1661411908239](https://user-images.githubusercontent.com/88763608/186600615-0b634790-1d54-437f-a850-e8ddf252f328.jpg)
3.场景列表一键执行该场景
4.执行中循环中的请求名称除了第一次，后面的名称和响应时间都是重复的
![1661411908246](https://user-images.githubusercontent.com/88763608/186600649-5d34ccb2-5be5-497c-a34a-81db8cce4cf0.jpg)
5.执行结束后，报告展示就正常了
![1661411908256](https://user-images.githubusercontent.com/88763608/186600681-ada9b411-fac6-48ae-9377-3faab3468c25.jpg)

### 期待的正确结果

执行中报告展示应该也是正常的

**Comment by linfengjjj** [comment]
[循环的名字.zip](https://github.com/metersphere/metersphere/files/9422375/default.zip)
这个是操作视频

**Comment by linfengjjj** [comment]
[records.txt](https://github.com/metersphere/metersphere/files/9422380/records.txt)
这是我用的场景变量内容

**Comment by zyyfit** [comment]
这个不好改，并且没什么实际影响，先不改了
