### ISSUE TITLE
[BUG]ui自动化生成测试报告时，页面会一直转圈。但是测试报告其实已经生成完成了。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#17446]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.12

### 使用外置数据库

否

### 问题描述

ui自动化生成测试报告时，页面会一直转圈。但是测试报告其实已经生成完成了。

metersphere的上层有经过nginx，没有配置超时时间。生成报告一直在转，ws没有抓到内容，消息内容没有“i'm alive”。
![51ba7e5d43b42276898f18e1889d42a](https://user-images.githubusercontent.com/83771182/186602621-60638c0b-0107-4a04-a42e-9f11bb4b7577.jpg)
![a4a802bb7ad81ccb7a885fed6b1374a](https://user-images.githubusercontent.com/83771182/186602659-1e0d2ef1-d435-4ae5-9709-1e1146370e37.jpg)

### 重现步骤

ui自动化生成测试报告时，页面会一直转圈。过几分钟后点击测试报告，发现报告已经生成完成。

### 附加信息

Uploading 78f781c56feef1caba8e41cce4fb4f40.mp4…

**Comment by yaoyi111** [comment]
https://user-images.githubusercontent.com/83771182/186603531-34083e86-4a42-4ee8-954a-d38c65319d43.mp4

**Comment by zrfit** [comment]
经沟通，是用户配置问题，配置nginx允许websocket通过，就可以了。

**Comment by zrfit** [comment]
经沟通，是用户配置问题，配置nginx允许websocket通过，就可以了。
