### ISSUE TITLE
紧急问题：接口定义导入后，选择了要导入的模块，选择了覆盖，结果把整个项目下面所有的一样的都覆盖了

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#1745]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.8.0-21bf611d

**Bug 描述**
简要描述您碰到的问题
接口定义导入后，选择了要导入的模块，选择了覆盖，结果把整个项目下面所有的一样的都覆盖了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/112822577-b3376180-90ba-11eb-863f-4bcd78bcfb6d.png)

**Comment by zyyfit** [comment]
您好，目前覆盖是这样设计的，您有什么更好的建议可以提一个enhancement
