### ISSUE TITLE
[BUG]接口测试>>接口定义>>API：API详情页面，设置了参数的描述和最大、最小长度后，点击保存。点击【文档】在接口文档里无法显示这些信息。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17453]
### MeterSphere 版本

V1.20.12

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口定义>>API：
1、API详情页面，设置了参数的描述和最大、最小长度后，点击保存。
2、点击【文档】，在这个接口文档里没有这些已经设置好的信息。

### 重现步骤

[BUG]接口测试>>接口定义>>API：
1、API详情页面，设置了参数的描述和最大、最小长度后，点击保存。
2、点击【文档】，在这个接口文档里没有这些已经设置好的信息。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/186610020-cd0c8dc6-72a5-4d6e-bd3a-01c65b95a32c.png)
![image](https://user-images.githubusercontent.com/78218624/186610613-93dd7128-148e-405c-ac2b-3e22e0d7fe24.png)

**Comment by xulinde** [comment]
v1.20.12lts还不支持 在接口文档显示高级设置的内容。v2.1.0支持
