### ISSUE TITLE
[BUG]CSV导入，获取的值是一串完整的json时，没有取全。可能问题原因：按照jmeter的功能应该将是否允许引号的条件设为TURE。

### ISSUE THREAD

**Issue by wangeqi** [metersphere/metersphere#1746]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
CSV导入，获取的值是一串完整的json时，没有取全
**Bug 重现步骤**
1.  csv文件某个值是一个json串
2. 在平台导入csv文件
3. 参数化取值
4. 查看取出的值

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本将会修复这个问题

**Comment by zyyfit** [comment]
您好，请问您的csv文件上传后是否 以逗号作为分隔符的？逗号作为分隔符的话，csv文件会自动把json串中的内容分割开，可以修改一下分隔符试试，如果不是这个问题请附上csv文件我们再看一下
