### ISSUE TITLE
[FEATURE]不太理解为什么只支持Python2

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#17463]
### MeterSphere 版本

v1.20.6

### 请描述您的需求或者改进建议

https://metersphere.io/docs/tutorial/use_python/
脚本中需要用到第三方库，但是metersphere所在宿主机很难安装python2的第三方包
2020年python2就已经不再维护了，为什么不支持python3 呢？

**Comment by ryanrain2016** [comment]
别想了，jython目前只支持pyhon2
