### ISSUE TITLE
[BUG]接口场景用例中的文件丢失会导致无法调试或者测试计划执行中断

### ISSUE THREAD

**Issue by ryanrain2016** [metersphere/metersphere#17476]
### 联系方式

ryan@top365.ml

### MeterSphere 版本

v2.0.0-9e3627ae

### 使用外置数据库

是

### 问题描述

之前使用[Kubernetes](https://kubernetes.io/) 部署的，后面升级之后发现有文件的用例都无法调试，调试接口报错 500
测试计划中有此用例的执行后测试计划会在这个用例中止

### 重现步骤

1. 添加接口场景用例，用例步骤中有请求文件
2. 删除服务器上的该文件，调试或者执行包含该用例的测试计划

### 期待的正确结果

1. 可以调试，控制台提示文件丢失，用例执行结果为失败
2. 包含此用例的测试计划执行时控制台提示文件丢失，该用例执行结果为失败，控制台报错提示，可继续执行后面的用例
3. 建议设置了出错后继续时，测试过程发生的任何错误不要阻止用例继续向后执行

**Comment by zyyfit** [comment]
1、没有csv文件的场景不支持调试/执行，2.1.0版本已经增加了提示信息
2、没有csv文件的场景在测试计划中不执行，但是测试没有影响其他用例，没有复现问题2
![image](https://user-images.githubusercontent.com/73461316/187110939-456f4734-aecc-4d40-9578-37de0f09716f.png)

**Comment by ryanrain2016** [comment]
这个后面多次试验发现是提交的数据是xls的文件时会报错，jpg就可以；取消勾选文件的那个字段就可以，加上之后就不行；换一个jpg的文件也可以；之前1.20版本上是正常的

**Comment by zyyfit** [comment]
没有复现，文件丢失的时候都是可以正常执行用例的，用例结果中会有报错信息
![image](https://user-images.githubusercontent.com/73461316/187587159-6dc1631e-755a-4f35-97c1-59ca2e883c8f.png)
