### ISSUE TITLE
[FEATURE]  接口测试枚举使用未说明，不知道使用规则

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17489]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

加下使用说明：这里是生成测试数据枚举才会生效的；默认值优先级大于枚举
![image](https://user-images.githubusercontent.com/103925124/186835596-484ae656-dc67-4fb4-8642-9f15de62f46f.png)
有默认值的情况下，生成不了枚举值

### 请描述你建议的实现方案

加下使用说明：这里是生成测试数据枚举才会生效的；默认值优先级大于枚举；

有默认值的情况下，可生成枚举值

**Comment by luty2018** [comment]
加下使用说明：这里是生成测试数据枚举才会生效的；默认值优先级大于枚举
-- 感谢建议， 这个说明可以加一下

另外问一下“有默认值的情况下，可生成枚举值” 这是希望解决什么场景？目前有默认值就直接取默认值了

**Comment by Ycr123888** [comment]
枚举里面的数据是测接口正向和反向的数据
默认值是 此接口进来后，不重新填值进行测试的值，也是给测试人员的一个示例；

“有默认值的情况下，可生成枚举值”  注重用户可切换两者的使用

**Comment by luty2018** [comment]
暂维持设计
