### ISSUE TITLE
[BUG]项目环境导出后，按模块匹配的配置丢失了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17493]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

项目环境导出后，按模块匹配的配置丢失了

### 重现步骤

1.创建项目环境，设置按模块匹配
![image](https://user-images.githubusercontent.com/88763608/186839404-e326810a-4c4b-4df6-99b8-0c676d477338.png)

2.导出项目环境
3.删除原来的项目环境，然后再导入，发现导入后，没有按模块匹配的配置了
![image](https://user-images.githubusercontent.com/88763608/186839956-37e0f0a4-cd7c-4bad-8d52-e23add38adb6.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，不支持导出模块类型的环境配置。
