### ISSUE TITLE
[FEATURE] ms支持jemter函数__chooseRandom(10,15,20,30)}/__RandomFromMultipleVars

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17492]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

使用场景     [从多个数中随机取一个值的方法](https://www.cnblogs.com/Gritli/p/15777626.html)

![426857793429104394](https://user-images.githubusercontent.com/103925124/186837485-16ba1265-5dde-4896-b203-6eeccb8cf9b6.jpg)
用户有如上图的枚举用例需给参数赋值

### 请描述你建议的实现方案

ms支持jemter函数${__chooseRandom(10,15,20,30)}/__RandomFromMultipleVars

**Comment by Hyyfit** [comment]
我们调研一下，如果是jmeter自带的函数，是可以支持的

**Comment by Ycr123888** [comment]
嗯嗯，是自带的，jemter官网一查就有的，大量用户有此需求~

**Comment by Ycr123888** [comment]
用户动态传参，强依赖此功能

**Comment by zhangzhaox** [comment]
__chooseRandom 函数非原生函数 属于插件补充函数  但建议MS平台默认支撑
要么用户 自行上传插件函数包，包含常用的MD5  BASE64等函数
![image](https://user-images.githubusercontent.com/82088551/187391183-da5a65cb-b283-4556-90c5-d94f910d64f7.png)

**Comment by zhangzhaox** [comment]
test1: ${__chooseRandom(1,2,3,)}
test1000: ${__MD5(11111,)}  
我上传了 functions-2.1的jar包 依然不可以

**Comment by Ycr123888** [comment]
你好，我在20.12-lts服务上试好了，步骤如下：
![4f11c4ea4b78f919f85e29f026867db](https://user-images.githubusercontent.com/103925124/187591797-1959fdc7-dc31-4fb6-abcc-dd356d6e7d1a.png)
将内置函数jar包放到ms-server容器下的/opt/jmeter/lib/ext(docker cp /mnt/c/lipan/jmeter-plugins-functions-2.1.jar 7684bc064363:/opt/jmeter/lib/ext),要重启ms服务；
![image](https://user-images.githubusercontent.com/103925124/187591879-927acc07-9e84-45a4-858c-6022ad5e81c9.png)
备注：重启后函数仍不生效，需要无痕+重新导入接口即可；
补充：在脚本中同样也可以使用了
![image](https://user-images.githubusercontent.com/103925124/187591976-25e699c3-5f55-44c6-8ce0-77c8ba5f2c29.png)

**Comment by zhangzhaox** [comment]
> 备注：重启后函数仍不生效，需要无痕+重新导入接口即可；

需要无痕+重新导入接口即可； 什么意思  
我们自行导入 生效了也算是解决方案

**Comment by Ycr123888** [comment]
就是正常重启后，函数可以用，遇到重启后函数仍然不可用的情况，需要无痕窗口+重新导入接口再加函数，就好了


自行导入是可以，希望可以加入产品

**Comment by zhangzhaox** [comment]
确认一次生效了，虽然没有理解失败时的操作---- 需要无痕窗口+重新导入接口再加函数

附件模板重构后还是希望支持下，现在仅支持 import 方式生效，表面现象就是不同的目录  /opt/jmeter/lib/ext/  与 /opt/metersphere/data/jar/  期待后续重合后能够支持平台上操作 生效  需要重启容器可以理解的

保持现行上传jar目标不变的情况下  可以通过plugin_dependency_paths=/opt/metersphere/data/jar/   达到同样的目的
但与目前v2.1版本统一调整成仅支持项目级jar方案存在一定的冲突

**Comment by luty2018** [comment]
> 就是正常重启后，函数可以用，遇到重启后函数仍然不可用的情况，需要无痕窗口+重新导入接口再加函数，就好了
> 
> 自行导入是可以，希望可以加入产品

我们在2.1版本上实现了jar包动态加载的效果，建议在2.1版本测试验证是否还存在该问题

**Comment by Ycr123888** [comment]
版本v2.1-563d887b，文件管理上传jmeter-plugins-functions-2.1.jar，在接口参数和脚本中调用均未生效
![image](https://user-images.githubusercontent.com/103925124/188777745-93268a7b-0b86-4e8a-a52b-000ff64dc1c6.png)

**Comment by luty2018** [comment]
已转需求，待排期
