### ISSUE TITLE
[FEATURE]能否支持可以查看测试计划里面的功能用例关联了多少自动化用例数目

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#17499]
### MeterSphere 版本

v2.1.0-2de48bb8

### 请描述您的需求或者改进建议

能否支持可以查看测试计划里面的功能用例关联了多少自动化用例数目，需要统计测试计划里面功能用例关联的自动化用例数据

### 请描述你建议的实现方案

添加一列显示功能用例关联的自动化用例数目

### 附加信息

![Uploading image.png…]()

**Comment by Hyyfit** [comment]
这个可以支持的，后续会规划排期。
