### ISSUE TITLE
[FEATURE] 场景内接口暂不支持使用枚举生成测试数据

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17495]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

场景内接口暂支持使用枚举生成测试数据

![image](https://user-images.githubusercontent.com/103925124/186844182-8c259f61-e557-47f7-9cc5-732bce71b106.png)

**Comment by luty2018** [comment]
我看你的参数已经设置了值888了，如果有设定的值就不会用枚举里面的值
