### ISSUE TITLE
[BUG]接口测试-后置脚本 SampleResult提示无法找到类

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17498]
### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

接口测试-后置脚本 SampleResult提示无法找到类；；官网说明可以直接使用

### 重现步骤

应该可以直接使用

### 附加信息

![1661511226067](https://user-images.githubusercontent.com/43202800/186888789-62050c1c-87ad-46ef-921d-cda2ddf32783.jpg)
<img width="638" alt="29bbfdfaf02726be259e50b67d9e8e0" src="https://user-images.githubusercontent.com/43202800/186888835-7a1fbd44-0ed1-41c5-b08f-8c861d63c4b2.png">

![5709b2af43cceebab7a8b804c5f7dc7](https://user-images.githubusercontent.com/43202800/186889082-56a49de8-d82a-4e89-9e92-d1c3420555c0.jpg)

**Comment by zyyfit** [comment]
感谢反馈，这里应该是官网的帮助文档写错了，调用的时候是这样用的 prev.setResponseCode("200"); 
我们修改一下官方文档

**Comment by zyyfit** [comment]
官方文档已修改
