### ISSUE TITLE
[QUESTION]是否支持需改 jmeter 的配置文件

### ISSUE THREAD

**Issue by abcanqi** [metersphere/metersphere#1749]
我想修改配置文件，以便可以在调试和排错的时候看到 response 与 request 信息
我想修改的文件在 `jmeter/bin` 目录的 `user.properties` & `jmeter.properties` 文件

**Comment by wangzhen-fit2cloud** [comment]
你好，目前可以通过使用自定义jmeter镜像的方式解决该问题，后续版本会考虑自定义配置项或配置文件
