### ISSUE TITLE
[BUG]前后置脚本引用 Python 第三方库失败

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#17501]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.6

### 使用外置数据库

是

### 问题描述

按照https://metersphere.io/docs/tutorial/use_python/的说明引用安装第三方库python-opencv，并且版本控制在3.1.0（python2.7可用）之后，脚本如下：

import sys
sys.path.append("/opt/metersphere/data/python/lib64/python2.7/site-packages")
import cv2

import cv2 会提示No module named cv2.cv2 in <script> at line number 3

### 重现步骤

1.安装python2和安装virtualenv

2.安装第三方包

#创建virtualenv
#data目录为docker默认挂载路径，可将第三方包安装该目录下，若Metersphere实际安装路径为其他路径，则下面操作放在MS实际安装路径下
cd /opt/metersphere/data/
mkdir python
cd python/
virtualenv --copies .
source bin/activate

#安装第三方包
pip install opencv-python==3.1.0.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/
3.安装成功，脚本引用，报错

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，目前针对python三方库的支持不是特别全，请自行研究一下吧。

**Comment by Faerie1999** [comment]
请问这方面的代码是放在项目哪个包里面呢？
