### ISSUE TITLE
[BUG] Swagger导入参数非必填选项失效

### ISSUE THREAD

**Issue by liuyuliang1108** [metersphere/metersphere#17504]
### MeterSphere 版本

v2.1.0

### 使用外置数据库

是

### 问题描述

Swagger导入参数非必填选项失效问题
这是一个一直都存在的问题，不知道是大家都没发现 还是觉得这不是一个问题

导入参数如下：
![image](https://user-images.githubusercontent.com/48239054/187109250-bd69c729-ed8f-4608-8d29-8db42194695f.png)

导入结果如下：
![image](https://user-images.githubusercontent.com/48239054/187109459-b3b911fe-a710-4c78-baed-cb758461d7fc.png)

### 重现步骤

可使用附加信息中的json测试导入

### 期待的正确结果

![image](https://user-images.githubusercontent.com/48239054/187109641-98831f53-2a78-43e9-bd74-54c98532ce3f.png)

### 附加信息

{"openapi":"3.0.1","info":{"version":null,"title":null,"description":null,"termsOfService":null},"externalDocs":{},"servers":[],"tags":[],"paths":{"/api/test/postData":{"post":{"summary":"提交数据","requestBody":{"content":{"multipart/form-data":{"schema":{"properties":{"id":{"type":"text","required":"false","example":"6666"}}}}}},"description":"提交数据","responses":{"[{\"valid\":true,\"file\":false,\"enable\":true,\"name\":\"[{\\\"valid\\\":true,\\\"file\\\":false,\\\"enable\\\":true,\\\"name\\\":\\\"200\\\",\\\"description\\\":\\\"OK\\\",\\\"urlEncode\\\":false,\\\"value\\\":\\\"OK\\\",\\\"required\\\":true},{\\\"valid\\\":false,\\\"file\\\":false,\\\"enable\\\":true,\\\"name\\\":\\\"\\\",\\\"urlEncode\\\":false,\\\"value\\\":\\\"\\\",\\\"required\\\":true}]\",\"urlEncode\":false,\"required\":true},{\"valid\":false,\"file\":false,\"enable\":true,\"name\":\"\",\"urlEncode\":false,\"value\":\"\",\"required\":true}]":{"headers":{"":{"schema":{"type":"string"},"example":""}},"description":"","content":{"application/urlencoded":{"schema":{"type":"string","example":""}}}}},"parameters":[],"tags":["APP","测试Api服务"]}}},"components":{}}

**Comment by xulinde** [comment]
您提供的json格式不对，方便提供下文件吗
![image](https://user-images.githubusercontent.com/64065190/187156177-a0ecbbf6-8b34-43c4-9fdb-3fc3dd115ff7.png)

**Comment by liuyuliang1108** [comment]
[Swagger_Api_默认项目 (16).zip](https://github.com/metersphere/metersphere/files/9442940/Swagger_Api_.16.zip)


> 您提供的json格式不对，方便提供下文件吗 ![image](https://user-images.githubusercontent.com/64065190/187156177-a0ecbbf6-8b34-43c4-9fdb-3fc3dd115ff7.png)
[Swagger_Api_默认项目 (16).zip](https://github.com/metersphere/metersphere/files/9442945/Swagger_Api_.16.zip)

**Comment by xiaomeinvG** [comment]
您好，感谢您的反馈，我们排查了这个问题，发现swagger提供的sdk在解析swagger文件的时候，将required这个属性的值置为了null，而我们的系统的默认值为必填值，因此产生了您描述的问题，此问题我们目前在等待swagger解决
