### ISSUE TITLE
[BUG]/testresourcepool/list/quota/valid 接口逻辑优化 

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17503]
### 联系方式

蒋林峰

### MeterSphere 版本

2.1

### 使用外置数据库

是

### 问题描述

客户在CI/CD中发现，该接口/testresourcepool/list/quota/valid耗时稳定超过2s，低于CI/CD的合格标准线。
担心：后续测试数据和资源池更多时，耗时可能还会增加

### 重现步骤

1.执行测试计划，选择资源池运行，观察该接口耗时时间
2.目前以上操作，查询资源池时，会将所有资源池状态进行查询，然后将状态不通过的资源池设置成无效过滤掉。
3.建议：
1.展示资源池列表时，我们只去数据库读取，选择具体某个资源池时再去校验该资源池状态，这样就只需要校验一个资源池了
2.我们可以统一在资源池列表那里加一个定期检测的功能，其他地方使用资源池的，就不再次进行校验了

**Comment by shiziyuan9527** [comment]
展示所有资源池列表，在选择资源池时才进行校验的话，会对用户造成误解，体验不好。
定时检测资源池有效性可能会有一定时间的数据不一致问题。
暂时保持这个逻辑，后续进行优化。
