### ISSUE TITLE
[BUG] 接口测试mock中后置脚本打印不生效

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17509]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

接口测试mock中后置脚本打印不生效

### 重现步骤

添加后置脚本
![image](https://user-images.githubusercontent.com/103925124/187113616-f8159f06-87fc-4ffe-9b66-2ae41a0917f6.png)
后点击执行
![image](https://user-images.githubusercontent.com/103925124/187113712-9d5be867-9479-49c0-8347-6a1bf13a2f1d.png)
控制台无新增打印
![image](https://user-images.githubusercontent.com/103925124/187113767-eb41df4c-aa4d-4647-898b-e54b0a88091c.png)

### 期待的正确结果

接口测试mock中后置脚本打印可生效

**Comment by xulinde** [comment]
设计如此。
控制台打印的是jmeter运行中的日志。 mock接口服务个功能和jmeter没有任何关系。 换句话讲，甚至可以用浏览器来访问一个get请求的mock接口。  这里没有任何输出日志的必要。 

如果想要调试，可以使用vars.put（参数），并在返回请求体中输出该参数
