### ISSUE TITLE
[BUG]通過URL方式導入接口解析失敗

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#17502]
### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

同個接口，通過URL方式導入接口解析失敗。但是通過JSON文件導入正常。之前兩種方式都是可以的

### 重现步骤

使用URL方式導入

### 期待的正确结果

導入成功

### 附加信息

![1661608733142](https://user-images.githubusercontent.com/37204403/187033509-d1e7fc28-c6eb-458a-819e-275152c5ed94.png)

**Comment by zyyfit** [comment]
您好，方便把您swagger的内容给我们看一下吗？我用这个地址测试是正常的
https://api.swaggerhub.com/apis/YANGYANGZHANG/MeterSphereImport/1.0.0

![image](https://user-images.githubusercontent.com/73461316/187112633-ab722eaa-17ac-48ec-ab02-a78ec347fde0.png)
