### ISSUE TITLE
[BUG]数据库连接请求不成功

### ISSUE THREAD

**Issue by shijie233** [metersphere/metersphere#17500]
### MeterSphere 版本

不清楚

### 使用外置数据库

是

### 问题描述

metersphere连接数据库连接失败，同样的连接串，账号密码一样在jmeter连接成功

返回错误如下：
{"success":false,"message":"Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.","data":null}

### 重现步骤

不清楚是什么版本
<img width="552" alt="image" src="https://user-images.githubusercontent.com/102729268/187017409-55e7f149-2941-47e3-889e-0f30896dc4f7.png">

**Comment by zyyfit** [comment]
请问链接的是什么数据库呢？数据库版本是什么？

**Comment by shijie233** [comment]
格桑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]数据库连接请求不成功 (Issue #17500)





 
请问链接的是什么数据库呢？数据库版本是什么？

**Comment by zyyfit** [comment]
邮件回复的消息显示不太正常，方便网页回复一下吗
![image](https://user-images.githubusercontent.com/73461316/187159403-42bc0a67-dafc-4e45-83db-4d633b4435d6.png)

**Comment by shijie233** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/102729268/187159888-77850ab8-e983-4a3c-8727-934507cd4ce6.png">

**Comment by zyyfit** [comment]
您先把数据库连接地址换成IP试试？另外，您的ms没有版本号，是自己拉代码打包的吗？

**Comment by shijie233** [comment]
问题维护团队，说是现在生产环境和测试环境是隔离的，没明白啥原因，有没有python脚本连接数据库模版？

**Comment by zyyfit** [comment]
脚本连接数据库？不是直接在环境配置里添加数据库？

**Comment by shijie233** [comment]
环境配置里添加数据库这不是报错了嘛，就想问问直接使用自定义脚本写python脚本连接可不可行
