### ISSUE TITLE
[BUG] UI自动化场景列表页，部分场景创建人信息为空，但是后台数据库表ui_scenario里的user_id和create_user都是有用户信息。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17505]
### 联系方式

王进

### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

UI自动化场景列表页，部分场景创建人信息为空，但是后台数据库表ui_scenario里的user_id和create_user都是有用户信息。

### 重现步骤

1. 现在复现不出来，但是用户环境有这个问题：
![1661739615429](https://user-images.githubusercontent.com/76033005/187110295-129605e2-9822-4c9f-bdb2-89d078bdbc86.png)
2. SELECT id,user_id, create_user FROM metersphere.ui_scenario 去查，可以看到所有场景都是有user_id和create_user信息
![1661739717448](https://user-images.githubusercontent.com/76033005/187110577-5571ba24-edff-4844-86a5-5dd03510cf25.png)

### 附加信息

客户环境的登录信息我有，如果需要看，随时联系我。

**Comment by xulinde** [comment]
v2.1.1已修复～
