### ISSUE TITLE
[BUG] 场景中使用枚举，执行接口，请求内容未使用枚举值

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17514]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

场景中使用枚举，执行接口，请求内容未使用枚举值

### 重现步骤

点击这里设置了枚举值
![image](https://user-images.githubusercontent.com/103925124/187133374-da9637d8-76b2-4be2-8023-0b68f234d771.png)
![image](https://user-images.githubusercontent.com/103925124/187133596-8fd22028-f95a-415e-9dbd-65388075f0e9.png)
点击调试执行
![image](https://user-images.githubusercontent.com/103925124/187133706-f6285dda-55cd-4f2a-b9dd-a555e4ec228c.png)

### 期待的正确结果

场景中使用枚举，执行接口，请求内容使用枚举值进行请求

**Comment by xulinde** [comment]
v1.20.14-lts已修复～
