### ISSUE TITLE
[FEATURE]  接口参数均可设置枚举值，目前只有请求体开启JSON-SCHEMA后的高级设置里可设置枚举

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17515]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

接口参数均可设置枚举值（QUERY和REST参数可设置枚举值）

![image](https://user-images.githubusercontent.com/103925124/187134037-c03d293b-e974-4ab7-8842-843a034e239f.png)

### 请描述你建议的实现方案

接口参数均可设置枚举值（QUERY和REST参数可设置枚举值）

**Comment by luty2018** [comment]
感谢建议，我们调研一下
