### ISSUE TITLE
[FEATURE]性能测试缺少吞吐量控制器

### ISSUE THREAD

**Issue by traers** [metersphere/metersphere#17526]
### MeterSphere 版本

v1.20.12-lts-2297374a

### 请描述您的需求或者改进建议

和jmeter一样，增加吞吐量控制器，根据线上接口流量比例来控制各个接口的占比，来模拟真实场景的压测。
目前的RPS只能控制每秒请求数，并不能根据每个接口的占比来动态控制比重。

### 请描述你建议的实现方案

没有吞吐量控制器（jmeter）的压测是没有灵魂的，类似阿里PTS的最大并发权重。https://help.aliyun.com/document_detail/70480.htm?spm=a2c4g.11186623.0.0.17ee16cdhyNwXw#concept-70480

**Comment by traers** [comment]
没有吞吐量控制器的压测是没有灵魂的。

**Comment by Hyyfit** [comment]
可以支持的，我们在2.4的版本之后，会陆续做性能测试的需求
