### ISSUE TITLE
[BUG] 接口api参数定义枚举后，预览成功，JSON-SCHEMA关闭后再打开，查看枚举，已被删除（场景内接口同现象）

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17523]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

接口api参数定义枚举后，预览成功，JSON-SCHEMA关闭后再打开，查看枚举，已被删除

### 重现步骤

接口下设置枚举
![image](https://user-images.githubusercontent.com/103925124/187145931-3d539ec0-4a1e-40ad-8db5-39d1800b907a.png)
关闭JSON-SCHEMA后显示
![image](https://user-images.githubusercontent.com/103925124/187146801-cb838dd4-3c93-47fc-83f8-e025a2ed10dd.png)
再次打开JSON-SCHEMA后查看高级配置，已为空
![image](https://user-images.githubusercontent.com/103925124/187146937-7ce8790e-4cd4-4617-b18b-60c104e9044c.png)

### 期待的正确结果

设置枚举后关闭JSON-SCHEMA，再打开JSON-SCHEMA，枚举数据正常

**Comment by xulinde** [comment]
设计如此～关了jsonschema后，就不能给json请求设置这些东西了

**Comment by Hyyfit** [comment]
设计如此。
