### ISSUE TITLE
[BUG]升级1.8，之前场景里设置的断言规则 默认变成了正则，导致断言报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#1752]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8.0
**Bug 描述**
简要描述您碰到的问题
1.升级1.8，之前场景里设置的断言规则为=，但是变成了正则，导致断言报错
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
之前这里默认就是用的正则，新版本只是加了这个选项而已

**Comment by shenkaibo** [comment]
好的 了解了
