### ISSUE TITLE
[BUG]我把metersphere的接口自动化中的50个场景导入到一个新场景中运行时控制台报错。这些场景单独运行都是没问题的，就是导入到一个新的场景中控制台就报这个错了，并且运行时也有大量报错了。详见下图

### ISSUE THREAD

**Issue by Thisisasnail** [metersphere/metersphere#17539]
### 联系方式

交流群47，柚子，邮箱liuyoushun@aliyun.com

### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 使用外置数据库

是

### 问题描述

![5afe5d515ced3ffa5f1a562c41a5e42](https://user-images.githubusercontent.com/63831219/187159903-40b6f8a1-bb7f-4355-9468-8ca3420b9fa5.jpg)
![c14af3acc0aaa4e9bd0342615fed2ca](https://user-images.githubusercontent.com/63831219/187160044-dd2dac7b-7a8a-4bcf-ba0b-39dc0a4c4e1d.jpg)

### 重现步骤

把metersphere的接口自动化中的50个场景导入到1个新场景中运行，每个场景可能有多个接口，总共大约有三十个左右的sql在前置和后置处理中，用于参数化和断言。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，看报错信息是场景中请求之间的sql变量名有相同的导致，后续版本我们会优化。

**Comment by Thisisasnail** [comment]
把其中有相同的sql变量名改了，再运行，改了的这些也会报错。希望得到优化
