### ISSUE TITLE
[BUG] 场景中导入一个已设置枚举的接口，打开JSON-SCHEMA，预览界面执行场景，界面错误停留在预览窗口，非模板窗口

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17535]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

场景中导入一个已设置枚举的接口，打开JSON-SCHEMA，预览界面执行场景，界面错误停留在预览窗口，非模板窗口

### 重现步骤

接口中设置参数枚举值
![image](https://user-images.githubusercontent.com/103925124/187153381-d3bcdd57-b84d-4a08-ad86-0ece702e9860.png)
导入场景后，打开JSON-SCHEMA，预览界面执行场景
![image](https://user-images.githubusercontent.com/103925124/187143204-3bc35255-0144-4d57-bee1-9748ee2db2ea.png)
界面错误停留在预览窗口，非模板窗口
（导致预览需手动刷新切到模板再切到预览）

**Comment by xulinde** [comment]
内部同事，已私信说明
