### ISSUE TITLE
[BUG] UI测试，UI自动化，生成报告模式（没有勾选“性能模式”, Chrome, 生成报告）截图不见了

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17534]
### 联系方式

王进

### MeterSphere 版本

 v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

UI测试，UI自动化，生成报告模式（没有勾选“性能模式”, Chrome, 生成报告）截图不见了

### 重现步骤

1. UI测试，UI自动化，生成报告模式（没有勾选“性能模式”, Chrome, 生成报告） 调试一个UI自动化场景
![Uploading 1e4c72084ae468847339347df4593c8.png…]()

### 期待的正确结果

之前一直有截图

**Comment by xulinde** [comment]
没有复现，只有失败的步骤才有截图，你那边如果是必现，详细描述下步骤～
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/64065190/187408525-359d5e8c-17a0-4ac7-9aad-0eb4babc3bbc.png">

**Comment by 35plus** [comment]
这个问题是问题，大海说在改了。
