### ISSUE TITLE
[BUG] api接口为空时新建api，测试计划进行关联，此时api列表为空，无法导入

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17546]
### 联系方式

18311441708

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

 api接口为空时新建api，测试计划进行关联，此时api列表为空

### 重现步骤

api列表为空，后新建api
![image](https://user-images.githubusercontent.com/103925124/187167713-5fe79548-20b0-44cc-9563-5460e7583dc3.png)
新建测试计划导入接口用例，api列表为空
![Uploading image.png…]()

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划里面关联的是接口CASE，如果api没有case，就不会显示api列表。
