### ISSUE TITLE
[BUG]post请求体里一使用变量就会报错JSON parse error: Unrecognized character escape ' ' (code 32)；不使用变量，把该参数写死，就能调试成功；把使用变量和写死两种情况metersphere发送的数据包抓包了一下，发现这俩发送出去的数据包不一样，使用变量的时候metersphere对json格式处理存在问题，少了好多反斜杠\

### ISSUE THREAD

**Issue by huangyingying0920** [metersphere/metersphere#17556]
### 联系方式

13770508236

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

post请求体里一使用变量就会报错JSON parse error: Unrecognized character escape ' ' (code 32)；不使用变量，把该参数写死，就能调试成功；把使用变量和写死两种情况metersphere发送的数据包抓包了一下，发现这俩发送出去的数据包不一样，使用变量的时候metersphere对json格式处理存在问题，少了好多反斜杠\
报错信息如下：
JSON parse error: Unrecognized character escape ' ' (code 32); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unrecognized character escape ' ' (code 32)\n at [Source: (PushbackInputStream); line: 1, column: 512] (through reference chain: com.fit2cloud.container.dto.CsProductDTO[\"composeYamlFile\"])

使用变量时调试结果、请求内容返回值、场景变量定义如下：
![9b711b9451b9b07502a3bf44a127692](https://user-images.githubusercontent.com/86640481/187332445-7b2d03f8-555f-4dd4-aae5-8aa9ca62b65d.jpg)
![103d0d7b51cc73618f041f684fa9ccf](https://user-images.githubusercontent.com/86640481/187332517-67f772c4-2cee-4e6e-99f4-0c026122397a.jpg)
![c30e84d175c9568cdd4ba8437b2fa4f](https://user-images.githubusercontent.com/86640481/187332590-979d3e2f-759a-4ed1-8263-f7a4cebb68f2.jpg)

直接把参数写死时调试结果如下：
![25d7224c49040e01803372672c75aac](https://user-images.githubusercontent.com/86640481/187332564-a7f854a7-58cc-4844-b481-014b9f5a31bb.jpg)

使用变量和把参数写死对应的metersphere发送的数据包：

[变量随机和参数写死对应的数据包.zip](https://github.com/metersphere/metersphere/files/9449029/default.zip)
![7655f1898e61f468ff6a06428b17a5a](https://user-images.githubusercontent.com/86640481/187333356-69d40de5-567c-4c2e-90aa-13d95187eb51.png)
![d61239796467576260ef2bd1bb6a3e5](https://user-images.githubusercontent.com/86640481/187333359-713b8716-d0f0-45ff-bba4-647eab18a948.jpg)

### 重现步骤

使用参数变量就能重现问题

### 期待的正确结果

对发出去的数据包json格式处理正确

**Comment by youliyuan-fit2cloud** [comment]
你好，在v2.1.0 版本中没有复现该问题，建议升级一下试试吧。
