### ISSUE TITLE
[BUG]  点击子模块，脑图显示异常用例重叠<偶现，多为初次渲染显示>

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17551]
### 联系方式

18311441708

### MeterSphere 版本

v2.1-af91f9ef

### 使用外置数据库

否

### 问题描述

点击子模块，脑图显示异常用例重叠

### 重现步骤

Windows，谷歌浏览器100比例，浏览器全展开，分辨率2520*1440

点击最子集模块
![image](https://user-images.githubusercontent.com/103925124/187177681-497e3ebc-2b59-4bc3-8232-ac33be76ebbb.png)

![image](https://user-images.githubusercontent.com/103925124/187174321-1539fce0-14f1-454d-aed5-b1a31adc1f6f.png)

**Comment by xulinde** [comment]
v2.3已修复～
