### ISSUE TITLE
[BUG]升级到v1.8.0以后定时作业初始化失败

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#1755]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.8.0

**Bug 描述**
定时任务无法执行，查看日志发现： ERROR i.m.service.ScheduleService 141 - Method[lambda$startEnableSchedules$0][初始化任务xxx

**截图**
如果有截图，请附上截图.
![ms-20210330异常作业](https://user-images.githubusercontent.com/22386206/112933405-5f785700-9152-11eb-8a88-116df2cc7fc8.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zh417233956** [comment]
@zyyfit 跟进一下

**Comment by zyyfit** [comment]
> @zyyfit 跟进一下

您好，现在已经发布了1.9.2版本，您升级一下看看还有这个问题吗
