### ISSUE TITLE
[BUG]浏览器页面最小化挂一晚上后，第二天打开直接死机

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#17554]
### 联系方式

QQ 61857543

### MeterSphere 版本

至少 v1.18.0 -- v1.20.12

### 使用外置数据库

是

### 问题描述

我浏览器开了两三个Metersphere页面，然后切到别的页签，把浏览器最小化挂一晚上（12小时以上）后，第二天早上打开直接死了，报了一串 Network Error ，浏览器对应页签进程CPU占用100%，对应页签毫无反应，杀掉页签进程才恢复。

同时，后台MySQL数据库CPU占用100%，排查发现这个spring boot工程一直在反复查notification表，查一次要花20秒（该表目前只有不到2万条记录），然后查了几千上万次，运行msctl restart后解决。

这个问题好像从年初刚开始用的时候到现在一直存在，我每天早上都要杀一次进程，就挺烦的。

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化一下。

**Comment by genezx** [comment]
实测只要在notification表上加一个 (receiver, create_time) 的联合索引后问题就消失了，建议把索引也加上。
