### ISSUE TITLE
[FEATURE] 接口场景测试报告无法自动清理

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#17555]
### MeterSphere 版本

v1.20.12

### 请描述您的需求或者改进建议

接口场景测试报告无法自动清理，api_scenario_report_result 这张表现在已经10多个G了。

### 请描述你建议的实现方案

建议加入自动清理N天以前报告的功能。

**Comment by luty2018** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/36292514/187338367-a0eb1fb5-6413-4a9c-974c-2a77c55bb3b5.png">
已提供清理报告功能了

**Comment by genezx** [comment]
看到了，谢谢
