### ISSUE TITLE
[BUG]测试跟踪-功能用例，在测试计划执行通过后，附件被删除

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#17568]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20.4-lts-b1

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例,编写用例后，上传附件。新建测试计划，执行该用例，附件被删除。
这个已经是发现的第二个无缘无故删除附件的bug了，希望能尽快解决，因为这种问题大家已经在疯狂吐槽ms了，很多人都在怀念以前使用禅道的日子。

### 重现步骤

1，测试跟中-功能用例，新建一个测试用例，上传一个附件
2，点击测试计划，新增一个测试计划，关联1步骤中的测试用例
3，点击该用例进行回归测试，点击通过
备注：执行测试用例的时候，不要点击附件这个标签，就在默认的备注下点击用例状态通过
结果：
回到测试用例中，查看该测试用例，发现测试用例的附件被删除了

### 期待的正确结果

1，测试计划中不应该更改测试用例的核心信息
2，删除文件能做成软删除，否则找都找不回来

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们尽快修复该问题。

**Comment by xulinde** [comment]
v1.20.13-lts已修复～
