### ISSUE TITLE
[BUG]缺陷对接了JIRA或者禅道等第三方平台，缺陷管理列表加载数据响应慢

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#17569]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.1

### 使用外置数据库

否

### 问题描述

缺陷对了JIRA或者禅道等第三方平台，缺陷管理列表加载数据响应慢

### 重现步骤

1、对接JIRA或者禅道平台
2、点击测试跟踪-缺陷管理页面，页面大概需要几秒才能刷新出来，并且在加载过程中，只显示操作列，如下：
![image](https://user-images.githubusercontent.com/35896106/187360792-069c9053-84cb-4c38-bc38-36fe0042e401.png)

### 期待的正确结果

希望可以优化加载速度，并且最好在加载的时候有个缓存页面，而不是像上面截图一样只展示操作列

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0版本中已优化。
