### ISSUE TITLE
[BUG]UI测试，“输入操作”，内容加入特殊字符（\n），测试报告，截图输入框，后面文本不会显示

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17564]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

使用UI测试，UI自动化场景里面，添加一个文本输入框，文本里面输入内容，包含特殊字符串（\n），测试报告里面，特殊字符串后面文字不会显示

### 重现步骤

UI测试，文本输入内容：
![image](https://user-images.githubusercontent.com/15188833/187345243-b73300ed-6345-4404-8110-95a9f334acf2.png)

测试报告结果：
![image](https://user-images.githubusercontent.com/15188833/187345314-7acf5074-3e93-490a-bf40-939258d53237.png)

**Comment by xulinde** [comment]
当前没有处理特殊字符， 转义字符 \n 会被当成换行符
