### ISSUE TITLE
[BUG]用例导出excel修改之后在导入会提示[责任人]必须当前项目成员，发现导入需要把责任人改成ID

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#17570]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.1

### 使用外置数据库

否

### 问题描述

用例导出excel修改之后在导入会提示[责任人]必须当前项目成员，发现导入需要把责任人改成ID

### 重现步骤

1、导出用例
![image](https://user-images.githubusercontent.com/35896106/187363215-f6fec09c-d1a9-44f6-93e3-c9db5543974d.png)
2、修改用例内容，其中责任人没有修改
3、导入用例，选择导入更新，提示第 2 行出错：[责任人]必须当前项目成员
![image](https://user-images.githubusercontent.com/35896106/187363386-4840caf4-e4bc-49b2-872c-0ba8259f1926.png)
4、找到责任人对应的ID，把责任人姓名改成ID可以正常导入
![image](https://user-images.githubusercontent.com/35896106/187364109-1f88da1c-3017-430d-93a6-b91f1ddd7a4d.png)

### 期待的正确结果

期望导出的用例不用修改责任人为ID也能正常导入

**Comment by xulinde** [comment]
后面会改成名称和ID都可以导入

**Comment by xulinde** [comment]
v2.1.1已修复～
