### ISSUE TITLE
[BUG]测试计划一旦关联测试用例，状态直接变更为“已结束”

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#1757]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8

**Bug 描述**
测试计划一旦关联测试用例，状态直接变更为“已结束”

**Bug 重现步骤**
1.  登录
2. 创建1个测试计划，只填必填项（此时状态为“未开始”）
3. 进入该测试计划，关联测试用例
4. 查看该测试计划的状态

**期待的正确结果**
依然为“未开始”

**截图**
目前是“已结束”

**Comment by xulinde** [comment]
v1.8.1会修复

**Comment by zyyfit** [comment]
v1.8.2已修复了这个问题
