### ISSUE TITLE
[BUG] 接口运行环境使用模块，调试接口，未取到域名ip信息

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17577]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

接口运行环境使用模块，调用接口，未取到域名ip信息

### 重现步骤

接口运行环境使用模块
![image](https://user-images.githubusercontent.com/103925124/187381579-791090d9-e1c1-468d-8ea1-11d7a6e263ef.png)
调试接口，未取到域名ip信息
![image](https://user-images.githubusercontent.com/103925124/187381723-f5b25404-6e80-494f-9ab1-e0c91ba430ec.png)

### 期待的正确结果

接口运行环境使用模块，调试接口，可正确取到域名ip信息

### 附加信息

如果环境中有 启用条件为无的，调试接口时，会取到启动条件为无的域名ip

**Comment by xulinde** [comment]
v1.20.13-lts已修复～
