### ISSUE TITLE
[FEATURE]  UI测试第一步执行时间长，建议初始化时间和第一步执行时间分开计算

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17576]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

UI测试第一步执行时间长，建议初始化时间和第一步执行时间分开计算

![企业微信截图_16618422061770](https://user-images.githubusercontent.com/103925124/187375206-15d66da2-1e8f-4aee-9949-f508b1ac4d6b.png)

第一个用例开始时间 14:41:19  最后一个用例的结束时间 14:43:30  .  但是从控制台看这段处于做一些连接护着初始化阶段
第二个用例开始时间是 14:43:27 ，从第二个开始，后面几个用例执行的都很快

### 附加信息

![企业微信截图_16618422689025](https://user-images.githubusercontent.com/103925124/187374935-bbd025bc-001d-4f93-842a-02c6a527e301.png)

**Comment by Hyyfit** [comment]
这个等我们UI脚本拆分后，可以考虑实现，现阶段做不了。
