### ISSUE TITLE
[BUG]接口调试QUERY参数选择编码后，未进行编码，展示的转换函数

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17589]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

接口调试QUERY参数选择编码后，未进行编码
![image](https://user-images.githubusercontent.com/103627487/187412151-0a01f133-d65c-4c22-8cbc-864d830f9e88.png)
![screenshot-20220830-180924](https://user-images.githubusercontent.com/103627487/187411068-56c63baa-38ba-41da-8079-44c263c9177a.png)
试了下jmeter可以转换
![image](https://user-images.githubusercontent.com/103627487/187411879-47846203-86ae-459a-a96b-d3a774b597c9.png)
![image](https://user-images.githubusercontent.com/103627487/187411759-77e99fef-d546-4ccf-a752-e31023f4c24e.png)

### 重现步骤

1、接口调试QUERY参数选择编码
![image](https://user-images.githubusercontent.com/103627487/187412340-a77b2b64-8656-4672-88f0-2285c3d8e05f.png)
2、QUERY参数输入值（{"schemeId":"182","planId":"","batchId":""}）
![image](https://user-images.githubusercontent.com/103627487/187412582-08bf0554-8d6a-4402-bbe6-0d9830dcde71.png)
3、点击调试

### 期待的正确结果

期望可以正常转换

**Comment by xulinde** [comment]
,转义下就可以了

**Comment by zhangzhaox** [comment]
> ,转义下就可以了

关键是有的时候又不需要转义

**Comment by xulinde** [comment]
json数据 只有一对不需要转义，数组的需要转义

**Comment by meijieDouDou** [comment]
这个方便优化下吗？1.用户那边很多这种的，一个个转义比较麻烦。2.很多用户都不太清楚什么时候转义，什么时候不转义，使用时不方便。3.jmeter目前数组的也可以不转义可转换，这个感觉也可以优化下呢？

**Comment by xulinde** [comment]
> 这个方便优化下吗？1.用户那边很多这种的，一个个转义比较麻烦。2.很多用户都不太清楚什么时候转义，什么时候不转义，使用时不方便。3.jmeter目前数组的也可以不转义可转换，这个感觉也可以优化下呢？

jmeter也需要转义
