### ISSUE TITLE
[BUG]接口测试>>接口定义>>Case：接口参数类型为file，上传文件名称含有中文，执行后，在请求体里展示的文件名为乱码。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17583]
### MeterSphere 版本

V2.0 和V1.20.12lts

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口定义>>Case：
1、条件：接口参数类型为file，
2、上传文件名称含有中文，
3、点击执行后，在响应内容中，请求内容体里展示的文件名为乱码。

### 重现步骤

[BUG]接口测试>>接口定义>>Case：
1、条件：接口参数类型为file，
2、上传文件名称含有中文，
3、点击执行后，在响应内容中，请求内容体里展示的文件名为乱码。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/187393020-23697711-b792-4156-a6ad-8c5e0f69124e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个是jmeter的bug，目前我们还没更好的解决办法。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #15764

**Comment by xyziven** [comment]
可以参考，接口请求中需要加一个Content Encoding设置项

https://www.cnblogs.com/xiaofeng91/p/13490418.html

**Comment by youliyuan-fit2cloud** [comment]
> 可以参考下面的链接，接口请求中需要加一个Content Encoding设置项
> 
> https://www.cnblogs.com/xiaofeng91/p/13490418.html

这解决的事请求内容，不是附件编码。

**Comment by xchnshi** [comment]
@youliyuan-fit2cloud jmeter 看着在新版本中已经修复，v2.x版本是否会考虑升级一下？
https://github.com/apache/jmeter/issues/4546

**Comment by xchnshi** [comment]
另外MeterSphere JMeter Functions是没开源的部分，能开源吗？好像jmeter版本修改是这里修改后才生效？

**Comment by xchnshi** [comment]
@luty2018 也请帮忙看一下
