### ISSUE TITLE
[BUG]之前已覆盖点进去会筛选已经关联的用例现在不行了

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#17588]
### MeterSphere 版本

版本:   v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

之前首页 功能用例 已覆盖 点击进去 会只显示已经覆盖的用例  现在点击进去是所有的用例

### 重现步骤

首页点击已覆盖数量

### 期待的正确结果

显示的是132条 列表应该只有132 而不是所有的用例

### 附加信息

![image](https://user-images.githubusercontent.com/26948634/187409151-d77bf63a-a05b-4325-aa37-4d5424b892d5.png)

**Comment by Xin7S** [comment]
新增的数量 之前点进去也只会有新增的那几条数据  现在点进去就是所有的功能用例

**Comment by xulinde** [comment]
后续版本会统一优化～

**Comment by xulinde** [comment]
v2.2.0已修复～
