### ISSUE TITLE
[BUG] 场景变量随机值中带特殊符号，使用不符合预期，符号“.”顺序错误

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17584]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

场景变量随机值中带特殊符号，使用不符合预期，符号“.”顺序错误

### 重现步骤

场景变量中添加如下随机值：test_0000@uuf.me
![image](https://user-images.githubusercontent.com/103925124/187395342-82d3452b-fe0e-411f-adb5-a25a89d086fc.png)
场景接口中调用如下
![image](https://user-images.githubusercontent.com/103925124/187395663-0a832f17-14cf-4480-b4f0-355a04ecdf1a.png)

### 期待的正确结果

场景变量随机值中用test_0000@uuf.me，出现test_0006@uuf.me

**Comment by youliyuan-fit2cloud** [comment]
目前JMeter也不支持输出格式为test_0000@uuf.me这种的，JMeter官方建议输出格式为test_000、test000这种
![image](https://user-images.githubusercontent.com/54612864/188556531-e6192be7-7350-4e29-b845-517bbaaa7788.png)
