### ISSUE TITLE
[QUESTION] MS-Server 连接不上Redis，请问如何解决？

### ISSUE THREAD

**Issue by langsz** [metersphere/metersphere#17587]
### 请描述您的问题

metersphere v2.1.0-b1
服务器上防火墙关闭；在PC端可以连上redis。
但是ms-server一直连不上，报错大致如下
 WARN   org.eclipse.jetty.webapp.WebAppContext: 533 - Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@19aa9540{application,/,[file:///tmp/jetty-docbase.8443.562544030235710024/, jar:file:/app/lib/swagger-ui-4.1.3.jar!/META-INF/resources],UNAVAILABLE}
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.shiro.spring.config.web.autoconfigure.ShiroWebFilterConfiguration': Unsatisfied dependency expressed through field 'filterMap'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.session.RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'redissonConnectionFactory' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Unsatisfied dependency expressed through method 'redissonConnectionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisson' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: Unable to connect to Redis server:

**Comment by ShallowHui** [comment]
可以试试下面的命令：
iptables -A INPUT -p tcp --dport 6379 -j ACCEPT
