### ISSUE TITLE
[BUG] 性能测试未设置监控信息，导出性能报告为pdf，部分数据丢失，有表格重叠<有监控机器时pdf正常>

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17585]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

性能未设置监控信息，导出性能报告为pdf，部分数据丢失，有表格重叠

### 重现步骤

性能测试未设置监控信息，导出性能报告为pdf
![image](https://user-images.githubusercontent.com/103925124/187397193-b9ab008c-5117-482f-ae85-c76e67a0c032.png)
查看下载的pdf
![image](https://user-images.githubusercontent.com/103925124/187397493-11f8ca3f-85cb-4666-952f-cec6d9eb3d86.png)
![image](https://user-images.githubusercontent.com/103925124/187398482-65a876ab-8a33-451b-b7ae-0e17df397d44.png)

### 期待的正确结果

性能未设置监控信息，导出性能报告为pdf，无数据丢失，无表格重叠

### 附加信息

[测试事务无监控.pdf](https://github.com/metersphere/metersphere/files/9451477/default.pdf)
[测试事务ycr有监控.pdf](https://github.com/metersphere/metersphere/files/9451479/ycr.pdf)

**Comment by youliyuan-fit2cloud** [comment]
已知问题，后续版本会修改性能大部分问题。
