### ISSUE TITLE
[FEATURE]  前后置脚本的框大小默认小一些，并且大小可随换行自动调大，或者用户可下拉调大

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17598]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

有些脚本内容很少，但是脚本框占用页面过大
![image](https://user-images.githubusercontent.com/103925124/187583046-4b9d0a7d-2b8d-4fa4-9d07-76e5a7bc0c3c.png)

想截图给研发人员看看（脚本连带请求内容），一大片空白，截不到一起

页面优化下~

**Comment by Hyyfit** [comment]
好的，可以优化的。
