### ISSUE TITLE
[BUG]导入postman导入ms，点击“修改”，在“TEST”页面环境无法引用到http路径

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17590]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

2.0.1

### 使用外置数据库

否

### 问题描述

导入postman接口，然后导入到MS平台，“编辑”接口，在“TEST”页面，引用环境，执行接口，没有http路径显示，http路径根据模块进行绑定。在case里面，执行接口成功。

### 重现步骤

环境里面配置http路径：
![image](https://user-images.githubusercontent.com/15188833/187421139-1c7e7f1a-47e2-4b02-ba4b-73055377f8fc.png)

在“TEST”里执行接口：
![image](https://user-images.githubusercontent.com/15188833/187421245-ac2c71b4-42ec-4201-935b-934a84494d8d.png)

返回结果：
![image](https://user-images.githubusercontent.com/15188833/187421336-48f938c0-750a-42e1-9b66-7a45bd89cbc1.png)

接口case执行，返回正确的http路径：
![image](https://user-images.githubusercontent.com/15188833/187421542-22e1ec19-1a4f-4e3a-a0c6-962bf8841f2d.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #17577
