### ISSUE TITLE
[FEATURE]  接口请求体预览可复制

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17597]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

接口请求体预览可复制
![image](https://user-images.githubusercontent.com/103925124/187580802-003f6c44-73f3-4bd3-ac10-d43397f27c62.png)

**Comment by Hyyfit** [comment]
关闭JSON-SCHEMA,就是json的预览格式了，可以复制的。

**Comment by Ycr123888** [comment]
好的
