### ISSUE TITLE
[FEATURE]  接口mock中后置脚本使用场景模糊，用户不易用

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17599]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

起初发现后置脚本中不可log.info();
![image](https://user-images.githubusercontent.com/103925124/187581084-043b3aa8-e885-469e-ac00-9b76d5e03f0e.png)
属于设计如此。
控制台打印的是jmeter运行中的日志。 mock接口服务个功能和jmeter没有任何关系。 换句话讲，甚至可以用浏览器来访问一个get请求的mock接口。 这里没有任何输出日志的必要。
如果想要调试，可以使用vars.put（参数），并在返回请求体中输出该参数
![企业微信截图_623ba31c-2482-45b1-9a1f-e11afd255c13](https://user-images.githubusercontent.com/103925124/187581831-18423c1e-4a45-45c1-b389-85bac7955700.png)

还是没有使用起来，是后置放入token之类的到环境变量嘛

### 请描述你建议的实现方案

给个可实现场景的例子在后置脚本框里

![image](https://user-images.githubusercontent.com/103925124/187584030-57ba6613-1a90-42df-871f-8d3b927cad93.png)

**Comment by Hyyfit** [comment]
这个说明类的，可以在用户手册中补充的。

**Comment by Ycr123888** [comment]
不只是补充的问题了，不知道咋用后置脚本，以及后置脚本的使用场景

**Comment by Ycr123888** [comment]
mock的后置脚本使用场景和咋使用未知，麻烦示例一下

**Comment by luty2018** [comment]
mock的后置脚本同接口中的一致，使用场景是看业务场景是否需要后置处理，你可以参考官网的前后置脚本的应用示例
