### ISSUE TITLE
[BUG]接口自动化的请求地址采用环境参数传参的方式，会导致请求地址多出”HTTP“，从而导致请求失败

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#17592]
### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

问题背景：
由于场景中不同的接口采用不同的环境，为了便于操作采用了传参的方式来进行请求协议类型以及服务器地址的拼接到请求URL上
问题现象：
MS v2.0版本可以使用环境参数或全局前置脚本设置请求协议以及服务域名的方式传参到接口自动化自定义请求中，可以正常发起请求，升级到v2.1版本后，请求URL前会自动加上”http”导致传参失败
1.环境参数：
<img width="925" alt="截屏2022-08-30 下午10 59 46" src="https://user-images.githubusercontent.com/34637801/187471275-90b2b262-8111-4a7f-a35b-0fed878b87fe.png">
2.接口自动化自定义请求：
<img width="923" alt="截屏2022-08-30 下午11 00 21" src="https://user-images.githubusercontent.com/34637801/187471422-f91a51b7-91fe-4eea-94be-cd93fbabc571.png">
3.请求结果：
<img width="1114" alt="截屏2022-08-30 下午11 00 58" src="https://user-images.githubusercontent.com/34637801/187471555-f5cbbc45-5f1d-430d-a3f7-b67f1769fc97.png">

### 重现步骤

1.在环境的“通用配置”中设置请求协议和服务器域名两个变量
<img width="892" alt="截屏2022-08-30 下午11 02 13" src="https://user-images.githubusercontent.com/34637801/187471845-19ac414d-909e-4a6b-bc9d-86471a94fd7c.png">
2.在接口自动化中创建自定义接口，其中接口协议和请求地址用上一步骤的变量
<img width="923" alt="截屏2022-08-30 下午11 03 20" src="https://user-images.githubusercontent.com/34637801/187472101-600a1a27-0f43-4069-ab62-42d91f422807.png">
3.选择对应的环境进行执行。

### 期待的正确结果

能正确的发起请求

**Comment by youliyuan-fit2cloud** [comment]
v2.1.1版本中已修复该问题。
