### ISSUE TITLE
[BUG]服务集成-缺陷管理平台中集成jira，测试链接提示失败，在后台查看日志是乱码

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#1759]
**MeterSphere 版本**
V1.8

**Bug 描述**
缺陷管理平台中集成jira，测试链接提示失败，在后台查看日志是乱码(jira是v7.3.6)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
<img width="1031" alt="111111" src="https://user-images.githubusercontent.com/21210217/112969215-9f096800-917f-11eb-815c-292201d25270.png">

**Comment by shiziyuan9527** [comment]
看错误是账号，密码的问题，请参考 Jira software server 认证信息为 账号密码，Jira software cloud 认证信息为 账号+令牌(账户设置-安全-创建API令牌)。如果还是失败，请进群交流。
