### ISSUE TITLE
[FEATURE]UI测试，将提取到的变量，希望能输出到控制台或者步骤结果中。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17591]
### MeterSphere 版本

v1.20.10

### 请描述您的需求或者改进建议

UI测试，提取到的元素对象，希望能输出到控制台或者步骤结果中。
<img width="423" alt="1661858008(1)" src="https://user-images.githubusercontent.com/104960608/187422549-3654b877-466c-4079-bfa2-2f809459f57e.png">

<img width="480" alt="1661858076(1)" src="https://user-images.githubusercontent.com/104960608/187422772-793adc4c-911c-44c2-8b9a-e4df5211c1e6.png">

**Comment by Hyyfit** [comment]
我们有在规划这个功能，还没排期上。
