### ISSUE TITLE
[BUG] 场景测试全屏模式在切换前置脚本时脚本内容不变化

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1760]
**MeterSphere 版本**
1.8.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  场景测试全屏模式；给接口增加两个同级的前置脚本
2. 单击左侧脚本节点；右侧脚本名称变但是内容没变
3. 
4. 

**期待的正确结果**
脚本内容和脚本名称一起变

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.8.1会修复该问题

**Comment by xulinde** [comment]
1.8.2已修复
