### ISSUE TITLE
[FEATURE] 【接口】接口加废弃状态，不会被接口用户数量统计到

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17602]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

对于一些已经导入，但是应用端已经废弃的接口，除了删除接口，有没有个地方能暂存又不会被统计到

![187633937806585036](https://user-images.githubusercontent.com/103925124/187585735-2250121f-e208-4df4-8828-5d60d796dbeb.jpg)

**Comment by Hyyfit** [comment]
待调研后规划
