### ISSUE TITLE
[BUG] 接口参数中使用beanshell函数引用三方jar包中方法，值为空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17609]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

接口参数中使用beanshell函数引用三方jar包中方法，值为空
加解密功能
![image](https://user-images.githubusercontent.com/103925124/187610569-9312daac-dc6c-4ca1-9656-a551641cc314.png)

${__BeanShell(import com.jsfund.demo.utils.JmeterUtils;JmeterUtils jmeterUtils = new JmeterUtils();String pwd = jmeterUtils.encrypt('123456');return pwd;,beanshell)}

补充：脚本中也不支持：（jmeter也不支持）
![image](https://user-images.githubusercontent.com/103925124/187611042-e6ac9c18-9db3-4acd-8ad2-b50f842b5235.png)

### 重现步骤

jmeter请求中支持
<img width="871" alt="385766448933789150" src="https://user-images.githubusercontent.com/103925124/187646103-ae4ddc21-8e63-44ce-bb1d-4dd09d50ec30.png">

<img width="941" alt="86349225634807719" src="https://user-images.githubusercontent.com/103925124/187610835-4b6d8de9-0de0-4dd2-83c6-ecd35843a07e.png">

### 期待的正确结果

接口参数中使用beanshell函数引用三方jar包中方法，可传递正确的值

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我们看了一下，目前不支持这种用法，因为2.1版本的文件管理重构了，即使1.20版支持了，2.1版本及后面的版本也是不行的。
可以在脚本里先设置出这个变量，然后再调用
