### ISSUE TITLE
[FEATURE]LTS版本测试计划关联场景用例无法选择所有数据

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17618]
### MeterSphere 版本

1.20.12-LTS

### 请描述您的需求或者改进建议

LTS版本测试计划关联场景用例无法选择所有数据；
希望可以类似于测试计划关联接口用例时，有个checkbox用于全选，详情见下面附件截图

### 附加信息

测试计划关联接口用例：
<img width="1306" alt="WechatIMG339" src="https://user-images.githubusercontent.com/32027713/187631903-81c7b7bd-49b0-4712-8cfe-0cfecba8772c.png">

测试计划关联场景用例：
<img width="1327" alt="WechatIMG340" src="https://user-images.githubusercontent.com/32027713/187632109-fc6197dd-0b8c-4293-987b-6ff50ea7c516.png">

**Comment by Hyyfit** [comment]
功能已经有了，等LTS升级后就可以支持。
