### ISSUE TITLE
[BUG] 使用了宝路CSV参数化插件 导致场景设置页面不能展示参数化文件名称

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#17615]
### 联系方式

14群-亲山留水

### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/187626276-7c591779-a98d-4e1f-a58a-9cc2133d9733.png)
使用的第三方csv插件  导致场景sh设置页面不能展示参数化文件，早期版本是没有这个问题的。
![image](https://user-images.githubusercontent.com/82088551/187633910-4e66b7aa-a86e-4a4a-b126-72f095dbad34.png)

### 重现步骤
使用的第三方csv插件  导致场景sh设置页面不能展示参数化文件
### 期待的正确结果
正常的展示参数化文件
_No response_

**Comment by xulinde** [comment]
您的宝路csv插件是什么版本？我用的1.2.3

**Comment by zhangzhaox** [comment]
> 您的宝路csv插件是什么版本？我用的1.2.3
我切换到1.2.3版本试了  不可以  而且高级设置tbale页也看不到
![image](https://user-images.githubusercontent.com/82088551/188038681-ee750145-0863-4bb9-846f-eaec5430db9d.png)

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/188264745-d239680a-7791-454a-bcd3-e683b2ee0e01.png)
![image](https://user-images.githubusercontent.com/82088551/188264780-11662faf-71cf-4b68-acf5-4625b00e3db2.png)
TestBeanGUI  手动更改com.baolu.jmeter.config.BaoluCSVDataSet guiclass   就可以识别
@xulinde 麻烦再确认下，签名传的 jmx脚本 在你哪里不能重现？  
宝路CSV插件功能在一般压测场景虽然功能不影响，但分布式负载场景 不能分割附件
