### ISSUE TITLE
[BUG]接口管理-修改api请求头请求提 保存后，更新接口这个没提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17610]
### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

接口管理-修改api请求头请求提 保存后，更新接口这个没提示

### 重现步骤

接口管理-修改api请求头请求提 保存后，更新接口这个没提示

### 期待的正确结果

开启了更新提示，保存应该给出提示

### 附加信息

![1b978217e2c82bb2ebf2ab2f07c3c75](https://user-images.githubusercontent.com/43202800/187617762-2edb01a2-f0c7-4f9e-805f-b8d038ea434e.jpg)
![b29ef087c99cbd55546f7df460b4159](https://user-images.githubusercontent.com/43202800/187617782-4d195167-0a1a-4449-b3b5-606fa4469e4d.jpg)

**Comment by zyyfit** [comment]
修改接口时，需要接口有用例，或者被场景复制了，才会有提示
