### ISSUE TITLE
[BUG]接口测试首页用例链接访问不到用例

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#1761]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.0
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  首页点击过去7天测试计划失败用例TOP 10中或者运行中的定时任务中的用例链接
2. 访问不到，有异常信息Cannot read property 'tags' of undefined
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
<img width="653" alt="tag1" src="https://user-images.githubusercontent.com/72964047/112978304-bea58e00-9189-11eb-864f-2b5976756d53.png">
<img width="589" alt="tag2" src="https://user-images.githubusercontent.com/72964047/112978329-c6fdc900-9189-11eb-8132-1abae7e36d34.png">

**Comment by xulinde** [comment]
未复现该问题，请详细描述下必现步骤
