### ISSUE TITLE
[BUG]全局后置脚本(所有场景步骤后执行),场景执行后控制台不输出打印结果

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17611]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

1.全局后置脚本(所有场景步骤后执行),场景执行后控制台不输出打印结果，不方便调试
![image](https://user-images.githubusercontent.com/103627487/187616322-6d453d7e-198a-42f5-b356-961bb3680aba.png)
![image](https://user-images.githubusercontent.com/103627487/187616862-3ac6fad0-ea0c-4723-acac-de19848d088e.png)
2.场景点击执行，报告中会有打印结果
![image](https://user-images.githubusercontent.com/103627487/187617360-275d10d9-28ea-4576-868f-222cee47265e.png)

### 重现步骤

1.环境中添加全局后置脚本(所有场景步骤后执行)
2.创建场景调试，查看控制台结果

### 期待的正确结果

场景调试，控制台可以看到全局后置脚本(所有场景步骤后执行)打印结果

**Comment by xulinde** [comment]
“所有场景步骤后执行”的全局后置脚本，只有在执行整个场景（生成报告）的时候才会起作用。 单独执行某个步骤时不会起作用
