### ISSUE TITLE
[BUG]社区版测试计划关联UI测试用例提示“授权认证失败”

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17622]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

社区版测试计划关联UI测试用例提示“授权认证失败”

### 重现步骤

社区版测试计划关联UI测试用例“授权认证失败”，不应该显示“UI测试用例“或者提示信息不应该是“授权认证失败”

### 附加信息

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32027713/187649519-5e9f7ea5-d675-4a76-a633-55a05620eaa5.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，建议改成提示什么呢？

**Comment by dashenyucainiao** [comment]
社区版能否去掉？或者改成和一级菜单UI的提示一样？

**Comment by youliyuan-fit2cloud** [comment]
> 社区版能否去掉？或者改成和一级菜单UI的提示一样？

OK，我们按照UI模块的提示一样改。

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已优化，社区版本在测试计划中不再显示UI测试用例的tab页。
