### ISSUE TITLE
[BUG]ms接口导出swagger格式后，再导入postman失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17626]
### 联系方式

张树彬

### MeterSphere 版本

1.20.12

### 使用外置数据库

否

### 问题描述

ms接口导出swagger格式后，再导入postman失败

### 重现步骤

swagger2：swagger导入postman正常，swagger导入ms正常，ms导出swagger格式后导入postman错误；
swagger3：swagger导入postman正常，swagger导入ms正常，ms导出swagger格式后导入postman错误

### 期待的正确结果

ms接口导出swagger格式后，再导入postman成功

### 附加信息

![6302245627f226f66af99e697dfe9ca](https://user-images.githubusercontent.com/77324661/187675589-7274bbb9-5ae8-43ab-bea7-ce46e193fe0f.jpg)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.14版本已修复
