### ISSUE TITLE
[BUG]postman导入ms的接口参数说明不全

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17627]
### 联系方式

张树彬

### MeterSphere 版本

1.20.12

### 使用外置数据库

否

### 问题描述

postman导入ms的接口参数说明不全

### 重现步骤

1. 在postman的接口里添加多个接口参数说明
2. 导入postman文件，再导入ms接口定义
3. 查看接口定义里的接口文档，参数说明显示不全，与postman不一致

### 期待的正确结果

正确显示所有的接口参数说明

### 附加信息

![dfe25698151da0c22e49337706364c2](https://user-images.githubusercontent.com/77324661/187676632-3ddd0eab-f7e1-4262-a801-32e9bcfc3f7f.png)
![577bd6465671c05c5bdcfccc571f536](https://user-images.githubusercontent.com/77324661/187676660-949fbab1-f4a3-4541-b2fa-7538ee87c8ab.jpg)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.14版本已修复
