### ISSUE TITLE
[BUG] POST整数场景变量时JSON类型错误

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#17629]
### 联系方式

QQ 61857543

### MeterSphere 版本

v1.20.12

### 使用外置数据库

是

### 问题描述

POST data:
{
  "test": [
    "1"       <---------- 应该是整数类型，但POST成了字符串类型
  ]
}

### 重现步骤

[Metersphere_Scenario_默认项目.7z.zip](https://github.com/metersphere/metersphere/files/9466111/Metersphere_Scenario_.7z.zip)

### 期待的正确结果

POST data:
{
  "test": [
    1
  ]
}

**Comment by genezx** [comment]
![image](https://user-images.githubusercontent.com/31116612/187813353-e8488453-2774-4c09-a594-8be384dd74d3.png)
![image](https://user-images.githubusercontent.com/31116612/187813334-69161d6a-95d6-4f64-a105-478958dd5dfa.png)

**Comment by zyyfit** [comment]
重复问题
https://github.com/metersphere/metersphere/issues/15760
https://github.com/metersphere/metersphere/issues/16319
