### ISSUE TITLE
[FEATURE]针测试计划，建议增加人员统计报表，比如谁执行了多少案例，谁写了多少案例

### ISSUE THREAD

**Issue by cds322** [metersphere/metersphere#17628]
### MeterSphere 版本

V2.1.0

### 请描述您的需求或者改进建议

针测试计划，建议增加人员统计报表，比如谁执行了多少案例，谁写了多少案例

### 请描述你建议的实现方案

1

### 附加信息

1

**Comment by Hyyfit** [comment]
我们后续调研一下，后面会完善报表的功能
