### ISSUE TITLE
[BUG]接口自动化引用场景之后，被引用的场景内的自定义请求拖出来之后均无法删除、关闭、拖回原场景

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17621]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.12-LTS

### 使用外置数据库

否

### 问题描述

1、接口自动化引用场景之后，被引用的场景内的自定义请求拖出来
2、被拖出来的自定义请求无法删除、关闭、拖回原场景

### 重现步骤

1、接口自动化引用其他场景（包含自定义请求)，
2、被引用的场景内的自定义请求拖出来，
3、对拖出原场景的自定义请求进行删除、打开、关闭、拖回原场景
4、发现上述操作均无法进行

### 期待的正确结果

至少可以进行删除、拖回被引用的场景

### 附加信息

截图：
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/32027713/187640844-322b8ae2-6c8b-488e-b80e-87abfd5b51c2.png">

**Comment by zyyfit** [comment]
历史遗留问题，暂不处理
