### ISSUE TITLE
[BUG] 导入全部功能用例，一直转圈，导出不了文件，需手动停止

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17635]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v2.1-e7992983

### 使用外置数据库

否

### 问题描述

导入全部功能用例，一直转圈，需手动停止（接口已报500，控制台有报错）
![image](https://user-images.githubusercontent.com/103925124/187892311-57fd48a4-48e7-4ec9-a886-9de8e0a121eb.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/187892570-45fc0114-20ab-4d54-a25b-d1fc8ba241ae.png)

### 附加信息

使用的qa环境

**Comment by xulinde** [comment]
502是qa环境在自动部署

**Comment by Ycr123888** [comment]
![image](https://user-images.githubusercontent.com/103925124/188350856-cbf898f9-3f21-4151-8907-db929c2dd9b1.png)
![image](https://user-images.githubusercontent.com/103925124/188350866-96648e17-b723-4acb-bc8f-db784b3688b2.png)
![image](https://user-images.githubusercontent.com/103925124/188350889-ca26397c-4624-4680-a9f8-f410b1c386ab.png)
服务正常后，执行是500

**Comment by xulinde** [comment]
/test/case/export/testcase是导出功能用例的接口，导出报错是已知问题，重复https://github.com/metersphere/metersphere/issues/17630
