### ISSUE TITLE
[BUG]添加脑图，保存后，刷新，脑图消失

### ISSUE THREAD

**Issue by galasa12** [metersphere/metersphere#1763]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zhengbangbo** [comment]
> 请问您保存的是什么内容呢？保存模块目前不支持脑图添加，保存用例的话需要添加用例标签

目前尝试使用脑图模式添加用例，
但是保存-修改(还在脑图模式中)-再保存，查看列表模式时有了两条用例。
也就是说再次保存时重新创建了新的用例。 @zyyfit

**Comment by zyyfit** [comment]
> > 请问您保存的是什么内容呢？保存模块目前不支持脑图添加，保存用例的话需要添加用例标签
> 
> 我在脑图内手动写的用例，洗碗后点右上角的保存，然后刷新后，内容全部丢失了

您好，目前已经发布了1.9.2版本，请升级到最新版试试

**Comment by zyyfit** [comment]
> @zyyfit
> 
> MeterSphere 版本
> v1.8.2-d59d4b5f
> 
> Bug 描述
> 脑图模式中编辑用例，点击保存，生成了新用例
> 
> Bug 重现步骤
> 
>     1. 进入脑图模式
> 
>     2. 添加一个用例
> 
>     3. 点击保存
> 
>     4. 编辑该用例
> 
>     5. 点击保存
> 
> 
> 期待的正确结果
> 编辑用例而不是新建一条用例
> 
> 截图
> ![Snipaste_2021-04-27_15-41-26.png](https://camo.githubusercontent.com/a7baf4f2103b6757817b82b134fb10bba7153afd76b145aee825f9e5040539f1/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30342f32372f39587170364f41616a5046374e4b772e706e67)

您好，目前已经发布了1.9.2版本，请升级到最新版试试
