### ISSUE TITLE
[BUG]UI自动化里面的步骤其他设置默认值设定为“出现异常截图”，但是实际出现异常没有截图

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17632]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

UI自动化里面的步骤其他设置默认值设定为“出现异常截图”，但是实际出现异常没有截图

### 重现步骤

1、调试原有的UI自动化场景
2、里面的步骤  其他设置  默认值设定为“出现异常截图”，但是实际出现异常没有截图

### 附加信息

原步骤设置：
<img width="949" alt="image" src="https://user-images.githubusercontent.com/32027713/187821596-9d097ca1-2788-45f8-a524-281b0d2b7cde.png">

调试结束后报告无截图信息：
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/32027713/187821489-e498f221-edae-444e-bf3e-89ca1c533832.png">

**Comment by zrfit** [comment]
v2.1.1已修复。
