### ISSUE TITLE
[FEATURE]  用户安装或升级后，有初始学习案例，增加用户易上手程度

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17631]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

用户安装或升级后，有初始学习案例，比如场景，有csv使用，循环控制器，条件控制器，token提取为环境变量后调用等例子

得到收益：用户在初次安装后，可复制例子然后简单换成自己项目的接口，执行调试，增加测试新手/对jmeter不太熟悉的用户的初始好感度依赖度。
同样升级的新功能，也有初始例子，减少用户初次尝试时，也需要找简易网站，小试牛刀的时间；比如：UI测试拖拽/UI测试绘图

**Comment by Hyyfit** [comment]
后面可以优化用户手册，和指导的短视频，这个不属于功能上的需求哈。

**Comment by Ycr123888** [comment]
好的
