### ISSUE TITLE
V2.1版本集成Jira后缺陷同步问题

### ISSUE THREAD

**Issue by huhu20180116** [metersphere/metersphere#17633]
### 联系方式

MeterSphere交流群49   昵称：虎虎

### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

1、复制文字到“描述框”，非手工填写，提交缺陷会提示“描述不能为空”。

2、填写缺陷相关信息：需求提出人、报告人、需求的业务场景、经办人等信息并提交保存，在缺陷列表编辑该缺陷，发现需求提出人、报告人、需求的业务场景等信息丢失，经办人信息变成了JIRAUSER****。

### 重现步骤

1、在项目管理集成jira。
2、创建缺陷。
3、编辑缺陷。

**Comment by xulinde** [comment]
问题1和2在v2.1.0版本都未复现，您那边如果是必现，请详细描述下jira版本，操作步骤等，或者直接发个操作视频，方便我们排查问题～
