### ISSUE TITLE
[BUG]xmind文件导入到脑图，部分节点的内容消失，且顺序颠倒

### ISSUE THREAD

**Issue by galasa12** [metersphere/metersphere#1764]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是使用的模板文件格式吗？没有复现您这个问题呢

**Comment by zyyfit** [comment]
> > 您好，请问是使用的模板文件格式吗？没有复现您这个问题呢
> 
> 方便提供联系方式吗？我可以提供录制的视频

可以加入我们的交流群
![image](https://user-images.githubusercontent.com/73461316/113140174-a0f42980-925a-11eb-96dd-561042080d0f.png)
