### ISSUE TITLE
[BUG]UI自动化，v2.1.0，存量UI自动化场景里如果复制导入了已有场景，场景以及子场景调试模式和测试计划里不会被执行 。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17649]
### 联系方式

王进

### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

UI自动化，v2.1.0，存量UI自动化场景里如果复制导入了已有场景，场景以及子场景调试模式和测试计划里不会被执行 。

### 重现步骤

1. UI自动化，v2.1.0，存量UI自动化场景里如果复制导入了已有场景，场景以及子场景调试模式和测试计划里不会被执行 。
2. v2.1.0 之前的版本是好的，用户通过场景导入的方式组装了一些场景，然后关联在测试计划里，每天回归执行，都是好的。
3. 升级到v2.1.0后，出现场景以及子场景调试模式和测试计划里不会被执行的问题。
![1662108545848](https://user-images.githubusercontent.com/76033005/188102035-192d6b03-0d54-4eb6-a043-597e35c850ae.png)

### 附加信息

如果需要看现象，可以线下联系我。客户环境可以访问。

**Comment by zhangdahai112** [comment]
已经有跟进在做一个重试的功能了，这属于 grid 没有正确拉起浏览器跑测试，导致报告为空

**Comment by 35plus** [comment]
两个问题，不相关，刚刚已经跟大海说明了。

**Comment by zrfit** [comment]
问题1:xpath含有双引号问题v2.1.1已解决。
问题2:grid造成未执行问题后续版本修复。

**Comment by zrfit** [comment]
v2.2.0版本增加了失败重试功能。
