### ISSUE TITLE
[BUG]v1.20源码bug

### ISSUE THREAD

**Issue by WYM201** [metersphere/metersphere#17643]
### 联系方式

微信号：18817464652

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

下载v1.20源码后，build出错
![image](https://user-images.githubusercontent.com/62410391/188039533-c81e51cb-5545-46e1-9cc8-1dc51a0b9e00.png)
我理解这里是不是写错了？jmeter的包里不该有ms有关的类

### 重现步骤

github上下源码后build

### 附加信息

![image](https://user-images.githubusercontent.com/62410391/188039581-f43ba971-8389-4cbf-bcc2-9c921d969d03.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，这个是MS core 代码，要先本地编译通过。
