### ISSUE TITLE
[FEATURE]接口测试报告，格式优化建议

### ISSUE THREAD

**Issue by Thisisasnail** [metersphere/metersphere#17645]
### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 请描述您的需求或者改进建议

![fc83a14f331dff279d73f6db784e310](https://user-images.githubusercontent.com/63831219/188040970-2272d7f9-03f9-4715-8259-a5d112b723e3.jpg)
没有响应码、响应时间、执行状态的描述，别人第一次看报告，都不清楚下面说的什么意思，尤其是响应时间。

### 请描述你建议的实现方案

建议接口测试报告中，此处位置插入下面响应码、响应时间、执行状态等相关描述。

**Comment by Hyyfit** [comment]
设计如此。
如果响应时间后面加上单位，“200ms”，与状态码有个区分，这样可以满足您的需求吗？

**Comment by Thisisasnail** [comment]
![1f2d5bde8d5978d9cee55ce0fd62a9b](https://user-images.githubusercontent.com/63831219/188597003-c290c207-f3e6-40a5-a156-afbf52760202.png)
可以，最少也得加个单位。。。
