### ISSUE TITLE
[BUG]UI测试，通过率计算错误

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#17648]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.12-lts

### 使用外置数据库

否

### 问题描述

带有子步骤的场景，通过率计算错误

### 重现步骤

1、创建UI测试，多增加一个子步骤的场景
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/72729206/188088249-94b98c08-4beb-4aa6-8f20-a66285c3ed90.png">
2、然后通过率是67%，第一个是个子步骤，虽然有步骤成功，但是步骤是失败的，通过率应该是0才对
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/72729206/188088487-888a4aa3-163d-4d97-b556-f39635a75627.png">

### 期待的正确结果

第一个是个子步骤，虽然有步骤成功，但是步骤是失败的，通过率应该是0才对

**Comment by zrfit** [comment]
v1.20.14-lts已修复，场景执行成功步骤为0，通过率为0%。
