### ISSUE TITLE
[FEATIURE]断言有问题

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#17644]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.6

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/issues/14086#issue-1250695469

后续回复里面的问题

### 重现步骤

如果响应内容为：
```
{
    "list": [
        {
            "id": 2,
            "name": "the First Element",
        },
        {
            "id": 11,
            "name": "the Second Element",
        }
    ]
}
```
在断言关系中 ，设置JSON断言如下：
$.list[*].id         不包括              1
断言结果是错误
但是实际上  [2,11] 不包括 1 应该是正确。

### 附加信息

如果问题解决了应该先测试通过一下，再关闭。

**Comment by zyyfit** [comment]
这个是把断言的值当作字符串判断了，我们先看看能不能支持数字吧

**Comment by zyyfit** [comment]
目前判断包含不包含都是当字符串处理的，暂时不支持数字判断，您可以在选包含不包含的那里选正则表达式
![image](https://user-images.githubusercontent.com/73461316/188566002-c0296d23-1fab-4823-be8e-680dda20cdcf.png)

**Comment by Faerie1999** [comment]
如果是测试的断言关系是包含，估计正则匹配也无法实现吧，这应该算是一个bug而不是新功能。为什么归类到暂不支持标签？

**Comment by Faerie1999** [comment]
> 目前判断包含不包含都是当字符串处理的，暂时不支持数字判断，您可以在选包含不包含的那里选正则表达式 ![image](https://user-images.githubusercontent.com/73461316/188566002-c0296d23-1fab-4823-be8e-680dda20cdcf.png)

好像^((?!1333).)*$ 这样的超过个位数的数字就会匹配上，看看正则表达式的解析是不是有问题？
