### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by iamhaoren** [metersphere/metersphere#17652]
### 请描述您的问题

Case 前置操作：
0、获取请求body
1、加密body
2、sampler.addArgument("",body)，放入新body
发送请求时，meterSphere 会将body进行 URLEncode，导致服务端解密失败。

**Comment by Hyyfit** [comment]
您好，我们正常是不会出现这个问题的，只有在这里配置了“是”才会Encode
如果确认会这个会复现，可以提bug
![image](https://user-images.githubusercontent.com/95834771/188581352-f3ac4f97-1747-4f4a-958e-97b4f57bb2fe.png)

**Comment by iamhaoren** [comment]
> 您好，我们正常是不会出现这个问题的，只有在这里配置了“是”才会Encode 如果确认会这个会复现，可以提bug ![image](https://user-images.githubusercontent.com/95834771/188581352-f3ac4f97-1747-4f4a-958e-97b4f57bb2fe.png)

你这是【QUERY参数】里的配置吧，【请求体】Tab没有这个配置入口呢

**Comment by Hyyfit** [comment]
截图看一下

**Comment by iamhaoren** [comment]
> 

![1](https://user-images.githubusercontent.com/34563392/189018938-40622a8a-7480-4278-8faa-dc9c22997b62.png)

**Comment by iamhaoren** [comment]
> 

![1](https://user-images.githubusercontent.com/34563392/189019012-782b17b5-2f0a-469e-a9fc-4c59800a3888.png)

**Comment by Hyyfit** [comment]
你加一下我微信
<img width="299" alt="image" src="https://user-images.githubusercontent.com/95834771/190568342-ebe91e57-7333-4418-8795-137e081fad73.png">
