### ISSUE TITLE
[BUG]功能用例自定义字段已经输入值并保存，在任务计划中关联用例后自定义字段值消失

### ISSUE THREAD

**Issue by zhangshihao930112** [metersphere/metersphere#17657]
### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

功能用例自定义字段已经输入值并保存，在任务计划中关联用例后自定义字段值消失

### 重现步骤

功能用例自定义字段已经输入值并保存，在任务计划中关联用例后自定义字段值消失

### 期待的正确结果

功能用例自定义字段已经输入值并保存，在任务计划中关联用例后自定义字段值不消失

### 附加信息

![微信截图_20220903085742](https://user-images.githubusercontent.com/85295604/188250220-192c62b0-9f90-483f-8c5c-76e46ccdce1b.png)
![微信截图_20220903091810](https://user-images.githubusercontent.com/85295604/188250321-56dc6bf3-639f-4f08-b32f-e85bc2365fa6.png)

**Comment by xulinde** [comment]
v2.1.1已修复～
