### ISSUE TITLE
接口定义定时同步swagger文档，希望增加标签或者开发项目名称字段，便于区分

### ISSUE THREAD

**Issue by dengcaifeng** [metersphere/metersphere#17653]
### MeterSphere 版本

v2.10

### 请描述您的需求或者改进建议

因为我们在MS里定义的一个项目里可能会涉及到多个服务的接口，定时同步swagger设置无法打标签或者填写服务名称，导致无法区分，希望增加”标签“或者”服务名称“字段

### 请描述你建议的实现方案

在表单上增加标签或者服务名称；
<img width="934" alt="截屏2022-09-02 下午5 24 40" src="https://user-images.githubusercontent.com/64075867/188108769-c3b6f488-2012-4500-99b1-27efd39492de.png">

**Comment by Hyyfit** [comment]
我们需要调研一下具体的实现

**Comment by dengcaifeng** [comment]
麻烦尽快给出排期

**Comment by luty2018** [comment]
在导入这里加标签是要加到对应的模块里，还是对应的接口上，如果是接口上，那我们2.2有规划api自定义模板，可以添加自定义字段来标识所属应用，请明确需求即时反馈。

**Comment by dengcaifeng** [comment]
增加一个字段，可以说明是哪个服务
<img width="1152" alt="截屏2022-09-06 下午2 28 33" src="https://user-images.githubusercontent.com/64075867/188562337-4e2b20df-f94d-4340-839f-f2821d73ca44.png">

**Comment by luty2018** [comment]
模块命名为服务名可以实现吧
