### ISSUE TITLE
接口定义文档需要使用URL来搜索

### ISSUE THREAD

**Issue by dengcaifeng** [metersphere/metersphere#17655]
### MeterSphere 版本

v2.10

### 请描述您的需求或者改进建议

目前接口定义文档只支持名称搜索，经常研发进行修改时，通过名称搜索非常不便捷，他们习惯用URL进行搜索，希望增加URL搜索的方式

### 请描述你建议的实现方案

希望增加URL的搜索方式，搜索对应的文档：
<img width="951" alt="截屏2022-09-02 下午5 39 22" src="https://user-images.githubusercontent.com/64075867/188111659-3621c36c-0db9-49bd-9b31-7f62b20cdb53.png">

**Comment by Hyyfit** [comment]
在列表页的搜索框，是支持路径搜索的。
