### ISSUE TITLE
[BUG]接口自动化，后置操作自动提取参数时，相应结果为JSON格式，报错信息显示：响应结果不是JSON格式

### ISSUE THREAD

**Issue by yangfan112** [metersphere/metersphere#17661]
### 联系方式

1441463302@qq.com

### MeterSphere 版本

v1.20.12-lts-2297374a

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/48746721/188353529-e80f554f-0f2d-4f16-97bd-ee1c42409e02.png)
[6cc5e11e-7625-4d21-9661-cee639673f91.txt](https://github.com/metersphere/metersphere/files/9486459/6cc5e11e-7625-4d21-9661-cee639673f91.txt)

### 重现步骤

接口测试-接口自动化-执行场景

**Comment by youliyuan-fit2cloud** [comment]
你好，目前v1.20.13-lts版本没有复现该问题，建议升级一下。

**Comment by zhangzhaox** [comment]
@youliyuan-fit2cloud  v1.20.13-lts 版本也会出现这个问题哦 麻烦使用这个json报文测试验证下，谢谢
![image](https://user-images.githubusercontent.com/82088551/188614535-420307a9-992c-4008-bd10-583dd0c15447.png)
