### ISSUE TITLE
[BUG]场景变量CSV某一列字段中有多行数据,实际发起请求只读取多行中的第一行

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17665]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.13-LTS

### 使用外置数据库

否

### 问题描述

场景变量CSV某一列字段中有多行数据,实际发起请求只读取多行中的第一行

### 重现步骤

1、场景变量中添加一个CSV类型的变量，这个CSV中某一列的字段中有多行数据

2、在循环控制器下使用这个场景变量，发现这个字段中的内容只被读取了第一行

### 期待的正确结果

可以读取这个字段的全部行数

### 附加信息

变量预览：
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/32027713/188368543-97e22de8-c4cc-4d71-91ba-2c7cb971d68c.png">

实际发送内容：

<img width="904" alt="image" src="https://user-images.githubusercontent.com/32027713/188368194-01030694-00e9-43a1-9dd5-920a8cd833cd.png">

文件内容
[test.csv](https://github.com/metersphere/metersphere/files/9486966/test.csv)

**Comment by zyyfit** [comment]
这个csv文件里是用 , 分割的，这样识别出来就是一行数据，你想让他是多行数据的话就需要正确的写在多行里，不能这样写
用其他分隔符也是，要正确的写成多条数据

**Comment by zyyfit** [comment]
设置是否可以带引号解决的
