### ISSUE TITLE
[BUG]接口自动化-回收站字段筛选不起作用

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17662]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

否

### 问题描述

接口自动化-回收站字段筛选不起作用
![image](https://user-images.githubusercontent.com/103627487/188356427-6b6da238-062b-4aa5-ae1e-7076ced52ea0.png)
![image](https://user-images.githubusercontent.com/103627487/188356577-7fa078c8-df0e-457c-95fe-aa9a479488c6.png)

### 重现步骤

接口自动化，进入回收站，通过列表头字段进行筛选
![image](https://user-images.githubusercontent.com/103627487/188356440-47938159-d9d4-4ebb-99f6-d9043654a5b1.png)
备注：接口自动化回收站所有通过表头字段筛选的均不起作用

### 期待的正确结果

能正常通过字段筛选出结果

**Comment by youliyuan-fit2cloud** [comment]
v2.1.1版本中已修复该问题。
