### ISSUE TITLE
[BUG]测试跟踪-用例管理：选择所有用例数据导出页面转圈

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17677]
### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

测试跟踪-用例管理：选择所有用例数据导出页面转圈

### 重现步骤

测试跟踪-用例管理：选择所有用例数据导出页面转圈

### 期待的正确结果

正确导出用例结果

### 附加信息

![微信图片_20220905164915](https://user-images.githubusercontent.com/43202800/188409231-bb4f1b2b-48d9-4474-8dcf-d91ffda14ebf.png)
![0767327dc4a953a778f3e454279fb6a7_](https://user-images.githubusercontent.com/43202800/188409272-b3101141-75ee-4024-8856-af18efaf205e.png)

**Comment by xulinde** [comment]
已知问题，重复，https://github.com/metersphere/metersphere/issues/17630
