### ISSUE TITLE
[BUG]在【文件管理】上传第三方加解密包，在接口-前置脚本中调用，出现调用失败，找不到类的情况。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17673]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

在【文件管理】上传第三方加解密包，在接口-前置脚本中调用，出现调用失败，找不到类的情况。
![image](https://user-images.githubusercontent.com/104960608/188391421-bd49d526-63b4-42af-b8fa-498829c4ee08.png)

![image](https://user-images.githubusercontent.com/104960608/188391310-ea3be784-99a1-4e18-a519-340d82685716.png)

jar包里为加解密方法
![image](https://user-images.githubusercontent.com/104960608/188392455-608e0882-d476-417d-af54-4a5b88f9bb7a.png)

### 重现步骤

1.【文件管理】页面，上传第三方jar包
2.在接口定义-快捷调试-前置脚本，调用这个jar包里的方法
3.在控制台出现找不到类的情况

**Comment by zyyfit** [comment]
1、请上传一下这个jar包，
2、请试一下在jmeter里是否能够正常执行，如果jmeter里执行也报错的话，那目前就是不支持的，如果jmeter里执行正常，我们再看看是哪里的问题

**Comment by 2lipan** [comment]
这在cloud环境(1.20.12版本)上可以运行
![image](https://user-images.githubusercontent.com/104960608/188430846-0340cf5c-1b74-48ed-a04b-a4cc183640e4.png)

**Comment by 2lipan** [comment]
![image](https://user-images.githubusercontent.com/104960608/188431151-85e9a9d4-187f-43f0-b7ee-d7e2081510fe.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
已确认是没开启加载jar包按钮导致的
