### ISSUE TITLE
[BUG]功能用例自定义字段为文本和复文本时，导入失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17672]
### 联系方式

张树彬

### MeterSphere 版本

2.1

### 使用外置数据库

否

### 问题描述

功能用例自定义字段为文本和复文本时，导入失败

### 重现步骤

1. 配置用例模板，增加自定义字段值类型为文本或者富文本格式
2. 下载Excel用例模板
3. 在本地按着下载的模板编写用例后导入MS
4. 查看导入用例格式为文本或富文本字段内容为空

### 期待的正确结果

导入用例字段格式为文本和富文本时，正确显示字段内容

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/188391696-1bf6c0c7-a3a7-4df1-b4ea-226063407361.png)

**Comment by xulinde** [comment]
v2.1.1已修复～
