### ISSUE TITLE
[FEATURE] 把诸多模块的场景集中在一个场景中，便于执行，但是集中后没有层级划分，没有层次感

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#17670]
### MeterSphere 版本

v2.0.0-b4

### 请描述您的需求或者改进建议

把诸多模块的场景集中在一个场景中，便于执行，但是集中后没有层级划分，没有层次感
![Uploading 8a98e55218e6dfb81f5023b7963819e.jpg…]()

### 请描述你建议的实现方案

期望场景中可以显示
![dd5d1bfcdae066718f1e4a4739531e2](https://user-images.githubusercontent.com/75885014/188388952-75bf1164-bebc-4195-9f7c-ba297c4a6d21.png)

**Comment by Hyyfit** [comment]
我们场景是支持多层嵌套了，可以通过创建多层的场景来体现层级关系。
