### ISSUE TITLE
[BUG]接口自动化中自定义请求域名用变量的情况下，认证配置不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17678]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.13-LTS

### 使用外置数据库

否

### 问题描述

接口自动化中自定义请求域名用变量的情况下，认证配置不生效

### 重现步骤

1、新增自动化场景，并在场景内添加认证配置；
2、环境配置中的通用配置新增对应的域名或者访问IP变量；
3、使用变量作为请求域名或者IP,并在自定义请求中添加认证配置，采用Basic Auth,发起请求；
4、直接在自定义请求中填写请求域名或者IP，并在自定义请求中添加认证配置，采用Basic Auth，发起请求；
5、观察并比对3、4两步的请求内容；

### 附加信息

自定义请求写死请求域名或者IP：
<img width="806" alt="image" src="https://user-images.githubusercontent.com/32027713/188413865-0a93503c-eb73-405d-852c-14c4197f7037.png">

自定义请求域名或者IP用变量替代：
<img width="885" alt="image" src="https://user-images.githubusercontent.com/32027713/188414165-2b4c91df-bf24-485e-aa57-5ab801cd2ffa.png">

**Comment by zyyfit** [comment]
没有复现
![image](https://user-images.githubusercontent.com/73461316/188529848-2b12c83b-dc97-48a5-9ec1-61fec5bfd5ea.png)

**Comment by zyyfit** [comment]
1.20.14版本已修复
