### ISSUE TITLE
[BUG]开源版本，点击”同步缺陷“按钮后，已同步到JIRA的缺陷，在MS上再次编辑时，已填写的字段内容被自动清空

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17684]
### 联系方式

张树彬

### MeterSphere 版本

2.1、1.20.12LTS

### 使用外置数据库

否

### 问题描述

开源版本，点击”同步缺陷“按钮后，已同步到JIRA的缺陷，在MS上再次编辑时，已填写的字段内容被自动清空

### 重现步骤

1. 开源版本（1.20.12LT版本和2.1版本都复现）
2. 配置JIRA信息，与JIRA集成成功
3. 在MS上创建缺陷后可自动成功同步到JIRA，同步后点击MS上的缺陷编辑按钮，字段内容都还在
4. 点击MS缺陷列表的”同步缺陷“按钮
5. 再次点击编辑已同步到JIRA的缺陷，已填写的字段内容被清空（有的全部清空，有的部分清空）

### 期待的正确结果

缺陷的字段内容正常显示

### 附加信息

![1662380156409](https://user-images.githubusercontent.com/77324661/188448346-4a9fb3e4-94f4-4da7-bc57-b19e4ae49b0f.jpg)
![1662380436024](https://user-images.githubusercontent.com/77324661/188448405-ad24a017-77a1-4c3d-b174-eb14fd65171a.jpg)
![1662380368313](https://user-images.githubusercontent.com/77324661/188448478-b0b51227-8c36-450b-86c3-3a1311023b88.jpg)
![1662380811877](https://user-images.githubusercontent.com/77324661/188449260-85c457d0-ef00-481a-a0c3-162997a640ec.jpg)

**Comment by xulinde** [comment]
使用2.1、1.20.12LTS均未复现该问题，jira模版有添加自定义字段吗？

**Comment by binbin0406** [comment]
> 使用2.1、1.20.12LTS均未复现该问题，jira模版有添加自定义字段吗？

有自定义字段，可以联系我，把我的JIRA环境给你验证

**Comment by xulinde** [comment]
v2.2.0已修复～
