### ISSUE TITLE
ms-server一直处于Restarting状态

### ISSUE THREAD

**Issue by kooli1** [metersphere/metersphere#17680]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/112049278/188417258-c12c738b-ddf9-4425-b2b8-ed0c61ca6750.png)

**Comment by kooli1** [comment]
[错误日志.txt](https://github.com/metersphere/metersphere/files/9488657/default.txt)

**Comment by AgAngle** [comment]
你好，看日志是docker挂载的本地目录有点问题，没找到 /opt/metersphere/conf/metersphere.properties 配置文件，具体原因还麻烦进一步排查一下，可能是selinux，或者目录权限之类的问题
