### ISSUE TITLE
[BUG]导入swagger之后，每个接口会自动生成case

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17691]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.13-LTS

### 使用外置数据库

否

### 问题描述

导入swagger之后，每个接口会自动生成case

### 重现步骤

1、导入metersphere的swagger

2、查看每个接口，会自动生成一个case

**Comment by zyyfit** [comment]
1.20.14版本已修复
