### ISSUE TITLE
[BUG]执行场景时个别case出现error，修改后执行成功，但测试报告中依然显示失败

### ISSUE THREAD

**Issue by antiy-zcl** [metersphere/metersphere#17695]
### 联系方式

862822315@qq.com

### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

执行场景时个别case出现error，修改后执行成功，但测试报告中依然显示失败

### 重现步骤

执行场景时个别case出现error
修改后执行成功
测试报告中此case依然显示失败
无论删除测试报告，删除场景重新创建，依然测试报告中依然显示失败
什么原因

**Comment by zyyfit** [comment]
方便把场景和执行环境上传一下吗

**Comment by zyyfit** [comment]
另外，可以看一下这个失败的case是不是有前后置脚本，脚本失败了，case也会失败的
