### ISSUE TITLE
[FEATURE] 断言处可否支持数值断言，断言的逻辑符号可否增加大于等于，小于等于

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#17698]
### MeterSphere 版本

v2.0.0-b4

### 请描述您的需求或者改进建议

1、断言处建议增加数值断言
2、断言的逻辑符号增加“大于等于”，“小于等于”

在实践中，一般地，后端开发不会控制接口返回数值的精度，且当小数点最后一位是0时，即使控制了精度，接口返回也默认去掉0，因断言仅支持字符串格式的断言，导致在判断一些盈亏或者比率时经常误报，防不胜防。因后端数据量太多，让后端开发控制接口返回每一个数据的精度工作量较大，若增加以上两种判断方式，则会减少很多误报。
![image](https://user-images.githubusercontent.com/75885014/188536763-2c003779-f040-4a6f-8fdc-a03eff1ca61b.png)

### 请描述你建议的实现方案

1、断言处建议增加数值断言
2、断言的逻辑符号增加“大于等于”，“小于等于”

**Comment by Hyyfit** [comment]
好的，可以优化一下断言。
