### ISSUE TITLE
[BUG]当频繁创建接口case、多人同时创建cese时，提示信息有误

### ISSUE THREAD

**Issue by antiy-zcl** [metersphere/metersphere#17696]
### 联系方式

862822315@qq.com

### MeterSphere 版本

 v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

当频繁创建接口case、多人同时创建cese时，提示信息有误

### 重现步骤

账号a创建场景1
同时账号b创建场景2
都成功保存后，提示显示a创建场景2成功

**Comment by zyyfit** [comment]
请问这个提示是指的右上角那个站内消息通知吗？
