### ISSUE TITLE
[FEATURE]导入swagger格式接口失败，提示信息不明确

### ISSUE THREAD

**Issue by antiy-zcl** [metersphere/metersphere#17697]
### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 请描述您的需求或者改进建议

字段验证信息不公开，导致openapi303版本的接口导入经常失败，提示信息不明确，不知道哪里出问题

**Comment by luty2018** [comment]
是通过文件还是URL方式导入？如果是文件导入可以将文件私发给我们进行测试，如果是URL导入确认是否含有中文？如含有中文请转码后再导入。
