### ISSUE TITLE
[FEATURE]增加sign加密，内置函数功能，操作数据库功能

### ISSUE THREAD

**Issue by 9dre4m** [metersphere/metersphere#177]
**请描述您的需求或者改进建议.**

1.请求验签，希望增加加密功能
2.增加内置函数   随机生成设定位数的字符串、数字   
当前日期函数   生成手机号

get请求  post请求  参数化用到

3.希望增加操作数据库的功能，参数化 断言  用途
**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.2.0 版本中支持，欢迎更新使用
