### ISSUE TITLE
[BUG]【系统设置-用户-导入用户】，下载模板填写完成后，进行导入，导入不成功，页面会报错

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17704]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

【系统设置-用户-导入用户】，下载模板填写完成后，进行导入，导入不成功，页面会报错，报错信息如下。
![image](https://user-images.githubusercontent.com/104960608/188554995-ad36d1c1-4492-4432-be25-9620991c3512.png)

### 重现步骤

1.【系统设置-用户】页面，点击【导入用户】，下载模板
2.填写模板，将上面所有"否"改成"是"，填写相应内容进行保存
3.上传模板，会看到页面错误信息。
****导入的用户模板****
[用户导入模板.xlsx](https://github.com/metersphere/metersphere/files/9493580/default.xlsx)

**Comment by youliyuan-fit2cloud** [comment]
你好，步骤2.填写模板，将上面所有"否"改成"是"，填写相应内容进行保存，改成“是” 之后得加上是哪个工作空间和项目，否则不要改成“是”。

**Comment by 2lipan** [comment]
上面有我导入的用户模板，希望能上传看看。至于哪个工作空间和项目我已填写了。如哪儿填写的不对或者漏填，为啥没有任何提示信息，弄的我都不知道哪儿不对。
![image](https://user-images.githubusercontent.com/104960608/188558656-e9babd5f-6b92-4bb3-98d2-ae3e5ae9f2f0.png)

**Comment by youliyuan-fit2cloud** [comment]
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/54612864/188560876-199a98c3-b616-40e6-aa00-9048eda2cf9a.png">

这里改成否，如果填 是，需要写项目名称，而且不能和前面的项目重复，就是用户不能同时是一个项目的项目管理员又是项目成员又是只读用户。

**Comment by 2lipan** [comment]
这两项已经改成“否”了，但是页面还是提示一样的错误。
[用户导入模板.xlsx](https://github.com/metersphere/metersphere/files/9494035/default.xlsx)
