### ISSUE TITLE
[FEATURE]SQL请求，按列存储，最好能自动生成返回结果行数，变量名_all（列所有值），变量名_rows（查询结果行数）

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17705]
### MeterSphere 版本

 v2.1.0-2de48bb8

### 请描述您的需求或者改进建议

SQL请求，按列存储，最好能自动生成返回结果行数，变量名_all（列所有值），变量名_rows（查询结果行数）

### 请描述你建议的实现方案

SQL请求，按列存储，最好能自动生成返回结果行数，变量名_all（列所有值），变量名_rows（查询结果行数）

**Comment by luty2018** [comment]
请根据东区排期规划更新到wiki上
