### ISSUE TITLE
[BUG]测试计划执行在选择一次环境后，在修改关联的case的环境无效

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#17710]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.12-lts

### 使用外置数据库

否

### 问题描述

1、首次创建测试计划，里面的case分别选择不同的环境，在执行测试计划的时候不选择环境，执行正常
2、在执行测试计划选择环境后，在编辑测试计划里面case的环境，然后在执行测试计划，不选择环境，执行结果还是以上一次的环境执行的
3、找不到地方来清除这个环境，只能重新建一个测试计划

### 重现步骤

1、创建一个测试计划，关联case时选择不同的环境
<img width="1465" alt="1" src="https://user-images.githubusercontent.com/72729206/188574766-dce5b819-f56b-458c-9e93-75fff05061f7.png">
2、执行测试计划，不选择环境，正常应该走内部管理case的环境
<img width="580" alt="2" src="https://user-images.githubusercontent.com/72729206/188575640-d642539a-6fd9-477b-8852-5659ea02123a.png">
3、测试结果正常
<img width="920" alt="3" src="https://user-images.githubusercontent.com/72729206/188575701-21362993-0852-4110-bb6d-148cc86f6e18.png">
4、再次执行测试计划，选择一个统一的环境
<img width="589" alt="image" src="https://user-images.githubusercontent.com/72729206/188575824-7794ea46-7cc7-4995-9b9f-33a7440dcad9.png">
5、测试结果正常
<img width="709" alt="image" src="https://user-images.githubusercontent.com/72729206/188576006-93f25359-c4d5-4a93-bc70-aa96b22aba4a.png">
6、重新编辑该测试计划，取消关联case，重新关联不同环境的case
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/72729206/188576159-b7989368-95a8-4e32-aa92-39e4e97aeafc.png">
7、执行测试计划不选环境
<img width="580" alt="2" src="https://user-images.githubusercontent.com/72729206/188576233-77aa0de5-4733-47ae-bbf6-ce67c820b559.png">
8、发现结果还是以上次统一选的环境执行的
<img width="869" alt="image" src="https://user-images.githubusercontent.com/72729206/188576394-5fb2fb4a-779d-466e-a518-9a7119bf4fd7.png">
9、编辑测试计划内部case的环境也发现变成了一个环境
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/72729206/188576579-ac92de20-471b-4962-bb9e-40d3dbd0bdb2.png">

### 期待的正确结果

1、只有在执行测试计划时不选环境，都应该以当前关联用例的环境为准

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
已确认暂时不处理这个问题，等后续把测试计划单独做成一个模块的时候统一处理
