### ISSUE TITLE
[BUG]用例评审时，每一条用例都要手动点击保存，建议可以自动保存用例评审结果

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17718]
### 联系方式

蒋林峰

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

用例评审时，每评审一条用例都要手动点保存，很麻烦。有时候会直接点下一条用例，忘记点保存，
建议用例标记为通过或不通过后，会自动保存评审状态，无需给每一条用例手动保存评审结果

### 重现步骤

1.创建用例评审。关联多条用例
2.点击评审用例
3.每次标记一条用例评审状态后，都要手动点保存，很麻烦
![image](https://user-images.githubusercontent.com/88763608/188589768-766771ed-ad7b-42a3-9c10-01ba700d8425.png)

### 期待的正确结果

可以自动保存用例评审结果，减少人工劳动

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
