### ISSUE TITLE
[QUESTION] 接口定义模块，需要先登录获取 Cookie，怎么办？

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1773]
**请描述您的问题.**

目前的解决方法是，把 Cookie 写在环境变量上，在接口定义的 Header 上使用。
但是，如果场景自动化引用了这个接口，那边可以使用新的 Cookie 吗（先登录，并勾选共享 Cookie）？

**Comment by jhong123** [comment]
经过测试，发现场景自动化中的「共享 Cookie」，可以覆盖接口定义里面设定的 Cookie。
但接口定义模块，登录这一步，请问有更好的解决方案吗？

**Comment by xulinde** [comment]
接口定义模块，目前没啥好的方案
