### ISSUE TITLE
批量接口自动化转化性能测试会多次重复导入[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#17739]
### 联系方式

dongxue.liu@fit2cloud.com

### MeterSphere 版本

 v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

接口自动化场景批量创建性能测试时，会多次重复导入

### 重现步骤

1.接口自动化列表，批量选择2个以上场景
2.批量转化为性能测试
![image](https://user-images.githubusercontent.com/30932762/188635772-3495583b-5944-4c71-a4c3-9265eb8f475a.png)
3.在性能测试里面会发现场景多次重复导入了
![image](https://user-images.githubusercontent.com/30932762/188635926-4ce291eb-7f65-4b35-a53e-49527d855270.png)

### 期待的正确结果

批量接口自动化能够正常导入性能测试

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
