### ISSUE TITLE
[FEATURE] TCP测试中增加判断接口返回完成类型

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#17735]
### MeterSphere 版本

v1.20.10-lts

### 请描述您的需求或者改进建议

目前tcp接口如果遇到分包方式，无法进行处理，建议增加TCP接口中判断接口是否完成的类型：包头+包体方式。参考apifox如图

### 附加信息

![image](https://user-images.githubusercontent.com/8164903/188604708-52e10a64-95f6-474c-8beb-e0d14dfaed05.png)

**Comment by luty2018** [comment]
感谢反馈，我们调研一下，尽快排期
