### ISSUE TITLE
[BUG] TCP请求使用GBK发送报文，接收返回报文时显示乱码

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#17731]
### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

TCP请求使用GBK发送含有中文的报文，接收返回报文时显示乱码。
若TCP服务端使用GBK接收含有中文的报文，使用UTF8返回报文，MS中可以正常显示，说明MS默认使用了UTF8接收返回报文，并未使用GBK进行接收。

### 重现步骤

TCP服务端使用GBK接收含有中文的报文，使用UTF8返回报文，MS中可以正常显示，说明MS默认使用了UTF8接收返回报文，并未使用GBK进行接收。

### 期待的正确结果

GBK方式下展示正常得返回内容

**Comment by tangw1257** [comment]
另外TCP mock中编码好想也是同样的问题

**Comment by zyyfit** [comment]
重复问题，1.20.13版本已修复
https://github.com/metersphere/metersphere/issues/16526
