### ISSUE TITLE
[BUG]环境里配置全局脚本，并行批量执行用例当前用例只输出当前用例的日志

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17740]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.14-lts & v2.2

### 使用外置数据库

否

### 问题描述

单个用例控制台打印的日志显示出多个用例的执行日志，不方便问题排查
### 重现步骤

环境里配置全局脚本

1.场景1，测试计划关联多个用例，选择并行执行
![image](https://user-images.githubusercontent.com/30038088/191732219-efc660df-2785-419e-9bee-25c395853963.png)

2.测试用例批量并行执行，生成独立报告，单个用例控制台显示的多个用例日志
![image](https://user-images.githubusercontent.com/30038088/191731778-841364bd-ee4c-49cf-8fc5-8cda31db65a2.png)

3.场景里多个用例，选择执行，查看控制台显示 多个用例日志
![image](https://user-images.githubusercontent.com/30038088/191732806-6c8aaf94-44e1-4318-8ee6-164e18f0780a.png)

### 期待的正确结果

只打印当前用例的全局脚本执行日志，便于分析

**Comment by zyyfit** [comment]
目前控制台无法准确的精确到每一个case的具体日志，只能根据case执行时间进行展示

**Comment by zyyfit** [comment]
这个问题微服务之后的版本已经支持了，微服务之前的版本由于改动太大，暂时不支持了
