### ISSUE TITLE
[BUG]测试计划报告明细：左侧【目录】显示会遮挡部分报告信息，并且【目录】没有缩进操作。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17744]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

前置条件：  全屏显示，浏览器没有缩小

[BUG]测试计划报告明细中：【目录】显示会遮挡部分报告信息。
进入测试计划报告明细，左侧的【目录】信息，
1、【目录】位置不改变；并且也没有缩进【目录】的操作；
2、【目录】会遮挡部分报告信息。

### 重现步骤

[BUG]测试计划报告明细中【目录】显示会遮挡部分报告信息。
进入测试计划报告明细，左侧的【目录】信息，
1、【目录】位置不改变；并且也没有缩进【目录】的操作；
2、【目录】会遮挡部分报告信息。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/188766240-dbbddbbb-4a58-47d0-ba4b-32b257ec3eeb.png)

**Comment by zyyfit** [comment]
**没有复现，你的电脑是windows还是mav？是什么浏览器？是必现的吗？**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/73461316/188792677-04cc6569-ab05-48af-8ac4-673a2cb40241.png">
![image](https://user-images.githubusercontent.com/73461316/188792702-96653c35-dfaa-49b5-b38c-dd043f6798a1.png)
