### ISSUE TITLE
[BUG]使用外部数据库导致数据库的连接数很高，数据库端显示一直处于sleep状态不释放。

### ISSUE THREAD

**Issue by Jeremywyl** [metersphere/metersphere#17746]
### 联系方式

wangyanlin0110@163.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

是

### 问题描述

使用外部数据库导致数据库的连接数很高，数据库端显示一直处于sleep状态不释放。

### 重现步骤
部署方式使用helm部署  数据版本8.0.25
使用外部数据库发现metersphere-server服务端到数据库的连接数很高，数据库端显示一直处于sleep状态不释放。
/ # netstat -lan | grep ESTABLISHED | wc -l
431

### 期待的正确结果

可以通过修改什么参数可以控制下连接数吗？

**Comment by liuruibin** [comment]
k8s 部署的话可以修改configmap

spring.datasource.hikari.maximum-pool-size=你想要的数值
spring.datasource.quartz.hikari.maximum-pool-size=你想要的数值

可以自行修改

**Comment by yinmin2020** [comment]
> k8s 部署的话可以修改configmap
> 
> spring.datasource.hikari.maximum-pool-size=你想要的数值 spring.datasource.quartz.hikari.maximum-pool-size=你想要的数值
> 
> 可以自行修改
配置了上限10个连接数，数据库里依然是450多~metersphere-data-streaming要重启，metesphere-server服务也要重启吗？

**Comment by yinmin2020** [comment]
配置了上限10个连接数，数据库里依然是450多~metersphere-data-streaming要重启，metesphere-server服务也要重启吗？
