### ISSUE TITLE
[BUG]接口响应结果是 JSON 格式，使用 “推荐JSONPath” 提取，报 “响应结果不是 JSON 格式”

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17747]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.13-lts

### 使用外置数据库

否

### 问题描述

接口响应结果是 JSON 格式，使用 “推荐JSONPath” 提取，报 “响应结果不是 JSON 格式”

### 重现步骤

1.使用 MS 登录接口，请求成功后，点击 后置操作->JSONPath提取-> 使用 推荐JSONPath提取
2.接口响应结果是 JSON 格式，使用 “推荐JSONPath提取” ，报 “响应结果不是 JSON 格式”

**Comment by dashenyucainiao** [comment]
1、JSONPath推荐断言和参数提取都存在这个问题；

2、当响应体结构简单且数据行数不多（具体行数未验证出来）的情况下，是可以成功的。

**Comment by zyyfit** [comment]
1.20.14版本已修复
