### ISSUE TITLE
[FEATURE]添加项目分类管理

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#17743]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

建议项目管理支持通过新建目录来进行分类管理，解决当项目较多时，优化【测试跟踪】【项目】和【系统设置】【项目管理】显示体验；

### 请描述你建议的实现方案

支持新建目录来支持分类管理

### 附加信息

![企业微信截图_16625114488610](https://user-images.githubusercontent.com/6109912/188765045-b12bb18c-542c-4a89-b1d5-66be820a4981.png)

**Comment by luty2018** [comment]
在系统设置的项目管理中，项目列表已提供搜索以及高级搜索功能，请具体描述现在带来的困扰，谢谢
