### ISSUE TITLE
[BUG]接口场景切换环境后，SQL请求的数据源切换正常，但加入到测试计划后，数据源切换异常

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#17753]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.1

### 使用外置数据库

否

### 问题描述

接口场景切换环境后，SQL请求的数据源切换正常，但加入到测试计划后，数据源切换异常

### 重现步骤

重现步骤较多，请查看我录制的操作视频，时长3分30秒

https://meeting.tencent.com/v2/cloud-record/share?id=df660c36-6add-4332-8658-94e55dcb4764&from=3

### 期待的正确结果

测试计划中的数据源能随着测试环境正常切换

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.15已修复，请等待版本发布后验证
测试计划，切换环境，环境下有同名的数据库名称，应选同名的，否则取当前环境下数据库第一条信息
