### ISSUE TITLE
[BUG]接口自动化-场景批量转性能测试提示环境未配置

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17761]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

否

### 问题描述

1.接口自动化-场景刚开始未配置环境
2.批量编辑运行环境，配置环境，确定后，场景能正常执行，未提示环境未配置
![image](https://user-images.githubusercontent.com/103627487/188798440-04c40c98-1f7b-41d9-b74b-203532f69da4.png)
3.选中场景，批量创建性能测试，跳转到性能测试后会提示环境未配置
![image](https://user-images.githubusercontent.com/103627487/188798239-f4c29086-ad82-43f1-9716-6c11115c39fa.png)

### 重现步骤

1.接口自动化-创建场景刚开始未配置环境
2.批量编辑运行环境，配置环境，
3.选中场景，批量创建性能测试
![image](https://user-images.githubusercontent.com/103627487/188799068-f8e7ee89-4284-449b-b289-f972e77512b7.png)

### 期待的正确结果

环境未配置，批量编辑环境后，能正常批量创建性能测试

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
