### ISSUE TITLE
[BUG]功能用例中导出所有用例(excel格式)失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17762]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

功能用例中导出所有用例(excel格式)失败

### 重现步骤

1、功能用例列表选择所有用例

2、点击导出，页面会一直转圈

### 期待的正确结果

可以准确导出用例列表

### 附加信息

页面操作：
<img width="675" alt="image" src="https://user-images.githubusercontent.com/32027713/188801874-2a97704e-5c10-4017-ab45-f82239e13dd6.png">

后台info.log日志报错:

![image](https://user-images.githubusercontent.com/32027713/188801949-38e2da31-8f4a-42aa-abcf-202c0b966273.png)

**Comment by xulinde** [comment]
已知问题，重复，https://github.com/metersphere/metersphere/issues/17630
