### ISSUE TITLE
[BUG]场景内引用其他场景，执行结果显示不准确

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#17766]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.13-LTS

### 使用外置数据库

否

### 问题描述

1、场景内引用其他场景
2、被引用场景内包含自定义脚本
3、该自定义脚本里面的断言失败时，但是被引用场景状态执行成功

### 重现步骤

1、场景内引用其他场景
2、被引用场景内包含自定义脚本
3、该自定义脚本里面的断言失败时，但是被引用场景状态执行成功

### 附加信息

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/32027713/188825137-f0fb0fde-c502-4a54-8760-c674a1b01cb2.png">

脚本包含的断言：

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/32027713/188825238-4dc36c55-7c1d-4450-ab61-c6c108b07a8a.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
