### ISSUE TITLE
[BUG]前后置脚本使用 BeanShell 引用外部 Jar 包，在1.X版本的环境是可以的，在2.0环境，根据文档脚本，在new对象时，报找不到命名空间的错误。

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#17776]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

根据官方文档《前后置脚本使用 BeanShell 引用外部 Jar 包》，在1.X版本的环境是可以的，在2.0环境，根据文档脚本，在new对象时，报找不到命名空间的错误。

### 重现步骤

一、创建java项目；
二、编写java文件；
三、打包jar
四、ms上传jar
五、创建测试接口
六、编写测试脚本

### 期待的正确结果

跟1.0一样就行

### 相关日志输出

```shell
Sourced file: inline evaluation of: ``import com.ms.test.jar.TestJar;  int[] arr = {1,2,3,5}; TestJar test = new TestJ . . . '' : Typed variable declaration : Class: TestJar not found in namespace : at Line: 4 : in file: inline evaluation of: ``import com.ms.test.jar.TestJar;  int[] arr = {1,2,3,5}; TestJar test = new TestJ . . . '' : TestJar 
 in inline evaluation of: ``import com.ms.test.jar.TestJar;  int[] arr = {1,2,3,5}; TestJar test = new TestJ . . . '' at line number 4
```

**Comment by zyyfit** [comment]
请查看一下文件管理中的开启jar包按钮是否开启
![image](https://user-images.githubusercontent.com/73461316/189020557-e1b236fd-2cb4-434a-a010-937faaf45775.png)
