### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#17775]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v

### 使用外置数据库

否

### 问题描述

根据官方文档中描述，《前后置脚本使用 BeanShell 引用外部 Jar 包》，在1.0中是可以执行的，2.0中，在new对象的时候，报找不到命名空间

### 重现步骤

一、创建一个jar项目

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #17776
