### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by du0506** [metersphere/metersphere#1778]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
- 1.8.1

**Bug 描述**
简要描述您碰到的问题
- 场景执行时自定义请求的地址被替换为场景的运行环境地址
- 单步调试时也是一样被替换

**Bug 重现步骤**
1.  新建场景，新建自定义请求 调试时正常，但选了运行环境后就被替换了

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/22487352/113154915-149e3280-926b-11eb-9fea-ef585afae56e.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题呢，您那边是必现的吗？能说一下具体操作步骤吗

**Comment by du0506** [comment]
> 您好，没有复现这个问题呢，您那边是必现的吗？能说一下具体操作步骤吗

![image](https://user-images.githubusercontent.com/22487352/113369423-e6684200-9393-11eb-8a08-81dc3d957612.png)

这个场景是升级前配置的，我试了升级后重建场景也是一样的问题。
步骤就是在历史数据查询场景里配置运行环境地址A，但是这个场景需要先去另一个地址B登录拿到token，所以场景第一步就是配置了一个自定义登录请求去B获取token，然后再继续测试B地址的接口。结果现在调试或者执行时自定义请求的地址被替换为场景运行环境A了，导致登录失败。
后来我测试：新建场景（不选择运行环境）-新建自定义请求，调试可成功，但是场景的运行环境选择后再调试自定义请求就有问题了

**Comment by du0506** [comment]
请问这个bug有定位到原因吗？有修复吗？谢谢

**Comment by zyyfit** [comment]
> 请问这个bug有定位到原因吗？有修复吗？谢谢

您好，目前已经发布了1.9.2版本，我试了没有这个问题了，请升级后试一下
