### ISSUE TITLE
[BUG]在断言里面，对于数据查询结果为 空 的情况，${contCode_1} 和vars.get("contCode_1")两种写法，输出的结果是不一样的

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#17783]
### MeterSphere 版本

v1.20.11-lts

### 使用外置数据库

是

### 问题描述

在断言里面，对于数据查询结果为 空 的情况，${contCode_1} 和vars.get("contCode_1")两种写法，输出的结果是不一样的。

![77efc5fb998a54e32733cdf5c2e350e](https://user-images.githubusercontent.com/100331967/189009331-1c6cb3f0-edb4-4fe5-973b-f51019a083cb.jpg)

### 重现步骤

在断言里面，对于数据查询结果为 空 的情况，${contCode_1} 和vars.get("contCode_1")两种写法，输出的结果是不一样的。

**Comment by zyyfit** [comment]
这两种写法本身也有一定的区别，jmeter里也是这样的
![image](https://user-images.githubusercontent.com/73461316/189078831-6ef841d8-0433-48fb-b4d6-f017f76993a2.png)
