### ISSUE TITLE
[BUG]接口自动化测试>>场景列表：编辑场景保存后，列表中【通过率】未被更新。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17784]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]接口自动化测试>>场景列表：编辑场景保存后，列表中【通过率】未被更新。

1、接口自动化测试>>场景列表：编辑场景，然后保存自动化场景。
2、返回场景列表页面，【执行结果】变更为“未执行”，但是【通过率】却是“100%”

【执行结果】与【通过率】不符造成困惑

### 重现步骤

[BUG]接口自动化测试>>场景列表：编辑场景保存后，列表中【通过率】未被更新。

1、接口自动化测试>>场景列表：编辑场景，然后保存自动化场景。
2、返回场景列表页面，【执行结果】变更为“未执行”，但是【通过率】却是“100%”

【执行结果】与【通过率】不符造成困惑

### 附加信息

列表信息
![image](https://user-images.githubusercontent.com/78218624/189018717-b389160b-7b2f-4481-842f-52d7c3c17e65.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.2.0版本已修复，请等待版本发布后验证，编辑场景后执行结果不会变为未执行了，保持原有结果
