### ISSUE TITLE
[BUG] 用例导出显示奇怪符号

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#17785]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

用例导出显示奇怪符号

### 重现步骤

功能用例导出具体可查看图片

### 附加信息

![image](https://user-images.githubusercontent.com/39703025/189019106-bcd1b1a2-4f33-44ec-a373-0b46c9aacdb1.png)
![image](https://user-images.githubusercontent.com/39703025/189019153-8fde45e4-40eb-472e-8838-9382e24668ec.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.15版本修复，请等待版本发布后验证
