### ISSUE TITLE
[BUG]UI自动化后置脚本返回的变量值有问题，断言失败

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17781]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.13-lts

### 使用外置数据库

否

### 问题描述

UI自动化后置脚本有返回值，用变量名称接收了值，但是断言失败，显示变量没有引用到值

### 重现步骤

1.UI自动化添加后置脚本，设置返回值，并接收
![8bfb47b2de46422cd42bbe8c2bd9a90](https://user-images.githubusercontent.com/88763608/188857685-29e80387-fa74-4b41-a623-432de5ec0a13.jpg)
2.断言该返回值变量
3.执行UI自动化，显示断言失败
![55118c46998939ee64fa0221dadfa91](https://user-images.githubusercontent.com/88763608/188857766-78bd644b-b75e-40d1-9308-9d272805b34f.jpg)

### 期待的正确结果

正确断言

**Comment by zrfit** [comment]
后置脚本错误，截图中的脚本num并没有返回，只是调用了，改成return num();就可以了。

**Comment by linfengjjj** [comment]
了解了，还有一个疑问
调用这个num()函数，这个函数内部本身有个return的，
函数内部的返回，是识别不到的么？

**Comment by linfengjjj** [comment]
了解了，还有一个疑问
调用这个num()函数，这个函数内部本身有个return的，
函数内部定义的返回，是识别不到的么？

**Comment by zrfit** [comment]
您好： 
1、⾸先metersphere 执⾏脚本的逻辑是采⽤了excuteScript进⾏执⾏, 
如果脚本中进⾏了返回，会进⾏返回值的捕获，如果没有返回仅单纯执⾏脚本内容。 
2、您当前的情况是：return 123456;是函数内部的返回，num()；只进行了函数调用，并未对全局代码块进行返回。
