### ISSUE TITLE
[FEATURE]目前不支持随机生成手机号

### ISSUE THREAD

**Issue by linda0007** [metersphere/metersphere#17789]
### 联系方式

微信：xyl1262486659  邮箱：xieyl01@mingyuanyun.com

### MeterSphere 版本

v1.20.3-lts-b3

### 使用外置数据库

是

### 问题描述

随机生成手机号场景很常见，但是需要手动写脚本生成，很麻烦，希望能提供内置函数@phone ，支持随机生成手机号

### 重现步骤

![image](https://user-images.githubusercontent.com/20278174/189028514-c1d06ea6-a0b2-4176-a209-607436514de0.png)

### 期待的正确结果

希望能提供内置函数@phone ，支持随机生成手机号

**Comment by Hyyfit** [comment]
这个功能确实有必要，我们后面会做的，感谢反馈。

**Comment by linda0007** [comment]
为啥没必要，生成手机号不是很常见的一个功能吗。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月13日(周二) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]目前不支持随机生成手机号 (Issue #17789)




 
这个功能确实有必要，我们后面会做的，感谢反馈。

**Comment by Hyyfit** [comment]
有必要，你看错了吧？
![image](https://user-images.githubusercontent.com/95834771/190297797-42ba6b0c-e666-4a0a-876d-a7c9fa291ac9.png)

**Comment by linda0007** [comment]
不好意思，看错了，我看你把这个问题单关了，还以为没必要做，是否有时间规划安排什么时候做？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月13日(周二) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]目前不支持随机生成手机号 (Issue #17789)




 
这个功能确实有必要，我们后面会做的，感谢反馈。
