### ISSUE TITLE
[BUG]UI自动化中将第一个步骤拖拽到循环控制器下后，执行报错

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17780]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.13-lts

### 使用外置数据库

否

### 问题描述

UI自动化中将第一个步骤拖拽到循环控制器下后，执行报错

### 重现步骤

UI自动化中将第一个步骤拖拽到循环控制器下后，执行报错
![2c560ee6542bbd905476aff3e3c4d4f](https://user-images.githubusercontent.com/88763608/188851813-a0f39e76-948a-4b37-b8ad-cdcd238a3547.jpg)

**Comment by linfengjjj** [comment]
这个应该需要支持吧？
否则我们就应该禁用在最外层添加任何流程控制了，而且最外层的流程控制，实际中也的确需要这种场景

**Comment by zrfit** [comment]
和产品沟通确认，后续版本优化这个问题。

**Comment by zrfit** [comment]
您好，v2.5.0已优化该功能，发布后请升级尝试。
