### ISSUE TITLE
[BUG] 功能用例页面部分操作报错 403，然后直接跳转到 setting 页面

### ISSUE THREAD

**Issue by aspirin420** [metersphere/metersphere#17794]
### MeterSphere 版本

v1.19.3-lts

### 使用外置数据库

是

### 问题描述

* 点击用例模块会报错 403，然后跳转到 setting 页面，包括 admin 账号也会出现这样的问题

![image](https://user-images.githubusercontent.com/32863315/189071320-0ac0e6dd-02ea-41b8-87af-af74a085e03c.png)

<img width="729" alt="image" src="https://user-images.githubusercontent.com/32863315/189051804-6b7cef34-6b50-4daa-a865-3b3571e3ee6e.png">

### 重现步骤

不是所有的模块点击都会报错，怀疑是不是和用例有关系？

**Comment by aspirin420** [comment]
![image](https://user-images.githubusercontent.com/32863315/189055010-b144aaaf-43fc-4e3e-9fb9-932d0f5aaf68.png)

**Comment by aspirin420** [comment]
导入用例的时候也会出现同样问题

**Comment by xulinde** [comment]
您的版本有点低，建议您升级到v1.20.14-lts版本，我用v1.20.14-lts未复现该问题。您升级完再试下，如果还有问题请继续反馈～
