### ISSUE TITLE
[FEATURE]Dubbo接口测试的Interfaces希望增加搜索功能

### ISSUE THREAD

**Issue by MadelS-F** [metersphere/metersphere#178]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54617021/88876417-ceb14a80-d255-11ea-8bec-2fe5334a9433.png)

在dubbo接口测试->Interface标签下的->Interfaces下拉框中增加搜索功能

**请描述你建议的实现方案**
element ui 的下拉框filter-method可以自定义搜索方法

**Comment by wangzhen-fit2cloud** [comment]
与 #157 重复
