### ISSUE TITLE
[BUG]【用例评审】用例评审关联的功能测试用例列表按ID排序的显示结果和功能用例列表不一致

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#17805]
### 联系方式

交流群45，付世鹏，andy.fu@31huiyi.com

### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

是

### 问题描述

用例评审关联的功能测试用例列表按ID排序的显示结果和功能用例列表不一致。

### 重现步骤

1、用例评审关联用例。
2、该用例评审的关联的功能测试用例列表按ID排序。

### 期待的正确结果

按ID排序的显示结果和功能用例列表一致。

### 附加信息

![image](https://user-images.githubusercontent.com/110213256/189066576-81d5ec8a-5d11-4a9c-83f8-72e8a667a768.png)

**Comment by xulinde** [comment]
v2.2已优化～
