### ISSUE TITLE
[BUG]测试计划关联接口测试用例，定时任务，任务通知不生效

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#1780]
**MeterSphere 版本**
1.8.0

**Bug 描述**
测试计划，定时任务，任务通知不生效

**Bug 重现步骤**
1.  测试计划关联接口测试用例
2. 设置定时任务
3. 设置运行失败时企业微信群消息通知

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
v1.8.1已修复，请升级到1.8.1试一下

**Comment by SmallLeafW** [comment]
> v1.8.1已修复，请升级到1.8.1试一下

已经升级到1.8.1了，还是没有通知

**Comment by zyyfit** [comment]
您好，请问是使用的什么方式的消息通知呢？
目前已发布1.9.2版本，请升级一下试试。
如果还是不行的话，可以检查一下钉钉是否配置了过滤词语，过滤词语是否正确；邮件通知的话是否发送通知太频繁被拉黑等；
如果还是没有解决问题可以加入我们的用户群详细讨论一下
![图片](https://user-images.githubusercontent.com/73461316/118260692-2f5bfc00-b4e5-11eb-8ff1-51415783e407.png)
