### ISSUE TITLE
[BUG]新建【接口定义-选择所有数据-导出-导出为MeterSphere格式】的接口case，点击case的ID进入页面，后台会出现空指针的错误日志。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17806]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

新建【接口定义-选择所有数据-导出-导出为MeterSphere格式】的接口case，点击case的ID进入页面，后台会出现空指针的错误日志。
<img width="960" alt="594ca15906173f07b56f0470195d14a" src="https://user-images.githubusercontent.com/104960608/189072790-eb2a3688-dffc-46b6-bb37-34cf7f421f19.png">

![image](https://user-images.githubusercontent.com/104960608/189072716-758c567b-6ef0-475b-8d22-4efdd5033d75.png)

### 重现步骤

1.【接口定义-选择所有数据-导出-导出为MeterSphere格式】抓取这个接口
<img width="483" alt="1662625001(1)" src="https://user-images.githubusercontent.com/104960608/189071842-a499e729-dc9d-4ab7-a691-bc97fa29ee6e.png">
2.将该接口进行调试，调式成功后，保存为case
![image](https://user-images.githubusercontent.com/104960608/189072092-fabc112b-ab7e-4ddb-a1bc-c0a18614c11f.png)
3.case页面，点击该case的ID进入页面，会发现后台在报错。
<img width="673" alt="1662625131(1)" src="https://user-images.githubusercontent.com/104960608/189072256-c50bbcfe-3267-482d-aeba-244d73671a69.png">
4.报错信息如下
![image](https://user-images.githubusercontent.com/104960608/189072344-9efb0459-6ed9-46c5-a373-340c381903ab.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，无法复现该问题，后台错误在页面上没什么影响吧？
