### ISSUE TITLE
[FEATURE] metersphere jenkins plugin优化，参数化执行的计划名称/场景名称

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#17802]
### MeterSphere 版本

jenkins plugin

### 请描述您的需求或者改进建议

对于同一个项目workspace id，参数化测试计划或测试计划。
使用jenkins时只需要填写参数即可，避免创建非常多的jenkins job.
![image](https://user-images.githubusercontent.com/9674075/189108918-d0ef834a-877f-40c8-864a-ee0c09280489.png)
如图，
1、参数化项目名称
2、参数化执行的计划、场景名称

### 请描述你建议的实现方案

测试计划或场景参数化，提供参数名，即可

**Comment by luty2018** [comment]
不好意思， 没有太理解，能否更进一步描述？

**Comment by xchnshi** [comment]
修改了描述

**Comment by luty2018** [comment]
了解了， 这个可以支持，预计在2个版本内。
