### ISSUE TITLE
[BUG] 首页的用例责任人分布没有显示出所有人的用例数量

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#17807]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

首页的用例责任人分布没有显示出所有人的用例数量

### 重现步骤

首页的用例责任人分布没有显示出所有人的用例数量

### 期待的正确结果

希望可以点进有个详情之类的能查询所有创建人或者责任人的用例

### 附加信息

![image](https://user-images.githubusercontent.com/39703025/189080132-30522c8a-7f97-4d1e-a65c-dbc2c5110f8b.png)
![image](https://user-images.githubusercontent.com/39703025/189080356-daec2944-0d19-4062-baae-daaccbb5edd0.png)

**Comment by xulinde** [comment]
未复现该问题，能详细描述下必现步骤吗？
