### ISSUE TITLE
[FEATURE] 接口请求参数下“请求体”中有内容时，没有标记

### ISSUE THREAD

**Issue by magicpose** [metersphere/metersphere#17819]
### MeterSphere 版本

v2.0.0

### 请描述您的需求或者改进建议

请求头，Query参数，rest参数中增加参数都会在title处有体现，请求体添加内容则没有。这样让人感觉请求体中没有数据，但实际是有的，使用有点别扭，希望能改善同样增加标记，不一定是参数个数
![image](https://user-images.githubusercontent.com/7636934/189254406-b2f30610-8a58-49eb-8f0c-936925d553ae.png)

**Comment by luty2018** [comment]
收到，我们会在下个版本优化
