### ISSUE TITLE
[BUG] 报告总结有的显示有的不显示

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#17820]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 使用外置数据库

是

### 问题描述

报告总结有的显示有的不显示

### 重现步骤

点击接口测试进入详情

### 附加信息

![image](https://user-images.githubusercontent.com/39703025/189257299-10e303a4-24b0-4536-a9e5-7121759ea50c.png)

**Comment by xulinde** [comment]
未复现该问题，请详细描述下复现步骤～
