### ISSUE TITLE
[QUESTION]对于数据库结果null的处理，转换成String类型时，放在外面和if里面，控台打印出的结果不一样

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#17829]
### 请描述您的问题

对于数据库结果null的处理，转换成String类型时，放在外面和if里面，控台打印出的结果不一样。

![image](https://user-images.githubusercontent.com/100331967/189299239-f9bc0115-eacd-409c-a716-f2aab71913dc.png)

**Comment by Hyyfit** [comment]
jmeter里也是一样的。暂不处理这个

<img width="937" alt="image" src="https://user-images.githubusercontent.com/95834771/190567745-a09df8f3-2a4d-4e22-912a-e59d7295b788.png">
