### ISSUE TITLE
[BUG]UI自动化执行成功，用例状态也是通过，但是测试报告状态为ERROR

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17821]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.14-lts

### 使用外置数据库

否

### 问题描述

UI自动化执行成功，用例状态也是通过，但是测试报告状态为ERROR

### 重现步骤

1.UI自动化执行成功，用例状态也是通过，但是测试报告状态为ERROR
2.我用的是附件的脚本
![e671632d5e0ee3c74dd071a4d17a220](https://user-images.githubusercontent.com/88763608/189259111-302adf8a-cc36-4154-8588-8f9ebd23a1be.jpg)
![5897da0008e7ec6e2d11c14223d3891](https://user-images.githubusercontent.com/88763608/189259121-445b1630-9710-43f7-86d0-5a3e97996113.jpg)
![a97d39ca1beff51973e7ca6d8dd24b7](https://user-images.githubusercontent.com/88763608/189259126-2c6027ad-58ce-4ef2-ae9a-a3afdd85d2ba.jpg)

### 附加信息

[Metersphere_Ui_默认项目.zip](https://github.com/metersphere/metersphere/files/9531837/Metersphere_Ui_.zip)

_No response_

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、UI步骤中的前后置脚本仅支持js脚本，vars.put("")是不支持的；
2、步骤中脚本的执行失败不会影响步骤结果，测试报告列表状态处理的时候未对该情况做处理，造成了该问题，下个版本优化。

**Comment by zrfit** [comment]
v1.20.15-lts已修复。
