### ISSUE TITLE
[BUG]缺陷管理将缺陷变更状态之后，在测试计划报告中关联的缺陷状态未发生改变。

### ISSUE THREAD

**Issue by 666liiuliuliu** [metersphere/metersphere#17830]
### 联系方式

交流群49 Dylan

### MeterSphere 版本

2.1

### 使用外置数据库

否

### 问题描述

缺陷管理将缺陷变更状态之后，在测试计划报告中关联的缺陷状态未发生改变。
![5974439c5996d1283dce1d62c9ae1be](https://user-images.githubusercontent.com/113175834/189322063-2add8804-4961-4dfe-bc0a-72ed6f4cdfcb.jpg)

![883367701a0f45e36dbeee45dcd30a6](https://user-images.githubusercontent.com/113175834/189322093-d1468197-af27-48ac-b3d5-e0d8517ecda2.jpg)

### 重现步骤

1.测试计划，新增缺陷。
2.缺陷管理，变更缺陷状态
3.测试计划，查看报告。已关联缺陷状态不正确。

### 期待的正确结果

测试计划已关联缺陷状态是否应该跟随缺陷管理状态一致？

**Comment by xulinde** [comment]
v2.2.已修复～
