### ISSUE TITLE
[BUG]v1.1 版本 Swagger 导入v1.0版本的接口列表中，【数据更新版本】和【数据创建版本】都选择v1.1版本，导入进去后API全量新增成了v2版本

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17834]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.14-lts && v2.1.0

### 使用外置数据库

否

### 问题描述

v1.1 版本 Swagger 导入v1.0版本的接口列表中，【数据更新版本】和【数据创建版本】都选择v1.1版本，导入进去后API全量新增成了v2版本

### 重现步骤

1.导入初始 v1.0版本的 swagger ，假如有7个接口
![image](https://user-images.githubusercontent.com/30038088/189333972-04e49970-3312-4c52-b0b4-56e29b95f4c5.png)

2.版本管理-新建一个 v1.1 版本，并设置成 最新版本
3.更新 swagger文件中其中2个接口的参数，新增2个接口
4.导入 swagger ，选择【覆盖】，【数据更新版本】和【数据创建版本】都选择v1.1版本
![image](https://user-images.githubusercontent.com/30038088/189334535-c4f58f4d-945a-46c1-8002-b7276f1e47e9.png)
5.导入进去，v1.1 显示有 9 个接口

### 期待的正确结果

正常 v1.1 应该只显示 变更的2个接口和新增的2个接口。

**Comment by zyyfit** [comment]
这个问题已转需求

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
