### ISSUE TITLE
[BUG] 导入有存量有修改用例的文件到新版本，选择覆盖，新版本为全部导入接口数据

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#17833]
### 联系方式

18311441708

### MeterSphere 版本

v2.1-af91f9ef

### 使用外置数据库

否

### 问题描述

导入有存量有修改用例的文件到新版本，选择覆盖，新版本为全部导入接口数据

### 重现步骤

现有存量用例100个在v1.0，创建新的版本v2.0，并设置细心现研发更新了原有的10个接口，和增加了50接口，导入这个150个用例的文件

目前现象是v2.0新建了150个用例

### 期待的正确结果

导入有存量有修改用例的文件到新版本，选择覆盖，新版本为新增和修改的接口

导入可实现v1.0有90个未升级的接口，v2.0有60个新接口

**Comment by luty2018** [comment]
与17834重复
