### ISSUE TITLE
[BUG] UI 测试点击“后端调试”，界面没有渲染执行结果

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#17843]
### 联系方式

18159668371

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

问题现象：UI 测试点击“后端调试”，界面没有渲染执行结果。
1、步骤左侧的成功图标以及每个步骤的执行之后的步骤结果 均无展示；
2、按钮状态从“停止”转换为“后端调试”

附问题复现视频：
https://user-images.githubusercontent.com/92966838/189798966-2c1d604f-b7a7-4c18-8d75-f966214db8b8.mp4

排查：
复现问题后，打开浏览器 console，有下述报错出现：
![image](https://user-images.githubusercontent.com/92966838/189801241-f9e07869-6f44-4230-8cf1-d6a36e201a05.png)

### 重现步骤

1、IDE 录制 脚本，下载 side 文件；
2、MS 上传 side 文件；
3、点击后端调试。

### 期待的正确结果

点击调试后，界面可以正常展示步骤的执行结果

**Comment by gaohonghai** [comment]
https://user-images.githubusercontent.com/92966838/189799219-2ed0ba09-5827-451c-81ca-0769aacb83be.mp4

**Comment by zrfit** [comment]
您好，未复现该问题，您这个场景是必现的吗？方便导出场景吗？我们尝试复现下。
