### ISSUE TITLE
[BUG] 工作台-我的待办（功能用例）点击跳转，跳转页面不对。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#17844]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

工作台-我的待办（功能用例），点击某个用例，跳转到用例列表而不是某个用例的详情。

https://user-images.githubusercontent.com/33945037/189802169-5003482b-9047-4dd5-914f-56b21a3b518d.mov

### 重现步骤

工作台-我的待办（功能用例），点击某个用例，跳转到用例列表而不是某个用例的详情。

### 期待的正确结果

工作台-我的待办（功能用例），点击某个用例，跳转到用例列表而不是某个用例的详情。

**Comment by youliyuan-fit2cloud** [comment]
v2.2.0中已优化。
