### ISSUE TITLE
[BUG]项目设置-文件管理，上传Jar包的更新时间错误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#17845]
### 联系方式

张树彬

### MeterSphere 版本

1.20.14

### 使用外置数据库

否

### 问题描述

项目设置-文件管理，上传Jar包的更新时间错误

### 重现步骤

1. 项目设置-文件管理，上传Jar包
2. 上传成功后，Jar包列表的更新时间错误，与实际上传时间不符

### 期待的正确结果

显示正确上传Jar包时间

### 附加信息

![1663045974835](https://user-images.githubusercontent.com/77324661/189814651-b02ffdfd-e0d4-4202-b080-318fb63333f9.jpg)

**Comment by youliyuan-fit2cloud** [comment]
你好，这是你电脑和服务器的时间，请确认下服务器时间是否一致吧。
