### ISSUE TITLE
[BUG]接口测试>>接口列表：列表头上的【版本】筛查有bug，查找不到正确的接口记录。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17842]
### MeterSphere 版本

V1.20.14lts

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口列表：列表头上的【版本】筛查和【最新版本】筛查，其两者的查询结果不一样。

条件：接口至少有2个不同的版本，在明细中也能查看到。

1、接口测试>>接口列表：【最新版本】筛查，能查看到指定版本的接口
2、接口测试>>接口列表：列表头上的【版本筛查】，查找不到指定版本的接口

### 重现步骤

[BUG]接口测试>>接口列表：列表头上的【版本】筛查和【最新版本】筛查，其两者的查询结果不一样。

条件：接口至少有2个不同的版本，在明细中也能查看到。

1、接口测试>>接口列表：【最新版本】筛查，能查看到指定版本的接口
2、接口测试>>接口列表：列表头上的【版本筛查】，查找不到指定版本的接口

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/189793708-c5600ed4-cc80-4887-b86c-d77039720632.png)
![image](https://user-images.githubusercontent.com/78218624/189794521-bd245903-b47c-4daa-874a-dc0665c5264b.png)
![image](https://user-images.githubusercontent.com/78218624/189794879-1df2419e-b4dd-489d-964c-44578b9f8dd2.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，仅筛选当前列表显示的接口定义结果，如果要看其他版本从文档右侧的版本筛选。
