### ISSUE TITLE
[BUG]执行测试计划后报告创建人显示不正确

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#17849]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

测试计划报告创建人正常展示的应该是case的创建人，现展示的是测试计划的创建人
![4b9ddef52fa82797a642be52128fae3](https://user-images.githubusercontent.com/103627487/189821759-66e2ece6-b8ce-450c-8519-abbd896e7b0a.jpg)
![92e61ea8367739630d561f70e6906fc](https://user-images.githubusercontent.com/103627487/189821792-7040d61e-478c-4f8d-b4fb-aa90a30809ee.jpg)

### 重现步骤

1.创建测试计划，测试计划关联case,case创建人与测试计划创建人不一致
2.执行测试计划，查看报告中展示的创建人

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
