### ISSUE TITLE
[BUG]接口设置模块，设置字符长度失效

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17851]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

2.1

### 使用外置数据库

否

### 问题描述

接口定义模块，接口case，“高级设置”设置好字符串长度，没任何反应

### 重现步骤

设置长度：
![image](https://user-images.githubusercontent.com/15188833/189835334-228d3f4d-5a2a-4ec9-bc22-63482701d1b8.png)

执行接口case，参数：
![image](https://user-images.githubusercontent.com/15188833/189835371-20c6ebfa-3c24-4b67-a2ea-97a8492c5a55.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈， 目前这里的设置不生效，仅在请求体-是json-schema格式的高级设置中生效。
