### ISSUE TITLE
[BUG] 接口测试报告无法自动清理

### ISSUE THREAD

**Issue by genezx** [metersphere/metersphere#17869]
### MeterSphere 版本

v1.20.12

### 使用外置数据库

是

### 问题描述

上月底在项目设置里面开启了“定时清理接口测试报告：保留7天内报告”的功能，但是半个月来至今从来没有触发自动清理。我上次手动删到8月18日，但是8月18日起的所有报告并没有自动清理。

### 重现步骤

。

### 附加信息

![image](https://user-images.githubusercontent.com/31116612/190034412-8eadbda5-1243-47b4-9d51-3a3246a1ca3d.png)
![image](https://user-images.githubusercontent.com/31116612/190034489-87792a30-598f-41a6-b62e-f84cf7470598.png)
![image](https://user-images.githubusercontent.com/31116612/190034558-5d8698a6-1325-4b06-8270-49821507c8c5.png)

**Comment by zyyfit** [comment]
您好，可以参考一下这个问题，如果无法解决的话，麻烦上传一下最近几天的日志信息
