### ISSUE TITLE
希望服务集成能支持redmine缺陷管理系统[FEATURE]

### ISSUE THREAD

**Issue by lvsheshamo** [metersphere/metersphere#17864]
### MeterSphere 版本

v1.20

### 请描述您的需求或者改进建议

希望服务集成能支持redmine缺陷管理系统

### 请描述你建议的实现方案

缺陷管理能支持和redmine系统关联，能同步redmine的缺陷信息

**Comment by luty2018** [comment]
我们预计会在v2.4版本将第三方平台对接的功能改造成插件机制，方便用户自行扩展第三方平台的对接

**Comment by lvsheshamo** [comment]
V2.4版本预计什么时候发布？
