### ISSUE TITLE
[BUG]工作台>>我的仪表盘>>我创建的用例：点击“马上创建”，页面调整到项目设置页面，而不是用例创建页面

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#17876]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]工作台>>我的仪表盘>>我创建的用例：点击“马上创建”，页面调整到项目设置页面，而不是用例创建页面

条件：新创建的工作空间、项目，并且给用户分配了工作空间权限和项目管理员权限。

操作：
1、用户登录系统，选择【工作台>>>>我的仪表盘】
2、我创建的用例：显示为0条，旁边的点击【马上创建】
3、问题：系统跳转到项目设置页面，而不是测试用例创建页面。

### 重现步骤

[BUG]工作台>>我的仪表盘>>我创建的用例：点击“马上创建”，页面调整到项目设置页面，而不是用例创建页面

条件：新创建的工作空间、项目，并且给用户分配了工作空间权限和项目管理员权限。

操作：
1、用户登录系统，选择【工作台>>>>我的仪表盘】
2、我创建的用例：显示为0条，旁边的点击【马上创建】
3、问题：系统跳转到项目设置页面，而不是测试用例创建页面。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/190054258-c04b06b3-15cd-4c8a-b453-f2fa9c0c89e9.png)

**Comment by xulinde** [comment]
v2.2.0已修复～
