### ISSUE TITLE
[BUG]Post请求，Json数据，会执行UrlEnconde

### ISSUE THREAD

**Issue by iamhaoren** [metersphere/metersphere#17870]
### 联系方式

2362578972@qq.com

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

否

### 问题描述

Post请求，json数据格式。
Case 前置操作：
0、获取请求body
1、加密body
2、sampler.addArgument("",body)，放入新body
发送请求时，meterSphere 会将body进行 URLEncode，导致服务端解密失败。
![image](https://user-images.githubusercontent.com/34563392/190049566-1900f8e6-938e-4f09-886b-a93389ced113.png)

### 重现步骤

Post请求，json数据格式。
Case 前置操作：
0、获取请求body
1、AES加密body
2、sampler.addArgument("",body)，放入新body
发送请求时，meterSphere 会将body进行 URLEncode，导致服务端解密失败。

### 附加信息

![image](https://user-images.githubusercontent.com/34563392/190049582-ebfa075a-f1d4-4d74-99dd-96798f7b4aeb.png)

**Comment by zyyfit** [comment]
您好，我看了一下，jmeter也是这样的，不过可以用变量的方式添加body，不会改变变量值
![image](https://user-images.githubusercontent.com/73461316/190345259-3e4c208e-2887-4001-938c-e870f17655ad.png)
