### ISSUE TITLE
[BUG]最新版本环境变量优先级大于了场景变量

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17873]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

最新版本环境变量优先级大于了场景变量

### 重现步骤

1.设置环境变量name=123456
<img width="756" alt="企业微信截图_16631208504201" src="https://user-images.githubusercontent.com/88763608/190053763-e85ce56c-3709-4ebb-b096-7824335a1098.png">

2.设置场景变量name=linfeng
<img width="744" alt="企业微信截图_16631208163486" src="https://user-images.githubusercontent.com/88763608/190053777-acd6ad41-5ddf-42de-9797-688216e44fd3.png">

3.请求中使用${name}，引用到了环境变量，跟旧版本不一致了
![image](https://user-images.githubusercontent.com/88763608/190053826-09145341-6def-4f3a-8cfe-78c60907096b.png)

### 期待的正确结果

产品：场景变量>环境变量

**Comment by zhangzhaox** [comment]
规范使用变量才是解决根本

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.2.0版本已修复，请等待版本发布后验证
