### ISSUE TITLE
[BUG]回收站里默认展示“废弃”状态的接口，但是列表筛选条件依然在，清除筛选条件后，可查询出其他正常状态的接口

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17878]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.14-lts & v2.1.1

### 使用外置数据库

否

### 问题描述

回收站里默认展示“废弃”状态的接口，但是列表筛选条件依然在，清除筛选条件后，可查询出其他正常状态的接口

### 重现步骤

1.切到回收站，点击 “接口状态” ，清除 “筛选条件” 可查询出其他正常状态的接口
![image](https://user-images.githubusercontent.com/30038088/190055101-800aea2d-aa0f-4a07-a606-ce9de13a0685.png)

**Comment by xulinde** [comment]
v2.1.1已经把筛选功能去掉了，不存在此问题。1.20分支后续也会去掉
