### ISSUE TITLE
[QUESTION]通过pipeline方式发起性能测试

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#17872]
### 请描述您的问题

1、请问下MS支持pipeline方式发起性能测试么？
2、MS的接口文档中性能测试的请求参数方便说明一下么，不知道如何构造下面这个接口请求？
接口：performance/run，body请求如下：（接口里的参数含义不明）
{
  "id": "string",
  "projectId": "string",
  "name": "string",
  "description": "string",
  "createTime": 0,
  "updateTime": 0,
  "loadConfiguration": "string",
  "advancedConfiguration": "string",
  "runtimeConfiguration": "string",
  "schedule": {
    "id": "string",
    "key": "string",
    "type": "string",
    "value": "string",
    "group": "string",
    "job": "string",
    "enable": true,
    "resourceId": "string",
    "userId": "string",
    "workspaceId": "string",
    "createTime": 0,
    "updateTime": 0,
    "projectId": "string",
    "name": "string",
    "config": "string"
  },
  "testResourcePoolId": "string",
  "refId": "string",
  "versionId": "string",
  "follows": [
    "string"
  ],
  "userId": "string",
  "triggerMode": "string",
  "testPlanLoadId": "string",
  "ownLoadConfiguration": "string",
  "ownTestPoolId": "string"
}

**Comment by luty2018** [comment]
目前我们支持通过pipeline方式执行测试计划或测试用例：
具体参考：https://mp.weixin.qq.com/s/LxZKKbrtvX5P7oub1xzwuA

**Comment by xieqione** [comment]
请问下目前支持Azure pipeline么？
