### ISSUE TITLE
[BUG]接口列表 选中某个模块，切到 接口首页【未覆盖】接口，进去后【高级搜索】 带着之前选中的模块的条件,但是【高级搜索】并未显示出条件信息，导致搜其他模块接口搜不到

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17877]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.14-lts & v2.1.1

### 使用外置数据库

否

### 问题描述

接口列表 选中某个模块，切到 接口首页【未覆盖】接口，进去后【高级搜索】 带着之前选中的模块的条件,但是【高级搜索】并未显示出条件信息，导致搜其他模块接口搜不到

### 重现步骤

1.接口列表，选中【全部接口】，切到接口首页【未覆盖】，点击跳转，列表有38个接口，记录 接口 “/add/def/user”
![image](https://user-images.githubusercontent.com/30038088/190053879-215f9ce7-e235-42cb-bbdf-0e7bd9c52d15.png)
2.选中 "MeterSphere" 模块
![image](https://user-images.githubusercontent.com/30038088/190054014-95fd06cd-cc7c-4580-88b6-e2b87662781b.png)
3.重新切回 接口首页【未覆盖】，再点击跳转，默认还是 选中  "MeterSphere" 模块
![image](https://user-images.githubusercontent.com/30038088/190054094-51f7ef19-1984-41dd-93c5-1bc7a84c3f1c.png)
4.搜索  接口 “/add/def/user” ，搜索不到，点击 【高级搜索】没有任何 条件信息。
![image](https://user-images.githubusercontent.com/30038088/190054276-cc071d38-c44d-4e74-9cd2-7e3f4abd6a31.png)

### 期待的正确结果

【高级搜索】如果带上次记录的条件信息，建议 在【高级搜索】里显示出来，这样 从其他页面切回去后，用户在重新做搜索时，能够看到 上次记录的查询信息，不至于 有搜索不到的情况。

**Comment by xulinde** [comment]
v1.20.15-lts & v2.2均已修复～
