### ISSUE TITLE
[FEATURE]功能用例维护缺少对判定表用例的支持

### ISSUE THREAD

**Issue by 1ToKiSa** [metersphere/metersphere#17886]
### MeterSphere 版本

2.1.1

### 请描述您的需求或者改进建议

1、测试跟踪-功能用例，用例模板缺少判定表类型的模板。在遇到大型系统时，会很麻烦；
2、由于上面1问题，自己创建判定表用例模板，但新增模板时，字段无法排序。导致自定义字段先后顺序混乱；
3、由于新增了自定义字段，在用例维护时，左侧的基础信息栏太过窄小，无法完全展示自定义字段；
4、自定义字段本身的框太小，无法自适应，每次打开都需要拉动，上千条用例，每条都拉动，令人反感。

### 请描述你建议的实现方案

1、期望增加判定表用例的功能用例模板；
2、期望在维护用例模板时，能够给字段排序；
3、期望功能用例打开时，左侧的基础信息栏能够设置大小且后续再打开固定大小不变；
4、期望自定义字段时，能够设置输入框的大小；或者在功能用例页面打开时，能自适应大小；或者在自定义用例模板时，能将字段配置到“步骤描述”和“前置条件”中间位置。

### 附加信息

<img width="1209" alt="微信图片_20220914185549" src="https://user-images.githubusercontent.com/110890934/190136153-c360221e-dbbc-47e0-9388-34c0249bdaaa.png">

**Comment by luty2018** [comment]
2、3、4点都可以优化， 我们会在3个版本内调整，感谢反馈。
