### ISSUE TITLE
[BUG]使用期间系统不定时出现被强制退出（高频）

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#17885]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

使用期间系统不定时出现被强制退出，从 redis 查 session 并未出现超时

### 重现步骤

使用期间系统不定时出现被强制退出，从 redis 查 session 并未出现超时

**Comment by maninhill** [comment]
1.20.14-lts 版本上也一样有问题吗？

**Comment by shenkaibo** [comment]
已解决，少了个 SERVER_SERVLET_SESSION_COOKIE_MAX-AGE 配置

**Comment by shenkaibo** [comment]
已解决，少了个 SERVER_SERVLET_SESSION_COOKIE_MAX-AGE 配置
