### ISSUE TITLE
[BUG] [企业用户] 返回报文JSON格式校验错误

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#17883]
### MeterSphere 版本

1.20.13

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/103017812/190108337-771c8248-90b3-494c-a7a5-15807a5455cb.png)
实际是合法的JSON

{
  "clientRequestId": "PremSAcal20220914164633680",
  "clientRequestTime": "2022-09-15T00:46:33",
  "result": 1,
  "calculatePolicyResult": {
    "inceptionDate": "2022-09-14T00:00:00",
    "installPrem": 1700,
    "annualPrem": 1700,
    "policyFee": 0,
    "policyFeeAn": 0,
    "calculateCoverageResults": [
      {
        "extendedProps": {},
        "coverageId": 1,
        "productCode": "FamilyProduct",
        "sumAssured": 50000,
        "policyFee": 0,
        "stdPremAf": 1700,
        "totalPremAf": 1700,
        "discntedPremAn": 1700,
        "discntedPremAf": 1700,
        "stdPremAn": 1700,
        "paymentFrey": "5",
        "insureds": [
          {
            "age": 31,
            "gender": "F",
            "birthdate": "1992-08-02T00:00:00",
            "smoking": "N",
            "orderId": 1
          }
        ],
        "extraPremiums": [],
        "grossPremAf": 1700,
        "discntPremAf": 0,
        "discntPremBf": 0,
        "discntPremAn": 0,
        "unit": 1,
        "premAn": 1700,
        "premAnBeforeDiscount": 1700
      }
    ]
  }
}

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请问下，这个是接口自动化里面的场景吧，场景中导入的接口case还是自定义请求？
