### ISSUE TITLE
[BUG]接口自动化场景引用另一个接口自动化场景，被引用场景内部包含自定义脚本请求且该请求内部有脚本断言，实际执行时该脚本断言执行失败，被引用场景显示成功

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17887]
### 联系方式

王进

### MeterSphere 版本

1.20.14

### 使用外置数据库

否

### 问题描述

接口自动化场景引用另一个接口自动化场景，被引用场景内部包含自定义脚本请求且该请求内部有脚本断言，实际执行时该脚本断言执行失败，被引用场景显示成功

### 重现步骤

1. 新建一个场景，引用一个已经存在的场景， 被引用场景里包含自定义脚本请求，且该自定义请求断言规则里有两个断言，断言是失败的。
2. 调试该场景，会发现场景执行结果是Success, 被引用场景执行结果也是Success，但是被引用场景里面的自定义脚本请求断言是失败的。
![image](https://user-images.githubusercontent.com/76033005/190173850-b9c74fc3-31dc-4cf1-bc52-5bf2b6951c15.png)

### 期待的正确结果

场景和被引用场景执行结果都应该是失败的。

### 附加信息

客户这边是 1.20.14

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #17766

**Comment by 35plus** [comment]
收到
