### ISSUE TITLE
[QUESTION]性能测试问题咨询

### ISSUE THREAD

**Issue by Phoebus888** [metersphere/metersphere#17889]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/45359605/190201111-ed83b0a8-4ba3-4be8-accc-c7e9dd798efa.png)
```
上面并发用户数我设置100,我有4台压测机  是不是总的线程压测就是100*4   一共有400线程压测
```

**Comment by zhangzhaox** [comment]
1、设置的100线程 就是100   跟你的多少台负载机没用必然的联系
2、设置的100线程 可以指定单节点负载机资源池运行  也可以指定多台负载机组成的集群资源池运行
