### ISSUE TITLE
[BUG] Jenkins插件执行job，时好时坏。并且执行之后MS计划状态未更新。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#17888]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

1. Jenkins job 执行测试计划，是好是坏。
2. 生成的测试报告链接端口不对，因为在部署项目的时候，已经把端口改成80端口了，生成的报告不应该有8081才对。

https://user-images.githubusercontent.com/33945037/190188817-a23e95fa-1ca6-4a36-8d19-624b1cc460ab.mp4

https://user-images.githubusercontent.com/33945037/190188861-7fb4372c-d7f4-48ca-aa5d-3ede922931e1.mov

### 重现步骤

Jenkins 版本：[Jenkins 2.346.3]
MS版本：   v2.1.1
Jenkins插件版本：metersphere-jenkins-plugin-v2.1.1.hpi

**Comment by youliyuan-fit2cloud** [comment]
2.生成的测试报告链接端口不对，因为在部署项目的时候，已经把端口改成80端口了，生成的报告不应该有8081才对。
---->这个请确认一下，当前站点配置是改成80端口 ？

**Comment by hao65103940** [comment]
谢谢，端口这个问题已解决。

**Comment by youliyuan-fit2cloud** [comment]
问题1，没有复现，请先自查一下手动执行该测试计划是否正常，单独执行测试计划中的用例是否正常？
