### ISSUE TITLE
[BUG]同一请求，在fidder上选择为xml格式正常显示，在ms上选择为xml格式显示异常。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17884]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.4-lts

### 使用外置数据库

否

### 问题描述

soap协议，返回的响应体为xml格式，选择xml格式进行展示，响应体显示的中文异常。同样的请求，fidder选择 xml 格式就正常显示。

### 重现步骤

1.请求在fidder上发送 soap协议，选择row格式和xml格式，可以看到row格式中文数据展示异常
![企业微信截图_16631463091003](https://user-images.githubusercontent.com/104960608/190123356-2df05388-9ba7-445d-8aa7-f7f8bd3262fa.png)

xml格式正常展示
![企业微信截图_16631468698091](https://user-images.githubusercontent.com/104960608/190123472-c628a449-bd8d-4455-b1de-c96c4af1b2e0.png)

2.在ms系统发送同一soap协议请求，选择xml格式展示，可以看到xml格式中文数据展示异常
![3f2ea146-81a8-457b-a3ce-c43df9bab2d1](https://user-images.githubusercontent.com/104960608/190123666-e6780d84-de4d-4a1d-b00b-67f8e984f822.png)

**Comment by youliyuan-fit2cloud** [comment]
1. 为HttpSampler新建后置控制器”BeanShell PostProcessor”
2. 其脚本框中输入：prev.setDataEncoding(“UTF-8”);

**Comment by 2lipan** [comment]
加上后，问题并没有解决
![image](https://user-images.githubusercontent.com/104960608/190573853-0821a68c-3827-4714-b516-74c560e4d9d7.png)

**Comment by 2lipan** [comment]
切换成 xml 格式也是一样。
![image](https://user-images.githubusercontent.com/104960608/190574280-f9e3a0df-ae88-484e-8fa7-6e1f75e0c870.png)

**Comment by youliyuan-fit2cloud** [comment]
Jmeter里面可以正常返回吗？我们也没有实际场景复现。
