### ISSUE TITLE
[BUG]项目设置模块中修改禅道的缺陷模板，每次进入后不做任何修改点保存。再次进入后页面下方新增字段的顺序就会随机发生变化。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#17895]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

项目设置模块中修改禅道的缺陷模板，每次进入后不做任何修改点保存。再次进入后页面下方新增字段的顺序就会随机发生变化。
<img width="960" alt="dea9373f156f3dfbc69d068e342e761" src="https://user-images.githubusercontent.com/83771182/190306526-961ca2c1-f902-48e5-b49e-e81fd78d53c1.png">
<img width="960" alt="ac53514ee0f499423ae73ef14c43d9e" src="https://user-images.githubusercontent.com/83771182/190306543-1c968d64-e942-479a-8c77-2d2e59cb6755.png">

### 重现步骤

每次进入禅道缺陷模板后不做任何修改点保存按钮，再次进入禅道缺陷模板。

### 期待的正确结果

再次进入禅道缺陷模板信息不应该发生变化。

### 相关日志输出

```shell
无
```

**Comment by xulinde** [comment]
v2.2.0已修复～
