### ISSUE TITLE
[FEATURE] 希望等待控制器等待时间能够支持场景变量，可以较好的适应批量调整等待时间场景

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#17891]
### MeterSphere 版本

v1.20.14-lts

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/82088551/190290449-2ef7d1e4-8604-44f5-bd68-34206fe03f80.png)

1、等待控制器设置时间位置处能够支持 场景变量 引用   满足批量调整场景

**Comment by luty2018** [comment]
这里考虑到变量的值不可控会导致运行失败，所以暂时不支持呢。
