### ISSUE TITLE
[BUG]org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 97 !

### ISSUE THREAD

**Issue by viviandfcao** [metersphere/metersphere#17898]
### 联系方式

123420987@qq.com

### MeterSphere 版本

最新版本

### 使用外置数据库

否

### 问题描述

升级后导入备份数据后一直无法成功启动服务

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/9986048/190321680-a50c0b67-8b8d-4195-9cd4-39538fb39854.png">
![image](https://user-images.githubusercontent.com/9986048/190321724-9987c705-a8ea-4106-bb5e-0e2fa7ebcc35.png)

### 重现步骤

1. 离线下载最新的包
2. 备份数据库
3. 安装后发现服务一直起不来，因为忽略数据库的大小写配置一直无法生效
4. 只好将data目录删除后，重新安装
5. 导入备份数据
6. 重启服务，就出现了以上的异常

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题是安装过程中有些sql执行失败了，可以尝试再次安装一次，大概率会解决该问题。
