### ISSUE TITLE
性能测试权重分配运行机制策略问题和优化[FEATURE]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#17890]
### MeterSphere 版本

v1.20-14-lts

### 请描述您的需求或者改进建议

背景：总共74台nc组成了一个超大压测池，9台ds+kafka。
场景：一个性能测试里面放入了40个线程组，选择了74台nc组成的资源池。每个线程组在资源池里面选择不同几台机器使用，剩余其他都是0权重。

现在的问题是，MeterSphere即使设置了权重为0的机器，但是在实际运行中，还是会在权重为0的机器上启动一个Jmeter（虽然没有并发，但是还是会启动下空跑）。所以导致的问题是每次上述场景在压测过程中，每台nc上都启动了大量的无用Jmeter，这样导致nc机器的性能急剧下降，调度的速度也很慢。

### 请描述你建议的实现方案

1.性能测试设置权重为0的nc节点，不应该运行空的Jmeter，而是在测试任务下发时，只下发到权重不为0的nc上。
2.在测试资源部分，应该支持针对有问题的nc单独显示。（目前74台nc组成的资源池，如果其中有一台nc有问题，导致整体测试都无法使用，必须要后台查日志，然后在人工修复或者剔除）

**Comment by zhangzhaox** [comment]
这是要上多少哦  74台超大资源池
1、针对你目前问题可以采用分解的思路 分成几个线程池和场景脚本  运行时同步启动多个场景并行运行，相对负载压力应该和放在一起时一样的   同时可规避达到了个别有问题 影响全局
2、node节点同时存在组成不同规模的资源池，避免小并发 选择大资源池的尬尴
