### ISSUE TITLE
[BUG]复制接口自动化场景，新的场景的创建人为空

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#17897]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.14-lts

### 使用外置数据库

否

### 问题描述

复制接口自动化场景，新的场景的创建人为空

### 重现步骤

1.复制某个场景，并且保存
2.新的场景创建人是空的
![image](https://user-images.githubusercontent.com/88763608/190309779-14240b1a-2f7f-48a1-9925-228d30a4a9f7.png)

### 期待的正确结果

复制的用例，创建人应该是复制的操作人，功能用例就是这样的

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
