### ISSUE TITLE
[FEATURE]希望优化切换项目的下拉框

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#17892]
### MeterSphere 版本

1.20.5

### 请描述您的需求或者改进建议

当前平台项目切换的下拉框较为短小，公司项目名称比较长，展示不全，为项目切换带来困难

### 请描述你建议的实现方案

建议增大下拉框大小

### 附加信息

![aca31c0c7316930596d35f8f2bd7af5](https://user-images.githubusercontent.com/22739229/190300771-7d9b3168-09cc-47c2-a7d9-4d7b4bdc23df.jpg)

**Comment by luty2018** [comment]
请问你这个项目名称是多少个字的？我们测试看看

**Comment by GITMrzk** [comment]
一般在20-30字左右

**Comment by luty2018** [comment]
这个已经在我们新的交互中进行优化了。 预计会在12月底的版本上线
