### ISSUE TITLE
[BUG]定时任务开关关闭后保存不生效

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#17903]
### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

定时任务开关关闭后保存不生效

### 重现步骤

1、点击性能测试->测试->选择测试名称"test"
2、点击定时任务进入定时任务配置窗口
3、关闭定时任务开关，点击保存

### 期待的正确结果

期望结果：
定时任务关闭成功
实际结果：
提示保存成功，实际定时任务仍然是开启状态

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/190351710-d6d4ae34-5793-485e-ba28-27f7a1472b24.png)
![image](https://user-images.githubusercontent.com/5198427/190351798-58465e2b-b69f-42cf-9008-9bc51fe0610e.png)

**Comment by xulinde** [comment]
v1.20.14-lts未复现该问题，建议您升级到最新版本～

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
