### ISSUE TITLE
[BUG]定时任务配置页关闭定时任务后刷新页面定时任务变成开启状态

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#17904]
### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

定时任务配置页关闭定时任务后刷新页面定时任务变成开启状态

### 重现步骤

1、点击性能测试->测试->选择测试名称"test"
2、点击定时任务进入定时任务配置窗口
3、关闭定时任务开关，不点击保存，直接关闭窗口（此时定时任务显示关闭状态）
4、刷新浏览器 或则 切换到其他菜单在切换回来（点击其他菜单在执行步骤1跳回来）

### 期待的正确结果

期望结果：
定时任务关闭状态切换到其他菜单在跳转回来状态保持不变
实际结果：
按照操作步骤中执行后定时任务开关状态不正确

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/190353814-10c1e986-3b74-49c1-8c27-622274bfb693.png)
刷新浏览器 or 切换其他菜单在切回来 ，定时任务开关从关闭状态变成开启状态
![image](https://user-images.githubusercontent.com/5198427/190354070-2523fa43-ed14-486d-9c18-cffdca4fdf53.png)

**Comment by xulinde** [comment]
修改完状态需要点击保存才会生效～
