### ISSUE TITLE
[BUG]测试跟踪--首页，未评审“数量”，覆盖“数量”，“点击”跳转到对应页面，用例数量不一致

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17910]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

2.1.1

### 使用外置数据库

否

### 问题描述

测试跟踪--首页，未评审“数量”，覆盖“数量”，“点击”跳转到对应页面，用例数量不一致

### 重现步骤

测试跟踪--首页，
1. “点击”为评审数量，未评审数量：15，到了“功能用例页面”，数量展示为16条，评审数量为1，跳转到“功能用例”页面，也是16条。
2. “点击”覆盖率“数量”和未覆盖“数量”，跳转到功能用例，数量都不一致

### 期待的正确结果

测试跟踪--首页，评审“数量”：15
![image](https://user-images.githubusercontent.com/15188833/190358994-5df26e1a-2e72-4b10-b018-7d9662f945f7.png)

功能用例数量：16
![image](https://user-images.githubusercontent.com/15188833/190359099-524c6a10-cc25-4859-9af0-ef8d39342f99.png)

**Comment by xulinde** [comment]
v2.2.0已修复～
