### ISSUE TITLE
接口断言脚本语言没有js[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1791]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.0
**Bug 描述**
简要描述您碰到的问题
接口断言脚本语言没有js
**Bug 重现步骤**
1.  进入接口测试的接口定义模块
2. 选择一个接口进行配置断言
3. 断言类型选择脚本
4. 语言选择js，发现并没有js语言

**期待的正确结果**
正确情况下应该是什么样的？
有js
![image](https://user-images.githubusercontent.com/80814232/113239527-7dbe8e00-92dd-11eb-8c0b-4932fce983c3.png)
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最下面两种都是js脚本，1.8版本对js脚本进行了细分
