### ISSUE TITLE
[BUG] UI自动化，元素断言中的元素不存在断言，实际使用下来元素确实不存在，但是断言失败了。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17915]
### 联系方式

王进

### MeterSphere 版本

 v2.1.1

### 使用外置数据库

否

### 问题描述

UI自动化，元素断言中的元素不存在断言，实际使用下来元素确实不存在，但是断言失败了。

### 重现步骤

1. 新建一个UI自动化场景
2. 添加若干步骤
3. 添加断言，元素断言，选择元素不存在。--实测下来元素确实不存在，断言应该是PASS，但是 实际结果断言为Failed

![e45b1a11964c7499bb374c9bbcd1fb8](https://user-images.githubusercontent.com/76033005/190389761-a75153b2-db42-48f6-8bd2-508ea2384fda.jpg)

**Comment by zrfit** [comment]
v2.2.0版本已修复。
