### ISSUE TITLE
[BUG]项目自定义ID开启，但是导入的时候没有显示自定义ID,显示的是系统默认的ID。

### ISSUE THREAD

**Issue by 327282227** [metersphere/metersphere#17928]
### MeterSphere 版本

 v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

这个自定义ID没升级之前可以正常显示，升级后只能显示系统默认的，但是升序排列时又是按照自定义的ID来排序，导致这里有问题，
![a4604a23c0f980adcc8e3482d9df6bf](https://user-images.githubusercontent.com/113670658/190589962-39adc59e-9a27-4918-a296-7e4c826951dd.jpg)

### 重现步骤

1.开启自定义ID
2.导入自定义ID的用例

**Comment by youliyuan-fit2cloud** [comment]
v2.2.0中已优化。
