### ISSUE TITLE
[BUG]性能测试中使用python脚本报错  Cannot find engine named: 'python'

### ISSUE THREAD

**Issue by chaoshui66** [metersphere/metersphere#1792]
**MeterSphere 版本**
1.8.1
**Bug 描述**
性能测试中使用python脚本报错
**Bug 重现步骤**
1.  在接口自动化-场景列表 中添加自定义脚本 使用python语言
2. 场景创建性能测试
3. 性能测试中脚本执行失败 , 日志提示 Cannot find engine named: 'python', ensure you set language field in JSR223 Test Element

**截图**
python脚本如下
![image](https://user-images.githubusercontent.com/29295507/113239747-f1f93180-92dd-11eb-9ba1-679081f00699.png)

**完整日志**
完整日志
[jmeter (1).log](https://github.com/metersphere/metersphere/files/6240786/jmeter.1.log)

**Comment by liuruibin** [comment]
性能测试的镜像中缺少jython相关的jar，我们会在新的镜像中加入，现在也可以编辑性能测试手动上传jar
