### ISSUE TITLE
[BUG]JIRA-默认模版里自定义字段-经办人和报告人，点击同步缺陷后，经办人和报告人没有显示名字，而是JIRAUSER编号。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17922]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

1.20.10-lts

### 使用外置数据库

否

### 问题描述

JIRA-默认模版里自定义字段-经办人和报告人，API字段为F12抓取的key名(assignee和reporter)，点击同步缺陷后，经办人和报告人显示的不是jira上的名字，而是JIRAUSER编号。

### 重现步骤

1.在jira页面，f12抓取经办人和报告人的key，为assignee和reporter
2.在JIRA-默认模版里自定义字段-经办人和报告人
![image](https://user-images.githubusercontent.com/104960608/190551281-fca42d7d-3fd4-49f1-80c9-7ecdc24293fd.png)

![image](https://user-images.githubusercontent.com/104960608/190551332-ed524923-a217-412a-8590-586efef875d6.png)
3.点击同步缺陷，可看到经办人和报告人显示的是JIRAUSER编号。
![image](https://user-images.githubusercontent.com/104960608/190546042-18c8ee32-16c7-4cfe-8b2b-92d6d40f4c32.png)

**Comment by xulinde** [comment]
检查下字段的id是不是填错了
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/64065190/190602421-c41f2350-7c7b-4c39-8fc6-1da2d63bbe2a.png">
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/64065190/190602988-6ab3285f-65d4-4064-aaa9-367785af849f.png">
