### ISSUE TITLE
[BUG]后置脚本无法转义

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#17929]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

1.20.11

### 使用外置数据库

是

### 问题描述

apiId.split("\\|")报错，Sourced file: inline evaluation of: ``import java.lang.String; import java.lang.Integer; import cn.hutool.core.codec.B . . . '' Token Parsing Error: Lexical error at line 27, column 30.  Encountered: "|" (124), after : "\"\\": <at unknown location>
 in <unknown file>
问题原因：\\应该解析成了文件路径

### 重现步骤

a.split("\\|")

**Comment by xulinde** [comment]
jmeter也是这样，暂不支持～
