### ISSUE TITLE
[BUG]目前企业版和禅道集成后，在ms或禅道提交的缺陷不能做到实时双向同步，系统需要等到每天晚上才能同步，缺陷数据量大时点击手动同步按钮又非常缓慢，影响工作效率

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#17933]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

目前企业版和禅道集成后，在ms或禅道提交缺陷后不能做到实时双向同步，系统需要等到每天晚上才能同步，缺陷数据量大时点击手动同步按钮又非常缓慢，每次同步要很久影响工作效率。
建议增加缺陷实时双向自动同步功能，或者可以设置同步间隔时间周期，如每隔一个小时同步一次。
在执行手动同步时，能否做到增量同步，加快同步的效率。

### 重现步骤

在ms或禅道提交缺陷后不能做到实时双向同步，缺陷数据量大时点击手动同步按钮又非常缓慢

**Comment by luty2018** [comment]
需求提到战区，找凯波排期
