### ISSUE TITLE
[BUG]用例管理-用例树添加子模块，在第九层时添加报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#17935]
### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

用例管理-用例树添加子模块，在第九层时添加报错

### 重现步骤

用例树添加子模块先加八级，在第九层时添加报错

### 期待的正确结果

正常添加

### 附加信息

<img width="848" alt="Snipaste_2022-09-16_16-15-11" src="https://user-images.githubusercontent.com/43202800/190611594-c8074f3c-e689-4a32-bd33-d5f49417c07b.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，我们目前只支持最多八层模块。
