### ISSUE TITLE
[BUG]测试跟踪--功能用例，用例管理接口失败

### ISSUE THREAD

**Issue by startpjx** [metersphere/metersphere#17934]
### 联系方式

1253403984@qq.com

### MeterSphere 版本

1.20.14

### 使用外置数据库

是

### 问题描述

测试跟踪--功能用例，用例关联“接口用例”报错

### 重现步骤

截图展示：
![image](https://user-images.githubusercontent.com/15188833/190606613-a1e09508-b8d7-45de-9a76-9da6d8366456.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
