### ISSUE TITLE
[BUG]【JIRA-默认模版】中自定义模板字段，新增缺陷时，页面提示报错。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#17932]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

在【JIRA-默认模版】中新增  经办人 和 报告人 两个字段，缺陷管理-新增缺陷，经办人 和 报告人 不填写，只填写 标题和缺陷内容，点击确定，页面会报错，删除【JIRA-默认模版】新增的字段后，再创建缺陷，仍然报错。

### 重现步骤

1.在【模板字段】处创建两个字段，分别为  经办人 和 报告人
![image](https://user-images.githubusercontent.com/104960608/190596447-83cd3f3b-eb58-42ec-a765-fdcded91a346.png)

2.在【JIRA-默认模版】中新增这两个字段
![image](https://user-images.githubusercontent.com/104960608/190597144-54e0e83f-6481-405a-b226-64552dd6d3c5.png)

3.在项目中，缺陷选择【JIRA-默认模版】
![image](https://user-images.githubusercontent.com/104960608/190597210-bb7d0f6d-776c-4240-88e9-bbbab2aaaf7f.png)

4.新增缺陷，经办人 和 报告人 不填写，只填写 标题和缺陷内容，点击确定，页面会报错
![image](https://user-images.githubusercontent.com/104960608/190597561-0a3dbd69-381e-4dd7-aeb6-b3aaf630de76.png)

5.在【JIRA-默认模版】中将新增的字段删除后，再创建缺陷，页面还是报错。
![image](https://user-images.githubusercontent.com/104960608/190598118-35b1789b-b12b-4aab-ae29-d9141ed2c731.png)

**Comment by xulinde** [comment]
经办人/报告人的类型是是单选下拉列表，不是输入框，类型和属性值都写错了，创建缺陷肯定会报错哦～

**Comment by 2lipan** [comment]
可是我并没有绑定啊，这也得与jira上的类型一致吗？
