### ISSUE TITLE
等待控制器的使用

### ISSUE THREAD

**Issue by windy0122** [metersphere/metersphere#17953]
### 请描述您的问题

为什么场景里面设置了等待控制器未5秒，不是控制一个接口，而是每个接口都等待了5秒才执行，，无法将控制器拖入到接口下一层，，也无法将接口拖入到等待控制器下一层，，其他条件控制器，循环控制器中也无法添加等待控制器，

版本： v1.20.12-lts-2297374a

**Comment by zhangzhaox** [comment]
这个不是问题，原生jmeter也是这样
作用于单个API 请在API的前置添加等待控制器

**Comment by windy0122** [comment]
感谢，，没发现前置还能增加等待控制器，，(*^▽^*)
