### ISSUE TITLE
[FEATURE] 测试用例的json-schema 是否可以 配置一些有默认值的字段不显示在页面上

### ISSUE THREAD

**Issue by lihulanxx** [metersphere/metersphere#17967]
### MeterSphere 版本

v1.20.13

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/21300619/190940349-eaa8f09d-4bc9-492f-aab9-54745a287042.png)

测试用例的json-schema 是否可以 配置一些有默认值的字段不显示在页面上

**Comment by luty2018** [comment]
请问是要解决什么问题呢？

**Comment by lihulanxx** [comment]
> 请问是要解决什么问题呢？
主要是我想测试的时候隐藏一些不需要修改的字段，看起来会清爽些。比如上面图里的method字段 我设置了一个默认值，然后就可以隐藏这一行。

**Comment by luty2018** [comment]
这个我们不支持呢
