### ISSUE TITLE
[BUG]接口API点击"保存"-"一键同步"功能导致接口case参数无法新增和覆盖

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#17980]
### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

1.接口API需新增了一个参数，参数值只填写了参数名，未写参数值，勾选了"删除用例中无法与API文档对应的参数"后点击"确定"，导致所有对应的case的参数值均为空。
2.重新将接口case补充完相应参数值后，再次新增接口API参数，去掉"删除用例中无法与API文档对应的参数"，点击保存后，由于接口case对应的参数值与接口API参数中值不一致时，会自动在接口case增加参数值为空的同名参数。
新增参数"b"：
<img width="1073" alt="截屏2022-09-19 下午1 42 30" src="https://user-images.githubusercontent.com/34637801/190955783-2c5ac6f0-b41f-4c45-b99c-9c1432f7ad86.png">
接口case的"a"参数：
<img width="1434" alt="截屏2022-09-19 下午1 44 21" src="https://user-images.githubusercontent.com/34637801/190955945-e2d6c732-295c-456b-88dd-c70b67c82241.png">
点击接口API"保存"后接口case参数：
<img width="1438" alt="截屏2022-09-19 下午1 45 07" src="https://user-images.githubusercontent.com/34637801/190956016-2e8c9ac4-bf1f-44c2-a471-a79235b79634.png">

补充接口case参数后：
<img width="1433" alt="截屏2022-09-19 下午1 45 59" src="https://user-images.githubusercontent.com/34637801/190956107-93785b52-bf4c-4626-80cd-23fa56bf030c.png">
修改API接口参数后：
<img width="1083" alt="截屏2022-09-19 下午1 46 22" src="https://user-images.githubusercontent.com/34637801/190956154-0f6f4f9e-2697-4b12-a416-6888a00c9906.png">
去掉"删除用例中无法与API文档对应的参数"，点击"保存"后接口case参数
<img width="715" alt="截屏2022-09-19 下午1 47 19" src="https://user-images.githubusercontent.com/34637801/190956245-7049862c-46cf-49f1-ae67-9a445188a77a.png">
<img width="1420" alt="截屏2022-09-19 下午1 47 58" src="https://user-images.githubusercontent.com/34637801/190956296-47f12e7e-a499-4379-97ed-b43d782cf9d6.png">

### 重现步骤

步骤一：
1.在metersphere v2.1.1-96b84b46环境中准备一个API，并创建多个接口case，并填写相关请求参数和值
2.在API中新增一个参数，点击"保存"，使用默认设置点击"确定"
步骤二：
1.补充相关接口case参数值后
2.在接口API页面点击"保存"，去掉"删除用例中无法与API文档对应的参数"选项后，点击"保存"

### 期待的正确结果

能正常同步接口API新增参数

**Comment by zyyfit** [comment]
步骤一没有问题，如果勾选了同步所有参数、也勾了"删除用例中无法与API文档对应的参数"，接口case的参数就会跟接口定义完全一样

步骤二是个bug，我们修改一下

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后测试
