### ISSUE TITLE
[BUG] 测试跟踪，报告，接口用例统计分析，点击报告名称链接会直接跳转到接口用例或者场景用例详情页，需要改成点击链接后新打开一个新tab页

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#17993]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud,2.1

### 使用外置数据库

否

### 问题描述

测试跟踪，报告，接口用例统计分析，点击报告名称链接会直接跳转到接口用例或者场景用例详情页，需要改成点击链接后新打开一个新tab页

### 重现步骤

1. 点击测试跟踪
2. 点击报告
3. 查看报告里的接口用例分析
4. 在所有用例页面，打开一个场景自动化用例
5. 点击 场景名称链接，整个页面会跳转到 接口自动化场景。
6. 用户迫切需要 改成 ，点击链接后，打开新的tab，或者浏览器页，这样用户排查完问题后可以很快切回到报告。

<img width="1243" alt="1663569258043" src="https://user-images.githubusercontent.com/76033005/190961419-730850b3-48b1-42bb-a175-c0645c41177d.png">

### 期待的正确结果

9月，已经有3个企业用户跟我反馈这个事情，我内部tapd之前提了，客户追的紧，今天又催了，今天提bug，希望产品和开发，能尽快调整一下。
这个点是用户几乎每天都会碰到的点。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，会优化一下这里。

**Comment by youliyuan-fit2cloud** [comment]
v2.2.0中已优化。
