### ISSUE TITLE
[FEATURE] LDAP支持

### ISSUE THREAD

**Issue by wjangelking** [metersphere/metersphere#18]
**请描述您的需求或者改进建议.**

目前不支持LDAP

**请描述你建议的实现方案**

建议支持LDAP

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 目前不支持LDAP
> 
> **请描述你建议的实现方案**
> 
> 建议支持LDAP

1.1版本 7月底 会上LDAP，请持续关注！

**Comment by luty2018** [comment]
1.1版本已支持
