### ISSUE TITLE
[BUG]当dubbo Registry Center中的address填写不正确时后台会无限重连 

### ISSUE THREAD

**Issue by MadelS-F** [metersphere/metersphere#180]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.1.0
**Bug 描述**
简要描述您碰到的问题
接口测试->dubbo->Registry Center->address地址填写错误,后台会不停的重连
**Bug 重现步骤**
1.  在接口测试中选择dubbo
2. 在dubbo的Registry Center中的Protocol选择zookeeper
3. 在dubbo的Registry Center中Address里填入一个有效的ip地址及端口，但不是zookeeper的
4. 点击dubbo的Interface的get provider list

**期待的正确结果**
正确情况下应该是什么样的？
后台应该仅报错，不会无限尝试重连。
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54617021/88878261-1a65f300-d25a-11ea-94d8-76f081beb4b3.png)

**Comment by q4speed** [comment]
@wangzhen-fit2cloud 已修复，等待测试。
