### ISSUE TITLE
[BUG]接口定义的一个登录post请求，在test过程中显示为get 导致请求失败

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18005]
### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

接口定义的一个登录post请求，在test过程中显示为get 导致请求失败，见截图

### 重现步骤

接口定义的一个登录post请求，在test过程中显示为get 导致请求失败

### 期待的正确结果

展示为post请求

### 附加信息

![b92bc0bacd4c5d3cf8b0f8483a1a6df](https://user-images.githubusercontent.com/43202800/190975347-93dbd957-cdbf-43f6-8b8d-45b9cde373ed.jpg)

**Comment by xhy12** [comment]
该环境为全新部署的一个环境

**Comment by xulinde** [comment]
未复现该问题，运行环境换一个试试呢

**Comment by zhaohong111** [comment]
我这边也复现了两次，每次都是第二天或者过两天自己就好了
