### ISSUE TITLE
[BUG]打开的标签页无论路径输入的什么，最后都会跳转到个人信息界面

### ISSUE THREAD

**Issue by xiaozhao441** [metersphere/metersphere#18019]
### MeterSphere 版本

版本:   v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

之前的版本没有这个问题，最新的版本新打开的标签页无论路径输入的什么，最后都会跳转到个人信息界面，类似输入http://IP:8081/#/api/home

### 重现步骤

![image](https://user-images.githubusercontent.com/106516776/190995686-77ac0dbb-e49e-451f-a0d8-456c2a43ec49.png)
![image](https://user-images.githubusercontent.com/106516776/190995817-60d3c662-db16-4fc6-a286-6e9f08accb70.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该问题下个版本修复。

**Comment by xiaozhao441** [comment]
OK

**Comment by weishuo6** [comment]
v2.2.0版本尝试了下，问题依然存在

**Comment by youliyuan-fit2cloud** [comment]
> v2.2.0版本尝试了下，问题依然存在

2.2还没发布呢
