### ISSUE TITLE
[BUG]V2.0.1版本用例导出成xmind，用例步骤不展示，问题严重加个急

### ISSUE THREAD

**Issue by li824167627** [metersphere/metersphere#18015]
### 联系方式

824167627@qq.com

### MeterSphere 版本

V2.0.1

### 使用外置数据库

否

### 问题描述

用例列表创建测试用例，用例里面什么内容都有，前置条件、步骤、预期结果，然后导出成xmind后不显示用例里的任何具体内容包括不限于不显示步骤、预期结果等，导出成表格就不存在这个问题

### 重现步骤

创建用例，写上步骤、预期结果、前置条件等，导出用例成Xmind

### 期待的正确结果

导出的xmind的用例信息是完整的

**Comment by xulinde** [comment]
v2.1已修复～
