### ISSUE TITLE
[BUG]新建一个接口自动化场景，输入名称，然后引用一个场景，被引用场景里有自定义脚本，在未保存的情况下，选择环境，点调试，被引用场景自定义脚本不会被执行。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18028]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud

### 使用外置数据库

否

### 问题描述

新建一个接口自动化场景，输入名称，然后引用一个场景，被引用场景里有自定义脚本，在未保存的情况下，选择环境，点调试，被引用场景自定义脚本不会被执行。

### 重现步骤

1. 新建一个接口自动化场景
2. 输入场景名称
3. 然后引用一个调试好的场景，被引用场景里有自定义脚本，
4. 在未保存的情况下，选择环境，点调试，被引用场景自定义脚本不会被执行。
5. 这个问题是客户发现的，我今天复测了一遍，确实有。

### 期待的正确结果

新建的接口用例现在是不保存，无法触发执行。 
可不可以把场景自动化也做类似功能，未保存的接口自动化场景 用户点【调试】时，提示用户先保存 然后再执行。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
