### ISSUE TITLE
批量执行"接口自动化"中的场景，执行完成后，测试报告中输出的报告一直Running中

### ISSUE THREAD

**Issue by 377577118** [metersphere/metersphere#1804]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
批量执行"接口自动化"中的场景，执行完成后，测试报告中输出的报告一直Running中

**Bug 重现步骤**
1.  选择"接口测试"
2. 进入"接口自动化"界面
3. 在"场景列表"中批量选择100+场景测试用例
4. 选择"批量执行"
5. 执行完成后，进入"测试报告"界面查看输出的测试结果

**期待的正确结果**
"测试报告"界面显示执行后测试的结果

**实际结果**
测试报告中输出的报告一直出在Running中

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/59471334/113274951-d3f8f480-9310-11eb-8a0a-303a6cfc37a9.png)

**Comment by zyyfit** [comment]
您好，请问您使用的是哪个版本呀，这边没有复现呢，可以多等一会看看

**Comment by 377577118** [comment]
我这边用的是1.8.0版本的，这些用例之前都是执行OK的


看了某一个失败的请求，发现url参数缺失










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 批量执行"接口自动化"中的场景，执行完成后，测试报告中输出的报告一直Running中 (#1804)





 
您好，请问您使用的是哪个版本呀，这边没有复现呢，可以多等一会看看

**Comment by zyyfit** [comment]
好的，我们这边复现一下试试

**Comment by xulinde** [comment]
v1.10.2版本已修复
