### ISSUE TITLE
[BUG]服务集成之对接禅道Bug，关联禅道项目提示 “ ID不存在或其它错误”

### ISSUE THREAD

**Issue by weiguoyi** [metersphere/metersphere#18043]
### 联系方式

MeterSphere交流群46

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

如标题所述，使用MeterSpere版本v2.1.1，禅道版本开源版17.5。
禅道对应设置添加更改如下：
$config->features->apiGetModel    = true;
请求方式设置requestType = 'PATH_INFO'
![image](https://user-images.githubusercontent.com/16778692/191019230-489928aa-bf52-45ad-9061-63a5054c8e27.png)
![image](https://user-images.githubusercontent.com/16778692/191019459-b2b05d9a-d66d-4382-8d60-680b733cea2b.png)

根据对应的禅道流程项目设置，产品ID，如图所示
![image](https://user-images.githubusercontent.com/16778692/191019339-dc5f62d7-97a5-44a8-a9e7-c9ff90a15297.png)

### 重现步骤

如问题描述，每次都会提示该信息

**Comment by weiguoyi** [comment]
请问有计划什么时候对接吗？

**Comment by youliyuan-fit2cloud** [comment]
> 请问有计划什么时候对接吗？
有计划，但是时间现在还不确定，请关注后续更新的版本计划。
