### ISSUE TITLE
[BUG]【测试跟踪>>功能用例】选择用例，导出 用例为Excel格式。导出的用例在导入到MS其他项目中，提示无法导入。原因：导出文件中

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18051]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

条件：项目A和项目B：项目成员一样。

操作：
1、项目A：【测试跟踪>>功能用例】选择用例，选择【导出】 用例为Excel格式。
2、项目B：【测试跟踪>>功能用例】选择【导入】 项目A导出的用例Excel文件。
3、结果： 提示无法导入。原因：责任人ID不存在。

原因：用例导出文件中，责任人为名称非ID号。

### 重现步骤

条件：项目A和项目B：项目成员一样。

操作：
1、项目A：【测试跟踪>>功能用例】选择用例，选择【导出】 用例为Excel格式。
2、项目B：【测试跟踪>>功能用例】选择【导入】 项目A导出的用例Excel文件。
3、结果： 提示无法导入。原因：责任人ID不存在。

原因：用例导出文件中，责任人为名称非ID号。

### 附加信息

1、导出测试用例
![image](https://user-images.githubusercontent.com/78218624/191039230-dc3828c3-0b89-4146-ab62-45ddb6673b27.png)

2、导出的测试用例Excel 内容
![Uploading 导出用例.png…]()
![image](https://user-images.githubusercontent.com/78218624/191041088-91c259cd-f013-45d5-b6cb-e8cadf87c132.png)

**Comment by xulinde** [comment]
v2.1.1已修复～
