### ISSUE TITLE
[BUG]【测试跟踪>>用例评审】评审结果先添加图片，然后再填写评审意见；最后点击保存。 评审信息中只能看到图片，没有评审信息

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18052]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]【测试跟踪>>用例评审】评审结果先添加图片，然后再填写评审意见；最后点击保存。 评审信息中只能看到图片，没有评审信息
但是如果先发表意见，在上传图片，保存后，就可以显示意见和图片。反之就不行。

### 重现步骤

[BUG]【测试跟踪>>用例评审】评审结果先添加图片，然后再填写评审意见；最后点击保存。 评审信息中只能看到图片，没有评审信息
但是如果先发表意见，在上传图片，保存后，就可以显示意见和图片。反之就不行。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/191044442-9c2156eb-7cfe-434a-ae48-896b2b8787ae.png)

![image](https://user-images.githubusercontent.com/78218624/191045039-7776aecb-75e8-4381-8a82-53286cb587b9.png)

**Comment by xulinde** [comment]
v2.2已修复～
