### ISSUE TITLE
[BUG] 测试计划无法关联无CASE的API （实际上测试计划不应该允许关联API定义）

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#18062]
### MeterSphere 版本

2.1.1

### 使用外置数据库

否

### 问题描述

现状： 当测试计划关联API时，只能关联有CASE的API，无法关联无CASE的API
既然允许关联API，就不应该跟是否有CASE相关。

但实际上，测试计划不应该允许关联API定义，原因：
 1.  测试计划中的关联实际上是“引用”，关联后无法设置或调整请求参数
 2. API实际上是接口定义，本身不带有请求参数值

### 重现步骤

1. 创建接口定义
![image](https://user-images.githubusercontent.com/24548477/191156130-0bc1b524-2462-48c5-808f-400759337cce.png)

2. 无法关联新创建的API接口
![image](https://user-images.githubusercontent.com/24548477/191156485-47f42f7a-45eb-4db3-ac24-e8e76005e412.png)

3. 如果基于API创建一条CASE
![image](https://user-images.githubusercontent.com/24548477/191156646-ed182cba-8648-4a0a-a183-1ca1e883e865.png)

4.则可以关联
![image](https://user-images.githubusercontent.com/24548477/191156801-de88b926-e6d0-476c-87cf-e08fc029ce10.png)

### 期待的正确结果

测试计划不应该允许关联API定义

**Comment by luty2018** [comment]
我们的设计确实测试计划是不允许关联api，原因正如你描述的那样。在这里展示api的列表只是方便用户更快筛选，因为一个api可能有几十个case，选中api则直接关联api的所有case，可能这里需要增加一个提醒告知用户选择api实际添加的api的case。

**Comment by luty2018** [comment]
我们的设计确实测试计划是不允许关联api，原因正如你描述的那样。在这里展示api的列表只是方便用户更快筛选，因为一个api可能有几十个case，选中api则直接关联api的所有case，可能这里需要增加一个提醒告知用户选择api实际添加的api的case。

**Comment by xyziven** [comment]
嗯，提示或交互得改一下：只是按API的方式进行分组过滤出CASE而已，而且当选择API后，是API所有的CASE都会关联。

![image](https://user-images.githubusercontent.com/24548477/191310244-3a2b06b8-a932-423f-86e0-edb533f02887.png)
