### ISSUE TITLE
[BUG]测试计划关联单接口用例，批量执行时获取不到请求地址

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#1806]
**MeterSphere 版本**
1.8.1

**Bug 描述**
测试计划关联单接口用例，多选，批量执行，报错，获取不到URI

**Bug 重现步骤**
1.  测试计划关联单接口用例
2. 多选，批量执行

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40782672/113278386-736bb680-9314-11eb-8ae0-ee7370277cfa.png)

**Comment by zyyfit** [comment]
您好，这个问题将在1.8.2版本修复

**Comment by xulinde** [comment]
1.8.2已修复
