### ISSUE TITLE
[BUG] ms支持函数列表和函数联想未显示全

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18089]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

ms支持函数列表和函数联想未显示全

### 重现步骤

时间位移加减函数___timeShift联想没有
![image](https://user-images.githubusercontent.com/103925124/191194317-cde38b28-bd0e-4d8e-8c03-2cbb83d1725d.png)
小铅笔列表同样没有
![image](https://user-images.githubusercontent.com/103925124/191194472-a489c27c-b882-486f-9315-d0e7904d74cb.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zhangzhaox** [comment]
自定义的插件函数是否也可以在这个进行展示？
![image](https://user-images.githubusercontent.com/82088551/192224300-35bfdeb6-cadd-4967-b8ab-11c977dca8a4.png)

**Comment by zyyfit** [comment]
1.20.15 和 2.2.1已优化，请等待版本发布后使用
