### ISSUE TITLE
[BUG]  环境中设置全局变量为mock函数，引用变量，值错误为@string

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18104]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

环境中设置全局变量为mock函数，引用变量，值错误为@string

### 重现步骤

环境中设置变量
![image](https://user-images.githubusercontent.com/103925124/191240811-900e8f37-af27-4d70-b89c-05d58ca3d45c.png)
接口中引用
![image](https://user-images.githubusercontent.com/103925124/191240896-274509ef-3e4c-4848-938b-5c83fc5f61fc.png)

**Comment by zhangzhaox** [comment]
${__Mock(@string)}

**Comment by Ycr123888** [comment]
直接@string不支持是嘛

**Comment by zhangzhaox** [comment]
在API测试页面的form表单是生效的，目前应该是其他的地方都使用${__Mock(@string)}方式生效

mockjs函数直接生效肯定是需要前端支持的

**Comment by Ycr123888** [comment]
是这样的，mockjs函数在form表单之类的地方都可以直接引用，但是在环境变量里需要加${__Mock解析，用户是不知道的
并且jmeter函数可以直接引用的

建议给用户下提示，或者在环境mock函数页面加一下

**Comment by Ycr123888** [comment]
![image](https://user-images.githubusercontent.com/103925124/195547194-34d4cd47-c042-4673-b6d8-7ac1812d103b.png)
麻烦尽快拍下期，UI使用场景变量中带mock函数也是需要转一下哈

**Comment by youliyuan-fit2cloud** [comment]
经确认，你这个场景是在url 中，暂时不支持。
