### ISSUE TITLE
[QUESTION]"Specified key was too long" error

### ISSUE THREAD

**Issue by Sandu1213** [metersphere/metersphere#18129]
### **Environment**
Linux 16.04
MySQL 5.7.33

### reproducement
1.下载最新长期版安装包文件(metersphere-offline-installer-v1.20.14-lts)

2.进行安装后，ms-server反复重启，查看日志发现是“metersphere contains a failed migration to version 5”问题
![7393a2659502e77a85bc7ade5645029](https://user-images.githubusercontent.com/21214285/191420744-90eb491a-695f-40b5-a9e0-9e64b3794829.png)

3.参考[常见部署问题指南](https://metersphere.io/docs/v1.20.x-lts/faq/installation/#10)，提示要手动执行
![image](https://user-images.githubusercontent.com/21214285/191421218-c3b7d9af-cc8a-4314-85a9-eeb80ba6bac5.png)

4.手动执行脚本的时候又报“Specified key was too long"
![21b068e7bd37cdb617b58be95b58391](https://user-images.githubusercontent.com/21214285/191421694-69e74e0f-e2ad-47bd-a180-80ce4202031d.jpg)
![1ce81fddbbdfba8eed5d0a22c2bd6af](https://user-images.githubusercontent.com/21214285/191421720-074f50f8-5369-4d18-9bb6-9d630eeab130.jpg)

5.查询资料，怀疑是数据库不同版本字符集设置导致的问题，请帮忙看看
[【说明】](https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes)

**Comment by liuruibin** [comment]
检查 /opt/metersphere/conf/my.cnf

**Comment by Sandu1213** [comment]
检查后，已调整。问题解决。谢谢！
