### ISSUE TITLE
[BUG]   项目管理员或项目成员权限的用户不能编辑项目

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18132]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

项目管理员或项目成员权限的用户不能编辑项目

### 重现步骤

新建用户，给用户增加项目成员或项目管理员的权限
![image](https://user-images.githubusercontent.com/103925124/191434270-3f917716-48fe-44e4-8aec-d746ff3ec2f1.png)

查看项目成员或者项目管理员的权限，**_### 项目设置下不知道咋来的项目管理，但是确实有编辑项目的权限_**
![image](https://user-images.githubusercontent.com/103925124/191435225-548ae566-b1db-4ce2-84c4-9748c885c21f.png)

deng登录此用户，不能编辑项目
![image](https://user-images.githubusercontent.com/103925124/191434352-5cbecd5f-a649-4bd6-bcb1-c959769968d8.png)

必须给此用户增加工作空间管理员的权限此用户才能编辑项目

### 期待的正确结果

项目成员或项目管理员可编辑项目

**Comment by youliyuan-fit2cloud** [comment]
你好，这个不能编辑项目的页面是工作空间层面的操作，可以在项目设置-项目信息页面也编辑项目。
