### ISSUE TITLE
[BUG]接口自动化场景中引用的方式添加case，但是在场景里还能给引用的case添加前置、后置、断言，但是接口定义中该case不会同步，运行场景时case还是用的接口定义里的那一份

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#18133]
### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

接口自动化场景中**引用的方式添加case**，但是在场景里还能给引用的case添加前置、后置、断言，但是接口定义中该case不会同步添加，导致场景里该case和接口定义里的case变成了两个不一样的case，运行场景时case还是用的接口定义里的那一份，数据就混乱了

### 重现步骤

1、新建场景
2、用引用的方式添加case
3、在场景里对case进行修改，添加前后置和断言

### 期待的正确结果

要么在场景里对引用的case改了后能同步修改接口定义中的case，要么就是场景里不能对引用的case进行修改，否则两遍不同步会有问题

**Comment by zyyfit** [comment]
您好，设计就是这样的，引用的用例可以添加前后置操作，但是不会同步到接口用例中，只会在当前场景生效

另外， “运行场景时case还是用的接口定义里的那一份”，这个没有复现，保存后，运行场景，就会使用场景中显示的case
