### ISSUE TITLE
[BUG]MS idea插件，当同步的API有方法备注时，系统提示异常。去掉方法描述备注可正常同步

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18159]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]MS idea插件，当同步的API有方法备注时，系统提示异常。去掉方法描述备注可正常同步

条件：idea插件为最新插件。

### 重现步骤

[BUG]MS idea插件，当同步的API有方法备注时，系统提示异常。去掉方法描述备注可正常同步

条件：idea插件为最新插件。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/191479168-7d437fd9-86bb-46b8-9d18-d3301062063f.png)

![image](https://user-images.githubusercontent.com/78218624/191479251-dd350d51-e149-45dd-a4ef-af75a9bef437.png)

[idea同步错误信息.txt](https://github.com/metersphere/metersphere/files/9615636/idea.txt)

**Comment by youliyuan-fit2cloud** [comment]
新插件中已修复该问题，请下载新版本插件。
