### ISSUE TITLE
[FEATURE] 功能用例关联接口自动化场景，场景通过后对应的功能用例标记为通过

### ISSUE THREAD

**Issue by TesterPi** [metersphere/metersphere#18152]
### MeterSphere 版本

V1.20.14

### 请描述您的需求或者改进建议

接口自动化测试关注主流程的业务，期望有一个更直观的体现，场景接口自动化用例通过后，标记关联的对应功能用例为通过，这样看到相应的功能用例通过后，主流程可以认为是没有大问题的。

### 请描述你建议的实现方案

场景执行的状态关联对应绑定功能用例是否通过

**Comment by luty2018** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/36292514/192208204-04362fbd-fd01-4528-9ccd-27374aa55667.png">
在测试计划里面打开这个开关
