### ISSUE TITLE
[BUG]jira缺陷同步，sprint没有同步过来

### ISSUE THREAD

**Issue by xiaozhao441** [metersphere/metersphere#18155]
### 联系方式

17805241933

### MeterSphere 版本

版本:   v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

jira缺陷同步，sprint没有同步过来

### 重现步骤

![1663754307109](https://user-images.githubusercontent.com/106516776/191475458-978b8cda-fe27-4107-8341-f4f9f150a25e.jpg)

**Comment by xulinde** [comment]
未复现该问题，请检查下自定义字段类型和值是否和jira保持一致呢？
