### ISSUE TITLE
[BUG]  【UI测试模块】  元素库定义多个层级并且名字很长，在场景中选择元素对象，下拉框数据没有显示完整。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#18156]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts，v2.1.1

### 使用外置数据库

否

### 问题描述

<img width="966" alt="image" src="https://user-images.githubusercontent.com/33945037/191476458-4cb4f534-044d-4978-9149-343e476c4efe.png">

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/33945037/191476404-707ffb24-8ff8-4f64-b05e-c1fce40b3919.png">

### 重现步骤

如上
1. 元素库定义
2. 场景中引用

**Comment by zrfit** [comment]
您好，感谢您的反馈！问题已复现，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts和v2.5.1以上版本已修复该问题。
