### ISSUE TITLE
[BUG]【接口测试>>接口列表】api列表统计的总数和左侧模块统计的总数不一致。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18167]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]【接口测试>>接口列表】api列表统计的总数和左侧模块统计的总数不一致。

日常api操作：不同版本的接口导入新增、手动创建新增、也有移动等，但是没有删除。

使用一段时间后，发现这个项目下的接口统计：列表统计和左侧模块统计的api总数不一致。

### 重现步骤

[BUG]【接口测试>>接口列表】api列表统计的总数和左侧模块统计的总数不一致。

日常api操作：不同版本的接口导入新增、手动创建新增、也有移动等，但是没有删除。

使用一段时间后，发现这个项目下的接口统计：列表统计和左侧模块统计的api总数不一致。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/191517831-f0773482-5384-4f3a-b985-17bd58211a5a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
你好，后续发现是异常数据导致的，处理了的话会引起其他异常，经过考虑暂时不做处理。感谢理解。
