### ISSUE TITLE
[BUG] 接口用例执行响应内容过小，下面留了很大的空白区域，响应体过大时，需要拖动滚动条。

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18173]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.1.1-96b84b46/1.20.14-lts同现象

### 使用外置数据库

否

### 问题描述

接口用例执行响应内容过小，下面留了很大的空白区域，响应体过大时，需要拖动滚动条。

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/191644910-5d7079ee-206f-4c30-b992-0db9a104930c.png)
![image](https://user-images.githubusercontent.com/103925124/191645040-ef10c0e6-8228-4efa-b871-fabf8e9b19c2.png)

**Comment by xulinde** [comment]
v2.7已优化
