### ISSUE TITLE
[BUG]当场景步骤中步骤层级超过两层，第三层及之后的步骤结果将不会再测试报告中显示

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#18170]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.6

### 使用外置数据库

是

### 问题描述

如图所示，在一个循环控制器下，有一个条件控制器，条件 控制器下面的请求在调试或生成报告后相关的执行结果将不会在报告中显示：

![image](https://user-images.githubusercontent.com/31870788/191637510-86900681-6e31-4357-8d86-24b2c7605ae3.png)

![Uploading image.png…]()

### 重现步骤

如上所示的层级。

附加信息：当req2请求的断言结果为error时，如图：

查看执行报告，点击失败tag，发现里面也没有相关的信息：
![image](https://user-images.githubusercontent.com/31870788/191637895-d3d314d9-1153-454b-8a4d-5b5abc35a180.png)

**Comment by zyyfit** [comment]
1.20.14没有复现，建议升级
![image](https://user-images.githubusercontent.com/73461316/191713594-1918b299-5484-49e2-887d-9b07e4613ed9.png)
