### ISSUE TITLE
[BUG]创建版本设置为最新版，场景内新建版本关闭后创建人丢失

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#18185]
### 联系方式

1303647944@qq.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

1.创建版本设置为最新版
![image](https://user-images.githubusercontent.com/103627487/191651675-049941d2-0ad6-4753-9cb3-30a0f025ac7f.png)
2.场景内新建版本关闭后创建人丢失
![image](https://user-images.githubusercontent.com/103627487/191651822-f9ef6b8f-67d0-486e-8017-024254732a14.png)
![image](https://user-images.githubusercontent.com/103627487/191651889-9258609a-df4b-4626-ac90-fa8b1d467a9c.png)
![image](https://user-images.githubusercontent.com/103627487/191651941-f1f7d2f3-3ab9-47db-b8d7-dfb497b50066.png)

### 重现步骤

1.创建版本设置为最新版
2.场景内新建版本关闭后创建人丢失
![飞书20220922-112937](https://user-images.githubusercontent.com/103627487/191652112-d1ed81a9-be75-4766-b2e5-e61cb7fdd98d.gif)

### 期待的正确结果

修改版本后创建人正常显示

**Comment by xulinde** [comment]
按您提供的步骤无法复现该问题，方便把您的场景导出来吗？

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
