### ISSUE TITLE
[BUG]场景A中先添加场景B，再添加循环控制器并使用csv场景变量，运行场景A，每次循环不是逐行读取csv中数据，而是跳行读取

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#18189]
### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

场景A中先添加场景B，再添加循环控制器并使用csv场景变量，运行场景A，每次循环不是逐行读取csv中数据，而是跳行读取

### 重现步骤

1、新建场景A
2、场景A中添加场景B，在场景B的后面添加循环控制器，并使用csv场景变量，循环控制器中引用的方式添加case
3、运行场景A

_**原定定位：循环控制器前有其他别的场景，就会有跳行读取csv的这个问题**_

**Comment by zyyfit** [comment]
您好，循环控制在场景B内或者跟场景B同级都没有复现这个问题，方便把您的场景上传一下吗？可以将文件后缀改成txt传上来
![image](https://user-images.githubusercontent.com/73461316/191715373-c01871be-63ba-4e4a-843d-46e81baefe56.png)
![image](https://user-images.githubusercontent.com/73461316/191715457-681a9c89-3f13-4670-bbe0-1c55ba47ee72.png)

**Comment by minnn0306** [comment]
![image](https://user-images.githubusercontent.com/86464217/191931797-cb3a6d0f-eab9-4823-afb5-2c7caaae1726.png)
![image](https://user-images.githubusercontent.com/86464217/191931916-dd98da67-ce94-42dc-a42d-258dd74e5173.png)


**按这样操作必现这个问题**
![image](https://user-images.githubusercontent.com/86464217/191932129-184e7d52-30cb-4f44-9674-11613b8c112e.png)

**Comment by zyyfit** [comment]
这个是因为第一次的1，和后面一次循环里的6，被外层的先取了一次值，目前这个地方还无法修改，要等后期优化了
