### ISSUE TITLE
【功能用例】“脑图”模式下，新增用例，保存不上[BUG]

### ISSUE THREAD

**Issue by 404936800** [metersphere/metersphere#18186]
### 联系方式

15800007771

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

是

### 问题描述

【功能用例】“脑图”模式下，新增用例，保存不上。提示成功，一刷新，用例就没有了。

### 重现步骤

![image](https://user-images.githubusercontent.com/102789428/191652805-82566338-0d44-42c9-8ce9-1d8944dda81d.png)

![image](https://user-images.githubusercontent.com/102789428/191653471-253a3245-3087-46c5-9a60-926632b37b0b.png)

脑图 模式，添加用例，【保存】

### 期待的正确结果

脑图模式，用例新增成功。

**Comment by xulinde** [comment]
未复现该问题，建议您升级到v2.2.0版本

**Comment by 404936800** [comment]
还是不行，已升级2.2.0版本，依然不能脑图新增case。有没办法没？

**Comment by xulinde** [comment]
您好，请问您是这样操作的吗？
https://user-images.githubusercontent.com/64065190/192414455-1eab7c4c-b8c0-45ea-a57f-f79a07d72282.mov

**Comment by 404936800** [comment]
对，就是这么操作的。 2.01版本时，这功能好用，升级后就不行了。提示成功，实际没存上数据。

**Comment by xulinde** [comment]
我这复现不了，方便发个视频看下您的操作吗？

**Comment by 404936800** [comment]
详见下视频

https://user-images.githubusercontent.com/102789428/192674407-327621eb-93f1-4dcb-b219-4972679c01ed.mp4

**Comment by xulinde** [comment]
这个用户是啥权限的？

**Comment by 404936800** [comment]
admin、项目管理员、项目成员， 都试过，一样的不行。
我们是用helm部署的2.20版本
github上helm 最新版是 metersphere-2.0.1
我们是通过升级镜像的方式更新的，是否会有问题？

**Comment by xulinde** [comment]
这个应该跟部署方式没啥关系

**Comment by 404936800** [comment]
还需要我们提供什么信息，来排查解决这问题？

**Comment by youliyuan-fit2cloud** [comment]
> 还需要我们提供什么信息，来排查解决这问题？

windows电脑 的chrome浏览器？浏览器版本升级下 ？或者清缓存试试呢？

**Comment by zhaojiajun9** [comment]
我自己查看了一下数据，发现以下情况：

脑图创建的测试用例，在test_case表中的status字段是NULL

列表创建的测试用例，在test_case表中的status字段是'Prepare'

将脑图的测试用例的status字段update成Prepare后就能显示出来了

当前版本v2.2.0-b2

**Comment by zhaojiajun9** [comment]
test/case/minder/edit

**Comment by zhaojiajun9** [comment]
脑图保存时，test/case/minder/edit这个接口request body 中 status=null

![image](https://user-images.githubusercontent.com/114374234/194804547-42c327be-b689-43b6-925f-635e4310f1d2.png)

**Comment by 404936800** [comment]
> 

跟缓存没关系。我们这边所有人，都这现象。就没有好用的。

**Comment by zhaojiajun9** [comment]
> 

我这边也是升级后出现的这个问题

**Comment by youliyuan-fit2cloud** [comment]
> 脑图保存时，test/case/minder/edit这个接口request body 中 status=null
> 
> ![image](https://user-images.githubusercontent.com/114374234/194804547-42c327be-b689-43b6-925f-635e4310f1d2.png)

感谢反馈，后续版本会修复。

**Comment by 404936800** [comment]
怎么样了？修复没？

**Comment by xulinde** [comment]
10.27发布的版本会修复～

**Comment by xulinde** [comment]
v2.3.0已修复～

**Comment by 404936800** [comment]
后续会有2.3.0的helm chart 没？直接升级镜像 不行了。别的方式升级有点费事，不太好弄
