### ISSUE TITLE
[BUG]MS的前置脚本中无法使用第三方js文件

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#18194]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.10-lts

### 使用外置数据库

否

### 问题描述

前置脚本中使用第三方js文件不能正确使用，在jmeter工具上可以正常使用。

### 重现步骤

1.将第三方js上传到/opt/metersphere/data目录下
2.在接口的前后置脚本中写入js脚本，进行测试，控制台会报错
![image](https://user-images.githubusercontent.com/104960608/191673184-92724f17-43e4-4a1d-a9e1-38b03113619c.png)

3.将第三方脚本放到jmeter的bin目录下，同样的js脚本在jmeter上运行，正常通过。jmx脚本点击下载
![image](https://user-images.githubusercontent.com/104960608/191673410-02faefd3-afec-42df-841a-39ad19848687.png)

4.第三方js代码和ms的js脚本以及jmeter的jmx脚本可下载
[js文件.zip](https://github.com/metersphere/metersphere/files/9622874/js.zip)

**Comment by zyyfit** [comment]
你要这样用的话，不能传到data下面，要放在ms-server或者node-controller容器内的jmeter扩展文件夹下

**Comment by zyyfit** [comment]
您好，由于第三方js文件范围太大，支持起来比较困难，另外我们还有新版本的开发任务，所以暂时没有支持计划，后期可能会考虑支持
