### ISSUE TITLE
[BUG]多处模块时间显示不匹配

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#182]
版本：v1.1.0
![image](https://user-images.githubusercontent.com/43331464/88884496-52c0fd80-d269-11ea-903c-0039b00b78e4.png)
![image](https://user-images.githubusercontent.com/43331464/88884531-69675480-d269-11ea-81da-36aac0a5d6b3.png)
![image](https://user-images.githubusercontent.com/43331464/88884557-77b57080-d269-11ea-95e4-5897a41b4ccc.png)

系统所有地方都有，不止这些地方！

**Comment by 52testing** [comment]
建议获取更新同步为北京时间

**Comment by wangzhen-fit2cloud** [comment]
麻烦检查下你环境中部署服务器上的时区

**Comment by 52testing** [comment]
更新linux时间后，恢复正常。

**Comment by 52testing** [comment]
已解决；用户端用户设置问题
