### ISSUE TITLE
[BUG] 检查资源池节点上的 /etc/hosts 是否有 127.0.0.1 当前主机名 这条配置，请确保这个配置存在并删除报告重新执行

### ISSUE THREAD

**Issue by gsytzsh** [metersphere/metersphere#18201]
### MeterSphere 版本

helm  2.0.1

### 使用外置数据库

否

### 问题描述

k8s  性能测试出现如下错误
 检查资源池节点上的 /etc/hosts 是否有 127.0.0.1 `当前主机名` 这条配置，请确保这个配置存在并删除报告重新执行

### 重现步骤

 检查资源池节点上的 /etc/hosts 是否有 127.0.0.1 `当前主机名` 这条配置，请确保这个配置存在并删除报告重新执行

### 相关日志输出

```shell
2022-09-22 15:57:16,370  WARN thub.dockerjava.core.DockerClientBuilder:  96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.
```

**Comment by youliyuan-fit2cloud** [comment]
你好，k8s 不能使用nodecontroller 资源池。

**Comment by gsytzsh** [comment]
> 你好，k8s 不能使用nodecontroller 资源池。

那需要怎么配置呢

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，k8s 不能使用nodecontroller 资源池。
> 
> 那需要怎么配置呢

抱歉，目前还不支持。
