### ISSUE TITLE
[BUG]【接口测试>>API>>CASE】请求体json各种指定的数值型参数，切换到“”模式，有些数值型的参数属性，都被改为string类型。在切回json格式时，原来数值型的参数都被设置为了字符串

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18211]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]【接口测试>>API>>CASE】请求体json各种指定的数值型参数，切换到“”模式，有些数值型的参数属性，都被改为string类型。在切回json格式时，原来数值型的参数都被设置为了字符串。

### 重现步骤

[BUG]【接口测试>>API>>CASE】请求体json各种指定的数值型参数，切换到“”模式，有些数值型的参数属性，都被改为string类型。在切回json格式时，原来数值型的参数都被设置为了字符串。

### 附加信息

![接口json请求体1](https://user-images.githubusercontent.com/78218624/191722379-8b4cd323-d68b-4d8f-878d-c2333f4f47b8.png)

![image](https://user-images.githubusercontent.com/78218624/191722704-4932ab7d-0385-4b6b-b9fa-c2e88631b9dc.png)

![image](https://user-images.githubusercontent.com/78218624/191723030-6c2e8e95-2b8e-459a-81a5-b3fda5847f4e.png)

![image](https://user-images.githubusercontent.com/78218624/191723591-24a31fdc-4aa7-413d-96ba-34b8ee566e64.png)

**Comment by zyyfit** [comment]
这个目前无法解决，这个是变量取值，拿不到取值的结果，无法转化类型
相同问题 https://github.com/metersphere/metersphere/issues/15760
