### ISSUE TITLE
[BUG]自动化测试报告中没有打印该测试计划执行的环境、串行并行、执行资源池等关键信息

### ISSUE THREAD

**Issue by oldsuper** [metersphere/metersphere#18219]
### 联系方式

13811398758

### MeterSphere 版本

V1.20.x

### 使用外置数据库

是

### 问题描述

我们是贵司的一个B端客户，这些信息作为排查问题的关键信息，在系统中没有合理的展示，我们认为是一个明显的设计缺陷。请尽快修复。

### 重现步骤

自动化测试执行后，进入测试报告即可发现。

### 期待的正确结果

展示所有关键信息，都写在标题中。

**Comment by Hyyfit** [comment]
您好，我们的报告是有展示。
在2.X的版本里
![image](https://user-images.githubusercontent.com/95834771/192927003-ce138418-423a-41b2-8488-79654999615e.png)
