### ISSUE TITLE
[BUG] 项目管理修改项目接口模板失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18236]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

v2.2.0-3ab59f7c

### 重现步骤

修改为接口测试模板    ![Uploading 企业微信截图_16641599482025.png…]()
点击保存，再次查看，还是default

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/192206461-6b1fda75-35a1-412e-8a8e-f5ec1908e9ad.png)
请在“项目设置”--“项目信息”--编辑项目中修改接口模版。
