### ISSUE TITLE
[FEATURE]官方有计划支持postgres吗，或者现有框架支持难度在哪呢

### ISSUE THREAD

**Issue by mojerro** [metersphere/metersphere#18235]
### MeterSphere 版本

2.1.1

### 请描述您的需求或者改进建议

希望支持postgres

**Comment by luty2018** [comment]
目前jmeter是支持postgresql的，我们的执行引擎也是jmeter，所以理论上也能支持。

**Comment by mojerro** [comment]
了解，所以只是缺乏测试，感谢~
