### ISSUE TITLE
[BUG]接口自动化-循环控制器-条件控制器下的请求读取csv数据错乱。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#18233]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

在场景中新增 循环控制器-条件控制器 下有个自定义请求和引用的case，层级关系如下，在条件控制器下请求打印每次读取的csv，运行时,可以看到 条件控制器里的请求csv数据 是错乱的，并不是按照顺序依次读取。

### 重现步骤

1.【接口自动化】-【场景变量】-【上传csv】，csv里就只有表头字段(aa)以及1-10个数字
![image](https://user-images.githubusercontent.com/104960608/191942214-0cef9e4b-228d-4647-947d-fe3e2ace60a3.png)

2.在场景中新增 循环控制器-条件控制器 下有个自定义请求和引用的case，层级关系如下，在条件控制器下请求打印每次读取的csv
![image](https://user-images.githubusercontent.com/104960608/191942290-2a757e61-fc90-4bd6-a8ab-e29afb859857.png)

3.运行时,可以看到 条件控制器里的请求csv数据 是错乱的，并不是按照顺序依次读取。
![image](https://user-images.githubusercontent.com/104960608/191942859-f0e78775-54f6-4ec5-8a5b-e0dafe4ad3cb.png)

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/18189

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/18232
