### ISSUE TITLE
[BUG]  高级检索自定义字段搜索报SQL异常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18234]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

高级检索自定义字段搜索报SQL异常

### 重现步骤

功能模板新增需求号字段
![image](https://user-images.githubusercontent.com/103925124/191946831-4139ee36-cfda-41fa-9f81-bce401f81262.png)
功能用例设置需求号为COCS-3707,COCS-3706
![image](https://user-images.githubusercontent.com/103925124/191946954-f210f8d1-9940-48b3-acec-03d4d07b4c10.png)
高级搜索检索需求号
![image](https://user-images.githubusercontent.com/103925124/191947148-8b852d41-eb05-4772-89f0-692636d59d26.png)
![image](https://user-images.githubusercontent.com/103925124/191947183-ea7a8327-8fd0-4d72-a2ca-56d801445790.png)

### 相关日志输出
客户那边没有英文逗号，也报此错，所以还有别得符号会引起此SQL注入问题，麻烦研发同学一块排查
### 附加信息

SQL注入报错
![image](https://user-images.githubusercontent.com/103925124/191947228-86fb4263-8a30-4fcc-baab-385f58930504.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by Ycr123888** [comment]
这个能尽快排期修复下嘛，企业问题反馈

**Comment by Ycr123888** [comment]
@luty2018 这个能尽快排期修复下嘛，企业问题反馈

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
