### ISSUE TITLE
[BUG]脑图编写测试用例保存后显示保存成功，但是已保存的用例刷新页面后无法展示

### ISSUE THREAD

**Issue by zhaojiajun9** [metersphere/metersphere#18237]
### 联系方式

zhaojiajun@baicizhan.com

### MeterSphere 版本

v2.2.0-b2

### 使用外置数据库

否

### 问题描述

脑图编写测试用例保存后显示保存成功，但是已保存的用例刷新页面后无法展示

### 重现步骤

步骤1：
使用脑图编写测试用例

步骤2：
保存->保存后提示保存成功

步骤3：
刷新页面

步骤4：
查看刚刚保存的用例

### 期待的正确结果

保存且刷新后可以正常保存

**Comment by zhaojiajun9** [comment]
我这边看了一下，用例的数据是成功写入数据库的test_case表,但是无法展示

**Comment by xulinde** [comment]
您好，请问您是这样操作的吗？

https://user-images.githubusercontent.com/64065190/192414774-9c3687ff-935e-496c-97e8-1202ae10b8df.mov

**Comment by whiskyy** [comment]
版本:   v2.2.0-3ab59f7c
遇到相同问题

**Comment by zhaojiajun9** [comment]
我自己查看了一下数据，发现以下情况：

脑图创建的测试用例，在test_case表中的status字段是NULL

列表创建的测试用例，在test_case表中的status字段是'Prepare'

将脑图的测试用例的status字段update成Prepare后就能显示出来了

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #18186

**Comment by zhaojiajun9** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    就是这样操作
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhaojiajun
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2022年09月27日 ***@***.***> 写道： 




您好，请问您是这样操作的吗？

https://user-images.githubusercontent.com/64065190/192414774-9c3687ff-935e-496c-97e8-1202ae10b8df.mov



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
