### ISSUE TITLE
[BUG] 循环控制器+条件控制器组合使用，场景变量csv取值不对

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#18232]
### MeterSphere 版本

v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

循环控制器下面条件控制器，条件控制器下面有case，然后用自定义脚本打印场景变量中csv里面的值，结果是从第二行开始取值的（如下图），即打印出了zcsc10060
![image](https://user-images.githubusercontent.com/111938588/191935154-beffc510-1187-4ca3-a27c-aab53fa686bc.png)
但是条件控制器下面没有case，就自定义脚本，打印出的值是第一行的zcsc10009（正确）
测试发现条件控制器有n个case，那么取值就从n+1行开始，而非第一行开始

### 重现步骤

该问题必现，2.1和2.2版本都这样

### 附加信息

希望能尽快解决一下，影响了项目整体流程进行了！！！！！！

**Comment by zyyfit** [comment]
这里目前就是这样的，暂时没有什么好的处理方法，后续再考虑优化

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/18189

**Comment by minnn0306** [comment]
不会吧，微信群里，技术支持人员帮忙验证了，1.20.14-lts版本下不存在该问题，但是在2.2.0版本下复现了这个bug，这个问题不能优化吗，因为现在这个问题影响了项目整体流程进行了！

**Comment by zyyfit** [comment]
哦哦，那18189这个问题我们也再看看吧

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证
