### ISSUE TITLE
[BUG]测试计划里执行的UI自动化场景用例，偶尔出现失败的场景，但是报告里失败信息为空

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18241]
### 联系方式

王进

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

测试计划里执行的UI自动化场景用例，偶尔出现失败的场景，但是报告里失败信息为空

### 重现步骤

1. 客户这边的情况是，测试计划里有33个UI自动化场景
2. 添加到测试计划
3. 每天定时跑
4. 查看测试报告
![1664162837213](https://user-images.githubusercontent.com/76033005/192188138-727afb68-3fb1-42b3-acd4-91898bf9c631.png)

### 期待的正确结果

失败的场景，应该有失败信息记录，

**Comment by zrfit** [comment]
您好，确认下控制台日志，失败的场景控制台如果是如下图的日志，本质上还是因为grid问题造成的，同问题，https://github.com/metersphere/metersphere/issues/17649，v2.2.0将这种调用失败的场景都置为了失败状态，后续版本会对状态和grid问题进行调研后的统一优化。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/99731894/192221652-f793212c-6c38-4a7f-ad67-2c341f666d0e.png">
