### ISSUE TITLE
[BUG]环境中不输地址，直接定义变量，然后接口中用变量发送接口时，http后面只有一个斜杠

### ISSUE THREAD

**Issue by zyx030613** [metersphere/metersphere#18248]
### MeterSphere 版本

 v2.1.0-2de48bb8

### 使用外置数据库

否

### 问题描述

配置环境-HTTP配置中留空，然后在通用配置中设置变量ip为192.168.2.10:3333, 在接口中直接使用${ip}, 发现无法调用，查看内容是请求地址:
http:/192.168.2.10:3333/pangu/sdkServer/user/loginUser
.。。。。。
少了个斜杠，这个怎么处理

### 重现步骤

配置环境-HTTP配置中留空，然后在通用配置中设置变量ip为192.168.2.10:3333, 在接口中直接使用${ip}, 发现无法调用，查看内容

### 期待的正确结果

应该是双斜杠

**Comment by youliyuan-fit2cloud** [comment]
自定义变量方式不太好控制，建议变量值加上 http吧，感谢支持～
