### ISSUE TITLE
[BUG]接口自动化：引用了如图场景，然后自定义一个脚本，放到引用的场景里面去，发现只执行了引用的这个场景，自己自定义的脚本没有执行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18262]
### MeterSphere 版本

  v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

引用了如图场景，然后自定义一个脚本，放到引用的场景里面去，发现只执行了引用的这个场景，自己自定义的脚本没有执行

### 重现步骤

引用了如图场景，然后自定义一个脚本，放到引用的场景里面去，发现只执行了引用的这个场景，自己自定义的脚本没有执行

### 期待的正确结果

自定义的脚本执行

### 附加信息

![微信图片_20220926160336](https://user-images.githubusercontent.com/43202800/192225516-849af41e-5e4a-4bb4-9618-c74711f0fa5f.jpg)

**Comment by zyyfit** [comment]
引用的场景是不能修改和添加内容的，请问您是怎么操作的把自定义脚本添加进去了？

**Comment by opopjasica** [comment]
展开接口下往上可以拖进去，引用场景里面的接口也可以拖出来

**Comment by xhy12** [comment]
展开被引用的接口 从下往上托能拖进去。里面的接口也能拖出来；不能操作建议屏蔽

**Comment by zyyfit** [comment]
好的，我们优化一下

**Comment by zyyfit** [comment]
2.3.1 版本已修复，请等待版本发布后验证
