### ISSUE TITLE
[FEATURE]是否可以做个 Mac 版的安装脚本

### ISSUE THREAD

**Issue by EsqerYasen** [metersphere/metersphere#18272]
### 联系方式

mr.askar@icloud.com

### MeterSphere 版本

2.2.0

### 使用外置数据库

否

### 问题描述

按照教程安装还有又问题， FAQ里面没有对应的解决方案。
Mac 
https://metersphere.io/docs/v2.x/installation/offline_installation_mac/

### 重现步骤

Mac安装，参考这个文档。

### 相关日志输出
`flowrock@flowdeMac-mini metersphere-offline-installer-v2.2.0 % sudo sh install.sh
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
存在已安装的 MeterSphere, 安装目录为 /opt/metersphere, 执行升级流程
-e [MeterSphere Log]: 拷贝安装文件到目标目录
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file ... target_directory
-e [MeterSphere Log]: ======================= 开始安装 =======================
-e [MeterSphere Log]: 检测到 Docker 已安装，跳过安装步骤
-e [MeterSphere Log]: 启动 Docker
install.sh: line 78: service: command not found
-e [MeterSphere Log]: 检测到 Docker Compose 已安装，跳过安装步骤
hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
chmod: -R: No such file or directory
-e [MeterSphere Log]: 加载镜像
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms2-jdk11
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/kafka:3.2.0
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v2.2.0
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-data-streaming:v2.2.0
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v2.2.0
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.30
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/prometheus:latest
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/redis:6.2.6
Loaded image: registry.cn-qingdao.aliyuncs.com/metersphere/seleniarm-grid-all:4.1.4-20220519
-e [MeterSphere Log]: 启动服务

The HOSTNAME variable is not set. Defaulting to a blank string.
Stopping kafka ...
Stopping kafka ... done
Removing ms-data-streaming  ...
Removing kafka              ...
Removing ms-node-controller ...
Removing ms-data-streaming  ... done
Removing ms-node-controller ... done
Removing kafka              ... done
Removing network metersphere_ms-network
Removing volume metersphere_ms-conf
Removing volume metersphere_ms-logs
Removing volume metersphere_ms-data
Removing volume metersphere_ms-mysql-data
Removing volume metersphere_ms-prometheus-data
Removing volume metersphere_ms-prometheus-conf
Removing volume metersphere_ms-redis-data

The HOSTNAME variable is not set. Defaulting to a blank string.
Creating network "metersphere_ms-network" with driver "bridge"
Creating volume "metersphere_ms-conf" with default driver
Creating volume "metersphere_ms-logs" with default driver
Creating volume "metersphere_ms-data" with default driver
Creating volume "metersphere_ms-mysql-data" with default driver
Creating volume "metersphere_ms-prometheus-data" with default driver
Creating volume "metersphere_ms-prometheus-conf" with default driver
Creating volume "metersphere_ms-redis-data" with default driver
Creating kafka ...
Creating ms-prometheus ...
Creating redis         ...
Creating ms-node-controller ...
Creating mysql              ...
Creating ms-prometheus      ... error

ERROR: for ms-prometheus  Cannot create container for service prometheus: failed to mount local volume: mount /opt/metersphere/conf/prometheus:/var/lib/docker/volumes/metersphere_ms-prometheus-conf/_data, flags: 0x1000: no such file or directory
Creating mysql              ... error

ERROR: for mysql  Cannot create container for service mysql: failed to mount local volume: mount /opt/metersphere/data/mysql:/var/lib/docker/volumes/metersphere_ms-mysql-data/_data, flags: 0x1000: no such file or directory
Creating redis              ... error

ERROR: for redis  Cannot create container for service redis: failed to mount local volume: mount /opt/metersphere/data/redis:/var/lib/docker/volumes/metersphere_ms-redis-data/_data, flags: 0x1000: no such file or directory
Creating ms-node-controller ... error

ERROR: for ms-node-controller  Cannot start service ms-node-controller: error while mounting volume '/var/lib/docker/volumes/metersphere_ms-data/_data': failed to mount local volume: mount /opt/metersphere/data:/var/lib/docker/volumes/metersphere_ms-data/_data, flags: 0x1000: no such file or directory
Creating kafka              ... done
Creating ms-data-streaming  ...
Creating ms-data-streaming  ... error

ERROR: for ms-data-streaming  Cannot start service ms-data-streaming: error while creating mount source path '/host_mnt/opt/metersphere/logs/data-streaming': mkdir /host_mnt/opt/metersphere/logs/data-streaming: operation not permitted

ERROR: for prometheus  Cannot create container for service prometheus: failed to mount local volume: mount /opt/metersphere/conf/prometheus:/var/lib/docker/volumes/metersphere_ms-prometheus-conf/_data, flags: 0x1000: no such file or directory

ERROR: for mysql  Cannot create container for service mysql: failed to mount local volume: mount /opt/metersphere/data/mysql:/var/lib/docker/volumes/metersphere_ms-mysql-data/_data, flags: 0x1000: no such file or directory

ERROR: for redis  Cannot create container for service redis: failed to mount local volume: mount /opt/metersphere/data/redis:/var/lib/docker/volumes/metersphere_ms-redis-data/_data, flags: 0x1000: no such file or directory

ERROR: for ms-node-controller  Cannot start service ms-node-controller: error while mounting volume '/var/lib/docker/volumes/metersphere_ms-data/_data': failed to mount local volume: mount /opt/metersphere/data:/var/lib/docker/volumes/metersphere_ms-data/_data, flags: 0x1000: no such file or directory

ERROR: for ms-data-streaming  Cannot start service ms-data-streaming: error while creating mount source path '/host_mnt/opt/metersphere/logs/data-streaming': mkdir /host_mnt/opt/metersphere/logs/data-streaming: operation not permitted
Encountered errors while bringing up the project.

       Name                     Command                  State               Ports
-------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:9092->9092/tcp
ms-data-streaming    /deployments/run-java.sh         Exit 128
ms-node-controller   /deployments/run-java.sh         Exit 128
-e ======================= 安装完成 =======================

-e 请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
-e 您可以使用命令 'msctl status' 检查服务运行情况.

flowrock@flowdeMac-mini metersphere-offline-installer-v2.2.0 % msctl status

       Name                     Command                  State               Ports
-------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:9092->9092/tcp
ms-data-streaming    /deployments/run-java.sh         Exit 128
ms-node-controller   /deployments/run-java.sh         Exit 128
flowrock@flowdeMac-mini metersphere-offline-installer-v2.2.0 %`

_No response_

**Comment by zyyfit** [comment]
这个看起来是docker的问题，可以搜一下 docker /var/lib/docker/volumes/xxx。no such file or directory 看看能不能找到解决方法

**Comment by EsqerYasen** [comment]
折腾了好几天，Mac安装体验实在是太差了。麻烦能优化一下脚本或者针对Mac写另外一个脚本吗？

**Comment by luty2018** [comment]
目前没有这个规划。
