### ISSUE TITLE
[BUG]CASE页使用下拉三角符号选择全部数据打标签时（非追加标签），会把整个系统的标签覆盖

### ISSUE THREAD

**Issue by Tannii** [metersphere/metersphere#18274]
### 联系方式

941177402@qq.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

CASE页打标签时，通过下图方式选择全部数据，选择批量修改更改标签，会把整个系统的标签覆盖了
![image](https://user-images.githubusercontent.com/34464876/192235610-4528222d-7e1c-460c-b681-cbc7965176b8.png)
![image](https://user-images.githubusercontent.com/34464876/192235867-653c6bb3-2dfe-4a65-9634-61e8d1c72843.png)

### 重现步骤

见问题描述

**Comment by zyyfit** [comment]
不追加就是覆盖，想保留原来的标签就选追加
另外，覆盖整个系统是什么意思？我测试了，没有影响到除了勾选之外的用例
![image](https://user-images.githubusercontent.com/73461316/192492833-d03dd124-340b-47c1-a133-c781b0ef914a.png)

**Comment by Tannii** [comment]
就是除了你勾选的，其他项目的案例都被更新，你上面说的这个我清楚哈

**Comment by Tannii** [comment]
注意要通过我截图的操作去更新就会这样子

**Comment by zyyfit** [comment]
选择了所有数据，还是没有复现，

**Comment by zyyfit** [comment]
复现了

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证
