### ISSUE TITLE
[BUG]全局前置脚本引入包import net.sf.json.JSONObject;场景正常调试，测试计划并行串行正常执行，资源池执行报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#18278]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

全局前置脚本引入包import net.sf.json.JSONObject;场景正常调试，测试计划并行串行正常执行，资源池执行报错

### 重现步骤

1.全局前置脚本引入包import net.sf.json.JSONObject;
![image](https://user-images.githubusercontent.com/103627487/192260555-62c26ae2-cee8-4969-aed2-ff70c431929a.png)
2.创建测试场景，并调试,正常执行，控制台未报错
![image](https://user-images.githubusercontent.com/103627487/192260805-4bb5d38b-bb01-4835-b64a-df78263a895f.png)
3.测试场景并行执行正常
![image](https://user-images.githubusercontent.com/103627487/192260940-20670703-88bc-4f7c-96f3-a3e7164e8767.png)
4.测试场景，资源池执行报错
![image](https://user-images.githubusercontent.com/103627487/192261195-5def33f7-7589-4e1e-894c-c918debb7574.png)

### 期待的正确结果

资源池执行同场景调试，并行串行一致，可以正常执行

**Comment by zyyfit** [comment]
1.20版本没有复现，请检查系统设置 - 资源池是否勾选了同步jar包
![image](https://user-images.githubusercontent.com/73461316/192496737-297c859a-04f2-4abc-b51a-9d44e1777056.png)

**Comment by zyyfit** [comment]
复现了，后续版本修复

**Comment by shenkaibo** [comment]
能在 lts 修复么

**Comment by youliyuan-fit2cloud** [comment]
> 能在 lts 修复么
Local 资源池时没有内置那个包，手动把jar 上传到文件管理里面就可以了。

**Comment by zyyfit** [comment]
您好，通过排查发现，这个脚本是因为使用 net.sf.json.JSONObject 包导致的报错，使用这个包需要往系统里导入多个依赖包，然后这几个依赖包是没有在资源池中内置的，
您可以 org.json.JSONObject 这个json包，ms-server和资源池都有内置，就不需要导入额外的包了，
如果必须要使用 net.sf.json.JSONObject 包，需要在项目设置-文件管理中添加必须的依赖包，然后再用local资源池执行
