### ISSUE TITLE
[BUG]自定义代码时使用python调用redis环境配置无问题，但是执行时报错

### ISSUE THREAD

**Issue by Wyt-test** [metersphere/metersphere#18288]
### 联系方式

15903319650@163.com

### MeterSphere 版本

v1.20.6-lts-b2

### 使用外置数据库

否

### 问题描述

脚本正确的情况下无法调python第三方redis库

### 重现步骤

import sys

sys.path.append("/opt/metersphere/data/python/copies/lib/python2.7/site-packages")
import redis

def selectList(key, value):
    pool = redis.ConnectionPool(host='', port=, password='', decode_responses=True)
    r = redis.Redis(connection_pool=pool)

    a = r.lrange(key, 0, -1)
    b = a[1]
    print(b)

    if value != b:
        msg = " 111"
        print('true')
        AssertionResult.setFailureMessage(msg)
        AssertionResult.setFailure(True)

# value =${radioDramaId}
value = vars.get("radioDramaId")
selectList('radio_drama_honor_id_list_common_3', value)

### 期待的正确结果

可以正常使用python调用redis

### 相关日志输出

```shell
2022-09-26 17:49:53 ERROR d422ad6b 1-1 Problem in JSR223 script: JSR223split==Assertionsplit==1480225526122545154 == 'b'split&&import sys


AttributeError: 'javapackage' object has no attribute 'ConnectionPool' in <script> at line number 27
```

**Comment by xulinde** [comment]
python第三方库暂不支持～您可以自行研究下
