### ISSUE TITLE
[QUESTION]dockerhttpclient should be set

### ISSUE THREAD

**Issue by zxw1998** [metersphere/metersphere#18289]
### 请描述您的问题

性能测试执行报错Please check node-controller status，查询node-controller服务的日志之后发现在请求时日志记录dockerhttpclient should be set
![image](https://user-images.githubusercontent.com/49053312/192469340-7bae9321-8e1c-4351-b396-9679e3bcf5fe.png)

**Comment by wan92hen** [comment]
你好，请问 node-controller 节点是如何部署的。

**Comment by zxw1998** [comment]
k8s部署使用的2.0.1的helm包

**Comment by zxw1998** [comment]
> k8s部署使用的2.0.1的helm包

部署的是1.20.12版本

**Comment by wan92hen** [comment]
请问 k8s 的容器运行时是 containerd 吗？
我们在 k8s 中部署的 node-controller，也需要通过 docker in docker 的方式调用所在节点的 docker 接口去创建 JMeter 容器。node-controller 目前仅支持了 docker 接口，所以如果 k8s 节点用的 containerd，没有运行 docker 服务的话，在这里会有问题。

**Comment by zxw1998** [comment]
我们用的就是这个方式，但是d in d方式没挂载sock文件呀

**Comment by wan92hen** [comment]
https://github.com/metersphere/helm-chart/blob/61c10de725f5cf3bf403b777853bd3e5d5f6c1d8/charts/metersphere/templates/03-modules/metersphere-node-controller.yaml#L90

默认是挂载了整个 /var/run 目录的。
