### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sunzhiping100** [metersphere/metersphere#1828]
**请描述您的需求或者改进建议.**
测试计划期望可以指出 子计划的：一个测试计划，下面有有n多测试任务，各个任务可以选择不同的case，分给不同的人。
可以查看整个任务的进度+状态。可以查看子任务的进度+状态

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/70884437/113376526-8332db80-93a4-11eb-93f1-80354cf97221.png)

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。
