### ISSUE TITLE
[FEATURE] 接口测试报告模板 内容 可以执行的总数和失败数简要

### ISSUE THREAD

**Issue by sunzhiping100** [metersphere/metersphere#1829]
**请描述您的需求或者改进建议.**
接口测试报告模板 内容 可以执行的总数和失败数简要
![image](https://user-images.githubusercontent.com/70884437/113376892-69de5f00-93a5-11eb-9438-92a84d178655.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
测试报告通知模版后面会统一优化下
