### ISSUE TITLE
[BUG]场景接口覆盖率在开启 “url允许重复” 后，计算逻辑有误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#18292]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

场景接口覆盖率在开启 “url允许重复” 后，计算逻辑有误
1. 目前开启 “url允许重复”  的逻辑是 先查询 api_scenario_reference_id 表中的 reference_id 之后，再去 匹配 url 
这样有个问题，比如 我场景关联了 某个 case，但这个 case 后续被删除之后，场景中的步骤其实还在，这个步骤的api 对应的
url 在当前项目的 api 中也还存在，应该算做 “已覆盖”，按照 上边的逻辑，改 步骤 是没有统计到 “已覆盖” 之内的。

### 重现步骤

1.开启 “url允许重复” 、记录当前项目覆盖率
2.创建一个场景，导入一个 case，选择复制、保存场景
3.删除 case、回收站中也删除
4.查看场景覆盖率，开启 “url允许重复” 和 关闭  “url允许重复” 计算出的覆盖率 不同

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
