### ISSUE TITLE
[BUG]  接口参数类型切换失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18296]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

接口参数类型切换失败

### 重现步骤

String类型填入正则表达式，点击生成测试数据可正常生成
![image](https://user-images.githubusercontent.com/103925124/192516102-86248e1e-dc04-433d-b044-dd753a3058fd.png)
切换参数类型为number，最大最小值为1,100
![image](https://user-images.githubusercontent.com/103925124/192516228-ccc50898-3c0f-4761-b357-6053afe8bd70.png)
点击生成测试数据，参数类型依然为string,且数据为手机号
![image](https://user-images.githubusercontent.com/103925124/192516391-b353be9c-de00-4729-952d-b54b97bf952b.png)

### 期待的正确结果

生成数据为number

**Comment by youliyuan-fit2cloud** [comment]
v1.20.16-lts中已修复该问题。
