### ISSUE TITLE
[BUG]循环控制器中次数循环，当变量为负数时，会陷入无限循环

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#18290]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.6

### 使用外置数据库

否

### 问题描述

循环控制器中次数循环可以是一个变量，有时候由于前面的接口返回结果出错，导致次数为一个负数时，不是不进入循环，而是无限循环。

### 重现步骤

设置场景变量  sum 为 9
![image](https://user-images.githubusercontent.com/31870788/192472580-4b6ac832-e5b1-4eaa-ab14-ea6a101d703c.png)

设置次数循环，如下，执行后，将一直循环下去
![image](https://user-images.githubusercontent.com/31870788/192472855-50d3bce0-61fe-4bc3-b393-80941e3a8dc7.png)

![image](https://user-images.githubusercontent.com/31870788/192473397-09bb1895-ce06-4e3c-8360-2578c5034d2e.png)

### 期待的正确结果

不应该进入循环。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
