### ISSUE TITLE
[BUG]接口自动化选择【调试】，站内提示消息显示好几条执行信息。正常希望只显示一条提示信息

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18299]
### MeterSphere 版本

V2.1

### 使用外置数据库

否

### 问题描述

[BUG]接口自动化选择【调试】，站内提示消息显示好几条执行信息。正常希望只显示一条提示信息

操作步骤如下：
1、打开自动化脚本
2、设置环境
3、点击调试
4、问题：站内消息一下提示多条。

备注：没有做任何接口自动化场景的修改。

### 重现步骤

[BUG]接口自动化选择【调试】，站内提示消息显示好几条执行信息。正常希望只显示一条提示信息

操作步骤如下：
1、打开自动化脚本
2、设置环境
3、点击调试
4、问题：站内消息一下提示多条。
5、检查了消息配置，也为发现异常。

备注：没有做任何接口自动化场景的修改。

### 附加信息

一次【调试】显示多条提示信息
![image](https://user-images.githubusercontent.com/78218624/192665318-75505256-3aa4-4186-ad79-2c45e6fc9f63.png)

消息配置页面，也是正常的
![image](https://user-images.githubusercontent.com/78218624/192665382-72545a53-c790-4d48-8649-37070739d471.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题已修复。请升级到v2.1.1以上版本。
