### ISSUE TITLE
[BUG]【重要！！影响流程使用！！非lts版本下复现，lts版本下正常】当循环控制器里有条件控制器，条件控制器里有case，条件控制器中取场景变量csv的值会跳行取

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#18291]
### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

循环控制器下面条件控制器，条件控制器下面有case，然后用自定义脚本打印场景变量中csv里面的值，结果是从第二行开始取值的（如下图），即打印出了zcsc10060
![image](https://user-images.githubusercontent.com/86464217/192487545-d25719a7-0d81-4615-9edc-d4ad697edf51.png)

但是条件控制器下面没有case，就自定义脚本，打印出的值是第一行的zcsc10009（正确）
测试发现条件控制器有n个case，那么取值就从n+1行开始，而非第一行开始

https://user-images.githubusercontent.com/86464217/192487690-5f0afcea-cc62-4830-b7ad-e1d1392b3b31.mp4

**【重要！！影响流程使用！！非lts版本下复现，lts版本下正常】
【重要！！影响流程使用！！非lts版本下复现，lts版本下正常】
【重要！！影响流程使用！！非lts版本下复现，lts版本下正常】**

### 重现步骤

【重要！！影响流程使用！！非lts版本下复现，lts版本下正常】

**Comment by zyyfit** [comment]
这两个问题是不是重复了 https://github.com/metersphere/metersphere/issues/18232

**Comment by zyyfit** [comment]
这两个问题会在后面的版本解决，请问您在哪个交流群？

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #18232
