### ISSUE TITLE
[BUG] 接口参数高级设置中有配置时，不能流畅切换参数类型，且切换成功后，高级设置为空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18293]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

接口参数高级设置中有配置时，不能流畅切换参数类型，且切换成功后，高级设置为空

### 重现步骤

接口参数高级设置中有配置时
![image](https://user-images.githubusercontent.com/103925124/192514096-9860ad94-e151-43e2-abd7-bb6f29d65e92.png)
![image](https://user-images.githubusercontent.com/103925124/192514151-924165fa-9880-4f09-ac31-33aa30d2c581.png)
切换参数类型为number，切换不动，点击配置按钮可切换成功
![image](https://user-images.githubusercontent.com/103925124/192514268-734bb53e-84c9-435a-8321-6ddb6fe664ec.png)
切换成功后，高级设置为空
![image](https://user-images.githubusercontent.com/103925124/192514364-f924ab9f-5650-44f6-bdb2-c46a4debfcc3.png)
生成测试数据正常

**Comment by youliyuan-fit2cloud** [comment]
v1.20.16-lts中已修复该问题。
