### ISSUE TITLE
[BUG]sql请求-勾选引用环境 。再场景编辑页面sql请求可以通过，再场景列表批量执行不通过

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18308]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

sql请求-勾选引用环境 。再场景编辑页面sql请求可以通过，再场景列表批量执行不通过

### 重现步骤

前置条件：配置两个执行环境a b ，两个环境的数据库都配置多个。且ab 环境都存在一个库可以接口场景里面的通过sql请求

问题：在编辑列表勾选引用，环境a 环境b环境sql请求可以通过，，场景列表批量执行环境a执行不通过..失败的请求链接到别的库去了

### 期待的正确结果

接口测试列表sql可以执行

### 附加信息

![11](https://user-images.githubusercontent.com/43202800/192681825-6f295205-0480-43e8-95db-591230d39ef9.gif)
![bcf004b760559dcc258dd1366fd7519](https://user-images.githubusercontent.com/43202800/192681840-8937eb4d-e275-4f9d-804f-be5611a12b15.png)
![image](https://user-images.githubusercontent.com/43202800/192681865-aca519c1-4a72-418a-b415-ce2a9a72d49f.png)

**Comment by xhy12** [comment]
操作步骤：在添加数据源的时候添加了多个，调试后把数据源删除在重新添加
两次切换数据源都调试通过了，但是保存后 第一次修改的数据源默认读成了环境列表里面第一个数据库 ，保存不生效



https://user-images.githubusercontent.com/43202800/192697320-6265402b-6cf6-4065-a725-e0418bcdc53a.mp4

**Comment by youliyuan-fit2cloud** [comment]
> 操作步骤：在添加数据源的时候添加了多个，调试后把数据源删除在重新添加 两次切换数据源都调试通过了，但是保存后 第一次修改的数据源默认读成了环境列表里面第一个数据库 ，保存不生效
> 
>  Rec.0002.mp4

你这个情况看起来不是bug啊，已经切换过运行环境了，再切换回来是默认的第一个数据库，是这样的设计。

**Comment by luty2018** [comment]
多数据源切换，我们会根据同名数据源去切换，没有相同名称的数据源就默认列表第一个，建议多环境多数据源配置时采用同名数据源来达到自动切换的目的。
