### ISSUE TITLE
[BUG]接口测试首页接口未覆盖数量统计，点击跳转列表显示数量和统计数量不一致

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18309]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

接口测试首页接口未覆盖数量统计，点击跳转列表显示数量和统计数量不一致

### 重现步骤

接口测试首页接口未覆盖数量统计，点击跳转列表显示数量和统计数量不一致

### 期待的正确结果

统计一致，期望可以根据模块看到未覆盖的接口

### 附加信息

<img width="960" alt="接口测试首页接口数量统计" src="https://user-images.githubusercontent.com/43202800/192682611-f5a0e707-1af4-4f9d-92d7-f6bcac1950c0.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，跳转的页面是HTTP协议的，我看还有TCP协议的接口的呀，检查下吧。

**Comment by xhy12** [comment]
没有tcp协议

**Comment by xhy12** [comment]
本地项目没有tcp的协议数量也对不上
