### ISSUE TITLE
断言的方式期望增加个JSON Schema校验

### ISSUE THREAD

**Issue by 435805824** [metersphere/metersphere#1830]
什么是JSON Schema：
JSON Schema本身就是一种数据结构，可以清晰的描述JSON数据的结构。
是一种描述JSON数据的JSON数据。

使用JSON Schema的好处：
JSON Schema 非常适用于基于JSON的HTTP的API。
JSON Schema从Java的基本数据类型中对JSON结构进行校验，所以对JSON结构的校验可以理解为对每种不同数据类型的相应校验。
接口测试中可以快速的定位到自己数据格式的正确性。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by 435805824** [comment]
> 感谢反馈，我们先进行下相关调研

您好，这个功能需求目前有在排期吗。期望在您的平台能更早能使用到。这个确实是个非常好用的验证方式。在测试校验方面有突破性的方式结果。能让验证更加具有有效性。而且这个验证方式只需要引用即可。代码增加的很少。期望能够帮忙解决下。我们之前的工程python的。基本就十几行代码就解决了。
python的部分代码例子。
    elif examine_type == 'Schema_check':
        if http_code == '' or int(http_code) == code:
            try:
                response_parameter_list = json.loads(response_parameter_list)
                validate(instance=response_data, schema=response_parameter_list)
            except SchemaError as e:
                header = "验证模式schema出错：\n出错位置：{}\n提示信息：{}".format(" --> ".join([i for i in e.path]), e.message)
                result = False
            except ValidationError as e:
                header = "json数据不符合schema规定：\n出错字段：{}\n提示信息：{}".format(" --> ".join([i for i in e.path]), e.message)
                result = False
            else:
                result = False

**Comment by 435805824** [comment]
> 感谢反馈，我们先进行下相关调研

看了下，请求体里你们已经有这个校验了。
期待断言里也加一下。
万分感谢。

**Comment by xchnshi** [comment]
> 

reponse的json schema是需要的
