### ISSUE TITLE
 [BUG]性能测试报告中 response time(ms) 统计不准确

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18311]
### 联系方式

759590013@qq.com

### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

性能测试 -》测试报告 -》请求统计 表格中 的 response time(ms)  统计不准确，明显偏短
![截屏2022-09-28 下午12 04 17](https://user-images.githubusercontent.com/6245166/192685123-8378bbb8-2fe5-4532-9511-c3273372e241.png)

（性能测试 -》测试报告-》测试概览 中  response time 图中看上去是正确的）
![截屏2022-09-28 下午12 03 41](https://user-images.githubusercontent.com/6245166/192685064-6e254dee-b10a-45c1-bcd9-f2a0d092f6cd.png)

### 重现步骤

直接进行一次性能测试就可以复现

**Comment by xulinde** [comment]
这个计算的是平均数，你鼠标往右滑，中间很长一段都是400多

**Comment by zhangsai** [comment]
> 这个计算的是平均数，你鼠标往右滑，中间很长一段都是400多

@xulinde 不是AVG数字有问题，是90%、95%、99% 的统计不对

**Comment by xulinde** [comment]
> > 这个计算的是平均数，你鼠标往右滑，中间很长一段都是400多
> 
> @xulinde 不是AVG数字有问题，是Med、90%、95%、99% 的统计不对
图和数字是能对得上的，您自行查下这几个指标的含义

**Comment by xulinde** [comment]
用户升级版本后解决
