### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by a6106526** [metersphere/metersphere#18312]
### MeterSphere 版本

2.2.0

### 请描述您的需求或者改进建议

![bad50a0822c4c694d3d1751221d3325](https://user-images.githubusercontent.com/15136557/192703730-0530c36d-5014-4d84-9847-7304a2ac88c4.jpg)

快捷调试这里没办法鼠标下拉
看不到响应体
只能缩放看
![4cc0e228c5081b64ce837d4a423db61](https://user-images.githubusercontent.com/15136557/192703794-75446bb4-0139-4f20-b51a-c098ddc024b2.jpg)

![9e62e1c29fffd38411c9aadc2bc69ad](https://user-images.githubusercontent.com/15136557/192703819-4bff49c6-e4aa-48dc-bd4d-929c95bf3f62.jpg)

### 请描述你建议的实现方案

增加滚轮下滑

**Comment by luty2018** [comment]
没有重现你这个问题， 如果有需要可以在交流群联系@申凯波 远程看一下哦。
