### ISSUE TITLE
[FEATURE]测试报告建议添加一个用例执行进度折现图，管理者希望可以对测试人员执行用例效率做一个统计

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#18310]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

测试报告建议添加一个用例执行进度折现图，管理者希望可以对测试人员执行用例效率做一个统计

### 请描述你建议的实现方案

![Uploading 图片.png…]()
![Uploading 图片.png…]()

**Comment by opopjasica** [comment]
![image](https://user-images.githubusercontent.com/114552960/192690511-ec7b9501-34f9-4633-8bab-294b951c4fb9.png)

**Comment by luty2018** [comment]
感谢建议， 这个我们纳入一下规划。

**Comment by opopjasica** [comment]
收到！期待 ❤
