### ISSUE TITLE
[BUG]导入swagger文档时，“description”字段无法同步到metersphere页面的“描述”信息

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#18315]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.1

### 使用外置数据库

否

### 问题描述

导入swagger文档时，“description”字段无法同步到metersphere页面的“描述”信息

### 重现步骤

请查看swagger文档截图，和metersphere页面截图

![1](https://user-images.githubusercontent.com/18387151/192728884-0ee62c7b-8213-436e-a828-aba492b3ed93.png)
![2](https://user-images.githubusercontent.com/18387151/192728927-e84cf317-d3fc-4438-ac60-c3e1a8a11dc6.jpg)
![3](https://user-images.githubusercontent.com/18387151/192728955-b9202d33-1ce7-4f83-801d-8b6abfc527b4.jpg)
![4](https://user-images.githubusercontent.com/18387151/192728982-dad72475-5baf-481d-b4dc-b2f8400c1cb4.jpg)

### 期待的正确结果

“description”字段可以正常同步到metersphere页面的“描述”信息

**Comment by zyyfit** [comment]
确认一下，是swagger2.0的描述没导入成功吗？我这边测试是swagger2.0描述没导入，swagger3.0描述导入了
