### ISSUE TITLE
[BUG]  测试报告中接口携带等待控制器，结束时间错误，且等待控制器的占用时间和哪个接口占用不明确

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18316]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

测试计划中引用接口携带等待控制器，生产报告中，等待控制器的占用时间和哪个接口占用不明确

### 重现步骤

新建场景，接口随意，某接口中设置等待控制器20000毫秒
![image](https://user-images.githubusercontent.com/103925124/192736484-ae4387dc-5f07-4ce6-97e6-7ef21911ef58.png)
点击生成报告
![image](https://user-images.githubusercontent.com/103925124/192736849-a927d488-c85f-46e3-a60b-2d4e93624ffa.png)
**_此处的开始时间和结束时间不正确，实际花费20秒+；且等待控制器的占用时间和哪个接口占用不明确_**
![image](https://user-images.githubusercontent.com/103925124/192737134-075bd2a8-a522-43a2-bc47-f8c5a998a37c.png)

### 附加信息

- **_2.2版本亦存在此问题_**
- - **_测试计划报告的测试时间也存在同样问题_**
![image](https://user-images.githubusercontent.com/103925124/192745556-93acaf25-ed77-4cb0-b286-05a5fd112a52.png)
重点关注下！！！

**Comment by xulinde** [comment]
等待控制器加场景里是全局的，对所有请求都会生效，想对单个请求生效，直接在该接口里加
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/64065190/192930995-64d8b2e2-8769-45ce-a5bf-46aad581b841.png">

**Comment by Ycr123888** [comment]
“想对单个请求生效，直接在该接口里加”

我的问题前提就是在接口前置里加的

**Comment by xulinde** [comment]
平台执行有自身数据组装，发送，和存储消耗，有时资源不足情况还会处理的慢。现在的计算是根据请求的发起时间到 结束时间 的时间差，统计出来的时间可能会跟实际运行的时间差有些差距，后续会优化。产品已经在规划了～
