### ISSUE TITLE
[BUG]定时任务 邮件不通知

### ISSUE THREAD

**Issue by wang-qa** [metersphere/metersphere#1831]
MeterSphere 版本
1.8.1

Bug 描述
定时任务，任务通知不生效（邮件）

Bug 重现步骤

创建接口自动化或压测
设置定时任务
设置运行失败和成功时  邮件通知

期待的正确结果  
邮箱收到测试报告

截图
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/58168764/113379055-1838d300-93ab-11eb-9c13-53d427fe1f29.png)
![image](https://user-images.githubusercontent.com/58168764/113379099-2edf2a00-93ab-11eb-8d60-146144c069e1.png)

**Comment by xulinde** [comment]
创建用户时添加的邮箱和测试收件人是一个吗

**Comment by wang-qa** [comment]
> 创建用户时添加的邮箱和测试收件人是一个吗

系统设置的是 139邮箱   用户的邮箱是 qq邮箱

定时任务执行后，生成报告，邮箱无新邮件
