### ISSUE TITLE
工作空间下项目报告汇总

### ISSUE THREAD

**Issue by wq-zhou** [metersphere/metersphere#18321]
### 请描述您的问题

领导希望随时查看各项目接口用例执行情况，现在需要切换工作空间、切换项目才能一一查看，但是公司产品线多，产品线下项目也多，一个一个切换过于繁琐，领导需求是一次看全部运行结果，至少一个工作空间下的全部项目执行情况，想咨询下有没有什么方案能实现？盼回

**Comment by luty2018** [comment]
目前我们确实还不支持看一个空间下的全部项目执行情况，但是这个需求是合理的，我们会考虑做到工作台，目前工作台是跨项目的，管理者可以在工作台看到整个空间下所有项目的数据汇总。

**Comment by wq-zhou** [comment]
感谢回复，期待该功能的上线。

**Comment by luty2018** [comment]
已转需求跟进
