### ISSUE TITLE
[FEATURE]测试跟踪-测试计划-测试报告-失败用例无快速排查功能

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#18325]
### MeterSphere 版本

v2.2.0

### 请描述您的需求或者改进建议

场景：测试跟踪-测试计划-测试报告-失败用例5条
我知道失败重试机制。
这里关注的是 这个接口真的是有问题，我需要去联调一下

那么业务需求：
我需要在这里进行联调，一种当时是这里直接调式，验证是否是真的不通，或者哪里有问题
                                    另一种是可以跳转到对应case直接去调试

### 请描述你建议的实现方案

那么业务需求：
我需要在这里进行联调，一种是这里直接调式，验证是否是真的不通，或者哪里有问题
                                    另一种是可以跳转到对应case直接去调试

**Comment by luty2018** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/36292514/192926381-f4d05ec4-19db-4fa5-b4cc-bea02b3a395c.png">
失败重跑这个功能在我们的企业版里面已经提供了， 可以申请试用。

**Comment by legend818** [comment]
这个不应该作为企业版啊

**Comment by luty2018** [comment]
目前这个是规划到企业版功能中的， 不排除后续会放到开源版

**Comment by legend818** [comment]
建议放到开源版本啊

**Comment by luty2018** [comment]
会的。
