### ISSUE TITLE
[FEATURE]场景变量请求头与环境配置请求头优先级失效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#18330]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.14-LTS

### 使用外置数据库

否

### 问题描述

1、场景请求头与环境配置配置相同名称的请求头
2、接口自动化发起请求
3、发现实际发出去的请求头是环境配置里的请求头，不是场景变量里面配置的请求头

### 重现步骤

1、场景变量请求头与环境配置配置相同名称的请求头
2、接口自动化发起请求
3、发现实际发出去的请求头是环境配置里的请求头，不是场景变量里面配置的请求头

### 附加信息

场景变量的请求头：
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/32027713/192931795-14b588c9-d13c-48b9-b559-66e3c82f8014.png">
环境配置请求头：
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/32027713/192931893-b2837da0-9357-4aa7-a501-d4a3abe3af9a.png">
实际发出的请求头：
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/32027713/192931992-13a743ab-2f0b-4f69-92ba-33ecd6a52487.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，这里经过确认，请求头和变量不同，目前的逻辑是：
环境里的请求头优先级是高于场景请求头的，因为环境需要匹配，匹配到不同的环境会带上对应环境的请求头，如果场景请求头优先的话，环境匹配后的请求头就无法生效了

**Comment by luty2018** [comment]
如有疑问可以进一步沟通。
