### ISSUE TITLE
[FEATURE]UI测试脚本断言建议加个模糊匹配

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#18339]
### MeterSphere 版本

cloud最新版

### 请描述您的需求或者改进建议

步骤断言：比如某些提示语 为“xxx填写错误”。挨个文本是否等于/不等于期望值 的匹配很麻烦

期望：断言方式添加in //notin  这样只需要断言文字包含:" 填写错误"  就可以了

### 请描述你建议的实现方案

期望：断言方式添加in //notin  这样只需要断言文字包含:" 填写错误"  就可以了

### 附加信息

![图片](https://user-images.githubusercontent.com/114552960/192978458-43ddab98-2b50-48de-b53f-9ab71400e5ac.png)

**Comment by Hyyfit** [comment]
OK，这个确实有必要，我们最近的1-2个版本会支持
