### ISSUE TITLE
[BUG]测试计划内用例“添加缺陷”的缺陷状态统计不正确，“关联缺陷”的缺陷数量统计不正确

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18335]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

测试计划内用例“添加缺陷”的缺陷状态不正确，“关联缺陷”的缺陷数量统计不正确

### 重现步骤

1.创建测试计划，并关联功能用例
2.在测试计划内打开功能用例，点击“添加缺陷”，手动新增缺陷
3.在测试跟踪-缺陷管理修改该缺陷的状态为已关闭
4.查看“报告统计”，功能用例统计分析-测试结果。缺陷状态不对，都是新建状态
5.在测试计划内打开功能用例，点击“关联缺陷”，关联测试跟踪-缺陷关联中创建的缺陷
6.查看“报告统计”，功能用例统计分析-测试结果。缺陷数量不对，只统计了“添加缺陷”的数量，没有统计“关联缺陷”的数量
![image](https://user-images.githubusercontent.com/88763608/192964234-acd3e54d-0fa3-4ef4-bd4f-592b44c62abb.png)

### 期待的正确结果
“添加缺陷”和“关联缺陷”的缺陷数量和缺陷状态都应该正常统计并展示
_No response_

**Comment by xulinde** [comment]
v2.3.1已修复
