### ISSUE TITLE
[BUG]新版本用例字段格式变更，导致之前版本 excel 导入异常

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#18338]
### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

 v1.18.3 及之前版本，用例模板的自定义字段值在 excel 导出/导入展示的是["01"] 这种格式；
但是 v2.2.0 却展示为 [01] 这种格式了，导入之前的 excel 会报错

### 重现步骤

自定义用例模板下拉选多选字段，如下拉选值是 01  02  03
导入原  v1.18.3 的用例 excel 文件（下拉选字段值在 excel 写的是["01"]  ），无法在 v2.2.0 版本导入

### 期待的正确结果

可以和之前版本一样，新版本可以正常导入用例

**Comment by xulinde** [comment]
没有复现该问题，方便把导出的数据截图看下吗？
