### ISSUE TITLE
[BUG]场景Z中 引用场景X，场景X包含一个自定义脚本请求（该自定义请求包含一个前置SQL），场景Z中设置X场景变量uncheck "原场景变量"，在场景Z中切换数据源后 调试发现场景X中前置SQL的数据源实际值没有被切换。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18331]
### 联系方式

王进

### MeterSphere 版本

v1.20.14, cloud, v2.2

### 使用外置数据库

否

### 问题描述

场景Z中 引用场景X，场景X包含一个自定义脚本请求（该自定义请求包含一个前置SQL），场景Z中设置X场景变量uncheck "原场景变量"，在场景Z中切换数据源后 调试发现场景X中前置SQL的数据源实际值没有被切换。

### 重现步骤
1. 新建两个环境A, 它包含两个数据源a, b，信息如下：
   a: jdbc:mysql://10.1.12.15:3307/adb  , root/Password123@mysql   (手动在装MS的机器上建了一个库，下面没有任何表)
   b: jdbc:mysql://10.1.12.15:3307/metersphere,  root/Password123@mysql   (MeterSphere原生库)
2. 新建一个环境B，它包含两个数据源a, b，信息如下：
   a: jdbc:mysql://10.1.12.15:3307/adb  , root/Password123@mysql   (手动在装MS的机器上建了一个库，下面没有任何表)
   b: jdbc:mysql://10.1.12.15:3307/metersphere,  root/Password123@mysql   (MeterSphere原生库)
3. 新建场景X，添加一个自定义脚本，在该自定义脚本下添加前置SQL，选择数据源A，数据库b，同时在自定义脚本里增加如下内容：
   vars.put("name_1", "${name_1}");
   log.info("${name_1}");
   前置SQL:
   select name from user

4. 场景X，在A环境不同数据源a,b的调试结果不一样，  a数据源打印的日志是 ${name_1}, b打印的是系统管理员账号。
5. 保存场景X，环境选择A或者B，但是数据源b。
6. 新建场景Z，引用场景X，场景Z中设置X场景变量uncheck "原场景变量"，不勾选“原场景变量”，同时此时导入后看到默认的数据库是b。
7. 此时打开场景X，选择A或者B，但是数据源选a，然后保存。
8. 在场景Z里，切换环境，会发现，虽然不勾选“原场景变量”，调试结果 控制台看到${name_1}，说明 不勾选“原场景变量” 未生效。

**Comment by 35plus** [comment]
liyuan老师，我刚刚自己复测了场景c，确实有这个问题。帮忙让开发修复一下c。  至于 场景a，我再和用户沟通一下，看看怎么复现出来。

**Comment by 35plus** [comment]
liyuan，这个问题，经过再次复测确认，确实是bug。

**Comment by zrfit** [comment]
你好，感谢您的反馈！
根据您描述的问题和实际操作后说明如下：
1、首先步骤6和8中提到的是否勾选原场景变量对该场景要实现的效果并没有影响，因为场景X中没有场景变量。
2、场景Z引用场景X，切换环境后-相同的数据源，执行返回数据正常，并没有复现这个问题。
