### ISSUE TITLE
[QUESTION]mac,部署成功之后，无法使用网址访问

### ISSUE THREAD

**Issue by haohongbin** [metersphere/metersphere#18336]
### 请描述您的问题

mac(m1芯片)，下载metersphere-offline-installer-v2.2.0-arm64 安装包，安装成功之后，无法使用网址访问。
排查：
docker logs ms-server  看到如下错误
<img width="1636" alt="image" src="https://user-images.githubusercontent.com/45677141/192966351-c4b4b9c9-a898-4e6d-b070-69fd41a11e53.png">
但是实际目录下有该文件，读写权限为644

**Comment by wan92hen** [comment]
你好，请检查下容器配置的挂载目录有没有正常挂载上。

**Comment by haohongbin** [comment]
> 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/45677141/193198979-84bd4c4a-3360-4e16-8e9c-28dab62d3fd2.png">
conf文件夹没有挂上，为啥呢

**Comment by wan92hen** [comment]
可以再检查下 docker volume 的映射情况，mac 下的安装脚本使用的根路径是 `~`，对应的 metersphere 目录是 `~/metersphere`，然后 mac 下的 docker 卷挂载本地路径还需要在 docker desktop 里配点东西应该。

**Comment by haohongbin** [comment]
> 还需要在 docker desktop 里配点东西应该。

配置啥呢，我又检查了一遍映射没问题

**Comment by wan92hen** [comment]
你好，请问这个问题解决了吗？
