### ISSUE TITLE
[BUG]接口自动化场景用例中增加等待时间的自定义脚本时，执行步骤会卡死在等待的脚步步骤中

### ISSUE THREAD

**Issue by suki1222** [metersphere/metersphere#18346]
### MeterSphere 版本

 v2-0-1-aa6f2dde

### 使用外置数据库

否

### 问题描述

接口自动化场景用例中增加等待时间的自定义脚本时，执行步骤会卡死在等待的脚步步骤中

### 重现步骤

接口自动化场景用例中增加等待时间的自定义脚本

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把等待时间的自定义脚本截图我们看看吗？
