### ISSUE TITLE
[BUG]飞书通知无法使用@功能

### ISSUE THREAD

**Issue by honglianglv0917** [metersphere/metersphere#18349]
### 联系方式

18600619373@163.com

### MeterSphere 版本

v1.20.15

### 使用外置数据库

否

### 问题描述

消息发送到飞书,对应的接收人 使用了@,但是并没有关联

### 重现步骤

使用接口自动化配置"任务通知"和使用 "项目设置-消息设置",接收方式选择"飞书机器人",填写接收人和相关webhook,保存。
触发消息发送到飞书,对应的接收人 使用了@,但是并没有关联

ps
1.接收人配置了手机号和飞书的一致。
2.钉钉可以使用@,并有关联

### 期待的正确结果

触发消息发送到飞书,对应的接收人 使用了@,需要有关联

**Comment by honglianglv0917** [comment]
飞书@的是user_id并不是手机号

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，飞书暂时不支持。

**Comment by youliyuan-fit2cloud** [comment]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/54612864/196102120-2d3b4124-861d-42d9-8c56-dc867f80d457.png">
