### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Paprika-ztz** [metersphere/metersphere#18340]
### MeterSphere 版本

v1.20.12-lts-2297374a

### 请描述您的需求或者改进建议

加入批量操作功能，

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/103817441/192992796-b0f05e1b-e6cf-4e1e-851a-3d4e4a6be2a2.png)

**Comment by luty2018** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/36292514/193174591-c2de26ce-3608-4df1-bbec-40a3c835af76.png">
请描述清楚问题
根据你的描述，目前列表支持选择全部数据，是否能满足你的需求
