### ISSUE TITLE
[BUG]接口测试-接口定义-case-使用form-data请求体提交包含中文名称的附件，提交请求中被转化成乱码

### ISSUE THREAD

**Issue by rbsrcy** [metersphere/metersphere#18348]
### 联系方式

zhuoshangyi@hntradesp.com

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

接口测试-接口定义-case-使用form-data请求体提交包含中文名称的附件，提交请求中form-data中的中文文件名称被转化成乱码。
现象如下图
![附件](https://files.catbox.moe/ptfwg9.png)

### 重现步骤

接口测试-接口定义-case-使用form-data请求体提交包含中文名称的附件，提交请求中被转化成乱码。
现象如下图
![附件](https://files.catbox.moe/ptfwg9.png)

### 期待的正确结果

提交请求中form-data中的中文文件名称应该被正确转化

### 附加信息

![附件](https://files.catbox.moe/ptfwg9.png)

**Comment by rbsrcy** [comment]
补充日志：
请求地址:
https://dev.cimos.hntradesp.com/otrade/account/upload.ajax
请求头:
Connection: keep-alive
X-Requested-With: XMLHttpRequest
Content-Length: 39836
Content-Type: multipart/form-data; boundary=a9nv2aXgPR3jc2R9D0YBlB1bIOZqXQnrB98
Host: dev.cimos.hntradesp.com
User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.16.1)

Cookies :
XXXXXX
Body:
POST https://dev.cimos.hntradesp.com/otrade/account/upload.ajax

POST data:
--a9nv2aXgPR3jc2R9D0YBlB1bIOZqXQnrB98
Content-Disposition: form-data; name="file"; filename="????.jpg"
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

<actual file content, not shown here>
--a9nv2aXgPR3jc2R9D0YBlB1bIOZqXQnrB98--


Cookie Data:
XXXXXX

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个是jmeter的bug，目前我们还没更好的解决办法。

Duplicate of #17583
