### ISSUE TITLE
[BUG]接口定义-CASE,执行CASE用例成功，推荐jsonpath缺失全屏断言选择按钮

### ISSUE THREAD

**Issue by Makeseyou** [metersphere/metersphere#18341]
### MeterSphere 版本

  v1.20.14-lts-83677fba

### 使用外置数据库

是

### 问题描述

接口定义——CASE，执行成功的CASE进行JSONpath断言时，缺失全屏结果显示按钮

### 重现步骤

接口定义——>CASE：
1、新建一个CASE
2、执行新建的CASE成功，断言规则——>点击 推荐JSONpath按钮
3、显示的断言选择窗口不能全屏操作

### 期待的正确结果

CASE中进行断言时，可以全屏选择断言结果

### 附加信息

![image](https://user-images.githubusercontent.com/114658401/193002288-3c71ead9-b947-4c81-9b9b-2eb4787f36ff.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本操作

**Comment by zyyfit** [comment]
1.20.16版本已修复，请等待版本发布后验证
