### ISSUE TITLE
[BUG] 文件管理-git存储库，测试链接失败时间过长，且错误原因不清晰

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18347]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

文件管理-git存储库，测试链接失败时间过长，且错误原因不清晰
![image](https://user-images.githubusercontent.com/103925124/193224832-dd02901b-9be4-4e17-8ae8-3346757aa561.png)

### 重现步骤

文件管理-git存储库，测试链接失败时间过长，且错误原因不清晰
![image](https://user-images.githubusercontent.com/103925124/193224832-dd02901b-9be4-4e17-8ae8-3346757aa561.png)

提示项目不存在还是token错误，没有返回
偶现测试链接长时间加载报错Repository connect error!

### 期待的正确结果

提示git项目不存在
提示分支不存在
提示token错误
等错误信息，超时时间，超过10秒，待会再试。。

### 相关日志输出
使用git地址：请求时间短
![image](https://user-images.githubusercontent.com/103925124/193226425-0af296f9-7950-4066-b143-d7d4bc9fb0ba.png)

使用http地址：请求时间稍长些
![image](https://user-images.githubusercontent.com/103925124/193226193-05bda2e4-6505-43a0-a798-7bc5466fc878.png)

_No response_

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已优化。
