### ISSUE TITLE
[BUG]1.20.15, UI自动化，浏览器操作 如果URL是域名，会出现访问超时的情况

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18359]
### 联系方式

王进

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

1.20.15, UI自动化，浏览器操作 如果URL是域名，会出现访问超时的情况

### 重现步骤

1. 新建一个UI自动化场景
2. 添加浏览器操作，输入一个域名
3. 点生成报告或者后端调试，会出现超时
![1665218752213](https://user-images.githubusercontent.com/76033005/194698713-b534e7bc-c0df-434e-82d3-66859a8f86de.png)

4. 本地调试是好的。

**Comment by zrfit** [comment]
您好，未复现该问题，方便提供下URL吗？
