### ISSUE TITLE
[BUG]UI自动化脚本中包含关闭网页操作时，当关闭网页操作在UI脚本最后一步，执行时会出现执行报告无法生成的错误。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#18354]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.14-lts

### 使用外置数据库

否

### 问题描述

UI自动化脚本中包含关闭网页操作时，当关闭网页操作在脚本最后一步，执行时会出现测试结果报告无法生成的错误。

### 重现步骤

当关闭网页操作在UI脚本最后一步，执行时会出现测试结果报告无法生成的错误。

### 期待的正确结果

能正常生成测试报告

### 附加信息

![image](https://user-images.githubusercontent.com/83771182/194692592-ee64943c-bb2b-4dd9-a830-bc66f2e88ce9.png)

**Comment by zrfit** [comment]
您好，经过多次尝试验证，是当未勾选性能模式生成报告会有该问题，后续版本修复，感谢您的反馈！

**Comment by youliyuan-fit2cloud** [comment]
v1.20.16-lts版本已经修复了该问题。
