### ISSUE TITLE
[BUG]UI自动化脚本中包含关闭网页操作时，当关闭网页操作处在脚本的中间步骤时，执行脚本生成的测试报告中的截图并没有反映出关闭网页步骤被执行过。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#18356]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.15-lts

### 使用外置数据库

否

### 问题描述

UI自动化脚本中包含关闭网页操作时，当关闭网页操作处在脚本的中间步骤时，执行脚本生成测试报告中的截图并没有反映出关闭网页步骤被执行过。
<img width="922" alt="33cd6bab59866444737403ab418e033" src="https://user-images.githubusercontent.com/83771182/194692802-3f78e258-9077-41b0-b38c-b18d38329696.png">

### 重现步骤

![image](https://user-images.githubusercontent.com/83771182/194692866-9cd02cab-b09a-4b57-adb2-e95c3e2971f6.png)

制作ui脚本，其中包含关闭网页的操作步骤。

### 期待的正确结果

截图中应该可以体现出关闭网页后的状态，关闭网页后，应该不可以再通过脚本对该网页的元素进行操作。

**Comment by youliyuan-fit2cloud** [comment]
已修复该问题， 升级到最新的v1.20.18-lts吧。
