### ISSUE TITLE
v2.2版本复现 tcp gbk返回值乱码的问题，之前已经在v2.1修复了

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#18350]
@youliyuan-fit2cloud 咱们v2.2版本又复现了这个问题，之前已经在v2.1修复了。
![image](https://user-images.githubusercontent.com/92966838/194682289-3005e518-fc74-4cd0-9cda-9d978a4dde58.png)
![image](https://user-images.githubusercontent.com/92966838/194682303-c81851b5-bdaa-4aa4-8857-7d986e3967b2.png)

_Originally posted by @gaohonghai in https://github.com/metersphere/metersphere/issues/16526#issuecomment-1272194969_

**Comment by gaohonghai** [comment]
已修复的 issue 链接：https://github.com/metersphere/metersphere/issues/16526

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您这边乱码字符原本的正确字符是什么？我们测试一下看看
![image](https://user-images.githubusercontent.com/73461316/194703724-928dd3e2-7914-428a-b3be-36b2b7cdc4e0.png)

**Comment by gaohonghai** [comment]
`ZSXN2010140     <?xml version="1.0" encoding="GBK"?>
<RETURN><MAIN><APP /><OKFLAG>0</OKFLAG><REJECTNO>JL:1请联系管理员</REJECTNO></MAIN></RETURN>`

这个是客户返回的 xml 报文

**Comment by zyyfit** [comment]
收到

**Comment by gaohonghai** [comment]
大佬们，方便问下修复的档期吗

**Comment by youliyuan-fit2cloud** [comment]
> 大佬们，方便问下修复的档期吗

计划v2.3.1中解决，发布时间计划11.11

**Comment by zyyfit** [comment]
2.3.1已修复
