### ISSUE TITLE
[BUG]接口测试query参数值json串中有多个元素时，设置编码功能失效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18355]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

接口测试query参数值json串中有多个元素时，设置编码功能失效

### 重现步骤

1.创建接口测试
2.设置query参数data:{"name":"kokok","size":"xl"}，设置编码
![image](https://user-images.githubusercontent.com/88763608/194692922-4fe36b59-df90-4568-877e-8f4e184b078d.png)

3.发起请求，请求失败，编码失败了，提示不合法
![image](https://user-images.githubusercontent.com/88763608/194692856-296b47d1-43e3-4083-a9f9-a4c416945817.png)
![image](https://user-images.githubusercontent.com/88763608/194692878-243170a3-b2f8-4951-97ff-16ce0fe20ba6.png)

### 期待的正确结果

正常编码

**Comment by zyyfit** [comment]
query里的json字符串，英文逗号要加转义
