### ISSUE TITLE
[BUG]保存时报错SQL error happened, please check logs

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#18364]
### 请描述您的问题

上个月服务器由开发进行了一次磁盘清理操作，磁盘清理操作之后，小组成员继续使用metersphere进行测试工作，但是国庆假后发现，从上次磁盘清理操作的时间点之后，到国庆假后第一天复工，中间的所有的修改的数据、场景或者接口的配置都没有了。

请问是什么设置可能导致以上情况发生？

**Comment by Faerie1999** [comment]
补充说明：检查了服务器的数据库中的数据以及binlog，都没有那个时间点之后的数据。但是当时磁盘清理之后，那几天小组测试的数据一直是正常的，按理说当时数据库都会持久化到硬盘里面，针对这段时间的数据被清空的情况，开发进行了一些检查，但是未发现原因。

**Comment by luty2018** [comment]
收到反馈，尽快协助排查

**Comment by Faerie1999** [comment]
这几天保存的时候，metersphere网页会出现一个toast，提示“SQL error happened, please check logs”，打开浏览器控制台，提示是 内部服务器错误。上次清除的数据那几天网页也会报这个错误，是否是因为这个错误导致数据出现问题？这个地方需要关注一下，由于数据丢失对于公司损害较大，以下是截图，如果有有用信息，请回复，谢谢。

![image](https://user-images.githubusercontent.com/31870788/195575073-76b5c20b-3125-494e-91b1-2626bacc52eb.png)


控制台的报错信息如下：
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
{
    "data": {
        "success": false,
        "message": "SQL error happened, please check logs.",
        "data": null
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "headers": {
        "connection": "keep-alive",
        "content-encoding": "gzip",
        "content-type": "application/json",
        "date": "Mon, 10 Oct 2022 01:46:46 GMT",
        "server": "nginx/1.20.2",
        "transfer-encoding": "chunked"
    },
    "config": {
        "url": "/api/module/list/f54622fc-6448-4e22-8361-8fa0ad41c599/HTTP",
        "method": "get",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "CSRF-TOKEN": "TWq4ukVnODt3hhQ1XgkSeCVKID5l8NuMVNZCfZeThh4RAIduJT1wwMLsh1YCxUxKLxIXuTfoE0VOQdG/2SI/cVERrj3DOnGSwlRqtP51fDw=",
            "WORKSPACE": "03054a2d-fd91-497e-8e40-2ad956a8a24c",
            "PROJECT": "f54622fc-6448-4e22-8361-8fa0ad41c599"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "withCredentials": true,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        }
    },
    "request": {}
}

**Comment by Faerie1999** [comment]
版本:   v1.20.7

**Comment by Faerie1999** [comment]
> 都没有那个时间点之后的数据



> 收到反馈，尽快协助排查

请尽快协助排查，谢谢

**Comment by luty2018** [comment]
请问问题还存在吗？
