### ISSUE TITLE
[BUG] 使用自定义字段展示jira缺陷列表字段，未展示成功

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18360]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v1.20.14-lts-83677fba

### 使用外置数据库

否

### 问题描述

场景：【中信建投】 jira 平台，在缺陷列表页面的关键字字段，希望能在咱们MS系统缺陷列表页面展示出来。
遇到问题：使用自定义字段展示jira缺陷列表字段，未展示成功

### 重现步骤

1、模板中增加platformId字段
![image](https://user-images.githubusercontent.com/103925124/194700516-afb68d32-ea3a-445e-a4d9-eff71604e3bb.png)
2、项目引用此模板
![image](https://user-images.githubusercontent.com/103925124/194700675-e9200698-ad9b-4749-8304-a8b25655222d.png)
3、同步缺陷，platformId字段未空
![image](https://user-images.githubusercontent.com/103925124/194700716-fbb87cd9-7a75-4504-98f6-a94e70d8c660.png)

### 期待的正确结果

platformId展示jira中关键字字段

**Comment by xulinde** [comment]
v1.20.14-lts未复现该问题，请确认下：
1.自定义字段的类型和选项值是否和jira平台保持一致
2.API字段名是否正确

**Comment by Ycr123888** [comment]
已验证非缺陷
