### ISSUE TITLE
[BUG]飞书机器人的群通知@接收人功能，被@的人没有收到被@的通知，@xxx仅具有文本效果

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18365]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.0  飞书 5.21.5版本

### 使用外置数据库

否

### 问题描述

MS的飞书机器人在群里@成员后，成员能看到新消息，但是成员并不知道自己被@了，因为没有收到被@的提示

### 重现步骤

1.这是机器人发送的通知，本人只看到消息，并不知道自己被@了，需要进去群才能知道自己被@。如果群xiao消息多，很可能错失了消息
![image](https://user-images.githubusercontent.com/88763608/194734324-414bda24-d902-475b-8a55-27d8f922f913.png)
![image](https://user-images.githubusercontent.com/88763608/194734135-1dd3777f-5053-4f66-812c-929d05a923b6.png)
![image](https://user-images.githubusercontent.com/88763608/194734154-7184e223-93d9-41a9-ae4c-e6767608d1de.png)
2.这是真人手动@后，被@人收到的通知，会提示被某某@了
![d126599f-25c7-4616-82d6-23bfe499a2cf](https://user-images.githubusercontent.com/88763608/194734195-23a82c31-107a-4b54-9e04-e239089b00e8.png)
![image](https://user-images.githubusercontent.com/88763608/194734392-7136a2a4-8b0c-41b9-9289-66484621c25c.png)

### 期待的正确结果

被@人能收到被@的通知提示

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #18349
