### ISSUE TITLE
[BUG] 场景变量数组不能while，var.put的变量可以while

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18362]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

场景变量数组不能while，var.put的变量可以while
![image](https://user-images.githubusercontent.com/103925124/194706776-caaa7db3-9ee4-40e9-802a-7ba385d4ea0f.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/194706801-bbba8c2d-57dc-4cc6-9ddd-5a21172cc4cc.png)
未进入循环
![image](https://user-images.githubusercontent.com/103925124/194706847-d35e097a-b1c5-4b3c-80f9-9cc28b604708.png)
![image](https://user-images.githubusercontent.com/103925124/194706879-aafb5a77-f6bd-43f0-bea3-4a34fcc6252d.png)
循环了26次
![image](https://user-images.githubusercontent.com/103925124/194706951-6bc8f1b5-3bcc-436b-b7dc-0005d7c83887.png)

### 期待的正确结果

场景变量设置的列表也可以进入while循环

**Comment by zyyfit** [comment]
while不支持使用列表变量，可以参考这个文章
https://blog.csdn.net/jierxiaoyao/article/details/115512966
![image](https://user-images.githubusercontent.com/73461316/194751282-c1cfc06d-d8d0-47a5-ae0d-93286b4692f8.png)

**Comment by Ycr123888** [comment]
在脚本里定义的list，可以循环，且每次循环的次数不一致，while能不能支持下 场景变量里的列表和put的列表

**Comment by luty2018** [comment]
在TAPD提交需求。
