### ISSUE TITLE
[FEATURE]UI测试脚本编排使用体验不好，希望优化

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#18361]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

UI测试脚本编排使用体验不好：写步骤在左上角 添加步骤在右下角，并且有些步骤是连续输入操作，要一个一个去点 用起来真的好累:(。写脚本的体验不太好 

诚挚建议提高下用户体验：
1、写步骤本身就在页面右上角，希望可以直接添加步骤 比如输入操作连续输入时 回车复制多个 输入操作，
2、或者写了一个步骤后自动生成空的下一个步骤，（类似已有接口传参的输入框操作）

### 请描述你建议的实现方案

诚挚建议提高下用户体验：
1、写步骤本身就在页面右上角，希望可以直接添加步骤 比如输入操作连续输入时 回车复制多个 输入操作，
2、或者写了一个步骤后自动生成空的下一个步骤，（类似已有接口传参的输入框操作）

**Comment by Hyyfit** [comment]
1.有计划对输入步骤优化，初步的设计是在输入步骤内可以支持多条输入；
2.我们的步骤类型比较多，如果说生成一个空步骤，不好确定是什么类型的步骤，这个不考虑做。另外回车复制也是一样的道理，如果是对同一种类型的，可以直接对步骤进行复制，如果是不同类型的，回车复制不好确定类型。
<img width="292" alt="image" src="https://user-images.githubusercontent.com/95834771/194741207-4b8e221d-a230-419c-ac4f-eff94f424daf.png">

**Comment by opopjasica** [comment]
收到，感谢~

**Comment by opopjasica** [comment]
就是希望生成一个空步骤，用户自己选择就好 。主要就是操作在左下角 脚本在右上角视野上反人类

**Comment by Hyyfit** [comment]
最初的设计是考虑页面风格统一，借鉴了接口场景自动化的编排方式。
这个左下角，右上角位置的问题，我们交互后面会对这里进行优化～～。
空步骤确实不好区分是什么类型的步骤，这个不考虑。
