### ISSUE TITLE
[BUG]测试跟踪-缺陷管理，同步到 jira平台，点击【同步缺陷】后，ms中之前缺陷维护的优先级、标签、模块被清空，但是jira上这些数据还在

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#18369]
### MeterSphere 版本

2.1.0

### 使用外置数据库

否

### 问题描述

测试跟踪-缺陷管理，同步到 jira平台，点击【同步缺陷】后，ms中之前缺陷维护的优先级、标签、模块被清空，但是jira上这些数据还在

### 重现步骤

1、测试跟踪》缺陷管理》新建缺陷（缺陷是勾选使用 jira模板的）
2、缺陷维护标签、优先级、模块等》保存
3、点击同步缺陷

现象：ms中之前缺陷维护的优先级、标签、模块被清空，但是jira上这些数据还在

### 附加信息

![image](https://user-images.githubusercontent.com/86464217/194742943-b1604f32-5f90-4364-8f00-f90c57b24fd4.png)

**Comment by xulinde** [comment]
未复现该问题，请确认下：
1.自定义字段的类型和选项值是否和jira平台保持一致
2.API字段名是否正确
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/64065190/194789936-50d55519-d4bd-4411-a451-b39ce9b46aa0.png">

**Comment by minnn0306** [comment]
就不是自定义的，是项目管理那边勾选了使用 jira模板的，这俩是默认自带的

**Comment by xulinde** [comment]
> 就不是自定义的，是项目管理那边勾选了使用 jira模板的，这俩是默认自带的 ![image](https://user-images.githubusercontent.com/86464217/195556538-53071275-4a1c-4af8-90b3-352bd42d98de.png)

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/64065190/195579431-82b3bc34-19ca-4ef3-8065-41c8af40f2e1.png">
我用v2.2未复现，您升级下版本复测下
