### ISSUE TITLE
[BUG]功能用例，列表按评审结果筛选不生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18368]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

功能用例，列表按评审结果筛选不生效

### 重现步骤

功能用例，列表按评审——未通过，点击筛选列表数据无变化

### 期待的正确结果

按评审结果筛选生效

### 附加信息

<img width="940" alt="功能用例，列表按评审结果筛选不生效" src="https://user-images.githubusercontent.com/43202800/194741239-0a376ea3-e3d3-4b50-81ca-3eb401e34947.png">

**Comment by xulinde** [comment]
v2.3.0已修复～
