### ISSUE TITLE
[BUG]功能用例导出为excel用例,导出后乱序不是按照id排序

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18375]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

功能用例导出为excel用例,导出后乱序不是按照id排序

### 重现步骤

操作：功能用例列表，选择用例导出为excel， 导出后不是按照id排序的，列表乱序

### 期待的正确结果

按照id排序

### 附加信息

![dca2e9eff29e7704859b8c37380fe5d](https://user-images.githubusercontent.com/43202800/194804409-e698a916-c89b-4614-9331-a7dcc8848e1c.png)

**Comment by xhy12** [comment]
并且导入也是乱序的，希望研发能够优化

**Comment by xhy12** [comment]
![e3e2747e34a99ad0235ee717d7e2f54](https://user-images.githubusercontent.com/43202800/194833903-04f0edf2-1790-4202-8e0a-01c34257a490.png)
导入模块也不是按照excel 里面的排序展示的， 希望能够优化好减少工作量

**Comment by xhy12** [comment]
备注：1.20版本是可以按照 列表头排序后的顺序导出Excel  
           2.2版本现在 在有列表头排序的情况下和无排序的情况导出的Excel均为乱序

希望版本功能是统一的

**Comment by xulinde** [comment]
v2.3.0已优化～
