### ISSUE TITLE
[BUG] 【接口定义】-mock的后置脚本无法使用导入jar包

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#18371]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.1.1

### 使用外置数据库

否

### 问题描述

用maven打包jar包并导入到metersphere，在场景里用脚本调试通过，但是在mock的后置脚本无法使用导入jar包

### 重现步骤

1.上传jar包
2.进入接口自动化界面
3.创建场景
4.添加自定义脚本
5.将下面代码粘贴到脚本里，并调试通过
6.接口定义-编辑接口-mock设置-添加mock
7.设置请求参数
8.添加后置脚本，粘贴刚刚调试好的代码，并在body输出

### 期待的正确结果

1.后置脚本正常执行导入的jar包

### 相关日志输出

```shell
无
```

### 附加信息

1.上传jar包
![image](https://user-images.githubusercontent.com/45531073/194749483-d1017314-aebc-4970-bdf3-e5a033a015b5.png)
jar包
[xml2Json-1.0-SNAPSHOT.zip](https://github.com/metersphere/metersphere/files/9741233/xml2Json-1.0-SNAPSHOT.zip)

2.场景里调试代码
![image](https://user-images.githubusercontent.com/45531073/194749454-01bc163d-d3a1-4948-bed4-6ddd1066b9f7.png)
代码

[代码.txt](https://github.com/metersphere/metersphere/files/9741235/default.txt)

3.创建mock,添加后置脚本，将代码输出
![image](https://user-images.githubusercontent.com/45531073/194749729-39a2c713-5983-4269-af76-a8b36f95617c.png)
4.调式mock
![image](https://user-images.githubusercontent.com/45531073/194749992-8c2350a5-f461-4a20-8e1e-a760bb473c99.png)

5.接口脚本

[Metersphere_Api_ms自测 (3).zip](https://github.com/metersphere/metersphere/files/9741256/Metersphere_Api_ms.3.zip)

**Comment by zyyfit** [comment]
您好，mock的后置脚本里目前是不支持log打印的，我用你的脚本，去掉了log的内容，是可以正常获取到变量的
