### ISSUE TITLE
[FEATURE]原生Jmeter附件上传API默认选项报错误，但高级实现选择java选项 测试OK,MS平台该选项方案如何应对？

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#18370]
### MeterSphere 版本

1.20.15-lts

### 使用外置数据库

是

### 问题描述

[BUG]原生Jmeter附件上传API默认选项报错误，但高级实现选择java选项 测试OK,MS平台正对改选项方案如何应对？
![image](https://user-images.githubusercontent.com/82088551/194749685-eb032068-7c97-4b5c-b1a1-40e3b18827b3.png)
MS平台默认对应的原生Jmeter默认选项   （客户端实现：可选的有java和httpclient4，默认为httpclient4.）
![image](https://user-images.githubusercontent.com/82088551/194749847-278b1f2c-2836-4da6-b9b8-f0550d11cb19.png)
![image](https://user-images.githubusercontent.com/82088551/194749740-a8d7aafe-ae3e-451d-a2e0-0e5916230040.png)

### 重现步骤

原生Jmeter附件上传API默认选项报错误，但高级实现选择java选项 测试OK,MS平台正对改选项方案如何应对？
[上传附件实例.zip](https://github.com/metersphere/metersphere/files/9741247/default.zip) jmx原始脚本参考
![image](https://user-images.githubusercontent.com/82088551/194749793-8cfebf74-c839-4fa6-b973-60cedeb25eca.png)

**Comment by luty2018** [comment]
这个选项我们可以在下个版本加一下。

**Comment by zhangzhaox** [comment]
> 这个选项我们可以在下个版本加一下。

yyds

**Comment by zhangzhaox** [comment]
> 考虑到目前HTTPclient4的覆盖范围是比Java更广的，想问下贵司的系统api为什么不支持HTTPclient4呢？ 我们在下个版本会处理导入的jmx文件中，如果实现方式是Java，则系统也用Java去发送请求，不要因此报错。但是页面上不增加这个选项。

这个解决方案也可以，公司的项目要五花八门，个别项目不支持，我也搞不清楚为啥会出现必须要选择java的原因，代码层面的差异我也不清楚，否则可反向研发部门提出要求
