### ISSUE TITLE
[BUG]首页用例责任人分布统计未纳入导入的用例数，数量有缺失

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#18374]
### 联系方式

交流群5王佳信

### MeterSphere 版本

版本:   v1.20.9-lts-8cf9990f

### 使用外置数据库

否

### 问题描述

1、想通过首页查看项目参与的测试人员编写的用例数量
2、查看项目视图首页右上角的统计结果

### 重现步骤

1、通过Excel导入的方式向指定项目导入案例
2、在MS中直接编写部分案例
3、查看首页展示

### 期待的正确结果

展示的结果应包含导入的用例

### 附加信息

![image](https://user-images.githubusercontent.com/46660929/194791927-0b32d24a-763e-4320-8fc5-3f4a203c28b9.png)

**Comment by xulinde** [comment]
使用v1.20.15-lts未复现该问题，建议您升级到最新版本
