### ISSUE TITLE
[BUG]生成测试数据功能，使用number类型参数进行造数时，参数类型变为string或interger格式

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#18382]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

在接口定义-TEST-请求体-json-Schema格式中，选择number类型参数，点击生成测试数据，查看参数类型变为string或interger格式，number参数造数功能失效

### 重现步骤

见问题描述

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/194820904-eb9c0424-e2ac-4d7b-a089-9ea820ff151a.png)
![image](https://user-images.githubusercontent.com/92150453/194821448-10ca24fa-0f26-4e8e-ac85-5b0e048a2943.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已修复。
