### ISSUE TITLE
[BUG]测试跟踪，功能用例详情页，关联需求，需求列表页展示的需求没有包含子需求，只有父需求（禅道的测试结果）

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18384]
### 联系方式

王进

### MeterSphere 版本

v1.20.14, cloud, v2.2

### 使用外置数据库

否

### 问题描述

测试跟踪，功能用例详情页，关联需求，需求列表页展示的需求没有包含子需求，只有父需求（禅道的测试结果）

### 重现步骤

1. 禅道需求和子需求截图如下：
![2257a59c97191612d127782ea4992c2](https://user-images.githubusercontent.com/76033005/194828340-5a0f47ae-1dd6-422e-94f7-110c59eff9ec.png)
2. 在MeterSphere测试跟踪，用例详情页，关联需求tab，查看需求：
![95b8e88546e3782dbf5477c98a9f447](https://user-images.githubusercontent.com/76033005/194828625-bea4056d-5347-46d0-bdf4-08b8943734f7.png)
4. 可以看到 子需求没有被关联过来。

### 期待的正确结果

子需求应该被同步过来，像jira里有story，然后一个story还可以拆分成多个story，也有类似层级需求。

**Comment by xulinde** [comment]
v1.20.17已修复～
