### ISSUE TITLE
[BUG]v1.20.12-lts升级到v2.2.0后降级到v1.20.13-lts mysql服务无法启动

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#18394]
### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

v1.20.12-lts升级到v2.2.0后降级到v1.20.13-lts mysql服务无法启动

### 重现步骤

1、v1.20.12-lts升级到v2.2.0
2、v2.2.0降级到v1.20.13-lts
3、检查服务健康状况，mysql服务无法正常启动

### 期待的正确结果

所有服务都能正常启动运行

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/194977027-62311aa5-592f-435c-b813-320a0ee69784.png)
![image](https://user-images.githubusercontent.com/5198427/194977105-551e9123-6e73-4d48-af84-61d9cc2634c0.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，1.20升级到v2.0以上版本时，有提示v2.2版本使用的是mysql8 ，1.20是mysql7。降级的话会失败。
建议再尝试升级到v2.2版本吧。

**Comment by youliyuan-fit2cloud** [comment]
> 从1.20升级到2.0想体验想新功能，现在想回到v1.2x的版本只能卸干净重装了么

很遗憾，是这样的。
升级到2.0之前，有做备份的话就最好了。
