### ISSUE TITLE
[BUG]性能测试完毕后运行按钮状态还高亮显示

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#184]
版本：v1.1.0

1.运行jmx脚本一分钟场景
2.过去一分钟还没有停止，按钮还在运行状态
![image](https://user-images.githubusercontent.com/43331464/88886203-83566680-d26c-11ea-9b9f-af479dfa5158.png)

**Comment by wangzhen-fit2cloud** [comment]
已在新版本中修复
