### ISSUE TITLE
[BUG] TCP协议的JMX脚本，导入MS系统请求类型不对

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#18408]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

TCP协议的JMX脚本，BinaryTCPClientImpl形式，导入MS系统请求类型变成TCPClientImpl形式

### 重现步骤

1.tcp协议的jmx文件是 BinaryTCPClientImpl形式
![image](https://user-images.githubusercontent.com/104960608/195024297-94de47dd-ca69-428e-a10b-429c5ed11b59.png)

2.导入到MS系统就变成TCPClientImpl形式
![image](https://user-images.githubusercontent.com/104960608/195024458-dde28319-36a5-4daa-b21c-ae212a836688.png)

3.脚本如下
[TCP测试.zip](https://github.com/metersphere/metersphere/files/9752223/TCP.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证
