### ISSUE TITLE
[BUG]TCP协议的JMX脚本，导入MS系统执行报500

### ISSUE THREAD

**Issue by summer-yang21** [metersphere/metersphere#18415]
### 联系方式

交流群42；启明-杨志民/邮箱：793628560@qq.com

### MeterSphere 版本

1.20.3-lts；2.1.0；1.20.15-lts

### 使用外置数据库

否

### 问题描述

TCP协议的JMX脚本，导入MS系统2.1.0和1.20.15-lts版本执行报错

### 重现步骤

1、jmeter运行
![image](https://user-images.githubusercontent.com/62558712/195037250-dbd7f8fd-ce29-44dd-bc5f-fec483224286.png)
![image](https://user-images.githubusercontent.com/62558712/195037313-2b20d341-dbc6-4751-9647-8f36812d5bc7.png)
2、1.20.3-lts版本执行JMX脚本成功
![image](https://user-images.githubusercontent.com/62558712/195036426-2e78f67e-33d7-4b35-861b-58ddb1573da3.png)
3、2.1.0和1.20.15-lts版本执行JMX脚本报错500
![image](https://user-images.githubusercontent.com/62558712/195036521-1f51ec42-a7fe-4a65-8faa-cd0c00b317b1.png)
4、脚本如下：
[TCP测试.zip](https://github.com/metersphere/metersphere/files/9752935/TCP.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.3.0 和 1.20.16版本已经修复了这个问题，请等待版本发布后验证
