### ISSUE TITLE
[BUG]修改场景名称，新建版本后，场景页面卡死，一致转圈刷新不出来

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#18414]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

1.修改场景名称，新建版本后，场景页面卡死，一致转圈刷新不出来
![image](https://user-images.githubusercontent.com/103627487/195034010-fa6b6a34-4a93-407b-9da8-75267822deaa.png)

### 重现步骤

1.编辑场景，修改场景名称，新建版本(如果第一次修改能正常保存，再修改名称，新建版本，直到提示该场景存在多个版本，不允许修改场景名称）
![image](https://user-images.githubusercontent.com/103627487/195034858-44415b2f-780e-4576-8c18-fc8c2b0a6158.png)
![image](https://user-images.githubusercontent.com/103627487/195035034-6b746d46-35ca-457f-baa8-464cf8b617ba.png)

![image](https://user-images.githubusercontent.com/103627487/195034666-bd6c9727-5968-4eb5-9c18-36e6b784435a.png)

### 期待的正确结果

期望提示：该场景存在多版本，不允许修改名称，请新建接口，后页面不卡死，能正常操作页面

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.16已修复，请等待版本发布后验证
