### ISSUE TITLE
[BUG]功能用例模板，标签列带\,导入后编辑功能用例，用例名称和所属模块不显示

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#18427]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

1.功能用例模板，标签列带\,导入后编辑功能用例，用例名称和所属模块不显示
![img_v2_87bcf6a9-469f-4467-a71f-f38e5d9e051g](https://user-images.githubusercontent.com/103627487/195050637-48659b9d-a3d7-49a6-88a4-9a49caea4358.jpg)
![img_v2_c740ef81-cfff-4d2d-8545-2643e7213b3g](https://user-images.githubusercontent.com/103627487/195050677-9ce0d41e-ac6f-4809-98f1-28d51c0a4ffa.jpg)

### 重现步骤

1.下载功能用例模板，标签列加入\
2.功能用例导入，导入后编辑功能用例，查看功能用例名称和所属模块是否显示

### 期待的正确结果

能正常显示功能用例名称和所属模块

**Comment by xulinde** [comment]
v2.3.0已修复～
