### ISSUE TITLE
[BUG]ms 集成jira  提交缺陷使用jira的缺陷模板，字段的默认值未带出来

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18425]
### 联系方式

759590013@qq.com

### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

**ms 集成jira  提交缺陷使用jira的缺陷模板，字段的默认值未带出来**

在jira 里有为“描述”设置默认值内容
![截屏2022-10-11 下午4 56 39](https://user-images.githubusercontent.com/6245166/195045700-e9fd9f9b-f207-4ddb-abd2-ea4f31d61783.png)

在MS里创建时 却没有
![截屏2022-10-11 下午4 55 55](https://user-images.githubusercontent.com/6245166/195045533-bbca67af-7804-4f7e-b911-8040a4213203.png)

### 重现步骤

创建一次即可

**Comment by xulinde** [comment]
v2.7已修复
