### ISSUE TITLE
[QUESTION]使用过程中“接口数量统计-接口覆盖率”&“场景用例数量统计-接口覆盖率”的值统计异常低下ai

### ISSUE THREAD

**Issue by jiangrry** [metersphere/metersphere#18432]
### 请描述您的问题

在使用过程中，统计数据莫名其妙的降低，并且添加场景用例数量的情况下，覆盖率一直不能上涨。

**Comment by jiangrry** [comment]
![image](https://user-images.githubusercontent.com/6359046/195062136-0cd542fb-ee5d-4571-8f1c-4805ef833751.png)

![981d15649eea9cdeda500f5f1b48689](https://user-images.githubusercontent.com/6359046/195062372-a2dbc26c-e78e-4b35-a901-a164493815d4.png)

数据都很奇怪。统计比率都变成很低了

**Comment by luty2018** [comment]
是不是启用了版本功能？
你在哪个交流群，可以让同事协助你看看。

**Comment by jiangrry** [comment]
现在使用的是v1.20.12-lts-b3版本。
能提供协同支持？


蒋睿浩
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]使用过程中“接口数量统计-接口覆盖率”&amp;“场景用例数量统计-接口覆盖率”的值统计异常低下ai (Issue #18432)





 
是不是启用了版本功能？
 你在哪个交流群，可以让同事协助你看看。

**Comment by jiangrry** [comment]
我在14号交流群




蒋睿浩
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 中午11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]使用过程中“接口数量统计-接口覆盖率”&amp;“场景用例数量统计-接口覆盖率”的值统计异常低下ai (Issue #18432)





 
是不是启用了版本功能？
 你在哪个交流群，可以让同事协助你看看。

**Comment by luty2018** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/36292514/195525293-6b7a28f6-51f7-40ae-8094-a0f67143dcec.png">
原因如上述。
我们也会在2.0的版本里优化首页的统计策略
