### ISSUE TITLE
[BUG]接口列表》文档 右侧栏重叠

### ISSUE THREAD

**Issue by wang-qa** [metersphere/metersphere#1844]
**MeterSphere 版本**
1.8.1

**Bug 描述**
接口列表》文档 右侧栏重叠

**Bug 重现步骤**
1.  通过swagger 导入 大量接口
2. 右侧栏 文本重叠

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/58168764/113384345-686a6200-93b8-11eb-9c1c-547a31bf6c0e.png)

**Comment by xulinde** [comment]
没有复现该问题，建议您升级到最新版本再看下

**Comment by wang-qa** [comment]
![image](https://user-images.githubusercontent.com/58168764/113651669-ff8b2e80-96c4-11eb-9433-1ce90c9e6f6e.png)

v1.8.2-b4 最新版 复现
1. swagger 导入接口 （256个）
2. 点击 接口测试》接口定义（接口列表`api`页i）》接口定义（接口列表`文档`页i）

**Comment by xulinde** [comment]
已修复

**Comment by wang-qa** [comment]
![image](https://user-images.githubusercontent.com/58168764/118614471-5fabdf00-b7f2-11eb-8375-39e6b657b7e4.png)

https://user-images.githubusercontent.com/58168764/118614412-499e1e80-b7f2-11eb-8cc6-b56ccf80790b.mp4

复现步骤   该问题未修复
