### ISSUE TITLE
[FEATURE]表格筛选条件的配置

### ISSUE THREAD

**Issue by Bing-Wang-20161208** [metersphere/metersphere#18442]
### MeterSphere 版本

v1.20.12-lts-2297374a

### 请描述您的需求或者改进建议

缺陷管理：表头筛选可配置，例如：处理人可以使用多选下拉的方式进行筛选搜索
其他表格页面和字段都应该增加筛选的可能性，不管是在表头集成，或者是表格外搜索框

### 请描述你建议的实现方案

1.搜索功能的实现
2.每个字段的类型和搜索功能均可配置

**Comment by luty2018** [comment]
感谢建议。有这个规划，预计会在3个版本左右上线。
