### ISSUE TITLE
[BUG]定时清理性能测试报告没有生效

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#18454]
### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

定时清理性能测试报告没有生效

### 重现步骤

1、项目设置->应用管理->性能测试，启用设置-保留最近3个月报告
2、点击跳转到性能测试，检查3个月之前的性能测试报告，没有被及时清理

### 期待的正确结果

设置定期清理后能生效

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/195244424-0cf0979e-de8a-4e06-b693-e763a54afb0d.png)
![image](https://user-images.githubusercontent.com/5198427/195244466-ee0bcf61-2157-42b6-9afb-e142b71ede8b.png)

**Comment by xieqione** [comment]
昨天设置后没有生效，今天再次查看报告已经清理，想问下设置之后多久会生效？这里的逻辑是设置了定时任务每天某一个时间定点清理么？

**Comment by xulinde** [comment]
> 昨天设置后没有生效，今天再次查看报告已经清理，想问下设置之后多久会生效？这里的逻辑是设置了定时任务每天某一个时间定点清理么？
每天凌晨两点定时清理
