### ISSUE TITLE
[BUG]项目管理>>文件管理：这里上传了数据文件和jar包，因为还需要上传jar，但是发现无法上传，提示超过上线。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18474]
### MeterSphere 版本

V2.2

### 使用外置数据库

否

### 问题描述

[BUG]项目管理>>文件管理：这里上传了数据文件和jar包，因为还需要上传jar，但是发现无法上传，提示超过上线。
一个项目几十个场景，仅数据文件也不至10个啊。使用起来非常不便利，脚本因为无法上传jar而无法使用

### 重现步骤

[BUG]项目管理>>文件管理：这里上传了数据文件和jar包，因为还需要上传jar，但是发现无法上传，提示超过上线。
一个项目几十个场景，仅数据文件也不至10个啊。使用起来非常不便利，脚本因为无法上传jar而无法使用

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/195294854-9663e441-ccfd-4cc6-a059-517195beb7dc.png)

**Comment by xulinde** [comment]
v2.3.0已修复～
