### ISSUE TITLE
在场景中把jmx文件删除，加载jmx文件中依然存在此jmx[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1847]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  在场景配置中删除jmx，点击确定，点击保存
2. 点击加载jmx文件，发现删除的文件依然还在列表里
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
被删除的文件不应该存在
**截图**
![image](https://user-images.githubusercontent.com/80814232/113386841-a9b14080-93bd-11eb-8e07-2c12b8e85d77.png)

如果有截图，请附上截图.

**Comment by liuruibin** [comment]
在1.8版本中，同一个项目下的性能测试共享资源文件，编辑性能测试只是引用这些文件。想要删除上传的文件请在项目管理中操作。
