### ISSUE TITLE
[FEATURE]忘记密码了没办法登录

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#18472]
### MeterSphere 版本

v1.20.12-lts

### 请描述您的需求或者改进建议

1、一段时间不登录，忘记密码了，没有密码找回功能，希望提供忘记密码找回

**Comment by luty2018** [comment]
如果你是管理员请参考如下操作
https://metersphere.io/docs/v2.x/faq/installation/?h=%E5%BF%98%E8%AE%B0#26-metersphere
