### ISSUE TITLE
[BUG]缺陷管理与jira集成之后，经办人&报告人同步异常

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18471]
### 联系方式

759590013@qq.com

### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

背景：与jira集成，缺陷模板使用jira缺陷模板
问题描述：
问题1:创建缺陷 后 开发人员&测试人员 字段，在MS中显示正常，在jira中未显示（可选字段，相当于没有填），其它字段正常
问题2:在MS中点击同步缺陷，开发人员&测试人员 字段 被清空了，经办人&报告人被改成了 jira的用户编号，具体如图：

![截屏2022-10-12 下午4 27 18](https://user-images.githubusercontent.com/6245166/195291385-f567c76e-194e-44c2-86c1-577e2baf807b.png)

其中 开发人员&测试人员 为多选下拉列表、经办人&报告人为单选下拉列表

### 重现步骤

使用2.2 进行一次操作即可。
jira 版本：v8.6.0#806000-sha1:737bcc0

**Comment by xulinde** [comment]
未复现以上问题
问题1:请检查下开发人员&测试人员这两个字段的API字段、选项内容和ID是否和jira一致
问题2:经办人&报告人的ID获取方式如下图
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/64065190/195309584-0538aec4-9b49-4350-bf4a-f04a9a3978a5.png">

**Comment by zhangsai** [comment]
@xulinde 您好！我缺陷模板我未进行自定义，是“使用jira缺陷模板”。
  问题一中的开发人员&测试人员这两个字段的API字段、选项内容，都是系统自动生成的，应该是jira一致吧？

   问题二中 ，这个两个字段的ID，在“使用jira缺陷模板” 的情况下是要如何设置？
![截屏2022-10-12 下午6 08 17](https://user-images.githubusercontent.com/6245166/195315180-66a36e80-cc7f-4713-a22d-5512c9616772.png)

**Comment by zhangsai** [comment]
如果不“使用jira缺陷模板” 的话，使用起来就太不方便了，人员列表、还有一些其它字段的值需要jira&MS 中同时维护太痛苦了。

**Comment by zhangsai** [comment]
发现一个问题，我的jira 版本是8.6的，界面和你提供的不一样，这个有关系吗？你们支持的最好的jira版本是哪一个？

**Comment by xulinde** [comment]
> 发现一个问题，我的jira 版本是8.6的，界面和你提供的不一样，这个有关系吗？你们支持的最好的jira版本是哪一个？
> 
> 不好意思，问题一我描述有误，是新建的时候都是好的。是同步缺陷之后被清空了。其实和问题二是同一个问题。 点击同步缺陷之后，MS的开发人员、测试人员字段被清空，报告人、经办人显示成一个编号。JIRA中是正常的 @xulinde

这个应该jira版本没关系，您ms版本是最新的v2.2吗？我按您描述的步骤还是未能复现

**Comment by zhangsai** [comment]
> > 发现一个问题，我的jira 版本是8.6的，界面和你提供的不一样，这个有关系吗？你们支持的最好的jira版本是哪一个？
> > 不好意思，问题一我描述有误，是新建的时候都是好的。是同步缺陷之后被清空了。其实和问题二是同一个问题。 点击同步缺陷之后，MS的开发人员、测试人员字段被清空，报告人、经办人显示成一个编号。JIRA中是正常的 @xulinde
> 
> 这个应该jira版本没关系，您ms版本是最新的v2.2吗？我按您描述的步骤还是未能复现

你好，能加个微WX细聊一下吗？（WX:   sai-zhang）这个问题我现在可以必现


![截屏2022-10-14 上午11 18 20](https://user-images.githubusercontent.com/6245166/195754525-79492af5-2028-440f-b6dd-2c4626245d93.png)

![img_v2_7b2a0746-4f7f-4b6b-94f2-31ce03245f0g](https://user-images.githubusercontent.com/6245166/195754667-96380f2c-8b67-4f74-badb-582334a47a16.jpg)

**Comment by song-cc-rock** [comment]
@zhangsai 能否告知下Jira中开发人员及测试人员这两个自定义字段是使用那个类型呢, 如图示: 
![image](https://user-images.githubusercontent.com/40567414/197393084-0a6fde80-3469-4bb6-b402-8181f6d1fef8.png)

**Comment by zhangsai** [comment]
> 否告知下Jira中开发人员及测试人员这两个自定义字段是使

字段类型 ：“用户选择器（多选）”

**Comment by song-cc-rock** [comment]
> 

好的, 我这边复现一下

**Comment by song-cc-rock** [comment]
> > 否告知下Jira中开发人员及测试人员这两个自定义字段是使
> > @song-cc-rock
> > 字段类型 ：“用户选择器（多选）”

好的谢谢, 我复现一下.

**Comment by zhangsai** [comment]
> > > 否告知下Jira中开发人员及测试人员这两个自定义字段是使
> > > @song-cc-rock
> > > 字段类型 ：“用户选择器（多选）”
> 
> 好的谢谢, 我复现一下.

这个bug fix 能放到2.3.0吗？

**Comment by xulinde** [comment]
> > > > 否告知下Jira中开发人员及测试人员这两个自定义字段是使
> > > > @song-cc-rock
> > > > 字段类型 ：“用户选择器（多选）”
> > 
> > 
> > 好的谢谢, 我复现一下.
> 
> 这个bug fix 能放到2.3.0吗？

是的，v2.3会修复～

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0以上版本已修复，建议升级到最新的v2.5.1～
