### ISSUE TITLE
[BUG] lisence 账号数量授权6个，实际账号6个没超过授权，但是页面提示超过

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18479]
### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

 lisence 账号数量授权6个，实际账号6个没超过授权，但是页面提示超过

推测为默认admin账号占用了名额看看能不能优化下

### 重现步骤

 lisence 账号数量授权6个，实际账号6个没超过授权，但是页面提示超过

### 附加信息

![de76642fe953b1e0b2f03d800b35a82](https://user-images.githubusercontent.com/43202800/195316034-9824e64f-59bd-4e73-9c6b-ee5e244c2312.png)

**Comment by xhy12** [comment]
期望：买的6个账号应该可以直接建6个账号，admin不占名额

**Comment by youliyuan-fit2cloud** [comment]
你好，admin账号是超级管理员，确实算一个用户。暂时没有计划修改当前设计。
admin账号可以修改姓名做下区分。
