### ISSUE TITLE
[BUG]UI自动化用例编辑页面，在步骤过多的情况下，进行刷新时，概率性出现步骤名称均显示为英文。

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#18480]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

UI自动化用例编辑页面，在步骤过多的情况下，进行刷新时，概率性出现步骤名称均显示为英文。

### 重现步骤

4C8G的MS服务器，导入IDE录制的UI脚本，点击刷新按钮

### 期待的正确结果

刷新是，各步骤名称显示保持不变

### 附加信息

![96732ebda6beccffa262257ab276956](https://user-images.githubusercontent.com/92150453/195318246-f13c2df8-3dce-44ce-833f-c1e9481fb985.jpg)
![4e47b4363c064bda3b71299fce9aa4e](https://user-images.githubusercontent.com/92150453/195318312-e1719fc7-8123-4f61-bb90-2f9a9e54e26d.jpg)

**Comment by zrfit** [comment]
您好，感谢您的反馈！多次尝试，暂时未复现该问题，后续会继续关注这个问题，如果后续复现会进行修复。
