### ISSUE TITLE
[BUG] 测试计划中点击api执行结果，未弹结果框，前端报错，过一会正常 [刚执行完多点必现]

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18486]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

测试计划中点击api执行结果，未弹结果框，前端报错，过一会正常
![image](https://user-images.githubusercontent.com/103925124/195326700-290c6c89-2757-4058-937c-a0ae339632ec.png)

### 重现步骤

**_1、测试计划加入 较多api或case
2、点击执行结果，有的未结果框会弹图片中红色报错
3、前端报错，接口正常【图片中可见接口返回的是等待，但是页面显示的是通过】
4、过差不多5分钟不到再点执行结果，不报错，正常弹出结果框_**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.17版本已修复，请等待版本发布后验证
