### ISSUE TITLE
性能测试选按迭代次数执行后，没有结果输出[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1848]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
性能测试选按迭代次数执行后，没有结果输出
**Bug 重现步骤**
1.  选择性能测试
2. 压力测试选择按迭代次数
3. 执行此接口
4. 发现请求统计，错误记录，日志详情均无输出

**期待的正确结果**
正确情况下应该是什么样的？
有结果产生
**截图**
![image](https://user-images.githubusercontent.com/80814232/113387188-5f7c8f00-93be-11eb-84f8-cc57682b044f.png)
![image](https://user-images.githubusercontent.com/80814232/113387205-6c00e780-93be-11eb-8502-fa15b2ada31d.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，可能是您并发用户太少导致结果没显示出来，我们后续版本会优化这个问题的

**Comment by zyyfit** [comment]
您好，1.9.0版本已优化这个问题，请升级后再试一下
