### ISSUE TITLE
[BUG]测试用例以脑图的模式修改了页面样式但是保存后查看不生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18481]
### MeterSphere 版本

2.2

### 使用外置数据库

否

### 问题描述

测试用例以脑图的模式修改了页面样式但是保存后查看不生效

### 重现步骤

1、测试跟踪-功能编写切换为脑图模式
2、选择样式修改当前脑图展示样式，保存
3、问题：切换成表格用例后 再次切换脑图保存的用例样式不生效

### 期待的正确结果

脑图展示保存过的样式

### 附加信息

<img width="924" alt="测试用例以脑图的模式修改了页面样式但是保存后查看不生效" src="https://user-images.githubusercontent.com/43202800/195318330-8abe7f8f-b771-44ad-8cd6-b4fbd3d9a955.png">

**Comment by xulinde** [comment]
跟产品确认，暂时没计划做。原因：用的第三方的东西，这些要实现的话存储难度比较大，加载样式可能会有性能问题
