### ISSUE TITLE
[BUG]性能测试：删除测试场景后，该测试场景关联的报告页面报错。

### ISSUE THREAD

**Issue by dugangandy** [metersphere/metersphere#185]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.1.0

**Bug 描述**
简要描述您碰到的问题
性能测试：删除测试场景后，该测试场景关联的报告页面报错。

**Bug 重现步骤**
1.  新建一个性能测试场景
2. 运行该性能测试场景，并生成了性能测试报告
3. 删除该性能测试场景
4. 重新打开该性能测试场景对应的性能测试报告

**期待的正确结果**
正确情况下应该是什么样的？
建议正常展示历史的性能测试报告，并给出提示该性能测试场景已经删除。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/13115769/88891879-80607380-d276-11ea-8daa-85d838001d7b.png)

**Comment by wangzhen-fit2cloud** [comment]
@shiziyuan9527 接口测试报告下拉列表里点击已删除的资源应该也会有这样的问题，统一处理下吧
