### ISSUE TITLE
[BUG]测试用例--打开脑图页面 会出现卡死的情况

### ISSUE THREAD

**Issue by liangweijie99** [metersphere/metersphere#1850]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.1

**Bug 描述**
简要描述您碰到的问题

测试用例--打开脑图页面 会出现卡死的情况

**Bug 重现步骤**
1.  打开测试跟踪菜单
2.  打开测试用例菜单
3. 切换到进入脑图页面
4. 

**期待的正确结果**
正确情况下应该是什么样的？

测试用例可以流畅地打开并用脑图的方式展示。

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/74578958/113388455-da46a980-93c0-11eb-9b6b-7991666f132e.png)

**Comment by xulinde** [comment]
大概有多少条用例

**Comment by liangweijie99** [comment]
648条

**Comment by zyyfit** [comment]
感谢反馈，这是因为用例较多，加载需要一定的时间，您可以点击等待稍等一会，我们会在后续版本优化页面加载速度的

**Comment by zyyfit** [comment]
1.10.2版本对这块功能进行了一次优化
