### ISSUE TITLE
[BUG]测试跟踪>>功能列表 +测试计划列表 和 接口测试>>接口列表 + 接口自动化列表：在这些列表页面，调整了列表的显示头信息，第二天在登录系统，列表头又恢复到默认显示顺序

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18505]
### MeterSphere 版本

V2.2

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>功能列表 +测试计划列表 和 接口测试>>接口列表 + 接口自动化列表：在这些列表页面，调整了列表的显示头信息，第二天在登录系统，列表头又恢复到默认显示顺序

### 重现步骤

[BUG]测试跟踪>>功能列表 +测试计划列表 和 接口测试>>接口列表 + 接口自动化列表：在这些列表页面，调整了列表的显示头信息，第二天在登录系统，列表头又恢复到默认显示顺序

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/195508323-c2e023e2-4e87-4350-9c33-3c6d5d8e54d6.png)
![image](https://user-images.githubusercontent.com/78218624/195508696-f15707f8-9b42-47cd-b232-b82700e821dd.png)

**Comment by xulinde** [comment]
使用v2.2未复现该问题，正常来说，重新登录或刷新浏览器都不会恢复默认顺序的，您那边是稳定复现吗？能再详细描述下步骤吗？

**Comment by huangxine** [comment]
比如第一天：接口自动化测试，列表中，表头的设置如下：全天使用都没有问题。
![image](https://user-images.githubusercontent.com/78218624/197525271-27293a88-4424-4dbc-801b-7a85fc99c2ca.png)
第二天登录系统，表头信息又被重新回复到默认表头信息了。

**Comment by xulinde** [comment]
仍然无法复现该问题
