### ISSUE TITLE
[BUG]从swagger导入到ms平台，enum类型会变成object类型，且值无法输入，描述也没有导入进来

### ISSUE THREAD

**Issue by a3436281** [metersphere/metersphere#18515]
### 联系方式

421486833@qq.com

### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

否

### 问题描述

如标题

### 重现步骤

1、选择url方式从swagger导入接口到ms平台（swagger中的接口包含enum类型的字段）
2、编辑case时没有对应的enum类型，且值无法输入，描述未导入进来

### 期待的正确结果

支持enum类型，描述可以正常导入

**Comment by zyyfit** [comment]
关于描述导入失败的问题，可以把接口swagger文件给我们一下吗

**Comment by zyyfit** [comment]
另外，
1、无法输入是因为object不支持当前节点输入，切换一下字段类型就可以输入了（string、number、integer、boolean都可以手动输入，object和array的根结点不允许输入，子节点如果不是object或array的话可以输入）
2、您是想要这里增加一个枚举类型吗？
![image](https://user-images.githubusercontent.com/73461316/195746881-23874a69-767e-48e7-9e2b-1a91f0d58bdf.png)
