### ISSUE TITLE
[BUG] 导入场景用例后，需要选择设置两个运行环境。

### ISSUE THREAD

**Issue by clobob** [metersphere/metersphere#18517]
### 联系方式

交流群5 奋窦[丽酉] douliyou@live.cn

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

从一个项目导出场景用例再导入另一个项目后，批量执行选择运行环境时需要选两个运行环境。

### 重现步骤

1. 项目A中选择场景用例以Metersphere格式导出，
2. 项目B中通过导入功能将步骤1中导出的json文件。
3. 项目B中选择批量执行刚导入的用例，选择运行环境，弹出选项有两个运行环境需要填写。

### 期待的正确结果

只需选择和配置一个运行环境

### 附加信息

![mmexport1665633868137](https://user-images.githubusercontent.com/10508051/195525720-17659321-e4c6-4adb-afdd-a1c4605397ef.jpg)

**Comment by zyyfit** [comment]
您好，我们目前的设计逻辑是这样的：
1、场景里如果是引用了接口用例，导出再导入其他场景后，会自动关联原始case（如果导入时使用的用户有原始case的权限），是不是因为这个原因，导入后这个场景就有两个项目接口了？如果是这样的话，是需要选择两个项目的环境的
2、关于环境不显示，如果没有项目权限，是不会显示项目相关信息的

**Comment by clobob** [comment]
1. 对于需要选择多个运行环境的设置不理解，因为新的项目需要设定运行环境，是否可以不关联原项目运行环境，感觉没有应用场景，既然有新的运行环境，原来的运行环境还留着，只是增加操作。
另：因为我做过多次项目导出导入(因项目接口不断删减)，会需要设定好多运行环境，所以感觉这个设定不合理。

**Comment by clobob** [comment]
目前我的应用场景可以使用环境组来减少多运行环境设置，但仍觉得目前的运行环境设定操作太多

**Comment by zyyfit** [comment]
> 1. 对于需要选择多个运行环境的设置不理解，因为新的项目需要设定运行环境，是否可以不关联原项目运行环境，感觉没有应用场景，既然有新的运行环境，原来的运行环境还留着，只是增加操作。
>    另：因为我做过多次项目导出导入(因项目接口不断删减)，会需要设定好多运行环境，所以感觉这个设定不合理。

1、如果不想关联以前的场景，可以在导入场景的时候，使用一个只有当前项目权限的账号进行操作，这样会自动在当前项目创建接口和用例并进行关联
2、运行环境如果不需要切换的话，选择一次就可以了，以后执行都会用已经保存的这个环境；如果有关于操作方面的优化建议或者意见，可以给我们提 FEATURE
