### ISSUE TITLE
接口定义前后置脚本支持beanshell前后置处理器

### ISSUE THREAD

**Issue by liwei512203** [metersphere/metersphere#18527]
### MeterSphere 版本

2.2.0

### 请描述您的需求或者改进建议

目前接口定义前后置处理器仅支持jsr233脚本，导致由平台接口转化成性能脚本后对压力机性能造成较大的损耗，目前性能测试人员大部分使用的是beanshell前后置处理器

**Comment by luty2018** [comment]
这个可以做，已纳入规划。
