### ISSUE TITLE
对于上传的jmeter脚本，如果带有jmeter镜像不支持的组件，会解析报错

### ISSUE THREAD

**Issue by liwei512203** [metersphere/metersphere#18528]
### MeterSphere 版本

2.2.0

### 请描述您的需求或者改进建议

对于存量脚本的上传，建议新增一个jmeter组件过滤器，对于ms平台jmeter执行镜像不支持的组件，转化成jmeter脚本是直接忽略掉，否则会报错jmeter解析失败

**Comment by luty2018** [comment]
这个我们支持不了，范围太大。

**Comment by liwei512203** [comment]
提供一种方案，做成数据库动态配置需要过滤的组件，参考如附件图片



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月22日(周二) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] 对于上传的jmeter脚本，如果带有jmeter镜像不支持的组件，会解析报错 (Issue #18528)




 
这个我们支持不了，范围太大。
