### ISSUE TITLE
[BUG]UI测试直接选择元素对象提取不到元素属性值

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#18539]
### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

UI测试直接选择元素对象提取不到元素属性值。
问题截图：
![问题描述](https://user-images.githubusercontent.com/55130444/195574945-bb2c1503-76a3-4aae-b9d3-b77b0efd2ce3.jpg)

### 重现步骤

1.UI测试元素库中创建好元素
2.创建场景，后置操作中添加提取参数，
3.选择提取元素信息，选择元素属性，点击添加
4.直接选择元素对象，选择创建好的元素，提取该元素有的属性值。
![过程2](https://user-images.githubusercontent.com/55130444/195577468-2e4ded04-8dee-4b03-9bdb-87ddbc5e5297.jpg)

### 期待的正确结果

元素实际值：
![实际元素值](https://user-images.githubusercontent.com/55130444/195576585-2f34cc56-ba3a-44af-9414-dd1550089fa1.jpg)

期待结果为可以提取到属性值 value：百度一下
![期待结果](https://user-images.githubusercontent.com/55130444/195576216-75b1b405-76c2-47c0-9316-f8f531d5063f.jpg)

### 附加信息

1.先使用元素定位提取一次元素属性值之后，换成元素对象再次提取，可以完成提取属性值

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已修复。
