### ISSUE TITLE
[BUG]jsonpath校验时接口返回数组中的所有值时选择等于校验方式，结果异常

### ISSUE THREAD

**Issue by seveneven** [metersphere/metersphere#18534]
### 联系方式

1576094753@qq.com

### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

jsonpath校验时接口返回数组中的所有值时选择等于校验方式，校验结果异常

### 重现步骤

![image](https://user-images.githubusercontent.com/18522076/195568820-e822e68f-891e-48a2-8059-37c34bbf1ad1.png)

### 期待的正确结果

详细如重现步骤图片所示。从目前结果来看，选择等于和选择包含的结果是一致的。预期应该输出校验不通过。

**Comment by zyyfit** [comment]
您好，data[*] 这样写的话，是需要data里的每个terminal_os都等于 PICO 才会通过的

**Comment by zyyfit** [comment]
没有复现这个问题，可以把你的响应json贴上来一部分吗？
