### ISSUE TITLE
[BUG]测试计划中有下载接口，下载文件过大导致 sql 保存报错，接口状态未捕获住异常信息，导致测试计划一直是 Running，直到超时

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#18536]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.1.0

### 使用外置数据库

否

### 问题描述

1.测试计划中有下载的接口用例，下载文件较大，报 “max_allowed_packet” 异常，导致 下载接口执行中断，但是 该异常信息，测试计划报告 并没有捕获到，导致测试计划一直是 Running 状态，直到超时，应该及时 返回异常信息给测试计划，而不是一直等待。
![26eb9eaa7b62de3e213b60eda9d4394](https://user-images.githubusercontent.com/30038088/195571652-78fead69-9507-4e5c-b8c5-047e24e74184.jpg)
![19cd4a9dbdbb46b9bb1c68e1aa111b2](https://user-images.githubusercontent.com/30038088/195573823-5e3bcd38-e8a1-466d-9c8a-509bee372606.png)

### 重现步骤

测试计划中关联一个下载接口用例，返回的响应结果较大时，超过 mysql  64M 时，（默认max_allowed_packet=64M），会有此问题。

### 期待的正确结果

建议将这种异常信息及时返回给测试计划，而不是一直等待。

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已修复。
