### ISSUE TITLE
返回结果包含[]的时候，断言结果不正确。

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#1854]
1.接口的返回结果为[123]
2. 预期：断言正确
3. 实际：断言结果显示不正确
![下载 (1)](https://user-images.githubusercontent.com/60743086/113389354-7ae99900-93c2-11eb-95e1-1b0c539ae736.png)
![下载](https://user-images.githubusercontent.com/60743086/113389388-88068800-93c2-11eb-82ea-bb6deeba05b6.png)

**Comment by xulinde** [comment]
没复现该问题，您可以升级最新版本再试下
![image](https://user-images.githubusercontent.com/64065190/113669457-6240f200-96e6-11eb-858a-2baf8cead20e.png)

**Comment by plateauandsp** [comment]
不是断言[]，而是断言xxxx: []这种类型
