### ISSUE TITLE
[FEATURE]Jenkins插件不能关联UI用例，希望支持

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#18547]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

jenkins插件-选择测试执行/输入测试名称，未能关联上项目中的UI用例，需补充

### 重现步骤

见问题描述

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/195755193-e01d01c5-b5a6-4450-b9a9-16063e5faf88.png)

**Comment by luty2018** [comment]
这个功能会在两个版本内支持。
