### ISSUE TITLE
[BUG]IDEA插件设置同步信息后，点击【test】按钮，验证通过后，设置的同步项目相关信息被更改。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#18558]
### MeterSphere 版本

V2.2

### 使用外置数据库

否

### 问题描述

[BUG]IDEA插件设置同步信息后，点击【test】按钮，验证通过后，设置的同步项目相关信息被更改。
idea插件版本为1.10

### 重现步骤

[BUG]IDEA插件设置同步信息后，点击【test】按钮，验证通过后，设置的同步项目相关信息被更改。
idea插件版本为1.10

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/195785799-a7d568a3-144c-4e85-b0b4-28f7ed48e185.png)
![1665731809090](https://user-images.githubusercontent.com/78218624/195785858-9b67e7ca-aa74-4255-ae4c-90dd29d0d9f1.jpg)
![1665731809098](https://user-images.githubusercontent.com/78218624/195785880-c9e12299-c5d3-4406-9d37-81927065cafb.jpg)
![1665731809105](https://user-images.githubusercontent.com/78218624/195785896-be66d984-ecf7-47f1-8994-7cf641ed16a0.jpg)

**Comment by zyyfit** [comment]
test按钮会测试链接是否成功，并且重新获取项目和模块信息，我们可以优化一下这个地方

**Comment by zyyfit** [comment]
idea插件 1.2.1 版本已修复
