### ISSUE TITLE
[BUG] 接口定义-请求参数选josn-schema--数据为integer类型参数为空-预览显示为0

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#18568]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

在接口定义里维护接口信息，请求参数为json报文，选json-schema维护字段的类型，当json里的字段类型为Integer且参数值未填，在预览显示值为0

### 重现步骤

1.进入接口定义界面
2.点击更多操作-创建接口
3.在接口界面维护接口信息，请求体选择json
4.切换成json-shchema维护字段的类型，将其中某一个字段类型改为Integer且不设置值
5.切换到预览界面，查看该字段值

### 期待的正确结果

json字段类型为Integer且值为设置，预览默认值显示为null

### 附加信息

1.维护接口信息
![image](https://user-images.githubusercontent.com/45531073/195802963-6cfd8056-2f9d-401c-b849-1d34b6e8f579.png)

2.预览
![image](https://user-images.githubusercontent.com/45531073/195802759-6c40b87f-d8fb-41dc-8d40-7df2691e3195.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
您好，这里我们考虑过后决定暂时不做处理，因为jsonschema设置了数据类型，显示为null的话这违背了计算机的基础知识

**Comment by 35plus** [comment]
ZYY，老师，目前客户这边的需求是 为空时默认为Null值。
