### ISSUE TITLE
[BUG]使用idea插件导入MS平台，会出现泛型对象打不开的情况

### ISSUE THREAD

**Issue by haipeng-fit2** [metersphere/metersphere#18560]
### 联系方式

haipeng.dong@fit2cloud.com
蓝卓

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

是

### 问题描述

使用metersphere-idea 1.1.0版本，导入到MS平台的泛型对象，缺少子节点。

### 重现步骤

目前只有通过idea导入出现这个问题，使用swagger，jmeter均正常。

### 附加信息

<img width="1436" alt="WeChat2b1b314c7843d4bb97bd2df25ed2470f" src="https://user-images.githubusercontent.com/81673899/195788571-29c011a2-199c-4928-bbb7-106f31769141.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，修改一下idea插件里的 object-deepth配置试试，改到最大
![image](https://user-images.githubusercontent.com/73461316/197105242-9f101b7b-595d-483f-9b0f-a9eae5d0c78e.png)

**Comment by haipeng-fit2** [comment]
收到，已找到原因并解决，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zyyfit ***@***.***&gt;
发送时间: 2022年10月21日 11:31
收件人: metersphere/metersphere ***@***.***&gt;
抄送: haipeng-fit2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]使用idea插件导入MS平台，会出现泛型对象打不开的情况 (Issue #18560)





 
您好，修改一下idea插件里的 object-deepth配置试试，改到最大
