### ISSUE TITLE
[BUG]项目管理上传jar包后，在本项目接口测试的前置脚本中，引用jar包执行报错，jar包没有生效。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#18579]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.2.0

### 使用外置数据库

是

### 问题描述

项目管理上传jar包后，在本项目接口测试的前置脚本中，引用jar包执行报错，jar包没有生效。

请求报文如下：
import com.test.test.TestCipher;
import java.util.*;
//import com.test.TestCipher;
import cn.hutool.json.JSONUtil;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import org.apache.commons.codec.binary.Base64;
String data= vars.get("appSecret");

log.info("----1-----"+data);

List cellphones = new ArrayList();

Map test1 = new HashMap();
test1.put("orderId","9");
test1.put("payTime",System.currentTimeMillis());
test1.put("payAmount","300");
test1.put("orderType","buy");
test1.put("startTime",System.currentTimeMillis());
test1.put("endTime",System.currentTimeMillis()+1000*60*60*24*100);
cellphones.add("86-18238899633");
Map test = new HashMap();
test.put("corporationName","退出081503");
test.put("corpId","TEST081503");
test.put("cellphones",cellphones);
test.put("logoutUrl","https://hose2019.feishu.cn/docx/doxcnhovQVNnfv5IRWRbuLYqBTd");
// test.put("order",test1);
String str = TestCipher.objConvertStr(test);
log.info(str);
// String str = JSON.toJSONString(test);
// log.info("----2-----{}",str);
String a= TestCipher.encrypt(str,data);
log.info("----2-----"+a);

vars.put("value", a);
String s= vars.get("value");

### 重现步骤

[jar包.zip](https://github.com/metersphere/metersphere/files/9784785/jar.zip)

### 期待的正确结果

jar包被引用后可以正常使用

### 相关日志输出

```shell
控制台报错信息如下：
2022-10-14 17:54:32 ERROR ThreadGroup 1-1 Problem in JSR223 script, JSR223PreProcessor
Sourced file: inline evaluation of: ``import com.test.test.TestCipher; import java.util.*; //import com.test.TestCiphe . . . '' : Typed variable declaration : Error in method invocation: Static method objConvertStr( java.util.HashMap ) not found in class'com.test.test.TestCipher' : at Line: 31 : in file: inline evaluation of: ``import com.test.test.TestCipher; import java.util.*; //import com.test.TestCiphe . . . '' : TestCipher .objConvertStr ( test ) 
 in inline evaluation of: ``import com.test.test.TestCipher; import java.util.*; //import com.test.TestCiphe . . . '' at line number 31
javax.script.ScriptException
```

**Comment by xulinde** [comment]
检查一下脚本和jar 文件是否有问题，放到jmeter 中依然执行不了的

**Comment by RoterLong** [comment]
问下 这个问题解决了嘛？

**Comment by yaoyi111** [comment]
>
在新版本中执行没有遇到问题
