### ISSUE TITLE
body里面是formdata格式无法成功，接口执行总是总是提示参数不存在

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#1857]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8.0？

**Bug 描述**
body里面是formdata格式无法成功，接口执行总是总是提示参数不存在

**Bug 重现步骤**
1.  接口中的body为formdata格式。post请求
2. 执行
3. 
4. 

**期待的正确结果**
接口能够正常运行

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能否具体描述一下您的请求信息和执行步骤呢？
![图片](https://user-images.githubusercontent.com/73461316/113803221-b0a9cb80-978e-11eb-905f-766911ed9be2.png)
