### ISSUE TITLE
[BUG]邮件报告模板内置变量值未生效

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#18571]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

邮件报告模板内置变量值未生效

1.20.15版本 plannedStartTime和plannedEndTime 未生效
2.2.0版本 stage、status、plannedStartTime、plannedEndTime、actualStartTime、actualEndTime、createTime、updateTime未生效

### 重现步骤

1.测试计划设置定时任务
2.消息通知选择为邮件发送，报告模板使用内置变量

### 期待的正确结果

1.接收邮件内容内置变量有值，并且值是准确的

### 附加信息

1.邮件模板如下
${operator}执行了接口自动化测试: ${name}
级别：P1
测试阶段：${stage}
标签：${tags}
通过率：${passRate}
描述：${description}
自动化测试报告：${planShareUrl}
测试计划执行时间:${plannedStartTime}
测试计划结束时间:${plannedEndTime}
2.收到的邮件内容

![df019d67981ceac5f90e6450116adbb](https://user-images.githubusercontent.com/45531073/195804195-98675bc4-589e-4998-9e61-1ce34ca4aca9.png)

**Comment by hao65103940** [comment]
![image](https://user-images.githubusercontent.com/33945037/196103072-f2b740e3-77a3-42e5-8cd7-f068eaecd057.png)

补充：如图所示。

**Comment by liushuneng** [comment]
1.升级到2.2.0版本部分变量仍然未生效
![image](https://user-images.githubusercontent.com/45531073/196110525-2b35f498-5d0f-4bd6-979f-8bf4ddfb046f.png)

**Comment by xulinde** [comment]
问题1：在v1.20.15-lts未复现，请检查下您模版字段是否配置正确
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/64065190/196116797-156f3b23-324f-4c5d-b7bb-df7fcbad0fbb.png">
问题2：在v2.2已复现，后续版本修复

**Comment by xulinde** [comment]
v2.3.0已修复～
