### ISSUE TITLE
场景无法批量复制

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#1858]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8.0？

**Bug 描述**
接口自动化场景无法批量复制

**Bug 重现步骤**
1.  sit环境包含多个文件夹，文件夹里面包含多个场景
2. 想批量复制文件夹下的场景到UAT
3. 
4. 

**期待的正确结果**
应该能够批量复制

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
收到，后面版本看能不能添加该功能

**Comment by xulinde** [comment]
v10.5已支持
