### ISSUE TITLE
[BUG]idea导入MS平台，path不完整

### ISSUE THREAD

**Issue by haipeng-fit2** [metersphere/metersphere#18581]
### 联系方式

haipeng.dong@fit2cloud.com  蓝卓

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

是

### 问题描述

路径不完整，只取了方法上的部分，并不会自动拼接完整的path，完整的应该是：/api/ops-manager/v1/supos/backup/bak

### 重现步骤

部分path 在controller中统一定义，当使用metersphere-idea 1.1.0的插件把path同步到MS平台上时，只会同步方法上的path，不会拼接controller中统一定义的部分

**Comment by zyyfit** [comment]
您好，您说的是这种情况吗？我导入是可以拼上完整path的
![image](https://user-images.githubusercontent.com/73461316/196081057-66fe31e3-41e0-4469-8e5d-3ca5239b29a0.png)

**Comment by haipeng-fit2** [comment]
是这个情况，但目前没有再没有复现出来，如有问题再反馈


------------------ 原始邮件 ------------------
发件人: zyyfit ***@***.***&gt;
发送时间: 2022年10月17日 11:14
收件人: metersphere/metersphere ***@***.***&gt;
抄送: haipeng-fit2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]idea导入MS平台，path不完整 (Issue #18581)





 
您好，您说的是这种情况吗？我导入是可以拼上完整path的

**Comment by zyyfit** [comment]
好的，那先关闭了
