### ISSUE TITLE
[FEATURE]【JIRA集成问题】在JIRA的集成中，使用JIRA的缺陷模板，创建BUG时，模板里面没有Sprint（计划）选项

### ISSUE THREAD

**Issue by junwei-liu** [metersphere/metersphere#18588]
### MeterSphere 版本

1.20.14

### 请描述您的需求或者改进建议

期望能够在1.20.16版本中，缺陷模板可以获取到JIRA的Sprint字段，这样方便在提交BUG后，开发人员在看板中激活的Sprint（计划）即可快速查询到自己的BUG。

### 请描述你建议的实现方案

目前不太清晰为什么会获取不到这个字段，如果在JIRA中手动配置其它字段，是可以同步到到。

### 附加信息

<img width="684" alt="image" src="https://user-images.githubusercontent.com/78710778/195878039-4720dac0-cd90-4097-a588-fb24971c3173.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/78710778/195878328-bf96c50c-0234-4740-978c-9f160edfcfa9.png">

**Comment by luty2018** [comment]
你是用的自动同步模板的功能吗？
麻烦提供你的模板配置页面
