### ISSUE TITLE
[BUG] Mock服务响应报文 MockJS函数不能生成动态数据

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#18621]
### 联系方式

群14-亲山留水

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/196087832-690856d2-bdde-4d8a-847b-c58fc580547b.png)
![image](https://user-images.githubusercontent.com/82088551/196087869-2476825b-8b24-4097-b2b1-ddf18413a307.png)
![image](https://user-images.githubusercontent.com/82088551/196087904-353c9639-9673-4e6a-8e01-4df80b6b2978.png)

表单模式和文本模式均未生效

### 重现步骤

创建mock条件响应，测试mock服务

### 期待的正确结果

MOCK服务响应配置 函数模拟生效生成动态数据

**Comment by zyyfit** [comment]
您好，我们的mock后置脚本和jmeter脚本是不一样的，这里现在不支持使用mockjs函数的

**Comment by zhangzhaox** [comment]
> 您好，我们的mock后置脚本和jmeter脚本是不一样的，这里现在不支持使用mockjs函数的

现在平台支持什么样形式的动态响应报文，不是标准的mockjs用法吗？

**Comment by zyyfit** [comment]
平台的mock服务和mockjs是两种不同的东西，mockjs是一种工具，mock服务是一个提供的虚拟服务。
mock服务的后置脚本目前支持groovy 和 python语言的脚本，暂时未将mockjs的功能集成进来

![image](https://user-images.githubusercontent.com/73461316/197742230-61f9cb7e-284b-4757-aef2-26901916ecde.png)

**Comment by zhangzhaox** [comment]
记得以前版本报文体哪里支持mockjs函数 生成动态响应报文的  记错了？

**Comment by zyyfit** [comment]
> 记得以前版本报文体哪里支持mockjs函数 生成动态响应报文的 记错了？

是的，之前也不支持的
