### ISSUE TITLE
[BUG]性能测试中文件上传有数量限制，删除文件后再上传还会提示超过数量限制

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18629]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

性能测试中文件上传有数量限制，删除文件后再上传还会提示超过数量限制，从项目管理-文件管理中上传文件是正常的
### 重现步骤

1.在性能测试中上传资源文件，最多只能添加9个
2.再次上传新的文件，会提示超过数量
![c3ffaa697bbb2c70b6020e167f79473](https://user-images.githubusercontent.com/88763608/196102670-5391ce41-a913-42aa-afe8-8db6dcbeab70.jpg)

3.将某个文件删除后只有8个文件，然后继续上传，还是提示超过数量限制
![73135191c64738ff73bcf935d9980c1](https://user-images.githubusercontent.com/88763608/196102688-4b749a3e-e6d3-46bd-87bf-914624c4b4cf.jpg)

4.从项目管理-文件管理中这个入口上传，可以继续正常上传
![4395a177ef4ad46c7448f2c759c5b64](https://user-images.githubusercontent.com/88763608/196102705-5915f131-9cf3-49b1-b70b-61f9db840aa3.jpg)
![d7d386a325eab56bbe75fabfeea2280](https://user-images.githubusercontent.com/88763608/196102714-9859fc1c-401e-4bba-ba68-a61e756a7b57.jpg)

### 期待的正确结果

1.性能测试资源文件文件上传这里包括了整个项目所有性能测试可能用到的资源文件，不应该有数量限制，9个数量限制是远远不够的。
2.项目管理-文件管理中上传文件，目前测出来文件数量限制是19个，19这个值也太少了，应该也是个bug
3.上面这两个地方都不应该把数量限制得太小

**Comment by xulinde** [comment]
一次最多能上传10个，刷新下页面又可以继续上传，这个后续版本可以优化下～

**Comment by xulinde** [comment]
v2.3.0已修复～

**Comment by linfengjjj** [comment]
已验证
