### ISSUE TITLE
[FEATURE]编辑项目-需求类型  字段为改为多选下拉框

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18632]
### MeterSphere 版本

V2.2.0

### 请描述您的需求或者改进建议

由于metersphere  的项目设置-编辑项目-需求类型  字段为单选的 导致 在与jira 集成时 ，将缺陷关联需求 无法匹配到一部分jira 的需求。
希望：
1.编辑项目-需求类型  字段为改为多选下拉框
![截屏2022-10-17 下午2 24 15](https://user-images.githubusercontent.com/6245166/196104373-0043e0d9-bf06-410e-97bb-7010ae9fabf7.png)

2.在测试用例与需求进行关联时，能通过jira 关键字进行搜索（现在无法显示）
![截屏2022-10-17 下午2 29 51](https://user-images.githubusercontent.com/6245166/196104556-11405e0d-7546-4d0f-b809-8e88b6b9665f.png)

**Comment by luty2018** [comment]
了解， 这个问题我们会在两个版本内修复
