### ISSUE TITLE
[BUG]用例列表的选择用例预览，“更改类型”选择“文本描述”显示为空

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18640]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

用例列表的选择用例预览，“更改类型”选择“文本描述”显示为空  （“步骤描述”时显示正常）
![截屏2022-10-17 下午5 36 09](https://user-images.githubusercontent.com/6245166/196143912-f72a4b11-a4fe-4d6a-8be5-10a57d94196b.png)
![截屏2022-10-17 下午5 36 26](https://user-images.githubusercontent.com/6245166/196143987-bc6b6ac3-3b41-43e4-a523-73309daf5043.png)

### 重现步骤

新建一个用例，进行一下预览

**Comment by luty2018** [comment]
这里不支持格式转换。
