### ISSUE TITLE
自定义数据库请求，如通过id查询时间，查询的时间与数据库中的时间不一致

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#1864]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8.0？

**Bug 描述**

自定义数据库请求，如通过id查询时间，查询的时间与数据库中的时间不一致
--

**Bug 重现步骤**
1.  meter平台的时间比正常时间晚了13个小时
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/60743086/113391672-78893e00-93c6-11eb-8ed1-148f7f10bfdb.png)

**Comment by zyyfit** [comment]
您好，是不是数据库时区设置的问题导致时间不对呢？
