### ISSUE TITLE
[BUG]保存场景、接口CASE时报错SQL error happened, please check logs 

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#18653]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.15

### 使用外置数据库

是

### 问题描述

这几天保存的时候，metersphere网页会出现一个toast，提示“SQL error happened, please check logs”，打开浏览器控制台，提示是 内部服务器错误。即使出现的toast是保存成功，也有一定的概率重新打开场景、接口CASE时，发现修改的数据并未修改成功，保存无效，由于数据丢失对于公司损害较大，以下是截图，如果有有用信息，请回复，谢谢。
![image](https://user-images.githubusercontent.com/31870788/196160298-4f5513e3-8d4d-4615-9521-1cb59620e817.png)
控制台的报错信息如下：
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
{
"data": {
"success": false,
"message": "SQL error happened, please check logs.",
"data": null
},
"status": 500,
"statusText": "Internal Server Error",
"headers": {
"connection": "keep-alive",
"content-encoding": "gzip",
"content-type": "application/json",
"date": "Mon, 10 Oct 2022 01:46:46 GMT",
"server": "nginx/1.20.2",
"transfer-encoding": "chunked"
},
"config": {
"url": "/api/module/list/f54622fc-6448-4e22-8361-8fa0ad41c599/HTTP",
"method": "get",
"headers": {
"Accept": "application/json, text/plain, /",
"CSRF-TOKEN": "TWq4ukVnODt3hhQ1XgkSeCVKID5l8NuMVNZCfZeThh4RAIduJT1wwMLsh1YCxUxKLxIXuTfoE0VOQdG/2SI/cVERrj3DOnGSwlRqtP51fDw=",
"WORKSPACE": "03054a2d-fd91-497e-8e40-2ad956a8a24c",
"PROJECT": "f54622fc-6448-4e22-8361-8fa0ad41c599"
},
"transformRequest": [
null
],
"transformResponse": [
null
],
"timeout": 0,
"withCredentials": true,
"xsrfCookieName": "XSRF-TOKEN",
"xsrfHeaderName": "X-XSRF-TOKEN",
"maxContentLength": -1,
"maxBodyLength": -1,
"transitional": {
"silentJSONParsing": true,
"forcedJSONParsing": true,
"clarifyTimeoutError": false
}
},
"request": {}
}

### 重现步骤

服务器的数据库连接并无问题。测试跟踪中的用例可以保存，但是接口中的CASE 和 场景无法保存，以及保存时时常出现“SQL error happened, please check logs”，F12打开浏览器控制器，提示错误码500。

上周有升级到v1.20.15，仍然存在该问题，不知道是不是软件bug，如果是服务器配置问题，应该都没法保存。如果需要环境或者远程控制，请留下企业微信，我可以配合。

**Comment by youliyuan-fit2cloud** [comment]
你好，升级导致的sql未执行成功。需要详细的log，然后我们看下具体是哪个sql失败。麻烦上传下报错时打印的相关log。

**Comment by Faerie1999** [comment]
[ms20221018.log](https://github.com/metersphere/metersphere/files/9808661/ms20221018.log)

**Comment by Faerie1999** [comment]
### SQL: insert into operating_log (id, project_id, oper_method,        create_user, oper_user, source_id,        oper_type, oper_module, oper_title,        oper_path, oper_time, oper_content,        oper_params)     values (?, ?, ?,        ?, ?, ?,        ?, ?, ?,        ?, ?, ?,        ?)
### Cause: java.sql.SQLException: No operations allowed after statement closed.


可能插入操作记录异常

**Comment by Faerie1999** [comment]
请看一下上面的日志文件，有更详细的记录。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为是数据库版本太低了。可以升级下数据库，或者参考下面链接改下连接池配置。
https://cloud.tencent.com/developer/article/1707872

**Comment by Faerie1999** [comment]
谢谢回复，目前数据库版本为5.7.33，已符合metersphere官方文档中的数据库版本为5.7的要求，请问是说mysql版本要升级到8.0吗？

**Comment by youliyuan-fit2cloud** [comment]
> 谢谢回复，目前数据库版本为5.7.33，已符合metersphere官方文档中的数据库版本为5.7的要求，请问是说mysql版本要升级到8.0吗？

不需要升级到mysql8.0，请先修改下连接池是否能修复该问题。

**Comment by Faerie1999** [comment]
![image](https://user-images.githubusercontent.com/31870788/196836487-7a887378-a143-4e86-b79f-cbc917b1e12c.png)
将最大连接数从2000改成10000，其他如上所示，但是当前问题并未解决。

**Comment by youliyuan-fit2cloud** [comment]
参考下面链接改下连接池配置。
https://cloud.tencent.com/developer/article/1707872

> ![image](https://user-images.githubusercontent.com/31870788/196836487-7a887378-a143-4e86-b79f-cbc917b1e12c.png) 将最大连接数从2000改成10000，其他如上所示，但是当前问题并未解决。

你改的不对吧。
参考下面链接改下连接池配置。
https://cloud.tencent.com/developer/article/1707872

**Comment by youliyuan-fit2cloud** [comment]
![Uploading image.png…]()
加我们同事企业微信沟通吧。方便快捷～

**Comment by Faerie1999** [comment]
好的，图挂了

**Comment by youliyuan-fit2cloud** [comment]
> 好的，图挂了

<img width="774" alt="image" src="https://user-images.githubusercontent.com/54612864/197146568-302f851a-fd19-423b-8d15-364598fc5d77.png">

**Comment by Faerie1999** [comment]
请问群里找哪一位负责人？

**Comment by youliyuan-fit2cloud** [comment]
> 请问群里找哪一位负责人？
交流群是多少？叫什么名字？我们找你吧。

**Comment by Faerie1999** [comment]
微信号: Jasmine-of-Lily

**Comment by youliyuan-fit2cloud** [comment]
经过企业微信沟通，问题已解决。
