### ISSUE TITLE
[BUG]测试计划执行中，报 redis 连接超时，导致测试计划一直是 Running 状态，建议优化 redis 连接配置和测试计划异常处理机制

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#18657]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.14-lts

### 使用外置数据库

否

### 问题描述

1. 测试计划 串行、本地 执行 ，出一直是 Running 的情况，且 最后一个执行完成的场景之后的场景都是 Waiting 状态
2. 查看后台日志报 Redis 连接超时
Redis server response timeout (3000 ms) occured after 0 retry attempts, is non-idempotent command: true. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (SETNX), params: [[-84, -19, 0, 5, 116, 0, 43, 83, 69, 82, ...], [-84, -19, 0, 5, 116, 0, 36, 54, 51, 52, ...]], channel: [id: 0x15c9e941, L:/172.30.10.4:50076 - R:10.50.101.81/10.50.101.81:6379]; nested exception is org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (3000 ms) occured after 0 retry attempts, is non-idempotent command: true. Increase nettyThreads and/or timeout settings. Try to define pingConnectionInterval setting. Command: (SETNX), params: [[-84, -19, 0, 5, 116, 0, 43, 83, 69, 82, ...], [-84, -19, 0, 5, 116, 0, 36, 54, 51, 52, ...]], channel: [id: 0x15c9e941, L:/[172.30.10.4:50076](http://172.30.10.4:50076/) - R:[10.50.101.81/10.50.101.81:6379](http://10.50.101.81/10.50.101.81:6379)]
3. redis 服务器配置：2c4g   
4. redis.conf 是默认配置

### 重现步骤

目前未定位到什么原因导致的 redis 连接超时，目前观察到现象是，大部分时间测试计划可正常执行，只是中间某一时刻
出现连接超时，之后 又恢复正常。
建议增加 重试次数 和 优化测试计划 异常处理机制。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.16-lts中已优化。
