### ISSUE TITLE
[FEATURE] 测试计划希望添加一个批量删除功能

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#18666]
### MeterSphere 版本

v2.2.0

### 请描述您的需求或者改进建议

测试计划希望添加一个批量删除功能。

![image](https://user-images.githubusercontent.com/33945037/196322908-1f762637-0abf-47b0-8662-0c182191eba0.png)

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/33945037/196322995-75b8693a-64a9-48a0-be8a-db1e8320ddb3.png)

测试计划希望添加一个批量删除功能。

**Comment by luty2018** [comment]
感谢建议，我们预计在两个版本内添加批量删除测试计划的功能
