### ISSUE TITLE
[BUG]idea中的项目可以正常编译打包运行，但是导出MeterSphere时报错 psiType is null

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18664]
### 联系方式

蒋林峰

### MeterSphere 版本

2.2.0

### 使用外置数据库

否

### 问题描述

idea中的项目可以正常编译打包运行，但是导出MeterSphere时报错 psiType is null
是客户那边出现了这个报错，然后我本地也找了一个项目，复现了这个报错
idea版本：2022.2
插件版本：1.1.0

### 重现步骤

1.在idea中打开附件中的项目源码，该项目可以正常运行的
![image](https://user-images.githubusercontent.com/88763608/196321140-cd32b6ac-8b9d-4c7b-bdad-b3a46bf400ae.png)

2.安装MeterSphere idea插件1.1.0版本
3.通过export to MeterSphere导出项目接口，页面弹出报错
![1666059181309](https://user-images.githubusercontent.com/88763608/196321029-1e2e4b2e-eec0-4d21-a89d-8bb1c3456b49.jpg)
4.这是idea.log截图
![image](https://user-images.githubusercontent.com/88763608/196321227-b5732aa5-96eb-4c63-b2a8-372102487346.png)

### 期待的正确结果

应该可以正常导出

附件中有项目源码，idea.log，操作视频

### 附加信息

[idea.log](https://github.com/metersphere/metersphere/files/9805859/idea.log)

https://user-images.githubusercontent.com/88763608/196321279-92922f12-cab7-4c72-b379-3f441bb9fb85.mp4

[SpringBootDemo-masterold.zip](https://github.com/metersphere/metersphere/files/9805864/SpringBootDemo-masterold.zip)

**Comment by zhangdahai112** [comment]
已经传了最新的插件，不会报错了
