### ISSUE TITLE
[BUG]接口请求体参数删除后，点击保存成功 ，JSON-SCHEMA模式下参数实际并没有删除成功

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#18661]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v1.20.15-lts&v2.2.0

### 使用外置数据库

否

### 问题描述

接口请求体参数删除后，点击保存成功 ，JSON-SCHEMA模式下参数实际并没有删除成功

### 重现步骤

1、接口请求体参数，json格式下删除最后参数，但是保留前一个参数后的，号点击保存（提示保存成功）
2、点击JSON-SCHEMA
3、可以看到参数并没有删除成功。

### 期待的正确结果

参数正常删除

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/196199734-5325aaea-8e90-4e6e-9422-3959bd8e46d5.png)
![image](https://user-images.githubusercontent.com/45786766/196199961-22d29ed4-ea33-4bd6-acd3-dec3c6b47fc5.png)
![image](https://user-images.githubusercontent.com/45786766/196200263-295784c5-294f-4a4b-9c82-0e436b49c96f.png)

**Comment by zyyfit** [comment]
1.20.16 和 2.3.0 版本已修复，请等待版本发布后验证
