### ISSUE TITLE
调试页面建议新开一个页面

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#1866]
**请描述您的需求或者改进建议.**
目前调试后，无法直接在原有的页面进行修改，需要关掉调试结果后才能修改。

**请描述你建议的实现方案**
调试页面建议新开一个页面

**Comment by xulinde** [comment]
可以全屏进行修改
![image](https://user-images.githubusercontent.com/64065190/113408685-60271c80-93e2-11eb-8a31-e4f46698bb9e.png)

**Comment by plateauandsp** [comment]
这边的意思是，接口自动化的调试采用新页面弹出，而不是覆盖在接口自动化编辑界面。最大化也也是覆盖的模式
