### ISSUE TITLE
[BUG]快捷调试添加参数多了以后，没做滚动条

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#18697]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

1.v2.2.0 快捷调试添加参数多了以后，没做滚动条
![image](https://user-images.githubusercontent.com/30038088/196381001-9cb7114f-34c6-47e9-a574-de009980aeac.png)
2.lts 版本是有的

### 重现步骤

1.接口列表-快捷调试，添加多个参数，没有滚动条，无法看到下面的参数

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证
