### ISSUE TITLE
[BUG]性能测试图表users包含小数，是怎么计算的？

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#187]
**MeterSphere 版本**
v1.1.0

users用户数应该是整数啊，图表是什么公式计算方式？
![image](https://user-images.githubusercontent.com/43331464/88989474-4b076480-d30e-11ea-9308-15db238423f9.png)

**Comment by liuruibin** [comment]
jmeter 出报告的时候使用double作为值的类型，这是个精度问题
