### ISSUE TITLE
对CSV文件取值时，始终从第三行开始（第一行是字段）

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#1870]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现您这个问题呢，能否描述一下具体复现步骤
