### ISSUE TITLE
[BUG] mock请求头中值带空格，返回体为空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#18704]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

mock请求头中值带空格，返回体为空

### 重现步骤
请求头值内容带空格
![image](https://user-images.githubusercontent.com/103925124/196397713-75837f08-80db-4a01-8a5c-f95c19db5917.png)
![d493295dcf0a547cc08405fe2492476](https://user-images.githubusercontent.com/103925124/197127143-1f910f60-70f3-4d89-8569-4be5a8a7fc86.png)
返回体为空
![3414361120efa7286fcb4556d0fb7ee](https://user-images.githubusercontent.com/103925124/197127157-d738f564-8cea-45ce-a874-81ec1c130754.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题
![image](https://user-images.githubusercontent.com/73461316/196848618-97c86a1d-9618-4246-821f-d77e5ede0992.png)

**Comment by zyyfit** [comment]
2.3.0版本已修复，请等待版本发布后验证
