### ISSUE TITLE
[FEATURE]性能测试相关的一些建议

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#18709]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

1. 进入页面：性能测试 -> 测试，建议此页面增加一列【场景描述】用来详细描述要测试的场景，毕竟测试名称能写的内容有限；
2. 
![image](https://user-images.githubusercontent.com/15868713/196411707-e0fd05ab-3a2d-48fc-aeed-b8ea0c88865a.png)
3. 测试脚本的高级配置页面，添加监控时，即使使用批量添加也还是需要手动再逐一添加需要监控的内容，比如 cpu，memory，disk 等，希望可以默认全都添加
4.  报告中监控详情页面，这里只能一台一台服务器查看监控结果，希望可以合并在一起查看
5. 增加测试报告的分析说明字段，方便分析报告之后做备注

**Comment by zhangzhaox** [comment]
自定义的监控指标的PSQL应该默认保存入库 供后续选择 而不是每次都需要自定义添加复制
