### ISSUE TITLE
[BUG]项目成员在无目录删除权限的情况下，误操作新增目录时，无法进行目录新增的回退操作，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#18711]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

项目成员在无目录删除权限的情况下，误操作新增目录时，无法进行目录新增的回退操作，建议优化

### 重现步骤

项目管理的权限设置中，目前尚未有针对目录的新增、删除权限，当该成员无用例的删除权限时，也间接没有目录的删除权限。导致若误操作进行了目录新增操作时，无法对新增的目录进行删除操作，只能输入名称进行保存。

建议能增加测试跟踪用例列表栏，目录的新增、删除权限控制。

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/196430769-30904c5b-3e6c-4caf-8807-a25f5064c9c0.png)

**Comment by sageonedream** [comment]
补充说明：
一般测试团队会限制部门人员的权限，但实际上我们的项目管理权限中，没有涉及到测试跟踪-用例目录的新增/删除权限，导致如果有人员在本身没有删除用例的权限时(会导致也没有删除目录的权限)，进行误操作新增了目录，但又没法取消这个新增目录的误操作(不填写时会提示输入模块名称，然后一直显示为空白，又没办法删除)

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
