### ISSUE TITLE
[BUG] 安装1.7.3报错

### ISSUE THREAD

**Issue by samz406** [metersphere/metersphere#1871]
[按照这个操作手册](https://metersphere.io/docs/installation/offline_installation/)

离线安装，没有修改配置，install.sh 后报错。

![image](https://user-images.githubusercontent.com/3055810/113393736-acb22e00-93c9-11eb-8c3e-15aee08cc976.png)

进入容器看了
![image](https://user-images.githubusercontent.com/3055810/113393631-83919d80-93c9-11eb-8a3f-1d9c59d36eb7.png)

**Comment by zyyfit** [comment]
您好，目前最新版本为v1.8.2，建议您使用最新版

**Comment by samz406** [comment]
最新版也是一样

**Comment by liuruibin** [comment]
执行命令是使用root用户吗

**Comment by samz406** [comment]
是的，最开始用的最新版本发现有问题，就用了老版本1.7试试，还是不得行，

**Comment by wangzhen-fit2cloud** [comment]
你好，这个问题应该是目录权限问题，在后续版本中增加了对目录权限的处理。
可以使用最新的 v1.10.1 安装。
