### ISSUE TITLE
功能用例无法按照功能列表表头的排序导出Excel文件，且导出的Excel文件无法重新排序

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#18726]
### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

目前我们公司在编写功能用例时会按照ID进行排序，ID是按照功能相互依赖关系来自定义设置的，我们不同项目上的人员平常会需要使用到execl文档来查看相关的用例，因此需要导出相应的Excel，在v1.20lst版本时可以进行正常导出，但是升级到v2.2.0后导出来的Excel就是乱序了，同时由于表格进行了拆分，无法使用excel的排序功能
功能用例截图：
<img width="1028" alt="截屏2022-10-19 下午2 46 59" src="https://user-images.githubusercontent.com/34637801/196616791-db73cde3-d0bc-44d2-a9b1-99d71e2ea9b3.png">
Excel表格截图：
<img width="1228" alt="截屏2022-10-19 下午2 48 17" src="https://user-images.githubusercontent.com/34637801/196617004-84bcc600-924a-4ee1-b5cb-72e9eb66d177.png">
Excel无法排序截图：
<img width="1027" alt="截屏2022-10-19 下午2 49 21" src="https://user-images.githubusercontent.com/34637801/196617204-92b79d24-9eb0-4611-85c4-73c37a9687ff.png">

### 重现步骤

1.进入功能测试用例表，点击“ID”列进行排序
2.勾选部分已排序的用例
3.批量导出，全选所有的导出项，导出格式选择"Excel"

### 期待的正确结果

1.能正确按照功能用例列表排序，导出excel

**Comment by xulinde** [comment]
排序问题v2.2.1已修复；excel无法排序不是我们的问题，解决不了
