### ISSUE TITLE
[BUG]UI测试，B场景复制的方式导入了A场景，在B场景里修改场景IP后，还是引用的A场景原来的IP

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#18743]
### 联系方式

张树彬

### MeterSphere 版本

1.20.15、2.2

### 使用外置数据库

否

### 问题描述

UI测试，B场景复制的方式导入了A场景，在B场景里修改场景IP后，还是引用的A场景原来的IP

### 重现步骤

1. A场景设置场景变量ip，在步骤中引用
2. 将A场景用复制的方式导入B场景
3. 在B场景中创建新的场景变量ip，重新在A场景步骤中引用
4. 执行时仍引用的A场景ip

### 期待的正确结果

场景导入其他场景中后，重新引用的场景变量应该更新生效，而不是仍引用之前的变量

### 附加信息

![7c1f630ac86482da8d2bb189ce8081e](https://user-images.githubusercontent.com/77324661/196665111-67ad7900-c491-45df-b8a6-ff6868daf1d7.png)
![b95877b86cf0f0c462c461dfae4c649](https://user-images.githubusercontent.com/77324661/196665110-9331ebb9-ddd2-443a-be89-4e152eca0f49.png)
![6116d03e1df7682f410583be1746847](https://user-images.githubusercontent.com/77324661/196665157-3dee0e22-7ed7-4b8f-b5fc-6743344f1b38.png)
![7aa7acef7a18c6c05678a5789453ee4](https://user-images.githubusercontent.com/77324661/196665608-a6b4e80f-b541-4a77-8ad6-cfda030578ab.png)

**Comment by zrfit** [comment]
您好，请确认下场景B复制场景A后，场景A是否取消了原场景变量设置，复制的场景是默认勾选原场景变量的，需要手动取消后才能引用当前场景的变量。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/197101173-5cac57bc-6f5d-4d7c-aec6-7085710ccb58.png">
