### ISSUE TITLE
[BUG]引用环境的自定义请求，在请求前插入了当前环境的环境配置

### ISSUE THREAD

**Issue by shiciki** [metersphere/metersphere#1875]
**MeterSphere 版本**
1.8.1

**Bug 描述**
引用环境的自定义请求，在请求前插入了当前环境的环境配置

**Bug 重现步骤**
1.  接口自动化，创建场景A，建立一个自定义请求，请求网址为 hostA/path
2. 建立场景B，配置环境域名为hostB， 引用场景A，
3. 运行场景B

**期待的正确结果**
请求网址为 hostA/path

**实际结果**
请求网址为 hostB/hostA/path

**Comment by zyyfit** [comment]
您好，1.8.2版本引用场景后不用再选环境了，您可以升级到1.8.2试一下
