### ISSUE TITLE
[FEATURE]与jira集成，新增“jira关键字”字段

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#18779]
### MeterSphere 版本

V2.2.0

### 请描述您的需求或者改进建议

与jira集成后，使用“jira缺陷模板” 
![截屏2022-10-20 下午3 22 37](https://user-images.githubusercontent.com/6245166/196882891-2fefc6f5-a31e-45a0-b79e-d1855405ec80.png)

1.在缺陷管理查询列表，增加显示一列“Jira 关键字”（例：YZT-3510），并且可以加一个链接，点击后跳转到 JIRA 平台查看详情
2.测试追踪-功能用例-用例列表  增加一列“关联的jiar需求”的标题

**Comment by luty2018** [comment]
我们已经在优化这部分的展示，预计在12月份上线
