### ISSUE TITLE
[QUESTION]请问下metersphere有自动生成用例功能吗？

### ISSUE THREAD

**Issue by TesterPi** [metersphere/metersphere#18798]
### 请描述您的问题

建立接口参数规则，比如是否必填，字段长度，类型等，然后将规则挂到接口上，接口根据规则自动生成测试用例以及对应的断言。请问下metersphere有这个功能吗？

**Comment by luty2018** [comment]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/36292514/197720342-4df2b4eb-1b40-4348-98cc-474a15d84c9e.png">
这个功能在我们企业版中已经提供， 也可以登录Cloud环境进行在线体验。

**Comment by TesterPi** [comment]
> <img alt="image" width="1473" src="https://user-images.githubusercontent.com/36292514/197720342-4df2b4eb-1b40-4348-98cc-474a15d84c9e.png">
> 
> 这个功能在我们企业版中已经提供， 也可以登录Cloud环境进行在线体验。

我的意思是能够自定义字段的规则，这个功能好像只是简单的做了参数的替换。
