### ISSUE TITLE
[BUG]性能测试都过了一天了还在启动starting

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#188]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.1.0
启动测试过去一天了，毫无反应，也不能取消更正，建议可以对运行的和这种异常的情况可以做停止操作；
现在是只要运行成功与否都无法停止操作。
![image](https://user-images.githubusercontent.com/43331464/89007459-5fae2180-d33b-11ea-9fd0-ff968551e59a.png)

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 您所使用的 MeterSphere 版本是？
> v1.1.0
> 启动测试过去一天了，毫无反应，也不能取消更正，建议可以对运行的和这种异常的情况可以做停止操作；
> 现在是只要运行成功与否都无法停止操作。
> ![image](https://user-images.githubusercontent.com/43331464/89007459-5fae2180-d33b-11ea-9fd0-ff968551e59a.png)
可以删除 或点击编辑进入报告内停止
