### ISSUE TITLE
[BUG]接口自动化导入har包后，不勾选引用环境，执行时还提示要选择运行环境

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#18808]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

接口自动化这边导入har，导入后默认是勾选了引用环境，如果不够选，他也不会展示完整的地址，然后执行时提示还要去配置环境
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/104493699/196933783-d48c14fd-9202-4369-8e30-2261adcbe88d.png">

### 重现步骤

1.在接口自动化导入har文件
2.去掉引用环境勾选，然后点击调试
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/104493699/196933783-d48c14fd-9202-4369-8e30-2261adcbe88d.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v2.3.0中已修复。
