### ISSUE TITLE
[BUG] 在另外一个项目引用，会移动Case

### ISSUE THREAD

**Issue by HughDong** [metersphere/metersphere#18802]
### MeterSphere 版本

2.1.1-96b84b46

### 使用外置数据库

是

### 问题描述

在B项目中，创建一个Case，创建一个C场景引用了这个Case
在A项目中，创建了另一个场景D，场景D引用了场景C，多运行几次后，这个Case就从B项目挪到了A项目中
在运行前有刷新场景

### 重现步骤

在B项目中，创建一个Case，创建一个C场景引用了这个Case
在A项目中，创建了另一个场景D，场景D引用了场景C，刷新场景，多运行几次

### 期待的正确结果

Case应该还是在B项目中

**Comment by zyyfit** [comment]
您好，没有复现这个问题，可以具体描述一下复现步骤吗？运行是指在场景编辑页面点调试，还是调试-生成报告，还是在场景列表里执行/批量执行？刷新是指在场景编辑页面点击保存按钮后的刷新按钮，还是点击浏览器的刷新按钮刷新整个页面？中间有没有什么其他操作？case项目改变了，是指在项目A新建了一个接口，然后case到这个接口下了，项目B中只剩接口没有case了吗？

**Comment by zyyfit** [comment]
还是没有复现，这个问题能稳定复现吗？能复现的话可以录个完整的操作视频上传一下，或者在我们的交流群里找工作人员沟通一下复现步骤
