### ISSUE TITLE
[FEATURE]功能测试用例模板支持添加全局自定义字段

### ISSUE THREAD

**Issue by ed6896** [metersphere/metersphere#18811]
### MeterSphere 版本

v2.1.0

### 请描述您的需求或者改进建议

当系统项目数量达到数十个时，若全部项目的功能测试用例模板需要统一添加一个自定义字段，此时需要逐一为每一个项目添加自定义字段，操作不方便且容易遗漏添加字段。

### 请描述你建议的实现方案

功能测试用例模板支持一键添加全局自定义字段

**Comment by luty2018** [comment]
我们会提供系统级别的自定义字段以及模板， 这个功能预计在6个版本左右的时间发布
