### ISSUE TITLE
[BUG]测试跟踪-测试用例，脑图用例的顺序和我xmind导入的顺序不一致

### ISSUE THREAD

**Issue by maxsteamedbread** [metersphere/metersphere#1882]
**MeterSphere 版本**
v1.8.0-21bf611d

**Bug 描述**
测试跟踪-测试用例，脑图用例的顺序和我xmind导入的顺序不一致

**Bug 重现步骤**
1.  测试跟踪-测试用例页面导入xmind用例
2. 查看用例-脑图模式

**期待的正确结果**
脑图的用例顺序与导入xmind的用例名称保持一致

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44501737/113410345-c95c5f00-93e5-11eb-9f56-0e10d5cfcd66.png)

![image](https://user-images.githubusercontent.com/44501737/113410383-dd07c580-93e5-11eb-80bd-ce1f3201bbbc.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本会优化这个问题

**Comment by xulinde** [comment]
1.9.0已优化
