### ISSUE TITLE
[QUESTION] 请问环境变量中，定义的变量、以及 Cookie 可以用后置脚本更新吗？

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1883]
**请描述您的问题.**
需求：接口定义模块需要先登录，再请求
类似 postman 的操作，可以把 Cookie 存起来，放在环境变量中；登录接口在后置脚本中更新这个值，就能达到请求的目的了。

![image](https://user-images.githubusercontent.com/11580681/113464289-17ad4480-945e-11eb-9097-f59c2718a2c9.png)

**Comment by xulinde** [comment]
可以

**Comment by jhong123** [comment]
> 可以

👍 可以举个例子吗

**Comment by jhong123** [comment]
补充：可以持久化存储吗？
