### ISSUE TITLE
[BUG]接口自动化场景，无法正确断言

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#18832]
### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

测试背景：
有一个接口自动化场景，测试步骤有90+，大部分步骤为同一个接口只是请求参数不同，均采用同一个JSONPATH断言，未使用其它控制器
问题现象：
在进行接口场景调试时，存在多个接口步骤无断言的情况如下图所示：
<img width="1207" alt="截屏2022-10-21 下午2 52 24" src="https://user-images.githubusercontent.com/34637801/197131715-7432d3a3-5122-4aae-aa80-d60c83f972f0.png">
<img width="1271" alt="截屏2022-10-21 下午2 54 09" src="https://user-images.githubusercontent.com/34637801/197131988-6682eb83-879f-44b9-9746-afc36d8dbd65.png">

### 重现步骤

1.准备一个接口自动化场景，测试步骤90+，大部分接口步骤为同一个接口，请求参数不一样，采用同一个断言规则，JSONPATH断言同一个参数
2.点击"调试"
注意：该问题无法稳定复现

**Comment by xulinde** [comment]
未复现该问题，方便把您的场景发下吗？
