### ISSUE TITLE
[BUG]英文语言下脑图文案出现中文

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18840]
### 联系方式

王进

### MeterSphere 版本

v1.20.15, cloud, v2.2

### 使用外置数据库

否

### 问题描述

英文语言下脑图文案出现中文

### 重现步骤

1. 脑图模式，右击鼠标，查看
<img width="566" alt="b2cb071ddcc6d5ad53b8f308831400c" src="https://user-images.githubusercontent.com/76033005/197147883-cf07a12f-be60-47b0-a5b0-40746bdf787c.png">
2. 创建评审邮件通知，有部分中文：

![f389d62c07dbc5a1256e90fb34b09e21_](https://user-images.githubusercontent.com/76033005/197149226-44378850-095f-4931-9c3c-e86f1dd2ca16.png)

**Comment by xulinde** [comment]
v1.20.16-lts已修复～
