### ISSUE TITLE
[BUG]APIfox导出的swagger3.0 接口定义文件，导入至MS平台时，请求体参数无法识别，均显示为空，请修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#18850]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

APIfox导出的swagger3.0 接口定义文件，导入至MS平台时，请求体参数无法识别，均显示为空，请修复

### 重现步骤

见问题描述和截图

### 附加信息

![1ab590bbe1c473b5ebad1857080d581](https://user-images.githubusercontent.com/92150453/197172463-2036f224-ef5b-4153-a2a7-64fc14e78204.png)
![5aa6dcf306dfa6c04cfcd48b9f2fcd6](https://user-images.githubusercontent.com/92150453/197172488-7e41ae3f-594c-4952-a606-088aeff735d0.jpg)

**Comment by zyyfit** [comment]
和这个bug重复了 ，2.3.0版本已解决，请等待版本发布后验证
https://github.com/metersphere/metersphere/issues/18381
