### ISSUE TITLE
[BUG]【接口自动化】不同环境中有同名的环境变量，并非使用指定环境的环境变量，而是使用同一个环境变量

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#18871]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

接口自动化，场景引用其他项目的接口，还有该项目的接口，如果不同环境中有同名的环境变量，并没有各自使用指定环境的环境变量，而是使用一样的环境变量
![image](https://user-images.githubusercontent.com/104960608/197436848-29de8a42-9ee1-4038-bcba-02d8cf9c84d4.png)

![image](https://user-images.githubusercontent.com/104960608/197436803-d16cd5e2-ea83-48ee-a3f1-ad5db9d0bd82.png)

### 重现步骤

1.在一个项目下添加【接口定义】的环境变量为test值为test_123456
![image](https://user-images.githubusercontent.com/104960608/197436240-5f5abcea-770f-4a22-9beb-b429dcc50aeb.png)
2.在另一个项目下添加【接口定义】的环境变量为test值为MeterSphere123456
![image](https://user-images.githubusercontent.com/104960608/197436577-2c82c930-59ff-40e5-9b9c-e4cb7c03c41e.png)
3.在【接口自动化】中将其都引入，选择对应的环境，打印环境变量test值都是一样的
![image](https://user-images.githubusercontent.com/104960608/197436848-29de8a42-9ee1-4038-bcba-02d8cf9c84d4.png)

![image](https://user-images.githubusercontent.com/104960608/197436803-d16cd5e2-ea83-48ee-a3f1-ad5db9d0bd82.png)

**Comment by zyyfit** [comment]
感谢反馈，我们的系统目前如果是在同一个场景里有同名变量，无法准确识别出来哪个变量应该使用哪个值，都是会使用同一个值的
