### ISSUE TITLE
[BUG]脑图创建用例，未添加用例标签，但点击保存后仍提示保存成功

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#18876]
### 联系方式

张树彬

### MeterSphere 版本

1.20.15lts

### 使用外置数据库

是

### 问题描述

脑图创建用例，未添加用例标签，但点击保存后仍提示保存成功，导致用例都白写了

### 重现步骤

1. 使用脑图创建新用例
2. 编写了用例信息，没加用例标签，但前置条件加了标签
3. 点击保存按钮，提示保存成功
4. 用例实际未保存成功

### 期待的正确结果

不添加用例标签无法创建用例没问题，但保存时应该给出正确提示，不要提示保存成功

**Comment by xulinde** [comment]
因为支持添加临时节点，用户不一定是要创建用例，提示保存成功是比较合理的
