### ISSUE TITLE
[QUESTION]V1.8.1在线安装zookeeper异常信息

### ISSUE THREAD

**Issue by chamilzr** [metersphere/metersphere#1887]
**请描述您的问题.**
在线安装V1.8.1，安装后
![msctl-status](https://user-images.githubusercontent.com/15024861/113509873-69eb8400-958a-11eb-8e48-12ad9daf6a87.png)
查看zookeeper日志，一直有warning刷屏
![zookeeper log](https://user-images.githubusercontent.com/15024861/113509895-8daeca00-958a-11eb-8c88-a1b229f50a8f.png)

**Comment by xulinde** [comment]
关下selinux 和防火墙，重启下docker试试

**Comment by chamilzr** [comment]
> 关下selinux 和防火墙，重启下docker试试

![image](https://user-images.githubusercontent.com/15024861/113686193-92de5700-96f9-11eb-91bb-a97d4ea7a1af.png)
都是关闭的，没有开启

**Comment by chamilzr** [comment]
![image](https://user-images.githubusercontent.com/15024861/113699773-9a592c80-9708-11eb-94df-15e2b5b6b7c3.png)
kafka日志信息，也没有什么异常
