### ISSUE TITLE
[BUG]rt渲染图和汇总数据中不匹配

### ISSUE THREAD

**Issue by colleen0911** [metersphere/metersphere#18870]
### 联系方式

交流群15&colleen

### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

![071565696e45d4eb258eade469d2467](https://user-images.githubusercontent.com/116532928/197436658-a2c5f895-0439-452b-a2e7-cd1b5af66783.jpg)

### 重现步骤

性能压测

### 期待的正确结果

渲染图和汇总数据展示一致

**Comment by xulinde** [comment]
您理解有误，图上是当前这段时间的平均响应时间；99% 是把所有请求响应时间从小到大排序，处于 99% 位置的那个响应时间
