### ISSUE TITLE
[BUG]工作空间下环境管理复制环境，导致复制后的环境HTTP请求头丢失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#18884]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.15-LTS

### 使用外置数据库

否

### 问题描述

系统设置->工作空间下的环境管理列表中，选择其中一个环境进行复制，原环境Http配置是有请求头的，复制后新环境的请求头丢失

### 重现步骤

1、切换到“系统设置”-》“工作空间”-》“环境管理”
2、选择具有HTTP请求头的环境进行复制
3、复制后，查看新环境的请求头是否和旧环境一样？是否丢失？

### 附加信息

源环境信息：
<img width="953" alt="image" src="https://user-images.githubusercontent.com/32027713/197446985-4fac4d6e-4f53-4945-9af5-f84b237fdea0.png">

复制的新环境：
<img width="957" alt="image" src="https://user-images.githubusercontent.com/32027713/197447029-f72b58d1-f029-4075-83a5-9b31fa805dc3.png">

**Comment by zyyfit** [comment]
1.20.16修复了这个问题，在系统设置-工作空间-环境列表复制环境时，禁止切换项目，和2.x版本保持一致，请等待版本发布后验证
