### ISSUE TITLE
[FEATURE]用例模板期望增加字段的自定义排序功能

### ISSUE THREAD

**Issue by colleen0911** [metersphere/metersphere#18889]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/116532928/197457244-4a174a66-a815-49fd-852f-84912b714314.png)

**Comment by luty2018** [comment]
感谢建议， 已规划需求。预计三个版本内上线
