### ISSUE TITLE
[BUG]UI自动化添加后置断言时，引用UI场景变量做校验失效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#18881]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

是

### 问题描述

UI自动化添加后置断言，用UI场景变量作为期望值进行断言校验时，场景变量值失效

### 重现步骤

1、创建UI场景
2、添加UI场景变量，字符串类型
3、场景步骤添加断言，用步骤2定义的场景变量作为期望值
4、执行

### 期待的正确结果

UI场景变量可以作为期望值被断言

### 附加信息

UI场景变量：
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/32027713/197444182-a23cbc8a-9776-47c0-bf54-809f2891d149.png">

定义断言：
![企业微信截图_1666579693495](https://user-images.githubusercontent.com/32027713/197444205-38386c24-157b-4aee-bfa2-019a6e1ac087.png)

执行结果：
![企业微信截图_16665798969460](https://user-images.githubusercontent.com/32027713/197444230-36f3daa9-de82-4d6e-8c59-a0b123dee01e.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，v2.3版本已修复该问题，版本发布后升级即可。

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
