### ISSUE TITLE
接口测试建议支持文件上传下载

### ISSUE THREAD

**Issue by kuanglei1986** [metersphere/metersphere#189]
**请描述您的需求或者改进建议.**
我们公司使用平台时，发现涉及文件上传的功能都无法发起请求，这个是项目开发中常用功能，建议优先排入开发计划

**请描述你建议的实现方案**
支持文件上传、下载的接口请求

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
