### ISSUE TITLE
[FEATURE] 测试用例部分功能优化建议。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#1890]
**请描述您的需求或者改进建议.**
版本 v1.8.2

1. 用例列表用例的“名称”字段目前默认显示的字太少，每次都需要手动把这一列拉长。如下图：
![图片](https://user-images.githubusercontent.com/44999044/113645094-d1075680-96b8-11eb-8637-649f031ceb5f.png)

2. 测试计划——测试用例，没有醒目的执行用例的入口。当前操作逻辑是点击用例本身是查看详情，点击“编辑”才是执行用例

3. 用例详情页优化，当前在用例评审过程中（投屏），评审的人看不见用例步骤写的是啥（前置条件与执行步骤占屏幕比例过小），还有在执行用例的过程中也一样看不清。

**请描述你建议的实现方案**

1. “名称”字段显示加长

2. 我觉得编辑的含义是编辑用例的主体或者上下文信息，而不是执行用例。固建议增加执行用例的入口，比如在列表前加一个“执行用例”的按钮，然后通过翻页的方式执行即可。

3. 我觉得用例详情应突出其主体，也就是用例本身（前置条件与执行步骤）。希望这个页面能够重新设计，考虑到多种评审场景（投屏，*线上演示：是否可以做成ppt演示——其他人屏幕跟着主讲人的操作自动变化，评审人也可评论）与执行场景，另外一定要突出用例主体内容，谢谢了。

**Comment by xulinde** [comment]
1和2后面可以优化
3下个版本会重构这个页面
