### ISSUE TITLE
[BUG]jmeter函数拼接在接口中引用是正常的，但是在脚本中会导致测试无法运行

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18909]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.15-lts

### 使用外置数据库

否

### 问题描述

jmeter函数拼接在接口中引用是正常的，但是在脚本中会导致测试无法运行

### 重现步骤

1.在第一个接口响应体中，提取列表变量name
![image](https://user-images.githubusercontent.com/88763608/197480427-53777073-185a-42f7-be85-aefcfe0359b0.png)

2.在第二个接口url中引用${__V(name_${__Random(1,${name_matchNr})})}是正常的，能引用到
![6d5ed9471093b9923f7db3bc9307dd6](https://user-images.githubusercontent.com/88763608/197480199-1581d160-33b0-429a-9dd1-b47028e06387.jpg)

3.把这个拼接函数放到第一个接口的后置脚本里,执行不了
![cbafa4a2d5514bcab826711d134f4cf](https://user-images.githubusercontent.com/88763608/197480221-70dd59ab-565b-4b9e-8f31-442f933610cc.jpg)

**Comment by zyyfit** [comment]
没有复现
![image](https://user-images.githubusercontent.com/73461316/197765835-66e59f2a-e61b-442f-8af4-4bd1a2227990.png)
![image](https://user-images.githubusercontent.com/73461316/197766018-e02b5516-5632-48ab-a728-371694a5e178.png)
![image](https://user-images.githubusercontent.com/73461316/197766069-8f5df69c-880e-4d0b-8329-41428cfe5146.png)

**Comment by linfengjjj** [comment]
我在QA环境里上传了一个场景，可以用这个环境复现，开了后置脚本就没法执行，关了就是正常的
















在 2022-10-25 19:51:36，"zyyfit" ***@***.***> 写道：

没有复现

**Comment by linfengjjj** [comment]
![image](https://user-images.githubusercontent.com/88763608/197923512-78d98528-ab4d-451d-8c4d-efba12d23b41.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by luty2018** [comment]
已修复，请确认问题是否还存在，如果存在请重新打开issue
