### ISSUE TITLE
[BUG]用例导入，按用例模板将必填字段填写完成，上传表格用例到ms报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#18910]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

测试跟踪:::用例导入，按用例模板将必填字段填写完成，上传表格用例到ms报错

### 重现步骤

按照用例模板导入 调整用例到用例平台，上传表格用例时报错

报错信息如图：### Error committing transaction. Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.TestCaseMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Column 'node_id' cannot be null ### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.TestCaseMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Column 'node_id' cannot be null

### 期待的正确结果

按模板填写后应该能正常导入

### 附加信息

[测试用例模版 (7).xlsx](https://github.com/metersphere/metersphere/files/9850083/7.xlsx)

**Comment by Andyguo5891** [comment]
![7441666750030_ pic](https://user-images.githubusercontent.com/46042812/197920859-0c47684e-255e-4adb-9888-b9521c90c9ae.jpg)
![7451666750089_ pic](https://user-images.githubusercontent.com/46042812/197920867-e2d5dc8b-67a0-4960-a1bc-d9b67670b99d.jpg)

原因还是因为在项目设置中关闭了「测试用例自定义ID」设置

**Comment by xhy12** [comment]
用户反馈删掉包含接口的内容即可导入成功，应该是规则冲突

![用户反馈删掉包含接口的内容即可导入成功，应该是规则冲突](https://user-images.githubusercontent.com/43202800/197924210-18b9bdfd-101d-4e7c-ae70-aa32f0270aff.png)

**Comment by xulinde** [comment]
v2.3.0已修复～
