### ISSUE TITLE
[BUG]测试计划-报告失败的接口右侧显示空白内容

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#18913]
### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

测试计划-报告失败的接口右侧显示空白内容（1480个接口定时任务跑，失败的10几个，部分失败的出现空白内容，无法排查失败哦原因。到接口测试-case那重新执行，成功的成功，失败的失败，都会返回结果）

### 重现步骤

1、测试跟踪--测试计划--报告
2、查看失败的用例
3、线上完全空白的内容

### 期待的正确结果

正确线上异常信息

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/197484729-9bebfa69-f027-4153-ac11-25f7fc37cfef.png)

**Comment by xulinde** [comment]
Console有报错信息吗？

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/199135864-8e411a87-0b2d-4f59-a6a6-81efc7e88993.png)

**Comment by xulinde** [comment]
定时任务是多久执行一次

**Comment by xulinde** [comment]
1.测试计划关联了1000+接口用例
2.测试计划设置定时任务，每10分钟执行一次
3.执行完查看测试报告-接口用例-失败用例，报告内容可以正常打开
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/64065190/199201566-b10ee7c5-785a-4e49-8202-d2428b72b9fc.png">

**Comment by legend818** [comment]
定时任务一天执行一次 1537个用例 不是所有的用例会出现这样 是部分用例会这样 失败的15个用例当中会有几个这样情况

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/199232304-ea37b4bd-dc2d-4936-abe4-7bc5f8b3fd8d.png)
每天晚上执行，第二天来，每天都有这样情况

**Comment by xulinde** [comment]
每次跑定时任务都会出现这种情况吗？把那十几个用例取消再跑试试呢？

**Comment by legend818** [comment]
每天定时跑都有这样情况，不是固定的接口出这种问题

**Comment by legend818** [comment]
升级到 2.2.1版本持续跟踪几天暂未发现问题

**Comment by xulinde** [comment]
> 升级到 2.2.1版本持续跟踪几天暂未发现问题
好的，如有问题再反馈
