### ISSUE TITLE
[BUG]文档结构校验，Jason文档结构校验，添加的校验内容和预期结果未被保存

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18930]
### 联系方式

王进

### MeterSphere 版本

v1.20.15, cloud, v2.2

### 使用外置数据库

否

### 问题描述

文档结构校验，Jason文档结构校验，添加的校验内容和预期结果未被保存

### 重现步骤

1. 创建一个接口自动化场景，添加一个请求，调试
2. 在断言规则那里添加文档结构断言，添加校验内容和预期结果，保存
3. 切换到别的步骤再回来，检查刚刚添加的断言，未被保存。

### 期待的正确结果

断言被保存

**Comment by zyyfit** [comment]
没有复现，请检查一下是否没有展开，如果不是这个问题的话，请详细描述一下操作步骤，或者上传一下可以复现的场景
![image](https://user-images.githubusercontent.com/73461316/197768163-de550ba5-299f-428c-ba4f-acf994da4f28.png)

**Comment by 35plus** [comment]
明白了，感谢
