### ISSUE TITLE
[BUG]设置定时任务时，点击减号，网站会崩馈

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#1896]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
设置定时任务时，点击减号，网站会崩馈
**Bug 重现步骤**
1.  打开定时间任务弹窗
2. 直接口点击页面的减号
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
不能点击时需要给出提示
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/80370956/113656874-5269e380-96cf-11eb-87da-b5acdd5d9dd1.png)
![image](https://user-images.githubusercontent.com/80370956/113656893-5c8be200-96cf-11eb-8710-93808dedf7c4.png)

**Comment by Evan-guo131** [comment]
定时任务页面bug

**Comment by jhong123** [comment]
+1

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
1.9.0已修复
