### ISSUE TITLE
[BUG]接口自动化执行的很慢，90多个接口要执行1个半小时 

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#1897]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
接口自动化执行的很慢，90多个接口要执行1个半小时 
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
实际接口响只有10几秒，建议不能相差太大

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
是批量执行多个场景吗

**Comment by fit2-zhao** [comment]
如果是单场景执行，1.检查一下是否有循环，等待组件等；2. 检查某个请求超时时间设置比较大 或返回内容太多；比如sql 请求，某个查询一次 查出几十万数据的情况；3 检查一下脚本 是否有 写的耗时的地方。
