### ISSUE TITLE
[BUG]场景调试某步骤卡在测试中，任务中心显示报告已经执行完，页面一直显示测试中

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#18990]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.14-lts

### 使用外置数据库

否

### 问题描述

1.场景调试某步骤卡在测试中，任务中心显示报告已经执行完，页面一直显示测试中
![1](https://user-images.githubusercontent.com/103627487/197668518-4a13cebb-5784-438d-9016-2eaa262823f3.png)
2.任务中心报告执行完成
![2](https://user-images.githubusercontent.com/103627487/197668638-3010ea65-3de9-4b54-84f8-a4e7d290f28e.png)
3.报告也可以正常点开
![3](https://user-images.githubusercontent.com/103627487/197668730-f30606d8-ee08-4809-811a-16b361de87d8.png)
4.点击停止场景调试,页面还是一直显示测试中
![4](https://user-images.githubusercontent.com/103627487/197668810-bb3398ca-9bba-40fb-9552-9cdaeb8aa445.png)
![5](https://user-images.githubusercontent.com/103627487/197669208-5a8db350-9fa3-4198-b827-6892f126575c.png)
5.任务中心的报告状态变为stoped
![6](https://user-images.githubusercontent.com/103627487/197669043-6f4a79e7-6697-435a-aab6-44ca982895c3.png)

### 重现步骤

1.目前本地未复现场景调试卡顿的问题，客户某场景出现的概率特别高（8/10）
2.场景调试与控制中心不同步问题仍然存在，同https://github.com/metersphere/metersphere/issues/17879
这个本地可以复现

**Comment by zyyfit** [comment]
您好，没有复现这个问题
