### ISSUE TITLE
[BUG]项目设置--模板管理--缺陷管理设置自定义字段有默认值，在创建缺陷没有显示设置好的默认值？

### ISSUE THREAD

**Issue by halydia** [metersphere/metersphere#18993]
### MeterSphere 版本

v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

项目设置--模板管理--缺陷管理设置自定义字段有默认值，在创建缺陷没有显示设置好的默认值？
![image](https://user-images.githubusercontent.com/38978791/197674376-b812e696-2484-45f1-9d38-ee7153a7e8da.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/38978791/197674450-c86eabd9-ef92-4a46-89a6-53dd74e4268d.png)

**Comment by xulinde** [comment]
v1.20.16-lts已修复～
