### ISSUE TITLE
[BUG]get方式的mock接口，不设置任何匹配条件时，响应体为空

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#18998]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

get方式的mock接口，不设置任何匹配条件时，响应体为空，实际上设置了mock的响应体

### 重现步骤

1.添加Mock接口，选择get方法，设置响应体，不设置匹配条件
![image](https://user-images.githubusercontent.com/88763608/197677096-117e0d02-45d9-467f-a7da-b4526acd7f05.png)
![image](https://user-images.githubusercontent.com/88763608/197677151-abeb080b-0b02-4fd1-91ba-51b7c49e5c9c.png)
2.调试mock接口，响应体为空
![image](https://user-images.githubusercontent.com/88763608/197677210-2112ef7a-fb97-486a-a56d-a59e1cd04245.png)

### 期待的正确结果

应该正常响应
1.换成post的类型是可以正常响应的，条件跟上面也一样
2.如果给上面的get接口添加一个请求触发条件，就能正常响应了；然后又把请求触发条件去掉，响应竟然也变正常了

**Comment by zyyfit** [comment]
请看一下是否mock期望的请求条件和接口定义的请求条件一样了，如果是一样的，并且接口定义里也没设置响应体的话，是会匹配到接口定义上的，这样会默认返回接口定义的响应体

**Comment by linfengjjj** [comment]
我的get  接口定义里没设置响应体，mock期望和接口定义都没有设置请求条件，mock设置了响应体，但是结果响应为空
我的post接口定义里没设置响应体，mock期望和接口定义都没有设置请求条件，mock设置了响应体，但是结果是响应了mock配置的响应体


就是同样都不设置请求条件，get没有响应体，post能正常响应
















在 2022-10-25 20:06:15，"zyyfit" ***@***.***> 写道：

请看一下是否mock期望的请求条件和接口定义的请求条件一样了，如果是一样的，并且接口定义里也没设置响应体的话，是会匹配到接口定义上的，这样会默认返回接口定义的响应体

**Comment by zyyfit** [comment]
麻烦你把你的这两个接口导出ms格式给我们看看吧

**Comment by linfengjjj** [comment]
> 麻烦你把你的这两个接口导出ms格式给我们看看吧

[get和post.zip](https://github.com/metersphere/metersphere/files/9900758/get.post.zip)
我录制了一个视频，这个视频应该很容易看出问题

**Comment by wuhenyan** [comment]
请问，你这边post接口是如何配置的呢，我尝试了很多方式配置post接口，请求均返回“No matching Mock expectation was found”

我这边只设置了一个mock的返回体
![image](https://user-images.githubusercontent.com/21330889/199489898-bcdf64b2-930c-4614-bbdf-8ea0be799128.png)
接口定义设置了一个响应体
![image](https://user-images.githubusercontent.com/21330889/199490038-da767a88-c226-4942-8361-9f031d52231a.png)
![image](https://user-images.githubusercontent.com/21330889/199490090-18a45c2d-e34c-4e1e-9609-2760d16026ea.png)

**Comment by linfengjjj** [comment]
> 请问，你这边post接口是如何配置的呢，我尝试了很多方式配置post接口，请求均返回“No matching Mock expectation was found”
> 
> 我这边只设置了一个mock的返回体 ![image](https://user-images.githubusercontent.com/21330889/199489898-bcdf64b2-930c-4614-bbdf-8ea0be799128.png) 接口定义设置了一个响应体 ![image](https://user-images.githubusercontent.com/21330889/199490038-da767a88-c226-4942-8361-9f031d52231a.png) ![image](https://user-images.githubusercontent.com/21330889/199490090-18a45c2d-e34c-4e1e-9609-2760d16026ea.png)

你可以看下我的附件视频，是怎么配置mock的

**Comment by zyyfit** [comment]
1.20.16 和 v2.2.1都已修复

**Comment by linfengjjj** [comment]
已验证
