### ISSUE TITLE
[FEATURE]一键安装脚本针对mac系统优化

### ISSUE THREAD

**Issue by heulizeyang** [metersphere/metersphere#19]
**请描述您的需求或者改进建议.**
mac操作系统用不了
离线安装包里面的install.sh问题也不少啊，优化下吧，照顾下mac用户

**请描述你建议的实现方案**
MSVERSION=$(curl -s https://github.com/metersphere/metersphere/releases/latest |grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+')

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈
