### ISSUE TITLE
[FEATURE] 环境变量可以批量修改

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#19047]
### MeterSphere 版本

1.20.15

### 请描述您的需求或者改进建议

测试环境有多个，有时候需要对多个环境添加，删除或修改相同的环境变量。因为没有全局变量，必须逐个环境文件修改，非常的低效！

### 请描述你建议的实现方案

可以同时修改多个环境的变量

**Comment by luty2018** [comment]
暂时还没有好的修改方案。也欢迎给我们建议一下。
