### ISSUE TITLE
[FEATURE] 接口测试界面-列宽不能调整导致编辑值的时候不方便

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19048]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

接口测试界面-请全体-jsonschema，编辑值的时候宽度不能调整，使用 jmeter 函数时编辑不方便。
比如一个极端特例，函数嵌套 
`${__property(skuSpecValue,,10)}${__property(unitName,,公斤)}/${__property(agriResMeterUnitName,,袋)}`

其实不是用 schema 模式就可以，但因为接口是swagger导入的，有每个字段的注释。非 schema 模式就看不到注释了。

### 请描述你建议的实现方案

期望可以自主调整列宽，如果输入框可以放大编辑就更好了。

### 附加信息
![image](https://user-images.githubusercontent.com/4860962/197734046-0032f406-4534-4277-b353-d2a7ffdea5bc.png)

_No response_

**Comment by luty2018** [comment]
感谢反馈， 已纳入优化。
