### ISSUE TITLE
[BUG] 用例管理中创建用例后，选择编辑，无法给用例添加测试步骤

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#1906]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8

**Bug 描述**
简要描述您碰到的问题
用例管理中创建用例后，选择编辑，无法给用例添加测试步骤

**Bug 重现步骤**
1.  进入测试用例管理页面
2. 在左侧模块管理部分，更多操作中选择新建用例
3. 在用例列表中，选择编辑刚才新建的用例
4. 在用例编辑页面中，无法添加用例测试步骤

**期待的正确结果**
正确情况下应该是什么样的？

**截图
<img width="1277" alt="Screen Shot 2021-04-06 at 3 51 24 PM" src="https://user-images.githubusercontent.com/9998431/113677521-404c6d00-96f0-11eb-8239-8dbbf83b3928.png">
<img width="1280" alt="Screen Shot 2021-04-06 at 3 51 36 PM" src="https://user-images.githubusercontent.com/9998431/113677544-480c1180-96f0-11eb-8f01-f8e79bbd7bad.png">
<img width="723" alt="Screen Shot 2021-04-06 at 3 54 04 PM" src="https://user-images.githubusercontent.com/9998431/113677592-54906a00-96f0-11eb-9c51-06f62a0e96cb.png">

**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们会尽快修复。您可以先这样创建用例
![image](https://user-images.githubusercontent.com/64065190/113695727-c7571080-9703-11eb-9967-3d2437c3f7e7.png)

**Comment by xulinde** [comment]
1.9.0已修复
