### ISSUE TITLE
[BUG][性能测试]压力配置页面启用 RPS，RPS 上限设置无效

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#19069]
### 联系方式

ke-liang

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

性能测试 -> 测试 -> 压力配置页面，启用 RPS，RPS 上限设置无效，设置的 3000，实际依然能达到 5000 多

### 重现步骤

性能测试 -> 测试 -> 压力配置页面，启用 RPS，RPS 上限设置无效，设置的 3000，实际依然能达到 5000 多

### 期待的正确结果

RPS 设置生效

**Comment by xulinde** [comment]
200 个用户，设置  RPS=3000，无此问题
<img width="684" alt="企业微信截图_59795760-2174-47dd-a03b-015081ce565d" src="https://user-images.githubusercontent.com/64065190/198562168-8a2ac95f-4926-4aaa-80cf-c91daae3bcf7.png">
