### ISSUE TITLE
[BUG]mysql数据库时间戳转换为日期格式时，空格显示为T，显示有误，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#19099]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

mysql数据库时间戳转换为日期格式时，空格显示为T，显示有误，请修改

### 重现步骤

sql语句通过UNIXTIME函数进行时间戳转换，显示的日期空格显示为T

### 附加信息

![1e508c567324ebd2cf5121e68c83ab1](https://user-images.githubusercontent.com/92150453/197943325-f7c5116f-ef81-4d07-93aa-45e38daaa946.jpg)
![cdbd25fdd474f72a0cca42d250bcc61](https://user-images.githubusercontent.com/92150453/197943336-ed2042f7-22a9-4fc9-b539-41cb8d0058b5.jpg)

**Comment by zyyfit** [comment]
您好，这个是因为我们使用的数据库连接驱动是8.0的，然后8.0的驱动jar包会有这个问题，5.x的版本没问题，所以这个是驱动的问题，暂时不处理了，然后如果需要正常格式的数据，可以使用下面这个格式化 sql 自己格式化一下
DATE_FORMAT(time, '%Y-%m-%d %H:%i:%s')

重复bug https://github.com/metersphere/metersphere/issues/17341
