### ISSUE TITLE
创建用户邮箱格式不支持带符号

### ISSUE THREAD

**Issue by paderlol** [metersphere/metersphere#191]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.3-b396
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/7919984/89157079-7b653200-d59e-11ea-8bb4-d30dbd8c1efd.png)
创建用户的时候,邮箱不支持带特殊符号,我们的企业邮箱是带有特殊符号的,这样导致我们无法创建邮箱
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.1.2 中解决
