### ISSUE TITLE
[BUG]jenkins构建执行测试计划后，未能收到邮件通知

### ISSUE THREAD

**Issue by wfx8989** [metersphere/metersphere#1911]
**MeterSphere 版本**
v1.8.1-13242356

**Bug 描述**
jenkins构建执行测试计划后，未能收到邮件通知

**Bug 重现步骤**
1、jenkins接口调用任务通知，收不到邮件（任务是正常执行通过的）
2、测试计划任务通知，可以收到邮件

以上两个收件箱都是同一个

**期待的正确结果**

能收到邮件通知

**截图**
![image](https://user-images.githubusercontent.com/68637962/113683847-3b3eec00-96f7-11eb-9ce8-d8dced5555eb.png)
![image](https://user-images.githubusercontent.com/68637962/113683868-4134cd00-96f7-11eb-9fb6-40589b8c0d1d.png)

**Comment by xulinde** [comment]
jenkins插件版本是多少呢

**Comment by wfx8989** [comment]
> jenkins插件版本是多少呢

1.7
![image](https://user-images.githubusercontent.com/68637962/113696292-63811780-9704-11eb-8635-912bb5d44543.png)

**Comment by zyyfit** [comment]
您好，最新版未复现这个问题，请升级到最新版1.10.0版本使用，请同时使用最新版插件
