### ISSUE TITLE
[BUG]test_plan_report表中的所有报告信息，update_time一直都等于create_time

### ISSUE THREAD

**Issue by awqinqing** [metersphere/metersphere#19138]
### 联系方式

awqinqing@foxmail.com

### MeterSphere 版本

v2.1.1

### 使用外置数据库

是

### 问题描述

test_plan_report 表中的update_time字段没有维护，当status字段更新后，update_time字段一直都等于create_time字段### 

### 重现步骤

test_plan_report表中的所有报告信息，update_time一直都等于create_time

### 期待的正确结果

期望test_plan_report.udapte_time字段的值自动可以随着test_plan_report.status字段值的更新而更新，当test_plan_report.status字段的值由running 变为FAILED时，test_plan_report.udapte_time的值更新为当前时间的时间戳

**Comment by xulinde** [comment]
未复现该问题，建议您升级到v2.2.0版本
![image](https://user-images.githubusercontent.com/64065190/198546311-3c59e46e-ed7e-46ab-b30b-a9927da7d436.png)
