### ISSUE TITLE
[BUG]接口自动化模块中，接口请求方式选择post后，执行时在请求内容中仍然以GET方式请求

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19137]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

接口自动化模块中，接口请求方式选择post后，执行时在请求内容中仍然以GET方式请求，2.2版本发现的，在1.20版本中测试无此问题。
<img width="640" alt="6056aa5bc43da3c8192cf4da40f4278" src="https://user-images.githubusercontent.com/83771182/197997453-60b17996-cfa9-4cf9-84d1-95549d0b5653.png">

### 重现步骤

接口自动化模块中，接口请求方式选择post后，执行时在请求内容中仍然以GET方式请求，可使用附件中脚本复现
[复现脚本.zip](https://github.com/metersphere/metersphere/files/9868360/default.zip)

### 期待的正确结果

接口请求方式选择post后，执行时在请求内容中也以post方式请求

**Comment by zyyfit** [comment]
您好，请问是不是这个接口会自动重定向？您把接口 - 其他设置 中的“跟随重定向”取消试试

**Comment by zyyfit** [comment]
另外，1.20和2.2版本表现不同，是因为1.20版本采用的jmeter5.4，2.2版本我们把jmeter升级到5.5版本了，这个问题是jmeter升级导致的，去掉接口 - 其他设置 中的“跟随重定向”选项后会返回跟1.20一样的 308 响应状态码
