### ISSUE TITLE
[QUESTION]本地Mac部署，ms-server服务一直restarting，起不来

### ISSUE THREAD

**Issue by Jason1227** [metersphere/metersphere#19134]
### 请描述您的问题

![1666776664354](https://user-images.githubusercontent.com/13938405/197991031-cd03c03f-fe22-48d2-b3d0-eebe5c9e0ffd.jpg)

**Comment by wan92hen** [comment]
请检查下 ms-server 容器挂载的卷是不是正常的，默认 linux 安装会将 /opt/metersphere/conf 挂载到容器中，mac 中应该是 ~/metersphere/conf
