### ISSUE TITLE
[BUG]  【接口测试】-【接口定义】-请求体由JSON-SCHEMA切换为json时，必填标识丢失

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#19133]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

   接口定义中，json数据切换到josn-schema维护字段必填项保存，切换成json再重新切换到josn-schema必填标识丢失

### 重现步骤

1.进入到接口测试-接口定义页面
2.进入接口编辑页面
3.将请求参数json数据切换成josn-schema模式维字段必填项并保存
4.切换成json再重新切换到josn-schema

### 期待的正确结果

切换成json再重新切换到josn-schema必填字段的信息要存在

### 附加信息

1.
![image](https://user-images.githubusercontent.com/45531073/197987151-19881f6d-49ea-4ca3-a945-2edd191ac184.png)
2.
![image](https://user-images.githubusercontent.com/45531073/197987853-737dd3a8-90b2-4af2-bd33-26c57d71a494.png)

**Comment by zyyfit** [comment]
您好，json字符串格式的数据转换为json-schema格式时，只是对json字符串进行转换，因为json字符串里是不带是否必填的标志的，所以用json转成json-schema后也是不带是否必填的标志的
