### ISSUE TITLE
[BUG]UI测试报告中未显示断言和提取参数信息

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#19143]
### 联系方式

张树彬

### MeterSphere 版本

1.20.15lts

### 使用外置数据库

否

### 问题描述

UI测试场景中，对步骤添加了提取和断言，但是在测试报告中未展现出来

### 重现步骤

1. 创建UI测试步骤
2. 设置数据提取和断言
3. 执行后，查看测试报告未显示相关信息

### 期待的正确结果

在UI测试报告中正常显示提取和断言信息

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/198004014-f9e71688-1296-48e7-8d82-efd6b85514ee.png)
![image](https://user-images.githubusercontent.com/77324661/198004145-6d4ad36e-d502-4988-ae4a-eebe908328e2.png)
![image](https://user-images.githubusercontent.com/77324661/198004253-e954b4a1-125f-4af2-9c36-3e391144ef94.png)
![image](https://user-images.githubusercontent.com/77324661/198004539-9a425229-049f-412c-9727-9adb5c041371.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.16-lts版本已修复。
