### ISSUE TITLE
[FEATURE] 场景用例可被标记为公共场景

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1917]
**请描述您的需求或者改进建议.**
场景用例可被标记为公共场景：
1. 公共场景不可设置场景变量；
2. 公共场景不可选择运行环境；
3. 公共场景不可调式；仅可作为一个片段被其他场景引用和复制。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by guhan121** [comment]
@xulinde 这个主要是为了防止；场景变量和场景参数会被复制到引用场景中去。
