### ISSUE TITLE
[BUG]UI测试后置操作设置断言执行后没有展示断言结果

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#19182]
### MeterSphere 版本

v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

1.使用UI测试，在后置操作中加入断言后，生成报告里断言结果没有展示。
2.报告里的步骤时间是错的。
<img width="1238" alt="1" src="https://user-images.githubusercontent.com/55130444/198202608-f9a9c0a1-1b59-4bfc-9667-28590c031f60.png">
<img width="1226" alt="2" src="https://user-images.githubusercontent.com/55130444/198202629-7b3b0987-dfd2-4f19-baa4-af28860ed155.png">

### 重现步骤

1.设置UI测试，选择步骤
2.后置操作增加断言，断言选择元素定位-元素文本期望等于（XXX）
3.生成报告，查看报告断言

### 期待的正确结果

1.后置操作能够使用断言，生成报告，可以在报告中查看到断言结果
2.步骤内的结束时间应该是正确。

### 附加信息

1.在v2.2.0版本是没有这个问题的，1.20.15版本存在这个问题。
<img width="1192" alt="3" src="https://user-images.githubusercontent.com/55130444/198203189-0c3a0384-89f5-40ce-9e60-7f592531e478.png">
<img width="1211" alt="4" src="https://user-images.githubusercontent.com/55130444/198203201-755af7ae-892e-4501-942c-ee680e8116dd.png">

**Comment by zrfit** [comment]
您好，感谢您的反馈！已知问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.16-lts版本已修复。
