### ISSUE TITLE
[BUG]v2.2，测试计划的测试报告，接口测试部分 失败用例tab页，如果有失败接口用例，用户无法跳转到具体的接口用例

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19196]
### 联系方式

王进

### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

v2.2，测试计划的测试报告，接口测试部分 失败用例tab页，如果有失败接口用例，用户无法跳转到具体的接口用例

### 重现步骤

1.  测试计划的测试报告，接口测试部分 失败用例tab页，如果有失败接口用例，用户无法跳转到具体的接口用例
2.  见下图
![1666855618347](https://user-images.githubusercontent.com/76033005/198219692-aa52d1ba-7da1-45d8-b3f1-9a956d792a71.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，目前在测试计划里面的接口用例报告不会跳转到接口测试模块。
