### ISSUE TITLE
[BUG]在系统设置--项目管理--创建项目中无法选择自定义的模板，但是默认项目却可以选择自定义的模板

### ISSUE THREAD

**Issue by halydia** [metersphere/metersphere#19191]
### MeterSphere 版本

 v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

切换到"默认工作空间"创建缺缺陷模板"禅道缺陷模板-自定义"之后，在系统设置--项目管理--创建项目中无法选择自定义的模板，但是默认项目却可以选择自定义的模板
![image](https://user-images.githubusercontent.com/38978791/198214928-4da2fea4-c1c7-4100-90ed-ede6d2e65cdb.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/38978791/198215097-7ee46e74-5c6a-4817-a6b1-1375cfbb4fc3.png)

### 期待的正确结果

应该都要能选择自定义模板才对

**Comment by xulinde** [comment]
模板是在默认项目下创建的，其他项目不能用
