### ISSUE TITLE
[BUG]用户发现shiro-core-1.9.0.jar版本依赖包存在安全风险 希望改用shiro-core-1.10.0.jar及以上版本的依赖包

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19197]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

用户发现shiro-core-1.9.0.jar版本依赖包存在安全风险 希望改用shiro-core-1.10.0.jar及以上版本的依赖包

### 重现步骤

![35cd7386371026b614c1e34b8af2ef8](https://user-images.githubusercontent.com/43202800/198219811-ed6b0708-9d75-4e4b-b9d6-246bed9372a7.jpg)
拉取最新项目，还是这个shiro-core-1.9.0

### 附加信息

![31fdfba261da65d51499659f5f1a692](https://user-images.githubusercontent.com/43202800/198219949-4471c043-14e3-43eb-b201-23442ecaba51.jpg)

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
