### ISSUE TITLE
[BUG]邮件通知里变量${stage}, ${description}, ${status},${actualStartTime},${actualEndTime}没有被替换

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19195]
### 联系方式

王进

### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

邮件通知里变量${stage}, ${description}, ${status},${actualStartTime},${actualEndTime}没有被替换

### 重现步骤

1. 创建定时任务通知，维护邮件通知内容和变量
2. 查看邮件通知，变量 ${stage}, ${description}, ${status},${actualStartTime},${actualEndTime}没有被实际值替换
![1666855387678](https://user-images.githubusercontent.com/76033005/198217745-54ae5aea-1d16-46f6-8d3c-6514793b3a20.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已解决。
