### ISSUE TITLE
[BUG]定时任务点击按钮报错

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#192]
**MeterSphere 版本**
v1.1.1-b462

**Bug 描述**
定时任务点击按钮报错

**截图**
![image](https://user-images.githubusercontent.com/30932762/89170014-a5741f80-d5b1-11ea-9fe4-3b4e9ccf366e.png)

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.1.2 中解决
