### ISSUE TITLE
[BUG] 接口定义，文档视图，接口定义（请求体）的一键展开、一键收起，没有将root下的head和body子项展开、收起

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19202]
### 联系方式

王进

### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

接口定义，文档视图，接口定义（请求体）的一键展开、一键收起，没有将root下的head和body子项展开、收起

### 重现步骤

1. 直接上图，见下图，已经点了一键展开，但是请求体里面的header和body里面的json字段没有展开
![1666856314042](https://user-images.githubusercontent.com/76033005/198220785-b02f2717-8ad4-4070-9e32-4996d68cea9f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
经过确认，这个地方的一键展开和收起不是针对json-schema的，是针对json-schame的高级设置的，如果有高级设置，才会展开，如果没有高级设置，就没有变化，如下图
![image](https://user-images.githubusercontent.com/73461316/198516886-fc3162e0-8c83-48e6-968a-49a22d4ada17.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
