### ISSUE TITLE
[BUG]设置某个接口mock后将该mock删除重新添加mock或者重新添加接口，请求均返回最初设置的mock返回

### ISSUE THREAD

**Issue by wuhenyan** [metersphere/metersphere#19229]
### 联系方式

13521081413微信

### MeterSphere 版本

v1.20.8-lts-hotfix-cabd3acc

### 使用外置数据库

是

### 问题描述

新建一个接口以及mock后调用返回mock结果成功
然后删掉了mock重新建了一个mock返回结果跟之前设置不同
再次请求mock返回的还是之前的mock数据
然后新建其他接口设置mock返回的依旧是之前的mock

### 重现步骤

新建一个接口以及mock后调用返回mock结果成功
然后删掉了mock重新建了一个mock返回结果跟之前设置不同
再次请求mock返回的还是之前的mock数据
然后新建其他接口设置mock返回的依旧是之前的mock

### 期待的正确结果

删除mock后重新设置或者新建其他接口应该返回新的mock数据

**Comment by zyyfit** [comment]
您好，最新版1.20.15没有复现这个问题，请升级后使用

**Comment by wuhenyan** [comment]
> 

您好，我用docker镜像最新版本还是1.20.8，并不是1.20.15呢，1.20.15的镜像是哪个呢？

**Comment by youliyuan-fit2cloud** [comment]
> > 
> 
> 您好，我用docker镜像最新版本还是1.20.8，并不是1.20.15呢，1.20.15的镜像是哪个呢？目前我看了下dockerhub中最新的就是1.20.8没有1.20.15
下载最新v1.20.15-lts的链接如下：
https://github.com/metersphere/metersphere/releases/tag/v1.20.15-lts

**Comment by wuhenyan** [comment]
> > > 
> > 
> > 
> > 您好，我用docker镜像最新版本还是1.20.8，并不是1.20.15呢，1.20.15的镜像是哪个呢？目前我看了下dockerhub中最新的就是1.20.8没有1.20.15
> > 下载最新v1.20.15-lts的链接如下：
> > https://github.com/metersphere/metersphere/releases/tag/v1.20.15-lts

谢谢回复，但是我目前是用的docker hub中自动拉取的，不支持手动拉取安装包部署，是否能将镜像推到dockerhub呢

**Comment by youliyuan-fit2cloud** [comment]
> 

就在阿里云仓库，可以手动pull最新的v1.20.15-lts 镜像，类似：
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/54612864/199379809-1640d79d-6d0a-4ba5-8840-f85272669480.png">

**Comment by wuhenyan** [comment]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/21330889/199472890-5946655a-fcf0-4d5a-abfc-5405fb9bb4ea.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/21330889/199472892-479c64cb-884a-4b14-9684-f047e4c498ba.png">
我重新部署了，但是设置mock以后一直请求不通了

**Comment by zyyfit** [comment]
这个看起来是网络的问题：This request could not be forwarded to the origin server or to any higher level cache servers.
