### ISSUE TITLE
[BUG] 测试计划设置失败重试，手动执行，还是只有一次，虽然失败，但没有重跑。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19228]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

测试计划设置失败重试为2，手动执行，执行失败的时候，并没有重新在跑一次。在任务列表中还是之后一次任务，并且在报告中也只能看到一次执行的报告。
![image](https://user-images.githubusercontent.com/33945037/198469519-5ff45433-84f0-44e9-ad56-1b22606ac3f4.png)
![image](https://user-images.githubusercontent.com/33945037/198469582-701101a3-a9b3-4e51-b8f5-a98190e3dc6b.png)

只执行了一次记录。

### 重现步骤

1. 测试计划设置失败重试次数。
2. 引入接口，然后手动执行测试计划。

查看报告即可

### 期待的正确结果

1. 应该有每一次的执行记录才对。

**Comment by xulinde** [comment]
v2.2.0未复现该问题，另外，重试几次，在任务中心是不会体现出来的
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/64065190/198549604-be18d8d1-7375-4e69-8c5f-bc4f473ac2f5.png">

**Comment by hao65103940** [comment]
这个问题最后排查出来了，是因为场景里面有断言，断言失败并不会重跑。

**Comment by xulinde** [comment]
断言失败正常来说会重跑，你那边有断言的场景都不没有重跑吗？
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/64065190/202111611-ded59e5d-7634-4fd5-bdd9-4689547c3e0c.png">

**Comment by hao65103940** [comment]
我模拟的场景是这样的：
接口请求是正确的，返回code码是200，但这个接口里面的断言报错，就没有自动重试了。重试次数是2.

![WX20221116-153030](https://user-images.githubusercontent.com/33945037/202115186-09ed638c-c7fd-40fa-b840-aad7f15e55ec.png)

**Comment by xulinde** [comment]
已复现，后续版本修复～

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
