### ISSUE TITLE
[FEATURE]强烈请愿！可以直接【链接】JIRA缺陷编号

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#1922]
请描述您的需求或者改进建议.
在功能或者接口测试 的执行页面，可以直接链接 既有的 JIRA 编号。

请描述你建议的实现方案
testlink中可以直接链接jira 现成的 编号，并可以输出到 缺陷报告中。谢谢

![image](https://user-images.githubusercontent.com/6467295/113795882-7802f580-9780-11eb-84b5-97bf43dfdf7c.png)

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by seasoncool** [comment]
@xulinde 
谢谢您的回复，这个功能对我们很重要。
因为有些缺陷是已经存在在JIRA系统里面了，我们需要引用它们的ID号码。

目前testlink里面，就有这个功能，只用输入 JIRA的projectKey+ID 就行了，（如：Test-123）

**Comment by t880216t** [comment]
自己实现了个，可以参考下。https://testerhome.com/topics/29702

**Comment by luty2018** [comment]
目前jira 已经插件化，可以自己添加这个效果。
