### ISSUE TITLE
[BUG]脚本中设置url变量，在请定义请求时，变量值会缺失

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19227]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.15-lts  v2.2.0

### 使用外置数据库

否

### 问题描述

脚本中设置url变量，url变量值较长，在请定义请求时，变量值会缺失。在jmeter中是正常的
![image](https://user-images.githubusercontent.com/88763608/198459800-ac3ae4cd-a228-4a3c-9938-0cd8c76cb4f7.png)
![image](https://user-images.githubusercontent.com/88763608/198460284-b9dba70a-be25-4589-8d76-f3fa3ee4a7d1.png)

### 重现步骤

1.在脚本中设置url变量
String url = "https://gy-test-1251891202.cos.ap-guangzhou.myqcloud.com/media/CRM-1666668451097_i210055cd541511edb8305254009bdbb7.m3u8?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDaWwf2nVtqV5p5qgzM9ml5jr41IJcJ2os%26q-sign-time%3D1666920953%3B1666926353%26q-key-time%3D1666920953%3B1666926353%26q-header-list%3Dhost%26q-url-param-list%3Dci-process%3Bexpires%26q-signature%3D0ba9c275f149de41bfa88760036c41e3b17d2a68&ci-process=pm3u8&expires=3600";
vars.put("requestUrl",url);
log.info(vars.get("requestUrl"));
2.在下一个请求的路径中引用${requestUrl}，结果实际请求时，路径缺失了一部分
![image](https://user-images.githubusercontent.com/88763608/198461916-feffd6a7-bafe-44db-a04e-625d754f69e7.png)
3.在Jmeter使用相同的操作，引用的时候路径是正常的
![image](https://user-images.githubusercontent.com/88763608/198462293-d298f75a-d8de-490e-93c4-100cd7d09324.png)
![image](https://user-images.githubusercontent.com/88763608/198462403-9e427715-1c7e-4bce-a1ac-1b8477baa176.png)

### 期待的正确结果

跟Jmeter保持一致

### 附加信息
[场景JMX文件集 (2).zip](https://github.com/metersphere/metersphere/files/9884583/JMX.2.zip)
[Metersphere_Scenario_MeterSphere 第二期演示项目 (3).zip](https://github.com/metersphere/metersphere/files/9884586/Metersphere_Scenario_MeterSphere.3.zip)
附件是复现的场景

_No response_

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.17 和 2.3.1 已修复，请等待版本发布后验证

**Comment by linfengjjj** [comment]
这个问题修复后带来了新的问题，https://github.com/metersphere/metersphere/issues/19701
