### ISSUE TITLE
[FEATURE]接口API视图下的显示的用例通过率依赖单接口用例的测试报告，建议修改为计算用例列表中的通过状态

### ISSUE THREAD

**Issue by chenfeng-fang** [metersphere/metersphere#19231]
### MeterSphere 版本

2.3.0

### 请描述您的需求或者改进建议

目前API下用例的通过率是依赖单接口执行生成的测试报告的，测试报告清理后，API原先100%用例通过率的就会变成0%。

如果查看该API用例列表的时候，可以看到用例上的执行结果是保留的（执行历史是关联测试报告的，会受影响，但这不要紧）

建议API的用例通过率不要受报告清理的影响。

**Comment by luty2018** [comment]
感谢反馈， 这个问题我们会在下一个版本修复。
