### ISSUE TITLE
[BUG]MeterSphere存在commons-text漏洞，请尽快修复

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19234]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.15-LTS

### 使用外置数据库

否

### 问题描述

Apache 在 lists.apache.org 网站上公布了 Apache Common Text 存在一个零日漏洞 CVE 2022 42889 ，版本在 1.5 到1.9 之间的 Apache Common Text 受到该零日漏洞的影响。Apache Commons Text是一个专注于处理字符串的算法的库。
MeterSphere当前用到的版本为commons-text-1.8.jar，请尽快修复

### 重现步骤

ms-server及node-controller等组件均涉及到此版本的库

**Comment by youliyuan-fit2cloud** [comment]
v2.2.1中已修复。
