### ISSUE TITLE
[BUG] 请求头缺失

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#19243]
### MeterSphere 版本

v1.20.5-lts

### 使用外置数据库

否

### 问题描述

在环境列表中，多个http请求的环境，配置一个https域名
使用此域名出现请求头缺失的情况

### 重现步骤

在环境列表中，多个http请求的环境，配置一个https域名
使用此域名出现请求头缺失的情况

### 附加信息

<img width="578" alt="image" src="https://user-images.githubusercontent.com/44996472/198522825-6dffc2c1-d476-4ea3-89fe-7405f6ea0fbe.png">

**Comment by xulinde** [comment]
v1.20.15-lts未复现，建议您升级到最新版本～
