### ISSUE TITLE
[FEATURE] 微服务拆分v2.3.0 版本，第一次进入之后，选择其它菜单，会有闪白的情况。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19266]
### MeterSphere 版本

v2.3.0

### 请描述您的需求或者改进建议

第一次登录之后，切换菜单，屏幕闪白。

https://user-images.githubusercontent.com/33945037/198538753-df05f1a8-94d0-4c2c-948e-3dee1ea7d448.mov

### 请描述你建议的实现方案

期望在登录的时候，把其他几个模块的链接缓存一下。

**Comment by luty2018** [comment]
感谢建议， 我们处理一下。
