### ISSUE TITLE
[BUG][性能测试]更新资源文件无效，删除后重新上传报错 “项目下该文件已经存在”

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#19269]
### 联系方式

ke-liang

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

升级到 2.3.0 之后，在性能测试的资源文件处更新已有 csv 文件无效，删除后更新报错 “项目下该文件已经存在”

### 重现步骤

1.从 2.2.0 升级到 2.3.0
2.在性能测试的资源文件处打开【加载文件】更新已有 csv 文件无效，文件名为 abcd.csv
3.删除 abcd.csv
4. 重新上传 abcd.csv，报错 “项目下该文件已经存在”

### 期待的正确结果

1. 可以更新资源文件
2. 删除后也可以重新上传

**Comment by xulinde** [comment]
已知问题，下个版本会修复～
