### ISSUE TITLE
[BUG]测试用例的导出和导入execl字段的值建议都用字段对应的text，避免用字段的value来显示和填写。如用例状态建议导出时显示的“未开始”，而不是“Prepare”

### ISSUE THREAD

**Issue by halydia** [metersphere/metersphere#19281]
### MeterSphere 版本

 v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

[BUG]测试用例的导出和导入execl字段的值建议都用字段对应的text，避免用字段的value来显示和填写。如用例状态建议导出时显示的“未开始”，而不是“Prepare”。
**另外能把执行结果的字段也导出来。**
![image](https://user-images.githubusercontent.com/38978791/198556060-edd16697-4c01-4d71-8800-9ba550342299.png)

### 重现步骤

见问题描述

**Comment by xulinde** [comment]
1.显示那个后续版本可以优化下
2.导出执行结果字段，v1.20还不支持，v2.2.0版本开始支持，您可以升级下
