### ISSUE TITLE
UI 测试元素断言未写断言断言内容，执行时提示不准确

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#19295]
### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

在进行UI测试时，在打开网页操作时，进行后置操作断言，选择元素断言的方式，只填写了断言方式未填写断言内容，执行UI用例时提示：“{'success':'false',message:null,data:null}”,提示不明确，不便于问题排查
断言设置：
<img width="1245" alt="截屏2022-10-30 上午9 23 04" src="https://user-images.githubusercontent.com/34637801/198858442-949b3d9a-5de9-4fd8-9ab7-3f458c06fd53.png">
执行时错误提示：
<img width="888" alt="截屏2022-10-30 上午9 23 42" src="https://user-images.githubusercontent.com/34637801/198858443-44b0a1cd-b139-4841-8d31-10ca9dd1a17b.png">

### 重现步骤

1.创建一个UI测试用例
2.在步骤中后置操作中创建一个后置断言
3.选择元素断言，且不填写具体断言内容
4.点击保存和执行

### 期待的正确结果

能正确提示“断言内容未填写”这样类似的提醒

**Comment by Hyyfit** [comment]
我们2.1的版本已经做了必填校验。1.20lts上是没有这个功能的，可以等下一个lts版本。
