### ISSUE TITLE
[BUG]2.2.0升级到2.3.0，手动执行测试计划报错

### ISSUE THREAD

**Issue by zhangchaolei** [metersphere/metersphere#19294]
### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

手动执行测试计划中的接口场景，出现接口报错如下

实际未影响测试计划执行

### 重现步骤

![image](https://user-images.githubusercontent.com/29458304/198818326-1848c66b-ddbe-40bd-bcd7-4d84889dd050.png)

### 期待的正确结果

不要出现报错

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，请详细描述复现步骤，然后补充下后台日志信息。
例如：
复现步骤：
1.测试计划-关联了接口场景用例 ？
2.在测试计划-接口场景用例列表中，手动点击执行单个场景 还是批量执行多个场景用例？
3.前端报错？然后查看后台日志并上传。

**Comment by zhangchaolei** [comment]
1.测试计划-关联了接口场景用例 ？-- 是的，关联了接口场景用例
2.在测试计划-接口场景用例列表中，手动点击执行单个场景 还是批量执行多个场景用例？ -- 测试计划列表页面，执行测试计划
3.前端报错？然后查看后台日志并上传。 -- task接口报错
![image](https://user-images.githubusercontent.com/29458304/198973238-29715328-7e8e-48a9-87fc-b57b2ff46932.png)

关键日志信息如下，提示缺少“metersphere.ui_scenario_report”：
![image](https://user-images.githubusercontent.com/29458304/198975337-4c3bed1e-a669-4ba5-b87d-68c70b993b76.png)

是否可提供SQL手动创表修复。谢谢。

**Comment by youliyuan-fit2cloud** [comment]
[ui-error.sql.zip](https://github.com/metersphere/metersphere/files/9899983/ui-error.sql.zip)
你好，请执行附件中的sql。

**Comment by youliyuan-fit2cloud** [comment]
[fix.sql.zip](https://github.com/metersphere/metersphere/files/9900008/fix.sql.zip)
你好，请参考附件执行sql修复该问题，

**Comment by zhangchaolei** [comment]
修复成功，感谢。
