### ISSUE TITLE
[BUG] v2.3, UI自动化稳定性测试, 测试计划包含20个场景，每30分钟执行一次，每次执行时间4mins，但是每跑50次，出现2~3次timeout，且执行时间超过1小时。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19299]
### 联系方式

王进

### MeterSphere 版本

v2.3

### 使用外置数据库

否

### 问题描述

v2.3, UI自动化稳定性测试, 测试计划包含20个场景，每30分钟执行一次，每次执行时间4mins，但是每跑50次，出现2~3次timeout，且执行时间超过1小时。

### 重现步骤

1. 新建一个测试计划
2. 添加20个UI自动化场景
3. 设置定时任务，每半个小时或1个小时执行一次
4. 持续观察结果
![1667182325171](https://user-images.githubusercontent.com/76033005/198917131-61716aaa-6591-4efb-a4b6-504028b90af8.png)

![b627bf23167accad54b1dd95af047af](https://user-images.githubusercontent.com/76033005/198917473-22496fdf-7ec9-4d18-9904-3f1b4ead15db.png)

### 附加信息

我统计了 两天的日志，大概，每跑50次，出现2~3次。

**Comment by youliyuan-fit2cloud** [comment]
请截图看下这个定时任务的配置参考下图：
![image](https://user-images.githubusercontent.com/54612864/199175218-b5145797-81a7-4dbc-a0e8-2428a47d876f.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0中已优化，请升级一下吧。
