### ISSUE TITLE
[FEATURE]接口文档编写，描述无法在表单中设置和展示，导致接口文档显示不直观

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#19297]
### MeterSphere 版本

v1.20.14-lts-83677fba

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/198910248-db55d06d-b8d7-4766-b86a-d526c254b719.png)

### 请描述你建议的实现方案

请求表单增加描述字段：
![图片](https://user-images.githubusercontent.com/23067502/198910941-b51206aa-b733-47fb-b8f1-ba97a8f62015.png)

**Comment by luty2018** [comment]
这个已经在做新的交互设计了。大概2个版本后会上线
