### ISSUE TITLE
[BUG]【偶现】复制场景后出现了多个重名和重复ID的场景

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19292]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

复制场景后出现了多个重名和重复ID的场景
![image](https://user-images.githubusercontent.com/88763608/198648295-db513f50-eded-4f16-9b99-1472fc00804a.png)

### 重现步骤

未知

> 你好，没有复现，如果场景重复会有提示信息。请描述复现步骤和常规操作有什么不同？ <img alt="image" width="1351" src="https://user-images.githubusercontent.com/54612864/198968386-995b4f57-f141-4055-bc40-f3ce9613f162.png">

暂时不知道如何复现，这是偶现，按理说会提示重复，不知道为什么会出现了几个ID和名称重复的场景

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，如果场景重复会有提示信息。请描述复现步骤和常规操作有什么不同？
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/54612864/198968386-995b4f57-f141-4055-bc40-f3ce9613f162.png">

**Comment by linfengjjj** [comment]
这个我找到复现方法了。应该是我复制后快速的按了几次保存，就重复了，这种方式不好复现，需要手速很快。
有另一种方式复现。点复制的时候，顺便多按几次CTRL+S，这样也能复现这个bug。
[重复ID.zip](https://github.com/metersphere/metersphere/files/10020554/ID.zip)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0中已修复。
