### ISSUE TITLE
[BUG]JavaScript脚本 从api定义导入接口  URL和参数为空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19306]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.3

### 使用外置数据库

否

### 问题描述

JavaScript脚本 从api定义导入接口  URL和参数为空

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/198926228-21313f92-0ee4-4533-b448-743bc50972ec.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请确认一下“从API定义导入”时所选的“运行环境”是否有请求地址和参数。
