### ISSUE TITLE
关于插件

### ISSUE THREAD

**Issue by lyl2008dsg** [metersphere/metersphere#19326]
### 请描述您的问题

Q1：请问MQTT 的插件去哪里下载？

Q2：已经支持Thrift了吗？同问插件在哪里下载？

![image](https://user-images.githubusercontent.com/6263451/198948323-77789b9a-b8f1-4cea-9f90-4705982c1ead.png)

**Comment by luty2018** [comment]
MQTT  插件是企业版， 可以去官网申请试用，工作人员会和你联系。
Thrift  目前还不支持。
