### ISSUE TITLE
[FEATURE]测试计划关联测试用例，左侧目录结果不能完全展示

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#19329]
### MeterSphere 版本

v1.20.13-lts-b1

### 请描述您的需求或者改进建议

测试计划关联测试用例，左侧目录结果不能完全展示

![image](https://user-images.githubusercontent.com/67257251/198956291-c62acc66-0f4c-4702-b388-d84be421f193.png)

### 请描述你建议的实现方案

建议加上一个左右滑动的滚动条，替代...的省略

**Comment by luty2018** [comment]
感谢建议， 我们会在近3个版本内优化
