### ISSUE TITLE
[BUG] 配置了系统邮件后，刷新页面，配置丢失并报错

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1935]
**MeterSphere 版本**
1.7.3

**截图**
![image](https://user-images.githubusercontent.com/38770463/113835247-5fb1cb80-97be-11eb-812b-31f8ceff884d.png)

**Comment by zyyfit** [comment]
您好，是必现的吗？这边没有复现呢

**Comment by wonderfulwxw** [comment]
是必现的。

**Comment by zyyfit** [comment]
您好，目前最新版是1.9.3，请升级一下看看还有没有这个问题
