### ISSUE TITLE
[BUG]接口测试在环境配置中设置了全局认证信息后执行时无法生效，但在单个接口中设置了同样信息的认证配置可以生效

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19367]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

接口测试在环境配置中设置了全局认证信息后执行时无法生效，但在单个接口中设置了同样信息的认证配置可以生效，并且接口能执行成功。

环境配置中设置了全局认证信息
![466ce209f4416a725bc9c4c3c269ee8](https://user-images.githubusercontent.com/83771182/199005398-9206ba74-640e-45e7-9a26-524d19fa4d63.jpg)
选择环境执行失败
![e16e3eb0f5d95d15e6cb2e0927f368f](https://user-images.githubusercontent.com/83771182/199006048-c7e4449f-e9b4-44f2-86b8-b1e92f2c910a.jpg)

单个接口中设置了同样信息的认证配置
![38de98ef839e87da6e635c707d97377](https://user-images.githubusercontent.com/83771182/199005543-07df1cac-16bf-4d8e-9585-adb600838d7f.jpg)

### 重现步骤

接口测试在环境配置中设置了全局认证信息后，选择该环境执行接口用例。

**Comment by youliyuan-fit2cloud** [comment]
接口中的认证配置优先级高于环境配置中的认证，你在接口中的认证配置应该置空，而不是选择了No Auth。选择了No Auth，系统认为默认使用当前接口中的认证配置了，即 No Auth 。

**Comment by youliyuan-fit2cloud** [comment]
v2.3.1中已修复。
