### ISSUE TITLE
[FEATURE]UI用例建议批量操作支持设置当前步骤截图，提升用户使用体验

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#19378]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

当前UI场景用例，后端调试/生成报告时，若需查看每个步骤的截图，需对每个步骤当都设置：当前步骤截图，操作繁琐。
建议批量操作时能支持设置截图配置，提高用户的工作效率。

### 重现步骤

见描述

### 附加信息

![1667282043863](https://user-images.githubusercontent.com/92150453/199168288-8c1139b8-e3fa-42ae-8a5d-e0867465a326.jpg)

**Comment by Hyyfit** [comment]
功能实现中，2.4上线
