### ISSUE TITLE
[BUG]UI测试的输入组件中添加追加输入时，导致用例执行异常

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#19385]
### MeterSphere 版本

cloud版-1.20.15lts

### 使用外置数据库

否

### 问题描述

在UI场景用例的输入组件中，勾选追加输入，并换行添加回车输入函数，保存用例并执行时，所有场景均为执行，功能实现异常

### 重现步骤

见问题描述

### 附加信息

![fbba8d6bf6c306419fea528de1f4e39](https://user-images.githubusercontent.com/92150453/199176231-c04a22a8-194b-4af2-ae65-7b29b6a9e92b.jpg)
![78ca4ccead951f1b481a64abe0ba785](https://user-images.githubusercontent.com/92150453/199176241-cd0f24ba-0748-420d-b6ca-9faaa601240e.jpg)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
1.20.16-lts修复了无法生成报告问题，但是用chrome浏览器执行生成报告-追加输入步骤会执行失败，需要升级docker中chrome版本，后续版本再修复追加输入步骤执行失败的问题。
