### ISSUE TITLE
[BUG]接口测试-接口自动化场景化：接口导入时，打开“接口导入”弹框，切换项目，对应接口目录、接口展示失败

### ISSUE THREAD

**Issue by hongnini** [metersphere/metersphere#19396]
### MeterSphere 版本

版本:   v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

“接口导入”弹框，切换的项目菜单不能正常展示

### 重现步骤

1. 当前项目A
2. 进入“接口测试〉接口自动化“，创建场景
3. 点击【接口列表导入】按钮，打开“接口导入”弹框
![接口列表导入](https://user-images.githubusercontent.com/102306978/199188174-a24a19bb-834c-46e6-bbbb-863757c24e40.png)

4. 设置【切换项目】将A项目切换为B项目
5. 点击菜单任意目录
![2](https://user-images.githubusercontent.com/102306978/199188231-2f5ab3d4-89a5-49ac-94e1-e8aa26973eba.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，有日志吗？看一下。或者当前用户有项目B的接口模块权限吗？

**Comment by hongnini** [comment]
> 

看了一下前端请求，是前端请求数据的时候，带的projectId错误，请排查一下

**Comment by hongnini** [comment]
> 升级一下。

好的，谢谢
