### ISSUE TITLE
[FEATURE]接口测试中，用例的提取、断言上，希望能够支持填写说明性的描述

### ISSUE THREAD

**Issue by chenfeng-fang** [metersphere/metersphere#19406]
### MeterSphere 版本

2.3.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/50090858/199202647-6d79de0b-855b-4728-be14-f2af4988749e.png)
![image](https://user-images.githubusercontent.com/50090858/199202966-9ea2ff31-fcd6-4650-97f0-3e932350cf13.png)
这样可以提高用例/场景的可读性，尤其是断言的描述还可以用于报告中提高报告的可读性

**Comment by luty2018** [comment]
感谢建议， 这个可以加。
