### ISSUE TITLE
[BUG]jmeter脚本(多线程)导入ms,第一个线程第一个请求获取不到前置脚本设置的变量值

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#19410]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.3.0

### 使用外置数据库

否

### 问题描述

1.jmeter 脚本(多线程)导入ms,第一个线程第一个请求获取不到前置脚本设置的变量值
![image](https://user-images.githubusercontent.com/103627487/199210855-fbfd8d43-2df4-4a9e-b1b4-ebf58f84fadf.png)
![image](https://user-images.githubusercontent.com/103627487/199211260-5f9919fe-e2ae-4f5d-a0d3-f3e60e57b157.png)
2.单独执行一个线程可以正常获取到值
![image](https://user-images.githubusercontent.com/103627487/199211061-17039c67-b3ad-4287-801e-a6da2a091bbb.png)
![image](https://user-images.githubusercontent.com/103627487/199211135-dd7b3f50-c318-4d20-982c-64fde4adbf96.png)

### 重现步骤

1.jmeter 多线程脚本，并正常执行，每个线程有beanshell前置处理程序设置脚本变量
![image](https://user-images.githubusercontent.com/103627487/199211893-9f4375ee-9bf9-4270-97ee-0c87dbe269b8.png)
2.jmeter 脚本正常执行
![image](https://user-images.githubusercontent.com/103627487/199212019-12744841-c54b-49ad-a112-ec17295bfd74.png)
3.导入到ms场景中
![image](https://user-images.githubusercontent.com/103627487/199212219-f21d37c1-446a-4e7a-9ef3-8c1cb8f960c0.png)
4.场景调试，第一个请求前置脚本设置变量值没有拿到
![image](https://user-images.githubusercontent.com/103627487/199212440-e4742500-cee9-499d-8505-94379cec56ef.png)
![image](https://user-images.githubusercontent.com/103627487/199212757-fc678b55-c1fa-469b-80a3-f2ea5837d226.png)

### 期待的正确结果

期待前置脚本设置变量都能正常获取

**Comment by youliyuan-fit2cloud** [comment]
你好，这个场景方便发出来吗？方便我们快速复现，感谢。
