### ISSUE TITLE
[BUG]用场景变量和前置返回的变量 int类型的值 都会转成string，而且我也设置成 number 和 integer 都不行

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#19415]
### MeterSphere 版本

V2.2

### 使用外置数据库

否

### 问题描述

用场景变量和前置返回的变量 int类型的值 都会转成string，而且也设置成 number 和 integer 都不行。建议设置了参数类型，请求体json格式里面的值，应该根据设置转换，而不应该全部处理为字符型。

### 重现步骤

用场景变量和前置返回的变量 int类型的值 都会转成string，而且也设置成 number 和 integer 都不行。建议设置了参数类型，请求体json格式里面的值，应该根据设置转换，而不应该全部处理为字符型。
1）请求体json格式，打开json-schema，设置参数类型为数值型，并且赋值为数值
2）点击执行或者调试后，请求体里的参数变成字符串类型。

### 期待的正确结果

请求参数设置了参数类型，请求体json格式里面的值，应该根据设置转换，而不应该全部处理为字符型。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/199216977-fb32b2fa-d089-4878-a081-f611b37d80c9.png)

![image](https://user-images.githubusercontent.com/78218624/199216393-cce4a326-8bdd-4dc8-8683-d3e80e918aa7.png)

**Comment by hitechr** [comment]
我也遇到同样的问题，试了好多方法都不行，使用变量时都统一按字符串来提交

**Comment by hitechr** [comment]
我的版本是：v1.20.15-lts
