### ISSUE TITLE
[FEATURE]断言

### ISSUE THREAD

**Issue by Kimtaega** [metersphere/metersphere#1941]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
1、希望一个Jsonpath断言的作用域可以覆盖整个脚本的所有接口
2、希望可以有批量操作：批量禁用/启用接口，批量删除

**Comment by xulinde** [comment]
1.是场景级别的断言吗
2.已在后续版本规划中

**Comment by Kimtaega** [comment]
1、是的，在接口测试中的场景，接口自定义等模块的断言
2、谢谢，希望MeterSphere越来越好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]断言 (#1941)





 
1.是场景级别的断言吗
 2.已在后续版本规划中

**Comment by xulinde** [comment]
v1.10.2版本已实现
