### ISSUE TITLE
[BUG]UI自动化用例A引用指令B，修改指令 B 里面的步骤，执行用例A 的时候还是执行的指令 B里旧的步骤。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19429]
### 联系方式

王进

### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

UI自动化用例A引用指令B，修改指令 B 里面的步骤，执行用例A 的时候还是执行的指令 B里旧的步骤。

### 重现步骤

1. 新建UI自动化场景A
2. 在A里引用指令B，保存退出
3. 修改指令B，比如打开一个网址，或者修改当前步骤截图等等，保存。
4. 执行场景A，会看到A里执行的指令B还是旧的指令B里面的步骤。 

### 附加信息

客户发现的问题，复测下来确实是问题。

**Comment by 35plus** [comment]
和这个问题类似和关联的现象：用例A里面引用了指令 B，然后复制用例 A为 C，修改指令 B，C 里面不能更新，也不能修改。
本质上和当前问题是一个问题。

**Comment by xulinde** [comment]
v2.4.0已修复～
