### ISSUE TITLE
[BUG] 调试过程中API报告不按照请求时间排序

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1942]
**MeterSphere 版本**
1.8.2

**Bug 描述**
场景用例中有复制和引用其他用例；
调试结束后API请求的报告没有按照时间进行排序显示；找了半天才找到最后一步

场景如下：
第一步是引用一个场景；第二步是复制一个场景；第三步是引用一个接口；第4步是引用一个场景；第五步引用一个接口

结果再报告页面
第五步没有显示在最后；和第三步显示在一起了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，这个问题将在后续版本修复

**Comment by zyyfit** [comment]
您好，1.9.0版本已修复了这个问题，目前最新版是1.9.3，请升级后试试
