### ISSUE TITLE
[BUG]get请求时间函数%20是转码后显示空格

### ISSUE THREAD

**Issue by a6106526** [metersphere/metersphere#19425]
### 联系方式

870416257@qq.com

### MeterSphere 版本

2.2.0

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/15136557/199380289-b36600a0-7e9f-4aa5-b366-02b3e3c87998.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/15136557/199380289-b36600a0-7e9f-4aa5-b366-02b3e3c87998.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，Jmeter结果也是如此，暂时没有办法解决。

**Comment by zhangzhaox** [comment]
这不是问题 所有的URL参数特殊字符都需要进行urlencode编码的
