### ISSUE TITLE
[BUG] UI自动化场景步骤名称中带有“”号，会导致场景不执行

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19422]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

是

### 问题描述

UI自动化场景步骤名称中带有“”号，会导致场景不执行

### 重现步骤

1、创建UI场景
2、添加场景步骤，步骤名称中添加“”号
3、保存后执行场景
4、场景不执行，后台日志会报错

### 附加信息

步骤截图：
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/32027713/199377756-962601a9-45ca-4151-bfac-b3429c840f14.png">

ms-server日志截图：
<img width="982" alt="image" src="https://user-images.githubusercontent.com/32027713/199378148-83399a89-f475-4378-b45f-732491ac5b76.png">

**Comment by xulinde** [comment]
v2.3.1已修复～
