### ISSUE TITLE
[BUG]UI场景转为指令时，对应的UI场景变量没有带过去，需要手动重新添加

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19424]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.2.0

### 使用外置数据库

否

### 问题描述

UI场景转为指令时，对应的UI场景变量没有带过去，需要手动添加

### 重现步骤

1、选择一个具有场景变量的UI场景
2、批量选择步骤创建自定义指令
3、查看创建后的自定义指令，发现对应场景变量没有带过去

### 期待的正确结果

场景变量可以带过去，否则指令就失效了

### 附加信息

原场景：
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/32027713/199379783-2f5f7812-18cb-49f2-8738-c2d65aec7a59.png">

创建指令后的场景：
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/32027713/199379862-bf68b754-d8d2-48f8-bd77-62b7f62f6114.png">

**Comment by xulinde** [comment]
v2.3.1已修复～
