### ISSUE TITLE
[FEATURE] 环境配置 如果多人打开，那么最后保存的一个 会把前面人修改的环境变量覆盖掉

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#19426]
### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

环境配置 如果打开多个，那么 最后保存的一个 会把前面页面的环境变量覆盖掉

### 重现步骤

1.多个不同账号打开同一个项目下的环境变量配置
2.每个账号都修改环境配置
3.前面修改的会被后面修改的覆盖掉

**Comment by A616984934** [comment]
这应该是一个bug,每次存环境变量之前，应该先校验已有数据，只修改已有数据部分才对

**Comment by luty2018** [comment]
是的， 目前系统还不支持协同编辑， 这块也在我们的规划中。
