### ISSUE TITLE
[BUG]编辑功能用例，修改信息后无法保存

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#19421]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.3.0

### 使用外置数据库

否

### 问题描述

编辑功能用例，修改信息后无法保存

### 重现步骤

1.创建功能用例，正常创建
![image](https://user-images.githubusercontent.com/103627487/199220696-ae9e0fba-67c9-4907-8ebd-08e8036e500c.png)
![image](https://user-images.githubusercontent.com/103627487/199220837-b5f581b3-d591-4b5e-8754-c8b865e4238a.png)
2.编辑用例，添加步骤，点击保存后，页面刷新未提示保存成功
![image](https://user-images.githubusercontent.com/103627487/199220991-cfd5e8b4-ec3e-4634-bab4-87161b30477f.png)
3.关闭页面，提示未保存
![image](https://user-images.githubusercontent.com/103627487/199221242-5e86ba0b-5a2c-4af6-80b8-ee0ff599cf9f.png)
4.关闭后，编辑进去，发现步骤确实未添加成功
![image](https://user-images.githubusercontent.com/103627487/199221386-c75debbd-5b38-47a2-866d-4137d2af50a7.png)

**Comment by xulinde** [comment]
按您描述的步骤未复现该问题，请看下我的操作是否和您的一致？

https://user-images.githubusercontent.com/64065190/199382796-a5d867b8-8ffd-4bea-8303-84cf5c8d1e4f.mov
