### ISSUE TITLE
[BUG]UI测试，自动化场景-输入框操作-输入内容包含英文双引号会导致无法执行。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#19437]
### 联系方式

于凯杰

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

1.UI测试-UI自动化执行测试，输入操作选择输入框，输入内容为元素xpath定位数据（如//*[@id="su"]），会导致UI自动化场景执行不了。
![1](https://user-images.githubusercontent.com/55130444/199388615-69872e07-6120-4901-9cb7-29a69f205a63.jpg)
![2](https://user-images.githubusercontent.com/55130444/199388637-e64c4457-f1eb-4b90-94bc-8ca40cc8a52b.jpg)

### 重现步骤

1.ui测试选择UI自动化
2.场景里操作选择输入操作,输入内容为//*[@id="su"]，
3.执行自动化场景。
![3](https://user-images.githubusercontent.com/55130444/199400226-793145af-8e76-4898-b2ff-e37449bc58ea.jpg)

### 期待的正确结果

输入框的输入内容不会影响执行UI自动化测试。

### 附加信息

经过排查，发现输入 **英文双引号** 后会导致无法执行自动化场景

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/19422
