### ISSUE TITLE
[BUG]UI模块关闭，复制测试计划报错

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#19432]
### 联系方式

杨晓燕

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

关闭UI模块，复制测试计划报错

### 重现步骤

1、关闭UI模块
![wecom-temp-4018-ad468f9c551742d042411beeed55cf38](https://user-images.githubusercontent.com/72729206/199385696-f56efbc9-50e5-45ac-a00a-37c3edb76682.png)
2、复制测试计划
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/72729206/199382692-75ef374f-ad97-4ff8-b00d-ab1e6210a964.png">

### 期待的正确结果

可以正常复制

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #19423
