### ISSUE TITLE
[BUG]接口配置中，当请求体由json切换为json-schema时，null值被处理成""造成接口调用失败

### ISSUE THREAD

**Issue by chenfeng-fang** [metersphere/metersphere#19439]
### 联系方式

MeterSphere交流群51 -隼龙

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

请求体由json切换为json-schema时，null值被处理成""造成接口调用失败

切换到json-schema时，可以看到配置的内容中确实是null类型的
![image](https://user-images.githubusercontent.com/50090858/199409594-53c1dde2-a966-4d87-b32f-ce79ab080179.png)
但实际使用的时候，不论是切换回json，还是实际调用，都确认到传递的值为空串""
![image](https://user-images.githubusercontent.com/50090858/199409398-7a6d5d97-7108-49ee-84ac-17fc8e410f06.png)

### 重现步骤

请求体json中创建值为null的参数，切换到json-schema后测试切换回json、发送请求检查请求内容

### 期待的正确结果

切换到json-schema后，null类型的值在切换会json、实际发送请求的时候，都正常传null值

**Comment by chenfeng-fang** [comment]
由此引申，json-schema中目前似乎并不支持配置null值（选择数据类型的时候其实没有null类型可以选择），值里面填null肯定会识别为字符串“null”
![image](https://user-images.githubusercontent.com/50090858/199411892-c2505df8-d9ae-4d79-8c09-c43b2b51a9ed.png)

**Comment by youliyuan-fit2cloud** [comment]
> 由此引申，json-schema中目前似乎并不支持配置null值（选择数据类型的时候其实没有null类型可以选择），值里面填null肯定会识别为字符串“null” ![image](https://user-images.githubusercontent.com/50090858/199411892-c2505df8-d9ae-4d79-8c09-c43b2b51a9ed.png)

感谢反馈，确实如你所说，我们需要处理一下转换为jsonschema后类型为string

**Comment by youliyuan-fit2cloud** [comment]
你好，最新发布的v2.3.1版本中，修改为json转换jsonSchema后，nulll类型，默认转换为 string 类型，值为空。

**Comment by chenfeng-fang** [comment]
> 你好，最新发布的v2.3.1版本中，修改为json转换jsonSchema后，nulll类型，默认转换为 string 类型，值为空。

之前的版本就是null会转成空值，我需要的是在jsonSchema中支持转换到null值、支持传null值
