### ISSUE TITLE
[FEATURE]高级搜索，目前设置了筛选条件一直生效有时候会误以为数据出错了，取消筛选还需要再次点进去 ，交互体验不好建议把重置、取消筛选放外边儿

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19446]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

1、api数据列表列表高级搜索，目前设置了筛选条件一直生效有时候会误以为数据出错了，
2、取消筛选还需要再次点进去 ，交互体验不好建议把重置、取消筛选放外边儿

### 重现步骤

![Uploading 高级搜索，目前设置了筛选条件一直生效有时候会误以为数据出错了，取消筛选还需要再次点进去 ，交互体验不好建议把重置、取消筛选放外边儿.png…]()

### 期待的正确结果

交互体验不好建议把重置、取消筛选放外边儿

**Comment by xhy12** [comment]
![高级搜索，目前设置了筛选条件一直生效有时候会误以为数据出错了，取消筛选还需要再次点进去 ，交互体验不好建议把重置、取消筛选放外边儿](https://user-images.githubusercontent.com/43202800/199418969-6fef7fdf-abe2-450d-b33f-2c8c17a0272c.png)

**Comment by Hyyfit** [comment]
已规划优化
