### ISSUE TITLE
[BUG]性能测试，新建——引用接口自动化场景。接口第一页勾选后翻页再勾选，切换第一页查看勾选不生效但是实际选上了 

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19444]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

性能测试，新建——引用接口自动化场景。接口第一页勾选后翻页再勾选，切换第一页查看勾选不生效但是实际选上了 

### 重现步骤

步骤1：性能测试，新建——引用接口自动化场景。接口第一页勾选后翻页再勾选，

问题：切换第一页查看勾选不生效。但是确定的时候但是实际选上了 （见操作录屏）

### 期待的正确结果

翻页 第一页勾选状态保留

### 附加信息

![翻页勾选后，查看勾选不生效但是实际选上了 、](https://user-images.githubusercontent.com/43202800/199415197-3717d0dd-4ae6-4db1-930e-3b3bda1a6be4.png)

https://user-images.githubusercontent.com/43202800/199415219-22045fdf-b74f-424f-b51f-f082b2ba6703.mp4

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
