### ISSUE TITLE
[FEATURE]优化工作空间命名提示描述，更加准确、简洁

### ISSUE THREAD

**Issue by LonelyWarrior2023** [metersphere/metersphere#19441]
### MeterSphere 版本

2.3

### 请描述您的需求或者改进建议

<img width="432" alt="图片" src="https://user-images.githubusercontent.com/117255533/199410613-ebadcfd9-eeee-4822-aa2f-b529fdcf5195.png">
<img width="638" alt="图片" src="https://user-images.githubusercontent.com/117255533/199410841-0bf5c434-2008-48c2-8226-2f3a34708532.png">

./frontend/src/i18n/zh-CN.js:    special_characters_are_not_supported: '格式错误(不支持特殊字符，且不能以\'-\'开头结尾)',

pattern: /^(?!-)(?!.*?-$)[a-zA-Z0-9\u4e00-\u9fa5-]+$/

错误的提示信息与pattern的意思不符合（只含有汉字、数字、字母、下划线不能以下划线开头和结尾）
不是所有人对特殊字符的理解是限制在数字、细目、汉字、下划线中的
所以建议提示信息更加准确，减少出现理解上的差异

**Comment by luty2018** [comment]
已纳入v2.5版本优化
