### ISSUE TITLE
[FEATURE]用例模板表格希望优化：目前 步骤和预期单元格需要写完之后挨着去调整格式，调整工作量挺大的 建议优化成 多个步骤 预期可以写一行里面可以根据换行符自动识别到平台生成多行数据

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19440]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

用例模板表格希望优化：目前 步骤和预期单元格需要写完之后挨着去调整格式，调整工作量挺大的 

建议优化成 多个步骤 预期可以写一行里面可以根据换行符自动识别到平台生成多行数据

### 请描述你建议的实现方案

![用例模板表格希望优化：目前 步骤和预期单元格需要写完之后挨着去调整格式，调整工作量挺大的](https://user-images.githubusercontent.com/114552960/199411337-cb8cf1da-0172-4db4-95b0-d10b01bb64b8.png)
如图：

**Comment by luty2018** [comment]
这个也是比较多用户反馈一个步骤一行才改的，可能需要适应一下了。
