### ISSUE TITLE
[FEATURE]性能测试目前不支持脚本编辑，期望在接口场景编排添加常用性能测试组件：如吞吐量控制组件 

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19449]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

性能测试目前不支持脚本编辑，期望在接口场景编排添加常用性能测试组件：如吞吐量控制组件 

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/114552960/199425393-54ff4205-7f97-49d2-8f44-ed56988cec36.png)

**Comment by luty2018** [comment]
感谢建议， 性能测试这块后续有规划支持。
