### ISSUE TITLE
[FEATURE]优化建议：用例评审完成之后可以选择生成为测试计划

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19442]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

背景：目前用例评审完成之后，需要根据评审计划创建同样的一个 测试计划去做功能执行，还需要挨个去选择用例创建测试计划

期望：既然已经有现成的用例评审计划了，希望可以 配置选择生成为测试计划。方便管理执行

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/114552960/199412650-b159c4e5-4dc0-4b0b-ae91-7490c07a5169.png)
在用例评审计划处添加操作 可以配置为测试计划

**Comment by luty2018** [comment]
这是个非常好的建议！我们尽快调研！

**Comment by opopjasica** [comment]
期待！！！

**Comment by luty2018** [comment]
预计在2023年Q1

**Comment by luty2018** [comment]
预计在2023年Q1

**Comment by opopjasica** [comment]
收到！官方真给力
