### ISSUE TITLE
[BUG]角色设置不能删除测试用例评审。但是用户在用例评审列表中依旧能看到删除按钮，并且点击删除，可以正常打开删除弹出页面，在删除弹出页面输入信息点击确认后，这时系统异常，直接跳转到工作空间页面。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#19466]
### MeterSphere 版本

V2.2

### 使用外置数据库

否

### 问题描述

[BUG]角色设置不能删除测试用例评审。但是用户在用例评审列表中依旧能看到删除按钮，并且点击删除，可以正常打开删除弹出页面，在删除弹出页面输入信息点击确认后，这时系统异常，直接跳转到工作空间页面。

### 重现步骤

[BUG]角色设置不能删除测试用例评审。但是用户在用例评审列表中依旧能看到删除按钮，并且点击删除，可以正常打开删除弹出页面，在删除弹出页面输入信息点击确认后，这时系统异常，直接跳转到工作空间页面。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/199491725-84fd3a8e-5a2f-414b-a07b-44327502df7d.png)
![image](https://user-images.githubusercontent.com/78218624/199491871-40a5492b-5f54-4ccd-b140-aaf79988e200.png)
![image](https://user-images.githubusercontent.com/78218624/199491932-20a1986e-2ab8-4518-a83d-f8bfe6d33a56.png)
![image](https://user-images.githubusercontent.com/78218624/199492067-b42c35dc-f8a5-4cbb-9000-eac178927fe3.png)
![image](https://user-images.githubusercontent.com/78218624/199492281-0306e765-18ff-4e1f-8ae2-de8ff2e0b12a.png)

**Comment by xulinde** [comment]
v2.3已修复～
