### ISSUE TITLE
[BUG]系统消息提醒中 操作人 错误

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#19472]
### 联系方式

zhangrufeng_006@163.com

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

在执行接口case成功后，消息中心中的系统通知，其中提到的 操作执行人 与实际操作人不一致，与操作日志中记录的结果不符。

![image](https://user-images.githubusercontent.com/100331967/199660016-e73e8930-9efa-4322-91e6-ed56dc866d16.png)
![image](https://user-images.githubusercontent.com/100331967/199660035-e40fd0d2-a167-44b1-b4d6-a556a28e45e8.png)

### 重现步骤

1.执行接口case
2.执行成功后，查看消息中心中的系统通知
3.查看其中提到的 操作执行人 与实际操作人是否一致，与操作日志中记录的结果是否相符。

**Comment by zyyfit** [comment]
您好，没有复现这个问题，大概是什么情况下会出现这种问题呢？

**Comment by zrf87** [comment]
没有什么特殊操作，电脑上也没有登录过其它用户，应该并不是缓存问题，但最近经常出现上面的问题。

**Comment by zyyfit** [comment]
您好，这个问题我们这边还是没有复现，之前应该修复过类似的问题，您可以清缓存或者升级到1.20.16试一下，如果还是会出现，可以在交流群里找我们的工作人员帮忙排查一下问题

**Comment by fit2cloud-yangxiaoyan** [comment]
我们在2.1.1版本也发现了
