### ISSUE TITLE
开发人员进入缺陷管理页面，最好只能看到处理人是自己的缺陷，并且状态为新建的，就不需要每次进入都要筛选那么麻烦。

### ISSUE THREAD

**Issue by 327282227** [metersphere/metersphere#19473]
### MeterSphere 版本

 v2.1.1-96b84b46

### 请描述您的需求或者改进建议

开发人员进入缺陷管理页面，最好只能看到处理人是自己的缺陷，并且状态为新建的，就不需要每次进入都要筛选那么麻烦。

### 请描述你建议的实现方案

开发人员进入缺陷管理页面，最好只能看到处理人是自己的缺陷，并且状态为新建的，就不需要每次进入都要筛选那么麻烦。

**Comment by luty2018** [comment]
感谢建议，有考虑这种设计
