### ISSUE TITLE
[FEATURE]功能用例创建文件夹时，可以自动创建子文件夹(该文件夹下包含提前创建好的模板内容)

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#19471]
### MeterSphere 版本

v1.20.4-lts-b1

### 请描述您的需求或者改进建议

1，我们会提前定义好功能用例模板，会区分 模块、用例等
2，当有用户创建了一级文件夹时，自动把模板内容添加到该文件夹下

**Comment by luty2018** [comment]
麻烦进一步描述需求， 目前模板是按项目来区分的， 一个项目一个模板
