### ISSUE TITLE
[BUG][测试跟踪]报告-接口用例统计分析的失败用例中部分用例的右侧的执行结果显示空

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#19486]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

是

### 问题描述

接口用例统计分析的失败用例中部分用例右侧的执行结果显示“内容为空”

### 重现步骤

1、测试跟踪中定时执行测试计划
2、查看测试计划定时执行后的报告-接口用例统计分析的失败用例中内容

### 期待的正确结果

执行结果显示正确（同接口测试中对应用例的执行结果）

### 附加信息

![QQ截图20221104092359](https://user-images.githubusercontent.com/117417157/199865151-5a13716f-f5f2-46f8-a51c-39595f2dbfe6.png)

**Comment by zyyfit** [comment]
您好，能具体描述一下出现场景吗

**Comment by vivage** [comment]
步骤
1、创建接口测试用例的测试计划（整个系统的接口）
2、为这个测试计划设置定时任务
3、查看这个定时执行测试计划后生成的报告
4、在报告的接口用例统计分析区域查看失败接口的执行结果
结果：发现接口的执行结果区域中显示内容空白（单个执行这样的接口，执行结果是正常的）










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月4日(星期五) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][测试跟踪]报告-接口用例统计分析的失败用例中部分用例的右侧的执行结果显示空 (Issue #19486)





 
您好，能具体描述一下出现场景吗

**Comment by zyyfit** [comment]
您好，用1.20.16版本没有复现这个问题，您可以升级试试，如果升级也有这个问题的话，可以在交流群里联系我们的工作人员帮您排查一下问题
