### ISSUE TITLE
[FEATURE]  debbo接口页面建议去掉右上角的环境下拉框

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19484]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v1.20.14-lts-83677fba

### 使用外置数据库

否

### 问题描述

 debbo接口引用环境变量失败

### 重现步骤

1、环境中存在变量test2
![image](https://user-images.githubusercontent.com/103925124/199686831-2beede00-374b-4bee-bc2e-50cebb5586c5.png)
2、脚本中引用
![image](https://user-images.githubusercontent.com/103925124/199687534-19d714b9-ee33-45c2-acf6-87c39fc0bbc7.png)
**_打印结果 为void_**
![image](https://user-images.githubusercontent.com/103925124/199687726-17784e85-9be1-4c72-a2ba-a4cf2df1a6d2.png)
3、参数中引用也不生效
![image](https://user-images.githubusercontent.com/103925124/199689079-4d9472b8-eab9-4471-9fe3-fa4f286a051f.png)

**Comment by zyyfit** [comment]
感谢反馈，目前dubbo接口是不会使用环境的，dubbo接口的所有接口信息都是从自身获取的，所以也不会获取到环境里的变量

**Comment by Ycr123888** [comment]
那为啥可以支持选择环境啊，去掉环境选择可嘛？

**Comment by luty2018** [comment]
可以提需求走全局环境， 也个也是在规划内的。
