### ISSUE TITLE
[BUG]接口自动化TEST界面断言文档结构时“添加子字段”按钮功能无效

### ISSUE THREAD

**Issue by ed6896** [metersphere/metersphere#19488]
### MeterSphere 版本

2.2.1

### 使用外置数据库

是

### 问题描述

接口自动化TEST界面断言文档结构时“添加子字段”按钮功能无效

### 重现步骤

1. 通过“添加子字段”按钮添加一个子字段
2. 删除新添的子字段
3. 再次点击“添加子字段”按钮，此时该按钮点击后无任何响应

### 期待的正确结果

可以反复添加子字段

### 附加信息

![无标题](https://user-images.githubusercontent.com/70947946/199873833-04c6fc8c-92ad-417b-9cea-595db9d4921f.png)

**Comment by zyyfit** [comment]
1.20.17 和 2.3.1 版本已修复，请等待版本发布后验证
