### ISSUE TITLE
[BUG]优化接口测试-接口自动化报告失败栏内容展示。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#19482]
### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

1.接口自动化场景报告里，失败页面展示为空，但在场景列表中查看结果为失败。

### 重现步骤

1.接口自动化，创建好场景。
![tapd转gitlab-万物云](https://user-images.githubusercontent.com/55130444/199684212-7bcfc9e5-0052-40bd-b2b0-fbd4c2e86f2b.jpg)

2.设置全局前置脚本，打开关联场景结果。
![tapd转github2](https://user-images.githubusercontent.com/55130444/199684344-46ab7c6c-618a-4228-aaeb-23eb762a67e6.jpg)

3.执行接口自动化测试，失败里没有内容。但场景列表页面展示执行结果为失败。
![tapd转github1-2](https://user-images.githubusercontent.com/55130444/199684370-3034153a-89a9-4676-a9b8-8066bf4ffb18.jpg)

![tapd转github3](https://user-images.githubusercontent.com/55130444/199684429-d0db52e2-a321-4ef3-9e04-9fca21ec565e.jpg)

优化建议：报告失败内容里展示具体报错信息提示

### 期待的正确结果

场景测试报告失败内容里展示具体报错信息提示。

**Comment by zyyfit** [comment]
感谢您的反馈，我们这里目前是考虑到，因为全局前置脚本不属于场景中的步骤，所以没有在场景报告结果中展示，但是因为关联了场景执行结果，所以在场景列表中的执行结果是受到全局前置脚本影响的
