### ISSUE TITLE
[BUG]接口测试-场景报告-展示语言混乱

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#19481]
### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

1.接口自动化执行场景测试，生成报告，测试报告内容展示为中英文混合，
2.右上切换语言为English，展示为全英文，然后切换为中文（简体），还是展示为中英文混合。
![1103-中英文bug](https://user-images.githubusercontent.com/55130444/199681107-2f5f55fc-3463-46fd-8c5f-e258d01dca71.jpg)

### 重现步骤

1.接口测试-接口自动化增加一个场景。
2.接口信息填写完整，点击生成报告，报告内容展示为中英文混合。

### 期待的正确结果

应该展示和我选择的语言相同。

### 附加信息

接口自动化场景列表执行结果展示也有问题
![1103-bug-补充](https://user-images.githubusercontent.com/55130444/199681752-5aaf6f6a-34d1-4777-90b7-1d81ad189cb9.jpg)

**Comment by zyyfit** [comment]
感谢您的反馈，目前接口这边是这样的：
1、关于接口和场景状态的问题，是我们在2.3.0版本统一过的，不管语言是中文还是英文，状态都会显示为英文的，success、error 等
2、语言选择英文的时候，如果有用户创建时填写的数据，如接口名称、用户名称等是中文的，我们是不会同步切换为英文的
具体请看截图信息
![image](https://user-images.githubusercontent.com/73461316/199952030-af79ebfb-8b9f-4c5c-b707-f4182bb9ad40.png)
![image](https://user-images.githubusercontent.com/73461316/199953523-2a144bd4-ad42-443e-9979-4ae85e31c41f.png)
