### ISSUE TITLE
[BUG] 断言异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1948]
**MeterSphere 版本**
1.8.2
**Bug 描述**
简要描述您碰到的问题
在需要断言的json字符串变量中有"的存在导致图片中注释部分的代码出错

![image](https://user-images.githubusercontent.com/5517369/113858994-f9857280-97d6-11eb-858d-82c6ea7997c9.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这是jmeter的报错，我们后续版本将会考虑修复这类问题的

**Comment by guhan121** [comment]
@zyyfit 上面注释的代码难道不是metersphere生成的么？

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会尽快修复该问题。

**Comment by zyyfit** [comment]
您好，1.10.1版本已修复这个问题，请升级后使用
