### ISSUE TITLE
[QUESTION] 怎么修改密码策略(复杂度、强度)

### ISSUE THREAD

**Issue by KnightBlood** [metersphere/metersphere#19494]
### 请描述您的问题

死活找不到修改密码策略的地方

**Comment by KnightBlood** [comment]
2.3.0版本

**Comment by KnightBlood** [comment]
?就这么一个问题几天没人解答?
还是说你们压根没考虑 密码复杂度设置

**Comment by luty2018** [comment]
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/36292514/200455509-909d83bf-1f8f-42fc-92e8-7f8730123d31.png">
<img width="472" alt="image" src="https://user-images.githubusercontent.com/36292514/200455871-53df45fe-76f1-4b5a-9435-0eef9e6401b1.png">
建议加入我们的交流群， 或者提前熟悉下文档。

**Comment by KnightBlood** [comment]
我要修改的是密码复杂度不是密码
懂?

**Comment by KnightBlood** [comment]
> <img alt="image" width="1464" src="https://user-images.githubusercontent.com/36292514/200455509-909d83bf-1f8f-42fc-92e8-7f8730123d31.png">
> 
> <img alt="image" width="472" src="https://user-images.githubusercontent.com/36292514/200455871-53df45fe-76f1-4b5a-9435-0eef9e6401b1.png">
> 
> 建议加入我们的交流群， 或者提前熟悉下文档。

答非所问
我要修改的是密码复杂度不是密码
