### ISSUE TITLE
[BUG]测试跟踪>>测试用例>>脑图模式：在测试用例或者模块上，右键选择删除功能，进行删除操作。目前在操作日志里无相关日志操作。即：目前没有办法通过日志查看是谁做了删除操作，删除了哪些信息。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#19496]
### MeterSphere 版本

V2.2&V1.20.15-lts

### 使用外置数据库

否

### 问题描述

测试跟踪>>测试用例>>脑图模式：在测试用例或者模块上，右键选择删除功能，进行删除操作。目前在操作日志里无相关日志操作。即：目前没有办法通过日志查看是谁做了删除操作，删除了哪些信息。

### 重现步骤

测试跟踪>>测试用例>>脑图模式：在测试用例或者模块上，右键选择删除功能，进行删除操作。目前在操作日志里无相关日志操作。即：目前没有办法通过日志查看是谁做了删除操作。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/199887901-657bd19b-51b8-4f64-8b30-254ccb20c8ae.png)
![image](https://user-images.githubusercontent.com/78218624/199888081-f199dcbd-bc69-4b11-9fb9-4d70b1852a4b.png)

**Comment by xulinde** [comment]
脑图只有一个保存的接口，目前没有分那么细，后期看产品怎么规划这块

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by luty2018** [comment]
脑图v3.0已经覆盖， 建议升级到v3.0使用。
