### ISSUE TITLE
[FEATURE] 接口自动化自定义请求，不能单独调试且没有代码联想提示，建议增加一个调试入口嵌入脚本编辑器功能

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19497]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

接口自动化自定义请求，不能单独调试且没有代码联想提示，建议增加一个调试入口嵌入脚本编辑器功能
![image](https://user-images.githubusercontent.com/114552960/199895694-a2db01dc-b63e-4e46-8ad1-f92c530595c7.png)

**Comment by luty2018** [comment]
感谢建议， 这个功能暂时没有排期计划， 需要进一步调研。
