### ISSUE TITLE
[FEATURE]接口自动化 变更记录只能查看不能回滚到上次的记录版本，建议添加一个变更版本回滚的操作按钮方便调试

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19499]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

接口自动化 变更记录只能查看不能回滚到上次的记录版本，对我实际的业务参考性不强 

建议添加一个变更版本回滚的操作按钮，这样可以用到历史调试数据，这个功能实现的意义更大
![image](https://user-images.githubusercontent.com/114552960/199896622-a8410de5-7c6a-4c0d-a8d7-d7d51f862970.png)

**Comment by luty2018** [comment]
感谢建议， 我们需要进一步调研实现方案。

**Comment by SolarisYan** [comment]
请问根据变更记录回滚到之前的某个历史版本的功能实现了吗？
