### ISSUE TITLE
[FEATURE]接口自动化：接口+自定义脚本有二十多步，挨着去找脚本很麻烦看的眼花缭乱的。。能不能加个脚本执行缩略轴，快速跳转到目标步骤

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19500]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

接口自动化：接口+自定义脚本有二十多步，挨着去找脚本很麻烦看的眼花缭乱的。。能不能加个脚本执行缩略轴，快速跳转到目标步骤
如图：

![image](https://user-images.githubusercontent.com/114552960/199898026-56f1558a-3603-4d00-a867-ecb9f11ad504.png)

**Comment by opopjasica** [comment]
调试的时候 步骤都是展开去查看，鼠标滑动对比 弄得头昏眼花的

**Comment by luty2018** [comment]
你好， 这个问题描述的比较简单，麻烦添加我的企业微信，详细沟通一下需求，谢谢！
<img width="474" alt="image" src="https://user-images.githubusercontent.com/36292514/203208840-3d3bcab0-f5ed-4107-88fb-a6c02a214bef.png">

**Comment by opopjasica** [comment]
![image](https://user-images.githubusercontent.com/114552960/210742746-16c4ae3d-599e-45b0-bf78-84a64a354a81.png)
建议参考 知乎这个缩略轴
