### ISSUE TITLE
[BUG]在使用功能用例列表的“高级搜索”的时候，按自定义的用例状态进行搜索，只能查询到一条数据

### ISSUE THREAD

**Issue by spheretangmeng** [metersphere/metersphere#19529]
### 联系方式

微信：zuanshixiu668 “MeterSphere北方区交流群”

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

在使用功能用例列表的“高级搜索”的时候，按自定义的用例状态进行搜索，只能查询到一条数据

### 重现步骤

1.先上传N条功能用例
2.自定义“用例状态”字段的属性值（多选下拉框），并删除掉原有的属性值
3.批量修改用例的“用例状态”属性为上一步中自定义的值
4.在用例列表用高级搜索功能来搜索查询对应状态的用例，仅选择一种状态的用例

### 期待的正确结果

查询到所有符合条件的用例

### 附加信息

![image](https://user-images.githubusercontent.com/113685220/199956258-c631a807-407c-403e-a11b-b085650a1d36.png)
![image](https://user-images.githubusercontent.com/113685220/199956331-7f607b5b-e8ff-4281-9758-42cf177ad6c7.png)
我图片上展示的都不止一条

**Comment by xulinde** [comment]
v2.3.1已修复～
