### ISSUE TITLE
[BUG] 编辑默认用例模板中名称信息后保存，系统用例模板新增了，且不可删除

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19521]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

编辑默认用例模板中名称信息后保存，系统用例模板新增了，且不可删除

### 重现步骤

1、编辑default中名称信息
![image](https://user-images.githubusercontent.com/103925124/199947954-b56c5a7c-65ae-4569-9882-ebac40f8e62b.png)
2、保存后为新增，不可删除
![image](https://user-images.githubusercontent.com/103925124/199948246-2c5f75c3-7398-46c1-98ce-36189badbe09.png)

**Comment by xulinde** [comment]
和研发确认：默认模版是所有项目共用的全局模版, 属于初始默认数据, 这条数据上的更改就是新增一个新的模板
