### ISSUE TITLE
[BUG] 从1.7.3 升级到1.8.2 后，出现大量SQL error

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#1952]
**MeterSphere 版本**
1.8.2

部署方式： 
helm chart 

**截图**
![image](https://user-images.githubusercontent.com/38770463/113953148-bca69380-9849-11eb-93ce-ade749f6c597.png)

**Comment by xulinde** [comment]
截图下具体sql报错日志信息吧，可能是数据库配置有问题

**Comment by wonderfulwxw** [comment]
![image](https://user-images.githubusercontent.com/38770463/114684312-605cdb80-9d43-11eb-8d12-c8e2b701471a.png)

![image](https://user-images.githubusercontent.com/38770463/114684372-6eaaf780-9d43-11eb-8ca4-05776e1f59d2.png)

![image](https://user-images.githubusercontent.com/38770463/114684500-8c785c80-9d43-11eb-999f-9d6f2b167f22.png)

![image](https://user-images.githubusercontent.com/38770463/114684562-9c903c00-9d43-11eb-9201-7d0c813ed4c8.png)

**Comment by zhangzhaox** [comment]
升级后 需要清除浏览器缓存，不记得日志是否一致，我之前出现过2次都是这样解决的

**Comment by wonderfulwxw** [comment]
@zhangzhaox 
不是同样的问题， 经过手动更改一些table的schema后，问题解决。
