### ISSUE TITLE
[BUG]  v2.3版本PostMan文件导入失败，v2.2.1及以下是成功的

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19533]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

 v2.3版本PostMan文件导入失败，v2.2.1及以下是成功的

### 重现步骤

 按照附件中的文件，在v2.3版本接口定义进行导入，v2.2.1也进行导入一下

### 附加信息

PostMan文件：
[Postman Echo.postman_collection.json.zip](https://github.com/metersphere/metersphere/files/9947717/Postman.Echo.postman_collection.json.zip)

日志异常：
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/32027713/200215706-176a8a93-4910-4eb9-9130-377711d47d74.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.3.1版本已修复，请等待版本发布后验证
