### ISSUE TITLE
[BUG] v1.8.2 接口自动化的子模块中包含了接口用例后无法再重新修改该子模块名称

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#1953]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.2

**Bug 描述**
简要描述您碰到的问题
接口自动化的子模块中包含了接口用例后无法再重新修改该子模块名称

**Bug 重现步骤**
1.  进入接口测试，接口自动化测试页面
2.  添加子模块
3.  在子模块中添加用例，或从其他模块中移动用例到新建的子模块中
4.  重新命名子模块名称，失败

补充：
是否是移动用例时modulePath未设置导致apiscenario中的modulepath未更新？

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde2** [comment]
感谢反馈，下个版本会修复

**Comment by xulinde** [comment]
感谢反馈，下个版本会修复

**Comment by fit2-zhao** [comment]
1.9 已经修复。
