### ISSUE TITLE
[BUG]接口自动化模块，引用的接口case也可以修改请求体的关联文件，但修改后不会生效。应该禁止修改。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19536]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

接口自动化模块，引用的接口case也可以修改请求体的关联文件，但修改后不会生效。应该禁止修改。
<img width="704" alt="5b04438c2575d9c61b7970c08152d8b" src="https://user-images.githubusercontent.com/83771182/200218696-faa84be0-77db-4ddd-a78a-f04f1b253164.png">

### 重现步骤

接口自动化模块，引用的接口case也可以修改请求体的关联文件，但修改后不会生效

### 期待的正确结果

引用的case应该禁止修改。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v2.3.1中已修复。
