### ISSUE TITLE
UI测试导出前置操作中包含数据提取的用例，在导入之后数据提取会丢失[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#19538]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

1、编写UI自动化用例，添加前置操作-数据提取
![image](https://user-images.githubusercontent.com/35896106/200220165-1c8b030a-d187-401d-84fa-aa1b44118e82.png)
2、选择此用例并导出
![image](https://user-images.githubusercontent.com/35896106/200220215-aaad9b3b-74d0-4a1c-b1e2-97f4704a8013.png)
3、在将此用例导入到MS平台，点击查看用例内容，发现前置操作-数据提取没了
![image](https://user-images.githubusercontent.com/35896106/200220332-ce209dbb-1a98-40dc-a186-d11de913421b.png)

### 重现步骤

同上

### 期待的正确结果

可以正常导入导出

**Comment by zrfit** [comment]
您好，已经复现该问题，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.3.1中已修复。
