### ISSUE TITLE
[BUG]请求体为xml格式的mock接口无法使用postman请求命中mock结果

### ISSUE THREAD

**Issue by chimamay** [metersphere/metersphere#19549]
### 联系方式

MeterSphere 交流群48---赤马---may.wang@pkfare.com

### MeterSphere 版本

 v1.20.14-lts-83677fba

### 使用外置数据库

否

### 问题描述

mock功能里，请求体使用xml格式的时候，使用metersphere平台请求mock接口是能正常命中mock规则返回mock结果，但同样的请求条件使用postman请求却没有数据返回。把mock规则里的请求体去掉就能正常返回mock结果了。

### 重现步骤

1.定义一个接口，mock设置里设置请求体为xml格式，参数如下：
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:OTA_HotelSummaryNotifRQ ID="10183307" xmlns:ns2="http://www.opentravel.org/OTA/2003/05">
    <ns2:HotelSummaryMessages xmlns="http://www.opentravel.org/OTA/2003/05" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opentravel.org/2017B/OTA_HotelSummaryNotifRQ.xsd">
        <HotelSummaryMessage StatusType="Closed"/>
    </ns2:HotelSummaryMessages>
</ns2:OTA_HotelSummaryNotifRQ>
响应体设置xml格式如下：
<OTA_HotelSummaryNotifRS  CorrelationID="a4434cab-5e72-11ed-a32a-95a56ae57332"><Errors><Error  Status="NotProcessed" ShortText="Authorization error" Code="497"/></Errors></OTA_HotelSummaryNotifRS>
保存mock规则设置
2.点击mock规则列表上的执行按钮，点击测试，验证能正常返回mock结果
3.在postman上请求mock服务接口，使用一样入参，结果postman上无响应结果返回
![728f4329edf47f01e9917f5b34ba1a2](https://user-images.githubusercontent.com/77480821/200279785-e1a06c42-01c3-4ebb-a70b-f0c39729a1be.jpg)

### 期待的正确结果

mcok能支持xml格式的请求体，不支持的话去掉这个选项

### 附加信息

将mock规则中的请求体格式从xml改成raw，postman能请求成功拿到对应mock结果

**Comment by zyyfit** [comment]
已确认是mock期望中带了\r\n等格式导致，统一格式后正常
