### ISSUE TITLE
[BUG] UI场景引用其他场景，被引用场景的场景变量没有在当前场景中实时更新

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19540]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.3.0及v2.2.0

### 使用外置数据库

否

### 问题描述

1、UI场景B引用的UI场景A刚开始没设置变量，B场景引用了A场景，查看A场景变量是空的；
2、然后去A场景中添加了新的变量，这边在B场景内查看A场景变量还是旧的内容

### 重现步骤

1、引用的场景A刚开始没设置变量，B场景引用了A场景，查看A场景变量是空的；
2、然后去A场景中添加了新的变量，这边在B场景内查看A场景变量还是旧的

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
