### ISSUE TITLE
[BUG]TCP接口GBK编码含中文的，窗口响应体显示问号

### ISSUE THREAD

**Issue by debinlin** [metersphere/metersphere#19546]
### 联系方式

debin.lin@kdlins.com.cn

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

TCP接口GBK编码含中文的，窗口显示问号

### 重现步骤

ZSXN2010140     <?xml version="1.0" encoding="GBK"?>
<RETURN><MAIN><APP /><OKFLAG>0</OKFLAG><REJECTNO>JL:1????</REJECTNO></MAIN></RETURN>

### 期待的正确结果

中文正常显示

### 附加信息

![image](https://user-images.githubusercontent.com/117635032/200270387-f73bcf63-ec20-41d6-bbc5-f029ec55614d.png)

**Comment by debinlin** [comment]
2.0.1的版本可正常显示

**Comment by zyyfit** [comment]
您好，2.3版本已修复了这个问题，您可以升级到最新版 2.3.1 试一下
