### ISSUE TITLE
[BUG]v1.20.16, 接口自动化列表页，直接点击接口自动化场景执行图标，弹出的报告页面“全部”tab页步骤为空

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19561]
### 联系方式

王进

### MeterSphere 版本

v.1.20.16

### 使用外置数据库

否

### 问题描述

v1.20.16, 接口自动化列表页，直接点击接口自动化场景执行图标，弹出的报告页面“全部”tab页步骤为空

### 重现步骤

1. 接口自动化场景列表页，选择一个场景，点击执行图标

![1668147572523](https://user-images.githubusercontent.com/76033005/201276374-77f06279-34a6-47f2-a383-3a7ccdbc0d0f.png)

![1667832906614](https://user-images.githubusercontent.com/76033005/200341104-74c913e4-9db4-4d10-b819-e02c60be271e.png)

**Comment by youliyuan-fit2cloud** [comment]
请问下，是否必现？必现的场景发一下吧

**Comment by 35plus** [comment]
是必现的。
