### ISSUE TITLE
[BUG]接口定义下面的TEST分类下没有“保存”按钮，做的任何修改都无法保存

### ISSUE THREAD

**Issue by spheretangmeng** [metersphere/metersphere#19576]
### 联系方式

微信：zuanshixiu668 “MeterSphere北方区交流群”

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

没办法在接口的TEST下对接口参数工前置后置操作进行调试和保存

### 重现步骤

![Uploading image.png…]()

### 期待的正确结果

有保存按钮，可以正确保存添加的前置脚本和后置脚本

**Comment by youliyuan-fit2cloud** [comment]
![截屏2022-11-08 14 27 05](https://user-images.githubusercontent.com/54612864/200490954-f45586e2-1b1f-48d0-af20-01f4431d09fb.png)

你好，这里只是临时测试用的，如果要保存可以在 “测试”的下拉菜单中 另存为新用例。
