### ISSUE TITLE
[FEATURE]接口测试期望增加数据驱动配置资源池：如登录：常见正常输入、错误输入、xss注入输入方式等。配置成数据池，后续其他地方有类似输入方式直接快速引用为入参

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#19586]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 请描述您的需求或者改进建议

接口测试期望增加数据驱动配置资源池：如登录：常见正常输入、错误输入、xss注入输入方式等。
配置成数据池，后续其他地方有类似输入方式直接快速引用为入参

**Comment by luty2018** [comment]
感谢建议， 需要进一步调研，是否能提供相关功能参考？
