### ISSUE TITLE
[FEATURE]接口自动化，接口标题：超长；滚动条进场拉出重影 

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19592]
### 联系方式

 v2.2.0-3ab59f7c

### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

问题：接口自动化，接口标题滚动条进场拉出重影 ，

### 重现步骤

接口自动化，接口标题：输入很多字符，然后拉标题下的进度条 经常拉出重影不好用

### 期待的正确结果

不拉出重影

**Comment by xhy12** [comment]
![滚动条进场拉出重影 ，建议优化下](https://user-images.githubusercontent.com/43202800/200530138-55ab0305-1cbb-4dbe-928c-08f7b004f25c.png)

**Comment by zyyfit** [comment]
您好，最新版2.2.1没有复现这个问题，建议您升级试试

**Comment by xhy12** [comment]
还是一样从标题头部拉的时候不好拉 ，如果仔细一点找进度条也可以拖动 就是使用体验不是很好

**Comment by luty2018** [comment]
已转需求-接口交互优化
