### ISSUE TITLE
选择项目创建测试显示优化

### ISSUE THREAD

**Issue by Sadomaster** [metersphere/metersphere#196]
1.选择项目之后，点击【创建测试】跳转测试界面不应重新选择项目

**Comment by wangzhen-fit2cloud** [comment]
@shiziyuan9527  在性能测试里选择了某个项目以后，点击列表中的创建测试弹出创建性能测试的页面项目是空的，看下能不能跟接口测试那样，从某个项目下的测试列表点创建测试进来后自动把项目给选上
