### ISSUE TITLE
[BUG] 性能测试持续压3个小时，报告一直是reporting，不能自动变为completed

### ISSUE THREAD

**Issue by tengxunchao** [metersphere/metersphere#19608]
### 联系方式

376110722@qq.com

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

是

### 问题描述

性能测试持续压3个小时，报告一直是reporting，不能自动变为completed
压测任务时间：11月8日  19:35开始压测， 持续：3小时40分钟

datastreaming日志显示： 11-8 19:35开始的压测任务，在23:15已经结束了，后续没有任何日志了
![f9009ee530aaee8ae6264d3293e03b1](https://user-images.githubusercontent.com/54707265/200728688-b0de7038-395e-4991-872b-96e2f2d7244a.jpg)

11月9日查看该报告状态，一直是reporting：
![068a0d2f4ddce613df573ee3b64293c](https://user-images.githubusercontent.com/54707265/200730274-48ecee4b-97e6-452f-8e52-6996fc25fa82.jpg)

11月9日查看该报告，无结束时间：
![5d4942c8220ba21665bda5ea6c879e7](https://user-images.githubusercontent.com/54707265/200730155-bae148b2-45ea-4b2f-8b16-6d019a00c61b.jpg)

bug描述：从datastreaming日志上看，在11月8日23:15压测已经结束了， 但是11月9日看，压测报告一直是 reporting。无法自动变成 Completed.

### 重现步骤

启压测任务，3小时40分钟。
3小时40分钟后，查看压测任务

### 期待的正确结果

11月8日  19:35开始压测， 持续：3小时40分钟。  
期待现象：在11月8日 23:15之后，此压测报告状态自动变为 Completed.
且 支持压测 72小时（稳定性压测需要长时间压测），报告可以生成成功！

### 相关日志输出

```shell
ms-server, node-controller，data-streaming都没有异常日志输出，日志都是正常的。
```

**Comment by xulinde** [comment]
未复现该问题，建议您升级到v1.20.16-lts再试下
