### ISSUE TITLE
[BUG]postman Collection v2.1格式数据导入MeterSphere报错

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19605]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.3.0

### 使用外置数据库

否

### 问题描述

postman Collection v2.1格式数据导入MeterSphere报错，解析数据出错

### 重现步骤

1.导出postman格式为Collection v2.1 json格式
![image](https://user-images.githubusercontent.com/88763608/200574433-79805e5c-47bb-4faf-a726-7b7b0ef21e28.png)

2.导入MeterSphere接口自动化或接口定义。页面报错，解析数据错误
<img width="848" alt="7dcfe2fdeabfe72cd01adb90e854ef7" src="https://user-images.githubusercontent.com/88763608/200574301-9adb67aa-3164-4844-8764-c9ed965d4bdd.png">
<img width="776" alt="594ef304b626f6a4fd5abd055994304" src="https://user-images.githubusercontent.com/88763608/200574313-33d778d2-3d7c-426c-bd4f-456fb23ef063.png">

### 期待的正确结果

正常导入

### 相关日志输出
[MeterSphere.postman_collection.zip](https://github.com/metersphere/metersphere/files/9961429/MeterSphere.postman_collection.zip)

_No response_

**Comment by xulinde** [comment]
用你提供的文件未复现该问题
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/64065190/200760928-b7f18881-4600-46ea-a78c-4dfcd8974521.png">

**Comment by linfengjjj** [comment]
你好 你用的是对外发布的v2.3.0版本吗？

**Comment by linfengjjj** [comment]
不用内测版 用对外发布的v2.3.0官方版本 应该能复现 我在多个环境复现过

**Comment by linfengjjj** [comment]
![image](https://user-images.githubusercontent.com/88763608/200798006-dd50b462-5685-424c-98c9-e1d1ddd4228f.png)
![image](https://user-images.githubusercontent.com/88763608/200798131-7a7cc5cd-592d-4b2f-b2a1-321457be0067.png)
我这边用官方的v2.3.0安装包测试是必现的

**Comment by xulinde** [comment]
v2.3.1已修复～

**Comment by linfengjjj** [comment]
已验证
