### ISSUE TITLE
[BUG]压测时，metersphere有时候刷新很慢，页面很卡

### ISSUE THREAD

**Issue by tengxunchao** [metersphere/metersphere#19611]
### 联系方式

376110722@qq.com

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

是

### 问题描述

压测任务开启时，有时候metersphere页面刷新很慢，页面很卡， 有时候根本刷新不出来.  
属于偶发问题。

metersphere资源给的很高， 压测时资源使用量很低，从资源的角度看基本没压力。
建议优化  系统性能

### 重现步骤

开启metersphere压测任务即可。  属于偶发问题

### 期待的正确结果

压测任务进行时，页面打开速度正常。 无影响。
建议优化系统性能

**Comment by youliyuan-fit2cloud** [comment]
你好，根据目前描述我们没有复现，具体原因要看下您的场景和后台日志信息，或者建议升级到最新的1.20.16-lts版本试试呢？
