### ISSUE TITLE
[BUG] 脑图创建模块和用例，顺序不能保存

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19610]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

脑图创建模块和用例，顺序不能保存

### 重现步骤

在脑图下创建模块和用例，如图
1.创建 用例 1
2.创建 模块 1
3.创建 模块 1/用例 1
4.点击保存按钮，提示保存成功
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4860962/200730565-96511e5d-5bfd-4232-ac6b-42a0affc1d2d.png">

5.切换到列表
6.再次切换到脑图，发现顺序已经不对了
<img width="663" alt="image" src="https://user-images.githubusercontent.com/4860962/200731032-ffc90991-f2f7-4ce9-981b-7394b74d8ca0.png">

**Comment by xulinde** [comment]
您好，模块和用例的顺序是保存不了的，在数据库里都不是一张表

**Comment by hao1032** [comment]
> 您好，模块和用例的顺序是保存不了的，在数据库里都不是一张表

这个不是用户要思考的问题吧，这样就说无需处理，是不是不合适啊。

**Comment by hao1032** [comment]
我这边需要模块和用例有序是这样的，下图为例。
在测试这个表单到时候，我一定是从上往下测试，有些字段相对简单会设置一个用例覆盖，有些字段复杂就会这是为一个模块，下面有几个用例。

这时如果用例和模块的顺序不能保存，就会打乱执行的顺序，要找来找去，非常难用。

<img width="373" alt="image" src="https://user-images.githubusercontent.com/4860962/200854581-2daf6b48-181d-4d4e-90b7-8e06263aa665.png">

<img width="797" alt="image" src="https://user-images.githubusercontent.com/4860962/200856645-22c408cf-ea59-4765-954a-c88da74d78af.png">

**Comment by hao1032** [comment]
我觉得不能因为“在数据库里都不是一张表”去关闭一个 bug，是不是应该考虑该需求是否合理。

如果合理，应该去实现；
如果不合理，可能是我产品用的不熟悉，可以请教一下这个情况该如何处理？

感谢。

**Comment by xulinde** [comment]
> 我觉得不能因为“在数据库里都不是一张表”去关闭一个 bug，是不是应该考虑该需求是否合理。
> 
> 如果合理，应该去实现； 如果不合理，可能是我产品用的不熟悉，可以请教一下这个情况该如何处理？ 又或者需求是合理的但是实现难度大，也可以说明，但是 bug 应该是延期解决，不是关闭。
> 
> 感谢。

您好，这个实现起来难度比较大，我转需求给产品，让她们来评估下吧～

**Comment by hao1032** [comment]
> > 我觉得不能因为“在数据库里都不是一张表”去关闭一个 bug，是不是应该考虑该需求是否合理。
> > 如果合理，应该去实现； 如果不合理，可能是我产品用的不熟悉，可以请教一下这个情况该如何处理？ 又或者需求是合理的但是实现难度大，也可以说明，但是 bug 应该是延期解决，不是关闭。
> > 感谢。
> 
> 您好，这个实现起来难度比较大，我转需求给产品，让她们来评估下吧～

多谢，非常需要这个。

**Comment by luty2018** [comment]
这个问题我们已经收到，我们的脑图背后有一套转换用例的逻辑，这里会相对复杂一点，所以需要进一步调研。

**Comment by luty2018** [comment]
可以的， 我们预计在2023年的Q1进行初步改造。

**Comment by hao1032** [comment]
好的
