### ISSUE TITLE
[BUG]Jmeter本地加断言判断成功，上传平台断言报错

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#19626]
### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

否

### 问题描述

Jmeter本地加断言判断成功，上传平台断言报错

### 重现步骤

1、Jmeter本地给接口加JSON断言，本地断言成功，如下图
![image](https://user-images.githubusercontent.com/5198427/200767962-b5f9290e-22cc-45ef-a5ac-55df9662642f.png)
![image](https://user-images.githubusercontent.com/5198427/200768089-14f49fda-0f96-4c50-861c-25f9236e2e61.png)
2、上传平台后运行，断言失败，提示信息：
Expected to find an object with property ['Succeed'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
![image](https://user-images.githubusercontent.com/5198427/200768223-9b10c285-7eab-41ba-b0fd-07b2ad0d50ec.png)

补充说明：
![image](https://user-images.githubusercontent.com/5198427/200768590-53a0a604-9724-4649-9ffa-d619828262ed.png)
勾选此选项，本地Jmeter断言也会失败，提示和平台一样，但是不勾选此选项本地断言就是成功的。

### 期待的正确结果

本地断言成功，上传平台断言也应该如本地一样

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，方便把jmx文件贴上吗？我们进一步确认下是什么原因？
