### ISSUE TITLE
[QUESTION]性能测试完成发报告邮件的模板在哪里配置呢

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#19633]
### 请描述您的问题

性能测试完成后配置消息通知发送邮件， 邮件内容是默认的，如果想修改邮件内容，在哪里可以配置呢？

**Comment by luty2018** [comment]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/36292514/201250666-0d4cfea2-ad7a-42b7-ace7-4528af4fd811.png">

自定义消息通知模板是企业版功能， 可以申请试用。
