### ISSUE TITLE
[BUG]ui测试需要最新的chrome版本

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19632]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

ui测试，访问被测环境 a 加载不出登录界面，换一个测试环境b就可以访问。排查相关日志后后大老师说要更新最新ui测试需要最新的chrome版本

### 重现步骤

ui测试，访问被测环境 a 加载不出登录界面，换一个测试环境b就可以访问

![530306abf2c82c3b965e94a4624cc67](https://user-images.githubusercontent.com/43202800/200791972-1c82aec5-f303-4542-8908-3a593f48771c.jpg)

![c7a47063c928ab8b5f5408081c65a42](https://user-images.githubusercontent.com/43202800/200792047-5ab071b8-3432-4572-8009-99b537f0c0a7.jpg)

### 期待的正确结果

ui测试需要最新的chrome版本

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题为已知问题，后续版本修复。
