### ISSUE TITLE
[BUG]v2.3.0-f7d4cc4e版本测试计划完成后，不能手动保存测试报告；

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#19639]
### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

测试计划完成后，不能手动保存测试报告；

### 重现步骤

1. 创建测试计划
2. 执行完成，配置报告模板：删除接口、性能、UI等模块用例显示；
3. 单击保存测试报告

### 期待的正确结果

能正确的保存测试报告，并在【报告】标签页中显示

### 相关日志输出

```shell
请求链接：
http://172.27.62.71:8081/track/test/plan/report/saveTestPlanReport/72819699-2fe2-42ce-b39f-91c196af5034/MANUAL

响应
{"timestamp":1668043487625,"status":500,"error":"Internal Server Error","path":"/test/plan/report/saveTestPlanReport/72819699-2fe2-42ce-b39f-91c196af5034/MANUAL"}

msctl status查看所有的容器都是healthy状态
```

**Comment by ChangqiaoWang** [comment]
版本为全新在线安装。

**Comment by youliyuan-fit2cloud** [comment]
![图片](https://user-images.githubusercontent.com/54612864/200990568-5e387317-5b2b-464f-94f9-06610dfd7a37.png)

你好，同一个版本，没有复现这个问题。看你这个报告链接是不对的，缺少/track 路径，建议更新到最新版本 v2.3.1 或者清理下缓存？

**Comment by ChangqiaoWang** [comment]
get请求链接于你的是一样的，http://172.27.62.71:8081/track/test/plan/report/saveTestPlanReport/72819699-2fe2-42ce-b39f-91c196af5034/MANUAL

respone回复的链接缺少/track。

更换其他的浏览器也是一样的结果。

**Comment by ChangqiaoWang** [comment]
![企业微信截图_16680690665367](https://user-images.githubusercontent.com/6109912/201040402-55aecef8-1ce2-4f70-ad1d-f507b54e0551.png)

升级到v2.3.1也是一样的错误，是否跟我们采用全新安装有关；我们采用1.20.0版本升级到2.2.1版本这个功能是正常的。

**Comment by youliyuan-fit2cloud** [comment]
https://live.vhall.com/v3/lives/watch/269836764

开源版bug。。。这个链接试用企业版吧😂

**Comment by youliyuan-fit2cloud** [comment]
> ![企业微信截图_16680709317475](https://user-images.githubusercontent.com/6109912/201046998-6d965aaa-7f2c-4523-ada1-45bce500fa52.png) [info.txt](https://github.com/metersphere/metersphere/files/9979100/info.txt)

你好，请重新升到到v2.3.1，有修复该问题。
