### ISSUE TITLE
[BUG]jsonpath断言，响应体中字段为null的值识别不到，导致断言失败

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#19637]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

jsonpath断言，响应体中字段为null的值识别不到，导致断言失败

### 重现步骤

1.可以用mock环境，mock响应体为
{
    "code": 0,
    "message": "成功",
    "data": {
        "price": 1,
        "amount": null,
        "currency": null,
        "orderDetailVOList": null
    }
}
2.用推荐jsonpath断言data
![image](https://user-images.githubusercontent.com/103627487/200827354-972ee8f8-698b-46a3-887f-58e56711bc9a.png)
3.查看断言结果，字段为null的值未取到
![image](https://user-images.githubusercontent.com/103627487/200827514-4394da49-468b-41ec-b940-370fe7fe1ca7.png)

### 期待的正确结果

能正确断言

**Comment by youliyuan-fit2cloud** [comment]
Jmeter不支持，我们暂时不处理。

**Comment by meijieDouDou** [comment]
jmeter是支持的
![image](https://user-images.githubusercontent.com/103627487/209790042-4a8de20e-7ab9-496d-a9fd-e99e803e19da.png)
![image](https://user-images.githubusercontent.com/103627487/209790294-eefd1d4c-f83c-4cfd-bb28-21c8d299a475.png)
ms响应体中字段为null的值断言识别不到，导致断言失败，2.5.0版本就可以，1.20.17lts就会失败

**Comment by youliyuan-fit2cloud** [comment]
v1.20.18-lts中已修复，请升级一下吧。
