### ISSUE TITLE
[BUG]Swagger 导入报解析数据错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#19649]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

1.Swagger 导入报解析数据错误
![image](https://user-images.githubusercontent.com/103627487/201045554-4caf884b-9f45-4627-8da4-26c8ed873e9a.png)
![image](https://user-images.githubusercontent.com/103627487/201046006-e14bbda1-20e1-4697-9506-abfd260c50e1.png)

### 重现步骤

Swagger 导入

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
