### ISSUE TITLE
[BUG]测试计划-测试报告--失败用例（默认ID长度显示不全）

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#19644]
### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/19423100/200994032-e37c38d4-5935-4ca5-bba1-d53ee4dba948.png)
[BUG]测试计划-测试报告--失败用例（默认ID长度显示不全）

### 重现步骤

测试计划-测试报告--失败用例（默认ID长度显示不全）

### 期待的正确结果

显示完整的ID,至少默认显示完全，同时我记得之前可以调整列宽，现在没找到（以前调整列宽也挺费劲的）

**Comment by legend818** [comment]
这种优化不费劲啊，建议早处理

**Comment by xulinde** [comment]
v2.4.0已做优化～
