### ISSUE TITLE
[BUG]接口用例的断言修改后，场景里的用例断言没有同步被修改，而是在旧的断言的基础上进行追加

### ISSUE THREAD

**Issue by jun168** [metersphere/metersphere#19643]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

1、在接口用例中，修改断言；
2、到场景里面，查看对应被引用的断言；
3、场景里面被引用的用例断言没有同步被修改，而是在旧的断言的基础上进行追加

### 重现步骤

1、在接口用例中，修改断言；
2、到场景里面，查看对应被引用的断言；
3、场景里面被引用的用例断言没有同步被修改，而是在旧的断言的基础上进行追加

### 期待的正确结果

接口用例的断言修改后，场景里的被引用的用例断言应同步被修改，而不是追加

### 附加信息

![image](https://user-images.githubusercontent.com/43701366/200992201-956deb6f-5f16-4f77-974d-b52a0acf6446.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，v2.2.1版本以上没有这个问题，升级一下 ？
