### ISSUE TITLE
[BUG]V2.3.0压测时不配置域名绑定报错Non HTTP response code: java.net.UnknownHostException

### ISSUE THREAD

**Issue by BigDarkOrange** [metersphere/metersphere#19641]
### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

压测时，若接口为域名非IP并且未配置域名解析，则压测时报错Non HTTP response code: java.net.UnknownHostException

### 重现步骤

1、接口定义为域名地址
2、所载项目环境管理不配置域名解析
3、压测时高级配置不配置域名解析
4、执行压测

### 期待的正确结果

请求正常

**Comment by xulinde** [comment]
未复现该问题，在接口那能调试成功吗

**Comment by BigDarkOrange** [comment]
API测试正常调用，只有性能测试时异常

**Comment by BigDarkOrange** [comment]
![image](https://user-images.githubusercontent.com/112859774/201248499-2619e65e-0ded-4813-9104-674d21b7b101.png)
![image](https://user-images.githubusercontent.com/112859774/201248592-d242d208-2e6e-4058-9ec9-bca287abeb60.png)
![image](https://user-images.githubusercontent.com/112859774/201248847-0c9f2bd7-e74c-420b-bc0e-53b40f59d8b0.png)
![image](https://user-images.githubusercontent.com/112859774/201248886-f5cdb6a0-d39e-4738-b072-f69f83978749.png)

配置上域名解析后就正常了

**Comment by xulinde** [comment]
这个报错原因一般是dns解析错误，或者网络不通。请自行检查下

**Comment by BigDarkOrange** [comment]
单接口一直可以正常请求，换了性能测试就报错，服务器内ping 这个域名也是正常的，如果是dns解析错误的话，为什么单接口测试可以通过呢

**Comment by xulinde** [comment]
方便把场景导出来吗

**Comment by BigDarkOrange** [comment]
[执行成功.zip](https://github.com/metersphere/metersphere/files/10040380/default.zip)
[执行失败.zip](https://github.com/metersphere/metersphere/files/10040381/default.zip)
执行成功ZIP中我把host文件改了下，原数据是正常的

**Comment by xulinde** [comment]
跟研发确认了，内部域名需要配置才能正常使用，jmeter也是这样

**Comment by BigDarkOrange** [comment]
好的
