### ISSUE TITLE
[FEATURE]测试计划支持从已执行完毕的测试计划中选取非执行成功的用例

### ISSUE THREAD

**Issue by ZaZing** [metersphere/metersphere#19646]
### MeterSphere 版本

v2.3.0

### 请描述您的需求或者改进建议

在测试流程中，无论瀑布还是敏捷，测试均需要多轮测试，除了完备的自动化测试能支持全量测试，手动测试均会在每轮测试进行用例筛选。在现有的meterspher中，测试计划只支持对用例集合进行筛选，而通常二轮或者更多轮次的筛选，会在用例集中选取核心用例+上轮未执行成功的用例，当前无法实现。

### 请描述你建议的实现方案

避免功能的复杂性，尽量不改动原有逻辑，且符合测试工作形态，可以在报告页面增加创建新计划按钮，创建时输入测试计划名称，同时默认选择当前报告页面对应计划内未执行成功的用例。

**Comment by luty2018** [comment]
感谢建议， 我们已经规划了这个功能， 预计会在3个版本左右上线。
