### ISSUE TITLE
功能用例增加引用用例功能（类似接口引用）

### ISSUE THREAD

**Issue by damowang-lcc** [metersphere/metersphere#19657]
### MeterSphere 版本

v1.21.x-lts

### 请描述您的需求或者改进建议

userstory：在现有的项目中，我们一个项目有大约几万条case，存在大量模块的case相同，导致需要重复的添加，但一个相同case发生增加测试点的时候，其他case都需要改变

### 请描述你建议的实现方案

建议在case中和接口自动化一样，引用了公共的case后，我只需要维护修改公共的case。对应的下属模块的case都改变，这样就能很方便的进行维护

**Comment by luty2018** [comment]
收到， 感谢反馈
