### ISSUE TITLE
[QUESTION] MeterSphere Jenkins 插件 v2.3.1 安装后在Jenkins验证账户报错

### ISSUE THREAD

**Issue by lxshopping** [metersphere/metersphere#19652]
### 请描述您的问题

Jenkins安装完metersphere-jenkins-plugin-v2.3.1.hpi 插件，构建自由风格的软件
具体报错信息：
验证MeterSphere帐号失败！com.alibaba.fastjson.JSONException: field null expect '[', but string, pos 2, line 1, column 3"",field null expect '[', but string, pos 2, line 1, column 3""

**Comment by liuruibin** [comment]
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/23045261/201291112-1f6e9cf0-7bdb-40f6-84ab-76b2f4b63616.png">
我自己在jenkins上安装2.3.1没这个问题

**Comment by dreamerwyx** [comment]
> ### 请描述您的问题
> Jenkins安装完metersphere-jenkins-plugin-v2.3.1.hpi 插件，构建自由风格的软件 具体报错信息： 验证MeterSphere帐号失败！com.alibaba.fastjson.JSONException: field null expect '[', but string, pos 2, line 1, column 3"",field null expect '[', but string, pos 2, line 1, column 3""

我也遇到了这个问题，我知道怎么解决了。
其实就是插件版本不匹配的问题。
首先查看你的metersphere版本，然后去下载对应版本的插件就可以了。
[https://github.com/metersphere/jenkins-plugin/releases](https://github.com/metersphere/jenkins-plugin/releases)
