### ISSUE TITLE
[BUG]redis中spring.session相关key疯狂刷数据

### ISSUE THREAD

**Issue by CodeDream-Mo** [metersphere/metersphere#19653]
### 联系方式

1503991544@qq.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

无论是使用外置redis还是内置redis，redis中都在疯狂刷数据，不是一直刷，感觉好像定时刷，每次大概会持续半小时到1小时，就一直在刷spring.session相关的数据，我可以保证当时我们内部人员没有人在使用，并且访问网站是有ip白名单

### 重现步骤

就按照官方在线部署后，过半天就可以发现莫名多了很多数据

### 附加信息

![截图](https://user-images.githubusercontent.com/35525664/201070912-3a2719dd-8b65-4823-ab86-d4b8ebccf9cf.png)
![企业微信截图_16679796547791](https://user-images.githubusercontent.com/35525664/201071442-92d23ef3-ece2-44c4-bfc7-5e6965fa4a14.png)

**Comment by liuruibin** [comment]
检查数据库的定时任务或jenkins定时任务，是否有通过apikey方式调用
