### ISSUE TITLE
[QUESTION]请先根据代码中的 build.md 操作后，下载ms-jmeter-core的代码到本地选择2.3的分支执行mvn install

### ISSUE THREAD

**Issue by HFwas** [metersphere/metersphere#19668]
请先根据代码中的 build.md 操作后，下载ms-jmeter-core的代码到本地选择2.3的分支执行mvn install

_Originally posted by @liuruibin in https://github.com/metersphere/metersphere/issues/19656#issuecomment-1311162721_
      

执行之后还是报错

**Comment by HFwas** [comment]
报错信息在这个issue下：https://github.com/metersphere/metersphere/issues/19656

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/19656#issuecomment-1313171709
