### ISSUE TITLE
[BUG]B项目引用A项目时，在请求里设置环境变量，已有的环境变量的值没有更新，而是在其他环境处新增了环境变量。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#19677]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

在B项目引用A项目的case，选择对应环境后，使用变量时使用的是其他项目的环境变量，但是设置环境变量时却没有对应更新其他项目变量值，而是在本身环境变量处新增了变量。

### 重现步骤

1. 在 测试项目导入 默认项目的接口case，选择 默认项目的百度环境，测试项目的TEST环境
![image](https://user-images.githubusercontent.com/104960608/201298475-ebdbad13-bd7c-45a2-a14f-fdff6ace285c.png)
![image](https://user-images.githubusercontent.com/104960608/201298748-13662ef8-3de9-42a1-9203-ee2aa12fb6c1.png)
2. 默认项目的百度环境没有age变量，测试项目的TEST环境有age变量
![image](https://user-images.githubusercontent.com/104960608/201299017-39272b0f-945b-4643-b2fe-a656e57da372.png)
![image](https://user-images.githubusercontent.com/104960608/201299184-4aa7f704-7a23-452c-a1ba-8104dee46564.png)
3. 在请求后置脚本里打印并执行脚本，点击调试
![image](https://user-images.githubusercontent.com/104960608/201299353-62aed579-f6e5-4683-b6e7-02c2bd8b1231.png)
4. 控制台打印出测试项目的TEST环境的age变量
![image](https://user-images.githubusercontent.com/104960608/201299787-cd775ca2-7a89-411b-91d1-402590ab67e9.png)
5. 测试项目的TEST环境age变量值没有更新，但是默认项目的百度环境新增了age变量。
![image](https://user-images.githubusercontent.com/104960608/201299472-96b99455-8ce1-4c17-b5aa-ac06cfdffec3.png)
![image](https://user-images.githubusercontent.com/104960608/201299564-44204b2d-a678-49ee-bbdb-98e3bd81e7df.png)

**Comment by zyyfit** [comment]
您好，感谢您的反馈，目前的逻辑是这样的：
1、如果项目A的场景，引用了其他项目的case，在选择环境的时候需要选择其他项目的环境，执行场景的时候就会把其他项目的环境变量和当前项目的环境变量放在一起使用，所以可以引用到，
2、设置环境变量的时候，由于带上了项目的环境ID ${__metersphere_env_id} 这个参数，所以保存的时候会存到引用的case所在的项目
