### ISSUE TITLE
[BUG] 引用或复制rpc场景保存时SQL错误，method 字段太长

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#19681]
### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/9674075/201281675-505ed1c5-6abb-4ed6-95b6-85eeee746352.png)
2022-11-11 13:52:46,233 [XNIO-1 task-3] ERROR i.m.c.h.RestControllerExceptionHandler 176 - Method[sqlExceptionHandler][Data truncation: Data too long for column 'method' at row 1]
java.sql.BatchUpdateException: Data truncation: Data too long for column 'method' at row 1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 
前端发送的数据为：
![image](https://user-images.githubusercontent.com/9674075/201282943-a8779887-53b6-4f05-851e-8a14eb2a1091.png)

package io.metersphere.api.service;
ApiScenarioReferenceIdService.java文件中处理RPC方法提取时，默认会使用rpc method
    private String getMethodFromSample(JSONObject item) {
        String method = null;
        if (item.containsKey(MsHashTreeService.TYPE) && item.containsKey(MsHashTreeService.METHOD) && StringUtils.equalsIgnoreCase(item.getString(MsHashTreeService.TYPE), "HTTPSamplerProxy")) {
            method = item.getString(MsHashTreeService.METHOD);
        } else if (item.containsKey(MsHashTreeService.TYPE) && StringUtils.equalsAnyIgnoreCase(item.getString(MsHashTreeService.TYPE), "DubboSampler")) {
            method = RequestType.DUBBO;
        }
        return method;
    }

2. ApiScenarioReferenceIdService.deepElementRelation方法中如下
//                    if (item.containsKey(MsHashTreeService.METHOD)) {
//                        method = item.getString(MsHashTreeService.METHOD);
//                    }
                    String method = this.getMethodFromSample(item);

### 重现步骤

在一个接口自动化场景中，引入RPC场景并保存

**Comment by zyyfit** [comment]
您好，1.20最新版没有复现这个问题，建议您升级试试
如果升级还是有问题的话，可以把您引用的那个dubbo场景导出来给我们看一下吗？
