### ISSUE TITLE
[BUG]选中一条接口用例使用批量编辑修改用例等级，结果所有用例的用例等级全都被修改了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19689]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.16-lts

### 使用外置数据库

否

### 问题描述

选中一条接口用例使用批量编辑修改用例等级，结果所有用例的用例等级全都被修改了

### 重现步骤

1.点击某个接口，进入接口编辑页面
![image](https://user-images.githubusercontent.com/88763608/201365688-7fe72d5c-7219-492b-af2a-7e0d9f315ddb.png)
![image](https://user-images.githubusercontent.com/88763608/201365750-e255b3ee-ecb5-47c9-b70e-1220bad971c3.png)
2.点击“CASE”，进入该接口的CASE列表
![image](https://user-images.githubusercontent.com/88763608/201365870-867f1b65-d398-45a8-826a-21c5c3b81a56.png)
3.勾选列表中的用例，并且点击“选择所有数据”
![image](https://user-images.githubusercontent.com/88763608/201366025-79dc5b7b-eaf2-4a40-8de5-7b955d2cc0dd.png)
4.点击批量编辑，修改该用例等级为P3
![image](https://user-images.githubusercontent.com/88763608/201366325-3ea5ff88-e19c-4016-9108-8d3d75d993af.png)
5.结果所有CASE的用例等级都变成了P3
![image](https://user-images.githubusercontent.com/88763608/201366493-3510bdbb-8af0-4f14-bb11-4251c53e4269.png)

### 期待的正确结果

按上面的截图来看，应该只修改一条用例的等级才对

### 附加信息
附件是复现视频
_No response_
[批量修改用例属性.zip](https://github.com/metersphere/metersphere/files/9991098/default.zip)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
