### ISSUE TITLE
[BUG]用css选择器在浏览器上可以找到目标元素，但是在ui脚本里面找不到

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19686]
### MeterSphere 版本

 v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

用css选择器在浏览器上可以找到目标元素，但是在ui脚本里面找不到

### 重现步骤

比如百度找热搜词条：通过css选择器 span.title-content-title:contains('国家卫健委：不再判定次密接')  可以找打元素
再比如下拉框里面定位元素有空格：div.dropdown-content li:last-child 也可以找到元素

但是放到脚本里面就不行了

![d424e4411967facf9425ffb0cd12f19](https://user-images.githubusercontent.com/43202800/201317530-eea6c8ab-4695-4582-b4f2-e813a55d7456.jpg)
![image](https://user-images.githubusercontent.com/43202800/201318475-7f307c2a-cea1-4d92-a774-e30e8ab36c93.png)

### 期待的正确结果

页面css能找到，脚本应该也能找到

**Comment by xhy12** [comment]
[Metersphere_Ui_演示项目.txt](https://github.com/metersphere/metersphere/files/9989262/Metersphere_Ui_.txt)
脚本如下，改了下文件后缀 改为.side应该可以用

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、附件中的脚本在ide中运行也是失败的。
2、页面中元素的查找与CSS表达式不是对等的。
3、页面中元素CSS表达式的获取方式为：打开浏览器 >>【F12】>> 点击Elements标签 >> 定位元素后右键选择Copy >> Copy selector。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/201353249-ab38a7bd-4459-4e01-8248-a398bfde077b.png">
4、验证CSS表达式：打开浏览器 >>【F12】>> 点击Elements标签 >> 【Ctrl +F】>> 在搜索框中输入或粘贴任何CSS Selector表达式 >> 回车查看查找结果。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/99731894/201353544-583246ea-fc60-45c4-ad71-42b729a6b6f2.png">

**Comment by xhy12** [comment]
这个在页面元素可以找到，ide验证里面的括号是中文括号，改成应该才能识别，需要处理下字符

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/201588489-38ca601c-e78b-4fb7-9532-29ade3759dc6.png)
[Metersphere_Ui_演示demo (1).txt](https://github.com/metersphere/metersphere/files/10000083/Metersphere_Ui_.demo.1.txt)

**Comment by xhy12** [comment]
主要是想问为什么 f12能找到元素，为什么放到 ide不行呢？css 语法也没错呀 这点很困扰

**Comment by zrfit** [comment]
css  :contains() 问题，selenium当前不支持。
http://stackoverflow.com/questions/14595149/alternative-of-contains-in-cssselector-selenium-webdriver
