### ISSUE TITLE
[BUG] 导出性能测试报告为pdf，报告里的监控详情缺少被测机监控信息

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19692]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

导出性能测试报告为pdf，报告里的监控详情缺少被测机监控信息

### 重现步骤

192.168.0.200是被测机

性能测试增加被测机信息
![61ceeb1c578a2abd3298b7bd83f275a](https://user-images.githubusercontent.com/103925124/201460556-b89c7fe8-0c3a-443c-96df-75735fdb2a26.png)
测试报告可查看
![ab433af5f612faa8c2c234f378fa831](https://user-images.githubusercontent.com/103925124/201460567-a27289b9-2693-48d3-bc13-be0918209e75.png)
pdf缺少被测机监控信息
![2f5ca8b1d22172c1ac5da014bb94f63](https://user-images.githubusercontent.com/103925124/201460524-99c7e8df-2ab3-402a-9d49-a9f757b33c22.png)

**Comment by xulinde** [comment]
导出只有第一个值的，是静态的
