### ISSUE TITLE
旧版本，转场景测试后， 切到新版本，关联场景用例出现sql异常[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#1970]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
1.5旧版本，转场景测试后， 切到新版本1.8.2，关联场景用例出现sql异常（主键冲突）
**Bug 重现步骤**
1.  旧版本1.5转场景测试
![image](https://user-images.githubusercontent.com/80814232/113992151-bdf5b180-9885-11eb-887c-af58f6245e2e.png)

2. 切换到新版本1.8.2，选择对应项目，测试计划-接口测试用例-场景用例-关联
![image](https://user-images.githubusercontent.com/80814232/113992339-ef6e7d00-9885-11eb-82b3-a507c99bc759.png)

3. 点击确定出现sql异常，后台日志如下
![image](https://user-images.githubusercontent.com/80814232/113992363-f5fcf480-9885-11eb-91f9-97985a52865a.png)

**期待的正确结果**
正确情况下应该是什么样的？
正常关联
**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by fit2-zhao** [comment]
这个问题始终无法正常复现，建议把转过来有问题那条数据删除 ，用最新版本重新转一下。
