### ISSUE TITLE
[BUG]LTS版本，自定义请求的url使用变量，会自动新增一个多余的“http”

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19701]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.16-LTS

### 使用外置数据库

否

### 问题描述

LTS版本，脚本设置url变量为https:/xxxxxx，自定义请求的完整请求地址使用变量${url}，会自动新增一个多余的“http”

### 重现步骤

1.自定义脚本设置url变量
url = "https://www.baidu.com";
vars.put("url",url);
log.info(vars.get("url"));
2.自定义请求中引用url变量，自动加了一个多余的"http"
![image](https://user-images.githubusercontent.com/88763608/201565612-146c76da-f6a3-4194-b1aa-18ae2d40bc4e.png)
3.主线版本是正常的，LTS版本有问题
![image](https://user-images.githubusercontent.com/88763608/201565687-d43542bc-4010-467a-a896-44f158da6e89.png)

### 期待的正确结果

不应该带上多余的http。
https://github.com/metersphere/metersphere/issues/19227 这个问题修复后，导致的新问题。

### 相关日志输出

```shell
附件有复现场景
```

### 附加信息

[Metersphere_Scenario_验证项目.zip](https://github.com/metersphere/metersphere/files/9999165/Metersphere_Scenario_.zip)

**Comment by zyyfit** [comment]
1.20.17已修复，请等待版本发布后验证
