### ISSUE TITLE
[BUG] 修改接口定义，关闭一键同步case按钮，不起作用。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19704]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.2.1-51f7f392

### 使用外置数据库

否

### 问题描述

修改了接口定义的参数，关闭一键同步case按钮，然后保存。点击到case里面，还是会同步过来的。

![image](https://user-images.githubusercontent.com/33945037/201567619-d714de83-c5de-4f1f-9617-2250db9a0a69.png)
![image](https://user-images.githubusercontent.com/33945037/201567648-5bfd42c0-a38b-47ce-a7b2-a3e0b047a0af.png)
![image](https://user-images.githubusercontent.com/33945037/201567682-7a9e7d33-e944-4262-94cc-6ec43b496025.png)

当 开启了一键同步case按钮，关闭下面的同步设置，则不会同步。
![image](https://user-images.githubusercontent.com/33945037/201567995-b4e60366-fb7a-48ba-ba20-ef4bbf3b7ddd.png)

### 重现步骤

接口定义页面修改，然后点击保存，修改一键同步case操作。

### 期待的正确结果

当关闭大按钮，则都应该不同步才对。

**Comment by zrfit** [comment]
您好,最新版本v2.3.1无该问题，建议升级尝试。
