### ISSUE TITLE
[BUG]  【UI测试】UI场景导入指令或者场景-原场景变量无法使用

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#19706]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

UI场景导入指令或者场景-原场景变量无法使用

### 重现步骤

1.在原场景或者指令中使用变量
2.创建一个新场景
3.导入场景或者变量
4.执行
5.观察场景执行结果

### 期待的正确结果

1.引用的场景能使用原场景的变量
2.如果不使用原场景的变量，在新场景设置的变量也可以引用

### 附加信息

1.原f场景变量
![image](https://user-images.githubusercontent.com/45531073/201584167-31885efd-fe24-4404-aa57-d8154639bd47.png)
2.在新场景中执行
![image](https://user-images.githubusercontent.com/45531073/201584348-fccd25a0-9648-4877-8eae-089045d31283.png)

**Comment by zrfit** [comment]
您好，最新版本v2.3.1不存在该问题，场景中导入场景-原场景变量可引用成功；导入场景取消勾选原场景变量-引用当前场景变量也成功，建议升级至最新版本。
