### ISSUE TITLE
[BUG]【用例评审】测试用例自定义ID后，在用例评审列表还显示为系统生成的ID

### ISSUE THREAD

**Issue by fushipeng2022** [metersphere/metersphere#19703]
### 联系方式

交流群45，付世鹏，fushipeng@126.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

是

### 问题描述

自定义ID的测试用例在用例评审关联的测试用例列表显示的ID不正确

### 重现步骤

1、项目启用“测试用例自定义ID”设置。
2、新建/导入测试用例，此时测试用例ID为自定义的ID。
3、创建用例评审，关联该自定义ID的测试用例，查看ID显示。

### 期待的正确结果

显示为自定义ID。

### 附加信息

![image](https://user-images.githubusercontent.com/110213256/201567635-0e84bb31-4e1a-43e7-8e05-b84c06623782.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0中已修复。
