### ISSUE TITLE
[FEATURE]接口测试，JSON_SCHEMA中不支持使用null值，会转化为空值

### ISSUE THREAD

**Issue by chenfeng-fang** [metersphere/metersphere#19720]
### MeterSphere 版本

2.3.1

### 请描述您的需求或者改进建议

json请求中key值为null的情况，在切换到json-schema中会转换为空值
![image](https://user-images.githubusercontent.com/50090858/201618517-d00040a2-fbb6-4c39-a763-6214fea7821b.png)
![image](https://user-images.githubusercontent.com/50090858/201618543-99a4f5d6-72f6-4049-b178-a08c5483d15d.png)

业务上存在有需要传递null值，传空值反而会报错的场景。

在json中写是可以，但是json中就不能对字段进行说明注释了

### 附加信息

像apifox中在json结构化的时候会提供null类型来支持传null值，或许可以参考一下
![image](https://user-images.githubusercontent.com/50090858/201618941-a595180a-68a9-4435-8c2d-0bdaacbccf65.png)

**Comment by luty2018** [comment]
感谢建议， 我们处理一下。
