### ISSUE TITLE
接口case  加了前置SQL 转换为性能测试后 就无法正确的连接数据库了，缺少jdbc的驱动，转性能时  这个驱动  没正常带过去，导致无法连接.[BUG]

### ISSUE THREAD

**Issue by fengwanjie** [metersphere/metersphere#19724]
### 联系方式

move_flower@163.com

### MeterSphere 版本

v1.20.9-lts-8cf9990f

### 使用外置数据库

是

### 问题描述

接口case  加了前置SQL 转换为性能测试后 就无法正确的连接数据库了，缺少jdbc的驱动，转性能时  这个驱动  没正常带过去，导致无法连接。

### 重现步骤

接口case  加了前置SQL 转换为性能测试后 就无法正确的连接数据库了，缺少jdbc的驱动，转性能时  这个驱动  没正常带过去，导致无法连接。

**Comment by zyyfit** [comment]
您好，1.20 的最新版没有复现这个问题，请升级后试试，
如果升级后还是不行，可以把您的CASE导出来给我们看一下吗？重要信息可以脱敏
