### ISSUE TITLE
[BUG]Azure DevOps 批量关联需求，需求列表没展示

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#19721]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

Azure DevOps 批量关联需求，需求列表没展示
![image](https://user-images.githubusercontent.com/30038088/201619737-2891dbbe-f23d-4ff8-9194-9b3f0f61e691.png)

### 重现步骤

功能用例列表，选择 批量关联需求

### 期待的正确结果

![a90baff01d5020b050886f1cdbe8b78](https://user-images.githubusercontent.com/30038088/201619882-33b62c68-21a2-48f8-a7bb-8e19e09fa2c9.png)

**Comment by xulinde** [comment]
未复现该问题，检查下服务集成-需求类型和Azure一致吗？
<img width="610" alt="image" src="https://user-images.githubusercontent.com/64065190/201816233-a9761de3-22e4-43a7-abb0-83b29a587fcc.png">

**Comment by shenkaibo** [comment]
今天试了下 又可以了 ！
