### ISSUE TITLE
[FEATURE] 导出接口自动化场景后无附件

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#19729]
### MeterSphere 版本

v1.20.16

### 请描述您的需求或者改进建议

对于接口自动化有使用附件的POST请求，和场景环境变量中有使用csv文件的场景，导出后再到导入，无法使用。
需要找到缺失附件的位置再重新上传文件，查找和操作比较繁琐。

希望：
1. 导出时场景+附件+环境变量文件，可以压缩保存
2. 导入时，可以实现解压到该场景下，可正常使用，不需要再人工介入

**Comment by luty2018** [comment]
感谢建议， 导入导出暂时还没有计划，可以在上传文件的地方提供文件下载功能是否能改善目前的操作呢？

**Comment by xchnshi** [comment]
自动化场景的附件或环境变量的附件，应该是放到指定项目id的路径下，且命名有一定规范。而上传文件并不能直接找到接口自动化场景所在位置。

**Comment by luty2018** [comment]
主要是文件导出再导入的时候要将文件和场景对应起来进行解析，这里的逻辑就会比较复杂，所以是否有其他方法可以覆盖你的需求。
