### ISSUE TITLE
[BUG] 【接口自动化】文件上传后，会在文件名前，自动加一串随机值（预期：保留原文件名）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#1972]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
【接口自动化】文件上传后，会在文件名前，自动加一串随机值（预期：保留原文件名）

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
保留原文件名

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/114001260-5859f300-988e-11eb-957e-373e4c1bb050.png)

**Comment by xulinde** [comment]
后面版本可以优化下

**Comment by xulinde** [comment]
1.10版本已修复
