### ISSUE TITLE
[BUG]v2.3   浏览器兼容问题：firefox 浏览器 功能用例 脑图内容显示错位

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19732]
### MeterSphere 版本

2，3

### 使用外置数据库

否

### 问题描述

浏览器兼容问题：firefox 浏览器 功能用例 脑图显示错位

### 重现步骤

问题：使用firefox 查看脑图，用例内容显示错位。如图
![v2 3 firefox 浏览器脑图显示错位](https://user-images.githubusercontent.com/43202800/201837127-1d25becd-0fcd-49ee-aa49-5d8d79fbe6af.png)

### 期待的正确结果

显示不错位

**Comment by xulinde** [comment]
在线的百度脑图也有这个问题，目前无法修复，得等百度脑图修复
