### ISSUE TITLE
[BUG]  一键同步，单独只开启一个请求体同步，不生效。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19736]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.2-51f7f392

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33945037/201851051-1bc15459-4a01-4640-bba9-bdaf94c0f677.png)
1. 只勾选同步“请求头”，则不生效。
2. 必须上面和下面都要勾选上，才能同步。

### 重现步骤

如上图所示

### 期待的正确结果

应该只勾选单个的时候，就可以同步。

**Comment by zyyfit** [comment]
您好，2.3.1版本没有复现这个问题，请升级后使用

**Comment by hao65103940** [comment]
https://user-images.githubusercontent.com/33945037/202100790-824bc599-1a33-484c-92b2-bf287a39fb20.mp4


视频中演示了两个问题：

问题1. 当只设置请求体同步的时候，在接口定义里面新添加字段，保存之后，case里面没有添加对应字段。必须开启“删除用例中无法与API文档对应的参数”才能同步。
应该是开启同步什么，就同步什么。

问题2. 当一个接口定义，有很多case的时候，并且每个case的参数值都不相同。假设，开发同学改了一个参数字段名，这个时候需要同步到所有的case里面，这个时候勾选了“删除用例中无法与API文档对应的参数”，就会把旧case里面的参数值给删除掉，而替换成新的。这个是不对的。因为我只想改字段名，为什么要覆盖所有呢？

**Comment by zyyfit** [comment]
第一个问题是bug，第二个问题不是bug，因为改掉接口定义里那个name参数后，name参数在接口里就不存在了，勾选了删除与接口文档无法对应的参数，就会把case里有但是接口定义里没有的参数删掉，目前我们是不支持只修改字段名不修改字段值的，字段名修改后，无法判断哪个字段的值对应的修改的这个参数

**Comment by hao65103940** [comment]
好的 明白了

**Comment by zyyfit** [comment]
2.4.0版本已修复，请等待版本发布后验证
