### ISSUE TITLE
[BUG]在JSON-SCHEMA开启时编辑了高级设置字段，然后将JSON-SCHEMA关闭，高级字段属性丢失。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19733]
### 联系方式

王进

### MeterSphere 版本

v.2.2.1, v.1.20.16

### 使用外置数据库

否

### 问题描述

在JSON-SCHEMA开启时编辑了高级设置字段，然后将JSON-SCHEMA关闭，编辑了下请求头信息，保存后会将高级设置里面的信息全部置空

### 重现步骤

1. 新增一个接口
2. 在JSON-SCHEMA开启时新增字段属性，编辑高级设置字段，保存接口信息
3. 然后将JSON-SCHEMA关闭，再打开，会发现高级属性丢失了。 

### 附加信息

JSON-CHEMA关闭导致高级属性丢失，客户反馈无法接受。
站在用户的角度 关闭，再打开，客户原来的高级属性必须存在。
我们自己实测操作了几遍，大概理解了设计逻辑，不过客户不能接受我们的解释。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。

**Comment by hao65103940** [comment]
这个问题在V2.10.10-lts上又出现了，复现步骤同上
