### ISSUE TITLE
[BUG]MeterSphere测试计划下会把上一条用例关联的JIRA需求缓存带到后面用例中展示，前端页面没有及时更新数据

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19747]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.16-LTS

### 使用外置数据库

否

### 问题描述

MeterSphere测试计划下会把上一条用例关联的JIRA需求缓存带到后面用例中展示，前端页面没有及时更新数据

### 重现步骤

测试计划下，假如用例1关联需求1，用例2关联需求2，会出现这样的情况，必现步骤如下：
1、打开用例1查看，关联需求为1---ok
2、打开用例2查看，查看需求为1---错误，刷新整个页面，再进入查看，需求为2--正确；
3、再次查看用例1，查看需求为2---错误。

### 附加信息

视频：

https://user-images.githubusercontent.com/32027713/202065294-c6305f12-df05-4e0a-8eba-342a7ea189f3.mp4

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
