### ISSUE TITLE
[BUG]功能用例下的高级搜索功能，针对搜索条件创建人下拉框显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19748]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.16-LTS

### 使用外置数据库

否

### 问题描述

功能用例下的高级搜索功能，针对创建人及执行人下拉框显示错误：

切换到不同的项目下，该项目的项目成员也是不同的，但是高级搜索功能下创建人及执行人下拉框的人员列表都是相同的

### 重现步骤

1、功能用例下的高级搜索功能，筛选创建人及执行人

2、切换到不同的项目下，该项目的项目成员也是不同的，但是高级搜索功能下创建人及执行人下拉框的人员列表都是相同的

### 附加信息

项目A搜索:
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/32027713/202066856-7f47cb7f-ca4d-4355-920d-c80a9473f742.png">
项目A的项目成员：
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/32027713/202066922-1d440407-606c-448e-9385-99d4cda5ecc3.png">

项目B搜索:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32027713/202067046-2cbe6903-62c6-4767-b028-69bfb707cdba.png">
项目B的项目成员：
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32027713/202067164-598820dc-28f2-4d5e-878f-f746b488ade1.png">

**Comment by xulinde** [comment]
目前逻辑，创建人查的工作空间下的，后面可以改成项目下的

**Comment by xulinde** [comment]
1.20.18-lts已优化，建议您升级下版本
