### ISSUE TITLE
[BUG] 请求内容 post data json 没有格式化显示

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19744]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

2.2 版本 json 还可以格式化显示，方便查看
![image](https://user-images.githubusercontent.com/4860962/201894826-7961af13-6078-415a-b464-bc84f0aca43f.png)

2.3 不能格式化显示，不方便
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4860962/201895042-cce63ecb-3995-4c9a-9673-7a4575e6a90a.png">

### 重现步骤

如描述

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，2.4.1版本修复了这个问题，请等待版本发布后验证
