### ISSUE TITLE
[BUG]TCP接口，响应内容的请求地址未显示

### ISSUE THREAD

**Issue by Buken-Lin** [metersphere/metersphere#19741]
### 联系方式

debin.lin@kdlins.com.cn

### MeterSphere 版本

版本:   v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

TCP接口，响应内容的请求地址未显示

### 重现步骤

TCP接口，响应内容的请求地址未显示

### 附加信息

请求地址:

请求头:

Cookies :

Body:
ZSXN10103176    <?xml version="1.0"

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，在2.4.0版本中，我们和jmeter保持了一致，在响应信息中去掉了请求地址这块内容

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
