### ISSUE TITLE
[BUG] MS使用__CSVRead函数循环读取csv文件指定列的值，每次调试，未从第一行正序读取

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19754]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

MS使用__CSVRead函数循环读取csv文件指定列的值，每次调试，未重头正序读取

### 重现步骤

MS所在服务器有dd.csv文件
![image](https://user-images.githubusercontent.com/103925124/202074181-ec9ba6a3-eee9-4539-bb25-cb7511b22a9f.png)
设置循环控制器为次数循环5次
前置脚本引用服务后打印
![image](https://user-images.githubusercontent.com/103925124/202073951-3613522b-219b-46f0-8c24-03aceec361c8.png)
每次点击调试，打印均不变，且未正序读取
![image](https://user-images.githubusercontent.com/103925124/202074255-67fb8f22-3d3e-4d13-9596-a789ddc1dc13.png)
jmeter设置循环次数为5
![image](https://user-images.githubusercontent.com/103925124/202074367-3a7cf82e-82ed-4f48-bca6-de88e9f9eefa.png)
第五次，获取当前行的第一列为admin1
![image](https://user-images.githubusercontent.com/103925124/202074434-7084be90-b42a-463b-ab26-070e2e277f93.png)

**Comment by zyyfit** [comment]
感谢反馈，不过我看jmeter里使用循环执行，目前和我们的系统里表现是一样的，我们暂时对这个问题不做修改
