### ISSUE TITLE
[BUG]测试计划>>关联测试用例>>在弹出的关联测试用例页面，其左侧模块显示不全，并且左侧显示框也无法向右拖拽调整窗口大小。请调整和测试用例列表显示一样，能拖拽调整窗体显示宽度。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#19757]
### MeterSphere 版本

V2.3.1

### 使用外置数据库

否

### 问题描述

[BUG]测试计划>>关联测试用例>>在弹出的关联测试用例页面，其左侧模块显示不全，并且左侧显示框也无法向右拖拽调整窗口大小。请调整和测试用例列表显示一样，能拖拽调整窗体显示宽度。

### 重现步骤

[BUG]测试计划>>关联测试用例>>在弹出的关联测试用例页面，其左侧模块显示不全，并且左侧显示框也无法向右拖拽调整窗口大小。请调整和测试用例列表显示一样，能拖拽调整窗体显示宽度。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/202076438-b8b15d90-fb0a-4019-97bd-c1f78efc2ccb.png)

**Comment by huangxine** [comment]
测试评审中关联测试用例类似，也无法通过拖拽调整左侧模块显示的宽度

**Comment by xulinde** [comment]
v2.4.0已做优化～
