### ISSUE TITLE
[BUG] 功能用列，导入思维导图，存在特殊字符例 -->  ，导入后显示异常为：--&gt;

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#19752]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

版本:   v1.20.16-lts-3bb3478d

### 使用外置数据库

是

### 问题描述

功能用列，导入思维导图，存在特殊字符例 -->  ，导入后显示为：--&gt;

### 重现步骤

思维导图-->导入的用例
![image](https://user-images.githubusercontent.com/23476281/202073044-14842b8f-a9af-496c-b53e-c86eae709370.png)

导入后，思维导图查看用例：
![image](https://user-images.githubusercontent.com/23476281/202073184-6018953a-25db-411d-b37d-717d9a543c8e.png)

**Comment by xulinde** [comment]
未复现该问题，您xmind版本是多少
<img width="661" alt="image" src="https://user-images.githubusercontent.com/64065190/202119865-bfd51a4d-ad6d-42eb-b3b0-78e6694728b9.png">

**Comment by chase001** [comment]
版本: XMind 8 Update 9 (R3.7.9.201912052356)

**Comment by xulinde** [comment]
方便导出给我复现下吗？

**Comment by xulinde** [comment]
重复
https://github.com/metersphere/metersphere/issues/20468
