### ISSUE TITLE
[BUG]V2.2.1   执行接口自动化，点击调试出现死锁（出现频次高）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19759]
### MeterSphere 版本

2.2.1

### 使用外置数据库

否

### 问题描述

接口自动化调试报错，提示死锁

### 重现步骤

接口自动化调试报错，提示死锁。暂无法稳定复现重启环境后好一段时间 过几天又出现了‘
![Uploading ca678b38c434ec0c1a3a325da2696fe.png…]()

### 附加信息

[error.log](https://github.com/metersphere/metersphere/files/10017924/error.log)
[info(3).log](https://github.com/metersphere/metersphere/files/10017925/info.3.log)

**Comment by xhy12** [comment]
![ca678b38c434ec0c1a3a325da2696fe](https://user-images.githubusercontent.com/43202800/202078090-1b31010e-0def-40b6-8f1d-9799d4a86da4.png)

**Comment by zhangzhaox** [comment]
@xhy12 可以从数据库层面把mysql死锁锁链日志找出来，也可以协助解决死锁问题

**Comment by xhy12** [comment]
[mysql 死锁查询内容.txt](https://github.com/metersphere/metersphere/files/10064909/mysql.txt)
![4b7e95f86f16987f38dc99b49eccf8c](https://user-images.githubusercontent.com/43202800/203251781-bff5fca4-1d8f-491a-bae1-a701baa51a5c.png)
 死锁出现查询结果见附件

**Comment by xhy12** [comment]
死锁开启binlog日志如下
[mysqlbin.txt](https://github.com/metersphere/metersphere/files/10111742/mysqlbin.txt)

**Comment by youliyuan-fit2cloud** [comment]
一直未能复现出来，只能猜测可能发生的地方进行了事务拆分，升级后请反馈是否还会复现，感谢～
