### ISSUE TITLE
[BUG]消息通知存量太多，导致查询消息接口pending中，页面转圈圈用不了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19755]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

消息通知存量太多，导致查询消息接口pending中，页面转圈圈用不了

### 重现步骤

1.客户定时任务数量有20个，最快的频率是4分钟一次。大部分是半小时一次。跑了一个月了，现在进入任何页面都很慢
2.查看浏览器控制台，发现查询消息通知的接口一直阻塞中
<img width="352" alt="4065ffaa663e323b745a5a4e6f80394" src="https://user-images.githubusercontent.com/88763608/202074596-f0925756-4e86-4835-9c9f-4ba4f399a873.png">
![image](https://user-images.githubusercontent.com/88763608/202076259-14ea193e-e108-4073-8264-fc95fb304b11.png)

3.查看数据库notification表，存量有20多万条
<img width="263" alt="6c7b0c1fa435afd0ac1e5af12c2122e" src="https://user-images.githubusercontent.com/88763608/202074690-cbd8f75e-9063-41ec-ab9c-5df20baf7f40.png">
4.清空notification表后，暂时恢复不卡了
5.需要优化下查询的语句和逻辑

### 期待的正确结果

需要优化下查询的语句和逻辑

**Comment by youliyuan-fit2cloud** [comment]
你好，请先使用如下sql优化一下看看是否还会出现该问题，
CREATE INDEX notification_create_time_index ON notification (create_time);
