### ISSUE TITLE
[BUG]  MS使用__CSVRead函数读取csv文件指定列的值，作为参数传递，获取值为空

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19753]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

 MS使用__CSVRead函数读取csv文件指定列的值，作为参数传递，获取值为空

### 重现步骤

MSsuoza所在服务器有dd.csv文件
![image](https://user-images.githubusercontent.com/103925124/202071939-f5afe8d5-6ebe-46b3-ab7b-27880b5a01e7.png)
![image](https://user-images.githubusercontent.com/103925124/202073195-d3847ce9-a050-4135-aec2-4da32d7f147f.png)
前置脚本中引用
![image](https://user-images.githubusercontent.com/103925124/202071994-7ab22c6c-a3f9-4040-b5c0-1786c04f60dc.png)
读取打印正常
![image](https://user-images.githubusercontent.com/103925124/202072995-b1f60cf3-7c05-4c0e-911b-8b33d97f6d97.png)
在参数中引用，值为空
![image](https://user-images.githubusercontent.com/103925124/202073050-56771001-7589-4201-92db-67f136293563.png)
且控制台报错
2022-11-16 11:00:33 WARN 037b2111 1-1 037b2111 1-1 - can't parse column number:  1 java.lang.NumberFormatException: For input string: " 1"

**Comment by zyyfit** [comment]
已确认是函数中多了一个空格导致的
