### ISSUE TITLE
[BUG] MS使用StringToFile函数将字符串写入文件，执行一次，写入了两次

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19762]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.1.1-96b84b46

### 使用外置数据库

否

### 问题描述

MS使用StringToFile函数将字符串写入文件，执行一次，写入了两次

### 重现步骤

接口前置脚本增加字符串写入文件函数
![image](https://user-images.githubusercontent.com/103925124/202088393-b3300efa-5eb1-4fb8-af62-20d03c8eb185.png)
**String  kong = "${__StringToFile(/opt/metersphere/data/json/aa.txt,\n${uname},,)}";
log.info("打印（写入文件）",kong);**

文件被写入两次uname的值
![image](https://user-images.githubusercontent.com/103925124/202088446-ca0cdaac-27dc-424c-b7bd-576fb616bfb1.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
经验证，在jmeter里的请求中添加脚本就会执行两次，单独一个脚本就是执行一次
