### ISSUE TITLE
[QUESTION]左侧菜单的[工作台]怎么不见了

### ISSUE THREAD

**Issue by chenshangwei** [metersphere/metersphere#19760]
### 请描述您的问题

metersphere-offline-installer-v2.3.0
metersphere-offline-installer-v2.3.1
这两个版本，都是如此
取消了这个页面吗？没用过其他版本 

![117](https://user-images.githubusercontent.com/5057104/202079104-7671c843-b0df-4d71-9aee-396604db0562.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，企业版本升级到2.3以上需要修改配置文件/opt/metersphere 目录下的.env文件中相关配置，参考下图所示，重启服务后生效。
<img width="689" alt="image" src="https://user-images.githubusercontent.com/54612864/202333233-6ba752a9-1b0f-4230-a9d1-a2fdcaac5e1b.png">
