### ISSUE TITLE
[BUG] 接口自动化场景，引用单接口用例保存后 再次查看断言丢失

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#19764]
### MeterSphere 版本

2.3

### 使用外置数据库

否

### 问题描述

接口自动化场景，引用单接口用例保存后 再次查看断言丢失

### 重现步骤

1、接口自动化场景，引用单接口用例保存
问题:再次打开这条数据，查看 断言丢失。有录屏
![image](https://user-images.githubusercontent.com/43202800/202097858-73321c25-4df7-4cfc-b5df-d806db61bc42.png)

### 期待的正确结果

断言规则保留

### 附加信息

https://user-images.githubusercontent.com/43202800/202097910-81954b27-97e8-4b4d-b143-22ddf0138427.mp4

**Comment by youliyuan-fit2cloud** [comment]
已知问题，请下个版本发布后升级一下。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0中已修复。
