### ISSUE TITLE
[FEATURE]建议jenkins控制台日志中的MeterSphere报告连接改为免登录的分享链接。

### ISSUE THREAD

**Issue by Thisisasnail** [metersphere/metersphere#19778]
### MeterSphere 版本

v1.20.16-lts-3bb3478d

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/63831219/202123036-28685ada-c6bc-43b6-a34b-162bba7a38f6.png)
在DevOps体系中，jenkins控制台执行的日志中生成的MeterSphere报告连接需要登录才能查看，很不方便。如果是报告的分享链接就好了，可以直接获取jenkins控制台日志中的链接通过邮件发给本次测试的相关开发和产品。

### 请描述你建议的实现方案

jenkins控制台日志中的MeterSphere报告连接建议改为免登录的报告分享链接。

### 附加信息

https://user-images.githubusercontent.com/63831219/202124203-4e6430b2-e807-4c79-aa51-17fbee65a863.mp4

**Comment by luty2018** [comment]
感谢建议， 这个可以加。在两个版本内。

**Comment by Thisisasnail** [comment]
好的，多谢

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
