### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hinagaryou** [metersphere/metersphere#19770]
### MeterSphere 版本

v1.20.15-lts-6dc0c1ce

### 请描述您的需求或者改进建议

这个能定期清吗？发现这个消息占用的内存也比较大，一段时间不去数据库清就满了要。

### 请描述你建议的实现方案

建议可以在启用设置里面加一下通知清理的功能。
![1668582683964](https://user-images.githubusercontent.com/50445174/202110669-17db393d-316b-410d-b36b-08d6f1fdf559.jpg)

### 附加信息

![22322bdbe8598f2804637d22a2a74cb](https://user-images.githubusercontent.com/50445174/202110965-eba63261-466f-4776-9e2c-07b118cfab57.jpg)

**Comment by luty2018** [comment]
感谢建议， 这个可以加， 2个版本内。
