### ISSUE TITLE
[BUG]测试计划，UI自动化测试失败重跑，目前是“在同一个打开的浏览器session下面重新跑一遍场景”，从实际效果看有缺陷

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19779]
### 联系方式

王进

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

测试计划，UI自动化测试失败重跑，目前是“在同一个打开的浏览器session下面重新跑一遍场景”，从实际效果看有缺陷

### 重现步骤

客户这边的场景：
1. 一个测试计划，关联了157个UI自动化场景，每天定时跑
2. 现在每天都有五六个失败的，从控制台日志看，失败的场景有重跑。
3. 这些失败的场景，如果手动去执行一次，都是PASS的。
5. 跟开发沟通了失败重试机制，目前是“在同一个打开的浏览器session下面重新跑一遍场景”，目前看很有可能是这个设计，导致重跑时浮层对象找不到，失败的步骤比第一次更早。
6. 跟开发沟通，一致认为，做成 failed session关闭，然后 新建一个session，这样更科学。

### 附加信息

按照客户的要求，还有内部沟通，提了这个bug

**Comment by zrfit** [comment]
v2.4.0已修复。
