### ISSUE TITLE
[BUG]在 MS 平台新增缺陷，点击同步缺陷到 Azure Devops 平台，在 MS 平台上该缺陷不再显示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#19777]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

在 MS 平台新增缺陷，点击同步缺陷到 Azure Devops 平台，在 MS 平台上该缺陷不再显示，但是在 Azure Devops 平台上已经同步过来。在同步缺陷时，该缺陷应该挂到过滤 ID 所在的缺陷上。

### 重现步骤

1. 服务集成 Azure Devops 平台，在项目处也设置了过滤 ID
![AZure的过滤ID](https://user-images.githubusercontent.com/104960608/202116552-0d02a933-18b5-41a3-a4ff-6ed2be397fd4.png)

![262d0b0f3bb1e38e768a06884428932](https://user-images.githubusercontent.com/104960608/202138920-c04cc65a-172c-47a3-a8f6-021fd4aff29f.png)

2. 在 MS 平台上新增缺陷
![1668584338154](https://user-images.githubusercontent.com/104960608/202117182-66ceef14-d78b-4207-9483-8c2a142e24b6.jpg)

3.点击同步缺陷后， MS 平台上该缺陷不再出现
![image](https://user-images.githubusercontent.com/104960608/202117479-369bfc7a-d454-4f59-ab4d-82795042f9d2.png)

4. 在 Azure Devops 平台上能看到该缺陷已被同步过来
![image](https://user-images.githubusercontent.com/104960608/202117710-ff9bc8a0-571b-4a6b-9a2d-c31af0aa7c73.png)

### 期待的正确结果

希望点击同步缺陷后该缺陷都能在 MS 平台展示。该缺陷能挂到该过滤 id 下

**Comment by xulinde** [comment]
v2.4.0已修复～
