### ISSUE TITLE
[BUG]接口自动化点击运行，“全部”的内容不显示

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#19780]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

1、接口自动化列表点击运行，出现“全部”的内容不显示的情况；
2、测试报告列表中打开，是有报告内容的。

### 重现步骤

1、接口自动化列表选择某个场景，点击运行
2、查看报告内容，发现“全部”内容不显示

### 附加信息

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/32027713/202127361-e9a2fff3-5b69-458e-9f67-b1bd4c528bd2.png">

**Comment by zyyfit** [comment]
已知问题，2.3.1中已修复，请升级后使用

**Comment by hao65103940** [comment]
V2.3.1 验证，并未修复，复现步骤：
1. 只关闭一键同步case按钮，高级选项不动。
2. 然后修改接口定义的请求体参数，case里面会覆盖同步的。
<img width="715" alt="image" src="https://user-images.githubusercontent.com/33945037/202346060-c927dd64-4efa-47f8-b1d2-19d59e4cf205.png">
<img width="880" alt="image" src="https://user-images.githubusercontent.com/33945037/202346263-3439ad05-59c8-4089-86af-beff6f5fa412.png">
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/33945037/202346306-ac3b890d-3b5b-45a0-86b5-62be65b56c78.png">
