### ISSUE TITLE
[BUG]场景编辑不符合预期

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1979]
**MeterSphere 版本**
1.8.2

**Bug 描述**
未正确引用

**Bug 重现步骤**
1.  在接口自动化中新加一个自定义请求；
2. 将该请求另存为接口定义； 此时接口API和接口CASE都有了这个接口；
3. 删除场景中的自定义请求；
4. 给另存为的请求增加前置脚本和断言
3. 给场景引用接口CASE中刚另存为的请求；
4. BUG1 : 场景中的该步骤还是显示为自定义请求；没有变为引用；
5. BUG2: 场景中的该步骤不可编辑并且没有显示在接口CASE中添加的前置脚本和后置脚本

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
@fit2cloudrd 
查数据看的时候发现 在另存为这一步把对应自定义请求的
  "referenced": "Created",
  "index": "5",
存到的 api_test_case 表中导致显示异常

**Comment by zyyfit** [comment]
感谢反馈，不好意思之前没注意到这个issue，将在后续版本中修复这个问题

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
