### ISSUE TITLE
[FEATURE]项目可以配置常用变量表，在填写字段的时候方便填写

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19798]
### MeterSphere 版本

v2.3.0-f7d4cc4e

### 请描述您的需求或者改进建议

1. 公司有上千个接口要编写用例
2. 每个接口用例都要填写某些常用的变量，如 ${token}，其他还有和 ${token} 常用程度差不多
3. 每次都要手动输入 ${token}，非常麻烦

### 请描述你建议的实现方案

1.能否在项目配置里面加一个常用变量配置项目
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/4860962/202339205-c380afe6-df33-4168-8b35-f7db07646083.png">

2.在接口编写填入变量的时候就可以选择了
<img width="603" alt="image" src="https://user-images.githubusercontent.com/4860962/202339353-081e5944-7b8f-42b0-8651-389fd3230c8f.png">

**Comment by luty2018** [comment]
需要进一步调研这个功能的实用性。

**Comment by hao1032** [comment]
如果 https://github.com/metersphere/metersphere/issues/19800 可以实现，当前这个可能就没有必要了。
