### ISSUE TITLE
[FEATURE] 场景用例中，脚本没有 debug 按钮

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19793]
### MeterSphere 版本

v2.3.0-f7d4cc4e

### 请描述您的需求或者改进建议

用例调试中，脚本也需要调试，但是又不希望执行整个过程，希望脚本也增加执行按钮
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/4860962/202170713-2fb7fc97-5269-4c6d-9569-f24f2928efc3.png">

**Comment by luty2018** [comment]
这个目前还无法支持。
