### ISSUE TITLE
[BUG] 缺陷的操作日志没有展示自定义字段的变更记录

### ISSUE THREAD

**Issue by bingosam** [metersphere/metersphere#19799]
### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

更新缺陷的操作日志没有展示自定义字段的变更记录

### 重现步骤

为缺陷模板配置了若干个自定义字段，新增缺陷后对自定义字段进行编辑，查看操作日志详情，只体现了操作成功，没有自定义字段的新旧值

### 期待的正确结果

操作日志详情可以看到自定义字段的变更记录

**Comment by luty2018** [comment]
这个会在后续版本中支持。
