### ISSUE TITLE
[BUG] jsonpath length 没有正常获取

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19803]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

1.在 https://jsonpath.com/ 站点上可以看到 jsonpath 支持 length
![image](https://user-images.githubusercontent.com/4860962/202346806-ae66f000-1fac-4782-a9d5-b5e834142bfb.png)

2.在之前的 bug 中看到 ms 之前貌似也支持 lenght（不太确定）
https://github.com/metersphere/metersphere/issues/5188

3.当前 ms 使用 jsonpath length 有问题
<img width="923" alt="image" src="https://user-images.githubusercontent.com/4860962/202346992-dff2c94a-4c89-4087-a1f1-53461011f49c.png">

### 重现步骤

在 jsonpath 中对数组使用 length

**Comment by zyyfit** [comment]
您好，jmeter也是不支持这样使用的，我们和jmeter保持一致

**Comment by hao1032** [comment]
ok,了解了。
