### ISSUE TITLE
[FEATURE]循环控制器显示的状态 希望以最后一次循环的结果为准

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#19809]
### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

设置循环控制器多次循环后，前面失败后面成功，显示的控制器状态为失败

### 重现步骤

设置循环控制器多次循环，查看循环控制器显示结果

### 期待的正确结果

如果多次循环中，最后是正确的，那么整体循环控制器状态应该显示正确

**Comment by A616984934** [comment]
是的，按照逻辑来说如果循环次数里面最终结果是成功的，那么这个步骤应该是成功的才对

**Comment by zyyfit** [comment]
> 是的，按照逻辑来说如果循环次数里面最终结果是成功的，那么这个步骤应该是成功的才对

感谢您的反馈，但是我们目前的逻辑是，假如循环5次，第一次失败了，后面4次是成功的，这个循环控制器的结果就是失败的

**Comment by A616984934** [comment]
比如这种场景，轮询查看接口的结果，需要等待结果，不能因为前几次接口没返回正确结果，就认为整个接口场景出现错误，这个逻辑明显是不合理的

**Comment by A616984934** [comment]
![image](https://user-images.githubusercontent.com/44996472/203771405-2169585d-4101-4089-b9fe-0c6105d6c575.png)
同时会造成jenkins执行报错

**Comment by luty2018** [comment]
这种情况下可能是要以最后一次循环结果为准，但是分支情况太多， 我们需要进一步调研。

**Comment by mengshuai85** [comment]
是的，也碰到这种场景了，比如等待的场景（不想一次等待1分钟，可以分成6次循环，每次10s，后面成功了，就说明ok了）

可以加上一个 开关（循环：是否以最后1次执行为准）

**Comment by assilzm** [comment]
> 这种情况下可能是要以最后一次循环结果为准，但是分支情况太多， 我们需要进一步调研。

我们这边也遇到这样的问题。如果暂时没有这样的计划，能告知下如何修改吗？我们自己处理下逻辑。
