### ISSUE TITLE
[BUG]接口自动化点击“执行”按钮，页面弹出报告为空，实际上是有报告的

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19807]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

接口自动化点击“执行”按钮，页面弹出报告为空，实际上是有报告的

### 重现步骤

1.创建场景，场景中请求百度
![image](https://user-images.githubusercontent.com/88763608/202351388-9e1a5f07-c29a-4bc7-872f-e4b4c636eb1b.png)
2.在场景列表中，点“执行”
![image](https://user-images.githubusercontent.com/88763608/202351472-013ad994-7590-4efd-b2d6-bcc2ee8eb715.png)
3.页面弹出的报告啥也没有
![image](https://user-images.githubusercontent.com/88763608/202351537-7e2a6248-3fc5-41b4-a9c9-d7ef0aa39377.png)
4.从测试报告页面进去查看，是正常执行有内容的报告
![image](https://user-images.githubusercontent.com/88763608/202351658-7a3e7fbc-f031-442b-9d7f-f2131c6d8e83.png)
![image](https://user-images.githubusercontent.com/88763608/202351721-92a96154-b1df-4d25-b3dc-05bbea01b018.png)

### 期待的正确结果

展示正常

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #19780
