### ISSUE TITLE
[BUG]接口场景自动化在升级到2.3.1后不能复制步骤

### ISSUE THREAD

**Issue by spheretangmeng** [metersphere/metersphere#19806]
### 联系方式

tangmeng@sphere-ex.com

### MeterSphere 版本

2.3.1

### 使用外置数据库

否

### 问题描述

这个复制没有用，点击复制就展示步骤，再点就是关闭，根本没有复制

### 重现步骤

![image](https://user-images.githubusercontent.com/113685220/202349830-ccd1d974-b45a-4dc1-a274-135201636ffe.png)

**Comment by youliyuan-fit2cloud** [comment]
![Uploading image.png…]()
