### ISSUE TITLE
[BUG]等待控制器没有按照顺序执行

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#19808]
### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

接口自动化部分加上等待控制器后，没有按顺序执行，直接先执行的等待控制器，即使排在步骤二

### 重现步骤

接口自动化加上等待控制器，将等待步骤排在后面，执行自动化

### 附加信息

<img width="967" alt="image" src="https://user-images.githubusercontent.com/44996472/202364413-d584078e-ac8e-435d-8df2-71c9f6f4bf34.png">

**Comment by zyyfit** [comment]
您好，感谢您的反馈，目前我们的系统中，跟请求平级的等待控制器是所有请求都会生效的，会在所有同级请求步骤前进行等待；步骤内的等待控制器才是当前步骤生效的

**Comment by A616984934** [comment]
等待控制器 无法拖入接口请求内，那么如果要使用等待控制器 是否需要建立事物步骤才可以？

**Comment by zyyfit** [comment]
> 等待控制器 无法拖入接口请求内，那么如果要使用等待控制器 是否需要建立事物步骤才可以？

接口请求内不需要拖入，可以在前置步骤中添加等待控制器，有这个选项的，后置步骤不能添加
