### ISSUE TITLE
[BUG]接口测试中Jsonschema按钮关闭打开的操作，会导致原有参数 是否必须复选框状态被取消，见截图

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19817]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.16

### 使用外置数据库

否

### 问题描述

接口测试中Jsonschema按钮关闭打开的操作，会导致原有参数 是否必须复选框状态被取消，见截图
复选框状态都是选中的，保存。
<img width="652" alt="1668671925139" src="https://user-images.githubusercontent.com/83771182/202388838-d7703de6-1acb-4404-a90e-4e5897de5f9c.png">
关闭Jsonschema按钮后，再次打开，此时复选框状态都变为未选中。
![image](https://user-images.githubusercontent.com/83771182/202389523-f9512576-d9b1-4a1d-97e0-d20f3af8e8e7.png)

### 重现步骤

关闭打开操作Jsonschema按钮后，原有参数 是否必须复选框状态变成未选中。

### 期待的正确结果

关闭打开操作Jsonschema按钮后，原有参数 是否必须复选框状态不应发生变化。

**Comment by zyyfit** [comment]
您好，感谢您的反馈，这里是这样的，json-schema格式的作用是把当前json字符串格式化展示，json字符串里是没有是否必填的这个选项的，所以关闭后再开启，也不会保留之前的是否必填选项，就都会变成默认的未选中状态
