### ISSUE TITLE
[BUG]接口自动化调试时，里层的场景没执行完，外层就显示success，状态提示不正确，状态应该显示测试中。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19825]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.16

### 使用外置数据库

否

### 问题描述

接口自动化调试时，里层的场景没执行完，外层就显示success，状态提示不正确，状态应该显示测试中。操作时是在场景里面引用场景，并在脚本中加个等待时间。
![b2a2cebe5c8b62c6ff3d4a1fa09d29e](https://user-images.githubusercontent.com/83771182/202418551-b74e3bbf-b27c-4ba7-b3c1-009fc5676793.png)

### 重现步骤

操作时是在场景里面引用场景，并在脚本中加个等待时间。

### 期待的正确结果

接口自动化调试时，里层的场景没执行完，外层状态应该显示测试中。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，跟开发人员确认了我们目前的逻辑是这样的：
场景下 10 个请求 ，请求1 开始执行场景显示测试中，请求1执行完成场景显示请求1 的结果，这时如果后续请求都出问题，场景最终定格上次执行的结果，如果间隔时间短请求2开始执行则显示测试中，请求2执行完成后综合计算一次结果，以此类推。
