### ISSUE TITLE
关于不能支持python3的烦恼

### ISSUE THREAD

**Issue by yiguwei** [metersphere/metersphere#19820]
### MeterSphere 版本

v1.20

### 请描述您的需求或者改进建议

能否帮忙尽快实现支持python3语法。python2都停止维护了

### 请描述你建议的实现方案

1.jmeter基础镜像增加python3环境
2.node-controller启动容器时或者jmeter dockerfile 新增pip install 安装包命令，信息由ms-server服务提供。
3.用例页面要是选择python脚本，新增输入框，填入当前脚本需要安装的包名称和版本信息。存入db。运行用例时beanshell脚本采用java命令行的形式调用python的环境来运行python3语法的脚本来获取脚本结果。

**Comment by Jarvan40** [comment]
期望+1.
我项目组内的部分代码也是用python3写的，python2可以考虑向下兼容，但使用python3的会越来越多。

**Comment by luty2018** [comment]
我把这个issue置顶了， 先收集下有多少人对Python3有强需求吧。

**Comment by zhangzhaox** [comment]
虽然我不用py3，但同事偶尔会提起这个需求，有py3基本上可以顺利承接下py的用户群里

**Comment by NepPure** [comment]
需py3

**Comment by legend818** [comment]
前排顶一下

**Comment by wan92hen** [comment]
> ### MeterSphere 版本
> v1.20
> 
> ### 请描述您的需求或者改进建议
> 能否帮忙尽快实现支持python3语法。python2都停止维护了
> 
> ### 请描述你建议的实现方案
> 1.jmeter基础镜像增加python3环境 2.node-controller启动容器时或者jmeter dockerfile 新增pip install 安装包命令，信息由ms-server服务提供。 3.用例页面要是选择python脚本，新增输入框，填入当前脚本需要安装的包名称和版本信息。存入db。运行用例时beanshell脚本采用java命令行的形式调用python的环境来运行python3语法的脚本来获取脚本结果。
> 
> ### 附加信息
> _No response_

你好，我们使用了 JMeter 中的 JSR223 + Jython 来执行 python 脚本，Jython 项目目前仅支持到 python2 版本，python3 版本的 Jython 具体发布时间还不确定（https://www.jython.org/jython-3-mvp.html）。

你在 Issue 中提到的这种方案，可以解决 Python3 脚本的执行问题，但是不能很好的跟 JMeter 上下文进行交互。比如将用户定义、提取的各种变量，传递到 Python 脚本中，或者将 Python 脚本执行过程中产生的一些数据，再作为变量传递给 JMeter 以便后续步骤使用。

**Comment by Bu1eCat** [comment]
需python3

**Comment by hao1032** [comment]
有需要，py2 遇到中文就跪了，我现在每个脚本都要加一个 import

**Comment by TSleon** [comment]
需python3

**Comment by xianwq** [comment]
现在不光是不支持python3的问题，就算python2的话，第三方库通过sys.path.append引入也是不能用的；亲测，不知道大家可以不

**Comment by wan92hen** [comment]
> 现在不光是不支持python3的问题，就算python2的话，第三方库通过sys.path.append引入也是不能用的；亲测，不知道大家可以不

这个要具体看是什么库。还是由于使用了 Jython，有些依赖 C 语言的库确实不支持。
https://github.com/jython/jython/issues/53

**Comment by xieqione** [comment]
需要用py3哦

**Comment by goodboyxzmkk** [comment]
需要用py3

**Comment by Kaka000001** [comment]
希望支持py3，能解决很多问题

**Comment by gaye746560359** [comment]
需python3

**Comment by ZaynMalik1** [comment]
希望支持py3

**Comment by tqq1994516** [comment]
是不是可以基于k8s job去调度python3容器 执行脚本，传入参数脚本和依赖，运行完获取输出

**Comment by chenrenyiabc** [comment]
希望支持python3，很多库python2无法支持 😭

**Comment by zhouxiongjie1997** [comment]
希望支持

**Comment by ke-liang** [comment]
这必须要 python3

**Comment by conansharp** [comment]
需python3

**Comment by TesterPei** [comment]
需要支持python3 并支持上传第三方包，可在代码中引用。
python2已经没有人维护了

**Comment by hanchenglong001** [comment]
强烈需要。我目前自己实现了个接口 把python脚本通过请求体传过去。然后执行完在传回来。

**Comment by yangstones** [comment]
+1

**Comment by sodawaterzh** [comment]
强烈需要py3

**Comment by Icesuspect** [comment]
极度需要

**Comment by zhenhuaplan** [comment]
希望支持脚本支持Python3.8以上

**Comment by sunume** [comment]
希望支持py3

**Comment by zhouweisong** [comment]
希望早日支持python3

**Comment by triangle959** [comment]
希望支持python3

**Comment by YellCatt** [comment]
我觉得也需要支持python3和第三方库，ms的使用下限低，但是上限不够高啊，很多用python写成的测试用例是没法办法通过ms运行和管理的，无疑增加了管理成本

**Comment by tqq1994516** [comment]
> 是不是可以基于k8s job去调度python3容器 执行脚本，传入参数脚本和依赖，运行完获取输出

我目前是基于apache pulsar functions来管理python3脚本，然后基于接口测试插件开发了相关插件，可以下拉选择 function ,form输入json参数然后运行，将返回值再json化返回，服务和相关插件后续追更

**Comment by triangle959** [comment]
已收到

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/25398

**Comment by quarrierZhang** [comment]
不是py3 太多问题

**Comment by davidcchen** [comment]
需py3

**Comment by Mr1X** [comment]
插眼，支持python3

**Comment by XiamenHongjingsheng** [comment]
强烈要求新增python3。毕竟ms平台是给测试圈的所有测试人员使用的，测试圈里的尤其新人，基本都是用python。

**Comment by Stephen0910** [comment]
才七年而已，再等七年，说不定直接上python4

**Comment by luty2018** [comment]
v3.0已经支持Python3了，大家可以在这个环境体验：https://demo.metersphere.com/

**Comment by luty2018** [comment]
Python3 引入三方包的方式：https://github.com/metersphere/metersphere/issues/31811
