### ISSUE TITLE
[BUG]ms和jira集成后，在ms里面提交bug时 ，在“描述”字段添加内容后，点击保存，提示描述为空，报400

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#19833]
### 联系方式

张树彬

### MeterSphere 版本

v1.20.12-lts

### 使用外置数据库

否

### 问题描述

ms和jira集成后，在ms里面提交bug时 ，在“描述”字段添加内容后，点击保存，提示描述为空，报400

### 重现步骤

1. ms与jira集成成功
2. 在ms缺陷管理创建缺陷，在描述字段中编辑内容
3. 点击保存按钮，提示描述为空，报400

### 期待的正确结果

可以正常编辑及保存”描述“字段内容

### 附加信息

![927ef26394939795dd9006457256710](https://user-images.githubusercontent.com/77324661/202440966-7070ff37-c8c6-4d90-97e7-047106f221fe.png)

**Comment by xulinde** [comment]
400一般是自定义字段类型或值和jira字段对应不上导致，和描述应该没关系，可以先把自定义字段逐个删除排查下～

**Comment by binbin0406** [comment]
没用自定义字段，是用的jira模板

**Comment by xulinde** [comment]
我在v1.20.16-lts试了下可以正常提交，建议升级下版本
