### ISSUE TITLE
[BUG]接口自动化模块导入jmx脚本中带Module Controller引用模块，导入提示成功但是解析不了，执行时引用模块功能不起作用。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#19830]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.16

### 使用外置数据库

否

### 问题描述

接口自动化模块导入jmx脚本中带module controller引用模块，导入提示成功但是解析不了module controller，执行时module controller引用模块功能不起作用。
![050a0abd2fe198721e3c4b092f9a80e](https://user-images.githubusercontent.com/83771182/202428254-2cbae105-85be-48e5-bc6c-6e6aa7728260.png)

### 重现步骤

接口自动化模块导入jmx脚本中带module controller引用模块

### 期待的正确结果

接口自动化模块导入jmx脚本中带module controller引用模块，能正确解析，执行时module controller引用模块功能正常。

**Comment by zyyfit** [comment]
感谢您的反馈，目前我们不支持 module controller
