### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by kubecto** [metersphere/metersphere#19834]
### 请描述您的问题

nginx 我做转发现在访问不到

**Comment by kubecto** [comment]
location /metersphere {
            rewrite ^/metersphere?$ /metersphere/login#/ redirect;
           # rewrite ^/metersphere(.*)$ $1 break;
            proxy_pass http://10.102.99.6:8081;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

**Comment by fit2-zhao** [comment]
https://metersphere.io/docs/v2.x/quick_start/quick_start/?h=nginx#153-jsonpath

可以参照这个配置，如果还有问题，把日志贴出来看看。
