### ISSUE TITLE
[BUG]最新版本引用列表使用${变量名_ALL}方法失效了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#19843]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

最新版本引用列表使用${变量名_ALL}方法失效了

### 重现步骤

1.原来的效果
<img width="354" alt="4fdfdaa2d4a29c0189ab8bd15a73d30" src="https://user-images.githubusercontent.com/88763608/202612131-70ce1e16-b9cb-465e-9fb4-0a781bb98431.png">
2.现在的效果
![image](https://user-images.githubusercontent.com/88763608/202612308-148c3961-e95c-48cb-b7c4-1f437e46ae2d.png)

### 期待的正确结果

_ALL方法要生效

**Comment by linfengjjj** [comment]
我是在2.3.1正式发布版本出现的，我刚刚用内部的QA环境也复现了，在这个项目下
![image](https://user-images.githubusercontent.com/88763608/203213403-4b7bbc05-41f0-4d38-a2ce-a743939aa247.png)

**Comment by zyyfit** [comment]
sql的按列存储变量，在jmeter里也是这种结果
![image](https://user-images.githubusercontent.com/73461316/203352929-945cbeca-3ac7-471b-bbb5-33bb894ea0a3.png)
