### ISSUE TITLE
[BUG]ms系统对接ldap。账户密码验证成功，填写用户过滤器和ldap属性映射后。ldap账户登录不成功。

### ISSUE THREAD

**Issue by 15034309829** [metersphere/metersphere#19850]
### 联系方式

15034309829@163.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

ms系统对接ldap。账户密码验证成功，填写用户过滤器和ldap属性映射后。ldap账户登录不成功。
![image](https://user-images.githubusercontent.com/71599987/202647147-ada746d2-962e-4db1-bf3c-e4bb9de73a37.png)

### 重现步骤

ms-系统设置-系统-系统参数设置-ldap设置，填写基本信息。
用户过滤器：(cn={0})
ldap属性映射：｛"username": "cn","name": "cn","email": "mail"}

ladp：
![image](https://user-images.githubusercontent.com/71599987/202648112-8f9b19ef-7d46-4341-b5c6-d96af87499e2.png)

### 附加信息

![image](https://user-images.githubusercontent.com/71599987/202647182-ed53b4c9-fdd4-44ce-9643-9c660b430f39.png)

**Comment by youliyuan-fit2cloud** [comment]
image 抄了一样，还是报用户不存在。

您需要根据 ldap 服务器类型选择合适的用户过滤器，可能的选项有 (uid={0}) 或 (sAMAccountName={0}) 或 (cn={0})，可以先试一下修改用户过滤器和对应的属性映射。
