### ISSUE TITLE
[BUG]功能用例设计时可以支持步骤描述和文本描述两种方式，但在测试计划的用例执行的时候只支持步骤描述

### ISSUE THREAD

**Issue by spheretangmeng** [metersphere/metersphere#19851]
### 联系方式

微信：zuanshixiu668 “MeterSphere北方区交流群”

### MeterSphere 版本

2.3.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/113685220/202649302-b79e4059-1fd8-4af5-851f-ad10ffeabc97.png)
![image](https://user-images.githubusercontent.com/113685220/202649323-363bcaa1-953d-4965-8b56-5086097eca4f.png)
在用例设计时只写了文本描述，没有写步骤描述，结果在测试计划执行时，发现步骤描述为空，也没办法切换为文本描述

### 重现步骤

1.创建一个测试用例，只写文本描述，不写步骤描述
2.将该用例加入到测试计划中
3.在测试计划中查看该用例
发现用例步骤中无法切换到文本描述

### 期待的正确结果

可以和用例设计时一样进行步骤描述和文本描述切换

**Comment by xulinde** [comment]
这里设计的时候是 选择一种编辑方式编写，测试计划就按照这种方式展示，您也是只用了一种方式编辑，这里就不添加测试计划修改方式了
