### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Jarvan40** [metersphere/metersphere#19857]
### MeterSphere 版本

v2.3.1

### 请描述您的需求或者改进建议

接口测试功能：
目前我所在的项目里，所有接口都会发到同一个URL。这样在接口定义里，我就无法定义同URL的不同接口。
因为没接触过其他HTTP的项目，只能简单说下我目前项目的接口情况：

请求内容：
接口1：
{
   op_name:"op_name1",
   class: "op_class1",
   params:{},
   ...
}
接口2:
{
   op_name:"op_name2",
   class: "op_class2",
   params:{},
   ...
}

### 请描述你建议的实现方案

在web页面实操发现，新增接口都会有自己的ID，建议用ID来区分接口。

**Comment by luty2018** [comment]
在应用设置开启接口URL可重复就行
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/36292514/203201155-a01d9c47-0c06-4b42-9774-4052beae6662.png">
