### ISSUE TITLE
[BUG] MS (2.3.1) 同步禅道(12.5.3)缺陷失败

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#19856]
### 联系方式

18159668371

### MeterSphere 版本

2.3.1

### 使用外置数据库

否

### 问题描述

1、MS无法完全同步缺陷；
2、MS 同步禅道缺陷页面处于不断加载状态。

### 重现步骤

问题一：

https://user-images.githubusercontent.com/92966838/202670772-8427d5c9-f353-4536-ad9f-6a7f3b491892.mp4

问题二：

https://user-images.githubusercontent.com/92966838/202670867-2d15149e-d502-4f4e-a189-2629a8f7fda1.mp4

**Comment by xulinde** [comment]
问题2已复现，后续版本修复；问题1未复现，请确认下缺陷是否在所选的创建时间范围内

**Comment by gaohonghai** [comment]
问题一：忽略
问题二：
开源（2.3.1）
1、MS 上先创建一个缺陷；
2、MS上 删除该缺陷；
3、MS点击同步缺陷。

**Comment by gaohonghai** [comment]
问题二预计可以在哪个版本修复呀，2.4吗

**Comment by xulinde** [comment]
> 问题二预计可以在哪个版本修复呀，2.4吗

是的

**Comment by gaohonghai** [comment]
感谢感谢

**Comment by xulinde** [comment]
v2.4.0已修复～
