### ISSUE TITLE
[BUG]  swagger导入失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19869]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

 v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

swagger导入失败，报解析失败
![image](https://user-images.githubusercontent.com/103925124/202689751-76e3d17b-4d58-4844-b775-3edd81444cdd.png)

### 重现步骤

使用附件swagger-json文件

[swaggerApi (2).zip](https://github.com/metersphere/metersphere/files/10040638/swaggerApi.2.zip)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
