### ISSUE TITLE
[BUG]Unexecuted场景用例在Test Result图表里没有被统计显示

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19879]
### 联系方式

王进

### MeterSphere 版本

1.20.16

### 使用外置数据库

否

### 问题描述

Unexecuted场景用例在Test Result图表里没有被统计显示

### 重现步骤

1， 客户这边最近碰到测试计划里偶尔会出现一个场景是unexecuted，但是这个unexecuted没有被统计到 Test Result页面的图表里
![402ba3c67828d074828ea8bfa9a8880](https://user-images.githubusercontent.com/76033005/202843687-09a58935-0f5d-456d-bca9-bc6cc247b56d.png)
2. 另外一个客户提到的问题是，触发测试计划后，假如中间去查看报告，看到的执行率是100%，不太合理。
3. 关于Unexecuted出现的原因，还在和客户排查。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
