### ISSUE TITLE
[BUG]接口定义，接口用例，json文档结构校验，在预期结果处输入值后，再打开，值不见了。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#19876]
### 联系方式

王进

### MeterSphere 版本

v1.20.16，v.2.2

### 使用外置数据库

否

### 问题描述

接口定义，接口用例，json文档结构校验，在预期结果处输入值后，再打开，值不见了。

### 重现步骤

1. 选择某一个接口，新建接口用例，
2. 在断言规则 页面添加 文档结构断言，在预期结果处输入数值，保存
3. 再打开，数值不见了。
![1caf95f88ddec5f5da5c6233849b96a](https://user-images.githubusercontent.com/76033005/202735613-6140aed7-b843-440f-a3d0-298a7aef07ce.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
