### ISSUE TITLE
[BUG] UI 测试列表，勾选显示所有数据，点击删除某一个场景，会全部删除掉

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19882]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

UI场景列表，勾选了显示全部数据，点击某一个场景的删除按钮，会把勾选的数据全部删除。
![image](https://user-images.githubusercontent.com/33945037/202951764-7171e424-fb11-4126-89f0-d876b6551fc6.png)

### 重现步骤

UI场景列表，勾选了显示全部数据，点击某一个场景的删除按钮，会把勾选的数据全部删除。

### 期待的正确结果

应该只删除当前的

**Comment by zrfit** [comment]
您好，感谢您的反馈，最新版本不存在该问题，建议升级尝试。

**Comment by hao65103940** [comment]
新版本V2.3.1 UI 不存在了，但是接口自动化场景出现这问题了。



https://user-images.githubusercontent.com/33945037/202990576-4d2781cd-5983-4a98-8d87-83ef2c3d242f.mov

**Comment by zrfit** [comment]
您好，接口场景的问题已经反馈，后续版本修复。
