### ISSUE TITLE
[BUG]  希望UI 导入的时候，跟接口导入一样，可以直接导入对应的层级目录。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19883]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

希望UI导入的效果跟接口导入效果一致。可以支持导入层级目录。

UI
![image](https://user-images.githubusercontent.com/33945037/202952059-e6310adf-e583-4317-a14e-754e0e7cd736.png)

接口
![image](https://user-images.githubusercontent.com/33945037/202952213-a29927d3-d77e-49f6-a770-28673e84b4e2.png)

### 重现步骤

UI场景导入

### 期待的正确结果

可以支持导入层级目录

**Comment by zrfit** [comment]
您好，感谢您的反馈，UI场景支持导出导入MS格式，已经加入产品迭代计划，后续版本会增加该功能。
