### ISSUE TITLE
[BUG]状态码非2开头的接口在测试报告中提示为失败，实际断言是成功的。

### ISSUE THREAD

**Issue by qingqingdufu** [metersphere/metersphere#1989]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？  
 v1.8.0-21bf611d

**Bug 描述**
执行【错误密码登录】场景用例时，断言成功，测试报告中显示失败，报告列表中显示error。

**Bug 重现步骤**
1.  接口场景中新增【错误密码登录】，断言规则为msg中包含“登录失败”；
2.  执行场景用例，登录接口返回为  {"status":"400","msg":"登录失败，..........."} ，查看测试报告--》断言成功，但提示为失败

**期待的正确结果**
猜测是将接口返回状态码非2开头的用例都视为 失败了。
期望以断言结果为准，断言成功则用例通过；断言失败则用例fail。既然是测试用例，关键步骤必然有断言。一个场景中至少有1条断言。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/38524981/114157106-dcc37900-9955-11eb-8c4d-07dc7bd2cd17.png)

**Comment by zyyfit** [comment]
您好，这边没有复现这个问题，请问您断言中勾选忽略状态了吗
![图片](https://user-images.githubusercontent.com/73461316/114163808-30859080-995d-11eb-930b-2a1fcb3d7266.png)

**Comment by qingqingdufu** [comment]
没有看到忽略状态这一选项：
![image](https://user-images.githubusercontent.com/38524981/114164253-a853bb00-995d-11eb-9fff-976cb41d792d.png)

**Comment by zyyfit** [comment]
> 没有看到忽略状态这一选项：
> ![image](https://user-images.githubusercontent.com/38524981/114164253-a853bb00-995d-11eb-9fff-976cb41d792d.png)

是这样的，只有选择对文本或者正则断言里的responseCode断言才会有这个选项

**Comment by qingqingdufu** [comment]
为啥jsonpath断言不支持呢？这不合理啊，都是一样的断言目的
