### ISSUE TITLE
[BUG] 【接口测试】-接口用例-rest参数-点高级设置按钮，界面呈现灰色不可编辑，再次点击才会恢复正常

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#19890]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

是

### 问题描述

在rest参数界面-点高级设置按钮，界面呈现灰色不可编辑，再次点击才会恢复正常

### 重现步骤

1.进入接口case界面
2.点rest参数选项
3.点高级设置按钮

### 相关日志输出

```shell
点高级设置按钮，进入高级设置界面可以编辑
```

### 附加信息

1.录屏
[问题录制.zip](https://github.com/metersphere/metersphere/files/10052661/default.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
