### ISSUE TITLE
[BUG] 对不同脚本语言进行区分，高亮显示

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#19897]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

V2.2版本

![image](https://user-images.githubusercontent.com/33945037/202977249-8b787201-de81-4c71-83f4-2711b592d572.png)

V2.3 版本
系统设置->环境管理->配置环境->全局前置/后置脚本

![image](https://user-images.githubusercontent.com/33945037/202977277-de884fc1-63d9-46bc-909c-f9cf81d6ac27.png)

### 重现步骤

V2.3 版本
系统设置->环境管理->配置环境->全局前置/后置脚本
![image](https://user-images.githubusercontent.com/33945037/202979698-ff86f1d0-ea16-4939-8218-9a4df7b160fe.png)

### 期待的正确结果

高亮显示

**Comment by zyyfit** [comment]
感谢您的反馈，2.4.0版本已经修复了这个问题，请等待版本发布后验证
