### ISSUE TITLE
[BUG]【非系统管理员权限用户】点击高级搜索，会退出登录

### ISSUE THREAD

**Issue by bestdd** [metersphere/metersphere#199]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
master
**Bug 描述**
简要描述您碰到的问题
【非系统管理员权限用户】点击高级搜索，会退出登录
**Bug 重现步骤**
1.  创建非“系统管理员权限”，其他权限的用户
2. 登录后，【点击测试跟踪】-【点击项目】-【选择XX项目】-【点击高级搜索】

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/7333223/89283059-17ff0100-d67f-11ea-942f-27fa305cf944.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你的代码是最新的吗？这个问题我们有修改，你可以更新下代码再试一下

**Comment by bestdd** [comment]
已解决
