### ISSUE TITLE
[BUG]场景测试中，批量禁用后，再单步启动其中几步，该脚本下的前置操作中的脚本无法打开，保持禁用状态。

### ISSUE THREAD

**Issue by JoyceQ2022** [metersphere/metersphere#19918]
### 联系方式

qiao.jing.joyce@vertiv.com

### MeterSphere 版本

 v1.20.13-lts-4e5c1d1c

### 使用外置数据库

否

### 问题描述

场景测试中，批量禁用后，再单步启动其中几步，该脚本下的前置操作中的脚本无法打开，保持禁用状态。

### 重现步骤

![1](https://user-images.githubusercontent.com/116712473/203006640-3d06da1d-a9fd-438c-95e8-0594910273b7.jpg)

### 期待的正确结果

启用该步时，其内部的前置或者后置脚本中的启用禁用应该也可以进行操作。

**Comment by youliyuan-fit2cloud** [comment]
你好，你期望的结果是：启用步骤时，其内部的前后置脚本同时自动被开启是吗？
当前确实需要单独手动开启前后置的开关。

**Comment by JoyceQ2022** [comment]
> 你好，你期望的结果是：启用步骤时，其内部的前后置脚本同时自动被开启是吗？ 当前确实需要单独手动开启前后置的开关。

是的，在场景里，批量禁止后，单独打开某一步时，希望该步里的前置或后置脚本同步开启，或者允许点击开启，目前开启不了。
