### ISSUE TITLE
[BUG] 接口参数设置中添加函数后不点保存，点击下一个参数的小铅笔，历史函数不可消除，导致预览还会加上函数；重新进入场景编辑参数，无此问题

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#19929]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

接口参数设置中添加函数后不可消除

### 重现步骤

在接口参数设置拼接函数
![image](https://user-images.githubusercontent.com/103925124/203016062-bf530ded-7cef-48be-b868-06664f1a2131.png)
不退出点击下一个参数的小铅笔
![image](https://user-images.githubusercontent.com/103925124/203021028-3711319e-252b-4926-ad47-864310456d85.png)
可以看到依然后记录，且函数是选中状态，如果此参数不想用函数
点击@word后，想预览一下，就会带上concat:88上次的数据
![image](https://user-images.githubusercontent.com/103925124/203021703-739202ea-b15e-4385-ae59-a5ac1a6e8dcb.png)
![Uploading image.png…]()

### 期待的正确结果

参数设置 不留痕

**Comment by youliyuan-fit2cloud** [comment]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/54612864/203453652-2017ba07-6d25-4300-a882-0ecf31cdf577.png">

最后一张图看不到，请重新上传。

**Comment by Ycr123888** [comment]
最后一张图不重要了，前面的图就够了

**Comment by youliyuan-fit2cloud** [comment]
> 最后一张图不重要了，前面的图就够了

抱歉，因为没复现这个问题，猜测是最后一张图的没有，所以没看明白是什么问题
