### ISSUE TITLE
[BUG]MS录制插件-get请求query参数为空时解析from表单时丢失参数

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#19936]
### 联系方式

群14-亲山留水

### MeterSphere 版本

1.20.15-lts

### 使用外置数据库

是

### 问题描述

1、query参数传值为空时，MS插件录制脚本在from表单未展示，可能存在查询结果不一致的情况
![image](https://user-images.githubusercontent.com/82088551/203023423-b334bad3-89f4-440f-a424-1fdc8bded94c.png)   MS插件录制形成的错误展示
![image](https://user-images.githubusercontent.com/82088551/203023888-742666be-b7bb-47b6-b1e4-b10d739fe900.png)  原生录制形成的正常展示

2、建议MS插件录制脚本事务及请求名称如原生代理脚本类似
![image](https://user-images.githubusercontent.com/82088551/203024846-c9aca1d9-8243-411c-9e1e-a74aaa13b09f.png)
建议MS插件录制形成的脚本如原生jmeter代理录制脚本命名类似，如http请求名称仅保留事务名称_编号+URLPATH，参数部分不应放在请求名呢，存在如下不变，MS平台页面展示不清晰，且不能因编号保持固定请求顺序

### 重现步骤

MS录制插件 和原生jmeter代理 分别录制脚本

### 期待的正确结果

![image](https://user-images.githubusercontent.com/82088551/203025971-d8d65d11-f493-49c7-ba49-7623af056950.png)
期望 MS平台请求统计展示类似如上   详细展示事务时，展示请求名称如上  事务名称+数字编号+URLPATH

**Comment by zhangzhaox** [comment]
@xulinde 希望MS插件录制形成的脚本形式参考
![image](https://user-images.githubusercontent.com/82088551/203942867-9093ce26-7163-4975-bc97-9506afbfac95.png)
简洁的 http请求名称 前缀数字排列 方便在MS平台执行报告 事务明细按照明细排序

**Comment by xulinde** [comment]
> @xulinde 希望MS插件录制形成的脚本形式参考 ![image](https://user-images.githubusercontent.com/82088551/203942867-9093ce26-7163-4975-bc97-9506afbfac95.png) 简洁的 http请求名称 前缀数字排列 方便在MS平台执行报告 事务明细按照明细排序
> 
> #{counter,number,000} - #{path} (#{name})或者#{counter,number,000} - #{path}

感谢您的建议，后续我们会做考虑～

**Comment by zhangzhaox** [comment]
> > @xulinde 希望MS插件录制形成的脚本形式参考 ![image](https://user-images.githubusercontent.com/82088551/203942867-9093ce26-7163-4975-bc97-9506afbfac95.png) 简洁的 http请求名称 前缀数字排列 方便在MS平台执行报告 事务明细按照明细排序
> > #{counter,number,000} - #{path} (#{name})或者#{counter,number,000} - #{path}
> 
> 感谢您的建议，后续我们会做考虑～

希望能纳入3.0版本优化
