### ISSUE TITLE
[BUG] 多项目同名环境变量有覆盖

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19931]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

在一个项目中引用另外一个项目的场景，同名的环境变量被覆盖。

### 重现步骤

1.创建 2 个 A 和 B 项目，2 个项目的环境变量都配置有 token
2.在 B 中创建场景用例，只有一个步骤 自定义脚本 log.info("B token: ${token}");
3.在 A 中创建场景用例
   >步骤 1 自定义脚本：log.info("A token before: ${token}");
   >步骤 2 引用 B 创建的场景用例
   >步骤 3 自定义脚本：log.info("A token after: ${token}");

A 项目环境变量 token 值：A token value
B 项目环境变量 token 值：B token value

执行 A 中的场景用例，***使用环境组***，结果如下
![image](https://user-images.githubusercontent.com/4860962/203023162-55ff6119-4ee9-48e2-b984-1874cf4d8a42.png)

### 期待的正确结果

期待 A 中最后一个步骤打印 A 中 token 的值

**Comment by xulinde** [comment]
和开发确认了下，执行机制就是这样的哦，比如第三个步骤想使用前面步骤提取后的值怎么办；完全隔离了就没法使用了，这样会出现更多问题，也完全改变了JMeter的变量传递机制了。

**Comment by hao1032** [comment]
额，我不清楚 jmeter 能不能模仿类似的场景？ 你知道吗？ 如果可以我去试一下。

不过你们的流程是怎么回事啊？
1.你们15 小时前发更新日志说修复了这个 bug，并且已经发布了新版本
![image](https://user-images.githubusercontent.com/4860962/203893775-c11c796b-cc3e-4676-928a-de48d6614bf1.png)
![image](https://user-images.githubusercontent.com/4860962/203893803-18994c7c-d33f-40bc-811d-1bff54f9cc96.png)

2. 15 个小时后，在已经发版后，又说这个 bug 不用修改。？？？？？？？？？

**Comment by luty2018** [comment]
> 额，我不清楚 jmeter 能不能模仿类似的场景？ 你知道吗？ 如果可以我去试一下。
> 
> 不过你们的流程是怎么回事啊？ 1.你们15 小时前发更新日志说修复了这个 bug，并且已经发布了新版本 ![image](https://user-images.githubusercontent.com/4860962/203893775-c11c796b-cc3e-4676-928a-de48d6614bf1.png) ![image](https://user-images.githubusercontent.com/4860962/203893803-18994c7c-d33f-40bc-811d-1bff54f9cc96.png)
> 
> 2. 15 个小时后，在已经发版后，又说这个 bug 不用修改。？？？？？？？？？

非常抱歉， 这个是统计修复缺陷的时候出现了失误，同名变量这里无法制订一个规则同时满足两种需求，所以我们遵循了jmeter的处理原则，这个问题确实不需要改。
