### ISSUE TITLE
导入postman json文件没有导入全且目录和postman不一致

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#1995]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
导入postman json文件没有导入全且目录和postman不一致

**Bug 重现步骤**
1.  导入Postman Collection v2.1 格式的 json 文件
2.  导入之后没有把所有的接口都导入进来（相同的API接口参数不同没有生成对应的case）
3.  导入之后目录关系错乱

**期待的正确结果**

![image](https://user-images.githubusercontent.com/35896106/114332871-a49c8000-9b79-11eb-832e-4a92ef235f4d.png)

**截图**
![image](https://user-images.githubusercontent.com/35896106/114332872-a49c8000-9b79-11eb-9d77-b9355fa7be5e.png)

**Comment by zyyfit** [comment]
您好，相同的API接口参数不同没有生成对应的case这个问题我们会在后续版本优化，目录混乱这个问题没有复现，能描述一下具体操作步骤或者方便提供一下原始数据文件吗

**Comment by weishuo6** [comment]
附件为原始数据文件，请查收。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月14日(星期三) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 导入postman json文件没有导入全且目录和postman不一致 (#1995)





 
您好，相同的API接口参数不同没有生成对应的case这个问题我们会在后续版本优化，目录混乱这个问题没有复现，能描述一下具体操作步骤或者方便提供一下原始数据文件吗

**Comment by zyyfit** [comment]
> 附件为原始数据文件，请查收。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年4月14日(星期三) 上午10:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 导入postman json文件没有导入全且目录和postman不一致 (#1995) 您好，相同的API接口参数不同没有生成对应的case这个问题我们会在后续版本优化，目录混乱这个问题没有复现，能描述一下具体操作步骤或者方便提供一下原始数据文件吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，邮件里没有收到附件呢

**Comment by zyyfit** [comment]
您好，目前最新版是1.10.3，请升级后试试还会不会出现这个问题
