### ISSUE TITLE
[BUG]多项目使用环境组，场景用例环境没有替换

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#19967]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

调试场景使用环境 env1，环境组配置环境 env2，执行时没有使用 env2.

### 重现步骤

1. 创建项目 A，为 A 创建 2 个环境 env1 和 env2，环境中都有环境变量 token
2. 在 A 中创建场景用例，执行环境选择 env1，加入步骤-自定义脚本，打印 token 值
3. 创建项目 B，为 B 创建 1 个环境 env1
4. 在系统设置中，创建环境组 envGroup，包含 A 项目的 **env2** 和 B 项目的 env1
5. 在项目 B 中，创建场景用例，执行环境选择 环境组 envGroup，加入步骤-引用项目 A 的场景用例（第二步创建的）
6. 执行 B 中的场景用例，发现打印的不是 A 项目 **env2** 中的环境变量 token 值

### 期待的正确结果

可以打印 A 项目 env2 的 token 值

**Comment by hao1032** [comment]
ms是不是要发新版本了，可以看看这个 bug 吗？ 能不能在新版本前给修复下呢？
挺影响使用的。

**Comment by youliyuan-fit2cloud** [comment]
你好，根据你的描述没有复现该问题，方便把你这个场景上传一下吗？

**Comment by hao1032** [comment]
[归档.zip](https://github.com/metersphere/metersphere/files/10073638/default.zip)

有需要可以微信联系我，hao1032 ，着急

**Comment by hao1032** [comment]
不能复现了，有情况再更新
