### ISSUE TITLE
[FEATURE]API文档对应的swagger地址，希望能够加个鉴权，只有metersphere登录的用户才可以访问

### ISSUE THREAD

**Issue by TTtesting** [metersphere/metersphere#1996]
**请描述您的需求或者改进建议.**

API文档对应的swagger地址，希望能够加个鉴权，只有metersphere登录的用户才可以访问

**请描述你建议的实现方案**

API文档对应的swagger地址，希望能够加个鉴权，只有metersphere登录的用户才可以访问

**Comment by xulinde** [comment]
您是要二次开发吗
