### ISSUE TITLE
[BUG]【接口定义-test 】处修改参数值，点击“更新接口”，case处的值没有同步修改

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#19975]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

接口定义-test 处修改参数值，点击“更新接口”，case处的值没有同步修改

### 重现步骤

接口定义-test 处修改参数值，点击“更新接口”，case处的值没有同步修改
![image](https://user-images.githubusercontent.com/104960608/203216762-e65265b4-7c5c-45fa-8e8d-5be657c2f242.png)
![image](https://user-images.githubusercontent.com/104960608/203216839-ef9eb318-dedd-4229-a317-72aabdccd451.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，抱歉，这个问题经过和开发，产品确认，TEST页面修改后并更新接口，不会同步修改CASE内容。目前可以在Api页面修改后，保存时会提示是否同步到CASE。
