### ISSUE TITLE
[BUG]测试计划关联用例，当用例较多的时候崩溃（6000条）

### ISSUE THREAD

**Issue by wangqibiao1987** [metersphere/metersphere#19980]
### 联系方式

250300336@qq.com

### MeterSphere 版本

v2.3.1-lts 

### 使用外置数据库

否

### 问题描述

[BUG]测试计划关联用例，当用例较多的时候崩溃（6000条）

### 重现步骤

登录后台，点击测试跟踪--测试计划--新建测试计划--关联测试用例
当用例较多，几千条，加载过程中崩溃保存，提示内存泄漏
当用例较少，几十条，加载正常

**Comment by youliyuan-fit2cloud** [comment]
你好，服务器配置是多少？开源版服务器配置至少4U8G。

**Comment by wangqibiao1987** [comment]
服务器配置是8核16G,后来看了下，300条案例就内存泄露崩溃了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月23日(周三) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]测试计划关联用例，当用例较多的时候崩溃（6000条） (Issue #19980)




 
你好，服务器配置是多少？开源版服务器配置至少4U8G。

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题后续会继续优化。
目前建议你修改测试跟踪模块的默认可使用的内存配置，即修改/opt/metersphere/docker-compose-test-track.yml文件中的内存配置
