### ISSUE TITLE
[BUG]MS chrome 浏览器插件安装时报错

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#19991]
### MeterSphere 版本

2.0

### 使用外置数据库

否

### 问题描述

安装浏览器插件时报错：
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details

### 附加信息

Chrome 浏览器版本：107.0.5304.87（正式版本） (x86_64)

**Comment by Andyguo5891** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/46042812/203241284-4e0fcddc-64b4-420f-9acf-c4c942b976bf.png">

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/203676596-d921ccfe-9c9c-468f-9010-3b1b97384741.png)


这个版本安装正常，升级一下？
