### ISSUE TITLE
是否会提供 SaaS 版本？

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#2]
或者有个在线的快速体验环境？

**Comment by wangzhen-fit2cloud** [comment]
在线环境计划在下个版本（7月底）提供，SaaS 版的话长远看会有，但还没有明确的时间点。

**Comment by maninhill** [comment]
期待。

**Comment by zhcloud** [comment]
SaaS 是免费的吗？

**Comment by buuugmaker** [comment]
> SaaS 是免费的吗？

@zhcloud  你好，这个目前还没有很明确的计划哈。有什么新的进展和计划我们会在 github 和官网更新的，欢迎持续关注。
