### ISSUE TITLE
[FEATURE]接口测试部分费力度太高，跟实际操作差距略大，能不能增强？可参考Hitchhiker

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#20]
**请描述您的需求或者改进建议.**
接口测试部分费力度太高，跟实际操作差距略大

**请描述你建议的实现方案**
https://github.com/fangyuanrui/Hitchhiker

**Comment by wangzhen-fit2cloud** [comment]
你好，能否针对这个问题举几个具体的例子。目前情况来看我们整体再转换成类似 Hitchhiker 的使用方式不太现实，可以针对不好用的地方进行针对性的优化。

**Comment by guhan121** [comment]
@wangzhen-fit2cloud 
可以从json返回值中快速添加断言
![like this](https://raw.githubusercontent.com/brookshi/images/master/Hitchhiker/assert.gif)

**Comment by guhan121** [comment]
@wangzhen-fit2cloud

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，我们目前正在对接口测试进行比较大的修改，在新版本中会参考借鉴上面的两个功能。
@luty2018
