### ISSUE TITLE
[BUG]阿里云服务器 CentOS 8 操作系统一键安装失败

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#200]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.1.1

**Bug 描述**
简要描述您碰到的问题

![image](https://user-images.githubusercontent.com/41712985/89291058-6ebf0780-d68c-11ea-8461-0b16b167a126.png)
![image](https://user-images.githubusercontent.com/41712985/89291082-77afd900-d68c-11ea-95fc-d591cccefb2c.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，已收到你的反馈，我们去确认一下

**Comment by wangzhen-fit2cloud** [comment]
你好，根据 docker 官网文档，目前还没有推出官方的 docker 包
