### ISSUE TITLE
老版本升级新版本2.3.1后，测试用例--steps字段中未对预期结果为空时做兼容处理，导致测试用例导出报空指针错误

### ISSUE THREAD

**Issue by chuwenyuan** [metersphere/metersphere#20007]
### 联系方式

MeterSphere交流群31--@媛哥哥哥哥哥~   邮箱：530437008@qq.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

1、服务器从1.xx版本通过离线升级包 升级到2.3.1版本。
2、升级完成后， 测试用例进行导出操作， 发现页面一直处于加载空白状态， 用例导出失败。
3、查看日报报空指针错误。
4、经排查后发现老版本测试用例步骤中预期结果为空时，数据库test_case中steps字段的json未存储result。新版本创建测试用例，预期结果为空时会存储result为空字符串。
5、升级后，对于result兼容上有问题。

举例：预期结果未填
老版本升级后的steps字段：
[{
 "num": 1,
 "desc": "点击任务列表",
 "result": "任务描述可输入100个字符"
}, {
 "num": 2,
 "desc": "点击新建任务"
}, {
 "num": 3,
 "desc": "点击全场景攻击模拟模板"
}, {
 "num": 4,
 "desc": "任务名称输入100个字符"
}]

2.3.1版本的steps字段：
[{"num":1,"desc":"跳转主机页面成功","result":""}] 

### 重现步骤

1、在1.xx版本上创建测试用例，预期结果不填写。
2、升级为2.3.1版本。
3、导出这个测试用例
4、导出一直处于页面空白加载中，导出失败。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0中已修复。
