### ISSUE TITLE
[BUG] 自定义member字段校验CustomFieldMemberValidator不支持姓名相同的用户

### ISSUE THREAD

**Issue by bingosam** [metersphere/metersphere#20008]
### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

excel导入用例时，若用例负责人在系统中出现同名，则此处转化为map时异常

![2022 11 22_张坤彬 3744fe7222e968ccdee5dc56fb7c1500](https://user-images.githubusercontent.com/20456289/203253740-3aaed954-0797-4df9-9033-4cb0a76a7a85.png)

### 重现步骤

创建2个同名帐号
导入用例，指定用例负责人为其中一个ID

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.0已4修复。
