### ISSUE TITLE
[BUG]接口自动化里，创建自定义请求rest不会替换变量

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2000]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口自动化，创建场景，添加自定义请求，rest参数 不会替换变量
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
<img width="1226" alt="企业微信截图_28dc798a-5554-47ad-ad6a-91a906b5b335" src="https://user-images.githubusercontent.com/30038088/114376539-49d64900-9bb8-11eb-8407-b545af8f09d2.png">

**Comment by xulinde** [comment]
下个版本修复

**Comment by shenkaibo** [comment]
是的 提错了 忽略额
