### ISSUE TITLE
你好，在新版本中已实现该功能

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#2001]
你好，在新版本中已实现该功能

_Originally posted by @wangzhen-fit2cloud in https://github.com/metersphere/metersphere/issues/189#issuecomment-712096047_

**Comment by lingrance** [comment]
请问在 v1.8.2 中上传下载的入口在哪里呀？

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/114963458-67006580-9e9f-11eb-8da4-4df1ac0a73fa.png)

**Comment by lingrance** [comment]
太棒啦！
