### ISSUE TITLE
[BUG] 缺陷记录2021-04-12

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2002]
**MeterSphere 版本**
1.8.2

**Bug 描述**

功能块 | 描述 | 期望
-- | -- | --
登录 | 添加组织成员权限后进入系统无法看到项目等内容，跟没有权限一样 | 权限开通后立即生效
登录 | 分配空间后重新登录可能导致无法获取到空间权限 |  
场景自动化 | UI检视部分用例无法自动化仍需人工校验 |  
场景自动化 | UI部分默认是展开的，交互不够友善 |  
  | 编辑脚本时，点击代码模板，新增的脚本不会增加至游标处，而是增加至脚本末尾 |  
  | 点击执行，执行结束后，界面显示的响应结果可能不是最新的，而是前一次执行的结果 |  
  | 当复制一个A创建的场景后，创建人不变，期望显示责任人 |  
  | 场景用例基础信息里不显示id，不方便查询 |  
场景自动化 | 已执行调试，断言规则处点击推荐JSONPath提取时仍提示【请先执行调试获取响应结果】更新：必须在编辑界面点击执行才可以获取到响应结果 |  
  | 登陆过期后点击页面显示Network error，刷新后才跳转到登录窗期望：登陆过期后点击页面直接跳转到登录窗 |  
场景自动化 | 1.8.0全屏模式编辑场景，自定义脚本窗口不支持左右滑动，导致脚本容易无法完全显示出来 |  
  | 在全屏模式下设置运行环境点调试，提示未设置 |  
  | 场景用例里添加描述保存后描述内容不见了 |  
场景自动化 | 被引用的场景环境变量会生效，导致新场景设定的环境变量会覆盖 |  
  | 将一子模块的用例移至回收站并清空，再创建同名子模块时会报错【该层级下已存在此模块名称】 |  
场景自动化 | 创建场景用例，选择模块时，模块较多，建议支持模糊搜索 |  
场景自动化 | 场景用例里面，描述文案保存后，再次进入描述文案为空：100115进入场景用例详情，修改操作步骤文案，保存后未生效；100115 |  
场景自动化 | 一个场景用例，打开2个场景详情tab之后，保存最新修改的tab，然后再切换回旧tab，保存，会保存旧的内容，很容易出现最新内容被旧内容覆盖的情况 |  
场景自动化 | 用例展开步骤后，导入场景或接口列表时已展开着的步骤会自动折叠起来 |  
平台 | 修改用例没有log，无法知道他人修改的内容 | 至少能看到谁动了用例
平台 | 用例状态缺少审核状态 | 1. 用例除现有三个状态外可以考虑添加待审核状态；审核完成之后改为已完成
平台 | 场景变量中变量的列表不能区分开；如果列表定义成变量脚本直接报错；调试报告返回undefined | 1. 如果脚本报错；能在调试报告中显示脚本异常
平台 | 每次调试都保存场景用例；导致用例最后更新时间没有任何意义； | 如场景用例未发生变化则不更新最后时间
平台 | 如果接口定义时写错POST为get;后期调试发现修改了接口定义；但是接口CASE不会跟着更新 |  

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，
1、“添加组织成员权限后进入系统无法看到项目等内容，跟没有权限一样”，这块是说已经分配了具体的工作空间权限了吗？组织成员自己单独的权限目前是不能进行其他操作的

2、“分配空间后重新登录可能导致无法获取到空间权限” 这个问题是稳定复现的吗？是的话可以描述一下复现步骤吗？

3、“场景变量中变量的列表不能区分开；如果列表定义成变量脚本直接报错；调试报告返回undefined” 这个问题是取不到变量中的变量值，这边测试没有报错，能具体描述一下复现步骤吗？

4、“如果接口定义时写错POST为get;后期调试发现修改了接口定义；但是接口CASE不会跟着更新” 这个问题设计的时候考虑到维护接口定义和接口用例的可能分别是开发和测试，故修改接口定义后不应该同步修改接口用例，接口用例可以手动批量修改（如url、请求方式等）

其他问题会考虑后续版本优化的

**Comment by guhan121** [comment]
@zyyfit 

api_case 怎么批量修改请求类型；我是直接去数据库改的...

**Comment by zyyfit** [comment]
> @zyyfit
> 
> api_case 怎么批量修改请求类型；我是直接去数据库改的...

![图片](https://user-images.githubusercontent.com/73461316/114650749-5cb26000-9d15-11eb-9195-3ae92b7d01f7.png)

![图片](https://user-images.githubusercontent.com/73461316/114650764-60de7d80-9d15-11eb-820c-799de4aec992.png)

**Comment by guhan121** [comment]
@zyyfit 
![image](https://user-images.githubusercontent.com/5517369/114651840-486f6280-9d17-11eb-900c-f18fe68dcc80.png)
![image](https://user-images.githubusercontent.com/5517369/114651867-57561500-9d17-11eb-9d32-4efbdc981955.png)

**Comment by guhan121** [comment]
> > @zyyfit
> > api_case 怎么批量修改请求类型；我是直接去数据库改的...
> 
> ![图片](https://user-images.githubusercontent.com/73461316/114650749-5cb26000-9d15-11eb-9195-3ae92b7d01f7.png)
> 
> ![图片](https://user-images.githubusercontent.com/73461316/114650764-60de7d80-9d15-11eb-820c-799de4aec992.png)

这个有点隐蔽
