### ISSUE TITLE
[BUG] 性能测试，脚本带参数化执行时报错

### ISSUE THREAD

**Issue by itransit** [metersphere/metersphere#20026]
### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

[BUG] 性能测试，脚本带参数化执行时报错：
后台：
![image](https://user-images.githubusercontent.com/20274103/203287685-4c6846f3-2e64-4cbf-9d4d-cd134ae9ca53.png)
前端：
![4d03917bfd807c62d50400a43ce2ed3](https://user-images.githubusercontent.com/20274103/203287793-91761910-714c-4ebd-bef9-92db0d2793ed.png)
在v2.2.1中正常：
![6c9d03ce01c70761a60550f0e871da9](https://user-images.githubusercontent.com/20274103/203287863-84c67b93-fd66-4320-988e-a2b7d096f778.png)

### 重现步骤

1录制脚本
2性能测试，高级配置中添加自定义变量
3保存并运行

**Comment by 2lipan** [comment]
脚本如下:
[RECORD-2022-11-22-1606.zip](https://github.com/metersphere/metersphere/files/10066489/RECORD-2022-11-22-1606.zip)

![image](https://user-images.githubusercontent.com/104960608/203291817-ef214ba2-12ea-4c97-b63c-473a20ca630e.png)
