### ISSUE TITLE
[BUG]功能用例-脑图模式，点击放大按钮后，左侧区域出现遮挡，显示不完整。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20031]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

功能用例-脑图模式，点击放大按钮后，左侧区域出现遮挡，显示不完整。

### 重现步骤

1. 脑图模式，点击放大按钮
![image](https://user-images.githubusercontent.com/104960608/203292404-d56e3f55-d914-420b-b12a-f82a4c3416ba.png)

2.左侧区域出现遮挡，显示不完整
![image](https://user-images.githubusercontent.com/104960608/203292604-c985f05d-f6f7-4798-80c5-3e3c295d6e12.png)

**Comment by 2lipan** [comment]
v2.6.0版本问题依然存在
![image](https://user-images.githubusercontent.com/104960608/215416609-37ea3bbe-e9e0-475b-88c2-d8a3439f612f.png)

**Comment by youliyuan-fit2cloud** [comment]
计划在v2.7.0 中解决。

**Comment by youliyuan-fit2cloud** [comment]
v2.7.0 中已修复。
