### ISSUE TITLE
[BUG]场景级联引用bug.

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2003]
**MeterSphere 版本**
1.8.2

**Bug 描述**
场景A引用接口case c1；场景B引用场景A;接口case c1更新(更新断言脚本)； 
打开场景B;点击更新；显示的接口case信息是最新的；
运行发现接口断言脚本还是旧的。

在B中删除A; 打开A 点击刷新保存；再到B中引用A;
点击调试脚本正常!

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by zyyfit** [comment]
v1.10.0版本已修复了这个问题，请升级后使用
