### ISSUE TITLE
[BUG]postman文件导入后，有4条用例只导入成功第一条数据

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#20038]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v1.20.x-lts&2.2.0

### 使用外置数据库

否

### 问题描述

一个postman接口文件，里面有4个path和请求方式一致的接口，只是接口参数不一样，导入时只能导入成功一个接口以及一条用例

### 重现步骤

1、导入存在path和请求方式一致的接口postman文件
2、查看MS是否导入成功多条用例

### 期待的正确结果

导入path和请求方式一致，请求参数不一致的接口时，识别生成为一个接口多条用例

**Comment by youliyuan-fit2cloud** [comment]
postman正常的导入是根据文件的item有几个就会生成几个接口, 如果是idea插件导出的文件不会生成case，如果普通的postman文件，不会带有case，那么case的生成是根据api生成的， 然后根据下图中url可重复这个条件事否开启，进行筛选，如果开启url不可重复， 会根据重复的判断条件默认导入重复的第一条。 我们目前的逻辑不会生成多个用例。
![image](https://user-images.githubusercontent.com/54612864/205243659-b760adf7-0740-4ac7-a97a-fea07de3cc9f.png)
