### ISSUE TITLE
[FEATURE] API 调试问题

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2004]
**请描述您的需求或者改进建议.**

1. 我们单个API和API CASE是没法调试的；需要放到前置后置场景中去调试
2. 希望能在场景中调试；然后在API CASE中能看到调试时返回的响应报文；这样最起码能直接在API case里面直接加断言

**请描述你建议的实现方案**

1. 响应报文可以按照接口的ID保存一份最新的 或者 根据引用的保存多份
比如数据库就可以 为 API_ID API_CASE_ID  RESP_DATA 

这样 在API CASE就可以看到对应的报文

**Comment by guhan121** [comment]
或者推荐的json断言的那个table可以自己贴一个json进去 然后生成断言

**Comment by xulinde2** [comment]
这里后面会优化
