### ISSUE TITLE
优化建议性能测试模块查询SQL优化

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#20076]
### MeterSphere 版本

1.20.15-lts

### 请描述您的需求或者改进建议

SELECT report_id AS reportId, content, part
FROM load_test_report_detail
WHERE report_id = '0a1851c1-f690-4054-81f1-b6ac34593a32' AND part > 1
ORDER BY part
优化前相当于全表扫描效果，具体到本SQL 原始的主键索引效果较差
![image](https://user-images.githubusercontent.com/82088551/203503129-7b436505-0e2f-48f0-8569-47c15c97971c.png)
![image](https://user-images.githubusercontent.com/82088551/203503565-f1eb2559-64bb-4f4d-8fbd-c58794403e45.png)

![image](https://user-images.githubusercontent.com/82088551/203502981-8314e65b-76d8-478e-8cf4-2933d7b8c81f.png)
原始主键索引不好调整，可冗余一个索引
ALTER TABLE metersphere.load_test_report_detail
  ADD INDEX IDX1_load_test_report_detail (report_id, part);
优化后的效果
![image](https://user-images.githubusercontent.com/82088551/203502791-e6e9c7c2-56ad-4789-ab18-e067eb4bdbc8.png)

### 请描述你建议的实现方案

方案如上

### 附加信息
SQL2 
SELECT count(0)
FROM api_definition
     LEFT JOIN user ON api_definition.user_id = user.id
     LEFT JOIN project_version
        ON project_version.id = api_definition.version_id
WHERE     api_definition.protocol = 'HTTP'
      AND api_definition.module_id IN
             ('09c4355f-250e-49c3-ae88-3f64a19832f7')
      AND api_definition.status IN ('Prepare', 'Underway', 'Completed')
      AND api_definition.latest = 1
\G;

补充索引
ALTER TABLE metersphere.api_definition
  ADD INDEX IDX_module_id (module_id, status);
![image](https://user-images.githubusercontent.com/82088551/203506795-1b9e8d0e-e0a7-4a6f-8896-4517ba5f4044.png)

**Comment by liuruibin** [comment]
感谢提醒，我们后面会考虑优化这里的查询SQL
