### ISSUE TITLE
[FEATURE]新增GET接口时更改url唯一性限制范围

### ISSUE THREAD

**Issue by qingqingdufu** [metersphere/metersphere#2008]
**请描述您的需求或者改进建议.**
我们有一系列GET接口，url相同，通过查询参数来区别，例如  /flow?type=todo ，/flow?type=rev ，/flow?type=mine，
但是，新增接口时会报错：请求地址已存在！ 那我只能建一个接口，使用时反复改参数，非常麻烦。

**请描述你建议的实现方案**
GET类型接口 由原来逻辑： url 唯一性校验 更改成  url+param组合后 唯一性校验

**Comment by guhan121** [comment]
@qingqingdufu 好奇问一下 这个type=todo 难道不应该是接口请求参数么

**Comment by qingqingdufu** [comment]
是query请求参数，是跟 url拼接在一起使用的。完整的路径示例：
获取来源为微信的数据 ---http://www.baidu.com?resource=wechat ,
获取来源为QQ的数据 ---http://www.baidu.com?resource=qq ,
获取来源为网页的数据 ---http://www.baidu.com?resource=pc ,
我希望建3个接口，方便场景中直接引用。
如果限制url：http://www.baidu.com的唯一性，用户就不能引用了，只能复制，然后每次都要改参数。改来改去，都是那几个固定的参数，那为啥不允许直接多建几个接口呢？

**Comment by guhan121** [comment]
应该是你 只有一个接口 www.baidu.com 然后有三个接口case

**Comment by qingqingdufu** [comment]
有道理，这个可以关了
