### ISSUE TITLE
[BUG] GET请求query参数未生效

### ISSUE THREAD

**Issue by qingqingdufu** [metersphere/metersphere#2009]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8

**Bug 描述**
GET请求 query参数未生效，导致返回数据为空。

**Bug 重现步骤**
1.  创建查询流程场景，get接口：/flow?type=todo&limit=10  
2. 选择环境后，点击调试
3. 返回数据为空，查看日志，请求数据中，type=todo&limit=10等QUERY参数未生效

**期待的正确结果**
3.返回数据完整，请求数据中 url和query拼接正常

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/38524981/114498901-94f36900-9c57-11eb-94bd-afd684edbcdb.png)

**Comment by xulinde2** [comment]
您用的哪个版本，我这里用1.8.2没复现
![Uploading image.png…]()

**Comment by qingqingdufu** [comment]
v1.8.0-21bf611d

**Comment by qingqingdufu** [comment]
![image](https://user-images.githubusercontent.com/38524981/114650511-f4fc1500-9d14-11eb-84e3-86fe254d5d82.png)

**Comment by xulinde2** [comment]
是的，跟您一样的测试场景

**Comment by qingqingdufu** [comment]
或许我可以录个屏，单独发给你，方便发一下你的邮箱吗？

**Comment by xulinde** [comment]
1.9.0已修复
