### ISSUE TITLE
[BUG]@natural(1000,9999)在接口调试中能够生成相应的随机数，在UI场景参数设置中不能生成相应的随机数

### ISSUE THREAD

**Issue by xiaozhao441** [metersphere/metersphere#20093]
### 联系方式

17805241933

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

@natural(1000,9999)在接口调试中能够生成相应的随机数，在UI场景参数设置中不能生成相应的随机数
![4ec526c7a6a87431af17860f11e14c5](https://user-images.githubusercontent.com/106516776/203538265-16714b35-0dd8-4072-a7ad-56b8d1016a0c.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/106516776/203538414-9b2c5167-8c90-4d49-85a6-beed89e8e55a.png)
![4ec526c7a6a87431af17860f11e14c5](https://user-images.githubusercontent.com/106516776/203538497-8c91330d-c730-4237-af97-b9466ba0da91.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们最新版本没有复现该问题，请详细描述下怎么使用这个场景变量，相关页面截图看看吧。

**Comment by xiaozhao441** [comment]
1、想要呈现的效果是输入内容中后四位是随机数
![image](https://user-images.githubusercontent.com/106516776/203892189-be17ea16-1aa9-4d25-b5c3-9e74afd9a2ed.png)
2、通过场景变量中的自定义变量来实现该效果，自定义变量值设置为@natural(1000,9999)
![image](https://user-images.githubusercontent.com/106516776/203892357-b6f7af9d-e882-4cf6-a027-04803ce004b7.png)
3、运行截图如下
![image](https://user-images.githubusercontent.com/106516776/203892663-afce5cea-0cad-4c4e-9aab-8aa4fb53d011.png)
4、自定义变量值为@natural时，运行截图如下
![image](https://user-images.githubusercontent.com/106516776/203892917-a89636ca-9c33-424e-a1a3-69c5e343cc97.png)

![image](https://user-images.githubusercontent.com/106516776/203892830-aca429fe-19c2-40db-b2e0-49a90bfe3e5e.png)

**Comment by xiaozhao441** [comment]
补充一下：通过${自定义变量名}来传参
![image](https://user-images.githubusercontent.com/106516776/203893770-cc90d31e-b295-46e3-b012-449c90bc817b.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
