### ISSUE TITLE
[BUG]性能测试设置完资源池中压力机的最大并发数，压测执行时，分配策略选固定节点、自定义策略 没限制住单个压力机的最大并发数

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#20103]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.16-lts & v2.3.1 

### 使用外置数据库

否

### 问题描述

性能测试设置完资源池中压力机的最大并发数，压测执行时，分配策略选固定节点没限制住最大并发数

### 重现步骤
一、固定节点  未限制 单个压力机最大并发数
1.资源池中设置压力机节点的最大并发数为100
![8b0c3e13a97a8b859000ce9e8ef46e9](https://user-images.githubusercontent.com/30038088/203545660-4cbb7831-f5ae-4710-b48b-5fe7e61a432d.png)
2.执行压测时，选择固定节点，200并发 仍然可正常执行。
![55586d656351306d17a2b7fb10ab274](https://user-images.githubusercontent.com/30038088/203545827-9509591f-c733-4034-bd09-18cdb1af57f2.png)

二、自定义策略 未限制最大并发数
1.资源池中设置压力机节点的最大并发数为100
![8b0c3e13a97a8b859000ce9e8ef46e9](https://user-images.githubusercontent.com/30038088/203545660-4cbb7831-f5ae-4710-b48b-5fe7e61a432d.png)
2.场景配置 200 并发， 自定义策略 设置为 0.3，0.7，即 ms-node-controller 分配60并发 ， 10.1.13.21 分配140 并发，实际 140 超过了 10.1.13.21  设置的最大并发数
![image](https://user-images.githubusercontent.com/30038088/203548593-e0010fc2-971c-45f7-83b4-6bf26274c72b.png)

### 期待的正确结果

分配策略 选择 固定节点、自定义策略 时，需限制 资源池中 设置的 压力机最大并发数。

**Comment by youliyuan-fit2cloud** [comment]
你好，资源池中的并发数限制的是接口测试。

**Comment by 2lipan** [comment]
自定义-有两个节点，最大并发数都为100，占比均为50%，按理说上面的并发数可以填到200的，但是不让输入200，会自动跳回100
![image](https://user-images.githubusercontent.com/104960608/209912566-29f2c97c-9e80-4e98-a9e7-4c311a071af4.png)
