### ISSUE TITLE
[BUG]性能测试，http请求，执行报错

### ISSUE THREAD

**Issue by tody0330** [metersphere/metersphere#2010]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.7.3 
**Bug 描述**
性能测试，http请求，执行报错

**Bug 重现步骤**
性能测试，上传jmeter脚本，创建的是http请求，错误结果日志中是tcp错误
执行结果日志中报错，提示错误见附件截图
![image](https://user-images.githubusercontent.com/53678289/114518401-e6105680-9c71-11eb-854c-46bd4cc7ba20.png)

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，建议升级到最新版试一下
