### ISSUE TITLE
[BUG]1.8.2版本性能测试执行时间到时脚本不能停止

### ISSUE THREAD

**Issue by JackWangSong** [metersphere/metersphere#2011]
**MeterSphere 版本**
1.8.2

**Bug 描述**
性能测试脚本执行时间5秒，启动脚本后  执行时间到一分钟没有停止脚本，导致执行超时

**Bug 重现步骤**
1.  压力配置并发数设置成200，按时间执行，时间设置5秒，RPS上限为2
2. 执行脚本，查看报告执行时间
3. 
4. 

**期待的正确结果**
按照时间正常停止

**截图**
如果有截图，请附上截图.
![微信图片_20210413204026](https://user-images.githubusercontent.com/45200987/114553760-909b7000-9c98-11eb-8a1a-7ebf3302dbd4.png)
[jmeter.log](https://github.com/metersphere/metersphere/files/6303755/jmeter.log)
[正式环境提交.pdf](https://github.com/metersphere/metersphere/files/6303758/default.pdf)

**Comment by wangzhen-fit2cloud** [comment]
@liuruibin 副老师看下这个吧

**Comment by dragonhaimax** [comment]
@JackWangSong  你好，我是原厂的技术人员想了解下你这个问题情况。最近会去你们旺旺总部交流jumpserver，方便加个联系方式么。V信和我github id保持一直
