### ISSUE TITLE
[FEATURE]测试用例的评审优化

### ISSUE THREAD

**Issue by pitter2007** [metersphere/metersphere#2012]
测试用例的评审,如果审核未通过,测试修改完毕后,平台无地方通知评审人再次评审.优化下评审流程

**Comment by xulinde2** [comment]
修改完，可以添加评论，触发消息通知
![image](https://user-images.githubusercontent.com/67534035/114649313-df85eb80-9d12-11eb-9292-98ff700168d5.png)

**Comment by guhan121** [comment]
@xulinde2 事件能用勾选方式么；每次只能选一个事件有点累
