### ISSUE TITLE
[BUG] 1.20.16, test plan执行完成，测试报告里有接口测试通过率数据，但是表test_plan_report_content的pass_rate字段值为空。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#20122]
### 联系方式

王进

### MeterSphere 版本

1.20.16

### 使用外置数据库

否

### 问题描述

1.20.16, test plan执行完成，测试报告里有接口测试通过率数据，但是表test_plan_report_content的pass_rate字段值为空。

### 重现步骤

1. 新装MS1.20.16，或者升级到MS1.20.16.
2. 执行包含接口用例或场景用例的测试计划
3. 执行完成，打开报告，执行率，通过率都有。
4. 按道理执行完成后会自动生成passrate等数据，或者 用户手动打开报告，也会触发相关数据生成。
5. 查看表test_plan_report_content的pass_rate字段，里面是空的。客户这边 之前 一直 在这张表查数据，现在发现升级到1.20.16后，这个字段值 不管怎样，一直都会空。

### 附加信息

跟开发快速沟通了一下，有可能1.20.16优化中产生的bug，帮忙转给天阳。

**Comment by xulinde** [comment]
v1.20.17已修复～
