### ISSUE TITLE
[BUG]json格式参数参数化时无法实现传入int类型，传入后自动变成了string

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#20123]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v1.20.14-lts-83677fba

### 使用外置数据库

否

### 问题描述

1.请求体json中参数化后无法实现int类型传参。

### 重现步骤

1.beanshell设置int类型参数
![图片](https://user-images.githubusercontent.com/23067502/203685527-d766beb2-ce11-4ead-a4d4-d0e11de544b3.png)

2.请求体json中进行引用
![图片](https://user-images.githubusercontent.com/23067502/203683303-96c7a336-bf0f-4939-9062-e43c2d652688.png)

### 期待的正确结果

请求体json格式可以实现int类型数据参数化

**Comment by youliyuan-fit2cloud** [comment]
你好，和Jmeter结果一样,需要用脚本处理一下，参考如下链接：https://www.jianshu.com/p/c5dfe5ecee0b
