### ISSUE TITLE
[BUG]接口测试-case-编辑某个接口-查看执行历史不包含测试计划定时任务的执行情况

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20126]
### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

接口测试-case-编辑某个接口-查看执行历史不包含测试计划定时任务的执行情况

### 重现步骤

1、使用测试跟踪-测试计划执行接口caseA

2、进入到接口测试-case-编辑case A 查看执行历史          不包含测试计划定时任务的执行情况

### 期待的正确结果

弹出的这个caseA的执行情况应该包含所有被引用的执行情况

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划的执行结果不会同步到接口测试模块的接口CASE结果中。
