### ISSUE TITLE
[FEATURE]接口test之后如果忘记另存为，之前调试过的内容就会消失；希望test可以保留最近一次调试结果并进行回显

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#20124]
### MeterSphere 版本

 v1.20.14-lts-83677fba

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/203685889-81535690-253e-45ee-adeb-b2d230a57a07.png)
接口test之后如果忘记另存为，之前调试过的内容就会消失。

### 请描述你建议的实现方案

希望test可以保留最近一次调试结果并进行回显。

**Comment by luty2018** [comment]
感谢建议， 这个可以加。
