### ISSUE TITLE
[QUESTION]能否支持接口定义评审功能

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#20145]
### 请描述您的问题

公司内部想将当前的MS平台作为测试团队与开发团队主要工作的平台，为了确保开发人员定义的接口正确，同时确保接口测试用例使用的接口完整无误，能否在接口测试模块参考测试跟踪模块中的用例评审，实现接口定义评审的功能。

**Comment by luty2018** [comment]
在我们2023年的规划中，请留意后续版本规划。
目前其他公司是用api文档来进行评审，可以暂时先这么用。
