### ISSUE TITLE
[BUG]复制场景用例场景用例的创建人不会发生变化

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2014]
**MeterSphere 版本**
1.8.2

**Bug 描述**
复制场景用例场景用例的创建人不会发生变化

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
复制场景用例场景用例的创建人应该改为复制者

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，后续版本会优化这个问题的

**Comment by zyyfit** [comment]
最新版已修复
