### ISSUE TITLE
[QUESTION]测试用例状态能否独立出来，不与测试用例执行状态混淆？

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#20148]
### 请描述您的问题

当前MS平台中的测试用例状态包含未开始、执行中、已完成三种状态，这个状态应该是用例关联到测试计划后的用例执行计划，并非用例本身的状态，能否将该用例状态与用例执行状态剥离开来，
即用例状态包含：在用状态、作废状态以及已删除状态，其中前两者页面显示，已删除状态后台展示即可；
而用例在测试计划中的执行状态为：当前的未使用、进行中、已通过、失败、堵塞等。

**Comment by luty2018** [comment]
用例的状态指用例是否设计完成的状态，你说的测试计划的执行状态是要参考用例表的执行结果
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/36292514/203729326-72ba7d9f-8dc2-41a6-917e-b4298e34f837.png">

**Comment by xueqidove** [comment]
> 用例的状态指用例是否设计完成的状态，你说的测试计划的执行状态是要参考用例表的执行结果 <img alt="image" width="1171" src="https://user-images.githubusercontent.com/36292514/203729326-72ba7d9f-8dc2-41a6-917e-b4298e34f837.png">

非常感谢，理解了
