### ISSUE TITLE
[FEATURE]基于项目维度支持项目管理员或者其他管理员角色定义系统各清单页面中字段的默认展示内容以及展示顺序等

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#20153]
### MeterSphere 版本

v2.2.1-68ccaa2a

### 请描述您的需求或者改进建议

参考TAPD的项目，能够支持某级别的管理员自定义该项目中各个列表页面或者详情页面的默认字段展示内容以及展示顺序，可参见TAPD中的项目配置页面：
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/60059766/203705759-2d4d9441-8a4a-4360-bf43-6319734e79ff.png">

设置图：
![image](https://user-images.githubusercontent.com/60059766/203710075-7eb90f4f-8b99-4465-9812-373bba7f62cc.png)

**Comment by luty2018** [comment]
目前我们用例以及缺陷模板也支持了自定义段配置以及默认值设置，不知道具体是指那一块的功能缺失呢？

**Comment by xueqidove** [comment]
> 目前我们用例以及缺陷模板也支持了自定义段配置以及默认值设置，不知道具体是指那一块的功能缺失呢？

比如定义api接口的页面，默认展示的字段等，而不要系统默认就展示参数名、类型、值等字段。
![image](https://user-images.githubusercontent.com/60059766/203929708-7928dc4b-0dcf-4c0f-8528-78346fce73b6.png)

**Comment by luty2018** [comment]
api这里已经优化了， 下个版本会支持用户来选择要展示哪些字段
