### ISSUE TITLE
[FEATURE]测试计划手动执行问题

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2015]
**请描述您的需求或者改进建议.**
1. “规划&执行按钮”分开；规划就感觉是给计划增加场景；执行就是执行该计划；如果是里面有场景用例点了执行应该就执行了；实际上点“规划&执行”并没有触发手动执行
2. 我给计划添加的都是场景用例；却找不到一次性手动执行所有场景用例的方式。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
收到，我们先讨论下再反馈
