### ISSUE TITLE
[FEATURE]计划中关联测试用例时，添加支持多个不同模块用例选择

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#20152]
### MeterSphere 版本

2.4.0

### 请描述您的需求或者改进建议

MeterSphere 版本
2.4.0

请描述您的需求或者改进建议
计划中关联测试用例时，添加支持多个不同模块用例选择；

请描述你建议的实现方案
选择关联测试用例时，左侧支持通过复选框选择多个模块的用例，如附加信息的图所示；

附加信息
![image](https://user-images.githubusercontent.com/6109912/188817319-5e32a602-4596-46a8-a596-f86311e9be19.png)

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/6109912/203705541-860d26a2-c4f0-42e3-b5e4-491d33ed0d8d.png)

**Comment by luty2018** [comment]
这个已经规划了， 大概会在v2.7上线。
