### ISSUE TITLE
[FEATURE]用例评审过程中如有审批未通过需修订后重新评审的用例无法识别

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#20151]
### MeterSphere 版本

v2.2.1-68ccaa2a

### 请描述您的需求或者改进建议

当前用例评审状态主要有通过、未评审、未通过三种状态，我们的使用场景时用例虽然未通过，但是希望能够修改用例后重新进行评审，当前这种状态无法在平台中记录识别，能否将其按照如下调整

1. 用例评审状态：
- 未评审状态（默认状态）
- 未通过（待修订）状态
- 修订未评审状态
- 通过状态
2. 用例评审流程：
- [1]发起评审，状态为默认未评审
- [2]评审人评审：
        状态为未通过（未通过是否可以直接选择将该用例作废？）
        状态为通过
- [3]用例修订人：修订用例，更新用例评审状态为修订未评审；
- [4]评审人评审：
        状态为未通过（未通过是否可以直接选择将该用例作废？）
        状态为通过
- [5] 上述2、3、4循环执行即可知道用例审批通过或作废。

**Comment by luty2018** [comment]
感谢建议， 这块我们确实还没有， 预计在v2.7版本会对评审结果这块进行初步改造， 可以先扩展出这几个状态。
