### ISSUE TITLE
[FEATURE]环境域名配置无法满足当前需求

### ISSUE THREAD

**Issue by qingqingdufu** [metersphere/metersphere#2016]
**请描述您的需求或者改进建议.**

【背景】我们使用的平台架构比较复杂，因此同一个项目内 接口的域名/ip、端口有很多不一致的，例如：
regis_url:     http://10.175.1.13:41450/usercenter/register
login_url:     http://10.175.1.13:21268/login
jenkins_url:  http://10.175.1.16:21988/usercenter
gitlab_url:    http://10.175.1.10:8087
base_url:      http://10.175.1.13:41450/devops    --大部分

【尝试解决途径】：
          在【通用配置】中增加regis_url、login_url、jenkins_url、gitlab_url变量,值为上述url前缀部分，【HTTP配置】base_url
【遇到问题】：
          接口url禁止 ${jenkins_url}/jobs 格式，强制要求 /api/v1/jobs 。新增的用例只能选择环境，不能编辑url。选择环境后，自动与环境域名base_url拼接，接口请求地址错误。

**请描述你建议的实现方案**
仅限于HTTP请求
1、测试用例允许编辑接口url，在url添加前缀变量；
2、当url中 含http或https时，不进行 环境域名+url自动拼接，使得请求地址可自定义配置；
      当url中不含http或https，符合格式/api/v1/jobs时，与环境域名拼接，实现默认拼接。

**Comment by xulinde** [comment]
感谢反馈，我们先讨论下再给反馈

**Comment by zhoubihui** [comment]
同有这个需求，现在是直接和环境域名拼接了
