### ISSUE TITLE
[BUG]请求体 body在json-schema from表单模式下，请求实际发出body非报文实例

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#2017]
**MeterSphere 版本**
1.8.2版本

**Bug 描述**
[
    {
        "cartId": "购物车id",
        "count": 0
    }
]
请求体这样的body在json-schema from表单模式下，请求实际发出body为JsonObject，详细请看图片 

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截![1_20210414134815](https://user-images.githubusercontent.com/82088551/114660661-45c93900-9d28-11eb-8e2e-fcffea81a78a.png)**
如果有截图，请附上截图
![2_20210414134828](https://user-images.githubusercontent.com/82088551/114660666-482b9300-9d28-11eb-83c7-753ac7c0840e.png)
![3_20210414134923](https://user-images.githubusercontent.com/82088551/114660668-48c42980-9d28-11eb-8695-6c5cd4e5ff36.png)

.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by yxz312** [comment]
这个应该是跟issues-2491是同一问题吧，都是时间json中都没有内容，虽然在json-schema中看到有内容

**Comment by zyyfit** [comment]
您好，1.9.0版本已修复了这个问题，现在最新版是1.10，请升级后试试
