### ISSUE TITLE
[BUG]dubbo请求一直没有返回

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#20178]
### 联系方式

juanmaocxy@163.com或者交流群42

### MeterSphere 版本

1.20.11

### 使用外置数据库

是

### 问题描述

1、录入dubbo接口测试，超时时间为3s
2、发送dubbo请求
3、界面一直在转圈，没有返回，超过一分钟停止请求
4、将metersphere服务重启即可又正常了，可以正常请求dubbo
5、如果不重启服务，过几分钟这个接口能看到有执行失败的结果，显示手动关闭请求，然后又能正常请求dubbo了

### 重现步骤

1、录入dubbo接口测试，超时时间为3s
2、发送dubbo请求
3、界面一直在转圈，没有返回，超过一分钟停止请求
4、将metersphere服务重启即可又正常了，可以正常请求dubbo
5、如果不重启服务，过几分钟这个接口能看到有执行失败的结果，显示手动关闭请求，然后又能正常请求dubbo了

### 期待的正确结果

dubbo正常返回，如果超时也在3s后返回结果

### 附加信息

![image](https://user-images.githubusercontent.com/58592452/203730380-9d116b20-ca95-4321-b36a-012cb62f8cc8.png)
过几分钟后返回如下图所示，成功的请求为5分钟之后重试返回的
![image](https://user-images.githubusercontent.com/58592452/203731161-4353ef11-dab7-405c-8b35-04a52390d4bb.png)

**Comment by xulinde** [comment]
未复现该问题，建议您升级到新版本1.20.16-lts再试下

**Comment by juanmaocxy** [comment]
> 未复现该问题，建议您升级到新版本1.20.16-lts再试下

这个不是必现的，是个偶现问题，不确定是否是由于自动化定时任务占有资源导致的或者某个异常进程导致的

**Comment by xulinde** [comment]
> > 未复现该问题，建议您升级到新版本1.20.16-lts再试下
> 
> 这个不是必现的，是个偶现问题，不确定是否是由于自动化定时任务占有资源导致的或者某个异常进程导致的

好的，如在遇到此问题，建议您看下后台是否有报错日志，前端是否有报错信息
