### ISSUE TITLE
[QUESTION]缺陷对接JIRA的时间跟踪字段无法同步

### ISSUE THREAD

**Issue by Ray-SR** [metersphere/metersphere#20198]
### 请描述您的问题

JIRA版本v8.13.2，有个字段名称是时间跟踪timetracking, 下面有2个子字段: 初始预估、剩余的估算, 传值的时候需要传一个类似{"remainingEstimate": "30d", "originalEstimate": "30d"}的对象, 这种应该如何处理呢？

**Comment by AgAngle** [comment]
我看了一下，这个参数格式有点特殊，目前还支持不了，后续会支持

**Comment by Ray-SR** [comment]
> 我看了一下，这个参数格式有点特殊，目前还支持不了，后续会支持

好吧，谢谢
