### ISSUE TITLE
[BUG]swagger导入成功，但是参数并没有导入进来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20197]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

swagger导入成功，但是参数并没有导入进来

### 重现步骤

swagger导入成功，但是很多接口的参数并没有导入进来
[otc.zip](https://github.com/metersphere/metersphere/files/10088069/otc.zip)

**Comment by youliyuan-fit2cloud** [comment]
你好，附件文件接口中parameters参数里缺少了必要参数 in 导致 swagger 无法识别参数是query参数还是path参数还是body参数，所以我们系统无法解析。建议修改文件后导入。
