### ISSUE TITLE
[QUESTION]关于复杂场景接口测试的支持

### ISSUE THREAD

**Issue by fuzecheng** [metersphere/metersphere#202]
**请描述您的问题.**

像jmeter中 一个sampler是包含前置后置处理器来处理复杂请求的，在这个开源工具中 同样能对这样的请求做支持吗。比如获取一个请求或者响应参数 并对这个参数进行对应加密 或者特定函数的处理，再放入下一个请求中等等

**Comment by wangzhen-fit2cloud** [comment]
你好，目前发布的 v1.1.1 版本中可以进行变量提取，提取后的变量可以用在后续的请求中。内置函数及前后置脚本的支持正在开发，计划在 8月底的 v1.2.0 中提供，其他更控制方式如条件判断、循环等还在规划中

**Comment by fuzecheng** [comment]
好的 如果有函数提取一类的功能 会比较赞，另外beanshell应该是在前置 后置 断言都可以支持到吧

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BugKing <notifications@github.com&gt;
发送时间: 2020年8月5日 15:45
收件人: metersphere/metersphere <metersphere@noreply.github.com&gt;
抄送: fuzecheng <405960648@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[metersphere/metersphere] [QUESTION]关于复杂场景接口测试的支持 (#202)





 
你好，目前发布的 v1.1.1 版本中可以进行变量提取，提取后的变量可以用在后续的请求中。内置函数及前后置脚本的支持正在开发，计划在 8月底的 v1.2.0 中提供，其他更控制方式如条件判断、循环等还在规划中

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
