### ISSUE TITLE
[BUG] 导出场景报告，格式为file，非pdf，手动改为.pdf后缀，可查看

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20205]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

导出场景报告，格式为file，非pdf，手动改为.pdf后缀，可查看

### 重现步骤

使用下面json文件导入场景
[Metersphere_Scenario_安全组件.zip](https://github.com/metersphere/metersphere/files/10088540/Metersphere_Scenario_.zip)
导入后执行场景，点击导出测试报告
![image](https://user-images.githubusercontent.com/103925124/203899770-fbc02451-19a9-4547-85e6-a77130bd24b5.png)
此时导出的文件无pdf后缀，需手动改为pdf后缀后可查看
![image](https://user-images.githubusercontent.com/103925124/203899829-5c040200-ad1b-42ce-b22a-c4a4d7ef415c.png)

**Comment by youliyuan-fit2cloud** [comment]
建议升级到v2.4.0。

**Comment by Ycr123888** [comment]
必现的哈，2.4版本也是必现的

**Comment by youliyuan-fit2cloud** [comment]
看起来是场景名字最后是数字导致的，临时改下场景名称吧。后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
