### ISSUE TITLE
[BUG]缺陷管理，按字段排序报错

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#20200]
### MeterSphere 版本

v2.3.0-f7d4cc4e

### 使用外置数据库

否

### 问题描述

缺陷管理列表点击字段排序报错：SQL error happened, please check logs.

### 重现步骤

1、禅道缺陷模板中新添字段：严重程度、处理人、状态
2、缺陷管理列表，按照新添字段（严重程度、处理人、状态）排序报错
【 SQL error happened, please check logs. 】

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/89765365/203893075-7629f1fb-3c33-476c-aaa9-ecc65f1fa824.png">

**Comment by hzhfit2cloud** [comment]
日志文件：

[test-track_error.log](https://github.com/metersphere/metersphere/files/10088601/test-track_error.log)

**Comment by xulinde** [comment]
v2.4.0已修复该问题，建议升级版本

**Comment by hzhfit2cloud** [comment]
感谢
