### ISSUE TITLE
[BUG]任务中心默认打开的接口测试默认不加载

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20209]
### MeterSphere 版本

v2.4

### 使用外置数据库

否

### 问题描述

任务中心默认打开的接口测试默认不加载

### 重现步骤

1、测试跟踪-测试计划
2、点击测试中心
3、接口测试tab默认无数据，需要切换场景或者性能tab再切回来才加载数据

### 期待的正确结果

正确加载数据（数据量大有性能问题）

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/203916497-4cf1e603-e857-4720-bc7d-0bbcc2321707.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，任务中心会实时更新各种用例的执行状态。

**Comment by legend818** [comment]
可以远程看一下

**Comment by youliyuan-fit2cloud** [comment]
你好，任务中心默认是10s中会刷新一次执行结果，请耐心等待一下。如果一直没有任务加载是问题，请再重新提个issue，感谢。

**Comment by legend818** [comment]
我的意思是 点任务中心 他其实没有发起请求，下面这三个tab他没有发起请求，切换tab 你就知道 这时候才发起请求

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/205427328-dd559a82-3daf-4f99-9c8c-d9cd337ef0cf.png)

**Comment by youliyuan-fit2cloud** [comment]
> 我的意思是 点任务中心 他其实没有发起请求，下面这三个tab他没有发起请求，切换tab 你就知道 这时候才发起请求

明白你的意思了，我们会优化一下。

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0版本中已优化。
