### ISSUE TITLE
[BUG]性能问题测试跟踪-测试计划-选择一计划手动执行性能很慢

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20206]
### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

升级到2.4版本，手动执行测试计划，性能很慢

### 重现步骤

1、测试跟踪 --测试计划
2、选择一计划（1500多接口+部分场景用例）
3、手动执行
4、弹出任务中心，列表页面刷白，性能问题见图

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/203904252-186beeea-fe92-4df7-b281-6bda40817b00.png)
做个容器内存优化
![image](https://user-images.githubusercontent.com/19423100/203904615-9d90966b-e6da-4c76-ba9b-f195a09db284.png)

**Comment by legend818** [comment]
你看还有5分钟报错的
![image](https://user-images.githubusercontent.com/19423100/203905177-a002e95f-7c86-45c0-a1b8-e587baad17f1.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/203905379-9a8a281d-604d-40dd-b011-4b271ba54cda.png)

**Comment by xulinde** [comment]
v2.5.1已优化，建议您升级下版本～
