### ISSUE TITLE
[BUG] 一台服务器上引用的场景case 导出之后， 导入到另一台服务器上，引用 就变成复制了。

### ISSUE THREAD

**Issue by chuwenyuan** [metersphere/metersphere#20202]
### 联系方式

530437008@qq.com

### MeterSphere 版本

v2.3.1

### 使用外置数据库

否

### 问题描述

1、服务器1上的场景（场景的内容是引用的其他场景），该机器上的所有case（包括被引用的源case）全部导出之后。
2、导入到新服务器2上， 查看引用的那些场景， 引用的场景都变成了复制。
![image](https://user-images.githubusercontent.com/110810583/203898535-d3d7dbb1-ecd6-4c0e-ac8f-06f42eac920f.png)
![image](https://user-images.githubusercontent.com/110810583/203898585-ac7e7a10-1607-49f1-8fa8-23458501fa01.png)

### 重现步骤

1、服务器1上的场景（场景的内容是引用的其他场景），该机器上的所有case全部导出之后。
2、导入到新服务器2上， 查看之前引用的那些场景， 引用的场景都变成了复制。

### 附加信息

![image](https://user-images.githubusercontent.com/110810583/203898545-b8cb8062-3c5c-45bb-854c-6a25dbc526c4.png)
![image](https://user-images.githubusercontent.com/110810583/203898593-87159af7-4185-41c5-9594-124b4589015a.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个是正常情况，因为导入的新环境2（新服务器）中并没有之前环境1中 场景里面引用的其他场景，会导致找不到原始场景或case，所以导入时把这些引用的场景和接口case做了处理，变为复制的。
