### ISSUE TITLE
[BUG]接口测试未执行统计准确性问题

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20217]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

我觉得与20216问题有关联性

接口测试首页的未执行接口统计不准确

### 重现步骤

1、接口测试-首页--查看接口用例未执行 57
2、点击57发现部分用例是接口自动化当中场景引用的
3、到接口自动化场景当中执行，执行成功
4、刷新接口测试-首页-还是57（是不是应该执行成功了，这个case要变更啊）

5、到测试跟踪--计划--执行计划中引用的场景，case还是未执行

### 期待的正确结果

我觉得在场景也好、测试计划当中也好，执行了引用了脚本，该脚本就应该变更，不然你首页统计的目的是干嘛，除非是为了在接口测试这个服务的独立统计

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/203921973-79d5e8ed-6b5d-4893-b336-c691d426bf1b.png)

**Comment by youliyuan-fit2cloud** [comment]
这个接口用例数量统计-未执行的统计结果就是接口定义-接口case列表中 未执行状态的case，和场景没有关系。
而且你还有RPC协议的接口吧，请再检查一下这里是否有未执行的case。
