### ISSUE TITLE
[BUG]主线版本测试计划中用例关联缺陷后，在测试计划外的功能用例和缺陷管理看不到两者关联关系。跟LTS版本不一致

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#20224]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

主线版本测试计划中用例管理缺陷后，在测试计划外的功能用例和缺陷管理看不到两者关联关系。跟LTS版本不一致,LTS版本在测试计划外，功能用例和缺陷依然存在关联关系。

### 重现步骤

1.创建测试计划，关联功能用例
2.在测试计划中将功能用例关联某个缺陷
<img width="947" alt="9eeff49e6666b9382be99ada7327c59" src="https://user-images.githubusercontent.com/88763608/203933162-16c99fb2-4940-4756-bf1e-496e4b90a620.png">

3.在测试计划外的功能用例或缺陷管理中，用例和缺陷没有关联关系
<img width="955" alt="6ec5738eae911b8aaafa3983eb24e40" src="https://user-images.githubusercontent.com/88763608/203933191-969e400f-db30-4c16-ad81-48409697d3e6.png">
<img width="922" alt="cc52c8e19d7bcf5c8e59488d31167d6" src="https://user-images.githubusercontent.com/88763608/203933212-44327ca0-9f28-4bb3-852a-c227300c05e7.png">

4.如果是LTS版本，在测试计划中将用例关联缺陷后，在测试计划外用例和缺陷依然存在关联关系
<img width="952" alt="afd78a8aeef200bed8ed37fd40d22d5" src="https://user-images.githubusercontent.com/88763608/203933234-658268d1-3e14-4850-8ec6-e766e3e514a4.png">
<img width="954" alt="cd06f3445facba2b781bded8ebc2497" src="https://user-images.githubusercontent.com/88763608/203933244-6a453626-580a-47f1-90c5-2036f0e10c7c.png">
<img width="950" alt="87f9ebe740fefa61d8e925af448eedd" src="https://user-images.githubusercontent.com/88763608/203933254-a9d3a283-96f0-4725-aa7a-8258703480bc.png">

### 期待的正确结果

跟LTS版本保持一致

**Comment by youliyuan-fit2cloud** [comment]
你好,v2.4.0版本问题，v2.3中正常。下个版本会修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
