### ISSUE TITLE
[BUG]  接口定义JSONSchema切换，无限添加"\" 转义符

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20228]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.4

### 使用外置数据库

否

### 问题描述

JSONSchema按钮切换，无限添加 "\” 转义符

https://user-images.githubusercontent.com/33945037/203937533-4c6036e9-210d-4f28-b3c9-031880afde23.mp4

![image](https://user-images.githubusercontent.com/33945037/203938138-78b58d41-6c4d-4748-9f7f-4e551fdc1ce7.png)

![image](https://user-images.githubusercontent.com/33945037/203938167-fbc58f61-b87a-4bf1-b94c-ca5c48c801bd.png)

![image](https://user-images.githubusercontent.com/33945037/203939050-b19b7912-5108-42a4-ae50-ae3933933bc6.png)

### 重现步骤

一直点击JSONSchema按钮切换 ，就会复现

**Comment by zyyfit** [comment]
您好，没有复现这个问题，建议您清一下浏览器缓存再试试
