### ISSUE TITLE
[BUG]UI测试 鼠标点击弹窗 鼠标拖拽操作页面能找到元素 且调试步骤也是成功的，但是页面无响应

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20225]
### MeterSphere 版本

2.2.1

### 使用外置数据库

否

### 问题描述

UI测试 鼠标点击弹窗 鼠标拖拽操作页面能找到元素 且调试步骤也是成功的，但是页面无响应

### 重现步骤

如图：鼠标点击操作 用的css定位，能够找到元素，ui脚本调试也是通过的，但是页面截图无弹窗弹出来。 为内网环境可找我提供下环境
![第六步是点击服务器上传，成功了，但是没有弹出上传界面，截图不对](https://user-images.githubusercontent.com/43202800/203935702-4c21d21b-ef21-4f28-a574-d362a433afe0.png)

### 相关日志输出

```shell
相关info.log也拷贝了
```

### 附加信息

[info.log.txt](https://github.com/metersphere/metersphere/files/10089907/info.log.txt)

**Comment by xhy12** [comment]
![d2b5798acae45bd98b2a2e0370a969e](https://user-images.githubusercontent.com/43202800/203946872-179ec2e0-88a1-4a3a-b40a-e51de51aac2a.png)
页面调试，找css.click() 可以点击页面

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/203954211-f6b86f81-5226-4e99-8094-bc0fd50fc8e6.png)
鼠标拖拽步骤成功了但是页面截图无响应

**Comment by zyyfit** [comment]
您好，我看了一下脚本，发现脚本里的xpath跟页面上的xapth是不一样的，上面是我这次copy的xpath，下面是我从脚本里复制过来的xpath，您先处理一下改成正确的xpath吧
![image](https://user-images.githubusercontent.com/73461316/204182760-d353bcf0-63aa-46a7-a063-eec353e8b100.png)

**Comment by xhy12** [comment]
定位元素不准确问题
