### ISSUE TITLE
[FEATURE]为LDAP用户提供批量权限设置

### ISSUE THREAD

**Issue by greedygod** [metersphere/metersphere#2023]
目前可以通过excel模板一次性批量导入大量用户并赋权；

但对于实际集成了ldap的环境来说，不会考虑手动创建用户，但就只能手动一个个赋权了（默认LDAP初始化为无权限用户）

需求：
 - 针对ldap方式创建的用户，提供可配置默认赋予角色的功能；
 -  或者参考excel模板导入方式，提供导入模板数据来批量设置已有用户权限的功能

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by xulinde** [comment]
v1.12支持用户组和权限，您可以先把用户批量添加到用户组，然后再设置对应权限
