### ISSUE TITLE
[BUG]测试跟踪-测试计划结束日期不能正确写值

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20234]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划结束日期不能正确写值

### 重现步骤

1、测试跟踪-测试计划
2、执行一个计划里面只包含一个case
3、执行成功（通过任务中心验证-已截图）
4、结果
结束日期不能正确写值

### 期待的正确结果

正确写值

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/203943653-4d209c46-e577-4681-9cf1-bf228b773a57.png)

**Comment by zyyfit** [comment]
您好，请问测试计划的状态和进度分别是什么情况呢？是像这样进度 100%了，但是状态还在进行中吗？
![image](https://user-images.githubusercontent.com/73461316/204180381-c0baf64e-2032-4929-a101-97f0752daba0.png)

**Comment by legend818** [comment]
快一个小时了 有了，
![image](https://user-images.githubusercontent.com/19423100/204515290-24887e7d-f4c4-45c0-be62-728e141196d5.png)

**Comment by legend818** [comment]
发现问题了，就是一直没有截止时间，切换页面等等操作都不行，但是你点一下这个计划，点进行就行了，然后结束时间就是你点得时间

**Comment by zyyfit** [comment]
好的，那就是测试计划状态导致的

**Comment by legend818** [comment]
可以关闭了
