### ISSUE TITLE
[BUG]测试计划报告统计准确性问题

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20243]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

测试计划报告统计准确性问题

### 重现步骤

1、测试跟踪-测试计划
2、手动执行一个测试计划（数量比较多，包含接口和场景）
3、进到测试跟踪-报告
4、查看报告
5、统计未执行和失败数量有问题

### 期待的正确结果

正确统计

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/204066594-cd223e0c-f9d0-45c3-b7c9-f9484b81c237.png)

**Comment by xulinde** [comment]
v2.5.1已修复，建议您升级下版本～
