### ISSUE TITLE
[BUG]接口测试首页-未覆盖统计不准确 

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20240]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

[BUG]接口测试首页-未覆盖统计不准确 

### 重现步骤

1、接口测试首页-未覆盖显示2
3、点击2
3、弹出api界面只有1

### 期待的正确结果

正确统计

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/203956772-633c3dd5-2ba4-49fa-8965-9395ccd686e1.png)
![image](https://user-images.githubusercontent.com/19423100/203956976-57791ce5-d145-4847-9ad4-d2ed4a0d8a9c.png)

**Comment by song-tianyang** [comment]
您好，您项目下没有TCP/SQL/DUBBO等接口了吗？

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/204066413-792a279c-651f-454f-a2b2-e87637904836.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/204072029-b3269091-0464-4a3b-b60c-753730c898b2.png)

我怀疑是这个
![image](https://user-images.githubusercontent.com/19423100/204072002-7d3d2521-01d0-43f5-bbb2-d4b8e4a69e30.png)

![image](https://user-images.githubusercontent.com/19423100/204072020-c4514a29-9cc9-456d-a6fe-36e2db025cad.png)

**Comment by song-tianyang** [comment]
您好，目前只有dubbo属于rpc接口类型。以后可能会支持更多的rpc接口。 您将请求类型切换到dubbo应该能看到。  所以也许并不是统计不准确，另一个未覆盖的可能就是dubbo。

**Comment by legend818** [comment]
我的问题，你上面提醒得对 我没有注意到接口定义哪里可以切换查询

**Comment by youliyuan-fit2cloud** [comment]
> 我的问题，你上面提醒得对 我没有注意到接口定义哪里可以切换查询

你好，如果不是问题，问题先关掉了。
