### ISSUE TITLE
[BUG] 偶发在多个同学并发测试时;调试控制台日志会错乱

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2024]
**MeterSphere 版本**
1.8.2

**Bug 描述**
如题
A同学的调试控制台里面的日志包含B同学的日志

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题
