### ISSUE TITLE
[BUG]测试跟踪-报告页面查询报错

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20253]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

测试跟踪-报告页面查询报错

### 重现步骤

1、测试跟踪-打开报告页面
2、查询报错

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/204170627-a433d317-992b-4694-80a1-7143f4dda315.png)
![image](https://user-images.githubusercontent.com/19423100/204170699-e8745cd9-62fa-4ef7-917c-8590cba7a4eb.png)
![image](https://user-images.githubusercontent.com/19423100/204170725-eae25c90-c3be-466f-b47c-a9d75fd9efa5.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/204170782-d3f236aa-ecdb-457a-bd34-5500f22e43ae.png)

**Comment by youliyuan-fit2cloud** [comment]
已知问题，下个版本会优化该问题，请关注一下发布信息。
