### ISSUE TITLE
[BUG] 从postman导入接口定义时，api_module树生成异常

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#20252]
### MeterSphere 版本

V2.4.0

### 使用外置数据库

否

### 问题描述

1. module A/subpath1/subpath2已存在
2. 新建module B, 在B中导入新增接口/subpath1/subpath2/interface 
发现新导入的接口在接口目录树中没有被统计到，也没有显示。但是在首页统计的接口总数中被统计到了。

排查发现api_module表中为B/subpath1/subpath2新建module 树，但是新生成的subpath1/subpath2 module_id 的parent_id不是B module的id, 就是新导入用例生成的module没有挂载到跟节点下。api_module表中新生成的第二级module的parent_id在api_module表中不存在。
![1](https://user-images.githubusercontent.com/2188338/204135647-ef081552-e36f-40a7-8585-77d1f76a41b6.png)
![2](https://user-images.githubusercontent.com/2188338/204135650-08b18b6a-165d-4a9b-90d8-ce082fc29b65.png)
![3](https://user-images.githubusercontent.com/2188338/204135651-2d21c14e-c6e6-47d6-b016-851605246822.png)

### 重现步骤

1. 通过postman定义接口目录结构A/subpath1/subpath2，并在该目录下创建一批接口，然后导出为json文件，再导入到ms
2. 在postman中目录A/subpath1/subpath2下新增一批接口，然后导出为json文件，再次导入到ms

**Comment by youliyuan-fit2cloud** [comment]
你好，按照描述步骤没有复现该问题，接口定义页面的接口统计信息一直是这样的吗？
<img width="295" alt="image" src="https://user-images.githubusercontent.com/54612864/204425332-6c9888e0-4924-4a83-8430-84d2de10bb4e.png">

<img width="404" alt="image" src="https://user-images.githubusercontent.com/54612864/204425357-f9691246-9b17-4c3f-9052-46ae4f2d095a.png">
