### ISSUE TITLE
[BUG]接口定义swagger文件导入，解析失败

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20251]
### MeterSphere 版本

V2.4.0

### 使用外置数据库

否

### 问题描述

接口定义swagger文件导入，解析失败
1.接口定义中导入swagger文件，在2.2版本能正确解析，接口导入成功；
2.在2.4版本导入swagger文件，报错数据解析失败。

### 重现步骤

见问题描述(swagger文件已提供给由老师)

### 附加信息

![bc23f5da94fa74b9ec3414f16986d5a](https://user-images.githubusercontent.com/92150453/204093537-964808ed-3d59-4b32-a61d-8b0d55dd2db8.jpg)
![448b084edb3f63aece9bb6b894a1c1d](https://user-images.githubusercontent.com/92150453/204093543-935936a6-3101-4589-8e83-def651736b6a.jpg)
![90e3c0fafdee88f9591f95e33ccca31](https://user-images.githubusercontent.com/92150453/204093550-6c996928-f381-4f68-ac0b-8d4edfc7d1c2.jpg)
![ff4619ba926480ae9e020031e4b0c22](https://user-images.githubusercontent.com/92150453/204093554-aeeb34d6-fe66-467e-ad03-376bfa402e0d.jpg)
![93f3a678deba7e0ac41ae68df77ffa7](https://user-images.githubusercontent.com/92150453/204093559-3a298855-3cee-4d07-9ef8-8c704c40b33b.jpg)

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
