### ISSUE TITLE
[BUG]场景中，使用python 前置脚本中设置list类型变量时，设置失败了

### ISSUE THREAD

**Issue by wfx8989** [metersphere/metersphere#2025]
**MeterSphere 版本**

v1.8.1-13242356
**Bug 描述**

场景中，使用python 前置脚本中设置list类型变量时，设置失败了

rolename是str，能设置变量成功
role是list，设置变量失败了

**截图**
![截屏2021-04-14 下午6 07 00](https://user-images.githubusercontent.com/68637962/114697418-7ae98180-9d50-11eb-9860-c6034db04c00.png)

![截屏2021-04-14 下午6 09 09](https://user-images.githubusercontent.com/68637962/114697416-7ae98180-9d50-11eb-8677-eb7deb8d93ee.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
您好，请问这个问题还在吗？可以试一下vars.putObject
