### ISSUE TITLE
[BUG] 场景A中引用了接口用例，创建新的场景B，在B中复制导入场景A，在场景B中无法删除 复制导入的场景A里的引用步骤。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#20256]
### 联系方式

王进

### MeterSphere 版本

v.1.20.16, v2.x

### 使用外置数据库

否

### 问题描述

场景A中引用了接口用例，创建新的场景B，在B中复制导入场景A，在场景B中无法删除 复制导入的场景A里的引用步骤。

### 重现步骤

1. 新建场景A，引用几个接口用例，复制几个接口用例，保存
![1669603588655](https://user-images.githubusercontent.com/76033005/204180693-1d90369f-e6ab-4461-844c-106d2b7f5f87.png)

2. 新建场景B，复制导入场景A，保存，此时，在场景B里 尝试删除 场景A里的 部分被引用步骤，无法删除。
![1669603557887](https://user-images.githubusercontent.com/76033005/204180645-bd6bb770-01e5-4868-b552-a2799f3a7073.png)

**Comment by youliyuan-fit2cloud** [comment]
你这个场景中引用的case不支持删除。
