### ISSUE TITLE
[BUG]定时任务Cron表达式导致页面崩溃

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#20262]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v1.20.16-lts&v2.2.0

### 使用外置数据库

否

### 问题描述

Cron表达式：0 0/20 * * * ?
单独删除以上表达式中的数字2时，会导致页面崩溃

### 重现步骤

1、接口自动化定时任务设置
2、自动生成Cron表达式：0 0/20 * * * ?
3、手动删除表达式中的数字2

### 期待的正确结果

页面正常显示，不会崩溃

**Comment by heyuehua** [comment]
![image](https://user-images.githubusercontent.com/45786766/204206805-dec71823-883a-4a9d-b81e-08d97f088136.png)

**Comment by heyuehua** [comment]
![image](https://user-images.githubusercontent.com/45786766/204206911-655bcef6-c6c8-4875-bf96-7573a3836964.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.17-lts中已修复该问题。
