### ISSUE TITLE
[BUG]MeterSphere集成Azure Devops平台后，无法新增缺陷

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20266]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

ms集成Azure Devops平台后，点击新增缺陷，填写完相关信息后，点击保存，F12里看到报500错误，后台日志也报相应错误。
![1669618599551](https://user-images.githubusercontent.com/104960608/204213651-879072b2-3557-413f-97a3-7c9b526fc82a.jpg)

![80aa698d162eaea420a472000935f71](https://user-images.githubusercontent.com/104960608/204213683-d4632328-2bc4-4d95-b697-978bbb3618c5.png)

### 重现步骤

1.ms集成Azure Devops平台，点击测试连接，正常连接
![image](https://user-images.githubusercontent.com/104960608/204214008-b2a52d01-580a-4a94-89a4-b29bbe7ff226.png)

2.关联项目，填写AzureDevops项目ID和过滤ID后，点击确定
![image](https://user-images.githubusercontent.com/104960608/204214092-776edb58-9d41-44ec-ba40-d7f39253cd37.png)

3.测试跟踪-新增缺陷，填写缺陷内容后，点击保存，F12能抓到报错500信息
![1669618599551](https://user-images.githubusercontent.com/104960608/204214238-34508d74-1a5c-448d-af32-d11e7e806cf1.jpg)

4.查看后台日志报错信息如下
![80aa698d162eaea420a472000935f71](https://user-images.githubusercontent.com/104960608/204214416-a179397e-a664-47a7-b53f-09382a5be8b7.png)

**Comment by xulinde** [comment]
已知问题，下个版本会修复
