### ISSUE TITLE
[BUG]v2.4.0, 复制或引用指令，总是弹出 "测试指令 指令为空，导入失败"

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#20261]
### 联系方式

王进

### MeterSphere 版本

v2.4

### 使用外置数据库

否

### 问题描述

v2.4.0, 复制或引用指令，总是弹出 "测试指令 指令为空，导入失败"

### 重现步骤

1. 新建一个指令，保存
2. 新建一个UI自动化场景，引用或复制刚刚新建的指令。
3. 复制或引用失败，总是弹出 "测试指令 指令为空，导入失败"，此时，即使去维护指令入参，再重复步骤1,2,3，提示还是一样。

**Comment by youliyuan-fit2cloud** [comment]
无图无真相啊。
