### ISSUE TITLE
[FEATURE]接口自动化页面接口多了会太卡，建议优化

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#2027]
**请描述您的需求或者改进建议.**
接口自动化页面接口多了会太卡，建议优化
优化的流畅一点

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/80370956/114803092-6c8f7a00-9dd1-11eb-8d16-f37c23476054.png)

**Comment by xulinde** [comment]
步骤总共多少条

**Comment by Evan-guo131** [comment]
> 步骤总共多少条

大概50条左右开始，切换就有点卡了

**Comment by xulinde** [comment]
下个版本优化了这里，您到时候可以再体验下
