### ISSUE TITLE
[BUG]在MS平台已安装MQTT插件的情况下，上传包含MQTT取样器的JMX文件时，MQTT插件相关配置仍显示为原生xml，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20278]
### MeterSphere 版本

V2.2.1

### 使用外置数据库

否

### 问题描述

在MS平台已安装MQTT插件的情况下，上传包含MQTT取样器的JMX文件时，MQTT插件相关配置仍显示为原生xml，建议优化

### 重现步骤

见问题描述

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/204236497-b0e38d38-1eb8-4af4-a12c-fb153e090a46.png)
脚本文件：
[JMX与MS场景用例.zip](https://github.com/metersphere/metersphere/files/10102068/JMX.MS.zip)

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉长时间未反馈，该问题已在v2.5.0以上版本中优化了，建议升级一下吧。
