### ISSUE TITLE
[BUG]MS对接jira，勾选自动同步缺陷模板时，jira问题模板中的时间跟踪字段未能同步成功，需优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20276]
### MeterSphere 版本

V2.2.1

### 使用外置数据库

否

### 问题描述

MS对接jira，勾选自动同步缺陷模板时，jira问题模板中的时间跟踪字段未能同步成功，需优化

### 重现步骤

见问题描述

### 附加信息

![90a5d0de40c79944f35406cc7f17206](https://user-images.githubusercontent.com/92150453/204232384-55e83dec-c8c9-48b8-9d3c-9a0c8bb9fb4c.png)
![085cb6d393962ad3a44eb8ba66cc23c](https://user-images.githubusercontent.com/92150453/204232395-9f2907e6-fbad-4b11-bc89-4ecab6a038f7.png)

**Comment by gaohonghai** [comment]
@xulinde @youliyuan-fit2cloud  两位老师，这个问题咱们预计会在小版本进行修复吗，同样遇到了因为这个字段，报错的问题。
![image](https://user-images.githubusercontent.com/92966838/211998769-de8e1d2c-dfb1-4a31-ba93-ec8bfcfd7c29.png)
