### ISSUE TITLE
jenkins配置metersphere连接时系统异常（账号和地址都是正确的）

### ISSUE THREAD

**Issue by andy99999** [metersphere/metersphere#20289]
### 请描述您的问题

jenkins配置metersphere连接时系统异常

![image](https://user-images.githubusercontent.com/71812568/204420073-516bd690-81cd-4886-9d77-184aa04c4810.png)

**Comment by luty2018** [comment]
你现在是用的什么版本？如果是2.3以上的版本，Jenkins也需要同步下载最新版本。

**Comment by andy99999** [comment]
metersphere版本是v1.20.16-lts-b1，jenkins目前版本[Jenkins 2.361.3]

**Comment by luty2018** [comment]
> metersphere版本是v1.20.16-lts-b1，jenkins目前版本[Jenkins 2.361.3]

你要么升级MeterSphere到2.3以上版本， 要么降级Jenkins插件到1.20.17版本
