### ISSUE TITLE
[BUG]升级2.3版本用户无法登录

### ISSUE THREAD

**Issue by Yingqingshan** [metersphere/metersphere#20288]
### 联系方式

yingqing.shan@sayweee.com

### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

V2.2版本，用户可以正常标准或ldap类型用例登录
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/100674970/204418333-ce483d4b-734e-41eb-a8ec-5c40bebe6175.png">

升级2.3及以后版本使用ldap登录就会提示以下错误，只能通过local类型的用户登录
<img width="451" alt="image" src="https://user-images.githubusercontent.com/100674970/204418424-e9eab113-c6cc-442a-bfa6-9cf52dbf3a7a.png">

用户根本就不知道自己的用户类型，如何选择类型登录呢？是不是应该兼容ladp类型登录呢

### 重现步骤

新增用户，ID为员工工号，其他按截图数据输入

登录的时候改成ldap类型登录，不适用local类型

### 期待的正确结果

不需要区分用户类型，应该也可以ldap类型登录

**Comment by youliyuan-fit2cloud** [comment]
你好，通过api登录 v2.3以上版本需要新增一个参数，参考如下：
![image](https://user-images.githubusercontent.com/54612864/204458636-c63642ac-c97c-4802-bd1b-dff8d4a4ea05.png)

**Comment by Yingqingshan** [comment]
你没看到我的意思，这个接口并不是V2.3才有得；接口就是需要带authenticate的；
1、以前非ldap注册的用户，使用ldap登录是支持，你们只校验这个用户邮箱是否存在，存在+ldap账号验证通过就直接用存在的邮箱登录
2、而现在逻辑发生变化了，你不仅仅验证ldap邮箱是否校验通过，还验证这个邮箱、类型、ID和昵称等，这样我注册是local登录的，肯定就没办法用ladp登录了

**Comment by Yingqingshan** [comment]
你如果要复现，给你个SQL，你插入表里
```mysql
INSERT INTO `metersphere`.`user` (`id`, `name`, `email`, `password`, `status`, `create_time`, `update_time`, `language`, `last_workspace_id`, `phone`, `source`, `last_project_id`, `create_user`, `platform_info`, `selenium_server`) VALUES ('W0404', 'yingqing.shan', 'yingqing.shan@sayweee.com', 'b4d3492f93808003991c30eddb484795', '1', 1646023664666, 1669635341673, 'zh_CN', '936956e6-8abe-4302-8bb8-fbee3f3c031d', '15000220022', 'LOCAL', 'd15dcf0e-2def-4c91-af24-1a61ef014f6f', 'admin', NULL, '');
```

**Comment by liuruibin** [comment]
<img width="141" alt="image" src="https://user-images.githubusercontent.com/23045261/204476442-eb88deb2-459a-4045-b591-9d2f1103716c.png">
你的这个用户类型的LOCAL，登陆的时候也需要选中LOCAL，选择其他的无法登陆成功

**Comment by Yingqingshan** [comment]
之前不是LOCAL 都支持ldap登录嘛？我2.2的版本都是支持的

**Comment by youliyuan-fit2cloud** [comment]
> 之前不是LOCAL 都支持ldap登录嘛？我2.2的版本都是支持的

你好，我们2.3以上版本做了优化，其实不是local也能登录是有缺陷的。

**Comment by Yingqingshan** [comment]
关键是local 只能选普通账号，ldap只能选择ldap登录，员工如何支持自己是ldap还是local类型呢？这个登录会存在很多不合理的缺陷，我们公司基本都是ldap登录，而且有部分用户类型local类型，选择ldap就只能保持，说账号存在或不唯一。

**Comment by youliyuan-fit2cloud** [comment]
> 关键是local 只能选普通账号，ldap只能选择ldap登录，员工如何支持自己是ldap还是local类型呢？这个登录会存在很多不合理的缺陷，我们公司基本都是ldap登录，而且有部分用户类型local类型，选择ldap就只能保持，说账号存在或不唯一。

理解了，我们又改回原始的方式了，这样可能更满足用户的需求。下周发布的v2.6.0中会更新该问题。
