### ISSUE TITLE
[BUG] ms 文档搜索有 bug，明明有缺搜索不到

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20298]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

帮助文档搜索特定字符串，搜索结果有问题

### 重现步骤

https://metersphere.io/docs/v2.x/

使用“环境”搜索，可以看到有“环境变量”字符串
![image](https://user-images.githubusercontent.com/4860962/204435347-19b4b60e-271d-43ee-b3f9-15365dda9518.png)

使用“环境变量”，提示没有结果
![image](https://user-images.githubusercontent.com/4860962/204435406-7b033f39-a3d5-4287-ab86-c370cc9e1b5a.png)

**Comment by youliyuan-fit2cloud** [comment]
@shenkaibo 请帮忙处理下一下文档的问题吧。

**Comment by 2lipan** [comment]
缺陷已修复，可正常查询内容。
![image](https://user-images.githubusercontent.com/104960608/205006304-91bae3a7-6973-470c-ad6d-9d6b92fd65a7.png)

![image](https://user-images.githubusercontent.com/104960608/205006337-e14943d6-c071-4bee-81c2-dc9312aebfa9.png)

**Comment by hao1032** [comment]
验证可以了
