### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by MIAOZHIYANG** [metersphere/metersphere#20297]
### MeterSphere 版本

v1.20.14-lts-83677fba

### 联系方式

交流群50-programer code 2575909565@qq.com

### 请描述您的需求或者改进建议

Gitlab CI/CD集成MS自动化测试，执行测试计划无法触发钉钉机器人通知，根据MS相关工作人员的提示，MS系统设置Jenkins任务通知，还是没有触发钉钉机器人通知。工作人员说gitlab走的不是jenkins插件没有适配信息。

**Comment by luty2018** [comment]
Jenkins任务通知是针对Jenkins插件触发的事件进行通知， 和gitlab没有关系的。 如果你gitlab配置的是单独的场景就配置场景的通知， 是测试计划就配置测试计划的通知。
