### ISSUE TITLE
[BUG]UI测试定位不到元素

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#20296]
### 联系方式

张树彬

### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

UI测试定位不到元素（客户的系统，可以找我要账号验证）

### 重现步骤

1. 登录被测系统
2. 无法定位到首页输入框元素

### 期待的正确结果

可以正确定位到系统元素

**Comment by youliyuan-fit2cloud** [comment]
已修复，建议升级到最新v2.5.1 版本。
