### ISSUE TITLE
[BUG]升级2.4.0后，运行接口用例时，api-test容器经常会自动重启

### ISSUE THREAD

**Issue by spheretangmeng** [metersphere/metersphere#20306]
### 联系方式

微信：zuanshixiu668 “MeterSphere北方区交流群”

### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

执行单个接口的用例，api-test容器就自动重启

### 重现步骤

执行单个接口的用例，api-test容器就自动重启

**Comment by spheretangmeng** [comment]
试过，一旦修改了，容器就会卡在staring状态

**Comment by youliyuan-fit2cloud** [comment]
> 试过，一旦修改了，容器就会卡在staring状态

服务器内存多少？是不是不够用了。。。

**Comment by spheretangmeng** [comment]
16G

**Comment by youliyuan-fit2cloud** [comment]
额...
1.修改后的文件方便截图看看；
2.starting 状态的容器日志截图看看。

**Comment by spheretangmeng** [comment]
[image] [image] 上午试的时候总是起不来，这会重新试了一下，看起来是正常了，但我执行接口脚本的时候，又自动重启了 [image] python脚本是执行成功了的，不过得多试几次，

**Comment by youliyuan-fit2cloud** [comment]
> [image] [image] 上午试的时候总是起不来，这会重新试了一下，看起来是正常了，但我执行接口脚本的时候，又自动重启了 [image] python脚本是执行成功了的，不过得多试几次，

图片看不了。

**Comment by spheretangmeng** [comment]
好像还是看不了图片，要不你加我微信吧

**Comment by youliyuan-fit2cloud** [comment]
> 好像还是看不了图片，要不你加我微信吧

<img width="612" alt="image" src="https://user-images.githubusercontent.com/54612864/204509474-1c242545-7e6c-4b1e-a907-d01fb3cc1c3a.png">
我的企业微信二维码
