### ISSUE TITLE
[BUG]ui测试：chrome 浏览器支持打开弹框应用

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20303]
### MeterSphere 版本

2.2

### 使用外置数据库

否

### 问题描述

UI测试 无法打开应用弹窗，和大老师讨论后有绕过方法提出chrome 浏览器支持打开弹框应用之类的，

### 重现步骤

系统应用弹窗，通过ui测试的弹窗无法操作

![9bc405a5a50ef825a5543be5f5c56b4](https://user-images.githubusercontent.com/43202800/204449923-dedb3c1a-07c4-4126-ac20-ddfa65e6d38f.png)
![aed796c478a4e89d5890e63fc20271a](https://user-images.githubusercontent.com/43202800/204449935-3601f2ab-5814-4ac3-8f7f-099d2f199d01.png)

**Comment by Hyyfit** [comment]
暂不支持。
