### ISSUE TITLE
[BUG]  jenkins Job执行接口自动化场景出现一直running的现象。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20307]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

v1.20.16-lts

在jenkins上安装了对应的 [metersphere-jenkins-plugin-v1.20.16-lts.hpi](https://github.com/metersphere/jenkins-plugin/releases/download/v1.20.16-lts/metersphere-jenkins-plugin-v1.20.16-lts.hpi)  安装包，创建流水线，执行MS的接口自动化，一直出于running状态。

![image](https://user-images.githubusercontent.com/33945037/204453274-0560940d-35eb-469b-bb59-112d75d1f9cc.png)

![image](https://user-images.githubusercontent.com/33945037/204453307-805bd8c8-c486-4205-a5f6-f9c657d622b2.png)
![image](https://user-images.githubusercontent.com/33945037/204453357-24ddfa0c-2cf9-4fab-8dd4-6aff2fc21531.png)

![image](https://user-images.githubusercontent.com/33945037/204453404-4e57b562-a551-4e43-b9a6-472fe2488b1a.png)

### 重现步骤

1. jenkins插件准备好
2. 创建一个接口自动化
3. 在jenkins上创建job并且配置。
4. 执行job

### 期待的正确结果

应该正确执行

**Comment by youliyuan-fit2cloud** [comment]
你好，这个场景用例在MS系统中调试是否正常？主要看下场景有没有选中运行环境。

**Comment by hao65103940** [comment]
![image](https://user-images.githubusercontent.com/33945037/204983031-01eaef64-a46e-40ef-b032-b5a828e02701.png)
在MS中是正常的，场景中已经保存了环境，这个你应该是可以复现的

**Comment by huajingtong** [comment]
请问是否已解决，我也遇到此问题了，一直running 
https://github.com/metersphere/metersphere/issues/20433

**Comment by hao65103940** [comment]
> 请你把jenkins最后执行结果的截图发出来吧。还有资源池选中的是什么？

jenkins一直就是Running状态，一直在跑，除非手动关闭。
![image](https://user-images.githubusercontent.com/33945037/205537971-12ad08e4-b932-4ba1-9924-5b7d0e97224a.png)

资源池配置如下：

![image](https://user-images.githubusercontent.com/33945037/205538228-3ca56dcb-2976-439a-88ce-fc94dbf7e1df.png)

![image](https://user-images.githubusercontent.com/33945037/205538228-3ca56dcb-2976-439a-88ce-fc94dbf7e1df.png)

**Comment by huajingtong** [comment]
> 有资源池选中的是什么
jenkins的资源池

<img width="962" alt="image" src="https://user-images.githubusercontent.com/30971576/205538927-aeee9ea8-72c6-4694-99d8-db288657879c.png">

metersphere资源池也是本地
![image](https://user-images.githubusercontent.com/30971576/205539219-282518ef-9845-4f91-b65c-9104e4d3c246.png)

**Comment by youliyuan-fit2cloud** [comment]
后台 info.log 和jmeter log 日志看看？ 
可能是测试资源池的镜像和版本。
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/54612864/205555998-56ae21b3-421e-4461-b912-5c649c2c379f.png">

我们最新版本的1.20.17-lts没有复现,建议升级到最新版本试试吧。

**Comment by huajingtong** [comment]
请问升级1.20.17-lts之后 ，会不会影响历史的功能（之前倒入的功能用例以及创建的api接口、case场景、接口自动化那些功能会不会兼容，不会影响使用吧）
因为之前v1.20.11-lts 我们测试组已经使用过一段时间了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]  jenkins Job执行接口自动化场景出现一直running的现象。 (Issue #20307)





 
后台 info.log 和jmeter log 日志看看？
 可能是测试资源池的镜像和版本。
 
 
我们最新版本的1.20.17-lts没有复现,建议升级到最新版本试试吧。

**Comment by maninhill** [comment]
不会影响历史功能和数据。但是仍然建议你升级前先备份下。

**Comment by huajingtong** [comment]
是看这里面的日志吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 中午1:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]  jenkins Job执行接口自动化场景出现一直running的现象。 (Issue #20307)





 
不会影响历史功能和数据。但是仍然建议你升级前先备份下。

**Comment by youliyuan-fit2cloud** [comment]
> 是看这里面的日志吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2022年12月5日(星期一) 中午1:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG] jenkins Job执行接口自动化场景出现一直running的现象。 (Issue #20307) 不会影响历史功能和数据。但是仍然建议你升级前先备份下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

<img width="922" alt="image" src="https://user-images.githubusercontent.com/54612864/205559679-63cfc739-1d8e-4290-b612-1290daa0b45c.png">

/opt/metersphere/logs/metersphere目录下面的info和jmeter日志。

**Comment by hao65103940** [comment]
新版本，已解决。
