### ISSUE TITLE
[BUG]API更新的邮件消息通知，在添加更新时间变量时，变量值未生效

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20315]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

API更新的邮件消息通知，在添加更新时间变量时，变量值未生效

### 重现步骤

见问题描述

### 附加信息
![80db59d25776ae1298d56e1e82c21f0](https://user-images.githubusercontent.com/92150453/204459802-f294481a-a663-4553-b3c1-ada5acdd22e6.png)

**Comment by youliyuan-fit2cloud** [comment]
最新版本没有复现，升级一下吧。

**Comment by sageonedream** [comment]
经确认，V2.4版本已无此问题
![image](https://user-images.githubusercontent.com/92150453/204748849-55337a88-df06-471d-942d-4482284644db.png)
