### ISSUE TITLE
[BUG]API更新的邮箱消息通知，在API未变更，只点击保存时，仍会发送消息通知，功能实现有误，建议优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20316]
### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

API更新的邮箱消息通知，在API未变更，只点击保存时，仍会发送消息通知，功能实现有误，建议优化

### 重现步骤

见问题描述

### 附加信息

![39c7c02c0aea6f6ce9bd882643b30a3](https://user-images.githubusercontent.com/92150453/204459994-d6d42dab-2135-459e-8de4-713d592635f9.png)
![e7164826bf2b14e449a3e7822aa9c4e](https://user-images.githubusercontent.com/92150453/204460003-ee5fe491-099b-466c-9d7d-50f64b0f98cf.png)

**Comment by youliyuan-fit2cloud** [comment]
我们最后沟通后，认为页面点击编辑就认为是更新了，不去校验属性是否变更。如果每个接口/用例/计划等等的属性验证的话，后台是非常大的工作量，所以暂时不会变更。
