### ISSUE TITLE
[BUG]【接口测试】-jmeter脚本导入-接口不能执行

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#20310]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

是

### 问题描述

将jmeter脚本导入到metersphere中，接口无法执行

### 重现步骤

1.进入接口定义页面，导入jmeter脚本
2.调式导入的接口

### 期待的正确结果

导入脚本能正常执行

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/204457318-3b2bddbf-bcec-4cd8-8ca4-976590071ec0.png)
[Metersphere_Api_supOS-通用业务.zip](https://github.com/metersphere/metersphere/files/10110395/Metersphere_Api_supOS-.zip)

**Comment by fit2-zhao** [comment]
这个缺陷已经修复过，已经产生的脏数据用以下SQL处理下：

update api_definition set request = JSON_SET(request, '$.enable', true)  where request->'$.enable' = false;
update api_test_case set request = JSON_SET(request, '$.enable', true)  where request->'$.enable' = false;
