### ISSUE TITLE
[BUG]接口自动化执行选择环境，当环境数量多时，场景中嵌套场景，响应时间过慢的问题

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#20337]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

一个项目当配置有10个环境时
![a93c5a358c89c9101b356b3e2a13522](https://user-images.githubusercontent.com/83771182/204511866-aad986e6-bf34-4b75-a65b-d804ffe9f0cf.png)
接口自动化选择环境时，响应时间达到1.1分钟
![1e282fc5c5fab25126241bb5f5ea183](https://user-images.githubusercontent.com/83771182/204512076-62f49a5e-3d2d-40a8-ad77-defe827e3ea0.png)
但另一个项目配置了29个环境 
接口自动化选择环境时，响应时间只有9.3秒。
![044c7b46677a9e8fff5733736276261](https://user-images.githubusercontent.com/83771182/204512234-c2543194-166b-404f-9715-89835a67fddb.png)

以上两个测试场景的区别是，第一个场景里面有子场景，子场景里面还有一个子场景。而第二个场景比较简单没有子场景。下面截图为第一个场景
![3aa4ce59d226df5b3e157ee04235451](https://user-images.githubusercontent.com/83771182/204512557-3e38c574-cf19-4e04-bae2-3126d2acff8c.png)

### 重现步骤

一个项目当配置有多个环境时，选择环境

### 期待的正确结果

响应时间正常

### 相关日志输出

```shell
测试脚本见附件
```

### 附加信息

[Uploading 资料.zip…]()

**Comment by yaoyi111** [comment]
[资料.zip](https://github.com/metersphere/metersphere/files/10112743/default.zip)

**Comment by xulinde** [comment]
导入你的场景和环境，选择环境，响应时间14s+， 没有几分钟
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/64065190/204740744-e2b05fd8-e589-49ba-9ebb-c87333d97b21.png">

**Comment by yaoyi111** [comment]
![微信图片_20221201210355](https://user-images.githubusercontent.com/83771182/205059811-d24711ac-3cd8-451c-8684-88fbd3d15dd2.jpg)
