### ISSUE TITLE
[FEATURE] 用例搜索希望支持详情搜索

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20347]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

想要找某个用例，但是用例名称不记得了，知道的是详情里面有某个关键字，希望支持详情搜索。
![image](https://user-images.githubusercontent.com/4860962/204699015-3ba5d2c9-5353-40fa-824b-5b793c4957a9.png)

**Comment by luty2018** [comment]
目前我们底层的存储还不太支持。

**Comment by hao1032** [comment]
你们明年不是要重构脑图吗？ 搜索不加上吗？

LuoTing ***@***.***> 于2022年12月6日周二 10:49写道：

**Comment by hao1032** [comment]
这个应该是基础功能了，可以考虑加上吗？

**Comment by luty2018** [comment]
可以， 我们有计划做全局搜索，到时候可以一并加这个功能
