### ISSUE TITLE
[FEATURE] 脑图不能只展开 执行失败/未执行 的用例

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20349]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

1. 测试计划执行后，因为某些原因有些用例没有执行，有些用例执行失败。
2. 第二天继续执行时，需要过滤出 未执行/执行失败 的用例，继续测试。

**Comment by luty2018** [comment]
这个功能在我们规划的v2.27版本中
