### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#20342]
### MeterSphere 版本

2.4.0

### 联系方式

13735892260

### 请描述您的需求或者改进建议

meteresphere 首页，左侧的菜单自动伸缩性时候，给人一种一闪一闪的感觉，固定在那里又感觉浪费空间，建议设计成类似禅道的模式。

**Comment by luty2018** [comment]
麻烦提供一下截图看看

**Comment by hztony** [comment]
这个是交互，你可以试试光标去那个区域来回动几下
