### ISSUE TITLE
[BUG]接口测试首页-未覆盖链接无法根据协议类型准确筛选并显示，很容易造成误解

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#20341]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

接口测试首页，鼠标点击未覆盖数量，进行跳转链接，但无法根据协议类型准确筛选并显示，很容易造成误解。

### 重现步骤

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/46042812/204689962-579d9e51-f073-4dab-b0b3-bb2ee532a5aa.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/46042812/204690101-d3293311-d041-47b2-b6b1-4ea1986d2899.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，计划在v2.9.0中做优化，请关注发布信息～

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
