### ISSUE TITLE
[BUG] 通过脑图执行用例，步骤不能设置结果

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20348]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

列表中执行用例可以设置步骤结果，脑图不行。

### 重现步骤

列表中执行用例，步骤可以设置结果
![image](https://user-images.githubusercontent.com/4860962/204699682-20159f34-6167-419f-bc0e-1b545d4cb13e.png)

脑图中执行，无法设置
![image](https://user-images.githubusercontent.com/4860962/204699800-7c317f02-026d-49c3-90c6-e1ff66548878.png)

**Comment by xulinde** [comment]
您好，明年Q2会对脑图进行重构
