### ISSUE TITLE
[BUG]  功能用例--》功能列表批量编辑，编辑责任人，第一次不能选择值。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20352]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

  v2.2.1

### 使用外置数据库

否

### 问题描述

第一次加载不出来
<img width="740" alt="image" src="https://user-images.githubusercontent.com/33945037/204698999-8b612c27-c87a-4ccb-a45c-ca645d7138db.png">

关闭之后刷新之后就有了
<img width="857" alt="image" src="https://user-images.githubusercontent.com/33945037/204699069-6edeb60d-bf25-4239-851e-9e748f7c7f77.png">

### 重现步骤

第一次点开不行，关闭刷新之后

### 期待的正确结果

正常显示

**Comment by xulinde** [comment]
最新版本没有复现该问题，建议升级下版本

**Comment by hao65103940** [comment]
V2.4.1 已修复
