### ISSUE TITLE
[BUG]swagger导入，无法导入到特定的模块

### ISSUE THREAD

**Issue by chenlizhen959** [metersphere/metersphere#2035]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，能具体描述一下复现步骤吗？

**Comment by chenlizhen959** [comment]
1.手动创建一个模块
2.通过swagger导入
3.选定创建的模块
4.将导入到该模块
5.查看结果
在 2021年4月15日 +0800 PM6:46，zyyfit ***@***.***>，写道：

**Comment by xulinde** [comment]
1.9.2已修复
