### ISSUE TITLE
[FEATURE] 分页数量 希望可以选择一次，下次使用上次选择的

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20351]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

个人使用中觉得每页 10 个太少了，一般选择最多的 50 个，特别是测试计划关联用例的时候。
![image](https://user-images.githubusercontent.com/4860962/204700822-a4069479-7980-4431-be0e-7a5015e9b436.png)

### 请描述你建议的实现方案

1. 希望我选择 50 个后，下次我就不用选择了
2. ms 中多个地方都有分页，希望某个地方选择 50 后，其他的分页也能复用这个选择
3. 希望有大于 50 个的选择，比如 100 个，500 个？

**Comment by luty2018** [comment]
“希望有大于 50 个的选择，比如 100 个，500 个” 这个会有性能的问题。
“希望我选择 50 个后，下次我就不用选择了”-- 这个可以做。

**Comment by hao1032** [comment]
> “希望有大于 50 个的选择，比如 100 个，500 个” 这个会有性能的问题。 “希望我选择 50 个后，下次我就不用选择了”-- 这个可以做。

什么时候做啊？
