### ISSUE TITLE
[BUG]批量勾选一个场景里面的多个case，做批量删除，会把剩余case的后置脚本和断言清空

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20354]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

批量勾选一个场景里面的多个case，做批量删除，会把剩余case的后置脚本和断言清空

### 重现步骤

1.场景中接口列表导入多个case,含有后置脚本和断言
![image](https://user-images.githubusercontent.com/103627487/204703486-9ca79532-872f-4caa-8321-0213b6e2f94a.png)
2.批量删除case
![image](https://user-images.githubusercontent.com/103627487/204703581-8965780e-a04c-4a24-8f39-843b59adf199.png)
![image](https://user-images.githubusercontent.com/103627487/204703641-69c25392-452c-412b-b52a-9ad3fc1ced50.png)
3.剩余case的后置操作和断言清空
![image](https://user-images.githubusercontent.com/103627487/204703780-1a68f44c-69bc-4c31-ae42-b3cc8e518d18.png)

**Comment by youliyuan-fit2cloud** [comment]
请再检查一下导入的接口case，看起来case ID都是一样的。

**Comment by meijieDouDou** [comment]
升级到v1.20.17-tls还是有这个问题存在
![image](https://user-images.githubusercontent.com/103627487/205094948-ba8d62a9-67d6-4457-bff5-8b6341d30f35.png)
![image](https://user-images.githubusercontent.com/103627487/205095086-360ae902-9b20-4caf-a8ff-d68de9ff2c59.png)

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉长时间未反馈，该问题已经在v1.20.18-lts中解决了。
