### ISSUE TITLE
[BUG]接口自动化报告失败的case没有id不便于跟踪

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20358]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口自动化报告失败的case没有id不便于跟踪

### 重现步骤

1、接口自动化执行
2、报告-查看error的
3、无ID不知道是哪个case（想去接口定义-case你那去调式一下）

### 期待的正确结果

1、有caseid
2、点击caseid可以链接到case

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/204735916-067b81b4-fa1f-4a65-87b9-0371251567eb.png)

**Comment by luty2018** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/36292514/205009155-69bfaeda-01b9-41fd-92f2-d2eecf7bb626.png">
只有集合报告是提供跳转的， 独立报告本身用户已经知道是哪个场景了。

**Comment by legend818** [comment]
现在不是想知道是哪个场景 是caseid问题
你在接口自动化的时候添加case 显示ID的，但是你执行这个场景之后一个case报错了
 我需要去单独调试一下，在报告那看到的case没有ID，不好找

**Comment by luty2018** [comment]
了解， 我们优化一下。
