### ISSUE TITLE
[FEATURE] 脑图需要搜索功能

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#20350]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

执行用例，有时需要看下某个用例，只记得关键字，脑图需要搜索功能快速定位用例。

**Comment by luty2018** [comment]
这个规划在脑图的重构中了 。
