### ISSUE TITLE
[FEATURE] 邮件发送模板，希望测试计划阶段调整为中文的。目前是(smoke,system) 英文显示的

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20368]
### MeterSphere 版本

  v2.2.1

### 联系方式

leibo.zhao@fit2cloud.com

### 请描述您的需求或者改进建议

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/33945037/204755993-e09c0fc8-72da-42ca-bae7-cef372010812.png">

希望改成中文显示

### 请描述你建议的实现方案

中文显示

**Comment by luty2018** [comment]
需求提tapd，这个已经提过了。
