### ISSUE TITLE
[BUG]接口自动化添加case高级查询需支持按接口case的模块检索

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20364]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口自动化添加case高级查询需支持按接口case的模块检索

### 重现步骤

1、接口自动化--新建场景
2、添加case--高级查询
3、想不添加A模块或者想添加B模块的全部case
4、无法实现

### 期待的正确结果

高级查询支持检索

**Comment by xulinde** [comment]
如果想导入B模块的全部case，可以点击左侧B模块，然后复选框选择全部数据
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/64065190/204994150-366c70f5-3482-4fd7-bb85-a95adb617097.png">

**Comment by legend818** [comment]
我想过滤B模块的P1

**Comment by xulinde** [comment]
可以先过滤出B模块的所有case，然后高级搜索按等级再筛选
