### ISSUE TITLE
[BUG]测试计划，配置定时任务，勾选外置资源池选项，实际已经执行通过了，但是报告结果显示 NotExecute

### ISSUE THREAD

**Issue by zfp19961018** [metersphere/metersphere#20363]
### 联系方式

939369712@qq.com

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

测试计划，配置定时任务，勾选外置资源池选项，实际已经执行通过了，但是报告结果显示 NotExecute
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/63086034/204740750-7b2667c0-69ce-4cbf-a19d-eddb642edc38.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/63086034/204740877-3b8674ff-eae0-4b34-af6c-98a8593cf49e.png">

### 重现步骤

测试计划，配置定时任务，勾选外置资源池选项

### 期待的正确结果

正确显示执行结果

**Comment by zfp19961018** [comment]
如果不是一个bug,或许想知道这个可能和什么配置相关？

**Comment by xulinde** [comment]
用的什么类型的资源池，local、k8s还是node

**Comment by zfp19961018** [comment]
选择的是local，现在是必现。

**Comment by xulinde** [comment]
> 选择的是local，现在是必现。
方便把场景导出来，我们复现下吗
