### ISSUE TITLE
[BUG]接口自动化添加case缺少对比功能

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20362]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口自动化添加case缺少对比功能

### 重现步骤

前提：ms是一个平台化的系统，操作员有张三、李四、王五等等，现有一大型系统在ms实现
1、接口自动化--某个场景A  张三添加了100个case，后续李四新增了case，单未添加到场景A
2、王五、小明等等添加case，添加了部分到场景A
3、还有哪些case遗漏了呢，不知道

### 期待的正确结果

在添加case的时候，对比当前场景的case，只检索未添加到场景的case
 或者高级查询加个选项过滤
或者已经在场景A的有个标识，

**Comment by luty2018** [comment]
“或者已经在场景A的有个标识” 这个可以加

**Comment by legend818** [comment]
最好的方案是 再加个高级查询

**Comment by luty2018** [comment]
了解， 我们有计划规划全局搜索，待规划排期。
