### ISSUE TITLE
[BUG] v2.3.1 & v2.4.0 性能测试不能通过加载自定义变量来运行

### ISSUE THREAD

**Issue by itransit** [metersphere/metersphere#20373]
### MeterSphere 版本

v2.3.1 or  v2.4.0

### 使用外置数据库

否

### 问题描述

在edge最新版【Microsoft Edge 版本 107.0.1418.62 (正式版本) (64 位)】上，
通过 插件 【metersphere-chrome-plugin-v1.2.4 】录制脚本并手动修改脚本进行自定义参数化，比如用户名、密码、token等动态数据
运行性能测试，页面无反应；对比在v2.2.1版本运行均正常。

### 重现步骤

在edge最新版【Microsoft Edge 版本 107.0.1418.62 (正式版本) (64 位)】上，
通过 插件 【metersphere-chrome-plugin-v1.2.4 】录制脚本并手动修改脚本进行自定义参数化，比如用户名、密码、token等动态数据
运行性能测试、页面无反应

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我截图里执行的这个场景是在edge上安装的插件录制的脚本，然后也添加了参数化字段
![image](https://user-images.githubusercontent.com/73461316/204996299-e5bb28db-4a67-479d-a22c-1037d2f7b4fb.png)
![image](https://user-images.githubusercontent.com/73461316/204996437-9090c860-cd34-4106-96f0-a2b30cf27b24.png)
