### ISSUE TITLE
[FEATURE]接口测试case通过检索之后反向不到API

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20372]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口测试case通过检索之后反向不到API

### 重现步骤

【前提】： 这是一个平台化系统，张三、李四王五都在操作，接口自动化发现一个case失败，找到id
1、接口定义-case搜索到对应case
2、想知道是哪个模块的接口定义，没办法

### 期待的正确结果

我想找到是哪个模块的，这样我可以上系统去验证一下是不是系统也有问题。希望可以让我追溯到接口定义

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/204784374-589c4901-fbf6-4842-9118-1339c3ffe1cd.png)
你看接口定义就知道在哪个模块

![image](https://user-images.githubusercontent.com/19423100/204785689-d08fe66a-1863-41ba-8d01-1780cc714a6f.png)

**Comment by luty2018** [comment]
意思是在case列表增加模块字段展示吗

**Comment by legend818** [comment]
也可以，这样可以减小范围， 目标是找到这个case 对应的接口定义是哪个

**Comment by luty2018** [comment]
好的， 了解清楚了。待规划排期。
