### ISSUE TITLE
[BUG]2.4.0版本集成服务没有了JIRA相关内容

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#20371]
### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

2.4.0版本集成服务没有了JIRA相关内容

### 重现步骤

1. 在线安装2.4.0版本
2. 查看集成服务

### 期待的正确结果

与2.3.1版本一样存在JIRA集成服务器

### 附加信息

![企业微信截图_16698037308886](https://user-images.githubusercontent.com/6109912/204771021-d15024e9-aca4-41f8-98c7-bb9fce49f796.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，服务集成对接第三方平台插件化（用户可以自行对接第三方项目管理平台），请参考下面链接下载插件。
https://github.com/metersphere/metersphere-platform-plugin
