### ISSUE TITLE
[FEATURE] 项目环境配置中新增开关控制接口测试请求发送使用浏览器发送

### ISSUE THREAD

**Issue by naah69** [metersphere/metersphere#20384]
### MeterSphere 版本

v1.20.16-lts-3bb3478d

### 联系方式

17604510149

### 请描述您的需求或者改进建议

目前开发中想要调试接口，需要在postman或其他工具中进行接口请求调试。
然后再讲接口导入到metersphere或手动复制。

测试过metersphere中的接口调试，发现该功能的请求是由后端进行转发的。
使用127.0.0.1的话，没办法像yapi一样满足功能。
所以希望接口调试时可以加入从浏览器发送请求的策略。
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/25682169/205004603-49179a6e-e902-45a9-8a10-63234ac78b77.png">

### 请描述你建议的实现方案

在项目的环境配置中加入开关控制请求的发送策略，本地或远端。
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/25682169/205004551-b6b3b4bd-9551-4075-b719-977536c2795d.png">

**Comment by luty2018** [comment]
这个我们需要进一步调研具体的实现。

**Comment by naah69** [comment]
> 这个我们需要进一步调研具体的实现。

好的，感谢回复
