### ISSUE TITLE
[BUG]每天定时执行测试计划，内存占用会逐日升高，最后会将内存占满崩掉，需要重启服务才可以

### ISSUE THREAD

**Issue by zfp19961018** [metersphere/metersphere#20383]
### 联系方式

939369712@qq.com

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

每天定时执行测试计划，内存占用会逐日升高，最后会将内存占满崩掉，需要重启服务才可以
内存占比都在增加，好像内存没有释放

### 重现步骤

每天跑定时任务测试计划

**Comment by youliyuan-fit2cloud** [comment]
你好，请进一步说明一下这个定时任务的数据量，任务多久执行一次，一次执行多长时间，我们继续跟踪复现。

**Comment by zfp19961018** [comment]
每天执行大概3000多条case吧，每天定时跑两次，内存会一直飙升
<img width="429" alt="image" src="https://user-images.githubusercontent.com/63086034/205244083-aef084e0-bc06-4e59-9068-f5855be95fb9.png">

**Comment by youliyuan-fit2cloud** [comment]
如果使用 jython 版本 2.7.1-2.7.3 只要引入 import httplib 执行时，会遇到这种问题。目前没有更好的解决方案，建议使用2.7.0版本。
