### ISSUE TITLE
[FEATURE] 所有执行成功的弹框显示，希望可以设置颜色，比如：成功为绿色，失败为红色。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20381]
### MeterSphere 版本

v2.2.1

### 联系方式

leibo.zhao@fit2cloud.com

### 请描述您的需求或者改进建议

所有执行成功的弹框显示，希望可以设置颜色，比如：成功为绿色，失败为红色。

### 请描述你建议的实现方案

所有执行成功的弹框显示，希望可以设置颜色，比如：成功为绿色，失败为红色。

**Comment by luty2018** [comment]
请在tapd提交需求到交互设计迭代。
