### ISSUE TITLE
[BUG]  jsonpath表达式不被允许使用.length()函数；jmeter可以使用

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20380]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

jsonpath表达式不被允许使用.length()函数；jmeter可以使用

### 重现步骤

接口响应体如下
![image](https://user-images.githubusercontent.com/103925124/204981189-b38ba57d-42de-42b9-adb5-6b1da102a127.png)
提取参数jsonpath表达式中使用.length()
![image](https://user-images.githubusercontent.com/103925124/204981308-13316076-c25b-4dc8-9487-e44544e5d35f.png)
控制台报错： Error processing JSON content in len, message: Options AS_PATH_LIST and ALWAYS_RETURN_LIST are not allowed when using path functions!
Options AS_PATH_LIST and ALWAYS_RETURN_LIST are not allowed when using path functions!
![image](https://user-images.githubusercontent.com/103925124/204981450-a59b51d0-4a23-43bd-a446-3d984e2a3ac7.png)
断言中使用同上报错
![image](https://user-images.githubusercontent.com/103925124/204981820-db74a328-e86b-4ae2-a34d-547a26ff33d8.png)

### 期待的正确结果

可使用jsonpath  .length等方式
jmeter中使用：https://blog.csdn.net/qq_43856284/article/details/113739336
在线jsonpath表达式：https://www.jsonpath.cn/

**Comment by zyyfit** [comment]
您好，感谢您的反馈，上面您发的这个文章里写了，jmeter支持数组length的话需要先下载一个插件，然后添加插件中的json提取器，而我们是默认不带这些插件的，所以是和没有添加插件的jmeter保持一致的
![4ebb7d964a98688e3a9436d4914bcde](https://user-images.githubusercontent.com/73461316/205202180-2a442e46-965f-4fb1-9e6a-04e55a3ed03a.png)
![548458b6682cdd3e35d057bb1f05d6c](https://user-images.githubusercontent.com/73461316/205202206-6ee105fb-a5d8-4a64-9221-6e7366333485.png)
