### ISSUE TITLE
[BUG]测试计划关联场景，场景内sql自定义请求名称为空，场景不执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20396]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

测试计划关联场景，场景内sql自定义请求名称为空，场景不执行

### 重现步骤

1.添加sql协议自定义请求，请求名称为空
![image](https://user-images.githubusercontent.com/103627487/205090246-1be7c606-9bc3-403b-a7a7-9ee32a0a08ee.png)
![image](https://user-images.githubusercontent.com/103627487/205091153-a26b31c4-610f-431a-9c3e-49adb1908cbc.png)
2.测试计划关联刚刚创建的场景执行
![image](https://user-images.githubusercontent.com/103627487/205091597-c483ad5f-0f9a-422f-ae88-38eb62ea3f0e.png)
3.可以看到，该场景直接执行失败，0s返回，控制台也没有任何信息
![image](https://user-images.githubusercontent.com/103627487/205091854-2721b35a-ce1f-42a4-9b84-537b61e2da3b.png)
4.自定义请求添加上名称后（或者添加上名称后再删除），可以正常执行

**Comment by zyyfit** [comment]
您好，添加了自定义sql请求，没有填名称，后面也没编辑过名称，没有复现这个问题
![image](https://user-images.githubusercontent.com/73461316/205205592-ac3e9e6f-4bdd-4ca1-abdd-cf369752a80c.png)
