### ISSUE TITLE
[BUG]全局设置了Cookie,请求也设置了Cookie，在请求中看到两个Cookies

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#20393]
### 联系方式

MeterSphere 交流群31    chase  chase001@qq.com

### MeterSphere 版本

版本:   v1.20.16-lts-3bb3478d

### 使用外置数据库

是

### 问题描述

全局设置了Cookie,请求也设置了Cookie，在请求中看到两个Cookies

### 重现步骤

![image](https://user-images.githubusercontent.com/23476281/205054577-950d3613-aba0-4b4e-8853-0dc1e63907a4.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，确认了一下，我们目前是会合并所有的cookie，所以是每个cookie都会显示的

**Comment by chase001** [comment]
能说明下吗？不是很理解以下：说明，到底是会显示两个还是合并显示成一个呢？
我们目前是会合并所有的cookie，所以是每个cookie都会显示的。

**Comment by zyyfit** [comment]
显示的时候是每个都会显示，但是实际生效的时候是合并成一个生效的

**Comment by chase001** [comment]
能向浏览器那样直接就一个cookie吗？
![image](https://user-images.githubusercontent.com/23476281/210744357-23e0fcda-3d37-4f70-bf49-381c910f63a7.png)
一个cookies:
里面有环境变量的cookie和请教的cookie都不知那个cookie生效了
![image](https://user-images.githubusercontent.com/23476281/210744765-948ce07f-7c4f-4542-ac48-0a8733227ba4.png)
