### ISSUE TITLE
[BUG]缺陷字段筛选无效

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#20399]
### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

无法按照缺陷模板新添字段（严重程度、处理人、状态）筛选

### 重现步骤

1、进入测试跟踪-缺陷管理
2、按照缺陷模板新添字段（严重程度、处理人、状态 等）筛选
3、勾选某一项进行筛选，缺陷列表数据没按照条件刷新

**Comment by youliyuan-fit2cloud** [comment]
v2.4.1中已修复。
