### ISSUE TITLE
[FEATURE]期望可像postman一样根据swagger接口文档和curl命令来导入接口

### ISSUE THREAD

**Issue by qddkk** [metersphere/metersphere#20418]
### MeterSphere 版本

v1.20.x-lts

### 联系方式

1004709058@qq.com

### 请描述您的需求或者改进建议

期望可像postman一样根据swagger接口文档和curl命令来导入接口
这样不用一个一个接口录入方便很多
<img width="878" alt="image" src="https://user-images.githubusercontent.com/59435662/205251300-9ba12a63-0a09-4502-bf82-1f1ceedc6117.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/59435662/205251381-8ad1240c-14ac-42f1-85a4-3ee40a696a93.png">

### 请描述你建议的实现方案

导入curl命令生成对应接口的入参、请求头、地址
导入swagger文档地址批量导入接口文档

**Comment by luty2018** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/36292514/205256700-e4036890-fc7e-4f97-9389-2264f0831357.png">
已经支持通过swagger地址直接导入。
