### ISSUE TITLE
[BUG]在测试智能门紧系统时，门锁系统MQTT服务发布消息，在PAAS平台的broker端接收后，透传至SAAS平台的broker端， APP的MQTT客户端再通过sub组件，订阅到门锁系统发布的消息。

### ISSUE THREAD

**Issue by 18565758984** [metersphere/metersphere#20410]
### 联系方式

zhouyiliang@kaadas.com

### MeterSphere 版本

v2.2.1-68ccaa2a

### 使用外置数据库

否

### 问题描述

问题:当前MS的MQTT插件，在建立连接时，必须指定连接名，导致发布、订阅的消息均与连接名进行了绑定。当存在MQTT客户端A接收MQTT服务端B的发布消息的测试场景时，由于两者连接名不一致，无法接收到消息。(备注:Jmeter中该场景中MQTT客户端A能正常订阅到MQTT服务的B发布的消消息)

### 重现步骤

问题:当前MS的MQTT插件，在建立连接时，必须指定连接名，导致发布、订阅的消息均与连接名进行了绑定。当存在MQTT客户端A接收MQTT服务端B的发布消息的测试场景时，由于两者连接名不一致，无法接收到消息。(备注:Jmeter中该场景中MQTT客户端A能正常订阅到MQTT服务的B发布的消消息)

**Comment by zyyfit** [comment]
您好，2.5.0版本我们去掉了mqtt组件的连接名必填字段校验，您可以下载最新的mqtt插件使用
