### ISSUE TITLE
[BUG]JSON-文档结构校验，导入json后，显示类型错误，下拉框没有该类型

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20426]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

JSON-文档结构校验，导入json后，显示类型为bigdecimal，下拉框没有该类型

### 重现步骤

1.断言规则处，选择json-文档结构校验，之后导入json
![image](https://user-images.githubusercontent.com/103627487/205302124-897e4683-1c54-4010-9a03-6c175ae69ced.png)
![image](https://user-images.githubusercontent.com/103627487/205302567-8a421561-b29c-4fa5-8b01-53a94cbe4853.png)
2.导入后自动回填的类型为bigdecimal，下拉框没有该类型
![image](https://user-images.githubusercontent.com/103627487/205302411-f113ce0a-a0f6-4f68-bd0f-153a28c44a41.png)
3.导入的json,可以参考下
{
    "code": 200,
    "message": "Success",
    "oneYearPerformance": 77.05269309438006,
    "oneDayPerformance": 101.18956254796623
}
备注：v2.4.0版本导入该json,类型自动回填的是number,v1.20.17-lts版本显示的是bigdecimal

### 期待的正确结果

1.期望下拉框加上bigdecimal类型，可供选择
2.若是bigdecimal包含在number类型中，回填错误，期望回填正确类型

**Comment by zyyfit** [comment]
您好，没有复现这个问题，在1.20.17版本也是number的
![image](https://user-images.githubusercontent.com/73461316/205620130-23b1965e-c1b8-4a20-9f9b-50d96583a738.png)

**Comment by meijieDouDou** [comment]
不是请求体那的json,是断言规则处的，json文档格式校验
![image](https://user-images.githubusercontent.com/103627487/205623530-b5d34c42-24fe-47e0-b1be-37a7b7c12306.png)
![image](https://user-images.githubusercontent.com/103627487/205623635-fe5f2456-7396-47c4-abdb-7a13cf9cf7a7.png)

**Comment by zyyfit** [comment]
好的，我们会把 bigdecimal 改成 number

**Comment by zyyfit** [comment]
已修复，1.20.18版本发布，请等待版本发布后验证
