### ISSUE TITLE
[BUG] 任务中心接口请求时间长，导致任务中心访问时空白页经常出现，接口返回数据后，再次访问任务中心，非空白页

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20425]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

任务中心接口请求时间长，导致任务中心访问时空白页经常出现，接口返回数据后，再次访问任务中心，非空白页

### 重现步骤
执行完测试计划，测试计划中场景较多
点击首页任务中心 接口请求37秒，37秒后页面才成功渲染，37秒内一直是空白页
![image](https://user-images.githubusercontent.com/103925124/205298249-c5284f1a-9148-437c-b86b-185c03975f7c.png)

### 附加信息

中信建投问题

**Comment by Ycr123888** [comment]
麻烦尽快修复一下，问题比较显眼，且不方便。企业用户提出@luty2018

**Comment by youliyuan-fit2cloud** [comment]
v1.20.18-lts中已修复，请升级一下吧。
