### ISSUE TITLE
[BUG]与JIRA BUG管理系统对接，不能通过手动导入的方式导入BUG，会提示错误

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#20423]
### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

与JIRA BUG管理系统对接，不能通过手动导入的方式导入BUG，会提示错误

### 重现步骤

1. 下载模板
2.  按照模板填写execl文件
3.  通过导入按钮导入缺陷

### 期待的正确结果

能正确的导入缺陷

### 附加信息

![企业微信截图_16699773435951](https://user-images.githubusercontent.com/6109912/205274445-f0071eee-5a63-46a8-acc9-12491596e3a1.png)

**Comment by xulinde** [comment]
未复现该问题，方便发下您的文件吗

**Comment by guoliang3** [comment]
确实,我也是这样导入的格式和说明对不上,而且错误文件不重新上传直接调回登录界面

**Comment by ChangqiaoWang** [comment]
需要什么文件？

**Comment by song-cc-rock** [comment]
> 需要什么文件？

请问你那边新建缺陷是否会报同样错误, 又或者看看新增缺陷页面与导入的EXCEL模板中表头字段内容是否对应
