### ISSUE TITLE
[BUG] PGSQL 连接报错

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#20435]
### 联系方式

18159668371

### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

项目环境中配置 PostgreSQL 提示SSL 连接失败，应该是未支持兼容发起 TLS 连接；Navicatb 客户端可以连接成功。
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/92966838/205533945-142aee98-7668-4280-9c80-edee8d11f881.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/92966838/205533960-99bb5138-eec1-434b-874e-0bce88b5febb.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/92966838/205534009-c4726cc3-1d84-4bea-9813-e83495e4e0f1.png">

### 重现步骤

1、维护 PGSQL 数据库连接
2、点击校验

### 期待的正确结果

可以正常通过 TLS 连接 PGSQL 数据库

**Comment by youliyuan-fit2cloud** [comment]
你好，你这个数据库版本是多少？

**Comment by gaohonghai** [comment]
![image](https://user-images.githubusercontent.com/92966838/205807503-1a312e33-b6f9-44f3-8cef-672bd5d8986e.png)

**Comment by youliyuan-fit2cloud** [comment]
emmm，目前还不支持高斯的。。。

**Comment by youliyuan-fit2cloud** [comment]
可以先提个需求，我们后期调研一下，然后反馈给您。

**Comment by gaohonghai** [comment]
导入指定版本的jar包，jmeter可以正常进行jdbc request
![image](https://user-images.githubusercontent.com/92966838/206411636-115032f6-6e43-4950-ba98-3110e1f52ac4.png)
![image](https://user-images.githubusercontent.com/92966838/206411694-66553052-f944-40cf-9f1e-f2ef3ddbea82.png)
![image](https://user-images.githubusercontent.com/92966838/206411674-72812e82-8739-43cc-8b5e-9dadebf07f3b.png)

但是我把他这个包 copy 到system-setting 容器和 project-management 容器下的 /app/lib  ，msctl reload 之后再进行连接 依然不行

**Comment by gaohonghai** [comment]
quote

> https://blog.csdn.net/LDR1109/article/details/126235616 看起来应该是驱动问题。你上传的jar跟MS内置的pgsql驱动冲突，现在没法兼容、切换。

@liqiang-fit2cloud 强哥，你说这个咱们或者客户这有什么迂回的办法可以解决一下吗

**Comment by liqiang-fit2cloud** [comment]
No workaround for now...
