### ISSUE TITLE
[BUG]自定义用例ID时，会出现多个ID相同的用例

### ISSUE THREAD

**Issue by MidnightColorfulCat** [metersphere/metersphere#20434]
### MeterSphere 版本

X

### 使用外置数据库

否

### 问题描述

自定义用例ID时，上传一份用例删除至垃圾桶，再次上传这份用例，会有部分垃圾桶用例自动返回用例列表，导致用例重复

### 重现步骤

自定义用例ID时，上传一份用例删除至垃圾桶，再次上传这份用例，会有部分垃圾桶用例自动返回用例列表，导致用例重复，出现多个ID相同的用例

### 期待的正确结果

以ID为标准，一个ID只有一条用例

**Comment by xulinde** [comment]
未复现该问题，是必现吗？再详细描述下复现步骤及截图吧
