### ISSUE TITLE
[QUESTION]编译失败，提示找不到baseSystemConfigDTO.setRunMode

### ISSUE THREAD

**Issue by giantgj** [metersphere/metersphere#20432]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/22345568/205449687-68573cf7-1131-4fe7-97bb-b701635aea52.png)

**Comment by liuruibin** [comment]
1. 按照build.md 把本工程的基本构建部分做完
2. 如果选择2.3分支需要单独下载ms-jmeter-core代码进行本地编译 `mvn install`
