### ISSUE TITLE
[BUG]飞书机器人,通知没有实际@提醒的作用

### ISSUE THREAD

**Issue by bove0623** [metersphere/metersphere#20431]
### 联系方式

18600619373@163.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

通知使用飞书机器人,通知的接收人选择对应的人,实际飞书群 只有展示的@标识,但没有实际@提醒的作用。
如果把自动化拿来线上巡检,报警不能及时触达,特别是周末 关注群本来就不多。
另外 是不是可以考虑 新增 短信,语音等不同优先级的通知,实际场景反馈,希望贵公司关注考虑。谢谢

### 重现步骤

通知使用飞书机器人,通知的接收人选择对应的人,实际飞书群 只有展示的@标识,但没有实际@提醒的作用。

### 期待的正确结果

通知使用飞书机器人，@希望有实际@提醒的作用,另外考虑不同优先级的通知,比如短信 语音更容易触达

**Comment by zyyfit** [comment]
您好，感谢您的反馈，这里目前是由于飞书自己的安全性限制，所以不能真实的艾特到具体的用户
