### ISSUE TITLE
[QUESTION]【期待回复】为什么非手动触发接口场景的时候，测试报告的状态一直是running

### ISSUE THREAD

**Issue by huajingtong** [metersphere/metersphere#20433]
### 请描述您的问题
【版本】
v1.20.11-lts
【联系方式】
934395737@qq.com

【问题描述】
为什么非手动触发接口场景的时候，测试报告的状态一直是running？
导致问题：
1.定时任务一直不结束，无法给我设置的webhook推送消息
2.jenkins一直拿不到执行结果

如下图
<img width="725" alt="image" src="https://user-images.githubusercontent.com/30971576/205498313-dd617b75-ea0b-41ed-aa22-2138cd37fe73.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/30971576/205498743-d7aa816d-c46b-44c1-9c00-26e7992bd520.png">

**Comment by huajingtong** [comment]
https://github.com/metersphere/metersphere/issues/20307
这个帖子和我遇到的问题一样

**Comment by youliyuan-fit2cloud** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/54612864/205586303-c7741392-f5e8-4ccc-845c-217697287e58.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/54612864/205586379-78795426-b998-4015-8895-956822df7bbc.png">

请检查系统设置的配置是否正确。

**Comment by youliyuan-fit2cloud** [comment]
> > <img alt="image" width="1106" src="https://user-images.githubusercontent.com/54612864/205586303-c7741392-f5e8-4ccc-845c-217697287e58.png">
> > <img alt="image" width="702" src="https://user-images.githubusercontent.com/54612864/205586379-78795426-b998-4015-8895-956822df7bbc.png">
> > 请检查系统设置的配置是否正确。
> 
> 这个资源池在哪儿进入的啊，没找到

1.系统设置-设置-测试资源池-LOCAL -编辑LOCAL资源池查看 node ip 
2.系统设置-系统参数设置-基本配置-当前站点URL

**Comment by huajingtong** [comment]
> > > <img alt="image" width="1106" src="https://user-images.githubusercontent.com/54612864/205586303-c7741392-f5e8-4ccc-845c-217697287e58.png">
> > > <img alt="image" width="702" src="https://user-images.githubusercontent.com/54612864/205586379-78795426-b998-4015-8895-956822df7bbc.png">
> > > 请检查系统设置的配置是否正确。
> > 
> > 
> > 这个资源池在哪儿进入的啊，没找到
> 
> 1.系统设置-设置-测试资源池-LOCAL -编辑LOCAL资源池查看 node ip 2.系统设置-系统参数设置-基本配置-当前站点URL

**配置正常**

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/205790635-841aa290-e615-4bd0-aee0-7f13dbf8a5aa.png)
