### ISSUE TITLE
[BUG]UI进行div元素拖拽时自动全屏，部分元素定位路径无法识别问题反馈

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#20447]
### MeterSphere 版本

V2.2.1

### 使用外置数据库

否

### 问题描述

问题一：
UI进行div元素拖拽时自动全屏
问题二：
使用xpath元素定位时，概率性元素识别错误；
使用css元素定位时，无法定位到对应元素

### 重现步骤

问题一：
客户的自测平台，在对自定义视图div页签的压差模块进行拖拽视图展示，无浏览器全屏操作的情况下，浏览器自动全屏显示，功能实现异常；
问题二：
在用xpath进行“压差”元素定位，定位外部的div路径时，有概率性路径识别为“电压”模块；
在用css进行“压差”元素定位时，无法识别到“压差”元素，导致用例执行失败。
备注：
用本地python基于之前的xpath、css进行元素定位，用例均执行正确(已录制视频，后续可单独提供)

### 附加信息
![a405e948ece2306be427b064db9b2d2](https://user-images.githubusercontent.com/92150453/205565845-b82bf06e-6ae0-4b45-ba70-0e3e5b41d4d4.png)
![微信图片_20221205143525](https://user-images.githubusercontent.com/92150453/205565464-3ba61cb4-3db5-4f11-9877-820ad99c162c.png)

**Comment by zrfit** [comment]
经和祥义沟通，客户内网才能复现，前几天客户lisence试用到期了没法复现，待和客户协调后再看是否能复现，然后再跟进该问题。

**Comment by sageonedream** [comment]
经确认，可能与咱们代码内，进行拖拽操作，自动全屏，导致css元素路径变动导致(已与大老师本地确认)
<img width="593" alt="0b866452eb1455af77967d5c632d71d" src="https://user-images.githubusercontent.com/92150453/205862921-6a1a7d45-14bd-484e-bd2d-2045d15e5da8.png">

**Comment by zrfit** [comment]
v2.5.0已修复。
