### ISSUE TITLE
[BUG]导入swagger的rest参数接口，导入不成功。

### ISSUE THREAD

**Issue by yourSwim** [metersphere/metersphere#20458]
### 联系方式

交流群号：137，昵称：BUDING

### MeterSphere 版本

 v1.19.3-df1d5d76

### 使用外置数据库

否

### 问题描述

导入swagger的rest参数接口，导入不成功。

### 重现步骤

导入有rest参数的接口的swagger

### 附加信息

![image](https://user-images.githubusercontent.com/32047076/205602375-0f9d795a-1c6d-49eb-94fc-5da2e05b19b0.png)
![image](https://user-images.githubusercontent.com/32047076/205602633-cbd83ff8-1dc7-4c0a-bf2c-15f615e19d0b.png)

**Comment by zyyfit** [comment]
您好，最新版 2.4.0版本 和 1.20.17-lts 版本都没有出现您这个问题，您可以升级到最新版试一下，如果还有问题的话，可以上传一下您的swagger文件给我们看看

**Comment by yourSwim** [comment]
场景描述：
我使用MeterSphere Jenkins插件，每次构建项目之后都会执行一次测试计划A，测试计划A有用户信息的新增接口（用户名做唯一性校验）。第一次构建执行完测试计划之后，就会保存一条用户到数据库了。我下次再构建的话，同样的用户信息再次保存一遍，用户名重复了，校验不通过，新增接口肯定不成功了。




期望：
每次构建，与上次构建同样的用户信息都能新增成功。所以这样才能达到这个效果？




是否有每次执行完测试计划之后，把这次执行所存到数据库里的数据都回滚的？因为只是为了测试接口是否跑得通，不希望影响到数据库的数据。

**Comment by zyyfit** [comment]
这种情况您可以在测试计划中增加清理数据的接口，把测试数据一起删除
