### ISSUE TITLE
[BUG]  环境配置里面的请求头Cookie和单个接口里面请求头冲突

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20467]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts，v2.2.1

### 使用外置数据库

否

### 问题描述

环境配置设置Cookie，单个接口里面也设置Cookie，请求的时候。
1. 单个接口里面的没有替换掉环境配置里面的。
2. 请求内容里面出现了两个Cookie，其中一个为Cookies

![image](https://user-images.githubusercontent.com/33945037/205620475-9b66d00c-bed6-474f-b1b8-fdbffb6d54ca.png)

![image](https://user-images.githubusercontent.com/33945037/205620436-5475dac6-2802-4042-970e-41cf73f430d9.png)

![image](https://user-images.githubusercontent.com/33945037/205620394-a8913477-f2b6-4da3-a6e1-77d62f75f424.png)

当都设置为Cookies的时候，确实被替换掉了，但是请求内容里面有两个Cookies

![image](https://user-images.githubusercontent.com/33945037/205620909-15d5318c-8162-47b1-997d-84ef70322493.png)

![image](https://user-images.githubusercontent.com/33945037/205620841-30cd9497-da1f-43f2-b4ba-b390d8f9fb78.png)

### 重现步骤

同上

### 期待的正确结果

1. 请求头应该是Cookies，不是Cookie？
2. 替换之后应该是只有一个。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #20393
