### ISSUE TITLE
[BUG]性能测试-测试详情数据不准确

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20466]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

性能测试-测试详情数据与请求统计数据对不上

### 重现步骤

1.执行性能测试，查看报告，查看测试详情数据和请求统计，测试详情的从压测整体曲线和数据看最大的响应时长是1983.8，而请求统计数据是2385.
![image](https://user-images.githubusercontent.com/103627487/205617709-0fdce7ac-8c30-4763-a3d4-e64647bf9b01.png)
![image](https://user-images.githubusercontent.com/103627487/205617806-5e0f436a-c006-4245-9c91-e4545003de56.png)
2.只看测试详情，响应百分比: 99th percentile 最大值，比上面两个响应的值都大
![image](https://user-images.githubusercontent.com/103627487/205619169-128012e4-66ec-4b30-b716-c34ef2b04374.png)
3.响应百分比: 99th percentile 这个值是怎么计算出来的，和请求统计里的 99% 是一个值吗？如果是一个值，为啥还有平均值，最大值和最小值
![image](https://user-images.githubusercontent.com/103627487/205619868-31bc5e47-af9a-4319-b0c5-b5dda6b6c6fe.png)
![image](https://user-images.githubusercontent.com/103627487/205619351-b6b9cc07-b9fb-4e58-b331-c01fe6c0a047.png)

**Comment by meijieDouDou** [comment]
这两个地方都是统计响应的Avg,Min,Max，数值是不一样的，这两个地方统计逻辑是有什么不同哇，图表数据的二次计算逻辑是什么呀？

**Comment by liuruibin** [comment]
已知：x轴是时间，y轴是指标值
avg：平均值，取n个x轴对应的y轴的值进行加和并除以n
min：最小值，取n个x轴对应的y轴的值进行比较并取得最小值
max：最大值，取n个x轴对应的y轴的值进行比较并取得最大值

**Comment by shenkaibo** [comment]
![image](https://user-images.githubusercontent.com/30038088/208090465-9aee6038-7893-405a-8cdc-2d1ddd469368.png)
这个 "99%响应时间" 的 max 值 怎么是取得 “请求统计” 里的 响应时间 max ?

**Comment by liuruibin** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/23045261/210780703-35382529-79a3-4bdd-8cbf-260aa76a39f6.png">
