### ISSUE TITLE
[BUG] 导入脑图，">"和“<” 反转义失败

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20468]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts，v2.2.1

### 使用外置数据库

否

### 问题描述

含有特殊符号的xmind脑图，导入MS之后，页面没有进行反转义
原图：
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/33945037/205621800-575ca803-9dab-4fd6-b69d-cc1c7d0728bf.png">
V1.20.17-lts 导入为：
![image](https://user-images.githubusercontent.com/33945037/205621998-bf36de13-2d40-45b9-80be-5a91f736222f.png)

V2.2.1 导入为

![image](https://user-images.githubusercontent.com/33945037/205622351-60a8eccf-3b80-42f9-9c21-138cbcbbfbc1.png)

### 重现步骤

脑图文件 如果需要 请联系: leibo.zhao@fit2cloud.com
可参考：https://blog.csdn.net/sinat_29326171/article/details/120967812?spm=1001.2101.3001.6650.5&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-5-120967812-blog-114648357.t0_edu_mix&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-5-120967812-blog-114648357.t0_edu_mix&utm_relevant_index=9

**Comment by xulinde** [comment]
用最新的v1.20.17-lts和v2.4.0都未复现该问题，方便把xmind导出来，我们复现下吗？
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/64065190/206135773-ab794c2a-5410-4d70-9a4d-90aa7e9a539c.png">

**Comment by xulinde** [comment]
v2.8.0已修复，建议您升级下版本～
