### ISSUE TITLE
[QUESTION]全局的前后置脚本（包括单接口、场景）执行逻辑是否有问题

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#20476]
### 请描述您的问题

场景一：全局前置脚本（单接口、所有场景步骤前均有配置）
1、脚本配置：下图中，在全局前置脚本栏目，对“单个请求步骤前执行”、“所有场景步骤前执行”都添加了执行脚本，并分别有对应标记日志输出。
![image](https://user-images.githubusercontent.com/92966838/205795448-c7e103d1-46f4-48a2-9b69-b2d19adb6b15.png)
2、在接口自动化场景中点击调试。

- 在场景第一个步骤中，分别执行了“所有场景步骤前执行”、“单个请求步骤前执行”的两个前置脚本。**问题一：是不是应该仅执行“所有场景步骤前执行”呢？**
- 在场景第二个步骤中，又分别执行了一次“所有场景步骤前执行”、两次“单个请求步骤前执行”的前置脚本。**问题二：这块的执行逻辑实在没看明白**

![image](https://user-images.githubusercontent.com/92966838/205796975-c48cdc90-a7ab-40e3-bf6f-433658360868.png)
![image](https://user-images.githubusercontent.com/92966838/205797011-1d92335d-8c00-4765-85da-99388903f0ba.png)

场景二：全局前置脚本（单接口、所有场景步骤前均有配置）+ 全局后置脚本（单接口、所有场景步骤后均有配置）
1、脚本配置：场景一的基础上，在下图全局后置脚本栏目，对“单个请求步骤后执行”、“所有场景步骤后执行”都添加了执行脚本，并分别有对应标记日志输出。
![image](https://user-images.githubusercontent.com/92966838/205800261-190f48b4-715e-447a-be93-c8e59bf53cf3.png)
2、在接口自动化场景中点击调试。

- 在场景第一个步骤中，前置脚本的执行情况于场景一一致；后置脚本执行了“单个请求步骤后执行”。
- 在场景第二个步骤中，前置脚本的执行情况于场景一一致；又执行了两次的“单个请求步骤后执行”。

![image](https://user-images.githubusercontent.com/92966838/205800755-e1b15ca6-924e-4ebc-a4f7-8b9997b89f3e.png)
![image](https://user-images.githubusercontent.com/92966838/205800721-959648aa-55e3-4522-9e6c-0748a61a0565.png)

总体上使用来看，作为普通用户没有弄明白逻辑，感觉有bug？

**Comment by luty2018** [comment]
日志会打印全部的信息， 这个是jmeter的逻辑，总感觉有bug，最终返回结果是否和预期一样？
