### ISSUE TITLE
[BUG]手动停止的性能测试场景 不能下载JTL文件，提示没有JTL文件

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#20472]
### 联系方式

群14-亲山留水

### MeterSphere 版本

1.20.17-lts

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/205790675-f9d65fee-7bd8-42b6-91e3-f90dad6d358b.png)
手动停止的性能测试场景 不能下载JTL文件，提示没有JTL文件

### 重现步骤

1、正常运行性能测试场景一段时间
2、手动停止场景
3、下载运行场景报告JTL文件

### 期待的正确结果

手动停止（非强制停止）的场景，JTL报告应该是可以下载的

**Comment by youliyuan-fit2cloud** [comment]
你好，社区版中测试资源池中不支持后置监听器功能，所以这个jtl报告不支持下载。后续考虑优化这里，感谢反馈。
