### ISSUE TITLE
[FEATURE] 接口定义，“未规划接口” 希望可以添加批量删除目录功能

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20473]
### MeterSphere 版本

v1.20.17-lts，v2.2.1

### 联系方式

leibo.zhao@fit2cloud.com

### 请描述您的需求或者改进建议

“未规划接口” 里面的目录，希望可以添加批量删除目录功能。

![image](https://user-images.githubusercontent.com/33945037/205793850-6ad338df-1502-4f36-8bd2-2eef9e97306f.png)

**Comment by luty2018** [comment]
TAPD已经提交过。
