### ISSUE TITLE
[FEATURE]建议：希望能支持接口swagger格式批量导入/导出功能

### ISSUE THREAD

**Issue by Jarvan40** [metersphere/metersphere#20470]
### MeterSphere 版本

v1.20.x-lts

### 联系方式

362337894@qq.com

### 请描述您的需求或者改进建议

由于项目原因，暂时没有接口文档。
我只能自己扒源码找到接口定义然后抽离出来，拼凑成swagger格式的接口导入文件。经测试可以单个导入。

我目前遇到的问题是：
1.我有几百个接口要导入。而swagger每个脚本只能导入一个接口。
2.未来维护可能还需要批量接口操作，期望能每个接口单独导入、导出

**Comment by zhangzhaox** [comment]
没有swagger的，可以尝试 IDEA插件同步API的方式

**Comment by luty2018** [comment]
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/36292514/205795889-b44d8432-5ced-4944-a704-bcf1cdfd7029.png">
如楼上建议，可以使用我们的idea插件。
