### ISSUE TITLE
服务集成中jira集成失败

### ISSUE THREAD

**Issue by qfl1202** [metersphere/metersphere#2047]
填写了jira关联的项目中的问题类型：缺陷
但是提交缺陷还是失败，error.log提示"errors":{"issuetype":"选择的问题类型错误。"}}]。
试了很多遍都不行，我猜测会不会是版本问题。
jira版本：v7.2.7

**Comment by guhan121** [comment]
@qfl1202 应该不是版本问题；应该是你jira有必填字段

**Comment by qfl1202** [comment]
> @qfl1202 应该不是版本问题；应该是你jira有必填字段

我改了一下  现在必填字段就仨，一个项目、一个问题类型、一个主题；提交还是报错"errors":{"issuetype":"选择的问题类型错误。"}}]

**Comment by qfl1202** [comment]
@guhan121 我改了一下 现在必填字段就仨，一个项目、一个问题类型、一个主题；提交还是报错"errors":{"issuetype":"选择的问题类型错误。"}}]
