### ISSUE TITLE
[BUG] api 调用测试计划执行接口，case 未执行，报“获取测试计划保存的环境信息出错!”问题

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20488]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

api调用测试计划执行接口，case未执行，报[获取测试计划保存的环境信息出错!]问题

### 重现步骤

1、api调用调用/test/plan/run接口  补充说明：此case很早被添加到测试计划中
执行时未设置环境
![image](https://user-images.githubusercontent.com/103925124/205847117-c1da3063-0f19-4fd4-b4f6-6c8b9fbdf09d.png)
2、查看报告，case未执行
![企业微信截图_16703000482801](https://user-images.githubusercontent.com/103925124/205846393-c38db33e-6e6d-453d-a0f5-e979fc17c8c7.png)
3、查看case详情，数据库已选择
![企业微信截图_16699638573384](https://user-images.githubusercontent.com/103925124/205846462-82b9bcba-2beb-4938-a60d-cee5be607ae4.png)
4、通过日志知道此case有报告id，故查看case报告，为停止状态
![企业微信截图_16703000624803](https://user-images.githubusercontent.com/103925124/205846590-97a70ad4-555c-4124-8f6a-bbca2c4114ba.png)
===============================分隔符=============================================
![企业微信截图_16703031473982](https://user-images.githubusercontent.com/103925124/206341764-d4ed756a-a024-4439-90a5-1552299fd41b.png)
============================分隔符============================================
![企业微信截图_16703031633899](https://user-images.githubusercontent.com/103925124/206341782-9b4621be-1b46-493c-b0df-3b60c384523b.png)

5、查看执行时日志
![image](https://user-images.githubusercontent.com/103925124/205846743-183080bb-0725-481b-94d2-ae6db2b62744.png)
详细日志如下：
[info.20221202-0.zip](https://github.com/metersphere/metersphere/files/10163710/info.20221202-0.zip)

### 期待的正确结果
对于很早加到测试计划的case-使用的环境代码判断加强

未执行的接口用户希望可以看到stoped的原因

### 附加信息
排查思路：
此case有前后置SQL，已选择数据库；
单执行case无问题；在测试计划中单执行case无问题；
有断言，是简单的状态码500；

_No response_

**Comment by Ycr123888** [comment]
**补充排查信息：**
测试计划id：89079e5a-f0d1-45e0-a4af-b28c1c3185b8
测试报告id:   aa80d169-da7b-4d72-9049-dc1d6afc3ccc
未执行用例num：103151003

**Comment by zyyfit** [comment]
您好，感谢您的反馈，日志里无法确定问题的具体原因，只能看出来是因为没有选择环境导致的，请问是怎么出现的这种没有环境的情况呢

**Comment by Ycr123888** [comment]
有一个较为混乱的前提，就是case是用户很久之前加入测试计划的，中间所选的环境不知道出现了什么问题

因为未执行原因未知，又影响到了测试计划的执行，用户已将此case取消关联到此测试计划

所以现在从只能从日志排查

**Comment by zyyfit** [comment]
用户环境能否复现呢？

**Comment by Ycr123888** [comment]
![image](https://user-images.githubusercontent.com/103925124/206605458-fc631e39-e548-42fa-8146-20852b5e06e9.png)
用户环境第一次出现如上图，赵勇当时也给看过，反馈看不出问题，继续观察是否可以复现
这次是第二次出现

**Comment by Ycr123888** [comment]
用户使用流水线调用测试计划，周期为一周执行一次，12月12号又出现未执行情况，第三次出现未执行
![image](https://user-images.githubusercontent.com/103925124/207257186-aae3770c-9581-4167-9eb7-4ba88d602782.png)
日志文件：
[info.20221212-0.zip](https://github.com/metersphere/metersphere/files/10215524/info.20221212-0.zip)
日志显示，测试计划中，此case执行结果是成功的
![1670916859874](https://user-images.githubusercontent.com/103925124/207254014-56a2f676-8b75-4384-a13f-205d07e35513.jpg)
测试计划开始执行时报错(database不知道为啥报这个错，重点关注下): 
![image](https://user-images.githubusercontent.com/103925124/207257406-d05bfa3f-82ed-4663-9bf4-34aca7b44315.png)
此case是8月加到测试计划中
![image](https://user-images.githubusercontent.com/103925124/207257775-cc9bfba2-3cf8-42be-a552-bfe549014226.png)
运行测试计划后，此case无变化，无修改
![image](https://user-images.githubusercontent.com/103925124/207257775-cc9bfba2-3cf8-42be-a552-bfe549014226.png)
此case可单独执行，无问题
![image](https://user-images.githubusercontent.com/103925124/207258251-ad83b1e6-e2a2-4014-b297-f08eff5a48d5.png)

**Comment by Ycr123888** [comment]
1、客户没有二开，是产品的1.20.16-lts
2、第一次 未执行是晓燕拉赵勇看的
3、客户那边的测试计划是400多个case，每个case几乎都有 1-3个前/后置SQL，客户每次都是流水线执行，出现频次已经到达一周一次了，所以不排除是api执行的问题

**Comment by fit2-zhao** [comment]
测试计划执行是走测试计划关联资源时选择的环境，你得确认这个环境是否有数据源。

**Comment by fit2-zhao** [comment]
检查一下环境的更新日志，看看那个时间点环境是否被人为调整过。

**Comment by Ycr123888** [comment]
流水线执行测试计划未选择环境
![企业微信截图_16727319972937](https://user-images.githubusercontent.com/103925124/210317742-199ef855-ce67-4798-addb-bb49cdec5f9b.png)
关联用例时选的环境和其他case一致，别得case也有前/后置SQL，可执行成功；
每次未执行的case不是同一个

**Comment by luty2018** [comment]
问题是否还存在？

**Comment by Ycr123888** [comment]
问题后来没有复现，但是一共出现了三次，用户也很想规避，关于未执行原因进行展示需求已提tapd，关闭此issue
