### ISSUE TITLE
[BUG] case中，有前后置sql，切换运行环境，case的总环境未变，二者不一致，保存后查看详情同样不一致

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20492]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.17-lt

### 使用外置数据库

否

### 问题描述

 case中，有前后置sql，切换环境，case的总环境未变，二者不一致，保存后查看详情也不一致，有些混淆

### 重现步骤

case中，有前后置sql，切换环境，case的总环境未变，二者不一致，保存后查看详情也不一致，有些混淆
![image](https://user-images.githubusercontent.com/103925124/205849503-a4472ad4-3416-47c8-951f-021df7a6b776.png)
切换1,2未变化
![image](https://user-images.githubusercontent.com/103925124/205849681-e15816be-aaa6-4b99-82b2-2957f91cfe40.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，如果多个环境中有同名数据源，切换环境会默认使用同名数据源，就是运行环境会变，但是数据源不会变

**Comment by zyyfit** [comment]
优化：测试计划里报告状态error，内容为空的问题

**Comment by zyyfit** [comment]
2.5.0版本在测试报告中会显示case执行结果，执行结果内容为空，请等待版本发布后验证
