### ISSUE TITLE
[BUG]接口定义，请求说明路径参数用#{id}描述不准确需要修改

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20491]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

定义接口这里如果是路径参数传参一般使用的${}的方式，但是这里说明是#{id}实际操作是无法传参的。描述有问题请修改

![91dc727f4f39841d7eedbd84aa4ef26](https://user-images.githubusercontent.com/43202800/205848663-b3cc7ed2-8393-4ec9-abfb-df82621ed548.png)

### 重现步骤

定义接口这里如果是路径参数传参一般使用的${}的方式，但是这里说明是#{id}实际操作是无法传参的。描述有问题请修改

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/205849187-0d21067d-8be7-4325-b208-77916718f3c6.png)
具体修改效果请找罗老师确认

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/205849345-5d4ef263-65e7-4d71-8ebe-ca751372bb93.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
已修复，2.4.2 版本（或者 2.5.0版本） 和 1.20.18版本 发布，请等待版本发布后验证
