### ISSUE TITLE
[BUG]自带的${__random()}函数中的最大最小值，不支持用前置sql中定义的列存储名变量。 

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#20499]
### 联系方式

zhangrufeng_006@163.com

### MeterSphere 版本

v1.20.15-lts

### 使用外置数据库

否

### 问题描述

自带的${__random()}函数中的最大最小值，不支持用前置sql中定义的列存储名变量。
但是在jmeter中可以使用。

### 重现步骤

背景：希望实现随机数的范围不超过我在数据库查出来的总记录数。用${__random()}这个函数，里面的最小最大值，取自前置sql中的列存储变量。
1.添加前置sql，获取列表的总记录数dict_bz_count。
2.添加前置脚本，使用${__random()}这个函数，${__Random(1,${dict_bz_count_1},sxbz_rand1)}；
3.保存运行
运行结果，一直在转圈运行。控制台没有错误提示，看不出什么问题，就是一直在转圈执行，只能手动停止。
![image](https://user-images.githubusercontent.com/100331967/206077240-53ec3c9d-2c0e-4649-94d6-f27ac0776fe2.png)

在jmeter中尝试，是可以输出结果的。
![image](https://user-images.githubusercontent.com/100331967/206077270-e7a8ffbf-2843-485a-ad39-96e84ae3946c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们使用jmeter尝试也是不行的，方便把jmx的场景发出来吗？

https://www.yingsoo.com/news/database/49104.html
ps：如上连接中所述使用${xxx_#}取值方式是获取sql语句的总记录数，不知道是否和你的场景是一个意思？

**Comment by zrf87** [comment]
不一样的，我预期的是：希望实现随机数的范围不超过我在数据库查出来的总记录数。用${__random()}这个函数，里面的最小最大值，取自前置sql中的列存储变量。

[测试随机取数2.zip](https://github.com/metersphere/metersphere/files/10184103/2.zip)

**Comment by youliyuan-fit2cloud** [comment]
你好，你这个jmx 文件场景也不是前后置脚本的方式 实现的，而且Jmeter 里面也不支持这种前后置里面列存储变量取值啊。
