### ISSUE TITLE
[BUG]接口请求后置操作提取参数时候，JSONPath的语法无效

### ISSUE THREAD

**Issue by liwanyin** [metersphere/metersphere#20508]
### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

接口请求后置操作提取参数时候，JSONPath的语法无效

### 重现步骤

1,编辑接口测试用例
2，reponse返回数组，JSONPath支持的获取数组长度length()无效

### 期待的正确结果

正确返回数组长度

### 附加信息

![图片](https://user-images.githubusercontent.com/11974866/206116312-17196aef-1775-45bc-9b4b-b52956c4bc6d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，当前系统还不支持使用 length function，对应jmeter中其实是JSON JMESPath 后置提取器，我们会考虑是否增加加。
Error processing JSON content in userGL, message: Options AS_PATH_LIST and ALWAYS_RETURN_LIST are not allowed when using path functions!Options AS_PATH_LIST and ALWAYS_RETURN_LIST are not allowed when using path functions!

**Comment by youliyuan-fit2cloud** [comment]
可以提个需求，这个先关闭了。
