### ISSUE TITLE
[BUG]UI场景支持导出，但是指令不支持导出

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#20500]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

UI场景支持导出，但是指令不支持导出

### 重现步骤

1、编辑UI测试指令
2、点击跟多操作无法导出
![image](https://user-images.githubusercontent.com/35896106/206080370-6216fb69-c28f-4254-866b-05a53483e92a.png)

**Comment by zrfit** [comment]
您好，v2.4指令不支持导出，之前版本是可以的，后续版本会再放开导出功能。
