### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 18329038106** [metersphere/metersphere#20514]
### MeterSphere 版本

版本:   v1.20.2-lts-0f489ee9

### 联系方式

微信号：JOIN1314920

### 请描述您的需求或者改进建议

遇到的问题：
1.根据metersphere的xmind模版写好用例，当用例步骤对应多条预期结果时，导人平台错乱了，无法识别步骤对应的多个预期结果。
2.metersphere平台在线编辑好的用例，1个用例步骤输入多个预期结果后，导出用例展示错乱
需求：用例步骤希望能够支持多个预期结果，目前是一个用例步骤只能支持一个预期结果

**Comment by xulinde** [comment]
经验证，v1.20.20-lts不存在此问题，建议您升级下版本
