### ISSUE TITLE
[BUG]接口断言选择文档结构校验 ，开启 跟随api 定义后，类型校验 不能开启

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#20527]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.17 & v2.4

### 使用外置数据库

否

### 问题描述

1.接口断言选择文档结构校验 ，开启 跟随api 定义后，类型校验 不能开启
![86bc2856ceda2d0bb6a4dc3cc6238c2](https://user-images.githubusercontent.com/30038088/206367177-1a23e74b-1e4e-4138-814e-10a8623ec315.png)
2. 内容校验 和 预期结果是不是也应该 可以修改？

### 重现步骤

接口调试 -> 断言规则 -> 文档格式校验

**Comment by zyyfit** [comment]
您好，感谢您的反馈，接口文档断言-跟随接口定义这里目前就是这样设计的，默认不可以编辑
