### ISSUE TITLE
[FEATURE]缺陷内容提交模板化

### ISSUE THREAD

**Issue by LonelyWarrior2023** [metersphere/metersphere#20539]
### MeterSphere 版本

2.4

### 请描述您的需求或者改进建议

建议缺陷提交时，缺陷的内容可以有一个良好的规范模板，而不是仅仅提供了一个「缺陷内容」的富文本编辑器，这无法规范测试人员规范、清晰地描述问题。
<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/117255533/206387726-1d16f65f-4f46-439a-b053-2a5a3a90478a.png">

### 请描述你建议的实现方案

建议参考MeterSphere github Issue 提交规范的模板设计
<img width="873" alt="图片" src="https://user-images.githubusercontent.com/117255533/206387971-344256b0-ef18-4744-a89d-807e5330b23e.png">

**Comment by luty2018** [comment]
这个模板是自定义的， 你可以在项目设置-模板管理里面去配置

**Comment by LonelyWarrior2023** [comment]
从产品的角度来考虑的话，默认的模版就应该提供这样的功能。
从使用者角度来看，作为用户，肯定是希望能够直接、快速、方便地使用默认的功能能够满足我的绝大部分需求。的确metersphere提供了可配置的模版能力，但默认的这个模版使用起来感觉并不是通用的。
对应用软件来说，绝大部分用户都是使用者，而不是设计者。

**Comment by luty2018** [comment]
我们没有设计默认模板，为什么会有”默认的这个模版使用起来感觉并不是通用的“这个感觉？
这里是富文本是设计就是为了去满足用户对不同用例模板的需求
