### ISSUE TITLE
[FEATURE]swagger 中可以设置和显示不同响应码对应的响应体，MS 默认只能显示 响应码是 200 的响应体

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#20531]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.17-lts & v2.4

### 使用外置数据库

否

### 问题描述

swagger 中可以设置和显示不同响应码对应的响应体，MS 默认只能显示 响应码是 200 的响应体

### 重现步骤

1.在 swagger 中设置 响应码是 400 的响应体内容，可显示出不同响应码对应的响应体
![image](https://user-images.githubusercontent.com/30038088/206370629-e81c372f-150c-440f-9d83-7fcd08e7dc14.png)

![image](https://user-images.githubusercontent.com/30038088/206370784-266841ea-d4d8-4b11-b78c-600080e777cf.png)

**Comment by luty2018** [comment]
暂不支持
