### ISSUE TITLE
metersphere 针对现在需要加密解密的接口应做兼容上传各种目录到指定工具对应目录下

### ISSUE THREAD

**Issue by lihe052g** [metersphere/metersphere#20535]
### MeterSphere 版本

2.4.0

### 联系方式

18224049088

### 请描述您的需求或者改进建议

1、场景：
我某个接口需要用jmeter脚本先初始化某个加密工具，其中需要导入包和识别bin目录下的cfg dir；其中cfg 目录需要部署在jmeter bin目录下
2、问题：
现在平台不支持dir的导入，也没法识别具体导入路径；导致加解密对应脚本无法运行

### 请描述你建议的实现方案

metersphere 针对现在需要加密解密的接口应做兼容上传各种目录到指定工具对应目录下

### 附加信息

import common.config.tools.config.ConfigTools3;
import common.web.tools.filter.crypt.ijiami.IJMTools;

ConfigTools3.load("cfg");
IJMTools.init();
注：cfg是个目录

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/206379062-b3da261a-1bcb-4cbd-8a02-ac19fad30167.png)
备注
