### ISSUE TITLE
[FEATURE]swagger json 导入后，希望json格式响应体可以自动转换为xml格式

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#20530]
### 联系方式

shenkaibo

### MeterSphere 版本

v1.20.17-lts & v2.4

### 使用外置数据库

否

### 问题描述

swagger json 导入后，xml 格式的响应结果转换失败

### 重现步骤

1.接口定义处导入 swagger json 
https://editor.swagger.io/  可以导出 swagger JSON 示例文件
2.切换 xml 格式，查看 响应体 内容，依然是 json 
![image](https://user-images.githubusercontent.com/30038088/206369725-8eb748c4-afc5-4ef2-9314-b37de8f6b05d.png)
3.swagger 可以正常查看
![image](https://user-images.githubusercontent.com/30038088/206369922-a1c4812c-e625-44fa-a0b1-64f2b5bc633d.png)

**Comment by luty2018** [comment]
我们这里切换XML和swagger是两码事。
