### ISSUE TITLE
[BUG]接口自动化中-场景状态不随着定时任务、手动执行后而改变

### ISSUE THREAD

**Issue by lxh3145** [metersphere/metersphere#2053]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.8.2

**Bug 描述**
简要描述您碰到的问题
接口自动化中-场景状态不随着定时任务、手动执行后而改变
**Bug 重现步骤**
1.  设置场景初始状态为未开始
2. 定时任务执行、手动执行
3. 查看场景状态依然为未开始
4. 

**期待的正确结果**
正确情况下应该是什么样的？
场景状态能随着执行而变

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/63571490/114958958-a8404780-9e96-11eb-896e-e8f95cfa23fc.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by xulinde** [comment]
当前状态这个字段是需要手动更新的～
