### ISSUE TITLE
[FEATURE]建议用例评审时操作进一步简化

### ISSUE THREAD

**Issue by LonelyWarrior2023** [metersphere/metersphere#20547]
### MeterSphere 版本

2.3.1

### 请描述您的需求或者改进建议

步骤执行失败后, 还需要多步点击, 才能保存结果, 效率太低。
不太明白对应的通过/失败等操作与保存的逻辑是什么？
实际操作鼠标要多次操作，太过于繁琐

<img width="416" alt="图片" src="https://user-images.githubusercontent.com/117255533/206391277-bd69da8c-0ce8-4b44-8319-16555f42c0b5.png">

### 请描述你建议的实现方案

1、点击通过/未通过直接跳转到下一条评审用例。

**Comment by luty2018** [comment]
这个我们已经在优化了哈，会尽快上线。
