### ISSUE TITLE
[BUG]未登录打开邮件链接跳转不到邮件页面

### ISSUE THREAD

**Issue by lxh3145** [metersphere/metersphere#2054]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.8.2

**Bug 描述**
简要描述您碰到的问题
点击邮箱中测试报告链接，提示用户登录，但是登录后却不能跳转到测试报告位置，只能进入主页

**Bug 重现步骤**
1.  设置定时任务执行发邮件
2. 点击邮件中测试报告链接
3. 提示登录 ，输入账号密码，提交后进入主页
4. 

**期待的正确结果**
正确情况下应该是什么样的？
bug重现步骤第三步后应该直接跳转到邮件位置

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本优化这个问题
