### ISSUE TITLE
[FEATURE]用例可以批量新增、替换标签，但是不能批量。功能缺失

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20554]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

用例可以批量新增、替换标签，但是不能批量。使用场景有所缺失 希望能加上

![用例可以批量新增、替换标签，但是不能批量](https://user-images.githubusercontent.com/43202800/206406479-626b2f49-dea4-4be0-9cf2-2b3547feab6b.png)
![Uploading 期望在编辑的时候可以回填历史标签、.png…]()

### 重现步骤

操作：功能用例列表选择用例，批量修改 -标签。此处可以新增标签、替换原有标签，但是不能删除 功能缺失

### 期待的正确结果

期望在编辑的时候可以回填历史标签、这样可以选择删除

![期望在编辑的时候可以回填历史标签、](https://user-images.githubusercontent.com/43202800/206406783-8ec43bb6-032d-4e52-9e9b-eb3948355d01.png)

**Comment by luty2018** [comment]
暂不支持
