### ISSUE TITLE
[BUG]接口自动化场景编辑自动保存

### ISSUE THREAD

**Issue by LonelyWarrior2023** [metersphere/metersphere#20550]
### MeterSphere 版本

2.4

### 请描述您的需求或者改进建议

编辑接口自动化场景时, 点击其他模块页面，比如「测试跟踪/UI测试等」, 原本编辑的内容没有自动保存，也没有提示保存，所有修改内容丢失，降低了工作效率。

### 请描述你建议的实现方案

建议增加自动保存到草稿或者跳转其他页面时提示保存或自动保存

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉长时间未反馈，目前我们编辑页面在关闭时会有未保存提示，考虑到前后端实现和系统性能不会做自动保存。感谢您的理解和支持。
