### ISSUE TITLE
[BUG]测试跟踪-缺陷缺陷，无法正常收到消息通知

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#20552]
### 联系方式

张树彬

### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

消息通知里对缺陷管理设置“更新”提醒，通知人为创建人和处理人，通知类型为站内信和邮件，均未收到消息通知提醒。

### 重现步骤

1. 项目设置-消息通知，对测试跟踪-缺陷设置通知，事件类型为“更新”，接收人为“创建人、处理人”，接收方式分别设置了邮件和站内信
2. 对已存在的缺陷点击编辑，任意更改字段内容，点击保存
3. 创建人和处理人的站内信以及邮件均未收到通知

### 期待的正确结果

能够按消息设置正确的收到通知提醒

**Comment by zyyfit** [comment]
您好，没有复现这个问题，创建人和处理人，邮件和站内信都收到了通知
![image](https://user-images.githubusercontent.com/73461316/207481361-894bccb6-02c3-4088-a7a2-2760bb98fb56.png)
![image](https://user-images.githubusercontent.com/73461316/207481443-d499ccd0-d510-4a77-bbce-f397dbbc7d57.png)
![image](https://user-images.githubusercontent.com/73461316/207481584-dae10406-b80a-49bf-bdf0-918fd48efd89.png)
