### ISSUE TITLE
[FEATURE]场景自动化调试界面改为tab方式

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2055]
**请描述您的需求或者改进建议.**
最大化调试的时候；改为tab方式展示调试结果；和控制台信息
第一个tab是编辑页面；第二个tab是测试报告页面；第三个tab显示日志页面

现在是调试完了有问题；要去改的时候调试日志就看不到了；要想想办法复制出来然后再去看

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后面版本看下能否优化

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/115516358-9e647d00-a2b8-11eb-8082-293aaea2a91f.png)
