### ISSUE TITLE
[BUG]测试跟踪-功能用例列表，全选所有用例后，再将部分用例取消勾选，点击批量删除后，仍会删除所有用例

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#20553]
### 联系方式

张树彬

### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例列表，全选所有用例后，再将部分用例取消勾选，点击批量删除后，仍会删除所有用例

### 重现步骤

1. 功能用例列表，勾选全部（全选所有数据，第一个选项）
2. 将其中部分用例取消勾选
3. 点击...里的批量删除
4. 仍然把所有用例都删掉了

### 期待的正确结果

取消勾选的用例，不应该删除

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/206402724-be7eae4f-c794-48aa-8e43-60f76211ebe7.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复。
