### ISSUE TITLE
[BUG]缺陷根据模板导入，缺陷ID重复

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#20568]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

缺陷根据模板导入，缺陷ID出现重复
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/46042812/206478746-b18480bb-66fd-46a1-985a-77c90c8c4d49.png">

### 重现步骤

1、缺陷管理-导入缺陷，将其它平台的导出的缺陷按照 MeterSphere 缺陷模板进行编辑
2、导入缺陷后发现缺陷ID出现多个重复

### 期待的正确结果

缺陷ID自增长，且不重复

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复。
