### ISSUE TITLE
[BUG]MS平台v2.0.1来对接禅道12.5，17.7 ，不加http://ip/zentao接口可以返回正常，加了之后就返回异常了，根据官方提示所有参数都已配置完成，还是接口异常

### ISSUE THREAD

**Issue by fupengfei12** [metersphere/metersphere#20561]
### 联系方式

腾生满山

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

我用平台2.01来对接禅道12.5，17.7 ，不加http://ip/zentao接口可以返回正常，加了之后就返回异常了，根据官方提示所有参数都已配置完成，还是接口异常
![image](https://user-images.githubusercontent.com/88263911/206418726-1d490b03-e4bd-4813-87ad-c6755592cc3f.png)
![image](https://user-images.githubusercontent.com/88263911/206418836-e0538f64-a480-4648-810a-cb7a30e1d005.png)
![Uploading image.png…]()

### 重现步骤

![image](https://user-images.githubusercontent.com/88263911/206418436-2eaf4b85-cb5b-402d-b5df-b4b62cc5aded.png)

### 期待的正确结果

希望尽快修复

**Comment by youliyuan-fit2cloud** [comment]
你好，没有理解您的意思，不加什么可以返回正常？指：$config->features->apiGetModel    = true; 这个配置加上之后不正常了？
禅道 12.5和17.7 版本都不行？禅道是企业版还是开源版的 ？

也可以参考如下官网操作步骤配置：
https://metersphere.io/docs/v2.x/tutorial/MeterSphere%20%E6%9C%8D%E5%8A%A1%E9%9B%86%E6%88%90%E4%B9%8B%E7%A6%85%E9%81%93%E5%AF%B9%E6%8E%A5/?h=%E7%A6%85%E9%81%93

1.【修改禅道配置】配置文件路径：/opt/zbox/app/zentao/config/my.php，修改 $config->requestType = 'PATH_INFO' 或 'GET'，重启禅道/opt/zbox/zbox restart
2.【修改MS配置】在“系统设置-工作空间-服务集成-禅道”配置页面，选择请求方式为'PATH_INFO' 或 'GET'
