### ISSUE TITLE
[BUG]测试跟踪-功能用例-回收站列表，全选所有用例后，再将部分用例取消勾选，点击恢复后，仍会恢复所有用例

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#20565]
### 联系方式

张树彬

### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

测试跟踪-功能用例-回收站列表，全选所有用例后，再将部分用例取消勾选，点击恢复后，仍会恢复所有用例

### 重现步骤

1. 功能用例回收站列表，勾选全部（全选所有数据，第一个选项）
2. 将其中部分用例取消勾选
3. 点击...里的恢复
4. 仍然把所有用例都恢复了

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复。
