### ISSUE TITLE
[BUG]登录后点击「关于」查看系统版本信息，显示错误版本信息-1.0.1

### ISSUE THREAD

**Issue by LonelyWarrior2023** [metersphere/metersphere#20569]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

系统版本信息错误
<img width="1162" alt="图片" src="https://user-images.githubusercontent.com/117255533/206481719-8a115fbb-404e-4058-824b-fb985910818e.png">

### 重现步骤

不太好重现，感觉像是获取版本号失败之后，设置了一个初始值

重新登录后又正常

**Comment by youliyuan-fit2cloud** [comment]
你好，全新安装的环境？打开的时候服务是否都是正常 状态？

**Comment by LonelyWarrior2023** [comment]
非全新安装，并且从正常逻辑上来说，是否全新安装，和这个缺陷来说应该没有关系。
能正常登录，能够打开页面，能够点击关于来查看版本信息那就说明服务是正常状态。
反过来，如果服务异常，那也不能说明显示一个错误的版本信息的处理是理所应当的。
有图就说明这个事实是存在的，从目前已有的信息（版本显示了1.0.1），看看对应的代码和逻辑，排查很难么?

**Comment by youliyuan-fit2cloud** [comment]
> 非全新安装，并且从正常逻辑上来说，是否全新安装，和这个缺陷来说应该没有关系。 能正常登录，能够打开页面，能够点击关于来查看版本信息那就说明服务是正常状态。 反过来，如果服务异常，那也不能说明显示一个错误的版本信息的处理是理所应当的。 有图就说明这个事实是存在的，从目前已有的信息（版本显示了1.0.1），看看对应的代码和逻辑，排查很难么?


1 .如果是你自己打包安装的会有种情况，就是没有用我们的github 安装包方式安装。
2.截图中的当前站点url地址也是空的。

ps：不知道你遇到了什么事，这种语气让我们很难理解。。。我们也是在尽力排查问题。但是好像觉得耽误你的时间了，抱歉，我们能力有限。只能帮你到这里了。
