### ISSUE TITLE
[BUG]测试跟踪-首页，用例责任人分布数据错误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#20567]
### 联系方式

张树彬

### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

测试跟踪-首页，用例责任人分布数据错误，功能用例和关联用例字段数据与实际不符

### 重现步骤

1. 测试跟踪-功能用例列表中的用例数量
2. 测试跟踪-首页，用例责任人分布国表中，功能用例和关联用例字段数据
3. 1和2步骤的数据不符
4. 截图为功能用例数的示例，关联用例数也不正确，可以验证一下

### 期待的正确结果

测试跟踪-首页，用例责任人分布国表中正确显示用例数量

### 附加信息

![1670510891179](https://user-images.githubusercontent.com/77324661/206477403-deed47f3-ac2b-471a-9d17-11aa12d3aba8.jpg)
![1670510978191](https://user-images.githubusercontent.com/77324661/206477433-88646d92-3d46-41e4-b843-7913dd6deb4d.jpg)

**Comment by xulinde** [comment]
v2.7.0已修复～
