### ISSUE TITLE
[BUG]2.4.1msctl uninstall+msctl reload服务全部healthy登录测试跟踪首页报错

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20576]
### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

msctl uninstall+msctl reload服务全部healthy登录测试跟踪首页报错
从2.3.0开始基本这样

### 重现步骤

1、msctl uninstall、
2、msctl reload
3、msctl status服务全部healthy
4、登录测试跟踪首页报错

### 期待的正确结果

你看看那个pending 那个是账户相关的信息都加载那么慢么

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/206645442-fa48214c-934c-4706-a64e-4c16df058630.png)

![image](https://user-images.githubusercontent.com/19423100/206645515-66d707d8-8a97-4e21-92cc-b45c39ed57f1.png)

![image](https://user-images.githubusercontent.com/19423100/206645690-ec03287c-c629-4cc5-9679-1e98fa3b56d9.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，看着是服务挂了额，检查下每个容器（对应各个功能模块）的yml 文件默认内存配置是不是还是初始的配置？如果是根据服务器配置改大一些，记得你们家服务器配置挺高的 （～～）。

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/206822437-6b3a9596-199a-4299-b30e-852d60ecc8fe.png)
![image](https://user-images.githubusercontent.com/19423100/206822475-5f8d7ab1-c538-4abf-96a7-6ade9e782d34.png)

**Comment by legend818** [comment]
基本上每次升级我都会手动调高

**Comment by AgAngle** [comment]
你好，请问，你的环境数据量大概是什么量级，这个项目下的数据量和整体数据量大致有多少；具体有哪些接口报错，可能需要针对性的优化下性能

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/207201358-47cd5a95-362c-4ab1-8879-eb460950430b.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/207201460-6c9b0bbf-9e84-4e76-9beb-0b382630d8bf.png)
