### ISSUE TITLE
[FEATURE]增加用例列表调整顺序需求

### ISSUE THREAD

**Issue by SeptemberCai** [metersphere/metersphere#20574]
### MeterSphere 版本

v1.20.13-lts-4e5c1d1c

### 联系方式

交流群5 Ami.

### 请描述您的需求或者改进建议

用例列表新增调整用例顺序的功能

**Comment by luty2018** [comment]
现在可以拖拽进行排序。

**Comment by SeptemberCai** [comment]
请问确定是我提到的版本可以进行拖拽操作吗？我这边操作是不行的
