### ISSUE TITLE
[FEATURE]响应体不支持全屏,响应数据unicode

### ISSUE THREAD

**Issue by hanchenglong001** [metersphere/metersphere#20575]
### MeterSphere 版本

v1.20.16-lts

### 联系方式

微信交流群53 all 　　　 　 　　 　👁_👁　: 

### 请描述您的需求或者改进建议

响应体支持全屏。或者可以支持拖拽.响应数据unicode转一下码.

### 请描述你建议的实现方案

响应体没有多是时候不方便查看。需要复制出来。 响应中unicode无法转码

### 附加信息

![4d326eb961f50f768194b5976bf2c38](https://user-images.githubusercontent.com/56539098/206642018-215f792d-ee04-4f5d-aca9-50604531fb92.png)

**Comment by luty2018** [comment]
收到， 我们下一步交互升级会优化这里。

**Comment by hanchenglong001** [comment]
@luty2018 这个什么时候优化啊
