### ISSUE TITLE
接口场景测试 JSON请求体中 json数组中的mock函数无效

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#20570]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

目前使用MS的接口场景中，当接口步骤请求体为JSON格式时，单个JSON体中的mock函数可以生效，当为JSON数组时mock函数不生效
单个JSON体，mock生效：
<img width="1166" alt="截屏2022-12-09 上午10 26 19" src="https://user-images.githubusercontent.com/34637801/206610111-6c9ec020-15a3-43be-83ee-b72e415bcfd7.png">
JSON数组，mock不生效：
<img width="901" alt="截屏2022-12-09 上午10 26 38" src="https://user-images.githubusercontent.com/34637801/206610154-a18cccae-757a-45bb-baf1-9edbaad6f08d.png">

### 重现步骤

1.场景一个场景
2.选择一个自定义接口作为场景步骤
3.分别使用单个JSON体和JSON数组作为请求体，均包含mock函数

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.5.1版本已修复，请等待版本发布后验证
