### ISSUE TITLE
[BUG] 接口定义里面，请求体，一键展开不生效

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20572]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33945037/206614672-2f39b98b-f7f4-45c8-b048-afcb87e7f1f7.png)

1. 问题： 一键展开按钮不生效。
2. 页面优化：全部字段尽可能在一个页面展示，不出现下面的拖拽条。

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
1.一键展开是针对root下节点的子节点展开的
2.目前不能手动调整，即使后端改了默认宽度，参数多了的话还是会遇到这个情况，效果不明显。暂时不做修改。

**Comment by hao65103940** [comment]
第一点是个问题，按钮点击不生效。
第二点希望以后会考虑。

**Comment by youliyuan-fit2cloud** [comment]
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/54612864/206903556-6c845cff-3550-41d3-a3a8-eda21c9c90da.png">

第二点请转需求。

**Comment by hao65103940** [comment]
![image](https://user-images.githubusercontent.com/33945037/210056837-bda473d0-da20-45d9-97f7-a0d8c2ad7967.png)

**Comment by youliyuan-fit2cloud** [comment]
> 

说过了额，是root下面的子节点才支持展开，你这是root下面的字符串参数，实现和需求不一致请转需求吧。
