### ISSUE TITLE
[BUG]v2.4.1 性能测试上传dcm文件，服务器minio路径中文件存在，发起压测生成的Jmeter容器中文件不存

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#20578]
### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

v2.4.1 性能测试上传dcm文件，服务器minio路径中文件存在，发起压测生成的Jmeter容器中文件不存在

### 重现步骤

1、新建性能测试任务，上传jmx脚本，相关jar包以及dcm数据文件，保存压测开始执行（此处dcm文件不会在文件列表中显示，如下截图，已提交关联bug：20557）
![image](https://user-images.githubusercontent.com/5198427/206652912-1bc6929e-a283-4d51-8299-2769971adbd5.png)

2、登录部署MS的服务器，检查上传的文件是否正常上传到平台所在服务器，如下所示，可以看到dcm文件已经上传到服务器
![image](https://user-images.githubusercontent.com/5198427/206653034-3a2f9c28-7ab4-467e-9e6b-2457f4f344cf.png)

3、开始执行压测，在Jmeter容器中检查文件是否存在
![image](https://user-images.githubusercontent.com/5198427/206653298-a37e9b3d-8151-4ebc-9d5b-e40734c5cad4.png)

4、Jmeter容器中dcm文件不存在
![image](https://user-images.githubusercontent.com/5198427/206653518-7eb62067-6f06-45a2-ac0a-b5ea9c4914c0.png)

5、MS平台中log也显示没有找到dcm文件
![image](https://user-images.githubusercontent.com/5198427/206653755-4a9f552e-c374-42a6-b3c9-8bdf5fca7d7b.png)

### 期待的正确结果

1、性能测试dcm文件上传能在列表中正常显示，且性能测试能正常运行

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个版本修复。

**Comment by liuruibin** [comment]
在性能测试报告页面里下载执行文件zip看看文件是否包含在内

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复该问题。
