### ISSUE TITLE
[BUG]JMX脚本里的同步定时器在MS平台不生效。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20582]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

JMX脚本里有同步定时器，在JMeter平台运行时，等到启动指定用户数时，才开始发送请求。将JMX脚本上传到MS平台性能测试页面，运行时，用户数没有达到指定的用户数，请求就已全部发送完毕，由此可见，同步定时器并没有发挥作用。

### 重现步骤

1. 将 JMX 脚本上传到性能测试页面，设置压力并发数为50，Ramp-up 为5，迭代次数为 1,
![image](https://user-images.githubusercontent.com/104960608/206666404-e59476ae-f805-4250-a334-bdecac1a44d2.png)

2. 点击保存并执行测试，最终运行结果可看到，用户数没有达到设置的50，而是38，请求已结束。
![image](https://user-images.githubusercontent.com/104960608/206666659-9c2248f6-d877-41c1-aa8c-70a84e08200f.png)

3. JMX 脚本里有个同步定时器，可直接放到JMeter进行测试，可看到等用户数都启动到指定数据时才开始跑请求

[HTTP请求.zip](https://github.com/metersphere/metersphere/files/10193424/HTTP.zip)

**Comment by liuruibin** [comment]
overview这个是测试开始后线程数的峰值，50线程数迭代一次共50次，你可以从jmeter.log中看出
![image](https://user-images.githubusercontent.com/23045261/206893038-581668d1-645b-4e73-b8ef-b26d922fbab9.png)

![image](https://user-images.githubusercontent.com/23045261/206893463-02d48e57-c201-4ee9-be88-63415140be42.png)


反复执行发现
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/23045261/206893302-ce834fe4-45d4-45ee-bd97-95b0d3a1130b.png">
