### ISSUE TITLE
[BUG]接口定义-CASE处，选择某一版本所有数据批量执行，其他版本的CASE也执行了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20584]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口定义-CASE处，选择某一版本所有数据，批量执行，测试报告中显示的是所有版本的CASE用例也执行了。

### 重现步骤

1. 接口定义-CASE处，有两个版本-V1.0.0和V2.4版本，V1.0.0版本CASE有269条数据，V2.4版本就一条CASE数据
![1670580877390](https://user-images.githubusercontent.com/104960608/206678970-6fa3a583-8fff-478a-bc85-957cc2e3bb8e.jpg)
![image](https://user-images.githubusercontent.com/104960608/206679134-6ff044f6-f3a8-4a74-a3de-57915ec62caa.png)

2. 在V1.0.0版本，点击所有可见数据（共269条）后，点击批量执行
![1670581015008](https://user-images.githubusercontent.com/104960608/206679909-6f7a6c4e-fa34-4d07-9b68-b197cae8ab92.jpg)

3. 在测试报告中执行的数据共270条，包括V2.4版本的一条数据
![image](https://user-images.githubusercontent.com/104960608/206680086-a3c655da-c62c-4dcd-8a9d-3173b8a5c6bc.png)

![1670581309628](https://user-images.githubusercontent.com/104960608/206680680-f3ececfd-253b-441b-9c95-e7cbeb951b18.jpg)

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复。
