### ISSUE TITLE
[BUG]v1.20.16-lts 接口场景配置钉钉消息  执行后 钉钉没有收到消息

### ISSUE THREAD

**Issue by jialiangding** [metersphere/metersphere#20583]
### MeterSphere 版本

   v1.20.16-lts-3bb3478d

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/20794765/206675496-73f3f090-1495-4654-b2be-06d8eab05d5f.png)
场景下配置的钉钉通知不生效
项目下消息设置中的钉钉配置可以生效

### 重现步骤

场景下配置的钉钉通知不生效
项目下消息设置中的钉钉配置可以生效

### 期待的正确结果

场景下配置的钉钉通知生效

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，
请确认以下几个问题：
1.接收人这里设置如果和消息通知是同一个人，请检查一下dingding 的webhook地址粘贴的是否正确；如果不是同一人，请确认这个接收人是否在 dingding通知群里面。
2.定时任务是否设置成功，接口测试-测试报告列表中有执行这个定时任务报告吗？
以上都不是，建议升级到最新的1.20.17-lst版本。
