### ISSUE TITLE
[BUG]文件管理相关的三个问题

### ISSUE THREAD

**Issue by flint9ban** [metersphere/metersphere#20581]
### 联系方式

15967122137

### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

问题1：
场景变量文件我用了“关联文件”，平时测试需要删除并重新上传，实际文件名没变，下面脚本也能正常读取，但是场景变量配置的地方显示“源文件已删除”，且没法预览
问题2：文件管理页面，新建子模块后刷新，子模块消失
问题3：保存场景1时，切换到另一场景2，另一场景名字会变成之前保存的场景名1

### 重现步骤

问题1：
场景变量文件我用了“关联文件”，平时测试需要删除并重新上传，实际文件名没变，下面脚本也能正常读取，但是场景变量配置的地方显示“源文件已删除”，且没法预览
问题2：文件管理页面，新建子模块后刷新，子模块消失
问题3：保存场景1时，快速切换到另一场景2，另一场景名字会变成之前保存的场景名1

**Comment by flint9ban** [comment]
MeterSphere 交流群28
小房子
xiesichao0613@163.com

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，问题1和问题2在新版本中已解决。
问题3没有复现，必现的方法是？
