### ISSUE TITLE
[BUG]接口导出Swagger格式，再Swagger格式导入，响应内容中的状态码显示不正确

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20586]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

接口导出Swagger格式，再Swagger格式导入，响应内容中的状态码显示不正确

### 重现步骤

1.通过Swagger官网导入接口，状态码描述显示如下
![image](https://user-images.githubusercontent.com/103627487/206684964-b07f03ad-428c-47d5-b929-a4b7ac9cfd8f.png)
2.导出接口Swagger格式
![image](https://user-images.githubusercontent.com/103627487/206685164-5e5a682d-356c-422f-9f7d-6325e755355d.png)
3.将导出的Swagger json文件导入ms,响应内容中的状态码显示不正确
![image](https://user-images.githubusercontent.com/103627487/206686107-d0225d8f-a018-4ccd-bd2d-9a14d4e53799.png)
4.查看导出的json文件，response显示的不正确
![image](https://user-images.githubusercontent.com/103627487/206685439-5dbaa6e9-cb3b-432a-a4a4-b78575417a47.png)
5.Swagger edit验证导出的json文件格式也错误
![image](https://user-images.githubusercontent.com/103627487/206685707-cc3d01fe-c898-4f4f-9dad-d36fde9238ba.png)

### 期待的正确结果

期望状态码能正常显示，与Swagger 官网导入后一致，

**Comment by youliyuan-fit2cloud** [comment]
已修复，请关注发布的v1.20.18-lts.
