### ISSUE TITLE
[FEATURE]全局断言的合理性欠缺

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20599]
### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

全局断言的合理性欠缺

### 重现步骤

1、接口测试设置了全局断言
2、ms是平台化产品，部分接口存在一些差异性，但是因为使用了全局断言，导致断言失败

### 期待的正确结果

在case上面设置不使用全局断言的开关，这样特殊的case使用case本身的断言

**Comment by luty2018** [comment]
感谢建议， 我们规划一下。

**Comment by legend818** [comment]
罗姐姐 这个你们不要pack了哦，实用性功能。不然这个产品的平台化价值不大了

**Comment by legend818** [comment]
个人感觉这个建议比误报库实用性更强一些

**Comment by luty2018** [comment]
已经规划了。开源版。

**Comment by legend818** [comment]
这个功能现在是咋实现的？？？？

**Comment by luty2018** [comment]
v3.0 版本哈

**Comment by legend818** [comment]
已经安装3.0 等待3.X   实现

**Comment by luty2018** [comment]
> 已经安装3.0 等待3.X 实现

3.0已经实现了哦，全局断言默认开启，关闭就行。
![image](https://github.com/metersphere/metersphere/assets/36292514/603ee290-735c-4931-9f06-7d37548c2a92)
