### ISSUE TITLE
[BUG]v2.4.1, 测试计划执行完成后，在测试跟踪》报告页面，报告依然显示Running，同时列表页成功率显示不准

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#20591]
### 联系方式

王进

### MeterSphere 版本

v.2.4.1

### 使用外置数据库

是

### 问题描述

v2.4.1, 测试计划执行完成后，在测试跟踪》报告页面，报告依然显示Running，同时列表页成功率显示不准

### 重现步骤

1. 客户这边升级到2.4.1后
2. 触发之前的测试计划执行
3. 接口测试的测试计划，执行率是100%，执行完成后 在测试跟踪》报告页面，报告依然显示Running，
详细报告内容里所有接口用例，场景用例都是PASS的，执行结束时间没有
![1670677510623](https://user-images.githubusercontent.com/76033005/206856616-54849b5b-ff82-46cb-bf9e-7643bb22edd6.png)
报告列表页，报告执行率是100%，但是还是显示running状态
![1670677540639](https://user-images.githubusercontent.com/76033005/206856644-f3ba4018-2fb6-4381-9d87-fe75ace7f137.png)

5. UI自动化的测试计划，执行率是100%，通过率89.4% ，但是列表显示 100%。

![1670677324262](https://user-images.githubusercontent.com/76033005/206856475-a3f30be9-5943-4cae-8206-3a67693366ae.png)
列表页显示成功率100%，但是报告里通过率89.4%。
![1670677363973](https://user-images.githubusercontent.com/76033005/206856512-51cf6ab0-1c29-46aa-873e-477229b1c12b.png)

**Comment by youliyuan-fit2cloud** [comment]
问题1：测试报告状态是running问题没有复现，测试环境将继续观察看看。请将客户环境的日志发过来吧。
问题2: 通过率不一致问题是已知bug，待修复中。

**Comment by legend818** [comment]
v2.4.1, 测试计划执行完成后，在测试跟踪》报告页面，报告依然显示Running，同时列表页成功率显示不准 ====我表示我有相同问题
