### ISSUE TITLE
[BUG]使用上传文件接口进行文件上传，执行提示文件路径找不到

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#20590]
### 联系方式

18259175411

### MeterSphere 版本

v2.1.0-rx

### 使用外置数据库

否

### 问题描述

上传文件接口，在场景中进行文件上传，执行的时候提示文件路径不存在，执行文件的地址是/opt/metersphere/data/body/xxxxx-xxx-xxx-xxxx/file.txt  XXXX-XXX-XXX-XXXX是metersphere平台自动生成的临时文件，由于没生成才导致执行接口失败。该问题为概率性事件，10次大概3次

### 重现步骤

使用有文件上传的接口，用form-data数据类型进行文件上传，多执行几次，会出现文件路径找不到的报错

### 附加信息

![629fd764529c677d559aa5c49d4980e](https://user-images.githubusercontent.com/120242714/206839521-d41947f5-f162-4bff-8590-64f26c49f529.jpg)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，升级到较新版本试试呢？
