### ISSUE TITLE
[BUG]接口自动化--设置参数批量导入，执行时，参数应该是换行了导致执行时参数错误

### ISSUE THREAD

**Issue by wuyezhao** [metersphere/metersphere#20598]
### 联系方式

475443417@qq.com

### MeterSphere 版本

1.20.17

### 使用外置数据库

否

### 问题描述

在1.20.17版本上，接口自动化--设置参数批量导入时，当我参数是一行一条数据，比如abc=123第二行是bcd=234直接放入到ms上，ms执行时，参数应该是换行了导致执行时参数错误，只能一个一个复制粘贴参数

### 重现步骤

在MS系统上，参数  批量导入 ，执行会报错，原因是比如(form-data格式类型)：
abc=234
bcd=456
cde=456
这种类型的参数导入进去执行会换行，导致报错，麻烦修复

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，可能是因为和你的测试场景不一致。请详细说明下你的场景，最好也 截图信息。
