### ISSUE TITLE
[BUG]自动化测试中引用的场景，无法修改场景设置了

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#20592]
### MeterSphere 版本

2.2.1

### 使用外置数据库

否

### 问题描述

自动化测试中引用的场景，无法修改场景设置了，之前的版本是可以自行修改场景设置中的选项

### 重现步骤

自动化测试中，添加引用场景，选择该引用点击场景设置，无法修改

### 期待的正确结果

引用时可以修改场景设置中的选项

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/206941630-8a9a3d4e-655c-4746-9f82-0f33719e52c1.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个bug在新版本中已经解决，考虑下是否升级到新版本。
