### ISSUE TITLE
[BUG]调试最大化显示异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2060]
**MeterSphere 版本**
1.8.2

**Bug 描述**
最大化后显示不能在左边
![image](https://user-images.githubusercontent.com/5517369/114964828-12121e80-9ea2-11eb-8e9a-9872b8292ed2.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是不是在展开之前有打开f12开发调试工具之类的？刷新页面再试一下呢？

**Comment by guhan121** [comment]
@zyyfit 我应该是在浏览器全屏前打开了全屏界面；然后他不能自适应了‘’

**Comment by zyyfit** [comment]
> @zyyfit 我应该是在浏览器全屏前打开了全屏界面；然后他不能自适应了‘’

好的，感谢反馈，会在后续版本优化这个问题的

**Comment by zyyfit** [comment]
最新版已修复
