### ISSUE TITLE
[BUG]接口自动化点击调试按钮时会自动跳转到登录页面

### ISSUE THREAD

**Issue by heyuan1233** [metersphere/metersphere#20600]
### 联系方式

a18318462900@163.com

### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口自动化点击调试按钮时会自动跳转到登录页面

### 重现步骤

接口自动化场景编辑时点击调试按钮时会自动跳转到登录页面

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是必现的吗？能详细描述一下具体操作步骤吗？
