### ISSUE TITLE
[BUG]  插件管理 有删除权限，无删除按钮，不能删除

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20616]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.4.1

### 使用外置数据库

否

### 问题描述

插件管理 有删除权限，无删除按钮，不能删除

### 重现步骤

上传插件，websock和mqtt插件无删除按钮
![image](https://user-images.githubusercontent.com/103925124/207216276-22d4bd6e-6be2-4afd-a01b-66037f7283f0.png)

### 期待的正确结果

插件管理 有删除权限，无删除按钮，不能删除

**Comment by youliyuan-fit2cloud** [comment]
你好，mqtt和websocket的插件版本和当前MS版本使用的不一致，请确认一下插件版本。

**Comment by Ycr123888** [comment]
![4ad725a7a8534c4c15f83028554d3e5](https://user-images.githubusercontent.com/103925124/207284420-c559740f-9fdd-4d52-9236-e1869627d9d5.jpg)
一个2.4环境的ms，已导入如上插件，然后升级到2.4.1，就会如上图，没有删除按钮
