### ISSUE TITLE
[BUG]IDEA v1.0.2的版本导入，提示导入成功，在MeterSphere 的操作日志记录也显示导入成功，但是页面没有显示导入的接口

### ISSUE THREAD

**Issue by shiyi1002** [metersphere/metersphere#20614]
### 联系方式

13670145155@163.com

### MeterSphere 版本

v1.0.2  idea 2021.3

### 使用外置数据库

否

### 问题描述

用v1.2.1的版本导入接口到meterPhere,报错：Export  to MeterSphere fail!null .
换成了v1.0.2的版本导入，提示导入成功，在MeterSphere 的操作日志记录也显示导入成功，但是页面没有显示导入的接口

### 重现步骤

用v1.2.1的版本导入接口到meterPhere,报错：Export  to MeterSphere fail!null .
换成了v1.0.2的版本导入，提示导入成功，在MeterSphere 的操作日志记录也显示导入成功，但是页面没有显示导入的接口

### 期待的正确结果

希望正常导入

**Comment by youliyuan-fit2cloud** [comment]
你好，MeterSphere是哪个版本？

**Comment by shiyi1002** [comment]
> 你好，MeterSphere是哪个版本？

1.0.2

**Comment by shiyi1002** [comment]
> > 你好，MeterSphere是哪个版本？
> 
> 1.0.2

idea插件版本是1.0.2，meterShpere版本是v1.2.0,后面把idea插件版本换成1.2.0，就报错：Export to MeterSphere fail!null

**Comment by zyyfit** [comment]
您好，我这边没有复现这个问题，再确认一下，metersphere是 1.20 版本吗？还是 metersphere 1.2.0 版本呢？如果是1.20.x的话，建议您把metersphere升级到最新版试试，或者插件卸载后重新安装一下。1.2.0的metersphere是在是太早了。
另外，现在插件的最新版是1.2.1了，在idea插件市场中直接搜索安装就可以。
