### ISSUE TITLE
[BUG]接口mock后置脚本中无法提取请求变量

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#20629]
### MeterSphere 版本

2.4.1

### 使用外置数据库

否

### 问题描述

添加接口创建mock，提取请求参数，调用mock地址，后台报错，同样的mock内容在2.2.1中是好的，更新后出现此问题

### 重现步骤

添加接口创建mock，提取请求参数，调用mock地址，后台报错，同样的mock内容在2.2.1中是好的，更新后出现此问题

### 期待的正确结果

正常返回提取数据

### 附加信息

调用内容![image](https://user-images.githubusercontent.com/40912823/207486090-a0e33356-5e54-4a27-8d66-536e53364848.png)
mock内容
![image](https://user-images.githubusercontent.com/40912823/207486224-26b6eb5c-0d7d-4e7c-8376-1af6d46b909a.png)
后台报错
![image](https://user-images.githubusercontent.com/40912823/207486367-4fd3b8b1-8f0c-4c53-80bf-1f9bac311813.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.5.0版本已修复，请等待版本发布后验证
