### ISSUE TITLE
[BUG] 自定义设置功能用例模板字段为“多值输入框” ，然后通过excel导入，页面展示有问题

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20627]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

1. 功能用例添加自定义字段，选择字段类型为“多值输入框”
![image](https://user-images.githubusercontent.com/33945037/207347643-61fb8e43-cc8e-466b-a396-21d741bfa662.png)
2.  导出用例，并勾选自定义字段
![image](https://user-images.githubusercontent.com/33945037/207348515-39fdae5e-d958-4a63-bc69-3edf6e565f7b.png)
3. 照着excel模板填写新的用例数据，导入。
![image](https://user-images.githubusercontent.com/33945037/207349432-e5610ba3-8b2f-4e0f-bde0-8417b78872bd.png)
4. 用“多值输入框”字段解析展示错误
![image](https://user-images.githubusercontent.com/33945037/207349679-273faab5-1bcb-43bb-8e83-6b9fcf64e165.png)

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
v2.5.1中已修复。
