### ISSUE TITLE
[QUESTION]【性能测试模块】如何删除上传的历史文件

### ISSUE THREAD

**Issue by tody0330** [metersphere/metersphere#2063]
**请描述您的问题.**

是否可以通过数据库删除历史上传的问题，删除后是否会对平台有影响？
能否提供具体哪个表，或者提供其他删除方法

**Comment by xulinde** [comment]
系统设置-项目管理-项目-操作-资源文件，可以进行删除

**Comment by guhan121** [comment]
@tody0330 我是强撸代码创造临时文件 
搞完重启容器啥都没了
