### ISSUE TITLE
[BUG] 无痕浏览器打开MS，用例列表出现页面错乱的情况

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#20631]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.4.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/33945037/207487980-501839e7-b013-4701-9ffe-4ec74a8cf413.png)

无痕浏览器打开用例列表出现的，刷新之后还是不行。

### 重现步骤

同上

**Comment by xulinde** [comment]
可以描述下稳定复现的步骤吗？
