### ISSUE TITLE
[BUG]脑图拷贝后，会拷贝很多奇怪的数据

### ISSUE THREAD

**Issue by libb-test123** [metersphere/metersphere#20632]
### 联系方式

MeterSphere 交流群2    .cn

### MeterSphere 版本

v1.20.13-lts-b1

### 使用外置数据库

否

### 问题描述

拷贝某一个木块的所有脑图用例，粘贴到另一个模块下，会出现很多非该模块的数据

### 重现步骤

1，点击全部用例，鼠标左键点击全部用例 模块，control-c
![image](https://user-images.githubusercontent.com/67257251/207489248-4e26af55-7f74-47cd-95f1-02db6cdafb91.png)
2，选择另一个模块拷贝
![image](https://user-images.githubusercontent.com/67257251/207489403-5ebd960d-3797-4bb3-8ff6-76a35933a15a.png)
3，展开 未规划用例模块，再点击teset模块
![image](https://user-images.githubusercontent.com/67257251/207489568-85c0ff3c-89d9-408b-9f62-88e13da7e03b.png)
结果：
复制的teset模块不应该出现用例的，因为它只是个空的文件夹
备注：复制全部用例的时候不要展开子模块的用例，这样问题才能复现

### 期待的正确结果

按照每个子模块自有的用例复制，不会复制别的模块用例

**Comment by xulinde** [comment]
使用v1.20.13-lts未复现该问题，建议您升级下版本

**Comment by libb-test123** [comment]
我就是用v1.20.13-lts 发现的问题，必现的。  你复现的时候， 复制的用例不要先展开，展开后再复制就是正确的了。

**Comment by xulinde** [comment]
v1.20.18-lts已修复～
