### ISSUE TITLE
[BUG]文件管理上传的文件再后台被存成文件夹。

### ISSUE THREAD

**Issue by zhangchaolei** [metersphere/metersphere#20658]
### MeterSphere 版本

2.3.0

### 使用外置数据库

否

### 问题描述

上传的jpg文件：
![image](https://user-images.githubusercontent.com/29458304/207537616-b3f1a163-69d7-4c96-9943-5df478f4703a.png)

后台看到的是一个文件夹：
![image](https://user-images.githubusercontent.com/29458304/207537961-f1c245bb-538c-4839-a7da-5edc53145679.png)

### 重现步骤

从【项目设置】-【文件管理】上传文件

### 期待的正确结果

文件即文件不要变成其他

**Comment by zyyfit** [comment]
您好，如果您看的是 /opt/metersphere/data/minio/metersphere/ 这个文件夹下的内容，这里是采用minio分片存储的，就是这样的
