### ISSUE TITLE
[BUG]通过测试计划的链接URL进入测试计划，计划的所属项目和计划名称显示不正确

### ISSUE THREAD

**Issue by Rick469** [metersphere/metersphere#20653]
### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

通过测试计划的链接URL进入测试计划，计划的所属项目和计划名称显示不正确

### 重现步骤

1、复制一测试计划URL链接地址
2、粘贴到一个已打开MeterSphere项目的窗口地址中，且复制的测试计划不属于该项目
3、粘贴后打开测试计划，查看左侧项目显示仍为原项目名，而非当前测试计划所属项目；计划名文本框显示为空

### 期待的正确结果

粘贴后打开测试计划，查看左侧项目显示当前测试计划所属项目；计划名文本框显示当前测试计划名

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.5.0版本已修复，请等待版本发布后验证

**Comment by Ycr123888** [comment]
1.20.17-lts此问题也是必现，麻烦修复下@zyyfit

**Comment by Ycr123888** [comment]
1.20.17-lts此问题也是必现，麻烦修复下@luty2018

**Comment by zyyfit** [comment]
1.20.18版本也已修复，请等待版本发布后验证
