### ISSUE TITLE
[BUG]测试跟踪中功能测试用例模块，通过批量编辑修改用例等级，修改后在高级搜索按用例等级进行查询，无法查询到正确的结果。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#20669]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.3.1

### 使用外置数据库

否

### 问题描述

测试跟踪中功能测试用例模块，通过批量编辑修改用例等级
![image](https://user-images.githubusercontent.com/83771182/207550320-27873ac4-2bd6-4daa-861d-629e76b2feb9.png)
修改后在高级搜索按用例等级进行查询
<img width="960" alt="1671008110802" src="https://user-images.githubusercontent.com/83771182/207550542-1abd1404-f159-4c18-8dc2-e1c405217e8a.png">
无法查询到正确的结果。
<img width="960" alt="1671008118948" src="https://user-images.githubusercontent.com/83771182/207550606-940d921a-dd3d-4d2d-9d15-fd7b38602257.png">

### 重现步骤

通过批量编辑修改用例等级，修改后在高级搜索按用例等级进行查询

### 期待的正确结果

查询到正确的结果。

### 相关日志输出

```shell
无
```

**Comment by xulinde** [comment]
v2.5.0已修复～
