### ISSUE TITLE
[BUG]使用定时任务执行测试计划中的接口测试，报未找到执行的JMX文件错误，不使用定时任务手动执行则没有问题。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#20686]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.4.1

### 使用外置数据库

否

### 问题描述

使用定时任务执行测试计划中的接口测试，报未找到执行的JMX文件错误，不使用定时任务手动执行则没有问题。
![d5f7a9b53337982f295f9c45534e37c](https://user-images.githubusercontent.com/83771182/207765592-ef95a447-482f-4fff-baf5-09e6329b9bb9.png)
定时任务的资源池使用的local
![c5fcaa7e26fe61119cdde621ac44a38](https://user-images.githubusercontent.com/83771182/207765632-6be4ab29-f985-46c9-9bd8-161af84c02a0.png)
日志见附件

### 重现步骤

使用定时任务执行测试计划中的接口测试

### 期待的正确结果

定时任务测试计划可正常执行

### 相关日志输出

```shell
日志见附件
```

### 附加信息

[ms-jmeter-run.log](https://github.com/metersphere/metersphere/files/10233496/ms-jmeter-run.log)
[ms-jmeter-run-log.log](https://github.com/metersphere/metersphere/files/10233497/ms-jmeter-run-log.log)

**Comment by zyyfit** [comment]
待确认是不是当前站点配置问题
