### ISSUE TITLE
[FEATURE]压测报告中增加执行压测时的配置信息展示

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#207]
**请描述您的需求或者改进建议.**
压测报告中，没写显示相应的压测配置，报告多了就分不清了.
比如同样的测试场景下第一次压测是配置的是10个用户，产出报告，然后修改了并发用户配置。

**请描述你建议的实现方案**
在压测报告中加入本次压测的配置说明。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
