### ISSUE TITLE
[QUESTION]关于平滑升级的事

### ISSUE THREAD

**Issue by bingosam** [metersphere/metersphere#20706]
### 请描述您的问题

当前msctl没法达到平滑升级，有没有相应的办法可以实现平滑升级？

**Comment by bingosam** [comment]
> 麻烦描述你对“平滑升级”的预期

因业务需要，会对程序进行二开。目前是打包重建docker镜像后，执行msctl reload实现升级。
此时会先停止旧的容器再启新容器，所以希望可以”平滑升级“

**Comment by luty2018** [comment]
暂时无法支持呢
