### ISSUE TITLE
[BUG]MOCK的接口有问号就无法识别到请求的内容

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#20719]
### MeterSphere 版本

 v2.4.1-e4d11ddc

### 使用外置数据库

否

### 问题描述

MOCK 的接口之前是可以正常识别到请求内容然后返回对应的数据的，但是现在获取不到变量，内部的脚本未做任何更改

### 重现步骤

一个根据请求内容返回对应的结果的MOCK接口进行调用

### 附加信息

![image](https://user-images.githubusercontent.com/26948634/208004334-1fbdb718-a9a4-46d4-a073-fa46bcc479f1.png)

**Comment by Xin7S** [comment]
![image](https://user-images.githubusercontent.com/26948634/208334507-4fba2bd1-ab6b-42ad-9c35-1baa6a583a09.png)
后置脚本内容:
var jsonParam = vars.get("body.json");
JSONObject jsonObject = JSONObject.parseObject(jsonParam);
var orderId=jsonObject.getJSONArray("rows").getJSONObject(0).getString("orderId");
vars.put("ORDERID",orderId.toString());
var storeCode=jsonObject.getJSONArray("rows").getJSONObject(0).getString("storeCode");
var whouse=jsonObject.getJSONArray("rows").getJSONObject(0).getString("whouse");
if(storeCode.equals("1006")&&whouse.equals("D305"))
{
    vars.put("FLAG","F");
	vars.put("MSG","天猫旗舰店D305MOCK会返回截停失败");
}
else if(storeCode.equals("1584")&&whouse.equals("D303"))
{
    vars.put("FLAG","F");
	vars.put("MSG","天猫旗舰店D303MOCK会返回截停失败");
}
else
{
    vars.put("FLAG","T");
	vars.put("MSG","成功");
}

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
定位到问题了，计划2.6版本修复

**Comment by zyyfit** [comment]
2.6.0版本已修复，请等待版本发布后验证
