### ISSUE TITLE
[BUG]UI测试文件上传当文件名为中文时，使用后端模式执行截图中文乱码

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#20724]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

UI测试文件上传当文件名为中文时，使用后端模式执行截图中文乱码

### 重现步骤

1、上传文件到文件管理，文件名为中文
![image](https://user-images.githubusercontent.com/35896106/208016609-1ac9bd31-483c-464f-b16d-9bfcc9416778.png)
2、使用上传控件，将文件添加进来，设置步骤截图
![image](https://user-images.githubusercontent.com/35896106/208016379-61b9edb7-d711-4b49-aded-a48a507fa9ff.png)
3、使用后端模式执行，查看截图结果
![image](https://user-images.githubusercontent.com/35896106/208018009-6b27278b-e396-4247-b7fd-97a6925549ec.png)

### 期待的正确结果

中文显示

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。
