### ISSUE TITLE
[BUG]接口测试-测试报告-场景测试报告导出的PDF文件查看时比较模糊

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#20738]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

当接口自动化场景步骤较多时（50+），测试完成后导出的PDF测试报告比较模糊

### 重现步骤

当接口自动化场景步骤较多时（50+），测试完成后导出的PDF测试报告比较模糊

### 期待的正确结果

导出的PDF测试报告文件应该是清晰的，易识别的
一般不会随着测试报告数据量（接口测试步骤）的多少而发生变化

### 附加信息

步骤少的时候（自己测试的15个步骤）是正常
1.20 lts正常

**Comment by youliyuan-fit2cloud** [comment]
v2.5.0中已修复。

**Comment by Andyguo5891** [comment]
奈斯~
