### ISSUE TITLE
[FEATURE]编写case时，期待光标放在标签上有弹窗显示标签详情

### ISSUE THREAD

**Issue by chunThree** [metersphere/metersphere#20737]
### MeterSphere 版本

 v2.4.0-165ceb

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/110656536/208047075-8bd70dca-dcfb-4daf-80f0-7dc35674ad96.png)

期待光标放在标签上有弹窗，显示标签详情

**Comment by luty2018** [comment]
感谢建议， 我们尽快安排。
