### ISSUE TITLE
[BUG]删除用户后，用户执行的性能测试报告不展示了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#20773]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

删除用户后，用户执行的性能测试报告不展示了，实际上数据库还有数据。跟产品确认了，删除用户后，该用户的报告也应该保留展示。

### 重现步骤

1.创建用户test
2.使用test用户登录，创建接口自动化场景，将场景转为性能测试，执行生成性能测试报告
3.切换到admin用户，将test用户删除
4.结果test用户执行的性能测试报告不展示了，数据库里还是有数据的
![image](https://user-images.githubusercontent.com/88763608/208339417-edaba7b5-25b0-4c9c-8401-3abcedbaef50.png)
![image](https://user-images.githubusercontent.com/88763608/208339447-794a9ddb-f242-4913-ae2b-cff738784c4d.png)

### 期待的正确结果

删除用户后，用户执行的性能测试报告应该要展示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
