### ISSUE TITLE
[BUG]接口返回数据被转义掉了,11182806.22757142被转义成1.1182806227571424E7

### ISSUE THREAD

**Issue by houpandeng111** [metersphere/metersphere#20780]
### 联系方式

微信asd8554

### MeterSphere 版本

版本:   v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

接口返回数据被转义了
![880f209da62564de2d683309efe7e62](https://user-images.githubusercontent.com/58907057/208365656-c364b609-3fbb-4271-960b-14b50f82b27e.png)

![a7d9da7eae0de8d1d84257a4a0b04fe](https://user-images.githubusercontent.com/58907057/208365939-92f21c52-4653-47b7-8d40-41cbb9543a9a.png)

### 重现步骤

1

### 期待的正确结果

1

### 相关日志输出

```shell
1
```

### 附加信息

1

**Comment by zyyfit** [comment]
您好，最新版2.4.1版本没有复现这个问题，请升级试试
![image](https://user-images.githubusercontent.com/73461316/208651382-31c73dfa-a354-4f6a-8564-b34ae921c963.png)
