### ISSUE TITLE
[FEATURE]引用下的场景能够快速跳转

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#20793]
### MeterSphere 版本

2.4.1

### 请描述您的需求或者改进建议

接口自动化中引用场景现阶段只有最外层的引用能够直接跳转到场景进行编辑，下级还是引用场景的时候无法直接进行跳转，调试修改时需要一层层进入不是很方便。

### 请描述你建议的实现方案

下级引用场景也能够直接跳转进行编辑

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/208394408-9cbf09b7-0cf3-40d5-8968-72a9e529c2b5.png)

**Comment by luty2018** [comment]
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/36292514/209086201-17a2a5c3-8d5f-463a-840c-78e20d3ee905.png">
这里可以新开网页打开引用的场景

**Comment by wszbc** [comment]
不是这个意思新开没什么问题，我的意思是比如场景a下面有引用b，b下面有引用c，c下面有引用d，那么你在a场景只能，先打开b，b再打开c，c再打开d，我想是不是直接在a场景就能打开d 要方便的多了
