### ISSUE TITLE
[BUG]导入Swagger 3.0接口文档，接口导入成功，但是接口的请求体格式为raw的参数导入失败

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#20792]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v1.20.17-lts&v2.2.0

### 使用外置数据库

否

### 问题描述

导入Swagger 3.0接口文档，接口导入成功，但是接口的请求体参数导入失败，请求体格式为raw，详细请看截图

### 重现步骤

1、准备一个Swagger 3.0接口文档，里边包含一个或多个请求体为raw格式的接口
2、把文档导入MS
3、查看raw格式的请求体参数是否导入成功

### 期待的正确结果

参数正常导入

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/208392645-7744048d-f4fb-48c3-8aba-e937f6af42c6.png)
![image](https://user-images.githubusercontent.com/45786766/208392919-6b4d91d8-fb9f-48f9-b3a6-0df2ef708bc4.png)

**Comment by heyuehua** [comment]
麻烦使用这个文件看一下
[openapi - 副本.txt](https://github.com/metersphere/metersphere/files/10311866/openapi.-.txt)

**Comment by zyyfit** [comment]
好的，这个文件能复现

**Comment by zyyfit** [comment]
2.5.1版本已修复，请等待版本发布后验证
