### ISSUE TITLE
[FEATURE]希望能增加执行sql的支持

### ISSUE THREAD

**Issue by kaixinbaba** [metersphere/metersphere#208]
**请描述您的需求或者改进建议.**
通常接口测试或者回归测试都需要后台是有数据的，所以希望可以通过上传sql脚本的方式去统一管理，整个测试周期中用到的数据，每次测试链开始都需要把数据重置一遍，这样测试的过程就会稳定，而不用担心是脏数据导致的测试失败，通过上传sql脚本的方式把构建数据的责任丢给使用者，平台就无需过于关注了，当然配套的还有管理数据源的功能（不仅仅是传统的数据库，mysql，oracle等，最好还要考虑mongodb这类新型的数据库，因为现在的公司一般都会有多种数据库）

**请描述你建议的实现方案**
数据管理也是一类权限，控制台可以提供上传的功能，并在创建的测试中有选项可以选择对应的脚本以及执行的环境，这样每次一个测试链都可以从最干净的源数据开始了。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
