### ISSUE TITLE
[BUG]测试跟踪-缺陷管理-缺陷-附件 pdf文件无法预览

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#20811]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

缺陷管理中附件对于pdf文件无法预览。

### 重现步骤

1、创建缺陷
2、在其它信息-附件中上传一个pdf文件
3、点击该文件条目的预览按钮，弹出一空白预览窗口，一直在转圈，没有预览内容。

### 期待的正确结果

期望该pdf文件可以预览。

图片预览可以，但pdf无法预览，而且对于不可预览的文件（例如：txt文件）屏蔽了预览按钮，但是对于pdf文件预览按钮还是enable的。从设计的期望上来说，应该是可以对pdf文件进行预览，但实际上不行。

### 附加信息

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/46042812/208571386-5f6119ae-e8e6-4050-8451-4634db061785.png">

**Comment by xulinde** [comment]
v2.7.0已修复～
