### ISSUE TITLE
[BUG]测试跟踪-缺陷管理-缺陷/缺陷描述的富文本编辑控件的编辑/预览控制逻辑不一致

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#20820]
### MeterSphere 版本

2.4

### 使用外置数据库

否

### 问题描述

1、测试跟踪-缺陷管理-缺陷/缺陷描述的富文本框的编辑/预览控制不符合逻辑，鼠标在富文本框的外部点击操作还会影响富文本框的编辑/预览状态，而且这样的操作偶尔还会出现鼠标漂移的现象。
2、手工点击富文本框的编辑/预览控制，进入预览状态，这时鼠标在富文本框的外部点击不会影响富文本框状态， 并且鼠标点击富文本框内部，无法自动切换到编辑状态。

### 重现步骤

1、测试跟踪-缺陷管理-缺陷/缺陷描述
2、在富文本控件中编辑文本并插入图片
3、鼠标在富文本控件的左侧多次点击
4、富文本控件的编辑/预览会进行切换
Q1: 并不是界外的每一次鼠标点击都会导致富文本控件进入预览状态，即如果富文本控件失去焦点后就是预览状态，那么应该是每一次失去焦点都是预览状态，而不是有时是，而有时又不是。

5、手动点击富文本控件的编辑/预览按钮，让富文本控件进入预览模式
6、再次执行鼠标在富文本控件的左侧多次点击——富文件控件无法自动进入编辑模式
7、执行鼠标在富文本控件在内部点击——富文件控件也无法自动进入编辑模式
Q2:自动和手动切换编辑/预览状态，后面的状态变更逻辑不一样，即无论自动还是手动切换到预览状态，之后鼠标在富文本控件在内部点击就应该进入编辑状态。

### 期待的正确结果

富文本控件的编辑/预览的切换保持逻辑上的一致。

**Comment by xulinde** [comment]
你好，这个控件的逻辑是，从光标输入状态失去焦点会变成预览状态，不是整个控件失去焦点，示例如下
下图是光标输入状态，失去焦点会变成预览模式
![image](https://user-images.githubusercontent.com/64065190/221772196-5e1f42f9-8db8-4a36-bed9-b1ea57213cc5.png)
下图是处于编辑状态，但是没有光标，则不会变成预览状态
![image](https://user-images.githubusercontent.com/64065190/221772230-ab0e1ce8-1936-4b84-a4ad-316bcc732ea4.png)
