### ISSUE TITLE
[BUG]批量添加参数，请求内容出现多余换行现象

### ISSUE THREAD

**Issue by maizi007** [metersphere/metersphere#20853]
### 联系方式

wlee.007@163.com

### MeterSphere 版本

v1.20.17-lts-c59a4086

### 使用外置数据库

否

### 问题描述

批量添加参数，请求之后请求内容参数后面会多个换行，导致请求参数异常。
对表单中输入的参数值重新编辑下后正常

### 重现步骤

![image](https://user-images.githubusercontent.com/121150194/208830899-4c934218-db0e-4fc2-bb20-4edcd6075089.png)
![image](https://user-images.githubusercontent.com/121150194/208831015-217c3f30-1c38-477b-9eb4-34d0847a97b5.png)

### 期待的正确结果

批量导入参数不出现多余的换行

**Comment by zyyfit** [comment]
您好，请问批量添加的时候是手动输入的还是从其他文件或者编辑器中复制的呢？如果是复制的，可能会复制到不显示的换行符号，导致带着换行

**Comment by maizi007** [comment]
是复制的，这个可以优化吗？自动去掉结尾的换行符

**Comment by zyyfit** [comment]
> 是复制的，这个可以优化吗？自动去掉结尾的换行符

这个考虑到有的用户可能需要带换行符的情况，自动去掉后用户不能手动添加，我们这边决定保留这个功能，就麻烦您手动去掉一下了

**Comment by maizi007** [comment]
好的，我看主要原因是windows和linux换行符引起，转成LF就没这个问题
