### ISSUE TITLE
[BUG]接口case的更新人显示不正确

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#20861]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.17-lts

### 使用外置数据库

否

### 问题描述

接口case的更新人显示不正确

### 重现步骤

1.admin用户创建一个接口case
2.切换用户，修改case
3.查看case更新人和变更历史，两个地方不一致
<img width="953" alt="e41eee87b8b5cf3971a12127a53dcc9" src="https://user-images.githubusercontent.com/88763608/208846231-9e9282bf-abf3-4155-b739-af38dbdbefc7.png">

### 期待的正确结果

应该保持一致

**Comment by zyyfit** [comment]
这里是显示有点问题，刷新一下就更新过来了，后续版本修复

**Comment by zyyfit** [comment]
1.20.18版本 和 2.5.0版本已修复，请等待版本发布后验证

**Comment by linfengjjj** [comment]
已验证，已解决
