### ISSUE TITLE
[BUG] 【报表统计】报表展示数值重叠，导出后缺少图表

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#20870]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.4

### 使用外置数据库

否

### 问题描述

【报表统计】报表展示数值重叠，导出后缺少图表

### 重现步骤

报表展示数值重叠
![image](https://user-images.githubusercontent.com/103925124/208859288-39a23cd9-9a3d-487b-9fa7-8cb3ed47eb77.png)
导出后缺少图表
![image](https://user-images.githubusercontent.com/103925124/208859936-31fa84d6-c3eb-4d9b-837b-13e06a2c1aad.png)
![image](https://user-images.githubusercontent.com/103925124/208860065-7980e251-6df5-4423-b192-65b035d8b54c.png)
如导出不好修改，建议修改为竖屏展示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by luty2018** [comment]
后续版本报表会借助DataEase实现。
