### ISSUE TITLE
[FEATURE]项目环境-环境配置：建议【通用配置】可以按分类显示，或支持拖拽。

### ISSUE THREAD

**Issue by 15068870403** [metersphere/metersphere#20873]
### MeterSphere 版本

V2.3.1

### 联系方式

微信：MetersPhere交流群40  ；邮箱15068870403@139.com

### 请描述您的需求或者改进建议

[项目环境-环境配置：建议【通用配置】可以按分类显示，或支持拖拽。
当目前通用配置定义的通用参数比较多时，没用上述功能支持，很不方便查看

**Comment by luty2018** [comment]
请问你说的分类是哪些？
