### ISSUE TITLE
[FEATURE]新建工作空间，将项目a的case及接口场景导入项目b，希望场景中关联接口时优先关联当前项目的接口

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20875]
### MeterSphere 版本

  v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

新建工作空间，将项目a的case及接口场景导入项目b，此时查看接口场景 里面引用的接口case不是当前项目的 ，而是原来项目的

### 重现步骤

1、新建一个工作空间b ,并再空间下新建一个项目
2、将工作空间项目a的接口case  及引用了这个case的场景导出， 并导入到空间b下的项目去

问题： 此时修改工作空间b 下面的接口case 参数， 接口场景的case不会变化；;若切换到工作空间a去修改这个case  接口场景的case参数会更着变

此处：创建新项目应用的不是当前项目的case 而是用的原项目的，无法达到数据迁移和快速复制到其它项目的
![1004af2761e3d4d14b6402f9d1c565e](https://user-images.githubusercontent.com/43202800/208881152-dee877b6-dc1a-4c8a-86be-0e860b5ca1ac.png)

### 期待的正确结果

case导入新的工作空间后，引用关系应该优先引用当前项目的case

**Comment by zyyfit** [comment]
您好，目前是这样设计的，会在系统里自动寻找当前用户有权限的接口关联，但是关联顺序不能保证

**Comment by xhy12** [comment]
正友说这里当时做导入导出的需求就是为了快速实现项目迁移，目前做不到项目层面的这种迁移效果。能不能补齐相关能力呢？

**Comment by luty2018** [comment]
已经线下讨论过，无法支持。
