### ISSUE TITLE
[BUG] [UI测试]-资源不释放-内存溢出

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#20871]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.2.1

### 使用外置数据库

是

### 问题描述

这是企业客户的一个问题，他们主要做的是UI测试，客户部署机器内存是16G，自从升级到V2.2.1版本，使用内存会不停得增加，最后把16G内存都消耗完，平台没有做测试内存也不会释放，

### 重现步骤

客户环境可以复现

### 期待的正确结果

UI测试完资源能释放，内存不出现异常

### 附加信息

<img width="732" alt="6b545217e7119e59e31f77258dde539" src="https://user-images.githubusercontent.com/45531073/208860654-d528fa52-ad02-47e9-b5de-129c862208b7.png">
![image](https://user-images.githubusercontent.com/45531073/208861862-dd231a96-5b25-494d-a62b-526e38dc60ad.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、v2.3.0版本对UI性能做了整体优化调整，对并发线程和资源分配都有优化。
2、最新版本未复现该问题。
3、建议升级至最新版本后尝试。
