### ISSUE TITLE
[BUG]接口自动化中，条件控制器达到条件了，却不执行里面的接口

### ISSUE THREAD

**Issue by 15068870403** [metersphere/metersphere#20872]
### 联系方式

微信：MetersPhere交流群40  ；邮箱15068870403@139.com

### MeterSphere 版本

V2.3.1

### 使用外置数据库

否

### 问题描述

MS的接口自动化中，在上一个接口返回的响应体中提取了字段var，然后把var中包含的内容作为判断条件，已经达到条件了，条件控制器里面的步骤不执行

### 重现步骤

MS的接口自动化中，在上一个接口返回的响应体中提取了字段var，然后把var中包含的内容作为判断条件，已经达到条件了，条件控制器里面的步骤不执行

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，建议您升级试试
![image](https://user-images.githubusercontent.com/73461316/209051150-7826db4a-590c-455f-ba10-cc27fdd8c2b0.png)
