### ISSUE TITLE
[BUG]报告链接点击跳转后，没有跳转到对应的项目

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#20887]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

在不同的项目，报告链接点击跳转后，没有跳转到对应的项目

### 重现步骤

1. 测试计划-报告列表页，F12找到报告id, 目前项目在 meijie 项目
![image](https://user-images.githubusercontent.com/103627487/209069821-fbc14398-52d1-4680-857c-2efb1358edb5.png)
2. 拼接链接 https://north-ms.fit2cloud.com/#/track/testPlan/reportList?resourceId=28128aa4-899c-495d-95fc-04fc3cc844da
3. 切换到另一个项目
![image](https://user-images.githubusercontent.com/103627487/209070509-0c59e67d-5e70-406c-8e72-d409fd677421.png)
4. 地址栏输入链接，报告正常展示，
![image](https://user-images.githubusercontent.com/103627487/209070766-cbdba6d6-7c9e-4ecc-8a3f-d016a7cc5280.png)
5.点击跳转，未跳转到对应的项目
![image](https://user-images.githubusercontent.com/103627487/209070980-d2daa6a4-0363-4732-a66e-901b502e7865.png)

### 期待的正确结果

期望能跳转到对应的项目，模块回显正确

**Comment by youliyuan-fit2cloud** [comment]
v1.20.18-lts中已修复，请升级一下吧。
