### ISSUE TITLE
[BUG]系统设置-编辑已存在的资源池-修改Port-限制不能超过9999

### ISSUE THREAD

**Issue by fengyubiao** [metersphere/metersphere#209]
**MeterSphere 版本**
1.1

**Bug 描述**
自定义启动node-controller-1.1，设置端口号为16004，在资源池修改端口号大于9999，无法修改为16004
系统设置-编辑已存在的资源池-修改Port-限制不能超过9999

**Bug 重现步骤**
1.  自定义启动node-controller-1.1，$JAVA_HOME/bin/java -Dfile.encoding=utf-8 -Dserver.port=16004-jar node-controller-1.1.jar
2. 登录平台，进入系统设置-编辑已存在的资源池-修改Port-限制不能超过9999

**期待的正确结果**
增大端口配置许可范围

**截图**
![图片](https://user-images.githubusercontent.com/6871534/89507155-b5347380-d7fe-11ea-9477-a6ecc475df59.png)

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 1.1
> 
> **Bug 描述**
> 自定义启动node-controller-1.1，设置端口号为16004，在资源池修改端口号大于9999，无法修改为16004
> 系统设置-编辑已存在的资源池-修改Port-限制不能超过9999
> 
> **Bug 重现步骤**
> 
> 1. 自定义启动node-controller-1.1，$JAVA_HOME/bin/java -Dfile.encoding=utf-8 -Dserver.port=16004-jar node-controller-1.1.jar
> 2. 登录平台，进入系统设置-编辑已存在的资源池-修改Port-限制不能超过9999
> 
> **期待的正确结果**
> 增大端口配置许可范围
> 
> **截图**
> ![图片](https://user-images.githubusercontent.com/6871534/89507155-b5347380-d7fe-11ea-9477-a6ecc475df59.png)

1.1.2版本 今晚修复发布哈
