### ISSUE TITLE
接口场景中了两个同级别的循环控制器，参数引用错误

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#20919]
### MeterSphere 版本

v1.20.17lts

### 使用外置数据库

否

### 问题描述

问题现象：
在接口自动化场景中使用两
个CSV场景变量，同时使用同级两个循环控制器，第一个循环控制器选择循环一次，第二个控制器选择循环控制一次，执行后，发现第二个循环控制器中读取CSV中的变量是从第二个CSV中读取第二行。
<img width="972" alt="截屏2022-12-23 下午7 05 02" src="https://user-images.githubusercontent.com/34637801/209325243-ed86e6b3-5fad-49c5-85c2-102e0852a6c3.png">
<img width="1281" alt="截屏2022-12-23 下午7 03 19" src="https://user-images.githubusercontent.com/34637801/209325021-ff633f73-1462-402a-80d9-b6bf577f4807.png">
<img width="1375" alt="截屏2022-12-23 下午7 03 34" src="https://user-images.githubusercontent.com/34637801/209325053-ac02cc33-e59c-43ae-9b40-d42d6aec232e.png">
<img width="1412" alt="截屏2022-12-23 下午7 04 23" src="https://user-images.githubusercontent.com/34637801/209325168-cacbfdab-ed94-4bc2-97e5-0b772443b738.png">

### 重现步骤

1.准备两个CSV文件，分别在里面设置一个参数，多行值
2.创建一个接口自动化场景
3.在场景变量中创建两个CSV变量。
4.在接口自动化场景中创建两个循环控制器
5.在循环控制器中创建一个自定义请求，同时分别创建一个前置脚本，分别打印对应的CSV变量值
6.执行场景

**Comment by zyyfit** [comment]
您好，由于目前场景中的csv变量设计的存放位置问题，导致取值会从第二个开始取，这是个历史遗留问题，目前暂时没有好的优化方案
