### ISSUE TITLE
[FEATURE]接口测试jsonpath断言希望支持过滤表达式写法

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#20912]
### MeterSphere 版本

v1.20.17-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

当返回数据有多条，希望断言其中某一条数据时，这时会用到jsonpaht过滤表达式断言，如$.store.book[?(@.category=='reference')].title  等于 "Sayings of the Century"
目前ms不支持这种写法，但这样写法很实用也很常见，希望能支持。https://www.cnblogs.com/FBGG/p/15116491.html

**Comment by luty2018** [comment]
这个可以支持，已添加规划
