### ISSUE TITLE
metersphere做性能测试时，不能显示完整的报错信息，只显示错误率，对排查错误没什么帮助，或者我没找到相关设置？

### ISSUE THREAD

**Issue by qiuquanzhi** [metersphere/metersphere#2093]

**Comment by zyyfit** [comment]
您好，可以看一下性能测试报告页面 的日志详情里有没有您想要的信息

**Comment by qiuquanzhi** [comment]
没有

发自我的iPhone

**Comment by qiuquanzhi** [comment]
没有，就是没有才问你们的，就是比如发生错误的时候，不能显示完整的报错信息，不好排查问题！




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Apr 19, 2021 10:57 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [metersphere/metersphere] metersphere做性能测试时，不能显示完整的报错信息，只显示错误率，对排查错误没什么帮助，或者我没找到相关设置？ (#2093)





 
您好，可以看一下性能测试报告页面 的日志详情里有没有您想要的信息

**Comment by qiuquanzhi** [comment]
这个可以写beanshell来输出日志。
