### ISSUE TITLE
[BUG] 接口测试 函数助手保存函数失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20967]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

接口测试 函数助手保存函数失败

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/209630916-96ac6a92-dc28-4f3b-b40e-53cc77fd35ef.png)
![image](https://user-images.githubusercontent.com/103925124/209630857-dc761bcc-7b4b-4b9e-bbb0-126d4913ddb0.png)

### 期待的正确结果

可正常保存

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by Ycr123888** [comment]
2.5.1版本metersphere已修复
