### ISSUE TITLE
[BUG] 接口列表版本筛选后，左侧模块用例数显示错误

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#20968]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

接口列表版本筛选后，左侧模块用例数显示错误

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/209634028-2fb4ee4c-0e5b-4440-83d8-1b7f47978ef5.png)
![image](https://user-images.githubusercontent.com/103925124/209633807-aa3594b2-267c-41c0-8ed4-186978ed0531.png)

**Comment by zyyfit** [comment]
您好，感谢您的反馈，本次搜索模块树显示问题仅针对右上角简单搜索框，不包括高级搜索和版本搜索
