### ISSUE TITLE
[BUG] 升级到2.4.1 后 /project/list 查询接口不支持参数过滤

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#20961]
### MeterSphere 版本

2.4.1

### 使用外置数据库

否

### 问题描述

在issue #14443 中，已经实现了“项目管理查询接口优化支持第三方平台项目参数JiraKey, ZendaoId...等, 来进行过滤” 。但是在升级到2.4.1后，发现这样的API查询过滤已经不生效了，原因可能是在配置jira集成后，没像以前那样将jirakey写入原来设计的字段中，见下图。
![image](https://user-images.githubusercontent.com/24548477/209614715-cd2392e8-4b57-489e-a4e2-1ca386fee992.png)

参见issue #14443中的实现的效果：支持在API查询时，在请求body中指定jirakey，而能够将对应的ms project查询出来，这对于跨系统间的集成非常重要。API接口应该前后兼容，要不然就破坏了原来的集成机制，也给用户带来困扰。

https://github.com/metersphere/metersphere/issues/14443
![image](https://user-images.githubusercontent.com/24548477/209614572-29c465b0-b836-4e52-8229-05cff808dc99.png)

附参考的请求body：
{
    "workspaceId": "8e9afc41-14a1-11ed-a123-0242ac1e0a02",
    "filters": {
        "jira_key": [
            "JIRAKEY"
        ]
    }
}

### 重现步骤

1. 配置JIRA集成，并与项目关联
2. 创建API调用请求，设置请求头
  
![image](https://user-images.githubusercontent.com/24548477/209615100-4ac98fa7-4d2a-4f64-a4cb-dd3b9530a5b4.png)

3. 设置请求参数
![image](https://user-images.githubusercontent.com/24548477/209615191-de61c8da-7df4-4dca-b210-830448a30b64.png)

4. 设置请求题
![image](https://user-images.githubusercontent.com/24548477/209615272-5dc95e24-f0ae-4091-8900-3eda62fca1e4.png)

### 期待的正确结果

期望：返回指定jirakey的MS project

**Comment by Ycr123888** [comment]
![image](https://user-images.githubusercontent.com/103925124/209616781-8ba2efb0-08d9-46e6-b630-5a7c115cd7a8.png)
建议方案：在project中可新增project_key字段，用来存储各大三方平台的项目key，列表检索SQL也可通过这个路径，实现对三方项目key的检索

**Comment by xyziven** [comment]
参考复现步骤

**Comment by xyziven** [comment]
或者，是否可以考虑将   tapdId/jiraKey/zentaoId/azureDevopsId   统一成thirdPlatformId，这样字段也精简且通用。

**Comment by zyyfit** [comment]
您好，我这边是可以正常查询的
![image](https://user-images.githubusercontent.com/73461316/209753167-fefc5744-efde-412d-b02c-a81451ab9833.png)
![image](https://user-images.githubusercontent.com/73461316/209753232-43a07302-d4dd-439b-9ad9-36264201500e.png)

**Comment by xyziven** [comment]
嗯，在v2.5.0验证了，又可以了。多谢！

**Comment by xyziven** [comment]
刚才验证错了。2.5.0也存在该问题：
当在2.5.0里新建集成的时候，新集成的项目并不会写到jirakey里，因此也查不出来。
如果是之前集成好的，因为jirakey有值，可以查询出来。
所以问题的本质不是查询，而是在创建项目集成时，新的版本并不会给jiraKey字段赋值。

**Comment by zyyfit** [comment]
哦哦，知道了，后续版本修复

**Comment by xyziven** [comment]
感谢！等2.6.0的时候我再验证一下。

**Comment by zyyfit** [comment]
> 感谢！等2.6.0的时候我再验证一下。

已经修复了这个bug，2.6.0没有赶上，如果2.6发小版本的话可以在2.6.1验证，或者2.7.0
