### ISSUE TITLE
[BUG]接口中JOSN格式的数据请求中的:被系统替换成了=号

### ISSUE THREAD

**Issue by Xin7S** [metersphere/metersphere#20973]
### MeterSphere 版本

v2.5.0-1e7e6908

### 使用外置数据库

否

### 问题描述

请求json结构的数据，不打开JSON-SCHEMA开关时，请求内容中的:在发送时被替换成为了=,导致接口无法使用
![ae1f692fd2ae7489cd5866885710a3b8](https://user-images.githubusercontent.com/26948634/209638615-88681bb4-cbd9-42c1-b8cd-7fa2b4bd240e.png)

### 重现步骤

使用标准json请求体，不打开JSON-SCHEMA开关时，发送请求

### 期待的正确结果

不用打开JSON-SCHEMA开关，也能正确发送请求内容 ，在此版本之前都是正常的

![image](https://user-images.githubusercontent.com/26948634/209639281-8c4bbb45-bcd0-409f-866d-15574c522dd2.png)

**Comment by xulinde** [comment]
未复现该问题，方便把接口导出，在我们环境复现下吗？

**Comment by xulinde** [comment]
v2.5.1已修复，建议您升级下版本～
