### ISSUE TITLE
[BUG] 接口自动化-场景引用 ：优先使用当前场景变量开关，自定义脚本设置的变量放在场景外边是不生效的，要拖到场景里面才生效。漏掉了一个场景

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#20979]
### MeterSphere 版本

2.5

### 使用外置数据库

否

### 问题描述

接口自动化-场景引用 ：优先使用当前场景变量开关，自定义脚本设置的变量放在场景外边是不生效的，要拖到场景里面才生效。漏掉了一个场景

### 重现步骤

1、接口自动化场景a  引用场景b（优先使用当前场景变量开关开启）。在场景b外边新建自定义脚本赋值  场景b引用不生效
2、若是把这个自定义脚本 拖到场景b里面去才生效，

问题：目前变量引用场景有缺失， 

![352ff8b8bc46bfe74c955c88f7d8460](https://user-images.githubusercontent.com/43202800/209646854-07c62780-ca7e-4c7b-88a2-14f17b8ec4aa.png)

### 期待的正确结果

按就近原则，在场景b上面设置的自定义脚本变量 应该也按开关配置生效

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/209648228-27afc804-fb31-4571-bb36-3c76d1a89e1e.png)

**Comment by xhy12** [comment]
在新的场景里设置了变量  但是在引用场景中无法使用新场景中设置的变量的值 ， 原场景中没有改变量值的设置

在描述下：场景a  引用场景b。 按照当前开关：优先使用当前场景变量；场景a要通过自定义脚本的方式重新定义一下场景b里面的部分变量，目前吧自定义脚本变量放在场景b里面 可以生效，放在场景b前面一步就不生效了。此处按照就近原则 放在场景b前面也生效才对

可以同步见录屏（有点大下载附件改成rar格式哦），如果还没描述清楚可以找我语音


[Uploading Rec 0001.txt…]()

**Comment by xhy12** [comment]
[Rec 0001.zip](https://github.com/metersphere/metersphere/files/10307507/Rec.0001.zip)

**Comment by zyyfit** [comment]
您好，感谢您的反馈，这里由于勾选了优先使用当前场景变量，所以场景变量的优先级大于步骤变量，
但是在场景内部的时候，内部的变量会按照步骤顺序执行，所以会覆盖掉这个场景变量

**Comment by xhy12** [comment]
勾选了优先使用当前场景变量。我在当前场景里面设置的变量  优先级就是应该大于原场景变量啊
那不然这里设置的变量在哪里去生效使用呢？？

**Comment by zyyfit** [comment]
> 勾选了优先使用当前场景变量。我在当前场景里面设置的变量 优先级就是应该大于原场景变量啊 那不然这里设置的变量在哪里去生效使用呢？？

是当前的场景变量优先级大于原场景变量，不是任意一个变量都大于原场景变量的

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/209787055-a9503501-0cd8-400c-9d5d-b1f21494e316.png)
脚本里面的变量确认了下也要就近取值，这里功能是不是没有覆盖到

**Comment by zyyfit** [comment]
已确认修改为当前场景里的过程变量也算作当前场景变量

**Comment by zyyfit** [comment]
2.6.0 和 1.20.19 都已修复，请等待版本发布后验证
