### ISSUE TITLE
[BUG]随机函数引起服务内存溢出

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#2098]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
请求中使用函数{__RandomString(1111111111,9999999999)}会导致服务502
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
你这个字符串太长了吧

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本优化这个问题
