### ISSUE TITLE
[BUG]V2.4.1版本升级后JIRA调用获取项目信息接口不能正常返回MS已维护的JIRA KEY

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#20997]
### MeterSphere 版本

版本:   v2.4.1-e4d11ddc

### 使用外置数据库

否

### 问题描述

此问题阻断JIRA与MS集成自动生成测试计划、测试评审，导致无法正常升级到正式环境，还请尽快安排修复。
前序版本中已经实现了JIRA向MS推送测试计划、测试评审
实现方式为调用四个接口分别为：
登录：/signin
获取MS项目信息：/setting/project/list/1/10
推送测试计划：/track/test/plan/add
推送测试任务：/track/test/case/review/save
当前版本升级后，获取MS项目信息：/setting/project/list/1/10接口不能正常返回JIRA KEY值，导致之后的两个接口创建任务时不能找到JIRA与MS的项目映射关系。
![Uploading image.png…]()

### 重现步骤

/setting/project/list/1/10
请求
{
    "filters": {
        "jira_key": [
            "GRPRMSYS"
        ]
    }
}

### 期待的正确结果

返回报文里 "jiraKey": null,应展示已维护的JIRA KEY

![image](https://user-images.githubusercontent.com/46660929/209748618-ef9b2ece-e2f7-43c4-b7db-3f8ff37e3dfe.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #20961
