### ISSUE TITLE
添加测试计划的接口指定了项目id但不生效

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#2099]
试了如果用户当前勾选的是 A项目， 比如调用添加test plan的接口时传了B项目的projectId, 但这个test plan 还是会加到A项目里。

**Comment by zyyfit** [comment]
您好，能具体描述一下操作步骤吗？这边没有复现这个问题

**Comment by wonderfulwxw** [comment]
用户在页面上勾选了项目A, id: aaaaaaaaaaaaaaaaaaaaaaaaaaaa
![image](https://user-images.githubusercontent.com/38770463/115192593-991efb00-a11d-11eb-8d8b-ca521b602ee2.png)


用户调用ms 接口/test/plan/add，想在项目B(id: bbbbbbbbbbbbbbbbbbbbbbbbbbb) 里添加一个测试计划
{
  "workspaceId": "wwwwwwwwwwwwwwwworkspaceidwwwwwwwwwwww",
  "name": "postman_add_plan06",
  "description": "sdfsdfsdfsdfsdfsdf",
  "stage": "system",
  "status": "Prepare",

  "principal": "sweetUser",
  "plannedStartTime": 1616062110000,
  "plannedEndTime": 1616148510000,
  "actualStartTime": 1616062110000,
  "creator": "sweetUser",
  "projectId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  "projectIds": [
    "............................relevanceprojectid................."
  ]
}

最终这个测试计划被添加到了 项目A中。
