### ISSUE TITLE
[BUG]【测试跟踪-测试计划-报告统计】环境信息丢失和开始结束时间不正确

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#20998]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.0

### 使用外置数据库

否

### 问题描述

测试计划-报告统计处，环境信息丢失和开始结束时间不正确

### 重现步骤

1. 测试计划-执行测试计划，在“报告”处可看到已完成，而且信息也都在
![image](https://user-images.githubusercontent.com/104960608/209750052-51767353-c3dd-425c-beee-6385ae569b1b.png)
![image](https://user-images.githubusercontent.com/104960608/209750079-e591d6aa-a16d-45f3-9a04-d1289aac48e8.png)

2.测试计划-报告统计，运行开始时间不对，而且没有结束时间，没有运行环境等信息
![image](https://user-images.githubusercontent.com/104960608/209750722-251e5fc9-63c5-419b-a2ad-5744e76789c5.png)

**Comment by youliyuan-fit2cloud** [comment]
已知，下个小版本修复。
