### ISSUE TITLE
[FEATURE]能不能把jmeter脚本编写的内容转成web版？这样就不用单机编写再上传了

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#21]
**请描述您的需求或者改进建议.**

能不能把jmeter脚本编写的内容转成web版？这样就不用单机编写再上传了

**请描述你建议的实现方案**
把jmeter客户端界面里面设置测试计划，设置请求的界面web化

**Comment by wangzhen-fit2cloud** [comment]
@fangyuanrui 
JMeter 客户端里提供的功能，能配置的东西是特别多的，我们把它的所有功能都迁到 web 端也不是特别现时。能否再详细说明下你们比较期望在 web 端能够进行哪些编辑和设置工作？
同时之前有看到过一个在线的 JMeter [编辑器](https://jmeter-plugins.org/editor/?utm_source=jpgc&utm_medium=banner&utm_campaign=header)，你也可以看下这个工具。

**Comment by yanguoqiang** [comment]
> @fangyuanrui
> JMeter 客户端里提供的功能，能配置的东西是特别多的，我们把它的所有功能都迁到 web 端也不是特别现时。能否再详细说明下你们比较期望在 web 端能够进行哪些编辑和设置工作？
> 同时之前有看到过一个在线的 JMeter [编辑器](https://jmeter-plugins.org/editor/?utm_source=jpgc&utm_medium=banner&utm_campaign=header)，你也可以看下这个工具。

您可以参考下Blazemeter，我觉得做的非常好。

**Comment by fangyuanrui** [comment]
> > @fangyuanrui
> > JMeter 客户端里提供的功能，能配置的东西是特别多的，我们把它的所有功能都迁到 web 端也不是特别现时。能否再详细说明下你们比较期望在 web 端能够进行哪些编辑和设置工作？
> > 同时之前有看到过一个在线的 JMeter [编辑器](https://jmeter-plugins.org/editor/?utm_source=jpgc&utm_medium=banner&utm_campaign=header)，你也可以看下这个工具。
> 
> 您可以参考下Blazemeter，我觉得做的非常好。

嗯，是挺好的，就是能集成就更好了(*^▽^*)
