### ISSUE TITLE
压测报告不准确[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#210]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.1
**Bug 描述**
简要描述您碰到的问题
压测报告概览显示没错误，但是详情有错误
![image](https://user-images.githubusercontent.com/30932762/89519244-a05fdc00-d80e-11ea-86ba-9e2b8008763d.png)
![image](https://user-images.githubusercontent.com/30932762/89519251-a35acc80-d80e-11ea-9eec-da5a6bc9d6fa.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
