### ISSUE TITLE
[BUG]K8s离线部署无法从有密码的Harbor内获取镜像

### ISSUE THREAD

**Issue by ousinka** [metersphere/metersphere#21001]
### MeterSphere 版本

2.4.1

### 使用外置数据库

是

### 问题描述

1、无法从有密码的Harbor内获取镜像。
2、手工作Harbor里pull到work节点，可以执行。
3、在无法修改Hosts的场景下，报“Error: 检查资源池节点上的 /etc/hosts 是否有 127.0.0.1当前主机名 这条配置，请确保这
配置存在并删除报告重新执行”，无法继续使用。

### 重现步骤

必现

### 期待的正确结果

希望处理正常

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/1711
