### ISSUE TITLE
[BUG]对同一接口分别使用MeterSphere与Jmeter性能测试结果存在差异

### ISSUE THREAD

**Issue by wholegale39** [metersphere/metersphere#2100]
[7c8f4958-9601-4afe-a034-98f0089a9f74.zip](https://github.com/metersphere/metersphere/files/6328638/7c8f4958-9601-4afe-a034-98f0089a9f74.zip)
**MeterSphere 版本**
1.8.2

**Bug 描述**
对同一接口分别使用MeterSphere与Jmeter性能测试结果存在差异，MeterSphere与Jmeter在同一机器上安装

**Bug 重现步骤**
1.  MeterSphere与Jmeter对同一接口设置同样的并发线程数与迭代次数
2. 首先使用MeterSphere执行性能测试
3. 然后使用Jmeter执行性能测试
4. 分别执行完毕后对比结果

**期待的正确结果**
理论上两个工具结果应该接近

**截图**
![](https://gitee.com/wholegale39/pictures_markdown/raw/master/20210417123806.png)
**MeterSphere**
![](https://gitee.com/wholegale39/pictures_markdown/raw/master/20210417124628.png)
![](https://gitee.com/wholegale39/pictures_markdown/raw/master/20210417124644.png)
**Jmeter**
![](https://gitee.com/wholegale39/pictures_markdown/raw/master/20210417124726.png)

**Comment by shenkaibo** [comment]
压力机节点和jmeter 是在统一机器上单独安装的么
