### ISSUE TITLE
在wsl环境下部署失败[QUESTION]

### ISSUE THREAD

**Issue by wch352136** [metersphere/metersphere#2101]
1.由于我自己本身习惯的系统是Windows，而且不是专业的开发人员，看到这个项目的要求系统是Linux，就打算在Windows的子系统下尝试部署
2.Windows的子系统（wsl）是第二代，也就是wsl2
3.安装的是拉取镜像什么的都挺顺利，但是启动的时候报错（无此文件或路径），好像是卷挂载失败，但是我实际cd 了一下路径是存在的。截图如下
![image](https://user-images.githubusercontent.com/17609338/115108313-5b499780-9fa2-11eb-9dd3-f3b398cac978.png)
![image](https://user-images.githubusercontent.com/17609338/115108330-73b9b200-9fa2-11eb-86ac-1767562f7762.png)

所以就想请问一下大家，有没有对wsl比较熟悉的朋友，能解答一下，怎么在wsl环境下部署此项目？对了wsl安装的docker是通过 Docker Desktop for windows的方式
![image](https://user-images.githubusercontent.com/17609338/115108397-d27f2b80-9fa2-11eb-8d3d-5ff423da6c1d.png)

![image](https://user-images.githubusercontent.com/17609338/115108381-be3b2e80-9fa2-11eb-8e1d-9e2d857ddaeb.png)

比较小白，查了好多资料没有找到正确的答案，无奈开一个issue，抱歉。

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题解决了吗？

**Comment by wch352136** [comment]
> 你好，请问该问题解决了吗？

还没有，目前靠自己连蒙带猜感觉应该是某些docker   compose配置文件没有针对这种wsl2特殊的docker环境做兼容导致的卷挂载出问题，但是我水平有限还不确定怎么改，还在艰难查资料中。国内对wsl的教程大部分都浅尝辄止，英文囿于我自己的水平可能有解决办法，但是我没查到。希望您这边如果有比较了解的 可以回答一下我的问题。
