### ISSUE TITLE
[BUG]2.5.0版本，集成jira之后，无法同步jira里的bug记录到metersphere

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#21021]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

在metersphere上创建bug可以同步到jira。但是jira中的数据无法同步到metersphere

### 重现步骤

echo

**Comment by shenkaibo** [comment]
双向同步，Jira 中的缺陷 同步到 MS 是企业版功能。
