### ISSUE TITLE
[BUG]2.5版本场景测试，请求体中使用变量，解析出来的POST data就不是json格式

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#21020]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/2188338/209806225-4817d7a8-9b29-4efe-b8b5-00b3faf84aec.png)

升级到2.5.0之后，之前能够正常运行的场景用例都不能执行了。这个请求体里只要使用变量，解析出来的POST data就不是json格式。如果把变量都替换成常量值，就没问题

### 重现步骤

echo

**Comment by zyyfit** [comment]
重复，https://github.com/metersphere/metersphere/issues/20973
已修复，请等待2.5.1版本发布后验证
