### ISSUE TITLE
[优化]脚本自定义的数组无法引用到循环控制器

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#21038]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v2.2

### 使用外置数据库

否

### 问题描述

javascript脚本自定义的数组引用到循环控制器作为循环参数时，循环无法执行

### 重现步骤

1、脚本自定义生成数组变量
2、变量引用到循环控制器
3、执行场景

### 期待的正确结果

自定义的数组变量引用到循环控制器执行成功

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/209935581-bf480280-eef6-4883-9d51-3b7216ff121a.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，暂时做不到～ ，可以提个需求。
