### ISSUE TITLE
[BUG]执行接口测试偶发报错finishConnect failed，每次都通过重启api-test容器能解决，希望排查问题。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21033]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

执行接口测试
![cbd0763f954ba7bbd7aab4f78f76bad](https://user-images.githubusercontent.com/83771182/209922160-dbb92c68-0c9f-4047-aa13-6081d7212f3e.jpg)
查看gateway容器日志报错信息如下

![68247af5c3b01caa07ce7086175410b](https://user-images.githubusercontent.com/83771182/209922406-f33afc66-7447-4344-bde2-7ddf78d7dc9b.jpg)
8004端口是api-test里服务的端口，MS使用过程中经常会遇到这个报错问题，每次都是通过重启api-test容器能解决，但是找不到问题根源，请协助排查。硬件方面内存也没有不足。

### 重现步骤

执行接口测试偶发问题

### 期待的正确结果

解决报错问题。

### 相关日志输出

![68247af5c3b01caa07ce7086175410b](https://user-images.githubusercontent.com/83771182/209923160-376042d4-22c3-4850-9430-f4993b59f122.jpg)

**Comment by fit2-zhao** [comment]
@yaoyi111  下次出现时保留现场环境我们远程看一下是缺陷还是部署安装方面存在问题。

**Comment by Jiang-boyang** [comment]
> ### MeterSphere 版本
> 2.4.0
> 
> ### 使用外置数据库
> 否

部署安装方式：helm 安装
无特殊个性化配置

也存在着问题，比较影响使用体验。

![image](https://user-images.githubusercontent.com/47846791/210465510-8b7d4a4f-09c9-491a-bf49-a7409a34944d.png)

**Comment by youliyuan-fit2cloud** [comment]
> 

@Jiang-boyang @yaoyi111 请根据MeterSpere服务器的配置，修改相应容器的可使用内存配置，服务器16G以上的，可以参考如下修改。
例如，修改api-test 模块的容器内存默认配置为2g， 即， 安装目录 /opt/metersphere/docker-compose-api-test.yml文件中的mem_limit: 2g
修改后，重启服务。如果还是会出现问题，请随时反馈，感谢～

**Comment by Jiang-boyang** [comment]
> 

好的 我试一下

**Comment by yaoyi111** [comment]
docker-compose-api-test.ym文件中修改mem_limit: 2g后，依然报错。
<img width="292" alt="123" src="https://user-images.githubusercontent.com/83771182/212907926-5211406b-6f4a-401a-9fab-849b2be9c062.png">

**Comment by yaoyi111** [comment]
[info.log](https://github.com/metersphere/metersphere/files/10543545/info.log)
[ms-jmeter-run.log](https://github.com/metersphere/metersphere/files/10543546/ms-jmeter-run.log)

**Comment by luty2018** [comment]
建议升级到v2.7试试。
