### ISSUE TITLE
[BUG]循环控制器中引用的接口无法进行删除或者禁用

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#21035]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v2.2.0&v2.4

### 使用外置数据库

否

### 问题描述

接口自动化场景中，在循环控制器里面引用接口case，引用后的case在控制器里面无法进行删除或者禁用操作

### 重现步骤

1、接口自动化场景中
2、添加循环控制器
3、循环控制器中引用接口case
3、删除引用的case

### 期待的正确结果

能正常删除或者禁用循环控制器里的case

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/209928691-51c67e29-f491-4490-a08d-abbda12fc060.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，建议升级到v2.5.1以上版本，引用case可以禁用（不能删除，后续版本改），复制的case可以删除和禁用。
