### ISSUE TITLE
[BUG] 文件管理导入 csv 报错 "Connection has been closed BEFORE response, while sending request body"

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21040]
### MeterSphere 版本

v2.5

### 使用外置数据库

否

### 问题描述

文件管理导入csv报错"Connection has been closed BEFORE response, while sending request body"
![image](https://user-images.githubusercontent.com/103925124/209940901-a390bb4b-e178-414b-9de8-a114a73d6852.png)

### 重现步骤
文件管理导入csv文件，文件因过大无法上传github，微信私聊发送

### 期待的正确结果
文件可正常导入
_No response_

### 附加信息
vim docker-compose-gateway.yml增加下面红框配置后，此问题依然存在：
![image](https://user-images.githubusercontent.com/103925124/210027402-af960e93-b92a-49a6-8a84-6d23328cb01e.png)

![image](https://user-images.githubusercontent.com/103925124/210027867-a6097325-1f42-4115-a84f-07f3d66b72ed.png)

此报错可能原因和解决思路：
https://blog.csdn.net/songjinbin/article/details/103537581
https://www.codeleading.com/article/22024178232/

**Comment by xulinde** [comment]
未复现该问题，私发下你的csv文件～
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/64065190/210056242-92858ff3-854b-4320-bb45-da890d713324.png">

**Comment by xulinde** [comment]
这个是上传大文件把服务弄挂了。project服务内存扩展下即可

**Comment by Ycr123888** [comment]
扩充到1000MB，依然上传失败
扩充到1500MB，上传成功，花费52s

1、大文件上传，在内存不够的情况下，可否先保证服务不挂可用，可提示上传失败，内存不足；
2、上传进度条显示可提需求解决

希望问题1得到修复

**Comment by xulinde** [comment]
> 扩充到1000MB，依然上传失败 扩充到1500MB，上传成功，花费52s
> 
> 1、大文件上传，在内存不够的情况下，可否先保证服务不挂可用，可提示上传失败，内存不足； 2、上传进度条显示可提需求解决
> 
> 希望问题1得到修复

问题1，可以在配置里修改文件大小限制，参考https://blog.csdn.net/qq_29127369/article/details/97397325
