### ISSUE TITLE
[BUG]接口定义导出接口为swagger格式失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#21055]
### 联系方式

张树彬

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

接口定义导出接口为swagger格式失败

### 重现步骤

1. 接口测试-接口定义
2. 勾选要导出的接口
3. 点击导出-swagger3.0格式
4. 没有成功导出接口文件，也没有任何提示

### 期待的正确结果

可以正确导出swagger格式接口文件

**Comment by youliyuan-fit2cloud** [comment]
具体版本号是多少？ 请检查一下是否和如下版本一致。如果一样的，请上传日志错误信息。
<img width="1416" alt="屏幕快照 2022-12-31 下午7 53 17" src="https://user-images.githubusercontent.com/54612864/210135780-aaa61d28-d8b3-490b-91f7-f39350846a25.png">

**Comment by youliyuan-fit2cloud** [comment]
已复现该问题，下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v2.6.0 中已修复～
