### ISSUE TITLE
[FEATURE]接口自动化执行场景时，排查异常情况，需要查找参数来源，所以希望增长查找参数的功能，如图jmeter的搜索功能

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#21053]
### MeterSphere 版本

v1.20.17-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

接口自动化执行场景时，排查异常情况，需要查找参数来源，所以希望增长查找参数的功能，如图jmeter的搜索功能

### 请描述你建议的实现方案

接口自动化执行场景时，排查异常情况，需要查找参数来源，所以希望增长查找参数的功能，如图jmeter的搜索功能

**Comment by luty2018** [comment]
你好， 没有看到图片， 辛苦补传一下， 谢谢！

**Comment by myliuq** [comment]
在接口定义、接口自动化页面希望可以搜索到参数，如上图，如有不清楚可以电话沟通一下




雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]接口自动化执行场景时，排查异常情况，需要查找参数来源，所以希望增长查找参数的功能，如图jmeter的搜索功能 (Issue #21053)





 
你好， 没有看到图片， 辛苦补传一下， 谢谢！

**Comment by luty2018** [comment]
转线下沟通

**Comment by myliuq** [comment]
线下沟通了吗？这个可以兑现吗？




雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]接口自动化执行场景时，排查异常情况，需要查找参数来源，所以希望增长查找参数的功能，如图jmeter的搜索功能 (Issue #21053)





 
转线下沟通
