### ISSUE TITLE
[BUG]接口请求，选择json格式的请求体时，填写字符串参数时，请求时数据格式被误转换为int类型

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#21059]
### MeterSphere 版本

V2.5.0

### 使用外置数据库

否

### 问题描述

接口请求，选择json格式的请求体时，填写字符串参数时，请求时数据格式被误转换为int类型

### 重现步骤

见问题描述和截图

### 附加信息

![b8d21293b5c0637929b5785e787f24a](https://user-images.githubusercontent.com/92150453/210294754-b88a2107-1c31-45a6-8c59-c533b7e4a24a.png)
![c7e7e0f868fc4f991b98020feebd0ad](https://user-images.githubusercontent.com/92150453/210294758-9627e877-f921-4601-a6d0-27309351f3ad.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现该问题，建议升级到最新版本。
