### ISSUE TITLE
[BUG]在接口用例中已上传的文件，用例转为性能测试时，文件丢失

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#21058]
### MeterSphere 版本

V2.2.1

### 使用外置数据库

否

### 问题描述

在接口用例中已上传的文件，用例转为性能测试时，文件丢失，导致性能测试执行失败

### 重现步骤

在接口用例的请求体中选择格式为file，并上传bmp文件，执行接口测试，请求成功；
转换该接口用例为性能测试，并执行压测时，请求失败，并报错无法找到该bmp文件

### 附加信息

![c7aeab86f5c5a58b760692ff30ddac2](https://user-images.githubusercontent.com/92150453/210294081-a0f2df9f-ed27-415b-89b0-18710444430b.png)
![c1feeb90c91b253dbf4a071d1ce7325](https://user-images.githubusercontent.com/92150453/210294096-35142c35-7963-4d85-a977-1744b4815f30.png)
jmx文件重命名为txt:
[4444_1671437722505(1).txt](https://github.com/metersphere/metersphere/files/10334108/4444_1671437722505.1.txt)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.6.0版本已修复，请等待版本发布后验证
