### ISSUE TITLE
[FEATURE] 测试计划关联接口用例列表时，未显示用例状态，同时也不能根据用例状态进行筛选

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21062]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v1.20.18  v2.5.0

### 使用外置数据库

否

### 问题描述

测试计划关联接口用例列表时，未显示用例状态，同时也不能根据用例状态进行筛选
![image](https://user-images.githubusercontent.com/33945037/210296372-f79f5183-01a7-47be-9905-f9ecf79fa30f.png)

### 重现步骤

同上

**Comment by hao65103940** [comment]
大概哪个版本会做？

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉长时间未反馈，我们讨论后决定暂时不支持该需求。
