### ISSUE TITLE
[BUG] 设置了项目的前置脚本，自动化场景用例，在接口自动化场景里执行没有问题，但是在测试计划中执行有错误信息。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#21076]
### MeterSphere 版本

V2.4.1

### 使用外置数据库

否

### 问题描述

1、项目环境中打开并且设置了host相关信息
2、项目环境中设置了前置脚本，登录处理
3、接口测试--接口自动化测试，执行接口自动化脚本没有问题
4、测试计划中执行接口自动化用例就出现错误。

### 重现步骤

1、项目环境中打开并且设置了host相关信息
2、项目环境中设置了前置脚本，登录处理
3、接口测试--接口自动化测试，执行接口自动化脚本没有问题
4、测试计划中执行接口自动化用例就出现错误。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/210315495-7bf0b1f9-e2f6-4cef-b8c4-04753b993952.png)

**Comment by huangxine** [comment]
补充信息：
客户在未升级到微服务架构前，这个脚本无论是在测试计划中，还是接口测试自动化中，执行都是没有问题的。系统升级到微服务架构后，在测试计划中执行就出现问题，接口自动化测试中执行是正常的。
下面是前置脚本信息，创建issue时，一直添加不了第二个图片。
![前置脚本](https://user-images.githubusercontent.com/78218624/210325632-db39f2af-ef30-40a6-adf8-a88a68434ecf.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是否可以提供一下具体的复现脚本？
