### ISSUE TITLE
[BUG]MQTT服务存在多broker服务透传时，B服务无法订阅到A服务发布的消息

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#21078]
### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

MQTT服务存在多broker服务透传时，B服务无法订阅到A服务发布的消息

### 重现步骤

用户操作场景：
1.MQTT门锁服务，发布修改门锁信息的消息，通过后台的中转服务平台(SAAS服务器接收发布的消息，透传给PAAS服务器)，再通过MQTT APP服务订阅门锁服务发布的消息。
说明：
在Jmeter上，通过添加多线程组的方式，一个线程组进行门锁服务的连接、发布；1个线程组进程APP服务的连接、订阅；在门锁服务发布消息的topic与APP服务订阅消息topic不同的情况下，APP服务能正常订阅到门锁服务发布的消息；
基于相同的参数配置，在MS上APP服务无法订阅到门锁服务发布的消息
备注：
本地有录制好的操作视频，可单独联系提供录制视频

**Comment by luty2018** [comment]
试试连接、订阅，并发控制器下加 订阅、服务
插件下载：
https://github.com/metersphere/metersphere-plugin-ParallelController

**Comment by fit2-zhao** [comment]
https://github.com/metersphere/metersphere-plugin-ParallelController
这个组件就可以实现跟发效果，和多线程组类似
