### ISSUE TITLE
[BUG] 【测试跟踪】通过批量修改的方式修改字段1的值为value11,  字段2的值也会变成value11。

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21075]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【测试跟踪】通过批量修改的方式修改字段1的值为value11,  字段2的值也会变成value11。

### 重现步骤

项目的用例模板新增两个输入框类型的字段
![image](https://user-images.githubusercontent.com/103925124/210316913-00a3c6ad-a067-446e-9b9c-e5af5c5729a2.png)
某用例的自定义字段值情况如下：
![image](https://user-images.githubusercontent.com/103925124/210317005-08decb3a-d859-43e0-aab1-de0f770df8b3.png)
通过批量修改某自定义字段的值为9999
![image](https://user-images.githubusercontent.com/103925124/210317450-04eb514a-2c10-4a83-8056-5a0631482118.png)
该用例的两个自定义字段值均为9999
![image](https://user-images.githubusercontent.com/103925124/210317528-7beb2af8-0862-4373-9891-e29fb650ca5f.png)

### 期待的正确结果

修改某一自定义字段成功，且其余子墩公益字段值不变

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v2.6.0 中已修复～
