### ISSUE TITLE
[BUG]接口定义模块，请求体是form时，用批量添加方式增加参数后，已添加参数值不能进行编辑，双击参数值没有反应。 

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21077]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

接口定义模块，请求体是form时，用批量添加方式增加参数后，参数值就不能编辑了，双击值没有反应。 
![image](https://user-images.githubusercontent.com/83771182/210327558-e5db8635-cbaf-4cd9-80ed-6afc141fbdb7.png)
必须 保存场景后，关闭该接口界面再次进入，双击才能进行编辑。
![image](https://user-images.githubusercontent.com/83771182/210327743-820b45c5-20a4-42b6-9150-25a43cf36ad4.png)

### 重现步骤

接口定义模块，请求体是form时，用批量添加方式增加参数后，参数值就不能编辑了，双击值没有反应。 必须 保存场景后，关闭该接口界面再次进入，双击才能进行编辑。

### 期待的正确结果

接口定义模块，请求体是form时，用批量添加方式增加参数后，参数值可以通过双击进行编辑。

### 相关日志输出

```shell
无
```

**Comment by youliyuan-fit2cloud** [comment]
即将发布的v2.6.0 中已修复～
