### ISSUE TITLE
[BUG] 【项目管理】编辑项目后新建项目，表单回显内容为刚编辑过的项目信息

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21081]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【项目管理】编辑项目后新建项目，表单回显内容为刚编辑过的项目信息

### 重现步骤

项目管理编辑 “验证deploy项目”后点击新建项目，此时回显为刚编辑过的项目信息：
![image](https://user-images.githubusercontent.com/103925124/210340950-9f2f8cc0-666a-467f-8be5-1f9820ea4a9e.png)

### 期待的正确结果

项目管理-新建项目为空白表单数据

**Comment by youliyuan-fit2cloud** [comment]
没有复现该问题，方便录个复现视频吧。
