### ISSUE TITLE
[BUG]场景中引用场景，批量删除步骤后，场景步骤丢失

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21098]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

场景中引用场景，批量删除步骤后，场景步骤丢失

### 重现步骤

1.创建场景，场景中引用场景
![image](https://user-images.githubusercontent.com/103627487/210537466-4473a894-6e42-46b8-bc64-7ff105ec170a.png)
2.批量删除步骤
![image](https://user-images.githubusercontent.com/103627487/210537639-dfcc8dd2-f482-4672-8ae8-49f6445eabae.png)
3.所有引用的的场景均无步骤了，无法点开
![image](https://user-images.githubusercontent.com/103627487/210538036-a7b4a493-c5ad-4b4e-af71-9ade7256ef3c.png)

### 期待的正确结果

场景中批量删除后，步骤正常显示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.19版本已修复，请等待版本发布后验证
