### ISSUE TITLE
[BUG]【UI自动化-浏览器操作-选择内嵌网页】frame 索引号从0开始，但是输入0无法保存。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21105]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【UI自动化-浏览器操作-选择内嵌网页】frame 索引号从0开始，但是输入0无法保存。
![image](https://user-images.githubusercontent.com/104960608/210687524-89dcf4dc-07de-4c91-97a6-e97d57658e58.png)

### 重现步骤

【UI自动化-浏览器操作-选择内嵌网页】frame 索引号从0开始，但是输入0无法保存。
![image](https://user-images.githubusercontent.com/104960608/210687524-89dcf4dc-07de-4c91-97a6-e97d57658e58.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v2.6.0版本已修复，发布后可升级验证。
