### ISSUE TITLE
[BUG] 【接口测试】  接口参数开启json-schema，参数高级设置的描述很长，预览描述，超出弹出框外

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21104]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

 接口参数开启json-schema，参数高级设置的描述很长，预览描述，超出弹出框外

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/210685948-c89a9cfd-1e73-42c1-b925-173d99499220.png)
![image](https://user-images.githubusercontent.com/103925124/210686179-2c6e68e2-e5c5-4c2b-8648-449d1b23b811.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
v2.6.0 和 v1.20.19 版本已修复，请等待版本发布后验证
