### ISSUE TITLE
[BUG]【接口定义-快捷调试】json参数，使用内置函数 "${__time(yyyy-MM-dd'T' HH:mm:ss .SSSZ,)}" 格式报错

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21106]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【接口定义-快捷调试】json参数，使用内置函数 "${__time(yyyy-MM-dd'T' HH:mm:ss .SSSZ,)}" 格式报错

### 重现步骤

1. 【接口定义-快捷调试】json参数，使用内置函数 "${__time(yyyy-MM-dd'T' HH:mm:ss .SSSZ,)}" 格式，出现报错
![image](https://user-images.githubusercontent.com/104960608/210689181-9c2ef0dd-061a-46ae-8278-6a16da3751c1.png)

2. 将同样的参数放到JMeter上运行，正常执行
![image](https://user-images.githubusercontent.com/104960608/210689473-96c95960-5dac-489d-a701-8e098dd2432f.png)

![image](https://user-images.githubusercontent.com/104960608/210689508-1e005d83-93c1-4197-a7c3-04a0412c15dc.png)

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/210697698-6985f491-d0c9-4afe-945b-f8d94277f31b.png)
可能原因，字符json格式下是有问题的  切换raw窗口试一下
