### ISSUE TITLE
[BUG]测试计划切换环境，关联的接口用例前后置sql环境未切换

### ISSUE THREAD

**Issue by lvchunyu1993** [metersphere/metersphere#21100]
### 联系方式

MeterSphere交流群44  微信

### MeterSphere 版本

v1.20.17-lts-c59a4086

### 使用外置数据库

否

### 问题描述

一个接口测试用例，存在前后置SQL，添加到测试计划中，先选择A环境，case执行成功；
测试计划切换到B环境，case执行失败，case前置sql执行环境仍为A

### 重现步骤

1. 测试用例存在前后置SQL，添加到测试计划A中，选择test环境运行；
2. 测试计划A 重新选择staging环境运行；

### 期待的正确结果

case运行成功，接口及前后置sql环境切换成功

**Comment by zyyfit** [comment]
您好，最新版 1.20.18 没有复现这个问题，能否详细描述一下操作步骤或者提供一下复现数据呢？
