### ISSUE TITLE
[BUG]csv文件的场景变量无法保存

### ISSUE THREAD

**Issue by Grant2108** [metersphere/metersphere#2111]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.0-21bf611d

**Bug 描述**
简要描述您碰到的问题
上传csv文件作为场景变量后，点击预览可以看到数据。
保存后，叉掉场景，再进入该场景进来查看该场景变量，显示暂无数据。

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/22139528/115188223-30cd1b00-a117-11eb-9e89-5c48f6978898.png)

**Comment by zyyfit** [comment]
您好，这个问题将会在1.9版本中解决

**Comment by zyyfit** [comment]
最新版已修复
