### ISSUE TITLE
[BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常

### ISSUE THREAD

**Issue by changdapu** [metersphere/metersphere#21112]
### 联系方式

55群-喜大普奔

### MeterSphere 版本

v2.5.1-8e5455a

### 使用外置数据库

否

### 问题描述

场景定时任务：
把每天10点运行，改成了每天9:30运行，就出现了上图错误：重置定时任务-启动新定时任务出现异常

data: nul]
message:重置定时任务-启动新定时任务出现异常
success:false

请求 URL: http://192.168.1.81:8081/api/api/automation/schedult请求方法: POST
状态代码:  500 Internal Server Error
远程地址: 192.168.1.81:8081
引用站点策略: no-referrer-when-downgrade

### 重现步骤

场景定时任务：
修改已存在的接口测试场景，把定时任务从 每天10点运行，改成了每天9:30运行，提示错误：重置定时任务-启动新定时任务出现异常

**Comment by changdapu** [comment]
给我一个查询方法，我查日志给你们这个问题，我今天没有重现，估计和见面交互，以及修改时间点有关，你给我日志查询方法，我再复现一次。发自我的手机-------- 原始邮件 --------发件人： xulinde ***@***.***>日期： 2023年1月6日周五 18:34收件人： metersphere/metersphere ***@***.***>抄送： changdapu ***@***.***>, State change ***@***.***>主    题： Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112)

未复现该问题，是必现的吗，后台有报错日志吗？

**Comment by xulinde** [comment]
> 给我一个查询方法，我查日志给你们这个问题，我今天没有重现，估计和见面交互，以及修改时间点有关，你给我日志查询方法，我再复现一次。发自我的手机-------- 原始邮件 --------发件人： xulinde ***@***.***>日期： 2023年1月6日周五 18:34收件人： metersphere/metersphere ***@***.***>抄送： changdapu ***@***.***>, State change ***@***.***>主 题： Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112) 未复现该问题，是必现的吗，后台有报错日志吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

日志路径：/opt/metersphere/logs/api-test/error.log

**Comment by changdapu** [comment]
我下载了所有日志，你看下有没有历史的日志【附件】
&nbsp;sz /opt/metersphere/logs/api-test/*.log


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 下午2:09
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112)





  
给我一个查询方法，我查日志给你们这个问题，我今天没有重现，估计和见面交互，以及修改时间点有关，你给我日志查询方法，我再复现一次。发自我的手机-------- 原始邮件 --------发件人： xulinde @.&gt;日期： 2023年1月6日周五 18:34收件人： metersphere/metersphere @.&gt;抄送： changdapu @.&gt;, State change @.&gt;主 题： Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112) 未复现该问题，是必现的吗，后台有报错日志吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
日志路径：/opt/metersphere/logs/api-test/error.log

**Comment by xulinde** [comment]
> 我下载了所有日志，你看下有没有历史的日志【附件】 &nbsp;sz /opt/metersphere/logs/api-test/*.log
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年1月9日(星期一) 下午2:09 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112) 给我一个查询方法，我查日志给你们这个问题，我今天没有重现，估计和见面交互，以及修改时间点有关，你给我日志查询方法，我再复现一次。发自我的手机-------- 原始邮件 --------发件人： xulinde @.&gt;日期： 2023年1月6日周五 18:34收件人： metersphere/metersphere @.&gt;抄送： changdapu @.&gt;, State change @.&gt;主 题： Re: [metersphere/metersphere] [BUG]修改接口测试场景【定时任务】报错：重置定时任务-启动新定时任务出现异常 (Issue #21112) 未复现该问题，是必现的吗，后台有报错日志吗？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: @.***&gt; 日志路径：/opt/metersphere/logs/api-test/error.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

看不到附件，您在交流群吗，我找您单独沟通
