### ISSUE TITLE
[BUG]接口自动化场景中，单独执行用例 不能调用环境变量，旧版本是正常的

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#21116]
### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

接口自动化场景中，单独执行用例 不能调用环境变量，旧版本是正常的

### 重现步骤

接口自动化场景中，单独执行用例 无法调用环境变量，旧版本是正常的

### 期待的正确结果

正常可以调用环境变量

### 附加信息

![image](https://user-images.githubusercontent.com/43720321/210710265-9f905507-b7d2-4085-a361-203bab2af03a.png)
![f448435dbc7546303250ebf42915606](https://user-images.githubusercontent.com/43720321/210710300-e2d4f02b-38b8-4474-8e6e-ae99fec1424c.png)

**Comment by Ycr123888** [comment]
1.20.18-lts 此问题同样必现，麻烦一起修复下

**Comment by zyyfit** [comment]
1.20.19  和  2.6.0 版本都已修复，请等待版本发布后验证
