### ISSUE TITLE
[BUG]【接口定义-导入-swagger】使用url进行导入当前网站的swagger文档，出现解析错误

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21111]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【接口定义-导入-swagger】使用url进行导入当前网站的swagger文档，出现解析错误

### 重现步骤

【接口定义-导入-swagger】使用url进行导入当前网站的swagger文档，出现解析错误
![image](https://user-images.githubusercontent.com/104960608/210705625-29aed5d0-fc2f-4b92-afe2-ed83f3e21d94.png)
![image](https://user-images.githubusercontent.com/104960608/210705693-5a423f71-2cde-4d6d-86de-0776d233a30d.png)

**Comment by zyyfit** [comment]
没有复现这个问题
![image](https://user-images.githubusercontent.com/73461316/210772315-31ef336e-47c9-4850-b808-a09f9070079d.png)

**Comment by zyyfit** [comment]
2.5.1 版本确实复现了，2.6.0 版本已经没有这个问题了，请等待2.6.0 版本发布后验证
