### ISSUE TITLE
[BUG] API自动化首页统计信息在切换table页后相关统计信息不可以展示

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#21120]
### 联系方式

群14-亲山留水

### MeterSphere 版本

v2.5.1

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/210714896-4505dfbf-a3c1-4669-99c2-e66e0e1ac0f0.png)
API自动化首页统计信息在切换table页后相关统计信息不可以展示，切换项目后可正常展示
![image](https://user-images.githubusercontent.com/82088551/210715169-2b3c6bfb-f9d2-4ecb-b26b-68f77c99ec5d.png)

### 重现步骤

切换项目，展示API首页统计信息，切换table页后回到首页

### 期待的正确结果

API首页统计信息正常展示

**Comment by zrfit** [comment]
v2.6.0版本已修复，发布后可升级验证。
