### ISSUE TITLE
[BUG] 版本升级API插件 并行插件 debug插件不能生效，但是又不能重新上传插件

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#21122]
### 联系方式

群14-亲山留水

### MeterSphere 版本

v2.5.1

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/82088551/210720276-ca3a55b7-497f-4647-a610-6102f61d21b2.png)
历史插件记录不能删除，但又未生效 ，但又不能重新上传插件，提示已存在

### 重现步骤

1、历史插件记录不能删除，但又未生效
2、重新上传API插件，不能上传提示已存在

### 期待的正确结果

1、最好是升级后历史插件同步生效
2、或者可以删除历史插件记录并可重新上传插件 并行插件和debug插件

**Comment by zyyfit** [comment]
如果着急使用可以在ms的数据库中执行一下这个sql
update `plugin` SET scenario='api' where scenario is null;

**Comment by zyyfit** [comment]
2.6.0版本已修复，请等待版本发布后验证
