### ISSUE TITLE
[BUG] 【性能测试】使用功能函数jar包，进行参数化失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21121]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【性能测试】使用功能函数jar包，进行参数化失败

### 重现步骤

文件管理上传jmeter功能函数jar包
[jmeter-plugins-functions-2.1.zip](https://github.com/metersphere/metersphere/files/10349877/jmeter-plugins-functions-2.1.zip)
![image](https://user-images.githubusercontent.com/103925124/210718168-3132c578-4ca1-4545-a21e-a331e2fe5347.png)
接口测试脚本和参数引用该函数成功：
![image](https://user-images.githubusercontent.com/103925124/210717473-3b5c7274-01fc-4e56-a17a-2d666a9688c9.png)
接口测试为本地资源池执行：
![image](https://user-images.githubusercontent.com/103925124/210718337-01da775b-ce2c-4ba9-8af4-54e65052ae54.png)
将场景转为性能测试执行：
![image](https://user-images.githubusercontent.com/103925124/210718456-0d6440c0-5250-4586-9a13-2f9748862b91.png)
同样是本地资源池执行：
![image](https://user-images.githubusercontent.com/103925124/210718531-ec3f7f5b-d51e-4a4c-a227-833eed1ae805.png)
性能测试中未参数化：
![image](https://user-images.githubusercontent.com/103925124/210718712-351d342d-adee-44e0-b523-cf488cecc8ad.png)

### 期待的正确结果

函数包加载后，在性能测试中依然可用

**Comment by liuruibin** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/23045261/211004469-78a91c03-6417-4a08-89b2-e7471ac97776.png">
在测试编辑的时候选择高级配置，覆盖jmeter.properties
<img width="967" alt="image" src="https://user-images.githubusercontent.com/23045261/211004598-e48a0816-fd24-42ad-9c6b-be8006b55507.png">
