### ISSUE TITLE
[BUG] 场景用例存在多个步骤，单独调试某一步骤，参数化之后不能获取到环境变量设置的值

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#21130]
### 联系方式

MeterSphere 交流群22    chase  chase001@qq.com

### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

场景用例存在多个步骤，单独调试某一步骤，参数化之后不能获取到环境变量设置的值

### 重现步骤

![image](https://user-images.githubusercontent.com/23476281/210745428-6e8a426e-8cf1-4bbd-87ff-e12e83c974af.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #21116
