### ISSUE TITLE
[BUG]性能测试测试场景高级设置选择 csv 分割，性能测试场景无法运行

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#21147]
### 联系方式

13735892260

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

性能测试过程，选择 csv 文件，采用是 txt ，选择了分割，性能测试无法运行

### 重现步骤

无

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by hztony** [comment]
不管是 txt 还是 csv 效果都一样

**Comment by hztony** [comment]
很好复现的，只是你的测试数据过于简单

**Comment by hztony** [comment]
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAwQDg1MzEuY24iLCJ1aWQiOjExMjY3NTgsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDAiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.R1dOmZlX5qJTo1H6U6ZaTUwxvSvyFD6p5jortiICEoGsXN6hx_6V-fgC6Hr74CHLtUUpbFFs72umD751bQKX4w
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAxQDg1MzEuY24iLCJ1aWQiOjExMjY3NTksImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDEiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.aL7mYYPXI0hqLgbEiSH6IwNlOY-BOugU5Po6GUQuMN_3742hCfMmhieyI6DleL9a7VUyV-WjzNXPOzau_gCuyg
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAyQDg1MzEuY24iLCJ1aWQiOjExMjY3NjAsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDIiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.dEhW53SgeY0-46GWdT_Nni7PFOkNvjEuhrxiF_lSDleOQbqOyNqtp26FqhOcR3BcrnrgdU6EWMwkYiYrOFQoqQ
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAzQDg1MzEuY24iLCJ1aWQiOjExMjY3NjEsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDMiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.qiIRg7SE08KzM9Lj3I0vZalS-CDnjZjWtiCR9R2Q0YaldWD7yJPJnjiVr-H3SlufTqdDBy6P72d3TReuhIl1TA
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDA0QDg1MzEuY24iLCJ1aWQiOjExMjY3NjIsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDQiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.I_CDx6cS0vk0JvcpZTQeuyiRjJhEgAvM5wwINR8x86UOaBCOQbFq-IiCetp1oEP5DJpuvoeWHTtDcsrTi_k1zw
eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDA1QDg1MzEuY24iLCJ1aWQiOjExMjY3NjMsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDUiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.i3c3Hs3flaPCW98nX0-quSpKImpuXWwFD_rQtVRDEtumcPHZ1pduweUUH-2vOKdz0LJV-vknExl7h9NgxkACJ

**Comment by youliyuan-fit2cloud** [comment]
> eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAwQDg1MzEuY24iLCJ1aWQiOjExMjY3NTgsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDAiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.R1dOmZlX5qJTo1H6U6ZaTUwxvSvyFD6p5jortiICEoGsXN6hx_6V-fgC6Hr74CHLtUUpbFFs72umD751bQKX4w eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAxQDg1MzEuY24iLCJ1aWQiOjExMjY3NTksImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDEiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.aL7mYYPXI0hqLgbEiSH6IwNlOY-BOugU5Po6GUQuMN_3742hCfMmhieyI6DleL9a7VUyV-WjzNXPOzau_gCuyg eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAyQDg1MzEuY24iLCJ1aWQiOjExMjY3NjAsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDIiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.dEhW53SgeY0-46GWdT_Nni7PFOkNvjEuhrxiF_lSDleOQbqOyNqtp26FqhOcR3BcrnrgdU6EWMwkYiYrOFQoqQ eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDAzQDg1MzEuY24iLCJ1aWQiOjExMjY3NjEsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDMiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.qiIRg7SE08KzM9Lj3I0vZalS-CDnjZjWtiCR9R2Q0YaldWD7yJPJnjiVr-H3SlufTqdDBy6P72d3TReuhIl1TA eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDA0QDg1MzEuY24iLCJ1aWQiOjExMjY3NjIsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDQiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.I_CDx6cS0vk0JvcpZTQeuyiRjJhEgAvM5wwINR8x86UOaBCOQbFq-IiCetp1oEP5DJpuvoeWHTtDcsrTi_k1zw eyJhbGciOiJFUzI1NiJ9.eyJzYyI6IlRNWSIsInN1YiI6IjE5MTAxMDExMDA1QDg1MzEuY24iLCJ1aWQiOjExMjY3NjMsImdpZCI6MTY3LCJpaWQiOiI5OTgzMiIsInJuIjoiMTkxMDEwMTEwMDUiLCJleHAiOjE2NzM3MzIyOTksImlhdCI6MTY3MzUxNjI5OSwidGlkIjoyNTMsInV0IjoyfQ.i3c3Hs3flaPCW98nX0-quSpKImpuXWwFD_rQtVRDEtumcPHZ1pduweUUH-2vOKdz0LJV-vknExl7h9NgxkACJ

这个是什么？不是错误日志呀，我们看不出来，得看看性能测试用例的配置截图和错误日志。
