### ISSUE TITLE
[BUG]在 Metersphere 执行性能测试，导出jtl文件，在jmeter 中导入，查看到请求内容为空

### ISSUE THREAD

**Issue by zhangxiang01** [metersphere/metersphere#21144]
### MeterSphere 版本

v1.19.2

### 使用外置数据库

否

### 问题描述

在 Metersphere 执行性能测试，导出jtl文件，在jmeter 中导入，查看到请求内容为空

### 重现步骤

1.执行性能测试（存在错误请求）
2.下载jtl 文件
3.在 jmeter 中创建线程组，添加查看结果树
4.导入从 Metersphere 下载的 jtl 文件
5.查看错误的接口信息

### 期待的正确结果

展示接口信息

### 附加信息

![截图](https://user-images.githubusercontent.com/39454317/210910096-e75626e7-d098-4e4f-b0db-b2e884d507bf.png)

**Comment by liuruibin** [comment]
性能测试为了保证测试性能输出的jtl不会保存测试结果，只有少量的关键信息。
