### ISSUE TITLE
[BUG]【性能测试】使用接口自动化转化来的场景，获取不到运行环境的环境变量

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21150]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【性能测试】使用接口自动化转化来的场景，获取不到运行环境的环境变量

### 重现步骤

1. 环境里设置环境变量后，在【接口自动化-场景】后置脚本中打印环境变量，点击调试，可看到正常打印环境变量值
![image](https://user-images.githubusercontent.com/104960608/210920419-af053851-f9c6-4112-aeda-65754f803c03.png)

![image](https://user-images.githubusercontent.com/104960608/210920480-dca6f9d6-e60a-44ee-89ab-50075c8bce67.png)

![image](https://user-images.githubusercontent.com/104960608/210920565-0c188b94-0f66-4f8c-97ce-b5175a3dc670.png)

![image](https://user-images.githubusercontent.com/104960608/210920611-907eda67-7789-4004-8585-09e5ec4a02ff.png)
2.将其转为性能测试，运行后，在控制台日志中看到，环境变量的值并没有取到
![image](https://user-images.githubusercontent.com/104960608/210920923-9b58b2fc-4a5f-401e-b639-d422e711507e.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.6.0版本已修复，请等待版本发布后验证
