### ISSUE TITLE
[BUG] 【接口测试】开启json-schema，后预览json数据显示不全，且数据未格式化

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21168]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

开启json-schema，后预览json数据显示不全，且数据未格式化<也无滑动条>

### 重现步骤

开启json-schema，后预览json数据显示不全，且数据未格式化<也无滑动条>
![image](https://user-images.githubusercontent.com/103925124/210982259-16ab8912-95f0-4a5f-9ece-479aa2a0f890.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.6.0中已修复该问题。
