### ISSUE TITLE
[BUG]接口自动化场景中，单接口执行的时候无法引用环境变量

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#21163]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

 v1.20.18-lts

### 使用外置数据库

否

### 问题描述

在接口自动化场景中，点调试执行接口的时候，能正常引用到环境变量，但是如果点击单个接口的执行按钮的话，执行时无法引用到环境变量

### 重现步骤

1、接口自动化场景中，点击调试，查看接口引用的环境变量是否取值成功
2、单独点击接口用例的执行按钮，查看接口引用的环境变量是否取值成功

### 期待的正确结果

单独点击执行一条用例时，环境变量引用取值成功

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/210963094-aa560dbb-6f2d-4446-b1c7-1db9d39a1755.png)
![image](https://user-images.githubusercontent.com/45786766/210963366-8b355c9c-5a8d-4485-8793-a3ba2aa8e456.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #21116
