### ISSUE TITLE
[FEATURE]为方便操作，希望接口自动化里面增加链接到接口定义页面可以修改接口信息

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#21172]
### MeterSphere 版本

v1.20.18-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

接口是引用过来的，不能编辑，当需要修改时得回到接口定义里面找到这个接口修改再同步到这里，希望这里增加链接能直接打开接口定义页面修改接口，这样操作就方便多了

### 请描述你建议的实现方案

![微信截图_20230106203446](https://user-images.githubusercontent.com/39357523/211013732-57920b53-3876-4a62-889a-e73c9227d691.png)

**Comment by myliuq** [comment]
![微信截图_20230106203446](https://user-images.githubusercontent.com/39357523/211013772-d7312fc9-a7d5-4a40-b649-a7ee33aa0ada.png)

**Comment by luty2018** [comment]
这个功能已经有了， 你点击ID就会在新窗口打开这个场景了。

**Comment by myliuq** [comment]
soga，get了，谢谢亲




雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月10日(星期二) 下午2:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]为方便操作，希望接口自动化里面增加链接到接口定义页面可以修改接口信息 (Issue #21172)





 
这个功能已经有了， 你点击ID就会在新窗口打开这个场景了。
