### ISSUE TITLE
[BUG]  全局前置脚本在多场景同时执行的情况下，会出现部分场景获取不到前置脚本的执行结果

### ISSUE THREAD

**Issue by Kaka000001** [metersphere/metersphere#21176]
### MeterSphere 版本

 v2.4.1-e4d11ddc

### 使用外置数据库

否

### 问题描述

1. 项目环境里配置了前置脚本，设置为所有场景步骤前执行（脚本主要内容为获取token，设置为环境变量）
2. 选中多个场景用例，串行执行
3. 出现第一个场景用例获取不到token,后面的场景用例可以获取到token
4. 再次选择多个场景用例，执行
5. 会发现其中一个场景用例适用的token是上一次执行获取的token,其他场景使用的是新本次执行获取到的新token

并行执行在第一次执行时，全部都获取不到token

### 重现步骤

如上问题描述，可以复现

### 期待的正确结果

希望在前置脚本执行结束的情况下，再执行场景用例

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，您可以等本周2.6.0版本发布后升级到2.6.0试试，如果还不行的话是否可以提供一下测试数据或者详细复现步骤？

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，您可以等本周2.6.0版本发布后升级到2.6.0试试，如果还不行的话是否可以提供一下测试数据或者详细复现步骤？
