### ISSUE TITLE
[BUG]测试用例导入时，标签里的信息是纯数字，在用例导入成功后，在再测试计划关联测试用例时，系统会崩溃。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#21177]
### MeterSphere 版本

V2.5.1

### 使用外置数据库

否

### 问题描述

条件：
1、测试用例通过Excel文件导入，并且用例的标签是“20230107”纯数字。

操作：
1、创建测试计划
2、关联测试用例
3、系统卡死，并且页面崩溃，最后提示 out of memory.

查找原因：
1、导入时标签里如添加中文导入成功后，再计划里关联测试用例，就没有问题，只有当纯数字时，计划中关联用例就异常。

### 重现步骤

条件：
1、测试用例通过Excel文件导入，并且用例的标签是“20230107”纯数字。

操作：
1、创建测试计划
2、关联测试用例
3、系统卡死，并且页面崩溃，最后提示 out of memory.

查找原因：
1、导入时标签里如添加中文导入成功后，再计划里关联测试用例，就没有问题，只有当纯数字时，计划中关联用例就异常。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/211230629-86da7adb-b5dc-41bb-a6e8-20a04f6fc633.png)
![image](https://user-images.githubusercontent.com/78218624/211230716-3ebea323-4b16-497d-adea-d6d72c7fa28c.png)

![image](https://user-images.githubusercontent.com/78218624/211230648-ff42aec4-d247-4476-874f-4d6f59e2474f.png)

**Comment by xulinde** [comment]
未复现该问题，excel文件发下吧

**Comment by huangxine** [comment]
[Metersphere_case设备健康 -标签.xlsx](https://github.com/metersphere/metersphere/files/10397921/Metersphere_case.-.xlsx)

**Comment by xulinde** [comment]
> [Metersphere_case设备健康 -标签.xlsx](https://github.com/metersphere/metersphere/files/10397921/Metersphere_case.-.xlsx)

导入该文件仍未复现

**Comment by xulinde** [comment]
> [Metersphere_case设备健康 -标签.xlsx](https://github.com/metersphere/metersphere/files/10397921/Metersphere_case.-.xlsx)

使用该文件已复现，v2.6版本修复

**Comment by huangxine** [comment]
2.6版本还是有问题啊。在测试计划关联时，可以选择标签为纯数字的用例，但是点击确认后，系统还是会崩溃的。
![image](https://user-images.githubusercontent.com/78218624/215690718-ed65b8e2-eec5-4685-8150-c0e7414be2fd.png)

并且重新进入系统>>进入测试计划列表，点击查看刚才的计划，系统崩溃
![image](https://user-images.githubusercontent.com/78218624/215691052-3b769def-7628-470b-8d54-11a216961cfd.png)


![image](https://user-images.githubusercontent.com/78218624/215690298-74a22140-8b57-4b3a-ad15-bf2881365d0d.png)

**Comment by xulinde** [comment]
> 2.6版本还是有问题啊。在测试计划关联时，可以选择标签为纯数字的用例，但是点击确认后，系统还是会崩溃的。 ![image](https://user-images.githubusercontent.com/78218624/215690718-ed65b8e2-eec5-4685-8150-c0e7414be2fd.png)
> 
> 并且重新进入系统>>进入测试计划列表，点击查看刚才的计划，系统崩溃 ![image](https://user-images.githubusercontent.com/78218624/215691052-3b769def-7628-470b-8d54-11a216961cfd.png)
> 
> ![image](https://user-images.githubusercontent.com/78218624/215690298-74a22140-8b57-4b3a-ad15-bf2881365d0d.png)

下个版本修复～

**Comment by xulinde** [comment]
v2.7.0已修复～
