### ISSUE TITLE
[FEATURE]希望增加能重置两层循环计数器的函数     

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#21171]
### MeterSphere 版本

v1.20.18-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

写接口自动化时会有2或多层循环的场景，例如第一层循环：按次数循环2次，循环里面的接口提取参数组arr，第二层循环，计数器为n，需要用到第一层的数组arr,根据计数器取值，用拼接函数${__V(arr_${n},)}。希望是4次循环arr取到的值为${__V(arr_${1},)}，${__V(arr_${2},)}；${__V(arr_${1},)}，${__V(arr_${2},)}，即每次第一层循环产生第二层循环的数据是一样的。而实际得到的arr值为${__V(arr_${1},)}，${__V(arr_${2},)}，${__V(arr_${3},)}，${__V(arr_${4},)}，因为计数器n跟随第一二层的循环一直递增，希望能重置第二层循环的计数器n在第二层循环时从1开始。

### 请描述你建议的实现方案

在jmeter里面是通过${__jm__循环新增楼栋__idx}函数重置计数器的，如图

### 附加信息

![微信图片_20230106145545](https://user-images.githubusercontent.com/39357523/211013257-4ad88ed3-81bc-41a7-9617-ba38f8982ee5.png)

**Comment by myliuq** [comment]
“写接口自动化时会有2或多层循环的场景，例如第一层循环：按次数循环2次，循环里面的接口提取参数组arr，第二层循环，计数器为n，需要用到第一层的数组arr,根据计数器取值，用拼接函数${__V(arr_${n},)}。希望是4次循环arr取到的值为${__V(arr_${1},)}，${__V(arr_${2},)}；${__V(arr_${1},)}，${__V(arr_${2},)}，即每次第一层循环产生第二层循环的数据是一样的。而实际得到的arr值为${__V(arr_${1},)}，${__V(arr_${2},)}，${__V(arr_${3},)}，${__V(arr_${4},)}，不管第一层还是第二层循环计数器n都是递增的，希望能重置第二层循环的计数器n。”

**Comment by luty2018** [comment]
暂时不支持
