### ISSUE TITLE
[BUG]接口自动化：循环中的接口不能设置启用禁用

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#21173]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

![企业微信截图_16730112772020](https://user-images.githubusercontent.com/39357523/211020590-bfbf7a1a-8197-4408-b01e-3910370fadb5.png)

### 重现步骤

接口自动化引入接口后，循环控制器下面的接口不能设置启用禁用

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题在2.6以上版本优化了，1.20的lts不再优化，如果感觉非常影响使用建议升级一下。
