### ISSUE TITLE
[BUG]v2.5.1, 批量选择接口，然后选择 导出成Swagger3.0格式，提示value is null.

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21185]
### 联系方式

王进

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

[BUG]v2.5.1, 批量选择接口，然后选择 导出成Swagger3.0格式，提示value is null.

### 重现步骤

1. 登录到MS v2.5.1
2. 批量选择接口
3. 点击导出》导出Swagger 3.0格式
4. 提示 value is null

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是否可以提供一下MS格式的复现数据？
