### ISSUE TITLE
[BUG]自动化测试场景导出为jmeter格式时，运行环境中的通用配置丢失

### ISSUE THREAD

**Issue by nico18576626619** [metersphere/metersphere#21201]
### 联系方式

274250917@qq.com

### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

自动化测试场景导出为jmeter格式时，运行环境中的通用配置丢失

### 重现步骤

1、自动化场景中随便选择一个场景，执行导出jmeter脚本操作
2、检查脚本的配置，发现通用配置项没有导出来
![image](https://user-images.githubusercontent.com/19904099/211267636-28db9a9e-d9ea-4c44-b65d-23f0dec15dde.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，场景里保存的时候有选择环境吗？
![image](https://user-images.githubusercontent.com/73461316/212022040-688ee00a-239a-4feb-a670-203091b817bc.png)
