### ISSUE TITLE
[BUG]IDEA插件导出部分接口报错

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#21213]
### 联系方式

张树彬

### MeterSphere 版本

1.20.16LTS

### 使用外置数据库

否

### 问题描述

使用最新IDEA插件，导出接口时，部分接口报错

### 重现步骤

1. 配置IDEA插件
2. 在IDEA里导出接口
3. 部分接口报错

### 期待的正确结果

正常使用IDEA插件导出接口

### 相关日志输出

```shell
日志已发给大海
```

### 附加信息

![f89c041532f9c722c8e0baef7a1bda8](https://user-images.githubusercontent.com/77324661/211282174-b14a65db-cb18-4226-832b-b352c71d5f32.jpg)

**Comment by zhangdahai112** [comment]
这个跟bin联系客户已经处理好了

**Comment by zrfit** [comment]
与研发沟通，用户修改表字段长度后该问题已解决。
