### ISSUE TITLE
[BUG] 定时任务-消息通知-通过率数据不准确

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#21225]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

测试计划定时执行，并设置了钉钉消息通知，钉钉收到的报告通过率与报告的通过率不一致

### 重现步骤

1.创建一个测试计划
2.设置定时任务
3.设置钉钉消息通知

### 期待的正确结果

钉钉收到通过率与报告数据一致

### 附加信息

1.钉钉收到的消息
![image](https://user-images.githubusercontent.com/45531073/211444248-a7d35d41-cbbd-4380-b95b-f2a06b3ce0d2.png)
2.报告
![image](https://user-images.githubusercontent.com/45531073/211445043-b512030f-2757-4107-a311-b98f17296e75.png)

**Comment by xulinde** [comment]
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/64065190/211740109-ae3926b7-dbdf-47ba-8727-ab1b44b3a14a.png">
![image](https://user-images.githubusercontent.com/64065190/211740121-669161db-f745-4909-9fc5-f3e9055782fe.png)

**Comment by xulinde** [comment]
v2.5.1已复现，v2.6版本修复～

**Comment by xulinde** [comment]
2.6.0版本已修复，请等待版本发布后验证
