### ISSUE TITLE
[BUG] idea export 接口到metersphere 报错

### ISSUE THREAD

**Issue by tiancaijunrui** [metersphere/metersphere#21226]
### 联系方式

email：zhacongjie@qgutech.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

是

### 问题描述

idea版本 2022.2.4
插件版本 1.2.1
metersphere 版本 2.5.1

### 重现步骤

![image](https://user-images.githubusercontent.com/16681429/211447458-e4a77b58-81d3-4581-bf7f-90e7e6a9f0ca.png)

### 期待的正确结果

上传成功

**Comment by luty2018** [comment]
可以更新idea插件到最新版本，MS也要升级到2.3以后的版本，如果还有问题可以重新打开issue

**Comment by zhangdahai112** [comment]
[metersphere-idea-plugin-1.2.2.zip](https://github.com/metersphere/metersphere/files/10869581/metersphere-idea-plugin-1.2.2.zip)
试试这个新打包的插件
