### ISSUE TITLE
[BUG] node-controller 调用报错

### ISSUE THREAD

**Issue by tiancaijunrui** [metersphere/metersphere#21239]
### 联系方式

email: zhacongjie@qgutech.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

是

### 问题描述

A机器部署了metersphere 全家桶，B机器部署了node-controller
性能测试选择LOCAL资源池没有问题，选B机器资源池报错。

### 重现步骤

压力测试-资源池，选择node-controller资源池
![image](https://user-images.githubusercontent.com/16681429/211486760-82229cc7-872e-48c2-bcee-00b55cf6f751.png)
![image](https://user-images.githubusercontent.com/16681429/211486829-97effc26-e02d-48a6-b85d-a3b2bff2a30b.png)
![image](https://user-images.githubusercontent.com/16681429/211486875-82a57491-3192-46ce-99e3-5243f5341d93.png)
![image](https://user-images.githubusercontent.com/16681429/211487021-4118d23b-3252-4501-a10c-a1ee05ec4545.png)

### 期待的正确结果

不报错

### 附加信息

部署在centos 8上。

**Comment by youliyuan-fit2cloud** [comment]
你好：
<img width="113" alt="image" src="https://user-images.githubusercontent.com/54612864/212033406-783a9250-c011-48a8-8929-6abbdf33cc99.png">

node-controller的端口不是默认的8082了？ 在MeterSphere系统资源池配置也是否修改了正确的端口 ？
参考如下：
![image](https://user-images.githubusercontent.com/54612864/212033661-390927ef-e7b6-4ca3-941d-672563275a94.png)

**Comment by tiancaijunrui** [comment]
> 你好： <img alt="image" width="113" src="https://user-images.githubusercontent.com/54612864/212033406-783a9250-c011-48a8-8929-6abbdf33cc99.png">
> 
> node-controller的端口不是默认的8082了？ 在MeterSphere系统资源池配置也是否修改了正确的端口 ？ 参考如下： ![image](https://user-images.githubusercontent.com/54612864/212033661-390927ef-e7b6-4ca3-941d-672563275a94.png)

![image](https://user-images.githubusercontent.com/16681429/215636711-4f2e592c-161a-4b45-b1c9-a3c682e5b7b1.png)
![image](https://user-images.githubusercontent.com/16681429/215636755-e7f726ad-2d00-43b3-a643-f32032096b87.png)

**Comment by liuruibin** [comment]
资源池添加成功了吗？

添加成功后选择资源池执行后台 /opt/metersphere/logs/performance-test/info.log 有什么报错

资源池本身的  /opt/metersphere/logs/node-controller/info.log 和 /opt/metersphere/logs/node-controller/ms-jmeter-run.log有什么报错

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
