### ISSUE TITLE
[BUG] 【接口测试】beanshell脚本点击设置环境参数出现多余 vars.put("key","value") 希望去除减少误导

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21236]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

beanshell脚本点击设置环境参数出现多余 vars.put("key","value") 希望去除减少误导

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/211481709-c1545fbe-0759-4940-8986-70ac8d71d75c.png)

**Comment by zyyfit** [comment]
这个是必要的，不是多余的，是为了防止用户在后续步骤有引用需求，如果只有第一行，那后续步骤会出现引用不到的情况

**Comment by Ycr123888** [comment]
可以给个注释嘛，用户有些难应用

**Comment by zyyfit** [comment]
目前决定先在操作手册里加一个使用说明
