### ISSUE TITLE
[BUG]v2.5.1, 测试计划执行UI自动化测试，偶现 通过率不准确，有些场景一直running，执行时间比2.2.1多一倍等问题

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21231]
### 联系方式

王进

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

v2.5.1, 测试计划执行UI自动化测试，偶现 通过率不准确，有些场景一直running，执行时间比2.2.1多一倍等问题

### 重现步骤

1. 客户一直用v2.2.1，维护了160个UI自动化场景
2. 之前升级到 2.4.1，后回撤到2.2.1
3. 这次因为安全升级到2.5.1。
4. 相同的测试计划，测试计划里有160个UI自动化场景，现在执行出现多个问题：
     1. 执行偶现中断
     2. 报告数据不准确：报告列表页 显示通过率 89%，报告详情页 显示通过率45%。
     3. 执行效率比之前慢很多

### 附加信息

相关日志已转给开发。

**Comment by youliyuan-fit2cloud** [comment]
你好，未复现问题，请补充详细的复现场景，包括测试计划配置，正常执行时长，以及日志详情。

**Comment by 35plus** [comment]
![1673339496022](https://user-images.githubusercontent.com/76033005/211500395-c2b15414-e434-4fca-aa77-76307eb0271e.png)
UI-Test 将近30分钟无任何日志输出，此时服务卡住了。 

test-track的日志 也印证了这点。
![1673339520589](https://user-images.githubusercontent.com/76033005/211500661-704762d9-f47b-49a9-8ec6-0ae02e403be6.png)

客户的机器 16C  32G内存，之前 同样的测试计划 只要20分钟，10个sessions。 

目前相同的环境6sessions，就能把UI test服务跑挂了。

**Comment by youliyuan-fit2cloud** [comment]
经开发同事复现分析上述问题，原因如下：
1.ui-test堆内存溢出导致重启 ,把docker内存调成4G或者最大堆内存搞成1.5G 是比较稳定了
2.执行效率问题，微服务以后，以前本地执行的线程，可能需要跨服务，消耗的cpu会多一些，同等资源下，比单体服务效率是会下降不少，通过尝试把grid单独部署在一台服务器上 35分左右能跑完，cpu核数有限的情况下  并发数设置9和11 差别并不大  设置多了反而更慢，如果把grid的资源耗满了，会导致页面没渲染出来就下个指令了，会是导致不稳定的因素。
如果用户还要再提升效率，要么加机器配置，要么用grid集群模式部署。我们微服务以后对配置的要求比单体服务也增加了  。
