### ISSUE TITLE
[BUG]v1.20.18,  测试计划里 添加10个 关联了接口自动化场景的功能用例，删除了8个功能用例，执行测试计划，测试报告统计出现错误

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21246]
### 联系方式

王进

### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

 测试计划里 添加10个 关联了接口自动化场景的功能用例，删除了8个功能用例，执行测试计划，测试报告统计出现错误

### 重现步骤

1. 新建plan时添加10个手工用例，其中有8个link了场景用例
2. 删除了8个用例，保留两个link了场景用例的手工用例
3. 执行测试
问题：
1. 总体用例数还是10个，而不是删除后的2个
2. 执行率错误
3. 通过率错误
4. 2个保留的手工用例是没有执行的状态
5. 执行的API用例是8个，而不是删除手工用例后的2个
6. 执行过API用例后，没有将结果同步到手工测试用例的comments中

### 附加信息

如上步骤是客户反馈过来，昨天晚上跟客户一起测试，确实存在描述的问题。

**Comment by zyyfit** [comment]
请确认几个地方：
1、步骤2中删除的8个用例，是功能用例还是场景用例？
针对这条解释一下：在测试计划里关联功能用例可以同步关联相关的场景用例，但是取消关联的时候不会同步取关，如果有需要，可以手动取关场景用例
2、步骤4中，如果场景用例没有手动取关，用例数是10是正确的
3、步骤5、步骤6中，执行率和通过率，具体是哪里错误？应该是多少？报告里显示的是多少？每个case的结果都是什么？
4、步骤7中，在测试计划列表点击执行按钮执行整个测试计划时，如果测试计划编辑窗口中没开启 “自动更新状态” 选项，不会把场景用例的结果同步到功能用例上，功能用例的状态就是不会变的
5、步骤8和步骤9的问题已经在前面解释过了
如果有补充，请补充的详细一些

**Comment by 35plus** [comment]
ok，那为什么功能用例关联的接口自动化用例执行了，但是 功能用例的状态没有发生改变呢？
