### ISSUE TITLE
[BUG] 引用场景复制后名称不可更改

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2125]
**MeterSphere 版本**
1.8.2

**Bug 描述**
引用一个场景，然后点击该场景右侧的复制按钮复制该场景，结果复制的场景名称为<原场景名称>_copy，而且名称无法修改

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
复制的场景与原场景名称相同

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，引用的场景目前不允许进行编辑等操作，您想复制的话可以在添加的时候选择复制场景

**Comment by guhan121** [comment]
@zyyfit 这个操作是先引用然后在复制引用那一步

结果把引用的名字改了；但是重新打开名字又正常了
