### ISSUE TITLE
[BUG]接口自动化使用文档结构断言无法保存场景，前端报错TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#21250]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.4.0和v2.6的QA release环境都复现了

### 使用外置数据库

否

### 问题描述

接口自动化使用文档结构断言无法保存场景，前端报错TypeError: Cannot read properties of undefined (reading 'type')

### 重现步骤

1.创建接口自动化场景，添加任意请求
2.在请求的断言中添加文档结构断言
3.保存场景，页面无响应
![image](https://user-images.githubusercontent.com/88763608/211529059-2e489533-56ed-4603-b6a4-9579d529ab12.png)

### 期待的正确结果

可以正确保存

**Comment by zyyfit** [comment]
qa环境现在没复现了，请确认是否已修复

**Comment by linfengjjj** [comment]
已修复
