### ISSUE TITLE
[BUG]  测试计划报告，失败重跑，不生效

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21267]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.5.1

### 使用外置数据库

否

### 问题描述

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/33945037/211709328-24588d23-8ca1-4d32-b1e2-95efc7aae891.png">

1. 测试计划报告里面，点击失败重跑，不生效，查看后台日志并没有执行日志输出

### 重现步骤

参考如上

**Comment by zyyfit** [comment]
您好，2.6.0版本没有复现这个问题，请问是必现的吗？能详细描述一下复现步骤和条件吗
