### ISSUE TITLE
[BUG]配置等待控制器和循环控制器的循环间隔时间，实际执行时间远远长于配置的数值

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2126]
**MeterSphere 版本**
1.8.2

**Bug 描述**
配置等待控制器和循环控制器的循环间隔时间，实际执行时间远远长于配置的数值

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
循环控制器下多个步骤的时候；每个步骤都等待循环时间

**Comment by zyyfit** [comment]
> 循环控制器下多个步骤的时候；每个步骤都等待循环时间

您好，我的理解，循环间隔应该是每个步骤都等待的，您想要每个循环之间进行等待的话可在循环的最后添加等待控制器
