### ISSUE TITLE
[BUG]  测试计划关联接口用例（接口用例中后断言脚本），执行测试计划，当断言失败时，在报告中查看断言脚本，弹框被掩盖在了报告页面下面，弹框层级不对

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21266]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

1. 创建接口用例设置断言脚本
2. 创建测试计划，并关联带有断言脚本的接口用例。
3. 执行测试计划，当断言失败的时候，在测试计划报告中查看，则看不到断言脚本。当关闭了当前报告页面，就能看到。说明弹框的层级不对。

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/33945037/211708871-c0a70987-009b-40a1-8680-7b938c3c9a29.png">
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/33945037/211708949-96419306-4a5c-411c-a40f-0a1df5c3d6fe.png">
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/33945037/211709052-94a434cd-899a-45d1-a988-1acd6150fc9e.png">

当关闭报告之后，就能看到弹框。
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/33945037/211709123-387f0c02-5c7b-4de3-a0ba-2778e9a2f7ba.png">

### 重现步骤

参考如上

**Comment by youliyuan-fit2cloud** [comment]
你好，v2.6.0版本没有复现，升级一下再试试吧，如果还有问题请随时反馈，感谢～

**Comment by youliyuan-fit2cloud** [comment]
> V2.6还有问题
> 
>  2023-01-20.17.59.22.mov

感谢视频反馈，已复现，下个大版本修复。

**Comment by zrfit** [comment]
v2.6.1已修复，待发布后可升级验证。
