### ISSUE TITLE
[FEATURE]场景的模块如果有多级无法直接定位到，尤其是有模块名字重复时候无法区分

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2127]
**请描述您的需求或者改进建议.**

场景的模块如果有多级无法直接定位到，尤其是有模块名字重复时候无法区分

**请描述你建议的实现方案**

显示多级目录名字，例如AAA/BBB，而且下拉列表可以直接展开到当前选择的节点

**Comment by xulinde** [comment]
您说的是这里吗
![image](https://user-images.githubusercontent.com/64065190/115491068-e2905700-a291-11eb-8738-992727b43788.png)

**Comment by guhan121** [comment]
![image](https://user-images.githubusercontent.com/5517369/115516637-ea172680-a2b8-11eb-8fbe-b338444b1726.png)
如我的图
没有直接跳转到 5下面

**Comment by guhan121** [comment]
期望是展开树
定位到展开的节点
![image](https://user-images.githubusercontent.com/5517369/115516939-35313980-a2b9-11eb-8df1-cff03256d7a1.png)
