### ISSUE TITLE
[BUG]复制场景用例时；场景用例的创建人还是旧的人

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2128]
**MeterSphere 版本**
1.8.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/2014
