### ISSUE TITLE
[FEATURE]场景用例的“编辑页面”无法看到场景用例的id

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2129]
**请描述您的需求或者改进建议.**

场景用例的“编辑页面”无法看到场景用例的id

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
你好，场景用例的id可以直接在场景列表看的

**Comment by guhan121** [comment]
主要的问题是 进入编辑页面后 你想知道ID把ID给别的同学 需要切回列表 然后根据用例名称找到当前的ID； 过程体验你懂得
