### ISSUE TITLE
[FEATURE]希望添加基础工具，如随机数和时间戳

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#213]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> **请描述你建议的实现方案**

1.2版本就会支持了，请关注月底的版本发布说明会哦

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
