### ISSUE TITLE
[BUG]测试计划关联未选择环境的场景执行获取不到环境设置的通用变量

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21307]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

测试计划关联未选择环境的场景执行获取不到环境设置的通用变量
备注：客户从v1.20.16-tls版本升级到v1.20.18-tls，在升级之前测试计划一直正常获取环境变量，升级后测试计划部分场景获取不到环境变量，手动执行重新选择环境依旧获取不到环境变量，重新关联这些场景依旧获取不到环境变量，经排查这些场景中保存的环境丢失（调试页,非测试计划），在场景中重新选择环境保存，调试场景，测试计划重新关联场景恢复，测试计划中场景才可以正常获取环境变量。
在我们环境未复现，拿客户的场景在我们环境可以复现。

### 重现步骤

1.导入客户场景，导入场景后，不编辑不进行调试
2.导入客户环境
[环境.zip](https://github.com/metersphere/metersphere/files/10389894/default.zip)
3.测试计划关联导入的客户环境，执行测试计划，请求内容中可看到未获取到环境变量
![image](https://user-images.githubusercontent.com/103627487/211749367-8e61ac92-f2a1-4eef-ac74-33dfd7c4f993.png)
4.场景选择环境，变量能正常获取
![image](https://user-images.githubusercontent.com/103627487/211749112-ff0b9626-5d4a-4d21-891f-84bb7392ba10.png)
5.场景中保存环境，调试，保存场景
6.再次执行测试计划,环境变量能正常获取到

**Comment by zyyfit** [comment]
这个文件下载不下来，请重新发一个吧

**Comment by meijieDouDou** [comment]
[场景和环境.zip](https://github.com/metersphere/metersphere/files/10399932/default.zip)

**Comment by zyyfit** [comment]
收到，后续版本修复

**Comment by zyyfit** [comment]
1.20.19版本已修复，请等待版本发布后验证
