### ISSUE TITLE
[FEATURE]点击左侧场景模块自动跳转到场景列表tab并清除搜索框中的filter

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2130]
**请描述您的需求或者改进建议.**
点击左侧场景模块自动跳转到场景列表tab并清除搜索框中的filter

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.点击左侧场景模块自动跳转到场景列表tab，这个当前就是这样实现的
2.我确认下能否这样优化

**Comment by guhan121** [comment]
嗯   1确实是 

麻烦看看2
