### ISSUE TITLE
[BUG]编辑用例后，用例状态变为通过

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#21306]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

版本:   v1.20.17-lts-c59a4086

### 使用外置数据库

是

### 问题描述

功能用例 评审通过的用例  复制这条用例  编辑保存后 用例状态是未评审  但 再次编辑保存 会变成评审通过

### 重现步骤

1.功能用例 评审通过的用例  复制这条用例
2.复制这条用例  编辑保存后 用例状态是未评审
3.但再次编辑保存 会变成评审通过

### 期待的正确结果

再次保后用例状态应该是未评审的

**Comment by xulinde** [comment]
v1.20.18-lts未复现该问题，建议您升级下版本
