### ISSUE TITLE
[BUG]断言规则适用JSONPath推荐方式，当列表索引值超过10，期望值无法自动填写

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#21303]
### MeterSphere 版本

2.5.1 & 1.20.18 lts

### 使用外置数据库

否

### 问题描述

1、断言规则适用JSONPath推荐方式，当列表索引值超过10，期望值无法自动填写。
2、响应体内容显示和JSONPath提取中的显示不一致，Key和Value的引号在这两处显示不一致，易造成误解。

### 重现步骤

1、添加JSONPath方式添加断言规则。
2、点击「推荐JSONPath断言」。
3、点击选择 JSON 内容中的列表索引超过10的便签。
4、JSONPath可正常自动填入，但期望值栏无法自动填入。

### 期待的正确结果

希望/要求对应的期望值可以自动填入。

### 附加信息

![image](https://user-images.githubusercontent.com/46042812/211746034-a040ab60-3cd9-42f5-a6d8-12acca1dca37.png)

**Comment by zyyfit** [comment]
2.6.1 版本已修复，请等待版本发布后验证，1.20版会在1.20.20版本修复

**Comment by youliyuan-fit2cloud** [comment]
在即将发布的v1.20.20-lts中验证通过，请关注发布信息。
