### ISSUE TITLE
[BUG]【接口自动化】导入JMX文件，JMX里的【用户自定义变量】控件的变量没有正常使用

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21314]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【接口自动化】导入JMX文件，JMX里的【用户自定义变量】控件的变量没有正常使用

### 重现步骤

1. 在 JMeter 上正常执行该 JMX 脚本

![image](https://user-images.githubusercontent.com/104960608/211773701-490ca60b-abb7-4d60-a022-f5758598b323.png)

![image](https://user-images.githubusercontent.com/104960608/211773767-cba98eda-8330-489c-959f-9029cdd7fdde.png)

![image](https://user-images.githubusercontent.com/104960608/211773845-ae408f4d-6c4a-4db8-9f55-dd2d34e145ae.png)

2. 将该 JMX 脚本导入 MS 系统【接口自动化】场景中，没有选择任何环境，直接点击调试，运行报错

![image](https://user-images.githubusercontent.com/104960608/211776324-df37242e-45ef-4775-a107-31820fc82a5d.png)

![image](https://user-images.githubusercontent.com/104960608/211776422-8a9cad1f-7c79-4c6a-bb91-3ad57bbd96f7.png)

出现的问题是:  JMX 文件的【用户自定义变量】控件没有正常使用，在【用户自定义变量】的端口是8081，最终结果里端口10990也不知道咋来的

**Comment by zyyfit** [comment]
2.6.0版本已修复，请更新验证
![image](https://user-images.githubusercontent.com/73461316/212051992-9900a612-2bc1-4cd9-9338-c5ab7e5c74cc.png)
