### ISSUE TITLE
[BUG] 【接口测试】Mock状态关闭后，切换页签，再回到Mock界面，又被开启

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21311]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

Mock状态关闭后，切换页签，再回到Mock界面，又被开启

### 重现步骤

Mock状态关闭后，切换页签
![image](https://user-images.githubusercontent.com/103925124/211773187-f3be6501-400e-4278-bd29-f2b97c55b2dd.png)
再回到Mock界面，又被开启
![image](https://user-images.githubusercontent.com/103925124/211773397-402d17c0-ecdd-4b48-b79b-b0b909b6d3eb.png)

**Comment by song-tianyang** [comment]
这个问题在即将发布的2.6上被发现和修复了。谢谢~
