### ISSUE TITLE
[BUG]场景内点击单步骤执行，提示“调用资源池执行失败，请检查资源池是否配置正常”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21310]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

禁用本地执行，场景点击调试正常执行，场景内点击单步骤执行，提示“调用资源池执行失败，请检查资源池是否配置正常”，不是所有场景都有这个问题，个别场景会有这个问题。(复现场景已上传附件）
[Uploading Metersphere_Scenario_ESOP境外员工管理系统.zip…]()

### 重现步骤

1.导入场景
2.随便选择环境，点击单步骤调试。提示“调用资源池执行失败，请检查资源池是否配置正常”
![image](https://user-images.githubusercontent.com/103627487/211768983-3f6a509d-52ad-40b0-8748-b617f9f73079.png)
3.点击调试执行正常
![image](https://user-images.githubusercontent.com/103627487/211769223-0dac2b57-930f-44d7-9fb1-94ca33dc7174.png)

### 期待的正确结果

期望单步骤也能正常执行

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.19版本已修复，请等待版本发布后验证
