### ISSUE TITLE
[FEATURE]测试计划 改进

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2132]
**请描述您的需求或者改进建议.**
1. 取消测试计划的下拉操作改为直接跳转到测试计划列表
2. 测试计划增加按钮 “一键重试”  —— 重试所有失败用例
3. 点击测试计划中的测试用例标题；可以直接找转到对应用例编辑页

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.点击测试计划名称可以跳转
2.我们先讨论下
3.测试计划是执行用例的，直接跳转到编辑用例页不是很合理吧

**Comment by xulinde** [comment]
1.点击测试计划名称可以跳转
2.我们先讨论下
3.测试计划是执行用例的，直接跳转到编辑用例页不是很合理吧

**Comment by guhan121** [comment]
3  你这个测试计划中的用例本来就不是复制的啊；
用例不过如果要改测试计划里面的用例还不是需要去用例编辑页面
如果是testlink那样测试计划里面的用例是属于复制；那就没问题
