### ISSUE TITLE
[BUG]接口自动化，进行批量禁用步骤操作后，单独启用某个步骤，调试时前后置脚本的功能没有被启用。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21328]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

接口自动化，进行批量禁用步骤操作后，单独启用某个步骤，调试时前后置脚本的功能没有被启用。
<img width="716" alt="1673444368685" src="https://user-images.githubusercontent.com/83771182/211822478-fb83caa6-0e89-4e99-be4e-814acd1ad71d.png">
单独启用某个步骤后调试，调试时前后置脚本的功能没有被启用
<img width="735" alt="1673444521067" src="https://user-images.githubusercontent.com/83771182/211822549-5d4c3911-e9c9-475c-8e0e-c88d6dd7e7fc.png">

### 重现步骤

接口自动化，进行批量禁用步骤操作后，单独启用某个步骤，调试时前后置脚本的功能没有被启用。
不做批量禁用脚本执行没有问题
<img width="757" alt="1673444686869" src="https://user-images.githubusercontent.com/83771182/211822684-25dc422a-fb93-472c-96f9-bc77144564dc.png">

### 相关日志输出

```shell
无
```

**Comment by xulinde** [comment]
和研发确认了下，不会自动给启用，需要手动调整
