### ISSUE TITLE
缺陷管理页面增加修改时间字段

### ISSUE THREAD

**Issue by 327282227** [metersphere/metersphere#21329]
### MeterSphere 版本

 v2.1.1-96b84b46

### 联系方式

327282227@qq.com

### 请描述您的需求或者改进建议

缺陷管理页面增加修改时间字段，方便相关人员知道开发是什么修复了bug，方便统计。

**Comment by luty2018** [comment]
可以的， 这个字段数据库已经有了，下个版本展示到列表里
