### ISSUE TITLE
[BUG]【接口自动化】导入 JMX 的请求与场景中自定义请求，请求地址都是一样的，但是导入的请求没有正常使用场景变量设置的port值

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21323]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.5.1

### 使用外置数据库

否

### 问题描述

【接口自动化】导入 JMX 的请求与场景中自定义请求，请求地址都是一样的，但是导入的请求没有正常使用场景变量设置的port值

### 重现步骤

1. 【接口自动化】设置场景变量，ip和port变量

![image](https://user-images.githubusercontent.com/104960608/211789074-e62e9c17-3cfb-41fc-955e-19578ccaa2e6.png)

2.  将 JMX 的HTTP请求导入MS系统接口自动化场景中，将其他都删除，只留下请求

![image](https://user-images.githubusercontent.com/104960608/211789967-83a438ea-bea7-42bb-a002-8f2802b9676f.png)

![image](https://user-images.githubusercontent.com/104960608/211789881-2d57947b-fb6f-4f61-95e2-d2e2a620b73d.png)

3. 在场景中添加自定义请求，请求地址与 JMX 一样

![image](https://user-images.githubusercontent.com/104960608/211790280-672bdabd-5f26-4260-a1a0-cff359844702.png)

4. 运行这两个请求，发现从 JMX 文件导入的请求是失败的，只使用了场景变量中的ip，没有使用port，端口出现10990，在场景中新增的自定义请求是正常使用场景中的ip和port

![image](https://user-images.githubusercontent.com/104960608/211790820-f8bc73a5-f123-4127-a3d3-90b1af2711d2.png)

![image](https://user-images.githubusercontent.com/104960608/211790897-b763a65d-e991-4628-8bdb-78de11e07e35.png)

**Comment by zrfit** [comment]
v2.7已修复该问题。
