### ISSUE TITLE
[QUESTION]集成至DEVOPS实现自动持续测试

### ISSUE THREAD

**Issue by net2817** [metersphere/metersphere#2133]
**请描述您的问题.**
研发开发的模板通过JENKINS构建时，自动通过脚本或程序扫描接口相关信息，并生成相关的测试用例与断言，上传至metersphere上面

扫描至的文件以什么样的格式怎么上传至metersphere ，有没有示例？

**Comment by xulinde** [comment]
平台目前还没这个功能
