### ISSUE TITLE
[BUG]使用环境组执行场景用例，不能保存数据到另外一个项目的环境变量

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21345]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

在 A 项目中不能修改 B 项目的环境变量

### 重现步骤

> 一个项目，不使用环境组，可以修改环境变量
1.项目 A，创建场景用例，添加脚本步骤
vars.put(${__metersphere_env_id}+"tokenA","tokenA");
vars.put("tokenA","tokenA");
2.执行用例选择单个环境
![image](https://user-images.githubusercontent.com/4860962/212006037-9e807116-fe04-42d6-b8bb-95d126f84ff4.png)
3.查看环境，可以正常修改环境变量值
![image](https://user-images.githubusercontent.com/4860962/212006231-9e3a48b5-bad1-476c-b204-c6259d1cfb13.png)

> 2 个项目（A和 B），使用环境组（环境组顺序第一个是 B，第二个是 A）
同上面的步骤，但是选择环境时选择环境组，执行后再次查看环境变量
![image](https://user-images.githubusercontent.com/4860962/212006495-8e25b15d-c249-4572-8934-d95a417ced3e.png)

在 A 项目中执行用例，发现环境变量被保存到了 B 项目中

> 2个项目
1.在 B 项目的场景用例中引用 A 项目的场景用例
2.执行 B 项目中的场景用例，发现 A 项目的场景用例中的保存环境变量不能生效（即保存数据到 A 项目的环境变量中）

### 期待的正确结果

1.同一个项目中使用环境组，数据不会保存到其他项目
2.希望在 B 项目中可以修改 A 项目的环境变量

**Comment by zrfit** [comment]
您好，最新版本v2.6.0未复现该问题，请升级尝试。

**Comment by hao1032** [comment]
我当前不是 2.6，和你再确认一下，12 号你们的人还在说不支持。你的验证结果是 2.6 已经支持了？？？
<img width="694" alt="image" src="https://user-images.githubusercontent.com/4860962/212806485-26e8abeb-f7a4-4b4e-86c5-a972fdac1275.png">

**Comment by zrfit** [comment]
经过和用户沟通已经复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v2.6.1已修复，待发布后可升级验证。
