### ISSUE TITLE
自动化场景导入，点击导入按钮后，整个页面致灰[BUG]

### ISSUE THREAD

**Issue by guoxin92** [metersphere/metersphere#2134]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
自动化场景导入，点击导入按钮后，整个页面致灰
**Bug 重现步骤**
1.  点击接口自动化测试，现选择一个场景，点击场景导入
![image](https://user-images.githubusercontent.com/80814232/115332385-4bac9780-a1ca-11eb-8f3b-c546aa349aa1.png)

2. 点击更多操作，选择导入
![image](https://user-images.githubusercontent.com/80814232/115332443-667f0c00-a1ca-11eb-9bd5-0608fa959ee0.png)

3. 页面致灰 ，w无法进行任何操作
![image](https://user-images.githubusercontent.com/80814232/115332494-86aecb00-a1ca-11eb-9988-c7c3e53cc4b0.png)

**期待的正确结果**
正确情况下应该是什么样的？
能正常导入
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题
