### ISSUE TITLE
[FEATURE]期望可以在场景用例中直接编辑保存引用的用例

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21354]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

1.场景用例中引用了很多用例，这些用例因为很多参数都是依赖场景上一步的结果，因此不能单独执行。
2.在场景用例的实际编写过程中经常需要修改引用的用例（需要添加一个提取参数、修改断言等）
3.因为不能单独执行，提取参数或者修改断言很麻烦，需要修改配置很多临时参数

### 请描述你建议的实现方案

希望可以在场景用例直接编辑和保存引用的用例

**Comment by luty2018** [comment]
如果要修改为啥不用复制呢？目前我们引用的规则就是不允许修改，否则没法做到保持引用最新

**Comment by hao1032** [comment]
> 如果要修改为啥不用复制呢？目前我们引用的规则就是不允许修改，否则没法做到保持引用最新

1.之前和你们咨询过，给的建议是尽量通过 ***引用*** 使用用例
<img width="891" alt="image" src="https://user-images.githubusercontent.com/4860962/212042766-68d68fca-4af0-4479-b60d-654030323c74.png">

2.我认为也应该使用引用，一旦接口有变化可以通过修改一个用例就能解决问题
3. "如果要修改为啥不用复制呢？" 我觉得你的这个问题不太对
- 用例都是要维护的，所以用例修改很正常
- 编写用例过程中，修改也是很频繁的


”目前我们引用的规则就是不允许修改“
1. 我这个提的是一个建议，不是 bug
2. 规则如果不合理或者能更好，是不是可以修改？

”否则没法做到保持引用最新“
1. 这个没有明白为什么直接编辑保存，就不能保持引用最新了呢？
2. 当前需要新开页面保存编辑，编辑后还要在场景用例里面点击刷新按钮吧，是不是当前也不能 保持最新？

当前 ms 提供了引用用例的能力，我在使用这个功能，在使用这个功能的过程中我遇到了一些不方便的地方，因此提了一个建议，我理解收集这些痛点是 ms 做开源希望看到的。

另外再补充一下当前不能直接编辑的，导致的问题
1. 当前要修改引用的 case 必须要新窗口编辑保存
2. 因为需要依赖字段，因此需要将已有变量（如：${num}）修改为具体值(如：3)
3. 然后发起请求，得到请求的返回结果，才能编辑 参数提取或者断言（我这边主要使用 jsonpath）
4. 编辑完成后保存，这时经常忘记将 字段具体的值修改为原来的 变量引用
5. 然后用例就会出现莫名其妙的问题，因为没有使用变量而是一个固定的值

ps：假设一个接口有 10 个字段，仅仅就是【变量 修改为 具体值】【具体值 修改为 变量】，这 2 个步骤就让人抓狂。

**Comment by luty2018** [comment]
非常感谢你的耐心解答，我的回复可能有些理解偏差，没有理解到你的修改是指的直接修改源用例。
这里也会出现一个用例被多个人引用，如果直接在场景引用里就对源用例进行修改也会造成其他case都受影响。这里是有风险的。
而跳转到源用例里面改，是因为源用例页面可以查询并通知所有引用的case

对于你实际应用遇到的问题，特别是第2点，我没有理解，是否可以加我的企业微信，进一步沟通，以免造成理解偏差。

**Comment by hao1032** [comment]
> 非常感谢你的耐心解答，我的回复可能有些理解偏差，没有理解到你的修改是指的直接修改源用例。 这里也会出现一个用例被多个人引用，如果直接在场景引用里就对源用例进行修改也会造成其他case都受影响。这里是有风险的。 而跳转到源用例里面改，是因为源用例页面可以查询并通知所有引用的case
> 
> 对于你实际应用遇到的问题，特别是第2点，我没有理解，是否可以加我的企业微信，进一步沟通，以免造成理解偏差。

可以的，怎么加你企业微信啊？

**Comment by luty2018** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/36292514/219532365-c893a3dd-a394-49c2-9304-d72eddd48d3d.png">
你所在的交流群添加一下。
