### ISSUE TITLE
[BUG]测试跟踪-测试计划 报告报错

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#21359]
### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划 报告报错

### 重现步骤

测试跟踪-测试计划 报告报错

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/212244210-5992422e-fc94-4b06-b7a9-569ffb298287.png)
![image](https://user-images.githubusercontent.com/19423100/212244268-9dae9858-e810-4056-803f-fa849be80dd6.png)
![image](https://user-images.githubusercontent.com/19423100/212244313-92c56c99-6647-4b62-8690-f5088afa781c.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/215922571-1add4af9-9790-4200-bc4d-1fbcf60ffbc1.png)

**Comment by luty2018** [comment]
已纳入性能优化

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且最新版本已优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
