### ISSUE TITLE
[BUG]v1.20.18, 用例模板添加了多个多种类型字段后，导入的用例在web 列表页不可见，但是在脑图模式可见

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21366]
### 联系方式

王进

### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

v1.20.18, 用例模板添加了多个多种类型字段后，导入的用例在web 列表页不可见，但是在脑图模式可见

### 重现步骤

1. 重现步骤比较长，请参照如下金山文档，进行重现：
【金山文档】 自定义字段问题复测
https://kdocs.cn/l/cqXuvcYMJpgk
![1673706422068](https://user-images.githubusercontent.com/76033005/212476874-fceebf2d-9993-4ce0-83d7-d235f7bf12eb.png)

### 附加信息

客户环境有该问题，在交付内部环境已复测。

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。

**Comment by 35plus** [comment]
是这周的1.20.19么？

**Comment by youliyuan-fit2cloud** [comment]
> 是这周的1.20.19么？

计划 是2023.02.03 。

**Comment by 35plus** [comment]
能不能 这周？客户这边服务的是海外客户，他们的海外客户，也是MS的用户，海外客户不过春节。

**Comment by liqiang-fit2cloud** [comment]
不是致命缺陷也不是严重缺陷，请等待排期。

**Comment by zrfit** [comment]
v1.20.19-lts已修复该问题，待发布后可升级验证。
