### ISSUE TITLE
[BUG]接口测试导入失败，提示「格式错误」

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#21362]
### MeterSphere 版本

2.6

### 使用外置数据库

否

### 问题描述

接口导出后再不同的项目下再导入；
之前版本导出的json文件再倒入；

以上两种情况都提示「格式错误」

### 重现步骤

1、在接口定义的API列表，选中多条，执行导出操作（MeterSphere格式），生成a.json文件
2、在另外一个项目中，在接口定义页面，选择导入刚导出的a.json文件，MeterSphere格式+不覆盖模式，点击「保存」按钮，提示「格式错误」。
以上操作在2.5.1上执行正常。

### 附加信息

![image](https://user-images.githubusercontent.com/46042812/212255558-f657d2aa-289b-4e55-a8c1-7992aa5665eb.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您导出的ms格式文件上传给我们看一下吗？可以把文件后缀改成txt后上传
