### ISSUE TITLE
[BUG]手动执行的时候环境选择的是dev环境，第一个登录接口获取token的脚本执行的是qa环境，而其余脚本执行的是dev环境

### ISSUE THREAD

**Issue by yunyun0909** [metersphere/metersphere#21365]
### 联系方式

z1136300527y@163.com

### MeterSphere 版本

 v1.20.16-lts-3bb3478d

### 使用外置数据库

是

### 问题描述

手动执行的时候环境选择的是dev环境，第一个登录接口获取token的脚本执行的是qa环境，而其余脚本执行的是dev环境
![image](https://user-images.githubusercontent.com/96361738/212464182-0c90fed3-5353-4c94-867f-d5267b6cc483.png)
![image](https://user-images.githubusercontent.com/96361738/212464188-47cb8228-bdbe-4457-92c5-32c3585c2635.png)

### 重现步骤

在该版本，手动执行的时候环境选择的是dev环境，第一个登录接口获取token的脚本执行的是qa环境，而其余脚本执行的是dev环境

### 期待的正确结果

选择那个环境，所有接口都在该环境执行

**Comment by zrfit** [comment]
您好，感谢您的反馈，请确认下：
1、看您的截图是在测试计划模块-确认下测试计划-接口用例列表-第一个登录接口获取token的用例的运行环境字段是dev环境吗？
2、测试计划-操作-执行或者用例列表批量执行或者单独执行-如果不选择环境-则按关联用例时选择的运行环境执行。
