### ISSUE TITLE
[BUG]接口自动化场景如果复制或引用了调试好的 上传传附件的接口用例或场景用例，会出现找不到附件的情况。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21364]
### 联系方式

王进

### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

接口自动化场景如果复制或引用了调试好的 上传传附件的接口用例或场景用例，会出现找不到附件的情况。

### 重现步骤

1. 调试好一个上传附件的接口用例。
2. 新创建一个接口自动化场景，复制或引用 刚刚调试好的接口用例。
3. 保存新建场景，点调试，会出现找不到文件的情况。 --MS当前是在当前场景的/opt/metersphere/data/body/场景uuid/目录下寻找附件，不会去 被引用或复制的 接口用例 的/opt/metersphere/data/body/被引用接口用例/ 下 找附件。
4. 只能在当前场景下，重新上传附件，这样才行。

### 附加信息

MS当前是在当前场景的/opt/metersphere/data/body/场景uuid/目录下寻找附件，不会去 被引用或复制的 接口用例 的/opt/metersphere/data/body/被引用接口用例/ 下 找附件。

**Comment by zyyfit** [comment]
您好，没有复现这个问题，引用和复制都试了，都是成功的，如果方便的话请上传一下原始场景

**Comment by 35plus** [comment]
1.20.18， 上这个问题是真实存在的
![5e686af45f3fff85c7cd893ed20e24d](https://user-images.githubusercontent.com/76033005/212610608-87c01115-8447-42e1-85e7-0108033dd02e.png)

**Comment by 35plus** [comment]
我自己和客户一起测试的：
1. 客户的MS是部署在/app目录下
2.  升级到1.20.18之前没有这个问题。
3. 上面的截图 提示  在容器里/opt/metersphere/data/body/e8... ...  提示找不到附件，
4. 实际附件是在 被引用的场景 的id目录下。 
5. 从错误日志看，当前场景执行上传附件  只是在 当前场景的 目录下，没有去 被引用场景的 目录下找附件。

**Comment by zyyfit** [comment]
已确认是原始文件丢失，暂时不知道是什么操作导致了文件丢失，如果能复现的话再处理
