### ISSUE TITLE
[BUG]UI测试，设置定时任务执行后，截图显示图片加载失败

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21360]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

UI测试，设置定时任务执行后，截图显示图片加载失败

### 重现步骤

1.创建UI测试脚本，设置定时任务执行
2.定时任务执行后，截图处显示图片加载失败
![image](https://user-images.githubusercontent.com/103627487/212245346-442eea85-6694-4e02-928a-9e2f79c7e314.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.19-lts已修复该问题，待发布后可升级验证。
