### ISSUE TITLE
[BUG]资源文件读取不了 mp4 文件

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#21363]
### 联系方式

13735892260

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

脚本中采用mp4文件上传，无法读取数据文件

### 重现步骤

1、项目配置上传了 JMeter 脚本（该脚本是文件上传，需要读取 mp4 文件）；
2、在性能测试中创建压测场景，添加 jmx 后，数据文件添加 mp4 文件，发现搜索不出来，然后采用本上传方式，发现 MP4 文件无法读取。

### 期待的正确结果

可以读取数据文件

**Comment by zyyfit** [comment]
您好，jmx文件里应该无法关联我们的系统文件，本地上传的方式我没有复现出来，请检查一下服务器中的文件路径和jmx里的文件路径是否一致

**Comment by hztony** [comment]
2.7.0 上依旧不能读取 mp4 文件
