### ISSUE TITLE
[FEATURE][需求]测试报告计算通过率时，建议不要将跳过的用例进行统计

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#21369]
### MeterSphere 版本

2.4.0

### 请描述您的需求或者改进建议

测试报告计算通过率时，建议不要将跳过的用例进行统计

### 请描述你建议的实现方案

测试报告计算通过率时，建议统计：通过用例、失败用例、未执行用例来计算通过率等指标；

### 附加信息

![企业微信截图_16738372038855](https://user-images.githubusercontent.com/6109912/212587876-2bf9eb88-a103-4db6-b80c-dfb6e9a80ef4.png)

**Comment by luty2018** [comment]
感谢反馈，通过率确实只计算通过的，我们确认下是否bug

**Comment by luty2018** [comment]
你说的是跳过的放到未执行进行统计吗？

**Comment by ChangqiaoWang** [comment]
不是放到未执行中统计，跳过的用例不参与统计，例如：总共100条用例，跳过20条用例，那么整体的用例只有80条；
原因是：
1. 用户在创建计划时候，都是批量选择模块所有的用例，可能存在部分用例不适合当前的产品，在执行时就会跳过这些用例；
2. 如果跳过的用例太多，通过率下降，导致不能过审；

**Comment by luty2018** [comment]
我们测试计划会增加质量阈值功能，通过率达到了设定的阈值就会标记测试计划通过，你看这样能满足你的需求吗？
<img width="751" alt="image" src="https://user-images.githubusercontent.com/36292514/217473184-7aee90b1-ea30-4b88-8cf9-4017971df0f8.png">
