### ISSUE TITLE
[BUG]接口保存提示框有文字错误

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#21367]
### MeterSphere 版本

2.6

### 使用外置数据库

否

### 问题描述

保存&同步设置框中的提示信息「不在弹出设置弹窗」，存在文字错误

### 重现步骤

1、在接口测试-接口定义编辑接口，并点击右上方的「保存」按钮
2、在弹出的保存&同步设置框中最下方的弹出提示信息「不在弹出设置弹窗」有文字错误，应该是「不再弹出设置弹窗」
3、提示信息对应的文字倒是正确的。

### 附加信息

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/46042812/212532979-fe7caee4-bfd2-4f36-8297-686c51e154ec.png">

**Comment by zrfit** [comment]
感谢您的反馈，后续版本修复。

**Comment by zrfit** [comment]
v2.6.1已修复，待发布后可升级验证。
