### ISSUE TITLE
[QUESTION] 使用单节点进行性能测试  结果TPS与原生jmeter差距太大 请问需要怎么优化下

### ISSUE THREAD

**Issue by mlq574** [metersphere/metersphere#21361]
### 请描述您的问题

使用单节点跑2000并发 单接口脚本 ms的结果：
![image](https://user-images.githubusercontent.com/42951437/212245847-93abf667-4d0b-41b3-a8b5-95ed8b92b7b6.png)
下图为在相同机器上运行相同脚本  jmeter得结果：
![image](https://user-images.githubusercontent.com/42951437/212254697-4da21d1a-8dcf-427e-a423-270373d25a92.png)
请问下需要怎么优化 能使tps差距缩小一点

**Comment by 35plus** [comment]
目前MeterSphere社区版用的kafka backendlistner插件 进行请求日志回传到kafka，然后datastreaming服务消费kafka里的数据，并入库，然后统计计算。

所以如果要支持1.5万tps的压测，建议采用外置kafka，把kafka和datastreaming服务单独部署，同时部署独立的nodecontroller压测节点。 

如果部署遇到问题，可以联系MeterSphere技术人员。

**Comment by mlq574** [comment]
你好  单独部署后 性能提高不明显  麻烦问下  瓶颈是在日志回传kafka还是datastreaming消费kafaka消息

**Comment by liuruibin** [comment]
在TPS高的情况下backendlistener的性能极速下降，导致发压端需要等待上传结果后才能开启下次请求，这个可以申请企业版试用，在资源池编辑的时候关闭后置监听器。效果会有明显提升
