### ISSUE TITLE
[FEATURE]用例调试时，执行按钮期望在顶部

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21371]
### MeterSphere 版本

v2.4.0-165ceb70

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

如果请求返回数据过长，执行按钮被覆盖，期望可以在顶部显示

1.请求数据过长，查看请求数据，需要滚动页面，导致 执行 按钮被覆盖
![image](https://user-images.githubusercontent.com/4860962/212588714-3f164728-bbbf-455c-a441-ad52b77dcdd9.png)

2.期望将 执行 按钮放在顶部，比如蓝框所在位置，不会收到滚动的影响
![image](https://user-images.githubusercontent.com/4860962/212588906-2ae6f8c9-671b-4dfb-b541-bf0d68f7faf6.png)

**Comment by luty2018** [comment]
这个页面在今年的UX交互升级规划中，届时会有调整。
