### ISSUE TITLE
[FEATURE][需求]测试计划中的测试报告，对于失败、跳过的用例，建议附带执行过程中的备注信息

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#21370]
### MeterSphere 版本

2.4.0

### 请描述您的需求或者改进建议

测试计划中的报告，对于失败、跳过的用例，建议附带执行过程中的备注信息，**方便导出报告后在评审时了解详细信息**，详细参加附加信息。

### 请描述你建议的实现方案

测试计划中的报告，对于失败、跳过的用例，建议在

### 附加信息

![企业微信截图_16738375066212](https://user-images.githubusercontent.com/6109912/212588473-40aaedf0-eb1a-4579-b0dd-c2cb0bff8162.png)

**Comment by luty2018** [comment]
感谢反馈，这里我们调研看看。
