### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by syang1997** [metersphere/metersphere#2138]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.2
**Bug 描述**
简要描述您碰到的问题
自动化测试中，使用谷歌插件录制操作后使用json导出脚本，将脚本导入到自动化测试场景中，生成的自定义请求无法生成参数提取断言等。
**Bug 重现步骤**
1.  使用谷歌插件录制操作后使用json导出脚本
2. 将脚本导入到自动化测试场景中
3. 点击自定义请求
4. 添加参数解析

**期待的正确结果**
正确情况下应该是什么样的？
子级操作添加成功
**截图**
如果有截图，请附上截图.
下面是页面中的报错，和对应的代码和数据。
![image](https://user-images.githubusercontent.com/48277927/115345112-e3b57b80-a1e0-11eb-984a-1b44459935a0.png)
![image](https://user-images.githubusercontent.com/48277927/115345145-edd77a00-a1e0-11eb-8c0a-267f8d9a8e69.png)

**Comment by zyyfit** [comment]
感谢反馈，这个问题会在后续版本修复

**Comment by zyyfit** [comment]
最新版已修复
