### ISSUE TITLE
[BUG]1.10.11升级1.20.18升级后，版本管理有两个1.0.0  且无法删除，期望只保留一个

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21399]
### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/43202800/212649031-1e928ed9-d40a-425a-93c2-be5f0ea23655.png)
1.10.11升级1.20.18升级后，版本管理有两个1.0.0  且无法删除，期望只保留一个

### 重现步骤

1.10.11升级1.20.18升级后，版本管理有两个1.0.0  且无法删除，期望只保留一个

**Comment by liuruibin** [comment]
我们执行升级没有复现这个问题，找到数据库中project_version表，找到该项目下的两条数据，选择保留其中一条
