### ISSUE TITLE
[BUG]1.10.11升级1.20.18  【老数据】场景a 引用场景b，场景b里面的值设置的部分值是空的，但是升级后会带上空格 （新数据不会报错）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21395]
### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

1.10.11升级1.20.18  【老数据】场景a 引用场景b，场景b里面的值设置的部分值是空的，但是升级后会带上空格 （新数据不会报错）

### 重现步骤

升级历史数据；1.10.11升级1.20.18   接口自动化

问题：场景a 引用场景b，场景b里面的值设置的部分值是空的，但是升级后会带上空格 ，如图
"officeNumber": "    "
历史数据场景变量多出来的空格，参数值空格请求执行会被非法校验
![image](https://user-images.githubusercontent.com/43202800/212647095-13236a00-a08e-4517-be77-a60dd81ab098.png)

### 期待的正确结果

期望：老数据是空的 ，升级上来应该也是空的 而不应该带上空格

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/212649793-73ccf2c1-5299-4066-8dbf-de2df6a3336b.png)
复现数据如图，如果需要复现可以联系我，找客户远程

**Comment by xhy12** [comment]
![image](https://user-images.githubusercontent.com/43202800/212649874-e633c322-8dd8-47ae-acb3-743b6ffe29fc.png)

**Comment by zyyfit** [comment]
已确认不是bug
