### ISSUE TITLE
[BUG]1.10.11升级1.20.18，接口自动化-  历史数据场景引用，场景开关默认勾选了优先使用当前场景 默认应该不勾选（新数据正常）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21396]
### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

接口自动化-  历史数据场景引用，场景开关默认勾选了优先使用当前场景 默认应该不勾选（新数据正常）

### 重现步骤

接口自动化-  历史数据场景引用，场景开关默认勾选了优先使用当前场景 默认应该不勾选（新数据正常）
![image](https://user-images.githubusercontent.com/43202800/212647532-b1d96d10-399a-470c-ac7e-cd81e65bc8f1.png)

### 期待的正确结果

历史数据默认不勾选开关

**Comment by zyyfit** [comment]
1.20.19 已修复，请等待版本发布后验证
