### ISSUE TITLE
[BUG]优化建议：目前版本管理新建了版本  切换版本会提示等待 但是马上切换页签修改会不生效 然后有个sql报错误以为是bug  此处建议如果没有修改成功 页面加个loading效果，避免误操作导致切换不成功

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21398]
### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

优化建议：目前版本管理新建了版本  切换版本会提示等待
但是马上切换页签修改会不生效 然后有个sql报错误以为是bug
 此处建议如果没有修改成功 页面加个loading效果，避免误操作导致切换不成功

### 重现步骤

优化建议：目前版本管理新建了版本  切换版本会提示等待
但是马上切换页签修改会不生效 然后有个sql报错误以为是bug
 此处建议如果没有修改成功 页面加个loading效果，避免误操作导致切换不成功
![image](https://user-images.githubusercontent.com/43202800/212648715-7562a9f2-ee3d-4708-a636-45056ce75b9f.png)
![image](https://user-images.githubusercontent.com/43202800/212648738-f6b5251e-1e63-4da6-9c57-f2dc1627605d.png)

### 期待的正确结果

建议如果切换版本成功 添加一个loading效果

**Comment by zyyfit** [comment]
这个报错看着是数据库表锁了，重启服务试试

**Comment by zyyfit** [comment]
![image](https://user-images.githubusercontent.com/73461316/216212914-4fb6a94f-876b-4efb-b21c-739609dbb40a.png)
