### ISSUE TITLE
[FEATURE]请愿！接口测试中能够支持附件上传的功能。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#214]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> **请描述你建议的实现方案**
安排

**Comment by seasoncool** [comment]
感谢您。

我们的测试场景是，有些接口需要上传（POST）一个视频或其它格式的文件，来测试上传接口是否正常。

目前在MS中没有发现该功能。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
