### ISSUE TITLE
[BUG]测试计划内的case，在脑图模式下更新用例执行结果，用例执行人没有更新。

### ISSUE THREAD

**Issue by testerfans** [metersphere/metersphere#21405]
### 联系方式

MeterSphere 交流群14  吴越

### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/105043452/212681121-8aa125e1-cfe8-435f-8f28-19234b030089.png)
测试计划-脑图模式-更新用例执行状态，用例执行人未更新成实际执行人

### 重现步骤

1、测试用例编写人为A；
2、新建测试计划，将A的用例关联到计划内；
3、用户B执行计划，切换到脑图模式；
4、用户B更新A的case；
5、切换到列表检查用例执行人是否更新。

### 期待的正确结果

用例执行人更新为实际执行人B

**Comment by zrfit** [comment]
v1.20.19-lts已修复，待发布后可升级验证。
