### ISSUE TITLE
[BUG]UI自动化测试，修改复制的场景步骤，会导致引用该步骤的场景数据出现错乱

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#21407]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v2.6

### 使用外置数据库

否

### 问题描述

A场景里面的步骤是复制出来的，B场景引用了A场景，修改A场景中复制的步骤后，进入B场景会看到B场景出现数据错乱

### 重现步骤

1、创建一个场景A
2、A场景添加步骤1，步骤2-4都是复制步骤1的
3、再创建一个场景B，引用场景A
4、修改场景A中的步骤
5、回去查看场景B，会发现场景B出现数据错乱

### 期待的正确结果

修改场景A步骤后，B场景数据正常

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/212802789-a89542b0-fd0b-4879-beae-a2158e7d1e03.png)
![image](https://user-images.githubusercontent.com/45786766/212803178-11c890c3-30e2-4a2c-970f-00e93768b84b.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。
