### ISSUE TITLE
[BUG]定时同步的cron表达式有问题，一直提示格式错误

### ISSUE THREAD

**Issue by zrf87** [metersphere/metersphere#21419]
### 联系方式

zhangrufeng_006@163.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

接口中定时同步配置，cron表达式有问题，提交时一直提示格式错误。 而且 自动生成 的功能也没有了。
接口自动化场景中的定时任务中cron表达式也有同样问题。

<img width="347" alt="8ce1b011134e2069002552716223dd0" src="https://user-images.githubusercontent.com/100331967/213053914-097d9207-f2a3-42f4-bcb8-f1a087fe9eea.png">

### 重现步骤

接口中定时同步配置，cron表达式有问题，提交时一直提示格式错误。 而且 自动生成 的功能也没有了。

**Comment by zyyfit** [comment]
您好，自动生成的按钮在请求参数设置的下面
![image](https://user-images.githubusercontent.com/73461316/213062867-3af8397a-b489-49e0-ab0e-607795cc1120.png)
