### ISSUE TITLE
[FEATURE]对绑定TAPD需求的用例提Bug时，增加Bug等级，可以直接在TAPD上关联到该需求

### ISSUE THREAD

**Issue by Hitoria** [metersphere/metersphere#2141]
**请描述您的需求或者改进建议.**
改进建议： 
        测试用例绑定TAPD上的需求后，在MeterSphere上提bug时，可以增加Bug等级字段，自动把Bug关联到TAPD上的该需求下。

**请描述你建议的实现方案**
        在提交Bug时，调用TAPD提交Bug的接口时，加入关联需求、Bug等级等的字段传入。

**Comment by xulinde** [comment]
目前已支持测试用例关联需求和缺陷

**Comment by Hitoria** [comment]
> 目前已支持测试用例关联需求和缺陷

但是在TAPD上需求的页面查看时，缺陷没和需求关联起来，在图示这个位置
![image](https://user-images.githubusercontent.com/39207507/115491188-1cf9f400-a292-11eb-91fc-153300790fe6.png)
TAPD上提缺陷的时候，有一个字段是关联到需求，也有Bug等级等字段，之后我们的MeterSphere上提缺陷的时候可否加上这些字段呢，方便提到TAPD直接关联和筛选。
![image](https://user-images.githubusercontent.com/39207507/115491314-4fa3ec80-a292-11eb-816a-8806887b9e9c.png)
