### ISSUE TITLE
[BUG]1.10.11 升级1.20.18 ，（老数据）接口自动化a场景引用b场景 修改b场景里面的场景变量保存后，a场景调试  刚刚修改的变量不生效（新数据验证了正常）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21416]
### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

1.10.11 升级1.20.18 ，（老数据）接口自动化a场景引用b场景 修改b场景里面的场景变量保存后，a场景调试  刚刚修改的变量不生效（新数据验证了正常）

### 重现步骤

1、背景，1.10.11 升级1.20.18   升级后拉去了最新镜像

问题：检查老数据《冒烟测试13》 a场景引用b场景 修改b场景里面的场景变量保存后，a场景调试  刚刚修改的变量不生效（新数据验证了正常）

如图：
![修改了原来场景 变量，新的场景里面引用 修改不生效](https://user-images.githubusercontent.com/43202800/212847930-807d3266-b87c-4605-8e25-666c45f85867.png)

### 期待的正确结果

原来场景修改后 新的场景参数修改应该生效

**Comment by zyyfit** [comment]
这个问题是因为场景 A 里复制了 2 个场景，里面都有场景变量 unitOfficeNumber，但是只改了第一
个场景变量的值，第二个场景里 unitOfficeNumber 的值还是空的，所以执行的时候，第二
个 unitOfficeNumber 覆盖了第一个 unitOfficeNumber 的值，所以是空值

1.20.19版本修改成了这样：
复制/引用的场景，场景设置选项都不勾选的时候，应该是就近原则，但是这个就近原则，是不包括场景变量的，举个例子：
场景 A 引用了场景 B，场景 B 中有场景变量 a；
如果在场景 B 步骤之前已经有过变量 a 了，则场景 B 中的变量 a 是不生效的；
如果在场景 B 步骤之前没有定义过变量 a，则场景 B 中的变量 a 生效；
然后如果场景A引用了场景B和场景C（步骤顺序为 场景B-场景C），场景B和场景C中都有变量a，则使用场景B中的变量a的值。
简单的理解就是重名场景变量取第一个的值，脚本中可覆盖变量值。

请等待版本发布后验证
