### ISSUE TITLE
[BUG]用例层级和数量多时，脑图模式复制模块和用例，用例内容展示错乱，并且保存时用例数据不对，只能正确保存复制的模块

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#21418]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

用例层级和数量多时，脑图模式复制模块和用例，用例内容展示错乱，并且保存时用例数据为空，只能保存复制的模块

### 重现步骤

1.可以看到该模块下用例数量有13条，接下来将在脑图模式下复制该模块用例到另一个模块
![image](https://user-images.githubusercontent.com/88763608/212873055-18af15f5-a19a-4e8c-beec-3608262d30a6.png)
2.在脑图模式下复制“PMS前台”模块和用例，并粘贴到“复现问题模块”模块下
![image](https://user-images.githubusercontent.com/88763608/212874030-a1d5b131-a51c-446f-883b-6f8dfb8556e0.png)
![image](https://user-images.githubusercontent.com/88763608/212874373-6ff085fd-538d-4426-a2b4-64d06ee68ae5.png)
3.可以看到粘贴后用例展示不对，数量明显多了很多，展示了非当前模块下的用例
![image](https://user-images.githubusercontent.com/88763608/212874883-b953b57e-ec18-4c2e-965c-9f3aeab6eb4e.png)
4.点击保存按钮，发现脑图和列表只保存了粘贴的模块，只保存了一条用例信息
![image](https://user-images.githubusercontent.com/88763608/212876136-4a02cf6c-566b-457b-b8f0-1eb0b5a31c04.png)

### 期待的正确结果

正确保存。
ps：在用例层级和数量少的情况下，上述操作是符合预期的

**Comment by linfengjjj** [comment]
我这边有可以稳定复现的环境

**Comment by zrfit** [comment]
v1.20.19-lts已修复，待发布后可升级验证。

**Comment by linfengjjj** [comment]
已验证，已解决
