### ISSUE TITLE
[BUG]v2.6, MeterSphere和jira对接，使用jira缺陷模板 选项勾选后，访问 测试跟踪 缺陷页面 会出现错误提示信息

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21411]
### 联系方式

王进

### MeterSphere 版本

v.2.6

### 使用外置数据库

否

### 问题描述

v2.6, MeterSphere和jira对接，使用jira缺陷模板 选项勾选后，访问 测试跟踪 缺陷页面 会出现错误提示信息

### 重现步骤

1. 升级到v2.6
2. 加载jira 2.5版本的插件（备注：目前jira最新插件是2.5）
3. 配置jira连接信息--测试成功
4. 配置工作空间下面的  项目信息，配置如下，勾选“使用jira缺陷模板”
![955320102472019706e0396537c89fa](https://user-images.githubusercontent.com/76033005/212815043-6a6ff769-fa37-483c-9834-5429cbcf6470.png)
5. 导航到测试跟踪 缺陷 页面，页面弹出如下错误。
![1673932553699](https://user-images.githubusercontent.com/76033005/212815718-8517dc43-696a-4bb2-b487-528d766707f0.png)

### 相关日志输出

```shell
见附加信息。
目前指导客户用的是 不勾选“使用jira缺陷模板”
```

### 附加信息

[metersphere jira日志.log](https://github.com/metersphere/metersphere/files/10431626/metersphere.jira.log)

日志文件

**Comment by xulinde** [comment]
未复现该问题，请确认下：
1.jira插件是不是最新版本；
2.服务集成，jira是否链接通过；
3.jira的key是否填写正确；
