### ISSUE TITLE
[BUG]前置脚本 python 打开一段时间后无法保存

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21417]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

用例前置添加 python 脚本，用例打开一段时间后，编辑的内容无法保存

### 重现步骤

1. 创建用例，前置操作添加 python 脚本
2. 关闭用例编辑界面
3. 再次打开用例编辑界面
4. ***等待 2 分钟***
5. 修改 python 脚本，后点击保存按钮【提示保存成功】
6. 关闭用例编辑界面
7. 再次打开用例编辑界面，发现刚修改的内容没有保存

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问是必现的吗？

**Comment by hao1032** [comment]
我尝试去复现也没有复现这个点，但是在实际编写中遇到了。可能我的步骤不对，bug 先不要关，我后面再找找规律。

**Comment by hao1032** [comment]
我实际使用中用 groovy 脚本又遇到了，可以看下附件视频

https://user-images.githubusercontent.com/4860962/215735449-ad64ec03-4564-470b-a734-19d1cdd79ba1.mp4

**Comment by zyyfit** [comment]
已在 https://github.com/metersphere/metersphere/issues/21425 这个issue里修复，请等待 2.7.0 版本发布后验证
