### ISSUE TITLE
[BUG]优化建议：ui测试设置了环境url,不选择环境直接点击调试，还是可以直接运行然后运行报错，如果没选择应该给出提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21421]
### MeterSphere 版本

v.2.6

### 使用外置数据库

否

### 问题描述

ui测试设置了环境url,不选择环境直接点击调试，还是可以直接运行然后运行报错，建议如果没选择环境应该给出提示

### 重现步骤

1、ui测试脚本，设置了环境url为变量使用，调试的时候不选择环境直接点击调试，还是可以直接运行然后运行报错
![image](https://user-images.githubusercontent.com/43202800/213072041-7d565e27-c798-427c-9bf6-67757ccbf2d9.png)

### 期待的正确结果

2、建议如果没选择环境应该给出提示

**Comment by zrfit** [comment]
您好，感谢您的反馈，目前的逻辑是UI场景不选择环境也是可以调试的，如果强校验，历史数据就无法执行了，所以场景详情的调试和场景列表的执行都不做运行环境的强校验，方便用户自行选择，选择运行环境-调试则可以引用环境变量；不选择运行环境，则默认用步骤的URL，场景也可以执行正常。

**Comment by xhy12** [comment]
收到 感谢
