### ISSUE TITLE
[BUG] 接口定时同步 ： Cron表达式-自动生成-设置了年， 保存的时候提示错误，不设置年就正常

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21420]
### 联系方式

v1.20.18

### MeterSphere 版本

v1.20.18

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/43202800/213065025-69973234-8212-40f0-8dc2-a99a95ee4e9c.png)
接口定时同步  corn表达式 自动生成设置了年 不能保存提示错误，不设置就正常

### 重现步骤

接口定时同步  corn表达式 自动生成设置了年 不能保存提示错误，不设置就正常

![Uploading 企业微信截图_16740079304376.png…]()

### 期待的正确结果

应该可以保存

**Comment by zrfit** [comment]
v1.20.19-tls已修复，待发布后可升级验证。
