### ISSUE TITLE
[BUG]接口定义case,后置操作添加脚本，修改信息后仍是以前的结果

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21425]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

接口定义case,后置操作添加脚本，修改信息后仍是以前的结果

### 重现步骤

1.case添加后置操作，打印响应信息，点击保存执行
![1](https://user-images.githubusercontent.com/103627487/213109199-1524d279-dc7d-45a7-a151-53cac1bd93bf.png)
![2](https://user-images.githubusercontent.com/103627487/213109223-4f7573f5-3e4c-4642-8169-b8ba2dd38e42.png)
2.修改打印信息，保存执行，控制台打印信息仍是之前的信息
![3](https://user-images.githubusercontent.com/103627487/213109532-5b32074b-8dfc-4feb-a498-d9f34fff52e9.png)
![4](https://user-images.githubusercontent.com/103627487/213109556-8763809f-1830-41c8-9f89-c22aaaf0bdb3.png)
3.退出重新编辑case,还是第一次编辑的后置脚本，像是提示保存成功，未保存成功
![5](https://user-images.githubusercontent.com/103627487/213109641-9ac503e4-add4-4ba7-b048-61b08a65c9e9.png)

**Comment by zrfit** [comment]
v2.6.1已修复，待发布后可升级验证。
