### ISSUE TITLE
[BUG] 集成 jira，创建缺陷后，删除缺陷提示 403 权限不足

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#21437]
### 联系方式

18159668371

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

客户使用 Ldap 账号登录 MS，集成 jira 8.17，并可以进行缺陷创建。但是创建缺陷后，使用同样的账号删除缺陷，提示 403 权限不足：you do not have permission to delete issues in this project；

使用通用的 LDAP 账号登录 jira，可以正常该条同步到 jira 的缺陷

![image](https://user-images.githubusercontent.com/92966838/215323697-83ef84d0-1e3e-4414-9e1e-02f5aafa7ff5.png)

### 重现步骤

1、集成禅道 8.17；
2、MS 新建缺陷；
3、删除缺陷。

### 期待的正确结果

能够正常删除

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。
之前有用户遇到该问题，ms重启一下就好了。

**Comment by gaohonghai** [comment]
咱们验证 Jira 的版本也是 8.x 吗

**Comment by youliyuan-fit2cloud** [comment]
> 

是的啊，v8.20
