### ISSUE TITLE
[FEATURE]用例列表在使用ID排序后，是否可以新增手动排序。

### ISSUE THREAD

**Issue by testerfans** [metersphere/metersphere#21439]
### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 联系方式

MeterSphere交流群14  吴越

### 请描述您的需求或者改进建议

测试用例编写过程中，经常会有查漏补缺的过程。在后期维护用例生成的ID会大，如：100040，但实际这条用例我想排序100010下面，并且不想打乱其他用例的顺序。核心目的还是为了保持用例执行思路上的连贯性。

### 请描述你建议的实现方案

完全按照脑图顺序进行排序，取消列表的ID、名称等排序功能。

列表的ID排序等对于用例执行和维护来说，使用上没有提供实际帮助。因为ID和名称等不代表用例执行逻辑。

**Comment by luty2018** [comment]
目前如果在脑图排序好以后， 切换到列表会以脑图的顺序来展示哦， 请问实际使用过程当中是遇到什么问题了吗？
