### ISSUE TITLE
[BUG]启动api-test服务报错说表不存在

### ISSUE THREAD

**Issue by wen-xue-bee** [metersphere/metersphere#21432]
### MeterSphere 版本

V2.6

### 使用外置数据库

是

### 问题描述

启动服务报错说表不存在，不会自动生成表结构吗
![image](https://user-images.githubusercontent.com/68628203/215270145-5063e41f-8dfa-4361-a6b2-4c5ecd275e69.png)

### 重现步骤

重启api-test 服务时

### 期待的正确结果

希望启动服务的时候，能自动生成表结构

**Comment by liuruibin** [comment]
这个表的初始化在system-setting模块中，初次使用请按照安装指引进行操作，避免数据库初始化不完整
