### ISSUE TITLE
[BUG]文档中创建数据库SQL错误

### ISSUE THREAD

**Issue by lohaaa** [metersphere/metersphere#21434]
### MeterSphere 版本

v2.x

### 使用外置数据库

是

### 问题描述

此链接下的创建数据库语句错误：[https://metersphere.io/docs/v2.x/dev_manual/#_6](url)

CREATE DATABASE `metersphere_dev` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci *//*!80016 DEFAULI ENCRYPTION='N'*/;

### 重现步骤

执行SQL

### 期待的正确结果

CREATE DATABASE `metersphere_dev` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci *//*!80016 DEFAULT ENCRYPTION='N'*/;

**Comment by youliyuan-fit2cloud** [comment]
@shenkaibo 辛苦帮忙看下这个文档问题，谢谢～

**Comment by shenkaibo** [comment]
已修改 https://metersphere.io/docs/v2.x/dev_manual/#_6
