### ISSUE TITLE
[BUG]v2.6, 【测试跟踪】【更多操作】【新建用例】，输入用例名称然后点【确定】，用例没有被保存。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21438]
### 联系方式

王进

### MeterSphere 版本

v.2.6 

### 使用外置数据库

否

### 问题描述

v2.6, 【测试跟踪】【更多操作】【新建用例】，输入用例名称然后点【确定】，用例没有被保存。

### 重现步骤

1. 登录MeterSphere Cloud
2. 通过【体验新版本】进入到MS Cloud v2.6
3. 连续点击【测试跟踪】【更多操作】【新建用例】，输入用例名称然后点【确定】，用例没有被保存。

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
经和产品沟通，v2.7测试跟踪页面重构，无该功能，所以不存在此问题了。
