### ISSUE TITLE
本地运行metersphere-platform-plugin-sdk这个依赖一直下载不下来怎么处理呢？

### ISSUE THREAD

**Issue by MyKays** [metersphere/metersphere#21433]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/49096399/215308293-a165e170-18f9-41af-b6e5-3b2bc934f16f.png)

**Comment by liuruibin** [comment]
本地编译需要自行下载相关的仓库一并编译，https://github.com/metersphere/metersphere-platform-plugin

**Comment by Get-lzh** [comment]
请问  自行下载的metersphere-platform-plugin版本要和metersphere版本一致吗？
