### ISSUE TITLE
[BUG]单接口用例转性能用例内容缺失无法执行

### ISSUE THREAD

**Issue by littlemouse12** [metersphere/metersphere#2144]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8.2

**Bug 描述**
在接口管理-case页面，点击创建性能用例，转换出的性能用例点击执行后，任务始终处于started状态，且无法结束。
将生成的jmx脚本下载后导入jmeter中发现，缺少了接口url等多个关键信息，脚本内容不完整。
同样的用例，在接口自动化页面通过场景用例转换生成的性能用例无此问题。

**Bug 重现步骤**
1.  创建单接口测试用例
2.  基于单接口用例，创建性能用例，并点保存并执行
3.  性能测试任务发起，但一直无结果返回。

**期待的正确结果**
单接口用例转换出的性能测试脚本应可正常在平台执行，保存并执行任务后，性能测试任务状态应能够自动改为running，并于较短时间内返回测试结果，可在页面查看性能测试报告。

**截图**
无

**Comment by zyyfit** [comment]
您好，这个问题将会在1.9版本解决，您可以等1.9发布后再试一下

**Comment by xulinde** [comment]
1.9.0已修复
