### ISSUE TITLE
[BUG] 【接口测试】脚本错误使用函数，导致接口不执行

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21447]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts/v2.6.0

### 使用外置数据库

否

### 问题描述

【接口测试】脚本错误使用函数，导致接口不执行

### 重现步骤

接口脚本中使用下面代码：
![image](https://user-images.githubusercontent.com/103925124/215405334-e43194c9-8767-4a47-b70b-3519c7f735f3.png)
ph=${__Random(111111111,999999999,)};
String a =String.valueOf(ph);
//以上两行代码实现了手机号后9位在1-9之间随机分配
phone=${__Random(3,9,)};
String b =String.valueOf(phone);
//以上两行代码实现了手机号第二位在3-9之间随机分配
//以上四行代码实现了手机号的足够随机
mobile=1+b+a;
//以上一行代码实现了将手机号的位数拼接起来
String email=a+"@123.com";
//以上一行代码将手机号联系起来，实现了邮箱随机

vars.put(${__metersphere_env_id}+"phone",mobile);
vars.put("phone",mobile);
log.info("手机号="+mobile);
//随机生成手机号
vars.put(${__metersphere_env_id}+"email",email);
//vars.put("邮箱",email);
//随机生成邮箱

tell="0755-"+${__RandomString(8,0123456789,)};
vars.put(${__metersphere_env_id}+"tell",tell);
//vars.put("tell",tell);
log.info("电话="+tell);
//生成注册电话

bank=${__RandomString(18,123456789,)};
String a =String.valueOf(bank);
vars.put(${__metersphere_env_id}+"bank",a);
vars.put("bank", a);
//vars.put("bank",a);
log.info("bank="+a);
//生成银行卡号

corporate_name="深圳"${__RandomString(3,孟晓苏称他从来不认为逼低收入家庭去购买商品房是正确的多年来他反复强调要给低收入家庭新市民与青年人家庭提供保障房包括产权型保障房与租赁型保障房而不是只能去买商品房为此必须加快完善住房双轨制政府要履行提供保障房责任央企国企要尽快回
归保障轨,)}"有限责任公司"
vars.put(${__metersphere_env_id}+"corporate_name",corporate_name);
//vars.put("corporate_name",corporate_name);
log.info("corporate_name="+corporate_name);
//随机生成公司名称
taxesNumber =9144${__RandomString(14,ASDFGHJKLZXCVBNM0123456789)}
vars.put(${__metersphere_env_id}+"taxesNumber",taxesNumber);
//vars.put("taxesNumber",taxesNumber);
log.info("taxesNumber="+taxesNumber);
//随机生成机构号

导致不执行
![image](https://user-images.githubusercontent.com/103925124/215405778-31ec5b9c-402f-4c44-84db-7ee21dae7d3a.png)
将代码中第一行 ph=${__Random(111111111,999999999,)}; 换成 ph=${__Random(1111,999,)};  可执行

### 期待的正确结果

函数异常时，接口仍可执行

**Comment by zrfit** [comment]
经验证，导入到jmeter执行，脚本错误接口也未执行，jmeter机制如此，暂时保持一致。
