### ISSUE TITLE
[BUG]触发方式为“API调用”的不下发企业微信通知

### ISSUE THREAD

**Issue by junwei-liu** [metersphere/metersphere#21457]
### 联系方式

1121213408@qq.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

项目设置--消息设置，设置测试跟踪的测试计划在执行成功后发送企业微信通知，但是触发方式为“API调用”的不下发企业微信通知

### 重现步骤

项目设置--消息设置，设置测试跟踪的测试计划在执行成功后发送企业微信通知，但是触发方式为“API调用”的不下发企业微信通知

### 期待的正确结果

无论何种调用方式，都下发通知

### 附加信息

![image](https://user-images.githubusercontent.com/78710778/215437999-b46a8e1e-7cb2-4d84-910a-0d535c3fc09b.png)

**Comment by zrfit** [comment]
您好，触发方式为API调用方式是jenkins触发执行的，需要设置jenkins任务通知。
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/99731894/215690552-a2f2dab8-d807-4b87-b1f7-58746447daf6.png">
