### ISSUE TITLE
[BUG] jira 8.17 同步缺陷，前端无响应

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#21456]
### 联系方式

18159668371

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

问题一：集成 jira 之后，点击同步缺陷（筛选近十天，不到 100 条缺陷），前端页面不断在转圈，没有响应；
问题二：刷新页面之后，才可以看到数据，但是也不确定是否都拉取成功。

页面一直转圈，接口无响应
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/92966838/215429291-c4ef1926-29a3-4f9d-89a3-76d33306e37c.png">

直到 gateway 超时提示
<img width="746" alt="image" src="https://user-images.githubusercontent.com/92966838/215429397-0ae6ccd5-a49c-419c-900e-4b5c16434785.png">

实际上后端info日志，数据拉取已经停止。后端日志停止输出是否算拉取成功了？如果是拉取成功，前端为什么没有响应？
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/92966838/215429731-bee66056-6250-449b-933d-1984c883db18.png">

### 重现步骤

1、集成 Jira 8.17；
2、点击同步缺陷，同时 tail -f info.log

### 期待的正确结果

1、能够正常同步缺陷；
2、即使拉取异常至少能够人性化通知，而不是直接将后端的返回丢给用户，用户体验差。

**Comment by gaohonghai** [comment]
![image](https://user-images.githubusercontent.com/92966838/215514384-4d9521f0-dddf-4d56-a95b-5db1ed3677ca.png)
这个是一直转圈无果，刷新页面之后同步部分缺陷的数量

**Comment by zrfit** [comment]
已远程和用户沟通，同步缺陷较多（字段较多），内存不够，调整内存后同步成功了。
