### ISSUE TITLE
[BUG]UI测试后端浏览器语言不能设置为中文，只能是英文

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#21458]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.18-lts

### 使用外置数据库

否

### 问题描述

UI测试后端浏览器不能设置为中文，通过vnc到后端浏览器手动设置也不行。
后端浏览器默认英文会导致部分客户被测系统的国际化切换有问题，需要我们的后端浏览器每次调用时保持中文语言。

### 重现步骤

1.本地windows测试，使用该命令行启动本地chrome浏览器可以正常切换语言。
chrome --lang=zh-cn --user-data-dir=F:\Locales（Locales目录路径）
<img width="686" alt="命令" src="https://user-images.githubusercontent.com/88763608/215640967-5d52e7c8-b2ba-4dc6-bdfa-64e7a1674021.png">
<img width="771" alt="中文" src="https://user-images.githubusercontent.com/88763608/215640987-0d16d975-5c86-415e-9ed4-aeb260d2459d.png">

2.跟研发确认了，我们后端浏览器有bug，切换不了中文，需要修复。

### 期待的正确结果

后端浏览器每次打开时语言设置为中文

**Comment by zrfit** [comment]
您好，该问题经沟通计划在v2.8修复，v1.20不进行修改。

**Comment by liuruibin** [comment]
本地调试需要您自行启动浏览器，容器支持中文的修改方式为
1. 改 `/opt/metersphere/docker-compose-seleniarm.yml` 增加一个环境变量 `LANG=zh_CN.UTF-8`，然后执行 `msctl reload`

2. 进grid容器
```
docker exec -it local-selenium-grid bash
```
3. 重新配置语言
```
sudo sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen && \
sudo dpkg-reconfigure --frontend=noninteractive locales && \
sudo update-locale LANG=$LANG
```
5.重启容器
```
docker restart local-selenium-grid
```
