### ISSUE TITLE
[BUG]测试计划-自动更新状态，功能用例关联了接口测试，执行测试计划功能用例状态没有标记上

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#21460]
### MeterSphere 版本

v2.6

### 使用外置数据库

否

### 问题描述

测试计划-自动更新状态，功能用例关联了接口测试，执行测试计划接口通过功能用例状态没有标记上
![image](https://user-images.githubusercontent.com/43202800/215644516-39543ed6-08fb-41cc-98af-1f000801f5af.png)
![2f3fc9f3e128004663b8a2aeee37dd0](https://user-images.githubusercontent.com/43202800/215644990-6fac59ea-d618-448a-9568-8455fee4718d.png)
![image](https://user-images.githubusercontent.com/43202800/215645131-ef271a7c-995f-4131-b971-365e4ef869b8.png)

### 重现步骤

1、功能用例-关联接口测试用例
2、测试计划关联这个用例，并执行
问题：接口通过功能用例状态没有标记上

### 期待的正确结果

功能用例标记通过

**Comment by zrfit** [comment]
您好，感谢您的反馈，已复现该问题，后续版本修复。
