### ISSUE TITLE
新建测试计划点击操作栏的运行按钮，运行成功后，接口用例的状态更新了，功能测试用例的状态未更新

### ISSUE THREAD

**Issue by hulinbig** [metersphere/metersphere#21464]
### 联系方式

191707485@qq.com

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

功能测试用例关联接口测试用例，新建测试计划引用该条功能用例后，点击测试计划列表的执行按钮，执行成功后，功能测试用例状态还是未开始，接口用例状态是已完成

### 重现步骤

第一步：功能测试用例关联接口测试用例  
第二步：新建测试计划将自动更新状态打开
第三步：测试计划内关联测试用例，勾选同步添加关联测试的用例   

### 期待的正确结果

期望：功能测试用例状态也要更新为已完成

**Comment by hulinbig** [comment]
![b1a68e122707e245287f07c37051ae6](https://user-images.githubusercontent.com/35224770/215654904-306b26bd-ee5e-4f5e-b372-b9c58d181d6a.png)

**Comment by zrfit** [comment]
该问题重复，同https://github.com/metersphere/metersphere/issues/21460
