### ISSUE TITLE
[BUG]在一个场景里面进行复制多个接口请求，多次进行修改变量点击调试和保存的时候，无法生效

### ISSUE THREAD

**Issue by sunyuanyuan666** [metersphere/metersphere#21461]
### 联系方式

1342695304@qq.com

### MeterSphere 版本

1.20.18

### 使用外置数据库

否

### 问题描述

在一个场景里面进行复制多个接口请求，多次进行修改变量点击调试和保存的时候，无法生效

### 重现步骤

在一个场景里面进行复制多个接口请求，多次进行修改变量点击调试和保存的时候，无法生效

### 期待的正确结果

在一个场景里面进行复制多个接口请求，多次进行修改变量点击保存的时候，可以正常保存，正常调试

### 附加信息

https://user-images.githubusercontent.com/124016102/215653444-0ae11fc4-80ee-4d5a-a3cd-b0442461977b.mp4

**Comment by zrfit** [comment]
您好，未能复现该问题。
1、复制的接口是都引用了变量吗？
2、多次修改的变量是场景变量吗？
3、是否有特使的操作顺序？尽量把操作步骤描述详细些，便于复现问题，多谢！

**Comment by sunyuanyuan666** [comment]
1.引用了场景变量
2.修改的内容是入参和断言
3.每一次点击或者修改操作之后，都会跟着操作一次保存

**Comment by zrfit** [comment]
您好，尝试多次仍未复现，已经发您邮件，我们私下远程沟通下具体场景。

**Comment by zrfit** [comment]
您好，未收到您的邮件回复，最新版本v1.20.20也未复现该问题。后续最新版本如您再遇到该问题可打开，多谢。
