### ISSUE TITLE
[BUG] 从测试报告点击用例名进入用例编辑页，module会丢失

### ISSUE THREAD

**Issue by sac911** [metersphere/metersphere#21463]
### MeterSphere 版本

1.20.18

### 使用外置数据库

是

### 问题描述

从report页面点击用例名link，
![image](https://user-images.githubusercontent.com/103017812/215653454-c580ec70-e52d-4fee-a5d2-2b121e6505cb.png)

打开新页面，用例编辑页模块丢失
![image](https://user-images.githubusercontent.com/103017812/215653538-d42a375c-d4cf-4eeb-b7ba-24edcc786b06.png)

18版本之前没有发现此问题，18版本之前只有在另外一个项目的plan中引用了这个项目的用例，执行后报告中点击会有此问题，但是在本项目的用例执行后不会有此问题。现在两种问题都存在！

### 重现步骤

见描述

**Comment by zrfit** [comment]
您好，感谢您的反馈！
测试计划中引用其它项目的用例-执行后查看报告-点击用例名称-模块名称未显示已复现，后续版本修复；
测试计划中引用当前项目的用例-执行后查看报告-点击用例名称-模块名称未显示未复现。
