### ISSUE TITLE
[FEATURE]接口调试时，某些页签显示不明显

### ISSUE THREAD

**Issue by TSleon** [metersphere/metersphere#21462]
### MeterSphere 版本

V2.4

### 请描述您的需求或者改进建议

api接口调试时，请求体，认证配置，其他设置这些页签下如果配置了内容，在页签上没有显示（1）或者已配置的标记，导致在调试时，忽略了此处的配置项。

**Comment by luty2018** [comment]
这个我们会在后期交互升级进行改善
