### ISSUE TITLE
[BUG]  UI 测试场景，使用场景变量配置mock参数，引用变量失败。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21465]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.6

### 使用外置数据库

否

### 问题描述

#  问题一
UI场景自动化，使用场景变量，在UI自动化里面执行没有问题，但是在UI 自动化列表中和测试计划中执行有问题。
![image](https://user-images.githubusercontent.com/33945037/215655194-9ee0ac16-219a-49c9-a056-cef19760d1c1.png)
![image](https://user-images.githubusercontent.com/33945037/215655275-ca49a134-95d4-4960-8b50-164c871a62fc.png)

* 点击生成报告结果如下：
![image](https://user-images.githubusercontent.com/33945037/215655413-5678f451-df46-463e-a1e7-6b06c9f3f25c.png)

![image](https://user-images.githubusercontent.com/33945037/215655395-111e3304-b413-42a5-a772-f92a85e17b96.png)

* 在UI列表中执行和加入到测试计划中执行都是以下效果
![image](https://user-images.githubusercontent.com/33945037/215655529-2f0e4ef9-6167-49ac-957e-89a490aeb799.png)

![image](https://user-images.githubusercontent.com/33945037/215655750-f6aadb58-7553-4754-b091-c41ea3bee8cf.png)

# 问题二
当在UI场景里面不选择环境的时候，没办法加入到测试计划中
![image](https://user-images.githubusercontent.com/33945037/215656076-09fd7547-097b-437c-81be-2c884d63ba34.png)
![image](https://user-images.githubusercontent.com/33945037/215656120-0ee899b8-149e-42c5-a53a-3eab2a1b61c6.png)

### 重现步骤

同上

**Comment by zrfit** [comment]
您好，感谢您的反馈！
问题一已复现，后续版本修复；
问题二目前产品功能逻辑就是这样的，测试计划中关联UI用例，是必须要选择环境才能关联的，与接口场景关联逻辑一致。

**Comment by zrfit** [comment]
v2.7已修复该问题。
