### ISSUE TITLE
[BUG]次数循环控制器，python脚本不生效

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#21478]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

次数循环控制器在python脚本中没有进行遍历，在beanshell中是正常的

### 重现步骤

1、在场景变量中添加 计数器 num
![image](https://user-images.githubusercontent.com/89765365/215723118-1d7ab81d-36b2-428a-9d33-4202de2c2ac4.png)

2、在次数循环控制器下添加自定义脚本，选择 python 脚本
![image](https://user-images.githubusercontent.com/89765365/215723557-cd182231-9555-49cc-80c9-45284dbeb2f1.png)

3、用 beanshell 脚本是正常的
![image](https://user-images.githubusercontent.com/89765365/215723742-5ac5e854-62c1-4d34-8549-6e5fd8b9e84b.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现，后续版本修复。

**Comment by zyyfit** [comment]
1.20.20 和 2.7.0 版本已修复，请等待版本发布后验证

**Comment by xiaoliu0528** [comment]
为啥现在还有这个问题，怎么循环都是只读取第一行 都3.6几的版本了
