### ISSUE TITLE
[BUG] 功能用例模板上传（只有一个步骤），导入之后列表形式会进行拆分展示，多个步骤就不会

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#21474]
### 联系方式

18159668371

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

1、用例只有一个步骤时，上传之后，步骤会被拆分展示
![image](https://user-images.githubusercontent.com/92966838/215695514-bbcc81df-9bfb-4d46-8bdf-43038e0b08ae.png)
![image](https://user-images.githubusercontent.com/92966838/215695663-6009be5e-3a3e-48e5-bb0f-4da6b78ccba0.png)

2、用例有多个步骤时，上传之后，步骤可以正常展示
![image](https://user-images.githubusercontent.com/92966838/215697941-960ba900-05b7-4959-8a01-bfc2fe7d6e31.png)

### 重现步骤

参考问题描述截图

### 期待的正确结果

问题描述中，第一点能够正常展示

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、新模版-只有一个步骤-换行输入步骤输入-如果把空步骤行删除-导入会拆分步骤显示，兼容旧模版原逻辑。
2、用新模版实现一个步骤的导入换行显示-不删除空步骤的行-只清空步骤数据后导入-暂时可解决该问题。
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/99731894/216284503-ff853607-6a3e-431d-9262-3c686ef69ad5.png">
注意：不要将只有一个步骤的用例放到最后一个，这里有已知bug，后续版本会优化。
3、从用户使用角度出发，作为一个非历史版本用户，导入模版步骤进行了拆分，但是用户操作一般只有一个步骤的话，一部分用户会删除没用步骤的行，则变成了老模版的导入情况，导致只有一个步骤的数据换行导入后没有在一个步骤内换行显示，而是拆分步骤显示换行数据，这个后续跟产品沟通确认是否做一些导入引导用户的友好提示的优化。
