### ISSUE TITLE
[BUG]接口定义导入postman文件时，某些GET请求导入失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#21484]
### 联系方式

张树彬

### MeterSphere 版本

2.6

### 使用外置数据库

否

### 问题描述

接口定义导入postman文件时，2.6版本某些GET请求导入失败，同样的接口导入LTS版本是成功的。（找我要脚本）

### 重现步骤

1. postman导出collection，包含GET请求
2. 导入2.6版本接口定义，提示解析数据出错
3. 导入LTS版本接口定义，导入成功

### 期待的正确结果

可以正确导入2.6版本接口定义中

### 附加信息

![ea88dfe5ed8dfab4bcdd62219feb2c0](https://user-images.githubusercontent.com/77324661/215790548-4f96e8ef-7457-4426-9848-c22d6634bbf0.png)

**Comment by zrfit** [comment]
v2.6.1已修复该问题，待发布后可升级验证。
