### ISSUE TITLE
[BUG]通过定时任务执行接口自动化场景，测试报告中前面的步骤执行状态都是pending未执行，但实际上已经被执行了，脚本后面的步骤也可以正常执行。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21483]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

通过定时任务执行接口自动化场景，测试报告中前面的步骤执行状态都是pending未执行
![4a1f0f1bf0620bd8be2797c3bdca568](https://user-images.githubusercontent.com/83771182/215767113-454b18a6-0f6d-4581-b39d-32c2eef29724.jpg)
![3c5d4d59c90f6ff3b76b5cee885b1bb](https://user-images.githubusercontent.com/83771182/215767513-62f86bb7-9043-499c-ba85-46eb99523ca7.png)

但实际上已经被执行了，脚本后面的步骤也可以正常执行。
![f906b5e1119a13cfeb9a3aa6037bfa2](https://user-images.githubusercontent.com/83771182/215767540-a353842d-22c3-4d8e-bdec-3728f54b8549.png)
![ed1008732995a501f5dc045e15c0e9e](https://user-images.githubusercontent.com/83771182/215767580-35765290-7191-4844-9e4e-f98ff99649af.png)

### 重现步骤

通过定时任务执行接口自动化场景，测试报告中前面的步骤执行状态都是pending未执行

### 期待的正确结果

通过定时任务执行接口自动化场景，测试报告中前面的步骤执行状态正常

### 相关日志输出

```shell
无
```

### 附加信息

脚本文件
[Metersphere_Scenario_【在用】数科.zip](https://github.com/metersphere/metersphere/files/10546600/Metersphere_Scenario_.zip)

**Comment by zrfit** [comment]
未复现该问题，执行时后端日志是否有异常，日志保存提供下，便于研发定位。

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
