### ISSUE TITLE
[BUG]接口自动化里增加foreach循环控制器，不放到第一步无法执行

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21492]
### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

1.使用接口自动化，增加了多个循环控制器和场景，发现增加的foreach循环控制器没有执行。
![image](https://user-images.githubusercontent.com/55130444/215936185-9a60fcd6-7a0c-4428-8656-c16b719788d5.png)

### 重现步骤

1.使用接口自动化，增加了foreach循环控制器，将foreach循环控制器放到场景步骤中间，或者最后都不会执行。
foreach循环控制器放到最后：
![image](https://user-images.githubusercontent.com/55130444/215936383-9872e290-a754-49c8-9e8a-5e3a3b9f84e2.png)
foreach循环控制器放到步骤中：
![image](https://user-images.githubusercontent.com/55130444/215936488-9d9c215e-3088-4751-8c17-16acb84ac05d.png)
foreach循环控制器放到第一步可以执行：
![image](https://user-images.githubusercontent.com/55130444/215936579-9684f6f7-9da2-490c-b99c-ab1ab674a856.png)

### 期待的正确结果

foreach循环控制器可以在场景中任何一步都能执行。

**Comment by zyyfit** [comment]
经排查，场景变量里也设置了一个list变量：id，第一个步骤里也有一个提取的变量：id，提取的这个id把场景变量里的id覆盖了，所以id的值是空的，然后 foreach里有用到id这个list，但是前面的提取里没有提取到，所以不执行是正常的
