### ISSUE TITLE
[BUG] 测试跟踪--测试报告中的分享链接无法访问

### ISSUE THREAD

**Issue by wpiami** [metersphere/metersphere#21493]
### MeterSphere 版本

V2.3

### 使用外置数据库

否

### 问题描述

测试跟踪模块下，测试报告的分享链接，访问打不开测试报告，提示如下图错误：
是否是因为微服务部署导致？
![iHaier20230201-112738](https://user-images.githubusercontent.com/19588624/215938542-32fbe644-bf0d-4614-a0ca-ba06100d557d.jpg)
![iHaier20230201-112906](https://user-images.githubusercontent.com/19588624/215938558-eaaed59e-c105-44fe-94c9-4178bf54816b.jpg)

### 重现步骤

测试跟踪-报告-查看测试报告

### 期待的正确结果

可以正常查看测试报告

**Comment by zyyfit** [comment]
您好，2.6.0版本没有复现这个问题，看url也没什么不对的地方，建议您升级试试

**Comment by wpiami** [comment]
> 您好，2.6.0版本没有复现这个问题，看url也没什么不对的地方，建议您升级试试

我们这边是前后端分离部署，前端这边是微前端部署的各个子服务，有没有可能是和这个部署方式有关系？请问你们这边部署是前后端分离部署吗？

**Comment by liuruibin** [comment]
前后分开部署的情况需要调整某些特殊接口（~~具体是哪些我们也没实践过~~）的解析，需要开发去自己调试
