### ISSUE TITLE
[BUG]上一个接口提取的参数，放到下一个接口中没有拿到提取的内容。

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#215]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
上一个接口提取的参数，放到下一个接口中没有拿到提取的内容。

**Bug 重现步骤**
1.  同一个场景中接口一提取了参数值
2. 接口二引用参数值
3. 执行后，接口二显示的仍为提取的字符的字符串，不是提取值
4. 

**期待的正确结果**
应该显示提取后的提取值。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/53041390/89853398-e4aefb80-dbc3-11ea-91c7-f3c4593f8409.png)
![image](https://user-images.githubusercontent.com/53041390/89853451-014b3380-dbc4-11ea-858b-eb47507a3601.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这种情况是因为没有提取成功。
可否把你第一个请求的响应格式发出来看一下？

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/89855886-4ffbcc00-dbca-11ea-881c-4e169f11faea.png)
![image](https://user-images.githubusercontent.com/53041390/89855915-5ee27e80-dbca-11ea-93f0-66123e174f02.png)
图1为接口一返回的请求值。
图2为引用的方式

**Comment by wangzhen-fit2cloud** [comment]
你如果是要提取 url 的话，提取的表达式应该类似 $.d.url 这样
