### ISSUE TITLE
[FEATURE]在性能测试中引用了接口自动化场景，运行失败后，无法在性能测试直接打开接口调试，要根据名称去接口测试列表查询，非常不方便

### ISSUE THREAD

**Issue by TSleon** [metersphere/metersphere#21504]
### MeterSphere 版本

V2.4

### 使用外置数据库

否

### 问题描述

在性能测试中引用了接口自动化场景，运行失败后，无法在性能测试直接打开接口调试，要根据名称去接口测试列表查询，非常不方便

### 重现步骤

在性能测试中引用了接口自动化场景，运行失败后，无法在性能测试直接打开接口调试，要根据名称去接口测试列表查询，非常不方便

**Comment by luty2018** [comment]
感谢反馈， 这个可以加。
