### ISSUE TITLE
[BUG]  批量删除功能用例后，未全部删除devops平台需求关联的功能用例链接

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21509]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.6

### 使用外置数据库

否

### 问题描述

批量删除功能用例后，未全部删除devops平台需求关联的功能用例链接

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/215984186-0ec48282-a29f-4722-8b4d-2f410652866f.png)
![image](https://user-images.githubusercontent.com/103925124/215984285-cf4524e9-deca-4047-ad00-0d33c57805cf.png)
批量删除上面4个用例，devops平台只删除了一个
代码原因：
![企业微信截图_16752384394311](https://user-images.githubusercontent.com/103925124/215984809-0481f1c3-b4e5-437b-89fb-09b3a4f8507a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
