### ISSUE TITLE
[BUG]1.7.3升级到1.8.2后, 部分项目已存在环境, 在场景中前端不请求获取环境列表, 点击运行环境显示无环境

### ISSUE THREAD

**Issue by pneo** [metersphere/metersphere#2150]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
1.7.3升级到1.8.2时, 部分项目已存在环境, 在场景中前端不请求获取环境列表, 点击运行环境显示无环境
**Bug 重现步骤**
1. 1.7.3 msctl upgrade
2. 打开已有环境的项目下的场景
3. 点击运行环境

**期待的正确结果**
正确情况下应该是什么样的？
显示已有环境列表
**截图**
只有部分项目存在该问题
![图片20210421092046](https://user-images.githubusercontent.com/12944903/115483390-42cbcc80-a283-11eb-9e88-c9fb39e6f93f.png)

**Comment by xulinde** [comment]
1.9.2已修复
