### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sephirothgao** [metersphere/metersphere#2151]
**MeterSphere 版本**
1.8.2
**Bug 描述**
ldap登录方式，使用发送邮件功能，邮箱配置正确的情况下，发送邮件失败，后台日志如下：
[Async-Executor1] ERROR i.m.n.sender.impl.MailNoticeSender 141 - Method[send][javax.mail.internet.AddressException: Domain contains illegal character in string ``xxx.xxx@@xxx.com'']

**Bug 重现步骤**
配置在新建测试计划时发送邮件，实际测试时没有发送，报错如上。

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您的接收邮箱配置的是正确的吗？我看报错里有两个@
