### ISSUE TITLE
[BUG]接口自动化测试报告导出显示不全

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#21515]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

当性能测试报告过长超过7页时发现后面的内容就不显示了

### 重现步骤

导出超过7页的性能测试报告发现有显示不全的问题
少于7页的报告是正常的

![image](https://user-images.githubusercontent.com/89765365/216002108-b469b0c0-acc3-4041-91b3-b5e6a8bac7fd.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by zyyfit** [comment]
您好，已修复，不过导出不全时还需要自己在导出弹框中设置缩放，代码中缩放页面会导致导出内容模糊
![image](https://user-images.githubusercontent.com/73461316/220230736-a2cb0af7-6951-4702-9a3b-9e4ed667b4a3.png)
