### ISSUE TITLE
[BUG]tapd同步缺陷到ms平台，详细步骤中的图片同步不过来。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21522]
### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

1.tapd同步缺陷到ms平台，没有将详细步骤中的图片同步过来

### 重现步骤

1.集成tapd，关联项目后
2.tapd创建详细步骤中带有图片的缺陷。
![image](https://user-images.githubusercontent.com/55130444/216013084-a2f958d1-2a73-49f1-a8ac-4a31f4536210.png)

3.ms平台选择同步缺陷
![image](https://user-images.githubusercontent.com/55130444/216013239-0de1ea2f-8aa1-4e00-ad3d-a4a64d9dfcfd.png)
4.查看同步的缺陷，发现图片没有同步过来
![image](https://user-images.githubusercontent.com/55130444/216013339-16561cda-c9a5-4af6-8a8a-1ed3f0609640.png)

### 期待的正确结果

能够将tapd缺陷详细步骤中的内容，包括文字和图片都同步到ms平台

**Comment by zyyfit** [comment]
请检查一下当前站点是否为 https 协议的，http的是无法同步tapd图片的

**Comment by zyyfit** [comment]
已复现

**Comment by zyyfit** [comment]
您好，由于 tapd 接口不支持访问图片，所以这个问题我们目前无法处理
