### ISSUE TITLE
[BUG]性能测试 导入csv方式以及stringfromfile方式 会报找不到文件错误

### ISSUE THREAD

**Issue by prozyworld** [metersphere/metersphere#2152]
**MeterSphere 版本**
v1.8.2-b4

**Bug 描述**
性能测试 导入csv方式以及stringfromfile方式 会报找不到文件错误

**Bug 重现步骤**
1.  单独测试场景可以正常读取文件
2. 场景放入性能测试中日志报找不到文件错误

**Comment by zyyfit** [comment]
您好，这个问题会在下个版本修复

**Comment by zyyfit** [comment]
最新版已修复
