### ISSUE TITLE
[FEATURE] 用例模板新增字段设置国际化同时实践的自定义字段可以升级为系统默认

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#21528]
### MeterSphere 版本

1.20.18

### 请描述您的需求或者改进建议

1. 在项目的用例模板中，新增自定义字段时，只能设置中文或者英文，切换语言会导致不匹配，无法实现真正的国际化
2. 经过实践，新增字段比较有实际意义的情况下，想推广到其他项目下，即设置为空间默认或系统默认模板，但是目前没有办法做到这一步

**Comment by luty2018** [comment]
目前自定义字段确实无法做到国际化，可能会考虑新增自定义字段时用户自行输入相应的国际化字段名
