### ISSUE TITLE
[BUG]场景中的接口添加文档结构断言，保存失败

### ISSUE THREAD

**Issue by 888888abc** [metersphere/metersphere#21527]
### 联系方式

（微信）MeterSphere 交流群48

### MeterSphere 版本

 v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

接口测试 - 场景测试 ，对API做 断言（文档结构校验），保存失败

### 重现步骤

页面路由：接口测试 -》 接口自动化 

1）构建场景自动化，复制API类型的CASE，对CASE断言
2）断言选择 “文档结构校验”
3）点击用例 「保存」 按钮，保存失败，没有调用接口
![WechatIMG614](https://user-images.githubusercontent.com/50913314/216218420-00bd4792-d427-4b4d-b83c-e1e80ce0221d.png)

### 期待的正确结果

可以保存成功

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.20 版本已修复
