### ISSUE TITLE
[FEATURE] 用例ID，建议自定义ID可调整为：前缀-自增ID

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21529]
### MeterSphere 版本

v2.5.1

### 请描述您的需求或者改进建议

用例ID，建议自定义ID可调整为：前缀-自增ID

### 请描述你建议的实现方案

建议修改为：前缀-自增ID，如ABC-00001、ABC-00002...

**Comment by chyhant** [comment]
自定义是没有任何限制，但是新增用例时不能自增，自己一个个填写的话，就很麻烦啦

**Comment by luty2018** [comment]
好的， 我们调研看看。

**Comment by chyhant** [comment]
建议可以参考一下testlink，迫切需要这个功能！

**Comment by luty2018** [comment]
好的，会尽快安排。
