### ISSUE TITLE
批量配置接口路径问题

### ISSUE THREAD

**Issue by windy0122** [metersphere/metersphere#21526]
### 请描述您的问题

如果有多个接口A,B,C，使用同一个域名如www.baidu.com，，如果同时设置这三个接口的域名都为www.baidu.com，，现在好像只能一个一个的设置，

**Comment by windy0122** [comment]
![image](https://user-images.githubusercontent.com/42708033/216214645-ad4f025d-608f-47a6-bce8-0097ca0a6977.png)

**Comment by luty2018** [comment]
你这里描述不太清楚， 不知道你具体要实现什么效果。

**Comment by windy0122** [comment]
就如我图片所显示的一样，，启用条件为路径来配置域名，，如果我有3个路径，A,B,C，，如果同时配置这三个路径的域名都为www.baidu.com，，

**Comment by luty2018** [comment]
目前需要添加3条

**Comment by windy0122** [comment]
希望能优化下，谢谢

**Comment by luty2018** [comment]
这个不是高频操作的功能，暂时不会对这里进行优化呢。
