### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by LF-lucky** [metersphere/metersphere#21521]
### MeterSphere 版本

2.4.1

### 请描述您的需求或者改进建议

能否支持在case内选择是否使用全局断言，比如全局断言errorcode=0，但是异常的case不满足，全局断言会被认为失败

**Comment by luty2018** [comment]
这个有在规划中，敬请关注哈。

**Comment by LF-lucky** [comment]
请问改需求在最新的2.7.0中有优化吗

**Comment by luty2018** [comment]
不会， 这个我们计划在v3.0版本去做。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
