### ISSUE TITLE
[QUESTION][TAPD缺陷模板]添加自动定义字段，自动如何配置，才能同步到TAPD系统上去

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#21525]
### 请描述您的问题

【版本信息】
2.4版本

【问题】
1. MS上的系统默认字段【严重程度】不能同步到TAPD上
2. MS上添加【优先级】字段中【选项内容】【选项ID】如何与TAPD上的【优先级】自动映射起来
![企业微信截图_1675247321763](https://user-images.githubusercontent.com/6109912/216018166-ff4f655b-c16a-438b-965d-9cb30da26276.png)
![企业微信截图_16752473484478](https://user-images.githubusercontent.com/6109912/216018262-496c4d01-0a2f-4d47-8b4f-5c0dac413c16.png)

**Comment by luty2018** [comment]
自定义字段不支持双向同步哦。
