### ISSUE TITLE
[BUG]富文本编辑器插入图片链接不生效，图片经常加载不出来

### ISSUE THREAD

**Issue by cxltsui** [metersphere/metersphere#21533]
### 联系方式

979621136@qq.com

### MeterSphere 版本

1.20.14-lts

### 使用外置数据库

否

### 问题描述

富文本编辑器插入图片链接不生效，图片经常加载不出来

### 重现步骤

创建缺陷，插入图片链接

### 附加信息

![864740b0199450c660ee1ec8f3a0e20](https://user-images.githubusercontent.com/42922417/216255857-2d84ed0d-daa1-4e51-a9a9-b870dd14491b.jpg)

**Comment by zyyfit** [comment]
您好，请检查一下图片链接是否需要权限等，我这里从百度找的图片，没有复现
![image](https://user-images.githubusercontent.com/73461316/216290966-f56c1a49-9367-4569-b357-4a01bed1a7f2.png)
![image](https://user-images.githubusercontent.com/73461316/216291077-17c58303-befd-4208-ac04-92053de0ce03.png)

**Comment by cxltsui** [comment]
偶现，但是出现问题频率很高。大部分时间都是显示有问题，包括历史图片。与图片权限无关，请看如下图，同样的图片链接，不同的效果：
![image](https://user-images.githubusercontent.com/42922417/216293905-bb77de76-92ca-4169-a527-b212dca19c8b.png)
![image](https://user-images.githubusercontent.com/42922417/216293949-290c7efc-7a57-4eb4-a16c-33f4348d8603.png)

**Comment by zyyfit** [comment]
还是没有复现，是不是网络连接不好，导致图片加载不出来？

**Comment by cxltsui** [comment]
点图片链接下载图片感觉还是蛮快的

**Comment by zyyfit** [comment]
您方便把图片链接提供给我们吗？我们看一下具体是什么问题
