### ISSUE TITLE
[BUG] V2.6 功能测试-脑图创建名称同样的模块，页面会卡

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21531]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.6

### 使用外置数据库

否

### 问题描述

# V2.6 功能测试-脑图创建名称同样的模块，页面会卡
![image](https://user-images.githubusercontent.com/33945037/216246606-312e00c7-f026-48be-9a98-85d0425bdc9f.png)

### 重现步骤

如上图所示

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本发布后验证
