### ISSUE TITLE
[BUG]通用环境变量中只填了变量名没填变量值，然后执行用例会报错csrf token is empty

### ISSUE THREAD

**Issue by fankun8894** [metersphere/metersphere#2153]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.1-13242356
**Bug 描述**
简要描述您碰到的问题
通用环境变量中只填了变量名没填变量值，然后执行用例，会报错
HTTP ERROR 500 javax.servlet.ServletException: java.lang.RuntimeException: csrf token is empty

**Bug 重现步骤**
1.  通用环境变量中只填了变量名没填变量值
2. 然后执行用例
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
用例执行成功

**截图**
如果有截图，请附上截图.
![1618974462874](https://user-images.githubusercontent.com/82922253/115491429-8d087a00-a292-11eb-8a52-e6bf73806c3d.jpg)

**Comment by zyyfit** [comment]
您好，下个版本修复这个问题

**Comment by zyyfit** [comment]
最新版已修复
