### ISSUE TITLE
[BUG]v.2.6.0,  MS同步缺陷，同步过来的数据，报告人 和 经办人 栏位没有同步成功

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21541]
### 联系方式

王进

### MeterSphere 版本

v.2.6.0

### 使用外置数据库

否

### 问题描述

v.2.6.0,  MS同步缺陷，同步过来的数据，报告人 和 经办人 栏位没有同步成功

### 重现步骤

1. 上传最新插件到MS系统设置，插件管理
2. 完成服务集成配置
3. 完成项目集成配置
4. 测试跟踪页面，点击缺陷管理，同步jira项目缺陷成功。
5. 检查数据，发现同步过来的数据，报告人 和 经办人 栏位没有同步成功。
<img width="405" alt="image" src="https://user-images.githubusercontent.com/76033005/216286567-b060dc1f-21fd-4fac-8278-4f7d698b469f.png">

### 附加信息

用建星给的最新版JIRA插件实测，测试同学无需复测，建星已知晓该bug。

另外，sprint，环境，史诗链接等字段也没有同步过来，客户想要 sprint和环境 这两个字段。 

<img width="513" alt="image" src="https://user-images.githubusercontent.com/76033005/216287472-6b3571f9-fc81-4a39-97f7-990ab4832a27.png">

**Comment by zrfit** [comment]
v2.7已修复该问题。
