### ISSUE TITLE
[FEATURE]用例支持预览

### ISSUE THREAD

**Issue by LsdtkDds** [metersphere/metersphere#2154]
**请描述您的需求或者改进建议.**

测试用例支持打开链接预览，不需要登录

**请描述你建议的实现方案**
打开链接，可以直接预览

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 测试用例支持打开链接预览，不需要登录
> 
> **请描述你建议的实现方案**
> 打开链接，可以直接预览

可以考虑支持分享功能
