### ISSUE TITLE
[FEATURE]接口定义 query参数、rest参数、 请求体中添加字段描述

### ISSUE THREAD

**Issue by tqq1994516** [metersphere/metersphere#21543]
### MeterSphere 版本

v2.6.0-068f4f4a

### 联系方式

18群  田

### 请描述您的需求或者改进建议

接口定义 query参数、rest参数、 请求体中添加字段描述，接口字段存在一些特殊规则可能需要备注

### 请描述你建议的实现方案
类似apipost 接口字段描述的效果
![image](https://user-images.githubusercontent.com/61398122/216297050-84abdb94-cd70-40e4-a416-af8ab2b8f240.png)
![image](https://user-images.githubusercontent.com/61398122/216297192-5d3a31bf-1e38-4113-9019-af3510a40162.png)
json请求体字段备注，希望可以在json-schema 模板处体现类似效果
![image](https://user-images.githubusercontent.com/61398122/216298754-cf6781fb-4f5a-4dd1-a5ba-500826c2090a.png)

最好字段描述可以聚合显示到接口文档那块
![image](https://user-images.githubusercontent.com/61398122/216298729-23d92b25-fabc-49f3-b48d-99e3446a8e74.png)

**Comment by luty2018** [comment]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/36292514/216500235-edadd751-c03d-4011-aee8-cbcdce34e1bc.png">
你可以升级到新版本使用哈，已经添加了描述。
