### ISSUE TITLE
[BUG]在接口自动化中上传csv文件 ，使用场景变量，接口中传参无法引用到

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#21549]
### 联系方式

3095500370@qq.com

### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

在上传了csv文件，按其文档引用csv中的场景变量，无法引用成功

### 重现步骤

1. 上传一个csv文件并可成功预览到 
![image](https://user-images.githubusercontent.com/49423711/216525739-78296748-0be6-437d-ada9-01b85cc279db.png)
2. 在接口中引用csv文件中的字段
![image](https://user-images.githubusercontent.com/49423711/216525862-3e8d20f6-78d5-4915-a7ef-627401b9628e.png)
3. 点击调试查看无法取到对应csv中的数据
![image](https://user-images.githubusercontent.com/49423711/216526181-b0afb8f2-a9e4-4c44-b7c1-8f4e54b4a5fb.png)

### 期待的正确结果

能获取到csv中的数据进行请求

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问是必现的吗？方便把您的场景导出来给我们看一下吗？
![image](https://user-images.githubusercontent.com/73461316/216580346-05b103d0-4935-4315-ad03-dfc6ad74c9d0.png)

**Comment by zhouxiongjie1997** [comment]
我使用的是开源版本，需要怎么导出？

**Comment by zyyfit** [comment]
开源版和企业版在这个功能上没有什么区别的，把场景导出成metersphere格式，然后和csv文件一起打个包上传附件就可以了，如果有敏感数据可以修改一下数据

**Comment by zhouxiongjie1997** [comment]
[Metersphere_Scenario_MDC(Market Data Cloud).zip](https://github.com/metersphere/metersphere/files/10672037/Metersphere_Scenario_MDC.Market.Data.Cloud.zip)
麻烦看下

**Comment by zhouxiongjie1997** [comment]
[v2chartstats.csv](https://github.com/metersphere/metersphere/files/10672043/v2chartstats.csv)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我们排查了一下，使用jmeter执行的时候，这个文件里的值也取不到，重新编写一个csv文件，或者检查一下文件格式是否正确

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
