### ISSUE TITLE
[BUG]接口定义case,后置脚本有错误，有时控制台打印不出来，多次执行会打印出错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21544]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

接口定义case,后置脚本有错误，有时控制台打印不出来，多次执行会打印出错误

### 重现步骤

1.接口定义case,添加后置脚本，脚本有错误
![image](https://user-images.githubusercontent.com/103627487/216289112-67439c6f-6ef4-4aff-9448-357869654ad6.png)
2.执行case，控制台脚本打印像是未打印全
![image](https://user-images.githubusercontent.com/103627487/216290075-8eed2db4-6804-4e76-bf57-8bc0a6020619.png)
3.再次或者多次执行case，控制台脚本出现错误
![image](https://user-images.githubusercontent.com/103627487/216290719-86cf32bf-9de0-4662-a2c5-a3031367874f.png)

### 期待的正确结果

期望控制台能正确打印

**Comment by zyyfit** [comment]
1、打印不出来可能是因为修改了后置脚本但是没保存上，这个问题已经修复了，请等待2.6.1版本发布后验证一下
2、beanshell中不加 ； 报错是正常的

**Comment by meijieDouDou** [comment]
1、打印不出来可能是因为修改了后置脚本但是没保存上，https://github.com/metersphere/metersphere/issues/21425 这个问题是2.6.0的bug, lts 版本没有这个问题。https://github.com/metersphere/metersphere/issues/21544 这个问题是在 lts 版本发现的问题，可能不是同一个问题
2、1、打印不出来可能是因为修改了后置脚本但是没保存上，https://github.com/metersphere/metersphere/issues/21425 ，这个问题已经修复了，请等待2.6.1版本发布后验证一下   
lts 版本也会同步修复吗？

**Comment by zyyfit** [comment]
1、看了一下 1.20 版本是没有 https://github.com/metersphere/metersphere/issues/21425 这个问题，请忽略
2、现在这个issue 也没有复现，请问是必现的吗？是否可以详细描述一下复现步骤？

**Comment by zyyfit** [comment]
已确认未复现
