### ISSUE TITLE
[BUG]性能测试报告监控资源切换，表格数据不切换

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#21548]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.18-lts

### 使用外置数据库

否

### 问题描述

性能测试报告监控资源切换，表格数据不切换

### 重现步骤

1、跑一个性能测试，监控两台服务器，一台有数据，一台没数据
2、从有数据的资源切换到没数据的资源，下方表格还是展示的原数据
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/72729206/216502961-16696110-d967-4377-8726-fdb7f6afbe63.png">

### 期待的正确结果

1、切换到没有数据的资源，表格展示为空表格

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.7.0版本修复了这个问题，因为影响不大并且1.20版本主要以功能稳定为主，所以1.20版本不修复了
