### ISSUE TITLE
[BUG] 【接口测试】-后置操作-提取参数-正则-匹配多条-只能匹配一条数据

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#21556]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

接口测试时，提取参数采用正则，勾选匹配多条选项，只能匹配一条数据

### 重现步骤

1.打开接口用例
2.后置操作-提取参数-正则
3.勾选匹配多条

### 期待的正确结果

勾选匹配多条，能匹配所有符合条件的数据

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/216570158-0102017a-6052-4fb8-97e1-682523f5dad8.png)

![image](https://user-images.githubusercontent.com/45531073/216569998-ec84410f-6507-44b5-96c0-0ae4235645da.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问是必现的吗？
![image](https://user-images.githubusercontent.com/73461316/216583651-3dc76825-6625-4b78-866b-a1879e785528.png)
