### ISSUE TITLE
[BUG]ms访问时出现：{"success":false,"message":"finishConnect(..) failed: Connection refused: /172.30.10.14:8005","data":null}

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#21551]
### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

{"success":false,"message":"finishConnect(..) failed: Connection refused: /172.30.10.14:8005","data":null}

### 重现步骤

偶现，能自动恢复，暂无重现步骤

**Comment by zyyfit** [comment]
您好，可以修改一下 yml配置文件，mem_limit 配置，把这个报错的服务的资源给大一些

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
