### ISSUE TITLE
[FEATURE]希望支持更多的数据库连接类型

### ISSUE THREAD

**Issue by chenrenyiabc** [metersphere/metersphere#21552]
### MeterSphere 版本

v1.20.11-lts-1f22fc0e

### 请描述您的需求或者改进建议

目前MeterSphere平台只支持mysql等4种类型的数据库连接，希望支持更多类型的数据库连接，如clickhouse/hive/mongodb/presto等

### 请描述你建议的实现方案

建议考虑扩展插件进行支持，可以让用户上传数据库驱动jar包支持

**Comment by luty2018** [comment]
感谢反馈，经过调研，jmeter有clickhouse的插件，这块理论上可以支持的。
