### ISSUE TITLE
[BUG]场景里前置脚本读取csv里的变量，语言Groovy,循环读取，只读取第一条数据

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21562]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

场景里前置脚本读取csv里的变量，语言Groovy,循环读取，只读取第一条数据

### 重现步骤

1.创建场景，上传csv文件
![image](https://user-images.githubusercontent.com/103627487/216579933-2ace5d9c-1517-4ecf-b705-01f66d483159.png)
2.前置脚本打印csv中变量，语言选择Groovy,添加循环控制器，次数循环，
![image](https://user-images.githubusercontent.com/103627487/216580248-1e69acf5-ca31-4be8-a95a-d76a6e7d1cf4.png)
3.执行后查看控制台打印，只打印了csv第一行变量
![image](https://user-images.githubusercontent.com/103627487/216580405-2918c00e-a81a-4a76-8744-3aaf340be940.png)

### 期待的正确结果

期望正常读取

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by fit2-zhao** [comment]
感谢反馈，此缺陷和 #21478 是同一个问题。

**Comment by zyyfit** [comment]
1.20.20 和 2.7.0 版本已修复，请等待版本发布后验证
