### ISSUE TITLE
[BUG]非 BeanShell，打印 CSV 数据有误

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21566]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

非 BeanShell，打印 CSV 数据有误

### 重现步骤

1.定义 CSV 场景变量
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/4860962/216759759-d309b74c-62ec-48d3-9c6f-6fc245bd61a0.png">

2.beanshell 打印结果，可以正常打印不同的 id
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/4860962/216759820-8eefc0b7-06f4-49bf-ab2d-a1145a1cf589.png">

3.非 BeanShell，尝试的 groovy和 python，打印的都是第一个 id
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4860962/216759865-7088eddc-b02d-43b3-9a9e-48fc77e30a68.png">

4.且显示有 error，控制台看不到错误日志
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4860962/216759919-ef42dcc5-62a3-4727-bcbb-3b53db5e9ce8.png">

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/21562

**Comment by zyyfit** [comment]
1.20.20 和 2.7.0 版本已修复，请等待版本发布后验证
