### ISSUE TITLE
接口场景引入接口case后不能修改，使用不方便，建议引入后后置 处理和断言可以修改，这样接口case的复用性会

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#21565]
### MeterSphere 版本

v1.20.18-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

背景：目前接口场景复制或引入接口case，这2种方式都有弊端：复制时，接口case调整了不能同步接口场景，导致接口cese和场景都要调，重复操作；引入时，接口场景里面不能调整接口case，而不同场景引入同一接口只是后置提取不一样时，相同接口的接口case要写多个才能满足不同场景
建议：接口场景引入接口case后，可以在场景里面调整接口后置处理和断言，这样不影响接口用例，还能可以大大减少接口case的重复性

### 请描述你建议的实现方案

建议：接口场景引入接口case后，可以在场景里面调整接口后置处理和断言，这样不影响接口用例，还能可以大大减少接口case的重复性

### 附加信息

![微信图片_20230204114959](https://user-images.githubusercontent.com/39357523/216746479-018dc8cd-1bc7-4677-9daf-54f5bcabd8af.png)

**Comment by luty2018** [comment]
目前我们还是会维持引用的用例不能编辑这样的原则。
