### ISSUE TITLE
[BUG]根据MeterSphere Jmeter镜像生成新镜像时，镜像校验失败

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#21573]
### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

根据MeterSphere Jmeter镜像生成新镜像时，镜像校验失败

### 重现步骤

1、编写dockerfile如下：
![image](https://user-images.githubusercontent.com/5198427/216878491-89bd8c80-0f5c-4aaf-8aea-a57c14c434a1.png)
2、执行镜像生成命令：
docker build -t jmeter-test .
打包过程和报错信息如下：
![image](https://user-images.githubusercontent.com/5198427/216878599-6fb966d2-90f0-4fc0-85cf-44aa49a118d0.png)

### 期待的正确结果

基于MeterSphere Jmeter镜像能正常打包新镜像

**Comment by liuruibin** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/23045261/217137977-1e49bce2-804e-4062-b363-576a4c13ce78.png">
没有复现出来，换台机器试试看

**Comment by xieqione** [comment]
我这边生成镜像Sending build context to Docker daemon 显示超过9G，我看你的截图里才56.54MB，这是为什么呀？

**Comment by xieqione** [comment]
换了几台机器都不行，我们这边有服务器限制外网访问，我这边已经申请且通过的白名单权限如下：
ttps://dockerauth-cn-qingdao.aliyuncs.com
https://registry.cn-qingdao.aliyuncs.com
还需要其他的URL地址访问权限么？

**Comment by liuruibin** [comment]
限制外网的情况下，先在能访问的地方下载镜像，保存成tar然后转移到内网环境里。

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
