### ISSUE TITLE
[BUG] Jira 自定义字段 Epic link 创建缺陷提示字段类型不匹配

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#21574]
### 联系方式

18159668371

### MeterSphere 版本

V2.5.1

### 使用外置数据库

否

### 问题描述

Jira 自定义字段 Epic link 创建缺陷提示字段类型不匹配
![image](https://user-images.githubusercontent.com/92966838/216880954-a5b94ed7-06b2-4d0d-81af-b531a28311e2.png)

### 重现步骤

1、MS中 配置 Epic link 自定义字段
![image](https://user-images.githubusercontent.com/92966838/216881073-6b4e6188-9e01-4aae-b8ce-dbce07a37ec5.png)
2、Jira 中该字段也为单选下拉框，选项应该是字符串形式
![image](https://user-images.githubusercontent.com/92966838/216881174-b3d09fc7-4192-42fb-8fbb-ee3e5c24e393.png)
3、创建缺陷点击提交提示报错
![image](https://user-images.githubusercontent.com/92966838/216880954-a5b94ed7-06b2-4d0d-81af-b531a28311e2.png)

### 期待的正确结果

能够正确处理这个字段

**Comment by zrfit** [comment]
您好，感谢您的反馈，最行版本v2.6.1未复现该问题，请升级后尝试验证。

**Comment by zrfit** [comment]
经沟通，最新版本已经不存在该问题。
