### ISSUE TITLE
[BUG]UI自动化环境勾选之后没有删除勾选的按钮

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#21575]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

UI自动化环境勾选之后没有删除勾选的按钮

### 重现步骤

1、UI自动化执行的时候勾选了环境，想叉掉这个勾选的环境时发现无法叉掉，因为UI场景不是必须的，所以存在误勾选的情况
![image](https://user-images.githubusercontent.com/35896106/216881103-5f9a6e81-17e2-4579-bd5c-f0f2511e0313.png)

2、参考接口测试那边
![image](https://user-images.githubusercontent.com/35896106/216881299-b3408af1-9d9c-4f27-9951-d68e561d80d7.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！下个版本优化。

**Comment by zrfit** [comment]
v2.7已优化该功能，环境可以删除了。
