### ISSUE TITLE
[BUG]UI自动化更新后其他账号看到的系统通知不对

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#21576]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

账号A进行UI自动化的场景更新，账号B看到的系统通知是账号A更新了接口自动化的内容

### 重现步骤

1、账号A进入UI自动化页面进行场景的更新保存操作
2、账号B查看到步骤1操作后的系统通知---账号A更新了接口自动化XXX

### 期待的正确结果

账号B查看到的系统通知---账号A更新了UI自动化XXX

### 附加信息

![QQ截图20230206121759](https://user-images.githubusercontent.com/117417157/216883741-c6320340-519b-4036-b22b-b48b5030b566.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
您好，v2.7版本已优化，修改UI版本不会接收到系统，UI自动化模块的通知后续版本会统一规划。
