### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tianx08** [metersphere/metersphere#21585]
### MeterSphere 版本

v1.20.14

### 请描述您的需求或者改进建议

1、用例输入时、步骤、检查点不支持图片展示
2、脑图展示用例是时、不支持显示markdown内容（备注 ），脑图节点不支持图片
3、脑图用例文本不支持部分文字高亮、着色
4、用例执行时仅支持按步骤显示、不支持单个用例脑图展示

**Comment by luty2018** [comment]
感谢反馈， 脑图这块的重构在规划中。
