### ISSUE TITLE
[BUG] Jira 缺陷模板字段无法完全同步

### ISSUE THREAD

**Issue by gaohonghai** [metersphere/metersphere#21597]
### 联系方式

18159668371

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

问题描述：
- 使用 Jira Saas 版本，关联项目至 MS，在创建缺陷拉取缺陷模板时，没有拉到 Jira 缺陷模板的所有字段，如下图所示：

Jira 默认的缺陷字段：
![image](https://user-images.githubusercontent.com/92966838/217131759-553d1037-e3f9-4600-8318-fb344fd53803.png)

MS 拉取到的缺陷字段：
![image](https://user-images.githubusercontent.com/92966838/217131788-b1d135f4-a08b-4062-bb2d-8ae8ecfc07cf.png)

### 重现步骤

1、注册 Jira Cloud 并创建项目；
2、Jira 项目中创建缺陷，查看控制台接口拉取的缺陷字段； 
3、MS 关联 Jira 项目；
4、MS 创建缺陷，查看控制台接口拉取 Jira 的缺陷字段；
5、比对

**Comment by zrfit** [comment]
已沟通确认，v2.7该问题已修复。
