### ISSUE TITLE
[BUG]接口测试中用了xpath断言失败，在jmeter中执行是成功的

### ISSUE THREAD

**Issue by zhenzhendong** [metersphere/metersphere#21596]
### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

接口测试中用了xpath断言失败，在jmeter中执行是成功的

### 重现步骤

接口测试-接口定义-添加断言规则-xpath方式

### 附加信息

<img width="630" alt="7c127816cbf5af7d9ccf3df9fea5b35" src="https://user-images.githubusercontent.com/122069934/216996147-fce2f7f4-b9dc-436c-ba37-efd01e984ac2.png">
![image](https://user-images.githubusercontent.com/122069934/216996309-e963eef6-259c-457a-9a1b-854f2bc2b02f.png)

**Comment by zyyfit** [comment]
您好，jmeter里的xpath断言有2个，我们系统里采用的是xpath2断言，然后xpaht断言和xpath2断言的写法是不一样的，请确认jmeter里的组件是否为xpaht2
![image](https://user-images.githubusercontent.com/73461316/217162348-dd9dce6a-1e67-4595-a525-66367c29ba14.png)

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
