### ISSUE TITLE
[BUG]场景中，断言处，加了文档结构校验后，场景无法保存和调试

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21595]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

场景中，断言处，加了文档结构校验后，场景无法保存和调试

### 重现步骤

1.创建场景，断言规则处添加文档结构校验，添加后展开root
![image](https://user-images.githubusercontent.com/103627487/216954088-c4663f58-3b40-460f-883c-8ed0071ace19.png)
2.点击调试和保存页面无反应
3.F12查看页面有报错
![image](https://user-images.githubusercontent.com/103627487/216954599-c86f9f92-f667-4ea7-8cd6-d917e87d7642.png)

**Comment by fit2-zhao** [comment]
在 v1.20.19-lts 版本已经修复过，请升级。

https://github.com/metersphere/metersphere/commit/bc608e60b7cb5959d27ed78ddeb1428cdc6cf466

**Comment by zrfit** [comment]
您好，已知问题，1.20.20-lts已修复，待发布后可升级验证。
