### ISSUE TITLE
[BUG] 场景报告导出为pdf，pdf只有三页，三页后的数据丢失

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21590]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.6

### 使用外置数据库

否

### 问题描述

场景报告导出为pdf，pdf只有三页，三页后的数据丢失

### 重现步骤

场景报告很长，有59个接口
![image](https://user-images.githubusercontent.com/103925124/216927247-f9d340aa-37f6-4e09-96c0-30a9cc9e4158.png)
导出pdf只有三页，不全
![image](https://user-images.githubusercontent.com/103925124/216927581-a2443981-b9c7-458c-8de2-48712b207c5e.png)

**Comment by fit2-zhao** [comment]
和这个#21515 重复
