### ISSUE TITLE
[BUG]swagger导入的接口没有配置默认超时时间，导致修改case的超时时间后，场景中引用的case也不能同步修改超时时间

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#21594]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.19-lts

### 使用外置数据库

否

### 问题描述

swagger导入的接口没有配置默认超时时间，导致修改case的超时时间后，场景中引用的case也不能同步修改超时时间

### 重现步骤

1.从swagger导入接口定义，接口没有给默认超时时间
![image](https://user-images.githubusercontent.com/88763608/216942725-68687db9-3194-463d-be56-e563fbb1d714.png)
2.创建接口case，并将接口case引用到场景中
![image](https://user-images.githubusercontent.com/88763608/216942911-b3378340-8535-4af2-a507-6d03defdbf6e.png)
![image](https://user-images.githubusercontent.com/88763608/216943020-b08ae4fa-9428-4474-8bd5-6a948202d76c.png)
3.修改原case的接口超时时间，再查看场景中case超时时间有没有同步，发现没有同步
![image](https://user-images.githubusercontent.com/88763608/216943270-8fcca82c-b9de-476d-9e9d-88d9347c2e18.png)
![image](https://user-images.githubusercontent.com/88763608/216943397-3167bfe7-4797-4e5b-aaac-e8a57a63dde9.png)

### 期待的正确结果

1.修改超时时间后，应该要同步到场景引用的case中
2.希望swagger导入的接口也默认给一个超时时间，不然每个接口都要手动设置一个超时时间，非常的费时

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.20 版本 和 2.7.0 版本都已修复

**Comment by linfengjjj** [comment]
已修复
