### ISSUE TITLE
[BUG]【项目设置-自定义代码】当前页面没有重置按钮，导致使用右侧的其他几项功能时，内容没有被清除，全都堆积在当前页面内。若想切换使用右侧的功能时，还得手动清除页面内容。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21608]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

【项目设置-自定义代码】当前页面没有重置按钮，导致使用右侧的其他几项功能时，内容没有被清除，全都堆积在当前页面内。若想切换使用右侧的功能时，还得手动清除页面内容。
![image](https://user-images.githubusercontent.com/104960608/217174042-3af74605-11a7-4e8f-b309-94ff2de769f6.png)

### 重现步骤

【项目设置-自定义代码】当前页面没有重置按钮，导致使用右侧的其他几项功能时，内容没有被清除，全都堆积在当前页面内。若想切换使用右侧的功能时，还得手动清除页面内容。
![image](https://user-images.githubusercontent.com/104960608/217174064-5a8ed890-7807-4fff-9c90-1dd327356ad4.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！右侧功能项是便于用户点击不同功能项直接添加显示到代码片段区域的，如果用户想要去掉部分代码，可以注释掉或者直接删除；如果全部代码片段都要删除，则快捷键全选直接删除就可以了。与产品沟通，目前设计如此。

**Comment by zrfit** [comment]
您好，感谢您的反馈！右侧功能项是便于用户点击不同功能项直接添加显示到代码片段区域的，如果用户想要去掉部分代码，可以注释掉或者直接删除；如果全部代码片段都要删除，则快捷键全选直接删除就可以了。与产品沟通，目前设计如此。
