### ISSUE TITLE
[BUG]主线版本脚本中加载js文件会执行异常

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#21604]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

主线版本脚本中加载js文件会执行异常，在lts版本中是正常的
参考这篇文章配置https://zhuanlan.zhihu.com/p/601063897

### 重现步骤

1.在接口自动化前置脚本中使用javascript脚本，输入以下内容
g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;
2.执行接口自动化场景，场景异常，没有任何响应
![image](https://user-images.githubusercontent.com/88763608/217169318-e7946954-30d9-4a12-b2cf-c47f8e8bd349.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zhangzhaox** [comment]
@linfengjjj 那个版本的LTS版本是正常的

**Comment by zyyfit** [comment]
> @linfengjjj 那个版本的LTS版本是正常的

最新版 1.20.19-lts 是正常的

**Comment by zyyfit** [comment]
2.7.0 版本已修复，请等待版本发布后验证

**Comment by linfengjjj** [comment]
已验证，已解决
