### ISSUE TITLE
[BUG]性能压测结束之后一直处于 running 状态

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#21606]
### 联系方式

ke-liang

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

性能压测结束之后一直处于 running 状态

### 重现步骤

1. 执行性能压测脚本

结果：
压测结束之后一直处于 running 状态，另外 TPS 值统计的不正确，之前相同的线程数可以达到 4000 多的TPS，现在只有 800 多，查询其它监控还是 4000 多的 TPS

**Comment by zyyfit** [comment]
您好，没有复现您这个问题，能稳定复现吗？如果可以的话请详细描述一下操作步骤详情 和 性能测试用例配置。
另外，请上传一下性能测试执行日志信息，包括ms服务中性能测试模块的日志和测试资源池的日志。
如果方便的话也请上传一下性能测试的资源文件
![image](https://user-images.githubusercontent.com/73461316/217456224-a7954704-615a-4d73-8066-e3e84b061ecb.png)

**Comment by ke-liang** [comment]
> 您好，没有复现您这个问题，能稳定复现吗？如果可以的话请详细描述一下操作步骤详情 和 性能测试用例配置。 另外，请上传一下性能测试执行日志信息，包括ms服务中性能测试模块的日志和测试资源池的日志。 如果方便的话也请上传一下性能测试的资源文件 ![image](https://user-images.githubusercontent.com/73461316/217456224-a7954704-615a-4d73-8066-e3e84b061ecb.png)

你这回复错地方了吧

**Comment by ke-liang** [comment]
环境配置问题，已解决
