### ISSUE TITLE
[BUG]思维导入导入后全部倒序对应

### ISSUE THREAD

**Issue by dengxy123321** [metersphere/metersphere#21607]
### 联系方式

dengxy@yeastar.com

### MeterSphere 版本

v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

思维导图的方式导入后，ID全部倒序对应
比如思维导图上下顺序1、2、3，导入后对应的ID为200009、200008、200007
期望结果：正序分配ID

### 重现步骤

思维导图的方式导入后，ID全部倒序对应
比如思维导图上下顺序1、2、3，导入后对应的ID为200009、200008、200007
期望结果：正序分配ID

### 期待的正确结果

思维导图的方式导入后，ID全部倒序对应
比如思维导图上下顺序1、2、3，导入后对应的ID为200009、200008、200007
期望结果：正序分配ID

**Comment by luty2018** [comment]
这里列表的设计是按创建时间排序，所以ID肯定是倒序。
但是为了满足用户导入文件时希望按列表顺序展示，所以对排序做了处理。
如果你用Excel的方式看列表会有点误导是ID分配不对，但事实上ID只是用例的一个属性，在这里并没有用例顺序的含义，如果你对ID和用例有强需求，建议你可以使用自定义ID来进行自主排序。
