### ISSUE TITLE
[BUG]【项目设置-自定义代码】输入内容点击确定按钮后，当前页面没有关闭，还得手动点击“X"才能关闭页面

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21605]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

项目设置-自定义代码片段，点击确定按钮后，当前页面没有关闭，还得手动点击“X"才能关闭页面
![image](https://user-images.githubusercontent.com/104960608/217169699-d60c3cc7-b963-452b-9c45-3f269b4ea3a7.png)

### 重现步骤

项目设置-自定义代码片段，点击确定按钮后，当前页面没有关闭，还得手动点击“X"才能关闭页面
![image](https://user-images.githubusercontent.com/104960608/217170092-03a5034f-d448-4aa3-8277-01ecd027c593.png)

**Comment by zyyfit** [comment]
因为这里保存后还有可能需要调试，所以设计的手动关闭

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
