### ISSUE TITLE
[BUG]定时执行的测试计划在执行失败后将报告分享至钉钉群，但是访问钉钉群的链接发现，执行结果取的是最新执行的结果，而我们是想看当时执行失败时的接口执行信息

### ISSUE THREAD

**Issue by gongruilinggit** [metersphere/metersphere#21600]
### 联系方式

MeterSphere 交流群41  龚瑞凌

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

否

### 问题描述

定时执行的测试计划在执行失败后将报告分享至钉钉群，但是访问钉钉群的链接发现，执行结果取的是最新执行的结果，而我们是想看当时执行失败时的接口执行信息

### 重现步骤

1、定时执行测试计划，设置执行失败分享至钉钉群
2、执行测试计划并失败，钉钉群收到报告链接
3、再次执行测试计划并执行成功
4、打开钉钉群收到的报告链接
5、链接里的接口具体执行信息已经不是执行失败的信息而是执行成功的信息

### 期待的正确结果

分享到钉钉群的那个报告链接里的具体内容 不要被覆盖 我分享到钉钉群的时候是什么样子 永远是什么样子 

### 附加信息

![Uploading 截图ms.png…]()

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.21版本已修复该问题。
