### ISSUE TITLE
[BUG]性能压测的场景配置页面，资源文件的加载文件页面显示不全所有文件

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#21603]
### 联系方式

ke-liang

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

性能压测的场景配置页面，资源文件的加载文件页面显示不全所有文件

### 重现步骤

1. 进入性能压测的场景配置页面
2. 打开资源文件的加载文件页面

结果：
不能显示已经上传的所有文件

### 期待的正确结果

可以显示已经上传的所有文件

**Comment by zyyfit** [comment]
您好，请问是什么文件没有显示呢？

**Comment by ke-liang** [comment]
> 

加载文件页面原本有 14 个，只显示了 10，没有我想要个更新的文件 A；
如果是新增测试场景，加载文件那里是可以显示 14 个，通过这种方式我更新了文件 A；之后再去原来的脚本中打开【加载文件】页面，此时可以显示 11 个，即新增显示了文件 A，但是还是没有全部显示

**Comment by zyyfit** [comment]
您好，没有复现您这个问题，不显示的文件后缀是什么？

**Comment by ke-liang** [comment]
1. 在 v2.5.1 版本，加载文件页面有 14 个文件，.csv, .jmx, jar 等
2. 升级到 v2.6.0 版本，没有做任何更新操作，几天后又更新到最新版本 v2.6.1
3. 更新加载文件页面的 .csv 文件

【实际结果】
加载文件页面只显示 10 个文件，并没有显示我要更新的那个 csv 文件

**Comment by zyyfit** [comment]
还是没有复现，您更新一下不显示的文件试试？
![image](https://user-images.githubusercontent.com/73461316/218366768-18b8c86f-31b2-44f9-a24a-ed510729fdc4.png)

**Comment by ke-liang** [comment]
> 

删除后重新上传可以的

**Comment by zyyfit** [comment]
> 删除后重新上传可以的

那请您先更新一下文件然后再观察一下看看会不会出现这种问题吧

**Comment by 13290445582** [comment]
最新环境未复现该问题，若存在问题请升级至v2.10.2版本，感谢。
