### ISSUE TITLE
[BUG]从脑图给用例切换模块之后需求ID没有了

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#21615]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

版本:   v1.20.19-lts-a80199cf

### 使用外置数据库

是

### 问题描述

脑图用例有需求id的然后挪到其他模块中需求id消失了
![image](https://user-images.githubusercontent.com/39703025/217202413-12588645-b86d-47b8-bb23-296dbc0b5233.png)
![image](https://user-images.githubusercontent.com/39703025/217202456-66959fd7-74a1-4cc4-95d7-026e9ddea897.png)

### 重现步骤

从脑图给用例切换模块之后需求ID没有了
![image](https://user-images.githubusercontent.com/39703025/217202629-117dfacd-85a8-49bf-9daa-6239fe45d75f.png)
这个用例挪到这个模块
![image](https://user-images.githubusercontent.com/39703025/217202689-03736480-3896-4a54-af80-d9314f263941.png)
挪完的需求id都没有  就这个没挪的还有

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，您的需求ID字段是在用例模版中添加的自定义字段吗？字段类型是什么？

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
