### ISSUE TITLE
[BUG]【项目设置-操作日志】输入“操作人”后，页面不会自动刷新，而是要点击"查询"按钮才能查询出结果

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21611]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

1.20.17-lts

### 使用外置数据库

否

### 问题描述

进入【项目设置-操作日志】页面，选择操作类型后，页面会自动刷新，将查询结果的日志显示在页面上，输入“操作人”后，页面不会自动刷新，而是要点击"查询"按钮才能查询出结果
![image](https://user-images.githubusercontent.com/104960608/217190345-2a892f8d-05ec-495a-8477-f2b413fc84ae.png)

### 重现步骤

1. 进入【项目设置-操作日志】页面，选择操作类型后，页面会自动刷新，将查询结果的日志显示在页面上
![image](https://user-images.githubusercontent.com/104960608/217190358-72fc4336-31e9-4269-9526-eb2123ccad2e.png)

2. 输入“操作人”后，页面不会自动刷新，而是要点击"查询"按钮才能查询出结果
![image](https://user-images.githubusercontent.com/104960608/217191177-f0b2d4ce-7619-48c2-9ce8-e4caee5ade14.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.20已修复该问题，待发布后可升级验证。
