### ISSUE TITLE
[BUG]缺陷管理，禅道集成，提交缺陷报错。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#21617]
### 联系方式

896705150@qq.com

### MeterSphere 版本

V2.2.0

### 使用外置数据库

否

### 问题描述

1、集成禅道，提交缺陷报错。禅道提交问题的必填字段，均已填写。
2、禅道连接测试通过、账号密码和权限没有问题、配置的是项目id（禅道中的产品id）。

### 重现步骤

1、集成禅道，提交缺陷报错。禅道提交问题的必填字段，均已填写。
2、禅道连接测试通过、账号密码和权限没有问题、配置的是项目id（禅道中的产品id）。

### 期待的正确结果

可以正常提交缺陷。

### 附加信息

![1](https://user-images.githubusercontent.com/71361375/217226848-dba2f844-654b-40f9-99c3-2594dd6b0ec0.png)

**Comment by xulinde** [comment]
未复现该问题，建议您升级到最新版本再试下～
