### ISSUE TITLE
[FEATURE]脑图用例评审、新建用例的时候，页面占比很小 只能通过鼠标拖拽比较麻烦，希望通过键盘上下左右键 小范围控制会更方便~~

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#21625]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

脑图评审、新建用例的时候，页面占比很小 只能通过鼠标拖拽比较麻烦，希望通过键盘上下左右键 小范围控制会更方便~~

![image](https://user-images.githubusercontent.com/114552960/217449996-ec177502-8f84-44db-9a56-35c80317ff0b.png)

### 请描述你建议的实现方案

脑图 可以用键盘上下左右键 小范围控制会更方便~~

**Comment by luty2018** [comment]
脑图这块的改造在2023年下半年进行，可以保持关注。
