### ISSUE TITLE
[BUG]UI测试本地模式调试或者未开启性能模式的错误截图发现列表的某列未被加载导致找不到元素

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#21627]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

UI测试本地模式调试或者未开启性能模式的错误截图发现列表的某列未被加载导致找不到元素

### 重现步骤

1、UI自动化
2、设置步骤之后，使用本地调试模式，不开启性能模式（为了能弹出chrome浏览器）
3、UI测试本地模式调试或者未开启性能模式的错误截图发现列表的某列未被加载导致找不到元素

### 相关日志输出

```shell
正确加载 可以联系我远程
```

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/217466213-0f9f0c51-7df5-429c-b111-0380e6fe13ca.png)
下图是正确页面
![image](https://user-images.githubusercontent.com/19423100/217466468-53c63f01-2262-4e25-9582-3742fa237402.png)
MS运行的错误页面：
![image](https://user-images.githubusercontent.com/19423100/217466873-e63635a1-4447-478f-9310-f1e7032fe5bc.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！远程沟通已复现该问题，后续版本修复。
