### ISSUE TITLE
[FEATURE]创建bug 希望能够自动获取用例里面的关键字，快速创建bug。提高bug提交和推送效率

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#21624]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

背景；因为目前提bug都是根据用例提交的，步骤和预期，bug等级，负责人等字段都是存在的，
希望在提交bug的时候自动读取 用例里面的关键字，这样减少编辑过程，快速提交bug

如图：关键字段和缺陷描述自动回填~

![image](https://user-images.githubusercontent.com/114552960/217449377-594ce32a-ffc1-454f-8af7-9ab507ad1af3.png)

### 请描述你建议的实现方案

创建bug 希望能够自动获取用例里面的关键字，快速创建bug。提高bug提交和推送效率

**Comment by Hyyfit** [comment]
我们在测试计划的优化内，有规划快速创建bug的功能，应该是可以覆盖您提的问题。
