### ISSUE TITLE
[FEATURE] 功能用例管理，关联缺陷字段希望能够展示jira 的id

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#21623]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

1、目前希望把jira和平台做对接，把用例和缺陷关联起来。目前只展示ms定义的缺陷id和jira上面的不一样，不方便把缺陷id和jira溯源协同管理比较麻烦。

2、

![image](https://user-images.githubusercontent.com/114552960/217448244-e72f6307-8bdb-44f1-9b57-21dd6019ea76.png)

### 请描述你建议的实现方案

功能用例管理，关联缺陷字段希望能够展示jira 的id。

**Comment by luty2018** [comment]
这个你在模板里面加一个自定义字段“jiraID"然后绑定API中的jiraID字段就可以获取到了。

**Comment by opopjasica** [comment]
是在哪个模板呢？用例模板吗
