### ISSUE TITLE
[BUG]ui测试web页面文本输入框必须使用  追加输入功能  方可找到对象进行输入

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#21628]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

ui测试web页面文本输入框必须使用  追加输入功能  方可找到对象进行输入

### 重现步骤

登录页面文本输入框正常
其他页面的文本输入框必须 使用追加输入

### 附加信息
![image](https://user-images.githubusercontent.com/19423100/217491322-31413c84-ec93-404e-b93a-3619e450450a.png)

可以联系我远程

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/217711312-53098393-1880-4aea-9cd2-5510f614d845.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已远程沟通复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v2.7已修复该问题。
