### ISSUE TITLE
[FEATURE] UI测试自定义脚本期望支持python, 用来解决登录验证码识别问题，目前仅js脚本不太适用

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#21622]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

UI测试自定义脚本期望支持python, 用来解决登录验证码识别问题，目前仅js脚本不太适用
python扩展插件多一些 比较好用，希望能采纳

### 请描述你建议的实现方案

UI测试自定义脚本期望支持python,

**Comment by Hyyfit** [comment]
您好，我们UI的整个场景是一个java脚本，如果在自定义脚步中支持python，技术上需要先实现场景脚本的拆分，所以暂时不考虑支持python。
