### ISSUE TITLE
[BUG] 测试计划中关联功能用例后查看报告统计，测试总数，通过率错误

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21630]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

测试计划中关联功能用例后查看报告统计，测试总数，通过率错误

### 重现步骤

1、有如下 十个用例
![image](https://user-images.githubusercontent.com/103925124/217484268-74e2aad2-42e9-4e3c-9dbb-28a934be697a.png)
2、测试计划一个一个关联用例后，关联到最后一个，查看测试总数，为1，之前都为0；刚导入时，都为“未执行”；
![image](https://user-images.githubusercontent.com/103925124/217484739-86773be5-bfc0-4201-8a11-d9f2ada678c8.png)
3、将下图两个执行结果改为通过时：
![image](https://user-images.githubusercontent.com/103925124/217485053-d3a68da8-5ad8-453e-8607-d308bf76210b.png)
![image](https://user-images.githubusercontent.com/103925124/217486020-4c9083e8-619f-4334-85ea-368b5531494d.png)

总结：找不到计算逻辑，没有规律，这些用例也无接口关联

出现在特定一些用例集合上；；

### 期待的正确结果

![image](https://user-images.githubusercontent.com/103925124/217484483-20cd2634-9254-4420-9af1-033aef685bc2.png)

**Comment by xulinde** [comment]
按你提供的步骤未复现该问题，方便录屏看下具体操作吗？

**Comment by Ycr123888** [comment]
请问有排查出问题嘛，需要数据库信息吗

**Comment by Ycr123888** [comment]
以下是测试计划中关联的用例，关联下面五条后，测试总数仍为0
![image](https://user-images.githubusercontent.com/103925124/219272124-a8dbb5df-80c0-4d38-ba55-e824cc937d2b.png)

INSERT INTO `metersphere`.`test_case` (`id`, `node_id`, `test_id`, `node_path`, `project_id`, `name`, `type`, `maintainer`, `priority`, `method`, `prerequisite`, `remark`, `steps`, `create_time`, `update_time`, `sort`, `num`, `other_test_name`, `review_status`, `tags`, `demand_id`, `demand_name`, `status`, `step_description`, `expected_result`, `custom_fields`, `step_model`, `custom_num`, `create_user`, `original_status`, `delete_time`, `delete_user_id`, `order`, `case_public`, `version_id`, `ref_id`, `latest`) VALUES ('c9f48780-733f-77c5-68bd-58dab2bd5a21', 'e7969ef9-7f2e-4828-a447-113768ff9fdc', NULL, '/test111', '82fd4e7d-4d10-41b5-a351-82d5745daa40', '6', 'case', 'kaibo', 'P0', 'manual', '', '', '[]', '1671170164370', '1671170199622', NULL, '100287', NULL, 'Prepare', '[]', '', NULL, NULL, '', '', NULL, 'STEP', '100287', 'kaibo', NULL, NULL, NULL, '1460019', NULL, 'a3ac7df8-6b57-443b-917a-d6ab9d26d277', 'c9f48780-733f-77c5-68bd-58dab2bd5a21', '1');
INSERT INTO `metersphere`.`test_case` (`id`, `node_id`, `test_id`, `node_path`, `project_id`, `name`, `type`, `maintainer`, `priority`, `method`, `prerequisite`, `remark`, `steps`, `create_time`, `update_time`, `sort`, `num`, `other_test_name`, `review_status`, `tags`, `demand_id`, `demand_name`, `status`, `step_description`, `expected_result`, `custom_fields`, `step_model`, `custom_num`, `create_user`, `original_status`, `delete_time`, `delete_user_id`, `order`, `case_public`, `version_id`, `ref_id`, `latest`) VALUES ('7553d493-16db-d053-ea99-adae6d4d337c', 'e7969ef9-7f2e-4828-a447-113768ff9fdc', NULL, '/test111', '82fd4e7d-4d10-41b5-a351-82d5745daa40', '5', 'case', 'kaibo', 'P0', 'manual', '', '', '[]', '1671170164520', '1671170199605', NULL, '100288', NULL, 'Prepare', '[]', '', NULL, NULL, '', '', NULL, 'STEP', '100288', 'kaibo', NULL, NULL, NULL, '1460039', NULL, 'a3ac7df8-6b57-443b-917a-d6ab9d26d277', '7553d493-16db-d053-ea99-adae6d4d337c', '1');
INSERT INTO `metersphere`.`test_case` (`id`, `node_id`, `test_id`, `node_path`, `project_id`, `name`, `type`, `maintainer`, `priority`, `method`, `prerequisite`, `remark`, `steps`, `create_time`, `update_time`, `sort`, `num`, `other_test_name`, `review_status`, `tags`, `demand_id`, `demand_name`, `status`, `step_description`, `expected_result`, `custom_fields`, `step_model`, `custom_num`, `create_user`, `original_status`, `delete_time`, `delete_user_id`, `order`, `case_public`, `version_id`, `ref_id`, `latest`) VALUES ('90e63577-f6cb-0bf7-c201-3a485e2f33ac', 'e7969ef9-7f2e-4828-a447-113768ff9fdc', NULL, '/test111', '82fd4e7d-4d10-41b5-a351-82d5745daa40', '4', 'case', 'kaibo', 'P0', 'manual', '', '', '[]', '1671170176554', '1676009014739', NULL, '100290', NULL, 'Prepare', '[]', '', NULL, NULL, '', '', NULL, 'STEP', '100290', 'kaibo', NULL, NULL, NULL, '1460078', NULL, 'a3ac7df8-6b57-443b-917a-d6ab9d26d277', '90e63577-f6cb-0bf7-c201-3a485e2f33ac', '1');
INSERT INTO `metersphere`.`test_case` (`id`, `node_id`, `test_id`, `node_path`, `project_id`, `name`, `type`, `maintainer`, `priority`, `method`, `prerequisite`, `remark`, `steps`, `create_time`, `update_time`, `sort`, `num`, `other_test_name`, `review_status`, `tags`, `demand_id`, `demand_name`, `status`, `step_description`, `expected_result`, `custom_fields`, `step_model`, `custom_num`, `create_user`, `original_status`, `delete_time`, `delete_user_id`, `order`, `case_public`, `version_id`, `ref_id`, `latest`) VALUES ('7b482cdf-4d31-7fd3-79b7-0fe6ac05e687', 'e7969ef9-7f2e-4828-a447-113768ff9fdc', NULL, '/test111', '82fd4e7d-4d10-41b5-a351-82d5745daa40', '3', 'functional', 'kaibo', 'P0', 'manual', '', '', '[]', '1671170176721', '1671170176721', NULL, '100292', NULL, 'Prepare', '[]', NULL, NULL, NULL, '', '', NULL, 'STEP', '100292', 'kaibo', NULL, NULL, NULL, '1460156', NULL, 'a3ac7df8-6b57-443b-917a-d6ab9d26d277', '7b482cdf-4d31-7fd3-79b7-0fe6ac05e687', '1');
INSERT INTO `metersphere`.`test_case` (`id`, `node_id`, `test_id`, `node_path`, `project_id`, `name`, `type`, `maintainer`, `priority`, `method`, `prerequisite`, `remark`, `steps`, `create_time`, `update_time`, `sort`, `num`, `other_test_name`, `review_status`, `tags`, `demand_id`, `demand_name`, `status`, `step_description`, `expected_result`, `custom_fields`, `step_model`, `custom_num`, `create_user`, `original_status`, `delete_time`, `delete_user_id`, `order`, `case_public`, `version_id`, `ref_id`, `latest`) VALUES ('b7c3ad05-8925-1e7b-83df-7071305c03a8', 'e7969ef9-7f2e-4828-a447-113768ff9fdc', NULL, '/test111', '82fd4e7d-4d10-41b5-a351-82d5745daa40', '2', 'case', 'kaibo', 'P0', 'manual', '', '', '[]', '1671170176700', '1671170199541', NULL, '100291', NULL, 'Prepare', '[]', '', NULL, NULL, '', '', NULL, 'STEP', '100291', 'kaibo', NULL, NULL, NULL, '1460937', NULL, 'a3ac7df8-6b57-443b-917a-d6ab9d26d277', 'b7c3ad05-8925-1e7b-83df-7071305c03a8', '1');

**Comment by Ycr123888** [comment]
12点54重新关联的，info.log日志里只要一条日志，无其他相关日志了。。。
![image](https://user-images.githubusercontent.com/103925124/219272734-09ca902c-d6a2-47db-b1c6-d699bfab00b6.png)
