### ISSUE TITLE
[BUG] 项目关联devops三方平台，批量关联需求后，tfs平台的需求未全部关联上所选用例

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#21633]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.6

### 使用外置数据库

否

### 问题描述

项目关联devops三方平台，批量关联需求后，tfs平台的需求未全部关联上所选用例

### 重现步骤

1、项目关联devops三方平台
2、批量关联需求到A
3、tfs平台查看需求A下的用例，无刚才选中用例

原因：未批量做取消关联和重新关联
需补充代码见下图：
![image](https://user-images.githubusercontent.com/103925124/217490984-2ab080da-62bb-47e0-b00f-b99d33b7ceda.png)

### 附加信息

try {
            for (TestCase tc : testCaseList) {
                EditTestCaseRequest editTestCaseRequest = new EditTestCaseRequest();
                editTestCaseRequest.setId(tc.getId());
                editTestCaseRequest.setDemandId(request.getDemandId());
                editTestCaseRequest.setProjectId(tc.getProjectId());
                editTestCaseRequest.setName(tc.getName());

                // 同步缺陷与需求的关联关系
                updateThirdPartyIssuesLink(editTestCaseRequest);
                // 同步用例与需求的关联关系
                addDemandHyperLink(editTestCaseRequest, "edit");
                tc.setDemandId(demandId);
                tc.setDemandName(demandName);
                mapper.updateByPrimaryKey(tc);
            }
        } catch (Exception e) {
            LogUtil.error(e);
        }

**Comment by Ycr123888** [comment]
这个同样希望也规划到 2.7.0

**Comment by xulinde** [comment]
v2.7.0已修复～

**Comment by fit2cloud-yaochunrong** [comment]
@youliyuan-fit2cloud 使用 v2.10.3-lts 版本此问题又复现，希望尽快修复下

**Comment by 13290445582** [comment]
v2.10.5已修复
