### ISSUE TITLE
[BUG]A场景中引用方式导入B场景，如B场景内容发送修改，批量执行或测试计划执行A场景时，测试报告中的B场景还是老内容

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#21635]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.5.1

### 使用外置数据库

否

### 问题描述

A场景中引用方式导入B场景，如B场景内容发送修改，批量执行或测试计划执行A场景时，测试报告中的B场景还是老内容

### 重现步骤

1、创建场景B，引用的方式导入case，保存场景B并关闭
2、创建场景A，引用的方式导入场景B，保存场景A，点击场景B的ID号打开场景B编辑页面
3、编辑场景B：修改场景名，引用的方式再导入一个case，保存场景B并关闭
4、回到场景A编辑页面，刷新，能看到最新的场景B，此时调试场景A，结果也正常，保存场景A并关闭
5、接口自动化tab下，直接点击场景列表里A场景的执行按钮执行，测试报告中内容正常
6、接口自动化tab下，批量执行或添加到测试计划执行A场景，测试报告里显示的还是原B场景的内容，不是修改后的

### 附加信息

![image](https://user-images.githubusercontent.com/86464217/217497211-676a0790-b082-4cd5-a2fc-4c35ae92b33e.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是否可以把操作步骤和有疑问的地方录制一个视频上传一下呢？

**Comment by minnn0306** [comment]
之前的操作步骤说的有问题，麻烦按这个步骤再试试，能稳定复现

1、创建场景B，引用的方式导入case，保存场景B并关闭
2、创建场景A，引用的方式导入场景B，保存场景A并关闭
3、编辑场景B：修改场景名，引用的方式再导入一个case，保存场景B并关闭
4、接口自动化tab下，直接点击场景列表里A场景的执行按钮执行，测试报告中内容正常
5、接口自动化tab下，批量执行或添加到测试计划执行A场景，测试报告里显示的还是原B场景的内容，不是修改后的

**因为已经是引用的方式tian添加的场景，讲道理不应该还需要重新去保存A场景才能让测试报告正常显示，否则这样失去引用的意义**


https://user-images.githubusercontent.com/86464217/217989496-e366fbbd-a972-4d17-bfff-8d46fcbcb132.mp4

**Comment by zyyfit** [comment]
复现了，感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本修复后验证
