### ISSUE TITLE
[FEATURE]关于使用MeterSphere压测和受用使用Jmeter命令行方式压测结果差距较大的建议

### ISSUE THREAD

**Issue by zxtester** [metersphere/metersphere#21632]
### MeterSphere 版本

V2.6.0-068f4f4a

### 联系方式

328598327@qq.com

### 请描述您的需求或者改进建议

MeterSphere压测和手动使用Jmeter命令行方式压测出的结果差距很大，建议修改MS对节点数据的统计方式，降低结果差距。

### 请描述你建议的实现方案

采用容器内部署influxdb，然后在脚本中添加jmeter-influxdb监听器，然后界面上展示时用和Grafana的仪表盘一样的方式展示。参考方式：https://mp.weixin.qq.com/s?__biz=MzI0NzEyMDE0Ng==&mid=2247484410&idx=1&sn=c032b2e169960ce2e7841fed6c985736&chksm=e9b5ab87dec22291172c65d244c2fdf0b2cf174d6550722ba63905f4b2201bbd1cc4be00a322&scene=27&key=5c01fc8b1ae06b95d152c031b7a0c8754c6325c3769bc399ca0ddfaa4e034488417e1c79313a7631dbd4de9ed3b4b580252a433a07a6475231e7455c891ec77bf74c85892c2c1029ef21a36b937f367ed21343317041288b7956cef8de951e9f82ab0bcfa8ab62386681fd197f288da25c8c05951dd75ccc34c3832e83f016db&ascene=7&uin=MjMwNTI5MTM0MA%3D%3D&devicetype=Windows+10+x64&version=6308011a&lang=zh_CN&session_us=gh_26b2c85cb504&exportkey=n_ChQIAhIQ6cqQJMKXX2rtlH%2F5PnpuKRLqAQIE97dBBAEAAAAAALKxDFY8nZcAAAAOpnltbLcz9gKNyK89dVj0d9TTY8ZBK0sXZKIW%2FQwajwS2jn3lZzFqeNfhM81v9ihxEOI1%2FIOJS51ReKhTeipN1WfH5gUWgn9z72uymutbSpB7AYz6Orzi5CDS06S%2FaehkpO3v46gIBxPRV3lfTyL92wNOU5h90bjEdcFh7UUIZLWRTGaAnRl%2FlZ8TsBjzC%2BuFvKiFpuuEzcsjBRfza8tn%2BV%2ByKw4xxt%2FFCxtIHBKYErukS3rLHkVp%2BzJl9MgWUQG3XRq4ntcailj10go8kGyRjLhJpQ%3D%3D&acctmode=0&pass_ticket=bRK7fL41qvS8ADtEJXr6s4k%2Fjo96BafczAIqAkYmuu%2F%2FW7RDNX9NTgtg3P42VZcsb3qxwwNLnyaYLwVNrW0SBw%3D%3D&wx_header=1&fontgear=2

**Comment by liuruibin** [comment]
JMeter中采用BackendListener的方案进行结果采集，在高tps的场景下都会很快遇瓶颈。JMeter发压端的缓存队列将很快就被占满进而无法开启新的请求，如果您需要测试高tps的场景请使用企业版并在资源池配置中关闭后置监听器选项。
