### ISSUE TITLE
[BUG]文件上传接口，环境配置中添加Content-Type后，接口case再添加Content-Type执行失败

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#21637]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

1、在环境配置中设置了Content-Type=application/json
2、执行文件上传接口case的时候再手动设置请求头Content-Type=multipart/form-data时，接口执行失败
3、如果去掉环境配置里面的Content-Type的话能执行，但是就需要所有接口一个一个进行添加Content-Type

### 重现步骤

1、在环境配置中设置了Content-Type=application/json
2、执行文件上传接口case的时候再手动设置请求头Content-Type=multipart/form-data时，接口执行失败

### 期待的正确结果

期望环境配置里面设置了Content-Type，文件上传接口也能通过手动配置Content-Type正常执行

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/217515840-7b69c7f6-f4dc-4062-b0b8-0200609409e9.png)

**Comment by zyyfit** [comment]
请求头和变量不同，目前的逻辑是：
环境里的请求头优先级是高于场景请求头的，因为环境需要匹配，匹配到不同的环境会带上对应环境的请求头，如果场景请求头优先的话，环境匹配后的请求头就无法生效了

**Comment by zyyfit** [comment]
罗老师看看这个需不需要做个优化 @luty2018

**Comment by zyyfit** [comment]
您好，接口上传文件的话，不需要在接口中添加请求头，在form-data请求体中填写参数类型就可以了，类型也是会自动填充的
![image](https://user-images.githubusercontent.com/73461316/217712050-d8b0d9eb-6b53-4e0a-8228-d2a48c2e0af7.png)

**Comment by heyuehua** [comment]
> 您好，接口上传文件的话，不需要在接口中添加请求头，在form-data请求体中填写参数类型就可以了，类型也是会自动填充的 ![image](https://user-images.githubusercontent.com/73461316/217712050-d8b0d9eb-6b53-4e0a-8228-d2a48c2e0af7.png)

这样操作的问题就是，一但我在场景里面引用了环境配置里面的content-type，那我的文件上传的接口就完全没法用了，不然就要一个一个接口的设置content-type

**Comment by zyyfit** [comment]
好的，这个bug在1.20版本里确实存在，后续版本修复

**Comment by zyyfit** [comment]
您好，这个问题是由于 1.20的Jmeter的版本是5.4.3，2.6的Jmeter的版本是5.5  执行版本不同导致的执行结果不同，建议升级到 2.6.1，或者取消一个content-type
