### ISSUE TITLE
[BUG]UI测试弹出的添加页面默认值加载不出来

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#21648]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

UI测试弹出的添加页面默认值加载不出来（某个字段，其他默认值字段可以）

### 重现步骤

1、UI测试，添加一个对象添加页面，有个字段是有默认值的，
2、使用本都调式的时候发现那个默认值没有被加载出来（这个字段有个特点，弹出的页面是有竖向滚动条的，他需要滚动到下面才能显示这个字段）

### 附加信息

出问题的页面
![image](https://user-images.githubusercontent.com/19423100/217742245-5ca8006a-5eb5-48fc-ac8f-411206c3bf83.png)

原始页面：

![image](https://user-images.githubusercontent.com/19423100/217743499-d5547652-23fd-42aa-b6bd-367fe950e33b.png)

可以在线联系我

**Comment by zrfit** [comment]
经远程沟通，用户网站首次执行未收到默认数据，刷新页面则可收到默认数据-下拉框则展示数据，需要排查下用户网站自身每次进入页面是否能收到默认数据请求。

**Comment by legend818** [comment]
可关闭
