### ISSUE TITLE
[FEATURE] 详细的测试用例建议增加链接，需要分享链接

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21645]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/22338833/217730887-54228da5-4c12-42d0-91aa-7bac2b1148cc.png)
建议单个详细的测试用例增加链接跳转，需要对外分享测试链接！

### 请描述你建议的实现方案

建议为单个用例增加链接，便于分享至其他平台！

**Comment by luty2018** [comment]
这个在v2.7版本支持。

**Comment by chyhant** [comment]
请问这个功能已经增加了吗，目前用例名称分享后还是没有链接哦，谢谢!

**Comment by chyhant** [comment]
@Hyyfit 主要用于将用例分享至其他平台，能通过链接跳转回来metersphere，谢谢！
