### ISSUE TITLE
[FEATURE]优化建议：系统参数设置，普罗米修斯的访问地址这样写不够直观，实际访问是ip:9090/targets ，建议加个跳转访问监控详情的按钮或者是超链

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#21656]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/114552960/217770597-0c65495b-1b97-4ec4-835c-3f8f9202c616.png)
优化建议：系统参数设置，普罗米修斯的访问地址这样写不够直观，实际访问是ip:9090/targets ，建议加个跳转访问监控详情的按钮或者是超链

刚开始用平台 不熟悉这个找了好久才找到的使用成本挺大的，如果能直接跳转会更友好！
希望产品大大能够采纳 💕

**Comment by opopjasica** [comment]
![image](https://user-images.githubusercontent.com/114552960/217771549-e7c390f5-c91c-4671-8805-c5913d109abe.png)
访问这个监控详情

**Comment by luty2018** [comment]
感谢建议，我们优化下。
