### ISSUE TITLE
[BUG]【系统设置-用户组与权限】工作空间管理员/工作空间成员的权限分配后是不可更改的。要删除、得先点“添加用户组”才出现删除按钮，才能删除

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21655]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

【系统设置-用户组与权限】工作空间管理员/工作空间成员的权限分配后是不可更改的。要删除、得先点“添加用户组”才出现删除按钮，才能删除
![efd5e9a0-730c-404c-98c4-41527a37c68d](https://user-images.githubusercontent.com/104960608/217769102-ed4240fc-d968-4321-b13e-8bf640c45a0b.png)

![8ba0c6ce-3c2d-4a95-839e-b3de3730a7d8](https://user-images.githubusercontent.com/104960608/217769101-0dcf65a6-52e8-4049-91d0-d5508cb57e63.png)

### 重现步骤

【系统设置-用户组与权限】工作空间管理员/工作空间成员的权限分配后是不可更改的。要删除、得先点“添加用户组”才出现删除按钮，才能删除
![efd5e9a0-730c-404c-98c4-41527a37c68d](https://user-images.githubusercontent.com/104960608/217769102-ed4240fc-d968-4321-b13e-8bf640c45a0b.png)

![8ba0c6ce-3c2d-4a95-839e-b3de3730a7d8](https://user-images.githubusercontent.com/104960608/217769101-0dcf65a6-52e8-4049-91d0-d5508cb57e63.png)

**Comment by zyyfit** [comment]
![image](https://user-images.githubusercontent.com/73461316/217795616-34371cde-e60a-459d-9607-2ac2859a71f7.png)

**Comment by xulinde** [comment]
v1.20.20-lts已优化
