### ISSUE TITLE
[BUG]接口调试保存界面，经常报404

### ISSUE THREAD

**Issue by nunter** [metersphere/metersphere#21657]
### 联系方式

lx.vs@qq.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

接口调试保存界面，经常报404 
![image](https://user-images.githubusercontent.com/10915931/217772189-71e55622-9652-4fcf-8e15-bd0a9863c09f.png)
![image](https://user-images.githubusercontent.com/10915931/217772232-8ff25bc9-7ab4-4268-8b55-0a7e1ed8e075.png)

### 重现步骤

![企业微信截图_16759332989996](https://user-images.githubusercontent.com/10915931/217772385-afb55f2e-a8a4-45ab-869e-cc84bb78d666.png)
![企业微信截图_16759332989996](https://user-images.githubusercontent.com/10915931/217772410-2c450d18-d9ed-4fbe-867a-39483179a705.png)

**Comment by nunter** [comment]
gateway 报出的错误日志

**Comment by zyyfit** [comment]
您好，请参考一下这个问题 https://github.com/metersphere/metersphere/issues/19738

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
