### ISSUE TITLE
[BUG]环境配置-数据库配置，数据库驱动不能为空的提示信息一直在显示

### ISSUE THREAD

**Issue by TangYoulong** [metersphere/metersphere#21653]
### 联系方式

dream_believer@163.com

### MeterSphere 版本

v2.2.1-68ccaa2a

### 使用外置数据库

否

### 问题描述

选择了数据库连接驱动后，未填红框未消失
![image](https://user-images.githubusercontent.com/47670867/217754053-d247a4fe-2cf3-43c6-b73f-f10ce143594d.png)

### 重现步骤

操作步骤
1、在配置环境，数据库配置是，先点击确定，必填项弹出未填红框
2、选择数据库连接驱动，但未填红框仍未消失
![image](https://user-images.githubusercontent.com/47670867/217754053-d247a4fe-2cf3-43c6-b73f-f10ce143594d.png)

### 期待的正确结果

选择数据库连接驱动后，未填红框应当消失

**Comment by zyyfit** [comment]
您好，最新版2.6.1版本没有复现这个问题，请升级后试试

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
