### ISSUE TITLE
[BUG]后置脚本无法正常使用js文件

### ISSUE THREAD

**Issue by CarpW** [metersphere/metersphere#21654]
### 联系方式

390693949@qq.com

### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

接口后置脚本，脚本中需要load相关的js文件
将js文件放置在服务器上，位置 /opt/metersphere/data
运行脚本提示 ReferenceError: "load" is not defined. in eval at line number 0 at column number 0
无法load需要的js文件
该接口和脚本在jmeter上可以正常使用。
![image](https://user-images.githubusercontent.com/41277506/217756056-aa0ebaac-a5b8-48da-a482-b5171a2f8bd0.png)
![image](https://user-images.githubusercontent.com/41277506/217756133-8616caeb-e064-4c2a-a159-a102e356de33.png)

### 重现步骤

1.接口自动化，新增场景
2.上传js文件至服务器
3.配置后置脚本
4.运行接口，报错

**Comment by zyyfit** [comment]
您好，请在load脚本前面加上这两行
g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;

**Comment by CarpW** [comment]
在load脚本前加上这两句话是可以正常load文件的，但是load文件后依然会报错。
因为这个脚本在jmeter上，只安装了JDK，是可以正常运行，，不太清楚是否还缺少什么环境才能在Metersphere才能正常运行
![image](https://user-images.githubusercontent.com/41277506/217995808-995eb126-3165-42e0-b35c-28076f55fb50.png)

**Comment by zyyfit** [comment]
您好，看报错是加载成功了但是缺少函数，由于第三方js文件范围太大，支持起来比较困难，请自己研究一下吧

**Comment by CarpW** [comment]
这个应该跟函数没有关系，我们在jmeter上运行用脚本语言js和javascript都可以正常运行
我们现在jdk版本是1.8.0，可能比较旧，能否问一下metersphere的jdk我们可以更换嘛？

**Comment by zyyfit** [comment]
1.20版本是使用的jdk8，应该没有问题的

**Comment by CarpW** [comment]
感谢，查找了一下你们的知识库，找到了相关的解决方案。

**Comment by zhangzhaox** [comment]
@CarpW  啥知识库啊，共享一下连接一起学习下，感谢

**Comment by CarpW** [comment]
> 

https://kb.fit2cloud.com/?p=118

**Comment by CarpW** [comment]
https://kb.fit2cloud.com/?p=118

> @CarpW 啥知识库啊，共享一下连接一起学习下，感谢
