### ISSUE TITLE
[BUG] api参数选择某环境变量界面点击浏览器返回键，地址有变化，未返回到场景详情页面

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21669]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

api参数选择某环境变量界面点击浏览器返回键，地址有变化，页面未进行返回

### 重现步骤

点击前，地址栏还在接口场景
![image](https://user-images.githubusercontent.com/103925124/217986449-8644d73b-1cf0-4eb1-b174-b479c0af7a2f.png)
点击后，地址栏回到了接口首页，页面未返回到场景详情页面
![image](https://user-images.githubusercontent.com/103925124/217987215-294909f6-e4dc-4c47-84b4-51f3e1a39249.png)

### 期待的正确结果

api参数选择某环境变量界面点击浏览器返回键，地址无变化，返回到场景列表页面

正常用户行为，且符合预期，重要客户提出

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这里回退是浏览器默认走路由跳转的，无法直接处理

**Comment by fit2-zhao** [comment]
弹出页面有关闭操作，不会再去监控浏览器的回退事件。
