### ISSUE TITLE
[BUG]  api参数选择某环境变量选中操作不流畅，选中保存无效

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21668]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

api参数选择某环境变量选中操作不流畅，选中保存无效

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/217985043-937ce4fd-d710-414d-b21b-e4a6116b7521.png)
![image](https://user-images.githubusercontent.com/103925124/217985590-db7d2e0c-037f-4c4e-82a8-497e766af9d1.png)
①选中，文本框未回显，导致保存后仍然为空
![image](https://user-images.githubusercontent.com/103925124/217985666-d47b950c-f585-4d15-898e-5a5423c39481.png)
②有全选操作，亦无效，且对多个场景变量同时使用的场景未知，希望先评论区解答下
③手动鼠标选中变量名后，文本框有引用值
![image](https://user-images.githubusercontent.com/103925124/217986058-fc6c8d4e-6862-4fee-beb6-2c273f2ca024.png)

**Comment by zyyfit** [comment]
多选框应该是没有作用的，后续版本会去掉，要选择的话就使用 方法3⃣️手动选中变量 引用即可

**Comment by zyyfit** [comment]
2.7.0和 1.20.20版本去掉了前面的多选框，请等待版本发布后验证
