### ISSUE TITLE
[BUG]测试计划间串行执行，测试计划未执行完时点击报告报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21679]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

测试计划间串行执行，例如：三个测试计划串行执行，在第一个测试计划未执行结束时，第二个和第三个测试计划都是running状态，点击第二个或者第三个测试计划报告详情报错，即第一个测试计划未执行完时点击后面的测试报告报错

### 重现步骤

1.创建测试计划，测试计划串行执行，为了方便验证问题，可以在第一个测试计划中添加等待控制器
![1](https://user-images.githubusercontent.com/103627487/218017304-8c079aae-e0ff-43d3-9d35-57998818282e.png)
2.测试计划开始执行后，前面测试计划还未执行结束，点击第三个测试报告详情
![2](https://user-images.githubusercontent.com/103627487/218017741-b1164494-ffbc-48dc-88c8-d7abe624f11c.png)
![4](https://user-images.githubusercontent.com/103627487/218018128-03f69d45-b426-4827-8fa5-2bb01706f7c1.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
v1.20.20已修复该问题，待发布后可升级验证。
