### ISSUE TITLE
[BUG] 使用默认系统配额，在配置列表详情页面进行开关操作，未回显成功，回到列表后，闪现到正确配额

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21672]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

 使用默认系统配额，在配置列表详情页面进行开关操作，未回显成功，回到列表后，闪现到正确配额

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/217990352-98ce4a48-5249-45b6-849b-4ac79b7d7248.png)
点击使用了默认配额的某空间详情页面
![image](https://user-images.githubusercontent.com/103925124/217990643-9f3e981a-7ec6-4f26-9b08-23cc69a7e27e.png)
点击关闭后，都变为0，是正常的
![image](https://user-images.githubusercontent.com/103925124/217990731-7b591247-d88a-4ce0-8308-6d1a021e7e44.png)
点击开后，还是0，是错误的
![image](https://user-images.githubusercontent.com/103925124/217990772-5bafe5ad-aa51-4ac3-836a-6125354da9de.png)
点击保存，列表数据由无限制闪变回默认配额
![image](https://user-images.githubusercontent.com/103925124/217990808-ccaaadcd-80a5-4b3c-8eff-ca6a409c9483.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.20 和 2.7.0 版本已修复，请等待版本发布后验证
