### ISSUE TITLE
[FEATURE]希望idea插件接口导入能够把响应体导入进来

### ISSUE THREAD

**Issue by RayPengzhihui** [metersphere/metersphere#21688]
### MeterSphere 版本

最新版本的idea插件

### 联系方式

微信 -交流群3 -啊哈- 695404476@qq.com

### 请描述您的需求或者改进建议

每次使用idea插件大批量从idea导入接口到meterspher平台
导入后发现没有响应体
希望后面响应体的导入也支持
因为测试得看接口响应体、前端得看接口响应体

### 请描述你建议的实现方案

EasyApi 这个idea插件支持响应体导入到yapi中
我建议你们可以cv他们的代码

**Comment by luty2018** [comment]
你是用的什么版本， 我们是支持导响应体的

**Comment by RayPengzhihui** [comment]
我升级新版本后发现响应体确实是可以导入进来的。
还有一个问题就是，响应体，请求体java的domian如何注释。

**Comment by zhangdahai112** [comment]
使用 javadoc 在属性上面注释试试
