### ISSUE TITLE
[BUG]导入swagger接口报错

### ISSUE THREAD

**Issue by mushisan3333** [metersphere/metersphere#21689]
### MeterSphere 版本

v2.5.1-8e5455a0

### 使用外置数据库

否

### 问题描述

导入swagger接口报错
![image](https://user-images.githubusercontent.com/108405361/218032918-b73de19d-e7c4-4306-bc0c-d3a1e401778b.png)

### 重现步骤

导入接口，选择swagger，文件导入和url导入都报错

**Comment by zyyfit** [comment]
1、请检查一下swagger文件格式是否正确，可以用这个官方网址检查
2、如果没有问题的话，请上传一下swagger文件，我们排查一下问题

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
