### ISSUE TITLE
[FEATURE]  导入功能用例，如下图，点击继续上传，建议提示用户“继续上传会忽略异常用例，继续上传正常的用例，如果没有正常用例，就是没有”

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21696]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

chunrong.yao@fit2cloud.com

### 请描述您的需求或者改进建议

只有一条数据，提示下图，点击继续上传，提示导入成功了，实际么有
**_用户会以为，继续上传，会忽略错误，仍然导入，可导入成功_**
![8724fab55484c78b43d793af5ac222f](https://user-images.githubusercontent.com/103925124/218033770-b59045e0-3ccf-43b6-906a-af2a9db4fad8.png)

### 请描述你建议的实现方案

建议提示用户“继续上传会忽略异常用例，继续上传正常的用例，如果没有正常用例，就是没有”

**Comment by luty2018** [comment]
可以在操作文档里添加“继续上传”的使用说明

**Comment by Ycr123888** [comment]
为什么要加在文档里呢，这种用户友好提示问题，需要用户系统文档参考着看。。。。而且文档中别得使用教程信息也很庞大了，这种小用法入口也很深了

**Comment by luty2018** [comment]
因为“继续上传”按钮是出现在错误数据后的，已经很明显是忽略错误继续上传的意思了，至于你说的只有一条用例数据，已经提示这条数据有问题了，为什么用户还会觉得能上传成功呢？
