### ISSUE TITLE
[BUG]dubbo测试，控制台一直报错

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#21697]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

2.6

### 使用外置数据库

是

### 问题描述

dubbo测试，使用了zk注册中心，控制台一直报错
![image](https://user-images.githubusercontent.com/58592452/218043762-a0c8a928-9e45-440f-a2f5-59c1f0006ecd.png)

### 重现步骤

dubbo测试，使用了zk注册中心，控制台一直报错

**Comment by zyyfit** [comment]
您好，使用zookeeper的dubbo环境没有复现这个问题，请检查一下环境信息，或者详细描述一下复现步骤
![image](https://user-images.githubusercontent.com/73461316/219258309-90c2a215-bfd5-4552-a1e7-c0361690cdc4.png)

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
