### ISSUE TITLE
[FEATURE]用例数量较大时，测试跟踪-功能用例 页面左侧的用例菜单加载时间很久

### ISSUE THREAD

**Issue by ryan255** [metersphere/metersphere#21698]
### MeterSphere 版本

v1.20.17-lts

### 联系方式

ryan255@163.com

### 请描述您的需求或者改进建议

![微信图片_20230210165751](https://user-images.githubusercontent.com/16772336/218048092-f5423c68-7a9c-4c99-b00b-5d033117da7c.png)

用例数量10000多，子模块总量大约100以上，一般有三到四层。 此时接口响应时间去到5秒以上

![image](https://user-images.githubusercontent.com/16772336/218048734-dbb20164-ac27-4a57-b735-ea2b259facf6.png)

### 请描述你建议的实现方案

建议优化这里的代码

**Comment by luty2018** [comment]
感谢建议， 左侧模块树这里已纳入性能优化
