### ISSUE TITLE
[FEATURE] 用例评审，最后一条用例页面点击下一条，未提示[已经是最后一条了]

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21699]
### MeterSphere 版本

v1.20.19-lts

### 请描述您的需求或者改进建议

用例评审，最后一条用例页面点击下一条，未提示[**_已经是最后一条了_**]，之前的某旧版本就是提示的
![image](https://user-images.githubusercontent.com/103925124/218050759-feb3d119-9837-4cf4-ab24-22bd5dae490d.png)

**Comment by luty2018** [comment]
在2.7新版交互已覆盖
