### ISSUE TITLE
[QUESTION]资源池配置与kafka数据处理相关代码是否开源？？

### ISSUE THREAD

**Issue by donfaquir** [metersphere/metersphere#217]
在代码里，没有找到资源池节点中处理逻辑的代码和kafka数据处理的代码，则两块相关的代码在哪里？？

**Comment by wangzhen-fit2cloud** [comment]
在我们这个组织账号的其他仓库中，请参考文档的组件说明部分，有链接到对应组件的仓库
https://metersphere.io/docs/system_arch/
