### ISSUE TITLE
[BUG]引用jar在接口场景执行正常，到性能场景报错“javax.script.ScriptException: Sourced file: inline evaluation of”

### ISSUE THREAD

**Issue by pool2023** [metersphere/metersphere#21705]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

引用jar在接口场景执行正常，到性能场景报错“javax.script.ScriptException: Sourced file: inline evaluation of”

### 重现步骤

引用jar在接口场景执行正常，到性能场景报错“javax.script.ScriptException: Sourced file: inline evaluation of……undefined variable or class name”

### 期待的正确结果

接口自动化场景正常执行，性能场景也正常执行，正常引用jar

### 附加信息

<img width="1233" alt="1676025723185" src="https://user-images.githubusercontent.com/125026768/218072229-c9958763-75b2-4606-a23f-9d986aa1d2dd.png">

**Comment by zyyfit** [comment]
您好，请参考一下这个问题看看，是否是同样的问题 https://github.com/metersphere/metersphere/issues/21121

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
