### ISSUE TITLE
[BUG]  测试跟踪-功能用例脑图模式下，将用例移动到收起状态的模块下，且该模块已有用例节点，移动成功后，该模块展开展示不对

### ISSUE THREAD

**Issue by wpiami** [metersphere/metersphere#21702]
### MeterSphere 版本

V2.3

### 使用外置数据库

否

### 问题描述

1. 用例1归属于模块1，模块2与模块1是同级，且模块2下有已关联用例
2. 拖动用例1到模块2，且模块2是收起状态
3. 拖动成功后，模块2下的其他用例未展示出现，只显示一条线
4. 模块2显示的-符号，点击模块2的-号，展示了模块2下的所有已关联用例

### 重现步骤

重复问题描述中的步骤

### 期待的正确结果

用例移动到收起的，并且已有用例子节点的模块上时，该模块正常展开展示子节点

**Comment by wpiami** [comment]
![image](https://user-images.githubusercontent.com/19588624/218070009-d363fbfa-af40-4e2b-8d0d-5c19f49a11bf.png)
移动后的展开状态

**Comment by wpiami** [comment]
![image](https://user-images.githubusercontent.com/19588624/218070488-8d5b00a0-ab7d-42d0-9f4d-201a3033b7b0.png)

**Comment by xulinde** [comment]
使用v2.6.1版本未复现该问题，建议您升级至最新版本～
<img width="698" alt="image" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">

**Comment by wpiami** [comment]
> 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">

可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，

**Comment by xulinde** [comment]
> > 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">
> 
> 可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，

您好，应该是2.3版本的bug，已经解决过了。所以建议下您升级版本

**Comment by wpiami** [comment]
> > > 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">
> > 
> > 
> > 可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，
> 
> 您好，应该是2.3版本的bug，已经解决过了。所以建议下您升级版本

麻烦能不能提供一下修改这个问题的git提交记录，我们项目现在不太能直接升级2.6版本

**Comment by xulinde** [comment]
> > > > 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">
> > > 
> > > 
> > > 可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，
> > 
> > 
> > 您好，应该是2.3版本的bug，已经解决过了。所以建议下您升级版本
> 
> 麻烦能不能提供一下修改这个问题的git提交记录，我们项目现在不太能直接升级2.6版本
不能升级的话，建议您选择列表模式，将用例批量移动到指定目录

**Comment by wpiami** [comment]
> 



> > > > > 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">
> > > > 
> > > > 
> > > > 可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，
> > > 
> > > 
> > > 您好，应该是2.3版本的bug，已经解决过了。所以建议下您升级版本
> > 
> > 
> > 麻烦能不能提供一下修改这个问题的git提交记录，我们项目现在不太能直接升级2.6版本
> > 不能升级的话，建议您选择列表模式，将用例批量移动到指定目录




用脑图的场景比较多，遇到这种情况，不能每次都去列表上操作吧

**Comment by xulinde** [comment]
> > 
> 
> > > > > > 使用v2.6.1版本未复现该问题，建议您升级至最新版本～ <img alt="image" width="698" src="https://user-images.githubusercontent.com/64065190/218439690-2999de23-e45a-4df4-a134-21fdd6aee34a.png">
> > > > > 
> > > > > 
> > > > > 可以用2.3版本测试吗？按上边的步骤2.3版本是必现的，
> > > > 
> > > > 
> > > > 您好，应该是2.3版本的bug，已经解决过了。所以建议下您升级版本
> > > 
> > > 
> > > 麻烦能不能提供一下修改这个问题的git提交记录，我们项目现在不太能直接升级2.6版本
> > > 不能升级的话，建议您选择列表模式，将用例批量移动到指定目录
> 
> 用脑图的场景比较多，遇到这种情况，不能每次都去列表上操作吧

您在我们交流群吗，不在的话扫码进下群吧，这样交流起来更方便些～
