### ISSUE TITLE
[BUG]从A项目把接口定义和接口自动化的数据全部导出，再导入到B项目中，（为了实现项目复制）接口定义的数据ID已经变了，但是场景中仍然使用的是A项目的场景。导致新项目无法正常使用

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#21710]
### 联系方式

18259175411

### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

目的：为了适配不同的数据库，所以一个项目需要完完全全的复制到另一个项目中，所以从旧项目中把接口定义的数据和接口自动化的场景用例全部导出，再切换到新项目中把数据进行导入，以实现项目的复制
期望：从A项目的数据导入到B项目中，可以在B项目中独立运行，形成两套完全独立的系统进行维护

### 重现步骤

1、创建A项目并在项目中建立API和CASE，并在场景用例中进行引用
2、将A项目中的接口定义和接口自动化场景进行导出，导出格式为metersphere
3、创建B项目，并在接口定义中和接口自动化中将A项目导出的数据进行导入
4、这时可以看到接口定义中，id已经和A项目的id不一样。但是在接口自动化页面中，可以看到还是引用的A项目的数据，界面显示如：A->登录
导致项目B无法正常独立的使用

### 期待的正确结果

从A项目中导出的数据再B项目中导入，A项目和B项目的代码一模一样，但是可独立运行，A项目和B项目的修改不相互影响

**Comment by zyyfit** [comment]
您好，目前的逻辑是，如果场景有引用接口，会在当前账户有权限的接口中寻找相同的接口关联，但是并不会优先关联当前项目的接口；
您可以先创建一个只有项目B权限的账户1，然后用账户1导入接口，这样应该就会关联项目B的接口了

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
