### ISSUE TITLE
[FEATURE]测试报告中建议增加用例ID的链接跳转

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21716]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

目前测试报告中的用例并不能做链接跳转，如果想要回溯到对应的用例，需要手工复制并粘贴去查，非常不方便
![image](https://user-images.githubusercontent.com/22338833/218256925-7053aca6-c148-402d-b43d-eb5c0817c921.png)

### 请描述你建议的实现方案

建议测试报告中，增加根据用例ID进行跳转！

**Comment by luty2018** [comment]
感谢建议， 这个可以加。

**Comment by chyhant** [comment]
这个功能比较迫切哦，能安排上吗，谢谢！

**Comment by luty2018** [comment]
短期安排不上， 预计2.8以后的版本

**Comment by chyhant** [comment]
@luty2018 请问这个预计几时能安排上呀？

**Comment by luty2018** [comment]
这个月底的v2.10

**Comment by chyhant** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
