### ISSUE TITLE
[BUG]项目新建了2个环境，刚开始只有一个环境，所有调试和运行都是用的A环境，但是新建了B环境后，进行执行，有的执行的A环境有的执行B环境

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#21711]
### 联系方式

18259175411

### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

项目原先就只有一个环境，后来再次添加了一个环境后，使用后面一个环境进行运行，这时候，前置和后的sql执行的时候，有的是执行新环境的有的执行旧环境

### 重现步骤

1、创建一个项目，并创建一个环境A，在项目中进行编写api case并在自动化场景中进行引用，全部使用的引用的方式
2、由于需要适配不同的环境，所以新建 环境B，环境A和环境B使用的数据库不一样，环境A使用的是mysql，环境B使用的金仓数据库
3、为了适配不同的数据库，有在case里面修改sql格式，导致部分case保存的是环境A，部分case保存的是环境B
4、在场景用例中选择环境B进行批量执行，会出现大量报错，原因是因为有的sql执行的是环境A有的sql执行的是环境B，理论上应该是跟随选择的环境进行执行sql的。

### 期待的正确结果

case里不管存的是环境A还是环境B，在执行场景的时候，应该跟随环境进行执行。而不是根据调试的时候存的场景进行执行

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能否描述的具体一点，比如场景中是否选择了环境，场景引用的是sql请求还是http请求中带的前后置sql脚本？sql请求/sql前后置脚本中是否选了环境？执行的时候是在哪个页面执行的呢？是批量执行还是单独执行？是默认用本地执行还是用了哪个资源池呢？
![image](https://user-images.githubusercontent.com/73461316/218401713-ed258e39-2ca3-4090-9c1a-679c8b63d72f.png)

**Comment by wuziyan1** [comment]
你上面的例子我能理解成，不同的环境用的是同一个类型的数据库吗？因为我用的是不同类型的数据库，一个是达梦环境，一个是mysql环境。然后case我是用的达梦环境，被引用后的场景我切换成mysql环境调试就不行了，因为他调用的是被引用case保存的前后置sql的环境。我需要去case里把后置sql的环境手动从达梦切换成mysql才能正常执行。说白了，就是参数会根据环境去取，但是驱动不会，反正case里存的是什么环境就执行的执行的什么环境，跟我们执行的时候选的环境无关

**Comment by zyyfit** [comment]
您好，我没理解您是什么意思，您是说您用了达梦数据库吗？但是我们现在是不支持达梦数据库的，目前只支持这4种数据库，您新建数据库配置的时候选驱动也只能在这4种里选
![image](https://user-images.githubusercontent.com/73461316/218669822-ee5ca5b3-7453-490c-b70f-fa6de58e95b9.png)

**Comment by wuziyan1** [comment]
是的，我们公司支持国产数据库，然后我们通过把驱动放到程序中的处理方式，并在api_test_environment表中修改 config表字段的值.目前数据库都可正常使用。
但是我们需要适配不同的数据库，所以需要切换环境进行执行，这时候，切换环境并不会去切换数据库，只会运用case保存的环境的数据库。所以会报错。我想这个问题应该跟数据类型无关，是因为你们程序切换环境确实不会切换数据库驱动导致的。希望贵司能支持该场景

**Comment by zyyfit** [comment]
目前我们没有内置其他数据库驱动，如果需要的话，得把驱动放到 api-test 里面，如果node 执行，需要把驱动放到资源池，您先试一下

**Comment by wuziyan1** [comment]
目前我们是把所有的容器的/APP/LIB都放了一遍驱动了，不是你说api-test里，所有容器都放进去，然后就可以用了，那你说的驱动放资源池是什么意思。没懂，有没有具体一点的操作步骤。比如放哪个容器的哪个文件夹下

**Comment by fit2-zhao** [comment]
如果不是我们项目内置的驱动，需要在相关容器中放置数据库驱动，不建议这种使用方式，因为未经过兼容测试不确定相关驱动包是否和我们内置包存在冲突情况，慎用。
