### ISSUE TITLE
[FEATURE]上传附件前需要进行文件check，需要事先拿到文件进行生成md5值，但是文件放服务器中经常文件路径找不到

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#21712]
### MeterSphere 版本

2.6.0

### 联系方式

18259175411

### 请描述您的需求或者改进建议

由于需要事先取到文件，所以需要先将文件放置到/opt/metersphere/data/body目录下。由于在取文件的时候，总是会自动先生成一个临时文件夹再将文件复制进去。但是由于经常临时文件夹生成不成功，导致执行用例失败，提示文件路径找不到。希望可以排查下临时文件夹生成不成功的原因。或者找一个地方可以不生成临时文件夹的地方，可以直接找得到文件。
复现步骤
1、将一个文件放置到/opt/metersphere/data/body目录下
2、在前置脚本中写代码取目录下的文件
3、如果没有提示错误，那就去把/opt/metersphere/data/body下的临时文件夹删掉再执行一次，就会复现了。

### 请描述你建议的实现方案

1、提供一个不会生成临时文集夹的目录，这样前置脚本中取文件的时候就可以取到路径了
2、可稳定生成临时文件夹，不会偶尔生成偶尔不会生成，导致校验报错

**Comment by song-tianyang** [comment]
感谢您的支持！

我们在即将发布的v2.7中优化了执行时接口附件的存放位置。 

我们设置了一个执行文件夹，每次执行的时候会检查执行文件夹里有没有本次执行需要的文件。
如果执行文件夹里没有文件、或者文件已更新（这里具体指在文件管理中上传的文件），那么我们就会将执行文件放在这个文件夹中，并将Jmx里的文件路径设置为执行文件夹中的文件路径。

执行文件夹目录暂定为 /opt/metersphere/data/api-folder/file/[ms or node(metersphere执行或者node节点执行)]/{projectId}

执行文件是在文件管理中关联的文件，源文件存放于MinIO或Git 中，那么下载完的文件会存放在上述文件夹里的 /{projectId} 中；
如果执行文件是更早版本上传的，存放在ms中 /opt/metersphere/data/{...}文件夹下的文件， 当使用node执行时，会将文件存放于 /opt/metersphere/data/api-folder/file/node/default/文件夹里。

希望这个改动可以帮到您。
