### ISSUE TITLE
[FEATURE]测试计划执行完成后，应自动生成一份测试报告，而非需要自己手工生成或定时任务生成

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21715]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/22338833/218249031-684a8faf-da23-46be-af2f-dd1ba3ba0458.png)

### 请描述你建议的实现方案

建议用例执行完成后，系统自动触发一次测试报告！

**Comment by luty2018** [comment]
自动执行的测试计划是会生成测试报告的，手动执行的测试计划需要人工确认后再点生成报告
