### ISSUE TITLE
[FEATURE]项目模板建议增加复制功能

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21714]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

目前的项目模板不支持复制，所以如果两个项目间的用例模板等无法复用，只能通过重新手工创建新模板的方式，非常不方便

尝试修改过default模板，也并非全局模板

### 请描述你建议的实现方案

建议增加项目各个模板的复制功能，以及设置全局字段功能，便于模板、字段的复用
![image](https://user-images.githubusercontent.com/22338833/218242679-805a5a1d-b2eb-49bf-a7c6-141f16284974.png)

**Comment by luty2018** [comment]
感谢建议，如果参考目前缺陷模板的复制方式是否能满足你的需求呢

**Comment by chyhant** [comment]
需要考虑不同项目间的复用问题

**Comment by luty2018** [comment]
目前缺陷模板的复制是否满足你的需求， 如果可以，那么用例模板的复制也会这么实现， 如果不满足，请例举。谢谢

**Comment by chyhant** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
