### ISSUE TITLE
[BUG]接口自动化页面，场景用例如果是使用引用的方式，内容无法复制，如想复制sql语句出来都复制不了，一定要去接口定义中找到被引用的地方去复制才行

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#21713]
### 联系方式

18259175411

### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

接口自动化页面，场景用例如果是使用引用的方式，内容无法复制，如想复制sql语句出来都复制不了，一定要去接口定义中找到被引用的地方去复制才行

### 重现步骤

接口自动化页面，场景用例如果是使用引用的方式，内容无法复制，如想复制sql语句出来都复制不了，一定要去接口定义中找到被引用的地方去复制才行

### 期待的正确结果

被引用也应该可复制，即使不能编辑

**Comment by zyyfit** [comment]
您好，最新版 2.6.1 版本没有复现这个问题 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/73461316/218386143-7686f6d2-9ff7-4fc7-b75c-ba1fa807e231.png">

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
