### ISSUE TITLE
[BUG]v2.6.1, 某客户swagger文档导入接口定义出现异常

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21735]
### 联系方式

王进

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

v2.6.1, 某客户swagger文档导入接口定义出现异常

### 重现步骤

1. 接口定义》更多操作》导入
2. 选择Swagger类型
3. 上传swagger文档（确定是swagger文档），导入
4. 显示导入成功，但是实际一个接口都没导入，后台服务抛出异常

### 相关日志输出

```shell
日志输出见附加信息，这是客户环境的日志。  

测试文件在百度网盘，客户删除了大部分接口，但是也可以复制现象。：
链接: https://pan.baidu.com/s/1gbcenTGCjHL2LoQV3b3SCQ?pwd=q4sx 提取码: q4sx
```

### 附加信息

[info.log](https://github.com/metersphere/metersphere/files/10719048/info.log)

**Comment by 35plus** [comment]
这个是客户脱敏的，给的文件有问题，原生的swagger文件导入有问题。

**Comment by 35plus** [comment]
你可以看一下info.log日志

**Comment by zyyfit** [comment]
给开发看了，开发说这是UI模块的日志，请再确认一下

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
