### ISSUE TITLE
[FEATURE]  编辑用户组除了名称都不能编辑，希望其他信息可编辑，比如改完全域用户组

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21738]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

18311441708

### 请描述您的需求或者改进建议

其他信息可编辑，至少能修改为全域用户组，不然用户需要删除重建

![image](https://user-images.githubusercontent.com/103925124/218384804-3ab4ebca-9568-41bd-bcdd-7b5643929c88.png)
![企业微信截图_16763558242239](https://user-images.githubusercontent.com/103925124/218656174-8a9b4d28-6f1d-465d-a593-3c2c428cf34a.png)

**Comment by Hyyfit** [comment]
您好，这里优化，会在UX交互升级的时候考虑，感谢反馈。
