### ISSUE TITLE
[FEATURE]  项目成员的权限，不应该可以查看工作空间下所有项目项目和人员

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21734]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

18311441708

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/103925124/218380498-8e169e54-96d1-4d94-899c-c7fd714722b5.png)
在工作空间-项目管理中只能看到自己有权限的项目，没有权限的项目不展示

在实际使用的信息隔离需求

**Comment by zyyfit** [comment]
补充：这里是用户默认增加了工作空间成员的权限，有项目管理菜单权限，但是用户不想把工作空间成员用户组中的项目管理菜单权限去掉

**Comment by Ycr123888** [comment]
![c1fbe4f91ea820d774555608ebef552](https://user-images.githubusercontent.com/103925124/218410815-c28abc76-185d-4169-94b7-761b8c9942df.png)

**Comment by luty2018** [comment]
设计如此， 有工作空间的权限就能查看工作空间下的菜单
