### ISSUE TITLE
[BUG]接口自动化场景jsonpath提取，勾选匹配多条，后续接口没有引用到原来的值

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21733]
### MeterSphere 版本

v2.4.1，v2.6.0, v2.6.1

### 使用外置数据库

否

### 问题描述

1.接口自动化，后置操作提取参数勾选匹配多条，提取出来数组格式。
2.后续接口采用${变量名_ALL}方式引用，没有引用到原来的数据

### 重现步骤

1.提取到的参数是带引号的
![image](https://user-images.githubusercontent.com/55130444/218380273-72bfef37-8613-4bc5-9cd3-274a4fb417b1.png)
2.这里引用到的数据，每个值是不带有引号的
![image](https://user-images.githubusercontent.com/55130444/218380433-fdd52d87-756c-4b40-9659-1f078947d36e.png)

### 期待的正确结果

能按照提取出来的值引用到之后的脚本中。

**Comment by zyyfit** [comment]
值本来就是不带引号的，响应结果里带引号是因为这是json字符串的格式，提取结果中带引号是因为提取出来是字符串格式的数据

**Comment by FayGao1230** [comment]
那引用时用前置脚本处理好了吗？
