### ISSUE TITLE
[BUG]操作日志对集成的平台账户密码显示为明文

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#21736]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

<img width="657" alt="image" src="https://user-images.githubusercontent.com/104493699/218381711-79ebe297-9a76-40b0-b509-ff4d1e21ada4.png">

### 重现步骤

1、进入【系统设置】-【服务集成】，任意添加一个平台集成，点击保存
2、进入操作日志，查看刚才集成的日志

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
