### ISSUE TITLE
[FEATURE] 创建完用户组之后，当前界面不存在新增数据

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21737]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

18311441708

### 请描述您的需求或者改进建议

工作空间-用户组与权限=========刚新建完的用户组，在最后一行数据
![image](https://user-images.githubusercontent.com/103925124/218382132-41c41656-1e6a-42ce-8a6b-0a10506ea1db.png)
需要手动翻到最后一页，才可可以配置权限
![image](https://user-images.githubusercontent.com/103925124/218382397-2ff14f99-41db-4498-8df3-a74787b851e6.png)

### 请描述你建议的实现方案

刚新建完的用户组，起码在当前页展示出来，不然用户不必要行为增加

**Comment by Hyyfit** [comment]
感谢反馈，在交互优化中会覆盖。
