### ISSUE TITLE
[BUG] 编辑用户组除了名称都不能编辑

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21732]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

编辑用户组除了名称都不能编辑

### 重现步骤

编辑用户组除了名称都不能编辑
![image](https://user-images.githubusercontent.com/103925124/218367426-d029ec4f-a5d5-4723-9745-ebbc715052d3.png)

至少能修改为全域用户组

**Comment by shiziyuan9527** [comment]
除了名称和描述外其它的创建后就不能修改了，逻辑就是这样的，如果要改的话就只能删除重建了。
