### ISSUE TITLE
[BUG]自定义脚本中设置了HashMap,动态取值取出结果为null,脚本在jmeter中可以正常取值

### ISSUE THREAD

**Issue by TesterPei** [metersphere/metersphere#21749]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

无法获取定义的HashMap中的value

### 重现步骤

定义一个map
Map GoodsListMap = new HashMap();
GoodsListMap.put("2", "includeCategoryPaths");
GoodsListMap.put("3", "includeBrandIds");
GoodsListMap.put("4", "includeTagIds");
GoodsListMap.put("5", "includeSpuIds");
GoodsListMap.put("1", null);
在通过响应中部分参数确定是哪种类型，通过自建Map获取规则
displayGoodsType = one_module.get("displayGoodsType");
newType = GoodsListMap.get(displayGoodsType);
这时获取的newType 为null

### 附加信息

![image](https://user-images.githubusercontent.com/71563322/218405094-7cb48f9a-096d-485f-9c6a-bcb6e9c546d3.png)

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
