### ISSUE TITLE
[BUG]UI测试，打开A网页，然后关闭A网页，再打开B网页，关闭A网页之后的步骤都是未执行了

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21752]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

UI测试，打开A网页，然后关闭A网页，再打开B网页，关闭A网页之后的步骤都是未执行了

### 重现步骤

1.UI测试，打开A网页，然后关闭A网页，再打开B网页
![image](https://user-images.githubusercontent.com/103627487/218409180-eee14945-7079-42ef-94a5-58779092a111.png)
2.点击生成报告，可以看到关闭A网页之后的步骤都是未执行了
![image](https://user-images.githubusercontent.com/103627487/218410407-9fdb3f66-0da4-4e0c-8de9-7b2c8a1476a4.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、您描述的场景-是单窗口操作-关闭网页后窗口就被关闭了，后面的步骤则不会被执行。
2、如果想要打开网页A后再打开网页B，则可以把打开网页B（追加页面）步骤挪到关闭网页A步骤之前，然后通过切换窗口在网页A或者B中操作和关闭对应窗口，用多窗口场景设计可满足。
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/99731894/218663257-1339d7ec-6979-40b9-9bc0-fb44f7f237bd.png">
