### ISSUE TITLE
[FEATURE]项目设置-自定义代码片段，点击确定按钮后，当前页面没有关闭，还得手动点击“X"才能关闭页面

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21768]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

18311441708

### 请描述您的需求或者改进建议

![8c929ee774dd6dd392f5d42f6e35dee](https://user-images.githubusercontent.com/103925124/218446286-4d5d5445-11b0-48d9-a2b8-3794b5474ecb.png)

保存成功后自动关闭回到列表页面

**Comment by Hyyfit** [comment]
感谢反馈，后续版本会更新的。

**Comment by Ycr123888** [comment]
v2.8.1可修复下嘛，频繁修复或新增的话，用户冗余操作有些多@Hyyfit
