### ISSUE TITLE
[BUG]接口请求头的Authorization参数值，在步骤数量较多的场景中执行时，总会在后面某个步骤开始就无法获取到完整的Authorization参数值了

### ISSUE THREAD

**Issue by meifeifei** [metersphere/metersphere#21761]
### 联系方式

844177611@qq.com

### MeterSphere 版本

v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

请求头参数的值，同一个场景的步骤里面，前面几个都能正确获取到，后面的几个步骤不可预知的会丢失一部分：
请求参数Authorization的值由2部分组成（Authorization的值：组成1 组成2）：
正确获取到的：Authorization的值：组成1 组成2
丢失的：Authorization的值：组成1，如下：
![cfaad317c329cc7b3f09003ac1942b7](https://user-images.githubusercontent.com/57786489/218427268-52960456-b786-4894-aa56-488b5c31f642.png)
![54ef03fb43732d5d5ee1febcaaad897](https://user-images.githubusercontent.com/57786489/218427295-e8d8bba3-5efa-4272-af5b-7dd95ed7671c.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/57786489/218427439-ae1c1da3-1d24-41f4-8313-4ce62ffa2962.png)

### 期待的正确结果

只要是一个场景的所有步骤，参数值都应该能正确完全的获取，不会有丢失。

**Comment by zyyfit** [comment]
您好，最新版1.20.19，场景里添加了接近300个请求，没有复现这个问题，请升级试试
![image](https://user-images.githubusercontent.com/73461316/218448020-fabfc81e-0722-4bde-b0be-80563ca8580f.png)

**Comment by meifeifei** [comment]
您好，请在场景里面引用场景和使用事务控制器看看，我这边也不是所有的大场景都有这个问题。

发件人: zyyfit ***@***.***>
发送时间: 2023年2月13日 19:38
收件人: metersphere/metersphere ***@***.***>
抄送: 梅菲06578 ***@***.***>; Author ***@***.***>
主题: Re: [metersphere/metersphere] [BUG]接口请求头的Authorization参数值，在步骤数量较多的场景中执行时，总会在后面某个步骤开始就无法获取到完整的Authorization参数值了 (Issue #21761)


您好，最新版1.20.19，场景里添加了接近300个请求，没有复现这个问题，请升级试试
[图像已被发件人删除。 image]<https://user-images.githubusercontent.com/73461316/218448020-fabfc81e-0722-4bde-b0be-80563ca8580f.png>

**Comment by meifeifei** [comment]
您好，请在场景里面引用场景和使用事务控制器看看，我这边也不是所有的大场景都有这个问题。

**Comment by zyyfit** [comment]
复现了，感谢反馈，后续版本修复

**Comment by meifeifei** [comment]
这里还有一个小case：
在导入另一个场景为步骤后，在后面添加case/api的步骤在执行时无法获取header的Authorization值（虽然这个值是全局变量—场景变量里面用了P函数全局化了）

发件人: zyyfit ***@***.***>
发送时间: 2023年2月14日 14:58
收件人: metersphere/metersphere ***@***.***>
抄送: 梅菲06578 ***@***.***>; Author ***@***.***>
主题: Re: [metersphere/metersphere] [BUG]接口请求头的Authorization参数值，在步骤数量较多的场景中执行时，总会在后面某个步骤开始就无法获取到完整的Authorization参数值了 (Issue #21761)


复现了，感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这里还有一个小case：
在导入另一个场景为步骤后，在后面添加case/api的步骤在执行时无法获取header的Authorization值（虽然这个值是全局变量—场景变量里面用了P函数全局化了）
--------------------------------------------
您好，这里没有理解您是怎么操作的，可以新提一个issue具体描述一下这个场景吗？最好一个issue只处理一个问题，不然多了不容易区分

**Comment by zyyfit** [comment]
1.20.20 版本 和 2.7.0 版本都已修复，请升级后使用
