### ISSUE TITLE
[BUG]接口自动化复制case，修改环境中的请求方式由http-https，接口case显示没有及时更新。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21765]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

1.将接口case复制到接口自动化中，
2.修改环境配置的http配置由 http改为https，更新保存之后，自动化场景刷新，页面仍然展示的是http，调试接口请求内容调用的是https。

### 重现步骤

1.将接口case复制到接口自动化中，
2.修改http配置由http改为https，刷新自动化场景，
![image](https://user-images.githubusercontent.com/55130444/218614846-1568f384-90c1-44dd-b5a3-872ce0967c9a.png)

3.执行接口case，请求内容是https，
![image](https://user-images.githubusercontent.com/55130444/218614786-2a223ddc-b2f4-423d-bac5-f27eabab6223.png)

4.需要重新选择运行环境点击确定，页面才会显示正确。

### 期待的正确结果
刷新之后能正确显示请求。

_No response_

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本发布后验证

**Comment by kaijie-yu** [comment]
已验证修复
