### ISSUE TITLE
[QUESTION] 镜像部署时，kafka一直提示超时

### ISSUE THREAD

**Issue by xzcawl** [metersphere/metersphere#21762]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/20625815/218431849-f74c4eb1-6940-4796-92ae-9899e4fec408.png)
如图显示，应用状态是healthy的，但是kafka异常

**Comment by liuruibin** [comment]
请检查kafka是否正常，端口是不是连通

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
