### ISSUE TITLE
[FEATURE]  新建用户组，比如项目用户组，用户需要手动点击很多次，希望增加全选框

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21778]
### MeterSphere 版本

v1.20.19-lts

### 联系方式

18311441708

### 请描述您的需求或者改进建议

 新建用户组，比如项目用户组，用户需要手动点击很多次，希望增加全选框
![image](https://user-images.githubusercontent.com/103925124/218653405-7ab42603-30ed-4dfb-a0d2-e8e31a6389dc.png)

**Comment by Hyyfit** [comment]
感谢反馈，已规划排期
