### ISSUE TITLE
[BUG]接口测试在json响应体数列值过多的情况下，概率性出现jsonpath提参/断言的精度值有误

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#21777]
### MeterSphere 版本

V2.6.1

### 使用外置数据库

否

### 问题描述

在json响应体的数组中的数列值过多(有7000多组数列)的情况下，进行jsonpath提参、断言时，概率性出现提取的数值精度显示有误，导致断言校验失败

### 重现步骤

概率性问题，在客户现场环境上复现概率较大，本地mock调试时，未能复现，需开发人员帮忙分析定位

### 附加信息

![1762196bdde1b79696db6449e57403d0_](https://user-images.githubusercontent.com/92150453/218651831-2722a37b-c0a5-47b5-8498-36e11652ca58.jpg)
[json响应体.txt](https://github.com/metersphere/metersphere/files/10729242/json.txt)

**Comment by zyyfit** [comment]
我们的环境没有复现这个问题，请提供一下错误信息或者执行日志等数据

**Comment by youliyuan-fit2cloud** [comment]
该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
