### ISSUE TITLE
[BUG] 环境配置-http配置增加路径为空的http配置，在添加时未提示，在点击确定时触发提示

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21795]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

环境配置-http配置增加路径为空的http配置，在添加时为进行提示，在点击确定时触发提示

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/218670628-79532efd-b9ec-4195-84c5-b4c555a69049.png)

### 期待的正确结果

点击添加时校验并提示 路径不能为空

**Comment by zyyfit** [comment]
1.20版本目前以保持稳定性为主，不影响功能的优化信息暂时不修复了
