### ISSUE TITLE
[BUG]导入har文件有接口url没有过滤掉重复的

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#21802]
### 联系方式

746560359@qq.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

导入HAR数据,选择不覆盖,依然产生重复数据

### 重现步骤

1.从chrome导出接口数据为har
2.metersphere选择导入HAR
3.系统参数接口配置为校验重复url
结果导入有接口url没有过滤掉重复的

### 期待的正确结果

过滤重复的

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请再检查一下接口url是否可重复的配置和相同url的接口请求方式是否相同，不同的请求方式也算不同接口的

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
