### ISSUE TITLE
[FEATURE]期望可以拷贝多个步骤到另外一个场景用例

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21805]
### MeterSphere 版本

v2.6.1

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

1.已有场景用例 A，里面有 30 个步骤
2 当前需要场景用例 B，其中有 15 个步骤是场景用例 A 中已有的

期望可以在场景用例 A 中选择 15 个步骤，然后复制到场景用例 B 中

需要复制的原因：
刚开始不知道场景用例 B怎么写， 开始写了 10 个步骤后，发现需要的其他步骤大部分都在用例 A 中。

### 请描述你建议的实现方案

如图，增加一个复制的选项
![image](https://user-images.githubusercontent.com/4860962/218697898-74b41a2c-d3cf-478d-ad09-bd695eb790a3.png)

**Comment by Hyyfit** [comment]
您好，我们支持复制场景，可以对复制后不需要使用的子步骤进行删除
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/95834771/218915315-89363af7-a579-4d06-8fcb-4171a000b0c0.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/95834771/218915846-f7bce89f-e985-4fbd-a66a-0dc49f39f6e1.png">

**Comment by hao1032** [comment]
你说的这个操作我知道，这样操作的前提是：我在写 B 用例前就知道 B 用例的大部分步骤是用例 A 里面的。

你可以看下我上面的描述，我说明了需要复制了的原因
> 需要复制的原因：
刚开始不知道场景用例 B怎么写， 开始写了 10 个步骤后，发现需要的其他步骤大部分都在用例 A 中。

**Comment by Hyyfit** [comment]
那也是要去A里复制，这不是一样的吗？

**Comment by hao1032** [comment]
> 那也是要去A里复制，这不是一样的吗？

怎么一样了？？

当前的场景我再描述一下：
1.开始写 B 用例，写了 10 个步骤，还有 15 个步骤需要写
2.想起来这 15 个步骤在 A 用例里面都有，**去 A 选择 15 个步骤然后复制到 B** 这个是我期望的功能

你说的一样是啥意思呢？
