### ISSUE TITLE
[BUG]接口自动化，场景没有编辑，却提示未保存

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21804]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

用例没有编辑，却提示未保存

### 重现步骤

1.场景用例列表中点击一个用例
2.用例加载后，不做任何操作，点击 X
![image](https://user-images.githubusercontent.com/4860962/218693582-583606df-ccdf-438f-ab03-16d393d462d4.png)
3.提示用例未保存
![image](https://user-images.githubusercontent.com/4860962/218693695-dccdba7e-c1f3-426b-8187-e635ee6abf2c.png)

### 期待的正确结果

没有修改，关闭用例，没有提示弹框

**Comment by xulinde** [comment]
使用v2.6.1版本未复现该问题，建议您详细描述下复现步骤或者录制个视屏

**Comment by hao1032** [comment]
https://user-images.githubusercontent.com/4860962/219303735-c7d340cb-3226-45c7-9a95-4a275d8db7fd.mp4

复现视频

**Comment by xulinde** [comment]
v2.7.0已修复
