### ISSUE TITLE
[BUG]v2.6.1, 用例评审，功能用例按照id排序，会出现排序不正确的情况。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#21809]
### 联系方式

王进

### MeterSphere 版本

v.2.6.1

### 使用外置数据库

否

### 问题描述

v2.6.1, 用例评审，功能用例按照id排序，会出现排序不正确的情况。

### 重现步骤

1. 如果要复现问题，需要在MS里创建比较多的用例，五六百条
2. 添加id为1005,1004开头的用例到用例评审里
3. 在用例评审里，按照id进行排序，就能看到现象，比如下面这个截图。
<img width="121" alt="1676431350485" src="https://user-images.githubusercontent.com/76033005/218919351-abd86248-cb67-4193-ad90-418f8d703624.png">

### 附加信息
帮忙在2.7上修复该问题，感谢！
_No response_

**Comment by xulinde** [comment]
未复现该问题，有稳定复现的步骤吗？

**Comment by 35plus** [comment]
<img width="901" alt="1677035561998" src="https://user-images.githubusercontent.com/76033005/220511914-31fe62dc-d324-4b09-9e5c-b6f124e4c3d2.png">

**Comment by 35plus** [comment]
这个问题刚刚复测了，还是有，需要往评审单里多加一些用例。

**Comment by xulinde** [comment]
v2.7.0已修复～
