### ISSUE TITLE
[BUG]使用 ${__V(certificateNo,)} 函数异常

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21803]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

异常
<img width="894" alt="image" src="https://user-images.githubusercontent.com/4860962/218691464-16b94465-0099-4e36-9e08-1e98f85edac7.png">

### 重现步骤

无

**Comment by zyyfit** [comment]
您好，没有复现这个问题，使用ms和jmeter执行结果一致
![image](https://user-images.githubusercontent.com/73461316/219292121-561c2d8c-6aa7-4535-baa5-213017145b9a.png)
![image](https://user-images.githubusercontent.com/73461316/219292183-a334370b-e258-4b7f-a982-d0157d73797c.png)
![image](https://user-images.githubusercontent.com/73461316/219292157-d9fe2b64-da11-4618-8f6b-5ce040331a89.png)

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
