### ISSUE TITLE
[BUG]ladp登录后1个小时内就被自动退出登录

### ISSUE THREAD

**Issue by yangxiea** [metersphere/metersphere#21806]
### 联系方式

yangxiea

### MeterSphere 版本

2.6.0

### 使用外置数据库

否

### 问题描述

ladp登录后1个小时内就被自动退出登录，此场景出现过多次

### 重现步骤

ladp登录后点击测试跟踪，被退出登录

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请详细描述一下复现步骤，比如项目是使用在线脚本一键安装的吗？配置有没有修改过？在什么情况下会出现被退出的情况？

**Comment by yangxiea** [comment]
> 您好，没有复现这个问题，请详细描述一下复现步骤，比如项目是使用在线脚本一键安装的吗？配置有没有修改过？在什么情况下会出现被退出的情况？

是包下载下来离线安装的，配置没有修改过。团队成员反馈有两种情况：1、写用例看脑图时突然被剔出。2、刚登录进来点击测试跟踪就被踢出。

**Comment by zyyfit** [comment]
退出时有没有日志信息或者是报错信息可以提供呢？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
