### ISSUE TITLE
[BUG]postman脚本导入到MS中，前后置脚本无法解析

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#21816]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

将postman中的脚本导出来后，导入到MS的接口自动化中，在MS中看不到前后置脚本

### 重现步骤

1、将该postman脚本导出
<img width="863" alt="image" src="https://user-images.githubusercontent.com/104493699/218927408-19277b51-b324-48cd-a000-fdd12bdd942c.png">
2、进入MS的接口自动化中，然后导入
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/104493699/218932282-585201a9-8c98-4aa7-a895-3a4e39fd3b98.png">

**Comment by zyyfit** [comment]
您好，目前我们只支持jmeter的前后置脚本，而且只支持我们系统里现在有的几个组件，其他系统里没有的组件导入的话，当作场景导入可以使用jmx原始文件执行，当作接口定义导入也是不会显示系统里没有的组件的
