### ISSUE TITLE
[FEATURE]建议Jira 集成支持关联多个 需求或故障类型

### ISSUE THREAD

**Issue by Jarod-Guo** [metersphere/metersphere#21810]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

**症状:**
目前在设置项目，关联JIRA项目时，关联 需求和故障 只能选一个Jira类型。
但是往往需求来源多个，比如: Story, 以及 Task
故障也会分多个jira类型.
![image](https://user-images.githubusercontent.com/55393693/218921720-2754f73b-bce6-446f-a2da-dc8650be5276.png)

**期望**
请支持需求和故障关联多个jira类型。
参考另一个工具的需求类型设置:
![image](https://user-images.githubusercontent.com/55393693/218922240-91f4e7d3-a0a1-4d6e-8b87-0bf0c944c3a7.png)

**Comment by luty2018** [comment]
感谢反馈，这里我们需要调研一下。
