### ISSUE TITLE
[BUG]【接口定义】快捷调试-选择本地上传文件后，点击调试后，没有内容返回

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21820]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

在快捷调试-选择本地上传文件后，点击调试后，没有内容返回
![image](https://user-images.githubusercontent.com/104960608/218946168-b27b2f9c-fa10-44a3-8002-6f5dbdc06423.png)

### 重现步骤

1. 将doc文件上传到文件管理处，在快捷调试-参数里选择关联文件，将该文件进行关联
![image](https://user-images.githubusercontent.com/104960608/218945080-c9459174-24f3-49c4-8e17-b6038638e772.png)

2.可看到有返回内容
![image](https://user-images.githubusercontent.com/104960608/218945406-58c4b58c-6794-489f-b5d4-fcdc94e1a95a.png)

3.在快捷调试-选择本地上传文件后，点击调试后，没有内容返回
![image](https://user-images.githubusercontent.com/104960608/218945589-b683ecfe-0cbd-425a-9832-6678a6daae79.png)

4.请求内容如下
[新建文件夹.zip](https://github.com/metersphere/metersphere/files/10739815/default.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本发布后验证
