### ISSUE TITLE
[BUG]场景执行(场景步骤较多），偶发Pending问题

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#21825]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

场景执行(场景步骤较多），偶发Pending问题，客户环境出现概率较高，自己环境设置定时任务，也会有这个问题出现，概率较低。

### 重现步骤

1.场景导入客户的场景，导入客户环境
[场景和环境-pendding.zip](https://github.com/metersphere/metersphere/files/10740053/-pendding.zip)
2.因执行时间较长，可以设置定时任务执行
![image](https://user-images.githubusercontent.com/103627487/218951670-3fb0124d-0679-4021-9b0b-fb5f516fe4d9.png)
3.查看报告，有Pending出现
![image](https://user-images.githubusercontent.com/103627487/218951493-1cb10bb0-b1d9-4c25-8375-a28d9f0954ee.png)
![image](https://user-images.githubusercontent.com/103627487/218951577-cee23b60-b005-4386-bfc6-59a4915edc41.png)

**Comment by luty2018** [comment]
没有复现， 建议升级版本继续观察
