### ISSUE TITLE
[BUG] 与JIRA BUG平台对接，有部分字段不会同步到BUG模板中；

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#21830]
### MeterSphere 版本

2.4.0

### 使用外置数据库

否

### 问题描述

与JIRA BUG平台对接，MS能获取JIRA BUG平台上大部分字段，在提交BUG时能被显示&编辑，部分字段不会同步到BUG模板中，例如【标签】字段

### 重现步骤

1. 创建JIRA项目，选择使用JIRA BUG模板
2. 通过MS提交BUG，在BUG编写页面，【标签】字段不会被显示
![企业微信截图_16764454284907](https://user-images.githubusercontent.com/6109912/218958574-f6d951c5-5523-4878-9573-e64c883308c5.png)
![企业微信截图_16764454611244](https://user-images.githubusercontent.com/6109912/218958674-72b1ab87-b458-4603-b5bd-182d40864afc.png)

**Comment by xulinde** [comment]
未复现该问题，建议您升级到最新版本再试下
