### ISSUE TITLE
[FEATURE]自定义变量下拉选择功能

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#21842]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

2297310871@qq.com

### 请描述您的需求或者改进建议

自定义的变量在用例或者场景中可以搜索联想出来：
![图片](https://user-images.githubusercontent.com/23067502/219064745-c351d796-4a2e-4f1b-b563-6043f6bd0573.png)

### 请描述你建议的实现方案

在用例或者场景中进行参数化的时候，通过@或者$或者其他关键字可以显示出来，或者通过输入关键字联想显示出来：
![图片](https://user-images.githubusercontent.com/23067502/219065243-7802bcb9-2c6a-4207-89bb-432034fc052c.png)

**Comment by Hyyfit** [comment]
感谢反馈，待规划排期。
