### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#21844]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

17321336962

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/219071109-fd9084cf-7911-42f9-8018-fcd743e489cb.png)
在一些复杂的场景中，需要参数化的测试数据比较多，数据的管理更希望跟随环境一起变化，配置环境-通用配置中的变量可以拖放进行位置调整使得排查更直观，可以进行分组便于管理

**Comment by luty2018** [comment]
分组的是根据什么特征来分呢？

**Comment by xiaochongzi-ling** [comment]
自定义分组，相当于打标签后进行组别管理，这样可以快速维护某一个分组数据。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by luty2018** [comment]
一般会打上什么内容的标签?麻烦解答一下谢谢！我们目前正在计划优化这里。

**Comment by xiaochongzi-ling** [comment]
相当于在目前的基础上进行二级分类分组，比如新股数据、新债数据可以分别作为一个分组；新股数据其下可以包括新股-沪市、新股-深市、新股-京市所对应的具体值。
分组的名称可以自定义，同样的分组名字则为一类数据；
数据的排序方式可以支持通过分组排序，方便数据维护；
数据可以拖动，可以将最新添加的数据拖动到同一类数据的位置。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE] (Issue #21844)



 
一般会打上什么内容的标签?麻烦解答一下谢谢！我们目前正在计划优化这里。

**Comment by luty2018** [comment]
那我们在变量名后面新增一个标签列， 可以改善目前的使用体验吗?

**Comment by luty2018** [comment]
<img width="1094" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/daf6510d-2d67-4fec-8834-69ce8c85f6cd">
