### ISSUE TITLE
[BUG] 遇到数据库卡顿频繁提交num值不发生变化

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2184]
**MeterSphere 版本**
1.8.2

**Bug 描述**
在mysqldump的时候因为数据库操作卡死；导致前端多次提交了场景保存操作；
发现卡住之后停掉了mysqldump操作
多个保存操作被响应了
结果是场景的num值相同了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是保存了多个场景然后场景ID相同吗

**Comment by guhan121** [comment]
@zyyfit 是的

**Comment by zyyfit** [comment]
最新版已修复，若还有问题请reopen
