### ISSUE TITLE
[BUG]random相关函数无法成功使用，其余函数可以

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#21843]
### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

是

### 问题描述

![图片](https://user-images.githubusercontent.com/23067502/219065586-9091215f-d82d-4cca-8929-cb00afbf09d7.png)

### 重现步骤

![图片](https://user-images.githubusercontent.com/23067502/219065734-8f22f9e9-fa20-4f3d-87e9-0f3ccd323419.png)

### 期待的正确结果

成功使用random相关函数

**Comment by zyyfit** [comment]
您好，最新版2.7.0版本没有复现这个问题，请升级后试试

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
