### ISSUE TITLE
[BUG]接口定义一键同步case处bug,接口打开json-schema，case不打开json-sheme，会导致请求体新增参数同步错误

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21847]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

接口定义一键同步case同步后，请求体同步出错。

### 重现步骤

1.新增接口，多个case
![image](https://user-images.githubusercontent.com/55130444/219240127-822e3477-d78f-4a64-9998-394266ec4fcf.png)
![image](https://user-images.githubusercontent.com/55130444/219240230-e0b4b5cb-3da0-4c20-9caf-92fed0cb58a9.png)
2.api请求体新增一个参数
![image](https://user-images.githubusercontent.com/55130444/219240627-563d768d-1fd9-4f84-a8ec-e1879f1e757e.png)
3.不勾选删除用例中无法与api文档对应的参数
![image](https://user-images.githubusercontent.com/55130444/219240816-5f11c342-8615-4d33-bc45-e9482a868677.png)
4.case同步后的请求体是很久之前的内容
![image](https://user-images.githubusercontent.com/55130444/219241984-328b6d40-b466-45dc-9d6b-5454fc1dbf47.png)

### 期待的正确结果

1.没有增加接口请求体参数时，接口里有，case中没有的参数同步过去后，不会把接口中的参数自动补到case中
2.json-schema的打开与否和api-case的同步没有关系，请求体数据同步应该不出问题
3.接口请求体里新增的字段能够一键同步到所有case中去

**Comment by zyyfit** [comment]
您好，没有复现您的问题，目前的逻辑是这样的，关于这几个问题，
1、case中没有的参数，不管是不是新增的，只要勾选了同步case，就都会同步过去
2、case中请求体的各个tab不会自动切换，不过数据都是同步了的，目前需要手动切换一下
3、新增的字段，如果接口中有，就不会修改接口中的字段和值了，如果接口中没有，并且勾选了同步，会同步过去的

**Comment by zyyfit** [comment]
复现了

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本发布后验证

**Comment by kaijie-yu** [comment]
已验证修复
