### ISSUE TITLE
[BUG] 在场景中切换环境后，前/后置SQL中未切换到同名数据库名称，在case中切换环境，会切换到同名数据库名称

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21858]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

在场景中切换环境后，前/后置SQL中未切换到同名数据库名称，在case中切换环境，会切换到同名数据库名称

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/219263176-54733d69-471c-4be0-812e-0ec91d5146cf.png)
![image](https://user-images.githubusercontent.com/103925124/219263268-e3fa1def-defe-41af-9686-56097916627c.png)

### 期待的正确结果

 在场景中切换环境后，前/后置SQL中可切换到同名数据库名称

**Comment by zyyfit** [comment]
您好，没有复现这个问题，如果您之前选择过 north copy 这个环境中的121 数据源并进行了保存，再从其他环境切换回来的时候，会优先选择您之前保存的环境，如果从来没保存过，才会有限选择同名数据源

**Comment by Ycr123888** [comment]
了解这个机制了
