### ISSUE TITLE
[BUG]将 MS 系统部署到 阿里云平台，扫描下来有1个应用漏洞

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#21853]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

将 MS 系统部署到 阿里云平台，扫描下来有1个应用漏洞
![564eb06e-464c-41c7-8ee1-a69bab011d1b](https://user-images.githubusercontent.com/104960608/219257602-6df84e77-7ef0-4a88-9652-7744eaa4becf.png)

### 重现步骤

1.将 MS 系统部署到 阿里云平台，扫描下来有1个应用漏洞
![564eb06e-464c-41c7-8ee1-a69bab011d1b](https://user-images.githubusercontent.com/104960608/219257260-07d1716b-adfa-4111-b2f9-9dc59ff5e105.png)
2. 可访问这个地址查看解决漏洞
https://avd.aliyun.com/detail?id=AVD-2022-39198

**Comment by maninhill** [comment]
@liuruibin

**Comment by liuruibin** [comment]
感谢提醒，我们将在 2.7.0中修复这个问题
