### ISSUE TITLE
[BUG]  环境配置页面，当鼠标选中数据库配置-数据库名称，点击确认时，必现请输入ip地址

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21854]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

环境配置页面，当鼠标选中数据库配置-数据库名称，点击确认时，必现请输入ip地址

### 重现步骤

点击能够环境的数据库名称
![image](https://user-images.githubusercontent.com/103925124/219259349-e75d2b7f-278e-4996-9398-c9981de0ff77.png)
切换红框环境到橙框环境，同样聚焦到数据库名称，然后点确认
![image](https://user-images.githubusercontent.com/103925124/219259558-d36f2799-df3e-4968-bb43-6e9ad86f3e9a.png)
会一直提示请输入IP地址，确认不了。。。
![image](https://user-images.githubusercontent.com/103925124/219259649-635eb988-4b25-494c-af67-272ba755845f.png)

### 期待的正确结果

可正常确认后退出

**Comment by zyyfit** [comment]
没有复现这个问题，请确认复现步骤

https://user-images.githubusercontent.com/73461316/219298002-1676cf35-d8c3-4106-b451-71c583664330.mov

**Comment by Ycr123888** [comment]
使用下面的环境和上面的步骤属于必现


环境文件已私发，未知原因上传不了~

**Comment by zyyfit** [comment]
已确认是因为开启了host但是没有填写host信息导致的，不知道怎么出现的这种情况，等复现了同样的场景再反馈吧
![image](https://user-images.githubusercontent.com/73461316/219320938-f669e47e-904b-4279-b09f-fde3e2690a9d.png)
