### ISSUE TITLE
[BUG]脚本使用泛型，报错

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21850]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

脚本使用泛型，报错

### 重现步骤

ArrayList<String> sites = new ArrayList<String>();
sites.add("Google");

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/4860962/219256633-38b7384e-2375-4dd6-a8cb-20c0ee8f33c1.png">

**Comment by zyyfit** [comment]
您好，不带 <String> 可以正常执行，带上 <String> 在jmeter里也是会报错的
![image](https://user-images.githubusercontent.com/73461316/219296979-4bfc634d-ee94-486e-ad5d-c7ca59699e15.png)

**Comment by hao1032** [comment]
我这边 jmeter 不会报错哦
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/4860962/219304811-1e2d543d-b3fe-41ea-b5c4-f3154164ac7e.png">

**Comment by zyyfit** [comment]
我看您jmeter里选的是groovy脚本，请在metersphere里也选择groovy脚本
![image](https://user-images.githubusercontent.com/73461316/219653784-a9595448-d489-4258-8847-caf0fdad742a.png)

**Comment by hao1032** [comment]
收到，可以了。
