### ISSUE TITLE
[BUG]系统登录，同样的请求数据，在jmeter中成功，MS中返回失败，如截图

### ISSUE THREAD

**Issue by daicp** [metersphere/metersphere#2185]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.1
**Bug 描述**
简要描述您碰到的问题
系统登录报错
**Bug 重现步骤**
1.  POST接口，
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
登录成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/39850851/115685555-e81d9800-a38a-11eb-9578-391f2186b458.png)
![image](https://user-images.githubusercontent.com/39850851/115685556-e81d9800-a38a-11eb-9d9d-084ec47b9f21.png)

**Comment by zyyfit** [comment]
您好，方便提供一下jmeter和metersphere的原始文件吗

**Comment by daicp** [comment]
您好，这个问题最后查明是程序的问题，不是MS的问题，非常感谢
