### ISSUE TITLE
[BUG]接口自动化调试过程中点击停止，调试历史列表中状态不会更新

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#21873]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

接口自动化调试过程中点击停止，调试历史列表中状态不会更新

### 重现步骤

1、选择接口自动化点击调试
2、点击停止
3、打开调试历史列表
4、当次执行的状态一直为running

### 期待的正确结果

更新为正确的状态

### 附加信息

停止：
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/32027713/219283602-47b585a8-5ce2-4df4-a8af-12ee4ce97bd5.png">

调试历史中的状态：
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/32027713/219283668-67c9d161-fbfb-4b5f-9188-b261bfe1a092.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.7.0版本已修复，请等待版本发布后验证
