### ISSUE TITLE
[FEATURE]接口自动化调试过程中，点击停止，希望已执行步骤测试结果及状态不清空

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#21872]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

接口自动化调试过程中，点击停止，已执行步骤测试结果及状态被清空

### 重现步骤

1、选择某个步骤较多的接口自动化场景
2、点击调试
3、点击停止
4、观察页面

### 期待的正确结果

希望停止之后，已经执行的步骤状态及执行参数结果保留下来

### 附加信息

调试：
<img width="986" alt="image" src="https://user-images.githubusercontent.com/32027713/219282714-855c551e-233d-4908-acb0-c443c37abfc7.png">

停止：
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/32027713/219282769-43a7ca7e-e577-4381-aaa0-228bb09b9945.png">

**Comment by Hyyfit** [comment]
感谢反馈，可以支持的，我们后续版本里会规划上。
