### ISSUE TITLE
[BUG]接口自动化内点击“铅笔”图形按钮，前置返回tab不会自动显示所有参数提取

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#21887]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

接口自动化内点击“铅笔”图形按钮，前置返回tab不会自动显示所有参数提取

### 重现步骤

接口自动化内点击“铅笔”图形按钮，前置返回tab不会自动显示所有参数提取，需要逐个点击步骤才可以显示

### 期待的正确结果

点击“前置返回”可以显示所有的参数提取

### 附加信息

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/32027713/219300330-1a76dffd-715f-451c-8b2c-ffae105c564c.png">

**Comment by luty2018** [comment]
全部显示出来会比较多， 需要手动点击步骤右边才会显示。
