### ISSUE TITLE
[BUG] 使用api调用执行测试计划，当userid为空或填不存在值时，执行测试计划接口成功，但报告一直running，不会自动停止

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#21892]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

使用api调用执行测试计划，当userid为空或填不存在值时，执行测试计划接口成功，但报告一直running，不会自动停止

### 重现步骤

调用执行测试计划接口，请求体中userid为空
![image](https://user-images.githubusercontent.com/103925124/219306897-82ab0891-e36d-41e9-a95e-a41c4bfcb1fb.png)
接口执行成功，未报错
![image](https://user-images.githubusercontent.com/103925124/219307700-d8ad81e4-36a5-42c7-a1cb-aeb8f006e63f.png)
导致测试报告一直running，不会停止
![cae707a4412629e782d18fe8f4a6bae](https://user-images.githubusercontent.com/103925124/219307180-57427d38-1808-4a49-879a-49771906979c.png)

### 期待的正确结果

当userid为空或userID不存在时，响应体提示为 userID为空或不正确

**Comment by xulinde** [comment]
userID是必填项，这个用户的userID为啥是空呢

**Comment by Ycr123888** [comment]
我提这个缺陷的意思是，接口应该返回userID是必填项，请填写

**Comment by xulinde** [comment]
v2.7.0已修复～
