### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hanchenglong001** [metersphere/metersphere#21893]
### MeterSphere 版本

v1.20-lts

### 联系方式

微信交流群53 all 　　　 　 　　 　👁_👁　: 

### 请描述您的需求或者改进建议

响应结果里面的html解析
jmeter的 html是真的解析html的。 metersphere只是整理了个格式。 希望和jmeter保持一致

### 附加信息

![b26066892ce4622eed68d58be733d47](https://user-images.githubusercontent.com/56539098/219319309-ab33272f-5451-407c-a70a-06e09481252a.png)
![0a620a2e92dfa822e93704c2bbebe4c](https://user-images.githubusercontent.com/56539098/219319334-e17ac0c4-f5a7-4875-8d2e-9e6b77593639.png)

**Comment by hanchenglong001** [comment]
还有我设置了响应体个格式 响应应该按照这个格式优先响应。不用自己在去选一下格式。
![image](https://user-images.githubusercontent.com/56539098/219323132-28f70194-cb10-4e85-9d39-b46e8f42e36d.png)

**Comment by Hyyfit** [comment]
您好，解析的目的是想要做什么？

**Comment by hanchenglong001** [comment]
@Hyyfit  一些老的项目接口响应是返回页面的。我想直观的看到页面。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
虽然我们底层是Jmeter，但是它的UI跟我们的不同，要实现有两种方式：1  直接把这个 html 在当前浏览器打开；2 找一个能显示html的插件集成进来。
但是这个功能我们暂时没有规划。
