### ISSUE TITLE
[FEATURE]接口测试建议可以选择多个测试集合批量执行

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#219]
目前新建测试等同于一个测试集合里面可以有多个场景，但是一个项目一般会按照模块分成很多个测试集，想要一起执行这些集合场景，目前只能单个集合执行

**Comment by wangzhen-fit2cloud** [comment]
你好，这个功能目前在开发中了，可以持续关注下

**Comment by wuha07456** [comment]
这功能大概啥时候上线啊 后续怎么在服务器更新

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
