### ISSUE TITLE
[FEATURE]环境多了以后，增加字段麻烦，期望可以批量增加

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21902]
### MeterSphere 版本

v2.6.1

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

假设项目已经有了 10 个环境（如果小组每个人都有自己的环境，可能会更多），如果需要对环境增加字段就很麻烦，需要每个环境单独编辑添加，期望可以批量添加。

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/4860962/219333596-a8288887-7ae0-4975-a56f-e216c2358244.png)

**Comment by Hyyfit** [comment]
可以具体说明一下是添加什么字段吗？

**Comment by hao1032** [comment]
没有明白你的意思？和什么字段有什么关系？

**Comment by Hyyfit** [comment]
环境里面的东西比较多，是需要批量添加什么？
![image](https://user-images.githubusercontent.com/95834771/219561935-5e6a3a46-a92b-4ee8-8ccd-b63421b28151.png)

**Comment by hao1032** [comment]
明白了，我的需求是这样的：

1.我当前有 10 个环境
2.当前需要增加一个字段“imgUrl"，及其对应的值”http://xxxx.com/pic.png"
3.我需要给所有的环境都加上这个字段，否则用例执行就会有问题
4.当前只能一个一个添加，很麻烦

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4860962/219689269-a046648e-57ff-4716-bab0-2a1e98966b10.png">

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
