### ISSUE TITLE
[BUG] UI 场景b引用了a指令，a修改后编辑b场景，会发现引用的a指令的子步骤里有错乱或者重复的

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21913]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

引用了a指令，然后a如果有修改，  此时编辑b场景，会发现引用的a指令的子步骤里有错乱或者重复的，然后一旦执行，测试报告里重复的就更多了

![611931aba6f8bcdb37892b1dea900a4](https://user-images.githubusercontent.com/83771182/219536503-f019a3b9-3e8d-4411-b8da-0735a50708fb.png)
![9f8410585710e7d62c00e1f9edbe572](https://user-images.githubusercontent.com/83771182/219536524-3db849a7-2ed2-40da-a317-c436aad32860.png)
![cadd570c67b792e42443f10ad3f873d](https://user-images.githubusercontent.com/83771182/219536587-b7646f49-357f-4c60-8364-d4590cf9f068.png)

### 重现步骤

引用了a指令，然后a如果有修改，  此时编辑b场景，会发现引用的a指令的子步骤里有错乱或者重复的，然后一旦执行，测试报告里 重复的就更多了

### 期待的正确结果

测试报告里内容不会重复

### 相关日志输出

```shell
无
```

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.7按您的操作未复现该问题，如果是稳定复现的辛苦提供下场景。
