### ISSUE TITLE
[FEATURE]测试用例模板中自定义的字段，在测试计划、测试报告中高级搜索里面无法显示

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#21919]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

测试用例模板中自定义的字段，在测试计划、测试报告中高级搜索里面无法显示![image](https://user-images.githubusercontent.com/22338833/219557927-81ca5a8b-3e0e-4532-807c-a1299bd6ff96.png)

### 请描述你建议的实现方案

参考测试用例中的高级搜索，可以搜索自定义的字段
![image](https://user-images.githubusercontent.com/22338833/219558205-a17fc9dd-1b7f-45b4-9e33-7a4b244f456a.png)

**Comment by Hyyfit** [comment]
感谢反馈，可以支持的，后续版本会更新这个功能。
