### ISSUE TITLE
[BUG]上传jar包后引用不到

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#21912]
### 联系方式

张树彬

### MeterSphere 版本

2.5、2.6.1

### 使用外置数据库

否

### 问题描述

经测试在2.5和2.6.1版本，文件管理上传jar包后，接口测试引用找不到jar包；同个jar包在1点几版本时上传到其他项目中，在2.5和2.6.1版本中都可以正常引用到。同个jar包在cloud环境是可以正常引用的。

### 重现步骤

1. 在2.5或2.6.1版本中
2. 上传jar包
3. 在接口测试中引用
4. 结果报错，找不到jar包

### 期待的正确结果

可以正常引用到jar包

**Comment by fit2-zhao** [comment]
并未复现此问题，请检查文件管理中的jar包是否开启应用于接口测试。
<img width="540" alt="image" src="https://user-images.githubusercontent.com/70558837/221072259-4a1f8580-aecd-4700-a9bb-d36837be7f96.png">

**Comment by zhangzhaox** [comment]
请检查文件管理中的jar包是否开启应用于接口测试。   附件功能重构之后  确实存在部分项目失效的情况，按照上述描述重新删除附件 重新上传 并开启用于接口测试   功能OK

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，关闭该issue，如果再次出现请重新提issue，感谢理解和支持～
