### ISSUE TITLE
执行案例的时候希望能够添加截图，以证明其执行结果及状态

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2191]
**请描述您的需求或者改进建议.**
执行案例的时候希望能够添加截图，以证明其执行结果及状态

**请描述你建议的实现方案**
执行案例的时候上传截图

![未命名文件](https://user-images.githubusercontent.com/32027713/115702943-1ce61b00-a39c-11eb-870a-c54b09cff1c4.jpg)

**Comment by xulinde** [comment]
后续版本会支持

**Comment by xulinde** [comment]
评论区可以添加图片

**Comment by xulinde** [comment]
![image](https://user-images.githubusercontent.com/64065190/129653989-c90b738a-c011-4773-afcf-faaf66b1011b.png)
