### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#21911]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

2297310871@qq.com

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/219386665-aa3c1664-fda3-44a0-9363-ea4f6c3b68ca.png)

很多接口或者用例、场景需要通过标签进行分类，标签的个数是固定的、能穷举的，目前标签只能手动输入，希望可以下拉选择。应用场景：比如测试场景需要通过标签来标记是正例还是反例；测试计划根据冒烟测试、回归测试等不同场景可以通过标签来选择不同用例，冒烟测试阶段可能只需要选择正例就足够。

### 请描述你建议的实现方案

标签可以通过自定义枚举，通过下拉选择标签，而不是每次都需要手动输入。

**Comment by xiaochongzi-ling** [comment]
期望接口和用例场景中的标签枚举值支持分别设置：
![图片](https://user-images.githubusercontent.com/23067502/219387851-6bf83cd4-e06e-4238-8506-663cbcbcca43.png)

**Comment by Hyyfit** [comment]
标签的含义就是不限制输入值。您提功能的感觉上更像是自定义字段，接口的自定义字段目前是不考虑做的。

**Comment by xiaochongzi-ling** [comment]
标签本身是不限制输入内容，希望有一个地方可以定义其枚举值，可以下拉选择。也就是可以手动输入，也可以下拉选择进行分组。
