### ISSUE TITLE
[FEATURE]响应体文本框支持拖拽式下拉扩大

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#21927]
### MeterSphere 版本

v2.6.1

### 联系方式

silverleo@163.com

### 请描述您的需求或者改进建议

当前接口相应接口显示框大小固定，当返回内容较多时，只能通过滚动条查看，不够友好。建议 响应体 文本框支持下拉放大，优化使用体验。
![image](https://user-images.githubusercontent.com/2188338/219567992-abeaa6c1-95ea-4bd6-ba22-0c5c931b5b27.png)

**Comment by luty2018** [comment]
感谢建议， 已反馈给交互同学进行改造。
