### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by wxbing2015** [metersphere/metersphere#21939]
### MeterSphere 版本

使用了最新版本

### 联系方式

wxbing@126.com

### 请描述您的需求或者改进建议

请求窗口和响应窗口水平显示需求，操作起来方便，不然老是要滚屏。 

### 请描述你建议的实现方案

无

### 附加信息

无

**Comment by luty2018** [comment]
请进一步详细描述， 一句话的需求不是好需求哦。
