### ISSUE TITLE
[FEATURE]期望接口 path 可以在名称下面显示

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21932]
### MeterSphere 版本

v2.6.1

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

查询接口时不能看到完整的 path，需要鼠标 over 才能看到，非常低效
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/4860962/219588351-72a13d51-fe31-4af7-bc30-da37f324ab1e.png">

### 请描述你建议的实现方案

期望 path 放在名称的下面
<img width="768" alt="image" src="https://user-images.githubusercontent.com/4860962/219591138-590f382f-6279-4bf4-a57d-e1b5b9803410.png">

**Comment by luty2018** [comment]
路径过长的情况依然会存在这个问题， 这里我让交互看看怎么优化

**Comment by hao1032** [comment]
> 路径过长的情况依然会存在这个问题， 这里我让交互看看怎么优化

至少比现在好很多啊

**Comment by luty2018** [comment]
好的， 这个交互优化会放到v3.0

**Comment by luty2018** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/36292514/222060890-b6943010-db0a-428a-b375-e222a5a1baa3.png">
已添加至内部交互优化排期，这边先关闭issue了。
