### ISSUE TITLE
[BUG]  接口模板添加自定义字段，接口定义列表 不能展示。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#21942]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

1. 接口模板添加自定义字段，接口列表不能展示，并且搜索不能搜索。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33945037/219607545-23146c54-ce09-4a85-a48d-9100e0c17727.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/33945037/219607606-e545ae6c-e23f-4dfa-91af-be0e99bf516f.png">

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/33945037/219607754-755cb880-84f8-4a82-95d5-5535d4190320.png">

### 重现步骤

同上

**Comment by fit2-zhao** [comment]
目前的设计就是这样的。
