### ISSUE TITLE
[BUG]文件管理上传jar包时报错Connection has been closed BEFORE response, while sending request body，是否限制了上传文件大小？

### ISSUE THREAD

**Issue by Forilan** [metersphere/metersphere#21947]
### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

否

### 问题描述

文件管理上传jar包时报错：Connection has been closed BEFORE response, while sending request body，上传的jar包大小为153MB，之前上传35MB的jar包没有问题

### 重现步骤

文件管理上传jar包时报错：Connection has been closed BEFORE response, while sending request body，上传的jar包大小为153MB

**Comment by Forilan** [comment]
原因找到了， 因默认容器内存限制为800M, 导致上传大文件时超出容器限制内存大小， 被内核kill。
解决方式：修改docker-compose-project-management.yml文件， 将默认的800m调大， 然后msctl reload

**Comment by xulinde** [comment]
> 原因找到了， 因默认容器内存限制为800M, 导致上传大文件时超出容器限制内存大小， 被内核kill。 解决方式：修改docker-compose-project-management.yml文件， 将默认的800m调大， 然后msctl reload

好的，先关闭该issue，如有问题继续反馈～

**Comment by davidcchen** [comment]
我也遇到这个问题了，如何解决，默认的800m调到1g，也有一样的问题

**Comment by davidcchen** [comment]
mem_limit: ${MS_TRACK_MEM_LIMIT:-4073741824}搞到4个g就可以了
