### ISSUE TITLE
[FEATURE] 优化CASE“执行”按钮位置

### ISSUE THREAD

**Issue by Forilan** [metersphere/metersphere#21948]
### MeterSphere 版本

v2.6.1-2e5b7801

### 请描述您的需求或者改进建议

在编辑用例时， 如果添加了几个前置或后置脚本， 运行该用例每次都要往上滚屏去点击“执行”按钮， 很麻烦。建议将“执行”按钮固定在上面。类似“保存”按钮， 或者添加“执行”按钮的快捷键。

**Comment by luty2018** [comment]
感谢建议， 接口case这里会进行交互升级， 会解决你说的这种情况哈。
