### ISSUE TITLE
[BUG]接口状态为【已完成】，导出成MS格式的文件，新建一个项目再导入，状态变成了【进行中】

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2195]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
接口状态为【已完成】，导出成MS格式的文件，新建一个项目再导入，状态变成了【进行中】

**Bug 重现步骤**
1.  点击【接口测试=》接口定义】
2. 将状态为【已完成】的接口导出为MS格式
3. 新建一个新的项目
4. 再将导出的文件导入

**期待的正确结果**
正确情况下应该是什么样的？
导入后的接口状态与导出前的一致

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/115806788-fcf53c80-a419-11eb-9251-5e93e912f84a.png)
![image](https://user-images.githubusercontent.com/78518076/115806813-07afd180-a41a-11eb-8f97-af870d1b805f.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
最新版已修复
