### ISSUE TITLE
[BUG]功能用例通过excel导入后，列表第一条数据，用例id比第二条数据用例id大

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21953]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

功能用例通过excel导入后，列表第一条数据，用例id比第二条数据用例id大
<img width="906" alt="d9ddff3eab6b3f454505f3d4fac9264" src="https://user-images.githubusercontent.com/55130444/219642360-09944cd3-c3f0-42ff-9155-6d443890fa73.png">

### 重现步骤

1.使用excel模板导入多条数据，excel用例在前面的id反而大

### 期待的正确结果
excel用例从上到下id从小到大，导入平台后期望也是和excel一样，用例id从小到大排
_No response_

**Comment by xulinde** [comment]
未复现该问题，excel方便发下吗？
