### ISSUE TITLE
[BUG]版本升级后，同一个case换了环境执行，控制台会报错。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#21954]
### MeterSphere 版本

v2.6.1 v1.20.15

### 使用外置数据库

否

### 问题描述

1.在1.20.15版本，一个用例可以切换不同的环境，执行结果没有报错。
2.升级到2.6.1之后，相同的用例同样是切换相同的环境，执行后控制台报错。
![feac49c4514cfcd20c9e030ab7dd805](https://user-images.githubusercontent.com/55130444/219645305-7520dea2-b6cf-452c-8dca-1356c827e815.jpg)

### 重现步骤

1.在客户测试环境可以复现

### 期待的正确结果

1.20.15升级到2.6.1之后，执行case可以选择不同的环境都能够执行成功，且控制台没有报错

**Comment by fit2-zhao** [comment]
建议检查一下环境的脚本信息和证书配置是否都正常。

**Comment by fit2-zhao** [comment]
已经确认是用户自定义的环境变量问题，需要检查变量的准确性。
