### ISSUE TITLE
[BUG]通过 jenkins 触发时会一直running ，触发单接口没问题，触发场景就会一直running。在ms里执行没有问题。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#21963]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.19

### 使用外置数据库

否

### 问题描述

通过 jenkins 触发时会一直running ，触发单接口没问题，触发场景就会一直running。在ms里执行没有问题。
ms版本和jenkins插件版本都是1.20.19

### 重现步骤

![ab704fdb70b1d7fa529aacfab063b21](https://user-images.githubusercontent.com/83771182/219829987-7d5dac2d-4cef-4fa9-8ec4-c13ae14e3313.png)
![177cdfb7d2f82c10e1f29b5b4b65836](https://user-images.githubusercontent.com/83771182/219829992-22f3a450-055a-4a81-ad8b-c2ec9f28229c.png)
![98cb807782a6b2e1061de662e8599be](https://user-images.githubusercontent.com/83771182/219829999-62f161d6-8e78-4fc1-9756-ef505f89dfb1.png)

### 期待的正确结果

触发场景可以正常执行

**Comment by youliyuan-fit2cloud** [comment]
你好，未复现该问题。请升级到最新版本试试吧。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，关闭该issue，如果再次出现请重新提issue，感谢理解和支持～
