### ISSUE TITLE
[FEATURE] 有循环嵌套时csv文件读取错乱

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#21970]
### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

当场景内部嵌套循环时，内层循环即使不涉及csv文件，也会影响后面的请求读取正确的csv数值。如：
如果内层循环之前的请求，读取的是csv的第一行，那么该内层循环后续的请求可能会读取csv第二行（甚至遇到过第三、四、五行）

![image](https://user-images.githubusercontent.com/24548477/219874944-6c108afc-23a1-4c12-8521-e060c72a140f.png)

例：
![image](https://user-images.githubusercontent.com/24548477/219875123-a5ff9283-c163-4628-9241-a1fa8d35b6fa.png)

### 重现步骤

1. 创建场景1
2. 场景1的第一个控件为循环控制器，读取csv（次数循环）
3. 循环控制器1下，嵌套引用一个已存在的场景（场景2）
4. 场景2包含一系列请求和一个循环控制器2
5. 循环控制器2 为while循环，通过常量控制循环，该循环不涉及csv文件读取
6. 执行场景1

如图：
![image](https://user-images.githubusercontent.com/24548477/219875377-f10af95b-76a7-4fcf-ad05-36e6a8f15108.png)

### 期待的正确结果

![image](https://user-images.githubusercontent.com/24548477/219874959-20e872c4-9ef4-4b2a-9a65-57a230a5ed9f.png)

如：
![image](https://user-images.githubusercontent.com/24548477/219875196-3bfd77b8-c74f-475b-a7f4-ac40bb2ff177.png)

### 附加信息

花了一天时间进行各种组合验证和排查，阻塞了正常的测试任务，请尽量下一版本修复，谢谢！

**Comment by zyyfit** [comment]
您好，由于目前的场景设计问题，这个场景导出到jmeter中执行也是这样的，暂时不做处理

**Comment by xyziven** [comment]
那是现在不能有任何的循环嵌套？新的设计大概会在什么时候？

**Comment by zhangzhaox** [comment]
@xyziven 目前的平台设计思想，希望主要用函数 更多的传统的csv文件入参，了解下API用例中的嵌套取值场景主要是为了解决什么测试用例实现

**Comment by luty2018** [comment]
v3.0 已解决嵌套使用csv的问题， 可以关注后续发布。
