### ISSUE TITLE
[FEATURE]测试计划关联用例筛选问题

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2197]
**请描述您的需求或者改进建议.**

版本1.8.2
1. 希望能增加用例状态列；可以根据用例状态来过滤（比如只有reviewed的用例）
2. 希望能有模块下用例全选功能；现在有很多页；每次只能1页一页的添加
3. 
**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.下个版本测试用例-高级搜索会新增按评审结果筛选用例
2.目前平台是有这个功能的，如图
![image](https://user-images.githubusercontent.com/64065190/115828799-c2eb6100-a440-11eb-8826-b81020f35d21.png)

**Comment by guhan121** [comment]
@xulinde 我说的是在测试计划中关联场景测试用例

**Comment by guhan121** [comment]
@xulinde 而且建议测试计划新增场景用例的时候能自动帮忙勾上已加入计划的用例
