### ISSUE TITLE
[BUG]插件开发教程不完整

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#21975]
### 联系方式

微信群--MeterSphere 交流群51--tango东

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

按照开发教程不能启用插件

### 重现步骤

1. 在文档底部找到插件 git 地址 https://metersphere.io/docs/v2.x/automation_plugin_dev/
2. 插件 git 地址 https://github.com/metersphere/metersphere-plugin-DummySampler
3. 插件描述中可以去 Releases 下载 jar 包，**实际上没法下载**
<img width="526" alt="image" src="https://user-images.githubusercontent.com/4860962/219932234-37780cbd-0b0c-4e11-a137-2ac5a0a7a1f8.png">
4. clone 代码，然后使用图中的操作打 jar 包，得到 metersphere-plugin-DummySampler-1.0.0.jar
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/4860962/219932313-703cbe83-0874-4cb5-b3cc-ed9777a95c26.png">
5. 上传 jar 包到文件管理
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/4860962/219932365-ea5e7fbf-361f-4f68-87e7-25219d1653f4.png">
6. 接口测试中没有出现期望总的步骤“模拟请求”
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/4860962/219932397-94d71fab-1004-4457-811e-c6584fc57b3b.png">

**Comment by shenkaibo** [comment]
你好，第 5 步上传插件的地方不对，在 系统设置-插件管理下，而不是项目管理的文件管理，这里用来上传 jar 包，csv 等。

**Comment by hao1032** [comment]
插件管理是付费功能吗？ 没有看到啊？
<img width="359" alt="image" src="https://user-images.githubusercontent.com/4860962/219989678-ca331c98-eed1-4530-9778-c39d40b20baf.png">

**Comment by hao1032** [comment]
换了系统账号可以看到插件管理了，但是上传成功没有看到列表中显示啊
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/4860962/219991051-c681575f-4a51-4c1e-88bd-3d7730ab543d.png">

**Comment by shenkaibo** [comment]
![image](https://user-images.githubusercontent.com/30038088/219991288-6b53b63e-4908-4ce8-bf2b-0f674c5a68b5.png)
点击上传，选择 接口测试 插件，然后 上传 插件 jar 包，上传完后 刷新下列表 看看。

**Comment by hao1032** [comment]
Uploading 屏幕录制2023-02-20 09.53.47.mov…

刷新了呢？ 你看看

**Comment by shenkaibo** [comment]
是自己打包的源码么？ mvn package 的需要把依赖包也打进去，比如 metersphere-plugin-ParallelController-1.0.0-jar-with-all-dependencies.jar

**Comment by shenkaibo** [comment]
是自己打包的源码么？ mvn package 的需要把依赖包也打进去，比如 metersphere-plugin-ParallelController-1.0.0-jar-with-all-dependencies.jar

**Comment by hao1032** [comment]
怎么打啊，有命令吗？我就是用开始截图的那个ide 自带的命令打包的

**Comment by hao1032** [comment]
刚使用这个命令，打了一个带依赖的包，size 13K
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/4860962/219995401-bbbcae9b-bc9b-4416-9efb-465fcf6cffe9.png">

<img width="651" alt="image" src="https://user-images.githubusercontent.com/4860962/219995462-04f44ab5-4bdb-4bc2-b73e-d65ca2db3500.png">

但是上传还是没有看到呢

https://user-images.githubusercontent.com/4860962/219995611-67d39107-dcb9-4112-96b3-ab371d388e44.mov

**Comment by shenkaibo** [comment]
mvn assembly:assembly -Dmaven.test.skip=true

**Comment by hao1032** [comment]
使用这个命令编译的 jar 包是 24K，可以上传了
<img width="636" alt="image" src="https://user-images.githubusercontent.com/4860962/219999104-42666b02-d9a2-40cf-b851-298161d69323.png">

但是我添加这个步骤并保存，就报 400
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/4860962/219999646-e9d9edb2-a0a5-442b-aa31-e48879082014.png">

**Comment by hao1032** [comment]
点击 执行也有问题
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/4860962/220000221-251a8640-5fdd-4bef-a631-3f8887f395b4.png">

**Comment by Ycr123888** [comment]
重新上传插件后，需要重启api-test服务呢

**Comment by hao1032** [comment]
msctl restart后可以了，请问有单独重启某个服务的命令吗》

**Comment by shenkaibo** [comment]
msctl reload/restart 容器名（比如：report-stat）

**Comment by hao1032** [comment]
好的感谢。

可以麻烦将教程补充完整吗》
文档：https://metersphere.io/docs/v2.x/automation_plugin_dev/
readme：https://github.com/metersphere/metersphere-plugin-DummySampler

**Comment by shenkaibo** [comment]
好的，感谢反馈!
