### ISSUE TITLE
[FEATURE]接口模板自定义字段之后，查询条件中希望可以显示该搜索条件

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#21985]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

17321336962

### 请描述您的需求或者改进建议

接口模板自定义字段之后，查询条件中希望可以显示该搜索条件
![图片](https://user-images.githubusercontent.com/23067502/219955552-59a9c970-1276-4f6d-8805-12e7d36992d5.png)

![图片](https://user-images.githubusercontent.com/23067502/219955481-8db47f41-fa8e-490a-8154-d847e7f96d42.png)

**Comment by luty2018** [comment]
这里确实还不支持， 预计下半年才会规划。
