### ISSUE TITLE
[FEATURE]“用例评审” 功能 支持 整体评审意见 输入

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#21993]
### MeterSphere 版本

v2.6.1

### 联系方式

silverleo@163.com

### 请描述您的需求或者改进建议

当前 用例评审 功能只能针对 评审任务中的单个用例 提交评审意见。通常情况下，一个评审任务 中的用例是针对某一功能 进行设计，当前模式下，评审人员无法对 测试用例设计 提交整体意见。
建议支持 dui对当前评审的整体意见提交

### 请描述你建议的实现方案
![image](https://user-images.githubusercontent.com/2188338/219997452-2f4d487a-8336-4f35-8d10-68891318894f.png)

**Comment by luty2018** [comment]
可以关注我们2.7以后的版本， 针对评审会出具评审报告，可以添加评审总结
