### ISSUE TITLE
[FEATURE]删除工作空间，建议增加相关风险提示

### ISSUE THREAD

**Issue by shorile** [metersphere/metersphere#22]
**请描述您的需求或者改进建议.**

项目是放在工作空间下，删除工作空间的时候，就会把这个工作空间里面的项目全部删掉。
建议增加相关提示

**请描述你建议的实现方案**

在删除工作空间的弹出确定框中，增加一句"会删除该工作空间中全部项目"的提示

**Comment by wangzhen-fit2cloud** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/metersphere/metersphere/issues/22](https://trello.com/c/f1DOCqaP/405-https-githubcom-metersphere-metersphere-issues-22)

**Comment by wangzhen-fit2cloud** [comment]
已在 v1.0.2 中修复
