### ISSUE TITLE
[BUG] 导入并发控制器插件失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22008]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/103925124/220020386-9b87d4e4-f11f-45c1-8084-94eedcb88317.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/220020386-9b87d4e4-f11f-45c1-8084-94eedcb88317.png)

**Comment by fit2-zhao** [comment]
您好，您当前这个服务版本可以使用 https://github.com/metersphere/metersphere-plugin-ParallelController/releases/tag/v1.0.0 这个插件包，我们测试过未曾发现您的问题。
