### ISSUE TITLE
[BUG]MS对接禅道后，进行飞书消息推送时，无法获取到消息通知

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#22006]
### MeterSphere 版本

V2.6.1 && 1.20.19lts

### 使用外置数据库

否

### 问题描述

在MS对接集成禅道后，进行新建缺陷的消息通知，选择飞书机器人通知。在新建缺陷成功后，飞书群未能获取到消息通知

### 重现步骤

见问题描述

### 附加信息

![2dd0d2c892349820f5feaf7e640872e](https://user-images.githubusercontent.com/92150453/220004131-98b8ae95-bb90-43df-8bd2-85cde5243d15.png)
![b4092f6d6f3e40ee61c48bc00e89820](https://user-images.githubusercontent.com/92150453/220004141-02c8b445-8f54-46ec-8f66-b9fd38d443b6.png)
![06e1c81f18fe4b186fddf0d71e145fa](https://user-images.githubusercontent.com/92150453/220004161-e8681619-0226-4868-b469-7d58b0593175.png)

**Comment by xulinde** [comment]
未复现该问题，检查下处理人手机号是否正确
![image](https://user-images.githubusercontent.com/64065190/220809745-a924eea3-3532-4f6e-9073-f7e451cad505.png)
