### ISSUE TITLE
[BUG] 模拟请求插件导入metersphere报错，导入失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22009]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/103925124/220021567-7d49899f-0680-4f39-b35b-66142062d029.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/220021575-131c6354-1846-4dff-ba06-487e9927aaf6.png)

**Comment by fit2-zhao** [comment]
这里的插件需要按照我们插件二开标准去编写才行，具体可参照官方文档和github上我们开源的插件：https://metersphere.io/docs/v2.x/user_manual/plugin_use/api_test_plugin/?h=%E6%8F%92%E4%BB%B6
