### ISSUE TITLE
[BUG]API请求参数开启json-schema的情况下， Test之后另存为新用例卡死

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#22012]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

是

### 问题描述

![图片](https://user-images.githubusercontent.com/23067502/220033673-f00953f8-e3bc-4747-9009-dc0cd5a285d8.png)

### 重现步骤

![图片](https://user-images.githubusercontent.com/23067502/220033835-e945e13c-7197-460c-a332-c014d73ec4c1.png)

**Comment by fit2-zhao** [comment]
感谢您的反馈，未曾复现您这种情况，可以f12打开控制台查看一下是否有报错，把相关的错误信息提供一下。

**Comment by panda0120** [comment]
碰到同样的问题

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且最新版本无法复现，关闭该issue，如果升级到最新版本v2.10 版本再次出现请重新提issue，感谢理解和支持～
