### ISSUE TITLE
[BUG]接口测试>>接口自动化测试>>场景变量：上传CSV文件后，刷新页面或者退出场景变量；然后再次进入场景变量，【预览】CSV文件，其内容为空。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22026]
### MeterSphere 版本

V1.20.19-lts

### 使用外置数据库

否

### 问题描述

1、接口测试>>接口自动化测试>>场景变量：上传CSV文件后，点击【预览】能正常显示CSV文件里的信息。
2、刷新页面或者退出场景变量页面；
3、再次进入场景变量，【预览】刚上传的CSV文件，其预览页面内容为空。

### 重现步骤

1、接口测试>>接口自动化测试>>场景变量：上传CSV文件后，点击【预览】能正常显示CSV文件里的信息。
2、刷新页面或者退出场景变量页面；
3、再次进入场景变量，【预览】刚上传的CSV文件，其预览页面内容为空。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/220045466-a16e8652-cbec-491b-9d46-88195ac1faa2.png)

**Comment by fit2-zhao** [comment]
未曾复现您这个问题，是否是csv文件过大这里加载慢的原因呢，或者查看一下是否有相关错误日志提供一下。

**Comment by huangxine** [comment]
csv文件就4列5行数据，不大。
你是在lts版本上尝试的吗？这个问题是必现的

**Comment by youliyuan-fit2cloud** [comment]
> csv文件就4列5行数据，不大。 你是在lts版本上尝试的吗？这个问题是必现的

csv文件方便发出来吗？我们对应版本没有复现。
