### ISSUE TITLE
[BUG] 前置SQL（SQLServer）前加等待控制器，导致到时间后，请求一直不停止

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22025]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.16-lts

### 使用外置数据库

否

### 问题描述

![企业微信截图_16768747275476](https://user-images.githubusercontent.com/103925124/220045054-b5e8de1a-ab12-4fe4-a2cb-4761e0ad2690.png)

### 重现步骤

![企业微信截图_16768747275476](https://user-images.githubusercontent.com/103925124/220045049-482bc2da-8da5-4a66-ac8a-a3ee3738428d.png)
30s可成功，40秒和60秒均为失败
数据库是SQLSERVER，我试了mysql设置60秒是好的

**Comment by fit2-zhao** [comment]
设置一下JDBC的超时时间。

**Comment by Ycr123888** [comment]
设置多久合适呢

**Comment by fit2-zhao** [comment]
> 设置多久合适呢

可以根据您自身得业务需求去设置
