### ISSUE TITLE
[QUESTION]swagger接口导入，之前地址只有一个api,现在有两个api

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#22035]
### 请描述您的问题

![图片](https://user-images.githubusercontent.com/23067502/220061815-1290b05a-d9de-4e6e-abbc-3e314bde85a6.png)

**Comment by fit2-zhao** [comment]
@xiaochongzi-ling 感谢反馈，从v2.3 之后版本采用微服务架构，第一个api 指的是网关路由地址。
