### ISSUE TITLE
[BUG]swagger文件导入格式与预期不符

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#22036]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

是

### 问题描述

导入文件：
![图片](https://user-images.githubusercontent.com/23067502/220062915-d81a8c9d-adff-48ed-8ccc-a61e96bbd4a3.png)

预期结果：
![图片](https://user-images.githubusercontent.com/23067502/220062506-2db1d97b-488f-462e-b692-886ed98faf53.png)

实际结果：
![图片](https://user-images.githubusercontent.com/23067502/220062407-8cb591ce-dc27-428f-8e1e-974bc54d415d.png)

### 重现步骤

按照导入文件内容构造数据进行swagger JSON文件导入。

**Comment by luty2018** [comment]
能否提供导入文件给我们验证一下？

**Comment by xiaochongzi-ling** [comment]
Dear all:
测试文件如上，数据请保密。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]swagger文件导入格式与预期不符 (Issue #22036)





 
能否提供导入文件给我们验证一下？

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们后续版本会优化一下，请关注后续版本发布release note。

**Comment by xiaochongzi-ling** [comment]
Dear all:
上一个测试文件上传成功，存在一个Json文件报解析出错，烦请排查。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "玲子"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午5:29
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [metersphere/metersphere] [BUG]swagger文件导入格式与预期不符 (Issue #22036)





Dear all:
测试文件如上，数据请保密。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]swagger文件导入格式与预期不符 (Issue #22036)





 
能否提供导入文件给我们验证一下？
