### ISSUE TITLE
[BUG]接口定义设置了swagger（有添加请求参数）定时任务，不会自动触发，同样的设置信息手动可以导出。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22044]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

接口定义设置了swagger（有添加请求参数）定时任务，不会自动触发，又加上了失败通知，也没有通知。同样的设置信息手动可以导出。
编辑时认证方式信息没有回显
![616a3633b315e20163f4102948b681a](https://user-images.githubusercontent.com/83771182/220071342-cf97a540-0a05-446e-b162-e7fa75f209bd.png)

![76704e9c5a7177c42b876a172701085](https://user-images.githubusercontent.com/83771182/220070853-f022ee7b-ecf0-4d9c-9db1-649bb8408cdf.png)
[Video_20230220164302.zip](https://github.com/metersphere/metersphere/files/10783087/Video_20230220164302.zip)

### 重现步骤

接口定义设置了swagger（有添加请求参数）定时任务，不会自动触发。见附件视频操作

**Comment by zyyfit** [comment]
1、不会自动触发这个问题没有复现，可能是同步失败了
2、同步失败的消息没提示和认证信息没回显这2个问题复现了

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
