### ISSUE TITLE
 [BUG]测试计划 的执行报告, 在线看单步结果是成功的，但是导出就变成了失败

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22067]
### 联系方式

silverleo@163.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

测试计划 的执行报告，在线看单步结果是成功的，但是导出就变成了失败：
在线看 
![074fc5394d6232edcb874f54cbfe7cc](https://user-images.githubusercontent.com/2188338/220100273-0492cc71-a85e-4821-b316-e18e292513ed.png)

导出为html之后的结果:
![e58cfcfb010c0c91326719e125f2848](https://user-images.githubusercontent.com/2188338/220100350-9c4d8600-b6ee-4883-9e99-b6405ae15fae.png)

### 重现步骤

同上

**Comment by xulinde** [comment]
未复现该问题，建议您升级到最新版本再试下
