### ISSUE TITLE
[FEATURE] 场景用例执行结果报告 需要能够以html文件导出

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22068]
### MeterSphere 版本

v2.6.1

### 联系方式

silverleo@163.com

### 请描述您的需求或者改进建议

场景用例 的测试报告，只能导出 pdf，导出的文件超大，还不便于阅读。希望能像测试计划的报告一样，也导出html

**Comment by luty2018** [comment]
感谢建议， 这块预计下半年整体交互升级后才能规划。

**Comment by yangstones** [comment]
测试计划 的测试报告 已经是可以导出html了，为什么要把场景用例的报告导出为pdf?  把 测试计划 的报告导出功能复制到 场景用例报告的导出 是不是就可以了？
这是一个很常用的功能，目前pdf的导出和阅读特别不友好，建议还是能高优处理一下




在 2023-02-21 10:05:59，"LuoTing" ***@***.***> 写道：

感谢建议， 这块预计下半年整体交互升级后才能规划。
