### ISSUE TITLE
[BUG]【接口定义】【接口自动化】，接口为POST接口，批量添加接口参数后，返回回来的部分数据后存在\r，断言报错

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2206]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
【接口定义】【接口自动化】，接口为POST接口，批量添加接口参数后，返回回来的部分数据后存在\r，断言报错

**Bug 重现步骤**
1.  在系统内按F12将接口入参抓取后赋值到txt文档，然后将:替换为,, 替换后，复制到接口参数的批量添加处
2. 执行接口
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
接口正确执行且返回数据无误

**截图**
如果有截图，请附上截图.

**Comment by HLX99** [comment]
![image](https://user-images.githubusercontent.com/78518076/115813319-8bbb8680-a425-11eb-8813-74864607bc8f.png)
![image](https://user-images.githubusercontent.com/78518076/115813354-99710c00-a425-11eb-8542-fd3f84fa3473.png)
![image](https://user-images.githubusercontent.com/78518076/115813410-b574ad80-a425-11eb-9907-154da9188a60.png)
![image](https://user-images.githubusercontent.com/78518076/115813464-ccb39b00-a425-11eb-9d97-19de3f560c9b.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能把复制的txt文件贴上来或者以附件的形式上传一下吗
