### ISSUE TITLE
[BUG]接口自动化测试上传文件报错

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22073]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

编写上传文件的接口，按要求请求体里面选择file类型，上传文件，保存，调试，报500错误，提示文件没有找到，见图片

### 重现步骤

编写上传文件的接口，按要求请求体里面选择file类型，上传文件，保存，文件已经上传到服务器/opt/metersphere/data/body/d1d8110a-71ba-93e1-1c7e-16c0968be088路径下，调试，报500错误，提示文件没有找到，见图片
[pp.zip](https://github.com/metersphere/metersphere/files/10788802/pp.zip)

### 期待的正确结果

能成功上传，能正常自动化测试上传文件功能

**Comment by fit2-zhao** [comment]
您好，从提供的返回值信息来看应该是 参数名称写错了，您被测系统接收的名称应该不叫” file “，响应信息中已经体现了。

![image](https://user-images.githubusercontent.com/70558837/220227930-6b48fb5e-1ed7-42bb-8335-514205a38942.png)

**Comment by myliuq** [comment]
您好，看抓包的参数名是叫file呢，还有其他原因吗？







雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口自动化测试上传文件报错 (Issue #22073)





 
您好，从提供的返回值信息来看应该是 参数名称写错了，您被测系统接收的名称应该不叫” file “，响应信息中已经体现了。

**Comment by myliuq** [comment]
![test111](https://user-images.githubusercontent.com/39357523/221856542-8237a1fc-532d-4d06-b9fd-7f5b9703a5d0.png)

**Comment by myliuq** [comment]
请问，这个问题有人处理吗？

**Comment by myliuq** [comment]
有人处理这个问题吗？
