### ISSUE TITLE
[BUG]消息中心执行人和执行历史的实际执行人不一致

### ISSUE THREAD

**Issue by hanchenglong001** [metersphere/metersphere#22075]
### 联系方式

微信交流群53 all 　　　 　 　　 　👁_👁　: 

### MeterSphere 版本

 v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

消息中心执行人和执行历史的实际执行人不是一个人。

### 重现步骤

编辑前置脚本访问接口后。

### 附加信息

![image](https://user-images.githubusercontent.com/56539098/220233315-e3743539-8ce3-478a-8c8c-3c227b407e8a.png)

**Comment by fit2-zhao** [comment]
您好，请问你这里的通知是下图的哪一类，如果是@提到我的 是属于正常现象。

![image](https://user-images.githubusercontent.com/70558837/220586273-341cc531-4d0e-4454-b86a-fbedf0625f9a.png)

**Comment by hanchenglong001** [comment]
是系统通知。

**Comment by hanchenglong001** [comment]
图1 是执行历史记录里面我执行的脚本记录。这个是正确的。 
图二是 系统通知里面，写着执行人是其他的人。这个是错误的。

**Comment by youliyuan-fit2cloud** [comment]
你好，我尝试了 不同用户执行接口用例，没有复现，请描述下详细的步骤方便我们进一步排查原因。
1.用户A执行的 接口用例case1 （创建人是谁？）
2.项目设置-消息设置-接口定义-站内信通知是如何设置的 ？截图看看

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，关闭该issue，建议升级到最新的v2.10.0-lts版本，如果再次出现请重新提issue，感谢理解和支持～
