### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by drppsy** [metersphere/metersphere#22074]
### MeterSphere 版本

v2.6.0-068f4f4a

### 联系方式

feta6@qq.com

### 请描述您的需求或者改进建议

希望MeterSphere支持Playwright框架/引擎，Playwright框架/引擎对比selenium还是有不少优势的。稳定、代码简单、不需要driver。
Playwright框架源码在github有47k star，
https://github.com/microsoft/playwright

Selenium框架源码在github为25k star。
https://github.com/SeleniumHQ/selenium

selenium只是有先发优势，Playwright才是趋势。

**Comment by luty2018** [comment]
感谢建议， 我们调研看看
