### ISSUE TITLE
[FEATURE] 访问场景报告URL链接，未跳转到正确项目

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#22082]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

访问场景报告链接，未跳转到正确项目

### 重现步骤

应该在【kaibo】项目下
![image](https://user-images.githubusercontent.com/103925124/220241640-7a8a7ed0-eb53-4a98-be8d-3cbc2dad1a21.png)
报告跳转后，项目和报告不匹配 。
<img width="925" alt="acf91551fce4e2e731eccc5621abceb" src="https://user-images.githubusercontent.com/103925124/220241719-242f4fcd-f1f7-427b-b7f0-6fc469014cd4.png">

**Comment by fit2-zhao** [comment]
没有很明白您的操作方式呀，当前系统中报告只展示当前项目的，对应的跳转也应该是当前项目下的场景，不存在跨项目的操作吧。

**Comment by Ycr123888** [comment]
操作步骤详细说明补充：
1、图1显示：该报告属于【test-xiaoming】项目下
2、复制该报告的url
3、切换项目到【睿鼎】
4、浏览器地址栏访问刚复制的url，显示项目还在【睿鼎】，正确显示应该在【test-xiaoming】项目下

**Comment by Ycr123888** [comment]
我这边不能重新打开，麻烦注意下这个问题

**Comment by youliyuan-fit2cloud** [comment]
你好，这个直接复制URL地址打开的报告链接还不能跳转到所属项目，已转需求，讨论后决定。

**Comment by luty2018** [comment]
v1 已经停止维护了。
