### ISSUE TITLE
[BUG]性能压测报告只统计了主机的压测数量吗？不应该是总计的吗

### ISSUE THREAD

**Issue by xxxxxxdddddd** [metersphere/metersphere#2208]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.8.1

**Bug 描述**
简要描述您碰到的问题
使用主机和子节点一起压测，一共压800，报告只显示400并发结果？？
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？正确的是报告显示总数800
实际只显示了并发400

**截图**
如果有截图，请附上截图.

**Comment by liuruibin** [comment]
会在这个版本中修复

**Comment by zyyfit** [comment]
您好，已在1.9版本中修复了这个问题，目前最新版是1.10.0，请升级使用
