### ISSUE TITLE
【优先级：高】【接口自动化】创建场景时，通过引用添加了接口定义中的用例，但是调整用例的断言后，场景虽然显示成了修改后的，但是执行无效

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2209]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
【接口自动化】创建场景时，通过引用添加了接口定义中的用例，但是调整用例的断言后，场景虽然显示成了修改后的，但是执行无效

**Bug 重现步骤**
1.  点击【接口自动化】，通过【接口定义导入】引用的方式添加接口用例
2. 执行接口，接口执行成功
3. 调整接口定义中该用例下的断言，故意调整成错误的，再执行场景，按理应该执行失败
4. 执行接口，接口仍执行成功

**期待的正确结果**
正确情况下应该是什么样的？
按照修改后的断言，显示对应的结果

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/115824730-f75c1e80-a43a-11eb-8f9f-ca8b97afc814.png)
![image](https://user-images.githubusercontent.com/78518076/115824780-13f85680-a43b-11eb-9f0c-269f1bbf80e6.png)
![image](https://user-images.githubusercontent.com/78518076/115824868-37230600-a43b-11eb-85db-ebd863529bbc.png)

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/2003
