### ISSUE TITLE
[BUG]UI测试，场景中复制指令，指令中设置参数（是函数@string)，场景内循环，每次参数都是同一个值

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22106]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

UI测试，场景中复制指令，指令中设置参数（是函数@string)，场景内循环，每次参数都是同一个值,

### 重现步骤

1.指令中设置参数，
![image](https://user-images.githubusercontent.com/103627487/220300198-e9ba96f5-e917-4ffd-83c3-82bf896c7d2e.png)
2.场景中复制指令，
![image](https://user-images.githubusercontent.com/103627487/220300417-4ff6e211-186b-4d02-9c02-eea1d3ad089e.png)
3.在场景中引用指令参数
![image](https://user-images.githubusercontent.com/103627487/220300706-ae19d92e-f095-4395-bb3d-7dd5bddadf43.png)
3.设置循环，执行报告，发现三次循环取到的是同一个值。
![image](https://user-images.githubusercontent.com/103627487/220300921-e1c60d42-7caf-4775-b83b-59ae84afe046.png)
![image](https://user-images.githubusercontent.com/103627487/220300977-d58dd45f-7926-4469-8204-8708e064538e.png)
[Metersphere_Ui_train_演示 (2).zip](https://github.com/metersphere/metersphere/files/10791789/Metersphere_Ui_train_.2.zip)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。

**Comment by zrfit** [comment]
您好，由于设计原因，整个ui流程是一个js文本，里面的jmeter函数例如${__Random(1,20)} 会在加载jmx时进行计算（仅一次），所以循环中取到的值都是第一次计算获得的，暂时没有好的解决方案，后续进行研发调研，有合理方案后进行优化。
