### ISSUE TITLE
[BUG]【接口定义】处接口请求类型一开始选错了，再次修改后再执行无效

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2210]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
【接口定义】处接口请求类型一开始选错了，再次修改后再执行无效

**Bug 重现步骤**
1.  点击【接口定义=》创建接口】
2. 将接口的基本信息填上，详见图一
3. 接口保存后，创建对应的用例，详见图二
4. 选择环境后执行接口，接口报错，详见图三，这下发现接口类型选错了，修改接口类型为GET 详见图四
5. 保存后，再次执行用例，仍报错，详见图五

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/115825526-22933d80-a43c-11eb-8526-84984b3b8c85.png)
![image](https://user-images.githubusercontent.com/78518076/115825599-3b035800-a43c-11eb-830f-1ee0a7e134b0.png)
![image](https://user-images.githubusercontent.com/78518076/115825661-553d3600-a43c-11eb-9a36-a960aa86530e.png)
![image](https://user-images.githubusercontent.com/78518076/115825715-671ed900-a43c-11eb-94a2-6db0391e90aa.png)
![image](https://user-images.githubusercontent.com/78518076/115825797-8453a780-a43c-11eb-8927-bf144b81b079.png)

**Comment by zyyfit** [comment]
您好，接口用例是不会跟随接口定义变更的，修改接口定义后可以勾选用例左侧的复选框，然后批量修改用例信息
![图片](https://user-images.githubusercontent.com/73461316/115830993-971daa80-a443-11eb-87eb-ad467c3612a7.png)
