### ISSUE TITLE
[BUG]UI测试，场景中复制指令，外部加循环执行报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22105]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

UI测试，场景中复制指令，外部加循环执行报错

### 重现步骤

1.场景中复制指令，在指令外部加了次数循环，点击生成报告执行报错，
![image](https://user-images.githubusercontent.com/103627487/220294788-f1d8190e-8b45-4f68-a836-651281fa31ab.png)
![image](https://user-images.githubusercontent.com/103627487/220292575-3a6a5111-4be5-4520-b3a6-05ba237c2950.png)
2.去掉外部循环，正常执行
![image](https://user-images.githubusercontent.com/103627487/220293229-907c2e97-ce5a-44e5-9e22-283ed6d06491.png)
![image](https://user-images.githubusercontent.com/103627487/220293017-70245751-80bd-42e6-9493-ac1c1be04074.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，后续版本修复。
