### ISSUE TITLE
[BUG]UI测试次数循环下，jmeter随机值函数始终为固定值

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#22107]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

UI测试次数循环下，不管循环几次，jmeter随机值函数始终为固定值

### 重现步骤

1、创建UI自动化场景
2、添加循环次数
3、循环内添加步骤，步骤内使用${__Random(1,99999999)}函数
4、查看结果截图

### 期待的正确结果

每次循环下，都使用不同的参数

### 附加信息

UI场景：
![image](https://user-images.githubusercontent.com/32027713/220304684-3380f0f7-7c8a-4b4c-a906-001e06b090ce.png)

实际参数值
![image](https://user-images.githubusercontent.com/32027713/220304842-95bc3e84-60c0-4908-ac01-dd7aa0986623.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！问题同https://github.com/metersphere/metersphere/issues/22106
