### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#22112]
### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 联系方式

346315670@qq.com

### 请描述您的需求或者改进建议

1、项目环境删除没有二次确认，很容易误删
2、同项目的环境不能添加到一个环境组里

**Comment by luty2018** [comment]
"1、项目环境删除没有二次确认，很容易误删"
这一点我们尽快加上。
”2、同项目的环境不能添加到一个环境组里“
目前的设计确实是这样的。

**Comment by goodboyxzmkk** [comment]
同项目环境可以添加到一个环境组就会方便很多，因为我们项目支持多环境部署window跟linux，希望可以支持

**Comment by luty2018** [comment]
好的， 我们会进一步调研。

**Comment by youliyuan-fit2cloud** [comment]
1、项目环境删除没有二次确认，很容易误删---已优化
2、同项目的环境不能添加到一个环境组里----暂时不支持。
