### ISSUE TITLE
[FEATURE]【接口定义】用例下，建议添加保存全部/一键保存的功能

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2211]
**请描述您的需求或者改进建议.**
场景：因为有时候一个接口下会有十好几条用例，一旦用例需要调整，就得一个个修改，每次修改完一个就得点击一下保存，而且修改后的接着就显示在最上面，改的多了就不知道哪个改了哪个没改，还得重新再点开看看，建议添加一键保存的功能，一起调整完了最后点击一个保存按钮即可

**请描述你建议的实现方案**
添加保存全部/一键保存的功能

**Comment by HLX99** [comment]
![image](https://user-images.githubusercontent.com/78518076/115826574-b74a6b00-a43d-11eb-8beb-c8b78a6c315e.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下
