### ISSUE TITLE
[BUG]在项目管理-文件管理中上传自定义jar包后，在接口自动化脚本中通过前置脚本引用jar包，不生效后台会报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22131]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

[BUG]在项目管理-文件管理中上传自定义jar包后，在接口自动化脚本中通过前置脚本引用jar包，不生效后台会报错
![51d6aebeeea5260589db6525757cbb2](https://user-images.githubusercontent.com/83771182/220367140-e1c9edde-f620-4db2-89f6-3baf10708433.jpg)

### 重现步骤

[BUG]在项目管理-文件管理中上传自定义jar包后，在接口自动化脚本中通过前置脚本引用jar包

### 相关日志输出

```shell
见截图
```

**Comment by fit2-zhao** [comment]
感谢反馈，会在2.7 版本修复。
