### ISSUE TITLE
[BUG]性能测试---资源文件上传后无法删除

### ISSUE THREAD

**Issue by xxxxxxdddddd** [metersphere/metersphere#2213]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.8.1

**Bug 描述**
简要描述您碰到的问题   资源文件上传后无法删除！！

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？可以删除以上传的资源文件

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，资源文件可在【系统设置-项目管理列表-操作-资源文件】中删除
![图片](https://user-images.githubusercontent.com/73461316/115831645-74d85c80-a444-11eb-8f2f-724bd76c391d.png)
