### ISSUE TITLE
[BUG]UI自动化场景，导入指令并编辑后，执行时测试报告上会展示出同一步骤被多次执行的结果记录

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22132]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

UI自动化场景，导入指令并编辑后，执行时测试报告上会展示出同一步骤被多次执行的结果记录
![611931aba6f8bcdb37892b1dea900a4](https://user-images.githubusercontent.com/83771182/220377040-7989d764-f38b-4c3d-9036-209fe7ffeb09.png)
![9f8410585710e7d62c00e1f9edbe572](https://user-images.githubusercontent.com/83771182/220377075-719a3dd3-b2d5-45d2-9bb8-081e677804c2.png)
![cadd570c67b792e42443f10ad3f873d](https://user-images.githubusercontent.com/83771182/220377110-56c50dbd-33d0-45ba-85f8-558c36a3f7d5.png)

### 重现步骤

UI自动化场景，导入指令并编辑后，执行时测试报告上会展示出同一步骤被多次执行的结果记录

### 期待的正确结果

测试报告结果中一个步骤只执行一次

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本未复现该问题，可以将您的场景导出提供下，我们尝试复现。

**Comment by zrfit** [comment]
经沟通，v2.7未再复现该问题。
