### ISSUE TITLE
[FEATURE]postman导入自动化脚本，前置、后置和断言脚本都没了

### ISSUE THREAD

**Issue by czm008** [metersphere/metersphere#22139]
### MeterSphere 版本

v2.5.1-8e5455a0

### 联系方式

cao137883191@126.com

### 请描述您的需求或者改进建议

postman导入自动化脚本，前置、后置和断言脚本都没了

**Comment by luty2018** [comment]
你好， 关于postman的导入确实不支持导入前后置及断言，考虑到解析和转换可能导致其它的问题。
