### ISSUE TITLE
[BUG] 接口响应大小4M，请求卡住不动

### ISSUE THREAD

**Issue by adenzhong** [metersphere/metersphere#22145]
### 联系方式

zjd168@qq.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

否

### 问题描述

接口响应大小4M，请求后一直卡着不动。应该是哪里做了限制。调整了api-test内存为4G也是一样。

### 重现步骤

![image](https://user-images.githubusercontent.com/113604623/220522025-fe85155a-ad8d-4db4-9e46-5a56dcf55759.png)

### 期待的正确结果

放开响应大小设置，让用户可以配置。

### 相关日志输出

```shell
gateway               | 2023-02-22 12:27:11,015  WARN        reactor.netty.channel.FluxReceive: 299 - [8fe9d3b0-4, L:/172.30.10.3:39621 ! R:172.30.10.15/172.30.10.15:8004] An exception has been observed post termination, use DEBUG level to see the full stack: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 10485760 has been exceeded.
```

**Comment by fit2-zhao** [comment]
在 /opt/metersphere/conf/metersphere.properties 添加属性：
spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=自定义大小
