### ISSUE TITLE
[FEATURE]功能用例，建议增加执行历史，便于查看历史用例的通过情况

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#22142]
### MeterSphere 版本

v2.6.1

### 请描述您的需求或者改进建议

参考testlink，建议增加功能测试用例的执行用例历史记录，便于查看用例历史执行情况
![image](https://user-images.githubusercontent.com/22338833/220508125-490ab0c2-d835-4701-a0ab-f4958402b9ce.png)
![image](https://user-images.githubusercontent.com/22338833/220508410-450c7d81-8dc2-46cf-a438-d3d5ea4548b8.png)

### 请描述你建议的实现方案

参考testlink

**Comment by luty2018** [comment]
这个功能在我们新版测试计划有的，请关注我们后续的发布。

**Comment by chyhant** [comment]
请问下，这个功能预计会在什么版本发布呀，谢谢！

**Comment by luty2018** [comment]
v3.0版本

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！

**Comment by chyhant** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
