### ISSUE TITLE
测试用例新版本导出来步骤和预期是没有合并成一个单元格

### ISSUE THREAD

**Issue by 838602256** [metersphere/metersphere#22156]
### MeterSphere 版本

v1.20.x-lts 

### 联系方式

838602256@qq.com

### 请描述您的需求或者改进建议

导出时做个可选项-是否合并步骤

### 请描述你建议的实现方案

导出时做个可选项-是否合并步骤

**Comment by luty2018** [comment]
后续会考虑支持，5月份以后的版本。
