### ISSUE TITLE
[BUG]用例评审，按ID排序，没有效果

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22153]
### MeterSphere 版本

2.5.0

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/25762331/220553454-a033161d-f350-4e55-842f-7365984d5bb4.png)

### 重现步骤

用例评审
点击ID的排序箭头

### 期待的正确结果

按ID升序或降序排列

**Comment by xulinde** [comment]
重复，https://github.com/metersphere/metersphere/issues/21809
