### ISSUE TITLE
[性能测试] 无法进行压测，版本号v1.8.2-b4

### ISSUE THREAD

**Issue by nova17621370317** [metersphere/metersphere#2217]
![image](https://user-images.githubusercontent.com/30234902/115831844-b537da80-a444-11eb-8ddb-560975083078.png)

**Comment by liuruibin** [comment]
1. 检查node-controller日志 /opt/metersphere/logs/node-controller/ 是否有启动容器的日志
2. 检查data-streaming 日志 /opt/metersphere/logs/data-streaming/ 是否有计算结果的日志
