### ISSUE TITLE
[BUG]自动化场景内使用计数器循环，循环次数有误

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2219]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
自动化场景内使用计数器循环，循环次数有误

**Bug 重现步骤**
1.  设置计数器，如图一
2. 使用循环控制器设置如图二
3. 执行接口，结果循环了19次，如图三
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78518076/115833295-7440c580-a446-11eb-97a7-06e1caa17281.png)
![image](https://user-images.githubusercontent.com/78518076/115833360-891d5900-a446-11eb-8870-0841dbe5c7e1.png)
![image](https://user-images.githubusercontent.com/78518076/115833422-9df9ec80-a446-11eb-8239-523ef240825e.png)

**Comment by zyyfit** [comment]
您好，目前系统里 在循环中使用计数器的话，计数器只会取1个值，不会在每次循环的时候增加，所以循环条件一直成立，所以直到超时才停止循环的
