### ISSUE TITLE
[BUG]从脑图里创建的测试用例，在用例数量统计中不展示，且全量导出的文件也缺少这部分用例

### ISSUE THREAD

**Issue by igotyouu** [metersphere/metersphere#22196]
### 联系方式

928815578@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

全部用例应该有728个，但统计这里只显示501个，导出excel也只能导出501个

### 重现步骤

1.通过脑图的方式创建新用例，这种用例就会出现该情况
2.到首页-用例数量统计中，数量不对，缺少脑图创建的那部分用例
3.导出全量用例文件，文件中也缺少脑图创建的那部分用例

### 期待的正确结果

麻烦修复该问题

### 附加信息
![微信图片_20230223113146](https://user-images.githubusercontent.com/98306931/220815752-1b3731e8-1fb1-4d11-a771-ba7be5e53449.png)

![f8f61a9e3e45fd4a62ffe30aa38bd1c](https://user-images.githubusercontent.com/98306931/220815337-088c8828-dd57-4081-835c-92e0b47a9ea1.png)

**Comment by luty2018** [comment]
可以截图看看你在脑图新增的用例吗， 可能没有打标签，没有满足生成用例的条件。

**Comment by igotyouu** [comment]
收到

**Comment by luty2018** [comment]
那我这边先把issue关闭， 如果确认还有问题可以重新打开哈。

**Comment by igotyouu** [comment]
如图，红框的是通过脑图新增的，其它用例是之前列表、或者excel导入创建的，
都没有什么标签呀











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]从脑图里创建的测试用例，在用例数量统计中不展示，且全量导出的文件也缺少这部分用例 (Issue #22196)





 
可以截图看看你在脑图新增的用例吗， 可能没有打标签，没有满足生成用例的条件。
