### ISSUE TITLE
[BUG]客户环境：接口自动化引用case， 修改原case连接超时时间后，刷新接口自动化脚本 对应case的超时时间不显示数据。【本地验证不复现】

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22193]
### MeterSphere 版本

v2.2.1

### 使用外置数据库

否

### 问题描述

问题：接口自动化引用case， 修改原case连接超时时间后，刷新接口自动化脚本 对应case的超时时间不显示数据。【本地验证不复现】

### 重现步骤

1、接口自动化引用case， 并修改原case连接超时时间
2、问题：刷新接口自动化脚本 对应case的超时时间不显示数据。

本地验证不复现，有对应录屏

### 附加信息

https://user-images.githubusercontent.com/43202800/220811769-7d419356-6c2b-47a0-9f5c-dc67931169c6.mp4

**Comment by luty2018** [comment]
每个case的引用都必现吗？把这个case步骤删了重新引用也必现吗？

**Comment by luty2018** [comment]
有修复类似的问题，等1.20.20发布后试试

**Comment by xhy12** [comment]
修改后重新引用case生效，但是再次修改case 点击场景里面的更新按钮不生效

**Comment by xhy12** [comment]
当前版本是2.2.1
