### ISSUE TITLE
[FEATURE]导入用例时，搜索期望可以模糊搜索 path

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#22217]
### MeterSphere 版本

v2.6.1

### 联系方式

微信群--MeterSphere 交流群51--tango东

### 请描述您的需求或者改进建议

搜索 case 有时记不住用例名称，但是对用例对应的 path 有印象，希望搜索可以增加 path

当前 path 不能搜索
<img width="960" alt="image" src="https://user-images.githubusercontent.com/4860962/220847888-c987374b-86c4-43bb-81b3-8269644d142e.png">

只能搜索名称
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4860962/220848309-3526059a-15e4-4f76-a38c-6a13c0e1c42c.png">

**Comment by luty2018** [comment]
这个可以支持，预计下个版本吧。
