### ISSUE TITLE
[BUG]测试计划批内功能用例按照“更新时间”排序，执行批量通过时SQL异常

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#22228]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.18-LTS

### 使用外置数据库

否

### 问题描述

测试计划批内功能用例按照“更新时间”排序，执行批量通过时SQL异常

### 重现步骤

1、测试计划关联功能用例
2、功能用例列表按照更新时间排序
3、多选，执行批量通过
4、报sql异常

### 附加信息

页面报错：
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/32027713/220880403-b2bcf76c-5b4b-4184-91b9-0c4666a4c32b.png">

日志报错：
![image](https://user-images.githubusercontent.com/32027713/220880170-e29bdc3b-267e-4ec6-9a2c-dbc9d902ac5f.png)

**Comment by xulinde** [comment]
v1.20.20-lts已修复
