### ISSUE TITLE
[FEATURE]性能测试报告导出为PDF后，PDF的监控详情里面没有添加的其他服务器监控信息

### ISSUE THREAD

**Issue by zhushiqiao** [metersphere/metersphere#22223]
### 联系方式

微信群53，邮箱370458034@qq.com

### MeterSphere 版本

v1.20.19-lts-b1

### 使用外置数据库

否

### 问题描述

将性能测试报告导出为PDF后，PDF文档中的监控详情部分，只包含了默认的压力机监控数据，没有包含添加的其他服务器监控内容
![a97379b043615440d895ae43e413f00](https://user-images.githubusercontent.com/48430451/220857040-0bc60616-da34-4c44-bc4b-118c2e6fc8e6.png)
![dc529888a2adfed88817696b974764e](https://user-images.githubusercontent.com/48430451/220857054-17f52014-895a-476c-a793-d53707a206c9.png)

### 重现步骤

1、在创建性能测试时，在高级配置中添加其他服务器监控
2、完成性能测试后，在测试报告中点击导出报告按钮，然后查看导出的PDF文档

### 期待的正确结果

导出的PDF文档中，监控详情部分，应该包含所有服务器监控信息，而不仅仅展示默认的压力机监控内容

**Comment by liuruibin** [comment]
您好，关于导出pdf这里，现在采用的方式是利用浏览器截屏来实现的。这个导出功能会在3.0版本中讨论如何实现
