### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by limin-fit2** [metersphere/metersphere#22237]
### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

测试计划执行成功后，邮件发送功能存在部分字段未解析
<img width="839" alt="image" src="https://user-images.githubusercontent.com/61964761/221105745-b26247d6-7048-4c17-9376-893c67ce92fb.png">

### 重现步骤

测试计划执行成功后，邮件发送功能存在部分字段未解析
![Uploading image.png…]()

**Comment by zyyfit** [comment]
您好，最新版2.7.0已经修复了这个问题，请升级后使用
![image](https://user-images.githubusercontent.com/73461316/221155654-5eb642d8-47ad-46a2-8861-1bbf9af4f68e.png)
