### ISSUE TITLE
[BUG]用例评审，超过截止时间，状态未变成已结束

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22236]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

用例评审，超过截止时间，状态未变成已结束

### 重现步骤

1.创建用例评审，评审用例
2.超过截止时间之后，查看评审状态，发现评审状态未变成已结束
![image](https://user-images.githubusercontent.com/103627487/221097271-4ad9fe19-21eb-4399-bd9d-263bbb1d14c4.png)

### 期待的正确结果

超过截止时间，评审状态变成已结束

**Comment by zyyfit** [comment]
跟这个是一个问题 https://github.com/metersphere/metersphere/issues/22235
