### ISSUE TITLE
[BUG]用例评审，未达到截止时间，状态变成了已结束，

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22235]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

1.用例评审，未达到截止时间，状态变成了已结束，经测试发现，当用例评了未通过，用例评审状态会变成已结束

### 重现步骤

1.创建用例评审，关联用例，评审用例，有用例评审结果为未通过
![image](https://user-images.githubusercontent.com/103627487/221095968-6a0303f9-920f-47a6-8f0f-250137ae8102.png)
2.查看评审结果，状态变成已结束，还未到截止时间
![image](https://user-images.githubusercontent.com/103627487/221096087-7b3a4f45-f87c-4d7c-888e-15e7ebb549f4.png)

### 期待的正确结果

超过截止时间才会变成已结束，与评审结果无关

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.20.20 版本已修复，请等待版本发布后验证

**Comment by meijieDouDou** [comment]
1.20.20 试了，未达到截止时间，一人评论，用例评审状态就变成了已结束
![通过](https://user-images.githubusercontent.com/103627487/223343229-c94fbac0-a378-460c-beca-dc5b4dc0e149.png)
![已结束](https://user-images.githubusercontent.com/103627487/223343309-9269c263-6f62-4682-b02c-92923f8b9951.png)
