### ISSUE TITLE
[QUESTION]接口自动化执行速度很慢

### ISSUE THREAD

**Issue by baisimon** [metersphere/metersphere#22232]
### 请描述您的问题

同一个脚本循环SQL查询 第一次执行很慢 后面都很快. 
![image1](https://user-images.githubusercontent.com/44863622/221077407-aa94a64e-561c-45a1-b364-501b7da1bc42.png)
![image2](https://user-images.githubusercontent.com/44863622/221077410-4336f99b-34a4-4450-9a5d-c7ac4a224457.png)
(每个有关于查询SQL的任务都很慢 单任务手动运行的话至少也都得几秒钟)
![image3](https://user-images.githubusercontent.com/44863622/221077887-e8cc46ae-6a14-4e08-ab64-88c00f611907.jpg)

自查数据库无问题 查询都毫秒级返回
自查服务器配置 进行升配到16C32G 速度也没变化

**Comment by fit2-zhao** [comment]
请问用的是什么数据库，数据库的版本又是什么？方便的话把JDBC 连接配置也贴出来看一下；第一次慢后续快，应该和数据库缓存有关。

**Comment by baisimon** [comment]
目标数据库与版本:MySQL5.6
JDBC连接配置:
![image4](https://user-images.githubusercontent.com/44863622/221143531-6a1184bb-31d5-4a19-9c8f-8cbb344b4d05.jpeg)
这些SQL不通过服务去查询  使用命令行 不管怎么查 结果都是毫秒级返回的。

**Comment by fit2-zhao** [comment]
第一次请求是会比后续慢一些，但大多情况都是毫秒级响应，如果您的请求都是几千毫秒，建议从网络层面检查一下。

**Comment by fit2-zhao** [comment]
第一次建立连接是会慢点，你可以尝试把数据库连接数给大些试试看。

**Comment by baisimon** [comment]
100已经是能设置的最大连接数了。 第一次建立连接的话 这个连接速度慢的问题能优化吗？

**Comment by fit2-zhao** [comment]
这个速度应该是和环境有一定关系，目前我们测试过多个数据库，第一次连接大概都在 1s 以内
![image](https://user-images.githubusercontent.com/70558837/223377137-cff4eddd-17b0-4864-9ba9-4985811fba92.png)

**Comment by baisimon** [comment]
这个环境指的是什么呢？ 能否具体一些 我们好进行排查。
我们也尝试过更换环境测试效果  在云平台购买16C32G的服务器进行部署测试 大概就快了2S左右 连接的速度不能优化到1S以内。是否还有其他的原因 目前没有排查的头绪 这样的连接速度 跑任务需要等待的时间太长了

**Comment by baisimon** [comment]
已找到问题来源。 一开始我们的数据库最大连接数是100
改为0后 执行速度变为毫秒。 但我看对端mysql的连接数没有打满的 是不是metersphere配置连接数后会产生什么BUG?
