### ISSUE TITLE
[BUG]测试计划勾选自动更新状态实际未生效

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#22238]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

测试计划勾选自动更新状态实际未生效

### 重现步骤

1、创建测试计划，勾选自动更新状态
![image](https://user-images.githubusercontent.com/35896106/221110408-413b66b7-d5ef-4577-b1bb-8b3798bb2400.png)
2、关联功能用例，勾选同时添加关联测试的用例（功能用例里已经关联了接口用例）
![image](https://user-images.githubusercontent.com/35896106/221110677-2485ee33-8506-4dcf-a985-2a7537700b8d.png)
3、执行测试计划，发现接口测试已经执行完成，但是对应的功能用例状态没有改变 
![image](https://user-images.githubusercontent.com/35896106/221110922-a7298417-8aaf-4165-8405-1ca50ba476ce.png)
![image](https://user-images.githubusercontent.com/35896106/221110962-5da61ead-2269-47cd-8ce2-b1a01d746dee.png)

### 期待的正确结果

当接口用例状态为成功时，功能用例状态也自动变成功

**Comment by zrfit** [comment]
已知问题，同https://github.com/metersphere/metersphere/issues/21460
后续版本修复。
