### ISSUE TITLE
[BUG]新建API keys页面不显示

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#22243]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

新建API keys页面不显示

### 重现步骤

1、点击个人信息
![image](https://user-images.githubusercontent.com/35896106/221115168-6756fcc1-afa1-4dc3-95fe-ab9c5bf8a7a4.png)
2、点击创建API keys，弹窗提示保存，实际页面上看不到
![image](https://user-images.githubusercontent.com/35896106/221115204-e8f61724-bca0-47f2-b2ea-49a5539ceba3.png)
3、查看数据库发现已经创建成功
![image](https://user-images.githubusercontent.com/35896106/221115440-97864f9c-f626-4cb3-be4f-99f195588926.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！后续版本修复。

**Comment by zrfit** [comment]
您好，v2.7.1已修复该问题，待发布后可升级验证。
