### ISSUE TITLE
[BUG]从脑图里创建的测试用例，在用例数量统计中不展示，且全量导出的文件也缺少这部分用例

### ISSUE THREAD

**Issue by igotyouu** [metersphere/metersphere#22246]
### 联系方式

928815578@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

全部用例应该有728个，但统计这里只显示501个，导出excel也只能导出501个

### 重现步骤

1.通过脑图的方式创建新用例，这种用例就会出现该情况
2.到首页-用例数量统计中，数量不对，缺少脑图创建的那部分用例
3.导出全量用例文件，文件中也缺少脑图创建的那部分用例

### 期待的正确结果

麻烦修复该问题

### 附加信息

![微信图片_20230223113146](https://user-images.githubusercontent.com/98306931/221116608-4aed8721-3a49-47e2-81d5-402db73f54a1.png)
![微信图片_20230223112333](https://user-images.githubusercontent.com/98306931/221116645-b09b1de6-2e5b-4344-a7c3-a7f2d0db18d5.png)
![微信图片_20230223122227](https://user-images.githubusercontent.com/98306931/221116678-15058041-c502-4aca-ac1a-3961281f0ce5.png)

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/221131327-658ae536-bcb1-4c3d-a5ae-a122267fbcd5.png)
![image](https://user-images.githubusercontent.com/36292514/221131441-887b5ab4-5aae-4204-95f9-1a4bfed7170d.png)
<img width="718" alt="image" src="https://user-images.githubusercontent.com/36292514/221131552-631cf33f-ac01-4b92-81d6-2071bdd0eda7.png">
![image](https://user-images.githubusercontent.com/36292514/221131663-15533fc6-ad76-4f26-b8b8-056e3d40f82f.png)
没有复现你说的问题哦。

**Comment by igotyouu** [comment]
真的是奇怪了，又试了下，不止脑图，普通列表创建的也统计不到

![微信图片_20230224174101](https://user-images.githubusercontent.com/98306931/221145478-1fa1088f-a232-4175-8cfa-9966cbadccef.png)

**Comment by xulinde** [comment]
> 真的是奇怪了，又试了下，不止脑图，普通列表创建的也统计不到
> 
> ![微信图片_20230224174101](https://user-images.githubusercontent.com/98306931/221145478-1fa1088f-a232-4175-8cfa-9966cbadccef.png)

方便录屏看下您操作吗

**Comment by igotyouu** [comment]
收到

**Comment by 13290445582** [comment]
建议升级到最新版，如果再次出现请重新提issue，感谢理解和支持～
