### ISSUE TITLE
[BUG] 同样的接口场景，环境也一模一样，MS两个版本，2.2.1和2.6.2  ，2.2.1执行成功，2.6.2执行失败。 链接oracle数据源

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#22242]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

企业客户，MS两个版本，分别是2.2.1和2.6.2。
环境一直，数据场景一直。
链接oracle数据源
2.2.1执行成功。2.6.2执行失败

![image](https://user-images.githubusercontent.com/33945037/221113062-581c8136-6cc9-42e6-93ab-cf60fcda7af6.png)

![image](https://user-images.githubusercontent.com/33945037/221113104-76c5c5e4-2e5d-47c8-8653-b83dcac6174b.png)

### 重现步骤

同上

**Comment by fit2-zhao** [comment]
先把连接数改大点，后续版本优化一下连接占用情况。

**Comment by youliyuan-fit2cloud** [comment]
该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
