### ISSUE TITLE
[FEATURE] 总的接口覆盖率统计

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#2224]
**请描述您的需求或者改进建议.**
当前接口覆盖率统计是按单接口和场景分开统计的，作为PMO和管理人员，同时关心总的接口覆盖率，无论是在单接口用例还是场景用例中覆盖的。
比如：总共500个接口，想知道有多少比率是被覆盖的，不管是是在单接口用例还是场景用例中覆盖到的。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by xulinde** [comment]
1.10已实现
