### ISSUE TITLE
[FEATURE]集成开源网络测试仪dperf怎么样？

### ISSUE THREAD

**Issue by pengjianzhang** [metersphere/metersphere#22256]
### MeterSphere 版本

v1.20.x-lts 

### 联系方式

pengjianzhang@gmail.com

### 请描述您的需求或者改进建议

dperf是目前性能最高的网络测试仪，几乎所有中国的大厂都在使用，
问一下，metersphere有集成dperf的想法或计划吗？

https://github.com/baidu/dperf

### 请描述你建议的实现方案

没有

### 附加信息

没有

**Comment by luty2018** [comment]
非常感谢你的建议，但是我们系统目前还有很多需要完善的地方，所以暂时还没有计划做这一块的集成。

**Comment by pengjianzhang** [comment]
祝metersphere项目越来越好！也请向周围的朋友推荐一下dperf项目，谢谢！
