### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yi447780897** [metersphere/metersphere#22251]
### 联系方式

52群

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

2.6.1升级至2.7.0后docker无进程，服务无法启动

### 重现步骤

2.6.1升级2.7.0
查看docker进程显示为空

### 期待的正确结果
dockers及ms相关服务正常启动
_No response_

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #22267 请参考 该问题，升级下docker，谢谢～
如果还会遇到问题，请重新打开issue。
