### ISSUE TITLE
[FEATURE]接口自动化：后置json提取希望实现能提取随机一个数据，同jmeter的后置json提取

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22257]
### MeterSphere 版本

V1.20.18-lts

### 联系方式

15927004063

### 请描述您的需求或者改进建议

接口自动化：后置json提取希望实现能提取随机一个数据，同jmeter的后置json提取

### 请描述你建议的实现方案

接口自动化：后置json提取希望实现能提取随机一个数据，同jmeter的后置json提取，如图
[pic.zip](https://github.com/metersphere/metersphere/files/10822382/pic.zip)

**Comment by luty2018** [comment]
感谢建议， 这个我们计划放到v3.0

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
