### ISSUE TITLE
[FEATURE] 测试用例列表交互优化建议：用例展示拥挤，全选不展示用例勾选数量，脑图图标不醒目不好找，建议调整

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22255]
### MeterSphere 版本

v2.7

### 使用外置数据库

否

### 问题描述

测试用例列表交互优化建议：用例展示拥挤，全选不展示用例勾选数量，脑图图标不醒目不好找，建议调整 。见截图

### 重现步骤

![脑图图标看着不像脑图 不醒目](https://user-images.githubusercontent.com/43202800/221133931-a3b4d175-c3ba-4276-a071-f03ff249f653.png)
![全选数据也不显示选择多少条了](https://user-images.githubusercontent.com/43202800/221133929-f070c4eb-6ef6-48e3-86bb-e982610cd0d2.png)
![Uploading 小屏幕滚动条太多了，看起来很拥挤.png…]()

**Comment by xhy12** [comment]
![小屏幕滚动条太多了，看起来很拥挤](https://user-images.githubusercontent.com/43202800/221134744-e844ffa5-b56f-4212-b578-77a59935b226.png)

**Comment by luty2018** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/36292514/221526847-418a9565-b85e-409b-af57-a03b790c2460.png">
条数在这里显示
