### ISSUE TITLE
[BUG]测试跟踪-用例详情-版本对比-关联测试用例，列表显示不全

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22262]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.7

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/30038088/221354530-a53eb1aa-3e1e-4b14-b557-84db22876832.png)

### 重现步骤

测试跟踪-用例详情-版本对比-关联测试用例，查看列表，显示不全。

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题为已知问题，后续版本修复。
