### ISSUE TITLE
[BUG]测试报告里未能体现各个执行人分配的任务执行进度

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#2226]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
测试报告里未能体现各个执行人分配的任务执行进度
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
测试报告能体现各个执行人分配的任务执行进度情况
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，后续版本会考虑这方面的需求
