### ISSUE TITLE
[BUG] 测试计划，报告里面，失败重跑，之前失败的已经跑成功了，但是状态没有改变

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#22264]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

v2.6.2

### 使用外置数据库

否

### 问题描述

如图所示，
执行的时候，没有设置失败重跑，执行完成之后，报告中看到失败的，然后点击失败重跑，
![image](https://user-images.githubusercontent.com/33945037/221361834-bc2a6458-93d9-4b3e-b330-ab0f63bee427.png)

### 重现步骤

经过几次验证，得出结论如下：
测试计划，开启失败重跑，则测试计划执行结果错误很多，单条执行用例或场景都是没有问题的。（串行）

**Comment by fit2-zhao** [comment]
未曾复现，请细化一下复现步骤，如果有错误日志或特殊数据方便的话提供出来。

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
