### ISSUE TITLE
[BUG]编辑功能用例保存后，列表会加载所有用例数据

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#22265]
### 联系方式

张树彬

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

编辑功能用例保存后，用例列表会加载所有用例数据，耗费不必要的资源

### 重现步骤

1. 功能用例-选择某个模块-创建或编辑用例
2. 保存该用例
3. 用例列表会加载出所有用例

### 期待的正确结果

只加载当前模块用例

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.7不存在该问题，新建或者编辑用例保存后在当前用例页面刷新，建议升级到最新版本。
