### ISSUE TITLE
[BUG]自定义监控数据无法显示，并且会在刷新后消失

### ISSUE THREAD

**Issue by RunInSpace-Wei** [metersphere/metersphere#22261]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

配置了两项自定义监控数据：
![image](https://user-images.githubusercontent.com/87799321/221192815-78bc419a-cd67-402d-a99e-12476634911e.png)
性能测试结束后左边列表显示了7项监控数据，但图表只显示了4项：
![image](https://user-images.githubusercontent.com/87799321/221193407-7fb2e2aa-5022-4c53-9e46-1a16cd2e593c.png)
刷新网页，重新进入监控详情页面后，左边自定义的两项指标消失了，图表显示了metersphere自带的5项指标：
![image](https://user-images.githubusercontent.com/87799321/221194140-e952c15f-631d-43e9-8a1c-c3c56e5fc0dd.png)

### 重现步骤

问题描述中出现的问题一直存在，可多次重现

**Comment by youliyuan-fit2cloud** [comment]
你好，根据截图中的信息推测是写的promQL 语法不对所以获取不到监控数据，需要自行研究一下官方文档如何写promQL。
很抱歉，目前我们也没办法给出所有要查询的数据promQL ，感谢您的理解和支持。
参考链接：https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by RunInSpace-Wei** [comment]
> 你好，根据截图中的信息推测是写的promQL 语法不对所以获取不到监控数据，需要自行研究一下官方文档如何写promQL。 很抱歉，目前我们也没办法给出所有要查询的数据promQL ，感谢您的理解和支持。 参考链接：https://prometheus.io/docs/prometheus/latest/querying/basics/

谢谢
