### ISSUE TITLE
Jmeter脚本一个接口定义带四个接口case，导入到MS中只存在一个接口case,造成数据丢失。

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22266]
### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

前使用的是1.20.8-lts版本，在本地Jmeter上编辑接口定义和多个case，一个接口定义对应多个接口case可正常导入MS，升级到1.20.19-lts版本后，导入时只能导入一个接口定义和一个case，造成数据丢失。
一：1.20.8-lts 导入截图：
<img width="1397" alt="截屏2023-02-26 下午10 44 20" src="https://user-images.githubusercontent.com/34637801/221417551-8d1f2449-1841-495a-87af-6f3a59f785a5.png">
<img width="1396" alt="截屏2023-02-26 下午10 44 02" src="https://user-images.githubusercontent.com/34637801/221417519-3d69fe47-5e1a-4e05-abd0-59835b7a95bf.png">
<img width="1167" alt="截屏2023-02-26 下午10 45 09" src="https://user-images.githubusercontent.com/34637801/221417592-1941a882-3f72-4076-9f4d-6b9e5b09b725.png">
二：1.20.19-lts 导入截图：
<img width="1251" alt="截屏2023-02-26 下午10 46 07" src="https://user-images.githubusercontent.com/34637801/221417664-2ce2ae82-447f-4fd6-96a9-8d3172c9a2aa.png">

### 重现步骤

1.准备1.20.8-lts和1.20.19-lts
2.分别导入jmeter（一个线程组，多个case）脚本
3.采用"覆盖"模式导入。

### 期待的正确结果

1.20.19-lts 能正确导入"一个接口定义多个case"

**Comment by xiaomeinvG** [comment]
JMeter 用例实际上都是接口请求，因此ms系统会统一处理成接口定义，并为接口生成一个默认用例

**Comment by pengzhengyou** [comment]
但是这个1.20.8 LTS版本可以将其处理为一个接口定义 多个接口case
