### ISSUE TITLE
测试用例编辑页面，保存退出回到用例列表主页面的设计容易造成“是否已保存”的疑惑

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22268]
### MeterSphere 版本

2.7.0

### 请描述您的需求或者改进建议

目前2.7版本用例编辑完了后，会自动保存，但是退回到用例列表页面目前是一个"回退按钮"，不太符合常见的编辑页面设计，容易造成“是否已保存”的疑惑
<img width="1178" alt="截屏2023-02-26 下午11 28 51" src="https://user-images.githubusercontent.com/34637801/221420105-b3eb6ec5-a2f6-458a-aa02-ff1e7d7793f2.png">

### 请描述你建议的实现方案

建议提供“保存按钮”或者“用例列表”按钮

**Comment by luty2018** [comment]
这个会删掉。
