### ISSUE TITLE
[FEATURE] online 安装时候，关于各个容器的名字

### ISSUE THREAD

**Issue by StringKe** [metersphere/metersphere#22279]
### MeterSphere 版本

v2.7.0

### 联系方式

authemail(at)qq.com

### 请描述您的需求或者改进建议

安装脚本中所有 docker-compose 配置的 container name 应该增加一个前缀，不与当前 docker 容器内的其他容器冲突。

比如 我现在有一个叫做redis的容器了，metersphere 的安装脚本会创建同名的容器，会失败

其次，容器创建失败，没有退出安装流程。

**Comment by StringKe** [comment]
同时也建议，安装脚本，先检测 install.conf 中配置的所有端口是否存在冲突

**Comment by liuruibin** [comment]
我们不建议同一台机器上安装多个不同产品，这样会不仅会导致容器重复，也会增加维护成本。

**Comment by StringKe** [comment]
我在本地测试，开发环境下的，存在多个是很正常的行为吧？

**Comment by liuruibin** [comment]
既然开发环境，DIY程度很高，您可以先下载安装包，修改yml里的容器名称安装即可
