### ISSUE TITLE
功能用例评审"多人评审"，一人评审完成后，整个评审成为“已结束”的状态

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22272]
### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

功能用例评审"多人评审"，一人评审完成后，整个评审成为“已结束”的状态
评审列表截图：
<img width="747" alt="截屏2023-02-27 上午11 00 38" src="https://user-images.githubusercontent.com/34637801/221463029-e10632be-b6e9-4f92-875d-8e690ff3437b.png">

### 重现步骤

1.编写多个测试用例。
2.创建一个测试用例评审，选择"全部通过"，选择多人评审。
3.使用一个账户，进行全部评审。
4.转入用例评审列表查看对应的"状态"。

### 期待的正确结果

用例评审状态为”进行中“

**Comment by youliyuan-fit2cloud** [comment]
你好，这里的“已结束” 状态是指 该用例评审的到了 “截止时间”，即自动变更为 “已结束”，和测试用例的评审结果没有关联关系。
测试用例的评审结果和“已完成”状态有直接关系，用例被所有评审人 评审了之后才会是“已完成”。
请确认是否是以上情况，如果仍有问题请重新打开issue。

**Comment by pengzhengyou** [comment]
不是的 多人评审 一个评审选择通过或者不通过 都会结束掉 
<img width="1372" alt="截屏2023-03-02 上午9 59 02" src="https://user-images.githubusercontent.com/34637801/222311235-1bb586b8-3d9c-4f13-8031-a3cb865f1349.png">
<img width="836" alt="截屏2023-03-02 上午9 59 46" src="https://user-images.githubusercontent.com/34637801/222311345-1921327b-0152-4120-b2c5-d4320d51e8da.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，如果是批量编辑用例然后评审通过，用例会强制标记为通过。
其他问题 v2.8.0 中已修改，请升级一下吧～
