### ISSUE TITLE
[BUG]缺陷管理导出，高级搜索进行筛选后导出，导出的是全部用例而不是筛选后的用例

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#22273]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v2.4.1&v2.6.1

### 使用外置数据库

否

### 问题描述

缺陷管理进行缺陷的导出，高级搜索进行搜索到部分数据，选择导出所有数据，导出的是全部缺陷数据而不是筛选后的缺陷数据。

### 重现步骤

1、缺陷管理进行高级搜索
2、导出选择所有数据
3、导出

### 期待的正确结果

期待导出选择所有数据的那个“共2条”可以优化

### 附加信息

![image](https://user-images.githubusercontent.com/45786766/221463131-922b325a-6e3b-40f5-a035-a4fb766f8b36.png)
![image](https://user-images.githubusercontent.com/45786766/221463496-9e45d20b-cf28-4350-941c-68f7c0566d8e.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，后续版本修复。

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，后续版本修复。
