### ISSUE TITLE
功能用例变更记录“变更前记录”和“变更后记录”希望可以在同一个弹窗页面展示，比较好做信息对比

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22271]
### MeterSphere 版本

v2.7.0

### 请描述您的需求或者改进建议

功能用例变更记录“变更前记录”和“变更后记录”希望可以在同一个弹窗页面展示，比较好做信息对比,目前只能单独点开一个查看，且是英文展示，可读性比较差。
<img width="740" alt="截屏2023-02-27 上午10 56 33" src="https://user-images.githubusercontent.com/34637801/221462519-7ca6029c-1c39-4af5-a9ee-33660e1c6170.png">
<img width="1373" alt="截屏2023-02-27 上午10 56 00" src="https://user-images.githubusercontent.com/34637801/221462445-e0b0c45a-5462-4f40-bccf-1a43879653c8.png">

### 请描述你建议的实现方案

1.建议变更字段以中文描述展示。
2.建议可以同时打开变更前详情和变更后详情，便于对比。

**Comment by luty2018** [comment]
版本对比才是全文对比
