### ISSUE TITLE
[BUG] 用例创建人异常变更

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2227]
**MeterSphere 版本**
1.9.0

**Bug 描述**
用例创建人在用例review后更新了用例状态、调试操作、查看场景变量操作触发保存之后就会变为当前操作的人。

同时 缺少最后更新人

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
创建人 创建时间
更新人 更新时间
看样子要加列；才能为后期用例更新日志做铺垫

**Comment by zyyfit** [comment]
您好，在1.9.2版本没有复现这个问题，目前最新版是1.10.0，请更新到最新版试一下
