### ISSUE TITLE
[BUG]接口自动化定时任务报告结果内容缺失

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#22288]
### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

设置了接口自动化定时任务，任务结束后用例失败，少许用例（偶发，每次都在变），查询失败内容时，error中是空的，但是报告中提示的是存在error，我的每个步骤都是有断言的，最后两步没有打印执行日志

### 重现步骤

正常设置接口自动化定时任务，定时任务结束后打开失败的用例报告

### 期待的正确结果

error能够显示error的日志内容，运行的步骤报告也应该能够显示

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/221487012-b751bd0e-e4f0-48ea-9ad8-fcc01a388f61.png)
error中没有对应信息
![image](https://user-images.githubusercontent.com/40912823/221487348-35eb89b0-8574-48dc-ae0b-75041a0e0b77.png)
运行日志中最后一步是成功的后面的都没日志了
![image](https://user-images.githubusercontent.com/40912823/221487470-3d2199c9-e39c-496b-af34-623a894eecbf.png)
后台日志也没有报错不是脚本问题导致中断

**Comment by youliyuan-fit2cloud** [comment]
你好，目前没有复现该问题，应该和实际场景有关系，是否方便把场景文件和日志详细信息发出来，方便我们进一步排查问题，感谢您的支持～

**Comment by wszbc** [comment]
> 你好，目前没有复现该问题，应该和实际场景有关系，是否方便把场景文件和日志详细信息发出来，方便我们进一步排查问题，感谢您的支持～

场景文件太多了 我有很多嵌套，感觉跟场景本身没啥关系一下，我计划里面关联了200多条用例，有时候会有这种不显示情况，而且每次都会变，比如今天是这两条明天是另外两条，有时候重跑一次也是ok的。我少搞几条再观察下具体情况

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，目前没有复现该问题，应该和实际场景有关系，是否方便把场景文件和日志详细信息发出来，方便我们进一步排查问题，感谢您的支持～
> 
> 场景文件太多了 我有很多嵌套，感觉跟场景本身没啥关系一下，我计划里面关联了200多条用例，有时候会有这种不显示情况，而且每次都会变，比如今天是这两条明天是另外两条，有时候重跑一次也是ok的。我少搞几条再观察下具体情况

好，如果有必现的场景请随时联系我们，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
