### ISSUE TITLE
[BUG]【接口自动化】ForEach循环执行3次-后置脚本断言只取到第一次循环的前置sql值

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#22280]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.6.2

### 使用外置数据库

是

### 问题描述

ForEach循环执行3次-后置脚本断言只取到第一次循环的前置sql值

### 重现步骤

1.创建一个自动化脚本
2.加入循环控制器，并执行3次
3.在循环控制器中添加一个接口
4.在接口上添加前置sql
5.在接口上添加自定义脚本断言，校验前置sql查到的值
6.执行场景

### 期待的正确结果

断言取得是当前循环前置sql的值

### 附加信息

第一次循环
![e19f68c54c5f5692da16fd023dfce47](https://user-images.githubusercontent.com/45531073/221472386-f6b931b7-1a45-4c0f-97fa-aecdc3f78697.jpg)

第二次循环
![image](https://user-images.githubusercontent.com/45531073/221472150-94ce71e1-da86-43d5-ab6e-9c9f43faf1ed.png)

第二次循环结果
![image](https://user-images.githubusercontent.com/45531073/221472208-f492c6b0-764b-45fb-869d-520d109baae2.png)

**Comment by fit2-zhao** [comment]
未曾复现，应该是步骤设计有问题，SQL如果是按列存储 ，后置脚本中验证需使用动态索引方式获取 如：variable_index ; index = 动态值 1,2,3 等。

**Comment by liushuneng** [comment]
前置sql是按列取的，每次循环从数据库随机查到一条数据，然后按列存储名为vc_name，我用后置脚本打印vc_name值是正常的，每次循环值不一样，但是在case脚本断言中，打印vc_name值是第一次循环的

1.脚本打印前置sql查到的vc_name值
![ac75cf54ccb5c9aedc52934b363c52a](https://user-images.githubusercontent.com/45531073/221517432-528703c7-01dc-4388-97a1-7f776606cd66.jpg)
2.脚本断言打印的vc_name值
![fd1a5434aef04a7a707df93ab4246a7](https://user-images.githubusercontent.com/45531073/221517568-d6fa7a0f-4c80-4d1f-82cb-252f44e6f5cb.jpg)
3.每次循环后置脚本打印的值是对的，但脚本断言中打印的是第一次循环的值
![image](https://user-images.githubusercontent.com/45531073/221517727-c07c509e-b76d-400f-b855-1d52a5e8336c.png)
![image](https://user-images.githubusercontent.com/45531073/221517925-12b55f01-60e3-4118-8c56-68a5b53d6ec4.png)

**Comment by fit2-zhao** [comment]
2.7 已经测试正常，如果之前版本有问题就升级到2.7 吧。
