### ISSUE TITLE
v2.10 LTS 版本发布说明

### ISSUE THREAD

**Issue by luty2018** [metersphere/metersphere#22292]
MeterSphere LTS 版本说明：

v1.10-lts：发布时间为 2021 年 5 月 27 日，目前已经停止维护；
v1.20-lts：发布时间为 2022 年 4 月 27 日，目前仅进行必要的安全类 Bug 修复和严重 Bug 修复；
v2.10-lts：发布时间为 2023 年 5 月 25 日，每两周发布小版本，持续进行 Bug 修复和部分功能的有限优化。

**Comment by maninhill** [comment]
GitHub 上面的每个 Issue 要做到有始有终。

**Comment by maninhill** [comment]
到 v2.10-lts 发布时，建议规划的 Milestones 如下：

- v2.7.1
- v2.8.0
- v1.20.21-lts
- v2.8.1
- v2.9.0
- v1.20.22-lts
- v2.9.1
- v2.10.0-lts

**Comment by gaye746560359** [comment]
着重提升可用性。稳定性。对服务器资源占用也进行降低

**Comment by luty2018** [comment]
> 着重提升可用性。稳定性。对服务器资源占用也进行降低

感谢信任与支持，这是我们一直改进的方向！

**Comment by juanmaocxy** [comment]
2.x版本采用了分布式架构，可以通过增加节点的方式提高性能，那定时任务可以改成分布式调度么不然api的服务是不是不能部署多个

**Comment by fit2-zhao** [comment]
> 2.x版本采用了分布式架构，可以通过增加节点的方式提供高性能，那么指定时间任务可以改成分布式调度那么不能的api的服务多不是不能

感谢反馈，定时任务从v1 版本到v2 版本都是使用Quzartz，而Quzartz自身是支持集群的，如果部署多个api服务，那么对于一个任务而言也是只会分配给一个服务去执行。

**Comment by juanmaocxy** [comment]
> 

感谢解答，api多节点部署之后应该会稳定很多

**Comment by fit2-zhao** [comment]
Quzartz集群方案则是多个api服务使用的是同一个数据库，通过在数据库中配置定时器信息， 以数据库悲观锁的方式达到同一个任务始终只有一个节点在运行，各个Quartz服务器都遵守基于数据库锁的调度原则，只有获取了锁才能调度后台任务，从而保证了任务执行的唯一性。

**Comment by JFRabbit** [comment]
@luty2018  请问 v1.20.7-lts-f835cdf2的版本能否平滑升级到最新版,  比如v2.8或是5月份的v2.10

**Comment by zzkskys** [comment]
如果从 v1.x-lts 升级至 v2.10-lts，能否出一篇升级文档？文档最好涉及到以下某些方面 : 
- 依赖组件的升级要求(例如 v21-lts 的 mysql 版本要求在 8.0以上、需要 minio 组件等)
- 需要备份哪些数据

**Comment by legend818** [comment]
需求：
不管是哪个版本 自动备份功能还是必须的，不管是开源还是xpack，要锁定用户群体要给用户安心，每次升级都慌慌，技术每次都是问备份没有。 干嘛不自动呢
如果升级出问题（当然--升级一定要做好，别让人心慌），有备份做回退，解决用户升级恐慌症。

**Comment by goodboyxzmkk** [comment]
jmeter 都支持mqtt，开源版为什么不支持

**Comment by maninhill** [comment]
MeterSphere LTS 版本说明：

- v1.10-lts：发布时间为 2021 年 5 月 27 日，目前已经停止维护；
- v1.20-lts：发布时间为 2022 年 4 月 27 日，目前仅进行必要的安全类 Bug 修复和严重 Bug 修复；
- v2.10-lts：发布时间为 2023 年 5 月 25 日，每两周发布小版本，持续进行 Bug 修复和部分功能的有限优化。

**Comment by luty2018** [comment]
> jmeter 都支持mqtt，开源版为什么不支持

您好， MeterSphere的MQTT插件是由产品团队自主研发，目前是企业版功能，可以在官网先申请试用，是否满足您的需求。

**Comment by maninhill** [comment]
https://github.com/metersphere/metersphere/releases/tag/v2.10.0-lts

欢迎大家下载升级体验。

**Comment by deanzhang** [comment]
![53ddbbb47df0351c56660f573503168](https://github.com/metersphere/metersphere/assets/147624/3cf0f153-4bcc-4214-8701-95f3cabe0cf9)
v2.6.1升级到v2.10.0拉不到jmeter-master:5.5-ms5-jdk17这个容器镜像是什么问题？其他人有遇到吗？

**Comment by mengshuai85** [comment]
在ubuntu环境下，从2.7.1 升级到 2.10 报错

Error processing tar file(exit status 1): symlink libkdb5.so.10.0 /usr/lib64/libkdb5.so.10: no space left on device

这个错误：实际上 服务器上是有 剩余空间的，磁盘足够大

**Comment by youliyuan-fit2cloud** [comment]
你好，没有遇到这个情况，手动pull一下试试呢？
docker pull registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms5-jdk17

> ![53ddbbb47df0351c56660f573503168](https://user-images.githubusercontent.com/147624/241604226-3cf0f153-4bcc-4214-8701-95f3cabe0cf9.png) v2.6.1升级到v2.10.0拉不到jmeter-master:5.5-ms5-jdk17这个容器镜像是什么问题？其他人有遇到吗？

**Comment by youliyuan-fit2cloud** [comment]
> 在ubuntu环境下，从2.7.1 升级到 2.10 报错
> 
> Error processing tar file(exit status 1): symlink libkdb5.so.10.0 /usr/lib64/libkdb5.so.10: no space left on device
> 
> 这个错误：实际上 服务器上是有 剩余空间的，磁盘足够大

你好 ，请检查下docker挂载目录可用的磁盘空间是否满了？

**Comment by mengshuai85** [comment]
> > 在ubuntu环境下，从2.7.1 升级到 2.10 报错
> > Error processing tar file(exit status 1): symlink libkdb5.so.10.0 /usr/lib64/libkdb5.so.10: no space left on device
> > 这个错误：实际上 服务器上是有 剩余空间的，磁盘足够大
> 
> 你好 ，请检查下docker挂载目录可用的磁盘空间是否满了？

多谢提醒，确实可能，忽略docker这边了，现在docker挂载的磁盘，还剩6.7G，很可能是不够metersphere安装了
后续我将docker路径迁移后再看看
