### ISSUE TITLE
[BUG]用例评审中关联的用例，没有展示用例的评论

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#22290]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

用例评审中关联的用例，没有展示用例的评论

### 重现步骤

1.这是测试跟踪-功能用例中的评论
![image](https://user-images.githubusercontent.com/88763608/221494178-18012de2-5e4b-4bd9-afae-f2d8ff2f6260.png)
2.这是在用例评审中的用例评论
![image](https://user-images.githubusercontent.com/88763608/221494293-1c004ab8-f99b-42c8-a348-0c81d4777b8b.png)

**Comment by luty2018** [comment]
评审这里的交互还没有完全升级，这里会展示成和功能测试用例一样。会在后续版本上线。
