### ISSUE TITLE
[BUG]用例评审中用例的评审结果，没有保持最新状态

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#22294]
### 联系方式

蒋林峰

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

用例评审中用例的评审结果，没有保持最新状态。

### 重现步骤

1.用例评审的最新已经是已通过，但是用例评审结果还是未通过
![image](https://user-images.githubusercontent.com/88763608/221496780-b7215ccc-8d69-4f66-bb4d-ae15fa1b33d8.png)

2.用例列表中也是未通过
![image](https://user-images.githubusercontent.com/88763608/221496751-39aea49d-83ab-4bb1-a91b-7f6b7a6388cc.png)

### 期待的正确结果

评审状态更新正常。
我这边有复现环境，可以稳定复现，只有个别用例评审中的用例会有这种现象，复现条件还不明确。

**Comment by xulinde** [comment]
你好，用例评审标准是什么？如果是全部通过，则所有人通过才算通过，确认下其他人的评审结果是什么

**Comment by linfengjjj** [comment]
非问题，应该是评审标准的问题。
