### ISSUE TITLE
[BUG]【接口定义】case选择mock环境运行后，请求的地址不是环境中设置好的mock地址

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22298]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1. mock环境地址为 http://democenter.fit2cloud.com:2702/api/mock/100001
![image](https://user-images.githubusercontent.com/104960608/221511316-8f3753ee-11cf-4f05-b1f0-71bc5ca63b56.png)

2. 运行case时，选择mock环境后，点击运行，发出去的地址不是设置好的mock环境地址。
![image](https://user-images.githubusercontent.com/104960608/221511400-72f3392c-495f-4fc5-bb00-3ec7a506ef49.png)

### 重现步骤

1. mock环境地址为 http://democenter.fit2cloud.com:2702/api/mock/100001
![image](https://user-images.githubusercontent.com/104960608/221511316-8f3753ee-11cf-4f05-b1f0-71bc5ca63b56.png)

2. 运行case时，选择mock环境后，点击运行，发出去的地址不是设置好的mock环境地址。
![image](https://user-images.githubusercontent.com/104960608/221511400-72f3392c-495f-4fc5-bb00-3ec7a506ef49.png)

**Comment by song-tianyang** [comment]
您好！感谢您的支持！

通过您的截图，我觉得出现这个问题的原因，是您Case的路径仅是一个"/"，并没有其它后缀。

Mock目前不支持没有后缀的路径。您发送这个请求的话是会被重定向的。

我们在设计这个功能时，希望这个功能不仅仅是在metersphere上使用，也希望提供给其它有需求的被测系统使用。在这个初衷下，如何更精确的通过url路径来定位到想要的接口定义，进行Mock期望的匹配，就成了我们首先要考虑的问题。  

如图中直接向Mock服务发送没有后缀的请求，对于我们的匹配算法来说，这样的请求稍显宽泛和随意，违背了我们想精确定位接口定义的初衷。也是基于这个原因，我们目前并没有支持这种请求的想法。

再次感谢您的支持！祝您生活愉快！
