### ISSUE TITLE
[FEATURE]增加标志位，来作为 测试用例/测试计划 是否可执行的判断条件，来避免并发执行引发的冲突

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22302]
### MeterSphere 版本

v2.6.1

### 联系方式

silverleo@163.com

### 请描述您的需求或者改进建议

**问题描述**：大部分接口用例/场景用例/测试计划受测试环境、测试数据等各种因素影响，在并发执行的时候会引发冲突。如何对用例的当前状态进行识别，并在执行的时候进行相应的处理，是一个亟需解决的问题。

**建议方案**：
1. 在 **接口用例/场景用例/测试计划** 定义的时候，增加一个是否可并发执行的标志位。由创建者来设置用例是否可并发执行。
2. 在用例执行之前，根据**标志位 + 当前状态** 来决定是否可立即执行。如果不能立即执行，则放到队列里等待执行。
3. 在用例列表页面，实时更新当前用例的执行状态，对于长时间处于排队或者运行中状态的用例，用户可以手工取消或停止执行。

测试平台的主要功能之一是测试服务化，测试用例可以作为测试资源以服务化的形式提供给关人员使用。如果不能处理好用例的状态管理，会大大降低用户的使用体验，希望能够考虑一下这个需求的实现。多谢！

**Comment by luty2018** [comment]
我们在如何处理接口是否能并发执行的场景里提供了串行和并行的执行模式。对于不能并发执行的接口建议用户使用串行模式。
或者你可以进一步描述你的场景或者说串行不能覆盖的场景，否则你目前说的这种方案稍显复杂，测试计划批量执行的时候会出现很多其它问题的。

**Comment by yangstones** [comment]
![image](https://user-images.githubusercontent.com/2188338/221779154-3c4d873e-be2b-4b58-a530-01b79a27d8be.png)
您是说上面这个 测试计划 的执行设置吗？
我试了一下，在这个地方选择串行执行，并不能避免下面的问题：
1. 用户A 触发了测试计划1的执行
2. 在A触发的执行还未结束的时候，用户B也触发了测试计划1的执行

这种，测试计划A就有两个执行的实例在并发执行，会造成计划中测试用例的执行冲突。你方便的话可以通过邮件发一下您的电话，我给您打电话具体解释一下我提的需求场景
我的邮箱：silverleo@163.com

**Comment by zhangzhaox** [comment]
@yangstones 在A触发的执行还未结束的时候，用户B也触发了测试计划1的执行  这种情况 本质是还是用例设计时的独立性不够吧，数据绑定死了？

**Comment by yangstones** [comment]
> @yangstones 在A触发的执行还未结束的时候，用户B也触发了测试计划1的执行 这种情况 本质是还是用例设计时的独立性不够吧，数据绑定死了？ 设计场景用例时的要求 每个用例具备独立执行、重复执行的能力。

测试用例的构建和执行也要考虑具体的业务场景，有些时候，完全要求用例执行的独立性是成本很高的，符合业务场景的用例才是合适的用例。比如，通过调用接口，向物理设备下发配置，受物理设备的限制，无法为每次执行都分配一套物理设备环境，为了保证测试的准确性，只能通过防止并发执行来实现。
另外，我觉得用例是否能并发执行，应该是由用户自己来决定的，所以这是个优化项。如果实现起来有难度，可以把方案简化以下：
1. 只通过标志位和当前状态，对测试计划的执行做约束。
2. 在场景测试列表中，显示当前用例的执行状态。思路就是：平台把状态告知用户，由用户来决定要不要执行。

**Comment by zhangzhaox** [comment]
比如，通过调用接口，向物理设备下发配置，受物理设备的限制，无法为每次执行都分配一套物理设备环境，为了保证测试的准确性，只能通过防止并发执行来实现。   这场景绝对的并发  很容易出现？ 你现在的主要问题是执行计划 与 个人调试时 出现并发失败的问题？

**Comment by yangstones** [comment]
> 

跑题了！现在不是讨论我的测试场景是不是容易出现。而是用户现在有这个需求，你们可以不去实现，但是没必要质疑用户的使用场景

**Comment by luty2018** [comment]
> > 
> 
> 跑题了！现在不是讨论我的测试场景是不是容易出现。而是用户现在有这个需求，你们可以不去实现，但是没必要质疑用户的使用场景

你好， 并没有质疑你的使用场景， 上面回复你问题的是另外一位开源用户，他只是一起参与交流。
对于你的这个场景，我们还是更建议从设计场景的角度去规避， 系统去做这样的功能只会让执行逻辑更为复杂，排查错误也更难。
