### ISSUE TITLE
[BUG]接口自动化场景【调试】按钮，不能让从接口定义里复制过来的接口与环境关联上，导致执行url不完整

### ISSUE THREAD

**Issue by jackieliestener** [metersphere/metersphere#22307]
### 联系方式

55群 董俊鹏

### MeterSphere 版本

v1.20.18-lts

### 使用外置数据库

否

### 问题描述

接口自动化里面，host与路径不能拼接（可能是因为变动了接口定义的结构）环境配置里面也发生了变化，选择了test环境，但是关联不上，host一直为空的状态
![image](https://user-images.githubusercontent.com/85087144/221532485-6a964fb1-6f93-4134-91d3-08d58b25b691.png)

### 重现步骤

1. 修改接口定义目录结构和名称后，导致环境管理里面，【HTTP配置】启用条件的模块里面的关联失效，变为乱码
2. 删除显示为乱码的模块，重新关联模块
3. 去执行在修改接口定义目录前已经写好的接口自动化
4. 执行的时候，选择环境，点击【调试】，执行失败
![image](https://user-images.githubusercontent.com/85087144/221532164-ba7c422e-29d1-4eea-bfda-5d9990a77e88.png)

### 期待的正确结果

执行时候选择什么环境就关联什么环境的host

**Comment by zyyfit** [comment]
您好，方便把您的接口信息和环境信息上传给我们看一下吗？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
