### ISSUE TITLE
[BUG]sql查询取值不正确

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#22308]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

使用场景：sql查询数据，使用计数器循环把每行的数据取出来

问题，执行到第3次循环时，第三行第二列的数据取到了第四行第二列的数据

### 重现步骤

看截图

### 期待的正确结果

正常取出每一行的数据

### 附加信息

![image](https://user-images.githubusercontent.com/43720321/221546183-16c12690-dae7-48ba-aa23-9151f7c65c95.png)

**Comment by fit2-zhao** [comment]
未曾复现您的问题，按照您的描述我上传了我的操作步骤，您可以参考对比下：
![image](https://user-images.githubusercontent.com/70558837/221742729-29f0a7d5-dccf-41ba-ab71-65b9f4002faa.png)
![image](https://user-images.githubusercontent.com/70558837/221742742-89356c83-3dec-4320-8c6e-64b104303401.png)
![image](https://user-images.githubusercontent.com/70558837/221742748-21a1b3c5-1073-474f-b8b2-d40be1bd5e23.png)
![image](https://user-images.githubusercontent.com/70558837/221742758-8d591cd8-fd6d-4268-acbb-72292d060907.png)

**Comment by goodboyxzmkk** [comment]
请检查测试数据，第二行二列与第三行二列数值相同的情况

**Comment by fit2-zhao** [comment]
感谢反馈，值重复情况也未曾复现您的问题。

![image](https://user-images.githubusercontent.com/70558837/222023828-e1d0b6fe-6e2d-44b8-babe-2657e74f3dbe.png)

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
