### ISSUE TITLE
[BUG]接口自定义，请求体选择x-www-form-urlencoded，类型输入application/vnd.ms-excel,使用xls文件作为参数会报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22311]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

接口自定义模块，请求体选择x-www-form-urlencoded，类型输入application/vnd.ms-excel，执行该导入接口时，后台报错，前端卡死了
![48f5669fa7c8404f2454a4452ffdd3d](https://user-images.githubusercontent.com/83771182/221598858-0bbb7724-3d95-4565-b93b-cf8b04411f10.jpg)
使用如图xls文件作为参数
![28dcc5cd9bbb3b7ea9587d554b7a09a](https://user-images.githubusercontent.com/83771182/221599024-7f1cd5f9-06a4-4bf0-9f41-06215c35484c.jpg)
会报错，日志之见图
![a9843472dcbc662fac55c085525ea10](https://user-images.githubusercontent.com/83771182/221599354-a53d1bf9-e17f-4141-9216-b4501cfbc9e1.jpg)
![0ca8894aaeb49fd6f04b7e81cb91955](https://user-images.githubusercontent.com/83771182/221599376-b9c77550-3f39-4ee4-bcd6-ff0246c1bb50.jpg)
如果传xlsx的文件，并且更改类型则可以执行成功，只有xls文件不行。

### 重现步骤

接口自定义模块，请求体选择x-www-form-urlencoded，类型输入application/vnd.ms-excel，执行该导入接口时，后台报错，前端卡死了

### 相关日志输出

```shell
见截图
```

**Comment by fit2-zhao** [comment]
感谢您的反馈，这个问题已经在2.7.0版本修复过了，请升级到该版本。
