### ISSUE TITLE
[BUG]性能测试-报告详情页面，选择性能测试时配置的监控设备后，监控图未显示。

### ISSUE THREAD

**Issue by huangzhenmin123** [metersphere/metersphere#22321]
### 联系方式

58群/美文

### MeterSphere 版本

v1.20.19-lts-a80199cf   v2.5.0-1e7e6908

### 使用外置数据库

否

### 问题描述

性能测试-报告详情页面，选择性能测试时配置的监控设备后，监控图未显示，但列表界面显示有监控信息。

### 重现步骤

1、创建性能测试
2、运行性能测试；
3、查看报告详情

### 期待的正确结果

监控图正常显示

**Comment by liuruibin** [comment]
感谢提醒，这里存在类型转换错误，我们会在下个版本中修复
