### ISSUE TITLE
[BUG]脑图编写用例，长时间打开2小时左右，再编辑用例保存报错

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#22328]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

脑图编写用例，长时间打开页面2小时左右，再编辑用例保存报错

### 重现步骤

脑图编写用例，长时间打开页面2小时左右，再编辑用例保存报错

### 期待的正确结果

可以正常编辑用例

### 附加信息

![db18d32924610a6a3a1c47a2396f868](https://user-images.githubusercontent.com/43720321/221772107-ad6805da-e226-4576-97b5-d44ab21fac0f.png)

**Comment by xulinde** [comment]
您好，我们这边没有复现该问题，您那边是必现的吗，能否提供下详细的复现步骤？

**Comment by 13290445582** [comment]
您好，最新环境未复现该问题，建议升级至v2.10.2再次尝试，若问题还存在，请重新提issue，感谢。
