### ISSUE TITLE
[BUG]用例模板设置的是文本描述，导入用例后显示的还是步骤描述

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22322]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.18

### 使用外置数据库

否

### 问题描述

用例模板设置的是文本描述，导入用例后显示的还是步骤描述

### 重现步骤

![导入用例bug](https://user-images.githubusercontent.com/39357523/221751767-87fc5c19-3e30-468f-9dc7-da3be3aff1ef.png)

### 期待的正确结果

期望用例显示的是文本描述，与预期结果对应；步骤描述预期结果错乱了

**Comment by xulinde** [comment]
v1.20.20-lts未复现该问题，建议您升级下版本

**Comment by myliuq** [comment]
亲，升级到v1.20.20 lts版本了，但是这个bug还是存在，导入之后还是显示的步骤描述呢










雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月28日(星期二) 晚上6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]用例模板设置的是文本描述，导入用例后显示的还是步骤描述 (Issue #22322)





 
v1.20.20-lts未复现该问题，建议您升级下版本

**Comment by myliuq** [comment]
![image](https://user-images.githubusercontent.com/39357523/221856753-aad3f53c-15fa-4374-b858-ccbc372946c1.png)
![image](https://user-images.githubusercontent.com/39357523/221856788-aebbd146-e631-4b6b-af50-6df954c2dcd5.png)

**Comment by xulinde** [comment]
您看下导入的excel中，“编辑模式”字段的值是什么？

**Comment by myliuq** [comment]
知道了，“编辑模式”为TEXT才是文本，为STEP就是步骤，谢谢，解决了




雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]用例模板设置的是文本描述，导入用例后显示的还是步骤描述 (Issue #22322)





 
您看下导入的excel中，“编辑模式”字段的值是什么？
