### ISSUE TITLE
[BUG]v1.20.19  脑图编辑先保存临时模块，保存 ；把再临时模块标记为用例，保存报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22329]
### MeterSphere 版本

v1.20.19

### 使用外置数据库

否

### 问题描述

 脑图编辑先保存临时模块，保存 ；把再临时模块标记为用例，保存报错  见截图

### 重现步骤

1、脑图增加临时模块，保存
2、问题：把再临时模块标记为用例，保存报错  

### 相关日志输出

```shell
[文件：20230228141255.gif]
```

**Comment by xhy12** [comment]
![20230228141255](https://user-images.githubusercontent.com/43202800/221772454-7bcc9d45-01c7-43a0-be08-5ea76e2e34d1.gif)

**Comment by tinychange** [comment]
我们也碰到了这个问题，求修复

**Comment by xulinde** [comment]
重复，https://github.com/metersphere/metersphere/issues/22327
