### ISSUE TITLE
[BUG] oidc登录后用户名称名称乱码

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22326]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

oidc登录后用户名称名称乱码
当客户的用户信息接口是utf-8时，登录后如下图：
![image](https://user-images.githubusercontent.com/103925124/222033676-46e4b2ac-1ee9-45c3-a08e-253aff7dc16f.png)
当客户的用户信息接口是非utf-8时，登录后如下图：
![image](https://user-images.githubusercontent.com/103925124/222033744-482c34fb-f87b-4efa-be69-4fcf90cf9db1.png)

### 重现步骤

使用代码调用，打印也是乱码
![f6fbc13b-7003-4976-9a8f-77cbf629d6e8](https://user-images.githubusercontent.com/103925124/221769561-158e15f8-0fa8-486e-b9da-400bbc7f54dd.png)
加上：restTemplate.getMessageConverters().set(1, new StringHttpMessageConverter(StandardCharsets.UTF_8));
后响应体不乱码
![image](https://user-images.githubusercontent.com/103925124/221772394-05b6c8c8-fa25-42ce-af23-b4b390bd9ce8.png)
![image](https://user-images.githubusercontent.com/103925124/221772644-c27711dd-1a55-439e-ab0a-93cd75a269a3.png)
故编码需统一为utf8

**Comment by Ycr123888** [comment]
经客户环境加上 restTemplate.getMessageConverters().set(1, new StringHttpMessageConverter(StandardCharsets.UTF_8));打包gateway镜像验证，使用oidc登录无乱码。使用公司keyclock亦通过

**Comment by liuruibin** [comment]
您好，我们系统内接入OIDC OAuth2 等服务时仅对接标准格式，如果是修改过的平台我们无法支持

**Comment by Ycr123888** [comment]
![1677663916376](https://user-images.githubusercontent.com/103925124/222102720-69ced418-7468-41e6-834a-a416452d89c8.png)
出现此问题客户的用户信息接口，响应体编码为utf-8，如上图restTemplate默认编码非utf8
如加上 restTemplate.getMessageConverters().set(1, new StringHttpMessageConverter(StandardCharsets.UTF_8));后兼容性更强

**Comment by liuruibin** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/23045261/222389518-71ad19e2-2150-4538-b23e-472f77f43f20.png">
我们LTS版本中使用的spring boot 是2.7.x, metersphere v2.7 使用的是spring boot v3.0.x

**Comment by Ycr123888** [comment]
该用户的用户信息接口如下图：
![67ed4afb4da6e39e3e96670e042c71a](https://user-images.githubusercontent.com/103925124/222404536-016847f2-76e4-48fe-839c-c38aca4219f9.png)
已设置编码，未设置响应头为Content-Type:application/json; charset=utf-8，让客户加上后再次尝试

还是建议产品也加上
// 设置restemplate编码为utf-8
restTemplate.getMessageConverters().set(1,new StringHttpMessageConverter(StandardCharsets.UTF_8));
来兼容更多三方接口，且对原来支持的接口无影响

**Comment by Ycr123888** [comment]
设置响应头为Content-Type:application/json; charset=utf-8后，无乱码问题，感谢解答回复
