### ISSUE TITLE
[BUG]用例模板自定义字段（多选类型），编辑用例导入后列表上这个字段的值没有显示

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22323]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

用例模板自定义字段（多选类型），编辑用例导入后列表上这个字段的值没有显示

### 重现步骤

1.用例模板设置自定义字段“测试方式”，类型为多选下拉列表
2.编辑功能用例时，导入excel编辑的用例
3.导入后，用例列表上面的“测试方式”显示为空，编辑页面次字段是有值的
![自定义字段](https://user-images.githubusercontent.com/39357523/221752567-f6999927-8aef-493a-9aa5-99a1c1eb1273.png)
![自定义字段列表bug](https://user-images.githubusercontent.com/39357523/221752607-6cd7ce0e-5a67-45c9-b75f-68266373e22a.png)

### 期待的正确结果

用例列表上面的“测试方式”列能正确显示值

**Comment by xulinde** [comment]
v1.20.20-lts未复现该问题，建议您升级下版本

**Comment by myliuq** [comment]
收到，已升级，已解决，谢谢




雨过天晴
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月28日(星期二) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]用例模板自定义字段（多选类型），编辑用例导入后列表上这个字段的值没有显示 (Issue #22323)





 
v1.20.20-lts未复现该问题，建议您升级下版本
