### ISSUE TITLE
接口测试Python前置脚本，unicode类型中文变量，无法与环境参数中的，中文变量正确判断

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22334]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

在1.20.15-LTS版本中可以使用”unicode类型中文变量“与环境参数中的”中文变量“进行相等的正确判断，升级到v2.7.0版本后就无法进行正确的判断，必须将环境参数中的”中文变量“进行decode.("utf-8")才能进行判断：
1.20.15-LTS版本截图：
<img width="1392" alt="截屏2023-02-28 下午2 39 18" src="https://user-images.githubusercontent.com/34637801/221774044-000f41d6-2be6-4621-a650-53d0bfd4d875.png">
<img width="1395" alt="截屏2023-02-28 下午2 39 41" src="https://user-images.githubusercontent.com/34637801/221774099-05b2c643-59d6-4a9c-b803-9716cba4b3e9.png">
v2.7.0版本截图：
<img width="1280" alt="截屏2023-02-28 下午2 41 38" src="https://user-images.githubusercontent.com/34637801/221774472-42b8a6d9-b7aa-4839-9e54-6e7f782491e6.png">
<img width="1386" alt="截屏2023-02-28 下午2 42 20" src="https://user-images.githubusercontent.com/34637801/221774592-99dff631-2be7-4582-a40c-6d3513c9eadd.png">

### 重现步骤

1.分别部署一台v1.20.15LTS版本的MS服务和v2.7.0版本的MS服务
2.分别创建一个接口定义和case（比如调用百度网站）
3.在接口case前置脚本中创建一个Python脚本
4.脚本内容如下：
import sys
sys.path.append("/opt/metersphere/data/python/lib/python2.7/site-packages")
reload(sys)
sys.setdefaultencoding('utf-8')

def get_headers():
    log.info("====operationList========")
    a = "测试中文"
    b = "测试中文2"
    operationList = [unicode(a),unicode(b)]
    log.info("====if========")
    if  operationList[0].decode('unicode-escape') == "${c_family_name}":
        log.info("====after========"+operationList[0].decode('unicode-escape'))

get_headers()
5.会发现 1.20.15LTS版本可以正确进入”if“条件里，v2.7.0版本无法正确进入到”if“条件里，需要将"${c_family_name}"改为"${c_family_name}".decode("utf-8")中才可以。

### 期待的正确结果

v2.7.0版本也能正确的进入if判断语句中

**Comment by pengzhengyou** [comment]
但是 你这个方式变化了后 用户已经有上万个存量接口用例 的前置脚本使用了这样的判断，又没有批量修改的方法  无法逐个去进行修改

**Comment by fit2-zhao** [comment]
![image](https://user-images.githubusercontent.com/70558837/222322936-d4297c4c-4ac0-461d-9db5-8389e3b91bb7.png)
从上图结论来看，if 判断并未受编码影响，输出内容如果不转码，则会出现乱码，所以应该从自身脚本检查一下，这里和编码关系不大。
（ps：所有版本均是这样）
