### ISSUE TITLE
[BUG]vars.get一个未设置的变量，默认值是什么？jmeter默认为null

### ISSUE THREAD

**Issue by Forilan** [metersphere/metersphere#22336]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

![fa227320a35285590ecee0490a2d122](https://user-images.githubusercontent.com/6127516/221783294-aec8b630-4eb1-4ad2-b721-dc5c4a2e0861.png)

vars.get一个未设置的变量，默认值是什么？jmeter默认为null

### 重现步骤

场景脚本中

**Comment by fit2-zhao** [comment]
你好，感谢反馈，您困惑的原因是：当有声明属性接收就是void ；直接输出就是 null

![image](https://user-images.githubusercontent.com/70558837/221824737-f431b082-8f99-48bb-832e-08fbadf60b9a.png)
