### ISSUE TITLE
[BUG]测试场景引用接口测试用例，当接口测试用例变更，在场景中直接执行，执行的还是变更前的测试用例，必须要点击编辑进行场景调试后，才会引用修改后的接口测试用例

### ISSUE THREAD

**Issue by daicp** [metersphere/metersphere#2233]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  创建一个接口测试用例1
2. 场景一个自动化测试场景，并增加用例，将用例1引用进来
3. 修改测试用例1的某个地方，如传参
4. 返回自动化中，直接执行场景，执行的是修改前的用例

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这个问题将在1.9.0版本修复

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/2003
