### ISSUE TITLE
[BUG]项目设置-应用管理-接口测试-定时清理接口测试报告似乎没有生效

### ISSUE THREAD

**Issue by Jetdachui** [metersphere/metersphere#22344]
### 联系方式

2306427193@qq.com

### MeterSphere 版本

 检测当前版本为v1.20.19-lts

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/74963743/221809146-6d03e3e2-ebed-400d-af3b-decdbc8c494b.png)
<img width="1883" alt="企业微信截图_16775757952631" src="https://user-images.githubusercontent.com/74963743/221808045-51c43fb6-edeb-4140-b6fa-fe639838124e.png">

### 重现步骤

21号中午因为报告太多 进数据库清理了报告
![image](https://user-images.githubusercontent.com/74963743/221808436-b7c456b3-4cae-46b1-9eb0-c746fb4af717.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题计划在v2.8.0版本中修复，请关注发布信息。

**Comment by shiziyuan9527** [comment]
您好，需要提供下24号的info日志定位问题。

**Comment by Jetdachui** [comment]
[info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879699/info.20230224-0.log)
[error.20230224-0.log](https://github.com/metersphere/metersphere/files/10879700/error.20230224-0.log)
[info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879702/info.20230224-0.log)

**Comment by youliyuan-fit2cloud** [comment]
> [info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879699/info.20230224-0.log) [error.20230224-0.log](https://github.com/metersphere/metersphere/files/10879700/error.20230224-0.log) [info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879702/info.20230224-0.log)

感谢，已收到您反馈的信息，会在下个版本中修复。

**Comment by shiziyuan9527** [comment]
> [info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879699/info.20230224-0.log) [error.20230224-0.log](https://github.com/metersphere/metersphere/files/10879700/error.20230224-0.log) [info.20230224-0.log](https://github.com/metersphere/metersphere/files/10879702/info.20230224-0.log)

您好，提供的info日志没有内容。
还有就是现在报告的数据被清理了吗?
