### ISSUE TITLE
[BUG]功能用例评审，评审状态错误

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#22346]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

评审后，评审状态显示人名拼音

### 重现步骤

随便评审一个都这样

### 期待的正确结果

正确显示评审状态

**Comment by xulinde** [comment]
使用最新的v2.7.0版本未复现该问题，建议您升级下版本

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
