### ISSUE TITLE
[BUG]  设置页面title后，访问metersphere，title加载过慢

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#22343]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.19-lts/v2.6.1

### 使用外置数据库

否

### 问题描述

设置页面title后，访问metersphere，title加载过慢

### 重现步骤

设置页面title后，访问metersphere，title加载过慢，出现明显切换痕迹
如出现网速过慢，将出现title切换失败
![image](https://user-images.githubusercontent.com/103925124/221808158-0f80a108-f8f2-4305-96a3-d3e223acf065.png)
视频在下面压缩包中：
[伊利.zip](https://github.com/metersphere/metersphere/files/10848487/default.zip)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，遇到过该问题，目前还没特别好的解决办法，会加入v3.0版本规划中，请关注后续反馈。

**Comment by liuruibin** [comment]
> 这个很难解决吗？ @liuruibin

取决于网速
