### ISSUE TITLE
[BUG]场景引用接口测试用例，delete接口，无法获取最新的接口地址

### ISSUE THREAD

**Issue by daicp** [metersphere/metersphere#2235]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![20210423195158](https://user-images.githubusercontent.com/39850851/115868318-ddd4ca00-a46e-11eb-9d37-64d3c999bd53.png)
![20210423195610](https://user-images.githubusercontent.com/39850851/115868320-df05f700-a46e-11eb-9c7c-7fb2ec745c12.png)

**Comment by zyyfit** [comment]
您好，请问您修改的是接口还是用例？引用的是接口还是用例？修改用例引用接口的话引用内容还是跟接口保持一致的
