### ISSUE TITLE
[BUG]编写测试用例为文本类型时，回车键无法换行

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#22368]
### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

编写测试用例为文本类型时，回车键无法换行

### 重现步骤

新建测试用例，类型选择文本描述，对话框中输入文字后点击回车，无法换行

### 期待的正确结果

能够按回车键正常换行

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/222038547-36f9c828-1c69-49c0-b54e-4f233f7fb71a.png)

**Comment by lingllgh** [comment]
编辑用例页面, 任何文本输入框enter键都无反应

**Comment by xulinde** [comment]
> 编辑用例页面, 任何文本输入框enter键都无反应

已确认是bug，后续版本修复

**Comment by zrfit** [comment]
您好，v2.7.1已修复该问题，待发布后可升级验证。
