### ISSUE TITLE
[BUG]在测试计划中编排接口场景测试用例，通过手动触发或者是jenkins平台自动触发，都会出现有的场景用例未执行

### ISSUE THREAD

**Issue by luoyongming** [metersphere/metersphere#22364]
### 联系方式

MeterSphere 交流群57

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

![7d4d90a35f1cc69c1cf17fc1cd2cc9f](https://user-images.githubusercontent.com/126635333/222028717-ce3a6e3b-10a6-4d1c-9623-e9b2891161bf.png)
![cc36d86138db3a6bb1f5156420dfd2d](https://user-images.githubusercontent.com/126635333/222028749-5e9ff963-282c-4c26-9fcb-847119d2c6d9.png)

### 重现步骤

在测试计划中编排接口场景测试用例，通过手动触发或者是jenkins平台自动触发，都会出现有的场景用例未执行的情况，导致测试计划流程失败

### 期待的正确结果

希望测试计划执行流程能正常进行

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.7尝试多次并未复现该问题，请升级后尝试。

**Comment by 13290445582** [comment]
该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～

**Comment by bedisco** [comment]
> 该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～

您好，这个优化有具体的pr可以学习吗，我这边一直在使用1.20.x  也发现了这种情况，想直接在1.20.x直接修复。感谢~
