### ISSUE TITLE
[BUG]报告分享链接有效期为15天，定时任务发送的测试报告链接有效期仅有24小时

### ISSUE THREAD

**Issue by bimengyan** [metersphere/metersphere#22367]
### MeterSphere 版本

v2.7.0

### 联系方式

15346210973@163.com

### 请描述您的需求或者改进建议

定时任务发送的测试报告链接有效期仅有24小时
在项目设置-应用管理中设置【测试跟踪】和【接口测试】的报告分享链接有效期为15天，这个设置只影响主动分享的测试报告链接有效期，不影响定时任务自动发送的测试报告链接有效期，定时任务发送的测试报告有效期依旧为24小时

### 请描述你建议的实现方案

建议定时任务自动发送的测试报告有效期可设置

### 附加信息

![image](https://user-images.githubusercontent.com/117714341/222038120-849f1b0e-2b18-4c57-8490-c8c51e91fac6.png)

**Comment by luty2018** [comment]
感谢反馈，我们复现一下

**Comment by bimengyan** [comment]
依旧存在问题，25日的测试报告链接，点击失败的用例弹出提醒：连接已失效，请重新获取
![image](https://user-images.githubusercontent.com/117714341/222097222-0dc8fe17-c9ee-4349-872b-2e48a1f0bf46.png)

**Comment by bimengyan** [comment]
SELECT * from api_scenario_report where id=custom_data 拿到项目id project_id
该sql无法查询到project_id，拿我当前可用的定时任务产生的测试报告的

**Comment by wxg0103** [comment]
测试报告的id为空说明报告被删了      报告失效后  就会被删除

**Comment by bimengyan** [comment]
测试报告未被删除，在测试跟踪-报告中依然能找到该报告，并能正常查看，但是通过链接就会报上述错误

**Comment by bimengyan** [comment]
根据上述sql查询的测试跟踪报告有效时间为15D
![image](https://user-images.githubusercontent.com/117714341/222313736-448d33f1-9f64-4fd7-8f3f-92a93eb328f5.png)

**Comment by wxg0103** [comment]
感谢反馈  这个问题将在v2.8修复
祝您生活愉快
