### ISSUE TITLE
[BUG]接口自动化失败重试日志位置错误，未失败也重试了

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#22379]
### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

接口自动化失败重试日志位置错误，重试的日志不是连续的而是中间隔了其它操作，未失败的操作也进行了重试

### 重现步骤

正常新建测试计划，加入接口自动化用例，添加定时任务，跑完后看报告

### 期待的正确结果

失败的地方进行重试，重试的时候日志应该是连续不间断的

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/222070410-5f29eb8c-3a3b-4f72-ac71-1c6fc6344745.png)

**Comment by fit2-zhao** [comment]
感谢反馈，请确认一下是否开启了误报断言了。

**Comment by wszbc** [comment]
> 感谢反馈，请确认一下是否开启了误报断言了。

请问误报断言在哪里看，没看到有这个东西捏，我就只是在定时任务的时候开了一个失败重试2次

**Comment by fit2-zhao** [comment]
感谢反馈，排序问题已经复现，会在2.8版本修复，成功请求再次执行问题未曾复现。

**Comment by youliyuan-fit2cloud** [comment]
> > 感谢反馈，请确认一下是否开启了误报断言了。
> 
> 请问误报断言在哪里看，没看到有这个东西捏，我就只是在定时任务的时候开了一个失败重试2次

误报是在所选的运行环境里面的全局断言开启，但是误报是企业版功能～ 
如果是开源版和误报没关系了。

**Comment by youliyuan-fit2cloud** [comment]
位置错误问题在v2.8.0 中已修改，请升级一下
未失败也会重试没有复现，如果方便的话把场景发我们试试？

**Comment by wszbc** [comment]
> 位置错误问题在v2.8.0 中已修改，请升级一下 未失败也会重试没有复现，如果方便的话把场景发我们试试？

我研究了下未失败重试的场景是一个自定义脚本控件，这个控件里面设置了断言规则只要代码中设置了AssertionResult.setFailureMessage(msg);就会导致重试必现，不论最后断言是否通过。然后我想问下重试的规则是什么啊，断言不过对应的控件就会重试设置的次数么？

**Comment by youliyuan-fit2cloud** [comment]
> > 位置错误问题在v2.8.0 中已修改，请升级一下 未失败也会重试没有复现，如果方便的话把场景发我们试试？
> 
> 我研究了下未失败重试的场景是一个自定义脚本控件，这个控件里面设置了断言规则只要代码中设置了AssertionResult.setFailureMessage(msg);就会导致重试必现，不论最后断言是否通过。然后我想问下重试的规则是什么啊，断言不过对应的控件就会重试设置的次数么？

你理解是对的，断言不过对应的控件就会重试

**Comment by wszbc** [comment]
> > > 位置错误问题在v2.8.0 中已修改，请升级一下 未失败也会重试没有复现，如果方便的话把场景发我们试试？
> > 
> > 
> > 我研究了下未失败重试的场景是一个自定义脚本控件，这个控件里面设置了断言规则只要代码中设置了AssertionResult.setFailureMessage(msg);就会导致重试必现，不论最后断言是否通过。然后我想问下重试的规则是什么啊，断言不过对应的控件就会重试设置的次数么？
> 
> 你理解是对的，断言不过对应的控件就会重试。 AssertionResult.setFailureMessage(msg); 如果有值 表示就是失败断言。

不对啊，断言是否通过不是AssertionResult.setFailure(true);这句么 我会在msg先把对应参数打出来，如果断言通过就AssertionResult.setFailure(false);通过，如果失败了，那么会打印我对应的msg出来让我快速定位哪里错了，而且我试了下接口控件中如果断言失败了是没有重试的

**Comment by youliyuan-fit2cloud** [comment]
> > > > 位置错误问题在v2.8.0 中已修改，请升级一下 未失败也会重试没有复现，如果方便的话把场景发我们试试？
> > > 
> > > 
> > > 我研究了下未失败重试的场景是一个自定义脚本控件，这个控件里面设置了断言规则只要代码中设置了AssertionResult.setFailureMessage(msg);就会导致重试必现，不论最后断言是否通过。然后我想问下重试的规则是什么啊，断言不过对应的控件就会重试设置的次数么？
> > 
> > 
> > 你理解是对的，断言不过对应的控件就会重试。 AssertionResult.setFailureMessage(msg); 如果有值 表示就是失败断言。
> 
> 不对啊，断言是否通过不是AssertionResult.setFailure(true);这句么 我会在msg先把对应参数打出来，如果断言通过就AssertionResult.setFailure(false);通过，如果失败了，那么会打印我对应的msg出来让我快速定位哪里错了，而且我试了下接口控件中如果断言失败了是没有重试的

  你好，方便把这个场景发给我们试试吗？使用最新版本没有出现你说的情况。感谢理解和支持～

**Comment by wszbc** [comment]
> > > > > 位置错误问题在v2.8.0 中已修改，请升级一下 未失败也会重试没有复现，如果方便的话把场景发我们试试？
> > > > 
> > > > 
> > > > 我研究了下未失败重试的场景是一个自定义脚本控件，这个控件里面设置了断言规则只要代码中设置了AssertionResult.setFailureMessage(msg);就会导致重试必现，不论最后断言是否通过。然后我想问下重试的规则是什么啊，断言不过对应的控件就会重试设置的次数么？
> > > 
> > > 
> > > 你理解是对的，断言不过对应的控件就会重试。 AssertionResult.setFailureMessage(msg); 如果有值 表示就是失败断言。
> > 
> > 
> > 不对啊，断言是否通过不是AssertionResult.setFailure(true);这句么 我会在msg先把对应参数打出来，如果断言通过就AssertionResult.setFailure(false);通过，如果失败了，那么会打印我对应的msg出来让我快速定位哪里错了，而且我试了下接口控件中如果断言失败了是没有重试的
> 
> 你好，方便把这个场景发给我们试试吗？使用最新版本没有出现你说的情况。感谢理解和支持～

我的地址都是内网的给你也用不了我单独写了个场景可以直接帮你复现bug，导入到计划中，计划设置重试次数然后执行，
[Metersphere_Scenario_OMS.zip](https://github.com/metersphere/metersphere/files/11084469/Metersphere_Scenario_OMS.zip)
![image](https://user-images.githubusercontent.com/40912823/228106785-8b170530-7717-4eea-989c-cc42ea92af41.png)
第一个控件就是明明断言成功了 但是重试了
![image](https://user-images.githubusercontent.com/40912823/228106958-4be2b869-6a9a-409b-ab94-76888441321e.png)
第二个就是接口断言失败了但是没有重试

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈的复现文件，下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/228406600-1d05beba-04bc-401a-8b66-871d3f5c4728.png)
第一个请求脚本断言更改了执行结果了，这里就会重试。

![image](https://user-images.githubusercontent.com/54612864/228406665-18a82b61-5de0-4f6a-ab95-43d7a5c70782.png)

第二条没有重试是因为失败停止了。
所以是场景配置的问题。

**Comment by wszbc** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/228406600-1d05beba-04bc-401a-8b66-871d3f5c4728.png) 第一个请求脚本断言更改了执行结果了，这里就会重试。
> 
> ![image](https://user-images.githubusercontent.com/54612864/228406665-18a82b61-5de0-4f6a-ab95-43d7a5c70782.png)
> 
> 第二条没有重试是因为失败停止了。 所以是场景配置的问题。

先变成失败条件满足才变成成功这样能够更准确的保证断言的正确性因为争取的场景是唯一的，如果只断言失败，其实会出现一些异常情况没有写进断言，这样真的报错了断言也会通过无法暴露功能的问题，而且判断内容太多也会导致代码相对复杂，容易写错，所以才选择这种先定义为失败，只有满足成功条件才变成成功，这样对于脚本调试和定位都会更简单精准。
而且你这个失败重试的判断点和界面的成功失败逻辑不一致，第一个请求判断成功失败是整个脚本完成后所以我先失败后变成成功所以他的结果最后是成功的，然而你得重试判断的时候是在脚本中间就认定为失败导致了重试，所以最后就是重试了2个成功的用例，我认为失败重试应该是以你整个用例失败后再来判断是否重试，而不是中间进行重试，这样符合你原有的用例判定机制。
第二条失败停止没重试就没理解了，同样的大场景下，第一个不是也失败了他不也应该停止，然后直接第二个用例不跑么，结果是第一个跑了2遍，第二个跑了1遍停了

**Comment by wszbc** [comment]
> > ![image](https://user-images.githubusercontent.com/54612864/228406600-1d05beba-04bc-401a-8b66-871d3f5c4728.png) 第一个请求脚本断言更改了执行结果了，这里就会重试。
> > ![image](https://user-images.githubusercontent.com/54612864/228406665-18a82b61-5de0-4f6a-ab95-43d7a5c70782.png)
> > 第二条没有重试是因为失败停止了。 所以是场景配置的问题。
> 
> 先变成失败条件满足才变成成功这样能够更准确的保证断言的正确性因为争取的场景是唯一的，如果只断言失败，其实会出现一些异常情况没有写进断言，这样真的报错了断言也会通过无法暴露功能的问题，而且判断内容太多也会导致代码相对复杂，容易写错，所以才选择这种先定义为失败，只有满足成功条件才变成成功，这样对于脚本调试和定位都会更简单精准。 而且你这个失败重试的判断点和界面的成功失败逻辑不一致，第一个请求判断成功失败是整个脚本完成后所以我先失败后变成成功所以他的结果最后是成功的，然而你得重试判断的时候是在脚本中间就认定为失败导致了重试，所以最后就是重试了2遍成功的用例，我认为失败重试应该是以你整个用例失败后再来判断是否重试，而不是中间进行重试，这样符合你原有的用例判定机制，所以你现在看到的情况就是正确的用例跑了2遍
> 
> 第二条失败停止没重试就没理解了，同样的大场景下，第一个不是也失败了他不也应该停止，然后直接第二个用例不跑么，结果是第一个重试2遍，第二个跑完停了不重试

**Comment by luty2018** [comment]
“我认为失败重试应该是以你整个用例失败后再来判断是否重试，而不是中间进行重试”

你好， 你的理解是对的，目前我们确实是单个请求失败就重试，后续会改成用户来制定重试的机制，是单个请求失败重试还是整体失败重试。这样是否能满足你的需求？

**Comment by wszbc** [comment]
> “我认为失败重试应该是以你整个用例失败后再来判断是否重试，而不是中间进行重试”
> 
> 你好， 你的理解是对的，目前我们确实是单个请求失败就重试，后续会改成用户来制定重试的机制，是单个请求失败重试还是整体失败重试。这样是否能满足你的需求？

应该是可以的，其实总结就是前面说的 现在的判断会导致用例判定成功，但是实际重试了，现有的功能整体规则存在问题，如果新的规则是统一的肯定就不存在这种误判了

**Comment by luty2018** [comment]
v3.1版本我们已经调整了失败重试和失败停止的优先级， 重试完以后才会执行失败停止。
