### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#22374]
### MeterSphere 版本

v2.7.0-34d44a5e

### 联系方式

3095500370@qq.com

### 请描述您的需求或者改进建议

在循环控制器执行完成后,每个循环的结果均需手动点击展开才能看到响应数据,较为麻烦

### 请描述你建议的实现方案

在点击循环1,循环2时自动展开响应体

### 附加信息

![image](https://user-images.githubusercontent.com/49423711/222063651-d66f05de-2374-4a85-86d2-00f6d0718eca.png)

**Comment by luty2018** [comment]
感谢建议，这是个很好的交互优化，我们预计在v2.10会调整。
