### ISSUE TITLE
[BUG]性能测试部分节点监控数据未展示

### ISSUE THREAD

**Issue by LiuYj1994** [metersphere/metersphere#22377]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/22275710/222067503-cb05fec6-7185-4caf-815a-54273b91b4e9.png)
如图，未包含CPU,Memory信息，监控均采用默认配置

### 重现步骤

通过Prometheus接口api/v1/query_range返回数据排查，未展示图表均包含指标为100的值，压测对应服务，使其对应CPU资源利用率100%即可重现。
api/v1/query_range接口查询CPU指标返回数据：
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"instance":"192.168.x.x:9100"},"values":[[1677636683.794,"0.9333333310981686"],[1677636688.794,"0.9333333310981686"],[1677636693.794,"1.1166666696468894"],[1677636698.794,"1.1166666696468894"],[1677636703.794,"1.1166666696468894"],[1677636708.794,"0.9833333361893892"],[1677636713.794,"0.9833333361893892"],[1677636718.794,"0.9833333361893892"],[1677636723.794,"0.733333326255277"],[1677636728.794,"0.733333326255277"],[1677636733.794,"0.733333326255277"],[1677636738.794,"1.1666666716337204"],[1677636743.794,"1.1666666716337204"],[1677636748.794,"1.1666666716337204"],[1677636753.794,"71.31666666517656"],[1677636758.794,"71.31666666517656"],[1677636763.794,"71.31666666517656"],[1677636768.794,"99.73333333308499"],[1677636773.794,"99.73333333308499"],[1677636778.794,"99.73333333308499"],[1677636783.794,"99.98333333370586"],[1677636788.794,"99.98333333370586"],[1677636793.794,"99.98333333370586"],[1677636798.794,"100"],[1677636803.794,"100"],[1677636808.794,"100"],[1677636813.794,"99.95000000111759"],[1677636818.794,"99.95000000111759"],[1677636823.794,"99.95000000111759"],[1677636828.794,"100"],[1677636833.794,"100"],[1677636838.794,"100"],[1677636843.794,"99.94999999801318"],[1677636848.794,"99.94999999801318"],[1677636853.794,"99.94999999801318"],[1677636858.794,"99.9166666654249"],[1677636863.794,"99.9166666654249"],[1677636868.794,"99.9166666654249"],[1677636873.794,"99.96666666741173"],[1677636878.794,"99.96666666741173"],[1677636883.794,"99.96666666741173"],[1677636888.794,"100"],[1677636893.794,"100"],[1677636898.794,"100"],[1677636903.794,"99.96666666741173"],[1677636908.794,"99.96666666741173"],[1677636913.794,"99.96666666741173"],[1677636918.794,"98.35000000273187"],[1677636923.794,"98.35000000273187"],[1677636928.794,"98.35000000273187"],[1677636933.794,"91.29999999888241"],[1677636938.794,"91.29999999888241"],[1677636943.794,"91.29999999888241"],[1677636948.794,"99.98333333370586"],[1677636953.794,"99.98333333370586"],[1677636958.794,"99.98333333370586"],[1677636963.794,"99.96666666430731"],[1677636968.794,"99.96666666430731"],[1677636973.794,"99.96666666430731"],[1677636978.794,"100"],[1677636983.794,"100"],[1677636988.794,"100"]]}]}}

### 期待的正确结果

正确展示对应指标数据及图表信息

### 相关日志输出

```shell
performance-test服务报错日志：
2023-03-01 15:09:15,082 [qtp1954132378-36346] ERROR i.m.service.MetricQueryService 142 - Method[queryPrometheusMetric][query prometheus metric fail.]
2023-03-01 15:09:15,082 [qtp1954132378-36346] ERROR i.m.service.MetricQueryService ? - Method[queryPrometheusMetric][null]
java.lang.ClassCastException: null
```

### 附加信息

![image](https://user-images.githubusercontent.com/22275710/222068848-d2aa31fc-7bf7-4b8d-950a-64a10e863fbf.png)
推测此处会导致强转报错，请官方确认。
下图为本人测试复现：
![image](https://user-images.githubusercontent.com/22275710/222074864-999611d5-fcfc-4821-9067-30c392bc83ba.png)
![image](https://user-images.githubusercontent.com/22275710/222074903-67545f7a-3545-4b22-9736-33cd51dd4baf.png)

**Comment by liuruibin** [comment]
感谢提醒，这个问题我们已经修复，将在2.8.0中发布

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划在v2.8版本修复该问题。
