### ISSUE TITLE
[BUG]获取个人的APIkeys失败

### ISSUE THREAD

**Issue by xianwq** [metersphere/metersphere#22378]
### 联系方式

1056735572@qq.com

### MeterSphere 版本

v2.7

### 使用外置数据库

是

### 问题描述

新建apikeys后，列表没展示新建的key
![image](https://user-images.githubusercontent.com/45792060/222070077-fd07bb8a-978e-42ae-84bf-cc9eb4591f03.png)
![image](https://user-images.githubusercontent.com/45792060/222070173-36fddd57-26da-46c4-af0f-c2dda4d3e380.png)
提示/setting/user/key/info/的url Status Code: 404 Not Found

### 重现步骤

新建apikeys就可以复现

### 期待的正确结果

/setting/user/key/info/ 改成/setting/user/key/info就可以了；多了一个/
![image](https://user-images.githubusercontent.com/45792060/222070742-9b5af781-1c27-48d3-ba31-a9333f1a349c.png)

**Comment by xulinde** [comment]
重复，https://github.com/metersphere/metersphere/issues/22243
