### ISSUE TITLE
[BUG]metersphere调用接口返回结果和postman、jmeter不一致

### ISSUE THREAD

**Issue by gongruilinggit** [metersphere/metersphere#22384]
### 联系方式

MeterSphere 交流群41  龚瑞凌

### MeterSphere 版本

版本:   v1.20.20-lts-79d354a6

### 使用外置数据库

否

### 问题描述

1、web系统使用PHP开发
2、metersphere调用接口返回结果和postman、jmeter不一致
metersphere：
![image](https://user-images.githubusercontent.com/110591412/222078406-0cd10eb7-9f04-48cb-b127-166e58553721.png)
![image](https://user-images.githubusercontent.com/110591412/222078655-3e84bb73-b07f-4901-9132-1cb510c93983.png)
![image](https://user-images.githubusercontent.com/110591412/222078735-c6ee3866-53e7-4dcb-8243-d46a36bc0d8c.png)
![image](https://user-images.githubusercontent.com/110591412/222078967-58d55cc3-ec08-4742-83c4-a09003fa0413.png)
postman：
![image](https://user-images.githubusercontent.com/110591412/222079684-ba965dc3-b0b9-41c4-9b17-ce4062401029.png)
系统界面：审核保存操作
![image](https://user-images.githubusercontent.com/110591412/222080092-07e67150-6054-4107-95c2-2076b3b95214.png)

### 重现步骤

可能只能在PHP系统上才能复现
我对比很长时间发现只有那个user-agent的值不一样
我本地jmeter工具版本是Apache-HttpClient/4.5.12 (Java/18.0.1.1)
而metersphere上是User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.17)
metersphere调用接口也不是完全没效果，有部分数据库字段值是变更了的，还有部分未变更
首先排查了我们自己接口的问题，发现用postman和jmeter都没问题，感觉像是metersphere不兼容这种请求场景

**Comment by fit2-zhao** [comment]
感谢反馈，我看您的参数使用的是urlencode 类型， 是都需要进行 encode 是吗，目前可以看出接口其实已经发通，造成这种现象应该和入参及被测接口逻辑有关，还需在这方面检查一下。
