### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by lilyxucsj** [metersphere/metersphere#22387]
### 请描述您的问题

metersphere通过接口测试，怎么将响应数据保存为文件？
jmeter可以通过：保存响应到文件完成

**Comment by luty2018** [comment]
不好意思， 我们还不支持这个功能。
想问一下这个功能的应用场景和使用频率是什么样子的呢？

**Comment by lilyxucsj** [comment]
我们有款产品，进行接口测试时需要将响应输出的文件，已验证功能的正常

**Comment by luty2018** [comment]
请问是接口返回的是文件，还是说接口返回的内容另存为文件？

**Comment by lilyxucsj** [comment]
接口返回的签章文件PDF或者OFD等格式
- 返回结果类型为：byte[]

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/3069
了解了，可以关注一下这个issue，也是相同的需求，我们会在v3.0来规划这个需求
