### ISSUE TITLE
[BUG]编辑用例时,经常没有正常加载模块(为空), 修改其它内容后自动保存, 导致用例变成了"未规划用例"

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#22392]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

编辑用例时,经常没有正常加载模块(为空), 修改其它内容后自动保存, 导致用例变成了"未规划用例"

### 重现步骤

* 进入用例列表, 点击所属模块不为空的用例的id, 新页面打开编辑用例的窗口, 发现"所属模块"为空
* 不一定每次都能重现, 但大部分时候都会出现, 估计5次能出现4次的样子
* 另外2.7 会自动保存, 所以如果不小心点击了其它可编辑内容使之获得输入焦点, 然后又再别处点击鼠标, 使得失去焦点, 这条用例就会变成属于"未规划用例"

**Comment by lingllgh** [comment]
估计要在模块比较多, 结构复杂的环境会容易出现, 几乎100%重现
很影响用例修改操作,  必须要反复刷新, 直到能正常显示所在模块才能编辑
![image](https://user-images.githubusercontent.com/126652938/226794207-01a5a50e-6fb4-45c2-8cbc-75af208ab63f.png)

**Comment by youliyuan-fit2cloud** [comment]
> 估计要在模块比较多, 结构复杂的环境会容易出现, 几乎100%重现 很影响用例修改操作, 必须要反复刷新, 直到能正常显示所在模块才能编辑 ![image](https://user-images.githubusercontent.com/126652938/226794207-01a5a50e-6fb4-45c2-8cbc-75af208ab63f.png)

感谢再次反馈复现步骤，下个版本中已修改了，请关注发布信息，谢谢～

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
