### ISSUE TITLE
[BUG] 测试计划中用例展示的评论内容没有进行Markdown渲染

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#22399]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

测试计划中用例展示的评论内容没有进行Markdown渲染

### 重现步骤

* 进入测试计划
* 打开一条用例
* 查看用例右侧评论( 如果没有, 可以加一条带 Markdown 语法的评论)
* 评论没有进行Markdown渲染, 显示的是源码

### 附加信息

![image](https://user-images.githubusercontent.com/126652938/222098996-1176fac0-c95b-419a-8585-01849a33e957.png)

**Comment by zhouxiongjie1997** [comment]
在文本描述的用例上使用markdown格式在预览时也是没有渲染格式的

**Comment by zrfit** [comment]
您好，v2.7.1已修复该问题，待发布后可升级验证。
