### ISSUE TITLE
[FEATURE] 提供关闭用例编辑自动保存的选项

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#22395]
### MeterSphere 版本

2.7

### 请描述您的需求或者改进建议

2.7编辑用例的自动保存的功能存在问题:
* 如果写了错误的内容不想保存都没有回退的办法, 如果不小心点了别的地方还保存了
* 容易误触, 编辑框获得焦点, 然后又失去焦点就保存了, 即使没做任何修改
* 每改一个项就保存一次,  还是改完后一次保存比较好

### 请描述你建议的实现方案

回退到2.61的方案, 通过按钮手动保存, 或者提供选项让用户选择可以关闭自动保存功能

**Comment by luty2018** [comment]
非常抱歉带给你不好的体验。
这个功能我们已经在调整了，下周的小版本可以发布。

**Comment by zrfit** [comment]
您好，v2.7.1已经优化，待发布后可升级验证。
