### ISSUE TITLE
[BUG] 测试计划中测试用例的页面, 打开右上角的链接无法的进入原有的用例

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#22398]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

测试计划中测试用例的页面, 打开右上角的链接无法的进入原有的用例

### 重现步骤

* 进入测试计划
* 点中一个测试用例,
* 进入了测试用例页面
* 左上角有一个原用例的链接, 点击会出现新页面
* 在2.61版本中会跳转到原用例, 在2.7中跳转到了所在项目

### 附加信息

![image](https://user-images.githubusercontent.com/126652938/222097884-0ad43712-d4ba-4b00-8e6e-ad510fb23c52.png)

**Comment by xulinde** [comment]
v2.8.0已修复，建议您升级下版本～
