### ISSUE TITLE
[BUG] 编辑用例页面, 前置条件和备注没有进行Markdown渲染, 显示的是源码

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#22393]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

编辑用例页面, 前置条件和备注没有进行Markdown渲染, 显示的是源码

### 重现步骤

* 打开编辑一个用例
* 发现 前置条件和备注内容没有进行Markdown渲染, 显示的是源码

### 期待的正确结果

前置条件和备注内容应该进行正常Markdown渲染

### 附加信息

![image](https://user-images.githubusercontent.com/126652938/222093908-c85a0572-4138-45f6-9201-c170efe8fdca.png)

**Comment by zrfit** [comment]
您好，v2.7.1已修复该问题，待发布后可升级验证。
