### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by henryxiaolovejava** [metersphere/metersphere#224]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
**答：**v1.1.2

**Bug 描述**
简要描述您碰到的问题
**答：**系统 -> 用户，点击创建用户，前端对于密码校验逻辑存在问题，导致无法提交

**Bug 重现步骤**
1.  点击系统菜单下的用户子菜单
2.  点击创建用户，弹出form会话框
3.  对于密码输入框按照前端文案提示，进行输入，仍然无法提交，请确认前端校验逻辑

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/62002467/90085865-94fb3c00-dd4b-11ea-8e1a-0dbc3ea0f4d5.png)

**Comment by wangzhen-fit2cloud** [comment]
截图中的密码没有包含大写字母

**Comment by henryxiaolovejava** [comment]
sorry，我通过前端文案理解的是，英文可大小写字母
