### ISSUE TITLE
[BUG]测试报告链接有效期设置为15天，两三天后点击测试报告链接进去查看失败用例详情报错

### ISSUE THREAD

**Issue by bimengyan** [metersphere/metersphere#22405]
### 联系方式

15346210973@163.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

测试跟踪设置测试报告分享链接有效期为15天，两三天后点击链接进去可以正常打开，但是点击失败用例查看详情会报错
提示：连接失效，请重新获取

### 重现步骤

1、测试跟踪设置测试报告分享链接有效期为15天
2、运行测试计划生成测试报告后分享链接（测试计划内关联的为自动化用例）
3、两三天后点击链接进入，正常进入后点击失败用例查看详情活点击所有用例查看详情

### 期待的正确结果

有效期内正常查看用例详情

### 附加信息

![image](https://user-images.githubusercontent.com/117714341/222118819-f23ed39a-a182-4376-b748-7ab83c0d333d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，计划在v2.8.0版本中修复，请关注发布信息。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～

**Comment by bimengyan** [comment]
已修复，非常感谢
