### ISSUE TITLE
[FEATURE]需要统计测试管理中，所有人的工作量，包括案例编写，修改，测试执行

### ISSUE THREAD

**Issue by cds322** [metersphere/metersphere#22402]
### MeterSphere 版本

2.6.0

### 联系方式

cds322@163.com

### 请描述您的需求或者改进建议

需要统计测试管理中，所有人的工作量，包括案例编写，修改，测试执行的工作量数据；最好是能形成报表；

**Comment by luty2018** [comment]
我们是有规划做统计报表这类的功能，您提出的这些工作量是否有更具体的统计指标呢？
比如编写案例你希望统计出用例的修改具体是指修改次数?还是修改的时效等等，希望可以更具体一点，以及这些指标你期望能反馈出什么问题，这样可以更好的帮助我们去站在用户视角来设计这个功能。

**Comment by cds322** [comment]
> 您提出的这些工作量是否有更具体的统计指标呢？
> 比如编写案例你希望统计出用例的修改具体是指修改次数?还是修改的时效等等

就是比如，想统计所有项目，按人统计他的工作量，包括新增案例量，修改案例数，执行案例数。

**Comment by luty2018** [comment]
好的， 短期内我们不会做， 但是现在你可以用我们另一款开源工具DatEase做质量大屏的方式来实现。
参考：https://baijiahao.baidu.com/s?id=1741307639090201455&wfr=spider&for=pc
<img width="717" alt="image" src="https://user-images.githubusercontent.com/36292514/224951012-6269b0a8-6129-4efb-8f32-7354e4e0d47a.png">
