### ISSUE TITLE
[FEATURE]希望增加需求管理和项目管理的相关功能

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22409]
### MeterSphere 版本

2.7.0

### 请描述您的需求或者改进建议

当前需求管理和项目管理，需要使用其他工具，很不方便；
希望MS增加需求管理和项目管理的相关功能

**Comment by luty2018** [comment]
非常感谢您的建议。
现阶段我们会聚焦在测试能力建设上面，所以需求管理相关功能暂时没有规划。
