### ISSUE TITLE
[BUG]连接数据库报异常，兼容性有问题

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#22401]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

问题：

连接 sqlserver 报异常

### 重现步骤

如截图 

### 期待的正确结果

正常连接

### 附加信息

![ed9239faf44cfdd28c5b85827576846](https://user-images.githubusercontent.com/43720321/222102910-46ba2d19-246b-4d6e-9dad-dcd58ea5617c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，当前这个sqlserver版本是多少？
我们目前支持7.4.1.jre8 以下版本，下个MeterSpherer版本v2.8.0会支持7.4.1.jre8以上版本。

**Comment by goodboyxzmkk** [comment]
> 

sql 2012 r2

**Comment by goodboyxzmkk** [comment]
> 你好，在数据库驱动连接URL后面加上下面的那个参数： encrypt=true;trustServerCertificate=true; 例如：jdbc:sqlserver://xxx.xxx.xxx.xxx:1433;DatabaseName=test;encrypt=true;信任服务器证书=真；

升级2.10版本后，连接sql2008R2版本又不行了，需要怎么改参数？
