### ISSUE TITLE
[BUG]功能用例版本筛选后，模块统计数量错误

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22412]
### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

1.版本筛选后，模块统计数量错误
![37d9267d8dbe6df8e58822052e8e192](https://user-images.githubusercontent.com/55130444/222317551-f9969ed7-65a6-4716-ad46-06da591d9273.png)

### 重现步骤

1.项目管理版本管理，创建多个版本
2.同一个模块下分别创建不通版本的功能用例
3.筛选版本后，数量统计错误

### 期待的正确结果
1.筛选版本后，用例数量显示正确
_No response_

**Comment by youliyuan-fit2cloud** [comment]
你好，在最新版本v2.7.0中没有复现该问题，建议升级一下。

**Comment by kaijie-yu** [comment]
![image](https://user-images.githubusercontent.com/55130444/223003001-a5eb38f3-6369-4ed2-b826-94895055656d.png)
2.7.0这里子模块下统计数量是2个，我筛选版本后统计数量还是两个，这里是这样设计的吗

**Comment by youliyuan-fit2cloud** [comment]
> 
左侧模块需要手动刷新下试试，右侧筛选后 左侧模块树没有自动更新。

**Comment by kaijie-yu** [comment]
这需要修复吧

**Comment by youliyuan-fit2cloud** [comment]
> 这需要修复吧

嗯，会的。计划在v2.8.0中优化。

**Comment by kaijie-yu** [comment]
2.8.0已优化
