### ISSUE TITLE
[BUG]无法在新的模块下新增功能用例

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22413]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1.模块处创建多个模块，
![image](https://user-images.githubusercontent.com/55130444/222319303-bacb4ae6-6593-4304-b78d-6cad66acc7eb.png)
2.在新创建的模块下新增功能用例
![image](https://user-images.githubusercontent.com/55130444/222319368-34411044-943f-4c04-abc5-8194914dd91c.png)
3.新增用例保存之后，显示在为规划模块下
![image](https://user-images.githubusercontent.com/55130444/222319478-f2e3e4d2-8096-47da-bd71-dfd33935c084.png)
![image](https://user-images.githubusercontent.com/55130444/222319519-94b71be1-c9d2-4203-b75f-753d169144f5.png)

### 重现步骤

1.模块处创建多个模块，
![image](https://user-images.githubusercontent.com/55130444/222319303-bacb4ae6-6593-4304-b78d-6cad66acc7eb.png)
2.在新创建的模块下新增功能用例
![image](https://user-images.githubusercontent.com/55130444/222319368-34411044-943f-4c04-abc5-8194914dd91c.png)
3.新增用例保存之后，显示在为规划模块下
![image](https://user-images.githubusercontent.com/55130444/222319478-f2e3e4d2-8096-47da-bd71-dfd33935c084.png)
![image](https://user-images.githubusercontent.com/55130444/222319519-94b71be1-c9d2-4203-b75f-753d169144f5.png)

### 期待的正确结果

1.能够在所选的功能模块下新增功能用例

**Comment by luty2018** [comment]
已指派开发，等待v2.7.1发布

**Comment by kaijie-yu** [comment]
2.8.0解决
