### ISSUE TITLE
[BUG]UI自动化-场景中参数值的首位是0时，传值后，0被省略掉了

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#22417]
### MeterSphere 版本

v2.7.0-0dea7880

### 使用外置数据库

否

### 问题描述

UI场景测试中，参数值的首个字符是0，传值过程中，该参数值的首字符会被省略掉，造成断言错误

### 重现步骤

前提：参数的值首个字符为0，eg.  变量a的值为0824003
1、进入UI自动化-场景页面，执行带前提中参数的场景
2、发现执行结果不对，断言中变量a的值0被丢弃了

### 期待的正确结果

参数的值传递过程中，内容不会丢失

### 附加信息

![图片](https://user-images.githubusercontent.com/117417157/222329251-6a10fe48-5cfa-4a95-a3e1-54f2ef21976c.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
