### ISSUE TITLE
[BUG]批量移动元素库中元素到其他模块，提示成功，实际未移动

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#22411]
### MeterSphere 版本

v2.7.0-0dea7880

### 使用外置数据库

否

### 问题描述

批量移动元素库中元素到其他模块，提示成功，实际未移动

### 重现步骤

1、UI测试-元素库页面，点击左侧的一个模块，查看该模块的元素
2、勾选其中的元素，点击批量移动，选择批量移动的目的模块，点击确定
3、查看移动操作完毕后的结果

### 期待的正确结果

移动到目的模块

### 附加信息

![1](https://user-images.githubusercontent.com/117417157/222316816-9cd9c358-a355-44fb-be5e-a0a9ae40814d.gif)

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
