### ISSUE TITLE
[BUG]接口自动化场景里场景引用子场景共享cookie设置没有生效

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22410]
### MeterSphere 版本

v2.4.1

### 使用外置数据库

否

### 问题描述

1.两个接口场景a, b，b场景勾选了共享cookie调通之后，a场景引用b场景，a场景没有勾选共享cookie，，导致场景b在场景a种没有调通，
![image](https://user-images.githubusercontent.com/55130444/222308972-3a72f371-51fa-4833-93b7-94bc1fbb03fb.png)
![image](https://user-images.githubusercontent.com/55130444/222310168-cac0f20e-2b4b-4fb6-93e5-a7debdccd2cc.png)

### 重现步骤

1.创建两个场景，a和b，b场景勾选了共享cookie调通,
2.a场景不勾选共享cookie，调试，

### 期待的正确结果
同一个环境下，a场景引用b场景，b场景可以跑通
_No response_

**Comment by youliyuan-fit2cloud** [comment]
你好，目前还不支持引用的场景使用自己的cookie。
