### ISSUE TITLE
[BUG]dubbo接口测试，当参数是列表且列表中有json串的时候，整个参数对象，到服务这里是null，参数没传过去

### ISSUE THREAD

**Issue by sxqs** [metersphere/metersphere#22419]
### 联系方式

1038074253@qq.com

### MeterSphere 版本

 v1.18.0-82ba1b94

### 使用外置数据库

否

### 问题描述

[BUG]dubbo接口测试，当参数是列表且列表中有json串的时候，整个参数对象，到服务这里是null，参数没传过去

如碰到下列参数：
{"wayPointList”:”[{address":"杭州站(进站口)","cityCode":"0571","cityName":"杭州市","creatorLat":0.0,"creatorLng":0.0,"delFlag":0,"id":0,"lat":30.244174,"lng":120.181948,"orderNo":0,"poiId":"B023B07ERI","poiType":0,"realLat":0.0,"realLng":0.0,"sequence":1,"status":0,"traveledMileage":0,"type":2}]","whoName":"","whoTel":"19900000001"}

### 重现步骤

dubbo接口测试，当参数是列表且列表中有json串的时候，整个参数对象，到服务这里是null，参数没传过去

如碰到下列参数：
{"wayPointList”:”[{address":"杭州站(进站口)","cityCode":"0571","cityName":"杭州市","creatorLat":0.0,"creatorLng":0.0,"delFlag":0,"id":0,"lat":30.244174,"lng":120.181948,"orderNo":0,"poiId":"B023B07ERI","poiType":0,"realLat":0.0,"realLng":0.0,"sequence":1,"status":0,"traveledMileage":0,"type":2}]","whoName":"","whoTel":"19900000001"}

**Comment by liuruibin** [comment]
您好，这个dubbo 接口是如何定义出来的呢，我们目前没有这种API，请您提供一个方便我们复现问题

**Comment by sxqs** [comment]
这个api是公司的，我无法提供出来，参数类型如下：


"wayPointList":"[{"address":"杭州站(进站口)","cityCode":"0571","cityName":"杭州市","creatorLat":0.0,"creatorLng":0.0,"delFlag":0,"id":0,"lat":30.244174,"lng":120.181948,"orderNo":0,"poiId":"B023B07ERI","poiType":0,"realLat":0.0,"realLng":0.0,"sequence":1,"status":0,"traveledMileage":0,"type":2}]"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]dubbo接口测试，当参数是列表且列表中有json串的时候，整个参数对象，到服务这里是null，参数没传过去 (Issue #22419)





 
您好，这个dubbo 接口是如何定义出来的呢，我们目前没有这种API，请您提供一个方便我们复现问题

**Comment by liuruibin** [comment]
我自己做了一个这样的接口并没有复现出来
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/23045261/224353999-090e2a26-5e23-4b65-849a-121b0627b090.png">

**Comment by liuruibin** [comment]
使用String来接收JSON格式的参数需要进行转义，如果您还有其他问题请重新提交ISSUE
