### ISSUE TITLE
[BUG]TCP 协议前置脚本-报文头添加长度脚本只使用于 groovy，其他类型脚本报错，建议修改脚本模板，或者隐藏其他脚本的生成入口

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22422]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.20-lts

### 使用外置数据库

否

### 问题描述

TCP 协议前置脚本-报文头添加长度脚本只使用于 groovy，其他类型脚本报错，建议修改脚本模板，或者隐藏其他脚本的生成入口
![image](https://user-images.githubusercontent.com/30038088/222347308-88b249ca-a7cb-4d91-b97f-b37fcc020e8f.png)

只有 groovy 正常
![image](https://user-images.githubusercontent.com/30038088/222347470-e0b37354-abf5-4eb2-bd31-4497858515c8.png)

### 重现步骤

1.创建一个 TCP 协议的 mock 接口
![image](https://user-images.githubusercontent.com/30038088/222348174-12d69b8c-9cf2-463d-bfdf-08e2dddbc27e.png)
2.创建一个 TCP 协议 case，添加前置脚本，选择【报文头添加长度】脚本，如下图
![image](https://user-images.githubusercontent.com/30038088/222347470-e0b37354-abf5-4eb2-bd31-4497858515c8.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，计划下个版本优化。

**Comment by song-tianyang** [comment]
感谢您的提醒和建议。  我们决定在后续的版本中去掉这两个脚本。

这两个脚本当时是配套x-pack加强包里的ESB报文格式使用的，用于为他们计算、去除报文头的。

ESB报文功能目前被我们取消了，使其回归为最本质的TCP协议。这两个脚本也没有太大的用处了。

谢谢！
