### ISSUE TITLE
[BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#22424]
### MeterSphere 版本

v2.7.0-0dea7880

### 使用外置数据库

否

### 问题描述

UI场景中在中间过程中加入带有条件控制器的指令，该指令所在步骤启用后，其下步骤中的传参会出现问题；禁用该步骤后传值恢复正常

### 重现步骤

前提：存在带有条件控制器的指令
1、UI测试-场景编辑页面，增加前提中的指令为中间步骤后调试该场景
2、禁用步骤1中增加的指令步骤后，再次调试该场景

### 期待的正确结果

新增指令步骤后，其下步骤的传参，值无问题

### 附加信息

![图片](https://user-images.githubusercontent.com/117417157/222353324-e08ffc29-20c1-41d1-b820-2f0d50dd653a.png)
![图片](https://user-images.githubusercontent.com/117417157/222353673-c1872bd8-397c-405d-bd04-c713bc9c066e.png)

**Comment by zrfit** [comment]
您好！感谢您的反馈！
1、在最新版本根据您的截图配置创建相似场景未复现您的问题，是必现的吗？方便导出场景或者私下远程复现一下吗？
2、您的第一张截图，引用指令：配置字段显示-入参searchname是自定义入参吗？复制指令：计量-实时-普通查询-入参no1是自定义入参吗？确定下这2个参数的来源，且变量参数采用就近原则:步骤内数据提取>入参>场景变量>环境变量。

**Comment by vivage** [comment]
应该是必现，操作几次都这样，参数的使用情况，具体见附件



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424)





 
您好！感谢您的反馈！
 1、在最新版本根据您的截图配置创建相似场景未复现您的问题，是必现的吗？方便导出场景或者私下远程复现一下吗？
 2、您的第一张截图，引用指令：配置字段显示-入参searchname是自定义入参吗？复制指令：计量-实时-普通查询-入参no1是自定义入参吗？确定下这2个参数的来源，且变量参数采用就近原则:步骤内数据提取&gt;入参&gt;场景变量&gt;环境变量。

**Comment by zrfit** [comment]
&nbsp;您好，未看到附件呢，直接发邮件给我吧，github上传有的格式不支持。
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Mar 7, 2023 12:23 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424)

&nbsp;



 应该是必现，操作几次都这样，参数的使用情况，具体见附件 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月6日(星期一) 下午2:23 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424) 
 
 
 
 
 
   
 您好！感谢您的反馈！ 
  1、在最新版本根据您的截图配置创建相似场景未复现您的问题，是必现的吗？方便导出场景或者私下远程复现一下吗？ 
  2、您的第一张截图，引用指令：配置字段显示-入参searchname是自定义入参吗？复制指令：计量-实时-普通查询-入参no1是自定义入参吗？确定下这2个参数的来源，且变量参数采用就近原则:步骤内数据提取&amp;gt;入参&amp;gt;场景变量&amp;gt;环境变量。

**Comment by vivage** [comment]
上次就是直接回复邮件的，现在再次回复所有，再看看附件吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424)





 &amp;nbsp;您好，未看到附件呢，直接发邮件给我吧，github上传有的格式不支持。 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Date: &amp;nbsp;Tue, Mar 7, 2023 12:23 PM 
 To: ***@***.***&amp;gt;;  
 Cc: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424) 
 
 &amp;nbsp; 
 
 
 
  应该是必现，操作几次都这样，参数的使用情况，具体见附件  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年3月6日(星期一) 下午2:23  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [metersphere/metersphere] [BUG][UI测试]场景中加入一个带条件控制器的指令后，传值出现问题 (Issue #22424)  
   
   
   
   
   
     
  您好！感谢您的反馈！  
   1、在最新版本根据您的截图配置创建相似场景未复现您的问题，是必现的吗？方便导出场景或者私下远程复现一下吗？  
   2、您的第一张截图，引用指令：配置字段显示-入参searchname是自定义入参吗？复制指令：计量-实时-普通查询-入参no1是自定义入参吗？确定下这2个参数的来源，且变量参数采用就近原则:步骤内数据提取&amp;amp;gt;入参&amp;amp;gt;场景变量&amp;amp;gt;环境变量。

**Comment by zrfit** [comment]
您好，最新版本v2.10-lts未复现该问题，建议升级尝试，如仍有问题请将场景单独发送到邮箱rui.zhang@fit2cloud.com。
