### ISSUE TITLE
[BUG] 消息设置-接口定义新增api，修改api，新增case，修改case站内通知不生效

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22420]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1.消息通知接口定义增加创建api站内通知方式
![image](https://user-images.githubusercontent.com/55130444/222341240-8552127d-1050-49ee-9137-221edf9641d3.png)
2.新创建接口后，没有收到消息通知
![image](https://user-images.githubusercontent.com/55130444/222341423-b65d1387-bdcf-4d4c-8be5-fa8149fc08cf.png)

### 重现步骤

1.消息通知接口定义增加创建api站内通知方式
2.新增api，
3.消息通知收不到新增接口的通知

### 期待的正确结果

1，增加新增api接口的站内消息通知后，新增api后可以收到消息通知

**Comment by youliyuan-fit2cloud** [comment]
你好，消息通知里面设置 选中的接收人是 某个人（实际用户名），站内通知的是 在 @提到我的 tab页面；
消息通知选中的接收人是 “创建人” or “关注人” 这种的站内通知 在 “系统通知” tab 页。
请再次确认是否重现。

**Comment by kaijie-yu** [comment]
重新验证了一下，新增api，站内通知在两个tab页面都没有收到消息
