### ISSUE TITLE
[BUG]接口定义>>API 【test】页签：点击测试，响应结果为503；但是系统操作日志信息为【调试  成功】，并且改日志无任何明细

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22429]
### MeterSphere 版本

V2.7

### 使用外置数据库

否

### 问题描述

[BUG]接口定义>>API 【test】页签：点击测试，响应结果为503；但是系统操作日志信息为【调试  成功】，并且改日志无任何明细

### 重现步骤

[BUG]接口定义>>API 【test】页签：点击测试，响应结果为503；但是系统操作日志信息为【调试  成功】，并且改日志无任何明细

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/222359873-cc9ebecb-e0bf-4c01-80e5-2a36b27b0311.png)
![image](https://user-images.githubusercontent.com/78218624/222360448-fb32cbc1-9ad9-4d42-ad54-1b0839ed6713.png)

**Comment by fit2-zhao** [comment]
感谢反馈，这里是操作日志，非执行结果并不会显示执行内容，所以这里只是代表这次操作是否成功或失败，
