### ISSUE TITLE
[FEATURE] 测试跟踪导出-plan-report.html优化

### ISSUE THREAD

**Issue by gengxiaoxiaoxin** [metersphere/metersphere#22431]
### MeterSphere 版本

main

## 静态资源的内联
目前导出的html，没有图片和字体等资源文件的内联，显示空白。
## tree shaking
![image](https://user-images.githubusercontent.com/29268441/222364527-0b7d9be3-5aa7-4115-941f-e967d88b63c7.png)

## 静态资源的内联
Webpack5配置assert-inline（不过还需要解决多entry下不要影响其他entry）
```js
//vue.config.js
chainWebpack: config => {
    // support font,image or athor file type
    config.module
      .rule('font-inline')
      .test(/\.(woff2?|eot|ttf|otf)(\?.*)?$/i)
      .type('asset')
      .parser({
        dataUrlCondition: {
          maxSize: 100 * 1024 // you want inline100kb
        },
      })
}
```

## tree shaking
以下几个打包的大头：
1.  element-ui 按需引入（需同时配置按需引入时国际化）
2. brace在导出报告这个业务中，是否引入了过多的语言mode
3. fortawesome 是全量引入，是否可以优化为需要哪个图标，library.add一个

**Comment by luty2018** [comment]
感谢建议。我们调研看看。

**Comment by AgAngle** [comment]
你好，你的建议非常到位，这个问题有待排期，也欢迎你多提 pr ！

**Comment by zhangzhaox** [comment]
太专业了看不懂
