### ISSUE TITLE
[FEATURE]场景a引用子场景b(b勾选共享cookie)后，期望子场景可以使用自己的cookie

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22432]
### MeterSphere 版本

v2.4.1

### 请描述您的需求或者改进建议

1.两个接口场景a, b，b场景勾选了共享cookie调通之后，a场景引用b场景，a场景没有勾选共享cookie，，导致场景b在场景a种没有调通，
![image](https://user-images.githubusercontent.com/55130444/222308972-3a72f371-51fa-4833-93b7-94bc1fbb03fb.png)
![image](https://user-images.githubusercontent.com/55130444/222310168-cac0f20e-2b4b-4fb6-93e5-a7debdccd2cc.png)
2.期望可以支持子场景使用自己的cookie

**Comment by luty2018** [comment]
b场景需要勾选使用原场景环境
