### ISSUE TITLE
[QUESTION]K8S部署方式中，如何配置REDIS多节点、SENTINEL

### ISSUE THREAD

**Issue by Jasonnnnnnnn** [metersphere/metersphere#22434]
### 请描述您的问题

K8S部署方式中，如何配置REDIS多节点、SENTINEL？

**Comment by liuruibin** [comment]
首先按照您喜欢的方式部署好redis集群，然后修改ConfigMap配置中的redisson.yml 这一部分，配置详情参见 https://github.com/redisson/redisson/wiki/Table-of-Content
