### ISSUE TITLE
[BUG]切到 TCP 协议，进入 mock模块，发现此处显示的是 http 协议的mock环境地址

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22438]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

切到 TCP 协议，进入 mock模块，发现此处显示的是 http 协议的mock环境地址

### 重现步骤

切到 TCP 协议，进入 mock模块，发现此处显示的是 http 协议的mock环境地址
![3462805067bb87cb40a3b7e2c3afa2d](https://user-images.githubusercontent.com/104960608/222390719-767df754-ede6-48d7-bad6-257557c0f2c1.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
