### ISSUE TITLE
[BUG]Jmeter上调试通过的跨线程传参脚本上传到平台后性能测试中运行报错

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#22437]
### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

Jmeter上调试通过的跨线程传参脚本上传到平台后运行报错

### 重现步骤

1、Jmeter里创建2个线程组：线程组1、线程组2
2、线程组1添加一个登录接口，返回token通过跨线程同步的方式传递给线程组2使用，调试通过，返回正常
3、上传Jmeter脚本到平台
4、平台上运行测试

### 期待的正确结果

平台上能正常运行跨线程传参脚本

### 附加信息

![image](https://user-images.githubusercontent.com/5198427/222385806-061be578-eee1-41f5-89ce-aa364adea9b7.png)
![image](https://user-images.githubusercontent.com/5198427/222386005-a6a1d742-91d8-4892-90f3-d191013d85b3.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，在MeterSphere平台执行前，把下图中的“顺序执行场景”开关打开试试吧，你这个线程组是并行执行了所以没有取到参数值。
![image](https://user-images.githubusercontent.com/54612864/223375713-0a0df702-8580-4260-8029-20ad236cfcdd.png)

**Comment by youliyuan-fit2cloud** [comment]
由于长时间未反馈且没有复现，故关闭该问题。
