### ISSUE TITLE
[BUG]v2.6.1 开启ui测试之后，加载js文件要等40s。 同一个服务器安装2.6版本不会这样

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22430]
### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

v2.6.1 开启ui测试之后，加载js文件要等40s。 同一个服务器安装2.6版本不会这样

怀疑有前端性能问题，请优化

访问网址http://123.56.50.204:8081/

### 重现步骤

v2.6.1 开启ui测试之后，加载js文件要等40s。 同一个服务器安装2.6版本不会这样

怀疑有前端性能问题，请优化

访问网址http://123.56.50.204:8081/
![v2 6 1 加载页面要很久，磁盘够用](https://user-images.githubusercontent.com/43202800/222369692-246d1d27-602d-41e5-b288-c64907e394ac.png)

**Comment by xhy12** [comment]
![微信图片_20230302161205](https://user-images.githubusercontent.com/43202800/222369836-959b8169-552c-45b2-ae28-4264de3dd8ac.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.7未复现该问题，请升级尝试。

**Comment by xhy12** [comment]
![微信图片_20230309174938](https://user-images.githubusercontent.com/43202800/223984536-cd49060e-9c92-43d8-865e-dad9d0544374.png)

**Comment by zrfit** [comment]
已经反馈给研发和产品，计划v2.8优化。

**Comment by maninhill** [comment]
这个问题要重点跟进。

**Comment by liuruibin** [comment]
页加载速度和网速有关，在服务拆分的时候我们使用过两种方案: 

1. 以前首次加载没有预加载其他模块的时候进系统后切换模块会出现短暂的白屏。
2.现在首次加载会预加载所有模块的首页静态资源，只是首次慢，进去切换模块就正常了。

我们现行方案是2，这对网速有一定的要求
