### ISSUE TITLE
[BUG]UI自动化测试指令里入参设置函数后，循环时随机字符串函数出来的都是同一值

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22441]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.6.1

### 使用外置数据库

否

### 问题描述

UI自动化测试指令里入参设置函数后，循环时随机字符串函数出来的都是同一值
<img width="438" alt="image" src="https://user-images.githubusercontent.com/83771182/222398027-851edc62-05fd-41bc-81ea-ee807d811a05.png">

### 重现步骤

UI自动化测试指令里入参设置函数后，循环时随机字符串函数出来的都是同一值

**Comment by zrfit** [comment]
您好，感谢您的反馈！已知问题，由于设计原因，整个ui流程是一个js文本，里面的jmeter函数例如${__Random(1,20)} 会在加载jmx时进行计算（仅一次），所以循环中取到的值都是第一次计算获得的，暂时没有好的解决方案，后续进行研发调研，有合理方案后进行优化。同问题https://github.com/metersphere/metersphere/issues/22106
