### ISSUE TITLE
[BUG]创建CSV场景变量，关联一个CSV文件（包含多列多行数据），脚本中有嵌套循环，且每个循环退出都以csv文件变量作为判断条件，出现循环次数不对的情况。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#22447]
### 联系方式

王进

### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

创建CSV场景变量，关联一个CSV文件（包含多列多行数据），脚本中有嵌套循环，且每个循环退出都以csv文件变量作为判断条件，出现循环次数不对的情况。

分析发现MS生成的jmeter脚本里每个循环，以及嵌套循环下面都有相同的csv组件，导致循环次数不对。
用户想要的只是在线程组下面第一个循环里添加一个csv配置原件。循环以及嵌套循环下面不加csv配置原件。
这个原因和现在的场景变量设计有关。

### 重现步骤

客户这边的重现步骤：
1. 添加一个CSV场景变量，这个CSV有几十列数据。
2. 在场景里添加循环，循环推出条件 ${c_run}不等于"end"
3. 在循环里再嵌套循环，同时发出请求测试。
4. 发现循环次数不对。
（金融客户不可以外泄数据和脚本）

### 期待的正确结果

客户想要的是在第一个层级的循环里针对CSV所有记录做循环。
嵌套循环里的循环，循环次数不对，从测试看是对所有记录又做了一次循环。

### 附加信息

这个问题和目前的场景变量设计有关系。 从这个客户的现象看，场景变量的设计，应该是放到右下脚的“+”号里，让用户可以在不同层级，不同地方按需添加各种场景变量。 

因为是企业客户，脚本和数据不可以放到网上。请线下联系演示。

**Comment by fit2-zhao** [comment]
感谢反馈，这个#21970 优化需求和您这个诉求相同，请关注后续动态。

**Comment by 35plus** [comment]
感谢，有没有可能给一个大概优化或修复时间？
