### ISSUE TITLE
[BUG]接口测试-批量导入的参数后，velue 值多一个空格

### ISSUE THREAD

**Issue by aawoshilu** [metersphere/metersphere#22454]
### 联系方式

交流群32 name：小测试

### MeterSphere 版本

v2.7.0-34d44a5eb 

### 使用外置数据库

否

### 问题描述

直接复制的谷歌浏览器中的 请参数，然后批量导入后，请求体中的值都自动多一个空格，
是吧“:”冒号用空替换吗？
![image](https://user-images.githubusercontent.com/126857082/222677611-ee9592c5-5472-43df-ba80-759fde7e34d6.png)
![image](https://user-images.githubusercontent.com/126857082/222677680-adbd641e-d994-4faf-84ce-a1bd55e3bc6d.png)

### 重现步骤

activity_status: 2
user_join_model: 1
如上着2个 复制后 直接批量导入

### 期待的正确结果

请求体  参数值 不能前面自动带有空格

**Comment by fit2-zhao** [comment]
感谢反馈，非常抱歉给您带来了不好的体验，从您提供的这两个参数中来看是带有空格的，所以在导入前请自行去除空格，平台不会自动给去除，因为对于一些特殊用户定长报文的业务是需要参数前面带空格或其他占位。
