### ISSUE TITLE
[BUG]接口请求体form-data批量添加后字段存在换行导致接口无法正常测试

### ISSUE THREAD

**Issue by tqq1994516** [metersphere/metersphere#22450]
### 联系方式

472159011@qq.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

是

### 问题描述

接口测试中，接口body使用form-data，通过批量添加进行添加参数，从其他文档中将参数复制至添加添加框中，添加后发送请求字段值后会多一个回车，导致后端接口解析值异常

### 重现步骤

请求内容如下
请求地址:
http://xxx/openapi/aidipkg/v1/pkg/upload_package
请求头:
Connection: keep-alive
X-Forwarded-User: 
Content-Length: 3250
Content-Type: multipart/form-data; boundary=TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Host: 
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.6)

Cookie :
Body:
POST http://xxx/openapi/aidipkg/v1/pkg/upload_package

POST data:
--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="pkg_name"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

test-oss

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="desc"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="version"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

11

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="storage_location"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

oss_token
--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="ipd_id"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

SD2018-R62

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="version_type"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

develop

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="scene"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

ADAS

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="level"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

system

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="module"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="use_for_dev"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="version_status"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

NotStarted

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="source_version"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="dev_type"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="task_type"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="sign"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

false

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="level_usr"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

public

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="members"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

{"departments":["aiot"]}

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="file_name"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

render_yuce.tar.gz

--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma
Content-Disposition: form-data; name="type"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

pkg
--TXdTlw92M0ijQQ8A3XPRACSKOlFJYma--

Cookie Data:

### 期待的正确结果

字段值后无回车

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问是不是通过复制粘贴的方式批量添加的呢？   如果是的话，请检查一下复制的文本格式，可能是复制的文本中带了回车字符

**Comment by tqq1994516** [comment]
> 您好，没有复现这个问题，请问是不是通过复制粘贴的方式批量添加的呢？ 如果是的话，请检查一下复制的文本格式，可能是复制的文本中带了回车字符

复制的文本有回车啊，不然我应该怎么区分kv，我在批量添加的表单里不也是用回车分区多个字段吗

**Comment by youliyuan-fit2cloud** [comment]
你好，请反馈下执行后错误的截图信息，响应结果中（请求内容详情 ）方便我们快速定位问题，感谢您的理解和支持 ～

**Comment by tqq1994516** [comment]
> 你好，请反馈下执行后错误的截图信息，响应结果中（请求内容详情 ）方便我们快速定位问题，感谢您的理解和支持 ～

复现步骤 麻烦看下  那个就是系统中的 发出去的请求的详情

**Comment by youliyuan-fit2cloud** [comment]
> Content-Disposition: form-data; name="pkg_name"
> Content-Type: text/plain; charset=UTF-8
> Content-Transfer-Encoding: 8bit

你好，我们是用的上面的信息复制后测试的，没有复现呐～ 
 如下图，请检查下你这边复制后显示的是否一致？
![image](https://user-images.githubusercontent.com/54612864/225817033-5ee1e5e5-7696-4fda-bff5-9ad2a201bdba.png)

“添加后发送请求字段值后会多一个回车，导致后端接口解析值异常” 这个异常的截图请贴出来看看 ？

**Comment by tqq1994516** [comment]
> > Content-Disposition: form-data; name="pkg_name"
> > Content-Type: text/plain; charset=UTF-8
> > Content-Transfer-Encoding: 8bit
> 
> 你好，我们是用的上面的信息复制后测试的，没有复现呐～ 如下图，请检查下你这边复制后显示的是否一致？ ![image](https://user-images.githubusercontent.com/54612864/225817033-5ee1e5e5-7696-4fda-bff5-9ad2a201bdba.png)
> 
> “添加后发送请求字段值后会多一个回车，导致后端接口解析值异常” 这个异常的截图请贴出来看看 ？

请问你们有按照我描述里复现吗？

![msedge_r2ZaRCrS1D](https://user-images.githubusercontent.com/61398122/225836978-06e2ee61-6f3d-4641-84d2-5fa4bfce9113.gif)
从其他文档中复制过来含有回车，发送时也会带上，如果直接在编辑框中输入不会

**Comment by youliyuan-fit2cloud** [comment]
操作步骤一样的，不过是用的最新版本v2.7.1，升级到v2.7.1 试试呢？
![image](https://user-images.githubusercontent.com/54612864/226227743-693d4d4d-92b8-41a5-a4dc-a1155adcb945.png)

**Comment by tqq1994516** [comment]
升级至2.7.1依然存在该问题

**Comment by youliyuan-fit2cloud** [comment]
你好，之前我们在MacBook 电脑正常的，使用windows系统确实存在该问题，后续版本会修复，感谢支持和持续反馈～

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
