### ISSUE TITLE
[BUG]文件上传无法设置implementation为Java模式

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#22456]
### MeterSphere 版本

v1.20.18-lts-783ad1cf

### 使用外置数据库

否

### 问题描述

文件上传后，请求报错
{
    "code": 4,
    "title": null,
    "msg": "action failed",
    "description": null,
    "data": "Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found"
}

### 重现步骤

Jmeter中设置implementation为Java模式，上传接口到MS中，可正常执行。
直接在MS中创建的file上传接口，无法设置implementation为Java模式。

**Comment by youliyuan-fit2cloud** [comment]
你好，目前MS中还不支持设置Java模式，具体原因可以参考下面的issue，感谢您的理解和支持～

https://github.com/metersphere/metersphere/issues/18370
