### ISSUE TITLE
[BUG]测试跟踪-测试计划-定时任务，设置重试失败次数，通知的报告和测试跟踪的报告不一致

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22451]
### MeterSphere 版本

2.7.0

### 使用外置数据库

是

### 问题描述

[BUG]测试跟踪-测试计划-定时任务，设置重试失败次数，通知的报告和测试跟踪的报告不一致

### 重现步骤

<img width="304" alt="image" src="https://user-images.githubusercontent.com/25762331/222623887-cf314c25-28e3-48e2-a79a-9ad6debe407b.png">
![image](https://user-images.githubusercontent.com/25762331/222623893-ded0fbcc-bdc8-411b-934e-17ab8d034253.png)

测试跟踪报告：
![image](https://user-images.githubusercontent.com/25762331/222623928-54c952fa-1bea-4ba3-ab24-08fd7c476943.png)

飞书通知报告：
![image](https://user-images.githubusercontent.com/25762331/222623941-f6bf790f-0ff5-4a37-8306-94131e571e7c.png)

**Comment by xulinde** [comment]
使用v2.7.0未复现该问题，建议您升级下版本

**Comment by fusu-qa** [comment]
> 使用v2.7.0未复现该问题，您可以看下飞书的通知报告，返回的响应内容是什么？还有，定时任务的间隔时间是多久

飞书报告里的接口返回的状态码是200，定时任务1小时一次

**Comment by xulinde** [comment]
> > 使用v2.7.0未复现该问题，您可以看下飞书的通知报告，返回的响应内容是什么？还有，定时任务的间隔时间是多久
> 
> 飞书报告里的接口返回的状态码是200，定时任务1小时一次

是每次定时任务的结果都不一致，还是偶发

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
