### ISSUE TITLE
[BUG]v2.7.0-34d44a5eb 版本中 接口定义-批量添加导入的参数 都是默认非必填

### ISSUE THREAD

**Issue by aawoshilu** [metersphere/metersphere#22452]
### 联系方式

交流群32 name：小测试

### MeterSphere 版本

v2.7.0-34d44a5eb 

### 使用外置数据库

否

### 问题描述

一个接口的参数很多，我直接抓包数据批量添加后，在请求体展示页面中 是否必填都默认 是非必填 

### 重现步骤

随意找个接口，请求体-批量导入，就行
![image](https://user-images.githubusercontent.com/126857082/222657837-ef4e272e-4ef3-4d96-9976-d29f5989d3a4.png)

### 期待的正确结果

1、希望批量添加后默认都是必填参数

### 附加信息

![image](https://user-images.githubusercontent.com/126857082/222657836-a783412f-6d9d-4dbb-9c2f-c8e4f64fee37.png)

**Comment by fit2-zhao** [comment]
感谢您的反馈，很抱歉给您带来了不好的体验，目前的设计确实是这样，对于必填和非必填的默认选择确实两难，但是大多用户的接口参数，必填项是小于非必填项的，所以从导入后修改的数量来看 我们更倾向于 非必填默认，后续我们可以考虑其他方向来优化，比如支持批量修改。
