### ISSUE TITLE
[BUG]通过SwaggerURL导入接口，接口的body有更新，但是重新导入swagger ，接口没有对应更新

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22459]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

通过SwaggerURL导入接口，接口的body有更新，但是重新导入swagger ，接口没有对应更新。

### 重现步骤

1.选择路径为/environment/list/{goPage}/{pageSize} 的接口，原接口有name值，现在删除请求体里name，保存
![image](https://user-images.githubusercontent.com/55130444/223013131-c2b775c7-aa1b-499c-b44c-b698269b21a1.png)
2.接口列表通过Swagger URL导入接口，选择覆盖，同步覆盖api，保存
![image](https://user-images.githubusercontent.com/55130444/223012561-3df16e38-28e6-4cd5-a68e-273c90380e3a.png)
3.更新后的接口仍然没有name
![image](https://user-images.githubusercontent.com/55130444/223013420-65fdf022-fea7-49d4-87f4-8ef8da09d746.png)

### 期待的正确结果

通过SwaggerURL导入的接口有请求体变更，重新导入swagger ，平台上对应的接口能对应更新

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现您的问题。重复导入时选中的模块是否和原模块一致？导致新生成了数据？

**Comment by kaijie-yu** [comment]
之前能够复现，刚刚确认了下，确实是复现不出来。

**Comment by youliyuan-fit2cloud** [comment]
> 

复现再重新提issue吧，这个我关闭啦。
