### ISSUE TITLE
[BUG]测试计划 - 报告处，统计的百分百加起来超过 100% 了

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22457]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

测试计划 - 报告处，统计的百分百加起来超过 100% 了

### 重现步骤

测试计划 - 报告处，统计的百分百加起来超过 100% 了
![image](https://user-images.githubusercontent.com/104960608/223010021-3395a181-2cc4-4d81-a9db-b691f2454d0d.png)

**Comment by xulinde** [comment]
6个接口可以复现该问题，后续版本修复
<img width="726" alt="image" src="https://user-images.githubusercontent.com/64065190/223090149-2d62f858-4f92-4783-8149-df7ba8570b76.png">

**Comment by xulinde** [comment]
v2.8.0已修复，建议您升级下版本～
