### ISSUE TITLE
[FEATURE]在接口定义 模块中能不能增加一个批量删除 批量导出 批量编辑的按钮呢，在请求头请求体中

### ISSUE THREAD

**Issue by aawoshilu** [metersphere/metersphere#22453]
### MeterSphere 版本

v2.7.0-34d44a5eb 

### 联系方式

交流群32 name：小测试

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/126857082/222666936-62b16c30-eb45-4119-a19f-5af867a18193.png)

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/126857082/222666930-b1953c72-19ff-4292-9777-5defd3c32314.png)

**Comment by luty2018** [comment]
不好意思， 请问这个加这个功能是要覆盖什么样的场景？

**Comment by luty2018** [comment]
不好意思， 请问这个加这个功能是要覆盖什么样的场景？
