### ISSUE TITLE
[BUG]接口自动化模块中新增一个自定义请求，保存后另存为接口定义，发现在接口定义的API和CASE中都新增了这一条数据

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22467]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

接口自动化模块中新增一个自定义请求，保存后另存为接口定义，发现在接口定义的API和CASE中都新增了这一条数据，感觉应该只有接口API中新增这条才对。
<img width="634" alt="7d5ce26f4eb754edabbbc8c72ca171e" src="https://user-images.githubusercontent.com/83771182/223043921-376aabcc-5c10-4a4b-b7f9-307f8c48a64d.png">
<img width="713" alt="6c4845c34083f7cdbddea4528e1b4db" src="https://user-images.githubusercontent.com/83771182/223043945-bb12f859-a327-4816-88ed-db857f587c96.png">

发现在接口定义的API和CASE中都新增了这一条数据
<img width="741" alt="1678087606080" src="https://user-images.githubusercontent.com/83771182/223044807-0d65903e-7514-4be8-addf-df4e72f25dee.png">

### 重现步骤

接口自动化模块中新增一个自定义请求，保存后另存为接口定义，发现在接口定义的API和CASE中都新增了这一条数据

**Comment by luty2018** [comment]
设计如此，创建api的时候会给用户创建一条相应的case供用户后续直接复制或引用。
