### ISSUE TITLE
[BUG]环境配置： 环境生效规则-同一接口设置环境[模块] >[路]>[无]， 实际操作不是这样，是最新添加什么规则按什么规则生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22460]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

同一接口设置环境[模块] >[路]>[无]， 实际操作不是这样，是最新添加什么规则按什么规则生效

### 重现步骤

![cdddee668df1c65388f4ee3b45dc6d3](https://user-images.githubusercontent.com/43202800/223020970-e31b0c0e-956a-4648-b2d4-431f63c233ed.png)

1、先添加的模块在添加路径，后添加的路径生效
2、然后再添加模块，模块的地址又生效了
不是按模块>路径的方式生效

**Comment by xhy12** [comment]
![4f781461ec684f644bb3d327522cbd6](https://user-images.githubusercontent.com/43202800/223021699-fa43ef80-50cc-4a1e-9e53-83b84e6b2e50.png)

**Comment by xhy12** [comment]
环境配置:路径怎么匹配多个呢，我看添加多个只有一个生效，用的空格分隔

**Comment by luty2018** [comment]
模块和路径的优先级>无
而模块和路径是优先匹配到哪个就用哪个，并没有模块>路径这个规则。
