### ISSUE TITLE
[BUG]接口自动化，场景引用，场景设置开启优先使用当前场景，实际上使用的还是原场景

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22465]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

接口自动化，场景引用，场景设置开启优先使用当前场景，实际上使用的还是原场景

### 重现步骤

新增两个场景，场景1中前置脚本将a设置值10，
![image](https://user-images.githubusercontent.com/55130444/223035626-52fe04b7-141a-4d9e-8656-066d92f80417.png)
场景2中将a设置值20，
![image](https://user-images.githubusercontent.com/55130444/223035652-d86d8c18-248b-43b8-9753-2ab520d57789.png)
场景1引用场景2，
场景2里设置为优先使用当前场景，然后发起请求。场景2中a的值还是20.
![image](https://user-images.githubusercontent.com/55130444/223035700-4f2c41f5-9911-4a85-b80d-d7898ea8c4c5.png)
![image](https://user-images.githubusercontent.com/55130444/223035336-58d40031-b89a-4a60-972f-9bd67768577f.png)

### 期待的正确结果

场景2中a的值为10

**Comment by luty2018** [comment]
脚本变量属于过程变量， 你这种情况不需要选这些设置就行了。

**Comment by kaijie-yu** [comment]
不勾选还是使用的原场景的变量
