### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by oh-jy** [metersphere/metersphere#22479]
### MeterSphere 版本

v1.20.12-lts

### 联系方式

MS微信52群

### 请描述您的需求或者改进建议

测试计划A比如是执行1个小时， B是1小时后执行， 但是遇到特殊情况A执行超时半个小时，B计划是不会等A计划执行完才执行的。
希望支持测试计划顺序执行。

### 请描述你建议的实现方案

希望支持测试计划顺序执行。

**Comment by luty2018** [comment]
你好， 我们测试计划支持选择运行模式，建议你升级版本使用哈。
![image](https://user-images.githubusercontent.com/36292514/223302443-372d7ebc-4cc0-41c6-8e52-ec97342dcfe2.png)
