### ISSUE TITLE
[BUG]场景中引用case,case中添加的后置操作调换顺序后，场景中顺序未变化

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22474]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

场景中引用case,case中添加的后置操作调换顺序后，场景中引用的case后置操作顺序未变化

### 重现步骤

1.场景中引用case，case的后置操作顺序如图
![image](https://user-images.githubusercontent.com/103627487/223055166-8cf47510-2c07-435d-9ec7-ca0579410d80.png)
2.case后置操作顺序变化
![image](https://user-images.githubusercontent.com/103627487/223055372-db84503a-7a8e-44fe-b34a-e9bf8f95b767.png)
3.查看场景中case的后置操作顺序未变化
![image](https://user-images.githubusercontent.com/103627487/223055630-3cb3d358-7751-4cb5-b203-9b4c676e4d02.png)

**Comment by fit2-zhao** [comment]
感谢反馈，会在v1.20.21-lts中修复这个问题。
