### ISSUE TITLE
metersphere平台已对接jira，在测试计划中提交缺陷时，报 Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown

### ISSUE THREAD

**Issue by xiaoroubao999** [metersphere/metersphere#22476]
### 联系方式

微信手机同号：18651606429

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

metersphere平台已对接jira，这个在个人信息加了自己的信息后，个人信息Basic Auth校验通过，在测试计划中提交缺陷时，报
Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown

### 重现步骤

1、在测试计划提交缺陷，填写bug人即可

### 期待的正确结果

1、可以正常提交

**Comment by xulinde** [comment]
没有复现该问题，jira插件版本和ms版本一致吗？项目关联jira，模版选的默认模版还是jira缺陷模版？

**Comment by xiaoroubao999** [comment]
插件版本：






在这边是验证通过的












这边一旦填写了账号信息，就会报那个错，这边如果不填写，可以提交成功，只不过是默认的工作空间配置的账号信息








麻烦看一下了   谢谢  







在 2023-03-06 19:19:52，"xulinde" ***@***.***> 写道：

没有复现该问题，jira插件版本和ms版本一致吗？项目关联jira，模版选的默认模版还是jira缺陷模版？

**Comment by xiaoroubao999** [comment]
方便加一下微信麽~~

**Comment by xulinde** [comment]
您可以加下我们的交流群
<img width="400" alt="image" src="https://user-images.githubusercontent.com/64065190/223407617-1ab73576-9414-40b7-b8aa-d832006013c0.png">

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
