### ISSUE TITLE
[BUG]接口自动化中复制的API另存为CASE后，在新场景中引用该CASE，保存场景再次进入编辑，显示“原始API不存在”

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22473]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

复现步骤：
1、接口自动化模块新建场景，选择“接口列表导入”复制一个api；
2、复制的api，鼠标指向“...”点击“另存为新用例”保存为接口case；
3、新建场景，选择引用步骤二的case，此时列表中确实显示"CASE""引用"，保存场景关闭。
4、再次进入场景编辑，此时列表中变成了"API""引用"，并且有黄色叹号，显示“原始API不存在”，并且被自动禁用。
![image](https://user-images.githubusercontent.com/83771182/223053936-cd1f12b1-3c24-490f-9211-ce16e3508518.png)

### 重现步骤

1、接口自动化模块新建场景，选择“接口列表导入”复制一个api；
2、复制的api，鼠标指向“...”点击“另存为新用例”保存为接口case；
3、新建场景，选择引用步骤二的case，此时列表中确实显示"CASE""引用"，保存场景关闭。
4、再次进入场景编辑，此时列表中变成了"API""引用"，并且有黄色叹号，显示“原始API不存在”，并且被自动禁用。

**Comment by wxg0103** [comment]
您好  感谢反馈  这个问题将在v2.8修复
祝您生活愉快

**Comment by Ycr123888** [comment]
2.7.1已验证通过
