### ISSUE TITLE
[BUG] 2.7版本MS在编写用例时，会保存失败报错

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#22475]
### 联系方式

15375857626

### MeterSphere 版本

2.7版本

### 使用外置数据库

否

### 问题描述

客户在进行编写测试用例时，会出现在编辑结束，点击保存按钮时，报错500，具体步骤描述如下。

### 重现步骤

1.写一个案例，不提供标签，点击保存
![ebfd33d7a84d465e4700ec8fdb4b455](https://user-images.githubusercontent.com/47737772/223057190-2e89492b-b819-48c8-acc1-f73af5605571.png)
2.断开网络
3.连接网络
4.后续的案例全部都无法保存
![6f3140b1a6999f669112dd5a7ef9ee6](https://user-images.githubusercontent.com/47737772/223057324-d7f598e7-1e31-452b-9595-1010626a6f10.png)
![0afdbe83b3d4ba3363366d8d4254e2b](https://user-images.githubusercontent.com/47737772/223057348-548b2deb-6d9c-400a-8915-2fedfdb6485a.png)

### 期待的正确结果

用例正常保存成功。

### 附加信息

![image](https://user-images.githubusercontent.com/47737772/223057700-3df4ee7f-776d-4720-9724-2db39238e704.png)

**Comment by luty2018** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/36292514/223314159-1b806095-8890-4b96-bdaf-2595d972799c.png">
你好， 我这边按你说的方式操作无法复现呢。有确定联网成功吗？

**Comment by luty2018** [comment]
这边先关闭issue，如果可以复现你可以重新打开。
