### ISSUE TITLE
[BUG]场景内上传csv文件，保存后，再修改本地的csv文件表头，再保存场景，报 Network Error错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#22498]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

场景内上传csv文件，保存后，再修改本地的csv文件表头，再保存场景，报 Network Error错误

### 重现步骤

1.场景内上传csv文件，保存场景
![image](https://user-images.githubusercontent.com/103627487/223367590-67a72185-3d99-42a8-8397-933a50fb3499.png)
2.修改本地csv文件表头，保存本地csv文件
![image](https://user-images.githubusercontent.com/103627487/223367972-b7927a49-8f85-4b9f-84a1-c3719152adb5.png)
3.直接点击保存场景，如果第一次点击未出现，可以点击下调试，在点击保存
![image](https://user-images.githubusercontent.com/103627487/223368388-5f716747-b2b8-4cea-bb7d-c1b8d4f1fd9d.png)
![image](https://user-images.githubusercontent.com/103627487/223368878-0539c914-4c18-4100-ac60-f613a64ebb44.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，计划下个版本中修复。
