### ISSUE TITLE
[BUG]循环控制器里csv变量引用失败

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#2249]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
用户名、密码使用csv变量，利用循环控制器遍历多种组合场景，直接在场景中执行是没有问题的，在测试计划中选择批量执行、和其他场景一起执行的时候，传参只传了一个，其他都为EOF。

**Bug 重现步骤**
1. 创建登录的接口场景
2. 引用第一步场景的接口场景，创建登录成功的接口场景，执行没有问题
2. 引用第一步场景的接口场景，创建登录失败的接口场景（使用了循环控制器，读取csv变量里面的几个值），执行没有问题
3. 创建测试计划，关联2、3步骤创建的登录成功的接口场景和登录失败的接口场景，选择批量执行
![image](https://user-images.githubusercontent.com/35896106/115988384-0fbf6b00-a5ec-11eb-8068-e2dbf45ac46c.png)

**期待的正确结果**
正确情况下应该是什么样的？
直接在场景里执行的结果如下：
![image](https://user-images.githubusercontent.com/35896106/115988935-5d3cd780-a5ee-11eb-8c73-fbcbd5e11bb2.png)

在测试计划里面批量执行的结果如下：
![image](https://user-images.githubusercontent.com/35896106/115988437-501ee900-a5ec-11eb-9f24-baea7adbee11.png)

**Comment by zyyfit** [comment]
您好，能具体描述一下操作步骤吗？比如循环控制器使用的什么循环等？这边没有复现呢
