### ISSUE TITLE
[BUG]更新已存在的全局断言脚本失败，更新内容无法同步到数据库

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22494]
### 联系方式

silverleo@163.com

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

编辑全局断言脚本，弹出窗口上没有保存按钮，脚本更新无法保存到数据库。直接关闭弹出窗口，也无法保存脚本。
![35d6fef2fb0eb598fa719e4139cf98d](https://user-images.githubusercontent.com/2188338/223356665-fb571ca7-d1ca-4ea8-9393-1caaf647e1b6.png)

### 重现步骤

编辑全局断言脚本，弹出窗口上没有保存按钮，脚本更新无法保存到数据库

**Comment by yangstones** [comment]
就是你这个入口。点击编辑脚本的按钮，弹出的编辑窗口没有保存按钮，并且关闭编辑窗口之后，更新的内容没有同步到数据库

**Comment by yangstones** [comment]
我是说编辑已经存在的全局断言脚本，不是新建

**Comment by yangstones** [comment]
编辑已经存在的全局断言脚本，关闭编辑窗口，并点击确定，变更内容没有同步到数据库

**Comment by yangstones** [comment]
页面发送给服务器端的内容就是错的：
在代码中删除第一行的注释，然后关闭编辑窗口，然后点击确定按钮，可以看到发送给服务器的脚本内容是老的版本：

![image](https://user-images.githubusercontent.com/2188338/223400994-2a50bc59-3cf5-478b-9aae-9004608cde17.png)

**Comment by yangstones** [comment]
你对同一个脚本，多次操作更新和保存试一下

**Comment by luty2018** [comment]
你好，我们明天会发布v2.7.1版本， 你可以升级试试， 目前我在v2.7.1版本上使用这块功能都是正常的。

**Comment by yangstones** [comment]
2.6.1和2.7.1版本，初始状态：
环境A中全局断言脚本为版本1， 环境B中全局断言脚本为版本2
编辑环境A中的全局断言脚本为版本1.1，打开环境B，全局断言也显示为1.1，但是数据库中环境B的脚本还是版本2

**Comment by yangstones** [comment]
edge浏览器和chrome浏览器稳定复现

**Comment by luty2018** [comment]
好的， 已经复现了，转开发跟进

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
