### ISSUE TITLE
部署完成后访问不到 [QUESTION]

### ISSUE THREAD

**Issue by linxinjie-s** [metersphere/metersphere#225]
**请描述您的问题.**
部署完成后访问不到，查看服务器状态如图
![image](https://user-images.githubusercontent.com/69612931/90087304-025c9c00-dd4f-11ea-9aab-cdf31a59a2bb.png)

**Comment by linxinjie-s** [comment]
![image](https://user-images.githubusercontent.com/69612931/90087966-88c5ad80-dd50-11ea-9b5f-80cd7226da84.png)
![image](https://user-images.githubusercontent.com/69612931/90087981-8f542500-dd50-11ea-9bc4-6006e92b4596.png)

**Comment by wangzhen-fit2cloud** [comment]
请检查服务器上及其所在网络的防火墙配置，是否放通了 8081 端口

**Comment by linxinjie-s** [comment]
防火墙对应端口是开放了的。我觉得和ms-data-streaming有关
![image](https://user-images.githubusercontent.com/69612931/90231343-9b71dc80-de4d-11ea-8b51-1e69eab03af8.png)

**Comment by wangzhen-fit2cloud** [comment]
通过 netstat 查看只说明有服务监听在 8081 端口，需要通过 firewall-cmd 命令放通下 8081 及其他端口

**Comment by linxinjie-s** [comment]
![image](https://user-images.githubusercontent.com/69612931/90354299-7b276500-e07b-11ea-8ff2-5a9a4b7b5362.png)

**Comment by linxinjie-s** [comment]
其他端口也都是开放的
