### ISSUE TITLE
[BUG]上传平台的 mp4/mp3 文件不能被性能测试资源文件引用

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#22500]
### 联系方式

13735892260

### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

项目-文件管理，上传了 mp4 和 mp3 等文件，在性能测试中，创建测试，引入资源文件 mp4 等，发现无法查到文件

### 重现步骤

2.5 ～ 2.7 都是这样，开源版本，是不是有什么特殊配置要求

### 期待的正确结果

可以正常使用

### 附加信息

<img width="755" alt="image" src="https://user-images.githubusercontent.com/5398144/223381449-d6f84fd5-2784-4d0f-8f11-ad814ef7caba.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/5398144/223381542-6399d928-dec7-4f6a-964e-a52d7d16dbc4.png">

**Comment by luty2018** [comment]
你好， 最初这里为了防止用户上传非法文件所以对文件类型做了限制。
我们会在3.0版本对这里放开文件类型限制。

**Comment by hztony** [comment]
好的，期待你们 3.0 早日发布 😄
