### ISSUE TITLE
[BUG]  项目设置-环境管理，首次添加环境设有http配置，保存成功后，http配置未保存成功

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22502]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

项目设置-环境管理，首次添加环境设有http配置，保存成功后，http配置未保存成功

### 重现步骤

项目设置-环境管理,首次添加环境设有http配置，添加添加后保存，
![image](https://user-images.githubusercontent.com/103925124/223382645-d34bd729-ff00-4169-aab8-4b914db82267.png),
http配置未保存成功
![企业微信截图_16781819989191](https://user-images.githubusercontent.com/103925124/223383626-0c48878a-9405-42f2-bcf2-7891feb41650.png)

备注：非每次必现，属于多次操作必现

**Comment by youliyuan-fit2cloud** [comment]
你好，尝试多次没有复现，请确认截图1中，点击“添加”时，底部是否列出了 http配置内容 ？

**Comment by youliyuan-fit2cloud** [comment]
已复现，应该是“添加”时底部列表没有正常返回输入内容，下个版本修复。

**Comment by Ycr123888** [comment]
收到。最好顺便校验下，用户输入的包含https，http的话，提示用户删掉，格式不对

**Comment by youliyuan-fit2cloud** [comment]
> 收到。最好顺便校验下，用户输入的包含https，http的话，提示用户删掉，格式不对

这个格式问题暂时不改，待v3.0中规划吧。
