### ISSUE TITLE
postman文件导入场景后，无法进行断言，前置条件等操作

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#2251]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
postman文件导入场景后，无法进行断言，前置条件等操作

**Bug 重现步骤**
1.  把postman文件导入场景里面
2. 
3. 
4. 

**期待的正确结果**
能够进行断言等操作

**截图**
.

**Comment by zyyfit** [comment]
感谢反馈，这个问题将在1.9.0版本修复

**Comment by xulinde** [comment]
1.9.0已修复
