### ISSUE TITLE
[BUG]SQL 协议取值是，如果字段为 null，${xx} 取值不成功，vars.get("xx") 可以正常取值

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22512]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.7

### 使用外置数据库

否

### 问题描述

SQL 协议取值是，如果字段为 null，${xx} 取值不成功，vars.get("xx") 可以正常取值

### 重现步骤

1.查询、设置变量
![image](https://user-images.githubusercontent.com/30038088/223399522-a8ad6afc-c29b-4c33-b0b9-55109375598d.png)
2.取值
![image](https://user-images.githubusercontent.com/30038088/223399632-65687d40-3dd5-4e1a-871c-4bd185633246.png)

**Comment by fit2-zhao** [comment]
感谢反馈，目前变量取值机制确实是这样的，我们使用的测试引擎JMeter也是相同处理方式，vars.get 取值是上下文对象中获取，而${}属于匹配检索方式，所以确实有差异 在使用时可以根据自身需求去选择。
