### ISSUE TITLE
[BUG]如果复制一个带场景变量的旧场景到当前场景，旧场景的场景变量无法在当前场景中修改

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#22522]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.6.0

### 使用外置数据库

否

### 问题描述

如标题描述的现象

### 重现步骤

重现过程，可查看我录制的视频操作过程
https://meeting.tencent.com/v2/cloud-record/share?id=78e140b1-9502-4924-ac8b-d1764c773100&from=3

### 期待的正确结果

如果复制一个带场景变量的旧场景到当前场景，希望旧场景的场景变量能一起复制到当前场景

**Comment by fit2-zhao** [comment]
感谢反馈，非常抱歉给你带来了不好的体验，目前这个功能已经支持了的，入口比较隐蔽请参考下图：

<img width="932" alt="image" src="https://user-images.githubusercontent.com/70558837/223893417-dc3cf7cc-ef1e-421d-8848-338a693a490a.png">
