### ISSUE TITLE
[FEATURE]希望能够出一个全局性的组织，用于管理全局性的进度、状态信息跟踪

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2252]
**请描述您的需求或者改进建议.**
当前组织下，如果项目特别多，工作空间特别多，那么管理人员需要不断的切换组织和工作空间，很不方便管理；

**请描述你建议的实现方案**
希望能够出一个全局性的组织，用于管理全局性的进度、状态信息跟踪

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
