### ISSUE TITLE
接口场景列表导入创建场景时，按顺序勾选的用例排序并没有按顺序排列

### ISSUE THREAD

**Issue by huskiesir** [metersphere/metersphere#22520]
### MeterSphere 版本

v2.7.0-34d44a5e

### 联系方式

1832025651@qq.com

### 请描述您的需求或者改进建议

ms在创建场景时选择接口列表导入，依次按顺序勾选后，发现在场景中的接口排列顺序是反的，这个能优化下吗？？？
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/45967454/223462565-11aaff69-9a00-4400-ab17-6580198fd863.png">

### 请描述你建议的实现方案

按顺序勾选的用例，在接口场景中应该延用勾选的顺序，而不是应该让用户再重新编排用例顺序。
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/45967454/223463137-537941e0-d1b2-4d3f-9160-86e4135e7cba.png">

**Comment by luty2018** [comment]
你好， 是按照列表顺序添加并不是按勾选顺序。暂时也没有计划要改成勾选顺序。
