### ISSUE TITLE
[BUG]在MeterSphere前后置脚本中引用Python第三方库（不能实现）

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#22524]
### 联系方式

595520137@qq.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

https://zhuanlan.zhihu.com/p/446668517?utm_id=0
按官方的教程操作，引用第三方库，但是调试时控制台报错，找不到

### 重现步骤

可以支持第三方吗？

**Comment by fit2-zhao** [comment]
感谢反馈，目前可以支持三方库，三方库使用的方式较多，您可以把具体的问题发到我们交流群里，和大家一起探讨。

**Comment by conansharp** [comment]
![image](https://user-images.githubusercontent.com/111938588/223952494-68a456eb-656e-4f4e-8bc3-ec4c85edd4a6.png)
就按官方里的例子操作了下，我这边调试的时候，提示找不到xpinyin

**Comment by fit2-zhao** [comment]
感谢反馈，三方库确实比较多，需要考虑版本兼容性等，您提到的redis 我们后续也尝试一下看看能否出一个比较好的方案。
