### ISSUE TITLE
[BUG]手动修改[.env]文件里的kafka端口号，重新reload服务，所有服务状态都正常，但是其他服务或MS服务器上telnet kafka都无法连接。发现kafka的yml文件里有些端口号是写死的

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22526]
### MeterSphere 版本

V2.7

### 使用外置数据库

否

### 问题描述

1、手动修改[.env]文件里的kafka端口号，9092改为9094
2、重新reload服务，所有服务状态都正常，
3、问题：
     1) 接口测试发生404错误；
     2）性能测试提示连接异常
     3）其他服务docker里 或 MS服务器上telnet kafka都无法连接。

4、检查kafka的yml文件里有些端口号9092是写死的，
5、修改yml文件里的9092为9094，重启服务，才可以。

### 重现步骤

1、手动修改[.env]文件里的kafka端口号，9092改为9094
2、重新reload服务，所有服务状态都正常，
3、问题：
     1) 接口测试发生404错误；
     2）性能测试提示连接异常
     3）其他服务docker里 或 MS服务器上telnet kafka都无法连接。

4、检查kafka的yml文件里有些端口号9092是写死的，
5、修改yml文件里的9092为9094，重启服务，才可以。

### 期待的正确结果

yml文件里这个端口号不应该是写死的

### 附加信息

![env文件修改](https://user-images.githubusercontent.com/78218624/223649245-360c4687-3eaa-4b06-a739-598c0b5c8049.png)

![kafka服务端口号](https://user-images.githubusercontent.com/78218624/223649274-405b3c18-907e-4f01-b60f-9cf13b57230f.png)

![性能测试错误提示](https://user-images.githubusercontent.com/78218624/223649736-4860f625-c4bf-47f1-805d-277e0a037204.png)

![网络不通](https://user-images.githubusercontent.com/78218624/223649321-4d84c80b-36ff-424d-b96e-dabb232e3fd5.png)
![修改yml文件](https://user-images.githubusercontent.com/78218624/223650307-59918961-30e5-4219-afae-b951b23083aa.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本v2.8.0中会优化。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
