### ISSUE TITLE
测试计划手动选择"资源池"执行，导致该测试计划定时任务实际执行时使用的"资源池"发现变化

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#22539]
### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

有两个资源池：A和B，测试计划设置定时任务，采用"串行/并行+资源池（A）"的模式执行，手动采用"串行/并行+资源池（B）"的模式执行一次测试计划，后续测试计划定时任务执行时实际使用的资源池都是B
测试计划定时任务截图（采用LOCAL资源池）：
<img width="860" alt="截屏2023-03-08 下午5 50 54" src="https://user-images.githubusercontent.com/34637801/223680230-c8e2587e-155c-4068-b486-e13e53651492.png">
测试计划手动执行截图（采用"测试资源池"）：
<img width="525" alt="截屏2023-03-08 下午5 51 46" src="https://user-images.githubusercontent.com/34637801/223680432-1f5b4074-a78c-4fa4-abe8-057d26b1982c.png">
LOCAL资源池的运行日志：
<img width="1401" alt="截屏2023-03-08 下午5 52 28" src="https://user-images.githubusercontent.com/34637801/223680591-d03944a2-6a92-4975-965c-fc498f0b61b7.png">
测试资源池的运行日志：
<img width="1402" alt="截屏2023-03-08 下午5 52 50" src="https://user-images.githubusercontent.com/34637801/223680688-caeefcdb-f308-4bda-aff3-9de5445dc31d.png">
   从日志时间可判断，定时任务所有的执行均在"测试资源池"中进行，而非设置的"LOCAL资源池"中进行。

### 重现步骤

1.准备两个资源池：A和B
2.测试计划设置定时任务，采用"串行/并行+资源池（A）"的模式执行。
3.手动采用"串行/并行+资源池（B）"的模式执行一次测试计划。
4.查看两个节点的/opt/metersphere/logs/node-controller/ms-jmeter-run-log.log日志

### 期待的正确结果

手动执行选择的资源池，不会影响定时任务设置的资源池。

**Comment by luty2018** [comment]
非问题， 设计如此， 测试计划环境的优先级最高。
