### ISSUE TITLE
meter平台导入接口目前必须要选择相关的模块，无法选择根目录

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#2253]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
meter平台导入接口目前必须要选择相关的模块，无法选择根目录

**Bug 重现步骤**
1. meter平台上有分模块的接口
2.  从yapi导出的接口是一个项目下所有的接口
3. 导入meter平台，必须要选择一个模块，而不能直接全部覆盖
3. 
4. 

**期待的正确结果**
能够选择根目录，覆盖所有的接口

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/60743086/115989430-e6eda480-a5f0-11eb-9e1d-a324f7210bcc.png)

**Comment by zyyfit** [comment]
您好，目前是这样设计的

**Comment by zyyfit** [comment]
还有，建议您升到最新版，最新版可以不选择模块，不选择模块就默认导入到根目录下
