### ISSUE TITLE
[BUG]将第三方包上传，在前置脚本引用该包，多运行几次，有时可以正常引用，有时出现找不到的情况。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22549]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

将第三方包上传，在前置脚本引用该包，多运行几次，有时可以正常引用，有时出现找不到的情况。

### 重现步骤

1.将该包上传到v2.7.0版本，在前置脚本引用该包，多运行几次，有时可以正常引用，有时出现找不到的情况。
![image](https://user-images.githubusercontent.com/104960608/223909272-5d88a482-0030-4878-a46b-5571eb360822.png)

![image](https://user-images.githubusercontent.com/104960608/223910003-ff89ee4e-fb47-4097-9668-9e0bdfdf9d26.png)

![image](https://user-images.githubusercontent.com/104960608/223910064-5308804b-9134-4702-aa50-851b81894208.png)

2. jar包如下
[Downloads.zip](https://github.com/metersphere/metersphere/files/10927418/Downloads.zip)

**Comment by fit2-zhao** [comment]
感谢反馈，根据您提供的jar包并未复现您说的这种情况，通过批量执行多次或者循环多次均无法重现，能否提供您失败后的日志信息，我们再做进一步分析。

![image](https://user-images.githubusercontent.com/70558837/223930870-5dfad954-d04c-447b-bd2d-6d2cf202d88c.png)

**Comment by Forilan** [comment]
这个问题我也遇到了，测试计划关联了10个场景，每个场景又引用了其他场景，执行测试计划， 大概10次能遇到1次。
![image](https://user-images.githubusercontent.com/6127516/224008177-f2da2ab3-b13d-4230-830c-b87c1781eaaa.png)

**Comment by maninhill** [comment]
这类问题需要重点跟进。

**Comment by Forilan** [comment]
为什么关闭呢，解决了吗？
