### ISSUE TITLE
[FEATURE]测试计划关联功能用例后，脑图下增加评论或者备注功能。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22547]
### MeterSphere 版本

v2.7.0

### 请描述您的需求或者改进建议

1.期望测试计划管理功能用例，执行时，可以在脑图下增加评论或者备注功能。
![image](https://user-images.githubusercontent.com/55130444/223904220-d77ab9e4-185f-4602-be08-98b56419e3b2.png)
我理解可以在这里加一个标签，（备注/评论），然后输入内容。

**Comment by luty2018** [comment]
这个已经规划了， 脑图功能最终会和列表功能对齐。
