### ISSUE TITLE
上传附件系统一直报错相关的内容为空（postman可以成功，但是meter不行）

### ISSUE THREAD

**Issue by flygirls88** [metersphere/metersphere#2254]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
上传附件系统一直报错相关的内容为空
**Bug 重现步骤**
1.  上传附件
2. 相关请求体都已经填写
3. 
4. 

**期待的正确结果**
上传成功

**截图**
![image](https://user-images.githubusercontent.com/60743086/115989613-cb36ce00-a5f1-11eb-8d18-901d6c6dd697.png)
![image](https://user-images.githubusercontent.com/60743086/115989638-e73a6f80-a5f1-11eb-92ca-bd7905dd23f5.png)

**Comment by zyyfit** [comment]
您好，要上传文件的话不需要填写Content-Type请求头的，您可以去掉这个请求头再试一下
