### ISSUE TITLE
[BUG] db2数据库找不到驱动类

### ISSUE THREAD

**Issue by Forilan** [metersphere/metersphere#22550]
### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

驱动jar包是上传了， 也开启了"加载jar包"
脚本中使用java代码写了个简单的demo， jdbc连接db2， 提示找不到驱动类

### 重现步骤

![微信截图_20230308183714](https://user-images.githubusercontent.com/6127516/223910441-a456fe97-ca69-406f-afee-f8da62b582ef.png)
![微信截图_20230309102422](https://user-images.githubusercontent.com/6127516/223910458-b918ea4b-9bb7-4579-bda7-a17540a8bc64.png)

**Comment by Forilan** [comment]
在jmeter上测试是没问题的
![微信截图_20230309161343](https://user-images.githubusercontent.com/6127516/223960985-709cbc88-88ad-4e5f-9c16-12efd8cb52dd.png)

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/4761
你好， 我们目前还不支持DB2，计划在v3.0版本支持
