### ISSUE TITLE
[BUG]【UI测试-本地调试】在本地调试时，点击“停止”按钮，发现浏览器并没有关闭，而是还在执行该场景的内容，直到该场景执行完

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22557]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

【UI测试-本地调试】在本地调试时，点击“停止”按钮，发现浏览器并没有关闭，而是还在执行该场景的内容，直到该场景执行完

### 重现步骤

1. 【UI测试-本地调试】在本地调试时，点击“停止”按钮，发现浏览器并没有关闭，而是还在执行该场景的内容，直到该场景执行完
![image](https://user-images.githubusercontent.com/104960608/223947181-7c9d0578-9e4a-4b13-9a86-265220620367.png)

![image](https://user-images.githubusercontent.com/104960608/223947861-55816d1e-7be3-42c4-a872-c79d296b5067.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.8修复。
