### ISSUE TITLE
[BUG]【UI测试】引用场景后，将步骤拖拽进引用的场景，右侧的 ... 功能没有了，而且也不能再拖拽出来。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22552]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1. 当前场景有2个步骤，再 导入其他场景 进行引用
![image](https://user-images.githubusercontent.com/104960608/223931297-f0949a7b-e649-4a2e-8033-5c57624e0dba.png)

2. 将与 引用场景 同级的步骤 拖拽进 引用场景里，可看到还是有 .... 这个功能的
![image](https://user-images.githubusercontent.com/104960608/223931543-c3453f50-3e99-4ee2-9af1-009cf4f8fab0.png)

3. 点击 引用场景 后，再次查看拖拽进去的步骤，发现已经没有 ....的功能了。而且该步骤也不能拖拽出来了
![image](https://user-images.githubusercontent.com/104960608/223932540-a767a4a6-6e40-48f5-a8ef-619ae3e47777.png)

### 重现步骤

1. 当前场景有2个步骤，再 导入其他场景 进行引用
![image](https://user-images.githubusercontent.com/104960608/223931297-f0949a7b-e649-4a2e-8033-5c57624e0dba.png)

2. 将与 引用场景 同级的步骤 拖拽进 引用场景里，可看到还是有 .... 这个功能的
![image](https://user-images.githubusercontent.com/104960608/223931543-c3453f50-3e99-4ee2-9af1-009cf4f8fab0.png)

3. 点击 引用场景 后，再次查看拖拽进去的步骤，发现已经没有 ....的功能了。而且该步骤也不能拖拽出来了
![image](https://user-images.githubusercontent.com/104960608/223932528-1aa42d3a-8432-4b10-99e0-33d8b98eea5f.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，场景步骤是不能拖动到引用的场景下的，同理，引用的场景下的子步骤也是不能拖拽出来的，计划v2.8修复场景步骤可拖拽到引用场景下的问题。
