### ISSUE TITLE
[BUG]先构建的jenkins计划，后在接口自动化列表批量添加场景用例到测试计划，再次通过jenkins调用，测试报告不展示接口场景测试结果

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22555]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

先构建的jenkins计划，后在接口自动化列表批量添加场景用例到测试计划，再次通过jenkins调用，测试报告不展示接口场景测试结果

### 重现步骤

1、jenkins构建测试计划执行任务：test
2、接口自动化列表，添加3个场景用例 到测试计划test中
3、重新在jenkins 上点击构建，跑完之后，测试报告不展示 添加3个场景用例
![先构建的jenkins计划，后在接口自动化列表批量添加场景用例](https://user-images.githubusercontent.com/43202800/223946114-d5a72209-c1f8-4e0f-89e6-600504a24ba0.png)

### 期待的正确结果

添加了新的测试用例，测试计划数据应该同步更新

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题在最新版本v2.7.1未复现，建议升级尝试。

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题在最新版本v2.7.1未复现，建议升级尝试。

**Comment by xhy12** [comment]
新造了数据不复现，就是某一条数据存在问题
