### ISSUE TITLE
[BUG]【UI测试】当前场景-引用场景后，选择“原场景变量”后，进行保存后，再次进入这个场景后，选择“优先使用当前场景变量”，点击保存，再次进入这个场景后，发现还是显示"原场景变量"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22556]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

【UI测试】当前场景-引用场景后，选择“原场景变量”后，进行保存后，再次进入这个场景后，选择“优先使用当前场景变量”，点击保存，再次进入这个场景后，发现还是显示"原场景变量"

### 重现步骤

1. 【UI测试】当前场景-引用场景后，选择“原场景变量”后，进行保存
![image](https://user-images.githubusercontent.com/104960608/223946051-eb61e005-1fb3-40d4-a272-2bc27a18eeec.png)

2. 再次进入这个场景后，选择“优先使用当前场景变量”，点击保存
![image](https://user-images.githubusercontent.com/104960608/223945544-70b347f1-50c6-461d-8f95-7ee6646a240a.png)

3.再次进入这个场景后，发现还是显示"原场景变量"
![image](https://user-images.githubusercontent.com/104960608/223945879-9b6431cd-f47c-429f-83e8-e20607e68914.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.8修复。
