### ISSUE TITLE
[FEATURE]测试跟踪，功能用例，脑图模式，没有加标签保存的时候能否增加一个提示。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#22571]
### MeterSphere 版本

v2.7.0 v2.6.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/55130444/224038201-60a318dc-3d08-4d5a-bdf2-ecf7d455387c.png)
提示保存成功，因为没有加标签，导致实际没有保存成功。切换回列表再切换回来会导致新增的内容消失。

### 请描述你建议的实现方案
增加一个友好提示，类似”新增内容未增加标签，请确认是否保存“这种的。
_No response_

**Comment by luty2018** [comment]
脑图这里除了能写用例以外，也是支持用户记录一些不需要保存用例的内容，比如测试大纲等等，所以我们是无法判断用户哪些需要加标签的。

**Comment by kaijie-yu** [comment]
可是我在用例这个级别，如果没有添加标签，保存提示成功，从列表在切换回来，内容就没了

**Comment by kaijie-yu** [comment]
bug #22599
