### ISSUE TITLE
[BUG]接口自动化前置处理引入js文件可以执行，创建性能测试却不能执行

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22579]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

接口自动化前置处理引入js文件可以执行，创建性能测试却不能执行

### 重现步骤

 1.执行接口自动化，是正常的
2.将接口自动化创建性能测试，执行就报错了
如图是脚本，视频是操作步骤
![接口](https://user-images.githubusercontent.com/39357523/224244224-9f64616e-5c34-4891-84b8-d41075bb5598.png)
[重现.zip](https://github.com/metersphere/metersphere/files/10939383/default.zip)

### 期待的正确结果

前置处理里面引入js在性能测试中可以正常执行

**Comment by liuruibin** [comment]
您好，接口测试脚本引入的这个文件路径会在转成性能测试的时候保持原样，如果需要转成性能测试正常执行，需要性能测试编辑时上传这个js，并且修改脚本中的引用路径，改成/test/文件名。在性能测试执行的时候所有的文件都会在jmeter容器的/test/目录中

**Comment by myliuq** [comment]
![image](https://user-images.githubusercontent.com/39357523/224652034-8a951c9f-fe42-4a7b-b395-a63c668a2be7.png)
![image](https://user-images.githubusercontent.com/39357523/224652059-4d05363b-6f07-4655-b6a6-b2148e3eeecb.png)
放到/test下面也不行呐

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把接口自动化场景转性能测试 的jmx文件和js文件发出来吗？需要确认这个jmx文件中对应的js目录信息，然后做对应修改。

**Comment by myliuq** [comment]
好的，附件为jmx脚本和js文件
[test.zip](https://github.com/metersphere/metersphere/files/10977327/test.zip)

**Comment by youliyuan-fit2cloud** [comment]
> test.zip

这个zip文件不行，下载下来不是zip格式，你是不是在企业微信沟通群里面？哪个群？企业微信沟通？

**Comment by myliuq** [comment]
我没在企业微信群，可以发我下企业微信群二维码，我加一下

**Comment by myliuq** [comment]
吧test.zip  改成test.rar就可以解压了

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试使用这个文件正常执行了。
检查下这个js文件上传到这里了吗？
![image](https://user-images.githubusercontent.com/54612864/225814610-692d05aa-f1e4-4cea-91e4-67a0695a8999.png)

**Comment by myliuq** [comment]
原来这里还要上传，soga，我也执行成功了，感谢老师

**Comment by youliyuan-fit2cloud** [comment]
我们的用户手册需要优化一下～

**Comment by myliuq** [comment]
给小哥哥小姐姐赞赞赞！
