### ISSUE TITLE
[BUG]测试跟踪，首页统计功能用例数量错误，新增用例之后，统计数据不更新

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22587]
### 联系方式

silverleo@163.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

测试跟踪，首页统计功能用例数量错误，新增用例之后，统计数据不更新
![image](https://user-images.githubusercontent.com/2188338/224270760-503e0ef3-85e6-4b2d-bfce-a9886e4db256.png)

![image](https://user-images.githubusercontent.com/2188338/224270837-5526042b-c116-4d4f-a6ec-4604ea01daca.png)

### 重现步骤

拉拉拉

**Comment by youliyuan-fit2cloud** [comment]
你好，我怎么都没复现呐，你这个新建用例是如何操作的？刷下页面也不更新么？请描述下操作步骤，方便我们快速排查问题，感谢您的理解和支持～

**Comment by yangstones** [comment]
> 你好，我怎么都没复现呐，你这个新建用例是如何操作的？刷下页面也不更新么？请描述下操作步骤，方便我们快速排查问题，感谢您的理解和支持～

建议试用我的环境排查一下。我这里有多个项目，其他项目的用例数量很少，也没有复现这个问题。只有这个项目的用例数量最多，能否稳定复现。方便的话可以私信一下您的微信或者qq，我们远程一起看一下。silverleo@163.com

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，我怎么都没复现呐，你这个新建用例是如何操作的？刷下页面也不更新么？请描述下操作步骤，方便我们快速排查问题，感谢您的理解和支持～
> 
> 建议试用我的环境排查一下。我这里有多个项目，其他项目的用例数量很少，也没有复现这个问题。只有这个项目的用例数量最多，能否稳定复现。方便的话可以私信一下您的微信或者qq，我们远程一起看一下。[silverleo@163.com](mailto:silverleo@163.com)
请问你在企业微信沟通群里面吗？加下企业微信 ？请注明MS用户
![image](https://user-images.githubusercontent.com/54612864/224880703-37314143-581b-429a-986e-20d6c32446b9.png)

**Comment by luty2018** [comment]
已复现并转TAPD由开发跟进

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
