### ISSUE TITLE
接口定义-测试的窗口建议可以改变窗口比例

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#2259]
**请描述您的需求或者改进建议.**
问下这边可以调为可以上下拉动吗？  这样我截图就可以把报文和对应的返回结果截再在一张图里
![image](https://user-images.githubusercontent.com/35896106/115992457-6afb5880-a600-11eb-8e1f-61770ca3fc5e.png)

这样消息体数据比较少的时候，我可以改变窗口比例，将消息体和接口返回消息显示在一个页面
**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后续可以优化下这里
