### ISSUE TITLE
[BUG]快捷调试，输入带 query 参数的url，识别后，参数无法编辑，需禁用后才能编辑

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22606]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

快捷调试，输入带 query 参数的url，识别后，参数无法编辑，需禁用后才能编辑

### 重现步骤

1.创建接口快捷调试
2.http://www.baidu.com?c=3&b=2&a=1
3.参数无法编辑
![image](https://user-images.githubusercontent.com/30038088/224459657-f5a53bb9-8404-46ad-9e8b-1d3c33a08ace.png)
禁用后才可以编辑
![image](https://user-images.githubusercontent.com/30038088/224459668-6729a631-b035-4e59-89f7-5e0b2431e466.png)

**Comment by liuruibin** [comment]
感谢提醒，这是一个bug。我们会在2.8.0中修复
