### ISSUE TITLE
[FEATRUE]【性能测试】当前场景下无法查看本场景下的脚本

### ISSUE THREAD

**Issue by zhyong666** [metersphere/metersphere#22608]
### 联系方式

202206期-张勇

### MeterSphere 版本

v2.6.1

### 使用外置数据库

否

### 问题描述

在当前场景下，【已存在的文件】未显示当前场景的已上传脚本文件，仅显示其他场景下的脚本。当有重新上传脚本的需求时，在本场景中无法完成，需要切到其他场景下，才可以完成，导致该功能易用性差。
![1](https://user-images.githubusercontent.com/96411776/224598248-f45b85d9-a9d6-4e47-9fa6-03aa523f93bc.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/96411776/224598412-c04c4ddd-98d6-4b8a-b5ca-5ce2dab12a4b.png)

### 期待的正确结果

在本场景中【已存在的文件】可以查看本场景已经上传的脚本，方便【重新上传】操作

**Comment by luty2018** [comment]
你好， 目前性能测试确实还不支持在线查看和编辑脚本， 你可以在接口自动化那边编辑好再转性能测试。

**Comment by zhyong666** [comment]
> 你好， 目前性能测试确实还不支持在线查看和编辑脚本， 你可以在接口自动化那边编辑好再转性能测试。

你好！问题可能没有描述清楚哦，场景2下【加载JMX文件】-【已存在的文件】看不到场景2下的已经上传的脚本文件，只能在其他场景中才可以看到，如果我发现脚本存在问题，想要执行【重新上传】的操作，则需要在其他场景中执行，比如，在场景1中去查看该JMX文件，点击【重新上传】。在之前的版本，该功能是可以在当前场景中完成对应脚本重新上传的操作的。

**Comment by zhyong666** [comment]
【性能测试】场景A下【已存在的文件】未展示场景A下的JMX文件-无法执行重新上传操作
