### ISSUE TITLE
[BUG]【UI测试】B场景引用A场景，当A场景步骤名称发生变化后，B场景仍然显示A场景之前的名称。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22613]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

【UI测试】B场景引用A场景，当A场景步骤名称发生变化后，B场景仍然显示A场景之前的名称。

### 重现步骤

1. 【UI测试】在B场景引用A场景
![image](https://user-images.githubusercontent.com/104960608/224618834-5b4f775f-a770-49d2-b96d-4d7588ea9000.png)

2.修改A场景的步骤名称，进行保存
![image](https://user-images.githubusercontent.com/104960608/224619050-35ff0805-04bc-4c39-a1f7-491aa8febb67.png)

3. 在B场景中仍然显示修改之前的名称
![image](https://user-images.githubusercontent.com/104960608/224619120-00910a28-ab2a-480f-862f-8d2f78954a3c.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，点击刷新按钮，引用场景的名称应该同步更新显示，计划v2.8修复。
