### ISSUE TITLE
[BUG] 引用第三方JS  V1.20.19版本测试OK的脚本，升级到V2.6.1办吧 脚本运行不成功

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#22614]
### 联系方式

群14-亲山留水

### MeterSphere 版本

V2.6.1

### 使用外置数据库

是

### 问题描述

[BUG] 引用第三方JS  V1.20.19版本测试OK的脚本，升级到V2.6.1办吧 脚本运行不成功,涉及到的JS的API 或自定义脚本运行 一直在转圈

### 重现步骤

g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;
load("/opt/metersphere/data/body/crypto-js.min.js");
var var1=CryptoJS.MD5("metersphere");
var var2=CryptoJS.SHA512("metersphere");
var var3=CryptoJS.SHA256("metersphere");
log.info("===111=== "+var1);
log.info("===111=== "+var2);
log.info("===111=== "+var3);

**Comment by liuruibin** [comment]
我自己在服务器中上传了这个文件，没有问题，您看是不是服务器上这个文件不在了
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/23045261/224648114-bb6876bd-67cd-474b-803c-aa69dcf4f992.png">

**Comment by zhangzhaox** [comment]
对应目录有这个文件，自定义脚本和API用例的地方 都在转圈在   你的V2.6.1版本？
会不会是别的原因 我看那个微服务的日志？

**Comment by zhangzhaox** [comment]
对应目录有这个文件，自定义脚本和API用例的地方 都在转圈在   你的V2.6.1版本？
会不会是别的原因 我看那个微服务的日志？

**Comment by fit2-zhao** [comment]
执行时观察一下这个  /opt/metersphere/logs/api-test/ms-jmeter-run.log 日志信息。

**Comment by zhangzhaox** [comment]
https://github.com/metersphere/metersphere/issues/21604 已找到解决方案 v2.6.1版本确实有问题 2.7版本已修复
