### ISSUE TITLE
[BUG]性能测试关联的文件被删除后，删除性能测试失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#22616]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

性能测试关联的文件被删除后，删除性能测试失败

### 重现步骤

1、创建性能测试，关联文件
2、在文件管理删除被关联的文件
3、再点击性能测试列表，再删除该性能测试

### 期待的正确结果

正常删除

### 附加信息

<img width="960" alt="wecom-temp-feac9831211431c51e6406a576e42e6c" src="https://user-images.githubusercontent.com/32027713/224636548-bafb52e0-ccf2-45c4-8535-517d95fa9934.png">

**Comment by liuruibin** [comment]
您好，现在确实有这个问题，您可以先关联一个jmx再进行删除。我们后续修复这个问题
