### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by adenzhong** [metersphere/metersphere#22631]
### MeterSphere 版本

 v2.7.0-34d44a5e

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/113604623/224659147-650bb0ce-5a72-4d0a-87f0-c299fdba6907.png)
如图所示，功能用例左边文件夹名称太长时显示不完整，希望可以在右侧顶部，把全部用例改成文件夹名称

**Comment by luty2018** [comment]
你可以升级到v2.7.1 左侧要拉宽来展示。
