### ISSUE TITLE
[BUG]  接口场景里面引入另一个场景，被引入的场景中脚本中右边的脚本编辑选择消失了。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#22641]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

1. 创建场景A，添加自定义脚本
2. 创建场景B，引入场景A，打开引入的场景A 就能复现。

场景B：
![image](https://user-images.githubusercontent.com/33945037/224669863-eacb72c6-1f92-49aa-bb1b-b53139dd8d5f.png)

场景A：
![image](https://user-images.githubusercontent.com/33945037/224669873-7151b8e0-6e7d-4bbc-af03-7ed04d3893aa.png)

之前版本是有的
![image](https://user-images.githubusercontent.com/33945037/224670310-49548c2d-a515-4e20-87da-dbd72ab3e622.png)

### 重现步骤

同上

**Comment by fit2-zhao** [comment]
感谢反馈，这个目前就是这样设计的，引用场景步骤是不允许操作，这个之前版本是缺陷，后续版本做了修复。
