### ISSUE TITLE
[QUESTION]node-exporter 监听node-controller端口如何修改 

### ISSUE THREAD

**Issue by shanfeiyang** [metersphere/metersphere#22640]
### 请描述您的问题

node-controller默认9100端口被占用，我修改了这个端口，但是node-exporter监听node-controller的端口没有改掉，看日志仍然在监听9100，这该如何改

**Comment by shenkaibo** [comment]
你好，需要同步在修改资源池的端口配置， 【系统设置】-【测试资源池】，点击【编辑】修改端口信息。
![image](https://user-images.githubusercontent.com/30038088/224675580-64918b59-ae2c-4c9c-8315-1b1bfb37184c.png)

**Comment by shanfeiyang** [comment]
> 你好，需要同步在修改资源池的端口配置， 【系统设置】-【测试资源池】，点击【编辑】修改端口信息。 ![image](https://user-images.githubusercontent.com/30038088/224675580-64918b59-ae2c-4c9c-8315-1b1bfb37184c.png)

我是低版本1.7离线升级到1.20.19，现在页面还是1.7的页面，没有monitor端口的设置

**Comment by shenkaibo** [comment]
升级到 v1.20.19 肯定是有这个页面的，您清除下浏览器缓存试试。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Dwyane ***@***.***&gt;;
发送时间：2023年3月14日(星期二) 上午9:13
收件人："metersphere/metersphere" ***@***.***&gt;;
抄送："申凯波 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [metersphere/metersphere] [QUESTION]node-exporter 监听node-controller端口如何修改  (Issue #22640)
-----------------------------------

 

  
你好，需要同步在修改资源池的端口配置， 【系统设置】-【测试资源池】，点击【编辑】修改端口信息。 
  
我是低版本1.7离线升级到1.20.19，现在页面还是1.7的页面，没有monitor端口的设置
