### ISSUE TITLE
[BUG]测试跟踪的用例评审功能，脑图模式中，将用例评审状态改为通过，保存并刷新后，用例评审状态又恢复为未开始了

### ISSUE THREAD

**Issue by awqinqing** [metersphere/metersphere#22658]
### 联系方式

awqinqing@foxmail.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

是

### 问题描述

测试跟踪的用例评审功能，脑图模式中，将用例评审状态改为通过，保存并刷新后，用例评审状态又恢复为未开始了

### 重现步骤

测试跟踪-用例评审-脑图模式
标记某个用例为通过，然后保存，然后刷新，用例状态又变为未开始

### 期待的正确结果

通过

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已知问题，我们下个版本修复，请关注发布信息。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
