### ISSUE TITLE
[BUG] 测试跟踪>>功能测试用例>>导入测试用例：当文件步骤描述过长时，系统崩溃。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22650]
### MeterSphere 版本

V2.7

### 使用外置数据库

否

### 问题描述

[BUG] 测试跟踪>>功能测试用例>>导入测试用例：当文件步骤描述过长时，系统崩溃

### 重现步骤

[BUG] 测试跟踪>>功能测试用例>>导入测试用例：当文件步骤描述过长时，系统崩溃

### 期待的正确结果

如果操作太长了截取或提示，但是别报异常吧

### 附加信息

![导入太长异常](https://user-images.githubusercontent.com/78218624/224678267-95a9a61f-99ea-4da0-b8f8-aa06ef9aa0d3.png)
[Metersphere_case_飞致云演示 (8).xlsx](https://github.com/metersphere/metersphere/files/10956346/Metersphere_case_.8.xlsx)

**Comment by zrfit** [comment]
您好，感谢您的反馈！用您的附件在最新版本v2.7.1上传成功未复现该问题，研发已经和您联系，看到回复下私聊信息，具体排查下。
