### ISSUE TITLE
[BUG]缺陷通知没有缺陷详情链接和修改内容

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22657]
### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

缺陷通知没有缺陷详情链接和修改内容

### 重现步骤

缺陷通知没有缺陷详情链接和修改内容

### 期待的正确结果

缺陷通知里包含缺陷详情链接和修改内容，比如评论内容，状态修改内容等

**Comment by luty2018** [comment]
你好， 目前企业版的通知模板可以通过配置这些字段来实现这个需求，您可以申请企业版试用。
