### ISSUE TITLE
[BUG]sso redirect回调后https变为http

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22653]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.20-lts

### 使用外置数据库

否

### 问题描述

sso oauth2.0 地址都配置的 https ，redirect回调后https变为http

### 重现步骤

sso oauth2.0 地址都配置的 https ，redirect回调后https变为http

### 期待的正确结果

修改方式,参考这个博客
https://www.shuzhiduo.com/A/GBJr6BoZJ0/
![699f06c48efa012e78d4b59512cdb14b_](https://user-images.githubusercontent.com/30038088/224685294-9ea1ea80-5415-4e59-a203-cfd132098169.png)
已验证通过。

**Comment by liuruibin** [comment]
您好，在1.20.x中并没有对接过OAuth2.0，请您升级到2.x最新版测试，这里先关闭这个issue。如果还有问题，请打开这个issue

**Comment by shenkaibo** [comment]
CAS、OIDC 应该也有类似的问题

**Comment by shenkaibo** [comment]
升级到 v2.10 也有这个问题
