### ISSUE TITLE
[v1.8.2] 最新版本点击推荐JSONPATH无反应

### ISSUE THREAD

**Issue by t880216t** [metersphere/metersphere#2266]
**问题/需求描述**
前端代码的replaceAll函数，存在浏览器兼容问题，点击推荐Json路径没有反应。
问题代码段：
https://github.com/metersphere/metersphere/blob/b4d8c693ba449f8fd51bac3c888bba0c993bbf10/frontend/src/business/components/api/definition/components/assertion/ApiAssertions.vue#L159
`let expect = jsonItem.expect.replaceAll('\\', "\\\\").replaceAll('(', "\\(").replaceAll(')', "\\)")
          .replaceAll('+', "\\+").replaceAll('.', "\\.").replaceAll('[', "\\[").replaceAll(']', "\\]")
          .replaceAll('?', "\\?").replaceAll('/', "\\/").replaceAll('*', "\\*")
          .replaceAll('^', "\\^").replaceAll('{', "\\{").replaceAll('}', "\\}").replaceAll('$', "\\$");`

**解决方式**：
使用兼容性更好的正则表达式匹配：
`let expect = jsonItem.expect.replace(/\\\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
            .replace(/\+/g, "\\+").replace(/\./g, "\\.").replace(/\[/g, "\\[").replace(/\]/g, "\\]")
            .replace(/\?/g, "\\?").replace(/\//g, "\\/").replace(/\*/g, "\\*")
            .replace(/\^/g, "\\^").replace(/\{/g, "\\{").replace(/\}/g, "\\}").replace(/\$/g, "\\$");`

**Comment by zyyfit** [comment]
您好，请问您使用的是什么浏览器，chrome和火狐试了都可以正常使用的

**Comment by t880216t** [comment]
我的是mac  chrome 89出现的，这个问题可参考下别人的文章：[JavaScript String.prototype.replaceAll 兼容性导致的问题](https://blog.csdn.net/wuyujin1997/article/details/112912567)

**Comment by xulinde** [comment]
1.9.2最新版本还有此问题吗

**Comment by t880216t** [comment]
1.9.2没有做代码修改，理论上这个js语法兼容问题还是存在的。
