### ISSUE TITLE
[v1.8.2]通过Swagger导入的接口路径会以“//”开头

### ISSUE THREAD

**Issue by t880216t** [metersphere/metersphere#2267]
**问题/需求描述**
通过swagger导入的接口，路径会以“//”开头。
问题代码段：
https://github.com/metersphere/metersphere/blob/8539b5d011cc0485cfc41a3020123adecdf55447/backend/src/main/java/io/metersphere/api/dto/definition/parse/Swagger2Parser.java#L80

**解决方法**：
`String pathStr = (basePath + apiDefinition.getPath().replaceAll("//","/")).replaceAll("//","/");`

**Comment by zyyfit** [comment]
您好，请问您使用的是哪个版本？我这边接口导入和文件导入都没有复现

**Comment by t880216t** [comment]
> 您好，请问您使用的是哪个版本？我这边接口导入和文件导入都没有复现

我master分支的，看了下和v1.8.2代码是一样的。

**Comment by xulinde** [comment]
1.9.2已修复
