### ISSUE TITLE
[BUG] V2.7.0版本：导入api后会自动生成一条case，在该case请求体中上传本地文件，执行case时提示找不到文件

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#22689]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

V2.7.0版本：导入api后会自动生成一条case，在该case请求体中上传本地文件，执行case时提示找不到文件

原因定位：只有自动生成的case会出现该问题，如果是手动创建的case并且在case请求体中上传文件，执行case时不会出现找不到文件的问题

### 重现步骤

1、接口定义》导入api
2、因为导入api后会自动生成一条case，编辑该case，请求体中，参数类型为file，上传一个本地文件
3、保存case并执行

### 附加信息

![image](https://user-images.githubusercontent.com/86464217/224944084-8588258c-c351-4e74-8222-89eab3908bb3.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，计划下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
介于长时间未反馈，故关闭该问题。
