### ISSUE TITLE
[BUG]场景保存提示【文件个数超出限制】-无法保存场景

### ISSUE THREAD

**Issue by zhyong666** [metersphere/metersphere#22688]
### MeterSphere 版本

V2.6.1

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/96411776/224940455-68cbf771-3cdd-444b-afe1-1a9cf0015cce.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/96411776/224940914-f664366f-bf6f-4d1e-9606-69521513df64.png)

**Comment by liuruibin** [comment]
您好，我们这里默认是有上传文件数限制的。

如果您需要上传很多个文件的话可以自定义jmeter镜像https://github.com/metersphere/jmeter-image，这个更方便
如果您的同时需要导入多个场景可以先将场景合并后再转成性能测试，在jmeter中不区分线程组名称，您可以调整好线程组名称后再转成性能测试

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v3.0会放开限制文件类型和文件个数。

**Comment by zhyong666** [comment]
> 您好，感谢您的反馈！计划v3.0会放开限制文件类型和文件个数。

好的~
