### ISSUE TITLE
[BUG][UI自动化]指令页签进行步骤操作后，添加步骤的按钮莫名消失

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#22710]
### MeterSphere 版本

v2.7.0-0dea7880

### 使用外置数据库

否

### 问题描述

指令页签进行步骤操作后，添加步骤的按钮莫名消失，需要重新打开指令编辑页面添加步骤icon才会显示出来

### 重现步骤

指令页签进行常规的添加步骤、设置步骤操作后继续进行添加步骤操作，有时出现添加步骤的icon没了

### 期待的正确结果

添加步骤的icon不会消失

### 附加信息

![1](https://user-images.githubusercontent.com/117417157/225189862-1e469f2c-4df5-4220-be7e-f1e310bc5103.gif)

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.7.1未复现该问题，建议升级尝试。
