### ISSUE TITLE
[BUG]前端vue配置jmeter前置脚本时加载第三方js报错

### ISSUE THREAD

**Issue by 18602738007** [metersphere/metersphere#22715]
### 联系方式

87513277@qq.com

### MeterSphere 版本

v2.7.1-b1

### 使用外置数据库

否

### 问题描述

MS: v2.7.1-b1

接口测试-->接口自动化-->场景步骤中-->前置脚本（  配置 JSR223 预处理程序）javascript

执行后 ，控制台提示加载外部脚本异常。

在v2.5.1版本通过测试的步骤，  升级到v2.7.1之后就报错了。

### 重现步骤

可以

### 期待的正确结果

web端可以正常读取外部js文件， 无报错信息 .

### 相关日志输出

```shell
2023-03-15 13:45:03 ERROR 85bc74a4 1-1 Problem in JSR223 script, BeanShellPreProcessor
TypeError: Cannot read property "Base" from undefined (/opt/metersphere/data/jmeter/jsrsasign-all-min.js#22) in /opt/metersphere/data/jmeter/jsrsasign-all-min.js at line number 22 at column number 0
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

### 附加信息

var navigator = this;
var window = this;

g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;
//load("https://cdn.bootcdn.net/ajax/libs/jsrsasign/10.5.13/jsrsasign-all-min.min.js");
load("/opt/metersphere/data/jmeter/jsrsasign-all-min.js");
log.info("jsrsasign加载成功");

**Comment by fit2-zhao** [comment]
感谢反馈，未曾复现您的问题，从错误  TypeError: Cannot read property "Base" from undefined (/opt/metersphere/data/jmeter/jsrsasign-all-min.js#22) in /opt/metersphere/data/jmeter/jsrsasign-all-min.js at line number 22 at column number 0
来看像是您自身js存在问题，如果方便可以把js发出来我们也试一下。

**Comment by 18602738007** [comment]
你好，感谢MS团队协助解决，这个问题在微信群给王进反馈过。












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]前端vue配置jmeter前置脚本时加载第三方js报错 (Issue #22715)





 
感谢反馈，未曾复现您的问题，从错误  TypeError: Cannot read property "Base" from undefined (/opt/metersphere/data/jmeter/jsrsasign-all-min.js#22) in /opt/metersphere/data/jmeter/jsrsasign-all-min.js at line number 22 at column number 0
 来看像是您自身js存在问题，如果方便可以把js发出来我们也试一下。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/225888414-90831681-7d7f-4d3d-9f85-e31e7fb0c9de.png)
JMeter 5.5中执行也是失败的，请检查js脚本吧。

**Comment by 18602738007** [comment]
这个js是官方共用的 检查什么？...你的版本执行失败了&nbsp; 我的执行成功了...











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月17日(星期五) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]前端vue配置jmeter前置脚本时加载第三方js报错 (Issue #22715)





 

 JMeter 5.5中执行也是失败的，请检查js脚本吧。

**Comment by fit2-zhao** [comment]
感谢反馈，这个问题是因为目前我们平台内置的测试引擎JMeter 5.5， JDK 使用的是17版本的原因，从JDK15 之后删除了Nashorn JavaScript 引擎，我们引入了新的 Mozilla Rhino 来支持JavaScript脚本；Rhino对于js的标准要求会更严格一些；建议按照错误提示规范调整下就可以了。

**Comment by 18602738007** [comment]
收到 感谢反馈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fit2-zhao ***@***.***&gt;
发送时间: 2023年3月24日 19:12
收件人: metersphere/metersphere ***@***.***&gt;
抄送: TAOTAO ***@***.***&gt;, Manual ***@***.***&gt;
主题: 回复：[metersphere/metersphere] [BUG]前端vue配置jmeter前置脚本时加载第三方js报错 (Issue #22715)

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
