### ISSUE TITLE
[BUG]测试报告用例数500+时打开报错

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#22716]
### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

接口自动化场景，用例数500+，分享测试报告连接，打开连接报错
![image](https://user-images.githubusercontent.com/3060035/225225338-9a65d4e7-99c8-46b1-afff-9d6a7ee6f700.png)

### 重现步骤

创建一个场景，添加用例数500+。生成测试报告

**Comment by youliyuan-fit2cloud** [comment]
你好，服务器配置如果比较高，可以修改下安装目录 /opt/metesphere/docker-compose-api-test.yml 中的内存限制，改大一些.然后重启服务。

**Comment by gaye746560359** [comment]
> 你好，服务器配置如果比较高，可以修改下安装目录/opt/metesphere/docker-compose-api-test.yml中的内存限制，修改大部分。然后重新启动服务。
加了内存也没用，一直转菊花
![image](https://user-images.githubusercontent.com/3060035/225570189-6d627e60-c85c-4463-bcdf-67ce931a22de.png)

**Comment by liuruibin** [comment]
您好，修改内存之后需要执行 msctl reload 使配置生效

**Comment by gaye746560359** [comment]
> 您好，修改内存之后需要执行msctl reload使配置生效

肯定执行过的

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/225806271-9b5591ea-bfe2-43b5-bba4-eeb0158658d5.png)

例如上图中文件 men_limit 默认值当前是1G，可以修改为2G就是2147483648，然后 msctl reload，
检查是否生效可以使用命令 docker stats，参考 如下图：

![image](https://user-images.githubusercontent.com/54612864/225806585-8337a71f-9d6e-46e2-b647-20996d94098b.png)

**Comment by gaye746560359** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/225806271-9b5591ea-bfe2-43b5-bba4-eeb0158658d5.png)
> 
> 例如上图中文件 men_limit 默认值当前是1G，可以修改为2G就是2147483648，然后 msctl reload， 检查是否生效可以使用命令 docker stats，参考 如下图：
> 
> ![image](https://user-images.githubusercontent.com/54612864/225806585-8337a71f-9d6e-46e2-b647-20996d94098b.png)

![image](https://user-images.githubusercontent.com/3060035/226221323-d2e2bb3b-9723-4b1a-8c49-799d742ac648.png)
![image](https://user-images.githubusercontent.com/3060035/226221365-256ad767-e85d-4c25-9fef-e9e646e45d54.png)

**Comment by song-tianyang** [comment]
打开分享场景的报告， v2.8优化了查询方式。报告内容会做异步处理，不会再将所有的数据都查出来。

这个改动应该可以帮到您

**Comment by gaye746560359** [comment]
> 打开分享场景的报告， v2.8优化了查询方式。报告内容会做异步处理，不会再将所有的数据都查出来。
> 
> 这个改动应该可以帮到您

好的，预计什么时候发布呢？主要是这个报告领导们要看

**Comment by song-tianyang** [comment]
v2.8预计这周四发布

感谢您的支持

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0中已修复，建议升级到最新版本v2.10。
