### ISSUE TITLE
[BUG]在脑图模式下创建的功能用力用例，保持成功后，在首页看板的用例数量统计里不体现

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#22714]
### MeterSphere 版本

1.20.20-lts

### 使用外置数据库

是

### 问题描述

在脑图模式下创建的功能用力用例，保持成功后，在首页看板的用例数量统计里不体现

### 重现步骤

脑图模式创建用例，保存成功，列表模式下可见，切到首页看板，功能用例数量不变，刷新浏览器亦然

**Comment by youliyuan-fit2cloud** [comment]
你好，使用的用例模版中的用例等级是否是必填？如果不是必填会这个问题，而且创建用例的时候没有选择用例等级会导致这个问题，计划下个版本修复。
