### ISSUE TITLE
[BUG] v2.7.0版本，api-test、track、gateway三个服务频繁因内存溢出而重启，在2.2.0旧版本不会出现该问题

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#22718]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

v2.7.0版本，api-test、track、gateway三个服务频繁因内存溢出而重启，在2.2.0旧版本不会出现该问题

感觉应该需要排查下，2.2.0版本没有出现过这个问题，但是升级到2.7.0后每天都因内存溢出而重启好几次

通过一键部署的，没有修改过默认配置

### 重现步骤

多个人同时操作ms，没有定位到是什么具体操作导致内存溢出而重启

### 附加信息

![image](https://user-images.githubusercontent.com/86464217/225229104-0f81704d-705e-4ea7-958b-a1e1666a0954.png)

**Comment by liuruibin** [comment]
您好，2.3之后我们升级了架构，会比2.2及之前版本更耗资源。您可以将服务器配置加高一些

**Comment by conansharp** [comment]
![image](https://user-images.githubusercontent.com/111938588/225530696-9326e42b-0c79-4511-bee2-08b983f10f79.png)
是不是这个启动参数设置的太小了，这个有地方可以改吗，容器的内存已经设置2g了，也没有超过这个值，内存异常只可能是jar启动的参数了吧

**Comment by liuruibin** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/23045261/225794300-54440f95-dc4c-440e-9f24-340c82c0f66a.png">
修改这里，或者在/opt/metersphere/.env 里加上 MS_API_MEM_LIMIT=2048m

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
