### ISSUE TITLE
[BUG]1、测试跟踪>>功能测试用例：点击查看用例，进入明细 2、点击编辑，修改该测试用例，比如操作步骤或者管理需求 3、点击保存，并且能成功保存 4、问题：该用例的【所属模块】为空，保存后，这个字段的信息被丢失了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22767]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

1、测试跟踪>>功能测试用例：点击查看用例，进入明细
2、点击编辑，修改该测试用例，比如操作步骤或者管理需求
3、点击保存，并且能成功保存
4、问题：该用例的【所属模块】为空，保存后，这个字段的信息被丢失了。

### 重现步骤

1、测试跟踪>>功能测试用例：点击查看用例，进入明细
2、点击编辑，修改该测试用例，比如操作步骤或者管理需求
3、点击保存，并且能成功保存
4、问题：该用例的【所属模块】为空，保存后，这个字段的信息被丢失了。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/225285901-a5251ba3-ba4e-4e38-8ddd-0e12c1e16e0a.png)
![image](https://user-images.githubusercontent.com/78218624/225286232-92a073ff-68ee-4026-b968-f610dcf0b5ec.png)
![image](https://user-images.githubusercontent.com/78218624/225287080-1ff25a3d-ec35-4a7b-a577-176f1d5a7031.png)

**Comment by luty2018** [comment]
感谢反馈， 这个我们已经修复了，会在下周发布v2.8版本。
