### ISSUE TITLE
[BUG]我的仪表盘里我的代办中测试计划数据统计有误，与实际数量不相符

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22779]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

我的仪表盘里我的代办中测试计划数据统计有误，与实际数量不相符。在我的待办中查询的实际数量只有不到十个。
<img width="960" alt="1678932884026" src="https://user-images.githubusercontent.com/83771182/225492210-098ae8bf-fdbd-4082-8f9a-9b34c21319b8.png">

### 重现步骤

我的仪表盘里我的代办中测试计划数据统计有误，与实际数量不相符。

**Comment by luty2018** [comment]
已转tapd，由开发跟进

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
