### ISSUE TITLE
[BUG]接口自动化执行测试，报告不刷新

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22787]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/25762331/225504735-7c3c48e3-6169-4259-af18-dcf3b25392b2.png)

![image](https://user-images.githubusercontent.com/25762331/225504614-7e5ae590-2983-47bc-affc-d402ed2409cf.png)

### 重现步骤

接口自动化执行测试，报告不刷新

**Comment by fit2-zhao** [comment]
感谢反馈，请问是否使用了nginx 了呢，如果使用了请参照：https://metersphere.io/docs/v2.x/installation/offline_installation/?h=nginx+%E9%85%8D%E7%BD%AE#6 这个配置一下。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
