### ISSUE TITLE
[BUG]执行用例时，自动提交bug至禅道，报500错误

### ISSUE THREAD

**Issue by CrDym** [metersphere/metersphere#2278]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  进入测试跟踪
2. 选择测试计划
3. 选择一条测试用例进行编辑
4. 在用例中打开【提缺陷按钮】，选择bug影响版本和处理人（禅道已配置完毕，可以拉取到版本信息和处理人字段）
**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/20080190/116039220-0d691980-a69d-11eb-899f-ad631b0b6f39.png)
![image](https://user-images.githubusercontent.com/20080190/116039294-25409d80-a69d-11eb-91ce-f74b1dae9e91.png)
![image](https://user-images.githubusercontent.com/20080190/116039319-2d98d880-a69d-11eb-8d55-665dfe295bad.png)

**Comment by zyyfit** [comment]
感谢反馈，这个问题将在1.9.0版本修复

**Comment by xulinde** [comment]
1.9.2已修复
