### ISSUE TITLE
[BUG]【用户组与权限】项目成员不勾选“删除用例”的权限，【测试跟踪-功能用例】页面，勾选某条用例，发现下面还有“删除”的选项，建议隐藏不显示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22784]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

【用户组与权限】项目成员不勾选“删除用例”的权限，【测试跟踪-功能用例】页面，勾选某条用例，发现下面还有“删除”的选项。

### 重现步骤

1.用户有“项目成员(系统)、工作空间成员(系统)”的角色
![image](https://user-images.githubusercontent.com/104960608/225495901-ffa77899-4937-4ac3-9408-35cc8ad9f3c7.png)
2.在【用户组与权限】项目成员不勾选“删除用例”的权限
![image](https://user-images.githubusercontent.com/104960608/225495688-666b89e9-b588-42c4-8f2b-a2493c24df96.png)
3.【测试跟踪-功能用例】页面，勾选某条用例，发现下面还有“删除”的选项。建议还是隐藏不显示较好。
![image](https://user-images.githubusercontent.com/104960608/225496156-1271afbb-e758-4c35-b658-130b91299633.png)
4.点击删除，提示错误信息。这个错误信息不明确
![image](https://user-images.githubusercontent.com/104960608/225496324-e464908b-efea-457d-bb4c-bb74ceb8513a.png)

**Comment by luty2018** [comment]
已转tapd，开发跟进。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
