### ISSUE TITLE
[FEATURE]项目可以修改工作空间、测试评审可以到处过程记录

### ISSUE THREAD

**Issue by zpzpp** [metersphere/metersphere#22780]
### MeterSphere 版本

v2.7.0-34d44a5e

### 请描述您的需求或者改进建议

希望能够实现以下功能：
1、项目可以修改工作空间，不然一旦创建就无法更改；
2、测试评审可以导出评审记录（项目管理需要需求评审过程记录文档）；
3、设立公共用例概念，目前用例是按工作空间、项目来划分的，有些通用用例是可以多个项目复用的，目前只能导出后再导入到新的项目中，如果可以把一部分用例设置为公共用例，同一工作空间、多个工作空间可以共享，就会方便很多。

**Comment by luty2018** [comment]
1.工作空间是高于项目的一个层级， 这里项目可以修改工作空间是什么意思没有看明白？或者是想解决什么问题？
2.测试评审在我们v3.0 会支持评审记录以及评审测试报告，报告也会支持导出。
3.目前已经支持公共用例库了，无需导入导出操作，公共用例库是企业版功能你可以在官网申请试用。

**Comment by zpzpp** [comment]
1、我们遇到的问题是一开始把项目创建到默认空间了，现在分工作空间后默认空间的项目无法换到新的工作空间中，这个问题可能是个个例，不知道有什么方法可以修改

**Comment by luty2018** [comment]
页面上确实没有提供， 可以数据库改一下

**Comment by zpzpp** [comment]
方便给下具体修改哪些字段吗？担心会有字段关联
