### ISSUE TITLE
[BUG]功能用例模板新增用例等级字段值，功能用例选择后列表及编辑页面显示异常

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#22792]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

功能用例模板新增用例等级字段值，功能用例选择后列表及编辑页面显示异常

### 重现步骤

1、功能用例模板内用例等级字段新增字段值
2、编辑某个用例选择新增的字段值
3、保存之后，查看列表及编辑页面

### 附加信息

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/32027713/225510834-b37b46e5-fbd6-4cbb-83ed-c5a075374457.png">

**Comment by luty2018** [comment]
已转tapd，开发已修复。
