### ISSUE TITLE
[BUG]接口定义，TEST和CASE，点击执行报错

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22790]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/25762331/225505004-202047f5-8605-47c6-893f-c4081eec23ed.png)
![image](https://user-images.githubusercontent.com/25762331/225505292-ef66cbda-086b-41d8-bb18-cb75b225bc34.png)

### 重现步骤

接口定义，TEST和CASE，点击执行报错

**Comment by fusu-qa** [comment]
把这个case放到接口自动化里执行，是成功的，说明不是环境的问题

**Comment by fit2-zhao** [comment]
感谢反馈，请问是否使用了nginx 了呢，如果使用了请参照：https://metersphere.io/docs/v2.x/installation/offline_installation/?h=nginx+%E9%85%8D%E7%BD%AE#6 这个配置一下。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
