### ISSUE TITLE
[BUG]接口定义，另存为新用例，页面崩溃

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#22791]
### MeterSphere 版本

2.7

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/25762331/225505918-ab9763e0-f8b7-4d82-9320-e0301e37775f.png)
![image](https://user-images.githubusercontent.com/25762331/225505951-67a505b9-9833-4be2-b433-46a5fa3889c5.png)

### 重现步骤

接口定义，另存为新用例，页面崩溃

**Comment by fit2-zhao** [comment]
感谢反馈，这里对json-schema格式处理确实有性能上的问题，您可以先切换到json格式就会正常使用，这个问题会在2.8版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
