### ISSUE TITLE
[FEATURE]由管理员维护项目

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#228]
**请描述您的需求或者改进建议.**
项目一般是由项目管理办公室或项目经理维护的，而非测试经理

**请描述你建议的实现方案**
设置只有管理员才有权限创建和修改项目信息

**Comment by youliyuan-fit2cloud** [comment]
您好，我们MeterSphere初衷是给测试人员使用，如果后期有调整或者有更多人提出这个需求，会考虑增加,请持续关注我们～
