### ISSUE TITLE
[BUG]长时间未操作登录失效未及时提醒,用户继续操作会导致编辑内容后，保存失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2281]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8.2
**Bug 描述**
简要描述您碰到的问题
长时间未操作登录失效未及时提醒或者显示不明确 ,用户还能继续操作，但是会导致编辑内容后，保存失败

**期待的正确结果**
长时间未操作登录失效情况下，应该强制退出系统，并让用户重新登陆后再操作

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前默认登陆超时时间是6小时，可在配置文件中修改登陆超时时间，如果一直在操作的话应该不会突然登陆超时

**Comment by dashenyucainiao** [comment]
1、很长时间（超过12小时）没有操作之后，直接点击页面进行操作没有让我强制登出，
2、还可以操作，当有保存或者编辑时，才会提醒我异常（并不会退出到登录页面）
3、在保存动作之前的填写的数据全部丢失。。。。

**Comment by xulinde** [comment]
v1.10.2版本已优化
