### ISSUE TITLE
[BUG]前置脚本变量不生效

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#22828]
### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

全局前置脚本生成加密参数sign,设置为变量无法引用

### 重现步骤

全局前置脚本
`import hashlib
import json
from os.path import normpath, basename

path = sampler.getUrl().getPath()
api = basename(normpath(path))

args = sampler.getArguments();
requestBody = args.getArgument(0).getValue()

body = json.loads(requestBody)
body.pop("sign", None)

ascii_values = []
for k, v in body.items():
    ascii_values.append((ord(k[0]), k, v))
sorted_dict = sorted(ascii_values)

strli = []
for li in sorted_dict:
    strli.append(li[1] + "=" + li[2])
li = ""
for i in strli:
    li += i + "&"
newstrli = li + "key={}".format(api.upper())
ms = hashlib.md5()
ms.update(newstrli.encode())
sign = ms.hexdigest().upper()
# log.info("sign:"+sign)
vars.put("sign", sign)
vars.put("sign", sign)
`
执行case时变量${sign}无法获取到值

**Comment by song-tianyang** [comment]
您好，您的全局前置脚本是写在哪一模块下了？
是单个步骤请求之前，还是所有步骤请求之前运行？

(所有步骤请求之前运行是专门为接口场景执行设计的，对接口用例不生效)

**Comment by gaye746560359** [comment]
> 

是单个步骤请求之前

**Comment by gaye746560359** [comment]
> 您好，您的全局前置脚本是写在哪一模块下了？ 是单个步骤请求之前，还是所有步骤请求之前运行？
> 
> (所有步骤请求之前运行是专门为接口场景执行设计的，对接口用例不生效)

进一步验证了下，全局前置脚本设置的变量，在接口的前置脚本中能打印出来，但是在接口的请求体中变量无法获取

**Comment by song-tianyang** [comment]
很抱歉隔了这么久才回复您。

我们很重视您的问题，并且在自己的服务器上做了测试。 发现一切正常。

我们的操作流程是这样的：

1.既然是api-case使用的前置脚本，我们要在测试环境-全局前置脚本-单个请求步骤前执行中编写脚本：
![image](https://user-images.githubusercontent.com/75963100/225825880-b587862e-2cb0-4383-b740-72003ece4ee9.png)

2.我们选择了一个Get请求的用例，将前置脚本的参数置位它的query参数栏中。选择环境，执行：
![image](https://user-images.githubusercontent.com/75963100/225826751-b33edec8-c832-43c8-ac19-a24d9a9734ed.png)

3.我们检查了请求地址，发现前置脚本里存放的变量正常取到了：
![image](https://user-images.githubusercontent.com/75963100/225826965-2e6fef04-001d-4482-a5a5-57bdb933c947.png)

**Comment by gaye746560359** [comment]
> 我们要在测试环境-全局前置脚本-单个请求步骤前执行中编写脚

你这里放确实有效。试试在这里放还有效不
![image](https://user-images.githubusercontent.com/3060035/225839317-539e7c4f-3fa6-4912-9af8-446253593e24.png)

**Comment by song-tianyang** [comment]
我刚才又试了下raw的格式。发现也是可以正常获取到数据的。 

下图是我的请求参数：
![image](https://user-images.githubusercontent.com/75963100/225882382-c42d162d-7748-46e4-9f1d-a5cc68a9cfec.png)

然后这里是发送内容：
![image](https://user-images.githubusercontent.com/75963100/225882565-c5e5792d-52d5-4bf3-a9ae-f966fb5a13b1.png)

**Comment by song-tianyang** [comment]
![image](https://user-images.githubusercontent.com/75963100/226235834-a7754b8e-36c2-4d20-b8ff-dad3eb75e8f9.png)

这是企业微信群聊的二维码。  这个issue先关闭了    如果我们的工作人员发现确实是bug，会由他们转告我们或者提一个新的issue的

谢谢您的支持
