### ISSUE TITLE
[FEATURE]测试计划支持完全串行运行测试用例

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#22831]
### MeterSphere 版本

v2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

测试计划支持完全串行运行测试用例，比如我在一个测试计划里有接口测试，场景测试，UI测试，压力测试，我理想中的串行运行时先运行接口测试，之后是场景测试，后UI测试，后压力测试
而不是像现在，选择串行运行后，
接口测试是串行，场景测试是串行，ui测试是串行，压力测试是串行
但是这四者是并行

**Comment by luty2018** [comment]
目前这样是考虑到提升执行效率，你说的按测试类型串行，目前的版本也可以通过创建多个测试计划来满足。

**Comment by YellCatt** [comment]
> 目前这样是考虑到提升执行效率，你说的按测试类型串行，目前的版本也可以通过创建多个测试计划来满足。

多个测试用例有很多问题，比如功能用例同时关联了接口和场景用例，怎么处理啊？而且很多情况下，也没有那么多环境让一个测试计划执行四种测试类型啊，测试环境的成本是否可以考虑一下？
