### ISSUE TITLE
[QUESTION]接口前置脚本如何替换请求体？

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#22832]
### 请描述您的问题

post请求，请求体是json，如何替换整个body？如何只替换其中一个参数？

**Comment by fit2-zhao** [comment]
您可以试试这样：

import org.apache.jmeter.protocol.http.util.HTTPArgument;
import org.apache.jmeter.config.Arguments;

Arguments arguments = new Arguments();
// 单个参数
HTTPArgument httpArgument = new HTTPArgument("key", "value");
arguments.addArgument(httpArgument);
// 添加到请求中
sampler.setArguments(arguments);

**Comment by gaye746560359** [comment]
> 您可以试试这样：
> 
> import org.apache.jmeter.protocol.http.util.HTTPArgument; import org.apache.jmeter.config.Arguments;
> 
> Arguments arguments = new Arguments(); // 单个参数 HTTPArgument httpArgument = new HTTPArgument("key", "value"); arguments.addArgument(httpArgument); // 添加到请求中 sampler.setArguments(arguments);

没有达到效果；期望是不改变原有的参数，新增一个键值对。目前实际结果是只有一个值
![image](https://user-images.githubusercontent.com/3060035/225799788-09282a73-c43c-44cf-9810-7e88f57c6bac.png)

**Comment by fit2-zhao** [comment]
您可以试试 sampler.getArguments().addArgument("k","v"); 这种。
