### ISSUE TITLE
[FEATURE]当功能用例、前置、后置用例都关联了自动化用例的时候，执行功能用例的时候，它们关联的自动化用例也能自动执行

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22833]
### MeterSphere 版本

2.7.1

### 联系方式

silverleo@163.com

### 请描述您的需求或者改进建议

当功能用例、前置、后置用例都关联了自动化用例的时候，执行功能用例的时候，它们关联的自动化用例也能自动执行

**Comment by luty2018** [comment]
感谢建议，你是指的功能用例在加入到测试计划时将这个用例的前后置功能用例以及前后置功能用例的关联用例都一并加入到测试计划吗？
