### ISSUE TITLE
[BUG]新版本IDEA插件无法连接

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#22834]
### 联系方式

张树彬

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

多个用户反馈，在msS的github官网下载的1.2.2和1.2.3版本idea插件，配置正确的信息后，总是无法连接；同样的信息连接 jenkins是成功的。

### 重现步骤

1. 进入github的ms官网
2. 下载1.2.2或1.2.3版本idea插件
3. 配置正确信息后，连接失败

### 期待的正确结果

希望连接成功

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/225792671-22e95636-edb1-44a1-acaf-d11b8e389f52.png)
![image](https://user-images.githubusercontent.com/77324661/225792740-0fe0541a-83ff-41f7-8041-5e5be7b5b47c.png)
<img width="1326" alt="c83c5194d21181fd3342a2385b7133b" src="https://user-images.githubusercontent.com/77324661/225792852-f5bfad22-3d55-4131-b098-aeecc5aacaa7.png">

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/22799 重复问题
