### ISSUE TITLE
[MOCK功能]mock响应体中 添加内置得函数 无法生效

### ISSUE THREAD

**Issue by iahiul** [metersphere/metersphere#22841]
### MeterSphere 版本

1.20.20-lts

### 使用外置数据库

否

### 问题描述

在使用mock功能时 添加了响应体使用内置函数 但实际响应体里面内置函数并未生效

### 重现步骤

1.mock响应体添加内置函数@time
![11e8bf83d4c79d615558ed11e9a9434](https://user-images.githubusercontent.com/110093328/225797554-f3712d89-0ccd-4559-b7b8-4420e710ac20.png)
2.测试发起mock请求 查看响应体
![b02d892080a4f760ea7aed7bce79306](https://user-images.githubusercontent.com/110093328/225797617-e4b78ad7-ccc7-46e2-94a5-558bb8ef65c2.png)

### 期待的正确结果

响应体中得ffff字段值应该是返回对应得@time时间

**Comment by song-tianyang** [comment]
您好，mock服务中暂时不支持mockJs的使用。

很抱歉，我们没有在前端页面处理好，让您误以为可以使用
