### ISSUE TITLE
[BUG]测试计划中添加场景用例，全选所有场景（不止一页数据），非当前页的某个场景含多个项目运行环境时，在测试计划中选择环境时无法选择多个项目环境，导致执行测试计划时一直running

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#22858]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

1、测试跟踪》测试计划》新建》关联场景用例》全选所有场景，我当时选中了300多个场景
![image](https://user-images.githubusercontent.com/86464217/225845198-8a1cf272-70a8-4469-b49c-46cf33a9cb00.png)
2、选择运行的环境
但是当非当前页的某个场景含多个项目运行环境时，在测试计划中选择环境时无法选择多个项目环境，只能选到当前页场景的原运行环境
![image](https://user-images.githubusercontent.com/86464217/225846584-81ae410a-7a64-4300-908b-ac1e28913e59.png)
3、如果按照步骤2保存了测试计划并且执行，没有任何提示且状态一直在running中
原因定位就是添加到测试计划里的某个场景没有配置运行环境

### 重现步骤

见问题描述

**Comment by luty2018** [comment]
这里环境展示是根据当前登录人的项目权限来判断的，并不是你选择的当前页数据。
正如你说的场景中存在跨项目的步骤，请检查当前账号是否也拥有其他项目的权限。

**Comment by minnn0306** [comment]
> 这里环境展示是根据当前登录人的项目权限来判断的，并不是你选择的当前页数据。 正如你说的场景中存在跨项目的步骤，请检查当前账号是否也拥有其他项目的权限。

当前账号拥有权限，而且我试过了，切换到那一页，勾选这个跨项目的场景，运行环境那边就会出现多个项目的环境了

**Comment by song-tianyang** [comment]
您好，我们了解到了您的问题，预计v2.8修复。

这样您在全选场景时， 运行环境会展示您选择的场景中所有涉及到的项目选项

**Comment by youliyuan-fit2cloud** [comment]
v2.8.0 中已修改，请升级一下吧～
