### ISSUE TITLE
[FEATURE]慎重考虑下这个需求，测试计划支持完全串行运行测试用例

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#22854]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

测试计划支持完全串行运行测试用例，比如我在一个测试计划里有接口测试，场景测试，UI测试，压力测试，我理想中的串行运行时先运行接口测试，之后是场景测试，后UI测试，后压力测试
而不是像现在，选择串行运行后，
接口测试是串行，场景测试是串行，ui测试是串行，压力测试是串行
但是这四者是并行

客服回复：目前这样是考虑到提升执行效率，你说的按测试类型串行，目前的版本也可以通过创建多个测试计划来满足。

其实我面对的情况是只有一个测试环境，且每天就只有12小时可以跑测试用例，如果创建多个测试计划，那么功能用例则无法关联接口用例，场景用例，性能用例，因为他们都分散在不同的测试计划中了

我希望官方可以慎重考虑下这个功能，毕竟，一个项目，最好只有一个测试计划，出一份测试报告。并不是每个人都有四个测试环境可供四种测试并行执行的。环境也是成本啊

**Comment by luty2018** [comment]
好的， 感谢建议， 这个我们会放到v3.0讨论规划。

**Comment by zhangzhaox** [comment]
"比如我在一个测试计划里有接口测试，场景测试，UI测试，压力测试，我理想中的串行运行时先运行接口测试，之后是场景测试，后UI测试，后压力测试" @YellCatt 完全串行主要目的是什么   是否应该保持前后依赖？（接口测试，场景测试，UI测试 ）三种测试用例分工明确，不同类型的用例，在执行上也没有依赖关系。性能测试确实应该最后单独执行

**Comment by YellCatt** [comment]
> "比如我在一个测试计划里有接口测试，场景测试，UI测试，压力测试，我理想中的串行运行时先运行接口测试，之后是场景测试，后UI测试，后压力测试" @YellCatt 完全串行主要目的是什么 是否应该保持前后依赖？（接口测试，场景测试，UI测试 ）三种测试用例分工明确，不同类型的用例，在执行上也没有依赖关系。性能测试确实应该最后单独执行

完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙的，而且功能测试用例关联了接口case和场景用例，是不能放在两个测试计划里的@zhangzhaox

**Comment by luty2018** [comment]
“完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙”
这个没有很理解怎么节约时间成本了， 麻烦进一步解释一下哈，帮助我们更好了解需求。
目前接口case和场景自动化如果是串行执行的话，是第一个接口case和第一个场景自动化用例一起跑，这样不是更提升执行效率吗？

**Comment by YellCatt** [comment]
> “完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙” 这个没有很理解怎么节约时间成本了， 麻烦进一步解释一下哈，帮助我们更好了解需求。 目前接口case和场景自动化如果是串行执行的话，是第一个接口case和第一个场景自动化用例一起跑，这样不是更提升执行效率吗？

第一个接口case和第一个场景自动化用例一起跑，你们的测试用例在一个环境里跑，不会报错吗？
第一个接口case和第一个场景自动化用例一起跑，这个的前提条件就是你们有两个相同的环境，才能做到一起跑，但是如果有两个一样的环境，应该是分发测试用例才是最高效的，而不是接口cese和场景一起并行运行

**Comment by YellCatt** [comment]
> “完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙” 这个没有很理解怎么节约时间成本了， 麻烦进一步解释一下哈，帮助我们更好了解需求。 目前接口case和场景自动化如果是串行执行的话，是第一个接口case和第一个场景自动化用例一起跑，这样不是更提升执行效率吗？

有一个前提条件啊，只有一个自动化测试环境啊，如果在这样的条件下，怎么做才能让场景自动化用例和接口case一起跑，且不会互相干扰，只能是完全串行，不然就只能分两个测试计划，分两个就浪费时间

**Comment by YellCatt** [comment]
> > “完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙” 这个没有很理解怎么节约时间成本了， 麻烦进一步解释一下哈，帮助我们更好了解需求。 目前接口case和场景自动化如果是串行执行的话，是第一个接口case和第一个场景自动化用例一起跑，这样不是更提升执行效率吗？
> 
> 有一个前提条件啊，只有一个自动化测试环境啊，如果在这样的条件下，怎么做才能让场景自动化用例和接口case一起跑，且不会互相干扰，只能是完全串行，不然就只能分两个测试计划，分两个就浪费时间

而且在补充一点，功能用例在两个测试计划里就不能跟测试用例相关联，所以目前ms这一套，最低的测试成本必须是两个自动化测试环境，UI的部分还不算。每多加一个测试，就必须部署一套环境，不然并行运行，之间有干扰，怎么判断是测试用例问题，还是环境问题，还是BUG？

**Comment by YellCatt** [comment]
> “完全串行是为了节约时间成本啊，我一个自动化测试环境就只有12个小时可以运行，接口case和场景测试用例中间是有时间空隙” 这个没有很理解怎么节约时间成本了， 麻烦进一步解释一下哈，帮助我们更好了解需求。 目前接口case和场景自动化如果是串行执行的话，是第一个接口case和第一个场景自动化用例一起跑，这样不是更提升执行效率吗？

我再举个例子，办公室的打印机，只能串行运行，如果要打印机并行运行，怎么办？多加一台打印机咯，有多少并行需求，就多加多少台打印机，第一这样可能不会发生干扰，第二，确实提高了效率。问题是增加了打印机成本，ms相同的道理啊

**Comment by luty2018** [comment]
我们建议用户从场景设计上去规避数据依赖的问题。
但是我们基于“除非前后置都无法去避免的时候，才可能是避免一起跑”这种场景去理解用户的需求。
会在v3.0去考虑规划，但依然不建议用户这么使用。
