### ISSUE TITLE
[BUG]V2.7.1, 运行环境 Http域名配置如果用变量，且变量实际赋值包含端口号，会导致接口请求URL中多了"[ ]"。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#22857]
### 联系方式

王进

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

V2.7.1, 运行环境 Http域名配置如果用变量，且变量实际赋值包含端口号，会导致接口请求URL中多了"[ ]"。

### 重现步骤

1. 准备任意一个接口用例。 
2. 新建一个环境，添加如下全局前置脚本：
ip='43.155.87.201:8080'
vars.put("f",ip)
log.info(f)
<img width="842" alt="1679039480610" src="https://user-images.githubusercontent.com/76033005/225844720-9ec3f350-bafb-4cfe-9b5c-2855a0b505eb.png">
3. 添加Http配置，配置如下：
${f}/console
<img width="847" alt="1679039521411" src="https://user-images.githubusercontent.com/76033005/225844894-6b568ce3-fc13-4e56-8148-ffd338653871.png">
4. 保存环境。
5. 打开接口用例，选择上面创建的环境，点击执行，查看请求内容
请求地址:
http://[43.155.87.201:8080]/console/api/v1alpha1/users
Body:
GET http://[43.155.87.201:8080]/console/api/v1alpha1/users

GET data:

[no cookies]

### 附加信息

客户升级到2.7.1之后发现这个问题，升级之前是2.6，说没有这个问题。
上面测试和截图复测步骤，已验证。

**Comment by 35plus** [comment]
补充：如果不加端口号“：8080”，测试是没问题的。

**Comment by fit2-zhao** [comment]
感谢反馈，目前我们使用的底层测试引擎JMeter对于变量当作url处理确实是这样，其实变量的使用方式比较多，用法也比较灵活，没必要执着某一种特定用法一定要达到特定效果。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #16839

**Comment by 35plus** [comment]
客户的应用场景是 访问某接口，返回一个json格式响应内容，里面有多个 IP:端口  的信息，取其中一条。他这个ip：端口是动态的。

**Comment by 35plus** [comment]
我尝试把 环境域名 改成 ${ip}:${port}/console这种格式的，但是MS平台不支持，提示error.

**Comment by 35plus** [comment]
<img width="792" alt="a99ab2f0ed602033b7ed6c9bfacc528" src="https://user-images.githubusercontent.com/76033005/226567638-df314270-8b57-4eec-ae3e-3ec0ffa70ee0.png">
 帮忙优化支持这种格式的环境域名。
