### ISSUE TITLE
[BUG]测试跟踪-缺陷管理：添加缺陷，上传的文件名过长时，导致提交bug失败，但是bug却已经同步至jira

### ISSUE THREAD

**Issue by minnn0306** [metersphere/metersphere#22859]
### 联系方式

daimin0306@163.com

### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

1、测试跟踪-缺陷管理-添加缺陷
2、上传文件，当文件名过长时，导致metersphere上提交bug失败，但是该bug确已经同步至jira

上传的文件如下
[嘎嘎嘎嘎嘎过过过过过过过过过过过过过过过看见就军军军军军军军军军军军军军军军军军反反复复付付付付付付付付付付batchAddFamily2+template3GGGGGGG嘎嘎嘎嘎嘎过过过过过过过过过过过过过过过看见就军军军军军军军军军军军军军军军军军反反复复付付付付付付付付付付batchAddFamily2+template3GGGGGGG.xls](https://github.com/metersphere/metersphere/files/10999148/batchAddFamily2%2Btemplate3GGGGGGG.batchAddFamily2%2Btemplate3GGGGGGG.xls)

### 重现步骤

同上

**Comment by luty2018** [comment]
已转开发跟进。

**Comment by song-cc-rock** [comment]
![image](https://user-images.githubusercontent.com/40567414/226265949-2e859322-381c-426b-8f73-0d3341efc7d0.png)
![image](https://user-images.githubusercontent.com/40567414/226265516-3a6db861-979a-4863-ac4e-8f63b9759ec3.png)
@minnn0306 我这边能使用该文件能正确添加到MS附件及同步到Jira附件中, 麻烦重试下, 如果还有问题, 麻烦请提供日志或截图.

**Comment by luty2018** [comment]
建议你周四升级到v2.8再试试，如果有问题可以重新打开issue
