### ISSUE TITLE
[BUG]接口自动化测试上传文件接口报错

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#22865]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

编写上传文件的接口，按要求请求体里面选择file类型，上传文件，保存，调试，报500错误，提示文件没有找到，见附件图片，附件pp.zip下载后改成pp.rar再解压即可看到图片

### 重现步骤

编写上传文件的接口，按要求请求体里面选择file类型，上传文件，保存，文件已经上传到服务器/opt/metersphere/data/body/d1d8110a-71ba-93e1-1c7e-16c0968be088路径下，调试，报500错误，提示文件没有找到，见图片
[pp.zip](https://github.com/metersphere/metersphere/files/10999517/pp.zip)

### 期待的正确结果

能成功上传，能正常自动化测试上传文件功能

**Comment by myliuq** [comment]
自动化脚本见附件，将Metersphere_Scenario_典型包场景化测试.zip下载下来改名为Metersphere_Scenario_典型包场景化测试.rar即可解压
[Metersphere_Scenario_典型包场景化测试.zip](https://github.com/metersphere/metersphere/files/10999527/Metersphere_Scenario_.zip)

**Comment by song-tianyang** [comment]
您好，感谢您的支持
我们导入了您的场景，然后将文件重新上传了一下，发现文件可以正常找到：
![image](https://user-images.githubusercontent.com/75963100/225897971-1c54bf80-ec39-4b44-be29-15090309188c.png)

**Comment by song-tianyang** [comment]
并没有其他操作。 我的脚本也是用的您发的第二个zip，文件也是在您给的第一个zip中拿的。
或者您加入我们企业微信群，我们的工作人员帮您看一下

**Comment by myliuq** [comment]
好的，怎么加到企业微信群？

**Comment by song-tianyang** [comment]
在我们这个项目的首页介绍中就有企业微信二维码的。

**Comment by song-tianyang** [comment]
这个issue先关闭了。

如果我们的工作人员发现确实是bug，会由他们转告我们或者提一个新的issue。

谢谢您的支持
