### ISSUE TITLE
[BUG]升级v2.3版本的 flyway sql 中大量修改各种场景报告、接口报告的状态，然而表中 status 没加索引，导致 sql 执行特别慢

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22897]
### 联系方式

shenkaibo

### MeterSphere 版本

v1 升级 v2.3之后版本均有次问题

### 使用外置数据库

否

### 问题描述

升级v2.3版本的 flyway sql 中大量修改各种场景报告、接口报告的状态，然而表中 status 没加索引，导致 sql 执行特别慢

### 重现步骤

升级v2.3版本的 flyway sql 中大量修改各种场景报告、接口报告的状态，然而表中 status 没加索引，导致 sql 执行特别慢，
建议 在修改这个 sql 之前，先对涉及修改的表的 status 加上索引，不然很慢，有的用户数据量特别大，要几个小时才能升级完。

**Comment by fit2-zhao** [comment]
感谢反馈，后续版本对相关字段及表结构均有优化，也预设了最大超时时间等，如果用户在升级时数据量比较大而失败的，可以手动执行“V2__2.3.0_release.sql ”SQL，也可以分批处理，升级SQL手动执行完成后，再次执行 这个SQL “update api_version set success =1 where version =2 and description ='2.3.0 release'; ” 就可以了。
