### ISSUE TITLE
[BUG]在环境里设置了全局前置脚本，在接口定义模块化中执行时不生效，但是在接口自动化中执行生效。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#22903]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

在环境里设置了全局前置脚本，在接口定义模块化中执行时不生效，但是在接口自动化中执行生效。
<img width="751" alt="ac8100b0e5cf7f62059769e88dc2b1c" src="https://user-images.githubusercontent.com/83771182/226240861-b72cbcd4-e7a3-4b1c-8c44-a86a41ae4c0c.png">
用参数方式设置请求头和全局变量
<img width="754" alt="2a6e8c966609f539e9c1b2ad8da917d" src="https://user-images.githubusercontent.com/83771182/226240900-1397ea96-b307-4a2c-bfc1-27b926061e04.png">
在接口自定义执行成功
<img width="650" alt="9314f2f9e59d8c79d18ae82fa21bee8" src="https://user-images.githubusercontent.com/83771182/226240955-559473f8-0ff3-4e3f-92e3-63caf3c40ba7.png">
同样的环境配置和接口，在接口定义执行失败，取不到值。
![image](https://user-images.githubusercontent.com/83771182/226241060-8af60402-6bd0-43d5-aa16-ef89af8fc7dd.png)

### 重现步骤

在环境里设置了全局前置脚本，在接口定义模块化中执行时不生效，但是在接口自动化中执行生效。

**Comment by song-tianyang** [comment]
您好，看您第一张图，是把脚本写在了”所有场景步骤前“执行。

这里的设置是只针对场景的。

如果您想在接口定义中使用全局前置脚本，请在”单个请求步骤前执行“这里设置。

给您带来的困扰深感抱歉！
