### ISSUE TITLE
[BUG]UI测试>>元素库：在列表中选择几个元素，选择【批量移动】，指定移动的文件夹。提示已经成功，但是最终没有移动到指定的文件夹中

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22900]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

[BUG]UI测试>>元素库：在列表中选择几个元素，选择【批量移动】，指定移动的文件夹。提示已经成功；刷新页面，查看最终信息，没有移动到指定的文件夹中

### 重现步骤

[BUG]UI测试>>元素库：
1、在列表中选择几个元素，选择【批量移动】，
2、指定移动到MS文件夹。
3、提示已经成功；
4、刷新页面，
5、查看最终信息，没有移动到指定的文件夹中

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/226238383-3aa7a21b-064d-4278-946c-75d1e389def8.png)

![image](https://user-images.githubusercontent.com/78218624/226238570-7258b1bd-e39f-454c-b64f-f0ebb272fb5a.png)
![image](https://user-images.githubusercontent.com/78218624/226238614-2c615ed3-6267-4fb2-8e64-a88350f1fb6d.png)
![image](https://user-images.githubusercontent.com/78218624/226238690-6a33a43d-06a3-404e-a5fc-c8bcfca55157.png)

**Comment by huangxine** [comment]
![image](https://user-images.githubusercontent.com/78218624/226239037-327dfc68-75be-4fe9-8e5c-b64d00644d7b.png)

**Comment by xiaomeinvG** [comment]
您好，感谢反馈，该问题我们已在v2.8版本中修复，待发布后可升级验证
