### ISSUE TITLE
[BUG]【测试跟踪】当前模块的用例点击“复制”，所属模块会变成“未规划用例”而不是原本模块。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22901]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

【测试跟踪】当前模块的用例点击“复制”，所属模块会变成“未规划用例”而不是原本模块。
![image](https://user-images.githubusercontent.com/104960608/226239382-c4a8357f-db63-4f0c-8b8d-f80e2bd51080.png)

![image](https://user-images.githubusercontent.com/104960608/226239474-28756495-e8e5-43d0-92e1-eaf5ba1d91a1.png)

### 重现步骤

【测试跟踪】当前模块的用例点击“复制”，所属模块会变成“未规划用例”而不是原本模块。
![image](https://user-images.githubusercontent.com/104960608/226239382-c4a8357f-db63-4f0c-8b8d-f80e2bd51080.png)

![image](https://user-images.githubusercontent.com/104960608/226239474-28756495-e8e5-43d0-92e1-eaf5ba1d91a1.png)

**Comment by luty2018** [comment]
没有复现，2.7.1已经改了， 在qa环境测试。
