### ISSUE TITLE
[BUG]【测试跟踪】测试用例点击“编辑”按钮进入无法修改，还得点击“编辑”按钮才能进行修改

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22902]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

【测试跟踪】测试用例点击“编辑”按钮进入后，无法修改，还得点击“编辑”按钮才能进行修改
![image](https://user-images.githubusercontent.com/104960608/226240350-66e99c2e-f1d1-4d5f-ba01-89afd5039fcc.png)

![image](https://user-images.githubusercontent.com/104960608/226240580-bbc0ebb4-db21-4a27-8bab-104f4ae5313b.png)

### 重现步骤

【测试跟踪】测试用例点击“编辑”按钮进入后，无法修改，还得点击“编辑”按钮才能进行修改
![image](https://user-images.githubusercontent.com/104960608/226240350-66e99c2e-f1d1-4d5f-ba01-89afd5039fcc.png)

![image](https://user-images.githubusercontent.com/104960608/226240580-bbc0ebb4-db21-4a27-8bab-104f4ae5313b.png)

**Comment by luty2018** [comment]
收到 ，这里我们优化一下。
