### ISSUE TITLE
[BUG]UI测试>>元素库&UI自动化列表：设置表头后，刷新页面不彻底，造成批量操作的点按钮没有。具体操作见明细

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22914]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

[BUG]UI测试>>元素库&UI自动化列表：设置表头后，刷新页面不彻底，造成批量操作的点按钮没有。具体操作见明细

操作：
1、在列表中，选择了2个脚本，批量操作的点点按钮也出现了
2、这时点击右上角的设置，设置了列表显示信息，点击确认
3、页面进行了刷新，但是批量操作的点点按钮没有刷新掉。
4、再次选择刚才选择的那两个脚本，批量操作的点点按钮消失了，无法实现批量操作了

### 重现步骤

[BUG]UI测试>>元素库&UI自动化列表：设置表头后，刷新页面不彻底，造成批量操作的点按钮没有。具体操作见明细

操作：
1、在列表中，选择了2个脚本，批量操作的点点按钮也出现了
2、这时点击右上角的设置，设置了列表显示信息，点击确认
3、页面进行了刷新，但是批量操作的点点按钮没有刷新掉。
4、再次选择刚才选择的那两个脚本，批量操作的点点按钮消失了，无法实现批量操作了

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/226260706-e8b80f60-67d7-4d48-9ea0-92edcc30dc0a.png)
![image](https://user-images.githubusercontent.com/78218624/226260972-58291beb-76d7-4de6-9bab-807c4c40192e.png)
![image](https://user-images.githubusercontent.com/78218624/226261099-0b8906ab-9c4e-448f-b3d7-d14e7e792f42.png)

**Comment by Hyyfit** [comment]
已确认，2.8修复
