### ISSUE TITLE
[BUG]测试云环境，环境设置：添加误报规则-选择响应时间配置后添加不生效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#22929]
### MeterSphere 版本

  v1.20.20-lts-79d354a6

### 使用外置数据库

否

### 问题描述

测试云环境，环境设置：添加误报规则-选择响应时间配置后添加不生效

### 重现步骤

测试云环境，环境设置：添加误报规则-选择响应时间配置后添加不生效

![测试云环境，误报规则添加响应时间点击](https://user-images.githubusercontent.com/43202800/226271885-8d6e9ece-2681-4eea-94af-ffae298f0b28.png)

### 期待的正确结果

按照规则保存生效

**Comment by luty2018** [comment]
已复现，tapd转开发跟进
