### ISSUE TITLE
[BUG]UI测试缺少判断元素是否存在的步骤

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#22921]
### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

我的场景是 A到B页面 B页面会存在2种可能，从A进入到B页面，我想做个判断，如果能找到“某元素”进入 b-1操作，找不到进入到b-2操作

### 重现步骤

我的场景是 A到B页面 B页面会存在2种可能，从A进入到B页面，我想做个判断，如果能找到“某元素”进入 b-1操作，找不到进入到b-2操作

### 期待的正确结果

有个判断元素是否存在的步骤
现在的问题就是没有判断元素是否存在的操作

**Comment by Hyyfit** [comment]
您好，可以结合流程控制实现,步骤如下:
1.元素操作-等待元素存在，注意这里的错误处理选择“忽略异常并继续”。
2.在高级设置中添加数据提取，store  a=1。
3.添加流程控制-if条件判断
4.if${a}== 1，进入b1
5.else 进入b2
