### ISSUE TITLE
[BUG]UI测试>>有关鼠标拖拽的自动化脚本，导出后，所有的相关鼠标拖拽设置都没有被导出。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#22936]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

[BUG]UI测试>>有关鼠标拖拽的自动化脚本，导出后，所有的相关鼠标拖拽设置都没有被导出。

### 重现步骤

[BUG]UI测试>>有关鼠标拖拽的自动化脚本，导出后，所有的相关鼠标拖拽设置都没有被导出。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/226278957-47aba309-5b1c-4efb-8076-f4f7c4c7aaa4.png)
![image](https://user-images.githubusercontent.com/78218624/226279117-4b26d336-10ee-49c6-801b-9caacb1fc4c1.png)
导出文件无法上传，如果需要可以下线提供

**Comment by zrfit** [comment]
您好，感谢您的反馈！
鼠标拖拽-元素内部拖拽是metersphere的拓展功能，导出格式为ide，ide并没有对应的指令，所以鼠标拖拖拽-元素内部拖拽导出后会变为鼠标拖拽-操作元素a-->目标元素a的形式。
