### ISSUE TITLE
[BUG]接口导出再导入部分响应体数据丢失。

### ISSUE THREAD

**Issue by tianyihuhu** [metersphere/metersphere#22932]
### 联系方式

huxueyan_will@126.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

当JSON-SCHEMA关闭时，导出接口再次导入后，导入接口响应体正常，当JSON-SCHEMA打开时，导出接口再次导入后，导入接口响应体丢失部分结构。

### 重现步骤

复现步骤：
1.接口响应体JSON-SCHEMA打开时，导出接口-Swagger3.0格式导出json文件
2.在其他项目中导入json文件，查看对应接口响应体是否完整。

响应体参考：
{
    "status": 200,
    "message": "成功",
    "success": true,
    "data": {
        "defaultExpandedKeys": [
            "${__Mock(@string)}"
        ],
        "defaultCheckedKeys": [
            "${__Mock(@string)}"
        ],
        "sourceData": [
            {
                "name": "${__Mock(@name)}",
                "id": "${__Mock(@id)}",
                "type": "${__Mock(@string)}",
                "isActive": false,
                "isSelect": false,
                "isLeaf": false,
                "children": [
                    
                ],
                "isOperate": ""
            }
        ]
    }
}

### 期待的正确结果

预期：新导入的接口响应体内容与导出的接口响应体内容保持一致。

### 附加信息

![image](https://user-images.githubusercontent.com/16482933/226274894-b4df40cd-4e71-4945-aa26-df565c44f5b6.png)

**Comment by xiaomeinvG** [comment]
感谢反馈，已复现该问题，后续版本修复

**Comment by luty2018** [comment]
已转tapd，开发跟进

**Comment by 13290445582** [comment]
v2.9.0已修复
