### ISSUE TITLE
[BUG] 删除场景后，场景覆盖率未改变，回收站清空场景后，场景覆盖率正常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#22933]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

 删除场景后，场景覆盖率未改变，回收站清空场景后，场景覆盖率正常

### 重现步骤

场景覆盖率未0，总共33个接口
![image](https://user-images.githubusercontent.com/103925124/226275219-5b32e6bf-8aed-4a11-a5bd-18a7c94d5c8c.png)
新建场景导入33个接口后保存
![image](https://user-images.githubusercontent.com/103925124/226275734-a255e50a-9c1f-4b39-a101-ca435cdae990.png)
覆盖率未100%
![image](https://user-images.githubusercontent.com/103925124/226275884-83e7566c-0f02-449c-8ddf-95dc4728ab6f.png)
删除场景后，依然为100%
将回收站清空后，为0%，正确
![1679298161235](https://user-images.githubusercontent.com/103925124/226276357-fc5381fe-8c7b-445f-80ff-1a74e680e4a5.png)

### 期待的正确结果
删除后，覆盖率也正常
_No response_

**Comment by luty2018** [comment]
目前确实是这么设计的，只要系统中存在就会计算覆盖率，彻底删除了才会影响统计。你可以转成需求我们3.0 再规划。
