### ISSUE TITLE
[BUG]老版本的接口定义和接口用例导出json文件后再导入到新版本，导入失败

### ISSUE THREAD

**Issue by tygk** [metersphere/metersphere#22939]
### 联系方式

1026526269@qq.com

### MeterSphere 版本

 v2.1.0-b1和v2.7.1-b3

### 使用外置数据库

是

### 问题描述

外置数据库，通过导出和导入方式无法恢复数据

### 重现步骤

老版本ms v2.1.0-b1，数据库5.7版本；
新版本ms  v2.7.1-b3，数据库8.0；
外置独立数据库；
没有通过数据库同步数据，mysql8.0版本中msterspere database为空；
1. 把老版本的接口用例导出为metersphere格式json文件，再导入到新版本的ms上，提示“格式错误”；
2. 把老版本的接口用例导出为swagger 3.0格式json文件，再导入到新版本的ms上，提示“格式错误”；
3. 把老版本的接口用例导出为swagger 3.0格式json文件，再导入其他API工具，可以导入成功；

**Comment by xiaomeinvG** [comment]
您好，感谢您的反馈，从您的步骤来看：
对于第一步： ms系统导入导出基于数据库有相应的表结构运行的，建议您执行一下flyway,先生成相应的表结构再试一下
对于第二步： ms系统导入swagger 文件时需要您选择swagger的导入形式执行。

**Comment by tygk** [comment]
1.&nbsp; &nbsp;单独部署了一个mysql8.0版本，手动创建了metersphere database，相当于此时的database是空的，此时必须要先进行所有表结构同步才能导入接口文件？
2.&nbsp; &nbsp;metersphere上也是先导出为swagger 3.0格式的文件，再导回到ms上，选择swagger，导入也是“格式错误”；

**Comment by xiaomeinvG** [comment]
您好，如果在运行ms项目之前您已创建了metersphere database ，是不必要先同步的，如果可以，希望您提供一下错误日志，方便我们进行判断。

**Comment by tygk** [comment]
你好，请查收附件

**Comment by xiaomeinvG** [comment]
您好，没有在您的邮件中看到附件，请确认发送成功了吗

**Comment by tygk** [comment]
再试试呢，这次分别上传了原文件和压缩了下：

**Comment by xiaomeinvG** [comment]
您好，可能是github的原因，没能收到您的附件，在您留的联系方式中发送了邮件，请注意查收，给您带来的不便深感抱歉

**Comment by xiaomeinvG** [comment]
感谢您的反馈，问题已知晓，我们将在v2.8版本修复该问题。
