### ISSUE TITLE
[BUG]脑图模式下编辑子级模块，拼音的第一个字母会被当成英文

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#22944]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.20-lts&v2.7.1

### 使用外置数据库

否

### 问题描述

脑图模式下在选中的当前模块点击空格键弹出菜单，再通过Tab键创建子级模块。编辑子级模块，拼音的第一个字母会被当成英文

### 重现步骤

1.在脑图模式下，点击空格，点击tab键
![image](https://user-images.githubusercontent.com/88763608/226298224-4c7e7779-9811-4abd-b993-8ad823c16387.png)
2.在子级模块中输入拼音，结果第一个字母没有被输入法识别成拼音
![image](https://user-images.githubusercontent.com/88763608/226298460-078c49b3-fd75-4b6f-b0db-c4827e1db7bd.png)

### 期待的正确结果

子级模块能正常输入拼音

**Comment by luty2018** [comment]
重新输一次就好了
