### ISSUE TITLE
[BUG]Azure Devops 平台，创建缺陷，创建人不是【个人信息】配置的 token 对应的人，而是 【工作空间】配置的 token 对应的人

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22942]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

Azure Devops 平台，创建缺陷，创建人不是【个人信息】配置的 token 对应的人，而是 【工作空间】配置的 token 对应的人

### 重现步骤

Azure Devops 平台，创建缺陷，创建人不是【个人信息】配置的 token 对应的人，而是 【工作空间】配置的 token 对应的人

**Comment by luty2018** [comment]
已在v2.8修复

**Comment by 13290445582** [comment]
您好，您提供的问题，经过执行，并未复现，麻烦您在v2.8重现并提供可测试环境。
