### ISSUE TITLE
[BUG]Azure Devops 平台 同步缺陷报错，数组越界

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#22943]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

Azure Devops 平台 同步缺陷报错，数组越界

### 重现步骤

![image](https://user-images.githubusercontent.com/30038088/226297015-2f5e4ebe-2c9b-4ae7-8afe-27fce4d47484.png)

**Comment by luty2018** [comment]
已在v2.8修复
