### ISSUE TITLE
[BUG]元素库的元素表达式有格式问题时，UI场景无法调试，且页面没有任何提示

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#22952]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

元素库的元素表达式有格式问题时，UI场景无法调试，且页面没有任何提示

### 重现步骤

1.元素库中创建一个任意元素，表达式类似这么写//*[@id="${logname"]/div[1]/div/div[1]/div/div[3]/button。${}符号是不完整的。
2.在场景中引用该元素并执行场景。没有任何提示，但是无法运行。
![image](https://user-images.githubusercontent.com/88763608/226314266-b2d6cf9d-c556-440e-bfdf-c25bb37b72b7.png)
3.后台日志可以看到是因为定位表达式格式出错。
<img width="518" alt="09101ff1f9e4065f126cc227c7f84be" src="https://user-images.githubusercontent.com/88763608/226314374-34f4c685-cc11-46e7-8e92-6e093a660015.png">

### 期待的正确结果

要有提示，不然这种异常看起来会很怪异，应该在页面上给相关提示。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交到tapd，开发跟进

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
