### ISSUE TITLE
[BUG]【接口自动化】当执行结果为“误报”时，“定时任务”的消息通知里的选项设置只有执行成功/失败，没有误报的选项。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#22967]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

【接口自动化】当执行结果为“误报”时，“定时任务”的消息通知里的选项设置只有执行成功/失败，没有误报的选项。
![image](https://user-images.githubusercontent.com/104960608/226506644-88cec7db-cf17-46d1-bb23-c81af2bda61e.png)

![image](https://user-images.githubusercontent.com/104960608/226506720-ed1561f7-d208-48fd-a0d2-e902cfc5659e.png)

### 重现步骤

【接口自动化】当执行结果为“误报”时，“定时任务”的消息通知里的选项设置只有执行成功/失败，没有误报的选项。
![image](https://user-images.githubusercontent.com/104960608/226506644-88cec7db-cf17-46d1-bb23-c81af2bda61e.png)

![image](https://user-images.githubusercontent.com/104960608/226506720-ed1561f7-d208-48fd-a0d2-e902cfc5659e.png)

**Comment by 13290445582** [comment]
您好，目前产品设计为支持发送执行成功和执行失败选项，若有需要误报通知需求，后续版本我们可以计划添加需求，谢谢反馈
