### ISSUE TITLE
[BUG]性能测试-场景A下--【已存在的文件】-未能展示场景A下上传的JMX文件A

### ISSUE THREAD

**Issue by zhyong666** [metersphere/metersphere#22970]
### MeterSphere 版本

V2.6.1

### 使用外置数据库

否

### 问题描述

场景A下-已存在的文件-不能展示场景A已上传的jmx文件A-导致重新上传脚本A-需要到其他场景下执性重新上传操作
![image](https://user-images.githubusercontent.com/96411776/226508628-c0f4801c-21ca-4aa8-b646-f98176c929a5.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/96411776/226508615-dc640b12-db22-478d-932b-40f283829f73.png)

**Comment by liuruibin** [comment]
您好，这个问题我没有复现。您可以把详细步骤做个录屏方便我们定位，也将后台的报错日志一起提供给我们

**Comment by zhyong666** [comment]
> Reference in new issue



> 您好，一个jmx只能引用一次。重复使用的话jmeter无法识别相同名字的线程组和采样器。这会被判定为同一个

您好，那么【脚本重新】上传这个功能，就仅能在其他场景中进行了~

建议：脚本重新上传的操作，在如下【资源文件】下进行，是不是更方便些

![image](https://user-images.githubusercontent.com/96411776/226789834-987971c5-62d5-4fce-a8ad-cff609f9f24b.png)
