### ISSUE TITLE
[BUG]接口定义：swagger导入（使用Url方式）报错

### ISSUE THREAD

**Issue by mengshuai85** [metersphere/metersphere#22979]
### 联系方式

mengshuai85@163.com

### MeterSphere 版本

v2.7.1-9947cfcf

### 使用外置数据库

否

### 问题描述

1. 在使用swagger 在线URL 方式导入接口定义时，报错：Swagger 解析失败，请确认文件格式是否正确
2. 但是通过swagger-doc 另存为 文件后，通过文件上传方式，可以正常导入

swagger 版本是3 的时候，提示这个错误
当swagger版本是2的时候，正常 导入

![image](https://user-images.githubusercontent.com/5234760/226528872-ae6562c9-86a7-4d34-a55c-ae7e1666281e.png)

### 重现步骤

1. swagger-doc 内容版本：{"openapi":"3.0.3","info":{"title":
![image](https://user-images.githubusercontent.com/5234760/226529130-47f05add-eb57-4b08-9065-20e87015d786.png)

保存后就提示错误了

**Comment by 13290445582** [comment]
您好，您提供的问题目前我们尚未复现成功，您这边是否方便提供下错误日志与swagger-doc文件，以便我们更快速的复现，谢谢

**Comment by mengshuai85** [comment]
找到原因了，json文件能导入成功，但是URL方式失败，

**Comment by mengshuai85** [comment]
> 您好，您提供的问题目前我们尚未复现成功，您这边是否方便提供下错误日志与swagger-doc文件，以便我们更快速的复现，谢谢

找到原因了，json文件能导入成功，但是URL方式失败，
原因是 使用url方式时，需要增加 cookie请求头，原来没有添加，一直失败
通过网页直接打开 swagger-doc 文档，自动带这个参数了

![image](https://user-images.githubusercontent.com/5234760/226775070-3a110bdd-40a7-45b9-bb23-28b207668c7d.png)
