### ISSUE TITLE
[BUG]  一个场景引用另一个场景，其中一个场景名称很长，引进来之后名字展示补全，也没有提示，不易于查看。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#22981]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.8

### 使用外置数据库

否

### 问题描述

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/33945037/226535522-3e28d84b-98e1-4ac1-8d5a-78fd4a82c68e.png">

1. 创建一个名字很长的场景
2. 在创建一个场景，引用上一个场景。

### 重现步骤

同上

**Comment by 13290445582** [comment]
您好，名称这里过长后会有滚动条显示，后面留白是因为需要预留空间展示执行的结果。您可以再试一下。![image](https://user-images.githubusercontent.com/128017892/226539767-7ae29857-9b46-49b3-9df9-c4680fdc0afa.png)
