### ISSUE TITLE
[BUG]登录超时不回到登录页面

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#2298]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.2
**Bug 描述**
登录超时不回到登录页面，一直提示Network Error

**Bug 重现步骤**
1.  登录之后放置一段时间，等待超时
2. 

**期待的正确结果**
正确情况下应该是什么样的？
回到登录页面
**截图**
如果有截图，请附上截图.
![111](https://user-images.githubusercontent.com/29306248/116075983-3a7df200-a6c6-11eb-84cc-ef9904839f39.jpg)

**Comment by xulinde** [comment]
现在还会出现此问题吗

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
