### ISSUE TITLE
[FEATURE]测试跟踪模块样式优化建议

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#230]
建议对以下页面样式进行优化以增强易用性：
1、测试跟踪-首页，我的计划面板宽度不够，导致内容显示不全，建议：
1.1、我的计划中的表格内容支持换行显示
1.2、最近测试面板另起一行放置
2、测试跟踪-项目-全部项目页面，创建时间、更新时间、操作列内容比较固定，空间建议紧凑一点，将空间留给名称和描述列，表格内容建议默认自动换行
3、测试用例-全部用例页面，ID、类型、测试方式列内容相对固定，空间建议紧凑一点，表格内容建议默认支持自动换行
4、测试计划-全部计划页面，负责人显示的是用户名，建议显示中文姓名；负责人、当前状态、测试阶段、更新时间、操作列内容固定，建议紧凑一点；表格内容建议支持自动换行；创建时间列和更新时间列作用重复，建议只显示更新时间列
5、测试计划明细页面的用例表格中，ID、优先级、类型、测试方式、执行人、执行结果、更新时间、操作列内容长度固定，建议列宽紧凑一点，空间留给其他列；表格内容建议自动换行
6、项目、用例、测试计划列表最多每页只显示100个，用例多时很不方便，建议增加到每页最多500个

**Comment by wangzhen-fit2cloud** [comment]
@luty2018

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已进行修改
