### ISSUE TITLE
[BUG]【环境设置】数据库配置处有不能为空提示，将每一项都进行填写完后，“数据库驱动”下边还存在提示“不能为空”

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23002]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

1.【环境设置】数据库配置处，啥都不填直接点击确定，每一项下面都有提示
![image](https://user-images.githubusercontent.com/104960608/226570300-dd050db9-4b27-4a3b-850f-3ddcab3cda2b.png)

2.将每一项都进行填写完后，就这“数据库驱动”下边还存在提示“不能为空”
![1679391944534](https://user-images.githubusercontent.com/104960608/226569734-80d8c792-3f4b-41cc-b9db-061a93c4b893.png)

### 重现步骤

1.【环境设置】数据库配置处，啥都不填直接点击确定，每一项下面都有提示
![image](https://user-images.githubusercontent.com/104960608/226570300-dd050db9-4b27-4a3b-850f-3ddcab3cda2b.png)

2.将每一项都进行填写完后，就这“数据库驱动”下边还存在提示“不能为空”
![1679391944534](https://user-images.githubusercontent.com/104960608/226569734-80d8c792-3f4b-41cc-b9db-061a93c4b893.png)

**Comment by 13290445582** [comment]
感谢反馈，您提供的问题已复现并提交至tapd平台，开发跟进
