### ISSUE TITLE
[BUG]【插件管理】删除插件时的提示“删除需重启服务后生效?”应该是个肯定句，而不是问句

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23005]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

删除插件时的提示“删除需重启服务后生效?”应该是个肯定句，而不是问句
![image](https://user-images.githubusercontent.com/104960608/226572683-6b72818c-3fb7-4863-b49c-53d46cda5463.png)

### 重现步骤

删除插件时的提示“删除需重启服务后生效?”应该是个肯定句，而不是问句
![image](https://user-images.githubusercontent.com/104960608/226572683-6b72818c-3fb7-4863-b49c-53d46cda5463.png)

**Comment by 13290445582** [comment]
感谢反馈，已经复现并提交到tapd，开发跟进
