### ISSUE TITLE
[BUG]【模板管理】创建字段时，使用场景设置为测试计划，但是并没有看到可以设置测试计划模板的地方，而且设置了在测试计划里并没有显示该字段

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23008]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

模板字段-创建字段时，使用场景设置为测试计划，但是并没有看到可以设置测试计划模板的地方，而且设置该字段在测试计划里并没有显示

### 重现步骤

模板字段-创建字段时，场景设置里有测试计划，但是并没有看到可以设置测试计划模板的地方，而且设置该字段在测试计划里并没有显示
![f526d903eb7add618bdea4f67bf1ca1](https://user-images.githubusercontent.com/104960608/226576089-a059e655-f2d7-4b74-973b-cf7d11de7b6c.png)

**Comment by 13290445582** [comment]
您好，产品目前设计如此，后续会对测试计划模块进行优化，感谢反馈。
