### ISSUE TITLE
[BUG]【插件管理】上传jmeter的jar提示上传成功，在日志中查询到上传成功，但是在列表中没有展示出来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23006]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

上传jmeter的jar提示上传成功，在日志中查询到上传成功，但是在列表中没有展示出来

### 重现步骤

1.上传jmeter的jar提示上传成功，但是在列表中没有展示出来
![image](https://user-images.githubusercontent.com/104960608/226572987-94989f68-66b4-4d3f-8af3-cf29697401d2.png)

![image](https://user-images.githubusercontent.com/104960608/226573088-95531932-5d39-4991-98c1-19da3642003e.png)

![image](https://user-images.githubusercontent.com/104960608/226573188-80b7ae00-7244-4bd9-bc46-cc727d899911.png)

2.在日志中查询到上传成功
![image](https://user-images.githubusercontent.com/104960608/226574598-264b948f-8435-48ee-ba31-c5a308d9f809.png)

3.这个jar包如下
[radiussampler.zip](https://github.com/metersphere/metersphere/files/11027012/radiussampler.zip)

**Comment by 13290445582** [comment]
感谢反馈，已提交tapd，开发跟进
