### ISSUE TITLE
[BUG]【环境配置】全局前置/后置脚本处的下拉框，展示的请求类型与接口定义处的不统一。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23018]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

1.在接口定义处可看到是 http/tcp/sql/dubbo等选项
![image](https://user-images.githubusercontent.com/104960608/226605680-6ddd5df0-ee90-475c-826f-330488abb717.png)

2.在环境下拉框里是 http/tcp/jdbc/dubbo 等选项，能否统一。
![image](https://user-images.githubusercontent.com/104960608/226605937-15970be3-4eb1-4856-b12a-76eb32433e1f.png)

### 重现步骤

1.在接口定义处可看到是 http/tcp/sql/dubbo等选项
![image](https://user-images.githubusercontent.com/104960608/226605680-6ddd5df0-ee90-475c-826f-330488abb717.png)

2.在环境下拉框里是 http/tcp/jdbc/dubbo 等选项，能否统一。
![image](https://user-images.githubusercontent.com/104960608/226605937-15970be3-4eb1-4856-b12a-76eb32433e1f.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
