### ISSUE TITLE
[FEATURE]用例不支持按照等级排序

### ISSUE THREAD

**Issue by Walter-Shui** [metersphere/metersphere#2301]
用例现在分为P0，P1，P2,P3等级。建议支持按照等级进行排序。比如优先展示P0级别用例，在展示P1级别。测试时按照用例的优先级进行回归。

**Comment by xulinde** [comment]
高级搜索支持按等级筛选
![image](https://user-images.githubusercontent.com/64065190/116182407-d3585000-a74e-11eb-8b2a-4471948f616b.png)

**Comment by Walter-Shui** [comment]
我们这边想要的功能其实是按照用例的等级排序。按照P0,P1,P2,P3这样排序。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.9.2 已支持。
