### ISSUE TITLE
[BUG]接口自动化编辑页面，左侧编辑框拖动无效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23026]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

接口自动化编辑页面，左侧编辑框拖动无效

### 重现步骤

1、创建或者编辑接口自动化场景
2、拖动左侧的编辑框，拖动之后又会弹回去

### 附加信息

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/32027713/226785291-549f64c2-bbe1-42bc-aae1-a78eff3efdbd.png">

**Comment by 13290445582** [comment]
您好，感谢您的反馈，目前在接口自动化模块，创建或者编辑接口自动化场景，拖动左侧的编辑框，会自动回弹，后续版本会进行优化，目前设计为此。
