### ISSUE TITLE
[BUG]v1.20.20，翻译问题，App Management下面的的 Track/API/UITest/Perforamnce对应页面的 Report Sharing Link 右边出现字符重叠

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23027]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

v1.20.20，翻译问题，App Management下面的的 Track/API/UITest/Perforamnce对应页面的 Report Sharing Link 右边出现字符重叠

### 重现步骤

1. 切换到英文
2. 导航到Project Settings>App Management
3. 分别切换到  Track/API/UITest/Perforamnce对应页面
<img width="484" alt="1679452017458" src="https://user-images.githubusercontent.com/76033005/226786027-c734e132-cc4e-4299-8320-6f75a95f30cc.png">

**Comment by 13290445582** [comment]
您好，感谢您的反馈，您提交的问题已复现并提交到tapd平台，开发跟进
