### ISSUE TITLE
[BUG]【idea插件】点击页面上的Reset，当前页面内容并未清空。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23025]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

【idea插件】点击页面上的Reset，当前页面内容并未清空。

### 重现步骤

【idea插件】点击页面上的Reset，好像并无作用，当前页面内容并未清空。
![image](https://user-images.githubusercontent.com/104960608/226784495-f16c5ddd-6c0f-4eff-8eeb-df6953ba016c.png)

**Comment by zrfit** [comment]
您好，计划metersphere-idea-plugin-1.2.5会去掉该按钮，待发布后可升级验证。
