### ISSUE TITLE
[FEATURE]对测试用例参数化管理

### ISSUE THREAD

**Issue by jiawen94** [metersphere/metersphere#23030]
### MeterSphere 版本

v2.3.1-845ff07b

### 请描述你建议的实现方案

上述只是我的需求和想法，实现方案还是得由你们确定。

**Comment by luty2018** [comment]
了解， 我们有计划做自动生成测试用例的功能，应该可以覆盖你的部分需求。 这块会进一步调研，可以关注我们后续的版本发布计划！
