### ISSUE TITLE
[BUG]英文环境, Project Settings>File，列表页“作用范围”没有翻译，以及该字段对应的值“项目”，“工作空间” 需要翻译

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23033]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

英文环境, Project Settings>File，列表页“作用范围”没有翻译，以及该字段对应的值“项目”，“工作空间” 需要翻译

### 重现步骤

1. 切换到英文环境
2. 导航到Project Settings>File
<img width="810" alt="fdb2c36bb94ed0bd52dba24096f307c" src="https://user-images.githubusercontent.com/76033005/226787964-947a8694-5e4a-4feb-9040-6a47af74d565.png">
<img width="1151" alt="1679452859665" src="https://user-images.githubusercontent.com/76033005/226788025-c41e068b-b149-4567-a9e3-4bfd1ab17f56.png">

### 附加信息

客户的海外客户也要用MS，所以需要改掉未翻译的

**Comment by youliyuan-fit2cloud** [comment]
v1.20 版本存在，v2版本没有这个字段。
v1.20.21-lts中会修改～
