### ISSUE TITLE
[BUG]英语环境，Project Settings>Template，中文模板名称没有翻译

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23034]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

英语环境，Project Settings>Template，中文模板名称没有翻译

### 重现步骤

1.切换到英语环境
2. 导航到Project Settings> Template。
<img width="807" alt="df953fcf28baf0c60196836ced7b759" src="https://user-images.githubusercontent.com/76033005/226788582-89465abb-5747-4bb4-913f-d3059c357a4b.png">

**Comment by 13290445582** [comment]
感谢反馈，您提供的问题已复现并提供至tapd平台，开发跟进
