### ISSUE TITLE
[BUG]切换到英语环境，Config Environment页面 Environment Name显示换行了。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23031]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

切换到英语环境，Config Environment页面 Environment Name显示换行了。

### 重现步骤

1.切换到英语环境
2. 导航到Project Settings>Environment页面
3. 点击 Create Environment
<img width="840" alt="1679452136754" src="https://user-images.githubusercontent.com/76033005/226786949-f41edf5a-801c-4000-bab9-7afd279013fd.png">

**Comment by 13290445582** [comment]
感谢您的反馈，您提供的问题已复现并提交至tapd平台，开发跟进
