### ISSUE TITLE
[BUG] python ssl库调用在新版本报错

### ISSUE THREAD

**Issue by tygk** [metersphere/metersphere#23035]
### 联系方式

1026526269@qq.com

### MeterSphere 版本

v2.7.1-b3

### 使用外置数据库

是

### 问题描述

v2.7.1-b3版本上环境设置中，全局前置脚本，使用python代码
import httplib
import ssl
import json
ip=vars.get("server_ip")
port=vars.get("port")
params = '''{"account":"admin", "password":"admin"}'''
headers = {'Content-type':'application/json'}
conn = httplib.HTTPSConnection(ip,port,context=ssl._create_unverified_context())
conn.request("POST", "/app/login", params, headers)
res = conn.getresponse()
response = unicode(res.read(), 'utf-8')
log.info(response)
token=json.loads(response)["data"]["token"]
log.info(token)

接口调试的时候，报错'module' object has no attribute '_create_unverified_context'  in <script> at line number 8

同样的代码在v2.1.0-b1上测试没有问题

### 重现步骤

同上

**Comment by fit2-zhao** [comment]
感谢反馈，抱歉给您带来了不好的体验，_create_unverified_context 这个函数从jython 2.7.2之后的版本才支持，因从jython 2.7.1 之后的版本有严重性能问题，所以目前我们平台内置的还是2.7.0。

**Comment by tygk** [comment]
那这个bug就不做修复吗？我的所有接口都是要用https的，目前用py代码来实现接口前后置，都必须要使用_create_unverified_context，否则py代码就会报错。
除了换回到老版本的metersphere，还有其他办法吗？

**Comment by fit2-zhao** [comment]
如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的2.7.0，替换位置api-test 镜像中 /opt/jmeter/lib/ext/jython-standalone.jar；如果使用资源池需要再替换node 镜像中相同位置的jar。
下载地址：https://www.jython.org/

**Comment by tygk** [comment]
好的，感谢指导~

**Comment by quarrierZhang** [comment]
不行就GG
