### ISSUE TITLE
[BUG]场景名称含有$,批量执行报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23043]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

场景名称含有$,批量执行报错

### 重现步骤

1.创建场景，场景名称中含有$
![image](https://user-images.githubusercontent.com/103627487/226820788-25f8c1dc-608f-4c9d-9b46-b43e25115674.png)
2.列表页批量执行
![image](https://user-images.githubusercontent.com/103627487/226820871-eb155690-bf33-402d-bc58-af699cbdb2d2.png)
![image](https://user-images.githubusercontent.com/103627487/226821046-0791440b-23e0-41bb-891e-e4276602f8a4.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复～
