### ISSUE TITLE
[BUG] 功能用例-脑图模式下，添加多级临时节点，修改第一级临时节点为模块，保存后，该节点下数据丢失

### ISSUE THREAD

**Issue by wpiami** [metersphere/metersphere#23044]
### 联系方式

1462607050@qq.com

### MeterSphere 版本

V2.3

### 使用外置数据库

否

### 问题描述

功能用例-脑图模式下，添加多级临时节点，修改为第一级临时节点为模块，保存后，该节点下数据丢失

### 重现步骤

1. 功能用例-脑图模式下，新建多级临时节点，并保存；
2. 切换列表，再次进入脑图界面，显示正常；
3. 此时选择第一级临时节点，将其设置为模块，点击保存；
4. 再次切换到列表，重新进入脑图界面，设置为模块的节点，其子节点全部丢失；

### 期待的正确结果

设置第一级临时节点为模块，保存后，再次进入脑图界面，该节点下的数据正常展示，不丢失

### 附加信息

https://user-images.githubusercontent.com/19588624/226828370-9fe3865f-cee8-4024-93f2-522f36fe1f52.mov

**Comment by 13290445582** [comment]
感谢您的反馈，您提供的问题已复现并提交至tapd平台，开发跟进

**Comment by wpiami** [comment]
> 感谢您的反馈，您提供的问题已复现并提交至tapd平台，开发跟进

好的，这个问题如果有解决方案了，麻烦及时回复一下，感谢🙏

**Comment by 13290445582** [comment]
好的，一定及时通知您。

**Comment by wpiami** [comment]
> 好的，一定及时通知您。

**Comment by wpiami** [comment]
> 好的，一定及时通知您。

谢谢，麻烦了

**Comment by 13290445582** [comment]
v2.8.1 中已修改，请升级一下吧～
