### ISSUE TITLE
[BUG]接口修改后导入-覆盖模式，接口内容更新成功，但是列表更新时间不变

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#23041]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

接口修改后导入-覆盖模式，接口内容更新成功，但是列表更新时间不变

### 重现步骤

1、在现有的api上添加一个case
2、本地修改api 的请求体导入：此时查看api接口内容已经变了，列表更新时间不变

### 期待的正确结果

接口变化，列表更新时间改变，有录屏（是个压缩包文件太大改成后缀txt了，改成rar即可查看）

### 附加信息

![image](https://user-images.githubusercontent.com/43202800/226797367-a7f5f4ed-c3a5-4420-aee9-f08159f6e371.png)
[Uploading Rec 0002.txt…]()

**Comment by 13290445582** [comment]
感谢您的反馈，已复现问题并提交至tapd平台，开发跟进
