### ISSUE TITLE
[FEATURE]多条断言的情况下，有失败断言。并不是很好区分失败断言是哪一条

### ISSUE THREAD

**Issue by jiangrry** [metersphere/metersphere#2306]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/6359046/116171216-ee20c980-a73a-11eb-941d-99e4d4b56b03.png)
打印的日志中，断言这里不好找断言失败的信息

**请描述你建议的实现方案**
打印的日志中，断言规则这里添加一列，把断言名称也显示一下

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你指的是控制台中打印的日志吗？

**Comment by jiangrry** [comment]
感觉现在这个页面上留着的“断言名称”更像是断言方式，并不能很好的帮助定位失败断言







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]多条断言的情况下，有失败断言。并不是很好区分失败断言是哪一条 (#2306)





 
你好，请问你指的是控制台中打印的日志吗？
