### ISSUE TITLE
[BUG]接口测试>>接口测试用例：请求参数里，选择系统提供的Jmeter标准函数--随机数。执行后此函数不起作用。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23069]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口测试用例：请求参数里，选择系统提供的Jmeter标准函数--随机数。执行后此函数不起作用。

### 重现步骤

[BUG]接口测试>>接口测试用例：请求参数里，选择系统提供的Jmeter标准函数--随机数。执行后此函数不起作用。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/226914969-4e893dcd-b0c3-4be5-b329-307794b71db9.png)
![image](https://user-images.githubusercontent.com/78218624/226915229-0c178531-dbba-4cf4-b5d9-a9338cadcf7b.png)
![image](https://user-images.githubusercontent.com/78218624/226915988-dd945b24-0901-434f-a220-49b2f5ff2b7f.png)
![image](https://user-images.githubusercontent.com/78218624/226916174-c0e37aac-8b7e-493f-8c7c-df9f837a1a77.png)

**Comment by fit2-zhao** [comment]
感谢反馈，Random 函数是需要加上随机范围配合使用的，比如：${__Random(1,10)} ；具体您可以参照JMeter 函数提供的文档：https://jmeter.apache.org/usermanual/functions.html
