### ISSUE TITLE
[BUG]脑图切换到列表时，加载过程中会显示多余的页面

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#23067]
### 联系方式

张树彬

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

脑图切换到列表时，加载过程中会显示多余的页面

### 重现步骤

1. 测试跟踪-功能用例
2. 脑图和列表模式来回切换
3. 切换过程中偶现加载时间过长，会展示出列表页的操作按钮

### 期待的正确结果

希望切换用例格式时加载时间不要过长，提高系统性能，目前只维护了40条用例，就要加载几秒钟；另外在切换过程中不要展示多余的页面。

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/226900384-8a856998-bef6-4f62-adf8-1b025e83ad8a.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进

**Comment by 13290445582** [comment]
v2.9.0已修复
