### ISSUE TITLE
[BUG]UI测试报告截图加载失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#23068]
### 联系方式

张树彬

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

发现很多之前UI测试报告里可以正常显示的截图，最近查看都不能显示了，提示加载失败。

### 重现步骤

1. UI测试-报告，打开以前执行过有添加截图的场景（我这里显示3月12号之前报告里的截图都无法显示）
2. 查看该场景的步骤截图，提示加载失败

### 期待的正确结果

可以正常打开报告中的截图

### 附加信息

![1679488598117](https://user-images.githubusercontent.com/77324661/226908206-63cc241a-14da-4e27-8b0b-390c7a6ba1ad.jpg)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进

**Comment by 13290445582** [comment]
该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
