### ISSUE TITLE
[BUG] 断言,Not Contains类型的，在报告里体现的描述不准确。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23072]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

断言,NOT Contains类型的，在报告里体现的描述不准确。

### 重现步骤

1. 比如下面为Not Contains的断言
<img width="843" alt="faab8fb96904240bf74a317f70116f2" src="https://user-images.githubusercontent.com/76033005/227085480-86c97ac9-4b8b-48e8-8dc4-1b2044c0cfe7.png">

2. 断言执行结果描述：
<img width="569" alt="e669a89d8042fe5dba56023dc0a532b" src="https://user-images.githubusercontent.com/76033005/227085584-265c8291-4630-4aa9-b7e1-deb9ef84a791.png">

3. 断言执行没问题，只是文描没有体现出 Not Contains。

**Comment by youliyuan-fit2cloud** [comment]
已发布的v1.20.21 -lts中已修复。
即将发布的v2.8.1中修复。
