### ISSUE TITLE
[BUG]【环境配置】通用配置处配置含有英文大写变量名，HTTP配置处引用该变量进行保存时，发现会把变量名的大写变成小写

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23079]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

【环境配置】通用配置处配置英文大写变量名为TEST11，HTTP配置处引用该变量进行保存时，发现会把变量名的大写变成小写

### 重现步骤

【环境配置】通用配置处配置英文大写变量名为TEST11
![image](https://user-images.githubusercontent.com/104960608/227095972-d83cd195-b48a-4dcd-8d21-7590953a07b1.png)

HTTP配置处引用该变量进行保存时，发现会把变量名大写变成小写
![image](https://user-images.githubusercontent.com/104960608/227096381-5acd0be8-3ab3-4b11-92bc-c6b99645ff76.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进
