### ISSUE TITLE
[BUG]【环境配置】在通用环境处上传csv文件，环境处引用csv里的ip，接口定义处TEST处选择环境运行后，请求地址不对。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23078]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

【环境配置】在通用环境处上传csv文件，环境处引用csv里的ip，接口定义处TEST处选择环境运行后，请求地址不对。

### 重现步骤

【环境配置】在通用环境处上传csv文件，csv文件里写的是ip地址
![image](https://user-images.githubusercontent.com/104960608/227095246-aa0e362e-1f96-48b6-b3a4-797730a587ec.png)

![image](https://user-images.githubusercontent.com/104960608/227095087-935c07a4-756c-4861-a431-300ea858fe2b.png)

![image](https://user-images.githubusercontent.com/104960608/227095286-a89170be-6583-4f54-94c7-a6bc5fa56710.png)
接口定义处TEST处选择环境运行后，出现的地址会多[]
![image](https://user-images.githubusercontent.com/104960608/227095513-2dfa4257-957b-48c0-afcb-6bf797b8d234.png)

**Comment by 13290445582** [comment]
感谢反馈，目前我们使用的底层测试引擎JMeter对于变量当作url处理确实是这样，如果不加端口号“，测试是没问题的。
