### ISSUE TITLE
[BUG]UI测试，设置场景变量，实际步骤中只用场景变量取出来的值是缺少内容。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23088]
### 联系方式

kaijie.yu@fit2cloud.com

### MeterSphere 版本

v2.7.1

### 使用外置数据库

否

### 问题描述

1.UI测试，设置场景变量，实际步骤中只用场景变量取出来的值是缺少内容。

### 重现步骤

1.UI测试新建场景，增加场景变量   测试cmy_5@increment，
![image](https://user-images.githubusercontent.com/55130444/227112646-50f900e7-993f-49c2-8d18-7b033ac659ca.png)
2.增加输入操作，输入 内容 ${变量名}。
![image](https://user-images.githubusercontent.com/55130444/227113489-3f069bd3-7287-41c5-a6a3-cf9873189f11.png)
3.执行ui场景。变量名称没有完全引用过来。
![image](https://user-images.githubusercontent.com/55130444/227113563-ee36bad4-8c13-4865-a7db-a0d923898d4b.png)

### 期待的正确结果

1.能够把场景变量中的变量完全引用过来

**Comment by 13290445582** [comment]
您好，您提供的问题并未复现，您可以提供下相应报错信息嘛。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128017892/227135841-36162617-dc9d-4d7d-8593-feead6b575b7.png">

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
