### ISSUE TITLE
[FEATURE]功能用例-脑图模式，希望对模块，临时节点进行上移下移操作后，能保存节点的顺序

### ISSUE THREAD

**Issue by wpiami** [metersphere/metersphere#23093]
### MeterSphere 版本

V2.3

### 联系方式

1462607050@qq.com

### 请描述您的需求或者改进建议

希望在脑图中，对模块，临时节点进行上下移动操作后，可以保存成功，目前是不能正常保存的

### 附加信息

https://user-images.githubusercontent.com/19588624/227144280-c0950621-b0cd-4ccf-b5d2-166df0321aac.mov

https://user-images.githubusercontent.com/19588624/227144330-c8e43dfc-4f35-408d-b626-5f410563cdcc.mov

**Comment by luty2018** [comment]
移动模块是会保存顺序的。
目前移动临时模块不支持保存，因为脑图顺序其实是根据列表顺序生成的，所以还无法兼顾到临时节点，这个我们会在v3.0 进行优化。

**Comment by wpiami** [comment]
> 移动模块是会保存顺序的。 目前移动临时模块不支持保存，因为脑图顺序其实是根据列表顺序生成的，所以还无法兼顾到临时节点，这个我们会在v3.0 进行优化。

操作脑图移动模块，目前保存后不能保存模块的顺序，请问你说的会保存顺序是在脑图上操作吗？
