### ISSUE TITLE
[FEATURE]接口调试

### ISSUE THREAD

**Issue by DishuiH** [metersphere/metersphere#23109]
### MeterSphere 版本

V2.8.0

### 联系方式

59 群梦晴

### 请描述您的需求或者改进建议

1. 执行按钮太小了
![图片](https://user-images.githubusercontent.com/39475748/227411391-f21b8691-86f4-4bf5-8e4b-da07e816d572.png)
2.调试过程中经常需要看到变量的变化，环境配置这里能不能直接放到旁边而不是下拉才能点到
![图片](https://user-images.githubusercontent.com/39475748/227411595-fbf8e75b-bb20-49f8-9a42-7cf97f7b292d.png)
3. 响应要默认打开，调试关键就是看响应了还把响应默认合上
![图片](https://user-images.githubusercontent.com/39475748/227411899-02b68b38-2cbe-4060-a45a-9b9add814816.png)

### 请描述你建议的实现方案

1. 尽可能把重要控件拉大
2. 把环境配置放到一级界面
3. 接口响应默认打开
4. 在场景外提取的变量都应作为环境变量。在场景内提取的变量都应该作为场景变量，不管是单步调试还是整体调试都应该能使用

**Comment by luty2018** [comment]
好的， 感谢建议， 我们在3.0会对这块进行交互升级。

**Comment by DishuiH** [comment]
waiting...
