### ISSUE TITLE
[BUG]【接口自动化】请求里的断言选择jsonpath断言，条件为“大于”，将该场景导出JMX，将该JMX在JMeter里打开，发现断言变成"等于"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23117]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

【接口自动化】请求里的断言选择jsonpath断言，条件为“大于”，将该场景导出JMX，将该JMX在JMeter里打开，发现断言变成"等于"

### 重现步骤

1.【接口自动化】请求里的断言选择jsonpath断言，条件为“大于”。
![image](https://user-images.githubusercontent.com/104960608/227418956-913cf5a2-e51d-4c38-8d8a-524279ebc31c.png)

2.将该场景导出JMX
![image](https://user-images.githubusercontent.com/104960608/227419195-c150aae0-90ab-421e-8790-9d7fda923591.png)

3.将该JMX在JMeter里打开，发现断言变成"等于"
![image](https://user-images.githubusercontent.com/104960608/227419309-fed1f062-8b75-4d83-8082-d546a8cd6d7c.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进
