### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by yangxiea** [metersphere/metersphere#23118]
### 请描述您的问题

每天第一次进登录页就会出现
<img width="609" alt="企业微信截图_16796285851790" src="https://user-images.githubusercontent.com/125354412/227420027-440ca0b6-200b-45fb-9736-a7a2531dede8.png">

**Comment by luty2018** [comment]
你在交流群吗， 可以添加 “申凯波 ”我们帮你远程看一下。
