### ISSUE TITLE
[BUG] 自定义字段值在数据库中的值存储有双引号，不应该带双引存储

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23121]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

自定义字段值在数据库中的值存为有双引号，不应该带双引存储

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/227436923-d7e295e4-6a27-4060-aba0-4435fde7d415.png)

**Comment by lingllgh** [comment]
2.71应该就有这个问题, 导致用例列表中直接显示了自定义字段的原始值而不是对应文本

**Comment by AgAngle** [comment]
你好，这里存的是 JSON 序列化之后的文本，因为自定义字段类型众多，所以统一 JSON  序列化后存储，使用时反序列化即可
