### ISSUE TITLE
[BUG]UI测试，指令里的入参是变量，把指令引入到ui自动化脚本里，执行后此变量的引用无法得到正确的值，显示${}

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23133]
### MeterSphere 版本

V2.7.1 和2.8

### 使用外置数据库

否

### 问题描述

[BUG]UI测试，指令里的入参是变量，把指令引入到ui自动化脚本里，执行后此变量的引用无法得到正确的值，显示${}

### 重现步骤

[BUG]UI测试，指令里的入参是变量，把指令引入到ui自动化脚本里，执行后此变量的引用无法得到正确的值，显示${}

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/227467829-fdae267c-a114-42f9-bd5a-bb0dfad01eb4.png)
![image](https://user-images.githubusercontent.com/78218624/227468234-72b58694-408f-4d80-b11a-4889759f9d67.png)
![image](https://user-images.githubusercontent.com/78218624/227468422-05a9189d-173d-4910-ab6f-722817474812.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0中已修复。
