### ISSUE TITLE
[BUG] 在windos idea中能跑起来的V1.19源码如何部署到centos linux环境中

### ISSUE THREAD

**Issue by algmir** [metersphere/metersphere#23143]
### 联系方式

MeterSphere 交流群58  闻风  hanlei32@faw.com.cn

### MeterSphere 版本

V1.19

### 使用外置数据库

否

### 问题描述

win打jar包失败了，然后 改了pom.xml中的 run win-build ，前端npm就打出来了，现在V1.19有个前端jar包，后端jar包，对源码进行部署 如何部署，比如说 通过 docker-compose或docker部署，有什么教程，方法步骤，求助。

### 重现步骤

V1.19源码，idea运行，win黑框 打包部署，maven clean package 然后打出来2个jar包，分别是前端后端jar包，如何部署

**Comment by liuruibin** [comment]
您好，v2.2.x及之前版本中执行 mvn clean package 后会产生一个allinone的jar，我们做镜像时会把这个jar解压运行。具体情况请查看Jenkinsfile的构建过程

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
