### ISSUE TITLE
[BUG]场景中请求很多时，查看报告时浏览器崩溃

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23144]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

场景中请求很多时，场景中有一循环控制器，次数循环，循环次数设置8000，执行结束，查看报告时，点击循环控制器下的步骤，浏览器崩溃。

### 重现步骤

1.创建场景，场景中添加循环控制器，循环控制器下设置请求8000
![image](https://user-images.githubusercontent.com/103627487/227542593-3b715ea9-9106-47d9-84bd-b4b7901804f3.png)
2.执行结束后查看报告，点击循环控制器下面的请求，浏览器崩溃
![image](https://user-images.githubusercontent.com/103627487/227542967-589f7927-1a20-4b8a-81a2-1eb70ef7e986.png)
![image](https://user-images.githubusercontent.com/103627487/227543521-8ba13c5b-dcbf-47c7-93e3-e802dc93e654.png)

**Comment by meijieDouDou** [comment]
浏览器崩溃这个问题，执行场景时，请求很多时，也会偶发浏览器崩溃，麻烦看下是否可以同步优化

**Comment by youliyuan-fit2cloud** [comment]
> 浏览器崩溃这个问题，执行场景时，请求很多时，也会偶发浏览器崩溃，麻烦看下是否可以同步优化

应该是同一个问题，后续版本会尽力优化。
