### ISSUE TITLE
[BUG]环境地址配置的 url 带 /xx 后缀时，替换 原 ui 步骤里的 url 地址有误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#23142]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

环境地址配置的 url 带 /xx 后缀时，替换 原 ui 步骤里的 url 地址有误

### 重现步骤

1.环境地址配置如下
![f1a146d5788288aa5939d3c6e0697bf](https://user-images.githubusercontent.com/30038088/227513492-6922814e-b341-4ac0-b5fd-893069193cfe.png)
2.原 ui 场景 url 步骤配置如下
![a4142bf243659556d5b755c4117a9fc](https://user-images.githubusercontent.com/30038088/227513580-56e5f5f9-2ca1-4e74-b23d-afd1332791c0.png)
3.选择环境执行，替换后的 Url 如下
![da2fd8079a2a67a0f9f9407788322f8](https://user-images.githubusercontent.com/30038088/227513736-bf71c02c-7875-4356-9adb-5710da3d5eea.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！
环境配置中配置的是环境域名，场景选择环境后替换的是url的域名，从您的截图来看，场景url替换的环境域名是成功的，然后拼接上了场景url的路径，目前功能逻辑是这样的。
<img width="713" alt="image" src="https://user-images.githubusercontent.com/99731894/227826870-ef2595d3-ca4d-4347-be8d-865061d0753d.png">

**Comment by shenkaibo** [comment]
实际业务中，好多 微服务的 url 都是 域名+/+微服务前缀,比如 www.ms.com/api/ ；这样替换后 就会变成 www.ms.com/api/api
