### ISSUE TITLE
[BUG]【文件管理】音频文件PCM格式上传后，在后台服务器存储是个文件夹，在beanshell 无法获取该音频文件

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23140]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

【文件管理】音频文件PCM格式上传后，在后台服务器存储是个文件夹，在beanshell 直接写路径获取该音频文件，会提示是个文件夹，无法获取这个音频文件。

### 重现步骤

1.【文件管理】音频文件PCM格式上传后，在后台服务器存储是个文件夹
![image](https://user-images.githubusercontent.com/104960608/227505113-6770d7cd-72bd-4f1a-a9df-108e237671ad.png)

![image](https://user-images.githubusercontent.com/104960608/227505439-ffda90b8-853e-4753-af3a-29f526ae39a2.png)
2. 在beanshell 直接写路径获取该音频文件，会提示是个文件夹，无法获取这个音频文件。
3. 音频文件如下
[8k_10s.zip](https://github.com/metersphere/metersphere/files/11061381/8k_10s.zip)

**Comment by song-tianyang** [comment]
文件管理上传的文件是由minio负责存储的，并不是直接存储在服务器硬盘上的。
如果要在beanshell里获取服务器硬盘上的文件，不如直接将文件手动上传到服务器上
