### ISSUE TITLE
[BUG] 功能用例详情页面，回显devops需求失败，为空白框

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23156]
### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

 功能用例详情页面，回显devops需求失败，为空白框

### 重现步骤

 功能用例详情页面，回显devops需求失败，为空白框：
1、选择任一devops需求
![image](https://user-images.githubusercontent.com/103925124/227833364-98a557e7-08a8-4c4e-85ff-2637b88a5f48.png)
2、保存后并刷新，需求回显失败
![image](https://user-images.githubusercontent.com/103925124/227833259-91145e30-ed46-42a8-be45-36c28ce10b90.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #21508
