### ISSUE TITLE
[BUG]UI测试if流程控制中步骤未执行

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#23166]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

问题一：
1.在if流程的上一个步骤中添加JS后置脚本。在页面显示上一个步骤执行成功，但后台有脚本报错的情况下，下个条件判断步骤未执行；
问题二：
2.基于问题一，在if流程的步骤中即使设置了忽略异常继续执行，上个步骤存在后台脚本报错时，当前条件判断的步骤仍不会执行

### 重现步骤

叫问题描述(已与雨绮对接确认)

### 附加信息

![3bd8668fa853cc9ef63a9e8b6fb5a07](https://user-images.githubusercontent.com/92150453/227849503-474e0e01-6538-47f5-80be-6d0bfe6e6eb6.png)
![3328a9876afd584c00572068b7017da](https://user-images.githubusercontent.com/92150453/227849523-60f10cb0-f5ab-45f5-b28d-36c568c06ab5.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.8.1修复。

**Comment by liuruibin** [comment]
您好，脚本中自行执行alert后需要自己执行关闭操作，否则selenium无法定位到alert下面的元素并进行操作
