### ISSUE TITLE
[BUG] 在脑图模式下复制已有用例时，编辑、保存后，刷新会发现已有用例被修改，并没有添加新的用例

### ISSUE THREAD

**Issue by Hitoria** [metersphere/metersphere#2316]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2-b4

**Bug 描述**
在 用例列表 的 脑图模式 下编写用例时
如果通过复制粘贴进行编辑，保存后，刷新会发现，实际上 被复制的用例 被覆盖了，相当于在原有用例上进行了修改

**Bug 重现步骤**
1.  在模块下新建一条用例，填写前置条件、步骤和预期结果等，保存（如图1）
2. 在脑图模式下，复制这个用例，粘贴（如图2）
3. 编辑新用例的标题和内容，并点击右上角保存（如图2）
4. 刷新页面，发现原用例被覆盖（如图3）

**期待的正确结果**
复制粘贴、编辑新的用例并保存后，应当生成新的用例，而不是覆盖被复制的用例

【原因分析和猜测】
脑图模式的复制操作可能复制了用例ID，由于系统是以ID作为主键区分用例的，所以新用例提交时，ID与被复制的用例一致，会导致 被复制的用例 被修改，而不会生成新的用例

**截图**
![image](https://user-images.githubusercontent.com/39207507/116182393-cc314200-a74e-11eb-9aae-14546038ff3f.png)
![image](https://user-images.githubusercontent.com/39207507/116182553-0ef31a00-a74f-11eb-8ec7-91ca5d38b411.png)
![image](https://user-images.githubusercontent.com/39207507/116182687-4661c680-a74f-11eb-9844-a6d350c0b615.png)

**Comment by zyyfit** [comment]
感谢反馈，您是通过ctrl+c、ctrl+v 的方式复制的吗？我们会考虑优化这个问题的

**Comment by Hitoria** [comment]
> 感谢反馈，您是通过ctrl+c、ctrl+v 的方式复制的吗？我们会考虑优化这个问题的
是的，通过ctrl+c复制用例标题，然后点到它的父节点，按下ctrl+v。通过这样的操作复制的。

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用

**Comment by Hitoria** [comment]
> 1.10.2版本已修复，请升级使用

收到，我稍晚些升级试一下
辛苦啦~
