### ISSUE TITLE
[BUG]场景用例数过多时保存报错

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#23167]
### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

场景编辑后保存报错

### 重现步骤

场景用例550+，保存时报错
![image](https://user-images.githubusercontent.com/3060035/227852275-0eced76a-12e0-47ef-93c7-d6c44ec77558.png)
查看服务状态时api-test会重启

保存场景用例数不多时正常

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #22716 
 
请参考上诉issue 修改服务器的api-test容器配置，感谢理解和支持～
