### ISSUE TITLE
[BUG]【接口自动化】-场景导出Metersphere格式-引用case的后置脚本内容与实际不符合

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23177]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

1.20.20lts版本里有个场景A,场景A中引用CASE B,该case B后置操作中有一个后置sql和后置脚本，将场景A导出为metersphere格式，将文件导入到2.8.0版本中，发现场景中的case 后置脚本内容变了，与实际内容不符

### 重现步骤

1.case B中增加后置sql和后置脚本
2.创建一个场景，命名为场景A
3.在场景A中引用case B,保存
4.将场景A导出为metersphere文件
5.将导出的文件导入到2.8.0版本中
6.检查导入的场景case脚本

### 期待的正确结果

1.导出场景的case后置脚本与实际导出要一致

### 附加信息

重现步骤，动态图片
![0390b036-8bb0-4ace-bac0-5954cefe6d0e](https://user-images.githubusercontent.com/45531073/227878349-f627cf45-8b24-463b-8252-f6bf4313d603.gif)

**Comment by liushuneng** [comment]
![0390b036-8bb0-4ace-bac0-5954cefe6d0e](https://user-images.githubusercontent.com/45531073/227885847-59e031b0-562b-4249-af89-d58d5dba0797.gif)

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v1.20.21导出文件到2.8未复现该问题，待v1.20.21发布后可升级验证。
