### ISSUE TITLE
[BUG] 自定义字段文本框输入{}会自动变为[object Object]

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23178]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

自定义字段文本框输入{}会自动变为[object Object]

### 重现步骤

自定义字段文本框输入{}会自动变为[object Object]
![image](https://user-images.githubusercontent.com/103925124/227883525-d8b2e67a-4bbe-4707-be2d-75601ece789c.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.8.1修复。

**Comment by Ycr123888** [comment]
v2.8.1没有修复哈@zrfit

**Comment by zrfit** [comment]
经过沟通，v2.9已不存在该问题，待发布后可升级验证。
