### ISSUE TITLE
[BUG]失败重跑成功后没有更新报告记录

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#23171]
### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

测试计划执行的测试报告中，对失败的接口自动化场景进行失败重跑，成功后，测试报告没有更新对应的结果，失败记录没有变成成功，成功率也没有更新成100%，在任务中心查看重跑的任务实际已经成功执行并通过。

### 重现步骤

进入测试报告，选择任意失败的接口自动化测试用例，点击失败重跑。

### 期待的正确结果

重跑成功后应自动更新测试报告。

**Comment by song-tianyang** [comment]
感谢您的反馈！ 这个问题预计在2.8.1版本修复

能冒昧的问一下您的联系方式吗？ 关于之前您提到的测试计划执行相关问题，我们想要进一步跟进您那边目前的状况

**Comment by wszbc** [comment]
> 感谢您的反馈！ 这个问题预计在2.8.1版本修复
> 
> 能冒昧的问一下您的联系方式吗？ 关于之前您提到的测试计划执行相关问题，我们想了解一下更多信息

qq 335347678
