### ISSUE TITLE
[BUG]英文版本操作和信息错行

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#2318]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？V1.8

**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/78218624/116189762-048b4d00-a75c-11eb-8f21-ec2e4c7ccf4e.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xyziven** [comment]
中文下正常，该问题切换到英文下、并且需要左右滚动时才会出现

![image](https://user-images.githubusercontent.com/24548477/116373694-2e1da480-a840-11eb-9321-2ff85668cfbb.png)

**Comment by xulinde** [comment]
1.9.0已修复
