### ISSUE TITLE
[BUG] 自定义模板，添加多个字段，字段在浏览器默认比例尺下，未展示全，且无滚动条

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23181]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

自定义模板，添加多个字段，字段在浏览器默认比例尺下，未展示全，且无滚动条

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/227885121-6a2d75f6-ee74-4071-b5e7-d7aeb1d6c003.png)
在百分之90的比例尺下，能test2字段能展示出来，在100比例尺下，test2字段展示不出来，且无滚动条
![image](https://user-images.githubusercontent.com/103925124/227887442-21242430-8756-410f-9315-d91d479d232e.png)

**Comment by 13290445582** [comment]
您提供的问题并未复现，请问可以提供录屏文件或者详细信息嘛？
