### ISSUE TITLE
[BUG]   自定义字段在功能用例详情页面展示顺序错乱

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23182]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

自定义字段在功能用例详情页面展示顺序错乱

### 重现步骤

某模板导入自定义字段后
![image](https://user-images.githubusercontent.com/103925124/227888457-8d6aa9e3-398b-4142-9648-95a2c59f33a1.png)
在用例详情展示错乱，无规律，也未和模板字段顺序保持一致
![image](https://user-images.githubusercontent.com/103925124/227888624-13830742-9a50-424a-9175-334cbb85db6c.png)

**Comment by 13290445582** [comment]
您好，您提供的问题并未复现，请问可以提供录屏文件或者详细信息嘛？
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128017892/227921088-7acca984-af12-42ce-9731-6d570709e295.png">
