### ISSUE TITLE
[BUG] 功能用例-脑图模式，Ctrl C Ctrl V复制粘贴xmind文件中的节点，保存不成功

### ISSUE THREAD

**Issue by wpiami** [metersphere/metersphere#23197]
### 联系方式

1462607050@qq.com

### MeterSphere 版本

V2.3

### 使用外置数据库

否

### 问题描述

功能用例-脑图模式，Ctrl C Ctrl V复制粘贴xmind文件中的节点，未做修改，保存不成功

### 重现步骤

https://user-images.githubusercontent.com/19588624/227918817-63691c5d-3f3b-412f-9429-6703b34ed317.mov

### 期待的正确结果

Ctrl C复制、Ctrl V粘贴节点之后，能正常保存，显示脑图数据

**Comment by 13290445582** [comment]
感谢反馈，您提供的问题并未复现，请问可以提供其他帮助复现信息嘛？

https://user-images.githubusercontent.com/128017892/228121214-42e1b775-c61a-4db5-85a8-b84a4fc57667.mov

**Comment by wpiami** [comment]
> 



> 感谢反馈，您提供的问题并未复现，请问可以提供其他帮助复现信息嘛？

你好，你发的视频中看着系统比较新，我是在官网https://cloud.metersphere.com/#/track/case/all操作的，从文件中复制节点，粘贴到脑图中，未做任何修改保存后保存不上。
我本地2.3版本也是这个现象，是不是最新版本已经做过处理了，如果做过修复能不能提供一下修复的git记录

**Comment by 13290445582** [comment]
您好，我们最新版本没有该漏洞，您可以升级到最新版使用

**Comment by wpiami** [comment]
> 您好，我们最新版本没有该漏洞，您可以升级到最新版使用

你好，2.3版本和官网系统都存在该问题，很影响使用，能提供修复记录吗？

**Comment by AgAngle** [comment]
你好，该问题已经修复，提交记录可以查看下面链接：
https://github.com/metersphere/metersphere/commit/8926118ecf49b1b345738d0a0288a3a2730be071

**Comment by wpiami** [comment]
>

> 你好，该问题已经修复，提交记录可以查看下面链接： [8926118](https://github.com/metersphere/metersphere/commit/8926118ecf49b1b345738d0a0288a3a2730be071)

你好，这个提交记录修复的是手动新建的临时节点，保存成功后查询到数据，但是未展示的问题。
我现在提的这个问题是，复制粘贴的临时节点点击保存并没存上，保存接口并没有临时节点的参数，和你发的记录不是同一个问题

**Comment by AgAngle** [comment]
> > 
> 
> > 你好，该问题已经修复，提交记录可以查看下面链接： [8926118](https://github.com/metersphere/metersphere/commit/8926118ecf49b1b345738d0a0288a3a2730be071)
> 
> 你好，这个提交记录修复的是手动新建的临时节点，保存成功后查询到数据，但是未展示的问题。 我现在提的这个问题是，复制粘贴的临时节点点击保存并没存上，保存接口并没有临时节点的参数，和你发的记录不是同一个问题,下图是保存时的传参 ![20230328-144619](https://user-images.githubusercontent.com/19588624/228151296-f3e675ff-4c18-4511-98ca-5c33a852c6a8.jpeg)

你好，你是二开需要修复问题是吧，我看了下 cloud 环境的版本，我们最新的 v1.20 分支的代码没有复现，应该是已经修复了，你可以分支切到 v1.20 ，该分支相比 cloud 环境一共有下面几个提交，你查看下脑图相关的提交
![image](https://user-images.githubusercontent.com/41557596/228155127-ba361e7e-e156-4792-8f56-65e9d5888071.png)
