### ISSUE TITLE
[BUG]【接口定义】设置Mock请求返回为 xml 格式数据，进行xpath后置提取数据，没有提取到

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23198]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

【接口定义】设置Mock请求返回为 xml 格式数据，进行xpath后置提取数据，没有提取到

### 重现步骤

1.【接口定义】设置Mock请求返回为 xml 格式数据
![image](https://user-images.githubusercontent.com/104960608/227919348-3bbf7402-24ef-4148-ad02-e6506bde1379.png)

2. 发送mock请求，进行xpath后置提取passwd的数据，发现没有提取到
![image](https://user-images.githubusercontent.com/104960608/227919651-ce96c1fe-2045-4e17-b895-118faeb39c23.png)

![image](https://user-images.githubusercontent.com/104960608/227919709-d94b2873-bb0b-4e10-a533-693f793cad34.png)

3.xml格式里的数据如下:
<iq type="result" id="register0" to="tcl.com/d69ea5b5">
    <bundling  xmlns="jabber:iq:guide">
        <sendtime>2023-03-27 17:43:24</sendtime>
        <password>c4815db6873d97ad41fd7307e9beef03bb8848d5</password>
        <userid>12333255</userid>
        <errorcode>0</errorcode>
    </bundling>
</iq>

**Comment by youliyuan-fit2cloud** [comment]
你好，这种xml格式中包括xmlns还不支持，jmeter中也需要插件才行。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/228457892-b1270dd0-782a-4ffd-9ecb-8d5a4008e551.png)

又研究了一下，可以参考上图的表达式提取。

**Comment by youliyuan-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/228457892-b1270dd0-782a-4ffd-9ecb-8d5a4008e551.png)
> 
> 又研究了一下，可以参考上图的表达式提取。
这个表达式也可以：/iq/bundling/password/text()
