### ISSUE TITLE
[FEATURE]用例导入支持freemind的mm格式

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#232]
**请描述您的需求或者改进建议.**
很多时候是使用思维导图进行用例编写的，有利于理清思路，各类思维导图软件基本都支持freemind的mm格式，建议支持该种格式的导入

**请描述你建议的实现方案**
freemind的mm格式文件结构是类似xml格式，可以解析出其中每个节点的内容，建议规则如下：
最下层一个节点为预期执行结果，倒数第二层节点为步骤描述，倒数第三层节点为前置条件，倒数第四层节点为用例名称，再往上的节点为所属模块层级（可能是多层），用例类型、优先级、测试方式为默认值，维护人为当前用户

**Comment by wangzhen-fit2cloud** [comment]
你好，在最新发布的 1.3 版本中支持了 xmind 类型的思维导图格式
