### ISSUE TITLE
[BUG]循环控制器情况下，token续命机制无法实现

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#23206]
### 联系方式

22973108171@qq.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

是

### 问题描述

每次请求后token会变，需要将请求后的token传到下一次请求。在使用循环控制器的情况下，无法实现第一次循环后的token传给下一次循环：
![图片](https://user-images.githubusercontent.com/23067502/227963878-e13668dd-fe02-4577-abf9-0262a01d8530.png)

### 重现步骤

前提条件：每请求一次下单接口之后token会变:
1.登录将token进行后置提取；
2.循环控制器设置次数循环为3，循环下单接口。

实际结果：
第一次请求成功；
第二次报token失效。

预期结果：
将第一次请求后提取的token传给第二次请求。

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.8未复现您的问题，建议升级尝试，如方便可将场景导出我们尝试复现。
