### ISSUE TITLE
[BUG][性能测试]测试场景配置页面，当前场景引用的jmx文件，在已上传的文件列表中不显示

### ISSUE THREAD

**Issue by yangfan112** [metersphere/metersphere#23209]
### MeterSphere 版本

 v2.7.1-9947cfcf

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/48746721/228110082-2c2f94ed-421c-4f39-b678-5094dfaed16e.png)

### 重现步骤

1、编辑已创建的测试场景
2、点击加载jmx文件
![image](https://user-images.githubusercontent.com/48746721/228110394-00829d4f-761e-4f5f-9624-bb0403c65402.png)

### 期待的正确结果

1、显示当前测试场景中已引用的jmx文件，可以正常更新jmx文件。

**Comment by 13290445582** [comment]
感谢反馈，更新jmx文件是需要将场景内加载的jmx文件删除，保存成功后，再次加载新的jmx文件即可更新成功。

**Comment by yangfan112** [comment]
jmx文件删除后，测试场景无法保存
![image](https://user-images.githubusercontent.com/48746721/228146142-75b6d742-42d1-42f0-b19b-fa01163592ba.png)
![image](https://user-images.githubusercontent.com/48746721/228146323-54c78ee7-aef4-48ca-bb43-352c7f6f623a.png)

**Comment by 13290445582** [comment]
问题已提交。
