### ISSUE TITLE
[FEATURE]JSON文件结构校验需要保留导入的JSON文件

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#23208]
### MeterSphere 版本

v2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

JSON文件结构校验保留导入的JSON文件，现在的情况是关闭测试用例后，原先导入的位置变成了空白了。
原因：有些接口需要反复多次修改导入的JSON文件，且一段时间后发现返回的结果与原先的结果不符，需要用工具做下对比，如果保留文件，可以很大的提高效率。希望在日后的3.0版本可以讨论下这个需求。

**Comment by Hyyfit** [comment]
感谢建议， 我们会在v3.0版本支持这个功能

**Comment by YellCatt** [comment]
> 感谢建议， 我们会在v3.0版本支持这个功能

谢谢
