### ISSUE TITLE
[BUG] 自定义字段在高级搜索中，非稳定出现

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23217]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

自定义字段在高级搜索中，非稳定出现

### 重现步骤

在模板里添加了下列自定义字段：
![image](https://user-images.githubusercontent.com/103925124/228145642-9964fb75-a666-477a-8837-7a6ba147a1a0.png)
在用例的高级检索中**_多点必现自定义字段未出现，不可选择问题_**
![image](https://user-images.githubusercontent.com/103925124/228146490-5a05cb88-1e4e-4748-a927-28a5e04074e8.png)

**Comment by 13290445582** [comment]
https://user-images.githubusercontent.com/128017892/228166469-4823660e-eda6-4c2e-b928-1e300bbdfd69.mov

您好，是有特定点击顺序或操作会必现吗？经过多次尝试并未复现该问题

**Comment by Ycr123888** [comment]
多进几次用例评审的高级搜索，没有啥特定顺序，就是一直访问高级搜索的检索条件

**Comment by 13290445582** [comment]
感谢反馈，问题已提交，开发跟进

**Comment by 13290445582** [comment]
该问题在v2.8.1已修复，升级一下吧～

**Comment by meijieDouDou** [comment]
用例评审-关联用例的高级搜索，还是存在自定义字段在高级搜索中，非稳定出现问题
![image](https://user-images.githubusercontent.com/103627487/231146083-f66f7019-5a6f-49d3-88fd-03906fc1d3c4.png)
![image](https://user-images.githubusercontent.com/103627487/231146739-11bc20ff-d785-4eaa-847c-3f4a50bb2d5e.png)

**Comment by 13290445582** [comment]
感谢反馈，计划v2.9.0修复
