### ISSUE TITLE
[BUG] 筛选多选下拉列表的值，报SQL异常

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23218]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

筛选多选下拉列表的值，报SQL异常

### 重现步骤

在模板里添加了一个多选下拉列表
![image](https://user-images.githubusercontent.com/103925124/228145642-9964fb75-a666-477a-8837-7a6ba147a1a0.png)
在用例li里设置值
![image](https://user-images.githubusercontent.com/103925124/228146168-321b1137-b61c-46b0-94cf-d6a91168fdf1.png)
进行筛选,下图在测试计划关联功能用例的高级搜索
![image](https://user-images.githubusercontent.com/103925124/228147011-6f39557b-c4ba-4fc4-9e86-610b656a2769.png)
后台日志：
![image](https://user-images.githubusercontent.com/103925124/228146878-b4c56582-8765-43c8-a5b2-f7022d95d85e.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交tapd，开发跟进
