### ISSUE TITLE
[BUG]部署多个api节点，页面上执行自动化测试一直处于pending状态，刷新发现已经处理完成

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#23211]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

是

### 问题描述

1、部署两个api服务节点
2、手动执行自动化测试，发现全部处于pending状态
3、刷新发现已经执行完成
![image](https://user-images.githubusercontent.com/58592452/228115738-47ff79ff-8875-407a-a901-f93af38db3fb.png)
![image](https://user-images.githubusercontent.com/58592452/228116141-31b503b7-e6c9-4447-8a03-7fd92bf9d503.png)
应该是没有回调的问题

### 重现步骤

1、部署两个api服务节点
2、手动执行自动化测试，发现全部处于pending状态
3、刷新发现已经执行完成

**Comment by fit2-zhao** [comment]
您的部署方案是什么样的具体讲一下，比如是使用的 k8s 部署还是docker compose 方式 网络是否都已经打通，redis kafka 等公共组件是否使用的是同一个。

**Comment by juanmaocxy** [comment]
> 您的部署方案是什么样的具体讲一下，比如是使用的 k8s 部署还是docker compose 方式 网络是否都已经打通，redis kafka 等公共组件是否使用的是同一个。

通过源码构建，使用docker compose进行构建，所有节点用的是同一份配置，单节点的时候没有问题

**Comment by fit2-zhao** [comment]
是二开打包的吗，建议用我们的安装包试试。
