### ISSUE TITLE
[BUG]ForEach 控制器 无法解析 对象数组

### ISSUE THREAD

**Issue by 18602738007** [metersphere/metersphere#23219]
### 联系方式

87513277@qq.com

### MeterSphere 版本

v2.7.1-b1

### 使用外置数据库

否

### 问题描述

ForEach 控制器 无法解析 对象数组 如json提取如下：，
dataResult：[{"id":57723,"creator":"13871249316","creatorId":15883,"updator":null,"version":null},{"id":57724,"creator":"13971249316","creatorId":15883,"updator":null,"version":null}.............]

只能解析基本类型 列如:
shopIds：["45","43"]
state：["1","1"]
liveId：["57723","57694"]

### 重现步骤

无。。。。。。。。。。。。

### 期待的正确结果

期望支持解析对象数组

### 附加信息

"嗨皮大叔：
可以执行 ，是我的问题，但是对象数组 解析不了@李攀 "
------
@嗨皮大叔 这个问题可以在github上提个issue反馈一下 https://github.com/metersphere/metersphere/issues/new/choose

**Comment by zrfit** [comment]
您好，感谢您的反馈！目前暂不支持foreach循环遍历对象数组。
