### ISSUE TITLE
[BUG]功能用例，自定模板字段是文本框时，创建功能用例输入自定义字段，再次查看不显示

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23221]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8

### 使用外置数据库

否

### 问题描述

功能用例，自定模板字段是文本框时，创建功能用例输入自定义字段，再次查看不显示

### 重现步骤

1.创建用例模板，自定义字段类型选择文本框
![image](https://user-images.githubusercontent.com/103627487/228148673-2413e932-3fb2-4a18-b93b-999bb0d65fc1.png)
2.创建功能用例，点击保存,保存后已经不显示自定义字段
![image](https://user-images.githubusercontent.com/103627487/228148953-f20068e5-bb43-414f-ad15-cccae8bcbc44.png)
![image](https://user-images.githubusercontent.com/103627487/228149032-bde16d61-23f0-4508-934c-102d23ee5115.png)
3.列表出显示，查看进去也不显示
![image](https://user-images.githubusercontent.com/103627487/228149314-afcd58f8-db86-411b-8fac-9f9ded09fb2e.png)
![image](https://user-images.githubusercontent.com/103627487/228149438-4b6b3211-789d-439b-8fb0-fd8dd24955b8.png)

**Comment by 13290445582** [comment]
该问题在后续版本有优化，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
