### ISSUE TITLE
[BUG] 点击评审详情，出现很长时间一直加载中，评审内容非过多，只有十条

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23223]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

 点击评审详情，出现很长时间一直加载中，评审内容非过多，只有十条

### 重现步骤

点击评审详情，出现很长时间一直加载中，评审内容非过多，只有十条，正常谷歌页面，无痕窗口会快一些
![image](https://user-images.githubusercontent.com/103925124/228157651-c0dba100-71f2-4b74-88fc-48eefdadf881.png)

如果复现不了的，提供环境复现

**Comment by 13290445582** [comment]
感谢反馈，问题并未复现，您可以查到是哪里慢了吗？提供一些相关信息
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128017892/228183327-7be07d52-a505-498e-8189-3ac5e0df04bf.png">

**Comment by Ycr123888** [comment]
服务器内存问题
