### ISSUE TITLE
[FEATURE] 测试跟踪，提缺陷时，支持图片上传，且图片能同步到 Jira 等平台（提单时，图片很重要，目前不支持图片上传和同步）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2323]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/11580681/116194400-60a59f80-a763-11eb-9a70-abf3abacd96e.png)

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by xulinde** [comment]
v1.11已支持
