### ISSUE TITLE
[BUG]测试跟踪功能用例列表页，每行的样式没有对齐见图，另外进入到用例详情页面，用例名称前置条件备注文本框内的信息也没对齐

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#23238]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

测试跟踪功能用例列表页，每行的样式没有对齐见图
<img width="857" alt="1679996691142" src="https://user-images.githubusercontent.com/83771182/228196717-e2c242b9-8a4c-4a0d-a49e-353ff8258456.png">

另外进入到用例详情页面，用例名称、前置条件、备注文本框内的信息也没对齐。缩进不一致。
<img width="697" alt="1679996738911" src="https://user-images.githubusercontent.com/83771182/228197385-449bfbc7-ec9d-4e5a-9558-49ca6019c400.png">

### 重现步骤

测试跟踪功能用例列表页，每行的样式没有对齐见图。另外进入到用例详情页面，用例名称、前置条件、备注文本框内的信息也没对齐。缩进不一致。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进

**Comment by 13290445582** [comment]
v2.8.1中已修改，请升级一下吧～
