### ISSUE TITLE
[BUG]在请求体里粘贴请求报文的长度较长时，显示不完整，没有显示参数最后的分号。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#23249]
### 联系方式

张树彬

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

在请求体里粘贴请求报文的长度较长时，显示不完整，没有显示参数最后的分号。

### 重现步骤

1. 复制请求体（请联系我要参数文件）
2. 粘贴到MS接口请求体中，最后的分号未显示
3. 再将该请求体从MS中复制到文本文档，是有分号的

### 期待的正确结果

完整显示粘贴到请求体的报文内容

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/228248857-4589e17e-354b-4073-b8c7-27063b0a9fca.png)
![1680009520002](https://user-images.githubusercontent.com/77324661/228250371-dae6a73a-bc5d-465a-a511-0dce44d713a1.jpg)
![1680009682494](https://user-images.githubusercontent.com/77324661/228250399-c8243c09-4ac7-494b-a266-9014bacbdc2f.jpg)
![1680009862000](https://user-images.githubusercontent.com/77324661/228251572-947526cf-6af3-4b42-845e-8fe80b1fc8af.jpg)

**Comment by 13290445582** [comment]
您好，请提供下参数文件

**Comment by binbin0406** [comment]
你好，参数文件里有两段，都可以使用。











 张树彬 
北区解决方案架构师
M: +86 15810085615
北京市朝阳区东三环中路7号财富中心写字楼A座3106室


FIT2CLOUD 飞致云 / www.fit2cloud.com
为数字经济时代创造好软件


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Mar 29, 2023 11:14 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] [BUG]在请求体里粘贴请求报文的长度较长时，显示不完整，没有显示参数最后的分号。 (Issue #23249)

&nbsp;



 
您好，请提供下参数文件

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进
