### ISSUE TITLE
[BUG]使用脑图编写用例，后来添加的用例调整到节点的最上边，保存后再次打开会显示在最下边

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#23243]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

使用脑图编写用例，后来添加的用例调整到节点的最上边，保存后再次打开会显示在最下边，不清楚是不是按添加时间倒序了，但在脑图中这样的排序并不合理

### 重现步骤

使用脑图编写用例，后来添加的用例调整到节点的最上边，保存后再次打开会显示在最下边

### 期待的正确结果

按脑图编写后保存的顺序展示

**Comment by 13290445582** [comment]
感谢反馈，脑图模式与列表模式排序一致，如果列表有排序，脑图的拖拽排序会失效。
