### ISSUE TITLE
[BUG]接口自动化内编辑模块名称修改失败，并报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2325]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8.2

**Bug 描述**
接口自动化内编辑模块名称修改失败，并报错 模块树结构来源于jmeter

**截图**
<img width="959" alt="WechatIMG129" src="https://user-images.githubusercontent.com/32027713/116197303-2b02b580-a767-11eb-878a-c2b593aecb59.png">
<img width="1116" alt="WechatIMG130" src="https://user-images.githubusercontent.com/32027713/116197314-2e963c80-a767-11eb-899f-b3b37f43579a.png">
<img width="1236" alt="WechatIMG87" src="https://user-images.githubusercontent.com/32027713/116197392-4cfc3800-a767-11eb-88b6-cf68ecb888b2.png">

**Comment by wangzhen-fit2cloud** [comment]
@fit2-zhao 勇哥确认下吧

**Comment by fit2-zhao** [comment]
1.9 已经修复
