### ISSUE TITLE
[BUG]功能用例评审评论，粘贴多张图片确定后，图片不能全部展示

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23250]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

功能用例评审评论，粘贴多张图片确定后，图片不能全部展示，其他同事不方便查看

### 重现步骤

1.评审功能用例，输入评论，粘贴3张图片，如图所示
![111](https://user-images.githubusercontent.com/103627487/228263783-1f28b532-69ef-4605-9a94-20d12db62b4b.png)
2.确认后，发现3张图片只显示1张，另一张显示的是图片链接，还有一张未显示
![222](https://user-images.githubusercontent.com/103627487/228264153-42d1e707-5bf6-4213-a5ac-6bde5dde40e0.png)
3.编辑评论可以看到3张图片
![333](https://user-images.githubusercontent.com/103627487/228264257-d601d4ac-24ae-42e8-9c63-860e57bf956f.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进
