### ISSUE TITLE
[FEATURE]用例评审 实际评审发现测试有很多用例测试点没考虑到漏了，但是评审实际也不能算没通过，希望评审加个遗漏状态

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#23262]
### MeterSphere 版本

1.20.10

### 请描述您的需求或者改进建议

用例评审 实际评审发现测试有很多用例测试点没考虑到漏了，但是评审实际也不能算没通过，希望评审加个遗漏状态

**Comment by luty2018** [comment]
没有太明白你的意思， 能再进一步描述你的使用场景吗？

**Comment by opopjasica** [comment]
目前用例评审过程中，会发现用例涉及人员会将测试点写漏，需要再下来修改补齐后，进行二次评审
但是已经是评审的状态，不能算当前用例不通过，应该算是遗漏；

目前用例评审标记 只有通过、不通过两个状态，所以希望再加一个标记，方便查找扩展

**Comment by luty2018** [comment]
建议你升级版本到v2.8.1， 我们有个重新提审的状态，评审中的用例发生变更后状态会自动切为重新提审状态。
