### ISSUE TITLE
[FEATURE]环境管理-通用变量，目前用的比较多，测试下来有四五十个变量挨着找起来比较麻烦，期望加一个变量分组方便管理

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#23263]
### MeterSphere 版本

1.20.10

### 请描述您的需求或者改进建议

环境管理-通用变量，目前用的比较多，测试下来有四五十个变量挨着找起来比较麻烦，期望加一个变量分组方便管理

**Comment by luty2018** [comment]
感谢建议， 这个功能会在我们v3.0版本规划。

**Comment by luty2018** [comment]
目前增加了一个搜索， 如果要分组展示，请问具体按什么类目进行分组呢， 是否有建议？

**Comment by luty2018** [comment]
![image](https://github.com/metersphere/metersphere/assets/36292514/65d1a75a-12ab-4da9-bec2-4292b40a1ea4)
v3.0已经增加了搜索和标签，建议您升级使用。
