### ISSUE TITLE
[BUG] 接口用例删除后，在回收站内不显示

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#23273]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

接口用例删除后，在回收站内不显示
数据库 api_test_case 表中status=Trash的数据，在回收站内不显示

### 重现步骤

删一个

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。
![image](https://user-images.githubusercontent.com/54612864/228494827-72f55cd9-b6d6-40ee-b208-d84cfad5c748.png)

CASE tab页面没有数据吗？怎么删除的？

**Comment by yangstones** [comment]
哦，只是数量显示不正确，点击进入回收站内还是能看到数据的。只是数量统计错误的显示为0

**Comment by youliyuan-fit2cloud** [comment]
我们环境回收站的统计数量也是正确的，清下缓存？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
