### ISSUE TITLE
[FEATURE] 脑图用例评审无法修改用例还需要返回功能用例页面编辑，很麻烦

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#23271]
### MeterSphere 版本

v1.20.19-lts-a80199cf

### 联系方式

346315670@qq.com

### 请描述您的需求或者改进建议

建议可以用脑图评审时直接修改用例，再把用例数据同步更新，不需要在评审的过程中再返回用例编写页面修改

**Comment by luty2018** [comment]
<img width="1429" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/83308619-9990-41f4-af2f-67851927cc21">
v3.0已支持，欢迎下载使用。
