### ISSUE TITLE
[BUG]   测试跟踪-测试计划-查看测试报告，报告中的失败用例详情打不开

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23280]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划-查看测试报告，报告中的失败用例详情打不开

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/228515051-e68012b9-79d8-438d-8bb9-253da24a6b0f.png)

![image](https://user-images.githubusercontent.com/103925124/228514910-c4095ca7-e8fa-43fb-b2f4-e2af2412e9f7.png)
![企业微信截图_16800837338937](https://user-images.githubusercontent.com/103925124/228514967-7c1d59e8-5b0d-4c8f-99f7-13fa6aeb1154.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！看下前端报错，如果是如下图报错，则该问题是已知问题，偶尔会出现前端组件注册失败的情况，可以强刷下页面就好了，计划v2.9对组建进行优化。
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/99731894/228711864-4c5734ae-51cd-40ea-a77b-7480ff79b556.png">
