### ISSUE TITLE
[BUG]页面停留在接口模块，刷新页面后列表展示全部数据而不是当前模块，不友好

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#23289]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

页面停留在接口模块，刷新页面后列表展示全部数据而不是当前模块，不友好

### 重现步骤

页面停留在接口模块，刷新页面后列表展示全部数据而不是当前模块，不友好

![页面停留在接口模块，刷新页面后列表展示全部数据而不是当前模块，不友好](https://user-images.githubusercontent.com/43202800/228710607-82ab8453-e4a9-41df-89be-a49badbf3ce4.png)

### 期待的正确结果

应该停留在当前接口模块

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题和产品沟通暂时不做修改，各模块都是这个逻辑。
