### ISSUE TITLE
[BUG] 测试计划-报告，查看报告内容，报告开始时间不正确

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23282]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

测试计划-报告，查看报告内容，报告开始时间不正确

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/228518449-8a68b8eb-d7a3-4bed-a07e-ca6e00184b1b.png)
![image](https://user-images.githubusercontent.com/103925124/228520147-7dd7fa27-3654-4cc4-ab5e-4259ef929d76.png)
查看测试跟踪-报告的该计划最新报告
![image](https://user-images.githubusercontent.com/103925124/228520644-d8f8d130-c2dc-4798-a54b-c66989df24a6.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、测试计划内的报告为临时报告-关联用例后开始时间就更新了。
2、测试跟踪-报告是执行计划时生成的一次性固定报告，这个开始时间是根据计划执行的开始时间而言的。
所以这2个地方的报告的开始时间是会不一致的。
