### ISSUE TITLE
[BUG]接口自动化，选择编辑其中的一个场景 导致页面报500错误【空指针异常】

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2328]
**MeterSphere 版本**
V1.8.2

**Bug 描述**
接口自动化，选择编辑其中的一个场景 导致页面报500错误

**截图**
![WechatIMG88](https://user-images.githubusercontent.com/32027713/116199019-3f47b200-a769-11eb-9891-7c8604d377c3.jpeg)
<img width="1079" alt="WechatIMG89" src="https://user-images.githubusercontent.com/32027713/116199034-4373cf80-a769-11eb-9002-07c9480dd686.png">
<img width="1281" alt="WechatIMG90" src="https://user-images.githubusercontent.com/32027713/116199041-453d9300-a769-11eb-860c-597617ad4ece.png">

**Comment by zyyfit** [comment]
感谢反馈

**Comment by dashenyucainiao** [comment]
啥时候能解决啊，客户等着要呢，影响使用

**Comment by zyyfit** [comment]
您好，已修复这个问题，目前最新版是1.9.3，请升级后再看看
