### ISSUE TITLE
[BUG]我们接口case执行成功,MS每次站内通知是创建人，但实际通知人不是case 创建人。

### ISSUE THREAD

**Issue by yjc1020** [metersphere/metersphere#23283]
### 联系方式

dejavu.yang@vevor.net

### MeterSphere 版本

 v1.20.20-lts

### 使用外置数据库

否

### 问题描述

我们接口case执行成功,MS每次站内通知是创建人，但实际通知人不是case 创建人，是其他的同事，其他人执行自己的case也是提示的某个同事的名字，请问是什么原因呢  ？

### 重现步骤

我们是原版本是1.20.8 然后在线升级到1.20.20-lts之后就有这个问题出现；不知道是在升级的过程中修改到其他文件了吗还是对数据库的表做了啥更改？

### 期待的正确结果

期望是通知到正确的case创建人，而不是用户列表中的固定的某个名字；

**Comment by youliyuan-fit2cloud** [comment]
你好，请检查一下消息设置-接口定义中的通知是如何设置的？
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/54612864/228532801-9615c0cf-7a19-4358-b889-5c9b3c771ff8.png">

**Comment by yjc1020** [comment]
都是默认的创建人





  	
 杨建川 
上海司顺电子商务有限公司  
 电话：02180158916-2342 
 ***@***.*** 
 地址：成都 
	     
	   		 上海司顺电子商务有限公司  	 企业主页  		      
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
 This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
***@***.***>
日　期：2023年03月29日 20:19:24
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [metersphere/metersphere] [BUG]我们接口case执行成功,MS每次站内通知是创建人，但实际通知人不是case 创建人。 (Issue #23283)

 你好，请检查一下消息设置-接口定义中的通知是如何设置的？

**Comment by yjc1020** [comment]
![image](https://user-images.githubusercontent.com/128673692/228704252-1cc8c287-476d-438c-847e-fdfd33886581.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，站内通知分为 “@提到我的”和 “系统通知”两种。
如果是你这种默认的配置，接收人是 选择的“创建人”，站内通知在“系统通知”里面，请看下 “系统通知”里面是否正确？
“@提到我的 ” 是指 接收人是指定了某个用户。
如果以上都正常，请联系我们远程看看情况，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
![Uploading image.png…]()
企业微信加我，然后方便腾讯会议，向日葵远程都行？

**Comment by yjc1020** [comment]
向日葵吧 我没企业微信；
------------------------------------------------------------------
发件人：MatataYou ***@***.***>
发送时间：2023年3月30日(星期四) 10:00
收件人：metersphere/metersphere ***@***.***>
抄　送：杨建川 ***@***.***>; Author ***@***.***>
主　题：Re: [metersphere/metersphere] [BUG]我们接口case执行成功,MS每次站内通知是创建人，但实际通知人不是case 创建人。 (Issue #23283)
 < >
 企业微信加我，然后方便腾讯会议，向日葵远程都行？

**Comment by youliyuan-fit2cloud** [comment]
微信号 ：18618203007

**Comment by yjc1020** [comment]
加你了 ，通过下
------------------------------------------------------------------
发件人：MatataYou ***@***.***>
发送时间：2023年3月30日(星期四) 10:06
收件人：metersphere/metersphere ***@***.***>
抄　送：杨建川 ***@***.***>; Author ***@***.***>
主　题：Re: [metersphere/metersphere] [BUG]我们接口case执行成功,MS每次站内通知是创建人，但实际通知人不是case 创建人。 (Issue #23283)
微信号 ：18618203007

**Comment by youliyuan-fit2cloud** [comment]
经排查是后台获取的在线用户错了，导致前端显示错误，下个版本修复～
