### ISSUE TITLE
[BUG] 【接口测试】-mock后置脚本-不支持获取content-type类型application/xml的xml数据

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23293]
### 联系方式

82973834@qq.com

### MeterSphere 版本

V2.8.0

### 使用外置数据库

否

### 问题描述

mock后置脚本目前只支持接收请求头content-type为test/xml类型的xml数据，不支持获取content-type类型为application/xml的xml数据，这个问题影响到客户使用mock，希望能在2.8.1版本上尽快修复！

### 重现步骤

1.新建一个mock
2.请求体选择为xml类型，请求头的Content-Type设置为application/xml
3.添加后置脚本接收请求数据，然后将接收的数据作为响应报文返回

### 期待的正确结果

1.mock后置脚本支持获取content-type类型为application/xml的xml数据

### 附加信息

1. mock后置脚本
![image](https://user-images.githubusercontent.com/45531073/228718928-cc53c8ba-5716-4822-a972-bd9cf031bf7a.png)

2.接收content-type类型为test/xml的xml数据
![image](https://user-images.githubusercontent.com/45531073/228719116-5fead2ee-6d80-4aeb-8a4f-fb2d8b189ffa.png)
![image](https://user-images.githubusercontent.com/45531073/228719147-6b9928c3-2415-446c-bcaf-3fe6d8370186.png)
2.接收content-type类型为application/xml的xml数据
![image](https://user-images.githubusercontent.com/45531073/228719280-690d2fd2-4826-476b-abbf-e5ac096341c5.png)
![image](https://user-images.githubusercontent.com/45531073/228719298-46897dff-9be5-4f31-89e2-d37925561a4a.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9支持。
