### ISSUE TITLE
[BUG] 接口参加批量操作选中后显示选中数不正确

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23298]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

接口步骤批量操作选中后显示选中数不正确

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/228756617-30315010-6a95-42e7-b4c8-7cbb4bab2aea.png)
![image](https://user-images.githubusercontent.com/103925124/228756716-0a170476-37ea-4f47-b66a-225d8fabec82.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，计划v2.8.1修复。

**Comment by zrfit** [comment]
您好，和产品沟通，v2.8.1去掉了批量操作选中后的数量展示，可升级验证。
