### ISSUE TITLE
[BUG]测试计划关联功能用例使用高级搜索搜自定义字段，再次使用高级搜索自定义字段消失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23299]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

1、测试计划里面关联测试案例，使用高级搜索功能，选择自定义的字段搜索关联用例
2、再次关联测试案例使用高级搜索功能，弹窗里面不展示自定义字段了

### 重现步骤

1、测试计划里面关联测试案例，使用高级搜索功能，选择自定义的字段搜索关联用例
2、再次关联测试案例使用高级搜索功能，弹窗里面不展示自定义字段了

### 附加信息

第一次：
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/32027713/228762181-5490e006-582d-4f82-b88e-c8d6398d6b24.png">

第二次，自定义字段消失了：
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/32027713/228762351-13d2a135-0660-4d44-8c1c-ff55f6d35f92.png">

**Comment by 13290445582** [comment]
Duplicate of #23217
