### ISSUE TITLE
[BUG] sql 中使用自定义变量中设置的内置函数不生效

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23296]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

sql 中使用自定义变量中设置的内置函数不生效

### 重现步骤

1.在 sql 自定义变量中设置变量，使用内置函数
![image](https://user-images.githubusercontent.com/103627487/228741615-08002543-c8ce-438d-9d0d-96eb4e1e672d.png)
2. 在 sql 中引用这个自定义变量
![image](https://user-images.githubusercontent.com/103627487/228741798-3b4b7d99-f610-4440-b1d0-440d737e6977.png)
3.查看請求
![image](https://user-images.githubusercontent.com/103627487/228742014-62951910-3c29-4178-ab08-3eb3f8433d4e.png)

**Comment by meijieDouDou** [comment]
![image](https://user-images.githubusercontent.com/103627487/229021839-a62717c5-f016-44ba-a5e5-1e36a0df87c8.png)
这里能否做个优化，或者给个提示，因为点击这个框显示的是 @id ,很多用户都不知道

**Comment by youliyuan-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/103627487/229021839-a62717c5-f016-44ba-a5e5-1e36a0df87c8.png) 这里能否做个优化，或者给个提示，因为点击这个框显示的是 @id ,很多用户都不知道

木问题，下个版本优化一下，加上提示。
