### ISSUE TITLE
[QUESTION]按照步骤排查后，kafka仍显示“kafka不可用，请检查配置”

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#233]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/53041390/90109567-96922780-dd7e-11ea-948c-ce36b6396020.png)
![image](https://user-images.githubusercontent.com/53041390/90109622-ab6ebb00-dd7e-11ea-8e8f-41f0166acf92.png)
不是使用外部的kafka。

要怎么处理kafka才可用

**Comment by chenqiunuan** [comment]
且防火墙已经关闭

**Comment by wangzhen-fit2cloud** [comment]
你好，请问现在 ms-data-streaming 的状态还是 starting 吗？
可以发下 /opt/metersphere/.env 文件的配置

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/90113844-7f563880-dd84-11ea-8691-17c1bae39144.png)
你好，请问是哪个文件？

**Comment by wangzhen-fit2cloud** [comment]
有个叫 .env 的隐藏文件

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/90114600-8598e480-dd85-11ea-84b4-5c424d9896ac.png)z
找到了，你看看。
不过我刚查看了zookeeper

![image](https://user-images.githubusercontent.com/53041390/90114435-49658400-dd85-11ea-9120-1adb64811e8a.png)
查看了zookeeper的日志。一直在循环报错

**Comment by wangzhen-fit2cloud** [comment]
![](https://user-images.githubusercontent.com/53041390/90114600-8598e480-dd85-11ea-84b4-5c424d9896ac.png)
这里的kafka地址是 31.7，与你发的第一张图里的 31.64 不一致，请问是什么情况呢？

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/90116414-0822a380-dd88-11ea-845a-ab888a3ba6b5.png)
这个是kafka的日志。你说的地址不一致的情况。我也不知道

**Comment by wangzhen-fit2cloud** [comment]
麻烦看下服务器上 ifconfig 的 IP 配置，你执行 nc -zv 这个命令的时候，为什么是用的 172.20.31.64 这个地址呢？

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/90117151-18874e00-dd89-11ea-998f-ac77fe497e22.png)
因为这台机子的ip就是31.64呀

**Comment by wangzhen-fit2cloud** [comment]
麻烦执行下这个命令看下结果
```bash
hostname -I|cut -d" " -f 1
```
可以把上面提到的 .env 文件中的 MS_KAFKA_HOST 的值改为 172.20.31.64 这个地址，再执行下 msctl reload 命令
另外这台服务器在安装 MeterSphere 前后有换过 IP 地址之类的吗？

**Comment by chenqiunuan** [comment]
可以了~改了IP后就行了。谢谢

**Comment by wangzhen-fit2cloud** [comment]
```bash
hostname -I|cut -d" " -f 1
```
这个命令的结果，以及是否更改过服务器 IP 呢？

**Comment by chenqiunuan** [comment]
![image](https://user-images.githubusercontent.com/53041390/90121314-694d7580-dd8e-11ea-9c84-e83a59350360.png)
该服务器IP是动态的，是会有更改的情况。

**Comment by wangzhen-fit2cloud** [comment]
如果是这样的话 IP 变了这里也需要相应地改一下

**Comment by chenqiunuan** [comment]
好的。谢谢
