### ISSUE TITLE
[BUG] 筛选自定义字段不属于条件不生效

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23303]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

筛选自定义字段不属于条件不生效

### 重现步骤

筛选多选下拉菜单：条件为属于
![image](https://user-images.githubusercontent.com/103925124/228786606-69e44801-1b3f-444c-87a7-3eaa5355f59e.png)
属于的结果：
![image](https://user-images.githubusercontent.com/103925124/228786908-6bdfed62-c332-41f8-9d1c-600ae4083881.png)
设置不属于：![image](https://user-images.githubusercontent.com/103925124/228787010-6bfadce2-9f57-4c64-baf1-ecfc31b64c8b.png)
结果为空：
![image](https://user-images.githubusercontent.com/103925124/228787168-e45ed5c1-7955-4215-8505-dfe16eea7c90.png)

### 期待的正确结果

设置不属于，应该出现除了属于的两条的所有用例

**Comment by 13290445582** [comment]
你好，请问设置为“不属于”后，无法筛选出来的数据是否为使用该用例模版之前创建的用例。使用该用例模版后创建的新用例，“不属于”条件可以筛选出来嘛？

**Comment by Ycr123888** [comment]
请问设置为“不属于”后，无法筛选出来的数据是否为使用该用例模版之前创建的用例
回答：是的
使用该用例模版后创建的新用例，“不属于”条件可以筛选出来嘛？
回答：可以的

**Comment by 13290445582** [comment]
感谢反馈，问题已提交至tapd平台，后续开发跟进

**Comment by 13290445582** [comment]
v2.8.1 中已修改，请升级一下吧～
