### ISSUE TITLE
[FEATURE]优化建议：接口参数变量引用期望可以添加，自动联想全局变量

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#23300]
### MeterSphere 版本

1.20.20

### 请描述您的需求或者改进建议

接口参数变量引用期望可以添加，自动联想全局变量
目前参数这里可以有自动联想，但是自己设置的变量不能联想过来，希望能够补齐这块的能力，使用体验up!up
![image](https://user-images.githubusercontent.com/43202800/228763314-f0c42800-1cc2-4beb-bab1-dca0fb35e599.png)

**Comment by Hyyfit** [comment]
感谢建议， 我们会在v3.0版本优化这里的体验

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
