### ISSUE TITLE
[BUG]功能用例字段变更记录中，字段变更显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23308]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

功能用例字段变更记录中，字段变更显示错误，对应不上

### 重现步骤

如下图

### 附加信息

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/32027713/228809458-c9ec38d2-d590-47bf-8864-bd53cea63eb0.png">

**Comment by 13290445582** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128017892/228814931-3e0040d0-1914-461a-883d-dac496dd841d.png">
您好，您提供的问题并未复现，请问还有其他帮助复现的相关信息嘛或者操作录屏

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
