### ISSUE TITLE
[BUG]验证MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败

### ISSUE THREAD

**Issue by ys-xmgg** [metersphere/metersphere#23328]
### 联系方式

maqingyuan@huice.com

### MeterSphere 版本

2.80

### 使用外置数据库

否

### 问题描述

Jenkins插件配置metersphere构建时，验证账户提示：验证MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败。检查url,key和secretkey都是正确的

### 重现步骤

稳定重现

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，Jenkins插件用的是哪个版本？最好和MeteSphere版本一致，按发布的Jenkins最新版本试下。

**Comment by ys-xmgg** [comment]
2.80版本，是一致的，导入.hpi的Sent from my iPhoneOn Mar 31, 2023, at 11:14, zrfit ***@***.***> wrote:﻿
您好，感谢您的反馈！未复现该问题，Jenkins插件用的是哪个版本？最好和MeteSphere版本一致，按发布的Jenkins最新版本试下。

**Comment by liuruibin** [comment]
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/23045261/229036244-ea92c807-71b1-4f25-937d-c38e4ad23c3e.png">
您可以从jenkins上查看日志有没有别的错误
