### ISSUE TITLE
[FEATURE]使用插件同步接口到平台时，controller类上的地址前缀无法识别

### ISSUE THREAD

**Issue by yangdonghui** [metersphere/metersphere#23326]
### MeterSphere 版本

 v2.6.0-068f4f4a

### 联系方式

114-领先未来-MS-企业支持群

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/3621332/229003784-34a298a4-7988-42ed-9a4e-bcf98b800a67.png)
![image](https://user-images.githubusercontent.com/3621332/229003828-ef4a6a12-836c-49d2-bca9-a2d09d06eca5.png)
![image](https://user-images.githubusercontent.com/3621332/229003916-973ee3eb-3b76-4a18-8b24-1368aef4a389.png)

### 请描述你建议的实现方案

希望能识别在controller类上的前缀，从ide同步接口的时候能自动识别后进行地址拼接处理

**Comment by luty2018** [comment]
你的插件版本是多少
