### ISSUE TITLE
[BUG] 接口 json 请求体内容替换后，旧描述依然在，且新描述输入不了

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23336]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

 接口 json 请求体内容替换后，旧描述依然在，且新描述输入不了

### 重现步骤

复现步骤在视频中，[video(10).zip](https://github.com/metersphere/metersphere/files/11117979/video.10.zip)

问题比较动态，截图不好说明

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，计划v2.9修复。
