### ISSUE TITLE
[FEATURE] 响应体预览类型是否可以支持根据响应头的类型来自动切换？

### ISSUE THREAD

**Issue by abeelan** [metersphere/metersphere#23349]
### MeterSphere 版本

2.8

### 请描述您的需求或者改进建议

响应预览类型是否可以支持根据响应头的类型来自动切换？

<img width="491" alt="image" src="https://user-images.githubusercontent.com/34361264/229051950-6585826e-05f1-401d-92eb-65a9e0cb3a20.png">

响应体大部分都是 json，每次查看都需要手动切换一下。
这样需要展示啥类型的预览，直接修改响应头就好了。。。

**Comment by Hyyfit** [comment]
感谢建议，我们会在v3.0版本可以支持用户设置 默认展示的格式；

**Comment by abeelan** [comment]
好的~ 辛苦~
