### ISSUE TITLE
[BUG] CASE 编辑页面，执行完请求后，手动修改预览响应体为 json，再次执行，预览格式有误

### ISSUE THREAD

**Issue by abeelan** [metersphere/metersphere#23350]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

如题

### 重现步骤

如题，再次执行该请求，响应体预览格式变为一行，但是预览格式类型显示的依然是 json
需要手动切换到 text，再手动切换为 json，格式显示才正确。

**Comment by zrfit** [comment]
您好，感谢您的反馈！能截个图吗？实际响应体格式是什么？

**Comment by abeelan** [comment]
![image](https://user-images.githubusercontent.com/34361264/229419923-8fd61a58-c462-4a19-b8cd-19dd297e17a3.png)

格式变为一行展示了（text？），高亮还是在的，预览方式选择的还是 json。

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.9修复。
