### ISSUE TITLE
[BUG] 执行场景用例失败时，抛越界异常

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#23377]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

1. 通过测试计划执行包含多个步骤的场景用例，并设置执行模式为 失败停止
2. 其中一个步骤执行失败
![c2481f432b4400ded7fc393068dd524](https://user-images.githubusercontent.com/2188338/229108389-4b5dfa5b-4e74-439c-ae8c-4990a8a08533.png)

error日志中持续出现越界异常，如下：
![813cfcce82290073e2f76c1fcf342ac](https://user-images.githubusercontent.com/2188338/229108433-3232d96e-b33b-46ce-875f-34601116b9a6.png)

### 重现步骤

如上

**Comment by fit2-zhao** [comment]
感谢反馈，从错误信息来看是报告加载问题，经过研究这个错误信息并不影响正常使用，我们会在下个版本进行调整。

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
