### ISSUE TITLE
[BUG]将测试case导出至xmind文件，导出的xmind文件修改case后，无法再次导入至metersphere,导致用例库无法维护

### ISSUE THREAD

**Issue by xiaozhang873** [metersphere/metersphere#23379]
### 联系方式

xiao.zhang@transsion.com

### MeterSphere 版本

v1.10.4-221f275f

### 使用外置数据库

否

### 问题描述

用例库中的case导出xmind文件，该文件再次导入metersphere，无法导入成功，导入用例均为空

### 重现步骤

1.导出为xmind文件
导出格式
![image](https://user-images.githubusercontent.com/129511669/229112948-622aaf04-f863-4440-a4b2-3b64be57d660.png)
2.将文件再次导入metersphere,文件夹下的所有用例均为空
![image](https://user-images.githubusercontent.com/129511669/229113316-22db6c2b-fd73-47a2-bd12-7d22425bf313.png)

**Comment by maninhill** [comment]
请升级到最新的 v1.20.21-lts 版本。

**Comment by maninhill** [comment]
v1.10 太老，我们只支持和维护 v1.20 lts 版本。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.2-lts最新版本未复现，建议您升级至最新版本。
