### ISSUE TITLE
V2.6版本源码本地打包报错

### ISSUE THREAD

**Issue by MyKays** [metersphere/metersphere#23387]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/49096399/229430709-98733863-fac5-46bc-9d5b-c05ae81767e1.png)
![image](https://user-images.githubusercontent.com/49096399/229430852-d0c9e528-2f5c-480a-a019-29d7fa451a4a.png)
这个包本地已经打好了，还是一直报找不到

**Comment by luty2018** [comment]
二次开发，建议自行研究代码哈。
