### ISSUE TITLE
[FEATURE]消息通知太简单且不直观

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#23382]
### MeterSphere 版本

v2.8

### 联系方式

bowen.tang@fit2cloud.com

### 请描述您的需求或者改进建议

目前ms提供的消息通知到邮件等第三方平台太简单，如执行自动化场景之后只提供了一个报告url跳转及场景名称和成功与否，企业版也只是新增了一些参数，通过html编写方式来自定义页面，但这参数所提供的信息太少，没法显示场景里详细的步骤，还是需求去点击url查看详细报告，非常不实用。用户在使用robot framework（其他开源产品也是），可以在邮件正文直接提供非常详细的报告内容，如场景里每步执行结果，这些都不需要去点击链接就可以获取，非常高效。
ms的消息通知在企业版功能能不能优化一下，可以直接提供详细的报告，至少将执行错误的步骤名称等信息显示出来。
【配图是用户用的robot framework出具的邮件报告】
![d19609988fabe6371e1765aad0eed31](https://user-images.githubusercontent.com/66759501/229402499-89bc7490-38c3-430e-8a12-63ae31e2f68b.png)

### 请描述你建议的实现方案

类似robot framework的报告，实现不难，就看愿不愿意做出来，可以放到当前企业版功能中；
另外也可以跟dataease的定时报告类似，发送的是仪表板的截图，ms可以将报告截图出来放到发送的邮件中。

**Comment by luty2018** [comment]
3.0 我们会支持添加dataease的链接， 这个可以前期通过dataease来满足需求。
