### ISSUE TITLE
[BUG]UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：其他设置中的截图设置不是指定的设置，而是变为默认设置了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23395]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：其他设置中的截图设置不是指定的设置，而是变为默认设置了。

### 重现步骤

UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：其他设置中的截图设置不是指定的设置，而是变为默认设置了。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/229445949-cdb8887f-9164-4c09-82c5-c9484a1f34c2.png)
![image](https://user-images.githubusercontent.com/78218624/229446321-b8188905-b8ca-419c-98e5-f26f6b9147cb.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！UI目前只支持导出为ide格式，不支持导出为metersphere格式，截图配置为metersphere的扩展功能，所以导出导入后会恢复为默认配置。
