### ISSUE TITLE
[BUG]UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：断言中断言值的判断符号由大于、包含等都变为了等于

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23394]
### MeterSphere 版本

V2.8

### 使用外置数据库

否

### 问题描述

UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：断言中断言值的判断符号由大于、包含等都变为了等于

### 重现步骤

UI测试>>>导出脚本>>>再把脚本导入到其他项目，出现问题：断言中断言值的判断符号由大于、包含等都变为了等于

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/229444299-22cfb4a9-4930-4b35-abf9-e20a633c9cb7.png)
![image](https://user-images.githubusercontent.com/78218624/229444580-0034a3db-d53c-4823-83b5-241372284477.png)

**Comment by xiaomeinvG** [comment]
selenium ide只支持等于和不等于，所以导出时ms系统会处理为“=”
