### ISSUE TITLE
[BUG] 浏览器访问测试计划预览地址，metersphere页面出现屏闪，且跳转预览页面失败

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23393]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

 浏览器访问测试计划预览地址，metersphere页面出现屏闪，且跳转预览页面失败

### 重现步骤

1、复制默认空间下的测试计划预览地址
![image](https://user-images.githubusercontent.com/103925124/229441486-59238baa-5699-4799-aa24-ff8d7963a575.png)
2、将空间切换到非默认空间下
输入刚才的地址，metersphere页面出现屏闪，且最终，加载测试计划预览页面失败，展示的是下面的页面
![image](https://user-images.githubusercontent.com/103925124/229441876-80a4c862-f37b-4fb1-8277-51b17ed1c151.png)
3、将复制的链接，在无痕窗口空白地址栏直接访问可成功

**Comment by youliyuan-fit2cloud** [comment]
你好，这个场景我们目前还不支持，如果有强烈需要请提个需求，感谢理解和支持。

**Comment by Ycr123888** [comment]
原来可以的

**Comment by Ycr123888** [comment]
2.7之前版本也可以的
