### ISSUE TITLE
[BUG]修改接口定义，用户体验不好

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#23403]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/2188338/229470533-2c75fdd8-55dc-4606-864b-266460583b57.png)
修改完基础信息，还得点击api tab, 再点保存，麻烦

### 重现步骤

同上

**Comment by Hyyfit** [comment]
非常抱歉给您带了不好的体验。
我们v3.0会对这个页面的交互升级优化
