### ISSUE TITLE
[BUG]单独执行测试计划关联的接口用例或场景，执行完成后，用例状态未正确更新

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#23404]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.20-lts

### 使用外置数据库

否

### 问题描述

单独执行测试计划关联的接口用例或场景，执行完成后，用例状态没有更新正确

### 重现步骤

1.结果如下图
![image](https://user-images.githubusercontent.com/88763608/229472262-40a6de89-e444-48d0-85c5-23f6ffbf290c.png)

### 期待的正确结果

应该正确更新

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v1.20.22修复。
