### ISSUE TITLE
[BUG]接口测试导入jmeter文件后，调试接口。test下会一直提示输入url。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23416]
### 联系方式

kaijie.yu@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

1.使用jmeter调试完接口后，把jmx文件导入到我们平台，切换到test下，点测试，会一直提示让输入url

### 重现步骤

1.jmeter调试后的jmx文件
![image](https://user-images.githubusercontent.com/55130444/229485008-a7bc9a3d-1e8d-4229-abb1-364d1ffb5676.png)
2.导入到ms平台
![image](https://user-images.githubusercontent.com/55130444/229485109-aabf4e1d-a2da-400f-b253-5d511a220a3a.png)
3.切换到test下，点测试会一直提示输入url
![image](https://user-images.githubusercontent.com/55130444/229485287-cbdf3ee9-21dc-43cb-a457-0b766bda16fb.png)

### 期待的正确结果

1.调试后的脚本，选择环境后可以直接在test调通。

**Comment by 13290445582** [comment]
该问题未复现

**Comment by 13290445582** [comment]
v2.9.0已修复
