### ISSUE TITLE
[BUG] 接口自动化-场景定时执行，报告发送钉钉群，点击链接需要登录

### ISSUE THREAD

**Issue by Mr-Brown-bear** [metersphere/metersphere#23434]
### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

接口自动化场景定时执行后，测试报告推送钉钉群，链接报告需要进行登录，若浏览器登录过则直接打开。

### 重现步骤

群消息：
消息通知: 
xxx执行接口自动化成功: 2023-03-11-21-36, 报告: http://xxx.xxx.xxx.xxx:xxx/#/api/automation/report/view/194eb4a0-f440-452c-b26c-fb3622262538
点击链接，需要登录

### 期待的正确结果

期望：可以免密查看测试报告

**Comment by Mr-Brown-bear** [comment]
交流群反馈过
![image](https://user-images.githubusercontent.com/45188256/229681845-33a350dc-5d77-4dd7-bbe6-2f2de94e6691.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进

**Comment by wxg0103** [comment]
您好  链接需要登录主要是因为在该浏览器没有登录过，没有需要的session等信息。
我们企业版可以配置通知模版，可以设置免密登录链接。
祝您生活愉快
