### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by qq876633655** [metersphere/metersphere#23438]
### MeterSphere 版本

v2.8.0-ac76fee1

### 请描述您的需求或者改进建议

用例模板中添加字段

### 请描述你建议的实现方案

希望添加一个类似jira中标签的模板字段，可以编辑添加，也可以下拉框选择添加，可以下拉框选择历史中已有的标签

### 附加信息

<img width="497" alt="微信图片_20230404144531" src="https://user-images.githubusercontent.com/52779051/229710024-fe73008a-339d-462b-8ec1-49297a585701.png">

**Comment by luty2018** [comment]
您好， 感谢建议， 目前标签还没有计划要做统一管理， 可能需要大多数人有这个需求，我们才会考虑呢。

**Comment by qq876633655** [comment]
不是给标签坐统一管理，是希望用例模板的自定义标签可以添加一种类型，可以下拉选择，可以手动填写，类似jira里面的标签使用。现在大部分的自定义字段只有单独的下拉选择或者单独的文本填写，可以优化成一个类型

**Comment by luty2018** [comment]
哦哦， 理解了。我看一下哈。
