### ISSUE TITLE
[QUESTION]接口测试一直在测试中loading状态，有时会导致api模块的重启

### ISSUE THREAD

**Issue by littlelilyjiang** [metersphere/metersphere#23433]
### 请描述您的问题

请求一个项目中请求数据比较大，时长比较长的接口时，自定义请求一直处于测试中的loading状态【如下图】
![image](https://user-images.githubusercontent.com/21242743/229681052-9cce41fb-9dac-4f30-99ea-91a5036953d7.png)
如果点击停止会出现错误提示【如下图】，然后api模块开始自动重启
![image](https://user-images.githubusercontent.com/21242743/229681081-2d4932ee-d732-4f90-9fe0-4bec7716483b.png)

在postman请求这个接口，请求的时间也很久，但是最终可以返回数据
![image](https://user-images.githubusercontent.com/21242743/229681138-ce5f9208-8647-4865-904a-72696554fabe.png)

尝试修改全局超时时间为240000也无法正常完成请求

**请问有什么办法可以正确请求这种请求时长较长的接口吗？**

**Comment by luty2018** [comment]
请问你当前使用的版本？

**Comment by littlelilyjiang** [comment]
@luty2018 你好 使用的2.8.0

**Comment by fit2-zhao** [comment]
您这可能存在两个问题：1 请求响应时间较长导致处于loading状态是因为web socket连接长时间没响应超时了，这个问题在2.8.1 会修复；2 停止导致服务重启这个问题我们暂时也没复现，这个可能和您部署时api服务分配的内存是否足够有关，如果您执行的接口比较耗费资源且同时有很多类似接口同时并发，建议相应内存可以加大些。

**Comment by littlelilyjiang** [comment]
期待1中的修复

2中之前重启的问题出现比较频繁，增加了机器的配置之后重启的情况减少了很多只是偶然会出现，应该确实和内存分配有关系

谢谢解答
