### ISSUE TITLE
[BUG]脑图模式下复制用例并保存，会导致被复制的用例丢失

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#23432]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.21-lts

### 使用外置数据库

否

### 问题描述

脑图模式下复制用例并保存，会导致被复制的用例丢失

### 重现步骤

1.使用火狐浏览器打开ms v1.20.21-lts版本，以cloud为例
2.在某模块下手动创建一条用例保存，左边模块用例数正常更新。
3.将上一步创建的用例复制一个，再保存。发现左边模块树用例数量还是1，再次点击模块树进入脑图，最开始的用例不见了，只保留了复制出来的用例。
4.具体现象和操作步骤可以参考附件视频。
5.该问题在火狐浏览器文档复现，在谷歌浏览器偶现，希望都能处理。

### 期待的正确结果

正常保存更新

### 附加信息
[脑图保存问题.zip](https://github.com/metersphere/metersphere/files/11144389/default.zip)

_No response_

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进

**Comment by 13290445582** [comment]
您好，目前火狐使用脑图会有一些兼容性问题，推荐您先使用谷歌浏览器
