### ISSUE TITLE
[BUG]非root的系统用户执行性能测试偶尔提示无权限

### ISSUE THREAD

**Issue by liuchangfitcloud** [metersphere/metersphere#2345]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  登录非root的系统管理员点性能测试报错
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
系统管理员有权限访问所有操作

**截图**
如果有截图，请附上截图.
![421619516213_ pic](https://user-images.githubusercontent.com/44662176/116221048-d455a580-a77f-11eb-802b-8d50225bdf74.jpg)

**Comment by zyyfit** [comment]
您好，请问登陆的账号有项目的操作权限吗？具体是什么权限的用户呢？只读用户是不能进行操作的
