### ISSUE TITLE
[BUG]测试用例评审>>>创建评审>>>评审通过标准选择【全部通过】；>>>添加评审用例：添加一条用例，其评审结果为【未开始】，添加到计划里。问题：还未开始评审，但是此评审结果，被设置为【评审中】

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23455]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

测试用例评审>>>创建评审>>>评审通过标准选择【全部通过】；
>>>添加评审用例：添加一条用例，其评审结果为【未开始】，添加到计划里。
问题：
1、还未开始评审，但是此评审结果，被设置为【评审中】
2、点击【取消关联】，该用例的评审结果也不会被还原，还是【评审中】

### 重现步骤

测试用例评审>>>创建评审>>>评审通过标准选择【全部通过】；
>>>添加评审用例：添加一条用例，其评审结果为【未开始】，添加到计划里。
问题：
1、还未开始评审，但是此评审结果，被设置为【评审中】
2、点击【取消关联】，该用例的评审结果也不会被还原，还是【评审中】

### 期待的正确结果

1、还未开始评审，但是此评审结果，被设置为【评审中】===还没有开始评审呢，不能设置状态为‘评审中’
2、点击【取消关联】，该用例的评审结果也不会被还原，还是【评审中】===有时误操作关联错误用例，在取消，其用例的评审结果应该被还原。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/229779696-d11185cd-a84f-4494-a83a-fdbe5d24c167.png)

![image](https://user-images.githubusercontent.com/78218624/229779281-cf1f76cc-b724-4eae-8223-9465e0d95aa7.png)

**Comment by 13290445582** [comment]
您好，您反映的问题当前产品设计如此，感谢反馈。

**Comment by Hyyfit** [comment]
您好，感谢反馈。
问题1:设计是这样的。
用例的评审状态根据流程有3种情况
未加入评审计划【未评审】->已进入评审计划【评审中】->有评审结果【通过/未通过】
【评审中】的状态一是可以快速的分辨出是否加入了测试计划；二是多人评审的时候，【评审中】是一个中间态，需要所有的评审人都评审了才有一个最终态的评审结果。

问题2:取消关联，评审未更新状态，为已知的bug，2.9会优化。
