### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lin-wu-1990** [metersphere/metersphere#23467]
### MeterSphere 版本

2.7.1

### 联系方式

微信交流群39，yzbf

### 请描述您的需求或者改进建议

汇报一个不知道是不是bug的问题，今天因为metersphere不支持导入postman环境变量，所以写了个脚本转换postman变量文件格式来输出键值对，想直接复制进ms里，然后运行就报错了，发现是键值对后面的换行符也被带进变量里去了，查看接口请求，整页复制的键值对，每一行后面的换行符都会被转义成/r
![7f65205b12d6a566388747015a95b16](https://user-images.githubusercontent.com/72718331/230354211-7cda9959-c8a1-4bd3-a202-a58c923bb7a6.png)
![186e988557d534b72a972352ac192aa](https://user-images.githubusercontent.com/72718331/230354265-3ade80a1-698b-4097-8027-c8a8a0bef768.png)
![7a71c07503221210c8aff7fd188c7e7](https://user-images.githubusercontent.com/72718331/230354287-55d9ba70-761f-4ea5-9a2b-a8e2ba3963be.png)

### 请描述你建议的实现方案

建议在批量导入时，去除尾部的换行符

**Comment by wxg0103** [comment]
您好，这个在v2.8.1已经修复了，您可以升级试试。
