### ISSUE TITLE
[BUG]执行环境地址为特殊域名的接口自动化，会导致页面一直处于执行中

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23464]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.21-LTS

### 使用外置数据库

否

### 问题描述

执行环境地址为特殊域名的接口自动化，会导致页面一直处于执行中

### 重现步骤

创建自定义请求或者接口定义内复制接口，例如配置环境为：http://sop.zqsit.internal.virtueit.net:81
页面会一直处于执行中

### 附加信息

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/32027713/230321622-1ec03698-9bd7-4aea-a0ec-c3c8226fb9b8.png">

**Comment by 13290445582** [comment]
你好，你提供的配置环境使用postman工具也是此现象，是不是环境问题？

**Comment by dashenyucainiao** [comment]
> 你好，你提供的配置环境使用postman工具也是此现象，是不是环境问题？

PostMan可以超时退出，但是ms却一直处于“执行中”，会导致执行过程卡住

**Comment by 13290445582** [comment]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/128017892/230355374-175ca92d-c751-4e47-92d4-f8b08c68285a.png">
接口请求的默认超时时间为一分钟，ms同样如此

**Comment by dashenyucainiao** [comment]
> <img alt="image" width="1346" src="https://user-images.githubusercontent.com/128017892/230355374-175ca92d-c751-4e47-92d4-f8b08c68285a.png">
> 
> 接口请求的默认超时时间为一分钟，ms同样如此

你这个版本是1.20.21-lts版本吗？

**Comment by 13290445582** [comment]
是

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
