### ISSUE TITLE
用例模板自定义字段多了之后，不管是写用例的时候还是执行用例的时候显示的都很混乱

### ISSUE THREAD

**Issue by qq876633655** [metersphere/metersphere#23471]
### MeterSphere 版本

2.8.0

### 请描述您的需求或者改进建议

用例模板自定义的字段比较多，希望可以对多的字段进行一个排版，让整体看起来有顺序，不是杂乱的

### 请描述你建议的实现方案

不需要智能，最简单的实现就是按照个人用例模板里面从上到下定义的字段进行顺序排版就行了

### 附加信息

<img width="1234" alt="62D6D450-031A-46d2-9242-557903D3138C" src="https://user-images.githubusercontent.com/52779051/230360157-f856a3b7-eb1e-46e0-9cf5-8425e0ba65d3.png">
<img width="1234" alt="37EA6C95-26CC-441c-B55F-9F7C567158C9" src="https://user-images.githubusercontent.com/52779051/230360172-bd0f89a5-4370-4f90-8607-49d180722161.png">
<img width="1234" alt="2B4D62A3-9EF4-4c16-8CCB-C246BBBA33CE" src="https://user-images.githubusercontent.com/52779051/230360287-7e34c56b-9cbf-4868-a853-13afe945b2fb.png">

**Comment by luty2018** [comment]
感谢建议， 我们v2.9优化一下
