### ISSUE TITLE
[BUG]切换环境，数据源不会切换到同名数据源

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23477]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.0&v1.20.21-lts

### 使用外置数据库

否

### 问题描述

切换环境，数据源不会切换到同名数据源,一个环境里有多个数据源，多个环境数据源相同，切换环境，数据源不会切换到同名数据源

### 重现步骤

1.多个环境里有多个数据源，数据源名称相同
![数据源](https://user-images.githubusercontent.com/103627487/230533347-f88f8241-08e2-483e-a3ce-86d122c24e0e.png)
2.场景中选择环境63（第二个数据源）保存
![image](https://user-images.githubusercontent.com/103627487/230533475-a0578806-cc0c-430f-81f0-d0d00d0e3da6.png)
3.切换环境，发现数据源切换到了2702，没有切换到同名数据源63

### 期待的正确结果

期望切换环境，能切换到同名数据源

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划v2.9修复
