### ISSUE TITLE
[BUG]执行接口用例时，mock数据在发起接口请求前没有被转化

### ISSUE THREAD

**Issue by rbsrcy** [metersphere/metersphere#23476]
### 联系方式

zhuoshangyi@hntsp.com

### MeterSphere 版本

v1.20.21-lts-6359b12e

### 使用外置数据库

否

### 问题描述

执行接口用例时，mock数据在发起接口请求前没有被转化

### 重现步骤

![](https://api.onedrive.com/v1.0/shares/s!AuzCPramtuAZhFIWl8Um587thX8L/root/content)
![](https://api.onedrive.com/v1.0/shares/s!AuzCPramtuAZhFMEmibCi9j-AKyB/root/content)

### 期待的正确结果

执行接口用例时，mock数据在发起接口请求前是被转化了的
期望值："access_token": "XXXXX-XXXXX-XXXX-XXXXX"
实际值："access_token": "${__Mock(@guid)}"

**Comment by scarletyyh** [comment]
您好，目前我们的mock环境不支持使用@guid和${ }，十分抱歉。

**Comment by zyyfit** [comment]
> 这个@Guid 不是你们环境提供的的选项就有的吗?见下图，然后那个${} 是你们转化出来的，我没有写这个玩意 ![](https://camo.githubusercontent.com/fa660340d60685fce05b2171f0a54b418c329c8eaf8495e60565dbcd96c4d590/68747470733a2f2f6170692e6f6e6564726976652e636f6d2f76312e302f7368617265732f732141757a435072616d7475415a6846774e536875594243303465634b442f726f6f742f636f6e74656e74)

您好，这里是这样的，@ 形式的变量在接口请求里是可以用的，但是mock期望里是不支持的，mock期望里也不支持 ${} 变量，也就是说，假设您在mock期望里添加了 @String 变量作为请求参数或者是响应值，在执行的时候，系统不会将这个mock期望里的 @String 解析成随机字符串，不过在其他页面，比如接口API、TEST、CASE 等页面都是可以使用 @ 变量的

**Comment by rbsrcy** [comment]
为啥不支持呀，我mock接口的目的不就是为了仿照假数据的吗

**Comment by song-tianyang** [comment]
不好意思，目前的开发计划安排中暂时还没有增加MockJs支持的打算。 

mock参数可选@xxx是我们细节上的失误，后续版本中已经去掉了。支持MockJs后会再开放出来。

**Comment by rbsrcy** [comment]
希望mock接口返回参数支持 mockjs，很好用的功能为啥要去掉

**Comment by song-tianyang** [comment]
您可能误会了。

Mock期望里的后置接口从没支持过MockJS函数。

接口定义、接口用例、接口场景等前后置脚本以及自定义脚本步骤是一直可以支持MockJS的，没有去掉。

这两个不是同一个功能。

感谢支持。

**Comment by rbsrcy** [comment]
希望后续Mock期望支持MockJS
