### ISSUE TITLE
[BUG]接口自动化场景里Not Null断言，导出jmeter脚本后断言成为 Null

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23484]
### 联系方式

王进

### MeterSphere 版本

v.1.20.21, v2.8.1

### 使用外置数据库

否

### 问题描述

接口自动化场景里Not Null断言，导出jmeter脚本后断言成为 Null

### 重现步骤

1. 新建接口自动化场景。
2. 添加请求，添加Not Null断言。
3. 导出场景为jmeter格式。
4. 用jmeter工具打开，查看Not Null断言----导出jmeter脚本后断言成为 Null
<img width="957" alt="1680850929363" src="https://user-images.githubusercontent.com/76033005/230559109-0af76ff3-b5e9-484a-b0f5-54e6b53754d0.png">

**Comment by fit2-zhao** [comment]
JMeter 自身在这块支持有限，我们基于JMeter又扩展了几种校验方式，所以从平台导出的JMX文件是有差异的。
