### ISSUE TITLE
[BUG] 脑图模式下用例莫名被删除

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#23491]
### MeterSphere 版本

2.7.0

### 使用外置数据库

否

### 问题描述

有很多用例被莫名放到了回收站里，怀疑跟脑图编辑有关。至少确认有2人是上周创建的用例，已经进行了评审，这周发现模块下用例全不见了（模块本身还在），后来发现都在回收站里。测试人员自己肯定没做删除操作。
使用的都是Chrome浏览器。
初步检查发现，至少有5个模块，五位测试人员维护用例存在该现象，并受次影响。
检查回收站，发现回收站里有2万多用例，至少从去年11月份开始就有此现象（用例被非人工误删）。

### 重现步骤

怀疑的操作场景（有可能是其他的操作场景）
  模块A 测试人员是 A1、A2两个人， 但模块B的同学会删除模块A的用例

**Comment by 13290445582** [comment]
您好，感谢您的反馈，该问题在最新版本v2.8.1未复现，建议升级尝试。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
