### ISSUE TITLE
[QUESTION] 根据路径配置域名，是否支持一条域名下配置多个路径？

### ISSUE THREAD

**Issue by abeelan** [metersphere/metersphere#23490]
### 请描述您的问题

环境配置 - HTTP配置，选择按路径配置

问题：
域名为 host.com，需要匹配该域名的一级路径：
- path1
- path2
- ... 

目前是添加多个配置，也就是 
-  添加一条HTTP配置：host.com  /path1
-  添加一条HTTP配置：host.com  /path2
-  添加一条HTTP配置：host.com  /...

域名会写多次。这种情况是否支持 host.com 下同时配置多条一级路径呢？

> 一个应用包含了很多子应用，所以有这种场景。

尝试按照模块去配置，但是勾选了一级模块后，下面新增子模块并不会自动生效，还需要手动去添加，总是忘记~ 模块多了，维护起来不太直观。

**Comment by luty2018** [comment]
感谢建议！
“尝试按照模块去配置，但是勾选了一级模块后，下面新增子模块并不会自动生效，还需要手动去添加，总是忘记~ 模块多了，维护起来不太直观。”
模块这里我们会提供一个选项是否包含模块的子级，来覆盖你这种场景

**Comment by abeelan** [comment]
> 感谢建议！ “尝试按照模块去配置，但是勾选了一级模块后，下面新增子模块并不会自动生效，还需要手动去添加，总是忘记~ 模块多了，维护起来不太直观。” 模块这里我们会提供一个选项是否包含模块的子级，来覆盖你这种场景

那太好了，这个改动会放在五月份的 lts 版本当中吗？

上面已经能满足大部分需求了；感谢。

还是弱弱的说一句，按模块去配置的话，模块中其实也是会包含一些请求其他域名的接口，域名支持配置多路径这个需求也还是存在的。

**Comment by luty2018** [comment]
会的，已经规划在5月份的lts版本了。
