### ISSUE TITLE
[BUG]接口自动化前后置脚本通过vars.putObject设置的数组不能直接用于for each循环。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23496]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

前后置脚本通过vars.putObject设置的数组不能直接用于for each循环。

### 重现步骤

1.接口自动化场景复制接口。
2.接口后置脚本中定义list类型变量。
3.通过vars.putObject将list变量设置为场景变量
4.这个接口后新增循环控制器，无法直接使用 设置的场景变量。

### 期待的正确结果
通过vars.putObject设置的list场景变量可以直接用于for each循环
_No response_

**Comment by zrfit** [comment]
您好，感谢您的反馈！
这种情况暂时不支持；JMeter ForEach遍历的是prefix_index类似的集合。
