### ISSUE TITLE
[FEATURE]在TCP协议和SQL协议的接口测试报告，“请求内容”需要加上请求地址信息

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#23503]
### MeterSphere 版本

v2.8.0

### 联系方式

songbing@fit2cloud.com

### 请描述您的需求或者改进建议

如果标题描述的信息

### 请描述你建议的实现方案

HTTP协议的接口测试报告中，“请求内容”是有请求地址信息的
<img width="964" alt="image" src="https://user-images.githubusercontent.com/18387151/230834078-1eca3127-4294-4a47-bae7-239068e04d6e.png">

TCP协议的接口测试报告，“请求内容”需要请求地址信息
<img width="799" alt="image" src="https://user-images.githubusercontent.com/18387151/230834239-29336b22-74d0-4dfe-a1a2-ba473dbc1b9f.png">

SQL协议的接口测试报告，“请求内容”也需要请求地址信息，还有连接的数据库名称信息
<img width="758" alt="image" src="https://user-images.githubusercontent.com/18387151/230834361-f686c4cd-107f-459f-8f96-b27a3ebc4591.png">

**Comment by Hyyfit** [comment]
好的， 感谢建议， 这个我们会放到v3.0讨论规划。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
