### ISSUE TITLE
[BUG] 文件管理拉取git文件存在三问题

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23502]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

正常输入下面的路径格式文件可拉取：
![image](https://user-images.githubusercontent.com/103925124/230822732-d94e2c4d-c6c5-4796-99b5-a46b81d6d418.png)
文件路径存在空格时，提示文件不存在，应该处理掉空格后拉取
![image](https://user-images.githubusercontent.com/103925124/230822554-3fb47d30-2848-4dbd-8438-c7832a98180d.png)
仓库跟路径下的文件，如果加/会提示文件不存在，此处需要处理下或验证/提示下用户输入的格式
![image](https://user-images.githubusercontent.com/103925124/230822596-31e2fe33-97f5-402e-be8a-b2d15f94096f.png)
预览git文件时，未显示文件分支和文件路径，不方便用户**追根溯源**
![image](https://user-images.githubusercontent.com/103925124/230822802-282910a2-45f6-4842-bb9b-f4449788e336.png)

### 重现步骤

文件管理拉取git文件存在三问题

**Comment by zrfit** [comment]
您好，感谢您的反馈！
经沟通问题处理结果如下：
1.文件路径带空格： github允许这样的文件名字存在，所以这个不处理。
2.文件带路径符号： 用一个问号tips提示： 根目录无需附带路径分隔符/。
3.文件详情里的分支信息： 在第三行加入分支信息。
问题2和3计划在v2.9修复。
