### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#23505]
### MeterSphere 版本

v2.8.0-ac76fee1

### 请描述您的需求或者改进建议

ms平台关联禅道后，在ms平台上创建用例关联需求的时候，建议‘关联需求’下拉选项展示形式优化增加需求ID的展示，完整展示为‘需求ID-需求标题’，下拉框支持按需求ID或者需求标题模糊搜索匹配。

**Comment by Hyyfit** [comment]
感谢建议， 我们在v3.0版本，对于关联需求的页面会重新设计，最终展示的效果会跟2.8版本的关联测试一样，以列表的方式展示更多的信息。并且在选择关联的时候，选项也可以支持需求ID的展示，也可以支持模糊搜索。
如果您还有其他的信息需要展示，也可以补充，我们在优化的时候会考虑的，非常感谢您的反馈。
