### ISSUE TITLE
[BUG] 【测试跟踪】从1.20.20升级到2.8.1版本，在1.20.20版本测试计划用例执行上传的截图和评论，在2.8.1版本查询不到

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23500]
### 联系方式

82973834@qq.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

从1.20.20升级到2.8.1版本，在1.20.20版本测试计划用例执行上传的截图和评论，在2.8.1版本查询不到

### 重现步骤

1.准备一个1.20.20环境
2.创建一个测试计划并关联功能用例
3.测试计划的功能用例，上传截图，并在提交评论
4.将1.20.20升级到2.8.1
5.查看升级的测试计划

### 期待的正确结果

1.升级到2.8.1，之前测试计划功能用例执行时，上传的截图和评论可以查到

### 附加信息

1.20.20版本
<img width="1177" alt="126923b575e24758e5f046982bea78c" src="https://user-images.githubusercontent.com/45531073/230820131-4708cf56-34fa-4cee-8109-00d1d7ef56df.png">

<img width="932" alt="1b5826e1a5b17264c18d453875398db" src="https://user-images.githubusercontent.com/45531073/230820169-28677a5d-4239-4b57-beac-e77456a9850a.png">

<img width="1177" alt="26e422bdfeb0a33f8355c6e6c57d75b" src="https://user-images.githubusercontent.com/45531073/230820190-a0982bf7-27cb-4e12-89e4-b60bf9bd99b6.png">

升级到2.8.1版本

![image](https://user-images.githubusercontent.com/45531073/230821175-f533ebcc-86f6-4b88-b41d-e41cf880f1a0.png)
![image](https://user-images.githubusercontent.com/45531073/230821266-8c189667-7b4c-49b1-a1bf-2aeff09da873.png)

<img width="1341" alt="6c3ee3b6cfe0f7a2929c12fe48ccbbe" src="https://user-images.githubusercontent.com/45531073/230820803-f1f3434c-5d2e-4545-912f-7f07ac4f1e41.png">

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、v1.20.20版本-测试计划中的功能用例执行的评论-并未区分评论类型；
2、而2.8.1计划中的评论对评论类型进行了区分（用例评论、执行评论、评审评论、全部评论）。
3、历史数据无评论类型-导致升级后计划中的评论无法区分类型，所以出现了该问题，计划v2.9修复该问题。
