### ISSUE TITLE
[BUG]UI自动化后置脚本在for each循环中无法使用环境变量

### ISSUE THREAD

**Issue by sky84892070** [metersphere/metersphere#23501]
### 联系方式
18192631378

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

[BUG] UI自动化后置脚本在for each循环中无法使用环境变量

### 重现步骤

1、在"工作空间” -> "环境列表"，中选择一个环境，配置“通用环境”的“应用环境” -> "场景变量" WEBADD -> "类型" 字符串 ->"https://blog.csdn.net/"
2、在 “UI 测试" -> “UI自动化” -> "场景" -> "场景步骤" -> 增加"ForEach"
3、在“ForEach循环中”增加“浏览器操作”步骤，并添加后置脚本；
4、在后置脚本中使用环境变量“${WEBADD}

期望结果： 在forEach循环中，后置脚本中使用环境变量可以生效。
实际结果： 在forEach循环中，后置脚本中使用环境变量不生效，场景变量可以正常使用。
### 期待的正确结果

期望结果： 环境变量可以生效。

### 相关日志输出

```shell

```

**Comment by zrfit** [comment]
您好！感谢您的反馈！将foreach的引用和后置脚本引用私发我下，看下是否引用正确。

**Comment by zrfit** [comment]
后置脚本如下方式引用环境变量失败，如您的脚本和下面引用方式不同，也可提供下我们尝试复现，计划v3.0规划修复。
var url=${WEBADD};
console.info(url);
return url;
