### ISSUE TITLE
[FEATURE]建议新增标签库。配置标签时可以从标签库中进行选择维护

### ISSUE THREAD

**Issue by Walter-Shui** [metersphere/metersphere#2350]
建立一个标签库，在编辑用例的时候，可以下拉框选择标签，标签人人都可以用，但是标签库不是所有人都有权限增删改
批量编辑的时候，目前只有用例等级，类型，测试方式，维护人，建议增加批量编辑标签的功能。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
