### ISSUE TITLE
[BUG]测试计划执行时选择失败重试，导致计划中接口脚本的循环没有被执行完全。如果不选择失败重试则没有问题

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#23509]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

测试计划执行时选择失败重试，导致计划中接口脚本的循环没有被执行完全。如果不选择失败重试则没有问题。同一个接口在接口自动化中执行也没有问题。怀疑是2.8.1版本修复之前  失败重试的debug问题造成新bug的，请排查。
<img width="859" alt="89dd12fce4fec4e5a3851b849cbe1ae" src="https://user-images.githubusercontent.com/83771182/230839115-1136dd62-f57f-44d0-bc10-2a7dc99a4175.png">

### 重现步骤

测试计划执行时选择失败重试，导致计划中接口脚本的循环没有被执行完全。如果不选择失败重试则没有问题

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，计划于v2.9修复

**Comment by 13290445582** [comment]
v2.9.0已修复
