### ISSUE TITLE
[BUG]功能用例-测试计划执行时，自定义字段文本框输入{}会显示为[object Object]

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23515]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

功能用例-测试计划执行时，自定义字段文本框输入{}会显示为[object Object]

### 重现步骤

1.功能用例自定义字段文本框输入{}，功能用例正常展示
![image](https://user-images.githubusercontent.com/103627487/230848649-2542ba83-a23a-497b-870c-a1348c93578d.png)
2.添加测试计划执行，显示为[object Object]
![image](https://user-images.githubusercontent.com/103627487/230848773-948704c9-b52a-4bb5-a867-be4a6182110f.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
最新版本已修复
