### ISSUE TITLE
[BUG]从 1.20.21-lts-b1 导出的接口，在2.8.1 版本内导入，提示接口导入成功，但实际上并没有接口被导入。

### ISSUE THREAD

**Issue by huskiesir** [metersphere/metersphere#23514]
### 联系方式

1832025651@qq.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

从 1.20.21-lts-b1 导出的接口，在2.8.1 版本内导入，提示接口导入成功，但实际上并没有接口被导入。
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/45967454/230843617-b87f528a-8ad5-4f6b-bb15-29f27608f871.png">

### 重现步骤

从 1.20.21-lts-b1 导出的接口，在2.8.1 版本内进行接口导入

### 期待的正确结果

应该能确保导入成功，且ms能兼容低版本。

**Comment by 13290445582** [comment]
感谢您的反馈，未复现该问题。
1.导入时是否选择了模块？
2.导入的接口在当前项目下是否 存在？
3.导入模式选择的为覆盖还是未覆盖？

**Comment by huskiesir** [comment]
导入模式选择的未覆盖，其他选择默认

**Comment by youliyuan-fit2cloud** [comment]
你好，建议在项目设置-应用管理-接口测试-开启下图的开关试试导入，可能是有重复的接口导致的和项目中已存在的接口对比一下。如果还是有问题方便的话把接口文件发出来，我们再尝试复现。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
