### ISSUE TITLE
[BUG]场景A中导入场景B,场景B中有csv文件，在场景A中删除原场景变量后，再上传一直提示文件不存在

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23513]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.21-lts

### 使用外置数据库

否

### 问题描述

场景A中导入场景B,场景B中有csv文件，在场景A中删除原场景B上传的csv文件后，再上传调试一直提示文件不存在

### 重现步骤

1.创建场景，场景中导入场景，
![image](https://user-images.githubusercontent.com/103627487/230840671-3002eccc-8bb7-4318-a4df-afbe7419cd4b.png)
2.查看场景变量，并删除csv文件
![image](https://user-images.githubusercontent.com/103627487/230840754-c5847fe6-65b9-49d2-9537-1b211efd5bb4.png)
![image](https://user-images.githubusercontent.com/103627487/230840894-a5a741c9-9825-4a71-9ea7-3a293e2771a2.png)
3.场景设置中设置的是
![image](https://user-images.githubusercontent.com/103627487/230842047-9dae3f20-a2eb-4f22-9f70-4dc8613d6a12.png)
4.再次上传文件后保存调试提示“csv文件不存在”
![image](https://user-images.githubusercontent.com/103627487/230842150-755b7ad4-6862-450f-b29c-b278fe7452b5.png)
5.关闭场景再次打开，csv文件显示如图
![image](https://user-images.githubusercontent.com/103627487/230842324-7e3917dd-9625-464e-90d0-ef4a52a68f81.png)
6.删除时提示，CSV文件：【 undefined 】
![image](https://user-images.githubusercontent.com/103627487/230842407-27d0cd41-b79c-4a12-8e83-1f9ba0b44a96.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v1.20.22修复。
