### ISSUE TITLE
[BUG]swagger文件导入不成功

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#23524]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

是

### 问题描述

![图片](https://user-images.githubusercontent.com/23067502/230873577-bcb5236f-f6f8-4f8a-9322-88bc19985327.png)

### 重现步骤

具体测试文件已邮件,邮箱2297310871@qq.com

**Comment by zrfit** [comment]
您好，感谢您的反馈！已邮件给您，辛苦将邮件附件发下，我们尝试去复现。

**Comment by xiaochongzi-ling** [comment]
多谢：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]swagger文件导入不成功 (Issue #23524)





 
您好，感谢您的反馈！已邮件给您，辛苦将邮件附件发下，我们尝试去复现。

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.9修复。
