### ISSUE TITLE
[FEATURE]创建场景页面，用例标题显示宽度是否可调整下？

### ISSUE THREAD

**Issue by abeelan** [metersphere/metersphere#23528]
### MeterSphere 版本

2.8

### 请描述您的需求或者改进建议

如图
<img width="920" alt="image" src="https://user-images.githubusercontent.com/34361264/230879303-765472b2-f948-4387-bcee-cc1fbe479019.png">

后面宽度还挺富裕呢，不遮挡用例执行结果就 OK 吧，试了下 22 就差不多哈

另外显示不全的话，加 `...` 做个截断如何，直接截断 UI 有点逼死强迫症哈哈哈（其实还好哈）

**Comment by Hyyfit** [comment]
好的，我们3.0的UX会优化这个页面，尽可能多的展示用例的名称，感谢您的反馈
