### ISSUE TITLE
[BUG]接口定义导入swagger文件，导入模式选择覆盖或者不覆盖都会新增接口

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#23542]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

 v2.8.0-ac76fee1

### 使用外置数据库

是

### 问题描述

![图片](https://user-images.githubusercontent.com/23067502/231028071-fb155bc8-2982-468a-a06d-c4c5b4d2ac79.png)

### 重现步骤

1.导入一份swagger文件，开启URL可重复。
2.导入模式为覆盖，重新导入；
3.导入模式为不覆盖，重新导入。

### 期待的正确结果

覆盖或者不覆盖的情况下，已经存在的接口都不应新增：
![图片](https://user-images.githubusercontent.com/23067502/231028487-35dbf801-2619-492a-bf09-2feb14ab3d85.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已邮件给您，辛苦将邮件附件发下，我们尝试去复现。

**Comment by xiaochongzi-ling** [comment]
多谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口定义导入swagger文件，导入模式选择覆盖或者不覆盖都会新增接口 (Issue #23542)





 
您好，感谢您的反馈！已邮件给您，辛苦将邮件附件发下，我们尝试去复现。

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，计划v2.9修复。
