### ISSUE TITLE
[BUG][接口自动化]循环控制器，ForEach模式，循环开启失败

### ISSUE THREAD

**Issue by yangfan112** [metersphere/metersphere#23543]
### MeterSphere 版本

 v2.8.1-26ae5c20

### 使用外置数据库

否

### 问题描述

接口自动化页面，场景配置中，循环控制器在ForEach模式下，接口不会发起请求，循环没有开启
![image](https://user-images.githubusercontent.com/48746721/230881792-7a8e9609-e376-4ff4-a810-192d27fc7a87.png)
![image](https://user-images.githubusercontent.com/48746721/230881865-1bdf9657-ba6c-4dbc-bf61-37f69c1ecc1a.png)

### 重现步骤

1、访问接口自动化页面
2、添加循环控制器，控制器下添加接口请求
3、点击ForEach模式
4、保存后，点击调试

### 期待的正确结果

ForEach循环开启，正确遍历csv文件内容

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题已复现，计划v2.9修复。
