### ISSUE TITLE
[BUG]当UI测试场景多次循环时包含if等流程控制时，测试报告显示的逻辑有问题

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#23541]
### 联系方式

张树彬

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

UI测试场景设置了两次循环，且每次循环分别满足if和else条件，在测试报告中只显示了一次执行结果，这样看不出来两次循环的过程中是否准确的执行了if和else两个不同的流程。
应该展示两次执行结果，比如：
第一次循环满足else，则执行else流程，未执行if流程；
第二次循环满足if，则执行if流程，未执行else流程。

### 重现步骤

1. 创建UI自动化场景，设置foreach循环（引用变量里包含两个值，执行两次）
2. 在foreach里分别设置if和else流程
3. 设置第一次循环满足else条件，第二次循环满足if条件
4. 执行后在报告中无法查看到两次循环所执行的流程，逻辑不完整

### 期待的正确结果

在报告中可以清晰的看出每次循环所执行的流程

### 附加信息

![image](https://user-images.githubusercontent.com/77324661/230910404-25fb30f8-f405-44de-9b8f-cb7fb6509924.png)

![1681133566111](https://user-images.githubusercontent.com/77324661/230911124-a6f9af16-ee36-4230-b43f-1df878b1b416.jpg)

**Comment by zrfit** [comment]
您好，感谢您的反馈！循环报告显示的问题为已知问题，计划在v3.0统一优化报告显示逻辑。
