### ISSUE TITLE
[QUESTION]Found when try to refresh the test plan detail page,there will be a update testPlan http-call.I wan to know waht is the http-call use for

### ISSUE THREAD

**Issue by lmtoc** [metersphere/metersphere#23553]
### 请描述您的问题

hello maintainers, we build a mertersphere platform for ourself use based on 2.0.0 version;
and when I use the test plan part ,I found there will always be a http-call like the curl behind,and I removed the ip
and some other data:

```
curl 'http://$host:8081/test/plan/edit' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'CSRF-TOKEN: xxxxxx=' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: MS_SESSION_ID=xxxxxxxx' \
  -H 'Origin: http://$host:8081' \
  -H 'PROJECT: $projectId' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://$host:8081/' \
  -H 'User-Agent: $ua' \
  -H 'WORKSPACE: $workSpaceId' \
  --data-raw '{"id":"$testPlanId","updateTime":$updateTimeMillSecs}' \
  --compressed \
  --insecure
```

its a post call,and the body just 
`{"id":"$testPlanId","updateTime":$updateTimeMillSecs}`

the page is `http://$host:8081/#/track/plan/view/$testPlanId`

I check the api in backend module,and it is a api for update testPlan so I want to know what is  this http-call for,is it a bug?

**Comment by song-tianyang** [comment]
Thank  you, bro

It's not a bug. We want automatic statistics some information about test plan ,  like status.  So this  http-call
 is our triggers.

Don't worry be happy!  LOL

**Comment by lmtoc** [comment]
thx
