### ISSUE TITLE
[BUG]复制功能用例，偶发字段回显不正确问题

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23552]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.21-lts

### 使用外置数据库

否

### 问题描述

复制功能用例，偶发字段回显不正确问题

### 重现步骤

1.复制功能用例，责任人，用例状态，用例等级显示不正确（是偶发的）
![image](https://user-images.githubusercontent.com/103627487/231042232-ab128ff8-79f3-4011-9196-ea9299ffa707.png)
![image](https://user-images.githubusercontent.com/103627487/231042469-2caf0530-c0b9-4492-8eeb-d47ffcc158ba.png)

**Comment by meijieDouDou** [comment]
我和客户在lts版本均有复现，是偶发的，频率也不高，lts版本多试几次呢

**Comment by 13290445582** [comment]
建议升级到最新版本，如果再次出现请重新提issue，感谢理解和支持～
