### ISSUE TITLE
[FEATURE]优化：测试用例管理可以关联禅道 缺陷和需求，但是接口失败提交bug不能这样关联，期望接口自动化、接口case也可以设置禅道的需求、缺陷 的关联关系

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#23576]
### MeterSphere 版本

2.8.1

### 请描述您的需求或者改进建议

背景：测试用例管理可以禅道关联缺陷和需求，但是接口失败提交bug不能这样关联，不方便做统一缺陷-用例-需求的统一管理管理
期望：接口自动化、接口case也可以设置禅道的需求、缺陷 的关联关系 做统一管理

![Uploading 接口自动化、接口case希望可以设置禅道的需求、缺陷 的关联关系设置，同测试用例管理.png…]()

### 请描述你建议的实现方案

接口自动化、接口case也可以设置禅道的需求、缺陷 的关联关系 做统一管理 同用例管理

**Comment by xhy12** [comment]
![接口自动化、接口case希望可以设置禅道的需求、缺陷 的关联关系设置，同测试用例管理](https://user-images.githubusercontent.com/43202800/231120674-37361dbc-cb48-4bd1-807f-9af8bb6cce6d.png)

**Comment by Hyyfit** [comment]
好的， 感谢建议， 这个我们会放到v3.0讨论规划。
