### ISSUE TITLE
[FEATURE][性能测试]性能测试脚本依赖的 jar 包可以不用每个脚本都加载一遍，做统一管理

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#23571]
### MeterSphere 版本

v2.6.1

### 联系方式

ke-liang

### 请描述您的需求或者改进建议

现在有 N 多个性能测试脚本，经过一段时间运行执行更新了签名算法，依赖的 jar 包也随之做了变化，增多了一个 jar 包，即之前脚本依赖 A jar，A jar 依赖 B jar，现在变成了个 A jar 依赖 B jar 和 C jar，我需要把每一个脚本都添加一遍新增的 B jar 包

改进建议：
脚本所依赖的 jar 包可以统一管理，存放在一处即可，就像放在 jmeter 的 lib/ext 下一样

### 请描述你建议的实现方案

现在有 N 多个性能测试脚本，经过一段时间运行执行更新了签名算法，依赖的 jar 包也随之做了变化，增多了一个 jar 包，即之前脚本依赖 A jar，A jar 依赖 B jar，现在变成了个 A jar 依赖 B jar 和 C jar，我需要把每一个脚本都添加一遍新增的 B jar 包

改进建议：
脚本所依赖的 jar 包可以统一管理，存放在一处即可，就像放在 jmeter 的 lib/ext 下一样

**Comment by liuruibin** [comment]
您好，鉴于您的需求，您可能需要一个定制的jmeter镜像
1. 下载镜像构建文件 https://github.com/metersphere/jmeter-image
2. 定制您的镜像 例如加入jar 修改脚本 修改默认的jmeter.properties等
3. 制作镜像 docker build 
4. 上传到您的镜像仓库或做成tar复制到资源池进行docker load
5. 在资源池配置中输入新镜像的tag，重新执行测试即可使用您制作的镜像啦
