### ISSUE TITLE
[BUG]文件管理，git 拉取的文件的 commitId 取值有误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#23587]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

文件管理，git 拉取的文件的 commitId 取值有误，目前展示的是仓库的最新的commitId，应该是拉取的对应文件的最新的commitid。

### 重现步骤

同一个仓库，先修改文件A，push 后是 commit1； 再修改文件B, push 后是 commit2； 然后拉取文件A，展示的是 commit2

**Comment by youliyuan-fit2cloud** [comment]
v2.9中已修复。
