### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by yaowei666** [metersphere/metersphere#23585]
### MeterSphere 版本

v2.8.1

### 联系方式

376937872@qq.com

### 请描述您的需求或者改进建议

问题需求：
在接口用例中，需要添加已存在的API接口，作为前置和后置脚本，但是导入API接口进来后，发现都是代码格式的脚本，并不是所有的测试人员都能看懂这些代码；

预期：
希望能做到倒入进来后，做到直观的界面形式，测试人员可以直接操作传参和赋值，便于在项目组内进行推广和使用；

**Comment by Hyyfit** [comment]
好的， 感谢建议， 这个我们会放到v3.0讨论规划。

**Comment by luty2018** [comment]
您好， 如果您是在前置脚本中引入的接口用例， 这里是以脚本的方式去执行的，所以要把接口翻译成脚本才能运行
