### ISSUE TITLE
[BUG]  git文件上传不同分支，同一路径文件拉取失败报文件已存在

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23586]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

git文件上传不同分支，同一路径文件拉取失败报文件已存在

### 重现步骤

同样的路径master分支已拉取成功，

test分支拉取时报文件已存在：
![image](https://user-images.githubusercontent.com/103925124/231197876-9656d3c8-dd05-4442-8808-f682aee15aaa.png)

### 期待的正确结果

不同分支，同一路径的文件，可拉取成功，页面并作出区分

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0中已修复。
