### ISSUE TITLE
[BUG]同样的beanshell 脚本2.6可以执行 2.8.1就不行了

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#23588]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

long nowTime =System.currentTimeMillis();
long todayStartTime =nowTime - ((nowTime + TimeZone.getDefault().getRawOffset()) % (24 * 60 * 60 * 1000L));
long tomorrowStartTime =todayStartTime + 86400000;
vars.put("tomorrow_time",String.valueOf(tomorrowStartTime));

报错

![image](https://user-images.githubusercontent.com/43202800/231337754-eb4dc4a0-0b52-448f-be0e-77ce417fa31f.png)

### 重现步骤

如上同样的beanshell 脚本2.6可以执行 2.8.1就不行了

### 期待的正确结果

没有变化应该可以执行才对

**Comment by youliyuan-fit2cloud** [comment]
你好， v2.8 以后版本升级 到jdk17 导致的，可以参考如下代码使用。
import org.python.icu.util.TimeZone;
long nowTime =System.currentTimeMillis();
long todayStartTime =nowTime - ((nowTime + TimeZone.getDefault().getRawOffset()) % (24 * 60 * 60 * 1000L));
long tomorrowStartTime =todayStartTime + 86400000;
vars.put("tomorrow_time",String.valueOf(tomorrowStartTime));

**Comment by xhy12** [comment]
感谢
