### ISSUE TITLE
[BUG]缺陷状态更新消息通知有误，状态一直显示为new

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#23595]
### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

缺陷在进行更新，变更缺陷状态时，消息通知中缺陷状态一直显示为：new，显示有误
(备注：同时建议消息通知中的缺陷状态语言类型与平台上的语言类型保存一致)

### 重现步骤

见问题描述

### 附加信息

![image](https://user-images.githubusercontent.com/92150453/231367891-e7dcce89-bb66-4dfa-95f4-4ec09c9c7907.png)
![image](https://user-images.githubusercontent.com/92150453/231368016-95ad3816-28da-4096-ae58-7f46f3d6af29.png)
![image](https://user-images.githubusercontent.com/92150453/231367944-57a94dc5-c756-450d-99c7-bf9eb1c65ed3.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。计划于v2.9.0修复

**Comment by youliyuan-fit2cloud** [comment]
消息设置中模版字段 “状态” 获取的结果和列表不一致，该字段不是实际缺陷状态，下个版本模版删除该字段。
