### ISSUE TITLE
[QUESTION]上一个接口请求的参数值，下一个接口引用不能正确显示

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#236]
**请描述您的问题.**

![image](https://user-images.githubusercontent.com/53041390/90208923-a06a6800-de1c-11ea-930e-ad537730a421.png)
![image](https://user-images.githubusercontent.com/53041390/90208946-b4ae6500-de1c-11ea-9c22-5fda3d0f51dd.png)
你好，我在下一个接口引用参数值时，还是不能把参数内容引用过去。
![image](https://user-images.githubusercontent.com/53041390/90208990-cc85e900-de1c-11ea-8b8a-460b27b49744.png)
在网上jiancha检查时，语句是可以提取到对应内容的。
这个是什么情况呀？

**Comment by wangzhen-fit2cloud** [comment]
你可以试试这个正则
```
Set-Cookie:\stoken=Value=(.+?);
```

**Comment by chenqiunuan** [comment]
这个就可以。做了什么限制吗？
