### ISSUE TITLE
测试计划 -查看测试报告 开放的问题与已关闭的问题颜色相同的，建议调整。 缺陷与Jira系统进行了关联。

### ISSUE THREAD

**Issue by ZhiChengXin** [metersphere/metersphere#23605]
### 联系方式

15000362081@163.com

### MeterSphere 版本

  v2.8.0-39aed27e

### 使用外置数据库

否

### 问题描述

![5a6909f87ccd4a43f5257c445fef8bf](https://user-images.githubusercontent.com/114223168/231403603-6a8ef4d9-65b9-4e75-897d-b124025f98cb.png)

### 重现步骤

![5a6909f87ccd4a43f5257c445fef8bf](https://user-images.githubusercontent.com/114223168/231403603-6a8ef4d9-65b9-4e75-897d-b124025f98cb.png)

**Comment by 13290445582** [comment]
您好，您反馈的问题未复现，邮件已发送给您，辛苦将相关配置操作与复现发送，感谢

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
