### ISSUE TITLE
[BUG]大场景中包含多个场景，某个场景中包含的场景断言会对其他子场景也生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#23602]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.21-lts

### 使用外置数据库

否

### 问题描述

场景A里有场景断言
场景B里没有场景断言
把场景A导出JMX，然后再导入为一个新的场景C
然后在场景C里面再引用场景B
这时候场景断言对场景B也会生效，这是有问题的

### 重现步骤

1.场景A里有场景断言
场景B里没有场景断言
把场景A导出JMX，然后再导入为一个新的场景C
然后在场景C里面再引用场景B
这时候场景断言对场景B也会生效
2.
<img width="942" alt="65d4f0e449fc00419151dbf206b329e" src="https://user-images.githubusercontent.com/88763608/231399646-4f397382-3be2-4b31-ad34-1dbb8f94692f.png">
<img width="758" alt="1cb59da7f0ef891db79a94b70045b95" src="https://user-images.githubusercontent.com/88763608/231399674-44b32242-556c-4d53-84a9-557cbdcf2ce0.png">

### 期待的正确结果

场景A的场景断言不应该对场景B生效

**Comment by youliyuan-fit2cloud** [comment]
你好，当前问题原因是从ms平台导出的jmx会自动生成线程组，如果再导入jmx，然后在这个新的场景增加场景步骤，执行的时候会把这个步骤合到同一个线程组里执行，导致这个jmx场景断言成了全局的断言，会对和这个jmx同级别的步骤生效。
v2.8以上版本中针对这种问题做了相应的优化，建议升级到最新版本。
