### ISSUE TITLE
[BUG]json文档结构校验，正则匹配数据，不是所有的值都符合校验规则，断言也成功了

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23615]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

json文档结构校验，正则匹配数据，不是所有的值都符合校验规则，断言也成功了

### 重现步骤

1.  json文档结构校验,不是所有的值都符合校验规则，断言也成功了，应该是都符合这个正则表达式才对
![image](https://user-images.githubusercontent.com/103627487/231454146-25e323c7-0e5a-49c2-b265-d8142f0310be.png)
![image](https://user-images.githubusercontent.com/103627487/231454907-3ddb834f-2d4d-4dbf-bb99-3ed146715dbb.png)
2. 经验证是满足其中一个值的校验，就断言成功，应该是都符合这个正则表达式才对
![image](https://user-images.githubusercontent.com/103627487/231455024-3daf51cb-a0b9-45b1-9674-fef3e6a6d2c3.png)
![image](https://user-images.githubusercontent.com/103627487/231455122-e793824b-e56e-44ed-8e75-a329ad118bfc.png)

### 期待的正确结果

期望与官网的jsonschema也一样都符合这个正则表达式，才断言成功

**Comment by scarletyyh** [comment]
您好，json文档结构校验方式下，这种只能校验data里面的一个数组，如果您需要匹配所有数数组，可以使用jsonpath方式。

**Comment by scarletyyh** [comment]
您好，json文档结构校验方式下，这种只能校验data里面的一个数组，如果您需要匹配所有数数组，可以使用jsonpath方式。

**Comment by meijieDouDou** [comment]
是一个数组，但是满足数组中一个值的校验，就断言成功，
