### ISSUE TITLE
[BUG]UI测试-环境里定义的数组，后置脚本获取不到，场景里定义到数组，就可以获取到

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23611]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

UI测试-环境里定义的数组，后置脚本获取不到，场景里定义到数组，就可以获取到

### 重现步骤

1. 环境里定义数组
![image](https://user-images.githubusercontent.com/103627487/231439264-540f1d2c-01bb-4850-a2d3-9cbe42a5fd76.png)
2.场景里后置脚本引用
![image](https://user-images.githubusercontent.com/103627487/231439450-3c3e003e-6543-4729-9f1e-660bd0fd8574.png)
3.查看执行结果，未获取到
![image](https://user-images.githubusercontent.com/103627487/231439634-1b3ce9f0-1172-47da-a222-9865f28657cf.png)

以下是场景里设置数组，能正常获取到
![image](https://user-images.githubusercontent.com/103627487/231439799-25b6e3af-fdb7-40d5-ae3f-9b4e9dafe0ed.png)
![image](https://user-images.githubusercontent.com/103627487/231439915-d372ec4e-f796-4b0d-9d6a-3eaaa42a5f5c.png)
![image](https://user-images.githubusercontent.com/103627487/231440130-92fda8d6-1540-4bf5-9042-3cca171d815e.png)

但是场景里后置脚本也获取不到整个数组，获取后结果为{}
![image](https://user-images.githubusercontent.com/103627487/231440470-81d0845d-b26e-4897-9c56-d376d199f2b5.png)
![image](https://user-images.githubusercontent.com/103627487/231440623-86f02cdc-0d6d-4e52-b5b5-2aae69c36a0f.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈!第一个问题已复现，计划v2.9修复；第二个问题在v2.9未复现，待v2.9发布后可升级验证。
