### ISSUE TITLE
[BUG]测试计划执行，资源池取消勾选，选中的资源池未清空

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23610]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

测试计划执行，资源池取消勾选，选中的资源池未清空

### 重现步骤

1.执行测试计划，勾选资源池，再取消勾选，选中的资源池未清空，报告里还会显示资源池
![image](https://user-images.githubusercontent.com/103627487/231434870-8155a79b-2f43-4b05-a4b9-0a16e1043221.png)
![image](https://user-images.githubusercontent.com/103627487/231435317-89b3af6b-6da9-47b8-bf73-30f04fda58d0.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.9.0已修复
