### ISSUE TITLE
[BUG]【在线等】docker-compose 版本与配置文件不兼容或配置文件存在问题，请重新安装最新版本的 docker-compose 或检查配置文件

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#23634]
### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

1、2.7.1升级到2.8.1
2、在线、离线都报错docker-compose 版本与配置文件不兼容或配置文件存在问题，请重新安装最新版本的 docker-compose 或检查配置文件

### 重现步骤

1、2.7.1升级到2.8.1
2、在线、离线都报错docker-compose 版本与配置文件不兼容或配置文件存在问题，请重新安装最新版本的 docker-compose 或检查配置文件

### 期待的正确结果

1、我是从1.0到2.0 一路走过来的
2、机器是全新，那么如果升级docker-compose也应该是你们一起弄
3、如果是修改yml版本3为2.1 也是啊

赶紧出方案怎么处理 ，卡住了

### 附加信息

![image](https://user-images.githubusercontent.com/19423100/231669525-59bcfd14-fd2d-4059-80a4-a6468dd7591d.png)
![image](https://user-images.githubusercontent.com/19423100/231669585-f446f419-7b92-42f2-a795-aaa8a0464cdb.png)

**Comment by liuruibin** [comment]
您好，我们不会对已安装的docker 和docker-compose进行修改。您可以自行修改yml中version为2.1然后执行msctl reload

**Comment by zhangzhaox** [comment]
把系统里原有的docker-compose 删除掉  再安装就可以了

**Comment by legend818** [comment]
> 您好，我们不会对已安装的docker 和docker-compose进行修改。您可以自行修改yml中version为2.1然后执行msctl reload

我是离线安装修改2.8.1的未2.1升级的。中间出现selenium arm服务没有被停止和移除。手动停止和删除的。 昨天都干完了，在线没有等到结果

**Comment by legend818** [comment]
> 把系统里原有的docker-compose 删除掉 再安装就可以了

昨天已经处理了，不是你这种方式，在线等好焦急啊。。。。 下个版本还是这个问题
=======================
应该是个缺陷吧

**Comment by youliyuan-fit2cloud** [comment]
> > 您好，我们不会对已安装的docker 和docker-compose进行修改。您可以自行修改yml中version为2.1然后执行msctl reload
> 
> 我是离线安装修改2.8.1的未2.1升级的。中间出现selenium arm服务没有被停止和移除。手动停止和删除的。 昨天都干完了，在线没有等到结果
> 
> ==================================================== 下个版本还会出现这个问题，应该是个缺陷

你好，下个版本不会出现了，之前的docker-compose版本太低了。
