### ISSUE TITLE
[BUG] 用例列表多个字段的列宽无法用鼠标拖动调节，如“标签”、“用例类型”、“执行结果”、“责任人”等

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23638]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

用例列表多个字段的列宽无法用鼠标拖动调节，如“标签”、“用例类型”、“执行结果”、“责任人”等

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/231682398-3e9ee058-0fef-435b-aecf-c0a47ecc7e72.png)

### 期待的正确结果

希望修复用例列表中字段的列宽拖动调节功能

**Comment by 13290445582** [comment]
感谢反馈，表头有固定间隔。
