### ISSUE TITLE
[BUG]设计场景用例时，无法禁用子场景下的子场景用例

### ISSUE THREAD

**Issue by wanhx829** [metersphere/metersphere#23645]
### 联系方式

wanhx1324@163.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

我在使用场景用例测试接口时，在场景用例中导入场景用例，则无法禁用场景用例下的场景用例。例如：
在场景用例4下有一个场景用例3，而场景用例3下还有场景用例2和场景用例1，则编辑场景用例4时，禁用场景用例1无法保存，请见下面的动图：
![问题1](https://user-images.githubusercontent.com/52766648/231714513-d2a11c53-04ba-4512-aaa7-f79d229098bf.gif)

### 重现步骤

1、创建四个场景用例：场景1，场景2
![image](https://user-images.githubusercontent.com/52766648/231715200-aec1539c-78bf-4835-986f-f31c17492ba6.png)
![image](https://user-images.githubusercontent.com/52766648/231715030-25c168af-2f3d-4c71-9162-d27d604fe8ba.png)
![image](https://user-images.githubusercontent.com/52766648/231715096-907b407b-3a39-4185-b522-5bf15eaf3058.png)
2、创建场景3用例：场景3，引用场景1，引用场景2
![image](https://user-images.githubusercontent.com/52766648/231715635-603ed1af-081b-4275-b2f5-1027a980a6f4.png)
3、创建场景4用例：场景4，引用场景3
![image](https://user-images.githubusercontent.com/52766648/231715845-8bb85cc3-fba9-4fac-bc83-5c0fc9c6e29b.png)
4、此时编辑场景4用例时，禁用场景1，禁用场景2则无法保存
![image](https://user-images.githubusercontent.com/52766648/231716740-71e7b4bd-9634-4436-8490-40cc02a8cea8.png)
![image](https://user-images.githubusercontent.com/52766648/231716889-cd7fa4af-86ce-4e25-9e8b-35076ee8cbd3.png)

### 期待的正确结果

1、可以正常启用禁用子场景下的子场景以及步骤
2、场景下引用场景，引用n层也能正常使用

**Comment by scarletyyh** [comment]
您好，感谢您的反馈！已复现该问题，计划v2.9修复。

**Comment by wanhx829** [comment]
![image](https://github.com/metersphere/metersphere/assets/52766648/dda4d94f-8efb-420b-be1f-acd0536317d0)
2.9版本只修复了保存的问题，但是执行调试时，禁用的步骤仍然继续执行
