### ISSUE TITLE
[BUG]通过 Chrome浏览器的selenium插件导出录制的脚本，导入至MS后步骤出现内容缺失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23647]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.21-LTS

### 使用外置数据库

否

### 问题描述

通过 Chrome浏览器的selenium插件导出录制的脚本，导入至MS后步骤出现内容缺失

在1.20.21-LTS版本中有问题，v2.8.1版本看起来没问题

### 重现步骤

通过 Chrome浏览器的selenium插件导出录制的脚本，导入至MS后步骤出现内容缺失

脚本如下

[test2.side.zip](https://github.com/metersphere/metersphere/files/11228224/test2.side.zip)

### 附加信息

1.20.21-LTS版本如下：
<img width="881" alt="image" src="https://user-images.githubusercontent.com/32027713/231927092-cd5aa4ac-117f-4e6f-ab98-317a17d9c5fd.png">

2.8.1版本如下：
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/32027713/231927372-ed58e30e-77b2-42a6-b221-eb726a36324e.png">

  selenium  IDE版本：
![image](https://user-images.githubusercontent.com/32027713/231927444-165639cf-a851-4ff4-8e6c-997f7f579d47.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！已复现该问题，计划v1.20.22修复。
