### ISSUE TITLE
[BUG]通过前置脚本，从请求中获取参数，用于生成报文中的参数。参数带不到请求报文的变量中，脚本见附件和截图

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#23646]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

通过前置脚本，从请求中获取参数，用于生成报文中的参数。参数带不到请求报文的变量中，前置脚本见附件。
![3122e3fdd4c4115139ed5256be732f0](https://user-images.githubusercontent.com/83771182/231758808-cbdc3ff8-32f9-4267-8cff-5534e92bd312.png)
[前置脚本(1).txt](https://github.com/metersphere/metersphere/files/11222179/1.txt)
修改前置脚本后，参数赋值正常了，见下图。
![17bc646c8bf16fd850f423ec5c8df31](https://user-images.githubusercontent.com/83771182/231759067-cd28ea5e-be60-4dc0-9c5c-b77e96d363b8.png)

### 重现步骤

通过前置脚本，从请求中获取参数，用于生成报文中的参数。参数带不到请求报文的变量中，前置脚本见附件。

**Comment by youliyuan-fit2cloud** [comment]
你好，看看控制台的日志有没有错误信息？

**Comment by yaoyi111** [comment]
![afe5d76950c2c51b81ab46325ce1747](https://user-images.githubusercontent.com/83771182/232030692-0976bb65-2987-4ed5-8b5c-f1dc72d30943.jpg)
String request=ctx.getCurrentSampler().getArguments().getArgument(0).getValue();
log.info("old request is:"+request);

是不是log.info代码有问题

**Comment by youliyuan-fit2cloud** [comment]
你好，我们这边场景没有复现该问题，方便的话把复现场景发给我们试试。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/232406766-90ae4576-3fe6-410e-b047-28e756170ae1.png)
下面这一行需要调整下位置，参考上图。
log.info("old request is:"+reqBodyJson.toString());

**Comment by youliyuan-fit2cloud** [comment]
该问题已解决，修改脚本后恢复正常。
