### ISSUE TITLE
[BUG]接口自动化调试点击停止，希望保留已执行步骤的执行结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23649]
### MeterSphere 版本

v2.8.1

### 联系方式

zhaojun@fit2cloud.com

### 请描述您的需求或者改进建议

有些用户步骤数很多，为了查看执行过程中的参数变化，但是又不想等所有步骤都执行完，会在某些步骤执行后停止调试，然后进行报告的查看与脚本的修改

### 请描述你建议的实现方案

1、接口自动化执行过程中，点击“停止”，希望可以在调试页面、调试历史两个至少保留一个已执行步骤的执行结果

2、对于调试过程中点击停止，在调试历史中无法打开内容，那么保存此条调试历史的意义是什么呢？
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/32027713/231930133-e12cf99d-3f79-4063-9dcc-7fb02855d138.png">

3、针对之前使用频率较高的模块，其中某些操作逻辑的调整或者修改，麻烦请产品同学慎重一下哈

使用习惯的调整过程会影响使用体验

**Comment by luty2018** [comment]
感谢建议， 我们会在v3.0讨论规划

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
