### ISSUE TITLE
[BUG]测试跟踪-测试计划，单独执行测试用例，执行完后结果没有同步。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23652]
### 联系方式

kaijie.yu@fit2cloud.com

### MeterSphere 版本

v1.20.21，v1.20.20

### 使用外置数据库

否

### 问题描述

1.测试跟踪-测试计划，单独执行测试用例，执行完后没有结果展示。

### 重现步骤

1.创建测试计划
2.测试计划里关联接口测试用例
3.单独执行接口，会提示执行成功，接口执行结果没有更新执行成功或者失败。
![image](https://user-images.githubusercontent.com/55130444/231936702-31ba11a2-30d0-4cbc-baa1-810ea8a9da91.png)

### 期待的正确结果
1.可以拿到执行结果展示。
_No response_

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划里面所有接口case都有该问题吗？
在接口定义-CASE页面执行该接口case是否能正常执行 ？

**Comment by kaijie-yu** [comment]
所有接口都是这样的，接口页面case可以正常执行，
后台ms-jmeter-run日志没有报错。
这里其实是执行完后，结果没有更新到页面上，一直显示未执行
