### ISSUE TITLE
[BUG]工作台->我的仪表盘->我创建的用例中，本周新增用例数量统计错误

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#23653]
### 联系方式

357861578@qq.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

前置条件：
1.一用户负责的项目在2023年2月20至2月22添加接口用例5个
2.当前系统时间是2023年4月14日
工作台->我的仪表盘->我创建的用例中，显示本周新增用例数量5

### 重现步骤

在工作台->我的仪表盘->我创建的用例中，查看本周新增用例数量

### 期待的正确结果

在工作台->我的仪表盘->我创建的用例中，显示本周新增用例数量为0

### 附加信息

[
![caseno](https://user-images.githubusercontent.com/130725706/231936758-8dccebde-42cc-43ab-a39c-36c4f96a50a7.png)
](url)

**Comment by 13290445582** [comment]
该问题未复现，建议更新最新环境尝试

**Comment by heavenlyye** [comment]
除了2.8.1还有最新的发布版本吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]工作台-&gt;我的仪表盘-&gt;我创建的用例中，本周新增用例数量统计错误 (Issue #23653)





 
该问题未复现，建议更新最新环境尝试

**Comment by 13290445582** [comment]
可以提供下服务器日志，先尝试下重启服务看能不能恢复正常。

**Comment by heavenlyye** [comment]
需要哪个服务的日志？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]工作台-&gt;我的仪表盘-&gt;我创建的用例中，本周新增用例数量统计错误 (Issue #23653)





 
可以提供下服务器日志，先尝试下重启服务看能不能恢复正常。

**Comment by 13290445582** [comment]
工作台日志

**Comment by heavenlyye** [comment]
不知道你能接收多大的附件







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]工作台-&gt;我的仪表盘-&gt;我创建的用例中，本周新增用例数量统计错误 (Issue #23653)





 
工作台日志

**Comment by 13290445582** [comment]
![image](https://user-images.githubusercontent.com/128017892/232015737-8fb06ba6-5cbb-457c-84aa-879df53f5f12.png)
请加下企业微信发送附件

**Comment by heavenlyye** [comment]
跟你们反馈一个问题及不容易了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]工作台-&gt;我的仪表盘-&gt;我创建的用例中，本周新增用例数量统计错误 (Issue #23653)





 

 请加下企业微信发送附件

**Comment by 13290445582** [comment]
抱歉，会为您尽快解决的

**Comment by 13290445582** [comment]
v2.9.0已修复
