### ISSUE TITLE
[FEATURE]希望对于新版本的模块列表显示及UI的步骤显示，可以把底色调深一点，方便操作

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23650]
### MeterSphere 版本

v2.8.1

### 联系方式

zhaojun@fit2cloud.com

### 请描述您的需求或者改进建议

希望对于新版本的接口及测试跟踪下的模块列表显示及UI的步骤显示，可以把底色调深一点，选中某个模块或者对于UI步骤中的启用禁用，颜色看起来差别很小，不是很方便操作

**Comment by luty2018** [comment]
这个自定义主题色是否能解决？
