### ISSUE TITLE
[BUG]有些参数需要里面带有\n才能成功，类似图片，但是复制进去调接口的时候，没有\n，然后一直调不通

### ISSUE THREAD

**Issue by yangbin941225** [metersphere/metersphere#2366]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
有些参数需要里面带有\n才能成功，类似图片，但是复制进去调接口的时候，没有\n，然后一直调不通。

**Bug 重现步骤**
1.  复制浏览器中控制台里获取的参数
2. 粘贴到metersphere对应的值里面
3. 调用接口
4. 参数中因为有隐藏参数调用失败

**期待的正确结果**
调试的时候，可以拉取放大值的输入框，方便调试，可以在metersphere中回车，后者默认将文本中间的\n带进去
接口调用成功

复制粘贴默认去掉值最后的跟着的隐藏参数
**截图**
![image](https://user-images.githubusercontent.com/81786635/116339458-09a9d400-a810-11eb-95ac-86f43436adde.png)

**Comment by zyyfit** [comment]
您好，能描述一下具体操作步骤吗？包括在哪个模块，哪个页面，什么地方填写的参数等

**Comment by yangbin941225** [comment]
六、交付实施：  甲方可按需向乙方采购交付实施服务，包括硬件设备到店后的安装、布线、调试、维修等劳务服务，甲方应积极协调、配合乙方的施工、安装、调试或维修，以确保项目的顺利进行，施工完成后甲方应安排门店在醒目位置张贴相应提示标识（由乙方随设备提供或甲方自行打印），因未按要求张贴标识产生的后果乙方不承担任何责任。七、不可抗力：  双方约定的不可抗力事件包括：战争、封锁、冲突、叛乱、罢工、雇主停工、内乱、骚动、政府行为、暴动、产品厂家原因，乙方的上游供应商的原因、严重火灾、水灾或被人们所不能控制的自然因素。由于不可抗力事件造成合同不能履行的，任何一方不需要承担违约责任。但不可抗力事件发生在任何一方违约后的，违约方不得以不可抗力事件主张免责。八、 保密义务：  在本合同及其附件有效期内以及有效期结束两年之内，甲方有义务对从乙方处得到的信息保密，信息包括但不限于产品价格、销售计划、奖励政策、客户清单、财务信息、技术秘密等，未经乙方书面许可，甲方不得向第三方透露本协议的条款。一经查实，泄露方应承担相应的赔偿责任。九、 争议解决：  当合同出现争议时，应协商解决。协商不成的，则由乙方所在地人民法院管辖。违约方除按照本合同约定承担违约责任外，还须向守约方支付守约方为实现债权而支付的一切费用，包括但不限于律师费、诉讼费等。十、 商誉维护：  双方均有义务维护对方商誉。任何一方不得以捏造事实、夸大缺陷或使用带有贬损意义的语言等方法诋毁对方或对方其它伙伴的产品质量或服务质量。 十一、附注：本合同有效期三年，自双方签字盖章之日起生效，若本合同到期时，仍有订单尚未履行完毕的，则合同有效期顺延至该等订单履行完毕之日止。合同扫描件具有与合同正本同等的效力，本合同一式两份。产品所有权（及风险）自乙方交付时转移，但甲方未履行支付全部货款义务的，货物所有权属于乙方所有。合同中所支付的一切费用均用人民币支付,并采用电汇或转帐支票方式汇到供方帐户。非因产品质量问题而产生的货物退换，由需方承担往返运费。因本合同有关的争议，首先由双方协商解决，协商不成的，任一方均可向乙方所在地人民法院提起诉讼。


参数就是这些。它有一定格式，像图片里的那样，所以需要一些\n参数。
模块还是接口自动化里面的场景，form data里






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月28日(星期三) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]有些参数需要里面带有\n才能成功，类似图片，但是复制进去调接口的时候，没有\n，然后一直调不通 (#2366)





 
您好，能描述一下具体操作步骤吗？包括在哪个模块，哪个页面，什么地方填写的参数等

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，请升级到最新版试一下，目前最新版是1.10.3，升级前请做好备份
