### ISSUE TITLE
[QUESTION]能够自动化抓包生成关联依赖的上一个接口返回的json字段路径以及参数变量，并且能够自动生成关联参数变量传入到下一个接口，全部自动化实现，无效手动关联可以吗？

### ISSUE THREAD

**Issue by cfy3133** [metersphere/metersphere#23665]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/43978367/231983665-bc52c72e-7d29-4e2a-a1b7-b35d890bfdec.png)

**Comment by luty2018** [comment]
暂时不支持。

**Comment by cfy3133** [comment]
后续可以支持吗

**Comment by luty2018** [comment]
需要看是否大家都有这个需求。

**Comment by cfy3133** [comment]
能够录制脚本，还不用手动关联参数，小白也可以用滴，就是不会做接口测试的小白都能上手，这种需求应该非常多人想用，只是没有好的开源平台而已滴，其实有个开源平台做出来了，但是不是很精确，而且易用性不是很好，所以问下您这个平台是否能做，谢谢！
以下是开源平台做的
![image](https://user-images.githubusercontent.com/43978367/234439689-0c315e78-0f79-4928-8880-c52565049e71.png)

**Comment by luty2018** [comment]
能发下项目地址吗

**Comment by cfy3133** [comment]
以下是开源项目地址：https://github.com/wuranxu/pity

**Comment by luty2018** [comment]
收到，谢谢
