### ISSUE TITLE
[BUG] 【接口测试】接口定义-tcp mock 后置脚本获取不到求内容

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23671]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

tcp mock 后置脚本获取不到求内容

### 重现步骤

1.创建一个tcp mock
2.填写请求内容
3.添加后置脚本获取请求内容
4.将获取到的请求内容做为返回内容

### 期待的正确结果

tcp mock能跟http mock一样，后置脚本能获取请求内容

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/231994387-025df997-8c66-48f6-b96f-a80589ec127e.png)
![image](https://user-images.githubusercontent.com/45531073/231994466-f0110b77-af33-4f83-8f6a-b18306541e65.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9支持。
