### ISSUE TITLE
[FEATURE] 响应内容框可以调整大小

### ISSUE THREAD

**Issue by hanchenglong001** [metersphere/metersphere#23673]
### MeterSphere 版本

v1.20-lts

### 联系方式

微信交流群53 all 　　　 　 　　 　👁_👁　: 

### 请描述您的需求或者改进建议

响应内容多行的时候无法完整的看到响应内容
![image](https://user-images.githubusercontent.com/56539098/232004332-2bd5264c-37cc-4c8c-9250-194f20b9d2f2.png)

### 请描述你建议的实现方案

可以自由的调整响应内容框的大小

**Comment by luty2018** [comment]
这个会在我们v3.0版本优化。
