### ISSUE TITLE
[BUG]接口自动化批量编辑环境保存后，自动化步骤内环境显示仍为之前保存的环境信息

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#23674]
### 联系方式

v2.8.1

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

接口自动化批量编辑环境保存后，自动化场景内环境显示仍为之前保存的环境信息

### 重现步骤

1、打开一个接口自动化场景，然后选择其中一个环境进行保存，并查看步骤内的域名信息

2、在列表中勾选批量编辑，选择编辑的属性字段  “环境”

3、选择其他环境并保存

4、再次打开该接口自动化，查看步骤中的域名信息，发现还是批量编辑之前的环境域名信息

5、实际发起调试却是批量编辑后的环境，对用户产生误导，希望统一一致

### 附加信息

批量编辑之前：
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/32027713/232009657-925a6dda-b93e-4a04-ad43-8d051ae0dc2d.png">

批量编辑：
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/32027713/232009968-ef280df2-5f80-481e-b57b-1f4078819327.png">

批量编辑之后：
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/32027713/232010245-84cb76f6-3c19-44ae-8649-1c9006b8e0e6.png">

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.9.0已修复
