### ISSUE TITLE
[BUG]复制的参数，有些会在末尾自动带有\r的隐藏参数，导致接口运行失败

### ISSUE THREAD

**Issue by yangbin941225** [metersphere/metersphere#2367]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
复制的参数，有些会在末尾自动带有\r的隐藏参数，导致接口运行失败；
**Bug 重现步骤**
1.  复制浏览器中控制台里获取的参数
2. 粘贴到metersphere对应的值里面
3. 调用接口
4. 参数中因为有隐藏参数调用失败

**期待的正确结果**
正确情况下应该是什么样的？
复制粘贴默认去掉值最后的跟着的隐藏参数
接口调用成功
**截图**
![image](https://user-images.githubusercontent.com/81786635/116338623-9eabcd80-a80e-11eb-8ed6-65dd53c503bc.png)

**Comment by zyyfit** [comment]
您好，能具体描述一下操作步骤吗

**Comment by yangbin941225** [comment]
就是通过控制台抓取了接口，然后直接复制form data里的参数，一个个的粘贴到平台的接口自动化场景里，然后调试，运行不通过。找后台看发现一些数字或者纯文字的参数后面会有/r的隐藏参数，导致没通




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月28日(星期三) 晚上7:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] [BUG]复制的参数，有些会在末尾自动带有\r的隐藏参数，导致接口运行失败 (#2367)





 
您好，能具体描述一下操作步骤吗

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/2366
