### ISSUE TITLE
[FEATURE]文件上传希望能支持参数化

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#23670]
### MeterSphere 版本

v2.7.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/111938588/231989219-1dcf58eb-b6cb-4176-8075-95ff58f4d850.png)
文件上传相关的接口，即类型是file，然后需要手动上传一个文件的，希望能支持参数化。比如有情况是先去下载一个图片，然后通过接口上传图片，但图片是随机的，如果上传能参数化就比较好。

**Comment by luty2018** [comment]
感谢建议， 我们会在v3.0讨论规划。

**Comment by shoutian44443** [comment]
可否知道下多久能支持呢？
