### ISSUE TITLE
[BUG]登录ms,登录地址路径用各模块路径时报"network error"

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23688]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

登录ms,登录地址路径用各模块路径时报"network error"，例如用http://ms.company.com:8081/#/track/home 登录报错，直接用http://ms.company.com:8081/#/login 登录没问题

### 重现步骤

1.新打开一个页签（一定要新打开一个）,登录ms，输入地址http://XX:8081/#/track/home
![img_v2_274de662-1c3b-4f14-9b7f-276b5431d77g](https://user-images.githubusercontent.com/103627487/232275300-cc72956b-4c67-4133-ab7c-35cdfb26eb3e.png)
![img_v2_bc854b77-57bc-4d8e-aef5-92460ec9c12g](https://user-images.githubusercontent.com/103627487/232275268-aab6a6f5-64a8-414f-a3ac-44a2979427fc.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.9.0已修复
