### ISSUE TITLE
[FEATURE]希望可以在功能测试用例栏像场景测试用例一样，添加运行按钮，批量执行和报告

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#23687]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

我做的项目是一个长期的项目，功能在刚开发出来的时候，需要编写功能用例，去关联接口，场景和UI自动化用例。
目前就单一功能想测试，只能创建一个测试计划去测试，而不是通过勾选该功能下的所有功能用例，去自动化执行相关联的接口，场景和UI自动化用例，并串行执行这些用例，生成一份报告。希望在3.0版本后可以酌情可虑添加这项功能

**Comment by luty2018** [comment]
不好意思， 没有太看明白你的需求呢， 可否进一步详细描述？

**Comment by YellCatt** [comment]
> 不好意思， 没有太看明白你的需求呢， 可否进一步详细描述？

比如我有一个登录功能，设计了十个功能用例，这十个功能用例关连了接口用例，场景用例，ui用例，我现在想把登录功能测试一遍，目前的办法是创建一个计划，把登录功能的功能用例放在计划里，相关连的其他用例就可以运行了。但是这个过程太繁琐了，能不能像场景用例一样，勾选，一键运行，形成报告

**Comment by luty2018** [comment]
明白了， 目前还是需要加入到测试计划执行，没有计划在功能用例里增加运行按钮哈。
