### ISSUE TITLE
[FEATURE] 可以合并多轮测试，输出总报告

### ISSUE THREAD

**Issue by lotushh** [metersphere/metersphere#23685]
### MeterSphere 版本

v2.8.1

### 请描述您的需求或者改进建议

创建测试计划，执行**第一轮RC1**后得到报告1，执行**第二轮RC2**后得到报告2，执行**第三轮RC3**后得到报告3。
通常也需要一个**总报告**能查看RC1~RC3的执行情况，不需要用户分别打开3个报告。
建议实现同一测试计划下合并报告的功能。

**Comment by luty2018** [comment]
这个功能会在我们v3.0 去讨论
