### ISSUE TITLE
[BUG]  文件管理拉取git文件存在三问题-新提

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23686]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

文件管理拉取git文件存在三问题

### 重现步骤

git-csv 路径也需要显示，原因：下图中的同名文件（图截错了，应该截的是同名文件）为同一仓库，同一分支，不同路径拉取的文件如a.csv和x/x/x/a/csv的关系，不显示路径无法区分
![img_v2_c55c0fe0-b57b-470f-ae27-b052e870096g](https://user-images.githubusercontent.com/103925124/232198574-1faf7f1c-ad68-40e9-b87c-c2524cbc929f.jpg)
某人预览后，文件的更新人变某人，预览不应该变更修改人哈！
![img_v2_0295971a-d7ae-4a0f-853e-b1bc88816aeg](https://user-images.githubusercontent.com/103925124/232198840-01c1178f-8812-4c50-91b6-7be6b15840d7.jpg)
删除模块，页面未刷新，还显示这已删除模块的文件，如下图，删除模块后，文件仍然显示在列表中，刷新后无
![image](https://user-images.githubusercontent.com/103925124/232199192-8d3e44a8-88e6-4f16-ad60-65b1b2ae5527.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.9.0已修复
