### ISSUE TITLE
[FEATURE] 在报告总结对话框中添加修改单元格背景色和字体颜色

### ISSUE THREAD

**Issue by lotushh** [metersphere/metersphere#23683]
### MeterSphere 版本

v2.0.1

### 请描述您的需求或者改进建议

测试跟踪 -- 报告 -- 查看测试报告 -- 报告总结 --编辑  --添加修改单元格背景色和字体颜色

**Comment by luty2018** [comment]
不好意思，暂时没有这个规划。
