### ISSUE TITLE
[FEATURE] 在报告中可以添加新的类似报告总结的目录分类

### ISSUE THREAD

**Issue by lotushh** [metersphere/metersphere#23684]
### MeterSphere 版本

v2.0.1

### 请描述您的需求或者改进建议

测试跟踪 -- 报告 -- 查看测试报告 -- 添加新的类似报告总结的目录分类（比如测试环境，测试需求）

**Comment by luty2018** [comment]
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/36292514/232365412-61ab6b41-c7ff-4500-9882-e5e251afdb77.png">
目前已经支持了。

**Comment by lotushh** [comment]
你好，我的意思是否可以添加和测试报告，用例统计分析同级别的编辑框
