### ISSUE TITLE
[BUG] jsonpath提取的值缺失精度

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23697]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

1.20.21-lts

### 使用外置数据库

否

### 问题描述

响应数据里的小数有2个0，推荐的jsonpath结果里小数没有0，但是最终提取的小数又有1个0

### 重现步骤

响应数据里的小数有2个0，推荐的jsonpath结果里小数没有0，但是最终提取的小数又有1个0
![8724081939861b9fc18e60a507aa88f](https://user-images.githubusercontent.com/104960608/232372152-eb92a500-a840-44cb-a35a-6cd223a82c34.png)

![7aea123a515763b8f38c80fa378b531](https://user-images.githubusercontent.com/104960608/232372165-f917b9ae-bc44-439e-a879-2497ca030850.png)

**Comment by 13290445582** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/128017892/232465421-498f3d54-f908-41f5-83fa-aa36cbeebc09.png">
<img width="942" alt="image" src="https://user-images.githubusercontent.com/128017892/232465463-d8b64bb9-928f-4fd6-b24c-41954833d7ba.png">
感谢反馈，测试环境未复现，方便提供下您的复现场景嘛

**Comment by 13290445582** [comment]
提取精度bug已于v1.20.22修复，推荐JSONPath提取精度问题尚未复现

**Comment by Ycr123888** [comment]
接口响应体可使用下面json数据：
{
    "total": 1,
    "hisTotal": 0,
    "rows": [
        {
            "id": 7812,
            "intervalOrderNo": "230418000010",
            "accountId": 13,
            "accountName": "查启维-衍生品对冲（原查启维）",
            "orderTypeCode": 4,
            "orderTypeName": "银行间衍生品指令",
            "targetCode": "FR007_5Y",
            "targetAbbr": null,
            "tradeDirection": 2,
            "tradeMarket": "CFETS",
            "targetTypeCode": 90100,
            "targetTypeName": "利率互换",
            "startDate": "2023-04-18T00:00:00.000+08:00",
            "endDate": "2023-04-18T00:00:00.000+08:00",
            "openOrCloseFlagCode": null,
            "operNo": "CSC26329",
            "operName": "文健敏",
            "validFlag": 1,
            "delFlag": 0,
            "approvalLog": "审批通过",
            "approvalStatusCode": 2,
            "approvalStatusName": "审批通过",
            "minPrice": 0.0025,
            "maxPrice": 15.0,
            "maxNetPrice": null,
            "minNetPrice": null,
            "maxFullPrice": null,
            "minFullPrice": null,
            "maxContractPrice": 15.0,
            "minContractPrice": 0.0025,
            "orderNum": 150,
            "intervalOrderProgress": null,
            "dayDealProgress": 0.0,
            "dealProgress": 0.0,
             "dayDealNum": null,
            "dealNum": null,
            "validOrderNum": null,
            "avgPrice": null,
            "avgNetPrice": null,
            "avgFullPrice": null,
            "avgContractPrice": null,
            "createUsr": "CSC26329",
            "updateUsr": "CSC26329",
            "createDate": "2023-04-18T08:16:03.000+08:00",
            "lastUpdateDate": "2023-04-18T08:16:04.000+08:00",
            "validOrderNumLegs": null,
            "dayDealNumLegs": null,
            "dealNumLegs": null,
            "drafterRole": "Fid_Prop_InvstManager",
            "currentRole": "Fid_Management_Prop",
            "quoteType": 2,
            "settleDays": null,
            "quoteElement": null,
            "minYtm": null,
            "maxYtm": null,
            "minYte": null,
            "maxYte": null,
            "tradeAmount": 3000000000,
            "validTradeAmount": null,
            "dayDealAmount": null,
            "dealAmount": null,
            "avgYtm": null,
            "legFlagCode": null,
            "bpMax": null,
            "bpMin": null,
            "refuseMsg": null,
            "legs": null,
            "templateName": null,
            "baseNum": 0,
            "baseTradeAmount": null,
            "starFlag": false,
            "ifFitYtmBond": false
        }
    ],
    "rowsOne": null,
    "rowsTwo": null,
    "cntInfo": null,
    "code": 200,
    "msg": null
}

**Comment by Ycr123888** [comment]
断言或提取 maxContractPrice 字段

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v1.20.22修复。
