### ISSUE TITLE
[BUG]接口测试不能支持query请求参数值是json格式的多参数编码

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23693]
### 联系方式

kaijie.yu@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

1.接口测试，请求参数为query格式，值是Json，不能支持json包含多个参数的编码

### 重现步骤

1.创建一个接口，请求参数里选择query参数，请求值填写json格式，编码选择是，{"where":{"rate":"1","age":18}}
![image](https://user-images.githubusercontent.com/55130444/232314544-8fc64a2f-379b-4934-9a4a-f155a8cf259b.png)
2.但是可以支持json格式的值的是单个参数的编码
![image](https://user-images.githubusercontent.com/55130444/232314673-5a70a478-89c3-47c2-bae8-e366ed7654af.png)

### 期待的正确结果
能够支持query参数，值是json格式 单个和多个参数的 编码

**Comment by kaijie-yu** [comment]
<img width="1004" alt="b32f15c872cd7257e1da6c6b2bd5234" src="https://user-images.githubusercontent.com/55130444/232429128-a9a16b00-7e81-43b8-97b6-37c51324b632.png">
<img width="989" alt="b03772b2d1d9b857617c279afbf6de6" src="https://user-images.githubusercontent.com/55130444/232429160-ed15cea4-5040-4f24-8efb-16ae470eaa8d.png">
jmeter是可以支持json的编码请求的。

**Comment by 13290445582** [comment]
感谢反馈，JMeter ${__urlencode()} 函数不支持 json 编码，MeterSphere平台目前用的就是这个。

**Comment by 13290445582** [comment]
您好，是不支持的

**Comment by kaijie-yu** [comment]
你的意思是jmeter能够支持，我们产品现在不支持，是这个意思嘛，
那后续有计划支持吗

**Comment by 13290445582** [comment]
你好，暂时没有

**Comment by 13290445582** [comment]
计划于v2.9.0支持query请求参数值是json格式的多参数编码

**Comment by 13290445582** [comment]
v2.9.0已修复
