### ISSUE TITLE
[BUG] 启用k8s资源池(接口测试) 时报错

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#23705]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

按照步骤 《[在MeterSphere平台添加并使用Kubernetes资源池](https://mp.weixin.qq.com/s/zYm9PdujA6vRAPZzMdHUKA)》创建k8s资源池。
资源池的deploy已成功创建，在ms创建资源池页面也填入了正确的信息，但是资源池无法成功启用，system-setting报错如下：
2023-04-17 13:22:09,171  WARN      io.fabric8.kubernetes.client.Config: 559 - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2023-04-17 13:22:09,664  WARN      io.fabric8.kubernetes.client.Config: 559 - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
dfc6baee-2f2d-4c40-9bde-a37f6262ab60

但是当资源池只作为性能测试用途时，能成功启用
![image](https://user-images.githubusercontent.com/24548477/232400670-a4cc7791-1c24-4f5f-8504-acc8d306334b.png)

### 重现步骤

1. 参考文章 (https://mp.weixin.qq.com/s/zYm9PdujA6vRAPZzMdHUKA  创建k8s资源池
2. 资源池用途勾选“接口测试”
3. 启用k8s资源池

### 期待的正确结果

接口测试用途的k8s资源池能成功启用

### 相关日志输出

```shell
2023-04-17 13:22:09,171  WARN      io.fabric8.kubernetes.client.Config: 559 - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2023-04-17 13:22:09,664  WARN      io.fabric8.kubernetes.client.Config: 559 - Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
dfc6baee-2f2d-4c40-9bde-a37f6262ab60
```

**Comment by youliyuan-fit2cloud** [comment]
你好，这个日志可以忽略。前端控制台提示什么错误？方便把Job模版上传发我们看看吗？

**Comment by xyziven** [comment]
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    test-id: ${TEST_ID}
  name: ${JOB_NAME}
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        test-id: ${TEST_ID}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: test-id
                      operator: In
                      values:
                        - ${TEST_ID}
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - command:
            - sh
            - -c
            - /run-test.sh
          env:
            - name: START_TIME
              value: "${START_TIME}"
            - name: GRANULARITY
              value: "${GRANULARITY}"
            - name: JMETER_REPORTS_TOPIC
              value: ${JMETER_REPORTS_TOPIC}
            - name: METERSPHERE_URL
              value: ${METERSPHERE_URL}
            - name: RESOURCE_ID
              value: ${RESOURCE_ID}
            - name: BACKEND_LISTENER
              value: "${BACKEND_LISTENER}"
            - name: BOOTSTRAP_SERVERS
              value: ${BOOTSTRAP_SERVERS}
            - name: RATIO
              value: "${RATIO}"
            - name: REPORT_FINAL
              value: "${REPORT_FINAL}"
            - name: TEST_ID
              value: ${TEST_ID}
            - name: THREAD_NUM
              value: "${THREAD_NUM}"
            - name: HEAP
              value: ${HEAP}
            - name: REPORT_ID
              value: ${REPORT_ID}
            - name: REPORT_REALTIME
              value: "${REPORT_REALTIME}"
            - name: RESOURCE_INDEX
              value: "${RESOURCE_INDEX}"
            - name: LOG_TOPIC
              value: ${LOG_TOPIC}
            - name: GC_ALGO
              value: ${GC_ALGO}
          image: ${JMETER_IMAGE}
          imagePullPolicy: IfNotPresent
          name: jmeter
          ports:
            - containerPort: 60000
              protocol: TCP
          volumeMounts:
            - mountPath: /test
              name: test-files
            - mountPath: /jmeter-log
              name: log-files
        - command:
            - sh
            - -c
            - /generate-report.sh
          env:
            - name: START_TIME
              value: "${START_TIME}"
            - name: GRANULARITY
              value: "${GRANULARITY}"
            - name: JMETER_REPORTS_TOPIC
              value: ${JMETER_REPORTS_TOPIC}
            - name: METERSPHERE_URL
              value: ${METERSPHERE_URL}
            - name: RESOURCE_ID
              value: ${RESOURCE_ID}
            - name: BACKEND_LISTENER
              value: "${BACKEND_LISTENER}"
            - name: BOOTSTRAP_SERVERS
              value: ${BOOTSTRAP_SERVERS}
            - name: RATIO
              value: "${RATIO}"
            - name: REPORT_FINAL
              value: "${REPORT_FINAL}"
            - name: TEST_ID
              value: ${TEST_ID}
            - name: THREAD_NUM
              value: "${THREAD_NUM}"
            - name: HEAP
              value: ${HEAP}
            - name: REPORT_ID
              value: ${REPORT_ID}
            - name: REPORT_REALTIME
              value: "${REPORT_REALTIME}"
            - name: RESOURCE_INDEX
              value: "${RESOURCE_INDEX}"
            - name: LOG_TOPIC
              value: ${LOG_TOPIC}
            - name: GC_ALGO
              value: ${GC_ALGO}
          image: ${JMETER_IMAGE}
          imagePullPolicy: IfNotPresent
          name: report
          volumeMounts:
            - mountPath: /test
              name: test-files
            - mountPath: /jmeter-log
              name: log-files
      restartPolicy: Never
      volumes:
        - emptyDir: {}
          name: test-files
        - emptyDir: {}
          name: log-files

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/232415914-8f1b7ee6-2fba-4081-a540-2088a69d4735.png)

部署方式 yaml文件参考上图中 Namespace的帮助提示中的文件。

**Comment by xyziven** [comment]
close the issue since it is a yml related.
