### ISSUE TITLE
[BUG] 接口响应体小数点未展示全

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23700]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

![8595a34049b9f80706ec22f2119903b](https://user-images.githubusercontent.com/103925124/232373866-99d4113a-0bd1-4aae-b48f-578fac343b55.png)

### 重现步骤

![af0fd1544cbe06ab5f8ee11e7157b73](https://user-images.githubusercontent.com/103925124/232373913-b0a286ad-a14c-4d4b-a60a-f200e18692ee.png)
![2631e13c192af0ee29f10d00b924b34](https://user-images.githubusercontent.com/103925124/232373921-547dfb66-99ca-4a04-b8e0-15e5704a1fac.png)
![c68597220f503ab3f812db107773abb](https://user-images.githubusercontent.com/103925124/232373929-b7825d80-e748-46c2-bb15-637c3a6cf3f1.png)

**Comment by wxg0103** [comment]
这个请求在JMeter中也是这个结果，目前无法解决
