### ISSUE TITLE
模块框建议增加一个拖动条

### ISSUE THREAD

**Issue by summerswind** [metersphere/metersphere#23704]
### MeterSphere 版本

1.20.12-lts

### 联系方式

125974852@qq.com

### 请描述您的需求或者改进建议

层级较深时，模块的名字被遮住了展示不出来，建议增加一个拖动按钮，可以移动查看最底层的模块后面的名字

### 请描述你建议的实现方案

层级较深时，模块的名字被遮住了展示不出来，建议增加一个拖动按钮，可以移动查看最底层的模块后面的名字

### 附加信息

接口测试->接口自动化->最左侧的模块，下拉到最下方，不支持按钮拖动展示

**Comment by luty2018** [comment]
建议更新到v2.8.1版本， 左侧模块可以调整宽度并固定。
