### ISSUE TITLE
[BUG]测试计划定时任务的结果报告中，失败重试无法结束

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#23710]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

测试计划中添加定时任务，定时任务中只有接口场景用例，存在失败后进行重试，从任务中心可观察到所有任务都已经重新跑完了，但原本报告中执行状态还是重新执行中，新的执行结果也未进行更新

### 重现步骤

测试计划中添加定时任务，定时任务中只有接口场景用例，存在失败后进行重试，从任务中心可观察到所有任务都已经重新跑完了，但原本报告中执行状态还是重新执行中，新的执行结果也未进行更新

### 期待的正确结果

能够正常执行完并更新新的执行结果

### 附加信息

![image](https://user-images.githubusercontent.com/40912823/232398821-01bdcd29-84d1-461e-aec8-8550fb753bc5.png)

**Comment by 13290445582** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128017892/232427745-a473dba4-2828-4785-8dc7-39240e4b4cbd.png">
无法复现，失败重跑成功

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
