### ISSUE TITLE
[BUG]页面刷新之后，接口测试导入页面最下方的说明显示为空，切换数据格式之后又OK了

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2371]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.8.2
**Bug 描述**
页面刷新之后，接口测试导入页面最下方的说明显示为空，切换数据格式之后又OK了

**Bug 重现步骤**
1. 页面刷新
2.点击导入

![WechatIMG91](https://user-images.githubusercontent.com/32027713/116348100-0a4a6680-a820-11eb-9d64-d2693b4d99ff.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复

**Comment by xulinde** [comment]
1.9.2已修复
