### ISSUE TITLE
[BUG] 条件控制器的条件框太小+报告不显示条件控制器的备注问题，难以分辨

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#23722]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

条件控制器的条件框太小+报告不显示条件控制器的备注问题，难以分辨

### 重现步骤

问题1：条件框太小，导致不能编辑，只能粘贴出来编辑后，粘贴回去
![image](https://user-images.githubusercontent.com/103925124/232443609-9cfb0c98-d87f-410d-b5cb-c15111a4dffb.png)
问题2：条件控制器的备注，报告中不显示，导致报告条理性欠缺
![image](https://user-images.githubusercontent.com/103925124/232443004-434294f7-d4c3-43b5-937c-370189613925.png)
![image](https://user-images.githubusercontent.com/103925124/232442914-58007070-b68f-43ee-a931-23865e1b556d.png)
问题3：条件控制器空和非空，也有备注可填写
![image](https://user-images.githubusercontent.com/103925124/232444133-0ecd02ad-25e6-4274-99d4-280444f2260f.png)

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
