### ISSUE TITLE
[FEATURE] 缺陷模板- 希望能有一个全局的公共自定义模板，而不是在每个项目都需要重新设置定义模板

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#23745]
### MeterSphere 版本

v2.8.1

### 联系方式

群14-亲山留水

### 请描述您的需求或者改进建议

A项目设置好了 自定义模板   
B项目看不到A项目设置好的自定义缺陷模板（希望能看到A项目的已设置好的自定义模板，B项目仅需关联使用即可）

目前所有的项目都需要自己重复设置缺陷模板，这不利于模板的统一规划使用

**Comment by luty2018** [comment]
感谢建议， 这个我们会在v3.0支持。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
