### ISSUE TITLE
[BUG] 偶现首页报错，且报告不明晰，用户不好排查

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23748]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

1.20.21-lts

### 使用外置数据库

否

### 问题描述

偶现首页报错

### 重现步骤

![企业微信截图_1681798117806](https://user-images.githubusercontent.com/103925124/232710192-19e6755f-1d26-4e0f-9b57-c55e81cee791.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，后端是否有报错日志，提供下。
