### ISSUE TITLE
[FEATURE]接口文档定义，响应体部分操作不太方便

### ISSUE THREAD

**Issue by txzqy123** [metersphere/metersphere#23740]
### MeterSphere 版本

v2.8.1

### 联系方式

txzqy123@163.com

### 请描述您的需求或者改进建议

1、【接口定义功能】接口编辑的场合，编辑响应体，且响应体内容比较长的时候。点击保存按钮页面都会跳转到最顶部，且将正在编辑的响应体折叠起来，不利于后续进一步查看和编辑。
【期望】：点击保存保持原有页面位置及状态
2、【接口定义功能】接口编辑的场合，编辑响应体，响应体比较长的场合，响应内容部分太小，不太方便操作，如下图所示
【期望】：可以拖动响应内容的大小
![image](https://user-images.githubusercontent.com/13378979/232667669-0d0a5c37-a7bf-4f7e-beb2-669b3e4502e9.png)

3、【接口定义功能】接口编辑的场合，编辑响应体，直接通过json生成响应内容的场合，如果是个list，生成的结构太多，此处是文档编辑，应该只对一个对象声明就可以了。不用把list里面的所有内容都展示。
![WX20230418-115802](https://user-images.githubusercontent.com/13378979/232667594-7b560eeb-1b3a-4774-984f-bbf0a8502c02.png)

**Comment by luty2018** [comment]
感谢建议， 这块已经转交交互设计优化。
