### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by richardwu0313** [metersphere/metersphere#23744]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

richard_wu0313@hotmail.com

### 请描述您的需求或者改进建议

报告统计/功能用例统计分析中的用例列表无法直接导航到用例详细

### 请描述你建议的实现方案

ID 添加链接到用例详细的link

**Comment by luty2018** [comment]
你好， 报表这块我们会在v3.0进行全新升级，v2版本会维持现状。
