### ISSUE TITLE
[BUG] 请求密集型自动化测试场景，在测试计划中执行，发现两个TOP SQL，并且测试计划里场景经常是未执行，或者全部失败。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#23746]
### 联系方式

王进

### MeterSphere 版本

v.1.20.20, v2.7.1

### 使用外置数据库

否

### 问题描述

 请求密集型自动化测试场景，在测试计划中执行，发现两个TOP SQL，并且测试计划里场景经常是未执行，或者全部失败。

### 重现步骤

1. 客户是保险企业，他们的应用场景是，一个自动化场景里循环几千次，甚至需要上万次，对应的csv文件里有两三万行。 
2. 在我们建议下，客户把场景拆分成20个，每个场景里循环一千次，对应一个csv文件包含1000行数据，列数超过上百列。 
3. 单个场景调试执行，完全OK。
4. 可是如果将这些场景放到一个测试计划里，偶尔出现not executed，或者全部失败。如果这个测试计划在夜间执行过程中，跟别的测试计划执行重叠了，那肯定是 全部failed或者部分not executed。
5. 我们和客户排查了几次日志，还有数据库。 最后都是指向下面这个SQL: 
UPDATE `api_scenario_report` SET `project_id` = ? , `name` = ? , `create_time` = ? , `update_time` = ? , `status` = ? , `user_id` = ? , `trigger_mode` = ? , `execute_type` = ? , `scenario_name` = ? , `scenario_id` = ? , `create_user` = ? , `actuator` = ? , `end_time` = ? , `report_version` = ? , `version_id` = ? , `report_type` = ? , `description` = ? WHERE `id` = ?  

还有一个SQL也是TOP SQL:
DELETE FROM `api_execution_queue` WHERE `id` NOT IN ( SELECT `t1` . `queue_id` FROM `api_execution_queue_detail` `t1` ) 

6. 尤其是这条update语句，每次只要出现问题，它肯定是top sql。从客户的测试场景来说，可以理解，一个场景要处理和更新的 report数据比较大。假如多个场景执行，肯定导致出现锁，下面截图就是每次执行失败必看到的日志：
<img width="790" alt="1681800158796" src="https://user-images.githubusercontent.com/76033005/232693086-1c637581-3592-449d-b9bb-4a3940086c0e.png">

7. 客户这边 只要夜间出现 两个测试计划，或者多个测试计划重叠跑。 也肯定出现问题。 

### 期待的正确结果

针对这种 请求密集型的场景 所对应的结果和日志处理，请开发研究研究，尽量优化一下。
该问题，前一段时间 在2.6.1上另外一个用户那里也碰到了，当时磊博和开发看了，最后是建议客户先不跑那个场景。 

### 附加信息

客户的环境摸不到，建议客户做了几次监控，目前来看，还行。 
![image](https://user-images.githubusercontent.com/76033005/232693553-2f48b361-9845-4860-bfd3-5cafce2afdc0.png)

![70f570e7d548d3bbdb68789b9b25a1f](https://user-images.githubusercontent.com/76033005/232693608-6cbe77dc-f880-4429-808c-5dd9f3f22432.jpg)

**Comment by fit2-zhao** [comment]
感谢反馈，描述到的几个优化点，在下版本都会优化一下，如果能有详细一份日志就更好了。

**Comment by 35plus** [comment]
<img width="1287" alt="25d4c5bb549a34dde2a8b94cd3cd6db" src="https://user-images.githubusercontent.com/76033005/233952557-07ced212-6c84-445c-b99d-99e984944aa1.png">

**Comment by 35plus** [comment]
[info.zip](https://github.com/metersphere/metersphere/files/11339297/info.zip)

**Comment by 35plus** [comment]
赵勇，日志更新进来了。

**Comment by 35plus** [comment]
[ms-jmeter-run-log.log (2).zip](https://github.com/metersphere/metersphere/files/11339314/ms-jmeter-run-log.log.2.zip)

**Comment by 35plus** [comment]
kafka的日志 还没更新进来，等待客户提供。

昨天夜里出现MS服务重启了。 估计资源不够了。

**Comment by fit2-zhao** [comment]
使用资源池了吗，如果使用了资源池日志也提供下。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
