### ISSUE TITLE
[BUG]Swagger url导入到未规划接口下，报“格式错误”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23753]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

Swagger url导入到未规划接口下，第一次正常导入，再次导入报“格式错误”

### 重现步骤

1. Swagger url 导入到未规划接口下(注意:模块选择未规划接口），第一次能正常导入，第二次导入报格式错误
![image](https://user-images.githubusercontent.com/103627487/232696310-ad2d5c43-5e67-4526-97a8-711749b5ee62.png)
![image](https://user-images.githubusercontent.com/103627487/232726811-e2944ba7-a4fb-4384-a21e-98ee0e96d838.png)
![img_v2_306c03f1-9350-459f-992d-806aa94e406g](https://user-images.githubusercontent.com/103627487/232727530-8f23e9e3-2772-46a6-91eb-61a458a1fafd.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by zrfit** [comment]
v2.9未复现该问题，请升级尝试。
