### ISSUE TITLE
[QUESTION]metersphere-2.5版本运行的时候报错 maven下载的jar是空的

### ISSUE THREAD

**Issue by liulili-dalao** [metersphere/metersphere#23759]
### 请描述您的问题

java: 读取C:\Users\Transsion\.m2\repository\io\metersphere\metersphere-platform-plugin-sdk\1.0.0\metersphere-platform-plugin-sdk-1.0.0.jar时出错; zip END header not found，
然后找到 metersphere-platform-plugin 项目打包报错 程序包io.metersphere.base.domain不存在

**Comment by luty2018** [comment]
您好， 二开请自行查阅文档。

**Comment by liulili-dalao** [comment]
请问一下，查询什么文档，可以自己解决，可以给一下思路吗

**Comment by wangpanwangpan** [comment]
你有找到吗😀

**Comment by wangpanwangpan** [comment]
> 请问一下，查询什么文档，可以自己解决，可以给一下思路吗

今天试了下  找到framework/sdk-parent/domain进行编译发布 然后再去编译插件 最后编译主干

**Comment by kxzonly** [comment]
@liulili-dalao 
我分析了一下，是因为metersphere-platform-plugin/metersphere-platform-plugin-sdk/pom.xml文件中的domain这个依赖给的版本号是main导致的，修改成当前分支线的版本号就能解决，例如这个问题改成2.5
![image](https://github.com/metersphere/metersphere/assets/37934520/f3d175dd-e1fd-453e-9b31-39a0c305f8e2)
正常的版本号应该是跟metersphere库中的framework/sdk-parent/domain的版本号是一致的，一般为大版本号，例如2.10这种，可以在这个目录执行mvn clean package得到版本号，如下图
![image](https://github.com/metersphere/metersphere/assets/37934520/5f2f24ee-bfc4-45bb-b07e-04356834195d)

编译完plugin-sdk，不要忘了发布到私有库或者mvn install一下，要不主库还是过不去编译的

顺便吐槽一下，官方的开发没事不要让一些提问者没事瞎切main分支去编译，人家用想用老平台来编译，你非让人用main分支，好使是好使，你不怕人家就算编译成功了也用不了哈，还有那种丢回复说看文档的，你们除了一个build.md还有啥高级文档了，不要光想着企业版搞钱，维护一下社区的评价好不好
