### ISSUE TITLE
[BUG]UI测试不开启的时候，在测试计划页面点击全部停止报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23758]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

UI测试不开启的时候，在测试计划页面点击全部停止报错

### 重现步骤

1. 配置文件 .env 中MS_UI_ENABLED=false情况下，在测试计划页面点击全部停止报错
![image](https://user-images.githubusercontent.com/103627487/232737542-d6dd4c75-dcdf-481b-842f-7a429aa3b661.png)

**Comment by song-tianyang** [comment]
问题收到！ 预计V2.9.0修复
