### ISSUE TITLE
[BUG]test后置操作拉动后置操作问题

### ISSUE THREAD

**Issue by 1father1** [metersphere/metersphere#23767]
### 联系方式

交流44群

### MeterSphere 版本

最新

### 使用外置数据库

是

### 问题描述

后置操作-添加后置脚本-输入参数-输入参数页面是打开的状态-在添加后置脚本-往上拉进上一个后置脚本的框上就会出现

下面是微信聊天记录复现
在已经有两条数据的情况下
![7f4faeeebc396cc7c634e5e5db7686c](https://user-images.githubusercontent.com/108117313/232764907-20cf151c-b08c-46f8-b982-9445fde56437.png)
新建第三条
然后拉过去第二个数据上
![4bf5316e21a6373cf78f8b69de9d13d](https://user-images.githubusercontent.com/108117313/232764984-c5b89db8-c71f-424f-b163-468d58fa4c7d.png)
拉过去
就复现了

### 重现步骤

https://user-images.githubusercontent.com/108117313/232764718-93c9ea44-96fc-42f4-a6a5-0843d21537c9.mp4

**Comment by 13290445582** [comment]
感谢反馈，问题已提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0以上版本已修复。
