### ISSUE TITLE
[FEATURE]与TAPD需求关联时，能够按照需求分类树展示可选需求

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#2376]
**请描述您的需求或者改进建议.**
与TAPD平台对接后，创建测试用例时，下拉选择需求时有点慢，另外就是需求查看时不方便

**请描述你建议的实现方案**

关联TAPD需求时，能够按照需求分类树展示可关联的需求；
展示慢建议可以优先展示需求分类，用户逐级设置时再进行需求展开；

**Comment by xulinde** [comment]
感谢反馈，后续版本会优化下

**Comment by luty2018** [comment]
非常抱歉长时间没有回复，关联需求这里后面会优化成关联用例一样的交互， 以列表形式查看， 建议你查看我们v2.7的关联用例的交互方式，是否能满足需求。
这边先关闭issue，如有建议可以重新打开或者新创建。
