### ISSUE TITLE
[BUG]环境配置中 host 引用变量时，请求地址不正确

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23762]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

环境配置中 host 引用变量时，请求地址不正确,请求地址会多出 端口/,

### 重现步骤

1.环境中配置ip为变量
![image](https://user-images.githubusercontent.com/103627487/232748245-d4d7561c-d620-42e9-8fee-12d2c160a8ac.png)
![image](https://user-images.githubusercontent.com/103627487/232748350-16f3cbb1-c106-4498-a678-ade82b472815.png)
2.接口自动化中执行场景
![image](https://user-images.githubusercontent.com/103627487/232748787-9d6c1715-ad18-40f8-9def-3b38eec0fbea.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前是按照jmeter的实现方式，但是后续版本会优化。

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0中已修复。
