### ISSUE TITLE
[BUG]jira集成后，同步缺陷报错

### ISSUE THREAD

**Issue by zhangsai** [metersphere/metersphere#23776]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

jira集成后，同步缺陷报错
![screenshot-20230419-102753](https://user-images.githubusercontent.com/6245166/232951079-d94eb7be-9f78-4e3d-9ad4-5f4d28c87695.png)

### 重现步骤

点击同步缺陷就可以重现

### 期待的正确结果

同步成功

**Comment by 13290445582** [comment]
感谢反馈，问题未复现。
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/128017892/232979664-0dc9a8af-e284-4fa9-b77e-8ab2e6efb196.png">

**Comment by 13290445582** [comment]
麻烦提供下后台日志，帮助找到问题

**Comment by zhangsai** [comment]
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1

> 麻烦提供下后台日志，帮助找到问题

**Comment by 13290445582** [comment]
你好，经过分析，报错原因是有个自定义字段值过长，您可以将下面表中的字段值长度加长。![image](https://user-images.githubusercontent.com/128017892/233248638-f3a82af0-a93e-49ba-b5e9-28c3a87e677b.png)

**Comment by zhangsai** [comment]
> 你好，经过分析，报错原因是有个自定义字段值过长，您可以将下面表中的字段值长度加长。![image](https://user-images.githubusercontent.com/128017892/233248638-f3a82af0-a93e-49ba-b5e9-28c3a87e677b.png)

我将字段类型改为text 后，同步成功了，感谢！
建议后续版本直接将这个字段改为text，避免其他人也碰到类似问题

**Comment by 13290445582** [comment]
感谢
