### ISSUE TITLE
[BUG]swagger V2版本URL方式导入提示格式错误

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#23775]
### 联系方式

群14-亲山留水

### MeterSphere 版本

v2.8.1

### 使用外置数据库

是

### 问题描述

swagger V2版本URL方式导入提示格式错误
同样的swagger信息 通过json文件中转导入是可以的

### 重现步骤

![swagger_v2_url](https://user-images.githubusercontent.com/82088551/232939455-2c66eb9c-cc3b-4eca-8a29-38f954dba286.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，请确认这个swagger url 链接导入是否需要 cookie信息？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
