### ISSUE TITLE
[BUG]基于一个已关联Tapd平台需求的测试用例，通过复制方式重建测试用例时，创建页面关联的tapd需求展示为id号

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#2377]
**MeterSphere 版本**
 MeterSphere 版本是1.9.2

**Bug 描述**
基于一个已关联Tapd平台需求的测试用例，通过复制方式重建测试用例时，创建页面关联的tapd需求展示为id号

**Bug 重现步骤**
1.  在测试用例管理中，创建测试用例，同时关联Tapd中的需求，创建完成后点击保存；
2.  基于已保存的测试用例重新复制一个测试用例，继续编辑，编辑页面中展示的关联的tapd需求展示为id号

**期待的正确结果**
正确情况下应该是展示原用例关联的需求名称

**截图**
![image](https://user-images.githubusercontent.com/60059766/116355716-d4f84580-a82c-11eb-88cc-db9219d45a30.png)

**Comment by zyyfit** [comment]
感谢反馈，今天将发布1.9.0版本，请发布后看一下最新版
