### ISSUE TITLE
[BUG]朋友们，这个问题又出现了---测试用例列表中，同一用例多次打开时，会出现多个浏览器标签，且每个tab都可以编辑保存。保存后，系统保存最后一次编辑的内容。很容易造成数据冲突或覆盖。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#23779]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

[BUG]测试用例列表中，同一用例多次打开时，会打开多个浏览器标签，且每个浏览器标签都可以分别编辑保存。保存后，系统会保存最后一次编辑的内容。
很容易造成数据冲突或覆盖。

### 重现步骤

[BUG]测试用例列表中，同一用例多次打开时，会打开多个浏览器标签，且每个浏览器标签都可以分别编辑保存。保存后，系统会保存最后一次编辑的内容。
很容易造成数据冲突或覆盖。

### 期待的正确结果

1、同一用例，应只允许打开一个浏览器标签。当重复打开时，直接跳转到正在打开的用例标签，而非再打开一个。
2、为什么要重新打开新的浏览器标签？很不方便啊，原来在meterspehre内打开新tab页不是挺好用的么？？

**Comment by song-tianyang** [comment]
您好。 目前ms没有做数据历史校验，V2版本也不打算做数据历史校验。

也就是说哪怕浏览器只打开一个，有多个用户在多台机器上操作，也是会进行数据覆盖的。

这是B/S架构的特性，如果要解决的话可以增加数据版本提交校验。但是我们V2没有这个打算。

数据历史校验这个功能已经在我们在V3待讨论的需求列表中了。我们的产品同事会在V3功能评估中再从开发成本、交互体验等多方面角度来考虑这个功能。
