### ISSUE TITLE
[BUG]在postman上调试成功的接口，导出文件在导入到MS系统中，此接口无法执行成功，提示参数值类型不对。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23774]
### MeterSphere 版本

2.8.1 & lts1.20.14

### 使用外置数据库

否

### 问题描述

在Postman上面执行成功的接口，导出在导入到MS里，执行一直提示参数传递类型不对。
错误信息【系统出错了，请联系管理员。错误原因：[ Optional int parameter 'addType' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type. ]】
备注：
1）MS 是lts1.20.14版本 和2.8.1版本
2）MS服务器和被测服务环境网络没问题。
3）Postman中请求头里的参数也都copy到ms中

### 重现步骤

在Postman上面执行成功的接口，导出在导入到MS里，执行一直提示参数传递类型不对。
错误信息【系统出错了，请联系管理员。错误原因：[ Optional int parameter 'addType' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type. ]】
备注：
1）MS 是lts1.20.14版本 和2.8.1版本
2）MS服务器和被测服务环境网络没问题。
3）Postman中请求头里的参数也都copy到ms中

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/232777937-dfb32a4d-6106-4af2-9d2b-979cbbc57b38.png)

**Comment by youliyuan-fit2cloud** [comment]
https://blog.csdn.net/qq13933506749/article/details/119535721

参考上诉连接，已远程确认非问题。
