### ISSUE TITLE
[BUG] 接口文档不能展示参数是否必填属性

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23780]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

接口文档不能展示参数是否必填属性

### 重现步骤

在api中可设置参数是否必填属性
![企业微信截图_16818741152548](https://user-images.githubusercontent.com/103925124/232959491-120ae6d6-2c4b-4f38-9034-2f0df551e461.png)
在文档中展示不出来，影响研发和测试联调效率，需尽快修复下
![企业微信截图_16818742573594](https://user-images.githubusercontent.com/103925124/232959602-e94df7ad-da37-4831-b20c-435736d31fb5.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.9.0已修复
