### ISSUE TITLE
第三方浏览器兼容问题(QQ浏览器)[BUG]

### ISSUE THREAD

**Issue by shisanTJ** [metersphere/metersphere#2378]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.2-d59d4b5f
**Bug 描述**
简要描述您碰到的问题
接口测试的首页ui存在错位
**Bug 重现步骤**
1.  进入接口测试模块
2. 点击首页
3. 查看场景用例数量统计模块
4. 

**期待的正确结果**
正确情况下应该是什么样的？
ui正常显示  无错位
**截图**
如果有截图，请附上截图.
![UI错位](https://user-images.githubusercontent.com/58593579/116355934-26083980-a82d-11eb-8ce0-f527862c151c.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复兼容性问题

**Comment by zyyfit** [comment]
最新版已修复
