### ISSUE TITLE
[BUG]文件管理上传的文件，无法拿到源文件读取内容

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#23799]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1.文件管理上传一个文件，从接口看是http开头的地址，实际地址在服务器上为【/opt/metersphere/data/minio/metersphere/项目id/XXX】
![image](https://user-images.githubusercontent.com/111938588/233001628-f9f81fae-1d56-4d9c-9da6-59728859edf7.png)
2.服务器上查看，上传的文件其实是文件夹
![image](https://user-images.githubusercontent.com/111938588/233001944-5fe8c7b5-7785-4a26-8336-76ea3328a3f7.png)
3.文件夹里面，是xl.meta这样的文件，无法打开

所以，如果需要打开上传的文件，读取里面的内容，现在不知道要怎么弄？以前比较早的版本，文件是传到/opt/metersphere/data/body下面的，且都是实际的文件，可以读取的

### 重现步骤

文件管理上传文件，怎么拿到源文件？

**Comment by song-tianyang** [comment]
您好，目前文件管理的文件是直接放在MinIO里面的。 
您图里的文件目录，是MinIO为文件管理生成的一系列文件。具体详情您可以参阅MinIO的技术文档。
目前程序里使用文件管理上传的文件，是需要通过“文件引用”来进行操作的。程序会通过MinIO来获取真实文件。

如果您要通过绝对路径来使用这个文件，您可以直接在/opt/metersphere/data/目录下，手动将文件上传到您在这个目录下自定义的文件夹里。

**Comment by conansharp** [comment]
> 您好，目前文件管理的文件是直接放在MinIO里面的。 您图里的文件目录，是MinIO为文件管理生成的一系列文件。具体详情您可以参阅MinIO的技术文档。 目前程序里使用文件管理上传的文件，是需要通过“文件引用”来进行操作的。程序会通过MinIO来获取真实文件。
> 
> 如果您要通过绝对路径来使用这个文件，您可以直接在/opt/metersphere/data/目录下，手动将文件上传到您在这个目录下自定义的文件夹里。

文件引用是怎么操作的

**Comment by song-tianyang** [comment]
![image](https://user-images.githubusercontent.com/75963100/233884311-cd2f8ea1-8834-4f58-a725-96dcdd3f9348.png)

在MS的功能中使用文件管理的文件基本上就是这个操作
