### ISSUE TITLE
[FEATURE]脑图编写测试案例未标记为用例标签保存时建议提醒，而不是直接丢弃数据

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#23798]
### MeterSphere 版本

版本:   v2.7.1-9947cfcf

### 请描述您的需求或者改进建议

脑图编写测试用例时，有时会忘记给用例标题打【用例】标签，在保存的时候这部分未打标签的用例会直接丢失。

### 请描述你建议的实现方案

1、保存这类没有标签的用例，在传统视图中不展示即可
2、保存的时候增加提示，还有未标记【用例】的条目，是否继续保存
3、即便不实现，这部分数据应可以在回收站中找到，而非直接丢失
尽可能不要丢失数据，经常会遇到编写了很多用例，由于忘记打标签导致的数据丢失。

**Comment by luty2018** [comment]
你好， 没有标记用例的节点丢失的问题在v2.8.1已经修复了，你可以更新下版本。
未标记用例的节点可能是临时节点，本身系统是支持保存临时节点的，所以系统不会去提示。
