### ISSUE TITLE
[FEATURE]接口模板中加入自定义字段（必填），导入时没有校验自定义字段

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23794]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

接口模板中加入自定义字段（必填），导入时没有校验自定义字段，导致导入后需要手动编辑接口输入自定义字段

### 重现步骤

1. 项目中设置自定义字段
![image](https://user-images.githubusercontent.com/103627487/232999802-c611cbae-2960-4f3b-804f-9c4ab776c1b8.png)
3.导入接口，例如：Swagger 导入,定时同步没有校验 Api 自定义字段,导入后需要手动输入自定义字段
![image](https://user-images.githubusercontent.com/103627487/232998905-5ccfffac-7864-4800-8b5a-664b9e90ef3e.png)
![image](https://user-images.githubusercontent.com/103627487/232999278-f1e43f53-2d73-4f21-8e2d-61496bf47110.png)

**Comment by luty2018** [comment]
转bug处理，v2.10 上

**Comment by luty2018** [comment]
经讨论，暂不支持这个需求。
