### ISSUE TITLE
[BUG]Swagger-ui未授权访问漏洞

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#23796]
### MeterSphere 版本

版本:   v2.8.1-da9fa08c

### 使用外置数据库

否

### 问题描述

漏洞名称
Swagger-ui未授权访问漏洞

### 重现步骤

漏洞描述
Swagger是一个规范和完整的框架，用于生成、描述、调用和可视化 RESTful 风格的 Web 服务，JAVA在金融机构开发语言的地位一直居高不下，而作为JAVA届服务端的大一统框架Spring，便将Swagger规范纳入自身的标准，建立了Spring-swagger项目，所以在实际测试环境中，基于spring框架的swagger-ui接口展示及调试文档页面最为常见。

### 期待的正确结果

漏洞成因
Swagger未开启页面访问限制，Swagger未开启严格的Authorize认证。
漏洞危害
通过翻查文档，得到api接口，点击parameters，即可得到该api接口的详细参数。直接构造参数发包，通过回显可以得到大量的用户信息，包含了手机号，邮箱等。
修复方案
1.Swagger开启页面访问限制。
2.Swagger开启Authorize认证。找到Startup文件，我们看到Swagger的配置如下：``` services.AddSwaggerGen(options => { options.SwaggerDoc("v1", new Info { Title = "YjJob API", Version = "v1" }); options.DocInclusionPredicate((docName, description) => true); });

### 相关日志输出

```shell
/webjars/swagger-ui/index.html
```

### 附加信息

/webjars/swagger-ui/index.html

**Comment by wangjiaxin1100** [comment]
建议给个临时方案，是否可以通过关停的方式，及时解决安全漏洞问题

**Comment by liuruibin** [comment]
您好，我们的swagger文档是可以匿名访问的。部分接口也是匿名的，大部分接口需要通过权限校验才可以进入。如果您发现某个接口可以直接获取私密信息请告知我们，方便我们进行排查修复

**Comment by wangjiaxin1100** [comment]
暂时没有不经认证可以直接获取私密信息的接口，安全同事提示这类接口定义的暴露本身就存在风险，是否可以考虑增加开关，在不同的环境上区分处置，比如测试环境可以开放Swagger API，正式生产环境允许关闭访问。

**Comment by liuruibin** [comment]
您好，您可以从Nginx或其他代理工具中禁用swagger的url，我们默认不会对swagger入口做限制

**Comment by shenkaibo** [comment]
v2 最新版可以在 /opt/metersphere/conf/metersphere.properties 中添加 swagger.enabled=false ，然后 msctl restart 下
