### ISSUE TITLE
[BUG][【接口定义】Tcp Mock-后置脚本设置响应报文编辑为GBK-其它接口调用TCP Mock时，接收的响应报文用GBK编码解析中文乱码

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23795]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

用后置脚本在Tcp Mock响应报文编辑格式为GBK，其它接口调用TCP Mock时，接收的响应报文用GBK编码解析中文乱码

### 重现步骤

1.创建一个tcp mock
2.增加后置脚本，在后置脚本中将字符串编码设置为GBK，然后在响应报文中输出
3.用TCP 客户端调用该mock，字符串用GBK编码解析并输出

### 期待的正确结果

用TCP 客户端调用该mock，字符串用GBK编码解析并输出的中文不乱码

### 附加信息

1.tcp mock 请求参数
![image](https://user-images.githubusercontent.com/45531073/233003330-f2e2c4bb-276d-4998-be1c-170925ac3bca.png)
2.设置 tcp mock 响应报文编码
![image](https://user-images.githubusercontent.com/45531073/233003708-5ac940ab-e518-45bc-9679-fbd63cce7271.png)

3.用TCP 客户端调用mock 
![image](https://user-images.githubusercontent.com/45531073/233004306-4e1d468a-570a-4aab-8e7e-26a0e01ec440.png)

代码如下：
   Socket socket = new Socket("ip","端口");
            System.out.println("连接服务器成功");

            // 获取输入流和输出流
            InputStream inputStream = socket.getInputStream();
            OutputStream outputStream = socket.getOutputStream();

            // 向服务器发送数据
            String message = "33";
            outputStream.write(message.getBytes());
            //System.out.println("发送消息：" + message);

            // 读取服务器响应数据
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
            String response = reader.readLine();
            System.out.println("收到服务器消息：" + new String(response.getBytes(),"gbk"));
            System.out.println(response);
            // 关闭流和Socket连接
            outputStream.close();
            inputStream.close();
            socket.close();

**Comment by song-tianyang** [comment]
TCP的后置脚本编写中，不要这么转。用ISO-8859-1。ISO-8859-1 可以作为中间编码，不会导致数据丢失。

所以后置脚本中改成这样：
![image](https://user-images.githubusercontent.com/75963100/233261610-5b7cb6e4-a942-4427-8cf1-bd164465b28d.png)

并且，tcp-mock服务在返回内容时，是将返回的字符串按照服务器默认的编码格式(如UTF-8)来转换字节流的。

那么在客户端需要这样来处理：
![image](https://user-images.githubusercontent.com/75963100/233261954-773f0390-e184-43b1-b264-11d111130051.png)


最后：由于tcp-mock最后会将返回的字符串按照ms所在服务器的默认编码格式进行编码，如果确实需要GBK格式的数据的话，最方便的方式还是将ms部署到默认编码格式为GBK的机器中。否则就会变得略微麻烦一些。

**Comment by liushuneng** [comment]
@song-tianyang  客户系统是GBK格式返回的，所以需要TCP-mock字符串也返回GBK格式
