### ISSUE TITLE
[BUG]测试计划中设置定时任务，告警设置为【执行失败】发消息。但是当报告结果为误报时，也发告警消息了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23793]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

[BUG]测试计划中设置定时任务，告警设置为【执行失败】发消息。但是当报告结果为误报时，也发告警消息了。
操作：
1）设置误报规则
2）设置项目环境>>全局断言：开启误报，选择【请求同时包含误报和失败断言，请求结果处理为： 误报】
3）创建测试计划中，并且只添加一个自动化脚本，设置定时任务，发消息设置为【执行失败】发消息
4）结果：报告结果为误报，但是还发消息了。

备注：接口测试中设置定时任务是没有问题的，

### 重现步骤

[BUG]测试计划中设置定时任务，告警设置为【执行失败】发消息。但是当报告结果为误报时，也发告警消息了。
操作：
1）设置误报规则
2）设置项目环境>>全局断言：开启误报，选择【请求同时包含误报和失败断言，请求结果处理为： 误报】
3）创建测试计划中，并且只添加一个自动化脚本，设置定时任务，发消息设置为【执行失败】发消息
4）结果：报告结果为误报，但是还发消息了。

备注：接口测试中设置定时任务是没有问题的

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/232992083-d613e1b5-6617-46fa-bc4e-491d824153e4.png)
![image](https://user-images.githubusercontent.com/78218624/232992241-19e5102d-69a9-42e1-8e27-a2e1f77991e2.png)
![image](https://user-images.githubusercontent.com/78218624/232992413-7414a4df-f449-45e7-a668-c65083ec3948.png)
![image](https://user-images.githubusercontent.com/78218624/232992580-2d93efd1-061b-4c8f-a9fc-cf4fd239eabe.png)

**Comment by song-tianyang** [comment]
测试计划这里，后台判断最终执行结果时，只会区分为成功和失败。

也就是说，如果成功率不为100%，就会按照失败处理。

如果有成功和误报这两种情况存在，因为成功率不是100%，测试计划也会发送通知提醒用户。
