### ISSUE TITLE
[BUG]UI测试不能清空react的某些输入框

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#23803]
### 联系方式

蒋林峰

### MeterSphere 版本

1.20.20-lts&2.8.1

### 使用外置数据库

否

### 问题描述

在1.20.20-lts版本，有客户遇到了这种情况，UI测试没有勾选“追加输入”，但是上一次输入的内容还在
<img width="850" alt="032884a4ab1fa9e051676d66ef4cf71" src="https://user-images.githubusercontent.com/88763608/233023295-dd91f5df-8c2d-4b52-b13c-ecc240193ee8.png">
在2.8.1版本，也有客户遇到了这种情况，UI测试没有勾选“追加输入”，但是上一次输入的内容还在
![image](https://user-images.githubusercontent.com/88763608/233025361-eb396469-e278-4d14-afaa-8c87166c7718.png)

### 重现步骤

本地用MS做为被测端，测试了自动化场景页面高级搜索弹窗中的输入框和场景详情中的输入框，都没有复现。
上面两个客户被测服务前端都是用react写的，会跟前端框架有关系吗？

**Comment by xiaomeinvG** [comment]
您好，感谢您提出的问题，webdriver 的 element.clear在react 组件的操作上确实是有问题的，或者说这是react组件预期就是这样，只能通过模拟人为操作清空输入框。关于这个问题webdirver 和selenium 的官方 也认为这不是一个问题，而是这个组件自身的期望结果。具体详情可以查看以下链接：
https://github.com/SeleniumHQ/selenium/issues/6863
