### ISSUE TITLE
[FEATURE]测试计划关联接口场景用例两处优化

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#23802]
### MeterSphere 版本

v2.8.0-ac76fee1

### 联系方式

2297310871@qq.com

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/233024454-278b81b5-204d-4d20-90da-bae62151f450.png)
![图片](https://user-images.githubusercontent.com/23067502/233024509-6b07281f-1fc7-4246-8f81-a2204825dc2b.png)

### 请描述你建议的实现方案

1.希望关联用例的时候可以筛选已完成的用例进行关联；
2.已经关联的用例希望可以选择进行取消关联。

**Comment by luty2018** [comment]
1.可以在高级搜索中进行过滤
![image](https://user-images.githubusercontent.com/36292514/233049691-550fffe8-f8e7-4e74-9369-9f4550bbf4eb.png)
2.可以在批量处理中进行取消关联
![image](https://user-images.githubusercontent.com/36292514/233049796-f751fd75-ee84-4b14-977b-d8c958a2a424.png)
