### ISSUE TITLE
[BUG]测试计划》运行配置，里面有些按钮有问题

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#23801]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

1.测试计划》运行配置，保存并执行，并不能保存配置；单独的保存按钮才有效
![image](https://user-images.githubusercontent.com/111938588/233027403-e70a4f49-3166-4651-999a-9c2a62e185b5.png)
2.测试计划》运行配置，资源池运行不勾选，也会按照这个模式去运行的
![image](https://user-images.githubusercontent.com/111938588/233022636-900f4ce7-53e1-4af1-8e64-aa400caa5de9.png)

### 重现步骤

资源池运行这个，可以选择本机或者有部署其他地方的，但应该勾选了按钮才有效吧，现在是未勾选也按照这个去执行测试计划的

**Comment by 13290445582** [comment]
感谢反馈，问题一在最新版本并未复现，建议升级至最新版本；问题二其他用户已反馈，计划于v2.9.0修复。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
