### ISSUE TITLE
[BUG]切换到脑图视图，通过左侧的测试用例树查看用例时，脑图不更新

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#2380]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.9.2

**Bug 描述**
切换到脑图视图，通过左侧的测试用例树查看用例时，脑图不更新

**Bug 重现步骤**
1.  点击测试用例树中的一个测试用例节点，基于脑图视图查看测试用例，脑图方式显示测试用例正确；
2. 依然基于脑图视图，但是鼠标点击其他测试用例节点，脑图视图的该节点下的测试用例不刷新

**期待的正确结果**
脑图视图的测试用例应该随着测试节点树选择的结果同步更新

**截图**
![image](https://user-images.githubusercontent.com/60059766/116356695-310f9980-a82e-11eb-90fb-0bc603bdbdf0.png)

**Comment by zyyfit** [comment]
您好，是必现的吗？没复现出来，能详细描述一下操作步骤吗

**Comment by 462548187** [comment]
就是必现的，你内容太少了，没复现

**Comment by xulinde** [comment]
1.9.2已修复
