### ISSUE TITLE
[BUG]接口自动化自定义get请求，请求体选择  x-www-form-urlencoded ，值没有没有拼接到URL上。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#23805]
### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

1.自定义请求没有把请求体是  x-www-form-urlencoded 的值拼接到url上。

### 重现步骤

1.接口自动化创建自定义请求，请求体选择 x-www-form-urlencoded ，输入名称为id ，值为 {"msg":{"id":"1","age":"18"}}，编码格式选择是。
![image](https://user-images.githubusercontent.com/55130444/233052974-5811a94b-81b0-486d-bc94-786b922c5332.png)
2.执行自定义请求会发现增加的请求体没有拼接到url上。

### 期待的正确结果

1.期待自定义请求可以将请求体是 x-www-form-urlencoded 的内容拼接到url上。

### 附加信息

1.case中可以把请求体是 x-www-form-urlencoded 的内容拼接到url上
![image](https://user-images.githubusercontent.com/55130444/233053761-922837a3-9002-4260-8f0f-d4cc784ca6e6.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
