### ISSUE TITLE
[BUG]【QQ浏览器】接口自动化内响应结果断言规则--推荐jsonpath断言功能失效

### ISSUE THREAD

**Issue by shisanTJ** [metersphere/metersphere#2381]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.82
**Bug 描述**
简要描述您碰到的问题
接口自动化的断言功能内的推荐jsonpath表达式失效
**Bug 重现步骤**
1.  接口测试模块
2. 接口自动化模块
3. 选择一个场景
4. 在接口内已有响应结果内选择断言规则
5. 选择推荐jsonpath断言;
6. 点击相关字段
7. 结果是没有添加相关的jsonpath表达式

**期待的正确结果**
正确情况下应该是什么样的？
点击的话会出现相关jsonpath表达式
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是必现的吗？能描述一下具体的复现步骤吗？没有复现出来

**Comment by shisanTJ** [comment]
QQ浏览器...
复现步骤:
1接口测试里面打开一个快捷调试
2输入一个接口地址进行测试;
3.在响应结果里添加断言
4.选择推荐jsonpath断言
5.点击弹窗里的响应内容
6.结果:没有出现推荐的jsonpath表达式


| |
十三画一个我
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月29日 ***@***.***> 写道：

您好，是必现的吗？能描述一下具体的复现步骤吗？没有复现出来

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/2378

**Comment by zyyfit** [comment]
最新版已修复
