### ISSUE TITLE
[BUG]node-controller创建容器失败时，性能测试没有置位Error状态

### ISSUE THREAD

**Issue by baiyous** [metersphere/metersphere#23819]
### 联系方式

bai.you@qq.com

### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

node-controller创建容器失败时，性能测试没有置位Error状态

### 重现步骤

源码PerformanceTestService 在 startEngine（）时，本身因为engine.start()抛出的异常，结果捕获的时候直接engine.stop()，再此抛出异常，导致后续的修改状态逻辑没有正确执行

**Comment by liuruibin** [comment]
您好，我在测试中没有发现这个问题，错误信息可以记录到表里， 您具体使用场景是什么

**Comment by baiyous** [comment]
![5252DBAC-E596-4a1f-8C19-B8B886B8494A](https://user-images.githubusercontent.com/79647146/233584787-fb673c5f-3127-440c-8ac6-963743117a3a.png)

**Comment by youliyuan-fit2cloud** [comment]
> 

很抱歉，我们目前没有遇到你这种情况，源码部署方式需要自行解决看看，感觉您的理解和支持～
