### ISSUE TITLE
helm 部署2.8.1 提示没有这个configmap

### ISSUE THREAD

**Issue by 710210668** [metersphere/metersphere#23827]
### 请描述您的问题

Unable to attach or mount volumes: unmounted volumes=[opt-metersphere-config]

**Comment by 710210668** [comment]
values.yaml 配置的mysql 和redis 为false ,  看提示找不到 configmap metersphere-config 里面的redisson.yml 相关配置，但我看metersphere-config.yaml  的配置需要if .Values.redis.enabled  才会配置redisson.yml，这个怎么办

**Comment by liuruibin** [comment]
您可以自行创建configmap
