### ISSUE TITLE
[BUG]Testplan的"测试进度"与测试报告中的"执行率"不一致

### ISSUE THREAD

**Issue by suchaonan** [metersphere/metersphere#23826]
### 联系方式

su15275529968@163.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

是

### 问题描述

![TmMSm6WMFz](https://user-images.githubusercontent.com/31874919/233342043-f7ab6203-189e-4ca1-9a13-ea0dab171a0e.png)
![dPwfacwavi](https://user-images.githubusercontent.com/31874919/233342059-b585a30d-8dab-42cc-8024-e149ef83dd4c.png)

### 重现步骤

1. 创建一个testplan
2. 执行完其中所有的测试用例
3. 查看测试计划中这个testplan的"测试进度"与该testplan的测试报告中的"执行率"

### 期待的正确结果

在测试计划列表中这个testplan的"测试进度"应该为100%, 测试报告中的"执行率"也应该为100%

**Comment by 13290445582** [comment]
你好，测试进度与执行率的不一致，是不是测试计划内在执行完毕后，又添加了用例进去，导致报告内执行率100%，测试进度99.9%呢，再执行下该测试计划试下呢。

**Comment by suchaonan** [comment]
确认了测试计划的全部测试用例个数以及测试报告中的全部用例个数一致, 并且筛选到"未执行"的测试用例个数为0, "测试进度"仍然显示99.9%

https://user-images.githubusercontent.com/31874919/233565230-cb42e8d3-bece-4670-9a13-47ec418d7d96.mp4

**Comment by 13290445582** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/128017892/233566591-3edb3663-5713-4caf-9f61-c332802af67d.png">
看下这里的报告数据呢

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
