### ISSUE TITLE
[BUG]禁用本地执行,自定义请求sql,不输入名称,调试时提示“调用资源池执行失败,请检查资源池是否配置正常”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#23828]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

禁用本地执行，自定义sql请求,不输入名称,调试时提示“调用资源池执行失败，请检查资源池是否配置正常”

### 重现步骤

1.禁用本地执行，创建场景，添加自定义sql请求，不输入名称
![image](https://user-images.githubusercontent.com/103627487/233366135-b09a7840-37b5-484d-9266-73b48456149d.png)
2.点击调试，出现提示“调用资源池执行失败，请检查资源池是否配置正常”
![image](https://user-images.githubusercontent.com/103627487/233367725-888bdea3-25b0-4378-83ad-48dbd1208259.png)
3.场景内多次点击调试还有个现象，点击调试后，一直卡住没反应
![image](https://user-images.githubusercontent.com/103627487/233369413-514c1550-d81c-4f00-920e-80d0b2c9d0d7.png)
等待一会页面报错
![image](https://user-images.githubusercontent.com/103627487/233370125-4d6ef537-d201-4e0b-8ca9-7e7626204980.png)
4.场景列表批量执行，报告里控制台报错
![image](https://user-images.githubusercontent.com/103627487/233368356-21543e52-a233-47fc-98fc-b0fb2bf6c727.png)

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0中已修复。
