### ISSUE TITLE
[BUG]多个结果其总数matchNr，通过vars.getObject拿到为什么不是int的

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#23831]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

通过提取有多个结果的数据，有matchNr获取总数，${XXX_matchNr}这个值是int类型的；vars.getObject("XXX")获取的变量是本身的数据类型，那vars.getObject("XXX_matchNr")获取的为什么是str类型的

### 重现步骤

比如变量a有多个结果，那么${a_matchNr}即其总数，这个值可直接用于循环；但是vars.getObject("a_matchNr")拿到的不是int，不能直接用于循环，这挺奇怪的

**Comment by 13290445582** [comment]
你好，感谢反馈，我们的 ${} 变量跟jmeter是保持一致的，jmeter里返回什么类型，我们这里就返回什么类型。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
