### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by rbsrcy** [metersphere/metersphere#23833]
### MeterSphere 版本

v1.20.21-lts-6359b12e

### 联系方式

zhuoshangyi@hntsp.com

### 请描述您的需求或者改进建议

使用场景过程中发现有个地方使用不是很方便，场景里面的步骤只能通过复制或者引用两种方式中一种使用case或者api，
1、使用复制不方便维护，得两边修改
2、使用引用，虽然可以只修改一边，但是被引用的步骤的前置或者后置步骤不能在场景中禁用或者启用，只能修改被引用的case。不方便，建议可以双向修改。
3、建议强化环境中的全局前置步骤功能，给每个全局步骤配置触发条件，每个case可以主动或者被动（通过触发条件）关联全局步骤，这样可以减少case中前置步骤，同时提高灵活性。

**Comment by luty2018** [comment]
感谢建议， 这个我们会在v3.0讨论排期。
