### ISSUE TITLE
[BUG]用meterSpherer在接口定义中导出swagger格式，请求体的内容没有导出来，只导出来了url

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#23832]
### 联系方式

jianqiang.liu@fit2cloud.com

### MeterSphere 版本

v2.8.X

### 使用外置数据库

否

### 问题描述

用meterSpherer在接口定义中导出swagger格式，请求体的内容没有导出来，只导出来了url

### 重现步骤

<img width="886" alt="image" src="https://user-images.githubusercontent.com/40912189/233525819-92c06a9b-5269-483b-b7ce-56d5f75abfdc.png">
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/40912189/233526046-0ffb1b9e-8e38-479c-873a-54b7b34c9f00.png">

**Comment by xiaomeinvG** [comment]
感谢反馈，该问题将在下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.9.0中已修复。
