### ISSUE TITLE
[BUG]【接口自动化】场景里含有循环控制器，点击调试后立马点击停止，后台进程实际并没有停止。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23859]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【接口自动化】场景里含有循环控制器，点击调试后立马点击停止，页面看着是停止了，但是后台进程并没有停止，查看的是/opt/metersphere/logs/api-test下的ms-jmeter-run-log，发现一直在打印，直到循环执行结束才停下。

### 重现步骤

【接口自动化】场景里含有循环控制器，点击调试后立马点击停止，页面看着是停止了，但是后台进程并没有停止，查看的是/opt/metersphere/logs/api-test下的ms-jmeter-run-log，发现一直在打印，直到循环执行结束才停下。
![image](https://user-images.githubusercontent.com/104960608/233615910-c6854489-03ee-4b70-afeb-e933bb2ea80d.png)

![image](https://user-images.githubusercontent.com/104960608/233615990-31ff4575-4c23-45c7-be24-55c467c1bcf4.png)

**Comment by fit2-zhao** [comment]
已经开始执行中的线程不能强制stop，目前使用的是Thread 的 interrupt()，不会立马终止。
