### ISSUE TITLE
[BUG]场景中上传 csv文件，将该 csv文件 删除，再次上传同一个 csv 文件，服务器上之前的 csv 文件还在，并没有被删除

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23852]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.21

### 使用外置数据库

否

### 问题描述

场景中上传 csv文件 运行请求后，将该 csv文件 删除掉，再次上传同一个 csv 文件，服务器之前的 csv 文件还在，并没有被删除

### 重现步骤

场景中上传 csv文件 运行请求后，将该 csv文件 删除掉，再次上传同一个 csv 文件，服务器之前的 csv 文件还在，并没有被删除
![image](https://user-images.githubusercontent.com/104960608/233593221-ff5f9e1c-6df0-4087-8d9b-f9f0e9ab8057.png)

![image](https://user-images.githubusercontent.com/104960608/233594217-41faf30e-727b-4501-aa40-0af1276f83e0.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！目前未同步删除是为了防止其它场景引用造成无法执行问题。后续v3.0会将文件保到文件服务器，则不会存在该问题。
