### ISSUE TITLE
[FEATURE] 【接口测试】-tcp mock 返回字符串支持设置编码格式

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23875]
### MeterSphere 版本

2.8.1

### 联系方式

82973834@qq.com

### 请描述您的需求或者改进建议

目前tcp mock返回的字符串采用默认编码格式进行编码的，客户有些系统接口采用GBK编码格式的进行编码的，这时候客户系统调用tcp mock接收的中文字符是乱码的

### 请描述你建议的实现方案

tcp mock支持配置返回编码格式

### 附加信息

![image](https://user-images.githubusercontent.com/45531073/233816081-49e8226d-eb30-46b5-9573-72db0e38ffb8.png)

**Comment by luty2018** [comment]
v2.9
