### ISSUE TITLE
[QUESTION]metersphere的kafka发送jmeter的引擎日志能保证顺序吗

### ISSUE THREAD

**Issue by MrZbb** [metersphere/metersphere#23872]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/31841743/233790875-0dead011-d415-4787-8d9a-6d97a7b7780f.png)
![image](https://user-images.githubusercontent.com/31841743/233790884-016e908d-22d4-4726-a002-44a47d13b4a3.png)
我看生产者的log4j2就配置了个这个kafkaappender,在topic多个分区的情况下也没做hash。。。那不就是日志是很大概率是乱的吗，而且我本地也测试了下，可以看到日志显示顺序确实乱了

**Comment by liuruibin** [comment]
感谢提醒，我们先排查一下问题

**Comment by MrZbb** [comment]
> 感谢提醒，我们先排查一下问题
> 
> 事实上jmeter配置日志的时候仅指定topic名称，如果分区有多个的话顺序确实不能保证。 <img alt="image" width="1628" src="https://user-images.githubusercontent.com/23045261/233815772-847e6a1b-4e6b-40d2-bfd3-b3b2944b65e7.png"> 我检查了很多个测试结果的日志，这种情况并不常见。而且即便上下2行顺序不一致也并不影响阅读。如果您介意这个，您可以将分区数设置为1

嗯我看代码实现中，是把消费到的多条日志组合成一条存数据库，根据part排序，我在想如果data-stream部署多台的时候，会不会出现顺序非常乱的情况，因为多台的时候一个消费组下不确定是哪台消费的，就算kafka消息中心是顺序的，但是part中的信息会被分散到多个消费实例上。所以是否可以考虑每条日志还是以数据库一行为主存入，查询的时候根据日志本身的时间信息进行排序。
