### ISSUE TITLE
[BUG] 场景名称是否同名校验错误，导致场景列表同名场景很多，不好区分

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#23886]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

场景名称是否同名校验错误，导致场景列表同名场景很多，不好区分
![image](https://user-images.githubusercontent.com/103925124/233819129-f9e48cd3-4a5e-49e2-aab0-8d9985cb6993.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/103925124/233819129-f9e48cd3-4a5e-49e2-aab0-8d9985cb6993.png)
场景名称前面有空格时，还是保存成功，不是场景已存在
![image](https://user-images.githubusercontent.com/103925124/233819196-b0476bf0-b887-4e04-851c-379ce37aef3e.png)
在场景列表场景名称展示无差异，导致无法分辨
![image](https://user-images.githubusercontent.com/103925124/233819248-68791163-4772-423e-b064-403a3ad8eadd.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复
