### ISSUE TITLE
[BUG] 测试计划下的测试用例列表页面，设置表头显示字段时，自定义字段无法显示

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#23899]
### 联系方式

15375857626

### MeterSphere 版本

V2.8.1、v2.2.0

### 使用外置数据库

否

### 问题描述

在项目设置-模板管理-测试用例模板中，客户自定义了一个测试用例字段，例如定义了一个“是否自测”字段。定义好后，回到测试跟踪-功能用例列表页中，点击小齿轮按钮，可以设置自定义的表头字段，将其显示到列表中。但是，测试计划-功能测试用例列表中，点击小齿轮按钮，却找不到我自定义的“是否自测”这个字段，无法将它显示到测试计划的功能测试用例列表里面。

### 重现步骤

![e4c04b6cd3969fa8602a5c8a3c9ad13](https://user-images.githubusercontent.com/47737772/233824124-616d54c6-b7b6-4ac5-977d-7150193c8feb.png)
![5ce20fe7644f2d6ee756094dd713095](https://user-images.githubusercontent.com/47737772/233824123-03255ee3-d20c-48e1-9cc4-54a72894b119.png)
![5099adb5bf2e510d12d5ffc60e17813](https://user-images.githubusercontent.com/47737772/233824125-792fc70f-ed1a-4ca5-89a3-1dd7b2fdc4fa.png)

### 期待的正确结果

在测试计划-功能测试用例列表中，点击小齿轮，应该要可以看到测试用例模板自定义的字段。

**Comment by 13290445582** [comment]
感谢反馈，目前设计如此，测试计划-功能测试用例处小齿轮与高级搜索均不显示自定义字段。

**Comment by blooze123** [comment]
好的，谢谢！
