### ISSUE TITLE
[BUG]性能测试报告错误记录编码问题

### ISSUE THREAD

**Issue by bestdd** [metersphere/metersphere#239]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.1  master
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/7333223/90224939-1386d500-de43-11ea-901e-ba28b942d427.png)

**Bug 重现步骤**
1.  【接口测试】中设置 断言，包含中文
2. 创建【性能测试】，运行，在【性能测试报告】错误统计页面，断言中文显示为编码，显示异常

**期待的正确结果**
正确情况下应该是什么样的？
性能测试【性能测试报告】错误统计页面 中文需要正常显示
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue #238  重复
