### ISSUE TITLE
[QUESTION] 从2.2.0升级至2.8.1版本后，插件上传成功，但ParallelController等都不可用了

### ISSUE THREAD

**Issue by PolkFan** [metersphere/metersphere#23937]
### 请描述您的问题

从2.2.0升级至2.8.1版本后，插件上传成功，但都不可用，包括官方提供的 ParallelController，基于 DummySampler 开发的插件均无法使用，日志报：

2023-04-23 20:22:08,237  WARN .support.DefaultHandlerExceptionResolver: 207 - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Could not resolve type id 'io.metersphere.plugin.parallel.controller.MsParallelController' as a subtype of `io.metersphere.plugin.core.MsTestElement`: no such class found]

![企业微信截图_1682252754212](https://user-images.githubusercontent.com/24569669/233840060-9eca8027-574e-4554-bdcc-298b59f7e633.png)
![企业微信截图_16822527824675](https://user-images.githubusercontent.com/24569669/233840066-b3dcb2a1-7bb3-4184-8ce5-08d80e7a2ac0.png)

ParallelController 插件（无改动）：
[metersphere-plugin-ParallelController-1.0.1-jar-with-all-dependencies.jar.zip](https://github.com/metersphere/metersphere/files/11303728/metersphere-plugin-ParallelController-1.0.1-jar-with-all-dependencies.jar.zip)

**Comment by fit2-zhao** [comment]
感谢反馈，未曾复现你的问题，插件在系统设置-插件管理中上传 使用场景选择“接口测试”，目前没做热加载所以上传成功后需要重启api-test 服务，然后就能正常使用了。

![image](https://user-images.githubusercontent.com/70558837/233909480-e991faf2-66d8-4e96-983e-807acb988139.png)

![image](https://user-images.githubusercontent.com/70558837/233909246-c2cc67bd-2d46-4b7e-bf64-78d9cb3565b5.png)

**Comment by PolkFan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PolkFan** [comment]
今天卸载重新加载配置重装后，上传插件重启可以使用了。应该是升级平台产生的一些异常导致。
