### ISSUE TITLE
[FEATURE] 基于 DummySampler 插件开发的自定义请求无法传入自定义变量

### ISSUE THREAD

**Issue by PolkFan** [metersphere/metersphere#23938]
### MeterSphere 版本

v2.2.0

### 联系方式

交流群8 - Fan

### 请描述您的需求或者改进建议

基于 DummySampler 插件开发的自定义请求，在场景中使用 ${url} ，执行自定义脚本时无法先提取值传入DummySampler，无法参数化。期望可以像jmeter一样前置提取值后再执行自定义请求。

升级到2.8.1由于报错暂无法验证（已提另一个问题），或有其他可参数化的方法可说明下，谢谢。

### 请描述你建议的实现方案

期望可以像jmeter一样前置提取值后再执行自定义请求。

### 附加信息

![image](https://user-images.githubusercontent.com/24569669/233840311-72cb1e93-7a4b-41a4-a62c-6682bfe37fc9.png)
![image](https://user-images.githubusercontent.com/24569669/233840362-4e0b17a3-cd05-4a00-a20b-a20a59aa5c8c.png)

**Comment by fit2-zhao** [comment]
从响应内容来看是json处理报错了，可以先检查下插件，目前插件使用方式和JMeter类似，这种变量都可以使用。
![image](https://user-images.githubusercontent.com/70558837/233910290-009c69fe-1cb6-4324-815a-46ec98a77143.png)

**Comment by PolkFan** [comment]
![image](https://user-images.githubusercontent.com/24569669/233920152-59327701-b943-43e8-8485-685072cd6150.png)
![image](https://user-images.githubusercontent.com/24569669/233919815-06632aff-8950-4026-8050-4c6ce5d40d06.png)
这里是插件中添加的日志打印，证明自定义变量没有进入插件内

**Comment by PolkFan** [comment]
> 从响应内容来看是json处理报错了，可以先检查下插件，目前插件使用方式和JMeter类似，这种变量都可以使用。 ![image](https://user-images.githubusercontent.com/70558837/233910290-009c69fe-1cb6-4324-815a-46ec98a77143.png)

这个报错是因为自定义变量是个Json，解析时打印的是 ${xxx-token}导致的异常
