### ISSUE TITLE
[BUG]从2.6.0升级到2.8.1版本，引入了jar包，前置脚本操作excel的代码不执行

### ISSUE THREAD

**Issue by Wangjipeng163** [metersphere/metersphere#23939]
### 联系方式

18311193299@163.com

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

引入了jar包，操作excel的代码不执行

### 重现步骤

jar包代码

`import java.io.*;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.io.File;
import java.io.IOException;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.usermodel.DateUtil;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class ExcelUtils {

    private final String XLS = "xls";
    private final String XLSX = "xlsx";
    private final DateFormat FORMAT = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    private final Integer page = 0;
    private String excelPath = "";

    public ExcelUtils(String path) {
        excelPath = path;
    }

    /**
     * 输出数据到自定义模版的Excel输出流
     *
     * @param excelTemplate 自定义模版文件
     * @param data          数据
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public void writeDataToTemplateOutputStream(File excelTemplate, List<List<Object>> data) throws IOException {
        Workbook book = getWorkbookFromExcel(excelTemplate);
        writeDataTWorkbook(null, data, book, 0);
        writeWorkbookToOutputStream(book, new FileOutputStream(excelTemplate));
    }

    /**
     * 从Excel文件获取Workbook对象
     *
     * @param excelFile Excel文件
     * @return Workbook对象
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public Workbook getWorkbookFromExcel(File excelFile) throws IOException {
        try (
                InputStream inputStream = new FileInputStream(excelFile);
        ) {

            if (excelFile.getName().endsWith(XLS)) {
                return new HSSFWorkbook(inputStream);
            } else if (excelFile.getName().endsWith(XLSX)) {
                return new XSSFWorkbook(inputStream);
            } else {
                throw new IOException("文件类型错误");
            }
        }
    }

    /**
     * 把Workbook对象内容输出到Excel文件
     *
     * @param book Workbook对象
     * @param file Excel文件
     * @throws FileNotFoundException 找不到文件异常，文件已创建，实际不存在该异常
     * @throws IOException           输入输出异常
     */
    public void writeWorkbookToFile(Workbook book, File file) throws FileNotFoundException, IOException {
        if (!file.exists()) {
            if (!file.getParentFile().exists()) {
                file.getParentFile().mkdirs();
            }
            file.createNewFile();
        }
        try (
                OutputStream outputStream = new FileOutputStream(file);
        ) {
            writeWorkbookToOutputStream(book, outputStream);
        }
    }

    /**
     * 把Workbook对象输出到Excel输出流
     *
     * @param book         Workbook对象
     * @param outputStream Excel输出流
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public void writeWorkbookToOutputStream(Workbook book, OutputStream outputStream) throws IOException {
        book.write(outputStream);
    }

    /**
     * 输出数据到Workbook对象中指定页码
     *
     * @param title 标题，写在第一行，可传null
     * @param data  数据
     * @param book  Workbook对象
     * @param page  输出数据到Workbook指定页码的页面数
     */
    public void writeDataToWorkbook(List<String> title, List<List<Object>> data, Workbook book, int page) {
        Sheet sheet = book.getSheetAt(page);

        Row row = null;
        Cell cell = null;

        // 设置表头
        if (null != title && !title.isEmpty()) {
            row = sheet.getRow(0);
            if (null == row) {
                row = sheet.createRow(0);
            }

            for (int i = 0; i < title.size(); i++) {
                cell = row.getCell(i);
                if (null == cell) {
                    cell = row.createCell(i);
                }
                cell.setCellValue(title.get(i));
            }
        }

        List<Object> rowData = null;
        for (int i = 0; i < data.size(); i++) {

            row = sheet.getRow(i + 1);
            if (null == row) {
                row = sheet.createRow(i + 1);
            }

            rowData = data.get(i);
            if (null == rowData) {
                continue;
            }
            for (int j = 0; j < rowData.size(); j++) {
                cell = row.getCell(j);
                if (null == cell) {
                    cell = row.createCell(j);
                }
                setValue(cell, rowData.get(j));
            }
        }
    }

    /**
     * 输出数据到Workbook对象中指定页码
     *
     * @param title 标题，写在第一行，可传null
     * @param data  数据
     * @param book  Workbook对象
     * @param page  输出数据到Workbook指定页码的页面数
     */
    public void writeDataTWorkbook(List<String> title, List<List<Object>> data, Workbook book, int page) {
        Sheet sheet = book.getSheetAt(page);

        Row row = null;
        Cell cell = null;

        List<Object> rowData = null;
        for (int i = 0; i < data.size(); i++) {

            row = sheet.getRow(i);
            if (null == row) {
                row = sheet.createRow(i);
            }

            rowData = data.get(i);
            if (null == rowData) {
                continue;
            }
            for (int j = 0; j < rowData.size(); j++) {
                cell = row.getCell(j);
                if (null == cell) {
                    cell = row.createCell(j);
                }
                setValue(cell, rowData.get(j));
            }
        }
    }

    /**
     * 读取Excel文件第一页
     *
     * @param pathname 文件路径名
     * @return 第一页数据集合
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public List<List<Object>> readExcelFirstSheet(String pathname) throws IOException {
        File file = new File(pathname);
        return readExcelFirstSheet(file);

    }

    /**
     * 读取Excel文件第一页
     *
     * @param file Excel文件
     * @return 第一页数据集合
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public List<List<Object>> readExcelFirstSheet(File file) throws IOException {
        try (
                InputStream inputStream = new FileInputStream(file);
        ) {

            if (file.getName().endsWith(XLS)) {
                return readXlsFirstSheet(inputStream);
            } else if (file.getName().endsWith(XLSX)) {
                return readXlsxFirstSheet(inputStream);
            } else {
                throw new IOException("文件类型错误");
            }
        }

    }

    /**
     * 读取xls格式Excel文件第一页
     *
     * @param inputStream Excel文件输入流
     * @return 第一页数据集合
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public List<List<Object>> readXlsFirstSheet(InputStream inputStream) throws IOException {
        Workbook workbook = new HSSFWorkbook(inputStream);
        return readExcelFirstSheet(workbook);
    }

    /**
     * 读取xlsx格式Excel文件第一页
     *
     * @param inputStream Excel文件输入流
     * @return 第一页数据集合
     * @throws IOException 错误时抛出异常，由调用者处理
     */
    public List<List<Object>> readXlsxFirstSheet(InputStream inputStream) throws IOException {
        Workbook workbook = new XSSFWorkbook(inputStream);
        return readExcelFirstSheet(workbook);
    }

    /**
     * 读取Workbook第一页
     *
     * @param book Workbook对象
     * @return 第一页数据集合
     */
    public List<List<Object>> readExcelFirstSheet(Workbook book) {
        return readExcel(book, page);
    }

    /**
     * 读取指定页面的Excel
     *
     * @param book Workbook对象
     * @param page 页码
     * @return 指定页面数据集合
     */
    public List<List<Object>> readExcel(Workbook book, int page) {
        List<List<Object>> list = new ArrayList<>();
        Sheet sheet = book.getSheetAt(page);
        for (int i = 0; i <= sheet.getLastRowNum(); i++) {
            Row row = sheet.getRow(i);

            // 如果当前行为空，则加入空，保持行号一致
            if (null == row) {
                list.add(null);
                continue;
            }

            List<Object> columns = new ArrayList<>();
            for (int j = 0; j < row.getLastCellNum(); j++) {
                Cell cell = row.getCell(j);
                columns.add(getValue(cell));
            }

            list.add(columns);
        }

        return list;
    }

    /**
     * 解析单元格中的值
     *
     * @param cell 单元格
     * @return 单元格内的值
     */
    private Object getValue(Cell cell) {
        if (null == cell) {
            return null;
        }
        Object value = null;
        switch (cell.getCellType()) {
            case BOOLEAN:
                value = cell.getBooleanCellValue();
                break;

            case NUMERIC:

                // 日期类型，转换为日期
                if (DateUtil.isCellDateFormatted(cell)) {
                    value = cell.getDateCellValue();
                }

                // 数值类型
                else {

                    // 默认返回double，创建BigDecimal返回准确值
                    value = new BigDecimal(cell.getNumericCellValue());
                }
                break;

            default:
                value = cell.toString();
                break;
        }

        return value;
    }

    /**
     * 设置单元格值
     *
     * @param cell  单元格
     * @param value 值
     */
    private void setValue(Cell cell, Object value) {
        if (null == cell) {
            return;
        }

        if (null == value) {
            cell.setCellValue((String) null);
        } else if (value instanceof Boolean) {
            cell.setCellValue((Boolean) value);
        } else if (value instanceof Date) {
            cell.setCellValue(FORMAT.format((Date) value));
        } else if (value instanceof Double) {
            cell.setCellValue((Double) value);
        } else {
            cell.setCellValue(value.toString());
        }

    }

    //**************************************************************************

    /**
     * 读取单元格值
     *
     * @param row
     * @param col
     * @return
     * @throws IOException
     */
    public String getRowCol(int row, int col) throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);

        return l.get(row).get(col).toString();
    }

    /**
     * 读取行列，单元格值
     *
     * @param row
     * @return
     * @throws IOException
     */
    public List<Object> getRow(int row) throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);

        return l.get(row);
    }

    /**
     * 获取行数
     *
     * @return
     * @throws IOException
     */
    public Integer getRowNum() throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);

        return l.size();
    }

    /**
     * 修改单元格数据
     *
     * @param row
     * @param col
     * @param data
     */
    public void setRowCol(int row, int col, String data) throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);
        l.get(row).set(col, data);
        File file = new File(excelPath);

        writeDataToTemplateOutputStream(file, l);

    }

    /**
     * 修改单元格数据
     *
     * @param row
     * @param col
     * @param data
     */
    public void setRowCol1(int row, int col, String data) throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);
        l.get(row).add(col, data);
        File file = new File(excelPath);

        writeDataToTemplateOutputStream(file, l);

    }

    /**
     * 插入行
     *
     * @param row
     * @param data
     */
    public void insertRow(int row, List<Object> data) throws IOException {
        List<List<Object>> l = readExcelFirstSheet(excelPath);
        l.add(row, data);
        File file = new File(excelPath);
        writeDataToTemplateOutputStream(file, l);

    }

    /**
     * 插入行
     *
     * @param row
     * @param data
     */
    public void setRow(int row, List<Object> data) throws IOException {

        List<List<Object>> l = readExcelFirstSheet(excelPath);
        if (l.size() == row) {
            l.add(row, data);
        } else if (l.size() > row) {
            l.set(row, data);
        }
        File file = new File(excelPath);
        writeDataToTemplateOutputStream(file, l);

    }

    /**
     * 设置默认结算模版数据
     *
     */
    public void setData() throws IOException {

        int num = getRowNum();
        for(int i =1;i<num;i++) {
            setRowCol1(i,7,"1000");
            setRowCol1(i,8,"9000");
            setRowCol1(i,9,"10000");
            setRowCol1(i,10,"9000");
            setRowCol1(i,11,"9000");
            setRowCol1(i,12,"100");
            setRowCol1(i,13,"100");
            setRowCol1(i,14,"100");
            setRowCol1(i,15,"30000");
        }
    }

    public void setData1() throws IOException {

        int num = getRowNum();
        System.out.println(num);
        for(int i =1;i<num;i++) {
            setRowCol1(i,7,"1000");
            setRowCol1(i,8,"9000");
            setRowCol1(i,9,"10000");
            setRowCol1(i,10,"9000");
            setRowCol1(i,11,"9000");
            setRowCol1(i,12,"100");
            setRowCol1(i,13,"100");
            setRowCol1(i,14,"100");
            setRowCol1(i,15,"30000");
        }
    }

    /**
     * 设置分包结算模版数据
     *
     */
    public void setSubcontractData() throws IOException {

        int num = getRowNum();
        for(int i =1;i<num;i++) {
            setRowCol1(i,7,"1000");
            setRowCol1(i,8,"9000");
            setRowCol1(i,9,"10000");
            setRowCol1(i,10,"9000");
            setRowCol1(i,11,"200");
            setRowCol1(i,12,"9000");
            setRowCol1(i,13,"100");
            setRowCol1(i,14,"100");
            setRowCol1(i,15,"100");
            setRowCol1(i,16,"30000");
            setRowCol1(i,17,"1000");
        }
    }

    /**
     * 设置赔偿金结算模版数据
     *
     */
    public void setCompensationData() throws IOException {

        int num = getRowNum();
        for(int i =1;i<num;i++) {
            setRowCol1(i,7,"1000");
            setRowCol1(i,8,"9000");
            setRowCol1(i,9,"10000");
            setRowCol1(i,10,"9000");
            setRowCol1(i,11,"200");
            setRowCol1(i,12,"9000");
            setRowCol1(i,13,"100");
            setRowCol1(i,14,"100");
            setRowCol1(i,15,"100");
            setRowCol1(i,16,"30000");
        }
    }
`

Metersphere前置脚本
`import ExcelUtils;

ExcelUtils eu = new ExcelUtils("/opt/metersphere/data/body/fef4823d-df0e-4ad8-8976-66d96594b8f9/结算模板 (17).xlsx");
eu.setSubcontractData();`

### 期待的正确结果

执行

**Comment by fit2-zhao** [comment]
请在文件管理中自行引入poi 相关jar包就行，api 服务目前不使用poi 相关功能，所以内置包已经去除。
