### ISSUE TITLE
[BUG]【UI测试】输入两个变量，运行后发现只有一个变量生效，另外一个变量暂未生效。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23940]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【UI测试】输入两个变量，运行后发现只有一个变量生效，另外一个变量暂未生效。

### 重现步骤

1. 【UI测试】环境变量设置url，以及mock设置变量，将这两个变量拼接成一个数据，运行后发现只会有一个变量生效
![image](https://user-images.githubusercontent.com/104960608/233884861-a4272631-d752-41d6-ae35-256ac282b4cf.png)
![image](https://user-images.githubusercontent.com/104960608/233884955-92345748-44cc-4b73-9fe0-d5c1f766ab7f.png)
![image](https://user-images.githubusercontent.com/104960608/233884991-344eb164-8af2-42bf-af56-51cbca7a7279.png)
![image](https://user-images.githubusercontent.com/104960608/233884798-3775c321-ca3a-4696-814c-d382ceb19b96.png)
2. 【UI测试】mock设置两个变量，将这两个变量拼接成一个数据，运行后还是发现只会有一个变量生效
![image](https://user-images.githubusercontent.com/104960608/233885406-ff8351e4-f7c3-476e-9b23-27729a35e566.png)
![image](https://user-images.githubusercontent.com/104960608/233885481-e4a8878b-b62a-41b8-8c67-26d5f71340bb.png)
![image](https://user-images.githubusercontent.com/104960608/233885373-06784fb3-35ef-40bb-baab-87fdad343729.png)
![image](https://user-images.githubusercontent.com/104960608/233885334-6a3e0511-2d9b-4fff-b96d-52d5b2a84357.png)

**Comment by xiaomeinvG** [comment]
感谢您的反馈，如果从执行结果来看这不是一个bug，如果您的两个变量之间不存在其他文本，我们是可以解析正确的，如果两个变量间存在其他字符串我们只能解析第一个变量
