### ISSUE TITLE
[BUG]【UI测试】环境变量里设置mock函数，在场景里两次使用这个环境变量，得到的结果不一样

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23957]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【UI测试】环境变量里设置mock函数，在场景里两次使用这个环境变量，得到的结果不是一样的。正常来说，环境变量是预加载，在运行场景前就加载进去了，那这两个变量值是不是应该一样的呢

### 重现步骤

1.【UI测试】环境变量里设置mock函数，在场景里两次使用这个环境变量，得到的结果不是一样的。正常来说，环境变量是预加载，在运行场景前就加载进去了，那这两个变量值是不是应该一样的呢
![image](https://user-images.githubusercontent.com/104960608/233927072-7c272a54-577e-4b64-8420-3dfe1ca65239.png)
![31f77fcdfad0c5ac9c0c6f250160374](https://user-images.githubusercontent.com/104960608/233927239-327b80db-c9c4-46ca-acc0-80583e4bfbf8.png)
![c7de346805273144c878278814b0f0c](https://user-images.githubusercontent.com/104960608/233927307-3c045023-6561-47f3-90c6-bf6e41ddf739.png)
![4c84891f73d4997b8afeaf0d3cfb9b6](https://user-images.githubusercontent.com/104960608/233927341-88475229-9986-4705-aae7-22fba935e79b.png)
![8fdeb054841da6f59fb2a361c821017](https://user-images.githubusercontent.com/104960608/233927357-a5f38c10-647f-4790-9209-8abac3bf1f75.png)
2. 在接口测试环境变量里也同步设置了这个mock函数，也是在场景里两次使用这个环境变量，得到的结果是一样的
![image](https://user-images.githubusercontent.com/104960608/233930323-4e0731a9-4cfc-4ded-b35b-949521e2df78.png)
![image](https://user-images.githubusercontent.com/104960608/233930243-47a2cbf0-f407-41ce-886c-06ee7f9d4924.png)
![image](https://user-images.githubusercontent.com/104960608/233930430-a0b7460d-121b-4157-92da-4e20a949f15f.png)
![image](https://user-images.githubusercontent.com/104960608/233930550-0fa4e1d3-9ed0-4767-89a7-fbe36680ec33.png)

**Comment by xiaomeinvG** [comment]
感谢您的反馈，接口和UI的执行机制是不同的，对于ui而言,Mock.mock() 被调用两次，每次都会重新生成一组随机数据，因此返回值可能会不同
