### ISSUE TITLE
[BUG]【UI测试】场景变量设置为mock函数@ip，引用后在运行时，产生的ip数据后面多了个空格

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23959]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【UI测试】场景变量设置为mock函数@ip，引用后在运行时，产生的ip数据后面多了个空格

### 重现步骤

【UI测试】场景变量设置为mock函数@ip，引用后在运行时，产生的ip数据后面多了个空格
![image](https://user-images.githubusercontent.com/104960608/233942167-d99fe00b-d40b-4185-913a-0fcd09fdfd36.png)
![image](https://user-images.githubusercontent.com/104960608/233942105-1b1d24a1-be42-4141-920e-db9262effa40.png)
![image](https://user-images.githubusercontent.com/104960608/233942042-aa8c4a2d-f419-4c93-a730-d6576f6c4cf2.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9.1修复。
