### ISSUE TITLE
[FEATURE]建议设置定时任务时，可以给其他组织下的账号或者没有MS账号的邮箱账号发送邮件， 目前仅支持给当前组织下的账号对应的邮件账号发送邮件

### ISSUE THREAD

**Issue by HLX99** [metersphere/metersphere#2396]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
建议设置定时任务时，可以给其他组织下的账号或者没有MS账号的邮箱账号发送邮件，
目前仅支持给当前组织下的账号对应的邮件账号发送邮件

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
