### ISSUE TITLE
[BUG] 脑图删除模块节点没有二次确认功能，表单模式下是有二次确认的。目前在脑图模式下，点击delete建，整个模块节点下的所有信息都直接删除了

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#23973]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

[BUG] 脑图删除模块节点没有二次确认功能，表单模式下是有二次确认的。目前在脑图模式下，点击delete建，整个模块节点下的所有信息都直接删除了。希望这里提供和表单模式下的删除，有二次确认的

### 重现步骤

[BUG] 脑图删除模块节点没有二次确认功能，表单模式下是有二次确认的。目前在脑图模式下，点击delete建，整个模块节点下的所有信息都直接删除了。希望这里提供和表单模式下的删除，有二次确认的

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/234006709-1472abb3-f57f-4b54-bf44-858fe9bb0ec3.png)

**Comment by huangxine** [comment]
![image](https://user-images.githubusercontent.com/78218624/234007585-6d3c6a4c-068c-41d5-839c-9d63be5a040f.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.0修复

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
