### ISSUE TITLE
[BUG]接口传参json格式，打开json-schema，模版中，将值删除，预览模式值依然为0，发送请求，传参值也为0（数据类型为integer）

### ISSUE THREAD

**Issue by WOWOXX** [metersphere/metersphere#23976]
### 联系方式

微信 Metersphere交流群60-蛙仔

### MeterSphere 版本

v2.8.1-da9fa08c

### 使用外置数据库

否

### 问题描述

接口传参json格式，打开json-schema，模版中，将值删除，预览模式值依然为0，发送请求，传参值也为0（数据类型为integer）

### 重现步骤

1.接口打开json-schema
2.模版中，将值删除（数据类型为integer）
3.点击预览模式，值依然为0
4.发送请求，传参值也为0

### 期待的正确结果

模版中，值删除后，预览模式值应为0，发送请求报错提示
message": "JSON parse error: parseDecimal error, field : costScore; nested exception is com.alibaba.fastjson.JSONException: parseDecimal error, field :键名

### 附加信息

<img width="652" alt="0e6084b53599b9ab0da718be6cc0ef9" src="https://user-images.githubusercontent.com/131730827/234158198-ba477591-7ada-4288-95b1-1418accb7d18.png">

**Comment by 13290445582** [comment]
感谢反馈，int类型值为空的话，默认值为0。

**Comment by WOWOXX** [comment]
int和integer是同一数据类型？

**Comment by 13290445582** [comment]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/128017892/234447061-bd31f17e-0cb1-45e2-9808-e1f659bf2259.png">
metersphere里int与integer为同一类型，默认值都是0

**Comment by WOWOXX** [comment]
那我觉得模版中没有值，应该显示0，现在是不显示

**Comment by 13290445582** [comment]
值为空，int类型默认的传参值为0，如果模版这里显示为0的话，相当于这个值不为空，相当于填写的值为0，所以为不显示。
