### ISSUE TITLE
[BUG] 【接口测试】 接口自动化-编写场景用例-偶尔会碰到点保存无反应，场景无法保存不了，导致用例丢失

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#23985]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.21

### 使用外置数据库

否

### 问题描述

编写自动化场景用例时，偶尔会碰到点保存无反应，场景保存不了，导致用例丢失，服务器日志不报错信息，F12抓包无接口调用信息

### 重现步骤

1.进入接口自动化模块
2.编写自动化场景用例
3.在页面停留时间超过1小时
4.点保存

### 期待的正确结果

点保存能正常保存

### 附加信息

F12 日志
![image](https://user-images.githubusercontent.com/45531073/234165819-3aea3214-d841-401c-bc89-ac8bacb2b7c8.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！尝试多次，未复现该问题。
