### ISSUE TITLE
[BUG]  接口测试报告，查看用例，加载很慢 ，需要优化sql查询

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#23993]
### 联系方式

leibo.zhao@fit2cloud.com

### MeterSphere 版本

V2.6.2

### 使用外置数据库

否

### 问题描述

数据量大概1000多条，加载报告列表很慢。  

接口测试->测试报告->场景/用例

https://user-images.githubusercontent.com/33945037/234183108-4f5d70c2-587b-4a4c-8ff9-580c71a1aa6a.mp4

### 重现步骤

同上

**Comment by hao65103940** [comment]
V2.8.1 也有问题

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，经沟通，用户环境mysql剩余资源较少，建议调整后再尝试。
