### ISSUE TITLE
[BUG] 【测试跟踪-测试用例】使用思维导图编写测试用例，新建模块后，保存，提示成功，实际未成功（这样在新模块写了用例后，会丢失数据，建议增加错误提示）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2399]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2

**Bug 描述**
简要描述您碰到的问题
使用思维导图编写测试用例，新建模块后，保存，提示成功，实际未成功

**Bug 重现步骤**
1.  使用思维导图编写测试用例
2. 新建模块后，保存
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
给出相应提示

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/116377100-6ecaed00-a843-11eb-89da-47a08f1f842a.png)

**Comment by zyyfit** [comment]
您好，思维导图里是不支持新建模块的，后续会考虑优化一下这里
