### ISSUE TITLE
[BUG]【UI测试】运行场景时，得到的值并不是在场景变量里设置的值

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#23996]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【UI测试】运行场景时，得到的值并不是在场景变量里设置的值

### 重现步骤

1. 【UI测试】在场景变量里设置字符串的值为 211201197406112563
![image](https://user-images.githubusercontent.com/104960608/234206207-2700fde6-582f-44c3-ab29-beefc9c6d1f0.png)
2.在场景里引用这个变量名
![image](https://user-images.githubusercontent.com/104960608/234206400-fa8129a3-38ac-4c28-bd42-98fee4762796.png)
3. 最终运行结果通过截图可看到，并不是我在场景里设置的值
![image](https://user-images.githubusercontent.com/104960608/234206576-065963c6-1cfa-48c7-afe7-e2db5794f00c.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9.1修复。
