### ISSUE TITLE
[QUESTION]部署代码后，执行接口测试提示“Could not read JMeter properties file:/opt/jmeter/bin/jmeter.properties”

### ISSUE THREAD

**Issue by songoex** [metersphere/metersphere#240]
**请描述您的问题.**
如题，请问是我 jmeter 配置文件放的路径不对吗？
![image](https://user-images.githubusercontent.com/17444283/90237389-c90f5380-de56-11ea-9ae8-d68dcdc9d67c.png)

**Comment by wangzhen-fit2cloud** [comment]
https://metersphere.io/docs/dev_manual/#jmeter
