### ISSUE TITLE
[BUG] 测试用例添加缺陷时，分辨率低的电脑模版样式发生了变化

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24003]
### 联系方式

jianqiang.liu@fit2cloud.com

### MeterSphere 版本

v2.8.X

### 使用外置数据库

否

### 问题描述

测试用例添加缺陷时，缩小浏览器 模版样式问题
<img width="663" alt="image" src="https://user-images.githubusercontent.com/40912189/234245164-f36af8a1-c8e1-4751-a50d-5368bd3e4463.png">

### 重现步骤

1、测试用例添加缺陷
2、缺陷的模版包含概述如上图
3、客户版本为2.8.1 

### 期待的正确结果

测试用例添加缺陷时，低分辨率的电脑 模版样式保持一个正常的样子

**Comment by 13290445582** [comment]
你好，请提供下帮助复现的相关信息，服务集成平台以及分辨率大小

**Comment by sss903065212** [comment]
1、jira 8.20.3版本
2、只要缩小浏览器窗口就能复现

**Comment by youliyuan-fit2cloud** [comment]
你好，如果页面内容很多，我们不建议分辨率低于这个1366*768使用。请确认下分辨率是否太低了。

**Comment by sss903065212** [comment]
分辨率确实低于这个1366*768

**Comment by youliyuan-fit2cloud** [comment]
那确实太低了。目前不会处理。
