### ISSUE TITLE
[FEATURE]希望能够解决压测调用场景脚本中不同逻辑有不同线程数的问题，初始化和断言

### ISSUE THREAD

**Issue by moteng** [metersphere/metersphere#24000]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

[FEATURE]希望能够解决压测调用场景脚本中不同逻辑有不同线程数的问题，初始化和断言

**Comment by luty2018** [comment]
v3.0 讨论规划
