### ISSUE TITLE
[FEATURE]  用户授权项目希望可以添加全选选项，如果有很多项目，一个一个点太麻烦了

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#24019]
### MeterSphere 版本

所有版本

### 联系方式

leibo.zhao@fit2cloud.com

### 请描述您的需求或者改进建议

<img width="512" alt="image" src="https://user-images.githubusercontent.com/33945037/234453914-0860dea9-01dc-4b5c-a133-c7585d23baa2.png">

### 请描述你建议的实现方案

希望可以添加全选选项，避免一个一个勾选

**Comment by luty2018** [comment]
感谢建议，这个可以支持

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！内部环境已可以体验。
