### ISSUE TITLE
[BUG]lts 版本 data-streaming 启动时没有初始化 hikari 连接池

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#24020]
### 联系方式

shenkaibo

### MeterSphere 版本

1.20.21-lts

### 使用外置数据库

否

### 问题描述

lts 版本 data-streaming 启动时没有初始化 hikari 连接池

### 重现步骤

1.进入 lts data-streaming 容器，拿到容器ip ，去数据库里查询 连接数为0
![image](https://user-images.githubusercontent.com/30038088/234455151-1b8b5cc9-266c-4d33-8379-5fb4f2218c01.png)
![image](https://user-images.githubusercontent.com/30038088/234455274-3fc88068-1502-467c-a4ec-33fddeaa8738.png)
日志中也不打印 创建 hikari 连接池的日志

### 期待的正确结果

v2.x 的 datastreaming 启动后会创建 hikari 连接池，进入 data-streaming 容器，拿到容器ip 能在 mysql 中能查到 相应的连接数
![image](https://user-images.githubusercontent.com/30038088/234456075-06f042fa-59d0-42c9-b694-5cbce3229df2.png)
![image](https://user-images.githubusercontent.com/30038088/234456186-a5c8dc89-aa2e-4943-b3b4-1e3f5a5b6e9d.png)

日志里会打印 创建 hikari 连接池的日志
![image](https://user-images.githubusercontent.com/30038088/234457843-9fdec4ce-6edf-4952-9680-3e2160ecc239.png)

**Comment by liuruibin** [comment]
性能测试不能执行了吗？如果不行请上传报错日志
