### ISSUE TITLE
[BUG]【测试跟踪】搜索框里搜索内容后，列表中显示出搜索内容，但是切换到xmind脑图里，还是显示出所有的内容

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24025]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

搜索框里搜索内容后，列表中显示出搜索内容，但是切换到xmind脑图里，还是显示出所有的内容，并没有按照搜索的展示内容

### 重现步骤

搜索框里搜索内容后，列表中显示出搜索内容，但是切换到xmind脑图里，还是显示出所有的内容，并没有按照搜索的展示内容
<img width="800" alt="b1c74608cd9def3b962bd03ff3cf5c3" src="https://user-images.githubusercontent.com/104960608/234462585-a9270717-1a25-4cf1-8de5-0fb1df3e2a1c.png">

**Comment by 13290445582** [comment]
感谢反馈，脑图和列表的查询条件并不是公共的，所以列表/脑图切换时会刷新。
