### ISSUE TITLE
[BUG]【UI测试】场景变量-变量类型为数组，数据为数组嵌套数组，通过下标获取不到数组里的元素

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24030]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【UI测试】场景变量-变量类型为数组，数据为数组嵌套数组，foreach循环变量数组里的每个元素，获取的元素也是个数组，在前置脚本中使用数组下标获取里面的每个元素并进行返回，根据运行截图可看到最终没获取到

### 重现步骤

1.【UI测试】场景变量-变量类型为数组，数据为数组嵌套数组
![image](https://user-images.githubusercontent.com/104960608/234496808-f874ff66-1502-4f3c-9ee0-f7edcaf85c75.png)
2.foreach循环变量数组里的每个元素
![image](https://user-images.githubusercontent.com/104960608/234496962-559281a9-2bd5-49d2-9edd-9343c106d120.png)
3.获取的元素也是个数组，在前置脚本中使用数组下标获取里面的每个元素并进行返回，根据运行截图可看到最终没获取到
![image](https://user-images.githubusercontent.com/104960608/234497171-1fca885b-583b-43a6-ae85-35968a8e8ace.png)
![image](https://user-images.githubusercontent.com/104960608/234496547-b7f2acf6-3c08-4815-a2f2-69536b97c856.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.9不存在该问题，待发布后可升级。
