### ISSUE TITLE
不同环境需要不同的文件上传，有没有简易方式实现类似变量上传

### ISSUE THREAD

**Issue by chenzijiechenzijie** [metersphere/metersphere#24031]
### MeterSphere 版本

 v2.7.0-34d44a5e

### 联系方式

chenzijie@sinohealth.com

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/116268247/234510549-608d1d84-da4d-4f40-b1a9-22bd17068226.png)

因环境不一样，所以需要的文件内容也不一致。 目前只能通过创建两条不同的case，存储两份不一样的文件实现。
想知道有没有能通过变量根据项目/标签等某些字段判断应该取哪个文件的实现方式呢？

**Comment by zhangzhaox** [comment]
待上传的文明名称 用环境变量去配置切换 上传不同的文件 不可以？
