### ISSUE TITLE
[BUG]【模板设置】模板设置处设置时间选择器的字段，在缺陷管理页面，点击该字段进行排序，排序后的结果还是乱的

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24032]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

【模板设置】模板设置处设置时间选择器的字段，在缺陷管理页面，点击该字段进行排序，排序后的结果还是乱的

### 重现步骤

1.【模板设置】模板设置处设置一个缺陷模板字段如下
![image](https://user-images.githubusercontent.com/104960608/234521473-7c9194f8-8832-4e71-b688-0cbff9845283.png)
![image](https://user-images.githubusercontent.com/104960608/234521598-369f2e39-015b-4ed3-9869-237542e7f143.png)
2.将其绑定到当前项目下
![image](https://user-images.githubusercontent.com/104960608/234521907-30897a82-f201-43b4-b415-df07ae090469.png)
3.在【缺陷管理】页面新建几个用例选择不同的发现时间，然后点击发现时间表头的排序，发现排序还是乱的
![image](https://user-images.githubusercontent.com/104960608/234522370-036768c3-45fc-402e-891d-a3cb82adbb32.png)
![image](https://user-images.githubusercontent.com/104960608/234522545-a69e67df-9590-42f4-a33d-ae998f6b464a.png)
![image](https://user-images.githubusercontent.com/104960608/234522643-739de5d6-c6f4-4eb8-a18f-41b1343cb7d2.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.1修复
