### ISSUE TITLE
[BUG]实际循环次数比次数循环设置的次数还要多

### ISSUE THREAD

**Issue by 844177611** [metersphere/metersphere#24047]
### 联系方式

844177611@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

实际循环次数比次数循环设置的次数还要多

### 重现步骤

1. 添加事务控制器（以下操作都在这个控制器中）
2. 接口列表导入：普通API或者Case
3. 添加循环控制器，设置次数循环：5次，成果后继续循环Off
4. 在次数循环控制器中添加一个普通API或者case

### 期待的正确结果

次数循环应该根据实际情况进行循环，且循环次数不应该超过设置的次数

### 附加信息

![image](https://user-images.githubusercontent.com/129732806/234550691-82a31fdb-538d-4054-a5c7-0d923bcaeb9f.png)

**Comment by 13290445582** [comment]
感谢反馈，该问题在最新环境未复现，建议升级至最新环境～

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
