### ISSUE TITLE
[BUG]测试跟踪>>功能测试用例>>版本对比：一个用例的两个版本，并且不同版本的操作步骤有差异，但是在对比中，看不到这块的差异

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24059]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>功能测试用例>>版本对比：一个用例的两个版本，并且不同版本的操作步骤有差异，但是在对比中，看不到这块的差异

### 重现步骤

[BUG]测试跟踪>>功能测试用例>>版本对比：一个用例的两个版本，并且不同版本的操作步骤有差异，但是在对比中，看不到这块的差异

### 期待的正确结果

[BUG]测试跟踪>>功能测试用例>>版本对比：一个用例的两个版本他们的操作步骤有差异，但是在对比中，看不到这块的差异

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/234592275-8c66d1b6-e242-42a9-819f-f56be6233204.png)
![image](https://user-images.githubusercontent.com/78218624/234592533-b44296a0-4019-4dea-9805-947f96d4cd0e.png)
![image](https://user-images.githubusercontent.com/78218624/234592668-0ebf956d-8fbf-45a9-804b-04b8510aff69.png)

**Comment by 13290445582** [comment]
感谢反馈，计划于3.0优化该问题

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
