### ISSUE TITLE
[BUG]不在任何循环控制器中的请求执行后响应结果显示有循环

### ISSUE THREAD

**Issue by 844177611** [metersphere/metersphere#24050]
### 联系方式

844177611@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

不在任何循环控制器中的请求执行后响应结果显示有循环

### 重现步骤

1. 添加事务控制器
2. 从接口列表导入：API或者Case
3. 添加循环控制器：次数控制器，设置5次，成功后继续Off
4. 循环控制器，添加一个API或者Case

### 期待的正确结果

不在循环控制器内的请求不应该显示有循环的响应结果

### 附加信息

![20230426-184127](https://user-images.githubusercontent.com/129732806/234552215-7fcf5173-b564-4841-b987-936d6995f69c.gif)

**Comment by 13290445582** [comment]
感谢反馈，该问题在最新环境未复现，建议升级至最新环境～

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
