### ISSUE TITLE
[BUG]UI测试，对换行的文本设置断言失败

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#24060]
### 联系方式

张树彬

### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

UI测试添加断言时，当文本中有换行时，无法断言成功

### 重现步骤

1. 设置UI自动断言，选择“断言值-元素文本等于期望 或者 元素文本包含期望 ”
2. 在文本框中输入带有换行的文本
3. 调试场景后显示断言失败

### 期待的正确结果

兼容带换行的文本格式

### 附加信息

![8385327893fc16194d9efe464e2a216](https://user-images.githubusercontent.com/77324661/234603921-cf315f93-31c2-4e25-9889-d816bb12a728.jpg)
![5d777c7107277a3556407f9ce1fcd2f](https://user-images.githubusercontent.com/77324661/234604020-d367ea10-5335-4324-8b65-d2d3f9a0e6ec.jpg)
![47b0dc1d7d70e132605babc751be1aa](https://user-images.githubusercontent.com/77324661/234604100-168f016b-3f78-4514-9fa4-cbd683d3c6b9.jpg)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9.1修复。

**Comment by zrfit** [comment]
经沟通和调研，断言换行加\n即可断言成功，请尝试下是否可以。
