### ISSUE TITLE
[BUG]操作日志加载太慢

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#24067]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

版本:   v1.20.21-lts-6359b12e

### 使用外置数据库

是

### 问题描述

查询操作加载太慢，operating_log  操作日志表中有26万的数据量
![image](https://user-images.githubusercontent.com/39703025/234746108-0d1fdbb9-ec1b-4338-8b17-28fa0b26f589.png)
导致在查询操作日志需要等很久如图
![image](https://user-images.githubusercontent.com/39703025/234746575-26f4de0e-7d9e-4bc1-95bb-415d2997a271.png)

### 重现步骤

进入系统日志-系统-操作日志需等待

### 期待的正确结果

期待响应在10秒之内显示操作日志

### 相关日志输出

```shell
无
```

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v1.20.22修复。

**Comment by fit2-zhao** [comment]
您好，感谢反馈，您的问题原因是分页加 order by time desc 导致，可以调整文件 “ /opt/metersphere/conf/my.cnf ” 中的 参数 
 “innodb_buffer_pool_size” ，在mysql文档中建议调整mysql所占内存的 80% ，您可以根据自己的部署现状调整，目前默认比较小。
