### ISSUE TITLE
[BUG]场景中csv 读取，分隔符为两个%%号时，取不到变量

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24072]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

场景中csv 读取，分隔符为两个%%号时，取不到变量

### 重现步骤

1.场景引用csv中变量，csv 分割为%%
![image](https://user-images.githubusercontent.com/103627487/234754691-e1850dd6-ee1d-4111-8dc3-fab4c051f4da.png)
![image](https://user-images.githubusercontent.com/103627487/234754761-0b515322-e388-4eba-ba91-2b43ff09cecd.png)
csv文件可参考
[按选中检录数据 - 副本.csv](https://github.com/metersphere/metersphere/files/11339389/-.csv)
2.调试场景，查看变量引用
![image](https://user-images.githubusercontent.com/103627487/234754957-ed25aa1a-7b6c-4b59-8152-6b68cc2b455e.png)
![image](https://user-images.githubusercontent.com/103627487/234754994-fd1c326a-16f4-4c5d-94fa-5d22e10a8097.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！metersphere接口执行后端调用jmeter，用jmeter试了下也存在该问题，换成单个分隔符“%”就可以了。

**Comment by zhangzhaox** [comment]
特殊字符 需要转义  \%\% 可以试一下，更跟分隔符是良策
