### ISSUE TITLE
[BUG]项目环境-通用设置里面的环境变量多时，在场景里选择设置场景环境点开的时候需要转好久然后才显示环境

### ISSUE THREAD

**Issue by mayuan28** [metersphere/metersphere#24071]
### 联系方式

18515284298

### MeterSphere 版本

1.20.18

### 使用外置数据库

是

### 问题描述

项目环境-通用设置里面的环境变量多时，在场景里选择设置场景环境点开的时候需要转好久然后才显示环境

### 重现步骤

项目环境-通用设置里面的环境变量多时，在场景里选择设置场景环境点开的时候需要转好久然后才显示环

### 期待的正确结果

当配置环境里的通用配置里的变量多的情况下，在场景里选择环境时不要转

**Comment by zrfit** [comment]
您好,感谢您的反馈！最新版本v1.20.21未复现该问题，建议升级尝试。

**Comment by 13290445582** [comment]
建议升级到最新版本，如果再次出现请重新提issue，感谢理解和支持～
