### ISSUE TITLE
[FEATURE]希望能把Jmeter插件中的常用函数加入到 Jmeter镜像中 如jmeter-plugins-functions-2.1.jar

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#2408]
**请描述您的需求或者改进建议.**

这个jar包中的常用的 MD5、URLDecode等方法是常用函数

**请描述你建议的实现方案**
或希望指导下如何使用基于metersphere提供的基线镜像 自定义生成的Jmeter镜像
感谢

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
