### ISSUE TITLE
[BUG]相同的前后置脚本调用http能成功，但调用https不成功

### ISSUE THREAD

**Issue by leonfunsfy** [metersphere/metersphere#24085]
### 联系方式

MeterSphere 202209期学习班      昵称：Leon,邮箱:funsfy@126.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

否

### 问题描述

问题：相同的前后置脚本调用http能成功，但调用https不成功

### 重现步骤

前提：在2.8.0微服务部署的平台中，接口A的一个casesB能执行通过
步骤：1.建立casesX，casesX中有一个前置脚本，脚本是casesB的内容
2.建立一个http请求的环境配置；建立一个https请求的环境配置（系统功能是一样的）
3.在http请求的环境配置下，执行casesX，能通过
4.在https请求的环境配置下，执行casesX，不能通过，有报错
一、具体前置脚本如下：
import urllib2
import urllib
import json
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import random
n1=random.randint(10000,99999)
n1=str(n1)
headers = {'Content-Type':'application/json','Cookie':'${cookie}','X-Auth0-Token':'${X-Auth0-Token}'}
log.info(str(headers))
url = '${yuming}/${servenameyh}/tag/addTag'
#url += '?wbId=${id}&groupId=${groupid}'

data ={
    "tagName": "自动化标签"+n1,
    "editPower": 1,
    "usePower": 1,
    "syncWx": 0
}
data = json.dumps(data)
log.info(url)
log.info(str(headers))
log.info(data)
req = urllib2.Request(url,headers=headers,data=data)
req.get_method = lambda: 'POST'
rp = urllib2.urlopen(req)
log.info(str(rp))
page = rp.read().decode("utf-8")
log.info(page)
data_obj = json.loads(page)
id= data_obj["data"]
log.info("id:"+id)
# 传递变量
vars.put("id",id)
#vars.put("groupid",groudid)

**Comment by youliyuan-fit2cloud** [comment]
你好，请问报错信息是什么？场景文件方便发我们看看吗？

**Comment by leonfunsfy** [comment]
在 2023-04-28 14:12:13，"MatataYou" ***@***.***> 写道：

你好，请问报错信息是什么？场景文件方便发我们看看吗？

**Comment by leonfunsfy** [comment]
2023-05-06 14:19:44 ERROR cffb2dde 1-1 Problem in JSR223 script, 获取上级部门idpython
urllib2.URLError: <urlopen error [Errno 1] Tag mismatch! (javax.crypto.AEADBadTagException: Tag mismatch!)> in <script> at line number 16
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)

**Comment by youliyuan-fit2cloud** [comment]
你好，根据这个错误日志和脚本信息，看着是https的有安全要求，请检查是否需要证书，是否需要加解密过程？

**Comment by youliyuan-fit2cloud** [comment]
介于未复现且长时间未回复，故关闭该问题。
