### ISSUE TITLE
[BUG]断言JSONPath匹配报错

### ISSUE THREAD

**Issue by lishiyi11** [metersphere/metersphere#2409]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.8.2-d59d4b5f

**Bug 描述**
简要描述您碰到的问题
断言JSONPath匹配报错，json的具体的内容是
\{"componentSn":false,"stolen":false,"wepFlag":false,"matchExchangeRule":false,"matchRefurbishRule":false,"needHideActivationDate":false\}

截图为响应正常，断言失败的图片

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
 
 
![响应正常](https://user-images.githubusercontent.com/83342919/116386735-a5593580-a84c-11eb-8d9c-4087217ede7f.png)

![image](https://user-images.githubusercontent.com/83342919/116386675-97a3b000-a84c-11eb-8b1e-57086d85d741.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by wch352136** [comment]
> 感谢反馈，将在后续版本修复这个问题

类似的问题，如下图，上面是我的断言，下面是断言结果
![image](https://user-images.githubusercontent.com/17609338/116664388-fabb5100-a9ca-11eb-9df8-bd052cafcc7f.png)

**Comment by zyyfit** [comment]
您好，目前暂时不支持对大段json数据进行断言，您可以具体到某个字段进行断言，后续版本可能会考虑优化这种问题
另外，预期不为空的断言问题这边没有复现，您可以升级版本后试一下
