### ISSUE TITLE
[BUG]项目场景多，场景里的步骤多 引用其他场景多的情况，场景里打开场景环境设置点开的时候一直转，加载不出来，需要转很久才显示环境

### ISSUE THREAD

**Issue by mayuan28** [metersphere/metersphere#24096]
### 联系方式

18515284298

### MeterSphere 版本

v1.20.21-Its

### 使用外置数据库

是

### 问题描述

项目场景多，场景里的步骤多 引用其他场景多的情况，场景里打开场景环境设置点开的时候一直转，加载不出来，需要转很久才显示环境，视频已经发送邮件中 938492421qq.com

### 重现步骤

项目场景多，场景里的步骤多 引用其他场景多的情况，场景里打开场景环境设置点开的时候一直转，加载不出来，需要转很久才显示环境，视频已经发送邮件中 938492421qq.com

### 期待的正确结果

项目场景多，场景里的步骤多 引用其他场景多的情况，场景里打开场景环境设置点开不需要加载很久出现环境，加载不出来，视频已经发送邮件中

### 相关日志输出

```shell
项目场景多，场景里的步骤多 引用其他场景多的情况，场景里打开场景环境设置点开就加载出环境
```

**Comment by youliyuan-fit2cloud** [comment]
你好，“视频已经发送邮件中 938492421qq.com” 这个邮箱地址是从哪个渠道获取的？ 是我们同事吗？我们无法获取到这个视频，建议发到github 上吧。

**Comment by mayuan28** [comment]
这是视频，昨天回复bug邮件be被退回了

Uploading 6cbdb354ebc81ebf73116ce3acffbc2a.mp4…

**Comment by youliyuan-fit2cloud** [comment]
> 这是视频，昨天回复bug邮件be被退回了
> 
> Uploading 6cbdb354ebc81ebf73116ce3acffbc2a.mp4…

你好，看起来视频没上传成功，我们无法下载。

**Comment by mayuan28** [comment]
视频太大了，我照了一下，视频里面加载环境快30秒了，
https://user-images.githubusercontent.com/124749460/235089110-1d9e34fa-fac0-49da-acdb-84ad7715fec6.mp4

**Comment by mayuan28** [comment]
一个场景大概做900个多接口，80个场景 里面有也有beanshell，几乎每个项目如果接口上800多个就出现这问题必现的卡，不管环境哪里卡，接口多的时候在场景里调试打开页面都卡不过比环境设置那里好一些不是半天加载不出来，api_secario这个表查数据慢，这种一个场景800多个接口不是特殊案例是常规的

**Comment by youliyuan-fit2cloud** [comment]
> 

了解了，我们需要研究一下怎么优化。

**Comment by fit2-zhao** [comment]
您好，这个场景太大了，页面渲染不了，建议拆分下吧。

**Comment by youliyuan-fit2cloud** [comment]
单个场景，添加的请求数大于500时，系统会给出提示“单个场景请求数大于500可能导致页面加载异常”，前端渲染问题目前没有解决方案，所以仅提示不做技术处理。感谢理解和支持。
