### ISSUE TITLE
[FEATURE]csv文件每次编辑后都需要自行设置编码格式否则出现乱码

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#24092]
### MeterSphere 版本

v2.8.0-ac76fee1

### 联系方式

2297310871@qq.com

### 请描述您的需求或者改进建议

![图片](https://user-images.githubusercontent.com/23067502/234818469-097320b7-ab55-4eed-ba97-d09536d77c5f.png)
非常感谢MS团队，非常棒的开源系统，祝五一假期快乐！！！

### 请描述你建议的实现方案

希望可以兼容csv文件中文UTF-8编码显示，不用手动设置编码格式。

**Comment by luty2018** [comment]
你好， 可以私信发下你的源文件给我们看看吗？
在交流群添加我的企业微信即可。

**Comment by xiaochongzi-ling** [comment]
麻烦邮件联系2297310871@qq.com

**Comment by luty2018** [comment]
已转邮件联系
