### ISSUE TITLE
[FEATURE]UI测试：能支持用户自定义修改访问打开页面的超时连接时间。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24105]
### MeterSphere 版本

2.8.1

### 使用外置数据库

否

### 问题描述

[BUG]UI测试：能支持用户自定义修改访问打开页面的超时连接时间。
现象：
1、客户的测试环境，访问一个系统页面打开就需要30-40秒，完全加载完成需要1分多钟。
2、UI测试第一个节点（打开页面）都无法执行成功，提示超时或者404等异常，

问题：
1）在UI脚本里，没有办法设置连接超时时间，
2）系统配置文件也这个连接超时参数设置

期望
1）对于这块能开放出来让客户自定义

### 重现步骤

[BUG]UI测试：能支持用户自定义修改访问打开页面的超时连接时间。
现象：
1、客户的测试环境，访问一个系统页面打开就需要30-40秒，完全加载完成需要1分多钟。
2、UI测试第一个节点（打开页面）都无法执行成功，提示超时或者404等异常，

问题：
1）在UI脚本里，没有办法设置连接超时时间，
2）系统配置文件也这个连接超时参数设置

期望
1）对于这块能开放出来让客户自定义

### 期待的正确结果

请求打开系统页面的 连接超时时长允许用户自定义

**Comment by zrfit** [comment]
您好，感谢您的反馈！可以通过设置打开网页步骤的后置操作中的等待时间设置超时。

**Comment by huangxine** [comment]
你说的这个方法试过：在脚本的前后置操作里都添加了超时时间都不可以。

另外：后置操作的意义，应该是访问到这个网页或者完成了当前操作后，再执行添加的这些后置操作吧，目前是当前操作或者动作都没有完成，怎么可能启动用户自定义的后置操作呢？

**Comment by zrfit** [comment]
感谢反馈，计划v3.0优化。
