### ISSUE TITLE
[BUG]API文档访问报错

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#24118]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

![图片](https://user-images.githubusercontent.com/23067502/235064215-bd19d388-8c8b-477f-864a-e4e82a5975dc.png)
![图片](https://user-images.githubusercontent.com/23067502/235064236-7354ff11-45c4-41e8-b912-037d4f608113.png)

### 重现步骤

见描述

**Comment by youliyuan-fit2cloud** [comment]
你好，v2.8.1以上版本已解决该问题，升级一下吧。
