### ISSUE TITLE
[BUG]接口测试，旧版本【转场景测试】功能，原用例前/后置脚本无论使用的是什么语言，转换后都是beanshell

### ISSUE THREAD

**Issue by zengjin55** [metersphere/metersphere#2411]
**MeterSphere 版本**
V1.8.1

**Bug 描述**
旧版本转场景测试功能，自定义脚本、预执行脚本、后执行脚本，为python语言时，转换后为beanshell

**Bug 重现步骤**
1.  接口测试，新建旧版本用例，预执行脚本、后执行脚本、断言自定义脚本均使用python编写
2. 选择旧用例，执行【转场景测试】
3. 切换至新版本-接口自动化，查看转换后的场景用例-前/后置脚本

**期待的正确结果**
旧用例使用python，转换后新用例亦为python语言

**截图**
![Uploading image.png…]()

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by xulinde** [comment]
1.9.2已修复

**Comment by zengjin55** [comment]
升级了v1.9.2，前后置修改了，旧用例中断言使用python语言，转换后语言没有变依然为beanshell
