### ISSUE TITLE
[BUG]接口列表导入swagger的json文件，报：解析数据出错

### ISSUE THREAD

**Issue by try3** [metersphere/metersphere#24117]
### MeterSphere 版本

v2.8

### 使用外置数据库

否

### 问题描述

接口列表导入swagger的json文件，报：解析数据出错

 
[swagger.zip](https://github.com/metersphere/metersphere/files/11350231/swagger.zip)

### 重现步骤

接口测试->接口定义->接口测试导入，选swagger，上传json文件，点保存，报 ：解析数据出错

**Comment by 13290445582** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/128017892/235067447-fed45d47-7c03-4112-9d84-99256f50432b.png">
您好，您提供的swagger.zip在最新版本可以正常导入，建议升级至最新版本～

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
