### ISSUE TITLE
[BUG]功能用例创建子模块不输入名称，点击脑图，该模块会展示其他模块用例

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#24115]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

创建一个空目录，在该目录创建子目录，不输入子目录名称，点击脑图，会错误的展示该目录的用例

### 重现步骤

1、创建目录
2、创建子目录
![image](https://user-images.githubusercontent.com/104493699/235046817-c912cbdb-5d7c-48a9-b2bf-c653b6082217.png)
3、这时点击脑图，以及下面的模块，会展示其他目录的用例
![image](https://user-images.githubusercontent.com/104493699/235047504-944ee00e-9817-4076-8162-beab62b5e191.png)

### 期待的正确结果

应该不展示用例

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.1修复
