### ISSUE TITLE
[FEATURE]希望可以将没有关联自动化测试用例的功能用例一键筛选出来，且对项目的自动化率进行统计

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24133]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

项目要求是写功能测试用例，之后对描述的功能测试用例，编写接口用例和场景用例和UI用例，以达到由手动转到自动化的效果，如果一个项目自动化率是100%，那么表示项目完全可以自动化测试了，目前问题是功能测试用例是否关联自动化测试用例不能直观展示，2是无法简单筛选出没有自动化的测试用例，3是页面上也没有自动化率的统计

**Comment by luty2018** [comment]
现在首页可以获取到1和2的数据， 第3点我们会在v3.0实现

**Comment by YellCatt** [comment]
> 现在首页可以获取到1和2的数据， 第3点我们会在v3.0实现

没有可能更加直观的展示是否关联了自动化测试用例的方法吗？

**Comment by luty2018** [comment]
> > 现在首页可以获取到1和2的数据， 第3点我们会在v3.0实现
> 
> 没有可能更加直观的展示是否关联了自动化测试用例的方法吗？

有已覆盖 和 未覆盖的数据统计了，点击就会跳转到列表，还不够直观吗？

**Comment by luty2018** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/36292514/236594039-0d8b1e11-a165-4aed-8285-e00a9bb6be93.png">

**Comment by YellCatt** [comment]
> Contributor

可以
