### ISSUE TITLE
[FEATURE]希望添加环境组可以对单个测试计划增加分发模式

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24131]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

随着测试用例的增加，优化用例后，如果依旧无法达到12小时的测试时间的自动化测试要求，那么只能配置更多的测试环境。

这个时候测试计划，需要对测试用例进行分发都每个测试环境中。

假设目前的测试用例运行时间是24小时，一个环境。

如果第二天需要交付，那么配置两个环境，一个测试计划，对所有的测试用例进行分发，能达到12小时就能测试完成。

**Comment by luty2018** [comment]
系统有提供环境组功能

**Comment by YellCatt** [comment]
> 系统有提供环境组功能 在工作空间的环境管理里面

目前的环境组功能是将一个测试用例发给两个环境，我的需求是将两个测试用例发给两个环境，达到测试时间减半的效果，这两个不一样

**Comment by luty2018** [comment]
额 ，如果只是想达到测试时间减半的效果， 那现在测试计划里也可以指定不同的环境是不是可以覆盖呢，你可以加我的企业微信聊一下这个。

**Comment by YellCatt** [comment]
> 额 ，如果只是想达到测试时间减半的效果， 那现在测试计划里也可以指定不同的环境是不是可以覆盖呢，你可以加我的企业微信聊一下这个。

怎么加企业微信？是否可以直接加微信，15021342292，你申请好友的时候，备注下MS平台

**Comment by YellCatt** [comment]
> 系统有提供环境组功能 在工作空间的环境管理里面
完全不是一个想法，这个就是希望在时间有限的情况下，尽可能通过叠加测试环境的方式来降低时间成本，测试环境都是相同的，就像一台打印机10张打印纸，多加一台，两台打印机，就各分5张打印纸，速度就可以叠加。

**Comment by YellCatt** [comment]
> 系统有提供环境组功能 在工作空间的环境管理里面
完全不是一个想法，这个就是希望在时间有限的情况下，尽可能通过叠加测试环境的方式来降低时间成本，测试环境都是相同的，就像一台打印机10张打印纸，多加一台，两台打印机，就各分5张打印纸，速度就可以叠加。

**Comment by YellCatt** [comment]
> 系统有提供环境组功能 在工作空间的环境管理里面
完全不是一个想法，这个就是希望在时间有限的情况下，尽可能通过叠加测试环境的方式来降低时间成本，测试环境都是相同的，就像一台打印机10张打印纸，多加一台，两台打印机，就各分5张打印纸，速度就可以叠加。

**Comment by luty2018** [comment]
这个需求不会支持， 用两个测试计划指向不同的环境可以覆盖。
