### ISSUE TITLE
[BUG]UI测试-后置操作脚本返回 json 值，断言错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24130]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

UI测试-后置操作脚本返回 json 值，断言错误

### 重现步骤

1. 打开 ms 网址，例如：http://XX:8081/api/user/ws/current/member/list    这个地址会返回登录错误的 json 
![image](https://user-images.githubusercontent.com/103627487/235129997-fc69c4a9-d58d-4451-a20a-a9b7f78d3e36.png)
2. 在后置操作脚本获取返回
![image](https://user-images.githubusercontent.com/103627487/235130245-3a0465bd-3d42-412a-8186-61aa27d221c9.png)
3. 断言值
![image](https://user-images.githubusercontent.com/103627487/235130389-c107c58d-8486-4662-89d9-32a607432d3d.png)
4.后端调试，步骤结果中报错，其实提取到值了断言错误
![image](https://user-images.githubusercontent.com/103627487/235130659-e212ba16-bb09-42ea-b035-b3ba01f7c510.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、打开网址不对，应该是http://xx:8081/#/api/user/ws/current/member/list
2、断言失败计划v2.9.1修复。
