### ISSUE TITLE
[FEATURE]环境配置中的前后置脚本是否可以区分接口case，场景用例，UI用例，且全局前后置脚本支持多个

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24132]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

我的需求是这样的，我的接口case是要运行多个前置脚本的，1是用来生成测试数据，2是获取token
但是我场景测试是不要跑前置脚本的，这两者就冲突了。
目前的解决方案是配置多个环境，前置脚本部分写在环境配置中，部分写在测试用例中，不方便维护。
环境有多个，不方便测试计划的统一运行

**Comment by luty2018** [comment]
感谢建议， 我们会在v3.0讨论规划

**Comment by YellCatt** [comment]
> 感谢建议， 我们会在v3.0讨论规划

谢谢

**Comment by luty2018** [comment]
v3会设置不同场景的前后置脚本
<img width="670" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/083088ad-5632-4216-bd9d-94a621befb08">
 待发布后看看是否满足需求
