### ISSUE TITLE
设置执行72小时，实际执行不到72小时，而且状态好几天了一直是reporting

### ISSUE THREAD

**Issue by zhpoplar** [metersphere/metersphere#24134]
### 请描述您的问题

状态如下，时长不够，一直reporting
<img width="1136" alt="屏幕截图 2023-05-03 215452" src="https://user-images.githubusercontent.com/26213974/235937435-bfecad38-e6e0-458d-b03f-614e0545c1df.png">

<img width="561" alt="屏幕截图 2023-05-03 215616" src="https://user-images.githubusercontent.com/26213974/235937638-c8274196-895a-4eaa-a75d-b050fbcc1e93.png">

**Comment by zhangzhaox** [comment]
请检查下kafka服务是否还正常，kafka所在的服务器磁盘是否足够

**Comment by zhpoplar** [comment]
> 请检查下kafka服务是否还正常，kafka所在的服务器磁盘是否足够
服务器磁盘充足, kafka服务正常
<img width="563" alt="微信截图_20230504084657" src="https://user-images.githubusercontent.com/26213974/236081656-2819d967-ee81-41d0-8b56-4a3ac20927dc.png">

**Comment by zhpoplar** [comment]
> 请检查下kafka服务是否还正常，kafka所在的服务器磁盘是否足够

刚停掉测试，重新启动，提示kafka不可用，请问如何整改

**Comment by zhangzhaox** [comment]
重启kafka 和datastreaming服务 试试 连接kafka的的host信息 可以调整成实际ip地址  不使用kafka 走的docker内部网络

**Comment by zhpoplar** [comment]
> 重启kafka 和datastreaming服务 试试 连接kafka的的host信息 可以调整成实际ip地址 不使用kafka 走的docker内部网络

改了配置之后，执行了一下msctl reload，炸了
<img width="319" alt="微信截图_20230504105952" src="https://user-images.githubusercontent.com/26213974/236103861-2bdaef6c-be88-4507-8cbc-1b998be1b633.png">

**Comment by zhpoplar** [comment]
> > 重启kafka 和datastreaming服务 试试 连接kafka的的host信息 可以调整成实际ip地址 不使用kafka 走的docker内部网络
> 
> 改了配置之后，执行了一下msctl reload，炸了 <img alt="微信截图_20230504105952" width="319" src="https://user-images.githubusercontent.com/26213974/236103861-2bdaef6c-be88-4507-8cbc-1b998be1b633.png">

重试几次就好了

**Comment by zhpoplar** [comment]
> 重启kafka 和datastreaming服务 试试 连接kafka的的host信息 可以调整成实际ip地址 不使用kafka 走的docker内部网络

您好，目前又出现了这种情况，已重启kafka和datastreaming服务，切修改kafka的配置，请问如何让任务继续执行
- 卡在了54小时
<img width="643" alt="image" src="https://user-images.githubusercontent.com/26213974/236653329-7f55955f-00ea-4d98-a467-fc9fe44fab2f.png">

- 日志停在了6号
<img width="522" alt="image" src="https://user-images.githubusercontent.com/26213974/236653351-34264762-2139-4711-883a-c7345ffc9a6c.png">

- 发现kafka socket 的大小错误，已调整，并重启
<img width="648" alt="image" src="https://user-images.githubusercontent.com/26213974/236653378-92e81d4a-c4ba-433c-b4b8-bb1f9be962a7.png">

**Comment by liuruibin** [comment]
开源版使用后置监听器采集结果数据导致执行后期kafka和data-streaming压力非常大，我们在企业版中去掉了后置监听器，您可以试用企业版进行测试
