### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lingmingyu** [metersphere/metersphere#24135]
### MeterSphere 版本

v2.8.0-ac76fee1

### 联系方式

19975275300

### 请描述您的需求或者改进建议

现状：只是单接口的场景失败重试不能满足业务需求，不能智能判断是之前的接口没拿到数据还是，这条接口有问题导致失败
建议：测试计划增加单个场景的的重试功能，如果用例失败整个场景重试，和单接口失败二选一

### 请描述你建议的实现方案

建议：测试计划增加单个场景的的重试功能，如果用例失败整个场景重试，和单接口失败二选一

### 附加信息

![image](https://user-images.githubusercontent.com/49540442/236090890-6855954b-6ecb-4a52-943a-40f7ed854064.png)

**Comment by luty2018** [comment]
这个我们会在v3.0实现，由用户选择是步骤重试还是场景重试。

**Comment by lingmingyu** [comment]
V3.0大概是什么时候呢

**Comment by luty2018** [comment]
11月份

**Comment by lingmingyu** [comment]
黄花菜都凉了
