### ISSUE TITLE
[FEATURE][优化建议]接口自动化建议能支持关键字的封装(类似内置的mockJS和Jmeter函数)，用于业务上的快速计算

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#24148]
### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

接口自动化建议能支持关键字的封装(类似内置的mockJS和Jmeter函数)，用于业务上的快速计算

### 重现步骤

无

### 附加信息

![9517d641f5b9ec35a92a6bded822fb5](https://user-images.githubusercontent.com/92150453/236126495-05c22d12-345f-48a3-a4a0-ca1d384e80bc.jpg)
![2202fcfa971fb5b4596b843bbecc6dc](https://user-images.githubusercontent.com/92150453/236126494-97c6bba3-86a3-492f-9a28-de5033717dad.png)

**Comment by luty2018** [comment]
这个需求我们已经收到了， 会在v3.0讨论规划

**Comment by luty2018** [comment]
关注v3的公共脚本功能
