### ISSUE TITLE
3个需求建议

### ISSUE THREAD

**Issue by GoldLoong** [metersphere/metersphere#24149]
### MeterSphere 版本

v1.20.x-lts

### 联系方式

443423777@qq.com

### 请描述您的需求或者改进建议

1.正则提取支持同jemeter一样的匹配规则，如list提取到多个值，需要第x个的情况目前无法很简单的提取的，会在返回的结果中随机返回任意列表的内容（如jmeter中的匹配数字：0代表随机取值功能，同时默认参数也挺有用的如提取失败不至于影响后续脚本）
2.接口定义或接口自动化中修改接口参数可以双向一键更新，或者在接口定义中修改了接口参数可以一键同步到自动化场景的对应接口。（现在必须在两边分别编辑）

### 请描述你建议的实现方案

1

### 附加信息

1

**Comment by luty2018** [comment]
感谢建议！
第1点我们调研一下jmeter。
关于第2点，接口定义里的参数录入是测试这个接口的，任何一个进入接口定义页面的人都可以录入参数来进行测试，接口定义的参数和接口自动化是没有直接关系的。您可以把接口用例用起来，使用接口自动化去引用接口用例，接口用例的参数变更后，接口自动化会引用最新的参数。

**Comment by luty2018** [comment]
第一点我们已经在v3.0中实现， 欢迎下载使用。
