### ISSUE TITLE
咱们玩的起就玩玩不起别玩，整的跟PDD砍一刀一样恶心人！

### ISSUE THREAD

**Issue by GoldLoong** [metersphere/metersphere#24150]
### 请描述您的问题

看到MeterSphere 实战训练营付费课程有优惠，这么优惠当然可以购买系统学习一下，去开发那把自己手机拿回来，提示付款0.1元，第一次扫码超时，刷新重新付款变成了199，玩得起就玩别不起别玩！别整的跟PDD砍一刀一样，不差那2百，但是你这个行为不恶心膈应人！ 有截图为证！

**Comment by songbing0312** [comment]
我是本课程的讲师，《MeterSphere 实战训练营》课程今天早上11:00整，到11:10分在进行内容调整，其中价格设置有误，正好被您看到，给您造成困扰，实在报歉
