### ISSUE TITLE
[QUESTION] mac m1适配问题

### ISSUE THREAD

**Issue by linghao-meng** [metersphere/metersphere#24153]
### 请描述您的问题

之前尝试过在mac m1上进行安装metersphere安装, 但是按照文档上的操作安装无法继续下去
想请问有计划在mac m1上适配一下更新下文档吗?

**Comment by liuruibin** [comment]
您好，我们仅支持x86和部分arm64芯片的镜像。mac m1 版本镜像暂时没有计划
