### ISSUE TITLE
[BUG]接口测试：添加后置脚本，语言选择“python”，在脚本里对项目变量进行赋值，赋值的中文在项目变量里为乱码；但是相同操作和信息选择“beanshell”，没有出现乱码的问题

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24176]
### MeterSphere 版本

2.9

### 使用外置数据库

否

### 问题描述

[BUG]接口测试：添加后置脚本，语言选择“python”，在脚本里对项目变量进行赋值，赋值的中文在项目变量里为乱码；但是相同操作和信息选择“beanshell”，没有出现乱码的问题

### 重现步骤

[BUG]接口测试：添加后置脚本，语言选择“python”，在脚本里对项目变量进行赋值，赋值的中文在项目变量里为乱码；但是相同操作和信息选择“beanshell”，没有出现乱码的问题

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/236178010-42db2514-c0fc-4ddb-b16d-692c5c550138.png)
![image](https://user-images.githubusercontent.com/78218624/236178622-f86a7f78-07ab-4125-8c66-6ed08e2f2d94.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9.1修复。
