### ISSUE TITLE
[BUG]接口自动化-跨项目选择后，删除另一个项目的权限，测试计划关联后，计划不执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24178]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.9

### 使用外置数据库

否

### 问题描述

接口自动化-跨项目选择后，删除另一个项目的权限，场景内可以调试，测试计划关联后，计划不执行，报告空白

### 重现步骤

1.场景内跨项目导入场景，
![image](https://user-images.githubusercontent.com/103627487/236179263-afb7f1b0-275c-4d33-a0dd-2cba50508dc4.png)
2. 切換到没有另一项目权限的用户（例如图切换到没有kaibo项目权限的用户），場景内另一項目环境不显示
![image](https://user-images.githubusercontent.com/103627487/236179729-6e5256e7-ab7d-4000-9e15-feb7c6e2f72a.png)
3.测试计划关联该场景，因为没有另一项目权限，只能选择该项目环境
![image](https://user-images.githubusercontent.com/103627487/236180137-590dd67e-5e94-4e2f-85db-012645ec1663.png)
4. 测试计划执行，执行页面报告空白，没有用例展示，任务中心也没有报告
![image](https://user-images.githubusercontent.com/103627487/236180467-912ca6db-388d-4d73-8424-2d0528b68ba1.png)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.9.1修复～

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
