### ISSUE TITLE
断言正则表达式错误

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#24186]
目前判断包含不包含都是当字符串处理的，暂时不支持数字判断，您可以在选包含不包含的那里选正则表达式
![image](https://user-images.githubusercontent.com/73461316/188566002-c0296d23-1fab-4823-be8e-680dda20cdcf.png)

_Originally posted by @zyyfit in https://github.com/metersphere/metersphere/issues/17644#issuecomment-1237728681_

好像^((?!1333).)*$ 这样的超过个位数的数字就会匹配上，看看正则表达式的解析是不是有问题？

**Comment by song-tianyang** [comment]
您好，您可以在正则表达式验证网站上校验正则表达式是否正确。

**Comment by Faerie1999** [comment]
> 您好，您可以在正则表达式验证网站上校验正则表达式是否正确。

正确，你可以试试，真的正确。

https://www.site24x7.com/zhcn/tools/regex-parser.html

![1073971683194309_ pic](https://user-images.githubusercontent.com/31870788/236796966-346a255a-637c-4d7c-a74b-5f632e65b53a.jpg)
![1073991683194349_ pic](https://user-images.githubusercontent.com/31870788/236796986-3f8e961d-fd45-4137-8cf7-b9fea9b8f4cd.jpg)

**Comment by song-tianyang** [comment]
这个正则建议是基于Java或js的写法。 
同时，我在您上图的网站上验证，以及自己使用接口返回内容进行验证的时候发现：
如果返回单行数据，是可以正常匹配的；
如果返回的内容是多行，这个正则表达式无法匹配，需要处理一下。

**Comment by Faerie1999** [comment]
单行数据、多行数据结果是一样的。
![image](https://user-images.githubusercontent.com/31870788/237008551-ca3e8e3c-dfd0-4d8b-9889-5fa5b733ba41.png)
![image](https://user-images.githubusercontent.com/31870788/237008622-fdb7ff01-798c-40e7-81b4-33166530f9b5.png)
![image](https://user-images.githubusercontent.com/31870788/237008908-d8f9762b-f0f9-425b-b6cc-130fd613bdc6.png)

![image](https://user-images.githubusercontent.com/31870788/237008742-a40996ca-7762-4cb2-87bb-a639994ce8d3.png)

而metersphere中，如果结果返回的值 $.result[*].id 是130100,1,2,4，正则匹配的断言会正确；如果结果返回的值 $.result[*].id 是13010,1,2,4，正则匹配的断言还是会正确。按理说前者应该是错误，后者应该是正确。

**Comment by Somebody-JIAN** [comment]
我明白了，您是用$.result[*]来取值的。 *匹配的是任意值。 所以只要有一个是符合条件的就会是true
