### ISSUE TITLE
[BUG]测试计划关联用例后，删除环境，计划不执行，报告空白

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24194]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.9

### 使用外置数据库

否

### 问题描述

测试计划关联用例后，删除环境，计划不执行，报告空白

### 重现步骤

1.测试计划关联场景用例
![image](https://user-images.githubusercontent.com/103627487/236381587-a124e6a3-4162-48ac-a8c7-a14c39b3389d.png)
2.环境管理中删除关联场景用例时选择的环境
3.执行测试计划，计划不执行，报告内容为空
![image](https://user-images.githubusercontent.com/103627487/236381725-871abbac-6281-4e93-b2df-329782de2028.png)

### 期待的正确结果

希望环境管理中有测试计划在引用这个环境的时候，环境不允许删除

**Comment by zrfit** [comment]
您好，感谢您的反馈！v2.10优化为删除环境增加提示信息：删除(删除环境)可能导致使用该环境的测试执行失败。
