### ISSUE TITLE
[BUG]性能测试执行：性能测试脚本为接口测试用例一键转性能测试；点击保存并执行，报告也都能正常，但是系统后台日志有错误：查询关注人接口异常

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24197]
### MeterSphere 版本

2.9

### 使用外置数据库

否

### 问题描述

[BUG]性能测试执行：性能测试脚本为接口测试用例一键转性能测试；点击保存并执行，报告也都能正常，但是系统后台日志有错误：查询关注人接口异常

1、接口用例，比如登录接口。调试成功；查看系统日志，里面没有任何错误信息。
2、一键转性能测试，设置相关发压策略，点击保存并执行
3、性能报告也能正常显示
4、后台查看性能日志：/opt/metersphere/logs/performance-test/info.log 日志文件出现，接口执行异常日志。这个日志里的错误信息，不是我的性能测试脚本触发的，我的脚本仅仅是ms的登录接口。

### 重现步骤

[BUG]性能测试执行：性能测试脚本为接口测试用例一键转性能测试；点击保存并执行，报告也都能正常，但是系统后台日志有错误：查询关注人接口异常

1、接口用例，比如登录接口。调试成功
2、一键转性能测试，设置相关发压策略，点击保存并执行
3、性能报告也能正常显示
4、后台查看性能日志：/opt/metersphere/logs/performance-test/info.log 日志文件出现，接口执行异常日志。这个日志里的错误信息，不是我的性能测试脚本触发的，我的脚本仅仅是ms的登录接口。

### 附加信息

![image](https://user-images.githubusercontent.com/78218624/236387867-2b901800-e214-4044-81d3-6ce1db6a7406.png)
![image](https://user-images.githubusercontent.com/78218624/236387897-28fd7ada-ebd7-4d67-92df-fa2b0b183d84.png)

**Comment by liuruibin** [comment]
您好，性能测试执行在新容器内，这个info日志是性能测试模块内的日志，应该是其他原因导致的

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
