### ISSUE TITLE
[BUG]接口定义导入swagger文件时报解析数据出错，实际检查文件没有格式及内容错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#24191]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.9.0及v2.8.1

### 使用外置数据库

否

### 问题描述

接口定义导入swagger文件时报解析数据出错，实际检查文件没有格式及内容错误

### 重现步骤

接口定义导入swagger文件  ，具体文件麻烦请私聊我获取

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.9.1修复。
