### ISSUE TITLE
[BUG]文件下载类型接口一直在测试中，后台无日志，无法查看响应内容

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24208]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

文件下载类型接口点击执行一直在测试中，后台无日志，无法查看响应内容

### 重现步骤

1.下载地址是https://cdn0-download-offline-installer.fit2cloud.com/docs/support/metersphere-plugin-mqtt-2.5-jar-with-all-dependencies.jar
2.使用接口测试，一直显示测试中
![image](https://user-images.githubusercontent.com/88763608/236407910-8947cbea-cf20-4cb9-a046-fa27c72527ff.png)
3.后台其实已经报错，页面无任何提示
![image](https://user-images.githubusercontent.com/88763608/236407985-80220461-516e-4e2e-a750-035c86f838cf.png)
![image](https://user-images.githubusercontent.com/88763608/236407986-31f98c6e-42d9-423b-9969-7683218fbe2c.png)

### 期待的正确结果

希望能下载，报错也有提示

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、您提供的地址用浏览器打开报错，确认地址是否正确并有效？
<img width="965" alt="image" src="https://user-images.githubusercontent.com/99731894/236623513-f0d81f50-71ad-41fe-be84-3517de6e9e74.png">
<img width="865" alt="image" src="https://user-images.githubusercontent.com/99731894/236623886-e77901b2-3df1-45b8-b0e2-182d0de9a5f4.png">
2、在最新版本v2.9用同类接口验证是可以的
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/99731894/236623587-8838e9be-b024-4ac6-a10d-aadb4ed89f80.png">
3、建议用正确有效的地址升级到到最新版本尝试。

**Comment by zrfit** [comment]
私下沟通提供正确链接后复现，计划v2.10修复。

**Comment by shenkaibo** [comment]
> 更改下websocket配置就行：
> 
> spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=838860800
@fit2-zhao 这个配置只能在 docker-compose-gateway.yaml 中修改，在 metersphere.properties 中修改不生效
