### ISSUE TITLE
[BUG]导入用例的时候由于卡顿，出现用例重复导入

### ISSUE THREAD

**Issue by lixuejun725** [metersphere/metersphere#24205]
### 联系方式

xuejun_315@613.com

### MeterSphere 版本

高校cloud版

### 使用外置数据库

否

### 问题描述

导入用例的时候由于卡顿，出现用例重复导入,但手动无法新建同名用例文件夹内，且平台特别卡，
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/38548829/236406260-26b83574-277e-4423-b150-2646947f5fba.png">

### 重现步骤

在功能用例点击导入，出现导入卡顿，多次点击，会出现用例重复导入。

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，导入多少用例？私下提供下导入数据和确认下环境。
