### ISSUE TITLE
[BUG]创建测试计划，选择责任人之后ID显示过长，文本框放不下。

### ISSUE THREAD

**Issue by lixuejun725** [metersphere/metersphere#24209]
### 联系方式

xuejun_315@613.com

### MeterSphere 版本

高校cloud版

### 使用外置数据库

否

### 问题描述

创建测试计划，选择责任人之后ID显示过长，文本框放不下。
<img width="896" alt="image" src="https://user-images.githubusercontent.com/38548829/236410423-cb86ebac-b2e1-411e-992d-e4aa55588d79.png">

### 重现步骤

创建测试计划，选择责任人

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.0-lts中已优化。
