### ISSUE TITLE
[BUG]多个hosts域名配置导出jmeter时只有一个存在

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24210]
### 联系方式

jianqiang.liu@fit2cloud.com

### MeterSphere 版本

v2.8.X

### 使用外置数据库

否

### 问题描述

多个hosts域名，一个域名对应的请求解析道对应的IP，然后重定向访问第二个域名时无法解析为对应IP

### 重现步骤

1、项目环境配置多个host域名
<img width="919" alt="image" src="https://user-images.githubusercontent.com/40912189/236413659-4f3accd8-2335-4a8c-b641-caa03439a122.png">
2、场景里引用
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/40912189/236414218-fe4aa9cd-4257-4106-b7b6-f646f7ae8f8d.png">
3、导出为jmeter格式
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/40912189/236414292-b2d6eed3-f759-4025-b6b1-31733b15b61b.png">
4、导入到jmeter之后只有一个host映射
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/40912189/236414125-726c0baa-68a0-419b-abde-0fa3b10efac0.png">

### 期待的正确结果

多个host域名配置都能导入到jmeter里

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，您的场景是都用到这2个域名了吗？请私下提供下场景。

**Comment by song-tianyang** [comment]
您好

场景导出jmx，是以场景的视角，在它选择的环境中使用到了哪些配置，就会把哪些配置添加到jmx中。

也就是说，如果您的场景里只用到一个host，就不会把多余的host配置导出来。

![image](https://user-images.githubusercontent.com/75963100/236628512-ea401d67-73a6-4aee-b90e-bedf1b910913.png)

类似于上图，http环境配置了不同的启用条件，不同的启用条件对应的host也不一样。我们只会把满足启用条件的信息导出来。

我们认为按照场景导出其需要的信息，不额外添加其余配置，这样做是正确的。

**Comment by sss903065212** [comment]
是这边客户提出的问题，
比如：
1.1.1.1 映射 www.baidu.com
1.1.1.1 映射 www.fit2cloud.com

现象如下：
我在场景里面调用www.baidu.com 重定向到了www.fit2cloud.com ，由www.fit2cloud.com给我返回信息
但导出的jmx 只有1.1.1.1 映射 www.baidu.com，没有1.1.1.1 映射 www.fit2cloud.com 所以访问失败

问题：怎么做才能把1.1.1.1 映射 www.fit2cloud.com 也映射到jmx

**Comment by song-tianyang** [comment]
![image](https://user-images.githubusercontent.com/75963100/236791836-3b364260-89da-4577-8e35-e54c69f4ffc0.png)
不好意思， 我并没有达到您这一步的效果。
这是我的环境配置：
![image](https://user-images.githubusercontent.com/75963100/236792118-a7f200b2-232a-42ea-943c-94ea49530fda.png)
这是我的场景报告：
![image](https://user-images.githubusercontent.com/75963100/236792279-f5a96540-f3ed-4436-913e-e92e34050dd0.png)

我在场景中也没达到您说的要www.fit2cloud.com返回信息。

**Comment by sss903065212** [comment]
1.1.1.1 映射 A域名
1.1.1.1 映射 B域名
这个很难复现的，首先需要有一个真实的A域名，然后调用A域名的API，这个API所在的系统会把这个请求重定向到B域名

<img width="692" alt="image" src="https://user-images.githubusercontent.com/40912189/236983694-640f0661-9f0e-4259-b4c2-d67c0ceb7bc0.png">
这个是假设，客户是真实的场景，我无法给你提供这个真实的A、B域名，客户那边就算提供了也无法调用的，他们是内网
