### ISSUE TITLE
[BUG]测试场景中删去引用case会导致原复制的case内容缺失

### ISSUE THREAD

**Issue by 031802306** [metersphere/metersphere#24223]
### 联系方式

chenxinbin@star-net.cn

### MeterSphere 版本

 v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

当在一个测试场景中同时引入了多个case（引用或复制方式）（该case拥有前置操作、后置操作或者断言）。
使用批量删除，勾选删除其中一个case时，会导致另一个留下的case的前置操作、后置操作或断言被清空。

### 重现步骤

若留下的case是复制的，那么在保存刷新过后该case原来拥有的前置操作、后置操作或者断言就无法还原了。
这对于一个场景需要多次引用或复制同一个case时，很影响使用。

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v1.20.22未复现该问题，建议升级尝试。
