### ISSUE TITLE
[BUG] 【接口测试】-接口的请求参数值过大，参数的格式会有问题，导致接口请求报格式问题

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#24238]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v1.20.20-lts，2.9

### 使用外置数据库

是

### 问题描述

有个接口的请求参数过大，在ms上会报格式问题，同样的参数在postman请求是正常的

### 重现步骤

1.创建一个接口
2.将附件的请求参数维护到接口中
3.观察json的格式

### 期待的正确结果

接口能正常调通

### 附加信息

1.接口请求参数
[ms参数.zip](https://github.com/metersphere/metersphere/files/11410975/ms.zip)

2.ms和postman接口调用对比
![image](https://user-images.githubusercontent.com/45531073/236593036-3c98491a-c6a3-4d7d-8680-d51acdda83d2.png)

![436840888fe2ca497eda44e7f4dc91f](https://user-images.githubusercontent.com/45531073/236593062-9a924e55-4f43-4dd6-b933-15c9cfcb5454.png)

3.  在ms上格式显示有问题
![d8a86778e72bace9ce0d6b2402106ee](https://user-images.githubusercontent.com/45531073/236593071-7fffc1f2-04e8-49b1-a04a-6c4d1af9050d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by fit2-zhao** [comment]
感谢反馈，目前定位到是我们使用的底层测试引擎JMeter的一个bug：https://github.com/apache/jmeter/issues/5035
这个缺陷原因是JSON中含有变量+三个反斜杠 “ \ ”转译符号导致，建议把 三个反斜“ \ ” 改成 单 ” \ “ 就能正常使用。

**Comment by karhow** [comment]
> 感谢反馈，目前定位到是我们使用的底层测试引擎JMeter的一个bug：[apache/jmeter#5035](https://github.com/apache/jmeter/issues/5035) 这个缺陷原因是JSON中含有变量+三个反斜杠 “ \ ”转译符号导致，建议把 三个反斜“ \ ” 改成 单 ” \ “ 就能正常使用。

为什么三个反斜“ \ ” 改成 单 ” \ “ 就能正常使用，可以说明一下原因吗？
