### ISSUE TITLE
[BUG]性能测试请求数较多时，导出性能测试报告后，请求统计内容导出不全

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#24237]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

性能测试请求数较多时，导出性能测试报告后，请求统计内容导出不全

### 重现步骤

选定请求内容较多的脚本做性能测试，导出性能测试报告后，请求统计内容导出不全

### 期待的正确结果

可以全部导出

### 附加信息

页面报告内容：
![image](https://user-images.githubusercontent.com/32027713/236592594-650c0fb9-98f7-4216-9d51-9be79e73a8fa.png)

导出实际报告内容：
![image](https://user-images.githubusercontent.com/32027713/236592609-bd5d109d-93a5-42f1-ba70-60c44d73b7e1.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，预计2.10版本优化。
/
Duplicate of #22359
