### ISSUE TITLE
[FEATURE]使用脑图去编写测试用例，保存时如果有模块名称重复，希望提示语可以加上重复模块的名称

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#24236]
### MeterSphere 版本

v2.9.0

### 联系方式

mengqiao.shi@fit2cloud.com

### 请描述您的需求或者改进建议

使用脑图去编写测试用例，保存时如果有模块名称重复，希望提示语可以加上重复模块的名称，如果写的太多了，再回去一条条找比较费时间
<img width="964" alt="image" src="https://user-images.githubusercontent.com/104493699/236591833-f05027f2-7b5e-4be8-92a8-b0f5518328ab.png">

**Comment by luty2018** [comment]
不是太有必要把。
