### ISSUE TITLE
IDEA 配置MeterSphere 插件信息时 对应的version内容没有同步过来

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#24241]
### 联系方式

14707070227

### MeterSphere 版本

 v2.9.0-426de152

### 使用外置数据库

否

### 问题描述

在 IDEA 2023.1 版本中下载了 1.2.5 的metersphere 插件，配置好插件信息，点击test，提示同步成功，但是，对应的version内容没有同步过来

### 重现步骤

1. 在IDEA 上面离线安装最新的 metersphere（v1.2.5） 插件
2. 在IDEA 上面配置 metersphere 插件信息
3. 点击 test，提示同步成功，工作空间、项目名称、模块信息都同步过来了，但是对应的version内容是空的，下拉没有数据

### 期待的正确结果

点击 test，提示同步成功，version下拉有版本内容数据

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://user-images.githubusercontent.com/50016789/236597858-324d40f5-54dc-45b4-8e6e-ad852de7d146.png)
![image](https://user-images.githubusercontent.com/50016789/236597929-9b1def67-f026-4c56-a22e-5d5f54db5c12.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
MS v2.10.0-lts中已优化，请使用最新的MeterSphere idea插件。
插件下载地址：
https://plugins.jetbrains.com/plugin/18097-metersphere/versions
