### ISSUE TITLE
[FEATURE]接口自动化场景能否放开失败后继续执行？

### ISSUE THREAD

**Issue by Donly16** [metersphere/metersphere#24250]
### MeterSphere 版本

v1.20.20-lts-79d354a6

### 请描述您的需求或者改进建议

接口自动化循环里面，只有次数循环可以设置失败后是否继续，且只能在只有一个请求的时候打开。其他2种循环根本就无法设置。
许多测试场景需要失败后继续的，能否放开这个限制？允许失败后继续执行？

**Comment by luty2018** [comment]
其他两种循环是有结束条件的， 满足就结束了，能举个例子，什么场景需要满足非次数循环又要满足失败后继续的吗？
