### ISSUE TITLE
grpc 插件好像不兼容[BUG]

### ISSUE THREAD

**Issue by 710210668** [metersphere/metersphere#24252]
### 联系方式

710210668@qq.com

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

用了metersphere-plugin-GrpcSampler-1.1.0-jar-with-all-dependencies.jar 这个插件，来支持grpc测试， 但测试的时候报错， api-test 错我日志如下：2023-05-06 10:20:05,419 [qtp2096217940-11609] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver 207 - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Could not resolve type id 'io.metersphere.plugin.grpc.sampler.MsGrpcSampler' as a subtype of `io.metersphere.plugin.core.MsTestElement`: no such class found]

![image](https://user-images.githubusercontent.com/42403461/236617502-b73ec4be-e4b1-48f1-abe2-c7d37fd81099.png)

### 重现步骤

可以复现

**Comment by youliyuan-fit2cloud** [comment]
你好，看起来是插件找不到了，请检查一下grpc插件上传是否正常。
插件使用方法：
1、将 grpc 插件在系统设置-插件管理模块导入
2、将 grpc 协议的 proto 文件目录压缩(.zip 格式)
3、在 MeterSphere 项目设置-文件管理上传压缩包
4、GRPC 插件参数：原型文件夹路径填写 压缩包文件名（如：hello_account.zip）

**Comment by 710210668** [comment]
ok

**Comment by youliyuan-fit2cloud** [comment]
长时间未反馈，关闭该问题。如再次遇到请重新提issue，感谢理解和支持～
