### ISSUE TITLE
[BUG]metersphere提bug的默认模版中，没有拉取到JIRA中Sprint和链接的事务，两个字段

### ISSUE THREAD

**Issue by FrancoFang667788** [metersphere/metersphere#24266]
### MeterSphere 版本

版本:   v1.20.10-lts

### 使用外置数据库

是

### 问题描述

[BUG]metersphere提bug的默认模版中，没有拉取到JIRA中Sprint和链接的事务，两个字段

<img width="808" alt="image" src="https://user-images.githubusercontent.com/48195272/236778178-d38d8a04-d7da-4b11-a3b5-3f0bb7973940.png">
![image](https://user-images.githubusercontent.com/48195272/236778199-cc590e37-66a9-441f-afb8-a2a22e1906b4.png)

### 重现步骤

[BUG]metersphere提bug的默认模版中，没有拉取到JIRA中Sprint和链接的事务，两个字段

**Comment by luty2018** [comment]
这个我们在新版本已经解决了， 要升级到v2.9.1版本，或者可以月底升级到v2.10LTS版本

**Comment by FrancoFang667788** [comment]
最新的事2.9.0的版本，也可以吗？

**Comment by youliyuan-fit2cloud** [comment]
> 最新的事2.9.0的版本，也可以吗？

升级到v2.9.1版本
