### ISSUE TITLE
[FEATURE]接口Case和场景测试的编辑页面，是否可以提供一个回滚功能，回滚回修改前的，在同一个版本内回滚

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24269]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

一次误操作，造成一个脚本测试用例被覆盖，无法还原

**Comment by luty2018** [comment]
我们企业版有提供版本功能， 你可以在官网申请企业版试用哈。

**Comment by YellCatt** [comment]
> 我们企业版有提供版本功能， 你可以在官网申请企业版试用哈。

我觉得不是版本功能，是一个临时性的回滚功能，并并非与上个版本对比，就像ctrl+z撤销一样

**Comment by luty2018** [comment]
数据回滚是一个比较复杂的需求， 目前我们还无法支持， 非常抱歉。
