### ISSUE TITLE
[FEATURE]建议多用户使用同一个环境运行接口的时候能够串行执行

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24277]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

两个用户共用一个环境，现在是并行执行用例的
我的想法是像两个用户用共享的打印机，是串行执行接口用例的，如果是并行执行，容易造成用例错误

**Comment by luty2018** [comment]
感谢建议， 我们会在v3.0规划多人协同执行的解决方案

**Comment by luty2018** [comment]
另外，希望进一步得到这个问题的详细使用场景
两个人同时点的执行吗？什么场景下会有这种操作?

**Comment by YellCatt** [comment]
> 另外，希望进一步得到这个问题的详细使用场景 两个人同时点的执行吗？什么场景下会有这种操作?

我是在使用过程中，越发觉得很多情况下并行都是不可行的，因为测试资源真的很有限，即是一般人都多过测试环境配置，每个测试用例在独立的情况下，如果两个人在同时编辑好用例准备运行，那么在一个环境里一定会有冲突。

**Comment by YellCatt** [comment]
> 

比如有6个人，测试一个项目，但是自动化测试只有3个，那么这6个人如果并行写测试用例，同时提交了测试用例去运行，那么3个环境，必须得有人排队，ms必须得告知用户那个环境是正在使用的，哪个是空闲的，或者ms去自动分发测试用例在哪个环境里去执行。

**Comment by luty2018** [comment]
<img width="463" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/6de9721f-4e6e-440c-a266-ef4e91c47710">
麻烦你添加我的企业微信进一步沟通，谢谢！

**Comment by YellCatt** [comment]
> <img alt="image" width="463" src="https://user-images.githubusercontent.com/36292514/240549845-6de9721f-4e6e-440c-a266-ef4e91c47710.png"> 麻烦你添加我的企业微信进一步沟通，谢谢！

能不能用微信加好友，企业微信，不会加好友啊，要不你教下怎么操作？

**Comment by luty2018** [comment]
与 #22854 重复
