### ISSUE TITLE
[FEATURE]是否可以添加一个需求单编写的功能

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24270]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：工作流程是 给一个需求单->编写测试功能用例->手动测试->转换为自动化测试用例->添加到测试计划中->每天跑

原因：很多时候需求改变，最好直接在ms上能看到原始的需求单是怎么样的

**Comment by luty2018** [comment]
你好， 目前我们还是会聚焦在测试平台的范围内，测试用例支持关联需求，在后续的版本也会支持系统内打开需求查阅。

**Comment by YellCatt** [comment]
> 你好， 目前我们还是会聚焦在测试平台的范围内，测试用例支持关联需求，在后续的版本也会支持系统内打开需求查阅。

我觉得这也是测试的范围内，且有利于形成测试工作的闭环，也能提供一个测试覆盖率的指标

**Comment by luty2018** [comment]
> > 你好， 目前我们还是会聚焦在测试平台的范围内，测试用例支持关联需求，在后续的版本也会支持系统内打开需求查阅。
> 
> 我觉得这也是测试的范围内，且有利于形成测试工作的闭环，也能提供一个测试覆盖率的指标

不好意思， 暂时没有需求这个规划。
