### ISSUE TITLE
[BUG]【模板设置】用例模板中自定义字段，勾选条件进行筛选，没有筛选想要的数据

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24275]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

1.20.22-lts

### 使用外置数据库

否

### 问题描述

【模板设置】用例模板中自定义字段进行筛选不好使

### 重现步骤

1.【模板设置】自定义字段aa只有是、否两个值，将其加入到用例模板中
![image](https://user-images.githubusercontent.com/104960608/236809138-feedaca7-8f83-4cf8-b83a-23738131b801.png)
2.新建两条用例，aa字段分别为是/否
![image](https://user-images.githubusercontent.com/104960608/236809312-46fc4b5f-fe0c-4557-a02c-1635c1e40a2e.png)
3.勾选字段后点击筛选，页面还是没筛选出想要的数据
![image](https://user-images.githubusercontent.com/104960608/236809445-936d7901-ea28-44f5-87a9-6b6cad273ba0.png)
![image](https://user-images.githubusercontent.com/104960608/236809561-626f1315-00c0-4546-8ef0-85d8986f2423.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v1.20.23修复。
