### ISSUE TITLE
[FEATURE]缺陷管理希望增加一个缺陷分类功能：1、以目录树的方式展示； 2、目录支持增删改查；3、缺陷列表可以根据目录树进行搜索

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#24278]
### MeterSphere 版本

1.7.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/25762331/236984265-c5ddcdc0-8841-46d8-8b44-6b1c9906625b.png)

**Comment by luty2018** [comment]
这个我们有在v3.0规划哈

**Comment by Hyyfit** [comment]
您好，缺陷我们不考虑做模块树。如果是要分类的话，可以通过添加自定义字段的方式实现，高级搜索也是支持自定义字段的搜索的，您看这样可以解决您的问题吗？
