### ISSUE TITLE
[BUG]给接口自定义处的某个接口配置了变量路径，且该变量已配置到了环境变量中，调用时的url没有取到环境变量中的接口地址

### ISSUE THREAD

**Issue by summerswind** [metersphere/metersphere#24276]
### 联系方式

125974852@qq.com

### MeterSphere 版本

1.20.12-lts

### 使用外置数据库

否

### 问题描述

环境变量与路径变量同时存在时，应当先取路径变量

### 重现步骤

1、在接口定义中新增接口，接口详情中将路径定义变量${inteface_type}
2、在环境变量中，配置环境变量：
1）通用配置：inteface_type=vccsapitob
2）http配置环境域名：10.99.69.173:8888，启用条件“无”
3）http配置环境域名：10.99.69.173:8913，启用条件指定路径“等于”“vccsapitob”
3、调用该接口，查看到调用的地址为：http://10.99.69.173:8888/vccsapitob
已在微信群中与贵司研发“李攀”沟通，有截图详情

### 期待的正确结果

http://10.99.69.173:8913/vccsapitob

**Comment by zrfit** [comment]
您好，感谢您的反馈！路径匹配暂不支持变量方式。
