### ISSUE TITLE
[FEATURE]有一个需求：测试报告中需要对单个测试用例的用时进行统计

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24287]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试报告中需要对单个测试用例的用时进行统计
原因：无论接口case和场景用例，都不是简单的访问下，能不能通的问题，都有很多的前置条件，一个测试用例短的几十ms，长的半个小时以上对于用时时间的统计可以让我们更好的去开发出优秀的测试用例，降低环境的时间成本

**Comment by luty2018** [comment]
报告上有一个耗时，是需要什么样的统计？

**Comment by YellCatt** [comment]
> 报告上有一个耗时，是需要什么样的统计？

每个测试用例的运行耗时统计，我们需要优化测试用例，腾出更多的环境时间，运行更多的用例，降低成本

**Comment by YellCatt** [comment]
> 报告上有一个耗时，是需要什么样的统计？

实际的情况是我们编写的过程中使用了大量的time.sleep来模拟人的操作，一开始不是那么严格控制，希望场景测试能通就行，到后期，时间上不够了，需要对场景用例的用时进行控制，需要对每个测试用例的耗时进行统计

**Comment by luty2018** [comment]
这个我们调研看看

**Comment by YellCatt** [comment]
> 这个我们调研看看

好的谢谢，我个人是觉得很重要的，一个接口case节约10秒，700个，就是2小时了

**Comment by luty2018** [comment]
待 v3.0 讨论规划
