### ISSUE TITLE
[BUG]测试跟踪-测试计划实际开始和实际结束时间显示错误

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24285]
### MeterSphere 版本

v2.9.X

### 使用外置数据库

否

### 问题描述

1、手动执行测试计划  不管是串行还是并行，实际开始时间都没改变
2、定时执行测试计划  不管是串行还是并行，实际结束时间都没改变

### 重现步骤

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/40912189/237049925-d8dee634-2d21-4444-ab76-d9fad92eef79.png">
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/40912189/237050477-b269a916-e68c-49a7-86f4-36ca82ced0c2.png">

### 期待的正确结果

实际开始和结束时间 保证正确性

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这块的逻辑需要再优化一下～

**Comment by youliyuan-fit2cloud** [comment]
v2.10.0-lts中已优化。
修改后的逻辑： 执行整个测试计划时，实际开始时间刷新、实际结束时间置空、测试计划状态改为进行中 执行正常结束后，根据测试计划内的用例是否全部结束，再改实际结束时间以及测试计划状态为完成。
