### ISSUE TITLE
[FEATURE]吐槽一个问题啊，接口文档功能真的不好用啊

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24284]
### MeterSphere 版本

2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

开发组一直想用ms平台来管理接口和接口文档，但是接口文档真的不如showdoc这种看上去方便简洁紧凑，而且ms也没有提供文档的下载功能，对外提供接口文档都无法离线下载
需求：
1.修改接口文档展示
2.提供doc或者docx接口文档下载，可以是单个接口，也可以是多个接口的

**Comment by luty2018** [comment]
感谢建议， 目前接口文档是我们重点优化的功能点，我会参考你推荐的工具。
另外接口文档我们有提供在线分享的功能，是否以分享来替代下载更适合？

**Comment by YellCatt** [comment]
> 感谢建议， 目前接口文档是我们重点优化的功能点，我会参考你推荐的工具。 另外接口文档我们有提供在线分享的功能，是否以分享来替代下载更适合？

不合适，客户要求的是离线的文档，即使是html都比在线分享好。还有就是接口文档真的挺糟糕的，单个接口都没有一份直接看的文档，都是集合在一起的，不方便啊

**Comment by luty2018** [comment]
了解， 你推荐的showdoc确实看起来更简洁明了！

**Comment by YellCatt** [comment]
> 了解， 你推荐的showdoc确实看起来更简洁明了！

3.0后按我的要求改一版？

**Comment by zhangzhaox** [comment]
API文档附近下载 和API URL一键分享适用场景不同，目前是通过swagger文件中转生成word文档效果也可以

**Comment by YellCatt** [comment]
> API文档附近下载 和API URL一键分享适用场景不同，目前是通过swagger文件中转生成word文档效果也可以

具体怎么操作？

**Comment by zhangzhaox** [comment]
@YellCatt 请参考https://github.com/JMCuixy/swagger2word
目前有个问题ms平台导出的swagger-json文件 没有响应报文  少了这部分内容
@luty2018 希望3.0版本之前能修改这个bug

**Comment by luty2018** [comment]
> @YellCatt 请参考https://github.com/JMCuixy/swagger2word 目前有个问题ms平台导出的swagger-json文件 没有响应报文 少了这部分内容 @luty2018 希望3.0版本之前能修改这个bug

你使用的哪个版本， 目前我们导出会有响应体，前提是也要有状态码
