### ISSUE TITLE
[BUG]导入缺陷时，当缺陷字段为输入框，并存在回车时，会导致数据解析失败

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#24283]
### MeterSphere 版本

V2.7.1

### 使用外置数据库

否

### 问题描述

导入缺陷时，当缺陷字段为输入框，并存在回车时，会导致数据解析失败

### 重现步骤

见问题描述，问题现象、excel文件已单独发给建星

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。
