### ISSUE TITLE
[BUG]UI 场景中，元素步骤 不能拖动到 两个指令中间

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#24281]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.9.0

### 使用外置数据库

否

### 问题描述

UI 场景中，元素步骤 不能拖动到 两个指令中间

### 重现步骤

1. 创建一个包含两个指令和一个元素操作步骤的 UI 场景
![image](https://user-images.githubusercontent.com/30038088/237005041-65044ba0-8794-4cd2-beb2-a0bfa4447bf6.png)
2.将元素操作步骤 拖动到 两个指令中间，无法拖动进去。
![image](https://user-images.githubusercontent.com/30038088/237005258-562bbd85-5136-4021-ad69-e8274c3e2efc.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。
