### ISSUE TITLE
[BUG]性能测试勾选顺序执行场景，但报告里的请求统计顺序不对

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24290]
### 联系方式

jianqiang.liu@fit2cloud.com

### MeterSphere 版本

V2.9

### 使用外置数据库

否

### 重现步骤

请看问题描述

### 期待的正确结果

按顺序就要按顺序

**Comment by zrfit** [comment]
您好，感谢您的反馈！方便私下提供下jmx文件吗？

**Comment by sss903065212** [comment]
<img width="1049" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/c75e69ef-77ad-4ac5-8049-d7aeba8ee104">

<img width="913" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/dc7c301d-301f-4db5-9f79-ea23a4d630c5">

**Comment by sss903065212** [comment]
已发送企业微信

**Comment by liuruibin** [comment]
您好，您可以检查资源池配置，如果开启了后置监听器的话可以尝试关闭这个开关。之后再进行性能测试

**Comment by liuruibin** [comment]
https://github.com/metersphere/data-streaming/pull/61

**Comment by liuruibin** [comment]
顺序执行场景的开关是多场景同时只能执行一个，在同一个场景内执行是按照sampler顺序进行的。jmeter生成的表格是无序的，我们这里按照label的出现顺序进行了排序，如果两个label名称有重复的话会造成排序错误。您可以先修改label名称来规避这个问题，我们后续会优化代码。下图是改了label后正常的排序
<img width="303" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/aa70ccd5-adf9-47ee-bdf4-8b7fd6df5a0b">
下面是重复的部分
<img width="350" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/0da8c0ad-da66-4848-b760-28ddf81bc9f7">

**Comment by sss903065212** [comment]
这个场景目前，我们在客户现场发现 A场景引用B场景（包含条件控制器），经试验 将A的自定义请求放到B的条件控制器中，顺序OK的

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/commit/6f2183769abf4275b90bcb3a3677f1756de64550 代码改动在这里

**Comment by sss903065212** [comment]
ok,那我们这边联系客户更改一下标签，测试看下
