### ISSUE TITLE
[FEATURE]测试报告和测试结果中都应该展示脚本运行的结果，且脚本运行失败，用例也应该算是失败

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24295]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试报告和测试结果中都应该展示脚本运行的结果，且脚本运行失败，用例也应该算是失败
原因：一个完整的测试用例应该是全局前置脚本，用例前置脚本，接口访问，断言，用例后置脚本，全局后置脚本，这中间有任何一个报错或者失败都算作测试用例运行失败，最好【响应体 响应头 控制台 断言 提取 请求内容】再加个脚本，展示脚本是否运行成功

**Comment by luty2018** [comment]
如何判断脚本执行是否失败这个系统是获取不到的。

**Comment by YellCatt** [comment]
> 如何判断脚本执行是否失败这个系统是获取不到的。

肯定是可以获取到的

**Comment by luty2018** [comment]
> > 如何判断脚本执行是否失败这个系统是获取不到的。
> 
> 肯定是可以获取到的

很乐意听一下你的方案。

由于脚本是用户主观添加的，对于脚本的编写、标准这些都是程序无法控制的，目前我们给的解决方案是，用户在脚本里面添加判断脚本是否成功的步骤，如果失败，可以添加系统提供的终止测试的步骤。如下图：
![image](https://github.com/metersphere/metersphere/assets/36292514/865c989f-56df-45aa-847d-fe503d4bd7a4)

**Comment by YellCatt** [comment]
> > > 如何判断脚本执行是否失败这个系统是获取不到的。
> > 
> > 
> > 肯定是可以获取到的
> 
> 很乐意听一下你的方案。
> 
> 由于脚本是用户主观添加的，对于脚本的编写、标准这些都是程序无法控制的，目前我们给的解决方案是，用户在脚本里面添加判断脚本是否成功的步骤，如果失败，可以添加系统提供的终止测试的步骤。如下图： ![image](https://user-images.githubusercontent.com/36292514/237273821-865c989f-56df-45aa-847d-fe503d4bd7a4.png)

目前我也不知道是怎么做到的，但是我现在在用的版本是可以实现的，我们开发做了点修改。

**Comment by YellCatt** [comment]
> > > 如何判断脚本执行是否失败这个系统是获取不到的。
> > 
> > 
> > 肯定是可以获取到的
> 
> 很乐意听一下你的方案。
> 
> 由于脚本是用户主观添加的，对于脚本的编写、标准这些都是程序无法控制的，目前我们给的解决方案是，用户在脚本里面添加判断脚本是否成功的步骤，如果失败，可以添加系统提供的终止测试的步骤。如下图： ![image](https://user-images.githubusercontent.com/36292514/237273821-865c989f-56df-45aa-847d-fe503d4bd7a4.png)

开发跟我聊了下，编译器能编译 能执行就认为是成功的，即没有报错为成功

**Comment by luty2018** [comment]
这不合理吧

**Comment by YellCatt** [comment]
> 这不合理吧

我觉得挺合理的，除非测试人员都是用了try-catch去屏蔽报错信息，能检测到前后端的脚本运行失败，一个完整的测试用例才全完整

**Comment by luty2018** [comment]
那我们没有这个计划。
