### ISSUE TITLE
[BUG][性能测试]多线程组中，脚本中全局变量的设置没有生效

### ISSUE THREAD

**Issue by yangfan112** [metersphere/metersphere#24299]
### MeterSphere 版本

 v2.8.1-26ae5c20

### 使用外置数据库

是

### 问题描述

1、Jmeter脚本跨线程组使用token全局变量
2、Jmeter工具脚本没有问题
3、MS上全局变量没有生效，导致请求失败
![image](https://github.com/metersphere/metersphere/assets/48746721/113c68ea-c3ba-4098-81ca-d27312459155)
![image](https://github.com/metersphere/metersphere/assets/48746721/848e44a3-08b0-419e-9835-daafcb073ff6)
![image](https://github.com/metersphere/metersphere/assets/48746721/0706db2d-9cc5-4dbf-b760-1820bc8b6eef)
![image](https://github.com/metersphere/metersphere/assets/48746721/999a82d9-fc12-4036-81b1-0fb37bc47a65)

### 重现步骤

1、建立多线程组的jmx脚本
2、创建全局变量
3、在其余线程组中引用全局变量
4、上传MS平台，创建性能测试场景，并运行，查看结果

### 期待的正确结果

MS平台中，全局变量不会失效

**Comment by yangfan112** [comment]
好的，我试下

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
