### ISSUE TITLE
[BUG]接口测试》》前后置脚本》》语言选择python，if判断条件为中文时，即使条件满足也跳转到else。使用beanshell没有问题。python脚本处理中文这里应该是有bug

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24296]
### MeterSphere 版本

2.9

### 使用外置数据库

否

### 问题描述

[BUG]接口测试》》前后置脚本》》语言选择python，if判断条件为中文时，即使条件满足也跳转到else。使用beanshell没有问题。python脚本处理中文这里应该是有bug

### 重现步骤

[BUG]接口测试》》前后置脚本》》语言选择python，if判断条件为中文时，即使条件满足也跳转到else。使用beanshell没有问题。python脚本处理中文这里应该是有bug

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/49dee44c-d6d2-494b-9189-6df8e2cf9e99)

**Comment by fit2-zhao** [comment]
感谢反馈，参考这个 #24294
