### ISSUE TITLE
[BUG]【项目设置-模板管理】将用例模板-用例步骤设置为“文本描述”后不生效。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24297]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.9.0

### 使用外置数据库

否

### 问题描述

【项目设置-模板管理】将用例模板-用例步骤设置为“文本描述”后不生效。

### 重现步骤

1.【项目设置-模板管理】将用例模板-用例步骤设置为文本描述后，点击保存
![image](https://github.com/metersphere/metersphere/assets/104960608/4908d196-0c1d-412a-9146-60b25b332900)
![image](https://github.com/metersphere/metersphere/assets/104960608/0e1a17d3-454f-447b-a4f0-03ec6408b341)
2.将项目的用例模板设置为刚刚修改后的模板
![image](https://github.com/metersphere/metersphere/assets/104960608/fb200587-7a8e-4d92-8483-6d4fdd345c1a)
3.测试跟踪-功能用例处，新建功能用例，发现用例步骤并不是模板设置里的文本描述
![image](https://github.com/metersphere/metersphere/assets/104960608/68cb5de4-bbca-4d8c-891f-febcce236c10)

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
