### ISSUE TITLE
[FEATURE]metersphere中的BUG提交完成，关联JIRA，却无法关联到JIRA中具体的故事点下面

### ISSUE THREAD

**Issue by FrancoFang667788** [metersphere/metersphere#24291]
### 联系方式

franco

### MeterSphere 版本

版本:   v2.9.0-426de152

### 使用外置数据库

否

### 问题描述

![image](https://user-images.githubusercontent.com/48195272/237063562-2ff93aae-cad6-4094-8462-3f1abd5c277d.png)

在meterspher中的用例下关联了对应的需求，然后在用例下提交了bug，关联到JIRA后，对应bug却无法关联到JIRA中的故事点

上上图，JIRA默认是能通过一个故事点看到下面所有的BUG，以及BUG的状态

<img width="773" alt="image" src="https://github.com/metersphere/metersphere/assets/48195272/66e3e795-128d-46a0-a36c-d2922bbef9e7">

### 重现步骤

<img width="772" alt="image" src="https://user-images.githubusercontent.com/48195272/237063133-e4927877-950d-44ab-b396-57509835d3bb.png">

### 期待的正确结果

在ms中新建用例有关联需求的选项，然后在需求下提交bug，期望：对应的bug也能关联到需求，在JIRA中就能把对应的故事点下的BUG全部展示出来

**Comment by luty2018** [comment]
你好， 目前jira已经进行了插件化，用户可以自行在插件中完成对第三方平台的进一步开发。
