### ISSUE TITLE
[BUG]接口导入 Swagger 文件报“解析数据出错”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24292]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.9

### 使用外置数据库

否

### 问题描述

1.接口导入 Swagger 文件报“解析数据出错”
![image](https://github.com/metersphere/metersphere/assets/103627487/220496bd-b2b6-4275-8a91-85b4fd5c0a7c)

### 重现步骤

1.接口导入 Swagger 文件（文件私发）
![image](https://github.com/metersphere/metersphere/assets/103627487/220496bd-b2b6-4275-8a91-85b4fd5c0a7c)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。
