### ISSUE TITLE
[BUG]接口测试》》前后置脚本》》语言选择python，使用log.info打印中文为乱码

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24294]
### MeterSphere 版本

2.9

### 使用外置数据库

否

### 问题描述

[BUG]接口测试》》前后置脚本》》语言选择python，使用log.info打印中文为乱码

### 重现步骤

[BUG]接口测试》》前后置脚本》》语言选择python，使用log.info打印中文为乱码

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/b311cb9c-2dd8-41ca-9494-c4ab3a42f122)

**Comment by fit2-zhao** [comment]
感谢反馈，python 中文需要转译，加个 "u" 就行
![image](https://github.com/metersphere/metersphere/assets/70558837/99f48945-63e7-4af4-a024-f5571cbe5d70)
