### ISSUE TITLE
[FEATURE] 希望条件控制器支持逻辑 或 、与等

### ISSUE THREAD

**Issue by xianwq** [metersphere/metersphere#24303]
### MeterSphere 版本

v2.7

### 联系方式

1056735572@qq.com

### 请描述您的需求或者改进建议

目前条件控制器只支持 某个变量满足某个条件，不支持多个条件

### 请描述你建议的实现方案

希望条件控制器支持逻辑表达，比如多个变量都满足条件，或者只要有一个条件满足就可以

就是多个条件的与或非

**Comment by zhangzhaox** [comment]
目前可通过生成的模板脚本轻松实现
