### ISSUE TITLE
[BUG]设计场景用例时，禁用子场景下的子场景用例仍然可以调试执行

### ISSUE THREAD

**Issue by wanhx829** [metersphere/metersphere#24306]
### 联系方式

wanhx1324@163.com

### MeterSphere 版本

 v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

关联这个问题：https://github.com/metersphere/metersphere/issues/23645

保存完成后执行调试，禁用的步骤仍然继续执行

### 重现步骤

1、创建四个场景用例：场景1，场景2，场景3，场景4
![image](https://github.com/metersphere/metersphere/assets/52766648/a2e93bba-4037-4742-8271-bebb81f5bbff)
![image](https://github.com/metersphere/metersphere/assets/52766648/316c6cf1-faac-48b9-aef3-c7b701cf6485)
![image](https://github.com/metersphere/metersphere/assets/52766648/dd72510f-6ea3-4381-9125-23f0843d8db7)
2、创建场景3用例：场景3，引用场景1，引用场景2
![image](https://github.com/metersphere/metersphere/assets/52766648/b868ead0-a0fe-49d6-96b6-064fd8e1b2ba)
3、创建场景4用例：场景4，引用场景3
![image](https://github.com/metersphere/metersphere/assets/52766648/ab8d9b39-e423-4d30-9b02-2f612ab26a9a)
4、此时编辑场景4用例时，禁用场景1，禁用场景2执行调试
![image](https://github.com/metersphere/metersphere/assets/52766648/14bbabb1-ae59-45a4-8e1e-e2652cbed0f1)
5、可以发现禁用的场景和步骤仍然执行

### 期待的正确结果

场景下引用场景，引用n层也能正常使用（不仅可以保存，也可以应用到调试执行）

**Comment by youliyuan-fit2cloud** [comment]
非常感谢您的反馈，下个版本会修复该问题。

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
