### ISSUE TITLE
[FEATURE]企业微信机器人和邮件推送的信息不够多，且有用

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24304]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

目前的的webhook推送的信息不够全面，你无法在推送的信息里获取到足够的内容
原因：群里是有多工种组成的，只有测试才会点开查看，比如产品经理，项目经理，开发等，他们只是需要知道一个结果就行了，而且无论结果失败还是成功，都要收到这份推送的消息
建议改成：
比如说我今天跑了3500个测试用例，其中3400个通过，110个不通过
测试环境：XXXXX 
测试计划：XXXX
接口测试，运行1700个测试用例，1670个通过，30个不通过
场景测试，运行1700个测试用例，1670个通过，30个不通过
压力测试，运行100个测试用例，50个通过，50个不通过
链接：XXXXXXXX

**Comment by Hyyfit** [comment]
测试计划的消息通知模版里是有这样的字段，支持用户自行配置

<img width="630" alt="image" src="https://github.com/metersphere/metersphere/assets/95834771/0aeed234-1d05-42d5-8bbf-242a6cf81576">

**Comment by YellCatt** [comment]
> 测试计划的消息通知模版里是有这样的字段，支持用户自行配置
> 
> <img alt="image" width="630" src="https://user-images.githubusercontent.com/95834771/237890227-0aeed234-1d05-42d5-8bbf-242a6cf81576.png">

好吧，如果能改下默认就好了，毕竟默认的真的不太行

**Comment by luty2018** [comment]
模板我们优化一下。
