### ISSUE TITLE
[QUESTION]long term版本中对安全问题IDOR漏洞修复计划

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#24301]
### 请描述您的问题

请问这个安全问题，需要修复吗？如果需要，修复计划是怎样的？
https://github.com/metersphere/metersphere/security/advisories/GHSA-j5cq-cpw2-gp2q

感谢

**Comment by fit2-zhao** [comment]
已经修复过了，请升级到 >=v1.20.21 版本就可以。

**Comment by xchnshi** [comment]
好的，感谢
