### ISSUE TITLE
MeterSphere 使用中调整了侧边栏展示的宽度后，再点击具体模块，侧边栏宽度又恢复到了原来的宽度

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#24300]
### 联系方式

14707070227

### MeterSphere 版本

 v2.9.0-426de152

### 使用外置数据库

否

### 问题描述

MeterSphere 使用中由于模块较多，需要调整侧边栏的宽度，但是调整了侧边栏展示的宽度后，再次点击具体模块，侧边栏宽度又恢复到了原来的宽度。

### 重现步骤

1. 调整了侧边栏展示的宽度；
2. 再次点击具体模块，侧边栏宽度又恢复到了原来的宽度。

### 期待的正确结果

希望侧边栏调整宽度后，再次点击具体模块，侧边栏宽度保持之前调整好的宽度，而不是系统设置定义好的宽度。

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/b4853eee-6405-47b9-8971-732ee079cd20)
![image](https://github.com/metersphere/metersphere/assets/50016789/c9ff0dca-8a90-4b65-b3ae-5a3189036b7a)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本尽量优化一下哈。

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
