### ISSUE TITLE
[BUG]测试跟踪>>功能用例>>在备注里添加图片，保存后，想再添加附件，发现添加【附件】按钮不显示了

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24309]
### MeterSphere 版本

2.9

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>功能用例>>在备注里添加图片，保存后，想再添加附件，发现添加【附件】按钮不显示了

### 重现步骤

[BUG]测试跟踪>>功能用例>>在备注里添加图片，保存后，想再添加附件，发现添加【附件】按钮不显示了

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/2cb93aff-e23c-495f-bc0a-c7910efaeeaf)

![image](https://github.com/metersphere/metersphere/assets/78218624/24601797-7247-4b12-8f52-205dc49ef863)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本未复现，请升级到最新v2.9.1版本。

**Comment by huangxine** [comment]
升级尝试后，在2.9.1版本没有这个问题了
