### ISSUE TITLE
压力测试中配置的响应是3s 但是看测试结果还有响应时间是 超过3s的但是错误率是0的[BUG]

### ISSUE THREAD

**Issue by tiancaijunrui** [metersphere/metersphere#24312]
### MeterSphere 版本

2.7.0

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/16681429/b1d42bd1-583f-4766-a637-3f0cd6bdfeed)
![image](https://github.com/metersphere/metersphere/assets/16681429/7b52b1a6-4453-49f5-afd5-11736df95c4d)
![image](https://github.com/metersphere/metersphere/assets/16681429/defc946b-c93d-459b-a405-3a9a375ee014)

### 重现步骤

见上图

### 期待的正确结果

两个展示效果可以保持一致

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题。

**Comment by liuruibin** [comment]
您好，我们在jmeter的使用实践中发现这个超时时间的配置不是100%可靠的。jmeter推荐我们使用断言来处理这种情况
<img width="864" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/0ac11a0c-a292-485d-939b-a8244616a0ad">
