### ISSUE TITLE
[QUESTION]场景变量中的列表型变量如何引用整个列表？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#24315]
### 请描述您的问题

如果对于接口的返回结果，需要提取列表中的元素的属性值在某个列表中的元素，本来是：

`$.result[?(@.attribute in ${list})]`

但是这个${list}，当设置了一个场景变量list，类型为列表，提取不到任何值，因为${list}为空。所以如果这种情况，列表型变量怎么引用这个列表？或者场景变量应该怎么弄？

**Comment by fit2-zhao** [comment]
场景列表变量会生成和JMeter自定义变量一致 pre_index 方式，配合ForEach使用，如果单个获取需要带上索引取值，比如list_0，list_1 等，而表达式 $.result[?(@.attribute in ${list})] 是 JSON Path 表达式，用于从 JSON 数据中筛选出具有特定属性值的元素。

**Comment by fit2-zhao** [comment]
场景列表变量会生成和JMeter自定义变量一致 pre_index 方式，配合ForEach使用，如果单个获取需要带上索引取值，比如list_0，list_1 等。
而表达式： “$.result[?(@.attribute in ${list})]” 是 JSON Path 表达式，用于从 JSON 数据中筛选出具有特定属性值的元素。
