### ISSUE TITLE
[BUG]接口自动化场景列表树状菜单报错

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#24317]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

进入接口自动化菜单，选择一个树状菜单下的场景打开进入编辑， 切回场景列表，再次选择其它树状菜单时无任何反映，js报错

### 重现步骤

进入接口自动化菜单，选择一个树状菜单下的场景打开进入编辑， 切回场景列表，再次选择其它树状菜单时无任何反映，js报错

### 期待的正确结果

能够切回列表继续选择其它菜单下的场景并打开

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/40912823/5ab632c9-75a6-46a2-b7b2-a73d4ab82688)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
