### ISSUE TITLE
[BUG]接口导入-导入 Swagger 文件报“格式错误”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24323]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v1.20.22-lts

### 使用外置数据库

否

### 问题描述

接口导入-导入 Swagger 文件报“格式错误”，v2.9.1版本导入正常，v1.20.22版本导入报错

### 重现步骤

1. 接口导入 Swagger 文件(文件私发）
![image](https://github.com/metersphere/metersphere/assets/103627487/e5e8b662-4c0d-4b0e-906c-43d6e0bac468)

**Comment by youliyuan-fit2cloud** [comment]
v1.20.23-lts中已解决。
