### ISSUE TITLE
[BUG]【UI测试】指令里嵌套子指令，指令里再嵌套条件控制器，然后指令传参就无法正确识别

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24322]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

【UI测试】指令里嵌套子指令，子指令里有条件控制器，传参传不进来

### 重现步骤

1.【UI测试】指令里嵌套子指令，子指令里有条件控制器，传参传不进来，主要是以下这种结构
![image](https://github.com/metersphere/metersphere/assets/104960608/b53451f7-f9b0-4e9e-b622-0f5802e74c62)
![image](https://github.com/metersphere/metersphere/assets/104960608/b481098e-cedf-4e01-bf82-adc2d67c1049)
![image](https://github.com/metersphere/metersphere/assets/104960608/9d944bb8-7a76-4fb2-999f-216d67cea852)
2.运行结果如下
![image](https://github.com/metersphere/metersphere/assets/104960608/ed976301-0057-49d1-9b4a-18e28d791da6)
3.如果将条件控制器禁用了，就可以正常传参
![image](https://github.com/metersphere/metersphere/assets/104960608/e6e70914-a1fd-47a1-b567-e4bc0c4947c2)
![image](https://github.com/metersphere/metersphere/assets/104960608/d2ccdba9-ad12-4a15-9183-efa03ab789bd)
4. 脚本如下:
[Metersphere_Ui.zip](https://github.com/metersphere/metersphere/files/11441444/Metersphere_Ui.zip)

**Comment by zrfit** [comment]
您好，感谢您的反馈！v3.0统一规划。

**Comment by luty2018** [comment]
指令已经禁用了， 建议用户还是使用引用/复制场景的方式来组织场景。
