### ISSUE TITLE
[FEATURE]测试计划报告\任务中心报告\性能测试报告，case\功能\性能报告可跳转原用例

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24325]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试计划报告\任务中心报告\性能测试报告，case\功能\性能报告可跳转原用例
场景是我每天打开测试报告，之后看到错误的测试用例，之后跳转过去修改，测试报告页是要一直开着的
具体流程：打开测试报告页->发现有错误的测试用例->点击跳转此用例->程序自动新建一个tab标签，跳转到用例的编辑页面，原先的测试报告页保留着
原因：提高解决问题用例的效率，解决完毕后，一键重跑错误用例

**Comment by Hyyfit** [comment]
感谢反馈，3.0会优化
