### ISSUE TITLE
[BUG]请提供v2.9.1版本在k8s上部署的脚本，老的脚本不可用

### ISSUE THREAD

**Issue by FrancoFang667788** [metersphere/metersphere#24324]
### MeterSphere 版本

 v1.20.10-lts

### 使用外置数据库

否

### 问题描述

请提供v2.9.1版本在k8s上部署的脚本，老的脚本不可用

https://metersphere.io/docs/v2.x/installation/kubernetes_installation/ 这里的版本是老版本的部署，无法使用

### 重现步骤

请提供v2.9.1版本在k8s上部署的脚本，老的脚本不可用

https://metersphere.io/docs/v2.x/installation/kubernetes_installation/ 这里的版本是老版本的部署，无法使用

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们会修改下，请关注下文档更新。

**Comment by shenkaibo** [comment]
请问是下载的 最新的 helm-chart 安装包么？
https://github.com/metersphere/helm-chart/releases/download/metersphere-2.9.1/metersphere-2.9.1.tgz
我本地使用最新的 helm-chart 安装包 metersphere-2.9.1.tgz 用 helm install 部署是没有问题的。

**Comment by zikkinbun** [comment]
默认的values文件如果选用外部kafka，要把 kafka.bootstrap-servers={{.Values.kafka.host}}.{{.Values.kafka.namespace}}:{{.Values.kafka.port}} 改成 kafka.bootstrap-servers={{.Values.kafka.host}}:{{.Values.kafka.port}}，不然会报错，这个在官方文档上并没有提及

**Comment by shenkaibo** [comment]
> 
这个可以 单独在 configmap 里修改。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
