### ISSUE TITLE
[BUG]【UI测试】场景变量里设置json变量，在json里设置了url的值，在指令入参处引用不到

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24332]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

【UI测试】场景变量里设置json变量，在json里设置了url的值，在指令入参处引用不到

### 重现步骤

1.【UI测试】场景变量里设置json变量，在json里设置了url的值
![image](https://github.com/metersphere/metersphere/assets/104960608/31ce93a5-4bbc-4a73-acb0-31eec3293d83)
2.在指令里引用这个json里的url值，最终发现没有引用到
![image](https://github.com/metersphere/metersphere/assets/104960608/fd73e3f2-197a-446e-a7de-252f68a47d41)
![image](https://github.com/metersphere/metersphere/assets/104960608/1b18a67a-d363-47b5-aead-3e6fb47606ae)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v3.0规划。
