### ISSUE TITLE
[BUG]开启功能用例自定义ID后，切换功能用例列表页面，用例ID有时候是自定义ID，有时候是默认ID

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24334]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.9.0

### 使用外置数据库

否

### 问题描述

开启功能用例自定义ID后，切换功能用例列表页面，用例ID有时候是自定义ID，有时候是默认ID

### 重现步骤

1.开启应用设置-功能用例自定义ID
2.在用例评审和功能用例页面直接切换，同时还可以刷新页面，会出现用例ID变化的情况。具体请查看附件复现动图。

### 期待的正确结果

不变化

### 附加信息
[ID变化.zip](https://github.com/metersphere/metersphere/files/11449067/ID.zip)

_No response_

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
