### ISSUE TITLE
[BUG]测试计划中的状态错乱问题

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#24330]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

1、测试计划中计划结束时间小于当前时间，状态为非已结束的数据，状态都变成了已结束，且无法修改为已完成。
2、测试计划中计划结束时间小于当前时间，状态为已归档的数据，在筛选条件为已归档时进行查询，会都变成已结束。
3、测试计划中当时间正常超过计划结束时间时，状态自动变更为已结束。

### 重现步骤

1、历史数据，更新版本后状态都被刷了，重新更新状态页面提示成功，但刷新后其实没有成功还是结束状态
2、历史数据，默认是没有查归档数据的，当你把规定条件加进去进行查询，会把原本已归档数据都查出来但是状态会给你变成已结束。
3、测试计划中当时间正常超过计划结束时间时，刷新页面状态自动变更为已结束。

### 期待的正确结果

帮助文档中的状态定义是：
已完成：表示计划中所有的测试用例都通过了。
已结束：表示计划中执行结果有失败的，但是都执行完了。

不应靠计划结束时间强行变更状态

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，最新版本修改了这块的设计，如果测试计划设置了计划结束时间，不管测试计划是否执行完成（进行中/已完成），是否成功还是失败，一旦到了计划结束时间， 该测试计划状态会自动变更为 “已结束”。
如果这块有其他建议请随时联系我们～

**Comment by wszbc** [comment]
1、那我的归档数据也变成了已结束，应该是bug把
2、如果只按照时间就将状态改为结束逻辑感觉怪怪的，那我可以理解不能允许有延期了，只要超时就自动结束了，我觉得本质这个位置其实是要监控测试进展，那么如果用例没有执行完，强行结束就感觉状态意义不大了，如果真要强行结束感觉人为操作更为灵活，之前的逻辑执行完了一个状态 全部通过一个状态感觉挺好的，只不过结束和完成状态先后可以定义的更清晰，测试工作结束，计划完成；测试工作完成，计划结束这两个理解感觉都行，所以按照之前的描述感觉也还不错说清楚别人就知道了

**Comment by youliyuan-fit2cloud** [comment]
> 1、那我的归档数据也变成了已结束，应该是bug把 2、如果只按照时间就将状态改为结束逻辑感觉怪怪的，那我可以理解不能允许有延期了，只要超时就自动结束了，我觉得本质这个位置其实是要监控测试进展，那么如果用例没有执行完，强行结束就感觉状态意义不大了，如果真要强行结束感觉人为操作更为灵活，之前的逻辑执行完了一个状态 全部通过一个状态感觉挺好的，只不过结束和完成状态先后可以定义的更清晰，测试工作结束，计划完成；测试工作完成，计划结束这两个理解感觉都行，所以按照之前的描述感觉也还不错说清楚别人就知道了

问题1 确实是bug，下个版本会修复。
问题2 我们内部研究一下哈，请关注后续更新。

**Comment by 13290445582** [comment]
v2.10.0-lst已修复
