### ISSUE TITLE
[BUG]没有项目的情况下，去创建用例，能够正常创建成功，但是不能对该用例进行任何操作

### ISSUE THREAD

**Issue by nsc-wuqi** [metersphere/metersphere#2433]
**MeterSphere 版本**
1.8.2

**Bug 描述**
在没有项目的情况下，去创建用例，能够正常创建成功，但是不能对该用例进行任何操作。
新建一个项目后，在该项目空间下创建的用例就能正常操作，但是之前没有项目创建的用例就消失了。

**Comment by zyyfit** [comment]
您好，1.9.0版本修复了这个问题，请等最新版发布后更新试一下
