### ISSUE TITLE
[BUG]【接口定义】导入swagger文件，出现格式错误

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24337]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v1.20.22-lts

### 使用外置数据库

否

### 问题描述

【接口定义】导入swagger文件，出现格式错误

### 重现步骤

1.【接口定义】在v1.20.22版本上，导入swagger文件，出现格式错误
![image](https://github.com/metersphere/metersphere/assets/104960608/1d04d1a5-eeb2-40ad-8889-8f21462f5b4b)
2.在2.9.1版本可以正常导入
![image](https://github.com/metersphere/metersphere/assets/104960608/88887c8b-1804-4877-99ec-c1f122ad7dff)
3.swgger文件如下
[openapi.zip](https://github.com/metersphere/metersphere/files/11450019/openapi.zip)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #24323
