### ISSUE TITLE
[BUG]测试计划-场景用例全部停止报错

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#24349]
### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

![图片](https://github.com/metersphere/metersphere/assets/23067502/bd2d6122-af55-4d75-b40c-6f91ec3fd148)

### 重现步骤

测试计划-任务中心-全部停止

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.9.1未复现该问题，建议升级尝试。
