### ISSUE TITLE
[FEATURE]接口case的编辑界面的运行和保存按钮是否可以移动到固定栏上？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24344]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：接口case的编辑界面的运行和保存按钮是否可以移动到固定栏上？
原因：编辑长脚本的时候非常不方便，每次运行都要用鼠标滚轮滚到最上面才能运行，如果在跟环境配置的那栏固定栏上，会方便很多，如果能像场景用例一样能用快捷键就更好了

**Comment by Hyyfit** [comment]
感谢反馈，我们3.0会优化。
