### ISSUE TITLE
[BUG]【UI测试】指令里嵌套指令，在外层指令设置的值无法传入到子指令的步骤中

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24345]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

【UI测试】指令里嵌套指令，在外层指令设置的值无法传入到子指令的步骤中

### 重现步骤

1.【UI测试】指令里嵌套指令，子指令里有引用参数，会在子指令处显示，但是也会在外层指令显示
![image](https://github.com/metersphere/metersphere/assets/104960608/b0817764-e704-479c-a730-1f4a598dd4cf)
![image](https://github.com/metersphere/metersphere/assets/104960608/c5416eca-9314-4971-866c-a69df4ad7467)
![image](https://github.com/metersphere/metersphere/assets/104960608/d0f8a786-b0a9-4fcd-be1c-5b70bb1d0928)
2.在场景中引用指令，在最外层赋好参数值，最终值并没有传入到子指令的步骤里
![image](https://github.com/metersphere/metersphere/assets/104960608/ef9628df-50e0-48de-9d39-f3ef8e74759d)
![image](https://github.com/metersphere/metersphere/assets/104960608/3130351f-ac96-408f-92f9-c8b2d9295802)
![image](https://github.com/metersphere/metersphere/assets/104960608/4d695c82-79bb-4e38-9de0-3ffd5993198b)
3.如果指令的值无法传入到子指令里，那在指令这儿设置值毫无意义，建议指令不要显示子指令的入参变量，或者填写了也能传进去。

**Comment by zrfit** [comment]
您好，感谢您的反馈！
1、变量获取就近原则，优先取内层的入参。
2、可以直接将变量值填写到内层的入参；也可以把值填写为${url}形式，通过场景变量传递。

**Comment by 2lipan** [comment]
@zrfit 
在场景处，指令下的子指令不让填写；只能在原指令处写${ip}进行引用外层的值，可是点击保存后，页面就立马置空了呀
![be39739907e1017d57d566a31d2bc68](https://github.com/metersphere/metersphere/assets/104960608/68ba3b50-bc05-4835-9610-c829be5c0b5a)
![image](https://github.com/metersphere/metersphere/assets/104960608/2a104f2f-3b52-4a4b-ac59-216072eaa602)

**Comment by zrfit** [comment]
变量名和${}中的变量名不能同名！
