### ISSUE TITLE
[BUG]【接口自动化】当事务控制器下嵌套事务控制器，子事务控制器下嵌套自定义脚本，点击场景调试，发现自定义脚本并没有响应结果及响应内容

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24355]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

【接口自动化】当事务控制器下嵌套事务控制器，子事务控制器下嵌套自定义脚本，点击场景调试，发现自定义脚本并没有响应结果及响应内容

### 重现步骤

1.【接口自动化】当事务控制器下嵌套事务控制器，子事务控制器下嵌套自定义脚本，点击场景调试，发现自定义脚本并没有响应结果及响应内容
![image](https://github.com/metersphere/metersphere/assets/104960608/7133db40-a671-422b-b86b-ec57f7c52e66)
2.若只嵌套一层事务控制器，就能正常执行
![image](https://github.com/metersphere/metersphere/assets/104960608/b27f6e11-fcfb-4def-8b31-bae83b8ea4a7)
![image](https://github.com/metersphere/metersphere/assets/104960608/59c7cb4b-3c00-47c7-acb4-6f884033d894)
3.请求如下:
[Metersphere_Scenario_默认项目.zip](https://github.com/metersphere/metersphere/files/11459454/Metersphere_Scenario_.zip)

**Comment by wxg0103** [comment]
您好  这个不是我们平台的问题，建议可以了解一下这个事务控制器的使用逻辑
Generate parent sample：如果事务控制器下有多个取样器，勾选它，那么在“查看结果树”中我们不仅可以看到事务控制器，还可以看到每个取样器，并且事务控制器定义的事务是否成功取决于子事务是否都成功，子事务其中任何一个失败即代表整个事务失败。
你的每个事务控制器都勾选了Generate parent sample，那程序是以哪个样本作为其他样本的父项，这不符合程序逻辑，建议子事务去掉这个选项。

祝您生活愉快！
