### ISSUE TITLE
[BUG]接口测试：前后置脚本使用python动态提取响应体json的数据，此数据内容依旧为json串。但是提取后，里面的json串里都有u，造成其他接口无法正常使用。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24354]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

[BUG]接口测试：前后置脚本使用python动态提取响应体json的数据，此数据内容依旧为json串。但是提取后，里面的json串里都有u，造成其他接口无法正常使用。

原因：
1、需要从json响应体，动态提取数组信息组成业务场景，系统自带的提取，只能提取固定值或者所有数组信息。
2、使用脚本动态提取，发现提取的json结果，每个值前，都多了u，导致提取的数据无法正常使用。

### 重现步骤

[BUG]接口测试：前后置脚本使用python动态提取响应体json的数据，此数据内容依旧为json串。但是提取后，里面的json串里都有u，造成其他接口无法正常使用。
原因：
1、需要从json响应体，动态提取数组信息组成业务场景，系统自带的提取，只能提取固定值或者所有数组信息。
2、使用脚本动态提取，发现提取的json结果，每个值前，都多了u，导致提取的数据无法正常使用。

### 期待的正确结果

动态提取的json串能正常使用。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/d84198b5-81e2-40d8-84f6-cb21737e572f)
![image](https://github.com/metersphere/metersphere/assets/78218624/4dffcfe3-2f22-4bf5-848e-88d25eab08b6)
![image](https://github.com/metersphere/metersphere/assets/78218624/55f555c1-a192-45b7-b8dd-05f1596c6859)

**Comment by wxg0103** [comment]
您好  这个不是缺陷
ms平台内置的python版本是2.7
在Python中，str(res)用于将一个对象转换为字符串。如果对象是Unicode字符串，转换后的字符串会带有u前缀，表示它是一个Unicode字符串
如果想将json转字符串可以使用json.dumps() ，json.dumps() 是一个内置函数，用于将 Python 对象转换为 JSON 格式的字符串可以避免带u前缀
![image](https://github.com/metersphere/metersphere/assets/46886316/102948af-6b61-454d-bac1-1587585382d9)

**Comment by huangxine** [comment]
我是要动态随机获取json的值，目前如果这样用还是无法实现动态随机获取。比如对于查询的全国省份信息，随机动态获取省份信息。自动化场景里的参数不能写固定，都是随机动态获取的

**Comment by huangxine** [comment]
谢谢谢谢，我明白了。
