### ISSUE TITLE
[BUG]UI测试后置操作下拉框元素value断言，当元素没有value值时无法完成断言。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#24357]
### MeterSphere 版本

v1.20.20

### 使用外置数据库

否

### 问题描述

1.UI测试后置操作下拉框元素value断言，当元素没有value值时无法完成断言

### 重现步骤

1.编写UI测试脚本
2.断言选择下拉框断言，我目前想要使用下拉框断言方式来断言5条/页
![image](https://github.com/metersphere/metersphere/assets/55130444/c28d1d09-d194-4a05-815e-686cb0ff595f)
3.使用元素断言可以确定元素存在
![image](https://github.com/metersphere/metersphere/assets/55130444/b316784a-e623-453b-aa0d-6ce8a5b93f19)
![image](https://github.com/metersphere/metersphere/assets/55130444/bb50fa17-f9ef-4744-ab01-78b3470be075)
4.当使用下拉框断言时：会一直提示
![6ca7efba598878bf8a9e9fde4524f06](https://github.com/metersphere/metersphere/assets/55130444/36925a4f-06c1-4f2b-8b6d-9197a0d34ae4)

### 期待的正确结果

1.UI测试后置操作断言选择下拉框时，能够完成断言。

**Comment by xiaomeinvG** [comment]
感谢您的反馈。1.20不再修复除安全问题以外的问题。该问题在2.10未复现，建议您后续升级至2.10版本
