### ISSUE TITLE
[BUG]场景中点击复制的 api 跳转到接口定义页面，自定义字段不显示

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24358]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

场景中点击复制的 api 跳转到接口定义页面，自定义字段不显示

### 重现步骤

1. 场景中复制带有自定义模板字段的Api 
![image](https://github.com/metersphere/metersphere/assets/103627487/f872e8ff-0930-49c8-bc1a-4cf1ee6196a7)
2. 点击复制的Api 从场景中跳转到Api 编辑页面，自定义字段不显示
![image](https://github.com/metersphere/metersphere/assets/103627487/f8897956-8f27-4ffe-9924-48a80b8a4aba)
![image](https://github.com/metersphere/metersphere/assets/103627487/6a0aea31-b4c2-4ca6-972f-1758bd8c38d3)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。
