### ISSUE TITLE
[BUG]项目中用户组与权限中添加成员，搜索姓名搜索不到

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24359]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

1. 项目中用户组与权限中添加成员，搜索姓名搜索不到，搜索用户id 可以搜索到

### 重现步骤

1. 项目中用户组与权限中添加成员，搜索姓名搜索不到，搜索用户id 可以搜索到，下拉框展示的是姓名
![image](https://github.com/metersphere/metersphere/assets/103627487/54cb8948-b1e6-45b3-8c76-bc3ded42dd87)
![image](https://github.com/metersphere/metersphere/assets/103627487/c024263a-d2f1-44de-aaeb-8d97e6d02822)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。
