### ISSUE TITLE
[BUG]接口测试>>前后置脚本：在脚本里无法给项目环境中定义的列表参数赋值。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24364]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>前后置脚本：在脚本里无法给项目环境中定义的列表参数赋值。

### 重现步骤

[BUG]接口测试>>前后置脚本：在脚本里无法给项目环境中定义的列表参数赋值。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/8419117d-87f5-43b6-bddf-55637cb001b9)
![image](https://github.com/metersphere/metersphere/assets/78218624/61a3c24e-a56c-454b-b672-8009324052a9)
![image](https://github.com/metersphere/metersphere/assets/78218624/59adb766-8c69-45c0-ba3c-3e3906571bfc)

![image](https://github.com/metersphere/metersphere/assets/78218624/eae875fa-efb3-41b5-950a-a2b104729a56)
![image](https://github.com/metersphere/metersphere/assets/78218624/69dadd92-4d8b-4d4c-b193-1547fbd95ee0)

**Comment by zrfit** [comment]
您好，感谢您的反馈！脚本保存到环境变量问题计划v2.10修复，注意提取列表需要用脚本转换成字符串。
