### ISSUE TITLE
[BUG]导出场景报告，多次点击导出，导出页数增加

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24366]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

V2.9.1

### 使用外置数据库

否

### 问题描述

导出场景报告，多次点击导出，导出页数增加（导出文件查看好像是请求内容翻倍）

### 重现步骤

1. 场景报告，点击导出报告,第一次点击导出看是2页
![image](https://github.com/metersphere/metersphere/assets/103627487/bba6605d-6122-495e-a16b-d9d57d7b3056)
2.报告页不关闭，再次点击导出变成了3页，多次点击导出会一直增加
![image](https://github.com/metersphere/metersphere/assets/103627487/3dac9f0f-5a82-419a-9af8-08f1dc69fe83)

**Comment by Somebody-JIAN** [comment]
您好，我在V2.9.1版本中，使用chrome浏览器未能复现。

**Comment by meijieDouDou** [comment]
我在 qa 环境也能稳定复现，可以试个报告是多页的，不要试一页的，因为内容也会增加一倍，一页可能看不出来

**Comment by Somebody-JIAN** [comment]
是的，qa和cloud都无法复现。  
chrome版本是： 113.0.5672.92（正式版本） (arm64) 
弹出了pdf保存框之后我这里无法点击后面的导出按钮。

**Comment by Somebody-JIAN** [comment]
https://github.com/metersphere/metersphere/assets/75963100/ca03228a-5809-4300-b55e-1aefdcccdf9c

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.0-lts以上版本已修复。
