### ISSUE TITLE
[BUG]测试计划的报告分享链接用浏览器打开，报告步骤内容处于转圈并出现前端报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#24361]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

1.20.22-LTS

### 使用外置数据库

否

### 问题描述

测试计划的报告分享链接用浏览器打开，报告步骤内容处于转圈并出现前端报错

### 重现步骤

测试计划的报告分享链接用浏览器打开，报告步骤内容处于转圈并出现前端报错

### 附加信息

<img width="903" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/ab30f3df-74f5-4ddf-8af2-dc7fa2d50479">

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v1.20.23修复。
