### ISSUE TITLE
新增用例用会出现重复的数据[BUG]

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#2436]
**MeterSphere 版本**
版本: v1.8.2-d59d4b5f

**Bug 描述**
新增用例用会出现重复的数据

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
不新增用例不出现重复的用例

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/80370956/116497486-0da22880-a8da-11eb-86f1-35d1990b4c98.png)

**Comment by zyyfit** [comment]
您好，1.9.0版本修复了这个问题，请更新后再试一下
