### ISSUE TITLE
[FEATURE]有一个需求，我需要在接口case页面有一个单选框，将部分的测试用例取消全局前后置脚本

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24365]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：我需要在接口case编辑页面一个单选框，将部分的测试用例取消全局前后置脚本
原因：接口case一部分需要全局前后置脚本，方便统一维护脚本，另一方面异常的接口访问不需要全局前后置脚本，如果全局前后置脚本运行了，我这个项目每个case大概要浪费15秒的时间，主要是数据加载，token获取等等，所以有没有办法给没有需要前后置脚本的测试用例做一个标记，在测试计划中就不要运行前后置脚本了？

**Comment by luty2018** [comment]
感谢建议， 这个需求我们已经规划在v3.0了
