### ISSUE TITLE
[FEATURE] 希望LDAP 登录的用户默认绑定一个用户权限

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24371]
### MeterSphere 版本

v2.9.X

### 请描述您的需求或者改进建议

希望LADP的用户登录的时候默认添加一个指定的用户组权限，这样LADP的用户登录的时候就可以直接使用不需要再找管理用户申请相关的用户组权限了

### 请描述你建议的实现方案

方案1、在用户组权限增加一个开关（唯一默认LDAP开启时生效）
方案2、在LADP增加一个选项（唯一默认绑定的用户组权限）

**Comment by luty2018** [comment]
v2版本不会新增功能了， 这个可以在tapd提交需求。

**Comment by sss903065212** [comment]
好的TAPD已提交
