### ISSUE TITLE
自定义请求不支持跨环境运行，辛苦优先修复

### ISSUE THREAD

**Issue by chaochaozui** [metersphere/metersphere#24370]
### 联系方式

MeterSphere 交流群50的超超

### MeterSphere 版本

v2.4.0-165ceb70

### 使用外置数据库

否

### 问题描述

编写场景CASE时，使用了“自定义请求”来操作db，而这个组件一定要填写“运行环境”+“数据源”，那在切换环境比如我想不对用例做任何个性，就能在开发环境批跑用例，而一旦场景CASE中有“自定义请求”，就必须一个一个的找出来并修改“运行环境”指向开发环境，这明显有问题。

### 重现步骤

编写场景CASE使用“自定义请求”组件，运行环境和数据源名称置为空，运行该用例时指定运行环境，此时自定义请求这一步会报错“数据源为空请求选择数据源”

### 期待的正确结果

“自定义请求”组件应该支持跨环境运行，运行环境和数据源名称都是可以在项目环境中定义的，所以只要场景CASE或场景计划选择某运行环境，“自定义请求”组件也应该使用对应的环境信息+数据源信息，以便实现跨环境运行。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/133349886/6d55fa95-42dd-47a3-b119-829a654730b1)

**Comment by zrfit** [comment]
您好，感谢您的反馈！自定义请求未填写环境-勾选引用环境-则可以在场景选择的环境下执行。
<img width="909" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/11eb72fa-2ff9-46c8-9670-9839eadacf08">
