### ISSUE TITLE
[BUG]接口测试json请求体用json-schema转换后再关闭json-schema，数据内容发生了变化

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24378]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.22-lts

### 使用外置数据库

否

### 问题描述

接口测试json请求体用json-schema转换后再关闭json-schema，数据内容发生了变化

### 重现步骤

1.将以下数据粘贴在接口的请求体json中
{"isDraft":0,"params":[{"abarbeitungId":6109,"auditOpinion":"","auditStatus":1,"taskDetailId":4322637617135616},{"abarbeitungId":6110,"auditOpinion":"","auditStatus":1,"taskDetailId":4322637617135616}],"taskType":4,"userAccountId":"265338797888245761"}
![image](https://github.com/metersphere/metersphere/assets/88763608/590d0874-4b0a-48c8-9175-1e666d212248)
2.开启json-schema
3.关闭json-schema，数据内容发生了变化
![image](https://github.com/metersphere/metersphere/assets/88763608/80620ff2-bb54-465b-82b2-56621b81c54e)

### 期待的正确结果

不应该发生变化

**Comment by youliyuan-fit2cloud** [comment]
v1.20.23-lts中已解决。
