### ISSUE TITLE
批量执行接口自动化，报告全部通过不了，在单条场景跑报告显示成功，批量跑报告总有报错

### ISSUE THREAD

**Issue by arvingoing** [metersphere/metersphere#2437]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.9.0版本优化了这个问题，您升级到最新版试一下，或者排查一下是不是接口并发数过多服务器压力过大？
