### ISSUE TITLE
[FEATURE] 希望自定义代码片段添加引用功能-自定义代码片段功能 添加引用的逻辑

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24372]
### MeterSphere 版本

v2.8.X

### 请描述您的需求或者改进建议

接口定义 前置或者后置里面 可以添加自定义代码片段，但修改自定义代码片段无法自动更新接口里的自定义代码片段，希望在
<img width="1232" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/69863e54-470b-45dd-8ceb-1d364ccffc19">

**Comment by luty2018** [comment]
感谢建议， 这个我们有考虑支持，只是还没有很好的解决方案。

**Comment by sss903065212** [comment]
好的吧
