### ISSUE TITLE
[BUG]误报库的描述内容在误报库列表没有展示

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24377]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.22-lts

### 使用外置数据库

否

### 问题描述

误报库的描述内容在误报库列表没有展示

### 重现步骤

1.创建一个误报，添加描述，描述信息在误报列表没有展示出来
![image](https://github.com/metersphere/metersphere/assets/88763608/1d5f6ed3-2676-4d0a-b442-a3daeca5be06)

### 期待的正确结果

展示出来

**Comment by youliyuan-fit2cloud** [comment]
v1.20.23-lts中已解决。
