### ISSUE TITLE
[BUG]接口测试，前置脚本导入api进行https请求，报错：Tag mismatch! (javax.crypto.AEADBadTagException: Tag mismatch!)

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#24385]
### MeterSphere 版本

v1.20.18

### 使用外置数据库

否

### 问题描述

1.1.20.18版本，通过从api定义导入的方式导入一个python前置脚本，不修改脚本内容
![image](https://github.com/metersphere/metersphere/assets/55130444/fa7d61e1-7a9c-49d4-a482-a01f8213d457)
![image](https://github.com/metersphere/metersphere/assets/55130444/14468b03-666c-43d8-ac06-e1b3a6b5a567)
会报以下报错
Tag mismatch! (javax.crypto.AEADBadTagException: Tag mismatch!) in <script> at line number 10
javax.script.ScriptException

2.1.20.15版本，同样的方式导入到前置脚本中，可以正常执行。
![image](https://github.com/metersphere/metersphere/assets/55130444/c0ef48d5-43f8-49de-8f7e-367938922391)
![image](https://github.com/metersphere/metersphere/assets/55130444/2db9e197-0cb1-4841-99d6-1971f5d62398)

### 重现步骤

1.新增https接口和case
2.接口前置操作从api导入后，执行接口，控制台报错。

### 期待的正确结果

1.20.18版本也能够在前置操作中执行python的前置脚本

**Comment by youliyuan-fit2cloud** [comment]
没有复现，建议升级到最新的v1.20.22-lts版本试试。

**Comment by 13290445582** [comment]
建议升级到最新版本，如果再次出现请重新提issue，感谢理解和支持～
