### ISSUE TITLE
[FEATURE] 接口定义的消息触发事件建议增加接口状态变更为“已完成”

### ISSUE THREAD

**Issue by magicpose** [metersphere/metersphere#24396]
### MeterSphere 版本

v2.9.1-b4

### 请描述您的需求或者改进建议

一直在使用，刚升级到最新版本，提一个小需求，接口定义的消息触发事件能不能增加接口状态变更为“已完成”，这个在协作的时候非常有用
![image](https://github.com/metersphere/metersphere/assets/7636934/ef66039d-9849-4423-a61b-43d39ae9b780)

**Comment by luty2018** [comment]
您好，这个建议可以先通过调用我们的api去完成覆盖，系统目前还没有计划支持哈。

**Comment by magicpose** [comment]
> 您好，这个建议可以先通过调用我们的api去完成覆盖，系统目前还没有计划支持哈。

api去覆盖指的是2次开发吗，代价有点大
