### ISSUE TITLE
[BUG]接口定义JSON-SCHEMA里Integer类型默认传值问题

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#24397]
### 联系方式

yi.yao@fit2cloud.com

### MeterSphere 版本

1.20.20

### 使用外置数据库

否

### 问题描述

接口定义JSON-SCHEMA这里是Long类型的，识别成Integer类型了，然后传到后端默认传的是0，应该传null才正确。

![d10140fce44af353759f30889b634cd](https://github.com/metersphere/metersphere/assets/83771182/c03e9b47-a49d-43ea-9a4c-a718fec42031)

### 重现步骤

接口定义JSON-SCHEMA这里是Long类型的，识别成Integer类型了，然后传到后端默认传的是0，应该传null才正确。

**Comment by zrfit** [comment]
您好，最新版本v1.20.22未复现该问题，请升级尝试！
