### ISSUE TITLE
[BUG]接口自动化跑带runtime控制器等脚本OOM

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#24393]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.22-lts和2.9.1

### 使用外置数据库

否

### 问题描述

接口自动化跑带runtime控制器等脚本OOM

### 重现步骤

1、接口自动化导入一个带有事物和runtime控制器的脚本
2、点击执行
<img width="1475" alt="image" src="https://github.com/metersphere/metersphere/assets/72729206/288b80c7-a479-41a7-ada7-b57ee7178e09">

3、1）lts版本从docker stats可以看出内存越来越高，ms-server服务到4.5G时会OOM
      2）v2.9.1版本使用资源池，ms-node-controller服务会OOM
![image](https://github.com/metersphere/metersphere/assets/72729206/96a886e1-d4b1-4e80-b91b-0de08b49cc37)
4、调整jvm参数没有效果，内存的大小取决于脚本中runtime的时间，时间越长，内存会一直增长
5、jmeter测试是可以正常结束
![Uploading image.png…]()
6、脚本如下
[场景JMX文件集 (1).zip](https://github.com/metersphere/metersphere/files/11477001/JMX.1.zip)

### 期待的正确结果

可以正常执行，不OOM

### 附加信息
dump分析
<img width="1475" alt="image" src="https://github.com/metersphere/metersphere/assets/72729206/cc791917-3925-4a53-a85f-79e6b11f3824">

_No response_

**Comment by fit2-zhao** [comment]
感谢反馈，目前平台只支持一个线程组，如果有多个也会生成不同场景最终放到一个线程组中执行，脚本中分析发现 如果都合并到一个线程组执行是有问题的，建议调整下脚本，用一个线程组调试好再导入平台。
