### ISSUE TITLE
[FEATURE]【接口测试】-接口复制-希望把接口下的Mock和case一起复制过来

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24406]
### MeterSphere 版本

v2.9.1

### 联系方式

82973834@qq.com

### 请描述您的需求或者改进建议

我们目前版本接口的复制，只复制了接口的数据，未将接口下的case和mock一起复制过来，希望将该功能优化下，复制时能加接口下的case和mock一起复制过来

**Comment by luty2018** [comment]
接口复制不是高频操作，复制接口后也会要改一些参数，这里复制case和mock没有意义
