### ISSUE TITLE
[BUG] MS平台导出的swagger-json格式文件缺少响应体信息详细内容

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24402]
### 联系方式

群14-亲山留水

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

MS平台导出的swagger-json格式文件缺少响应体详细内容，导致转换成word本地文档后缺少响应体详细内容

### 重现步骤

MS平台导出的swagger-json格式文件缺少响应体详细内容，导致转换成word本地文档后缺少响应体详细内容

### 期待的正确结果

![image](https://github.com/metersphere/metersphere/assets/82088551/bd0948cf-1573-4e6b-907e-9554572b7ca7)
响应体或请求体以json请求文本示例展示

**Comment by zrfit** [comment]
您好，感谢您的反馈！响应内容设置状态码了吗？需要设置状态码，才能导出响应体。

**Comment by zhangzhaox** [comment]
![image](https://github.com/metersphere/metersphere/assets/82088551/e9ef16ef-8ea9-452b-95a3-38abc9b42183)
![image](https://github.com/metersphere/metersphere/assets/82088551/dbff4103-1ebe-4f80-94a9-5cea55b83f92)

**Comment by zrfit** [comment]
您好，最新版本v2.9.1未复现该问题，请升级尝试。

<img width="1402" alt="image" src="https://github.com/metersphere/metersphere/assets/75963100/ac0271cd-d4eb-464d-b36a-419d2a84dac5">
