### ISSUE TITLE
[FEATURE]【接口自动化】-新增模块复制功能-可以复制该模块下的所的层级和接口

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24407]
### MeterSphere 版本

v2.9.1

### 联系方式

82973834@qq.com

### 请描述您的需求或者改进建议

新增模块复制功能-可以复制该模块下的所的层级和接口

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/b720f5f5-ca62-418d-a279-a793dfc95e0b)

**Comment by luty2018** [comment]
未开启UIR可重复时，路径是唯一的，模块复制无法通过保存校验。

**Comment by Larson13** [comment]
罗老师，这个是自动化场景的复制，不是接口定义的api复制，不需要开户url可重复，客户是想在模块上新增一个复制功能，能复制该模块下的所有场景
