### ISSUE TITLE
UI上，会出现按钮上移，排版凌乱的局面，影响用户使用体验

### ISSUE THREAD

**Issue by arvingoing** [metersphere/metersphere#2441]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.9.0版本已发布，请升级到最新版再看一下，还有问题的话请说明一下具体是哪个页面或者附上截图
