### ISSUE TITLE
[BUG]自动化测试场景中嵌套循环控制器

### ISSUE THREAD

**Issue by xianwq** [metersphere/metersphere#24410]
### 联系方式

1056735572@qq.com

### MeterSphere 版本

v2.7

### 使用外置数据库

是

### 问题描述

首先添加一个场景变量，csv格式的；
然后场景中添加一个循环控制器，控制器下面有一个http请求控制器，这个控制器读取csv的变量${name};
然后这个循环控制器下面再加一个循环控制器，内层的这个循环控制器下面再套一个http请求控制器，这个控制器也是读取csv的变量${name}; 
以上相当于两层循环控制器，我们想要的效果是，外层循环读取第一行csv数据，然后内层循环也读取第一行；就是如果外层循环读取第n行数据，那么内存循环也是读取第n行数据；
目前的效果是，内存循环会从第二行开始读取，然后第三行等等；

### 重现步骤

在本地jmeter中实验发现，如果CSV数据集只在第一层循环控制器下面，那么内层的循环控制器会跟随外层的循环控制器；
如果csv数据集在第一层循环控制器下面，并且也在第二层循环控制器下面的话，那么内存就会从第二行开始读取；

所以我们是不是应该只把csv的数据集放在最外层的循环控制器下面就好了；

**Comment by zrfit** [comment]
您好，感谢您的反馈！该问题为已知问题，同https://github.com/metersphere/metersphere/issues/21970，计划在v3.0进行规划。
