### ISSUE TITLE
[BUG]UI测试使用批量执行，鼠标点击步骤会出现无法点击的情况

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24422]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.8.1

### 使用外置数据库

否

### 问题描述

背景：客户生产环境是1.20.20-lts，已有1000+写好的用例，需要主线版本批量执行的功能。所以准备了一台8c32g的机器给我验证主线版本。
部署过程：在测试环境部署了1.20.20-lts，将生产环境备份的数据库导入测试环境，然后再将测试环境升级到2.8.1
问题：在2.8.1挑选了一些单独执行一定能成功的用例，使用批量执行并行就会报错。
批量执行报错的步骤随机不固定，报错类型分为这几种：
Expected condition failed: waiting for presence of element located By.xpath 
Element click intercepted
Element not interactable
<img width="450" alt="c7d5d5176409ff47fed52c88e440779" src="https://github.com/metersphere/metersphere/assets/88763608/dc89d839-40a8-4a13-878d-80aaee77b743">

### 重现步骤

客户环境可以出现，本地未复现，尝试过以下排查方式，暂未找到原因：
1.批量执行选择串行，这样是成功的。
2.增加前后置等待时间，最多增加到40多秒，也会报错。从vnc观察后端浏览器执行过程能看到页面比较卡顿，但是页面还是能加载出来的。
3.使用单独部署在额外机器上的grid去执行，也有同样问题。
4.allinone部署的2.8.1，将其他服务容器全部停止掉，只保留UI模块，也有同样问题。
5.使用性能模式批量并行执行也会出现这个问题。
6.观察grid中浏览器运行情况，除了页面卡顿，没有发现其他异常，页面没有发现遮挡物或加载不全。

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，研发远程跟进排除下。
