### ISSUE TITLE
[FEATURE]断言中的json文件格式校验 默认生成验证正则表达，而不是value=

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24425]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：断言中的json文件格式校验 默认生成验证正则表达式，而不是value=
场景：大于50个字段的json都不可能去下面修改成正则验证，最好是在导入的时候就直接是正则

**Comment by luty2018** [comment]
您好，能提供具体的测试用例吗

**Comment by YellCatt** [comment]
> 您好，能提供具体的测试用例吗

没法提供啊，怎么提供啊？我有个测试用例，返回字段有25000个呢

**Comment by luty2018** [comment]
> > 您好，能提供具体的测试用例吗
> 
> 没法提供啊，怎么提供啊？我有个测试用例，返回字段有25000个呢

那麻烦你把需求描述清楚，两句话get不到你的意思。

**Comment by YellCatt** [comment]
> > > 您好，能提供具体的测试用例吗
> > 
> > 
> > 没法提供啊，怎么提供啊？我有个测试用例，返回字段有25000个呢
> 
> 那麻烦你把需求描述清楚，两句话get不到你的意思。

就是那么多的字段返回，在导入的时候直接修改完成是最好的手段，不能靠下面一个个去点击修改成正则匹配啊

**Comment by YellCatt** [comment]
> > > 您好，能提供具体的测试用例吗
> > 
> > 
> > 没法提供啊，怎么提供啊？我有个测试用例，返回字段有25000个呢
> 
> 那麻烦你把需求描述清楚，两句话get不到你的意思。

还有就是用正则表达式匹配判断是兼容value=，但是value=是不兼容正则表达式匹配的

**Comment by luty2018** [comment]
理解了， 但是我们不会这么去做， 导入的数据我们第一原则是还原数据， 不会对用户的数据去进行正则加工， 先不说转成正则时可能出错，这也不是通用需求。
