### ISSUE TITLE
[BUG]【性能测试】压测过程中出现错误时，将其最低点和最高点用曲线连起来展示有误

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24435]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.8.0

### 使用外置数据库

否

### 问题描述

【性能测试】压测过程中出现错误时，当勾选所有错误，各种错误都各自成一条曲线，给人感觉是这个错误在这个区间内不断增长，这个曲线实际是最低点和最高点这两个时刻才报的错，这个区间并没有一直在报错，建议报错以点的形式进行展示，不要用线连起来。

### 重现步骤

【性能测试】压测过程中出现错误时，当勾选所有错误，各种错误都各自成一条曲线，给人感觉是这个错误在这个区间内不断增长，这个曲线实际是最低点和最高点这两个时刻才报的错，这个区间并没有一直在报错，建议报错以点的形式进行展示，不要用线连起来。
![1684309075623](https://github.com/metersphere/metersphere/assets/104960608/ec9b9a8d-d229-4aaf-a64d-300cf6311ace)

![1684309199787](https://github.com/metersphere/metersphere/assets/104960608/d59c46fe-a45b-4660-8f97-dddb361b0710)

**Comment by liuruibin** [comment]
您好，统计图表并不都是每个时刻都有值的，如果某个时刻为空表示这个时刻这个指标并不存在。图表会自动连成一条线，这样图看起来更直观

**Comment by 2lipan** [comment]
建议像JMeter原始图形一样，使用折线图，这样可以清晰看到哪几个时间段有报错，当前使用曲线连接，还得一个个鼠标放上去才知道哪些时间段有点出现，不直观。
![6d790143979e0db01b43a92d4c74152](https://github.com/metersphere/metersphere/assets/104960608/28d05f0c-fe4d-4b1c-ab48-b3e7e94581c5)
