### ISSUE TITLE
[BUG]从工作台进行查看我创建的缺陷时，部分缺陷字段内容没显示

### ISSUE THREAD

**Issue by heyuehua** [metersphere/metersphere#24436]
### 联系方式

2295335045@qq.com

### MeterSphere 版本

v2.9.0

### 使用外置数据库

否

### 问题描述

创建好的缺陷，在缺陷管理页面上进入查看的时候，缺陷字段内容显示正常，但是从工作台-我创建的缺陷进入查看缺陷的时候，部分缺陷字段内容不显示

### 重现步骤

1、缺陷管理里创建缺陷，字段显示正常
2、工作台-我创建的-缺陷管理
3、点击缺陷进入查看缺陷内容，发现部分字段内容不显示

### 期待的正确结果

从工作台进入查看缺陷时，内容正常显示

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45786766/e17bb57b-5d15-4ada-9364-a0fe6f3b368d)
![image](https://github.com/metersphere/metersphere/assets/45786766/a35f081b-0e3f-4c76-b9f9-4250f1d27587)
![image](https://github.com/metersphere/metersphere/assets/45786766/f3a010c2-287e-4a8d-8a2b-43da1962c4db)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10.1修复。
