### ISSUE TITLE
[FEATURE]脑图格式写测试用例可以将标记 “用例” 和优先级如 “P1”设置为默认值

### ISSUE THREAD

**Issue by ke-liang** [metersphere/metersphere#24438]
### MeterSphere 版本

v2.8.1

### 联系方式

ke-liang

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/15868713/6a538c8b-b88b-488d-97c1-3e161a75b8d8)

### 请描述你建议的实现方案

我们是使用脑图格式书写测试用例的，在模块的下一级别创建测试用例，但每一条测试用例都要手动添加标记 “用例” 和优先级如 “P1”，希望这两个可以添加为默认值；另外希望测试用例页面可以自动保存，不需要每次都手动点击保存；还有就是希望删除整个用例时添加二次确认功能，谢谢！

**Comment by luty2018** [comment]
您好，脑图除了能设计用例外，也支持用户添加临时节点的， 比如测试大纲等。所以这里不适合自动添加用例和等级标签。
自动保存我们暂时不会做，因为考虑存在多人协作的场景。
删除已添加二次确认， 可以升级版本到2.9.1使用。
