### ISSUE TITLE
[BUG]性能测试测试场景下载执行文件 jmx脚本中的查看结果树（仅错误日志选型未默认勾选）

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24446]
### 联系方式

群14-亲山留水

### MeterSphere 版本

V2.8.1

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/82088551/b1ea3c99-3a1a-4afd-8562-2ce0b735fcb9)
![image](https://github.com/metersphere/metersphere/assets/82088551/86c1e3d0-2212-414c-b97b-2e8b1c98075d)
性能测试测试场景下载执行文件 jmx脚本中的查看结果树（仅错误日志选型未默认勾选）
以前版本 是默认勾选的，无论上传的原始脚本是否勾选

### 重现步骤

执行压测场景
下载执行文件查看jmx脚本

### 期待的正确结果

无论上传的原始脚本是否勾选，执行场景下载的压测执行脚本文件中的查看结果树（仅错误日志的选项）是默认勾选的，

**Comment by liuruibin** [comment]
您好，我刚刚自己测试发现上传脚本的配置和下载zip是保持一致的。我们没有专门针对这个配置做修改，尽管如此性能测试中不推荐脚本中包含任何形式的Listener，这会拖慢执行。
