### ISSUE TITLE
[FEATURE]希望在测试用例模板中添加自定义字段，能在Mysql数据库的test_plan_test_case库表中读取到这个字段的信息

### ISSUE THREAD

**Issue by suchaonan** [metersphere/metersphere#24448]
### MeterSphere 版本

v2.6.1-2e5b7801

### 联系方式

su15275529968@163.com

### 请描述您的需求或者改进建议

在测试用例模板中添加自定义字段（比如：执行方式），希望能在MeterSphere的Mysql数据库的test_plan_test_case库表中读取到这个字段的信息

**Comment by luty2018** [comment]
你好， 自定义字段不是维护在这个表的， 请问具体是希望解决什么问题？
