### ISSUE TITLE
[BUG] 【测试跟踪】-功能用例-责任人如果纯数据帐号，进入编辑页面，责任人显示为空

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24447]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

功能用例的责任人如果纯数据帐号，进入编辑页面，责任人显示为空

### 重现步骤

1.创建一个纯数字帐号
2.进入测试跟踪模块-功能用例模块
3.创建一个功能用例，责任人选择刚创建的纯数字帐号，并保存
4.编辑刚创建一个用例
5.观察责任人是否能正常显示

### 期待的正确结果

1.责任人是纯数字的话，进入编辑页面能正常显示出来

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/1cd0741a-7c0e-4d3f-b980-f5cb1476522c)

![image](https://github.com/metersphere/metersphere/assets/45531073/5da04e15-192d-4a5e-9b87-5f7f11934962)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10.2-lts修复。
