### ISSUE TITLE
[BUG]【接口定义】api设置mock-将该接口删除，该接口mock还能使用

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24457]
### 联系方式

82973834@qq.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

api设置mock-将该接口删除，该接口mock还能使用，

### 重现步骤

1.在api中创建一个mock
2.然后将该api删除掉
3.在平台调用mock，观察mock是否能调通

### 期待的正确结果

将api删除，api在回收站列表中，api状态为废弃，该api的mock应该要改为关闭状态，从回收站列表中恢复到接口列表中，mock的状态改为开启

**Comment by zrfit** [comment]
您好，感谢您的反馈！api编辑页面未关闭，删除api后仍可在未关闭api的tab页面进行操作，保证用户可以继续调试和编辑api。
