### ISSUE TITLE
[BUG]测试跟踪中的测试报告无法删除

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#24456]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

测试跟踪中的测试报告无法删除

### 重现步骤

选择测试报告点击删除，提示sql错误

### 期待的正确结果

能够正常删除

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/40912823/0984e845-d443-4859-98e7-98836e962ce0)
![image](https://github.com/metersphere/metersphere/assets/40912823/cb0cb447-3e67-498a-9dbd-ccee5fa347e1)

**Comment by zrfit** [comment]
您好，感谢您的反馈！删除是成功的，但是后端日志报错，计划v2.10修复。

**Comment by wszbc** [comment]
> 

我这删除也没成功捏，刷新后那条记录还在

**Comment by wszbc** [comment]
> 您好，感谢您的反馈！删除是成功的，但是后端日志报错，计划v2.10修复。

我这删除也没成功捏，刷新后那条记录还在
