### ISSUE TITLE
[BUG]jenkins集成，验证账号时提示验证“MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败”

### ISSUE THREAD

**Issue by hychff** [metersphere/metersphere#24453]
### 联系方式

gameboyh9@163.com

### MeterSphere 版本

v2.7.0-34d44a5e

### 使用外置数据库

否

### 问题描述

和jenkins集成，使用的jenkins版本号为：metersphere-jenkins-plugin-v2.7.0.hpi，登录jenkins验证账号，提示验证“MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败”
MeterSphere API Endpoint：http://192.168.101.40:8081
MeterSphere API AccessKey：nvV9rKXKRqNhGbYp
MeterSphere API SecretKey：Dx120kBZakS7hLZN

### 重现步骤

和jenkins集成，使用的jenkins版本号为：metersphere-jenkins-plugin-v2.7.0.hpi，登录jenkins验证账号，提示验证“MeterSphere帐号失败！java.lang.RuntimeException: HttpClient查询失败,HttpClient查询失败”

**Comment by youliyuan-fit2cloud** [comment]
你好，请上传后台错误日志，方便定位问题，谢谢。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
