### ISSUE TITLE
[BUG]性能测试报告详情打开报错，浏览器崩溃

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#24454]
### MeterSphere 版本

 v1.20.17-lts

### 使用外置数据库

否

### 问题描述

性能测试报告详情打开报错，浏览器崩溃，压测时间短的报告可以打开，这份打不开的报告压测时间3分钟，100并发。

### 重现步骤

1、100并发持续3分钟压测
2、压测结束后打开报告详情

实际结果：
打开报告详情报错，浏览器崩溃

### 期待的正确结果

报告详情能正常打开

### 附加信息

![报告加载](https://github.com/metersphere/metersphere/assets/5198427/1e7d586f-ca5a-4b25-854f-873a48784421)
![报告加载2](https://github.com/metersphere/metersphere/assets/5198427/30318f82-59e4-4818-b07d-477c198336ea)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请问是否必现？当时网络环境是否正常？

**Comment by xieqione** [comment]
我这边必现，网络环境是正常的，有的报告可以打开，这份报告打开就崩溃，怀疑是请求的下载文件很多的时候就会出现

**Comment by youliyuan-fit2cloud** [comment]
你好，该性能测试用例的聚合时间配置是多少？如果时间很短，例如1s/3s，然后执行时间很长的话有可能会导致这个问题。建议长时间测试不要设置太短。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
