### ISSUE TITLE
[FEATURE]测试计划中的功能测试用例列表  右侧操作，需要添加前置条件，用例步骤，预期结果这三个字段

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24451]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试计划中的功能测试用例列表  右侧操作，需要添加前置条件，用例步骤，预期结果这三个字段
场景：在列表进行测试，而非详情页中
原因：tapd提供这项功能

**Comment by Hyyfit** [comment]
3.X的测试计划，用例的执行是以抽屉的方式展示，左侧展示用例列表

**Comment by YellCatt** [comment]
> 3.X的测试计划，用例的执行是以抽屉的方式展示，左侧展示用例列表

拭目以待~
