### ISSUE TITLE
[BUG]场景修改csv 文件后，性能里点击同步场景设置最新变更，页面csv 文件未刷新过来

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24464]
### 联系方式

meijie.wang@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

场景修改csv 文件后，性能里点击同步场景设置最新变更，页面csv 文件未刷新过来，需要手动刷新下地址栏，才刷新过来，

### 重现步骤

1. 场景创建性能测试，
![image](https://github.com/metersphere/metersphere/assets/103627487/8a687ba7-5876-4e92-b8f8-383ffbc328b1)
2.修改场景里的csv保存
![image](https://github.com/metersphere/metersphere/assets/103627487/55ab3d31-3a94-4775-a10d-6e91b25f8578)
3.点击同步场景设置最新变更
![image](https://github.com/metersphere/metersphere/assets/103627487/3b18bb87-9616-4d6f-ac4f-20cdb6af3d0c)
页面刷新后，csv文件未变化
![image](https://github.com/metersphere/metersphere/assets/103627487/d59adcea-2d9a-4ba6-bcbd-0ad185c76546)
4.刷新下地址栏，可更新
![image](https://github.com/metersphere/metersphere/assets/103627487/b72786ba-8faa-4adc-b0c8-b9569fecd23d)

### 期待的正确结果

期望 点击同步场景设置最新变更 实时刷新过来

**Comment by youliyuan-fit2cloud** [comment]
v2.10.1-lts中已修复。
