### ISSUE TITLE
[BUG] 项目成员想修改报告名称，但修改不了，原因 修改名称的权限和删除报告权限是同一个

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24462]
### MeterSphere 版本

v2.9.X

### 使用外置数据库

否

### 问题描述

项目成员有修改报告名称的权限，但修改不了，原因 修改名称的权限和删除权限是同一个
这个修改报告名称的权限 不应该跟删除报告权限合二为一吧？？？

### 重现步骤

A账号有项目成员的权限
B账号有项目管理员的权限

A无法 修改报告名称
B 可以修改

### 期待的正确结果

A可以修改报告名称

**Comment by youliyuan-fit2cloud** [comment]
v2.10.1-lts中已修复。
