### ISSUE TITLE
[FEATURE]测试计划和批量运行，运行前，软件需要对运行时间进行预判，并告知

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24468]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试计划和批量运行，运行前，软件需要对运行时间进行预判，并告知
场景：大规模运行测试用例，超过几千个用例，你需要对什么时候结束需要有一个大概的了解

**Comment by luty2018** [comment]
感谢建议， 目前我们还做不到，我们无法知道执行的资源到底是啥，耗时多少。

**Comment by YellCatt** [comment]
> 感谢建议， 目前我们还做不到，我们无法知道执行的资源到底是啥，耗时多少。

你们做的到的，每个测试用例都会运行过，你们可以统计到每次的运行时长，而不是去问执行的资源是什么
