### ISSUE TITLE
[BUG]在后置操作中提取参数用Jsonpath的函数$.length()提取数据长度，没有返回值

### ISSUE THREAD

**Issue by JoyceQ2022** [metersphere/metersphere#24460]
### 联系方式

qiao.jing.joyce@vertiv.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

在编写接口测试时，使用后置操作，自己编写脚本获取回来数据长度是5，选择提取参数，Jsonpath，用$.length()提取数据长度，执行后，显示数据提取为空。

### 重现步骤

响应体为：
[
    {
        "id": 1,
        "name": "admin",
            },
    {
        "id": 2,
        "name": "administrator",
           },
    {
        "id": 3,
        "name": "engineer",
            },
    {
        "id": 4,
        "name": "operator",
          },
    {
        "id": 5,
        "name": "browser"
         }
]
后置操作为：
![575f0436-fa1a-40d6-8048-dc3fef546767](https://github.com/metersphere/metersphere/assets/116712473/8cea8c01-439a-447e-ab11-3e8c1fedf818)

### 期待的正确结果

显示提取的数据长度5

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #20380

感谢反馈，请查看上述问题的回复～

**Comment by JoyceQ2022** [comment]
那Metersphere可以下载使用这个插件吗？断言里为什么是可以提取判断？

**Comment by youliyuan-fit2cloud** [comment]
断言这里也是后续版本支持的，提取的时候我们暂时还不支持。后续版本可能考虑内置这个插件。

**Comment by JoyceQ2022** [comment]
所以，现在意思是不支持安装这个插件，如果想在前置或后置提取，目前就只能使用脚本编写，对吗？

**Comment by youliyuan-fit2cloud** [comment]
对的，提取的组件和断言不是一个，所以还不支持。
