### ISSUE TITLE
[FEATURE] 用例模板中的自定义字段支持在测试计划中关联用例的组合查询中进行筛选

### ISSUE THREAD

**Issue by minrui321727** [metersphere/metersphere#2446]
**请描述您的需求或者改进建议.**
v1.9.0版本添加了自定义字段， 但是目前该字段木支持在组合查询中进行筛选或者查询结果中进行排序筛选

**请描述你建议的实现方案**
1. 组合查询中添加已有的自定义字段筛选条件
2. 用例列表表头支持添加自定义字段的显示并支持点击后筛选。。

**Comment by xulinde** [comment]
感谢反馈，后续版本可以优化下这里
