### ISSUE TITLE
[BUG]UI测试两个场景，同样的执行步骤，同样的元素，后端调试一个能通过一个不能通过

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#24472]
### 联系方式

张树彬

### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

偶现，但已经遇到多次，一共两种情况：
1. 两个一模一样的场景，步骤和元素也一致，其中一个场景的某些步骤执行失败，另一个场景全部执行通过；（未设置断言，不存在业务逻辑影响的问题）
   执行失败步骤报错：
   Expected condition failed: waiting for presence of element located by: By.xpath: //*[@id="taxrate1to3"]/form/div[3]/div[3] (tried for 15 second(s) with 500 milliseconds interval)
2. 两个一模一样的场景，步骤和元素也一致，其中一个场景执行不起来，点击调试后马上就会自动停止，而另一个场景能正常执行；
3. 以上两种现象基本都是先创建的场景有问题，后面重新做的场景没问题；使用本地、后端调试都会出上述情况

### 重现步骤

1. 创建场景，执行
2. 开始能正常执行，后面就不能执行了
3. 再创建一个一样的新场景，执行成功

偶发现象，不能稳定复现

### 期待的正确结果

1. 一模一样的场景，其中一个能正常执行，另一个也应该可以正常执行
2. 一模一样的场景，其他一个场景的步骤全部执行通过，另一个场景步骤也应该可以执行通过

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/77324661/b3e304d0-ff0f-41ba-9f51-4f4e34c25b7d)
![image](https://github.com/metersphere/metersphere/assets/77324661/84c39892-c76e-415c-8bba-1f9c9b6934c5)

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，该问题是必现的吗？复现场景是否可以导出？
