### ISSUE TITLE
swagger 2.0的接口文档导入格式不兼容

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#24479]
### MeterSphere 版本

v1.20.22-lts

### 使用外置数据库

否

### 问题描述

采用swagger 2.0版本的接口JSON文件导入MeterSphere 报缺少content字段，但是在1.20.19-LTS版本可正常导入
<img width="800" alt="截屏2023-05-19 下午2 58 33" src="https://github.com/metersphere/metersphere/assets/34637801/48f543ae-7714-438f-a07d-18af7fea6469">
<img width="1098" alt="截屏2023-05-19 下午2 59 35" src="https://github.com/metersphere/metersphere/assets/34637801/2a541cb2-1cc9-4ec5-b48c-1366a7cd4190">

### 重现步骤

1.部署一个1.20.22-LTS的MeterSphere环境
2.准备一个swagger2.0版本的接口的JSON文件
3.在接口测试模块的接口测试模块中导入。

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #24323
