### ISSUE TITLE
[BUG]UI测试以生成报告执行，如果步骤出错不会生成报告。

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#24482]
### 联系方式

mengqiao.shi@fit2cloud.com

### MeterSphere 版本

 v1.20.22-lts

### 使用外置数据库

否

### 问题描述

UI测试以生成报告执行，如果步骤出错不会生成报告，如果步骤没问题，报告可以正常生成。

### 重现步骤

1、创建一个UI测试用例，某个步骤的定位方式写个错误的
![image](https://github.com/metersphere/metersphere/assets/104493699/9fe9a3e9-4c37-4e98-a580-27a7a8ce91d1)
2、以生成报告的方式执行
![image](https://github.com/metersphere/metersphere/assets/104493699/4f7e2af1-c540-4743-b0d1-b9c1350fa7a1)

**Comment by zrfit** [comment]
您好，感谢您的反馈！最新版本v2.9.1不存在该问题，建议升级尝试。
