### ISSUE TITLE
[BUG]测试跟踪>>测试计划>>功能测试列表： 1、在功能列表，想把测试用例移出计划，但是在列表操作复选框选中，要非常细心才能保证点中呢，只要稍微偏一点，就进行了页面跳转，再返回发现之前的工作都前功尽弃了。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24493]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪>>测试计划>>功能测试列表：
1、在功能列表，想把测试用例移出计划，但是在列表操作复选框选中，要非常细心才能保证点中呢，只要稍微偏一点，就进行了页面跳转，再返回发现之前的工作都前功尽弃了。
2、一个计划里我们有上千条的用例，好不容易选择要移出的，就因为没有点准，进行了页面跳转，今天早上被这个整崩溃了都。

### 重现步骤

[BUG]测试跟踪>>测试计划>>功能测试列表：
1、在功能列表，想把测试用例移出计划，但是在列表操作复选框选中，要非常细心才能保证点中呢，只要稍微偏一点，就进行了页面跳转，再返回发现之前的工作都前功尽弃了。
2、一个计划里我们有上千条的用例，好不容易选择要移出的，就因为没有点准，进行了页面跳转，今天早上被这个整崩溃了都。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/292c2e51-61fa-44b7-8aa7-a4bd3360fc37)

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
