### ISSUE TITLE
[FEATURE] 是否可以给一个选项，类似于postman 的Automatically follow redirects开关

### ISSUE THREAD

**Issue by matthewdy** [metersphere/metersphere#245]
**请描述您的需求或者改进建议.**

目前3xx的返回会自动跳转，有时候不需要自动跳转，建议和postman一样 给个这样的开关。

Automatically follow redirects
Follow HTTP 3xx responses as redirects.

**请描述你建议的实现方案**

接口调用的方法上加一个开关选项

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
