### ISSUE TITLE
[BUG]接口定义-Swagger 导入报“解析数据出错”

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24501]
### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

接口定义-Swagger 导入报“解析数据出错”

### 重现步骤

1. Swagger 文件导入报错（文件私发）
![image](https://github.com/metersphere/metersphere/assets/103627487/2b038b75-4c17-4f15-9e8b-c41357371131)
![image](https://github.com/metersphere/metersphere/assets/103627487/15052c39-f0c2-4103-bac2-effd0f74ea76)

**Comment by 13290445582** [comment]
v2.10.0-lts已修复
