### ISSUE TITLE
[FEATURE]SQL按列存储加大文字长度限制

### ISSUE THREAD

**Issue by heshaol** [metersphere/metersphere#2450]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/72126159/116516148-d2b2eb80-a8ff-11eb-9539-3fe8af0943dc.png)

**请描述你建议的实现方案**
限制长度增加到500字符

**Comment by xulinde** [comment]
感谢反馈，这个可以优化下

**Comment by xulinde** [comment]
1.9.2已优化
