### ISSUE TITLE
[BUG]使用离线安装包，执行安装脚本，运行到第160行遇到错误

### ISSUE THREAD

**Issue by eryajf** [metersphere/metersphere#24509]
### 联系方式

eryajf@163.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

使用离线安装包，执行安装脚本，运行到第160行遇到错误：

```sh
install.sh: line 160: syntax error near unexpected token `>'
install.sh: line 160: `exec > >(tee -a ${__current_dir}/install.log) 2>&1'
```

现在我通过把这行内容注释，让脚本顺利运行。

### 重现步骤

应该执行安装就会遇到

**Comment by youliyuan-fit2cloud** [comment]
你好，安装命令是否是bash  或者  ./install.sh 方式？ 其他方式安装不行。

**Comment by eryajf** [comment]
了解了，我是 sh install.sh 执行的
应该改用 bash install.sh
