### ISSUE TITLE
[FEATURE]建议开源版增加用户可设置UI测试模块隐藏或显示

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#24502]
### MeterSphere 版本

V2.9.0

### 联系方式

357861578@qq.com

### 请描述您的需求或者改进建议

开源版显示UI测试菜单，每次点击显示“UI自动化为企业版功能....” 对于不需要使用此模块的用户最好不要看到此菜单，建议增加用户自定义设置，来控制UI测试菜单是否显示

**Comment by luty2018** [comment]
可以的
<img width="1467" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/6c407499-ad7d-40bb-a9ed-6e6ec592a282">

**Comment by heavenlyye** [comment]
非常感谢
