### ISSUE TITLE
[BUG]用例评审过程中，关联用例再取消导致用例评审状态错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#24508]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

1.20.22-LTS

### 使用外置数据库

否

### 问题描述

用例评审过程中，关联用例再取消导致用例评审状态错误

### 重现步骤

1、用例评审过程中，先关联两个用例
2、全部评审通过，用例评审状态是“已完成”
3、再关联两个用例，通过一个，取消关联一个，再查看用例评审状态，发现还是进行中

### 期待的正确结果

状态能够正确变化

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v1.20.23-lts修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.23-lts中已解决。
