### ISSUE TITLE
[FEATURE]希望通知到飞书群中的测试计划，接口定义能直接附上超链接点进去

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#24503]
### MeterSphere 版本

v2.8.0-ac76fee1

### 联系方式

3095500370@qq.com

### 请描述您的需求或者改进建议

1. 在通知到飞书内的测试计划和接口定义能附上超链接
2. 接口定义后能复制单接口的超链接
3. 飞书测试报告通知详细到时间，，总用例条数，通过，失败，错误，跳过，耗时等信息，避免点进去才能看到详情

**Comment by luty2018** [comment]
你好，免登录跳转以及模板配置是企业版功能哈， 你可以在官网先试用看看是否满足需求。
