### ISSUE TITLE
[FEATURE]相同项目的环境组的创建

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24513]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：相同项目的环境组的创建
场景：一个项目里有多个环境，需要同时跑一些测试用例，但是目前程序禁止了一个项目里创建一个项目组

**Comment by luty2018** [comment]
请详细描述你的需求，环境组是在工作空间创建的，并没有限制一个项目一个，是一个环境组下面一个项目一个环境。谢谢

**Comment by YellCatt** [comment]
> 请详细描述你的需求，谢谢

一个测试用例需要在两套以上的环境跑过才能算作通用，现在环境组只能是不同项目中创建，我想一个项目中也能创建环境组，去跑一个测试计划

**Comment by luty2018** [comment]
你的这个需求目前有多种覆盖方式：
一个测试计划：可以在测试计划添加两次这条用例， 再分别指定不同的环境去跑。
多个测试计划：A环境一个B环境一个
环境组是提供给跨项目的场景使用， 和你理解的不一样哦。

**Comment by YellCatt** [comment]
> 你的这个需求目前有多种覆盖方式： 一个测试计划：可以在测试计划添加两次这条用例， 再分别指定不同的环境去跑。 多个测试计划：A环境一个B环境一个 环境组是提供给跨项目的场景使用， 和你理解的不一样哦。

好的，谢了

**Comment by wws-test** [comment]
一个测试计划：可以在测试计划添加两次这条用例， 再分别指定不同的环境去跑。

那测试计划怎么设置两种环境 除了预先设值  如果是API调用怎么去设置多个环境
