### ISSUE TITLE
[FEATURE]测试计划和批量运行，运行前，软件需要对运行时间进行预判，并告知

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24526]
### MeterSphere 版本

2.8.1

### 请描述您的需求或者改进建议

需求：测试计划和批量运行，运行前，软件需要对运行时间进行预判，并告知
场景：大规模运行测试用例，超过几千个用例，你需要对什么时候结束需要有一个大概的了解

### 请描述你建议的实现方案

每个测试用例都会运行过，你们可以统计到每次测试case的运行时长，而不是去问执行的资源是什么，只要加在一起，就可以得出总时长，也可以得到大概运行到几点结束

**Comment by luty2018** [comment]
不好意思，我们没有计划支持这个。
