### ISSUE TITLE
[BUG]接口自动化测试，进入创建新的场景，然后切换到场景列表页面进行搜索，此时搜索功能无效。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#24530]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

接口自动化测试，进入创建新的场景，然后切换到场景列表页面进行搜索，此时搜索功能无效。如果不创建新场景，搜索功能正常。
![image](https://github.com/metersphere/metersphere/assets/83771182/b5a8f818-4866-4b29-97e4-3fd9b8812bc0)

### 重现步骤

接口自动化测试，进入创建新的场景，然后切换到场景列表页面进行搜索，此时搜索功能无效。如果不创建新场景，搜索功能正常。

**Comment by luty2018** [comment]
你好， 没有复现， 或者已经在最新版本修复， 可以本周四升级v2.10重试
