### ISSUE TITLE
[BUG]场景目录无法切换

### ISSUE THREAD

**Issue by linzi7669** [metersphere/metersphere#24536]
### 联系方式

290741639@qq.com

### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

是

### 问题描述

在各场景目录之间点击切换，右侧场景无法随着左侧目录切换而切换，每次需要刷新网页才能正常切换
vue.runtime.esm.js:6  TypeError: Cannot read properties of undefined (reading 'status')

### 重现步骤

1.接口自动化场景目录下打开任意一个场景
2.点击左上角场景列表返回
3.在各场景目录之间点击切换，右侧场景无法随着左侧目录切换而切换
vue.runtime.esm.js:6  TypeError: Cannot read properties of undefined (reading 'status')

**Comment by luty2018** [comment]
感谢反馈， 已转开发跟进。

**Comment by linzi7669** [comment]
升级到2.10版本后，这个缺陷没有出现了。
