### ISSUE TITLE
[BUG]接口测试>>前后置脚本给变量赋值后，在参数里无法正常引用这个变量的值。无论选择python和beanshell结果都是一样的。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24549]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>前后置脚本给变量赋值后，在参数里无法正常引用这个变量的值。无论选择python和beanshell结果都是一样的。

1、先用vars.get取得变量值，处理完成后，
2、再用vars.put赋值给变量A
3、在请求体里使用变量A
4、执行，请求体里得到的信息为${A},

### 重现步骤

[BUG]接口测试>>前后置脚本给变量赋值后，在参数里无法正常引用这个变量的值。无论选择python和beanshell结果都是一样的。
1、先用vars.get取得变量值，处理完成后，
2、再用vars.put赋值给变量A
3、在请求体里使用变量A
4、执行，请求体里得到的信息为${A},

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/60a5d44b-6b0f-4b8b-827a-3ecccd3525d8)
![image](https://github.com/metersphere/metersphere/assets/78218624/00eb2d09-064c-4224-9bc5-9580b03bc86b)
![image](https://github.com/metersphere/metersphere/assets/78218624/9b723060-29c8-4774-a5a2-8052f7da2f5d)
![image](https://github.com/metersphere/metersphere/assets/78218624/ec0b79bd-3639-4e57-bc4d-b0d8f0d6da63)

**Comment by zrfit** [comment]
您好，感谢您的反馈！metersphere后端调用的jmeter，用jmeter验证暂时也无法获取过程变量为${}的值。
