### ISSUE TITLE
[BUG] 场景查看场景用例变更历史为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24552]
### 联系方式

18311441708

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

场景查看场景用例变更历史为空
![image](https://github.com/metersphere/metersphere/assets/103925124/6fe3a6c0-8a9c-4545-b1ee-8222c486955c)

### 重现步骤

1、进行修改复制的API接口名称后查看变更历史为空
2、增加和修改APIquery参数/json参数名后，变更历史为空
3、进行API步骤的删除/添加之后，变更历史为空
![image](https://github.com/metersphere/metersphere/assets/103925124/6fe3a6c0-8a9c-4545-b1ee-8222c486955c)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.3-lts修复。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
