### ISSUE TITLE
[BUG]同一个接口，不同版本，选择【新建】不同版本的接口，在弹出的【复制信息到新版本】窗口中，选中所有项。然后在打开【依赖关系图】生成的依赖图中，同一个接口不同版本直接是间接依赖，对这个结果感觉困惑。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24550]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

[BUG]同一个接口，不同版本，选择【新建】不同版本的接口，在弹出的【复制信息到新版本】窗口中，选中所有项。然后在打开【依赖关系图】生成的依赖图中，同一个接口不同版本直接是间接依赖，对这个结果感觉困惑。
1、是bug还是设计的逻辑就这样？
2、如果是设计逻辑是这样，那也有问题，因为：当接口里没有设置前后置依赖，选择【新建】不同版本的接口，操作同上，打开依赖图里，并没有依赖图，所以看不到新版本和老版本接口直接有间接依赖关系。

### 重现步骤

[BUG]同一个接口，不同版本，选择【新建】不同版本的接口，在弹出的【复制信息到新版本】窗口中，选中所有项。然后在打开【依赖关系图】生成的依赖图中，同一个接口不同版本直接是间接依赖，对这个结果感觉困惑。
1、是bug还是设计的逻辑就这样？
2、如果是设计逻辑是这样，那也有问题，因为：当接口里没有设置前后置依赖，选择【新建】不同版本的接口，操作同上，打开依赖图里，并没有依赖图，所以看不到新版本和老版本接口直接有间接依赖关系。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/96fd2565-74c9-4989-aaa9-83a197f230de)
![image](https://github.com/metersphere/metersphere/assets/78218624/46bd5e15-614e-437b-a2a6-b5bea1795798)

**Comment by 13290445582** [comment]
已转产品跟进
