### ISSUE TITLE
[FEATURE]功能用例查询显示时可以添加一个是否显示子目录用例

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#24559]
### MeterSphere 版本

2.9.1

### 请描述您的需求或者改进建议

功能用例查询显示时添加一个是否显示子目录用例

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/40912823/37062c93-f82d-4196-b0df-4b99beb57054)
阿里云效中是这样设计的，只想看某个层级的用例的时候更方便，有时候模块名比较长无法快速对模块名进行区分

**Comment by luty2018** [comment]
好的， 感谢建议， 我们优化一下。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
