### ISSUE TITLE
[QUESTION]执行自动化接口时卡顿很久才会执行，求助

### ISSUE THREAD

**Issue by 535103680** [metersphere/metersphere#24553]
### 请描述您的问题

之前使用一直是没有问题的，但是今天突然开始执行自动化接口点击开始后 要很长一段时间才开始执行接口，求帮忙解决一下

**Comment by 535103680** [comment]
其他操作都很正常

**Comment by luty2018** [comment]
你是什么版本， 有升级过吗

**Comment by 535103680** [comment]
&nbsp;v1.20.18-lts-b2




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] [QUESTION]执行自动化接口时卡顿很久才会执行，求助 (Issue #24553)





 
你是什么版本， 有升级过吗

**Comment by 535103680** [comment]
没有升级过版本

**Comment by luty2018** [comment]
如果没有升级过版本， 建议你重启试试

**Comment by 535103680** [comment]
重启试过了，还是一样不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] [QUESTION]执行自动化接口时卡顿很久才会执行，求助 (Issue #24553)





 
如果没有升级过版本， 建议你重启试试

**Comment by luty2018** [comment]
被测系统有做什么调整吗， 你这个看起来不是metersphere的问题。

**Comment by 535103680** [comment]
找到问题了，是我们与服务器网络问题，谢谢你，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 中午11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] [QUESTION]执行自动化接口时卡顿很久才会执行，求助 (Issue #24553)





 
被测系统有做什么调整吗， 你这个看起来不是metersphere的问题。
