### ISSUE TITLE
[BUG]修改测试计划的计划结束时间为当前时间之前，修改计划状态刷新后恢复原始状态

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24561]
### 联系方式

18311441708

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

修改测试计划的计划结束时间为当前时间之前，修改计划状态刷新后恢复原始状态

### 重现步骤

1、修改测试计划的计划结束时间为当前时间之前
![image](https://github.com/metersphere/metersphere/assets/103925124/aea9df61-1400-486e-a237-e95ca54915f5)
此时测试计划的状态自动变为已结束
![image](https://github.com/metersphere/metersphere/assets/103925124/8f914a8a-4114-46e2-b050-4955c81e0cba)
2、在计划列表或者详情修改测试计划的状态
![image](https://github.com/metersphere/metersphere/assets/103925124/2aee1dcd-7212-453c-8a92-4a5ad9a0e69c)
刷新后恢复原始状态
![image](https://github.com/metersphere/metersphere/assets/103925124/8f433128-f31e-491e-94fe-58529f2cc806)
**如果没有第一步，修改计划状态很顺利，进行2操作后，修改状态失败，产品有涉及规范在这边，但是么有进行不能修改提示，
用户以为有缺陷哈**

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.1-lts修复

**Comment by Somebody-JIAN** [comment]
测试计划的计划结束时间到了之后，就会把测试计划改为已结束状态。 产品设计如此。
