### ISSUE TITLE
[FEATURE]有无计划在接口测试中增加数据结构模块，类似于apifox

### ISSUE THREAD

**Issue by sunzqe** [metersphere/metersphere#24575]
### MeterSphere 版本

v2.9.1-32da5112

### 联系方式

32310786@qq.com

### 请描述您的需求或者改进建议

有无计划在接口测试中增加数据结构模块，类似于apifox，可以根据提交的数据结构模块自动生成一些mock的数据
![image](https://github.com/metersphere/metersphere/assets/20399909/f6bf21c0-7982-4267-a2ef-c03c4646159b)

**Comment by luty2018** [comment]
这个会在v3.0讨论规划
