### ISSUE TITLE
[BUG] 新建用例步骤信息里的文本描述和步骤描述的介绍写反了

### ISSUE THREAD

**Issue by minrui321727** [metersphere/metersphere#2458]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.0

**Bug 描述**
简要描述您碰到的问题
用例步骤信息中的步骤描述和文本描述的街十号写反了，

**Bug 重现步骤**
1.  点击某一条用例
2. 点击步骤信息中的[更改类型]
3.  查看介绍文本

**期待的正确结果**
正确情况下应该是什么样的？
- 步骤描述：适用于需要每一个步骤进行测试的场景，有明确的测试步骤、预期结果
- 文本描述：使用于简单的测试场景，没有明确的测试步骤

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/9495643/116525247-e7e14780-a90a-11eb-949b-9ec5b057b204.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本优化下

**Comment by xulinde** [comment]
1.9.2已修复
