### ISSUE TITLE
[FEATURE]希望能对swagger文档中的枚举值做解析到api定义的枚举值中

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#24582]
### MeterSphere 版本

v2.8.0-ac76fee1

### 联系方式

3095500370@qq.com

### 请描述您的需求或者改进建议

希望能对swagger文档中的枚举值做解析到api定义的枚举值中

**Comment by luty2018** [comment]
感谢建议， 我们调研看看。

**Comment by youliyuan-fit2cloud** [comment]
v3.1中已支持。
