### ISSUE TITLE
docker-compose-mysql.yml配置

### ISSUE THREAD

**Issue by kikyoqiang** [metersphere/metersphere#24589]
### MeterSphere 版本

v2.9.1-b4

### 请描述您的需求或者改进建议

docker-compose-mysql.yml 中
    ports:
      - 3307:3306
 3307是写死的

没有用到 install.conf中的
## 数据库端口
MS_MYSQL_PORT=3306

所以改变这个MS_MYSQL_PORT，并不会改变docker暴露端口
造成了误导

SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true ********
通过容器名访问，还是用到了MS_MYSQL_PORT 这样会出现连不上的情况

建议：
mysql docker暴露端口 和 其它容器访问mysql端口区分

**Comment by liuruibin** [comment]
您好，这里确实有问题。建议您先手动修改yml，我们会在后续版本中修改这里
