### ISSUE TITLE
[FEATURE] 附件上传服务器后，在场景用例中使用附件，希望能在控制台中打印该文件的 MS平台路径

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24594]
### MeterSphere 版本

v2.9.1

### 联系方式

群14-亲山留水

### 请描述您的需求或者改进建议

附件上传服务器后，在场景用例中使用附件，希望能在控制台中打印该文件的 MS平台路劲
（目前仅使用新上传的附件，第一次引用用例时控制会输出ms平台中的附件路径，不是每次都输出，导致不方便）
![image](https://github.com/metersphere/metersphere/assets/82088551/95db9bc9-d0c3-496f-8a73-85519e8c0f99)

在有些用例中需要写入文件，并读取更新后的用例，目前准确定位 附件目录信息 有一点复杂

**Comment by Somebody-JIAN** [comment]
您好。

当场景数据保存之后，用到的文件都会放在MinIO中。

我们系统内部是不建议直接将文件放在服务器上的。跳过一个统一的文件管理入口，在使用过程中可能会出现我们意料之外的安全问题。

您图中的路径也不会是一成不变的。 那个路径是我们为了优化文件的下载效率而生成的临时文件夹。如果文件有更改（在文件管理页面有更改），这个路径也是会变化的。

我们几乎没有遇见您的使用场景：文件作为参数使用，还会被修改。在我们看来这样的文件就变成了“一次性”的文件，无法做到持续使用。 

所以也希望您能详细的描述一下您的使用场景，针对您的需求，我们会讨论一个实现方法，能在不违背我们初衷的前提下实现您的使用需求

**Comment by zhangzhaox** [comment]
MinIO作为附件上传后的源头，，，，执行调试时在node节点本地同步生成对应的临时目录文件，这样的设计很好。

execl文件导入的业务场景，为了保证场景的持续运行，文件数据是存在有动态数据的，只需动态写入前面API动态生成的部分变量参数即可。
execl文件导入的业务场景======不可能每次都导入相同的文件，业务上肯定不成功。

”您图中的路径也不会是一成不变的。 那个路径是我们为了优化文件的下载效率而生成的临时文件夹。如果文件有更改（在文件管理页面有更改），这个路径也是会变化的“    不更新附件的情况下路径是不变的，即时更新附件后变了也可以接受，日志输出即可
![image](https://github.com/metersphere/metersphere/assets/82088551/27300510-aa04-4bc5-a5ef-e6bd7099acb5)
仅需控制台打印本地的附件目录，方便获取，并不是为了跳过MinIO附件管理统一入口

**Comment by Somebody-JIAN** [comment]
新上传的附件，第一次引用用例时控制会输出ms平台中的附件路径，以及在返回的控制台中输出数据，这些操作是我们使用的jmeter包处理的。

V3版本我们会认真评估一下这个功能

**Comment by zhangzhaox** [comment]
![image](https://github.com/metersphere/metersphere/assets/82088551/f63741a1-9dcd-419a-a4d6-44fdfa5d15e7)
这个附件路径对于在banshell脚本读取文件内容时是很重要的信息，望评估后尽量满足，谢谢
