### ISSUE TITLE
[BUG] 附件信息页面，删除模块信息后，附近列表看不到该附件，且不能重新上传，提示文件已存在

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24595]
### 联系方式

群14-亲山留水

### MeterSphere 版本

v2.9.1

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/82088551/31a48305-ffcd-498a-bf90-fa2bb884dcac)
附件信息页面，删除模块信息后，附近列表看不到该附件，且不能重新上传，提示文件已存在

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/82088551/53631d52-1620-436b-8155-e2ceb2e3f142)
删除该模块信息

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.1-lts修复
