### ISSUE TITLE
[QUESTION] 2.6.1版本升级至2.10-ls版本资源此无法启动

### ISSUE THREAD

**Issue by wanghongbin73** [metersphere/metersphere#24597]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/22722572/19b0a9ab-8728-4af4-aa7e-8f75b96f6986)
2.6.1版本升级至2.10-ls版本资源此无法启动

**Comment by liuruibin** [comment]
您好，我们这次进行了安全加固，如果您的资源池不是用标准安装包进行部署的话需要自行修改。

1. 部分目录需要配置权限
```
chmod 777 -R /opt/metersphere/logs
chmod 777 -R /opt/metersphere/data/body
chmod 777 -R /opt/metersphere/data/api-folder
chmod 777 -R /opt/metersphere/data/node
```

2. 修改docker-compose-node-controller.yml
    增加环境变量：RUN_AS_NON_ROOT_USER: 'true'
    覆盖 command: sh -c 'sed -i "s/:101:/:${MS_DOCKER_GID:-101}:/g" /etc/group; /deployments/run-java.sh'
    执行命令将docker gid 写入 .env文件：
    echo MS_DOCKER_GID=$(getent group docker | cut -f3 -d:) >> /opt/metersphere/.env
    修改完成后执行 msctl reload
![image](https://github.com/metersphere/metersphere/assets/23045261/753230b1-c13a-4244-966c-72c4556e5c7b)

**Comment by wanghongbin73** [comment]
可以了，谢谢
