### ISSUE TITLE
[QUESTION] Jmeter镜像无法下载

### ISSUE THREAD

**Issue by donfaquir** [metersphere/metersphere#246]
在搭建本地开发环境时，配置文件指定的`registry.fit2cloud.com/metersphere/jmeter-master:0.0.6`无法获取，有没有其他地址可下载

**Comment by wangzhen-fit2cloud** [comment]
镜像地址可以换成我们阿里云仓库的地址
registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master
