### ISSUE TITLE
[FEATURE] 在性能测试引用接口自动化场景选择接口时加入环境选择

### ISSUE THREAD

**Issue by wanghongbin73** [metersphere/metersphere#24602]
### MeterSphere 版本

v2.10.x-lts

### 联系方式

781774349@qq.com

### 请描述您的需求或者改进建议

在性能测试引用接口自动化场景选择接口时加入环境选择，方便性能测试时选择执行环境
![image](https://github.com/metersphere/metersphere/assets/22722572/737faaba-df4d-4407-8a99-53189960bf6f)

### 请描述你建议的实现方案

![image](https://github.com/metersphere/metersphere/assets/22722572/737faaba-df4d-4407-8a99-53189960bf6f)

**Comment by luty2018** [comment]
感谢建议， 性能测试目前还没有与环境打通， 我们预计会在v3.0规划这里。
