### ISSUE TITLE
[BUG]接口定时同步，选择了导入模式为覆盖且同步覆盖API模块，同步的接口依然存在多份一样的

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#24618]
### 联系方式

3095500370@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

是

### 问题描述

接口定时同步，选择了导入模式为覆盖且同步覆盖API模块，同步的接口依然存在多份一样的

### 重现步骤

1. 设置定时同步，选择了导入模式为覆盖且同步覆盖API模块
2. 查看同步的api接口，存在多份一致的

### 期待的正确结果

能覆盖一致的接口

**Comment by zrfit** [comment]
你好，感谢您的反馈！最新版本v2.10 LTS未复现该问题，建议升级到 v2.10 LTS尝试。
