### ISSUE TITLE
[FEATURE]场景调试里，多层嵌套下，勾选父级，应该子级都勾上，取消父级，自己也应该都取消

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24617]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

比如我导入一个场景
场景父级是自己的名称，下面有很多的子步骤
就是逻辑应该是上面开启，下面就自动开启，上面关闭，下面也自动关闭。如果上面开启，下面想关闭，就应该手动关闭
你勾选父级，应该子级都勾上，取消父级，自己也应该都取消

**Comment by luty2018** [comment]
步骤的启用/禁用 控制的是这个步骤是否执行，步骤含有子步骤时，也是当做一个步骤整体处理的，如果外层的启用禁用与子步骤联动， 则无法恢复初始状态。经线下沟通，保持现状。
