### ISSUE TITLE
[BUG] 删除功能用例评论，服务器上的markdown图片未删除

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24616]
### 联系方式

chunrong.yao@fit2cloud.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

否

### 问题描述

 删除功能用例评论，服务器上的markdown图片未删除

### 重现步骤

测试计划的功能用例进行评论:后进行保存
![image](https://github.com/metersphere/metersphere/assets/103925124/fc0636f8-e4b2-46be-9bf3-31c80b51ea0e)
然后进行删除评论操作，提示删除成功：
此时数据库test_case_comment表中亦无此数据
此时服务器存放目录未删除，长期使用，无用数据增多，将导致服务器数据目录内存占用过大
![image](https://github.com/metersphere/metersphere/assets/103925124/ad87bb46-c23f-4fe4-9e82-483f0492c9bd)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
