### ISSUE TITLE
[BUG]脑图写用例，经常性丢失

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#24610]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

1、使用脑图写用例
在脑图中经常修改，拖动模块及用例，用例改模块，模块改用例等一系列操作后，保存会丢失用例，非常影响使用热情 

### 重现步骤

1、使用脑图写用例，在脑图中经常修改，拖动模块及用例，用例改模块，模块改用例等一系列操作后，保存会丢失用例

**Comment by maninhill** [comment]
建议升级到 v2.10 LTS， v1.20 LTS 我们后续只进行安全相关问题的修复，望理解。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
