### ISSUE TITLE
[BUG]低版本升级至2.10LTS后，接口定时同步任务无法删除，并报错SQL ERROR

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#24611]
### MeterSphere 版本

V2.10LTS

### 使用外置数据库

否

### 问题描述

V2.9.1升级至V2.10LTS，在原版本存在接口定义同步的定时任务时，在接口测试首页、接口定义-定时同步中删除原定时任务时，删除失败并报错SQL ERROR

### 重现步骤

见问题描述

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/92150453/7e66a8e5-b89f-45c9-a5d1-982ea163d567)
![52c733b9120934b58c9b448362226d5](https://github.com/metersphere/metersphere/assets/92150453/e5ff02fd-92ed-4f06-876a-f5538f7b7ccb)

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，辛苦发下后端报错日志。

**Comment by zrfit** [comment]
您好，最新版本v2.10.2-lts未复现该问题，建议升级尝试。
