### ISSUE TITLE
[BUG]同步MS缺陷到高版本Jira丢失描述和图片信息

### ISSUE THREAD

**Issue by shaohuage** [metersphere/metersphere#24626]
### 联系方式

61100119@qq.com

### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

在MS创建缺陷输入标题、描述信息后，只同步了标题到jira（版本9.4.3）上，描述和里面的图片信息都没同步过去。

### 重现步骤

1.在自己部署的MS平台输入缺陷标题、描述（文字+图片）创建缺陷。
2.在jira上查看是否同步成功。

### 期待的正确结果

预期：同步成功，jira上的缺陷包含标题，描述，图片信息；
实际：同步失败，jira上的缺陷仅包含标题

**Comment by luty2018** [comment]
您好， 感谢反馈。
MeterSphere v2版本目前还不支持与JIRA高版本进行适配。
为了应对用户不同版本不同平台的差异化需求，我们已经将对接JIRA的功能进行了插件化。
如果您这边有开发基础可以参考插件开发文档进行对接：
https://github.com/metersphere/metersphere-platform-plugin/wiki/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97
如果您这边没有开发计划，也可以在官网或交流群联系我们的客户成功同学，由交付团队来进行对接。
