### ISSUE TITLE
[BUG]metersphere的数据库，没有表名称注释、表字段注释，数据库表字段的设计不人性化，也不规范

### ISSUE THREAD

**Issue by junwei-liu** [metersphere/metersphere#24631]
### 联系方式

1025656390@qq.com

### MeterSphere 版本

v2.10.20-lts 

### 使用外置数据库

否

### 问题描述

metersphere的数据库，没有表名称注释、表字段注释，数据库表字段的设计不人性化，也不规范，**建议补充表名称中文注释，表字段的comment注释。**

### 重现步骤

metersphere的数据库，没有表名称注释、表字段注释，数据库表字段的设计不人性化，也不规范，**建议补充表名称中文注释，表字段的comment注释。**

### 期待的正确结果

**建议补充表名称中文注释，表字段的comment注释。**

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，建议已收到～
