### ISSUE TITLE
[FEATURE]希望对性能测试能够添加断言操作

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24635]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：希望对性能测试能够添加断言操作
场景：我这边性能测试一般都在半个小时左右，确定好指标合格后，希望直接断言，以后这条性能测试就不需要人去关注了

**Comment by luty2018** [comment]
后面会支持给性能测试打标签的功能，如果不需要关注了可以打个标签。
