### ISSUE TITLE
[BUG]批量执行UI场景，生成集合报告，报告中失败状态的统计错误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#24642]
### 联系方式

张树彬

### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

批量执行3个UI场景，生成集合报告，这三个场景中都执行了登录流程，而每个场景的登录流程都有步骤执行失败，报告的失败状态统计有问题，每个场景都显示了三个场景的失败步骤，正确应该每个场景只显示自己的失败步骤。

### 重现步骤

1. 创建三个UI场景，且每个场景都引用“登录“场景
2. 批量串行这三个场景，生成集合报告
3. 引用的”登录“场景中有各别步骤执行失败
4. 查看UI测试报告-失败状态，每个场景都统计了三个场景的失败步骤

### 期待的正确结果

应该每个场景只统计该场景的失败步骤

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/77324661/937dbdc6-e3c2-4b7e-ba48-722bf0789d1e)
![image](https://github.com/metersphere/metersphere/assets/77324661/9fc847af-69ca-4c11-968f-c1e07dd1d2e9)
![image](https://github.com/metersphere/metersphere/assets/77324661/37a43cb9-f2e0-466f-8c7c-839a819d15e9)
![image](https://github.com/metersphere/metersphere/assets/77324661/2096d44f-ad6a-4f3f-9e29-da715574f434)

**Comment by zrfit** [comment]
您还，感谢您的反馈！最新版本v2.10.0-lts未复现该问题，建议升级尝试。
