### ISSUE TITLE
[BUG]接口自动化使用CSV场景变量，循环遍历时会跳行

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24644]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

接口自动化使用CSV场景变量，循环遍历时会跳行。
CSV文件内容有十几行，循环12次，循环到第五次后，又开始从头循环

### 重现步骤

1.在qa-release环境里，南区MS成功组工作空间-UItest项目中的ID为100035的接口自动化场景中能够复现
2.在循环中加了打印的步骤，循环跳行是通过打印的数据不对判断出来的
![image](https://github.com/metersphere/metersphere/assets/88763608/d80e2f2b-d921-4227-b7df-53587f64af48)
![image](https://github.com/metersphere/metersphere/assets/88763608/6dba5e3f-c59e-4fd7-8fc7-17a64e31bcbd)
![image](https://github.com/metersphere/metersphere/assets/88763608/4d54db58-bf13-4d02-8074-d9a6080988c8)

### 期待的正确结果

正确遍历

**Comment by zrfit** [comment]
您好，感谢反馈！和https://github.com/metersphere/metersphere/issues/21970属于同类问题，已提需求，计划在v3.0对csv变量获取逻辑进行优化。
