### ISSUE TITLE
[BUG] 接口标签删除后不生效

### ISSUE THREAD

**Issue by Ybump14** [metersphere/metersphere#2464]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.0-e6a9556e
**Bug 描述**
简要描述您碰到的问题
接口定义出，接口的标签无法清除
**Bug 重现步骤**
1.  进入接口定义列表，编辑接口
2. 在接口信息页面，将标签清除，点击保存

**期待的正确结果**
正确情况下应该是什么样的？

接口的标签消失

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本修复
