### ISSUE TITLE
[BUG]配置了CAS单点登录后，使用CAS登录，登录回调时，会报sql语句错误

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#24647]
### MeterSphere 版本

V2.10.x-lts

### 使用外置数据库

否

### 问题描述

用户配置了MS的CAS单点登录，配置完成后，在进行Redirect URL跳转回MS时，会报错Field 'id' doesn't have a default value的sql异常。Redirect URL的配置内容是：http://MS地址/sso/callback/cas/${authId}
MS是部署在华为云上的，版本是V2.10.x-lts。之前有做数据迁移，原本MS是在云下环境，后续数据迁移到了云上华为云。
![154b3f6887dc8f2eb9d5025ff0af16a](https://github.com/metersphere/metersphere/assets/47737772/5683b7c1-3959-4617-b967-e5f6065ee1d3)

### 重现步骤

1.配置CAS单点登录
2.使用CAS的方式进行登录
3.跳转后报错Field 'id' doesn't have a default value

### 期待的正确结果

正确结果应该是能够正常通过CAS单点登录到首页。

**Comment by blooze123** [comment]
{"success":false,"message":"\n### Error updating database.  Cause: java.sql.SQLException: Field 'id' doesn't have a default value\n### The error may exist in io/metersphere/base/mapper/UserMapper.xml\n### The error may involve io.metersphere.base.mapper.UserMapper.insertSelective-Inline\n### The error occurred while setting parameters\n### SQL: INSERT INTO user      ( email,                              `status`,                       create_time,                       update_time,                                            `source` )       values ( ?,                              ?,                       ?,                       ?,                                            ? )\n### Cause: java.sql.SQLException: Field 'id' doesn't have a default value\n; Field 'id' doesn't have a default value","data":null}

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，请确认下CAS系统中配置的single log out callback的地址是什么？

**Comment by blooze123** [comment]
![image](https://github.com/metersphere/metersphere/assets/47737772/339eb6e1-8e24-4624-99d5-fb1773523df4)
重定向地址是这个

**Comment by zrfit** [comment]
好滴，感谢！后续研发跟进后进行反馈。

**Comment by blooze123** [comment]
好的，看看能否尽快哈，可以进行远程排查。

**Comment by liuruibin** [comment]
sql 错误是新建用户没有ID字段，可能是查询用户信息没有返回

**Comment by blooze123** [comment]
那要如何解决这种情况呢？
ps:MS数据是有做过迁移，从线下环境迁移到华为云的另一套环境,不知道是否是这个影响的

**Comment by blooze123** [comment]
![image](https://github.com/metersphere/metersphere/assets/47737772/71176a34-17f3-4bfe-82a6-d2c093757b86)
![image](https://github.com/metersphere/metersphere/assets/47737772/e723ee97-60dc-497c-8563-504d1ccaeca3)
是否是因为单点登录系统，单点过来后，FormDate里面没有传id字段，导致MS在登录过来后，插入新用户的时候，找不到默认id

**Comment by liuruibin** [comment]
对接cas之后验证用户有效性会返回这样的信息，我们用username当作用户id保存的。您检查一下cas这个接口是否是如下格式
<img width="1253" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/c26c5d4a-874a-4c63-90b8-57bebe142e74">
