### ISSUE TITLE
[BUG]接口测试>>接口列表>>文档：在接口文档中，选择接口【响应体】点击“收起”或者“一键展开”时，系统提示MS无反应

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24649]
### MeterSphere 版本

2.10-lts

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口列表>>文档：在接口文档中，选择接口【响应体】点击“收起”或者“一键展开”，然后在点击【请求体】“展开”或“收起”时，系统提示MS慢无反应

备注：清理浏览器缓存也试过了，不行。只要点击“收起”或者“一键展开”，系统就卡死

### 重现步骤

[BUG]接口测试>>接口列表>>文档：在接口文档中，选择接口【响应体】点击“收起”或者“一键展开”，然后在点击【请求体】“展开”或“收起”时，系统提示MS慢无反应。

备注：清理浏览器缓存也试过了，不行。只要点击“收起”或者“一键展开”，系统就卡死

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/3c209eec-0d42-4c49-80fa-dc9e565236ac)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，是所有接口文档的一键展开都这样？还是只有这个接口 ？响应体数据很多？
ps：以后标题尽量简洁明了 ，例如这个问题的标题： 接口文档中点击接口响应体 的“一键展开”后系统无响应。
