### ISSUE TITLE
[BUG]环境配置，勾选了通用配置列表，切换环境，通用配置不切换

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24640]
### MeterSphere 版本

v2.10-lts 

### 使用外置数据库

否

### 问题描述

1. 环境配置，勾选了通用配置列表，切换环境，通用配置不切换
2. 环境配置，勾选了通用配置列表, 切换页数，无法切换
3. 清空环境名称，切换环境后，另一个环境也会提示"请输入名称"

### 重现步骤

1. 环境配置，勾选通用配置列表
![image](https://github.com/metersphere/metersphere/assets/103627487/1f44ddf5-af68-42bf-84f5-76ecdc8f032b)
切换环境，通用配置不切换
![image](https://github.com/metersphere/metersphere/assets/103627487/4021d374-9601-4b63-b237-6492b2fcd31d)
2. 环境配置，勾选了通用配置列表, 切换页数，无法切换
![image](https://github.com/metersphere/metersphere/assets/103627487/d2d729ce-94ee-4992-b86b-579ed0965428)
3. 清空环境名称，切换环境后，另一个环境也会提示"请输入名称"
![image](https://github.com/metersphere/metersphere/assets/103627487/b27ac1de-9446-4744-9778-1e4f1fd3b87c)
![image](https://github.com/metersphere/metersphere/assets/103627487/a1efbb2b-b25d-4fc2-8b7a-1650c361a7f2)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
