### ISSUE TITLE
[BUG]MeterSphere 任务通知报告，运行环境显示的环境有重复

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#24641]
### MeterSphere 版本

2.9.1

### 使用外置数据库

是

### 问题描述

MeterSphere 任务通知报告，运行环境显示的环境有重复
![image](https://github.com/metersphere/metersphere/assets/25762331/9cdc5061-dfc7-4f57-a5cf-b8339317781e)

### 重现步骤

测试跟踪-测试计划，关联接口测试case，配置定时执行，执行失败发送邮件
通知内容里收到的报告链接打开，运行环境显示的环境有重复

**Comment by 13290445582** [comment]
您好，感谢您的反馈！最新版本v2.10 LTS未复现该问题，建议升级到 v2.10 LTS尝试。

**Comment by 13290445582** [comment]
建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
