### ISSUE TITLE
[BUG] 调整用例列表的选项展示顺序，刷新页面之后会恢复到调整之前 

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24653]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

<img width="1438" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/08a394dc-573a-4c03-bb55-c6354086f7ce">

### 重现步骤

如上图

### 期待的正确结果

刷新之后能看到调整之后的展示顺序

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by sss903065212** [comment]
好滴

**Comment by 13290445582** [comment]
v2.10.2已修复
