### ISSUE TITLE
[BUG]【接口测试】同一个接口导出成MeterSphere格式和swagger格式后，再次导入系统后，swagger响应数据的展示内容不对。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24656]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【接口测试】同一个接口导出成MeterSphere格式和swagger格式后，再次导入系统后，swagger响应数据的展示内容不对。

### 重现步骤

【接口测试】同一个接口导出成MeterSphere格式和swagger格式后，再次导入系统后，swagger响应数据的展示内容不对。
metersphere格式:
![image](https://github.com/metersphere/metersphere/assets/104960608/5a44c817-64eb-47a9-9189-8c8cba0c0456)
swagger格式
![image](https://github.com/metersphere/metersphere/assets/104960608/02014e71-98b8-42be-b738-2e319d57d2fa)

文件可点击下载进行导入
[导出文件.zip](https://github.com/metersphere/metersphere/files/11590418/default.zip)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10.3-lts修复。

**Comment by zrfit** [comment]
swagger处理数组格式数据只是展示数据结构定义，而且严格要求数组内的每个元素的数据结构相同，因此在导出的时候，只会导出数组的第一个元素，当前示例文件中的data 数组里有四个元素，swagger导出时只会导出第一个。

**Comment by 2lipan** [comment]
swagger 的数组没有显示第一个，而是直接显示成 null 了。
![image](https://github.com/metersphere/metersphere/assets/104960608/9163dacc-40f7-4c5c-a1d8-5820992e0101)
