### ISSUE TITLE
[BUG] jira 缺陷模版 切换问题和需求类型后，功能用例之前关联好的JIRA不再显示

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24652]
### MeterSphere 版本

v2.10.X

### 使用外置数据库

否

### 问题描述

如图：
1、切换之前设置和效果如下
<img width="1239" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/c8f01ef5-c2a3-4768-89aa-56c7432cef26">
<img width="1193" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/b7225c88-df9f-4c14-ba69-064d5eec2176">
2、切换之前设置和效果如下
<img width="1188" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/30e59e55-7e05-4be4-8b7d-326b6ad43f44">
<img width="1356" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/22938c84-4d90-4f63-8e66-6e2b9a9a2229">

### 重现步骤

如问题描述

### 期待的正确结果

切换之后，可以展示切换之前关联的Jira缺陷

**Comment by youliyuan-fit2cloud** [comment]
你好，用例关联的需求查看的时候每次会根据需求类型获取，需求类型变了就获取不到了。
