### ISSUE TITLE
[BUG]接口测试>>接口列表>>文档：文档中的接口定义，响应体能否提供json格式的展示。目前即使在api定义中，响应体设置了json及json内容。在文档中也无法展示成json格式的

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24651]
### MeterSphere 版本

2.10-lts

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>接口列表>>文档：文档中的接口定义，响应体能否提供json格式的展示。目前即使在api定义中，响应体设置了json及json内容。在文档中也无法展示成json格式的

### 重现步骤

[BUG]接口测试>>接口列表>>文档：文档中的接口定义，响应体能否提供json格式的展示。目前即使在api定义中，响应体设置了json及json内容。在文档中也无法展示成json格式的

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/3b6f842c-dc99-4c8f-9fa9-fff8a7bae2fb)
![image](https://github.com/metersphere/metersphere/assets/78218624/93916038-6126-409d-abf9-d40a5f937965)

**Comment by 13290445582** [comment]
您好，接口列表-文档-不支持json格式查看。
