### ISSUE TITLE
[BUG]从接口自动化场景一键转到性能测试场景,性能场景执行失败，排查后发现生成的JMX文件中HTTPSampler.path 的参数自带了个斜杆

### ISSUE THREAD

**Issue by ttyj711** [metersphere/metersphere#24654]
### 联系方式

1113522755@qq.com

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

从接口自动化场景一键转到性能测试场景,性能场景执行失败，排查后发现生成的JMX文件中HTTPSampler.path 的参数自带了个斜杆

<img width="877" alt="微信图片_20230529163841" src="https://github.com/metersphere/metersphere/assets/54162007/c32efde2-9844-4b6d-abb0-9e194f8e0d06">

### 重现步骤

1.接口自动化场景 选择一个场景转化成性能测试场景
2.性能测试场景点击保存并且执行，提示Non HTTP response code: org.apache.http.client.ClientProtocolException

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，如方便导出场景发下，我们尝试复现。
