### ISSUE TITLE
[BUG] 功能字段自定义字段过长时，导出功能用例为Excel，导出成功，但自定义字段均为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24655]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

功能字段自定义字段过长时，导出功能用例为Excel，导出成功，但自定义字段均为空

### 重现步骤

如下图，**‘请求内容’**字段未文本框非输入框
![image](https://github.com/metersphere/metersphere/assets/103925124/14515ef3-8fc8-4f35-b20d-1e780e872d99)
在功能用例中，设置此**‘请求内容’**的值为很长：
用户这里用的图片的base64字符串：https://www.zhangxinxu.com/sp/base64.html
保存后，进行导出此功能用例为Excel的操作：
**_查看Excel，自定义字段的值均都空：_**
![image](https://github.com/metersphere/metersphere/assets/103925124/191edef2-18f6-4a84-a7de-771190a49583)

### 期待的正确结果

当某自定义字段导出失败时，其他自定义字段的值不受影响，可正常导出

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.2已修复
