### ISSUE TITLE
grpc 插件自动化接口测试，报错java.lang.RuntimeException: Unable to resolve service by invoking protoc: 

### ISSUE THREAD

**Issue by 710210668** [metersphere/metersphere#24661]
### 联系方式

710210668@qq.com

### MeterSphere 版本

v2.8.6

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/42403461/c7394673-fb08-4cdb-b6e7-f4aa63698245)

### 重现步骤

可以复现

**Comment by 710210668** [comment]
![image](https://github.com/metersphere/metersphere/assets/42403461/c9b0eff9-2496-4ab7-b11b-87558cb17717)

**Comment by hzhwyh0116** [comment]
根据报错信息请排查以下问题：
1、请检查下压缩包是否按照相应格式压缩（先把 protoc文件放到文件夹中，压缩文件夹进行上传）
2、请检查一下是否安装proto编译环境（详情请查看使用手册，若还存在问题请联系vx：hzh254052917）

[MeterSphere-GRPC插件使用手册.pdf](https://github.com/metersphere/metersphere/files/11596796/MeterSphere-GRPC.pdf)
