### ISSUE TITLE
[BUG]脑图字体加粗后保存，再重新进入脑图未加粗

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24664]
### MeterSphere 版本

V2.10-lts

### 使用外置数据库

否

### 问题描述

脑图字体改变加粗后保存，再重新进入脑图未加粗

### 重现步骤

1. 脑图字体改变加粗后保存，再重新进入脑图未加粗
![image](https://github.com/metersphere/metersphere/assets/103627487/6f3f27bb-77dc-47ad-bc0f-0516de3ab2b6)
![image](https://github.com/metersphere/metersphere/assets/103627487/e948b0c1-3456-43c7-b331-c5b1be907395)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
暂不支持该功能，脑图已去掉样式编辑菜单。
