### ISSUE TITLE
[BUG]最新版MS的接口自动化-场景导入-场景复制后，无法进行前后置脚本编写

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#24667]
### MeterSphere 版本

V2.10.0-lts

### 使用外置数据库

否

### 问题描述

在升级MeterSphere v2.10.0-lts之后。使用接口自动化功能，当一个场景下，复制了另一个场景。此时复制后的场景，无法进行前置操作、后置操作、断言规则的添加按钮点击。

### 重现步骤

1.创建一个场景，在左下角的+号里进行”场景导入“操作。
![image](https://github.com/metersphere/metersphere/assets/47737772/703ee7de-9af5-42e5-8949-eb9bb4b2f28c)
2.点击复制场景。
![image](https://github.com/metersphere/metersphere/assets/47737772/e4bc2b65-0c16-476e-8540-b7ab0c98d96c)
3.打开复制后的场景，选择其中一个接口，进入前置脚本，发现无法点击”添加“按钮。
![image](https://github.com/metersphere/metersphere/assets/47737772/85a3cc6e-900d-46dd-baa2-d472d01476d1)

### 期待的正确结果

复制场景后，能够正确添加前置脚本、后置脚本、断言规则。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.1-lts中已修复。

**Comment by blooze123** [comment]
好的，谢谢哈
