### ISSUE TITLE
[BUG]【测试跟踪】当测试计划里只关联了UI测试，点击执行时页面会提示“请选择资源池”，页面也没有显示出资源池

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24662]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【测试跟踪】当测试计划里只关联了UI测试，点击执行时页面会提示“请选择资源池”，页面也没有显示出资源池

### 重现步骤

【测试跟踪】当测试计划里只关联了UI测试，点击执行时页面会提示“请选择资源池”，页面也没有资源池显示，不选又不让执行
![image](https://github.com/metersphere/metersphere/assets/104960608/07d32d1d-f97f-42aa-bd9b-9afeea4e9a90)

![image](https://github.com/metersphere/metersphere/assets/104960608/933c27dc-525f-49d6-b43b-a85b80c92123)

**Comment by 13290445582** [comment]
您好，您提供的问题目前尚未复现，方便提供下复现的场景嘛？

**Comment by 13290445582** [comment]
问题已复现，已转tapd，计划于v2.10.1-lts修复
