### ISSUE TITLE
[BUG]【UI测试】指令里，前置步骤引用了场景后将其禁用，自定义步骤里还留了一步骤，点击“本地调试”，页面提示"没有开启的步骤"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24672]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】指令里，前置步骤引用了场景后将其禁用，自定义步骤里还留了打开浏览器这一步骤，点击“本地调试”，页面提示"没有开启的步骤"

### 重现步骤

【UI测试】指令里，前置步骤引用了场景后将其禁用，自定义步骤里还留了打开浏览器这一步骤，点击“本地调试”，页面提示"没有开启的步骤"
![image](https://github.com/metersphere/metersphere/assets/104960608/a8c6de80-2c55-4177-a159-899557abe021)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10.1修复。
