### ISSUE TITLE
[BUG] 场景-Xpath提取的数组使用${xxx_ALL}不生效,无法打印出来数组数据

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24679]
### MeterSphere 版本

v1.20.23、v2.10.0-lts及以下

### 使用外置数据库

否

### 问题描述

参考步骤重现，json文件无法上传，我给拷出来了，你新建一个json文件 把下面内容复制进去，然后这个导入到场景里面即可

### 重现步骤

{"projectId":"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3","version":"v2.10-c875969f","data":[{"id":"1987fe24-6904-434c-a3cf-5de0cb32cc1f","projectId":"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3","tags":"","userId":"ljqtest","apiScenarioModuleId":"8322027b-31c0-464a-8969-ab233c47e408","modulePath":"/未规划场景/未规划场景","name":"sss","level":"P0","status":"Underway","principal":"ljqtest","stepTotal":2,"schedule":null,"createTime":1685438476450,"updateTime":1685438829379,"passRate":"100%","lastResult":"SUCCESS","reportId":"6604a12f","num":100013,"originalState":null,"customNum":"100013","createUser":"ljqtest","version":3,"deleteTime":null,"deleteUserId":null,"executeTimes":8,"order":75000,"environmentType":"JSON","environmentGroupId":null,"versionId":"74465d55-1ae9-48db-8322-79f524f089ac","refId":"1987fe24-6904-434c-a3cf-5de0cb32cc1f","latest":true,"scenarioDefinition":"{\"headers\":[],\"variables\":[],\"mockEnvironment\":false,\"active\":false,\"environmentMap\":{},\"type\":\"scenario\",\"isMockEnvironment\":false,\"environmentEnable\":false,\"referenced\":\"Created\",\"enable\":true,\"name\":\"sss\",\"enableCookieShare\":false,\"hashTree\":[{\"resourceId\":\"44233bea-4eff-4a3f-9997-59070674f9ba\",\"autoRedirects\":false,\"type\":\"HTTPSamplerProxy\",\"body\":{\"valid\":false,\"xml\":false,\"binary\":[],\"kvs\":[],\"json\":false,\"kv\":false,\"type\":\"KeyValue\"},\"isMockEnvironment\":false,\"path\":\"/l/cqBFZk3I7zOw\",\"protocol\":\"HTTP\",\"enable\":true,\"followRedirects\":true,\"connectTimeout\":\"60000\",\"hashTree\":[{\"resourceId\":\"050c7e32-668d-4421-bb1b-ea09e6c857ed\",\"mockEnvironment\":false,\"active\":false,\"index\":1,\"type\":\"Extract\",\"isMockEnvironment\":false,\"xpathType\":\"html\",\"regex\":[],\"xpath\":[{\"variable\":\"title\",\"valid\":true,\"expression\":\"/html/body/div[*]/ul/li[*]/a\",\"multipleMatching\":true,\"type\":\"XPath\",\"value\":\"${title}\"}],\"enable\":true,\"name\":\"提取数组\",\"hashTree\":[],\"json\":[],\"id\":\"bb90af2c-eecf-0304-7445-7cd32b63ec0c\",\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.extract.MsExtract\"},{\"jsr223\":[],\"resourceId\":\"3bffe577-5d1f-4976-93ac-8c84a5706370\",\"mockEnvironment\":false,\"document\":{\"type\":\"JSON\",\"data\":{\"json\":[],\"include\":false,\"xmlFollowAPI\":\"false\",\"typeVerification\":false,\"xml\":[],\"jsonFollowAPI\":\"false\"},\"enable\":true},\"xpath2\":[],\"active\":false,\"index\":2,\"jsonPath\":[],\"type\":\"Assertions\",\"isMockEnvironment\":false,\"duration\":{\"valid\":false,\"type\":\"Duration\",\"value\":0,\"enable\":true},\"regex\":[],\"scenarioAss\":false,\"enable\":true,\"hashTree\":[],\"id\":\"079d4525-6153-76fc-954c-971574a215ce\",\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.assertions.MsAssertions\"}],\"id\":\"9b4e4c22-b311-f4da-af25-4cee7cf3dfee\",\"responseTimeout\":\"60000\",\"headers\":[{\"valid\":false,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"name\":\"\",\"value\":\"\",\"urlEncode\":false,\"required\":true}],\"rest\":[{\"valid\":false,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"type\":\"text\",\"contentType\":\"text/plain\",\"urlEncode\":false,\"required\":false}],\"method\":\"GET\",\"mockEnvironment\":false,\"active\":true,\"index\":1,\"url\":\"http://c.biancheng.net/view/7459.html\",\"customizeReq\":true,\"referenced\":\"Created\",\"name\":\"获取HTML表格\",\"isRefEnvironment\":false,\"arguments\":[{\"valid\":true,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"name\":\"R\",\"value\":\"L1MvMQ\",\"urlEncode\":false,\"required\":false},{\"valid\":true,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"name\":\"name\",\"type\":\"text\",\"value\":\"admin\",\"contentType\":\"text/plain\",\"urlEncode\":false,\"required\":false},{\"valid\":true,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"name\":\"password\",\"type\":\"text\",\"value\":\"meterpshere\",\"contentType\":\"text/plain\",\"urlEncode\":false,\"required\":false},{\"valid\":false,\"min\":0,\"file\":false,\"max\":0,\"enable\":true,\"type\":\"text\",\"contentType\":\"text/plain\",\"urlEncode\":false,\"required\":false}],\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy\",\"doMultipartPost\":false},{\"resourceId\":\"eb3b0729-5bef-4b07-971d-b0677ebebc88\",\"mockEnvironment\":false,\"scriptLanguage\":\"beanshell\",\"active\":false,\"index\":2,\"label\":\"SCENARIO-REF-STEP\",\"type\":\"JSR223Processor\",\"isMockEnvironment\":false,\"script\":\"\\n\\nvar ss = vars.get(\\\"title\\\");\\n\\nlog.info(\\\"asdasd--->:\\\" + ss);\\nlog.info(\\\"asdasd--->:\\\" + \\\"${title_ALL}\\\");\\nlog.info(\\\"asdasd--->:\\\" + \\\"${title_1}\\\");\\nlog.info(\\\"asdasd--->:\\\" + \\\"${title_3}\\\");\\nlog.info(\\\"asdasd--->:\\\" + \\\"${title_5}\\\");\\nlog.info(\\\"asdasd--->:\\\" + \\\"${title}\\\");\",\"jsrEnable\":true,\"enable\":true,\"name\":\"打印数据\",\"hashTree\":[{\"jsr223\":[],\"resourceId\":\"f0cd7daa-bb4c-44be-ae7a-aca582dbf7c5\",\"mockEnvironment\":false,\"document\":{\"type\":\"JSON\",\"data\":{\"json\":[],\"include\":false,\"xmlFollowAPI\":\"false\",\"typeVerification\":false,\"xml\":[],\"jsonFollowAPI\":\"false\"},\"enable\":true},\"xpath2\":[],\"active\":false,\"index\":1,\"jsonPath\":[],\"type\":\"Assertions\",\"isMockEnvironment\":false,\"duration\":{\"valid\":false,\"type\":\"Duration\",\"value\":0,\"enable\":true},\"regex\":[],\"scenarioAss\":false,\"enable\":true,\"hashTree\":[],\"id\":\"eb3392d3-a2ac-3ebd-499b-0e10ce2bb416\",\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.assertions.MsAssertions\"}],\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.processors.MsJSR223Processor\"}],\"id\":\"1987fe24-6904-434c-a3cf-5de0cb32cc1f\",\"projectId\":\"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3\",\"clazzName\":\"io.metersphere.api.dto.definition.request.MsScenario\",\"onSampleError\":true}","description":null,"environmentJson":"{}"}],"nodeTree":[{"id":"88a9141c-e1bd-4ee4-8f30-dcfd24cb5338","projectId":"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3","name":"未规划场景","parentId":null,"level":1,"createTime":1678255815277,"updateTime":1678255815277,"pos":1,"label":"未规划场景","children":[{"id":"8322027b-31c0-464a-8969-ab233c47e408","projectId":"b2452dd2-f2d2-4c59-86a1-a4a8b7acdfb3","name":"未规划场景","parentId":"88a9141c-e1bd-4ee4-8f30-dcfd24cb5338","level":2,"createTime":1685438476439,"updateTime":1685438476439,"pos":65536,"label":"未规划场景","children":null,"caseNum":1,"path":"/未规划场景/未规划场景"}],"caseNum":13,"path":"/未规划场景"}]}

### 期待的正确结果

xpath提取的数组能使用${XXX_ALL} 读取
如下：
<img width="457" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/27fda0ad-057e-4f31-a1c5-fa6ca6498126">

**Comment by youliyuan-fit2cloud** [comment]
你好，不用使用 ${title_ALL}直接打印这个数组里面所有元素。
可以参考如下beanshell脚本
int counter = 1;
while (vars.get("myVariable_" + counter) != null) {
    String data = vars.get("myVariable_" + counter);
    log.info("Extracted Data " + counter + ": " + data);
    counter++;
}

**Comment by sss903065212** [comment]
那为何jsonPath提取的数组可以使用
