### ISSUE TITLE
[BUG]【UI测试】场景引用指令，指令修改了操作对象，但场景里定位并未发生改变

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24670]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】场景引用指令，指令修改了操作对象，但场景里定位并未发生改变

### 重现步骤

1.【UI测试】指令A里设置操作对象为元素对象，在指令AA引用指令A，指令AAA引用指令AA
![image](https://github.com/metersphere/metersphere/assets/104960608/b4f31bd8-ade0-401d-8fe9-fbce3df11ffb)
![image](https://github.com/metersphere/metersphere/assets/104960608/7ce7b8a9-340b-480e-a298-1e369e674057)

2. 在场景里新建场景TEST，引用指令AAA
![image](https://github.com/metersphere/metersphere/assets/104960608/8c5af12a-de0f-4818-9b1b-a9aa2a955107)

3. 修改指令A里的操作对象为元素定位，场景TEST里引用的定位并没有发生改变，还是之前的
![image](https://github.com/metersphere/metersphere/assets/104960608/bf046bde-c52e-483d-9dfb-5c4e3c6b8bb4)
![image](https://github.com/metersphere/metersphere/assets/104960608/a94c7c40-1f63-4223-b39b-dcf11275dc20)

**Comment by zrfit** [comment]
您好，感谢您的反馈！多层嵌套的引用数据同步逻辑修改影响范围较大，计划v3.0进行规划来修复该问题。

**Comment by luty2018** [comment]
指令会禁用掉， 建议用户使用复制/引用场景来组织。
