### ISSUE TITLE
[BUG]  如果接口用例中有前后置sql，当从A项目迁移到B项目，在B项目中查看，用例关联的前后置sql环境没有发生变化，还是老得环境。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#24678]
### 联系方式

452988409@qq.com

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

如果接口用例中有前后置sql，当从A项目迁移到B项目，在B项目中查看，用例关联的前后置sql环境没有发生变化，还是老得环境。

### 重现步骤

1. 在A项目中，新建接口用例，并添加前置或后置sql。 
2. 导出接口用例。
3. 切换B项目，导入进去。查看接口用例的前后置sql，发现环境还是老得环境。

<img width="1405" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/bc727758-45dd-4005-9701-d41430019552">

<img width="1360" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/5081c77d-78a2-4ae4-97ae-199d99a2b764">

### 期待的正确结果

1. 当导入到新项目时，可以清空环境。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
