### ISSUE TITLE
[BUG]【项目设置-应用管理】工作台-启用设置，啥都没输入，直接点击开启时间设置按钮，页面会有“保存成功”的提示

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24673]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【项目设置-应用管理】工作台-启用设置，啥都没输入，直接点击开启时间设置按钮，页面会有“保存成功”的提示

### 重现步骤

【项目设置-应用管理】工作台-启用设置，啥都没输入，直接点击开启时间设置按钮，页面会有“保存成功”的提示
![image](https://github.com/metersphere/metersphere/assets/104960608/24b4dd31-804e-475d-8397-9e9cba913aaf)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.2已修复
