### ISSUE TITLE
[BUG][【UI测试】-多个场景批量执行-场景步骤会执行多次

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24687]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

多个UI场景批量执行，UI场景里的步骤会执行多次

### 重现步骤

1.进入UI自动化模块
2.选择多个场景
3.点击批量处理-批量执行
4.运行配置里选择集合报告
5.点击确定
6.查看报告

### 期待的正确结果

按原先设置的场景执行，步骤不会多次执行，并能执行通过

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/a9e72ede-915a-40b8-a128-b6dbd0449d9d)
![image](https://github.com/metersphere/metersphere/assets/45531073/0a9f35d8-0330-4bb0-bcdd-112627c58f3a)

![image](https://github.com/metersphere/metersphere/assets/45531073/88c0bc0b-8530-419a-ab91-59d99f762a79)
![image](https://github.com/metersphere/metersphere/assets/45531073/38a4122c-e046-4954-9d1a-6c2e426fbe52)

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，可私发下复现数据我们尝试复现。

**Comment by Larson13** [comment]
@zrfit qa环境【东区测试空间-勿动】-【测试工作空间】项目有场景复现
![image](https://github.com/metersphere/metersphere/assets/45531073/bb367990-dd0a-4323-8955-5a823c222fc0)

**Comment by zrfit** [comment]
感谢，计划v3优化。
