### ISSUE TITLE
[FEATURE]需求：对于关联功能的自动化测试用例，提供审核功能

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24686]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：对于关联功能的自动化测试用例，提供审核功能

场景：我们应该是以功能测试用例为中心，先审核功能测试用例，后审核自动化测试用例，将功能用例自动化

P.S. 很奇怪的想法，但是我觉得自动化测试用例部分需要审核

**Comment by luty2018** [comment]
嗯， 我们在规划自动化用例审核的功能， 用户按需开启。
