### ISSUE TITLE
[BUG]MS集成Jira，缺陷模板选择【使用jira缺陷模板】，MS读取的Jira缺陷模板中有错误：非必填项变为必填项，并且缺陷无法保存

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24685]
### MeterSphere 版本

2.10-lts

### 使用外置数据库

否

### 问题描述

[BUG]MS集成Jira，缺陷模板选择【使用jira缺陷模板】，MS读取的Jira缺陷模板中有错误：非必填项变为必填项，并且缺陷无法保存

条件及前期操作：
1、Jira自定义字段中，只定义了一个自定义字段：{开发团队}，属性为下拉单选框，全局
2、jira字段配置中，这个字段有多个配置，一个必填，其他为非必填
3、在jira创建缺陷时，有页面信息中个{开发团队}，一个必填，一个非必填

问题：
1、在MS创建缺陷时，页面也有两个{开发团队}，但是都为必填项了
2、在MS点击保存时，原本非必填项的值，传到必填项里了，提示值无效无法保存

### 重现步骤

[BUG]MS集成Jira，缺陷模板选择【使用jira缺陷模板】，MS读取的Jira缺陷模板中有错误：非必填项变为必填项，并且缺陷无法保存

条件及前期操作：
1、Jira自定义字段中，只定义了一个自定义字段：{开发团队}，属性为下拉单选框，全局
2、jira字段配置中，这个字段有多个配置，一个必填，其他为非必填
3、在jira创建缺陷时，有页面信息中个{开发团队}，一个必填，一个非必填

问题：
1、在MS创建缺陷时，页面也有两个{开发团队}，但是都为必填项了
2、在MS点击保存时，原本非必填项的值，传到必填项里了，提示值无效无法保存

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/4c0c5b1d-3192-476d-b548-40bff8f6edfd)
![image](https://github.com/metersphere/metersphere/assets/78218624/67456925-f7ea-4e31-8cb5-8cac9c826240)
![image](https://github.com/metersphere/metersphere/assets/78218624/0a072aa6-32ec-4464-a5bb-6399a042acc1)
![image](https://github.com/metersphere/metersphere/assets/78218624/c1e8e477-ba6b-4a8b-9eb4-195cb2adc818)
![image](https://github.com/metersphere/metersphere/assets/78218624/7c3701e1-e8e2-4281-9fa3-bf0577161efe)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.2-lts中已修复。
