### ISSUE TITLE
创建缺陷的通知模板里面添加了${处理人} 的变量名，实际收到的消息通知里面不是处理人的名字，而是处理人的id

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#24688]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

1. 项目设置的消息设置里面，绑定了企业微信的Webhook，创建缺陷的通知模板里面添加了${处理人} 的变量名
2. 创建缺陷，企业微信群收到了消息通知，但是通知模板里面没有出现处理人的名字，而是处理人的id

### 重现步骤

1. 项目设置的消息设置里面，绑定了企业微信的Webhook，创建缺陷的通知模板里面添加了${处理人} 的变量名
2. 创建缺陷，企业微信群收到了消息通知
3. 通知模板里面没有出现处理人的名字，而是处理人的id

### 期待的正确结果

希望收到的消息通知里面出现出现处理人的名字，而不是处理人的id

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/640c83d4-8634-429f-b071-e257910157c9)
<img width="247" alt="0696d2d39eda8ba82b2704cc1403e3f" src="https://github.com/metersphere/metersphere/assets/50016789/e0e669f3-8691-437f-b028-5bd24d4c3e9b">
<img width="322" alt="ba865e241e42322a3734a628571fd31" src="https://github.com/metersphere/metersphere/assets/50016789/5ac0ef91-6ac0-4345-ac11-9338bbf08a17">

**Comment by youliyuan-fit2cloud** [comment]
你好， 这个字段保存在数据库中是ID信息，所以提取出来也是ID，还不支持 获取到名称，感谢理解和支持～
