### ISSUE TITLE
[BUG] 场景全屏编辑后，步骤数据（响应体）框展示不全

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24682]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

场景全屏编辑后，步骤数据展示不全

### 重现步骤

场景全屏编辑后，步骤数据（响应体）框展示不全
![image](https://github.com/metersphere/metersphere/assets/103925124/1b1a22a1-c4c8-4268-a37e-bb2786ccd464)

### 期待的正确结果

看下是否需要加滚动条

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
