### ISSUE TITLE
[FEATURE]测试计划中关联的用例和用例库分开，每次测试计划用例是个锁定状态，不随着库中的用例删除而删除。

### ISSUE THREAD

**Issue by xiongxiaoqing0614** [metersphere/metersphere#24699]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

测试计划中关联的用例和用例库分开，每次测试计划用例是个锁定状态，不随着库中的用例删除而删除。

**Comment by luty2018** [comment]
目前测试计划和测试用例的关系是引用关系，防止测试用例有变更后， 在测试计划还是执行的旧版本。
