### ISSUE TITLE
[FEATURE]测试计划报告中新增缺陷等级和自定义字段统计

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24693]
### MeterSphere 版本

v2.10.1

### 请描述您的需求或者改进建议

2.10.1版本测试计划报告的测试结果只有缺陷数量和状态统计，缺陷统计有点简单，客户希望报告支持缺陷等级和自定义字段的统计

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/fb775a8c-e1fd-43be-8c0e-2ca6510d5fc3)
![image](https://github.com/metersphere/metersphere/assets/45531073/a3894c3a-647c-422c-9886-5d9e7190b8f4)

**Comment by luty2018** [comment]
v2 不支持， 可以在tapd提交需求。
