### ISSUE TITLE
[BUG] 【测试跟踪】-测试计划报告缺陷状态统计不准确

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24692]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

测试计划报告缺陷状态统计不准确

### 重现步骤

1.创建一个测试计划
2.关联功能测试用例
3.点击执行测试用例
4.测试用例不通过提缺陷
5.查看测试计划报告缺陷统计

### 期待的正确结果

测试计划报告缺陷状态统计准确

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/68e5a34c-5744-48d8-8185-af7ea03fdc00)

![image](https://github.com/metersphere/metersphere/assets/45531073/413ecced-eb46-4ce2-9411-5e395797821c)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.2-lts修复。

**Comment by Larson13** [comment]
@zrfit 2.10.2  版本仍然有这个问题
![image](https://github.com/metersphere/metersphere/assets/45531073/1a2d744e-0cff-4981-835c-97fe84c8cf0b)
![image](https://github.com/metersphere/metersphere/assets/45531073/7ade38b4-b628-4da3-92fb-3c4a50a2ea48)

**Comment by maninhill** [comment]
不知要改多少遍，才能把数据统计正确？

**Comment by youliyuan-fit2cloud** [comment]
> 不知要改多少遍，才能把数据统计正确？

该用户的版本不是 v2.10.2 。。。。
