### ISSUE TITLE
[BUG] 测试计划导出报告报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24697]
### MeterSphere 版本

v2.10-lts 

### 使用外置数据库

否

### 问题描述

测试计划40多用例，或更多的时候，测试计划报告导出报错

### 重现步骤

1. 执行测试计划，导出报告
![image](https://github.com/metersphere/metersphere/assets/103627487/d33641cd-287d-4bdf-9350-82c4c1fcce55)
![image](https://github.com/metersphere/metersphere/assets/103627487/8899cfd1-5456-42f1-b4ba-413efb927f14)
![image](https://github.com/metersphere/metersphere/assets/103627487/c6288f7a-37ac-4730-8d0d-b12885090a23)

**Comment by 13290445582** [comment]
您好，测试场景方便提供下吗？测试环境未复现该问题

**Comment by meijieDouDou** [comment]
场景多添加点试试

**Comment by 13290445582** [comment]
好的，已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复。
