### ISSUE TITLE
[BUG]场景加载环境报错，无法调试

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24694]
### MeterSphere 版本

v2.10-lts

### 使用外置数据库

否

### 问题描述

场景加载环境报错，无法调试

### 重现步骤

1. 导入场景文件（文件私发）
2. 点击调试，或者运行环境，查看错误
![image](https://github.com/metersphere/metersphere/assets/103627487/fafd88d7-4574-41a8-ba5f-2f8592575d9c)
![image](https://github.com/metersphere/metersphere/assets/103627487/15a0e15e-6103-4df3-86bc-3a57218f7f61)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该场景数据可能比较特殊，后续版本优化一下。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.1-lts中已修复。
