### ISSUE TITLE
[BUG]原指令里提取两个参数后，在原指令处显示类型为storeTitle和storeText，在另外一个指令里引用该指令后，后端调试一下后，类型就都变成false了

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24696]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】原指令里提取两个参数后，在原指令处显示类型为storeTitle和storeText，在另外一个指令里引用该指令后，后端调试一下后，类型就都变成false了

### 重现步骤

【UI测试】原指令里提取两个参数后，在原指令处显示类型为storeTitle和storeText，在另外一个指令里引用该指令后，后端调试一下后，类型就都变成false了
![image](https://github.com/metersphere/metersphere/assets/104960608/0a5af92f-2c3b-4455-a1a6-13bfa45c8b44)
![image](https://github.com/metersphere/metersphere/assets/104960608/7e8b8d94-32a0-404b-9971-dca69231597d)

**Comment by zrfit** [comment]
您好，感谢您的反馈！计划v2.10.1修复。
