### ISSUE TITLE
[FEATURE]操作日志增加高级搜索

### ISSUE THREAD

**Issue by xiongxiaoqing0614** [metersphere/metersphere#24707]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

操作日志增加高级搜索，比如可根据标题搜索

**Comment by luty2018** [comment]
好的， 感谢建议， 这个可以加。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
