### ISSUE TITLE
[BUG]以追加的方式复制了一个新的缺陷模板，该模板内的字段名称错误

### ISSUE THREAD

**Issue by tygk** [metersphere/metersphere#24703]
### 联系方式

1026526269@qq.com

### MeterSphere 版本

v2.10.0-lts-b4

### 使用外置数据库

是

### 问题描述

模板管理中以追加的方式复制了一个新的缺陷模板，进入该新的缺陷模板后，字段名称显示错误。原默认字段名称为“优先级”，新模板的字段名称为“优先级_copy5d6bb64c”，新模板的字段名称应该和原模板保持一致才对。

### 重现步骤

模板管理中以追加的方式复制了一个新的缺陷模板，进入该新的缺陷模板，查看字段名称

### 附加信息

![f821b1498715a12c40f669c5fd353b2](https://github.com/metersphere/metersphere/assets/53895033/6f2f7b01-cc95-45a8-a03b-c8dddc3c31c5)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
同一项目下追加的话, 由于字段存在, 字段名重复所以会添加后缀来区分，非问题。

**Comment by tygk** [comment]
同一个项目下多个模板间共用同一个字段是正常的需求吧，如果复制一个模板就多一个字段，而且这个字段还是带_xxxx后缀的，这种字段根本没法用的

**Comment by 13290445582** [comment]
您好，当初主要是为了跨项目复制模板做的这个功能，建议如果同一项目下，可以新增一个模版，把相同的字段加进去。
