### ISSUE TITLE
[BUG]场景中事务控制器下请求报错，但是事务控制器显示成功

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24702]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

场景中事务控制器下请求报错，但是事务控制器显示成功

### 重现步骤

1. 场景中添加事务控制器，事务控制器下有错误请求，但是事务控制器显示成功（偶发的）
![image](https://github.com/metersphere/metersphere/assets/103627487/db2c8938-41f6-4469-b3ad-b1bed02be4a9)
2. 场景中有事务控制器的时候，场景调试请求好像是按照步骤统计的
![image](https://github.com/metersphere/metersphere/assets/103627487/42888f9a-9b7a-4451-8550-1a4c925d1437)
场景生成报告是按照请求统计的，是不是场景调试的时候也需要按照请求统计
![image](https://github.com/metersphere/metersphere/assets/103627487/85a6c039-b68c-4e58-afb7-b56cbe8f003c)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
