### ISSUE TITLE
[BUG]集成禅道记录bug，添加禅道对应字段，添加禅道状态字段时，无法记录缺陷，错误提示content为null，删除掉该字段就可以进行缺陷记录，禅道的其他字段可以，状态这个字段不行。

### ISSUE THREAD

**Issue by Merlity** [metersphere/metersphere#24706]
### 联系方式

623427175@qq.com

### MeterSphere 版本

v2.6.0-068f4f4a

### 使用外置数据库

否

### 问题描述

集成禅道记录bug，添加禅道对应字段，添加禅道状态字段时，无法记录缺陷，错误提示content为null，删除掉该字段就可以进行缺陷记录，禅道的其他字段可以添加，就是状态这个字段不行。
<img width="1247" alt="image" src="https://github.com/metersphere/metersphere/assets/25683261/f061c9c3-ec2b-4317-af6f-545daa0d74e2">
<img width="1210" alt="image" src="https://github.com/metersphere/metersphere/assets/25683261/036d3718-019c-4157-b9ab-61a570fdd63f">

### 重现步骤

1、编辑缺陷模版里面的禅道模版，添加缺陷字段；
2、保存，创建缺陷，提示错误；

**Comment by Merlity** [comment]
<img width="1256" alt="image" src="https://github.com/metersphere/metersphere/assets/25683261/07aa22cb-f5db-479b-99ae-fb331117ff7f">
相关模版字段

**Comment by 13290445582** [comment]
您好，感谢您的反馈，该问题在最新环境未复现，建议升级至最新环境尝试。

**Comment by 13290445582** [comment]
该问题在最新版本未复现。建议升级到最新版本并且下载最新的禅道插件，如果后续有问题请重新提issue，感谢理解和支持～
