### ISSUE TITLE
[FEATURE]建议优化下标签的间距问题，减少....的使用，对名称增加换行

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24701]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：建议优化下标签的间距问题，减少....的使用，对名称增加换行
场景：很多时候我们的测试用例都是有前缀的，类似电影命名法，之后重要的内容看不见，有些地方名称就显示两三个字符，看到的测试用例都是一个名称，比如像用例等级这种，真的不需要给那么大的间距

**Comment by luty2018** [comment]
我们是有固定最小宽度的，用例名你调整宽度以后也是会保存记录的。标签这里会优化。
