### ISSUE TITLE
[BUG] 使用Jenkins插件触发自动化测试用例，用例始终处于running状态

### ISSUE THREAD

**Issue by chjtester** [metersphere/metersphere#24716]
### 联系方式

交流群59：悠悠我心

### MeterSphere 版本

2.10

### 使用外置数据库

否

### 问题描述

使用Jenkins插件触发自动化测试用例（用例内仅有一个百度请求且手动触发任务正常），用例始终处于running状态，资源池使用默认的LOCAL。在任务中心中停止，多次触发用例，问题依然存在
<img width="1624" alt="image" src="https://github.com/metersphere/metersphere/assets/53989235/f8a9f2e5-1957-40fc-bf40-cfa3c48c7a39">

### 重现步骤

1、定义一个百度接口
2、将接口生成用例
3、在Jenkins上创建一个任务，任务中只加载metersphere插件
4、构建任务

### 期待的正确结果

用例状态正常流转

### 相关日志输出

```shell
根据交流群内沟通，查看了node_controller的日志，未发现错误日志
```

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.1-lts修复
