### ISSUE TITLE
[FEATURE]缺陷模板管理的字段希望能支持自由移动字段顺序

### ISSUE THREAD

**Issue by tygk** [metersphere/metersphere#24714]
### MeterSphere 版本

v2.10.0-lts-b4

### 联系方式

1026526269@qq.com

### 请描述您的需求或者改进建议

缺陷模板管理的字段希望能通过拖拽的或者按钮的方式可以上下移动字段的显示顺序

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/53895033/623a5c7d-2eac-4b75-a64f-bacdb1f0e09c)

**Comment by luty2018** [comment]
好的 感谢建议， 这个可以加

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
