### ISSUE TITLE
[BUG]性能测试同步场景后，csv 文件丢失

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24712]
### MeterSphere 版本

v2.10-lts 

### 使用外置数据库

否

### 问题描述

性能测试同步场景后，csv 文件丢失

### 重现步骤

1. 场景一键转性能
![image](https://github.com/metersphere/metersphere/assets/103627487/61c8dfa2-8ec7-4e0e-82b3-cc631f319fa7)
2. 保存后点击同步场景设置最新变更
![image](https://github.com/metersphere/metersphere/assets/103627487/a85ed9ab-fcbb-435f-bba6-e538973f50d5)
同步之后csv 文件丢失
![image](https://github.com/metersphere/metersphere/assets/103627487/f73964da-5c2e-4405-914e-5f75bb19f1d8)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，计划于v2.10.2-lts修复

**Comment by 13290445582** [comment]
v2.10.2已修复
