### ISSUE TITLE
[BUG]2.10，自动化场景列表页，选择一个模块，打开一个场景，进行简单编辑，保存，在新建一个场景等操作后，回到列表页，无法切换模块。

### ISSUE THREAD

**Issue by mikeinshanghai** [metersphere/metersphere#24717]
### 联系方式

王进

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

2.10，自动化场景列表页，选择一个模块，打开一个场景，进行简单编辑，保存，在新建一个场景等操作后，回到列表页，无法切换模块。

这是一个偶发问题。客户2.9.1上经常遇到，我本地复现了好几次，复现过一次。

### 重现步骤

1. 切换到自动化场景列表页，左边有几个模块。 
2. 选择一个模块，然后点击场景编号，打开场景，简单编辑场景，然后保存。
3. 再新建一个场景
4. 切回到场景列表页
5. 选择其它模块，切换不了模块。

**Comment by mikeinshanghai** [comment]
https://github.com/metersphere/metersphere/assets/3350394/edf50aa6-efec-45e6-852a-5a21aa74a964

这是客户录的屏。 
我自己这边复现过一次，在2.10

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题在最新版本没有复现，复现后是怎么恢复正常的？当时网络是否正常，是否有其他同步操作？
烦请提供下复现时控制台信息，方便我们进一步排查原因。

**Comment by 13290445582** [comment]
你好，该问题在最新环境未复现，若升级最新版本后问题仍存在，请重新提issue。
