### ISSUE TITLE
[BUG] 1.20.23 LTS版本 场景会时不时不打印log.info("")，脚本报错看不到日志输出

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24732]
### MeterSphere 版本

V1.20.23LTS

### 使用外置数据库

否

### 问题描述

<img width="1101" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/0bdd2f72-19e7-4b40-98d9-8ca3b963b20f">
<img width="718" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/71ec0d79-fa9e-4f6b-b6d4-8f7af873dc24">

### 重现步骤
1、写三个步骤（都用自定义脚本）
2、每个脚本写的内容依次为log.info("1");log.info("2");log.info("3");
3、调试：1，2，3 所在的控制台输出时不时的丢失1或者2或者3
### 期待的正确结果

每个步骤的每个控制台都能准确输出里面的内容和报错信息

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
您好，v1.20-lts目前仅进行必要的安全类 Bug 修复和严重 Bug 修复，该问题在v2.10-lts测试没问题，建议您升级至v2.10-lts。
