### ISSUE TITLE
[BUG] 1.20.23LTS JSONPath断言 正则比对3260.00 != 3260.0  导致之前写的正则比对报错

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24735]
### MeterSphere 版本

v1.20.23LTS

### 使用外置数据库

否

### 问题描述
1、设置一个变量A=3260.0
     设置一个变量B=3260.0
2、JSONPath正则和equels比对一下
3、注意版本
4、因为1.20.23修复了JSONPath断言精度的问题

第一张图：表述的的正则比对3260.00 != 3260.0 
<img width="1232" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/a8a6de6c-8ce2-4d43-9535-571a6456fbab">
第二张图：equels比对3260.00 == 3260.0
<img width="1249" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/984264b4-4d49-4208-955b-560b759f1be8">
第三张图：是用其他工具解析获取的值
<img width="1241" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/350b6b84-e95c-45e9-b17e-b98aeb0b61f5">

### 重现步骤
复现步骤：参考以上图片即可；

### 期待的正确结果
优化一下：正则比对像equels比对一样

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复，升级一下吧。
