### ISSUE TITLE
[BUG]测试计划删除，报错：SQL error happened, please check logs.

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#24738]
### 联系方式

Limon

### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

测试计划删除失败。

![image](https://github.com/metersphere/metersphere/assets/44999044/c53c3d0c-f708-4c7d-a4b7-0b2f0fb762f6)

### 重现步骤

删除测试计划，计划中关联了功能和接口用例。

**Comment by 13290445582** [comment]
您好，在最新环境多次尝试并未复现该问题，建议升级至最新版本尝试。

**Comment by LimonFHM** [comment]
您好，已升级至最新2.10lts版本，问题未解决。
![image](https://github.com/metersphere/metersphere/assets/44999044/d7dc0c82-fe4b-4574-aeda-73fb5e8e5f9e)

**Comment by LimonFHM** [comment]
ps：如果是新创建的“测试计划”，删除可以成功。以上数据都是老版本带过来的数据，可能在1.x版本中创建的计划，一路升级到2.10，然后这些老数据删除不了。

**Comment by 13290445582** [comment]
待发布v2.10.1后尝试下吧～

**Comment by 13290445582** [comment]
您好，经过多次尝试在最新环境并未复现，建议您升级至最新环境，若问题仍存在，请重新提issue。
