### ISSUE TITLE
[BUG] 升级版本后禅道对接失效。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#24747]
### 联系方式

Limon

### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

配置完全没动，从2.8升级上来，禅道就对接不了了，提示500.

![image](https://github.com/metersphere/metersphere/assets/44999044/ab394ed1-1285-47d1-b153-ae995bbb7ea0)

### 重现步骤

1. 禅道测试连接失效
2. 提交BUG同步失效
3. 校验禅道用户是否正常失效

**Comment by youliyuan-fit2cloud** [comment]
你好， zentao插件版本是旧的吗？
建议用最新的插件版本，下载链接如下。
https://github.com/metersphere/metersphere-platform-plugin/releases

**Comment by LimonFHM** [comment]
是的，谢谢
