### ISSUE TITLE
[BUG]UI测试添加步骤按钮偶现消失

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24746]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10-lts

### 使用外置数据库

否

### 问题描述

UI测试添加步骤按钮偶尔会消失，重新打开几次场景才会出现
![image](https://github.com/metersphere/metersphere/assets/88763608/46b58f83-a06a-48fb-8e21-9e620bf7626a)

### 重现步骤

偶现的，提交记录下

### 期待的正确结果

不应该消失

**Comment by youliyuan-fit2cloud** [comment]
你好，只这一句话实在没办法复现问题，请描述清楚前置操作等信息，感谢理解和支持～

**Comment by zrfit** [comment]
经沟通，暂时无法复现，未找到复现条件，后续如发现复现规律可再打开。
