### ISSUE TITLE
[BUG]集成jira模板后缺陷管理页面和创建缺陷页面加载加载慢

### ISSUE THREAD

**Issue by janehugit** [metersphere/metersphere#24757]
### MeterSphere 版本

 v2.10.0-lts

### 使用外置数据库

是

### 问题描述

在项目中集成了jira的缺陷模板后，打开缺陷管理页面和创建缺陷页面加载慢

### 重现步骤

1. 在项目中集成了jira的缺陷模板
2. 打开缺陷管理页面，在测试跟踪的模块中第一次加载的时候很慢，10s左右，后面就正常了，但是切换到别的模块，再回到测试跟踪模块，再打开缺陷管理页面时，依然很慢
3. 打开创建缺陷页面，每次都加载很慢，10s左右

### 期待的正确结果

页面加载速度正常

### 相关日志输出

```shell
日志中显示打开时有去读取jira中所有项目的数据，但实际这个项目只是关联了jira中一个项目的模板，可能是加载慢的原因之一
```

### 附加信息

![3e810127a8dc18549dabd2aeb125a858](https://github.com/metersphere/metersphere/assets/135193527/3a9ca1bf-5b88-4c75-933c-79b403a54885)
![bf31af014f14b90ca91c8ebd42e8381a](https://github.com/metersphere/metersphere/assets/135193527/f0a8d6de-98a7-4d6b-815a-3f2c25e384e1)

**Comment by 13290445582** [comment]
感谢反馈，已提交tapd，开发跟进。

**Comment by AgAngle** [comment]
你好，你是jira的字段很多吗，还是用户选择框的用户数很多呢？还有就是目前使用的 jira 插件是2.10吗，2.10 的插件有解决用户数量过多导致加载慢的问题

**Comment by janehugit** [comment]
> 

当前项目集成的jira的项目里面的用户不是很多，不知道你们的机制是直接加载的jira所有的用户还是只加载了当前集成的项目的用户？我们jira所有的用户确实很多。
另外，我已下载了jira的插件2.10，但是上传插件一直显示解析失败
![image](https://github.com/metersphere/metersphere/assets/135193527/ff1bf45e-1772-4829-9334-2d28ab959fc6)

**Comment by AgAngle** [comment]
你好，这么看应该是有的用户下拉框加载全部用户耗时比较久，2.10.0 用户选项改成了类似jira的页面检索，应该能解决这个问题；另外插件是这里： https://github.com/metersphere/metersphere-platform-plugin/releases 下载的吗？报错可以查看下 /opt/metersphere/logs/system-setting/xxx.log 的日志

**Comment by janehugit** [comment]
> 你好，这么看应该是有的用户下拉框加载全部用户耗时比较久，2.10.0 用户选项改成了类似jira的页面检索，应该能解决这个问题；另外插件是这里： https://github.com/metersphere/metersphere-platform-plugin/releases 下载的吗？报错可以查看下 /opt/metersphere/logs/system-setting/xxx.log 的日志
 
是从这个地址下载的插件，我刚刚又试了下，报错又变成‘Network error’了
![image](https://github.com/metersphere/metersphere/assets/135193527/de7f51f8-bbc2-4395-8838-c3afe742f501)
我查了下你说的这个路径的日志，找不到报错的日志，这个目录下的所有的log文件我都查了都没有。


![image](https://github.com/metersphere/metersphere/assets/135193527/76af2659-af65-4c97-a5a4-0db9e04a9e7b)

**Comment by janehugit** [comment]
之前装旧版的插件2.8.1的时候也出现过类似的问题，试了很多次，然后突然有一天就装成功了，然后后来再下载的新插件就再没有试成功过，之前也是找不到报错日志。感觉这个插件安装成功全靠运气。

**Comment by AgAngle** [comment]
你好，有加交流群吗，可以留下群信息，我加你看看什么问题吧

**Comment by janehugit** [comment]
> 你好，有加交流群吗，可以留下群信息，我加你看看什么问题吧

交流群60，糊糊

**Comment by AgAngle** [comment]
目前排查是因为史诗链接选项加载数据过多导致较慢，后续版本优化

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～

**Comment by janehugit** [comment]
> v2.10.3已修复，请升级～

请问是系统版本还是插件？我看插件的这个版本还没出来

**Comment by 13290445582** [comment]
您好，github插件已更新，可以下载最新插件了～

**Comment by janehugit** [comment]
> 您好，github插件已更新，可以下载最新插件了～

插件更新后还需要别的操作吗？目前已经更新到最新的插件了，但是缺陷管理页面加载还是很慢
