### ISSUE TITLE
[BUG]性能测试无法读取到csv文件，接口自动化正常（附图）

### ISSUE THREAD

**Issue by aya23333** [metersphere/metersphere#2475]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.0-e6a9556e

**Bug 描述**
简要描述您碰到的问题
性能测试无法读取到csv文件，接口自动化正常

**Bug 重现步骤**
1. 接口自动化设置场景变量，场景变量为CSV文件 ，变量名为${idd}
![image](https://user-images.githubusercontent.com/83439052/116642063-984d5b00-a9a0-11eb-9498-26e3b8a86b49.png)
![image](https://user-images.githubusercontent.com/83439052/116642069-9d120f00-a9a0-11eb-9c64-6da724e02c7f.png)

2. QUERY参数id参数化${idd}，调试接口自动化，正常运行 正常读取到CSV的值
![image](https://user-images.githubusercontent.com/83439052/116642120-b3b86600-a9a0-11eb-92f8-05400a00b355.png)
![image](https://user-images.githubusercontent.com/83439052/116642253-f8440180-a9a0-11eb-8b86-ad4ebfb23fd6.png)

3. 该接口自动化用例 转换为 性能测试，性能测试报错 日志为Could not read file header line for file 1fca157a-7b9_mnew338.csv
![image](https://user-images.githubusercontent.com/83439052/116642286-0f82ef00-a9a1-11eb-8022-49b177434f9d.png)

4.检查路径下的文件/opt/metersphere/data/body/1fca157a-7b9_mnew338.csv   确实存在
![image](https://user-images.githubusercontent.com/83439052/116642312-1e69a180-a9a1-11eb-9f8a-3780613ef118.png)

5.性能测试下载改jmx文件，在jmeter中运行（更改使用CSV绝对路径）正常

比如
比如CSV文件里面ID是 1,2,3   
请求链接是https://www.XXX.com&id=${id}
请求的链接分次https://www.XXX.com&id=1   https://www.XXX.com&id=2  https://www.XXX.com&id=3

**期待的正确结果**
正确情况下应该是什么样的？
正常获取到该CSV文件，与接口自动化一样可正常读取CSV文件

**截图**
截图如上

**Comment by aya23333** [comment]
![image](https://user-images.githubusercontent.com/83439052/116646254-3265d100-a9aa-11eb-9c04-9326a0264a1e.png)
文件头行为idd，日志报读取不到文件头行就很奇怪，jmeter可以正常读取该文件的数据

**Comment by aya23333** [comment]
![image](https://user-images.githubusercontent.com/83439052/119919529-3848d500-bf9d-11eb-84ea-69a1e48e1754.png)
一个月了，还没有修改这个BUG，日志报错找不到这个文件

**Comment by aya23333** [comment]
![image](https://user-images.githubusercontent.com/83439052/119919684-88c03280-bf9d-11eb-84f0-9f039a0ddedb.png)

**Comment by xulinde** [comment]
这个问题下个版本会修复，临时解决方案，手动改下jmx的里面的文件名然后重新上传

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.10.1 已修复，请升级到该版本。

**Comment by aya23333** [comment]
> 你好，v1.10.1 已修复，请升级到该版本。



> 这个问题下个版本会修复，临时解决方案，手动改下jmx的里面的文件名然后上传

不清楚你们怎么测试通过的，我删除了原来的csv文件 又上传放入，日志显示“ Could not read file header line for file”“无法读取文件的文件头行”，但是 改了文件名后可以正常读取，这不是还是有问题嘛，三个版本了

图1：提示“无法读取文件的文件头行”
![image](https://user-images.githubusercontent.com/83439052/123190800-d2d00180-d4d2-11eb-8b25-49bb23f7aaf1.png)
图2：文件命名为1fca157a-7b9_mnew338.csv，可正常读取
![image](https://user-images.githubusercontent.com/83439052/123190704-9ef4dc00-d4d2-11eb-9397-f19c56dea377.png)
图34为对比mnew338.csv 与 1fca157a-7b9_mnew338.csv
![image](https://user-images.githubusercontent.com/83439052/123190987-1cb8e780-d4d3-11eb-880e-f414ede4fde5.png)
![image](https://user-images.githubusercontent.com/83439052/123190999-20e50500-d4d3-11eb-9c66-5d941c52caeb.png)

**Comment by aya23333** [comment]
![image](https://user-images.githubusercontent.com/83439052/123193686-cf8b4480-d4d7-11eb-98fa-66d672fc0548.png)
