### ISSUE TITLE
[BUG]1.20.23LTS 配置调试权限不生效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24751]
### MeterSphere 版本

v1.20.23LTS及以下

### 使用外置数据库

否

### 问题描述

配置了权限，但是页面没有调试按钮

### 重现步骤

1、配置权限和用户
<img width="1291" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/1b58d8dd-9732-4c56-956c-53aaab23b965">
<img width="1046" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/2aa3fdb7-0f7c-4049-9551-cecea969a962">
2、切换用户，打开接口测试的接口自动，找一个场景打开
<img width="1234" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/16dfea3b-2ea8-4b8b-892e-6fefe0cbcb03">

### 期待的正确结果

配置简单的调试权限和出来调试按钮

**Comment by 13290445582** [comment]
感谢反馈，问题已提交tapd，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
