### ISSUE TITLE
[QUESTION]单接口用例是否需要标识为场景用例的步骤

### ISSUE THREAD

**Issue by Laimf1995** [metersphere/metersphere#24755]
### 前提：
目前场景用例可以对 CASE 进行引用和复制，被引用或者复制的 CASE 则成为场景用例的一个步骤
按照用例是独立性，那么CASE 作为步骤，就不是一个完整的用例，不能单独运行。
在首页会统计 CASE 情况，在测试计划 勾选也不能很好区分 是单接口 CASE 还是场景用例的步骤 CASE。

### 做法：
目前做法是场景用例引用或者复制的 CASE 中，进行打标签识别。

### 想请问：
1、场景用例的步骤 如果引用或者复制CASE，这样的使用是否合理，是否满足用例独立性。
2、是否需要在单接口用例里面进行标识为场景步骤。
3、怎么样更加合理的划定单接口CASE 和 场景用例里面的步骤 CASE 。

**Comment by luty2018** [comment]
你好， 系统在接口这里提供了单接口case的能力，至于用例是否具备独立性，是否能单独运行，这个我们没有限制，每个人接口用例的设计和预期是不一样的。而场景用例提供引用或复制接口case，其实是为了提升接口case的复用性，如果用户觉得因为引用的不是一个独立可运行的case，用户其实也可以在系统先创建场景级别的接口用例， 再通过场景引用场景的形式来实现。

我们提供的是通用的产品功能，而怎么规范使用这个可以用户制订标准。
或者说目前的实现如果覆盖不到你的需求，那你可以提出具体的场景哈。
