### ISSUE TITLE
[BUG]【UI测试】场景中 if/else 判断条件下就只有一个步骤，运行时，这个步骤是成功的，但是同样的步骤会出现多个重复

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24756]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】场景中 if/else 判断条件下就只有一个步骤，运行时，这个步骤是成功的，但是同样的步骤会出现多个重复

### 重现步骤

【UI测试】场景中 if/else 判断条件下就只有一个步骤，运行时，这个步骤是成功的，但是同样的步骤会出现多个重复
![1685676972428](https://github.com/metersphere/metersphere/assets/104960608/6309c658-9c14-415e-a6ff-e8c912d49152)
![1685676972446](https://github.com/metersphere/metersphere/assets/104960608/2b49d1b4-17da-4546-a179-b08d457ce5d5)

**Comment by zrfit** [comment]
您好，感谢反馈！截图场景步骤含子步骤if/else的父级步骤分别是引用的场景还是指令？截图看是嵌套了一层。

**Comment by 2lipan** [comment]
引用指令
![image](https://github.com/metersphere/metersphere/assets/104960608/80cc0558-9cbf-4d11-b0dc-c76396948651)

**Comment by zrfit** [comment]
您好，未复现该问题，待v2.10.1-lts发布后可升级尝试。
