### ISSUE TITLE
[BUG]浏览器录制插件，设置只录制“http Request”，但录制结果里还是有css和js信息，结果和设置不相符

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#24768]
### MeterSphere 版本

2.10-lts

### 使用外置数据库

否

### 问题描述

[BUG]浏览器录制插件，设置只录制“http Request”，但录制结果里还是有css和js信息，结果和设置不相符

### 重现步骤

[BUG]浏览器录制插件，设置只录制“http Request”，但录制结果里还是有css和js信息，结果和设置不相符

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/eca72b59-abc9-43b7-bfa6-cd2b471bb3a9)

**Comment by youliyuan-fit2cloud** [comment]
你好，http request 指的是http请求都会录制，这个下载js 也是 http 请求，目前并不会过滤掉下载文件的http 请求。
