### ISSUE TITLE
[QUESTION]2.10版本本地开发环境部署时，io.metersphere:domain:jar:main依赖包找不到

### ISSUE THREAD

**Issue by chjtester** [metersphere/metersphere#24773]
### 请描述您的问题

项目需要依赖io.metersphere:metersphere-platform-plugin-sdk:pom:1.6.0这个jar包，然后下载metersphere-platform-plugin-sdk源码准备打包，下载依赖时
<img width="1148" alt="image" src="https://github.com/metersphere/metersphere/assets/53989235/a42957e4-8e44-4075-a3f8-150412061867">

**Comment by shenkaibo** [comment]
https://github.com/metersphere/metersphere/tree/main/framework/sdk-parent/domain
到 metersphere 主仓库，切到 main 分支，本地 mvn clean install 下 domian 项目

**Comment by lotushh** [comment]
> https://github.com/metersphere/metersphere/tree/main/framework/sdk-parent/domain
> 到 metersphere 主仓库，切到 main 分支，本地 mvn clean install 下 domian 项目

你好，找不到main分支

**Comment by D1zzzY1** [comment]
我也出现同样的问题 install了 domain 项目后仍然提示
![image](https://github.com/metersphere/metersphere/assets/107469948/cce829a2-6142-4111-8b7b-68aeb902d283)

**Comment by Get-lzh** [comment]
请问您怎么解决的啊

**Comment by bigdata2018ken** [comment]
同问，怎么处理的啊

**Comment by bigdata2018ken** [comment]
> 请问您怎么解决的啊
官方文档没有更新，还有一个仓库地址需要打包 https://github.com/metersphere/metersphere-platform-plugin
