### ISSUE TITLE
[BUG]jsonpath 提取响应体，对响应体中的 / 进行了转义，导致传参使用报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24771]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

jsonpath 提取响应体，对响应体中的 / 进行了转义，导致场景中下个接口使用提取的这个参数接口报错

### 重现步骤

1. mock 请求，响应体中含有 /
![image](https://github.com/metersphere/metersphere/assets/103627487/2902f0d5-84ac-40fe-853b-039253d34d1e)
2. 提取参数，查看提取进行了转义
![image](https://github.com/metersphere/metersphere/assets/103627487/80873bf0-fe3e-44c1-8b56-5195a81e1e81)

**Comment by youliyuan-fit2cloud** [comment]
你好，这里的  日期 里面的” / “是需要转义，正常的。
