### ISSUE TITLE
[BUG]工作空间类用户组，赋予除服务集成以外的所有权限，该组用户登录系统后无法创建项目

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#24789]
### 联系方式

357861578@qq.com

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

工作空间类用户组，赋予除服务集成以外的所有权限，该组用户登录系统后无法创建项目

### 重现步骤

操作步骤：
1.创建工作空间类用户组
2.为该用户组赋予除服务集成以外所有权限
3.添加该用户组的成员test01
4.test01用户登录系统后点击“系统设置->项目管理”中的【创建项目】

预期结果：
可以新增项目

实际结果：
创建项目弹窗闪一下即消失，无法创建项目

### 附加信息

![图片](https://github.com/metersphere/metersphere/assets/130725706/325ca762-19ee-4c44-94a2-c9a91ba6fa9f)

![图片](https://github.com/metersphere/metersphere/assets/130725706/144df9aa-8b7a-46e8-8162-14ea5dd84fef)

https://github.com/metersphere/metersphere/assets/130725706/ce946b17-6aca-488f-af2f-a8186f53bb20

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
经过反馈，该问题不是bug，因为创建项目需要选择集成第三方平台，所以需要加上集成第三方平台查询权限，感谢反馈。
