### ISSUE TITLE
[QUESTION]2.10版本本地开发环境部署时，启动SettingApplication提示java: 程序包io.metersphere.plugin.loader不存在

### ISSUE THREAD

**Issue by SayorNotDo** [metersphere/metersphere#24788]
### 请描述您的问题

<img width="1059" alt="image" src="https://github.com/metersphere/metersphere/assets/41109095/d148302f-4124-44ce-bcf2-2b2c9808106d">

**Comment by luty2018** [comment]
二次开发需要自行研究代码。
