### ISSUE TITLE
[BUG]场景调试响应体很大时一直显示测试中，任务中心显示报告已经执行完

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24783]
### MeterSphere 版本

v2.10-lts

### 使用外置数据库

否

### 问题描述

场景调试响应体很大时（18w数据），一直显示测试中，任务中心显示报告已经执行完，任务中心报告也能正常点开，生成报告可以正常执行

### 重现步骤

1. 可以 mock 一个响应体很大的接口，场景中调试
![image](https://github.com/metersphere/metersphere/assets/103627487/3c9b76e5-3f6a-4463-82d1-7c8a523a9779)
2. 可以看到调试历史中报告已经执行完成，场景调试页面一直测试中，调试历史中报告页可以正常点开
![image](https://github.com/metersphere/metersphere/assets/103627487/89ee302f-0c78-4c79-a8f2-b5ae8754b15c)
![image](https://github.com/metersphere/metersphere/assets/103627487/090adf6a-b294-4c45-8992-8df3f774f9ee)
![image](https://github.com/metersphere/metersphere/assets/103627487/f85a39e9-eed9-4906-89cd-20e741ba95d6)
![image](https://github.com/metersphere/metersphere/assets/103627487/44900eb5-40ed-497e-9a03-46ad146d54a6)

**Comment by 13290445582** [comment]
您好，感谢反馈！未复现该问题，待v2.10.1发布后升级尝试。

**Comment by meijieDouDou** [comment]
在qa 环境尝试复现，出现调试历史中报告已经执行完成，场景调试页面没有显示测试中，没有执行结果，调试历史报告中已经有执行结果
![image](https://github.com/metersphere/metersphere/assets/103627487/5aba1621-0843-4444-adf2-dd32b5b7e610)
![image](https://github.com/metersphere/metersphere/assets/103627487/f2d49619-7724-4a31-a011-8c068abf4509)

**Comment by 13290445582** [comment]
问题已提交tapd，开发跟进。

**Comment by 13290445582** [comment]
https://github.com/metersphere/metersphere/issues/24208
您好，按照这个配置下，再进行测试尝试下。

**Comment by meijieDouDou** [comment]
在 gateway 的 docker-compose-gateway.yaml 中 添加 environment
SPRING_CLOUD_GATEWAY_HTTPCLIENT_WEBSOCKET_MAX-FRAME-PAYLOAD-LENGTH: 512000000
场景内调试可以执行返回了，但是执行成功后浏览器偶发会崩溃，概率很大
