### ISSUE TITLE
[BUG]接口中存在http和sql用例的时，在首页接口用例统计，点击未覆盖跳转不到sql用例的展示页面。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#24785]
### MeterSphere 版本

 v1.20.23-lts-77e58286 

### 使用外置数据库

否

### 问题描述

接口中存在http和sql用例的时，在首页接口用例统计，点击未覆盖跳转不到sql用例的展示页面。

![image](https://github.com/metersphere/metersphere/assets/33945037/9c7c2662-42c9-47d1-9676-bf3abb67b470)

![image](https://github.com/metersphere/metersphere/assets/33945037/a4870182-92b3-42c0-a4ae-70d1e6a5900f)

![image](https://github.com/metersphere/metersphere/assets/33945037/a13e1444-578a-40f8-8610-833de5f27b4d)

### 重现步骤

1. 设置2条sql协议请求
2. 1条设置有用例，1条未设置。这个时候，页面用例应该是有1条未覆盖。
3. 默认切换展示http列表
4. 切换接口首页用例统计，点击未覆盖跳转。
5. 直接跳转到http的展示页面，并没有跳转到sql的页面。

**Comment by luty2018** [comment]
这个问题在 v2.10 LTS 已修复，建议升级版本。
