### ISSUE TITLE
[BUG]【UI测试】导入A指令，再新建指令引用该指令，点击保存，浏览器崩溃

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24786]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】导入A指令，再新建指令引用该指令，点击保存，浏览器崩溃

### 重现步骤

【UI测试】导入A指令，再新建指令引用该指令，点击保存，浏览器崩溃
![image](https://github.com/metersphere/metersphere/assets/104960608/31751cec-87ce-46fd-8827-106bfb00cdfe)

A指令如下
[Metersphere_Ui_MeterSphere_演示.zip](https://github.com/metersphere/metersphere/files/11649111/Metersphere_Ui_MeterSphere_.zip)

**Comment by 13290445582** [comment]
您好，感谢反馈，未复现该问题，是否是网络波动原因？待v2.10.1发布后升级尝试。

**Comment by 13290445582** [comment]
您好，多次验证，未复现该问题，后续若还存在该问题，请重新提issue。

**Comment by 2lipan** [comment]
再导入这个指令试试
[Metersphere_Ui.zip](https://github.com/metersphere/metersphere/files/11862568/Metersphere_Ui.zip)
![image](https://github.com/metersphere/metersphere/assets/104960608/512f37dd-7e72-4606-97b5-de2c3258958c)

**Comment by 13290445582** [comment]
感谢提供场景，问题已复现并提交至tapd平台。

**Comment by maninhill** [comment]
浏览器崩溃问题要想办法解决，至少是优化，做问题的终结者。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
