### ISSUE TITLE
[BUG] 功能用例 XMind 导入，文件包含特殊字符，用例步骤显示乱码

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [metersphere/metersphere#24784]
### 联系方式

995006199@qq.com  郭灶鹏

### MeterSphere 版本

2.10

### 使用外置数据库

否

### 问题描述

1、导入功能用例 XMind 格式，用例步骤包含特殊字符 。<img width="564" alt="image" src="https://github.com/metersphere/metersphere/assets/30264974/7b2d37a0-66e8-4a1b-b6cf-98c767a9d33d">
2、导入之后查看用例， 用例步骤出现乱码，出现&amp，如下图
<img width="796" alt="image" src="https://github.com/metersphere/metersphere/assets/30264974/c715da87-d517-45db-8353-7335747295c6">
上传的XMind 文件：
[21.xmind.zip](https://github.com/metersphere/metersphere/files/11648304/21.xmind.zip)

### 重现步骤

见问题描述。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
