### ISSUE TITLE
[BUG]【UI测试】流程控制-if条件控制-条件表达式切换为条件列表，该填的地方都填写了，但是页面会提示"参数不能为空"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24782]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】流程控制-if条件控制-条件列表，该填的地方都填写了，但是页面会提示"参数不能为空"

### 重现步骤

【UI测试】流程控制-if条件控制-条件列表，该填的地方都填写了，但是页面会提示"参数不能为空"
![image](https://github.com/metersphere/metersphere/assets/104960608/b9d99359-52d9-4d9d-970b-b5b7926f97cc)

**Comment by zrfit** [comment]
您好，感谢反馈！经沟通，是切换条件后可复现该问题，计划v2.10.2-lts修复。

**Comment by zrfit** [comment]
经沟通，是切换条件后可复现该问题，计划v2.10.2修复。
