### ISSUE TITLE
[BUG]UI测试模块，复制出来的UI测试，创建人为空

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#24795]
### 联系方式

15275908957

### MeterSphere 版本

1.20.23-lts

### 使用外置数据库

否

### 问题描述

UI测试模块，复制出来的UI测试，创建人为空

<img width="1385" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/a97319e0-3757-439a-94da-6f30f42167cc">

### 重现步骤

UI测试模块，在UI测试列表，复制一个测试，然后点击保存，复制出来的一条，没有创建人。

### 期待的正确结果

复制的人就是创建人

**Comment by 13290445582** [comment]
您好，感谢反馈，您提供的问题并未复现，v1.20-lts版本目前仅进行必要的安全类 Bug 修复和严重 Bug 修复；若该问题再次出现，建议升级至v2.10-lts版本。
