### ISSUE TITLE
[FEATURE]建议更改测试用例的排序规则，按照创建时间倒序排序

### ISSUE THREAD

**Issue by junwei-liu** [metersphere/metersphere#24797]
### MeterSphere 版本

v2.10.20-lts 

### 联系方式

1025656390@qq.com

### 请描述您的需求或者改进建议

[FEATURE]建议更改测试用例的排序规则，按照创建时间倒序排序

- 测试用例的编写一般都是从头到尾的进行编写，按照现在的排序规则，最后编写的会在最上面。但是这样的话，在生成测试用例评审的时候，就会把最后编写的用例变成了第一条用例，测试用例之间有时有正向顺序的，所以就导致特别极其不方便。

### 请描述你建议的实现方案

建议：

- 测试用例的编写可以，也就是功能用例的测试用例仍然可以按照创建时间进行正序排序，即最新的在最上面。
- 用例评审模块的测试用例，按照倒序排序，即创建时间最早的在最上面。

### 附加信息

**### 特别紧急，**用例评审的时候放弃使用的心情都有了，直接导出excel进行评审的。

**Comment by maninhill** [comment]
@luty2018 用例评审时，用户不能自行选择排序顺序吗？

**Comment by junwei-liu** [comment]
> @luty2018 用例评审时，用户不能自行选择排序顺序吗？

创建评审任务，添加测试case的时候，一般都是直接全选一个文件夹，那么就自动带入了所有的测试case。但是这样的一个结果就是创建时间正序排序。
如果在评审里面使用ID进行排序，排序的结果是错乱的，不知道是不是有BUG。

**Comment by luty2018** [comment]
> > @luty2018 用例评审时，用户不能自行选择排序顺序吗？
> 
> 创建评审任务，添加测试case的时候，一般都是直接全选一个文件夹，那么就自动带入了所有的测试case。但是这样的一个结果就是创建时间正序排序。 如果在评审里面使用ID进行排序，排序的结果是错乱的，不知道是不是有BUG。

你好， 感谢反馈！针对你反馈的问题，我这边解答一下：
1.用例的排序规则目前我们默认是按创建时间，这个不会变更，考虑到用例会跟随版本、需求不断新增，按创建时间排序是更符合大家的使用的。也很理解你这边的使用场景， 所以我们提供了排序功能，当你排序后也会记住你的操作。
2.评审关联用例这边我们在表头增加了排序，规划在了  v2.10.1 预计在 6 月 8 日发布。
<img width="1404" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/547303e3-11a8-47f0-8713-6c6e8a233010">
同时，为了覆盖你说的在关联的时候全选文件夹，那在评审页面，我们也添加了创建时间的字段显示， 可以通过创建时间来还原你的创建顺序。
以上是否能解决你的问题？
另外你说在评审里使用 ID 排序是错乱的，是否可以提供截图给我们排查一下？

**Comment by luty2018** [comment]
> @luty2018 用例评审时，用户不能自行选择排序顺序吗？

加了排序，在 2.10.1 版本上。

**Comment by junwei-liu** [comment]
> > @luty2018 用例评审时，用户不能自行选择排序顺序吗？
> 
> 加了排序，在 2.10.1 版本上。

![image](https://github.com/metersphere/metersphere/assets/78710778/308503c8-ca68-4641-b53c-32c86df6377d)

**Comment by junwei-liu** [comment]
> > @luty2018 用例评审时，用户不能自行选择排序顺序吗？
> 
> 加了排序，在 2.10.1 版本上。

是否考虑在lts版本上修复该问题？

**Comment by maninhill** [comment]
v2.10.1-lts，就是 lts 版本。

**Comment by maninhill** [comment]
本周四发布，到时你可以升级。
