### ISSUE TITLE
[BUG] 自动化场景用例编辑页面，切换到场景列表页面，点击左侧的树结构目录 右侧的详细信息不同步刷新

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24794]
### MeterSphere 版本

V2.9.1

### 使用外置数据库

是

### 问题描述

自动化场景用例编辑页面，切换到场景列表页面，点击左侧的树结构目录 右侧的详细信息不同步刷新
![image](https://github.com/metersphere/metersphere/assets/82088551/3f7c18cc-86de-40bc-abd2-bca7b16f66cc)

### 重现步骤

1、任意场景用例进入编辑页面
2、点击左上角的场景列表，切换到场景列表页面，再操作目录结构树，，，  即可重现问题
![image](https://github.com/metersphere/metersphere/assets/82088551/861f3fff-051d-4bdb-952e-a3ad0f73a9c9)

**Comment by 13290445582** [comment]
您好，感谢反馈，在最新环境未复现该问题，建议升级至最新环境尝试。

**Comment by 13290445582** [comment]
该问题在最新环境未复现，升级至最新版本若还存在问题，请重新提issue，感谢。
