### ISSUE TITLE
[QUESTION]v2.10.0-lts版本是否支持sqlserver2008r2的SQL操作？

### ISSUE THREAD

**Issue by zhangchaolei** [metersphere/metersphere#24799]
### 请描述您的问题

2.10.0-lts版本连接  sqlserver2008r2 数据库成功
![image](https://github.com/metersphere/metersphere/assets/29458304/6f89b2a9-7c33-4867-9d5b-9af112782c23)

但是SQL操作时报错
![image](https://github.com/metersphere/metersphere/assets/29458304/ad8548e5-b448-4ddc-85b0-b52648f082ce)

**Comment by luty2018** [comment]
你好 ，sql server 驱动版本目前升级到11.2.3.jre17了，所以老版本不兼容，建议升级。

**Comment by zhangchaolei** [comment]
了解，谢谢
