### ISSUE TITLE
[FEATURE] 产品UI界面上增加访问在线帮助文档的链接

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#248]
**请描述您的需求或者改进建议.**

产品UI界面上增加访问在线帮助文档的链接。

**请描述你建议的实现方案**

右上角有帮助图标，点击跳转到在线文档页面。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 产品UI界面上增加访问在线帮助文档的链接。
> 
> **请描述你建议的实现方案**
> 
> 右上角有帮助图标，点击跳转到在线文档页面。

1.3版本

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已添加
