### ISSUE TITLE
[FEATURE]一个小建议：显示文本内容的时候，如果显示器显示不下，可以换行显示嘛？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24805]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：显示文本内容的时候，如果显示器显示不下，可以换行显示嘛？
场景：写一点小脚本或者，或者接口返回的内容比较长的时候，这点很痛苦，都是拷贝到其他软件去查看的

**Comment by luty2018** [comment]
脚本这里我们有规划增加自动换行功能， 可以关注后面的版本更新哈。

**Comment by YellCatt** [comment]
> 脚本这里我们有规划增加自动换行功能， 可以关注后面的版本更新哈。

非常感谢，其他地方，比如接口case 请求内容也能加入自动换行也是极好的

**Comment by luty2018** [comment]
收到， 已规划

**Comment by luty2018** [comment]
v3已支持自动格式化
