### ISSUE TITLE
[BUG]测试跟踪，功能用例页面，把左边模块区域收起来后，退出系统，重新登录后，就无法展开了

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#24800]
### 联系方式

王进

### MeterSphere 版本

V2.10

### 使用外置数据库

否

### 问题描述

测试跟踪，功能用例页面，把左边模块区域收起来后，退出系统，重新登录后，就无法展开了

### 重现步骤

在客户系统上：
1. 把模块区域收起来
<img width="260" alt="1685966299094" src="https://github.com/metersphere/metersphere/assets/76033005/ddc9a64e-bec2-4c2b-8c85-c8be82402164">
2. 然后退出系统，再登录进来，打开功能用例页面，就会发现模块区域无法展开。 
3. 在我们内部部署的相同版本上未复现该问题，如果需要我们可以腾讯会议演示。

**Comment by youliyuan-fit2cloud** [comment]
你好， 该问题最新版本没有问题，请确认下是否是正式发布的版本：
![image](https://github.com/metersphere/metersphere/assets/54612864/94ffc2d6-7807-454a-803c-44031db19bd2)

**Comment by youliyuan-fit2cloud** [comment]
清缓存后无此问题。
