### ISSUE TITLE
[BUG]【系统设置】-【工作空间】-【项目管理】创建项目时不支持选自定义模板

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24804]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

【项目设置】-【模板管理】里创建自定义用例模板，在系统设置的工作空间中去创建项目时，不支持选自定义用例和缺陷模板

### 重现步骤

1.进入【项目设置】-【模板管理】模块，创建自定义用例模板
2.进入【系统设置】-【工作空间】-【项目管理】模块，点击创建项目
3.在选择用例模板

### 期待的正确结果

创建项目时支持选自定义模板

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/b38fdb95-919f-43f7-9554-c58a638c8a1f)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个用例模版是项目级别的模版，你新创建项目的时候还没有自定义模版，当然看不到其他的项目的模版。
