### ISSUE TITLE
[BUG]测试跟踪-测试计划--接口测试用例执行结果与报告不一致

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#24801]
### MeterSphere 版本

V2.10.X-LTS

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划--接口测试用例执行结果与报告不一致

### 重现步骤

[前提]测试跟踪-测试计划-设置某个计划定时任务晚上22点执行
[步骤]1、点击测试跟踪-报告
2、查看22点定时任务报告
3、报告失败数49 
4、测试计划--接口测试--执行结果 列【筛选】-error
5、找不到部分失败的case
6、 刷新页面  通过更新时间列排序 ，发现竟然还有更新时间和执行结果是2023-05-28的数据，执行结果是success，====那么问题来了，定时任务是全量执行的今天是6月6号，理论上都应该是6月5号晚上22点之后的定时任务时间啊

### 期待的正确结果

测试跟踪--测试计划的报告一致性

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/e6d4731b-febb-4710-bed6-0f7b63f97f3b)

**Comment by legend818** [comment]
我们团队一直通过这个页面的 执行结果来筛选失败error重新执行，现在这个数据不一致影响使用

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已让开发定位问题，请关注后续反馈。

**Comment by youliyuan-fit2cloud** [comment]
该问题在v2.10.2-lts种已修复。

**Comment by legend818** [comment]
2.10.2 升级问题还存在

**Comment by legend818** [comment]
研发说是 Jackson的一个安全设置问题，计划3版本解决，对接一下   z 勇

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
