### ISSUE TITLE
[BUG]UI测试，输入操作，输入内容 目前是必须输入内容，但是客户碰到给输入框置空，然后再次查询的场景。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#24813]
### 联系方式

王进

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

UI测试，输入操作，输入内容 目前是必须输入内容，但是客户碰到给输入框置空，然后再次查询的场景。

### 重现步骤

1. UI测试，输入操作，输入内容（见下图），当前是必须输入内容。
<img width="515" alt="1686035341402" src="https://github.com/metersphere/metersphere/assets/76033005/7a6b36a5-ba86-4f3e-9a05-c1d39d104ef5">

2. 在用户查询场景中，先输入内容 比如一个 ID，然后点击查询。查出若干记录。
3. 接着用户想把刚刚的输入框，置空，然后点击查询，查询所有记录。 
    备注：当前输入操作 输入框是“默认就是清空后输入”。用户想要的就是 清空，不做任何输入。
5. 按照当前设计，要么 输入框 什么都不需要输入 也就是 将必须输入内容限制改成可选输入，实现直接给输入框置空就行。或者 在输入操作 输入内容，提供一个置空选项。

**Comment by zrfit** [comment]
您好，感谢反馈！用输入框的功能键功能可实现清空输入框操作，注意要勾选追加输入，在输入框中输入${KEY_CONTROL+A}${KEY_BACK_SPACE}${KEY_ENTER}。
