### ISSUE TITLE
[BUG]【测试跟踪】-【测试计划】测试计划执行时设置失败重试，如果场景里有循环控制器，循环控制器下的接口执行失败未重新执行

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24816]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

在测试计划设置失败重试，手动执行测试计划时，如果场景里有循环控制器，循环控制器下的接口执行失败未重新执行

### 重现步骤

1.进入接口自动化模块，创建一个接口场景，并在该场景中加入循环控制器
2.进入【测试跟踪】-【测试计划】模块，创建一个测试计划，并关联刚刚创建的场景
3.执行测试计划，并且设置失败重试

### 期待的正确结果

如果测试计划设置失败重试，循环控制器下的接口执行失败也会重新执行

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/493ba53e-3f54-4aef-bf24-3662e00b7a39)

**Comment by fit2-zhao** [comment]
感谢反馈，循环控制器下的请求不会重试。
