### ISSUE TITLE
[BUG]大场景导出 metersphere 格式，再导入报错，场景中接口的入参比较大，大于5M，都是 json

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#24810]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10-lts

### 使用外置数据库

否

### 问题描述

2023-06-04 11:48:02,622 [qtp1949430968-47608] ERROR i.m.s.scenario.ApiScenarioService 177 - Method[scenarioImport][java.lang.RuntimeException: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (5005744) exceeds the maximum length (5000000)]
java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (5005744) exceeds the maximum length (5000000)

### 重现步骤

社区用户报错

**Comment by youliyuan-fit2cloud** [comment]
你好，请补充几个信息，这个大场景是多大？包括多少个请求？json文件有多大等等信息？

**Comment by shenkaibo** [comment]
场景私发你

**Comment by shenkaibo** [comment]
jackson-core-2.15.0 不支持修改 maximum length
https://github.com/FasterXML/jackson-core/pull/1019
看起来 [jackson-core-2.15.2 ](https://github.com/FasterXML/jackson-core/releases/tag/jackson-core-2.15.2) 支持了 覆盖默认的 StreamReadConstraints 配置

**Comment by shenkaibo** [comment]
单独替换 api-test 容器 /app/lib 下的  jackson-core-2.15.0.jar 为  jackson-core-2.15.2.jar， 可以临时解决这个问题

**Comment by shenkaibo** [comment]
@youliyuan-fit2cloud 这个改完 能支持可配置么，目前  jackson-core-2.15.2 的话 最大默认是 20M，我们这里 有大于 20M 的 json 需求，  jackson-core-2.15.2 支持可配置 大小，建议我们也做成可配置的。
![b121d2b5e7efa09a32a2dc2cf17b207](https://github.com/metersphere/metersphere/assets/30038088/2d23f9ba-dd02-4467-aed8-d6394360490d)

**Comment by youliyuan-fit2cloud** [comment]
> 

经过内部讨论，目前不支持可配置。即，不会单独去升级某个包，会随着框架一起升级。当前临时解决方案即可。感谢理解和支持～

**Comment by shenkaibo** [comment]
> > 
> 
> 经过内部讨论，目前不支持可配置。即，不会单独去升级某个包，会随着框架一起升级。当前临时解决方案即可。感谢理解和支持～

现在我们替换包 jackson-core-2.15.2 最大只支持到 20M ，目前这里有大于 20 M 解析的需求，这个目前暂时还解决不了。
