### ISSUE TITLE
[BUG]【测试跟踪】基于测试计划关联功能用例报错

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#24818]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

测试计划，关联功能用例，关联报错，必现。
<img width="1439" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/01364f37-77e0-4743-9963-6fe9000417f0">
<img width="916" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/9b44f4d4-6b64-47ef-8f54-84f1bf00eba7">
<img width="1431" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/e6a14522-ec2f-4556-aa81-6e75cd1ce539">
<img width="1097" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/7acee43c-6fb3-40a3-8add-ccbbb04ef9a6">

### 重现步骤

现创建十多个功能用例，把标签设置为“展示”，然后创建一个测试计划，使用测试计划关联功能用例，使用高级搜索，搜索标签“展示”，然后选择一个模块，最后选择所有数据，关联报错

### 期待的正确结果

可以正常关联

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。
