### ISSUE TITLE
[FEATURE]需求：通过接口文档，自动生成接口异常访问的入参和自动请求一遍

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24819]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：通过接口文档，自动生成接口异常访问的接口case，并自动请求一遍
场景：快速对接口进行异常传参测试

**Comment by luty2018** [comment]
自动生成接口异常访问的接口case的规则是什么样的

**Comment by YellCatt** [comment]
> 自动生成接口异常访问的接口case的规则是什么样的

我不知道是否有通用性啊，但是我这边，访问方式，字段传值类型（可以根据接口文档），字段传值大小都要测试，所以我想是否有可能ms最这类的异常情况进行自动化生成

**Comment by luty2018** [comment]
明白， 这个可以规划。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
