### ISSUE TITLE
[BUG]接口自动化场景导入接口，查询时报错（偶现）

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#24823]
### MeterSphere 版本

v2.10.0lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/55130444/c7848b20-9975-4e58-98b7-3f599e3be5c3)
接口自动化场景里引用api，按照路径搜索，偶现504报错。

### 重现步骤

偶现错误，怀疑是接口数量很多，搜索条件查询响应慢导致。

**Comment by youliyuan-fit2cloud** [comment]
你好， 导致该问题的原因可能是当时服务器的负载过高，内存/网络状况比较差，再次遇到请及时查看服务器状况，可以随时反馈给我们，感谢理解和支持～

**Comment by 13290445582** [comment]
您好，该问题在最新环境未复现，在确保网络等条件的前提下升级至最新版本测试，若问题仍存在，请重新提issue。
