### ISSUE TITLE
[BUG]测试跟踪-测试计划手动执行任务中心显示成功，但是报告却显示running

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#24820]
### MeterSphere 版本

V2.10.X-LTS

### 使用外置数据库

否

### 问题描述

[BUG]测试跟踪-测试计划手动执行任务中心显示成功，但是报告却显示running

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/19423100/a4e658a1-67a9-48cf-bd5d-5106694a4ce9)
![image](https://github.com/metersphere/metersphere/assets/19423100/663e09e4-1113-427e-af3a-9bda1b0594b2)
【前提】测试跟踪--测试计划有一个2个case的 计划
【步骤】1、测试跟踪--测试计划 手动执行这个计划
2、任务中心显示2个case 都是success
3、测试跟踪-报告显示成功50%  其中一个是running

### 期待的正确结果

正确一致性

**Comment by legend818** [comment]
2.10.2 版本没有发现此问题了

**Comment by fit2-zhao** [comment]
感谢配合。

**Comment by legend818** [comment]
2.10.6版本此问题复现
