### ISSUE TITLE
[BUG]测试跟踪-报告--运行数据显示超多环境数据

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#24821]
### MeterSphere 版本

V2.10.X-LTS

### 使用外置数据库

否

### 问题描述

测试跟踪-报告--运行数据显示超多环境数据

### 重现步骤

1、测试跟踪--报告--查看 某一特定报告（就他特殊）
2、运行环境 那   环境显示超多（2.8.1版本就发现有此问题）

### 期待的正确结果

正确显示

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/03c0490f-98a5-4de3-8ee4-f1ceeffadae9)

**Comment by Somebody-JIAN** [comment]
这是之前执行过测试计划产生的报告吗？

**Comment by legend818** [comment]
之前执行过的是什么意思？  我现在每次执行都是这样 手动 定时都是这样

**Comment by youliyuan-fit2cloud** [comment]
v2.10.2-lts中已修复。
