### ISSUE TITLE
[QUESTION]用例评审时添加评论时有两个操作和查看入口，使用场景是什么？

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#24822]
### 请描述您的问题

点击一个用例评审单中的用例进行评审（评审人角色登录），发现页面上有两个【评论】添加按钮，如图1所述，其中1处的评论无法添加，2处的评论可添加，这两个的区别是什么？
再次尝试通过2处添加一个评论，添加评论后效果如图2所述，页面中展示了两个评论，是否可以取消1处的评论展示和添加功能，只保留2处？或者两个地方的展示是否有其他用途或者使用场景？

图1：
<img width="1284" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/4649847b-cbc6-47cd-8bcb-6451a7f6c8c5">
图2:
<img width="1252" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/a7ba88bf-def0-45bf-a162-fd11e737e29e">

**Comment by luty2018** [comment]
评论1是这个用例的全部评论。出于页面复用所以展示了， 这里我们也在规划在后续的版本中评审的时候去掉评审1 。
感谢反馈哈。
