### ISSUE TITLE
[BUG]使用计数器作为变量来提取响应体结果，提取tab打印从2开始

### ISSUE THREAD

**Issue by Joesmj** [metersphere/metersphere#24834]
### 联系方式

1228289832@qq.com

### MeterSphere 版本

v2.8

### 使用外置数据库

是

### 问题描述

提取参数打印的不是从code1开始，所以也拿不到对应的提取参数
![image](https://github.com/metersphere/metersphere/assets/26533041/8bcd2a7f-037a-4821-9894-46295c874869)
![image](https://github.com/metersphere/metersphere/assets/26533041/51672dc6-b14c-4fa1-a558-0e25d3ed3d03)

### 重现步骤

只要在后置操作中通过jsonPath提取参数，并且参数已计数器命名，就可以复现

### 期待的正确结果

响应内容->提取->打印code1: 0

**Comment by zrfit** [comment]
您好，感谢反馈！目前metersphere后端调用的jmeter，目前和jmeter变量机制是一致的。

**Comment by Joesmj** [comment]
那我上面说明的问题怎么解决呢
