### ISSUE TITLE
[BUG] 使用同一个CSV数据 次数循环导致下面While循环无法使用

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24832]
### MeterSphere 版本

所有版本

### 使用外置数据库

否

### 问题描述

第一种情况：次数循环在前（有问题）
<img width="984" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/1b71c750-0e01-470f-91fd-5cfad9650e97">
第二种情况：次数循环在前，关闭成功之后继续循环（关闭之后，正常）
<img width="980" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/ba9a14da-b840-48eb-b50e-8009d28650b4">
第三种情况：While循环在前(这个情况是可以的)
<img width="1023" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8ac2d1c5-98de-4981-a83e-51c5d90017a2">

### 重现步骤

1、上传一个CSV文件（单列、多列都行）
2、添加次数循环 （循环次数随意，但是循环里要使用CSV文件的变量）
3、添加while循环（循环条件指定为CSV文件的第一行的变量值）如下：
<img width="1002" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/171e6a88-ccd9-4aa5-b0e9-1d5b7a563d8f">
<img width="872" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/e0597600-4cd2-4203-9d44-3ed83bcca2a4">
4、如果按照步骤复现不了可以联系我提供相关文件

### 期待的正确结果

每次循环都应该一个新的开始，对于他使用的CSV文件变量也应该是新的开始；
做到不同的循环对csv文件的处理保证隔离性

**Comment by zrfit** [comment]
您好，感谢反馈！和https://github.com/metersphere/metersphere/issues/21970属于同类问题，已提需求，计划在v3.0对csv变量获取逻辑进行优化。
