### ISSUE TITLE
[BUG]自定义系统管理用户组应该不可以将自己的用户组改为系统默认的超级管理员用户组

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#24837]
### 联系方式

无

### MeterSphere 版本

v2.10.x

### 使用外置数据库

否

### 问题描述

登录用户被赋予如下图1中的用户组1-3的三个角色，登录平台后新增用户组4，如下图可以为自己添加超级管理员（系统）的权限，权限反串了，小权限用户可以将自己升级为超级管理员用户了。
<img width="590" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/d7694718-9b66-4e5d-95f7-94e4bf9e6f01">

### 重现步骤

步骤一：管理员创建 iamadmin 的用户组，所述类型选择系统，如下图所示：
<img width="691" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/13e15c71-16f5-414b-86ba-979986212111">

步骤二：管理员创建用户为其赋权如图所示的用户组1-3，然后退出登录，用新建的用户登录MS平台；

步骤三：新建用户登录后，新添用户组4，并如下图选择超级管理员（系统）点击保存
<img width="590" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/547f89b3-6875-4551-99b6-7ff1d6237bf4">
步骤四：该登录用户成了超级管理员。

### 期待的正确结果

如重新步骤所描述，归属系统类型用户组的用户不能有将自己改为超级管理员（系统）的用户组

**Comment by youliyuan-fit2cloud** [comment]
你好，请确认一下 自定义的系统用户组开启了哪些权限？-----这个“ iamadmin 的用户组”
如果这个系统用户组开启了编辑用户等权限，属于该用户组内的用户即可以 给任何用户添加 超级管理员的用户组 权限。

**Comment by xueqidove** [comment]
> 你好，请确认一下 自定义的系统用户组开启了哪些权限？-----这个“ iamadmin 的用户组” 如果这个系统用户组开启了编辑用户等权限，属于该用户组内的用户即可以 给任何用户添加 超级管理员的用户组 权限。

主要是越权了

**Comment by luty2018** [comment]
不是越权的问题，是你权限配置的问题。修改用户的权限归属系统-用户菜单，你给了用户组这个菜单的操作权限，那拥有这个用户组的人就可以改，你为什么要给空间和项目级别的用户组开一个系统的修改权限呢？

**Comment by youliyuan-fit2cloud** [comment]
上诉我们产品负责人已解释说明，保持当前设计。
