### ISSUE TITLE
[FEATURE]测试报告中，场景的耗时时间是否可以统计到左侧的列表中

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24839]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：测试报告中，场景的耗时时间是否可以统计到左侧的列表中
场景：需要对耗时太久的场景进行优化，目前只能一个个点开查看到底场景耗时的情况

**Comment by luty2018** [comment]
这个我们可以在新版本规划一下

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
