### ISSUE TITLE
[BUG]  很紧急 直接阻断流程使用 

### ISSUE THREAD

**Issue by GitHub201609** [metersphere/metersphere#24830]
### 联系方式

交流9群 Boom

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

方案1  所有脚本放在一个场景中  sql 执行 虽说有传参 但是不显示最终的数据   【九群 王进远程调试还是有问题】
方案2  将 http 放在A 场景  将  sql 部分放在B 场景  在创建c 场景 将A B 引入 通过
//vars.put("body_new","${body}");   定义全局变量  但是每次不是取得最新的值

### 重现步骤

先定义 http  请求  通过返回值获取 return  =  ${return}

通过 自定义  sql   执行  
    select  id.name   from  xxx  where xs=    ${return}   执行没有返回值       ${return}  是正常传入的
     select  id.name   from  xxx  where xs=    1334       写死  可以执行成功 

### 期待的正确结果

先定义 http  请求  通过返回值获取 return  =  ${return}

通过 自定义  sql   执行  
    select  id.name   from  xxx  where xs=    ${return}    
     希望能正常取到返回值 
    
    

### 附加信息

9群 王进远程看过问题

**Comment by youliyuan-fit2cloud** [comment]
select id.name from xxx where xs= ${return} -----------> xs ="${return}" .没加上双引号？
参考：select * from user where name="${name}"

**Comment by GitHub201609** [comment]
> select id.name from xxx where xs= ${return} -----------> xs ="${return}" .没加上双引号？ 参考：select * from user where name="${name}"

单引号 双引号  去空格都试了 无效

**Comment by youliyuan-fit2cloud** [comment]
你好，我们环境没有复现，方便把场景发给我们吗？
控制台日志和后台日志也一并发一下吧

**Comment by youliyuan-fit2cloud** [comment]
经用户反馈，是sql有延迟，非系统问题。
