### ISSUE TITLE
[FEATURE]场景测试里，自定义脚本是否可以给加一个单步运行的按钮

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#24831]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：场景测试里，自定义脚本是否可以给加一个单步运行的按钮
其他的都有，就它不能支持单步运行

**Comment by luty2018** [comment]
平台不具备开发环境，没法单独运行脚本呢。
