### ISSUE TITLE
[BUG]V2.10版本,脑图调整用例顺序保存后不生效

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#24847]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

脑图调整用例顺序保存后不生效

### 重现步骤

1、点击模块下的用例，调整用例顺序到最下方，保存
2、重新点击左则模块，点击全部展开，用例顺序又回到原来的位置
![666](https://github.com/metersphere/metersphere/assets/43720321/67c063f3-073a-468d-a058-60acc8022b6b)

### 期待的正确结果

用例顺序调整后重新打开，按调整的顺序保存

### 附加信息

![666](https://github.com/metersphere/metersphere/assets/43720321/1f718bd0-b047-47d0-a3e5-e0f76c63821f)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.3-lts修复。

**Comment by zrfit** [comment]
功能用例列表按表头字段排序后进入脑图模式，置灰上移、下移按钮；功能用例列表不按表头字段排序后进入脑图模式，上移、下移按钮可点击并且保存后按脑图排序显示。
