### ISSUE TITLE
[BUG]csv数据文件设置的文件名在metersphere侧拼接的时候多拼了/test

### ISSUE THREAD

**Issue by ituqun** [metersphere/metersphere#24840]
### 联系方式

15951836943

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

${__BeanShell(import org.apache.jmeter.services.FileServer;FileServer.getFileServer().getBaseDir()+System.getProperty("file.separator")+"deviceIds.txt";)}
设置文件名为与jmx文件同级目录下的deviceIds.txt，这样在本地调试无问题的情况下，将jmx文件上传到metersphere上
![image](https://github.com/metersphere/metersphere/assets/135803980/647f3d7f-ef59-4b68-869a-230cdc95ebf2)
在性能测试的时候发现，metersphere会自动在获取的目录下再拼接个/test
![image](https://github.com/metersphere/metersphere/assets/135803980/c402df9c-69d5-4fbc-a98f-bd9f7e19af49)

### 重现步骤

csv数据文件设置，文件名设置为${__BeanShell(import org.apache.jmeter.services.FileServer;FileServer.getFileServer().getBaseDir()+System.getProperty("file.separator")+"deviceIds.txt";)}

### 期待的正确结果

/test/deviceIds.txt，这样无论在哪儿跑脚本，都是取当前目录下的deviceIds.txt，本地jmx也没有必要非得放在/test目录下去调试

**Comment by liuruibin** [comment]
您好，性能测试执行时所有文件都在/test/目录里。我们会自动将文件路径改成/test
