### ISSUE TITLE
[BUG]场景调试接口响应体很大时，会导致浏览器崩溃

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24841]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

场景调试接口响应体很大时，会导致浏览器崩溃

### 重现步骤

1.  场景调试接口响应体很大时,执行成功后点击请求内容，再点击响应体，浏览器崩溃
![image](https://github.com/metersphere/metersphere/assets/103627487/5b98c20b-ddaf-4ab9-bc27-0aa5e8992109)
![image](https://github.com/metersphere/metersphere/assets/103627487/1a3b1680-d41d-4dd4-a1dc-60cf75dda5c8)

**Comment by fit2-zhao** [comment]
感谢反馈，响应内容过大时页面渲染比较耗费资源，建议加大自身电脑内存，或者把不常用占资源应用关闭掉。

**Comment by maninhill** [comment]
浏览器崩溃问题要想办法解决，至少是优化，做问题的终结者。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已优化，升级一下吧。
