### ISSUE TITLE
[BUG]【接口测试】 接口首页场景定时任务数量统计，从通过跳转的报告无法打开

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#24855]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

接口首页场景定时任务数量统计，从通过跳转的报告无法打开 

### 重现步骤

1.进入自动化场景页面，设置一个场景定时执行
2.进入接口首页，在场景定时任务数量统计模块，点击已通过或者未通过的场景数量
3.在跳转出来为页面里，点击查看报告

### 期待的正确结果

1.跳转页面报告能正常打开

### 附加信息

![1686212447544](https://github.com/metersphere/metersphere/assets/45531073/e411faee-e5ec-46aa-966d-0e3eefda2d4c)
![1686212532105](https://github.com/metersphere/metersphere/assets/45531073/b10a7082-8bf0-4f9d-aaf3-bc211e595620)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.2-lts修复。
