### ISSUE TITLE
[BUG]【接口测试】登录接口-后置提取参数，其中age参数是返回值中不存在的字段，断言能成功

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24857]
### 联系方式

pan.li@fit2cloud.com

### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【接口测试】登录接口-后置提取参数，其中age参数是返回值中不存在的字段，断言能成功

### 重现步骤

【接口测试】登录接口-后置提取3个参数，其中age参数是返回值中不存在的字段，提取值也是空
![image](https://github.com/metersphere/metersphere/assets/104960608/3edfcd9c-c049-443b-b6e6-09281d9785c5)

使用jsonpath断言时进行正则匹配，发现age这个参数断言正确了。
![image](https://github.com/metersphere/metersphere/assets/104960608/27a3e06e-c2fa-4252-b01c-2be64fa3e1e6)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.3-lts修复。
