### ISSUE TITLE
[BUG]测试计划定时任务消息通知配置两个相同类型的飞书机器人通知，只会触发一个通知。

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24856]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

测试计划定时任务消息通知配置两个相同类型的飞书机器人通知，只会触发一个通知。
比如：有两个执行完成的消息通知，都是飞书机器人，只是机器人地址不同，结果只会出发呀一个消息通知。
而换成钉钉机器人，就可以触发两个通知。

### 重现步骤

1.设置测试计划定时任务，给定时任务添加两个执行完成的消息通知，分别使用不同群的飞书机器人。

2.结果只有一个群里收到了机器人通知
![Uploading image.png…]()

### 期待的正确结果

应该跟钉钉机器人一样，都会通知到

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.1-lts未复现该问题，建议升级尝试。
