### ISSUE TITLE
[BUG]进入接口自动化页面，创建场景需要提前选择模块，否则会报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#24862]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

从其他页面进入接口自动化页面时，通过“更多操作”创建场景，如果不提前选择模块，页面会报错；之前的逻辑是如果不选择模块会默认归属到“未规划模块”内，而不是像现在这样报错

### 重现步骤

1、打开接口自动化页面

2、不选择左侧模块的情况下，通过更多操作创建自动化场景

3、查看现象，可如下截图

### 附加信息

<img width="722" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/32bbc7d7-e4f1-4712-a922-c2ee8c64561d">

<img width="765" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/42d169f7-6f99-4d5b-9e28-a513de55d927">

**Comment by zrfit** [comment]
您好，感谢反馈！已知问题，计划v3.0会去掉这个入口，建议点击+创建场景。
