### ISSUE TITLE
[QUESTION]服务集成中没有禅道？

### ISSUE THREAD

**Issue by gaye746560359** [metersphere/metersphere#24860]
### 请描述您的问题

最新的v2.10.1-lts中怎么集成禅道？
![image](https://github.com/metersphere/metersphere/assets/3060035/127cba82-31c5-4d95-bdce-b60952ceba78)

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere-platform-plugin/releases 
我们将第三方平台进行了插件化， 需要先在这个页面下载对应插件上传到平台就可以了。
