### ISSUE TITLE
[BUG]平台同步禅道缺陷时，优先级、所属项目、相关需求等自定义字段皆显示为对应id值，显示不友好，需优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#24861]
### MeterSphere 版本

V2.10.0LTS

### 使用外置数据库

否

### 问题描述

平台同步禅道缺陷时，优先级、所属项目、相关需求等自定义字段皆显示为对应id值，显示不友好，需优化

### 重现步骤

见问题描述即截图

### 附加信息

![0fac59506c840b51f17b4f9708acedc](https://github.com/metersphere/metersphere/assets/92150453/db498f2f-a0fc-4dd5-b982-5a5eaf7b9266)
![1686279971039](https://github.com/metersphere/metersphere/assets/92150453/1ac8c3a2-291b-4fa6-9ec2-552b6e823e2c)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.1-lts未复现该问题。
1、禅道是哪个版本？
2、检查禅道系统和ms自定义字段配置选项是否一致，优先级是否禅道系统配置的就是数字？提供对应截图看看。
3、建议升级到最新版本尝试。
