### ISSUE TITLE
[FEATURE]接口自动化调试的时候，希望不用触发消息通知

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24869]
### MeterSphere 版本

v2.10.0-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

接口自动化调试的时候，希望不用触发消息通知。
因为调试的时候，负责人也在观察页面，调试也很容易失败，这种消息发到群里面不太好，也无需通知其他人。

**Comment by luty2018** [comment]
已排期优化
