### ISSUE TITLE
[BUG]【性能测试】mqtt请求资源池不开启后置监听，运行到指定时间后一直停不下来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#24876]
### 联系方式

2361094294@qq.com

### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

否

### 问题描述

【性能测试】mqtt协议的性能测试，资源池开启后置监听，进行压测，运行到指定时间可以正常停止，若资源池不开启后置监听，进行压测，运行到指定时间后一直停不下来，等待了很就久也停不下来

### 重现步骤

1.【性能测试】mqtt协议的性能测试，资源池开启后置监听，进行压测，运行到指定时间可以正常停止
![image](https://github.com/metersphere/metersphere/assets/104960608/c3c5b088-4c48-4b5e-bb04-1853f677569a)
![image](https://github.com/metersphere/metersphere/assets/104960608/ec2380e7-5d9c-49f3-a5da-e6247365d985)
2. 若资源池不开启后置监听，进行压测，运行到指定时间后一直停不下来，等待了很就久也停不下来
![image](https://github.com/metersphere/metersphere/assets/104960608/de94fa05-ef0a-4084-8bed-e84ef0b0d5f3)
![image](https://github.com/metersphere/metersphere/assets/104960608/64926c1d-5bb8-41f6-9a12-84a1616d1556)
后台的jmeter容器也一直是up状态，jmeter的_report容器日志里一直显示计算中
![image](https://github.com/metersphere/metersphere/assets/104960608/afdc578a-39f8-4f71-a582-0acdb6d43e41)
![image](https://github.com/metersphere/metersphere/assets/104960608/d2539424-eee0-4e43-9c05-5180da118366)
3. 在v 2.10.1-lts 版本上也有此问题
![image](https://github.com/metersphere/metersphere/assets/104960608/3eb39e87-6b50-4065-b0a7-87ca2ab04c05)
4. 脚本如下:
[Metersphere_Scenario_mqtt.zip](https://github.com/metersphere/metersphere/files/11705547/Metersphere_Scenario_mqtt.zip)

**Comment by liuruibin** [comment]
我本地用命令行启动这个jmx同样不能停止

![image](https://github.com/metersphere/metersphere/assets/23045261/d5735606-1382-40ce-acae-bb35c27ef724)

但是结束标记已经输出了，就是jvm不能退出

**Comment by youliyuan-fit2cloud** [comment]
实际上是用后置监听器容器也不能正常结束，只是jmeter结束消息能被识别到。容器不能正常退出，官方的mqtt插件也不行
测试中发现 mqtt 建立连接后不会自动断开，导致jmeter不能正常结束。

**Comment by 2lipan** [comment]
但是在 JMX 界面上，可以看到到指定时间会自动停止。
![企业微信截图_16886230714665](https://github.com/metersphere/metersphere/assets/104960608/dd7e1eba-d595-43f5-a24a-ef30342e6cf9)
![企业微信截图_16886230555598](https://github.com/metersphere/metersphere/assets/104960608/7c21d0c7-39e4-4831-9bd1-d12ea0efb110)
