### ISSUE TITLE
[FEATURE]建议外部接口自动化场景用例导入ms平台后，导入的接口自动化用例涉及到的接口自动与系统已导入的接口定义关联，统计接口覆盖率

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#24872]
### MeterSphere 版本

版本:   v2.10.0-lts-89acace0

### 请描述您的需求或者改进建议

[FEATURE]建议外部接口自动化场景用例导入ms平台后，导入的接口自动化用例涉及到的接口自动与系统已导入的接口定义关联，统计接口覆盖率

**Comment by luty2018** [comment]
这个是会的呀， 只要路径匹配上了就会算覆盖率。

**Comment by feiyu0316** [comment]
好的，上周群里面客服回答说不会，让我提个优化建议😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月12日(周一) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]建议外部接口自动化场景用例导入ms平台后，导入的接口自动化用例涉及到的接口自动与系统已导入的接口定义关联，统计接口覆盖率 (Issue #24872)




 
这个是会的呀， 只要路径匹配上了就会算覆盖率。
