### ISSUE TITLE
[FEATURE]测试计划中使用高级搜索过滤用例时，支持选择自定义字段

### ISSUE THREAD

**Issue by vilian00** [metersphere/metersphere#24874]
### MeterSphere 版本

v2.7.1-9947cfcf

### 联系方式

MeterSphere 交流群63：vilian

### 请描述您的需求或者改进建议

目前测试用例列表中的高级搜索是支持选择自定义字段的，但在测试计划中筛选用例的高级搜索中不支持选择自定义字段，期望添加自定义字段搜索功能。
![image](https://github.com/metersphere/metersphere/assets/42952901/b5103554-1257-4e07-bcc4-73b2e3a3ced1)

**Comment by luty2018** [comment]
好的， 感谢反馈。我们加一下。

**Comment by luty2018** [comment]
已支持，可以更新版本使用。
