### ISSUE TITLE
[BUG]jenkins插件环境切换不生效

### ISSUE THREAD

**Issue by shitou3421** [metersphere/metersphere#2487]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.0-b3

**Bug 描述**
jenkins插件的运行环境配置不生效。我场景中用的是测试环境，在jenkins调用该场景并使用开发环境运行，实际上还是用的测试环境运行的

**Bug 重现步骤**
1.  创建两个环境：开发环境、测试环境
2. 创建接口自动化场景，场景配置为测试环境运行
3. jenkins插件中调用该接口自动化场景，并设置运行环境为开发环境
4. jenkins任务执行后，发现还是使用测试环境运行的

**期待的正确结果**
正确情况下应该是什么样的？
 jenkins任务执行后，应该改为jenkins配置的开发环境

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
这个问题没复现呢，您插件是用的最新版本吗
