### ISSUE TITLE
[FEATURE]建议接口自动化增加批量编辑用例功能，例如批量增加断言

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#24873]
### MeterSphere 版本

版本:   v2.10.0-lts-89acace0

### 请描述您的需求或者改进建议

[FEATURE]建议接口自动化增加批量编辑用例功能，例如批量增加断言

**Comment by luty2018** [comment]
那可以在环境里面添加全局断言。
<img width="978" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/e44e5d54-c28a-4181-a1e0-3992fdba9104">

**Comment by feiyu0316** [comment]
收到，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月12日(周一) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]建议接口自动化增加批量编辑用例功能，例如批量增加断言 (Issue #24873)




 
那可以在环境里面添加全局断言。
