### ISSUE TITLE
[BUG]升级到v2.10.1-lts-65fad062之后，场景的引用数据没有数据，需要手动重新保存。才可以有数据

### ISSUE THREAD

**Issue by AnneXie01** [metersphere/metersphere#24888]
### 联系方式

MeterSphere 交流群62、昵称：anne xie, wechat: yiren2936

### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

场景的引用无法查询到

### 重现步骤

在接口自动化页面，新建如下图几个文件夹
![1686548595699](https://github.com/metersphere/metersphere/assets/93319433/293eb27d-26b9-48d8-b0bf-c10b9166dab9)，
在E文件夹下新建场景1，
在app文件夹新建场景2，场景2引用场景1
step1: 查看场景1的引用

step2: 升级到v2.10.1-lts-65fad062之后，之前的数据没有数据，需要手动重新保存。才可以有数据

### 期待的正确结果

step1: 期望可以查询到场景1的展示，实际无

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，建议清理下缓存？

**Comment by youliyuan-fit2cloud** [comment]
该问题是其他缺陷修复影响了历史数据，确实需要手动保存后恢复正常，暂时没有解决方案，所以暂时不处理，感谢您的理解和支持。
