### ISSUE TITLE
[FEATURE] 所有搜索功能只要检索字段又前后空格就搜索不出来数据

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#24892]
### MeterSphere 版本

所有

### 使用外置数据库

否

### 问题描述

<img width="1395" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/10e3f274-43aa-46b8-886b-0988ed4d170d">
 测试用例1 这个是有的，加了前后空格就搜索不出来了

### 重现步骤

1、打开功能功能用例（或者其他的带搜索框的）一个页面
2、根据名称 搜索 前后加一下空格

### 期待的正确结果

在后台能去除一下前后空格

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.2-lts修复。

**Comment by Somebody-JIAN** [comment]
您好

我们不会对您的搜索条件手动进行去除空格处理。因为我们无法分辨您是手误敲了空格，还是就是要搜索以空格开头/结尾的数据

我们只会认为，您既然敲了空格，那么就是要搜索前/后带有空格的数据

**Comment by sss903065212** [comment]
我不这么认为，我想没有人会以空格为开头和结尾

**Comment by Somebody-JIAN** [comment]
给你举个例子就可以了。

<人员管理 添加用户>
<项目管理 项目组添加用户>

这两个数据，如果我只记住了关键字是”添加用户“， 我要准确搜索第一条， 那我只需要在前面加个空格，填写” 添加用户“就可以了。 

搜索条件是一种查询方式。  手误敲了空格，自己把空格删除，这个操作成本我不认为有多高。我个人感觉，如果为了兼容要求进行修改，那程序就失去了一种查询手段。

我们内部评估一下。
