### ISSUE TITLE
[QUESTION]2.10版本接口测试相关组件如何使用JDK11环境安装

### ISSUE THREAD

**Issue by sowfe** [metersphere/metersphere#24890]
### 请描述您的问题

当前2.10版本默认java环境未JDK17，但是由于JDK15以后不支持secp256k1加密算法，导致升级后接口请求的加密脚本不能使用，现在想将metersphere接口测试的java环境降到JDK11

**Comment by liuruibin** [comment]
您好，我们提供的镜像已经提高了基线，不能降低到jdk17以下
