### ISSUE TITLE
[BUG]mock返回异常

### ISSUE THREAD

**Issue by blank-1** [metersphere/metersphere#2489]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/30788027/116672300-9a311180-a9d4-11eb-8049-d46897db0b48.png)
![image](https://user-images.githubusercontent.com/30788027/116672383-b5038600-a9d4-11eb-9fff-8c88b0b7e172.png)
**Bug 重现步骤**
1.  配置mock
2. 点mock环境测试

**预期结果**
![image](https://user-images.githubusercontent.com/30788027/116671846-03fceb80-a9d4-11eb-9478-b0fecbfd0bb5.png)

**Comment by xulinde** [comment]
感谢反馈，我们试着复现下

**Comment by xulinde** [comment]
1.9.2已修复
