### ISSUE TITLE
[BUG] swagger生成的json文件导入时提示解析失败

### ISSUE THREAD

**Issue by 17680313722** [metersphere/metersphere#24895]
### 联系方式

1762258188@qq.com

### MeterSphere 版本

2.8.0

### 使用外置数据库

是

### 问题描述

1、swagger导出json文件，在metersphere进行导入，提示解析失败
![image](https://github.com/metersphere/metersphere/assets/32856534/f24a8a4a-36c1-44da-aaab-5050af5592d1)
2、设置定时任务，配置对应的swagger的url，定时任务也不生效

### 重现步骤

1、
![image](https://github.com/metersphere/metersphere/assets/32856534/36c671a1-8d1b-426c-a0f4-4b1ebc36f1a6)
2、
![image](https://github.com/metersphere/metersphere/assets/32856534/aeab6dc8-e972-447b-b5f3-ef38ed8d0e63)
3、文件校验通过为json格式
![MXpnhM7QQX](https://github.com/metersphere/metersphere/assets/32856534/c0d33bee-89e1-4593-ace1-2ae87e492af4)

### 期待的正确结果

导入成功，生成相关的接口信息

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，建议升级到最新v2.10.1-lts版本，有优化该问题，或者把文件发出来我们尝试复现，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
长时间未反馈，关闭该问题。
