### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by nova17621370317** [metersphere/metersphere#249]
**请描述您的需求或者改进建议.**

例如这个场景下有多个接口，那么转化性能测试后，跑的是所有的接口的性能测试吗， 我想单独跑，还需要多次创建

**Comment by nova17621370317** [comment]
nova

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 例如这个场景下有多个接口，那么转化性能测试后，跑的是所有的接口的性能测试吗， 我想单独跑，还需要多次创建

月底的版本会上场景和请求的启用、禁用功能，可以启用指定的场景或请求再转性能测试
