### ISSUE TITLE
metersphere v2.10.0版本执行离线部署apitest时，报数据库表不存在[QUESTION]

### ISSUE THREAD

**Issue by fw0037** [metersphere/metersphere#24900]
### 请描述您的问题

![wx_camera_1686562350255](https://github.com/metersphere/metersphere/assets/20429450/133194b4-facc-4b3e-87ee-c878baaf998e)
centos7.9离线首次部署时metersphere v2.10.0时，报错无相关表结构，数据库版本mysql 8.0。数据库只有表api_version

**Comment by fit2-zhao** [comment]
需要系统设置服务和项目管理服务先起来。
