### ISSUE TITLE
[BUG] csv 文件有问题，场景不执行，也无报错信息提示 

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24905]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

csv 文件有问题，场景不执行，也无报错信息提示 ，用户不知道问题在哪里，期望能给个提示，方便用户知道哪里有问题

### 重现步骤

1. 创建场景，添加错误的csv 文件
[根据类比查询.csv](https://github.com/metersphere/metersphere/files/11721687/default.csv)
2.调试场景,不执行，也无报错提示信息
![image](https://github.com/metersphere/metersphere/assets/103627487/14e3ed80-1c10-499a-a97f-c4ff32fa13a6)

### 期待的正确结果

期望能给个错误信息提示

**Comment by fit2-zhao** [comment]
感谢反馈，这个是底层测试引擎JMeter的一个bug，暂时没有特别好的处理方法，执行没结果时检查处理好csv文件就行。
