### ISSUE TITLE
[BUG]调用/track/test/plan/run/save接口执行测试计划时，如果userId参数不是平台上存在的用户，消息通知会判断出错

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24902]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

调用/track/test/plan/run/save接口执行测试计划时，如果userId参数不是平台上存在的用户，消息通知会判断出错。
实际上测试计划执行失败了，但是会发送成功的消息通知。

### 重现步骤

1.调用/track/test/plan/run/save接口执行某个测试计划,userId参数值随机输入，使用平台上不存在的用户ID
![image](https://github.com/metersphere/metersphere/assets/88763608/73b037d6-d2ff-4cfb-bf1d-b1bf30c3f351)
2.结果测试计划正常调用执行了，测试计划报告是失败的，但是发送了执行成功的消息通知。
![image](https://github.com/metersphere/metersphere/assets/88763608/806160c5-efd5-48bd-8e9d-7ba51326b1d0)
![image](https://github.com/metersphere/metersphere/assets/88763608/a83c1c89-1b3d-4471-9430-61f00d9305df)

### 期待的正确结果

应该正确发送对应的消息通知。

**Comment by youliyuan-fit2cloud** [comment]
请说明一下，这个消息通知是怎么设置的？项目设置- 消息设置？问题描述不清楚，没办法复现该问题，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts以上版本已优化，对userId参数做了校验，不允许非系统用户执行。
