### ISSUE TITLE
[BUG] UI测试，在本地执行中，选择输入控件，未勾选“追加输入”，在实际执行时候，并没有清空内容，而是在已有内容后面追加

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#24914]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

UI测试模块，在本地执行中，有输入的控件，没有勾选“追加输入”，但是在实际执行中，原来的内容并没有清空，而是在已有内容基础上追加内容。

之前版本是ok的，2.10之后就不行了。

![image](https://github.com/metersphere/metersphere/assets/33945037/5d6e9476-ea8b-428b-a984-02f0ea1b1a71)

### 重现步骤

1. UI本地调试
2. 有输入控件，改控件定位元素为，以后内容的框。
3. 然后再改控件内容框里面随意输入。不勾选“追加输入”.
4. 保存，并执行。可以从本地浏览器中清楚的看到，之前内容没有删除，在已有内容上追加。

### 期待的正确结果

1. 当未勾选“追加输入”的时候，应该是清空内容，在进行输入。

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，方便的话提供下导出场景文件。

**Comment by hao65103940** [comment]
> 您好，感谢反馈！未复现该问题，方便的话提供下导出场景文件。

是本地测试，看视频最后一步，会在名字后面追加，并没有清除内容再填写。

https://github.com/metersphere/metersphere/assets/33945037/19faa597-0081-41c0-aaad-ae07ddc0c967

**Comment by zrfit** [comment]
用上述场景可复现，计划v2.10.3-lts修复。
