### ISSUE TITLE
[QUESTION]安装了新版本：v2.10.1-lts-65fad062后，出现接口自动化&性能测试问题，请问是什么原因？

### ISSUE THREAD

**Issue by chenruiyingry** [metersphere/metersphere#24917]
### 请描述您的问题

安装了新版本：v2.10.1-lts-65fad062，尝试直接从v1.20 lts直接升级或情况重装都会出现下面的问题：
在性能测试引用自动化接口时会报错：服务调用出错[serviceId:api,url:/api/automation/export/jmx],错误信息:Error while extracting response for type [class io.metersphere.controller.handler.ResultHolder] and content type [application/json]
![image](https://github.com/metersphere/metersphere/assets/36652469/4f292d4e-0717-4199-8aff-e02911f694ea)

在接口自动化点调试时，会报错：调用资源池执行失败，请检查资源池是否配置正常
![image](https://github.com/metersphere/metersphere/assets/36652469/1239eda0-62ac-405f-9d58-209e94a9b189)
实际上是有默认资源池的
![image](https://github.com/metersphere/metersphere/assets/36652469/2d8a0b3a-1d7c-4b04-ae1b-f609a7fb87f7)

麻烦大佬帮忙看下是什么原因？

**Comment by fit2-zhao** [comment]
请把相关错误日志上传一下，目前错误信息看不出来问题。

**Comment by chenruiyingry** [comment]
需要哪里的日志呢？

**Comment by fit2-zhao** [comment]
看一下这两个日志：/opt/metersphere/logs/api-test/ms-jmeter-run.log & /opt/metersphere/logs/node-controller/ms-jmeter-run.log。

**Comment by luty2018** [comment]
如果问题依然存在您可以重新打开issue
