### ISSUE TITLE
[BUG]接口定义-case，请求体-json格式，数据没有成功保存

### ISSUE THREAD

**Issue by Ready-cc** [metersphere/metersphere#2491]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8
**Bug 描述**
简要描述您碰到的问题
新增/修改case，导入json格式的请求数据
提示保存成功，但是关闭后再进入该条数据查看，json数据还是空
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by Ready-cc** [comment]
![image](https://user-images.githubusercontent.com/6858370/116672434-c2207500-a9d4-11eb-8c07-bbc00f948f79.png)
![image](https://user-images.githubusercontent.com/6858370/116672445-c482cf00-a9d4-11eb-9ded-15fe13d9bb0a.png)

**Comment by Ready-cc** [comment]
![image](https://user-images.githubusercontent.com/6858370/116672658-0a3f9780-a9d5-11eb-8b27-a86f486f937e.png)
![image](https://user-images.githubusercontent.com/6858370/116672677-0f044b80-a9d5-11eb-96e0-4ceaa9c00d63.png)

**Comment by xulinde** [comment]
没有复现该问题，是不是编辑完，没有保存用例呢

**Comment by yxz312** [comment]
这个问题是在json-schema中导入或者填写后，在json中看不到内容，这样保存接口，再打开接口看json，依然是没有内容的。
![json-schema中填写json中确没有内容](https://user-images.githubusercontent.com/49225469/119246092-1d4b1f00-bbb1-11eb-8341-11e3253542d7.jpg)
![image](https://user-images.githubusercontent.com/49225469/119246113-6dc27c80-bbb1-11eb-93f2-dd16ec8d823b.png)

**Comment by yxz312** [comment]
这个问题能尽快解决吗？接口的定义都没办法正常保存，问题很严重

**Comment by zyyfit** [comment]
您好，1.10.0版本修复了这个问题，目前是选择json-schema格式保存后，再次打开会展示json-schema格式，切换成json格式则没有数据，想要看json格式的数据可预览查看
