### ISSUE TITLE
[BUG]dubbo请求传入json参数，执行报错

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#24912]
### 联系方式

张树彬

### MeterSphere 版本

2.10LTS

### 使用外置数据库

否

### 问题描述

dubbo请求传入json参数，执行报错。同样的请求和参数在其他测试工具上执行结果正常。（麻烦私联我提供接口参数信息）

### 重现步骤

1. 创建dubbo请求
2. 参数为json
3. 执行后报错
4. 该请求在其他测试工具上执行，执行成功

### 期待的正确结果

执行结果成功

### 附加信息

![Uploading d9ac4fec67a54ee0793bbbaf91536b6.jpg…]()
![image](https://github.com/metersphere/metersphere/assets/77324661/da9114df-30df-4913-89ca-bcc0e765fc32)

**Comment by binbin0406** [comment]
![d9ac4fec67a54ee0793bbbaf91536b6](https://github.com/metersphere/metersphere/assets/77324661/ea4a72e8-90ed-4851-8cf3-fd19ef50afcb)

**Comment by liuruibin** [comment]
1.0 前后去掉引号试过吗
