### ISSUE TITLE
[BUG] UI测试弹框操作，确认不了弹框

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#24921]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

删除用例时，弹框需确认，使用metersphere的弹框操作，弹框未确认

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/3f8353c2-a48f-4469-9e7e-6a511903657b)
![image](https://github.com/metersphere/metersphere/assets/103925124/fa50d785-4c7b-4397-9fc1-d024d135da91)

**Comment by zrfit** [comment]
您好，弹框操作指的是浏览器弹框，而上述场景对应的网页中看似是弹框，实际对应元素是div形式，用鼠标点击-元素定位进行相关操作。

**Comment by fit2cloud-yaochunrong** [comment]
您好，正好使用ui的弹框操作确认不了后，使用鼠标点击确认按钮，报找不到元素，我测的是metersphere功能删除时弹框的确认@zrfit

**Comment by zrfit** [comment]
1、弹框操作指的是alert弹框，ms删除功能用例用-实际对应元素是div形式，用鼠标点击-元素定位是可以删除成功的。
2、alert弹框操作的上一步鼠标点击不要带截图操作是可以成功的，带截图弹框操作会失败为已知需求，计划v3进行调研后看是否可实现。
