### ISSUE TITLE
[BUG]功能用例列表显示用例数量与首页数量不一致

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24928]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

功能用例列表显示用例数量与首页数量不一致

### 重现步骤

1. 功能用例列表数量
![image](https://github.com/metersphere/metersphere/assets/103627487/9905de14-6964-4733-a71b-b0e232903a95)
2. 首页用例数量
![image](https://github.com/metersphere/metersphere/assets/103627487/6720786c-54cd-454e-a069-56ed576cd79f)

**Comment by youliyuan-fit2cloud** [comment]
你好，内部环境没有遇到该问题，是升级之后出现的还是一直存在该问题，如果方便的话需要远程看看实际环境排查问题。

**Comment by janehugit** [comment]
我这边升级到最新版本v2.10.1-lts之后是仪表盘的用例数和功能用例首页的数不一致
![image](https://github.com/metersphere/metersphere/assets/135193527/cebc23b2-67ee-41a7-8757-3e59407bbff0)
![image](https://github.com/metersphere/metersphere/assets/135193527/9c7926de-fa2a-4f91-ac67-92f90c309e04)

**Comment by youliyuan-fit2cloud** [comment]
> 我这边升级到最新版本v2.10.1-lts之后是仪表盘的用例数和功能用例首页的数不一致 ![image](https://user-images.githubusercontent.com/135193527/245977381-cebc23b2-67ee-41a7-8757-3e59407bbff0.png) ![image](https://user-images.githubusercontent.com/135193527/245976998-9c7926de-fa2a-4f91-ac67-92f90c309e04.png)

你好，我的工作台统计是当前用户 有权限的所有项目的总和数据，第二张图是一个项目中的用例数，请再看看其他项目的数据吧。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
