### ISSUE TITLE
[BUG]功能用例点击左右箭头，无反应，回不到模块

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#24927]
### MeterSphere 版本

v1.20.10

### 使用外置数据库

否

### 问题描述

功能用例点击左右箭头，无反应，回不到模块

### 重现步骤

1. 功能用例点击左右箭头，无反应，回不到模块
![image](https://github.com/metersphere/metersphere/assets/103627487/fc0d2009-41e7-4dfa-8398-309a1131f640)

**Comment by youliyuan-fit2cloud** [comment]
请确定复现版本，然后清缓存再试试吧。我们环境没有复现。

**Comment by meijieDouDou** [comment]
在qa 环境，项目:北区测试 可以复现

**Comment by youliyuan-fit2cloud** [comment]
> 在qa 环境，项目:北区测试 可以复现

有没有清缓存那？

**Comment by youliyuan-fit2cloud** [comment]
清缓存后恢复正常。
