### ISSUE TITLE
发送PUT 请求，状态码200，但响应体无任何信息，用其他测试工具（postman、jmeter）响应体有信息

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#24939]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

使用metersphere创建了一个 put 类型的请求方式的接口，测试发送请求，返回状态码200，但响应体无任何信息，使用其他测试工具（postman、jmeter）响应体有信息

### 重现步骤

1. 使用metersphere创建了一个 put 类型的请求方式的接口，测试发送请求；
2. 返回状态码200，但响应体无任何信息；
3. 尝试使用其他测试工具（postman、jmeter），同样的接口和请求参数，响应体返回有信息

### 期待的正确结果

期望使用metersphere平台创建的 put 请求方式接口，发送请求，返回状态码200，且响应体有信息

### 相关日志输出

```shell
无
```

### 附加信息

![1686712928386](https://github.com/metersphere/metersphere/assets/50016789/d19c0980-20a5-44e4-ab7b-48fbf7ab98be)
![1686712928386](https://github.com/metersphere/metersphere/assets/50016789/98acec43-090d-4448-8177-6f7c2b7e91b2)
![image](https://github.com/metersphere/metersphere/assets/50016789/8b138adf-bb77-4c37-b33c-33f3832be65a)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.2-lts修复。

**Comment by Somebody-JIAN** [comment]
您好。 我们使用put自己的put接口，目前没发现有问题。

我们不知道您那边数据的差异在哪里。 您可以对比一下ms的请求内容以及postman的请求内容，看一看差异在哪里

同时，我们发现您postman里出现了乱码。  ms的编码格式应该是UTF-8，不知道您那里有没有可能因为乱码导致了错误

**Comment by spritelyl** [comment]
![image](https://github.com/metersphere/metersphere/assets/50016789/daa252e2-3181-4034-aa4f-072327a1d144)
postman 里面响应体没有乱码

**Comment by spritelyl** [comment]
![image](https://github.com/metersphere/metersphere/assets/50016789/b581d8fd-704d-4f41-998c-c8dd8b4b105b)
postman 响应体里面没有乱码
