### ISSUE TITLE
[BUG]接口自动化，场景内引用多层级场景时，设置场景步骤为“禁用”状态会失效

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#24932]
### 联系方式

张树彬

### MeterSphere 版本

2.10LTS

### 使用外置数据库

否

### 问题描述

接口自动化，场景内引用多层级场景时，设置场景步骤为“禁用”状态会失效，仍然会执行该步骤

### 重现步骤

1. 创建一个接口自动化场景
2. 在一个新的场景中引用场景1
3. 在一个新的场景中引用场景2
4. 在一个新的场景中引用场景3
5. 最后一共是4层场景的引用关系，然后将最下面的场景步骤禁用（可能禁用任意一个场景步骤都可复现，可以试下）
6. 执行当前场景，被禁用的步骤仍然会正常执行

### 期待的正确结果

在当前场景引用场景后，设置步骤禁用后，执行时该步骤应该不再执行

### 附加信息

<img width="606" alt="ce3bf7faa8c2dcbd18516e0b3eddf75" src="https://github.com/metersphere/metersphere/assets/77324661/2cc412c9-6366-42d5-b4da-01a8ccfdd6e3">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
