### ISSUE TITLE
[BUG]测试计划里的功能用例变更记录失效

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#24934]
### 联系方式

18143089490

### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

是

### 问题描述

升级了新版本，再次更新修改了测试计划里的功能用例执行结果，在用例变更记录里，没有新纪录

### 重现步骤

升级了新版本，再次更新修改了测试计划里的功能用例执行结果，在用例变更记录里，没有新纪录

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，可升级到v2.10.1-lts尝试。
