### ISSUE TITLE
[FEATURE]接口定义-请求路径唯一判断

### ISSUE THREAD

**Issue by Ready-cc** [metersphere/metersphere#2494]
**请描述您的需求或者改进建议.**
同路径下query参数不同的接口，无法新增多个接口定义数据

**请描述你建议的实现方案**
建议去掉路径唯一验证
可适用不同客户需求

**Comment by xulinde** [comment]
项目那里可以设置请求路径重复
![image](https://user-images.githubusercontent.com/64065190/116673383-e6c91c80-a9d5-11eb-8ae4-fc69eefb8167.png)

**Comment by Ready-cc** [comment]
额。可以了，谢谢。
