### ISSUE TITLE
[BUG]接口自动化x-www-form-urlencoded格式入参，参数value是json，超长截断导致报错

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#24942]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.x-lts

### 使用外置数据库

否

### 问题描述

见附件接口信息，接口入参是x-www-form-urlencoded格式，参数值是json格式，json里面有中文，需要转义，用${__urlencode()}函数转义后，执行报截断报错，如图2
![报错](https://github.com/metersphere/metersphere/assets/39357523/71670240-5c7a-4751-b9dc-9cb43c5f3292)

### 重现步骤

见附件接口信息，接口入参是x-www-form-urlencoded格式，参数值是json格式，json里面有中文，需要转义，用${__urlencode()}函数转义后，执行报截断报错，参数超数据库长度了，咨询Metersphere交流群的老师说这个是bug，收到请联系我发送接口信息

### 期待的正确结果

可以正常执行

**Comment by zrfit** [comment]
您好，感谢反馈！请将接口信息发送至邮箱rui.zhang@fit2cloud.com。

**Comment by myliuq** [comment]
您好，接口信息见附件




qjiyyn
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口自动化x-www-form-urlencoded格式入参，参数value是json，超长截断导致报错 (Issue #24942)





 
***@***.***。

**Comment by zrfit** [comment]
您好，邮件没收到附件呢，您是哪个交流群的，怎么称呼，我们企业微信沟通下。

**Comment by myliuq** [comment]
能收到邮件吗，做完附件发您了，我在这个群，我微信号是15937004063，可以加我聊哈










qjiyyn
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月16日(星期五) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口自动化x-www-form-urlencoded格式入参，参数value是json，超长截断导致报错 (Issue #24942)





 
您好，邮件没收到附件呢，您是哪个交流群的，怎么称呼，我们企业微信沟通下。

**Comment by myliuq** [comment]
回复的消息显示不了附件，我发的邮件您可能没有收到，我在微信群"MeterSphere 交流群59"里面，叫雨过天晴，我微信号15927004063，您加下我




qjiyyn
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "雨过天晴"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月16日(星期五) 上午10:01
***@***.******@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [metersphere/metersphere] [BUG]接口自动化x-www-form-urlencoded格式入参，参数value是json，超长截断导致报错 (Issue #24942)



能收到邮件吗，做完附件发您了，我在这个群，我微信号是15937004063，可以加我聊哈










qjiyyn
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月16日(星期五) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口自动化x-www-form-urlencoded格式入参，参数value是json，超长截断导致报错 (Issue #24942)





 
您好，邮件没收到附件呢，您是哪个交流群的，怎么称呼，我们企业微信沟通下。

**Comment by zrfit** [comment]
经沟通，为内网环境，测试环境用上述数据mock请求未复现该问题，建议升级到最新版本v2.10.2-lts尝试，如仍存在该问题，可再打开我们继续跟进排查。
