### ISSUE TITLE
[BUG]    v2.10.0-lts  无法加载 metersphere.properties 配置的自定义变量的值。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#24953]
### MeterSphere 版本

  v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

1.  在 /opt/metersphere/conf，添加了一些自定义配置的变量，比如 ms.node.controller.host=10.1.14.202  
2. v2.10.0-lts 之前版本，添加之后可以在自定义封装的jar包中使用。
3. 升级到了v2.10.0-lts 版本，就读取不了了。

 v2.10.0-lts 之前版本效果：
![image](https://github.com/metersphere/metersphere/assets/33945037/1762bfcc-5020-4cb5-8e67-37d9ea7763c2)

 v2.10.0-lts 版本效果：
![image](https://github.com/metersphere/metersphere/assets/33945037/af402349-1204-42ae-9b7a-daa20b087872)

 

### 重现步骤

1. 配置metersphere.properties 文件
2. 写一个jar包，然后上传。
3. 创建接口场景自定义脚本，执行jar包中方法。
4. 看控制台输出

### 期待的正确结果

能够正确读取配置的变量

**Comment by liqiang-fit2cloud** [comment]
由于用户在自定义脚本中调用本地资源可能造成不可预知的后果，所以在v2.10 LTS版本中的进程已改为非root用户运行，并且限制了本地命令的执行和本地文件的读写。
相关的安全公告已经发布：
[GHSA-5473-9v2g-rpqm](https://github.com/metersphere/metersphere/security/advisories/GHSA-5473-9v2g-rpqm)
https://mp.weixin.qq.com/s/vSs7GkZ7deGV1Pmfmpp9RQ
建议考虑别的方式实现，比如环境变量什么的。

**Comment by hao65103940** [comment]
> 由于用户在自定义脚本中调用本地资源可能造成不可预知的后果，所以在v2.10 LTS版本中的进程已改为非root用户运行，并且限制了本地命令的执行和本地文件的读写。 相关的安全公告已经发布： [GHSA-5473-9v2g-rpqm](https://github.com/metersphere/metersphere/security/advisories/GHSA-5473-9v2g-rpqm) https://mp.weixin.qq.com/s/vSs7GkZ7deGV1Pmfmpp9RQ 建议考虑别的方式实现，比如环境变量什么的。

既然无法读写，那么是不是在metersphere.properties配置的参数都不生效了呢？ 比如配置的 spring.datasource.hikari.maximum-pool-size 这些配置。

**Comment by wan92hen** [comment]
当前版本已经不会给 node-controller 挂载 /opt/metersphere/conf 目录了，如果需要修改 node-controller 的配置，可以通过配置环境变量或挂载单独配置文件的方式处理。

**Comment by hao65103940** [comment]
> 要修改 node-control
我的问题是，如果在metersphere.properties 添加了一些配置，比如spring.datasource.hikari.maximum-pool-size ，eureka.instance.instance-id 等一些 springboot里面 相关配置，是不会生效的吗？
