### ISSUE TITLE
[BUG]从测试报告邮件里面连接打开的报告页面查看结果一直转圈圈

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#24957]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.x-lts

### 使用外置数据库

否

### 问题描述

执行测试计划给邮箱发送测试报告，打开报告里面的连接，测试报告里面的结果一直转圈圈打不开

### 重现步骤

执行测试计划给邮箱发送测试报告，打开报告里面的连接，测试报告里面的结果一直转圈圈打不开，从metersphere站点测试报告进去看结果可以正常查看
![图片](https://github.com/metersphere/metersphere/assets/39357523/2baa22a2-f6bd-4213-876b-0ae98778be05)

### 期待的正确结果

从邮件里面的测试报告连接可以正常查看报告

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，待v1.20.4-lts发布后尝试。
