### ISSUE TITLE
[BUG]基于UI测试，在使用输入操作步骤时，使用变量属性有问题。

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#24966]
### 联系方式

15275908957

### MeterSphere 版本

1.20.23-lts

### 使用外置数据库

否

### 问题描述

UI测试，使用输入操作步骤，在元素定位使用xpath，定位值使用，${}，变量，输入内容不填写变量，填写正常的值，本地调试报错。

### 重现步骤

1.创建步骤一，打开网页，连接填写http://baidu.com
2.在步骤一中，使用js脚本返回值为百度输入框的xpath变量，变量名任意
3.创建步骤二，在元素定位中填写上一步的变量名
4.输入框内，填写正常数字或者字符串
5.本地调试
<img width="1253" alt="image" src="https://github.com/metersphere/metersphere/assets/66937739/036211dd-493d-488b-a476-714effa70927">

### 期待的正确结果

这个问题在2.10-lts中没有复现，期望与2.10-lts保持一致。

**Comment by zrfit** [comment]
您好，感谢反馈！通过文件发现，多个变量名称相同，请尽量规避命名相同的变量。不同变量名出，引用是正常的。
