### ISSUE TITLE
[BUG]测试计划的消息通知executionTimes变量无效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#24968]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

测试计划的消息通知executionTimes变量无效

### 重现步骤

1.配置测试计划消息通知，模版中使用executionTimes变量
![image](https://github.com/metersphere/metersphere/assets/88763608/a49cd0b2-751d-42b4-8762-104358638cee)

2.实际发送的通知中，这个变量没有值
<img width="521" alt="2c2a1954e6d780f46de1d868be0ef66" src="https://github.com/metersphere/metersphere/assets/88763608/d153ade9-35c3-4a7e-8df9-2b0521b74bab">

### 期待的正确结果

应该有值

**Comment by youliyuan-fit2cloud** [comment]
你好，该参数已不再适用，后续版本会在模版中删掉。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.2-lts中已移除该变量。
