### ISSUE TITLE
[QUESTION]为什么我安装部署之后，不管在线还是离线，重启服务器都不能自动启动呢？

### ISSUE THREAD

**Issue by zyx030613** [metersphere/metersphere#24961]
### 请描述您的问题

在线和离线安装都试了，官方客服小姐姐还特意加我微信问我为什么要一天内下载三次。
安装完没问题，重启服务器就不行
msctl start
Starting redis              ... done
Starting minio              ... done
Starting prometheus         ... done
Starting kafka              ... done
Starting data-streaming     ... done
Starting node-controller    ... done
Starting nodeexporter       ... done
Starting eureka             ... done
Starting gateway            ... done
Starting mysql              ... done
Starting system-setting     ... done
Starting report-stat        ... done
Starting workstation        ... done
Starting test-track         ... done
Starting api-test           ... done
Starting performance-test   ... done
Starting project-management ... done
ERROR: No containers to start
我没用过docker，请帮忙看下怎么启动

**Comment by liuruibin** [comment]
我们默认是自行启动所有的容器的，您是用root用户进行操作的吗？防火墙和selinux都是关闭状态吗

**Comment by zyx030613** [comment]
我关闭了防火墙，关闭了selinux，重启了系统，重启后8081是开启的，过一会就关闭了，有什么日志能看吗？输入msctl命令如下：[root@localhost ~]# msctl status

Name   Command   State   Ports
------------------------------
[root@localhost ~]# msctl ps

Name   Command   State   Ports
------------------------------

**Comment by zyx030613** [comment]
我在/opt/metersphere/logs/metersphere目录下找到了今天打印的日志，
[info.log](https://github.com/metersphere/metersphere/files/11766622/info.log)
我看里面是有error的，请帮忙看看是这个导致的吗

**Comment by luty2018** [comment]
请问问题还存在吗？

**Comment by luty2018** [comment]
如果问题还存在， 您可以重新开启或新创建issue。
