### ISSUE TITLE
[BUG]metersphere部署多个api服务节点之后进行接口测试无法收到响应

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#24978]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

是

### 问题描述

通过2.7.1分支的源码打包镜像，在服务器上部署了eureka、gateway、setting、project、api、workstation、track、performance、report这些服务，当api服务的节点只有一个的时候服务运行正常，当部署两个api服务的节点，在界面点击接口测试，一直收不到后台的响应，但是在测试报告的地方可以看到请求成功，怀疑是否是websocket的问题

### 重现步骤

1、部署服务，采用同一套conf配置和redis配置
2、api服务部署两个节点，
3、在界面点击接口测试，发现一直没有收到响应
4、下图为请求的报文以及部署的服务（由于github上传有问题，下述链接为外部链接，有效期三天）
https://free.wzznft.com/i/2023/06/15/s7u9n9.png
https://free.wzznft.com/i/2023/06/15/s8dklg.png
https://free.wzznft.com/i/2023/06/15/s8e3ws.png

**Comment by liqiang-fit2cloud** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。
我这里先把issue关掉。
如果后面你用官方镜像和官方安装方式再出现问题可以再打开issue。
另外v2.7.1已经不在维护，请升级到最新的LTS版本。

**Comment by sfihp** [comment]
debug请求和 websocket 是2个连续的接口调用，如果nginx配置是平均分发策略，就会有建立websocket在debug机器外的那个机器上 ， 出现这样的问题可以是用iphash策略，保持链接就可以了。
