### ISSUE TITLE
[BUG]自定义jar包删除后，该jar包中的方法仍旧可以调用

### ISSUE THREAD

**Issue by SniperCN** [metersphere/metersphere#24975]
### MeterSphere 版本

v1.20.23-lts-77e58286

### 使用外置数据库

是

### 问题描述

+ 1，自定义jar包上传成功后，jar包内方法调用失败，重启服务后调用成功
+ 2，自定义jar包删除成功后，jar包内方法仍旧可以成功调用
+ 3，自定义jar包删除后，新增java类中的方法，重新打包上传（包名不变），新方法调用失败

### 重现步骤

1，在系统设置->项目管理页面上传jar包
2，直接在case前置操作beanshell中导入目标类，并调用目标方法，然后执行case，beanshell执行失败，提示类未定义（期望：beanshell执行成功）
3，重启服务后再次执行case，beanshell执行成功
4，在系统设置->项目管理页面删除步骤1中上传的jar包，重启服务后执行步骤2中的case，beanshell正常执行（期望：beanshell执行失败）
5，在步骤2中所导入的类中新增方法，重新打包并上传，然后重启服务
6，在步骤2中的case的beanshell中调用步骤5中新增的方法，执行case，beanshell执行失败，提示方法未找到（期望：beanshell执行成功）

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现，方便把自定义jar包发出来吗？

**Comment by SniperCN** [comment]
这个问题出现的始末是这样的，我自定义jar包中的class A有两个重载方法：B(String a, String b)    C(String a, String b, String c)
我在1.20.1x.lts版本中正常使用，然后我把metersphere的版本从1.20.1x.lts在线升级至v1.20.23-lts，发现方法C调用失败（提示方法未找到，从服务器../metersphere/data/jar/中下载jar包反编译确认方法是存在的）；再尝试调用方法B，执行成功
后续我做了以下步骤尝试处理：
1，在metersphere系统设置->项目管理页面操作删除jar包，重启服务后再重新上传，问题未解决（过程中发现，jar包删除且服务重启后，方法B仍可以正常调用）
2，更改class A所属包名，打包上传，问题临时解决

最后，我重新写了附件中的demo，上传metersphere进行测试，问题复现：


***@***.***
 
发件人： MatataYou
发送时间： 2023-06-16 10:13
收件人： metersphere/metersphere
抄送： SniperCN; Author
主题： Re: [metersphere/metersphere] [BUG]自定义jar包删除后，该jar包中的方法仍旧可以调用 (Issue #24975)
你好，我们没有复现，方便把自定义jar包发出来吗？

**Comment by SniperCN** [comment]
最后，我重新写了附件中的demo，上传metersphere进行测试，问题复现：
1，首次上传，类中方法可正常调用
2，删除jar包，并且在类中新增方法B，重新打包上传，方法B调用失败（提示方法未找到）




***@***.***
 
发件人： ***@***.***
发送时间： 2023-06-16 11:02
收件人： metersphere/metersphere
主题： Re: Re: [metersphere/metersphere] [BUG]自定义jar包删除后，该jar包中的方法仍旧可以调用 (Issue #24975)
这个问题出现的始末是这样的，我自定义jar包中的class A有两个重载方法：B(String a, String b)    C(String a, String b, String c)
我在1.20.1x.lts版本中正常使用，然后我把metersphere的版本从1.20.1x.lts在线升级至v1.20.23-lts，发现方法C调用失败（提示方法未找到，从服务器../metersphere/data/jar/中下载jar包反编译确认方法是存在的）；再尝试调用方法B，执行成功
后续我做了以下步骤尝试处理：
1，在metersphere系统设置->项目管理页面操作删除jar包，重启服务后再重新上传，问题未解决（过程中发现，jar包删除且服务重启后，方法B仍可以正常调用）
2，更改class A所属包名，打包上传，问题临时解决

最后，我重新写了附件中的demo，上传metersphere进行测试，问题复现：


***@***.***
 
发件人： MatataYou
发送时间： 2023-06-16 10:13
收件人： metersphere/metersphere
抄送： SniperCN; Author
主题： Re: [metersphere/metersphere] [BUG]自定义jar包删除后，该jar包中的方法仍旧可以调用 (Issue #24975)
你好，我们没有复现，方便把自定义jar包发出来吗？

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，这个版本确实存在该问题，建议升级到最新的v2.10.2-lts 版本（明天发布），感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
