### ISSUE TITLE
[FEATURE]  测试计划和功能用例填写表单信息中的“责任人”字段是否可以默认设置为登录用户

### ISSUE THREAD

**Issue by limin-fit2** [metersphere/metersphere#24989]
### MeterSphere 版本

v2.10.0-lts-89acace0

### 请描述您的需求或者改进建议

创建功能用例和测试计划填写的表单信息中，责任人字段是否能默认为当前登录用户（接口测试场景表单会自动带入当前登录用户信息，无需再次下拉选择）
![image](https://github.com/metersphere/metersphere/assets/61964761/8e28b15c-f86c-440e-a816-36010f90d6d7)

**Comment by luty2018** [comment]
可以的 ，您在项目设置-模板管理中， 选择用例模板指定责任人为创建人就可以了。

**Comment by limin-fit2** [comment]
已设置，后续版本时候能在默认模版中直接配置好“创建人”属性，这样就避免需要在人为设置一次，也可以和其他模版保持统一

**Comment by luty2018** [comment]
默认现在的逻辑哈
