### ISSUE TITLE
[FEATURE] 1.9.0 增加topic未更新官网说明

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2498]
**请描述您的需求或者改进建议.**

1. 突然增加topic导致使用运维kafka告警（运维kafka不允许直接创建topic）.
2. 新增运行的容器作用没有在官网说明

**请描述你建议的实现方案**

**Comment by fit2-zhao** [comment]
@guhan121  您这边之前的topic 是申请运维创建的吗，如果走的运维流程，那么新版需要新增topic： ms-api-exec-topic；Partition个数根据实际而定；这个topic会用于接口自动化 分布式执行的消息处理。

**Comment by guhan121** [comment]
@fit2-zhao 是的 topic 要到运维申请；然后我直接升级；运维那边报警电话就不停；直接被运维找上门了。
