### ISSUE TITLE
[BUG]对接禅道可以双向同步缺陷（开源版）

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#24983]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v2.10.1-lts版本

### 使用外置数据库

否

### 问题描述

1、正常对接禅道
2、测试跟踪-缺陷管理页面对接禅道
3、点击同步缺陷可以同步所有的禅道缺陷到MeterSphere平台中
![image](https://github.com/metersphere/metersphere/assets/35896106/852c42db-4435-467e-8485-02960d629de8)

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，最新版本v2.10.2没有复现该问题。
