### ISSUE TITLE
[BUG]【权限问题】创建用户给定用户指定项目管理员或项目成员权限，系统设置项目管理页面确可以看到所有项目并修改

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#24987]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v2.10.1-lts版本

### 使用外置数据库

否

### 问题描述

1、创建用户并给与指定项目管理员（默认项目）或者项目成员（默认项目）权限
![image](https://github.com/metersphere/metersphere/assets/35896106/e55d2ccc-1618-4089-8b79-127a016d0b14)
2、使用给用户登陆，点击系统设置-项目管理，可以看到所有项目
![image](https://github.com/metersphere/metersphere/assets/35896106/7a05c650-ce0a-4276-84de-b581912a65e1)
3、同时可以对其他项目环境进行更改
![image](https://github.com/metersphere/metersphere/assets/35896106/29348136-0e55-40a1-bfb4-2325f3c085b5)

### 重现步骤

同上

### 期待的正确结果

给定指定项目管理员或者项目成员角色，系统设置-项目管理那边只能看到和管理自己的项目

**Comment by 13290445582** [comment]
感谢反馈，因为给用户分配项目成员/项目管理员会默认分配工作空间成员/工作空间管理员，所以可以看到该工作空间下所有项目。
修改其他项目环境问题未复现，您等待v2.10.2发布后进行尝试。

**Comment by 13290445582** [comment]
您好，请升级至最新版本，查看下是否存在该问题。

**Comment by weishuo6** [comment]
升级到最新2.10.2-tls版本还是会有这个问题，我大概知道原因了。

默认工作空间成员的权限就具备环境配置的权限，所以项目管理员或者项目成员可以看到所有项目并修改其他项目的环境配置，把这个权限去掉后就不能修改了，所以这块没啥问题了。

PS：另外一个问题，个人理解项目成员或者项目管理员，在系统设置那边也只能看到自己所在的项目才对，不应该看到所有的




***@***.***
 
发件人： wangyicheng
发送时间： 2023-06-25 14:31
收件人： metersphere/metersphere
抄送： weishuo6; Author
主题： Re: [metersphere/metersphere] [BUG]【权限问题】创建用户给定用户指定项目管理员或项目成员权限，系统设置项目管理页面确可以看到所有项目并修改 (Issue #24987)
您好，请升级至最新版本，查看下是否存在该问题。

**Comment by 13290445582** [comment]
您好，在给用户分配项目成员/项目管理员用户组时，会自动分配工作空间成员/工作空间管理员用户组，所以该用户可以看到该工作空间下所有项目，若无其他问题将关闭该issue。
