### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ZhixingWang** [metersphere/metersphere#24986]
### MeterSphere 版本

MeterSphere Recorder 版本 1.2.4

### 联系方式

王工 andy.sh@qq.com

### 请描述您的需求或者改进建议

可以把返回的消息体(responsed message) 也保存下来吗？
很多时候，需要解析返回的消息体，并从中提取信息，给后续请求使用。
主要是为了方便静态分析。因为手工调用/调试的时候，发过去的参数的是动态的，可能都不对，拿不到正确的响应消息体。

**Comment by luty2018** [comment]
请您升级到v2.10 LTS版本
