### ISSUE TITLE
是否可以支持在别的平台（如：jira）粘贴用例时，用例ID能附带超链接，便于点击用例ID即可跳转至Metersphere上的用例

### ISSUE THREAD

**Issue by chyhant** [metersphere/metersphere#24988]
### MeterSphere 版本

v2.10.1

### 请描述您的需求或者改进建议

使用过程中发现：
1、目前用例的ID有超链接，但是如果要在其他平台批量关联用例，仅能显示用例ID，无超链接，无法跳转，导致两个系统间无法交互，体验不友好，期望能优化下，谢谢！
例如：
在复制或导出测试报告时，支持导出为excel表格式，附带超链接！

### 请描述你建议的实现方案

在复制或导出测试报告时，支持导出为excel表格式，附带超链接！
![image](https://github.com/metersphere/metersphere/assets/22338833/e9c8bcf8-511c-402d-a937-355f5cde8699)

**Comment by luty2018** [comment]
感谢建议， 这个已经规划了。

**Comment by chyhant** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
