### ISSUE TITLE
[BUG]mock数据里面@dataImage没有起作用

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#24994]
### MeterSphere 版本

v1.20.15

### 使用外置数据库

否

### 问题描述

场景变量：
![image](https://github.com/metersphere/metersphere/assets/31870788/1799f893-42bc-45aa-9fa3-8a70a2466592)

请求：
![image](https://github.com/metersphere/metersphere/assets/31870788/48c0e287-82f7-41ef-81d3-b4f908851c73)

响应：
![image](https://github.com/metersphere/metersphere/assets/31870788/bf8e6f7c-63cc-4792-89ec-0773beee333a)

### 重现步骤

如上

**Comment by zrfit** [comment]
您好，感谢反馈！已反馈给研发，确认后回复。

**Comment by zrfit** [comment]
您好，感谢反馈！metersphere后端调用的jmeter，jmeter不支持该函数，v2.10.4-lts已优化去掉该函数，建议使用其它函数或者升级到最新版本。
