### ISSUE TITLE
[BUG] 功能用例的变更记录不可读，内容展示错乱

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#24999]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

是

### 问题描述

1，在测试计划中，在列表上，直接修改用例状态后，在用例的修改记录中，没有记录
2，在测试计划中，在用例详情里，修改用例状态，在用例的修改记录中，有记录，但不太可读，信息错乱，有些没有变化的字段，显示发生了变化，比如，创建人，备注，实际变更后的用例状态，展示到了变更前内容的列里，有些变更后的内容，展示了一些莫名其妙的内容，比如用例标题

### 重现步骤

1，在测试计划中，在列表上，直接修改用例状态后，在用例的修改记录中，没有记录
2，在测试计划中，在用例详情里，修改用例状态，在用例的修改记录中，有记录，但不太可读，信息错乱，有些没有变化的字段，显示发生了变化，比如，创建人，备注，实际变更后的用例状态，展示到了变更前内容的列里，有些变更后的内容，展示了一些莫名其妙的内容，比如用例标题

**Comment by locust-zhang** [comment]
![Snipaste_2023-06-19_08-46-40](https://github.com/metersphere/metersphere/assets/84962582/82674558-6847-4dd4-94ac-00a48d6a17ef)

**Comment by 13290445582** [comment]
您好，可以提供下您复现的录屏视频嘛，帮助进行复现。

**Comment by locust-zhang** [comment]
Filmage 2023-06-20_132643.mp4

**Comment by locust-zhang** [comment]
> 您好，可以提供下您复现的录屏视频嘛，帮助进行复现。


https://github.com/metersphere/metersphere/assets/84962582/87fb2e3f-8bcd-469d-b8f6-d1443c46215d

**Comment by 13290445582** [comment]
感谢，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
