### ISSUE TITLE
[BUG]接口测试，响应内容大，接口无法停止

### ISSUE THREAD

**Issue by gaosongtao1994** [metersphere/metersphere#24993]
### 联系方式

19211099410@163.com

### MeterSphere 版本

v2.10.1-lts-65fad062

### 使用外置数据库

否

### 问题描述

接口：http://zhangjiakou-gis.ncmewater.com/api/business/ZHANGJIAKOU/facilities/category/GX/geometry/1/details
POST data:
{"fields":["LINKCODE","FNID1","FNID2","LENGTH","CATEGORY","IN_CODE","OUT_CODE","IN_ELE","OUT_ELE","COV_SOIL","MATERIAL","CALIBER","STYLE","FILLER","IN_CORRO","COATING","OUT_CORRO","ROUGH_DATE","ROUGH_N","ROUGH_C","PRESSURE","LANE_WAY","GALLERY","LEVEL","STATUS","DATE","CLASS","DISTRICT","COMMUNITY","DATA","REMARK","GEO_INELE","GEO_OUTELE"]}

现象：结果无法停止。postman和jmeter测试此接口无异常
初步分析，响应内容大，前端无法加载

### 重现步骤

metersphere调用接口：http://zhangjiakou-gis.ncmewater.com/api/business/ZHANGJIAKOU/facilities/category/GX/geometry/1/details
POST data:
{"fields":["LINKCODE","FNID1","FNID2","LENGTH","CATEGORY","IN_CODE","OUT_CODE","IN_ELE","OUT_ELE","COV_SOIL","MATERIAL","CALIBER","STYLE","FILLER","IN_CORRO","COATING","OUT_CORRO","ROUGH_DATE","ROUGH_N","ROUGH_C","PRESSURE","LANE_WAY","GALLERY","LEVEL","STATUS","DATE","CLASS","DISTRICT","COMMUNITY","DATA","REMARK","GEO_INELE","GEO_OUTELE"]}

### 期待的正确结果

正常显示，接口正常停止

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/135119736/ebb5ba9f-57ac-491e-8a34-034104ca807d)

**Comment by zrfit** [comment]
您好，感谢反馈！无法调用此接口，请提供下响应数据。

**Comment by gaosongtao1994** [comment]
抱歉，路径写错了，接口路径：https://zhangjiakougis.ncmewater.com/api/business/ZHANGJIAKOU/facilities/category/GX/geometry/1/details

post 参数：{"fields":["LINKCODE","FNID1","FNID2","LENGTH","CATEGORY","IN_CODE","OUT_CODE","IN_ELE","OUT_ELE","COV_SOIL","MATERIAL","CALIBER","STYLE","FILLER","IN_CORRO","COATING","OUT_CORRO","ROUGH_DATE","ROUGH_N","ROUGH_C","PRESSURE","LANE_WAY","GALLERY","LEVEL","STATUS","DATE","CLASS","DISTRICT","COMMUNITY","DATA","REMARK","GEO_INELE","GEO_OUTELE","DISTRICT"]}

**Comment by zrfit** [comment]
您好，感谢反馈！消息内容过大，可修改kafka配置后尝试。
![image](https://github.com/metersphere/metersphere/assets/99731894/7163e36a-5554-4b41-80be-f9ff4f31a0f8)

**Comment by gaosongtao1994** [comment]
![image](https://github.com/metersphere/metersphere/assets/135119736/9c60eede-64ae-4ab6-a65a-0fbd80b0c5f3)
![image](https://github.com/metersphere/metersphere/assets/135119736/205a0066-1778-42fc-a270-614aad544dd7)
已更新版本，已修改kafka配置，BUG未修复

**Comment by zrfit** [comment]
您好，请提供下后端日志，按截图建议的配置我们环境验证是可以返回结果的。

<img width="1340" alt="image" src="https://github.com/metersphere/metersphere/assets/70558837/b68caa21-7ea2-4245-925f-6ac1603eebf8">

**Comment by gaosongtao1994** [comment]
在 2023-07-06 17:42:17，"zrfit" ***@***.***> 写道：

您好，请提供下后端日志。

**Comment by gaosongtao1994** [comment]
链接: https://pan.baidu.com/s/1Hs8eY1i3wHCv0gzS1ah4iA 提取码: 1234  日志请下载一下

**Comment by fit2-zhao** [comment]
在 /opt/metersphere/conf/metersphere.properties 中添加参数 spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=209715200 然后重启服务看看效果。

**Comment by gaosongtao1994** [comment]
修改了api-test配置，mem_limit: 2g # default 1g bytes，现在可以了，bug可以关闭

**Comment by zrfit** [comment]
好的，感谢！
