### ISSUE TITLE
[BUG]接口测试，执行计划时 当请求在循环控制器内，失败了就不会重试

### ISSUE THREAD

**Issue by chn2987** [metersphere/metersphere#24996]
### 联系方式

18520103625

### MeterSphere 版本

 v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

接口测试，执行计划时，当请求在循环控制器内，失败了就不会重试

### 重现步骤

1.新建场景，添加循环控制器
2.在循环控制器内添加请求
3.设置断言为失败
4.创建计划，添加该场景
5.执行时，开启失败重试
![image](https://github.com/metersphere/metersphere/assets/32096198/25b0c567-4c88-432f-b3f1-334e9170eb89)

### 期待的正确结果

循环内的请求失败了，也需要重试

**Comment by fit2-zhao** [comment]
感谢您的建议，目前设计如此，循环控制器内不会重试。
