### ISSUE TITLE
字体模糊，难以看清，看的眼睛疼[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#2499]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9

**Bug 描述**
简要描述您碰到的问题
用例的字体怎么变模糊,印象中更新1.9之前，看的比较清晰的

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
字体清晰可见

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/117238275-23c26280-ae5f-11eb-91c2-e53bae83e7a0.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本优化下

**Comment by jhong123** [comment]
+1

**Comment by xulinde** [comment]
1.9.2已修复
