### ISSUE TITLE
[BUG]MOCK后置脚本for循环没有生效

### ISSUE THREAD

**Issue by myliuq** [metersphere/metersphere#24998]
### 联系方式

15927004063

### MeterSphere 版本

v1.20.21-lts

### 使用外置数据库

否

### 问题描述

MOCK第三方接口，mock接口的返回值为接口请求体里面的值，请求体里有多个数据值，所以返回值需要取到请求体的值循环赋值，用MOCK后置脚本进行处理，但是用for循环没有生效，运行还是空的，如图

### 重现步骤

MOCK第三方接口，mock接口的返回值为接口请求体里面的值，请求体里有多个数据值，所以返回值需要取到请求体的值循环赋值，用MOCK后置脚本进行处理，但是用for循环没有生效，运行还是空的，如图，具体的脚本请联系我发送，这里发不了附件，谢谢，辛苦了，我的微信是15927004063

### 期待的正确结果

MOCK可以正常处理这种场景，达到模拟测试的目标

**Comment by myliuq** [comment]
![mock后置脚本](https://github.com/metersphere/metersphere/assets/39357523/a0c24eae-ff76-457c-bac6-6ceb014dcaa2)

**Comment by myliuq** [comment]
![调试](https://github.com/metersphere/metersphere/assets/39357523/7b5d8d5e-c104-4137-8fbb-89f9b11b40af)

**Comment by myliuq** [comment]
![运行](https://github.com/metersphere/metersphere/assets/39357523/37f15bb6-6495-4f67-80b6-613d327d15cb)

**Comment by myliuq** [comment]
![调试](https://github.com/metersphere/metersphere/assets/39357523/3d064549-65ba-4269-b5d0-b7a2898c9fc5)
实际运行mock接口返回的oihckqunsz数组为空，调试mock接口是有值的，请忙不排查为什么运行起来就没有for循环的赋值了

**Comment by zrfit** [comment]
您好，复制提供下您的全部后置脚本看下。

**Comment by myliuq** [comment]
已经解决，谢谢哈




qjiyyn
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月20日(星期二) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]MOCK后置脚本for循环没有生效 (Issue #24998)





 
您好，复制提供下您的全部后置脚本看下。
