### ISSUE TITLE
[FEATURE]持续交付上，我希望可以增加通过判断接口测试定时任务的执行结果来决定是否发送测试报告到对应用户的邮箱，做到每天线上回归可以监控及时发现问题

### ISSUE THREAD

**Issue by songxt01** [metersphere/metersphere#250]
**请描述您的需求或者改进建议.**

持续交付上，我希望可以增加通过判断接口测试定时任务的执行结果来决定是否发送测试报告到对应用户的邮箱，做到每天线上回归可以监控及时发现问题，失败就打电话给对应项目的负责人

**请描述你建议的实现方案**
希望增加入口：
1、凡是配置了定时任务的项目或者接口用例，能够增加选项（1、测试结果失败才发送邮件测试报告，且打电话给对应项目的负责人告诉他出错了，2、不管项目测试结果是不是失败，都会发送邮件测试报告，执行失败就打电话），这样每天通过定时任务能及时发现线上问题
非常感谢 @飞致云  的全体工作人员

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 持续交付上，我希望可以增加通过判断接口测试定时任务的执行结果来决定是否发送测试报告到对应用户的邮箱，做到每天线上回归可以监控及时发现问题，失败就打电话给对应项目的负责人
> 
> **请描述你建议的实现方案**
> 希望增加入口：
> 1、凡是配置了定时任务的项目或者接口用例，能够增加选项（1、测试结果失败才发送邮件测试报告，且打电话给对应项目的负责人告诉他出错了，2、不管项目测试结果是不是失败，都会发送邮件测试报告，执行失败就打电话），这样每天通过定时任务能及时发现线上问题
> 非常感谢 @飞致云 的全体工作人员

发邮件可以做， 打电话就暂时不考虑呢

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
