### ISSUE TITLE
[BUG]v2.10.1，脑图模式 新建的测试用例保存后 -责任人-默认是空的 

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#25001]
### 联系方式

王进

### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

v2.10.1，脑图模式 新建的测试用例保存后 -责任人-默认是空的 

### 重现步骤

1. 切换到脑图模式，新建一个功能用例，保存。
2. 切换到列表视图，进入用例详情页，
3. 责任人是空的。----客户希望脑图模式创建的用例，责任人是当前操作用户。

### 附加信息

意向客户反馈的缺陷。

**Comment by 13290445582** [comment]
感谢反馈，经过复现，测试环境下脑图模式创建用例责任人为当前操作用户，建议待发布v2.10.2后升级尝试～

**Comment by 35plus** [comment]
感谢

**Comment by 13290445582** [comment]
您好，该问题在最新环境未复现，若升级到最新环境还存在该问题，请重新提issue。
