### ISSUE TITLE
[BUG]功能用例启用版本管理后，创建用例时可以选择版本，但是编辑用例时就没办法选择用例版本了。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#25009]
### 联系方式

王进

### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

功能用例启用版本管理后，创建用例时可以选择版本，但是编辑用例时就没办法选择用例版本了。

### 重现步骤

1. 创建功能用例：
<img width="1226" alt="1687145469440" src="https://github.com/metersphere/metersphere/assets/76033005/1f8a1f88-7749-4c39-bf63-4aa9f308114d">

2. 编辑用例时，无法选择了，客户希望在编辑用例时候，可以对版本字段也进行选择编辑。

**Comment by 13290445582** [comment]
感谢反馈，不支持编辑版本，若需要其他版本，您可以选择新建版本，谢谢。
