### ISSUE TITLE
[BUG]测试计划，执行功能用例，点击添加缺陷，弹出的页面太小，尤其是如果用户MS对接了jira，会出现字段布局变形不好用的情况。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#25003]
### 联系方式

王进

### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

测试计划，执行功能用例，点击添加缺陷，弹出的页面太小，尤其是如果用户MS对接了jira，会出现字段布局变形不好用的情况。

### 重现步骤

1. 进入测试计划，执行功能用例
2. 在"关联缺陷” tab页面，点击添加缺陷。
3. 如果MS对接了jira，弹出的页面布局非常不好用。客户希望页面size能大点。

<img width="1280" alt="1687142188503" src="https://github.com/metersphere/metersphere/assets/76033005/5783d2c4-35dd-43f0-8070-c0c7c155bcf1">

### 附加信息

意向客户

**Comment by 35plus** [comment]
截图是我们测试环境截图，客户那边 缺陷字段有十几个，在这个size的页面显示非常局促。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/8765acc9-257d-437c-bd05-5c9f4405b5d0)
你好，我们用的jira看起来正常的。如果哪里觉得不好请上传实际用户截图。

**Comment by 35plus** [comment]
<img width="848" alt="823814b9b1becbf3349ff6d0cf0aead" src="https://github.com/metersphere/metersphere/assets/76033005/2b8331f5-be25-410f-ae8a-26d84d29e307">

**Comment by 35plus** [comment]
<img width="848" alt="823814b9b1becbf3349ff6d0cf0aead" src="https://github.com/metersphere/metersphere/assets/76033005/906b1d14-fa02-453d-ac13-b95f20ae1cbd">

**Comment by 35plus** [comment]
<img width="541" alt="1687314665524" src="https://github.com/metersphere/metersphere/assets/76033005/5f05042d-15c1-4dec-b855-966a8c58339e">

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中做了优化，可以最大化该页面。
