### ISSUE TITLE
[FEATURE]功能用例的脑图第一次进入选择某节点时建议不要自动展开

### ISSUE THREAD

**Issue by janehugit** [metersphere/metersphere#25004]
### MeterSphere 版本

 v2.10.0-lts

### 请描述您的需求或者改进建议

第一次进入功能用例的脑图模式时，选择某节点时，该节点如果有子节点则会自动展开，当使用场景时进入脑图模式想通过鼠标框选多个根节点时，多有节点都会自动展开，导致多选使用不是很方便，而且当折叠节点之后，再次框选是不会展开的
![image](https://github.com/metersphere/metersphere/assets/135193527/aaad0492-db1d-49dd-9e37-d749b4033d72)
![image](https://github.com/metersphere/metersphere/assets/135193527/c6c4a453-09d5-4a3c-88b7-6e5df1963281)

### 请描述你建议的实现方案

建议第一次进入脑图模式时，选择节点不要自动展开
![image](https://github.com/metersphere/metersphere/assets/135193527/cf260129-1b28-45d4-b07d-2d01cb4445c3)

**Comment by luty2018** [comment]
感谢反馈， 这个我们在v3.0会优化。

**Comment by luty2018** [comment]
v3.0 已支持， 可以升级使用。
