### ISSUE TITLE
[BUG]【功能用例】自定义模板字段为文本框，然后新建用例时填入一个大的json串保存。选中该用例-“复制到”某目录，点击复制后的用例查看，发现原本的字段值大json串没被复制过来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25016]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【功能用例】自定义模板字段为文本框，然后新建用例时填入一个大的json串，进行保存。选中该用例-点击“复制到”某目录，点击复制后的用例查看，发现原本的字段值大json串没被复制过来

### 重现步骤

【功能用例】自定义模板字段为文本框，然后新建用例时填入一个大的json串，进行保存。
![image](https://github.com/metersphere/metersphere/assets/104960608/4a2cf1f4-d2e2-4b7b-b8e3-14b75ad826d2)
选中该用例-点击“复制到”某目录，点击复制后的用例查看，发现原本的字段值大json串不见了
![image](https://github.com/metersphere/metersphere/assets/104960608/bbca31e9-bc9f-4061-a43e-97e69c2cc8df)
![image](https://github.com/metersphere/metersphere/assets/104960608/b1db3561-1a94-4d27-8a8b-c27f39378be5)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
