### ISSUE TITLE
[BUG]  【接口定义】当删除接口case到回收站的时候，回收站统计数量不对

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25018]
### MeterSphere 版本

v2.1.1

### 使用外置数据库

否

### 问题描述

1. 创建接口，创建接口case。
2. 删除case，刷新页面，回收站统计数量不对。
3. 实际是有case的，但是统计数量为0
4. 只有点回收站里面，切换case才能看到
<img width="489" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/25115354-4c7b-4343-bdab-1d5412f7ef93">
<img width="1170" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/8dd5989c-cebc-4cc9-9c43-7325b9808105">

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
你好，这个统计的是删除的接口定义数量，不是接口case的。
