### ISSUE TITLE
[BUG]与jira集成，在jira中创建的字段为二级列表类型，该字段内容在ms系统中可以正常显示，但是导出内容是错误的

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#25014]
### 联系方式

张树彬

### MeterSphere 版本

2.10lst

### 使用外置数据库

否

### 问题描述

与jira集成，在jira中创建的字段为二级列表类型，该字段内容在ms系统中可以正常显示，但是导出内容是错误的

### 重现步骤

1. 配置ms与jira集成
2. 在jara中创建字段，字段类型为二级列表
3. 在jira或ms端创建缺陷，正常选择该字段二级列表内容，保存或同步缺陷
4. 在ms中查看该 字段显示的二级列表内容正确
5. 在ms中选中该条缺陷，点击导出
6. 导出文件中，该字段的二级列表内容显示为错误编号，并未显示真正的字段内容

### 期待的正确结果

希望该字段类型导出后，也可以在本地文件中正常显示其内容

### 附加信息

![Uploading b53088354f77ff929f1d4c79bb48ee9.jpg…]()

**Comment by binbin0406** [comment]
![1687159260848](https://github.com/metersphere/metersphere/assets/77324661/5106401f-3845-4665-aeef-5c6865062b39)
![b53088354f77ff929f1d4c79bb48ee9](https://github.com/metersphere/metersphere/assets/77324661/264e8c9c-69dc-4414-a47d-afe173d7d519)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
