### ISSUE TITLE
[BUG]【接口测试】JSONPATH断言-正则匹配，断言结果不准确

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25027]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【接口测试】JSONPATH断言-正则匹配，当jsonpath提取的值为“智慧水务项目测试”，正则表达式为"^[\u4e00-\u9fa5]{3,9}$",断言结果为false

### 重现步骤

【接口测试】JSONPATH断言-正则匹配，当jsonpath提取的值为“智慧水务项目测试”，正则表达式为"^[\u4e00-\u9fa5]{3,9}$",返回结果为false，但是在idea里测试是为true
![image](https://github.com/metersphere/metersphere/assets/104960608/4a92d90b-f65a-4de1-b249-c6d5d1c41de2)
![image](https://github.com/metersphere/metersphere/assets/104960608/fbd25c06-6d6e-49c9-a105-acc78be185c1)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/f6de68ab-dc85-457d-8e02-29a40542b088)

这样写就行啦。

**Comment by 2lipan** [comment]
jsonpath断言值希望能 正则匹配 到这个值是含有3-9个汉字才是对的，如果正则匹配后面写具体值，那这"正则匹配"与"包含"有啥区别？ "正则匹配" 应该是可以写“正则表达式” 才对。

**Comment by youliyuan-fit2cloud** [comment]
> jsonpath断言值希望能 正则匹配 到这个值是含有3-9个汉字才是对的，如果正则匹配后面写具体值，那这"正则匹配"与"包含"有啥区别？ "正则匹配" 应该是可以写“正则表达式” 才对。

你说的对，我们改～

**Comment by fit2-zhao** [comment]
感谢反馈，目前平台底层测试引擎JMeter 内置用的是 Jakarta-ORO 库，所以正确写法是 "^[\u4e00-\u9fa5]{3,9}$"，
注意因为有编码问题正确加入平台展示如图：

![image](https://github.com/metersphere/metersphere/assets/70558837/fb2054b2-d31d-4ce5-b784-a8be80483766)

**Comment by 2lipan** [comment]
希望能解决编码问题，否则不符合用户习惯
![image](https://github.com/metersphere/metersphere/assets/104960608/eb2b858b-4c5a-48a0-8741-f8807f558319)

**Comment by fit2-zhao** [comment]
> 希望能解决编码问题，否则不符合用户习惯 ![image](https://user-images.githubusercontent.com/104960608/249420573-eb2b858b-4c5a-48a0-8741-f8807f558319.png)

试试加上配置 jmeter.properties  中添加 jmeter.regex.engine = jdk
