### ISSUE TITLE
[BUG] v1.9.1 环境配置已设置header，但调试时选择对应的环境，请求没有加上header

### ISSUE THREAD

**Issue by davidhhuan** [metersphere/metersphere#2503]
**MeterSphere 版本**
v1.9.1

**Bug 描述**
环境配置已设置header，但调试时选择对应的环境，请求没有加上header

**Bug 重现步骤**
1.  系统设置 -> 项目 -> 环境配置，如图1
2. 执行接口，如图2

**期待的正确结果**
应该是选择好运行环境，在请求头部会出现环境配置里面的header；发出的请求应该带上环境配置里面的header

**截图**
![图1](https://user-images.githubusercontent.com/449399/117239634-bebc3c00-ae61-11eb-9579-5979e608e4ba.png)

![图2](https://user-images.githubusercontent.com/449399/117239856-1fe40f80-ae62-11eb-9314-94ef8afe227b.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
1.9.2已修复
