### ISSUE TITLE
[BUG]【接口测试】JSONPATH断言, 当断言的JSONPATH表达式为"$.project[*].name" 时，等于 两个不同的值都断言正确了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25037]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【接口测试】JSONPATH断言, 当断言的JSONPATH表达式为"$.project[*].name" 时，等于 “智慧水务项目测试”和“智慧水务项目测试1”断言都正确了。

### 重现步骤

【接口测试】JSONPATH断言, 当断言的JSONPATH表达式为"$.project[*].name" 时，等于 “智慧水务项目测试”和“智慧水务项目测试1”断言都正确了。
![image](https://github.com/metersphere/metersphere/assets/104960608/b306c3fd-fcb3-4f1a-ad54-ac459ba84d98)
![image](https://github.com/metersphere/metersphere/assets/104960608/4bf5ea45-1239-4aa8-b28f-ae2c5a692070)
![image](https://github.com/metersphere/metersphere/assets/104960608/fc9a2f1c-1a05-4b6c-b9e4-1cceee6d2790)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
