### ISSUE TITLE
[BUG]接口修改自定义字段，第一次保存后仍提示未保存

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25033]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

接口修改自定义字段，保存后，关闭页签时仍提示未保存

### 重现步骤

1. 接口定义修改自定义字段保存,保存成功
![image](https://github.com/metersphere/metersphere/assets/103627487/66bbd37c-e4b4-4214-98cb-56b7598c9a5c)
2.关闭页签,仍提示未保存
![image](https://github.com/metersphere/metersphere/assets/103627487/58603564-6ddb-484e-9f54-dc9d88c40c6e)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
