### ISSUE TITLE
[BUG]点击编辑信息，出现闪退

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#25041]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

创建一个用例执行的角色
![image](https://github.com/metersphere/metersphere/assets/33934471/2cbc3650-44db-4415-a13e-8433fd1b43f9)

将角色给一个用户，
![image](https://github.com/metersphere/metersphere/assets/33934471/1dcb959d-5116-478f-87c6-f968de0c9458)

用户登陆后，点击编辑信息，出现闪退
![image](https://github.com/metersphere/metersphere/assets/33934471/8d4e4deb-9b0a-4883-b9eb-1010321fe7e6)

### 重现步骤

1、创建一个用例执行的角色
2、将角色给一个用户，
3、用户登陆后，点击编辑信息，出现闪退

### 期待的正确结果

应该可以编辑用户信息

**Comment by 13290445582** [comment]
感谢反馈，该问题为已知问题并已提交至tapd平台，后续版本修复。

**Comment by davidcchen** [comment]
新版本问题已解决
