### ISSUE TITLE
[FEATURE] 需要知道测试计划中性能，场景；api_case分别执行耗时

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2504]
**请描述您的需求或者改进建议.**

需要知道测试计划中性能，场景；api_case分别执行耗时
用处是；如果一个计划耗时太久可以分拆成多个计划来执行

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前还不支持，后续是否支持需要先内部讨论下再反馈
