### ISSUE TITLE
[BUG] 切换版本模块时目录数据统计未发生变化

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25051]
### MeterSphere 版本

所有版本

### 使用外置数据库

否

### 问题描述

<img width="1203" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8dac72dd-dedb-4fbc-a66e-a6f11e034763">

### 重现步骤

1、项目设置里新建一个版本
2、在接口测试-接口定义中将一个API迁移到新建的版本
3、case列表、文档列表切换版本号
4、发现左边的目录统计数据未发生变化

**Comment by 13290445582** [comment]
您好，感谢您的反馈，左侧目录显示的为接口数量，所以在切换至CASE/文档时左侧数量不会发生变化。
