### ISSUE TITLE
[BUG【UI测试】场景变量里设置变量为json，填入后校验不通过，但是将该json拿到在线解析里是可以正常解析的

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25062]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【UI测试】场景变量里设置变量为json，填入后校验不通过，但是将该json拿到在线解析里是可以正常解析的

### 重现步骤

【UI测试】场景变量里设置变量为json，填入后校验不通过，但是将该json拿到在线解析里是可以正常解析的
![image](https://github.com/metersphere/metersphere/assets/104960608/f85fd6e6-2dd1-41f2-825e-b5ce017fee94)
![image](https://github.com/metersphere/metersphere/assets/104960608/fff69d48-a388-4460-a416-f31da9b8d849)

json如下:
{"type":"LOCAL","path":"//span[text()='普通登录']","username":"test","password":"test123456","assert":"//li[text()=' 系统设置 ']"}

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.3修复。
