### ISSUE TITLE
[BUG]UI测试场景内包含多个层级的复制场景时，点击保存按钮，浏览器会崩溃

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25061]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

UI测试场景内包含多个层级的复制场景时，点击保存按钮，浏览器会崩溃

### 重现步骤

1.创建UI场景“组合1”，里面复制两个其他场景
2.创建UI场景“组合2”，里面复制两个其他场景
3.创建UI场景“组合3”，里面复制“组合1”和“组合2”
4.在“组合3”详情中中点击“保存”，浏览器页面无响应，一会就崩溃了，查看任务管理器发现内存占用比较高。
<img width="856" alt="53f941f7e4efc7d3a6c3abd75013ba1" src="https://github.com/metersphere/metersphere/assets/88763608/f76564c4-56ca-4698-b354-4f85164760bf">
<img width="850" alt="56b8a07662d23660c321b61f6bbb0f1" src="https://github.com/metersphere/metersphere/assets/88763608/ac1fb7fe-80bf-4d3d-a26c-df20e0557a17">
<img width="907" alt="715cb65671d542888242a7912c0ce6a" src="https://github.com/metersphere/metersphere/assets/88763608/1fee23b1-562b-493f-a13f-7af46cb95f51">

### 期待的正确结果

希望可以正常保存

**Comment by xiaomeinvG** [comment]
如果浏览器资源不充足，我们建议您尽量少开一些占用浏览器资源的标签页，或者当前页面的步骤尽量不要一次性展开

**Comment by linfengjjj** [comment]
你好，你可以亲自试一下，不展开也会崩溃，面对这种情况，根本无法使用，而且我的浏览器只打开了一个github和metersphere的标签页。
![image](https://github.com/metersphere/metersphere/assets/88763608/bc50b554-002e-4bdc-9159-fc4b600667a8)

**Comment by zrfit** [comment]
您好，浏览器打开10+tab页也未复现该问题！待v2.10.2-lts发布后尝试。

<img width="1436" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/550fc9fb-4fd0-4e9f-abee-60837cf8eb4b">

**Comment by linfengjjj** [comment]
最新进展：
1.选择某个步骤再保存会导致浏览器卡顿甚至崩溃。
2.不选中任何一个步骤，保存无异常。
3.我和客户电脑都是windows的，其他用windows电脑的同事也试了是同样的现象。

**Comment by zrfit** [comment]
您好，用windows系统chrome和firefox都验证了，选中步骤保存，响应会比较慢，点击请求后当前页面进行其它操作可以保存成功；如果进行其它操作，浏览器就报错了，已提优化到tapd，计划v3进行优化。
