### ISSUE TITLE
[FEATURE]场景里的组合搜索是否可以添加对接口路径的搜索？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#25078]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：场景里的组合搜索是否可以添加对接口路径的搜索？
场景：开发修改完接口的情况下，需要对接口case和场景里使用过该接口的都做一次测试，场景里使用过该接口的无法准确被搜索出来

**Comment by luty2018** [comment]
目前企业版支持针对开发修改后的接口进行通知关注人和 case/场景的创建人， 并支持一键同步变更，可以申请试用企业版。
