### ISSUE TITLE
[FEATURE]跨项目使用接口自动化时，用户复制场景后，该场景下的引用场景的运行环境，会跟随当前的运行环境的变化而变化。而不是跟随原始场景的运行环境变化。

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#25082]
### MeterSphere 版本

v2.10.1-lts

### 请描述您的需求或者改进建议

在使用MS接口场景自动化模块中，当跨项目复制场景时，会遇到如下问题：用户在当前项目中复制了另一个项目的接口场景，这个场景下又引用了别的场景。当用户将这个复制场景的运行环境修改时，复制场景下的引用场景的运行环境不会随着修改。只有当该引用环境的原始环境下的运行环境修改了，它才会随之修改。

### 请描述你建议的实现方案

建议实现的场景是：
在跨项目使用接口自动化时，用户复制场景后，该场景下的引用场景的运行环境，会跟随当前的运行环境的变化而变化。而不是跟随原始场景的运行环境变化。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/47737772/68230337-f199-4619-b987-50946a269ac1)
![image](https://github.com/metersphere/metersphere/assets/47737772/8e1d16ce-a0e4-42f1-9e46-7c3ea9572207)

**Comment by luty2018** [comment]
已规划了改进方案。
