### ISSUE TITLE
[BUG] 【接口测试】——在接口自动化中复制接口case并保存，当在接口case列表中删除这个case的时候，首页统计的接口覆盖率不对。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25087]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

1. 创建接口，创建接口case，查看接口测试->首页->接口覆盖率的值。
2. 创建接口自动化，并且关联接口case保存。
3. 删除刚才创建的接口case，此时接口自动化已经包含了接口case。
4. 再观察接口测试->首页->接口覆盖率的值,发现会有变化。这个是不对的，正常应该是不变才对，虽然接口case删除了，但也已经覆盖在自动化里面了，应该统计。

接口case删除之前：

<img width="650" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/069ae95c-5b42-4c6d-acaa-379becca5f64">

接口case删除之后：
<img width="967" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/c78f222d-e938-4e06-ac65-3deff12f94ed">

<img width="663" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/a8703eee-a9e4-44c9-89c2-d6757d4cf901">

### 重现步骤

同上

**Comment by 13290445582** [comment]
您好，按照您提供的步骤复现，并未出现接口覆盖率变化的的现象，请检查下是否有其他操作，或者提供下完整的复现录屏帮助复现，感谢。

**Comment by hao65103940** [comment]
> 您好，按照您提供的步骤复现，并未出现接口覆盖率变化的的现象，请检查下是否有其他操作，或者提供下完整的复现录屏帮助复现，感谢。


https://github.com/metersphere/metersphere/assets/33945037/f382e097-a606-4148-82f1-960f49004020

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
升级至最新环境，均未复现，经过沟通，关闭该issue。
