### ISSUE TITLE
[BUG]自动化场景保存不成功，后台log报错JSON parse error: String length (5039106) exceeds the maximum length (5000000)]

### ISSUE THREAD

**Issue by Jarod-Guo** [metersphere/metersphere#25089]
### MeterSphere 版本

v2.10.1-lts-65fad062

### 使用外置数据库

否

### 问题描述

- API\接口自动化
    创建API自动化场景，保存时不能保存成功。 F12 查看接口 400 报错

![image](https://github.com/metersphere/metersphere/assets/55393693/1e9845cd-e94e-4283-a655-ba8a9d87290f)

- 后台日志
   JSON parse error: String length (5039106) exceeds the maximum length (5000000)]?

### 重现步骤

进入 API\接口自动化，创建场景，调试后保存。
重新进入场景，接口内容没保存上，场景为空

**Comment by liqiang-fit2cloud** [comment]
系统限制，暂不支持大json，待第三方依赖解决。
https://github.com/metersphere/metersphere/issues/24810
