### ISSUE TITLE
[BUG] swagger导入接口出现重复

### ISSUE THREAD

**Issue by davidhhuan** [metersphere/metersphere#2509]
**MeterSphere 版本**
v1.9.1

**Bug 描述**
swagger导入接口出现重复，做了定时导入。同样的接口会出现两个，一个会多一个"/"在前面

**Bug 重现步骤**
1.  如图所示

**期待的正确结果**
同样的接口应该只导入一次

**截图**
![image](https://user-images.githubusercontent.com/449399/117250408-bf5ecd80-ae75-11eb-8dc6-e952b0448a91.png)

**Comment by xulinde** [comment]
能说下复现步骤吗，我们这边没复现

**Comment by davidhhuan** [comment]
> 能说下复现步骤吗，我们这边没复现

![image](https://user-images.githubusercontent.com/449399/117284018-fabec380-ae98-11eb-9ea2-c00d9b8d473c.png)
![image](https://user-images.githubusercontent.com/449399/117284192-280b7180-ae99-11eb-918a-eb99be881f84.png)
![image](https://user-images.githubusercontent.com/449399/117284239-35286080-ae99-11eb-8fd4-b5b2c87a4bc1.png)



感觉操作过程没什么特殊的，但就是能触发到这个bug

**Comment by davidhhuan** [comment]
@xulinde 我发现是定时任务才会出现多一个"/"的，所以就造成重复的出来。是不是可以优化一下这里的代码

![image](https://user-images.githubusercontent.com/449399/117390755-5339a380-af21-11eb-8959-cb4f8dd8f91f.png)

**Comment by xulinde** [comment]
1.9.2已修复
