### ISSUE TITLE
[BUG][优化]UI测试场景中复制了一个其他场景，此外没有其他步骤时，无法使用批量操作功能

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25090]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

UI测试场景中复制了一个其他场景，此外没有其他步骤时，无法使用批量操作功能

### 重现步骤

1.创建一个场景，场景里复制一个其他场景，没有批量操作的按钮。如果想要给复制的场景里的步骤批量设置截图等操作，就没办法操作，很不方便。
<img width="912" alt="f97dc963590ddcf881d27374a51f500" src="https://github.com/metersphere/metersphere/assets/88763608/1d2a3676-01bc-4292-836c-e3b8a82c5fc4">
<img width="913" alt="6dd25d9b36fca0bafbaf02443328412" src="https://github.com/metersphere/metersphere/assets/88763608/4a70d3de-9b64-4684-882e-6555e48828c3">
<img width="916" alt="38f4367732d3449508b8add30ebb06c" src="https://github.com/metersphere/metersphere/assets/88763608/31200c59-de3b-4507-87b8-1a49f1f04452">
2.还要再额外加个步骤才会出来批量操作入口。建议优化下，就算最外层只有一个步骤，也提供批量操作的入口。

### 期待的正确结果

建议优化下，就算最外层只有一个步骤，也提供批量操作的入口。

**Comment by liqiang-fit2cloud** [comment]
优化需求请提feature，不要提bug。
