### ISSUE TITLE
[BUG]接口自动化场景调试完后没有保存，然后切换到测试跟踪模块，导致接口调试的内容全部都没了

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25104]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

接口自动化场景调试完后没有保存，然后切换到测试跟踪模块，导致接口调试的内容全部都没了

### 重现步骤

接口自动化场景调试完后不保存，然后切换到测试跟踪模块，再切换回接口自动化场景，之前调试好的场景就没有保存上

### 期待的正确结果

如果没有保存上，是不是可以从接口测试切换到测试跟踪后，可以增加一个保存的提示

**Comment by wan92hen** [comment]
目前只有主动关闭场景编辑标签的时候才有保存提示，其他退出方式确实可以加一下。

**Comment by luty2018** [comment]
已修复
