### ISSUE TITLE
[BUG]“推荐jsonpath断言”功能中，点击数组或对象生成的结果中数字变成了字符串

### ISSUE THREAD

**Issue by LuxTong** [metersphere/metersphere#25109]
### MeterSphere 版本

v2.10.0-lts

### 使用外置数据库

否

### 问题描述

“推荐jsonpath断言”功能中，点击数组或对象自动生成的断言结果中，接口返回的数字，被转换为字符串，直接点击数组或对象自动生成的断言无法直接使用

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/34410215/856fb11e-c9b6-47a1-b284-0d42b3e6477f)
![image](https://github.com/metersphere/metersphere/assets/34410215/e96d9f46-f2b9-49ea-8884-d662cffe15d7)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
您好，经过沟通，前端json是会丢失精度的，为了保持数据的精度，所以把所有的数字都转化成了字符串。

**Comment by 13290445582** [comment]
v2.10.5已修复
