### ISSUE TITLE
[BUG]创建测试计划分配测试用例 不能多选测试执行人，分配完用例不会消除已勾选的

### ISSUE THREAD

**Issue by ali10180209** [metersphere/metersphere#2510]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？最新版本

**Bug 描述**
创建测试计划分配测试用例 不能多选测试执行人，分配完用例不会消除已勾选的

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
目前执行人还不支持多选
