### ISSUE TITLE
[FEATURE]场景变量被赋值的时候，建议在场景变量弹框中能展示值

### ISSUE THREAD

**Issue by lthu99** [metersphere/metersphere#25118]
### MeterSphere 版本

2.9.1

### 请描述您的需求或者改进建议

场景变量被赋值的时候，建议在场景变量弹框中能展示值

### 请描述你建议的实现方案

场景变量被赋值的时候，建议在场景变量弹框中能展示值

**Comment by luty2018** [comment]
如果是在执行过程中给变量赋值，建议通过提取变量和打印变量来查看，场景变量弹窗中是定义变量和常量的地方
