### ISSUE TITLE
点击下一条，报错[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#2511]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/117258147-39478480-ae7f-11eb-8db2-af673e3375bc.png)

**Comment by xulinde** [comment]
该问题在1.9.2已修复，建议您升级到最新版本
