### ISSUE TITLE
[FEATURE]我有一个想法，是否可以在企业版的基础上，去除一些功能，保留核心的功能，提供付费的个人版本

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#25111]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

如题。

**Comment by luty2018** [comment]
MeterSphere的定位是团队协作的一站式持续测试平台。
个人使用的话， 你可以看看MeterSphere的cloud版，这个也是包含全部企业版功能的，按人/年订阅，费用也不高。

**Comment by YellCatt** [comment]
> MeterSphere的定位是团队协作的一站式持续测试平台。 个人使用的话， 你可以看看MeterSphere的cloud版，这个也是包含全部企业版功能的，按人/年订阅，费用也不高。

ε=(´ο｀*)))唉
