### ISSUE TITLE
[BUG]【接口测试】JMeter脚本-断言处勾选Not，但是导入MS里，发现断言类型为正则，这个Not作用没有体现出来。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25116]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

【接口测试】JMeter脚本-断言处勾选Not，但是导入MS里，发现断言类型为正则，这个Not作用没有体现出来。

### 重现步骤

【接口测试】JMeter脚本-断言处勾选Not，但是导入MS里，发现断言类型为正则，这个Not作用没有体现出来。
![image](https://github.com/metersphere/metersphere/assets/104960608/fe504637-d27d-4573-91cb-2d8f2c875d72)
![image](https://github.com/metersphere/metersphere/assets/104960608/a7313a66-0943-4311-ba0d-37058224d6b0)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd，开发跟进。

**Comment by fit2-zhao** [comment]
目前平台不支持这种类型，请提需求。
