### ISSUE TITLE
[BUG]脑图编写用例，不同分支下的模块名称可以重复，但选择其中一个分支保存时会提示模块重复，无法保存

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#25117]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

1、脑图编写用例，不同分支下的模块名称可以重复，但选择其中一个分支保存时会提示模块重复，无法保存

![b265c8299ea006a05dcf4efe74addb1](https://github.com/metersphere/metersphere/assets/43720321/99de3bfd-450b-4b61-9f33-87b6129b66af)

### 重现步骤

脑图编写用例，不同分支下的模块名称可以重复，但选择其中一个分支保存时会提示模块重复，无法保存

### 期待的正确结果

正常可以保存

**Comment by 13290445582** [comment]
您好，您的问题是在最新的v2.10.2遇到的吗，方便提供下复现录屏吗？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
