### ISSUE TITLE
[QUESTION] v2.9.0版本，环境配置-全局断言-启用误报按键不存在

### ISSUE THREAD

**Issue by jia9iZhang** [metersphere/metersphere#25127]
### 请描述您的问题

MeterSphere: v2.9.0-426de152
角色：项目成员(系统)

参考文档教程：https://kb.fit2cloud.com/?p=252#heading-8
在进行环境配置-全局断言配置时，并不存在 “启用误报” 按钮，请问是移除该功能了吗？还是该按钮有权限限制？
<img width="1180" alt="image" src="https://github.com/metersphere/metersphere/assets/50917145/2f689f47-65e1-4932-ba3c-b676ab90b747">

**Comment by luty2018** [comment]
这个是企业版功能哦

**Comment by jia9iZhang** [comment]
了解
