### ISSUE TITLE
[BUG]添加缺陷会报英文错误

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#2512]
**MeterSphere 版本**
版本: v1.9.1-2cb10c1e
**Bug 描述**
添加缺陷会报英文错误

**Bug 重现步骤**
1.  从测试计划进入测试用例
2. 在执行用例时添加缺陷时会报错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/80370956/117261383-a7da1180-ae82-11eb-9a63-41406aa439db.png)

**Comment by xulinde** [comment]
能说下具体的操作步骤吗

**Comment by littlelilyjiang** [comment]
您好 我也出现了这个问题
![image](https://user-images.githubusercontent.com/21242743/118428300-bbe30600-b701-11eb-902c-9d3bd731bc05.png)
1. 新建测试计划
2. 执行测试计划
3. 点击添加缺陷

出现这个英文提示 请问需要如何解决呢

@xulinde

**Comment by xulinde** [comment]
您好，最新的1.10版本还会有这个问题吗

**Comment by zyyfit** [comment]
您好，这个问题是因为项目没有设置默认缺陷模板导致的，最新版已修复，请升级使用
