### ISSUE TITLE
[BUG]接口测试请求体转json-schema后，会丢失空格

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25124]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

接口测试请求体转json-schema后，会丢失空格

### 重现步骤

1.接口测试请求体使用该请求体
{
    "datetime": "2023-06-21 00:00:00"
}
<img width="292" alt="b4ef19821a921c0ef0bc54d44c6c80d" src="https://github.com/metersphere/metersphere/assets/88763608/03163728-99e2-4b8d-a4aa-a86818a01064">

2.开启json-schema，空格丢失了
<img width="514" alt="f959cb922288e034a596a23928f9a57" src="https://github.com/metersphere/metersphere/assets/88763608/7f943dd0-a8a9-4729-9009-7dc8c79b33c7">

3.关闭json-schema，空格也回不来了
<img width="533" alt="202660df52be54af71d53e434c0cfc1" src="https://github.com/metersphere/metersphere/assets/88763608/69db839e-ff14-4094-ba72-ecd1ef054ec0">

### 期待的正确结果

不应该丢失

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.3-lts修复。
