### ISSUE TITLE
[FEATURE]建议创建用例的"保存并继续添加"不应该停留在之前的编辑界面，应该清空所有值

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#25136]
### MeterSphere 版本

v2.10.2-lts

### 请描述您的需求或者改进建议

当前点击"保存并继续添加"，依然停留在之前的编辑用例界面

![image](https://github.com/metersphere/metersphere/assets/33934471/cf6e8124-6303-4f79-b956-d0475c3fbd64)

### 请描述你建议的实现方案

建议保存后，新开一个页面，所有值都被清空；或者添加防误点机制，当前不做修改，点击就会生成新的用例

**Comment by davidcchen** [comment]
或者每次点击"保存并继续添加"后，把之前的用例的标题和步骤清空，这样我们就可以复用一些用例的内容

**Comment by 13290445582** [comment]
https://github.com/metersphere/metersphere/issues/25280
