### ISSUE TITLE
[BUG]添加缺陷无法添加截图

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#2513]
**MeterSphere 版本**
版本: v1.9.1-2cb10c1e

**Bug 描述**
添加缺陷需要可以 ctrl+V 添加截图功能

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**

**截图**

**Comment by xulinde** [comment]
当前版本还不支持，后续会支持

**Comment by xulinde** [comment]
v1.10.2已支持
