### ISSUE TITLE
[BUG]当项目数量过多时，用户授权用户组出现下拉列表不显示项目名称

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#25143]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

当项目数量过多（大约400左右），管理员给用户授权用户组出现下拉列表显示“搜索获取其他选项”错误，而不显示实际的项目名称

### 重现步骤

1、创建多个项目 （环境是400个）
2、系统设置下给用户授权用户组
3、观察项目下拉列表

### 附加信息

如下图：
<img width="336" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/cc9a0d70-52ea-4b3f-b047-97aba4e7a443">

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
