### ISSUE TITLE
[BUG]测试计划列表查看报告内容显示错误，与实际的测试计划报告显示内容不符

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#25148]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

1.20.23-LTS

### 使用外置数据库

否

### 问题描述

测试计划列表中查看报告内容，显示的通过率、执行率、测试时间等信息错误(不知道该数据从何处获取到的)，且与该测试计划最近一次的报告内容显示不符

### 重现步骤

1、测试计划手动执行完成后，在测试计划列表中查看报告
2、在报告列表中，查看该测试计划最近一次报告，对比测试内容

### 期待的正确结果

测试计划列表中的报告，与报告列表中最新一次报告相符且显示正确

### 附加信息

1、测试计划列表显示
<img width="1435" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/29287cf9-a97d-4fb3-902c-e604f0a5a958">
<img width="1422" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/0846f4e1-7e23-4d39-bf63-968c37d2bc5e">

列表中查看报告：
<img width="1434" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/840980ec-5031-442e-a3f4-d3bf0b753ccb">

2、实际在报告列表查看：
<img width="1433" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/8c3b4d5d-6fae-4aa8-a8c7-b71739708cfe">
<img width="1416" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/db8d61f3-0874-4079-bf6d-7fe881f5eaa0">

**Comment by youliyuan-fit2cloud** [comment]
1.测试跟踪-报告列表 中的结果仅是当次，当时计划中包含的用例执行结果统计。
2.测试跟踪-测试计划-报告或计划里面报告统计详情，是当前最新的测试计划执行统计，测试计划列表中的报告和测试计划详情的报告统计是完全一致的。
3.从上面截图发现，测试计划中的前后用例数有变更，报告数据应该不一样。
