### ISSUE TITLE
[FEATURE]接口case的标签太多时，会出现样式穿透，建议优化

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25169]
### MeterSphere 版本

v2.10.2-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

接口case的标签太多时，会出现样式穿透，建议优化
<img width="938" alt="c14dd5a6bcde7da222eb79e11f52ece" src="https://github.com/metersphere/metersphere/assets/88763608/3d63d5b0-0713-4008-8cda-1f500b55f92f">

**Comment by luty2018** [comment]
已转bug处理
