### ISSUE TITLE
[BUG]【接口测试】接口定义导入Har包报com.fasterxml.jackson.dataha'rinlinth o046272) exceeds the maximum length (5000000) 错误

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#25162]
### MeterSphere 版本

v2.10.2

### 使用外置数据库

否

### 问题描述

浏览器录制har包从接口定义导入报错

### 重现步骤

见附件

### 期待的正确结果

har包可以正常导入

### 附加信息

<img width="803" alt="29f17d7c9a0b3ca94ff00129cfb1f67" src="https://github.com/metersphere/metersphere/assets/45531073/dca4d22f-f05e-495b-aeac-9c94feb283fc">

har包
[sit-ph-portal.fehorizon.com20230628.zip](https://github.com/metersphere/metersphere/files/11862553/sit-ph-portal.fehorizon.com20230628.zip)

**Comment by fit2-zhao** [comment]
感谢反馈，和这个 #25156 issues重复了，请关注这个后续。
