### ISSUE TITLE
[FEATURE]UI测试步骤下面的元素库中，元素对象的“操作”入口太隐蔽了，建议优化

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25170]
### MeterSphere 版本

v2.10.2-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

UI测试步骤下面的元素库中，元素对象的“操作”入口太隐蔽了，建议优化
<img width="906" alt="1a8b989434908173af60d0de9b06628" src="https://github.com/metersphere/metersphere/assets/88763608/cd80902f-22bf-467a-960d-d930a3776b53">
<img width="935" alt="2d360df150107c257dab915e8384f9c" src="https://github.com/metersphere/metersphere/assets/88763608/ed817b09-36b5-44ab-9bb4-079f757d3104">

**Comment by luty2018** [comment]
元素是在元素库（二级菜单）中操作， 这里只是加了一个便捷操作的入口。
