### ISSUE TITLE
[BUG]ms升级到V2.10版本后，请求体中json转义的数据，不能换行使用，之前换行使用的全部报错：JSON parse error: Illegal unquoted character

### ISSUE THREAD

**Issue by luoxiangfei** [metersphere/metersphere#25189]
### 联系方式

david.luo@anker-in.com

### MeterSphere 版本

v2.10.1-lts 

### 使用外置数据库

否

### 问题描述

ms升级到V2.10版本后，请求体中json转义的数据，不能换行使用，之前换行使用的全部报错：JSON parse error: Illegal unquoted character

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/46469855/a8f5fa20-422f-42b9-aa1a-45ec869af7f3)

### 期待的正确结果

转义的json数据，换行后还能正常请求，不然我转义数据量非常大的时候，后面的数据根本就看不到

**Comment by 13290445582** [comment]
您好，可以将场景导出下，帮助复现嘛？

**Comment by luoxiangfei** [comment]
![image](https://github.com/metersphere/metersphere/assets/46469855/19de7c07-7482-4268-9262-025a725c5404)
![image](https://github.com/metersphere/metersphere/assets/46469855/7e1f1a64-90da-48d3-89af-3018fc6b1328)

**Comment by luoxiangfei** [comment]
这么说够明白了吗？
![image](https://github.com/metersphere/metersphere/assets/46469855/3273ab44-052b-47d5-9096-8cef0e9acf6a)

**Comment by luoxiangfei** [comment]
[Metersphere_Api_结算中心.txt](https://github.com/metersphere/metersphere/files/11868793/Metersphere_Api_.txt)
吧txt改成json导入，接口数据在这里

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
您是从哪个版本升级到的v2.10版本呢？

**Comment by luoxiangfei** [comment]
> 您是从哪个版本升级到v2.10版本呢？

我是从1.20版本升级过来的

**Comment by luoxiangfei** [comment]
> 感谢反馈，问题已复现并提交至tapd平台，开发后续，后续版本修复。

非常感谢

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
