### ISSUE TITLE
[BUG]接口自动化场景添加自定义请求时在地址上自动添加了 `http://`

### ISSUE THREAD

**Issue by wan92hen** [metersphere/metersphere#25180]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

添加自定义请求时，如果最终希望勾选引用环境，在地址中只填写相对路径时系统会在最前面的位置自动添加 `http://`，需要保存后回到场景编辑页面才能删除，并勾选引用环境选项。
![image](https://github.com/metersphere/metersphere/assets/27671436/4c09e2ef-7155-401a-8f49-9249ed0c0877)

### 重现步骤

1. 打开场景编辑页面
2. 添加自定义请求步骤
3. 在弹出的抽屉中选择 `HTTP` 请求类型，并在地址框中填入 `/test`
4. 点击页面其他位置，地址框中内容变成了 `http:///test`

### 期待的正确结果

建议在弹出抽屉的编辑逻辑与场景编辑界面中的逻辑一致，即：
1. 在抽屉页面也增加 `引用环境` 勾选框；
2. 勾选引用环境时，类似场景编辑页面中自定义请求处理方式，将当前所选环境的域名信息显示在地址栏前方；
3. 不勾选引用环境时，地址栏提示“请输入完整地址”，并进行自动补全 `http://` 协议头的处理。

**Comment by 13290445582** [comment]
感谢反馈，已提交tapd平台，后续版本优化。

**Comment by luty2018** [comment]
v3.0已支持，欢迎下载使用。
