### ISSUE TITLE
[BUG]【UI测试】alert弹窗，“弹窗操作”点击了“确定”，页面上看着正常点击，但是步骤结果显示失败

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25183]
### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

【UI测试】alert弹窗，“弹窗操作”点击了“确定”，页面上看着正常点击，但是步骤结果显示失败

### 重现步骤

【UI测试】alert弹窗，“弹窗操作”点击了“确定”，页面上看着正常点击，但是步骤结果显示失败
![image](https://github.com/metersphere/metersphere/assets/104960608/545bdad5-e607-42b4-b86c-dc1cf4dbc27e)
![image](https://github.com/metersphere/metersphere/assets/104960608/bef478f7-3aa0-463f-a702-ca884f309204)

**Comment by zrfit** [comment]
同问题https://github.com/metersphere/metersphere/issues/24921

**Comment by 2lipan** [comment]
@zrfit  这问题与问题#24921 还是不一样，这是alert框，不是div，而且前面步骤和后面步骤都没有截图，可导入如下脚本试试
[Metersphere_Ui_MeterSphere_演示.zip](https://github.com/metersphere/metersphere/files/11892855/Metersphere_Ui_MeterSphere_.zip)

**Comment by zrfit** [comment]
您好，用您的场景验证，v2.10.3-lts无该问题，待v2.10.3-lts发布后升级尝试。
