### ISSUE TITLE
[BUG]【UI测试】页面alert弹窗，对alert弹窗文本进行断言，断言失败。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25188]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

【UI测试】页面alert弹窗，想对alert弹窗文本进行断言，断言失败。页面手动点击弹出的信息为“Alert Message”，但是“本地调试”点击弹出的信息为"[object Arguments]"

### 重现步骤

【UI测试】页面alert弹窗，想对alert弹窗文本进行断言，断言失败。页面手动点击弹出的信息为“Alert Message”，但是“本地调试”点击弹出的信息为"[object Arguments]"
![image](https://github.com/metersphere/metersphere/assets/104960608/4203389d-dc14-4281-8328-7877e091884e)

![image](https://github.com/metersphere/metersphere/assets/104960608/d8b56776-57ea-4067-9a10-aa137275533f)

![image](https://github.com/metersphere/metersphere/assets/104960608/4fa95952-cb18-449c-9dd2-af58c2409baf)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.2-lts未复现该问题，建议升级尝试。

**Comment by 2lipan** [comment]
该问题在v2.10.2-lts版本仍存在，可导入以下脚本试试
[Metersphere_Ui_MeterSphere_演示.zip](https://github.com/metersphere/metersphere/files/11892819/Metersphere_Ui_MeterSphere_.zip)
![image](https://github.com/metersphere/metersphere/assets/104960608/1a2584b7-2447-41b0-9471-fc637898e07e)
![image](https://github.com/metersphere/metersphere/assets/104960608/a5c4dced-92e1-4a88-9645-a2f9fd8e1db2)

**Comment by zrfit** [comment]
您好，您的场景中通过脚本alert弹框后并没有关闭，所以断言的是第一个弹框中的文本，可以通过脚本关闭脚本中的alert弹框，然后再鼠标操作弹出新的弹框，再进行后面弹框操作的断言即可。
![image](https://github.com/metersphere/metersphere/assets/99731894/63764ee4-6735-41e5-94b8-553aee4bca41)
