### ISSUE TITLE
[BUG]  禅道关联需求失败

### ISSUE THREAD

**Issue by songshien** [metersphere/metersphere#2519]
**MeterSphere 版本**
版本: v1.9.1-2cb10c1e

**Bug 描述**
关联禅道项目ID 成功，获取需求失败，后台ERROR日志

**Bug 重现步骤**
1.  选择项目
2.  新建用例
3.  关联需求
4. 

**期待的正确结果**
正常情况是不是应该是在【关联需求】下拉框中关联出禅道对应的需求

**截图**
![image](https://user-images.githubusercontent.com/49715889/117278542-70279580-ae93-11eb-9833-37637f3a7465.png)
![image](https://user-images.githubusercontent.com/49715889/117278619-7fa6de80-ae93-11eb-90fb-90064d18c34a.png)
![image](https://user-images.githubusercontent.com/49715889/117278682-8d5c6400-ae93-11eb-939a-024b6654654f.png)
![image](https://user-images.githubusercontent.com/49715889/117278806-a9f89c00-ae93-11eb-88b4-e91998b4bb07.png)

**Comment by xulinde** [comment]
下个版本修复

**Comment by shiziyuan9527** [comment]
关联的禅道项目下有需求吗

**Comment by songshien** [comment]
> 关联的禅道项目下有需求吗

有啊

**Comment by songshien** [comment]
> 下个版本修复

好的，谢谢

**Comment by wangzhen-fit2cloud** [comment]
你好，请问升级到 1.9.2 之后问题还存在吗？

**Comment by songshien** [comment]
> 你好，请问升级到 1.9.2 之后问题还存在吗？

问题依旧没有解决，再付几个图给您参考：

![image](https://user-images.githubusercontent.com/49715889/118210602-39f2a300-b49d-11eb-9ab1-da764850fd5c.png)
![image](https://user-images.githubusercontent.com/49715889/118210654-5262bd80-b49d-11eb-81f2-819b4f0535e9.png)
![image](https://user-images.githubusercontent.com/49715889/118210745-7aeab780-b49d-11eb-91fd-b56e0b455fcf.png)
![image](https://user-images.githubusercontent.com/49715889/118210807-96ee5900-b49d-11eb-8128-a5491eed4f10.png)
![image](https://user-images.githubusercontent.com/49715889/118210894-bb4a3580-b49d-11eb-85cd-766c567bfeb8.png)
![image](https://user-images.githubusercontent.com/49715889/118210918-c56c3400-b49d-11eb-9442-180078222d84.png)

**Comment by lfc3249635** [comment]
禅道版本12.2 同样的问题：
get zentao bug fail can not cast to JSONObject

**Comment by shiziyuan9527** [comment]
> > 你好，请问升级到 1.9.2 之后问题还存在吗？
> 
> 问题依旧没有解决，再付几个图给您参考：
> 
> ![image](https://user-images.githubusercontent.com/49715889/118210602-39f2a300-b49d-11eb-9ab1-da764850fd5c.png)
> ![image](https://user-images.githubusercontent.com/49715889/118210654-5262bd80-b49d-11eb-81f2-819b4f0535e9.png)
> ![image](https://user-images.githubusercontent.com/49715889/118210745-7aeab780-b49d-11eb-91fd-b56e0b455fcf.png)
> ![image](https://user-images.githubusercontent.com/49715889/118210807-96ee5900-b49d-11eb-8128-a5491eed4f10.png)
> ![image](https://user-images.githubusercontent.com/49715889/118210894-bb4a3580-b49d-11eb-85cd-766c567bfeb8.png)
> ![image](https://user-images.githubusercontent.com/49715889/118210918-c56c3400-b49d-11eb-9442-180078222d84.png)

![image](https://user-images.githubusercontent.com/58418919/121134263-c8243400-c865-11eb-9a5f-a31ff05ed521.png)
我们关联的是项目下的需求，但是你们好像是用的 产品-项目 这种流程，所以对应的其实是你 产品 菜单下的需求，你可以尝试关联对应的产品ID试下

**Comment by songshien** [comment]
> > > 你好，请问升级到 1.9.2 之后问题还存在吗？
> > 
> > 
> > 问题依旧没有解决，再付几个图给您参考：
> > ![image](https://user-images.githubusercontent.com/49715889/118210602-39f2a300-b49d-11eb-9ab1-da764850fd5c.png)
> > ![image](https://user-images.githubusercontent.com/49715889/118210654-5262bd80-b49d-11eb-81f2-819b4f0535e9.png)
> > ![image](https://user-images.githubusercontent.com/49715889/118210745-7aeab780-b49d-11eb-91fd-b56e0b455fcf.png)
> > ![image](https://user-images.githubusercontent.com/49715889/118210807-96ee5900-b49d-11eb-8128-a5491eed4f10.png)
> > ![image](https://user-images.githubusercontent.com/49715889/118210894-bb4a3580-b49d-11eb-85cd-766c567bfeb8.png)
> > ![image](https://user-images.githubusercontent.com/49715889/118210918-c56c3400-b49d-11eb-9442-180078222d84.png)
> 
> ![image](https://user-images.githubusercontent.com/58418919/121134263-c8243400-c865-11eb-9a5f-a31ff05ed521.png)
> 我们关联的是项目下的需求，但是你们好像是用的 产品-项目 这种流程，所以对应的其实是你 产品 菜单下的需求，你可以尝试关联对应的产品ID试下

尝试关联产品id，还是报错，后台日志如下：
![image](https://user-images.githubusercontent.com/49715889/121497871-736fed00-ca0e-11eb-95a4-8ff6647bb421.png)

**Comment by songshien** [comment]
经过测试，此问题在最新的release版本v1.12.1中已经修复，在此特别感谢团队的关注和跟进。
