### ISSUE TITLE
[BUG] v1.20 版本 QuotaService 接口的实现在那里？

### ISSUE THREAD

**Issue by qwganker** [metersphere/metersphere#25205]
### MeterSphere 版本

v1.20

### 使用外置数据库

否

### 问题描述

QuotaService 只看见接口定义，没看见实现

### 重现步骤

QuotaService 只看见接口定义，没看见实现

**Comment by fit2-zhao** [comment]
您好这个是企业版功能，如果您还不是企业用户可以在企业微信群中去联系我们工作人员申请企业版。
