### ISSUE TITLE
[BUG]测试计划执行过程中进入用例关联界面，导致测试计划列表数据显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#25213]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

2.10.2-LTS

### 使用外置数据库

否

### 问题描述

测试计划执行过程中，点开测试计划名称进入关联用例界面，不做任何操作，再返回测试计划列表发现测试计划的进度变成“已完成”，“执行结束时间”变为当前时间，列表中点击查看报告也显示错误   ，而通过报告列表查看报告实际还是处于执行中。

### 重现步骤

1、测试计划列表中选择一个测试计划执行
2、当页面显示该计划处于running中之后，点击该测试计划名称，进入关联用例页面
3、再返回测试计划列表，查看改测试计划的执行进度，状态及结束时间

### 附加信息

列表内容：
<img width="1027" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/3a5d070b-32d4-40bc-b824-08f01f6979a5">
<img width="1167" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/e3e1f418-4c9c-4bf8-a68f-f222c902d5f5">

报告内容：
<img width="1424" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/f8b1ddc5-e791-4164-9ccd-8654bd13ee27">

**Comment by 13290445582** [comment]
您好，该问题在测试环境未复现，您那边稳定复现吗，有其他前置条件吗，方便发下完整录屏帮助复现吗？

**Comment by dashenyucainiao** [comment]
可以复现，我私发你环境

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
