### ISSUE TITLE
[BUG]脑图编辑，模块名称太长，保存页面会报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25219]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

脑图编辑，模块名称太长，保存页面会报错

### 重现步骤

脑图编辑，模块名称太长（例如：【开通服务-仅勾选】【Type为 investor】【Type为ed investor】【Type为ed investor】【Type为ed investor】【Type为 investor【Type为 investor），保存页面会报错
![image](https://github.com/metersphere/metersphere/assets/103627487/e31d95a0-06ff-45ba-9fb8-041bcdc5491a)
![img_v2_39e9e81a-c3c0-4b9b-8f5d-b2f8db36f69g](https://github.com/metersphere/metersphere/assets/103627487/f06d5959-5d23-420e-a802-bebcc6e48565)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
