### ISSUE TITLE
[BUG][JIRA]与JIRA平台对接时，MS上编辑BUG页面保存会提示错误，导致不能保存成功

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#25220]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

JIRA平台对接时，MS上编辑BUG页面保存会提示错误，导致不能保存成功

### 重现步骤

1. 项目使用【JIRA缺陷模板】
2. BUG双向同步后，在MS打开BUG进行编辑，实际不进行任何编辑动作，直接进行保存，会提示错误导致不能保存；详细的错误信息参考附件信息。

### 期待的正确结果

无任何错误提示

### 附加信息

![企业微信截图_16878531948652](https://github.com/metersphere/metersphere/assets/6109912/32cdeacd-dd20-4595-8c33-724dbaf1b113)

**Comment by ChangqiaoWang** [comment]
JIRA平台插件2.10.0版本

**Comment by youliyuan-fit2cloud** [comment]
你好，错误消息表明这些字段无法在当前屏幕上设置，或者这些字段在 Jira 中是未知的。可能的原因包括：

需要在正确的屏幕上设置这些字段。请检查您的 API 请求是否使用了正确的屏幕。
这些字段可能已经被删除或重命名了。请确保您在 API 请求中使用的字段名称是正确的。
您可能没有足够的权限来设置这些字段。请检查您的 API 请求中使用的用户是否有足够的权限来设置这些字段。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
