### ISSUE TITLE
[BUG]创建接口场景并点击保存后，页面提示保存成功，但切换到场景列表，没有自动刷新场景列表信息

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#25223]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

描述信息，如标题所示

### 重现步骤

重现步骤，如下图所示
<img width="952" alt="WX20230627-165152@2x" src="https://github.com/metersphere/metersphere/assets/18387151/6785dfa3-731c-4002-a1a1-c08130aa4bf6">
<img width="857" alt="WX20230627-165459@2x" src="https://github.com/metersphere/metersphere/assets/18387151/cd490389-aef1-46af-9807-219c1d612adf">

### 期待的正确结果

在创建场景并保存成功后，切换到“场景列表”后，场景列表能自动刷新一次，看到最新创建的场景信息

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
