### ISSUE TITLE
[BUG]超级管理员用户不授项目级别权限，任务中心搜索失效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#25228]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

2.10.2-lts

### 使用外置数据库

否

### 问题描述

对于超级管理员用户不授项目级别权限，执行测试计划后，在任务中心按“执行人”搜索失效，且任务中心中看不到在执行的任务，尤其是UI测试用例。

### 重现步骤

1、创建一个新用户并授权超级管理员
2、选择某个项目下的测试计划，手动执行
3、点开任务中心，搜索执行人
4、点开任务中心中的各种类型用例，发现没有在执行中的任务
5、给用户授权当前项目后，可以看到执行人列表出现当前用户，并可以看到任务信息

### 附加信息

截图如下：
![image](https://github.com/metersphere/metersphere/assets/32027713/790d376f-673c-4b30-8702-e545d5cbdbf1)

**Comment by 13290445582** [comment]
已知问题，计划于v2.10.3修复。

**Comment by 13290445582** [comment]
您好，设计层面问题不大改，已转v3.0待设计规划。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
