### ISSUE TITLE
[BUG]不同用户设定表头显示字段，不应该影响到其他用户

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#25231]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

不同用户设定表头显示字段，不应该影响到其他用户

### 重现步骤

1、用户A登进系统，测试跟踪->测试计划->操作，进行表头显示字段设置
2、用户B登进系统，测试跟踪->测试计划->发现显示的表头是用户A设置的
![image](https://github.com/metersphere/metersphere/assets/33934471/20bc22a0-5ee0-48b1-ac9e-c1922fbdbb69)

### 期待的正确结果

不用用户相互设定的表头显示字段，应该互不影响

**Comment by 13290445582** [comment]
您好，多个用户对同一个项目进行修改，项目内容的变更当然会同步给其他用户，表头的显示也属于对项目内容的操作。
