### ISSUE TITLE
[QUESTION]请问列表变量中的值如果包含逗号，逗号怎么转义？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#25246]
### 请描述您的问题

请问列表型场景变量怎么转义逗号？里面有一个值有逗号，就直接隔开了。
比如a,b,(a,b) 期望的第三个元素是(a,b)，但是循环里面变成了四个循环。
![41687857406_ pic](https://github.com/metersphere/metersphere/assets/31870788/83be8f90-ff0f-40da-96a2-661035621826)

**Comment by luty2018** [comment]
<img width="755" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/e5ef3c03-fd6d-41ee-9f21-9795fed08359">
