### ISSUE TITLE
[BUG]全局前置脚本导入>>从API定义导入：选择api，导入api的脚本，当测试环境地址为多域时，导入的脚本环境地址不对。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#25252]
### MeterSphere 版本

V2.10.2-lts

### 使用外置数据库

否

### 问题描述

[BUG]全局前置脚本导入>>从API定义导入：选择API，导入API的脚本，当测试环境地址为多域时，导入的脚本环境地址不对。

前置条件：
1、测试环境的地址为2条，1）启用条件【无】时，地址为B；2）启用条件【模块】，并且模块=OA时，地址为A
2、在测试环境http配置中，按模板定义的域名，在域名列表中排在第一个

操作：
1、全局前置脚本：选择右侧【api测试】：从API定义导入：
2、选择API, 并且此API属于【用户管理】模块，
3、选择测试环境1

错误：
1、导入的脚本中，引用的http配置的域名错误，引用的是第一条记录的地址

### 重现步骤

[BUG]全局前置脚本导入>>从API定义导入：选择API，导入API的脚本，当测试环境地址为多域时，导入的脚本环境地址不对。

前置条件：
1、测试环境的地址为2条，1）启用条件【无】时，地址为B；2）启用条件【模块】，并且模块=OA时，地址为A
2、在测试环境http配置中，按模板定义的域名，在域名列表中排在第一个

操作：
1、全局前置脚本：选择右侧【api测试】：从API定义导入：
2、选择API, 并且此API属于【用户管理】模块，
3、选择测试环境1

错误：
1、导入的脚本中，引用的http配置的域名错误，引用的是第一条记录的地址

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/15f9dfce-0ea2-48db-9d3f-f5246b24aefb)
![image](https://github.com/metersphere/metersphere/assets/78218624/cf3daa42-e42d-4773-916a-4c319e403b36)
![image](https://github.com/metersphere/metersphere/assets/78218624/f1b57458-14fc-4ba2-8511-5451372e5099)

**Comment by zrfit** [comment]
您好，感谢反馈！环境配置-全局前置脚本-从api定义导入-选择数据-选择环境-导入后的脚本域名默认取环境的第一个域名。
