### ISSUE TITLE
[BUG]请求设置的Cookie替换不了配置环境-->HTTP配置设置的请求头的Cookie

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#25258]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

 v2.10.2-lts-b028f4ea

### 使用外置数据库

否

### 问题描述

请求头设置了Cookie，环境变量也设置了Cookie，查看请求内容
请求的中设置的Cookie显示为 Cookie :chase
环境变量的设置的Cookie显示为Cookie：Rl
两个：显示的位置不同

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/23476281/1b37fc8a-a74a-450d-be08-85f4e29ed3e5)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
您好，目前的设计上，这种情况就是会多个Cookie值，不会替换，到V3.0我们会再规划。
