### ISSUE TITLE
[BUG]接口测试swagger导入时选了导入模块，导入后目录下面会自动创建未规划接口文件夹，应该直接导入到模块路径下。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#25255]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.0lts

### 使用外置数据库

否

### 问题描述

接口测试swagger导入时选了导入模块目录
<img width="360" alt="d74ae278e4334e7e189e909a5ead90a" src="https://github.com/metersphere/metersphere/assets/83771182/b30423af-b1c1-4287-820a-4de908e1c6c7">

导入后目录下面会自动创建未规划接口目录，应该直接导入到灰度发布路径下
<img width="879" alt="7ffe93a34e48954832c6f57e7cca932" src="https://github.com/metersphere/metersphere/assets/83771182/f169003b-2f30-4c5c-9dfc-4bdae4ce0c8f">

导入文件如下
[swagger导入灰度发布接口.zip](https://github.com/metersphere/metersphere/files/11889567/swagger.zip)

### 重现步骤

接口测试swagger导入时选了导入模块目录，导入后目录下面会自动创建未规划接口目录，应该直接导入到灰度发布路径下

**Comment by zrfit** [comment]
您好，感谢反馈！文件下载后解压失败，辛苦再发下文件。确认下swagger中接口对应的模块是什么？如果swagger接口的模块是a ，导入选择模块b，那么会在模块b下新建模块a并导入接口。

**Comment by zrfit** [comment]
您好，文件中的tags为空，导入ms会默认处理为未规划模块。
