### ISSUE TITLE
[BUG]  测试计划里面的场景，在不勾选失败继续的情况下，失败的步骤应该有重试（目前没有）

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#25253]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

测试计划里面的场景，在不勾选失败继续的情况下，失败的步骤应该有重试（目前没有）

### 重现步骤

1、场景未勾选失败继续
![image](https://github.com/metersphere/metersphere/assets/103925124/954f2cc1-546d-4ca6-80c1-1ad5a84d40c5)
2、测试计划关联了上面的场景，且配置了失败重试3次去执行
![image](https://github.com/metersphere/metersphere/assets/103925124/52186ea4-e75c-4a9a-8668-296f85b1a244)
3、异常的点:步骤三未重试
![image](https://github.com/metersphere/metersphere/assets/103925124/9aa3e616-674f-4947-9c46-1476c54b5cd8)

### 期待的正确结果

 在不勾选失败继续的情况下，失败的步骤还是应该有重试，

举例：场景未勾选失败继续，步骤三执行失败（目前没有重试），应该执行重试，重试第二次的时候，成功了，那么下面的步骤应该继续执行了。
![image](https://github.com/metersphere/metersphere/assets/103925124/de957ef5-26e8-4757-9acb-f20aca7bae10)

**Comment by zrfit** [comment]
您好，感谢反馈！场景默认是失败继续，如果主动取消这个配置，则是希望场景失败停止；测试计划那里相当于是一个全局的失败重试配置，执行的时候场景的配置优先。

**Comment by fit2cloud-yaochunrong** [comment]
是的，按场景执行么有问题，**核心问题还是说  在不够选失败继续的情况下，失败的步骤还是应该有重试，**

举例：场景未勾选失败继续，步骤三执行失败（目前没有重试），应该执行重试，重试第二次的时候，成功了，那么下面的步骤应该继续执行了。@zrfit
