### ISSUE TITLE
[BUG]PostMan导入接口缺失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2525]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9.1
**Bug 描述**
简要描述您碰到的问题
实际的PostMan json文件内有10个接口，但是读出来的内容仅仅只有8个接口

**Bug 重现步骤**
1.  接口定义---》导入----》选择PostMan类型---》选择文件
**期待的正确结果**
正确情况下应该是什么样的？
总共是10个接口
**截图**
如果有截图，请附上截图.
![WechatIMG92](https://user-images.githubusercontent.com/32027713/117288776-7111f480-ae9e-11eb-85a9-218d815590bb.png)

<img width="913" alt="WechatIMG117" src="https://user-images.githubusercontent.com/32027713/117288357-fe087e00-ae9d-11eb-8a85-3950321306b3.png">

**Comment by xulinde** [comment]
方便发下您的json文件吗，我们这边没复现呢

**Comment by dashenyucainiao** [comment]
[贷后管理系统-苑冬亮.json.zip](https://github.com/metersphere/metersphere/files/6440599/-.json.zip)

**Comment by dashenyucainiao** [comment]
你可以解压之后试一下，是PostMan的


[贷后管理系统.json.zip](https://github.com/metersphere/metersphere/files/6440602/json.zip)

**Comment by zyyfit** [comment]
您好，导入接口定义的话，相同的接口都合并了，会在一个接口里添加多个用例，导入场景的话会每个接口都显示出来的
