### ISSUE TITLE
[BUG]一键安装脚本配置url错误

### ISSUE THREAD

**Issue by xie0723** [metersphere/metersphere#25251]
### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

使用脚本：curl -sSL https://resource.fit2cloud.com/metersphere/metersphere/releases/latest/download/quick_start.sh | bash

问题截图：
![20230628-112138](https://github.com/metersphere/metersphere/assets/10458419/1ee3d7a1-5b2b-4b5a-9ab5-0f52f486c22f)

### 重现步骤

使用脚本：curl -sSL https://resource.fit2cloud.com/metersphere/metersphere/releases/latest/download/quick_start.sh | bash

**Comment by liuruibin** [comment]
您好，脚本中包含一段python脚本，需要您的环境中有python环境
