### ISSUE TITLE
[BUG]同步jira缺陷时的摘要框太小了，应该是一个大文本编辑框

### ISSUE THREAD

**Issue by NeoChan01** [metersphere/metersphere#25250]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

![meter01](https://github.com/metersphere/metersphere/assets/124759943/84b8586f-18c9-4273-8e7e-755d26f07a1e)

### 重现步骤

如标题

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
