### ISSUE TITLE
[BUG]前置脚本使用RSA相关方法的时候报错提示使用了非公开的方法

### ISSUE THREAD

**Issue by juanmaocxy** [metersphere/metersphere#25259]
### 联系方式

juanmaocxy@163.com

### MeterSphere 版本

2.10.2-lts

### 使用外置数据库

是

### 问题描述

在接口测试中前置脚本使用了RSA相关的方法，调用jmeter执行时报使用了非公开方法

尝试修改docker-compose，增加JAVA_TOOL_OPTIONS="--add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.security.pkcs=ALL-UNNAMED --add-opens java.base/sun.security.x509=ALL-UNNAMED" 发现服务启动就报错了，经查资料所得，好像是jdk17不支持使用JAVA_TOOL_OPTIONS插入启动参数

### 重现步骤

以下是我的部分脚本：
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.ByteArrayOutputStream;
import java.security.*;
import java.security.interfaces.RSAKey;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import cn.hutool.crypto.digest.DigestUtil;
import com.alibaba.fastjson.JSONObject;

/** *//**
     * 加密算法RSA
     */
    public static final String KEY_ALGORITHM = "RSA";

    public Map genKeyPair(int size) throws Exception {
        KeyPairGenerator keyPairGen = KeyPairGenerator.getInstance("RSA");

        keyPairGen.initialize(size, new SecureRandom());
        KeyPair keyPair = keyPairGen.generateKeyPair();
        RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();
        RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
        String publicKeyString = Base64.getEncoder().encodeToString(publicKey.getEncoded());
        String privateKeyString = Base64.getEncoder().encodeToString(privateKey.getEncoded());
        Map result = new HashMap();
        result.put("privateKey", privateKeyString);
        result.put("publicKey", publicKeyString);
        return result;
    }
    
Map keys = genKeyPair(1024);

以下是报错内容：
Sourced file: inline evaluation of: ``import javax.crypto.Cipher; import javax.crypto.spec.IvParameterSpec; import jav . . . '' : Typed variable declaration : Typed variable declaration : Error in method invocation: Cannot access method getEncoded() in 'class sun.security.x509.X509Key' :java.lang.IllegalAccessException: class bsh.Reflect cannot access class sun.security.x509.X509Key (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @61322f9d : at Line: 116 : in file: inline evaluation of: ``import javax.crypto.Cipher; import javax.crypto.spec.IvParameterSpec; import jav . . . '' : .getEncoded ( )

**Comment by fit2-zhao** [comment]
感谢反馈，我们内置jdk17 对安全方面有限制，暂时不支持这种方式，你可以再尝试一下其他替代方式。

**Comment by juanmaocxy** [comment]
> 感谢反馈，我们内置jdk17 对安全方面有限制，暂时不支持这种方式，你可以再尝试一下其他替代方式。

你好，请问有demo么，我这边尝试了一下，好像都不太行
