### ISSUE TITLE
[FEATURE]UI测试场景中复制了一个其他场景，此外没有其他步骤时，无法使用批量操作功能

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25257]
### MeterSphere 版本

v2.10.2-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

1.创建一个场景，场景里复制一个其他场景，没有批量操作的按钮。如果想要给复制的场景里的步骤批量设置截图等操作，就没办法操作，很不方便。
2.还要再额外加个步骤才会出来批量操作入口。建议优化下，就算最外层只有一个步骤，也提供批量操作的入口。
![image](https://github.com/metersphere/metersphere/assets/88763608/b3d8d293-671d-47b2-bc20-ef0d0e09f388)
![image](https://github.com/metersphere/metersphere/assets/88763608/7c724e96-ac7f-47d1-b30a-7f098123e187)
![image](https://github.com/metersphere/metersphere/assets/88763608/18227d54-5112-45da-b713-0b45ebcb6335)

### 请描述你建议的实现方案

建议优化下，就算最外层只有一个步骤，也提供批量操作的入口。

**Comment by Hyyfit** [comment]
感谢反馈，我们会在近期的版本里优化
