### ISSUE TITLE
[BUG]测试用例批量操作有权限时报服务器错误

### ISSUE THREAD

**Issue by janehugit** [metersphere/metersphere#25261]
### MeterSphere 版本

 v2.10.2-lts

### 使用外置数据库

是

### 问题描述

测试用例批量操作时，如果没有权限，弹出服务调用出错

### 重现步骤

复现步骤：
1. 以项目成员的身份登录，进入项目
2. 进入测试跟踪，功能用例
3. 批量选择测试用例并点击编辑
4. 选择属性

实际结果：弹出服务调用出错
![752648ec9c17aad35f09da17cdd14ecd](https://github.com/metersphere/metersphere/assets/135193527/e08ed067-41a0-489c-a7da-c228b9ec59e8)

### 期待的正确结果

期望结果：给出正常的提示，例如：无批量操作权限

**Comment by zrfit** [comment]
您好，感谢反馈！没有批量编辑权限编辑按钮是不能点击的，是有批量编辑权限报这个问题吧？如果是有编辑权限报这个问题，计划v2.10.3-lts修复。

**Comment by janehugit** [comment]
出现该问题的账号之前是项目成员的权限，多选用例后可以点击编辑按钮，但是编辑之后报这个错。
该账号的权限改成项目管理员之后，再次编辑可以正常编辑。
所以我理解是本身没有批量编辑权限的账号去批量编辑报的这个错，这个错误提示里也确实写着dose not have permission，但是这个错误提示不应该用脚本语言提示，应该catch之后转换成自然语言。或者跟你说的，没有权限就不能点击编辑按钮。

**Comment by zrfit** [comment]
是的，待v2.10.3-lts发布后尝试。1、无权限账户，不可点击编辑操作 2、有权限用户，可正常编辑。
