### ISSUE TITLE
[BUG]【接口定义】接口-后置脚本里含有sql导出再导入其他环境，后置sql处无法选择运行环境和数据源

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25262]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

【接口定义】接口-后置脚本里含有sql导出再导入其他环境，后置sql处无法选择运行环境和数据源

### 重现步骤

【接口定义】接口-后置脚本里含有sql导出再导入其他环境，后置sql处无法选择运行环境和数据源
![image](https://github.com/metersphere/metersphere/assets/104960608/ca198e0b-2851-479b-9e36-db9c293b6ee7)
![image](https://github.com/metersphere/metersphere/assets/104960608/3935b03a-3d7a-4fd9-adf4-62552718426c)
![image](https://github.com/metersphere/metersphere/assets/104960608/eae94c34-ebc1-4bb1-acbe-0dac38cf745c)

API脚本如下
[Metersphere_Api_Test项目.zip](https://github.com/metersphere/metersphere/files/11891339/Metersphere_Api_Test.zip)

**Comment by 13290445582** [comment]
已知问题，计划于v2.10.3修复。

**Comment by 13290445582** [comment]
v2.10.3已修复，请升级～
