### ISSUE TITLE
[BUG]快捷操作工作空间中文筛选不能用

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25275]
### MeterSphere 版本

v2.10.1，

### 使用外置数据库

否

### 问题描述

1.无法使用中文筛选工作空间
![image](https://github.com/metersphere/metersphere/assets/55130444/9df98e36-a72d-4061-8308-d8e5bce2c95f)

### 重现步骤

1.点击工作空间，搜索框输入中文后会直接跳出输入框

### 期待的正确结果

可以使用筛选条件搜到中文工作空间

**Comment by 13290445582** [comment]
您好，该问题在最新版本未复现，建议切换下浏览器尝试或者清除下浏览器缓存，建议升级至最新版。

**Comment by wan92hen** [comment]
Windows 下的 Chrome 及 Edge 浏览器都存在跟问题，在 Mac 上试了下确实是正常的。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/e924da3d-be23-4003-9f55-7bfe77aa1775)
windows chrome v109.0.5414 也正常。

**Comment by 13290445582** [comment]
最新版本已发布，请升级，若存在问题，请重新提issue。
