### ISSUE TITLE
[BUG]导入的swagger文档中的date类型无法解析，解析为了null

### ISSUE THREAD

**Issue by zhouxiongjie1997** [metersphere/metersphere#25274]
### 联系方式

3095500370@qq.com

### MeterSphere 版本

v2.10.2-lts-b028f4ea

### 使用外置数据库

否

### 问题描述

导入的swagger文档中的date类型无法解析，解析为了null

### 重现步骤

1.导入的接口字段数据类型为date
2. 导入后变为了null

### 期待的正确结果

显示正确的date数据类型

**Comment by 13290445582** [comment]
date类型数据指的是这个截图中的类型吗？
![image](https://github.com/metersphere/metersphere/assets/128017892/b8aee84e-9d24-4ab4-9e27-569bac0950f1)
只支持红框里的几种类型，可以发下您的复现录屏和复现场景吗

**Comment by zhouxiongjie1997** [comment]
是的，类型就为date

**Comment by 13290445582** [comment]
根据上面的截图提示，仅支持使用array，boolean，integer，number，object，string类型。

**Comment by zhouxiongjie1997** [comment]
这个不能增加需求吗，实际api就有date类型的

**Comment by 13290445582** [comment]
您好，上边给您的截图是swaager本身不支持Date类型。
您可以提一个FEATURE需求交给我们产品评估下，感谢理解与支持～

**Comment by zhouxiongjie1997** [comment]
![image](https://github.com/metersphere/metersphere/assets/49423711/99337e32-5725-4f33-84e9-a0fe2cb68871)
接口文档是这样展示的

**Comment by 13290445582** [comment]
您好，导入的文件可以发我一下吗，谢谢。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
