### ISSUE TITLE
[BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#25278]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

是

### 问题描述

metersphere系统运行一段时间后，企业微信没有收到通知：
![图片](https://github.com/metersphere/metersphere/assets/23067502/48fd1c34-6aaf-416f-b813-ed39e5b76447)

### 重现步骤

metersphere系统运行一段时间后，企业微信没有收到通知。

### 期待的正确结果

可以收到通知。

**Comment by 13290445582** [comment]
您好，检查一下Webhook地址是否正确？检查一下测试计划是否执行结束？执行结束状态与任务通知配置是否一致？

**Comment by xiaochongzi-ling** [comment]
您好，webhook地址正确，测试计划执行结束，并且之前通知接收都正常，在没有调整任何内容的情况下，突然某天开始无法收到。需要帮忙看下如何从服务层面排查这个问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





 
您好，检查一下Webhook地址是否正确？检查一下测试计划是否执行结束？执行结束状态与任务通知配置是否一致？

**Comment by 13290445582** [comment]
新建一个测试计划关联一些其他的执行失败的用例测试一下呢？是所有的定时任务通知都无法收到，还是只有这一个测试计划的定时任务通知无法收到？

**Comment by xiaochongzi-ling** [comment]
所有项目的所有定时任务通知都无法收到。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 上午10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





 
新建一个测试计划关联一些其他的执行失败的用例测试一下呢？是所有的定时任务通知都无法收到，还是只有这一个测试计划的定时任务通知无法收到？

**Comment by 13290445582** [comment]
升级下最新版本吧

**Comment by xiaochongzi-ling** [comment]
之前版本存在出现这个问题，升级到2.10之后自动好了，后来又自动出现，应该和版本没有关系，希望可以协助提供下排查这个问题的路径以及可能原因。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





 
升级下最新版本吧

**Comment by youliyuan-fit2cloud** [comment]
> 之前版本存在出现这个问题，升级到2.10之后自动好了，后来又自动出现，应该和版本没有关系，希望可以协助提供下排查这个问题的路径以及可能原因。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年6月29日(星期四) 中午11:22 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278) 升级下最新版本吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，发下日志，定时任务执行时后台日志 test-track模块下的info.log

**Comment by xiaochongzi-ling** [comment]
您好，帮忙看下如何解决，多谢：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





  
之前版本存在出现这个问题，升级到2.10之后自动好了，后来又自动出现，应该和版本没有关系，希望可以协助提供下排查这个问题的路径以及可能原因。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" @.&gt;; 发送时间:&nbsp;2023年6月29日(星期四) 中午11:22 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278) 升级下最新版本吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，发下日志，定时任务执行时后台日志 test-track模块下的info.log

**Comment by youliyuan-fit2cloud** [comment]
> 

没有收到附件～

**Comment by xiaochongzi-ling** [comment]
您好，没有拿到log文件，只有截图，帮忙看下：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





   
没有收到附件～

**Comment by youliyuan-fit2cloud** [comment]
> 您好，没有拿到log文件，只有截图，帮忙看下：
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年6月29日(星期四) 晚上6:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278) 没有收到附件～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

log截图也没看见啊。。。你在企业微信交流群吗？不在群里扫码加入吧，二维码如下图。如果在群里面说明是在哪个群，昵称信息，我们再联系你。
![image](https://github.com/metersphere/metersphere/assets/54612864/8dd60dc6-98cb-4f16-8164-cc308c1e3cb1)

**Comment by xiaochongzi-ling** [comment]
好的，多谢，我在48群，昵称：玲子。日志截图见附件。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 中午1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278)





  
您好，没有拿到log文件，只有截图，帮忙看下：
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" @.&gt;; 发送时间:&nbsp;2023年6月29日(星期四) 晚上6:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]metesphere测试计划定时任务执行一段时间后没有发送企业微信通知 (Issue #25278) 没有收到附件～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
log截图也没看见啊。。。你在企业微信交流群吗？不在群里扫码加入吧，二维码如下图。如果在群里面说明是在哪个群，昵称信息，我们再联系你。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
