### ISSUE TITLE
创建功能用例选择保存并继续添加按钮，保存成功但是页面内容没有清空

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#25280]
### 联系方式

14707070227

### MeterSphere 版本

 v2.10.2-lts-b028f4ea

### 使用外置数据库

否

### 问题描述

创建功能用例，选择了保存并继续添加按钮，保存成功了，但是页面内容没有清空，还是之前的内容，添加要手动一个个删除之前的内容

### 重现步骤

1. 创建功能，填写好内容，点击保存并继续添加按钮
2. 保存成功，但是页面内容没有清空，还是之前的内容，添加要手动一个个删除之前的内容

### 期待的正确结果

期待保存成功，页面内容清空，不需要手动一个个删除之前的内容

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/82e3e291-65aa-493e-92a1-0b1a5e5633b2)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
重复问题，已关联。
