### ISSUE TITLE
[BUG]测试计划，关联某一模块下面的用例，点击【确定】会直接把关联用例页面给关闭了，测试跟踪重度用户反馈，能不能只关联不关闭页面。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#25287]
### 联系方式

王进

### MeterSphere 版本

v2.10.2

### 使用外置数据库

否

### 问题描述

测试计划，关联某一模块下面的用例，点击【确定】会直接把关联用例页面给关闭了，测试跟踪重度用户反馈，能不能只关联不关闭页面。

### 重现步骤

1. 选择某一模块，关联用例，然后点击确定
<img width="1156" alt="1688024107076" src="https://github.com/metersphere/metersphere/assets/76033005/9818f9fb-37f5-4041-a697-dc3a74680f8c">

2. 关联用例页面会被关闭。 

3. 实际项目中，用户可能要关联几个模块下面的用例，意味着要打开”关联用例页面“几次。

4. 现在不支持同时一次关联多个模块的用例。

### 附加信息

这是一个易用性的bug，企业客户反馈。
关联用例页面已经提供了”X"图标关闭页面了，如果【确定】也关闭页面，似乎功能重复

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
