### ISSUE TITLE
[BUG] 【接口测试】通过 MeterSphere 导入Swagger json 格式文件后，必填项未被勾选

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25290]
### 联系方式

452988409@qq.com

### MeterSphere 版本

V2.10.2-lts

### 使用外置数据库

否

### 问题描述

导入文件：
[swaggerApi (7).txt](https://github.com/metersphere/metersphere/files/11903452/swaggerApi.7.txt)

1. 在MeterSphere上通过swagger json 文件导入，必填字段没有在MeterSphere上勾选

![image](https://github.com/metersphere/metersphere/assets/33945037/82e404c6-a43f-4107-986e-e03e16794973)

![image](https://github.com/metersphere/metersphere/assets/33945037/155e51b4-6b6a-4bcb-849a-afa02da1abe4)

![image](https://github.com/metersphere/metersphere/assets/33945037/b6cafeef-cf34-41bb-ac37-5fd96988e15d)

在导入的jsonscheam当中，item下面的必填都没有显示在MeterSphere上，应该是代码逻辑bug。

2. 还有一个问题，在MeterSphere上创建一个接口，请求体使用JSONSchema，根节点root为array类型，里面嵌套object类型，导出swagger格式，导出的json文件并没有必填显示。

![image](https://github.com/metersphere/metersphere/assets/33945037/29e541f9-82d5-44db-b106-12010a05016d)

![image](https://github.com/metersphere/metersphere/assets/33945037/ab7752d9-cbdd-4976-84ac-0d3373e74160)

### 重现步骤

同上

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交至tapd平台，开发跟进，后续版本修复。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
