### ISSUE TITLE
[BUG]【UI测试】修改场景里的原指令步骤名称或者定位值，运行结果会出现重复步骤而且顺序混乱。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25296]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

【UI测试】新建登录指令，然后将其引用到场景里保存运行后，修改登录指令里的定位值，点击保存，再去运行场景生成报告，发现报告里多重复了几个步骤，而且顺序混乱。

### 重现步骤

1.【UI测试】新建登录指令，然后将其引用到场景里，还添加了两个步骤进行保存运行
2. 修改登录指令里的定位值，点击保存，再去运行场景生成报告，发现报告里多重复了几个步骤，而且顺序混乱。
![image](https://github.com/metersphere/metersphere/assets/104960608/729669da-4b0f-4b14-af0e-fb853d3f913d)
![image](https://github.com/metersphere/metersphere/assets/104960608/c7bd26a8-b62f-4c38-8dff-797d562833ec)
3.修改登录指令里的步骤名称，点击保存，运行场景生成报告，报告里还是多了重复步骤顺序混乱
![image](https://github.com/metersphere/metersphere/assets/104960608/351a5764-2ea3-4590-ba15-c3e1b9ca7358)
![image](https://github.com/metersphere/metersphere/assets/104960608/788bd19e-e291-478a-8934-797200ea3146)

**Comment by fit2-zhao** [comment]
感谢反馈，已经了解到您的困惑点，目前设计层面确实允许这种操作会出现重复情况，建议您从使用层面先进行规避，目前逻辑不会再进行大规模改造了。
