### ISSUE TITLE
[BUG]系统从1.20lts升级直接至2.10lts，系统的docker-compose没有自动升级，还需要手动对docker compose升级

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#25293]
### MeterSphere 版本

V2.10.2-lts

### 使用外置数据库

否

### 问题描述

[BUG]系统从1.20lts升级直接至2.10lts，系统的docker-compose没有自动升级，还需要手动对docker compose升级

目前给2个客户做升级系统。发现：系统从1.20.X-lts升级直接至2.10.2-lts，升级前关闭了docker，手动先将docker和docker-compose卸载删除（步骤按照官方提供的《1.20 LTS 至2.10 LTS 升级指南》），然后做的升级，升级后发现docker-compose没有升级，还是最初的版本。请确认install.sh脚本是否需要优化。

### 重现步骤

[BUG]系统从1.20lts升级直接至2.10lts，系统的docker-compose没有自动升级，还需要手动对docker compose升级

目前给2个客户做升级系统。发现：系统从1.20.X-lts升级直接至2.10.2-lts，升级前关闭了docker，手动先将docker和docker-compose卸载删除（步骤按照官方提供的《1.20 LTS 至2.10 LTS 升级指南》），然后做的升级，升级后发现docker-compose没有升级，还是最初的版本。请确认install.sh脚本是否需要优化

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/3f0106c8-23dc-4b75-8d7f-32203491c811)
![image](https://github.com/metersphere/metersphere/assets/78218624/ccdd23e6-8487-49fa-b771-9d93c246eb47)

**Comment by youliyuan-fit2cloud** [comment]
/
Duplicate of #23634
