### ISSUE TITLE
[BUG]连接sql server2008r2报异常

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#25299]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

1、连接sql server2008r2报异常，这个问题原来是修复过的，现在又不行了

![image](https://github.com/metersphere/metersphere/assets/43720321/e8b2d258-9e00-4982-bccb-34fc1dc88acd)

### 重现步骤

1、连接sql server2008r2报异常，这个问题原来是修复过的，现在又不行了

### 期待的正确结果

正常可连接sql2008r2 、 2019r2

**Comment by youliyuan-fit2cloud** [comment]
https://github.com/metersphere/metersphere/issues/13631
![image](https://github.com/metersphere/metersphere/assets/54612864/f2cecafd-9c45-42d9-9701-e83ab28f5295)
你好，参考这个热心用户回复的方案解决。

**Comment by goodboyxzmkk** [comment]
你好，V2.10版本没有ms-server这个容器，直接进这个路径提示目录不存在


请问这个问题要怎么处理









孤恋秋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]连接sql server2008r2报异常 (Issue #25299)





 
#13631
 
 你好，参考这个热心用户回复的方案解决。

**Comment by youliyuan-fit2cloud** [comment]
> 你好，V2.10版本没有ms-server这个容器，直接进这个路径提示目录不存在 请问这个问题要怎么处理 孤恋秋 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年6月30日(星期五) 下午3:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]连接sql server2008r2报异常 (Issue #25299) #13631 你好，参考这个热心用户回复的方案解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请仔细看下“长期解决方案”

**Comment by goodboyxzmkk** [comment]
线下部署的，没办法都统一都使用最新版本的数据库，所以升级版本这个解决方案不现实


那么有没办法解决连接旧版本的问题？




孤恋秋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 下午2:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]连接sql server2008r2报异常 (Issue #25299)





  
你好，V2.10版本没有ms-server这个容器，直接进这个路径提示目录不存在 请问这个问题要怎么处理 孤恋秋 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" @.&gt;; 发送时间:&nbsp;2023年6月30日(星期五) 下午3:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]连接sql server2008r2报异常 (Issue #25299) #13631 你好，参考这个热心用户回复的方案解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
请仔细看下“长期解决方案”

**Comment by youliyuan-fit2cloud** [comment]
那只能用上面说的临时解决方案，把我们平台的java版本降低和你们的mysql适配了。
需要改api-test 和node-controller 容器里面的文件。

**Comment by goodboyxzmkk** [comment]
如何修改？麻烦给个解决方案，谢谢




孤恋秋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]连接sql server2008r2报异常 (Issue #25299)





 
那只能用上面说的临时解决方案，把我们平台的java版本降低和你们的mysql适配了。
 需要改api-test 和node-controller 容器里面的文件。

**Comment by youliyuan-fit2cloud** [comment]
你好，上面回复的热心网友截图中已经说明了， “临时解决方案”。看不到？还是有什么问题？

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/7cd6a9c8-caf5-440a-bdb6-5bf3f97ac05e)

**Comment by goodboyxzmkk** [comment]
麻烦看一下上下文，参考临时解决办法，在V2.10版本没有ms-server这个容器

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/89d82256-81f2-4d0e-aa30-9c201aa64639)
这里没说清楚？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
