### ISSUE TITLE
[BUG]功能用例在测试计划中执行完成后，执行结果未自动回写至用例列表中，需修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#25306]
### MeterSphere 版本

V2.10.2lts

### 使用外置数据库

否

### 问题描述

功能用例在测试计划中执行完成后，执行结果未自动回写至用例列表中，需修复

### 重现步骤

1.选择一条功能用例并随机关联一条自动化用例；
2.创建测试计划，勾选自动更新状态，添加该功能用例和对应的自动化用例；
3.执行测试计划，在自动化用例执行完成后，查看测试计划中功能用例执行结果是否自动回写成功；
4.查看功能用例列表页对应功能用例执行结果是否自动更新；

### 期待的正确结果

3.测试计划中用例执行结果与自动化用例执行结果保持一致；
4.功能用例列表页对应功能用例的执行结果更新为与最新一次测试计划中该用例执行结果一致。

实际结果：
3.OK；
4.功能用例列表页对应用例执行状态仍显示为：未执行。

### 附加信息

![332aa9551df132af093c73c2f7b59ac](https://github.com/metersphere/metersphere/assets/92150453/2f5f5af2-f9b0-423d-9bc0-0e7a46efa0d6)
![f93d82d040c3191bab68a72f9d8281c](https://github.com/metersphere/metersphere/assets/92150453/90a2d1fe-772b-4f86-b368-5ff7d6474a6c)

**Comment by 13290445582** [comment]
感谢您的反馈，我们将在v2.10.3修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
