### ISSUE TITLE
[BUG]性能测试报告详情打开报错，浏览器崩溃

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#25305]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

性能测试报告详情打开报错，浏览器崩溃，压测时间短的报告可以打开，这份打不开的报告压测时间3分钟，16并发。

### 重现步骤

1、16并发持续3分钟压测（报告聚合时间设置的10秒）
2、压测结束后打开报告详情

实际结果：
打开报告详情报错，浏览器崩溃

### 期待的正确结果

压测完毕，报告能正常查看

### 附加信息

![load_report](https://github.com/metersphere/metersphere/assets/5198427/b5463890-a10b-4286-bed6-31b2132744d0)
![crash](https://github.com/metersphere/metersphere/assets/5198427/24df89ee-2db8-4b56-a725-aac1271e33b3)

v1.20.17-lts版本提过这个问题（BUG号：24454），目前已升级到最新的v2.10.2-lts（全新安装，数据库只有这一个性能测试任务）还是存在此问题。

**Comment by maninhill** [comment]
浏览器崩溃问题要想办法解决，至少是优化，做问题的终结者。

**Comment by liuruibin** [comment]
您好，我们用同样的时长进行测试没有出现这个问题，方便将您的场景提供给我们进行排查吗，邮件发送至: bin@fit2cloud.com

**Comment by xieqione** [comment]
压测脚本和数据已发送至邮箱：[bin@fit2cloud.com](mailto:bin@fit2cloud.com)，请注意查收

**Comment by liuruibin** [comment]
<img width="1337" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/fe781449-2823-42a7-bd74-b4736ceb553a">
我用同一个jmx进行测试，时长5分钟资源消耗很平稳，并无出现浏览器崩溃的情况。您是否更换过其他浏览器或电脑进行测试过呢

**Comment by xieqione** [comment]
换过的，好几个同事都反馈有这个问题，我现在搭建一套新环境，重新跑一下，如果有问题直接把数据库导出来给你们排查下吧，请求打服务全失败和成功不一样的。我重新搭建的环境，设置的用这个jmx跑3分钟，实际跑了1分钟就挂住了，直接reporting状态了，然后浏览器就崩了。
![image](https://github.com/metersphere/metersphere/assets/5198427/b4c853b2-66d6-45c8-a9bc-600205e47326)

**Comment by liuruibin** [comment]
jmeter容器没到3分钟就自行退出了吗

**Comment by xieqione** [comment]
是的。进入报告里，还能点击立即停止，压测没有正常结束，但是报告外又一直卡在reporting状态。
![image](https://github.com/metersphere/metersphere/assets/5198427/e8e808e8-c968-4dba-aa3f-abdc374f5422)
![image](https://github.com/metersphere/metersphere/assets/5198427/3a380d21-3713-442e-bc78-2c2455b3d6f3)
这个是在最新的版本上测试的，重新部署的环境，就这一个场景。之前v1.20.17-lts还没有这种情况。昨天想把数据库导出发给你们看看的，但是最新版数据库导出报错。
![image](https://github.com/metersphere/metersphere/assets/5198427/cc436c37-3a8d-4276-9c5c-c8518676cd19)

**Comment by xieqione** [comment]
新版mysql验证类型是这样的，修改后会对程序有影响么？
![image](https://github.com/metersphere/metersphere/assets/5198427/f0c7a53e-106e-4148-849a-2039298a8830)

**Comment by xieqione** [comment]
在新搭建的环境上安装部署v2.10.2-lts版本跑了15并发，1分钟压测，生成报告的时候还是导致浏览器崩溃了，且一直显示reporting状态，我把数据库dump出来了，已经发送至邮箱：[bin@fit2cloud.com](mailto:bin@fit2cloud.com)，请注意查收，谢谢。

补充说明一下：v2.10.2-lts版本压测10秒钟就会出现一直卡在reporting的问题，v1.20.17版本压测10秒没有这个问题，可正常变更测试状态为完成。应该是压测脚本的特殊性，具体原因未知。

**Comment by zhangzhaox** [comment]
混合场景如20个业务场景脚本  总事务数约100个  仅运行1.5小时左右  jmeter容器就自动停止关闭了，报告一直处于reporting 状态   
![image](https://github.com/metersphere/metersphere/assets/82088551/faa9feed-e405-4c28-af14-1160b73f8119)

**Comment by liuruibin** [comment]
> 混合场景如20个业务场景脚本 总事务数约100个 仅运行1.5小时左右 jmeter容器就自动停止关闭了，报告一直处于reporting 状态 ![image](https://user-images.githubusercontent.com/82088551/251617447-faa9feed-e405-4c28-af14-1160b73f8119.png)

8003是性能测试模块的端口，出这个错误一般情况下是性能测试模块OOM导致容器重启。仅运行1.5小时是不是后台的jmeter已经退出了？是开源版部署的吗
<img width="1034" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/3f1b173d-8e87-46f7-9ca6-f7e5442ca977">

**Comment by xieqione** [comment]
我之前发给贵司的mysql dump文件有验证么，是不是会导致浏览器崩溃呢？

**Comment by liuruibin** [comment]
> 我之前发给贵司的mysql dump文件有验证么，是不是会导致浏览器崩溃呢？

并没有异常，在我这里仅仅是100% error

**Comment by youliyuan-fit2cloud** [comment]
> 我之前发给贵司的mysql dump文件有验证么，是不是会导致浏览器崩溃呢？

你好，执行性能测试使用的资源池是LOCAL资源池吗？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为无法复现该问题，建议升级到最新的版本v2.10.5-lts，再试试哈，如果还有问题请随时反馈，感谢理解和支持。
