### ISSUE TITLE
[QUESTION] Windows 环境安装失败

### ISSUE THREAD

**Issue by Simple-Stark** [metersphere/metersphere#25308]
### 请描述您的问题

使用版本：2.10.2
电脑配置：
处理器	13th Gen Intel(R) Core(TM) i5-1340P   1.90 GHz
机带 RAM	16.0 GB (15.7 GB 可用)
按照文档 https://metersphere.io/docs/v2.x/installation/offline_installation_windows/ 部署安装
不报错，也无法成功，界面卡在下图不动
![image](https://github.com/metersphere/metersphere/assets/61400566/d7b93ff0-a385-4655-8fc9-d2e1bcc083b1)
docker desktop 如图所示
![image](https://github.com/metersphere/metersphere/assets/61400566/bc69aa99-6e17-4e4d-9cf0-a49bff427220)

**Comment by luty2018** [comment]
你好， 不支持Windows安装的。
