### ISSUE TITLE
[BUG] 【接口测试】TCP 接口被删除，该TCP接口的MOCK还能被调用

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#25303]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

删除某TCP MOCK接口，其它工具还可以正常调用该接口的MOCK

### 重现步骤

1.在某Tcp接口中创建一个 TCP MOCK
2.然后把该接口删除掉
3.用工具调用该MOCK，观察MOCK是否能调通

### 期待的正确结果

将API删除，API在回收站列表中，API状态为废弃，该API的MOCK应该要改为关闭状态，从回收站列表中恢复到接口列表中，MOCK的状态改为开启

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。
