### ISSUE TITLE
[FEATURE] 【UI测试】 UI场景导出再导入后，场景步骤与原场景不匹配

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#25300]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

2.10.2-LTS，1.20.23-LTS

### 使用外置数据库

否

### 问题描述

该UI自动化场景步骤是通过导入其他UI自动化场景组成，然后将该场景导出后换一个项目再重新导入，就会出现所有步骤被全部摊开，并不会显示原场景内的显示逻辑，原子场景的名称也会消失，只剩下所有的步骤。

### 重现步骤

1、新建一个UI自动化场景
2、通过“UI列表导入”导入其他自动化场景
3、保存后导出side文件
4、切换项目，再将步骤三导出的文件再导入
5、编辑导入后的自动化场景，查看步骤

### 附加信息

原步骤显示：
<img width="1155" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/93a3d368-ce4b-41df-838c-12a9e26a77bf">

导入其他项目后步骤：
<img width="1254" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/1c36c5e6-f233-42d4-b4d8-19a3cc11c03c">

**Comment by zrfit** [comment]
您好，感谢反馈！该问题为已知问题，UI测试导出的文件格式为.ide格式，导出后再导入是会平铺所有步骤展示。计划v3会增加导出导入为ms格式文件，则可解决该问题。

**Comment by dashenyucainiao** [comment]
好的，期待3.0可以解决此问题
