### ISSUE TITLE
[BUG]【接口测试】 在使用平台做测试时chrome经常出现崩溃问题

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#25304]
### MeterSphere 版本

v2.10.0

### 使用外置数据库

否

### 问题描述

使用平台做测试chrome经常出现崩溃问题，脚本因为没有保存而丢失

### 重现步骤

浏览器打开比较大的场景执行或者场景中循环次数很大，这个问题经常出现

### 期待的正确结果

浏览器能正常使用

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/1bccbe0c-6d44-4465-9ca7-50d23126b612)

**Comment by maninhill** [comment]
浏览器崩溃问题要想办法解决，至少是优化，做问题的终结者。

**Comment by luty2018** [comment]
> 浏览器崩溃问题要想办法解决，至少是优化，做问题的终结者。

前端白同学周末已经调优了一版，还在测试中。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已优化，升级一下吧。
