### ISSUE TITLE
[BUG]性能测试压测完成下载jtl到本地打开和平台上展示结果不一致

### ISSUE THREAD

**Issue by xieqione** [metersphere/metersphere#25301]
### MeterSphere 版本

v1.20.7

### 使用外置数据库

否

### 问题描述

性能测试压测完成下载jtl到本地打开和平台上展示结果不一致

### 重现步骤

1、平台执行性能测试持续时间3分钟（顺序执行、按迭代次数执行均可）
2、压测结束下载压测报告中的jtl文件到本地，用jmeter打开
3、对比平台报告中请求统计和本地jmeter打开的jtl请求统计结果

实际结果：
平台中展示请求统计结果和本地jmeter中打开jtl中结果不一致，压测接口的请求响应时间越长差异越大

### 期待的正确结果

平台统计请求结果和下载后jtl中结果一致

### 附加信息

第一组对比结果：（接口响应时间比较短的情况）
1、平台压测1分钟
![image](https://github.com/metersphere/metersphere/assets/5198427/a9c67d53-152e-4f01-b99e-1dbc6bd68ae7)
![image](https://github.com/metersphere/metersphere/assets/5198427/20a8ebce-f842-47b6-872c-0ce6317ad378)
第二组对比结果：（接口响应时间比较长的情况）
![image](https://github.com/metersphere/metersphere/assets/5198427/19846248-b842-49c4-b682-01b95d106803)
![image](https://github.com/metersphere/metersphere/assets/5198427/b2146a77-e151-4a62-82c3-1bb00a9aa854)

**Comment by liuruibin** [comment]
您好，我们是采用jmeter -g 来生成报告的额，您可以使用这种方式生成一个html报告进行查看对比

**Comment by xieqione** [comment]
数据量比较小的时候是一致的，生成报告出错的时候差异会比较大，可能也是因为这个Bug：25305

**Comment by liuruibin** [comment]
jmeter 本身提供gui的报告和jtl离线报告两种，我们采用的是jtl的方式，可能和gui的会有一些差异。还有其他因素也会影响测试结果，比如资源池空闲资源多少，kafka的性能等
