### ISSUE TITLE
[BUG] 冗余的/opt/metersphere/data/body的数据文件所占空间越来越大，导致磁盘不够用

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25317]
### MeterSphere 版本

所有

### 使用外置数据库

是

### 问题描述

1、随着使用时间的增加，/opt/metersphere/data/body的数据文件，如：CSV文件、JMX文件等，性能测试和接口测试用到的文件，
当调试时 重复上传文件，导致/opt/metersphere/data/body的数据文件越来越大，但是又没有清理的手段

2、删除文件是假删除
<img width="1178" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/745946bf-6d86-42d1-8812-142fbf648738">

### 重现步骤

1、新建一个接口场景
2、上传一个较大的CSV文件
3、点击调试
4、不断重复（2「修改同名文件内容即可」、3）
5、在不断重复执行4的时候查看/opt/metersphere/data/body的数据文件
6、删除的CSV文件还是存在
7、删除场景、报告 --- 删除的CSV文件还是存在

### 期待的正确结果

1、不要出现文件删不掉的问题、
2、历史的无关联的文件数据能有个按钮什么的清除一下，客户在使用的过程中发现这个数据太大了

**Comment by 13290445582** [comment]
感谢您的反馈，我们将在v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
