### ISSUE TITLE
[BUG] 并发执行测试计划时，场景调试需要等待时间过长

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25316]
### MeterSphere 版本

v2.10.2-lts,v2.10.1-lts 

### 使用外置数据库

否

### 问题描述

问题背景：
1、测试计划”并行“执行，请求数量1600左右
2、测试计划执行总时长为2000S左右
3、有些场景执行时长100S左右
4、均使用的是”local“资源池
5、版本2.10.1LTS
6、资源池的最大线程数为200
在这前提下，接口测试调试执行场景出现了下面的情况
<img width="1420" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/ae043315-5583-41e9-af64-4106a3688a9a">

### 重现步骤

1、测试计划”并行“执行，请求数量1600左右
2、测试计划执行总时长为2000S左右
3、有些场景执行时长100S左右
4、均使用的是”local“资源池
5、版本2.10.1LTS
6、资源池的最大线程数为200
此时执行场景调试（会出现等待时间过长的现象）

### 期待的正确结果

并行执行测试计划时，保留部分线程资源给场景调试

**Comment by fit2-zhao** [comment]
感谢反馈，建议多启几个资源池，批量执行使用一个资源池，调试使用另外资源池，不要使用一个就可以了。

**Comment by sss903065212** [comment]
只有一台机器如何使用另外的资源池

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/8a37d1b8-1925-400a-8a1e-6701132b0bbf)
https://metersphere.io/docs/v2.x/user_manual/system_management/system/#4
请看下我们的用户手册吧，里面有详细说明的。

**Comment by sss903065212** [comment]
这个反馈的意思是，目前只有一台机器，无法添加其他的资源池，此时我在执行测试计划的过程中，其他人做接口自动化测试需要等待的时间太长了，之前1.20.23没有此现象

**Comment by sss903065212** [comment]
升级2.10.1LTS之后按照1.20.23版本的操作此过程，出现了issue标题描述的现象

**Comment by sss903065212** [comment]
大体意思就是升级之后，测试计划影响了接口场景的测试性能，除了前面给出的添加另外的资源池以外，产品层面能否和之前的1.20.23lts版本代码对这部分处理逻辑对比一下看看能否优化一下，或者有其他的建议除了添加另外的资源池

**Comment by sss903065212** [comment]
@youliyuan-fit2cloud @fit2-zhao
