### ISSUE TITLE
[BUG] 场景变量CSV文件本地修改之后点击调试、保存强制要求重新上传，重新上传之后之前的文件在服务器上还存在着

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25324]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

1、场景变量添加CSV文件后，修改了本地的CSV文件，再点击调试或者保存，会强制要求重新上传CSV文件
2、重新上传之后发现，只前上传的问题还存在于/data/body目录下
3、多修改几次本地文件、然后在场景中点击调试、保存 ，再看下/data/body目录 如此反复，磁盘空间被脏数据占满了
![image](https://github.com/metersphere/metersphere/assets/40912189/1b46a37d-48c8-4b86-b6fa-765dd8897c7b)

### 重现步骤

1、新建一个场景
2、场景变量添加一个随意的CSV文件
3、修改2的本地CSV文件
4、在场景中点击调试、保存
5、出现问题描述中的问题
6、重新上传之后，查看/data/body目录 看下是否有多个重名的CSV文件
7、多修改几次本地文件、然后在场景中点击调试、保存 ，再看下/data/body目录 如此反复，磁盘容量越来越小

### 期待的正确结果

1、本地修改的文件不要强制要求重新上传、或者给个选项（确定重新上传、不重新上传）
2、重新上传的话，把之前的文件从服务器上删除掉

**Comment by zrfit** [comment]
您好，感谢反馈！
问题1: 引用的本地附件发生变更需要重新上传附件，目前平台前端使用的Element UI 上传组件规范是这样，防止文件攻击。
问题2:同问题#25317，计划v2.10.4-lts修复。
