### ISSUE TITLE
[FEATURE]全局变量可以支持列表

### ISSUE THREAD

**Issue by Triangel1314** [metersphere/metersphere#2532]
**请描述您的需求或者改进建议.**

在环境变量里设置全局变量的时候可以支持列表的方式，我们现在多个场景需要用到同一个变量，但是变量的值是不一样的，需要全局变量支持列表，不然只能在每个场景单独设置，那就失去了全局变量的意义

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
这个我们内部讨论下再给反馈
