### ISSUE TITLE
[BUG]测试用例ID排序为乱序

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#25321]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

测试用例ID排序为乱序

### 重现步骤
点击ID的上下排序按钮，得到的排序结果上都是乱的

![image](https://github.com/metersphere/metersphere/assets/33934471/5954b16d-f0b5-471c-a220-6457accd698d)

### 期待的正确结果

应该是有序的

**Comment by davidcchen** [comment]
![image](https://github.com/metersphere/metersphere/assets/33934471/829db74f-d022-4523-883e-cb67df8f8d26)

**Comment by 13290445582** [comment]
![image](https://github.com/metersphere/metersphere/assets/128017892/b2eea9b1-654d-4d13-bcb4-57d7f8112071)
您好，根据截屏看起来貌似并没有进行ID排序，请检查下您的操作，若存在问题请及时反馈。
若进行了ID排序后，是这样的显示的：
<img width="149" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/d271e9e6-7769-4dfe-bdca-469d73f10aaa">

**Comment by davidcchen** [comment]
> 
点了，没用，依然是乱序的

**Comment by 13290445582** [comment]
<img width="67" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/17d32efb-c1a7-4d5f-b588-ae9c0d687da3">
排序选择上，颜色会变深色的，发下你排序截图看看，若后台或前台有报错信息也发下看看。

**Comment by davidcchen** [comment]
![image](https://github.com/metersphere/metersphere/assets/33934471/b58b6ec6-e045-4888-9565-86a2ca3bc273)

![image](https://github.com/metersphere/metersphere/assets/33934471/81c21c5f-3d54-48de-8b34-552553556135)

**Comment by davidcchen** [comment]
你们没有测试么？这么简单的case都复现不了？

**Comment by davidcchen** [comment]
查看接口返回值，初步猜测应该是没有按照customNum进行排序，好像是用了默认给的id排序了

**Comment by davidcchen** [comment]
我期间有做用例编号的调整，因为有用例更新和新增

**Comment by davidcchen** [comment]
测试计划也有同样的问题
![image](https://github.com/metersphere/metersphere/assets/33934471/a5839c50-e5ce-4d3d-9048-ed4b2a1a9c16)

**Comment by davidcchen** [comment]
用例评审也是一样的
![image](https://github.com/metersphere/metersphere/assets/33934471/18c30b63-9b2d-401b-ae0f-1a56e92adab2)

**Comment by 13290445582** [comment]
您好，等发布最新的v2.10.3版本再尝试下吧，测试环境未复现。

**Comment by davidcchen** [comment]
最新的v2.10.3版本，依然有问题
![image](https://github.com/metersphere/metersphere/assets/33934471/ac14eee4-9400-424c-96a1-0de7c538f592)

**Comment by davidcchen** [comment]
应该是这个功能开关，开启后，前端排序取值错误
![image](https://github.com/metersphere/metersphere/assets/33934471/92833f2e-4e5a-41f9-9ec4-99d9050fcd87)

**Comment by 13290445582** [comment]
按照提供的升级至v2.10.3的截图，排序没有错误。
自定义ID是字符串类型的，排序按照字符串类型排序，先比较第一个字符，一个字符一个字符进行比较。

**Comment by davidcchen** [comment]
按照字符排序，好像也有问题
![image](https://github.com/metersphere/metersphere/assets/33934471/845a40e2-f710-4c11-b810-feef8b9192fa)

**Comment by davidcchen** [comment]
> 按照提供的升级至v2.10.3的截图，排序没有错误。 自定义ID是字符串类型的，排序按照字符串类型排序，先比较第一个字符，一个字符一个字符进行比较。

这种排序不好用，最好优化下，不然自定义就没用了

**Comment by davidcchen** [comment]
> 按照提供的升级至v2.10.3的截图，排序没有错误。 自定义ID是字符串类型的，排序按照字符串类型排序，先比较第一个字符，一个字符一个字符进行比较。

或者自定义的就按照数字排序，这样有用例更新还可以调整用例顺序，不然无序的用例编号就没有意义了，测试执行的时候还要一个一个去找顺序的用例

**Comment by 13290445582** [comment]
目前采用的自定义ID就为字符串类型，排序逻辑当然是字符串排序，若您有更好的建议请新提FEATUREissue交给我们评估下，根据字符串排序规则，您提供的截图排序并无问题，非缺陷，关闭该issue，感谢理解与支持。
