### ISSUE TITLE
[BUG]【测试跟踪-用例评审-开始评审】用例评审不通过时，不输入评审内容，点击确定，提示信息不明显。多点击几次确定，输入框内提示信息消失

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25339]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-用例评审-开始评审】用例评审不通过时，不输入评审内容，点击确定，提示信息不明显。多点击几次确定，输入框内提示信息消失

### 重现步骤

【测试跟踪-用例评审-开始评审】用例评审不通过时，不输入评审内容，点击确定，提示信息不明显。
问题：多点击几次确定，输入框内提示信息消失

### 期待的正确结果

意见必填信息不消失

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43202800/dee5b94f-45a2-46c5-a0d9-4e50e7ca8b30)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。

**Comment by luty2018** [comment]
这是第三方编辑器的问题， 暂时不改。
