### ISSUE TITLE
[BUG]【测试跟踪-功能用例-查询】 ：特殊字符查询查询框输入下划线、百分号、\t等，查询出的结果有误。【用例评审-用例列表】，【测试跟踪-测试计划-查询】【缺陷列表 】查询也有同样问题、请处理特殊字符查询

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25338]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-功能用例-查询】
查询框输入下划线、%、\t等，查询出的结果到了所有数据

### 重现步骤

【测试跟踪-功能用例-查询】
查询框输入下划线、%、\t等，查询出的结果到了所有数据

### 期待的正确结果

用例里面没有包含% 应该不能查到数据

### 附加信息

![输入百分号能查出数据，不匹配](https://github.com/metersphere/metersphere/assets/43202800/e46f80b9-c38f-40fd-b09f-a31d7c5baec4)

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/ad4511d4-c00e-4111-a639-3a77845862d7)
yong用例评审列表查询也有同样问题

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/e35679f6-6234-4932-82b1-1b0288f299b0)
缺陷列表查询也有同样问题。
请处理查询特殊字符

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。

**Comment by luty2018** [comment]
因为 % 和 _ 是mysql的通配符，要搜索“ % ” “_ ” “ \t ”需要在前面再加一个 '\' 就能查了。
如果我们处理了这些特殊字符，那么类似"xxx%yyy" 这种中间值的模糊匹配就无法支持了。
