### ISSUE TITLE
[BUG] URL引用的自定义常量,实际请求会被`[]`包裹，常量格式${ip}:${port}

### ISSUE THREAD

**Issue by zgxme** [metersphere/metersphere#25333]
### 联系方式

wechat：rickvanilla

### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

环境配置常量
![image](https://github.com/metersphere/metersphere/assets/32547390/29b407a9-136e-4144-b956-2ecd0c608f96)

URL引用自定义常量，参数引用自定义常量
![image](https://github.com/metersphere/metersphere/assets/32547390/22fb64a3-ddff-4a10-9c1c-25daafea07e1)

### 重现步骤

XXX

### 期待的正确结果

URL引用的自定义常量，不会被`[]`包裹

**Comment by zgxme** [comment]
需求是 请求返回json response，我要提取里面的某个字段，这个字段是个ip:port形式。

然后我用这个字段去请求

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
