### ISSUE TITLE
[FEATURE]接口case的编辑界面，目前请求头会标注个数，是否请求体也标注下有无问题，响应结果中，断言标注下失败数量，方便查看

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#25330]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：接口case的编辑界面，目前请求头会标注个数，是否请求体也标注下有无问题，响应结果中，断言标注下失败数量，方便查看
原因：入参最好都能标注下，方便查看，而不是要一页页的翻找，如果标注了，很容易就定位到问题

**Comment by luty2018** [comment]
好的， 这个可以优化

**Comment by luty2018** [comment]
v3.0已支持，建议使用v3.0版本。
