### ISSUE TITLE
[BUG]个人信息设置，去掉姓名点确定 提示信息和输入框信息不一致

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25334]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

个人信息设置，去掉姓名点确定 提示信息和输入框信息不一致

### 重现步骤

个人信息设置，去掉姓名点确定 提示信息和输入框信息不一致

### 期待的正确结果

提示信息和输入框信息显示一致

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43202800/54aaca7d-4567-432b-9701-8f662bad460d)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
