### ISSUE TITLE
[FEATURE]场景编辑调试界面中，对运行时间的统计，单位是ms，是否可以动态显示单位，如果数字比较大，就显示s（秒）或者min（分钟）

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#25331]
### MeterSphere 版本

2.8.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

需求：场景编辑调试界面中，对运行时间的统计，单位是ms，是否可以动态显示单位，如果数字比较大，就显示s（秒）或者min（分钟）
原因：所有的测试用例编辑完成后，都要按照时间进行优化，有些测试用例确实是用时比较大，动态显示单位可以一眼就知道具体结果，不用去计算

**Comment by luty2018** [comment]
暂无规划。
