### ISSUE TITLE
[BUG]新建用例和查看用例时，责任人数据显示不一致。选择责任人时不用显示邮箱。保存用例到列表，查看用例详情和列表模块展示不一致

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25337]
### MeterSphere 版本

1.20.1-lts

### 使用外置数据库

否

### 问题描述

新建用例和查看用例时，责任人数据显示不一致。选择责任人时不用显示邮箱

### 重现步骤

1、新建用例选责任人显示了邮箱
2、查看用例不显示邮箱

显示不一致

### 期待的正确结果

显示一致

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43202800/8dd02b25-5283-46d7-984c-a5c77a84471d)

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/f153fe66-4228-4c24-9aac-21b1d32794ad)
查看用例，和用例列表，显示的模块字段不一样

**Comment by zrfit** [comment]
您好，感谢反馈！
问题1:新建用例责任人下拉显示邮箱是为了区分重名用户且可通过邮箱搜索责任人。
问题2:未复现模块显示不一致问题，请提供详细操作复现步骤。

**Comment by xhy12** [comment]
查看用例，用例只显示最后一层级，列表显示的所有层级
![image](https://github.com/metersphere/metersphere/assets/43202800/4aca6cae-f459-484e-a53b-8dee765510c8)

**Comment by zrfit** [comment]
编辑页面显示的是就是具体所属模块，列表显示的是全路径。
