### ISSUE TITLE
[BUG] 在项目管理-模板管理创建了新模板，项目管理-操作日志没有记录新的日志

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25346]
### MeterSphere 版本

2.10.3-dev

### 使用外置数据库

否

### 问题描述

在项目管理-模板管理创建了新模板，项目管理-操作日志没有记录新的日志
![image](https://github.com/metersphere/metersphere/assets/43202800/d4ea59ea-2d34-4064-9cf9-9da1a605a215)

### 重现步骤

在项目管理-模板管理创建了新模板，项目管理-操作日志没有记录新的日志

### 期待的正确结果

显示日志

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/be1a76a4-c69c-470f-acf1-a64aa5b9a32b)
已有功能，2.10.1-lts 有数据，但是点击跳转有点问题，用dev环境验证 目前都无记录

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
