### ISSUE TITLE
[BUG]测试跟踪-测试计划-报告统计-编辑】 报告总结编辑时，输入超长内容，点击保存，页面数据显示不全。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25340]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/43202800/94d20506-03da-4f09-9c02-a63b67dd40f5)
测试跟踪-测试计划-报告统计-编辑】 报告总结编辑时，输入超长内容，点击保存，页面数据显示不全。

### 重现步骤

]测试跟踪-测试计划-报告统计-编辑】 报告总结编辑时，输入超长内容，点击保存，页面数据显示不全。

### 期待的正确结果

超长自动换行显示

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。
