### ISSUE TITLE
[BUG]环境配置-数据库配置。什么都不填直接点校验，提示信息不明确

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25342]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

环境配置-数据库配置。什么都不填直接点校验，提示为url can not be null

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/43202800/3183981e-5eb7-40f1-bfd2-ee099971c10d)
环境配置-数据库配置。什么都不填直接点校验，，提示为url can not be null

### 期待的正确结果

中文明确提示需要填写 数据库的驱动 完整url链接地址

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
