### ISSUE TITLE
[BUG]【项目设置】-更多选项-自定义代码片段：标签字段输入字符数过长时点击确定提示提示sql error

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25349]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-更多选项-自定义代码片段：标签字段输入字符数过长时点击确定提示异常信息。
![image](https://github.com/metersphere/metersphere/assets/43202800/4ab44218-21ff-4b21-93c6-dca2bf156dec)

### 重现步骤

【项目设置】-更多选项-自定义代码片段：标签字段输入字符数过长，超过提示字符时点击确定 提示sql error

### 期待的正确结果

保存给出限制，无sql error 

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43202800/e1acf0a8-5f5d-4625-b9b5-63b134c31f89)
后台报错

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
