### ISSUE TITLE
[BUG]【项目设置】-文件管理：点击查看重新上传文件提示保存成功，文件名没有变

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25345]
### MeterSphere 版本

v2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-文件管理：点击查看重新上传文件提示保存成功，文件名没有变

### 重现步骤

步骤：【项目设置】-文件管理：上传一个zip文件 列表文件名信息显示正常
问题：点击查看该文件，看重新上传文件提示保存成功，文件名没有变，列表文件信息也没变
![image](https://github.com/metersphere/metersphere/assets/43202800/882f0402-2f3c-467b-b6de-cec9d1fcb0b8)

### 期待的正确结果

重新上传文件应该刷新

**Comment by youliyuan-fit2cloud** [comment]
转产品和开发回复：
1.文件类型和文件大小要获取最新文件的信息

2.文件名无需修改

  文件名是第一次上传文件时获取的文件名称，用户是可以修改这个名称的
  通过编辑进入到这个页面操作了重新上传文件，这里只用替换文件就行。因为用户并没有修改名称，我们系统也没有修改文件时自动获取文件名的逻辑。
基于用户第一次上传文件时改了名称“1.xls”变更为“场景变量”，重新上传了“2.xlsx”那我们要把名称从“场景变量”变更为“2.xlsx”吗？这不合理

**Comment by xhy12** [comment]
这里看不出变化，重新长传是成功还是失败了呢

**Comment by xhy12** [comment]
只能进入服务器后台检查文件确认吗

**Comment by xhy12** [comment]
基于用户第一次上传文件时改了名称“1.xls”变更为“场景变量”，重新上传了“2.xlsx”那我们要把名称从“场景变量”变更为“2.xlsx”吗？这不合理
——————
这里是重新上传，如果不允许这样操作应该是屏蔽入口吧

**Comment by luty2018** [comment]
> 这里看不出变化，重新长传是成功还是失败了呢

重新上传的时候文件类型、大小都会获取最新的， 文件名不会变， 文件名用户自行修改
