### ISSUE TITLE
[BUG]用例评审列表，显示的数据为【名称】，关联用例列表、用例编写列表都显示的【用例名称】显示不一致

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25355]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

用例评审列表，显示的数据为【名称】，关联用例列表、用例编写列表都显示的【用例名称】显示不一致
![image](https://github.com/metersphere/metersphere/assets/43202800/86f02775-44c0-4160-911e-f2b75fb83509)

### 重现步骤

[BUG]用例评审列表，显示的数据为【名称】，关联用例列表、用例编写列表都显示的【用例名称】显示不一致

### 期待的正确结果

显示一致

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
