### ISSUE TITLE
[BUG]测试跟踪-缺陷列表，缺陷名称超长，删除提示框显示不完整

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25356]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

测试跟踪-缺陷列表，缺陷名称超长，删除提示框显示不完整
![image](https://github.com/metersphere/metersphere/assets/43202800/05ad72bf-a853-4c18-b96a-5eb5649ceb12)

### 重现步骤

1测试跟踪-缺陷列表，创建一个缺陷名称超长的缺陷，
2删除缺陷，提示框显示不完整

### 期待的正确结果

提示框显示完整

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
