### ISSUE TITLE
[BUG]【接口定义】响应结果中 dataInfos 字段为空，使用 JSON 文档结构校验-断言dataInfos 长度大于0，最终断言成功。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25361]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

【接口定义】响应结果中 dataInfos 字段为空，使用 JSON 文档结构校验-断言dataInfos 长度大于0，最终断言成功。

### 重现步骤

1.【接口定义】响应结果中 dataInfos 字段为空，使用 JSON 文档结构校验-断言dataInfos 长度大于0，最终断言成功。
![image](https://github.com/metersphere/metersphere/assets/104960608/069709e9-48d5-491c-911f-0f9ebc2571df)
![image](https://github.com/metersphere/metersphere/assets/104960608/61cdea37-7aac-4cea-9e9e-54cacbfaf99f)
![image](https://github.com/metersphere/metersphere/assets/104960608/34f57567-18b9-48b0-9850-0d171e985cf7)

2. 响应体如下:
{
    "success":true,
    "code":"000",
    "messageSequence":null,
    "message":"正常",
    "result":{
        "resourceInfos":[
            {
                "success":true,
                "resourceName":"111111",
                "totalCount":150,
                "currentCount":100,
                "time":7,
                "dataInfos":[]
            }
        ]
    }
}

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
