### ISSUE TITLE
[BUG]接口自动化测试，引用场景，开启优先使用当前场景还是会引用到原场景的变量

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25363]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

1.接口自动化测试，引用场景，开启优先使用当前场景变量还是会引用到原场景的变量

### 重现步骤

1.新建场景 id1，场景变量增加常量 id = 1，场景内增加请求1，引用id =1
![1688460441435](https://github.com/metersphere/metersphere/assets/55130444/6ffa1131-2ec8-4e61-b14f-2b826a892973)
![1688460439809](https://github.com/metersphere/metersphere/assets/55130444/adf11eab-cc0a-4f9a-ab4a-22b6bd4042a6)
2.新建场景 id2，场景变量增加常量id  = 2，场景内增加请求2，引用场景id=2，引用场景1
![1688460468012](https://github.com/metersphere/metersphere/assets/55130444/528b10fb-753f-4208-b06b-5ec4e5bdf12b)
![1688460500669](https://github.com/metersphere/metersphere/assets/55130444/c9d740f8-bb70-43c5-95d9-46884e39a882)
3.新疆场景 id4，场景内增加csv变量 id 值是 44444，引用场景2，场景设置开启优先使用当前场景变量，id无法引用44444这个值
![1688460528938](https://github.com/metersphere/metersphere/assets/55130444/c6203f54-e009-49e6-865f-3d4aa6affd35)
![1688460575284](https://github.com/metersphere/metersphere/assets/55130444/543c43dd-e3fa-4ed6-91ae-749548357781)
![1688460616668](https://github.com/metersphere/metersphere/assets/55130444/40276e51-4c05-43cc-a6aa-8bb3cf3c7169)

### 期待的正确结果

id3场景可以引用到 csv文件中的id变量
_No response_

**Comment by fit2-zhao** [comment]
感谢您的建议，目前设计的场景变量优先原则只是针对常量，CSV变量不支持这样做。
