### ISSUE TITLE
[BUG]API定义模块中，选定版本，再选择CASE栏查看单接口用例时，选择版本功能失效，需修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#25372]
### MeterSphere 版本

V2.10.2lts

### 使用外置数据库

否

### 问题描述

API定义模块中，选定版本，再选择CASE栏查看单接口用例时，选择版本功能失效，需修复

### 重现步骤

1.开启版本管理功能，导入不同版本的API文档；
2.选定一个版本，查看该版本下的API文档；
3.选择CASE页签，查看该版本下的CASE显示情况；

实际结果：选择CASE页签后，版本筛选功能失效，刷新显示成所有接口数量

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/92150453/ada12b7d-7ef8-4acf-b4a9-e241406dfcbb)
![image](https://github.com/metersphere/metersphere/assets/92150453/0275cded-91d2-4e11-9884-c7eed626cbc2)

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.3-lts无该问题，待v2.10.3-lts发布后升级尝试。

**Comment by zrfit** [comment]
您好，暂时未复现该问题，后续最新版本如果再遇到该问题，可再打开并提供详细的日志信息和复现步骤。
