### ISSUE TITLE
[BUG]jenkins调用MS测试计划，在测试计划执行成功率为100%的情况下，jenkins job被MS置为构建失败，需修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#25370]
### MeterSphere 版本

V2.10.2lts

### 使用外置数据库

否

### 问题描述

jenkins调用MS测试计划，在测试计划执行成功率为100%的情况下，jenkins job被MS置为构建失败，需修改

### 重现步骤

见问题描述

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/92150453/b2b8bfd9-494d-4a41-9a82-df295fb669c3)
![image](https://github.com/metersphere/metersphere/assets/92150453/983cc0a1-a573-41b4-862c-5bbff0485704)

**Comment by youliyuan-fit2cloud** [comment]
你好，请截图说明下jenkins中配置，MS中测试计划包括哪些种类的用例？ jenkins版本和ms版本是否一致？

**Comment by sageonedream** [comment]
【备注】在私有化部署版本验证jenkins调用OK，对接MS cloud 2.10.2lts版本，jenkins调用存在以上反馈的问题

**Comment by wan92hen** [comment]
经过初步判断该问题是角色权限导致的，Jenkins 插件需要通过查询系统设置信息的接口获取 MeterSphere 的站点地址信息，而 MeterSphere Cloud 环境中的用户不具备这个操作权限，导致了插件执行过程中出现异常。

请确认下在私有化部署的环境中，Jenkins 上配置的 API Key 对应的用户，是不是有系统管理员角色或者有查看系统设置操作权限的角色。如果有的话，可以把该角色去掉后再次执行 Jenkins 任务，应该会出现同样的问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
