### ISSUE TITLE
[BUG]在对接口的后置beansell断言成功（response code 为4xx）结果还是失败

### ISSUE THREAD

**Issue by shoutian44443** [metersphere/metersphere#25380]
### 联系方式

shoutian44443@163.com

### MeterSphere 版本

v2.8.x-lts

### 使用外置数据库

否

### 问题描述

接口返回 response header code为401
实际该接口返回401正确，并对response做了后置beansell断言且通过
该接口的执行结果还是error
![image](https://github.com/metersphere/metersphere/assets/60697646/cb7f0652-bdaa-4d86-8b2c-1629333a9189)

### 重现步骤

无

### 期待的正确结果

如用户自己编写了断言且通过。就不应该用原本系统自带断言。

**Comment by youliyuan-fit2cloud** [comment]
你好，可以在断言规则中开启 “忽略状态”
![image](https://github.com/metersphere/metersphere/assets/54612864/475c6396-43e2-4180-9bad-060ed3c451d4)

ps：你这个版本比较低了，建议升级到最新的v2.10.2-lts哈。

**Comment by shoutian44443** [comment]
想问下 v2.10.2-lts 都有这个忽略状态选择框吗 @youliyuan-fit2cloud 
我看了脚本断言是没有这个忽略状态选择框的

**Comment by shoutian44443** [comment]
![image](https://github.com/metersphere/metersphere/assets/60697646/59b73a21-30cf-43cb-b9d2-e88df840c74f)
增加了一个 忽略状态的断言还是error

**Comment by shoutian44443** [comment]
可以了 谢谢
