### ISSUE TITLE
[BUG] 我的工作台待办-当前人员创建了性能测试数据，工作台我的待办没有数据统计

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25396]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

问题:
我的工作台待办-当前人员创建了性能测试数据，工作台我的待办没有数据统计
![image](https://github.com/metersphere/metersphere/assets/43202800/7b4a8c6b-dc4b-4893-a88c-8d93b40ce730)

### 重现步骤

我的工作台待办-当前人员创建了性能测试数据，工作台我的待办没有数据统计

### 期待的正确结果

按照当前人员创建的数据统计

**Comment by 13290445582** [comment]
您好，工作台-我的待办-性能测试：查询所选项目下性能测试中状态为error且创建人包含自己的测试。
检查下您的性能测试处的测试状态为error且创建人包含当前用户嘛？

**Comment by xhy12** [comment]
为什么其他列表就是显示的我当前创建的数据呢？能不能加个说明啥的，只有数字看不明白

**Comment by 13290445582** [comment]
感谢反馈，已沟通，并不是缺陷，issue关闭。
