### ISSUE TITLE
[FEATURE] 关于MeterSphere支持原生Python3的方案建议

### ISSUE THREAD

**Issue by zhenhuaplan** [metersphere/metersphere#25398]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

测试人员对于MeterSphere的呼声一直很高，但目前来看因为框架本身基于jpython解释器版本一直止步于2.7版本的限制，一直没看到有升级到python3的消息，对此我给出使用远程Python3环境，大概思路是使用http接口的形式，将python3脚本发送至远端已有python3的环境进行编译运行处理，之后返回脚本内的所有变量及值，使用接口的形式有利于数据的上下文传递和处理，同时解决目前框架无法支持原生python3脚本的痛点。目前我已实现该接口的雏形，效果如下：
<img width="1052" alt="image" src="https://github.com/metersphere/metersphere/assets/75710024/b6cbd14c-9c79-427c-9f1a-1aa9f7f13edb">
当然，如果相关配置可以单独结合框架进行开发展示，可能效果会理想一些。

**Comment by luty2018** [comment]
感谢建议，我们调研一下

**Comment by linfengjjj** [comment]
厉害了 大佬
你的python remote接口服务包和安装方式可以分享下吗

**Comment by fit2-zhao** [comment]
v3 已经可以支持 python3 了欢迎使用。

```
docker run -d -p 8081:8081 --name=metersphere -v ~/.metersphere/data:/opt/metersphere/data cr2.fit2cloud.com/metersphere/metersphere-ce-allinone
```

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/31811
可以参考这个
