### ISSUE TITLE
[FEATURE]对接mantis缺陷管理工具

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#254]
**请描述您的需求或者改进建议.**
测试执行时提出的bug需要在缺陷管理工具中进行管理，mantis是使用较多的缺陷管理系统之一，mantis本身也提供bug创建和查询的接口

**请描述你建议的实现方案**
测试执行时发现的bug可以直接提交到mantis，在测试记录中能够看到并打开相关的bug（mantis链接）

**Comment by youliyuan-fit2cloud** [comment]
您好，目前暂时不支持对接mantis工具，已支持禅道，JIRA和Tapd缺陷管理系统。
