### ISSUE TITLE
[BUG]接口测试首页统计，rpc协议和列表显示的下拉不一致，

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25408]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

接口测试首页统计，rpc协议和列表显示的下拉不一致，

![image](https://github.com/metersphere/metersphere/assets/43202800/ea023205-9540-4652-bcc1-bb9874a256ff)

### 重现步骤

接口测试首页统计，rpc协议和列表显示的下拉不一致，

### 期待的正确结果

显示一致

**Comment by zrfit** [comment]
您好，感谢反馈！后续版本进行优化！
