### ISSUE TITLE
[BUG]优化建议： 环境配置，数据库提示非中文，密码项必填没有加* 提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25403]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

优化建议： 环境配置，数据库提示非中文，密码项必填没有加* 提示

![image](https://github.com/metersphere/metersphere/assets/43202800/0632963b-598a-4343-9e8a-0bdd14d53bfb)

### 重现步骤

优化建议： 环境配置-没有填写密码，数据库提示非中文，密码项必填没有加* 提示

### 期待的正确结果

密码加* 提示，提示信息建议改成中文，说看不懂 ——

**Comment by fit2-zhao** [comment]
感谢您的反馈

1 密码是可以为空的，如果平台加上限制没有密码的用户就无法使用了。
2 错误提示使用原生错误信息，用户更直观清晰了解错误。

**Comment by xhy12** [comment]
希望加个使用提示，如果密码没通过加个红框标记啥的

**Comment by fit2-zhao** [comment]
不点校验时是不清楚密码对不对的，点了校验后，提示信息里面不是很清楚了吗。
