### ISSUE TITLE
[QUESTION]缺少io.metersphere.xpack下的代码

### ISSUE THREAD

**Issue by fw0037** [metersphere/metersphere#25401]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/20429450/80e1025f-bb1e-4701-a673-1f61ab8db2a7)

使用1.20.23版本的项目，发现该项目下文件 源码缺失，查找其它版本，均发现该文件缺失，请问可以从哪些渠道获取呢？
当前缺失该文件后，API接口测试实际运行不起来。

**Comment by luty2018** [comment]
建议你用v2.10的源码，我们已经处理了这部分。
