### ISSUE TITLE
[BUG]接口测试json请求体使用json-schema格式化之后再关闭schema，请求体内容发生了很奇怪的变化

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25412]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

接口测试json请求体使用json-schema格式化之后再关闭schema，json请求体内容发生了很奇怪的变化

### 重现步骤

1.创建一个接口case
2.接口case的请求体使用以下请求体。
{
    "taskDetailId": 4392102867664896,
    "area": "",
    "businessTypeIds": [
        
    ],
    "levelTwoOptionList": [
        1840,
        1844
    ],
    "pointsTypes": [
        
    ],
    "personLiables": [
        
    ],
    "operateTypes": [
        
    ],
    "userAccountId": "1471090057715712016"
}
![image](https://github.com/metersphere/metersphere/assets/88763608/21f56215-fff2-43a3-84d7-37b286b4477b)

3.使用json-chema
![image](https://github.com/metersphere/metersphere/assets/88763608/e21967f9-c98c-40da-a04e-ca2ad31c9418)

4.关闭json-schema，内容发生了变化
![image](https://github.com/metersphere/metersphere/assets/88763608/cb5479b3-d26b-4ec2-add8-599c447d6c0e)

### 期待的正确结果

不应该发生变化

**Comment by 13290445582** [comment]
感谢您的反馈，我们将在v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
