### ISSUE TITLE
【接口定义】接口列表>文档，建议增加排序规则

### ISSUE THREAD

**Issue by Gaiokane** [metersphere/metersphere#25416]
### MeterSphere 版本

v1.20.21-lts-6359b12e

### 联系方式

MeterSphere 交流群41——Gaiokane

### 请描述您的需求或者改进建议

目前接口文档排序只有三种，都是和创建时间、更新时间有关，模块下接口较多时，前端查找接口文档并不方便

### 请描述你建议的实现方案

建议多增加些排序规则，如按接口ID、接口名称等

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/10814413/d62ab27d-71af-49a3-ac23-17027c9403b6)

**Comment by luty2018** [comment]
好的， 感谢建议。

**Comment by luty2018** [comment]
v3进行了改版， 可以待发布后看是否满足需求，如不满足可以再次提交issue
