### ISSUE TITLE
[FEATURE] 建议用例添加标签可以用更快捷的方式

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#25419]
### MeterSphere 版本

v2.10.1-lts-65fad062

### 请描述您的需求或者改进建议

现在修改用例标签需要进入用例编辑界面, 操作过程不太方便而且过于笨重, 保存会更新整个用例的内容

### 请描述你建议的实现方案

建议设立独立的入口, 标签可以直接添加或修改删除, 不会影响用例的其它内容
例如在查看用例的界面, 标签是处于可编辑状态, 而其它内容是只读, 需要点击编辑才可编辑

**Comment by luty2018** [comment]
设计如此， 暂无规划。
