### ISSUE TITLE
[BUG] 项目设置-项目环境-创建环境（通用配置）：变量设置字符较长时未悬浮显示。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25421]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

问题：项目设置-项目环境-创建环境（通用配置）：变量设置字符较长时未悬浮显示。。

### 重现步骤

项目设置-项目环境-创建环境（通用配置）：变量设置字符较长时未悬浮显示。
![image](https://github.com/metersphere/metersphere/assets/43202800/f9d21ea1-def5-4ba7-bb8c-15b4b7e64055)

### 期待的正确结果

超长字符悬浮显示

**Comment by 13290445582** [comment]
您好，我们这里超长字符支持鼠标左右滑动显示的。
