### ISSUE TITLE
优化:【项目设置】-项目环境：创建环境不输入内容点击确定，必填项提示信息与字段名称不一致。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25429]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境不输入内容点击确定，必填项提示信息与字段名称不一致。
![image](https://github.com/metersphere/metersphere/assets/43202800/1c86ed9a-6ee7-4a82-b3e0-781398a143ed)

### 重现步骤

【项目设置】-项目环境：创建环境不输入内容点击确定，必填项提示信息与字段名称不一致。

### 期待的正确结果

保持一致

**Comment by 13290445582** [comment]
感谢反馈，这里保持原来设计，不做修改。
