### ISSUE TITLE
[BUG] 测试用例，查看并修改用例状态为 已完成，将该用例加入到测试计划中，点击执行页面的 用例状态还是未开始

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25427]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

测试用例，查看并修改用例状态为 已完成，将该用例加入到测试计划中，点击执行页面的
用例状态还是未开始

### 重现步骤

1、测试用例，查看并修改用例状态为 已完成，
2、将该用例加入到测试计划中
3、点击执行页面的用例状态还是未开始，和列表实际显示不一样
![测试用例，查看并修改用例状态为 已完成，将该用例加入到测试计划中，点击执行页面的](https://github.com/metersphere/metersphere/assets/43202800/1eda9b55-0b47-494f-bfea-103573f9f8c2)

### 期待的正确结果

按修改后的状态显示

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.4修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
