### ISSUE TITLE
[BUG] ui显示问题；【项目设置】-项目基本信息：编辑按钮不醒目不美观。（建议调整跟其他模块操作列编辑按钮一致）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25426]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

ui显示问题；【项目设置】-项目基本信息：编辑按钮不醒目不美观。（建议调整跟其他模块操作列编辑按钮一致）
![image](https://github.com/metersphere/metersphere/assets/43202800/294677b0-9cca-48be-9ab2-8bd1e63ebf76)

### 重现步骤

ui显示问题；【项目设置】-项目基本信息：编辑按钮不醒目不美观。（建议调整跟其他模块操作列编辑按钮一致）

### 期待的正确结果

建议调整跟其他模块操作列编辑按钮一致）

**Comment by 13290445582** [comment]
感谢反馈，对名称进行修改，都是用的这种图标，风格统一。
