### ISSUE TITLE
[BUG] ui显示问题：【测试跟踪】-缺陷管理-编辑缺陷-关联用例/附件-删除没有提示/名称过长时，删除对话框 按钮太靠下，页面不好看

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25425]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】-缺陷管理-编辑缺陷-关联用例/附件-删除没有提示/名称过长时，删除对话框 按钮太靠下，页面不好看

### 重现步骤

【测试跟踪】-缺陷管理-编辑缺陷-关联用例/附件-删除没有提示/名称过长时，删除对话框 按钮太靠下，页面不好看
![image](https://github.com/metersphere/metersphere/assets/43202800/f3e6f347-53a8-48a4-ac85-78534846af1c)

### 期待的正确结果

调整页面布局如：
![image](https://github.com/metersphere/metersphere/assets/43202800/cdfb0da3-042a-4d15-b856-3b31bfcc694c)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.4修复该问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
