### ISSUE TITLE
[BUG]项目环境列表-搜索框显示“根据名称搜索”，数据列字段名称为：环境名称，未统一。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25422]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

项目环境列表-搜索框显示“根据名称搜索”，数据列字段名称为：环境名称，未统一。
![image](https://github.com/metersphere/metersphere/assets/43202800/72a92057-9554-4c68-8e40-b86bee12fe85)

### 重现步骤

项目环境-搜索框显示“根据名称搜索”，数据列字段名称为：环境名称，未统一。

### 期待的正确结果

字段显示统一

**Comment by 13290445582** [comment]
经过与产品确认，不修改原先设计。
