### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ben-boys** [metersphere/metersphere#25439]
### MeterSphere 版本

v2.10.1-lts

### 联系方式

18566013446

### 请描述您的需求或者改进建议

用例模板提一个优化建议，建议步骤描述可以增加字段，很多步骤前面都有前置条件，重新往上面看前置条件很不顺，很难受
![8625b1b507b13a977ed75ca7b07b503](https://github.com/metersphere/metersphere/assets/55377093/e9f2dbef-270b-47cc-9753-fd508946230f)

### 请描述你建议的实现方案

新增步骤前的前置条件栏，或者可以自定义步骤栏，例如可以步骤栏新增测试点，这样可以一条用例里面写多个测试点

**Comment by luty2018** [comment]
暂时没有规划哦。
