### ISSUE TITLE
[BUG]【接口定义】 升级到新版后原来场景断言失败

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#25437]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

从2.10.2版本升级到2.10.3版本，原来接口场景接口返回的数据与预期结果一致，接口断言报错，升级前是正常的

### 重现步骤

1.下载附件脚本
2.附件脚本上传到平台中
3.执行上传的脚本
4.观察断言是否成功

### 期待的正确结果

断言可以成功

### 附加信息

1.脚本
[Metersphere_Scenario测试项目.zip](https://github.com/metersphere/metersphere/files/11979828/Metersphere_Scenario.zip)
![image](https://github.com/metersphere/metersphere/assets/45531073/d30e9d49-4aec-44f5-ab41-e224eec24fbe)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.4-lts中已修复，升级一下吧。
