### ISSUE TITLE
[BUG] jira 对接，勾选使用jira模板，创建缺陷报错。用户反馈：jira这个字段的格式是没有秒(yyyy-MM-DD hh:mm)。 ms识别到的是含有秒的(yyyy-MM-DD hh:mm:ss)

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25434]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

<img width="707" alt="9d456ac2-46f4-45f3-84e6-ccaa6e0a823d" src="https://github.com/metersphere/metersphere/assets/43202800/19a480ae-629b-49fd-8811-b82774fc82e3">

1、jira 对接，勾选使用jira模板

2、再缺陷管理创建缺陷报错
![image](https://github.com/metersphere/metersphere/assets/43202800/db354ef9-59fe-4380-8dca-edb978155749)

3、用户反馈：jira这个字段的格式是没有秒(yyyy-MM-DD hh:mm)。 ms识别到的是含有秒的(yyyy-MM-DD hh:mm:ss)
![image](https://github.com/metersphere/metersphere/assets/43202800/eae711c5-d491-41a7-911d-801fcedb8370)

### 重现步骤

<img width="707" alt="9d456ac2-46f4-45f3-84e6-ccaa6e0a823d" src="https://github.com/metersphere/metersphere/assets/43202800/19a480ae-629b-49fd-8811-b82774fc82e3">

1、jira 对接，勾选使用jira模板

2、再缺陷管理创建缺陷报错
![image](https://github.com/metersphere/metersphere/assets/43202800/db354ef9-59fe-4380-8dca-edb978155749)

3、用户反馈：jira这个字段的格式是没有秒(yyyy-MM-DD hh:mm)。 ms识别到的是含有秒的(yyyy-MM-DD hh:mm:ss)
![image](https://github.com/metersphere/metersphere/assets/43202800/eae711c5-d491-41a7-911d-801fcedb8370)

### 期待的正确结果

应该需要处理格式一致

**Comment by 13290445582** [comment]
感谢反馈，该问题计划于v2.10.4版本修复。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
