### ISSUE TITLE
[BUG] 优化建议【项目设置】-项目环境：创建环境通用配置导入选择JSON文件提示“保存成功”建议修改为点击上传选择文件提示“导入成功”点击确定提示“保存成功”。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25430]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境通用配置导入选择JSON文件提示“保存成功”建议修改为点击上传选择文件提示“导入成功”点击确定提示“保存成功”。

![image](https://github.com/metersphere/metersphere/assets/43202800/f8d777d9-1ff0-435d-81e9-c14f69e76ddc)

### 重现步骤

【项目设置】-项目环境：创建环境通用配置导入选择JSON文件提示“保存成功”

### 期待的正确结果

建议修改为点击上传选择文件提示“导入成功”点击确定提示“保存成功”。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.4版本优化。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
