### ISSUE TITLE
[BUG]正则表达式提取器，是否可以实现“Main samples and sub samples"?也就是对重定向子请求也进行参数提取。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#25431]
### 联系方式

王进

### MeterSphere 版本

v2.10.2

### 使用外置数据库

否

### 问题描述

正则表达式提取器，是否可以实现“Main samples and sub samples"?也就是对重定向子请求也进行参数提取。

### 重现步骤

1. Jmeter正则表达式提取器支持下面几种
![3ce32dce86aa20b79e07021d8205e6c](https://github.com/metersphere/metersphere/assets/76033005/77b81fb1-b8f5-4fb4-85d1-d0d171ba5984)
2. 其中第一种是否可以支持？跟客户实测下来截图里的第一种情况目前不支持。

**Comment by 13290445582** [comment]
您好，感谢反馈，不支持Main sample and sub-samples。

**Comment by 35plus** [comment]
能不能 把它转成一个需求，因为在很多公司这个常见应用场景。

**Comment by 13290445582** [comment]
您好，提需求的话，提个FEATURE给产品吧，产品探讨下。
