### ISSUE TITLE
[BUG] 【项目设置】-项目环境：创建环境通用配置导入JSON文件名称过长时建议加上悬浮显示窗口以便能查看全部内容。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25432]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境通用配置导入JSON文件名称过长时建议加上悬浮显示窗口以便能查看全部内容。

![image](https://github.com/metersphere/metersphere/assets/43202800/a3b740ae-e264-4b65-8b47-4af139e59dfd)

### 重现步骤

【项目设置】-项目环境：创建环境通用配置导入JSON文件名称过长时建议加上悬浮显示窗口以便能查看全部内容。

### 期待的正确结果

【项目设置】-项目环境：创建环境通用配置导入JSON文件名称过长时建议加上悬浮显示窗口以便能查看全部内容。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.4版本优化。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
