### ISSUE TITLE
[BUG]  环境管理-证书配置：keystore 类型（p12, pfx, jks）  上传后不生成证书条目

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25435]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

环境管理-证书配置：keystore 类型（p12, pfx, jks）  上传后不生成证书条目

### 重现步骤

环境管理-证书配置：keystore 类型（p12, pfx, jks）  上传后不生成证书条目

操作证书见附件，是一个rar文件，改成txt后缀了

### 附加信息

[证书.txt](https://github.com/metersphere/metersphere/files/11979132/default.txt)

**Comment by xhy12** [comment]
密码 1234567890

**Comment by 13290445582** [comment]
感谢反馈，我们将在v2.10.4版本修复这个问题。

**Comment by fit2-zhao** [comment]
感谢您的建议，您提供的证书有问题，或者密码不对，你可以找个在线工具检测一下。

**Comment by 13290445582** [comment]
您好， 使用了正确的证书可以上传成功，请您检查下证书和密码，后续有问题请反馈，感谢理解与支持。
