### ISSUE TITLE
[BUG]测试计划中使用脑图标注执行结果，测试用例中没有更新执行结果

### ISSUE THREAD

**Issue by jack084015** [metersphere/metersphere#25446]
### 联系方式

18392875887@163.com

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

手动执行测试计划是时，使用脑图标准结果，执行的最新结果没有同步到测试用例中。

### 重现步骤

1、测试计划中使用脑图标准结果；
![image](https://github.com/metersphere/metersphere/assets/49033962/a11e7b63-4062-4257-822c-84776ec34155)

2、测试用例中结果没有更新；
![image](https://github.com/metersphere/metersphere/assets/49033962/b526f7f3-b62f-44e1-9de8-ffa4a322b5e7)

### 期待的正确结果

测试用例结果应该更新

![image](https://github.com/metersphere/metersphere/assets/49033962/5e7a6bf7-d9e3-4a68-aba2-23f96188fe1f)

**Comment by 13290445582** [comment]
已知问题，计划于v2.10.4修复。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。

**Comment by jack084015** [comment]
![image](https://github.com/metersphere/metersphere/assets/49033962/81cefad4-8f91-4aea-8293-5c32291d0e28)
v2.10.4-lts-6a2bf297 验证问题仍存在

**Comment by 13290445582** [comment]
报歉，验证时操作缺少一步骤，问题迭代到v2.10.5版本，感谢理解与支持。

**Comment by 13290445582** [comment]
v2.10.5已修复
