### ISSUE TITLE
[BUG] 优化建议【项目设置】-项目环境：创建环境通用配置操作列建议添加提示启用成功、禁用成功；链接超时和响应超时输入超长字符数时显示有小数，需要添加字符数长度校验。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25451]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

优化建议【项目设置】-项目环境：创建环境通用配置操作列建议添加提示启用成功、禁用成功；
链接超时和响应超时输入超长字符数时显示有小数，需要添加字符数长度校验。

### 重现步骤

优化建议【项目设置】-项目环境：创建环境通用配置操作列建议添加提示启用成功、禁用成功；链接超时和响应超时输入超长字符数时显示有小数，需要添加字符数长度校验。

### 期待的正确结果

1 项目环境：创建环境通用配置操作列建议添加提示启用成功、禁用成功；
2 链接超时和响应超时输入超长字符数时显示有小数，需要添加字符数长度校验。

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复该问题。

**Comment by luty2018** [comment]
无需修改， 启用禁用每个都给提示太频繁了。

链接超时时间输入超长字符就会展示科学计数法，这也很正常啊， Excel也是这么处理的。

小数是我们允许输入的，为什么要限制？
