### ISSUE TITLE
[BUG] 【项目设置】-项目环境：创建环境通用配置类型选择CSV、计数器、随机数高级设置必填项字段“变量名”不输入内容提示信息与字段名称“变量名”不一致。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25456]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境通用配置类型选择CSV、计数器、随机数高级设置必填项字段“变量名”不输入内容提示信息与字段名称“变量名”不一致。

### 重现步骤

【项目设置】-项目环境：创建环境通用配置类型选择CSV、计数器、随机数高级设置必填项字段“变量名”不输入内容提示信息与字段名称“变量名”不一致。

### 期待的正确结果

校验信息一致

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/8affa7f3-6de5-455e-b877-b5b8bc121439)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本优化该问题。

**Comment by 13290445582** [comment]
v2.10.5已优化
