### ISSUE TITLE
脑图写用例，建议增加自定义标签功能。

### ISSUE THREAD

**Issue by kingfeng999** [metersphere/metersphere#25452]
### MeterSphere 版本

v2.10.3-lts-ac6522a2

### 联系方式

13802282483

### 请描述您的需求或者改进建议

在平台上通过脑图来编写功能测试用例时，建议增加自定义标签功能。比如：执行步骤、预期结果等

**Comment by luty2018** [comment]
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/a16f303b-9d32-464f-b67e-c854a7552cec">
打了用例标签的子节点如果有两个则为步骤和预期结果；一个则默认为只有预期结果没有步骤， 这个不需要手动打标签的
