### ISSUE TITLE
[BUG] 【项目设置】-项目环境：创建环境全局认证配置认证用户名输入中文保存成功， 没有限制用户名长度。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25459]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境全局认证配置认证用户名输入中文保存成功，
没有限制用户名长度。
![image](https://github.com/metersphere/metersphere/assets/43202800/3df85dde-0574-40a7-a87a-9e2ecc4227bd)

### 重现步骤

【项目设置】-项目环境：创建环境全局认证配置认证用户名输入中文保存成功，
没有限制用户名长度。

### 期待的正确结果

其他模块配置都有超长校验，此处应该要设置超长校验

**Comment by zrfit** [comment]
您好，感谢反馈！v3进行优化。
