### ISSUE TITLE
[BUG]【项目设置】-项目环境：创建环境TCP配置服务器/ip、端口、连接、响应等字段没有限制输入格式类型。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25458]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-项目环境：创建环境TCP配置服务器/ip、端口、连接、响应等字段没有限制输入格式类型。

![image](https://github.com/metersphere/metersphere/assets/43202800/2827c9df-02b6-4b86-a25c-4227a5906540)

### 重现步骤

【项目设置】-项目环境：创建环境TCP配置服务器/ip、端口、连接、响应等字段没有限制输入格式类型。

### 期待的正确结果

【项目设置】-项目环境：创建环境TCP配置服务器/ip、端口、连接、响应等字段没有限制输入格式类型。

**Comment by zrfit** [comment]
您好，感谢反馈！经过沟通，上述字段暂时不做格式强校验，方便用户自行输入对应格式和变量格式的引用。
