### ISSUE TITLE
[FEATURE]提交TAPD缺陷，希望可以选择发现版本、严重程度、优先级、状态、处理人等TAPD字段

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#2545]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/26756176/117407175-c272c000-af40-11eb-94b8-a0b84c479e41.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
后面会支持自定义字段

**Comment by xulinde** [comment]
1.10版本支持自定义缺陷模版，自定义字段
