### ISSUE TITLE
[BUG]MS对接TAPD，双向同步时，优先级字段值未能正确同步至MS

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#25464]
### MeterSphere 版本

V2.10.3lts

### 使用外置数据库

否

### 问题描述

MS对接TAPD，进行缺陷双向同步时，优先级字段值未能正确同步至MS

### 重现步骤

见问题描述

### 附加信息

![54649d9b52297baa0ba781ae1d6e7c5](https://github.com/metersphere/metersphere/assets/92150453/9d497928-13c1-47d1-a862-d28b50c93b40)
<img width="1378" alt="ebb3e9c531062f4d3a898734680b449" src="https://github.com/metersphere/metersphere/assets/92150453/7e706202-0923-4352-89cd-2d2ccb1f0488">

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
