### ISSUE TITLE
[BUG] 【接口测试】-接口定义-TCP-转XML数据-未填写数据提示数据为空

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25462]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【接口测试】-接口定义-TCP-转XML数据-未填写数据提示数据为空

![image](https://github.com/metersphere/metersphere/assets/43202800/4cf5e6c7-2f68-458a-a9f5-9137110d828b)

### 重现步骤

【接口测试】-接口定义-TCP-转XML数据-未填写数据提示数据为空

### 期待的正确结果

【接口测试】-接口定义-TCP-转XML数据-未填写数据提示数据为空

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
