### ISSUE TITLE
[BUG]场景变量引用错误

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#25467]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

问题现象：
接口自动化场景中，在环境参数中设置一个CSV变量，CSV中有某个变量名称和场景变量中的某个变量名称一直，接口场景执行时，接口中引用的是CSV文件中的变量，不是场景变量中的变量值。
环境参数：
<img width="1395" alt="截屏2023-07-10 下午5 14 47" src="https://github.com/metersphere/metersphere/assets/34637801/ec597d32-2887-4bda-b46a-75dcea929012">
CSV文件：
<img width="565" alt="截屏2023-07-10 下午5 15 27" src="https://github.com/metersphere/metersphere/assets/34637801/fe083447-1b57-4674-99cb-550a8bc6320e">
场景变量：
<img width="1399" alt="截屏2023-07-10 下午5 16 26" src="https://github.com/metersphere/metersphere/assets/34637801/5374c469-5e40-45dd-880e-a6354a7b7330">
接口引用：
<img width="988" alt="截屏2023-07-10 下午5 17 06" src="https://github.com/metersphere/metersphere/assets/34637801/6f47810b-17e2-4761-afdf-90769e4edaa0">

### 重现步骤

1.准备一个CSV文件，上传至环境参数中
2.准备一个接口自动化场景，场景步骤中引用CSV中某个变量
3.设置场景变量，变量名称和场景步骤中引用的变量名称一致。
4.执行接口自动化场景，查看请求参数。

### 期待的正确结果

接口自动化场景步骤引用的是场景变量的值

**Comment by 13290445582** [comment]
感谢反馈，目前平台变量机制设计就是这样，集成的底层测试引擎JMeter中处理CSV变量的优先级是高于普通变量，也就是说场景上的变量不会覆盖CSV变量。
