### ISSUE TITLE
[BUG] 【ui测试】-测试报告-步骤-开始时间和结束时间建议格式一致

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25461]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/43202800/32ccc81f-70e7-4576-871c-886a64daf259)

【ui测试】-测试报告-步骤-开始时间和结束时间建议格式一致

### 重现步骤

【ui测试】-测试报告-步骤-开始时间和结束时间建议格式一致

### 期待的正确结果

【ui测试】-测试报告-步骤-开始时间和结束时间建议格式一致

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts优化。
