### ISSUE TITLE
[BUG]在测试计划中，编辑进入测试用例详情，改变测试用例的状态后保存，会导致测试用例的模块变更为“默认模块”

### ISSUE THREAD

**Issue by Ybump14** [metersphere/metersphere#2547]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1-2cb10c1e
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  在测试计划中,关联测试用例
2. 对这条测试用例进行编辑,在编辑弹窗的详情中,改变用例的状态为"通过/失败"等

**期待的正确结果**
正确情况下应该是什么样的？

不会改变用例本来归属的模块

实际结果
用例会被移动到默认模块

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
下个版本会修复

**Comment by Ybump14** [comment]
~
