### ISSUE TITLE
[BUG] 【项目设置】-模板管理-模板字段：创建字段名字段备注输入超长字符数提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25487]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-模板字段：创建字段名字段-文本框 备注输入超长字符数提示“SQL error happened, please check logs.”

![image](https://github.com/metersphere/metersphere/assets/43202800/ae586b09-a00a-4c57-ba93-66a4637455d8)

![image](https://github.com/metersphere/metersphere/assets/43202800/e0a92367-6d24-41d9-9bc9-d64f62c533c7)

### 重现步骤

【项目设置】-模板管理-模板字段：创建字段名字段备注输入超长字符数提示“SQL error happened, please check logs.”

### 期待的正确结果

字段超长请给出校验

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
