### ISSUE TITLE
[BUG]  【项目设置】-模板管理-模板字段：字段名称没有做重复校验。同名问题为多了空格

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25483]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

  【项目设置】-模板管理-模板字段：字段名称没有做重复校验

![image](https://github.com/metersphere/metersphere/assets/43202800/90bbc92a-a042-4f63-8076-ecc23185f6cd)

### 重现步骤

  【项目设置】-模板管理-模板字段：字段名称没有做重复校验

### 期待的正确结果

字段重复不方便区分使用，建议校验重复字段

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
