### ISSUE TITLE
[BUG]接口自动化变量无编辑权限时，编辑报错

### ISSUE THREAD

**Issue by janehugit** [metersphere/metersphere#25484]
### MeterSphere 版本

 v2.10.3-lts

### 使用外置数据库

否

### 问题描述

项目成员角色无接口自动化变量编辑权限，编辑变量时可以保存，但是再点击时报错

### 重现步骤

1. 打开接口自动化模块
2. 在场景中打开场景变量
3. 点击场景变量报错
![53e694fd238d58036fa9bdf4c6f224d9](https://github.com/metersphere/metersphere/assets/135193527/a14d1f1d-071c-42c6-8027-03ff9926ae62)

### 期待的正确结果

无权限时点击场景变量提示无权限的正确信息

**Comment by zrfit** [comment]
您好，感谢反馈！
1、变量是csv类型，确认下用户对应权限是否开启了项目设置-文件管理的查询权限？没开启，则会报上述报错，开启了，则可以正常查看。
2、目前对于权限提示信息和跳转问题为已知问题，已提优化到v3。
