### ISSUE TITLE
[BUG]【项目设置】-误报库：状态列点击启用、禁用都提示保存成功，建议修改为“启用成功”和“禁用成功”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25481]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-误报库：状态列点击启用、禁用都提示保存成功，建议修改为“启用成功”和“禁用成功”

### 重现步骤

【项目设置】-误报库：状态列点击启用、禁用都提示保存成功，建议修改为“启用成功”和“禁用成功”

![image](https://github.com/metersphere/metersphere/assets/43202800/6492d7dc-990f-441c-a98c-cbb303ebde0b)

### 期待的正确结果

，建议修改为“启用成功”和“禁用成功”

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
