### ISSUE TITLE
[BUG]  【项目设置】-模板管理-模板字段：创建字段-下拉框。添加选项值内容过长时界面展示不美观。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25488]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-模板字段：创建字段-下拉框。添加选项值内容过长时界面展示不美观。

![1689055630017](https://github.com/metersphere/metersphere/assets/43202800/28ae9ca7-767d-4dec-afc9-10d28a1c3157)

### 重现步骤

【项目设置】-模板管理-模板字段：创建字段-下拉框。添加选项值内容过长时界面展示不美观。

### 期待的正确结果

建议设置 字符数限制

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
