### ISSUE TITLE
[BUG]【项目设置】-误报库：创建误报校验误报名称重复时点击保存提示“错误代码不可重复”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25482]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-误报库：创建误报校验误报名称创建两个数据，数据重复时点击保存提示“错误代码不可重复”
![image](https://github.com/metersphere/metersphere/assets/43202800/ca863acd-0a2b-45aa-b4b4-96c6c1a4fb5e)

### 重现步骤

【项目设置】-误报库：创建误报校验误报名称创建两个数据，数据重复时点击保存提示“错误代码不可重复”

### 期待的正确结果

提示语句不清晰，请修改，如 误报规则不能配置重复等

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
