### ISSUE TITLE
[BUG]  【项目设置】-模板管理-缺陷模板：创建缺陷模板描述和标签、已选字段API字段名输入字符数过长时点击保存提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25492]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-缺陷模板：创建缺陷模板描述和标签、已选字段API字段名输入字符数过长时点击保存提示“SQL error happened, please check logs.”
![image](https://github.com/metersphere/metersphere/assets/43202800/9cea71e9-0639-4b67-b22b-0c838ca60811)

### 重现步骤

给出超长字符校验

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
