### ISSUE TITLE
[BUG] 【项目设置】-模板管理-用例模板：创建模板点击保存提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25491]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-用例模板：创建模板点击保存提示“SQL error happened, please check logs.”
![image](https://github.com/metersphere/metersphere/assets/43202800/86a5bfdd-fdd4-440c-85b9-d83d6d2e53e0)

### 重现步骤

【项目设置】-模板管理-用例模板：创建模板点击保存提示“SQL error happened, please check logs.”

### 期待的正确结果

给出超长限制

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
