### ISSUE TITLE
[BUG]  【项目设置】-模板管理-缺陷模板：选择一条数据操作列点击复制-追加或覆盖选择目标项目点击确定提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25493]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-缺陷模板：选择一条数据操作列点击复制-追加或覆盖选择目标项目点击确定提示“SQL error happened, please check logs.”

![image](https://github.com/metersphere/metersphere/assets/43202800/10fbfc14-4ab0-4f37-85a1-99e85f0f1488)

### 重现步骤

【项目设置】-模板管理-缺陷模板：选择一条数据操作列点击复制-追加或覆盖选择目标项目点击确定提示“SQL error happened, please check logs.”

### 期待的正确结果

复制无报错

**Comment by xhy12** [comment]
应该是名称有64字符 再copy导致
![image](https://github.com/metersphere/metersphere/assets/43202800/278506a4-ef49-4c57-8c6c-13816ba4f17b)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
