### ISSUE TITLE
[BUG] 【项目设置】-版本管理：创建版本功能字段“版本”输入空格可以保存。建议对输入版本号格式做校验。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25499]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-版本管理：创建版本功能字段“版本”输入空格。建议对输入版本号格式做校验。
![image](https://github.com/metersphere/metersphere/assets/43202800/9ee74658-d2c9-43c5-aa30-d8e0a7ab63f7)

### 重现步骤

【项目设置】-版本管理：创建版本功能字段“版本”输入空格。建议对输入版本号格式做校验。

### 期待的正确结果

建议对输入版本号格式做校验。

**Comment by luty2018** [comment]
不排除有些用户的版本号是需要输入空格的，比如“v 1.10”
