### ISSUE TITLE
[BUG] 【项目设置】-模板管理-接口模板：模板设置-基础字段不能编辑。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25498]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【项目设置】-模板管理-接口模板：模板设置-基础字段不能编辑。

![image](https://github.com/metersphere/metersphere/assets/43202800/32275c5e-b1f7-4cfc-86da-0316bdab76c2)

### 重现步骤

【项目设置】-模板管理-接口模板：模板设置-基础字段不能编辑。

### 期待的正确结果

其他模板都可以编辑，此处不可编辑是因为什么呢？

**Comment by luty2018** [comment]
设计如此，接口定义只能新增字段， 不能修改系统字段。
