### ISSUE TITLE
[BUG]接口测试用例名称输入框太短

### ISSUE THREAD

**Issue by fusu-qa** [metersphere/metersphere#25495]
### MeterSphere 版本

2.9.1

### 使用外置数据库

否

### 问题描述

接口测试用例名称输入框太短
![image](https://github.com/metersphere/metersphere/assets/25762331/8b455368-22b0-4fd8-8e48-e701185fb3d2)

### 重现步骤

接口定义-CASE-添加/编辑

**Comment by 13290445582** [comment]
您好，感谢您的反馈，为了整体页面的美观我们采用了这样大小的输入框，名称过长时，可以向右滑动查看名称，感谢理解与支持。
