### ISSUE TITLE
[BUG]批量禁用部分步骤，会导致同一场景下其他未禁用步骤的后置脚本被禁用

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25507]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

批量禁用部分步骤，会导致同一场景下其他未禁用步骤的后置脚本被禁用

### 重现步骤

操作步骤如下：
1.全选场景下所有步骤
![image](https://github.com/metersphere/metersphere/assets/103627487/1bc1b6e1-fbc9-4c9e-abd9-cc16d555c5ed)
2.把部分步骤去掉勾选，例如步骤7、8、9
![image](https://github.com/metersphere/metersphere/assets/103627487/d62b0cbb-a3ac-4211-828a-4b4fa7f669cc)
3.此时去检查步骤7、8、9的后置脚本，发现脚本被禁用。
![image](https://github.com/metersphere/metersphere/assets/103627487/6f6fe32e-c1b9-4427-8885-b89636f0c522)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。
