### ISSUE TITLE
[BUG]【接口测试】 连接超时与响应超时时间取值逻辑错误

### ISSUE THREAD

**Issue by shijianliangs** [metersphere/metersphere#25503]
### MeterSphere 版本

v1.20.24-lts

### 使用外置数据库

否

### 问题描述

连接超时与响应超时时间取值逻辑错误

### 重现步骤

- 场景1：
环境配置中设置连接/响应超时 50000ms,环境配置中设置连接/响应超时 60000ms, 实际执行使用的是环境配置中的设置50000ms

- 场景2：
环境配置中设置连接/响应超时 50000ms,环境配置中设置连接/响应超时 60001ms, 实际执行使用的是接口配置中的设置60001ms

### 期待的正确结果

场景1与2 关于连接/响应超时的取值逻辑应该保持一致，如：优先取接口配置中的，接口未配置则取环境配置中的，环境中也未配置则取默认值 60000

### 附加信息

建议去除红框中的判断
[https://github.com/metersphere/metersphere/blob/v1.20.24-lts/backend/src/main/java/io/metersphere/api/dto/definition/request/sampler/MsHTTPSamplerProxy.java#L329](https://github.com/metersphere/metersphere/blob/v1.20.24-lts/backend/src/main/java/io/metersphere/api/dto/definition/request/sampler/MsHTTPSamplerProxy.java#L329)
<img width="984" alt="image" src="https://github.com/metersphere/metersphere/assets/46232318/80d696f4-49be-4b53-8cea-87610aa88153">

**Comment by zrfit** [comment]
您好，感谢反馈！
1、你的描述均写的环境配置？环境配置中设置连接/响应超时 50000ms,环境配置中设置连接/响应超时 60000ms，这里是不是写错了？有一个是不是场景步骤连接/响应超时？
2、这里的取值逻辑是，优先请求步骤自身设置的连接/响应超时，没有设置则走环境的设置的连接/响应超时，都没设置则取后端设置的默认连接/响应超时60000ms。

**Comment by shijianliangs** [comment]
> 您好，感谢反馈！ 1、你的描述均写的环境配置？环境配置中设置连接/响应超时 50000ms,环境配置中设置连接/响应超时 60000ms，这里是不是写错了？有一个是不是场景步骤连接/响应超时？ 2、这里的取值逻辑是，优先请求步骤自身设置的连接/响应超时，没有设置则走环境的设置的连接/响应超时，都没设置则取后端设置的默认连接/响应超时60000ms。

不好意思，更正下重现步骤：
场景1：
**环境配置**中设置连接/响应超时 20000ms,**步骤配置**中设置连接/响应超时 10000ms, 实际执行使用的是**步骤配置**中的设置10000ms
场景2：
**环境配置**中设置连接/响应超时 20000ms,**步骤配置**中设置连接/响应超时 60000ms, 实际执行使用的是**环境配置**中的设置20000ms

我在v2.10.3-lts-ac6522a2中复现了。

- 环境配置
<img width="990" alt="image" src="https://github.com/metersphere/metersphere/assets/46232318/3c193975-0b8c-4cfa-b539-90cdac9c8bc7">

- 步骤配置和实际结果
<img width="1680" alt="image" src="https://github.com/metersphere/metersphere/assets/46232318/a1250b05-9678-48eb-9b40-f8550b6917ed">

期望步骤1和步骤2 均使用步骤配置

**Comment by zrfit** [comment]
您好，计划v2.10.4-lts优化。

**Comment by luty2018** [comment]
是这样子的，我们有一个默认的超时时间60000ms，这个超时时间也初始化到每个接口定义和环境中了。
如果用户不修改，那么默认按照这个超时时间去执行。
场景1：用户修改了某一个接口的默认超时时间，这时候用户的主观意图是希望以自身修改的这个时间为准，所以这时候接口自身的超时时间是高于环境的。
场景2：用户修改了环境里的默认超时时间，这时候用户的主观意图是希望所有这个环境执行的接口都以环境里的超时时间为准，避免挨个接口去修改， 那么这时候环境的超时时间是高于接口自身的。
