### ISSUE TITLE
[FEATURE]功能用例层级限制支持配置

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#25502]
### MeterSphere 版本

v2.10.2-lts

### 请描述您的需求或者改进建议

节点8层不够用，建议可以在项目设置里面进行配置
![image](https://github.com/metersphere/metersphere/assets/42445400/7a874da4-d484-46f5-85c8-713b5b8192bf)

**Comment by luty2018** [comment]
好的， 我们会在2个小版本内取消这个限制

**Comment by youliyuan-fit2cloud** [comment]
v2.10.5-lts版本中已取消层级限制。
