### ISSUE TITLE
[BUG] beanshell 脚本断言，在不勾选 JSR223 时，断言结果恒为真

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25504]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

beanshell 脚本断言，在不勾选 JSR223 时，断言结果恒为真

### 重现步骤

1. 脚本断言，不勾选 JSR223 ，断言结果恒为真
![image](https://github.com/metersphere/metersphere/assets/103627487/b8633302-2c9a-41ac-803b-163ef4e06a6c)
![image](https://github.com/metersphere/metersphere/assets/103627487/8e823042-1c1a-4876-bb36-45761a009977)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。
