### ISSUE TITLE
[BUG]【接口自动化】场景里添加“自定义请求”，请求地址http前有个空格，然后发出去的请求就不对

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25505]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

【接口自动化】场景里添加“自定义请求”，请求地址http前有个空格，然后发出去的请求就不对

### 重现步骤

【接口自动化】场景里添加“自定义请求”，请求地址http前有个空格，然后发出去的请求就不对
![1689064694522](https://github.com/metersphere/metersphere/assets/104960608/4d1c1196-8147-4676-bbfa-05405bddbc36)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts修复。
