### ISSUE TITLE
[BUG]使用MS 的录制插件录制的脚本，保存json格式再导入到接口自动化里，这些接口都是无序的，还需要手动调整接口的前后顺序；但是如果把录制脚本保存为jmx格式再导入，接口都是有序的，即接口的前后顺序和录制脚本里一致。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#25517]
### MeterSphere 版本

2.10.3-lts

### 使用外置数据库

否

### 问题描述

[BUG]使用MS 的录制插件录制的脚本，保存json格式再导入到接口自动化里，这些接口都是无序的，还需要手动调整接口的前后顺序；但是如果把录制脚本保存为jmx格式再导入，接口都是有序的，即接口的前后顺序和录制脚本里一致。

### 重现步骤

[BUG]使用MS 的录制插件录制的脚本，保存json格式再导入到接口自动化里，这些接口都是无序的，还需要手动调整接口的前后顺序；但是如果把录制脚本保存为jmx格式再导入，接口都是有序的，即接口的前后顺序和录制脚本里一致。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/e67181fb-81be-40e2-a029-bb30f02e57a2)
![image](https://github.com/metersphere/metersphere/assets/78218624/2cb58a8f-cae0-49db-993b-5477aed8e831)
![image](https://github.com/metersphere/metersphere/assets/78218624/de54d738-125b-462d-9ace-5dc20acd1666)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
