### ISSUE TITLE
[BUG]环境全局变量

### ISSUE THREAD

**Issue by YiweiBen** [metersphere/metersphere#25515]
### 联系方式

63726790@qq.com

### MeterSphere 版本

v2.1

### 使用外置数据库

否

### 问题描述

环境变量在已存在的情况下无法通过vars.remove删除

### 重现步骤

前置操作vars.put(${__metersphere_env_id}+"key","value");
后置操作vars.remove(${__metersphere_env_id}+"key");
当前置操作和后置操作均存在执行时正常，当前置操作Put,后置操作没有Move的情况下，环境变量将无法通过remove删除。
预期：前置操作put，无后置，环境变量应存在。之后无前置，后置删除，环境变量应消失(目前没有预期消失)

**Comment by fit2-zhao** [comment]
感谢建议，目前不支持这样用法，vars.put(${__metersphere_env_id}+"key","value") 这种方式是为了标记更新环境变量存储入库，方便在下一次使用此环境的场景/用例中去获取更新后的内容。
