### ISSUE TITLE
[BUG]MeterSphere最新版本python脚本使用request库verify=False不生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25510]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

MeterSphere最新版本python脚本使用request库verify=False不生效

### 重现步骤

1.准备一个需要证书校验的被测地址
2.在python中使用request库发起请求，使用verify=False参数。
例如：res = requests.post(url=url_, json=json_, headers=header, verify=False)
3.控制台报错：
Max retries exceeded with url: /app/v1.0/user/login (Caused by SSLError(SSLError(1, u'Tag mismatch! (javax.crypto.AEADBadTagException: Tag mismatch! 
这个报错是证书校验失败，说明verify=False参数没有生效。
4.request库版本是2.27.1，在MSv1.20.15-lts版本中，同样的脚本是不会报错的，说明在旧版本中verify=False是生效的。
目前在MeterSphere最新版本中试了request库2.27.1版本，2.22.0版本，这两个版本verify=False都无效。

### 期待的正确结果

需要提供一个在MS最新版适用的request库版本，或者提供其他的能让request请求绕过校验的方法。

**Comment by linfengjjj** [comment]
https://github.com/metersphere/metersphere/issues/16690

**Comment by linfengjjj** [comment]
在MS最新版本中如果把jython包替换成原来的2.7.2版本，这个request请求就不会报错，但是2.7.2版本又有内存溢出，所以不能这么替换。不替换的话，request库verify=False又不生效，有什么办法吗？

**Comment by fit2-zhao** [comment]
```
import requests
import ssl
ssl_context = ssl.create_default_context()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE

response = requests.get('https://example.com', verify=ssl_context)
```

可以使用自定义的 SSLContext： 通过创建一个自定义的 SSLContext 对象，并配置为信任所有证书，来禁用 SSL 证书验证，试试这种写法行不行，如果还是不行就更换 beanshell ｜ groovy 吧。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
