### ISSUE TITLE
[BUG]  系统设置-用户上传文件 提示信息和实际上传的提示不匹配，看不出限制是多大

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25527]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【系统设置】-系统-用户：1、点击上传选择格式xls/xlsx大小为50M的文件提示“上传文件大小不能超过 100MB!”；2、选择大小为100M的文件仍然提示“上传文件大小不能超过 100MB!”

![image](https://github.com/metersphere/metersphere/assets/43202800/bbd7692c-a5d7-47c1-b7e4-589ae17df31d)

### 重现步骤

【系统设置】-系统-用户：1、点击上传选择格式xls/xlsx大小为50M的文件提示“上传文件大小不能超过 100MB!”；2、选择大小为100M的文件仍然提示“上传文件大小不能超过 100MB!”

### 期待的正确结果

提示一致

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
