### ISSUE TITLE
[BUG] ui显示问题， 系统设置-用户管理，当工作空间名称超长显示不全，样式不太好看

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25526]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

ui显示问题， 系统设置-用户管理，当工作空间名称超长显示不全

![image](https://github.com/metersphere/metersphere/assets/43202800/00644e96-24c2-4fd6-9f2d-d5ef8333162c)

### 重现步骤

ui显示问题， 系统设置-用户管理，当工作空间名称超长显示不全

### 期待的正确结果

可以优化下样式

**Comment by zrfit** [comment]
v2.10.4-lts-工作空间下拉框名称显示已优化，过长省略显示，鼠标悬浮到名称上显示全名称。
