### ISSUE TITLE
[BUG] 性能测试-压力配置：压力预测图缺少横纵坐标字段名称

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25524]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

性能测试-压力配置：压力预测图缺少横纵坐标字段名称

![image](https://github.com/metersphere/metersphere/assets/43202800/87073086-c100-49c8-a14e-a704ccb769ef)

### 重现步骤

性能测试-压力配置：压力预测图缺少横纵坐标字段名称

### 期待的正确结果

请给出性能测试-压力配置：压力预测图缺少横纵坐标字段名称

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.4-lts优化。
