### ISSUE TITLE
[BUG] 性能测试：延迟时间无单位（秒）； 性能测试：压力配置，Ramp-Up没有单位（秒）

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25525]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

性能测试：延迟时间无单位（秒）；
![image](https://github.com/metersphere/metersphere/assets/43202800/3e2b4b7a-c2b4-40d7-ac85-29aaaf8d1a28)

### 重现步骤

性能测试：延迟时间无单位（秒）；

### 期待的正确结果

添加单位

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/74878d20-eea0-49ca-8b37-631898e8fafb)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已优化。
