### ISSUE TITLE
[BUG] 系统设置-用户，导入用户，用户名全是数字，导入会有提示超长sql报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25532]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

系统设置-用户，导入用户，用户名全是数字，导入会有提示超长sql报错
![image](https://github.com/metersphere/metersphere/assets/43202800/13c8f585-f2fa-4360-8928-7a77d46a1960)

### 重现步骤

系统设置-用户，导入用户，用户名全是数字，导入会有提示超长sql报错

### 期待的正确结果

给出提示而不是报错

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43202800/2e0317cc-8918-4dce-a18e-b7533a37395a)
52ge个数字

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
