### ISSUE TITLE
[BUG] 【系统设置】-系统-测试资源池：创建资源池-镜像。输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25536]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【系统设置】-系统-测试资源池：创建资源池-镜像。输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.”

![image](https://github.com/metersphere/metersphere/assets/43202800/b1eeea38-8ce6-48c4-8b89-2b78ede08223)

### 重现步骤

【系统设置】-系统-测试资源池：创建资源池-镜像。输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.”

### 期待的正确结果

给出字符限制

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
