### ISSUE TITLE
[BUG] 项目设置-版本管理，可以创建全是空格的数据，系统设置-工作空间，创建空格数据提示名称不能为空，不统一

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25533]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

目设置-版本管理，可以创建全是空格的数据，系统设置-工作空间，创建空格数据提示名称不能为空，不统一

![image](https://github.com/metersphere/metersphere/assets/43202800/9c2eddd7-597b-402f-a3b2-fe9aa433b9c8)

### 重现步骤

目设置-版本管理，可以创建全是空格的数据，系统设置-工作空间，创建空格数据提示名称不能为空，不统一

### 期待的正确结果

应该统一规则，是否可以创建 空格数据？

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本统一该问题。

**Comment by 13290445582** [comment]
v2.10.5已优化，版本管理处不可以创建全是空格的名称。
