### ISSUE TITLE
[BUG]当Content-Type为image/png时，无法正确显示返回的图片

### ISSUE THREAD

**Issue by 844177611** [metersphere/metersphere#25534]
### 联系方式

844177611@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

当Content-Type为image/png时，无法正确显示返回的图片
![image](https://github.com/metersphere/metersphere/assets/129732806/d2ba3a08-57be-46b2-a546-f8d17c240ae2)
![image](https://github.com/metersphere/metersphere/assets/129732806/d6aa39c0-3332-4e86-902a-787411091245)
同样的请求在postman/jmeter中就能正确返回
![image](https://github.com/metersphere/metersphere/assets/129732806/2ed32ce9-6744-4a63-b0e2-1d6d50eb2ed7)

### 重现步骤

1. 找一个返回是图片的接口进行请求（Content-Type:image/png）

### 期待的正确结果

当返回的Content-Type为image/png时，返回体应该是图片

**Comment by zrfit** [comment]
您好，感谢反馈！metersphere平台返回的是文件内容，不支持直接返回文件，如果想看图片，可以写后置脚本实现。
