### ISSUE TITLE
[BUG]优化建议，【系统设置】-系统-测试资源池：选择校验通过的数据点击启用没有提示“启用成功”。选择已启用的数据点击禁用，提示信息建议修改为“禁用成功

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25538]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【系统设置】-系统-测试资源池：
选择校验通过的数据点击启用没有提示“启用成功”。选择已启用的数据点击禁用，提示信息建议修改为“禁用成功

![image](https://github.com/metersphere/metersphere/assets/43202800/d2eea53a-297e-4fb5-8653-d8f19170ace1)

### 重现步骤

【系统设置】-系统-测试资源池：
选择校验通过的数据点击启用没有提示“启用成功”。选择已启用的数据点击禁用，提示信息建议修改为“禁用成功

### 期待的正确结果

建议修改提示语

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
