### ISSUE TITLE
[FEATURE]接口测试-断言规则中使用xpath对html格式进行断言会报错

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#25541]
### MeterSphere 版本

 v2.10.2-lts

### 使用外置数据库

否

### 问题描述

参考MS的官网xpath断言方式进行断言（https://metersphere.io/docs/v1.20.x-lts/user_manual/api_test/api_step/?h=xpath#153-jsonpath），无法断言成功，对不同网站进行xpath断言，还会报各种不同类型的异常错误。

### 重现步骤

以百度为例：
1.接口定义处，增加一个百度地址，执行后，能够获取百度的html相关信息
![image](https://github.com/metersphere/metersphere/assets/47737772/59563757-537e-424c-8ca1-4e9827ec5dfa)
2.在断言规则处，增加一个xpath的断言规则，复制百度的任意xpath路径（例如“百度一下”按钮），添加到断言规则中，再执行接口，即会报错：Open quote is expected for attribute "http-equiv" associated with an element type "meta".
![image](https://github.com/metersphere/metersphere/assets/47737772/88b8a564-0698-4f06-8207-b0ec562e55b1)
![image](https://github.com/metersphere/metersphere/assets/47737772/134cdce6-179d-4aa0-84d8-22d54ee6dcd2)

### 期待的正确结果

能够根据xpath正确获取到对应的值，成功执行断言规则不报错

**Comment by luty2018** [comment]
<img width="798" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/7837e88b-b47e-467b-9658-cb2062c0afbd">
我们缺少一个配置项， 下个小版本加上

**Comment by youliyuan-fit2cloud** [comment]
v2.10.5-lts版本中已支持该功能。
