### ISSUE TITLE
[BUG] 重置定时任务-删除旧定时任务时出现异常

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#25542]
### 联系方式

281016636@qq.com

### MeterSphere 版本

版本:   v2.9.1-32da5112

### 使用外置数据库

是

### 问题描述

无法使用定时任务，更新提示异常： 
![image](https://github.com/metersphere/metersphere/assets/26613645/e8625215-b980-4dcf-b379-fe68d56f0423)
![image](https://github.com/metersphere/metersphere/assets/26613645/a2c05162-5588-4354-bba7-32e0b7fefc91)

### 重现步骤

选择测试计划-定时任务， 更新定时任务，保存

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，建议升级到最新版本v2.10.3-lts尝试。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
