### ISSUE TITLE
[BUG]【接口测试】接口定义TEST中，字段勾选必选，多次点击生成测试数据，会偶尔生成空值

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25548]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/33945037/f4b325ee-6cec-4c2a-8300-522e00a0f2d6

### 重现步骤

1. 创建接口并设置几个参数
2. 勾选必填，点击生成测试数据，多点几次。
3. 偶尔会出现空值的现象。

**Comment by zrfit** [comment]
您好，感谢反馈！参数高级设置最大长度和最小长度没设置的话是会生成空字符串的。
<img width="1068" alt="image" src="https://github.com/metersphere/metersphere/assets/75963100/b2f2a58f-aae0-434a-b09e-bb9b17f5ad2f">
