### ISSUE TITLE
[BUG]swagger 定时同步，偶发同步失败问题

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25549]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

swagger 定时同步，偶发同步失败问题

### 重现步骤

swagger 定时同步，邮件设置通知，偶发同步失败问题，日志有如下报错
![image](https://github.com/metersphere/metersphere/assets/103627487/e7441a6e-936d-46da-83c1-37b5087f1ade)

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题。
1、请提供执行的全部详细日志。
2、定时同步swagger地址是否方便提供？我们尝试复现下。

**Comment by zrfit** [comment]
您好，暂时未复现该问题，后续最新版本如果再遇到该问题，可再打开并提供详细的日志信息和同步信息。
