### ISSUE TITLE
[BUG]【系统设置】-系统-系统参数设置-认证设置：1、添加类型URL输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25540]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【系统设置】-系统-系统参数设置-认证设置：1、添加类型URL输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.
![image](https://github.com/metersphere/metersphere/assets/43202800/e07b9007-88fa-451b-857e-2505fb3d024e)

### 重现步骤

【系统设置】-系统-系统参数设置-认证设置：1、添加类型URL输入字符数过长时点击确定提示异常信息“SQL error happened, please check logs.

### 期待的正确结果

请给出长度限制

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
