### ISSUE TITLE
[BUG]  API 请求体开启 json-schema 后，在代码片段使用API导入，生成的代码使用的接口参数非最新数据

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#25553]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

API 请求体开启 json-schema 后，在代码片段使用API导入，生成的代码使用的接口参数非最新数据

### 重现步骤

有一 API 中请求体参数为下图并开启json-schema：
![image](https://github.com/metersphere/metersphere/assets/103925124/fe656e1b-8c47-456f-81b8-a4f454caf40d)
修改 age 参数为 111122222，仍旧开启 json-schema
![image](https://github.com/metersphere/metersphere/assets/103925124/80dc6ded-a1dc-4c32-9b7e-9fae22938653)
此时项目设置-创建代码片段，使用API导入后，代码中 json 参数非最新
![image](https://github.com/metersphere/metersphere/assets/103925124/81870aed-f76f-48f4-bae4-89dd2eb5ae06)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.4版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
