### ISSUE TITLE
[BUG] UI 测试选择环境后，环境中的地址会覆盖“打开网页”步骤中填写的地址，导致用例中打开的网页均是环境的地址

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#25565]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

问题现象：
UI测试用例包含一个或者多个“打开网页”步骤时，且步骤中填写了网页地址后，选择环境执行时，打开的均是环境的地址，不选择环境执行时，则打开的是“打开网页”步骤设置的地址，由于测试计划关联UI场景时必须选择环境，因此导致一些UI测试场景无法在测试计划执行。
UI测试用例：
<img width="1379" alt="截屏2023-07-12 下午6 15 37" src="https://github.com/metersphere/metersphere/assets/34637801/4bcde1fe-88fb-4187-bcba-13779a7d3528">
未选择环境执行：
<img width="1396" alt="截屏2023-07-12 下午6 16 25" src="https://github.com/metersphere/metersphere/assets/34637801/724fec93-4b59-4c75-acc0-87cf26b5ff6d">
<img width="1318" alt="截屏2023-07-12 下午6 16 42" src="https://github.com/metersphere/metersphere/assets/34637801/10c15866-0e47-461a-afed-077db05e134b">
选择环境执行：环境地址填写的是MS的地址
<img width="1368" alt="截屏2023-07-12 下午6 17 07" src="https://github.com/metersphere/metersphere/assets/34637801/65a6bf1c-8917-4533-b96a-dfeee5fa22c3">

<img width="1349" alt="截屏2023-07-12 下午6 17 18" src="https://github.com/metersphere/metersphere/assets/34637801/d5323a72-919d-4c66-ba78-b3aa1a6ce50a">

### 重现步骤

1.创建一个环境
2.创建一个UI测试用例，包含一个或者多个“打开网页”步骤，并填写与环境不同的地址
3.分别进行选择环境执行和不选择环境执行，执行方式不限

### 期待的正确结果

当“打开网页”步骤未填写网址时，使用环境地址，当“打开网页”步骤填写了网址时，使用填写的地址

**Comment by zrfit** [comment]
您好，感谢反馈！
1、选择环境后，环境中的域名就是会替换打开网页url的域名。
2、可以添加一个环境，不填写HTTP配置，计划批量关联UI场景的时候选择这个环境，则执行的时候场景的url就不会被替换掉了。
3、计划关联UI用例-强制选择环境为已知要优化的问题，计划v2进行优化。
