### ISSUE TITLE
[BUG]项目管理-项目成员，可以添加重复多次添加同一个成员，建议加一个唯一性校验

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25583]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

项目管理-项目成员，可以添加重复多次添加同一个成员，建议加一个唯一性校验
![image](https://github.com/metersphere/metersphere/assets/43202800/fea32ec4-d90c-4701-804d-4b62a8940d44)

### 重现步骤

项目管理-项目成员，可以添加重复多次添加同一个成员，建议加一个唯一性校验

### 期待的正确结果

建议加一个唯一性校验

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.5版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
