### ISSUE TITLE
[FEATURE]接口定义-swagger 定时同步和swagger 导入时，API 更新时间字段没有刷新，会导致无法从页面查看哪些接口更新过，哪些接口已从swagger 移除

### ISSUE THREAD

**Issue by LianWilliam** [metersphere/metersphere#25584]
### MeterSphere 版本

  v2.10.2-lts

### 使用外置数据库

是

### 问题描述

接口定义-swagger 定时同步和swagger 导入时，
API 更新时间字段没有刷新，
会导致无法从页面查看哪些接口更新过，哪些接口已从swagger 移除

### 重现步骤

页面接口定义菜单，点击更多操作-定时同步，或者更多操作-导入，成功后查看列表数据，更新时间字段未刷新

### 期待的正确结果

期望：
1、所有swagger中存在的接口，定时同步、导入时，对应的API更新时间刷新到操作时间
2、swagger不存在的接口，更新时间不刷新

这样可以通过更新时间字段排序，查询到swagger不存在的接口，批量删除，能保障系统接口文档为最新状态

**Comment by zrfit** [comment]
您好，感谢反馈！导入选择覆盖模式，api有变更，更新时间字段更新，api没变更，更新时间字段不更新；对于swagger中没有，但是之前已经导入进来的api，更新时间字段是不更新的。

**Comment by LianWilliam** [comment]
> 您好，感谢反馈！导入选择覆盖模式，api有变更，更新时间字段更新，api没变更，更新时间字段不更新;对于swagger中没有，但是之前已经导入进来的api，更新时间字段是不更新的。

对现在问题就在这，
api没变更，更新时间字段不更新;
对于swagger中没有，但是之前已经导入进来的api，更新时间字段是也不更新；

这2种情况都不更新的话，哪怎么通过什么筛选条件，找出swagger中没有（metersphere中多余的部分），然后删掉呢？

**Comment by LianWilliam** [comment]
从v2.7.1更新到v2.10.2-lts才出现这个问题，v2.7.1之前的版本导入或者定时同步，所有匹配到的API更新时间都更新了，metersphere中多余的部分没更新，我可以根据更新时间倒序，批量选中这些多余的API，然后删除。v2.10.2-lts版本没有筛选条件找出“metersphere中多余的部分”去删掉

**Comment by luty2018** [comment]
1.没有变更的api不会变更“更新时间”，这么做是为了方便用户通过更新时间来筛选本次变更的接口
2.swagger已删除的接口在MS不会同步删除， 因为考虑到不同用户的需求不一致，贸然删除不太合适， 这里我们后面可以在同步操作开放配置项， 用户可以自定义是否同swagger数据保持一致。

**Comment by LianWilliam** [comment]
> 1.没有变更的api不会变更“更新时间”，这么做是为了方便用户通过更新时间来筛选本次变更的接口 2.swagger已删除的接口在MS不会同步删除， 因为考虑到不同用户的需求不一致，贸然删除不太合适， 这里我们后面可以在同步操作开放配置项， 用户可以自定义是否同swagger数据保持一致。



是的，1、2这样是比较合理，目前metersphere中多余的api”想要删掉，目前有没有别的方法能够筛选出来删掉？
另外问一下，说的后面可以在同步操作开发配置项，这个预计什么版本做，有规划吗？

**Comment by luty2018** [comment]
你好，我们已经规划了， 预计会在3.0版本上线这个功能
