### ISSUE TITLE
[FEATURE]【接口自动化】JMX脚本导入接口自动化场景里，无法运行定时任务

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25587]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】JMX脚本导入接口自动化场景里，无法运行定时任务

### 重现步骤

【接口自动化】在JMeter上做好JMX脚本导入接口自动化场景里，不用选择环境就能正常运行，但是设置定时任务时，为啥还需要选择运行环境，导致该场景不能跑定时任务
![image](https://github.com/metersphere/metersphere/assets/104960608/cad66802-ded1-4674-ab95-3408c1f92465)

JMX脚本如下:
[HTTP Request.zip](https://github.com/metersphere/metersphere/files/12035957/HTTP.Request.zip)

**Comment by zrfit** [comment]
您好，感谢反馈！经沟通，后续版本优化。

**Comment by luty2018** [comment]
<img width="592" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/1a58a6b3-c902-4953-acb3-e5fdaa3b620c">
选择默认环境即可。
