### ISSUE TITLE
[BUG]测试计划下面的功能测试用例编辑时，上传附件只能下载，不能删除，而且只要有一个用例上传了附件，编辑其他用例的时候也会出现这个附件

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2558]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9.1
**Bug 描述**
简要描述您碰到的问题

1、测试计划下面的功能测试用例编辑时，上传附件只能下载，不能删除(选错了怎么办，还没办法预览）
2、而且只要有一个用例上传了附件，编辑其他用例的时候也会出现这个附件

**Comment by zyyfit** [comment]
收到，测试计划里应该禁止编辑用例的，也就是不可以上传附件，只能标记测试执行实际结果、是否通过和添加评论，附件可以在测试用例模块中添加和删除

**Comment by dashenyucainiao** [comment]
1、目前是可以上传附件的，而且只要有一个用例上传了附件，编辑其他用例的时候也会出现这个附件
2、如果不能上传附件，就把上传附件的按钮权限控制一下

**Comment by zyyfit** [comment]
您好，已经修复了这个问题，目前的逻辑是：
测试计划里禁止编辑用例（包括上传附件也不可以，只能预览和下载附件）
