### ISSUE TITLE
[BUG]项目设置-模板管理，新建用例模板，模板名称、描述、用例名称、步骤描述输入超长字符数多次点击保存，字段会出现自动填充字符/////////////////////

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25580]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

项目设置-模板管理，新建用例模板，模板名称、描述、用例名称、步骤描述输入超长字符数多次点击保存，字段会出现自动填充字符/////////////////////

### 重现步骤

1、模板名称、描述、用例名称、步骤描述输入超长字符数
2、已选字段默认值选择用例状态、责任人、用例等级
3、添加字段或设置自定义字段默认值都输入超长字符数点击保存(多点了几次)  责任人、添加字段默认值就会自动填充内容。

![d1ae87a3e67228f30acb31a13e548e2](https://github.com/metersphere/metersphere/assets/43202800/b0dee3ca-1fec-48ab-af2f-1ed66072aed8)

### 期待的正确结果

超长做校验，多点几次自动追加字符

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
