### ISSUE TITLE
[FEATURE]优化建议：系统设置，用户组月权限，修改角色权限 取消勾选第一个查询会取消所有菜单勾选，建议给出说明

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25586]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

优化建议：系统设置，用户组月权限，修改角色权限 取消勾选第一个查询会取消所有菜单勾选，建议给出说明

![给提示](https://github.com/metersphere/metersphere/assets/43202800/b7e611bd-6d06-4168-b6c7-426e4134e0f0)

### 重现步骤

优化建议：系统设置，用户组月权限，修改角色权限 取消勾选第一个查询会取消所有菜单勾选，建议给出说明

问题：按照常规操作都是取消一个就是一个，目前是把查询选项都取消了，用户认为很难理解
内部说明是有查询权限才能操作别的，取消查询别的不能操作，但是使用习惯非常规，建议加个提示？ 会比较好

### 期待的正确结果

使用习惯非常规，建议加个提示？ 会比较好

**Comment by luty2018** [comment]
出于安全考虑，我们所有的权限都是基于查询权限为前提的。查询权限都没有了， 编辑、删除这些权限还在，用户啥也不能做， 岂不是更像bug？
不需要说明， 因为没有这种使用场景，不给查询但是给操作权限， 你能举个例子吗？

**Comment by xhy12** [comment]
此处逻辑并无问题，只是反馈和常见的使用方式不同。所以希望加个说明

**Comment by xhy12** [comment]
此处说的使用方式是：所见即所得，勾选什么就展示什么。
此处设计功能业务，后续再给客户解释下
