### ISSUE TITLE
[BUG]优化建议：系统设置-系统参数设置，页面上传logo图片没有校验格式，上传zip文件，点确定后一直转圈报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25588]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

优化建议：系统设置-系统参数设置，页面上传logo图片没有校验格式，上传zip文件，点确定后一直转圈报错

### 重现步骤

优化建议：系统设置-系统参数设置，页面上传logo图片没有校验格式，上传zip文件一直转圈报错

![上传非图片格式文件，直接校验](https://github.com/metersphere/metersphere/assets/43202800/3fea6cb4-ff85-4f79-b8cf-ee5a5eed594c)

### 期待的正确结果

建议在前端上传文件限制格式，上传错误文件先给出友好提示

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts优化。
