### ISSUE TITLE
[BUG] 环境设置，创建字符名称填写了边界值64的数据。 然后列表复制数据，因为带上了copy字样导致字符超长，但是此处无提示超长字符也没有看到copy，容易误解建议检查名称弹个提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25581]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

[BUG] 环境设置，创建字符名称填写了边界值64的数据。 然后列表复制数据，因为带上了copy字样导致字符超长，但是此处无提示超长字符也没有看到copy，容易误解建议检查名称弹个提示

### 重现步骤

1环境设置，创建字符名称填写了边界值64的数据。 然后列表复制数据，因为带上了copy字样导致字符超长，
2 但是此处无提示超长字符也没有看到copy，容易误解建议检查名称弹个提示
![image](https://github.com/metersphere/metersphere/assets/43202800/99e3dff4-d1df-4180-8130-da6b90b02b81)

### 期待的正确结果

建议检查名称弹个提示

**Comment by 13290445582** [comment]
感谢您的反馈，2.10.4版本对该问题进行了修复，请等待发布最新版本后升级尝试。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
