### ISSUE TITLE
[BUG]【接口自动化】删除本地csv，再次点击保存或运行场景，页面会提示该文件已被修改。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25591]
### MeterSphere 版本

v1.20.23-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】在桌面上传csv文件后，运行场景可以正常运行。删除本地桌面该csv，再次点击保存或运行场景，页面会提示该文件已被修改。

### 重现步骤

【接口自动化】在桌面上传csv文件后，运行场景可以正常运行。删除本地桌面该csv，再次点击保存或运行场景，页面会提示该文件已被修改。
![1689229752579](https://github.com/metersphere/metersphere/assets/104960608/5815f41a-e16b-4f88-93dc-ac27fe57801d)
![1689229752588](https://github.com/metersphere/metersphere/assets/104960608/32f5ec81-fbb0-4abf-ba4f-96cd7f99c0fb)

**Comment by zrfit** [comment]
您好，感谢反馈！引用的本地附件发生变更需要重新上传附件，目前metersphere平台前端使用的Element UI 上传组件规范是这样的，防止文件攻击。
