### ISSUE TITLE
[BUG] 【系统设置】-工作空间-操作日志：部分模块操作日志没有记录，例如系统设置、项目设置中的应用管理、版本管理等。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25594]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【系统设置】-工作空间-操作日志：部分模块操作日志没有记录，例如系统设置、项目设置中的应用管理、版本管理等。

![Uploading image.png…]()

### 重现步骤

【系统设置】-工作空间-操作日志：部分模块操作日志没有记录，例如系统设置、项目设置中的应用管理、版本管理等。

### 期待的正确结果

建议添加日志

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/81eee3a2-62a7-4544-88c0-06a5f3abf80f)

**Comment by 13290445582** [comment]
您好，设计上没有这部分，后续我们添加了请求操作来辅助查询这部分日志，后续在V2版本上不会再追加操作日志，感谢您的理解与支持。
