### ISSUE TITLE
[BUG]功能用例关联三方平台需求后，在脑图模式修改用例名称或内容并保存，会丢失需求关联关系

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25598]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

功能用例关联三方平台需求后，在脑图模式修改用例名称或内容并保存，会丢失需求关联关系

### 重现步骤

1.功能用例关联一个jira需求
2.在脑图模式下修改功能用例的内容并保存
3.回到用例列表，查看用例详情，发现用例已经没有关联需求了

### 期待的正确结果

不应该丢失关联关系

### 相关日志输出

```shell
附件里有复现视频
```

### 附加信息

[关联需求.zip](https://github.com/metersphere/metersphere/files/12036438/default.zip)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
