### ISSUE TITLE
[BUG] 【报表统计】：全部报表“场景用例”建议修改为接口自动化的场景用例 容易误解，并且ui自动化场景没有统计到

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25595]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

【报表统计】：全部报表“场景用例”建议修改为接口自动化的场景用例 容易误解，并且ui自动化场景没有统计到\\\

![image](https://github.com/metersphere/metersphere/assets/43202800/ebc03a80-752c-42aa-85f4-40171dab12db)

### 重现步骤

【报表统计】：全部报表“场景用例”建议修改为接口自动化的场景用例 容易误解，并且ui自动化场景没有统计到

### 期待的正确结果

全部报表“场景用例”建议修改为接口自动化的场景用例 容易误解
统计ui自动化场景

**Comment by 13290445582** [comment]
您好，报表统计模块后期不进行修改bug了，我们的V3.0版本会去掉这个模块，感谢理解与支持。
