### ISSUE TITLE
[BUG] 配额管理，删除一条数据，提示删除成功，但是列表数据还在

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25590]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

配额管理，删除一条数据，提示删除成功，但是列表数据还在

![image](https://github.com/metersphere/metersphere/assets/43202800/5dc0b84d-7c50-47d6-9cea-16929337c94f)

### 重现步骤

配额管理，删除一条数据，提示删除成功，但是列表数据还在

如果不能删除可以屏蔽删除按钮，如果删除的是其他信息可以给一个提示

### 期待的正确结果

如果不能删除可以屏蔽删除按钮，如果删除的是其他信息可以给一个提示

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。
