### ISSUE TITLE
[BUG]优化建议 系统设置-环境组：编辑不填内容点+ 没反应，可以给个提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25593]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

优化建议 系统设置-环境组：编辑不填内容点+ 没反应，可以给个提示
![image](https://github.com/metersphere/metersphere/assets/43202800/a5a51d50-6068-463a-9673-dbada3520362)

### 重现步骤

优化建议 系统设置-环境组：编辑不填内容点+ 没反应，可以给个提示

### 期待的正确结果

优化建议 系统设置-环境组：编辑不填内容点+ 没反应，可以给个提示

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本优化这个问题。

**Comment by 13290445582** [comment]
v2.10.5已优化
