### ISSUE TITLE
[BUG] 系统设置-环境组名称为边界值50，在列表里面点复制字符超长 会提示sql error。 _copy边界值复制问题请优化

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25592]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

系统设置-环境组名称为边界值50，在列表里面点复制字符超长 会提示sql error。 _copy边界值复制问题请优化

![image](https://github.com/metersphere/metersphere/assets/43202800/55c3b56d-04d2-447e-b579-0ae1fba9857b)

### 重现步骤

系统设置-环境组名称为边界值50，在列表里面点复制字符超长 会提示sql error。 _copy边界值复制问题请优化

### 期待的正确结果

 _copy边界值复制问题请优化提示信息等，

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
