### ISSUE TITLE
[BUG]性能测试-从接口场景引用。接口列表查询结果选择数据保存，再次打开列表查询结果还在，重新打开应该清理

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25597]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

性能测试-从接口场景引用。接口列表查询结果选择数据保存，再次打开列表查询结果还在，重新打开应该清理

![image](https://github.com/metersphere/metersphere/assets/43202800/ff8f2b5e-aa5e-47cf-8c31-eb9330f7f41d)

### 重现步骤

1、性能测试-从接口场景引用。接口列表查询结果选择数据保存，
2、再次打开列表查询结果还在，重新打开应该清理

### 期待的正确结果

查询结果重置列表

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5修复这个问题。

**Comment by 13290445582** [comment]
您好，经过反馈，性能测试关联场景支持同一场景关联多次，所以接口列表查询结果选择数据保存，再次打开列表查询结果还在。后续有问题请重新提issue，感谢您的理解与支持。
