### ISSUE TITLE
[FEATURE] 接口测试中，希望能支持图片、excel等的附件上传

### ISSUE THREAD

**Issue by BoswellBao** [metersphere/metersphere#256]
**请描述您的需求或者改进建议.**
接口测试中，希望能支持图片、excel等的附件上传

**请描述你建议的实现方案**
每个接口上传的附件可以存放到服务器，下次再跑接口时不用再上传本地的附件

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已支持该功能，请升级体验。
