### ISSUE TITLE
监控详情无法查看多个节点的数据

### ISSUE THREAD

**Issue by qby1234321** [metersphere/metersphere#25606]
### 联系方式

16619941750（微信同号）

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

我们的项目服务器有4各节点，我想压测完成之后的报告里边能看到这4个节点的监控详情，但是现在只能看到一个

### 重现步骤

说明：
1.把监控详情里边的曲线图称为：曲线图，如图：
![image](https://github.com/metersphere/metersphere/assets/35056522/4af55f5b-dc68-4dc2-8092-d74706b77452)
2.把选择监控的节点就叫节点，如图：
![image](https://github.com/metersphere/metersphere/assets/35056522/e314fc72-85ee-424b-9e81-f0888cc274e4)
3.把CPU，memort，disk等等称为指标，如图：
![image](https://github.com/metersphere/metersphere/assets/35056522/89102251-d8e0-4b42-b15a-fa48cb5c600a)
操作步骤如下：
- 第一次，只监控一个节点下的5个指标，设置如下：
![image](https://github.com/metersphere/metersphere/assets/35056522/f6aa8887-7ed0-4f51-aef8-02b7b3eb4fa8)
曲线图展示如下：
![image](https://github.com/metersphere/metersphere/assets/35056522/b58fa88a-0e92-4ae7-8e57-7231636a69c9)

- 第二次，想监控多个节点下的5个指标，设置如下：
- 
![image](https://github.com/metersphere/metersphere/assets/35056522/b40a8892-6aec-45d5-941c-e89dff0cae82)
![image](https://github.com/metersphere/metersphere/assets/35056522/8fa763b1-4b53-4ec3-bb28-b62e087eafa5)
![image](https://github.com/metersphere/metersphere/assets/35056522/0b30adbe-b72c-4720-a2bd-3d975938a20f)
![image](https://github.com/metersphere/metersphere/assets/35056522/a8b62d74-ef16-4831-a68f-49ac21874f2b)

- 曲线图展示如下：
![image](https://github.com/metersphere/metersphere/assets/35056522/4d4304b3-f710-4fca-a8fb-45443e899bb1)

### 期待的正确结果

想要的结果是：切换节点，看到对应节点的监控，或者根据切换指标，显示对应的指标，比如切换到CPU那个指标，我可以看到4个节点的cpu使用情况，在切换到内存，我可以看到4个节点上的内存使用情况，而不是无论怎么切换始终都是第一个指标不变

**Comment by 13290445582** [comment]
您好，该问题计划于v2.10.4版本修复。

**Comment by 13290445582** [comment]
v2.10.4-lts版本已修复。
