### ISSUE TITLE
使用测试计划的失败重试机制，查看测试报告发现前面的接口执行成功了，但是后面还是触发了失败重试接口。

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#25600]
### 联系方式

14707070227

### MeterSphere 版本

 v2.10.2-lts-b028f4ea

### 使用外置数据库

否

### 问题描述

使用测试计划的失败重试机制，查看测试报告发现前面的接口执行成功了，但是后面还是触发了失败重试接口。

### 重现步骤

1. 创建一个测试计划，关联接口测试场景用例
2. 执行测试计划，使用测试计划的失败重试机制
3.运行测试计划，查看测试报告发现前面的接口都执行成功了，但是后面还是重试了接口
4.执行测试计划不使用失败重试机制，发现是接口是可以正常执行的

### 期待的正确结果

执行测试计划，使用测试计划的失败重试机制，运行测试计划，查看测试报告接口执行成功并且不发生失败重试。

### 相关日志输出

```shell
无
```

### 附加信息

正常运行的截图：
<img width="966" alt="ce9e83946557d8197277ffade77e84e" src="https://github.com/metersphere/metersphere/assets/50016789/e34c74e7-7156-41da-be30-8c606b41f667">
使用失败重试的截图：

<img width="697" alt="73dd6dbde023894d34cf85ca7949c67" src="https://github.com/metersphere/metersphere/assets/50016789/84b2763b-b88a-45a3-9ea6-921024658a8a">

**Comment by 13290445582** [comment]
您好，该问题在最新环境未复现，建议升级至最新环境尝试。
场景和运行环境可以导出发我吗？

**Comment by fit2-zhao** [comment]
已经定位到是XPath断言的一个问题，计划2.10.5 LTS 版本修复。

**Comment by 13290445582** [comment]
v2.10.5已修复
