### ISSUE TITLE
[BUG]JSON-SCHEMA模版integer，number类型错误

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#2560]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
JSON-SCHEMA模版integer，number类型参数发送请求时未按预期转换成正确的值
<img width="1115" alt="wecom-temp-bea5c5407beac068b9bbc15bbb64d0dc" src="https://user-images.githubusercontent.com/72964047/117415753-3dd96f00-af4b-11eb-99ae-37dcf2cac637.png">
<img width="1257" alt="wecom-temp-ecaf7f92e335ad5a5ef4e32a22bef073" src="https://user-images.githubusercontent.com/72964047/117415767-429e2300-af4b-11eb-945a-c981c07b8780.png">
<img width="1263" alt="wecom-temp-2871dfffc79c9b06ca874e0604e11ff6" src="https://user-images.githubusercontent.com/72964047/117415784-45991380-af4b-11eb-840d-6dd2d356b5db.png">

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by zyyfit** [comment]
您好，1.10.0版本已修复，请升级使用
