### ISSUE TITLE
[BUG]【接口定义】在线json解析里可以正常解析，放接口里然后点击json-schame,页面卡顿，而且过一段时间会报 json解析错误 

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25614]
### MeterSphere 版本

v2.10.3lts

### 使用外置数据库

否

### 问题描述

【接口定义】json在编辑器里可以正常解析，放接口里然后点击json-schame,页面卡顿，而且过一段时间会报 json解析错误 

### 重现步骤

【接口定义】json在在线编辑器里可以正常解析，放接口里然后点击json-schame,页面卡顿，而且过一段时间会报 json解析错误 
![image](https://github.com/metersphere/metersphere/assets/104960608/9f1c7e57-cf3e-48b3-a709-a130430c7b67)
![image](https://github.com/metersphere/metersphere/assets/104960608/da65ac48-0523-42cb-8a0b-98bf3b99980b)
![image](https://github.com/metersphere/metersphere/assets/104960608/db24a9c7-b4c4-484e-8965-89d3f9d3260f)

json文件如下:
[新建文本文档.zip](https://github.com/metersphere/metersphere/files/12038349/default.zip)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。
