### ISSUE TITLE
[BUG]【测试跟踪】脑图里-调整模块顺序点击保存后，切到列表页面，然后再进入脑图页面，发现还是调整之前的目录结构

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25618]
### MeterSphere 版本

v1.20.23-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】脑图里-调整模块顺序点击保存后，切到列表页面，然后再进入脑图页面，发现还是调整之前的目录结构

### 重现步骤

【测试跟踪】脑图里-调整模块顺序点击保存后，切到列表页面，然后再进入脑图页面，发现还是调整之前的目录结构
![image](https://github.com/metersphere/metersphere/assets/104960608/026993ac-e87c-403e-85e3-bebf3328bdc4)
![image](https://github.com/metersphere/metersphere/assets/104960608/8be3df24-26f4-4e45-a4c7-f8fd5fb4765d)

**Comment by davidcchen** [comment]
还有优先级，添加后保存，刷新后就消失了

**Comment by 13290445582** [comment]
您好，感谢您的反馈，计划于v2.10.5版本修复这个问题。优先级问题未复现，您确认一下保存成功了吗，在最新环境刷新后数据也是存在的，建议您升级至最新版本尝试一下。

**Comment by 13290445582** [comment]
您好，经过反馈，脑图模式暂不支持定制模块的顺序，感谢您的理解与支持。
