### ISSUE TITLE
[BUG]从2.10.1升级到2.10.3版本后，进项目管理的文件管理界面报没权限，必须是超级管理员才行

### ISSUE THREAD

**Issue by zlp19860220** [metersphere/metersphere#25617]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

从2.10.1升级到2.10.3版本后，进项目管理的文件管理界面报没权限

### 重现步骤

从2.10.1升级到2.10.3版本后，有系统管理员或者项目管理员权限的人登录到项目管理的文件管理界面，报无权限然后跳转到了系统设置界面了
![报错](https://github.com/metersphere/metersphere/assets/38429286/35ac3eba-cddb-413d-9e75-b7e2ce797bdc)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。
1.升级后清理下缓存
2.请检查下用户的所属用户组（项目管理员）的权限是否开启 “文件管理”的权限

**Comment by zlp19860220** [comment]
![报错1](https://github.com/metersphere/metersphere/assets/38429286/24d8dfd2-8c78-45bc-983c-17f127f46686)

对应的用户是有项目管理员权限的

**Comment by youliyuan-fit2cloud** [comment]
再看看当前查看的这个项目，该用户是什么权限的，查看对应的权限，例如“项目成员” 用户组 的权限 未开启 “文件管理”  ？

**Comment by zlp19860220** [comment]
有项目成员、项目管理员这两个角色，权限不叠加么，优先项目成员么？

**Comment by youliyuan-fit2cloud** [comment]
> 有项目成员、项目管理员这两个角色，权限不叠加么，优先项目成员么？

权限是叠加的，现在问题还存在吗？这个用户怎么添加到这个项目步骤描述一下？怀疑用户添加到项目的方式我们授权这块没考虑到。

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
