### ISSUE TITLE
[BUG]【测试跟踪】“用例评审”里关联用例，筛选打标签的用例，选择所有数据，点击确定，页面毫无反应，后台报错

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25639]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】功能用例处给用例打标签，然后在“用例评审”里关联用例，筛选打标签的用例，选择所有数据，点击确定，页面毫无反应，后台报错

### 重现步骤

【测试跟踪】功能用例处给用例打标签，然后在“用例评审”里关联用例，筛选打标签的用例
![image](https://github.com/metersphere/metersphere/assets/104960608/5b168da5-c02f-44cf-92bc-1980c2b0b73f)
![image](https://github.com/metersphere/metersphere/assets/104960608/aa002c13-ed79-455b-a223-fc863e455222)
![image](https://github.com/metersphere/metersphere/assets/104960608/b4d0e3aa-afd8-4f5c-9ff8-9a247b156f82)
选择所有数据，点击确定，页面毫无反应，查看后台/opt/metersphere/logs/test-track里的info日志，发现报错
![image](https://github.com/metersphere/metersphere/assets/104960608/1bf2e8c0-bc5f-4494-91eb-90b5d0c8edf2)
![image](https://github.com/metersphere/metersphere/assets/104960608/32b20336-076a-46a6-9106-4613185b5f28)
![image](https://github.com/metersphere/metersphere/assets/104960608/29faca95-52e4-4c56-bf5e-addabf14c27d)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
https://github.com/metersphere/metersphere/issues/25646

**Comment by 13290445582** [comment]
v2.10.5已修复
