### ISSUE TITLE
[BUG]用例评审-高级搜索筛选标签后，无法实现所有用例关联

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25646]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

用例评审-高级搜索筛选标签后，无法实现所有用例关联.

### 重现步骤

1.新增用例30个，全部增加标签v5.9
2.增加用例评审
3.用例评审关联用例，高级搜索筛选标签v5.9后，无法实现所有用例关联.
![image](https://github.com/metersphere/metersphere/assets/55130444/eadfc2c5-4985-4d22-aa50-20c7b9fc6584)
![image](https://github.com/metersphere/metersphere/assets/55130444/9c6a03b8-bab5-4045-933e-a25ad4786680)
![image](https://github.com/metersphere/metersphere/assets/55130444/54684b8d-3feb-4ce9-bdef-c9617b7d450c)

### 期待的正确结果

能够根据高级搜索标签筛选出来的结果，做所有用例关联。

**Comment by 13290445582** [comment]
您好，重复问题，已关联。
