### ISSUE TITLE
[BUG]测试计划中失败的用例，关联缺陷显示的都是一样

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#2564]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版本
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/26756176/117416684-32d30e80-af4c-11eb-8b04-4e3c48cb2a75.png)

**Comment by xulinde** [comment]
v1.10.2已修复
