### ISSUE TITLE
[需求优化&Bug]缺陷详情页面，点击翻页按钮会自动修改该所属模块为“默认模块”

### ISSUE THREAD

**Issue by jinjiacheng2018** [metersphere/metersphere#2565]
**请描述您的需求或者改进建议.**
缺陷1：进入缺陷编辑页面，不修改该任何内容，点击翻页按钮，会自动修改模块为“默认模块”
![image](https://user-images.githubusercontent.com/37428569/117419608-5c416980-af4f-11eb-98db-f03855ba1922.png)

**请描述你建议的实现方案**
优化1：建议修改用例确认状态后，能够自动翻页，避免手动点击翻页
优化2：建议用例详情不要只会展示，不直观

**Comment by jinjiacheng2018** [comment]
metersphere版本：V1.9.1

**Comment by xulinde** [comment]
v1.13已优化
