### ISSUE TITLE
[BUG]在测试计划中，使用脑图模式，将用例标记为“通过”并保存，在系统设置-操作日志中并没有得到记录

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#25659]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

v2.10.3-lts-ac6522a2

### 使用外置数据库

是

### 问题描述

在测试计划中，使用脑图模式，将用例标记为通过并保存，在系统设置-操作日志中并没有得到记录

### 重现步骤

1、在测试跟踪-功能用例中新建一条测试用例
2、新建一个测试计划
3、在新建立的测试计划中关联这条测试用例
4、切换到脑图模式
5、在脑图模式下，点击“通过”按钮，并点击保存；此时会弹出保存成功的弹窗
6、进入系统设置-操作日志，并没有看到用例状态更新的日志提示

### 期待的正确结果

期待的正确结果：在系统设置-操作日志中，有日志记录此条测试用例被更新

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
