### ISSUE TITLE
[BUG]用脑图的形式执行测试计划里的用例，点击保存后日志没有相关记录

### ISSUE THREAD

**Issue by 57cz** [metersphere/metersphere#25662]
### 联系方式

xu.yao@faw-vw.com

### MeterSphere 版本

v2.10.3-lts-ac6522a2

### 使用外置数据库

否

### 问题描述

用脑图的形式执行测试计划里的用例
<img width="886" alt="f88fadf74ff78d1067c620df7dfed98f" src="https://github.com/metersphere/metersphere/assets/51302655/8ffd88c9-bf9f-46b8-af5c-de8837cc8725">
点击保存后日志没有相关记录
<img width="958" alt="388e917db3f46d3c6232d34f27554599" src="https://github.com/metersphere/metersphere/assets/51302655/0d68c397-bf8c-4c00-8cf0-dbcf27b1a1d1">

### 重现步骤

1建立测试计划，关联测试用例
2利用脑图的形式通过测试用例
3查看日志，发现没有相关记录

### 期待的正确结果

通过脑图形式执行测试用例，日志中显示正确结果

**Comment by zrfit** [comment]
您好，感谢反馈！同#25659。
