### ISSUE TITLE
[BUG]Schema `metersphere` contains a failed migration to version 2

### ISSUE THREAD

**Issue by sonce** [metersphere/metersphere#25669]
### 联系方式

oiqwys@gmail.com

### MeterSphere 版本

v2.9.1

### 使用外置数据库

是

### 问题描述

环境: K8S
外置的数据库
安装后POD无法启动，查看日志是flyway的migration失败了。

### 重现步骤

1. helm安装
2. 查看日志发现migration version 2失败
3. 查看数据库，version2  并没有失败（metersphere_version表sucess = 1）
4. version 133 的sucess = 0。于是手动执行了2.9.0/ddl/V138__modify_case_node_index.sql。并设置sucess = 1
5. 重新helm安装，依旧出现migration的报错（version = 2）.metersphere_version中的所有version都已经是sucess。

### 相关日志输出

```shell
2023-07-18 13:37:28,754 ERROR g.springframework.boot.SpringApplication: 822 - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 2 !
```

**Comment by liqiang-fit2cloud** [comment]
再上下翻翻日志，里面有详细的sql错误。

**Comment by sonce** [comment]
已解决。
除了metersphere_version表，还有api_version。其他version表还存在sucess=0的。

**Comment by doctorlong** [comment]
> ```shell
> migration
> ```
哥们咋解决的呀

**Comment by doctorlong** [comment]
> 已解决。 除了metersphere_version表，还有api_version。其他version表还存在sucess=0的。

哥们咋解决的呀，我也是类似的问题

**Comment by EstherOnly** [comment]
> > 已解决。 除了metersphere_version表，还有api_version。其他version表还存在sucess=0的。
> 
> 哥们咋解决的呀，我也是类似的问题

把表api_version清空，重启api-test服务就可以了
