### ISSUE TITLE
[BUG]UI测试，数字变量值太大时，引用后会变成科学计数法

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25670]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

UI测试，数字变量值太大时，引用后会变成科学计数法

### 重现步骤

1.设置场景变量name=999999999999999
![image](https://github.com/metersphere/metersphere/assets/88763608/329497b9-6fcf-4c7a-afa0-20355fd362a9)

2.测试百度输入框，输入name变量，结果输入后是科学计数法
![image](https://github.com/metersphere/metersphere/assets/88763608/1accad68-afbf-42d9-897f-f90efe4d4ddf)
![image](https://github.com/metersphere/metersphere/assets/88763608/dbd4518b-93db-40bd-af1d-6e5c0b124a30)

### 期待的正确结果

不自动转换科学计数法

**Comment by xiaomeinvG** [comment]
您好，在java 中 int的最大类型为2的31次方-1 ，您当前输入的值已经大于 int 类型的最大范围，所以会产生科学计数，您可以选择更换类型
