### ISSUE TITLE
[BUG]【接口测试】当返回体为xml自定义格式时，使用xpath方式提取值提取不到，但是使用代码就能正常提取到

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25679]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

【接口测试】当返回体为xml自定义格式时，使用xpath提取值提取不到，但是使用代码就能正常提取到

### 重现步骤

【接口测试】当返回体为xml自定义格式时，使用xpath方式提取值提取不到，但是使用代码就能正常提取到
![image](https://github.com/metersphere/metersphere/assets/104960608/6b886ecc-5569-4878-bf16-85c03ad41839)
![image](https://github.com/metersphere/metersphere/assets/104960608/9928e3c4-458b-4a88-8974-2bb37ba6503d)
![image](https://github.com/metersphere/metersphere/assets/104960608/63581458-2d56-47e5-9a25-e34b18223a31)

返回体如下:
[test.zip](https://github.com/metersphere/metersphere/files/12079435/test.zip)

**Comment by liqiang-fit2cloud** [comment]
自己研究研究。

**Comment by 2lipan** [comment]
已在 jmeter 上试出来了
![image](https://github.com/metersphere/metersphere/assets/104960608/91fd98aa-afc3-465f-9ea7-59f54570918b)
![image](https://github.com/metersphere/metersphere/assets/104960608/955deaa8-b1e7-4b78-b3cf-afe12000769d)
