### ISSUE TITLE
[QUESTION]Mac使用docker本地部署，gateway/system-setting/ms-data-streaming这3个服务起不来

### ISSUE THREAD

**Issue by EdwardCheck** [metersphere/metersphere#25687]
### 请描述您的问题

- gateway
- system-setting
- ms-data-streaming

其他容器都能正常启动，这3个服务启动失败，看日志是连不上mysql，通过本机navicate可以连上这个mysql说明数据库是ok的
镜像版本: `MS_IMAGE_TAG=v2.10.2-lts`
mysql变量

```
MS_EXTERNAL_MYSQL=false
MS_MYSQL_HOST=mysql
MS_MYSQL_DB=metersphere
MS_MYSQL_USER=root
MS_MYSQL_PORT=3307
MS_MYSQL_PASSWORD=Password123@mysql
```

错误日志

```
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
        ... 27 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
        ... 30 common frames omitted
```

**Comment by youliyuan-fit2cloud** [comment]
https://metersphere.io/docs/v2.x/installation/offline_installation_mac/
你好，参考上述链接，mac电脑配置是不是太低了 ？安装方式署是在线安装部署吗？还是源码部署？

**Comment by EdwardCheck** [comment]
> https://metersphere.io/docs/v2.x/installation/offline_installation_mac/ 你好，参考上述链接，mac电脑配置是不是太低了 ？安装方式署是在线安装部署吗？还是源码部署？

- 配置 macbook pro 16G + M1芯片
- 离线安装：文件名 metersphere-offline-installer-v2.10.2-lts-arm64

**Comment by youliyuan-fit2cloud** [comment]
> > https://metersphere.io/docs/v2.x/installation/offline_installation_mac/ 你好，参考上述链接，mac电脑配置是不是太低了 ？安装方式署是在线安装部署吗？还是源码部署？
> 
> * 配置 macbook pro 16G + M1芯片
> * 离线安装：文件名 metersphere-offline-installer-v2.10.2-lts-arm64

docker ps 看下 mysql 端口查看下配置的是不是3307 ？默认值是3306。

**Comment by EdwardCheck** [comment]
> 

```
CONTAINER ID   IMAGE                                                                             COMMAND                    CREATED         STATUS                             PORTS                                            NAMES
92ab35084a72   registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.33                         "docker-entrypoint.s…"    3 minutes ago   Up 3 minutes (healthy)             33060/tcp, 0.0.0.0:3307->3306/tcp                mysql
7eb18b06110c   registry.cn-qingdao.aliyuncs.com/metersphere/system-setting:v2.10.2-lts           "/deployments/run-ja…"    5 days ago      Up 3 seconds (health: starting)                                                     system-setting
49383e481461   registry.cn-qingdao.aliyuncs.com/metersphere/gateway:v2.10.2-lts                  "/deployments/run-ja…"    5 days ago      Up 16 seconds (health: starting)   0.0.0.0:8081->8000/tcp                           gateway
ce583dd721a1   registry.cn-qingdao.aliyuncs.com/metersphere/data-streaming:v2.10.2-lts           "/deployments/run-ja…"    5 days ago      Restarting (1) 13 seconds ago                                                       ms-data-streaming
12630fc7da32   registry.cn-qingdao.aliyuncs.com/metersphere/eureka:v2.10.2-lts                   "/deployments/run-ja…"    5 days ago      Up 5 minutes (healthy)                                                              eureka
c339afeb2ae3   registry.cn-qingdao.aliyuncs.com/metersphere/redis:6.2.6                          "docker-entrypoint.s…"    5 days ago      Up 5 minutes (healthy)             0.0.0.0:6379->6379/tcp                           redis
6cbae0bcbc64   registry.cn-qingdao.aliyuncs.com/metersphere/kafka:3.4.0                          "/opt/bitnami/script…"    5 days ago      Up 5 minutes (healthy)             0.0.0.0:9092->9092/tcp                           kafka
967209ad2a53   registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:v1.5.0                 "/bin/node_exporter …"    2 weeks ago     Up 5 minutes (healthy)                                                              nodeexporter
946b459a17a0   registry.cn-qingdao.aliyuncs.com/metersphere/minio:RELEASE.2023-04-13T03-08-07Z   "/usr/bin/docker-ent…"    2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:9000-9001->9000-9001/tcp                 minio
b7da8c831fd4   registry.cn-qingdao.aliyuncs.com/metersphere/node-controller:v2.10.2-lts          "sh -c 'sed -i \"s/:1…"   2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:8082->8082/tcp, 0.0.0.0:9100->9100/tcp   ms-node-controller
f0058c88d655   registry.cn-qingdao.aliyuncs.com/metersphere/prometheus:v2.42.0                   "/bin/prometheus --c…"    2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:9090->9090/tcp                           ms-prometheus
```

mysql端口设置的3307

**Comment by youliyuan-fit2cloud** [comment]
> > 
> 
> ```
> CONTAINER ID   IMAGE                                                                             COMMAND                    CREATED         STATUS                             PORTS                                            NAMES
> 92ab35084a72   registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.33                         "docker-entrypoint.s…"    3 minutes ago   Up 3 minutes (healthy)             33060/tcp, 0.0.0.0:3307->3306/tcp                mysql
> 7eb18b06110c   registry.cn-qingdao.aliyuncs.com/metersphere/system-setting:v2.10.2-lts           "/deployments/run-ja…"    5 days ago      Up 3 seconds (health: starting)                                                     system-setting
> 49383e481461   registry.cn-qingdao.aliyuncs.com/metersphere/gateway:v2.10.2-lts                  "/deployments/run-ja…"    5 days ago      Up 16 seconds (health: starting)   0.0.0.0:8081->8000/tcp                           gateway
> ce583dd721a1   registry.cn-qingdao.aliyuncs.com/metersphere/data-streaming:v2.10.2-lts           "/deployments/run-ja…"    5 days ago      Restarting (1) 13 seconds ago                                                       ms-data-streaming
> 12630fc7da32   registry.cn-qingdao.aliyuncs.com/metersphere/eureka:v2.10.2-lts                   "/deployments/run-ja…"    5 days ago      Up 5 minutes (healthy)                                                              eureka
> c339afeb2ae3   registry.cn-qingdao.aliyuncs.com/metersphere/redis:6.2.6                          "docker-entrypoint.s…"    5 days ago      Up 5 minutes (healthy)             0.0.0.0:6379->6379/tcp                           redis
> 6cbae0bcbc64   registry.cn-qingdao.aliyuncs.com/metersphere/kafka:3.4.0                          "/opt/bitnami/script…"    5 days ago      Up 5 minutes (healthy)             0.0.0.0:9092->9092/tcp                           kafka
> 967209ad2a53   registry.cn-qingdao.aliyuncs.com/metersphere/node-exporter:v1.5.0                 "/bin/node_exporter …"    2 weeks ago     Up 5 minutes (healthy)                                                              nodeexporter
> 946b459a17a0   registry.cn-qingdao.aliyuncs.com/metersphere/minio:RELEASE.2023-04-13T03-08-07Z   "/usr/bin/docker-ent…"    2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:9000-9001->9000-9001/tcp                 minio
> b7da8c831fd4   registry.cn-qingdao.aliyuncs.com/metersphere/node-controller:v2.10.2-lts          "sh -c 'sed -i \"s/:1…"   2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:8082->8082/tcp, 0.0.0.0:9100->9100/tcp   ms-node-controller
> f0058c88d655   registry.cn-qingdao.aliyuncs.com/metersphere/prometheus:v2.42.0                   "/bin/prometheus --c…"    2 weeks ago     Up 5 minutes (healthy)             0.0.0.0:9090->9090/tcp                           ms-prometheus
> ```
> 
> mysql端口设置的3307

你好，检查下MAC 电脑的防火墙和网络配置。

**Comment by EdwardCheck** [comment]
> 
```
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate

> Firewall is disabled. (State = 0)
```

防火墙是关闭的

**Comment by liuruibin** [comment]
MS_MYSQL_PORT改成3306试试呢

**Comment by EdwardCheck** [comment]
> MS_MYSQL_PORT改成3306试试呢

都试过了

**Comment by luty2018** [comment]
请问是否已解决问题，如果问题未解决可以重新打开issue
