### ISSUE TITLE
[BUG] 功能用例关联 tfs 需求后，访问tfs需求下关联的用例链接，只能到功能用例列表，未进入功能用例详情

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#25682]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

功能用例关联 tfs 需求后，访问tfs需求下关联的用例链接，只能到功能用例列表，未进入功能用例详情

### 重现步骤

1、功能用例关联tfs需求
2、在tfs下查看功能用例链接
![image](https://github.com/metersphere/metersphere/assets/103925124/4bde4206-c0f8-4a89-964f-f47d5731c3cc)
3、访问链接，只能到功能用例列表，未进入功能用例详情
![image](https://github.com/metersphere/metersphere/assets/103925124/43f3fc5b-1c02-475e-9ddd-416a24f9da22)

**Comment by liqiang-fit2cloud** [comment]
找凯波。
