### ISSUE TITLE
[自定义代码片段返回值是null]

### ISSUE THREAD

**Issue by xuzhenzhen** [metersphere/metersphere#25689]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/20080350/0842b1e6-5e3f-4849-8d23-fb53f146cde4)
![image](https://github.com/metersphere/metersphere/assets/20080350/5b270729-ab90-48c3-aff9-2f82629a2fb0)
我从平台下载此jar包，在ide里面引用jar包，同样的代码，是可以跑通的
![image](https://github.com/metersphere/metersphere/assets/20080350/0c1f7e4b-b287-442c-b59b-8c4f815be694)

**Comment by xuzhenzhen** [comment]
ide的jdk版本是17

**Comment by youliyuan-fit2cloud** [comment]
你好，这个脚本不是beanshell脚本吧。。。

**Comment by xuzhenzhen** [comment]
我这个脚本没有问题，过了一段时间又可以跑通了，我也很无奈，不知道是不是jar包更新的问题
