### ISSUE TITLE
[循环怎能获取到每次的下标]

### ISSUE THREAD

**Issue by xuzhenzhen** [metersphere/metersphere#25688]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/20080350/324be1e3-d1ed-4dc6-9d25-3f1d32ad1f2e)

**Comment by youliyuan-fit2cloud** [comment]
你好，请再看下我们的帮助文档，这里有很多用户手册，很多使用案例，描述的比较详细，感谢支持～
https://metersphere.io/docs/v2.x/user_manual/api_test/api_scenario/?h=%E5%BE%AA%E7%8E%AF#62-foreach
