### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by keybersan** [metersphere/metersphere#25696]
### MeterSphere 版本

1.12

### 联系方式

微信号：keybersan

### 请描述您的需求或者改进建议

io.metersphere.api.service.task.SerialScenarioExecTask#call注释掉这个方法时，
300个场景，2G内存可以运行完，执行  jMeterService.runLocal方法40G内存都不够用；
 if (request.getConfig() != null && StringUtils.isNotBlank(request.getConfig().getResourcePoolId())) {
                jMeterService.runTest(runModeDataDTO.getTestId(), runModeDataDTO.getReport().getId(), request.getRunMode(), request.getPlanScenarioId(), request.getConfig());
            } else {
                jMeterService.runLocal(runModeDataDTO.getReport().getId(), runModeDataDTO.getHashTree(), TriggerMode.BATCH.name().equals(request.getTriggerMode()) ? TriggerMode.BATCH.name() : request.getReportId(), request.getRunMode());
            }
分析后发现RunModeDataDTO占据很大的内容；
![image](https://github.com/metersphere/metersphere/assets/27944820/2698bdc2-033f-4e47-a6cc-4740ce0ad1f7)

测试20个场景dump出来的结果.

**Comment by fit2-zhao** [comment]
可以参照新版本，相关问题应该有处理过。

**Comment by keybersan** [comment]
请问修复记录是提交记录： 2108e9ef93534e8fe8abe9eae0a1512e880231c8
还是哪一个呢？
