### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xuzhenzhen** [metersphere/metersphere#25695]
### MeterSphere 版本

2.0.13

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/20080350/957b33da-80df-4882-b48d-5efc9a2032e5)
引入外置api，没有做代码的改动，跑的时候是异常的

### 重现步骤

同描述

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有 2.0.13这个版本，源码部署还是安装包部署，
可以尝试把 35行代码注释掉试试，感谢理解和支持 ～

**Comment by xuzhenzhen** [comment]
![image](https://github.com/metersphere/metersphere/assets/20080350/065a827f-8d8f-455b-8a4d-c182620b75a6)
注释掉也是不行的呢
