### ISSUE TITLE
[BUG]接口测试>>前后置sql：设置了环境和数据库，点击保存，关闭该页面，然后在打开此用例，发现设置的前后置sql相关数据库配置都是空。需要手动切换一下执行环境才可以。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#25708]
### MeterSphere 版本

V2.10.3-lts

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>前后置sql：设置了环境和数据库，点击保存，关闭该页面，然后在打开此用例，发现设置的前后置sql相关数据库配置都是空。需要手动切换一下执行环境才可以。

操作：
1、接口case添加前后置sql，配置相关数据库信息； 执行测试环境为test1，点击保存，测试通过。
2、关闭接口case页面
3、打开接口case，问题：之前配置的sql相关数据库信息都为空，需要手动切换执行环境：test1 到test2，然后在切换test1，此sql脚本里配置的数据库信息才会有。

期望：
再次打开接口case时，sql相关的数据库配置信息，根据case当前的执行环境，自动拉取。

### 重现步骤

[BUG]接口测试>>前后置sql：设置了环境和数据库，点击保存，关闭该页面，然后在打开此用例，发现设置的前后置sql相关数据库配置都是空。需要手动切换一下执行环境才可以。

操作：
1、接口case添加前后置sql，配置相关数据库信息； 执行测试环境为test1，点击保存，测试通过。
2、关闭接口case页面
3、打开接口case，问题：之前配置的sql相关数据库信息都为空，需要手动切换执行环境：test1 到test2，然后在切换test1，此sql脚本里配置的数据库信息才会有。

期望：
再次打开接口case时，sql相关的数据库配置信息，根据case当前的执行环境，自动拉取。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/b2522d81-1238-402b-b2c1-458fae143676)

![image](https://github.com/metersphere/metersphere/assets/78218624/61c373b7-830c-4c87-a26c-84f44894ea63)

**Comment by huangxine** [comment]
![image](https://github.com/metersphere/metersphere/assets/78218624/335b0eec-9d76-4971-8942-2cc021202e79)

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.4-lts无该问题，待发布后可升级尝试。
