### ISSUE TITLE
[BUG]定时同步缺陷系统有错误信息无法正常同步，但是手动同步缺陷是没有问题的。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#25706]
### MeterSphere 版本

V2.10.3-lts

### 使用外置数据库

否

### 问题描述

ms设置集成jira，缺陷定时同步日志有错误。手动触发同步是没有问题的，就是定时同步不行。
缺陷定时同步里设置了同步的条件，详情见下图

### 重现步骤

ms设置集成jira，缺陷定时同步日志有错误。手动触发同步是没有问题的，就是定时同步不行。
缺陷定时同步里设置了同步的条件，详情见下图

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/02fc73f2-ae6a-47cf-a78c-150d8fe3b0a2)
![image](https://github.com/metersphere/metersphere/assets/78218624/2fa87b10-436d-45fd-86b4-410aeace4aef)
[error.log](https://github.com/metersphere/metersphere/files/12093686/error.log)

**Comment by huangxine** [comment]
补充：
1）jira版本：v8.12.0#812001-sha1:d5099a0
2）jira插件也是用的最新版本的

**Comment by 13290445582** [comment]
您好，在最新环境未复现该问题，建议您升级至最新环境，该问题必现吗？
1.请问您使用的是jira缺陷模版还是在ms内配置的jira模版
2.模版上都配置了哪些字段，同步时缺陷有特殊数据吗
3.可以提供下服务器的实时日志，tail -f info.log看看报错信息

**Comment by huangxine** [comment]
> 您好，在最新环境未复现该问题，建议您升级至最新环境，该问题必现吗？ 1.请问您使用的是jira缺陷模版还是在ms内配置的jira模版 2.模版上都配置了哪些字段，同步时缺陷有特殊数据吗 3.可以提供下服务器的实时日志，tail -f info.log看看报错信息

1、缺陷模板应该没有问题，否则手动同步缺陷也会不成功
2、在附件里提供了完整的错误日志文件还不够吗？你这里的【提供下服务器的实时日志，tail -f info.log……】这个是什么意思？是提供“定时同步”的实时日志吗？难道还需要客户在0点的时候盯着系统给弄日志？如果是提供现在系统的实时日志，里面也没有“定时同步”相关的信息，对你检查这个问题有帮助吗？

**Comment by 13290445582** [comment]
经过沟通与排查，用户环境未使用最新插件，已更新插件。
