### ISSUE TITLE
未来是否支持 JSONPath 提取参数支持 Json 数组结构呢？

### ISSUE THREAD

**Issue by jia9iZhang** [metersphere/metersphere#25707]
### 请描述您的问题

最近在使用MeterSphere 时，使用JSONPath提取参数时，遇到“JSONPath 提取参数不支持解析JSON数组”提示。
未来是否支持 JSONPath 提取参数支持 Json 数组结构呢？

**Comment by luty2018** [comment]
你好， 推荐JSONPath提取目前确实不支持。
建议你这边先手写表达式来解决。
![image](https://github.com/metersphere/metersphere/assets/36292514/89256da8-8e06-40a8-9725-28ebb7bd97cf)

**Comment by jia9iZhang** [comment]
好的哈
