### ISSUE TITLE
[BUG]测试计划关联场景，场景中引用了case, case 修改，测试计划执行未同步更新

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25703]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

测试计划关联场景，场景中引用了case, case 修改，测试计划执行未同步更新。

### 重现步骤

1. 场景中引用 case 
![image](https://github.com/metersphere/metersphere/assets/103627487/67c026db-f43f-4fdd-9796-69a054550fc3)
2.测试计划关联场景
![image](https://github.com/metersphere/metersphere/assets/103627487/7d9a7a5c-dc4e-48d3-95a5-a3f93eaaef22)
3. case 中复制后置脚本第一个脚本，调整脚本顺序到最后一个，修改脚本内容
![image](https://github.com/metersphere/metersphere/assets/103627487/043ea9c6-c77f-4cf2-a8ad-00e3eed58788)
![image](https://github.com/metersphere/metersphere/assets/103627487/15b91b75-c7cd-4d52-949c-d2e75284791b)
4. 执行测试计划，后置脚本打印的值是乱的，还没有打印复制8
![image](https://github.com/metersphere/metersphere/assets/103627487/bd9d251b-942c-4c2c-b08a-0d99bf972d30)
5. 测试计划报告中跳转到场景中，后置操作多了一个，调试打印结果顺序是不对的，点击场景内的同步后，还是多一个
点击保存，再点击同步才刷新过来
![image](https://github.com/metersphere/metersphere/assets/103627487/312dbde4-3fcc-448b-a076-e95d78a075f5)
![image](https://github.com/metersphere/metersphere/assets/103627487/0eb9bdb2-42d5-45f4-9461-9ac5e49451e7)

### 期待的正确结果

测试计划关联场景，场景中引用了case, case 修改后置操作，测试计划执行能同步更新

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。
