### ISSUE TITLE
[BUG]接口测试场景用例都自定义了ID，但在测试跟踪-功能用例下去关联场景用例时，显示的ID还是默认的

### ISSUE THREAD

**Issue by JoyceQ2022** [metersphere/metersphere#25700]
### 联系方式

qiao.jing.joyce@vertiv.com

### MeterSphere 版本

v1.20.19-lts-a80199cf

### 使用外置数据库

否

### 问题描述

在项目设置-应用管理-接口测试中，允许场景自定义ID打开，在接口测试-接口自动化中场景用例的ID已经变化，但在测试跟踪-功能用例下去关联场景用例的时候,，ID还是显示的默认ID，由于默认ID不允许编辑，导致在做测试计划的时候，执行顺序会按照默认ID执行，而不能按照设计的ID顺序要求去执行，会导致计划失败。

### 重现步骤

1.项目设置-应用管理-接口测试中，允许场景自定义ID打开
2.用户自定义场景用例ID
3.测试跟踪-功能用例下去关联场景用例，显示的ID依然是默认ID。
4.制定测试计划时，执行顺序按默认ID顺序排序，导致对有顺序要求的场景用例失败。

### 期待的正确结果

1.要么可以允许编辑默认ID
2.要么将关联测试时，关联场景用例的ID也使用用户自定义的ID

### 附加信息

![Inked2023-07-19 152548](https://github.com/metersphere/metersphere/assets/116712473/fdc0e99a-ccb6-498b-9fd3-87d6477b387b)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题计划在后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.5-lts 版本已修复该问题，建议升级一下。
