### ISSUE TITLE
[BUG]在接口自动化界面下，编辑某个场景，在场景下的接口内添加多个参数提取或者断言脚本后，只要删除其中某一个步骤，整个界面会收缩，原来编辑的内容就找不到了

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2570]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
   V1.9.1

**Bug 描述**
简要描述您碰到的问题
在接口自动化界面下，编辑某个场景,在场景下的接口内添加多个参数提取或者断言脚本后，只要删除其中某一个步骤，整个界面会收缩，原来编辑的内容就找不到了

**Bug 重现步骤**
1.  编辑接口自动化下的某个场景
2. 在场景下添加多个断言或者其他步骤
3. 删除其中某一个步骤
4. 整个页面收缩，原来编辑的内容找不到了

**期待的正确结果**
正确情况下应该是什么样的？

 删除其中某一个步骤， 被删除的那一行消失，仍然可以手动编辑而不是整个页面收缩回去

**Comment by zyyfit** [comment]
您好，1.10.0版本已修复这个问题，请升级后查看
