### ISSUE TITLE
[FEATURE] 测试跟踪-用例模板下载，备注字段太靠前，影响使用

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25710]
### MeterSphere 版本

2.10.3-lts

### 请描述您的需求或者改进建议

常见写用例字段是id，模块，用例名称，前置条件，操作步骤，预期结果这样

建议把备注字段挪后面一点，使用体验不太好
![image](https://github.com/metersphere/metersphere/assets/43202800/8b582bf4-4f80-402c-8a01-a36c0eaf7602)

### 请描述你建议的实现方案

建议把模板 备注字段挪后面一点

**Comment by luty2018** [comment]
感谢建议 暂维持现状
