### ISSUE TITLE
[BUG] metersphere/jmeter-master镜像中引用 jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar ，存在fastjson 版本 < 1.2.80 反序列化漏洞

### ISSUE THREAD

**Issue by wangzd777** [metersphere/metersphere#25719]
### 联系方式

wangzd-e@glodon.com

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/120180679/05948e1d-b6b2-4a9f-a3b9-530ad3e8eef3)
图示版本 jmeter镜像依赖  jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar ，该jar中使用了 1.2.70 版本的fastjson。此版本存在 反序列化漏洞。在最新版本 的 metersphere/jmeter-master 镜像中 仍然存在此问题
![image](https://github.com/metersphere/metersphere/assets/120180679/32bb2397-329c-4fe4-b712-f16e80f92582)

### 重现步骤

如问题描述

**Comment by wangzd777** [comment]
![image](https://github.com/metersphere/metersphere/assets/120180679/98efaa3e-3932-4848-8bc8-007d8c203dfb)
fastjson 版本如图

**Comment by fit2-zhao** [comment]
感谢您的提醒，JMeter最新镜像已经升级。
