### ISSUE TITLE
[FEATURE]系统管理员提供统一组织下多个空间多个项目的整体情况面板，分别以空间，项目和人为维度统计【测试用例，接口用例，测试计划，bug数量】

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2571]
**请描述您的需求或者改进建议.**
系统管理员提供统一组织下多个空间多个项目的整体情况面板，分别以空间，项目和人为维度统计【测试用例，接口用例，测试计划，bug数量】

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
这个企业版后面会支持
