### ISSUE TITLE
[BUG]接口测试时，使用推荐jsonpath断言时，弹窗中的内容被遮挡

### ISSUE THREAD

**Issue by wanhx829** [metersphere/metersphere#25721]
### 联系方式

wanhx1324@163.com

### MeterSphere 版本

v2.10.4-lts-6a2bf297

### 使用外置数据库

否

### 问题描述

![问题333](https://github.com/metersphere/metersphere/assets/52766648/c5fc3cd7-9da7-4835-96ae-c80a9a54e80d)
使用推荐jsonpath进行断言或提取参数

### 重现步骤

响应的内容较长时，使用推荐jsonpath进行断言或提取参数

### 期待的正确结果

正常显示

**Comment by zrfit** [comment]
您好，感谢反馈！用mac和windows均未复现该问题。
1、终端是mac还是windows？
2、浏览器和版本分别是什么？

**Comment by wanhx829** [comment]
windows版本使用Google浏览器（114.0.5735.199）
重现步骤：接口自动化场景用例，设置多个步骤

**Comment by zrfit** [comment]
经沟通，是被遮挡，可以下拉滚动，已复现，计划v2.10.5-lts优化。
