### ISSUE TITLE
[BUG]接口测试对空列表断言不生效（已经升级最新版本）

### ISSUE THREAD

**Issue by wanhx829** [metersphere/metersphere#25720]
### 联系方式

wanhx1324@163.com

### MeterSphere 版本

v2.10.4-lts-6a2bf297

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/52766648/26d73c5d-0735-4018-9437-86ef4fd5e86c)
升级到v2.10.4-lts-6a2bf297版本，接口测试时，对列表进行断言，断言不正确

### 重现步骤

对列表进行断言

### 期待的正确结果

正常断言

**Comment by zrfit** [comment]
您好，感谢反馈！断言条件是正则匹配吗？如果是正则匹配[]则会失败，改为等于则可以。

**Comment by wanhx829** [comment]
是的，改为等于[]是可以的，但正则匹配“ \ [  \ ] ”怎么不行呢？  我在之前版本都是这样设置的，是可以断言的
![image](https://github.com/metersphere/metersphere/assets/52766648/e5aadf87-1bd4-4bae-96e4-c4a2eff51308)

还有另外一个问题，如果列表中存在内容，断言条件改为等于也是无法断言的
![image](https://github.com/metersphere/metersphere/assets/52766648/9de8ab5d-69cf-444d-aa82-c2861093cf55)
