### ISSUE TITLE
[BUG]【接口测试】接口用例页面点击保存，出现遮罩层尺寸不对。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25729]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

1. 创建接口用例
2. 点击保存,出现等待的遮罩层尺寸大小不对。
<img width="1408" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/1e4568e1-2f37-44ce-903e-e602f907e9c8">

### 重现步骤

1. 创建接口用例
2. 点击保存,出现等待的遮罩层尺寸大小不对。

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
