### ISSUE TITLE
[BUG]功能用例预览可显示区域小

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25735]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

功能用例步骤描述较多时，功能用例预览可显示区域小，下面还有很大区域，还需要滑动滚动条，也不美观

### 重现步骤

1.功能用例多加点步骤，点击预览查看
![image](https://github.com/metersphere/metersphere/assets/103627487/751743c9-6627-48d8-9451-fb05aebb7cc4)
功能用例预览可显示区域小，下面还有很大区域，需要滑动滚动条，也不够美观
![image](https://github.com/metersphere/metersphere/assets/103627487/55663a59-8898-40a4-803d-46cc4f41ebf1)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本优化。

**Comment by 13290445582** [comment]
v2.10.5已优化
