### ISSUE TITLE
[QUESTION]服务重新部署，数据迁移后，文件管理中csv文件还在，但是内容为空。

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#25744]
### 请描述您的问题

服务重新部署，数据迁移后，文件管理中csv文件还在，但是内容为空：
![图片](https://github.com/metersphere/metersphere/assets/23067502/b5062524-6103-4af3-b74c-a998e63a4da7)
![图片](https://github.com/metersphere/metersphere/assets/23067502/7007260a-f5c1-40e9-af2b-3a16e2fc0427)

**Comment by luty2018** [comment]
感谢反馈，数据迁移需要同步将MinIO 挂载的目录/opt/metersphere/data 下面的附件。
我们也会将页面优化一下，这里可能误导了用户文件已经迁移过来了。

**Comment by xiaochongzi-ling** [comment]
迁移data文件后解决。
