### ISSUE TITLE
[FEATURE] 建议测试计划加锁定功能，防止测试计划里面的测试结果被误改

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#25740]
### MeterSphere 版本

v2.10.2-lts

### 请描述您的需求或者改进建议

当前测试计划的测试结果，可以随时被修改，希望加一个锁定的功能，不能被随便篡改
![image](https://github.com/metersphere/metersphere/assets/33934471/98ec8540-4f4f-4a64-ba29-99aac07d797a)

### 请描述你建议的实现方案

建议一个锁定的角色权限，只有解锁的人可以随意改，修改测试结果也有地方记录

**Comment by luty2018** [comment]
我们在v3版本会增加测试计划的执行记录， 可以记录每一次变更的操作人信息。暂时没有规划要加锁定功能。
