### ISSUE TITLE
[BUG] 系统设置-用户：excel导入用户提示名称不能超出64字符，改成名称刚好64 页面上再修改这个用户 提示字段在2-50

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25748]
### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

导入用户提示名称不能超出64字符，改成名称刚好64 页面上再修改这个用户
提示字段在2-50
![image](https://github.com/metersphere/metersphere/assets/43202800/791ef07f-3775-4009-9420-697992b06cf8)

### 重现步骤

 1、系统设置-用户：excel导入用户提示名称不能超出64字符，，改成名称刚好64 
2、页面上再修改这个用户 提示字段在2-50 

字符长度限制不一致

### 期待的正确结果

限制一致

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
