### ISSUE TITLE
[FEATURE] getApiScenarioEnv不要限制只有 HTTPSamplerProxy/JDBCSampler/TCPSampler才能用环境变量

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2574]
**请描述您的需求或者改进建议.**

getApiScenarioEnv不要限制只有 HTTPSamplerProxy才能用环境变量
万一我测试就是自定义脚本+断言岂不是没办法使用环境变量？

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
没太明白您的需求，能详细描述下吗

**Comment by guhan121** [comment]
如果测试场景只有自定义脚本是没法选择环境的；你测试一下就知道了
