### ISSUE TITLE
[BUG]导入用例如果xmind中没有设置优先级导入后默认固定为P0，导入也应从默认模板中获取默认值

### ISSUE THREAD

**Issue by FangLiao12** [metersphere/metersphere#25753]
### 联系方式

13550384499@163.com

### MeterSphere 版本

v2.10.3-lts-ac6522a2

### 使用外置数据库

否

### 问题描述

在【项目设置】->【模版管理】->【用例模版】的默认模板中设置用例等级是P2，但导入用例如果没有设置优先级则导入后默认仍为P0，导入应也从默认模板中获取默认值

### 重现步骤

1. 在【项目设置】->【模版管理】->【用例模版】的默认模板中设置用例等级是P2
2. 导入xmind格式的用例，在xmind文档中未设置优先级
3. 导入后默认仍为P0

### 期待的正确结果

导入应也从默认模板中获取默认值，在xmind中没有指定优先级的情况下应默认为P2

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
