### ISSUE TITLE
[FEATURE] 场景编辑在运行的时候取消自动保存

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#2575]
**请描述您的需求或者改进建议.**

比如领导就是想跑一下用例而已；结果点一下的调试 用例就的创建人就变成领导了；并且最后的更新时间也变成最后一次执行调试的事件。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
我们系统还没有操作人这个字段，1.10版本会加
