### ISSUE TITLE
[BUG]修改UI并发线程数重启服务之后 查看 http://ip:4444 页面 session 数量未发生变化

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25755]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

修改数据表system_parameter 中的base.grid.concurrency 的值为2，批量执行大于4个的UI 用例，在 http://ip:4444 页面 session 数量未发生变化

### 重现步骤

1、修改数据表system_parameter 中的base.grid.concurrency 的值为2
2、重启服务器
3、批量执行大于4个的UI 用例
4、打开 http://ip:4444 页面 session 数量是4

### 期待的正确结果

调整base.grid.concurrency 的值为2之后，打开 http://ip:4444 页面 session 数量是为2

**Comment by xueqidove** [comment]
补充下背景：
UI 测试用例场景（50个 UI场景，共计600多个步骤）在 UI 测试模块调试测试均没问题，但是集成关联到测试跟踪模块中的测试计划后执行同样的UI测试场景（设置为并行执行且不勾选性能模式），失败率可达30%。失败现象集中为下拉框和弹窗加载缓慢。
基于以上与技术人员沟通，建议修改上述参数，但修改后并不生效。

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。

**Comment by sss903065212** [comment]
这个修复是指这个参数修改生效的修复，还是性能提升的修复

**Comment by zrfit** [comment]
参数修改生效。
