### ISSUE TITLE
[BUG] 步骤较多时，点击步骤的输出，页面会自动滚动

### ISSUE THREAD

**Issue by hao1032** [metersphere/metersphere#25757]
### 联系方式

MS开源用户支持: 合肥-左岸-v2.10.4-lts-a23f75d9

### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

步骤较多时，点击步骤的输出，页面会自动滚动

### 重现步骤

详情见附件视频

### 期待的正确结果

页面不会自动滚动

**Comment by hao1032** [comment]
[屏幕录制2023-07-21 15.48.21.zip](https://github.com/metersphere/metersphere/files/12122133/2023-07-21.15.48.21.zip)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
