### ISSUE TITLE
[QUESTION]【测试计划】->【功能测试用例】选择脑图形式，无法编辑用例，且在页面新增用例保存后实际未生成用例

### ISSUE THREAD

**Issue by FangLiao12** [metersphere/metersphere#25765]
### 请描述您的问题

功能路径：【测试计划】->【功能测试用例】，选择脑图形式

问题1：无法在脑图页面编辑现有用例

问题2：在页面新增用例保存后实际未生成用例

**Comment by Hyyfit** [comment]
测试计划仅支持脑图模式执行用例，不支持修改和新建用例
