### ISSUE TITLE
[BUG]UI测试断言勾选框是勾选的状态，断言失败

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25764]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

UI测试断言勾选框是勾选的状态，勾选框已经勾选成功，断言失败

### 重现步骤

1. 断言勾选框是否勾选成功
![image](https://github.com/metersphere/metersphere/assets/103627487/3ccd6a48-d7c4-4bdb-9301-7a659d1cfdd9)
![image](https://github.com/metersphere/metersphere/assets/103627487/8ab0723d-c398-4a8c-b581-815b99fc7ccd)
2.运行后报告中已经勾选成功
![image](https://github.com/metersphere/metersphere/assets/103627487/1e25f505-7edc-493b-8cd1-4d2dfc097c51)
断言显示
![image](https://github.com/metersphere/metersphere/assets/103627487/e7d722c6-9824-4525-8f91-e8f588adebc6)

**Comment by zrfit** [comment]
您好，感谢反馈！复选框是否被选中，是根据type="checkbox"这个类型的input返回的isSelect 这个属性去校验的，因此，断言元素是否被选中的元素路径必须要定位到input 这一层才可以。
![image](https://github.com/metersphere/metersphere/assets/99731894/21c6b475-0a22-4774-bdad-10b43c2cd429)
<img width="1326" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/51fb6259-5dbb-442b-9ca6-e8e40466dc36">
