### ISSUE TITLE
[BUG] 测试用例评审时，脑图模式无法添加“评论”。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#25769]
### 联系方式

975539382@qq.com

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

脑图模式下，评审用例无法添加评论。

### 重现步骤

1. 如下图：在评审用例时，直接添加一条记录：
![image](https://github.com/metersphere/metersphere/assets/44999044/48d5f01f-fcd5-4508-be9f-cf5256c49fc7)
2. 切换成列表查看时，评论内容为空（仅展示我添加过评论）：
![image](https://github.com/metersphere/metersphere/assets/44999044/d4840480-1aca-42f1-902b-79c04edca9bf)

**另：脑图模式下，点击不通过，也不会像列表一样弹出评论的窗口让我必填。**

### 期待的正确结果

希望脑图模式下评审时，评论可以正常填写。

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
您好，经过与产品确认，脑图没有支持评论功能，暂不支持该功能，感谢您的理解与支持。
