### ISSUE TITLE
关于测试计划的一些建议

### ISSUE THREAD

**Issue by junge4505** [metersphere/metersphere#25768]
### MeterSphere 版本

v2.10.2-lts-b028f4ea

### 联系方式

junge4505@163.com

### 请描述您的需求或者改进建议

场景：
一个测试迭代分多个测试阶段或测试周期，冒烟测试，一轮测试，回归测试，上线测试，不同阶段可能会有相同的用例需要执行，只是涉及的阶段或环境不同，如回归测试在预发布环境，上线测试是生产环境。按照目前的设计，需要一个阶段创建一个测试计划，后续测试结束后，出具测试报告需要合并所有阶段的测试报告。使用起来不太方便。

### 请描述你建议的实现方案

两种方式均可考虑：
1、一个测试计划下面支持测试周期、测试阶段或子计划，测试计划挂载当前版本所有需要执行的用例，再将用例分配到不同的测试周期或测试阶段，最后一个版本出具一个测试报告。
2、不改变现有的结构，增加一个测试计划组的概念，将现有的测试计划合并到一个组进行跟踪，并出具测试报告。

### 附加信息

无

**Comment by luty2018** [comment]
已规划到v3.0

**Comment by luty2018** [comment]
已支持， 可以升级使用。
