### ISSUE TITLE
[BUG]2.4.0版本升级到2.10.4版本，出现编辑用例弹出错误提示，提示内容：“服务调用出错[serviceId:performance,url:/performance/getLoadCaseByIds],错误信息:403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_PERFORMANCE_TEST:READ]","data":null}"”

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#25767]
### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

2.4.0版本升级到2.10.4版本，出现编辑用例弹出错误提示，提示内容：“服务调用出错[serviceId:performance,url:/performance/getLoadCaseByIds],错误信息:403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_PERFORMANCE_TEST:READ]","data":null}"”

### 重现步骤

1. 系统升级到2.10.4
2. 进入功能用例，随意找一条用例进行查看，单击查看用例后，出现错误提示：“服务调用出错[serviceId:performance,url:/performance/getLoadCaseByIds],错误信息:403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_PERFORMANCE_TEST:READ]","data":null}"””
3. 在用例编辑页面，单击【关联测试用例】必现错误提示。

### 期待的正确结果

无错误提示

### 相关日志输出

```shell
2023-07-23 09:56:02,210 [qtp1919292887-415] ERROR io.metersphere.service.MicroService 177 - Method[postForResultHolder][服务调用出错[serviceId:performance,url:/performance/getLoadCaseByIds],错误信息:403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_PERFORMANCE_TEST:READ]","data":null}"]
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_PERFORMANCE_TEST:READ]","data":null}"
```

### 附加信息

![企业微信截图_16900787551373](https://github.com/metersphere/metersphere/assets/6109912/236842ed-f484-4275-8182-940ba452194c)

**Comment by 13290445582** [comment]
您好，根据您提供的日志显示，缺少性能测试的查询权限。请将系统设置-用户组与权限-设置权限-性能测试-查询测试勾选保存。尝试下可以解决您的问题吗？

**Comment by ChangqiaoWang** [comment]
系统设置-用户组与权限-设置权限-性能测试-查询测试勾选保存 ，问题解决

**Comment by 13290445582** [comment]
您好，该问题已解决，关闭issue，后续有问题请重新提issue，感谢理解与支持。
