### ISSUE TITLE
[BUG]与JIRA平台对接，采用系统JIRA默认模板，报告人和经办人通过搜索的方式搜索出来的人，用鼠标单击不会被选中，报告人下拉列表框仍然是空的

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#25776]
### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

与JIRA平台对接，采用系统JIRA默认模板，报告人和经办人通过搜索的方式搜索出来的人，用鼠标单击不会被选中，报告人下拉列表框仍然是空的

### 重现步骤

1. 创建项目与JIRA平台对接，采用JIRA默认BUG模板
2. 创建的新的BUG，报告人下拉表框通过搜索的方式搜索出来的项，不能通过鼠标单击的方式选中，可以通过键盘回车键的方式选中到报告人下拉列表框中；

### 期待的正确结果

报告人可以通过鼠标的方式选中搜索出来的项；

**Comment by youliyuan-fit2cloud** [comment]
v210.5-lts中已修复，建议升级一下吧。
