### ISSUE TITLE
[BUG] 测试计划点击执行，报告状态变为"Completed" ，点进报告详情，任务还没有执行完，并且任务是在不断执行中，直到执行完成。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25785]
### MeterSphere 版本

v2.10.4-lts,v2.10.3-lts

### 使用外置数据库

否

### 问题描述

1. 点击执行测试计划。
2. 查看报告状态为”Completed“，但点击进入报告详情之后任务还没有执行完成，并且在持续执行中。
3. 当都执行完成之后，报告列表的通过率会改变。

https://github.com/metersphere/metersphere/assets/33945037/9ce7a575-86d0-445e-8992-b84cf3b5be1a

https://github.com/metersphere/metersphere/assets/33945037/6454a0f6-a871-40f6-ac8b-b2a87c1ea790

### 重现步骤

同上

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.6-lts修复。
