### ISSUE TITLE
[FEATURE] 接口自动化场景，等待控制器等待顺序需求

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#25791]
### MeterSphere 版本

V2.10.x-lts

### 请描述您的需求或者改进建议

MS使用过程中时遇到一个场景，需要在前一个接口执行完毕后，等待2分钟，等待结束后，再执行下一个接口的前置脚本以及后续的接口内容。按照目前MS的前置等待控制器的逻辑，它每次都会先执行前置脚本，再执行等待控制器。
当前的需求就是：无论怎么调整前置等待控制器的顺序，前置脚本都没办法先等待两分钟再执行前置脚本，能否支持对前置操作按顺序执行，或者有其他方案能够支持上述的场景。

### 请描述你建议的实现方案

方案1：
MS的“前置操作”支持顺序执行，即如下图：
![image](https://github.com/metersphere/metersphere/assets/47737772/2d44aa69-90b6-4c67-97d5-f0535ce40624)

方案2：
是否有其他方式可以实现上述的需求场景，做到前一个接口执行完毕后，等待一段时间，再执行前置脚本。

**Comment by zhangzhaox** [comment]
方案2：
是否有其他方式可以实现上述的需求场景，做到前一个接口执行完毕后，等待一段时间，再执行前置脚本。   按照你这个描述 是后置脚本  如果你的这个API请求之前  还有别的请求  你这个延迟2000毫秒可放在 上一个请求的后置里面

**Comment by blooze123** [comment]
![image](https://github.com/metersphere/metersphere/assets/47737772/2f7fb167-d24b-401d-8f58-12575316af95)

**Comment by luty2018** [comment]
你可以在下一步的前置操作里面加等待时间， 可以覆盖这个场景。

**Comment by blooze123** [comment]
谢谢，已经解决这个问题了，通过前置脚本直接添加java线程sleep脚本解决这个问题了：
Thread.currentThread().sleep(1000*n);   (n为秒数)
