### ISSUE TITLE
[BUG]添加的测试用例id重复

### ISSUE THREAD

**Issue by zhanggefei** [metersphere/metersphere#2579]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.8.2

**Bug 描述**
创建的用例id重复
![1WechatIMG1553](https://user-images.githubusercontent.com/37612532/117459607-28ca0380-af7e-11eb-88c3-ef57c06d1238.jpeg)

**Bug 重现步骤**
正常添加用例

**Comment by xulinde** [comment]
什么操作会出现这个情况呢

**Comment by zhanggefei** [comment]
一般这么用：先在MS上写一条用例，然后导出，按照这个导出模板继续写别的用例，然后把导出的excel里的id一列的值都删掉，然后再上传到ms上。

**Comment by xulinde** [comment]
1.10.4已修复
