### ISSUE TITLE
【接口测试】希望能加上像postman一样的，勾选或者取消勾选某个参数

### ISSUE THREAD

**Issue by zhangjmjh** [metersphere/metersphere#258]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/53334634/90615476-c5a50f00-e23e-11ea-906a-cdcfd1b9a113.png)

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> ![image](https://user-images.githubusercontent.com/53334634/90615476-c5a50f00-e23e-11ea-906a-cdcfd1b9a113.png)
> 
> **请描述你建议的实现方案**

1.3版本

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已实现该功能
