### ISSUE TITLE
[FEATURE]【测试计划】->【功能测试用例】选择脑图形式，全部展开后用例顺序能否和列表保持一致

### ISSUE THREAD

**Issue by FangLiao12** [metersphere/metersphere#25809]
### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 联系方式

13550384499@163.com

### 请描述您的需求或者改进建议

【操作步骤】
1. 通过xmind导入用例，导入后排序和导入的xmind中一致
2. 在测试计划中关联用例，关联后在列表查看排序和导入的xmind中一致

【实际结果】
再选择脑图形式执行用例，但排序混乱，和导入的xmind中不一致

【建议】
排序和导入的xmind中一致

**Comment by luty2018** [comment]
关联用例时是根据关联的先后顺序进行排序的
