### ISSUE TITLE
[QUESTION]data文件迁移咨询

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#25804]
### 请描述您的问题

您好，最近进行了服务迁移，以下是新旧服务data目录文件情况，请教下需要迁移哪些文件，具体操作步骤是什么，望解答：
![图片](https://github.com/metersphere/metersphere/assets/23067502/eb3ff0df-0c8e-49e4-a2f6-440a57ed795a)

**Comment by 2lipan** [comment]
MeterSphere的使用数据默认存放在/opt/metersphere/data目录下，除kafka、redis、prometheus、zookeeper外，data下的其他目录都需要迁移，因为这些目录存放的是持久化数据，需要迁移，而kafka、redis等服务存放的是临时数据，没有迁移的必要。对于mysql目录也是可以不用迁移，可以mysqldump备份sql，然后在新环境执行sql恢复数据。你可以先将旧环境升到与新环境同一版本，然后再使用mysqldump备份sql，在新环境上执行sql，然后再迁移目录。详细可参考该教程 https://kb.fit2cloud.com/?p=9a46f075-5cfe-46de-81f8-ab5278699697
