### ISSUE TITLE
[FEATURE]自定义字段，能够在测试用例列表显示

### ISSUE THREAD

**Issue by zhanggefei** [metersphere/metersphere#2580]
**请描述您的需求或者改进建议.**
在用例模版里添加的自定义字段，期望能够在测试用例列表能配置显示，直接在列表显示出来。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
自定义字段是会在测试用例显示的，您项目关联用例模版了吗

**Comment by wangzhen-fit2cloud** [comment]
最新的版本可以在列表中展示自定义字段了，排序暂未支持。
