### ISSUE TITLE
[BUG]接口case请求体json格式打开JSON-SCHEMA后浏览器崩溃

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25825]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

1.接口case请求体json格式打开JSON-SCHEMA后页面无响应，浏览器崩溃。
![image](https://github.com/metersphere/metersphere/assets/55130444/48c4afca-02df-4877-8f2a-479aa7c42e2e)

### 重现步骤

1.新增接口case
2.请求体选择json格式，增加请求内容。
3.增加完之后点击打开JSON-SCHEMA，页面崩溃
![image](https://github.com/metersphere/metersphere/assets/55130444/60f14c9c-4851-42c7-a47b-49a64e375aee)

**Comment by 13290445582** [comment]
感谢您的反馈，计划后续版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复

**Comment by kaijie-yu** [comment]
v2.10.5lts已验证修复。
