### ISSUE TITLE
[BUG]接口case打开JSON-SCHEMA，增加json请求体参数描述，切换后增加的描述内容消失

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#25838]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

接口case打开JSON-SCHEMA，增加json请求体参数描述，切换后增加的描述内容消失

### 重现步骤

1.case里请求体打开JSON-SCHEMA，勾选设置里的描述，增加描述内容，保存。
![image](https://github.com/metersphere/metersphere/assets/55130444/25b3330e-91f6-4265-8531-7301aee143fb)
2.然后关闭JSON-SCHEMA，再打开JSON-SCHEMA，增加的描述内容没有显示。
![image](https://github.com/metersphere/metersphere/assets/55130444/75a423bf-d954-4e32-a7fa-dfdad5a55249)

### 期待的正确结果

打开或者关闭JSON-SCHEMA，不应该影响到原有的描述内容

**Comment by zrfit** [comment]
您好，感谢反馈！计划v3优化。

**Comment by luty2018** [comment]
这个描述是从接口定义带过来的， 要增加参数的描述， 要到接口定义页面
