### ISSUE TITLE
[BUG] 权限问题-功能用例查看需要性能测试查看权限,不然报错

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25831]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

是

### 问题描述

如题：
<img width="1063" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/86ab8a12-980a-43b6-ba39-e5fb0361927b">

### 重现步骤

1、对一个只有项目成员和工作空间成员权限的用户，修改项目成员的权限 取消他的性能测试的权限
<img width="899" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/ca22e2f6-493b-46d2-ad43-615a2d62bd25">
2、打开测试跟踪的功能用例，找一个功能用例 点击查看
<img width="1063" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/e7d6548c-bf00-419c-a909-9f53bd240f74">
<img width="1027" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/c02e0efa-8e00-4d95-8a62-3d3a6e23290b">

### 期待的正确结果

和2.10.1LTS一样，不要报错，或者没有性能测试的权限，在功能用例的关联测试的地方就不要展示性能测试

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
