### ISSUE TITLE
脑图使用版本筛选后，左侧模块树的数量展示不会同步筛选

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#25832]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

切换到脑图模式，使用了版本筛选后，左侧模块树的数量展示不会同步筛选

### 重现步骤

1. 切换到脑图模式，使用版本筛选条件
2. 左侧模块树的数量展示不会同步筛选

### 期待的正确结果

希望左侧模块树的数量展示会同步筛选

### 相关日志输出

```shell
无
```

### 附加信息

![70d153eaba8e9720fa66ac33d3532ee](https://github.com/metersphere/metersphere/assets/50016789/3571048f-2bb6-4ba1-9c63-042224acda80)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
感谢您的反馈，尚不支持该功能，目前脑图会根据左侧模块树选中的模块，进行局部渲染，如果左侧模块树还需要根据版本进行筛选，此时脑图的渲染会受到影响，增加了页面的复杂度，暂时没有计划支持，感谢理解与支持。
