### ISSUE TITLE
[BUG] JsonPath 空数组 [] 断言问题 等于和正则匹配 都失败 

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25836]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

如题：
<img width="1302" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/32e53697-eb3f-4b94-85a0-cb0da3d4b9ec">

### 重现步骤

这个不需要重现步骤了吧
1、新建一个接口case 、添加一个mock、断言根据JsonPath
2、如图：
<img width="1278" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/7df2eff1-6d27-42f5-9a47-58099de92452">
<img width="644" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/26b484c5-2235-4fe9-87ef-508a577aedfd">
<img width="1055" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/2e5476c0-c172-46a1-ac86-2fc9ae5738e4">
<img width="1034" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/6f46d323-7a15-4527-90ee-365df24e00da">

### 期待的正确结果

不管 等于还是正则匹配当然是断言要成功了，正则匹配做不到起码等于要可以吧？

**Comment by zrfit** [comment]
您好，感谢反馈！同问题#25720，v2.10.5-lts修复。
