### ISSUE TITLE
[BUG] 修改系统 logo图标和系统名称后 刷新页面时会还是会一段时间显示默认的 MeterSphere logo 和名称

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25840]
### MeterSphere 版本

所有

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/40912189/159c0362-844a-4ea2-9513-c34f5a3a2d23

### 重现步骤

1、修改系统logo图片和名称
<img width="1086" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/34c2c7f6-260b-4589-ad2c-351f4002ce33">
2、点击刷新页面

https://github.com/metersphere/metersphere/assets/40912189/159c0362-844a-4ea2-9513-c34f5a3a2d23

### 期待的正确结果

1、希望做到替换是真的替换，而不是加载覆盖的替换，找个会写的前端改下吧
2、提供一个思路：默认logo 和文字 等信息 放到服务器上，替换的话就直接替换查找新的图片和文字 路径？

**Comment by liuruibin** [comment]
浏览器标签页上的图标favicon是加载后手动替换的，如果您很介意这里可以先将index.html里的图标替换成需要的，重新做包部署即可。这里就将这个issue关闭了

**Comment by sss903065212** [comment]
给老板演示功能的时候，加载页面不希望出现这个metersphere的图标favicon，希望能采纳这个提议

**Comment by sss903065212** [comment]
觉得这个地方是功能缺陷，认为既然提供替换系统logo功能，为什么还会有之前的metersphere的图标favicon加载出现

**Comment by sss903065212** [comment]
不觉得这个地方不合理吗？先将index.html里的图标替换成需要的，重新做包部署即可？？？？
不会做二次开发的

**Comment by sss903065212** [comment]
每次升级都重新打个包？

**Comment by fit2-zhao** [comment]
修改compose 文件挂载一个自定义的ico 覆盖 gateway 容器里的/app/static/favicon.ico 就能满足。

**Comment by liqiang-fit2cloud** [comment]
v2.10.5已修复。
