### ISSUE TITLE
[BUG]  接口请求体为 array 特殊格式时，预览和执行时为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#25844]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

接口请求体为 array 特殊格式时，预览和执行时为空

### 重现步骤

1、导入下面的metersphere-json格式的接口文件，接口请求体为 array 特殊格式
[Metersphere_Api_托管部管理人服务平台.zip](https://github.com/metersphere/metersphere/files/12158834/Metersphere_Api_.zip)
2、预览和执行时为空
![image](https://github.com/metersphere/metersphere/assets/103925124/1670dc27-69cc-48a6-9899-e52c0d0897d2)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
