### ISSUE TITLE
功能用例使用版本筛选条件，切换到脑图模式后，条件没有带过来，需要重新筛选

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#25848]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

功能用例使用版本筛选条件，切换到脑图模式后，条件没有带过来，需要重新筛选。

### 重现步骤

1. 功能用例使用版本筛选条件
2. 切换到脑图模式后，条件没有带过来，需要重新筛选

### 期待的正确结果

切换到脑图模式后，条件自动带过来，不需要再重新筛选

### 相关日志输出

```shell
无
```

### 附加信息

<img width="882" alt="3591343001d1b0f2f0398665c0e4159" src="https://github.com/metersphere/metersphere/assets/50016789/d28b9ebf-83ea-416b-9145-8629bc216d08">
![1690273895256](https://github.com/metersphere/metersphere/assets/50016789/db8bebcc-3c50-4d0f-ad70-682e0754292b)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.5版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.5已修复
