### ISSUE TITLE
[BUG]“推荐jsonpath断言”功能中，点击数组或对象生成的结果中数字变成了字符串

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25849]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

“推荐jsonpath断言”功能中，点击数组或对象生成的结果中数字变成了字符串

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103627487/a43b27d7-7614-46ee-86b4-7cf26070277d)
<img width="702" alt="02370c66353b5b148a92c10f812e29d" src="https://github.com/metersphere/metersphere/assets/103627487/44c2c5a4-30de-4646-b96e-c06eae07518c">

可以参考issues   #25109

**Comment by youliyuan-fit2cloud** [comment]
/
Duplicate of #25109
