### ISSUE TITLE
[BUG]【测试跟踪】导图模式，复制粘贴用例，保存不上

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#2585]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  测试跟踪，测试用例，导图模式
2. 复制粘贴用例，保存
3. 刷新页面，复制的用例没有保存成功

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/2316

**Comment by zyyfit** [comment]
1.10.2版本解决这个问题
