### ISSUE TITLE
[BUG]【接口自动化】全屏展示后，推荐 jsonpath 提取功能，不可用（提示：请先执行调试获取响应结果；实际已经执行了，还会提示）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2586]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
全屏展示后，推荐 jsonpath 提取功能，不可用（提示：请先执行调试获取响应结果；实际以及执行了，还会提示）

**Bug 重现步骤**
1.  接口自动化，全屏
2. 使用断言/参数提取组件，推荐 jsonpath 提取
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
弹出提取窗口
实际：提示“请先执行调试获取响应结果”

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/117524478-fb1da280-afef-11eb-87cd-24653c554cc8.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
您好，1.10.0版本已修复了这个问题，请升级到最新版使用
