### ISSUE TITLE
[BUG] 权限问题 接口测试添加CSV文件 需要项目设置的权限？

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25861]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/40912189/6de40d85-b26d-4f42-bfe1-0803e5c251be)

### 重现步骤

1、项目成员 的权限去掉项目设置的权限
2、在接口自动化添加场景变量选CSV文件
3、报错了

**Comment by zrfit** [comment]
您好，感谢反馈！场景变量是csv类型-添加文件-关联文件-是要去文件管理获取数据-用户对应权限建议开启项目设置-文件管理的查询权限。

**Comment by sss903065212** [comment]
明白了，现在权限控制比之前严格了对吗

**Comment by zrfit** [comment]
是的，权限控制现在划分的比较细。
