### ISSUE TITLE
[BUG] 正则断言不能识别^[]$

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25866]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

<img width="1079" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/227b81ab-5189-4a77-b593-fd346af37231">

### 重现步骤

1、写个mock 返回[]
2、测试选择mock环境
3、添加正则断言 ^[]$
4、
<img width="898" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/652f7ae4-35a7-4b7c-bf49-236c9d06a503">
5、执行调试，查看响应内容-断言

### 期待的正确结果

断言成功

**Comment by fit2-zhao** [comment]
可以试试加上转译： “^\\[\\]$”

**Comment by sss903065212** [comment]
<img width="1040" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/1c9961f2-bd65-4bae-838d-c6243b4435c0">

**Comment by sss903065212** [comment]
<img width="1024" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/289dfaa2-9c04-49c4-aae3-f0cfad869fa0">

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.5-lts修复。

**Comment by fit2-zhao** [comment]
您好，感谢反馈！同问题 #25720，v2.10.5-lts修复。

**Comment by sss903065212** [comment]
@fit2-zhao 不同的断言方式，这个是“正则” #25720 是“jsonPath” ,我不确定后台是不是用的同一个逻辑处理的
