### ISSUE TITLE
[QUESTION]node处理任务异常，未找到执行的jmx文件

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#25863]
### 请描述您的问题

![图片](https://github.com/metersphere/metersphere/assets/23067502/1fd21707-007c-4fba-a826-449ceb4ca8ca)

**Comment by luty2018** [comment]
什么版本

**Comment by xiaochongzi-ling** [comment]
以下是版本、install配置文件、使用的测试资源池信息：
版本：



install配置文件：

目前使用的测试资源池：





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]node处理任务异常，未找到执行的jmx文件 (Issue #25863)





 
什么版本

**Comment by xiaochongzi-ling** [comment]
以下为部分日志截图，多谢：
node-controller日志：












api-test:
















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "玲子"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午3:27
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [metersphere/metersphere] [QUESTION]node处理任务异常，未找到执行的jmx文件 (Issue #25863)



以下是版本、install配置文件、使用的测试资源池信息：
版本：



install配置文件：

目前使用的测试资源池：





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]node处理任务异常，未找到执行的jmx文件 (Issue #25863)





 
什么版本

**Comment by xiaochongzi-ling** [comment]
![图片](https://github.com/metersphere/metersphere/assets/23067502/aa93d023-5c5b-4abb-90a9-9613ce9f6d19)

**Comment by fit2-zhao** [comment]
![image](https://github.com/metersphere/metersphere/assets/70558837/715b96dd-dd9c-4b75-aee6-b47f8358b541)

1 检查日志中的链接是否能正常下载执行脚本
2 检查这个目录是否有读写权限

ps：如果 1 不通过再去 api-test 服务中把日志贴出来看看（可能没环境｜ 有特殊步骤）导致。
如果 2 不对加上权限就好了。

**Comment by guawali** [comment]
![Image](https://github.com/user-attachments/assets/a9488da3-7fd3-452c-9928-5c9b7ea5809e)

我也遇到了这个问题，偶发的
场景：在测试计划里面同时跑65个用例，且这些场景是并行的，场景之间互不干扰，执行完成后这一个场景用例报错。目前执行了约10次，只有一次报这个错误
PS：服务器资源当时被占用了很多，系统内存只剩下50m，不确定是否会有影响

metersphere版本：v2.10.0-lts-89acace0
@luty2018 @fit2-zhao  麻烦帮忙看下，谢谢 thanks
