### ISSUE TITLE
[BUG] 【测试跟踪-测试用例-脑图】复制用例后保存，原来的用例会被覆盖

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2587]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
复制用例后保存，原来的用例会被覆盖，预期新增一条用例

**Bug 重现步骤**
1.  测试跟踪-测试用例-脑图
2. 选中一条用例，复制
3. 保存
4. 

**期待的正确结果**
正确情况下应该是什么样的？
保存成功，原来的用例和复制的用例，同时存在
实际：原来的用例会被覆盖

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/117524545-58b1ef00-aff0-11eb-853b-0e06ccee113b.png)

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/2316

**Comment by zyyfit** [comment]
1.10.2版本解决这个问题
