### ISSUE TITLE
[BUG] v2.10.3-lts 接口自动化调试时 步骤中丢失了测试中的提示信息

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25873]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

V1.20.23LTS 接口自动化调试执行  执行的地方会显示测试中
<img width="1116" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/73020164-0b84-479e-a025-3f2234df8151">
V2.10.3LTS 接口自动化调试执行 执行的地方不再显示测试中
<img width="1065" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/3b08d516-c00d-458f-b2f7-756b56148c36">

### 重现步骤

1、新建一个场景
2、找一个返回较慢的请求（如github）
3、把第二个步骤复制几次
4、点击调试（观看第一个或者后续的步骤）
5、没有出现测试中的提示信息

### 期待的正确结果

V2.10.3LTS 相较于 V1.20.23LTS  在接口自动化这个地方是去掉了测试中的提示信息吗？
如果没有去掉那就是bug，希望展示测试中的提示信息 ，因为客户想直观的看到那个接口在测试中，比如if条件控制器，可以更好的知道是哪一个if在执行

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。
