### ISSUE TITLE
[BUG] 原api有case。api更新，接口参数少了一个，使用一键同步case功能：删除用例中无法与API文档对应的参数——实际没有删除少了的哪个参数

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25872]
### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

1原api有case。api更新，接口参数少了一个，
2、使用一键同步case功能：删除用例中无法与API文档对应的参数——实际没有删除少了的哪个参数

### 重现步骤

1原api有case。api更新，接口参数少了一个，
![image](https://github.com/metersphere/metersphere/assets/43202800/ce44e89b-aa25-4464-a4af-213e3a00846d)
![image](https://github.com/metersphere/metersphere/assets/43202800/5a451cf1-c1fe-418c-b74b-d406e9607131)

2、使用一键同步case功能：删除用例中无法与API文档对应的参数——实际没有删除少了的哪个参数

![image](https://github.com/metersphere/metersphere/assets/43202800/49efaf89-8d60-4af2-9067-c390528a0a86)

### 期待的正确结果

按照勾选去掉 多出来的参数

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.5-lts修复。
