### ISSUE TITLE
 [BUG] ${__lowercase(${__UUID},)}   jmeter的 这种函数在ms平台不能执行，在jmeter上面可以

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25878]
### MeterSphere 版本

2.10.1-lts

### 使用外置数据库

否

### 问题描述

${__lowercase(${__UUID},)}   jmeter的 这种函数在ms平台不能执行，在jmeter上面可以

![image](https://github.com/metersphere/metersphere/assets/43202800/880bf736-c44a-49b6-a895-43b8c1e90fb6)

### 重现步骤

${__lowercase(${__UUID},)}   jmeter的 这种函数在ms平台不能执行，在jmeter上面可以

### 期待的正确结果

可以执行

**Comment by fit2-zhao** [comment]
__lowercase 处理的是一个字符正确写法应该是：${__lowercase("${__UUID}")} 需要加引号。

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/751cc328-d8fe-4b22-be02-ff7cdfd55094)
跨线程这个参数这样用不行吗

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/407c9967-6370-4b5a-8229-ed88ecda1c75)
![image](https://github.com/metersphere/metersphere/assets/43202800/d3ee1ffe-46d3-4553-ae63-c85ce2a5ccc4)
反馈加了引号也不生效
