### ISSUE TITLE
[QUESTION]Node-controller节点磁盘如何清理

### ISSUE THREAD

**Issue by sl619437557** [metersphere/metersphere#25891]
### 请描述您的问题

内网服务器无法附图，大致问题如下：
使用了分布式部署的方式，部署了多台node-controller节点，发现任务无法启动。
发现node服务器下的docker挂载路径 /var/lib/docker的磁盘满，查看后应该都是性能测试任务容器文件。是否和我们在有性能测试任务执行时重启后端服务的操作有关？node服务器docker路径下的这些文件如何清理是否可以直接删除？

**Comment by shenkaibo** [comment]
可用 sudo docker system prune -a -f 清理下 docker 目录
