### ISSUE TITLE
[BUG]在接口列表，切换模块的时候会把前一个模块的分页数带过去，导致页面上选中的是第1页，数据展示的是别的页数数据

### ISSUE THREAD

**Issue by Triangel1314** [metersphere/metersphere#2589]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
切换模块的时候没有重置分页id或者选中的分页id不是当前数据的id
![image](https://user-images.githubusercontent.com/56533158/117525274-01158280-aff4-11eb-83b7-c1565f97d339.png)
选中的shi是第一页，展示的数据是第2页
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/56533158/117525283-0c68ae00-aff4-11eb-9953-b45222ad86dc.png)

**Comment by zyyfit** [comment]
您好，这个问题会在后续版本优化

**Comment by zyyfit** [comment]
您好，1.10.0版本将会修复这个问题

**Comment by zyyfit** [comment]
1.10.0版本已修复
