### ISSUE TITLE
[BUG] 断言问题 jsonPath 断言 31.01 != 31.0100 导致很多场景断言失败

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25909]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

是

### 问题描述

针对数字断言的问题：升级之前1.20.23   
断言 31.01 == 31.0100
升级之后2.10.3LTS
断言 31.01 != 31.0100

<img width="901" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/bbded075-4166-4c2f-8cb0-c4ae9db34ca2">
1、等于
<img width="1009" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/9e794c9b-7222-4f67-9eb0-384e158b19a9">
2、正则
<img width="1041" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/ef2eece2-02f8-4cbe-9b07-499209137709">

### 重现步骤

1、写个自定义接口 + mock
2、mock 响应体 { "sss": 31.0100}
3、TEST 选择 mock环境 
4、断言如下
<img width="1041" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/a2dae8cb-7445-45c3-b942-731a59d47657">

**Comment by sss903065212** [comment]
@youliyuan-fit2cloud @fit2-zhao

**Comment by sss903065212** [comment]
之前 v1.20.23LTS 提过类似的 #24735 现在v2.10.3LTS又不行了

**Comment by fit2-zhao** [comment]
您觉得在测试中是否相等呢？

**Comment by Hyyfit** [comment]
jsonpath中的【等于】是完全匹配，包括精度匹配，因此31.01！=31.0100；
建议使用文档结构断言中的【值 等于】，只校验数值相等，可以实现31.01==31.0100

**Comment by sss903065212** [comment]
jsonpath中的【等于】全部替换结构化断言的代价太大，而且对于返回参数很大的接口支持的很不友好
滑动导航很难操作，需要考虑客户使用MS的深度和宽度
