### ISSUE TITLE
[BUG]【测试跟踪】标签为数字开头，且含有空格的功能用例，导入后，用例详情页面啥内容也没有。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25900]
### MeterSphere 版本

v2.10.3

### 使用外置数据库

否

### 问题描述

【测试跟踪】标签为数字开头，且含有空格的功能用例，导入后，用例详情页面啥内容也没有。

### 重现步骤

【测试跟踪】标签为数字开头，且含有空格的功能用例，导入后，用例详情页面啥内容也没有。
![ef69482e8768adda45e42bc2ba38da3](https://github.com/metersphere/metersphere/assets/104960608/48e9f01c-9581-4e0d-b4cf-c83c902e6110)
![e4b059171dd07e6c0c45616b7b051b5](https://github.com/metersphere/metersphere/assets/104960608/28414464-b7f7-4609-a4fe-f04180713abb)

功能用例文件如下:
[Sample.zip](https://github.com/metersphere/metersphere/files/12179869/Sample.zip)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
