### ISSUE TITLE
[BUG]接口测试，文件上传，file 置空不符合预期结果

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#25914]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

接口测试，文件上传，file 传参数不传文件和file 不传参数预期返回的结果不一致，现在file 传参数不传文件和file 不传参数返回结果一致

### 重现步骤

1. 接口测试，文件上传，file 传参数，不传文件，不符合预期
![image](https://github.com/metersphere/metersphere/assets/103627487/fb001f84-80f1-4ba7-8d79-a2d0325ea13c)
ppostman 返回结果
![image](https://github.com/metersphere/metersphere/assets/103627487/4f743f4b-4d9e-4566-86a8-67d44f00b97c)
2. file 参数不传，符合预期
![image](https://github.com/metersphere/metersphere/assets/103627487/4ef3e83a-f61c-4659-a007-57c41e2b8f8f)
![image](https://github.com/metersphere/metersphere/assets/103627487/dc0fc59e-9655-4f89-a34d-a144564a8f2f)

**Comment by zrfit** [comment]
您好，感谢反馈！Metersphere后端调用的jmeter，请用jmeter请求看下您的接口返回什么。

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
