### ISSUE TITLE
[BUG] 前置或者后置 beanShell 脚本这个String code = ${__time()}; 导致所在步骤无结果返回

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25913]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

前后置使用这个String code = ${__time()}; 导致所在步骤无结果返回
<img width="835" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/b94ec51b-59ba-441f-bf03-e5b5b602d2e5">

### 重现步骤

1、随便建一个场景
2、添加一个自定义请求
3、前置或者后置beanShell脚本中添加String code = ${__time()};
4、点击调试

### 期待的正确结果

${__time()} 可以在beanShell中正常执行

**Comment by 13290445582** [comment]
您好，这个函数在JSR223 的 beanshell 脚本执行报错导致无结果返回，建议换成 groovy脚本就行。

**Comment by sss903065212** [comment]
beanshell不支持是吧

**Comment by 13290445582** [comment]
暂不支持
