### ISSUE TITLE
[FEATURE]【测试跟踪】  编辑功能用例后 离开页面后自动保存用例

### ISSUE THREAD

**Issue by PandaTestGrid** [metersphere/metersphere#25929]
### MeterSphere 版本

v2.10.4-lts

### 请描述您的需求或者改进建议

metersphere 测试跟踪 -> 功能用例 -> 脑图 离开当前编辑页可以自动保存编辑用例

### 请描述你建议的实现方案

离开页面后自动保存 or  实时保存

**Comment by luty2018** [comment]
你好， 这个我们会在v3.0讨论规划
