### ISSUE TITLE
[BUG] 【接口测试】快捷调试接口会出现端口丢失问题

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#25927]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

用快捷调试接口会出现端口丢失问题

### 重现步骤

用快捷调试接口

### 期待的正确结果

端口不会丢失

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/c3b976ae-88ae-45b5-95aa-fffa284e2a20)

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.6版本修复这个问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.5-lts版本已修复。
