### ISSUE TITLE
[BUG]【测试跟踪】功能用例选择几条数据进行导出，然后将导出用例再次导入，出现导入失败提示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25937]
### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】功能用例选择几条数据进行导出，然后将导出用例再次导入，出现导入失败提示。

### 重现步骤

【测试跟踪】功能用例选择几条数据进行导出，然后将导出用例再次导入，出现导入失败提示。
![image](https://github.com/metersphere/metersphere/assets/104960608/0aedf275-efa5-4aeb-a0fc-b7a926723f5c)
 将之前导出的用例删掉，再导入excle文件，可以正常导入。

**Comment by 13290445582** [comment]
您好，根据您的截图显示，当前项目下存在相同用例，导入新建是肯定会失败的，这种情况下需要选择导入更新，您可以尝试一下，感谢反馈。
