### ISSUE TITLE
[BUG] 测试计划报告详情，打开某一个接口用例，查看接口请求内容，请求内容很长的时候，展示不全。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#25930]
### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

1. 创建一个测试计划，关联接口用例，这个接口用例有很长的请求内容。
2. 执行测试计划，在报告中查看，控制台查看请求内容。发现没有展示完。

<img width="1234" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/bab88a0b-8308-4760-8e31-7f53fe72ec72">

### 重现步骤

同上

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
