### ISSUE TITLE
[BUG]--添加了循环控制器,根据断言判断失败重试 ,这时候如果重试发起了2个一样的请求，一个成功一个失败，最终场景结果为ERROR，预期为成功

### ISSUE THREAD

**Issue by 157571062297** [metersphere/metersphere#25949]
### 联系方式

pengcheng.wu@summerfarm.net

### MeterSphere 版本

版本:   v2.10.4-lts-6a2bf297

### 使用外置数据库

否

### 问题描述

添加了循环控制器,根据断言判断失败重试 ,这时候如果重试发起了2个一样的请求，一个成功一个失败，最终场景结果为ERROR，预期为成功
![d0f07b3a96bb6b17a4cd2cb62e267eb](https://github.com/metersphere/metersphere/assets/30097089/5dbd1e60-9325-4e9d-8f17-4ff4ad363116)

### 重现步骤

![d0f07b3a96bb6b17a4cd2cb62e267eb](https://github.com/metersphere/metersphere/assets/30097089/c33eb364-f240-4117-9503-14e3229fea1a)

**Comment by zrfit** [comment]
您好，感谢反馈！循环控制器下步骤中含有失败步骤，所以循环控制器的最终结果是失败状态，目前统计的原则是有一个步骤失败，则场景的最终结果就是失败。

**Comment by 157571062297** [comment]
那我失败重试机制 怎么处理呢    重试发起了2个一样的请求，一个失败一个成功，我想要场景结果算成功，怎么设置

**Comment by 157571062297** [comment]
@zrfit

**Comment by zrfit** [comment]
@Hyyfit

**Comment by Hyyfit** [comment]
在场景编辑页，只需要设置一个请求，断言成功就可以了；
【失败重试】测试计划执行的设置中，如下图。
<img width="576" alt="image" src="https://github.com/metersphere/metersphere/assets/95834771/043ae907-f0d4-4e9a-8c21-78eeb0c0a22d">

另外场景的集合报告和测试计划的报告也都还有【失败重跑】功能。
<img width="1381" alt="image" src="https://github.com/metersphere/metersphere/assets/95834771/8037c17d-daff-4109-8174-cb10a647bc74">
