### ISSUE TITLE
[BUG]脑图模式：先添加用例集，再左侧添加文件夹，保存操作后用例丢失

### ISSUE THREAD

**Issue by zhenghuanying** [metersphere/metersphere#2595]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  新建用例集，切换到脑图模式
2. 添加一条用例集、用例、步骤及预期结果，或者复制其他用例
3. 点击：保存
4.

**期待的正确结果**
保存成功，数据正常；希望能够支持脑图添加用例集后再左侧目录添加文件夹名称相同时能够关联上

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，脑图暂时不支持创建模块和子模块，我们先进行下相关调研
