### ISSUE TITLE
[BUG]【误报库】返回数据"result"字段为空数组时，设置其让其为误报，但是误报不生效。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25958]
### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

【误报库】返回数据"result"字段为空数组时，设置其让其为误报，但是误报不生效。

### 重现步骤

【误报库】返回数据"result"字段为空数组时，设置其让其为误报，但是误报不生效。
![image](https://github.com/metersphere/metersphere/assets/104960608/d03b20fe-f5e7-4427-a0c9-132cc20e5d44)

![image](https://github.com/metersphere/metersphere/assets/104960608/89d5b308-c4a1-469a-8744-d1877324ff7f)

![image](https://github.com/metersphere/metersphere/assets/104960608/48590340-81a1-4a01-a838-578954f0c1de)
 
返回 json 报文为:
![74a802be-583d-40bb-b5b9-71224def1b41](https://github.com/metersphere/metersphere/assets/104960608/4ca55dc6-d0ac-4560-9fb9-177178de9862)

{
    "success": true,
    "code": 200,
    "message": "查询成功",
    "result": [
        
    ],
    "condition": {
        "test": "1111"
    }
}

**Comment by zrfit** [comment]
您好，感谢反馈！计划v3进行优化！

**Comment by luty2018** [comment]
已在v3.0支持
