### ISSUE TITLE
[BUG]在计划中，通过筛选器筛选后，选择【选择所有数据】，然后进行批量编辑，编辑的结果为当前可见数据，不是所有的筛选数据

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#25954]
### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

在计划中，通过筛选器筛选后，选择【选择所有数据】，然后进行批量编辑，编辑的结果为当前可见数据，不是所有的筛选数据

### 重现步骤

1. 进入计划，使用筛选器筛选用例，如下图
![企业微信截图_16908693336861](https://github.com/metersphere/metersphere/assets/6109912/bbdb8ebc-e2c5-4328-931f-67fdf9db4a8f)

2.  选择所有筛选数据
![企业微信截图_16908694631018](https://github.com/metersphere/metersphere/assets/6109912/478f85e1-3375-45b6-9e60-9965ed61946e)

3. 对所有筛选数据进行批量编辑，实际编辑的结果为当前页所有的数据

### 期待的正确结果

筛选后，选择所有数据进行编辑，应该编辑的为筛选后所有的数据

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
