### ISSUE TITLE
[BUG] 场景debug调试时、每次都会查询环境列表获取数据，因环境数据过大导致调试需要额外等待很长时间

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25962]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

有89个环境信息、每个环境信息都有很多配置，这些环境信息从接口返回的数据大约3.5M，而每次点击调试时都会请求一次环境列表导致体验很差
具体问题如下图：
<img width="1421" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/60a4041c-c6bc-4537-8451-186d6011f1ba">

### 重现步骤

1、首先需要编辑100条左右的环境信息（可以联系我取这个文件）
2、建一个场景、选择对应的环境（随意）
3、保存之后打开开发人员工具
4、点击调试
5、重复第四步，观察是不是很慢

### 期待的正确结果

调试时不要每次都去请求环境列表的数据，提升用户体验

**Comment by youliyuan-fit2cloud** [comment]
你好，后续版本会优化这里，请关注后续版本发布信息。
ps：你这个 89个环境信息的场景不是特别常见，“体验非常差”的话请不要说了，我们很努力在改进和优化中 :(

**Comment by sss903065212** [comment]
额外等待很长时间
