### ISSUE TITLE
[BUG]【接口自动化】自定义请求-引用场景环境时，若环境启用条件为模块，则环境里的请求头不能正常应用到自定义请求里

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25965]
### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】自定义请求-引用场景环境时，若环境启用条件为模块，则环境里的请求头不能正常应用到自定义请求里

### 重现步骤

【接口自动化】自定义请求-引用场景环境时，如果环境启用条件为无，则环境里的请求头能正常应用到自定义请求里
![1690883535683](https://github.com/metersphere/metersphere/assets/104960608/016673a7-73e1-40ec-bf1f-245da08e2fdb)
![1690883567550](https://github.com/metersphere/metersphere/assets/104960608/6c6c1184-10e9-4d85-afc1-83377787415e)

如果环境启用条件为模块，自定义请求也能使用到环境地址，但是请求头没有正常使用
![1690883600399](https://github.com/metersphere/metersphere/assets/104960608/1880cc81-3e20-4c7a-84d2-18a117790cdb)
![1690883647421](https://github.com/metersphere/metersphere/assets/104960608/6b79e0d8-465e-4939-80cd-cd917556b6bc)

**Comment by zrfit** [comment]
您好，感谢反馈！自定义请求是无模块的，无法引用启用条件为模块的请求头，建议用启用条件为无的环境。
