### ISSUE TITLE
[BUG] 环境配置下的通用配置 批量添加、 编辑、分页和搜索功能 问题

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25967]
### MeterSphere 版本

v2.10.3-lts

### 使用外置数据库

否

### 问题描述

问题一：批量添加、删除问题（QA环境）

https://github.com/metersphere/metersphere/assets/40912189/36bb4ba8-d94b-40b1-88af-82ac6285d644

https://github.com/metersphere/metersphere/assets/40912189/7241d8dd-8379-46a9-9913-c9e31941b22d

问题二：编辑、分页和搜索功能 问题（2.10.3LTS）

https://github.com/metersphere/metersphere/assets/40912189/56a8a3ff-e73f-475d-836d-6ebf954c4c89

### 重现步骤

1、通用配置的参数超过50条
2、按照问题描述的视频操作即可复现

### 期待的正确结果

翻页、查询什么的还是去掉吧，使用浏览器自带的搜索功能挺好的，也不用分页，查询了，基本不会有上面的问题二了

**Comment by 13290445582** [comment]
你好，问题一已经复现了，反馈tapd，计划于v2.10.6版本修复这个问题。问题二在QA未复现，可以升级最新版尝试。

**Comment by 13290445582** [comment]
v2.10.6已修复
