### ISSUE TITLE
[BUG]资源池通过k8s配置多个pod，执行性能测试时一直卡在starting状态

### ISSUE THREAD

**Issue by wuhenyan** [metersphere/metersphere#25968]
### 联系方式

13521081413微信

### MeterSphere 版本

2.10.4-lts

### 使用外置数据库

否

### 问题描述

1、通过k8s形式部署了一套ms，并且配置了node-controller有2个pod
![image](https://github.com/metersphere/metersphere/assets/21330889/5581c3bf-ab00-4dba-b0b7-b6a15c546fda)
2、资源池中新增了node节点并且校验成功
![image](https://github.com/metersphere/metersphere/assets/21330889/1f0a8f75-81a0-48f4-a311-89ce00545bc7)
![image](https://github.com/metersphere/metersphere/assets/21330889/c30f701c-12ef-42b7-b93a-93a2424c8b9b)
3、执行性能测试，报告一直卡在starting状态
![image](https://github.com/metersphere/metersphere/assets/21330889/6dd1fc1e-6326-4d54-b174-6c88912f849b)
4、但是如果只配置一个node节点，是可以正常运行，而不会卡在starting不动

### 重现步骤

参考问题描述

### 期待的正确结果

多node能正常运行性能测试

**Comment by wuhenyan** [comment]
performance-test/error.log有如下报错
![image](https://github.com/metersphere/metersphere/assets/21330889/c6083eb0-0af0-4c89-b0b5-8c78fe5cb7cc)

**Comment by wuhenyan** [comment]
![image](https://github.com/metersphere/metersphere/assets/21330889/8835d378-5ba6-403b-a1ef-84588ba9ecb6)
/opt/metersphere/logs/node-controller/ms-jmeter-run.log 报错如上

**Comment by liuruibin** [comment]
您好，node资源池仅支持使用docker方式部署。如需使用k8s作为资源池请试用企业版

**Comment by wuhenyan** [comment]
但是这个并不是问题的原因，因为我现在即使部署2个pod，但是在资源池只添加一个IP他是可以执行性能测试成功的，只是添加两个pod的时候才会这样

**Comment by wuhenyan** [comment]
![image](https://github.com/metersphere/metersphere/assets/21330889/1db3009b-e162-4d8a-a0be-ff52de137ad8)
![image](https://github.com/metersphere/metersphere/assets/21330889/8f585481-49ca-4d0e-883e-d2b7a36763e6)
他这里是可以跑出来结果的

**Comment by wuhenyan** [comment]
10.1.0.135 这个就是这种方式部署的，同时起了两个pod，135是其中一个ip，用它跑性能测试完全没问题，还有个ip是10.1.0.133，用它单独跑也是可以的，只是把两个都加到资源池就不行了

部署截图
![image](https://github.com/metersphere/metersphere/assets/21330889/b36d5a4e-5bd9-4f1d-b899-c3ce69adbe5d)

**Comment by wuhenyan** [comment]
![image](https://github.com/metersphere/metersphere/assets/21330889/91ee2f04-178c-4d46-a82e-75841960d463)

**Comment by liuruibin** [comment]
这种我们确实没有试过，也不建议用户这么去做，node-controller 只是一个启动jmeter的代理，不承载压力

**Comment by liqiang-fit2cloud** [comment]
没这么用过，也不建议这么用，不过你可以试试用nodeAffinity强制这几个pod分散到不同node。

**Comment by wuhenyan** [comment]
![image](https://github.com/metersphere/metersphere/assets/21330889/1260021d-eab1-48ab-b74a-c6bb745ef17d)
这个方法是在metersphere交流群里，您这边同事给我回复的哦
