### ISSUE TITLE
[BUG] 场景不勾选失败继续的情况下，测试计划失败重试失效、失败重跑失效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#25961]
### MeterSphere 版本

v2.10.3-lts 

### 使用外置数据库

否

### 问题描述

场景不勾选失败继续的情况下，测试计划重试不生效、失败重跑失效
<img width="667" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/898da503-9e29-4be6-bb6c-0ac10a31af77">
<img width="1284" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/aa28e910-535d-4d72-a2f9-92c588f04465">

### 重现步骤

1、场景不勾选失败继续的情况下
2、将改场景关联到测试计划
3、执行测试计划时选择失败重试
4、失败重试失效
5、点击失败重跑
6、失败重跑失效

### 期待的正确结果

不管场景勾不勾选失败继续，都应该在测试计划选择失败重试或失败重跑时 执行重试机制

**Comment by 13290445582** [comment]
您好，创建接口场景不勾选失败继续，在测试计划执行勾选失败重试是不会执行失败重试的。
重跑是整个报告中失败的请求重新执行一次。在最新版本上不勾选失败继续，失败重跑也可以正常使用，可以在报告中点击失败请求去查看开始时间和结束时间来判断是否执行了失败重跑，若无法重跑，建议更新最新环境测试或者去QA测试一下。

**Comment by sss903065212** [comment]
问题：场景不勾选「失败继续」，在测试计划执行勾选失败重试是不会执行「失败重试」的 这个逻辑我知道，但是觉得不合理

 原因1：场景不勾选「失败继续」，后续的逻辑是场景层次的失败的地方后续步骤不继续

 原因2：测试计划执行勾选「失败重试」的逻辑，结合场景不勾选「失败继续」检测的时候不是应该把不勾选「失败继续」场景中失败的也计算到里面吗，当一个场景里面有失败的步骤时，应该把这个场景重跑一下

 原因3：测试计划执行勾选「失败重试」的逻辑， 不管场景勾不勾选「失败继续」，是否都应该当一个场景里面有失败的步骤时，把这个场景重跑一下？（很多场景失败步骤，单独重跑其中失败的步骤是没用的，大部分都会依赖前置步骤的数据）

**Comment by 13290445582** [comment]
您好，暂时这部分的逻辑是这样的，如果您觉得有可以改进的地方可以跟产品提下您的想法，产品评估下决定要不要改动，感谢您的理解与支持。
