### ISSUE TITLE
[BUG]helm-chart 部署 中引用外部 redis 时，无法加载 redisson.yml 配置文件

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#25979]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

helm-chart 部署 中引用外部 redis 时，无法加载 redisson.yml 配置文件
https://github.com/metersphere/helm-chart/blob/main/charts/metersphere/templates/01-config-map/metersphere-config.yaml
{{ if .Values.redis.enabled }}
  redisson.yml: |-
    {{ tpl .Values.redisson.yml . | nindent 4 }}
{{end}}

### 重现步骤

helm-chart 部署 中引用外部 redis 时，无法加载 redisson.yml 配置文件

### 期待的正确结果

不管是否引用 外部 redis 都加载 redisson.yml

**Comment by liuruibin** [comment]
已知悉

**Comment by youliyuan-fit2cloud** [comment]
该问题已修复，请更新下helm-chart。
