### ISSUE TITLE
[BUG] swagger文件导入导出MS问题

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#25974]
### MeterSphere 版本

 v2.10.4-lts

### 使用外置数据库

否

### 问题描述

今天测试了从apifox导出的swagger脚本。发现了几个bug问题和适配问题，想确认一下是否为MS的bug。问题如下：
1.从apifox导出的swagger脚本，当数据类型为array时，默认最大值字段为maxItems、最小值字段为minItems，而MS只能识别最大值字段为maxLength和最小值字段为minLength，导致导入swagger之后，所有array类型的字段，最大值最小值都无法正确展示。
2.从MS中导出swagger，当数据类型为array的字段时，array里面的items内容不完整。如下图：
![image](https://github.com/metersphere/metersphere/assets/47737772/e8fe04d6-77bb-45d3-acca-b7ae2c9974c0)
![image](https://github.com/metersphere/metersphere/assets/47737772/ba6f5086-828a-448a-8a18-a741737fc3be)
3.遇到多层嵌套数组时，MS没办法正确导入swagger的字段数据，如下图：
![image](https://github.com/metersphere/metersphere/assets/47737772/dc0ab7ed-cbe5-4598-b284-3c48fe7d73fa)
![image](https://github.com/metersphere/metersphere/assets/47737772/77792c62-b44c-4aa0-ae17-34fee88abf87)

PS：第一点和第三点问题，附加信息附带复现的swagger json脚本

### 重现步骤

如上述问题描述

### 期待的正确结果

能够正确识别swagger里面的字段数据，正确导入到MS中。

### 附加信息

{
  "openapi": "3.0.1",
  "info": {
    "title": "71.7.0.B-api",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "OpenApi会议接口"
    }
  ],
  "paths": {
    "/services/openapi/v1.0/room/meeting_create": {
      "post": {
        "summary": "创建会议日程",
        "x-apifox-folder": "OpenApi会议接口",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "operationId": "OpenApi会议接口__创建会议日程",
        "tags": [
          "OpenApi会议接口"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/com.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/com.base.specification.response.ResponseBodySpecCom.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiResponse"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/com.base.specification.response.ResponseBodySpec"
                }
              }
            }
          },
          "405": {
            "description": "Method Not Allowed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/com.base.specification.response.ResponseBodySpec"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/com.base.specification.response.ResponseBodySpec"
                }
              }
            }
          }
        },
        "x-run-in-apifox": ""
      }
    }
  },
  "components": {
    "schemas": {
      "com.base.specification.response.ResponseBodySpec": {
        "title": "ResponseBodySpec",
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "x-apifox-orders": [],
            "properties": {},
            "x-apifox-ignore-properties": []
          },
          "status": {
            "type": "string"
          },
          "errMsg": {
            "type": "string"
          },
          "requestId": {
            "type": "string"
          },
          "errCode": {
            "type": "string"
          },
          "detailMsg": {
            "type": "string"
          }
        },
        "x-apifox-orders": [
          "data",
          "status",
          "errMsg",
          "requestId",
          "errCode",
          "detailMsg"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.base.specification.response.ResponseBodySpecCom.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiResponse": {
        "title": "MeetingCreateOpenApiResponse",
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/com.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiResponse"
          },
          "status": {
            "type": "string"
          },
          "errMsg": {
            "type": "string"
          },
          "requestId": {
            "type": "string"
          },
          "errCode": {
            "type": "string"
          },
          "detailMsg": {
            "type": "string"
          }
        },
        "x-apifox-orders": [
          "data",
          "status",
          "errMsg",
          "requestId",
          "errCode",
          "detailMsg"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiResponse": {
        "title": "会议创建响应",
        "type": "object",
        "properties": {
          "meetingId": {
            "type": "string",
            "description": "会议Id(首个日程)"
          }
        },
        "x-apifox-orders": [
          "meetingId"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.cloud.smartoffice.openapi.model.meeting.MeetingCreateOpenApiRequest": {
        "title": "会议创建请求",
        "required": [
          "endTime",
          "hostId",
          "roomId",
          "startTime",
          "subject"
        ],
        "type": "object",
        "properties": {
          "subject": {
            "maxLength": 255,
            "minLength": 0,
            "type": "string",
            "description": "会议主题"
          },
          "startTime": {
            "minimum": 1,
            "type": "integer",
            "description": "会议开始时间",
            "format": "int64"
          },
          "endTime": {
            "minimum": 1,
            "type": "integer",
            "description": "会议结束时间",
            "format": "int64"
          },
          "hostId": {
            "minimum": 1,
            "type": "integer",
            "description": "组织者的memberId",
            "format": "int64"
          },
          "participantIds": {
            "maxLength": 300,
            "minItems": 0,
            "type": "array",
            "description": "参会者的memberId",
            "items": {
              "type": "integer",
              "description": "参会者的memberId",
              "format": "int64"
            }
          },
          "guestEmails": {
            "maxItems": 300,
            "minItems": 0,
            "type": "array",
            "description": "外部参会者邮箱",
            "items": {
              "type": "string",
              "description": "外部参会者邮箱"
            }
          },
          "roomId": {
            "minimum": 1,
            "type": "integer",
            "description": "会议室Id",
            "format": "int64"
          },
          "notificationTimes": {
            "type": "array",
            "description": "会议提醒时间",
            "items": {
              "type": "integer",
              "description": "会议提醒时间",
              "format": "int32"
            }
          },
          "online": {
            "type": "boolean",
            "description": "是否为在线会议(仅Teams和Microsoft365)"
          },
          "repeat": {
            "allOf": [
              {
                "type": "object",
                "description": "会议重复规则",
                "x-apifox-orders": [],
                "properties": {},
                "x-apifox-ignore-properties": []
              },
              {
                "$ref": "#/components/schemas/com.cloud.smartoffice.openapi.model.meeting.MeetingRepeatRuleOpenApiDto"
              }
            ]
          },
          "meetingServices": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "description": "会议服务",
            "items": {
              "allOf": [
                {
                  "type": "object",
                  "description": "会议服务",
                  "x-apifox-orders": [],
                  "properties": {},
                  "x-apifox-ignore-properties": []
                },
                {
                  "$ref": "#/components/schemas/com.cloud.smartoffice.openapi.model.meeting.MeetingServiceOpenApiDto"
                }
              ]
            }
          },
          "remark": {
            "maxLength": 4096,
            "minLength": 0,
            "type": "string",
            "description": "备注"
          }
        },
        "x-apifox-orders": [
          "subject",
          "startTime",
          "endTime",
          "hostId",
          "participantIds",
          "guestEmails",
          "roomId",
          "notificationTimes",
          "online",
          "repeat",
          "meetingServices",
          "remark"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.cloud.smartoffice.openapi.model.meeting.MeetingServiceOpenApiDto": {
        "title": "会议服务",
        "required": [
          "contactIds",
          "serviceType"
        ],
        "type": "object",
        "properties": {
          "serviceType": {
            "maxLength": 255,
            "minLength": 0,
            "type": "string",
            "description": "会议服务名称"
          },
          "notificationRules": {
            "maxItems": 100,
            "minItems": 0,
            "type": "array",
            "description": "会议服务规则",
            "items": {
              "allOf": [
                {
                  "type": "object",
                  "description": "会议服务规则",
                  "x-apifox-orders": [],
                  "properties": {},
                  "x-apifox-ignore-properties": []
                },
                {
                  "$ref": "#/components/schemas/com.cloud.smartoffice.openapi.model.meeting.MeetingServiceRuleOpenApiDto"
                }
              ]
            }
          },
          "contactIds": {
            "maxItems": 100,
            "minItems": 1,
            "type": "array",
            "description": "联系人memberId",
            "items": {
              "type": "integer",
              "description": "联系人memberId",
              "format": "int64"
            }
          },
          "serviceRemark": {
            "maxLength": 4096,
            "minLength": 0,
            "type": "string",
            "description": "备注"
          }
        },
        "x-apifox-orders": [
          "serviceType",
          "notificationRules",
          "contactIds",
          "serviceRemark"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.cloud.smartoffice.openapi.model.meeting.MeetingServiceRuleOpenApiDto": {
        "title": "会议服务规则",
        "type": "object",
        "properties": {
          "meetingStatus": {
            "type": "string",
            "description": "会议状态条件. 会议状态条件: `NOT_STARTED`(会议开始前), `ENDED`(会议结束后)",
            "enum": [
              "NOT_STARTED",
              "ENDED"
            ]
          },
          "notificationTime": {
            "maximum": 86400,
            "minimum": 0,
            "type": "integer",
            "description": "提前通知时间(分钟); 如果条件是会议结束后, 可以为空",
            "format": "int32"
          }
        },
        "x-apifox-orders": [
          "meetingStatus",
          "notificationTime"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      },
      "com.cloud.smartoffice.openapi.model.meeting.MeetingRepeatRuleOpenApiDto": {
        "title": "会议重复规则",
        "required": [
          "endDate",
          "frequency",
          "type"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "description": "重复类型. 周期重复类型: `DAILY`(daily, 即每几日循环), `WEEKLY`(weekly, 即每几周周几循环), `ABSOLUTE_MONTHLY`(absolute Monthly, 即每几月指定日期循环), `RELATIVE_MONTHLY`(relative Monthly, 即每几月第几周周几循环), `ABSOLUTE_YEARLY`(absolute Yearly, 即每几年指定日期循环), `RELATIVE_YEARLY`(relative Yearly, 即每几年第几月第几周周几循环)",
            "enum": [
              "DAILY",
              "WEEKLY",
              "ABSOLUTE_MONTHLY",
              "RELATIVE_MONTHLY",
              "ABSOLUTE_YEARLY",
              "RELATIVE_YEARLY"
            ]
          },
          "frequency": {
            "maximum": 100000,
            "minimum": 1,
            "type": "integer",
            "description": "重复频率, 如每5天",
            "format": "int32",
            "example": 5
          },
          "dayOfWeek": {
            "maxItems": 7,
            "minItems": 1,
            "type": "array",
            "description": "每周的周几, 范围1-7, MONDAY为1",
            "example": [
              1,
              2
            ],
            "items": {
              "type": "integer",
              "description": "每周的周几, 范围1-7, MONDAY为1",
              "format": "int32"
            }
          },
          "dayOfMonth": {
            "maximum": 31,
            "minimum": -1,
            "type": "integer",
            "description": "每月的第几天, 范围为1-31或-1, 为-1时表示最后一天",
            "format": "int32",
            "example": 31
          },
          "weekOfMonth": {
            "maximum": 5,
            "minimum": -1,
            "type": "integer",
            "description": "每月的第几个星期X, -1表示最后一个, 1表示第一个",
            "format": "int32",
            "example": 4
          },
          "endDate": {
            "type": "string",
            "description": "重复结束日期, 使用ISO-8601附带时区拓展的格式, 如'2023-01-01T00:00:00+08:00[Asia/Shanghai]', 注意时区是必须的",
            "example": "2023-01-01T00:00:00+08:00[Asia/Shanghai]"
          }
        },
        "x-apifox-orders": [
          "type",
          "frequency",
          "dayOfWeek",
          "dayOfMonth",
          "weekOfMonth",
          "endDate"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": "Schemas"
      }
    }
  }
}

**Comment by 13290445582** [comment]
您好，swagger数据类型为array的字段时，导出array里面的items内容不完整，在swagger测试工具里也是这样子的，确实是只有一个，不是ms的bug。
<img width="669" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/0130323a-8faf-4a6c-8429-c184a297f02b">

导入到ms中repeat字段下没有内容，是因为repeat没有写type，所以导入到ms是null。
