### ISSUE TITLE
[BUG]测试跟踪：脑图模式编写用例后，未保存操作切换到列表时，建议进行未保存用例的提示

### ISSUE THREAD

**Issue by zhenghuanying** [metersphere/metersphere#2597]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  脑图模式编写用例
2. 未保存操作切换到列表
3. 
4. 

**期待的正确结果**
建议提示用例未保存，数据容易丢失

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先进行下相关调研
