### ISSUE TITLE
[BUG]UI测试流程控制-条件表达式中使用计算符结果不准确

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#25976]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

UI测试流程控制-条件表达式中使用计算符结果不准确。如果计算的值是整数是正确的，如果是浮点数就不准确。

### 重现步骤

1.这是准确的示例：设置UI测试场景变量n1=1，n3=3，流程控制表达式使用${n1}*3==${n3}，可以判断成功，进入控制器
![image](https://github.com/metersphere/metersphere/assets/88763608/68c6f8e8-37f8-4bb1-9d50-91f6f23c8343)
![image](https://github.com/metersphere/metersphere/assets/88763608/87ef27a8-05ee-44fe-b70c-f9ad6bec97d1)
2.这是不准确的示例：设置UI测试场景变量q3=45.8，q4=105.34，流程控制表达式使用${n1}*3==${n3}，条件判断失败，没有进入控制器
![image](https://github.com/metersphere/metersphere/assets/88763608/7cc9324c-eb85-464c-a74d-9ce31618dcf8)
![image](https://github.com/metersphere/metersphere/assets/88763608/bcd600de-e2e7-48e9-930a-8f997ace0af4)

### 期待的正确结果

希望可以准确

**Comment by liuruibin** [comment]
![image](https://github.com/metersphere/metersphere/assets/23045261/8c996d70-75a7-434e-8c2e-059115232b41)
你看并不等于

**Comment by linfengjjj** [comment]
感谢副老师！
