### ISSUE TITLE
[BUG] 系统设置-创建资源池，Jmeter_GC_ALGO 输入超长字符，提示 internal exception occured ,

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#25988]
### MeterSphere 版本

2.10.5-lts

### 使用外置数据库

否

### 问题描述

系统设置-创建资源池，Jmeter_GC_ALGO 输入超长字符，提示 internal exception occured ,
![image](https://github.com/metersphere/metersphere/assets/43202800/f670cf5e-06f3-41a5-b474-a5679726760e)

### 重现步骤

系统设置-创建资源池，Jmeter_GC_ALGO 输入超长字符，提示 internal exception occured ,
![image](https://github.com/metersphere/metersphere/assets/43202800/f670cf5e-06f3-41a5-b474-a5679726760e)

### 期待的正确结果

无报错

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
