### ISSUE TITLE
[FEATURE]能否自定义数据库驱动类配置数据库连接

### ISSUE THREAD

**Issue by wanorin** [metersphere/metersphere#25980]
### MeterSphere 版本

v2.10.4

### 联系方式

2064431535@qq.com

### 请描述您的需求或者改进建议

目前支持的数据库连接类型较少。不支持的数据库只能通过脚本连接，实际体验不佳。
jmeter针对不支持的数据库，可以自定义编辑驱动类。metersphere会有这样的功能吗？

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/127196164/eb4b61d4-351e-4f38-8988-fef04edfe713)

**Comment by luty2018** [comment]
会的， 我们正在计划将这块进行插件化处理，方便用户可以自定义数据库驱动

**Comment by fit2-zhao** [comment]
感谢建议，有个重复需求，请关注这个 #4761 后续。

**Comment by dragon1990** [comment]
msyql8的驱动目前也不支持
