### ISSUE TITLE
[BUG]【接口定义】上传接口，当上传文件为word/jpg时，后面的类型默认是application/octet-stream，这导致上传失败，需要手动将类型改为其他才能正常上传，希望能根据文件类型自动变成对应类型，或者有选择下拉框进行选择

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25986]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

【接口定义】上传接口，当上传文件为word/jpg时，后面的类型默认是application/octet-stream，这导致上传失败，需要手动将类型改为其他才能正常上传，希望能根据文件类型自动变成对应类型，或者有选择下拉框进行选择

### 重现步骤

【接口定义】上传接口，当上传文件为word/jpg时，后面的类型默认是application/octet-stream，这导致上传失败
![ee63a6727900bbaa784aa85a8cf2d7e](https://github.com/metersphere/metersphere/assets/104960608/b9a1c89c-372a-4a02-8412-05cbecdeddbc)
![7c987ccb4af46d0136a7e96a52f5093](https://github.com/metersphere/metersphere/assets/104960608/df3ff227-9a1d-424a-a3fc-9e3afdce4d62)
需要手动将类型改为其他才能正常上传，希望能根据文件类型自动变成对应类型，或者有选择下拉框进行选择

**Comment by liqiang-fit2cloud** [comment]
不是bug，需要的话提需求。
