### ISSUE TITLE
[BUG]接口自动化场景用例，在接口的前置脚本中vars.put设置的变量a后再在该接口的请求体中用${a}取该值，查看请求参数没有取到前置脚本中设置的值，还是展示${a}

### ISSUE THREAD

**Issue by zjmei10** [metersphere/metersphere#25989]
### MeterSphere 版本

版本:   v2.10.4-lts-6a2bf297

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/42205532/824498cc-66fe-479b-9ebe-cf39645fc22a)
标红色的值，在这个接口的前置脚本中有赋值如下：
![image](https://github.com/metersphere/metersphere/assets/42205532/91973339-5127-4d8f-bf8f-b9f96299a1ea)
控制台可以打印出赋值
![image](https://github.com/metersphere/metersphere/assets/42205532/0c90b85c-2723-4d06-bcc4-b89c9a34655c)
实际请求时拿不到设置的值
![image](https://github.com/metersphere/metersphere/assets/42205532/49ef7ac5-06f2-4dba-9aac-d1d37208780b)

### 重现步骤

1，场景中新增接口
2,接口请求类型为json，某个值为该接口在自己的前置脚本中设置的变量
3请求接口

### 期待的正确结果

请求接口时，可以获取到变量的值

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.5-lts无该问题，建议升级到最新版本尝试。
<img width="936" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/c3b7cb1c-ac67-4e28-982e-5c837c9fa75a">

**Comment by zjmei10** [comment]
已经升级到最新版本，还是有这个问题，可以看下你这个变量是在哪里设置的吗？是在该接口的前置脚本中写的吗？还有这个变量有设置为场景变量吗？

**Comment by zjmei10** [comment]
> 您好，感谢反馈！v2.10.5-lts无该问题，建议升级到最新版本尝试。 <img alt="image" width="936" src="https://user-images.githubusercontent.com/99731894/258038275-c3b7cb1c-ac67-4e28-982e-5c837c9fa75a.png">
已经升级到最新版本，还是有这个问题，可以看下你这个变量是在哪里设置的吗？是在该接口的前置脚本中写的吗？还有这个变量有设置为场景变量吗？
能不能给我看下前置里的脚本是怎样赋值的？我跟同事试了都是取不到值的

**Comment by zrfit** [comment]
您好，就是按您的描述和场景结构模拟在前置脚本设置的变量-然后请求参数引用该变量是可以的，并没有设置到场景变量中。
<img width="1074" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/f2abafcb-132c-423b-ab48-381f95883f01">

**Comment by zjmei10** [comment]
> 您好，就是按您的描述和场景结构模拟在前置脚本设置的变量-然后请求参数引用该变量是可以的，并没有设置到场景变量中。 <img alt="image" width="1074" src="https://user-images.githubusercontent.com/99731894/258287114-f2abafcb-132c-423b-ab48-381f95883f01.png">
那我还有什么可以排查的手段可以看下这个问题吗？我们这边就算不在循环中，接口的前置操作中赋值都是提取不到的

**Comment by zjmei10** [comment]
> 您好，就是按您的描述和场景结构模拟在前置脚本设置的变量-然后请求参数引用该变量是可以的，并没有设置到场景变量中。 <img alt="image" width="1074" src="https://user-images.githubusercontent.com/99731894/258287114-f2abafcb-132c-423b-ab48-381f95883f01.png">

好的，我刚排查过了，是因为全局前置脚本选择的在接口前置脚本之前运行，所以取值不对。
