### ISSUE TITLE
[BUG]【接口定义】当全局断言里设置了断言状态码，在接口里也设置了断言状态码，断言没有进行覆盖，而是都生效了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#25987]
### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

【接口定义】当全局断言里设置了断言状态码，在接口里也设置了断言状态码，断言没有进行覆盖，而是都生效了。

### 重现步骤

【接口定义】当全局断言里设置了断言状态码，在接口里也设置了断言状态码，断言没有进行覆盖，而是都生效了。
![image](https://github.com/metersphere/metersphere/assets/104960608/03aa0ccc-71d7-4691-94b9-d85d01787376)

**Comment by youliyuan-fit2cloud** [comment]
你好，觉得这个逻辑不合理吗？说出你的想法～^ _ ^～

**Comment by 2lipan** [comment]
JMeter里如果全局断言和请求断言都设置的话，会以全局断言为准。
![c6730025c821f3964554842c936b851](https://github.com/metersphere/metersphere/assets/104960608/22de6d5b-dbae-4d10-b446-e6d82a80625d)
现遇到场景是这样的: 大部分接口的正确返回结果都是code为0，状态码为200，但是有部分接口没有code，而且状态码可能是201这种，全局断言设了code为0，状态码为200的校验，想针对这小部分接口单独处理，所以需要在请求里另外设置断言，请求里断言需要覆盖全局断言才可以实现

**Comment by luty2018** [comment]
我们现在是全局断言和请求断言都会生效， 也有用户反馈你这类似的需求， 我们也规划了，会在请求的断言里加一个选项，忽略全局断言。因为涉及到执行逻辑的修改，是计划v3在加的。

**Comment by luty2018** [comment]
![image](https://github.com/metersphere/metersphere/assets/36292514/10d097d4-21d7-4320-8618-d229f8538770)
类似这个效果
