### ISSUE TITLE
[FEATURE][接口测试]建议“请求参数”子项的数量提示信息保持一致

### ISSUE THREAD

**Issue by zhoubo01** [metersphere/metersphere#25985]
### MeterSphere 版本

v2.10.x-lts

### 联系方式

zhoubo@ulic.com.cn;

### 请描述您的需求或者改进建议

建议“请求参数”子项的数量提示信息保持一致,目前接口编辑页面的请求参数子项中“请求体”、“认证配置”子项配置了也没有提示信息，建议与其他子项保持一致，否则容易误导用户。

### 请描述你建议的实现方案

“请求参数”子项的数量提示信息保持一致，子项中有配置内容，都给予数字提示

**Comment by luty2018** [comment]
感谢建议， 我们在最近的2个小版本内优化一下。

**Comment by luty2018** [comment]
看一下v3目前是否满足需求，基于v3来优化吧
