### ISSUE TITLE
[BUG]环境管理中的复制环境组，点击后出现没有权限的错误Subject does not have permission，但实际空间管理员已经分配了这个权限

### ISSUE THREAD

**Issue by wangxin188** [metersphere/metersphere#25990]
### MeterSphere 版本

v2.10.2-lts

### 使用外置数据库

否

### 问题描述

环境管理中的复制环境组，点击后出现没有权限的错误Subject does not have permission，但实际空间管理员已经分配了这个权限

### 重现步骤

创建一个用户，给他分配系统管理员，空间管理员以及项目管理员的身份，空间管理员中包含复制环境组的权限，这时点击复制环境组会出现权限问题，如果给用户分配超级管理员的身份，该用户可以复制环境组成功

### 相关日志输出

```shell
https://github.com/metersphere/metersphere/assets/141306651/8dfe5bac-8f84-49ee-858f-cf10515c247b
```

**Comment by 13290445582** [comment]
您好，请截屏下详细的权限配置信息。在最新版本未复现这种权限错误问题，建议您升级至最新版本尝试是否还会有此错误。

**Comment by wangxin188** [comment]
https://github.com/metersphere/metersphere/assets/141306651/54657401-5263-40a2-a604-55f2ab753318
https://github.com/metersphere/metersphere/assets/141306651/9c68b36a-90c7-4c2f-8a5e-ca0cb7f65f04

**Comment by wangxin188** [comment]
这个权限控制的代码主要在前端实现还是后端实现的。您那边能按照步骤复现吗，去除超级管理员身份后刷新一下在复制环境组就会出现刚刚的问题

**Comment by 13290445582** [comment]
您好，刚在旧版本测试确实有此问题，请升级最新的v2.10.5，最新版本无此问题。

**Comment by wangxin188** [comment]
好的，麻烦了，我稍后升级一下
