### ISSUE TITLE
[BUG]新安装的metersphere没有默认项目的时候点击环境列表报错

### ISSUE THREAD

**Issue by liuchangfitcloud** [metersphere/metersphere#2599]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1
**Bug 描述**
简要描述您碰到的问题
如果项目为空，点击环境列表报错
**Bug 重现步骤**
1.  安装1.9.1
2. 登录设置->项目->环境配置
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
不报错，获取默认初始化一个default的项目
![23081620460075_ pic_hd](https://user-images.githubusercontent.com/44662176/117531549-86f5f580-b015-11eb-81c7-d27ae3978976.jpg)

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
下个版本修复

**Comment by xulinde** [comment]
1.10.4已修复
