### ISSUE TITLE
[BUG] 功能用例的操作列 切换英文之后  文字按钮问题

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26005]
### MeterSphere 版本

v2.10.5-lts 

### 使用外置数据库

否

### 问题描述

2.10.x版本效果：
<img width="1137" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/55d2fbd3-ee40-4112-8de6-b1a8e1a993c8">
之前v1版本效果：
<img width="1251" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/163ff708-64b7-49fd-9298-87112ac64dc2">

### 重现步骤

1、切换英文
2、打开功能用例
3、查看用例列表的操作那一列
4、看下样式效果不理想

### 期待的正确结果

希望所有的相同的操作那一列的按钮能做到统一，是图片按就全是图片按钮，不然切换一个功能样式就变了，很难适应，关键文字按钮效果 英文展示来看不是很好

**Comment by 13290445582** [comment]
您好，在v2版本，功能用例-查看/复制/删除选择是就是文字按钮的方式，本身不是bug，您可以提FEATYRE给我们的产品老师评估下，看下是否需要改动这里，感谢您的理解与支持。
