### ISSUE TITLE
[BUG]通过Excel上传用例，开启了自定义ID，在上传的时候出现了报错

### ISSUE THREAD

**Issue by noah1007** [metersphere/metersphere#26009]
### 联系方式

noah.lin@deckers.com

### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

![MicrosoftTeams-image (232)](https://github.com/metersphere/metersphere/assets/74529826/add13abb-4956-4fd2-9a7c-93617be99885)
通过excel模版进行上传测试用例，模版表头：ID，Name，Module，Tag，Edit Model，Case status，Maintainer，priority
以往都是成功上传，在更新了2.10.5版本之后，出现了如图的错误

### 重现步骤

在项目管理设立开启自定义ID选项
通过excel模版进行上传测试用例，模版表头：ID，Name，Module，Tag，Edit Model，Case status，Maintainer，priority

### 期待的正确结果

正常上传成功测试用例

**Comment by 13290445582** [comment]
您好，请提供下导入的excel文件和项目的用例模版配置，导入excel文件报错的后台完整日志信息。

**Comment by noah1007** [comment]
{
  "success": false,
  "message": "\n### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.TestCaseMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Column 'node_id' cannot be null\n### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.TestCaseMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Column 'node_id' cannot be null",
  "data": null
}

**Comment by noah1007** [comment]
[task2.2.12 Tasks.xlsx](https://github.com/metersphere/metersphere/files/12271512/task2.2.12.Tasks.xlsx)

**Comment by noah1007** [comment]
> 您好，请提供下导入的excel文件和项目的用例模版配置，导入excel文件报错的后台完整日志信息。

你好，已经补齐

**Comment by 13290445582** [comment]
您好，还有您当前项目所使用的用例模版配置，截屏提供下，我配置一样的测试一下。

**Comment by noah1007** [comment]
> 

<img width="575" alt="MicrosoftTeams-image (233)" src="https://github.com/metersphere/metersphere/assets/74529826/a294afb4-2ce3-4284-b37d-898c32ab99df">

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
