### ISSUE TITLE
[BUG] 国际化问题 测试跟踪 功能用例导出、更改记录、编辑等

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26003]
### MeterSphere 版本

V2.10.5LTS

### 使用外置数据库

否

### 问题描述

<img width="1251" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/2b5b1de9-e93f-48da-acb8-9e9fce710fcc">
<img width="1356" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/375037ac-63c0-4cb3-bba0-a18252e8a335">
<img width="1267" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/a9dc3f45-4fd1-419c-a6bb-496db8ca404c">

### 重现步骤

1、
<img width="273" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/d193f5f9-e805-4c4e-9adb-1547e4fbb1cf">
2、点击功能用例
3、导出查看execl
4、编辑查看Preconditions
5、修改步骤
6、查看Change record

### 期待的正确结果

国际化 英文

**Comment by 13290445582** [comment]
感谢您的反馈，计划于v2.10.7版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
