### ISSUE TITLE
[BUG] 升级V2之后  原登陆URL不能登陆

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26006]
### MeterSphere 版本

v2.10.5-LTS

### 使用外置数据库

否

### 问题描述

v1 原先登陆路径为http://IP:port/login#/
v2 登陆路径为http://IP:port/#/login
导致客户升级之后输入域名登陆时 一直登陆不上问题
<img width="822" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/6061b5da-a016-4111-887b-59e18e0670c4">

### 重现步骤

1、找一个v1的环境
2、设置一个域名
3、升级v2
4、再打开这个域名
5、登陆不上出现401的报错

### 期待的正确结果

针对这种登陆路径发生变化的情况做下处理
1、提供一个页面提示客户路径发生变化使用新的路径
2、做转发用old登陆url 转发到new 登陆url上

**Comment by liqiang-fit2cloud** [comment]
不是bug，设计如此，不会强制v1和v2的url一致。
请按照v2的url调整域名设置。

**Comment by liqiang-fit2cloud** [comment]
无论是v1还是v2，输入IP和端口就会自动跳转到相应登录页面的url。
