### ISSUE TITLE
[FEATURE] 功能用例的操作列 切换英文之后 建议将文字按钮改为原先的图片按钮

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26016]
### MeterSphere 版本

v2.10.X-lts

### 请描述您的需求或者改进建议

希望整个平台的按钮样式可以保持统一，文字按钮效果在中英文切换后效果不如图片按钮
![image](https://github.com/metersphere/metersphere/assets/40912189/1affdbae-3174-4b48-802c-d7da809da691)
![image](https://github.com/metersphere/metersphere/assets/40912189/4762d53a-239d-4c59-aa45-88cbd3d41f49)

### 请描述你建议的实现方案

将V2的文字按钮改为V1的图片按钮的样式，对整个项目的按钮样式做个统一

**Comment by liqiang-fit2cloud** [comment]
V3和V2的都使用文字按钮，V1不再改动。

**Comment by sss903065212** [comment]
文字按钮，当涉及国际化切换英文时 样式会发生变化，这个文字方案的方案是否未考虑此情况

**Comment by liqiang-fit2cloud** [comment]
> 文字按钮，当涉及国际化切换英文时 样式会发生变化，这个文字方案的方案是否未考虑此情况

长度变化符合预期，不串行就行。
你可以试试阿里云。
<img width="211" alt="image" src="https://github.com/metersphere/metersphere/assets/20766823/3c688d47-4a7e-4951-b7ff-5f60ac4f4829">
<img width="338" alt="image" src="https://github.com/metersphere/metersphere/assets/20766823/eef025e1-48de-4391-a315-85861776372e">
