### ISSUE TITLE
[BUG] 在centos系统中安装离线包显示docker未安装

### ISSUE THREAD

**Issue by anstarword** [metersphere/metersphere#26018]
### 联系方式

anstarword@163.com

### MeterSphere 版本

metersphere-offline-installer-v2.10.4-lts.tar.gz

### 使用外置数据库

否

### 问题描述

按页面说明，在一个干净的conetos中进行离线安装，执行/bin/bash install.sh后，系统监测到没有安装docker，会自行安装，但在启动docker的阶段还是报docker未安装

### 重现步骤

同问题描述

### 期待的正确结果

install.sh里，这个地方似乎有问题
cp docker/bin/* /usr/bin/  这里将bin中所有文件copy到linux
chmod +x /usr/bin/docker*  这里只给了docker开头的文件以执行权限
这会导致后面启动docker失败 service docker start

将docker/bin/中copy过去的所有文件赋予可执行权限后，再执行install.sh就可以正常安装和启动metersphere了

**Comment by liuruibin** [comment]
您好，这个问题会在2.10.6中修复
