### ISSUE TITLE
[FEATURE]批量修改场景的运行环境

### ISSUE THREAD

**Issue by Xingac1999** [metersphere/metersphere#26011]
### MeterSphere 版本

v2.1.1

### 联系方式

2280930812@qq.com

### 请描述您的需求或者改进建议

场景：项目版本更新后，新创建一个metersphere中的**项目**，并将原来的**接口自动化**所有**场景**全部复制到新的项目中，此时所有的场景的**运行环境**为空，需要编辑每一个场景的运行环境才能正常运行
需求：批量修改同一个项目接口自动化中场景的运行环境

### 请描述你建议的实现方案

改变选中项目中所有运行场景的运行环境参数

**Comment by youliyuan-fit2cloud** [comment]
你好，在接口自动化页面-批量选中场景可以编辑修改运行环境，不知道是不是这个意思？参考下图：
![image](https://github.com/metersphere/metersphere/assets/54612864/01ab4b0b-ae56-4ad0-8734-83d3991ff1b6)

**Comment by Xingac1999** [comment]
是这个，之前没有找到这个批量功能，非常感谢！
