### ISSUE TITLE
[BUG]接口测试中JSONSchema切换数据类型失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#26029]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

接口测试中，打开JSONSchema之后，添加数据如附件中的步骤，会导致数据类型切换失败

### 重现步骤

可参考附件中的视频

### 附加信息

https://github.com/metersphere/metersphere/assets/32027713/fee5d47f-7ec2-473c-aab7-84b0452809ec

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.6-lts修复。
