### ISSUE TITLE
[BUG] swagger-url带中文导入metersphere失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26025]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

swagger-url带中文导入metersphere失败

### 重现步骤

swagger-url带中文导入metersphere失败：
![image](https://github.com/metersphere/metersphere/assets/103925124/168d7fcd-0e33-4367-8f70-6f1dad898d06)
![image](https://github.com/metersphere/metersphere/assets/103925124/89a12c8f-99b7-4b6a-9c7e-995d302d8f07)
直接使用https://xx.xx.com:2371/v3/api-docs?group=%E4%BB%AA%E8%A1%A8%E6%9D%BF%E7%AE%A1%E7%90%86导入y也是失败：
![image](https://github.com/metersphere/metersphere/assets/103925124/a47d67da-b0c5-4c99-b9bc-a08a70030e21)
dataease使用的是 Knifej
![81bf5df661f99f934daea3ab10bec1c](https://github.com/metersphere/metersphere/assets/103925124/8695780b-59b1-4b27-a1cb-6faee4ae34ae)

**Comment by zrfit** [comment]
您好，感谢反馈！
1、de的接口导入需要cookie校验，请求头要填写cookie信息，然后再填写带参数的url即可导入成功。
<img width="1249" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/fe40cb3c-9a5a-4432-ac41-ad887b7c4565">

2、url中的参数填写到QUERY参数中导入失败，计划v2.10.7-lts优化。
