### ISSUE TITLE
[FEATURE]同一项目下，不同模块下允许 同名场景

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2602]
**请描述您的需求或者改进建议.**

同一项目下，不同模块是否可以支持创建同名的场景用例

**请描述你建议的实现方案**
不同的模块我按照版本定义了下，每个模块 可能会跑同一个场景，场景的步骤相同，唯一区别是参数不同（因为不同版本），那么每个模块都会为同一个场景命名个新名字，能否考虑不同模块下允许 同名场景呢？
![2011620461625_ pic_hd](https://user-images.githubusercontent.com/30038088/117535576-fcb78c80-b028-11eb-9523-7c44fb88b119.jpg)

**Comment by xulinde** [comment]
是支持的，您用的是哪个版本呢

![Uploading image.png…]()
