### ISSUE TITLE
[BUG]开启录制插件导致报跨域(cross-origin frame)错误，关闭录制插件 无此问题

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2603]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
**Bug 描述**
简要描述您碰到的问题
开启录制插件导致报跨域错误，关闭录制插件 无此问题
**Bug 重现步骤**
1.  
![31620463347_ pic_hd](https://user-images.githubusercontent.com/30038088/117536033-7a7c9780-b02b-11eb-899b-74c3ee98cc77.jpg)

2.
![41620463352_ pic_hd](https://user-images.githubusercontent.com/30038088/117536042-80727880-b02b-11eb-8082-4fc0a0446e6b.jpg)

3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
可以正常录制
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是哪个页面报错呢？

**Comment by shenkaibo** [comment]
这个是被测系统 报的，点开我们 录制插件 就会有这个错，不打开 就没事。
