### ISSUE TITLE
[BUG]【性能测试】监控磁盘IO使用率，在prometheus页面使用promQL语句(读+写之和)可以正常查询到，将表达式放到MS监控里，没有监控数据出现

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26031]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

【性能测试】监控磁盘IO使用率，在prometheus页面使用promQL语句(读+写之和)可以正常查询到，将表达式放到MS监控里，没有监控数据出现

### 重现步骤

【性能测试】监控磁盘IO使用率，在prometheus页面使用promQL语句(读+写之和)可以正常查询到，将表达式放到MS监控里，没有监控数据出现
![image](https://github.com/metersphere/metersphere/assets/104960608/a11d1a04-2caa-4257-89f2-8e28f52e288d)
![image](https://github.com/metersphere/metersphere/assets/104960608/0384ad42-30a1-4422-a572-07a4ad8ecb79)
![image](https://github.com/metersphere/metersphere/assets/104960608/62aaa0c2-d245-41c7-a4a9-591b232d6eb9)

监控语句为:
sum by (instance) (rate(node_disk_reads_completed_total{instance="10.1.13.68:9100"}[5m]))+sum by (instance)(rate(node_disk_writes_completed_total{instance="10.1.13.68:9100"}[5m]))

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.6版本修复。

**Comment by 13290445582** [comment]
v2.10.6已修复。
