### ISSUE TITLE
[BUG]勾选失败停止的情况下，执行完成消息会发送两次

### ISSUE THREAD

**Issue by Joesmj** [metersphere/metersphere#26047]
### MeterSphere 版本

 v2.10.4-lts-a23f75d9

### 使用外置数据库

是

### 问题描述

测试计划中关联了接口、场景，勾选失败停止执行，如果接口靠前存在error触发失败停止操作的情况下，会发送两次消息通知

### 重现步骤

<img width="1392" alt="image" src="https://github.com/metersphere/metersphere/assets/26533041/68fbb855-4378-4f1a-9940-c78636d7da64">
![企业微信截图_8c529004-475d-4759-afdf-558f32b102f0](https://github.com/metersphere/metersphere/assets/26533041/4f145f6b-50da-49df-b6f3-b8b3e1cb9eed)

### 期待的正确结果

只发送一次

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.5-lts未复现该问题，建议升级到最新版本尝试。
