### ISSUE TITLE
[BUG] 功能用例-创建用例，添加前置条件时，英文的""符号，保存后，自动变成了中文的“”符号

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26054]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

 功能用例-创建用例，添加前置条件时，英文的""符号，保存后，自动变成了中文的“”符号

### 重现步骤

1.  功能用例-创建用例，添加前置条件，英文的""符号，保存后，自动变成了中文的“”符号（注意：英文引号中间要有字符）
![image](https://github.com/metersphere/metersphere/assets/103627487/f0a200b6-5def-4775-b6df-2b039e42b281)
![image](https://github.com/metersphere/metersphere/assets/103627487/cc355cb4-760d-48e3-ae56-65f320dec1a3)

**Comment by 13290445582** [comment]
感谢反馈，计划2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
您好，经过排查，是编辑器本身的问题，不是metersphere的问题，链接已附，感谢理解与支持。
https://github.com/hinesboy/mavonEditor/issues/803
