### ISSUE TITLE
[BUG]场景编辑，会修改场景的创建人

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2605]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9
**Bug 描述**
简要描述您碰到的问题
A用户创建的场景，B用户修改了之后，场景的创建人变成了B
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
场景的创建人不应该变
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.9.2 已修复该问题，请升级验证。
