### ISSUE TITLE
[用例管理]支持在一个浏览器里页签里操作（查看、编辑）用例

### ISSUE THREAD

**Issue by shizeweisugars** [metersphere/metersphere#26058]
### MeterSphere 版本

 v2.8.0-ac76fee1

### 联系方式

shizeweisugars@163.com

### 请描述您的需求或者改进建议

支持在一个浏览器里页签里操作（查看、编辑）用例

### 请描述你建议的实现方案

支持在一个浏览器里页签里操作（查看、编辑）用例，而不是现在新开一个浏览器页签，无论从操作上还是资源占用上均不如一个浏览器页签里人性化

**Comment by luty2018** [comment]
这个我们已经排期优化了
