### ISSUE TITLE
[FEATURE]目前测试报告比较简单，建议测试报告支持附件上传功能，丰富报告的内容

### ISSUE THREAD

**Issue by ChangqiaoWang** [metersphere/metersphere#26071]
### MeterSphere 版本

2.10.4-lts

### 请描述您的需求或者改进建议

目前测试报告比较简单，建议测试报告支持附件上传功能，丰富报告的内容

### 请描述你建议的实现方案

添加附件上传目录

**Comment by luty2018** [comment]
附件都是什么内容的？

**Comment by ChangqiaoWang** [comment]
word、pdf、html、execl等文件格式

**Comment by ChangqiaoWang** [comment]
word、pdf、html、execl、tar、winrar等文件格式

**Comment by luty2018** [comment]
这些是用例使用到的附件吗

**Comment by ChangqiaoWang** [comment]
不一定；比如：接口测试，用其他的工具手动进行了测试，生成了一份pdf文档，这时怎么证明这个接口功能被手动测试了呢，就需要把手动测试生成pdf文档附到本轮测试计划的报告中，补充说明接口功能已经手动进行了测试。

**Comment by lvluostudio** [comment]
> 不一定；比如：接口测试，用其他的工具手动进行了测试，生成了一份pdf文档，这时怎么证明这个接口功能被手动测试了呢，就需要把手动测试生成pdf文档附到本轮测试计划的报告中，补充说明接口功能已经手动进行了测试。

这个想法很好，我也感觉目前的测试报告有些单一。不过你说的这种，是不是附着到用例的测试结果中更好一些？ 感觉报告应该统计MS中执行的情况。但是为了丰富报告，或者添加一个可以人工编辑的富文本是否也行？ 主要是用通俗易懂的白话来描述一下测试版本的质量，让更多人能看懂测试报告。
cc: @luty2018

**Comment by luty2018** [comment]
> 

<img width="1471" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/a84deea3-226b-4391-8000-2ff9ed16a679">
报告总结这里已经提供了富文本供用户进行编辑呢。

**Comment by luty2018** [comment]
> 不一定；比如：接口测试，用其他的工具手动进行了测试，生成了一份pdf文档，这时怎么证明这个接口功能被手动测试了呢，就需要把手动测试生成pdf文档附到本轮测试计划的报告中，补充说明接口功能已经手动进行了测试。

了解， 但是很好奇为什么接口测试不在平台的测试计划里面执行呢？

**Comment by lvluostudio** [comment]
> > 
> 
> <img alt="image" width="1471" src="https://user-images.githubusercontent.com/36292514/260651533-a84deea3-226b-4391-8000-2ff9ed16a679.png"> 报告总结这里已经提供了富文本供用户进行编辑呢。

赞！就是期望有个这样的。谢谢回复！

**Comment by ChangqiaoWang** [comment]
> > 不一定；比如：接口测试，用其他的工具手动进行了测试，生成了一份pdf文档，这时怎么证明这个接口功能被手动测试了呢，就需要把手动测试生成pdf文档附到本轮测试计划的报告中，补充说明接口功能已经手动进行了测试。
> 
> 了解， 但是很好奇为什么接口测试不在平台的测试计划里面执行呢？

接口测试可以在平台里执行，例如像一些接口安全测试，使用burpsuite测试了，所以要上传测试报告。

**Comment by luty2018** [comment]
<img width="724" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/368afb2e-0428-436d-b426-4ca7f7494a2b">
能否通过上传外部链接的方式来覆盖呢， 这里再增加附件上传的入口，可读性和展示都不太好
