### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by luowei190604** [metersphere/metersphere#26077]
### MeterSphere 版本

v2.9.1

### 联系方式

MeterSphere交流群60，姚，376937872@qq.com

### 请描述您的需求或者改进建议

在做并发梯度压测时，结果建议展示每个梯度的压测结果，以便查看最优的并发和TPS；

或者你们的支持人员 建议在 开源版本中的事务名放开${threadNum} 变量

**Comment by luty2018** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/26081
