### ISSUE TITLE
[BUG]当json串内含有转义字符时，打开 json-schema 开关，json 串会在转义字符处被自动分割

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#26087]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

当json串内含有转义字符时，打开 json-schema 开关，json 串会在转义字符处被自动分割

### 重现步骤

接口定义-请求参数选择 JSON ，输入 
{
    "departmentCode": "H\\",
  "3EV\\": 0
}

切换 json-schema 开关，json 被自动切割。

**Comment by shenkaibo** [comment]
[json内有转义字符.webm](https://github.com/metersphere/metersphere/assets/30038088/7d9b53b3-cc8a-4cee-b123-b40628e6cf45)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.5-lts未复现该问题，请确认是否为发布的最新版本，如不是请升级尝试。
<img width="870" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/96efccba-e5fa-449f-a374-abcabd5b7f17">
<img width="829" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/70d764ad-1e39-4bc1-a2ec-80ea21c351fe">

**Comment by shenkaibo** [comment]
v2.10.5-lts 无此问题
