### ISSUE TITLE
SQL类型的断言，针对HTTP请求能够添加SQL查询断言

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#2608]
**请描述您的需求或者改进建议.**
我司系统对于接口测试的数据，无论是查询数据还是写入数据，都必须从数据库中进行查询后比对校验。在MeterSphere中测试方式如下：
1.提取HTTP接口参数
2.添加SQL请求，并保存参数
3.添加脚本断言，判断SQL和HTTP请求提取值

能否将三个步骤融合为一个步骤

**请描述你建议的实现方案**
能够将HTTP请求用例和SQL请求打包为一个用例，在场景中可以统一引用。支持直接SQL断言方式，可以完整的对一个接口进行请求后采用SQL断言

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，暂时不考虑该需求，后续会再调研一下是否支持。
