### ISSUE TITLE
[BUG]【接口测试】mock后置脚本的字符串数据过长，增加的数据与光标的位置会出现错位

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26080]
### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

Mock后置脚本中的字符串长度超过5000，光标会出现错位问题，增加的数据不在光标所在位置

### 重现步骤

1.创建一个Mock
2.在 Mock中增加后置脚本
3.在脚本中新增数据

### 期待的正确结果

后置脚本数据过长时，不会出现错位问题

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/05a89055-533e-4acc-8e94-4e04e7ea8733)
![image](https://github.com/metersphere/metersphere/assets/45531073/5eec90fa-c5e5-46f0-8c01-7e21b1a71e01)
[报文.txt](https://github.com/metersphere/metersphere/files/12298526/default.txt)

**Comment by fit2-zhao** [comment]
目前这个组件确实存在这个问题，后续可以参照 https://github.com/chairuosen/vue2-ace-editor/issues/97 ；这种字符比较多的建议格式化换行就正常了。
