### ISSUE TITLE
函数公共库

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#2609]
**请描述您的需求或者改进建议.**

目前在MeterSphere支持前后置脚本，断言脚本等，但是在不同的接口用例，场景中都需要填写直接脚本代码，能否支持脚本引用方式，减少脚本的冗余度

**请描述你建议的实现方案**
建设函数公共库，解决不同用例、场景中的脚本引用复制问题

**Comment by xulinde** [comment]
感谢反馈，我们先内部讨论下该需求
