### ISSUE TITLE
[BUG]请求体里引用变量，变量外不加引号，没办法转json-schema了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26099]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

请求体里引用变量，变量外不加引号，报错json格式错误，没办法转json-schema了

### 重现步骤

1.在json-schema模式下编辑请求体，设置一个integer类型变量
![image](https://github.com/metersphere/metersphere/assets/88763608/23c0292b-fe22-4d08-ba36-574067b1fba8)
2.将json-schema转为json
![image](https://github.com/metersphere/metersphere/assets/88763608/0d0dd400-0189-4749-b049-adbc86072894)
3.再将json转为json-schema，由于变量外没有引号，报格式错误了
![image](https://github.com/metersphere/metersphere/assets/88763608/07a2c4e7-d7d0-4de2-b42b-a966add4f490)

### 期待的正确结果

应该可以转换，不要校验变量外有没有引号，校验的话，对于数字类型变量很不友好，用户就没法使用json-schema功能了

**Comment by liqiang-fit2cloud** [comment]
需求的话提Feature。
