### ISSUE TITLE
[BUG]【UI测试】输入操作-小 i 提示里，html语法没有正常显示成常见内容。如 &quot 字符应该显示成 " 才对。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26095]
### MeterSphere 版本

v2.10.4

### 使用外置数据库

否

### 问题描述

【UI测试】输入操作-小 i 提示里，html语法没有正常显示成常见内容。如 &quot 字符应该显示成 " 才对。

### 重现步骤

【UI测试】输入操作-小 i 提示里，html语法没有正常显示成常见内容。如 &quot 字符应该显示成 " 才对。
![image](https://github.com/metersphere/metersphere/assets/104960608/2e9db84a-7f4e-4f70-9b00-a7400b53a601)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
