### ISSUE TITLE
[FEATURE] 希望增加免登陆或者使用单点登录查看报告

### ISSUE THREAD

**Issue by assilzm** [metersphere/metersphere#261]
**请描述您的需求或者改进建议.**
希望增加免登陆或者使用单点登录查看报告，方便报告集成到看板或者jenkins中

**请描述你建议的实现方案**
可以考虑通过对api/report免登陆验证或者能通过某个接口返回html格式的报告来实现。

**Comment by pcc426** [comment]
支持~或者至少在jenkins的console_output里加一个URL直接跳到MS查看对应的接口测试报告，如图
![图片](https://user-images.githubusercontent.com/11419548/103254084-edf80380-49be-11eb-8269-67c49ac598ea.png)

**Comment by xulinde** [comment]
最新版本插件已支持该功能
