### ISSUE TITLE
[FEATURE]建议UI测试中变量值为空时，统一标识为null

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26103]
### MeterSphere 版本

v2.10.5-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

UI测试中变量值为空时，统一表示方法，比如变量为空值时，值都为null。
希望可以统一一下，不然客户在流程控制中判断变量为空的时候很难知道怎么操作

### 请描述你建议的实现方案
目前UI测试里空值有多种表示方式：
1.在UI测试中，如果在场景变量里定义一个空的变量，这里的空值为null
<img width="718" alt="e213736a0f5f413611673b201634941" src="https://github.com/metersphere/metersphere/assets/88763608/52305296-17fc-4a7b-bf0d-1466bb448abc">
<img width="868" alt="39c4f2dd8d12541fc67fc0ca36f9665" src="https://github.com/metersphere/metersphere/assets/88763608/719b5c66-225f-43e8-b060-834e095f8a34">
2.在后置操作-参数提取中，如果表达式不对，没有该元素，那么这个提取的变量值为"${变量名}"，这里的空值为"${变量名}"
![image](https://github.com/metersphere/metersphere/assets/88763608/4a6178cf-77f2-490b-ba9c-3d06a8e94256)
<img width="622" alt="a06c46efc66a2ad2e7ea093943a47e8" src="https://github.com/metersphere/metersphere/assets/88763608/3c47965b-d5c1-4605-864e-92be65d62c1b">
<img width="903" alt="9601089f802d0e0c42b95774dfce0cc" src="https://github.com/metersphere/metersphere/assets/88763608/0e3d8b36-5199-47b1-b184-3dd5bbc7c8ed">
3.在后置操作-参数提取中，如果表达式正确，但是没有对应的值可以提取，这里的空值为""
比如表达式对的，但是这个元素没有text文本值，而我选择提取文本值，那提取的变量值就会是""
<img width="923" alt="e3e15c2fc8c9f23dceef7b2ba6414fb" src="https://github.com/metersphere/metersphere/assets/88763608/e325e193-804b-4498-9954-78753db00cef">

**Comment by Hyyfit** [comment]
一共有三种情况：
第一种覆盖的是 元素存在，值为 null
第二种覆盖的是 元素存在，值不存在 ，返回 “”
第三种覆盖的是 元素不存在，返回'${变量名}'
