### ISSUE TITLE
[BUG]校验数据库时报错，连接数据库失败

### ISSUE THREAD

**Issue by Helena966** [metersphere/metersphere#26105]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

添加数据库配置-校验数据库连接时报：Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
![09dfc1735698eb637abce5ec908018d](https://github.com/metersphere/metersphere/assets/66630660/b44a1371-2651-4e2b-b736-db44f73ded51)

### 重现步骤

1.项目设置-项目环境
2.创建环境-数据库配置
![image](https://github.com/metersphere/metersphere/assets/66630660/eac361d6-86b2-4efa-ab0a-c2c2955dfaad)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.5-lts未复现该问题，建议升级尝试。

**Comment by Helena966** [comment]
> 您好，感谢反馈！最新版本v2.10.5-lts未复现该问题，建议升级尝试。

必须升级才能解决这个问题吗？我们暂时没有升级的想法

**Comment by zrfit** [comment]
您好，v1.20版本在您的版本之后又迭代了10多个版本，除安全漏洞外无特殊情况不再进行版本更新，都是基于最新版本验证，后续我们主要维护v2.0版本，建议您升级到最新稳定版本，如不升级，请自行排查下数据库url地址和数据驱动等可能造成链接失败的情况，感谢理解。
<img width="922" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/68f86a0b-b73d-4193-95f9-8183a7fafad0">
