### ISSUE TITLE
[BUG]v2.10.5-lts-0ba6e94d版本测试计划两个场景用例放到一个测试计划，选择串行 执行的时候第二个用例无法正常运行

### ISSUE THREAD

**Issue by AnneXie01** [metersphere/metersphere#26104]
### 联系方式

17372609288

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

1、新建2个场景用例，test-1和test-2,两个场景内都只有1个脚本 python语言  
import time
time.sleep(2)
确定单独执行场景用例pass
2、新建一个测试计划 将2个用例加入
3、手动点击测试计划执行（串行）
期望用例很快执行完成 
但实际只有一个运行完成
另一个一直pending 或running状态

### 重现步骤

1、新建2个场景用例，test-1和test-2,两个场景内都只有1个脚本 python语言  
import time
time.sleep(2)
确定单独执行场景用例pass
2、新建一个测试计划 将2个用例加入
3、手动点击测试计划执行（串行）
期望用例很快执行完成 
但实际只有一个运行完成
另一个一直pending 或running状态

### 期待的正确结果

1、新建2个场景用例，test-1和test-2,两个场景内都只有1个脚本 python语言  
import time
time.sleep(2)
确定单独执行场景用例pass
2、新建一个测试计划 将2个用例加入
3、手动点击测试计划执行（串行）

期望用例很快执行完成

**Comment by AnneXie01** [comment]
我的版本是由低版本升级上来的 正在用的环境稳定复现，新搭建的metersphere 没有任何异常

**Comment by 13290445582** [comment]
您好，从哪个版本升级上来的？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
