### ISSUE TITLE
默认缺陷模板添加自定义字段下列选项的内容中包含[]时，导入缺陷会报错

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26107]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

使用默认模板，添加自定义字段的内容中包含[]时，导入缺陷时会报错

### 重现步骤

1. 添加自定义字段，类型选择单项下拉列表，下拉选项中的内容中包含了[]，保存好模板；
2. 下载最新模板，自定义字段中，填写好选择单项下拉列表的内容；
3. 导入缺陷时，报错：syntax error, pos 2, line 1, column 3[b1234567890]

### 期待的正确结果

导入缺陷成功

### 相关日志输出

```shell
无
```

### 附加信息

![1691657063895](https://github.com/metersphere/metersphere/assets/50016789/08ade8e4-2fb8-4c7f-a1a2-9e143bab14f5)
![image](https://github.com/metersphere/metersphere/assets/50016789/bcbef8f1-762d-4454-85e2-347fdeb37601)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复
