### ISSUE TITLE
[BUG] csv变量的设置太少, 导致每一个请求都使用一次csv变量, 即使场景中的请求没有使用csv变量, csv也会向下取

### ISSUE THREAD

**Issue by Mister-Qin** [metersphere/metersphere#26117]
### 联系方式

shuang_fa@126.com

### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

创建的场景添加2个不访问csv变量的请求, 一个循环访问csv变量的请求, 运行时, 每一个请求都会导致csv变量向下取值, 即使前面2个请求不使用csv变量
![image](https://github.com/metersphere/metersphere/assets/114208922/b54e51c1-02ea-4e37-9e62-aa9c6c3cbb39)

### 重现步骤

创建的场景添加2个不访问csv变量的请求, 一个循环访问csv变量的请求

### 期待的正确结果

只有第三个循环请求使用csv变量

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.5-lts未复现该问题，建议升级尝试。
<img width="930" alt="image" src="https://github.com/metersphere/metersphere/assets/75963100/f03bae4e-b192-43de-98d8-2dd88278ad6f">
