### ISSUE TITLE
[QUESTION]The following artifacts could not be resolved: io.metersphere:domain:jar:2.6

### ISSUE THREAD

**Issue by wanglewang** [metersphere/metersphere#26115]
### 请描述您的问题

编译打包metersphere-platform-plugin时：找不到jar包The following artifacts could not be resolved: io.metersphere:domain:jar:2.6

**Comment by fit2-zhao** [comment]
可以参照 https://github.com/metersphere/metersphere/blob/v2.10/build.md 编译后，相关jar版本统一就可以了。

**Comment by wanglewang** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project domain: Fatal error compiling: 无效的标记: --release -> [Help 1]

执行命令会报错
./mvnw clean install -pl framework,framework/sdk-parent,framework/sdk-parent/domain,framework/sdk-parent/sdk,framework/sdk-parent/xpack-interface

**Comment by Get-lzh** [comment]
我也遇到同样的提示，请问怎么解决呀

**Comment by Get-lzh** [comment]
![image](https://github.com/metersphere/metersphere/assets/58059353/60d8c47e-746c-4f3f-af11-0a38991c0d05)

**Comment by wanglewang** [comment]
设置命令行的maven和以及setting用的jdk，保证满足文档要求



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 15:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [metersphere/metersphere] [QUESTION]The following artifacts couldnot be resolved: io.metersphere:domain:jar:2.6 (Issue #26115)
