### ISSUE TITLE
[BUG] 测试跟踪-缺陷管理。jira上面的模板可以关联到事务，但是同步模板ms关联不到，没有这个关联事务字段选项。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#26126]
### MeterSphere 版本

2.10.3-lts

### 使用外置数据库

否

### 问题描述

测试跟踪-缺陷管理。jira上面的模板可以关联到事务，但是同步模板ms关联不到，没有这个关联事务字段选项。

### 重现步骤

1、项目管理对接了jira，勾选使用jira木模板
2、测试跟踪-缺陷管理。jira上面的模板可以关联到事务，但是同步模板ms关联不到，没有这个关联事务字段选项。
![image](https://github.com/metersphere/metersphere/assets/43202800/6c625ab0-76a8-4f32-8919-5a084644925f)

3、jira上面开启 关联事务如图：自定义字段-事务关联。已反馈给建星，说是可以复现
![3868eadb3359bec55fc27b29b54794e](https://github.com/metersphere/metersphere/assets/43202800/e7db76f5-97bf-4cbd-afcf-b879a2445f67)
![image](https://github.com/metersphere/metersphere/assets/43202800/c756484d-d623-4cfa-b37d-69c07475d6a0)

### 期待的正确结果

使用jira模板，应该可以同步关联事务字段

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复。

**Comment by 13290445582** [comment]
v2.10.7已修复。
