### ISSUE TITLE
[BUG]性能测试：多场景脚本测试执行，只有一个场景正常执行且没有报错，其他场景的步骤全部报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#2612]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
性能测试：多场景脚本测试执行，只有一个场景正常执行且没有报错，其他场景的步骤全部报错
**Bug 重现步骤**
1.  性能测试上传三个脚本
2. 执行只有一个场景正常执行且没有报错
3. 单个执行都可执行成功
4. 
**期待的正确结果**
正确情况下应该是什么样的？
多个场景执行，步骤都成功
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/83771182/117542011-4b751e80-b049-11eb-82ce-c8e4e50d361c.png)

**Comment by zyyfit** [comment]
您好，同样的脚本在jmeter里的执行结果是什么样的呢？

**Comment by huangxine** [comment]
在jmeter里面支持是没有问题的，执行成功

**Comment by wangzhen-fit2cloud** [comment]
具体的错误内容是什么呢？
