### ISSUE TITLE
需要拉取 metersphere, ms-jmeter-core、jmeter-plugins-webdriver三个服务代码，并切换到同一分支。

### ISSUE THREAD

**Issue by wanglewang** [metersphere/metersphere#26139]
### 请描述您的问题

jmeter-plugins-webdriver只有4.9和4.10两个分支，怎么和其他两个服务保持同一分支

**Comment by wanglewang** [comment]
./mvnw clean install -pl framework,framework/sdk-parent,framework/sdk-parent/domain,framework/sdk-parent/sdk,framework/sdk-parent/xpack-interface
执行命令会报错：[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project domain: Fatal error compiling: 无效的标记: --release -> [Help 1]

**Comment by wanglewang** [comment]
没问题了

**Comment by liuruibin** [comment]
此工程版本和webdriver版本保持一致
