### ISSUE TITLE
[BUG]性能测试保存并执行后，提示测试处于开始状态，但会出现get report result error报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#2613]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
性能测试保存并执行后，提示测试处于开始状态，但会出现get report result error报错
**Bug 重现步骤**
1.  性能测试保存并执行后
2. 提示测试处于开始状态，但会出现get report result error报错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
不会提示 get report result error
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/83771182/117542384-018d3800-b04b-11eb-93cc-e376d3aeff7c.png)

**Comment by zyyfit** [comment]
您好，是必现的吗？能描述一下具体操作步骤吗？这边没有复现呢

**Comment by yaoyi111** [comment]
是必现的，三个脚本见附件，执行时需要添加jar包。



***@***.***
 
发件人： zyyfit
发送时间： 2021-05-12 16:57
收件人： metersphere/metersphere
抄送： yaoyi111; Author
主题： Re: [metersphere/metersphere] [BUG]性能测试保存并执行后，提示测试处于开始状态，但会出现get report result error报错 (#2613)
您好，是必现的吗？能描述一下具体操作步骤吗？这边没有复现呢

**Comment by huhui** [comment]
遇到同样问题，请问如何解决
