### ISSUE TITLE
[BUG]TAPD的缺陷优先级同步到MS时，当优先级为无关紧要时，在MS上是英文

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26130]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

TAPD的缺陷优先级同步到MS时，当优先级为无关紧要时，在MS上是英文

### 重现步骤

1.设置TAPD里某个缺陷优先级为无关紧要
![image](https://github.com/metersphere/metersphere/assets/88763608/f650a17b-8672-4eb5-91df-9e9ff62cbe39)
2.在MS上点击同步缺陷，优先级展示的是英文
![image](https://github.com/metersphere/metersphere/assets/88763608/be1fc781-1275-44fe-91c8-f0b5392d990c)

### 期待的正确结果

应该展示中文

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.6-lts优化。
