### ISSUE TITLE
[BUG]  oracle 数据库表字段为number类型，在MeterSphere上用 sql 查询，查询数据的值不对

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26135]
### MeterSphere 版本

v1.20.5-lts

### 使用外置数据库

否

### 问题描述

oracle 数据库查询：

 
![36481691747184_ pic (1)](https://github.com/metersphere/metersphere/assets/33945037/29f68289-50c5-4bd1-a4ef-2138e4842967)

MS查询出来的数据：

![36491691747199_ pic (1)](https://github.com/metersphere/metersphere/assets/33945037/8130c005-645a-48f3-8cbf-72234fdcd1ca)

### 重现步骤

同上

**Comment by zrfit** [comment]
您好，感谢反馈！在jmeter上执行返回数据正确吗？

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
