### ISSUE TITLE
[BUG] 导入swagger接口，多次操作不会创建定时任务

### ISSUE THREAD

**Issue by davidhhuan** [metersphere/metersphere#2614]
**MeterSphere 版本**
v1.9.1

**Bug 描述**
导入swagger接口，多次操作不会创建定时任务

**Bug 重现步骤**
注意！以下操作不能都不能强制刷新浏览器，要不然不会重现问题

1，第一次已经正常导入了swagger接口
2，问题在于，第二次打开导入的时候，由于没有重置那两个校验，就变成了重用前面的表单数据，导致第二次导入swagger的定时任务不会创建，如图所示
![image](https://user-images.githubusercontent.com/449399/117564601-6d20e500-b0df-11eb-835e-359fd1448c47.png)
![image](https://user-images.githubusercontent.com/449399/117564650-b4a77100-b0df-11eb-928f-059d34abca9f.png)

**期待的正确结果**
每次重新打开导入的弹窗，都应该重置里面的按钮状态

**Comment by zyyfit** [comment]
您好，这边没有复现呢，我换了一个新的地址，两个定时任务都创建了
