### ISSUE TITLE
[BUG]部署完成后，重启时system-setting启动不了，报错数据库连接失败

### ISSUE THREAD

**Issue by Racheljia1989** [metersphere/metersphere#26144]
### MeterSphere 版本

v2.10.5-lts-b2

### 使用外置数据库

否

### 问题描述

<img width="929" alt="image" src="https://github.com/metersphere/metersphere/assets/43464921/a7a694ea-1ae8-42c3-ab86-ac08043706ab">
wsl的ubuntu 20.04操作系统，部署成功。每次关闭wsl后重启metersphere都报错system-setting启动不了，看doker日志是连接不上mysql，但手动连接mysql正常。

### 重现步骤

wsl的ubuntu 20.04操作系统，部署成功。每次关闭wsl后重启metersphere都报错system-setting启动不了，看doker日志是连接不上mysql，但手动连接mysql正常。

**Comment by liqiang-fit2cloud** [comment]
看看wsl关闭之后网络是不是发生了变化，如果发生了变化重启docker和msctl reload试试。

**Comment by linsihao7788** [comment]
我也是该问题，请问要如何解决呢？
