### ISSUE TITLE
[BUG]【测试跟踪-缺陷管理-复制】B用户基于A提交的缺陷复制并修改内容后，B用户提交的缺陷“创建人”显示的是A用户

### ISSUE THREAD

**Issue by tomseanmy** [metersphere/metersphere#26143]
### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

B用户基于A提交的缺陷复制并修改内容后，B用户提交的缺陷“创建人”显示的是A用户

### 重现步骤

使用A账号创建一条缺陷，再使用B账号复制这条缺陷并添加新的内容，B账号复制的这条缺陷创建人是A。

### 期待的正确结果

创建人应该是B账号

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
