### ISSUE TITLE
[BUG]功能用例-》脑图-》修改脑图，移动字节点到其他节点时，展示错误

### ISSUE THREAD

**Issue by no-42** [metersphere/metersphere#26157]
### 联系方式

756982469@qq.com

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

移动字节点位置到未被展开过的模块后时，模块中原本的子节点不会被展开，且全部变成了空节点，点击折叠展开后，移动过去的字节点消失了，且没有恢复到移动前的状态

### 重现步骤

移动字节点位置到未被展开过的模块后时，模块中原本的子节点不会被展开，且全部变成了空节点，点击折叠展开后，移动过去的字节点消失了，且没有恢复到移动前的状态

### 期待的正确结果

移动后，模块的节点应该正确展开，且移动的节点数据应该被保存到模块后，且展开后不会消失

### 附加信息

https://github.com/metersphere/metersphere/assets/63759073/82e518b4-65d6-4ab9-be7b-14ffca395548

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.6-lts修复。
