### ISSUE TITLE
[BUG]接口自动化场景步骤较多时，展开步骤和步骤的响应内容后上下滑动，页面会不受控制滑动并且自动收起响应内容

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#26158]
### 联系方式

shimengqiao

### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

接口自动化场景步骤有十多个，展开步骤和步骤的响应内容后上下滑动，页面会不受控制滑动并且自动收起响应内容

### 重现步骤

1、创建一个接口自动化场景，复制单接口的用例，复制超过10个步骤
2、展开步骤和步骤的响应内容
3、在页面上下滑动
可以看下面视频
[屏幕录制2023-08-14 17.10.22.mov.zip](https://github.com/metersphere/metersphere/files/12333304/2023-08-14.17.10.22.mov.zip)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts版本优化。

**Comment by hslzyd** [comment]
这个太影响接口场景编辑了，页面、光标总是乱跳，写个后置脚本写一半滚动一下页面直接给你跳没了，太崩溃了

**Comment by zrfit** [comment]
您好，场景详情步骤逻辑复杂，改动影响大，所以比较谨慎，目前没有较好的处理方案， 计划v2.10.8-lts先把自动聚焦去掉，从而解决该问题，感谢您的理解和支持，给您带来不便，深表歉意。
目前建议步骤较多时，可通过批量折叠步骤将所有步骤收起，只点击展开编辑单个步骤，其它步骤不展开，修改步骤后及时点击保存。

**Comment by fit2cloud-yaochunrong** [comment]
请问您说的“目前建议步骤较多时，可通过批量折叠步骤将所有步骤收起，只点击展开编辑单个步骤，其它步骤不展开，修改步骤后及时点击保存。”  是指自动收起目前无法没法做修改是嘛？

2.10.8抖动也还有有的，只是轻微了一些，但是还是有明显的 不符合鼠标操作的多余抖动，看下还能改进嘛

**Comment by youliyuan-fit2cloud** [comment]
你好，抱歉才回复，建议升级到最新版本尝试是否还存在。
