### ISSUE TITLE
[BUG]测试计划页面中不能查询到已经归档的测试计划

### ISSUE THREAD

**Issue by lvluostudio** [metersphere/metersphere#26156]
### 联系方式

wingle@qq.com

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

找不到可以查看已经归档的测试计划的地方，测试计划页面中不能查询到已经归档的测试计划。虽然提供筛选，但是查询结果依然为空。
![image](https://github.com/metersphere/metersphere/assets/140152970/e079f7f2-79a4-43d2-9129-cc4642597443)

### 重现步骤

1. 将某个测试计划的状态修改为归档
![image](https://github.com/metersphere/metersphere/assets/140152970/017f6b9c-14a9-4451-924d-1c7c5cb14373)
2. 然后再想查看刚才的计划，找不到哪里可以查询了

### 期待的正确结果

能提供查看归档计划的功能，在测试计划页面能筛选出归档的计划

**Comment by zrfit** [comment]
您好，感谢反馈！高级搜索-筛选归档计划v2.10.6-lts修复，可先在计划列表通过状态字段进行筛选归档计划。

**Comment by lvluostudio** [comment]
已确认，可以通过勾选列表中的状态字段来查看已归档测试计划
![image](https://github.com/metersphere/metersphere/assets/8476051/0ac4354c-a45c-4a9f-bf7f-537fc890e7d2)
