### ISSUE TITLE
[BUG]【UI测试】当alert弹窗内容有断言时，点击弹窗操作会显示成失败，但实际是成功的。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26161]
### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

【UI测试】当alert弹窗内容进行断言时，点击弹窗操作会显示成失败，但是通过看vnc，是点击了的。将断言关闭掉，点击弹窗操作会显示成功。

### 重现步骤

【UI测试】当alert弹窗内容进行断言时，点击弹窗操作会显示成失败，但是通过看vnc，是点击了的。
![e7528e23852a7b7c21c85111b424659](https://github.com/metersphere/metersphere/assets/104960608/2ebc6339-7e37-4835-a495-2730da960d9b)
![7073dbe7857c3c215b3d61dbb48c924](https://github.com/metersphere/metersphere/assets/104960608/4243c4f6-8872-4c84-9756-31efcdd1826b)
将断言关闭掉，点击弹窗操作会显示成功。
![65143fb5f1893a05cd8b23399e6ee58](https://github.com/metersphere/metersphere/assets/104960608/96201f86-b242-4b90-9f60-48be38ded254)
![de3efde1c27cd8d6a7f0122430d9e3d](https://github.com/metersphere/metersphere/assets/104960608/c087875f-5ebb-444b-99de-5548ac3098ab)

**Comment by zrfit** [comment]
您好，这个问题之前沟通过呢，已知问题，弹框操作的上一步鼠标点击不要截图，否则影响弹框，去掉上一步的截图，弹框操作断言正常，v3优化。
<img width="1283" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/920f6f46-4928-403c-852e-4b9e3d2f58f3">

**Comment by 2lipan** [comment]
这与截图有啥关系？同一场景运行2次，场景内容都一样，都是截图状态，唯一不一样的地方就是 断言是开启/关闭 状态。

**Comment by zrfit** [comment]
1、目前已知问题是alert弹框的上一步骤有截图，弹框操作就会失败、断言也会失败。
2、弹框是alert弹框吗？
3、弹框中的文本是什么？
4、断言内容是什么？
方便的话私发下你的场景文件看看。

**Comment by 2lipan** [comment]
确实是alert弹窗，弹窗文本内容是这，断言也是这。客户私有云环境，无法导出场景，但是可以远程会议看看
![1692080869723](https://github.com/metersphere/metersphere/assets/104960608/26a09150-6434-4b6f-83ab-9143b7fade2b)
