### ISSUE TITLE
[BUG]  小数正则断言问题

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26170]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

正则断言问题
<img width="1371" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/19e1013b-43c9-4fa9-894f-81b6527f1633">

### 期待的正确结果

断言正常

**Comment by zrfit** [comment]
您好，感谢反馈！metersphere后端调用的jmeter，目前暂时和jmeter保持一致。
<img width="1147" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/1ab18deb-8c6f-436a-a5b4-cd21a005578f">
可以直接用jsonpath推荐的断言进行断言，可成功。

**Comment by sss903065212** [comment]
ok
