### ISSUE TITLE
[BUG]Jira集成后，提交缺陷时报错，必现问题。配置集成项目时已勾选使用Jira缺陷模版复选框。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#26179]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.4lts

### 使用外置数据库

否

### 问题描述

Jira集成后，提交缺陷时报错，必现问题。配置集成项目时已勾选使用Jira缺陷模版复选框。错误日志见附件，Jira版本8.13.11
![lQLPJwyOAISPrhjNA2vNBzmwQRICgRVFk90Ez41eiwAQAA_1849_875](https://github.com/metersphere/metersphere/assets/83771182/e7a85206-c1ec-465f-b8d7-4fe540587869)
[MS报错信息.txt](https://github.com/metersphere/metersphere/files/12341706/MS.txt)

### 重现步骤

Jira集成后，提交缺陷时报错，必现问题。配置集成项目时已勾选使用Jira缺陷模版复选框。

**Comment by 13290445582** [comment]
你好，使用的jira插件是什么版本，是最新的吗？请提供下所使用的的jira配置的模版，帮助我们模拟复现，感谢。

**Comment by 13290445582** [comment]
已经提供最新jira插件使用，不再出现该问题，issue关闭，后续有问题请重新提issue，感谢理解与支持。
