### ISSUE TITLE
[BUG]功能用例导入 excel 报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26173]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

功能用例导入 excel 报错

### 重现步骤

1. 功能用例导入 excel 报错(excel文件私发）
![image](https://github.com/metersphere/metersphere/assets/103627487/64694204-836d-474d-9241-b982eec32dd4)

**Comment by zrfit** [comment]
您好，感谢反馈！企业微信已联系您，请发下导入文件。

**Comment by zrfit** [comment]
您好，已复现，导入文件的所属模块路径最前面缺少/，导致导入失败，计划v2.10.6-lts优化，可先加上/，则可导入成功。
