### ISSUE TITLE
[BUG]调用资源池执行失败，请检查资源池是否配置正常

### ISSUE THREAD

**Issue by Helena966** [metersphere/metersphere#26187]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

调试接口报错：调用资源池执行失败，请检查资源池是否配置正常
![1BD07172-08A6-4ed1-ABCA-4770823B70C1](https://github.com/metersphere/metersphere/assets/66630660/50eb2fdd-f4e9-425f-9873-1cc1b44169da)
k8s上部署的报的这个

### 重现步骤

【接口定义】-【快捷调试】 发起一个http请求

**Comment by zrfit** [comment]
您好，感谢反馈！请检查下您的系统设置-系统参数设置-基本设置-当前站点url是否正确。参考同类问题#25960、#25897、#25847、#24833。

**Comment by Helena966** [comment]
> 您好，感谢反馈！请检查下您的系统设置-系统参数设置-基本设置-当前站点url是否正确。参考同类问题#25960、#25897、#25847、#24833。

问题已解决，感谢感谢
