### ISSUE TITLE
[FEATURE] 接口自动化引用 CASE 应该禁止添加断言

### ISSUE THREAD

**Issue by hzhwyh0116** [metersphere/metersphere#26192]
### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

接口自动化引用 CASE 应该不能添加断言

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/89765365/c3d0c3fb-546d-42d6-a874-90f59d0df136)

**Comment by luty2018** [comment]
接口case和接口自动化不一样， 它是比较独立且没有什么业务流程在里面的， 所以case应用在不同的场景里面时，断言和提取参数都可能不一样， 为了提高case的复用性， 所以这里没有做限制。
