### ISSUE TITLE
[BUG] 循环控制器下的条件控制器在调试结束后一直显示测试中

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26191]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/40912189/439dfeeb-61b2-4f05-a73c-988b774d14d5

### 重现步骤

1、新建一个场景添加循环控制器（循环次数随意）
2、在循环控制器下添加条件控制器
3、在条件控制器下添加随意一个请求

### 期待的正确结果

当调试结束时条件控制器的「测试中」显示正确状态

**Comment by zrfit** [comment]
您好，未复现该问题，在v2.10.5-lts验证返回结果状态更新正常。必现吗？方便的话导出场景企业微信私发我下。
<img width="1044" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/ed85948e-4a81-4e2f-a3b3-2a5cfeafb049">

**Comment by sss903065212** [comment]
@zrfit 企业微信已发送

**Comment by zrfit** [comment]
已复现，条件控制器引用的变量是计数器类型的场景变量导致，计划v2.10.7-lts修复。
