### ISSUE TITLE
[BUG]创建缺陷页面关联用例列表显示异常

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#26207]
### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

<img width="1438" alt="image" src="https://github.com/metersphere/metersphere/assets/46042812/11555599-aa74-41e1-9bdf-ad17960273d9">

### 重现步骤

1、常见缺陷列表
2、关联用例
3、切换关联用例/附件TAB页面，然后返回关联用例页面
4、操作栏显示多了一条横线

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
