### ISSUE TITLE
断言规则选择不包含的时候，实际上包含有，结果还是断言成功

### ISSUE THREAD

**Issue by keybersan** [metersphere/metersphere#26213]
### 联系方式

954106360@qq.com

### MeterSphere 版本

1.12

### 使用外置数据库

否

### 问题描述

断言规则选择不包含的时候，无论是否包含该值，结果都是断言成功

### 重现步骤

1、场景模式下
2、接口调用
3、设置断言
4、断言规则不包含接口出现的值。
5、调试 显示断言成功。
6、更换断言不存在的另外一个值，
7、调试 显示断言成功。

### 期待的正确结果

期望不包含某个值时，断言成功。

### 附加信息

![Snipaste_2023-08-16_13-49-08](https://github.com/metersphere/metersphere/assets/27944820/87de822c-9971-4695-aa86-512141bfc9cf)
![Snipaste_2023-08-16_13-49-31](https://github.com/metersphere/metersphere/assets/27944820/c0bc258d-7518-4279-83a7-dcceec59b870)
![Snipaste_2023-08-16_13-59-42](https://github.com/metersphere/metersphere/assets/27944820/a62d54ae-5ad0-48f9-969c-459dd78dce96)

**Comment by fit2-zhao** [comment]
$.data[\*].xxx 如果要验证具体某条把 * 换成具体index ；否则 * 是任意匹配自然都能成功，从你的断言里面就能看出来有 .22 和 .21。

**Comment by keybersan** [comment]
如果我需要遍历$.data数组下的某个属性值，要如何填写表达式呢
