### ISSUE TITLE
[BUG]  MySQL或Oracle 查询，按存储结果存储，后置脚本通过info.log() 打印结果对象，控制台中显示的结果字段顺序跟数据库中的顺序不一致

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26221]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

1. 创建mysql 链接。
2. 按存储结果存储。
3. 后置脚本中打印结果。
4. 执行
5. 观察控制台日志，打印结果的字段顺序跟表字段顺序不一致，之前版本是好的。
<img width="922" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/f7078955-58f9-4e9e-a120-3f1b061d0ff7">
<img width="984" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/0bcff599-9940-4cef-aec3-9e792be3e991">

### 重现步骤

同上

**Comment by 13290445582** [comment]
感谢反馈，并非是缺陷，默认log输出上下文变量平台并不会去调整相关输出字符顺序，对于JSON而言顺序并不影响使用。
