### ISSUE TITLE
V2.10版本本地开发环境部署时，io.metersphere:domain:jar:main依赖包找不到

### ISSUE THREAD

**Issue by Get-lzh** [metersphere/metersphere#26237]
### 请描述您的问题

https://github.com/metersphere/metersphere/tree/main/framework/sdk-parent/domain
这个链接打开是404

**Comment by luty2018** [comment]
本地开发需要自行研究源码，谢谢。

**Comment by Get-lzh** [comment]
我想知道的是这个domain包的依赖在哪，之前看到说是这个链接，目前链接https://github.com/metersphere/metersphere/tree/main/framework/sdk-parent/domain打开是404

**Comment by luty2018** [comment]
现在已经不使用main了， 默认使用2.10分支，是不是拉错了代码

**Comment by liuruibin** [comment]
自v2.10.0-lts发布后，仓库中默认的分支是v2.10，main 已经删除不再维护。请自行调整
