### ISSUE TITLE
[FEATURE]接口用例内可以支持自定义请求

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2623]
**请描述您的需求或者改进建议.**
接口用例目前只能支持前置、后置、断言、提取，并不能满足例如数据库等类型的数据提取，希望能够加上自定义请求，不是在场景内

**请描述你建议的实现方案**
在case下面新增自定义请求

**Comment by xulinde** [comment]
这种测试场景，可以采用接口自动化方式，支持添加自定义请求

**Comment by plateauandsp** [comment]
因为case里面运行有的数据是需要从数据库查询的，希望再case里面完成单个接口场景运行，然后在自动化里面直接引用。而不是每次自动化里面加了case后，在重复加sql

**Comment by zyyfit** [comment]
> 因为case里面运行有的数据是需要从数据库查询的，希望再case里面完成单个接口场景运行，然后在自动化里面直接引用。而不是每次自动化里面加了case后，在重复加sql

您好，我们的请求支持sql类型的请求，在场景中也可以直接引用或复制来使用，请问是否满足您的需求呢？

**Comment by wangzhen-fit2cloud** [comment]
已支持前后置 SQL 请求, 可以通过添加前后置 SQL 请求的方式满足该场景.
