### ISSUE TITLE
[FEATURE] 希望添加接口时可以支持curl添加

### ISSUE THREAD

**Issue by zaojingyoutu** [metersphere/metersphere#26239]
### MeterSphere 版本

最新的版本中就行

### 联系方式

1293551420@qq.com

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/62125751/ea1bf0b4-32b8-4f6f-8455-c754782e86de)
在这个地方添加CURL导入

### 请描述你建议的实现方案

填写CURL后打开详情也，用户确定后在保持就行
curl导入只需要把主要的信息填写进去就可以了

**Comment by luty2018** [comment]
感谢建议， 这个功能我们已经规划在v3.0版本了。

**Comment by zaojingyoutu** [comment]
感谢,3.0版本预计什么时候发布？

**Comment by luty2018** [comment]
> 感谢,3.0版本预计什么时候发布？

年底了哦

**Comment by luty2018** [comment]
这个功能已经在v3.0 上线， 可以下载使用。
