### ISSUE TITLE
v2.10版本的 [metersphere-platform-plugin] 插件项目中的 io.metersphere:domain:main 没有是什么原因？

### ISSUE THREAD

**Issue by Get-lzh** [metersphere/metersphere#26249]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/58059353/478c1586-f551-4752-a7b3-805dddb18a0e)

**Comment by liqiang-fit2cloud** [comment]
https://github.com/metersphere/metersphere/blob/v2.10/build.md
