### ISSUE TITLE
[BUG]脑图导入，模块名包含TC名称时，导入失败

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#26244]
### MeterSphere 版本

V2.10.5

### 使用外置数据库

否

### 问题描述

脑图导入，在模块名陈中包含有TC名称时，导入失败

### 重现步骤

见问题描述

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/92150453/457d39d7-6b09-475d-affc-d4f93ebbd35b)
![970327162e0adfb41f9ce6d62f8e16e](https://github.com/metersphere/metersphere/assets/92150453/6b9fc7f2-2b3b-4de8-bfb6-4a7c70e6cc7d)

**Comment by 13290445582** [comment]
感谢反馈，计划v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
暂时不修改，已沟通，同意挂起，关闭issue，感谢。

**Comment by 13290445582** [comment]
您好，TC作为用例名称的关键字存在，若命名时采用TC进行命名，会与我们的关键字所冲突导致导入用例失败，因此在命名时应该避免用TC去命名与系统关键字冲突，感谢理解与支持。
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/c176b31f-2e00-4312-b614-5c223ed82fbb" />
