### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wangxin188** [metersphere/metersphere#26248]
### 联系方式

1009722326@qq.com

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

集成了jira，创建缺陷模板时使用jira模板时，
https://github.com/metersphere/metersphere/assets/141306651/46c44562-e21e-410b-8d66-3cd1d69d777a
报错如下：
https://github.com/metersphere/metersphere/assets/141306651/a3557115-5cff-4c53-8560-0d401d9f273b
按照jira模板进行手动创建，在jira模板的基础上加上经办人，报错如下：
https://github.com/metersphere/metersphere/assets/141306651/d46b17e0-4e96-4789-9a0b-3e49ea8dfd6c

### 重现步骤

1.在项目管理中找到项目集成jira，点击使用jira模板，在测试跟踪中找到创建缺陷模板，创建后点击保存报错，问题描述中的图2
2.手动创建模板，在1的基础上加上经办人，报错，问题描述中的图3

**Comment by 13290445582** [comment]
您好，未复现您说的这种情况，用的是最新的2.10.4的jira插件吗？方便的话可以提供下完整的操作录屏，感谢。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
