### ISSUE TITLE
[BUG][测试跟踪][测试计划]概率性出现执行一直处于running状态不会自动暂停，只能通过手动暂停

### ISSUE THREAD

**Issue by Liu-Ying-95** [metersphere/metersphere#26240]
### 联系方式

ying14_l@163.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

测试跟踪执行测试计划出现执行一直处于running状态不会自动暂停

### 重现步骤

创建测试计划--关联接口测试用例/场景用例--定时执行测试计划--概率性出现接口执行一直处于running状态不会自动暂停
![22821692153842_ pic](https://github.com/metersphere/metersphere/assets/51806839/4ea828d0-6d65-4e8c-82d3-2c23de7a8d6c)

### 期待的正确结果

接口执行超时/错误正常暂停

**Comment by 13290445582** [comment]
您好，在最新环境未复现该问题，建议您升级至最新版，测试下是否还存在该问题，若最新版也存在，您可以导出提供下状态错误的场景，帮助复现，感谢理解。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～

**Comment by Liu-Ying-95** [comment]
在  v2.10.6版本此问题还会复现，设定的定时任务是每半小时执行一次，每天都会碰到此问题，出现有用例running后定时任务就不会返回报告
