### ISSUE TITLE
本地执行编译V2.10版本报错

### ISSUE THREAD

**Issue by Get-lzh** [metersphere/metersphere#26253]
### 请描述您的问题

参考 https://github.com/metersphere/metersphere/blob/v2.10/build.md 链接
在执行完 命令：   ./mvnw clean install -pl framework,framework/sdk-parent,framework/sdk-parent/domain,framework/sdk-parent/sdk,framework/sdk-parent/xpack-interface,framework/sdk-parent/jmeter
之后报错如下，请问如何处理
![image](https://github.com/metersphere/metersphere/assets/58059353/a4dd7399-b1bb-40e6-99e7-440d495ee7ea)

**Comment by fit2-zhao** [comment]
确保是进入工程目录下执行相关命令，检查jdk和maven是否安装正常等；具体可以参照我们官方开发文档：
https://metersphere.io/docs/v2.x/dev_manual/#22
