### ISSUE TITLE
[BUG] 性能测试-资源监控，配置了多个监控信息，但是导出报告监控信息只有自带的ms-node

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#26250]
### MeterSphere 版本

2.10.5-lts

### 使用外置数据库

否

### 问题描述

性能测试-资源监控，配置了多个监控信息，但是导出报告监控信息只有自带的ms-node

### 重现步骤

性能测试-资源监控，配置了多个监控信息，
w问题：但是导出性能报告监控信息只有自带的ms-node

### 期待的正确结果

按配置信息显示完整的监控数据

**Comment by xhy12** [comment]
![性能测试配置了两份监控信息，但是导出的报告只有一份监控记录](https://github.com/metersphere/metersphere/assets/43202800/64b8c171-ac1b-4a13-ab6d-493ff007045e)

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复这个问题。

**Comment by liuruibin** [comment]
由于我们设计缺陷，导出本质上是网页截图。v2版本中不再优化这里
