### ISSUE TITLE
[BUG]批量执行接口测试场景选择资源池执行，info日志中生成的脚本和原场景顺序不同

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#26252]
### 联系方式

shenkaibo

### MeterSphere 版本

2.10.5-lts

### 使用外置数据库

否

### 问题描述

批量执行接口测试场景，执行时 去 info 日志查看打印的 jmx 脚本，用 jmeter 打开后 和原场景顺序不一致。
![image](https://github.com/metersphere/metersphere/assets/30038088/67902c86-3f03-4729-9cc2-b4ce3864439c)

### 重现步骤

批量执行接口测试场景，执行时 去 info 日志打印的 jmx 脚本，用 jmeter 打开后 和原场景不一致。
场景文件如下：
[Metersphere_Scenario_xxx.zip](https://github.com/metersphere/metersphere/files/12366312/Metersphere_Scenario_xxx.zip)

info 日志和 info 日志中打印的 jmx 脚本如下：
[info (2).zip](https://github.com/metersphere/metersphere/files/12366306/info.2.zip)

**Comment by fit2-zhao** [comment]
已确认是JMeter对Critical Section Controller 展示处理问题，相同jmx文件多次打开展示顺序都不是一致的，对于我们平台执行不影响，我们的执行顺序是有序处理。
