### ISSUE TITLE
[BUG]场景调试自定义脚本中python语句出现错误会导致调试场景时不显示该步骤被执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26260]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

场景调试自定义脚本中python语句出现错误会导致调试场景时不显示该步骤被执行，生成报告的形式调试的话，该步骤会显示pending

### 重现步骤

1. 脚本正则提取数据(如需要场景可私发）
![image](https://github.com/metersphere/metersphere/assets/103627487/d5812010-9c28-488e-bdd6-3c220c04f6da)
2.下面自定义脚本python使用
![image](https://github.com/metersphere/metersphere/assets/103627487/730b8ee0-6870-4692-99b9-54a384320b84)
3.调试，该步骤未执行
![image](https://github.com/metersphere/metersphere/assets/103627487/b7eb30cb-2680-4850-9e57-f7e725c186c8)

**Comment by 13290445582** [comment]
您好，经过排查，原因是JSR223解析器报错导致没有结果返回，需要用户将脚本改准确，非metersphere缺陷，感谢理解。
