### ISSUE TITLE
[BUG] 导入ui脚本，场景中的步骤[鼠标点击]为英文，原来版本为中文

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26267]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

导入ui脚本，场景中的步骤[鼠标点击]为英文，原来版本为中文

### 重现步骤

导入side文件（可私聊发送）后，查看场景步骤：：：
<img width="749" alt="企业微信截图_25fd978d-35c5-4c56-aa80-403bfd8ccaf6" src="https://github.com/metersphere/metersphere/assets/103925124/a3f9224d-4f01-4d99-93c2-c6ee44130cb3">
<img width="285" alt="企业微信截图_5f91ffef-4da4-4802-8b0d-a9f6690e7282" src="https://github.com/metersphere/metersphere/assets/103925124/a0c9e513-0bd3-43f2-98ba-41fde1354e4e">

**Comment by zrfit** [comment]
.side文件是从ms v2.10.5导出数据再导入后吗？用提供的文件导入后名称就是为英文，改成中文后再次导出导入，名字仍为中文，未复现该问题。

**Comment by zrfit** [comment]
经沟通已复现，计划v2.10.7-lts优化。
