### ISSUE TITLE
[FEATURE] 测试计划正在执行中的不能再次执行，导致流水线调用和手动触发的时候，不同环境不能再次执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26285]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

测试计划正在执行中的不能再次执行，导致流水线调用和手动触发的时候，不同环境执行不能再次执行
![image](https://github.com/metersphere/metersphere/assets/103627487/1ee6fef6-3f32-4e40-b571-056d7e9c4800)

### 重现步骤

测试计划还在执行的时候，再次触发同一个测试计划
![image](https://github.com/metersphere/metersphere/assets/103627487/8db118c8-d7ab-4cad-974b-25e715842058)

**Comment by zrfit** [comment]
您好，感谢反馈！
1、目前同一计划没执行结束，报告未完成，是不能再次执行的。
2、建议复制该计划，可选择其它环境执行，达到同样的目的。
3、v3会进行调研，如果调研后可以实现，我们会进行优化。

**Comment by luty2018** [comment]
会在.7改成定时任务触发的才限制同一测试计划未结束无法执行， 手动和API调用的取消限制
