### ISSUE TITLE
[BUG]功能用例中含有JSON相关内容时，在“保存”前后发生变化

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#26288]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

功能用例的步骤中，步骤类型为“文本描述”，如果内容中含有JSON相关内容，JSON中的"号会在保存后由" 变为“  ，导致用户实际测试过程中，复制文本描述中有关信息不准确。

### 重现步骤

1、打开某个类型为“文本描述”的功能用例
2、在某个步骤值内输入例如 ：{"name":"测试环节","status":"dede"}  这样的内容
3、更新保存后，再去复制相关内容至其他编辑器进行比对

### 期待的正确结果

保存前后内容一致

### 附加信息

保存前：
<img width="761" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/65e3fd8d-c2c4-4f5b-b852-da2016d8d7ce">

保存后：
<img width="648" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/ac7df0f9-b805-48d6-932c-35873d1ec717">

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.6-lts将不存在该问题，待发布后建议升级尝试。

**Comment by dashenyucainiao** [comment]
在v2.10.6-lts版本中验证已修复
