### ISSUE TITLE
[FEATURE]建议MeterSphere服务增加开机自启动功能

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#26299]
### MeterSphere 版本

v2.10.4-lts

### 联系方式

MeterSphere 交流群49（昵称heavenly）

### 请描述您的需求或者改进建议

目前在用v2.10.4-lts单机版，近期公司机房改造经常需要断电，每次断电启动MeterSphere服务器都需要重启一下docker才能正常访问MeterSphere平台，非常不方便，建议在一键部署时增加各服务开机自启动功能，减少手动重启docker 带来的不便

**Comment by liuruibin** [comment]
您可以手动执行 `sytemctl enable docker` 解决这个问题

**Comment by heavenlyye** [comment]
我这表达的不就是每次断电不只是接上电源，还要再重启一下Docker才能用吗？这个回复等于没有回复

**Comment by liuruibin** [comment]
你可以先解决问题，我们后面会考虑如何处理的。
