### ISSUE TITLE
[BUG]当后置脚本添加参数提取后，无法正常获取环境列表

### ISSUE THREAD

**Issue by clare0916** [metersphere/metersphere#26292]
### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

当后置脚本添加参数提取后，无法正常获取环境列表

### 重现步骤

当后置脚本添加参数提取后，无法正常获取环境列表

**Comment by zrfit** [comment]
您好，感谢反馈！
1、哪个功能模块？
2、后置脚本内容是什么？
3、从哪里获取环境列表失败？
请补充下复现详细步骤和截图信息,方便的话导出文件发到rui.zhang@fit2cloud.com便于我们进行复现排查。

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
