### ISSUE TITLE
[BUG]性能测试使用并行控制器压测时，测试概览页面展示的并发数与实际设置的并发数不符。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#26294]
### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

1.性能测试使用并行控制器压测时，测试概览页面展示的并发数与实际设置的并发数不符。

### 重现步骤

1.接口自动化创建场景a
2.用场景a创建性能测试
3.资源文件上传并发控制器jar包
4.设置并发数为20个
![image](https://github.com/metersphere/metersphere/assets/55130444/36c3fc35-1f19-4475-9243-5caa122d1789)
5.测试概览并发数为5个
![image](https://github.com/metersphere/metersphere/assets/55130444/bcf6841b-bef3-4892-8be4-e685f0fd246b)

### 期待的正确结果

性能测试报告，测试概览展示并发数为设置的并发数。

### 附加信息

1.不使用并行控制器，可以达到设置的并发数。
![image](https://github.com/metersphere/metersphere/assets/55130444/7f6a8e5e-bf58-42df-a200-7a06e0009ac1)
![image](https://github.com/metersphere/metersphere/assets/55130444/428d9102-7a9d-4584-8fd0-1bd94bdc307c)
2.JMeter使用并行控制器截图：
![image](https://github.com/metersphere/metersphere/assets/55130444/aeabdfb5-cd65-457a-81cc-5a72d496504b)

**Comment by 13290445582** [comment]
在最新环境未复现，已沟通，待发布最新版本进行测试，后续有问题请重新提issue，感谢理解与支持。
