### ISSUE TITLE
对接禅道无法支持GET方式调用接口导致对接不成功

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#2630]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
对接禅道报错，日志如下，MS到禅道服务器是通的，账号也是超级 model 调用接口权限， $config->features->apiGetModel = true也改了
![image](https://user-images.githubusercontent.com/35896106/117619167-7f635780-b1a1-11eb-9eca-2b36fbbf5058.png)
![image](https://user-images.githubusercontent.com/35896106/117619180-838f7500-b1a1-11eb-8405-065bdfa61330.png)
**Bug 重现步骤**
1.  系统设置-组织-服务集成-对接禅道
2. 输入账户密码、禅道地址，点击测试连接，报连接失败
3. 排查发现MeterSphere是通过 PATH_INFO 的方式调用接口，我们的是通过GET 的方式调用接口，因其他系统也也GET方式调用，所有无法更改

**期待的正确结果**
正确情况下应该是什么样的？
希望可以支持通过GET 的方式调用接口
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35896106/117619668-21833f80-b1a2-11eb-9ffb-9b7e55e29c09.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本优化这个问题
