### ISSUE TITLE
[BUG]UI测试url中路径带!符号会识别为不合法

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26304]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

UI测试url中路径带!符号会识别为不合法

### 重现步骤

1.UI测试第一个步骤设置为打开网页https://xxx.xxxx.xxx/#!/login
2.执行后会报错
![image](https://github.com/metersphere/metersphere/assets/88763608/1f6767a2-9bf3-45ff-bd43-8174d4ec58f5)

### 期待的正确结果

浏览器能打开的url，我们应该都能打开。
客户那边的路径是带#!的

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
