### ISSUE TITLE
[BUG]【项目设置】应用管理-接口测试-报告分享链接，开启状态，然后将其关闭，过一会刷新页面，自动恢复成开启状态

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26308]
### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

【项目设置】应用管理-接口测试-报告分享链接，目前是开启状态，将其关闭，过一会刷新页面，自动恢复成开启状态

### 重现步骤

【项目设置】应用管理-接口测试-报告分享链接，目前是开启状态，将其关闭，过一会刷新页面，自动恢复成开启状态
![1692672326092](https://github.com/metersphere/metersphere/assets/104960608/0b3c337f-fec3-403d-b49e-63f32bfade35)
![1692672371745](https://github.com/metersphere/metersphere/assets/104960608/c3d5d3fd-0087-4304-92bb-b6b80d58d519)

**Comment by 13290445582** [comment]
您好，这不是bug，就是这样设计的，那个按钮是，开启以后才能修改时间，并不是控制时间开启关闭的。
