### ISSUE TITLE
[BUG]性能测试加载JMX文件，勾选后再取消勾选的JMX文件也会被加载进来

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26300]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

性能测试加载JMX文件，勾选后再取消勾选的JMX文件也会被加载进来

### 重现步骤

1.在性能测试加载JMX文件，先勾选JMX A，再取消勾选JMX A，再勾选JMX B，总共只勾选一个JMX
![image](https://github.com/metersphere/metersphere/assets/88763608/a9213328-ab53-4f46-b88e-b7373f275e43)
2.实际上JMX A也被加载进来了
![image](https://github.com/metersphere/metersphere/assets/88763608/45d81431-90b6-4374-840c-14205af0a15b)

### 期待的正确结果

只加载当前勾选的

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
