### ISSUE TITLE
[BUG]开源版v2.10.4-lts从禅道同步Bug

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#26302]
### 联系方式

MeterSphere 交流群49（昵称heavenly）

### MeterSphere 版本

v2.10.4-lts

### 使用外置数据库

否

### 问题描述

本人目前使用的是开源版v2.10.4-lts，与公司禅道进行对接，结果把禅道Bug同步到MeterSphere平台，与贵司多位工程师确认，开源版不会把禅道Bug同步过来，也进行过版本升级，这问题仍然存在，禅道版本是：企业版6.4，如若贵司测试环境无法复现，我可以提供测试环境

### 重现步骤

请查看截图中124个bug中只有一个是在MetereShpere平台上创建的，它也能同步到禅道

### 附加信息

![bug0822](https://github.com/metersphere/metersphere/assets/130725706/220d7205-9674-43d0-b13c-cb9ac53e837b)

**Comment by 13290445582** [comment]
您好，可以将您的ms环境地址账号密码和对接禅道的地址账号密码发我复现一下，我的邮箱：yicheng.wang@fit2cloud.com，感谢。

**Comment by heavenlyye** [comment]
我在微信群：MeterSphere 交流群49（昵称heavenly），能否微信沟通？

**Comment by 13290445582** [comment]
可以添加我的微信：13290445582

**Comment by heavenlyye** [comment]
已添加，麻烦通过

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.6版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.6已修复

**Comment by heavenlyye** [comment]
目前 使用v2.10.11，已不存在此问题，感谢响应
