### ISSUE TITLE
[FEATURE]建议可以多项目共用同一个缺陷模板

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#26303]
### MeterSphere 版本

v2.10.4-lts

### 联系方式

MeterSphere 交流群49（昵称heavenly）

### 请描述您的需求或者改进建议

目前的MeterSphere缺陷模板是针对项目设置的，在一个项目设置好缺陷模板，另外一个项想要再用缺陷模块还需要再次设置模板，不太方便。因缺陷模板基本上变化不大，不太可能经常修改，建议同一个工作空间的项目可以共用相同的缺陷模板

**Comment by luty2018** [comment]
我们已经计划添加组织级别的模板了， 目前可以通过将项目模板复制到另外一个项目来解决哈，不需要重复创建。

**Comment by heavenlyye** [comment]
组织级别的模板大致什么时间可以上线呢

**Comment by luty2018** [comment]
> 组织级别的模板大致什么时间可以上线呢

预计在年底的版本

**Comment by heavenlyye** [comment]
感谢回复
