### ISSUE TITLE
[BUG]接口执行后JSONPath断言失败。

### ISSUE THREAD

**Issue by pengyif** [metersphere/metersphere#2631]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.9.1-2cb10c1e
**Bug 描述**
简要描述您碰到的问题
\[\["202104281101","202104281113",0\.9,0\.26,0\.9,0\.26,1\.7,1\.53,0\.44,1\.53,0\.44,0,0\.09,0,0\.15,0,0\.09,0,0\.15\]\]
**Bug 重现步骤**
1.  创建JSONPath断言
2. 执行接口
3. 断言失败
4. 但是返回值是匹配的

**期待的正确结果**
匹配上成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/83944885/117621280-087b8e00-b1a4-11eb-8358-95b884699c21.png)

**Comment by zyyfit** [comment]
您好，是不是需要转义一下断言里的字符？
