### ISSUE TITLE
[BUG]EXCEL导入用例报500

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#26335]
### 联系方式

MeterSphere交流群24 昵称多情的砍刀

### MeterSphere 版本

版本:   v2.10.5

### 使用外置数据库

否

### 问题描述

从页面上导出excel用例，然后再将用例导入更新，报500，页面显示英文key重复

### 重现步骤

从页面上导出excel用例，
然后再将用例导入更新

### 期待的正确结果

导入更新成功

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/39703025/2e65dac0-65b9-4343-89e5-06d293727460)

![image](https://github.com/metersphere/metersphere/assets/39703025/0184d1a8-2d7d-4c42-a418-28c509a279da)
![image](https://github.com/metersphere/metersphere/assets/39703025/84959dd1-d6e5-4e2c-aced-bfa69bef8ae6)
![image](https://github.com/metersphere/metersphere/assets/39703025/b5d3e54a-523d-4638-9524-8dea1ae175ea)

**Comment by 13290445582** [comment]
您好，可以提供下您导入的excel文件嘛？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
