### ISSUE TITLE
[BUG]使用While循环控制器时，循环控制器下的接口有存在前置加密脚本时，第一次会加密，第二次不会去加密了

### ISSUE THREAD

**Issue by lmx0621** [metersphere/metersphere#26339]
### 联系方式

MeterSphere 交流群18 昵称为：BlastStar

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

while循环中有前置加密时，第一次请求生效了，第二次循环请求没有生效呢

### 重现步骤

![3a97df0222ab6077ff88a0732c31a32](https://github.com/metersphere/metersphere/assets/24906094/f15a6653-7079-4a37-8bcd-1f5a7b9fdc76)

### 期待的正确结果

每次循环时都需要加密

**Comment by zrfit** [comment]
您好，感谢反馈！您的脚本具体是怎么加密的？是将该请求体对应字段加密后作为变量引用还是其它引用方式？请提供下前置脚本我们看下是否可复现。

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
