### ISSUE TITLE
[BUG]jdbc sampler中的test无法选择配置好的数据源

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26333]
### 联系方式

suprookie

### MeterSphere 版本

2.10.5-lts

### 使用外置数据库

是

### 问题描述

jdbc sampler中的test无法选择配置好的数据源

### 重现步骤

脚本sampler中的test无法选择配置好的数据源
1.编辑导入的sql脚本
2.环境配置
3.增加环境变量及数据库相关配置
4.选择test
5.无法带出配置的数据源

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.6-lts未复现该问题，建议升级尝试，如升级后该问题仍存在，请提供对应操作步骤截图并导出接口。
<img width="1082" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/115c5a71-8a38-4e04-ad4d-609e31b1cbfd">
