### ISSUE TITLE
[BUG]在评审计划中，使用列表模式或脑图模式，将用例标记为“通过”并保存，在系统设置-操作日志中并没有得到记录 

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26342]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.5-lts

### 使用外置数据库

否

### 问题描述

在评审计划中，使用列表模式或脑图模式，将用例标记为“通过”并保存，在系统设置-操作日志中并没有得到记录 

### 重现步骤

1、在测试跟踪-功能用例中新建一条测试用例
2、新建一个评审计划
3、在新建立的评审计划中关联这条测试用例
4、切换到脑图模式/列表模式
5、在脑图模式/列表模式下，点击“通过”按钮，并点击保存；此时会弹出保存成功的弹窗
6、进入系统设置-操作日志，并没有看到用例状态更新的日志提示

### 期待的正确结果

期待的正确结果：在系统设置-操作日志中，有日志记录此条测试用例被更新

### 附加信息

这个问题与#25659类似

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复此问题。

**Comment by Hyyfit** [comment]
您好，系统设置的记录是一个粗略的记录，像评审计划，具体到里面的某个用例的结果这样的记录，不适合放到系统设置中。
我们v3的版本里规划了每一个评审计划都有变更记录，会详细记录评审的过程。
感谢您的反馈！

**Comment by Hyyfit** [comment]
您好，v3.0 已覆盖。
用例加入到评审计划中会有记录，且每一次评审的历史，都可以在用例的详情中查看到
![image](https://github.com/metersphere/metersphere/assets/95834771/efebc1ad-8ec8-4ec4-88b6-a5dd8a81bd18)

**Comment by Hyyfit** [comment]
![image](https://github.com/metersphere/metersphere/assets/95834771/efebc1ad-8ec8-4ec4-88b6-a5dd8a81bd18)
