### ISSUE TITLE
[BUG]v2.10.5-lts-0ba6e94d配置禅道插件后关联项目编号报错

### ISSUE THREAD

**Issue by chenwawa** [metersphere/metersphere#26359]
### 联系方式

MeterSphere交流群63-幸会

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

配置了禅道并上传了插件后，在项目管理里准备配置禅道项目ID，点击编辑后报错
`Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "clazz" is null`
![image](https://github.com/metersphere/metersphere/assets/2209909/615864a7-d524-4de7-b063-ecf52ba2e1a7)

### 重现步骤

1、在禅道上增加了配置
2、在metersphere上传了禅道插件
3、绑定了禅道管理员账号并且测试通过，有超级model调用权限
4、回到metersphere配置禅道项目ID，点击项目编辑按钮后，报错：
`Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because "clazz" is null`
5、项目编辑页面能够打开，但是“集成第三方平台”选项中，没有“禅道”选项

### 期待的正确结果

编辑页面可以正常打开，可以下拉选中禅道选项，可以配置禅道项目ID

**Comment by 13290445582** [comment]
您好，重新上传下禅道插件试一试，重启禅道服务，github上可以下载最新的zentao插件，看下可以解决问题吗？

**Comment by chenwawa** [comment]
> 您好，重新上传下禅道插件试一试，重启禅道服务，看下可以解决问题吗？

升级到2.10.6版本后可以配置了，但是遇到新问题，无法推送bug到禅道，系统界面上没有报错反馈，请问下metersphere系统日志在哪个位置查看，我追踪下。

**Comment by 13290445582** [comment]
您好，无法推送到禅道，请检查下项目设置-项目信息-Zentao项目ID的填写是否正确，该项目ID需要填写你禅道中需要对接的产品的url中productID号。
在/opt/meterspere/logs/test-track可以看测试跟踪的日志。

**Comment by chenwawa** [comment]
根据禅道的配置模式，ID号需要填写产品ID，实际填写的也是产品ID，且检测通过。
日志已经提交工程师分析，还在排查。

**Comment by chenwawa** [comment]
解决通过了，感谢小东老师和工程师们。
目前还有几个遗留的不完美的地方，就是禅道中的带动态数据的字典项字段在ms新增bug界面里还没有，希望能够加上。

![image](https://github.com/metersphere/metersphere/assets/2209909/734f1204-d440-4a52-a978-9b1938d045f2)

**Comment by 13290445582** [comment]
感谢，您可以将您觉得可以继续改善的地方或者觉得需要添加的字段，提FEATURE给我们产品老师评估下，感谢理解与支持～

**Comment by lshc666** [comment]
v2.10.20-lts-9feb97b3  配置 jira 集成也遇到相同问题了
