### ISSUE TITLE
[BUG]创建测试计划时，添加标签，如果标签比较长会导致无法对齐

### ISSUE THREAD

**Issue by tangyuan903** [metersphere/metersphere#26361]
### 联系方式

交流群61-helt

### MeterSphere 版本

v.2.10.4-lts

### 使用外置数据库

否

### 问题描述

创建测试计划时，添加标签，如果标签比较长会导致显示时和较短的标签无法对齐

### 重现步骤

创建测试计划时，添加一个较长的标签和一个较短的标签

### 附加信息

![2c52e39441cd4a6c8a08e60ebeeaba0](https://github.com/metersphere/metersphere/assets/142998362/d2adc447-3b24-48dd-a486-889247f2e97c)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
