### ISSUE TITLE
[FEATURE] 环境配置中TCP配置建议可添加多个服务器IP和端口

### ISSUE THREAD

**Issue by tangyuan903** [metersphere/metersphere#26360]
### MeterSphere 版本

v.2.10.4-lts

### 联系方式

交流群61-helt

### 请描述您的需求或者改进建议

目前环境配置中HTTP可根据路径添加多个域名地址，希望TCP也可以支持配置多个地址。在实际使用中，一个场景可能会对应多个系统，需配置多个服务器地址。

### 请描述你建议的实现方案

通过路径配置多个服务器IP和地址

**Comment by luty2018** [comment]
这个我们会在v3.0讨论规划
