### ISSUE TITLE
[BUG]jemter5.5脚本的线程组中添加了foreach控制器导致调试时提示"场景步骤解析错误"

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26368]
### 联系方式

18510991012

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

jmeter5.5的脚本导入到接口自动化时，点击调试提示"场景步骤解析错误"。
问题原因：
            jemter脚本的线程组中添加了foreach控制器导致。

### 重现步骤

1.线程组中添加foreach控制器并保存。
2.上传脚本到自动化接口中
3.点击调试

### 期待的正确结果

可以识别该控件

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.6-lts用jmeter5.5添加foreach控制器导出到metersphere调试场景正常，建议升级到最新版本尝试。如升级后该问题仍存在，可将jmeter场景导出给我们看看，同时将metersphere调试的后端日志也提供下。
<img width="1035" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/8a381866-e34b-44c9-8d60-6b38550bccc6">
