### ISSUE TITLE
[BUG]【UI测试】指令-前置操作里，导入指令，点击执行，出现“第一个步骤必须是打开网页” 导致不能执行该指令

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26367]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

【UI测试】指令-前置操作里，导入指令，点击执行，出现“第一个步骤必须是打开网页” 导致不能执行该指令

### 重现步骤

【UI测试】指令-前置操作里，导入指令，点击执行，出现“第一个步骤必须是打开网页” 导致不能执行该指令
![image](https://github.com/metersphere/metersphere/assets/104960608/3993336a-4626-45c7-846d-4adb6267c296)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
