### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26369]
### MeterSphere 版本

2.10.5-lts

### 联系方式

18510991012

### 请描述您的需求或者改进建议

接口自动化测试导入的脚本在调试脚本时如提示"场景步骤解析错误"建议可以定位出解析错误的位置，方便进行调整或反馈。

**Comment by luty2018** [comment]
这个错误位置， 具体是指步骤里面的前后置脚本还是请求本身，是这个意思吗？
