### ISSUE TITLE
[FEATURE]接口定义和调试时可以选择保存cookie信息

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26373]
### MeterSphere 版本

v2.10.5-lts

### 联系方式

18610991012

### 请描述您的需求或者改进建议

接口定义和调试时可以选择保存cookie信息以便进行登录或其他需要cookie信息的请求的调试

**Comment by luty2018** [comment]
<img width="949" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/7cbede2a-6856-4673-8760-cb49942b0504">
已经提供这个功能了哦。

**Comment by glzzny** [comment]
对不起，我的缺陷描述的不是很具体，我具体说下。
我的需求场景是这样的，我司的登录接口是需要携带cookie经过认证接口的，这个过程是一个重定向请求的过程。
在单独定义登录接口时想要调试或者编写case，在无法携带cookie的情况下会被拦截无法登录。
