### ISSUE TITLE
[FEATURE]建议增加接口调试时响应信息里对正则/xpath/jsonpath等提取方式的脚本调试功能

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26374]
### MeterSphere 版本

v2.10.5-lts

### 联系方式

18610991012

### 请描述您的需求或者改进建议

建议增加接口调试时响应信息里对正则/xpath/jsonpath等提取方式的脚本调试功能

**Comment by luty2018** [comment]
能否更具体一点描述你的需求， 或者现在哪里不满足？

**Comment by glzzny** [comment]
1.在定义接口的Test标签中进行调试
2.调试时需要进行相应的断言或响应的提取(正则/jsonpath)的方式。
当前调试正则或jsonpath的语法：手写的正则及jsonpath的语句需要验证正确性只能通过一遍遍的调用接口确认
预期：可以像jmeter的GUI中添加的查看结果树中的相关语法的Tester进行计算，如图：
![image](https://github.com/metersphere/metersphere/assets/60509485/cdfc5622-7fd8-4000-b27c-c24313bcc54f)

**Comment by luty2018** [comment]
这个是第三方插件么

**Comment by luty2018** [comment]
你好， 感谢建议， 这个我们规划到v3.0 了

**Comment by luty2018** [comment]
![image](https://github.com/metersphere/metersphere/assets/36292514/c805d42a-1b2a-4cc8-a52e-989375601962)
目前可以通过推荐jsonpath功能进行快捷提取

**Comment by glzzny** [comment]
好的 谢谢

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
