### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26371]
### MeterSphere 版本

2.10.5-lts

### 联系方式

18510991012

### 请描述您的需求或者改进建议

建议在接口自动化添加的http请求中可以自定义端口号。

**Comment by luty2018** [comment]
<img width="235" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/f9879546-b8b8-4df8-aa09-24b6850accd6">
添加自定义请求可以自定义端口号。 如果是从接口列表中添加接口， 那么需要在环境里面配置端口号， 因为端口号是访问环境的一个属性。
