### ISSUE TITLE
[QUESTION]v2.0-lts版本不用性能测试，还需要kafka吗？

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#26389]
### 请描述您的问题

如题，主要使用接口自动化测试功能，如果不需要性能测试，那么在配置中填写实际不存在的kafka topic的话，接口自动化能正常执行吗？或者不填写kafk topic服务可以正常吗？
多谢

**Comment by fit2-zhao** [comment]
接口测试也需要kafka，配置文件中开放出来的topic是性能测试用到，接口测试的topic是在代码中定义不需要修改。
当前平台使用到的topic 您可以参阅：https://github.com/metersphere/metersphere/blob/747ca014835c140ca7a05e50dc0b477a4383df9d/framework/sdk-parent/sdk/src/main/java/io/metersphere/commons/constants/KafkaTopicConstants.java#L9C3-L9C3

**Comment by xchnshi** [comment]
> 

感谢回复。
如果不需要性能测试，仅是正常的消息通知，对于使用kafka 2.x版本可以吗？我们现在整体都没用kafka 3
