### ISSUE TITLE
[BUG]接口自动化的覆盖率统计数据异常

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#2638]
**MeterSphere 版本**
MeterSphere 版本是1.9.1

**Bug 描述**
接口场景用例的接口覆盖率统计，如果是通过jmeter导入的脚本生成的用例，无法识别出对应接口，覆盖率统计时未计算

**Bug 重现步骤**
1.  接口自动化页面，导入一个本地的jmeter脚本，生成场景用例
2. 在接口测试首页，接口覆盖率统计处，无法统计到该用例覆盖的接口数量

**期待的正确结果**
正确情况下，应能够计算jmeter导入的用例覆盖的接口数，并纳入覆盖率统计

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前接口覆盖率的统计方式是，接口定义中的接口，有用例的接口定义数/总接口定义数
