### ISSUE TITLE
[FEATURE]建议在变更记录中，“变更字段”采取“评审结果”、“执行结果”等词语进行描述

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26385]
### MeterSphere 版本

 v2.10.5-lts

### 联系方式

kiwifruit.guo@qq.com

### 请描述您的需求或者改进建议

在”功能用例”模块，我们的表头采取的是“评审结果”、“执行结果”字样，那么在变更记录，“变更字段”也应该保持统一；现在采用的是“状态”字段，表意不明
<img width="685" alt="B9E35F45-E3F0-41da-898A-550BB28A3745" src="https://github.com/metersphere/metersphere/assets/56757548/4530469d-e3bd-4d7d-aa87-f45f543e57da">
<img width="614" alt="62A716B4-29DA-4f37-A3F5-A28489733C23" src="https://github.com/metersphere/metersphere/assets/56757548/b04353d3-7c38-4dbf-8117-6379faf92243">
<img width="616" alt="054CE9ED-A7D5-4a9f-A629-BBB96514B5AC" src="https://github.com/metersphere/metersphere/assets/56757548/cb3c087e-6459-49c4-9c4b-ce7b20cd203c">

### 请描述你建议的实现方案

建议在变更记录中，“变更字段”采取“评审结果”、“执行结果”等词语进行描述

### 附加信息

这个issue 与#26342 #25659 相关

**Comment by luty2018** [comment]
感谢建议， 这里我们正在排期优化

**Comment by kiwifruit-guo** [comment]
请问预计排在哪一期修复呢？

**Comment by luty2018** [comment]
会在v3.0版本进行优化
