### ISSUE TITLE
[BUG]禅道集成MS时，无法通过项目ID集成，只能通过产品ID集成

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#26395]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.5lts

### 使用外置数据库

否

### 问题描述

禅道集成MS时，无法通过项目ID集成，只能通过产品ID集成
MS版本：v2.10.3-lts
MS插件：Zentao-2.10.3
禅道版本：开源版18.5
<img width="416" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/7c08b9a7-07ec-49c8-a0cc-7acc0e74827a">
项目ID
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/825dd586-4cf1-4807-8ba2-8761339deead">
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/d371042c-bfeb-4e1d-9bd2-6ce01fd5a44e">

产品ID
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/6ee15107-fc35-4e23-8aa2-3033a673bc7f">
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/001d06cf-cddf-4cb3-bd27-ba42f78aad65">

随机ID
<img width="415" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/5e3b5c61-dd2c-4819-bff9-65841d017e57">
<img width="416" alt="image" src="https://github.com/metersphere/metersphere/assets/83771182/28b06aee-c2a2-4a3b-8cc6-0b3e29a6356e">

### 重现步骤

禅道集成MS时，可以通过项目ID集成

**Comment by 13290445582** [comment]
您好，在18.5这些高版本禅道上，确实是使用产品ID进行集成，metersphere在Zentao项目ID提示那里是依据禅道12.5这些版本进行撰写的，集成12.5版本是可以正常使用产品ID或项目ID进行集成，禅道的高版本目前是使用的产品ID集成，现阶段不会对这方面进行修改，建议使用产品ID进行集成即可，感谢您的理解与支持。
