### ISSUE TITLE
[BUG]UI测试等待元素操作类型为“等待元素不存在”时，设置超时时间不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#26397]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

UI测试过程中，元素操作步骤类型为等待元素，当操作为“等待元素不存在”时，设置超时时间不生效。

### 重现步骤

1、添加元素操作，类型为等待元素
2、等待元素中的类型设置为“等待元素不存在”，随便写一个已经存在的元素，并设置超时时间为30000ms
3、执行后发现并未生效，报错信息显示仍然为15s

### 期待的正确结果

能够按照设置时间进行等待

### 附加信息

步骤内容及报错信息：

<img width="1324" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/d18a8602-06c3-468b-bfbb-2170e7961b6f">

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
