### ISSUE TITLE
[BUG]MS与JIRA集成后，同步缺陷时有些项目可以带出创建人数值，有些项目无法带出

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#26394]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

MS与JIRA集成后，同步缺陷时有些项目可以带出创建人数值，有些项目无法带出

JIRA插件用的github最新版本，JIRA版本是V8.13.1，同步不过来创建人数据的项目有3000个bug。

![6dba51591fd4958784096e53b57fa70](https://github.com/metersphere/metersphere/assets/83771182/69758364-fa7a-4b14-9f10-246d1aa47e34)

### 重现步骤

同步缺陷可带出创建人数据

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by song-cc-rock** [comment]
应该是定时同步的缺陷没有设置创建人吧, 手动同步的缺陷创建人是正常的.

**Comment by 13290445582** [comment]
v2.10.7已修复。
