### ISSUE TITLE
[BUG]mock地址修改后，打开mock界面地址又会被重置

### ISSUE THREAD

**Issue by traers** [metersphere/metersphere#26396]
### 联系方式

交流群16，淘沙

### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

在环境管理里面修改了mock的地址，再从接口处进入mock，mock的地址会被重置为初始化地址。

### 重现步骤

1，在环境管理里面修改mock的地址
2，选择接口，点击编辑，点击mock，问题复现

### 期待的正确结果

mock地址不会重置

### 附加信息

![ade63496-e171-4071-920d-cfa6d3765bc4](https://github.com/metersphere/metersphere/assets/53631945/d56655c7-f323-4ca6-bed6-a75cbb854f7f)
![image](https://github.com/metersphere/metersphere/assets/53631945/be6a6090-8252-434d-82fc-b2979f581a33)

**Comment by Somebody-JIAN** [comment]
您好。 ms的mock地址是会和系统设置中的当前站点的保持一致，并且程序在多处设置了检查。

如果您需要使用您自定义的mock地址，请您新建一个环境。
