### ISSUE TITLE
[BUG] 超级管理员权限无法移除公共用例库的用例

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26405]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

新建一个用户给超级用户管理员权限，该用户无法移除公共用例库的用例

### 重现步骤

1.新建一个用户
2.给该用户超级管理员权限
3.用该用户登陆 MeterSphere
4.移除公共用例库的用例

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/a2127e11-4809-4934-bdda-56e8cc44d5d1)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
