### ISSUE TITLE
[BUG]【测试跟踪】用例评审时，点击上一条、下一条切换用例，附件列表的附件未切换

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26420]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

在用例评审时候，点击上一条、下一条切换用例，附件列表的附件未切换

### 重现步骤

1.多条用例添加附件
2.创建用例评审
3.关联上面的用例
4.评审用例
5.点击上一条、下一条切换用例
6.观察切换用例时的附件是否有变化 

### 期待的正确结果

点击上一条、下一条切换用例，附件列表的附件一起切换

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/2ae873e6-19ab-4872-853c-9dd1584231f1)
![image](https://github.com/metersphere/metersphere/assets/45531073/a3e93d6e-e79f-46b0-b8a7-b7fc84c30605)

用例评审时附件未切换
![image](https://github.com/metersphere/metersphere/assets/45531073/b49b8e7e-5b80-42c5-93b3-e975f71e513c)

![image](https://github.com/metersphere/metersphere/assets/45531073/d967a59d-dc31-4c47-b763-adc50c9fefd0)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。

**Comment by Test-Alan** [comment]
【测试跟踪】用例评审时，点击上一条、下一条切换用例，前置条件没有切换。同样的问题
版本： v2.10.12-lts
