### ISSUE TITLE
[BUG]为一条用例添加依赖关系，前置/后置用例的状态不显示

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26433]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.5-lts

### 使用外置数据库

否

### 问题描述

为一条用例添加依赖关系，前置/后置用例的状态不显示

### 重现步骤

1、新增一条功能用例
2、为这条用例添加前置/后置用例
3、你会发现前置/后置用例的状态没有展示
![IMG_20230826_105739](https://github.com/metersphere/metersphere/assets/56757548/cebf27dc-6eda-49c0-bcde-664b16d15c41)

### 期待的正确结果

用例状态字段与前置/后置用例的实际状态一致

**Comment by 13290445582** [comment]
您好，最新版本未复现该问题，请升级最新版本测试。

**Comment by kiwifruit-guo** [comment]
在新版本中，此问题仍然存在；
请问这个“用例状态”的具体含义是什么？
应当如何让这个字段有值呢？

**Comment by 13290445582** [comment]
您好，请问您是开源版吗？经过排查，在开源版发现了此问题，企业版未发现该问题。

**Comment by kiwifruit-guo** [comment]
您好，是开源版本；
请问“用例状态”具体含义是什么？

**Comment by 13290445582** [comment]
<img width="1372" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/f2234313-4fc2-406d-8050-667c7223fffe">

**Comment by 13290445582** [comment]
计划于v2.10.7版本修复这个问题。

**Comment by kiwifruit-guo** [comment]
您好，经排查，这与项目的测试用例模板有关；如果项目的测试用例模板没有勾选“用例状态”，那么就会出现此现象。请考虑如何处理

**Comment by 13290445582** [comment]
感谢，已反馈。

**Comment by 13290445582** [comment]
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/61c6a764-e17e-4191-a534-c11e61f3322b">
您好，请问在用例模版这里，默认值选择值了吗？可以将您的模版截图发下

**Comment by kiwifruit-guo** [comment]
在模板中没有选择值；请研判如果没有在模板中勾选用例状态字段，那么依赖关系应当如何展示

**Comment by 13290445582** [comment]
您好，若模版中未设置默认值，创建用例时需手动选择用例状态，不选择用例状态则为空，那么这样显示就是没问题的。

**Comment by 13290445582** [comment]
您好，经过检查，不是缺陷，先关闭该issue，有问题可继续描述，感谢理解与支持。
