### ISSUE TITLE
[BUG]测试计划中，创建时间和更新时间与功能用例菜单下的时间不一样

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26435]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.5-lts

### 使用外置数据库

否

### 问题描述

测试计划中，创建时间和更新时间与功能用例菜单下的时间不一样

### 重现步骤

1、新建一条测试用例，新建一个测试计划并进行关联
2、观察测试计划中的创建时间和更新时间
3、观察功能用例菜单下的创建时间和更新时间
4、发现数据存在差异
![IMG_20230826_105817](https://github.com/metersphere/metersphere/assets/56757548/6cb31344-269d-4e4d-8f19-0d07028fffcf)

### 期待的正确结果

两组数据保持一致

**Comment by zrfit** [comment]
您好，感谢反馈！计划内用例的创建和更新时间，显示的是计划关联用例的时间和用例执行的时间，而不是功能用例列表该用例的创建和更新时间，这2个地方的时间是独立显示的，不同模块对应的时间含义不同。
