### ISSUE TITLE
[BUG]在测试计划里，执行一条用例，先点击通过，再点击保存，会出现两天一模一样的记录

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26434]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.5-lts

### 使用外置数据库

否

### 问题描述

在测试计划里，执行一条用例，先点击通过，再点击保存，会出现两天一模一样的记录

### 重现步骤

1、新建一条功能用例
2、建立一个测试计划并关联这个功能用例
3、点击通过
4、点击保存
5、观察用例的变更记录，出现两样相同的变更记录
![Snipaste_2023-08-26_09-46-32](https://github.com/metersphere/metersphere/assets/56757548/bbd7ec84-797d-415b-9821-9249043bc268)

### 期待的正确结果

只出现一条变更记录

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.6-lts未复现该问题，建议升级尝试。

**Comment by kiwifruit-guo** [comment]
bug 复现：
请在列表模式下进行操作：
列表模式下，点击通过，再点击保存
来到系统设置-操作日志中，查看日志
你会发现出现两条一模一样的记录（操作时间也相同）
