### ISSUE TITLE
[BUG]接口测试-选择环境配置，修改通用配置里的参数值后没有生效

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#26430]
### MeterSphere 版本

v2.10.5.v2.10.6

### 使用外置数据库

否

### 问题描述

接口测试-选择环境配置，修改通用配置后里的参数值没有生效

### 重现步骤

1.选择接口测试里的环境配置
![image](https://github.com/metersphere/metersphere/assets/55130444/c1fa07ef-210d-4227-b2c4-be1fe9e9f14d)
2.修改环境配置的参数值，没有生效
![image](https://github.com/metersphere/metersphere/assets/55130444/9a7fcfc7-4736-4227-80c9-85f9739b513f)

### 期待的正确结果

可以在接口测试选择环境配置修改通用配置的参数值

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
