### ISSUE TITLE
[BUG]全局断言，自动化接口执行后，“断言”页签里，“内容”和“错误信息”列信息显示错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#26441]
### MeterSphere 版本

V2.10.5-；

### 使用外置数据库

否

### 问题描述

1、设置全局断言
2、自动化接口测试>>场景里只有一个接口，并且该接口循环3次；点击执行
3、【断言】页签里面的问题：
    1）第一个循环的断言：“内容”和“错误信息”显示都不正确：“内容”为变量名称；“错误信息”为空；“是否成功”的结果是正确的
    2）第二个循环的断言：“内容“依旧不正确：为第一个循环的内容；“错误信息”和“是否成功”正确
    3）第三个循环的断言：“内容“依旧不正确：为第二个循环的内容；

### 重现步骤

1、设置全局断言
2、自动化接口测试>>场景里只有一个接口，并且该接口循环3次；点击执行
3、【断言】页签里面的问题：
    1）第一个循环的断言：“内容”和“错误信息”显示都不正确：“内容”为变量名称；“错误信息”为空；“是否成功”的结果是正确的
    2）第二个循环的断言：“内容“依旧不正确：为第一个循环的内容；“错误信息”和“是否成功”正确
    3）第三个循环的断言：“内容“依旧不正确：为第二个循环的内容；

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/b726fe9c-7824-4b5e-8b59-97c4f3456556)
![image](https://github.com/metersphere/metersphere/assets/78218624/c01aa145-3809-4df5-88ae-cef22ea0e7ab)
![Uploading image.png…]()

**Comment by huangxine** [comment]
![image](https://github.com/metersphere/metersphere/assets/78218624/8912e26d-92f0-406d-82ff-6e4ec218cb2b)

**Comment by 13290445582** [comment]
您好，暂不支持这样使用，变量赋值在脚本断言中，断言是后执行的，变量必然拿不到值，可以理解 ${msg_1} 时，上下文还没有这个变量。感谢反馈，后续有问题请重新提issue。

**Comment by huangxine** [comment]
这是全局断言设置界面，如果输入ss，选择等于，下面的代码是自动生成的
![image](https://github.com/metersphere/metersphere/assets/78218624/cbb73672-551b-4a4b-bd96-8cee0fb7e3f9)
全局断言里，不支持“变量”赋值这种操作吗？
![image](https://github.com/metersphere/metersphere/assets/78218624/fc62d4d9-f3a9-41eb-8279-bffc82debc1b)
