### ISSUE TITLE
[BUG]自动化接口场景变量：本地上传的文件，选择“转存至文件管理”并且指定转存的模块，此转存的文件，没有被存储到指定的模块中，都存在了默认路径“所有文件”目录里

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#26442]
### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

[BUG]自动化接口场景变量：本地上传的文件，选择“转存至文件管理”并且指定转存的模块，此转存的文件，没有被存储到指定的模块中，都存在了默认路径“所有文件”目录里

### 重现步骤

[BUG]自动化接口场景变量：本地上传的文件，选择“转存至文件管理”并且指定转存的模块，此转存的文件，没有被存储到指定的模块中，都存在了默认路径“所有文件”目录里

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/90f9da9d-5a8c-4f51-bcf3-c85707854e43)
![image](https://github.com/metersphere/metersphere/assets/78218624/c91d4a71-b05b-493f-ba44-326ef3de33f0)
![image](https://github.com/metersphere/metersphere/assets/78218624/a865c937-9984-4f83-9fcf-292250aea284)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.6-lts未复现该问题，建议升级尝试。

**Comment by huangxine** [comment]
系统已经升级还是存在相同等问题。
你可以找以前的脚本，里面有CSV文件的，然后点击“转存至文件管理”。不会存在到指定的目录。或者下线微信我提供给你能复现问题 的系统。

**Comment by zrfit** [comment]
新增csv变量-本地上传-转存文件到指定模块正常，编辑csv变量转存文件到指定模块失败，计划v2.10.7-lts修复。
