### ISSUE TITLE
[BUG] 消息通知-测试计划完成，通知的通过率和metersphere报告里面的通过率小数点精度不一致，且未带百分号

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26440]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

消息通知-测试计划完成，通知的通过率和metersphere报告里面的通过率小数点精度不一致，且未带百分号

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/a9ebc01c-7dc8-48bc-950d-0740a125050b)
![image](https://github.com/metersphere/metersphere/assets/103925124/93605ff7-5fe1-410a-ab75-dfb0e20c38de)
![image](https://github.com/metersphere/metersphere/assets/103925124/47516ade-9b8f-4570-83e0-7a990c08e9dd)

**Comment by liuruibin** [comment]
您可以通过修改模版自行定制输出内容
