### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#26452]
### MeterSphere 版本

 v2.10.6-lts

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/42445400/8752b818-4fd8-4fd3-934e-f57abe15568e)
问题：脑图编写用例，有重复用例无法保存，脑图用例比较多无法定位到相应用例
建议：可以直接保存，或者优化提示给出具体用例信息（模块和用例名称）

**Comment by luty2018** [comment]
目前的设计是同一模块下用例名称唯一，所以无法保存。
你提到的“给出具体用例信息（模块和用例名称）” 这里其实已经很明确了，就是你所在的模块， 和你录入的用例名称，这个无需系统重复提示了吧。

**Comment by lyxlin** [comment]
不是，脑图里面写用例不会写一条保存一次，都是写了好几个模块几十条用例一起保存 完全不知道哪里重复了

**Comment by luty2018** [comment]
好的， 那我们调研看看， 是否能高亮提示
