### ISSUE TITLE
[BUG]通过idea生成：IDE插件同步到meterSphere不会把必传和非必传的信息同步过来。

### ISSUE THREAD

**Issue by 11374493** [metersphere/metersphere#26463]
### 联系方式

chengwenliang@sinopharm.com

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

IDE插件同步到meterSphere系统
![image](https://github.com/metersphere/metersphere/assets/143389545/bcd7c7db-b030-43b6-bc55-a0102dec9e6d)

IDE插件同步到meterSphere不会把必传和非必传的信息同步过来。
![image](https://github.com/metersphere/metersphere/assets/143389545/2aabedda-b742-407e-b8a7-9390fb33fed0)

### 重现步骤

IDE插件同步到meterSphere系统
![image](https://github.com/metersphere/metersphere/assets/143389545/bcd7c7db-b030-43b6-bc55-a0102dec9e6d)

IDE插件同步到meterSphere不会把必传和非必传的信息同步过来。
![image](https://github.com/metersphere/metersphere/assets/143389545/2aabedda-b742-407e-b8a7-9390fb33fed0)

**Comment by fit2-zhao** [comment]
暂不支持，目前仅支持通用的一些属性，如果需解析schema中一些特殊属性 可以自行二开，IDEA插件地址：
https://github.com/metersphere/metersphere-idea-plugin 。
