### ISSUE TITLE
[BUG]【性能测试】性能测试-资源文件处，上传.dat文件，提示上传成功，但是下面并没有显示出对应文件

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26460]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【性能测试】性能测试-资源文件处，上传.dat文件，提示上传成功，但是下面并没有显示出对应文件

### 重现步骤

【性能测试】性能测试-资源文件处，上传.dat文件，提示上传成功，但是下面并没有显示出对应文件
![image](https://github.com/metersphere/metersphere/assets/104960608/2d0032ee-fad8-4aab-8608-4518bb1c58d4)
![image](https://github.com/metersphere/metersphere/assets/104960608/8e2e68c9-11fa-459c-9180-d32594819dc3)

dat文件如下
[test.zip](https://github.com/metersphere/metersphere/files/12451773/test.zip)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
