### ISSUE TITLE
[QUESTION] mock功能是否支持文件上传和下载接口

### ISSUE THREAD

**Issue by zhjdhx** [metersphere/metersphere#26466]
### 请描述您的问题

如何使用当前版本，mock 文件上传和下载接口的响应
注意是mock不是请求，请给出示例，在社区和官方文档均未发现教程

**Comment by luty2018** [comment]
你好，目前还不支持这个功能

**Comment by luty2018** [comment]
v3.0已经支持这个功能， 欢迎下载使用
