### ISSUE TITLE
在执行用例页面，操作交互非常卡顿，我晕[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#2646]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
在执行用例页面，操作交互非常卡顿，我晕

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
操作流畅

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/117660632-fca5c100-b1cf-11eb-8e7e-b39df830e2b6.png)

**Comment by xulinde** [comment]
下个版本优化下
