### ISSUE TITLE
[BUG]用例的自定义字段的默认值在脑图模式下未生效

### ISSUE THREAD

**Issue by lvluostudio** [metersphere/metersphere#26469]
### 联系方式

wingle@qq.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

用例的自定义字段的默认值在脑图模式下未生效。也就是虽然设置了默认值，也设置了为必选，但是其值，仍然为空

### 重现步骤

1。用例模板设置了如下的值
![image](https://github.com/metersphere/metersphere/assets/8476051/32b3ea44-0095-4a00-9746-09480708ea96)
2。用脑图创建一个用例，这个自动自动的值为空。（如果不是脑图默认，则会正确填充默认值）
![image](https://github.com/metersphere/metersphere/assets/8476051/dc8d3ca3-f906-403e-880b-03bf2735c720)

### 期待的正确结果

脑图模式设计用例时，自定义字段也能正确填充默认值

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by song-cc-rock** [comment]
目前V2版本用例脑图编辑暂时不支持自定义字段, 也就是不支持模板中的自定义字段默认值自动填充展示, 但是后台对于脑图的保存已经做了自定义字段默认值处理.

**Comment by 13290445582** [comment]
v2.10.7已修复。
