### ISSUE TITLE
[QUESTION]响应体设置mock，没有得到mock数据

### ISSUE THREAD

**Issue by miaoyinjun** [metersphere/metersphere#26473]
### 请描述您的问题

响应体设置mock数据为@cname
![image](https://github.com/metersphere/metersphere/assets/5077893/03ab6be6-4693-432b-b16c-67dcd6112916)
实际请求mock环境得到的是@name，请问是我哪里配置不对吗
![image](https://github.com/metersphere/metersphere/assets/5077893/795c1637-282d-45a0-8e9e-5c751e1c81f4)

**Comment by Somebody-JIAN** [comment]
目前Mock服务的请求和响应中都暂时不支持mock数据
