### ISSUE TITLE
[BUG]【UI测试】当场景变量“i”设置数值类型，次数循环的次数${i}进行引用，发现该场景一步都不执行。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26475]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【UI测试】当场景变量“i”设置数值类型，次数循环的次数${i}进行引用，发现该场景一步都不执行。

### 重现步骤

【UI测试】当场景变量“i”设置数值类型，次数循环的次数${i}进行引用，发现该场景一步都不执行。
![1693215503790](https://github.com/metersphere/metersphere/assets/104960608/0d2821b0-398d-430b-b53a-e4b3659362e6)
![1693215519027](https://github.com/metersphere/metersphere/assets/104960608/dcb03b0d-bda0-4a53-953c-5cd8029261d4)

将 “i ”设置为字符串类型，可以看到，该场景正常运行。
![1693215545175](https://github.com/metersphere/metersphere/assets/104960608/acc6ed5d-1816-4e8f-82d4-703c9cfeeb7f)
![1693215594426](https://github.com/metersphere/metersphere/assets/104960608/ac7152dd-53f8-47b4-b370-45bd97629e1c)

脚本如下
[Metersphere_Ui_Metersphere.zip](https://github.com/metersphere/metersphere/files/12453135/Metersphere_Ui_Metersphere.zip)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
