### ISSUE TITLE
[BUG]关联评审用例时的过滤器不能选择自定义字段

### ISSUE THREAD

**Issue by lvluostudio** [metersphere/metersphere#26471]
### 联系方式

wingle@qq.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

1. 在关联评审用例时，过滤器不能选择自定义字段了。在 v2.10.5-lts 版本是可以根据自定义字段进行筛选的。如下图，不能选择自定义字段了
![image](https://github.com/metersphere/metersphere/assets/8476051/13cedc25-5c46-4a82-807c-1266b892435f)

2. 另外，也不能再计划结束日期后修改为归档状态，会提示“截止时间不能早于当前时间”。 当时测试计划就不存在这个问题

### 重现步骤

1. 给用例模版设置一个自定义字段
2. 创建评审计划后，给评审计划关联测试用例
3. 筛选用例时，尝试选择自定义字段，会发现找不到自定义字段了
4. 尝试将一个已经过期（结束日期已过）的评审计划修改为归档状态，会发现设置失败

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
