### ISSUE TITLE
[BUG] 测试计划添加自动化场景，场景中引用了其他场景的脚本，添加脚本变量，执行测试计划，引用不生效。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26474]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

有A,B,C 三个场景，其中 A场景中有自定义脚本，有场景变量。B和C场景引用了A场景。接着新建测试计划，把B，C场景添加到测试计划中。然后再在A场景中添加一个新的变量，并打印。接着执行测试计划，发现刚才添加的变量并未打印。

https://github.com/metersphere/metersphere/assets/33945037/7387042d-0552-4e43-8c85-ed87d18e5c64

### 重现步骤

1. 创建三个场景,A,B,C
2. 其中两个场景B,C 引用同一个场景A .
3. A场景是一个自定义脚本，里面用到场景变量，然后脚本中打印日志。
4. 新建测试计划，关联BC两个场景，然后在A场景中添加场景变量，并打印日志。
5. 执行测试计划，查看报告。发现日志中没有打印新添加的变量

**Comment by zrfit** [comment]
您好，感谢反馈！按您的操作步骤在最新版本v2.10.6-lts版本未复现，场景B中是否也有同名的变量？

**Comment by hao65103940** [comment]
> 您好，感谢反馈！按您的操作步骤在最新版本v2.10.6-lts版本未复现，场景B中是否也有同名的变量？

我就是在V2.10.6-lts复现的，你好好看看视频，场景A是个脚本，BC场景引用的场景A。

**Comment by zrfit** [comment]
就是按上述步骤操作多次都未复现，已跟研发反馈，私下沟通看下。

**Comment by fit2-zhao** [comment]
已经确认是复制场景-场景变量设置默认值问题，暂时规避方法：场景变量设置-勾选 ”优先使用当前场景变量，没有则使用原场景变量“就可以解决。

<img width="1009" alt="image" src="https://github.com/metersphere/metersphere/assets/70558837/87b4fe98-2b77-4088-979f-066c51607510">
