### ISSUE TITLE
[BUG] 当授权项目成员角色，并且没有查看缺陷权限的时候，点击查看用例，会跳转到系统设置的页面。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26486]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/33945037/648d955c-30ba-4458-9200-8aceea506ae9

### 重现步骤

1. 创建新用户，授权项目成员角色
2. 编辑项目成员角色，去掉测试跟踪-》查询缺陷权限。
3. 使用新用户登录，功能列表随便点击一个查看，就会跳转到系统设置页面。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复。

**Comment by 13290445582** [comment]
v2.10.7已修复。
