### ISSUE TITLE
[BUG]【接口测试】接口自动化场景-自定义请求，当接口地址里含有变量，勾选引用环境，${变量名}的{}就会被转义编码成其他字符串

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26488]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【接口测试】接口自动化场景-自定义请求，当接口地址里含有变量，勾选引用环境，${变量名}的{}就会被转义成其他字符串

### 重现步骤

【接口测试】接口自动化场景-自定义请求，当接口地址里含有变量，勾选引用环境，${变量名}的{}就会被转义编码成其他字符串
![ea8f3692bde24db1b68cfc13e0d59fd](https://github.com/metersphere/metersphere/assets/104960608/f05e1aa7-f3c1-491e-9286-8f32b89c50ff)
![5bf68155cfc1da627f2b3743d2b696e](https://github.com/metersphere/metersphere/assets/104960608/be79b381-c52e-4439-80ff-c8a86bea4b9c)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复。

**Comment by 13290445582** [comment]
v2.10.7已修复。
