### ISSUE TITLE
[BUG]【UI测试】当设置变量值为true，然后在后置断言该值是否为true时，断言不了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26484]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【UI测试】当设置变量值为true，然后在后置断言该值是否为true时，断言不了。

### 重现步骤

【UI测试】当设置变量值为true，然后在后置断言该值是否为true时，断言不了。
![1693279513031](https://github.com/metersphere/metersphere/assets/104960608/72db4ee5-f1b8-480a-98f4-bee1a000d18e)
![1693279533680](https://github.com/metersphere/metersphere/assets/104960608/7a948de0-129c-4025-a241-c93894e5d6aa)
![1693279544715](https://github.com/metersphere/metersphere/assets/104960608/c14b6ec9-db10-43f7-b94e-500fd3a1475a)
![1693279575712](https://github.com/metersphere/metersphere/assets/104960608/0e8209d3-d9b5-449e-b445-d9caca9bd147)
![1693279592223](https://github.com/metersphere/metersphere/assets/104960608/cb18e06a-e1f9-4366-a600-8e03c2ca883d)

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.7-lts无该问题，待发布后升级尝试。
