### ISSUE TITLE
[FEATURE] 交互优化建议，目前编写自动化脚本、脑图写用例等不会有自动保存功能，有时候误关页面会导致写过的内容丢失，希望加个自动保存功能

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26496]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

[FEATURE] 交互优化建议，目前编写自动化脚本、脑图写用例等不会有自动保存功能，有时候误关页面会导致写过的内容丢失，希望加个自动保存功能

### 请描述你建议的实现方案

添加自动保存功能

**Comment by luty2018** [comment]
感谢建议， 目前在关闭页面时，系统判断有未保存的内容， 会发起提醒用户保存的弹窗。
自动保存目前还不支持，我们正在调研中。

**Comment by opopjasica** [comment]
直接点浏览器tab页的X不会保存，坐下自动保存会比较方便

**Comment by luty2018** [comment]
> 直接点浏览器tab页的X不会保存，坐下自动保存会比较方便

建议你升级到最新版本，切tab页的保存提醒已经支持了。
