### ISSUE TITLE
[FEATURE] 性能测试，希望支持脚本调试查看类似结果树功能，

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26499]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

性能测试，希望支持脚本调试查看类似结果树功能，

目前跑的结果只能一次跑完看到结果，希望可以在执行的过程中就看到测试结果，方便做调试参考。
目前也不能编辑脚本，如果能看到脚本定义好的的组件内容之类的就更好了，做测试更直观一些

**Comment by luty2018** [comment]
查看结果树的功能， 我们在规划了， 预计在2.10.8版本上线。编辑脚本目前建议导入到接口场景中进行编辑，再转为性能测试。

**Comment by Somebody-JIAN** [comment]
查看结果树这个功能我们评估后，并不打算做。因为：

1.性能测试过程中会发送上百万个请求，结果树是绑定在每一个请求上的，不知道如何查看
2.性能测试执行过程中，会定时整理当前的执行情况，tps、成功、失败、response time 等等
3.截至到当前回复日期的版本中，企业版增加了每种响应结果的前三条采样，您可以体验一下

综上，我们觉得不必再增加查看结果树功能了。
整体执行过程可监控
不同响应结果有采样
整体执行效率会更好
