### ISSUE TITLE
[FEATURE]ui测试查找元素希望支持 （隐式等待），ui元素有时候页面加载需要等待时间，目前只能加硬等待

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26497]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

[FEATURE]ui测试查找元素希望支持 （隐式等待），ui元素有时候页面加载需要等待时间，目前只能加硬等待

selenium 本身也支持这个功能，加上更好用

**Comment by Hyyfit** [comment]
MS内置了隐式等待，默认元素的操作等待时间是15s。
MS也支持显示等待，可设置等待时间；
![image](https://github.com/metersphere/metersphere/assets/95834771/c8a025c4-0e74-4afa-93f3-342f5ada6a6e)

**Comment by opopjasica** [comment]
隐式等待时间能不能也放出配置来自己配置呢

**Comment by luty2018** [comment]
v3 我们放到配置文件供用户自行修改
