### ISSUE TITLE
不知道在TAPD关闭的缺陷对应哪条用例，很难去MS平台修改用例的状态 ，我晕[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#2649]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
不知道在TAPD关闭的缺陷对应哪条用例，很难去MS平台修改用例的状态 ，我晕

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
在TAPD缺陷里最好可以查看并追溯到对应的用例

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/117744219-d5d0a480-b23a-11eb-808b-4e488e88193f.png)
![image](https://user-images.githubusercontent.com/37016695/117744249-e08b3980-b23a-11eb-8c64-fd7a8e389ce9.png)
![image](https://user-images.githubusercontent.com/37016695/117744271-ec76fb80-b23a-11eb-8c67-97503aedfecd.png)

**Comment by zyyfit** [comment]
后续版本优化
