### ISSUE TITLE
[FEATURE] 性能测试引用接口自动化-接口自动化更新后，每次转性能测试都需要重新在关联一下，希望可以做个一键同步最新脚本功能

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26498]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

性能测试引用接口自动化-接口自动化更新后，每次转性能测试都需要重新在关联一下，希望可以做个一键同步最新脚本功能

### 请描述你建议的实现方案

![image](https://github.com/metersphere/metersphere/assets/114552960/2d4dfe28-6c4b-401e-a10c-c2afed429a83)

**Comment by luty2018** [comment]
<img width="1475" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/8c103356-eb6d-4350-87fd-0183d1625772">
这里可以直接同步哦。
