### ISSUE TITLE
[FEATURE]性能测试执行结果之前的对比，或者以某个作为基线的对比结果是否有计划？

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#265]
**请描述您的需求或者改进建议.**

性能测试执行完成后，报告内容相对独立，希望能够增加选择多个报告（或者以某个报告作为基线）的对比性视图页面，可以作为日常性能测试的一个结果参考

**请描述你建议的实现方案**
简单标识以某个报告为基线后，其他报告的性能上升下降的对比页面

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，计划下个版本实现该需要，请您持续关注～

**Comment by youliyuan-fit2cloud** [comment]
v1.9.0 版本已实现该需求
