### ISSUE TITLE
【接口测试-场景】建议企业微信推送的场景测试报告，无需登录系统，可以直接在网页上查看。

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#2650]
【接口测试-场景】建议企业微信推送的场景测试报告，无需登录系统，可以直接在网页上查看。
提出原因：监控群聊中有很多开发，运维等其他工种，他们只关注错误的信息，无需登录系统操作，所以每次他们都需要登录的话，一个是账号权限不好弄，另一个是操作繁杂。

**Comment by zyyfit** [comment]
您好，您的需求可以理解，但是不登陆系统就可以查看报告的话，会有信息泄漏的风险
