### ISSUE TITLE
[BUG]  oauth认证-三方登录成功后回调metersphere，metersphere的地址被转发为https

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26509]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

oauth认证方式-三方登录成功回调metersphere时，metersphere的地址被转发为https

### 重现步骤

metersphere本身的地址是http；
配置的oauth认证地址是https；
![image](https://github.com/metersphere/metersphere/assets/103925124/97d7c36f-d0c8-440d-87dc-256373b1a84d)
![1693366439212](https://github.com/metersphere/metersphere/assets/103925124/454a375d-a855-41cf-b6b9-67843fdcd662)

### 期待的正确结果

转发到metersphere回调地址是http

**Comment by shenkaibo** [comment]
https://github.com/metersphere/metersphere/issues/22653

**Comment by 13290445582** [comment]
已提tapd。

**Comment by 13290445582** [comment]
你好，在测试环境未复现该问题，检查github配置。
![image](https://github.com/metersphere/metersphere/assets/128017892/f373f4bb-e833-450d-a5cc-bd13636aaa52)

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
