### ISSUE TITLE
[BUG]场景 csv 文件转存至文件管理，无法存至指定的模块

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26518]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

场景 csv 文件转存至文件管理，无法存至指定的模块

### 重现步骤

1. 场景中 csv 文件转存至文件管理
![image](https://github.com/metersphere/metersphere/assets/103627487/ed57c9f6-a9b8-42db-960c-1203ed9a9d58)
2.选择test 模块，dian'ji点击确定，显示操作成功
![image](https://github.com/metersphere/metersphere/assets/103627487/b8c96e52-88ab-4c11-92d6-7735a1ed0f6e)
![image](https://github.com/metersphere/metersphere/assets/103627487/8d3f0ad7-4d67-4d11-8e64-b22a1ce62567)
3.到项目设置文件管理里查看,发现test 模块下没有，在默认模块下
![image](https://github.com/metersphere/metersphere/assets/103627487/778b4205-8909-4203-8d4b-fdf0a82da739)
 
上述操作，若第一次转存至文件管理对应模块成功，可删除文件管理文件，多次尝试可复现

**Comment by 13290445582** [comment]
重复问题https://github.com/metersphere/metersphere/issues/26442
