### ISSUE TITLE
[BUG]【UI测试】环境配置里设置了UI变量，在foreach控制器下的前置脚本里，获取该变量然后将其返回，没有获取到值

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26512]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【UI测试】环境配置里设置了UI变量，在foreach控制器下的前置脚本里，获取该变量然后将其返回，没有获取到值

### 重现步骤

【UI测试】环境配置里设置了UI变量，在foreach控制器下的前置脚本里，获取该变量然后将其返回，没有获取到值
![image](https://github.com/metersphere/metersphere/assets/104960608/49112f11-b40d-4138-90df-1f70519304a6)
![image](https://github.com/metersphere/metersphere/assets/104960608/93b5e8dd-8565-44ec-a653-a5c64dcf5bad)
![image](https://github.com/metersphere/metersphere/assets/104960608/ca7cbd97-c727-484e-9337-9ee57ff4b0f2)
![image](https://github.com/metersphere/metersphere/assets/104960608/53d9305e-dbcf-4509-b171-86d7de35bd5c)

**Comment by zrfit** [comment]
您好，感谢反馈！同问题#23501。
