### ISSUE TITLE
[QUESTION]安装的最新版本没有禅道服务集成。

### ISSUE THREAD

**Issue by bohaiwangzi** [metersphere/metersphere#26528]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/13211575/647fc7cc-b192-4c70-ace4-5a86b3aeb896)
安装的最新版本没有禅道服务集成，这个是什么问题？

**Comment by bohaiwangzi** [comment]
![image](https://github.com/metersphere/metersphere/assets/13211575/5c7779dc-bab5-43cc-be18-898eb2c5131d)
版本v2.10.6-lts

**Comment by tomseanmy** [comment]
https://github.com/metersphere/metersphere-platform-plugin/releases/tag/v2.10.5
需要下载禅道插件，用admin进入ms点击插件管理->上传插件->下拉选择平台对接->上传metersphere-zentao-plugin-2.x-jar-with-dependencies.jar 再回去看就有了
