### ISSUE TITLE
[BUG]IDEA插件：配置信息test测试后，提示成功，但是项目的版本信息没有拉取。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#26529]
### MeterSphere 版本

V2.10.6-lts

### 使用外置数据库

否

### 问题描述

MS版本：2.10.6-lts
IDEA插件版本：1.2.5

在插件配置信息界面，点击【test】测试链接后，相关的版本信息下拉框里的信息没有被更新，必须来回切换项目后，版本信息才会被拉取

### 重现步骤

MS版本：2.10.6-lts
IDEA插件版本：1.2.5

在插件配置信息界面，点击【test】测试链接后，相关的版本信息下拉框里的信息没有被更新，必须来回切换项目后，版本信息才会被拉取

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/b80fc0db-ed81-47b4-9dcf-dbe34f4cf893)

![image](https://github.com/metersphere/metersphere/assets/78218624/9d249775-d952-4263-8f27-bdae43e51c43)

![image](https://github.com/metersphere/metersphere/assets/78218624/98ea2e2a-2cce-414e-a91b-055808b686d6)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。
