### ISSUE TITLE
[BUG]自动化场景中，编辑运行环境的问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#26525]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

在接口测试模块，自动化场景中，运行环境配置那里，修改一个运行环境的通用配置变量，无法修改成功。
![image](https://github.com/metersphere/metersphere/assets/66937739/de7f64e7-67ca-4b30-aa29-6abff45e7725)

### 重现步骤

1、创建自动化场景
2、随便写个场景名称，并添加一个自定义请求步骤
3、点击运行环境下拉框
4、点击环境配置
5、新加一个运行环境
6、设置一个通用配置变量
7、点击确定
8、在自定义请求步骤打印新建的运行环境变量
9、修改这个运行环境变量值，保存
10、再次打印、打印的还是新建时候的值。

### 期待的正确结果

期望修改值成功

_No response_

### 相关日志输出

保存运行环境变量，发出的值，是修改前的值。

_No response_

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复。
