### ISSUE TITLE
[FEATURE]性能测试的RPS控制组件为Throughput Shaping Timer，但实际MS的性能测试中无法做RPS的梯度控制，建议优化支持

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#26537]
### MeterSphere 版本

V2.10.6lts

### 请描述您的需求或者改进建议

性能测试在开启RPS后，下载报告中的执行文件中，RPS为梯度控制组件：Throughput Shaping Timer，但实际MS的性能测试中无法做RPS的梯度控制，建议优化支持

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/92150453/d39e2704-bdbf-45e6-9284-0bbc255bdbeb)
![9089bbd80f9a57bb189ac528f4205a9](https://github.com/metersphere/metersphere/assets/92150453/3dad34f2-493d-4036-94c4-478590a5309e)

**Comment by liuruibin** [comment]
您好，目前确实只能配置一条。v2中不再进行修改，v3.0规划。
