### ISSUE TITLE
[BUG]在线/离线安装获取包失败

### ISSUE THREAD

**Issue by pwang123** [metersphere/metersphere#26536]
### 联系方式

wang.ping1@navercorp.com

### MeterSphere 版本

v2.10.6-lts
v2.10.5-lts

### 使用外置数据库

否

### 问题描述

1、使用在线安装时，连接正常，获取包时提示Permission denied

2、使用离线安装时，使用wget获取包时，提示download 成功，但只下载了index.html

### 重现步骤

在线：
   执行命令：sudo curl -sSL https://resource.fit2cloud.com/metersphere/metersphere/releases/latest/download/quick_start.sh | bash
离线：执行命令：sudo wget https://community.fit2cloud.com/#/products/metersphere/downloads/v2.10.5-lts

### 期待的正确结果

在线：安装成功
离线：安装包下载成功

### 附加信息

在线logs:
![1693466496](https://github.com/metersphere/metersphere/assets/143693610/6566d287-3ef5-4a6f-af18-b50a092ab360)

离线logs：
![1693466694](https://github.com/metersphere/metersphere/assets/143693610/a3e04706-52bf-400f-ad12-ef1ae0f6d1f2)

**Comment by liqiang-fit2cloud** [comment]
在线：报错是permission denied, cannot write to...，请检查在当前目录有没有写权限。
离线：下载链接不对。离线下载需要登录，在浏览器里登录https://community.fit2cloud.com，然后选择相应的版本进行下载，这时候会生成有签名的下载链接并在浏览器里开始下载，如果要在服务器上下载就用有签名的链接。
