### ISSUE TITLE
[BUG][Cloud]在项目只有UI自动化用例的情况下，测试计划添加定时任务，保存失败，报错未选择资源池

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#26535]
### MeterSphere 版本

V2.10.6lts--Cloud

### 使用外置数据库

否

### 问题描述

Cloud环境上，在只创建了UI用例，接口、性能模块均未使用，且项目管理-应用管理-接口测试中未指定资源池的情况下，创建测试计划-关联UI用例，并设置定时任务时，保存失败并报错未选定资源池

### 重现步骤

见问题描述

### 期待的正确结果

在问题描述的基础上，纯UI用例的测试计划，设置定时任务能正常保存

### 附加信息

![de76451e2a89305b5f51d1d3d51b632](https://github.com/metersphere/metersphere/assets/92150453/326f84ab-144b-4ebf-8547-3b0a04069377)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。
