### ISSUE TITLE
[BUG]IDEA插件同步接口，中文描述最后一个字为乱码

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#26530]
### MeterSphere 版本

V2.10.6-lts

### 使用外置数据库

否

### 问题描述

IDEA插件版本：1.2.5

IDEA插件同步接口，中文描述最后一个字为乱码

### 重现步骤

IDEA插件同步接口，中文描述最后一个字为乱码

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/c7c9b14f-0543-4b9c-acb2-c0ee82f7e73d)

![image](https://github.com/metersphere/metersphere/assets/78218624/58b53e74-3496-4904-adc6-517517ca4b11)

**Comment by 13290445582** [comment]
<img width="539" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/d2d6a24d-42e5-4eac-924f-234001f4d709">
您好，通过使用同样的源码接口同步，未复现您所描述的问题，初步排查可能为您本身IDEA编码问题。

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
