### ISSUE TITLE
[BUG] 接口自动化导入-->MeterSphere格式的用例报错：Connection prematurely closed BEFORE response

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#26533]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

MeterSphere 版本：v2.10.6-lts-e87e920c
运行方式(安装包运行)、

接口自动化导入–>MeterSphere格式的用例报错：Connection prematurely closed BEFORE response

/api/api/automation/import

{“success”:false,“message”:“Connection prematurely closed BEFORE response”,“data”:null}

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/23476281/8a5fc07b-cdad-49fe-9250-bd2675454c6b)

**Comment by 13290445582** [comment]
您好，可以将导入的MeterSphere格式的场景提供下，邮箱：yicheng.wang@fit2cloud.com

**Comment by 13290445582** [comment]
该问题长时间未反馈，暂时关闭该issue，可等待最新版本发布，再进行尝试是否出现此情况，后续有问题可重新提issue，感谢您的理解与支持。
