### ISSUE TITLE
功能测试，功能用例评论消息问题[BUG]

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#26542]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

基于消息模板，功能用例评论，给创建人发送站内消息。
![image](https://github.com/metersphere/metersphere/assets/66937739/f6ae2fcb-e92b-4e12-884a-1de1f0c4d02f)
功能测试模块中，新建一个功能用例，添加一条评论，消息中心没有新消息。
![image](https://github.com/metersphere/metersphere/assets/66937739/b9cd7662-0e60-4928-ab3a-350e75f9250e)
![image](https://github.com/metersphere/metersphere/assets/66937739/479da8c7-a62a-4c56-b1f2-8b8d5ff772ba)

### 重现步骤

1、确定消息模板中，功能测试有评论发送站内通知的任务
2、新建一个功能用例
3、新建一个评论
4、查看消息中心

### 期待的正确结果

有消息可以接收

**Comment by 13290445582** [comment]
您好，当前操作用户为创建人时，不会发送站内信通知，使用其他账号登录，进行操作，接收人会收到站内信通知。
