### ISSUE TITLE
[FEATURE]【缺陷管理】添加已解决按钮，【消息设置】细化消息模板功能

### ISSUE THREAD

**Issue by tomseanmy** [metersphere/metersphere#26556]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 联系方式

tom_sean@outlook.com

### 请描述您的需求或者改进建议

1.【缺陷管理】在缺陷列表和详情中添加【已解决】按钮，快速标记缺陷状态为已解决并填写解决方案或者备注。
2.【缺陷管理】在缺陷详情中加入操作记录，如张三创建了缺陷，李四指定/确认了缺陷，王五解决了缺陷，张三关闭了缺陷。
3.【消息设置】消息提示里加入变量字段，如“更新：[处理人][$status]了缺陷 @link[$id]” -> "更新：@张三 解决了缺陷[链接@100010]"，实现可以在飞书或企业微信里面一键打开对应的缺陷和提示细化的缺陷更新状态。

**Comment by luty2018** [comment]
感谢建议 ，这个功能我们已经规划在v3.0版本了

**Comment by tomseanmy** [comment]
期待，现在缺陷管理部分确实有点弱，v3.x版本预计是什么时候发布呢？

**Comment by luty2018** [comment]
第一个版本预计在年底
