### ISSUE TITLE
接口响应体内容和提取参数、断言判断中的JSONPath提取展示出来的值不一致，导致参数提取和断言判断失败

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26550]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

运行接口场景，响应成功，但是响应体内容和提取参数、断言判断中的JSONPath提取展示出来的值不一致，导致参数提取和断言判断失败

### 重现步骤

1. 场景中包含多种引入场景，接口，判断，循环和等待时间
2. 调试场景，响应成功，但是响应体内容和提取参数、断言判断中的JSONPath提取展示出来的值不一致
3. 结果导致参数提取和断言判断失败

### 期待的正确结果

响应体内容和提取参数、断言判断中的JSONPath提取展示出来的值一致

### 相关日志输出

```shell
无
```

### 附加信息

![ab9381e8789fe464bb105962dbacc64](https://github.com/metersphere/metersphere/assets/50016789/d9dd457a-80f8-4819-84df-affa2d996fc5)

**Comment by 13290445582** [comment]
您好，该问题多次尝试未复现，也无其他用户反馈，暂时无法复现，可待后续有复现步骤，再重新提issue，我们后续也会关注该情况，感谢您的理解与支持。
