### ISSUE TITLE
[BUG]xmind用例导入后，MeterSphere中脑图和本地文件顺序相反

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#2656]
**MeterSphere 版本**
版本: v1.9.0-e6a9556e

**Bug 描述**
xmind用例导入后，MeterSphere中脑图和本地文件顺序相反

**Bug 重现步骤**
1.  本地xmind文件导入用例

**期待的正确结果**
期待结果：metersphere中脑图用例顺序同本地xmind文件一致

**截图**
xmind正确顺序：
![image](https://user-images.githubusercontent.com/49704984/117755531-f7d42200-b24e-11eb-9b08-c117a75bec60.png)

导入后的顺序不正确：
![image](https://user-images.githubusercontent.com/49704984/117755372-a9268800-b24e-11eb-8183-9bddfc38fb27.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题
