### ISSUE TITLE
[BUG]接口场景编辑页面，展开接口详情时编辑接口名称，光标

### ISSUE THREAD

**Issue by hslzyd** [metersphere/metersphere#26575]
### 联系方式

MeterSphere 交流群59

### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

接口场景编辑页面，有接口详情展开时，若点击接口名称编辑，光标会自动跳到请求体输入框中，无法编辑接口名称
![image](https://github.com/metersphere/metersphere/assets/8504229/7aa52b47-30de-43c4-80ed-bbbd000a31d6)

### 重现步骤

1、接口场景编辑页面
2、展开一个或多个接口详情，并切换请求体到json文本录入
3、点击任意接口请求的名称，编辑名称——光标自动跳到请求体输入框去了

### 期待的正确结果

光标不乱跳

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.7-lts将无该问题，待发布后升级尝试。
