### ISSUE TITLE
[FEATURE]接口自动化中场景用例增加前后置

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#26589]
### MeterSphere 版本

2.9.1

### 请描述您的需求或者改进建议

现在初始化工作和后置工作都是写在场景里面的，在运行时我这边是勾选失败不继续的，这样就有个弊端，代码中间失败想要执行的后置代码就无法被执行。

### 请描述你建议的实现方案

能够在场景中设置前置后置类似jmeter的setUp线程组和tearDown线程组，这样执行起来前后置和真正的场景就可以互不干扰

**Comment by luty2018** [comment]
你好， 目前我们已经支持这个功能了。
<img width="1011" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/121f2054-ce36-4270-84b0-886d707f19de">

**Comment by wszbc** [comment]
> 你好， 目前我们已经支持这个功能了。 <img alt="image" width="1011" src="https://user-images.githubusercontent.com/36292514/266268424-121f2054-ce36-4270-84b0-886d707f19de.png">

你这个是全局的跟我说的还是有点差别我说的是场景本身的，我的每个场景都有自己需要初始化的前后置，你现在是全局有前后置，接口有前后置，唯独场景没有前后置

**Comment by luty2018** [comment]
那你可以在场景的第一步和最后一步各加一个自定义脚本就行。我们全局的前后置也是通过自定义脚本去实现的

**Comment by wszbc** [comment]
我现在就是这样做的但是无法实现我开题说的效果，
我希望的效果是前置->执行场景->后置，
但实际执行会出现前置->执行场景（失败不继续），后置不会执行，由于公司现在就是失败的用例本身继续跑没有意义未勾选失败继续，所以希望的是前置->执行场景（不论失败成功）->后置，这样就可以让前置和后置不受真正的用例成功失败影响，我的前置后置主要是调接口配置一些开关，A场景失败了，开关还原，B场景还能继续使用，如果A失败了没有还原，那后面其它场景就都可能会受到影响了。
之所以不用全局是因为每个场景都需要有自己的前置后置，可能重叠也可能不重叠，没法统一加到全局前置后置里

**Comment by luty2018** [comment]
您好， 这个我们已经在v3.0中支持了， 欢迎下载使用。
<img width="750" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/c8be39b1-ac79-4bd4-8e49-a273ea437402">
