### ISSUE TITLE
测试用例关联jira需求，希望能增加需求模板，根据模板设置过滤的字段过滤要同步的需求，现在同步出来的需求几千条，没法有效与用例关联，

### ISSUE THREAD

**Issue by liuqi132** [metersphere/metersphere#26594]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

测试用例关联jira需求，希望能增加需求模板，根据模板设置过滤的字段过滤要同步的需求，现在同步出来的需求几千条，没法有效与用例关联，

### 请描述你建议的实现方案

测试用例关联jira需求，希望能增加需求模板，根据模板设置过滤的字段过滤要同步的需求，现在同步出来的需求几千条，没法有效与用例关联，

**Comment by AgAngle** [comment]
你好，关于需求过滤，针对不同用户，可能过滤的要求不一样，目前没有做对应的功能，如果有需要可以自行修改下插件，在项目配置页面添加需要过滤的字段，查询需求的时候根据填写的字段，过滤需求即可，插件开发参考：https://github.com/metersphere/metersphere-platform-plugin/wiki/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97
