### ISSUE TITLE
[BUG]【UI测试】场景里含有文件上传步骤，将该场景导出后再导入，发现没有文件上传步骤。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26598]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

【UI测试】场景里含有文件上传步骤，将该场景导出后再导入，发现没有文件上传步骤。

### 重现步骤

【UI测试】场景里含有文件上传步骤，将该场景导出后再导入，发现没有文件上传步骤。
![image](https://github.com/metersphere/metersphere/assets/104960608/e3be0ebc-28e1-424b-acdb-5eb579a7f644)
![image](https://github.com/metersphere/metersphere/assets/104960608/88b10a07-3794-42d0-9469-dd1fe0cd8500)

**Comment by zrfit** [comment]
您好，感谢反馈！文件上传为metersphere的扩展功能，v2暂不支持导出为ide格式，v3支持导出为metersphere格式后，则可解决该问题。
