### ISSUE TITLE
[FEATURE]能否增加一些脚本支持接口请求参数的动态修改

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#266]
**请描述您的需求或者改进建议.**

能否增加一些脚本支持接口请求参数的动态修改

**请描述你建议的实现方案**
通过对每个接口配置一个脚本文件，通过脚本中的逻辑算法动态生成并修改请求报文中某些字段值，达到可以支持脚本长期重用的结果
举例：
比如某个接口的请求参数是日期，那么根据自定义脚本日期可以动态生成，如每天运行脚本的时候都会生成当天日期去请求接口

**Comment by wangzhen-fit2cloud** [comment]
你好，在即将发布的 v1.2 版本中会有内置函数功能，可以满足你提到的这个场景

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已支持该功能，请升级体验。
