### ISSUE TITLE
[BUG]接口自动化场景，不选择环境进行调试时无“请先选择运行环境”提示

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#26617]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

创建一个接口自动化场景，引用完case步骤后，点击“保存”，点击“调试”时，不会提示“请先选择运行环境”，直接运行失败。
<img width="1285" alt="截屏2023-09-06 上午11 12 42" src="https://github.com/metersphere/metersphere/assets/34637801/ee0dba41-184d-4408-9071-50a70cca67be">

### 重现步骤

1.创建一个接口自动化场景
2.引用接口case作为场景步骤
3.点击“保存”
4.点击“调试”

### 期待的正确结果

点击“调试”时会提示“未选择运行环境”

**Comment by zrfit** [comment]
您好，去掉环境强校验是v2.10.6-lts专门做的优化，当前项目和跨项目环境都非必填，减少程序校验的复杂性，提高性能，用户通过执行测试自行排查环境问题。
