### ISSUE TITLE
[FEATURE]希望接口测试/接口自动化测试中支持图片类型的接口

### ISSUE THREAD

**Issue by chenj7918** [metersphere/metersphere#26624]
### MeterSphere 版本

 v2.10.6-lts-e87e920c

### 请描述您的需求或者改进建议

[希望接口测试/接口自动化测试中支持图片类型的接口，在测试过程中发现若接口格式为图片，会出现乱码情况，不太友好。实际测试场景中，会出现例如：登录含验证码的接口，验证码为单独的接口返回，且该接口为图片格式，在MS测试过程中会出现乱码情况。感谢~
![微信截图_20230906122317](https://github.com/metersphere/metersphere/assets/127493065/d5a4db43-9a97-4adb-af08-22babcb6b937)
![微信截图_20230906122542](https://github.com/metersphere/metersphere/assets/127493065/314c7e9d-889f-4bed-8c56-849c14ebe917)

### 请描述你建议的实现方案

可参考postman、apifox等工具对图片格式接口的支持

**Comment by luty2018** [comment]
已经规划在v2.10.8版本中， 请关注后续版本发布

**Comment by luty2018** [comment]
v2和v3已同步支持。
