### ISSUE TITLE
[FEATURE]【功能用例】移动、复制、修改模块时，希望能同步更新test_case表的node_path

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26627]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

test_case表的node_path存储的是模块路径信息，但移动、复制、修改模块时，没有同步更新test_case表的node_path，我们用DataEase统计功能用例时，会根据node_path统计功能用例的数量，当移动、复制、修改模块时，node_path没有同步更新，导致大屏功能用例数量不对

### 请描述你建议的实现方案

移动、复制、修改模块时，希望同步更新test_case表的node_path

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/70568050-7585-44ad-99e6-97755454df5c)
![image](https://github.com/metersphere/metersphere/assets/45531073/271fe0d7-9544-42d6-b032-0f8f5f3d55c0)

**Comment by AgAngle** [comment]
你好，这个字段由于维护成本较高，弃用了，如果你想统计，需要查询 test_case  表结合 test_case_node  表进行统计
