### ISSUE TITLE
[BUG] 含有python脚本的接口自动化场景转化成性能测试，压测时TPS上不来

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26631]
### MeterSphere 版本

V2.10.6-lts

### 使用外置数据库

否

### 问题描述

含有python脚本的接口自动化场景转化成性能测试，压测时TPS上不来。
但是同样的脚本放在jmeter上，tps可以跑起来。

![image](https://github.com/metersphere/metersphere/assets/33945037/881aed98-604d-44af-a730-9575b70299eb)

![image](https://github.com/metersphere/metersphere/assets/33945037/dd6ad613-7c53-44db-99cd-42ae900b08f8)

![image](https://github.com/metersphere/metersphere/assets/33945037/385f5b16-f6f7-4e88-9f56-ca2e19d4a3fb)

![image](https://github.com/metersphere/metersphere/assets/33945037/0dc31aeb-8f0b-41e8-bfe2-82eb5f177504)

### 重现步骤

在metersphere上的场景文件：
[Metersphere_Scenario_默认项目.txt](https://github.com/metersphere/metersphere/files/12535926/Metersphere_Scenario_.txt)

测试jmx脚本，可以直接在jmeter上跑。
[copy_python_1693989030177.txt](https://github.com/metersphere/metersphere/files/12535887/copy_python_1693989030177.txt)

服务器配置：8c16g
资源池：默认的node-controller
并发数：10
持续时间：60s

**Comment by liuruibin** [comment]
使用上方提供的jmx
cloud版
<img width="1941" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/8a39b047-e351-43ea-a34b-db5c042cb77c">
本地版
<img width="1638" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/fa727fd7-3113-42de-a8fa-dd92edf9019f">

表现一致

**Comment by liqiang-fit2cloud** [comment]
在研发环境测试也没问题。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～

**Comment by dragonleeee** [comment]
我也是这个情况 用python 写的签名脚本，tps就上不去
