### ISSUE TITLE
[FEATURE]-测试计划执行--失败重试时，希望能够定义重试间隔时间

### ISSUE THREAD

**Issue by 157571062297** [metersphere/metersphere#26645]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 联系方式

15757106297

### 请描述您的需求或者改进建议

如图这里的失败重试，实际运行时，请求失败是立即重试的，因为实际场景运用的时候，异步消费的问题会导致，前置等待器不好控制时间， 会出现失败情况，重试机制又是立即重试，所以失败重试机制没有实际作用

### 请描述你建议的实现方案

希望能够定义失败重试间隔时间

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/30097089/62b28ad0-afb1-44b0-a803-bbe70bcd1e44)

**Comment by luty2018** [comment]
感谢建议， 这个我们可以加一下。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
