### ISSUE TITLE
[BUG]使用chrome接口录制插件录制后，导出json文件到MS系统接口定义中导入，导入后列表的排序和录制列表排序不一致

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#26650]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.6lts

### 使用外置数据库

否

### 问题描述

使用chrome接口录制插件录制后，导出json文件到MS系统接口定义中，导入后列表的排序和录制列表排序不一致，在录制接口数量大的情况，手动重新排序非常费时。
<img width="960" alt="d9707d4227b72ccc823a9b7545606c5" src="https://github.com/metersphere/metersphere/assets/83771182/526df7b8-e381-4e93-85ef-e94d1a7e1f98">
<img width="732" alt="0174f4c788adcf4774fd67f0545848c" src="https://github.com/metersphere/metersphere/assets/83771182/4a808bb5-d46c-4f2f-a741-5993892ef053">

### 重现步骤

使用chrome接口录制插件录制后，导出json文件到MS系统接口定义中导入，导入后列表的排序和录制列表排序不一致

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。
