### ISSUE TITLE
[QUESTION]执行定时任务时，报错：[java.net.SocketTimeoutException: Connect timed out]

### ISSUE THREAD

**Issue by zhou-weijie** [metersphere/metersphere#26659]
### 请描述您的问题

日志见下图：
![image](https://github.com/metersphere/metersphere/assets/66190159/2d9074f7-81b7-466b-a9f1-e9185055e715)
红框中的链接我本机是可以正常访问的

**Comment by zhou-weijie** [comment]
ps：当前部署的版本是：v2.8.0-b5

**Comment by fit2-zhao** [comment]
检查一下站点的地址是否准确，可以复制图中红框标记的链接放到资源池所在的节点上curl ｜ wget 是否能正常下载文件。
