### ISSUE TITLE
IDEA插件 连接Metersphere 2.10.06 lts 提示connect fail [BUG]

### ISSUE THREAD

**Issue by mrxuying** [metersphere/metersphere#26660]
### 联系方式

756880285@QQ.COM

### MeterSphere 版本

2.10.06 lts

### 使用外置数据库

否

### 问题描述

IDEA插件(1.2.4) 连接Metersphere 2.10.06 lts 提示connect fail

### 重现步骤

按要求正确填写了server  及两个key值，点击test的时候提示connect fail

**Comment by zrfit** [comment]
您好，感谢反馈！idea插件版本为1.2.4测试连接和导入接口到metersphere v2.10.6-lts版本均成功，未复现该问题，建议检查下您的连接配置信息是否正确。
<img width="974" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/b00654d4-2719-487f-9e7b-0652eb9dd236">

<img width="595" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/23ef794c-0c8d-42e9-8aa9-f11428c30b67">
