### ISSUE TITLE
环境配置中环境名称为空时，删除提示内容出现undefined

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26667]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

环境配置中环境名称为空时，删除提示内容出现undefined

### 重现步骤

1. 选择系统设置项目管理的环境配置
2. 环境列表点击“+”新建环境，不填写名称，直接点击删除按钮，查看提示，删除提示内容出现undefined。

### 期待的正确结果

正常提示

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/4b2e0705-d117-4b3e-831e-24c13776069e)

**Comment by 13290445582** [comment]
您好，未命名显示undefined是正常的，请问您预期的正常显示是显示怎样的结果，可以说明一下。

**Comment by 13290445582** [comment]
经过沟通，目前设计上是采用的这种形式，感谢理解与支持，暂时关闭该issue，后续有问题可重新提issue。
