### ISSUE TITLE
系统设置项目管理的环境变量中修改通用配置的应用场景未生效

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26664]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

在系统设置项目管理的环境变量中，修改通用配置的应用场景，保存成功，但是重新打开页面发现未生效。

### 重现步骤

1. 在系统设置项目管理的环境变量中，修改通用配置的应用场景，
2. 保存成功，但是重新打开页面发现未生效。

### 期待的正确结果

期望修改应用场景成功

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/1ec41594-acaf-4bdc-9479-dfc0aeff1214)
![image](https://github.com/metersphere/metersphere/assets/50016789/4953f986-c589-4c82-a074-f59d8740c49e)

**Comment by zrfit** [comment]
您好，感谢反馈！同问题#26430，计划v2.10.7-lts修复。
