### ISSUE TITLE
项目管理列表翻页后重置查询状态，列表记录加载不正确

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26668]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

项目管理列表翻页后重置查询状态，列表记录加载不正确

### 重现步骤

1.项目列表翻至第二页
2.输入查询条件进行查询
3.清空查询条件，查看列表
4. 列表翻至第一页，但显示的仍是第二页的内容

### 期待的正确结果

列表翻页后重置查询状态，列表记录加载正确

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/dfde9845-4b56-4324-9231-0309396c5d4f)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，计划于v2.10.7版本修复。
