### ISSUE TITLE
缺陷管理中关联用例窗口，未过滤掉已关联用例，导致重复关联

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26675]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

缺陷管理中关联用例窗口，未过滤掉已关联用例，导致重复关联

### 重现步骤

1、创建缺陷时，打开用例关联窗口，关联了一条用例，点击确定

2、再次打开用例关联窗口，查看可关联用例，列表显示了所有用例，未过滤掉已关联的，导致重复关联。

### 期待的正确结果

再次打开用例关联窗口，查看可关联用例，列表过滤掉已关联的用例

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/bcf06f9c-a1d6-44c4-a9c7-6d3a9e93cfa4)
![image](https://github.com/metersphere/metersphere/assets/50016789/6dc2442e-a7d4-49b2-a2de-f97e7d440d2b)
![image](https://github.com/metersphere/metersphere/assets/50016789/6a0bc523-5985-4dc1-8e30-6275d85fbf2f)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，计划于v2.10.7版本修复。
