### ISSUE TITLE
系统复制环境并保存，环境会被生成两条

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26670]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

环境配置中复制环境并保存，环境会被生成两条

### 重现步骤

1、选择已有环境，点击复制

2、修改复制出的环境名称，保存

3、返回查看环境配置

4、出现两条复制后的环境

### 期待的正确结果

复制环境后，正确展示

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/66d5f790-c1a8-4446-bc6a-5bafc2bfe6de)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts修复。
