### ISSUE TITLE
[BUG] macOS Monterey安装部署中总报错“metersphere-offline-installer-v2.10.6-lts/install.conf: line 85: getent: command not found”

### ISSUE THREAD

**Issue by JoanQQ** [metersphere/metersphere#26672]
### 联系方式

苹果篮

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

macOS Monterey+Intel芯片，安装结果总报错：
[MeterSphere Log]: 启动服务 

Error response from daemon: invalid reference format

### 重现步骤

macOS Monterey+Intel芯片，下载离线包：
安装时，总提示“～/metersphere-offline-installer-v2.10.6-lts/install.conf: line 85: getent: command not found”。
查看“/opt/metersphere/”下的“install.conf”文件，发现以下配置值为空：
MS_DOCKER_GID=
安装结果也报错：
[MeterSphere Log]: 启动服务 

Error response from daemon: invalid reference format

**Comment by liuruibin** [comment]
这个是专为linux执行的，node-controller是以non root 方式启动jar，需要手动设置docker组的id。离线安装docker不会创建组，这里需要root的组id。

mac上可以将   `sed -i "s/:101:/:${MS_DOCKER_GID:-101}:/g" /etc/group` 去掉

**Comment by JoanQQ** [comment]
赋予/opt/metersphere充分权限且在docker desktop中配置分享文件夹，重启后即可。

去掉“sed -i "s/:101:/:${MS_DOCKER_GID:-101}:/g" /etc/group”，导致以下错误：

 msctl stop

parsing /opt/metersphere/docker-compose-node-controller.yml: yaml: line 9: did not find expected '-' indicator
