### ISSUE TITLE
缺陷管理中关联用例：用例关联窗口，查询后重置，列表未正确加载

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26673]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

缺陷管理中关联用例，在用例关联窗口中，查询后重置，列表未正确加载

### 重现步骤

1、打开用例关联窗口
2、翻至最后一页
3、输入查询条件，查询
4、清空重置查询状态，查看列表数据
5、页码显示1，但加载的是最后一页的数据

### 期待的正确结果

查询后重置后，列表正确显示

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/e1805931-b898-49f5-9932-7e8bc19226a9)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，计划于v2.10.7版本修复。
