### ISSUE TITLE
[BUG]脑图中无法删除 用例、备注等节点

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#2667]
**MeterSphere 版本**
版本: v1.9.0-e6a9556e

**Bug 描述**
脑图中无法删除 用例、备注等节点

**Bug 重现步骤**
1.  脑图中选中 任意用例的前置条件、或备注、或步骤
2. 点击删除
3. 点击保存

**期待的正确结果**
期待结果：可以正常删除
实际结果：删除失败
**截图**
![image](https://user-images.githubusercontent.com/49704984/117766927-e0069900-b262-11eb-9859-2bc90e9a8985.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
您好，1.10.0版本已修复了这个问题
