### ISSUE TITLE
[BUG] Selenium VNC 弱密码，当前版本无法修改密码。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26687]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

Selenium VNC 弱密码，当前版本无法修改。
Selenium官方给出方案，必须版本>=4.9.1-20230508 才可以设置。
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.9.1-20230508

### 重现步骤

UI场景测试：
1. 访问百度 http://www.baidu.com
2. 输入搜索metersphere，加一个前置脚本设置等待时间比如等待6000ms，方便验证。
3. 点击后端调试
4.  访问 http://ip:4444。当点击后端调试的时候，点击session菜单，会看到一条记录。

### 期待的正确结果

希望升级selenium hub的版本，可以解决设置VNC密码问题

**Comment by liqiang-fit2cloud** [comment]
已复现，将于v2.10.7修复。
临时方案：
升级Selenium镜像：https://github.com/metersphere/installer/commit/35598ac4b9432d1ae87cc7e1d8290665c0f87865
默认禁用vnc，默认vnc为只读模式，缺省弱密码改为强密码。用户可以手动开启vnc，开启后可以指定是否只读，并修改vnc密码：https://github.com/metersphere/installer/commit/02dd31c0951a225eaad99eda560e3eb91ba3001d
