### ISSUE TITLE
[BUG] UI测试中“回车”快捷键不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#26686]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

UI测试中“回车”快捷键不生效，还是原始的${KEY_ENTER}

### 重现步骤

1、创建UI场景
2、场景中添加输入操作
3、输入内容中拼装${KEY_ENTER}，进行测试

### 附加信息

原始步骤：
<img width="1076" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/7acd2aa0-8c62-4aea-ba43-6a2c739f24ba">

结果步骤：
<img width="1006" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/85a9b92d-32c4-4f6d-9960-4c553b4d5407">

**Comment by zrfit** [comment]
您好，使用功能键必须勾选“追加输入”，不勾选会当作字符串输入。
![image](https://github.com/metersphere/metersphere/assets/99731894/52ac5f2c-053d-4503-a400-7ee4aa0afb36)

**Comment by dashenyucainiao** [comment]
从1.20LTS版本升级到2.10.5-lts版本，是否需要手动勾选，目前看来是不会自动勾选的

**Comment by zrfit** [comment]
经沟通了暂时保持现状。
原因是1.20没有功能键功能 ，追加输入的含义是：勾选，在现有内容后面追加输入；不勾选，清空现有内容后再进行输入。不勾选追加输入功能键也是可以成功的，未通过追加输入控制功能键；
而2.0 增加了功能键快捷入口，便于用户使用功能键直接复制，但是使用功能键必须勾选“追加输入”，不勾选会当作字符串输入。
因为版本功能不同，所以历史数据如果含有功能键，升级到2.0后要手动勾选下才能生效。
