### ISSUE TITLE
[BUG]选中任意模块的脑图页面时，再切换模块，脑图页面不展示用例信息。

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#2669]
**MeterSphere 版本**
版本: v1.9.0-e6a9556e

**Bug 描述**
选中任意模块的脑图页面时，再切换模块，脑图页面不展示用例信息。

**Bug 重现步骤**
1.  选择任意模块的脑图页面（此时用例信息展示正常）

![image](https://user-images.githubusercontent.com/49704984/117768011-522bad80-b264-11eb-8fdf-7cb0808e52ee.png)

2. 切换模块
![image](https://user-images.githubusercontent.com/49704984/117768078-6ff91280-b264-11eb-83b4-397efc9e0cad.png)

**期待的正确结果**
期待结果：脑图正常展示选中模块的用例信息

**截图**

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
