### ISSUE TITLE
[FEATURE] 外部Kafka可以支持SASL_SSL吗

### ISSUE THREAD

**Issue by ahululu** [metersphere/metersphere#26695]
### MeterSphere 版本

2.9.1

### 联系方式

ahululu

### 请描述您的需求或者改进建议

外部Kafka可以支持SASL_SSL吗

### 请描述你建议的实现方案

现在大部分服务都不会用自建的Kafka了，云上Kafka服务为了安全考虑，都开启了SASL_SSL.咱们能多一些对这种外部服务的支持吗

**Comment by liuruibin** [comment]
现在版本还不支持，不过您可以通过ip白名单方式处理
