### ISSUE TITLE
[BUG]测试跟踪：用例编辑态用的标签，保存预览就变了，应该按实际编辑 的内容做保存 不要自动转换

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#26694]
### MeterSphere 版本

2.10.3

### 使用外置数据库

否

### 问题描述

测试跟踪-用例编辑态用的标签，保存预览就变了，应该按实际编辑 的内容做保存

![用例编辑态用的标签，保存预览就变了，应该按实际编辑 的内容做保存](https://github.com/metersphere/metersphere/assets/43202800/70a3917d-a8c7-4d23-ac67-defc35bafaf5)

### 重现步骤

1、用例描述填写信息：
<S>(重要信息同步] <N>
<Segment/>1.亲爱的道友，本周外放的<Segment/>我们在收获了很多道友的好评<Segment/>

保存预览字段标签变

### 期待的正确结果

期望：不要自动转换

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by song-cc-rock** [comment]
由于该编辑器组件支持XSS白名单配置来防止一些注入风险, 一些自定义的标签不在该白名单配置中, 也就会被编辑器拦截替换成[remove]文本, 来保证安全. 计划v2.10.8将上述图中的标签加入白名单配置来支持正常预览, 但后续不会对一些自定义标签做支持. 如果后续需支持一些可解析的HTML标签, 提issue即可.

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
