### ISSUE TITLE
[FEATURE]m预览显示字段不全，且在列表也没见不好查看，每次要再次找到按钮点击再关闭 建议做成类似产品并列预览会好看些

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26692]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

建议用例预览字段显示完整，优化一下交互，需要拖动列表去找预览按钮，再关闭预览步骤过多
做成并列格局预览会好用很多减少操作步骤，提高使用体验

![m预览显示字段不全，且在列表也没见不好查看，每次要再次找到按钮点击再关闭](https://github.com/metersphere/metersphere/assets/114552960/333e65e6-abea-4bd8-bc62-499960392138)

**Comment by luty2018** [comment]
这是哪个页面

**Comment by opopjasica** [comment]
ones的

**Comment by opopjasica** [comment]
metersphere 功能用例 查看用例的预览页面

**Comment by luty2018** [comment]
这个已经规划到v3.0优化了哈。
