### ISSUE TITLE
[QUESTION]压力测试中的参数和jmeter中本身的参数的关系是什么？

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#267]
**请描述您的问题.**

比如jmeter里的进程线程，用户数等等
还有2者结合最终产生的实际参数又是什么？
能不能再上传脚本后结合jmeter本身的参数计算展示出最终的进程、线程、虚拟用户、并发数的集合结果？

**Comment by wangzhen-fit2cloud** [comment]
界面上设置的并发数等会重写 jmx 脚本中的内容
