### ISSUE TITLE
[BUG]【接口定义】往环境变量里存一个变量(user_id)后，然后在环境-通用设置处修改这个变量，点击确定，再次打开通用设置处，发现该值并没有被改变

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26705]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【接口定义】往环境变量里存一个变量(user_id)后，然后在环境-通用设置处修改这个变量，点击确定，再次打开通用设置处，发现该值并没有被改变

### 重现步骤

【接口定义】往环境变量里存一个变量(user_id)后，然后在环境-通用设置处修改这个变量，点击确定，再次打开通用设置处，发现该值并没有被改变
![image](https://github.com/metersphere/metersphere/assets/104960608/a7205985-7e0c-4123-80b3-8dc685549e51)
![image](https://github.com/metersphere/metersphere/assets/104960608/08d5fc4d-7e06-4528-9362-9c347d246086)
![image](https://github.com/metersphere/metersphere/assets/104960608/4fa8a7ed-228f-4c4b-8500-540fabdeba77)
![image](https://github.com/metersphere/metersphere/assets/104960608/1173e0b4-3816-409f-8b6d-3be13fbdf13a)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #26430 
该问题重复，关闭。
