### ISSUE TITLE
[FEATURE]使用脑图用例：标记用例、状态步骤需要挨个选择，希望添加快捷键操作

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26701]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

使用脑图用例：标记用例、状态步骤需要挨个选择，希望可以添加快捷键操作

![image](https://github.com/metersphere/metersphere/assets/114552960/26525d1e-cd3b-4315-99c8-5cf1558ff3e6)

**Comment by luty2018** [comment]
感谢建议， 我们调研看看

**Comment by luty2018** [comment]
可以升级到v3.0，添加时可以选择类型
![image](https://github.com/metersphere/metersphere/assets/36292514/61608a1f-947f-4ce2-9178-4fa1d30147b2)
