### ISSUE TITLE
[FEATURE] 我在某个项目的链接，分享给别人以后他们打开还是显示的自己之前所在的项目，期望是优先进链接所在项目，没有权限的时候再重定向到自己项目

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26713]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

我在某个项目的链接，分享给别人以后他们打开还是显示的自己之前所在的项目，期望是优先进链接所在项目，没有权限的时候再重定向到自己项目

**Comment by luty2018** [comment]
感谢建议， 我们已经规划到v3了。目前v2版本因设计问题，改造成本太高。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
