### ISSUE TITLE
[BUG]以脑图形式编写用例，采用脑图模式进行编辑，那么如果一条步骤对应多个结果，则多个结果会变成一条

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26719]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.5-lts

### 使用外置数据库

否

### 问题描述

[BUG]以脑图形式编写用例，采用脑图模式进行编辑，那么如果一条步骤对应多个结果，则多个结果会变成一条

### 重现步骤

编写用例；
进入脑图模式；
用例名称：bug复现
步骤：查看输出结果
预期结果：结果1+回车+结果2+回车+结果3
保存；
刷新并打开，发现结果1、2、3合并进了一条

### 期待的正确结果

结果1、2、3独立保留，作为子节点挂在步骤下面

**Comment by 13290445582** [comment]
您好，一个步骤只能挂载一条结果。在脑图模式下，若您的结果有多种现象表示，可shift+回车，换行显示，与列表保持一致，感谢您的理解与支持。
