### ISSUE TITLE
[BUG]DELETE请求出现重复的https://域名

### ISSUE THREAD

**Issue by lwl8851206** [metersphere/metersphere#26715]
### 联系方式

359392231@qq.com

### MeterSphere 版本

v1.20.23-lts-77e58286

### 使用外置数据库

否

### 问题描述

新建自定义请求, 使用delete方法时，执行时会出现重复域名

### 重现步骤

1.新建自定义请求，选择“DELETE”方法
2.输入请求url ="https://www.baidu.com/simu//vehicle/926"
3.执行请求

### 期待的正确结果

正常发起delete https://www.baidu.com/simu//vehicle/926

### 相关日志输出

```shell
请求地址:
https://www.baidu.com/https://www.baidu.com/simu//vehicle/926
请求头:
Connection: keep-alive
Content-Length: 0
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: www.baidu.com
User-Agent: Apache-HttpClient/4.5.13 (Java/11.0.19)

Cookies :

Body:
DELETE https://www.baidu.com/https://www.baidu.com/simu//vehicle/926

DELETE data:


[no cookies]
```

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本未复现该问题，建议升级到最新版本尝试！
![image](https://github.com/metersphere/metersphere/assets/99731894/8a1a2708-bbcd-468d-83c9-ece1f672acec)
