### ISSUE TITLE
[优化]当用户选中 【测试跟踪】或【接口测试】或【性能测试】任意tab，切换组织或工作空间后仍然保持在当前tab页面，而不是直接刷新到【系统组织】

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#2671]
**请描述您的需求或者改进建议.**
当用户选中 【测试跟踪】或【接口测试】或【性能测试】任意tab，切换组织或工作空间后仍然保持在当前tab页面，而不是直接刷新到【系统组织】

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，这个后面版本可以优化下
