### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zZ771977492** [metersphere/metersphere#26724]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

是

### 问题描述

<img width="1356" alt="企业微信截图_cc93247e-2b6a-4b8a-ba95-63c28ba30d24" src="https://github.com/metersphere/metersphere/assets/58156287/cec9c02e-4de7-4edc-9bba-36210f26113c">
环境配置的通用配置中配置的变量无法删除

### 重现步骤

删除后点击确定，再次打开还是存在

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #26430
