### ISSUE TITLE
[BUG]接口case新建后还未保存，直接点击运行会一直卡在pending

### ISSUE THREAD

**Issue by FangLiao12** [metersphere/metersphere#26722]
### 联系方式

13550384499@163.com

### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

<img width="1451" alt="image" src="https://github.com/metersphere/metersphere/assets/95417178/e3641385-7b52-4c05-908c-94e1f204e288">

### 重现步骤

1. 从已有的case中点击复制创建一个新的case
2. 未点击保存直接点击运行
3. 运行状态一直显示pending，需要先保存之后才能恢复正常状态

### 期待的正确结果

给出提示或者运行时自动保存

**Comment by 13290445582** [comment]
您好，新建case未保存，运行按钮是禁用状态的，未保存case不允许直接点击运行，需要保存后才可正常点击运行按钮。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。可待最新版本发布后再次尝试，如果后续有问题请重新提issue，感谢理解和支持～
