### ISSUE TITLE
[BUG]全局断言修改保存不成功。

### ISSUE THREAD

**Issue by liuts933** [metersphere/metersphere#26725]
### 联系方式

qq 6042740

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

全局断言修改保存不成功。

### 重现步骤

[****](https://github.com/metersphere/metersphere/issues/22494#issue-1612907694)
这个问题又出现了，在v2.10.5 版本发现，然后升级到v2.10.6-lts 问题依旧。
已经创建好的全局断言，对起内容修改后保存。结果并未保存成功，仍然是修改前的样子。

**Comment by 13290445582** [comment]
您好，未复现该问题，可以提供录屏看看嘛？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～

**Comment by liuts933** [comment]
> 您好，未复现该问题，可以提供录屏看看嘛？

已经提供给北区售前张树彬，请联系他。
