### ISSUE TITLE
[BUG]性能测试报告“监控详情”中看不到被测机器的“memory”字段，添加监控设备时已经加了memory这个指标

### ISSUE THREAD

**Issue by 3201878036** [metersphere/metersphere#26727]
### 联系方式

MeterSphere 交流群67，或者3201878036@qq.com

### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

[BUG]性能测试报告“监控详情”中看不到被测机器的“memory”字段，添加监控设备时已经加了memory这个指标

### 重现步骤

操作步骤：
1、添加性能场景后，进入“高级配置”tab页，
2、点击最下面的”监控“/”添加“，添加被测服务器IP，端口等，添加性能指标，包含memory，点击"确定"，
3、其它性能测试配置项都设置好后，点击”保存并执行“，
4、执行完后，查看测试报告，切换到”监控详情“tab页，
5、选择刚刚添加的监控服务器，拉到底下查看监控指标值

预期结果：
能看到memory指标值

实际结果：
看不到memory指标，只能看到cup，磁盘，网络几个指标的数据

### 期待的正确结果

能看到memory指标值

### 附加信息

![Uploading image.png…]()

**Comment by 13290445582** [comment]
您好，未复现您的这种情况，请检查下您的配置是否正确，后续可提供下您的性能测试场景和监控配置信息，附加信息内的图片未成功上传，可再上传一下。

**Comment by 3201878036** [comment]
你好，

我这边在gitup上上传图片后，我自己这里也看不到图片，不知道怎么回事，我在这里截图给你吧。

操作步骤：
1、添加性能场景后，进入“高级配置”tab页，
2、点击最下面的”监控“/”添加“，添加被测服务器IP，端口等，添加性能指标，包含memory，点击"确定"，

看附件图1和图2


3、其它性能测试配置项都设置好后，点击”保存并执行“，
4、执行完后，查看测试报告，切换到”监控详情“tab页，
5、选择刚刚添加的监控服务器，拉到底下查看监控指标值，看不到memory这个指标

看附件图3和图4




肖芬
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]性能测试报告“监控详情”中看不到被测机器的“memory”字段，添加监控设备时已经加了memory这个指标 (Issue #26727)





 
您好，未复现您的这种情况，请检查下您的配置是否正确，后续可提供下您的性能测试场景和监控配置信息，附加信息内的图片未成功上传，可再上传一下。

**Comment by 13290445582** [comment]
您好，本地未复现该情况，后续我们会关注这个现象，感谢理解与支持。
