### ISSUE TITLE
[BUG]保存缺陷后，页面未自动跳转至缺陷列表，缺陷未显示在列表中

### ISSUE THREAD

**Issue by sara199119** [metersphere/metersphere#26739]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

保存缺陷后，页面未自动跳转至缺陷列表，缺陷未显示在列表中，但缺陷能同步至jira

### 重现步骤

1.创建缺陷，点击保存
2.页面未自动跳转至缺陷列表
3.手动返回缺陷列表，缺陷未显示在列表中，但缺陷能同步至jira

**Comment by 13290445582** [comment]
您好，该问题在我们即将发布的v2.10.7版本jira插件上已修复，请等待v2.10.7版本发布，我们会上传对应的插件。

**Comment by 13290445582** [comment]
v2.10.7版本插件已上传，请下载。
