### ISSUE TITLE
[BUG]点击进入系统设置-项目-环境配置，系统抛错，提示“SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2673]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.1-2cb10c1e
**Bug 描述**
简要描述您碰到的问题
点击进入系统设置-项目-环境配置，系统抛错，提示“SQL error happened, please check logs.”
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/117769515-607ac900-b266-11eb-9bdd-b4745c3527c6.png)

**Comment by feiyu0316** [comment]
前面有安装过，后面升级过程中一直有问题就移除了，重新装了一下！

**Comment by xulinde** [comment]
1.9.2已修复
