### ISSUE TITLE
[BUG]老版本问题复现

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26737]
### MeterSphere 版本

V2.10.6-LTS

### 使用外置数据库

否

### 问题描述

 此问题2.10-6版本复现 刚升级的
https://github.com/metersphere/metersphere/issues/24820

### 重现步骤

 此问题2.10-6版本复现 刚升级的
https://github.com/metersphere/metersphere/issues/24820

**Comment by 13290445582** [comment]
您好，测试计划关联的接口方便导出提供下吗？

**Comment by legend818** [comment]
支持在线远程查看

**Comment by 13290445582** [comment]
你好，执行该测试计划使用的资源池正常吗，换个资源池执行还会一直running吗？

**Comment by legend818** [comment]
不就一个本地资源池么
![image](https://github.com/metersphere/metersphere/assets/19423100/3f66b4fc-a5c0-492a-8530-ebfb62608602)
本人支持向日葵在线远程连接查看，在线等

**Comment by 13290445582** [comment]
提供您的日志信息和接口文件吧，不进行远程查看了。

**Comment by legend818** [comment]
接口文件是内网的你能访问么

**Comment by 13290445582** [comment]
你好，导出是为了看看接口结构，是不是有特殊脚本或断言之类的，模拟复现下。

**Comment by legend818** [comment]
我录制了视频 加我把。我就2个case 。在测试计划里面怎么导出？ 我这个是生成token 应该没有断言

**Comment by legend818** [comment]
现在啥子情况 还是无法复现么？上次视频和日志都提供了

**Comment by 13290445582** [comment]
您好，已找到代码上可能出现该问题的情况，计划于v2.10.8版本修复。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级，查看问题是否修复，请反馈。
