### ISSUE TITLE
[FEATURE]测试跟踪-测试计划-接口测试用例批量执行的时候资源池建议默认LOCAL

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26745]
### MeterSphere 版本

V2.10.6-LTS

### 请描述您的需求或者改进建议

测试跟踪-测试计划-接口测试用例批量执行的时候资源池建议默认LOCAL

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/1d14431d-a63d-48a5-830c-bffa516ba123)

**Comment by luty2018** [comment]
<img width="990" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/8eef98f3-14e9-4950-b2db-7e5b5e8be2fc">
你可以在这里指定默认资源池

**Comment by legend818** [comment]
完美
