### ISSUE TITLE
[FEATURE]测试跟踪-测试计划--选择某个测试计划--接口测试用例---点击case编号不直观看API

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26747]
### MeterSphere 版本

V2.10.6-LTS

### 请描述您的需求或者改进建议

1、测试跟踪-测试计划--选择某个测试计划--接口测试用例---点击case编号
2、点击某个caseID链接到新页面
想查看这个case的API，无法直观链接到API 查阅不便捷（因为有可能API发生改变，想直接修改）

### 请描述你建议的实现方案

可便捷查看修改API

**Comment by luty2018** [comment]
<img width="706" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/7d8057eb-7a30-43a1-9951-75e334e8ed77">
你点ID也是可以跳转的

**Comment by legend818** [comment]
测试跟踪页面 你这个好像是接口自动化页面

**Comment by luty2018** [comment]
> 测试跟踪页面 你这个好像是接口自动化页面

是按照你的描述从测试计划点过来的，你试试点击我圈中的地方， 我们的ID都做了跳转功能的
![image](https://github.com/metersphere/metersphere/assets/36292514/381f7dcc-119c-4811-8edc-983c40f5e930)

**Comment by legend818** [comment]
![image](https://github.com/metersphere/metersphere/assets/19423100/7b75a5a5-dcf3-45b5-b323-db7844485feb)
你操作的地方与我不相同，按我图去操作，然后点击红色方框会链接到该case，没有问题，但是现在是case错误了，我需要去修正对应API，没有办法快捷到API

**Comment by luty2018** [comment]
<img width="1432" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/8793ed30-9271-40dc-b117-c1252988ee96">

都去到case了。 找到api还不容易吗， 这个地方的id是case， 当然是跳到case更合理， 而且case执行错误， 也不一定每次都是要改api对不对， 大部分情况还是会调整case本身。

**Comment by legend818** [comment]
case是从api过来的，case变更了接口参数新增了 或者修改了等等。你得保证你演变过来的case或者API是正确的
然后这个case你看还不直观了解是那个模块的，一般我会通过API是找到是哪个模块 哪个菜单的

**Comment by luty2018** [comment]
> case是从api过来的，case变更了接口参数新增了 或者修改了等等。你得保证你演变过来的case或者API是正确的 然后这个case你看还不直观了解是那个模块的，一般我会通过API是找到是哪个模块 哪个菜单的

好的， 我们可以在这里加个模块， 你看看是否能满足需求

**Comment by luty2018** [comment]
<img width="904" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/5129f87f-8b85-4a3b-867d-c32edc037c06">
v3.0 跳转case后左侧会显示所属模块， 同时可以快捷打开api
