### ISSUE TITLE
[FEATURE]api变动case不能联动变更

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26744]
### MeterSphere 版本

V2.10.6-LTS

### 请描述您的需求或者改进建议

API，传参发生变化，修改api，case不会变动，其他页面引用的都不会变化，现在就是删除case 重新生成case（或者修改case），然后引入的地方重新导入

是否提供一个功能同步更新case参数等核心同步变更一下，可以是一个按钮，可以在api这边同步过去，也可以在case那边选择是否同步更新

**Comment by luty2018** [comment]
企业版已经提供了这个功能
<img width="935" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/c837800d-3460-46c6-921f-15ef3633f80a">
