### ISSUE TITLE
[BUG]  接口定义，复制版本数据功能不生效。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26752]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/33945037/0c1dd29d-8cd0-4677-82a6-5c970078e130)

根据文档所言，我当前版本为V1.1 ，要复制的数据版本为V1.0.0 ，按照此操作，功能没有生效。
![image](https://github.com/metersphere/metersphere/assets/33945037/a00ef26a-8224-43be-8c0b-eeb46120892c)
![image](https://github.com/metersphere/metersphere/assets/33945037/5d45b8b8-1792-4653-84b8-11fdde477e87)

### 重现步骤

1. 创建新版本V1.1
2. 在V1.0版本中新建几个接口，然后应用V1.1版本
3.  在接口定义列表，全部勾选然后选择复制版本数据，选择V1.0版本，点击保存，V1.1版本并没有相关的接口信息

**Comment by zrfit** [comment]
您好，感谢反馈！该功能复制的是同接口不同版本下含有同名称的case和mock进行强制覆盖,接口下没有case和mock数据不会发生变化。
![image](https://github.com/metersphere/metersphere/assets/99731894/131d06e9-fd21-4923-86b6-b796a054c8aa)
