### ISSUE TITLE
[BUG] 系统设置-操作日志，cas登录的用户名为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26754]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

 项目设置-操作日志，cas登录的用户名为空
![8df64aa7c960c2e93e13c696560154b](https://github.com/metersphere/metersphere/assets/103925124/719067b9-78e3-44f5-aa3e-bf2ebb9be94e)

### 重现步骤

![8df64aa7c960c2e93e13c696560154b](https://github.com/metersphere/metersphere/assets/103925124/bb8998f1-758e-4270-ae64-4ae603293468)
![image](https://github.com/metersphere/metersphere/assets/103925124/94cfadfd-5919-4a38-80fb-45da79a75d48)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
