### ISSUE TITLE
[BUG]思维导图导入用例数据错乱

### ISSUE THREAD

**Issue by lyxlin** [metersphere/metersphere#26751]
### MeterSphere 版本

 v2.10.6-lts

### 使用外置数据库

否

### 问题描述

思维导图中模块包含tc，导入平台后用例错乱
例如：模块tc测试
![image](https://github.com/metersphere/metersphere/assets/42445400/d0113a72-4739-4863-9676-888a98d6abc5)
![image](https://github.com/metersphere/metersphere/assets/42445400/df264aa9-497d-401d-901a-e2f1195af44d)

### 重现步骤

思维导图编写用例后导入平台，模块名称包含tc

**Comment by 13290445582** [comment]
您好，关于名称中存在tc时产生的问题，在V2版本不再修改，可以通过在命名时避开tc解决问题，感谢理解与支持。
https://github.com/metersphere/metersphere/issues/26244
