### ISSUE TITLE
[BUG]【特定场景脚本必现】浏览器访问接口自动化-编辑接口场景页面，浏览器报错，safari浏览器无法显示场景列表，谷歌浏览器样式存在穿透同时导致上下滚动页面到某处后页面自动上下胡乱滚动。

### ISSUE THREAD

**Issue by GoldLoong** [metersphere/metersphere#26757]
### 联系方式

v：GoldLoong

### MeterSphere 版本

v2.10.5 UP>v2.10.6-lts-e87e920 问题同样复现

### 使用外置数据库

是

### 问题描述

编写接口自动化场景，滑动到展开的接口，页面不受鼠标控制的自动上下滑动页面，视频（微信MS交流群61）35秒处我手已经放开鼠标了，页面开始上下滑动直到滑动到某个位置（一般最顶部或最尾）停下，再次重新滑动鼠标问题依旧。

 更换电脑发现，换了一台mac 问题更明显了，苹果原生浏览器直接打不开场景接口设计页面，如图
然后我从新安装了谷歌，乱滚动的效果好了点，但是有样式穿透。如图

状态码被下面的几个没展开的接口盖住了，上面这个图更明显

31接口被32接口盖住了

这个是谷歌浏览器的报错
safari浏览器的报错
有时候还会这样

### 重现步骤

浏览器访问接口自动化-编辑接口场景页面

### 期待的正确结果

正确显示展开或折叠的接口，上下滚动浏览器页面，接口流畅显示，页面不会跳动

### 附加信息

也可加我微信获取问题报错截图

**Comment by GoldLoong** [comment]
截图貌似传不上，可以加我微信

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。样式穿透问题的截图发下，浏览器版本是什么？已添加您，同意下。

**Comment by GoldLoong** [comment]
没看到你们加我啊

**Comment by zrfit** [comment]
GoldLoong这个是您微信号吗？加了多次了。直接将复现视频和图片传上来也可以，支持视频和图片上传的。

**Comment by GoldLoong** [comment]
狼皮龘猫！²⁰²³ ོ 🐺
GoldLoong  是我的微信，这个场景在我自己电脑上根本没法正常编辑

**Comment by zrfit** [comment]
就是这个微信号已经加您好多次了。

**Comment by GoldLoong** [comment]
那个你的微信是？让我来加你好了

**Comment by zrfit** [comment]
您好！
1、safari浏览器兼容问题涉及较多页面，我们汇总后后续版本会进行统一兼容性优化。
2、滑动页面跳动问题同#26158，场景详情步骤逻辑复杂，改动影响大，所以比较谨慎，目前没有较好的处理方案， 计划v2.10.8-lts先把自动聚焦去掉，从而解决该问题。
3、页面样式穿透问题未能复现，已经微信给您留言，需提供下对应复现步骤和图片、视频。
上述问题均计划在v2.10.8-lts修复，感谢您的理解和支持，给您带来不便，深表歉意。
