### ISSUE TITLE
[BUG]【测试跟踪-缺陷管理】新增缺陷“状态”字段选项后，所有缺陷状态自动变为“新建”

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#26765]
### 联系方式

张树彬

### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

【测试跟踪-缺陷管理】新增缺陷“状态”字段选项后，所有缺陷状态自动变为“新建”

### 重现步骤

1. 将缺陷管理中的缺陷提交状态，如：已解决、已关闭等
2. 到项目管理-模板配置-字段管理，给“状态”字段增加新的选项
3. 本地部署环境：回到缺陷列表，所有缺陷状态自动变成“新建”
4. cloud环境：回到缺陷列表报错，列表数据加载不出来

### 附加信息

<img width="618" alt="2a03795662855fbbb2c577151422987" src="https://github.com/metersphere/metersphere/assets/77324661/8ffee29a-c043-4ab0-b502-c0125b2fb7f2">
<img width="420" alt="147c3b37d8518f61247ba7e43aa4a2c" src="https://github.com/metersphere/metersphere/assets/77324661/21deae2b-fddd-4c33-9ffd-107b8fa71c31">
<img width="522" alt="dfce3bd732758390033aa129027242a" src="https://github.com/metersphere/metersphere/assets/77324661/2ebfa97c-f1c5-4b84-a0f7-d3f4d60bd30f">
<img width="514" alt="72225c3fe5f934ea52f5ed4f14cf8c3" src="https://github.com/metersphere/metersphere/assets/77324661/887cbdc9-929b-43b2-b363-09cfeab1ee47">

**Comment by 13290445582** [comment]
您好，在v2.10.6版本复现，在我们最新的测试环境未复现，待发布v2.10.7版本后请升级尝试。

**Comment by 13290445582** [comment]
最新版本v2.10.7已发布，请升级。
