### ISSUE TITLE
[BUG] JMX脚本中有循环控制器，循环控制器有设置名称，导入到MeterSphere 接口场景中，循环控制器的名称没有显示

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26762]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

JMX脚本中有循环控制器，循环控制器有设置名称，导入到MeterSphere 接口场景中，循环控制器的名称没有显示，但在报告中是有的

<img width="1002" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/2988a465-c05b-4c54-a6b2-2822089325aa">

![image](https://github.com/metersphere/metersphere/assets/33945037/1fd7b5ca-6667-4087-a38b-592ea85121d7)

![image](https://github.com/metersphere/metersphere/assets/33945037/a1874798-0d5d-47f8-b2c7-0b1d7e1f381d)

### 重现步骤

[test.txt](https://github.com/metersphere/metersphere/files/12607651/test.txt)
直接导入到MeterSphere 自动化场景中就可以查看到。

**Comment by 13290445582** [comment]
目前循环控制器不支持编辑名称，如果导入的JMX文件就以导入的名称为准，平台录入不支持录入名称，如果您有这种需求，可以提个需求给我们。
