### ISSUE TITLE
【性能测试-测试报告】性能测试执行完成后报告中无数据

### ISSUE THREAD

**Issue by wt0215** [metersphere/metersphere#26767]
### 请描述您的问题

**环境**
ms、node-controller、data-streaming：v2.2源码部署
redis、kafka使用docker镜像
**问题**
创建性能测试执行无报错，但报告中只有日志详情页显示正常，其他页面无数据
![image](https://github.com/metersphere/metersphere/assets/52696124/23c7d386-82c8-4560-b7c3-5342292b7abd)
![image](https://github.com/metersphere/metersphere/assets/52696124/62573f84-b3eb-4223-81e0-c9023b7e3c71)
而且看日志是已经正常执行完成的，请问该从哪儿排查问题呢？

**Comment by liuruibin** [comment]
此版本已经不再维护，建议使用最新v2.10代码进行测试

**Comment by wt0215** [comment]
请教一个问题，目前排查到该方法获取到的List为空
![image](https://github.com/metersphere/metersphere/assets/52696124/b95a8812-7199-4434-b99d-ac661929a82a)
导致计算报告时没有执行
![image](https://github.com/metersphere/metersphere/assets/52696124/92f9a54e-812e-4c85-86c5-2124a9c24f3f)
为什么未能获取到继承AbstractReport的子类呢

**Comment by wt0215** [comment]
问题解决了，Reflections依赖在0.10.X版本不支持springboot打包jar的方式，回退到0.9.11版本就好了
![image](https://github.com/metersphere/metersphere/assets/52696124/cbc8ad39-4bb4-4501-b485-edf985d03b2f)
