### ISSUE TITLE
[BUG]测试跟踪-报告失败重跑error状态与测试计划里面的pending不一致

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26769]
### MeterSphere 版本

V2.10.6-LTS

### 使用外置数据库

否

### 问题描述

测试跟踪-报告失败重跑error状态与测试计划里面的pending不一致

### 重现步骤

1、测试跟踪-报告--失败重跑
2、查看状态都是error
3、到测试跟踪-测试计划-接口测试用例查看对于case
4、显示pending  卡很久，估计一直执行不完

### 期待的正确结果

两边显示一致

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/dbc1f864-389b-4d16-8478-e82c54dab756)
![image](https://github.com/metersphere/metersphere/assets/19423100/a6876f89-6744-4f98-907b-a44acb893edf)

**Comment by 13290445582** [comment]
您好，该问题为已知问题，执行后未回写后续用例的失败状态，导致无法查询到最新失败状态, 改动量大V3解决。

**Comment by legend818** [comment]
千呼万唤的3.0出来了，可是这个是否提上议程了

**Comment by legend818** [comment]
千呼万唤的3.0出来了，可是这个是否提上议程了

**Comment by 13290445582** [comment]
您好，列入V3.0待规划的都在计划中的，等陆续功能更新出来，就可以看到了。
