### ISSUE TITLE
[BUG]【性能测试-测试报告】报告对比功能，选择的对比报告数量与实际对比的报告数量不一致

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#26766]
### 联系方式

张树彬

### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

【性能测试-测试报告】报告对比功能，选择的对比报告数量与实际对比的报告数量不一致

### 重现步骤

1. 同一个性能用例执行多次
2. 点击报告对比，选择多次的报告
3. 在报告对比中，总是比实际勾选的数量要多一个

### 期待的正确结果

按实际勾选报告数量进行对比

### 附加信息

![1694697764258](https://github.com/metersphere/metersphere/assets/77324661/ee661d1d-6306-4ad1-89d5-0d3fc12648b2)
![1694697808539](https://github.com/metersphere/metersphere/assets/77324661/e13fa144-3a0d-4f28-b8e4-688473c01ff0)

**Comment by 13290445582** [comment]
您好，对比总会包含当前报告，不论是否勾选当前这个报告，非缺陷。
