### ISSUE TITLE
[BUG]环境设置中配置的请求头，在执行接口测试时不生效！

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#2676]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.1

**Bug 描述**
在环境配置中设置的请求头信息，实际执行接口用例或接口自动化用例时均不生效。

**Bug 重现步骤**
1.  环境配置中新增一个环境信息，设置任意请求头（如qq，值为aa），保存。
2. 在接口用例执行时，选择该环境，点击执行，查看请求报文时发现无设置好的请求头信息。
3. 通过前置脚本打印该请求头的值，可以正确输出，证明设值是无误的。

**期待的正确结果**
正确情况下应该在请求报文中默认带上所有配置的请求头信息。
希望尽快修复！谢谢！

**截图**
![image](https://user-images.githubusercontent.com/22739229/117772107-68883800-b269-11eb-9e77-b81054000047.png)
![image](https://user-images.githubusercontent.com/22739229/117772371-ae450080-b269-11eb-9591-7dab6f3aacf0.png)
![image](https://user-images.githubusercontent.com/22739229/117773064-74282e80-b26a-11eb-81b6-83dfb1b2bbe1.png)

**Comment by memoriesoffkid** [comment]
> 下个版本修复

环境配置这块似乎不仅仅是请求头会丢失,我这边在使用按模块设置http 配置时候遇到过域名和请求头都丢失的问题,请问这同样是已知问题,另外有可能的话能否告知临时的规避方法

**Comment by xulinde** [comment]
1.9.2已修复
