### ISSUE TITLE
[BUG]UI测试提取xpath数量后生成的变量在后续断言值中无法进行断言

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#26771]
### MeterSphere 版本

V2.10.5lts

### 使用外置数据库

否

### 问题描述

1.进行xpath数量提取并生成变量；
2.在后续步骤中的断言值中引用该变量进行断言；
3.断言报错提示：strItem.startsWith is not a function

### 重现步骤

见问题描述，可提供脚本

### 附加信息

![52a9dea9095ac22f773a4fd617f42d3](https://github.com/metersphere/metersphere/assets/92150453/586c410e-b081-41c9-b75c-8abcdb7e0001)
![825b61d5983d7055540643ae8d1c191](https://github.com/metersphere/metersphere/assets/92150453/a1f709aa-cd54-4b00-ad1a-5b9104420b60)
![fcf3d22457429ec116c641178284b81](https://github.com/metersphere/metersphere/assets/92150453/6d1871b5-4cff-42d7-b52e-30b4d2672e33)

**Comment by zrfit** [comment]
您好，感谢反馈！已知问题，v2.10.7-lts将不存在该问题，待发布后可升级尝试。
