### ISSUE TITLE
[FEATURE]建议标签字段长度限制改大

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26770]
### MeterSphere 版本

v2.10.5-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议标签字段长度限制改大，v2.10.5-lts版本限制了15个字符长度，对于用户来说是不够的，希望改长一点。
![image](https://github.com/metersphere/metersphere/assets/88763608/3f4300b5-a26a-4ddc-8cbe-1b4a11a0a76b)
![image](https://github.com/metersphere/metersphere/assets/88763608/0d655e4f-6634-4387-8836-0263b290f33b)
![image](https://github.com/metersphere/metersphere/assets/88763608/f36d37dd-82c9-4591-93ed-bfc69f1abb8c)

**Comment by luty2018** [comment]
好， 我们改一下

**Comment by Hyyfit** [comment]
您好，标签长度已开放至50个字符；
