### ISSUE TITLE
[BUG] 【接口测试】 TCP MOCK 请求参数的长度超过1024时，MOCK 调用请求内容会丢失

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26778]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

TCP MOCK 设置请求参数的长度超过1024时，MOCK 调用请求内容会丢失

### 重现步骤

1.创建一个 TCP MOCK
2.在请求触发条件的请求内容中输入超过1024长度的参数 
3.设置响应内容
4.点击保存
5.调用 MOCK,观察接口是否有返回

### 期待的正确结果

TCP MOCK 请求参数超过1024时，调用 MOCK能正常返回

### 附加信息

1.长度1054的请求参数
![image](https://github.com/metersphere/metersphere/assets/45531073/a1bdb5ae-ee29-4403-82a4-2687df2757df)
2.设置请求触发条件
![image](https://github.com/metersphere/metersphere/assets/45531073/836bf675-3832-4f35-b32a-cbcb3e165ca3)
3.调用 MOCK 无返回
![image](https://github.com/metersphere/metersphere/assets/45531073/8233c89a-17f2-4b83-9583-c6137f3b77c2)
4.接收的请求内容少数据

![image](https://github.com/metersphere/metersphere/assets/45531073/e03fd317-44a7-40aa-8384-6662d27c1cc9)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复。
