### ISSUE TITLE
Is this library subject to US EAR (Encryption and Export administration regulations)?

### ISSUE THREAD

**Issue by ztest-dev** [metersphere/metersphere#26789]
### 请描述您的问题

First, thank you so much for developing this open-source software which is powerful and feature-rich but also simple and easy to use. I prepare to use it in my projects. However, I wonder whether this software is subject to the Export Administration Regulations (EAR).
In case of being controlled by EAR, would you please tell me which classification number (ECCN) does it come under? Are there any restrictions or specific license requirements? May I know in which country or region did your team compile it? And does the software have encryption function? In case that encryption function is included, has the filing information been submitted according to EAR§742.15(b)? 

I need this information to comply with the Export Administration Regulations (EAR), and I'm sure other users of this software would benefit from this information as well.

Thanks and best wishes！

**Comment by liqiang-fit2cloud** [comment]
It's not subject to EAR.

**Comment by ztest-dev** [comment]
Thank you for the information. It's really helpful.

liqiang-fit2cloud ***@***.***> 于2023年9月18日周一 14:24写道：
