### ISSUE TITLE
创建新的工作空间切换后，禅道服务集成成功，但是去创建项目集成第三方平台没有禅道选项

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26790]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

创建新的工作空间切换后，禅道服务集成成功，但是去创建项目集成第三方平台下拉选项中没有禅道选项。

### 重现步骤

1. 创建新的工作空间，并切换到新的工作空间
2. 禅道集成服务成功，然后去关联项目，创建新的项目
3. 集成第三方平台的下拉选项中没有禅道选项

### 期待的正确结果

集成第三方平台的下拉选项中有禅道选项

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/e4200ce4-2cd0-4ee6-8a50-63ad8cf2b419)
![image](https://github.com/metersphere/metersphere/assets/50016789/2ed6f57b-adf6-4d25-8510-e676ce78a095)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
