### ISSUE TITLE
[FEATURE]建议UI测试断言里，如果是不需要期望值的断言，就不要展示断言期望值输入框了，很多用户以为是bug

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26793]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议UI测试断言里，如果是不需要期望值的断言，就不要展示断言期望值输入框了，很多客户以为是bug。
![image](https://github.com/metersphere/metersphere/assets/88763608/2e27ef37-3e23-4c9b-a0db-6e23aa456555)

**Comment by luty2018** [comment]
v3.0优化
