### ISSUE TITLE
[BUG] 接口定义使用”生成测试数据“功能时，最大值最小值的限制没有效果

### ISSUE THREAD

**Issue by blooze123** [metersphere/metersphere#26795]
### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

1.在接口定义的TEST里面，进行请求体的高级设置，设置完最大长度和最小长度之后，点击”生成测试数据“，发现当选择”integer“类型时，不会根据给定的范围进行生成数据
![image](https://github.com/metersphere/metersphere/assets/47737772/fd46e5f2-4cbe-4ec7-b15f-02eec66f5098)
![image](https://github.com/metersphere/metersphere/assets/47737772/25206ad5-5ed9-46fb-8fcc-68051290a852)

### 重现步骤

如上述问题描述

### 期待的正确结果

能够正确生成指定范围的数据

**Comment by 13290445582** [comment]
您好，在最新环境未复现您反馈的问题，建议升级至最新版本尝试。
看您反馈的截图，没看到有缺陷的地方，integer类型设置的最大值为7最小值为5，生成的测试数据为5，符合最大值最小值区间。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
