### ISSUE TITLE
[BUG] 接口测试 响应体，使用正则表达式在ms里面匹配不到值，使用正则格式校验工具是可以提取到的

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#26797]
### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

正则表达式 OP(.*?)[0-9]+

接口返回值{
    "code": "000",
    "success": true,
    "msg": "000",
    "traceID": "972e738e-32c0-4380-8fe8-94d145b82297",
    "data": {
        "data": {
            "orderKey": "7280033141916437676",
            "payment": [
                {
                    "paymentID": "",
                    "paymentSubjectID": "11311001",
                    "paymentSubjectName": "哗啦啦微信",
                    "payorAccount": "",
                    "payeeAccount": "",
                    "cardTypeID": "",
                    "dueAmount": null,
                    "paidAmount": "",
                    "payload": "{\"appId\":\"wx2804355dbf8d15c3\",\"nonceStr\":\"c08bbd6d1a744f80956746316d9f9bc0\",\"package\":\"prepay_id=wx18132643149418100dc24a7f4728fe0000\",\"paySign\":\"RfniSS5F8KvDceLny8aZEADLSu6oK3G7Xekfog5bbpsib6VkgiRcpmOCY8iIqW4kUqK/6TzcsIbXZ9BdV24OhatkEUI9hCxc/CqnPNdIJJPVGIxGmJUe0wQAWyvw0yP/sE0jIvhY4VDwBP8yUinx/I0W8Wt7fgwSLDlBcKrvXV2DKETsLHp+LlUyKRWQ7ioSoY1UUrSQe5ZZ4G+WSABLwPBX0IJTM68HktgH3jIzvN17EEVhTIENigwvIpWS39gngjIcxSJTy5R0mLvNBYCV7wwMUfk+MW9Fyz78KvPeZU/LQjRCoPL/c9Zo9iLwHq9uQ3KaSDy8x1pua4kMHw6fag==\",\"signType\":\"RSA\",\"timeStamp\":\"1695014803\",\"isSuccess\":\"5\",\"erroFlag\":\"5\",\"erroMsg\":\"打开第三方微信支付\",\"paymentID\":\"OP7280033142998572204\",\"prepayType\":\"FORM\",\"bankSubMchId\":\"\",\"bankMchId\":\"\",\"bankTradeNo\":\"\"}",
                    "paymentStatus": 15,
                    "payBeginTime": "",
                    "payEndTime": "",
                    "payWay": 10,
                    "balanceID": "",
                    "couponID": "",
                    "pointAmount": "",
                    "payType": "",
                    "morePayParams": "",
                    "thirdTradeID": "",
                    "sceneInfo": "",
                    "couponName": "",
                    "couponTemplateID": "",
                    "pID": ""
                }
            ],
            "payload": "",
            "bankSubMchId": "",
            "bankMchId": ""
        }
    }
}
正则表达式为 /[OP]+[0-9]+/

![image](https://github.com/metersphere/metersphere/assets/43202800/32083672-5f72-4ea0-a0e2-eae90d4c1bd0)

### 重现步骤

ms采用mock的方式定义响应体，然后采用正则获取paymentID

正则表达式OP(.*?)[0-9]+

问题：使用在线格式校验工具可以提取到值，但是放到ms上提取不到

### 期待的正确结果

正则看起来无误，应该可以提取到

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复。

**Comment by 13290445582** [comment]
v2.10.7已修复。
