### ISSUE TITLE
[FEATURE]建议UI测试删除某个步骤后，自动变为未选中状态

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26792]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议UI测试删除某个步骤后，自动变为未选中状态，方便直接导入新的场景和指令。
目前是把选中的步骤删除后，会自动选中其他的步骤，这时候如果直接导入新的指令，会导入到自动选中的这个步骤的子步骤下。
![image](https://github.com/metersphere/metersphere/assets/88763608/925e7417-296f-4fb4-8d86-f48243cbe452)
![image](https://github.com/metersphere/metersphere/assets/88763608/410ae8d6-eb5e-49a9-af39-e1b9dee27f14)

**Comment by Hyyfit** [comment]
这个设计是考虑到，子场景内编辑步骤的时候，删除了步骤后，能快速的在子场景内继续编辑，所以会自动选中上一个步骤。
如果上一个步骤是场景，会加入到子场景的最后一个步骤，v3会优化这里的交互；
