### ISSUE TITLE
[BUG] 断言脚本中使用v="${varname}"获取参数，断言失败

### ISSUE THREAD

**Issue by lakuite** [metersphere/metersphere#26798]
### MeterSphere 版本

v1.20.23

### 使用外置数据库

否

### 问题描述

接口响应体
{
    "resultInfo": {
        "success": true,
        "code": null,
        "message": null,
        "data": {
            "sysInfo": {
                "sysID": 102,
                "bizID": null,
                "sysName": "执法办案-接口自动化",
                "displayName": "执法办案-接口自动化",
                "sysDesc": "执法办案-接口自动化",
                "displayOrder": null,
                "procDefID": null,
                "navType": "main",
                "printTitle": "执法办案-接口自动化",
                "printTemplate": "执法办案-接口自动化",
                "formID": null,
                "hisFormID": null
            },
            "forms": [
                
            ]
        },
        "timestamp": "2023-09-18 16:31:11",
        "unSuccess": false,
        "stackTrace": null
    }
}

前置/后置脚本中已获取sysDesc1和sysDesc变量值：
![image](https://github.com/metersphere/metersphere/assets/49950902/6a549c78-dda1-451d-808a-688d3264886e)
![image](https://github.com/metersphere/metersphere/assets/49950902/a445515c-e287-4596-a8da-022e8c14e861)

增加断言判断二者相等时，会产生报错：
![image](https://github.com/metersphere/metersphere/assets/49950902/724f14c2-ffc6-4ce4-bb1b-48caccf3edd1)
![image](https://github.com/metersphere/metersphere/assets/49950902/236bb113-4083-400f-b4d6-7f0aceef09a1)

### 重现步骤

断言脚本是通过MS自带方法生成的：
![image](https://github.com/metersphere/metersphere/assets/49950902/db24bce8-8307-4aa8-bd70-e54c05d2ab86)

### 期待的正确结果

手动把获取方式改为vars.get()可以获取成功，但是为什么"${}"这样就不行？
![image](https://github.com/metersphere/metersphere/assets/49950902/780edddd-a42f-4666-a9ff-e33f1166cf2c)
![image](https://github.com/metersphere/metersphere/assets/49950902/951e4673-989f-467c-9cb8-dbcb4278bcd5)

之前是MS版本是v1.20.7的，"${}"可以，升级到v1.20.23后就不行了，导致很多断言都报错

**Comment by 13290445582** [comment]
您好，暂时不支持直接$取值这种用法。

**Comment by lakuite** [comment]
你看下我截的图，$是获取到值了的，就是断言这里有个''号
![image](https://github.com/metersphere/metersphere/assets/49950902/95e20679-8cc9-4738-960e-d7b86d3a4475)

**Comment by fit2-zhao** [comment]
由于我们使用的jython三方包编码问题导致，具体可调整为：
```
value = vars.get("sysDesc_1"); 
if value != (u"${sysDesc1}") :
	msg = " "
	AssertionResult.setFailureMessage(msg)
	AssertionResult.setFailure(True)
```
加上 u 函数转化一下就可以，或者直接使用 vars 上下文变量中获取也行。
