### ISSUE TITLE
[FEATURE]建议UI测试断言支持“或”类断言。

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26791]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议UI测试断言支持“或”类断言。
客户有的元素会出现几种情况，都可以断言为成功，希望我们能支持“或”断言
![image](https://github.com/metersphere/metersphere/assets/88763608/f1f1ca89-10a9-4e3b-b1a4-2d0d5d9366b4)

**Comment by Hyyfit** [comment]
感谢反馈，v3 会增加UI的断言类型
