### ISSUE TITLE
[QUESTION]为什么程序运行一段时间后服务会自动停掉呢？

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#268]
**请描述您的问题.**

为什么程序运行一段时间后服务会自动停掉呢？重新启动容器有可以了。

**Comment by chenqiunuan** [comment]
查看日志，一直在循环执行这一部分内容。
![image](https://user-images.githubusercontent.com/53041390/90844421-6b1ec680-e396-11ea-9c83-18398a26382c.png)

**Comment by wangzhen-fit2cloud** [comment]
有设置定时任务之类的吗

**Comment by wangzhen-fit2cloud** [comment]
你好，请问还存在该问题吗，如果还存在请重新打开该 issue
