### ISSUE TITLE
[BUG]场景设置，无论设置优先使用原场景还是优先使用现场景，使用的都是原场景

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26809]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

场景设置，csv 文件中的变量，场景引用后对 csv 文件中的变量值做了修改，无论设置优先使用原场景还是优先使用现场景，使用的都是原场景 csv 中变量

### 重现步骤

1. 创建场景，场景中 上传 csv 文件，参数中引用
![image](https://github.com/metersphere/metersphere/assets/103627487/74e5d3ce-b47d-4f4f-878b-64035efd8f4f)
![image](https://github.com/metersphere/metersphere/assets/103627487/c2064fe9-ff18-42d8-98d4-e3ecdd829934)
2. 创建场景，引用 步骤1 中创建的场景，修改csv 文件中的值重新上传
![image](https://github.com/metersphere/metersphere/assets/103627487/6b6c8740-77f8-4f63-8370-97d7decf3cfe)
场景设置优先使用当前场景变量，没有则使用原场景变量，调试发现使用的是原场景中 csv 文件中的值
![image](https://github.com/metersphere/metersphere/assets/103627487/c91600cf-2342-4b81-8714-1556942aed71)
![image](https://github.com/metersphere/metersphere/assets/103627487/9f6a0b55-6cca-4de6-b709-d520e64acaaf)

**Comment by fit2-zhao** [comment]
优先原则只限于常量，针对csv变量还是遵循测试引擎JMeter对上下文变量处理逻辑。
