### ISSUE TITLE
[BUG]jsonpath提取参数错误

### ISSUE THREAD

**Issue by lakuite** [metersphere/metersphere#26801]
### MeterSphere 版本

v1.20.23

### 使用外置数据库

否

### 问题描述

MS版本由v1.20.7升级到v1.20.23，jsonpath提取参数失败，原本提取正常：
![image](https://github.com/metersphere/metersphere/assets/49950902/ffb2d75e-65bc-4d72-a28e-de3df6bd2e37)

接口响应体：
{
    "success": true,
    "code": 0,
    "message": null,
    "data": {
        "pageInfo": {
            "totalPage": 1,
            "currentPage": 1,
            "totalRecord": 1,
            "currentRecord": 1,
            "numPerPage": 10
        },
        "list": [
            {
                "subTaskId": 97,
                "tableId": 64,
                "tableName": "吸毒人员",
                "objectId": 55,
                "objectName": "自动化人员",
                "subTaskCode": "20230713200918837 主动走访异常任务",
                "taskDesc": "主动走访异常任务",
                "humanName": "egova",
                "feedbackTime": "2023-07-13 20:09:30",
                "address": "光谷金融港B4号楼(光谷金融港内)",
                "residentId": 2280767,
                "visitTypeId": 2
            }
        ]
    },
    "tipType": 1
}

### 重现步骤

如果先提取residentId，再用它获取前面的subTaskId和objectId就会提取为空：
![d443012d0bd597d5990a10558de3cec](https://github.com/metersphere/metersphere/assets/49950902/87950288-acec-4a20-a056-f238ce06f2de)

如果先提取subTaskId，再提取另两个，就可以正常提取：
![ddfaf83ec6a0c6b7fb7895e47e6c1e9](https://github.com/metersphere/metersphere/assets/49950902/6f75d40f-6f31-46e2-bf45-87d8a48fc1b5)

### 期待的正确结果

原则上是先获取的响应体，然后再执行后置操作，提取与否应该跟响应体中的参数值顺序无关，下面这种写法理应能正常提取：
![d443012d0bd597d5990a10558de3cec](https://github.com/metersphere/metersphere/assets/49950902/d0c3b7e1-f853-4531-9a74-f1018c07a5e4)

![image](https://github.com/metersphere/metersphere/assets/49950902/52057e1e-4680-4c83-82b9-8b3be5360c52)

**Comment by 13290445582** [comment]
您好，根据您的写法，导出到jmeter执行，结果与截图一致，metersphere与jmeter保持一致，非缺陷。
