### ISSUE TITLE
[BUG] JMX 中有JSON提取器，提取到结果是数组，导入到MeterSphere中，并没有自动勾选匹配多条。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26803]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

JMX 中有JSON提取器，提取到结果是数组，导入到MeterSphere中，并没有自动勾选匹配多条。

<img width="1173" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/28476ce9-6f38-411f-afab-c3e767a0af49">

![image](https://github.com/metersphere/metersphere/assets/33945037/a4becdf3-8348-40af-8aba-43f0c67a54ff)

### 重现步骤

1. 找一个响应结果是json数据格式的接口，有多个值。
2. 编写jmeter文件，使用json提取器，提取多个值。
3. 保存导入到metersphere上，在后置操作中可以看到没有匹配多个。

### 期待的正确结果

如果是提取多个值，希望自动勾选匹配多个值

**Comment by fit2-zhao** [comment]
勾上Compute concatenation var (suffix_ALL) 这个选项就行了。

<img width="1375" alt="image" src="https://github.com/metersphere/metersphere/assets/70558837/e4bb154e-adbb-4a61-9a9f-30362abb5a28">
