### ISSUE TITLE
[BUG] api接口以swagger3.0格式导出数据缺失

### ISSUE THREAD

**Issue by qzs8116** [metersphere/metersphere#26815]
### 联系方式

445989070@qq.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

以swagger3.0格式导出定义好的api接口，得到的数据会出现responses字段为空，缺失接口参数等情况。但是以metersphere格式导出数据是完整的。

### 重现步骤

1. 选中新建或已有接口，以swagger3.0格式导出
2. 导出文件数据缺失

### 期待的正确结果

api接口定义数据以swagger3.0格式导出的文件数据完整

**Comment by zrfit** [comment]
您好，感谢反馈！响应内容设置状态码了吗？导出为swagger格式，要设置状态码，才能导出响应数据。
<img width="1375" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/ef3cd750-a2f1-468a-8547-583471d17942">
![image](https://github.com/metersphere/metersphere/assets/99731894/bf6a6381-2c4e-4a91-87da-2b3602c5f26b)

**Comment by qzs8116** [comment]
好的，谢谢问题以解决
