### ISSUE TITLE
[BUG] JMX禁用的断言，导入到MS上会自动打开。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26824]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

JMX禁用的断言，导入到MS上会自动打开。

![image](https://github.com/metersphere/metersphere/assets/33945037/255af9f9-7349-4573-8b6a-acd29f84c00a)
![image](https://github.com/metersphere/metersphere/assets/33945037/8b9286af-a7e9-45ac-8000-718e15ddbf8b)

### 重现步骤

同上

### 期待的正确结果

应该关闭

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts优化。

**Comment by wicktu** [comment]
JMeter.convertSubTree(hashTree, true);
