### ISSUE TITLE
[BUG]${__CSVRead(,)}函数在MS最新版使用会导致场景一直running中

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26821]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

${__CSVRead(,)}函数在MS最新版使用会导致场景一直running中，api/info.log里卡在下载执行脚本就不动了。
这个函数在v2.10.0-lts版本中是可以正常使用的。

### 重现步骤

1.创建任意的接口自动化场景，在脚本中使用${__CSVRead(,)}函数，例如：${__CSVRead(/opt/metersphere/data/csv/testdata.csv,1)}

2.调试或执行该场景，会一直处于running中
![image](https://github.com/metersphere/metersphere/assets/88763608/ab010b5f-604b-4e59-a83e-81cf01532bc4)

3.在v2.10.0-lts版本中，同样的方法是不影响场景执行的
![image](https://github.com/metersphere/metersphere/assets/88763608/889fa60d-7f09-4636-b748-598bbf546d72)

### 期待的正确结果
可以正常使用该函数
_No response_

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.7版本修复这个问题。

**Comment by 13290445582** [comment]
v2.10.7已修复。
