### ISSUE TITLE
[QUESTION]自定义插件提示：“场景包含插件步骤，对应场景已经删除不能执行！”

### ISSUE THREAD

**Issue by liwei721** [metersphere/metersphere#26822]
### 请描述您的问题

自定义了个插件，在接口自动化中添加插件后提示：“场景包含插件步骤，对应场景已经删除不能执行！”
请问这是什么原因，应该怎么解决呢？是版本问题吗？

**Comment by liwei721** [comment]
<img width="598" alt="WX20230919-155130@2x" src="https://github.com/metersphere/metersphere/assets/3367699/f4dc1a29-a06a-4097-8874-81b5228a49c5">

**Comment by fit2-zhao** [comment]
1 检查插件原始jar文件是否丢失。
2 插件目前不是热加载的，上传成功后需要重启api-test 和 node- controller 服务。

**Comment by liwei721** [comment]
好的，感谢
建议将这个加到文档里。
