### ISSUE TITLE
[BUG]编辑接口自动化场景名称，无法鼠标选择文字

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#26836]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/40912189/486e48e4-bb25-4f16-be6c-66ae54ff7839

### 重现步骤

1、新建一个场景
2、复制一个其他场景
3、保存重新打开之后编辑复制过来的场景名称
4、用鼠标选择文字看看能否选择

### 期待的正确结果

鼠标可以选择文字

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.7-lts优化。
