### ISSUE TITLE
K8s部署，当使用Containerd而非Dockershim runtime 时，执行性能测试时报错

### ISSUE THREAD

**Issue by eanliu-yt** [metersphere/metersphere#26833]
### 请描述您的问题

![图片](https://github.com/metersphere/metersphere/assets/143773868/90cc08f2-648b-4f83-b6b8-6c1b7b2db55c)

**Comment by eanliu-yt** [comment]
且状态一直在starting

**Comment by liuruibin** [comment]
#22400

**Comment by eanliu-yt** [comment]
> #22400

有支持计划嘛？
