### ISSUE TITLE
[BUG]【接口定义】当传参为list数据时，[]会自动转义，设置了编码为否也不行，设置了${__urldecode([a\,b\,c])} 也不好使。但是在JMeter上测试是好使的

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#26835]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【接口定义】当传参为list数据时，[]会自动转义，设置了编码为否也不行，设置了${__urldecode([a\,b\,c])} 也不好使。但是在JMeter上测试是好使的

### 重现步骤

【接口定义】当传参为list数据时，[]会自动转义，但是JMeter上就不会自动转
![企业微信截图_16951761849219](https://github.com/metersphere/metersphere/assets/104960608/8dede103-bb56-4679-9f89-a5f5f672547e)
![image](https://github.com/metersphere/metersphere/assets/104960608/92806384-28f9-4235-8606-88acbd5224e0)
![image](https://github.com/metersphere/metersphere/assets/104960608/f97c764b-5396-428e-b67d-0a4b457dc7a2)

设置了编码为否也不行，设置了${__urldecode([a\,b\,c])} 也不好使。但是在JMeter上测试是好使的
![image](https://github.com/metersphere/metersphere/assets/104960608/c7edccf8-f1fb-4fd0-93bf-7e42216ec3b0)
![image](https://github.com/metersphere/metersphere/assets/104960608/a8ee4497-bc0c-463a-a741-5fac00c23717)
![image](https://github.com/metersphere/metersphere/assets/104960608/7e6e943d-29d0-4ef2-ad4b-e10a55ea9484)

**Comment by 13290445582** [comment]
您好，根据您jmeter中的配置，导入到metersphere中，接口的请求体对应的为raw格式，您提供的截图中快捷调试选择的请求体格式为x-www-form-urlencoded，因此将请求体格式更改为raw，采用同样的请求体内容，在metersphere中同样不会自动转义，与jmeter保持一致，感谢理解与支持。
![image](https://github.com/metersphere/metersphere/assets/128017892/f9ea256c-0c06-4871-9e49-e0f7fd695381)
