### ISSUE TITLE
[BUG] 【接口测试】 TCP MOCK 响应时间太慢

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#26840]
### MeterSphere 版本

v2.10.6lts

### 使用外置数据库

否

### 问题描述

平台总共有1300多个 MOCK，其中 MOCK 有加后置脚本判断请求数据，动态返回数据，调用 TCP MOCK 响应时间要8s多，TCP MOCK未加后置脚本，MOCK调用很快，希望能优化下。

### 重现步骤

无

### 期待的正确结果

TCP MOCK 加后置脚本后，调用 TCP MOCK 能快速响应

### 相关日志输出

```shell

```

### 附加信息

TCP MOCK 响应时间
![image](https://github.com/metersphere/metersphere/assets/45531073/5e0b433e-991d-41ff-8126-5e7a565e402f)

MOCK 后置脚本
![image](https://github.com/metersphere/metersphere/assets/45531073/edcfef98-1064-4eb3-8fdb-8b3abbd262a8)

MOCK 加后置脚本调用日志
<img width="1511" alt="1695360035830" src="https://github.com/metersphere/metersphere/assets/45531073/ad29795d-3f7e-480b-8636-8d53048d29a2">
MOCK 未加后置脚本 
![image](https://github.com/metersphere/metersphere/assets/45531073/c4183349-445a-45c5-bc35-9d35bc473810)

**Comment by 13290445582** [comment]
您好，可以将您的接口与MOCK数据导出提供下，建议升级至我们的最新版本，V1版本不再优化。

**Comment by Larson13** [comment]
不好意思，版本填错了，我们用的是最新版2.10.6版本

**Comment by 13290445582** [comment]
您好，本地未复现，研发反馈了排查方向，建议仔细排查，感谢理解与支持。
