### ISSUE TITLE
[FEATURE]接口路径修改后支持同步修改相关用例的接口路径

### ISSUE THREAD

**Issue by long-li-96** [metersphere/metersphere#26842]
### MeterSphere 版本

v1.20

### 请描述您的需求或者改进建议

在已经写好了接口case的情况下，接口路径变更，此时接口case里的接口路径不会同步变更，建议可以提供一个快捷更新用例接口路径的入口

**Comment by luty2018** [comment]
这个是支持的， 接口路径变更后case的路径会自动更新， 你可以提供详细版本号和重现步骤吗？
