### ISSUE TITLE
[BUG]TCP协议性能测试报告与JMeter界面的聚合数据不一致

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#26844]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

如标题描述

### 重现步骤

用标准jmeter5.5压测，不管是界面，还是jmeter命令行，
得到的tcp数值都是1300，错误率只有0.01%
<img width="1149" alt="WechatIMG1990" src="https://github.com/metersphere/metersphere/assets/18387151/f5aab5d8-aa85-43d3-bdbe-87158223953b">
<img width="1015" alt="WX20230920-144522@2x" src="https://github.com/metersphere/metersphere/assets/18387151/ef58378e-025f-4824-9634-f68d0eb8c956">
**问题1:**
导出jmeter5.5的jmx文件，导入到MeterSphere，
还用jmeter5.5所在服务器作为压测资源池，资源池已关闭后置监听
压测结果的错误率是100%，日志详情显示，连接不到tcp服务端
<img width="1262" alt="WX20230920-144726@2x" src="https://github.com/metersphere/metersphere/assets/18387151/fb21ea12-6fef-4715-9c41-0491dd272f25">
<img width="1267" alt="WX20230920-144752@2x" src="https://github.com/metersphere/metersphere/assets/18387151/7b413b45-512f-4de5-981b-71242f87a2e6">
**问题2:**
将jmeter5.5的jmx文件中的tcp请求体，前置脚本内容，手动复制到接口用例，
点击执行后，tcp请求和响应都是正常的
将接口用例转成性能测试，还选择jmeter5.5所在服务器作为压测资源池
得到tcp数值只有100，跟标准jmeter5.5的压测结果相差很大
<img width="1248" alt="WX20230920-145239@2x" src="https://github.com/metersphere/metersphere/assets/18387151/58b4a1d5-2b9e-4541-99d1-745db2a7de98">
<img width="1269" alt="WX20230920-144828@2x" src="https://github.com/metersphere/metersphere/assets/18387151/18cb6941-4b99-481b-bedc-58abc172267e">

刚才描述的2个问题，只针对tcp协议的性能测试

如果是http协议的性能测试，不管是把jmeter jmx导入到ms做压测，还是接口用例转性能测试，都是正常的

### 期待的正确结果

MeterSphere的TCP协议性能测试报告与JMeter界面的聚合数据要保持一致

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本优化问题2。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
