### ISSUE TITLE
[BUG]接口测试，修改api 其他设置里重定向规则，由跟随重定向修改到自动重定向，case没有同步。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#26847]
### MeterSphere 版本

v2.10.6lts

### 使用外置数据库

否

### 问题描述

接口测试，修改api 其他设置里重定向规则，由跟随重定向修改到自动重定向，case没有同步。

### 重现步骤

1.新增接口，
2.接口下新增case
3.修改接口重定向规则，查看case重定向规则没有同步

### 期待的正确结果
1.接口测试修改api 其他设置里重定向规则，case也可以同步修改。
_No response_

**Comment by 13290445582** [comment]
![image](https://github.com/metersphere/metersphere/assets/128017892/23bfff3a-4f16-4f00-a385-20edb410397a)
您好，重定向规则这里一键同步时不会同步至case。
