### ISSUE TITLE
[BUG]切换场景的运行环境，会影响场景内SQL请求的数据源

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26845]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

切换场景的运行环境，会影响场景内SQL请求的数据源.
在接口定义那边定义的SQL接口，导入场景后，数据源会受到场景运行环境的影响。

### 重现步骤

1.在接口定义中定义一个SQL请求
![image](https://github.com/metersphere/metersphere/assets/88763608/6a86a014-e36c-46c9-9755-222ffd58e1de)
2.将SQL请求导入接口自动化中
![image](https://github.com/metersphere/metersphere/assets/88763608/15e1defe-e50b-4a29-82ca-338bcf3caf7d)
3.切换场景运行环境后，SQL请求的运行环境和数据源都变化了
![image](https://github.com/metersphere/metersphere/assets/88763608/868b8324-794c-4864-b99f-554c971d5ffe)

### 期待的正确结果

不应该变化

**Comment by luty2018** [comment]
设计如此，在实际应用中，SQL步骤是辅助场景的前后步骤的，所以大多数用户希望跟随用户选择的场景执行环境来同步变更，如果不希望变更，可以在当前场景运行环境中配置一套相同的数据源。

**Comment by linfengjjj** [comment]
罗老师 是不是可以开放一个选项呢？跟随环境变更或不跟随环境变更？因为有一部分用户会认为这个是Bug，并且有一些场景的确不需要跟随环境切换数据源。

**Comment by linfengjjj** [comment]
而且用户的运行环境中一般不止有一个数据源，当有多个数据源的情况下，切换运行环境，并不能切换到用户需要的数据源中，自动切换后，还需要用户再手动去选择需要的数据源。看起来这样设计还是会不太友好。
