### ISSUE TITLE
[FEATURE]建议增加全局前置、后置脚本功能

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#2685]
**请描述您的需求或者改进建议.**
对于全局前置脚本：测试中经常有系统需要先登录后获取动态生成的token，再进行后续测试。按照当前的ms的相关设置，在单接口测试里需要给每个用例均添加一个前置脚本来调用登录请求获取token，再将token值配置到用例的header中，涉及很多重复操作。
对于全局后置脚本：例如测试完后希望将测试数据回归至原始状态，可通过全局脚本还原。

**请描述你建议的实现方案**
在环境管理中添加全局前置、后置脚本的设置

**Comment by xulinde** [comment]
这个功能正在调研中

**Comment by GITMrzk** [comment]
这个很关键啊，什么时候上？？

**Comment by xulinde** [comment]
v1.13已支持
