### ISSUE TITLE
[FEATURE] 性能测试报告导出页面加载空白，以为是有报错，等了很久报告才出来，希望优化下：页面添加下载报告进度条效果

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#26864]
### MeterSphere 版本

2.10.6

### 请描述您的需求或者改进建议

问题性能测试报告导出页面加载空白，以为是有报错，等了很久报告才出来，
希望优化下：页面添加下载报告进度条效果

![性能测试报告导出页面空白](https://github.com/metersphere/metersphere/assets/43202800/bb8285fb-3881-42d3-9cd5-1d0746912f7f)

### 请描述你建议的实现方案

页面添加下载报告进度条效果

**Comment by liuruibin** [comment]
现在的导出仅仅是个前端页面保存pdf，不能完整展示数据。v3会考虑重新设计这里
