### ISSUE TITLE
[BUG]接口测试SQL请求查询datetime类型数据出来后日期和时间中间会加“T”

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26869]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

接口测试SQL请求查询datetime类型数据出来后日期和时间中间会加“T”

### 重现步骤

1.准备一个datetime类型的数据
<img width="268" alt="a1c76ee0e90e14e5df4e5cc09a475f0" src="https://github.com/metersphere/metersphere/assets/88763608/8bb84a55-1047-48c2-8938-c9c10d2fe3dc">
2.在接口自动化场景中场景一个自定义SQL请求去查询这个字段，查询出来后中间多了"T"
<img width="567" alt="22b972aeeb8e11a8358d8cbc418477c" src="https://github.com/metersphere/metersphere/assets/88763608/8018a6b5-3033-411f-9b71-bce11e8f7661">

### 期待的正确结果

应该跟在mysql中查询出来的数据保持一致

**Comment by zrfit** [comment]
您好，感谢反馈！metersphere后端调用的jmeter，返回数据如此，如需要其它格式可通过脚本实现格式转换。
<img width="832" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/c1dca938-ada5-405a-8769-fbb21c8243f0">
