### ISSUE TITLE
[BUG]接口测试执行时后置操作提取参数中通过正则方式提取body内容时，会提取到请求内容的数据。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#26873]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

接口测试执行时后置操作提取参数中通过正则方式提取body内容时，会提取到请求内容的数据。
![ab2a27a35f11c796fa6a1c7698dabca](https://github.com/metersphere/metersphere/assets/83771182/94aa6afc-4695-4448-9990-1021cbdbed5c)
<img width="258" alt="99d80dd9bf80ec05aeaa9c2af8b366f" src="https://github.com/metersphere/metersphere/assets/83771182/4ce7e55f-a81d-4479-bda6-7e0d8d5e9ae2">
返回报文中并没有该信息
![f4f727ce8188f62072a7e3d796f62a4](https://github.com/metersphere/metersphere/assets/83771182/448d3e3f-aad5-43b8-8f19-196fe0e8333e)
![cd25f2bf623f42f2ba9b413599c90ec](https://github.com/metersphere/metersphere/assets/83771182/0fb16fe9-9f30-4f37-b18c-37f0e9c70bcc)
后来发现请求报文中有该信息，修改请求信息再次执行，参数提取的值会根据新的请求信息发生变化。这个接口比较特殊，请求报文和返回报文的格式很相近。

### 重现步骤

接口测试执行时后置操作提取参数中通过正则方式提取body内容时，会提取到请求内容的数据。

### 期待的正确结果

接口测试执行时后置操作提取参数中通过正则方式提取body内容时，如果返回报文中未包含符合条件的信息，则提取不到信息。

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.7-lts未复现该问题，建议升级尝试。
<img width="1049" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/4515a859-abf5-4a73-80ab-a7cb291e384f">
