### ISSUE TITLE
[BUG] 从Postman里面导出的接口包含断言脚本，导入到MS中断言脚本丢失

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26874]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

从Postman里面导出的接口包含断言脚本，导入到MS中断言脚本丢失

![image](https://github.com/metersphere/metersphere/assets/33945037/1287e2c3-554f-481e-8ed6-c5b644e674e7)

![image](https://github.com/metersphere/metersphere/assets/33945037/7e9d7a86-b008-4e47-8873-829cfa113844)

### 重现步骤

[登录接口测试. postman_collection.txt](https://github.com/metersphere/metersphere/files/12699549/postman_collection.txt)

上面是postman的文件，导入MS之后，断言丢失

**Comment by 13290445582** [comment]
您好，暂不支持，感谢理解与反馈。
