### ISSUE TITLE
[BUG]性能测试压力机分摊计算规则有误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#26880]
### 联系方式

shenkaibo

### MeterSphere 版本

v.1.20.24-lts 和 v2.10.6-lts

### 使用外置数据库

否

### 问题描述

性能测试压力机分摊计算规则有误
比如 100000 并发，27台 压力机，最大并发数一致，
目前算法： 
ratios 为 1/27 = 0.037 ，四舍五入后 每台 0.04 
下载脚本时，100000 * 0.04 = 4000 ，前26台 压力机分别为 4000 并发，
最后一台压力机 为 100000 - 4000 * 26 = -4000 , 最后一台压力机出现了负数。

### 重现步骤

比如 100000 并发，27台 压力机，最大并发数一致

**Comment by liuruibin** [comment]
我们用两位小数计算分配策略，在某些时刻会出现问题。

建议先使用自定义策略手动处理，或者调整压力机数量来避免这个问题
