### ISSUE TITLE
[BUG]UI测试，场景导出后再导入，第二个打开网页的步骤错误识别成切换窗口

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#26894]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

UI测试，场景导出后再导入，第二个打开网页的步骤错误识别成切换窗口

### 重现步骤

1.UI用例包含以下几个步骤
![image](https://github.com/metersphere/metersphere/assets/55130444/ea218912-57a7-4eb3-9d79-7abc045210bc)
2.将场景导出后再导入，第二个打开网页的步骤错误识别成切换窗口
![image](https://github.com/metersphere/metersphere/assets/55130444/57328eb2-1cde-4a29-82ce-d1da30478003)

### 期待的正确结果

1.导入后需要是原来的用例步骤。

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.7-lts无该问题，待发布后建议升级尝试。
