### ISSUE TITLE
[BUG]接口自动化内切换环境 ，SQL步骤的数据源切换错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#26909]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

接口自动化内，两个环境的数据源名称相同，切换环境不会自动切换到相同名称的数据源；切换环境后，默认选择第一个数据源名称，而不是自动切换到相同名称的数据源。

### 重现步骤

1、项目设置下的环境配置，创建两个环境，并在两个环境内创建多个数据源，其中某一个数据源名称相同；

2、创建接口自动化，在请求步骤中的前置或者后置操作中添加sql；

3、选择一个环境及sql步骤的数据源配置为名称相同的数据源并保存；

4、观察是否会切换到相同名称的数据源

### 期待的正确结果

可以自动切换至名称相同的数据源

### 附加信息

<img width="923" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/579594de-503b-4e20-b484-bba4cf2b6990">

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts优化。
