### ISSUE TITLE
[BUG]从JMeter界面导出JMX文件，再导入MeterSphere执行压测时，页面经常提示无法解析文件

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#26907]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

如标题所描述的信息

### 重现步骤

使用JMeter界面，可以正常执行一个单接口的性能压测，Listener监听器中，有添加“查看结果树”，“聚合报告”，“jp@gc图表插件”等操作
<img width="1009" alt="1" src="https://github.com/metersphere/metersphere/assets/18387151/6708347f-7249-4252-9e3e-f106790e5f9a">

将此JMeter界面的测试计划，导出成JMX文件后，导入到MeterSphere页面，点击“保存并执行”后，页面提示“无法解析JMX文件”
<img width="1269" alt="WX20230926-153037@2x" src="https://github.com/metersphere/metersphere/assets/18387151/fb8b3d0f-e678-4ba7-8b15-bc78a62c4f24">

**临时解决方法是：**
只保留JMeter界面的压测请求和前置脚本等信息，需要手动删除JMeter界面的“Listener监听器”等操作，再次将JMeter测试计划导出成JMX文件
<img width="1009" alt="2" src="https://github.com/metersphere/metersphere/assets/18387151/3ad7e901-99ef-4115-9374-6a4bf10fb44f">

重新导入新的JMeter JMX文件到MeterSphere页面，点击“保存并执行”后，MeterSphere才能正常执行压测
<img width="1265" alt="WX20230926-160022@2x" src="https://github.com/metersphere/metersphere/assets/18387151/75e35dc3-ab80-49cf-bf3e-f859cc4435c7">

### 期待的正确结果

由此可见，从JMeter导出JMX文件后，再导入到MeterSphere页面执行压测，这个操作过程不流畅。

需要测试人员提前删除JMeter界面的“Listener监听器”等操作，使用体验不好。

所以，为了提升用户使用体验，MeterSphere在解析JMeter JMX文件时，需要自动过滤掉JMX文件中的“listener监听器”操作，这样的压测过程才更加流畅。
<img width="1010" alt="WX20230926-153914@2x" src="https://github.com/metersphere/metersphere/assets/18387151/65ef8969-c323-4529-b192-ef1dd2f2ab03">

**Comment by 13290445582** [comment]
您好， 可以将您的jmx文件提供一下。

**Comment by songbing0312** [comment]
https://nginx-qa.fit2cloud.com/tmp/test0926.jmx

**Comment by 13290445582** [comment]
感谢反馈，计划v2.10.8版本优化该问题。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。

**Comment by suqin-sayweee** [comment]
压测创建时，title 里面包含了& 符号就会报解析失败
