### ISSUE TITLE
[BUG] 在接口定义页面，新增运行环境的通用配置，删除不生效。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26902]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

在接口定义页面，新增运行环境的通用配置，删除不生效。
1. 进入接口定义页面
2. 右上角环境配置
![image](https://github.com/metersphere/metersphere/assets/33945037/a781fd8f-8758-49d3-8bdb-3a4bec9d340e)
3. 随便找一个环境添加一个通用配置
![image](https://github.com/metersphere/metersphere/assets/33945037/107739b6-0723-4f28-a6c4-b3dc072e64b2)
5. 然后再删除确认，删除失败。

https://github.com/metersphere/metersphere/assets/33945037/c0d885f9-7a22-4e8a-8000-618267fbcea3

### 重现步骤

同上

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.7-lts不存在该问题，待发布后建议升级尝试。
