### ISSUE TITLE
[FEATURE] 性能测试结果希望做个测试详情看板

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#26910]
### MeterSphere 版本

1.20.20

### 请描述您的需求或者改进建议

我算是性能测试项目的小主管，主要会检查下小伙伴 的测试情况及协助分析测结果

目前测试结果分散在很多项目下面，不方便统测试结果，也没有配置管理看板的功能，对手下测试的情况都不太清楚要挨着点进去

建议：希望可以做测试结果看板，可以树状结构查看各个项目下  测试脚本的测试结果数据 （主要是管理看数据用，希望能够考虑）

**Comment by luty2018** [comment]
感谢反馈， 请问是类似接口测试首页的数据汇总吗？

**Comment by opopjasica** [comment]
可以的，最好是能跨项目获得一些图表数据，  比如近几天性能测试执行过的脚本，根据指标筛选异常脚本查看报告数据，可以做一些预览展示跳转查看详情

**Comment by luty2018** [comment]
了解， 这部分我们会在v3.0版本支持哈。
