### ISSUE TITLE
[BUG]接口自动化，打开接口详情，UI界面会不规则滑动

### ISSUE THREAD

**Issue by juranran** [metersphere/metersphere#26913]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

接口自动化，打开接口详情，UI界面会不规则滑动

https://github.com/metersphere/metersphere/assets/85550360/67d7af8d-0235-40f3-9a54-5a2db5a1eb52

### 重现步骤

接口自动化，打开接口详情，UI界面会不规则滑动

### 期待的正确结果

接口自动化，打开接口详情，UI界面只会随用户的鼠标滑动

**Comment by fit2-zhao** [comment]
感谢反馈，有重复issues，请关注这个issues：https://github.com/metersphere/metersphere/issues/26158
