### ISSUE TITLE
[BUG]创建新的工作空间并切换后，还未创建项目，但是测试跟踪首页却显示了上个工作空间的项目数据

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26917]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

创建新的工作空间并切换后，还未创建项目，但是测试跟踪首页却显示了上个工作空间的项目数据。

### 重现步骤

1. 在系统设置中创建的新的工作空间并切换
2. 不创建项目，但是切换到测试跟踪首页页面，发现显示了上个工作空间的项目数据

### 期待的正确结果

创建新的工作空间并切换后，还未创建项目，不显示上个工作空间的项目数据。

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/52cfbb1d-6655-4a1e-bda0-129f1a6d6260)
![image](https://github.com/metersphere/metersphere/assets/50016789/5a8b4d21-fab5-41ba-9133-813a8d11509f)

**Comment by zrfit** [comment]
您好，感谢反馈！有超级管理员权限的用户存在这个问题。
临时解决方案：新建工作空间后在系统设置-工作空间-项目管理新建项目，再次切到测试跟踪等其它模块页面数据就不会展示上个项目的数据了。
计划在v2.10.8-lts修复。
