### ISSUE TITLE
[BUG]在自动化场景中步骤A中提取json参数-响应结果中的某个子节点 ，在后面的步骤B中引用第1步的参数，发现无法编辑

### ISSUE THREAD

**Issue by mengranzhidie** [metersphere/metersphere#26922]
### 联系方式

13770832@qq.com

### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

场景：在自动化场景中：
1、在步骤A中提取json参数-响应结果中的某个子节点
2、在后面的步骤B中引用第1步的参数，发现无法编辑
![image](https://github.com/metersphere/metersphere/assets/101786073/20735392-423b-4d85-8b75-cf270b694e1b)
3、通过关闭json-schema手工编辑脚本可以满足
![image](https://github.com/metersphere/metersphere/assets/101786073/9880be6d-9622-4813-b9cd-7b1831539f70)
4、但是如果重新打开开关json-schema，数据就错乱了
![image](https://github.com/metersphere/metersphere/assets/101786073/a02616a8-27fc-43f2-91e6-9e2c37b0192f)
![image](https://github.com/metersphere/metersphere/assets/101786073/95cf2cde-46e7-4640-a4a8-c02971173b28)

### 重现步骤

见问题描述。

### 期待的正确结果

1、json类型可以编辑值
2、解决关闭json-schema的错乱问题

**Comment by zrfit** [comment]
您好！感谢反馈！
1、步骤A中提取的数据格式是什么？是字符串还是json？
2、开启schema后，字段类型为object和array类型的跟节点值是无法编辑的，下面的子节点值可编辑。
<img width="966" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/18920979-5758-4aac-a5c9-0ab9b0404bae">
3、最新版本v2.10.7-lts未复现错乱问题，建议升级尝试。
<img width="507" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/c77b5375-4c0b-4368-871d-108ef8c166a2">
<img width="922" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/0d589c18-4469-4c1e-bcda-e55661af5335">

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
