### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by liming07515** [metersphere/metersphere#26921]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

交流群67-铭子

### 请描述您的需求或者改进建议

测试用例导入时，自动生成的用例ID为倒序，导致第一条用例的ID为最大的，最后一条用例生成的ID为最小。
导致用例查看时，用例的顺序颠倒
目前导入现状：
测试用例1——ID：100005
测试用例2——ID：100004
测试用例3——ID：100003
测试用例4——ID：100002
测试用例5——ID：100001

### 请描述你建议的实现方案

希望在测试用例自定义ID未开启情况下，导入用例时，系统自动生成的ID为正序。
即：
测试用例1——ID：100001
测试用例2——ID：100002
测试用例3——ID：100003
测试用例4——ID：100004
测试用例5——ID：100005

### 附加信息

![73f1f6b7b449c5ac6ba9ff50a3c7b47](https://github.com/metersphere/metersphere/assets/146169477/1a04f44f-d504-4cd9-ae6c-39d6e9e3f735)

**Comment by luty2018** [comment]
这里是为了保证展示的用例顺序与导入文件中的一致，所以在文件导入后进行了ID降序排列

**Comment by liming07515** [comment]
刚深入测试了下，上述所说用例显示颠倒的问题是在特定场景下出现。
复现步骤：再用例评审模块进行关联用例时，如关联用例勾选时，勾选‘选择所有数据(共XX条)后，点击关联后。评审时进行脑图模式查看，用例的顺序是颠倒的。


’

**Comment by liming07515** [comment]
![image](https://github.com/metersphere/metersphere/assets/146169477/cd397cdb-80ed-445f-8c66-612ad8a1bad8)

**Comment by liming07515** [comment]
![image](https://github.com/metersphere/metersphere/assets/146169477/732e9644-599f-4d27-adea-0d55a78b369d)
![image](https://github.com/metersphere/metersphere/assets/146169477/fc18367c-e022-46b4-89ba-c9dccf049c8e)
测试计划关联用例，切换脑图模式查看，用例的顺序也是错乱的

**Comment by sss903065212** [comment]
@luty2018

**Comment by liming07515** [comment]
追加问题场景：
在测试计划模块，关联测试用例后，切换脑图模式，用例顺序也是错乱的，参加如下截图

![image](https://github.com/metersphere/metersphere/assets/146169477/25dd677a-ad19-4ca8-b94a-f05f8e3c9c0a)

![image](https://github.com/metersphere/metersphere/assets/146169477/1b777441-bfca-42f8-ac58-481b477b07b2)

**Comment by luty2018** [comment]
脑图是要按模块逐个级别展开的， 没法和列表完全一致。这受限于用例归属的模块。比如列表下第一个是模块1/a，第2-8是模块2,第10个是模块1/b，那切换脑图的时候，a和b 都是模块1，自然会显示在一个节点下。这么说能理解吗？
