### ISSUE TITLE
[BUG]接口定义 case 列表页，页码与列表数据显示不一致

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#26936]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

接口定义 case 列表页，页码与列表数据显示不一致
![image](https://github.com/metersphere/metersphere/assets/103627487/ff6bda60-1b35-4b70-a04d-a7032888a857)

### 重现步骤

1. 接口定义有多个模块，在一个模块下有14条用例(大于10条，能分页显示）切换到第2页后，再点击其他模块，再切回14条用例模块，就能看到这个现象了。
例如：下图，点击 test 模块，case 显示14条，切换到第二页，然后点击其他模块，再切回 test 模块
![image](https://github.com/metersphere/metersphere/assets/103627487/31e7fad5-49bd-4799-91d8-198984716b9a)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts优化。
