### ISSUE TITLE
[BUG]功能用例，进行评审之后，变更记录中没有找到评审记录

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#26938]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.7-lts

### 使用外置数据库

否

### 问题描述

功能用例，进行评审之后，变更记录中没有找到评审记录

### 重现步骤

1、新建一条用例
2、新建一条评审记录并关联
3、选择评审通过
4、回到功能用例
5、查看变更记录
6、发现没有记录评审结果

### 期待的正确结果

有评审结果的记录

### 附加信息

![IMG_20231007_091344](https://github.com/metersphere/metersphere/assets/56757548/23a11d16-cd7e-4238-b0b6-0e84bfe7ba43)

**Comment by 13290445582** [comment]
您好，在v2.0版本设计上并未规划记录该内容，若需要变更记录处记录该内容，可提需求。
