### ISSUE TITLE
创建接口路径重复后，弹出报错信息，关掉报错信息后，再点击创建接口一直在转圈

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#26945]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

创建接口路径重复后，弹出报错信息，关掉报错信息后，再点击创建接口一直在转圈。

### 重现步骤

1. 点击创建接口，填写好信息，创建接口；
2. 保存时出现报错提示，接口地址重复；
3. 修改新的路径后，发现页面一直在转圈，点击不了保存按钮；
4. 重新打开创建接口，填写不重复的接口，发现页面也一直在转圈，点击不了保存按钮。

### 期待的正确结果

修改新的路径后，页面不转圈，可以点击保存按钮。

### 相关日志输出

```shell
无
```

### 附加信息

![1696661616466](https://github.com/metersphere/metersphere/assets/50016789/377b63f7-6bb6-40fe-ac2a-0c0c0fc1039e)
![1696661671899](https://github.com/metersphere/metersphere/assets/50016789/d670096f-6c0d-4d5b-a5f2-ea25f4c0c59d)
![1696662313220](https://github.com/metersphere/metersphere/assets/50016789/bdb4729d-135f-4670-abfa-e9f5444ecc75)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本修复该问题。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
