### ISSUE TITLE
[BUG]定义接口时添加case，修改环境配置中的变量后保存测试不生效

### ISSUE THREAD

**Issue by glzzny** [metersphere/metersphere#26952]
### 联系方式

18510991012

### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

定义接口并添加case，在case中修改环境配置中的变量值后保存再调用接口，该变量值仍为之前的变量值，未在修改后的测试中生效

### 重现步骤

1.定义接口
2.添加case
3.case中修改环境变量中的值保存
4.调用接口

环境变量：
![image](https://github.com/metersphere/metersphere/assets/60509485/eedbcef2-ee8b-49b0-a72c-e09860c1ffde)

请求头：
![image](https://github.com/metersphere/metersphere/assets/60509485/21e3dbe9-b1f6-41d4-91ad-edc7dd9fc073)

保存后再次请求，cookie用的仍是之前的
![image](https://github.com/metersphere/metersphere/assets/60509485/04592e2a-8488-43e4-ac61-4f68edbb9646)

**Comment by zrfit** [comment]
您好，感谢反馈！该问题为已知问题，计划v2.10.8-lts修复。
