### ISSUE TITLE
[FEATURE]建议增加限制测试计划执行时长控制的字段

### ISSUE THREAD

**Issue by Liu-Ying-95** [metersphere/metersphere#26963]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 联系方式

ying14_l@163.com

### 请描述您的需求或者改进建议

测试跟踪-测试计划
设置定时任务后测试计划碰到有用例running 后只能手动暂停任务，计划会一直处于执行状态不能完成，不会开启下一个定时任务，建议增加一个限制测试计划执行时长控制的字段

**Comment by luty2018** [comment]
是否考虑设置用例的超时时间来规避这个问题呢
