### ISSUE TITLE
[FEATURE]测试用例用xmind导入时希望能支持导入“关联需求”字段

### ISSUE THREAD

**Issue by FangLiao12** [metersphere/metersphere#26968]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 联系方式

13550384499@163.com

### 请描述您的需求或者改进建议

测试用例xmind导入模板不支持“关联需求”字段，希望能支持。

**Comment by luty2018** [comment]
感谢建议， 这个我们会在v3.0讨论规划
