### ISSUE TITLE
[FEATURE]建议测试跟踪-缺陷列表的表头字段设置可以持久化保存

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26975]
### MeterSphere 版本

v2.10.7-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

目前把缺陷列表的某些字段隐藏不展示的配置是保存在前端的，用户一刷新或清理缓存后所有字段就又展示出来了。
特别是在对接第三方平台后，会展示太多字段，有点累赘，用户需要持久化隐藏一些不重要的字段。
![image](https://github.com/metersphere/metersphere/assets/88763608/bf72d6ec-5488-4bc2-9ee1-1ace9e577bb7)

**Comment by luty2018** [comment]
这个功能是支持的， 可能部分第三方的字段没有支持， 可以提缺陷处理
