### ISSUE TITLE
[BUG]接口定义--case-通过条件检索之后，不方便查看API

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#26970]
### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

接口定义--case-通过条件检索之后，不方便查看API

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/19423100/dcc21756-1d8c-4b2c-82ab-1f454269772b)
1、接口定义--case-输入case编号检索
2、发现API错误了，想去修改API
3、没有办法通过case检索到api，也不知道这个case属于哪个模块

### 期待的正确结果

便捷查看API  26747问题相同

**Comment by luty2018** [comment]
如果你的场景是希望找到对应的API ，那么建议在这里复制路径然后去API列表通过api路径查询
