### ISSUE TITLE
[BUG]接口测试，认证配置，如果勾选了其中任何一个认证， 就无法删除了，必须得勾选一个

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#26983]
### MeterSphere 版本

v2.10.7

### 使用外置数据库

否

### 问题描述

1.接口测试选择了认证方式后，就一定得选择一个，无法清空。
![image](https://github.com/metersphere/metersphere/assets/55130444/f528d9fc-c498-42bc-a6c3-3d347a6249c1)
![image](https://github.com/metersphere/metersphere/assets/55130444/e4ad1e57-ff27-4998-a17a-20f649b2a23b)

### 重现步骤

1.接口测试-认证配置-选择认证方式后无法清空

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts优化。
