### ISSUE TITLE
[BUG]项目设置-->项目环境-->操作【编辑】环境-->根据变量名称搜索之后保存，点【确认】所有变量都以搜索之后数据保存，没有搜索到的数据都被清空。

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#26995]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

版本:   v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

项目设置-->项目环境-->操作【编辑】环境-->根据变量名称搜索之后保存，点【确认】所有变量都以搜索之后数据保存，没有搜索到的数据都被清空。

![image](https://github.com/metersphere/metersphere/assets/23476281/7f1dd7d8-de21-4b7c-9daf-cc418a6e81dc)

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/23476281/3b79a34a-2d26-42ae-94f4-797815846b73)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8修复该问题。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
