### ISSUE TITLE
[BUG]  metersphere平台所有富文本框在点击图片预览后，富文本框属于失去焦点，但非预览模式，需要多余操作，使用不流畅

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#26996]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

metersphere平台所有富文本框在点击图片预览后，富文本框属于失去焦点，但非预览模式，需要多余操作，使用不流畅

### 重现步骤

鼠标点击富文本框外，再点击图片进行预览
![image](https://github.com/metersphere/metersphere/assets/103925124/4bc61914-9b6d-435f-9798-db7c0e1f571b)
点击页面位置，此时富文本框显示为：
![image](https://github.com/metersphere/metersphere/assets/103925124/b47edce5-52dc-4909-a4de-c187d15d569c)
希望显示为下图，不然需要多余操作（点击富文本框内，再点击富文本框外）：![image](https://github.com/metersphere/metersphere/assets/103925124/4bc61914-9b6d-435f-9798-db7c0e1f571b)

**Comment by zrfit** [comment]
您好，感谢反馈！v2富文本框用的是markdown ，三方问题，暂不处理。
