### ISSUE TITLE
[FEATURE]测试跟踪-功能用例建议增加一个查看最近修改的用例的入口

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#26999]
### MeterSphere 版本

v2.10.7-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

用户反馈用例很多的时候，修改用例关闭后经常不知道刚刚修改的是哪条用例。
建议加一个“最近修改”的用例列表，方便用户查看最近操作的用例。
![image](https://github.com/metersphere/metersphere/assets/88763608/8dc18feb-3587-41b6-8982-c2e31dd0a6b0)

**Comment by liqiang-fit2cloud** [comment]
可以用“更新时间”那列排序。
