### ISSUE TITLE
[BUG]  接口测试首页，接口用例覆盖率统计计算错误

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#26993]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/33945037/8e898e1a-18d7-49da-a206-e77c7e2067eb)

![image](https://github.com/metersphere/metersphere/assets/33945037/19f39c4b-9687-4f07-b9d9-eceb3ab96a83)

### 重现步骤

保证有接口定义，接口用例

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本修复该问题。

**Comment by Somebody-JIAN** [comment]
这是在v2.10.7版本中，针对接口测试首页的计算方法进行性能优化时出现的取值错误。 
感谢提醒！

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
