### ISSUE TITLE
[FEATURE]测试用例优化

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [metersphere/metersphere#26997]
### MeterSphere 版本

v2.10.7-lts-b1

### 请描述您的需求或者改进建议

1、创建用例的页面，步骤描述中包含“用例步骤、预期结果”，建议可以自定义添加其他属性，比如“测试数据”等等
2、创建用例的页面，只有一个“前置条件、步骤描述”，建议可以添加多个“前置条件、步骤描述”，一条用例下可创建多个子用例。

### 请描述你建议的实现方案

无

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/8575159/89d3ca7f-df48-499b-94f5-be6ae9ced2d1)

**Comment by luty2018** [comment]
问题1，建议使用文本类型， 同时在自定义模板中创建想要的其它属性
问题2，前置条件设计为富文本编辑器支持用户创建多条内容
创建子用例的场景是什么？是否可用用系统内置的关联用例，或者前后置依赖用例来覆盖？
