### ISSUE TITLE
支持环境配置功能

### ISSUE THREAD

**Issue by Sadomaster** [metersphere/metersphere#27]
1.可以配置多套不同的环境，测试环境的接口可以在正式环境上面跑通

**Comment by wangzhen-fit2cloud** [comment]
你好，我们在 v1.1 版本中会提供针对项目的环境管理功能，可以等我们 v1.1 版本发布后看下是否能满足你的需求。

**Comment by luty2018** [comment]
1.1版本已支持 请更新体验
