### ISSUE TITLE
[BUG] 接口定义-所属模块，默认只展示了根目录，且所属模块未从根目录开始高亮展示

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27017]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.5-lts

### 使用外置数据库

否

### 问题描述

接口定义-所属模块，默认值展示了根目录，且所属模块未从根目录开始高亮展示

### 重现步骤

接口所属默认默认只显示根目录，且所属根目录未高亮展示
![image](https://github.com/metersphere/metersphere/assets/103925124/55372487-cebb-434f-ab15-09e993c40647)
多层几级也未高亮展示
![image](https://github.com/metersphere/metersphere/assets/103925124/df7dabd4-7b96-4fb4-874b-9e310bbe8920)
不利于查看当前层级

**Comment by zrfit** [comment]
您好，感谢反馈！考虑性能问题只展示所属模块，不展示模块路径，高亮也只显示所属模块，v2暂不处理。
