### ISSUE TITLE
[BUG]修改了某个api参数在api列表保存没有使用一键同步参数功能 然后切换到case列表，勾选几个用例然后选择批量同步参数无反应 f12接口有报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27021]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

1、修改了某个api参数在api列表保存没有使用一键同步参数功能

2、然后切换到case列表，勾选几个用例然后选择批量同步参数无反应
f12接口有报错

### 重现步骤

1、修改了某个api参数在api列表保存没有使用一键同步参数功能

2、然后切换到case列表，勾选几个用例然后选择批量同步参数，页面无反应
f12接口有报错
![修改了某个api参数在api列表保存没有使用一键同步参数功能](https://github.com/metersphere/metersphere/assets/43202800/91e9e57e-c108-4283-ab90-bb9c4bfa8c3e)

### 期待的正确结果

应该可以同步case参数

**Comment by zrfit** [comment]
您好，感谢反馈！v2.10.8-lts将修复该问题，待发布后升级尝试。
