### ISSUE TITLE
测试用例能够支持复制粘贴图片而不仅仅是上传

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#2702]
**请描述您的需求或者改进建议.**
现在的测试用例处上传图片很复杂，如果支持复制粘贴上传会体验升级一个档次
另外测试用例中的执行步骤也需要支持上传图片，有很多使用场景用文字不清晰明了，而放在下方的图片处又不方便查找

**请描述你建议的实现方案**

1、建议在测试用例中支持复制粘贴图片
![image](https://user-images.githubusercontent.com/44960709/117899964-dcbeec00-b2fa-11eb-87bb-5ace207b7267.png)
2、建议在执行用例的步骤支持上传图片（可复制粘贴）
![image](https://user-images.githubusercontent.com/44960709/117900670-3e338a80-b2fc-11eb-833a-de51d4dbef2e.png)

**Comment by xulinde** [comment]
1.测试用例上传图片，下个版本会支持
2.执行用例处暂不支持
