### ISSUE TITLE
[BUG] mock环境修改地址-调试-修改的地址生效，然后再进入调试mock地址又变回去了

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27023]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

mock环境修改地址-调试-修改的地址生效，
然后再进入调试mock地址又变回去了

### 重现步骤

1、接口测试 api -test列表调试，mock环境修改地址-调试-修改的地址生效，
2、问题：关闭调试页面然后再进入调试mock地址又变回去了

![mock环境修改地址-调试-然后保存](https://github.com/metersphere/metersphere/assets/43202800/8c6ba896-3dfd-4e22-9c4e-e69c00ad58db)

### 期待的正确结果

修改mock地址生效

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本修复这个问题。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
