### ISSUE TITLE
[BUG]UI自动化步骤中元素库显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27036]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI自动化步骤中元素采用元素定位的方式，没有涉及到元素库，但是高级设置下面却显示元素库元素

### 重现步骤

1、添加一个采用元素定位的步骤
2、查看下方的元素库元素（有时会出现元素库列表缓慢加载）

### 附加信息

没有其他设置，直接使用的元素定位：
<img width="1338" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/3812a557-f957-40d7-b88e-17b05b83ecf3">

**Comment by zrfit** [comment]
您好，感谢反馈！
1、定位方式为元素定位-高级设置-元素库显示的所有元素库数据；为元素对象-高级设置-元素库只显示对应元素数据。
2、元素库列表缓慢加载，元素数量是多少？多慢？请提供下具体数据信息，验证150+元素列表显示是正常的。

**Comment by dashenyucainiao** [comment]
我只用到一个元素，为什么步骤内的元素库显示所有元素？
