### ISSUE TITLE
[BUG]UI测试编辑场景步骤时，添加配置保存后点击刷新按钮后，配置会消失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27034]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI测试编辑场景步骤时，添加配置保存后点击刷新按钮后，配置会消失，包括系统内置的配置。

### 重现步骤

1、编辑某个场景步骤，添加高级配置，例如添加前后置脚本
2、保存后，点击刷新按钮
3、查看步骤1设置的配置信息是否存在

### 期待的正确结果

可以保留正常的配置信息

### 附加信息

刷新之前：
<img width="1265" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/b08adbd7-2d33-4f62-a71a-da7551e39948">

刷新之后：
<img width="1316" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/c7def3a8-cc34-4404-96df-f6e5f8db976b">

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，添加高级配置-点击保存按钮保存成功后-点击刷新按钮-配置数据仍存在。是必现的吗？方便提供下场景并录个视频看下吗？

**Comment by dashenyucainiao** [comment]
https://github.com/metersphere/metersphere/assets/32027713/4e128efd-13e2-4915-a95c-09a1ac48daca

**Comment by zrfit** [comment]
视频没看到点击保存按钮呢，不点击保存按钮进行刷新，数据是不不会保存的。

**Comment by dashenyucainiao** [comment]
已经点了保存且配置并不是新添加的，是打开已经保存好的场景

**Comment by zrfit** [comment]
经沟通，多次尝试找到了复现规律，当打开多个场景编辑tab页的时候，编辑某个场景，选中场景步骤有前置操作，点击刷新按钮，前置操作步骤不显示了，计划v2.10.8-lts修复。

**Comment by Hyyfit** [comment]
您好，单个标签页可以正常刷新，多标签页刷新会存在问题，计划在v3的版本里解决。
