### ISSUE TITLE
[BUG]【接口测试-接口自动化】开发自定义协议插件上传到MS中使用遇到问题

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#27031]
### 联系方式

张树彬

### MeterSphere 版本

2.10.7LTS

### 使用外置数据库

否

### 问题描述

开发自定义fix接口协议插件上传到MS上，在场景中可以正常使用，但当场景中同时添加http请求时，对fix请求设置断言后，htpp请求也会同时被断言。

### 重现步骤

1. 开发自定义接口协议插件上传到MS
2. 创建接口场景
3. 添加http请求
4. 添加自定义协议插件请求
5. 对自定义协议插件请求设置断言、执行场景
6. http请求也会同时被断言

### 期待的正确结果

期望对自定义协议请求设置断言并执行时，不会影响到其他接口协议的请求

### 附加信息

![3cf67fa1706508fd7395314fa4930e5c](https://github.com/metersphere/metersphere/assets/77324661/9fa12b59-373b-46d7-a7af-97b06e4e5ef9)
![0e91e009daf9e14c60747c1aaf4834f6](https://github.com/metersphere/metersphere/assets/77324661/afe7b7fc-d9c3-4c4d-a7a3-cb84a1bd96f5)

**Comment by 13290445582** [comment]
您好，未有插件复现该问题。

**Comment by zhangzhaox** [comment]
@binbin0406 我按照指导手册上得要求，想改造完善下socket协议，上传后没有成功展示，能指导下吗，谢谢

**Comment by binbin0406** [comment]
> @binbin0406 我按照指导手册上得要求，想改造完善下socket协议，上传后没有成功展示，能指导下吗，谢谢

可以在企业微信群里联系下销售，找技术支持一下

**Comment by binbin0406** [comment]
> @binbin0406 我按照指导手册上得要求，想改造完善下socket协议，上传后没有成功展示，能指导下吗，谢谢

可以在企业微信群里联系下销售，找技术支持一下

**Comment by binbin0406** [comment]
> 您好，未有插件复现该问题。

主要因为这个插件是客户针对自己接口写的，我们没有特定的服务端进行复现。已经跟客户沟通，后面再想办法定位一下。

**Comment by 13290445582** [comment]
该问题未复现，后续有问题请重新提issue，感谢理解和支持～
