### ISSUE TITLE
[BUG]UI场景后置操作添加数据提取时，该步骤的元素库显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27033]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI自动化场景，步骤内后置操作添加数据提取时，步骤的高级设置下，元素库显示错误

### 重现步骤

1、添加一个元素操作的步骤
2、该步骤的元素来自于元素库
3、在步骤的后置操作中添加数据提取
4、提取的元素来自于元素库且和步骤二的元素设置的元素为非同一个，如果有多个数据提取，则以最后一个数据提取的元素进行显示元素库
5、再元素库查看

### 期待的正确结果

与步骤中的元素库一一对应

### 附加信息

原步骤的元素库显示：

<img width="1313" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/c9e9838d-d9ac-4c0a-bd8c-79e02ee1c273">

添加数据提取后的元素库显示：
<img width="1380" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/47be2bd3-c7ff-4b17-ba44-c0d6b4119028">
<img width="1433" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/82cbd4f0-ba92-4332-b926-cc6520c3b68a">

**Comment by zrfit** [comment]
您好，感谢反馈！因该显示的修改影响到多个地方，v2.10.8-lts高级设置-元素库-暂时显示所有元素，v2.10.9-lts再优化显示成操作步骤-操作对象-元素对象-对应元素。

**Comment by 13290445582** [comment]
您好，这个改动很多，v2版本目前不敢修改，执行可以正常使用，待规划该问题。
