### ISSUE TITLE
[BUG]系统设置-项目-环境设置 列表页面，搜索框输入关键字执行搜索，无法按输入的关键字过滤结果集！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2703]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.1-2cb10c1e
**Bug 描述**
简要描述您碰到的问题
系统设置-项目-环境设置 列表页面，搜索框输入关键字执行搜索，无法按输入的关键字过滤结果集！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/117904461-fca6dd80-b303-11eb-9a67-ae24a7e38ef6.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
1.9.2已修复
