### ISSUE TITLE
[BUG]【性能测试】使用自定义接口协议创建的接口场景，无法引用到性能测试

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#27032]
### 联系方式

张树彬

### MeterSphere 版本

2.10.7LTS

### 使用外置数据库

否

### 问题描述

开发自定义fix接口协议插件，上传到MS场景中可以正常使用，但保存接口场景后，无法在性能测试中引用该脚本。

### 重现步骤

1. 上传自定义接口协议插件
2. 创建接口场景
3. 打开性能测试-场景配置-引用接口自动化场景
4. 无法成功引用该场景

### 期待的正确结果

期待支持正确引用自定义接口协议的场景

**Comment by 13290445582** [comment]
您好， 未有插件可复现该问题。

**Comment by 13290445582** [comment]
未复现您说的这种情况，若您的场景使用了外部jar，在添加为性能测试时，需要在场景配置-资源文件-上传对应的jar包。若不是因此出现的问题，可以提供复现插件。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
