### ISSUE TITLE
[QUESTION] macos单机部署时，提示如下docker-compose 版本与配置文件不兼容或配置文件存在问题，请重新安装最新版本的 docker-compose 或检查配置文件

### ISSUE THREAD

**Issue by JiangJooh** [metersphere/metersphere#27043]
### 请描述您的问题

hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
/opt/metersphere/metersphere-offline-installer-v2.10.7-lts/install.conf: line 85: getent: command not found
存在已安装的 MeterSphere, 安装目录为 /opt/metersphere, 执行升级流程
-e [MeterSphere Log]: 拷贝安装文件到目标目录 
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
-e [MeterSphere Log]: ======================= 开始安装 ======================= 
-e [MeterSphere Log]: 检测到 Docker 已安装，跳过安装步骤 
-e [MeterSphere Log]: 启动 Docker  
install.sh: line 84: service: command not found
-e [MeterSphere Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
/opt/metersphere/metersphere-offline-installer-v2.10.7-lts/install.conf: line 85: getent: command not found
chmod: /opt/metersphere/conf/my.cnf: No such file or directory
chmod: -R: No such file or directory
chmod: -R: No such file or directory
chmod: -R: No such file or directory
chmod: -R: No such file or directory
chmod: -R: No such file or directory
chmod: /opt/metersphere/conf: No such file or directory
chmod: -R: No such file or directory
chmod: /opt/metersphere/*.yml: No such file or directory

stat /opt/metersphere/docker-compose-base.yml: no such file or directory
-e [MeterSphere Log]: docker-compose 版本与配置文件不兼容或配置文件存在问题，请重新安装最新版本的 docker-compose 或检查配置文件

**Comment by luty2018** [comment]
你好， 当前项目不支持MacOS部署。

**Comment by lucky0719520** [comment]
> 你好， 当前项目不支持MacOS部署。

但是你们放出来了MacOS的部署文档：https://metersphere.io/docs/v2.x/installation/offline_installation_mac/#23-metersphere

**Comment by JiangJooh** [comment]
那只支持window?

**Comment by liuruibin** [comment]
仅支持linux， 安装脚本也是比照bash来写的

**Comment by luty2018** [comment]
> 但是你们放出来了MacOS的部署文档：https://metersphere.io/docs/v2.x/installation/offline_installation_mac/#23-metersphere

非常抱歉，造成了误导， 我们会把这个文档下架。

**Comment by Hwwwww-dev** [comment]
> > 但是你们放出来了MacOS的部署文档：https://metersphere.io/docs/v2.x/installation/offline_installation_mac/#23-metersphere
> 
> 非常抱歉，造成了误导， 我们会把这个文档下架。

我同事M1的 Mac 对着文档捣鼓半天，安不上气死了都要...我试了一下才发现镜像拉取的是 AMD64的，装得上才有鬼了😅
