### ISSUE TITLE
[BUG]服务集成第三方插件成功后，取消服务集成失败。

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27042]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

 服务集成第三方插件成功后，取消服务集成失败。

### 重现步骤

在MS上集成第三方插件，比如飞书，服务集成成功后，点击取消集成，页面提示成功，刷新页面后，集成信息依然存在，后台SQL报错。

![image](https://github.com/metersphere/metersphere/assets/145318182/75f3d523-6d7d-482e-9d87-cd013fef6008)

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/355a88f3-55c2-45c7-aed8-f8a10d2ffb7f)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本修复该问题。

**Comment by fit2cloud-lijiaxin** [comment]
取消集成第三方插件（定制化插件，如ones ，飞书），页面也会报错报错：Internal exception occured, please check logs or contact administrator. 后台SQL报错: ERROR i.m.c.h.RestControllerExceptionHandler 177 - Method[sqlExceptionHandler][You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE project.id IN (SELECT id FROM (SELECT id
                FROM project
    ' at line 3]

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
