### ISSUE TITLE
[BUG]MeterSphere对接OIDC后无法正常忽略MeterSphere登录页面

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#27040]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

MeterSphere配置了对接kecyloak作为OIDC，填写了keycloak的访问地址，当首次访问MeterSphere时，进入的是MeterSphere访问页面，当用户登录完成后，登出MeterSphere后，再次访问MeterSphere时自动跳转到keycloak登录页面，但是无法正常登录
1.MeterSphere配置OIDC
<img width="940" alt="截屏2023-10-12 下午2 10 01" src="https://github.com/metersphere/metersphere/assets/34637801/6ffc07f5-3abd-410b-a730-b026ea5cd168">
2.keycloak配置（版本：21.1.0）
<img width="1346" alt="截屏2023-10-12 下午2 10 37" src="https://github.com/metersphere/metersphere/assets/34637801/8974c9ea-1c6c-432d-bbef-408dbdaf320b">
<img width="1357" alt="截屏2023-10-12 下午2 10 51" src="https://github.com/metersphere/metersphere/assets/34637801/86c2ec83-73f2-4963-9f40-4a7ba13cead0">
<img width="1386" alt="截屏2023-10-12 下午2 11 07" src="https://github.com/metersphere/metersphere/assets/34637801/59eb187c-b2ca-4255-8330-ede04c9019bc">
3.首次访问和登录MeterSphere
<img width="1240" alt="截屏2023-10-12 下午2 11 23" src="https://github.com/metersphere/metersphere/assets/34637801/bcee24ce-375b-4167-8036-cef23fe791cd">
<img width="1374" alt="截屏2023-10-12 下午2 11 57" src="https://github.com/metersphere/metersphere/assets/34637801/b094379c-2807-4afb-83db-1249686a45c1">
<img width="1354" alt="截屏2023-10-12 下午2 12 26" src="https://github.com/metersphere/metersphere/assets/34637801/a86dadf7-6671-4d26-bcb8-364ffffb6e2b">
4.登出MeterSphere，再次访问MeterSphere
<img width="1346" alt="截屏2023-10-12 下午2 13 12" src="https://github.com/metersphere/metersphere/assets/34637801/b1c4d66a-02c1-4031-908f-634fee0139a9">
<img width="1249" alt="截屏2023-10-12 下午2 13 36" src="https://github.com/metersphere/metersphere/assets/34637801/ce890d27-203f-4e3c-869c-b47d4c7e4e86">

### 重现步骤

1.准备MeterSphere和keycloak环境，按前面图片中的配置设置keycloak
2.配置MeterSphere中OIDC信息
3.访问MeterSphere，进行登录和登出以及再次登录操作

### 期待的正确结果

1.访问MeterSphere服务可忽略MeterSphere登录页，进入keycloak登录页面
2.能正常进行登录和登出

**Comment by youliyuan-fit2cloud** [comment]
v2.10.8-lts版本中已修复。
