### ISSUE TITLE
[BUG]接口自动化，复制的场景新增接口后，执行这个场景，新增接口无法拿到场景变量中的值

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27044]
### MeterSphere 版本

v2.10.5

### 使用外置数据库

否

### 问题描述

接口自动化，复制的场景新增接口后，执行这个场景，新增接口无法拿到场景变量中的值

### 重现步骤

1.创建接口自动化场景1，包含自定义请求
![image](https://github.com/metersphere/metersphere/assets/55130444/84500c8e-2158-4167-b9d9-d0fc6c51f6d3)

2.创建接口自动化场景2，场景2 中 场景导入 ，复制场景1

3.复制的场景1中，接口导入，复制case（signin） 到场景1中
![image](https://github.com/metersphere/metersphere/assets/55130444/97d74ee8-190f-4949-a9a2-59802daac993)

4.增加场景变量id 值为1.
![image](https://github.com/metersphere/metersphere/assets/55130444/b0b42124-d9d4-48b3-926b-0ffdf57a0e12)
5.场景设置
![image](https://github.com/metersphere/metersphere/assets/55130444/7e91e7e4-58e8-485d-b1bb-c11e63ff2596)

5.当前场景下调试，复制的case可以取到场景变量的值
![image](https://github.com/metersphere/metersphere/assets/55130444/5e4b824d-71f2-4e5f-852e-cb5877078220)
6.单独运行复制的case，也可以取到场景变量的值
![image](https://github.com/metersphere/metersphere/assets/55130444/dacedcdb-2998-4cac-b959-002b785ec9db)
7.但是单独运行场景，取不到场景变量的值
![image](https://github.com/metersphere/metersphere/assets/55130444/ecb56ac8-20f1-4a1f-a4e2-65a1560de6a0)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。
