### ISSUE TITLE
[BUG]UI用例未在等待时间之后进行截图

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27045]
### MeterSphere 版本

v2.10.X-lts 

### 使用外置数据库

否

### 问题描述

1、截图不管后置里面等待时间、也不会自动等待加载完成

### 重现步骤

1、新建一个UI场景
2、第一步 添加一个打开浏览器登录页面（比如MS的登录）
3、第二步 输入名称
4、第三步 输入密码
5、第四步 点击登陆
6、在第四步的后置中添加等待时间20000ms，截图
7、调试之后查看第四步的步骤结果的截图，看看是不是登陆后的页面
### 期待的正确结果
调试之后查看第四步的步骤结果的截图，是登陆后的页面；即截图需要等待后置里面等待时间结束或自动等待加载完成
_No response_

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.7-lts未复现该问题，建议升级到最新版本尝试。
![image](https://github.com/metersphere/metersphere/assets/99731894/52570c66-239f-4f64-bac5-2bf36b7abe73)
![image](https://github.com/metersphere/metersphere/assets/99731894/54b88e22-0cc6-452f-bef8-ea79360f6e76)

**Comment by sss903065212** [comment]
1、等待时间1000ms时就加载不出来了，
2、这个截图的时间点：是在点击登陆按钮的瞬间进行的截图，还是等待点击登陆按钮触发的事件结束再进行截图
3、根据下面的情况看，如果没有设置等待时间的话，是在点击登陆按钮的瞬间进行的截图
<img width="1122" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/850cb2b6-4426-4873-b8f2-4d8be937750a">
<img width="1140" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/554f17b9-ebf4-40fb-914d-e3f2fc0b50b8">

**Comment by zrfit** [comment]
1、步骤本身的截图是在点击登录按钮的瞬间进行的截图，而后置操作中的截图操作，是在步骤执行完成后，如果设置了等待时间，则在等待时间后进行截图，当前步骤的截图和后置操作的截图的时间点是不一样的。
2、后置截图是否展示登录后的页面，与访问该网页的登录速度和页面的渲染加载都有关系，如果页面登录后加载较慢，则在等待时间后的截图可能就是未显示登录后的页面，可增加等待时间；如果登录后页面跳转渲染的很快，则等待时间较短或者无需等待，后置截图也可能展示登录后的页面。
所以当前情况是正常的。
![image](https://github.com/metersphere/metersphere/assets/99731894/69ee1081-0803-4867-a9fc-d1a03c8da11b)
![image](https://github.com/metersphere/metersphere/assets/99731894/f2b30059-88d8-4a3e-b6a4-a0eb53b9d772)

**Comment by sss903065212** [comment]
那我们的步骤本身的截图还有什么意义

**Comment by sss903065212** [comment]
而且selenuim4.0 已经做了自动等待元素load 完毕的功能了，MeterSphere没有做方面的集成吗

**Comment by sss903065212** [comment]
@zrfit

**Comment by Hyyfit** [comment]
目前没有。
4.0的智能加载，还需要进一步调研能否支持。
