### ISSUE TITLE
[BUG]【接口测试】接口定义和接口自动化，导入jmeter格式的说明提示未更新

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#27049]
### 联系方式

张树彬

### MeterSphere 版本

2.10.7LTS

### 使用外置数据库

否

### 问题描述

接口定义和接口自动化，导入jmeter格式的说明提示未更新，目前2.3版本后已经支持到jmeter5.5版本，提示说明仍显示5.4版本

### 重现步骤

1. 接口测试-接口定义-导入-jmeter
2. 接口测试-接口自动化-导入-jmeter
3. 查看第一行的说明提示，未更新

### 期待的正确结果

更新支持的jmeter版本信息

### 附加信息

![1697108770435](https://github.com/metersphere/metersphere/assets/77324661/5a52788d-32b9-4036-b62a-69ea38c61942)
![1697108770447](https://github.com/metersphere/metersphere/assets/77324661/40d42467-e3b5-4224-9293-30b26fe5da20)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts优化。
