### ISSUE TITLE
[BUG]前置脚本报错Tag mismatch【已解决附带办法】

### ISSUE THREAD

**Issue by Mr1X** [metersphere/metersphere#27041]
### MeterSphere 版本

v2.10.6 及 v2.10.7-lts-b1

### 使用外置数据库

否

### 问题描述

# 前置脚本调用一个https接口报错，返回 `Tag mismatch`报错

脚本进行一个https的post请求，json数据格式

```
import httplib,urllib2,json

headers = {'Content-Type':'application/json'} 

params = {
    "Version": "1.0.0",
    "Type": "service"
}
# 替换真实地址
req = urllib2.Request('https://test.com/api//', json.dumps(params), headers)
rsp = urllib2.urlopen(req)
log.info(rsp.read())
```

## 报错信息
```
2023-10-12 11:17:28 ERROR c1143be9 1-1 Problem in JSR223 script, JSR223PreProcessor
urllib2.URLError: <urlopen error [Errno 1] Tag mismatch! (javax.crypto.AEADBadTagException: Tag mismatch!)> in <script> at line number 20
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

## 排查步骤

确认了以下3种方式可以成功
1. 直接用python代码
2. 本地jmeter执行
3. 在容器内使用curl请求成功

**上述步骤可以确认代码是没有问题的，应该是环境导致的**

尝试metersphere升级，从v2.10.6升级到v2.10.7， 还是执行失败

### 进入容器内排查

在容器内直接命令行调用jython, 发现还是报错 `Tag mismatch` ,但是报错信息更全，可以看出是jar包导致的报错

### 调试成功

因为本地是可以执行成功的，所以尝试用本地的`jython-standalone-2.7.3.jar` 包替换容器内的测试
经过验证，执行成功

## 解决办法

metersphere的 `v2.10.7`版本里面的`jython-standalone.jar`的版本是 `2.7.0`， 需要替换为 `2.7.3`

- 目前暂时的解决方式是替换后重新封装了镜像
- 一键安装需要等官方升级最新的镜像

### 重现步骤

用上述脱敏后的代码必现, https , post, json

### 期待的正确结果

执行成功

### 附加信息

![截图_16968186122060](https://github.com/metersphere/metersphere/assets/34152252/5bca3bfd-a5b5-4fbc-8d3f-d23d9ac8633e)

**Comment by 13290445582** [comment]
您好，可以提供下您在jmeter中运行该脚本的jmx文件吗？

**Comment by Mr1X** [comment]
> 您好，可以提供下您在jmeter中运行该脚本的jmx文件吗？

不熟jmx， 我windows本地安装的jmeter客户端，用的jython

![image](https://github.com/metersphere/metersphere/assets/34152252/b6cccd76-9780-428e-8a6f-1ce6ee30d295)

**Comment by 13290445582** [comment]
您好，将metersphere中带该脚本的场景导出也可以。

**Comment by Mr1X** [comment]
> 您好，将metersphere中带该脚本的场景导出也可以。

怎么导出，刚部署没多久，用的还不熟，我在你们交流群67群，可以群里直接找我

**Comment by 13290445582** [comment]
![image](https://github.com/metersphere/metersphere/assets/128017892/58f92e89-c2d8-4125-9f8f-d14a1528a12d)
添加我的微信吧。

**Comment by 13290445582** [comment]
感谢您提供的解决办法，下载jython 2.7.3 jar包替换镜像中的2.7.0，替换位置api-test 镜像中 /opt/jmeter/lib/ext/jython-standalone.jar；如果使用资源池需要再替换node 镜像中相同位置的jar。

**Comment by xchnshi** [comment]
@13290445582 hello，我看了一下最新的v2.10版本中，好像仍然是2.7.0的包，我们最近也遇到了类似问题。如何确认最新镜像中已经默认使用了jython 2.7.3 jar？谢谢

查看的是jython-standalone.jar中的文件：
![Image](https://github.com/user-attachments/assets/8f498fb8-5943-4e2d-a9bb-d2a179109dc0)

**Comment by 13290445582** [comment]
> [@13290445582](https://github.com/13290445582) hello，我看了一下最新的v2.10版本中，好像仍然是2.7.0的包，我们最近也遇到了类似问题。如何确认最新镜像中已经默认使用了jython 2.7.3 jar？谢谢
> 
> 查看的是jython-standalone.jar中的文件： ![Image](https://github.com/user-attachments/assets/8f498fb8-5943-4e2d-a9bb-d2a179109dc0)

您好，最新镜像中我们并未默认使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的2.7.0，替换位置api-test 镜像中 /opt/jmeter/lib/ext/jython-standalone.jar；如果使用资源池需要再替换node 镜像中相同位置的jar。
下载地址：https://www.jython.org/

**Comment by xchnshi** [comment]
> 使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的

替换后需要重启服务吗？刚刚直接替换了，不是不行。如果重启的话文件是不是又回到原来镜像中的文件了？

**Comment by 13290445582** [comment]
> > 使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的
> 
> 替换后需要重启服务吗？刚刚直接替换了，不是不行。如果重启的话文件是不是又回到原来镜像中的文件了？

可以挂载宿主机目录，通过挂载宿主机目录到容器中，替换宿主机上的文件后重启容器即可生效，可以参考docker挂载的办法。或者您也可以基于我们的镜像自己重新封装一个镜像。

**Comment by xchnshi** [comment]
> > > 使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的
> > 
> > 
> > 替换后需要重启服务吗？刚刚直接替换了，不是不行。如果重启的话文件是不是又回到原来镜像中的文件了？
> 
> 可以挂载宿主机目录，通过挂载宿主机目录到容器中，替换宿主机上的文件后重启容器即可生效，可以参考docker挂载的办法。或者您也可以基于我们的镜像自己重新封装一个镜像。

好的，谢谢；请问一下release版本没有将这个版本更新到镜像中，是出于什么考虑？

**Comment by 13290445582** [comment]
> > > > 使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的
> > > 
> > > 
> > > 替换后需要重启服务吗？刚刚直接替换了，不是不行。如果重启的话文件是不是又回到原来镜像中的文件了？
> > 
> > 
> > 可以挂载宿主机目录，通过挂载宿主机目录到容器中，替换宿主机上的文件后重启容器即可生效，可以参考docker挂载的办法。或者您也可以基于我们的镜像自己重新封装一个镜像。
> 
> 好的，谢谢；请问一下release版本没有将这个版本更新到镜像中，是出于什么考虑？

jython-standalone-2.7.3.jar 目前有性能问题，不建议使用，所以未默认使用。
https://github.com/jython/jython/issues/224
https://github.com/apache/jmeter/issues/6035

**Comment by xchnshi** [comment]
> > > > > 使用jython 2.7.3jar，如果不考率性能问题你可以下载jython 2.7.3 jar包替换镜像中的
> > > > 
> > > > 
> > > > 替换后需要重启服务吗？刚刚直接替换了，不是不行。如果重启的话文件是不是又回到原来镜像中的文件了？
> > > 
> > > 
> > > 可以挂载宿主机目录，通过挂载宿主机目录到容器中，替换宿主机上的文件后重启容器即可生效，可以参考docker挂载的办法。或者您也可以基于我们的镜像自己重新封装一个镜像。
> > 
> > 
> > 好的，谢谢；请问一下release版本没有将这个版本更新到镜像中，是出于什么考虑？
> 
> jython-standalone-2.7.3.jar 目前有性能问题，不建议使用，所以未默认使用。 [jython/jython#224](https://github.com/jython/jython/issues/224) [apache/jmeter#6035](https://github.com/apache/jmeter/issues/6035)

好的，谢谢
