### ISSUE TITLE
[BUG]UI自动化测试ForEach循环下，IF判断条件错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27057]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI自动化场景下，foreach步骤下的if判断条件，有四个循环的判断是为真，一个为假，实际最终的结果是全部为真。

### 重现步骤

1、创建一个自动化场景
2、场景下创建一个foreach循环，利用环境变量数组进行循环
3、在循环下创建if/else子步骤
4、观察判断结果

### 附加信息

判断条件：
<img width="1442" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/7155dccf-0977-4ffc-b2de-6f583bd03be0">

判断结果：
<img width="1469" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/22a8d973-a51f-4239-8683-33e3e53db93b">

实际的执行结果：（全部走到if里面了，本应该有个循环在else里面）
<img width="1447" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/1847c5d0-4910-4c14-9d2c-e02e70f1e207">

如果复现不了，请联系我提供复现场景。

**Comment by zrfit** [comment]
您好，感谢反馈！提供场景经排查是脚本错误，引用变量不需要加引号，去掉引号则循环正常。
