### ISSUE TITLE
STEP编辑模式的用例在导出时，步骤描述和预期结果按顺序出现在同一个单元格中，不是现在这种一个步骤占用一个单元格，非常不方便导出用例在本地修改

### ISSUE THREAD

**Issue by qq876633655** [metersphere/metersphere#27052]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 请描述您的需求或者改进建议

STEP编辑模式的用例在导出时，步骤描述和预期结果按顺序出现在同一个单元格中，不是现在这种一个步骤占用一个单元格，非常不方便导出用例在本地修改。如实现方案中的截图，上面的用例格式导致我修改用例非常不方便，希望导出用例做成下面那一类

### 请描述你建议的实现方案

![image](https://github.com/metersphere/metersphere/assets/52779051/97b6116c-b996-444a-83e4-a0ce30b127ba)

**Comment by luty2018** [comment]
嗯嗯， 我们已经意识到这个问题了。v3也会改掉这个设计。

**Comment by luty2018** [comment]
v3.2已修复，可以升级使用。
