### ISSUE TITLE
[BUG]  将xmind 脑图中的用例描述复制，粘贴到ms脑图。脑图上面写的用例换行，粘贴到ms脑图的展示格式错误

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27063]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

前提条件：脑图上面写的用例有换行，
问题：将xmind 脑图中的用例描述复制，粘贴到ms脑图。粘贴到ms脑图的展示格式错误和xmind上面展示的不一样

### 重现步骤

前提条件：脑图上面写的用例有换行，
问题：将xmind 脑图中的用例描述复制，粘贴到ms脑图。粘贴到ms脑图的展示格式错误和xmind上面展示的不一样

有录屏可以单独找我拿下上传不了

### 期待的正确结果

复制所见即所得

**Comment by xhy12** [comment]
![用例步骤 预期 有换行](https://github.com/metersphere/metersphere/assets/43202800/757751e6-047f-4a6e-b7fa-67d4700d9c96)

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/e3d433df-2ba4-49fd-8751-a4e35655ad40)
xmindl 里面有换行

**Comment by 13290445582** [comment]
您好，这个问题是我们目前使用的脑图组件的默认行为，如果粘贴的文本中带有回车，就会默认创建多个子节点，目前无法修改；想满足你这个需求，可以先添加一个子节点，然后双击子节点进入编辑状态再粘贴文本即可
