### ISSUE TITLE
[BUG]接口测试-接口自动化，批量选择场景接口案例进行批量执行，运行配置选择‘串行’、‘集合报告’确认执行后，报告一直出于‘running’状态，测试阻断~

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2706]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.1-2cb10c1e
**Bug 描述**
简要描述您碰到的问题
接口测试-接口自动化，批量选择场景接口案例进行批量执行，运行配置选择‘串行’、‘集合报告’确认执行后，报告一直出于‘running’状态，测试阻断~
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/117905318-96bb5580-b305-11eb-8d14-f52eb2fdd85d.png)
![image](https://user-images.githubusercontent.com/54024064/117905332-9a4edc80-b305-11eb-81da-1b59e6f8089d.png)

**Comment by xulinde** [comment]
已知问题，下个版本会修复

**Comment by fit2-zhao** [comment]
@feiyu0316  这个问题在1.9.1 中已经修复了 请检查一下  api_scenario_report  表中的 scenario_name  长度是否为 3000 ；如果不是 执行一下这个sql ALTER TABLE api_scenario_report MODIFY COLUMN scenario_name VARCHAR(3000);

**Comment by xulinde** [comment]
1.9.2已修复
