### ISSUE TITLE
[FEATURE] 接口测试性能问题

### ISSUE THREAD

**Issue by Mr1X** [metersphere/metersphere#27079]
### MeterSphere 版本

v2.10.7

## 接口测试性能问题，必现

后端接口响应时间51ms, 但是ms一直转圈圈，明显卡顿一秒多，控制台显示websocket耗时了1.77s

![image](https://github.com/metersphere/metersphere/assets/34152252/0865d1d4-f456-4d6d-9724-c1f34dd473b5)

![image](https://github.com/metersphere/metersphere/assets/34152252/d6b1d10c-eb83-43c9-a447-f5edcfd808f0)

![image](https://github.com/metersphere/metersphere/assets/34152252/aa8478b0-ebc5-4d27-aa45-4b9606b9e7bb)

### 请描述你建议的实现方案

大佬们看下能找到耗时的原因优化一下不

**Comment by liuruibin** [comment]
socket 时间表示我们系统内消息处理时间，和被测接口的响应时间没有必然联系

**Comment by Mr1X** [comment]
> socket 时间表示我们系统内消息处理时间，和被测接口的响应时间没有必然联系

我的意思socket耗时太长了，这里肯定有框架的性能问题，，需要看下能不能优化
