### ISSUE TITLE
[BUG]同一个资源池多个node节点，有node节点停止后，测试计划执行还是会分发任务到停止的node

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27075]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

1、同一个资源池多个node节点
2、该资源池的node都在同一台机器上
3、在服务器上只保留一个node，资源池不动
4、此时测试计划和场景调试 均会出现失败的情况

### 重现步骤

1、在服务器 原有nodeA的情况下，另起一个nodeB
2、将改nodeB加入nodeA所在的资源池 poolA
3、在服务器上stop掉nodeB
4、执行测试计划或场景调试的项目选择 poolA
5、查看失败情况，或者查看后台日志，可以看到有些任务还是会发到nodeB

### 期待的正确结果

在发送任务时，添加检测node节点是否可用
杜绝stop的node还被发送任务，导致调试失败

**Comment by fit2-zhao** [comment]
感谢反馈，现有的分配策略是这样的，每一批任务开始执行时会去计算并分配好执行策略，如果在每个小任务都去计算一次资源策略，任务较多时效率并不好，这个会在v3去重构执行策略，当前大版本不会再优化处理了。

**Comment by sss903065212** [comment]
了解了
