### ISSUE TITLE
[BUG]【接口测试】后置操作-提取参数，正则提取数据不对

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#27073]
### MeterSphere 版本

v2.10.7

### 使用外置数据库

否

### 问题描述

从2.10.6版本升级到2.10.7版本，正则提取数据不对，2.10.6版本是正常的

### 重现步骤

1.接口中加入后置操作-提取参数
2. 使用正则提取参数
3. 执行接口

### 期待的正确结果

新版本能按正确的正则表达式提取数据

### 附加信息

<img width="567" alt="a7cd3574bd18e3987df14cb89da5ca9" src="https://github.com/metersphere/metersphere/assets/45531073/9b5ddad7-150e-41ea-94a5-7695f4c740f9">

<img width="807" alt="1f5fd9c2e71b7e2b08063eb9864dab8" src="https://github.com/metersphere/metersphere/assets/45531073/04d1d538-a990-4064-b330-112482eaa835">
<img width="737" alt="3e0e7825aacbe28e082f07c973058c2" src="https://github.com/metersphere/metersphere/assets/45531073/3a34514d-26c3-4c89-9016-5bb878254e50">

**Comment by 13290445582** [comment]
您好，提供下您的响应体文件。

**Comment by fit2-zhao** [comment]
这个和之前 https://github.com/metersphere/metersphere/issues/26797 这个修复建议有逻辑冲突，会在下个版本进行优化处理，支持用户自己选择正则提取模版，将会兼容您这种情况。

**Comment by Larson13** [comment]
> 您好，提供下您的响应体文件。

[Metersphere_Scenario_默认项目 (1).json](https://github.com/metersphere/metersphere/files/12923476/Metersphere_Scenario_.1.json)

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
