### ISSUE TITLE
[FEATURE]测试集合-接口测试用例-场景用例 列表页，该页面无法手动排序场景案例，批量执行无法按想要的业务场景顺序执行案例，建议增加自定义场景案例批量执行按顺序执行的功能！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2707]
**请描述您的需求或者改进建议.**

测试集合-接口测试用例-场景用例 列表页，该页面无法手动排序场景案例，批量执行无法按想要的业务场景顺序执行案例，建议增加自定义场景案例批量执行按顺序执行的功能！

**请描述你建议的实现方案**
建议可增加自定义场景案例id的功能，场景执行顺序默认按id排序顺序执行

**Comment by xulinde** [comment]
这个和导入的顺序是一致的，您可以在导入时按顺序导
