### ISSUE TITLE
[BUG]指令被复制或者引用到场景时，选择环境后，对应的环境变量没有替换指令中的入参

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27084]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

指令复制或者引用到场景时，参数未被环境的参数替换？那调试指令的参数有没有环境可以选择，只能写参数？感觉这里逻辑冲突了

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/40912189/af57c720-6c96-4135-aea7-233b96242ca8)
比如上图的参数

**Comment by zrfit** [comment]
您好，感谢反馈！场景复制、引用指令 ，选择场景环境-执行-指令如有入参，指令下的步骤会优先引用入参，没有入参则走场景变量，没有场景变量，则走环境变量，指令步骤变量的引用顺序逻辑如此。

**Comment by sss903065212** [comment]
@zrfit 
第一：指令没有环境可选，如何调试
第二：指令调试的时候需要变量，只能通过入参来调试
第三：指令调试完毕，我还要去掉入参 才能被其他的场景使用了？
第四：你回答的这逻辑是现在存在的逻辑，我想知道的不是这个，而是这个逻辑适不适用业务的使用
