### ISSUE TITLE
[BUG] 【安全问题】登录日志无操作人

### ISSUE THREAD

**Issue by Mr1X** [metersphere/metersphere#27080]
### MeterSphere 版本

v2.10.7

### 使用外置数据库

否

### 【安全问题】

操作日志里面发现部分登录日志没有操作人

![image](https://github.com/metersphere/metersphere/assets/34152252/6a764faf-87eb-4ab2-9717-334e0dab05b0)

![image](https://github.com/metersphere/metersphere/assets/34152252/cdc28dad-ef19-4efd-95f1-75a2ddff1d63)

### 重现步骤

不确定怎么出现的，但是有很多这样的记录

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。
