### ISSUE TITLE
Selenium IDE 录制UI脚本，导入新版本的MeterSphere中解析网页链接失败

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27088]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

用Selenium IDE 录制UI脚本，保存并导入到MeterSphere中，编辑打开发现解析网页链接失败。

### 重现步骤

1. 用Selenium IDE 录制UI脚本，保存；
2. 导入MeterSphere中，编辑打开发现解析网页链接失败

### 期待的正确结果

Selenium IDE 录制UI脚本，导入新版本的MeterSphere中能正确解析网页链接

### 相关日志输出

```shell
无
```

### 附加信息

同一个脚本v2.10.7 版本解析失败：
<img width="956" alt="1697445347401" src="https://github.com/metersphere/metersphere/assets/50016789/10841fc6-2bd0-4694-8d18-0db2537b9228">
v2.10.5 版本解析成功
<img width="960" alt="7d936db438b619fa4ac59bc9f42e174" src="https://github.com/metersphere/metersphere/assets/50016789/d89fe040-0a16-401e-971b-2c38def34c2e">

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。
