### ISSUE TITLE
[BUG]环境变量 不同类型 同名无法添加问题

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27083]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

相同名称不同类型的变量无法同时存在

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/40912189/a35a7f50-250b-4a2a-9b80-f247df40cae0)

**Comment by zrfit** [comment]
您好，感谢反馈！不同应用场景，目前变量名称不能重复。v3将不区分应用场景，所以变量名仍不能重复，故v2暂时保持现状。

**Comment by sss903065212** [comment]
可以理解
