### ISSUE TITLE
[BUG]MeterSphere使用jmeter格式导出接口自动化场景，场景步骤中的后置脚本无法兼容jmeter

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#27081]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

MeterSphere的接口场景采用jmeter格式导出，导入jmeter（5.4）版本中，执行时报后置脚本（脚本类型groovy）无法兼容。
场景在MeterSphere中执行：
<img width="1032" alt="截屏2023-10-16 下午3 03 41" src="https://github.com/metersphere/metersphere/assets/34637801/e6015b60-7ebb-4f45-aebf-c049d54d55e1">
<img width="1055" alt="截屏2023-10-16 下午3 04 12" src="https://github.com/metersphere/metersphere/assets/34637801/c9511cf8-f867-48d0-bd0c-04ef81291d83">
场景导出后在jmeter中执行
<img width="1406" alt="截屏2023-10-16 下午3 04 58" src="https://github.com/metersphere/metersphere/assets/34637801/7d6756db-43e3-42d6-bdad-1d0dc4487a00">
需要在jmeter中修改为java的语言才能正常执行
<img width="1010" alt="截屏2023-10-16 下午3 06 19" src="https://github.com/metersphere/metersphere/assets/34637801/e706961f-3492-48fe-a0dc-9c95c24a0513">

### 重现步骤

1.本地准备一个jmeter（5.4或者其它版本）
2.准备一个场景，场景步骤中带一个后置脚本（groovy类型）
3.使用jmeter格式导出场景放入本地jmeter中执行。
4.查看jmeter的日志。

### 期待的正确结果

可以正确的在jmeter中执行

**Comment by fit2-zhao** [comment]
从错误信息来看应该是 import org.json 这个包产生了错误，您可以在文件管理中把 org json 对应的jar上传到平台，再执行看看效果。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
