### ISSUE TITLE
[BUG] UI用例 国际化问题

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27099]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

国际化处理不干净

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/40912189/91eb7f06-52c8-4471-b4b3-2bb356078222)

### 期待的正确结果

英文就要有英文展示的样子

### 附加信息

多测试测试国际化的问题

**Comment by youliyuan-fit2cloud** [comment]
你好，国际化问题已知，解决时间待定。




ps：为什么每次看你提问题都有点不舒服，请尽量考虑下所有开发测试同学的感受！我们一直在努力改进中。。。

**Comment by sss903065212** [comment]
很多提的建议不被采纳就算了，起码不要随便关掉这种issue吧，有很多还没有来得及回复你们的方案或者解答，单子就被毙了，然后我在colse的单子里再回复的时候也没有人关注了

**Comment by sss903065212** [comment]
辛辛苦苦的收集来的问题，按照要求写了复现步骤，然后给了一个解释就给关闭了，我们想要的其实很简单，不是一定要立即实现，而是理解这种辛苦，能给个排期，或者给个方向，我们也好心里有个底气去应对

**Comment by youliyuan-fit2cloud** [comment]
1.我们没有随便就关掉issue，都有解释说明回复了。可能大家意见不一致吧，近阶段不会有其他方案，留着没什么意义。
2.close的issue 我们关注的很少，因为已经处理过的问题，不需要关注。如果你觉得有充分理由，这种情况可以单独找我们沟通。
3.我们排期的，近期能解决的都会说明，既然解释说明过，表示我们经过沟通，考虑各种因素和优先级，才给出的回复。
理解你的辛苦，也请理解我们的难处。互相理解，我们在持续改进中。

**Comment by liqiang-fit2cloud** [comment]
现在没人关闭啊，上面说了是已知问题，解决时间待定。现在待排期的太多了，不可能每个需求每个问题都给明确排期，如果要提优先级的话请在你们团队里沟通然后通过接口人反馈。
GitHub上的Issue包括需求和缺陷，确定要做的事情都已经记录到TAPD，如果一段时间内没有明确计划的就先会关闭Issue。

**Comment by sss903065212** [comment]
新增国际化问题：
1、接口自动化：
<img width="936" alt="AMTEST" src="https://github.com/metersphere/metersphere/assets/40912189/f2e41742-7c55-4d07-a414-d16cd2cfc4e4">
2、涉及定时任务配置通知的地方
<img width="1214" alt="Pasted Graphic 2" src="https://github.com/metersphere/metersphere/assets/40912189/41505696-1cf8-44b3-9918-029225205607">

3、UI批量操作步骤的地方
<img width="542" alt="Sphere" src="https://github.com/metersphere/metersphere/assets/40912189/6793be74-7fd9-44ff-a9be-ef92662a0d38">
4、UI场景导入的地方：
<img width="899" alt="Scenario import" src="https://github.com/metersphere/metersphere/assets/40912189/8d0259e7-1dd7-4fe2-b134-9cfb3836a118">
<img width="234" alt="Instruction Steps" src="https://github.com/metersphere/metersphere/assets/40912189/85df7d1b-bb62-430f-badb-7c48f0d8648e">

**Comment by 13290445582** [comment]
您好，已补充，感谢反馈。
