### ISSUE TITLE
[BUG]性能测试 测试概览的vu和请求统计的samples数字不一致

### ISSUE THREAD

**Issue by pythonmwj** [metersphere/metersphere#2709]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？v1.9.1

**Bug 描述**
简要描述您碰到的问题
 性能测试 测试概览的vu和请求统计的samples数字不一致

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
性能测试 
> 测试概览的vu和请求统计的samples数字一致

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33612031/117907972-3dcccc80-b2c7-11eb-986e-7df1a0fbe237.png)
![image](https://user-images.githubusercontent.com/33612031/117907996-458c7100-b2c7-11eb-8688-864e81e805b5.png)

**Comment by zyyfit** [comment]
您好，请问压力测试配置是怎么配置的呢？多长时间内增加多少个并发用户数？
