### ISSUE TITLE
[FEATURE]可不可以提供mock的功能

### ISSUE THREAD

**Issue by BoswellBao** [metersphere/metersphere#271]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，能否再详细描述下你期望的 mock 功能时怎样的，是对请求内容的 mock，还是接口响应的 mock

**Comment by BoswellBao** [comment]
响应的mock，类似于yapi的那种，可以自己定义一个接口，然后制定自己期望该接口返回的数据。
其实yapi可以用， 就是想如果有一个平台实现这几类功能，就省去了管理其他平台的精力了
