### ISSUE TITLE
[BUG]UI自动化场景采用快捷键 ctrl+s 保存时信息出现错乱

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27104]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI自动化场景编辑后，采用快捷键 ctrl+s 进行保存，提示保存成功但是实际信息出现错乱。

### 重现步骤

参考附件视频
1、多按 “ctrl+s”几次之后，场景名称就变成和之前打开的场景名称一样了，参考视频1
2、前置加的等待时间也会被重置为0，参考视频2

### 附加信息

视频演示如下：
视频1
https://github.com/metersphere/metersphere/assets/32027713/9445453e-0bd1-4544-97ee-ec59dca1257b

错误如下：
<img width="1476" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/fd33fd79-ab1f-4be7-9e55-4b0b8edfd25b">

视频2

https://github.com/metersphere/metersphere/assets/32027713/45aedf5f-66ae-4aae-a538-43d39946c030

前置的等待时间第一次从100变为0，第二次修改为200000 ctrl+s之后变为2000

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。
