### ISSUE TITLE
[BUG]后置设置截图 发生元素定位失败时 步骤结果中只有文字没有截图

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27103]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

后置设置截图 发生元素定位失败时 步骤结果中只有文字没有截图
![image](https://github.com/metersphere/metersphere/assets/40912189/99491f2e-716e-4631-b925-db4e14c47b19)

### 重现步骤

1、新建一个UI用例
2、第一个步骤打开浏览器 url 为随便的一个
3、添加第二个步骤为等待元素
4、如图
<img width="1125" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/c7617466-4c1b-42c0-8059-74a8e4bf883e">
5、其他设置里设置 如图
<img width="432" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/f7ac4dc6-fdca-489b-bcbb-cc5d4b367242">
6、后置设置如图
<img width="954" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/b951112b-6aff-4a28-94b5-9a5e21caa7c4">
7、后端调试结束，看第二步骤（等待元素）的步骤结果

### 期待的正确结果

1、报错给截图，设置了两个截图，结果一个截图也没有展示
2、截图的时候不管报什么错都应该有这个截图
3、希望改正这个判断逻辑

**Comment by Hyyfit** [comment]
当步骤失败，后置操作和断言都不会执行，所以后置里的截图不会执行。
如果要截图，可在截图配置里配置“出现异常截图”

**Comment by sss903065212** [comment]
1、“出现异常截图” 实验过后可以，谢谢
2、后置不会执行可以理解，为什么“当前步骤截图”不会截图呢？

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.7-lts当前步骤截图正常，请升级到最新版本尝试。
<img width="1389" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/cb17b45f-ef4d-45ef-bf80-a82de96a446b">
<img width="1384" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/bb61720a-6880-4c7a-8438-6342cdf5eaa7">

**Comment by sss903065212** [comment]
.7 修复了

**Comment by sss903065212** [comment]
了解了
