### ISSUE TITLE
性能测试-报告-显示全部，显示问题

### ISSUE THREAD

**Issue by kuma-z** [metersphere/metersphere#2710]
**请描述您的需求或者改进建议.**

该页面中，状态一栏，建议添加“break”状态，即为在性能测试过程中手动停止的测试场景。以便后期查询、清理。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
手动停止是会保留测试报告的，便于查看
![image](https://user-images.githubusercontent.com/64065190/117955371-8f6a6b00-b34a-11eb-82c8-bcfa7f82c140.png)
