### ISSUE TITLE
[BUG] UI 输入操作上传文件没有本地上传

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27101]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

涉及文件上传的地方怎么也要有本地上传吧，不然怎么调试文档的数据对不对，改完再回来关联？
![image](https://github.com/metersphere/metersphere/assets/40912189/82ab4ae4-2916-47c2-ba3f-f058b6e109c6)

### 重现步骤

1、新建一个UI场景
2、添加一个步骤：输入操作
3、选择步骤类型为上传文件
4、点击添加文件的小框
5、发现没有本地上传的选项

### 期待的正确结果

涉及文件上传的地方怎么也要有本地上传才是正常的产品操作

**Comment by Hyyfit** [comment]
感谢反馈，已转需求

**Comment by sss903065212** [comment]
好的谢谢 @Hyyfit
