### ISSUE TITLE
[BUG] UI测试-窗口最大化失效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27116]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

<img width="752" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/eb97e6cb-49b3-4d53-b93f-94bf8f4cb710">
<img width="1126" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/96d4bd31-a379-48b8-8b00-070e41b40754">
窗口最大化的默认像素大小不对，导致截图显示的内容样式发生改变

### 重现步骤

1、新建UI一个场景
2、第一步打开浏览（建议使用MS的页面）（该步骤设置截图）
3、第二步设置窗口大小-最大化（该步骤设置截图）
4、调试后查看2和3步中的截图的浏览器样式
5、修改后台的参数重启服务后，继续上面的4，查看截图未发生变化
<img width="687" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/10841478-a482-45a7-8a51-88b57b2977a3">

### 期待的正确结果

窗口大小-最大化的像素能否和yml中设置参数保持一致

**Comment by liuruibin** [comment]
<img width="1942" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/f7d38164-71b1-44e4-a60f-d3037e974e3a">

<img width="1196" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/9f48809a-00f4-4528-9ea7-af1e363f3eb4">

**Comment by sss903065212** [comment]
已验证，去掉性能模式即可
