### ISSUE TITLE
[BUG]  功能列表分别写了 文本描述、步骤描述写用例, 导出excel为文本描述 导出脑图为步骤描述，导入更新的内容不一样

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27112]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

1、目前发现ms列表分别写了 文本描述、步骤描述写用例，保存用例时停留页面是文本描述
2、导出用例excel是文本描述的内容，导出脑图是步骤描述的内容。
这样将用例导出后修改再导入更新，excel方式和脑图方式更新的用例不一样，

### 重现步骤

1、目前发现ms列表分别写了 文本描述、步骤描述写用例，保存用例时停留页面是文本描述
2、导出用例excel是文本描述的内容，导出脑图是步骤描述的内容。
这样将用例导出后修改再导入更新，excel方式和脑图方式更新的用例不一样，

### 期待的正确结果

![image](https://github.com/metersphere/metersphere/assets/43202800/4a7afd66-47e5-4e23-acab-2f812cdd93ba)
 期望：步骤是文本描述格式 两种类型的格式可以互相切换。

有一点不太明白为什么要保留两份用例描述？

**Comment by xhy12** [comment]
![ms上面将用例描述改成文本描述后，导出脑图](https://github.com/metersphere/metersphere/assets/43202800/5cc693b3-35e4-4386-a46d-298dbe2cf285)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.8版本修复这个问题。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
