### ISSUE TITLE
[BUG]【测试跟踪-功能用例】批量编辑标签时，输入过长标签后点击确定，页面会提示错误信息，但同时也弹出保存成功的提示，实际标签并没有添加上去。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27125]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-功能用例】批量编辑标签时，输入过长标签后点击确定，页面会提示错误信息，但同时也弹出保存成功的提示，实际标签并没有添加上去。

### 重现步骤

【测试跟踪-功能用例】批量编辑标签时，输入过长标签后点击确定，页面会提示错误信息，但同时也弹出保存成功的提示，实际标签并没有添加上去。
![image](https://github.com/metersphere/metersphere/assets/104960608/aa4413bf-1cbf-4d07-9222-788b49dc818e)

**Comment by luty2018** [comment]
统一改成超过15个字符无法保存成功

**Comment by 13290445582** [comment]
您好，我们会在2.10.8版本优化这个问题，将标签长度限制到不能超过50个字符。

**Comment by 13290445582** [comment]
您好，关于过长标签保存，弹出保存成功提示和超长提示问题，是因为编辑的时候超长，就提示了错误信息，保存用例照样保存，超长的标签不保存，但是其他在字符范围内的标签依旧可以保存成功，只是不保存超长的字符。

**Comment by 2lipan** [comment]
一边提示限制字符，一边提示保存成功。进去看用例详情，标签并没有添加上，那这保存成功到底保存成功的是啥，会给人误解。
![db0a9be5e465b3b3409852a91bfbd07](https://github.com/metersphere/metersphere/assets/104960608/262a9007-ff02-4199-9b5d-fde85931b6f3)
