### ISSUE TITLE
[BUG]【测试跟踪-功能用例】批量编辑标签时，当标签长度输入过长时会提示错误信息，但是单个用例编辑标签时可以正常保存。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27123]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-功能用例】批量编辑标签时，当标签长度输入过长时会提示错误信息，但是单个用例编辑标签时可以正常保存。

### 重现步骤

【测试跟踪-功能用例】批量编辑标签时，当标签长度输入过长时会提示错误信息，但是单个用例编辑标签时，输入过多字符是可以正常保存，希望批量编辑标签与单个用例编辑标签保持一致。
批量编辑会提示
![image](https://github.com/metersphere/metersphere/assets/104960608/7825daa7-e61a-4125-810a-eec28b31a11b)
单个用例编辑长度很大的标签是可以
![image](https://github.com/metersphere/metersphere/assets/104960608/0d8dc20e-3eb8-439f-ae27-e431df9ad41a)

**Comment by luty2018** [comment]
这里只是提示，并没有强制限制保存，场景上确实也不需要强制限制。

**Comment by luty2018** [comment]
这个页面会改一下， 超过15个字符无法保存

**Comment by 13290445582** [comment]
您好，我们会在2.10.8版本优化这个问题，将标签长度限制到不能超过50个字符。

**Comment by 13290445582** [comment]
您好，最新版本v2.10.8已发布，请升级验证。
