### ISSUE TITLE
[BUG]【测试跟踪-功能用例】批量编辑标签时，当输入稍微长的标签时，都挤在左边，没有显示在输入框右边区域。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27124]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-功能用例】批量编辑标签时，当输入稍微长的标签时，都挤在左边，没有显示在输入框右边区域。

### 重现步骤

【测试跟踪-功能用例】批量编辑标签时，当输入稍微长的标签时，都挤在左边，没有显示在输入框右边区域。
![image](https://github.com/metersphere/metersphere/assets/104960608/9c86e9c9-2c97-421d-8513-fbd9358aebeb)

**Comment by luty2018** [comment]
<img width="1262" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/e2448c61-734f-4916-b090-55c071e450a2">
目前是固定了标签输入框的宽度了，这样可以保证多个标签一行展示的效果，如果将宽度改成100%后就是一行一个。
影响不大，可以v3再统一优化。如果用户确实都是超长标签，那可以排期优化。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
