### ISSUE TITLE
[BUG]接口定义页面id重复，导致ID不唯一，筛选接口不准确

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27120]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

接口定义页面id重复，导致ID不唯一，筛选接口不准确
![image](https://github.com/metersphere/metersphere/assets/103925124/bee6be3e-56e1-4e80-8e29-124c71ddc993)

### 重现步骤

接口定义页面id重复，导致ID不唯一，筛选接口不准确
![image](https://github.com/metersphere/metersphere/assets/103925124/bee6be3e-56e1-4e80-8e29-124c71ddc993)

测试将接口ID发送给研发定位问题时，出现多个，非唯一，用户混淆难使用

**Comment by 13290445582** [comment]
您好，什么操作步骤产生了两个相同的ID？

**Comment by fit2cloud-yaochunrong** [comment]
目前没有找到复现路径，
只能推测是导入覆盖ID生成错误，或者同一时段导入/新增造成ID重复
看下可以加个锁啥的，防止生成一样的ID，我这边也不好复现

**Comment by fit2cloud-yaochunrong** [comment]
目前没有找到复现路径，
只能推测是导入覆盖ID生成错误，或者同一时段导入/新增造成ID重复
看下可以加个锁啥的，防止生成一样的ID，我这边也不好复现

**Comment by fit2cloud-yaochunrong** [comment]
目前没有找到复现路径，
只能推测是导入覆盖ID生成错误，或者同一时段导入/新增造成ID重复
看下可以加个锁啥的，防止生成一样的ID，我这边也不好复现

**Comment by 13290445582** [comment]
该问题未稳定复现，后续问题请重新提issue，感谢理解和支持～
