### ISSUE TITLE
[BUG]自动化场景，UI界面的问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#27135]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

在自动化场景中，如果后置操作添加了很多提取参数，比如提取参数添加了12条，占满了屏幕，再添加一个后置脚本，点击后置脚本，界面会移动到这个步骤的最上面。

### 重现步骤

1.创建一个自动化场景
2.添加一个任意有后置操作的步骤
3.在后置操作里，添加12个提取参数
4.添加一个后置脚本
5.滚轮滚动到后置脚本那里
6.展开后置脚本
7.鼠标点击脚本内容框
8.（问题复现）界面移动到了这个脚本最上方

### 期待的正确结果

不该有界面移动，这边每个步骤后置操作参数都很多，在经常使用的地方，有这么一个操作不方便的问题，影响工作效率，希望可以修复。

**Comment by 13290445582** [comment]
感谢反馈，计划v2.10.9版本优化该问题。

**Comment by 13290445582** [comment]
您好，该问题已优化，请升级尝试。
