### ISSUE TITLE
[BUG]接口自动化场景，步骤拖动问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#27136]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

接口自动化场景，使用步骤拖动来改变步骤顺序，拖动后顺序错误。

### 重现步骤

1.创建一个接口自动化场景
2.创建两个任意API步骤
3.给两个步骤命名为辨识度大一点的名称
4.复制50多个第一个步骤，让没复制的第二个API步骤为最后一个步骤
5.拖动最后那个步骤到第一或第二个步骤上
6.（问题复现）实际到那个步骤上的不为之前拖动的步骤

### 期待的正确结果

让拖动步骤改变顺序成功

**Comment by 13290445582** [comment]
感谢反馈，计划v2.10.9版本优化该问题。

**Comment by 13290445582** [comment]
您好，该问题已优化，请升级尝试。
