### ISSUE TITLE
项目列表中切换不同产项目的成员列表，上一个项目成员列表的展示会影响下一个项目成员列表的展示

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27138]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

项目列表中切换不同产项目的成员列表，上一个项目成员列表的展示会影响下一个项目成员列表的展示

### 重现步骤

1. 项目列表中，打开一个项目中对应的成员列表，切换到第二页，
2. 再打开另一个项目的成员列表，发现也是展示的第二页数据，即上一个项目成员列表的展示会影响下一个项目成员列表的展示

### 期待的正确结果

上一个项目成员列表的展示不会影响下一个项目成员列表的展示

### 相关日志输出

```shell
无
```

### 附加信息

![1697611598970](https://github.com/metersphere/metersphere/assets/50016789/7cb3321c-6756-49a9-afc6-eb67c44d7d6b)
![1697611675934](https://github.com/metersphere/metersphere/assets/50016789/ee25dc48-8b96-4b03-9bb8-b9edf9296f57)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复这个问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
