### ISSUE TITLE
[BUG]当提取中的 数据中存在\n时会自动将他转译成空行，将这个数据发送后会导致json解析错误

### ISSUE THREAD

**Issue by yejianxing** [metersphere/metersphere#27140]
### 联系方式

17601245463

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

当提取中的 数据中存在\n时会自动将他转译成空行，将这个数据发送后会导致json解析错误

### 重现步骤

数据中存在\n

### 附加信息

![e1948943ad8c5d9e7b31be5471ffe97](https://github.com/metersphere/metersphere/assets/60419944/a8e8d2be-1040-450d-a90d-b5baf1da2c05)
![52952b54b94faa9bf52ca2de0859077](https://github.com/metersphere/metersphere/assets/60419944/064dc1ea-d029-4d9d-917d-1dc0a841b4d6)
![af3f82c527e8a9c57a84ba61a6d0c8d](https://github.com/metersphere/metersphere/assets/60419944/287b1b19-7a53-4f97-9063-945b2c920628)
![d60964c058cccf3acd4e3f0fb161f3d](https://github.com/metersphere/metersphere/assets/60419944/e9b51a26-1b98-49c7-85e2-f15eaa28f837)

**Comment by youliyuan-fit2cloud** [comment]
你好，jmeter和postman中也是这么处理的，应该是合理的方案。如果要满足你这个场景，可以提取后用脚本再处理下，将 “\n” 再转义。感谢理解和支持。
类似：
String extractedValue = vars.get("variableName");
String processedValue = extractedValue.replaceAll("\n", "\\\\n");
vars.put("processedVariable", processedValue);
