### ISSUE TITLE
[BUG] 新建/编辑 “测试用例评审”，浮层打开过程中屏闪

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#2714]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.9

**Bug 描述**
 新建/编辑 “测试用例评审”，浮层打开过程中屏闪

**Bug 重现步骤**
1.  新建“测试用例评审”
2. 
3. 
4. 

**期待的正确结果**
1.打开浮层过程中，无屏闪

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复

**Comment by zyyfit** [comment]
1.10.1版本已修复，请升级使用
