### ISSUE TITLE
优化建议：新增项目API执行资源池默认取资源池列表得第一个（会取到性能测试资源池），不合理且没有区分资源池属性自动化  性能测试

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#27153]
### MeterSphere 版本

v2.10.7

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/82088551/68d572bd-3cf7-4a6d-86a0-4b2ddb28e7d8)
新增项目API执行资源池默认取资源池列表得第一个（会取到性能测试资源池）,建议优化

### 重现步骤

新增项目 API执行资源池默认取资源池列表 默认第一节点

### 期待的正确结果

新增项目 API执行资源池默认取资源池列表 默认第一节点，但仅限于设置的自动化资源节点

**Comment by luty2018** [comment]
感谢建议， 这个我们优化一下
