### ISSUE TITLE
[BUG] 90%响应时间 与 平均响应时间 计算不准确

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#27155]
### 联系方式

zhangyy@bjhzwq.com

### MeterSphere 版本

 v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

最新版： v2.10.7-lts-7f7afdc5，企业版。

计算的90%响应时间比平均响应时间小很多，理论应比平均响应时间大。
![1](https://github.com/metersphere/metersphere/assets/71361375/0f51bbeb-0eb9-4b93-a555-0dcfbe683bff)

### 重现步骤

最新版： v2.10.7-lts-7f7afdc5，企业版。

计算的90%响应时间比平均响应时间小很多，理论应比平均响应时间大。

**Comment by liuruibin** [comment]
你这个最大值太大了，导致平均值也变大了
