### ISSUE TITLE
[BUG]redis无法启动

### ISSUE THREAD

**Issue by mayou33** [metersphere/metersphere#27159]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

cd /opt
wget https://github.com/metersphere/metersphere/releases/download/v2.10.7-lts/metersphere-online-installer-v2.10.7-lts.tar.gz
tar zxvf metersphere-online-installer-v2.10.7-lts.tar.gz
cd metersphere-online-installer-v2.10.7-lts
/bin/bash install.sh
启动报错
dependency failed to start: container redis is unhealthy
查看redis日志
docker logs redis
报Fatal error, can't open config file '/etc/redis/redis.conf': Permission denied
![图片](https://github.com/metersphere/metersphere/assets/22804372/bab99aa6-3b4c-4291-938d-486ebbdee95a)

解决方法：
chmod 644 /opt/metersphere/conf/redis.conf
docker restart redis
![图片](https://github.com/metersphere/metersphere/assets/22804372/23fa43f0-2a9b-4287-a706-6c2bc97c2c8b)

ps：
默认文件都是0640权限，建议至少改为0644

### 重现步骤

启动redis

**Comment by youliyuan-fit2cloud** [comment]
你好，centos7.9 系统安装没有复现该问题，你这个服务器是哪个版本？当前登录服务器的用户是什么权限？

**Comment by mayou33** [comment]
centos7.9 系统 ，用root账号

**Comment by mayou33** [comment]
![图片](https://github.com/metersphere/metersphere/assets/22804372/e99f2b19-c8fc-476b-a1d0-62df72eb79e9)
![图片](https://github.com/metersphere/metersphere/assets/22804372/ee3eea87-dcb4-4537-ac5a-abbacecc8b96)
我的环境必现 ，我先用  0644权限解决吧

**Comment by youliyuan-fit2cloud** [comment]
查看下umask是多少，默认应该是0022。
不是的话，执行
umask 755
msctl reload
如果服务器上安装部署了其他程序，可以单独修改metersphere 的安装目录权限。
