### ISSUE TITLE
[BUG] 性能测试运行结束后没有测试报告，后台报错

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#2715]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  性能测试》》选择从接口场景加载一个场景》》运行
2. 性能测试运行完毕，可以看到日志，但是没有测试报告
3. 查看log，发现系统错误
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/117910206-1e0cc700-b30e-11eb-8354-d153f76da482.png)

![image](https://user-images.githubusercontent.com/78218624/117910330-514f5600-b30e-11eb-9985-bf069af3485f.png)
![image](https://user-images.githubusercontent.com/78218624/117910466-8e1b4d00-b30e-11eb-827a-703bb54b3c51.png)

**Comment by zyyfit** [comment]
您好，您使用的是哪个版本呢？我在1.9.2上没有复现

**Comment by zyyfit** [comment]
您好，1.10.0版本修改了资源池验证的逻辑，请等待新版本发布后验证验证一下

**Comment by zyyfit** [comment]
1.10.0版本已修复
