### ISSUE TITLE
[BUG]接口测试，接口定义列表，用例状态没有同步。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27157]
### MeterSphere 版本

v2.10.7

### 使用外置数据库

否

### 问题描述

接口测试，接口定义列表，用例状态没有同步。

### 重现步骤

1.接口api的状态
![image](https://github.com/metersphere/metersphere/assets/55130444/8499aad1-958b-4cad-801a-fd7c32fe60fe)
2.对应case状态
![image](https://github.com/metersphere/metersphere/assets/55130444/09f8b283-e8c1-4ebf-8b1b-198950dcb0f8)

3.取值不一致。

### 期待的正确结果

接口定义列表 用例状态 可以和对应的case的状态保持一致

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.8-lts修复。
