### ISSUE TITLE
[BUG]接口定义-定时同步，接口请求体变化，新增参数没有同步

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27163]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

接口定义-定时同步，接口请求体变化，新增参数没有同步

### 重现步骤

1. 设置定时同步,同步接口, 版本v1.0.0,
![image](https://github.com/metersphere/metersphere/assets/103627487/bffca633-0482-4fa5-9d4b-744a8d2944ca)
![image](https://github.com/metersphere/metersphere/assets/103627487/39893faa-eb8f-4f3a-b7a9-22b12f40540d)
3.删除接口请求体中参数（为了模拟接口中参数有变更）
![image](https://github.com/metersphere/metersphere/assets/103627487/7aae4aea-4668-4bbd-a5d3-b8e7320f37c5)
4.创建 v2.0.0 版本和 v3.0.0 版本，把 v2.0.0 版本 设置为最新版本
![image](https://github.com/metersphere/metersphere/assets/103627487/058ee92e-3c01-4f2a-928f-06d5f62f0d4e)
5.定时同步，查看接口，接口更新时间已更新，参数没有更新
![image](https://github.com/metersphere/metersphere/assets/103627487/367697e1-0ce3-4d6a-b502-9817695cf0b5)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
