### ISSUE TITLE
[BUG]UI调试生成的图片会一直存在服务器上，导致磁盘空间越来越小

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27166]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

<img width="1248" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/ed580075-3255-430c-a354-c6f4bb9cb8eb">

<img width="491" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/dd112415-b9d4-4fdd-8c84-06088283cabb">

存放图片路径数据越来越大

### 重现步骤

1、找一个UI场景，每个步骤添加截图，进行后端调试（还有生成报告）
2、在多次调试的过程中，根据下图进行查看保存图片的空间数据变化，是否是越来越大
<img width="491" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/dd112415-b9d4-4fdd-8c84-06088283cabb">
3、删除UI测试的报告，查看保存图片的空间数据是否变小了

### 期待的正确结果

1、只保留最后一次的调试中的截图
2、删除报告时，可以删除对应的图片

**Comment by zrfit** [comment]
您好，感谢反馈！
1、调试的截图-后端服务会每天凌晨定时删除昨天之前的调试截图数据，v2暂时保持这种处理机制。
2、最新版本v2.10.7-lts版本，删除报告，服务器对应截图文件也删除，建议升级到最新版本尝试。
![image](https://github.com/metersphere/metersphere/assets/99731894/b40d61fc-e4da-420d-a9fb-6e50205901f4)

**Comment by sss903065212** [comment]
好的了解
