### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jiangrry** [metersphere/metersphere#2716]
**请描述您的需求或者改进建议.**
复制断言的时候原断言内容所在行回收拢，需要点击“+”才能对复制的断言进行修改
![image](https://user-images.githubusercontent.com/6359046/117910939-74c6d080-b30f-11eb-8185-b833db20cf33.png)

**请描述你建议的实现方案**
复制后，直接在原有断言下新增一条，不需要重新打开

**Comment by xulinde** [comment]
感谢反馈，下个版本可以优化下

**Comment by xulinde** [comment]
1.10版本已优化
