### ISSUE TITLE
[FEATURE]metersphere是否可以支持请求体注释

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27185]
### MeterSphere 版本

v2.10.7-lts

### 请描述您的需求或者改进建议

比如这样，参数多又不能转json-schema的时候，如果能注释就很好
![image](https://github.com/metersphere/metersphere/assets/88763608/48963dbf-5270-4c61-8d02-fcb39358f433)

**Comment by luty2018** [comment]
目前组件不支持，V3 会支持

**Comment by luty2018** [comment]
v3.0已支持， 欢迎下载使用
