### ISSUE TITLE
[BUG]已经删除的case在场景里还会运行

### ISSUE THREAD

**Issue by raykeyor** [metersphere/metersphere#27182]
### 联系方式

交流群64，昵称：皮蛋瘦肉周

### MeterSphere 版本

v2.10.5-its-0ba6e94d

### 使用外置数据库

是

### 问题描述

接口测试模块，在场景A中引用场景B，在场景B中引用了一个case。将这个case所属的api删除后，对应的case也被删除，但是运行场景A仍然会执行已经删除的case。我的预期结果是：将api进行删除后，对应的case也被删除。且在场景嵌套引用时不再执行我已经删除的case.

### 重现步骤

新建场景A，新建场景B，在场景A中引用场景B，在场景B中引用一个case。将这个case所属的api删除，运行场景A

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，当前删除后还在回收站里，场景中仍可执行。想要不执行可以在回收站中彻底删除该接口定义。感谢理解和支持～
