### ISSUE TITLE
[BUG]  在接口自动化中，选择运行环境，点击确认，会修改步骤中已经选择好的数据源。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#27183]
### MeterSphere 版本

v1.20.23-lts-77e58286

### 使用外置数据库

否

### 问题描述

在接口自动化中，选择运行环境，点击确认，会修改步骤中已经选择好的数据源。

https://github.com/metersphere/metersphere/assets/33945037/3fc8749f-3c72-40ea-abc0-ded992d28ca3

### 重现步骤

同上

**Comment by 13290445582** [comment]
您好，最新版本未复现该问题，建议升级至最新版本尝试。

**Comment by hao65103940** [comment]
> 您好，最新版本未复现该问题，建议升级至最新版本尝试。

是v1.20.23-lts-77e58286这个版本的，你测试的是什么版本？可否截图或者录制视频操作下？目前最新版本就是这个版本的

**Comment by hao65103940** [comment]
> > 您好，最新版本未复现该问题，建议升级至最新版本尝试。
> 
> 是v1.20.23-lts-77e58286这个版本的，你测试的是什么版本？可否截图或者录制视频操作下？
