### ISSUE TITLE
[BUG]添加依赖用例，如果用例50/页,有些用例没有勾选框

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#27180]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

如果用例50/页,有些用例没有勾选框

### 重现步骤

1、添加依赖用例
![image](https://github.com/metersphere/metersphere/assets/33934471/9b077dae-ba80-47e3-a92d-82851a5358d0)
2、设置每页50，发现有些用例，没有勾选框
![image](https://github.com/metersphere/metersphere/assets/33934471/bb50857d-b63b-4c62-bbee-df849aaab24b)

### 期待的正确结果

有勾选框，可以添加用例

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复这个问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
