### ISSUE TITLE
[BUG]    UI场景导出再导入，纯数字的字符串类型的变量，变成数值型了

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27190]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

UI场景导出再导入，纯数字的字符串类型的变量，变成数值型了

### 重现步骤

原场景的是字符串：
新导入的场景变为数值
![image](https://github.com/metersphere/metersphere/assets/103925124/ba37238b-57a3-472e-863d-8f4eb3e0960e)

**Comment by zrfit** [comment]
您好，感谢反馈！metersphere导出文件为ide格式，和ide兼容，目前导入是通过target内容校验类型转化显示，v2暂时保持现状。v3增加导出为metersphere格式，将解决该问题。
