### ISSUE TITLE
接口场景自动化执行多次之后，接口提取到的值与当前接口响应体不一致，接口提取还是提取上一次的响应体的值，并非本次响应体的值 ，这个问题

### ISSUE THREAD

**Issue by wuyezhao** [metersphere/metersphere#27208]
### 联系方式

475443417@qq.com

### MeterSphere 版本

2.10.6lts

### 使用外置数据库

是

### 问题描述

当我执行接口场景自动化，手动执行，跑了2-3次之后，如果上次响应体返回的code是400，这时候再执行，响应体返回的code是200，jsonpath提取的时候是提取的400，也就是拿的是上一次的，所以就会报错，导致接口自动化无法往下执行

### 重现步骤

就是场景自动化：然后执行多次，比如第一次是返回code是400或其他，然后第二次返回的是200，重复切换几次  就能重现这个问题

### 期待的正确结果

每次返回的响应体，jsonpath提取到的应该也是本次响应体的内容

**Comment by wuyezhao** [comment]
![6fc684c8acbb98e9e421b8d14887c36](https://github.com/metersphere/metersphere/assets/33748928/486d3756-e692-444c-b6c8-1102c7c25f40)

**Comment by wuyezhao** [comment]
![image](https://github.com/metersphere/metersphere/assets/33748928/9dc9663e-0840-457b-b5a1-be829d783b39)

**Comment by zrfit** [comment]
你好！感谢反馈！最新版本v2.10.7-lts未复现该问题，建议升级到最新版本尝试。

**Comment by wuyezhao** [comment]
我在2.10.7-lts依然有这个问题，能麻烦联系我一下吗？
