### ISSUE TITLE
[BUG]【测试计划】执行测试计划后，状态和测试进度没有刷新成功，仍然是上一次执行完的状态和测试进度

### ISSUE THREAD

**Issue by duxinc** [metersphere/metersphere#27217]
### 联系方式

交流群40-空空star

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划tab下，执行测试计划后，状态和测试进度没有刷新成功，仍然是上一次执行完的状态和测试进度；
手动刷新后，状态会正常，但是测试进度仍然没更新
![image](https://github.com/metersphere/metersphere/assets/77928086/8070da4d-c9cd-4d6d-b90c-29d9a55d2a35)

### 重现步骤

1.先执行一个测试计划，执行完后状态是已完成，测试进度是100%；
2.再次执行该测试计划，自动刷新后状态仍然是已完成，测试进度是100%；

### 期待的正确结果

再次执行该测试计划，自动刷新后状态应该是进行中，测试进度是0%或者实际进度，刚执行后测试进度应该不会是100%

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
关于重新运行时测试计划状态没有第一时间改动：
因为测试计划运行是个需要查询各种资源并进行执行的过程。为了让页面反应更快一些，这里使用了异步线程进行处理。所以为什么刚点击运行完，状态没有及时更新。因为数据还没处理完或者数据库事务没有同步提交。
关于测试进度：
测试进度的计算公式中， 如果一个用例执行过，那么就算是覆盖到了。所以即使是重复运行，哪怕是运行过程中，由于这个用例之前运行过，我们也会算作覆盖。
感谢您的理解与支持。
