### ISSUE TITLE
[BUG] “性能测试-测试-高级配置”里的“建立连接超时时间”和“响应超时时间”设置无效

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2723]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1-2cb10c1e

**Bug 描述**
下载了平台生成的Jmeter脚本，发现里面设置了6000ms的超时设置，而且“性能测试-测试-高级配置”里的“建立连接超时时间”和“响应超时时间”默认的是60000ms没有生效，手工改成30000ms也没有生效。有的时候不需要超时设置或本身就是长时间的请求的话，这个会导致“Non HTTP response code: java.net.SocketTimeoutException”的异常。

**Bug 重现步骤**
1.  配置一个请求，使其响应时间超过6000ms；或响应时间随机，有一定比例超过6秒（最大响应时间要能大一些）。
2.  在MeterSphere平台压测这个请求，“性能测试-测试-高级配置”里的“建立连接超时时间”和“响应超时时间”使用默认设置，压测，换成其他值重复压测。
3.  在压测报告里会发现有部分请求会出现“Non HTTP response code: java.net.SocketTimeoutException”的异常，且这些请求的最大响应时间约为6000ms（一般不超过7000ms）。

**期待的正确结果**
希望“性能测试-测试-高级配置”里的“建立连接超时时间”和“响应超时时间”的设置生效,。且它们可以填0或有其他配置使其失效（“建立连接超时时间”在前端页面不能填0，填0会变成10），这一点希望能达到与Jmeter相同的效果。

**截图**
暂无

**Comment by goteen** [comment]
@liuruibin 你好！我现在用的“v1.10.0-93f6870d”版本的，它压测时还是默认的6000ms，界面修改参数没有效，还是需要下载下来后手工修改超时时间。你们上一次修改好像是把前端页面修改了，后端生成Jmx文件的逻辑有做修复吗？

**Comment by liuruibin** [comment]
1. jmx 全局配置中本来有值的情况页面配置了的话会替换掉否则不处理。
2. jmx 采样器上的超时配置优先级高于全局配置，这里如果有值的话全局配置无效。
3. 从接口测试转换过来的性能测试采样器上有超时配置，可以从那里改了之后再转换 。

**Comment by goteen** [comment]
通过引用生成的JMX文件，采样器的超时配置默认的6000，我每次下载下来，就要修改这个值，而且自动生成的JMX里没有全局的“HTTP请求默认值”这个设置

**Comment by goteen** [comment]
@liuruibin 
1、通过Swagger导入的API里默认的超时时间显示是空，修改这个时间有用，**改成其它值后可以改成空**。
2、“接口自动化”的“其他设置”，它默认的是空，可以改成其它值（包括0），**改成其它值后就不能改成空了**。
3、虽然以上默认显示的都是空，但生成的JMX还是6000，需要手工改，改它们是有效的。
4、性能测试里设置超时时间不生效。
