### ISSUE TITLE
[BUG]2.10.7, 接口Mock后置脚本，无法引用第三方jar包。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#27237]
### 联系方式

王进

### MeterSphere 版本

v2.10.7

### 使用外置数据库

否

### 问题描述

2.10.7, 接口Mock后置脚本，无法引用第三方jar包。完全相同的脚本在自定义脚本里执行通过。

### 重现步骤

1. 克隆开源项目https://github.com/binarywang/java-testdata-generator，到本地，打包。
2. 把生成的java-testdata-generator-1.1.2.jar传到 MeterSphere项目设置》文件管理
3. 新建一个场景，添加自定义脚本，生成身份证id，调试执行成功
import cn.binarywang.tools.generator.*;
var idCard = ChineseIDCardNumberGenerator.getInstance().generate();
log.info(idCard);
vars.put("variabletmp", idCard);
log.info(vars.get("variabletmp"));

4. 打开一个接口定义，添加一个Mock，在该Mock下面添加一个后置脚本。
import cn.binarywang.tools.generator.*;
var idCard = ChineseIDCardNumberGenerator.getInstance().generate();
vars.put("variabletmp", idCard);
响应体定义如下：
{
    "result": ${variabletmp}
}

<img width="1272" alt="1698205966728" src="https://github.com/metersphere/metersphere/assets/76033005/2938d279-3918-4874-a0dd-95d02e5345a5">

5. 测试该Mock，会抛出异常
<img width="919" alt="1698206028772" src="https://github.com/metersphere/metersphere/assets/76033005/a1bbf8c0-7cc5-4202-a3d4-175dd074919f">

<img width="1532" alt="6d8756ce1d5d872ee47ca02c2e93f49" src="https://github.com/metersphere/metersphere/assets/76033005/7fe0dff9-55f4-4f43-ac41-07d3cbe1822c">

**Comment by Somebody-JIAN** [comment]
文件管理那里有没有启用这个jar包
以及这个jar包有没有其它关联的jar包

**Comment by Somebody-JIAN** [comment]
还有， var换成string试试。   
而且之前在wiki上写过， mock后置脚本里没有集成log对象的原因。
也就是说用log肯定会报错

**Comment by 35plus** [comment]
1. 启用了jar包
2. 没有关联jar包，这个jar在前后置脚本里可以直接调用，截图上面也有
3. 没有用log.info

**Comment by Somebody-JIAN** [comment]
https://github.com/binarywang/java-testdata-generator
我看了下这个开源项目的pom，里面引用了别的包：
![image](https://github.com/metersphere/metersphere/assets/75963100/f03df62d-d4bd-478f-899a-79b67101bf00)

当前版本的mock后置脚本是一个比较纯净的运行开发环境，跟前后置脚本不一样（前后置脚本里内置了部分默认jar包）。 所以暂不能做到类似于前后置脚本那样方便。  后续版本的优化方式也在讨论中。

**Comment by 35plus** [comment]
感谢

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
