### ISSUE TITLE
[FEATURE] 希望能支持Jmeter的setUp线程组和tearDown线程组的功能

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2724]
**请描述您的需求或者改进建议.**
    现在无法通过MeterSphere的配置实现Jmeter的setUp线程组和tearDown线程组的功能。这种特殊的线程组在整个压测过程中只需要执行一次，而现在生成的是普通的线程组。通过循环控制器和条件控制器暂时没有实现它们整个压测过程只执行一次的效果。
    这个功能同时需要能够实现跨线程组传递参数、修改变量的功能，不能传参的话效果会大打折扣，希望能够达到和Jmeter一样的效果。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by xulinde** [comment]
下个版本会支持

**Comment by xulinde** [comment]
1.10版本已支持
