### ISSUE TITLE
[BUG]不同的CSV文件，在循环嵌套中使用获取数据时顺序不准确

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27240]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

循环嵌套下有AB两个循环，B在A里面
分别打印2个不同的CSV数据，但是B打印的第一条数据不是第二个CSV文件的第一行的数据

### 重现步骤

1、新建一个场景
2、场景变量添加两个CSV文件
3、添加2个循环A、B，B循环在A里面
4、A循环打印第一个csv文件的数据
5、B循环打印第二个csv文件的数据
6、查看B循环的第一个打印数据是否是第二个CSV文件数据的第一行数据

### 期待的正确结果

不同循环使用CSV数据进行数据隔离

**Comment by zrfit** [comment]
您好，感谢反馈！该问题为已知问题，同#21970，v2暂时不处理，v3优化。
