### ISSUE TITLE
[BUG] 统一helm chart中所依赖的组件(image)版本

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#27243]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

在helm chart中，同一个kubectl，出现2个版本：
kafka中为1.25.10-debian-11-r6 ，在 MS各个微服务的template中为 1.19.15-debian-10-r3，建议统一一下，方便在离线环境安装。

$ grep -A 1 "repository: bitnami/kubectl" ../charts/kafka/values.yaml
      repository: bitnami/kubectl
      tag: 1.25.10-debian-11-r6 

![1698218684757](https://github.com/metersphere/metersphere/assets/24548477/2e659e02-266a-4ee7-874c-aacbff57710a)

### 重现步骤

N/A

**Comment by youliyuan-fit2cloud** [comment]
你好，v2.10.8-lts版本中已优化。
