### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by boommanpro** [metersphere/metersphere#27254]
### MeterSphere 版本

v1.20

### 联系方式

boommanpro@gmail.com

### 请描述您的需求或者改进建议

期待1panel部署支持

**Comment by liuruibin** [comment]
1.20 不再进行维护

**Comment by luty2018** [comment]
通过1panel部署，已经规划到v3.0版本了

**Comment by luty2018** [comment]
v3.0已支持通过1panel部署， 欢迎下载使用
