### ISSUE TITLE
[BUG]【性能测试】监控处，配置cpu表达式，最终监控数据一样，但是显示的图形不一样。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27257]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

【性能测试】监控处，配置cpu表达式，最终监控数据一样，但是显示的图形不一样。

### 重现步骤

【性能测试】监控处，配置cpu表达式,一个是系统默认表达式，一个是将系统默认表达式中的“%1$s” 写成具体ip:9100，最终监控数据一样，但是显示的图形不一样。
![image](https://github.com/metersphere/metersphere/assets/104960608/5a5b15e9-99e9-4712-87fe-5abda80c323d)
![image](https://github.com/metersphere/metersphere/assets/104960608/94720ad5-3207-4012-9fcb-324a83b918b1)

**Comment by zrfit** [comment]
您好，感谢反馈！监控指标只有选择下拉框的名称cpu才能默认以左侧单位显示曲线，自定义名称统一按右侧单位显示曲线。
<img width="877" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/0b720331-1332-434d-a446-864b2f8bf563">
<img width="1429" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/84287f34-9bcc-4812-aa46-842404518fa7">

**Comment by liuruibin** [comment]
我们不能预先知道自定义promQL返回的数据是个比率(0-100%)还是个数值，也不知道返回的是个字节数、MB、GB、温度、单纯的个数。所以除了我们内置的监控外，所有自定义监控的数值都是没有单位的。
