### ISSUE TITLE
[BUG]项目设置-文件管理，无法上传中文名称的txt文件

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27263]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

项目设置-文件管理，无法上传中文名称的txt文件，页面无响应

### 重现步骤

1.准备一个中文名称的txt文件，比如“日报.txt”
2.在项目设置文件管理中上传，结果页面无响应，后台无报错，控制台抓包也没内容
![image](https://github.com/metersphere/metersphere/assets/88763608/d323ecc1-8bc6-4e93-a619-92e764154d61)
![image](https://github.com/metersphere/metersphere/assets/88763608/5fcb6831-9fcd-4540-b40e-22f76f7c47ba)

### 期待的正确结果

正确上传

**Comment by liuruibin** [comment]
没有复现出来

**Comment by youliyuan-fit2cloud** [comment]
是否100%出现？浏览器版本？windows 机器 ？
