### ISSUE TITLE
[BUG]接口测试上传文件是中文名称，请求时是??问号

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27262]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

接口测试上传文件是中文名称，请求时是??问号

### 重现步骤

1.接口测试使用文件上传，上传一个中文名的文件
![image](https://github.com/metersphere/metersphere/assets/88763608/f06f4132-5237-40f1-9e64-780448515ac6)
2.执行测试，查看请求内容，文件名显示为??.txt
![image](https://github.com/metersphere/metersphere/assets/88763608/a0f6beca-9d88-4b1e-af81-0721674eaa8f)

### 期待的正确结果

正确编码中文文件名

**Comment by liuruibin** [comment]
jmeter 5.6 以上才支持中文文件名，我们v2.10用的是5.5 不再升级了
