### ISSUE TITLE
[BUG]高级搜索后再添加关联用例，发现有重复

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#27277]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

用例被重复关联

### 重现步骤

1、测试计划->点击进去->点击“关联测试用例”
![image](https://github.com/metersphere/metersphere/assets/33934471/b1d74ab5-e8bf-4eab-9d08-97e1afa1f299)

2、点进去“高级搜索”，直接点击查询
![image](https://github.com/metersphere/metersphere/assets/33934471/3416218a-2996-4c4f-8dc2-5d6d9143693b)

3、确定后，页数选择50/页,勾选左上角，点击确定
![image](https://github.com/metersphere/metersphere/assets/33934471/d611967a-96da-4e87-9585-a5efbefb2f87)

4、继续勾选将剩余13条加进去
![image](https://github.com/metersphere/metersphere/assets/33934471/9a7aa22b-56c8-47c2-a3d2-9e5ed4b50a91)

5、关闭后，发现有50条重复关联的用例
![image](https://github.com/metersphere/metersphere/assets/33934471/44168a8a-7804-491c-9144-76920e8ef7b8)

### 期待的正确结果

之前关联过的用例不应该被重复关联

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
