### ISSUE TITLE
[BUG]接口自动化报告高级搜索“API调用”，无法搜索出报告

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27288]
### 联系方式

蒋林峰

### MeterSphere 版本

v1.20.23-lts

### 使用外置数据库

否

### 问题描述

接口自动化报告高级搜索“API调用”，无法搜索出报告

### 重现步骤

1.接口自动化测试报告有API调用方式触发的
<img width="926" alt="8c6784c7718e3dc2b7faba0e060daf6" src="https://github.com/metersphere/metersphere/assets/88763608/42812ac1-2766-43d0-bca2-8339ba8ff020">
2.高级搜索选择API调用
<img width="911" alt="0eb4eb419eeab74c1adf95d31f5a4d4" src="https://github.com/metersphere/metersphere/assets/88763608/676c7350-f26b-4eeb-8ef4-141ab6091a9e">
3.查出来没结果
<img width="957" alt="618d18dc3e02d090e5c8c168c244f22" src="https://github.com/metersphere/metersphere/assets/88763608/5273d7b8-532c-4344-8bb4-410c24387881">

### 期待的正确结果

正确查询

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.8-lts无该问题，建议升级到最新版本尝试。
<img width="1192" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/9f8ba434-8573-4a2f-8fc0-f3ac83ff0ed3">
<img width="1353" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/b6ca9857-23e4-4a51-9a06-6d21dd3d85f7">
