### ISSUE TITLE
[BUG]升级到最新版本后超级管理员在项目管理的用户组与权限页面无权限

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27284]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

  系统由V2.10.6 升级到v2.10.8 ，原来的具有超级管理员的用户，不能打开项目管理-用户组与权限，提示无操作权限，新建用户赋予超级管理员，可以打开项目管理-用户组与权限

### 重现步骤

1.系统由V2.10.6 升级到v2.10.8 后，原来的超级管理员 不能打开项目管理中的用户组与权限，会提示无操作权限
2. 为该用户添加具有用户组权限的项目管理员后，可以打开项目管理中的用户组与权限
3. 该用户将第二步添加 的项目管理员用户组删除后，该用户依然可以打开项目管理的用户组与权限
4. 新建用户，并赋予超级管理员用户组，新建的用户可以打开项目管理的用户组与权限

### 期待的正确结果

系统升级后，原来的超级管理员可以打开项目管理-用户组与权限

### 附加信息

![909b4f6a19a4299c7415914c6aca9679](https://github.com/metersphere/metersphere/assets/145318182/f1e24d7b-fac7-432c-ad76-798b923e9f45)

**Comment by 13290445582** [comment]
感谢反馈，未复现，通过提供的相同账号相同环境打开，未复现该问题，初步猜测可能是浏览器缓存，可清理浏览器缓存尝试，感谢理解。
