### ISSUE TITLE
[BUG]测试计划左侧出现双滚动条

### ISSUE THREAD

**Issue by davidcchen** [metersphere/metersphere#27298]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

出现双滚动条，应该只有一个

### 重现步骤

加多个模块，每个模块添加用例，都加到测试计划里面
![image](https://github.com/metersphere/metersphere/assets/33934471/ef792084-6b93-4c31-9c0d-992ec9797ff9)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.9-lts优化。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
