### ISSUE TITLE
[BUG] c本地xmind编写用例没有写用例标签，导入后默认表示为模块，导入且不能手动改标记

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27292]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

本地xmind编写用例没有写用例标签，导入后默认表示为模块，导入且不能手动改标记

### 重现步骤

1\、地xmind编写用例没有写用例标签 tc
2、用例管理，导入xmind用例后  切换到脑图查看后默认表示为模块，导入且不能手动改标记
![本地xmind编写用例没有写用例标签，导入后默认表示为模块，导入且不能手动改标记](https://github.com/metersphere/metersphere/assets/43202800/28c3f953-ed37-4ec0-8076-fe06a7c8662a)

### 期待的正确结果

可以手动修改标记为用例及其他

**Comment by 13290445582** [comment]
您好，我们是不支持这样使用的，脑图模式下手动将模块修改为用例这种操作是不可以的，会涉及到删除模块，还关系到模块下的用例，所以是不能这样使用的，感谢理解。
