### ISSUE TITLE
[FEATURE]测试用例和Jira需求关联

### ISSUE THREAD

**Issue by Bearzzzzz** [metersphere/metersphere#273]
**请描述您的需求或者改进建议.**
1.在新建测试用例（手工、接口、性能测试）时，提供【关联需求】字段，用户可以将对应需求的JiraID填在此处。用例新建完成后，查看用例信息时，metersphere会以超链接的形式展示该用例的【关联需求】值，点击该超链接可以跳转到Jira中相应需求页面
2.接口测试运行完成之后，对于失败的用例metersphere会自动创建Jira缺陷给用例维护人（由用例维护人确认后转给相应的处理人处理）（考虑到实际运行中误报可能较多，尤其是在和流水线集成的情况下测试频率较高，为了避免产生大量无用的缺陷，建议metersphere在建缺陷前能自己做一个过滤，例如：已经建过缺陷且缺陷尚未关闭的用例不重复建缺陷；被测接口相同的用例不重复建缺陷）
3.手工测试除了当前metersphere支持的提缺陷方式外，也可以由用户选择创建jira缺陷，其中的部分缺陷信息由metersphere默认填好（如报告人为当前用户，处理人为所测用例关联需求的处理人），用户只需关注在填写缺陷描述等信息上。

Jira可以配置为创建缺陷时，给处理人发送邮件，通过这种方式确保每个缺陷在创建后都能及时通知到相应处理人做处理。

**请描述你建议的实现方案**
1.在metersphere的【系统设置】中可以加上一个【持续集成】菜单栏，里面用于维护所有持续集成工具的配置信息。Jira配置也放在该菜单栏下。对于jira来说，需要配置的信息包括：Jira访问链接、用户名（具有创建缺陷权限）、密码
2.对于创建缺陷等功能，可以通过jira官方提供的api实现：https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/

**Comment by zyyfit** [comment]
目前已经添加了jira关联功能，已实现在metersphere中手动提bug到jira
