### ISSUE TITLE
[BUG]接口测试，后置脚本，没有支持直接定义String类型的数组并赋值。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27304]
### MeterSphere 版本

qa环境

### 使用外置数据库

否

### 问题描述

1.前置脚本使用groovy，通过  String[] stringArray = {"Apple", "Banana", "Orange"}; ，无法这样定义数组，会报错，正常java是可以这样定义的。
![image](https://github.com/metersphere/metersphere/assets/55130444/8c4b5238-632d-4dc7-9791-f37a86cb87c1)
2.把 String[] stringArray = ["Apple", "Banana", "Orange"];  定义数组的大括号改成中括号就可以了，
![image](https://github.com/metersphere/metersphere/assets/55130444/bed09e52-05a0-4d10-b7c0-159295753ee5)
**3.这里是语法问题吗？？**

### 重现步骤

// String[] stringArray = {"Apple", "Banana", "Orange"};

String[] stringArray = ["Apple", "Banana", "Orange"];

String result = String.join(", ", stringArray);

log.info(result); // 输出结果

**Comment by fit2-zhao** [comment]
在 Groovy 中，数组的初始化方式与 Java 稍有不同，类似：

`def test = ["x", "a"]
`或 
`String [] test = new String[] {"x","a"};
`

**Comment by kaijie-yu** [comment]
感谢
