### ISSUE TITLE
[BUG]UI自动化步骤添加前后置等待时间，时间未设置具体值时导致整个测试场景执行中断

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27306]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

UI自动化步骤添加前后置等待时间，等待时间未设置具体值，用户后来忘记修改等待时间就保存了，最后执行场景发现在对应步骤执行中断。

### 重现步骤

1、选择某个UI自动化场景进行编辑
2、某个步骤前置或者后置添加等待时间
3、不设定等待时间值，执行整个场景

### 附加信息

添加等待时间之前：
<img width="1469" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/abbae467-dde7-4e57-9273-d9841659b90e">

添加等待时间之后：
<img width="1475" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/e6e1d3f1-a99b-4b83-a2b5-392f968f9e83">

**Comment by zrfit** [comment]
您好，感谢反馈！已知问题，计划v2.10.9-lts优化，增加默认值。

**Comment by 13290445582** [comment]
您好，实际开发过程中发现修改该处涉及到很多细节，为了保证开发质量，暂时不在v2.10.9版本实现，后续版本优化该处，感谢理解。
