### ISSUE TITLE
[BUG]  接口测试mock， 后置脚本python设置变量失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27302]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口测试mock后置脚本， 后置脚本python设置变量失败

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/998c12a5-9dc0-479c-b04d-c4a2ff522407)

![image](https://github.com/metersphere/metersphere/assets/103925124/74cf1200-b0f1-4cfc-a1a3-8f73197bff25)

**Comment by Somebody-JIAN** [comment]
语法不对。 python脚本应该是：
![image](https://github.com/metersphere/metersphere/assets/75963100/5191414b-d248-4db8-90cb-afc2dd62a3cb)

**Comment by fit2cloud-yaochunrong** [comment]
![1698724048507](https://github.com/metersphere/metersphere/assets/103925124/db23f82b-7faf-423a-93bd-1a6cd564c08e)
既然这样的话，要不改下这里的Pythone设置变量的例子呢

因为在  自动化测试的脚本了Pythone可以使用vars.put放变量的

**Comment by 13290445582** [comment]
您好，已收到建议，规划在v2.10.9版本优化一下。

**Comment by 13290445582** [comment]
您好，对该处的优化是  点击获取变量给出模版vars["variable_name"]，优化上目前是采用的该形式，设置变量未修改，仍保持原设计，感谢您的理解与支持。
