### ISSUE TITLE
[BUG][接口测试][测试跟踪]接口的返回数据里有表情，在单接口测试ok，但放到[测试跟踪-测试计划]中跑，该接口会显示未开始，无法执行

### ISSUE THREAD

**Issue by Jaskyer** [metersphere/metersphere#27311]
### MeterSphere 版本

v1.20.4-lts-5b8b8d82

### 使用外置数据库

否

### 问题描述

1. 有的接口(http/json)，该接口的返回值里带有表情，在【接口测试-接口定义】模块写的接口用例，单独调试是正常的
2. 但把多条接口用例，在【测试跟踪】-【测试计划】中取执行，则最终的测试报告中，该接口用例会显示未开始，里面什么信息都没有

### 重现步骤

如问题描述

### 期待的正确结果

【测试跟踪】-【测试计划】里也能正常执行

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/8936383/c3462e36-087e-4464-92c3-ff7f9930d92a)

![image](https://github.com/metersphere/metersphere/assets/8936383/3669e0c0-d8d2-451c-9667-d286714c0784)

**Comment by 13290445582** [comment]
您好，调试的接口方便提供下吗？

**Comment by Jaskyer** [comment]
> 您好，调试的接口方便提供下吗？

你好，抱歉哈，接口是我们内部接口不方便透露，里面返回的内容，表情有这些：💰🏂😏 📷
比如：{
    "code": 0,
    "data": {
        "medias": [
            {
                "info": {
                    "category": "",
                    "description": "带着xxx！💰🏂😏 📷",
				}
			}
		]
	}
}
可以Mock一下试试吗

**Comment by 13290445582** [comment]
您好，通过您提供的响应体内容mock，在最新环境v2.10.8版本未复现该问题，建议您升级至最新版本使用。

**Comment by lakuite** [comment]
> 您好，通过您提供的响应体内容mock，在最新环境v2.10.8版本未复现该问题，建议您升级至最新版本使用。

v1不能修复下么，我是 v1.20.23版本的，也有这个问题。v1和v2变化比较大，现在系统使用比较频繁，不好升级呐

**Comment by Jaskyer** [comment]
> > 您好，通过您提供的响应体内容mock，在最新环境v2.10.8版本未复现该问题，建议您升级至最新版本使用。
> 
> v1不能修复下么，我是 v1.20.23版本的，也有这个问题。v1和v2变化比较大，现在系统使用比较频繁，不好升级呐

+1

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉，v1版本目前只做严重问题修复，安全漏洞相关的修改，其他问题不再处理，感谢理解和支持～
