### ISSUE TITLE
[FEATURE]缺陷列表增加jira-id展示

### ISSUE THREAD

**Issue by buhuixiedaimade** [metersphere/metersphere#27326]
### MeterSphere 版本

2.10.8-lts

### 请描述您的需求或者改进建议

缺陷列表增加展示jira-id字段，该字段在数据库中有存储

目前ms不能点击缺陷跳转到jira，所以增加jira-id后，更容易让用户在jira找到对应的缺陷。

**Comment by Hyyfit** [comment]
V3 已规划
