### ISSUE TITLE
[FEATURE]测试计划执行用例步骤时，用例所有步骤执行完成后，自动更新整条用例的结果

### ISSUE THREAD

**Issue by buhuixiedaimade** [metersphere/metersphere#27327]
### MeterSphere 版本

2.10.8-lts

### 请描述您的需求或者改进建议

目前，在ms中执行测试计划中的用例，执行完用例的步骤后，还需要手动点击整条用例的结果。
建议在步骤结果全部标记后，自动更新用例的结果，如：
步骤都是通过，则用例结果标记为通过；
有失败的步骤，则用例结果标记为失败；
有阻塞的步骤，则用例结果标记为阻塞；
有跳过的步骤，则用例结果标记为跳过。
<img width="460" alt="image" src="https://github.com/metersphere/metersphere/assets/149168437/b5a7acf7-5a57-4ae0-b612-1663b0e62c6d">

**Comment by Hyyfit** [comment]
V3已规划
