### ISSUE TITLE
[BUG]API定义Case中的环境前置脚本没有执行

### ISSUE THREAD

**Issue by starzxzx** [metersphere/metersphere#27328]
### 联系方式

Meteresphere交流群41

### MeterSphere 版本

v1.20.22-lts 

### 使用外置数据库

否

### 问题描述

接口定义创建的case执行时，环境前置脚本没有执行

### 重现步骤

在接口定义创建API的Case，选择环境配置中的环境，执行后，应该是环境前置脚本生成的变量没有生成，也没有前置脚本相关的报错；相同环境在场景自动化中可以正确执行前置脚本

### 期待的正确结果

API定义中的Case可以执行前置脚本

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.8-lts无该问题，建议升级到最新版本尝试。

**Comment by starzxzx** [comment]
在官方版本上试用过了，确实没有问题
