### ISSUE TITLE
[BUG] 场景中引用环境变量，通过环境设置无法删除环境变量

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27338]
### MeterSphere 版本

v2.10.5-lts 

### 使用外置数据库

否

### 问题描述

场景中引用环境变量，通过环境设置无法删除环境变量

https://github.com/metersphere/metersphere/assets/40912189/73be1618-47e3-473f-b735-42eddbf76621

### 重现步骤

1、找一个环境E 添加参数A 值随便
2、新建一个场景 添加步骤自定义请求url中使用参数${A},选择环境E ，调试
3、观察请求提的url 是否替换了A的值
4、在选择环境的地方进入环境设置，删除环境E的变量A，点击确认
5、点击调试，观察自定义请求url中使用参数${A} 有没有被替换成删除的环境变量
6、如果${A}被替换成删除的环境变量，则问题复现完毕
7、否则多次重复上述步骤，直到复现为止，如果一直复现不了 可以联系我

### 期待的正确结果

保证正常的删除

**Comment by youliyuan-fit2cloud** [comment]
重复问题且最新版本v2.10.8-lts已解决。
