### ISSUE TITLE
[BUG]点击同步缺陷，ms上的缺陷创建人变为ms的系统管理员，数据库中creator变为admin。jira侧创建人是实际创建人

### ISSUE THREAD

**Issue by buhuixiedaimade** [metersphere/metersphere#27333]
### MeterSphere 版本

2.10.8-lts

### 使用外置数据库

否

### 问题描述

点击同步缺陷，ms上的缺陷创建人变为ms的系统管理员，数据库中creator变为admin。

### 重现步骤

1，使用个人账号在ms上创建jira缺陷，创建成功后查看ms上缺陷列表创建人，展示实际创建人；查看数据库issues表中creator展示实际创建人
2、点击同步缺陷，查看ms上缺陷列表创建人，展示为ms的管理员账号
3、查看数据库，creator变为admin
4、查看jira侧创建人，展示实际创建人
5、日志查看ms请求jira返回数据，creator和reporter均返回的是实际创建人信息

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。

**Comment by fit2cloud-yaochunrong** [comment]
2.10.11-lts版本此问题又出现了
