### ISSUE TITLE
[BUG] 偶现场景url使用环境变量不生效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27331]
### MeterSphere 版本

v2.10.5LTS

### 使用外置数据库

否

### 问题描述

偶现场景中某个请求的URL中使用环境变量不生效：具体请参考下图
<img width="811" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/5c22af23-4037-4833-9b35-3b3d239db331">

<img width="1022" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/15e5d13d-f280-4a97-a91a-cc68f3f8d778">

<img width="568" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/16f7f77c-a5cf-4991-8d90-9be9bc7eee1f">

<img width="878" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/84552551-914c-40f2-bcb4-4bb29f7e95d5">

### 重现步骤

无法复现，希望产品研发能协助分析原因所在，或提供指导意见

### 期待的正确结果

希望产品研发能协助分析原因所在，或提供指导意见

**Comment by 13290445582** [comment]
您好，感谢反馈，最新版v2.10.8版本未复现该问题，建议升级至最新版本尝试。

**Comment by 13290445582** [comment]
您好，最新版未复现该情况，建议升级最新版尝试，后续有问题请重新提issue，感谢理解与支持。
