### ISSUE TITLE
[FEATURE]轻量级浏览器插件，满足开发人员PC本地环境调试

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#27346]
### MeterSphere 版本

v2.10.8

### 请描述您的需求或者改进建议

开发人员本地PC服务调试的需求

目前Metersphere平台虽然node节点部署很灵活，但是大多数公司的服务器网络和OA办公网是单向的，即metersphere平台的不能范文开发人员本地服务

持续集成、持续测试背景下  开发人员在meterspher平台上的协同也至关重要，但开发人员的本地PC服务调试需求目前严重依赖网络，存在一定的壁垒，轻量化的浏览器插件是一个比较好的方案，不知是否考虑这块内容

**Comment by luty2018** [comment]
这个建议太好了， 我们也有规划， 只是不是以浏览器插件的形式，浏览器插件无法支持场景的调试， 可以期待我们的v3 版本

**Comment by zhangzhaox** [comment]
> 我们也有规划， 只是不是以浏览器插件的形式，浏览器插件无法支持场景的调试， 可以期待我们的v3 版本

非常期待，相对现成的市面上轻量级的插件，基于jmeter的轻量级客户端 功能肯定丰富更惊艳，值得期待
