### ISSUE TITLE
【BUG】使用并发控制器引用多个场景后，每个场景设置勾选原场景变量后没有生效

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27356]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

使用并发控制器引用多个场景后，每个场景设置勾选原场景变量后没有生效，场景中设置了相同的变量名称，引用会冲突。

### 重现步骤

1. 使用接口自动化场景中使用并发器，引用多个场景到并发控制器中，想要并发执行；
2. 但有的场景中设置了相同的变量名称，所以在每个场景设置中勾选了优先使用原场景变量；
3. 保存并调试，发现变量引用错误。

### 期待的正确结果

使用并发控制器引用多个场景后，每个场景设置勾选原场景变量后生效，场景中设置了相同的变量名称，引用不会冲突。

### 相关日志输出

```shell
无
```

### 附加信息

<img width="782" alt="1698807376150" src="https://github.com/metersphere/metersphere/assets/50016789/45651ba6-8824-4986-a445-470727a93874">
<img width="851" alt="1698807376163" src="https://github.com/metersphere/metersphere/assets/50016789/9df53541-2234-407c-a972-726dd300c443">
<img width="773" alt="1698807376179" src="https://github.com/metersphere/metersphere/assets/50016789/7dd0e600-932c-46f5-bdaa-ec740048554c">
<img width="862" alt="1698807376190" src="https://github.com/metersphere/metersphere/assets/50016789/a8c5bf6c-27d3-44d3-803f-6c1016fdfcd7">

**Comment by fit2-zhao** [comment]
暂时不支持并发控制器下的场景重名变量优先获取规则。
