### ISSUE TITLE
[BUG]接口测试-接口定义-接口列表-执行按钮,带特殊符号的标签被自动进行字符串分割

### ISSUE THREAD

**Issue by 449128388** [metersphere/metersphere#27353]
### 联系方式

449128388@qq.com

### MeterSphere 版本

v2.2.0-3ab59f7c

### 使用外置数据库

否

### 问题描述

完成编辑的接口点击接口列表中的执行按钮,带特殊符号的标签被自动进行字符串分割

### 重现步骤

1.在接口定义-接口列表-编辑接口页面中的标签中输入"V2.1R23C02"的标签
2.完成接口的编辑,返回接口列表
3.在接口列表点击【执行】按钮
4.进行【执行】按钮的编辑接口页面，发现"V2.1R23C02"的标签每一个都被进行了分割

### 期待的正确结果

进行【执行】按钮的编辑接口页面标签和接口列表中的保持一致

### 附加信息

![F7622839-151A-4900-886E-A9512F7DE09E](https://github.com/metersphere/metersphere/assets/35158962/b754d2c6-ab83-45d2-8125-29bad44b877e)
![3C3D3C0D-4C5D-47be-9ECA-8AA3EC6E41A5](https://github.com/metersphere/metersphere/assets/35158962/1adf10a8-06c5-4812-bfd0-12c15db5d3ff)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.8-lts未复现该问题，建议升级到最新版本尝试。
