### ISSUE TITLE
[BUG]上传功能用例-导入更新时未校验id重复，导致有重复的功能用例

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#27351]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

上传功能用例-导入更新时未校验id重复，导致有重复的功能用例

### 重现步骤

1. 功能用例 全部导出Excel，当前用例数为947
2. 将Excel中的STEP修改为TEXT，导入用例，选择导入更新，选择第1步导出的Excel
3. 查看页面显示的用例数，变为996
4. 再次导出用例，与步骤1的Excel进行比对，发现部分用例id重复，去重后用例数一致

### 期待的正确结果

导入新建和导入更新均可校验id重复

### 附加信息
![655da2f741bc9f2c6c1ed55fa4db389](https://github.com/metersphere/metersphere/assets/51410548/07c37348-9c1c-4f5a-a249-f532f84f0c8b)

_No response_

**Comment by 13290445582** [comment]
您好，在最新版本v2.10.8版本未复现该问题，建议升级至最新版本尝试。

**Comment by 13290445582** [comment]
您好，未在最新版复现该问题，建议升级最新版尝试，后续有问题请重新提issue，感谢理解与支持。
