### ISSUE TITLE
[BUG] 接口场景中，自定义步骤很多的时候，后置操作通过jsonpath提取参数会出现结果错乱的情况

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#27358]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口场景中，自定义步骤很多的时候，后置操作通过jsonpath提取参数会出现结果错乱的情况

https://github.com/metersphere/metersphere/assets/33945037/8e18bae9-5b5a-459e-bb1f-dc6009f622c8

还有一个页面交互的问题，当打开多个步骤详情的时候，会出现页面乱跑的情况。

### 重现步骤

1. 在接口场景中有多个自定义请求。
2. 调试通过之后，选择后置操作jsonpath提取，看弹出结果会有错乱情况。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。
反馈的页面交互问题在测试环境未复现，已修复问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。

**Comment by fit2cloud-lijiaxin** [comment]
v2.10.9 仍然出现
![0637cb9dbbeede612d849e1b27eadddf](https://github.com/metersphere/metersphere/assets/145318182/5e93cfd5-5ddb-4140-93f4-54ba32163e62)

**Comment by 2lipan** [comment]
在v2.10.9-lts版本上也有该问题
![image](https://github.com/metersphere/metersphere/assets/104960608/52bce1cd-e9e5-42db-9c51-871365b41e1b)
