### ISSUE TITLE
[BUG]性能测试-测试报告-测试详情，在执行中勾选结果指标，导出测试报告后，报告中没有展示对应的报告结果

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#27367]
### 联系方式

张树彬

### MeterSphere 版本

2.10.8LTS

### 使用外置数据库

否

### 问题描述

性能测试-测试报告-测试详情，在执行中勾选结果指标，导出测试报告后，报告中没有展示对应的报告结果

### 重现步骤

1. 打开执行完成的性能测试报告
2. 进入测试详情标签
3. 任意勾选几个结果指标
4. 点击导出报告
5. 查看导出的报告中，测试详情区域没有显示色选的指标结果

### 期待的正确结果

在测试报告中勾选测试详情指标后，导出的报告里可以展示对应的结果

### 附加信息

<img width="847" alt="b9cb626f9a211535816ae0ced7f425c" src="https://github.com/metersphere/metersphere/assets/77324661/c55c94d1-d759-4848-a287-fe733621f311">
<img width="660" alt="db4505128bcc4d96b1a1cc915b99a3b" src="https://github.com/metersphere/metersphere/assets/77324661/739f4eeb-216a-44f4-a324-188546ecb272">

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/22359
