### ISSUE TITLE
[BUG]为一条测试用例添加前置/后置用例时，搜索框左右两侧的数据不一致

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#27365]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.7-lts

### 使用外置数据库

否

### 问题描述

为一条测试用例添加前置/后置用例时，搜索框左右两侧的数据不一致

### 重现步骤

1、新增一条用例
2、为其增加前置用例
3、会发现菜单左侧的数据，与右侧筛选出来的数据不一致
4、在下图中可以看到，左侧总和30，右侧只有7条

### 期待的正确结果

左右两侧总和数据保持一致

### 附加信息

![IMG_20231101_154242](https://github.com/metersphere/metersphere/assets/56757548/e50ea755-8760-4f24-a403-961872b19a51)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
