### ISSUE TITLE
[BUG]全部用例数在用例菜单栏左右两侧数量不一致

### ISSUE THREAD

**Issue by kiwifruit-guo** [metersphere/metersphere#27366]
### 联系方式

kiwifruit.guo@qq.com

### MeterSphere 版本

 v2.10.7-lts

### 使用外置数据库

否

### 问题描述

全部用例数在用例菜单栏左右两侧数量不一致

### 重现步骤

1、观察项目左侧全部用例数
2、观察项目右侧全部用例数
3、二者不一致

### 期待的正确结果

二者一致

### 附加信息

![IMG_20231101_155231](https://github.com/metersphere/metersphere/assets/56757548/aba42d04-b26c-4cfd-b417-4b72114e60ae)

**Comment by 13290445582** [comment]
您好，最新环境未复现该问题，请升级最新版本尝试，若最新版问题仍在，您可以导出用例提供复现下，若不方便，可排查下是哪个模块数量不对，找到数量不一致的原因。

**Comment by kiwifruit-guo** [comment]
我试图排查，但是我没有定位到问题原因。如果您方便可以通过kiwifruit.guo@qq.com联系我

**Comment by 13290445582** [comment]
可能是有脏数据的存在。
依次进入左侧目录，对比每个目录的用例数量和列表显示的数量对比，找到出现两边数量不一致的目录，然后看下该目录列表显示实际上有几条用例。
看下可以找到是什么问题吗

**Comment by kiwifruit-guo** [comment]
我检查了每个目录的用例数，左侧展示的数字与右侧详情中用例总数是一样的

**Comment by 13290445582** [comment]
您好，一直未复现该问题，也没找到出现该情况的原因，请留意该问题，若产生复现步骤，可重新反馈，暂时关闭该issue，感谢理解与支持。
