### ISSUE TITLE
[BUG]偶现前置设置的变量，请求参数引用不生效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27377]
### MeterSphere 版本

v2.10.8-lts 

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/40912189/f4e5c9d1-5f23-4daf-8315-bdb99d898c6c

### 重现步骤

请联系我提供场景或者CASE用例

### 期待的正确结果

前置设置的变量，请求参数引用生效

**Comment by fit2-zhao** [comment]
`String requestQuery = sampler.getUrl().getQuery(); 
`
这段脚本原因，当执行`sampler.getUrl().getQuery();` 时， 请求sampler 的 url 就会开始解析，此时上下文变量中是没有signValue 变量的。
