### ISSUE TITLE
[BUG] 接口自动化列表数据，仅调试没有做修改操作，退出页面会提示保存

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27389]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

接口自动化列表数据，仅调试没有做修改操作，退出页面会提示保存

### 重现步骤

接口自动化列表数据，仅调试没有做修改操作，退出页面会提示保存

### 期待的正确结果

没有做操作应该不提示
![仅调试 没有修改 有保存提示](https://github.com/metersphere/metersphere/assets/43202800/b52e9e63-bde2-4987-9c51-fc06ce5a7184)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.9-lts优化。

**Comment by zrfit** [comment]
您好，经沟通，场景参数复杂，特殊参数也比较多，v3进行统一设计优化，感谢理解和支持。

**Comment by luty2018** [comment]
v3.0已支持。
