### ISSUE TITLE
[BUG] 接口测试，使用mock函数做了拼接 预览有效，但是放到请求体无效

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27383]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

接口测试，使用mock函数做了拼接 预览有效，但是放到请求体无效

mock拼接串：@county(true)@cword()@cword()@pick(['街','路']) @integer(1,100) 号。

![使用mock函数做了拼接，但是放到请求体无效](https://github.com/metersphere/metersphere/assets/43202800/a1993638-b3fc-475b-bbf1-4b458e169f88)

### 重现步骤

接口测试， 使用mock函数做了拼接 预览有效，但是放到请求体无效

### 期待的正确结果

接口测试请求体展示为mock函数值

**Comment by fit2-zhao** [comment]
执行参数解析较为复杂，暂时不支持这样拼接使用。
