### ISSUE TITLE
[BUG]测试计划，筛选用例执行人后再执行用例，在执行过程中数量会变少，有录屏

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27387]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

测试计划，筛选用例执行人后再执行用例，在执行过程中数量会变少，有录屏

### 重现步骤

1、创建测试计划，测试计划里面的执行人有多个
2、筛选某一个执行人 显示数据14条，执行过程标记 通过失败等，过一会儿列表莫名只展示5条数据

![筛选用例后再执行用例，在执行过程中数量会变少](https://github.com/metersphere/metersphere/assets/43202800/7e62f959-4348-4fb9-8639-4e7bbcc69101)

### 期待的正确结果

数据展示不变

**Comment by zrfit** [comment]
您好，感谢反馈！经沟通，已复现，计划v2.10.9-lts修复。

**Comment by 13290445582** [comment]
您好，考虑到性能问题，上一条下一条显示的数据实际也是跟列表一致是分页的，当每页10条，查询第11条时，会查询第二页的数据；当以执行人作为筛选条件时，由于执行时修改了部分数据的执行人，导致按当前筛选条件查询，总数发生变化，所以页面展示数据有变化
这个问题修改起来比较复杂，经过协商，v2不改动该处，v3解决，感谢您的理解与支持。

**Comment by Hyyfit** [comment]
3.0已规划
