### ISSUE TITLE
[BUG]MS删除项目后，issue表里的数据没有删除

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27384]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

删除项目后，该项目下新建的issue  数据表里没有被删除

### 重现步骤

1. 新建本地项目
2. 在缺陷管理处，新建缺陷
3. 在系统设置->项目管理 删除该项目
4. 查看数据库issue 表，仍然存在步骤2创建的缺陷数据

### 期待的正确结果

项目删除时，期望同步删除项目先缺陷

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
