### ISSUE TITLE
[FEATURE]建议服务重启后恢复执行未完成的测试计划

### ISSUE THREAD

**Issue by kkrrsq** [metersphere/metersphere#27380]
### MeterSphere 版本

v2.10.8-lts

### 请描述您的需求或者改进建议

当前服务重启后会结束未执行完成的测试计划，建议改成服务重启后恢复执行未完成的测试计划，继续将测试计划执行完成，避免因为服务意外重启而导致测试计划中断执行。

**Comment by liqiang-fit2cloud** [comment]
基于以下原因：
1. 技术上实现比较复杂，涉及到断点快照以及上下文的保存，目前还没有好的方案；
2. 很多测试计划从断点处继续执行会失败，可能是因为认证信息过期、被测系统不幂等之类的原因。
所以暂时没有做这个的计划。
