### ISSUE TITLE
[BUG]  测试计划-执行用例，按模块筛选执行人，批量修改属性后页面刷新停留得不是当前模块而是默认展示所有数据，并且再次却换到对应模块列表数量展示不对

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27386]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

  测试计划-执行用例，按模块筛选执行人，批量修改属性后页面刷新停留得不是当前模块而是默认展示所有数据

### 重现步骤

  1、测试计划-执行用例，按模块筛选执行人，批量修改属性
2、修改后列表页面自动刷新停留的是筛选后的所有数据，

不是当前模块而是默认展示所有数据，后续还需再筛一遍

### 期待的正确结果

停留在当前选中模块+当前选中执行人，而不是展示所有数据，

**Comment by xhy12** [comment]
![筛选后按模块切换，修改属性，修改后会跳到](https://github.com/metersphere/metersphere/assets/43202800/594eec09-97f8-4e4a-a9fc-6a6ac0e38459)

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/3377955f-87e8-4879-889e-dfe31b356b2e)
修改后刷新，再次切换模块列表数量展示不对

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
