### ISSUE TITLE
[BUG]  接口场景，导入case 选择，翻页不会记录，多页选了多条记录 最后只有最后一页的数据

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27391]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

接口场景，导入case 选择，翻页不会记录，多页选了多条记录
最后只有最后一页的数据

### 重现步骤

接口场景，导入case 选择，翻页不会记录，多页选了多条记录
最后只有最后一页的数据
![接口场景，导入case 选择，翻页不会记录，多页选了多条记录](https://github.com/metersphere/metersphere/assets/43202800/907f9d9a-3160-44fd-988e-503f69efe81e)

### 期待的正确结果

选择了几条，应该就带过去几条

**Comment by zrfit** [comment]
您好，感谢反馈！经沟通v3会增加该功能。

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
