### ISSUE TITLE
[FEATURE] ui测试元素定位 能不能参考做个图片识别定位，图片识别断言呢，操作和上手度会简便很多

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27393]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

ui测试元素定位 能不能参考做个图片识别定位，图片识别断言呢，操作和上手度会简便很多
就像影刀那总

**Comment by luty2018** [comment]
感谢建议， 我们有在调研这块的能力。

**Comment by liqiang-fit2cloud** [comment]
短期内没有方案也没有排期，先关闭。
