### ISSUE TITLE
[BUG] 接口测试ap编辑case 页面点击 返回箭头，跳转到了接口自动化页面，而不是停留在case列表。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27390]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

接口测试ap编辑case 页面点击 返回箭头，跳转到了接口自动化页面，而不是停留在case列表。
![点击返回上层，页面没有停留到当前页面 而是首页](https://github.com/metersphere/metersphere/assets/43202800/b1e04af8-69ab-4edc-a543-eb8b08c8e065)

### 重现步骤

接口测试ap编辑case 页面点击 返回箭头，跳转到了接口自动化页面，而不是停留在case列表。

### 期待的正确结果

按照操作层级逐级返回

**Comment by fit2-zhao** [comment]
感谢反馈，目前仅支持二级路由之间回退操作。
