### ISSUE TITLE
[BUG]接口自动化场景中，条件控制器在多次循环之后，判断不生效

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27405]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

1. 使用循环控制器里面定义了2次次数循环，
2. 然后再循环控制器里面添加条件控制器，
3. 调试执行发现条件控制器的判断会受上一次条件判断的结果影响

### 重现步骤

1. 使用循环控制器里面定义了2次次数循环，
2. 然后再循环控制器里面添加条件控制器，
3. 调试执行发现条件控制器的判断会受上一次条件判断的结果影响

### 期待的正确结果

条件控制器的判断不会受上一次条件判断的结果影响

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/a2eff359-cb06-4eec-82ff-04e3324b9e02)
![image](https://github.com/metersphere/metersphere/assets/50016789/ca9bff03-ff12-46f7-94ae-f3bc3c9607ff)
接口自动化场景：
[Metersphere_Scenario_zentao.json](https://github.com/metersphere/metersphere/files/13246708/Metersphere_Scenario_zentao.json)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by wxg0103** [comment]
您好  这个不是问题  由图可以看出  第一次的值是39 会存在一个变量为energySavingLightings的值
当第二次随机是值是73   会存在一个变量为normalLighting的值，因为是在一个线程里，现在两个变量会同时存在
所以当值为73的时候仍然会进入energySavingLightings的判断
