### ISSUE TITLE
[BUG]如果接口用例有加前置脚本，在转成性能测试用例后，MeterSphere性能报告的TPS数值与JMeter界面有差距

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#27418]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

不管是HTTP协议，还是TCP协议的接口用例，如果接口用例有加前置脚本，在转成性能测试用例后，在使用相同的压测服务的情况下，MeterSphere性能报告的TPS数值与JMeter界面有差距

### 重现步骤

把metersphere页面生成的 TCP_1698327587006.jmx 文件，下载到本地，
https://nginx-qa.fit2cloud.com/tmp/TCP_1698327587006.jmx

找到jmx文件中的cacheKey属性那一行，手动修改为
<stringProp name="cacheKey">true</stringProp>

这是修改后的 TCP_1698327587006_update.jmx 文件，
https://nginx-qa.fit2cloud.com/tmp/TCP_1698327587006_update.jmx

这是两个文件的对比，
<img width="808" alt="WX20231105-215717@2x" src="https://github.com/metersphere/metersphere/assets/18387151/89bb345b-0e06-4262-8c2e-a706f921e92f">

**临时解决办法是：**
在metersphere页面重新创建性能测试用例，导入刚才手动修改后的 TCP_1698327587006_update.jmx 文件，再执行压测，MeterSphere性能报告的TPS数值就可以与JMeter界面才能保持一致

### 期待的正确结果

不管是HTTP协议，还是TCP协议的接口用例，如果接口用例有加前置脚本，在转成性能测试用例后，在使用相同的压测服务的情况下，MeterSphere性能报告的TPS数值与JMeter界面要保持一致

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题经过进一步沟通，改动影响范围较大，解决时间待排期。

**Comment by jinyingone** [comment]
ElementUtil.initScript()
testElement.setProperty("cacheKey", false);
最好能提供一个配置入口，否则建议删除了
目前一台64核的机器，发压只能达到300qps，根本无法使用

**Comment by liuruibin** [comment]
我们在去年12月发布的版本v2.10.10-lts中提供了高级配置
<img width="2171" alt="image" src="https://github.com/user-attachments/assets/73324e7d-cb4e-4811-b2aa-a69264bb3f7f">

开启后会将脚本缓存起来

**即便如此，我们仍然建议性能测试中少使用脚本，不得已的情况也请使用beanshell代替jsr223**
