### ISSUE TITLE
[BUG] API响应体定义了多个状态码，文档列表没有展示完整

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27424]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

API响应体定义了多个状态码，文档列表没有展示完整
![image](https://github.com/metersphere/metersphere/assets/43202800/88752c81-7843-45e2-814d-63b2971ee7c3)

### 重现步骤

API响应体定义了多个状态码，文档列表没有展示完整

### 期待的正确结果

展示完整

**Comment by xhy12** [comment]
还有备注信息和依赖关系写了也不会在文档中显示

**Comment by youliyuan-fit2cloud** [comment]
你好，这个状态码默认只能加一个，你这个怎么实现有俩个？而且一般来说一个接口只有一种状态码。
问题2 ：备注和依赖关系不支持在文档中显示。

**Comment by xhy12** [comment]
反馈说是接口那里的状态这上面是研发写的备注，所以希望文档都展示以下

**Comment by youliyuan-fit2cloud** [comment]
> 反馈说是接口那里的状态这上面是研发写的备注，所以希望文档都展示以下

这没看懂呐。。。

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/5c80071a-6e7a-4c36-89ac-173769156fb5)
 zh状态码说明，是他们研发定义接口的时候写上去的，转成文档之后希望也展示出来，目前只展示了一个转台

**Comment by youliyuan-fit2cloud** [comment]
暂时不支持，如果有需求请提Feature给产品，感谢理解和支持～
