### ISSUE TITLE
功能用例关联了接口场景时，希望点击接口场景能够直接跳转到该条接口用例详情[FEATURE]

### ISSUE THREAD

**Issue by huhutouch** [metersphere/metersphere#27426]
### MeterSphere 版本

v2.10.6-lts-e87e920c

### 联系方式

381165483@qq.com

### 请描述您的需求或者改进建议

功能用例关联了接口场景时，希望点击接口场景能够直接跳转到该条接口用例详情

**Comment by luty2018** [comment]
感谢建议， 我们下个小版本加一下。

**Comment by huhutouch** [comment]
感谢，期待版本出来，希望metersphere越来越好~ 辛苦你们的付出啦~




huhu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 功能用例关联了接口场景时，希望点击接口场景能够直接跳转到该条接口用例详情[FEATURE] (Issue #27426)





 
感谢建议， 我们下个小版本加一下。

**Comment by luty2018** [comment]
<img width="1023" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/bd8c59c9-7495-4aa3-a10a-c075fc5bf873">
已经支持了， 欢迎更新版本使用！

**Comment by huhutouch** [comment]
收到，非常棒，这两天更新下
&nbsp;


huhu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月21日(星期二) 下午5:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] 功能用例关联了接口场景时，希望点击接口场景能够直接跳转到该条接口用例详情[FEATURE] (Issue #27426)





  已经支持了， 欢迎更新版本使用！
