### ISSUE TITLE
系统接口测试能够有统一断言的功能

### ISSUE THREAD

**Issue by qq741263802** [metersphere/metersphere#2742]
**请描述您的需求或者改进建议.**
系统接口测试能够有统一断言的功能，接口case中没有单独设置断言的就读取统一断言

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
接口自动化目前是支持场景级别的断言的，可以现在任意接口里加一条，然后拖拽到场景中

**Comment by qq741263802** [comment]
我试过了，不支持
