### ISSUE TITLE
[BUG] 升级版本后运行性能测试提示Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms7-jdk17

### ISSUE THREAD

**Issue by zhaojie-afk** [metersphere/metersphere#27432]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

**从v2.10.2升级到v2.10.8-lts后，使用页面上的性能测试，会报错，找不到镜像**：
Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms7-jdk17
![20231107-2](https://github.com/metersphere/metersphere/assets/76678700/3c2f24e6-3b44-4dcd-94b7-47271bfb36ac)

服务器上已经下载了相关镜像registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master        5.5-ms7-jdk17    
[
![20231107-1](https://github.com/metersphere/metersphere/assets/76678700/dbf668e4-e566-4ca6-8bfc-16b344ded771)
](url)

### 重现步骤

****从v2.10.2升级到v2.10.8-lts后，**

1. 运行页面上的性能测试，会报错，找不到镜像：
Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms7-jdk17

服务器上已经下载了相关镜像registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master        5.5-ms7-jdk17

**Comment by liuruibin** [comment]
您检查一下资源池节点上有没有这个镜像

**Comment by zhaojie-afk** [comment]
可以了，是资源节点上有一台没有升级最新版本
