### ISSUE TITLE
[FEATURE] 接口编排希望可以批量拖拽接口到控制器里面。目前一个一个拖很费时间

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27434]
### MeterSphere 版本

v2.6

### 请描述您的需求或者改进建议

接口编排希望可以批量拖拽接口到控制器里面。目前一个一个拖很费时间

我们一个场景的步骤有5-60步，引用完接口后添加控制器一个一个拖很麻烦

希望能个加个批量拖拽的功能

**Comment by luty2018** [comment]
感谢建议， 我们正在优化这块的交互
