### ISSUE TITLE
[FEATURE]建议接口CASE支持修改模板字段

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27440]
### MeterSphere 版本

v2.10.8-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

希望接口CASE也可以编辑模板，例如：增加这个CASE状态的选项值
![e127d08a-36cb-45ff-90b4-457e27114d06](https://github.com/metersphere/metersphere/assets/88763608/851224aa-fed1-4969-add7-6454f30fda4c)

**Comment by qian-kui** [comment]
期望能够和手工用例库一样有”前置操作“、”备注“的多文本字段。
当有的接口存在前置操作可以写在前置操作中
还有一些测试需要注意事项可以写在备注中。
