### ISSUE TITLE
[BUG]接口测试运行环境变量无法删除

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27449]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口测试运行环境变量无法删除

### 重现步骤

1.将附件中的环境导入MS的某个项目中
2.打开环境配置，搜索sign变量，然后删除并确定保存
![image](https://github.com/metersphere/metersphere/assets/88763608/99386105-0336-423b-b7f6-1174a306c613)
![image](https://github.com/metersphere/metersphere/assets/88763608/ef71e572-cdcd-40fc-969e-29f82efe7267)
![image](https://github.com/metersphere/metersphere/assets/88763608/814c7bd5-35d4-4258-aaf7-b7d74a3ac8ae)
3.再次打开环境配置，搜索sign变量，变量还存在
![image](https://github.com/metersphere/metersphere/assets/88763608/77a252a1-bca1-484c-9ee7-6874c78508a2)

![删除变量](https://github.com/metersphere/metersphere/assets/88763608/a2b831b5-9108-4c14-a2b7-0901cec2135a)

### 期待的正确结果

正常删除

### 附加信息

[MS_1_Environments (1).zip](https://github.com/metersphere/metersphere/files/13291409/MS_1_Environments.1.zip)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
