### ISSUE TITLE
[BUG][紧急]https接口请求，头部参数Content-Type为multipart/form-data类型时，每次请求boundary值会发生二次变化，若接口前置签名Content-Type，导致签名和接口实际请求的multipart/form-data中的boundary值不一致，最终签名失败，但通过jemter是可以固定boundary值

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#27445]
### MeterSphere 版本

v2.10.6-lts

### 使用外置数据库

否

### 问题描述

https接口请求，头部参数Content-Type为multipart/form-data类型时，每次请求boundary值会发生二次变化，若接口前置签名Content-Type，导致签名和接口实际请求的multipart/form-data中的boundary值不一致，最终签名失败，但通过jemter是可以固定boundary值

### 重现步骤

1、MS平台上，调用https接口请求，其中头部参数Content-Type为multipart/form-data类型的接口，固定boundary值
2、请求接口，MS控制台查看Content-Type的值，boundary会发生变化
3、boundary发生变化  导致使用Content-Type签名的接口会报签名异常，实际jemter上并不存在这样的问题，目前导致我们项目80%的接口无法上MS平台测试

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/69206282/1d4ccfa4-999c-4a9e-ae66-6b77f1b713c4)
![image](https://github.com/metersphere/metersphere/assets/69206282/1a9b3ee6-81f6-4832-961f-d4fb73907d67)

**Comment by 13290445582** [comment]
您好，请提供下复现的jmeter的jmx文件。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/48e074aa-1321-4f31-899d-ed60665cbf12)
不是这么写吗？你是怎们设置的固定boundary 值？

**Comment by 2115055005** [comment]
> 您好，请提供下详细的jmeter的jmx文件。
这里不支持上传jmx格式

**Comment by zh-ce** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/281242419-48e074aa-1321-4f31-899d-ed60665cbf12.png) 不是这么写吗？你是怎们设置的固定boundary 值？

通过HeaderManager headerManager = sampler.getHeaderManager() == null ? new HeaderManager() : sampler.getHeaderManager()
headerManager.add(new Header("Content-Type", "multipart/form-data; boundary=rwfUL_bpwLnxSZQjfmVda_Yar-dEtc"));  这种方法就可以处理这个boundary的值

通过这种方法在jmeter中就可以固定boundary的值，但是在MS中，最终发出去的请求还是会变化

**Comment by 2115055005** [comment]
> ![图像](https://user-images.githubusercontent.com/54612864/281242419-48e074aa-1321-4f31-899d-ed60665cbf12.png) 不是这么写吗？你是怎么设置的固定边界值？
直接写死，但是ms平台写死了 请求的时候也会变，并且发现  这个值应该是变换了2次

**Comment by 2115055005** [comment]
> 您好，请提供下面详细的jmeter的jmx文件。



> > ![image](https://user-images.githubusercontent.com/54612864/281242419-48e074aa-1321-4f31-899d-ed60665cbf12.png) 不是这么写吗？你是怎们设置的固定boundary 值？
> 
> 通过HeaderManager headerManager = sampler.getHeaderManager() == null ? new HeaderManager() : sampler.getHeaderManager() headerManager.add(new Header("Content-Type", "multipart/form-data; boundary=rwfUL_bpwLnxSZQjfmVda_Yar-dEtc")); 这种方法就可以处理这个boundary的值
> 
> 通过这种方法在jmeter中就可以固定boundary的值，但是在MS中，最终发出去的请求还是会变化

你们提供的这串代码   我们之前就试过了   还是请求的时候还是会变

**Comment by 2115055005** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/281242419-48e074aa-1321-4f31-899d-ed60665cbf12.png) 不是这么写吗？你是怎们设置的固定boundary 值？

写在前置脚本里的 ，直接ms页面请求头那里设置  我们也尝试过

**Comment by 2115055005** [comment]
> > 您好，请提供下面详细的jmeter的jmx文件。
> 
> > > ![image](https://user-images.githubusercontent.com/54612864/281242419-48e074aa-1321-4f31-899d-ed60665cbf12.png) 不是这么写吗？你是怎们设置的固定boundary 值？
> > 
> > 
> > 通过HeaderManager headerManager = sampler.getHeaderManager() == null ? new HeaderManager() : sampler.getHeaderManager() headerManager.add(new Header("Content-Type", "multipart/form-data; boundary=rwfUL_bpwLnxSZQjfmVda_Yar-dEtc")); 这种方法就可以处理这个boundary的值
> > 通过这种方法在jmeter中就可以固定boundary的值，但是在MS中，最终发出去的请求还是会变化
> 
> 你们提供的这串代码 我们之前就试过了 还是请求的时候还是会变

![image](https://github.com/metersphere/metersphere/assets/69206282/5cb2ba05-5f47-4f04-b74e-0507d278301f)

**Comment by 13290445582** [comment]
> > 您好，请提供下详细的jmeter的jmx文件。
> > 这里不支持上传jmx格式
将您的jmx文件打压缩包上传或者可以发送到我邮箱，yicheng.wang@fit2cloud.com

**Comment by 2115055005** [comment]
> yicheng.wang@fit2cloud.com

已发送 请查收

**Comment by 13290445582** [comment]
您好，jmeter 5.5版本以上的boundary值都是随机的，我们基于jmeter 5.5版本的，暂不支持固定boundary值，感谢理解。
