### ISSUE TITLE
[FEATURE]excel测试用例导入，步骤描述自行分格

### ISSUE THREAD

**Issue by LightDusts** [metersphere/metersphere#27448]
### MeterSphere 版本

v2.10.8-lts

### 联系方式

MeterSphere 交流群68  轻

### 请描述您的需求或者改进建议

步骤描述一开始也不会清楚知道有多少个步骤，如果按模板来还需要不断合并、拆分单元格。为什么不能自动分，我记得以前版本是有的
![Snipaste_2023-11-08_10-04-01](https://github.com/metersphere/metersphere/assets/130635668/2f4eb0ea-76f5-48b1-a7da-98cfd8e8fd84)
![Snipaste_2023-11-08_10-05-15](https://github.com/metersphere/metersphere/assets/130635668/e5b1d310-c860-408a-99fd-4467ab4e5d7e)

**Comment by Hyyfit** [comment]
您好，https://github.com/metersphere/metersphere/issues/25705
因为这个问题，我们在2.10.6的版本，将步骤描述改为根据标识[1] [2] [3]...来判断是否将单元格拆分为多个步骤，没有则为一个步骤；
