### ISSUE TITLE
建议接口测试可以增加批量修改请求参数功能

### ISSUE THREAD

**Issue by qq741263802** [metersphere/metersphere#2744]
**请描述您的需求或者改进建议.**
建议接口测试可以增加批量修改请求参数功能，例如需要批量修改请求头信息或QUERY参数 ，就要一个个改，比较慢

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后面版本可以添加改功能

**Comment by xulinde** [comment]
v1.13已支持
