### ISSUE TITLE
[BUG]v2.10.6版本上传接口使用附件，附件名称存在中文附件会错误返回问号？？

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#27454]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

附件名称存在中文附件会错误返回问号？？

### 重现步骤

附件名称使用中文或者含有中文的附件
使用上传接口，上传到系统上附件就是问号这种

### 附加信息

群同事反馈：目前MeterSphere使用的JMeter5.5版本不支持中文文件名，所以会出现问号
![image](https://github.com/metersphere/metersphere/assets/79577571/b5547d10-fbeb-45a8-b124-92952bc9bff2)

**Comment by 13290445582** [comment]
您好，jmeter 5.6 以上才支持中文文件名，我们v2.10-lts用的是jmeter 5.5，v2不再升级jmeter版本，感谢您的理解与支持。
