### ISSUE TITLE
[FEATURE]创建/编辑接口用例页面，期望用例名称框给大一点方便编辑时候使用

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#27453]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

接口用例页面，用例名称框太小了，尤其更新名称的时候很费劲

### 请描述你建议的实现方案

期望给长一点位置，方便编辑期间就可以直接看完整

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/79577571/4997f52c-0542-4338-b611-e1986c7e138f)

**Comment by luty2018** [comment]
这个我们已经规划在v3.0版本了， 会对整个页面进行交互优化
