### ISSUE TITLE
[BUG]接口调试中有token、uid、did等参数，调试报401，其他接口平台调试正常。最后，在调试过程请求体参数放到json-执行一遍，再切回x-www-from-urlencoded调试就正常了

### ISSUE THREAD

**Issue by QAqa123** [metersphere/metersphere#27462]
### 联系方式

MeterSphere 交流群68-Trust

### MeterSphere 版本

版本:   1.0.1

### 使用外置数据库

否

### 问题描述

接口调试中有token、uid、did等参数，调试报401，其他接口平台调试正常。最后，在调试过程请求体参数放到json-执行一遍，再切回x-www-from-urlencoded调试就正常了

### 重现步骤

1.在请求体-x-www-from-urlencoded下输入参数token、uid、did等参数
2.开始调试，出现401报错

**Comment by 13290445582** [comment]
您好，请问是在最新版本v2.10.8复现的吗？
报错401是否是token过期了，使用新的token可以调通吗？请检查
可以提供下有效的复现场景帮助复现下（包括请求、环境、参数），感谢支持。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。最新版本v2.10.9已发布，建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
