### ISSUE TITLE
[BUG]提取参数时，如果有URL地址，URL地址会被转义，无法正常使用

### ISSUE THREAD

**Issue by Tannii** [metersphere/metersphere#27465]
### 联系方式

941177402@qq.com

### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

问题描述：推荐类型提取，提取返回结果参数，如果提取参数中有URL的，URL会被转义，无法使用，如图
![e63ce5b8558ae61392b5b87cbdadd61](https://github.com/metersphere/metersphere/assets/34464876/e81ef9dd-cf8a-4350-bcd0-296a71d83ee8)
![1f58f1219c545d21f9cf044f39672fb](https://github.com/metersphere/metersphere/assets/34464876/7b44f35c-53fb-44df-a614-9ff23bf23244)

### 重现步骤

1.提取有URL的返回结果

**Comment by Tannii** [comment]
![92dfe0740c5e60159c34f7fdc59a3f8](https://github.com/metersphere/metersphere/assets/34464876/aee61ad9-9120-487a-b771-9b8d72813e23)
提取结果

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，我们是基于jmeter 5.5版本实现的，经过在jmeter 5.5版本上复现，jmeter提取到的也是转译后的，因此与jmeter保持一致，感谢理解。
