### ISSUE TITLE
[BUG]性能测试编辑场景时，上传jmx脚本时找不到脚本，导致在编辑状态下，同一个jmx文件或者文档无法重新上传，但是项目文件中有jmx文件

### ISSUE THREAD

**Issue by Liya-ou** [metersphere/metersphere#27466]
### 联系方式

13253771258@qq.com

### MeterSphere 版本

 v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

操作步骤：
1、编辑性能压测场景
2、删除加载文件
3、点击加载jmx文件按钮
4、找不到已经上传的jmx文件和其他文件，但是项目文件中有
如图：
![image](https://github.com/metersphere/metersphere/assets/121922410/1b6b3c91-c1b6-4e5a-94ff-ae011691fc4d)
![image](https://github.com/metersphere/metersphere/assets/121922410/13aeba34-1cbd-45d6-afba-9107f7ad85dc)
![image](https://github.com/metersphere/metersphere/assets/121922410/671a356b-b3fe-4b5e-b545-ea068424d105)
![68d0d28977e58dd31f7835f5c5422db6](https://github.com/metersphere/metersphere/assets/121922410/12d5ec15-05ad-4f79-bff8-9f106ff7fe90)

### 重现步骤

如图：
![image](https://github.com/metersphere/metersphere/assets/121922410/1b6b3c91-c1b6-4e5a-94ff-ae011691fc4d)
![image](https://github.com/metersphere/metersphere/assets/121922410/13aeba34-1cbd-45d6-afba-9107f7ad85dc)
![image](https://github.com/metersphere/metersphere/assets/121922410/671a356b-b3fe-4b5e-b545-ea068424d105)
![68d0d28977e58dd31f7835f5c5422db6](https://github.com/metersphere/metersphere/assets/121922410/12d5ec15-05ad-4f79-bff8-9f106ff7fe90)

### 期待的正确结果

期待：编辑的时候可以删除和修改jmx脚本和其他文件，致使重新上传jmx和其他文件

**Comment by 13290445582** [comment]
您好，用法就是这样的，删除该jmx文件后需要保存，再点击加载jmx文件可显示出删除的jmx了。
