### ISSUE TITLE
[BUG]接口测试。sql查出来的list，现在获取不到整个list

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27469]
### MeterSphere 版本

v2.10.8

### 使用外置数据库

否

### 问题描述

1.接口测试使用sql脚本，查出list无法获取到整个list

### 重现步骤

<img width="1020" alt="f30572af94132205ec530c2ec18c00b" src="https://github.com/metersphere/metersphere/assets/55130444/3c17a0b5-27b5-4050-8058-b50ab6bb4ef8">
<img width="727" alt="8fb40b98bcf522f67e5816e95d81a5e" src="https://github.com/metersphere/metersphere/assets/55130444/b07ac848-a991-4170-b36d-f3dfb4457210">
<img width="469" alt="94c174c13d8811b5b1565c8b5e106ab" src="https://github.com/metersphere/metersphere/assets/55130444/61acaa36-9b4a-4234-b989-a4cfe66fad6a">

### 期待的正确结果

1。sql查出来的list可以整个获取到

**Comment by fit2-zhao** [comment]
按列存储暂时没有 xxx_ALL 这种变量用法，在上下文中的变量只有 xxx_1 ｜ xxx_2 这种根据索引的。
