### ISSUE TITLE
上传大于50M以上会报错

### ISSUE THREAD

**Issue by 11374493** [metersphere/metersphere#27475]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

[BUG]上传大于50M以上的文件就会报网关错误

### 重现步骤

上传和发送接口消息文件大于100M以上

### 期待的正确结果

希望有个配置能控制文件大小

### 相关日志输出

```shell
{
    "success": false,
    "message": "Connection has been closed BEFORE response, while sending request body",
    "data": null
}
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/143389545/5c3bf236-0f39-4813-94bf-4d2dc71d1ac6)

**Comment by 13290445582** [comment]
您好，上传文件最大限制为50MB，不支持控制文件大小，若有此需求，可提需求讨论，感谢理解与支持。
