### ISSUE TITLE
[BUG] 【接口测试】测试计划定时执行，接口场景用例会出现获取不到环境配置的SLL证书

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#27470]
### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

有个项目接口是加密的，需要配置SSL证书，将SSL证书上传到Metersphere环境配置里，然后在接口自动化单独执行场景是正常的，接口无任何报错，但创建一个测试计划，将场景加入到测试计划中，使用默认环境定时执行偶发出现接口找不到证书报错，出现概率超过50%，报错信息如下：
javax.net.ssl.SSLException: No PrivateKey found for alias:'1'

### 重现步骤

1.在环境配置中上传SSL证书
2.创建一个自动化场景，在场景中加入加密接口
3.将接口调试通过
4.创建一个测试计划，加入刚调式好的自动化场景，环境选择默认
5.设置定时任务执行
6.观察接口是否报错

### 期待的正确结果

接口定时任务执行无报错

### 附加信息

1.环境配置SSL证书
![image](https://github.com/metersphere/metersphere/assets/45531073/b7d4f52d-f096-446b-b4f0-81df08c87251)

2.接口自动化场景单独执行
![image](https://github.com/metersphere/metersphere/assets/45531073/fbaeb27e-13e7-4568-9cab-d49944b57205)
3.测试计划定时执行
![image](https://github.com/metersphere/metersphere/assets/45531073/be70f460-4fba-4b78-9f23-9c6c591635b9)

**Comment by 13290445582** [comment]
您好，请提供下接口环境和SSL证书，可发送至我的邮箱yicheng.wang@fit2cloud.com

**Comment by Larson13** [comment]
> 您好，请提供下接口环境和SSL证书，可发送至我的邮箱[yicheng.wang@fit2cloud.com](mailto:yicheng.wang@fit2cloud.com)
SSL证书涉及生产环境，我先协调下

**Comment by 13290445582** [comment]
已修复，请升级至v2.10.10版本测试。
