### ISSUE TITLE
[BUG]接口响应体太大，执行后会一直卡在 running

### ISSUE THREAD

**Issue by kkrrsq** [metersphere/metersphere#27479]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

如果一个接口的响应体太大，执行后就会一直卡在 running ，如果是测试计划，那执行到这个用例后就会一直卡住，不会往下继续执行。造成这个问题的原因是响应体超过了 kafak 消息大小限制，导致 controller kafka 消息发送失败。
临时解决方案，可以调大 kakfa 消息大小配置，但这并不是一种很好的解决方案。一个是接口最大响应体大小无法确定，一个是如果 kafka 消息大小限制调太大可能会影响 kafka 性能。
请问一下是否有更合理的解决方案？比如响应超过大小限制就把响应数据截断？或者报错？至少不应该失败直接不处理，导致执行一直卡在 running

### 重现步骤

1.构造一个响应体大于 50M 的请求（假设 kafak 配置的消息大小限制是 50M）
2.执行请求，请求就会一直卡在 running
3.查看 controller 日志，可以发现 kafka 推送结果异常的报错

**Comment by 13290445582** [comment]
您好，该问题的解决方法就是您所描述的操作，暂无其他方案，感谢理解与支持。
