### ISSUE TITLE
[FEATURE]sql查询出来的list，希望支持获取全部数据

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27488]
### MeterSphere 版本

v2.10.8

### 请描述您的需求或者改进建议

sql查询出来的list，希望支持获取全部数据。
背景：目前sql查询出来的list，只能通过${变量名_1}，类似这种方式获取到其中的某一个值，洗碗可以支持${变量名_ALL} 获取所有值
### 请描述你建议的实现方案
是不是可以参考 后置jsonpath提取全部值的时候，支持${变量名_ALL} 方式获取全部值。

_No response_

**Comment by luty2018** [comment]
jmeter不支持这种用法， 目前我们也没有计划扩展这个能力
