### ISSUE TITLE
[BUG] 升级jmeter镜像所带的wget

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#27489]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

在通过某个独立的node资源池执行性能测试的时候，提示下载出错（无法成功建立连接），如下图。
进入jmeter容器手动执行wget下载也是同样的错误，但是ping地址显示网络是通的，并且443端口也通，而且用curl命令是可以成功下载的。node controller容器和所在虚机也均能下载成功。
此资源池node节点与MS服务器属于不同的网段，其他资源池能正常执行性能测试。
![1699544056074](https://github.com/metersphere/metersphere/assets/24548477/41e03073-bb5b-4df4-8da7-5291ea3ea36b)

**后来通过docker build 将jmeter-master镜像的wget版本升级到1.21（从https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/ 下载）， 就可以成功运行。**
$ wget -V
GNU Wget 1.21.4 built on linux-musl.

---------------------------------------------------------------------------
另外，目前jmeter镜像所带的wget版本所支持的参数非常有限，如缺少-d(debug) 和--no-check-certificate参数，也不利于排查。
$ wget -v （目前所带的wget参数）
wget: unrecognized option: v
BusyBox v1.36.1 (2023-07-27 17:12:24 UTC) multi-call binary.

Usage: wget [-cqS] [--spider] [-O FILE] [-o LOGFILE] [--header STR]
        [--post-data STR | --post-file FILE] [-Y on/off]
        [-P DIR] [-U AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

        --spider        Only check URL existence: $? is 0 if exists
        --header STR    Add STR (of form 'header: value') to headers
        --post-data STR Send STR using POST method
        --post-file FILE        Send FILE using POST method
        -c              Continue retrieval of aborted transfer
        -q              Quiet
        -P DIR          Save to DIR (default .)
        -S              Show server response
        -T SEC          Network read timeout is SEC seconds
        -O FILE         Save to FILE ('-' for stdout)
        -o LOGFILE      Log messages to FILE
        -U STR          Use STR for User-Agent header
        -Y on/off       Use proxy

基于以前2个方面考虑，建议升级jmeter镜像所带的wget

### 重现步骤

N/A

**Comment by liuruibin** [comment]
wget 在我们的镜像中仅仅作为下载执行zip用的，如果您需要其他功能可以写一个`Dockerfile` 进行扩展
```
FORM registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms7-jdk17
RUN apk add xxx 
```
