### ISSUE TITLE
[BUG]集成禅道提交缺陷问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#27499]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

提交禅道缺陷，使用截图贴到富文本框，点击保存，全量同步后，图片丢失。

### 重现步骤

1.集成禅道插件（包括设置禅道信息，项目关联等），版本为最新版本
2.进入缺陷管理页面，点击创建缺陷
3.填写其他必填信息。
4.随便截个图，复制到富文本框描述中。
5.点击保存（这时候还是有图片的）
6.到缺陷列表页面，点击全量同步（时间选择可以同步上述创建的缺陷即可，最好时间节点长一点，确保可以同步到上面创建的缺陷）。
7.同步完成，再次查看缺陷，图片丢失（本地上传附件好像也有此问题）

### 期待的正确结果

图片可以正常显示

**Comment by 13290445582** [comment]
您好，在缺陷内容处 上传图片 与 直接粘贴图片 同步缺陷已复现该问题，计划于v2.10.9版本修复，上传附件无此问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
