### ISSUE TITLE
[BUG]  【接口测试】升级到最新版本，前置脚本获取不到环境配置中变量值

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#27504]
### MeterSphere 版本

v2.10.8

### 使用外置数据库

否

### 问题描述

 有个项目的环境配置ip使用的是变量，变量值在通用变量配置的，执行自动化测试时，需要使用前置脚本获取环境中的ip，然后在脚本中调用依赖接口，未升级前，IP使用变量时，脚本可以获取到ip值，升级后，脚本无法获取变量的值，IP换成固定值，脚本可以正常获取

### 重现步骤

1.进入环境配置，在通用配置中设置变量ip和值
2.然后进入http配置中，将ip进行参数化
3.在接口中加入前置脚本获取ip的值
4.执行自动化脚本
5.在控制台观察是否获取到 ip值

### 期待的正确结果

ip使用参数化时，前置脚本可以获取到ip的值 

### 附加信息

第一步  将IP参数化
![image](https://github.com/metersphere/metersphere/assets/45531073/cd061cf2-1143-4a4c-9e2f-959b7def3d45)
![image](https://github.com/metersphere/metersphere/assets/45531073/523466a2-3122-4088-997c-a8e89035df9e)
第二步 前置脚本获取ip值
![image](https://github.com/metersphere/metersphere/assets/45531073/87f4288d-c0e2-47ee-8610-f91c91060992)
第三步  执行自动化脚本
![image](https://github.com/metersphere/metersphere/assets/45531073/6ddefe00-791c-45f1-9ac5-2b8111cdb000)

将IP换成固定值，执行场景可以获取到ip值
![image](https://github.com/metersphere/metersphere/assets/45531073/641d38ae-f7cc-4d5e-af77-b2c97538c2cf)

![image](https://github.com/metersphere/metersphere/assets/45531073/11252c12-6730-4e9a-8354-b68450ada68d)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，经过反馈，该用法已不支持，因为不知道变量是纯ip还是会有端口，执行之前拿不到，只能执行的时候拿到，导致可能引发其他问题，已不支持如此使用，感谢理解与反馈。
