### ISSUE TITLE
[BUG]项目环境上传csv文件保存后，文件预览显示为空

### ISSUE THREAD

**Issue by wangdeyu007** [metersphere/metersphere#27503]
### 联系方式

15004323835

### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

否

### 问题描述

项目环境上传csv文件保存后，文件预览显示为空。

### 重现步骤

项目环境上传csv文件保存后，文件预览显示为空。

### 期待的正确结果

显示csv文件预览

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
