### ISSUE TITLE
[FEATURE] POST `application/json` 希望支持对参数进行描述，便于前后端联调

### ISSUE THREAD

**Issue by imyzt** [metersphere/metersphere#27516]
### MeterSphere 版本

v2.10.0-lts-89acace0

### 请描述您的需求或者改进建议

`application/json` 无表格形式展示描述（不方便前后端联调）
![image](https://github.com/metersphere/metersphere/assets/28680198/2c276a1d-a645-4dc3-9341-4fc24f5c8064)

希望能够通用使用`application/x-www-form-urlencoded`模式的表格描述字段
![image](https://github.com/metersphere/metersphere/assets/28680198/aed9af58-af60-4b05-9ff3-aabcc597261c)

### 请描述你建议的实现方案

希望能够通用使用`application/x-www-form-urlencoded`模式的表格描述字段
![image](https://github.com/metersphere/metersphere/assets/28680198/aed9af58-af60-4b05-9ff3-aabcc597261c)

**Comment by luty2018** [comment]
感谢建议， 我们在v3版本会升级组件，支持在代码编辑器内添加注释。

**Comment by luty2018** [comment]
<img width="1114" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/d9095dcc-7bab-476c-bac0-843924ab9507">
v2 在高级中勾选描述即可

![image](https://github.com/metersphere/metersphere/assets/36292514/9f6f85ff-ed58-4306-a339-e22093e68e7e)

v3在列表中已提供描述，可以升级使用
