### ISSUE TITLE
[BUG]【接口自动化】场景变量为内置函数time，之后添加循环控制器，每次循环出来的时间都是一样的。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27529]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景变量为内置函数time，之后添加循环控制器，每次循环出来的时间都是一样的。

### 重现步骤

【接口自动化】场景变量为内置函数time，之后添加循环控制器，每次循环出来的时间都是一样的。
![ac978faedc46ce0c49aa6adb3588c1a](https://github.com/metersphere/metersphere/assets/104960608/04052769-cfbf-4384-9414-1d611c572fce)
![e654693328fe0a73623619d65b6fd05](https://github.com/metersphere/metersphere/assets/104960608/87c6b9bd-6135-428f-b227-5981dcfffc88)
![eef53c45cc8a1bca7f7f6050f5dbe19](https://github.com/metersphere/metersphere/assets/104960608/992674a0-9752-4a36-829c-5a3892f62ce5)

**Comment by fit2-zhao** [comment]
你固定成一个场景变量（用户自定义变量）后只会解析一次，如果想每次都改变就直接把变量写到请求上就行。

![image](https://github.com/metersphere/metersphere/assets/70558837/33fc4cb5-e060-44b8-8be6-94c159afa529)
