### ISSUE TITLE
[BUG]功能用例-批量编辑，自定义字段字段类型为文本框时，无法编辑

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27533]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

功能用例-批量编辑，自定义字段字段类型为文本框时，无法编辑，在功能用例批量编辑时不显示该自定义字段

### 重现步骤

1. 创建自定义字段，字段类型为文本框，项目设置选择该模板
![image](https://github.com/metersphere/metersphere/assets/103627487/da5074e7-b3d3-4bc5-84ce-1d1a3b7d846f)
2.功能用例，批量编辑，不显示该自定义字段
![image](https://github.com/metersphere/metersphere/assets/103627487/aaea8634-31f2-4942-9492-1fabed4badec)

**Comment by 13290445582** [comment]
您好，设计上功能用例列表处不显示文本框与富文本框类型字段，所以批量编辑时无法编辑文本框与富文本框类型字段，感谢理解。
