### ISSUE TITLE
[FEATURE] 希望结果里的响应时间图等可以和Jmeter一样调节时间间隔

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2753]
**请描述您的需求或者改进建议.**
    在界面上查看响应时间图等结果时，发现不能调节图的采样点的时间间隔，当压测时间很长时，折线图感觉就像糊了一样，看不清楚。
![image](https://user-images.githubusercontent.com/42863606/117973714-4d97ef80-b35f-11eb-9ead-31e2d4794236.png)

**请描述你建议的实现方案**
    建议可以设置成每隔多少ms显示一个点，或一共显示多少个点的选项（两个都可能会用到），这样的话，折线图就不会密密麻麻的看不清了。每个图是否可以单独设置、折线的粗细调节、采样点是否显示圆圈标志、配色等，需要你们调研了。希望能尽可能贴近Jmeter的效果，压测报告图表的效果有时也需要考虑

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/117981351-80de7c80-b367-11eb-9778-7d24183e356d.png)
你好，目前可以在创建测试时的高级配置中进行修改。

**Comment by goteen** [comment]
具体的采样间隔或取样数量在部分场景下是不确定的，如果在这里修改，就需要反复压测尝试，这样的话很影响效率；
而且这里的值只能选，不能自己填，有的时间间隔还需要计算得到（所以有的时候设置显示几个点就很有用）；
Jmeter的时间间隔精度是毫秒，MeterSphere精确到秒，部分场景下可能需要更精细的值。
