### ISSUE TITLE
[BUG]性能测试计算时长，取决于ms服务器和压力机服务器的时间，如果压力机服务器时间不对的话，计算时长会产生很大偏差

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2754]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9
**Bug 描述**
简要描述您碰到的问题
性能测试计算时长，取决于ms服务器和压力机服务器的时间，如果压力机服务器时间不对的话，计算时长会产生很大偏差
**Bug 重现步骤**
1.  ms主服务器时间
![image](https://user-images.githubusercontent.com/30038088/118013270-85655e00-b384-11eb-8a0f-e1f423f917a7.png)

2.
ms主服务的时间正常 为 2021/05/13 00:27:44
压力机1 时间 2021/05/13 12:03:34
压力机2 时间 2021/05/13 15:03:34
压力机3 时间 2021/05/13 00:27:44

4. 

**期待的正确结果**
正确情况下应该是什么样的？
开始时间和结束时间 应该都以 主服务器时间为准。
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们内部讨论一下

**Comment by zyyfit** [comment]
您好，暂时建议您部署的时候统一各个机器的时间
