### ISSUE TITLE
[BUG]  xmind里有特殊符号，导致导入功能用例失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27543]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

xmind里有特殊符号，导致导入功能用例失败

### 重现步骤

xmind里面的文本有<=符号，导入失败，删除了就好了
![42ebf763f53b81bb09cc5d0b1ab5186](https://github.com/metersphere/metersphere/assets/103925124/c27ccf1a-2298-4531-8009-e733172a73ad)

![e7e7bc5a9f511633ecb5b457512d488](https://github.com/metersphere/metersphere/assets/103925124/63c4164b-ea47-4a62-b38c-def8bb55504a)
手动转义仍失败
![image](https://github.com/metersphere/metersphere/assets/103925124/a7bde7ac-434c-460f-bcb6-d0f6a30f2f95)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
