### ISSUE TITLE
[BUG]创建用户组页面字段含义和选项值存在差异

### ISSUE THREAD

**Issue by HolyHorseman** [metersphere/metersphere#27552]
### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

否

### 问题描述

![1699949926310](https://github.com/metersphere/metersphere/assets/12827492/bdf6755a-a3d0-42f5-9340-c8aa6295fd49)
创建用户组页面，字段“所属项目”，选项值“工作空间”

### 重现步骤

页面操作可见

### 期待的正确结果

字段名称应为“所属工作空间”

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个版本会修复该问题。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级最新版本v2.10.9尝试。
