### ISSUE TITLE
[BUG]批量添加用户到工作空间异常

### ISSUE THREAD

**Issue by HolyHorseman** [metersphere/metersphere#27557]
### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/12827492/5737f7a9-aa59-4e6a-a0f5-10a0faa40fab)

### 重现步骤

1. 将已有工作空间的用户与未分配工作空间的用户选中；
2. 点击批量添加到工作空间；
3. 未分配工作空间的用户没有被添加到指定工作空间；

### 期待的正确结果

跳过已有工作空间用户，将未分配的工作空间的用户添加到目标工作空间。

### 附加信息

另一种场景：
1. 工作空间A，工作空间B，用户A在工作空间A，用户B未分配工作空间；
2. 选中用户A和B，批量添加到工作空间B；
3. 结果未知，未测试；

**Comment by 13290445582** [comment]
<img width="632" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/7e2df165-db55-4ac7-92f5-97d5178bd628">
<img width="649" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/e0c5d29d-8f10-4324-a334-1622040edda2">
您好，未复现您所描述的这种情况。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。最新版本v2.10.9已发布，建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
