### ISSUE TITLE
[BUG]接口测试，后置操作使用正则表达式提取参数，无法提取出内容

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27565]
### MeterSphere 版本

v2.10.8

### 使用外置数据库

否

### 问题描述

接口测试，后置脚本使用正则表达式提取参数，无法提取出内容。

### 重现步骤

1.mock一个响应结果。
{"code":0,
    "data":[
        {
            "id":"123",
            "notice":{
                "tts":"中午的时光，让我们一起沉淀心灵，享受宁静。",
                "dtid":"test"
            }
            
        }]
}
2.后置操作使用正则提取tts。  [\u4e00-\u9fa5]+，+[\u4e00-\u9fa5]+，[\u4e00-\u9fa5]+。
![image](https://github.com/metersphere/metersphere/assets/55130444/5d91253e-fd2d-41ed-bd5a-4e99d2f8af61)

3.实际在正则表达式网站上可以提取到内容。
![image](https://github.com/metersphere/metersphere/assets/55130444/c2e5f676-bba7-4f60-8603-637280c38361)

### 期待的正确结果
可以使用正则提取出想要的内容。
_No response_

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/3da65f45-4eea-44b3-ac65-20eac9461c13)

你好，我使用上述正则提取没问题。
以下ChatGPT回答：而且正则表达式用于匹配文本模式，而不是直接从结构化数据（如 JSON）中提取值。对于处理结构化数据（如 JSON），使用专门的 JSON 解析器和查询工具（如 JSONPath 解析器）通常比使用正则表达式更有效和可靠。这些工具能够更好地处理嵌套结构、数据类型转换等问题。因此，如果你要处理的是 JSON 数据，最好使用适当的 JSON 解析器和查询库，而不是仅依赖正则表达式。
