### ISSUE TITLE
测试用例编写脑图方式，mac电脑拖动某个字段，屏幕就找不到了[BUG]

### ISSUE THREAD

**Issue by xiaomi9025** [metersphere/metersphere#27560]
### 联系方式

zhenghonglei@ymt360.com

### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

是

### 问题描述

mac chrome客户端，测试用例编写，拖动某个字段，拖出屏幕外，很难操作再拉回来。

### 重现步骤

mac chrome客户端，测试用例编写，拖动某个字段，拖出屏幕外，很难操作再拉回来。

**Comment by 13290445582** [comment]
您好，不太理解所描述的操作是什么情况，可以提供下录屏。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。最新版本v2.10.9已发布，建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
