### ISSUE TITLE
[BUG] UI场景单独生成报告不报错，测试计划串行、并行 执行 UI用例报错并且每次的执行的错误率不一致

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27564]
### MeterSphere 版本

v2.10.8-lts 

### 使用外置数据库

否

### 问题描述

测试计划的报告信息：
<img width="936" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/9ad98028-7397-401e-ac71-97492d762386">
<img width="890" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/0bf551c5-e72b-4c19-8e84-0ad20dcfc8e4">
单独执行UI场景的报告信息：
<img width="1253" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/c9729b6a-b212-4daa-874f-117e6c265f59">

问题：在测试计划执行的UI用例失败的情况中有很多种类似上述的问题，下拉框选择失败、选择的不是UI用例xpath指定的、输入框内容不是指定的内容

### 重现步骤

重现的话内部数据不能外泄，可以联系我提供远程复现

### 期待的正确结果

测试计划执行UI用例时可以像单独执行UI场景用例一样不报错；

**Comment by 13290445582** [comment]
您好，测试了几种场景，未复现该问题，请检查UI测试处调试所用环境与执行测试计划所用环境是否一致。

**Comment by sss903065212** [comment]
目前我的测试计划的用例个数为270左右，后台UI并发线程为3，UI执行机 起了4个 node-chromium容器
并行执行发现失败用例50左右，串行执行发现失败用例5左右

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/27609 看起来是同一个问题

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，关闭该issue，感谢理解与支持。
