### ISSUE TITLE
[BUG]自定义工作空间批量操作引用和统计异常

### ISSUE THREAD

**Issue by HolyHorseman** [metersphere/metersphere#27561]
### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

否

### 问题描述

批量操作工作空间无法使用自定义分组；

### 重现步骤

0. 使用系统管理员账号操作；
1. 系统设置 > 用户组与权限，添加自定义工作空间类型的用户组；
2. 系统设置 > 用户，选择多个用户，批量添加到工作空间；
3. 勾选自定义工作空间名称；
4. 下拉框选择只有系统定义分组，没有自定义分组；
5. 如果通过操作每个用户，定义用户组时，可以选择系统定义分组或者自定义分组；

### 期待的正确结果

可以选择自定义分组；

**Comment by 13290445582** [comment]
您好，这里显示的用户组为全局用户组，请检查您创建的工作空间类型用户组的应用范围是否为全局。
