### ISSUE TITLE
[BUG]接口测试-接口自动化，自定义请求，取消勾选“引用环境”，实际接口执行后，还是会引用环境配置中的配置！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2757]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776

**Bug 描述**
简要描述您碰到的问题
接口测试-接口自动化，自定义请求，取消勾选“引用环境”，实际接口执行后，还是会引用环境配置中的配置！

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
接口测试-接口自动化，自定义请求，取消勾选“引用环境”，实际执行请求后，应不再引用环境配置中的配置！

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，您说的引用环境配置具体指什么配置呢？我勾选后没有引用环境域名，能否具体说描述一下呢
