### ISSUE TITLE
[BUG]接口自动化中引用自定义请求，发送请求时生成的请求地址异常

### ISSUE THREAD

**Issue by zhou-weijie** [metersphere/metersphere#27571]
### 联系方式

289020839@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

是

### 问题描述

在接口自动化测试-场景列表中，新增加一个自定义请求，测试时是可以正常请求并响应：
![image](https://github.com/metersphere/metersphere/assets/66190159/ab8b25bb-1993-4ef8-80b6-4e9c9ef80eb1)
点击保存，在列表中进行调试时，实际发送请求的地址，host重复了：
![image](https://github.com/metersphere/metersphere/assets/66190159/da1893dc-9932-4ed8-ad4c-2e87bd96420b)

### 重现步骤

在接口自动化测试-场景列表中，新增加一个自定义请求，测试时是可以正常请求并响应：
![image](https://github.com/metersphere/metersphere/assets/66190159/ab8b25bb-1993-4ef8-80b6-4e9c9ef80eb1)
点击保存，在列表中进行调试时，实际发送请求的地址，host重复了：
![image](https://github.com/metersphere/metersphere/assets/66190159/da1893dc-9932-4ed8-ad4c-2e87bd96420b)

### 期待的正确结果

可以正常发送请求

**Comment by 13290445582** [comment]
您好，未复现您描述的情况，可以提供下您的复现场景吗？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。最新版本v2.10.9已发布，建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
