### ISSUE TITLE
[FEATURE] 用例执行，脑图模式 使用快捷键delete 会把用例删除，不能ctrl z撤回。 希望在执行用例时禁用 删除操作

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27583]
### MeterSphere 版本

2.10.7

### 请描述您的需求或者改进建议

测试计划：用例执行，使用快捷键delete会把用例删除，不能ctrl z撤回。
希望在执行用例时禁用 删除操作

**Comment by xhy12** [comment]
![用例执行，使用快捷键delete](https://github.com/metersphere/metersphere/assets/43202800/11a24dbb-ac60-4d39-97f3-f14955e80a6a)

**Comment by xhy12** [comment]
![20231116100400](https://github.com/metersphere/metersphere/assets/43202800/0fdd93b5-ba4c-4918-90c5-afd8b03bc245)
编写用例的使用delete 快捷键会把正在编写的用例删除，希望能够有撤回操作，如：ctrl z 撤回

**Comment by luty2018** [comment]
已转需求
