### ISSUE TITLE
[BUG]【接口自动化】sql 请求，切换全局环境变量，sql 的环境还是老的（预期：sql 环境同步切换）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2758]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
sql 请求，切换全局环境变量，sql 的环境还是老的（预期：sql 环境同步切换）

**Bug 重现步骤**
1.  构造 sql 请求
2. 切换全局环境变量
3. 检查 sql 使用的环境信息
4. 

**期待的正确结果**
正确情况下应该是什么样的？
同步切换到新的环境配置
实际：sql 的环境还是老的

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/118068110-61ca0400-b3d4-11eb-94ac-b2f332cc56d3.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.10.0版本已修复
