### ISSUE TITLE
[BUG]接口自定义脚本，点击编辑名称后，自动跳到脚本编辑框,不能编辑脚本名称

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27584]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口自动化，添加自定义脚本，展开脚本编辑框，点击编辑脚本名称，自动跳转到脚本编辑框。

### 重现步骤

1.新建接口自动化场景
2.新建自定义脚本步骤
3.展开脚本编辑框，点击编辑脚本名称，光标自动跳转到脚本编辑框，不能编辑脚本名称

### 期待的正确结果

点击脚本名称编辑，可以正常编辑脚本名称

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/445a2db8-b048-4b7f-9462-7d2063b78cca)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.9版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.9版本已发布，请升级尝试。
