### ISSUE TITLE
[BUG]UI测试中修改被引用场景中的场景变量设置不生效

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#27596]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

导入引用场景列表，修改场景设置失败。

### 重现步骤

1.创建一个UI场景，设置打开网页百度步骤，保存场景。
2.创建一个UI场景，引入上一个场景。
3.修改引入场景的场景设置为，优先使用入参，没有则使用原场景变量，保存场景。
4.（问题复现）重新打开场景，场景设置失败。

**Comment by 13290445582** [comment]
您好，请问引入场景中是否存在指令，勾选 优先使用入参，没有则使用原场景变量 生效的前提是引用场景内有指令。

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
优先使用入参，没有则使用原场景变量   修改为    优先使用当前场景变量，没有则使用原场景变量）
