### ISSUE TITLE
[BUG] 【接口自动化】场景变量，csv 文件无法下载，再次编辑，建议支持在线编辑

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2759]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
场景变量，csv 文件无法下载，再次编辑，建议支持在线编辑

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
建议支持在线编辑，或者下载 csv 编辑

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118069019-faad4f00-b3d5-11eb-9298-3b69f8cf3e44.png)

**Comment by zyyfit** [comment]
感谢反馈，我们内部讨论一下
