### ISSUE TITLE
[BUG]MS 同步jira 缺陷，提示Date too long

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27594]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

社区42群，小苏，反馈，MS同步jira 缺陷提示Date too long...

### 重现步骤

社区42群，小苏，反馈，MS同步jira 缺陷提示Date too long...
建议修改custom_field_issues 表Value字段长度后，暂时规避

### 期待的正确结果

MS 可以正常同步jira缺陷

**Comment by fit2cloud-lijiaxin** [comment]
<img width="264" alt="ce444ee3d8b7d85f5919c6b5fb759de1" src="https://github.com/metersphere/metersphere/assets/145318182/54ddacd0-75a4-4973-9c31-c496b58c1670">
<img width="296" alt="14d4756bffd8ac74aee69f6d62d4ed2c" src="https://github.com/metersphere/metersphere/assets/145318182/4c40ca96-46a2-4780
<img width="467" alt="59442f9959e7e94dc2decf2b46365acb" src="https://github.com/metersphere/metersphere/assets/145318182/65af1a5f-4650-41f4-9e4e-681890f0c649">
-a9a3-ea94adb46bd0">
<img width="960" alt="5015e8e9e062a8effbb906b6687ee981" src="https://github.com/metersphere/metersphere/assets/145318182/15b97c02-6e36-440b-89cd-5cffe94281a7">
<img width="960" alt="4a7261ca6d49d13f82e328be0e769961" src="https://github.com/metersphere/metersphere/assets/145318182/91b42255-9980-4c26-9179-d92ef8ab730f">

**Comment by fit2cloud-lijiaxin** [comment]
<img width="296" alt="14d4756bffd8ac74aee69f6d62d4ed2c" src="https://github.com/metersphere/metersphere/assets/145318182/97089eae-d9a2-4b2d-a417-71a24bc599c
<img width="467" alt="59442f9959e7e94dc2decf2b46365acb" src="https://github.com/metersphere/metersphere/assets/145318182/281415d2-ac7e-4560-87d0-3711d9884561">
f">

**Comment by fit2cloud-lijiaxin** [comment]
<img width="296" alt="14d4756bffd8ac74aee69f6d62d4ed2c" src="https://github.com/metersphere/metersphere/assets/145318182/eee545ed-7e4c-460f-8c83-17bdb27af683">

**Comment by 13290445582** [comment]
您好，经过沟通，目前我们custom_field_issues 表Value字段长度设置为1000，难以避免该问题，v2暂不修改。v3上我们会将会采用超出就截取一部分, 不抛这个异常了，感谢理解与支持。
