### ISSUE TITLE
[BUG]swagger 导入接口，api 发生变更后，api 对应的 case 没有更新到 【我的工作台-我的待办-接口用例-待更新】列表

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#27600]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

swagger 导入接口，api 发生变更后，api 对应的 case 没有更新到 【我的工作台-我的待办-接口用例-待更新】列表

### 重现步骤

1.设置 api 的 保存&同步设置
![image](https://github.com/metersphere/metersphere/assets/30038088/4983c400-bba4-4a1b-9ea2-2b5d11a5ddce)

2.修改平台里已经存在的api，加一条 header 参数，保存
![image](https://github.com/metersphere/metersphere/assets/30038088/57be7220-8b4f-4837-937a-068ef02480ba)
3.导入 swagger,选择覆盖、同一API更新到 版本选择 和刚刚保存的api 同一版本
4.查看导入后的 api 参数发生变更，对应 case 的参数没有 同步更新
![image](https://github.com/metersphere/metersphere/assets/30038088/f38d66bd-ed4f-4e1e-a33a-e8c9cbd081d5)
![image](https://github.com/metersphere/metersphere/assets/30038088/71e2b44f-c8eb-4aff-a147-86a746f03503)
5.查看 【我的工作台-我的待办-接口用例-待更新】,该 api 对应的case 并没有更新到此列表
![image](https://github.com/metersphere/metersphere/assets/30038088/c919d0c6-1f63-4c95-80aa-022cb33066bc)

 

### 期待的正确结果

swagger 导入接口，api 发生变更后，api 对应的 case 应该更新到 【我的工作台-我的待办-接口用例-待更新】列表

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，经过反馈，设计如此，导入接口api对应的case不更新到我的工作台-我的待办-接口用例-待更新列表。
