### ISSUE TITLE
[BUG]测试计划执行UI用例，后置断言提取的xpath值不是打开页面的值

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27609]
### MeterSphere 版本

v2.10.8-lts 

### 使用外置数据库

否

### 问题描述

现象为：A用例执行时错乱使用B用例的东西，导致A用例执行失败
<img width="815" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/b772c468-95a4-4d34-833b-9a5a7b2d91ee">
<img width="453" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/fc71ad65-ca2c-4a54-99ba-708b9ae08a4a">
<img width="1251" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/763ac345-904e-487c-8eef-765c0a05c5e2">
<img width="1229" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/31ded38d-21e2-4111-9fba-04c580015aaf">

### 重现步骤

可以提供完整的测试计划需要的UI场景用例

### 期待的正确结果

测试计划可以做到完全的数据隔离，防止A执行时还能错误引用其他用例数据

**Comment by youliyuan-fit2cloud** [comment]
暂时未复现，请进一步确认复现场景。感谢理解和支持～

**Comment by liuruibin** [comment]
已经关联在另一个issue中了
