### ISSUE TITLE
[FEATURE] 测试计划中的用例，希望方便修改执行人

### ISSUE THREAD

**Issue by ouyangkui** [metersphere/metersphere#27612]
### MeterSphere 版本

v1.20.x-lts 

### 联系方式

41群 欧阳

### 请描述您的需求或者改进建议

测试计划中，单个用例的编辑，为啥不能指定执行人呢？

现在知道的办法，前面勾选 ，然后点击。。。，选择批量编辑，再选择属性，
感觉不是很友好和方便，
对于测试用例的分配工作。

### 请描述你建议的实现方案

这个类似功能可以参考testlink，貌似还可以

**Comment by luty2018** [comment]
执行人最终会获取实际执行用例的操作人， 执行前可以在列表上批量修改。v3我们会支持在列表上单独修改， 是否满足需求。

**Comment by ouyangkui** [comment]
列表上单独修改，或者批量选择修改，就更方便了，感谢！

**Comment by ouyangkui** [comment]
期待后续的优化

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
