### ISSUE TITLE
[BUG]【接口自动化】请求 mock 接口，当 mock 入参复杂时，会出现子查询，请求了一个 login 接口

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2762]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
请求 mock 接口，当 mock 入参复杂时，会出现子查询，请求了一个 login 接口

**Bug 重现步骤**
1.  接口自动化，使用循环的方式请求 mock 接口
2. mock 接口入参为 json，调整比较复杂
3. 调试，观察结果
4. 

**期待的正确结果**
正确情况下应该是什么样的？
正确返回 mock 接口的数据

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/118069347-9b037380-b3d6-11eb-99be-860d265ee2ad.png)

![image](https://user-images.githubusercontent.com/11580681/118069369-a5be0880-b3d6-11eb-9673-ee556c404a62.png)

**Comment by zyyfit** [comment]
您好，能具体说明一下入参是什么内容吗？是json字符串吗？
