### ISSUE TITLE
接口mock返回值mock无效

### ISSUE THREAD

**Issue by apolloyun** [metersphere/metersphere#27620]
### MeterSphere 版本

v2.10.1-lts-65fad062

### 使用外置数据库

否

### 问题描述

使用接口mock 在返回值类型，比如@string 返回值类型返回无效{
  "field_0_1_6127c": "@string"
}

### 重现步骤

{
    "field_0_1_6127c": "@string"
}

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/28510932/aa841316-ff58-43a3-98c1-a1795d957a59)

![image](https://github.com/metersphere/metersphere/assets/28510932/1d65418f-09d0-4f12-acd4-f05f3e2d00d6)

**Comment by Somebody-JIAN** [comment]
您好

mock服务目前不支持使用mock.js的函数

我们现在也在考虑如何实现。

**Comment by apolloyun** [comment]
我看那个body的数据是通过websocket 推送的，能不能再返回结果的地方去处理一下（处理方法和请求参数的处理方法一样能不能行）

**Comment by apolloyun** [comment]
@song-tianyang  麻烦看一下，谢谢！

**Comment by Somebody-JIAN** [comment]
这个方案我们也考虑过，事实也确实不是看到的这么简单。

解决方案出来我们也有，但是不支持当前版本的架构。于是我们决定在3.0大版本使用这个方案。

您这种使用场景，暂时用mock的脚本来处理一下吧

很抱歉

**Comment by apolloyun** [comment]
你们3.0的大版本什么时候发布呢，下个月吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 接口mock返回值mock无效 (Issue #27620)





 
这个方案我们也考虑过，事实也确实不是看到的这么简单。
 
解决方案出来我们也有，但是不支持当前版本的架构。于是我们决定在3.0大版本使用这个方案。
 
您这种使用场景，暂时用mock的脚本来处理一下吧
 
很抱歉

**Comment by Somebody-JIAN** [comment]
我们重新设计了产品底层框架，重新绘制了UI，重新设计了交互

我们期望V3大版本能让用户们有一种如沐春风的体验

我们要做的东西有很多，现在也在争分夺秒的开发着

我个人无法给您一个明确的发布计划，但是我们的目标是一致的，保证尽快发布一个非常稳定的3.0

**Comment by apolloyun** [comment]
非常期待，我是咱们产品的忠实粉丝。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月24日(星期五) 上午10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] 接口mock返回值mock无效 (Issue #27620)





 
我们重新设计了产品底层框架，重新绘制了UI，重新设计了交互
 
我们期望V3大版本能让用户们有一种如沐春风的体验
 
我们要做的东西有很多，现在也在争分夺秒的开发着
 
我个人无法给您一个明确的发布计划，但是我们的目标是一致的，保证尽快发布一个非常稳定的3.0
