### ISSUE TITLE
设置环境参数，存入特殊字符后字符缺失

### ISSUE THREAD

**Issue by apolloyun** [metersphere/metersphere#27636]
### MeterSphere 版本

v2.10.1-lts-65fad062

### 使用外置数据库

否

### 问题描述

vars.put(${__metersphere_env_id}+"adcggg","xqw\n001");

存入到环境变量的值 xqw\n001  后缺少了  \n001

### 重现步骤

vars.put(${__metersphere_env_id}+"adcggg","xqw\n001");

### 期待的正确结果

存入到环境变量的值后，显示的还是具体的值

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/28510932/7a3e2782-2c2e-4d72-861f-dc1f4dda51a6)
![image](https://github.com/metersphere/metersphere/assets/28510932/1cc7bd12-948e-4866-bf41-6228081d1351)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，涉及到特殊数据，需要加转译。
![image](https://github.com/metersphere/metersphere/assets/128017892/cd0875b8-c73b-41c0-af90-77da2b606a81)
