### ISSUE TITLE
[BUG]【接口自动化】禁用的接口，点击执行，会持续请求，无法获得返回（预期：禁用的接口，不可点击）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2763]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题
禁用的接口，点击执行，会持续请求，无法获得返回

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
禁用的接口，不可点击

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118069593-08170900-b3d7-11eb-8d58-11ae639ead5c.png)

**Comment by xulinde** [comment]
下个版本修复

**Comment by xulinde** [comment]
1.10版本已修复
