### ISSUE TITLE
[BUG]接口测试，请求参数与 Jmeter 一样，未按期望返回

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27643]
### 联系方式

Metersphere 交流群66

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口测试，请求参数与 Jmeter 一样，未按期望返回

### 重现步骤

接口测试，请求参数与 Jmeter 一样，未按期望返回
![img_v3_0259_49164f48-a25c-4704-a0f2-213105a8f57g](https://github.com/metersphere/metersphere/assets/103627487/6abdc93e-96f1-456a-946b-9c54ab8446ba)

**Comment by liqiang-fit2cloud** [comment]
截图看不清。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
