### ISSUE TITLE
[BUG] UI用例的后置断言使用环境参数变量时，环境变量未生效

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27645]
### MeterSphere 版本

v2.10.8-lts 

### 使用外置数据库

否

### 问题描述

<img width="1065" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/736a7d04-59fe-4a0c-893e-704ca0659d46">
<img width="1111" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/47c5fd9a-5345-4f0f-8526-bd4e473ab8d1">
<img width="1216" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/e88c8cbd-a278-4a46-9da3-13b57a36a6ad">

### 重现步骤

1、环境配置一个参数xxx
2、找一个输入操作 并引用${xxx}
3、在输入操作中添加后置操作 类似如下图
![image](https://github.com/metersphere/metersphere/assets/40912189/104dfb77-9f64-490d-bb78-72b6fad97147)

### 期待的正确结果

环境参数可以在后置断言中生效

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
感谢反馈，产品已沟通完毕，V3统一处理该问题，V2版本使用场景变量替代，感谢理解与支持。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
