### ISSUE TITLE
[QUESTION] 请问：mock 的一串随机码，添加到自定义环境变量中，是否会变化？

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2764]
**请描述您的问题.**
场景中，需要同时请求 mock 和服务器域名

现在，mock 环境无法修改域名

然后将 mock 地址，加入到自定义的域名中，设定好匹配规则。

![image](https://user-images.githubusercontent.com/11580681/118069902-97242100-b3d7-11eb-859e-c9e7fcc2d182.png)

**Comment by jhong123** [comment]
从代码看，应该是 ProjectID

![image](https://user-images.githubusercontent.com/11580681/118083760-0dce1800-b3f2-11eb-9dbf-8f24fab631be.png)

**Comment by xulinde** [comment]
这一串是项目id，不是随机的
