### ISSUE TITLE
[BUG]删除接口的用例后，在测试计划关联接口用例弹窗页仍可看到该接口

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27658]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

删除接口的case后，在测试计划关联接口用例弹窗页，仍会显示该接口，用例数为0

### 重现步骤

1. 创建为接口创建case
2. 测试计划，关联接口case，弹窗显示该接口，且用例数为1
3. 删除1创建的case
4. 再次打开测试计划，关联接口case弹窗，显示该接口，用例数为0
5. 选择关联该接口，页面提示成功，测试计划关联case列表页，无数据
6. 上述操作在多个接口测试，发现关联接口case会有多个用例数为0的接口

### 期待的正确结果

步骤4，接口case数为0时，打开测试计划关联接口case页，不显示用例数为0的接口

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/7466f05e-1c4f-4df5-b471-c73ad322fcd8)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
