### ISSUE TITLE
[FEATURE] 【接口自动化】mock 环境，无法新增、修改域名，建议支持

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2765]
**请描述您的需求或者改进建议.**
场景中，有同时请求 mock 环境和真实域名的情况
但 mock 环境，无法新增、修改域名，建议支持

**请描述你建议的实现方案**
mock 环境，支持新增、修改域名，并配置规则

![image](https://user-images.githubusercontent.com/11580681/118070146-f08c5000-b3d7-11eb-8855-d0bc39772657.png)

**Comment by xulinde** [comment]
1.1.9.2版本支持修改域名
2.目前只支持新增请求头，路径无法新增
