### ISSUE TITLE
[BUG]【接口自动化】提取参数时，jsonpath 匹配多个，勾选后，表达式错误（没有更新）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2766]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1 

**Bug 描述**
简要描述您碰到的问题
提取参数时，jsonpath 匹配多个，勾选后，表达式错误（没有更新）

**Bug 重现步骤**
1.  提取参数时，jsonpath，选择匹配多个
2. 勾选后，表达式错误（没有更新）
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
表达式也应更新：
$.worker[1].name  -> $.worker[*].name

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118070273-2a5d5680-b3d8-11eb-892c-b246b76dfdb2.png)

**Comment by xulinde** [comment]
1.9.2未复现该问题
