### ISSUE TITLE
[FEATURE]  系统操作日志表需要定时清理功能，占用磁盘空间巨大

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27665]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

系统操作日志表需要定时清理功能，占用磁盘空间巨大

### 重现步骤

查询近一个月的数据已经57万，全部数量查不出来，太多了
![image](https://github.com/metersphere/metersphere/assets/103925124/849ea855-a511-4f39-926d-99fb6533962d)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题之前我们有评估过，因为清理系统操作日志会影响后续查询操作信息，影响不好评估，可以手动后台删除，目前前端不支持该功能，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
@fit2cloud-yaochunrong 你好，这个转需求了，待产品回复吧。

**Comment by luty2018** [comment]
v3操作日志默认保存最近半年的， 在系统参数页面进行配置；v2不改了。
