### ISSUE TITLE
[BUG]接口Mock 数据超过30M, 保存报错，接口500

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27662]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口Mock 数据超过30M, 保存报错，接口500

### 重现步骤

1. 创建接口mock服务，保存超过30M的响应数据
2. 保存不成功，接口报错

### 期待的正确结果

mock服务可以保存超过30M的响应数据

### 相关日志输出

```shell
无
```

### 附加信息

<img width="1910" alt="3d7ac977acaa8ef888280c1eb38b2b5" src="https://github.com/metersphere/metersphere/assets/50016789/c75eeee9-5d20-4fc8-8cbc-f86558248d57">

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
