### ISSUE TITLE
[接口测试] Case的详情页，用例名称建议单独展示位一行

### ISSUE THREAD

**Issue by liuqi132** [metersphere/metersphere#27669]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

<img width="1072" alt="微信图片_20231123095457" src="https://github.com/metersphere/metersphere/assets/35127711/08ba9116-ad96-4a5a-888f-79d115f4df08">

**Comment by luty2018** [comment]
感谢建议， 这个页面的交互优化已经规划在v3.0版本了哈。

**Comment by luty2018** [comment]
v2.0已优化，可以升级到最新版本。
