### ISSUE TITLE
[FEATURE] 增加playwright框架的提议

### ISSUE THREAD

**Issue by wanghongbin73** [metersphere/metersphere#27668]
### MeterSphere 版本

v2.17.x-lts

### 联系方式

781774349@qq.com

### 请描述您的需求或者改进建议

希望在下一大版本中的ui测试模块增加playwright框架，供用户选择，写代码的方式较为灵活和快速，有助于metersphere产品吸引更多专业测试人员和测试公司使用

**Comment by luty2018** [comment]
感谢建议， 这个框架我们也调研过， 确实很灵活 ，在完善好现有UI测试模块的功能后， 也会考虑支持其他框架的。
