### ISSUE TITLE
[BUG]【接口自动化】环境变量有时选不到（偶现）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2767]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118070636-dc951e00-b3d8-11eb-87bb-c32b031b054f.png)

**Comment by xulinde** [comment]
1.9.2未复现该问题，建议升级到最新版本试下
