### ISSUE TITLE
[BUG]   json根目录为array，添加提取的数据库变量，字符串类型未赋值双引号，导致接口参数异常，接口执行失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27673]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

  json根目录为array，添加提取的数据库变量，字符串类型未赋值双引号，导致接口参数异常，接口执行失败【大批量紧急】

### 重现步骤

数据库查询id列，id为varchar类型：
![image](https://github.com/metersphere/metersphere/assets/103925124/aaa64fe7-462e-4afa-9582-e5cd190977f5)
![image](https://github.com/metersphere/metersphere/assets/103925124/6508c91a-14ab-4888-84f5-cc4ab5277683)
![image](https://github.com/metersphere/metersphere/assets/103925124/21fd6080-6e36-4bea-bb69-057531bce250)

**Comment by fit2-zhao** [comment]
平台并不会给变量自动追加引号，由用户自定义，比如变量中自己定义了 \" xxx  \"这种数据平台再次自动追加会错的更多。

**Comment by fit2cloud-yaochunrong** [comment]
![image](https://github.com/metersphere/metersphere/assets/103925124/9fbe867f-6755-44a6-bba5-b940652455bc)
麻烦看下这个，不是根目录的时候引用效果

**Comment by fit2-zhao** [comment]
我们再确认一下，变量机制是统一的，不会做特殊处理，使用的都是默认测试引擎JMeter 的上下文变量处理机制。

**Comment by fit2cloud-yaochunrong** [comment]
之前版本是正常的

**Comment by fit2-zhao** [comment]
下版本处理。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
