### ISSUE TITLE
[BUG] 接口调试，响应内容超过30M, 显示一直在测试中，得不到响应结果，但是接口导入到Jmeter中可以得到响应结果

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27679]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

接口调试，响应内容超过30M, 显示一直在测试中，得不到响应结果，但是接口导入到Jmeter中可以得到响应结果。

### 重现步骤

1. 接口调试，响应内容超过30M, 显示一直在测试中，得不到响应结果，
2. 但是接口导入到Jmeter中可以得到响应结果。

### 期待的正确结果

响应内容超过30M, 可以得到响应结果。

### 相关日志输出

```shell
无
```

### 附加信息

![499ccb67b8f2c0419dd702a653ba67f](https://github.com/metersphere/metersphere/assets/50016789/fde8e6d4-6dea-4794-a2c2-3b7248ddc2be)
<img width="1202" alt="c811073b8965b2afb414a347f0a0bce" src="https://github.com/metersphere/metersphere/assets/50016789/aa567348-52ce-4813-b626-3ef815710910">

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
在 /opt/metersphere/conf/metersphere.properties 中添加参数 spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=209715200 然后重启服务。
