### ISSUE TITLE
[BUG]【接口自动化】删除接口，保存，接口删除错误（偶现）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2768]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118070802-27af3100-b3d9-11eb-912a-46b6aec95432.png)

**Comment by xulinde** [comment]
未复现，等再复现的时候详细描述下步骤

**Comment by xulinde** [comment]
1.9.2未复现
