### ISSUE TITLE
[BUG] 浮点数断言不通过 4000.0 == 4000.00

### ISSUE THREAD

**Issue by lihuacai168** [metersphere/metersphere#27683]
### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

第一个接口返回的值是"paymentAmount": 4000.0,
第二个接口返回的值"paymentAmount": 4000.00

第二个接口断言 4000.0 == 4000.00是不通过  
有什么办法让可以变成通过，优雅一点的
![image](https://github.com/metersphere/metersphere/assets/11568297/59e09b30-7b66-4cea-a8ae-ab98e7523449)

### 重现步骤

看问题描述

**Comment by 13290445582** [comment]
您好，感谢反馈，使用的JsonPath断言吗，建议您升级至v2.10.9最新版本，将断言条件 '等于' 更改为 '正则匹配'，即可断言成功。
jsonpath 断言中的“等于”保持现有逻辑为完全匹配，需要匹配精度的时候建议使用“等于” 。这个也是我们针对jmeter扩展的一种断言，覆盖了精度匹配。
jsonpath 断言中的“正则匹配”恢复为jmeter自身逻辑，即校验数字时会默认忽略精度，校验字符串时为完全匹配，需要使用正则进行精度匹配时则需要自行填写表达式来覆盖。

**Comment by lihuacai168** [comment]
> 您好，感谢反馈，使用的JsonPath断言吗，建议您升级至v2.10.9最新版本，将断言条件 '等于' 更改为 '正则匹配'，即可断言成功。 jsonpath 断言中的“等于”保持现有逻辑为完全匹配，需要匹配精度的时候建议使用“等于” 。这个也是我们针对jmeter扩展的一种断言，覆盖了精度匹配。 jsonpath 断言中的“正则匹配”恢复为jmeter自身逻辑，即校验数字时会默认忽略精度，校验字符串时为完全匹配，需要使用正则进行精度匹配时则需要自行填写表达式来覆盖。

如果不升级的话，需要忽略精度应该怎么写比较方便

**Comment by 13290445582** [comment]
您好，建议您升级到最新版本使用，可方便使用断言规则。不升级的话，暂时没有其他合适的办法，只能写的时候就将数据写全，或者采用文档断言试试看，感谢您的理解与支持。
