### ISSUE TITLE
[FEATURE] 增加变量追踪功能

### ISSUE THREAD

**Issue by lihuacai168** [metersphere/metersphere#27684]
### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 请描述您的需求或者改进建议

# 背景
在实际使用过程中，用例是有多个场景组成，步骤超过100步也是很正常。  
在调试很长的用例时，比如在第100步使用了一个变量${a}，发现取值不是预期的。  
但无法快速找到这个变量是在哪里引用的，也不知道在哪里被更新过。  
因为可以设置变量的地方非常多，当前场景变量，引用场景的场景变量，脚本设置变量，后置提取器等  
目前是需要逐个去这些地方查找，相当耗费时间

### 请描述你建议的实现方案

# 方案1
增加变量追踪，记录每个变量的生命周期，比如在哪里开始初始化，经过哪个步骤被更新了値

# 方案2
在调试用例和测试报告时，增加全局搜索功能，支持搜索所有可能设置或者更新变量的地方，把对应的结果显示出来  
这样至少能快速定位

**Comment by luty2018** [comment]
感谢建议， 这个功能确实非常需要， 我们好好调研并规划

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
