### ISSUE TITLE
[BUG] UI用例引用的用例使用的定位是元素对象的话，在点击下面元素库内容时发生了变化

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27680]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

<img width="1259" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/2b09c84b-ad42-4c05-8d49-9a92fef2fed0">
<img width="1263" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/b9ccaf40-3e9e-4176-9368-08a8a4ff0ff5">

点击下面元素库的内容会替换 上面无法编辑的定位

### 重现步骤

1、建两个UI用例 A,B ；元素库建两个元素 m,n
2、A里面使用元素对象 
3、B引用A，然后看下图
<img width="1263" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/58f14713-89b3-4ded-ac98-2e4f260a3b43">

### 期待的正确结果

在引用其他用例时，元素对象不要替换，或者在
<img width="1263" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/cd477cd8-9ee0-4419-a689-6e908c8b9334">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，v2.10.9-lts中已修复该问题，请升级一下吧。

**Comment by 13290445582** [comment]
您好，偶现问题，修改该处涉及到前端缓存与相关联较多页面，V2版本以保持稳定为主，不在代码上进行改动该问题，目前通过不点击该元素对象达到避免出现替换的情况，感谢理解与支持。
