### ISSUE TITLE
[FEATURE]环境配置，通用配置里的批量导入，增加更清晰的提示。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27693]
### MeterSphere 版本

v2.10.8

### 请描述您的需求或者改进建议

1.环境配置，通用配置里的批量导入，能否增加更清晰的提示，比图常见的int和String怎样来写，是一直用key：value的方式吗。
因为有可能String类型，可能会写成  a：“11111”，这样 后面使用会导致取值错误。
![image](https://github.com/metersphere/metersphere/assets/55130444/87adcb30-bd61-4337-ab48-7ea811622a7e)

### 请描述你建议的实现方案

增加常见类型的批量添加提示。

**Comment by luty2018** [comment]
暂无此规划
