### ISSUE TITLE
[BUG]   接口请求体开启json-schema后，设置参数为空，实际请求时非空，不符合预期

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27698]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

 接口请求体开启json-schema后，设置参数为空，实际请求时非空，不符合预期

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/e9fa9d63-f9ad-4999-b28a-cbf0740d8305)

**Comment by fit2-zhao** [comment]
感谢反馈，下版本优化一下。

**Comment by 13290445582** [comment]
https://github.com/metersphere/metersphere/issues/27730

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
