### ISSUE TITLE
[BUG]  使用谷歌最新版 119.0.6045.160（正式版本）进行本地调试，运行UI测试过程中打开F12，浏览器闪退

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27701]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

使用谷歌最新版 119.0.6045.160（正式版本）进行本地调试，运行UI测试过程中打开F12，浏览器闪退

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/0edb6534-3d0b-46e2-beca-90cfec0d3b4e)
进行本地调试
![image](https://github.com/metersphere/metersphere/assets/103925124/ca5891c9-7fac-4413-ba6d-fef66807bc07)
调起F12后，浏览器闪退

**Comment by xulinde** [comment]
我的chrome版本和你一样，本地调试没问题。应该是driver版本不一致导致，用新版的driver试下
![image](https://github.com/metersphere/metersphere/assets/64065190/8b951ec5-faca-493d-b910-72c82ffcb3d2)

**Comment by xulinde** [comment]
已复现，后续版本修复。

**Comment by xiaomeinvG** [comment]
该错误是Chromedriver错误，他们给出了以下建议： https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
