### ISSUE TITLE
[BUG] 测试用例，修改后置脚本内容，保存并执行，脚本未生效（不必现）

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2770]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.2
**Bug 描述**
简要描述您碰到的问题
测试用例，修改后置脚本内容，保存并执行，脚本未生效（不必现）
**Bug 重现步骤**
1.  修改后置脚本内容，点击保存，执行完，控制台打印日志 ，显示脚本未生效
![image](https://user-images.githubusercontent.com/30038088/118073267-187eb200-b3de-11eb-8cc3-1896fdc8c370.png)

2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
测试用例，修改后置脚本内容，保存并执行，脚本是生效的
**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
1.9.2未复现该问题
