### ISSUE TITLE
[BUG]环境配置中通用配置给变量添加备注保存成功后，再打开发现并未保存成功备注

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27718]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

环境配置中通用配置给变量添加备注保存成功后，再打开发现并未保存成功备注

### 重现步骤

1. 配置环境变量
2. 添加通用变量，保存成功
3. 追加通用变量备注
4. 保存成功
5. 再打开发现前面添加的备注并未保存成功

### 期待的正确结果

环境配置中通用配置给变量添加备注保存成功

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/11873fc4-9476-47ea-b0f2-c3c702a1549f)
再次打开发现没有保存成功
![image](https://github.com/metersphere/metersphere/assets/50016789/c4487c8b-3795-488e-b358-c0826eab5822)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
