### ISSUE TITLE
[FEATURE] 用例页面，应该支持点击id，名称，甚至这一行， 跳转到查看页面。

### ISSUE THREAD

**Issue by ouyangkui** [metersphere/metersphere#27711]
### MeterSphere 版本

v1.20.x-lts

### 请描述您的需求或者改进建议

目前只支持点击后面的查看按钮，不是很友好。
而且，当鼠标放到用例行的时候，现实的是鼠标，可点击的，实际点击没有任何反应

**Comment by luty2018** [comment]
我们会在v2下个小版本支持， 可以关注我们的发布日志。

**Comment by luty2018** [comment]
已支持。
