### ISSUE TITLE
[BUG]  接口CASE中请求体Json数据如果有红叉，保存后重新打开该CASE json格式请求体数据不显示

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27710]
### MeterSphere 版本

v2.10.8-lts、v2.10.9-lts

### 使用外置数据库

否

### 问题描述

<img width="729" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/e0eb57b3-170b-4ea8-9568-f28bc775ffeb">
<img width="967" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8411ac91-838c-4527-8163-78dad19a63bb">

### 重现步骤

1、随便一个CASE
2、添加如下的json数据到请求体
{
    "A": ${__eval(${a_chargeYear})},
    "B": "Y"
}
3、保存后，重新打开该CASE，查看请求体json

### 期待的正确结果

修复到和.5一样，.5是可以正常展示的

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
