### ISSUE TITLE
[BUG] 场景列表-查看引用：测试步骤内嵌套引用的不能查询出来

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27716]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

场景列表-查看引用：测试步骤内嵌套引用的不能查询出来

### 重现步骤

举例三场景引用关系为：
![image](https://github.com/metersphere/metersphere/assets/103925124/a0486545-ba45-44b0-94a1-bcf8a5d26865)
点击子场景的查看引用，只有“父”场景，没有“爷”场景
![image](https://github.com/metersphere/metersphere/assets/103925124/79723459-cd87-477b-87ee-7ad77405041a)
希望：测试步骤内嵌套引用的也可以查询出来

**Comment by 13290445582** [comment]
您好，设计上只统计直接引用关系，暂不支持您提的这种查询的场景。
