### ISSUE TITLE
[BUG]【测试跟踪-用例评审】根据创建时间倒序后，切换到脑图页面，然后展开脑图到用例层级，页面就提示错误

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27726]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-用例评审】根据创建时间倒序后，切换到脑图页面，然后展开脑图到用例层级，页面就提示错误

### 重现步骤

【测试跟踪-用例评审】根据创建时间倒序后，切换到脑图页面，然后展开脑图到用例层级，页面就提示错误
![image](https://github.com/metersphere/metersphere/assets/104960608/41c528a9-f7b3-4575-93e0-b5ed1720c9d9)
![image](https://github.com/metersphere/metersphere/assets/104960608/ce09810b-ba1d-46a0-a60a-10e2a74cc019)
![image](https://github.com/metersphere/metersphere/assets/104960608/6e4556dc-a938-414b-81fb-4e4c61b65569)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
