### ISSUE TITLE
[BUG]测试计划 添加定时任务，飞书webhook 关键词 测试，测试计划自动执行后 ，飞书收到两条重复消息

### ISSUE THREAD

**Issue by yudongya** [metersphere/metersphere#27735]
### 联系方式

975387401@qq.com

### MeterSphere 版本

版本:   v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

1、测试计划 添加定时任务，
2、飞书webhook 关键词 测试，
3、测试计划自动执行后 ，飞书收到两条重复消息

### 重现步骤

1、测试计划 添加定时任务，
2、飞书webhook 关键词 测试，
3、测试计划自动执行后 ，飞书收到两条重复消息

### 附加信息

![微信图片_20231128145435](https://github.com/metersphere/metersphere/assets/21274199/96bd8c12-eb79-48d1-b0a6-d262a8c86e39)

**Comment by 13290445582** [comment]
<img width="1060" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/9a6ac2d2-7345-41c9-a887-7299fedae8df">
您好，未复现该情况。请检查任务通知处是否配置了两个执行失败的通知。

**Comment by yudongya** [comment]
![image](https://github.com/metersphere/metersphere/assets/21274199/16b3717b-6819-467c-ab5b-cf39b2cd2590)
只有一个

**Comment by 13290445582** [comment]
定时任务触发的通知 一直都是发两条重复消息吗 还是偶现

**Comment by yudongya** [comment]
一直两条，只在计划中两条，在场景中正常

**Comment by yudongya** [comment]
![image](https://github.com/metersphere/metersphere/assets/21274199/341f10b7-57a2-444e-acc6-f3e36d431ce4)
![image](https://github.com/metersphere/metersphere/assets/21274199/17792c69-823e-449f-9b48-497040ea3cb2)
这里点一次执行两次

**Comment by yudongya** [comment]
![image](https://github.com/metersphere/metersphere/assets/21274199/ec64a671-fb91-4bf0-88c0-6a1d932178d8)
都是接收两条，有哪些配置可能会在接收

**Comment by 13290445582** [comment]
定时任务消息通知就在上图配置，手动执行的在消息设置处配置。
目前在本地环境未复现该问题，请问接收方式为邮件、钉钉、企业微信也同样会有此问题吗？
您新建工作空间项目或者新搭建环境也同样会发送两条重复信息吗？

**Comment by yudongya** [comment]
你去问下 于凯杰  他已经远程看过了，知道情况，再说我们不是给你们测试的

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，暂时关闭该issue，感谢理解与支持。
