### ISSUE TITLE
[BUG] 【接口测试 - 接口自动化】接口参数类型设置为null时，实际发送了‘{}’

### ISSUE THREAD

**Issue by badanything** [metersphere/metersphere#27730]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

是

### 问题描述
metersphere 版本从2.10.7 升级到 2.10.9 后出现的问题

【接口测试 - 接口自动化】场景调试时，某些接口的参数的值设定为null，但在发起请求后，实际发送的值是 ‘{}’

### 重现步骤

【接口测试 - 接口自动化】
1. 将接口的某些参数的类型设置为null
2. 发送请求
3. 接口返回参数类型错误
![image](https://github.com/metersphere/metersphere/assets/87409905/7d80b9ab-ee46-401d-8a89-15cf119ac2b0)

**Comment by 13290445582** [comment]
您好，重复问题，已关联。
