### ISSUE TITLE
[BUG]  循环控制器和条件控制器下面的case状态错误，非有失败为失败，偶现

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27739]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

  循环控制器和条件控制器下面的case状态错误，非有失败为失败

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/e7faa204-fbb5-495f-a500-47f86cb05e51)
![image](https://github.com/metersphere/metersphere/assets/103925124/54f30e4f-682e-455c-a3b0-443c24bf812d)
![企业微信截图_17011633234611](https://github.com/metersphere/metersphere/assets/103925124/a68f8b59-5a95-4fd2-9da2-4a04cf8a99eb)

**Comment by 13290445582** [comment]
您好，通过创建相同结构场景，尚未复现该偶现问题，待有确切复现步骤请及时反馈，感谢您的理解与支持。

**Comment by 13290445582** [comment]
您好，暂时关闭该issue，若后续有稳定复现步骤，可重新提issue，感谢您的理解。
