### ISSUE TITLE
[FEATURE]场景中添加等待控制器 是对整个场景中步骤生效，而不是单个请求，希望能加个提示

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#27744]
### MeterSphere 版本

v2.10.9-lts

### 联系方式

shenkaibo

### 请描述您的需求或者改进建议

场景中添加等待控制器 是对整个场景中步骤生效，而不是单个请求，希望能加个提示
![image](https://github.com/metersphere/metersphere/assets/30038088/776a9ca4-b7eb-4b50-8f3a-a709ff48b2c2)

建议在等待控制器的右侧很大一部分空白处，加一个提示，类似
![image](https://github.com/metersphere/metersphere/assets/30038088/07d17376-7336-4936-9ae6-7893da27447e)

**Comment by luty2018** [comment]
v3优化
