### ISSUE TITLE
[BUG]消息通知-设置用例评审评论发送邮件，用例评审批量编辑通过未评论也发送邮件

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27749]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

消息通知-设置用例评审评论发送邮件，点击用例单条通过不评论没有发邮件，用例评审批量编辑通过未评论也发送邮件

### 重现步骤

1. 消息通知-设置 用例评审 评论 发送邮件
![image](https://github.com/metersphere/metersphere/assets/103627487/95bd1272-afb6-4c11-b985-2854a23c86fc)
2. 用例评审批量编辑通过未评论也发送邮件
![image](https://github.com/metersphere/metersphere/assets/103627487/ff1a311a-8a19-4209-8394-a6e7193ffff2)
![img_v3_025l_ee442f4e-34e9-4c31-91e8-b2e7708b75bg](https://github.com/metersphere/metersphere/assets/103627487/0f05cb09-d329-489b-969c-fcf153efccf6)
但是点击用例单条通过不评论就不会发邮件（我觉得这应该是正常逻辑）

**Comment by 13290445582** [comment]
感谢反馈，计划下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
