### ISSUE TITLE
[BUG]  调试场景执行完毕，步骤一直显示测试中，生成报告无此问题，偶现

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27742]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

调试场景执行完毕，步骤一直显示测试中他，生成报告无此问题，偶现

我这边是导入场景出现的，可问我要脚本

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/5b435a80-63f0-4745-84b6-854f7452d3e3)
![image](https://github.com/metersphere/metersphere/assets/103925124/798ba9a4-2e30-4636-a0c7-6b371e183335)

**Comment by 13290445582** [comment]
感谢反馈，已知问题，计划于v2.10.10版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。

**Comment by damonWongTest** [comment]
版本:   v2.10.13-lts-163a8232
还是一直测试中，但是使用jmeter又可以成功
![image](https://github.com/user-attachments/assets/581df141-c14d-4476-b61a-ad2fc830e1af)
