### ISSUE TITLE
[BUG]api开启同步更新case配置后，当请求体参数关闭 JSON-SCHEMA 后，修改api 请求体 json 参数的 value 会覆盖 case 对应参数的值

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#27746]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

api开启同步更新case配置后，当请求体参数关闭 JSON-SCHEMA 后，修改api 请求体 json 参数的 value 会覆盖 case 对应参数的值

### 重现步骤

1.api 初始参数
![image](https://github.com/metersphere/metersphere/assets/30038088/61a67631-0e01-400d-b71b-6027d01e5deb)

2.case 初始参数
![image](https://github.com/metersphere/metersphere/assets/30038088/8228c9da-db9e-4c2d-8194-ae6372e2308e)

3. 修改 api 参数
![image](https://github.com/metersphere/metersphere/assets/30038088/ec3869c2-0292-4d23-be05-351f37b6b0b4)
  
4. case 同步修改为
![image](https://github.com/metersphere/metersphere/assets/30038088/4c0f600f-398b-4186-be89-4d19c8cf1187)

**case 请求体中 name 参数 不应该被修改**

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，非缺陷。关闭JSON-SCHEMA，请求体都为文本信息，同步更新全部覆盖；开启JSON-SCHEMA，请求体为key-value值，就不会全部覆盖。

**Comment by shenkaibo** [comment]
> 您好，非缺陷。关闭JSON-SCHEMA，请求体都为文本信息，同步更新全部覆盖；开启JSON-SCHEMA，请求体为key-value值，就不会全部覆盖。

这里说的 开启 关闭 JSON-SCHEMA  是指 API  还是 CASE ?

**Comment by 13290445582** [comment]
> > 您好，非缺陷。关闭JSON-SCHEMA，请求体都为文本信息，同步更新全部覆盖；开启JSON-SCHEMA，请求体为key-value值，就不会全部覆盖。
> 
> 这里说的 开启 关闭 JSON-SCHEMA 是指 API 还是 CASE ?

API
