### ISSUE TITLE
[BUG]【测试跟踪-功能用例】从其他页面切到功能用例列表，当页面用例很多，左侧模块树层级也很多时，页面加载速度很慢，能否再进行优化。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27752]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪-功能用例】从其他页面切到功能用例列表，当页面用例很多，左侧模块树层级也很多时，页面加载速度很慢。8c32g的服务器，功能模块扩大内存大小到4g，4w多条用例有时会加载30秒，mysql慢查询开启了，打印到日志文件中，大概花了13秒之久，这个能否再进行优化。

### 重现步骤

【测试跟踪-功能用例】从其他页面切到功能用例列表，当页面用例很多，左侧模块树层级也很多时，页面加载速度很慢。4w多条用例有时会加载30秒，mysql慢查询开启了，打印到日志文件中，大概花了13秒之久，这个能否再进行优化。
![image](https://github.com/metersphere/metersphere/assets/104960608/0fc797ba-39fc-4e0f-a5d3-53eeee6daa2c)
![image](https://github.com/metersphere/metersphere/assets/104960608/d490c568-c074-4335-8e11-28a2ec2d3f36)

加载左侧模块树时，是不是可以不一次性全加载出来，可以先只加载二级目录，然后点击二级目录再加载三级目录，这样是不是可以节省时间

**Comment by 13290445582** [comment]
您好，请问：1.左侧模块数量为多少，层级为几层  2.是加载用例慢，还是模块慢呢  3.mysql慢查询有定位到是哪个sql慢了吗

**Comment by 2lipan** [comment]
左侧模块层级多的有9层，是进入这页面是转圈圈，根据在页面上F12抓的接口显示，加载模块的接口比加载右侧用例花的时间要长。慢查询sql私发。

**Comment by AgAngle** [comment]
你好，目前我们的测试环境也有几万的用例总数，但是没有出现过慢的情况，请问一下，你们准确的数据量，系统中的用例和模块总数，还有当前项目的用例和模块总数，我们再尝试复现下，可以查看下test_case表和test_case_node表；
其次可以尝试提升下mysql的配置，或者调节下mysql的系统参数，例如 buffer_pool_size 等参数；
另外，从慢sql日志上，大概找到这两条相关的 sql，可以尝试分析下，添加下索引，看看能不能有所改善

`SET timestamp=1701139408;
select tcn.id, count(*) as caseNum
        from test_case
        left join test_case_node tcn on test_case.node_id = tcn.id
         WHERE  test_case.project_id = 'xxx'
            and (test_case.status != 'Trash' or test_case.status is null)
            AND test_case.latest = 1 
        group by tcn.id;`

`select
        test_case.delete_user_id ,test_case.delete_time,
        project_version.name as versionName,
        project_version.id as versionId,
        test_case.last_execute_result,
        test_case.prerequisite, test_case.steps, remark, test_case.expected_result, test_case.step_description,
        test_case.id, test_case.node_id, test_case.node_path, test_case.project_id, test_case.`name`,
        test_case.`type`, test_case.maintainer, test_case.priority, test_case.`method`,
        test_case.create_time, test_case.update_time, test_case.test_id, test_case.sort, test_case.num,
        test_case.review_status, test_case.tags,
        test_case.demand_id, test_case.demand_name, test_case.`status`,
        test_case.custom_num, test_case.step_model, test_case.create_user,
        test_case.ref_id,test_case.latest
        from test_case
        left join project_version on project_version.id = test_case.version_id
         WHERE  test_case.project_id = 'xxx'
                    and (test_case.status != 'Trash' or test_case.status is null)
            AND test_case.latest = 1 
            order by    
                        test_case.`create_time` ASC
 LIMIT 10;`

**Comment by 2lipan** [comment]
已调大 buffer_pool_size 参数到 4G，从页面上看 加载情况有所改善。
