### ISSUE TITLE
[BUG]【UI测试】同时开启多个场景窗口，点击某场景某一步骤后，切到另外一窗口，然后再切到之前窗口，发现鼠标光标默认显示在第一个，右侧内容却没有切过来。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27753]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【UI测试】同时开启多个场景窗口，点击某场景某一步骤后，切到另外一窗口，然后再切到之前窗口，发现鼠标光标默认显示在第一个，右侧内容却没有切过来。

### 重现步骤

【UI测试】同时开启多个场景窗口，点击某场景某一步骤后，切到另外一窗口，然后再切到之前窗口，发现鼠标光标默认显示在第一个，右侧内容却没有切过来。
![image](https://github.com/metersphere/metersphere/assets/104960608/de57c6d5-a68d-40be-9c4c-881e7bc51969)
![image](https://github.com/metersphere/metersphere/assets/104960608/afdeba1e-6fd4-4620-9e1e-3713c5d47d5f)

**Comment by 13290445582** [comment]
当前版本不支持太多场景切换，可通过刷新解决该问题，不影响主流程进行的，暂不修复。
