### ISSUE TITLE
[BUG]接口自动化场景环境二次点击，前后置SQL查询执行时出现数据源错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27761]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.8-lts，v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口自动化场景环境二次点击，页面对应的数据源显示正常，但是前后置SQL查询执行出现数据源错误，实际执行时默认被切换成排序为第一的数据源

### 重现步骤

1、编辑某个接口自动化场景
2、调试接口自动化场景
3、下拉环境，点击确定
4、再次执行接口自动化

### 附加信息

https://github.com/metersphere/metersphere/assets/32027713/f4126775-3936-4159-87b7-c3e3fabde04b

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.10版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
