### ISSUE TITLE
[BUG]功能用例首页用例责任人分布，人员过多时无法显示全部人员名称 

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27765]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

功能用例首页用例责任人分布，人员过多时无法显示全部人员名称 

### 重现步骤

1. 功能用例首页用例责任人分布，人员过多时无法显示全部人员名称 ，而且人员过多时也不好分清楚哪个人对应哪个柱状图，还需一个一个柱状图点击查看
![image](https://github.com/metersphere/metersphere/assets/103627487/a58715f9-1b12-4e48-9d97-8b02d7985563)
![image](https://github.com/metersphere/metersphere/assets/103627487/586ff28b-6e43-4df1-a135-b79833958507)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.21-lts版本中已优化
