### ISSUE TITLE
[BUG]在MeterSphere接口自动化导入JMX文件，页面经常提示无法解析文件

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#27775]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.9

### 使用外置数据库

否

### 问题描述

如标题所示

### 重现步骤

操作过程如图所示
<img width="960" alt="WX20231201-110841@2x" src="https://github.com/metersphere/metersphere/assets/18387151/25f32e69-b67b-4b09-bbb8-1e4bbfcb0939">

请参考https://github.com/metersphere/metersphere/issues/26907
进行优化调整

**Comment by 13290445582** [comment]
您好，计划下个版本优化下该问题。

**Comment by 13290445582** [comment]
您好，v2不再修改这里，待3.0讨论规划，感谢理解与支持。
