### ISSUE TITLE
[BUG]【接口自动化】接口自动化-复制其他场景进行调试，返回内容为空时，点击“推荐JSONPath断言”，页面会有“请先执行调试获取响应结果”提示

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27779]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】接口自动化-场景里复制其他场景，点击调试，当请求发送成功但返回内容为空时，点击“推荐JSONPath断言”，页面会有“请先执行调试获取响应结果”提示

### 重现步骤

【接口自动化】接口自动化-场景里复制其他场景，点击调试，当请求发送成功但返回内容为空时，点击“推荐JSONPath断言”，页面会有“请先执行调试获取响应结果”提示
![image](https://github.com/metersphere/metersphere/assets/104960608/0b10721e-2f16-40e8-9998-b3aa97120284)

**Comment by 13290445582** [comment]
您好，计划下版本优化下该提示。

**Comment by 2lipan** [comment]
响应内容若有值，点击【推荐jsonpath提取】也有此情况。
![image](https://github.com/metersphere/metersphere/assets/104960608/0d4cb6ed-8bb3-452f-9221-a01b36f8f7bc)

**Comment by 13290445582** [comment]
您好，已优化文案，请升级验证。当前文案为：未检测到响应数据，请运行接口并确保产生了响应数据
