### ISSUE TITLE
[BUG]性能测试的执行方式如果选择“按迭代次数”，就不需要“压测时长”这个输入项

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#27773]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v2.10.9

### 使用外置数据库

否

### 问题描述

性能测试的执行方式如果选择“按迭代次数”，就不需要“压测时长”这个输入项，尽量与JMeter界面的使用体验保持一致

### 重现步骤

以下是MeterSphere页面的实际操作结果
<img width="1098" alt="WX20231201-103355@2x" src="https://github.com/metersphere/metersphere/assets/18387151/71b058f7-5d15-4da3-b068-d9585464354f">

### 期待的正确结果

性能测试的执行方式如果选择“按迭代次数”，就不需要“压测时长”这个输入项，尽量与JMeter界面的使用体验保持一致

**Comment by youliyuan-fit2cloud** [comment]
<img width="708" alt="image" src="https://github.com/metersphere/metersphere/assets/54612864/61e58d34-0747-41bd-9a72-9b4222a20d75">

你好，看上图提示信息：10s 和 3000次是哪个先到达按照哪个结束。所以暂时不做修改，感谢理解和支持～

**Comment by songbing0312** [comment]
<img width="879" alt="WX20231201-112448@2x" src="https://github.com/metersphere/metersphere/assets/18387151/ea63d6f5-4919-42bb-9b67-10dedf395aa2">

按JMeter界面的使用习惯，在选择“迭代次数”的情况下，“持续时长”的输入项默认是空值

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/07c0f86c-9f47-4d4d-88c4-3b324d8c4359)

需要选中 Sepcify Thread lifetime才行，和迭代次数 不冲突哇。

**Comment by songbing0312** [comment]
JMeter用户的使用习惯是，在选择“迭代次数”的情况下，默认不用管“持续时长”的配置
在MeterSphere页面选择“迭代次数”的情况下，还要手动修改“持续时长”的配置，这一步操作有点多余了
