### ISSUE TITLE
[BUG]导入用户时报错提示项 

### ISSUE THREAD

**Issue by wbbk** [metersphere/metersphere#27781]
### 联系方式

15195225960

### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

批量导入用户时 提示  建议优化下提示Cannot invoke "String.split（String）" because "workspacelnfolnExcel" is null

### 重现步骤

导入用户数据中 工作空间置空  ，导入就会报错Cannot invoke "String.split（String）" because "workspacelnfolnExcel" is null，但是不明确是什么内容的问题

### 期待的正确结果

导入用户数据中 工作空间置空  提示 工作空间未填写

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.10-lts 中已修复。
