### ISSUE TITLE
[FEATURE] 控制台输出日志格式支持自定义

### ISSUE THREAD

**Issue by lihuacai168** [metersphere/metersphere#27786]
### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 请描述您的需求或者改进建议

目前在使用beanshell在控制台输出日志的时候，存在以下问题：
- 无法快速定位日志输出所在脚本，除非每个日志都手工加上
- 控制台日志不合理，比如现在有10个步骤，在第3步时，控制台输出日志也包含了后面所有步骤的内容
![image](https://github.com/metersphere/metersphere/assets/11568297/3f5faf57-d395-4267-9311-1189d1978022)

### 请描述你建议的实现方案

1. 增加log配置格式，让在日志中输出脚本所在的用例步骤
2. 控制台日志只应包含当前步骤及以前步骤的日志，不应该包含所有日志输出

**Comment by fit2-zhao** [comment]
感谢建议，暂时不支持自定义，如果是有重用的脚本层面输出特定含义的日志，请自行做好区分，每个场景｜用例 之间做了隔离，同场景步骤之间无法再做细化区分。
