### ISSUE TITLE
[BUG]dubbo接口TEST的时候，资源池跟项目设置使用的资源池不一致，一直是Local

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27787]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

dubbo接口TEST的时候，资源池跟项目设置使用的资源池不一致，一直是Local

### 重现步骤

1.项目设置-应用管理-接口测试里选择非Local资源池
![ca8d9815-7612-4032-b8ab-defd9b5441d6](https://github.com/metersphere/metersphere/assets/88763608/de3e4664-f89d-4e6d-9d64-8a1767f4c361)

2.执行dubbo接口，显示Local资源池执行
![image](https://github.com/metersphere/metersphere/assets/88763608/97362c0d-6a6b-4d25-aba5-e6cf2e902426)

### 相关日志输出

```shell
跟项目设置选择的资源池一致
```

**Comment by 13290445582** [comment]
感谢反馈，计划下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
