### ISSUE TITLE
[BUG]【接口自动化】批量关闭步骤-请求会被禁用，前后置脚本也被禁用了

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27791]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】批量关闭步骤-请求会被禁用，前后置脚本也被禁用了。单独开启该请求，还要一个个开启前置脚本/后置脚本

### 重现步骤

【接口自动化】批量关闭步骤-请求会被禁用，前后置脚本也被禁用了。单独开启该请求，还要一个个开启前置脚本/后置脚本
![image](https://github.com/metersphere/metersphere/assets/104960608/9fffb3ba-0cee-48b8-bdec-a5cb484e47f7)

**Comment by fit2-zhao** [comment]
感谢您的建议，如果我没理机错，您再用批量开启是否就能解决，您单独禁用一个请求，里面的前后置脚本也不会同步禁用的，这里的操作并没有什么级联关系。
