### ISSUE TITLE
[BUG]UI自动化场景导入其他步骤较多场景时，添加步骤会出现序号增长但步骤空白的情况

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27797]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

UI自动化场景导入其他步骤较多场景时，例如本场景内添加其他场景步骤，在被导入场景内添加步骤会出现序号增长，但是步骤空白的情况

### 重现步骤

1、打开某个UI自动化场景
2、导入其他UI自动化场景（步骤尽量多一点）
3、在其他自动化场景内添加步骤
（某一个导入的场景步骤超过90可复现）

### 附加信息

<img width="655" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/0f3fb132-ca79-4266-a03b-9ba8682b1561">

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.10-lts修复。
