### ISSUE TITLE
[BUG] Let's Encrypt 证书的https接口测试失败

### ISSUE THREAD

**Issue by zhangjiezhang** [metersphere/metersphere#27796]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

Let's Encrypt 证书的https接口测试失败

### 重现步骤

![681F5945-A0EC-47CF-AC19-3BCB59D30992](https://github.com/metersphere/metersphere/assets/35765732/79ee717e-407a-4363-82bc-3bb45e38b0c8)

### 期待的正确结果

期望能正确获取接口响应

**Comment by zrfit** [comment]
您好，经沟通，v3进行调研优化,感谢理解和支持。
