### ISSUE TITLE
[FEATURE]接口测试加上目录功能

### ISSUE THREAD

**Issue by Bearzzzzz** [metersphere/metersphere#278]
**请描述您的需求或者改进建议.**
接口测试目前是以列表的形式展示的，这些测试的场景和目的不尽相同，在测试较多的情况下会比较混乱。建议采取类似【测试功能】下的【测试用例】布局方式，左侧也加上目录做层级维护。
![image](https://user-images.githubusercontent.com/52554843/91155164-098f8c80-e6f5-11ea-9549-306e8f38037e.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
目前已接口测试已在项目下增加左侧目录层级
