### ISSUE TITLE
MeterSphere的请求头经常要复制，目前这块复制操作不友好！

### ISSUE THREAD

**Issue by xmhawxp** [metersphere/metersphere#27800]
### MeterSphere 版本

v2.10.8-lts-313def9d

### 联系方式

15001148204

### 请描述您的需求或者改进建议

MeterSphere的请求头经常要复制，目前这块复制操作不友好！

针对通过请求头进行授权认证的接口，目前请求头只能一个一个复制，而不能大批量复制

### 请描述你建议的实现方案

MeterSphere针对MeterSphere的请求头、参数、请求体等等都实现postman的Bulk Edit功能

### 附加信息

目前飞致云的bin（微信名）在跟踪此事

**Comment by luty2018** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
