### ISSUE TITLE
[BUG] 使用idea插件同步接口到ms，修改api的字段内容后无法保存。

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27807]
### MeterSphere 版本

v2.10.9

### 使用外置数据库

否

### 问题描述

使用idea插件同步接口到ms，修改api的字段内容后无法保存。

### 重现步骤

1.idea插件版本1.2.5
2.使用插件同步接口到ms平台
3.修改接口中字段值
4.点击保存报错

### 期待的正确结果

idea插件同步到ms的接口，可以修改并且保存。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/55130444/fcf2f2f0-671a-4422-8248-8327809e2a2a)

**Comment by 13290445582** [comment]
您好，使用最新的1.2.6版本的idea插件未复现该问题，请使用1.2.6版本的idea插件测试下有此问题吗？

**Comment by kaijie-yu** [comment]
我验证下。

**Comment by kaijie-yu** [comment]
1.2.6插件没有问题
