### ISSUE TITLE
[BUG]功能用例脑图模式下，剪切复制快捷键会导致结构错乱

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27808]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

功能用例脑图模式下，剪切模块及用例信息，粘贴后会导致结果错乱

### 重现步骤

可参考附件内容

### 附加信息

https://github.com/metersphere/metersphere/assets/32027713/a68323ce-0e95-4b2d-b11f-b76a8dc4f6fe

**Comment by 13290445582** [comment]
您好，计划后续版本修复该问题，感谢理解。

**Comment by Hyyfit** [comment]
v3将会已覆盖该缺陷，请关注后续版本的发布；
