### ISSUE TITLE
[FEATURE] UI自动化中建议可以批量添加前置或者后置等待时间

### ISSUE THREAD

**Issue by huskiesir** [metersphere/metersphere#27812]
### MeterSphere 版本

 v2.10.8-lts

### 请描述您的需求或者改进建议

建议：UI自动化中建议可以批量添加前置或者后置等待时间
使用场景：UI测试时，有的页面加载慢，截图太快截不到完整的页面，所以需要在截图操作前面增加等待时间，但是每个步骤单独去添加等待时间又比较麻烦，所以需要批量添加等待时间。

### 请描述你建议的实现方案

<img width="1474" alt="image" src="https://github.com/metersphere/metersphere/assets/45967454/6728e0c9-bd2d-4afe-80af-17bf747e88f1">

**Comment by Hyyfit** [comment]
感谢反馈，v3会覆盖
