### ISSUE TITLE
[FEATURE] 优化 ：脑图用例模版校验当，TC 用例等级标签后空格总是导不进去/或导进去格式不对，用例多的时候挨着去改很费时间，希望用例标签不校验空格

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27839]
### MeterSphere 版本

2.10.6

### 请描述您的需求或者改进建议

脑图用例模版校验当，TC 用例等级标签后空格总是导不进去/或导进去格式不对，用例多的时候挨着去改很费时间，

希望用例标签不校验空格

### 请描述你建议的实现方案

希望脑图格式标签不校验空格

### 附加信息

![Snipaste_2023-12-06_10-07-47](https://github.com/metersphere/metersphere/assets/43202800/e79603a7-5405-4326-8752-b125c287fd38)
![111](https://github.com/metersphere/metersphere/assets/43202800/f6c4787e-972b-4d1e-9dd7-d9ce7a0678e0)

**Comment by Hyyfit** [comment]
感谢反馈，v3已规划覆盖；
