### ISSUE TITLE
[BUG]复制的环境配置，更改里面变量值之后，值还会使用复制前的数据。

### ISSUE THREAD

**Issue by guguangjie-pacvue** [metersphere/metersphere#27830]
### MeterSphere 版本

2.10.8-lts

### 使用外置数据库

否

### 问题描述

复制的环境配置里面更改过的值，经常会又恢复到更改前。

### 重现步骤

1. 有一个环境配置名字叫A。
2. 复制A这个环境配置（B)，更改里面变量的值并保存。
3. 打开配置A。
4. 再次打开环境配置B，之前更改的又变成A里面的值了。

### 期待的正确结果

复制的环境配置里面变量的值不会乱窜。

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v2.10.9-lts没有复现该问题，建议升级到这个版本试试。如果还会出现，请贴个修改参数页面的图，非常感谢～

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。感谢理解和支持。
