### ISSUE TITLE
[BUG]接口测试-接口定义，当接口路径最后有空格时，不会自动删除，会拼接到接口上

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#27838]
### MeterSphere 版本

v2.10.9,v2.10.8

### 使用外置数据库

否

### 问题描述

接口测试-接口定义，当接口路径最后有空格时，不会自动删除，会拼接到接口上

### 重现步骤

新增接口定义，接口路径最后增加空格，然后调试接口
![image](https://github.com/metersphere/metersphere/assets/55130444/7e606d99-97e7-454f-8fdd-3f9f9e8f07f3)

### 期待的正确结果

希望可以把接口路径末尾的空格去掉

**Comment by youliyuan-fit2cloud** [comment]
v2.10.10-lts 中已修复。
