### ISSUE TITLE
[BUG]MS占用空间太多

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#27831]
### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

MS占用空间太多

### 重现步骤

1、机器未安装任何服务，只安装ms
2、下面截图是执行了 sudo docker system prune -a -f 命令的结果

### 期待的正确结果

如何释放空间出来。数据库我看是39G ms-data也有数据好像也是30多G。  如何释放空间以及数据库优化一下

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/92c1c7be-d8db-4fac-a109-535f2ae8bf5a)
![image](https://github.com/metersphere/metersphere/assets/19423100/27f29689-df19-4e51-bcba-6a591df515cd)

**Comment by fit2-zhao** [comment]
可以先从以下步骤进行处理：

1 数据库占用方面，可以从项目管理-应用设置中 配置定时清理报告，把部分历史报告清理掉。
2 文件目录中找到 /opt/metersphere/logs 中把历史日志清理了，也可以按照安装配置设置历史日志保留时间。
3 选择性把container清理清理。

ps: 以上处理如果还是未解决，请把 volumes 占用详细情况贴出来看一下。

**Comment by legend818** [comment]
1、 一直只保留2天报告
2、这个处理了。data目录占用大
![image](https://github.com/metersphere/metersphere/assets/19423100/d1f206e8-40da-4825-8858-b951b8dbed6d)
3、container有什么可以清理的么，贴图
![image](https://github.com/metersphere/metersphere/assets/19423100/fec205a2-4bf0-479c-8541-d60576a23074)

 PS：volumes 占用详细情况贴出来看一下。
![image](https://github.com/metersphere/metersphere/assets/19423100/abfe303a-998c-4b7b-a53d-018ceaa32144)

**Comment by legend818** [comment]
1、 一直只保留2天报告
2、这个处理了。data目录占用大
![image](https://github.com/metersphere/metersphere/assets/19423100/d1f206e8-40da-4825-8858-b951b8dbed6d)
3、container有什么可以清理的么，贴图
![image](https://github.com/metersphere/metersphere/assets/19423100/fec205a2-4bf0-479c-8541-d60576a23074)

 PS：volumes 占用详细情况贴出来看一下。
![image](https://github.com/metersphere/metersphere/assets/19423100/abfe303a-998c-4b7b-a53d-018ceaa32144)

**Comment by fit2-zhao** [comment]
可以看下data文件夹中具体哪个文件夹占比较大。

**Comment by legend818** [comment]
![image](https://github.com/metersphere/metersphere/assets/19423100/e613af73-5a58-4131-98bc-ce0ed6d75a10)
![image](https://github.com/metersphere/metersphere/assets/19423100/e97f83e9-a3a2-45c9-83fa-22491fc027a6)

**Comment by legend818** [comment]
![image](https://github.com/metersphere/metersphere/assets/19423100/49dc60c9-3fdb-4acb-aea7-2309d429b1aa)
按我理解我定时清理这个报告duiy对应的这张表数据是不是也该清理掉了。为了便于跟踪定位问题，我执行最多的是测试跟踪那边的测试计划， 每个计划关联了很多case
![image](https://github.com/metersphere/metersphere/assets/19423100/eda09b1a-b5a2-43df-a86b-0c852ace09f3)

**Comment by legend818** [comment]
咋没动静了

**Comment by fit2-zhao** [comment]
<img width="679" alt="image" src="https://github.com/metersphere/metersphere/assets/70558837/23e280ca-d08a-44d2-a598-fd7a3cf0f25c">

这里配置了吗？

**Comment by fit2-zhao** [comment]
从你的描述来看应该都是测试计划产生的报告，清理这个就行。

**Comment by legend818** [comment]
我认为是这里清理失败了，    我这个设置一直是这样
![image](https://github.com/metersphere/metersphere/assets/19423100/322bfc4c-2fa1-407f-8bde-25c77fdf1dc7)

**Comment by youliyuan-fit2cloud** [comment]
感谢持续反馈，后续版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
数据库中已修复，但是服务器本地未同步删除数据，但是是mysql 本地清理机制问题参考链接，暂时保持现状。建议用户自己删除。

https://bugs.mysql.com/bug.php?id=108101

![image](https://github.com/metersphere/metersphere/assets/54612864/a414470d-ca50-4b1b-909a-0f7c210191f4)

**Comment by legend818** [comment]
@youliyuan-fit2cloud 能与我直接对接，看看怎么删除本地的这个数据么

**Comment by youliyuan-fit2cloud** [comment]
> @youliyuan-fit2cloud 能与我直接对接，看看怎么删除本地的这个数据么

你好，可以在数据库中执行 如下命令，释放磁盘空间
ALTER TABLE _table_name_ ENGINE = InnoDB;
table_name 替换为实际的表名，执行过程中需要时间较长，且会锁表，建议无人使用系统时执行。

**Comment by chenshan123456** [comment]
> > @youliyuan-fit2cloud 能与我直接对接，看看怎么删除本地的这个数据么
> 
> 你好，可以在数据库中执行 如下命令，释放磁盘空间 ALTER TABLE _table_name_ ENGINE = InnoDB; table_name 替换为实际的表名，执行过程中需要时间较长，且会锁表，建议无人使用系统时执行。

你好，请问要清理测试计划报告的话，对应数据库的表具体是哪几张
