### ISSUE TITLE
 [FEATURE] 拖拽步骤的时候希望横线是再步骤中间，而不是标识步骤上方， 不确定是托拖在上面还是下面的. 希望能有个展位显示

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27846]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

拖拽步骤的时候希望横线是再步骤中间，而不是标识步骤上方， 不确定是托拖在上面还是下面的. 希望能有个展位显示
![image](https://github.com/metersphere/metersphere/assets/114552960/92cc437b-89d8-47f7-b229-a45c8dbd5a41)

**Comment by luty2018** [comment]
感谢建议， 我们优化一下
