### ISSUE TITLE
[FEATURE] 优化：接口自动化场景编排，引用的用例 id, 希望添加一个超链接样式，用户看到知道点击会跳转避免拖拽步骤跳转影响使用

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27844]
### MeterSphere 版本

2.10.8

### 请描述您的需求或者改进建议

接口自动化场景编排，本来是想拖拽，结果误触到id 跳转页面了，操作不友好
![接口自动化场景编排，本来是想拖拽，结果误触到id 跳转页面了，操作不友好](https://github.com/metersphere/metersphere/assets/43202800/c21200e2-12c1-4874-b1dd-570da011597f)

**Comment by luty2018** [comment]
v3已规划
