### ISSUE TITLE
[FEATURE] 优化: 功能用例文本，当文本较长时，查看文本会自适应编辑框但是编辑用例不能自适应，希望编辑也可以自适应

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27840]
### MeterSphere 版本

2.10.8

### 请描述您的需求或者改进建议

功能用例文本，当文本较长时，查看文本会自适应编辑框但是编辑用例不能自适应，希望编辑也可以自适应
![但是编辑用例不能自适应，希望编辑也可以自适应](https://github.com/metersphere/metersphere/assets/43202800/d3ca04ff-38c8-4f63-9e70-d5a72486cad9)

### 请描述你建议的实现方案

希望编辑也可以自适应

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
