### ISSUE TITLE
[BUG] 当前用户没有接口测的权限，但是创建测试计划可以选择到 ， 权限没有隔离开

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27842]
### MeterSphere 版本

2.10.8

### 使用外置数据库

否

### 问题描述

当前用户没有接口测的权限，但是创建测试计划可以选择到 ， 权限没有隔离开

### 重现步骤

1、用户a 再项目a下面只赋予 测试跟踪模块的权限  
2、用户a 创建测试计划，可以选择当，项目a下面的接口

没有达到权限隔离的效果
![当前用户没有接口测的权限，但是创建测试计划可以选择到 ， 权限没有隔离开](https://github.com/metersphere/metersphere/assets/43202800/17da087a-234b-4102-8fc3-443167945acc)

### 期待的正确结果

希望按照菜单隔离权限，用户a看不到项目a的接口测试数据

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已知，考虑修改类似问题影响范围较大，暂时不处理了。
