### ISSUE TITLE
[FEATURE]  经常遇到被测试环境网络不通的情况，期望能在编辑环境的时候curl 一下校验网络是否通过

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27848]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/114552960/c100a42a-1bfc-47e3-9264-a9bd4b420474)
经常遇到测试环境网络不通的情况，期望能在编辑环境的时候curl 一下校验网络是否通过

**Comment by liqiang-fit2cloud** [comment]
因为安全原因，curl命令被禁止执行。
实际上，ping、curl、telnet都不是很好的方案，所以目前还是需要手动验证连通性。
