### ISSUE TITLE
[FEATURE] 接口自动化界面布局，期望能增加一个目录导航类似功能。当步骤较多，查找步骤切换步骤，拖拽步骤都不方便

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27843]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

接口自动化界面布局，期望能增加一个目录导航类似功能。当步骤较多，查找步骤切换步骤，拖拽步骤都不方便
![image](https://github.com/metersphere/metersphere/assets/114552960/5659b2d4-e043-45eb-a246-f45e0670df28)

![image](https://github.com/metersphere/metersphere/assets/114552960/dae0c1ce-869b-4e78-b616-1d4ad42fad65)

**Comment by luty2018** [comment]
感谢建议， 我们调研一下！
