### ISSUE TITLE
[FEATURE] 一个自动化用例中会测试4个账号，用到4个不同的token，怀疑测试过程中没有用到指定的token，目前测试报告日志是对应用例的，能否有所有步骤对应的日志（统一导出excel），方便分析上下文执行过程；

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27847]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

一个自动化用例中会测试4个账号，用到4个不同的token，怀疑测试过程中没有用到指定的token，目前测试报告日志看请求内容参数是对应用例的 挨着切换很多步骤看不全，

期望能有所有步骤对应的请求 响应参数日志（比如按步骤顺序统一导出excel），方便分析上下文执行过程；

**Comment by luty2018** [comment]
可以在需要验证的步骤后 加一个后置脚本 log.info 输出看一下。
另外我们测试最终都是发到被测系统的，可以通过被测系统的日志也能分析。

**Comment by opopjasica** [comment]
好吧
