### ISSUE TITLE
[FEATURE] 优化：用例执行的时候，点击标题修改跳转页面很多次，希望可以在用例执行页面增加一个编辑按钮，直接再执行页面修改用例，减少操作步骤

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27841]
### MeterSphere 版本

2.10.8

### 请描述您的需求或者改进建议

优化：用例执行的时候，点击标题修改跳转页面很多次，希望可以在用例执行页面增加一个编辑按钮，直接再执行页面修改用例，减少操作步骤

![image](https://github.com/metersphere/metersphere/assets/43202800/17be4798-2952-4193-861a-c4938ce6fa8f)

### 请描述你建议的实现方案

希望方便执行用例的编辑权限，加个编辑按钮等操作
修改过程记录变更日志

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
