### ISSUE TITLE
[FEATURE] 使用优化：接口自动化，用例编排控制器添加，会遮挡到步骤操作...删除。希望步骤编排+  可以悬浮拖拽位置

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27845]
### MeterSphere 版本

2.10.8

### 请描述您的需求或者改进建议

使用优化：接口自动化，用例编排控制器添加，会遮挡到步骤操作...删除。希望步骤编排+  可以悬浮拖拽位置

![遮挡，拖拽+](https://github.com/metersphere/metersphere/assets/43202800/9123a5a0-cbeb-46fc-bf62-d8fdc26efa09)

### 请描述你建议的实现方案

希望步骤编排+  可以悬浮拖拽位置

**Comment by luty2018** [comment]
v2应该不该这里， 挡住的行建议上下滚动再操作
