### ISSUE TITLE
[BUG]【接口测试】请求参数是固定的可以正常请求成功，若使用变量(环境变量)的话，就请求失败。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27850]
### MeterSphere 版本

 v2.10.6-lts

### 使用外置数据库

否

### 问题描述

【接口测试】请求参数是固定的可以正常请求成功，若使用变量(环境变量)的话，就请求失败。

### 重现步骤

【接口测试】请求参数是固定的可以正常请求成功，若使用变量(环境变量)的话，就请求失败。
![image](https://github.com/metersphere/metersphere/assets/104960608/19cd82ba-c682-40e6-beb1-5d2fb79bb4b0)
![image](https://github.com/metersphere/metersphere/assets/104960608/a052ebef-14b4-4e23-bd38-14c92ea0b74e)

![image](https://github.com/metersphere/metersphere/assets/104960608/59c15458-ef99-4d64-afa1-3e345de9aa3f)
![image](https://github.com/metersphere/metersphere/assets/104960608/5430ed9a-767e-4f3e-bc1a-812430f32cf0)
![image](https://github.com/metersphere/metersphere/assets/104960608/7dc25e2f-383c-4849-a26d-a47aad9cabba)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现该问题，是否尝试在最新版本试试该场景？如果仍复现请把场景文件贴上，我们进一步排查下原因。

**Comment by 2lipan** [comment]
升级到最新 v2.10.9-lts 版本，该问题仍然存在。
![image](https://github.com/metersphere/metersphere/assets/104960608/761efbeb-a754-46ac-86dc-0c253e30de24)
![1702449852778](https://github.com/metersphere/metersphere/assets/104960608/b784b95f-d0b6-4c9e-9548-f354ad0daa08)

**Comment by fit2-zhao** [comment]
非变量本身问题，是底层测试引擎JMeter对于json中存在变量&参数还有转译\\ 时 处理后会改变原始格式导致
![image](https://github.com/metersphere/metersphere/assets/70558837/ac81876b-fafc-4843-856d-337ecb7db86d)

详细可参照 https://github.com/metersphere/metersphere/issues/23210

建议这种数据格式尽量避开变量的使用。
