### ISSUE TITLE
[FEATURE]建议功能用例关联需求的时候，可以展示需求的第三方平台ID

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#27853]
### MeterSphere 版本

v2.10.9-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

]建议功能用例关联需求的时候，可以展示需求的第三方平台ID

### 请描述你建议的实现方案

目前会展示需求名称，但是用户实际环境中可能会遇到相同名称的需求，不太好辨别。
而目前的/issues/demand/list/projectId接口会获取需求的第三方平台ID，希望可以在v2.10.10-lts小小的优化下，可以在选需求时候展示下ID。
![image](https://github.com/metersphere/metersphere/assets/88763608/fef561eb-8ff7-41e4-a53b-b9f8f0cbdde7)
![image](https://github.com/metersphere/metersphere/assets/88763608/9c1fe470-3d29-46c2-9bf5-ad0c8feef188)

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
