### ISSUE TITLE
[BUG] 在请求接口的时候，如果运行环境使用的是【模块】或【路径】方式，在调用接口的时候，对应环境域名没有拼接具体的接口路径地址

### ISSUE THREAD

**Issue by 0x22E09-8** [metersphere/metersphere#27857]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

在请求接口的时候，如果运行环境使用的是【模块】或【路径】方式，在调用接口的时候，对应环境域名没有拼接具体的接口路径地址

### 重现步骤

1. 在环境HTTP配置中 配置模块或域名的url地址，选择或输入模块或路径
2.  测试执行当前模块下的对应的接口（选择 1 配置好的模块域名url）
3. 

### 期待的正确结果

能够正常执行模块或路径域名下对应的接口并返回正确的响应

### 附加信息

1.配置好的模块域名
![image](https://github.com/metersphere/metersphere/assets/28555655/a532d85b-8f2c-4356-bbe4-0180edc7f678)

2.在对应模块下执行接口测试
![image](https://github.com/metersphere/metersphere/assets/28555655/8c395b3f-98db-4b6d-969d-3c3f3108e797)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请检查下“其他设置”里面 选中的是“跟随重定向”还是“自动重定向”，这里是有区别的。其他接口是否也存在该问题？如果其他接口也存在请将详细信息截图贴上，包括响应体、控制台、请求内容和环境配置信息，谢谢～

**Comment by 0x22E09-8** [comment]
重新把自动重定向都取消后，正常了。谢谢
