### ISSUE TITLE
[BUG][接口自动化]带循环控制器的场景调试结束后，状态一直显示运行中

### ISSUE THREAD

**Issue by vivage** [metersphere/metersphere#27852]
### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

1、带循环控制器的场景调试结束后，状态一直显示运行中
2、测试计划中定时任务运行也有此问题

### 重现步骤

1、参照附件图示创建场景
2、手动运行场景用例或定时任务运行场景

### 期待的正确结果

运行结束后给出运行结果，且状态显示正确

### 附加信息

![90fff1904c656a2533c46e4500db498](https://github.com/metersphere/metersphere/assets/117417157/ee341db4-2f50-4f88-a349-0eafe7443981)
![767322838a1857d64e5515d6d37943a](https://github.com/metersphere/metersphere/assets/117417157/259b5abb-71cd-4723-ae3f-f756dab2f830)
![image](https://github.com/metersphere/metersphere/assets/117417157/f80a1ea6-00b2-4888-a920-f597dce1d1ae)
![image](https://github.com/metersphere/metersphere/assets/117417157/57ef374f-64ea-486b-b04c-56f5e1c00416)
![image](https://github.com/metersphere/metersphere/assets/117417157/23c6abcf-15b1-4bde-9e6c-4d6d22e3efb5)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，测试环境参考上诉场景没有复现该问题，不是很清楚循环控制器和里面的条件控制器的变量是怎么配置的，方便把这个场景发我们试试吗？

**Comment by vivage** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][接口自动化]带循环控制器的场景调试结束后，状态一直显示运行中 (Issue #27852)





 
感谢反馈，测试环境参考上诉场景没有复现该问题，不是很清楚循环控制器和里面的条件控制器的变量是怎么配置的，方便把这个场景发我们试试吗？

**Comment by youliyuan-fit2cloud** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年12月6日(星期三) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG][接口自动化]带循环控制器的场景调试结束后，状态一直显示运行中 (Issue #27852) 感谢反馈，测试环境参考上诉场景没有复现该问题，不是很清楚循环控制器和里面的条件控制器的变量是怎么配置的，方便把这个场景发我们试试吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没收到附件 。。。

**Comment by vivage** [comment]
[Uploading 场景JMX文件集.zip…]()

**Comment by youliyuan-fit2cloud** [comment]
> Uploading

你好，这个附件仍然无法下载，请确认正确上传。

**Comment by vivage** [comment]
[场景JMX文件集.zip](https://github.com/metersphere/metersphere/files/13790485/JMX.zip)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/b0fa1bd7-fc26-4b4f-887b-f41781545a09)

感谢反馈文件，我们内部环境调试上图，是条件控制器步骤一直停不下来。
你这边也是这种情况？还是 “调试” 后一直是 停不下来？ 
怀疑是死循环了，建议检查下while循环是否正确。

**Comment by vivage** [comment]
对的，调试也是一直停不下来。定时任务执行对应场景也时好时坏的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月29日(星期五) 下午5:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][接口自动化]带循环控制器的场景调试结束后，状态一直显示运行中 (Issue #27852)





 
image.png (view on web)
 
感谢反馈文件，我们内部环境调试上图，是条件控制器步骤一直停不下来。
 你这边也是这种情况？还是 “调试” 后一直是 停不下来？

**Comment by youliyuan-fit2cloud** [comment]
我们计划下个版本修复一下。

**Comment by vivage** [comment]
![图示](https://github.com/metersphere/metersphere/assets/117417157/f82062a4-6ee2-4b18-8da3-9ef2272e7cc4)

**Comment by 13290445582** [comment]
您好，最新环境未再复现此问题，建议升级至最新环境使用，若问题仍存在，后续再反馈，感谢理解。
