### ISSUE TITLE
[BUG]缺陷管理中缺陷列表点击用例数，跳转后没有跳转到相关联的用例列表

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27869]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

缺陷管理中缺陷列表点击用例数，跳转后没有跳转到相关联的用例列表

### 重现步骤

1. 创建缺陷，关联跨项目的功能用例
2. 点击保存，点击用例数链接
3. 跳转到功能用例列表，列表上无关联的用例数据

### 期待的正确结果

缺陷管理中缺陷列表点击用例数，跳转到相关联的用例列表

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/9a7b285c-85df-4eae-a4d8-25fca813f4c5)
![image](https://github.com/metersphere/metersphere/assets/50016789/835ed426-14b0-4a8d-8b85-3ce8ee577ade)

**Comment by youliyuan-fit2cloud** [comment]
当前实现是点击用例数不跳转到用例详细，是打开缺陷详情。
