### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JianShengFei** [metersphere/metersphere#27864]
### 联系方式

snws_ajax@163.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

bug1. 通过idea插件推送到MS的接口，缺失了部分数据，如枚举对象、或者泛型字段导出到MS只有一个Object，Object节点下无任何信息
bug2. 这种空对象Object编辑后保存数据，出现错误，此问题只出现在响应内容
bug3. 文档的请求参数=》请求体，切换JSONscma展示时，从json切换回来后，描述等相关数据丢失

### 重现步骤

重现步骤，问题描述已完善

### 期待的正确结果

正常展示及保存

**Comment by zrfit** [comment]
您好，感谢反馈！经沟通，v2暂不支持，v3进行优化，感谢理解和支持。

**Comment by fit2-zhao** [comment]
https://plugins.jetbrains.com/plugin/24867-metersphere-api-debugger/edit/versions/stable/600994
https://github.com/metersphere/metersphere-idea-plugin/releases/tag/v3.2.0

@JianShengFei  在这个版本已经兼容了 V2 和 V3 版本可以下载试用。
