### ISSUE TITLE
[BUG]【测试跟踪】导入excle的功能用例后，修改用例进行保存后，在变更记录里没有记录，接口和后台均有抛异常

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27867]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】导入excle的功能用例后，修改用例进行保存后，在 变更记录里没有记录，接口和后台均有抛异常

### 重现步骤

【测试跟踪】导入excle的功能用例后，修改用例进行保存后，在 变更记录里没有记录，接口和后台均有抛异常
![image](https://github.com/metersphere/metersphere/assets/104960608/430762ba-da3a-4431-8a6d-ddb65ec3492d)
![image](https://github.com/metersphere/metersphere/assets/104960608/f67aeb7f-2675-47f8-850d-72a4743bcf36)

功能用例如下
[Metersphere_case.zip](https://github.com/metersphere/metersphere/files/13594493/Metersphere_case.zip)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.10-lts 中已修复。
