### ISSUE TITLE
[BUG] 使用脑图进行修改和新增用例，保存后，页面未报错，重新打开后，用例未保存上，数据丢失

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27866]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

使用脑图进行修改和新增用例，保存后，页面未报错，重新打开后，用例未保存上

### 重现步骤

重新提审里面的testcase对象 projectId为空
![image](https://github.com/metersphere/metersphere/assets/103925124/446be33a-96bb-4f2a-a6c7-b585e4d5f7df)
详细的日志文件需要私发，因为日志里面涉及到用户信息

**Comment by fit2cloud-yaochunrong** [comment]
这个缺陷不规划修复嘛？

**Comment by youliyuan-fit2cloud** [comment]
> 这个缺陷不规划修复嘛？

我们目前只根据错误日志尝试修复了一版，请升级到v2.10.10-lts版本尝试。
