### ISSUE TITLE
[BUG]禅道(企业版)关联异常

### ISSUE THREAD

**Issue by kohlersDagger** [metersphere/metersphere#27873]
### 联系方式

kohlersDagger

### MeterSphere 版本

v2.10.4-lts-a23f75d9

### 使用外置数据库

否

### 问题描述

与 `禅道企业版 v8.8` 对接后无法创建缺陷

### 重现步骤

1. 禅道对接成功
![image](https://github.com/metersphere/metersphere/assets/49938137/e87e1a3f-c6ae-4a7d-a766-a8e13e3e86e0)
2.  账户绑定成功
![image](https://github.com/metersphere/metersphere/assets/49938137/5828d6fd-430a-4e68-b014-65b463bfdca5)
3. 项目模版绑定
![image](https://github.com/metersphere/metersphere/assets/49938137/596ad29c-2bc7-4722-91b4-273feb5359ed)
4. 创建缺陷失败
在 `缺陷管理` 中手动创建，点击 `保存` 无反应，调试工具显示接口 405
![image](https://github.com/metersphere/metersphere/assets/49938137/fbbd660f-3857-44c4-a616-9782ca03e988)
5. 关联缺陷失败
在 `功能用例` 中进入某个用例，点击 `关联缺陷` -> `创建缺陷` 无反应，或响应 405，查看 `test-track` 容器日志，如下：

> 2023-12-07 16:30:28,565  WARN     org.eclipse.jetty.server.HttpChannel: 806 - /issues/plugin/custom/fields/35b017d0-8cc8-11ee-b6f4-0242ac160009
> jakarta.servlet.ServletException: Request processing failed: java.lang.NullPointerException: Cannot throw exception because  the return value of "io.metersphere.plugin.exception.MSPluginException.getException(Object)" is null
>	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1019)
>	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
>	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
>	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
>	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
>	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
>     后略

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，请参考下面链接文档检查下是否需要改zentao配置，如仍有问题随时反馈。
**https://metersphere.io/docs/v2.x/user_manual/system_management/workspace/?h=zentao#23**
![image](https://github.com/metersphere/metersphere/assets/54612864/cd9e91c3-787f-40e0-a71e-4d85ca5f8bf2)

**Comment by kohlersDagger** [comment]
已确认 zentao 账号具有相应的权限，即`管理员角色`(`超级model调用接口`)。
已确认zentao 配置文件 `requestType` 为 `PATH_INFO`

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/0c42ba60-82b9-4821-aae0-0d6071b1b405)
这个配置加上了吗？
另，这个日志不全，请贴上前后相关的更多日志。

**Comment by kohlersDagger** [comment]
加上 `$config->features->apiGetModel = true;` 后可正常创建缺陷并同步到 zentao , 多谢。
