### ISSUE TITLE
[BUG]【接口自动化】场景变量设置变量为0.5，if 控制器里 引用该变量，设置条件为 大于0，但是无法进入控制器里。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27872]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景变量设置变量为0.5，if 控制器里 引用该变量，设置条件为 大于0，但是无法进入控制器里。

### 重现步骤

【接口自动化】场景变量设置变量为0.5，if 控制器里 引用该变量，设置条件为 大于0，但是无法进入控制器里。
![image](https://github.com/metersphere/metersphere/assets/104960608/19369a64-1760-44e7-8614-f75e2bd9efed)

**Comment by fit2-zhao** [comment]
暂时不支持，目前使用的底层测试引擎JMeter对条件控制器解析使用 jexl3 去做的，对小数兼容性不太友好，建议使用整数作为条件去使用。

**Comment by 2lipan** [comment]
if的判断条件是小数，可能该数据从响应体里提取或者直接sql从数据库里查询出来的，比如金融方面，关于钱之类的，得到的就是个小数，这进不去if条件，这合理吗？

**Comment by fit2-zhao** [comment]
目前底层暂不支持，如果有这方面的需要请转需求，感谢支持。
