### ISSUE TITLE
[BUG]接口自动化场景中，如果一个场景加入，被引用了很多次的子场景，保存就很慢，而且会报错。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#27878]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.5lts

### 使用外置数据库

否

### 问题描述

接口自动化场景中，如果一个场景加入，被引用了很多次的子场景，保存就很慢，而且会报错。如果一个场景加入，只被引用了1次的子场景，保存就很快。同样的脚本，复制case的保存就很快，但是引用case的保存就很慢，大概慢了几十秒。
![e576479ec139a9e1ecf0481a45f0f36](https://github.com/metersphere/metersphere/assets/83771182/19d0615e-e443-4e88-80dc-4c96051bd6a6)
![48da114071425e78c48640d71139651](https://github.com/metersphere/metersphere/assets/83771182/5b5930c8-9511-41c2-ba47-4ade0ffeeb55)

### 重现步骤

接口自动化场景中，如果一个场景加入，被引用了很多次的子场景，保存就很慢，而且会报错。如果一个场景加入，只被引用了1次的子场景，保存就很快。

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，建议升级到最新版本v2.10.9-lts尝试。
