### ISSUE TITLE
[BUG]【接口自动化】场景里循环结果太多的话，右移按钮与添加场景 的按钮重合了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27870]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景里循环结果太多的话，右移按钮 与 添加场景 的按钮重合了。

### 重现步骤

【接口自动化】场景里循环结果太多的话，右移按钮 与 添加场景 的按钮重合了。希望能优化一下
![image](https://github.com/metersphere/metersphere/assets/104960608/77f8b2ab-cc77-4cb9-acc4-9bbf25d5101c)

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，mac还是windows？浏览器是什么？
<img width="996" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/974b4742-b226-4461-af8e-24e552a22db9">
