### ISSUE TITLE
[BUG]  接口测试---》测试报告   查看报告之后没有关闭页面的按钮，再看其他报告必须切换页面

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2787]
**MeterSphere 版本**
V1.9.2

**Bug 描述**
接口测试---》测试报告   查看报告之后没有关闭页面的按钮，如果想要看其他报告的话，必须要切换页面

**期待的正确结果**
报告页面应该有关闭按钮，可以关闭之后再看其他的报告

**截图**
如果有截图，请附上截图.
<img width="1439" alt="WechatIMG99" src="https://user-images.githubusercontent.com/32027713/118103981-1e3fbc00-b40d-11eb-8cb1-c4f431c8573a.png">

**Comment by xulinde** [comment]
您用的哪个版本，是有关闭按钮的
![image](https://user-images.githubusercontent.com/64065190/118111798-c5752100-b416-11eb-989f-3606adaadd50.png)

**Comment by dashenyucainiao** [comment]
V1.9.2

**Comment by zyyfit** [comment]
您好，后续会优化这个问题，目前您可以再次点击 导航中的 测试报告，会保留您的搜索结果显示测试报告列表
![image](https://user-images.githubusercontent.com/73461316/118520380-9ccd8e00-b76c-11eb-937f-9c7aa37c3b0f.png)
