### ISSUE TITLE
[FEATURE]接口case测试中添加一个case依赖，当前case依赖另外一个case的响应参数，后续也可以在场景中直接就同步了

### ISSUE THREAD

**Issue by 0x22E09-8** [metersphere/metersphere#27880]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/28555655/589b9a1d-c031-4135-9f6d-518b9be97647)

**Comment by 0x22E09-8** [comment]
在case调试的时候经常需要依赖的case 所以希望能考虑支持

**Comment by luty2018** [comment]
感谢建议， 这个我们调研一下， case这块的调试， 我们正在优化中。
