### ISSUE TITLE
[FEATURE]  接口定义的Case 需要提供复制功能，不然同样或者类似的Case,需要的固定参数要填写很多遍，很难推广下去

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2788]
**请描述您的需求或者改进建议.**
接口定义的Case 需要提供复制功能，可以复制之后，稍微修改就可以用了；不然同样或者类似的Case,需要的固定参数要填写很多遍，很难推广下去

**请描述你建议的实现方案**
接口定义的Case 需要提供复制功能

**Comment by xulinde** [comment]
接口定义的case是支持复制的，如图
![image](https://user-images.githubusercontent.com/64065190/118110170-abd2da00-b414-11eb-9e4c-954c4c6ddd5b.png)
