### ISSUE TITLE
[FEATURE]  ui步骤期望可以配置不同的颜色的步骤，通过这个颜色来备注重要性，太多了都是白色，还不不到步骤，也不好找

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#27887]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

  ui步骤期望可以配置不同的颜色的步骤，通过这个颜色来备注重要性，太多了都是白色，还不不到步骤，也不好找![image](https://github.com/metersphere/metersphere/assets/114552960/de3d63a8-dd29-4d7c-85f4-0ba3fa0f3931)

**Comment by luty2018** [comment]
感谢建议， 我们转给交互同学调研一下！
