### ISSUE TITLE
[BUG] UI用例涉及到自动关闭页面的操作时，下面步骤无法执行

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27897]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

UI用例涉及到自动关闭页面的操作时，下面步骤无法执行

<img width="890" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8e70519a-02b8-48bd-af17-829a249d4d5b">

### 重现步骤

1、建一个UI用例
2、打开一个网址
3、跳转一个新的窗口
4、新窗口点击按钮或者其他的可以自动关闭该窗口
5、查看这个下面的步骤是否会执行

### 期待的正确结果

UI用例涉及到自动关闭页面的操作时，下面步骤可以正常执行

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题计划下个版本修复。

**Comment by sss903065212** [comment]
好的

**Comment by youliyuan-fit2cloud** [comment]
@sss903065212  经开发反馈，如果浏览器页面关闭当前窗口时，还存在当前其他窗口，是可以的正常执行的。
考虑到当前迭代情况，通过修改用例流程可以避免的问题我们尽量不改代码，感谢理解和支持。

**Comment by sss903065212** [comment]
目前用例 打开了三个标签页ABC 浏览器页面关闭当前窗口C时，还存在当前其他AB窗口，后续步骤还是无法正常执行

**Comment by youliyuan-fit2cloud** [comment]
> 目前用例 打开了三个标签页ABC 浏览器页面关闭当前窗口C时，还存在当前其他AB窗口，后续步骤还是无法正常执行

没有复现。用例发出来，我们看看。

**Comment by youliyuan-fit2cloud** [comment]
经远程查看，暂时无法支持浏览器自身关闭页面再继续执行后续步骤的场景，感谢理解和支持。
