### ISSUE TITLE
[BUG] 接口定义批量复制版本数据，功能不生效

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27893]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口定义批量复制版本数据，功能不生效

### 重现步骤

复制到指定版本后，切换到指定版本，无数据
![image](https://github.com/metersphere/metersphere/assets/103925124/83e193fd-6f9b-4158-9e1b-d4357455a6d2)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题会在下个版本解决。

**Comment by youliyuan-fit2cloud** [comment]
和研发沟通后确认，这里的复制是只会复制用例和mock数据 ，不会复制接口数据。感谢理解和支持
