### ISSUE TITLE
[FEATURE] 通过swagger url导入接口文档报解析失败（接口地址为https）

### ISSUE THREAD

**Issue by q1763868326** [metersphere/metersphere#27894]
### 联系方式

1763868326@qq.com

### MeterSphere 版本

v2.1

### 使用外置数据库

否

### 问题描述

后端服务开启了自行签名的https证书 导致swagger url导入失败

### 重现步骤

尝试导入自签名https证书的swagger api

### 期待的正确结果

能够正常导入 （对应Java请求框架应该可以设置https免证书验证）

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，目前版本还不支持这种自签名证书导入api，已转需求，待调研后反馈。
