### ISSUE TITLE
[BUG]接口调试，资源池选择 k8s 执行，场景中带 csv ,无法执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27899]
### MeterSphere 版本

v1.20.24-lts

### 使用外置数据库

否

### 问题描述

接口调试，资源池选择 k8s 执行，场景中带 csv ,偶发无法执行，调试历史中有报错，无法读取 csv 

### 重现步骤

1. 项目设置-应用管理-接口测试，资源池选择 k8s 资源池
2. 场景调试，场景中带 csv 文件,偶发无法执行，控制台有报错
![image](https://github.com/metersphere/metersphere/assets/103627487/49fe10ae-b238-4320-bdcb-702abc9ef8b0)
![image](https://github.com/metersphere/metersphere/assets/103627487/05f7c93e-6495-4c20-8289-d0c1fe4e2def)
3. 去掉 csv 文件能正常执行，本地local 资源池能正常执行

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，建议升级到v2版本。v1版本非安全漏洞和非常严重bug不再发布版本，感谢理解和支持。
