### ISSUE TITLE
[BUG]接口场景自定义请求成功后，另存为接口提示请求无效

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#27890]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.9

### 使用外置数据库

否

### 问题描述

场景中，添加自定请求，输入https://www.baidu.com，调试通过后，选择另存为接口定义，提示请求无效

### 重现步骤

场景中，添加自定请求，输入https://www.baidu.com，调试通过后，选择另存为接口定义，提示请求无效

### 期待的正确结果

场景中，添加自定请求，输入https://www.baidu.com，调试通过后，选择另存为接口定义，点击保存，可以成功保存

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/de31ad5e-017e-4d81-aed2-fa54306f2125)

**Comment by fit2cloud-lijiaxin** [comment]
期望结果：另存为接口，可以自动获取页面定义的请求，并将协议类型，自动截取

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前只能手动改下接口请求路径，我们计划在v3版本中有优化，感谢理解和支持～

**Comment by luty2018** [comment]
v3已规划， 可以关注发布说明。
