### ISSUE TITLE
[FEATURE]测试跟踪下的测试用例， 可以新加一个“保存并复制”的功能，并在上方新增“关闭其他”的功能，tab页太多，一个一个关闭太累

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2789]
**请描述您的需求或者改进建议.**
用例保存后 需要关闭老窗口 ，点击保存并新增， 应该默认带上之前用例填写的  标签  优先级 。 另外， 复制后的用例  需要提供  保存并新增功能， 目前只有保存功能。一旦用例比较多，对用户来说，这是个灾难

**请描述你建议的实现方案**
 可以新加一个“保存并复制”的功能，并在上方点击右键新增“关闭其他”的功能，使用起来方便，才能推广更多的人使用

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下

**Comment by dashenyucainiao** [comment]
麻烦优先级高一点，不然推广不下去，操作起来太累了

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/118128956-23f9c980-b42e-11eb-950d-f2231e399cb7.png)
![image](https://user-images.githubusercontent.com/27671436/118128970-29efaa80-b42e-11eb-81f2-281416081c82.png)
你好，如截图所示，目前这两个功能都是具备的。

**Comment by dashenyucainiao** [comment]
是新增一个 “保存并复制”的功能，不是“保存并创建”
