### ISSUE TITLE
[FEATURE]  浏览器录制的接口计划 有200个接口 但是 接口自动化列表 展示步骤数1， 需要展示具体接口总数量

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2790]
**请描述您的需求或者改进建议.**

浏览器录制的接口计划 有200个接口 但是 接口自动化列表 展示步骤数， 需要新增展示具体“接口总数量”列，用户关心的是接口的数量，并非步骤数，实际算通过率的时候，也是按照接口数量来统计的，并非按照步骤数

**请描述你建议的实现方案**
浏览器录制的接口计划 有200个接口 但是 接口自动化列表 展示步骤数， 需要新增展示具体“接口总数量”列
<img width="1436" alt="WechatIMG100" src="https://user-images.githubusercontent.com/32027713/118105253-bd18e800-b40e-11eb-84d1-a41f6220db50.png">

**Comment by xulinde** [comment]
执行场景，测试报告会展示请求总数

**Comment by dashenyucainiao** [comment]
需要在列表中显示，方便理解，例如：就一个步骤，通过率99%有点不太好理解

**Comment by dashenyucainiao** [comment]
用户非常关注接口数，在列表中展示更直观
