### ISSUE TITLE
[BUG]操作日志页面登录日志无法查询

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#27904]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

操作日志页面登录日志无法查询

### 重现步骤

操作日志选择登录查询，查询不一致

### 期待的正确结果

见图，还有其他字段也不一致，只单独查询这张表进行分组的operating_log

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/c3236213-19c1-4c9a-86ea-0c0737dc5ea0)

![image](https://github.com/metersphere/metersphere/assets/19423100/8f962d0b-d576-4ea0-9c6b-e6db75fba5b9)

**Comment by zrfit** [comment]
您好，感谢反馈！
1、登录是系统级别的日志，请到系统-操作日志中查看，在工作空间-操作日志下查询是不显示的。
2、表格中页面中数据的统计是在以什么纬度统计的？是系统纬度、空间维度、还是项目维度？

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
