### ISSUE TITLE
[BUG]操作日志存在部分操作人加载不出来

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#27905]
### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

操作日志存在部分操作人加载不出来

### 重现步骤

操作日志存在部分操作人加载不出来，

### 期待的正确结果

下面图一个是加载不出来 一个是能加载出来的对比图

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/b6e9a710-bf3b-45de-bf0b-423b0edbae36)
![image](https://github.com/metersphere/metersphere/assets/19423100/60ca9441-1b5d-487e-8571-d66c408ea2c7)

**Comment by zrfit** [comment]
您好，感谢反馈！未复现该问题，在系统和空间操作日志下验证多次均显示。
![image](https://github.com/metersphere/metersphere/assets/99731894/3a3e217d-351e-4e6c-b5d5-9b04b28b1a84)

**Comment by legend818** [comment]
空间日志，可支持远程看看。联系我

**Comment by zrfit** [comment]
您好，确认下操作记录数据库显示正常吗？
