### ISSUE TITLE
[BUG]创建新用户并绑定对应项目，用新用户登录后，在项目列表中可以跳转到绑定的项目，但是点击成员时却显示无该项目权限

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27903]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

创建新用户并绑定对应项目，用新用户登录后，在项目列表中可以跳转到绑定的项目，但是点击成员时却显示无该项目权限

### 重现步骤

1. 创建新用户，绑定对应项目
2. 用新用户登录后，在项目列表中可以跳转到绑定的项目，但是点击成员时却显示无该项目权限

### 期待的正确结果

用新用户登录后，在项目列表中可以跳转到绑定的项目，但是点击成员时也可以正常显示绑定的成员

### 相关日志输出

```shell
无
```

### 附加信息

![1702289019212](https://github.com/metersphere/metersphere/assets/50016789/2c4404b3-7ed2-4f55-b433-47890c2b5276)
![1702289083360](https://github.com/metersphere/metersphere/assets/50016789/1fdef63a-e9b6-48c0-bf50-80e98a7600ae)
![1702289117289](https://github.com/metersphere/metersphere/assets/50016789/786e2d0c-46a4-42dd-8786-5cf69dae6e7b)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请检查下 “工作空间管理员”用户组的权限是否开启编辑/添加成员等权限。
![image](https://github.com/metersphere/metersphere/assets/54612864/e8c6f13f-7a93-4913-9ea0-32731ccc8faf)

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
