### ISSUE TITLE
[BUG]项目管理列表中创建人筛选条件数据不对

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27900]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

项目管理列表中创建人筛选条件数据不对，有其他创建人，却只显示了Administrator

### 重现步骤

1. 创建test2 成员，创建项目
2. 项目管理列表中，使用创建人的筛选，发现下拉数据只有Administrator

### 期待的正确结果

项目管理列表中创建人筛选条件数据正确，下拉数据可以展示其他创建人

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/b36d5614-8506-42bb-94ff-36b6d4880915)
![image](https://github.com/metersphere/metersphere/assets/50016789/ce5afa70-f3a9-4c55-81ef-8db79d55eb48)
![image](https://github.com/metersphere/metersphere/assets/50016789/1a746f74-23f5-434b-a0fa-d8351ac33b1a)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题下个版本修复。
另外，非admin账号登录筛选没有该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.10-lts 中已修复。
