### ISSUE TITLE
[BUG]登出没有记录操作人

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#27906]
### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

登出没有记录操作人

### 重现步骤

登出没有记录操作人

### 期待的正确结果

登出没有记录操作人

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/19423100/50bd0854-ba7e-46eb-872b-72e343e10e55)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.10-lts修复。

**Comment by zrfit** [comment]
您好，v2.10.10-lts未在复现该问题，请升级尝试。
