### ISSUE TITLE
[BUG]测试计划的场景中有pending状态且没有数据展示并且执行时长为0ms

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27908]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

偶现测试计划中的场景 error状态的用例里面的步骤没有日志且执行时间为0ms
![image](https://github.com/metersphere/metersphere/assets/40912189/8d7549de-e2bd-41f7-91d1-6baf35430373)
<img width="1120" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/2680f89f-5bc7-4687-93cf-14705b9aa072">

可以提供该报告和对应的服务器容器的日志

### 重现步骤

1、建一个测试计划
2、创建一个场景CSV数据驱动的循环（其中某几行数据最好出现error）
3、测试计划关联该测试计划
4、观察测试计划的该用例

### 期待的正确结果

测试计划中的场景 error状态的用例里面的步骤有日志且执行时间不要为0ms

**Comment by 13290445582** [comment]
您好，目前尚未复现该问题，后续会持续关注该问题，感谢理解。

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，暂时关闭该issue，感谢理解与支持。
