### ISSUE TITLE
[BUG]【UI测试】打开网页后再关闭网页，下个步骤是再打开其他网页，发现没有执行

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27910]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【UI测试】打开网页后再关闭网页，下个步骤是再打开其他网页，发现没有执行

### 重现步骤

【UI测试】打开网页后再关闭网页，下个步骤是再打开其他网页，发现没有执行
![image](https://github.com/metersphere/metersphere/assets/104960608/b6bc1982-e6aa-42c1-90b1-07dfc2c25530)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #27897
参考上述issue反馈，感谢理解和支持。
