### ISSUE TITLE
[FEATURE]接口自动化 调试单个接口， 一点执行， 整个场景页面全部收起来了，看不到结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2791]
**请描述您的需求或者改进建议.**

接口自动化 调试单个接口， 一点执行， 整个场景全部收起来了，看不到结果，需要重新点开才能找到结果

**请描述你建议的实现方案**
单个接口的调试，直接放开，可以实时看到结果

**Comment by xulinde** [comment]
您用的是哪个版本呢，正常是不会收起来的

**Comment by dashenyucainiao** [comment]
V1.9.2
