### ISSUE TITLE
[BUG]测试资源池启用时报错

### ISSUE THREAD

**Issue by HOWRU1122** [metersphere/metersphere#27916]
### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

是

### 问题描述

<img width="1564" alt="截图" src="https://github.com/metersphere/metersphere/assets/58922479/2db9eecc-a41c-4c57-9a9d-95195b0a0911">

### 重现步骤

测试资源池启用时报错

**Comment by youliyuan-fit2cloud** [comment]
你好， 这个提示中说到 资源池 不对，请检查下这个资源池的node信息是否正确并可用。

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
