### ISSUE TITLE
[BUG]【环境配置】在某个环境名称处，设置了通用设置后，切换到其他环境，也设置了通用设置，点击确定按钮，发现只保存了当前环境的通用变量设置

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27925]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【环境配置】在某个环境名称处，设置了通用设置后，切换到其他环境，也设置了通用设置，点击上面的确定按钮，发现只保存了当前环境的通用变量设置

### 重现步骤

【环境配置】在某个环境名称处，设置了通用设置后，切换到其他环境，也设置了通用设置，点击上面的确定按钮，发现只保存了当前环境的通用变量设置
![image](https://github.com/metersphere/metersphere/assets/104960608/7513ecd5-6179-403d-a78f-890117fc3819)
![image](https://github.com/metersphere/metersphere/assets/104960608/1cd0a359-3aa7-4ed3-ab97-80e54b64859d)
![image](https://github.com/metersphere/metersphere/assets/104960608/574a2255-4bcb-4946-884e-8e269de1bf2c)

**Comment by 13290445582** [comment]
您好，已确认设计如此，非缺陷，感谢理解。
