### ISSUE TITLE
[BUG] 接口场景导入postman缺失url路径

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27921]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

<img width="500" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/9163b9b7-c845-450d-807d-2698fc3e9862">
<img width="1227" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8c8706e3-8afd-44f7-b923-d7149e04b55a">

### 重现步骤

1、导出一个 Postman Collection v2.1 格式的 json 文件
2、导入到MS接口场景中
3、查看步骤中的URL
<img width="683" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/32313954-80dd-4008-8eab-f1d17c521bb4">

### 期待的正确结果

期望导入之后不要缺失URL

**Comment by 13290445582** [comment]
感谢反馈，计划下版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
