### ISSUE TITLE
[BUG] 接口场景导入的postman-collection 点击调试一直卡在调试中没有信息返回

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27922]
### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

否

### 问题描述

<img width="1367" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/8f302733-f66c-4eb6-9a21-1cd03403a5db">

### 重现步骤

1、导出一个 Postman Collection v2.1 格式的 json 文件
2、导入到MS接口场景中
3、点击执行

### 期待的正确结果

这种一直停在调试中且没有任何信息返回是否正常？

**Comment by 13290445582** [comment]
您好，请问导入到MeterSphere中的接口在Postman中可以正常调试吗？

**Comment by sss903065212** [comment]
你好，问题点不在于是否可以在postman中调试，而是这种情况没有信息给出反馈，一直停留在这个页面，什么状态也没有，日志也没有

**Comment by 13290445582** [comment]
<img width="952" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/ad4cfcc3-963c-41ee-84b3-87d145102a18">
请求未调通连接失败，会有60s的超时报错。
