### ISSUE TITLE
[BUG]接口场景的前后脚本中有注释的函数时，无法调试

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#27926]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

<img width="1210" alt="image" src="https://github.com/metersphere/metersphere/assets/40912189/5df46afa-6ace-4dd3-aa15-eaebc4cc683d">

脚本内容为：
//vars.put("a_birthdate", "${__groovy(import static java.util.Calendar.YEAR;import static java.util.Calendar.MONTH;import static java.util.Calendar.DATE;def date = Date.parse(vars.get('a_date_format')\, vars.get('currentTime'));date.updated(year: date[YEAR]-30\,month:date[MONTH]\,date:date[DATE]-100).format('yyyy-MM-dd');,)}");
log.info("asd");

### 重现步骤

1、新建一个场景
2、添加一个步骤如：自定义请求http://www.baidu.com
3、在前置或后置脚本中添加
//vars.put("a_birthdate", "${__groovy(import static java.util.Calendar.YEAR;import static java.util.Calendar.MONTH;import static java.util.Calendar.DATE;def date = Date.parse(vars.get('a_date_format')\, vars.get('currentTime'));date.updated(year: date[YEAR]-30\,month:date[MONTH]\,date:date[DATE]-100).format('yyyy-MM-dd');,)}");
log.info("asd");
4、点击调试

### 期待的正确结果

注释的函数不要影响场景

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/c33338c3-2242-45e0-bd61-a208ba010774)

最新版本中没有复现该问题，请升级一下吧。

**Comment by sss903065212** [comment]
https://github.com/metersphere/metersphere/assets/40912189/7c33d95a-9411-4da8-bb07-ac1af88c23b2

**Comment by sss903065212** [comment]
最新QA环境上测试的结果如上

**Comment by sss903065212** [comment]
@youliyuan-fit2cloud

**Comment by youliyuan-fit2cloud** [comment]
> 最新QA环境上测试的结果如上

是你选的资源池有问题，该资源池节点不可用了，和注释没关系，换个资源池试试吧。
