### ISSUE TITLE
本地打包部署，项目中多个前端项目最后部署架构是咋样的

### ISSUE THREAD

**Issue by ksice** [metersphere/metersphere#27928]
### 请描述您的问题

<img width="825" alt="image" src="https://github.com/metersphere/metersphere/assets/26266303/5d548c43-9604-49a2-a231-0a727640d0c1">
目录层级有很多fronted不知道最终的部署架构是啥样的

**Comment by ksice** [comment]
如果不采用一键安装包部署，二次开发一些东西，需要怎么部署呢，谢谢

**Comment by ksice** [comment]
https://metersphere.io/docs/v2.x/dev_manual/ 同时我发现这个指导文档中指明的前端启动项目npm run serve命令是错误的

**Comment by shenkaibo** [comment]
> https://metersphere.io/docs/v2.x/dev_manual/ 同时我发现这个指导文档中指明的前端启动项目npm run serve命令是错误的
已修复 https://metersphere.io/docs/v2.x/dev_manual/#23

**Comment by shenkaibo** [comment]
> 如果不采用一键安装包部署，二次开发一些东西，需要怎么部署呢，谢谢

每个微服务都有对应的 Dockerfile 可单独打成容器镜像，然后替换一键部署的容器。

**Comment by ksice** [comment]
<img width="1098" alt="image" src="https://github.com/metersphere/metersphere/assets/26266303/5ba6439c-02ff-4a04-b296-0bc0099a8592">
docker build这个路径是不对的，因为我们打包之后是没有dependency的

**Comment by ksice** [comment]
还有个问题想请教一下，后端服务启动会自动运行前端，那你们这样的话前后端怎么联调呢

**Comment by chengkaisheng** [comment]
> <img alt="image" width="1098" src="https://private-user-images.githubusercontent.com/26266303/290369579-5ba6439c-02ff-4a04-b296-0bc0099a8592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MTM5MTEsIm5iZiI6MTcwMjYxMzYxMSwicGF0aCI6Ii8yNjI2NjMwMy8yOTAzNjk1NzktNWJhNjQzOWMtMDJmZi00YTA0LWIyOTYtMGJjMDA5OWE4NTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA0MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NWJkNmFiZTM1NzBiNWZhYThmMGQ0YWE5ZTNlNzI3MjA3ZWM2ODNkNmQ5N2IxZjVjZjA0ZmZiZWY0OGI0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHwF70feu3JaY3XF6HL_yFPL3fHMPMfWxb_1_iCsFis"> docker build这个路径是不对的，因为我们打包之后是没有dependency的

请问下这个问题解决了嘛

**Comment by 2han9wen71an** [comment]
> <img alt="image" width="1098" src="https://private-user-images.githubusercontent.com/26266303/290369579-5ba6439c-02ff-4a04-b296-0bc0099a8592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjkyMTgsIm5iZiI6MTcyNTQyODkxOCwicGF0aCI6Ii8yNjI2NjMwMy8yOTAzNjk1NzktNWJhNjQzOWMtMDJmZi00YTA0LWIyOTYtMGJjMDA5OWE4NTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1NDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YjlkMzdjMzE5ODA1OWU2OTJlNDMwMjkzYTM4MGFiZTNjYjRjNTgzNzA0MWJiNDlmMzU2Y2Q2OGY4NjI2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5H_I_iL8R3RAaVx3yfodN26DL1aBkvPQGNeWWPPxaRQ"> docker build这个路径是不对的，因为我们打包之后是没有dependency的

这个问题解决了嘛

**Comment by wws-test** [comment]
原生的dockerflie 确实是需要修改一下 按实际的路径修改即可
