### ISSUE TITLE
[FEATURE]关于用例高级搜索的改进需求

### ISSUE THREAD

**Issue by Shaady711** [metersphere/metersphere#27923]
### MeterSphere 版本

 v1.20.21-lts-6359b12e

### 联系方式

微信：MeterSphere交流群61 昵称：Yidi

### 请描述您的需求或者改进建议

在对用例进行高级搜索时，

1. 标签字段是否能支持匹配多个字段（例如同时包含“a” "b"）
2. 标签字段是否能支持匹配与或非逻辑(例如包含“a”,'不包含'b')，
3. 用例模板里的自定义字段是否能展示在高级搜索里作为一个搜索项
![企业微信截图_17024368492466](https://github.com/metersphere/metersphere/assets/123804272/e08e7fbb-3d55-433a-bc30-3bd4cc6eae83)

**Comment by luty2018** [comment]
已支持，请升级到v2版本使用 。
