### ISSUE TITLE
[FEATURE]测试用例 列表 名称 需要展示长一点， 标签和模块，更新时间 可以调短一点 ，用户更关注用例名称

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2792]
**请描述您的需求或者改进建议.**

测试用例 列表 名称 需要展示长一点， 标签和模块，更新时间 可以调短一点 ，用户更关注用例名称

**请描述你建议的实现方案**
测试用例 列表 名称 需要展示长一点， 标签和模块，更新时间 可以调短一点 ，用户更关注用例名称
<img width="1435" alt="WechatIMG101" src="https://user-images.githubusercontent.com/32027713/118108925-269af580-b413-11eb-9ad1-ad6f0cb70804.png">

**Comment by xulinde** [comment]
下个版本优化

**Comment by xulinde** [comment]
已优化成，表格拖拽固定列宽
