### ISSUE TITLE
[BUG]项目级权限设计有严重的漏洞

### ISSUE THREAD

**Issue by MrZbb** [metersphere/metersphere#27920]
### 联系方式

704464277@qq.com

### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

看了下项目级或者空间级的权限用的前端传过来的项目id跟空间Id来判断，用户可以绕过前端页面用postman来操作其他不属于自己项目的权限，代码层面逻辑问题![image](https://github.com/metersphere/metersphere/assets/31841743/08715cb6-00f0-45c6-9cc1-4a2488c0b54d)
![image](https://github.com/metersphere/metersphere/assets/31841743/6b56287b-be05-472d-8241-a5c4a42bb0ad)

### 重现步骤

我配置了一个只有demo项目1权限的用户
![1702432760265](https://github.com/metersphere/metersphere/assets/31841743/6a408b40-fa2e-48ab-9db4-79ebca584a14)

然后用这个用户通过postman删除了demo项目2的用例，并且成功了
![1702432779646](https://github.com/metersphere/metersphere/assets/31841743/4e6a8842-a376-4bf4-9e2f-bd4b6b0f1cbb)

**Comment by liuruibin** [comment]
感谢提醒，我们会在下次发布中修复这个问题。这里先关闭这个issue
