### ISSUE TITLE
[QUESTION] 同一个接口，相同的配置及规则，在本地用jemeter和在MS平台压测的结果差异非常大，想知道原因在哪里

### ISSUE THREAD

**Issue by 0x22E09-8** [metersphere/metersphere#27937]
### 请描述您的问题

本地客户端
![image](https://github.com/metersphere/metersphere/assets/28555655/7275084b-71ef-452c-a76a-cec23599d3c2)
![image](https://github.com/metersphere/metersphere/assets/28555655/c0189a32-e544-4213-bd08-82acb035e8ac)
![image](https://github.com/metersphere/metersphere/assets/28555655/f76c8d73-9031-4a62-b237-ec4b5cc48fbc)
MS平台
![image](https://github.com/metersphere/metersphere/assets/28555655/7850ef2b-9f45-481c-aeaa-66ac10a413b7)
![image](https://github.com/metersphere/metersphere/assets/28555655/e921705e-3d85-48e6-b3bb-1c1a7315cb23)

**Comment by liuruibin** [comment]
企业版的话，资源池配置哪里关闭后置监听器试试

**Comment by 0x22E09-8** [comment]
是社区版本，没有看到有关闭功能

**Comment by luty2018** [comment]
您好， jmeter在执行压测时， 提供了两种计算方式， 我们开源版和企业版分别使用了不同的计算方式， 导致了您现在看到的差异。

**Comment by 0x22E09-8** [comment]
感觉这个理由的逻辑没有太理解，在工具中没有错误率，但是平台却有错误率，计算方式不同 结果差距太大了，那这个功能就望而却步了，后续社区版的结果会有调整吗 还是结果只能保持现在这样了，那这个模块对于社区用户基本就等于没有什么用了

**Comment by luty2018** [comment]
> 感觉这个理由的逻辑没有太理解，在工具中没有错误率，但是平台却有错误率，计算方式不同 结果差距太大了，那这个功能就望而却步了，后续社区版的结果会有调整吗 还是结果只能保持现在这样了，那这个模块对于社区用户基本就等于没有什么用了

我们在最初进行性能测试模块的设计时，选择了离线计算jtl的方式来实现的。这一块在目前的项目上改造起来相对比较困难， 所以单独做了新的模块，提供给企业用户使用了。后续还是会放在企业版中，感谢理解。
