### ISSUE TITLE
[BUG]【接口自动化】当场景有很多自定义请求时，点击调试后，点击推荐jsonpath提取，会出现"请先执行调试获取响应结果"的提示，以及出现了jsonpath提取内容与响应内容不对应的问题。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27933]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】当场景有很多自定义请求时，点击调试后，点击推荐jsonpath提取，会出现"请先执行调试获取响应结果"的提示，以及出现了jsonpath提取内容与响应内容不对应的问题。

### 重现步骤

【接口自动化】当场景有很多自定义请求时，点击调试后，有的请求 点击推荐jsonpath提取，会出现"请先执行调试获取响应结果"的提示。
![image](https://github.com/metersphere/metersphere/assets/104960608/446b5f46-6939-4c6e-94d2-2233e6afcc15)
也有一些请求，点击推荐jsonpath提取，会出现jsonpath提取内容与响应内容不对应的问题
![1702448287078](https://github.com/metersphere/metersphere/assets/104960608/13c941c5-0540-4bee-9731-09fa87c0fe08)

**Comment by 13290445582** [comment]
感谢反馈，计划于下个版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
