### ISSUE TITLE
[BUG]跨项目引用时，sql脚本执行报错

### ISSUE THREAD

**Issue by Linxiuxiuo** [metersphere/metersphere#27942]
### 联系方式

MeterSphere 交流群28--秀🥕

### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

跨项目引用时，sql脚本执行报错

### 重现步骤

1.在A项目中编辑脚本，包含sql1.此时可正常执行成功。
2.在B项目引用步骤1的脚本，执行
执行到sql1时，报错“Name for DataSoure must not be empty in……”

### 期待的正确结果

正常执行引用脚本中的sql

### 附加信息

![ebdf1b4402293b1eabe6f1762c074ab](https://github.com/metersphere/metersphere/assets/153788638/5f5eb919-c44e-47fa-b0e5-4b26603c1505)

**Comment by 13290445582** [comment]
您好，请问您跨项目引用的是以下哪种形式SQL脚本？
1.引用了存在前置/后置sql的API/CASE执行错误
2.自定义SQL请求报错
3.有前置/后置SQL的自定义脚本
若是引用的第一种SQL脚本，请检查所使用运行环境有无正确的数据库配置？

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
