### ISSUE TITLE
[BUG]【接口自动化】导入swagger文档，发现json-schame处一个参数都没有，关闭json-schame还提示报错

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27945]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】导入swagger文档，发现json-schame处一个参数都没有，关闭json-schame还提示报错

### 重现步骤

【接口自动化】导入swagger文档，发现json-schame处一个参数都没有，关闭json-schame还提示报错
![image](https://github.com/metersphere/metersphere/assets/104960608/03d296cd-9b40-424e-a824-edbd345a0ed6)

swagger文件如下

[Uploading 合规问询.zip…]()

**Comment by 13290445582** [comment]
您好，经过查看您的swagger文件版本为3.1.0版本，我们支持 Swagger 2.0 与 3.0 版本的 json 文件，不适配3.1版本的文件，感谢理解。
