### ISSUE TITLE
dockerfile打包路径无效

### ISSUE THREAD

**Issue by ksice** [metersphere/metersphere#27941]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/26266303/1c70b244-6735-4a12-838c-4397d0f16514)
2.7新版本之后的dockerfile都不能使用，因为这个dependence路径不对，不知道是不是老版本未拆之前的路径

**Comment by liqiang-fit2cloud** [comment]
打包过程请参考https://github.com/metersphere/metersphere/blob/v2.10/Jenkinsfile

**Comment by ksice** [comment]
> 打包过程请参考https://github.com/metersphere/metersphere/blob/v2.10/Jenkinsfile

如果我想单独本地打包镜像，不走jenkins呢

**Comment by ksice** [comment]
> 打包过程请参考https://github.com/metersphere/metersphere/blob/v2.10/Jenkinsfile

好的我大概明白了，如果jar -xf进行解压之后到dependce的文件夹然后在进行build
