### ISSUE TITLE
[FEATURE]建议场景有多层嵌套时,可以有一个界面有多少变量,以及对应来源的接口/sql等信息

### ISSUE THREAD

**Issue by DoraemonYzx** [metersphere/metersphere#27955]
### MeterSphere 版本

 v2.7.0-34d44a5e

### 请描述您的需求或者改进建议

接口自动化场多个场景嵌套的场景,需要后期调试或者修改他人的用例时,不知道变量的来源以及使用的地方,维护过程困难

### 请描述你建议的实现方案

希望能有一个界面显示所有的变量名以及是从哪个接口/sql/脚本定义的, 以及使用在了哪个接口/sql/脚本中, 目前的参数列表需要点开每个接口 没办法看到全局.

**Comment by luty2018** [comment]
感谢建议， 这个我们调研一下
