### ISSUE TITLE
[BUG] 生成的压测报告PDF里响应时间图最后一部分点没有连接线

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2795]
**MeterSphere 版本**
v1.9.2-98b64776

**Bug 描述**
   压测后，导出PDF报告，发现测试概览里的响应时间**等**图，折线图的最后一部分总是没有折现连接。

**Bug 重现步骤**
1.  压测一个场景，注意控制一下样本数，太多则点连成了线，太稀疏也不适合。
2.  压测结束后下载报告查看。

**期待的正确结果**
希望连线没有遗漏

**截图**
![image](https://user-images.githubusercontent.com/42863606/118110354-e472b380-b414-11eb-97b8-6e0519d68dcf.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现该问题，计划下个版本修复~

**Comment by xulinde** [comment]
1.9.3已修复
