### ISSUE TITLE
[FEATURE]建议 接口自动化的前置/后置写入的sql可以看到执行的sql和运行的结果

### ISSUE THREAD

**Issue by DoraemonYzx** [metersphere/metersphere#27954]
### MeterSphere 版本

 v2.7.0-34d44a5e

### 请描述您的需求或者改进建议

接口自动化的前置/后置写入的sql 没办法查看到运行的sql以及结果,有参数传递的时候可读性不高,不利于调试,

### 请描述你建议的实现方案

希望能加上运行的sql和返回的结果

**Comment by luty2018** [comment]
v3已经规划了哈
