### ISSUE TITLE
[BUG]性能测试页面没办法更新jmx文件

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27962]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

做性能测试时，上传jmx文件，后来在本地做jmx文件的修改后，性能测试模块没办法更新该测试的jmx文件，加载jmx页面也没办法查询当前的jmx文件名，需要通过项目设置下的文件管理进行上传更新。

### 重现步骤

1、创建性能测试，上传jmx文件后保存
2、修改本地jmx文件，编辑原性能测试页面，点击加载jmx文件
3、搜索不到原jmx文件，没办法更新

### 附加信息

<img width="1135" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/27d69880-a718-43ea-8076-0ff758f96f34">

**Comment by liuruibin** [comment]
<img width="1380" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/da564eeb-b072-4b83-bc2f-dae8fdfb17ee">

**Comment by dashenyucainiao** [comment]
但是列表中搜索不到该jmx文件，所以没办法重新上传

**Comment by liuruibin** [comment]
感谢提醒，我们后面会考虑如何实现
