### ISSUE TITLE
[FEATURE]  生成的PDF可能会有些模糊且分页留白不合理

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2796]
**请描述您的需求或者改进建议.**
1、压测后，下载的PDF就像是浏览器网页报告的截图，然后根据浏览器分辨率进行了分割，这样的话有个问题，PDF放大后还是很模糊，看不清，**另外**分页时不同页前后衔接的地方就像是图片直接做了分割，没有留白，这种情况下不适合用来打印报告，要求严格的话，这种报告是有问题的，就要算Bug了。
2、可以通过不同分辨率（屏幕分辨率、浏览器缩放等）打开网页报告，然后再导出报告。
3、建议优化生成PDF的方法。

**请描述你建议的实现方案**
1、希望生成的PDF就像是Word文档另存为PDF的效果，放大后更清晰，分页合理，不会随着分辨率变化，导致每次下载同一份报告的PDF都不一样（比较明显的就是分页位置会不同）。

**Comment by xulinde** [comment]
后面版本优化
