### ISSUE TITLE
[BUG]性能测试采用CSV文件时，高级设置中的CSVDataSet设置保存不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#27961]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.8-lts,v2.10.9-lts

### 使用外置数据库

否

### 问题描述

性能测试时采用CSV文件进行参数化，在高级设置的CSVDataSet点击之后进行保存，页面上的开关按钮自动回弹，实际重新打开改性能测试的时候是修改成功的。

### 重现步骤

https://github.com/metersphere/metersphere/assets/32027713/894b33d9-7a45-44da-8152-167972383d79

**Comment by liuruibin** [comment]
感谢提醒，我们会在后续版本中修复

**Comment by 13290445582** [comment]
v2.10.11已修复，请升级。
