### ISSUE TITLE
[BUG]【功能用例】当项目成员不勾选删除用例权限时，删除模块时，删除按钮存在但是点不动。希望不显示删除按钮或者能置灰按钮。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27965]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【功能用例】当项目成员不勾选删除用例权限时，删除模块时，删除按钮存在但是点不动。希望不显示删除按钮或者能置灰按钮。

### 重现步骤

【功能用例】当项目成员不勾选删除用例权限时，删除模块时，删除按钮存在但是点不动。希望不显示删除按钮或者能置灰。
项目成员权限是 系统管理员或者项目管理员赋予的，用户并不知道他没有删除权限，还以为是系统缺陷。
![image](https://github.com/metersphere/metersphere/assets/104960608/bdb47b0e-9c35-4c87-8bfe-84b68947534e)
![image](https://github.com/metersphere/metersphere/assets/104960608/ed0c1942-38b1-443b-842c-df5de88c58c4)

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本优化下。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
