### ISSUE TITLE
[BUG]使用自定义功能用例模版，新建的用例在修改系统默认字段的值时会有变更记录。但是修改自定义字段的值没有变更记录。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#27960]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

使用自定义功能用例模版，新建的用例在修改系统默认字段的值时会有变更记录。但是修改自定义字段的值没有变更记录。
![1702565098106](https://github.com/metersphere/metersphere/assets/83771182/25a1b689-4a42-4d8b-bc93-2c8482121628)

### 重现步骤

使用自定义功能用例模版，新建的用例在修改系统默认字段的值时会有变更记录。但是修改自定义字段的值没有变更记录。

**Comment by 13290445582** [comment]
感谢反馈，计划下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，经过产品沟通，v2版本自定义字段是没有记录的；已转需求，v3会统一记录的，感谢理解与支持。
