### ISSUE TITLE
[BUG]【接口自动化】环境-通用配置里使用了csv文件，在场景里，当开启下面请求时，获取不到循环里的csv数据。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27974]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口自动化】环境-通用配置里使用了csv文件，在场景里，当开启下面请求时，获取不到循环里的csv数据。

### 重现步骤

【接口自动化】环境-通用配置里使用了csv文件，在场景里，当开启下面请求时，获取不到循环里的csv数据。
![image](https://github.com/metersphere/metersphere/assets/104960608/035cf94b-4f8a-47ef-9b38-2e554d56dbee)
![image](https://github.com/metersphere/metersphere/assets/104960608/677d8429-0412-458e-81c2-a1b450add2bc)
![image](https://github.com/metersphere/metersphere/assets/104960608/4478535e-6d3c-48cf-9911-66520c9a61bf)

当下面请求关闭时，可以引用到
![image](https://github.com/metersphere/metersphere/assets/104960608/14a6bb60-e4b0-4e5e-892a-9c7c184bfe78)

csv文件和场景如下
[场景.zip](https://github.com/metersphere/metersphere/files/13682320/default.zip)

**Comment by 13290445582** [comment]
您好，未发现代码上的异常，将您提供的csv文件重新打开保存了下，上传到环境配置处，调试时控制台正常打印，暂未发现其他异常情况，用其他csv文件进行测试未出现该情况，可能是该csv文件的某些问题，请按照上述方法重试，感谢理解与支持。
