### ISSUE TITLE
[BUG]  资源池的jmeter镜像，值未去两边空格，导致镜像存在，但执行异常

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#27977]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

资源池的jmeter镜像，值未去两边空格，导致镜像存在，但执行异常

### 重现步骤

这里镜像多加了空格
![image](https://github.com/metersphere/metersphere/assets/103925124/d47b970f-dc89-4aa2-9d14-56390ad26ab3)

执行报错
![image](https://github.com/metersphere/metersphere/assets/103925124/b8cd2948-0ef3-4023-bc14-49cc85b03ad6)

**Comment by liuruibin** [comment]
感谢提醒，我们会在后面的版本中优化这里

**Comment by 13290445582** [comment]
您好，v2.10.12已优化，请升级测试。
