### ISSUE TITLE
[FEATURE]    使用优化：UI测试逻辑控制按钮的点击 开启 关闭操作范围比较小不顺手，希望操作范围能扩大一点，优化一下

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#27971]
### MeterSphere 版本

2.10.7

### 请描述您的需求或者改进建议

  使用优化：UI测试逻辑控制按钮的点击 开启 关闭  小三角操作按钮太小 不顺手，希望操作范围能扩大一点，优化一下

![image](https://github.com/metersphere/metersphere/assets/43202800/ced82691-1222-4e30-9a43-64e52e7b2723)

### 请描述你建议的实现方案

 比如：单击逻辑控制器整个 组件块展开，再单击 关闭，

**Comment by Hyyfit** [comment]
感谢反馈，v3已规划
