### ISSUE TITLE
[BUG]【接口自动化】【接口自动化】场景开启两个请求，点击调试 只运行了第一个。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27973]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景开启两个请求，点击调试，只运行了第一个。

### 重现步骤

【接口自动化】场景开启两个请求，点击调试 只运行了第一个。
![image](https://github.com/metersphere/metersphere/assets/104960608/a047bf15-c296-4df2-94fe-b3066c87a9bd)
 而将次数循环关闭，下面请求才能正常运行。
![1702623586226](https://github.com/metersphere/metersphere/assets/104960608/2780ed42-aea0-4784-a9fc-c6425358d905)

脚本如下
[Metersphere_Scenario.zip](https://github.com/metersphere/metersphere/files/13682091/Metersphere_Scenario.zip)

**Comment by 13290445582** [comment]
您好，场景中未勾选失败继续，故请求失败后不再执行。
