### ISSUE TITLE
[FEATURE] 增加自定义内置函数配置

### ISSUE THREAD

**Issue by EasilyTest** [metersphere/metersphere#2797]
**请描述您的需求或者改进建议.**

现在的前后置脚本过于繁琐，调试的过程中要反复复制粘贴复用性极低

**请描述你建议的实现方案**
增加自定义内置函数配置，或者提供自定义函数修改教程

**Comment by xulinde** [comment]
已在调研中

**Comment by EasilyTest** [comment]
> 已在调研中

现在手动修改的方式为，重新编译jmeter函数包并替换，希望能有更便捷的方式
