### ISSUE TITLE
[BUG]【接口自动化】当前置脚本里代码被注释掉进行保存，之后导出后再导入，发现注释的内容恢复了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27976]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】当前置脚本里代码被注释掉进行保存，之后导出后再导入，发现注释的内容恢复了。

### 重现步骤

【接口自动化】当前置脚本里代码被注释掉进行保存，之后导出后再导入，发现注释的内容恢复了。
![image](https://github.com/metersphere/metersphere/assets/104960608/86a6dc92-107e-4acc-a57c-06e73707c2b2)
![image](https://github.com/metersphere/metersphere/assets/104960608/166d4356-0c3a-47ed-9909-9ebbc493a79d)

脚本如下
[Metersphere_Scenario000.zip](https://github.com/metersphere/metersphere/files/13682419/Metersphere_Scenario000.zip)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。
