### ISSUE TITLE
[BUG]【接口定义】swagger导入rest风格接口，接口参数并没有显示到REST参数处

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27986]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口定义】swagger导入rest风格接口，接口参数并没有显示到REST参数处

### 重现步骤

【接口定义】swagger导入rest风格接口，接口参数并没有显示到REST参数处
![image](https://github.com/metersphere/metersphere/assets/104960608/b0442cd2-e3e7-4962-90db-5f10a59f867b)

接口如下:
[TEST.zip](https://github.com/metersphere/metersphere/files/13698962/TEST.zip)

**Comment by 13290445582** [comment]
你好，计划下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级验证。

**Comment by 2lipan** [comment]
升级到v2.10.11-lts版本验证rest参数正常显示。
