### ISSUE TITLE
[BUG] 【性能测试】同一个虚拟机上，直接用jmeter 在虚拟机上跑，和当作 ms压力机跑，5个并发，跑10min,样本和吞吐量差9倍

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2798]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9。2
**Bug 描述**
简要描述您碰到的问题
同一个虚拟机上，直接用jmeter 在虚拟机上跑，和当作 ms压力机跑，5个并发，跑10min,样本和吞吐量差8-10 倍
**Bug 重现步骤**
1.  找一台虚拟机做压力节点，在ms上创建性能测试任务，设置5个并发，10min ，压测，下载jtl，用jmeter聚合报告查看结果
![image](https://user-images.githubusercontent.com/30038088/118117252-f1e06b80-b41d-11eb-8411-104d6c0824a4.png)

2. 任务执行中间，将jmx 从压力节点容器内部 下载下来，等上边任务执行完后，用jmter 直接在虚拟机上跑压测，生成jtl，用jmeter 打开。
![image](https://user-images.githubusercontent.com/30038088/118117253-f1e06b80-b41d-11eb-983c-75061e0cb9d1.png)
3. 对比结果差9倍
4. 脚本为 

**期待的正确结果**
正确情况下应该是什么样的？
结果相差 不应该 这么大
**截图**
如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
[1.jmx.zip](https://github.com/metersphere/metersphere/files/6472053/1.jmx.zip)

**Comment by zhangzhaox** [comment]
你这脚本的响应时间 接近于0？？
