### ISSUE TITLE
[BUG]【接口自动化】场景里嵌套场景，场景1提取的变量 在场景2的请求里引用，获取的结果和直接case里写死的值获取的响应内容不一样。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#27982]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景里嵌套场景，场景1提取的变量 在场景2的请求里引用，获取的结果和直接case里写死的值获取的响应内容不一样。

### 重现步骤

【接口自动化】场景里嵌套场景，场景1提取的变量 在场景2的请求里引用，获取的结果里，orders字段返回是空值
![44d656aeebac0ec0ddc08e6eedd7840](https://github.com/metersphere/metersphere/assets/104960608/9cd40cea-e6c9-4998-849d-d63e6e76f8b7)
![2e33625a188195ee8a039c954118ccf](https://github.com/metersphere/metersphere/assets/104960608/709d37fa-2acc-4ba3-8779-e144162d7e14)
![9834c4e393580f54cc85a77e89c5750](https://github.com/metersphere/metersphere/assets/104960608/b893aee6-0a76-4ab0-a509-7b05dc73f046)

拿着这获取的变量，直接在接口定义的case里执行，orders字段返回是有值。
![0164de989d845284f513ba7a2ed5652](https://github.com/metersphere/metersphere/assets/104960608/9c875faa-dff2-4b26-ad70-cdd459b1261f)
![05dac914e890d980c6b8811b7cacf18](https://github.com/metersphere/metersphere/assets/104960608/e7695f22-9fdf-45d4-91cc-cecd0a20647f)

**Comment by 13290445582** [comment]
您好，已转开发跟进，后续反馈会及时更新。

**Comment by 2lipan** [comment]
可能与客户被测系统 数据入库时间有关系，在该请求的前置添加等待时间1分钟，可以正常执行
