### ISSUE TITLE
[BUG]用例评审-评审人设置多个，评审通过标准为全部通过时，批量编辑通过，单人评审通过就通过了

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#27980]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

用例评审-评审人设置多个，评审通过标准为全部通过时，批量编辑通过，单人评审通过就通过了

### 重现步骤

1. 用例评审-评审人设置多个，评审通过标准为全部通过
![image](https://github.com/metersphere/metersphere/assets/103627487/4bbd6074-28d2-469a-80ed-92c541a610f8)
2. 批量编辑执行结果为通过
![image](https://github.com/metersphere/metersphere/assets/103627487/bc9b277f-f6d0-416a-83f8-55e9d11441b3)
3.查看评审结果，单人评审通过就通过了，
![image](https://github.com/metersphere/metersphere/assets/103627487/affdb07e-7749-49b6-ad8b-c0e1bf88a78d)

**Comment by 13290445582** [comment]
您好，设计如此，批量通过为强制通过，不需要其他评审人继续评审，感谢理解。
