### ISSUE TITLE
[BUG]部分环境配置无法添加域名

### ISSUE THREAD

**Issue by liaolongfei** [metersphere/metersphere#27989]
### 联系方式

交流群:Metersphere交流群4 昵称:琥珀  邮箱:longfei_liao@163.com 

### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

是

### 问题描述

部分环境配置无法添加域名。
chrome 版本 120.0.6099.72（正式版本） （64 位）
同一浏览器，同一账号，部分环境配置无法添加域名呢，有些又可以
![945c0c2da6d9e5c6d844110384ddd37](https://github.com/metersphere/metersphere/assets/6407371/aae1e2cd-74fa-4c42-ab77-41929f60d457)

### 重现步骤

只能在特定环境配置才可以重现。
已经由飞致云的同时远程协助查看，但无法明确原因。

### 期待的正确结果

能添加域名

**Comment by 13290445582** [comment]
您好，Chrome浏览器升级到最新版本会有此问题吗？您提到的特定环境配置才可复现，指的是什么样的环境配置可复现，请提供下，感谢。

**Comment by liaolongfei** [comment]
升级到最新版本也有问题。和浏览器版本无关，我在火狐浏览器也会有这样的问题。
而且是同一浏览器，不同的环境配置，会有个别环境配置无法编辑。
我无法在别的环境复现。我已经找了metersphere的员工进行远程查看过了，因为她无法查到原因，所以需要我在这边提issue。

**Comment by 13290445582** [comment]
您好，未在我们本地环境复现您的这种情况。
您提到的个别环境配置无法编辑，具体是什么样的环境才无法添加域名，可以截屏或者录屏看下吗？
无法编辑域名的环境，它目前使用的域名是什么样的，截屏看下。

**Comment by liaolongfei** [comment]
录屏如下，一共操作了2个环境。第一个环境是可编辑的，第二个环境是不可编辑的。
https://github.com/metersphere/metersphere/assets/6407371/eb0ec4c5-d734-42f2-8f75-e1f1ebafa21b

**Comment by 13290445582** [comment]
您好，通过录屏可看到，您的项目环境未显示您的Mock环境，是不是做过删除等操作，不清楚是否产生过异常操作，导致这个项目环境无法编辑，正常来说，只有Mock环境是无法编辑的。目前本地未复现您这种情况，您也可留意后续是否还有其他环境可操作出该情况，及时反馈，感谢您的理解与支持。

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，暂时关闭该issue，感谢理解与支持。
