### ISSUE TITLE
[FEATURE]测试用例评审通过方式增加

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#27995]
### MeterSphere 版本

2.9.1

### 请描述您的需求或者改进建议

现阶段的用例评审只有单人通过和全部通过，但是由于我们评审人员可能会比较机动，评审预计指定了5个人，最后可能不是5个人当时都有时间去评，所以希望可以设定几人通过。最终结果就是一共指定5个人，我设定3人通过，那么只要有3个人评了通过就可以算通过，那么后面人如果评了不通过 那么还是一票否决，变成不通过

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/40912823/4d533721-3a57-45c5-9c5a-f9294e5b5bb3)

**Comment by Hyyfit** [comment]
暂时没有这个功能的规划；
