### ISSUE TITLE
[FEATURE]用例名称显示不全，建议优化测试用例界面显示

### ISSUE THREAD

**Issue by shorile** [metersphere/metersphere#28]
**请描述您的需求或者改进建议.**

测试用例列表界面字段平均分布，用例名称显示不全，请优化界面显示

**请描述你建议的实现方案**

建议增加用例名称宽度，缩小优先级等其它字段宽度

**Comment by luty2018** [comment]
1.1.1版本上，请留意交流群版本更新通知
