### ISSUE TITLE
[BUG]测试计划定时执行时 ，关联的 CASE 使用 k8s 资源池，不定期 出现 running 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#28012]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/30038088/ae88ec5f-cb39-4619-9216-93d24a0c0035)

![image](https://github.com/metersphere/metersphere/assets/30038088/ff364a58-7f1a-463f-9443-ddf080be852e)

### 重现步骤

1.报错的时间节点，MS 服务、k8s node 监控信息都正常。
2.api-test info ms-jmeter 日志在改时刻无异常信息。

**Comment by 13290445582** [comment]
您好，本地暂时未复现该问题，后续会留意类似偶现问题，感谢理解。

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，暂时关闭该issue，感谢理解与支持。
