### ISSUE TITLE
[BUG] 通过CSV文件引用变量在多节点压测时可能会出现异常

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2801]
**MeterSphere 版本**
v1.9.2-98b64776

**Bug 描述**
1、使用csv文件引用变量，假设每一行为一组变量，则每组变量不能重复使用，重复使用会出现异常，在多节点下，每个节点都会拿到同一份文件，导致每组变量都会被重复引用，所以压测报告就会出现1/2、2/3或3/4等类似比例的异常率。
2、有的场景会出现异常，有的场景会出现响应时间延长的问题（等待锁释放）。
3、有几个思路或许可以参考：①可以把csv进行拆分；②由一个单独的组件把数据抽取后分发给不同的节点；③允许单独给每个节点上传CSV文件（这个方法对用户更容易控制每个节点的文件，但也会增加用户的操作成本）。

**Bug 重现步骤**
1.  设计一个请求，每组数据不能重复使用，当第2次乃至后续收到相同的数据时，返回异常，可以返回特定的状态码方便判断。
2.  通过CSV引用变量传给步骤1中的请求。
3.  使用多节点压测，且压测时间不能太短，太短可能不明显。
4.  查看压测报告，会发现这些异常。

**期待的正确结果**
多节点压测时不会出现这种因为传递了相同的数据而导致的异常。

**截图**
![image](https://user-images.githubusercontent.com/42863606/118120028-d8412300-b421-11eb-83ea-11cfff13dbd0.png)

**Comment by zyyfit** [comment]
您好，CSV引用这个问题因为考虑到其他使用场景，暂时没有太好的解决方法，后续版本会优化这个问题的
