### ISSUE TITLE
[BUG]缺陷管理，高级搜索数据不全

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#28024]
### 联系方式

jiguang.chen@fit2cloud.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

缺陷管理对接了jira，jira上的报告人，在高级搜索里，查看不到。

### 重现步骤

1.对接jira，报告人300个左右。
2.创建缺陷，报告人可以搜索到指定的人，如下图：
![image](https://github.com/metersphere/metersphere/assets/66937739/bc6f7775-2073-4fae-8f99-cfbd8fd19154)
3.g高级搜索时，搜索上图的人，搜索不到，如下图：
![image](https://github.com/metersphere/metersphere/assets/66937739/d3688b65-9608-4635-805a-b0bfa3b849fb)

### 期待的正确结果

可以与创建时，搜索到所有报告人

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复。

**Comment by 13290445582** [comment]
问题未复现，建议升级最新版本且使用可兼容的jira版本。
