### ISSUE TITLE
[BUG] CSV文件的引用不能选择是否循环使用以及不能选择文本识别符号

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#2802]
**MeterSphere 版本**
v1.9.2-98b64776

**Bug 描述**
1、不能控制数据文件是否可以循环使用，很多场景需要控制，这个是必需功能；
2、不能选择文本识别符号（特殊数据文件里，双引号、单引号、分隔符都有可能是值的一部分，这种场景还是比较常见的），这个是必需功能；

**Bug 重现步骤**
1.  打开“接口自动化-创建场景-场景变量-自定义变量-添加CSV”，即可看见无此选项。

**期待的正确结果**
1、增加是否循环使用的选项；
2、增加选择文本识别符号的选项（CSV本身可以使用双引号和单引号，或不使用引号，这个参考第3个图，Excel导入CSV文件源时就有此选项）；
这两个功能是Jmeter提供的标准功能，希望效果和Jmeter的相同。

**截图**
1、MeterSphere的配置
![image](https://user-images.githubusercontent.com/42863606/118121795-906fcb00-b424-11eb-98db-2d79f26c0474.png)
2、Jmeter里的CSV数据文件设置
![image](https://user-images.githubusercontent.com/42863606/118122187-12f88a80-b425-11eb-90cd-dd21e4f74222.png)
3、Excel导入CSV时需要文本识别符号才能判断哪些属于同一个值
![image](https://user-images.githubusercontent.com/42863606/118122452-74b8f480-b425-11eb-8b9d-ae7d09b6ddac.png)

**Comment by zyyfit** [comment]
您好，后续版本会考虑增加这些功能的
