### ISSUE TITLE
[BUG] 断言规则的脚步未保存

### ISSUE THREAD

**Issue by xiongxiaoqing614** [metersphere/metersphere#2803]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
断言脚步未保存
**Bug 重现步骤**
1.  添加单接口用例的断言规则
2. 并添加脚本断言规则
3. 点击保存
4. 执行该用例
5. 重复1-4步骤 
6. 执行结果未使用最新编辑的内容
7. 打开脚步编辑框，显示内容与执行内容不一致
**期待的正确结果**
正确情况下应该是什么样的？
脚步保存成功，每次执行是新修改的内容
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72964047/118125206-4210fb00-b429-11eb-830c-e0b1f91213b5.png)
![image](https://user-images.githubusercontent.com/72964047/118125254-51904400-b429-11eb-9e3f-343a92b5eb09.png)

**Comment by zyyfit** [comment]
您好，1.9.2版本未复现这个问题，请升级一下试试
