### ISSUE TITLE
[BUG]接口定义编写接口请求体时，在JSON-schema模式下是integer类型，关闭该模式，再打开JSON-schema模式，参数类型从integer变为了number。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#28036]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

接口定义编写接口请求体时，在JSON-schema模式下是integer类型，关闭该模式，再打开JSON-schema模式，参数类型从integer变为了number。
![image](https://github.com/metersphere/metersphere/assets/83771182/407a684b-b98c-4eba-aef6-65db4f039a6c)

### 重现步骤

接口定义编写接口请求体时，在JSON-schema模式下是integer类型，关闭该模式，再打开JSON-schema模式，参数类型从integer变为了number。

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题不好处理，v2版本暂不处理该问题，不影响主流程使用。比如一个整数 既可以选择类型是 Integer 也可以是 Number；从JSON出来的数据没法区分，但是标记成Number 也是没错的，Number 类型包含整数和小数。感谢您的理解与支持。
