### ISSUE TITLE
[BUG]测试跟踪中导出测试报告失败

### ISSUE THREAD

**Issue by chenjiev1** [metersphere/metersphere#28030]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

测试跟踪-测试计划，导出测试计划失败， 提示network error

### 重现步骤

1.在测试跟踪-测试计划中创建一个测试计划，测试计划的接口测试用例中关联42个场景
2.执行多次测试，在报告中选中一个报告记录，点击按钮栏中的“查看测试报告”，点击导出，导出失败，提示network error

### 期待的正确结果

正常导出测试报告

### 附加信息

![Unknown-1](https://github.com/metersphere/metersphere/assets/14901546/75045b98-abc5-4f7d-8582-d97f0713ce37)
![WechatIMG2214](https://github.com/metersphere/metersphere/assets/14901546/e9881fe6-a69e-43b0-ade8-539240b3ccd3)

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，最新环境测试之前可复现的数据已导出成功，可升级至最新版本使用，看问题是否解决，后续有问题再反馈。
