### ISSUE TITLE
[BUG] 测试计划关联的功能用例编辑之后，功能用例关联的测试没有出现在测试计划的接口接测试用例中

### ISSUE THREAD

**Issue by sss903065212** [metersphere/metersphere#28048]
### MeterSphere 版本

v2.10.9-lts 

### 使用外置数据库

否

### 问题描述

第一种问题：
1、测试计划关联 取消过关联的功能用例编辑之后，功能用例关联的接口测试用例没有出现在测试计划的接口接测试用例中
2、测试计划关联功能用例A
3、测试计划取消关联功能用例A
4、功能用例A关联接口测试用例B、C
5、测试计划关联功能用例A
6、测试计划未展示关联的接口测试用例B、C

第二种问题：
1、测试计划关联的功能用例编辑之后，功能用例新关联的接口测试用例没有出现在测试计划的接口接测试用例中
2、测试计划关联功能用例A
3、功能用例A关联接口测试用例B、C
4、测试计划未展示关联的接口测试用例B、C

### 重现步骤

按照问题描述重现即可

### 期待的正确结果

功能用例关联的测试能正确的展示在测试计划关联的接口测试用例列表中

**Comment by youliyuan-fit2cloud** [comment]
问题一和二是同一个问题，测试计划关联功能用例之后，功能用例里面再关联接口用例，测试计划不会再次同步。暂时不支持。
