### ISSUE TITLE
接口定义那里不能统一制定环境

### ISSUE THREAD

**Issue by lovelivestyle1102** [metersphere/metersphere#2804]
**接口定义那里不能统一制定环境**

**可以基于项目统一设置环境，单接口也可以自定义环境。自定义的优先级高于统一设置的**

**Comment by xulinde** [comment]
项目-环境配置，可以设置匹配条件，模块/路径 分别根据这两个条件去匹配，无就是没有条件，向当局全局
![image](https://user-images.githubusercontent.com/64065190/118252918-e3588980-b4db-11eb-9f55-92e86dac6f39.png)
