### ISSUE TITLE
[BUG] 在脑图模式下评审用例，添加的详细信息没有记录到评审记录中

### ISSUE THREAD

**Issue by lvluostudio** [metersphere/metersphere#28040]
### 联系方式

wingle@qq.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

如下图，脑图模式下添加的信息，保存成功，但是在评审记录中只看到有评论，评论的详情没有了。
![image](https://github.com/metersphere/metersphere/assets/8476051/8eecf97e-4e6a-4c47-93aa-af9230a24f46)

![image](https://github.com/metersphere/metersphere/assets/8476051/659f4b7d-0998-40b6-8410-8578870a26e2)

### 重现步骤

1. 进入评审计划的脑图模式
2. 给用例插入下级主题，添加“无测试步骤”
3. 保存，提示保存成功
4. 进入列表模式
5. 编辑刚才的用例
6. 查看评审记录
7. 发现有新增一条评审记录，但是内容没有刚才写的信息“无测试步骤”

### 期待的正确结果

评审记录中能看到写的详情，如：“无测试步骤”

**Comment by 13290445582** [comment]
您好，v2.10.10已修复，请升级尝试。脑图目前不支持添加评论，解决方案为：列表模式查看不会产生您描述的那条空白评论。
