### ISSUE TITLE
[BUG]<html> <head><title>456 Request Denied</title></head> <body> <center><h1>456 Request Denied</h1></center> <center>The request has been blocked</center> <hr><center>nginx</center> </body> </html>

### ISSUE THREAD

**Issue by Febulous** [metersphere/metersphere#28054]
### 联系方式

1074642101@qq.com

### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

提交用例保存或者保存一些脚本时

### 重现步骤

执行失败时保存会复现

**Comment by youliyuan-fit2cloud** [comment]
你好， 请把出现该问题步骤再描述详细一些，方便我们复现问题。包括操作截图，前端控制台报什么错误，后端错误日志等信息。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，关闭该问题，如果有补充请重新打开。感谢理解和支持。
