### ISSUE TITLE
[BUG]接口定义请求体X-www-form-urlencoded格式，响应结果中的请求内容错误

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#28052]
### 联系方式

张树彬

### MeterSphere 版本

2.10.9LTS

### 使用外置数据库

否

### 问题描述

接口定义中，请求体从raw格式切换到X-www-form-urlencoded格式后在页面显示正常，但执行接口后响应结果中的请求内容处显示错误

### 重现步骤

1. 创建接口，请求体填写在raw格式中
2. 切换请求体格式到X-www-form-urlencode
3. 执行接口
4. 查看响应内容中请求内容，未正确显示请求体内容

### 期待的正确结果

1. 可以在X-www-form-urlencode格式下，正确显示解析请求体内容

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/77324661/d49ab0e3-0f50-46c6-a569-e898fb48c11c)
![image](https://github.com/metersphere/metersphere/assets/77324661/9c2bcff2-f26b-4545-bbef-c133f4c432d7)

**Comment by 13290445582** [comment]
您好，请检查下名称处是否有空格？
<img width="980" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/98263135-6cb4-4673-afc9-011502ef26db">

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
