### ISSUE TITLE
[FEATURE]接口参数依赖其他接口的响应参数，只能通过场景步骤控制。希望前置条件增加一个依赖用例的选项

### ISSUE THREAD

**Issue by changxianle** [metersphere/metersphere#28051]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 请描述您的需求或者改进建议

接口参数依赖其他接口的响应参数，只能通过场景步骤控制。希望前置条件增加一个依赖用例的选项，先执行前置条件中依赖的接口用例，再执行当前用例。

**Comment by wengxiaqin** [comment]
> ### MeterSphere 版本
> v2.10.9-lts-1268b1f8
> 
> ### 联系方式
> _No response_
> 
> ### 请描述您的需求或者改进建议
> 接口参数依赖其他接口的响应参数，只能通过场景步骤控制。希望前置条件增加一个依赖用例的选项，先执行前置条件中依赖的接口用例，再执行当前用例。
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

**Comment by luty2018** [comment]
暂时没有这个规划哦。
