### ISSUE TITLE
[BUG]k8s 的 pod 中应用 有时会后出现 假死状态，建议在 helm-chart 的 应用的模板中添加类似livenessProbe探活机制，监控到假死不应答后，能够及时重启

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#28061]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

在跑接口测试或者UI测试时，node-controller 或者 selenium 有时间会出现 api-test 发送命令失败或者 selenium 4444 端口假死不应答的现象，建议在每个 deployment 的 yaml 上添加 livenessProbe探活机制 ，检查 应用进程的健康状况，发现假死后直接重启 pod。

### 重现步骤

k8s 的 pod 中应用 有时间后出现 假死状态，建议在 helm-chart 的 应用的模板中添加类似livenessProbe探活机制，能够重启

**Comment by fit2-zhao** [comment]
感谢建议，用户可以自行调整yaml配置。
