### ISSUE TITLE
[FEATURE]接口自动化循环控制器

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#2808]
**请描述您的需求或者改进建议.**
接口自动化循环控制器中的循环次数可以填入参数，根据参数来进行循环次数

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by zyyfit** [comment]
您好，使用foreach循环或者while循环是否能满足您的需求呢？

**Comment by wszbc** [comment]
> 您好，使用foreach循环或者while循环是否能满足您的需求呢？

硬要用while的话加点代码也能实现循环一次参数减一，不过就是操作起来会比较复杂，次数循环能识别参数是最方便的

**Comment by xulinde** [comment]
v1.13已支持
