### ISSUE TITLE
[BUG]【接口自动化】自定义请求的请求地址里含有变量时，点击引用环境，出现"url无效"的提示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28092]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】自定义请求的请求地址里含有变量时，点击引用环境，出现"url无效"的提示。

### 重现步骤

【接口自动化】自定义请求的请求地址里含有变量时，点击引用环境，出现"url无效"的提示。
![image](https://github.com/metersphere/metersphere/assets/104960608/4880ecb8-c961-4b8f-8d76-7fea09624291)
![image](https://github.com/metersphere/metersphere/assets/104960608/30eec428-46aa-4b79-a356-a109000d4859)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个情况需要手动修改下了，当选中“引用环境”时我们解析不出来这个路径是什么，所以提示url无效，感谢理解和支持～
