### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#28090]
### MeterSphere 版本

v2.10.9-lts

### 联系方式

357861578@qq.com

### 请描述您的需求或者改进建议

修改用例或测试场景中修改前后置元件、或请求名称时，只能通过键盘一个个字符往前移，不能通过鼠标快速移动到需要修改的位置上。建议可以通过鼠标快速移位或选择要修改的字符，方便操作。

### 请描述你建议的实现方案

修改用例或测试场景中修改前后置元件、或请求名称时，只能通过键盘一个个字符往前移，不能通过鼠标快速移动到需要修改的位置上。建议可以通过鼠标快速移位或选择要修改的字符，方便操作。

### 附加信息

![图片](https://github.com/metersphere/metersphere/assets/130725706/69e71594-2d43-4805-9fbf-1221c45fd9a9)

**Comment by luty2018** [comment]
感谢建议， 我们优化一下
