### ISSUE TITLE
[BUG]接口测试中请求http 接口，和用postman请求返回的响应数据不同

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28106]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口测试中请求http 接口，和用postman请求返回的响应数据不同

### 重现步骤

1. 接口测试创建接口，并请求成功，查看响应数据，发现返回的code 不对
2. 用postman 请求同一个接口，请求成功，查看响应数据，返回的code正确
3. 用postman 请求成功的数据，导出再导入MeterSphere 中请求，发现的返回的code 还是不对

### 期待的正确结果

接口测试中请求http 接口，和用postman请求返回的响应数据相同

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/4c4fe2f0-f34e-42dd-b9fa-4be3e809fd3a)
<img width="824" alt="1703490043447" src="https://github.com/metersphere/metersphere/assets/50016789/56723c10-3f09-4dbe-9d12-d4ccf85441f3">

**Comment by liqiang-fit2cloud** [comment]
有没有从被测系统服务端看看为什么会给客户端返回不同的结果，收到的请求有什么不同？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
