### ISSUE TITLE
[FEATURE]性能测试的执行报告中能否添加发压端的执行日志

### ISSUE THREAD

**Issue by haipeng-fit2** [metersphere/metersphere#28117]
### MeterSphere 版本

v2.10.9-lts

### 请描述您的需求或者改进建议

目前性能测试的执行报告中有被压测的信息以及发压端的Prometheus监控，但发压端容器的信息还需要到宿主机上输入命令看日志，能否可以将发压容器的日志信息也一起集成到性能报告中。

### 请描述你建议的实现方案

在性能报告中增加一页，将ms-jmeter-run等日志在前端展示出来。

**Comment by liuruibin** [comment]
目前性能测试中的日志仅收集了jmeter.log 其他的暂时不支持前台直接获取

**Comment by haipeng-fit2** [comment]
好的，明白啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘瑞斌 ***@***.***&gt;
发送时间: 2023年12月26日 10:58
收件人: metersphere/metersphere ***@***.***&gt;
抄送: haipeng-fit2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [FEATURE]性能测试的执行报告中能否添加发压端的执行日志 (Issue #28117)





 
目前性能测试中的日志仅收集了jmeter.log 其他的暂时不支持前台直接获取
