### ISSUE TITLE
[BUG]【测试跟踪】1. 测试计划-执行用例，使用思维导图方式，取消「通过」状态，保存，还是「通过」状态（预期：未执行）；2. 每次都需要点击保存，才会生效，建议点击「通过」后，自动保存（有时会忘记点保存，切换页面后全部状态被清空）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2811]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题
1. 测试计划-执行用例，使用思维导图方式，取消「通过」状态，保存，还是「通过」状态（预期：未执行）；
2. 每次都需要点击保存，才会生效，建议点击「通过」后，自动保存（有时会忘记点保存，切换页面后全部状态被清空）

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
1. 取消「通过」状态，保存，状态：未执行
2. 标记用例后，自动保存

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/118216816-ca81b100-b4a6-11eb-86c1-f0691e57a980.png)

**Comment by zyyfit** [comment]
您好，测试用例执行通过后目前不支持再改为未执行状态，第二个问题后续会考虑优化
