### ISSUE TITLE
[BUG]【接口测试】开启接口定义url可重复，将带case的api导出，再导入到其他目录，原api下的case都不见了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28129]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

【接口测试】开启接口定义url可重复，将带case的api导出，再导入到其他目录，原api下的case都不见了。

### 重现步骤

【接口测试】开启接口定义url可重复，将带case的api导出，再导入到其他目录，原api下的case都不见了。
![image](https://github.com/metersphere/metersphere/assets/104960608/775cd38b-9e3d-41e9-9591-1d9770fb9f53)
![image](https://github.com/metersphere/metersphere/assets/104960608/8a754f91-e67f-4059-994a-accdc42e0005)

**Comment by zrfit** [comment]
您好，感谢反馈！计划v2.10.11-lts修复。
