### ISSUE TITLE
[BUG]【测试跟踪】测试用例筛选后，再次查看，勾选状态会被清空

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2812]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
保持勾选状态

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118217053-4976e980-b4a7-11eb-83e0-582d10359918.png)

**Comment by zyyfit** [comment]
您好，这个问题已修复，请升级到最新版使用
