### ISSUE TITLE
[导入覆盖样例，覆盖了注释]

### ISSUE THREAD

**Issue by ky994226161** [metersphere/metersphere#28130]
### 联系方式

994226116@qq.com

### MeterSphere 版本

v2.10.8

### 使用外置数据库

否

### 问题描述

swagger导入的API规范是有注释的,但是在调试API时,为了了填写参数样例方便快捷,直接
使用ms插件录制json或HAR包等导入,导入后样例参数是导入了,但是覆盖了API原本的注释

### 重现步骤

swagger导入的API规范是有注释的,但是在调试API时,为了了填写参数样例方便快捷,直接
使用ms插件录制json或HAR包等导入,导入后样例参数是导入了,但是覆盖了API原本的注释

### 期待的正确结果

导入入参样例时,只更新参数,不覆盖原始的API注释

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/38663557/7f8cf23c-cace-4858-8afa-06e886dd1832)

**Comment by zrfit** [comment]
您好，感谢反馈！v3进行优化，感谢理解和支持。
