### ISSUE TITLE
[BUG]有while循环组件的接口自动化场景，转化为性能测试后会有多余Label，影响测试结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#28132]
### 联系方式

zhaojun@fit2cloud.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口自动化场景中，有while循环控制器时，将该自动化场景转化为性能测试后，请求统计会出现MS_LOOP。。。之类的Label，会影响最终报告结果

### 重现步骤

1、创建接口自动化，添加while循环控制器
2、将该自动化场景转化为性能测试
3、查看性能测试的请求统计

### 附加信息

原场景：
<img width="1327" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/69ee497a-99e5-4cfb-9c82-f9062d5f4143">

性能测试报告：
<img width="1320" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/153a4cfe-2c37-47ab-8c03-33112d915774">

**Comment by 13290445582** [comment]
您好，在Jmeter中测试，While控制器就有该请求，非缺陷。
<img width="519" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/072107a9-2496-49d1-91a8-3c9ea4634651">
