### ISSUE TITLE
[FEATURE] include lombok as a 'provided' dependency

### ISSUE THREAD

**Issue by xinkeng0** [metersphere/metersphere#28135]
### MeterSphere 版本

v2.10

### 请描述您的需求或者改进建议

https://github.com/metersphere/metersphere/blob/08347de201ebe7dd5456ace4a8e4e05df5246ffc/pom.xml#L115-L119

- https://projectlombok.org/setup/maven
> To set up lombok with any build tool, you have to specify that the lombok dependency is required to compile your source code, but does not need to be present when running/testing/jarring/otherwise deploying your code. Generally this is called a 'provided' dependency. This page explains how to integrate lombok with the [Apache Maven](https://maven.apache.org/) build tool.

### 请描述你建议的实现方案

```xml
<dependencies>
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<version>${lombok.version}</version>
		<scope>provided</scope>
	</dependency>
</dependencies>
```

**Comment by liuruibin** [comment]
Thanks for the reminder, we exclude this jar when building. You will not find this jar in the finished docker image

<img width="832" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/050cc02f-c47b-49f8-868a-0b2738442032">

**Comment by xinkeng0** [comment]
嗯，当然这无关与一个功能型问题。
我想描述的是optional的语义就像是我提供了一些可选的功能，如果你需要的话你可以引入相应的包开启。
而scope provided在这里从语义上来说更适合一些，lomkbok不应该存在于运行时，它只在运行期工作。
