### ISSUE TITLE
ms-network和metersphere_ms-network对应不上

### ISSUE THREAD

**Issue by ksice** [metersphere/metersphere#28142]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/26266303/932e1418-457e-4f45-8741-47b94d7dfd60)
docker-compose里面配置的是ms-network ,但是docker network ls显示的时候metersphere_ms-network，这两个网络对应不上啊

**Comment by liuruibin** [comment]
<img width="1999" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/e969d3e2-8b5d-46cf-a14c-bb416ca1b27a">

**Comment by ksice** [comment]
> <img alt="image" width="1999" src="https://private-user-images.githubusercontent.com/23045261/292986618-e969d3e2-8b5d-46cf-a14c-bb416ca1b27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjQ3NjMsIm5iZiI6MTcwMzY2NDQ2MywicGF0aCI6Ii8yMzA0NTI2MS8yOTI5ODY2MTgtZTk2OWQzZTItOGI1ZC00NmNmLWExNGMtYmI0MTZjYTFiMjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA4MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NWQ1NzcyMmY4N2U5MDg1NDJjNzJjOTFlNmM1YzlmMjdlOWQ2ZjJmYTJmYjUxZmQ2OTM1Zjk5ZGQ1YjM1NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5PvcsCI9rvTQhNIGVojQ-GZOhzIr9dFBsrg6Xd4BEQc">

我想请问一下我单独启动这个api-test启动不了的么，谢谢
