### ISSUE TITLE
[BUG]当请求体参数中有转义字符，在参数中使用变量，会存在转义字符丢失的情况

### ISSUE THREAD

**Issue by HUMINGO** [metersphere/metersphere#28140]
### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

当请求体参数中有转义字符，在参数中使用变量，会存在转义字符丢失的情况

### 重现步骤

发送请求前的参数
{
    "appkey": "${appkey}",
    "mode": "CHARGING",
    "notifyUrl": "",
    "requestId": "123123123123",
    "transactionId": "202312221008015548",
    "type": "",
    "paymentMethod": "{\"type\":\"Fingateway\",\"provided\":{\"payType\":\"DIRECT\",\"fingateway\":{\"appkey\":\"TOGG00008\",\"tradeType\":\"1\",\"channel\": \"1\",\"outOrderId\":\"202312221008015548\",\"amount\": 10,\"orderDesc\":\"\",\"notifyurl\":\"\",\"returnUrl\":\"https://www.baidu.com/\",\"cancelurl\":\"\",\"extendJson\":\"{\\\"currencyCode\\\":\\\"usd\\\",\\\"productName\\\":\\\"产品名称\\\", \\\"customerId\\\": \\\"stripe用户id\\\"}\"}}}"
}

参数中使用变量，发送请求，查看响应内容的请求数据体
{
  "appkey": "TOGG00008",
  "mode": "CHARGING",
  "notifyUrl": "",
  "requestId": "123123123123",
  "transactionId": "202312221008015548",
  "type": "",
  "paymentMethod": "{\"type\":\"Fingateway\",\"provided\":{\"payType\":\"DIRECT\",\"fingateway\":{\"appkey\":\"TOGG00008\",\"tradeType\":\"1\",\"channel\": \"1\",\"outOrderId\":\"202312221008015548\",\"amount\": 10,\"orderDesc\":\"\",\"notifyurl\":\"\",\"returnUrl\":\"https://www.baidu.com/\",\"cancelurl\":\"\",\"extendJson\":\"{\\"currencyCode\\":\\"usd\\",\\"productName\\":\\"产品名称\\", \\"customerId\\": \\"stripe用户id\\"}\"}}}"
}

**Comment by 13290445582** [comment]
您好，我们的底层逻辑是基于JMeter实现的，根据您提供的请求体内容在JMeter调试，结果与在MeterSphere调试结果一致，并非是MeterSphere的缺陷，感谢您的理解与支持。
<img width="1347" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/17986f79-3067-40f6-93ce-cdff69999a00">

**Comment by HUMINGO** [comment]
我在jmeter上试过了，确实也存在这个问题。这个问题算是jmeter的bug了吧
