### ISSUE TITLE
新增一个服务

### ISSUE THREAD

**Issue by ksice** [metersphere/metersphere#28145]
### 请描述您的问题

那我可以新增一个服务镜像么，然后嵌进去

**Comment by liuruibin** [comment]
可以的，这就需要你自己研究了。
加入交流群和更多网友一起讨论 https://metersphere.io/

群二维码：
![image](https://github.com/metersphere/metersphere/assets/75963100/94bba816-1647-49c8-83c2-3cd23d5044c0)

**Comment by ksice** [comment]
里面基本没人搭理啊
