### ISSUE TITLE
单独启动这个api-test

### ISSUE THREAD

**Issue by ksice** [metersphere/metersphere#28143]
### 请描述您的问题

如果我想通过命令一个个启动镜像的话，这个有文档介绍么，谢谢

**Comment by liuruibin** [comment]
<img width="1284" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/faf2e610-f152-44e3-a968-f2c48105817e">
部署模式可以安装图中的选项进行配置，不支持独立启动某个镜像，这样可能会导致服务不可用

**Comment by ksice** [comment]
那如果我要新增一个服务可以嵌入进去么
