### ISSUE TITLE
请问V3.x版本是不是还没有开放接口支持插件导出？还有导出idea的插件master才1.0.8版本，正式包才1.2.3版本，为什么会有1.2.6的最新包？没有上传最新代码吗？[QUESTION]

### ISSUE THREAD

**Issue by tzxylao** [metersphere/metersphere#28149]
### 请描述您的问题

我有两个问题哈
1. 我们打算使用你们metersphere的商业版，是不是部署最新的v3.x版本，那么这个版本你们支持插件idea接口导出到metershpere吗？
2. 导出插件的版本过低，1.2.3和1.2.6差距在哪，可以把代码仓库更新到最新吗？我们使用quarkus，插件明显需要自己定制化改造才能用，但看metersphere的最新代码，没看到和原来v1.20一样或类似的/api/definition/import接口，那么最新版本是还没支持吗？

**Comment by fit2-zhao** [comment]
你好，感谢对我们产品的支持。

问题1：v3.x 版本还在开发过程中，目前稳定版本是v2.10.10  LTS 版，建议使用这个版本，这个版本就支持IDEA 同步接口到MeterSphere ；v3 .x 版本后续也会支持IDEA接口同步到MeterSphere。

问题2:  < 1.2.6 版本的插件兼容IDEA 2020.1 — 2023.1.x 版本，插件使用的是jdk 11 做的包，从1.2.6 开始兼容最新版本IDEA 2023.2.x 之后版本，使用的是jdk 17 做的包， 您可以根据自己需求选择。目前插件仓库 v2.0 分支就是v2版本的最新代码；master 分支对应的是v1版本最新代码；v3.x 分支是开发中对应v3 版本的代码。
