### ISSUE TITLE
[BUG]   swagger导入的接口，保存api失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28156]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

 swagger导入的接口，保存api失败

### 重现步骤

 swagger导入的接口，保存api失败，私聊可发送metersphere接口文件
![image](https://github.com/metersphere/metersphere/assets/103925124/d0d5e75b-e9a5-413c-87f4-e64b24d40427)
![lQLPJx1c0lWaXwPNAnTNB3Gwi9CVyhx3FKMFfEDgkB-DAA_1905_628](https://github.com/metersphere/metersphere/assets/103925124/2a6e1380-7510-400b-b427-528d71f862da)

**Comment by 13290445582** [comment]
最新版本v2.10.10无此问题，请升级，感谢理解与支持。
