### ISSUE TITLE
V2.10版本为止，一直存在这个问题[BUG]

### ISSUE THREAD

**Issue by tzxylao** [metersphere/metersphere#28155]
### MeterSphere 版本

v.2.10

### 使用外置数据库

否

### 问题描述

<img width="1312" alt="image" src="https://github.com/metersphere/metersphere/assets/11553212/928c38c1-1d27-463f-8d0f-925ada62db4f">
<img width="792" alt="image" src="https://github.com/metersphere/metersphere/assets/11553212/615575d8-eda0-4c93-bfe3-e9b17221c1cb">

我看了v2.10及之前的代码，这个问题一直存在，用metersphere插件进行idea接口导入meterphere系统的时候，需要封装query查询参数，这个参数**是否必填required** 这个选项不能够自由传递，看代码因为写死了，希望能加入到PostmanKeyValue对象参数里。
metersphere的idea插件也非常不成熟，相比yapi，yapi能够支持quarkus接口的导出，metersphere-idea-plugin不支持，所以我会自行修改适配，但服务端需要麻烦你们支持下

### 重现步骤

v2.10之前都有这个问题，v3.x已经没有插件导入接口了？如果有请麻烦告诉我

**Comment by liuruibin** [comment]
v3.x 还在紧张的开发中，暂时不能告知

**Comment by tzxylao** [comment]
> v3.x 还在紧张的开发中，暂时不能告知

那v2版本能修复这个问题吗，从v1版本到现在一直存在 @liuruibin
