### ISSUE TITLE
[BUG]   生成测试数据，string类型，使用jmeter函数生成失败，mock是成功的

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28153]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

生成测试数据，string类型，使用jmeter函数生成失败，mock是成功的

### 重现步骤

如图点击生成测试数据，失败，未生成，mock是成功的
![image](https://github.com/metersphere/metersphere/assets/103925124/95e04c9d-2941-4c4d-aeef-60243cdbf1bd)

### 期待的正确结果

生成测试数据，可使用jmeter函数

_No response_

**Comment by fit2-zhao** [comment]
目前暂时不支持JMeter函数生成测试数据，JMeter函数是在执行时才能生效，生成数据功能并不会触发执行操作。
