### ISSUE TITLE
[BUG] 性能测试 java的net报错，性能测试抽样不展示数据报错信息

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28159]
### MeterSphere 版本

2.10.9

### 使用外置数据库

否

### 问题描述

性能测试 java的net报错，性能测试抽样不展示数据报错信息
![java的net报错，性能测试抽样不展示数据](https://github.com/metersphere/metersphere/assets/43202800/680d1741-483d-4d13-b086-ece396f0ed53)

### 重现步骤

性能测试 java的net报错，性能测试抽样不展示数据报错信息

**Comment by liqiang-fit2cloud** [comment]
网络错误时收不到响应数据，所以不显示。

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.10-lts未复现该问题，建议升级到最新版本尝试。
<img width="1395" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/452edf37-6e94-474f-9a1b-a58f70b4f50b">

**Comment by xhy12** [comment]
好的
