### ISSUE TITLE
[BUG] 站内消息中的用例连接，点击进去报错

### ISSUE THREAD

**Issue by ouyangkui** [metersphere/metersphere#28158]
### MeterSphere 版本

v1.20.x-lts

### 使用外置数据库

否

### 问题描述

用例品审，评论，
收到站内消息，查看，点击用例连接，报错
![image](https://github.com/metersphere/metersphere/assets/54564042/052656a1-b6b5-42be-a573-aab13767fb23)

### 重现步骤

用例品审，评论，
收到站内消息，查看，点击用例连接，报错

**Comment by 13290445582** [comment]
您好，在v1.20.24与v2.10.10环境验证，均未复现此问题，请升级最新版本v2.10.10版本进行测试，可导出提供下您评论点击跳转报错的用例。

**Comment by 13290445582** [comment]
您好，问题已复现，已关联至重复issue。
https://github.com/metersphere/metersphere/issues/28334
