### ISSUE TITLE
[BUG]环境变量上传csv 后，使用该环境运行接口场景，变量值取不到

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28167]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

在环境配置中，设置csv变量，在场景中打印变量，没有取到值

### 重现步骤

1. 环境配置中，设置csv变量
2. 在场景中使用次数循环控制器，打印变量，取不到值
3. 将csv 设置在场景变量中，在场景中使用次数循环控制器，可以成功打印

### 期待的正确结果

在环境配置中，设置csv变量，在场景中使用次数循环控制器，可以成功打印变量

### 附加信息

![1703752342730](https://github.com/metersphere/metersphere/assets/145318182/43dc2f8f-61a7-44cc-991a-1649575b3bbe)
![1703752381560](https://github.com/metersphere/metersphere/assets/145318182/a458dd73-e3f3-40cb-a944-8935015a19a3)
[country.csv](https://github.com/metersphere/metersphere/files/13784768/country.csv)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by fit2-zhao** [comment]
单独循环脚本确实有问题，配合请求一起使用，则能绕过此问题。
