### ISSUE TITLE
[BUG]接口自动化-场景引用，在脚本更新变量后，勾选优先使用当前场景变量，变量取值没有更新

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28160]
### 联系方式

jiaxin.li@fit2cloud.com

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口自动化，场景引入，勾选优先使用当前常见变量，在引用场景前，对变量值更新，引用场景中使用该变量，变量值没有更新

### 重现步骤

1. 创建场景a,设置场景变量为id=1
2. 创建场景b,设置场景变量id=2,使用自定义脚本，更新id=3,引用场景a,打开优先使用当前场景变量
3. 如上步骤调试。引用场景a的id=2
4. 取消勾选优先使用当前场景变量，id=3

### 期待的正确结果

无论是否勾选优先使用当前场景变量，id =3

### 附加信息

![1703742272216](https://github.com/metersphere/metersphere/assets/145318182/a9b3e5ce-6467-4df6-9aff-e586b5818c4c)
![1703742251185](https://github.com/metersphere/metersphere/assets/145318182/0348b9a5-2c66-4e6c-867b-83feea34edd8)

**Comment by zrfit** [comment]
您好，感谢反馈！默认不勾选场景设置-则优先取过程变量，如果勾选了场景设置，则按设置项优先取当前场景或者原场景的场景变量。
