### ISSUE TITLE
[BUG]kafka为多副本时，Got error produce response with correlation id 2332 on topic-partition ms-api-exec-topic-3, retrying (2147482482 attempts left). Error: NETWORK_EXCEPTION 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#28179]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

执行接口时，node-controller  info.log 报如下错
Got error produce response with correlation id 2332 on topic-partition ms-api-exec-topic-3, retrying (2147482482 attempts left). Error: NETWORK_EXCEPTION
Received invalid metadata error in produce request on partition ms-api-exec-topic-3 due to org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.. Going to request metadata update now

我们默认 acks 为 -1 (all)，建议改成默认为 1 

### 重现步骤

申请阿里云kafka（默认为集群）
![image](https://github.com/metersphere/metersphere/assets/30038088/86478cec-8de5-42f0-95e0-c6757c93b1d8)
执行接口测试

### 期待的正确结果

 在 /opt/metersphere/conf/metersphere.properties 加一下这个参数 spring.kafka.producer.acks=1 ,然后重启下 api-test 和 ms-node-controller ，之后再执行 就可以了 。
建议 改成默认 spring.kafka.producer.acks=1

**Comment by liuruibin** [comment]
感谢提醒，我们会在后续版本中优化这里
