### ISSUE TITLE
[FEATURE]建议功能用例支持设置多个责任人

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#28178]
### MeterSphere 版本

v2.10.10-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议功能用例可以设置多个责任人，因为实际中一条用例可能在多端，例如web端、app端都需要不同的责任人去验证，希望可以支持设置多个责任人
![image](https://github.com/metersphere/metersphere/assets/88763608/354a9368-ce12-4031-9eb5-73acca9d45b1)

**Comment by Hyyfit** [comment]
感谢反馈，v3已规划
