### ISSUE TITLE
[FEATURE]  测试跟踪，用例按模块删除，删除后回收站不展示模块，后续向恢复用例还要重新添加模块

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28170]
### MeterSphere 版本

2.10.9

### 请描述您的需求或者改进建议

 测试跟踪，用例按模块删除，删除后回收站不展示模块，后续向恢复用例还要重新添加模块

期望：按模块删除，回收站也按模块展示数据

**Comment by Hyyfit** [comment]
设计如此。整个模块删除了，用例就会归类到未规划中。
如果用例模块删除，回收站内显示了模块。用例列表又重新创建了同名模块，会有冲突。
