### ISSUE TITLE
[BUG]【接口定义】接口列表的模块名称与回收站的模块名称同名，删除接口列表中的模块，回收站里的模块名称变成了“未规划接口”

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28174]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

【接口定义】接口列表的模块名称与回收站的模块名称同名，删除接口列表中的模块，回收站里的模块名称变成了“未规划接口”

### 重现步骤

【接口定义】接口列表的模块名称与回收站的模块名称同名，删除接口列表中的模块，回收站里的模块名称变成了“未规划接口”
![image](https://github.com/metersphere/metersphere/assets/104960608/a5092cda-b7c7-4dea-8623-68c9d4af4c7b)
![image](https://github.com/metersphere/metersphere/assets/104960608/ba0a7d33-7e21-449b-bf82-b6c901b58287)
![image](https://github.com/metersphere/metersphere/assets/104960608/8a7c4ec2-232c-4d7f-9961-e298f7387b4c)
![image](https://github.com/metersphere/metersphere/assets/104960608/683745f3-e8cd-4ae1-8da4-8ad223a2eac3)

**Comment by zrfit** [comment]
您好，感谢反馈！删除整个模块，模块下的数据进入回收站未规划模块；只删除模块下数据不删除模块，删除后数据在回收站显示对应模块和删除的数据。
