### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by 997068329** [metersphere/metersphere#28175]
### MeterSphere 版本

v2.10

### 请描述您的需求或者改进建议

在做AIGC相关测试的时候，发现流式接口性能测试，响应时间能不能记录到首次流接收的时间

**Comment by liuruibin** [comment]
能详细描述场景吗，或者能提供一个jmx供我们在jmeter上调试吗

**Comment by 997068329** [comment]
你好，这个场景就是在ms平台上调用类openAI的接口，响应时间记录是整个流式输出完时的时间，ms平台能不能做到记录首个流式输出的时间，我看同类测试产品有这个功能对应连接，https://apifox.com/help/debugging-api/sse

**Comment by liuruibin** [comment]
暂时没有支持计划，等我们研究后决定
