### ISSUE TITLE
[BUG]  定时清理接口测试报告，表中未删除调试接口场景的报告结果数据，导致表数据占用内存过大

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28186]
### 联系方式

183114441708

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

定时清理接口测试报告，表中未删除调试接口场景的报告结果数据，导致表数据占用内存过大

### 重现步骤

定时清理接口测试报告，表中未删除调试接口场景的报告结果数据，导致表数据占用内存过大
![image](https://github.com/metersphere/metersphere/assets/103925124/9fd63427-ec16-4da3-9f5c-2ca67b781e71)
可看到场景调试历史：：
![image](https://github.com/metersphere/metersphere/assets/103925124/fadfa998-e6e5-40b1-81dc-ea8d22743c8d)
在数据库中过了一天也没被删除：api_scenario_report_result和api_scenario_report表都未删除调试的场景报告数据
![image](https://github.com/metersphere/metersphere/assets/103925124/f95c748d-358b-4460-93bc-1bbc5a3430aa)

**Comment by fit2-zhao** [comment]
感谢反馈，你这个应该是测试计划产生的数据，建议清理计划报告就行。
![image](https://github.com/metersphere/metersphere/assets/70558837/85965d59-c846-4db2-aceb-3fccf57d8e1a)

**Comment by fit2cloud-yaochunrong** [comment]
啊？我确实是场景直接调试啊，没有测试计划执行。要不你试下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年1月2日(周二) 上午9:33写道:

  

 
感谢反馈，你这个应该是测试计划产生的数据，建议清理计划报告就行。
 image.png (view on web)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #27831 

测试环境已复现，后续版本修复。
