### ISSUE TITLE
【接口场景】复制过来的接口场景里的接口url地址不能修改

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#2818]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
复制过来的接口场景里的接口url地址不能修改

**Bug 重现步骤**
1.copy了一个已有的接口场景
2.进入copy过来的场景里，修改某个接口的url地址
3.点击保存，然后运行，url地址还是老的调用地址

**Comment by xulinde** [comment]
没复现这个问题，您用的哪个版本？提交完有提示保存成功吗
