### ISSUE TITLE
[FEATURE]建议接口协议新增beanshell，方便扩展

### ISSUE THREAD

**Issue by StevenWangGitHub** [metersphere/metersphere#28181]
### MeterSphere 版本

v2.10.7-lts-7f7afdc5

### 请描述您的需求或者改进建议

建议接口协议新增beanshell，方便扩展，目前无法实现自己封装协议的接口测试

### 请描述你建议的实现方案

建议接口协议新增beanshell，像jmeter一样方便扩展，目前无法实现自己封装协议的接口测试

**Comment by luty2018** [comment]
感谢建议， v3已支持用户自定义扩展协议插件，参考插件开发：
https://github.com/metersphere/metersphere-platform-plugin/wiki/%E6%8F%92%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97%E2%80%90V3
