### ISSUE TITLE
【接口测试】批量运行接口场景后，没有一个显示页面可以查询当前测试进度和结果

### ISSUE THREAD

**Issue by jakubik1986** [metersphere/metersphere#2819]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
批量运行接口场景后，没有一个显示页面可以查询当前测试进度和结果

**Bug 重现步骤**
1.  打开接口自动化页面
2. 选择多个测试场景
3. 点击批量执行

**Comment by zyyfit** [comment]
您好，后续版本会考虑增加这个功能
