### ISSUE TITLE
[BUG] 【接口测试】接口自动化场景中导入多个场景时保存场景会很慢！

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28197]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

在A接口自动化场景中导入多个场景，保存A场景需要等待4-5S

### 重现步骤

1、进入接口自动化模块，创建新场景
2、在场景中导入接口用例或者接口
3、在场景中导入其他接口场景
4、保存场景

### 期待的正确结果

场景嵌套场景时，点击保存场景能快速保存

### 附加信息

1、场景更新
![image](https://github.com/metersphere/metersphere/assets/45531073/1a557d7b-0c4b-4c67-85a7-4676dd45edcb)
2、场景保存
![image](https://github.com/metersphere/metersphere/assets/45531073/76406acf-d08f-45c6-905a-e708bbc21cc9)

**Comment by 13290445582** [comment]
您好，A场景内大概多少步骤，所引用场景内是否有多步骤场景。

**Comment by Larson13** [comment]
接口步骤大该有5个，场景步骤不超过10个
![image](https://github.com/metersphere/metersphere/assets/45531073/803558f8-200d-497f-969b-08e85eaafa50)

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，关闭该issue，感谢理解与支持。
