### ISSUE TITLE
[BUG]测试计划关联测试用例时，通过搜索过滤后关联，点击关联时报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#28193]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

测试计划关联测试用例时，通过搜索过滤后关联，点击关联时报错。
![bc879548a1cd8401de062de40921d65](https://github.com/metersphere/metersphere/assets/83771182/72ceb0bf-c7b9-4ef6-b44e-afc090468a81)
![7a43fb3d18ac2f7b8d30c0782857a4b](https://github.com/metersphere/metersphere/assets/83771182/30d2d890-96a3-4812-9e5c-fff4be52198a)
[error.log](https://github.com/metersphere/metersphere/files/13807884/error.log)

### 重现步骤

测试计划关联测试用例时，通过搜索过滤后关联，点击关联时报错

**Comment by 13290445582** [comment]
您好，最新环境未复现该问题，建议升级最新版本v2.10.10版本尝试。
高级搜索筛选的哪个字段？只有勾选选择所有数据会复现还是任意选择用例关联都会复现该问题？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
