### ISSUE TITLE
[BUG]断言包含emoji时会失败

### ISSUE THREAD

**Issue by jarredzhong** [metersphere/metersphere#28194]
### 联系方式

zhongwenjin987@outlook.com

### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

否

### 问题描述

断言的期望结果跟实际结果包含emoji时，无论是否相等或匹配都会失败

### 重现步骤

1. 设置一个接口测试的响应的某个字段期望结果为emoji，如'🍔🍟🧋'；
2. 让接口对应的字段实际也返回期望的emoji，如'🍔🍟🧋'；
3. 执行该测试发现断言失败。

<img width="1462" src="https://github.com/metersphere/metersphere/assets/4101256/29670814-4c13-4c6d-b612-a659634070fb">

### 期待的正确结果

断言应该通过，因为两个字符串是相等的

**Comment by 13290445582** [comment]
您好，请提供下完整请求体。

**Comment by jarredzhong** [comment]
> 您好，请提供下完整请求体。

这个是我们内部的一个接口，通过一个用户ID查询用户详细信息，接口返回的昵称就是其中的一个字段，期望结果是通过该用户的id从数据库中获取昵称，部分请求信息如下：
<img width="818" alt="image" src="https://github.com/metersphere/metersphere/assets/4101256/62ecf10d-18aa-4063-bcf1-c407124b3016">

部分原始响应如下：
<img width="1079" alt="image" src="https://github.com/metersphere/metersphere/assets/4101256/22dbe06a-1933-47a4-a1e7-926b58642dde">

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，关闭该issue，感谢理解与支持。
