### ISSUE TITLE
[BUG]测试跟踪下的测试计划设置定时任务，定时任务偶尔会执行，之前执行的定时任务状态一直是starting 或者Running

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#2820]
**MeterSphere 版本**
V1.9.1

**Bug 描述**
测试跟踪下的测试计划设置定时任务，定时任务偶尔会执行，之前执行的定时任务状态一直是starting 或者Running

**期待的正确结果**
定时任务正常执行并且状态及时更新，邮件及时发送，现在感觉像是hang住了

**截图**
如果有截图，请附上截图.

![WechatIMG159](https://user-images.githubusercontent.com/32027713/118235102-db421f00-b4c6-11eb-8bab-97f0c805296f.jpeg)

日志报错：
![WechatIMG161](https://user-images.githubusercontent.com/32027713/118235142-ec8b2b80-b4c6-11eb-9c48-21be6babd657.jpeg)
![WechatIMG104](https://user-images.githubusercontent.com/32027713/118236433-a5059f00-b4c8-11eb-9d77-7171f042adce.jpeg)

**Comment by xulinde** [comment]
1.9.2已修复
