### ISSUE TITLE
[BUG] vars.put(${__metersphere_env_id}+"re_ul_cookie",re_ul_cookie);无法写入环境参数

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#28213]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

vars.put(${__metersphere_env_id}+"re_ul_cookie",re_ul_cookie);无法写入环境参数

### 重现步骤

vars.put(${__metersphere_env_id}+"re_ul_cookie",re_ul_cookie);无法写入环境参数

**Comment by youliyuan-fit2cloud** [comment]
你好，应该这么写：vars.put(${__metersphere_env_id}+"re_ul_cookie","re_ul_cookie");

**Comment by chase001** [comment]
已经回退到： v2.10.9-lts-1268b1f8
请解释下为什么： v2.10.9-lts-1268b1f8这样写就没有问题呢？vars.put(${__metersphere_env_id}+"re_ul_cookie",re_ul_cookie);

**Comment by Somebody-JIAN** [comment]
您好。  v2.10.10这样写也没有问题：

![image](https://github.com/metersphere/metersphere/assets/75963100/ed45766f-e5b0-473e-b3cc-dfaf3b14f31b)


![image](https://github.com/metersphere/metersphere/assets/75963100/ced7bc23-0153-4587-ad46-f465fa2e2817)


不知道您re_ul_cookie这个变量是什么时候获取到的？ 方便提供一下嘛，我们再尝试一下

**Comment by chase001** [comment]
以下是提取的操作
![image](https://github.com/metersphere/metersphere/assets/23476281/168528ce-995f-4787-8c59-0f0083c95d67)

**Comment by Somebody-JIAN** [comment]
您好：
我们模仿您提供的参数做了一个简易的脚本：
![image](https://github.com/metersphere/metersphere/assets/75963100/eec85599-b5d8-40d4-8305-6160a80b1d66)

最终执行的时候发现没出现问题：
![image](https://github.com/metersphere/metersphere/assets/75963100/491b6537-1411-4f89-8218-d5a12d1a80c0)

![image](https://github.com/metersphere/metersphere/assets/75963100/4746e8ee-6949-4fa0-9077-b0d59b3fc17d)
