### ISSUE TITLE
[FEATURE] MS插件导入API 或HAR导入API，无用的header信息占用太多的页面篇幅，体验不好

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#28216]
### MeterSphere 版本

v2.10.10

### 请描述您的需求或者改进建议

HAR或ms插件录制导入API时，是否可以考虑 配置默认的header 属性信息
![image](https://github.com/metersphere/metersphere/assets/82088551/e8fe7794-da71-4edc-a18d-2ce0c3e5d61f)
![image](https://github.com/metersphere/metersphere/assets/82088551/a8a1cdca-6e1f-49f2-a92b-1d8eec51857a)

**Comment by luty2018** [comment]
您觉得需要的有哪些， 我们可以做一个配置出来

**Comment by zhangzhaox** [comment]
没有理解你所述的整理配置表单的意思，我的问题如HAR数据包导入时希望导入的header头信息能够自定义选择有价值的，而不是默认所有，默认所有导入所有header信息 就会出现上述页面无用头信息太多占用页面篇幅的情况。
常用的有价值的头信息如Content-Type 、Authorization、token等，希望导入体验如swagger导入时可自定义头信息一样

**Comment by luty2018** [comment]
了解了， 目前v2版本可以简单优化的是， 导入时增加是否同步导入Header的开关， 但是不提供自定义请求头的功能， 用户可以在环境的请求头中配置全局请求头，这样是否能满足你的需求？

**Comment by zhangzhaox** [comment]
目前v2版本可以简单优化的是， 导入时增加是否同步导入Header的开关，也可以
