### ISSUE TITLE
性能测试json断言使用测试报告统计错误

### ISSUE THREAD

**Issue by qweeqwew** [metersphere/metersphere#28218]
### 联系方式

17277762130

### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

本地脚本调试上传到met，脚本中的json断言如果不勾选mach as regular expression，测试报告中的错误记录会把断言正确的交易认定为错误的

### 重现步骤

本地jmeter调试脚本，添加json断言，不勾选mach as regular expression，上传到met性能测试，错误记录会把断言成功的交易显示出来，如"value expect to be 0000, but found 0000"

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试环境没有复现，方便把这个文件发给我们复现吗？

**Comment by qweeqwew** [comment]
抱歉不方便，脚本是根据我们内部系统调试的。你们在本地jmeter调试脚本，在脚本中添加json断言，然后将脚本上传到性能测试。应该便能复现该问题

**Comment by qweeqwew** [comment]
我们又尝试了其它脚本，发现无该问题，但是仅针对我们某个内部系统的脚本存在该问题，我们这边再看看

**Comment by qweeqwew** [comment]
json断言的路径是一级就不会，二级就会，比如 $.x.x 就会，$.x的就不会出现

**Comment by youliyuan-fit2cloud** [comment]
> json断言的路径是一级就不会，二级就会，比如 就会，.x.x就会，.x的就不会出现

感谢再次反馈，我们也测试了多层级的，没有复现哦。
把你这个性能测试的日志详情 或者“下载执行文件” 发我们排查一下原因 ？
![image](https://github.com/metersphere/metersphere/assets/54612864/785453f8-bb00-442b-b6a0-9a28c1f08b4b)

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
