### ISSUE TITLE
[BUG]请求体参数Content-Type这个会缺失

### ISSUE THREAD

**Issue by whx156580** [metersphere/metersphere#28217]
### 联系方式

18595809728

### MeterSphere 版本

v2.10.6-lts-e87e920c

### 使用外置数据库

否

### 问题描述

就是我每次在请求头输入参数后 他总会少一个Content-Type这个参数
/

### 重现步骤

输入头 在输入体 回来再看就少了Content-Type这个参数

### 附加信息

=

**Comment by youliyuan-fit2cloud** [comment]
你好，请问下在请求体选中是哪种格式的内容，然后请求头的Content-Type的参数值内容是什么？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
