### ISSUE TITLE
[BUG] 测试计划，批量关联一万条用例，取消了几条用例后，所有关联的用例都消失了

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28215]
### MeterSphere 版本

2.10.6

### 使用外置数据库

否

### 问题描述

测试计划，批量关联一万条用例，取消了几条用例后，所有关联的用例都消失了

### 重现步骤

客户环境复现，测试计划，批量关联一万条用例，取消了几条用例后，所有关联的用例都消失了
![image](https://github.com/metersphere/metersphere/assets/43202800/f729555b-69c2-419a-a41a-79dc95d4da1a)

**Comment by youliyuan-fit2cloud** [comment]
无法复现，请说明怎么取消关联的用例？ 批量选中当前页还是全部页？

**Comment by xhy12** [comment]
升级最新版暂未复现了
