### ISSUE TITLE
[BUG]环境配置-->通用配置-->根据变量名称搜索，输入字符之后无法触发搜索

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#28212]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

环境配置-->通用配置-->根据变量名称搜索，输入字符之后无法触发搜索

### 重现步骤

环境配置-->通用配置-->根据变量名称搜索，输入字符之后无法触发搜索

![image](https://github.com/metersphere/metersphere/assets/23476281/38e1593f-33c8-46d0-b16f-e49cc34a2280)

**Comment by zrfit** [comment]
您好，最新版本v2.10.11-lts已修复，请升级后尝试。
