### ISSUE TITLE
[QUESTION]上传SFTP文件到服务器

### ISSUE THREAD

**Issue by Helena966** [metersphere/metersphere#28225]
### 请描述您的问题

使用python上传SFTP文件
![image](https://github.com/metersphere/metersphere/assets/66630660/7ffda005-1856-4f86-9caa-712c215d23c1)

**Comment by luty2018** [comment]
您的需求是？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
