### ISSUE TITLE
配置使用外部数据库，安装后发现 ms-server启动失败

### ISSUE THREAD

**Issue by dasandeyu** [metersphere/metersphere#2823]
**请描述您的问题.**
安装ms版本
1.9.1

关键报错
![image](https://user-images.githubusercontent.com/13783632/118247566-e781a880-b4d5-11eb-85fd-283958251594.png)

日志文件
[123.txt](https://github.com/metersphere/metersphere/files/6477708/123.txt)

**Comment by xulinde** [comment]
修改下sql_mode这个配置

**Comment by dasandeyu** [comment]
怎么修改呢？不好意思，我没弄清楚怎么改。

**Comment by dasandeyu** [comment]
> 修改下sql_mode这个配置

怎么修改呢？能描述的详细一点吗

**Comment by dasandeyu** [comment]
问题已解决。
![image](https://user-images.githubusercontent.com/13783632/118257998-e8b8d280-b4e1-11eb-8e07-8f4f352fb241.png)
