### ISSUE TITLE
[FEATURE] 测试报告关联的缺陷单状态 体验差

### ISSUE THREAD

**Issue by PandaTestGrid** [metersphere/metersphere#28247]
### MeterSphere 版本

v2.10.4-lts

### 联系方式

hanxuedong3011@gmail.com

### 请描述您的需求或者改进建议

1、metersphere jira 插件，测试报告关联的缺陷单状态没有随着 jira 单状态发生变化
2、关联的 jira 单无法通过链接快速跳转查看

**Comment by luty2018** [comment]
这个已经在v3版本中优化了哈， 可以关注v3的发布

**Comment by luty2018** [comment]
v3已发布，可以升级使用。
