### ISSUE TITLE
[BUG]-【接口自动化】无法获取自定义全局变量的最新值

### ISSUE THREAD

**Issue by yaweiyang0318** [metersphere/metersphere#28241]
### 联系方式

群：MeterSphere 交流群3  群昵称：Y

### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

场景：
A接口执行后，产生id：172 ，再次该接口执行产生id：178
B接口依赖A接口，取到的数据应该是最新的178，但是取的是172

### 重现步骤

1、A接口入参除name外，其他参数一致，在该场景中创建3条以上接口数据，接口名称命名为a1,a2,a3,a4....
2、为各自的接口设置独属于各自接口的全局变量：a1的id的全局变量：vars.put(${__metersphere_env_id}+"a1id","${id}");a2的id的全局变量：vars.put(${__metersphere_env_id}+"a2id","${id}");以此类推.....
3、A接口的出参ID作为B接口的入参，josn格式为：
{
    "dataTableColumnName": "gender",
    "id": "${a1id}",
}

### 相关日志输出

```shell
交流群中有详细的日志文件及步骤
```

**Comment by 13290445582** [comment]
您好，场景可以导出提供下吗？

**Comment by yaweiyang0318** [comment]
> 您好，场景可以导出提供下吗？

导出您也用不了，因为这是我们内部的环境，而且还做了vpn访问限制

**Comment by yaweiyang0318** [comment]
> > 您好，场景可以导出提供下吗？
> 
> 导出您也用不了，因为这是我们内部的环境，而且还做了vpn访问限制，或者我们远程排查也可以

**Comment by 13290445582** [comment]
您好，我们无法调试也没关系。可以导出您的场景看看具体是怎么写的，若所选环境里也有写其他内容，请截图说明。

**Comment by yaweiyang0318** [comment]
> 您好，我们无法调试也没关系。可以导出您的场景看看具体是怎么写的，若所选环境里也有写其他内容，请截图说明。

您好，场景已通过邮件形式发送

**Comment by 13290445582** [comment]
好的，可发送至我的邮箱：yicheng.wang@fit2cloud.com

**Comment by 13290445582** [comment]
您好，查看了脚本内容，非缺陷，是使用方法的错误。设置环境参数，我们会提供两行代码，补充上被删除掉的一行，即可取到值。往环境传值是执行完整个场景才会传值，不带第二行代码，取到的就为上一个值，所以需要第二行代码配合使用。
![image](https://github.com/metersphere/metersphere/assets/128017892/8886d38a-7078-437c-8430-9e757ff4e427)
