### ISSUE TITLE
[BUG]jsonPath断言问题

### ISSUE THREAD

**Issue by lishiyi11** [metersphere/metersphere#2825]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
1.jsonPath断言问题
匹配结果集中的所有list列表中每一项的siteCode---->$.result.list[*].siteCode--->等于和正则匹配结果不对，并不是效应list每条siteCode值都是AC,断言依然是成功

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![eadf65ea6baad6ab42822378e4759aa](https://user-images.githubusercontent.com/83342919/118249673-39c3c900-b4d8-11eb-8c72-4e78b4edb171.png)
![e4d4162e734452215952ee302a92741](https://user-images.githubusercontent.com/83342919/118249686-3c262300-b4d8-11eb-9261-67eaba18e944.png)

**Comment by zyyfit** [comment]
您好，暂时不支持这种使用方法，我们会考虑优化这个问题的
