### ISSUE TITLE
[FEATURE]  环境管理，添加域名希望能够批量添加

### ISSUE THREAD

**Issue by opopjasica** [metersphere/metersphere#28269]
### MeterSphere 版本

2.10.6

### 请描述您的需求或者改进建议

![8d91b2a24635cc0b98f817c574dda8f](https://github.com/metersphere/metersphere/assets/114552960/b04920bb-8c0b-4e31-9fca-b8fd2e6e72bb)
环境管理，添加域名希望能够批量添加

**Comment by Hyyfit** [comment]
感谢反馈，v3已规划了。
