### ISSUE TITLE
[BUG] ms 运行性能测试脚本，在jmeter上可以正常运行，在ms上会提示内存溢出，简单的单个接口能正常运行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28265]
### MeterSphere 版本

2.10.9

### 使用外置数据库

否

### 问题描述

ms 运行性能测试脚本，在jmeter上可以正常运行，在ms上会提示内存溢出，简单的单个接口能正常运行

应该是这个jmx脚本有某个字段解析异常，有客户的脚本，可以找我拿下

### 重现步骤

ms 运行性能测试脚本，在jmeter上可以正常运行，在ms上会提示内存溢出，简单的单个接口能正常运行

**Comment by liuruibin** [comment]
先调整资源池上的HEAP重新测试

**Comment by xhy12** [comment]
调大了-Xms4g -Xmx4g -XX:MaxMetaspaceSize=1028m    local 资源池可以 用独立安装的node-controller 不运行
![881d6fc671a2ac9903b33817d0fc856](https://github.com/metersphere/metersphere/assets/43202800/29aabd3c-a97b-4f8f-a551-33ada5798dcc)

**Comment by xhy12** [comment]
![f9c7c6e3d76fabbb54649231b76a0c9](https://github.com/metersphere/metersphere/assets/43202800/5e0a3034-cafc-4f53-bd44-c896941bbf12)

**Comment by xhy12** [comment]
空间足够
