### ISSUE TITLE
[BUG] 切换 tab 内存递增，存在内存泄漏的可能

### ISSUE THREAD

**Issue by yunaichun** [metersphere/metersphere#28271]
### 联系方式

naichunyu@gmail.com

### MeterSphere 版本

1.20

### 使用外置数据库

是

### 问题描述

切换 tab 内存递增，存在内存泄漏的可能

### 重现步骤

测试地址：https://cloud2.metersphere.com/#/track/case/all
测试路径：左侧 tab - 测试跟踪
测试步骤：不停点击顶部“首页”、“功能用例”。控制台切换到 Memory ，内存持续递增
![1](https://github.com/metersphere/metersphere/assets/15957114/d7f673b7-e7ce-492f-820a-4b4994dccd7e)
猜测：将 TestCaseList.vue 文件里的 ms-table 组件注释掉即稳定，猜测可能是这个组件有关系，麻烦帮忙看下

### 期待的正确结果

切换 tab 内存保持稳定

**Comment by youliyuan-fit2cloud** [comment]
最新版本没有复现该问题，请升级后尝试，感谢理解和支持。
