### ISSUE TITLE
[BUG]metersphere同步jira缺陷，未能将解决结果和经办人同步

### ISSUE THREAD

**Issue by zgs1** [metersphere/metersphere#28279]
### 联系方式

760097828@qq.com

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

集成jira，jira上修改了缺陷的解决结果和缺陷状态后，metersphere同步缺陷，未能将解决结果和经办人同步过来，导致测试人员无法在metersphere上关闭bug。

### 重现步骤

前置：已经集成jira，项目使用jira缺陷模板
1、测试人员使用metersphere提交缺陷，选择经办人
2、经办人在jira将bug状态变成已解决，并将解决结果至为‘延期解决’
3、测试人员使用metersphere同步缺陷后查看缺陷是否存在解决结果，经办人是否变成提交缺陷人员
4、测试人员，点击编辑，查看能否关闭缺陷

### 期待的正确结果

步骤2、开发人员在jira修改后，jira中缺陷状态变成已解决，解决结果为‘延期解决’，经办人变成提交缺陷人员
步骤3、缺陷解决结果应该为延期解决，经办人员变成实际的提交缺陷人员
步骤4、点击编辑，能够正常关闭缺陷

**Comment by zgs1** [comment]
在步骤4中，测试人员编辑缺陷，更改经办人后，点击保存后同步缺陷，metersphere上经办人依然是之前的开发人员

**Comment by 13290445582** [comment]
您好，本地测试环境未复现该问题，请问使用的什么版本的jira与jira插件？

**Comment by zgs1** [comment]
Jira v8.3.4   插件下载的最新的插件。更改了关联的jira账号，现在在metersphere能够更改状态了，但是同步缺陷后经办人还是无法同步过来（经办人和提交人不要是同一个人，真实使用是测试提交bug，经办人是开发人员）。缺少解决方法这个字段，也比较影响使用，因为延期解决或者无法复现这种也是已解决。

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，关闭该issue，感谢理解与支持。
