### ISSUE TITLE
[BUG]  场景变量csv使用while循环，循环次数异常

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28280]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

场景变量csv使用while循环，循环次数异常

### 重现步骤

场景变量csv使用while循环，循环次数异常    userId等于10077945的csv中只有一个
![image](https://github.com/metersphere/metersphere/assets/103925124/48a9f534-c82e-4c95-84eb-7ef2ecfe1ee6)
csv预览
![image](https://github.com/metersphere/metersphere/assets/103925124/23b98323-dc04-4d90-ac04-c6de99355ad4)
走了两次循环，应该是一次
![image](https://github.com/metersphere/metersphere/assets/103925124/459a6acd-06c6-4277-b20b-14813227f678)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已知，当初设计的缺陷，无法指定 csv 加载位置导致，v3版本会重新设计优化。

**Comment by luty2018** [comment]
v3.0已支持， 欢迎下载使用。
