### ISSUE TITLE
[BUG]  功能用例按名称排序，排序规则紊乱

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28289]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

功能用例按名称排序，排序规则紊乱

### 重现步骤

功能用例按名称排序，排序规则紊乱
![image](https://github.com/metersphere/metersphere/assets/103925124/df3799ad-ccc5-420c-9e75-2a578d51ab9a)
![image](https://github.com/metersphere/metersphere/assets/103925124/bf40e10b-110c-4310-8c43-4d01339f48fd)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个排序规则是按照数据库的字符串排序来的，暂时保持现状。如果有建议修改请提个需求。感谢理解和支持。
