### ISSUE TITLE
[BUG]  node-controller 资源池，改了端口，性能测试查看不到cpu使用率

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28286]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

node-controller 资源池，改了端口，性能测试查看不到cpu使用率

![image](https://github.com/metersphere/metersphere/assets/43202800/139d95fd-6a48-4b0e-ab1b-15098bab9c77)

### 重现步骤

node-controller 资源池，改了端口，性能测试查看不到cpu使用率

### 期待的正确结果

可以看到

**Comment by liuruibin** [comment]
<img width="646" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/24c1082d-1de1-4441-902a-dd74846b1398">
修改prometheus.yml 改成新端口

docker restart ms-prometheus
