### ISSUE TITLE
[BUG]2层循环控制器时，内部的计数使用外层接口获取的，内部计数最大值一直取的外层第一次循环获取的值

### ISSUE THREAD

**Issue by 844177611** [metersphere/metersphere#28285]
### 联系方式

844177611@qq.com

### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

场景如下：
循环控制器1（循环次数：5）
       接口1（提取参数A：数组；提取参数B：数组）
       循环控制器2（循环次数：${A_matchNr}）
              接口2：
                 请求体中参数a：${A_i}
                 请求体中参数b：${B_i}

i我目前是用的一个计数器：但下面的结束的值取的接口1第一次循环的值，后面循环的值一直看着像是没有获取到，所以导致i每次都是从1增加到第一次循环获取的值
开始：1
结束：${A_matchNr}
增加：1

### 重现步骤

场景如下：
循环控制器1（循环次数：5）
       接口1（提取参数A：数组；提取参数B：数组）
       循环控制器2（循环次数：${A_matchNr}）
              接口2：
                 请求体中参数a：${A_i}
                 请求体中参数b：${B_i}
计数器i：
开始：1
结束：${A_matchNr}
增加：1

执行结果如下：只有第一次循环12次的时候num取值是对的，后面的20和6的时候num取值还是遵循的第一次的12次来的
<img width="463" alt="5502c33138bf27fbcd96af10f5526c5" src="https://github.com/metersphere/metersphere/assets/129732806/62e42711-e15e-453a-97bf-63995c7df3cb">

### 期待的正确结果

循环控制器1：
    第一次循环获取控制器2的循环次数12：
        num: 1
        ...
        num: 12
    第二次循环获取控制器2的循环次数20：
        num: 1
        ...
        num: 20
    第三次循环获取控制器2的循环次数6：
        num: 1
        ...
        num: 6

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.10-lts未复现该问题，请提供具体场景，我们尝试复现。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
