### ISSUE TITLE
[BUG]压测报告里面：测试概览的错误数据 跟 请求统计里面的错误数据对不上

### ISSUE THREAD

**Issue by sherottkx** [metersphere/metersphere#28299]
### 联系方式

m15671564568@163.com

### MeterSphere 版本

2.10.9

### 使用外置数据库

否

### 问题描述

压测报告里面：测试概览的错误数据 跟 请求统计里面的错误数据怎么对不上呢？

### 重现步骤

压测报告里面：测试概览的错误数据 跟 请求统计里面的错误数据怎么对不上呢？

### 附加信息

![微信图片_20240112100025](https://github.com/metersphere/metersphere/assets/156389292/9bb1a905-6090-469b-8636-97fde23b1ebe)
![微信图片_20240112100035](https://github.com/metersphere/metersphere/assets/156389292/fd323ce9-f48a-4450-a8f4-36890e2443c1)

**Comment by liuruibin** [comment]
这个已经在v2.10.10中修复了，请更新至最新版本测试

**Comment by sherottkx** [comment]
你好，我们拉了2.10.10版本的最新代码，发现并没有我这个bug的相关修改记录。是不是记错了啊，我现在更新到 了2.10.10版本，确实问题依然存在。麻烦再帮忙看看













在 2024-01-12 10:41:56，"刘瑞斌" ***@***.***> 写道：

这个已经在v2.10.10中修复了，请更新至最新版本测试
