### ISSUE TITLE
[BUG]UI测试场景有多层嵌套引用场景时，修改原场景内容，不会同步到引用的场景中

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#28291]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

UI测试场景有多层嵌套引用场景时，修改原场景内容，不会同步到引用的场景中

### 重现步骤

1、创建一个场景A，然后场景B里面引用场景A，场景C里面再引用场景C
<img width="792" alt="8a12f4623eedb68d1d891bc0c305a6e" src="https://github.com/metersphere/metersphere/assets/88763608/59e4ff1c-8dcb-44f8-8f3e-8e11fd95016a">

2、修改场景A，不会同步到场景C中
<img width="830" alt="8372b478cc987bd0daa4f366f95e8a2" src="https://github.com/metersphere/metersphere/assets/88763608/323f077c-a926-4623-9005-95deef29f73f">

### 期待的正确结果

应该要同步变更

**Comment by zrfit** [comment]
你好，感谢反馈！v2后续版本修复。

**Comment by linfengjjj** [comment]
你好 这个缺陷什么时候可以修复好？

**Comment by Hyyfit** [comment]
v3会修复。
