### ISSUE TITLE
[BUG]安装后，ms-node-controller 和 ms-server两个服务无法启动

### ISSUE THREAD

**Issue by chenhb-zte** [metersphere/metersphere#283]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

ms-node-controller   /deployments/run-java.sh         Exit 1                                                             
ms-server            /deployments/run-java.sh         Exit 1  

docker ps -a
d1d1d8070c61        registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v1.1.2          "/deployments/run-..."   46 seconds ago      Exited (1) 35 seconds ago                                                             ms-server
4daa76208556        registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.1.2   "/deployments/run-..."   46 seconds ago      Exited (1) 37 seconds ago                                                             ms-node-controller

docker logs
8:37:46,772 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/metersphere/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (Permission denied)
        at java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (Permission denied)
        at      at java.io.FileOutputStream.open0(Native Method)
        at      at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.jav

**Bug 重现步骤**
1.  curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问现在可以正常运行了吗
