### ISSUE TITLE
[BUG]性能测试-高级配置中开启 csv 分割后，点击保存，不定时出现 'csv 分割' 和 'csv 表头' 退回关闭的情况

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#28308]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

性能测试-高级配置中开启 csv 分割后，点击保存，不定时出现 'csv 分割' 和 'csv 表头' 退回关闭的情况

### 重现步骤

1.创建接口场景，上传csv 
2.转成性能测试
3.选择资源池、设置线程组，点击保存
4.高级配置中开启 'csv 分割' 和 'csv 表头'  
5.点击保存，'csv 分割' 和 'csv 表头'  变成关闭。

### 期待的正确结果

点击保存，'csv 分割' 和 'csv 表头'  不会回退成 关闭。

**Comment by liuruibin** [comment]
请耐心等待，我们会不断优化
