### ISSUE TITLE
[BUG] helm安装V2.9.1版本metersphere，使用外置mysql数据库，数据库未能进行初始化

### ISSUE THREAD

**Issue by fanqinghui** [metersphere/metersphere#28309]
### 联系方式

fanqinghui@yeah.net

### MeterSphere 版本

V2.9.1

### 使用外置数据库

是

### 问题描述

执行helm脚本后，容器服务后台报错缺少表

### 重现步骤

helm 脚本如下：
`ingress:
  enabled: true
  host: metersphere.XXXX.cn
  annotations:
    #{}
    ## example for ingress annotions.
    kubernetes.io/ingress.class: it-intra
    kubernetes.io/tls-acme: "true"
  https:
    enabled: true
    secretName: "tls-hi-ins-com-cn"

common:
  imagePrefix: "registry.cn-qingdao.aliyuncs.com/metersphere/"
  imagePullSecrets: nil
  storageClass: metersphere-data
  imageTag: v2.9.1
  imagePullPolicy: Always
  properties: |-
    ## DATABASE
    spring.datasource.url=jdbc:mysql://{{.Values.mysql.host}}:{{.Values.mysql.port}}/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username={{.Values.mysql.username}}
    spring.datasource.password={{.Values.mysql.password}}

    ## redis
    spring.session.store-type=redis
    spring.redis.redisson.file=file:/opt/metersphere/conf/redisson.yml

    ## KAFKA
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic={{.Values.kafka.metricTopic}}
    kafka.bootstrap-servers={{.Values.kafka.host}}.{{.Release.Namespace}}:{{.Values.kafka.port}}
    kafka.log.topic={{.Values.kafka.logTopic}}
    kafka.test.topic={{.Values.kafka.testTopic}}
    kafka.report.topic={{.Values.kafka.reportTopic}}
    tcp.mock.port=10000

    ## minio
    minio.endpoint=http://{{.Values.minio.host}}:{{.Values.minio.port}}
    minio.access-key={{.Values.minio.username}}
    minio.secret-key={{.Values.minio.password}}

    ## JMETER
    jmeter.image={{ .Values.common.imagePrefix }}{{.Values.jmeter.image}}:{{.Values.jmeter.imageTag}}
    jmeter.pod.threads.limit=500

    ## K8S
    k8s.node-controller-image={{ .Values.common.imagePrefix }}{{.Values.nodeController.image}}:{{.Values.common.imageTag}}

    ## spring cloud
    eureka.client.service-url.defaultZone=http://{{.Values.eureka.host}}:{{.Values.eureka.port}}/eureka/

    logger.sql.level=info

apiTest:
  enabled: true
  image: api-test
  replicas: 1

performanceTest:
  enabled: true
  image: performance-test
  replicas: 1

systemSetting:
  enabled: true
  image: system-setting
  replicas: 1

projectManagement:
  enabled: true
  image: project-management
  replicas: 1

reportStat:
  enabled: true
  image: report-stat
  replicas: 1

testTrack:
  enabled: true
  image: test-track
  replicas: 1

gateway:
  enabled: true
  image: gateway
  replicas: 1

eureka:
  enabled: true
  image: eureka
  host: metersphere-eureka
  port: 8761
  replicas: 1

dataStreaming:
  enabled: true
  image: data-streaming
  replicas: 1
  properties: |-
    ## DATABASE
    spring.datasource.url=jdbc:mysql://{{.Values.mysql.host}}:{{.Values.mysql.port}}/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username={{.Values.mysql.username}}
    spring.datasource.password={{.Values.mysql.password}}

    ## KAFKA
    kafka.partitions=1
    kafka.replicas=1
    kafka.topic={{.Values.kafka.metricTopic}}
    kafka.bootstrap-servers={{.Values.kafka.host}}:{{.Values.kafka.port}}
    kafka.log.topic={{.Values.kafka.logTopic}}
    kafka.test.topic={{.Values.kafka.testTopic}}
    kafka.report.topic={{.Values.kafka.reportTopic}}
    jmeter.report.granularity=5000

    ## minio
    minio.endpoint=http://{{.Values.minio.host}}:{{.Values.minio.port}}
    minio.access-key={{.Values.minio.username}}
    minio.secret-key={{.Values.minio.password}}

uiTest:
  enabled: false
  image: ui-test
  replicas: 1

workstation:
  enabled: true
  image: workstation
  replicas: 1

nodeController:
  enabled: true
  image: node-controller
  replicas: 1
  properties: |-
    ## TBD

redisson:
  yml: |-
    singleServerConfig:
      password: {{.Values.redis.password}}
      address: "redis://{{.Values.redis.host}}:{{.Values.redis.port}}"
      database: {{.Values.redis.database}}

jmeter:
  image: jmeter-master
  imageTag: 5.5-ms4-jdk17

logPersistence:
  enabled: true
  accessModes: ReadWriteMany
  size: 10Gi

dataPersistence:
  enabled: true
  accessModes: ReadWriteMany
  size: 10Gi

mysql:
  enabled: false
  image: mysql
  imageTag: "8.0.33"
  #host: metersphere-mysql
  host: 10.75.0.8
  port: 3306
  username: metersphere
  password: metersphere@mysql
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 20Gi
minio:
  enabled: true
  image: minio
  imageTag: "RELEASE.2023-04-13T03-08-07Z"
  username: admin
  password: Password123@minio
  host: metersphere-minio
  port: 9000
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 20Gi
redis:
  enabled: false
  image: redis
  imageTag: "6.2.6"
  password: metersphere@redis123
  #host: metersphere-redis
  host: 10.75.0.3
  port: 6379
  database: 1
  persistence:
    enabled: true
    accessModes: ReadWriteOnce
    size: 10Gi
kafka:
  enabled: true
  fullnameOverride: metersphere-kafka
  host: metersphere-kafka
  port: 9092
  metricTopic: JMETER_METRICS
  logTopic: JMETER_LOGS
  testTopic: LOAD_TESTS
  reportTopic: JMETER_REPORTS
  persistence:
    enabled: false
  logPersistence:
    enabled: false
  logFlushIntervalMessages: _10000
  logFlushIntervalMs: 1000
  logRetentionBytes: _1073741824
  logRetentionCheckIntervalMs: 300000
  logRetentionHours: 168
  logSegmentBytes: _1073741824
  maxMessageBytes: _1000012
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 15
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 15
  externalAccess:
    enabled: true
    service:
      type: NodePort
      useHostIPs: true
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
  extraEnvVars:
    - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
      value: "true"
  kraft:
    enabled: true
  zookeeper:
    enabled: false
`

**Comment by liuruibin** [comment]
重新安装呢

实在找不到问题的话可以先用内置mysql启动，导出到外置数据库中

**Comment by 13290445582** [comment]
您好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请重新提issue，感谢理解和支持。
