### ISSUE TITLE
[BUG]测试计划编辑之后 编辑的测试计划是会跳到第一个，页面上没有展示出来

### ISSUE THREAD

**Issue by wuhuqifei11111** [metersphere/metersphere#28302]
### 联系方式

🎶

### MeterSphere 版本

 v2.10.7-lts-7f7afdc5

### 使用外置数据库

否

### 问题描述

测试计划编辑之后 编辑的测试计划是会跳到第一个的  现在可能是页面上没有展示出来  但是逻辑已经执行了  就导致这边测试计划配置后  越配置越乱

### 重现步骤

编辑配置测试计划环境即可复现

### 期待的正确结果

编辑测试计划后  页面能够正常像以前那样跳到第一个  或者 是后端的逻辑修改下

### 附加信息

![img_v3_0271_90aa3bf8-40c9-49ce-a269-60f0e24424fg](https://github.com/metersphere/metersphere/assets/156394386/8516aa87-0b69-4a3d-a05a-1490add2c118)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.10-lts未复现该问题，建议升级到最新版本尝试。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
