### ISSUE TITLE
[FEATURE]【优化建议】接口文档中对于字段的描述，不能默认显示出来，要手动点击展开，这个能不能优化一下，使用上很不方便

### ISSUE THREAD

**Issue by sherottkx** [metersphere/metersphere#28300]
### MeterSphere 版本

2.10.9

### 联系方式

m15671564568@163.com

### 请描述您的需求或者改进建议

接口文档中对于字段的描述，不能默认显示出来，要手动点击展开，这个能不能优化一下，使用上很不方便

### 请描述你建议的实现方案

建议每次默认就显示描述信息，因为研发的时候很多很多备注都写在描述信息里面，提高产研对接效率

### 附加信息

![微信图片_20240112112531](https://github.com/metersphere/metersphere/assets/156389292/a99cbd71-3c42-4a8f-9ed7-2963d0b7866b)
![微信图片_20240112112551](https://github.com/metersphere/metersphere/assets/156389292/e10af210-9d23-46cb-89ab-f20058e2a2c1)

**Comment by luty2018** [comment]
感谢建议， 这个我们已经在v3.0版本优化了， 可以关注v3.0版本的发布。
