### ISSUE TITLE
[BUG]性能测试，概览数据中 tps最高是900多 但是汇总是1748

### ISSUE THREAD

**Issue by sherottkx** [metersphere/metersphere#28314]
### 联系方式

m15671564568@163.com

### MeterSphere 版本

2.10.9

### 使用外置数据库

否

### 问题描述

性能测试模块，概览数据中 tps最高是900多 但是汇总是1748。详见附件截图

### 重现步骤

性能测试模块，概览数据中 tps最高是900多 但是汇总是1748。详见附件截图

### 附加信息

![20240112-153143](https://github.com/metersphere/metersphere/assets/156389292/a7e48282-6f9f-4dea-baac-ad0c142bd329)

**Comment by liuruibin** [comment]
从图上看不出来是什么问题，你可以从100vu一步步开始测试

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
