### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by huangliang1125** [metersphere/metersphere#28316]
### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 联系方式

365159654@qq.com

### 请描述您的需求或者改进建议

建议加入项目管理相关的能力，至少要把缺陷管理加入流转功能，可以减少内部不同工具的使用，项目管理者、开发、测试都能通过这1个工具对项目的总体测试工作和质量进行全面了解。

**Comment by Hyyfit** [comment]
感谢反馈，v3的缺陷管理已规划了状态流转的功能；
