### ISSUE TITLE
[BUG]  metersphere走Nginx访问时，出现网络不稳定/抖动时，页面弹出框异常，非提示网络异常，或直接后台重试

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28320]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

metersphere走Nginx时因网络不稳定/抖动时，页面弹出框异常

### 重现步骤

metersphere走Nginx时因网络不稳定/抖动时，页面弹出框异常
![image](https://github.com/metersphere/metersphere/assets/103925124/0233971a-4346-4ed6-8d04-29a3b5de7f23)

后台日志无相关异常，所以是本地访问Nginx代理后的metersphere，网络异常时报的

### 期待的正确结果

提示网络不稳定/后台重试，页面报错不友好，希望优化

**Comment by liuruibin** [comment]
你可以看看这个配置 https://www.cnblogs.com/kongieg/p/16495335.html
