### ISSUE TITLE
[BUG]点击用例评审消息通知，跳转用例报错：target must be object

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28334]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

1. 用例评审添加评论
2. 接受评审通知后，在消息通知，点击用例名称
3. 页面跳转后提示target must be object

### 重现步骤

1. 用例评审添加评论
2. 接受评审通知后，在消息通知，点击用例名称
3. 页面跳转后提示target must be object

### 期待的正确结果

1. 用例评审添加评论
2. 接受评审通知后，在消息通知，点击用例名称  可正常打开用例评审页，或者直接打开该用例页面

### 附加信息

![Uploading 1705297579337.jpg…]()

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by Hyyfit** [comment]
v3已覆盖该缺陷，请关注后续的版本发布
