### ISSUE TITLE
[QUESTION]helm部署metersphere，登录后页面显示空白，版本2.10.10

### ISSUE THREAD

**Issue by RogerQian27** [metersphere/metersphere#28337]
### 请描述您的问题

helm部署metersphere，登录后页面显示空白，版本2.10.10，详细内容请查看附件图片
![1](https://github.com/metersphere/metersphere/assets/42488705/95e9d25b-464e-4057-af90-c836aec580a8)
![log](https://github.com/metersphere/metersphere/assets/42488705/e2399c35-a6f2-48ec-9e73-13a5fdc44fa2)

**Comment by luty2018** [comment]
请问该问题是否依然存在？

**Comment by RogerQian27** [comment]
图片还是加载不出来，我没有使用ingress域名，将workstation的service改成了nodeport模式，不知是否这个改动的原因。
![1](https://github.com/metersphere/metersphere/assets/42488705/c8be2254-012b-44ef-8d59-d29d19c9d738)

**Comment by RogerQian27** [comment]
已解决，根据最新的文档，新建了gateway的service，就可以了。感谢

https://metersphere.io/docs/v2.x/installation/kubernetes_installation/
