### ISSUE TITLE
[BUG]【接口定义】导入swagger数据，当字段为数组时，导入进去值不正确

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28333]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

【接口定义】导入swagger数据，当字段为数组时，导入进去值不正确

### 重现步骤

【接口定义】导入swagger数据，当字段为数组时，导入进去值不正确
![image](https://github.com/metersphere/metersphere/assets/104960608/283e7893-d1ca-4e29-ba91-05bf0060a4ec)
![image](https://github.com/metersphere/metersphere/assets/104960608/53cc33c1-0722-4bb2-ad82-7467b7709fb1)
[user.zip](https://github.com/metersphere/metersphere/files/13934609/user.zip)

**Comment by 13290445582** [comment]
![image](https://github.com/metersphere/metersphere/assets/128017892/aec52b4d-ebf2-4b09-aa4e-d50063af24b2)
![image](https://github.com/metersphere/metersphere/assets/128017892/352818a1-7562-4d5c-9227-0d964274d5fa)
您好，文件中的内容采用图2的写法是有值的。
