### ISSUE TITLE
[BUG] 接口测试-环境组列表未刷新

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28332]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

[BUG] 接口测试环境组列表未刷新

### 重现步骤

项目里面的跨项目的case和api，已经删除替换成其他项目，刷新场景，环境已刷新，环境组已选择的未刷新
![image](https://github.com/metersphere/metersphere/assets/103925124/2b56eb88-c386-49c9-b65f-520dc666a47d)

### 期待的正确结果

不可使用的环境组，被清空，不被选中

**Comment by 13290445582** [comment]
您好，v2版本不再优化该问题，我们将在v3版本优化下。
