### ISSUE TITLE
[BUG] 性能测试压测时间长会导致磁盘io明显上升，磁盘占用空间明显上升

### ISSUE THREAD

**Issue by vvvzhangshuo** [metersphere/metersphere#28330]
### 联系方式

v__2008@yeah.net

### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

我压测通常使用80用户数，开启PRS, PRS 3000， 压测时长1小时
load_test_report_detail表的数据量经常会增加数十G , 且磁盘IO极高，导致平台非常卡顿。导致压测也经常自动停止。
服务器配置为8核16G SSD
认为load_test_report_detail表相关的逻辑有问题，单条数据的longtext数MB, 且频繁读写，导致整个平台在压测时稳定性极差。且压测结束后仍然占用极大磁盘空间，按理说应该删除无用数据，毕竟压测报告中的信息也是较少的，用不到这几G数据、
![meter_io](https://github.com/metersphere/metersphere/assets/37901979/062b6c74-4f51-4b52-995d-a9c9580c2f7f)

一个小时的测试完成后，服务器的io占用更高了，整个平台变得更加卡顿
![image](https://github.com/metersphere/metersphere/assets/37901979/5db0b43d-f0bf-48a6-b0af-7f528782aec3)
服务器读写高达数十MB

### 重现步骤

ubuntu20 server LTS
压测： 80用户数，开启PRS, PRS 3000，接口为GET请求，url较长。 压测时长1小时
压测结束后20分钟后导出报告
全程使用iotop软件监控磁盘io

### 期待的正确结果

磁盘io无明显上升，磁盘占用空间无明显上升

**Comment by 13290445582** [comment]
您好，欢迎来使用我们的企业版https://metersphere.io/。开源版确实一直有此问题，在企业版我们的算法进行了更新优化，建议您使用企业版，感谢理解。
