### ISSUE TITLE
[BUG]场景执行一次保存报错Internal exception occured, please check logs or contact administrator.

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28340]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

自动化场景，导入Mock 接口，提取参数，后续设置脚本打印该参数，点击调试后，再点击保存  页面报错 nternal exception occured, please check logs or contact administrator.

### 重现步骤

1. 附件为场景脚本，导入场景脚本，使用mock 环境
2. 点击运行第一个mock 接口，接口返回成功，点击保存 报错 Internal exception occured, please check logs or contact administrator.

### 期待的正确结果

可以正常保存场景数据

### 附加信息

![1705306947258](https://github.com/metersphere/metersphere/assets/145318182/3d28a831-ba1c-4139-b093-a0a5b056e263)
![1705306642301](https://github.com/metersphere/metersphere/assets/145318182/52cd0e3f-1ec4-4d2f-a3c3-e3c257400469)
[Metersphere_Scenario_测试项目 (3).json](https://github.com/metersphere/metersphere/files/13936591/Metersphere_Scenario_.3.json)

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.11已修复，请升级。
