### ISSUE TITLE
[FEATURE]批量编辑功能用例，增加批量修改企业版版本管理的选项

### ISSUE THREAD

**Issue by haipeng-fit2** [metersphere/metersphere#28344]
### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 请描述您的需求或者改进建议

希望在测试跟踪-功能用例，批量编辑功能用例，增加批量修改企业版的版本的选项，方便在功能没有更新时，可以批量新建多个功能新版本，而不用导出再导入的方式

### 附加信息

<img width="1260" alt="image" src="https://github.com/metersphere/metersphere/assets/81673899/b8f83138-e57b-4ab3-a97f-2868519c9733">

**Comment by luty2018** [comment]
感谢反馈， 这个功能已经规划到v3.0版本中了

**Comment by luty2018** [comment]
v2已支持匹配修改版本号。
