### ISSUE TITLE
[BUG]接口自动化场景中，body使用binary的方式提交doc\xls\ppt\wps\et\dps格式的文件，点击执行没反应

### ISSUE THREAD

**Issue by wuziyan1** [metersphere/metersphere#28351]
### 联系方式

836247742@qq.com

### MeterSphere 版本

V2.6.0

### 使用外置数据库

否

### 问题描述

接口自动化，请求体使用的格式为binary并上传doc\xls\ppt\wps\et\dps格式的文件，点击执行，没有反应

### 重现步骤

1、打开接口自动化
2、创建一个场景，并将url、header填写完整 
3、请求体选择的数据类型为binary，并进行文档上传
4、文档选择格式为doc\xls\ppt\wps\et\dps，并点击执行，无法执行

### 期待的正确结果

可正常执行doc\xls\ppt\wps\et\dps这6中格式的文件，后面那几种格式的文件是由doc、xls、ppt格式进行另存为就可以看到了

### 附加信息

https://github.com/metersphere/metersphere/assets/120242714/00f2d618-3f82-4635-be43-48d6e81161c5

**Comment by fit2-zhao** [comment]
请求升级到最新版本已经修复过了。
