### ISSUE TITLE
[BUG]拖拽脑图用例保存后用例丢失

### ISSUE THREAD

**Issue by tianx08** [metersphere/metersphere#28354]
### 联系方式

reej

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

测试跟踪模块-脑图模式下录入用例，模块A下 有M1,M2 两个模块， 模块M2 下有用例 U1,U2 两条用例，脑图模式下拖动U1用例到 M1模块下，接着删除模块M2，点击保存
模块M1下未新增用例（用例数为0） ，模块M2被删除

### 重现步骤

测试跟踪模块-脑图模式下录入用例，模块A下 有M1,M2 两个模块， 模块M2 下有用例 U1,U2 两条用例，脑图模式下拖动U1用例到 M1模块下，接着删除模块M2，点击保存
模块M1下未新增用例（用例数为0） ，模块M2被删除

### 期待的正确结果

模块M1下新增一条用例（用例数为1） ，模块M2及模块下用例被删除

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by Hyyfit** [comment]
v3 已覆盖该缺陷，请关注后续版本发布；
