### ISSUE TITLE
项目环境中如果配置了请求头，后续在修改删除时无法生效

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#2835]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9.2
**Bug 描述**
简要描述您碰到的问题
项目环境中如果配置了请求头，后续在修改删除时无法生效
**Bug 重现步骤**
1. 在项目环境中增加请求头
2. 接口场景中测试，可以正常使用
3. 修改项目环境中请求头
4. 接口场景中测试，修改不生效
5. 无论修改、删除、disable都无效

**期待的正确结果**
接口场景中能够正确引用项目环境的请求头

**截图**
![image](https://user-images.githubusercontent.com/30932762/118274860-3e987500-b4f8-11eb-858e-c9f047630b5c.png)
![image](https://user-images.githubusercontent.com/30932762/118274867-40623880-b4f8-11eb-8a56-f79f06c66d54.png)

**Comment by xulinde** [comment]
1.9.2已修复，请升级到最新版本在试下呢
