### ISSUE TITLE
[BUG] 修改 MeterSphere 主题颜色，在任务中心点击任务时，显示颜色不对

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28367]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

修改 MeterSphere 主题颜色为黄色，在任务中心点击任务时，任务条颜色变为紫色，颜色显示不正确

### 重现步骤

1、进入 系统设置-系统参数设置-显示设置中，修改主题色
2、进入任务中心，点击任务

### 期待的正确结果

点击任务时，颜色会显示正确

### 附加信息

![274a9a4982eccef6ea3f4a5a60009171 (1)](https://github.com/metersphere/metersphere/assets/45531073/f47e6422-d6e8-497f-bc91-e548b25e6679)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。
