### ISSUE TITLE
[BUG]  在接口自动化场景中，有场景变量csv文件，然后把这个自动化转化成性能测试的时候，转化过的性能测试中的高级配置没有csv文件。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28363]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

1. 接口自动化场景中有含有csv文件的场景变量。
2. 一键转化成性能测试。
3. 转化过的性能测试中的高级配置里面没有csv文件。
![image](https://github.com/metersphere/metersphere/assets/33945037/aac9c72a-f78c-4bca-b589-59889f464815)
![image](https://github.com/metersphere/metersphere/assets/33945037/1463e8df-0b54-4295-bf1e-8d2ed0dcae03)
![image](https://github.com/metersphere/metersphere/assets/33945037/b43c335c-1b66-443c-b83e-3614e79745da)

### 重现步骤

同上

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.11已修复，请升级
