### ISSUE TITLE
[BUG] jmx 脚本中有jmeter自带的取样器【java请求】，再jmeter上能正常运行，放到ms上有报错，并且报错取样信息查看是空白的

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28366]
### MeterSphere 版本

2.10.10-lts

### 使用外置数据库

否

### 问题描述

1、jmx 脚本中有jmeter自带的取样器【java请求】，再jmeter上能正常运行，
2、放到ms上有报错，并且报错取样信息查看是空白的

### 重现步骤

1、jmx 脚本中有jmeter自带的取样器【java请求】，再jmeter上能正常运行，
2、放到ms上有报错，并且报错取样信息查看是空白的

![02c3d027e5aa2719b3f58b47c1ff0ce](https://github.com/metersphere/metersphere/assets/43202800/96ceffa5-c003-48f4-a959-775a846d1000)
![932d279dd04b7e85d347c7128dea6ab](https://github.com/metersphere/metersphere/assets/43202800/13aa2661-b1b1-434b-a57a-28b0cfc41efc)

### 期待的正确结果

应该正常运行才对，java取样信息希望查看详细结果

**Comment by 13290445582** [comment]
您好，已导入jmx文件，与jmeter显示情况一致，未发现异常，关闭issue，感谢理解与支持。
