### ISSUE TITLE
[FAETURE]【测试跟踪】功能用例的高级查询页面，打开加载很慢，希望能默认去掉，放到的下面的添加筛选条件里。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28379]
### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】功能用例的高级查询页面，打开加载很慢，高级查询页面-所属模块大概5000多个
希望能默认去掉，放到的下面的添加筛选条件里。

### 重现步骤

【测试跟踪】功能用例的高级查询页面，打开加载很慢，高级查询页面-所属模块大概5000多个
希望能默认去掉，放到的下面的添加筛选条件里。
![image](https://github.com/metersphere/metersphere/assets/104960608/d14cfddb-7b3e-42a0-b9d3-3e5850dd7842)

**Comment by Hyyfit** [comment]
v3 已规划
