### ISSUE TITLE
[BUG]接口测试-接口自动化，配置场景案例中的sql请求运行环境和数据源名称后，点击【保存】提示保存成功，关闭场景编辑页面，再次进入编辑该场景，前面已经配置好的sql请求的“数据源名称”会丢失！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2837]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
接口测试-接口自动化，配置场景案例中的sql请求运行环境和数据源名称后，点击【保存】提示保存成功，关闭场景编辑页面，再次进入编辑该场景，前面已经配置好的sql请求的“数据源名称”会丢失！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/118344333-44c23c00-b560-11eb-9d0f-c715a51ada7d.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xieziqiang** [comment]
@zyyfit 遇到同样的问题，请问当前有什么解决办法没

**Comment by zyyfit** [comment]
您好，1.10.0版本修改了环境匹配逻辑，变更整个场景环境的时候会判断新选的环境是否有sql环境，有的话使用新环境，数据源默认使用新环境中的第一个，没有的话还使用之前设置的环境，数据源不变

**Comment by zyyfit** [comment]
> @zyyfit 遇到同样的问题，请问当前有什么解决办法没

您好，1.10.0版本修改了环境匹配逻辑，变更整个场景环境的时候会判断新选的环境是否有sql环境，有的话使用新环境，数据源默认使用新环境中的第一个，没有的话还使用之前设置的环境，数据源不变。

目前的话暂时没有什么好的解决方法，变更环境后只能手动更新一下

**Comment by zyyfit** [comment]
1.10.0版本已发布，可升级版本
