### ISSUE TITLE
[BUG]【UI测试】本地调试可以正常登录进去，点击后端调试和生成报告，页面有提示不能正常登录。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28370]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

【UI测试】本地调试可以正常登录进去，点击后端调试和生成报告，页面有提示不能正常登录。

### 重现步骤

【UI测试】本地调试可以正常登录进去，点击后端调试和生成报告，页面有提示不能正常登录。
![image](https://github.com/metersphere/metersphere/assets/104960608/7d91a636-b173-4f00-9ba2-64e75894da35)

[Downloads.zip](https://github.com/metersphere/metersphere/files/13948378/Downloads.zip)

**Comment by liuruibin** [comment]
这个提示非常明显了已经

**Comment by 2lipan** [comment]
手动将后端selenium-hub升级到最新版本，浏览器是v120版本，手动上传证书文件，出现的问题一样，也是登录不进去。页面证书上传限制了application/x-x509-ca-cert格式，但是在linux版本的chrome浏览器上传时，没有将证书识别为application/x-x509-ca-cert格式，而是pkix.cert格式。
