### ISSUE TITLE
一键部署时，system-setting报错

### ISSUE THREAD

**Issue by Wuqunqun** [metersphere/metersphere#28376]
### 请描述您的问题

![1212](https://github.com/metersphere/metersphere/assets/34914164/64d9dbb1-b5b7-4e7b-9acb-1c76ef52c02d)

**Comment by liuruibin** [comment]
https://metersphere.io/docs/v2.x/faq/installation/#8-usrlocalbinmsctl-line-115 你可以先按照这个文档进行操作

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
