### ISSUE TITLE
[BUG]用例评审-批量编辑 不写评论，在“评审历史”中没有评审结果

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#28382]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

用例评审-批量编辑 不写评论，在“评审历史”中没有评审结果，单独点进去编辑评审用例，不写评论会有评审结果

### 重现步骤

用例评审-批量编辑 不写评论，在“评审历史”中没有评审结果
![image](https://github.com/metersphere/metersphere/assets/103627487/db8eaaf9-750c-45ee-bd1d-b37cc65b61fd)
![image](https://github.com/metersphere/metersphere/assets/103627487/89e8be53-0d04-44ff-9bbd-8fca65d69add)

### 期待的正确结果

用例评审-批量编辑 不写评论，在“评审历史”中也有评审结果，同单独点进去编辑评审用例逻辑一样（不写评论也会有评审结果）

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by Hyyfit** [comment]
v3已覆盖该缺陷，请关注后续版本发布；
