### ISSUE TITLE
[BUG]项目B 场景导入，复制项目A的场景案例进来后，项目B中的运行环境无法切换，显示的是场景A的运行环境

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2838]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
项目B 场景导入，复制项目A的场景案例进来后，项目B中的运行环境无法切换，显示的是场景A的运行环境
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，本项目引用或复制其他项目的场景，选择环境时只能选择被引用项目的环境，但是可以切换被引用项目中的其他环境
