### ISSUE TITLE
[FEATURE] 禅道缺陷模板期望也像 jira一样可以使用模板，目前发现 禅道这个模板只能每个项目配一个，有多个项目使用要配置多次，也没有全局模板，使用很麻烦

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28391]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

禅道缺陷模板期望也像 jira一样可以使用模板，目前发现 禅道这个模板只能每个项目配一个，有多个项目使用要配置多次，也没有全局模板，使用很麻烦

### 请描述你建议的实现方案

禅道缺陷模板期望也像 jira一样可以使用模板

**Comment by Hyyfit** [comment]
v3 已规划。
