### ISSUE TITLE
[BUG]导出项目A的场景列表（MeterSphere格式）至本地，打开项目B，导入从项目A导出的json文件至项目B后，运行环境也无法切换，显示的是项目A的运行环境

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2839]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
导出项目A的场景列表（MeterSphere格式）至本地，打开项目B，导入从项目A导出的json文件至项目B后，运行环境也无法切换，显示的是项目A的运行环境
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复这个问题

**Comment by zyyfit** [comment]
1.10.0版本已修复，目前最新版是1.10.3，请升级使用
