### ISSUE TITLE
[FEATURE] 使用优化：用户组与权限设置，个人信息-配置第三方账号勾选了菜单，但是无法显示出来。发现需要勾选服务集成-查询才显示，这里逻辑是这样但是没有提示，使用体验不太好”所见非所得“

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28390]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

使用优化：用户组与权限设置，个人信息-配置第三方账号勾选了菜单，但是无法显示出来。

发现需要勾选服务集成-查询才显示，这里逻辑是这样但是没有提示，使用体验不太好

### 请描述你建议的实现方案

期望，如果能加个提示或者菜单联动勾选就好了
试错成本比较多

**Comment by xhy12** [comment]
![23f7ca3c1dc7f7296f7755639b6577f](https://github.com/metersphere/metersphere/assets/43202800/e87cd1b0-1a8f-4be7-a78c-17ee56cc607d)

**Comment by luty2018** [comment]
配置第三方信息时，需要查询用户所在项目绑定了哪些第三方项目， 以此来展示可以录入的平台。接口上是这么给的权限， v2先保持现状，v3已改。
