### ISSUE TITLE
minio报错，很多报错跟minio有关，看了下minio容器，报错如下

### ISSUE THREAD

**Issue by Wuqunqun** [metersphere/metersphere#28395]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/34914164/98e003fe-9485-4fd3-b4c7-771035fbb270)

**Comment by liuruibin** [comment]
你可以先回退到 RELEASE.2023-04-13T03-08-07Z
https://github.com/minio/minio/issues/18365

minio从2023年11月1日起，区分了老版本的cpuv1，需要专门指定这个tag才能使用最新版，我们在下次发布中回退到之前使用的版本，v2版本不再进行更新。

**Comment by Wuqunqun** [comment]
> 你可以先回退到 RELEASE.2023-04-13T03-08-07Z [minio/minio#18365](https://github.com/minio/minio/issues/18365)
> 
> minio从2023年11月1日起，区分了老版本的cpuv1，需要专门指定这个tag才能使用最新版，我们在下次发布中回退到之前使用的版本，v2版本不再进行更新。

具体是如何回退，具体步骤是啥

**Comment by liuruibin** [comment]
修改 /opt/metersphere/docker-compose-minio.yml
<img width="720" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/0500c3d4-e07b-4f61-81f3-0228d62381df">
将这里改成RELEASE.2023-04-13T03-08-07Z，保存后执行 msctl reload
