### ISSUE TITLE
[BUG]系统设置-环境配置 列表 列字段“项目”筛选功能，无法按关键字搜索，项目很多，无法快速查找到项目进项过滤（ps：顶部的快速搜索框无法按关键字搜索到结果集）

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2840]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
系统设置-环境配置 列表 列字段“项目”筛选功能，无法按关键字搜索，项目很多，无法快速查找到项目进项过滤（ps：顶部的快速搜索框无法按关键字搜索到结果集）
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
目前只支持根据环境名称筛选，后面可以优化下
