### ISSUE TITLE
[BUG]测试计划保存的运行环境为A，添加接口场景用例后，用例的运行环境是默认环境B，而不是A

### ISSUE THREAD

**Issue by 157571062297** [metersphere/metersphere#28409]
### 联系方式

1849828250@qq.com

### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

测试计划保存的运行环境为A，添加接口场景用例后，用例的运行环境是默认环境B，而不是A

### 重现步骤

测试计划保存的运行环境为A，添加接口场景用例后，用例的运行环境是默认环境B，而不是A

### 期待的正确结果

添加场景用例，运行环境应该是测试计划保存的运行环境，而不是默认环境

### 附加信息

![30094d317d51b92c94de9f475b79944](https://github.com/metersphere/metersphere/assets/30097089/79077087-f45c-4495-85af-1bbdf225bf59)

**Comment by 13290445582** [comment]
您好，添加场景用例时，所选择默认环境为场景的默认环境，您保存测试计划环境后再关联场景，所以后续所添加的场景未使用您保存的环境。
