### ISSUE TITLE
[BUG] 在JSON-SCHEMA开启时编辑了高级设置字段，然后将JSON-SCHEMA关闭，高级字段属性丢失。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28404]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

在JSON-SCHEMA开启时编辑了高级设置字段，然后将JSON-SCHEMA关闭，编辑了下请求头信息，保存后会将高级设置里面的信息全部置空
 同：https://github.com/metersphere/metersphere/issues/19733    这个issues一样

### 重现步骤

1. 新增一个接口
2. 在JSON-SCHEMA开启时新增字段属性，编辑高级设置字段，保存接口信息
3. 然后将JSON-SCHEMA关闭，再打开，会发现高级属性丢失了。

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，切换 JSON 就是会丢失，JSON 和 Schema 公用一个存储；v3 分开存储解决的，v2 不处理了。
