### ISSUE TITLE
[BUG]用例执行，进入一个用例有缺陷或者新增缺陷后，关闭该用例，进入新用例，会展示前面那个用例的缺陷

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2841]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
用例执行，进入一个用例有缺陷或者新增缺陷后，关闭该用例，进入新用例，会展示前面那个用例的缺陷
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
已知问题，下个版本修复

**Comment by xulinde** [comment]
1.9.3已修复
