### ISSUE TITLE
[BUG]【接口测试】环境配置设置按启用条件匹配环境，在场景编辑页面执行单步骤，获取不到 host

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28419]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

项目配置按模块匹配环境，在场景中调试单步骤，用例获取不到 host,调试整个场景是可以获取到 host 的

### 重现步骤

1、环境配置设置按模块匹配环境
2、创建一个新场景
3、在场景中导入 API
4、调试 API

### 期待的正确结果

项目配置按模块匹配环境，在场景中调试单步骤，用例能获取到 host

### 附加信息

1、环境按模块匹配环境
![image](https://github.com/metersphere/metersphere/assets/45531073/49d36a85-3002-4de2-aca9-d82ce98de752)
2、调试单步骤匹配不到环境
![image](https://github.com/metersphere/metersphere/assets/45531073/25018986-68f9-4de1-be7c-700cadfe5052)
3、调试整个场景可以获取到环境
![image](https://github.com/metersphere/metersphere/assets/45531073/1ab0da2f-7721-4a8a-8086-5b51b1a689c4)

**Comment by 13290445582** [comment]
感谢反馈，计划于v2.10.11版本修复该问题。

**Comment by 13290445582** [comment]
v2.10.11已修复，请升级。
