### ISSUE TITLE
[BUG]  响应体jsonschema高级设置后无效，误导用户有效，尤其在mock响应体中

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28410]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

响应体jsonschema高级设置后无效，误导用户有效，尤其在mock响应体中

### 重现步骤

响应体jsonschema高级设置后无效，误导用户有效，尤其在mock响应体中
![image](https://github.com/metersphere/metersphere/assets/103925124/b5794e49-f564-4380-bab2-5b679b23e996)
响应体设置了但无用，也不会生成
![image](https://github.com/metersphere/metersphere/assets/103925124/7f1ace55-9f2e-4e5d-a7e4-3eeee5849db2)

在mock方法的响应体误导更为明显,以为mock方法能动态返回，但是设置了，执行mock方法时无效
![image](https://github.com/metersphere/metersphere/assets/103925124/2309cd58-2424-4338-b4f5-49aa13caff73)

![image](https://github.com/metersphere/metersphere/assets/103925124/a815b991-bba4-4e99-adfc-e9bfc9726844)

**Comment by 13290445582** [comment]
感谢反馈，暂不支持如此使用，在v2版本不再修改这里了，不影响使用其他功能，感谢理解。
