### ISSUE TITLE
[FEATURE]测试计划关联的用例建议增加一个开关

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#28420]
### MeterSphere 版本

v2.x

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

目前计划里关联的用例都会执行，部分客户希望可以在计划内给每个用例增加一个启用禁用的开关，某次执行计划不需要执行某些用例时，就通过关闭开关实现跳过某些用例执行。

**Comment by luty2018** [comment]
目的是什么呢 ，这样也会影响测试计划的通过率。v3会支持测试计划组， 把需要执行的用例可以单独放一个计划里。

**Comment by linfengjjj** [comment]
有些用例在某次计划中不需要执行，后续可能又需要执行。如果没有开关，经常需要手动取消关联和再次关联，十分不便，增加开关更灵活，可以把关闭的不纳入通过率计算中。

**Comment by luty2018** [comment]
这个不是通用场景，不会支持。
