### ISSUE TITLE
UI测试模块后台未开启时，在测试计划里点击关联UI用例时前端报错

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#28428]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

当后端UI测试模块未开启时，创建一个测试计划，点击关联UI用例时，前端页面报错，希望隐藏掉UI用例，或者置灰。

### 重现步骤

1.准备一个MeterSphere2.10.10的环境，不启动UI模块
2.创建一个测试计划
3.进入测试计划点击UI用例
<img width="1379" alt="截屏2024-01-19 下午3 06 29" src="https://github.com/metersphere/metersphere/assets/34637801/b14718bd-26bc-45a1-b925-c6c1aaa62ece">

### 期待的正确结果

建议当UI模块未启动时，隐藏掉测试计划里的UI用例的选项，或者置灰

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本优化。
