### ISSUE TITLE
【BUG】性能测试用例删除JTL文件后，无法删除对应性能测试用例的报告

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#28426]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

性能测试用例删除JTL文件后，删除对应的性能测试报告时报500的错误。

### 重现步骤

1.准备一个性能测试用例
2.执行一次性能测试用例
3.删除对应的JTL文件
<img width="1271" alt="截屏2024-01-19 下午2 42 27" src="https://github.com/metersphere/metersphere/assets/34637801/6bb05815-1947-43cb-9846-bae9d0c066c4">
4.删除对应的性能测试用例报告
<img width="1283" alt="截屏2024-01-19 下午2 43 23" src="https://github.com/metersphere/metersphere/assets/34637801/d70b32c3-1c40-49bf-b7f3-65b42ff7e28c">

### 期待的正确结果

能正常删除对应性能测试用例报告

**Comment by youliyuan-fit2cloud** [comment]
这个jtl和该性能测试用例有什么关系？
执行该用例的时候没有用这个文件，截图1 显示的文件是 文件管理里面的所有文体。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，开源版本问题，默认资源池的后置监听器打开了，企业版没有该问题。

**Comment by youliyuan-fit2cloud** [comment]
较新的版本中不再生成JTL文件。
