### ISSUE TITLE
[BUG]【UI测试】同时打开引用场景和原场景，新增原场景的后置操作，刷新引用场景后，来回切换步骤，发现新增的后置操作不显示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28424]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

【UI测试】同时打开引用场景和原场景，新增原场景的后置操作，刷新引用场景后，来回切换步骤，发现新增的后置操作不显示。

### 重现步骤

【UI测试】在场景A里引用登录场景，同时打开场景A和登录场景，在登录场景后置操作新增截图和后置脚本，然后切到场景A，点击刷新按钮，可以看到原场景新增的后置操作被带过来了，但是来回切换下面步骤，发现原先的后置操作就不见了。
![image](https://github.com/metersphere/metersphere/assets/104960608/18f15353-b990-4c9e-a3ff-5958f47bff52)
![image](https://github.com/metersphere/metersphere/assets/104960608/96f163a1-3889-464a-a51b-6e4f0d6f3274)
![image](https://github.com/metersphere/metersphere/assets/104960608/ffaa560c-9a9c-47e0-ad4c-580d6b0603df)
![image](https://github.com/metersphere/metersphere/assets/104960608/07913650-3fdc-483a-8aa9-8a90fec57f04)

[Metersphere_Ui_共享平台-组装式应用平台.zip](https://github.com/metersphere/metersphere/files/13984736/Metersphere_Ui_.-.zip)

**Comment by 13290445582** [comment]
感谢反馈，计划于后续版本修复该问题。

**Comment by 13290445582** [comment]
引用tab 和原tab切换数据有缓存不及时更新问题，目前可规避方法是，关闭引用tab，再次打开就可以了.

**Comment by 2lipan** [comment]
使用关闭再打开，可以暂时的规避，但是无必要操作，繁琐且麻烦。

**Comment by 13290445582** [comment]
你好，目前得到的解决方案就是暂时规避此问题，UI部分能尽量少改动就尽量少改动，感谢理解。
