### ISSUE TITLE
[BUG]项目的环境配置删除后，该项目中已有的场景案例运行环境会被清空，重新维护好环境配置后，修改场景案例的运行环境，进行保存，系统会提示该场景的自定义ID已存在。

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2842]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.9.2-98b64776
**Bug 描述**
简要描述您碰到的问题
项目的环境配置删除后，该项目中已有的场景案例运行环境会被清空，重新维护好环境配置后，修改场景案例的运行环境，进行保存，系统会提示该场景的自定义ID已存在。
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是必现的吗？这边没有复现，能描述一下详细操作步骤吗

**Comment by zyyfit** [comment]
您好，是必现的吗？这边没有复现，能描述一下详细操作步骤吗
