### ISSUE TITLE
场景变量中使用CSV文件，转成性能用例后，修改场景用例步骤，在对应性能用例点击同步操作，CSV文件会丢失

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#28429]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

在一个场景中，场景变量中使用CSV文件，转成性能用例后，修改场景用例步骤，在对应性能用例点击同步操作，CSV文件会丢失，在性能测试用例里“资源文件”里找不到，导致CSV文件无法加载到性能测试用列中。

### 重现步骤

1.准备一个场景用例，并在场景变量中上传一个CSV文件
2.将场景用例转成性能用例
<img width="1272" alt="截屏2024-01-19 下午3 14 54" src="https://github.com/metersphere/metersphere/assets/34637801/dce39b3a-d1d4-4144-b569-cb9fea91fc47">
3.修改场景用例里的步骤
4.点击性能用例里的“同步”功能
<img width="1285" alt="截屏2024-01-19 下午3 16 22" src="https://github.com/metersphere/metersphere/assets/34637801/3bb4d4e5-b508-4707-8833-037504f9f88a">
5.可看到CSV文件丢失了
<img width="1383" alt="截屏2024-01-19 下午3 17 03" src="https://github.com/metersphere/metersphere/assets/34637801/68bd7286-7a05-4ee2-bf39-bb3ee1f82fed">

### 期待的正确结果

希望同步后CSV文件不会丢失

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请问下场景用例怎么修改的？

**Comment by pengzhengyou** [comment]
比如增加一个自定义请求

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后置监听器开启时存在该问题，开源版本中会遇到，后续版本解决。

**Comment by youliyuan-fit2cloud** [comment]
该问题在最新版本中已解决
