### ISSUE TITLE
[BUG] 在性能测试报告中，“测试详情” 中的响应百分比的值跟请求统计中的值不一致，并且为0

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28423]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

在性能测试报告中，“测试详情” 中的“响应百分比”的值跟请求统计中的值不一致，并且为0。其中最大值和最小值的平均值跟请求统计中的值也不一致。
<img width="1197" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/e659b72b-493d-4545-8176-03aa9e17f995">
<img width="1241" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/cb0215a8-0041-4e80-9cd8-0e866b93b405">

### 重现步骤

1. 随便一个接口做性能测试
2. 分析报告，在测试详情中展示“响应百分比”中的值，右边折线图的下方即可看到数据

<img width="1285" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/b689ad7c-4ed8-460b-a11a-b94d926ae141">

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/20466
