### ISSUE TITLE
[BUG]【UI测试】同时打开引用场景和原场景，修改原场景的URL后，点击引用场景的刷新按钮，发现引用场景里的URL并没有改变，还是之前的。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28425]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

【UI测试】场景A引用了登录场景，同时打开这两个场景，修改登录场景的URL后，点击场景A的刷新按钮，发现场景A里的URL并没有改变，还是之前的。

### 重现步骤

【UI测试】场景A引用了登录场景，同时打开这两个场景，修改登录场景的URL后，点击场景A的刷新按钮，发现场景A里的URL并没有改变，还是之前的。
![image](https://github.com/metersphere/metersphere/assets/104960608/e6597b6a-8c59-42fe-8d93-fbfc2054ffe1)
![image](https://github.com/metersphere/metersphere/assets/104960608/c6ba66c7-7e37-4063-818b-78b071cbdf2f)

[Metersphere_Ui_lipan (3).zip](https://github.com/metersphere/metersphere/files/13984829/Metersphere_Ui_lipan.3.zip)

**Comment by 13290445582** [comment]
感谢反馈，计划于后续版本修复该问题。

**Comment by 13290445582** [comment]
引用tab 和原tab切换数据有缓存不及时更新问题，目前可规避方法是，关闭引用tab，再次打开就可以了

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
