### ISSUE TITLE
[BUG]无法支持文件上传的接口请求

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2843]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
因请求头会默认以“Content-Type: application/json;charset=UTF-8”传递的问题，文件上传的接口请求失败，无法按文件上传接口请求中设置的“multipart/form-data”进行传递，导致文件上传接口失败！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/118344599-90c1b080-b561-11eb-9472-6f23d054da2d.png)

![image](https://user-images.githubusercontent.com/54024064/118344620-ad5de880-b561-11eb-8ffe-7f26bbaeef55.png)

**Comment by xulinde** [comment]
只上传文件，默认是不会带application/json请求头的，您检查下是否有传请求参数

**Comment by feiyu0316** [comment]
> 只上传文件，默认是不会带application/json请求头的，您检查下是否有传请求参数

这个问题是确认的，平台研发人员已经远程支持排查过了，确认为是bug！

**Comment by zyyfit** [comment]
您好，最新版1.10.3版本未复现这个问题，请升级到最新版查看一下
![image](https://user-images.githubusercontent.com/73461316/123674297-082e7380-d874-11eb-98e6-3b5a9426adea.png)
