### ISSUE TITLE
[BUG] 升级2.10.10之后，总是会出现 Connection prematurely closed BEFORE response，每次报错不一样，

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28448]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

升级2.10.10之后，总是会出现 Connection prematurely closed BEFORE response，每次报错不一样

使用性能测试总是出现报错

### 重现步骤

客户那边出现，本地无法复现

修改了参数，调大gateway 超时时间不生效，spring.cloud.gateway.httpclient.connect-timeout=300000 

看了网上帖子，需要程序上修改一些配置，请研发看看 https://blog.csdn.net/lihaipeng0417/article/details/113768398

每次报错 url不一样

![3477211d9380502eb7e2b7ce5daa386](https://github.com/metersphere/metersphere/assets/43202800/d0aacbef-2467-485d-b2f5-d5854bda7f89)
![f8f1dc786d34af324a575564ef626e5](https://github.com/metersphere/metersphere/assets/43202800/4cf9be9a-7c65-4f3e-81ce-b6464a6efcda)

**Comment by liuruibin** [comment]
已知问题，暂时没找到合适的方案，会持续调研跟进。

**Comment by liuruibin** [comment]
我先将这个issue关闭，如果后续三方组件修复了这里我们也会随之升级
