### ISSUE TITLE
[FEATURE]  MeterSphere的 IDEA 插件版本不兼容（idea 2023.3.2+）

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28446]
### MeterSphere 版本

idea 版本 2023.3.2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/33945037/e6e8383b-4716-47a9-938a-f8031058f603)

![image](https://github.com/metersphere/metersphere/assets/33945037/3fcc2b21-e808-4781-9256-25a5ebaee2fc)

插件版本希望可以兼容idea 高版本的

### 重现步骤

插件下载：https://plugins.jetbrains.com/plugin/18097-metersphere/versions/stable

在idea 2023.3.2 版本以上就没办法安装。

**Comment by fit2-zhao** [comment]
感谢反馈，插件v1.2.6 仅支持最新IDEA为 231版本；您可以使用插件源码自行编译一个兼容版，我们会在下一个版本发布兼容最新版本IDEA的插件。

源码仓库地址：https://github.com/metersphere/metersphere-idea-plugin
