### ISSUE TITLE
[BUG]【测试跟踪】MeterSphere 切换到英文模式导出功能用例，有部分字段内容未导出

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28445]
### MeterSphere 版本

v2.10.10

### 使用外置数据库

否

### 问题描述

MeterSphere 切换到英文模式导出功能用例,有部分字段内容未导出来，中文模式是正常的

### 重现步骤

1、切换到英文模式，创建功能用例
2、在英文模式下，导出功能用例

### 期待的正确结果

在英文模式下，能将所有内容导出

### 附加信息

同一个用例导出：
1、英文模式导出用例
![image](https://github.com/metersphere/metersphere/assets/45531073/eacfd5ee-88d9-467c-ab0d-1f4aa550b7c6)
2、中文模式导出用例
![image](https://github.com/metersphere/metersphere/assets/45531073/23c6fe22-0af7-456e-ab85-17c7d311df18)

**Comment by 13290445582** [comment]
您好，暂未复现该issue，原环境目前也无法复现，后续有问题请继续反馈。

**Comment by 13290445582** [comment]
您好，暂时无法复现该问题，后续会持续关注，关闭该issue，感谢理解与支持。
