### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#2845]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
上传的测试脚本中带有 setup 和 teardown 线程组和事务时，创建性能测试后，场景列表为空无法执行性能测试
**Bug 重现步骤**
1.  使用jmeter创建带有有 setup 和 teardown 线程组的脚本，线程组下级要有事务。
2. 在接口自动化模块导入jmx脚本。
3. 导入成功后，在场景列表中选择该场景创建性能测试
4. 创建后场景列表为空无法执行性能测试

**期待的正确结果**
正确情况下应该是什么样的？
创建性能测试后，场景列表中应有场景，并能正常执行性能测试。
**截图**
如果有截图，请附上截图.
<img width="894" alt="333" src="https://user-images.githubusercontent.com/83771182/118396394-f86f1d00-b681-11eb-823f-5c8b707cc17f.png">

**Comment by zyyfit** [comment]
您好，1.9.2版本可以执行带有 setup 和 teardown 线程组的测试，请升级后试一下
