### ISSUE TITLE
[BUG]  在场景编辑页面执行单步骤，获取不到 host，保存场景后，api报不存在，导致调试也取不到http配置，场景执行不了，影响全部场景用例【重要影响大】

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28463]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

在场景编辑页面执行单步骤，获取不到 host，保存场景后，api报不存在，导致调试也取不到http配置，场景执行不了，影响全部场景用例【重要影响大】

### 重现步骤

在场景编辑页面执行单步骤，获取不到 host，保存场景后，api报不存在，导致调试也取不到http配置，场景执行不了，影响全部场景用例，客户没有启动条件为无的http配置。
![image](https://github.com/metersphere/metersphere/assets/103925124/758ba1ff-7b5e-4292-b2fa-8fd6753135c0)
![image](https://github.com/metersphere/metersphere/assets/103925124/cc22bb14-deba-42cc-9749-3558b28bb810)

**Comment by fit2cloud-yaochunrong** [comment]
[https://github.com/metersphere/metersphere/issues/28419](url)  看下是否需要关联此缺陷

**Comment by youliyuan-fit2cloud** [comment]
> [https://github.com/metersphere/metersphere/issues/28419](url) 看下是否需要关联此缺陷

同一个问题，已修复待发布后验证。
