### ISSUE TITLE
[BUG] IDE插件无法安装在233版本的IDE上

### ISSUE THREAD

**Issue by huskiesir** [metersphere/metersphere#28468]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

233版本的IDE无法安装最新的1.2.6IDE插件
![image](https://github.com/metersphere/metersphere/assets/45967454/4612d3f5-4eae-4ab4-bf57-ba0e9da520d0)
<img width="1475" alt="image" src="https://github.com/metersphere/metersphere/assets/45967454/c747161c-5a44-46b7-a4dc-fa33065e517e">

### 重现步骤

在233IDE上安装最新的metersphere IDE插件（1.2.6目前最新），可以复现问题

**Comment by fit2-zhao** [comment]
感谢反馈，插件v1.2.6 仅支持最新IDEA为 231版本；您可以使用插件源码自行编译一个兼容版，我们会在下一个版本发布兼容最新版本IDEA的插件。

源码仓库地址：https://github.com/metersphere/metersphere-idea-plugin

**Comment by huskiesir** [comment]
> 感谢反馈，插件v1.2.6 仅支持最新IDEA为 231版本；您可以使用插件源码自行编译一个兼容版，我们会在下一个版本发布兼容最新版本IDEA的插件。
> 
> 源码仓库地址：https://github.com/metersphere/metersphere-idea-plugin

下个版本什么时候
