### ISSUE TITLE
[BUG]version=1.9.2,sql环境配置后，点击确定，报错

### ISSUE THREAD

**Issue by youngkevin1** [metersphere/metersphere#2847]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
sql环境配置后，点击确定，报错
**Bug 重现步骤**
{"success":false,"message":"Failed to parse multipart servlet request; nested exception is javax.servlet.ServletException: Unsupported Content-Type [application/json;charset=UTF-8], expected [multipart/form-data]","data":null}

**期待的正确结果**
正确情况下应该是什么样的？
从返回的错误信息看应该是该接口/api/environment/update  content-type应该使用表单传递，现在使用得json格式导致
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/56627749/118422117-2f324b00-b6f5-11eb-9b7a-1e833af1d872.png)

**Comment by youngkevin1** [comment]
还请确认！

**Comment by zyyfit** [comment]
您好，是在sql请求中添加的环境信息吗？如果是的话则是已知问题，会在后续版本修复，不是的话请详细描述一下复现步骤

**Comment by youngkevin1** [comment]
是的&nbsp; 环境的db配置的确定按钮会触发该异常，具体有修复时间么，这个sql的功能还是蛮常用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月18日(星期二) 晚上11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]version=1.9.2,sql环境配置后，点击确定，报错 (#2847)





 
您好，是在sql请求中添加的环境信息吗？如果是的话则是已知问题，会在后续版本修复，不是的话请详细描述一下复现步骤

**Comment by zyyfit** [comment]
> 是的&nbsp; 环境的db配置的确定按钮会触发该异常，具体有修复时间么，这个sql的功能还是蛮常用的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年5月18日(星期二) 晚上11:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]version=1.9.2,sql环境配置后，点击确定，报错 (#2847) 您好，是在sql请求中添加的环境信息吗？如果是的话则是已知问题，会在后续版本修复，不是的话请详细描述一下复现步骤 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

1.10.0版本已修复，目前最新版是1.10.3，请升级使用
