### ISSUE TITLE
[QUESTION]一键部署dependency failed to start: container system-setting is unhealthy

### ISSUE THREAD

**Issue by zhangmc** [metersphere/metersphere#28482]
### 请描述您的问题

Container system-setting Error
Container system-setting Error
Container system-setting Error
Container system-setting Error
Container system-setting Error
Container system-setting Error
dependency failed to start: container system-setting is unhealthy

使用一键部署最后出现以上问题，目前登录后工作台页面为空，只能看到UI测试和系统设置两个功能模块，
麻烦帮忙看看是什么问题，谢谢

system-setting/error.log 
![system-settingerror log](https://github.com/metersphere/metersphere/assets/7735737/d29a15b4-6b63-4fa7-b909-d716c638d2c9)

容器日志，没有报错，只有警告信息
![containlog](https://github.com/metersphere/metersphere/assets/7735737/7dd304e2-0a4a-40b1-96fb-bb30b4ba36b5)

status
![MSCTL](https://github.com/metersphere/metersphere/assets/7735737/96f06665-fe05-4df8-adab-116ad296765d)

**Comment by liuruibin** [comment]
仅成功启动了一个服务，重新执行安装试试

**Comment by zhangmc** [comment]
已解决，谢谢
