### ISSUE TITLE
[BUG] 通过swagger 导出的.json文件 导入生成接口api提示解析错误

### ISSUE THREAD

**Issue by waitingSunset** [metersphere/metersphere#28492]
### 联系方式

18356090979

### MeterSphere 版本

v2.10.x-lts 

### 使用外置数据库

是

### 问题描述

将swagger2.0生成的.json文件, 导入到接口时, 提示文件解析错误
<img width="786" alt="WechatIMG95" src="https://github.com/metersphere/metersphere/assets/96096525/5d83d8ff-7094-4638-835e-7865967fbcc6">

### 重现步骤

将swagger2.0生成的.json文件, 导入到接口时, 提示文件解析错误

**Comment by 13290445582** [comment]
您好，导入swagger2.0文件未遇到该情况，请提供下您的swagger文件。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
