### ISSUE TITLE
[BUG] 后置脚本给其他环境设置的环境参数，无法获取到

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#28494]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

想实现跨环境引用变量，后置脚本通过 vars.put("MS.ENV.3ec6e8c8-9aff-4638-b2e1-a0ae9a2213c1.token_fa", vars.get("csrfToken"));  给项目其他环境设置变量，之后通过 vars.get("MS.ENV.3ec6e8c8-9aff-4638-b2e1-a0ae9a2213c1.token_fa") 无法获取到

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103627487/d55e7861-ed07-457f-9355-04e6933a7de1)
通过脚本已经设置上
![image](https://github.com/metersphere/metersphere/assets/103627487/a053b76e-1ec1-4ad3-a1c2-5ef2cebcb4b8)
其他场景获取不到
![image](https://github.com/metersphere/metersphere/assets/103627487/3b5737d0-29be-46a1-a681-5feedc0eaa8f)

### 期待的正确结果

希望能通过这种方式存进去也能获取到

**Comment by 13290445582** [comment]
您好，不支持这样使用，不在同一个场景的上下文中是获取不到这个变量值的，跨环境去获取变量值是不支持的，感谢理解。
