### ISSUE TITLE
[BUG]后置脚本（python）a,b=1,2 赋值场景中，如果，写成了中文字符，不能正确报错

### ISSUE THREAD

**Issue by huahuablue** [metersphere/metersphere#28490]
### 联系方式

huahuablue@aliyun.com

### MeterSphere 版本

v2.10.8-lts-313def9d

### 使用外置数据库

是

### 问题描述

接口后置脚本中，中文字符，运行接口不会执行新的修改，执行结果也不更新。控制台也不报错

### 重现步骤

1.随便一个get 接口
2.添加后置脚本， a，b=1,2，其中a，b之间的逗号使用中文字符
![image](https://github.com/metersphere/metersphere/assets/61490106/f9bd7a85-7746-4080-b343-de77b1e67203)
3.再次执行接口，接口未正确执行。结果和参数都是展示之前的结果。控制台也不报错
4.只要不修改脚本错误的地方。随便怎么修改接口其他参数，均无法再次成功执行接口

### 期待的正确结果

控制台正确报错

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by luty2018** [comment]
![image](https://github.com/metersphere/metersphere/assets/36292514/5072f325-c6b2-41e0-9ee4-ef35eaa39e6f)
建议升级到v3，升级了脚本编辑器，语法错误会及时提醒。
