### ISSUE TITLE
[BUG]【环境管理】根据模块设置的环境导出后，将原先环境ip修改后再进行导入，发现环境后面对应的值不显示，需要手动点击才会显示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28498]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【环境管理】根据模块设置的环境导出后，将原先环境ip修改后再进行导入，发现环境后面对应的值不显示，需要手动点击才会显示。

### 重现步骤

【环境管理】根据模块设置的环境导出后，将原先环境ip修改后再进行导入，发现环境后面对应的值不显示，需要手动点击才会显示。
![image](https://github.com/metersphere/metersphere/assets/104960608/3aee1527-253f-4c1e-8a07-00e630cafb86)
![image](https://github.com/metersphere/metersphere/assets/104960608/2c08a284-3ee0-48ea-a3d2-24ca035cd8e1)
![image](https://github.com/metersphere/metersphere/assets/104960608/3511508d-c1cf-47fc-aac4-714c5c2dad46)

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by Hyyfit** [comment]
v3已覆盖该缺陷，请关注后续版本发布；
