### ISSUE TITLE
[BUG]性能测试-并发用户数设置修改后不生效

### ISSUE THREAD

**Issue by fangteng999** [metersphere/metersphere#28493]
### 联系方式

10583848@qq.com

### MeterSphere 版本

2.10

### 使用外置数据库

是

### 问题描述

性能测试-并发用户数设置最大为50，在系统设置修改配额后，未生效，依旧并发用户数设置最大为50

### 重现步骤

性能测试-并发用户数设置最大为50，在系统设置修改配额后，未生效，依旧并发用户数设置最大为50

### 期待的正确结果

性能测试-并发用户数能够正确使用配置

**Comment by 13290445582** [comment]
<img width="630" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/417b211f-0d13-4dde-b774-9c63864062b4">
您好，请问描述的修改配额后，并发用户数设置依旧为50指的是这里吗？修改配额不会自动将这里的数值更改，这里需要手动修改，不过超出配额限制时执行会失败报错提示。
<img width="1015" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/9eccc40f-8f2d-4bfc-a34d-8f4fffa5ba60">

**Comment by fangteng999** [comment]
是这个地方的并发用户数，默认的是50，修改配额后，并发用户数还是只能设置到50，不能增加
![image](https://github.com/metersphere/metersphere/assets/35520550/a0f0ef02-a7d4-4a53-aa9d-92949da718e4)

**Comment by 13290445582** [comment]
![image](https://github.com/metersphere/metersphere/assets/128017892/526be7b1-85b1-45c7-92c3-005ada2329c9)
您好，请检查该性能测试所使用的资源池设置的最大并发数，可调大这里的最大并发数。

**Comment by fangteng999** [comment]
好的，谢谢
