### ISSUE TITLE
[BUG]接口自动化，创建一个新项目，然后把旧项目的环境及脚本导出，再导入新项目，sql脚本里面 选择的 数据源 关系没有保留

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28503]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

接口自动化，创建一个新项目，然后把旧项目的环境及脚本导出，再导入新项目，sql脚本里面 选择的数据库 关系没有保留

### 重现步骤

1、接口自动化，创建一个新项目，然后把旧项目的环境及接口自动化脚本导出，——接口自动化脚本包含了sql脚本，且sql脚本使用的库在数据库列表配置了多个。选择的不是第一个数据源

2、再导入新项目，sql脚本里面 选择的数据库 关系没有保留

操作有录屏

![重新选择环境，默认是第一个环境](https://github.com/metersphere/metersphere/assets/43202800/81348e2b-55c2-4960-ad7e-7d66a6908beb)

### 期待的正确结果

验证了旧版本，sql脚本保留 选择的数据源关系

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/0f1c20af-01f5-4009-9b01-ecfedf630e60)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
经研发反馈暂不支持这种情况，感谢理解和支持。
