### ISSUE TITLE
[BUG]【测试跟踪】测试计划，列表用例排序后，思维导图的顺序展示不一致，不方便执行

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2851]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
列表排序，与思维导图一致

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118425841-9bfd1380-b6fc-11eb-831a-262f39e4a8cf.png)

![image](https://user-images.githubusercontent.com/11580681/118425829-91db1500-b6fc-11eb-9d7d-0012f5746bbe.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本优化这个问题

**Comment by zyyfit** [comment]
1.13.0已修复
