### ISSUE TITLE
[BUG]【测试跟踪】1. 测试计划-测试用例，测试用例列表排序后，切换到思维导图，再切换回列表，用例顺序回被重置；2. 脑图和列表的用例优先级，颜色不一致（预期：保持颜色一致）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2852]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2 

**Bug 描述**
简要描述您碰到的问题
1. 测试计划-测试用例，测试用例列表排序后，切换到思维导图，再切换回列表，用例顺序回被重置；
2. 脑图和列表的用例优先级，颜色不一致（预期：保持颜色一致）

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
 1. 排序保持一致，不会被重置
 2. 颜色保持一致，便与区分

**截图**
如果有截图，请附上截图.

问题 2：
![image](https://user-images.githubusercontent.com/11580681/118426718-50e40000-b6fe-11eb-9ffc-85159ee91e15.png)

![image](https://user-images.githubusercontent.com/11580681/118426643-2f831400-b6fe-11eb-8208-b441ebd44b62.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本优化这个问题
