### ISSUE TITLE
[BUG] 环境配置_拖动左边的环境列表环境名称依然展示不全

### ISSUE THREAD

**Issue by dasandeyu** [metersphere/metersphere#2853]
**MeterSphere 版本**
v1.9.1-2cb10c1e

**Bug 描述**
环境配置_拖动左边的环境列表环境名称依然展示不全

**Bug 重现步骤**
https://user-images.githubusercontent.com/13783632/118426789-7a9d2700-b6fe-11eb-95df-4e2c32683485.mp4

**期待的正确结果**
向右拖动，应该展示完整的环境名称。

**截图**
无

**Comment by xulinde** [comment]
感谢反馈，后面版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
