### ISSUE TITLE
[BUG]接口场景勾选单条用例导入，提示为导入全部

### ISSUE THREAD

**Issue by lakuite** [metersphere/metersphere#28538]
### MeterSphere 版本

v1.20.23

### 使用外置数据库

否

### 问题描述

接口自动化，在场景中复制/引用用例时，只勾选了1条用例，但却提示选择了所有用例
![image](https://github.com/metersphere/metersphere/assets/49950902/b245e5ac-5a02-4c8a-8dd0-54247ff45901)
点击确定后控制台有报错，不过实际是只导入了选择的那1条用例
![image](https://github.com/metersphere/metersphere/assets/49950902/28421e9e-0faf-41e1-b2d0-a8d37e5c0a75)

### 重现步骤

1.接口测试-接口自动化，新建场景
2.复制/导入接口用例，选择1条，点击按钮
3.弹出提示框“当前选择请求数 [xxx] 个可能导致页面加载异常，是否继续？”

怀疑是否跟用例总数有关，实际使用时别的项目空间都没有这个提示弹框，只有这个项目有，用例超500了

### 期待的正确结果

导入时并未勾选过多的用例，不应弹出提示框

**Comment by 13290445582** [comment]
您好，v1.20-lts版本，目前仅进行必要的安全类 Bug 修复和严重 Bug 修复，建议您升级至最新版本v2.10.11使用，感谢您的理解与支持。
