### ISSUE TITLE
[BUG]  接口自动化，编辑场景 sql请求 切换同名数据源，能够生效，保存后关闭，再次进入页面切换环境的数据源，同名数据源没有切换过去

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28534]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

接口自动化，编辑场景 sql请求 切换同名数据源，能够生效，保存后关闭，再次进入页面切换环境的数据源，同名数据源没有切换过去

### 重现步骤

前置条件：接口测场景里面，有多个场景且有多个sql请求
同一个脚本需要切换不同环境，数据源配置是同名的

1、编辑场景 sql请求 切换同名数据源，能够生效，保存后关闭
2|再次进入页面切换环境的数据源，同名数据源没有切换过去【有录屏】
![关闭后再进入，切换数据源，不是之前保存的的值默认变成 了第一个](https://github.com/metersphere/metersphere/assets/43202800/01c485be-a82e-4301-885a-c53227f3cde3)

手动维护困难，很影响使用，

### 期待的正确结果

切换环境保留同名数据源配置

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.12已修复，请升级测试。
