### ISSUE TITLE
[BUG]【测试跟踪】测试计划，测试用例执行时，步骤阴影太重，看不清（建议增加对比度，提高清晰，便与阅读）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2854]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/118426872-a28c8a80-b6fe-11eb-8c45-bd2da8896008.png)

**Comment by xulinde** [comment]
1.9.2优化成这样了
![image](https://user-images.githubusercontent.com/64065190/118471258-231cac80-b73a-11eb-9a07-bcf6091378f8.png)

**Comment by jhong123** [comment]
> 1.9.2优化成这样了
> ![image](https://user-images.githubusercontent.com/64065190/118471258-231cac80-b73a-11eb-9a07-bcf6091378f8.png)

还可以优化一下，同事们反馈，不清晰   谢谢

**Comment by zyyfit** [comment]
1.10.0版本又加深了一下字体颜色，应该比较清晰了
