### ISSUE TITLE
[BUG] 接口测试-文档结构校验导入，值为null的键未导入并展示

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28541]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

 接口测试-文档结构校验导入，值为null的键未导入并展示

### 重现步骤

case-文档结构校验
导入：
{
"data":{
"aa":null,
"bb":null
}
}
无下级两字段名：
![image](https://github.com/metersphere/metersphere/assets/103925124/35a5f017-9daa-462c-ad55-11075690a34d)

### 期待的正确结果

 接口测试-文档结构校验导入，值为null的键可导入并展示

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
