### ISSUE TITLE
[BUG] 测试计划，关联用例得用例同时又1.0 2.0得数据，版本处多选筛选1.0 2.0，结果不显示1.0的数据

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28559]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

测试计划，关联用例得用例同时又1.0 2.0得数据，版本处多选筛选1.0 2.0，结果不显示1.0的数据

### 重现步骤

1、测试用例，同一用例有1.0 2.0版本
2、测试计划关联用例，筛选勾选1.0 2.0 。筛选结果只展示2.0 不展示1.0得数据

![不展示1 0 (1)](https://github.com/metersphere/metersphere/assets/43202800/5660f867-e118-4d17-9ad7-cb89c0861fc6)
![不展示1 0](https://github.com/metersphere/metersphere/assets/43202800/10d2b6d6-d4f9-42fe-a43b-d144b206298d)

**Comment by youliyuan-fit2cloud** [comment]
你好，列表中版本字段筛选出来的是，用例的最新版本，不是它的所有版本。
下面的版本筛选可以选择历史版本的用例
![image](https://github.com/metersphere/metersphere/assets/54612864/5037f876-ffc2-45ed-895f-ce21ed37ea1b)
