### ISSUE TITLE
[BUG]CSV路径地址问题

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#2857]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
接口自动化模块上传jmx脚本和csv文件，点击调试功能时由于CSV 数据文件设置里面的路径时本地址，所以无法执行成功并提示csv文件不存在。
**Bug 重现步骤**
1.  进入接口自动化上传jmx脚本到场景
2. 进入场景变量导入csv文件
3. 选择调试脚本
4. 提示csv文件不存在

**期待的正确结果**
正确情况下应该是什么样的？
上传csv文件后，脚本中CSV 数据文件设置里的文件路径要自动变成服务器的路径

**截图**
如果有截图，请附上截图.
<img width="584" alt="csv" src="https://user-images.githubusercontent.com/83771182/118433604-f0f55580-b70d-11eb-9d30-f41d9570c6b6.png">

**Comment by xulinde** [comment]
该问题已修复，是用的1.9.2版本吗

**Comment by yaoyi111** [comment]
是的，1.9.2版本



***@***.***
 
From: xulinde
Date: 2021-05-17 18:54
To: metersphere/metersphere
CC: yaoyi111; Author
Subject: Re: [metersphere/metersphere] [BUG] (#2857)
该问题已修复，是用的1.9.2版本吗

**Comment by zyyfit** [comment]
您好，如果脚本里的csv文件地址是本地地址，需要修改成服务器上的相对路径地址，否则是会找不到文件的
