### ISSUE TITLE
[QUESTION]API接口测试报错，调用资源池执行失败，请检查资源池是否配置正常，查看日志文件，报了个空指针异常

### ISSUE THREAD

**Issue by wenchao1020** [metersphere/metersphere#28585]
### 请描述您的问题

问题： API接口测试报错，调用资源池执行失败，请检查资源池是否配置正常，
MeterSphere 版本：v2.10
描述： 已经确认当前站点url和访问metesphere的web站点一致
错误日志：![image](https://github.com/metersphere/metersphere/assets/34122361/ffda4bb8-8dac-4d60-915d-69a0930b134b)

**Comment by luty2018** [comment]
问题是否还存在？

**Comment by huangrui75** [comment]
存在，linux本地化jar部署，调用接口平台的时候直接报这个错，后台日志看在这个地方报错了，node-controller用的是V2.10.10直接部署的版本
