### ISSUE TITLE
CSV变量参数丢失，导致性能测试无法单个遍历每个用户一次

### ISSUE THREAD

**Issue by jianfengshxy** [metersphere/metersphere#28589]
### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 联系方式

13918199137

### 请描述您的需求或者改进建议

测试场景， 性能测试 CSV里面 每个用户参加一次活动（只能一次），要求起多个线程（User）并发，文件结尾就结束了不要循环文件
这是
![Snipaste_2024-01-29_17-34-42](https://github.com/metersphere/metersphere/assets/1559991/6070d7fe-e70c-40a8-a708-5dfc79c6a2ce)
对比 jmeter的csv配置，少了这三个配置，无法在性能测试中实现。csv文件一次性每一个用户并发执行一遍，需要加这三个参数

### 请描述你建议的实现方案

![Snipaste_2024-01-29_17-29-48](https://github.com/metersphere/metersphere/assets/1559991/d400755c-a761-4a1d-ae2c-ab859a435a16)

**Comment by luty2018** [comment]
建议更新版本， 我们在最新版本的性能测试中已经提供了这几个配置项。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
