### ISSUE TITLE
[BUG]使用Chrome浏览器（版本：75.0.3770.142）打不开部署的页面

### ISSUE THREAD

**Issue by 997068329** [metersphere/metersphere#28584]
### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

在使用Chrome浏览器（版本：75.0.3770.142）打不开部署的页面，F12打开控制台有报错信息：Uncaught SyntaxError: Unexpected token ?

### 重现步骤

在Chrome浏览器（版本：75.0.3770.142）可以复现

### 期待的正确结果

低版本浏览器可以兼容

**Comment by liuruibin** [comment]
很遗憾，我们使用的组件并不支持低版本的浏览器。随着组件库的不断更新，未来也不会支持老版本的浏览器
