### ISSUE TITLE
[BUG]同一批运行的接口案例中（都有引用同一个场景脚本）偶发获取不到host

### ISSUE THREAD

**Issue by shoutian44443** [metersphere/metersphere#28587]
### 联系方式

MeterSphere 交流群 60（守天）

### MeterSphere 版本

 v2.10.8-lts-313def9d

### 使用外置数据库

是

### 问题描述

[BUG]同一批运行的接口案例中（都有引用同一个场景脚本）偶发获取不到host

![Image (6)](https://github.com/metersphere/metersphere/assets/60697646/1bf95f31-cfe4-46e6-af07-4a7805838987)
![Image (5)](https://github.com/metersphere/metersphere/assets/60697646/01b29bbf-4073-41f3-bc15-cc3bc7bba972)
![WXWorkCapture_17064973354716](https://github.com/metersphere/metersphere/assets/60697646/8cf6897c-6ac8-46fa-8cfe-faaf296e633d)
![WXWorkCapture_17064924808073](https://github.com/metersphere/metersphere/assets/60697646/d7052b71-f551-4524-b8c0-f61bfa6a1630)

### 重现步骤

1.定时任务半夜执行100多个案例均会引用同一个登录脚本
2.偶发一两个案例无法获取到host（此案例其他接口也同样获取不到host）

**Comment by youliyuan-fit2cloud** [comment]
你好，这种偶发的情况，请提供下详细的日志信息，失败的场景方便的话贴出来，感谢理解和支持～

**Comment by shoutian44443** [comment]
后面复现了：当定时计划没有配置默认环境 且加入的场景案例也没有选环境，且该场景案例没有保存环境，就会这样
                      
不过这个是在运行了很久以后才这样的（这个场景案例之前一直是由环境的，偶然就变成没有环境了）

**Comment by youliyuan-fit2cloud** [comment]
感谢再次反馈，这种情况，我们优化过一次，建议升级到最新版本尝试，感谢理解和支持。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
