### ISSUE TITLE
在脚本中导入API定义接口不够，应该可以导入

### ISSUE THREAD

**Issue by jianfengshxy** [metersphere/metersphere#28588]
### MeterSphere 版本

  v2.10.10-lts-e9b6aa9e

### 联系方式

13918199137

### 请描述您的需求或者改进建议

目前只导入接口和实际应用相差太远了，可以支持导入case，并且根据case的内容生成对应请求，
并且不只是返回一个response ，还要根据后置脚本json提取器和断言 生成代码

### 附加信息

![Snipaste_2024-01-29_17-26-07](https://github.com/metersphere/metersphere/assets/1559991/bbf78968-fffd-4124-8b95-ffa6d64aab0d)
图一生成的太少了实际应用其实是case要把json 解析，把对应提取的参数放到环境变量里面
![Snipaste_2024-01-29_17-27-29](https://github.com/metersphere/metersphere/assets/1559991/a2acfe28-6da2-48d9-af05-8be339f69ef4)

**Comment by luty2018** [comment]
请问这是导入的什么格式的文件

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
