### ISSUE TITLE
[BUG]性能测试jmx脚本包含多级事务结构执行报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#2859]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
上传的脚本中包含多级事务结构时，在性能测试场景执行出现报告生成错误，后台报容器启动失败。
**Bug 重现步骤**
1.  接口自动化模块上传包含父子级事务的jmx文件 见附件
2. 创建性能测试并执行
3. 执行后提示报告生成错误，并且性能指标数据都为空
4. 后台日志容器失败

**期待的正确结果**
正确情况下应该是什么样的？
应能正常执行并生成性能测试报告
**截图**
如果有截图，请附上截图.
<img width="271" alt="2" src="https://user-images.githubusercontent.com/83771182/118442796-a7146b80-b71d-11eb-9814-a0a26b0812f1.png">

附件见

[客户脚本.zip](https://github.com/metersphere/metersphere/files/6491622/default.zip)

**Comment by zyyfit** [comment]
您好，后续版本会修复这个问题

**Comment by xulinde** [comment]
使用最新版本未复现该问题，建议您升级到最新版本再试下
