### ISSUE TITLE
[BUG]【接口自动化】场景导入到接口自动化里，点击调试不运行

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#28590]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】场景导入到接口自动化里，点击调试不运行

### 重现步骤

【接口自动化】接场景导入到接口自动化里，点击调试不运行
![image](https://github.com/metersphere/metersphere/assets/104960608/59ed1035-9f34-4441-ae54-5a55dc1f0cc0)

场景如下
[Metersphere_Scenario_账户-接口.zip](https://github.com/metersphere/metersphere/files/14082619/Metersphere_Scenario_.-.zip)

**Comment by fit2-zhao** [comment]
场景变量中 verify_code_signin_phone 变量对应的函数写错导致，修改后执行正常。
