### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28591]
### MeterSphere 版本

v2.10.9-lts

### 联系方式

14707070227

### 请描述您的需求或者改进建议

建议消息通知模板，${scenarioShareUrl} 字段的解释可以明确一点，是否两个字太模糊了，使用上容易造成歧义，建议改成免登录链接地址

### 请描述你建议的实现方案

${scenarioShareUrl}  字段解释从 链接跳转是否登录  改成 免登录链接地址，可以跟 ${reportUrl} 解释形成对比

### 附加信息

![企业微信截图_e983b630-1c44-40bc-95d0-070f1e706fc4](https://github.com/metersphere/metersphere/assets/50016789/2a518054-177d-45d0-a46d-b38b87292c2d)
<img width="411" alt="企业微信截图_17065215008887" src="https://github.com/metersphere/metersphere/assets/50016789/af98ca49-a15d-4348-af96-dd55d131cf94">

**Comment by luty2018** [comment]
感谢建议， 我们优化一下。

**Comment by luty2018** [comment]
这个在v2.10.12版本中已优化。
