### ISSUE TITLE
[FEATURE] 接口自动化定时任务设置好打开任务并保存后，希望列表页面可以主动刷新一下，不刷新的话，还是定时任务在列表还是关闭的状态

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28594]
### MeterSphere 版本

v2.10.11-lts

### 联系方式

14707070227

### 请描述您的需求或者改进建议

接口自动化定时任务设置好打开任务并保存后，希望列表页面可以主动刷新一下，不刷新的话，还是定时任务在列表还是关闭的状态

### 请描述你建议的实现方案

设置好定时任务后可以自动刷新列表页面

### 附加信息

设置定时任务：
<img width="625" alt="9b00675e7cf4a29562102510a6c9f38" src="https://github.com/metersphere/metersphere/assets/50016789/4dce4962-606e-4b68-a284-427a807a1687">
设置好保存后列表还是关闭的状态：
<img width="893" alt="1706524990418" src="https://github.com/metersphere/metersphere/assets/50016789/ae52f711-7a78-4738-9aa2-1db6f654e958">
手动刷新后列表状态才正确：
<img width="815" alt="1706525012349" src="https://github.com/metersphere/metersphere/assets/50016789/97aa401d-1e1c-40ad-a5da-2d66e2b9653b">

**Comment by luty2018** [comment]
收到， 感谢建议， 我们改一下。

**Comment by 13290445582** [comment]
您好，已实现，请升级至v2.10.16版本使用。
