### ISSUE TITLE
[FEATURE]压力测试能否支持jar包引用上传

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#286]
**请描述您的需求或者改进建议.**
我们的接口有个token值需要计算转换，并且这个值是动态变化的，目前我们的做法是写了一个jar包并且在beanshell引用该jar包并调用方法，对于这种情况，目前平台不支持。

**请描述你建议的实现方案**
能否在上传JMX文件的同时也能上传jar包，该jar包放到类似jmeter的ext目录下面

**Comment by jw-td** [comment]
在dubbo测试的时候也有这个需求，当一个pojo定义比较复杂的时候，jmeter自己解析会可能会失败，此时会报java.lang.RuntimeException: Failed to set pojo xxxxxx property xxxxxx的exception。
如果可以上传自定义pojo jar包，就能解决此问题，烦请考虑支持。

当然这个功能不仅仅是放到ext下就行，还要考虑如何动态加载到此jar包，才能使的功能正常工作

**Comment by zyyfit** [comment]
已支持上传jar包
