### ISSUE TITLE
[BUG]v1.9.2版本，jsonpath提取功能不起作用，点击标签没有任何反应

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#2861]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
v1.9.2版本，jsonpath提取功能不起作用，点击标签没有任何反应

**截图**
![image](https://user-images.githubusercontent.com/49089965/118445199-b47f2500-b720-11eb-85fb-bf62e2ede608.png)

**Comment by xulinde** [comment]
没有复现该问题，控制台有没有报错信息

**Comment by wjtlt3** [comment]
知道问题了，必须要点击那个小方块才行，我一直点击的字符。

**Comment by wjtlt3** [comment]
知道问题了，必须要点击那个小方块才行，我一直点击的字符。
