### ISSUE TITLE
[BUG] tcp 后置脚本打印环境id值是null, http接口可以打印出来

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28622]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

tcp 后置脚本打印环境id值是null, http接口可以打印出来

![image](https://github.com/metersphere/metersphere/assets/43202800/fd111220-8195-4378-a954-2565394543e3)

![企业微信截图_17065988002318](https://github.com/metersphere/metersphere/assets/43202800/d3c98762-d95e-4d05-b0ab-f078bb531708)

### 重现步骤

tcp 后置脚本打印环境id值是null, http接口可以打印出来

log.info("打印id+" + ${__metersphere_env_id});

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
你好，调试本身打印环境 id 没啥意义，暂不支持。创建TCP接口的CASE是支持后置脚本打印环境id值的，请升级v2.10.22版本使用。
