### ISSUE TITLE
导出的html测试报告默认看不到用例，需要手动搜索才可以[BUG]

### ISSUE THREAD

**Issue by IsChusen** [metersphere/metersphere#28625]
### 联系方式

cs81118111@gmail.com

### MeterSphere 版本

v1.20.x-lts

### 使用外置数据库

否

### 问题描述

导出的html测试报告默认看不到用例，需要手动搜索才可以

### 重现步骤

离线部署linux，主功能跑通，导出或者在线查看html报告

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/94282019/f9ac3a6e-7f56-462f-af04-71b538ad1e8c)

**Comment by 13290445582** [comment]
感谢反馈，已知问题，后续将在v2.10-lts版本修复，建议修复后升级v2.10-lts版本。

**Comment by 13290445582** [comment]
问题已修复，请升级v2.10.14版本。
