### ISSUE TITLE
使用jmeter文件上传至接口自动化，转成性能测试用例后，执行性能测试用例得到的TPS数量和实际相差十倍

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#28629]
### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

当将从jmeter中导出的jmeter脚本中上传至接口自动化中，保存为一个场景用例，然后将场景用例一键转为性能测试用例，设置好相应的并发等参数，执行性能测试用例，得到的TPS的数量和直接在性能测试用例列表，上传jmeter文件，创建性能测试用例，在相同的环境和测试参数情况下，测试结果TPS相差十倍
从接口自动化转性能测试结果
<img width="1278" alt="截屏2024-01-30 下午4 26 28" src="https://github.com/metersphere/metersphere/assets/34637801/62a6b78c-d31b-4e1c-936a-1f6f41bcdc41">
直接在性能测试用例上传jmeter文件测试结果
<img width="1286" alt="截屏2024-01-30 下午4 24 43" src="https://github.com/metersphere/metersphere/assets/34637801/08026a06-da27-4eef-a7fd-347b859acdf0">

### 重现步骤

1.准备一个2.10.11的MeterSphere环境
2.准备一个可以调试通过的jmeter脚本
3.从接口自动化上传保存为一个场景用例，转成性能测试用例，设置相应的测试参数
4.执行测试用例。
5.在性能测试列表创建一个性能测试用例。
6.上传同一个jmeter文件，设置相同的性能的性能测试参数，执行用例
7.对比两个用例执行结果

### 期待的正确结果

希望测试结果一致

### 附加信息

从接口自动化转成性能测试用例时会多出一个线程组，希望上次接口自动化时能自动去掉，性能测试结果不准的原因也是因为多了这个线程组导致的。

**Comment by fit2-zhao** [comment]
接口测试中会解析源文件并做一些加工处理，为了保证接口测试中变量能正确隔离，所以会加临界控制器，临界控制器在跑性能测试时tps 肯定会有 影响，建议转性能测试后下载jmx 手动调整下。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
