### ISSUE TITLE
ms-node-controller组件在执行任务一段时间后，会存在内存积累不释放的问题

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#28631]
### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

当使用【ms-node-controller】资源池执行接口自动化定时任务，频率为5分钟一次，当执行12个小时后，存在【ms-node-controller】 内存积累且不释放的问题。
【ms-node-controller】内存使用截图，已经占用了5.133GB：
<img width="561" alt="截屏2024-01-30 下午4 38 16" src="https://github.com/metersphere/metersphere/assets/34637801/53276aa3-5b81-4a7c-939e-f6502434d85f">
【ms-node-controller】的info.log日志截图，已半个多小时未刷新日志：
<img width="774" alt="截屏2024-01-30 下午4 39 46" src="https://github.com/metersphere/metersphere/assets/34637801/11685ad2-cffe-4edc-8ea2-b3cd50159930">
【ms-node-controller]的ms-jmeter-run.log日志截图，已经半个多小时未执行任务：
<img width="826" alt="截屏2024-01-30 下午4 41 52" src="https://github.com/metersphere/metersphere/assets/34637801/14cd0a22-4f18-420d-bc6b-bd35958bea62">

### 重现步骤

1.准备一个v2.10.11的MeterSphere环境
2.准备多个可调试通的接口自动化用例（10-20个场景用例）
3.准备一个测试计划关联以上多个接口自动化用例
4.设置测试计划定时任务执行，五分钟执行一次，执行十二个小时
5.停止测试计划，查看ms-node-controller内存占用情况变化

### 期待的正确结果

ms-node-contorller组件内存占用能在任务结束后及时释放

**Comment by fit2-zhao** [comment]
Could you try collecting and analyzing the heap dump? (see HeapDumpOnOutOfMemory + Eclipse Memory Analyzer)


OutOfMemoryError: Metaspace means there are too many classes loaded.

Could you try opening Duplicate Classes report instead?

See

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.mat.ui.help%2Freference%2Finspections%2Fduplicate_classes.html
https://www.eclipse.org/forums/index.php/t/1088736/

**Comment by lvchunyu1993** [comment]
存在同样的问题 Terminating due to java.lang.OutOfMemoryError: Java heap space

**Comment by xchnshi** [comment]
有进展吗？在下个小版本会修复吗？

**Comment by fit2-zhao** [comment]
出现问题时可以参考这个 https://github.com/metersphere/metersphere/issues/29586 抓取一份Thread Dump文件发出来。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
