### ISSUE TITLE
[BUG]配置的断言比较运算符未正确生效

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#2863]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
Jsonpath断言这里设置的不等于，但是实际还是按等于处理的

**截图**
![image](https://user-images.githubusercontent.com/49089965/118445439-0627af80-b721-11eb-824f-7d1ace77a00d.png)

**Comment by zyyfit** [comment]
您好，是必现的吗？能否描述一下详细信息，这边没有复现呢

**Comment by wjtlt3** [comment]
必现，看下面的截图。

![image](https://user-images.githubusercontent.com/49089965/118753335-59237300-b897-11eb-9eaa-37804ce108b0.png)
![image](https://user-images.githubusercontent.com/49089965/118753368-6cced980-b897-11eb-9453-5356938e6c49.png)
