### ISSUE TITLE
[BUG]自定义SQL请求执行异常

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#2864]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
这两个sql请求的步骤直接不执行了。。。单独调试sql请求也没反应。
重启了数据库也没用，还是老问题。

单独执行sql请求是一直转圈。
整个场景一起执行，在调试结果窗口直接没有 sql请求 的步骤数据。

**截图**
![image](https://user-images.githubusercontent.com/49089965/118445808-7b938000-b721-11eb-8dbb-4f169b2d87f5.png)

**Comment by wjtlt3** [comment]
和陈建星一起排查发现
1.自定义SQL请求里，有后置python脚本，导致执行异常
2.当启用开关关闭，再单独执行该请求，执行异常

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
排查完发现，使用python后置脚本执行失败会导致获取不到结果，脚本如下，已修改成忽略脚本失败

print("=====> resultSets: " + vars.get("resultSets1"))
print("=====> id: " + vars.get("modify_id1_1"))
print("=====> name: " + vars.get("modify_name1_1"))
print("=====> asset_id: " + vars.get("modify_asset_id1_1"))

// ${modify_name1_1}表示取出 modify_name1 字段中第一条数据，取第几条数据角标写对应数字即可。
if (${modify_name1_1} == "自动化测试修改成功1")：
    log.info("=====素材修改成功=====")
else
    AssertionResult.setFailure(true)
log.info("=====素材修改失败=====")

**Comment by zyyfit** [comment]
1.10.0版本已发布
