### ISSUE TITLE
[FEATURE]接口自动化环境配置中当配置了多个域名时，希望可以支持下拉选择，而不是默认只能选择第一个

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28654]
### MeterSphere 版本

v2.10.11-lts

### 联系方式

14707070227

### 请描述您的需求或者改进建议

接口自动化环境配置中当配置了多个域名时，希望可以支持下拉选择，而不是默认只能选择第一个

### 请描述你建议的实现方案

接口自动化环境配置中当配置了多个域名时，希望可以支持下拉选择

### 附加信息

<img width="960" alt="a698b7b98a7ab7548ca832f039531d6" src="https://github.com/metersphere/metersphere/assets/50016789/f2c46fef-3d1c-46d7-aa60-c38e4227ab00">

**Comment by luty2018** [comment]
匹配到多个规则的时候才默认取第一个， 这里是交叉配置了， 是否在第一个域名里面取消当前模块？

**Comment by AitchHe** [comment]
我也有同样的问题，目前一个接口仅支持一个域名，且不能自定义更改，这严重限制了测试场景，能不能支持下，如果有多个规则，默认第一个的同时，能不能支持下拉选择
