### ISSUE TITLE
[BUG]【接口测试】JSON数组参数从 json 切换到 JSON-SCHEMA,再切回到 JSON，参数格式转换不正确

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28658]
### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

接口参数是 json 数组，将参数格式 json 切换到 JSON-SCHEMA,再将 JSON-SCHEMA 切回到 JSON，参数格式转换不正确，原来json 数组变成列表了

### 重现步骤

1、创建一个接口
2、在接口编辑页面上，切换到请求体模块，参数类型选择 json
3、填入 json 数组参数
4、将参数格式 json 切换到 json-schema
5、将 json-schema关闭，切换成 json 格式
6、观察参数格式转换是否正确

### 期待的正确结果

参数格式 json-schema切回到 json 参数格式转化正确

### 附加信息

参数转化
![p01qp-fm2vx](https://github.com/metersphere/metersphere/assets/45531073/4583d1c1-f52b-49e7-be0a-f25f687be005)

转化前参数格式
![image](https://github.com/metersphere/metersphere/assets/45531073/f203ebef-3ebe-499d-8111-2dc80f748f06)
转化后参数格式
![image](https://github.com/metersphere/metersphere/assets/45531073/3039d085-e63c-4aee-b65c-49c87507b2f0)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。
