### ISSUE TITLE
[FEATURE]IDEA的metersphere插件需要更新

### ISSUE THREAD

**Issue by franky899** [metersphere/metersphere#28692]
### MeterSphere 版本

插件版本1.2.6

### 请描述您的需求或者改进建议

目前IDEA升级到2023.2版本或以上版本用不了metersphere插件了
<img width="229" alt="ms" src="https://github.com/metersphere/metersphere/assets/54705762/a4a08553-f562-47d6-b7e8-85109ea16cf7">

**Comment by fit2-zhao** [comment]
1.2.7版本已经上传到jetbrains插件市场，审核完成后就可以下载了。
