### ISSUE TITLE
[BUG]接口自动化事务控制器下接口点击单步骤执行，上面接口会跟着执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#28697]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

接口自动化事务控制器下接口是复制的上面步骤的接口，点击单步骤执行，上面被复制的接口会跟着执行

### 重现步骤

1. 创建场景，添加接口，添加事务控制器，复制上面步骤接口，放到事务控制器内，点击事务控制器接口单步骤执行，上面被复制的接口也跟着执行了
![image](https://github.com/metersphere/metersphere/assets/103627487/53ccc851-35b9-4e5d-879f-90a9a9d00592)

**Comment by 13290445582** [comment]
您好，已知问题，但目前未有好的解决方案，暂时无法解决，感谢理解。
