### ISSUE TITLE
[QUESTION] Chart部署Performance-test哪些模块也要同时enable？

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#28698]
### 请描述您的问题

版本：v2.10.11-lts
如果不部署api/test-track/ui/workstation/project management这些，只想进行性能测试，除了performance-test，其他的还有哪些要同时部署的吗？
谢谢

**Comment by liuruibin** [comment]
你可以再启动后手动关闭api-test test-track 等这些模块，gateway eureka system-setting project-management是基础模块必须开启
