### ISSUE TITLE
[BUG]测试跟踪-缺陷管理，多人同时提交缺陷，导致缺陷ID重复现象

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#28712]
### 联系方式

张树彬

### MeterSphere 版本

2.10.9LTS

### 使用外置数据库

否

### 问题描述

测试跟踪-缺陷管理，多人同时提交缺陷时，导致两条缺陷出现重复的ID

### 重现步骤

1. 进入测试跟踪-缺陷管理
2. 两个人同时创建缺陷，同时提交（本地创建，没有与其他平台集成）
3. 提交成功后，缺陷列表出现两条缺陷ID是相同的情况

### 期待的正确结果

缺陷ID应该是唯一的，不应该重复

### 附加信息

![4cba77deacbbb8cdd9f776344ec3b2d](https://github.com/metersphere/metersphere/assets/77324661/f305363c-d2fa-443a-adef-513d82e4b6b8)

**Comment by 13290445582** [comment]
您好，在v2设计上是有重复的可能，但是概率比较低，涉及的地方有点多，不好变更，v3解决，目前重复的，可以手动改下 issue 表的 num 字段，感谢您的理解与支持。
