### ISSUE TITLE
[BUG]性能测试断言错误时，错误记录断言错误信息显示不准确

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#28710]
### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

性能测试，当请求有多个断言时，有断言错误时(不是第一个断言错误），错误记录断言错误信息显示第一个断言的信息

### 重现步骤

1. 接口有多个断言，第二个断言报错，但是性能错误记录断言错误信息显示第一个断言的信息
![image](https://github.com/metersphere/metersphere/assets/103627487/ac09f9cd-ac96-4886-aed4-0a9c52395f52)
![image](https://github.com/metersphere/metersphere/assets/103627487/29fa1d60-b870-4f4b-9699-2202beb0c9cf)
经测试发现，断言有报错，好像一直显示的都是第一个断言的信息，希望哪个断言报错展示哪个断言的信息，方便一眼看出哪个断言的问题

### 期待的正确结果

希望哪个断言报错展示哪个断言的信息，方便一眼看出哪个断言的问题

**Comment by liuruibin** [comment]
目前就是这么设计的

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
