### ISSUE TITLE
[BUG]09版本直升11版本，服务无法启动

### ISSUE THREAD

**Issue by maiyajj** [metersphere/metersphere#28724]
### 联系方式

18042078927

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

09版本直升11版本，服务无法启动
<img width="885" alt="微信图片_20240202111549" src="https://github.com/metersphere/metersphere/assets/18521350/a7204a08-c3c3-41a5-96c0-4eb5d3a9b71b">
[gateway.log](https://github.com/metersphere/metersphere/files/14133766/gateway.log)
[system-setting.log](https://github.com/metersphere/metersphere/files/14133767/system-setting.log)

### 重现步骤

1、09版本数据库使用mysqldump导出数据sql，再将sql导入。
2、离线安装11版本。

### 期待的正确结果

1、11版本正常安装
2、服务正常启动

**Comment by liuruibin** [comment]
<img width="1068" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/c25bfa25-ef8e-45a0-ab85-45c200fd428f">
数据库里保存的key不能正常序列化，你把数据库表中的这条删除后重启

```
SELECT *
FROM file_metadata
WHERE name LIKE 'ms.login.rsa.key';

SELECT *
FROM file_content
WHERE file_id = 'ms.login.rsa.key';
```

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
