### ISSUE TITLE
[FEATURE]建议测试报告增加“需求清单”项，报告可导出Word文档

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#28737]
### MeterSphere 版本

v2.10.11

### 联系方式

357861578@qq.com

### 请描述您的需求或者改进建议

目前测试报告仅一项可编辑区域“报告总结”，因实际项目中测试报告还需要列出需求清单，建议增加需求清单编辑项，类似报告总结可以输入一段文字；报告的导出目前仅支持导出html文件，且不可查看用例清单，建议测试报告可以导出word文件，方便存档

### 请描述你建议的实现方案

建议测试报告增加“需求清单”项，报告可导出Word文档

**Comment by luty2018** [comment]
感谢反馈， 我们调研一下。
需求清单是指所有用例关联的需求都能展示是吗？
html格式的文件也可以存档。 这里为什么指定是Word？是有html覆盖不到的地方吗？

**Comment by heavenlyye** [comment]
需求清单能不能自动关联需求都可以，能有一个文本框可以手动填写需求内容即可

**Comment by heavenlyye** [comment]
对于目前已有的测试报告导出html文件，看不到用例清单，建议可以导出word文档，方便存档

**Comment by luty2018** [comment]
> 需求清单能不能自动关联需求都可以，能有一个文本框可以手动填写需求内容即可

既然只是要可以录入的话， 报告总结里面完全可以录需求清单了吧， 报告总结是一个富文本。
