### ISSUE TITLE
[BUG] tcp接口，场景添加${变量名后} 脚本就执行了 一直再running状态

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28739]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

tcp接口，场景添加${变量名后} 脚本就执行了 一直再running状态

### 重现步骤

tcp接口，场景添加${变量名后} 脚本就执行了 一直再running状态，不添加变量直接传参可以运行

### 期待的正确结果

支持 ${变量名} 传参

**Comment by xhy12** [comment]
同类问题：
提取参数采用xpath，提取到变量后，无法采用${}方式在后续脚本使用该变量
断言规则也无法使用${}方式，来使用之前提取的变量
<img width="948" alt="d018837d9bf0b77a14f9669be5c3da0" src="https://github.com/metersphere/metersphere/assets/43202800/d4b3a3f7-9126-4344-bc13-5791ce745372">

**Comment by 13290445582** [comment]
您好，排查应该是插件影响，单独脚本引用变量值同样无法执行，先将其余插件卸载干净再次尝试。
