### ISSUE TITLE
[BUG] tcp请求 case，在后置步骤添加sql请求后 一直在running状态

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28740]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/43202800/56c8cfbc-1a31-47b6-9581-d61d7deca91d)

### 重现步骤

 tcp请求 case，在后置步骤添加sql请求后 一直在running状态

**Comment by 13290445582** [comment]
经过测试，该sql所用数据源，执行sql请求未成功，先找下未执行sql成功的原因。

**Comment by 13290445582** [comment]
已卸插件，sql正常执行，非缺陷，issue关闭，感谢理解。
