### ISSUE TITLE
测试报告邮件链接只能用账号登录查看，不方便，是否可以添加过滤器，游客可以查看测试报告，不用登录

### ISSUE THREAD

**Issue by lxh3145** [metersphere/metersphere#2874]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
简要描述您碰到的问题
测试报告邮件链接只能用账号登录查看，不方便，是否可以添加过滤器，游客可以查看测试报告，不用登录
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
测试报告邮件链接只能用账号登录查看，不方便，是否可以添加过滤器，游客可以查看测试报告，不用登录
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，不登录就可以查看测试报告是一件风险很大的事情，我们会内部讨论一下
