### ISSUE TITLE
[BUG] 在测试计划列表里，点击“查看报告详情”，接着设置报告总结，然后执行测试计划。在测试报告页面，查看新的报告详情，仍然能看到之前设置的报告总结信息。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28741]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

在测试计划列表里，点击“查看报告详情”，接着设置报告总结，然后执行测试计划。在测试报告页面，查看新的报告详情，仍然能看到之前设置的报告总结信息。
但是根据这个报告的id去数据库查询，summary 字段为空，应该是显示的问题。

<img width="1018" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/b7aaec90-b104-4341-953f-6eabf1936ee8">
<img width="803" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/e20cfc4c-5980-4b80-bdb2-d61594588a1c">

<img width="1241" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/5977a07f-223b-4d30-aea1-bf5d67c20b6e">
<img width="888" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/ee1efda5-f2eb-4057-84bc-8810e64ed373">

### 重现步骤

1. 在测试计划列表里，点击“查看报告详情”，接着设置报告总结，
2. 然后执行测试计划。
3. 在测试报告页面，查看新的报告详情，仍然能看到之前设置的报告总结信息。

**Comment by 13290445582** [comment]
感谢反馈，非问题，您是通过测试计划列表查看测试报告跳转到的报告页面进行编辑报告总结，该处的报告并不是一次性报告，所以再生成报告是会保存编辑的报告总结的内容的。若您从测试跟踪-报告处进入报告编辑报告总结，再生成的报告不会保存您编辑的内容。
