### ISSUE TITLE
[BUG] 性能测试中，手动删除了项目文件，报告变得不可删除

### ISSUE THREAD

**Issue by tearell** [metersphere/metersphere#28753]
### 联系方式

tearell@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

无法删除已不存在的性能测试产生的报告

### 重现步骤

1.新增一个性能测试用例
2.执行这个用例
3.在项目文件中，能够看到一些自动生成的文件，并手动删除它
4.删除这个性能测试用例
5.删除多余的报告（无法删除）

### 期待的正确结果

能够正常删除报告

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题。后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
你好，请升级一下吧。问题已修复。
