### ISSUE TITLE
[BUG] 接口测试，环境配置-http配置，切换域名时，启用条件未跟随变化

### ISSUE THREAD

**Issue by bruceqiao** [metersphere/metersphere#2877]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![微信截图_20210517172051](https://user-images.githubusercontent.com/1934641/118465395-6bd16700-b734-11eb-9431-ef2da0acc979.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.10.0版本已修复
