### ISSUE TITLE
[BUG]接口自动化通过率计算错误

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28780]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

1. 接口自动化场景中引用了两个case
2. 保存后并执行
3. 两个case 中一个成功一个失败，通过率应该是50%, ，但是列表上却显示为67%

### 重现步骤

1. 接口自动化场景中引用了两个case
2. 保存后并执行
3. 两个case 中一个成功一个失败，通过率应该是50%, ，但是列表上却显示为67%

### 期待的正确结果

接口自动化通过率为50%

### 相关日志输出

```shell
无
```

### 附加信息

<img width="658" alt="e46a07b6c5e331255d22fc4705942cf" src="https://github.com/metersphere/metersphere/assets/50016789/1ef0d3f4-db16-4bd6-b44a-4f7e2fa41788">
<img width="820" alt="03acf22f2fac919bc0f19bd8aceebb1" src="https://github.com/metersphere/metersphere/assets/50016789/54b71fc0-0656-4489-adf3-4a0c0712b169">
<img width="816" alt="787a186c7341c3dd196427fad0a44fd" src="https://github.com/metersphere/metersphere/assets/50016789/ef32e725-76bf-445d-b3a0-1420ebf8dd76">

**Comment by 13290445582** [comment]
您好，尝试下新建一个场景引用两个case去执行，会复现该问题吗？本地未复现该情况。

**Comment by spritelyl** [comment]
会的

**Comment by 13290445582** [comment]
您好，经过检查环境，全局前置脚本有关联场景结果，这个算一条数据，将此处取消选择即可。
