### ISSUE TITLE
[BUG]通过脚本设置path后，第二次用脚本取path不对

### ISSUE THREAD

**Issue by linjzy** [metersphere/metersphere#28782]
### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

业务场景有2次取path的脚本，第二次不对，同样的脚本jmeter是正确的，详细设置如截图
![微信图片_20240204153028](https://github.com/metersphere/metersphere/assets/10286739/8fb3f770-33c4-48a3-9fbf-c75ffc9fd3b1)

![微信图片_20240204153327](https://github.com/metersphere/metersphere/assets/10286739/0afe4abf-556c-44ea-83af-647d47fc0693)

### 重现步骤

见附件

**Comment by 13290445582** [comment]
您好，未复现您这种情况，本地环境测试未发现该问题，是有其他步骤影响到该结果了吗？
![image](https://github.com/metersphere/metersphere/assets/128017892/f129b99d-0910-4d85-8ef7-eab4754ae35f)
![image](https://github.com/metersphere/metersphere/assets/128017892/c4831134-1aed-4dc3-bc7b-9c48a6d8d1d3)

**Comment by linjzy** [comment]
第二个截图有查询参数，你加上应该就能复现

**Comment by 13290445582** [comment]
您好，可以发一下您完整的url

**Comment by linjzy** [comment]
https://www.baidu.com/login.do?method=loginAndGo&loginName=abc

**Comment by 13290445582** [comment]
您好，sampler.getPath() 获取的是路径，如果想要获取url参数 请使用sampler.getUrl()；我们使用的底层测试引擎 JMeter 机制就是这样的，在JMeter中查看控制台打印的是一致的。
