### ISSUE TITLE
[FEATURE] 实现从循环中跳出，进入下一元素（类似于java 循环里面的continue 语句）

### ISSUE THREAD

**Issue by jianfengshxy** [metersphere/metersphere#28781]
### MeterSphere 版本

  v2.10.10-lts-e9b6aa9e

### 联系方式

13918199137

### 请描述您的需求或者改进建议

![当前的困难](https://github.com/metersphere/metersphere/assets/1559991/6a305423-a5e0-430b-91d4-de09a33ec85b)
![传统实现方式](https://github.com/metersphere/metersphere/assets/1559991/e03836ef-7c62-4f02-856b-802195253507)

第一张图代码简洁 ，但是目前实现起来有点困难。
第二张图是传统实现方式，嵌套太深，可维护性阅读性不强

### 请描述你建议的实现方案

总结起来说，目前在N多 逻辑判断后执行的操作 ，会被嵌套在大量IF控制器里面。优化：  如果把正确的逻辑操作提到第一层级（和条件判断平级），当判断条件不成立，直接跳出循环，进入下一个元素， 这样case简单容易管理

如果能支持 从 循环中 continue 跳出操作， 那么方案一就可以实现， case维护性大大增强

**Comment by luty2018** [comment]
感谢建议， 这个我们在v3.0讨论规划。
