### ISSUE TITLE
[QUESTION]性能测试 V2.10.11

### ISSUE THREAD

**Issue by RogerQian27** [metersphere/metersphere#28783]
### 请描述您的问题

上传jmx脚本，执行性能测试报错：Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms9-jdk17
![2](https://github.com/metersphere/metersphere/assets/42488705/3f65f2e6-94db-4d3b-ba3d-a187694ced71)

**Comment by liuruibin** [comment]
如果是自己单独部署的node-controller的话，需要自行下载这个镜像

docker pull registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.5-ms9-jdk17

**Comment by RogerQian27** [comment]
感谢，收动拉取镜像后问题已解决。但是在执行时，使用local资源池会继续报错。

Error: 检查资源池节点上的 /etc/hosts 是否有 127.0.0.1 `当前主机名` 这条配置，请确保这个配置存在并删除报告重新执行

**Comment by RogerQian27** [comment]
相同的问题之前有人提过，https://github.com/metersphere/metersphere/issues/18201，但是没有解决。
当前部署的k8s集群有3个节点，但是node-controller只部署了一个，资源并没有完全利用。
