### ISSUE TITLE
[FEATURE]【性能测试】执行性能测试脚本无写文件权限

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28838]
### MeterSphere 版本

v2.10.11

### 请描述您的需求或者改进建议

1、希望 jmeter 容器有写文件权限 ，执行性能测试支持写文件
2、jmeter容器可以挂载/opt/metersphere/data目录，执行完性能测试，可以下载文件

### 请描述你建议的实现方案

1、以root 运行 jmeter容器
2、jmeter 容器挂载/opt/metersphere/data目录

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/f0740c69-939a-4532-bba3-7b61fcd53d52)

**Comment by liuruibin** [comment]
性能测试的执行会新启动一个jmeter容器，不会挂载主机目录，执行结束自动销毁。无法操作主机上的文件，后续也没这种考虑
