### ISSUE TITLE
[BUG]【UI 测试】执行UI 场景测试时，使用平台内置 chrome 驱动测试报错

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#28839]
### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

用平台自带的 chrome 驱动执行 UI测试提示如下错误，换成 firefox 执行测试是正常的
unknown error: cannot determine loading status from unknown error: cannot determine loading status

### 重现步骤

1、UI 测试脚本使用 chrome执行

复现脚本可以联系我

### 期待的正确结果

使用 chrome驱动可以正常执行测试

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/fd08ec84-b2d8-4553-a3fd-ea5f7cea3ba4)
![image](https://github.com/metersphere/metersphere/assets/45531073/67693a7c-cefd-4512-9473-f1b1936aa9bf)

chrome 驱动执行测试
![image](https://github.com/metersphere/metersphere/assets/45531073/f6b07ee9-704d-4afc-9649-799926e9c786)

 firefox 驱动执行测试
![image](https://github.com/metersphere/metersphere/assets/45531073/19d8636b-c934-4e93-8066-76b111b53b96)

**Comment by 13290445582** [comment]
您好，请尝试将Chrome升级到最新版本测试，本地暂未复现该情况。
