### ISSUE TITLE
安装卸载步骤后，重新在线安装，就安装不起来

### ISSUE THREAD

**Issue by huangrui75** [metersphere/metersphere#28865]
### 请描述您的问题

安装卸载步骤后，重新在线安装，就安装不起来，system-setting一直报这个错：
<img width="944" alt="169d0610a40942e37e37dfeeef2cbc4" src="https://github.com/metersphere/metersphere/assets/159115897/b3302ae7-1e23-4b16-8ee6-fac5b10a4b0d">

**Comment by liuruibin** [comment]
看错误提示是连不上mysql，检查一下mysql这个容器的状态

**Comment by huangrui75** [comment]
> 看错误提示是连不上mysql，检查一下mysql这个容器的状态
  我试了一下，mysql是正常的，用ip去连接就不行，用容器名才行
