### ISSUE TITLE
[BUG] 复制同一个测试计划，修改其中的一个测试计划的环境并保存，另一个测试计划也会跟着变化，两个环境互相会串

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#28861]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

复制同一个测试计划，修改其中的一个测试计划的环境并保存，另一个测试计划也会跟着变化，两个环境互相会串

https://github.com/metersphere/metersphere/assets/33945037/7c234974-db93-448e-828b-bfb947c42ea9

### 重现步骤

1. 创建一个测试计划
2. 复制这个测试计划
3. 更改其中一个运行环境并保存，另一个也会发生发生变化
4. 对同一个测试计划打开执行页面两次，两次的环境都不一样。

**Comment by hao65103940** [comment]
又出现了一个新的问题，就是测试计划指定环境的时候，点击”保存”，再次点开是能够查看到刚才的那个环境，当点击”保存并执行“的时候，再次点开就看不到之前选择的那个环境了

https://github.com/metersphere/metersphere/assets/33945037/a5f7b42f-7e41-4e30-967b-6dedf50b59f5

**Comment by liqiang-fit2cloud** [comment]
> 又出现了一个新的问题，就是测试计划指定环境的时候，点击”保存”，再次点开是能够查看到刚才的那个环境，当点击”保存并执行“的时候，再次点开就看不到之前选择的那个环境了
> 
>  iShot_2024-02-07_16.03.16.mp4

另外提一个issue

**Comment by Somebody-JIAN** [comment]
> 又出现了一个新的问题，就是测试计划指定环境的时候，点击”保存”，再次点开是能够查看到刚才的那个环境，当点击”保存并执行“的时候，再次点开就看不到之前选择的那个环境了
> 
>  iShot_2024-02-07_16.03.16.mp4

这是一个显示问题

这个问题起源于一个需求：V2目前的版本，允许用户不选择环境进行用例关联。

由于V2数据结构的局限性，以及用户的可选操作比较多，包括但不限于直接执行、保存并执行、切换环境执行、切换环境保存并执行、进入测试计划中针对单独用例修改环境、删除部分用例对应的环境、重新关联一些没有选择环境的用例等种种操作。

我们无法有一个明确的标识判断并显示。

我也很遗憾，这里目前确实改不动了……
