### ISSUE TITLE
[FEATURE] 功能用例中的评论增加类型筛选

### ISSUE THREAD

**Issue by lingllgh** [metersphere/metersphere#28896]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 请描述您的需求或者改进建议

测试计划中的测试用例的评论是可以进行类型筛选的, 如下图:
![image](https://github.com/metersphere/metersphere/assets/126652938/70e27ab7-7193-4939-9d1f-301c85b17d2f)

希望在测试用例的详情页面中也能有这个筛选, 方便查看评论

**Comment by luty2018** [comment]
这个已经在v3.0版本实现了， 可以关注v3.0的发布哈。
