### ISSUE TITLE
[BUG]   用户表信息查询时未分辨大小写，导致本地用户和单点登录用户信息异常冲突报错

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#28894]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

  用户表信息查询时未分辨大小写，导致本地用户和单点登录用户信息异常冲突报错

### 重现步骤

新建本地用户邮箱为LILY@email.com
配置单点登录如OIDC信息后，在登录页跳转报错
![image](https://github.com/metersphere/metersphere/assets/103925124/669b2062-c11f-4c33-80c9-40cca6878ca0)
原因：OIDC的用户名为lily@email.com，查询数据库信息时，忽略了大小写
![image](https://github.com/metersphere/metersphere/assets/103925124/593be688-6a36-42dc-9992-82a19282fd1f)

### 期待的正确结果

本地邮箱和单点登录邮箱不是完全一致时不冲突，可正常登录

**Comment by liuruibin** [comment]
删除其中一个用户即可

**Comment by fit2cloud-yaochunrong** [comment]
本地用户挺多数据的，不能被删除

如果是同一个人有两个来源咱不支持
但是同一个邮箱，一个大写一个小写，咱系统不应该判断为同一人

**Comment by liqiang-fit2cloud** [comment]
设计如此，电子邮件地址本来就不区分大小写，AAA@A.com和aaa@a.com是一个邮件地址。
这种冲突的情况需要你自己处理。
