### ISSUE TITLE
[BUG]接口测试调试结果中提取变量没有显示在正确的位置中

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#289]
**MeterSphere 版本**
v1.2

**Bug 描述**
接口测试调试结果中提取变量没有显示在正确的位置中

**Bug 重现步骤**
1.  选择任意一个接口，设置变量提取(我选择的xpath，比如//input[@name='execution']/@value)
2. 点击调试按钮，查看调试结果中的响应部分
3. 提取变量的结果信息显示在断言中
4. 

**期待的正确结果**
提取变量的结果信息能够显示类似"提取变量"tab中

**截图**
<img width="844" alt="m2" src="https://user-images.githubusercontent.com/21210217/91414114-aaf61a00-e87e-11ea-99ea-84a3b288f5cb.png">

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决
