### ISSUE TITLE
[BUG] minio当前版本存在权限提升漏洞，需要升级

### ISSUE THREAD

**Issue by duxiaohan** [metersphere/metersphere#28905]
### 联系方式

duxiaohan1991@126.com

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

MinIO<RELEASE.2024-01-31T20-20-33Z 存在权限提升漏洞，可导致攻击者可利用该漏洞在获得低权限的情况下，构造恶意数据执行权限提升攻击，最终获取管理员权限。

### 重现步骤

进入minio容器，查看minio版本

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/28395 

你可以自行修改

<img width="741" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/96bd6d57-014b-4a13-a188-2bf2ddff11f8">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，参考上诉回复修改minio版本。
