### ISSUE TITLE
[FEATURE]希望在环境配置里面的全局前置脚本添加一个单次运行前置脚本

### ISSUE THREAD

**Issue by dugumona** [metersphere/metersphere#28929]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

微信群---MeterSphere 交流群58----思

### 请描述您的需求或者改进建议

增加单次执行的全局前置脚本  运行接口的时候 获取环境-》获取全局前置脚本-》获取单次前置脚本  
这样在接口定义哪里 调试接口就不用设置授权了 
手动设置的授权有时效性、系统登录通过sso单点登录、登录接口和测试接口环境不同

**Comment by luty2018** [comment]
<img width="939" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/702691fe-ef94-4104-859f-49669b756cca">
这个不能覆盖吗？
