### ISSUE TITLE
[FEATURE]在接口测试中编辑case的名称时，输入框过小，显示不出完整的case名称，建议将case名称下移且整行显示出case名称，方便编辑和查看完成的case名称。

### ISSUE THREAD

**Issue by ifpandas** [metersphere/metersphere#28927]
### MeterSphere 版本

v2.10.2-lts-b028f4ea

### 联系方式

fengyifu@sutpc.com

### 请描述您的需求或者改进建议

[FEATURE]在接口测试中编辑case的名称时，输入框过小，显示不出完整的case名称，建议将case名称下移且整行显示出case名称，方便编辑和查看完成的case名称。

![image](https://github.com/metersphere/metersphere/assets/160563723/74b0b054-1f89-4c50-ba3f-18bc01aabbf1)

### 请描述你建议的实现方案

![image](https://github.com/metersphere/metersphere/assets/160563723/58deb4b1-caef-485f-bbec-47b296810d77)

**Comment by luty2018** [comment]
感谢建议。我们在下周的版本优化。

**Comment by luty2018** [comment]
<img width="1468" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/2163782d-30f4-47df-a936-836b68de50fc">
