### ISSUE TITLE
[BUG]开源MS集成jira，同步缺陷时报错见图

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#28934]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

开源MS集成jira，同步缺陷时报错，jira版本7.10.2，jira插件2.10.7
![d90a5a4d894c729736b3b175bd7f180](https://github.com/metersphere/metersphere/assets/83771182/76a713e1-7605-45c5-a8b0-3e3fbd411a3c)
<img width="1420" alt="9279ca7bf3cb7c5a43509bccf2e2db9" src="https://github.com/metersphere/metersphere/assets/83771182/ed1fba5c-bd1d-43b5-92fc-65284879514c">

### 重现步骤

开源MS集成jira，同步缺陷时报错，jira版本7.10.2，jira插件2.10.7

**Comment by 13290445582** [comment]
您好，目前我们custom_field_issues 表Value字段长度设置为1000，难以避免该问题，v2暂不修改。v3上我们会将会采用超出就截取一部分, 不抛这个异常了，感谢理解与支持。https://github.com/metersphere/metersphere/issues/27594
