### ISSUE TITLE
[BUG]开源版MS集成jira提交bug，同步到jira后人信息是对的，再添加附件，同步到jira了，附件也同步过去了，但是修改人信息同步错误

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#28933]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

开源版MS集成jira后提交bug，同步到jira后人信息是对的，再添加附件，同步到jira了，附件也同步过去了，但是修改人信息同步错误，应该同步修改人的信息，但实际同步了全局默认设置的账号信息。
下图为ms提交的操作人
![dbf214a7885e485c030bb0c4eef5e69](https://github.com/metersphere/metersphere/assets/83771182/2825efeb-9c1d-4fb6-a2e5-663cf79f4971)
下图为jira同步的信息
![d358f26cbe3a7332d7dabc5d0e09440](https://github.com/metersphere/metersphere/assets/83771182/819456b0-4c9a-421a-9d64-19a469f86968)

第三方平台账号已填写。
![ec2b4cdf2c4df1d26c38baa855eb70f](https://github.com/metersphere/metersphere/assets/83771182/8851a6cd-75b6-4885-aa08-4b9428cf6e7e)

### 重现步骤

开源版MS集成jira提交bug，同步到jira后人信息是对的，再添加附件，同步到jira了，附件也同步过去了，但是修改人信息同步错误

**Comment by 13290445582** [comment]
您好，未复现该该情况，建议在新版本测试，可以在v2.10.12环境尝试下，感谢理解。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
