### ISSUE TITLE
[BUG]【消息配置】UI自动化使用企微机器人创建新通知，指定webhook后，配置模版，无法输入内容

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28944]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【消息配置】模块，UI自动化使用企微机器人创建新通知，指定webhook后，打开配置模版，无法输入内容

### 重现步骤

【消息配置】模块，UI自动化 创建新通知，事件指定执行成功，指定接收人，使用企微机器人，指定webhook后，打开配置模版，在页面上无法输入内容

### 期待的正确结果

【消息配置】模块，UI自动化 创建新通知，事件指定执行成功，指定接收人，使用企微机器人，指定webhook后，打开配置模版，可以正常键入内容

### 附加信息

![1708423848686](https://github.com/metersphere/metersphere/assets/145318182/1b97a645-8462-42ec-ab7c-9f4864e3d167)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by luty2018** [comment]
请升级至最新版本查看是否还存在问题

**Comment by fit2cloud-lijiaxin** [comment]
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/16e045b1-a9c7-4226-9059-05f4da632f90">
目前升级到最新版  v2.10.21-lts-f65e0842  ，经测试，UI自动化的 消息通知，选择webhook 后，消息模版依然无法键入

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
