### ISSUE TITLE
[FEATURE]希望编写缺陷内容时，有编号的list中间回车，后面内容的序号可以自动增加。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#28945]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.9lts

### 使用外置数据库

否

### 问题描述

希望编写缺陷内容时，有编号的list中间回车，后面内容的序号可以自动增加。
<img width="773" alt="1aa3b4ebc84f97a3b3a24e866871d1b" src="https://github.com/metersphere/metersphere/assets/83771182/f1d62473-c379-47d5-97c8-ef781e02a450">
希望实现中间回车序号自动增加。
<img width="435" alt="fc564487b3b3e1eea8b075654b14f42" src="https://github.com/metersphere/metersphere/assets/83771182/57f61d6d-50de-4306-9a67-2120a97dea72">

### 重现步骤

希望编写缺陷内容时，有编号的list中间回车，后面内容的序号可以自动增加。

**Comment by luty2018** [comment]
这个在我们v3.0已经实现了哈， 关注v3.0的发布。

**Comment by luty2018** [comment]
v3.0已支持
