### ISSUE TITLE
[BUG]没有任何定时任务，但是系统时不时出现锁表的情况

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#2896]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9版本

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  在系统中有操作执行接口自动化、性能测试多次
2. 打开测试报告，会出现错误信息提示
3. 查看后台日志，提示锁表了。此情况发生很多次了
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/118578760-52293180-b7bf-11eb-822a-e1a02b3b34ad.png)
![image](https://user-images.githubusercontent.com/78218624/118578769-55bcb880-b7bf-11eb-9997-d7e71536536b.png)

**Comment by huangxine** [comment]
重启服务后，进行尝试，发现又出现锁表的情况，具体操作如下：
做了几次不同脚本的压测，其中一个脚本失败，我修改了脚本文件然后在压测，就出现数据表锁定。支持了select * from information_schema.innodb_trx;
 select * from information_schema.innodb_locks;
 select * from information_schema.INNODB_LOCK_WAITS;
也没有发现哪个表锁定了
![image](https://user-images.githubusercontent.com/78218624/118588558-3038aa80-b7d1-11eb-9732-c34ce960481a.png)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，1.10.0版本修改了资源池验证的逻辑，请待新版本发布后查看

**Comment by zyyfit** [comment]
1.10.0版本已发布

**Comment by zyyfit** [comment]
1.10.0版本已发布
