### ISSUE TITLE
[BUG]2019.1版本的IDEA  安装1.0.3的MS插件    Other Settings 下没有 MeterSphere

### ISSUE THREAD

**Issue by haoxsGitHub** [metersphere/metersphere#28975]
### 联系方式

交流群47  图南

### MeterSphere 版本

v2.8.1-da9fa08c

### 使用外置数据库

否

### 问题描述

[BUG]2019.1版本的IDEA  安装1.0.3的MS插件    Other Settings 下没有 MeterSphere

### 重现步骤

[BUG]2019.1版本的IDEA  安装1.0.3的MS插件    Other Settings 下没有 MeterSphere

### 期待的正确结果

[BUG]2019.1版本的IDEA  安装1.0.3的MS插件    可以使用

### 附加信息

![微信图片_20240221153626](https://github.com/metersphere/metersphere/assets/35520003/a6e5ee0f-816d-4063-9f7f-52dd305b6792)
![微信图片_20240221153647](https://github.com/metersphere/metersphere/assets/35520003/780135b9-6a68-451c-b8f1-08838550d2d9)
<img width="686" alt="微信图片_20240221153652" src="https://github.com/metersphere/metersphere/assets/35520003/42fa9a08-3307-4588-b963-5bd01f580de3">

**Comment by 13290445582** [comment]
您好，建议升级下IDEA的版本，较新版本的idea插件无法兼容过低的IDEA版本，我们最新的idea插件更新到了v1.2.7，建议升级。
