### ISSUE TITLE
[BUG] 导入接口-Swagger-URL导入 一直解析失败

### ISSUE THREAD

**Issue by haoxsGitHub** [metersphere/metersphere#28977]
### 联系方式

交流群47  图南

### MeterSphere 版本

v2.8.1-da9fa08c

### 使用外置数据库

否

### 问题描述

导入接口-Swagger-URL导入 一直解析失败     对应Swagger导出的json文件可成功导入   但URL导入就一直失败

### 重现步骤

Swagger复制接口对应地址    在MS接口定义-接口导入-Swagger  粘贴UEL

### 附加信息

![微信图片_20240221154342](https://github.com/metersphere/metersphere/assets/35520003/16ab2c16-2345-453b-aa2e-985db2d4ad65)

**Comment by 13290445582** [comment]
您好，最新版本未复现，建议升级至最新版本测试。请提供下导入的swagger文件与完整的swagger地址。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
