### ISSUE TITLE
[BUG]测试计划报告详情里面有功能用例展示，但是导出后功能用例没有展示

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28983]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

测试计划报告详情里面有功能用例展示，但是导出后功能用例没有展示

### 重现步骤

1. 创建测试计划，关联功能用例并执行，生成测试报告后
2. 在报告详情里面有功能用例展示，但是导出后功能用例没有展示

### 期待的正确结果

期待导出后功能用例有展示

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/a9fe4e3f-f0d7-45b2-a363-3fbb7a936499)
![image](https://github.com/metersphere/metersphere/assets/50016789/dcfbbdae-f566-4e05-b6c6-1af2cd8231b9)

**Comment by 13290445582** [comment]
感谢反馈，已有重复issue，已关联。https://github.com/metersphere/metersphere/issues/28625
