### ISSUE TITLE
[BUG]测试计划报告不显示功能用例，测试时间显示错误

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#28990]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

测试计划报告不显示功能用例，测试时间显示错误

### 重现步骤

1. 指定功能用例关联接口用例
2. 新建测试计划，关联上述功能用例，同步添加关联的接口用例
3. 执行测试计划，待完成后，查看报告统计数据与报告数据，报告不显示功能用例，且测试起始时间相同

### 期待的正确结果

报告数据与报告统计数据一致，且正确

### 附加信息

![1708512580862](https://github.com/metersphere/metersphere/assets/145318182/5a535a56-d000-487d-84fd-0179e33511d1)
![1708512524461](https://github.com/metersphere/metersphere/assets/145318182/23cc7b5b-ad69-4993-9fbd-77c945772b06)
![1708512943459](https://github.com/metersphere/metersphere/assets/145318182/e7686532-b8f5-4359-a422-1e88a5be6fe0)

**Comment by Somebody-JIAN** [comment]
![image](https://github.com/metersphere/metersphere/assets/75963100/ace3cd66-a414-4a70-853f-fd369777cc61)
这里的报告是测试计划实时报告。 不是分批次执行测试计划时的时间。

测试计划实时报告的结束时间展示的是测试计划的实际结束时间，如果没有则不显示； 测试计划批次执行时报告显示的是对应批次的执行时间。两者时间并不一样。

测试计划的实际结束时间是会自动计算的，很多操作会触发计算函数，确定是否结束，结束的话赋予结束时间。

**Comment by fit2cloud-lijiaxin** [comment]
关于执行时间的问题 了解，
还有一个关于，报告中为什么不显示功能用例，请回复下

![image](https://github.com/metersphere/metersphere/assets/145318182/6839daa7-1d73-4822-a20b-9d6c4157647c)

**Comment by 13290445582** [comment]
您好，这个是已知问题，还未修复，后续版本修复，等待排期中，感谢理解。

**Comment by shenkaibo** [comment]
https://github.com/metersphere/metersphere/commit/1ce98885db9544ddc7efc6dca8827b6c947ac399

**Comment by 13290445582** [comment]
已修复，请升级v2.10.14版本。
