### ISSUE TITLE
[BUG]接口自动化，同一个csv, 分别放到两个次数循环使用 第二个循环控制器取数据不是第一条开始，而是第三条

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#28997]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

接口自动化，同一个csv, 分别放到两个次数循环使用 第二个循环控制器取数据不是第一条开始，而是第三条

### 重现步骤

接口自动化，同一个csv, 分别放到两个次数循环使用 第二个循环控制器取数据不是第一条开始，而是第三条
![同一个csv, 分别放到两个次数循环使用](https://github.com/metersphere/metersphere/assets/43202800/9c83a98a-63d9-4409-a37c-92c684e726f8)

### 期待的正确结果

按顺序从1开始取

**Comment by 13290445582** [comment]
您好，这个并不是缺陷，使用同一个CSV，是按照顺序读取，在JMeter中测试也是如此，若不按照顺序读，在执行过程中，可能会产生相同数据导致后面数据无法被读取。
