### ISSUE TITLE
[FEATURE]测试用例批量导入后排序混乱，请优化

### ISSUE THREAD

**Issue by shorile** [metersphere/metersphere#29]
**请描述您的需求或者改进建议.**

通过模板批量导入测试用例，导入后在测试用例排序规则不明，比较乱，建议优化排序

**请描述你建议的实现方案**

参考导入用例模板中的已有排序，对导入后的用例进行排序

**Comment by luty2018** [comment]
1.1版本已支持按导入顺序排序 请更新体验
