### ISSUE TITLE
[BUG]导出用例  功能  导出的excel表中的 用例内容 全部都是没有自动换行的     每次需要人为操作 自动换行 一下。

### ISSUE THREAD

**Issue by harry666666** [metersphere/metersphere#290]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？ 
v1.2.0
**Bug 描述**
简要描述您碰到的问题
[BUG]导出用例  功能  导出的excel表中的 用例内容 全部都是没有自动换行的     每次需要人为操作 自动换行 一下。
**Bug 重现步骤**
1.  勾选写好的测试用例
2.  点击  导出用例
3.  打开导出好的 excel表  查看每列内容（特别是 步骤 与 预期结果列）

**期待的正确结果**
正确情况下应该是什么样的？
期待  每一列都默认选择了自动换行 ，这样具有可读性
**截图**
如果有截图，请附上截图.
![导出用例bug](https://user-images.githubusercontent.com/39684915/91414710-864e7200-e87f-11ea-918d-43921dc442c2.jpg)

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决

**Comment by harry666666** [comment]
辛苦辛苦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BugKing <notifications@github.com&gt;
发送时间: 2020年10月12日 19:30
收件人: metersphere/metersphere <metersphere@noreply.github.com&gt;
抄送: harry666666 <7649088@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[metersphere/metersphere] [BUG]导出用例  功能  导出的excel表中的 用例内容 全部都是没有自动换行的     每次需要人为操作 自动换行 一下。 (#290)





 
你好，新版本中已解决
