### ISSUE TITLE
[FEATURE]  文件管理，链接第三方仓库，输入地址后没有以.git结尾，提示语不准确

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29000]
### MeterSphere 版本

2.10.11

### 请描述您的需求或者改进建议

![644c3e29-0055-4727-90c6-77fd3198a026](https://github.com/metersphere/metersphere/assets/43202800/f3a54d70-dbdb-4ea9-8c29-756656390673)
文件管理，链接第三方仓库，输入地址后没有以.git结尾，提示语不准确

### 请描述你建议的实现方案

可以准确提示需要有格式要求

**Comment by luty2018** [comment]
下个小版本优化一下
