### ISSUE TITLE
连接oracle数据库，不支持多行查询

### ISSUE THREAD

**Issue by lidan1990** [metersphere/metersphere#29004]
### MeterSphere 版本

版本: v2.7.1-9947cfcf

### 联系方式

506572911@qq.com

### 请描述您的需求或者改进建议

支持oracle多行查询

**Comment by luty2018** [comment]
![image](https://github.com/metersphere/metersphere/assets/36292514/b9163ff8-b6f9-4742-8836-daf926c155e2)
试试看看

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
