### ISSUE TITLE
[BUG]连接SQL server数据库时，提示 The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]"

### ISSUE THREAD

**Issue by kungunier** [metersphere/metersphere#29018]
### MeterSphere 版本

v2.9.0-426de152

### 使用外置数据库

否

### 问题描述

连接SQL server数据库时，提示 The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]"

### 重现步骤

选择com.microsoft.sqlserver.jdbc.SQLServerDriver驱动
其他数据库管理工具选择SQL server jtds驱动可以正常链接

**Comment by liqiang-fit2cloud** [comment]
本地无法复现，可能跟你的SQL Server版本不一样。
不过根据https://www.cnblogs.com/chengmuyu/p/16444009.html
https://blog.csdn.net/dangerous317/article/details/122172334
等资料，
已做更改https://github.com/metersphere/alpine-openjdk17-jre/commit/aad8c09e8d215bb3d74ce41c8f89befdb3956cb5
下个版本会包含。

**Comment by kungunier** [comment]
如果我想在当前版本修改JDK，禁用TLS1.*算法配置，应该修改哪个目录文件






| |
刘海龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月22日 17:53 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [metersphere/metersphere] [BUG]连接SQL server数据库时，提示 The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]" (Issue #29018) |

本地无法复现，可能跟你的SQL Server版本不一样。
不过根据https://www.cnblogs.com/chengmuyu/p/16444009.html
https://blog.csdn.net/dangerous317/article/details/122172334
等资料，
***@***.***
下个版本会包含。

**Comment by liqiang-fit2cloud** [comment]
参考这个提交 https://github.com/metersphere/alpine-openjdk17-jre/commit/aad8c09e8d215bb3d74ce41c8f89befdb3956cb5

**Comment by kungunier** [comment]
![20240229-102953](https://github.com/metersphere/metersphere/assets/41564820/8df8667f-0226-4896-987d-fde1dadd8ebe)

我们不太明白，是重新做一个镜像吗？有没有比较详尽的操作步骤

**Comment by kungunier** [comment]
不太明白该如何操作，是要重新新建一个镜像吗？还是替换安装文件中的Dockerfile，有没有详尽的操作可以提供一下

 





| |
刘海龙
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月22日 18:00 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [metersphere/metersphere] [BUG]连接SQL server数据库时，提示 The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]" (Issue #29018) |

参考这个提交 ***@***.***

**Comment by liqiang-fit2cloud** [comment]
升级到最新的[v2.10.12-lts](https://github.com/metersphere/metersphere/releases/tag/v2.10.12-lts)即可。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
