### ISSUE TITLE
[FEATURE] 【接口自动化】全屏编辑，切换左边的请求条目时，右边保留在选定的 tab 页，比如 最常用的是 body

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2901]
**请描述您的需求或者改进建议.**
【接口自动化】全屏编辑，切换左边的请求条目时，右边保留在选定的 tab 页，比如 body

**请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/11580681/118585725-1052b800-b7cc-11eb-8139-4d6011e9fde4.png)

**Comment by xulinde** [comment]
这个暂时优化不了，因为右侧是动态加载的
