### ISSUE TITLE
[BUG] 通过浏览器插件录制文件（任一格式）导入的接口自动化测试，设置定时任务后，无法正常执行，始终pending

### ISSUE THREAD

**Issue by Char-WangXu** [metersphere/metersphere#29035]
### 联系方式

18987434293

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 重现步骤

1. 首先通过浏览器插件录制接口，文件形式jmx或json，导入测试场景中，同时手动创建接口案例场景get2，用于对比，运行环境一栏均不设置
![b9e617a872c5a55669729594ef997b7d](https://github.com/metersphere/metersphere/assets/67749186/c8e7616b-61fb-40ff-b2d6-223474346d7c)

2. 对接口导入的案例及手动创建案例均设置定时任务，导入案例定时任务始终pending，手动创建案例正常执行
![cda3b4460015c89c398aded997346d81](https://github.com/metersphere/metersphere/assets/67749186/213848c8-55b9-4a07-abe8-9e6a6a8e8776)

![439b71686b59220a0edfd8235b644bd8](https://github.com/metersphere/metersphere/assets/67749186/66aca8a3-71ec-43be-b90a-7ce9be1b7c19)

![a4a98bfc7a63c3cc70133cc3c90a64d1](https://github.com/metersphere/metersphere/assets/67749186/350d42fe-6b75-42e5-bcf2-f683d18f3adb)

3. 查看api-test模块jmeter日志，发现空指针异常，根据日志查看代码发现异常为无法获取环境信息
![8d935f4d8e63e6e4aa540e9aa57d5f9a](https://github.com/metersphere/metersphere/assets/67749186/5ab9e531-e917-4be8-9b8e-50f2e1d6f22d)

![image](https://github.com/metersphere/metersphere/assets/67749186/aab59ec8-d5ba-4dda-93ea-dcb769e724ed)

4. 再次编辑浏览器插件导入的案例场景，设置运行环境信息，但手动创建名为get2的场景，依旧保持环境信息设置为空，此时浏览器插件导入的案例场景定时任务执行正常，但保持环境信息设置为空的名为get2的场景始终可以正常执行定时任务
![db64964b534f8ed6ddd3499d00904495](https://github.com/metersphere/metersphere/assets/67749186/97b7e8a1-3df3-4ed2-8591-ad150384c611)

### 期待的正确结果

导入案例与手动创建案例在相同配置（用户界面对比先配置相同）时，使用结果应一致。
使用String.equals()方法时，似乎缺少了判空的处理，逻辑不够严谨。
感谢您的认真阅读，祝好！

**Comment by fit2-zhao** [comment]
感谢 @Char-WangXu 的修复建议， 下版本修复此问题。

**Comment by Char-WangXu** [comment]
![0659376B](https://github.com/metersphere/metersphere/assets/67749186/1a40c319-6446-45ac-a359-077c886a9f58)

**Comment by 13290445582** [comment]
您好，v2.10.12已修复，请升级测试。
