### ISSUE TITLE
[BUG]【页面查询性能问题】接口定义有2万条左右时，页面进入初始化加载有1秒多的响应时间，已排除服务器资源问题

### ISSUE THREAD

**Issue by shenxingqi** [metersphere/metersphere#29033]
### 联系方式

MeterSphere 交流群34中，867296882@qq.com

### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

<img width="339" alt="image" src="https://github.com/metersphere/metersphere/assets/32626470/cc0f3d3f-3247-4045-b04c-b40c6ec29415">
现在已经在接口定义里导入了18000多个接口，发现页面响应变慢了，有1秒多，担心后面接口以及用例增加到3-5万可能会更慢，服务器资源应该是没问题的，内存16g，现在占用70%，部署是单机部署
1、在群里与官方人员咨询后先排查到api-test容器内存占用过高，扩展了容器内存为2g后问题仍未解决
<img width="1301" alt="image" src="https://github.com/metersphere/metersphere/assets/32626470/bd06d1e3-089c-4479-8c57-6ee6b66cf878">

2、尝试创建了其他空间，在其他空间建了几条接口定义，页面响应毫秒级加载是没问题的
3、担心接口定义页面后面发展到5万左右接口时会更慢，然后用例页面可能会更多，达到10万以上的数量

与官方支持人员沟通后确定提issue帮助解决

### 重现步骤

在接口定义里导入2万条左右的接口就能复现问题

### 期待的正确结果

接口定义10万左右的数据量也是毫秒级加载

**Comment by fit2-zhao** [comment]
如果服务器资源充足，可以尝试修改下mysql 的缓冲池大小，具体操作如下：

vim  /opt/metersphere/my.cnf ， 添加 innodb_buffer_pool_size = 实际大小 ；

msctl reload 即生效。

**Comment by shenxingqi** [comment]
已解决，感谢
