### ISSUE TITLE
[FEATURE] 性能测试报错分析，当脚本事务控制器勾选了“generate parent sample”不展示详细内容，希望保留jtl文件供分析

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29069]
### MeterSphere 版本

2.10.11

### 请描述您的需求或者改进建议
性能测试报错分析，当脚本事务控制器勾选了“generate parent sample”不展示详细内容

希望保留 jtl文件，对性能测试过程分析错误原因

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/d67f489d-5b8d-47de-9c96-9d969e1c57d5)

**Comment by zhangzhaox** [comment]
@xhy12 还有一种的方式应该是响应断言，断言失败时通过log输出关键变量信息，请求或响应 关键变量的信息打印 判断失败原因

**Comment by liuruibin** [comment]
jtl下载早期是为了用户验证我们的计算真实性用的，仅针对社区版开启后置监听器后。企业版关闭后置监听器后不会产生jtl。

即便现在使用老版本社区版的方式来保存jtl，下载jtl的内容也不会有事务控制器之下的具体请求的详细信息，整个事务控制器只有一条结果。
