### ISSUE TITLE
[BUG]从2.1.1升级到2.10.11后数据库丢失，备份恢复后运行报错

### ISSUE THREAD

**Issue by Xingac1999** [metersphere/metersphere#29062]
### 联系方式

2280930812@qq.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

更新后有数据丢失，使用备份数据进行数据还原后项目运行报错，显示如下：
![1708913256757](https://github.com/metersphere/metersphere/assets/45863249/99d4a96f-b215-4ebc-8a0d-6dec3f76ea8c)

### 重现步骤

从2.1.1升级到2.10.11
数据库运行unhealthy，按照[该链接](https://askubuntu.com/questions/1427384/cant-start-mysql-after-upgrade)修改后数据库启动
界面功能正常，数据有丢失
将备份数据进行还原
界面报错

**Comment by Xingac1999** [comment]
报错请求：
![1708914478494](https://github.com/metersphere/metersphere/assets/45863249/66d03014-cc08-478f-8617-8b4013340e66)
![1708914499800](https://github.com/metersphere/metersphere/assets/45863249/c6adad15-422d-4f8e-b5cf-a0aad51e8022)

**Comment by Xingac1999** [comment]
重新部署metersphere，数据库导入成功，msctl status全部healthy，登陆后界面卡死，一直在ip:8081/#/与ip:8081/#/setting/personsetting之间跳转，然后网页崩溃

https://github.com/metersphere/metersphere/assets/45863249/4768a6ef-dc69-4c12-af94-47e3ea77cda2

**Comment by 13290445582** [comment]
您好，清理下浏览器缓存或打开无痕模式或更换浏览器尝试下，ip：端口。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
