### ISSUE TITLE
[FEATURE] 测试计划 中 场景与场景实现变量共享

### ISSUE THREAD

**Issue by apolloyun** [metersphere/metersphere#29092]
### MeterSphere 版本

v2.10.11-lts

### 联系方式

229808484@qq.com

### 请描述您的需求或者改进建议

测试计划中引入多个场景，希望测试计划中的场景可以实现变量共享，按照目前的功能会将变量设置成环境变量，这样会导致环境变量的数量越来越多，而且后面环境变量会有很多无效的变量，环境变量后期管理起来也会非常的麻烦。jmeter 自身可以实现跨线程组传递参数。

**Comment by luty2018** [comment]
目前为了确保场景的成功率和正确率， 我们进行了变量的隔离。如果不进行隔离，同名变量这种情况会导致场景执行结果不可控哦。
