### ISSUE TITLE
[BUG]在编辑测试用例的时候，  若某步骤对应的预期结果 不填， 则导出excel表中的预期结果会自动填充 null。

### ISSUE THREAD

**Issue by harry666666** [metersphere/metersphere#291]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.0
**Bug 描述**
简要描述您碰到的问题
在编辑测试用例的时候，  若某步骤对应的预期结果 不填， 则导出excel表中的预期结果会自动填充 null。
**Bug 重现步骤**
1.  编写测试用例   预期结果不填
2.  选择导出该条测试用例
3. 打开导出的excel表，查看 预期结果 列内容
 

**期待的正确结果**
正确情况下应该是什么样的？
期望结果 ：单步骤对应的预期结果不填的话  就不现实任何内容  为空 即可
![导出用例bug](https://user-images.githubusercontent.com/39684915/91415147-2f956800-e880-11ea-95cc-80345f903483.jpg)

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
新版本中已解决
