### ISSUE TITLE
[BUG] 功能用例编写页面，切换tab页保存，没有弹出是否保存提示，直接关闭网页点x 也没有提示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29105]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

1、功能用例编写页面，切换tab页保存，没有弹出是否保存提示，
2、编辑功能用例页面直接关闭网页点x 也没有提示

![image](https://github.com/metersphere/metersphere/assets/43202800/c025ede3-1975-4de2-ba9e-25105a024cca)

### 重现步骤

1、功能用例编写页面，切换tab页保存，没有弹出是否保存提示，
2、编辑功能用例页面直接关闭网页点x 也没有提示

### 期待的正确结果

1、功能用例编辑页面，切换tab页 弹出保存提醒
2、直接关闭网页x 应该弹出提示
![image](https://github.com/metersphere/metersphere/assets/43202800/6bf87424-23f6-4f00-921b-765cbd1a3768)

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by Hyyfit** [comment]
感谢反馈，v3已覆盖该缺陷，请关注后续版本发布；
