### ISSUE TITLE
[BUG]【用例评审】多人评审，在脑图模式下，一个人评审通过，评审结果就通过了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#29117]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【用例评审】多人评审，在脑图模式下，一个人评审通过，评审结果就通过了。

### 重现步骤

【用例评审】多人评审，在脑图模式下，一个人评审通过，评审结果就通过了。
![image](https://github.com/metersphere/metersphere/assets/104960608/d74547b1-b2de-4bf7-9e22-cf0b4e41985e)
![image](https://github.com/metersphere/metersphere/assets/104960608/be06e989-1e90-412f-a89a-fe5f96ecf694)
![image](https://github.com/metersphere/metersphere/assets/104960608/143640cb-0f6a-41e8-b9fb-5287392ae680)

**Comment by 13290445582** [comment]
您好，脑图上的规则是这样的，在脑图内评审为强制操作，一人评审通过即为通过，一人评审不通过即为不通过，感谢理解与支持。

**Comment by 2lipan** [comment]
同一个评审，两种模式，走不一样的流程，这应该在【评审通过标准】选择【多人评审】时给个提示。
![image](https://github.com/metersphere/metersphere/assets/104960608/5c837858-45de-40ce-a2ec-1ce3ba6c3237)
