### ISSUE TITLE
[BUG]自动化场景，修改数据源的问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#29132]
### 联系方式

15275908957

### MeterSphere 版本

2.10.11-lts

### 使用外置数据库

否

### 问题描述

自动化场景里面，自定义请求中的前置操作，选择前置sql，数据源选择db1，在运行环境中更新后出现问题。

### 重现步骤

1.在运行环境中创建两个数据源，db1，db2。
2.接口自动化创建一个自定义请求，并且在前置脚本中使用前置sql选择第一个数据源，如db1.
3.在运行环境数据源中删除db1，然后重新创建db1。
4.问题复现，在接口自动化中，默认使用了db2.

**Comment by 13290445582** [comment]
您好，您删除db1数据源后，自然会切换至db2数据源，当重新再创建了db1数据源，此时已经是使用的db2数据源，当然是不会切换到db1数据源。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
