### ISSUE TITLE
[FEATURE] 缺陷的创建人需要加个感叹号说明下谁同步过来的，创建人是谁，非jira缺陷创建人

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29149]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

缺陷的创建人需要加个感叹号说明下谁同步过来的，创建人是谁，非jira缺陷创建人

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/597f1949-c686-40fa-9e0d-fdb41dfdca06)

**Comment by fit2cloud-yaochunrong** [comment]
或者这里的创建人是否可以改为同步人/平台创建人；创建人是三方平台的时候是空的，metersphere用户创建的时候有值；、
![image](https://github.com/metersphere/metersphere/assets/103925124/26983b71-20c6-4253-81ce-4b72b555e45e)

**Comment by luty2018** [comment]
这个会在6月的小版本增加

**Comment by luty2018** [comment]
<img width="887" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/03f022f8-35d1-4810-a33e-41b3f3b3fbc4">
