### ISSUE TITLE
[BUG]  【性能测试】未勾选删除报告权限，导致用户不能进行导出报告操作

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29147]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

未勾选删除报告权限，导致用户不能进行导出报告操作

### 重现步骤

项目成员的权限，未勾选删除报告权限
![image](https://github.com/metersphere/metersphere/assets/103925124/d65c675e-f58f-446d-b2cb-b20d0df51bea)
![9e11bf0b-ac84-4293-996a-b52cf48daece](https://github.com/metersphere/metersphere/assets/103925124/bd6f452c-54b8-47fd-b07c-a1d7ecd8974b)

### 期待的正确结果

【删除报告】权限不影响导出报告操作

**Comment by fit2cloud-yaochunrong** [comment]
![1709114268427](https://github.com/metersphere/metersphere/assets/103925124/7665b64f-1c4d-4d56-83d7-14dff0eabe6b)
没有删除报告的权限，这一栏都不能点击

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by fit2cloud-yaochunrong** [comment]
企业用户提出，麻烦排期修复下

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
