### ISSUE TITLE
[BUG]在脚本里定义了数组变动，但是for循环无法识别这个变量。for循环只能识别后置脚本提取的数组类型的变动，对于cvs里的数据也不识别

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#29164]
### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

[BUG]在脚本里定义了数组变动，但是for循环无法识别这个变量。for循环只能识别后置脚本提取的数组类型的变动，对于cvs里的数据也不识别

### 重现步骤

[BUG]在脚本里定义了数组变动，但是for循环无法识别这个变量。for循环只能识别后置脚本提取的数组类型的变动，对于cvs里的数据也不识别

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/78218624/86f4f5c3-075c-4ca8-8d38-2dca25a9f5c1)

![image](https://github.com/metersphere/metersphere/assets/78218624/b6c9e412-3642-4847-861a-08b82e9b9162)

**Comment by 13290445582** [comment]
您好，暂不支持，ForEach 循环的是 v_index 这种格式的数据 类似 v_1 ; v_2 这样；提取的上下文变量也是这种格式，而非数组对象。感谢您的理解与支持。
