### ISSUE TITLE
[QUESTION]场景用例中步骤的URI与接口定义一致，但接口覆盖率未统计到

### ISSUE THREAD

**Issue by fizzhu97** [metersphere/metersphere#29161]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/161595150/dc05069c-f810-42fc-b5c0-7f3bf2918452)
一、通过接口列表导入来，新增场景用例步骤，可以正常统计到已覆盖中
二、通过自定义来，新增场景用例步骤，可以正常统计到已覆盖中
三、通过复制步骤或场景，再修改步骤中的URI为新接口的URI，此步骤对应新URI接口未统计到已覆盖中
四、通过自定义新增场景用例步骤，保存过后，再修改为其他接口的URI，此步骤对应新URI接口未统计到已覆盖中

附件是导出的场景用例，尝试过把“scenarioDefinition”中\\"url\\":\\"(.*?)\\"的值替换为\\"path\\":\\"(.*?)\\"中的值，再导入时，已覆盖接口仅会新增1-2个接口。同一个导出的文件，再次导入，已覆盖的对应接口列表都可能是不相同的个接口。
[11.json](https://github.com/metersphere/metersphere/files/14433891/11.json)

**Comment by luty2018** [comment]
感谢反馈，这个问题我们已经复现，下个小版本修复

**Comment by fizzhu97** [comment]
@luty2018 没有设置里程碑，是因为还没纳入计划么？
![image](https://github.com/metersphere/metersphere/assets/161595150/513bf713-f341-4528-bad2-894aacfc54e7)

**Comment by luty2018** [comment]
会在3月28号的版本发布哈。

**Comment by 13290445582** [comment]
已修复，请升级版本。

**Comment by fizzhu97** [comment]
已经升级到v2.10.13-lts版本
但是，在接口测试 - 首页，查看接口覆盖率，还是不对。是历史场景用例的接口覆盖率不会自动纠正？
需要修改历史场景用例中的请求URL吗？
![image](https://github.com/metersphere/metersphere/assets/161595150/91c2b144-96fe-4674-9a6e-73bcc316188f)

**Comment by fizzhu97** [comment]
已经升级到v2.10.13-lts版本
但是，在接口测试 - 首页，查看接口覆盖率，还是不对。是历史场景用例的接口覆盖率不会自动纠正？
需要修改历史场景用例中的请求URL吗？
![image](https://github.com/metersphere/metersphere/assets/161595150/11f486d9-de5e-4c31-9167-2780e5c508de)

**Comment by fizzhu97** [comment]
@13290445582 帮忙看看

**Comment by 13290445582** [comment]
您好，刚又复现了下您的四个步骤，这四种情况都是可以统计到已覆盖中的。
<img width="274" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/afb7d39d-fab2-4b02-99b9-5865de76114f">

**Comment by fizzhu97** [comment]
您按问题描述里的完整步骤回归是通过的，因为是重新建的用例。
但之前版本已经存在问题的场景用例步骤(接口)：
1、升级版本后，未统计到接口覆盖率；
2、对有问题的场景用例步骤进行修改URI，也不会统计到接口覆盖率。

之前已经写好的场景用例（可能数据库已经存储的url,path是不一致的）
升级完版本后，依然是没统计到接口覆盖率的，对吗？那旧用例怎么能恢复接口的覆盖率

**Comment by fizzhu97** [comment]
还有一个场景遗漏了，针对旧的场景用例：
1、添加步骤，未统计新的URI到覆盖率；
2、复制旧的场景用例，再来修改，未统计新的URI到覆盖率；

**Comment by fizzhu97** [comment]
@13290445582
