### ISSUE TITLE
[FEATURE] 接口测试，测试计划被api调用时，能否根据保存的重试策略进行重试

### ISSUE THREAD

**Issue by lvchunyu1993** [metersphere/metersphere#29169]
### MeterSphere 版本

 v2.10.11-lts-a580bd0a

### 联系方式

MeterSphere 交流群44 吕小雨

### 请描述您的需求或者改进建议

目前在metersphere平台测试计划中配置了失败重试，但是测试计划被jenkins调用时，并不会对失败的case进行重试，能否增加这一功能，谢谢

**Comment by luty2018** [comment]
感谢反馈， 已重现该问题， 会在下个小版本修复。

**Comment by 13290445582** [comment]
已修复，请升级并更新最新插件。
