### ISSUE TITLE
[FEATURE] 优化： 性能测试，监控promql 下拉会有默认值，希望将这个值设置为 配置项。

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29166]
### MeterSphere 版本

2.10.11

### 请描述您的需求或者改进建议

promql 设置的标准和ms默认语句不同，所以每次配置测试监控项的时候都需要 手动充填比较麻烦

不同单位需求可能不同，有可能不仅限于这几项的默认值

期望：将监控语句可以设置为自定义配置项，再测试的时候可以快速选择
![image](https://github.com/metersphere/metersphere/assets/43202800/16052bbe-d232-43c3-afcc-65ed59d0cebf)

### 请描述你建议的实现方案

期望：将监控语句可以设置为自定义配置项，再测试的时候可以快速选择

**Comment by liuruibin** [comment]
v2中不再进行优化，v3我们会重新设计这里
