### ISSUE TITLE
[BUG]性能测试压力配置-资源池 修改后展示还是之前的选择,但是实际切换成功了，console报错

### ISSUE THREAD

**Issue by wuzhenrong** [metersphere/metersphere#29177]
### 联系方式

MeterSphere 交流群32、不能说的秘密、736110640@qq.com

### MeterSphere 版本

版本:   v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

资源池的下拉切换有点问题展示问题，看着没切换成功，但是是用的local，切换完了之后，我的这个性能测试的 压力配置页面就加载不出来了
![WechatIMG123](https://github.com/metersphere/metersphere/assets/16410401/b4ff072b-6592-4c64-a21e-346093a1f1db)
![WechatIMG121](https://github.com/metersphere/metersphere/assets/16410401/0fbb11dd-d6b3-4eb0-b13e-378e5c7f3568)

https://github.com/metersphere/metersphere/assets/16410401/2f3fef17-16ae-4ba7-902e-1694cd28a1bb

![image](https://github.com/metersphere/metersphere/assets/16410401/ec46dc19-fbc4-416f-bcb8-6132f3f0643c)

### 重现步骤

性能测试-场景编辑-压力配置，点击 资源池的下拉切换

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by wuzhenrong** [comment]
问下会在哪个版本修复？我目前的性能测试场景，每次一切换就打不开了，一直loading，都不敢用了

> 感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
已修复，请升级最新版本～
