### ISSUE TITLE
[FEATURE] 建议切换项目位置可以自定义顺序，当前名称相同的也不展示在一起不便于查看同类

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29170]
### MeterSphere 版本

v2.10.6

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/79577571/7fa1ee71-41f0-43f2-addb-92475cfe30aa)

### 请描述你建议的实现方案

期望可以改动顺序（支持管理员统一全局排序/个人排序）

**Comment by luty2018** [comment]
您好， 我们会在v2.10.13中修改为默认按首字母排序。暂不支持自定义排序功能。

**Comment by qian-kui** [comment]
请问设定编号 001-xxx  001-xxx 这种也会排列在一起吧？然后才显示 002-xxx ，003-xxx

**Comment by 13290445582** [comment]
您好，已实现，请升级。
