### ISSUE TITLE
[QUESTION]关于场景/测试计划的测试报告配置了7天定时清理，但数据库表文件仍然太大

### ISSUE THREAD

**Issue by fizzhu97** [metersphere/metersphere#29180]
### 测试报告配置为7天定期清理，界面仅显示7天内的，但数据库中的api_scenario_report相关表却仍然一天天变大

# pwd
/data/metersphere/data/mysql/metersphere

-rw-r----- 1 polkitd input 112K Oct  7 18:49 api_scenario_report_detail.ibd
-rw-r----- 1 polkitd input 716M Feb 28 20:00 api_scenario_report.ibd
-rw-r----- 1 polkitd input  36G Feb 28 19:00 api_scenario_report_result.ibd          //这个表太大了，设置了下图的7天定时清理，还是一天天变大。
-rw-r----- 1 polkitd input 840M Feb 28 20:00 api_scenario_report_structure.ibd

![image](https://github.com/metersphere/metersphere/assets/161595150/45dc423c-0510-4cc7-a646-f460eafe74f2)

![image](https://github.com/metersphere/metersphere/assets/161595150/f20090e2-7836-4d98-80d7-e3b4b8e2ff0f)

**Comment by liuruibin** [comment]
可以参考这个issue操作：https://github.com/metersphere/metersphere/issues/27831#issuecomment-1951509824
