### ISSUE TITLE
[BUG] 多步骤场景测试中，用例的后续操作中设置运行环境通用变量不起作用

### ISSUE THREAD

**Issue by cncal** [metersphere/metersphere#29195]
### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

在我的场景测试中，第一步先登录，登录用例的后续操作是先提取登录接口返回的 token，然后将其设置为运行环境的通用变量 Token（全局变量）：

<img width="1139" alt="image" src="https://github.com/metersphere/metersphere/assets/23520240/43b10fd0-e7fc-40ac-8c1e-b31ac8f9612a">

第二步修改登录密码，这个用例需要全局变量 Token 作为 AUTH(HTTP Request Header) 的值。但是场景测试中，发现第二步的请求中 AUTH 为空，运行环境的通用变量 Token 也为空：

<img width="1178" alt="image" src="https://github.com/metersphere/metersphere/assets/23520240/e635a570-6901-4eee-9999-63a32b6fd157">

通过调试日志发现，第一步的后续操作是执行了的，但全局变量的设置是不起作用的。我禁用第二步，只调试第一步，发现全局变量又可以设置上。以上过程可稳定复现。

### 重现步骤

如问题描述所述。

**Comment by 13290445582** [comment]
您好，建议您升级最新版本测试下。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
