### ISSUE TITLE
[BUG]【接口测试】sql语句，从text切换到table，没显示数据。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#29194]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【接口测试】sql语句，从text切换到table，没显示数据。

### 重现步骤

【接口测试】sql语句，从text切换到table，没显示数据。
![image](https://github.com/metersphere/metersphere/assets/104960608/d54b8d39-264d-43f0-9a5a-cee2a7201a40)
![image](https://github.com/metersphere/metersphere/assets/104960608/3d351558-c4c7-4eb8-9f58-27592efe828a)

**Comment by 13290445582** [comment]
感谢反馈，计划后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
