### ISSUE TITLE
[FEATURE]建议 项目及模块 可统计测试用例 数量 

### ISSUE THREAD

**Issue by harry666666** [metersphere/metersphere#292]
**请描述您的需求或者改进建议.**
 建议 项目及模块 可统计测试用例 数量 

**请描述你建议的实现方案**   见附图
![统计测试用例条数](https://user-images.githubusercontent.com/39684915/91415408-99157680-e880-11ea-9d9f-0d01350ff8bc.jpg)

**Comment by zyyfit** [comment]
最新版本v1.7.2，功能用例和接口用例都有左侧目录树，可以选择全部用例或子目录，查看右侧列表用例数量（右下角翻页区域，共X条）
