### ISSUE TITLE
离线安装包下载路径好像失效了，打不开

### ISSUE THREAD

**Issue by blackmaxer** [metersphere/metersphere#29202]
### 请描述您的问题

如题

**Comment by fit2-zhao** [comment]
请问是哪个版本的离线包

**Comment by blackmaxer** [comment]
> 请问是哪个版本的离线包

[v2.10.12-lts](https://github.com/metersphere/metersphere/releases/tag/v2.10.12-lts)
然后文档里的离线包下载地址打开也是空页面
https://community.fit2cloud.com/#/products/metersphere/downloads

**Comment by blackmaxer** [comment]
网络限制了，我这边的问题。。。
