### ISSUE TITLE
[FEATURE]接口测试，接口case编辑页面提供打开对应接口定义的功能

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#29206]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

接口case编辑页面提供打开对应接口定义的功能

### 请描述你建议的实现方案

case编辑页面上方接口名字展示接口ID，点击是新窗口打开接口定义页面，与自动化场景页面打开引用接口一致

**Comment by luty2018** [comment]
感谢建议， 我们会在下个小版本支持这个功能。

**Comment by 13290445582** [comment]
您好，已支持，请升级。
