### ISSUE TITLE
[FEATURE]接口测试，接口自动化场景编辑页面批量操作支持所选步骤快捷生成新场景

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#29207]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

UI自动化中由类似功能。选择步骤组成新场景有利于在编写端到端场景时识别可复用场景，快速形成新场景并快捷引用

### 请描述你建议的实现方案

多选步骤后提供“创建新场景”操作，确认提交后自动在当前场景对应位置替换成引用的场景

**Comment by luty2018** [comment]
感谢建议， 这是个很棒的需求， 我们会在v3.0规划此功能， 可以关注后续的发布。
