### ISSUE TITLE
[FEATURE]接口自动化，引用case和场景中的各项禁用启用操作支持独立修改

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#29204]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

很多时候在引用场景或者用例时只需要做一点点禁用启用操作，但目前就需要引用不同的场景，或者复制一个场景。引用和复制的优点无法同时享有。增加了场景编排的复杂性，无法有效利用原子场景和用例

### 请描述你建议的实现方案

被引用的case和场景的禁用启用按钮可以操作，保存原场景或者case时可以选择是否同步禁用启用状态

**Comment by luty2018** [comment]
感谢反馈，这个我们在v3.0已经支持了，可以关注v3.0的发布。
