### ISSUE TITLE
[FEATURE]接口测试，用例页面提供用户自定义变量设置功能

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#29205]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

单接口测试用例存在两种运行方式
1.单独调试或者运行
2.在自动化测试场景中编排执行
很多时候都是需要一些输入参数的，目前调试时在环境变量中设置，自动化场景中由上游接口提取。会造成要不就是环境配置中全局变量过多，要不就是接口编排只能使用case复制功能，后期维护难度高

### 请描述你建议的实现方案

case编辑页面，请求中增加自定义用户变量tab，类似于前置脚本。支持接口单独调试时使用自己的变量值，场景中使用场景传递的变量值

**Comment by luty2018** [comment]
感谢反馈， 这是一个很好的建议， 我们会认真做好设计。
