### ISSUE TITLE
[FEATURE]接口测试，接口自动化中编辑页面引用和复制可以进行切换

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#29208]
### MeterSphere 版本

2.10.10

### 请描述您的需求或者改进建议

在插入步骤时会选错，然后就得删除步骤重新操作。

### 请描述你建议的实现方案

引用和复制标识可以点击并切换，支持批量操作就更好了

**Comment by luty2018** [comment]
感谢建议， 这个需求我们会在v3.0版本讨论规划。
