### ISSUE TITLE
[BUG]接口测试，请求体为json数组时，开启JSON-SCHEMA，发出去的请求体为空，关闭JSON-SCHEMA，json-object变为字符串

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29213]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

接口测试，请求体为json数组时，开启JSON-SCHEMA，发出去的请求体为空，关闭JSON-SCHEMA，json-object变为字符串

### 重现步骤

![企业微信截图_17092775847774](https://github.com/metersphere/metersphere/assets/103925124/1d3d884d-72ba-40a7-aa3d-f95a289a9504)
![image](https://github.com/metersphere/metersphere/assets/103925124/3071712f-e219-4b4f-a41e-6e407b8d5357)
![image](https://github.com/metersphere/metersphere/assets/103925124/383b1c60-5e61-4087-9a4c-ed543f3969a4)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该问题已复现。介于目前首要任务是开发V3，v2版本的问题解决时间会有延迟，解决时间待定。感谢理解和支持。

**Comment by fit2cloud-yaochunrong** [comment]
企业用户提出缺陷，且影响测试，麻烦尽快修复下

**Comment by youliyuan-fit2cloud** [comment]
v2.10.15-lts已修复
