### ISSUE TITLE
[BUG]【页面跳转】点击某些按钮会跳转到系统设置-个人信息页面

### ISSUE THREAD

**Issue by tangonly** [metersphere/metersphere#29215]
### 联系方式

mingchao.tang@foxmail.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

点击某些按钮，比如测试跟踪首页的用例数量统计图标中的按钮时，会跳转到系统设置-个人信息页面
其它有问题的按钮：功能用例查看（偶发）等

### 重现步骤

测试跟踪首页的用例数量统计图标中的按钮，会跳转到系统设置-个人信息页面

**Comment by youliyuan-fit2cloud** [comment]
你好，出现这种情况和权限设置有关，请查看下用户所属的用户组权限是否有变更，如果再次遇到请附上前后端日志的信息，感谢理解和支持～

**Comment by tangonly** [comment]
用户组的权限没有变更，我附上录屏，视频里面可以看见复现步骤及浏览器控制台日志，请问后台日志怎么获取，要获取哪个模块的后台日志
[MeterSphere - Google Chrome 2024-03-08 10-06-32.zip](https://github.com/metersphere/metersphere/files/14532467/MeterSphere.-.Google.Chrome.2024-03-08.10-06-32.zip)

**Comment by youliyuan-fit2cloud** [comment]
收到，我们后续版本再优化一下。

**Comment by tangonly** [comment]
好的，请尽快处理，这个缺陷目前对我们的正常使用有较大的影响，请修复后通知我

**Comment by tangonly** [comment]
您好，这个bug在v2.10.14-lts版本修复了吗

**Comment by youliyuan-fit2cloud** [comment]
抱歉，该问题不是必现，我们暂时计划后续的版本中尝试优化一下，感谢理解和支持。

**Comment by tangonly** [comment]
您好，这个bug在v2.10.15-lts版本修复了吗

**Comment by youliyuan-fit2cloud** [comment]
> 您好，这个bug在v2.10.15-lts版本修复了吗

非常抱歉，还没有。该问题出现的概率很小，最近都忙于 v3 的开发和测试，但是我们尽量在下个月修复。感谢理解和支持。

**Comment by 13290445582** [comment]
您好，小概率事件，建议升级至最新版本，也可更新下浏览器尝试下，有稳定复现情况时请再反馈，感谢您的理解与支持。
