### ISSUE TITLE
[FEATURE] 增加测试报告和缺陷的独立链接

### ISSUE THREAD

**Issue by ShinChven** [metersphere/metersphere#2921]
**请描述您的需求或者改进建议.**

希望能为`测试报告`和`缺陷`增加独立链接，这样测试完以后可以引用到其他平台，比如 gitlab/github 的 issue 中，以提醒和串联工作流程。

**请描述你建议的实现方案**

为每个`测试报告`和`缺陷`增加独立的URL。

**Comment by xulinde** [comment]
已在后续版本规划中
