### ISSUE TITLE
[BUG]【接口测试 】-【首页】的统计页面里，点击过去7天有更新的接口时，跳转不了

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#29211]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

【接口测试 】-【首页】的统计页面里，点击过去7天有更新的接口时，跳转不了

### 重现步骤

【接口测试 】-【首页】的统计页面里，点击过去7天有更新的接口时，跳转不了,报错如图所示
![11ea3fd6-017a-4da1-bd1f-d1d4e2159f13](https://github.com/metersphere/metersphere/assets/103627487/6bbcfcd3-c01a-4126-bde5-23ee237a5a23)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.15-lts中已修复。
