### ISSUE TITLE
[FEATURE]【需求】【缺陷管理】缺陷之间可以进行关联

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29224]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

18291878104@163.com

### 请描述您的需求或者改进建议

【需求场景】
1、登记了多个缺陷
2、排查后发现其中几个有关联关系，需要进行关联，就像缺陷关联用例那样
![image](https://github.com/metersphere/metersphere/assets/107530175/328f6dd8-9ab2-449f-8703-789f3c77c8dc)
或者：一个问题提给了安卓端，小程序/web/ios端 也需要配合修改，这个时候会把安卓的问题复制修改里面内容走给其它端，但这几个端问题都要修改完成后才能进行验证，一班这种情况我们会在系统中将几个问题进行关联；

**Comment by luty2018** [comment]
是缺陷内容重复的意思吗?

**Comment by ywhkhb** [comment]
不是重复，开发定位问题后觉得这几个问题根因可能相同，关联到一起处理发自我的手机-------- 原始邮件 --------发件人： LuoTing ***@***.***>日期： 2024年3月4日周一 14:41收件人： metersphere/metersphere ***@***.***>抄送： ywhkhb ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [FEATURE]【需求】【缺陷管理】缺陷之间可以进行关联 (Issue #29224)
是缺陷内容重复的意思吗?

**Comment by luty2018** [comment]
那还是属于重复的范畴， 一般这种我们会在评论中贴上关联的缺陷的地址。然后将重复的关闭。

**Comment by ywhkhb** [comment]
或者：一个问题提给了安卓端，小程序/web/ios端 也需要配合修改，这个时候会把安卓的问题复制修改里面内容走给其它端，但这几个端问题都要修改完成后才能进行验证，一般这种情况我们会在系统中将几个问题进行关联；

**Comment by ywhkhb** [comment]
不同缺陷的链接地址是相同的，不支持复制链接：
![image](https://github.com/metersphere/metersphere/assets/107530175/0aa51511-d6cd-4ee3-a328-06c060fbf25c)

**Comment by luty2018** [comment]
我们在v3支持直接复制URL链接，可以后续升级使用
