### ISSUE TITLE
[FEATURE]【需求】【缺陷管理】缺陷中关联的用例支持标注测试结果

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29227]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

18291878104@163.com

### 请描述您的需求或者改进建议

缺陷中已实现了关联用例，
①但不能直接点开查看用例，如果可以直接查看对工程师会更友好，对开发来说可以作为参考进行自测；
②进一步优化：关联的用例后面可以标注测试结果：
一般一个缺陷开发修复后需要自测，然后测试同学再进行验收，希望在后面添加开发自测结果和测试验收结果两项（类比测试计划中的用例执行）

**Comment by luty2018** [comment]
v3.0支持在关联用例中点击用例ID新开页面打开查看用例详情
