### ISSUE TITLE
[FEATURE]【优化】【测试计划】当用例库中的用例有更新时，测试计划中的用例在没有任何提醒情况下会被直接更新

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29225]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

18291878104@163.com

### 请描述您的需求或者改进建议

【操作场景】
1、当前用例库用例适用于1.0版本，然后创建一个1.0版本测试计划，拉取库里的用例
2、当前 测试计划进行中或已完成了，然后2.0需求开发中，用例库中某几条用例进行了更新
然后会出现：
1、此时已被执行的用例直接被更新了——应该不能直接更新，可以有个标识提醒是否需要更新
2、1.0版本对外发布后可能出现了问题，然后追溯1.0测试计划，发现显示的用例和当时测试的不一致

### 请描述你建议的实现方案

当测试计划已经创建，此时计划中的用例被其他人在用例库中更新，测试计划中的用例不要直接更新，可以给一个明显标识提醒到测试人员当前执行的哪些用例有更新，确认是否需要同步，比如被修改的该条用例显示红色，有个更新按钮
![image](https://github.com/metersphere/metersphere/assets/107530175/5d103b4f-6e8f-4796-9ede-2c96ee448ab8)

**Comment by luty2018** [comment]
是的， 目前的设计是引用关系，保证每次执行都是执行的最新用例
