### ISSUE TITLE
[FEATURE]【需求】【测试计划】希望测试计划中的用例支持带执行结果等信息导出

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29226]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

18291878104@163.com

### 请描述您的需求或者改进建议

测试计划执行完成后，里面的用例目前不支持导出，希望可以像用例库中一样，选择用例和字段进行导出
![image](https://github.com/metersphere/metersphere/assets/107530175/32b482d2-8fe9-43cc-aa39-4e84c8922f17)

**Comment by luty2018** [comment]
这个功能已经规划到v3.0版本中了， 可以专注v3.0版本的发布。
