### ISSUE TITLE
[BUG] UI测试-打开网页报链接超时，截图显示访问成功【很多用户反馈】

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29231]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

UI测试-打开网页报链接超时，截图显示访问成功

### 重现步骤

UI测试-打开网页报链接超时，截图显示访问成功
找一个网页，metersphere访问时打开主网页不报错，里面的背景图，或者某些重大js访问不到（网络不通）
用metersphere打开网页操作并执行
查看测试报告如下图，**截图成功，只是背景图未展示完全，导致需要设置<忽略异常并继续执行>才能继续往下的步骤**
![企业微信截图_17092824528898](https://github.com/metersphere/metersphere/assets/103925124/8c5c6584-f204-4700-ad6b-80378f359dbc)
**查百度此报错原因为：selenium打开网页后，即使页面已经加载出来可以操作了，但是浏览器地址栏旁边还是在转圈，后面的代码也一直无法往下执行。其实大部分原因是由于静态文件加载太慢或者外链的CDN挂了导致的。**
![image](https://github.com/metersphere/metersphere/assets/103925124/3b32d76a-f335-4042-8eb1-b78cb87e246e)

**背景图访问不到导致的链接异常，还算明显可以排查到，有些F12的报错也会影响到打开网页的成功/失败**

**Comment by liuruibin** [comment]
网络导致的卡顿我们我无法预知，也无法解决。

处理方法也很简单，grid到目标网站联通即可，cdn这些手段也同此理
