### ISSUE TITLE
[BUG] IDEA同步到MS平台，Method识别问题

### ISSUE THREAD

**Issue by tangyin9593** [metersphere/metersphere#29233]
### 联系方式

18221797082

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

Java代码Controller层， api使用@RequestMapping(value = "", name = "", method = {RequestMethod.DELETE,RequestMethod.POST}) 方式的时候，识别不出来这个delete和POST方法，展示出来的只是GET方法，这不是我们想要的，我测试过其他好几个api管理工具，都是支持的。

### 重现步骤

1. 写好接口，method使用支持delete 和 post
<img width="999" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/5afa30c9-ba1b-4f78-a9c6-aded21d32939">

2. 同步成功
<img width="385" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/ddbc8514-18c4-4da6-8c1b-4868fbab4d91">

3. 查看ms平台，发现并没有识别到这个删除教室的api
<img width="1565" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/bc63f5db-5bc7-4fdb-a87a-82fba3ff5ed9">

4. 改一下代码， 我只写一个delete的method，并同步ms平台
<img width="814" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/41a292d0-3701-4375-a1ce-03c90096bce0">

5. 查看ms平台，发现是get方法请求，并没有识别出是delete方法请求
<img width="857" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/cfd2d498-7fa1-4215-85f6-78dea210bf8a">

### 期待的正确结果

能正确同步出对应类型的方法

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没出现这个情况。请问下插件版本是否是最新的 v1.2.7 ？
![image](https://github.com/metersphere/metersphere/assets/54612864/a430a78d-e458-4189-8bb9-e1af9b49f8c8)

**Comment by tangyin9593** [comment]
是的， 版本是最新的。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/bf1de192-05ba-4139-86e3-ab1aa191db44)
不能这么写，method 只支持一个。感谢理解和支持～
