### ISSUE TITLE
[BUG]【接口定义】修改接口的 path 后，case 里面的 path 没有变化，也无法修改

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#2925]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题
修改接口的 path 后，case 里面的 path 没有变化，也无法修改

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
case 里面的 path，同步变化，可修改

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/118624125-7440a500-b7fb-11eb-85fb-97036876a725.png)

**Comment by zyyfit** [comment]
您好，用例的信息不会跟随接口变动而变动的，要修改用例路径的话可以批量勾选，然后批量编辑

![image](https://user-images.githubusercontent.com/73461316/118691605-d4573b80-b83b-11eb-81e6-5f61044c1cfe.png)
