### ISSUE TITLE
[BUG]缺陷管理中关联测试用例后，用例关联测试计划，但是首页测试计划遗留缺陷统计没有新增

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#29254]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

缺陷管理中关联测试用例后，用例关联测试计划，但是首页测试计划遗留缺陷统计没有新增

### 重现步骤

1. 创建缺陷
2. 缺陷关联已有的测试用例
3. 创建测试计划
4. 测试计划关联功能用例（之前关联过缺陷的用例）
5. 首页测试计划遗留缺陷统计没有新增

### 期待的正确结果

首页测试计划遗留缺陷统计新增缺陷数量

### 相关日志输出

```shell
无
```

### 附加信息

![1709547775086](https://github.com/metersphere/metersphere/assets/50016789/faf3066d-d797-4d99-a308-60823750d48f)
![1709547775098](https://github.com/metersphere/metersphere/assets/50016789/d994bd66-1a65-4de6-9021-1533ac1d4d15)
![1709547775111](https://github.com/metersphere/metersphere/assets/50016789/c722a4e9-2d88-4a7f-adc1-76ab513b596e)

**Comment by 13290445582** [comment]
您好，测试计划遗留缺陷统计的统计规则是，统计在测试计划内已关联的用例后添加/关联的缺陷，在测试计划外关联的缺陷是不会统计到测试计划内的，所以这个数据没有新增是正确的。
