### ISSUE TITLE
[BUG] 复制多个测试计划，使用批量执行测试计划，测试计划任务执行不对

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#29264]
### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

复制测试计划A,将复制的测试计划与原测试计划进行批量执行，执行方式选择并行，执行的测试任务不对

### 重现步骤

1、复制测试计划A为测试计划B
2、将测试计划A和测试计划B进行批量执行、执行方式选择 并行
3、观察执行任务是否正确

### 期待的正确结果

批量执行测试计划任务正确

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/4ba6f100-1896-4687-ba72-36dc4a8ecfcb)
![image](https://github.com/metersphere/metersphere/assets/45531073/bfdb6563-28be-40f8-b04b-f0b11dab36dd)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
