### ISSUE TITLE
[FEATURE]API全量导出功能html或word的优雅格式文档，目前勉强通过修改API的方式达到

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#29262]
### MeterSphere 版本

V2.10.12

### 联系方式

群14-亲山留水

### 请描述您的需求或者改进建议

1、可参考showdoc，全量导出功能或选择功能模块导出功能完善，自定义选择导出swagger文件可暂时过度
2、目前支持的单API的HTML文件下载，使用场景有限，常用的导出场景是基于交付物的全量或者自动定义选择模式

### 请描述你建议的实现方案

我目前是通过修改API请求参数全量导出swagger文件，然后通过https://github.com/JMCuixy/swagger2word 转换word文档

**Comment by luty2018** [comment]
感谢建议， 这个我们有在v3规划哈
