### ISSUE TITLE
v2.10.12-lts win10安装， 执行 install.sh后 报错了

### ISSUE THREAD

**Issue by blackmaxer** [metersphere/metersphere#29261]
### 请描述您的问题

版本号 [v2.10.12-lts](https://github.com/metersphere/metersphere/releases/tag/v2.10.12-lts)

 Container gateway  Creating
 Container eureka  Creating
 Container redis  Creating
 Container ms-prometheus  Creating
 Container mysql  Creating
 Container minio  Creating
 Container kafka  Creating
 Container ms-node-controller  Creating
Error response from daemon: failed to mount local volume: mount /opt/metersphere/conf/prometheus:/var/lib/docker/volumes/metersphere_ms-prometheus-conf/_data, flags: 0x1000: no such file or directory

**Comment by blackmaxer** [comment]
我看win10下安装的ubuntu是有这个目录的 /opt/metersphere/conf/prometheus

**Comment by liuruibin** [comment]
重新安装可以解决吗

**Comment by blackmaxer** [comment]
装过几次，都是同样的问题

**Comment by liuruibin** [comment]
试试虚拟机呢，或者体验一下我们的cloud版免去安装过程享受所有功能 https://www.metersphere.com/

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。

**Comment by ihavechocolate** [comment]
在docker-compose的配置文件中加入driver: local
如：
volumes:
  ms-mysql-data:
    driver: local
    driver_opts:
      type: none
      device: ${MS_BASE}/metersphere/data/mysql
      o: bind
