### ISSUE TITLE
[BUG]导入swagger报错

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#2928]
**MeterSphere 版本**
   MeterSphere 版本是1.9.2
**Bug 描述**
  导入swagger报错

**期待的正确结果**
  swagger导入正确

**截图**
swagger格式是如下test.txt里面的内容格式：
![image](https://user-images.githubusercontent.com/37204403/118625922-01d0c480-b7fd-11eb-9d40-f51340580950.png)
[test.txt](https://github.com/metersphere/metersphere/files/6500027/test.txt)

**Comment by xulinde** [comment]
未复现该问题，方便发下您的文件吗

**Comment by wangeqi** [comment]
swagger的路径，不能用浏览器里输入框里的路径，需要用swagger打开后左上角的一个-api的路径

**Comment by SloanGao** [comment]
我是使用就是左上角打开的一个api路径，然后使用上传文件的方式也不行，其他的swagger我用同样方式导入都可以，就这个swagger不行
@xulinde ，上面的txt文件附件中就有swagger内容

**Comment by zyyfit** [comment]
> 我是使用就是左上角打开的一个api路径，然后使用上传文件的方式也不行，其他的swagger我用同样方式导入都可以，就这个swagger不行
> @xulinde ，上面的txt文件附件中就有swagger内容

使用上面的文件确实报错了，我们排查一下问题

**Comment by xulinde** [comment]
原因是格式错误
![image](https://user-images.githubusercontent.com/64065190/124553667-9784e980-de67-11eb-8def-ce3b9fb35c28.png)
