### ISSUE TITLE
[BUG]提交缺陷与jira进行关联报错

### ISSUE THREAD

**Issue by xiangziyun2009** [metersphere/metersphere#293]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2.0
**Bug 描述**
提交缺陷与jira进行关联报错

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
**截图**
如果有截图，请附上截图.

![OG`UF PS}ZOHPY29FA)BZI6](https://user-images.githubusercontent.com/23206552/91415737-0f19dd80-e881-11ea-84a8-cde69bfc39d9.png)
![F}S)${79A2ZGVFV(A X(N@Y](https://user-images.githubusercontent.com/23206552/91415780-193bdc00-e881-11ea-8c7a-94771b1ec638.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决
