### ISSUE TITLE
[FEATURE]项目管理-编辑项目-需求类型支持多选

### ISSUE THREAD

**Issue by junjunjune** [metersphere/metersphere#29303]
### MeterSphere 版本

v2.10.12-lts-a7d7c194

### 联系方式

junjunjune626@163.com

### 请描述您的需求或者改进建议

项目管理-编辑项目-需求类型支持多选，例如集成Jira，可以支持多选多种需求类型，包括story，task，bug等，方便项目下测试用例关联需求时可以关联不同类型的需求。
![关联需求支持多选](https://github.com/metersphere/metersphere/assets/44460196/35f9672c-2523-4d74-9861-1b0ff041ad41)

**Comment by luty2018** [comment]
v2暂时不会支持了，在v3版本中对这里进行了插件化， 可以在v3版本中修改插件来支持。
