### ISSUE TITLE
[BUG] 环境配置中根据模块作为启用条件，当勾选父目录时，会自动勾选子目录，但如果在父目录下面新增子目录，不能自动添加子目录

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#29332]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

环境配置中根据模块作为启用条件，当勾选父目录时，会自动勾选子目录，但如果在父目录下面新增子目录，不能自动添加子目录。

https://github.com/metersphere/metersphere/assets/33945037/277fb8df-2dad-4554-9bde-108942715c10

视频中目录比较少，如果有上百个目录的话，这样每次都需要手动添加，会很麻烦的。

### 重现步骤

同视频

**Comment by 13290445582** [comment]
您好，作为后新增的子目录，在环境配置中已保存的环境肯定不会自动添加该子目录。若子目录很多，建议可以再次勾选父目录达到全选子目录的效果。

**Comment by hao65103940** [comment]
这个是不太合理的，环境配置作为一个平台的配置功能，正常逻辑应该配置之后，应该不需要频繁更改才对，况且目录有很多，子节点和父节点目录都很多，每次添加都需要一个一个修改，操作起来太麻烦

**Comment by 13290445582** [comment]
您好，V2暂不修改了，我们将规划到V3的第二个版本支持。

**Comment by luty2018** [comment]
v3.5已支持
