### ISSUE TITLE
[BUG]【文件管理】普通用户启用了所有文件管理权限，但不能创建模块

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29350]
### 联系方式

18291878104@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

【文件管理】普通用户启用了所有文件管理权限，但不能创建模块，只有管理员才可以

### 重现步骤

1、给当前用户组启用全部文件管理权限
![871798b6204c18088fc3c275a36968a](https://github.com/metersphere/metersphere/assets/107530175/514feda7-8d59-4c6c-8db6-2276cd0beed4)
2、登录后进入文件管理，发现不显示（创建、编辑、删除）模块的按钮，
![622c18051cad0c83b5e4e65c28057b4](https://github.com/metersphere/metersphere/assets/107530175/84ed413d-c0e7-40c8-9971-80fa04774346)
只有用管理员账号才显示
<img width="430" alt="15990d6452779b30ec8b89e075784b4" src="https://github.com/metersphere/metersphere/assets/107530175/95ce3499-cf51-456c-98b3-2b3fe578fdd0">

### 期待的正确结果

不管哪种用户，赋了文件管理的所有权限应该能创建、编辑、删除模块
![image](https://github.com/metersphere/metersphere/assets/107530175/59fa42ea-9e80-47dc-afc5-379b3e2376c8)

**Comment by ywhkhb** [comment]
同一个账号，全选的文件管理权限；
3.7号：不显示创建、编辑、删除模块的按钮
3.8号：显示操作按钮，然后同一个电脑，再登录另一个人账号，也是全选的文件管理权限，不显示操作按钮
有点奇怪呢

**Comment by ywhkhb** [comment]
3.7号：给账号再添加了系统的项目管理员账号，发现不显示编辑按钮；
3.8号：又显示编辑按钮了，然后再给其它账号添加系统项目管理员权限，重新登陆后显示编辑按钮

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by Hyyfit** [comment]
感谢反馈，v3已覆盖该缺陷，请关注后续版本发布；
