### ISSUE TITLE
[BUG] UI场景被复制为新场景，源场景修改后新场景不会同步更新

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#29361]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

某个UI大场景的步骤中存在引用其他子场景，复制该子场景为另一步骤，修改原场景内容后，被复制的子场景没有同步更新。

### 重现步骤

1、创建一个新场景，引用其他已存在的A场景为子步骤B
2、在新场景内复制B子步骤得到C子步骤，保存新场景
3、修改被引用的原场景A的内容，保存
4、查看C步骤的内容没有更新

### 期待的正确结果

引用的场景步骤应该被更新

### 附加信息

新场景：
<img width="401" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/e3b4aae8-c88c-4f86-b1e7-232df033a75b">

被引用的场景修改后：
<img width="1320" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/4b3d9145-60f7-4916-a121-4583b59b3761">

新场景步骤：
<img width="1163" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/88bc2596-9787-4948-87e8-f7871f93d5db">

<img width="1028" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/3bff7da5-d77e-453e-b580-f2e9e308a5f8">

**Comment by Hyyfit** [comment]
v3 会统一处理
