### ISSUE TITLE
[BUG]v2.10.12, MeterSphere Dubbo协议测试抛异常

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#29362]
### 联系方式

王进

### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

v2.10.12, MeterSphere Dubbo协议测试抛异常

### 重现步骤

详细测试步骤见如下金山文档
【金山文档】 某客户Dubbo Bug
https://kdocs.cn/l/ccqOuIGvxSoC

### 期待的正确结果

MS应该能像Jmeter那样测试客户的dubbo服务。
MS所在服务器与被测服务之间端口已开。

### 相关日志输出

```shell
日志文件详见：
【金山文档】 2024-03-7
https://kdocs.cn/l/cgHDn9io32bS
```

客户这边用的是nacos，我们在验证的时候，nacos, zookeeper，留空，都验证了，始终无法执行get provider list，每次执行都会一直转圈圈

### 附加信息

1. 另外，还有别的问题，见下图：
<img width="1258" alt="c413773359599deadab138e187a575a" src="https://github.com/metersphere/metersphere/assets/76033005/2a7ad284-50ea-4637-9e54-7629b6eb08f8">
<img width="204" alt="ee5a549e264dec17f66a826ca0dc327" src="https://github.com/metersphere/metersphere/assets/76033005/1cdb2649-3f11-409f-a236-6be124130c84">

客户昨天在尝试用dubbo测试他们的接口后，啥也没干。MS平台 一天 产生了 三十多个日志文件，给相同的ip发送 dubbo信息。
这个是昨天的，48MB，全是发送dubbo的
【金山文档】 2024-03-6
https://kdocs.cn/l/coZZlda8sM5K

**Comment by 35plus** [comment]
这个问题暂时先不处理，下午和客户又做了些测试，目前看很有可能和客户的网络环境有关。

**Comment by 35plus** [comment]
今天再次验证，确认是bug。
1. 在MS里，接口自动化场景，创建一个和本地jmeter dubbo测试脚本，完全一样的 包含dubbo 自定义请求的脚本。
2. 导出该场景为jmeter脚本
3. 在本地用 jmeter 5.4.1打开，并且本地的 lib/ext/包含jmeter-plugins-dubbo-2.7.17-jar-with-dependencies.jar的对应jar包。
4. 点击测试，控制台抛出异常。这个异常也刚好解释了，为什么在MS上 没办法get provdier list。
[dubbo_test.zip](https://github.com/metersphere/metersphere/files/14536396/dubbo_test.zip)
<img width="1091" alt="1709891122447" src="https://github.com/metersphere/metersphere/assets/76033005/4d72474f-c67e-4de1-9d28-fc1a4bd1b2f2">

**Comment by 35plus** [comment]
除此以外，还做了如下验证：
1. 用本地jmeter（lib/ext下包含jmeter-plugins-dubbo-2.7.17-jar-with-dependencies.jar），调试一个 完全一样的dubbo请求
2. 测试是OK的，能发送和接收dubbo请求。
3. 但是，相同的jmeter，打开MS生成的jmx脚本，就会抛出异常。
下面这个是本地调试的jmeter脚本
[Dubbo Sample.zip](https://github.com/metersphere/metersphere/files/14536446/Dubbo.Sample.zip)

**Comment by 35plus** [comment]
这个问题，卡着客户现在的测试工作，希望研发团队能尽快处理一下。

**Comment by youliyuan-fit2cloud** [comment]
经沟通，我们测试环境无法复现，该问题无法处理。建议先排查当前使用dubbo环境，如果有其他进展请随时联系我们，感谢理解和支持。
