### ISSUE TITLE
[BUG]场景导入，场景列表显示的用户名，场景导入页面显示的用户id 不一致。客户那边的id是飞书同步过来的一串数字，导致识别不了人员

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29383]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

场景导入，场景列表显示的用户名，场景导入页面显示的用户id 不一致。
![场景导入，场景列表显示的用户名，场景导入页面显示的用户id 不一致](https://github.com/metersphere/metersphere/assets/43202800/bb291541-14ff-4d9a-9074-69c4294b3693)

客户那边的id是飞书同步过来的一串数字，导致识别不了人员
![image](https://github.com/metersphere/metersphere/assets/43202800/ef8e10de-058d-43ca-b9fc-c70042de0e5b)

### 重现步骤

接口测试编排导入场景，场景列表显示的用户名，场景导入页面显示的用户id 不一致。

### 期待的正确结果

导入场景列表显示为用户名

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复，导入场景列表显示为用户名。

**Comment by xhy12** [comment]
多久修复呢？没有Milestone

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
