### ISSUE TITLE
[BUG] 性能测试--监控详情的流量单位错误

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#2938]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题
性能测试的监控详情种，出口流量和入口流量的单位为MB/s，12000MB/s这数值偏离实际。应该是kbps符合常理。

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/24548477/118659114-9e0bc300-b81f-11eb-9eda-0e65385e5de9.png)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
1.9.3已修复，改成了kb/s
