### ISSUE TITLE
[BUG]用户ID包含特殊字符，导致访问用户/成员列表报错

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29385]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

用户ID包含特殊字符，导致访问用户/成员列表报错

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/63705ae8-db56-49ce-af07-95b36f9a0180)
![1709869807367](https://github.com/metersphere/metersphere/assets/103925124/6c700a5c-7b81-4ced-aa35-ac95dd506ae2)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by Hyyfit** [comment]
感谢反馈，v3已覆盖该缺陷，请关注后续版本发布；

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
