### ISSUE TITLE
[BUG]场景 接口步骤 后续点击 另存为接口定义-》创建接口，ms自动写入的url和当前填写的接口路径不一致

### ISSUE THREAD

**Issue by wuzhenrong** [metersphere/metersphere#29399]
### MeterSphere 版本

版本:   v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

场景中，某接口-》更多-〉创建接口，提示接口已存在，其实是因为 自动写入的url 不对，不是当前接口的url
/nio/site/steward/space/pad/v1/in/upccning-stat
/nio/site/steward/space/pad/v1/in/list-nio-site
见以下gif+截图
![自动创建接口](https://github.com/metersphere/metersphere/assets/16410401/30f79bb2-49d1-496b-9cac-7bbe5afdbdd6)

![image](https://github.com/metersphere/metersphere/assets/16410401/6dd7041a-3b8d-4b9d-b39d-fb765f6e0ecb)
![image](https://github.com/metersphere/metersphere/assets/16410401/ff91171b-59b6-4b56-b651-625bb1102b72)

### 重现步骤

场景中，某接口-》更多-〉创建接口

### 期待的正确结果

url自动带入

**Comment by 13290445582** [comment]
您好，已复现一种复现场景，复制产生的请求，另存为接口时url不一致，请确认您的接口是这样产生的吗，还是具体什么步骤产生的请求有这种问题？

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
