### ISSUE TITLE
[BUG]【用例评审状态】本地用例“导入更新”后评审状态不会从“通过”变成“重新提审”

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29396]
### 联系方式

18291878104@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

本地用例“导入更新”后评审状态不会从“通过”变成“重新提审”

### 重现步骤

对已评审的用例线上直接编辑，用例状态会从“通过”变成“重新提审”，但导出的用例本地修改后再重新导入，导入时选择“导入更新”，评审状态不会从“通过”变成“重新提审”
![image](https://github.com/metersphere/metersphere/assets/107530175/1810dca4-7369-4816-add8-dbf497046220)

### 期待的正确结果

已评审通过的用例只要被更新，无论哪种方式，都应该被置为“重新提审”

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by Hyyfit** [comment]
感谢反馈，v3已覆盖该缺陷，请关注后续版本发布；

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
