### ISSUE TITLE
[QUESTION]开发环境的jmeter镜像8082端口如何启动的?

### ISSUE THREAD

**Issue by wangjunkai1982** [metersphere/metersphere#294]
开发环境的jmeter镜像8082端口如何启动的?
docker run -e BOOTSTRAP_SERVERS=192.168.1.56:9092 -e LOG_TOPIC=metersphere-log registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:0.0.7
one shot run.
Aug 28, 2020 6:53:54 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
2020-08-28 06:53:54,557 kafka-producer-network-thread | producer-1 WARN Recursive logging from [org.apache.kafka.clients.NetworkClient] for appender [Kafka].
2020-08-28 06:53:54,571 kafka-producer-network-thread | producer-1 WARN Recursive logging from [org.apache.kafka.clients.Metadata] for appender [Kafka].
An error occurred: The file /test/*.jmx doesn't exist or can't be opened

创建Local测试环境的时候需要调用http://localhost:8082/status这个健康状态  这个8082在本地开发环境是怎么启动起来的 如何创建k8s分布式压测环境文档中也没有提到

我的配置文件如下
cat /opt/metersphere/conf
## DATABASE
spring.datasource.url=jdbc:mysql://192.168.1.55:3306/metersphere?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

## KAFKA
kafka.partitions=1
kafka.replicas=1
kafka.topic=metersphere
kafka.bootstrap-servers=192.168.1.56:9092
kafka.log.topic=metersphere-log
run.mode=local
jmeter.image=registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:0.0.7

**Comment by wangzhen-fit2cloud** [comment]
你好，测试节点需要部署运行 node-controller 这个组件，jmeter 容器是由该组件动态启动的
