### ISSUE TITLE
[BUG] 50个API组成的压测场景脚本，联系压测6小时场景，在运行3小时左右后，页面上查询数据不更新，DS消费服务和node压测容器正常负载消费

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#29419]
### MeterSphere 版本

v2.1.12-lts

### 使用外置数据库

是

### 问题描述

2024-03-10 16:17:59,856 [qtp335928592-1242] WARN  i.m.service.PerformanceReportService 114 - Method[getContent][get report result error]
![image](https://github.com/metersphere/metersphere/assets/82088551/21822672-a601-4644-8ebc-959eedb1504e)
设置运行的6小时场景，在运行3个多小时后页面的查询数据就不更新了，检查node节点压测容器正常压测，DS消费服务也在正常消费

![image](https://github.com/metersphere/metersphere/assets/82088551/3cd6f777-a4fe-4d72-a225-368878be5b84)
![image](https://github.com/metersphere/metersphere/assets/82088551/3fecfc30-a324-43c6-81a1-2a39244271de)

### 重现步骤

约50个API组成的压测场景，设置运行6小时场景，仅运行3小时左右，页面查询数据就不更新了，对应性能微服务未见明显异常
下面的日志都是一直刷新
2024-03-10 16:17:59,856 [qtp335928592-1242] WARN  i.m.service.PerformanceReportService 114 - Method[getContent][get report result error]

**Comment by liuruibin** [comment]
您好，欢迎来使用我们的企业版[https://metersphere.io/。开源版确实一直有此问题，在企业版我们的算法进行了更新优化，建议您使用企业版，感谢理解。](https://metersphere.io/%E3%80%82%E5%BC%80%E6%BA%90%E7%89%88%E7%A1%AE%E5%AE%9E%E4%B8%80%E7%9B%B4%E6%9C%89%E6%AD%A4%E9%97%AE%E9%A2%98%EF%BC%8C%E5%9C%A8%E4%BC%81%E4%B8%9A%E7%89%88%E6%88%91%E4%BB%AC%E7%9A%84%E7%AE%97%E6%B3%95%E8%BF%9B%E8%A1%8C%E4%BA%86%E6%9B%B4%E6%96%B0%E4%BC%98%E5%8C%96%EF%BC%8C%E5%BB%BA%E8%AE%AE%E6%82%A8%E4%BD%BF%E7%94%A8%E4%BC%81%E4%B8%9A%E7%89%88%EF%BC%8C%E6%84%9F%E8%B0%A2%E7%90%86%E8%A7%A3%E3%80%82)

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
