### ISSUE TITLE
[BUG] 工作台，我关注的，缺陷管理。显示的处理人是用户id区分不出来，用例管理-缺陷管理显示的是用户名称。期望展示为用名称

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29420]
### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

1、工作台，我关注的，缺陷管理。显示的处理人是用户id区分不出来，
2、用例管理-缺陷管理显示的是用户名称。

![image](https://github.com/metersphere/metersphere/assets/43202800/44f5e523-fe0d-4f71-8569-cab373b8438a)

期望展示为用名称

### 重现步骤

用例管理-缺陷：创建缺陷并关注
切换到工作台，我关注的，缺陷管理。显示的处理人是用户id区分不出来，

### 期待的正确结果

期望展示为用名称

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by xhy12** [comment]
这个什么时候修复呢 ，一直没更新

**Comment by 13290445582** [comment]
您好，v2.10.22版本已修复此问题，请升级。
