### ISSUE TITLE
[FEATURE]集成idea的plugin提供自定义配置

### ISSUE THREAD

**Issue by Noel443** [metersphere/metersphere#29443]
### MeterSphere 版本

v2.10.12-lts

### 联系方式

lyh131893049@163.com

### 请描述您的需求或者改进建议

idea安装了metersphere plugin，能导出接口定义的时候通过一些配置设置参数是否为必须还是非必需的，类似easy api这种可以通过对参数加注解实现导出接口定义的时候是必须的，或者提供相关配置

### 请描述你建议的实现方案

提供相关配置

### 附加信息

![Uploading WechatIMG6.jpg…]()

**Comment by luty2018** [comment]
感谢反馈， 这个我已记录， 会在v3.0安排规划。

**Comment by fit2-zhao** [comment]
https://plugins.jetbrains.com/plugin/24867-metersphere-api-debugger/edit/versions/stable/600994
https://github.com/metersphere/metersphere-idea-plugin/releases/tag/v3.2.0

@Noel443  可以试试这个版本是否能满足你的需求。
