### ISSUE TITLE
[BUG]【缺陷管理】【高级搜素】高级搜索不属于某条件时查询出来出来的都是属于该条件的

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29458]
### 联系方式

18291878104@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

高级搜索不属于某条件时查询出来出来的都是属于该条件的

### 重现步骤

1、搜索条件设置分支，不属于，dev，然后查询
2、查询出来的数据都是属于dev的缺陷
![image](https://github.com/metersphere/metersphere/assets/107530175/281ecf2d-1c0c-40cf-b554-72dfc1c93637)

### 期待的正确结果

查询出不属于dev的缺陷

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
