### ISSUE TITLE
[FEATURE]建议增加账号密码防暴力破解能力

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#29470]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

 客户端在限定的时间段内有多次连续尝试登录失败时，可以执行如下策略中的一种：
策略一：锁定帐号；
策略二：锁定IP；
策略三：认证间隔时间依次加倍。采用这种方式时，用户可以不设置自动锁定。
策略四：验证码登录
适用于：操作员帐号、最终用户帐号。 

### 重现步骤

 客户端在限定的时间段内有多次连续尝试登录失败时，可以执行如下策略中的一种：
策略一：锁定帐号；
策略二：锁定IP；
策略三：认证间隔时间依次加倍。采用这种方式时，用户可以不设置自动锁定。
策略四：验证码登录
适用于：操作员帐号、最终用户帐号。

**Comment by luty2018** [comment]
暂时没有规划
