### ISSUE TITLE
[BUG]项目管理员不能修改

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#29509]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

1、使用超级管理员账号创建了一个项目，项目管理员默认取得当前登录用户
2，【项目管理】-【成员】指定其他账户为项目管理员，当前项目的管理员变更失败

### 重现步骤

1、使用超级管理员账号创建了一个项目，项目管理员默认取得当前登录用户
2，【项目管理】-【成员】指定其他账户为项目管理员
3. 查看【项目管理】 项目管理员仍为当前登录用户

### 期待的正确结果

项目管理员仍为【成员】中，设置用户组为“项目管理员”的用户

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/4ade8896-3d54-43e1-982f-09911008fc67)
![image](https://github.com/metersphere/metersphere/assets/145318182/790ec06e-de3c-4754-abea-4737ac48ad99)
![image](https://github.com/metersphere/metersphere/assets/145318182/9f4b5bb1-03a8-4f46-8a1a-30ef470096ef)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by liuruibin** [comment]
使用其他有权限的用户可以调整，这个问题不再修改了
