### ISSUE TITLE
[BUG]【测试计划】筛选用例后全选导入时概率会报错

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29502]
### 联系方式

18291878104@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

【bug】【测试计划】筛选用例后全选导入概率会报错:Internal exception occured, please check logs or contactadministrator

### 重现步骤

1、测试计划中点击关联用例
2、左侧选择模块“回归”，然后高级搜索两个条件（是否已自动化：是，软固件：C1000_上，C2000_上）
3、筛选完成后全选，然后确定导入
![image](https://github.com/metersphere/metersphere/assets/107530175/bbe74986-37a3-4e32-bc87-0f0bc1bc27ea)
日志：上传附件
[info.log](https://github.com/metersphere/metersphere/files/14596207/info.log)

**Comment by 13290445582** [comment]
您好，按照筛选后全选导入未复现该问题。

**Comment by ywhkhb** [comment]
概率的，只要一出现这段时间基本每次出现现，然后少选点用例导入不会报错；
有提供附件info.log

**Comment by 13290445582** [comment]
您好，是不是全选时选中的有脏数据，按照您的步骤操作，筛选全选导入未产生这个错误，看错误信息跟数据库内容有关，可能是选中的脏数据。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
