### ISSUE TITLE
[BUG]环境配置-http配置-当设置了启用条件为模块时，在test中调试请求时，request未带上域名

### ISSUE THREAD

**Issue by mike041** [metersphere/metersphere#29513]
### MeterSphere 版本

v2.0.0-81da75b6

### 使用外置数据库

否

### 问题描述

环境配置-http配置-当设置了启用条件为模块时，在test中调试请求时，request未带上域名
![image](https://github.com/metersphere/metersphere/assets/56382648/305fcb6f-95c1-464c-ab5b-bddef50462f6)
![image](https://github.com/metersphere/metersphere/assets/56382648/0ec2cc11-cbfb-471d-b5f9-02517d6eef3e)

### 重现步骤

环境配置-http配置，配置一个启用条件为某个模块的域名
然后找一个该模块下的接口，在test中选择该环境并执行
可以在请求内容中看到域名是空的

### 期待的正确结果

目前在case中正式测试能带上域名
预期在test调试时也能带上

**Comment by 13290445582** [comment]
感谢反馈，最新版本未复现该问题，建议您升级最新版本使用。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
