### ISSUE TITLE
[BUG] 场景列表执行接口自动化时，场景里面的接口脚本参数没有传入环境变量中

### ISSUE THREAD

**Issue by wk-886** [metersphere/metersphere#29514]
### 联系方式

13871101476

### MeterSphere 版本

 v2.10.12-lts-a7d7c194

### 使用外置数据库

否

### 问题描述

接口自动化列表内点击执行接口时，脚本参数可以传递到环境变量中，从而被下一个接口引用；但是在场景列表执行时参数没有传递到环境变量中

### 重现步骤

比如我再1接口后置脚本里面写了自增参数，每执行一次该接口会把自增参数传入环境列表中，单独执行该接口都是正常的传参，但是在场景列表页面执行整个场景时就没有传参

### 期待的正确结果

执行场景时能正常传参

### 相关日志输出

```shell
无
```

### 附加信息

请尽快修复该问题，或者有其他操作方法可以解决

**Comment by wk-886** [comment]
![Uploading 场景列表页面执行时里面的接口脚本参数没有传递到环境变量中.png…]()

**Comment by 13290445582** [comment]
您好，本地测试可以正常传参到环境变量，您可提供下您操作的录屏并导出场景看下。

**Comment by wk-886** [comment]
[Uploading Metersphere_Scenario_HR.json…]()

**Comment by wk-886** [comment]
Uploading 场景列表执行脚本时参数没有传到环境变量中.mp4…

**Comment by wk-886** [comment]
我上传了场景文件和操作视频，你们能看见吗，总感觉这平台有问题，一直显示文件Uploading中

**Comment by 13290445582** [comment]
您好，还是看不到，或者您打个压缩包发我邮箱：yicheng.wang@fit2cloud.com

**Comment by wk-886** [comment]
邮件已发送

**Comment by 13290445582** [comment]
您好，已经看过您的视频，您中途停止调试场景，所以传参失败，等场景执行完是可以正常传参的，已确认该逻辑，感谢您的理解与支持。
