### ISSUE TITLE
[Question]缺陷模板的字段问题

### ISSUE THREAD

**Issue by zhang3292556** [metersphere/metersphere#29518]
集成禅道服务的项目，设置缺陷模板的时候，应怎样设置一个字段，使在创建缺陷时，让这一字段展示在禅道维护好的所属模块，我应该怎样设置？
![image](https://github.com/metersphere/metersphere/assets/163403180/5f3ed1f3-daeb-4825-aa81-f1d2f3ebe141)
MS版本：v2.10.12-its  禅道版本：12.5.3

**Comment by luty2018** [comment]
https://metersphere.io/docs/v2.x/faq/service_integration/?h=%E7%A6%85%E9%81%93#3-path_info
看看这个是否可以解决你的问题
