### ISSUE TITLE
[BUG] 接口设置前置脚本传参到环境变量时，当前接口引用该参数不是最新的，而是上一次的参数

### ISSUE THREAD

**Issue by wk-886** [metersphere/metersphere#29515]
### 联系方式

13871101476

### MeterSphere 版本

v2.10.12-lts-a7d7c194

### 使用外置数据库

否

### 问题描述

比如我在当前接口前置操作编写了一个脚本，该脚本产生的参数需要传入环境列表中；但是实际执行接口时，从环境列表获取前置脚本参数不是当前的的值，而是上一次的值，导致接口执行总是报错。

### 重现步骤

1

### 期待的正确结果

1

### 相关日志输出

```shell
1
```

### 附加信息

这种问题需要尽快处理，都没法使用

**Comment by 13290445582** [comment]
您好，检查下您的脚本是这样写的吗，按照图中写是可以取到的。若丢掉第二行的脚本，则是您描述的那种取到上一次值的现象。

**Comment by wk-886** [comment]
我没有看到您说的图在哪

**Comment by 13290445582** [comment]
您好，这个图片。
<img width="922" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/6d21078c-7be5-436e-86b1-54f6b3b96dd2">

**Comment by wk-886** [comment]
噢 我们以为只要第一行，因为之前的版本我们这边点击设置环境参数时，都只显示第二行，但是第二行根本就没有用，所以都是用的第一行。看你们这次更新的版本已经自动推送了两行，我试一下。

**Comment by wk-886** [comment]
刚按照您说添加了第二行代码，但是使用前置脚本时生成的参数还是无法传入到环境变量中，但是放在后置脚本中就可以传入，我发你邮件吧，给您看下视频操作

**Comment by 13290445582** [comment]
您好，我本地测试了下，前置也是没问题的，您看下您后置脚本禁用了吗？或者弄个新的场景单独测试下前置脚本。

**Comment by wk-886** [comment]
后置脚本禁用是啥意思？我是前置脚本有问题，不是后置脚本啊

**Comment by 13290445582** [comment]
我的意思是看你视频里的场景，同时存在前置脚本和后置脚本，是不是后置脚本也启用了，所以把前置脚本的值覆盖了。

**Comment by wk-886** [comment]
该不会是同一个接口不能同时启用前置和后置脚本吧？我把后置脚本关掉后前置脚本的传参就正常了，我后置脚本与前置脚本不是一个代码，所以不存在覆盖的情况

**Comment by wk-886** [comment]
恢复正常后，我再重新操作发现复现不了之前的情况了

**Comment by 13290445582** [comment]
您好，一个接口可以同时启用前置和后置脚本，这里是一直正常使用的，若无其他问题，将关闭该issue，感谢您的理解与支持。

**Comment by wk-886** [comment]
待观察
