### ISSUE TITLE
[BUG]场景加了foreach控制，显示的log中，Loop循环是在场景的单个步骤上。

### ISSUE THREAD

**Issue by dasandeyu** [metersphere/metersphere#2951]
**MeterSphere 版本**
v1.9.1-2cb10c1e

**Bug 描述**

**Bug 重现步骤**
1.  在场景中添加ForEach的控制器，然后导入一个已存在的场景。如下：
![image](https://user-images.githubusercontent.com/13783632/118753238-211c3000-b897-11eb-8f8c-a4e427098f8c.png)
2. 设置定时任务执行。
3. 定时任务执行完后，从报告中的饼图点击进入，跳转到”测试计划->接口测试用例页面“。点击”通过“按钮跳转到log页面。如下：
![image](https://user-images.githubusercontent.com/13783632/118753300-427d1c00-b897-11eb-9f70-dd6ee7df28e4.png)

**期待的正确结果**
希望LooContoller是在场景上。这样方便定位问题。类似手动执行的log。
![image](https://user-images.githubusercontent.com/13783632/118753412-853ef400-b897-11eb-8cee-5d0a57af9da5.png)

**Comment by zyyfit** [comment]
您好，后续版本优化这个问题
