### ISSUE TITLE
[BUG]【优化】【缺陷管理】缺陷导入200多后操作比较卡顿

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#29520]
### 联系方式

18291878104@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

导入了200左右缺陷，然后筛选，编辑完保存返回，点击翻页，都会出现转圈圈转很久，但用例有500多查询都没卡
![076779a5485700826cc71cb91208173](https://github.com/metersphere/metersphere/assets/107530175/f18f93a0-653c-4dac-80ef-d662ee16ff5f)

### 重现步骤

1、本地导入200多缺陷
2、然后筛选
3、打开一个缺陷进行修改/或翻页等操作

**Comment by 13290445582** [comment]
您好，请问缺陷集成的什么平台？

**Comment by ywhkhb** [comment]
没有集成其它平台，按照系统自己的模板整机的excel导入的发自我的手机-------- 原始邮件 --------发件人： wangyicheng ***@***.***>日期： 2024年3月18日周一 18:36收件人： metersphere/metersphere ***@***.***>抄送： ywhkhb ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [BUG]【优化】【缺陷管理】缺陷导入200多后操作比较卡顿 (Issue #29520)
您好，请问缺陷集成的什么平台？

**Comment by 13290445582** [comment]
您好，您的导入的缺陷可以提供下嘛？

**Comment by ywhkhb** [comment]
公司文件加密，发给你打开乱码，给你截图看下吧1、登记18个缺陷分两页时翻页转圈2/3秒2、本地表格导入200左右很卡，后来发现缺陷有些字段显示不正常，可能跟这个有点关系，比如都是相同的状态字段，这个字段是下拉选项，有些缺陷在外面列表显示加了引号，是不符合规则的，然后打开后编辑显示的空发自我的手机-------- 原始邮件 --------发件人： wangyicheng ***@***.***>日期： 2024年3月19日周二 10:19收件人： metersphere/metersphere ***@***.***>抄送： ywhkhb ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [BUG]【优化】【缺陷管理】缺陷导入200多后操作比较卡顿 (Issue #29520)
您好，您的导入的缺陷可以提供下嘛？

**Comment by ywhkhb** [comment]
[缺陷模版 (1).xlsx](https://github.com/metersphere/metersphere/files/14644973/1.xlsx)
加密的打开可能是乱码
![ed5d06ba99042dcd4ec6b2b0f0f3ac2](https://github.com/metersphere/metersphere/assets/107530175/56aa0477-a680-488b-8efc-f759a7f1d459)

**Comment by 13290445582** [comment]
感谢反馈，未复现该情况，后续将继续留意是否有此问题。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
