### ISSUE TITLE
[BUG]  测试计划报告列表点进去的报告，点击失败重试无效果

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29522]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

测试计划报告列表点进去的报告，点击失败重试无效果

### 重现步骤

点击失败重试，过好久，查看报告并没有重试（Case,场景）![image](https://github.com/metersphere/metersphere/assets/103925124/3feb8c33-f189-41d0-9381-a58cc8e0b866)

**Comment by 13290445582** [comment]
感谢反馈，本地测试环境未复现该问题，失败重跑后刷新下查看场景用例的开始时间结束时间，可看到是重跑后的时间。
<img width="1364" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/a5cb1e03-e6cb-4dfe-9ae4-8e87bf87992b">
