### ISSUE TITLE
[BUG] 测试计划中的用例，不显示编辑模式为TEXT的用例步骤和预期结果

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#2954]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  编写用例时，步骤选择“文本描述”
2. 用例关联至测试计划
3. 测试计划中，脑图形式执行用例，不显示用例步骤和预期结果

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
下个版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
