### ISSUE TITLE
[BUG]测试PUT接口，结果：状态码200，没有响应，接口功能未实现；

### ISSUE THREAD

**Issue by ZhaoGuoY** [metersphere/metersphere#29544]
### 联系方式

18612665031

### MeterSphere 版本

2.10.12

### 使用外置数据库

否

### 问题描述

公司本地部署，调不通PUT接口
![Uploading 317d8412588558a839c2b3c59bfbedc.png…]()
![Uploading a3c62e38f5f0563ff01a07c4f4342b4.png…]()

### 重现步骤

PUT接口、rest参数、+token，无其他

### 期待的正确结果

实现接口功能；

**Comment by 13290445582** [comment]
您好，请检查下您接口是否正确，本地测试是可以正常调试put类型接口的，您上传的图片未显示成功，请重新发送下。
<img width="1372" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/61654953-a403-4b44-b037-f4d68af223f4">

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
