### ISSUE TITLE
[BUG]接口请求时，偶尔404，再次请求时返回入参不正确，导入和新增都不能正常请求

### ISSUE THREAD

**Issue by zhanglingilng** [metersphere/metersphere#29547]
### 联系方式

876868265@qq.com

### MeterSphere 版本

v2.1.12

### 使用外置数据库

否

### 问题描述

接口请求时，偶尔404，再次请求时返回入参不正确，导入和新增都不能正常请求

### 重现步骤

1.新增接口请求，导入接口请求

**Comment by youliyuan-fit2cloud** [comment]
你好，描述的问题没办法复现，请详细说下具体操作步骤和接口信息。返回信息等等。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
