### ISSUE TITLE
[BUG]查询测试计划任务执行状态，swagger中该接口传 planId 不正确，应该传测试报告Id 才能正常查询数据。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#29551]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

查询测试计划任务执行状态，swagger中该接口传 planId 不正确，应该传测试报告Id 才能正常查询数据。

### 重现步骤

查询测试计划任务执行状态，swagger中该接口传 planId 不正确，应该传测试报告Id 才能正常查询数据。
![image](https://github.com/metersphere/metersphere/assets/104960608/a230a298-7871-44d6-8602-8203e38a5a5b)

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by Somebody-JIAN** [comment]
已改
