### ISSUE TITLE
[BUG] 测试计划中，执行用例，用例步骤和预期结果不是很清晰

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#2955]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  测试计划关联用例，执行用例

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40782672/118759910-73b01900-b8a4-11eb-99e1-1fc1bee3cd9e.png)

**Comment by zyyfit** [comment]
1.9.3会改成这种样式

![图片](https://user-images.githubusercontent.com/73461316/118796570-4f693200-b8ce-11eb-86cf-4ed15a1623c7.png)
