### ISSUE TITLE
[QUESTION]Jenkins插件，能通过钉钉机器人直接查看Jenkins控制台输出信息吗

### ISSUE THREAD

**Issue by fizzhu97** [metersphere/metersphere#29566]
### 请描述您的问题

如下图：
接入钉钉群告警：
点击“控制台”，能否可以在详情里面(不需要登录Jenkins)查看到此流水线任务的控制台输出信息（主要是想直接查看到测试报告URL）。
或者，可以配置console，拼接出MeterSphere的测试报告链接（需要参数化测试报告id），这个要怎么操作？
![1710554540714](https://github.com/metersphere/metersphere/assets/161595150/06bed2ea-eb16-4471-943b-54af48042212)
![1710554540714](https://github.com/metersphere/metersphere/assets/161595150/ffcb8568-0dd4-4f28-9257-7c3b298e39ed)
![image](https://github.com/metersphere/metersphere/assets/161595150/2a1d2a99-afd1-4cbf-8bb3-f1b1f495aaa7)

**Comment by luty2018** [comment]
感谢建议， 我们会在v3版本规划
