### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#2957]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.2

**Bug 描述**
简要描述您碰到的问题
性能测试，测试报告一直处于isRunning状态
**Bug 重现步骤**
1.  在jenkins选择一个未执行的较大的接口场景用例
2.  高频率执行接口场景，出现测试报告处于isRunning状态

**期待的正确结果**
正确情况下应该是什么样的？
正常执行完成后报告处于成功或失败的状态
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/34637801/118761014-4bc1b500-b8a6-11eb-90e9-dad94a95edc7.png)

**Comment by zyyfit** [comment]
您好，能稳定复现吗
