### ISSUE TITLE
[BUG]测试计划报告有时无法显示执行时间

### ISSUE THREAD

**Issue by tangyuan903** [metersphere/metersphere#29580]
### 联系方式

交流群61-helt

### MeterSphere 版本

v.2.10.4-lts

### 使用外置数据库

否

### 问题描述

偶现问题：测试计划报告有时无法显示执行时间

### 重现步骤

执行测试计划

### 期待的正确结果

显示执行时间

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有遇到该问题，建议升级到v2.10.12-lts。或者提供更详细的信息，包括具体页面截图，是否有错误日志。感谢理解和支持。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
