### ISSUE TITLE
[BUG]【测试跟踪】测试计划批量执行，切换到报告列表查看报告，再切回到测试计划列表，测试计划显示不对

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#29595]
### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

批量执行多个测试计划，从报告列表查看的执行的报告，再切换到测试计划列表，测试计划显示显示不对

### 重现步骤

1、使用A帐号创建多个测试计划，将测试计划的责任人指定为帐号B
2、使用C帐号登录平台，批量串行或者并行执行测试计划
3、切换到报告列表查看报告
4、切回到测试计划列表，查看测试计划

### 期待的正确结果

切回到测试计划列表可以查看到所有的测试计划

### 附加信息

测试计划截图

![bv6oc-6q96l](https://github.com/metersphere/metersphere/assets/45531073/926ecf74-a823-46c7-bf37-d496f8f8e7ef)

**Comment by 13290445582** [comment]
您好，未复现该问题，还可以稳定复现嘛，可以在测试环境测一下。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
