### ISSUE TITLE
[BUG]【测试跟踪】批量执行测试计划的报告创建人显示 不对

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#29594]
### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

批量执行多个测试计划，从报告列表查看的执行的报告，创建人显示不对

### 重现步骤

1、使用A帐号创建多个测试计划，将测试计划的责任人指定为帐号B
2、使用C帐号登录平台，批量串行或者并行执行测试计划
3、观察报告的创建人

### 期待的正确结果

使用其他帐号执行测试计划时，报告的创建人为该执行人

### 附加信息

1、创建多个测试计划

![image](https://github.com/metersphere/metersphere/assets/45531073/613a4c12-3cd4-4cd5-9213-5b820b45ec93)
2、其他帐号登录平台，批量执行测试计划
![image](https://github.com/metersphere/metersphere/assets/45531073/640bc08a-133e-4b73-ac2e-6a14077082cf)
3、查看测试计划报告的创建人
![image](https://github.com/metersphere/metersphere/assets/45531073/5ec34fa4-f1f7-415e-b491-4893f8415b66)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
