### ISSUE TITLE
[BUG]测试计划报告导出报错

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#29596]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

测试计划报告导出报错，场景较多时，39 功能用例  131场景用例，报告导出报错

### 重现步骤

测试计划报告导出报错
![image](https://github.com/metersphere/metersphere/assets/103627487/2c428b55-39bf-421c-a374-9e07fa498d0a)
![8ad903a1b7784b1cf1411a67459f287](https://github.com/metersphere/metersphere/assets/103627487/da16f5ef-acfe-41c1-bca6-2fe0c2069d61)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题已优化，请升级至v2.10.16版本使用。 json序列化有字符串大小限制，已优化，但是如果报错network error，可能是报告太大，后台服务挂了，可以加大容器的内存配置再导出
