### ISSUE TITLE
[BUG]接口自动化请求时提示系统异常，新增和复制结果一样，不能正常返回！

### ISSUE THREAD

**Issue by zhanglingilng** [metersphere/metersphere#29592]
### 联系方式

876867265@qq.com

### MeterSphere 版本

1.2.12lts

### 使用外置数据库

否

### 问题描述

使用接口自动化请求接口，返回系统异常，使用postman调试正常，偶尔接口返回404.403

### 重现步骤

1，选择接口自动化
2，新建或者复制接口或者导入
3，对接口进行编辑
4，输入正确的参数
5，接口返回系统异常

**Comment by youliyuan-fit2cloud** [comment]
你好，请详细描述下MS哪个版本？接口场景还是接口定义？具体接口信息配置，以及返回错误的截图贴出来才能更快定位问题，感谢理解和支持。

**Comment by zhanglingilng** [comment]
> 你好，请详细描述下MS哪个版本？接口场景还是接口定义？具体接口信息配置，以及返回错误的截图贴出来才能更快定位问题，感谢理解和支持。

![901710494252_ pic](https://github.com/metersphere/metersphere/assets/115617114/d7aae331-fbc9-4c9d-9f09-f850507984df)

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
