### ISSUE TITLE
[BUG]连续密集点击运行同一个测试计划，消息通知内容错乱

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#29600]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

连续密集点击运行同一个测试计划，消息通知内容里面的变量被替换为最新一次运行的结果，导致通知结果错乱。

### 重现步骤

1、项目设置下点击消息通知，为测试计划添加消息配置（至少添加通过率、实际开始、实际结束时间这三个变量）
2、连续密集点击运行同一个测试计划
3、消息通知内容里面的变量，并查看收到的内容

### 期待的正确结果

消息通知内按照每一次的执行结果进行发送。

### 附加信息

截图：
<img width="1443" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/96674f2c-cf4e-452b-aa07-216c77159b99">

消息通知内容：

{"text":"【定时任务执行】：测试计划:${name}执行完成。通过率为：${passRate}%, 开始时间：${actualStartTime}，结束时间：${actualEndTime}。
接口场景失败个数：${apiScenarioFailedCount};
UI场景失败个数：${uiScenarioFailedCount}。
测试报告: ${planShareUrl}"}

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，请把日志信息发一下吧。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。

**Comment by hujirong521317** [comment]
![20240513151154](https://github.com/metersphere/metersphere/assets/50876029/ff0ff2b3-81ea-4f54-8d68-1f39264ea049)
测试计划配置钉钉发送消息，，事件事执行完成或者执行成功发送，没有发送成功
![Uploading 20240513151154.jpg…]()
