### ISSUE TITLE
[BUG] 使用最新版本的禅道插件提交缺陷不能保存

### ISSUE THREAD

**Issue by chinaa12** [metersphere/metersphere#29607]
### 联系方式

zsx201424@163.com

### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

metersphere 使用插件连接禅道，测试用例中能关联到需求。目前再MeterSphere 中提交缺陷 不能保存，禅道最新版本是 18.11，插件最新版本：2.10.7

### 重现步骤

禅道账户开启Medol权限，并且已与NeterSphere连通，点击测试跟踪-缺陷管理-创建缺陷（填写内容）-保存
![微信图片_20240318191526](https://github.com/metersphere/metersphere/assets/60680013/6f1d53a1-96d5-4764-a31c-fabacb92900c)

### 期待的正确结果

提交成功

### 附加信息

[
[error.log](https://github.com/metersphere/metersphere/files/14635295/error.log)
]

**Comment by 13290445582** [comment]
您好，已上传最新禅道插件，请在github下载最新禅道插件，建议禅道版本在18.10以下，高版本不能完全适配，感谢您的理解与支持。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
