### ISSUE TITLE
[FEATURE]只使用接口测试模块时，没有接口及用例评审功能，期望能够单独可以针对接口/接口用例进行评审

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29617]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

只使用接口测试模块时（不使用功能测试跟踪模块，因为只针对 api 进行测试，不需要去使用测试跟踪-功能测试模块）

“接口测试”没有接口及用例的评审功能，期望能够可以针对接口/接口用例进行评审

**Comment by luty2018** [comment]
感谢反馈， 这个功能会规划到v3.0 ， 可以专注后续的发布
