### ISSUE TITLE
[BUG]功能用例编辑页面-相关需求搜索关键字后，显示出来的字体重叠

### ISSUE THREAD

**Issue by ly761645472** [metersphere/metersphere#29619]
### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

![1](https://github.com/metersphere/metersphere/assets/43343703/b4f02fce-5ce6-4ad2-ae9c-b1ab9ec4f21a)

### 重现步骤

功能用例编辑页面-禅道相关需求搜索关键字后，显示出来的字体重叠

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.22版本已修复此问题，请升级。
