### ISSUE TITLE
[BUG]【测试计划-测试报告-失败用例】无法显示标记为失败的测试用例列表

### ISSUE THREAD

**Issue by changdapu** [metersphere/metersphere#29613]
### 联系方式

changdapu@qq.com

### MeterSphere 版本

 v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/22142632/aceb07a4-ee49-4fc9-9b2d-257300af217e)
[BUG]【测试计划-测试报告-失败用例】无法显示标记为失败的测试用例列表，已经存在执行失败的测试用例。

### 重现步骤

测试计划，标记部分测试用例为【失败】
查看测试计划--测试报表--失败的用例

### 期待的正确结果

正常显示各种状态的用例

**Comment by 13290445582** [comment]
感谢反馈，已有重复issue，已关联。https://github.com/metersphere/metersphere/issues/28625
