### ISSUE TITLE
[BUG]测试用例【复制/移动】操作，无法平移用例所属的目录层级

### ISSUE THREAD

**Issue by changdapu** [metersphere/metersphere#29614]
### 联系方式

changdapu@qq.com

### MeterSphere 版本

 v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

[BUG]测试用例【复制/移动】操作，无法平移用例所属的目录层级

### 重现步骤

选择带有多层级目录的用例，复制或移动之后，无法把用例的目录层级移动复制

**Comment by 13290445582** [comment]
您好，复制/移动测试用例到其他目录层级下，不会带走你当前的层级信息，是在移动后的层级下添加该用例，所以无法达到通过复制/移动测试用例还会平移它所属的目录层级的效果。您可以移动该层级到其他层级下，来达到平移用例带走目录层级信息的效果。感谢您的理解与支持。
