### ISSUE TITLE
场景步骤中后置脚本中添加python的time.sleep方法，会导致关联该场景的测试计划执行后报告处于running状态无法结束

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#29629]
### MeterSphere 版本

v2.10.12-LTS

### 使用外置数据库

否

### 问题描述

场景步骤中后置脚本中添加python的time.sleep(10)方法，会导致关联该场景的测试计划执行后报告处于running状态无法结束
场景的截图：
<img width="1347" alt="截屏2024-03-19 下午2 51 20" src="https://github.com/metersphere/metersphere/assets/34637801/714aba30-a141-4afd-ba63-b962721d8602">
关联场景测试计划执行结果报告：
<img width="1395" alt="截屏2024-03-19 下午2 51 57" src="https://github.com/metersphere/metersphere/assets/34637801/0e4fdd3f-adc1-4160-a75b-334cb0d687de">

### 重现步骤

1.准备一个可以执行成功的接口自动化场景
2.在场景中某个步骤添加一个后置脚本
3.后置脚本设置python脚本
import time
time.sleep(10)
4.创建一个测试计划，关联场景
5.执行测试计划

### 期待的正确结果

测试计划报告状态能在正常时间内结束

**Comment by 13290445582** [comment]
您好，本次环境测试未发现该情况，建议您排查下所用环境是否有其他情况影响，感谢理解。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
