### ISSUE TITLE
[BUG]接口测试foreach循环控制器也会默认遍历CSV文件的数据

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#29625]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

在接口自动化中， 场景变量添加了CSV文件，场景中分别存在次数循环控制器和foreach循环控制器，执行时发现foreach循环控制器也会遍历CSV中的文件，导致次数循环里不能完全遍历CSV文件中的数据。

### 重现步骤

1、创建一个接口自动化场景，在其中上传CSV文件，并设置一个列表类型变量。
![image](https://github.com/metersphere/metersphere/assets/88763608/a0af5f2b-9981-4f39-a1d0-eeabd1b07967)
2、场景中添加一个foreach循环控制器和次数循环控制器，其中分别包含一个请求，分别引用数组中的size变量和csv中的name和id变量。
![image](https://github.com/metersphere/metersphere/assets/88763608/90071184-8660-4efa-82dc-7d25e36326b4)
![image](https://github.com/metersphere/metersphere/assets/88763608/6751582d-793c-4cc1-afb1-9e871bd544a0)
![image](https://github.com/metersphere/metersphere/assets/88763608/0da3fbda-4a56-449e-9194-edf8655bf6a7)
3、执行该场景，发现次数循环控制器中csv的参数从第五行开始引用的，没有从第一行开始。
![image](https://github.com/metersphere/metersphere/assets/88763608/5a5e9ee8-dfa9-4aa1-b652-f050b0dc4c89)
![image](https://github.com/metersphere/metersphere/assets/88763608/e3a544e9-d919-47cb-95fb-da297004c81c)
4、将该场景导出为JMX格式，并在JMeter打开，发现foreach控制器下也添加了csv文件设置，所以导致foreach循环也遍历了csv文件参数。
![image](https://github.com/metersphere/metersphere/assets/88763608/5d6a172a-454c-4a1f-978a-0990f055574b)
5、将JMX中foreach控制器下的csv文件设置去掉后，就可以避免foreach循环也遍历csv参数，次数循环控制器就可以从csv文件第一行开始遍历。
![image](https://github.com/metersphere/metersphere/assets/88763608/928c2e8e-0121-4120-936f-b0de54a901f6)

### 期待的正确结果

希望配置csv文件变量的时候，默认只给次数循环控制器遍历，不建议在所有控制器下面都添加同样的csv文件参数，有一些用户都反馈为什么foreach循环也遍历了csv，导致他们在场景中不方便次数循环跟foreach配合使用。

**Comment by 13290445582** [comment]
感谢反馈，在V3我们会这样实现，V2无法再修改这里了，感谢理解。

**Comment by linfengjjj** [comment]
循环控制器下面的子循环也会计数，希望这部分也不要默认计数，计数的地方太多了，复杂场景组合的时候很难把控，这个也会修复吗？
![image](https://github.com/metersphere/metersphere/assets/88763608/05baddef-ca77-442d-b17a-71e8aa0e0b0a)
![image](https://github.com/metersphere/metersphere/assets/88763608/20a1d27e-38f0-4754-9628-acc3250a4e5c)

**Comment by linfengjjj** [comment]
希望添加csv场景变量后，不要给场景中每个循环控制器都增加csv data set组件，这样跑一套下来，用户缕不清楚到底参数遍历到哪了，主要是在foreach循环和次数循环中的子次数循环中用户不需要遍历csv文件，所以我们就不要给每个循环默认都加上csv data set了。

**Comment by luty2018** [comment]
v2的设计上不支持， v3beta版本会支持CSV，可以在v3测试这种场景
