### ISSUE TITLE
[FEATURE]前端UI兼容手机端

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#2962]
**请描述您的需求或者改进建议.**
现在有个定时任务需要5分钟执行一次，万一半夜报错，我们想看报错原因，用手机看可能比较方便，但是现在用手机打开没办法看全。
![13591621329557_ pic](https://user-images.githubusercontent.com/30038088/118762756-516cca00-b8a9-11eb-93a4-790300e41e0b.jpg)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研
