### ISSUE TITLE
[BUG]测试计划列表查看报告，导出报告后功能用例列表不显示

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#29636]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

测试计划列表查看报告，报告里功能用例列表显示正常，导出报告后功能用例列表不显示

### 重现步骤

1. 测试计划列表页查看测试报告，报告里功能用例列表正常显示
![image](https://github.com/metersphere/metersphere/assets/103627487/6d54e2b6-71d7-4474-9c28-314a1f871de7)
![image](https://github.com/metersphere/metersphere/assets/103627487/ca2835d0-4e9d-4151-a7f6-26f256701184)
2. 导出报告后功能用例列表不显示
![image](https://github.com/metersphere/metersphere/assets/103627487/33d061c4-f58d-4048-90da-250f28b05b75)

**Comment by 13290445582** [comment]
感谢反馈，已有重复issue，已关联。https://github.com/metersphere/metersphere/issues/28625
