### ISSUE TITLE
[BUG]切换环境保存数据库，导致其他环境的sql请求数据库配置发生变化

### ISSUE THREAD

**Issue by a524137097** [metersphere/metersphere#29652]
### 联系方式

524137097@qq.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

切换环境保存数据库，导致其他环境的数据库配置发生变化

### 重现步骤

1.在环境38中保存38汉德数据库并点击保存
![image](https://github.com/metersphere/metersphere/assets/87356983/f2924fd7-e395-4e58-872f-efaf9dfabedc)
2.切换至29环境将数据库连接更改为29汉德，点击保存
![image](https://github.com/metersphere/metersphere/assets/87356983/85746377-100a-4d81-abf1-c0d4cf50f5b8)

3.将环境切换为环境38，发现38数据库的链接自动变成了sqlsever数据库
![image](https://github.com/metersphere/metersphere/assets/87356983/54fabd0a-e2c8-42da-86f7-a268298d9a5c)

### 期待的正确结果

切换为38环境时，数据库连接仍然为38汉德
在没有点击保存的情况下，数据库配置不应该自己变动

**Comment by wxg0103** [comment]
您好  目前的设计是  数据源的配置是会根据 场景选择的环境动态变得，如果不同的环境有相同名称的数据源，会选择名称相同的数据源，如果没有，就优先选择环境下的第一个数据源
