### ISSUE TITLE
[BUG] kafka消费组积压一直好高，如何清除这些积压

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#29659]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

版本: v2.10.12-lts-a7d7c194

### 使用外置数据库

是

### 问题描述

kafka消费组积压一直好高，如何清除这些积压

### 重现步骤

版本: v2.10.12-lts-a7d7c194
运行方式：安装包运行
浏览器版本：chrome(版本 112.0.5615.137（正式版本） （64 位）)

kafka积压一直好高，如何清除这些积压

![image](https://github.com/metersphere/metersphere/assets/23476281/af67035e-2252-4d15-9361-2cf3b757dfb8)
2024-3-20 补充相kraka有大量的消费组存在，请问这些消费组如何删除
![image](https://github.com/metersphere/metersphere/assets/23476281/5bbb1564-fa87-4109-8507-64c02c774cae)

**Comment by liuruibin** [comment]
我们默认kafka消息保留时间为1分钟，如果你的kafka另有配置的话需要自行处理。除此之外kafka保留的都是中间数据，你可以在空闲时间进行删除

**Comment by chase001** [comment]
1、默认kafka消息保留时间为1分钟
RE：请问那可以看配置，请给检查配置的具体操作。

2、除此之外kafka保留的都是中间数据，你可以在空闲时间进行删除
RE：请问题如何删除，请给出具体的操作步骤。

**Comment by liuruibin** [comment]
<img width="679" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/9c4ddce4-5a8a-4abb-ac71-7c845d31708f">


我不知道你是如何部署的kafka，如果我来操作我们内置kafka的话只需要重建容器即可

```
docker stop kafka
docker rm kafka
msctl reload
```

**Comment by chase001** [comment]
你截图文件的具体路径和是那个文件

**Comment by liuruibin** [comment]
/opt/metersphere/docker-compose-kafka.yml

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
