### ISSUE TITLE
[BUG]模版字段中没有适用于接口模板的状态字段

### ISSUE THREAD

**Issue by hihihinewer** [metersphere/metersphere#29662]
### 联系方式

bamuxian@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

没有适用于接口模板的“状态”系统字段
![image](https://github.com/metersphere/metersphere/assets/31436142/9d8ede7a-fdfc-48b0-ade0-20d21c77f5ac)

### 重现步骤

1. 进入项目设置-模版管理-模版字段
2. 查看字段名称是状态的，是否有适用于接口模板的

**Comment by youliyuan-fit2cloud** [comment]
你好，目前接口模块中默认没有这个字段，可以自己创建。

**Comment by hihihinewer** [comment]
![image](https://github.com/metersphere/metersphere/assets/31436142/76095713-2605-46e2-8dbe-ee4599b834c9)
新建接口的时候，有状态这个字段呀
