### ISSUE TITLE
[FEATURE] 【强烈需求】期望测试计划-接口用例，对还不能自动化需要人工参与的用例可以支持手动勾选测试结果

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29691]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

使用场景：
一部分用例已经写好断言了是可以自动化；一部分还不能写合适的断言，仍然需要人来参与判断是否测试通过

当前现状：
系统只支持自动化执行，没有人工执行结果的操作，无法将这俩部分的用例都统一到一个测试计划中

### 请描述你建议的实现方案

在测试计划-接口测试用例，除了当前系统已经实现的点击执行，展示测试结果外（这部分用来批量执行自动化的部分）；还能够支持人员手工设置测试结果（这部分用来执行手工测的那部分），这样到测试报告就可以展示完整的测试用例及结果了

**Comment by qian-kui** [comment]
跟进：
实际工作使用中不是每一个接口测试用例都能完全写好断言自动进行接口执行的，所以使用当前系统执行接口测试会无法判断到实际结果是否正确。
所以我们测试期间有断言的直接可以进行自动化执行，没有写好断言，需要人工参与判断是否通过的无法直接编辑测试结果是通过/不通过/阻塞。

所以期望咱们能够在测试计划-接口测试这部分还可以   支持人工执行并标识接口测试结果

**Comment by luty2018** [comment]
转下线私聊了。
