### ISSUE TITLE
[BUG]性能测试上传脚本未被实际删除

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#297]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  性能测试-进入一条测试记录-删除上传的性能脚本，刷新页面,已删除文件仍存在

**期待的正确结果**
正确情况下应该是什么样的？--文件被删除

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问删除后有点击保存按钮吗，目前是需要点击保存按钮才会实际删除
