### ISSUE TITLE
[BUG]Jenkins插件运行测试计划显示失败，实际运行成功

### ISSUE THREAD

**Issue by franky899** [metersphere/metersphere#29709]
### MeterSphere 版本

MS系统2.10.3，MS的Jenkins插件2.10.12

### 使用外置数据库

否

### 问题描述

![issue1](https://github.com/metersphere/metersphere/assets/54705762/d2b25951-2e40-4897-9706-1297e1db4479)
如图，Jenkins上构建项目后运行testplan，显示失败，但是MS系统里看是api方式调用成功的。

### 重现步骤

1、Jenkins版本图上有
2、pipeline脚本中增加metersphere测试计划步骤

### 期待的正确结果

显示调用测试计划成功，并显示报告链接

**Comment by 13290445582** [comment]
您好，未复现您反馈的这个问题。建议您将环境与插件升级至最新版本测试。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
