### ISSUE TITLE
[BUG] 自动化用例中引用的场景用例，被引用场景用例的成功失败状态显示有误

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#29707]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/82088551/b3b201ec-6757-4488-ab6d-aa303311d6a6)

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/82088551/b3b201ec-6757-4488-ab6d-aa303311d6a6)
正常调试窗口 成功失败的状态显示错误

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
