### ISSUE TITLE
[FEATURE]期望可以批量修改接口用例的状态、运行环境

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29713]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/79577571/db689dce-c70d-4e75-a1a3-f6c8af317252)
当前的接口用例批量操作不够使用
比如需要将已经审核的批量更新状态就无法使用、需要更改运行环境无法使用

### 请描述你建议的实现方案

建议增加批量操作

**Comment by luty2018** [comment]
好的， 感谢建议， 我排期加一下
