### ISSUE TITLE
[FEATURE]当接口请求较少但是返回信息很多时，返回框无法调整大小，一直滚动条滚动不太便捷

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29711]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/79577571/604d8160-52f1-41cf-96e8-47ff2c149243)

当接口请求较少但是返回信息很多时（往往返回值较长），返回框无法上下调整高度，易用性不是很好

### 请描述你建议的实现方案

建议响应内容框上下拖拉（就像用例列表可以左右拖拉展示更长的标题一样）

**Comment by luty2018** [comment]
这个在v3版本有支持响应内容左右布局， 可以看到整屏的内容。
