### ISSUE TITLE
[BUG] 接口模块导入导出：1、导出原模块接口及用例，再次导入选择覆盖，不会覆盖却在原树层下方多了一个树层结构2、导出的文件中是导出了创建人的，但是导入后创建人却是当前用户了

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29718]
### 联系方式

wannaspace@163.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

导入导出俩问题：
1、导出原模块接口及用例，再次导入选择覆盖，不会覆盖却在原树层下方多了一个树层结构
2、导出的文件中是导出了创建人的，但是导入后创建人却是当前用户了

### 重现步骤

1、导出原模块接口及用例，再次导入选择覆盖，不会覆盖却在原树层下方多了一个树层结构
![企业微信截图_17110751923233](https://github.com/metersphere/metersphere/assets/79577571/7e9d8ad0-9519-4824-9003-e85c95af0c5b)
导入时候：
![image](https://github.com/metersphere/metersphere/assets/79577571/de9be9d3-ada8-41f8-a8c4-a66028a01883)

2、导出的文件中是导出了创建人的，但是导入后创建人却是当前用户了

### 期待的正确结果

预期：
1、可以正确覆盖而不是新增一个树层
2、创建人不会受到覆盖影响，看到系统导出的 json 文件有 userid，应该取这个作为创建人
3、应该有最近更新人的字段更好一些

**Comment by 13290445582** [comment]
1.问题未复现，看您版本不是最新的，建议升级至最新版本测试。
2.设计如此，导入后创建人会更新为当前操作人，覆盖导入相当于新建，当前操作用户即为创建人。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
