### ISSUE TITLE
[FEATURE]期望支持添加备注，并且 postman 的备注也可以导出，支持导入到 metersphere

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29719]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

期望支持添加备注，并且 postman 的备注也可以导出，支持导入到 metersphere

### 请描述你建议的实现方案

![image](https://github.com/metersphere/metersphere/assets/79577571/eba1fa30-1519-46e8-b145-530394ec10d4)
![image](https://github.com/metersphere/metersphere/assets/79577571/d8468a23-e15a-4324-859d-cef430fa8a5c)

**Comment by luty2018** [comment]
v3.0编辑器中支持注释， 会解决这个问题
