### ISSUE TITLE
[BUG]环境变量经常出现不生效的情况（编辑、复制常见）

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29720]
### 联系方式

wannaspace@163.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

环境变量需要更新，经常遇到（编辑、复制常见）保存后，实际还是上次的值、新的值未保存上

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/79577571/46e5aeef-e5c0-4669-afdb-7b6226fcdda3)

**Comment by 13290445582** [comment]
您好，该问题在之前版本确实存在，后续版本有修复，请升级最新版本测试，最新版本若问题仍存在，请反馈详细步骤。

**Comment by qian-kui** [comment]
好的感谢，我们之后升级新版本
