### ISSUE TITLE
[QUESTION]请问是否有这方面的计划：支持将导出的API和CASE支持excel格式

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29721]
### 请描述您的问题

请问是否有计划将导出的API和CASE支持excel格式，json格式导出内容太多时不太方便查看

**Comment by luty2018** [comment]
API 文档导出为html格式可以解决你的问题吗。case目前还没有计划。

**Comment by qian-kui** [comment]
html 也可以，期待~
