### ISSUE TITLE
[BUG]测试计划报告导出，当报告比较大时，导出报告内存溢出

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#29738]
### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

1. 目前报告400多M，导出报告 test-track  模块挂掉，查看日志，内存溢出，把 test-track 模块内存调大到10G，jvm 内存调大到 4G，报告能导出，查看 test-track 容器内存7G。之后再导出报告，容器还会挂掉。
2. 消耗内存将近7G，报告导出完后，内存也不释放

### 重现步骤

测试计划多关联场景，之后导出报告（建议导出报告大于200M)，查看 test-track 容器内存，以及服务状态

### 期待的正确结果

报告导出内存使用过大，建议优化

**Comment by 13290445582** [comment]
感谢反馈，转给开发看下。

**Comment by luty2018** [comment]
1.20 不维护了， 请确认v2是都有这个问题。

**Comment by meijieDouDou** [comment]
不好意思，我写错版本了，是 v2 版本出现的，当时用户版本 v2.10.11-lts

**Comment by 13290445582** [comment]
报告内容过大，确实会占用比较多的内存，这是办法避免的，其中涉及到序列化和文本替换，不能光靠报告大小评估内存，目前在66环境测试，导出189m的报告，把test-track 设置为8g，此时 jvm 堆内存大概3.3g，能正常导出，，建议把内存再调大点
