### ISSUE TITLE
[BUG]脑图中无法保存子模块

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#2973]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.2
**Bug 描述**
脑图中无法保存子模块
![image](https://user-images.githubusercontent.com/49704984/118772619-8c292f00-b8b6-11eb-81cb-080236d27f6c.png)
简要描述您碰到的问题

**Bug 重现步骤**
1.  脑图中在默认模块下新建一个子模块
2. 点击保存
3. 页面刷新，但子模块保存失败

**期待的正确结果**
期待结果：保存成功

正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/49704984/118773033-f8a42e00-b8b6-11eb-8938-d3e3f21e7301.png)

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前不支持在脑图中创建子模块
