### ISSUE TITLE
[BUG]  全局前置脚本-单个请求步骤前执行，勾选为步骤前置后执行。实际全局前置脚本还是第一个执行的，不是在步骤前置后执行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#29733]
### MeterSphere 版本

2.10.12

### 使用外置数据库

否

### 问题描述

问题:全局前置脚本-单个请求步骤前执行，勾选为步骤前置后执行。实际全局前置脚本还是第一个执行的，不是在步骤前置后执行

客户使用场景
1、单个接口请求前置设置参数a，然后希望使用全局前置脚本 的【步骤前置后执行】 获取到参数a 
2、目前全局前置请求   再脚本运行之前执行  获取不到参数a,整个脚本都不运行

### 重现步骤

问题:全局前置脚本-单个请求步骤前执行，勾选为步骤前置后执行。实际全局前置脚本还是第一个执行的，不是在步骤前置后执行

![image](https://github.com/metersphere/metersphere/assets/43202800/c73d55b3-fa84-4521-ae65-994e8576c41c)
![8b2a14190a18fe472e8b5af51d37122](https://github.com/metersphere/metersphere/assets/43202800/2ff2bbbe-0770-44ea-a726-4cb82f2d8534)

### 期待的正确结果

按照设置，

全局前置脚本-单个请求步骤前执行，勾选为步骤前置后执行，应该再单个接口的全局前置执行完成之后执行

**Comment by 13290445582** [comment]
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/b6fe2294-138c-4364-be0e-23ec5fbc2bcd">
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/2a8cef60-8dcf-45b1-bd9e-29e9d1264d5a">
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/c1d62920-c1bf-4c85-a82f-d4fb21f27149">

您好，未复现您说的这种情况，请按照上图在最新环境创建新的环境与场景测试下，查看是否还有此问题。

**Comment by xhy12** [comment]
不是按顺序打印的，勾选这个菜单应该是 接口步骤前置脚本先打印，全局前置接口后打印

**Comment by xhy12** [comment]
还有我这个是打印变量，添加赋值脚本有什么用？

**Comment by 13290445582** [comment]
已转开发，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
