### ISSUE TITLE
[BUG] 功能用例详情页面，访问报错

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#29741]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

功能用例详情页面，访问报错

### 重现步骤

http://xxx.xxx.com:2702/#/track/case/all?resourceId=4d288a81-150b-4448-a0db-19fcc047d86f  (功能用例ID)
![image](https://github.com/metersphere/metersphere/assets/103925124/25ee2829-a437-444d-9cc5-4a8e53af96b5)

**Comment by youliyuan-fit2cloud** [comment]
请补充下详细的复现步骤，谢谢。
