### ISSUE TITLE
[BUG]v2.10.12，如果在性能测试任务 “高级配置” 里设置了聚合时间，performance-test服务就会抛出异常，性能测试任务一直处在starting

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#29760]
### 联系方式

王进

### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

v2.10.12，如果在性能测试任务 “高级配置” 里设置了聚合时间，performance-test服务就会抛出异常，性能测试任务一直处在starting

### 重现步骤

1. 创建一个性能测试任务，选择一个场景，设置并发
2. 在高级配置里，修改聚合时间，比如选择1秒或者5秒
3. 保存并执行
4. 查看performance test服务日志
<img width="1034" alt="defad344aced42f1495c98d16f3472b" src="https://github.com/metersphere/metersphere/assets/76033005/236eefc2-9d61-470f-9420-cbe1e2e2dfbe">

**Comment by 13290445582** [comment]
您好，本地测试性能测试任务未一直处在starting，按照您的描述未复现该情况，建议升级至最新版本测试。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
