### ISSUE TITLE
[QUESTION]Linux VM部署下，默认资源池没有监控

### ISSUE THREAD

**Issue by omsjemmatao** [metersphere/metersphere#29790]
### 请描述您的问题

选择默认资源池进行压测，结束后监控详情没有数据

**Comment by omsjemmatao** [comment]
社区版 v2.6.1-2e5b7801

**Comment by liuruibin** [comment]
1. 检查资源池9100能否联通
2. 检查prometheus是否收到监控
3. 查看后台是否有报错

**Comment by omsjemmatao** [comment]
msedn1app01是默认的资源池

![image](https://github.com/metersphere/metersphere/assets/108791362/44fd9808-f924-41ec-89a3-16436f76c01d)

/logs/performance-test/error.log 发现以下报错，

ERROR i.m.service.MetricQueryService ? - Method[queryPrometheusMetric][query prometheus metric fail.]
ERROR i.m.service.MetricQueryService ? - Method[queryPrometheusMetric][400 Bad Request: "{"status":"error","errorType":"bad_data","error":"invalid parameter \"end\": end timestamp must not be before start time"}"]
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"status":"error","errorType":"bad_data","error":"invalid parameter \"end\": end timestamp must not be before start time"}"

错误日志贴在附件了
[01_performance- test_error.log](https://github.com/metersphere/metersphere/files/14753510/01_performance-.test_error.log)

2024-03-26 13:54:44,341 切成另外一个资源池重新压测同一个任务，监控数据显示正常

**Comment by omsjemmatao** [comment]
有建议吗？

**Comment by luty2018** [comment]
请问问题还存在吗？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
