### ISSUE TITLE
[BUG]复制性能测试案例报错

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#298]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.2.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  选择性能测试案例（可正常执行的案例），点击复制，报错
备注：同一项目下，部分案例复制报错，部分可正常复制

**期待的正确结果**
正确情况下应该是什么样的？--可以正常复制

**截图**
![image](https://user-images.githubusercontent.com/33714230/91627564-d3028c00-e9ea-11ea-8a42-3f681c5336b1.png)
![image](https://user-images.githubusercontent.com/33714230/91627568-df86e480-e9ea-11ea-9419-40b2ec598724.png)
![image](https://user-images.githubusercontent.com/33714230/91627573-ee6d9700-e9ea-11ea-9b1b-e2ed7ef2000d.png)

**Comment by liuruibin** [comment]
看起来像是 file_metadata 表中已经没有关于源文件的信息了

**Comment by liuruibin** [comment]
已修复
