### ISSUE TITLE
[BUG] 执行接口测试用例，在列表执行和进入编辑页面执行俩页面执行结果不一致

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29812]
### 联系方式

wannaspace@163.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

执行接口测试用例，在列表执行和进入编辑页面执行俩页面执行结果不一致
比如在列表执行有时候不能获取到最新环境变量，导致执行异常（ps进入编辑页面执行正常）

### 重现步骤

见问题描述

**Comment by LukaDoncic-Magic** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
