### ISSUE TITLE
[BUG]接口自动化，引入redis的工具jar包，可以set,get redis的值，但是无法执行删除del

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#29814]
### 联系方式

13716054767

### MeterSphere 版本

 v2.10.12-lts-a7d7c194

### 使用外置数据库

否

### 问题描述

脚本：

import com.yxhhw.utils.RedisUtil

RedisUtil.set_redis("php", "suibian", "4")

def returnValue = RedisUtil.get_redis("php", "suibian")

log.info(returnValue)

RedisUtil.delete_redis("php", "suibian")

### 重现步骤

脚本：import com.yxhhw.utils.RedisUtil

RedisUtil.delete_redis("php", "suibian")
执行删除操作

### 期待的正确结果

能够删除成功

### 相关日志输出

```shell
2024-03-26 11:18:19 INFO 88adac53 1-1 Thread started: 88adac53 1-1
2024-03-26 11:18:19 INFO 88adac53 1-1 Thread finished: 88adac53 1-1
2024-03-26 11:18:19 WARN 88adac53 1-1 Lock 'global_lock_b1fb55f0' not released in: Csc
```

**Comment by LukaDoncic-Magic** [comment]
你好，在最新版本没有复现，请上传复现场景文件，redis的jar包和后台日志信息，方便我们进一步排查原因，感谢理解和支持

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
