### ISSUE TITLE
[BUG]Dubbo协议在配置注册信息时，如果协议Protocol为none(直连)，会导致测试执行失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#29828]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

Dubbo协议在配置注册信息时，如果协议Protocol为none(直连)，会导致测试执行失败；JMeter上运行时，可以执行成功。

### 重现步骤

1、创建Dubbo测试接口
2、注册中心选择Protocol为none(直连)，点击运行

### 附加信息

代码截图：
<img width="1001" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/196923a3-f77c-4426-ac9e-9f689d1e168a">

日志截图：
<img width="1235" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/88b376db-e9ef-4c4d-b71b-501470cec67d">

测试截图：
<img width="882" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/e191d012-c91c-4726-8809-1af78c816fe2">

**Comment by liuruibin** [comment]
已知问题，我们会在后续版本中修复

**Comment by cshwen** [comment]
以为 v2.10.17-lts 修了，升级试了下确认没有修复，18 版本会修吗，坐等好消息

**Comment by youliyuan-fit2cloud** [comment]
> 以为 v2.10.17-lts 修了，升级试了下确认没有修复，18 版本会修吗，坐等好消息
v2.10.18-lts会修复。

**Comment by cshwen** [comment]
@youliyuan-fit2cloud  着急使用这个功能，直接看源码分析了一下，怀疑以下有问题，麻烦抽空尽快修复发版，感激不尽(づ￣3￣)づ╭❤～
org.apache.dubbo.config.AbstractInterfaceConfig#getRegistry
<img width="844" alt="image" src="https://github.com/user-attachments/assets/9b421996-ec1c-4835-ba93-af21718a83b7">
<img width="966" alt="image" src="https://github.com/user-attachments/assets/8e74db7e-3011-48ab-8944-a44051836934">
那可能是 this.registries 这里获取 List 为空的原因？null再调用getProtocol()直接就抛异常了。为啥会变成空呢，退回去找源头。
org.apache.dubbo.config.ReferenceConfigBase#setUrl
<img width="858" alt="image" src="https://github.com/user-attachments/assets/6975f630-239d-4dd5-a693-5f492c73be6d">
怀疑是这里缺少 reference.setRegistry 设值，没法调试不好确定是否这里就是 Bug 根因。
https://github.com/metersphere/metersphere/blob/v2.10.17-lts/framework/sdk-parent/jmeter/src/main/java/io/github/ningyu/jmeter/plugin/dubbo/sample/DubboSample.java#L119-L126

**Comment by 13290445582** [comment]
您好，问题已修复，请升级v2.10.18版本使用。

**Comment by cshwen** [comment]
@13290445582  自测是能通过？那就奇怪了，我这边升到 v2.10.19-lts 然后一调用还是报错，相关代码再看了也是没发现有一点变更
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/9c4674df-6900-4216-a7bc-f81568a49578">

**Comment by liuruibin** [comment]
我们在3月26日已经将此处修改了
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/47076a01-5b85-4cda-bb72-87ee8549ad28">

如果你的环境没有生效，可以自行编译插件代码替换容器里的jar

https://github.com/metersphere/jmeter-plugins/tree/main/jmeter-plugins-for-apache-dubbo
