### ISSUE TITLE
[BUG]接口自动化，通过导入JMX文件方式导入场景，运行环境处空白的，选择不了

### ISSUE THREAD

**Issue by zhangaiwu** [metersphere/metersphere#2985]
**MeterSphere 版本**
V1.9.2

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  

1.  Metersphere录制脚本保存JMX文件
2. 接口自动化场景中导入保存的JMX文件
3. 编辑步骤2中导入的场景

**期待的正确结果**
点击运行环境可以切换项目环境

**截图**
![image](https://user-images.githubusercontent.com/45023298/118786746-b4b82580-b8c4-11eb-8cba-1e9c9c98469b.png)

**Comment by xulinde** [comment]
1.自定义请求是全路径的，勾选引用环境，不会使用环境的地址；
2.自定义请求只有url（/a），勾选引用环境，会使用环境的地址；
您确认下是属于哪种场景

**Comment by zhangaiwu** [comment]
导入的，是全路径

**Comment by zyyfit** [comment]
目前全路径暂时不支持使用环境，后面可能会考虑支持这种情况
