### ISSUE TITLE
[BUG]接口测试自动生成测试数据，高级设置中设置 最大长度=1、最小长度=10（最大长度 小于 最小长度） ,点击生成测试数据会生成一堆不相关的参数

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#29866]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

接口测试自动生成测试数据，高级设置中设置 最大长度=1、最小长度=10（最大长度 小于 最小长度） ,点击生成测试数据会生成一堆不相关的参数

### 重现步骤

1.初始参数
![image](https://github.com/metersphere/metersphere/assets/30038088/a5a90df3-2788-4ab1-9acc-97f5db7d3b00)
2.接口测试-json参数-点击高级配置-设置【最大长度】、【最小长度】
![image](https://github.com/metersphere/metersphere/assets/30038088/38d488a3-1db9-48c0-8001-9e7acd4598b0)

3.点击 【生成测试数据】，生成一堆不相关的参数
![image](https://github.com/metersphere/metersphere/assets/30038088/5b96fe41-6441-4ae9-a0e7-daf955d0469f)

**Comment by shenkaibo** [comment]
建议页面前端加一个校验

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，后续版本修复

**Comment by luty2018** [comment]
这个问题不做修改，建议用户按正确规则使用。
