### ISSUE TITLE
[FEATURE]接口请求返回的token等数据，希望可以设置为全局变量，供所有场景使用

### ISSUE THREAD

**Issue by zhangaiwu** [metersphere/metersphere#2987]
**请描述您的需求或者改进建议.**
接口请求返回的token等数据，希望可以设置为全局变量，供所有场景使用

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
环境配置或者场景那里都可以设置全局变量

**Comment by xulinde** [comment]
1.10.0版本已实现
![image](https://user-images.githubusercontent.com/64065190/119960660-c5108480-bfd7-11eb-9480-f1b053e0c281.png)
