### ISSUE TITLE
[FEATURE] 接口用例支持自定义添加字段，支持该字段的过滤搜索及表头搜索

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29872]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

接口用例支持自定义添加字段，支持该字段的过滤搜索及表头搜索

### 请描述你建议的实现方案

（可以在我们模板上支持添加，一般常用到下拉选、备注等字段）

**Comment by qian-kui** [comment]
支持搜索主要使用场景：1、在接口测试用例列表可以搜索或者表头放出自定义字段，可以过滤
2、可以在测试场景使用该字段进行搜索需要的测试用例
3、可以在测试计划搜索该字段值，搜出需要的用例

**Comment by luty2018** [comment]
感谢反馈，我们在v3.0会支持接口的自定义模板，允许用户添加自定义字段，同时高级搜索允许用户按自定义字段搜索。
