### ISSUE TITLE
[BUG]  测试计划执行功能用例，报告当中显示不出用例失败的数量

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#29883]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/33945037/8f2050b0-3209-4c3c-b901-49c7c26b607f)

### 重现步骤

1. 新建测试计划
2. 添加功能用例
3. 执行测试计划查看报告。

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
已修复，请升级v2.10.14版本。
