### ISSUE TITLE
[BUG]jekins 配置选择执行单个场景用例，构建时执行的是接口自动化下所有场景用例

### ISSUE THREAD

**Issue by zhangaiwu** [metersphere/metersphere#2988]
**MeterSphere 版本**
V1.9.2

**Bug 描述**
jekins 配置选择执行单个场景用例，构建时执行的是接口自动化下所有场景用例

**Bug 重现步骤**
1.  jekins 配置选择某个场景用例
2. 构建执行
3. 查看控制台输出日志

**期待的正确结果**
只执行选择的场景

**截图**
![image](https://user-images.githubusercontent.com/45023298/118787560-86871580-b8c5-11eb-995f-4083c0e46433.png)
![image](https://user-images.githubusercontent.com/45023298/118787605-8f77e700-b8c5-11eb-90e8-8f7f009d4cc5.png)

**Comment by zyyfit** [comment]
您好，这个列表不是执行的接口列表，您可以看一下下面的日志里显示执行成功的接口是否正确

**Comment by zhangaiwu** [comment]
知道了 谢谢
