### ISSUE TITLE
authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by zhaobofei** [metersphere/metersphere#29885]
### 请描述您的问题

I want to complete a performance test, but its report log always mentions an error, which is "opening a socket connection with the server 10.86.76.141/<unresolved>: 4180. I will not attempt to use SASL for authentication (unknown error)". In fact, as a server, Zookeeper is version 3.4.5 and authentication is not set because local use of JMeter pressure testing does not require authentication to cover [that]([url]()) the test case passes. However, this error is always encountered in Metersphere. May I ask if the version of Metersphere is 2.10, which is too high

**Comment by liuruibin** [comment]
在v2版本中我们已经去掉了zookeeper，你可以使用我们的安装包重新安装试试
