### ISSUE TITLE
[FEATURE]建议添加案例标签

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#299]
**请描述您的需求或者改进建议.**
建议添加案例标签

**请描述你建议的实现方案**
测试案例管理:
1.项目案例库-管理所有案例，各个迭代版本案例综合管理
2.案例添加标签-标签标识不同的迭代版本
满足可以快速查找指定版本的测试案例，也可以快速查找某个模块的各个版本的案例变更

**Comment by xulinde** [comment]
您好，平台已经增加该功能，您可以升级到最新版本体验
