### ISSUE TITLE
[BUG]场景导入用例列表，窗口只展示了4条数据，其余的要滚动才能查看

### ISSUE THREAD

**Issue by Triangel1314** [metersphere/metersphere#2991]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/56533158/118789366-47f25a80-b8c7-11eb-9794-abe7ce50a87f.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.9.3版本已经修复了这个问题，请更新后查看
