### ISSUE TITLE
[BUG]接口测试-接口自动化-操作【接口列表导入】，弹出接口导入弹窗，列表页面中“标签”字段展示错乱

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2992]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
[BUG]接口测试-接口自动化-操作【接口列表导入】，弹出接口导入弹窗，列表页面中“标签”字段展示错乱
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/118802357-9bb77080-b8d4-11eb-853e-37f0a36e3d5d.png)

**Comment by zyyfit** [comment]
您好，1.9.3版本已修复了这个问题，请升级后再看一下

**Comment by xulinde** [comment]
1.9.3已修复
