### ISSUE TITLE
[FEATURE]建议接口测试-接口自动化，场景步骤中的用例列表，增加列字段“标签”的展示，用于注释每个步骤接口的作用！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2993]
**请描述您的需求或者改进建议.**

建议接口测试-接口自动化，场景步骤中的用例列表，增加列字段“标签”的展示，用于注释每个步骤接口的作用！

**请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/54024064/118802634-f05aeb80-b8d4-11eb-92f3-fde55d8274a5.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化

**Comment by luty2018** [comment]
再加标签内容就太多了，如果规范用例或场景的命名这里是能达到你期望的效果的。
