### ISSUE TITLE
[FEATURE]系统设置-环境配置-通用配置 页面，建议增加变量注释列，用于说明每个变量的含义、作用

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#2994]
**请描述您的需求或者改进建议.**

系统设置-环境配置-通用配置 页面，建议增加变量注释列，用于说明每个变量的含义、作用

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/54024064/118802996-64958f00-b8d5-11eb-8745-ea7d9838cead.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化

**Comment by zyyfit** [comment]
您好，最新版已增加这个功能，请升级后使用
![图片](https://user-images.githubusercontent.com/73461316/123750126-cd1a5780-d8e8-11eb-936e-d24cdd0b73ce.png)
