### ISSUE TITLE
[BUG] 用例管理，从系统导出用例，补充完善用例步骤再导入系统，步骤没有拆分全放到一个框了

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#29947]
### 联系方式

wannaspace@163.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

功能用例管理，从系统导出用例，补充完善用例步骤再导入系统，步骤没有拆分全放到一个框了

### 重现步骤

1、从系统导出用例
2、补充完善用例步骤再导入系统
3、检查系统上操作步骤

没有拆分全放到一个框了
![用例步骤不能自动拆分了](https://github.com/metersphere/metersphere/assets/79577571/2cb1f3fb-699d-4262-9ab8-99915eccd4ab)

### 期待的正确结果

期望和旧版本一样，支持导入后自动拆分展示步骤【之前没升级时候用过 是可以拆分展示的】

**Comment by qian-kui** [comment]
![image](https://github.com/metersphere/metersphere/assets/79577571/e6093fbc-0c44-4072-98fc-ebb3f4a50542)

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，已复现，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/c299fd85-e9bf-43e0-8c11-0d0afd90d36c)
该问题的实现逻辑如上，感谢理解和支持。
