### ISSUE TITLE
执行场景用例时，当步骤超过20+时，容易出现错误

### ISSUE THREAD

**Issue by mingliang1859** [metersphere/metersphere#29955]
### 联系方式

1594768701@qq.com

### MeterSphere 版本

2.10.11

### 使用外置数据库

否

### 问题描述

点击调试场景用例，提示报错
  Connection prematurely closed BEFORE response

点击浏览器刷新按钮，页面显示 
  {"success":false,"message":"finishConnect(..) failed: Connection refused: /172.30.10.14:8004","data":null}

![Snipaste_2024-03-29_16-45-20](https://github.com/metersphere/metersphere/assets/84176890/320190c1-a813-42e8-b163-7bddcbb56380)

### 重现步骤

调试场景用例，场景包含20+的不同用例的步骤

**Comment by 13290445582** [comment]
您好，建议您增加api-test的内存大小，资源的大小目前无很好的解决方案，感谢理解与支持。
