### ISSUE TITLE
每次升级都报错，之前配置文件的信息被覆盖了，每次升级后都要重新配置，我晕。。应保留之前的配置文件信息[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#2995]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2

**Bug 描述**
简要描述您碰到的问题
每次升级都报错，之前配置文件的信息被覆盖了，每次升级后都要重新配置

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应保留之前的配置文件信息

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/118805716-d3c0b280-b8d8-11eb-8f52-ea2267a0cedc.png)

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/1301
