### ISSUE TITLE
[BUG]v2.20.12，性能测试报告 测试概览 页面有三处数据错误，测试详情有一处错误

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#29950]
### 联系方式

王进

### MeterSphere 版本

v2.10.12

### 使用外置数据库

否

### 问题描述

[BUG]v2.20.12，性能测试报告 测试概览 页面有三处数据错误，测试详情有一处错误

### 重现步骤

1.测试概览页面 响应 和90%响应，数值错误，还有response time
<img width="1265" alt="1711697345558" src="https://github.com/metersphere/metersphere/assets/76033005/821355f7-d941-4f9e-b726-e48ccfa7aab2">

下图为聚合报告页面，这个页面的j聚合报告值之前也是错误的，后来瑞斌修复了。
<img width="1265" alt="1711697379556" src="https://github.com/metersphere/metersphere/assets/76033005/0aeb73cc-0b89-4989-a89b-1697961629f2">

2. 同样的错误，在另外一个客户这里也出现了。
<img width="1138" alt="377d22140f63ee90aef2bc7b356d6ee" src="https://github.com/metersphere/metersphere/assets/76033005/9be1a169-7f5f-40c5-9b6d-ac90b8bbc54c">

3. 测试详情页面也有同样的问题。
<img width="1130" alt="1711697686900" src="https://github.com/metersphere/metersphere/assets/76033005/97de57da-4bbd-4ca2-b203-578c56b22abc">

### 附加信息

1. 该问题在两个客户那里已经出现，之前给瑞斌看过，瑞斌修复了聚合报告那里的错误。

**Comment by 13290445582** [comment]
问题已修复，请升级v2.10.14版本。
