### ISSUE TITLE
[FEATURE]用户组与权限更细化-管理项目管理员有开启共享的权限

### ISSUE THREAD

**Issue by daviadong** [metersphere/metersphere#29968]
### MeterSphere 版本

v2.10.12

### 请描述您的需求或者改进建议

目前项目中，我给项目管理员授予了新增用户组与权限的功能，使其可以创建用户组，但创建用户组时选择开启“工作空间共享”的权限我想关闭，但目前权限不到这层级。
![11711727156_ pic](https://github.com/metersphere/metersphere/assets/51897467/e9e6a5db-fc21-4491-a99b-d4c1f307b18b)
![21711727157_ pic](https://github.com/metersphere/metersphere/assets/51897467/1dd19c00-bc2a-49e8-ad22-6384eef668a1)

**Comment by luty2018** [comment]
目前建议通过规范去约束创建的行为了，v2版本暂时不会做这个功能哈。
月底发布的v3可以支持，可以到时候关注一下。
