### ISSUE TITLE
[BUG]在环境设置中，当恰好是第二页或者第三页的第一条，填写的变量名跟原有变量重复时，再删除该新增变量，此时，会导致所有的变量都展示不出来，包括第一页的所有变量，也无法进行变量的添加

### ISSUE THREAD

**Issue by zhanglijunSylvia** [metersphere/metersphere#29986]
### 联系方式

18667048031

### MeterSphere 版本

版本:   v2.10.12-lts-e87e920c

### 使用外置数据库

否

### 问题描述

![749363BC-B7E8-4669-AF29-C86E859C0053](https://github.com/metersphere/metersphere/assets/50434006/d6335203-2e78-4b68-843a-3793d79a33d2)

最后的现象如图所示

### 重现步骤

1、在环境配置种，恰好通用配置种设置的变量有 10 个，在第二页的第一个进行变量的添加，
2、如果此时变量名重复，会有重复提示
3、点击删除按钮
4、就会出现此现象，第一页的变量全部消失，也无法新增变量

### 期待的正确结果

在第 3 步的时候，删除变量，只删除当前设置的重复变量，不能影响第一页的所有变量的展示

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
