### ISSUE TITLE
[BUG]接口基础信息中有状态字段，但是在模版字段中没有定义接口模板下的“状态”

### ISSUE THREAD

**Issue by hihihinewer** [metersphere/metersphere#29993]
### 联系方式

bamuxian@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

接口基础信息中有状态字段，但是在模版字段中没有定义接口模板下的“状态”，导致无法对状态字段进行编辑

### 重现步骤

1. 新建接口，查看界面有“状态”, 
![image](https://github.com/metersphere/metersphere/assets/31436142/23899ccf-1f79-4b88-a208-ab5fec4af312)

2. 进入项目-模版管理，模版字段，查看是否有适用于接口模板的状态字段
![image](https://github.com/metersphere/metersphere/assets/31436142/4ca7ef81-90d8-4026-895f-dea8a907b973)

### 期待的正确结果

存在适用于接口模板的状态字段，可以编辑 添加值

**Comment by 13290445582** [comment]
您好，经过反馈，V2暂不支持，感谢理解。
