### ISSUE TITLE
[FEATURE]接口测试支持数据库断言

### ISSUE THREAD

**Issue by tuyula** [metersphere/metersphere#30]
**请描述您的需求或者改进建议.**

能否添加数据库断言

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
@tuyula 麻烦补充下 issue 的标题，已经针对这个需求更详细一点的描述
您提的其他几个也麻烦更新下 #

**Comment by 2115055005** [comment]
类似jmeter上的功能，可以连接数据库，通过写SQL的形式拉取数据库数据与接口返回的数据进行比对

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
