### ISSUE TITLE
[FEATURE]接口测试新增功能建议

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#300]
**请描述您的需求或者改进建议.**
添加接口文件上传功能、添加数据库查询功能

**请描述你建议的实现方案**
1.接口测试支持文件上传
2.接口测试支持数据库查询数据作为参数或者断言判断;以及delete数据清理

**Comment by zyyfit** [comment]
接口测试已支持测试上传文件接口，支持sql接口
