### ISSUE TITLE
[BUG]脑图部分case部分丢失问题

### ISSUE THREAD

**Issue by cfsunjian** [metersphere/metersphere#30018]
### 联系方式

41859978 小文

### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/51786370/ebb8915d-5a90-4b27-a2e3-0ba8ebab6fa7

脑图模块下增加两条用例，保存成功后，再次进来发现该用例丢失

### 重现步骤

脑图模块下增加两条用例，保存后发现该用例丢失

### 期待的正确结果

正确保存成功

**Comment by 13290445582** [comment]
您好，未复现您的这种情况，建议升级至最新版本。

**Comment by youliyuan-fit2cloud** [comment]
脑图编辑-添加用例后，如果没有打标签“用例” 或者其他标签“模块”是不会保存的。
