### ISSUE TITLE
[FEATURE]脑图查看用例的时候，显示“测试步骤”和“测试结果”标签，方便查看

### ISSUE THREAD

**Issue by ld469** [metersphere/metersphere#30012]
### MeterSphere 版本

v2.10.13-lts-163a8232

### 联系方式

ld469

### 请描述您的需求或者改进建议

使用脑图查看测试用例的时候，在测试步骤和测试结果那插入“测试步骤”和“测试结果”标签，方便查看。

**Comment by luty2018** [comment]
用例可能被加入到多个测试计划， 是要展示最后一次的执行结果吗，目前能在测试计划里面以脑图形式看执行过的用例结果，是否满足需求？
