### ISSUE TITLE
导出的PDF报告，展示不全，估计是太大太长。。[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#3002]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3

**Bug 描述**
简要描述您碰到的问题
导出的PDF报告，展示不全，估计是太大太长。。

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
展示全部内容

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/118909530-bf6ecb00-b955-11eb-9dfc-3e7fe52fadcb.png)

**Comment by zyyfit** [comment]
您好，请问这是导出的什么报告？
