### ISSUE TITLE
[BUG]MeterSphere 1.9.1，启用资源池失败，报错(JSON String, Number, Array, Object or token 'null', 'true' or 'false

### ISSUE THREAD

**Issue by wuwoyiran** [metersphere/metersphere#3003]
使用MeterSphere 1.9.1，
发现的问题：机器1和机器2均部署了node-controller节点，但是启动资源池失败，后台报错：nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'OK': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
![image](https://user-images.githubusercontent.com/33147344/118911258-7c622700-b958-11eb-85a4-ad925c1ec2fa.png)

当使用v1.6版本时可以启用成功。

**Comment by zyyfit** [comment]
您好，目前的最新版已经是1.9.3版本了，请升级到最新版试一下

**Comment by wuwoyiran** [comment]
你好，用1.9.3的版本还是会报这个问题~
![image](https://user-images.githubusercontent.com/33147344/119290707-ae88c700-bc7f-11eb-8300-a009919208a5.png)
