### ISSUE TITLE
环境配置点击确定时有时候总是报错，即使啥也没有修改[BUG]

### ISSUE THREAD

**Issue by wk-886** [metersphere/metersphere#30056]
### MeterSphere 版本

v2.10.12-lts-a7d7c194

### 使用外置数据库

否

### 问题描述

环境配置点击确定时有时候总是报错，即使啥也没有修改，但是退出页面后再重新进来有时候又会正常

### 重现步骤

场景列表接口自动化新增接口case后保存，再去环境配置添加模块-更新-确定后，提示IP地址错误，次数不管怎么修改都报错，即使啥也不改点确定也报错；退出界面后再点击其他页面时，再重新进入环境配置又会恢复正常

**Comment by wk-886** [comment]
![Uploading 环境配置确定报错.png…]()

**Comment by LukaDoncic-Magic** [comment]
您好，未复现该问题，您能提供一下录制视频吗？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
