### ISSUE TITLE
提交的缺陷，没换行，图片也没展示 [BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#3005]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3

**Bug 描述**
简要描述您碰到的问题
提交的缺陷，没换行，图片也没展示

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应换行展示，图片展示成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/118913051-52f6ca80-b95b-11eb-9339-cb788ca26013.png)
![image](https://user-images.githubusercontent.com/37016695/118912914-1c20b480-b95b-11eb-9ec0-2249cf64eabc.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.11.0已修复
