### ISSUE TITLE
[BUG]【测试跟踪】 功能用例使用自定义id,在测试计划中通过 ID 筛选用例，无法关联筛选出的所有用例

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#30059]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

项目的功能用例使用的是自定义 id，是用 Excel 编辑好用例导入到平台的，在测试计划中关联用例时，通过自定义 ID 筛选用例，关联筛选出的所有用例，页面提示关联成功，但测试计划查不到关联的用例

### 重现步骤

1、进入项目设置-应用管理-测试跟踪，开启测试用例自定义 ID
2、使用 Excel 编写功能用例，功能用例使用自定义 ID, 将用例导入到平台
3、创建一个测试计划，在测试计划中关联功能用例，在关联功能用例时，使用自定义 ID 筛选功能用例，并将筛选出来的所有功能用例加入到测试计划中

### 期待的正确结果

在测试计划中使用自定义ID 筛选用例时，可以一次性将筛选出的用例关联到测试计划中

### 附加信息

https://github.com/metersphere/metersphere/assets/45531073/3ac120c3-6eb1-4c9d-bc0e-5d3d620768b1

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
问题已修复，请升级v2.10.14版本。
