### ISSUE TITLE
[BUG] 从测试计划列表的报告中点击分享链接，代码逻辑有bug，会导致分享的链接，隔天再次访问的时候失效。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#30061]
### MeterSphere 版本

v2.10.11-lts，v2.10.13-lts

### 使用外置数据库

否

### 问题描述

从测试计划列表的报告中点击分享链接，代码逻辑有bug，会导致分享的链接，隔天再次访问的时候失效。

### 重现步骤

1. 在测试计划列表中点击查看报告 
2. 点击分享链接
3. 隔天再次访问，就会失效
（报告分享链接时间大于30天） 从代码上看，跟这个没太大关系。

<img width="1434" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/4db53f42-f586-4e88-91ae-e1b20a74dae8">

<img width="864" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/c6aa8fd7-87ec-46e2-9bbf-f856a732db94">
<img width="783" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/018f8038-bcde-42c7-be62-031dd61e1492">
<img width="812" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/fec03d29-f8af-40ed-b721-1996ea5d9fef">

此时应该是测试计划id，而不是报告id。这里查到为null
<img width="850" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/303ea618-a6ab-41f2-a915-30f0298e62f4">

走的这段逻辑，只要大于1天，就会被删除
<img width="1192" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/675511c4-0b6b-498d-a1e7-dfbba9b4b3ae">

**Comment by hao65103940** [comment]
这是个问题。为什么要关掉？是后面版本修复了吗？

**Comment by Zhuzhiming123zhu** [comment]
您好，这个报告分享的有效期为24小时，24小时后就会过期

**Comment by Zhuzhiming123zhu** [comment]
![image](https://github.com/metersphere/metersphere/assets/166777277/5d9a3ad8-6ebc-4b94-aafb-f51e05cb43c6)
您好，感谢您提出的问题，设计是这样的，测试计划报告分享有效期为24小时，24小时后再次访问链接是会失效的。

**Comment by wxg0103** [comment]
感谢您的反馈，我们将在v2.10.17-lts版本修复这个问题，祝您生活愉快！！！

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级至v2.10.16版本使用。
