### ISSUE TITLE
[FEATURE]UI测试增加对驱动driver的操作能力，这样可以实现一些客户端认证的web应用登录的难题

### ISSUE THREAD

**Issue by XiangjunZhao475720456** [metersphere/metersphere#30066]
### MeterSphere 版本

v2.10.12-lts

### 请描述您的需求或者改进建议

[FEATURE]UI测试增加对驱动driver的操作能力，这样可以实现一些客户端认证的web应用登录的难题

### 请描述你建议的实现方案

[FEATURE]UI测试增加对驱动driver的操作能力，这样可以实现一些客户端认证的web应用登录的难题

### 附加信息

[FEATURE]UI测试增加对驱动driver的操作能力，这样可以实现一些客户端认证的web应用登录的难题

**Comment by luty2018** [comment]
感谢建议， 我们将在v3.0版本讨论规划

**Comment by XiangjunZhao475720456** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件我已收到，我会尽快处理你的邮件……

**Comment by XiangjunZhao475720456** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件我已收到，我会尽快处理你的邮件……
