### ISSUE TITLE
[BUG]测试计划报告中的功能用例统计分析不显示失败用例

### ISSUE THREAD

**Issue by haipeng-fit2** [metersphere/metersphere#30065]
### MeterSphere 版本

v2.10.13

### 使用外置数据库

否

### 问题描述

在测试计划的报告统计一览，功能用例统计分析中只在全部用例中显示了失败的用例，而在不显示失败用例处不显示，对应的阻塞用例是正常显示的
<img width="1693" alt="image" src="https://github.com/metersphere/metersphere/assets/81673899/6e5fc1a4-1e04-4d21-b062-e8e55914ba4d">
<img width="1694" alt="image" src="https://github.com/metersphere/metersphere/assets/81673899/e5a41aa2-061a-4a98-9968-4cdbaa16805d">
<img width="1724" alt="image" src="https://github.com/metersphere/metersphere/assets/81673899/bdd7c598-01b2-4cf1-a7e5-b95a75bd951f">

### 重现步骤

1、创建测试计划，添加功能用例
2、确定功能用例执行结果
3、进入报告统计，查看功能用例统计分析

**Comment by 13290445582** [comment]
感谢反馈，已有重复issue，已关联。https://github.com/metersphere/metersphere/issues/28625
