### ISSUE TITLE
[BUG]用excel模板导入用例，如果用例步骤有多行，导入ms后每一行被分割成了一个步骤

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#3008]
**MeterSphere 版本**
1.9.1

**Bug 描述**
用excel模板导入用例，如果用例步骤有多行，导入ms后每一行被分割成了一个步骤

**Bug 重现步骤**
1.  导入的excel见附件“test.xls”
2. 查看ms上生成的用例
3. 步骤2、步骤3被分割成了多个步骤，见附件“实际的样子”

**期待的正确结果**
导入metersphere时，提取步骤编号来确定生成步骤，而不是根据换行符生成步骤，见附件“期待的样子”

**截图**
[test.xls](https://github.com/metersphere/metersphere/files/6512673/test.xls)
![实际的样子](https://user-images.githubusercontent.com/5140999/118915371-699f2080-b95f-11eb-9a9a-0c77acc3929e.png)
![期待的样子](https://user-images.githubusercontent.com/5140999/118915375-6ad04d80-b95f-11eb-8ec3-0980c41a6dbd.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
1.10版本已修复
