### ISSUE TITLE
[FEATURE] 期望接口返回信息支持搜索

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#30083]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/79577571/471480e8-062e-4378-aaef-20cd6eed7777)
响应体内容往往比较多，直接使用浏览器 ctrl+f 都不能搜，不便于使用

**Comment by luty2018** [comment]
你好， 我们在v3.0版本支持了这个功能， 预计月底发布
