### ISSUE TITLE
[BUG]【项目环境】通用变量处存在分页，在其他页输入参数名后，点击后面输入框，会跳转到第一页。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#30090]
### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

【项目环境】通用变量处存在分页，在其他页输入参数名后，点击后面输入框，会跳转到第一页。

### 重现步骤

【项目环境】通用变量处存在分页，在其他页输入参数名后，点击后面输入框，会跳转到第一页。
![image](https://github.com/metersphere/metersphere/assets/104960608/60e1cd69-2781-4449-880c-01eae54c5a00)
![image](https://github.com/metersphere/metersphere/assets/104960608/400d8ad5-4e96-4260-a204-c05563b4738f)

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，后续版本修复该问题。

**Comment by LukaDoncic-Magic** [comment]
问题已修复，请升级到v2.10.14-lts
