### ISSUE TITLE
性能测试提升报告生成错误，但是过几秒钟报告正常产生[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#301]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2
**Bug 描述**
简要描述您碰到的问题
性能测试提升报告生成错误，但是过几秒钟报告正常产生[BUG]
**Bug 重现步骤**
1.进行任意性能测试

**截图**
![image](https://user-images.githubusercontent.com/30932762/91651959-4e387080-eac5-11ea-9b4b-3410644752e7.png)
![image](https://user-images.githubusercontent.com/30932762/91651961-54c6e800-eac5-11ea-9e13-acbb5da80b36.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决
