### ISSUE TITLE
[BUG]接口测试-接口定义-编辑接口-测试有几率报错json错误

### ISSUE THREAD

**Issue by yeohjesus** [metersphere/metersphere#3010]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
接口测试-接口定义-编辑接口-测试有几率报错json错误
**Bug 重现步骤**
1.  新建接口-json请求内容{“test”:"test"}
2. 保存接口-关闭标签页 
3. 编辑接口-修改请求内容${data}
4.点击测试，选择环境执行 
5.请求参数中JsonSchema有预期外的参数（如图，或历史请求内容）

**期待的正确结果**
正确情况下应该是什么样的？
正常执行请求内容为未定义的参数data，或前置脚本中定义的data值
**截图**
如果有截图，请附上截图.
<img width="776" alt="修改请求内容报错4" src="https://user-images.githubusercontent.com/18098023/118930084-e211db80-b977-11eb-8faf-d731c1024a36.png">
<img width="736" alt="修改请求内容报错3" src="https://user-images.githubusercontent.com/18098023/118930087-e3430880-b977-11eb-9c3e-1e08ed84c74a.png">
<img width="451" alt="修改请求内容报错2" src="https://user-images.githubusercontent.com/18098023/118930094-e4743580-b977-11eb-9683-6de1bf7ff878.png">
<img width="655" alt="修改请求内容报错" src="https://user-images.githubusercontent.com/18098023/118930098-e50ccc00-b977-11eb-9e6c-4052497890c0.png">

**Comment by zyyfit** [comment]
您好，没有复现出来，我们尝试定位一下
