### ISSUE TITLE
[BUG]  次数循环里面的成功后继续功能不生效

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30111]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

次数循环里面的成功后继续功能不生效

### 重现步骤

次数循环里面的成功后继续功能不生效，如图还是循环了五次
![image](https://github.com/metersphere/metersphere/assets/103925124/04354859-2fa7-4865-9972-2aa6861c1866)

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by luty2018** [comment]
这里不作修改了，确实是不支持。
如果要进行条件判断再循环，建议使用while循环来覆盖这个场景。
v3 已经下掉了这个功能。
