### ISSUE TITLE
[BUG]性能测试，已存在的文件不能删除

### ISSUE THREAD

**Issue by zhangfeilynu** [metersphere/metersphere#3011]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1-b1
**Bug 描述**
简要描述您碰到的问题
性能测试，加载同名文件，提示已存在，请先删除同名文件，但是没有删除功能
**Bug 重现步骤**
1. 性能测试模块，创建测试
2. 加载jmx文件，上传本地demo.jmx，之后选中确定
3. 加载data.csv文件，上传本地csv文件，之后选中确定
4. 保存测试
5. 编辑测试，再次加载文件(或者jmx文件)，上传本地data.csv（或者demo.jmx）
6.步骤5提示data.csv已存在，请先删除
**期待的正确结果**
正确情况下应该是什么样的？
能够删除已存在的文件或者jmx文件
**截图**
如果有截图，请附上截图.
<img width="1068" alt="同名文件不能上传" src="https://user-images.githubusercontent.com/18474882/118930367-3cab3780-b978-11eb-82c6-511479e94908.PNG">

**Comment by zyyfit** [comment]
您好，删除功能在系统设置里，可能不太好找，我们考虑优化一下
![图片](https://user-images.githubusercontent.com/73461316/119110161-6e91cc00-ba54-11eb-8d2d-a7204a68469d.png)
