### ISSUE TITLE
[BUG] 欧尼桑 柳俊星 5i5j: 重定向本身应该没问题，不过我现在是想取消重定向，但是好像取消后并没生效

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#3012]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
欧尼桑 柳俊星 5i5j:
重定向本身应该没问题，不过我现在是想取消重定向，但是好像取消后并没生效

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
欧尼桑 柳俊星 5i5j:
重定向本身应该没问题，不过我现在是想取消重定向，但是好像取消后并没生效

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，未能复现该问题，请升级到最新版本再试下吧
