### ISSUE TITLE
[FEATURE]建议接口测试增加重试次数的全局控制参数

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#3013]
**请描述您的需求或者改进建议.**
作为接口测试人员，我希望 MeterSphere 平台中在接口自动化-场景测试中支持对单接口执行增加重试次数的全局控制参数。自动化测试执行时，如果单接口执行失败，则根据此配置参数进行重试，如有成功，则继续进行后续的场景节点，如果重试全失败，则确认接口调用失败。这样可以过滤偶发的网络因素对最终的测试结果带来的影响，同时对测试成功率也有一定的保障。

**请描述你建议的实现方案**
增加接口重试次数参数，默认为1，范围1-5

**Comment by xulinde** [comment]
后面版本会考虑加

**Comment by Andyguo5891** [comment]
查看新版本已支持类似功能，
