### ISSUE TITLE
[BUG]导入的脚本中带事务，导入后事务控制器无法正常显示，应与添加新事物控制器显示的样式一致

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3014]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题
导入的脚本中带事务，导入后事务控制器无法正常显示，应与添加新事物控制器显示的样式一致
**Bug 重现步骤**
1.  接口自动化模块导入包含事务的jmx脚本
2. 导入后事务控制器无法正常显示
3. 与新增的事务控制器显示不一致
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应与添加新事物控制器显示的样式一致
**截图**
如果有截图，请附上截图.
<img width="718" alt="44" src="https://user-images.githubusercontent.com/83771182/118942328-3079a700-b985-11eb-830e-4b00d53ee28e.png">

**Comment by zyyfit** [comment]
1.10.0版本已修复

**Comment by zyyfit** [comment]
1.10.0版本已修复

**Comment by zyyfit** [comment]
1.10.0版本已修复
