### ISSUE TITLE
接口自动化场景变量中的CSV文件，无法正确读取CSV的变量值

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#30148]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

接口自动化中，在场景变量中，当CSV文件有多列且部分列缺少值时，部分列的参数无法正确读取。
CSV文件截图：
<img width="1121" alt="截屏2024-04-09 上午11 26 58" src="https://github.com/metersphere/metersphere/assets/34637801/eccd111c-85d4-441f-81b5-748855fd98b0">
<img width="767" alt="截屏2024-04-09 上午11 27 31" src="https://github.com/metersphere/metersphere/assets/34637801/87148787-d8b4-43c5-b9a3-9e3539a95992">
执行脚本打印截图：
<img width="1057" alt="截屏2024-04-09 上午11 28 18" src="https://github.com/metersphere/metersphere/assets/34637801/81dadd1d-0cb7-46c6-8ce6-4128b911b3ab">
脚本打印结果：
<img width="959" alt="截屏2024-04-09 上午11 28 58" src="https://github.com/metersphere/metersphere/assets/34637801/74aa3883-b8da-4444-87e4-664701e99c19">

### 重现步骤

1.创建一个接口自动化场景
2.上传CSV文件到场景变量中，部分列有值，部分列没有值
3.在接口自动化场景中添加一个循环控制器，设置循环一次
4.在循环控制器内自定义一个脚本打印CSV中的变量值

### 期待的正确结果

能正确读取和打印出目标CSV列的变量值

**Comment by fit2-zhao** [comment]
已经确认过，不是缺陷，目前平台机制就是如此，使用的底层测试引擎JMeter也是相同逻辑。
