### ISSUE TITLE
[BUG]xmind测试用例，内容有换行导入之后，无换行

### ISSUE THREAD

**Issue by easu** [metersphere/metersphere#3016]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是1.9.2

**Bug 描述**
xmind格式的测试用例，比如预期结果含有换行时，导入成功后，无换行

**Bug 重现步骤**
1.  准备1份xmind 测试用例，内容含有换行
2. 测试用例，导入xmind
3. 
4. 

**期待的正确结果**
导入成功后，内容依然有换行

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/17491657/118947716-31610780-b98a-11eb-8b17-de782c6c670a.png)
![image](https://user-images.githubusercontent.com/17491657/118947810-49d12200-b98a-11eb-9b47-e931001fc4ee.png)

**Comment by zyyfit** [comment]
您好，这边没有复现呢，能描述一下具体复现步骤吗

**Comment by zyyfit** [comment]
您好，这边没有复现呢，能描述一下具体复现步骤吗
