### ISSUE TITLE
[BUG]配置禅道同步时测试连接报错

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#30179]
### 联系方式

张树彬

### MeterSphere 版本

2.10.10LTS

### 使用外置数据库

否

### 问题描述

神道版本18.7，禅道链接使用了https协议，并且做了证书校验，浏览器可以访问，但需要导入一个p12的证书。
在MS中配置禅道同步时测试连接提示：“
I/O error on GET request for "https://172.31.0.254:11100/api-getsessionid.json": Certificate for <172.31.0.254> doesn't match any of the subject alternative names: [”

### 重现步骤

1. 下载禅道插件，上传至MS
2. 在MS中配置禅道信息，点击测试链接后报错

### 期待的正确结果

可以正常连接禅道

### 附加信息

![1712673171375](https://github.com/metersphere/metersphere/assets/77324661/4a46d3a1-8cd2-4c4f-b08a-f957ab25fa64)

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，目前暂不支持私有证书上传功能，已转为需求
