### ISSUE TITLE
[BUG]【性能测试】将项目管理员的删除报告取消勾选，性能测试报告无法导出和分享、再次执行

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#30182]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

修改项目管理员权限，取消删除报告权限，性能测试报告无法导出报告、分享报告、再次执行

### 重现步骤

1、进入【系统】-【用户组与权限】，将性能测试报告，删除报告去掉
2、进入【性能测试】-【报告】，点击分享报告、导出报告、再次执行

### 期待的正确结果

取消删除报告，不影响导出报告、分享报告、再次执行等权限

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/7211d7a6-a3f2-4c27-8b16-05483245bd2b)

![image](https://github.com/metersphere/metersphere/assets/45531073/cc49719e-1da6-4bba-9e45-f07379acaf6e)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.15已修复，请升级。
