### ISSUE TITLE
[BUG] windows server 安装 node-exproter，ms监控不到，不出数据，但是普罗米修斯可以自动发现。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3018]
**MeterSphere 版本**
V1.9.3

**Bug 描述**
windows server 安装 node-exproter，ms监控不到，不出数据，但是普罗米修斯可以自动发现。

**Bug 重现步骤**
1.  winserver上安装node-exproter  地址：https://github.com/prometheus-community/windows_exporter/releases/tag/v0.16.0
2. ms性能测试配置对应地址
3. 开始压测任务，查看监控图

**期待的正确结果**
ms能监控到数据

**截图**
没有数据：
![image](https://user-images.githubusercontent.com/44999044/118951252-894d3d80-b98d-11eb-8423-5a18ff33f24d.png)

普罗米修斯是发现了的：
![image](https://user-images.githubusercontent.com/44999044/118951457-b0a40a80-b98d-11eb-87ac-ca88072b38c2.png)

**Comment by LimonFHM** [comment]
?

**Comment by mexth** [comment]
有进展么,也遇到一模一样的问题.现象也一样

**Comment by mexth** [comment]
在windows server上使用的windows exporter和官方的node exporter里面的metrics不一样,导致metersphere里面预置的查询命令失效导致的这个问题.不知道官方有没有计划修复一下这个问题, windows server虽然使用率不是特别高,还是经常会遇到的. metersphere里面添加监控时区分一下windows exporter和node exporter感觉应该就OK了.

**Comment by LimonFHM** [comment]
@zyyfit @fit2cloudrd 请问有进展了么

**Comment by liuruibin** [comment]
升级到最新版，添加自定监控 
![image](https://user-images.githubusercontent.com/23045261/135230408-a53ea7a2-6ecf-4672-9d62-d94149190f14.png)
