### ISSUE TITLE
[BUG]性能测试，由场景自动化用例转化为性能测试时，场景自动化用例设置的 csv文件会自动由 1 个变成 2 个

### ISSUE THREAD

**Issue by zhanglijunSylvia** [metersphere/metersphere#30184]
### 联系方式

18667048031

### MeterSphere 版本

版本:   v2.10.12-lts-e87e920c

### 使用外置数据库

否

### 问题描述

性能测试，由场景自动化用例转化为性能测试时，场景自动化用例中的场景变量使用的的 csv文件会自动由 1 个变成 2 个。
场景自动化设置的场景变量内容
![image](https://github.com/metersphere/metersphere/assets/50434006/99ecbe85-5d74-4ec0-84da-d770c2e97a30)
创建性能测试后，变成 2 个
![image](https://github.com/metersphere/metersphere/assets/50434006/a91f01fa-eb1c-4f9d-8d03-c759063666e8)

csv文件内容如下：

### 重现步骤

1、场景自动化用例创建，场景变量中使用 csv文件
2、由该场景自动化用例创建性能测试
3、文件由 1 个变成了 2 个

### 期待的正确结果

创建性能测试后，原本是什么文件还是什么文件

**Comment by LukaDoncic-Magic** [comment]
您好，未复现该问题，可以提供录屏看看嘛？

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
