### ISSUE TITLE
[FEATURE]希望脑图模式添加重复的功能用例后可以提示出具体的模块和用例名称

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#30198]
### MeterSphere 版本

v2.10.13-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

希望脑图模式添加重复的功能用例后可以提示出具体的模块和用例名称，期望版本是V2.10.x-lts版本。
目前只会模糊提示“该模块下已存在该测试用例”，如果能提示xxx模块下已存在xxx用例，对用户来说会非常友好。
<img width="945" alt="536f260e47f78570fdb573f64f138bf" src="https://github.com/metersphere/metersphere/assets/88763608/be61b1d5-0776-4586-9d95-226b212f4771">

**Comment by luty2018** [comment]
好的， 在后续小版本安排优化一下

**Comment by linfengjjj** [comment]
罗老师，预计哪个小版本优化呢
