### ISSUE TITLE
[BUG]v3.0.0-rc12没有测试计划页面

### ISSUE THREAD

**Issue by everiori** [metersphere/metersphere#30196]
### MeterSphere 版本

v3.0.0-rc12

### 使用外置数据库

否

### 问题描述

安装v3.0.0-rc12版本，发现测试计划页面没了

### 重现步骤

安装v3.0.0-rc12版本，发现测试计划页面没了

**Comment by liuruibin** [comment]
您好，v3版本还在紧张的开发中，请您谅解
