### ISSUE TITLE
[BUG]不同场景嵌套引用，相同场景变量只会用第一个场景中的变量值

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#3019]
**MeterSphere 版本**
   MeterSphere 版本是1.9.3

**Bug 描述**
 不同场景嵌套引用，相同场景变量只会用第一个场景中的变量值，如下场景步骤，在场景B中，场景B和引用的场景A均使用了场景A的变量值

**Bug 重现步骤**
1.  场景A设置了 场景变量x
2.  场景B也设置 场景变量x
3.  场景B中引用场景A

**期待的正确结果**
 场景A和场景B分别使用各自的场景变量

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复这个问题
