### ISSUE TITLE
[QUESTION]1.20.20版本，接口列表加载时候响应很慢，提速的思路？

### ISSUE THREAD

**Issue by KyleWong2007** [metersphere/metersphere#30218]
### 请描述您的问题

点击接口列表大概有10s左右的响应时间，服务器性能满足8C16G。请问有什么限制速度的可能性和提速的思路呢？

参考：/api/definition/list/的响应速度大约80ms
<img width="693" alt="企业微信截图_17128076211517" src="https://github.com/metersphere/metersphere/assets/100743754/4227291b-441a-4e8e-8ab2-4e62dac7cf84">

**Comment by fit2-zhao** [comment]
可以尝试调整MySQL配置： “ /opt/metersphere/conf/my.cnf ” 中的参数 “innodb_buffer_pool_size” ；
根据MySQL官方文档中建议可以设置MySQL所占内存的 80% ，您可以根据自己的部署现状调整，平台默认比较小。

**Comment by KyleWong2007** [comment]
> 可以尝试调整MySQL配置： “ /opt/metersphere/conf/my.cnf ” 中的参数 “innodb_buffer_pool_size” ； 根据MySQL官方文档中建议可以设置MySQL所占内存的 80% ，您可以根据自己的部署现状调整，平台默认比较小。

有提速效果，感谢！
