### ISSUE TITLE
[FEATURE]接口测试报告希望可以增加打标功能

### ISSUE THREAD

**Issue by zhanglijunSylvia** [metersphere/metersphere#30230]
### MeterSphere 版本

版本:   v2.10.6-lts-e87e920c

### 联系方式

18667048031

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/50434006/87146b4f-371b-4fb9-bdb8-e2714b12d4c3)
如图所示，
1、如果是失败报告的，希望能增加批量增加/修改标签的功能，还有根据标签来查询，这样方便统计失败用例都是因为什么原因导致失败的
2、希望能增加批量导出报告的功能，现在只有批量删除报告

**Comment by luty2018** [comment]
好的， 感谢建议， 我们会在v3.0版本进行规划
