### ISSUE TITLE
[BUG]已生成的测试报告，进入后页面右上方仍可选择打点时间，但是选择设置后并无效果，建议已生成测试报告禁止此项的选择

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3024]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题
已生成的测试报告，进入后页面右上方仍可选择打点时间，但是选择设置后并无效果，建议已生成测试报告禁止此项的选择
**Bug 重现步骤**
1.  进入已生成的历史 测试报告
2. 进入后选择页面右上方打点时间进行设置
3. 设置后并无效果
4. 建议已生成测试报告禁止此项的选择

**期待的正确结果**
正确情况下应该是什么样的？
. 建议已生成测试报告禁止再选择打点时间
**截图**
如果有截图，请附上截图.

<img width="960" alt="1111" src="https://user-images.githubusercontent.com/83771182/118963521-177af100-b999-11eb-93b8-fc224c952e22.png">

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本优化

**Comment by zyyfit** [comment]
已经改成测试结束之后禁用下拉框
