### ISSUE TITLE
失败重跑能够支持整个场景的重跑，而不单纯只针对case，因为一般来说case都是有上下游约束的。

### ISSUE THREAD

**Issue by cocohero123** [metersphere/metersphere#30265]
### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 联系方式

363422893@qq.com

### 请描述您的需求或者改进建议

失败重跑能够提供个选项，对整个场景进行重跑，而不单纯只针对case，因为一般来说case都是有上下游约束的。
这个选项建议是具体到每个场景做选择。

### 请描述你建议的实现方案

失败重跑能够提供个选项，对整个场景进行重跑，而不单纯只针对case，因为一般来说case都是有上下游约束的。
这个选项建议是具体到每个场景做选择。

**Comment by luty2018** [comment]
感谢建议， 这个我们有考虑的， 已经在v3.0版本中进行了调整，允许用户自定义重跑策略。

**Comment by luty2018** [comment]
在执行场景的过程中，即便是有上下游的关系，重试失败的一步也不影响使用上游获取到的数据，您可以测试一下，目前从执行效率和执行结果上来看，没有需要重试整个场景的必要哦。
<img width="1150" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/6f144729-8432-4c2e-a263-bbe3ffa9ba36">
