### ISSUE TITLE
[BUG]在导入的场景中条件控制器，调试输出的log，条件控制前前是一部分，条件控制是一部分

### ISSUE THREAD

**Issue by dasandeyu** [metersphere/metersphere#3026]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.1-2cb10c1e

**Bug 描述**

**Bug 重现步骤**
1.  导入场景，在步骤中添加条件控制器。
2.如下：
![image](https://user-images.githubusercontent.com/13783632/118962323-d59d7b00-b997-11eb-8a29-842e9495ddb7.png)
3. 执行测试
4. 如下
![image](https://user-images.githubusercontent.com/13783632/118965448-485c2580-b99b-11eb-84e2-d5aa32d8d8cb.png)

**期待的正确结果**
场景中加入了条件控制器，场景的报告应该在一起。2应该为7。

**截图**

**Comment by zyyfit** [comment]
您好，1.9.2未复现这个问题，请升级后再试一下

**Comment by dasandeyu** [comment]
后续大版本我会考虑升级的，谢谢。
