### ISSUE TITLE
[BUG] 配置根据模块选择不同域名的环境，确定生域名未生效

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#30271]
### 联系方式

MeterSphere 交流群7   .dot

### MeterSphere 版本

v1.20.13-lts

### 使用外置数据库

是

### 问题描述

配置根据模块选择不同域名的环境，确定生域名未生效
接口步骤中，有提示API不存在 和原场景不存在 
该场景为导入的场景

![ms_bug_环境变量 启用条件为模块时确定后http域名未生效](https://github.com/metersphere/metersphere/assets/9674075/e75ffdfb-51e5-43de-b664-0fb78a517b6a)

![ms_bug_select_env_confirm](https://github.com/metersphere/metersphere/assets/9674075/bc4c53cd-191c-4671-8807-e5e181e10328)

![API_Not_Exist](https://github.com/metersphere/metersphere/assets/9674075/c5f7db0c-cf47-4206-92d0-2fd3cd5799e4)

### 重现步骤

如上

### 期待的正确结果

导入的场景，是否应该使用当前的场景的模块，作为域名匹配的条件，而不是用导入的场景信息来导入

**Comment by xchnshi** [comment]
功能理解有误，这里的模块列表是接口定义处的模块列表，不是接口自动化场景中的模块列表，这么看就没问题了。
但是对于导入的场景，在接口定义处没有定义模块，那么本质是生效不了的，需要接口定义也全部导入，才能应用区分模块来应用环境域名地址。

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，对于导入的场景，接口定义处如果您没有定义模块，配置的域名环境是不能生效的，您需要将接口定义也全部导入，才能根据模块区分来应用环境域名地址
