### ISSUE TITLE
[BUG]全局断言JSON-文档结构校验保存不上

### ISSUE THREAD

**Issue by liuts933** [metersphere/metersphere#30270]
### MeterSphere 版本

 v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

见 ：https://github.com/metersphere/metersphere/issues/26725#issue-1891990925
补充：主要是”JSON-文档结构校验“ 保存不上。正则没有问题。

视频联系贵司北区售前张树彬

### 重现步骤

见 ：https://github.com/metersphere/metersphere/issues/26725#issue-1891990925

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，已复现，后续版本修复

**Comment by LukaDoncic-Magic** [comment]
问题已修复，请升级到v2.10.15-lts版本
