### ISSUE TITLE
[BUG]接口场景定时任务在所有步骤都执行成功，且未存在全局前后置脚本的情况下，场景执行结果仍为error，结果有误，需定位处理

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#30284]
### MeterSphere 版本

V2.10.8lts

### 使用外置数据库

否

### 问题描述

1.创建一个场景，并设置定时任务，在定时执行时，查看报告中各场景、各请求步骤均为success的情况下，测试报告列表页该场景执行报告状态显示为Error，显示有误，需定位处理

### 重现步骤

见问题描述
（备注：后期需远程定位可联系我，并协调客户环境进行远程）

### 附加信息

![209d8a57cd9c6282eeff603d268e371](https://github.com/metersphere/metersphere/assets/92150453/97ada054-d3fd-45dd-bae9-43503a5b95fe)
![51dd1ba05781c09ee593fe8ea3a52c9](https://github.com/metersphere/metersphere/assets/92150453/9e39b786-533c-4f3e-919c-6f6e164f8a2d)
![e5eb35161618de761661e283d848d8c](https://github.com/metersphere/metersphere/assets/92150453/4dd742b7-2db8-4f76-8bb8-46e4bb979fc7)
![c98c36225fa93ca95502214528207dc](https://github.com/metersphere/metersphere/assets/92150453/f5093095-6e32-405b-b2ec-8e8506fbcdf3)

**Comment by 13290445582** [comment]
您好，本地定时未复习该问题，您可以将可执行成功场景提供出来或在我们测试环境复现下。尝试新建场景单独的定时任务是否有问题，是不是被影响到了呢。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
