### ISSUE TITLE
[BUG]数据库修改密码后，MS 上使用新密码校验不通过

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30289]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

数据库修改密码后，MS 上使用新密码校验不通过

### 重现步骤

1.数据库原密码Password123@mysql
2.更新密码为Password123^mysql
3. 在MS 上更新环境，使用新密码验证连接失败

### 期待的正确结果

数据库更新密码后，在 MS 使用新密码验证连接成功

### 附加信息

<img width="916" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/d61eabd0-0113-4de9-9df5-f892fc12a697">
![image](https://github.com/metersphere/metersphere/assets/145318182/f4422123-f384-4aeb-9933-cf116013f7a5)
![image](https://github.com/metersphere/metersphere/assets/145318182/9f41665c-bd32-4772-99a7-3e851055fce9)
![image](https://github.com/metersphere/metersphere/assets/145318182/5f4a07ca-b98e-4c85-b869-3d87b9932d5e)

**Comment by 13290445582** [comment]
您好，特殊字符可能会有转义的情况。建议设置密码不使用特殊字符，或者研究下转义解决该问题，感谢理解与支持。

**Comment by fit2cloud-lijiaxin** [comment]
更新数据库密码为password，使用旧密码在MS 上校验通过，使用新密码校验失败
![WechatIMG42](https://github.com/metersphere/metersphere/assets/145318182/87334977-a040-4a2f-b4bb-665321d94fa6)
![WechatIMG43](https://github.com/metersphere/metersphere/assets/145318182/e039ad50-1fec-4ae7-9965-3af89e422c09)

![WechatIMG44](https://github.com/metersphere/metersphere/assets/145318182/8c4894b6-4ee8-45a4-b071-56c13fb971e5)
