### ISSUE TITLE
[FEATURE]JIRA相关，失败的测试用例引用jira缺陷 ，可以显示在该用例的下方。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#303]
**请描述您的需求或者改进建议.**

测试用例失败后，需要link一个jira的缺陷。

希望在执行的测试用例内，显示链接的 jira 缺陷信息，如 ID和描述等。

同样在报告页面，能够把该缺陷的最新信息引入到报告内。

**请描述你建议的实现方案**

**Comment by pcc426** [comment]
> **请描述您的需求或者改进建议.**
> 
> 测试用例失败后，需要link一个jira的缺陷。
> 
> 希望在执行的测试用例内，显示链接的 jira 缺陷信息，如 ID和描述等。
> 
> 同样在报告页面，能够把该缺陷的最新信息引入到报告内。
> 
> **请描述你建议的实现方案**

最新的1.2.1版本似乎已经实现了。。不过对应的ID展示的不友好
