### ISSUE TITLE
[BUG]集成禅道插件打开缺陷报错

### ISSUE THREAD

**Issue by liangyao375** [metersphere/metersphere#30309]
### 联系方式

17600343201

### MeterSphere 版本

v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

方法都试过了，也装了最新插件，配置都检查成功，禅道版本：开源版18.9
![image](https://github.com/metersphere/metersphere/assets/55582967/d8a6d54e-a783-4d38-b302-1b0307a9bcc1)
[error1.log](https://github.com/metersphere/metersphere/files/14980173/error1.log)

### 重现步骤

点击缺陷管理报错，创建缺陷报错

**Comment by liangyao375** [comment]
已经修改
https://github.com/metersphere/metersphere-platform-plugin/pull/3

**Comment by 13290445582** [comment]
您好，并不确定是哪里的问题，本地所用最新版本禅道插件和18.10版本禅道未复现，您可先使用您修改后的包，感谢理解与支持。
