### ISSUE TITLE
[BUG]xmind格式的功能用例，一个步骤对应多行预期结果的时候，从xmind粘贴到ms会生成新的主题

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#30339]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

功能用例xmind格式，一个步骤对应多行预期结果的时候，从xmind粘贴到ms会生成新的主题

### 重现步骤

1、在ms上创建一个功能测试用例，一个步骤的语气结果中填入多行内容
![image](https://github.com/metersphere/metersphere/assets/88763608/2c83e171-d5ec-4283-9199-62e7f58e9a1b)
2、将这个用例导出为xmind格式
![image](https://github.com/metersphere/metersphere/assets/88763608/c9c5c1ee-c6cb-4889-9505-80e3bd5bdbe6)
3、复制xmind中的内容粘贴到ms，结果预期结果生成了新的主题
![image](https://github.com/metersphere/metersphere/assets/88763608/fe51f7e0-e784-4745-ad88-04a709e45a48)
![image](https://github.com/metersphere/metersphere/assets/88763608/f96675f0-ef0e-41e0-9ec0-0f2dff96a0ca)

### 期待的正确结果

希望不生成新的额外的主题

**Comment by 13290445582** [comment]
您好，这个问题是我们目前使用的脑图组件的默认行为，如果粘贴的文本中带有回车，就会默认创建多个子节点，目前无法修改；想满足你这个需求，可以先添加一个子节点，然后双击子节点进入编辑状态再粘贴文本即可。
相关重复issue链接：https://github.com/metersphere/metersphere/issues/27063
