### ISSUE TITLE
[BUG] idea编辑器，插件版本不兼容。idea 最新版本是2024.1

### ISSUE THREAD

**Issue by tangyin9593** [metersphere/metersphere#30342]
### 联系方式

18221797082

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

idea编辑器，插件版本不兼容。idea 最新版本是2024.1
请更新一下插件。

### 重现步骤

<img width="515" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/9757e5c4-b743-4603-a96a-05c877d144fb">
<img width="937" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/8b86bf96-351a-4c45-b4f3-571e78ab2e6c">
<img width="1431" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/858ba554-933b-4791-91a7-20a746ca1253">

### 期待的正确结果

做好插件版本的的升级。

**Comment by 13290445582** [comment]
您好，这个IDEA版本太新了，我们暂时还未支持，感谢您的理解，可以降低下你的呢IDEA版本。

**Comment by fit2-zhao** [comment]
https://plugins.jetbrains.com/plugin/18097-metersphere/edit/versions/stable/534752
已支持，等审核后就可以使用。
