### ISSUE TITLE
[BUG]Jenkins下发任务接口/automation/run/jenkins不存在错误

### ISSUE THREAD

**Issue by kxzonly** [metersphere/metersphere#3034]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3

**Bug 描述**
按照官方文档看，ms配置的地址是平台地址，后面是不带/api的
jenkins请求http://ms平台地址/api/automation/run/jenkins
但实际请求的为http://ms平台地址/automation/run/jenkins
查看了一下代码，应该是标注处少一个斜线导致的，但是为什么api在请求的时候直接被忽略了就不太清楚了
![image](https://user-images.githubusercontent.com/37934520/119092226-c1618880-ba40-11eb-87fa-0b819e90d061.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
jenkins请求http://ms平台地址/api/automation/run/jenkins

**截图**
![image](https://user-images.githubusercontent.com/37934520/119091911-587a1080-ba40-11eb-9e82-4a981c18800c.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by zyyfit** [comment]
v1.10.0版本已修复
