### ISSUE TITLE
[FEATURE]【需求】评审结束&通过的用例后面被修改后不会变成“重新提审”，导致无法筛选被修改过的用例

### ISSUE THREAD

**Issue by ywhkhb** [metersphere/metersphere#30340]
### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 联系方式

18291878104@163.com

### 请描述您的需求或者改进建议

评审结束&通过的用例后面被修改后可以变成“重新提审”，这样就能知道哪些被别人修改了，方便领导重新审核
![image](https://github.com/metersphere/metersphere/assets/107530175/9774b46f-054b-4369-9e55-2124d0ecf57b)

**Comment by Hyyfit** [comment]
需要在项目设置中，开启重新提审，才会触发这个功能
![image](https://github.com/metersphere/metersphere/assets/95834771/9099d3c0-d1d7-4c3c-8239-6862494c0105)

**Comment by ywhkhb** [comment]
这个开关启用了：![image](https://github.com/metersphere/metersphere/assets/107530175/668802e9-22eb-4b77-a845-433bcf84de95)
这个开关只有评审活动进行中时评审”通过“的被修改才会变成”重新提审“；
想要表达的意思是：评审活动已经结束了，这批评审通过的用例在后期迭代中被人修改了，或被人不小心改错了，希望这种场景下用例也可以变成”重新提审“，给一个被修改过的标志，可以筛选

**Comment by luty2018** [comment]
这个问题在v3.0中已修复， 可以后续升级使用。
