### ISSUE TITLE
[BUG]自动化场景中使用CSV循环，在测试计划中失败重试没有生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#30360]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

自动化场景中使用CSV循环，循环中有失败的用例，在测试计划中失败重试没有生效

### 重现步骤

1、创建一个使用csv+循环控制器的接口自动化场景，另其中某一次循环是失败的，其余的循环是成功的
![image](https://github.com/metersphere/metersphere/assets/88763608/da33a048-cb8e-45be-a4fb-e861e0a3bca6)
2、将该场景放到测试计划中，执行时设置失败重试，结果没有触发重试
![image](https://github.com/metersphere/metersphere/assets/88763608/16b44bef-05ca-4ba6-9a9a-c6247ad12e35)
![image](https://github.com/metersphere/metersphere/assets/88763608/04953c09-c30e-41f9-98ce-ce9616314212)

### 期待的正确结果

应该触发重试

**Comment by 13290445582** [comment]
您好，场景内的循环控制器，某次循环失败，是不会触发测试计划的失败重试机制的，循环不会重试。
