### ISSUE TITLE
[FEATURE]在接口自动化模块里面场景步骤这里，页面往下拉的时候，希望可以将最上面调试那一行固定住，编辑调试反复拖拉，用起来很繁琐

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3036]
**请描述您的需求或者改进建议.**
在接口自动化模块里面场景步骤这里，编辑页面往下拉的时候，希望可以将最上面调试那一行置顶，现在每次点调试，都要把页面再往上拉上去，这样来回的反复拖拉特别繁琐

<img width="1439" alt="WechatIMG107" src="https://user-images.githubusercontent.com/32027713/119105007-8024a500-ba4f-11eb-8758-434a76c9f5f0.png">

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化

**Comment by xulinde** [comment]
v10.5已优化
