### ISSUE TITLE
[BUG]接口自动化中，设置误报规则后，启用误报，断言成功，然后匹配上误报，但是显示error

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#30378]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

接口自动化中，设置误报规则后，启用误报，断言成功，然后匹配上误报，但是结果显示error

### 重现步骤

1. 设置响应400的误报规则
2. 环境配置中开启全局断言，启用误报
3. 调试接口，断言成功，然后匹配上误报，但是结果显示error

### 期待的正确结果

断言成功，然后匹配上误报，然后显示误报

### 相关日志输出

```shell
无
```

### 附加信息

<img width="766" alt="1713340142975" src="https://github.com/metersphere/metersphere/assets/50016789/ee3c444e-ed17-40d4-abf9-0ece7026dd87">
<img width="829" alt="1713340200642" src="https://github.com/metersphere/metersphere/assets/50016789/ef610536-71cc-428e-ba8f-0182e9d749a3">

**Comment by 13290445582** [comment]
你好，目前系统设计并无问题，请确认是否使用问题，感谢反馈。
