### ISSUE TITLE
[FEATURE]接口自动化断言失败后程序执行情况

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3037]
**请描述您的需求或者改进建议.**
能够在接口中选择断言失败后，程序是否需要继续，部分场景中前置接口失败了那么后置接口也没有执行的必要了

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
可以设置条件控制器

**Comment by xulinde** [comment]
可以设置条件控制器

**Comment by wszbc** [comment]
> 可以设置条件控制器

那这种操作太不方便了等于每个断言我都要去加入条件控制器去判断断言的成功与否要嵌套好多层，jmeter原版也是可以断言失败终止的，感觉这边如果能实现过来会更方便操作。

**Comment by zyyfit** [comment]
最新版可配置失败后是否继续，请升级使用
![图片](https://user-images.githubusercontent.com/73461316/123751254-1e771680-d8ea-11eb-85f9-a584407b468e.png)
