### ISSUE TITLE
环境变量删不掉[BUG]

### ISSUE THREAD

**Issue by cocohero123** [metersphere/metersphere#30374]
### 联系方式

363422893@qq.com

### MeterSphere 版本

v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

环境变量删不掉[BUG]，批量删除也好，单个删除也好，点击后没有反应。

### 重现步骤

环境变量删不掉[BUG]

**Comment by 13290445582** [comment]
您好，最新未复现该问题，建议升级至最新版本v2.10.14使用。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
