### ISSUE TITLE
[FEATURE]测试计划中， 用例关键信息都是灰色的 且 字体小， 看起来很费劲 

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3038]
**请描述您的需求或者改进建议.**
测试计划中， 用例关键信息都是灰色的 且 字体小， 看起来很费劲 ，关键的步骤信息才是用户关注的重点，其他信息可以适当固定缩小，希望“通过”等操作按钮可以在步骤的下方也可以加一下，不然用户看了一大堆信息，还得拖到最上面点击，累

**请描述你建议的实现方案**
<img width="1439" alt="WechatIMG108" src="https://user-images.githubusercontent.com/32027713/119109309-a4828080-ba53-11eb-90ae-75f04d065718.png">

**Comment by xulinde** [comment]
感谢反馈，后面版本可以在优化下的

**Comment by xulinde** [comment]
v1.10.2版本已优化
