### ISSUE TITLE
测试计划中 用例执行，状态更新太慢了， 需要等很久才更新好大概（3~5s）,如果用户有几百上千个用例需要操作咋整？

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3039]
**请描述您的需求或者改进建议.**
        每一个点击用例的状态之后，要转圈圈大概3~5秒的时间，但是用户有几百个甚至上千个，而且点击具体状态之后没有直接跳到下一个的按钮或者快捷操作，十分影响工作效率
<img width="1439" alt="WechatIMG109" src="https://user-images.githubusercontent.com/32027713/119112255-7ce0e780-ba56-11eb-83a6-b4b245cd91e7.png">

 **请描述你建议的实现方案**
        网络良好的情况下，响应时间应该控制在1秒之内，且可以直接切换下一个，操作需要考虑用户的数据量和便捷性，类似于下面这样：
![image (1)](https://user-images.githubusercontent.com/32027713/119115217-80c23900-ba59-11eb-92da-37de4db8bd88.png)

**Comment by xulinde** [comment]
部署机配置如何

**Comment by dashenyucainiao** [comment]
8C16G

**Comment by xulinde** [comment]
升级到最新版本该问题有优化吗
