### ISSUE TITLE
[接口测试]一个测试里面的多个场景操作优化建议

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#304]
![image](https://user-images.githubusercontent.com/13564069/91677825-83e96200-eb76-11ea-998e-5157760afba0.png)

1.每个场景的收起展开单独控制，点击那个场景收起展开就操作那个场景，目前的操作体验不好
2.支持跨场景的接口复制

**Comment by xulinde** [comment]
您好，新版本场景可以复制/引用子场景，您可以升级到最新版本体验下
