### ISSUE TITLE
[BUG]【性能测试】场景里引用场景，原场景里有引用csv，在性能测试页面，引用接口自动化场景，csv文件没带过来。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#30406]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

【性能测试】场景里引用场景，原场景里有引用csv，在性能测试页面，引用接口自动化场景，csv文件没带过来。

### 重现步骤

【性能测试】场景里引用场景，原场景里有引用csv，在性能测试页面，引用接口自动化场景，csv文件没带过来。
![image](https://github.com/metersphere/metersphere/assets/104960608/a7120e5b-566d-4031-8a6f-5f81d9dd0d33)
![image](https://github.com/metersphere/metersphere/assets/104960608/b3eecb26-2e05-49ee-a74e-60f289bf4d44)
![image](https://github.com/metersphere/metersphere/assets/104960608/069eb84e-ef82-44d7-a1a4-5e8e95ef52b0)

**Comment by 13290445582** [comment]
您好，目前的用法是，在场景设置处需勾选场景设置，再进行接口自动化场景转性能测试，将CSV文件带过去，若有其他问题，请继续反馈。
![image](https://github.com/metersphere/metersphere/assets/128017892/02d16255-7608-4456-8520-839a5ec657cc)

**Comment by 2lipan** [comment]
已按要求勾选使用，可以将csv文件正常带入。
