### ISSUE TITLE
[FEATURE]简化测试用例模板， 减少测试人员非必要输入

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3040]
**请描述您的需求或者改进建议.**
简化测试用例模板，现在要填写的内容太多了
1、 去掉ID	， 自定义ID，编辑模式这三列
2、 所属模块	用例类型	维护人  这三列 也去掉，可以根据前端传入导入时选中的模块， 默认功能用例， 维护人 用个人账号

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/32027713/119113138-5ec7b700-ba57-11eb-81b0-af3f35f53194.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化
