### ISSUE TITLE
[BUG] 【测试跟踪】测试计划关联接口和功能用例，执行测试计划后，报告列表的报告未更新功能用例的结果

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#30430]
### MeterSphere 版本

v2.10.13

### 使用外置数据库

否

### 问题描述

 测试计划关联了接口和功能用例，执行接口和功能用例后，报告列表中报告未更新功能用例的执行结果

### 重现步骤

1、创建一个测试计划
2、关联功能和接口用例
3、执行接口、功能用例
4、进入报告列表查看报告

### 期待的正确结果

手动执行功能用例后，报告列表中的报告同步更新功能用例结果

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/121e6395-b9d4-476c-b178-1e40e7ccaeb4)

![image](https://github.com/metersphere/metersphere/assets/45531073/5965c185-8a54-4792-8a5e-073d2aa91ee1)
![image](https://github.com/metersphere/metersphere/assets/45531073/bbb40712-41e9-4836-be51-701fed6a2a50)

![image](https://github.com/metersphere/metersphere/assets/45531073/f9e504d2-1324-4496-8874-39b350949fe2)

**Comment by 13290445582** [comment]
1.报告列表处的报告为一次性报告，后续修改状态，不会影响到报告列表处的报告状态，所以不会更新用例结果。
2.反馈的报告内无法查看用例问题在最新版本v2.10.14版本已修复，请升级。
