### ISSUE TITLE
[FEATURE]测试用例列表需要展示 责任人

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3043]
**请描述您的需求或者改进建议.**

测试用例列表需要展示 责任人

**请描述你建议的实现方案**
<img width="1439" alt="WechatIMG111" src="https://user-images.githubusercontent.com/32027713/119117869-41491c00-ba5c-11eb-95db-a8b287ef12a6.png">

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化这里

**Comment by xulinde** [comment]
v1.10.2版本已实现
