### ISSUE TITLE
【建议】项目设置的模版管理内，用例模版支持复制到其他项目，例如 缺陷模版

### ISSUE THREAD

**Issue by cui369680775** [metersphere/metersphere#30437]
### MeterSphere 版本

V2.10.13

### 联系方式

369680775@163.com

### 请描述您的需求或者改进建议

项目设置的模版管理内，用例模版支持复制到其他项目，目前缺陷模版支持复制到其他项目，用例模版不支持，这样对于自定义的用例模版不友好，新创建项目，还需要重新配置用例模版

**Comment by luty2018** [comment]
这个我们会规划到v3.0版本中。

**Comment by luty2018** [comment]
同时v3.0支持组织级的模板， 这样就不用挨个项目创建了。

**Comment by cui369680775** [comment]
> 同时v3.0支持组织级的模板， 这样就不用挨个项目创建了。

v3.0什么时候正式发布，或者可以2.0可以升级到3么

**Comment by luty2018** [comment]
> > 同时v3.0支持组织级的模板， 这样就不用挨个项目创建了。
> 
> v3.0什么时候正式发布，或者可以2.0可以升级到3么

Beta版本5月底，正式版本6月底。
