### ISSUE TITLE
[BUG] 场景步骤，切换引用环境会变更path路径的内容

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#30467]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

版本:   v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

场景步骤，切换引用环境会变更path路径的内容

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/23476281/7ef47c7a-1265-4e51-bc26-38e686d7facb)

### 期待的正确结果

不变更path的内容，只变更域名内容

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.16-lts版本修复这个问题。

**Comment by youliyuan-fit2cloud** [comment]
暂不支持，请手动修改一下吧，感谢理解和支持。
