### ISSUE TITLE
[需求] 不同的项目可以互相复制用例

### ISSUE THREAD

**Issue by cui369680775** [metersphere/metersphere#30482]
### MeterSphere 版本

V2.10.13

### 联系方式

369680775@163.com

### 请描述您的需求或者改进建议

目前新建项目还需要重新创建测试用例模版（自定义字段）和缺陷模版，然后导入用例，需求是可以直接复制用例模版和缺陷模版，然后可以从别的项目上直接复制用例到新项目。

**Comment by luty2018** [comment]
这个会在v3.0版本中讨论规划。可以关注后续的发布。
