### ISSUE TITLE
[BUG]性能测试同步定时器模拟用户组的数量设置为任意数，超时时间设置为0，执行测试会一直进行下去无法停止进行修改

### ISSUE THREAD

**Issue by xxxxxxdddddd** [metersphere/metersphere#3048]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.0
**Bug 描述**
简要描述您碰到的问题
创建性能测试，同步定时器模拟用户组的数量设置为任意数，超时时间设置为0
执行测试会一直进行下去无法停止进行修改

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这边没有复现呢，能描述一下具体操作步骤或者提供一下脚本吗
