### ISSUE TITLE
[BUG]【ui测试】单点登录页面未能成功跳转到目标页面

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30481]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

客户的目标网站使用统一cas认证系统，在ui测试中，访问目标网址，使用数据用户名，密码登录后，跳转到认证成功页面，没有进到目标网址中。

### 重现步骤

客户的目标网站使用统一的cas认证系统，在ui测试中，访问目标网址，使用数据用户名，密码登录后，跳转到认证成功页面，没有进到目标网址中

### 期待的正确结果

访问目标网址，使用数据用户名，密码登录后，跳转到目标网址中

### 附加信息

![登录场景](https://github.com/metersphere/metersphere/assets/145318182/f0067e15-927b-4fb1-99e5-bffc4f2607c4)
![单点登录页面](https://github.com/metersphere/metersphere/assets/145318182/9109a551-e8bf-4f79-be92-64baa134291b)
![目标网址](https://github.com/metersphere/metersphere/assets/145318182/8687e10d-f961-40a8-9dd1-977573507793)

**Comment by fit2cloud-lijiaxin** [comment]
登录步骤后，增加一步，打开目标网页并勾选追加页面，也未能打开目标网站页，仍是认证成功页。

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请您升级到最新版本再做操作
