### ISSUE TITLE
[BUG]建议在压测结束后，可以对压测配置进行修改

### ISSUE THREAD

**Issue by xxxxxxdddddd** [metersphere/metersphere#3049]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.3
**Bug 描述**
简要描述您碰到的问题
建议在压测结束后，可以对压测配置进行修改
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是可以修改的，压测执行后会自动跳转到测试报告页面，要修改测试需要再切回测试部分
