### ISSUE TITLE
[BUG]性能脚本get请求断言判断有误

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#305]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？----1.2.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  性能测试-脚本中get请求未设置断言
实际运行结果：显示断言失败错误

**期待的正确结果**
正确情况下应该是什么样的？--无断言错误判断
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33714230/91688211-164c2e80-eb94-11ea-9f09-9e48dcac7da2.png)

**Comment by liuruibin** [comment]
我在自己测试过程中也出现了断言错误，用原始的jtl文件使用 jmeter -g 命令生成默认的报表，也有断言错误。目前不知道如何处理
