### ISSUE TITLE
[BUG]  接口自动化场景 引用 case，如果修改 case 的前置和后置脚本，场景层不会自动更新，需手动删除case重新引用

### ISSUE THREAD

**Issue by ronkyzhong** [metersphere/metersphere#3050]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9.2
**Bug 描述**
简要描述您碰到的问题
接口自动化场景 引用 case，如果修改 case 的前置和后置脚本，场景层不会自动更新，需手动删除case重新引用
**Bug 重现步骤**
1.  接口定义接口A，转为 case A1且后置脚本thread.sleep(1000)
2. 接口自动化场景C 引用case A2，此时修改case A1 的后置脚本thread.sleep(20000)，此时场景C 的 case A1 执行的后置脚本还是thread.sleep(1000) 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
接口自动化场景C 引用case A2，此时修改case A1 的后置脚本thread.sleep(20000)，此时场景C 的 case A1 执行的后置脚本应该是thread.sleep(2000) 

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题呢，修改case后有没有刷新场景或者刷新页面呢？
