### ISSUE TITLE
[BUG]接口自动化批量执行生成报告时，只执行当前页所有场景用例。其他页场景用例并没有执行

### ISSUE THREAD

**Issue by ronkyzhong** [metersphere/metersphere#3051]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.9.2
**Bug 描述**
简要描述您碰到的问题
接口自动化批量执行生成报告时，只执行当前页所有场景用例。其他页场景用例并没有执行
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
接口自动化批量执行生成报告时，执行所有场景用例
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能描述一下具体操作步骤吗
