### ISSUE TITLE
[FEATURE]脑图编辑建议参考wps增加自动保存的功能，或者切换其他tab的时候给出是否保存的提示

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#3052]
**请描述您的需求或者改进建议.**
用户编辑脑图，写了好多，切回用例列表，再切回去的时候，之前 编辑的脑图信息 都没了，还得重新写

**请描述你建议的实现方案**
脑图编辑建议参考wps增加自动保存的功能，或者切换其他tab的时候给出是否保存的提示！

**Comment by xulinde** [comment]
感谢反馈，可以优化

**Comment by xulinde** [comment]
v1.13已支持自动保存功能
