### ISSUE TITLE
[BUG] 场景接口覆盖率统计有误

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30530]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

 场景接口覆盖率统计有误

### 重现步骤

1.在A项目新建场景，关联的都是A项目的用例
![image](https://github.com/metersphere/metersphere/assets/103925124/5b58c422-2b2e-4698-9ef9-34061f04a040)
2、在B项目新建场景，复制A项目的场景
![image](https://github.com/metersphere/metersphere/assets/103925124/bb1c7000-3d5c-4bad-ac9f-8a9740de59bb)
3、在复制过来的场景添加当前B项目的用例

此时，查看B项目的覆盖率，发现新添加的用例接口未覆盖
在这里点击进入，检索接口，仍存在
![image](https://github.com/metersphere/metersphere/assets/103925124/9cce1931-733f-41ca-b10a-0ca71b697c7c)

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，已复现，后续版本修复

**Comment by 13290445582** [comment]
您好，V2的数据结构，针对复制场景的各种内部修改不会进行额外记录，V2如果针对这个地方做改动，可能会出现创建/修改场景速度卡慢的问题。所以V2不会再改这里，这个问题我们规划到v3版本解决。
