### ISSUE TITLE
[BUG]  场景打开后卡死，操作不了，显示异常

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30531]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

场景打开后卡死，操作不了，显示异常

### 重现步骤

场景打开后卡死，操作不了，显示异常。F12接口均200
![image](https://github.com/metersphere/metersphere/assets/103925124/b1698e8f-e20c-4183-af2b-40dbd4b04df0)
![image](https://github.com/metersphere/metersphere/assets/103925124/c68e3500-2779-47f4-915b-be61b286434a)
复制场景仍有此问题，导出场景再导入无此问题

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请您升级到最新版本操作

**Comment by youliyuan-fit2cloud** [comment]
这个问题是只有这个场景会出现卡死还是其他场景也会遇到？
如果只有这个场景，建议把场景发我们看看。
如果是不止这个场景，检查下当前系统内存使用情况，服务是否正常？

**Comment by fit2cloud-yaochunrong** [comment]
![38385af9-7d2d-4767-8f24-fcdbec8063fc](https://github.com/metersphere/metersphere/assets/103925124/6ac5545d-a8c0-46af-9239-d9c73e61f93e)
![92b13038-efe6-41e2-bd71-7278554bcdff](https://github.com/metersphere/metersphere/assets/103925124/5dc8ce25-8905-4e7f-957c-8cdef9329028)
2.10.15-lts再次出现
正常的场景步骤应该显示为：
![企业微信截图_17180751361137](https://github.com/metersphere/metersphere/assets/103925124/118fca1a-4489-4014-83fa-4385e1c1ae62)
补充：将原场景重新 导出导入后，    把所有 case  都注释掉，  再设置运行环境保存 后， 再把case 放开， 这个场景就可以正常编辑和修改了。导入后， 直接设置运行环境  就不能修改  界面没反应了。

**Comment by vilian00** [comment]
同样遇到这个问题。

操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。
原因：
       导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。
![image](https://github.com/metersphere/metersphere/assets/42952901/026f8f0a-5f41-484e-9f2e-ffabcfd3de59)

**Comment by fangjianchao** [comment]
> 同样遇到这个问题。
> 
> 操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。 原因： 导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。 ![image](https://private-user-images.githubusercontent.com/42952901/340162761-026f8f0a-5f41-484e-9f2e-ffabcfd3de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM0MzMsIm5iZiI6MTcxODg1MzEzMywicGF0aCI6Ii80Mjk1MjkwMS8zNDAxNjI3NjEtMDI2ZjhmMGEtNWY0MS00ODRlLTlmMmUtZmZhYmNmZDNkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmU3MzJhODVmNTY4N2Q0ZmYxZDc0MzUyNjRiYTYzNzZiY2I1OTYxYTBlYzExNjUxZjY2MjcyZDE3N2QwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yesV4TlmrtL92nhk92NlLb7zVE-FkxSzFdkSK7oSCes)

大家有没有遇到编辑器展开折叠卡死的问题

**Comment by luty2018** [comment]
> > 同样遇到这个问题。
> > 操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。 原因： 导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。 ![image](https://private-user-images.githubusercontent.com/42952901/340162761-026f8f0a-5f41-484e-9f2e-ffabcfd3de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM0MzMsIm5iZiI6MTcxODg1MzEzMywicGF0aCI6Ii80Mjk1MjkwMS8zNDAxNjI3NjEtMDI2ZjhmMGEtNWY0MS00ODRlLTlmMmUtZmZhYmNmZDNkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmU3MzJhODVmNTY4N2Q0ZmYxZDc0MzUyNjRiYTYzNzZiY2I1OTYxYTBlYzExNjUxZjY2MjcyZDE3N2QwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yesV4TlmrtL92nhk92NlLb7zVE-FkxSzFdkSK7oSCes)
> 
> 大家有没有遇到编辑器展开折叠卡死的问题

建议您使用v3.0，我们对编辑器使用了新的组件

**Comment by luty2018** [comment]
> 同样遇到这个问题。
> 
> 操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。 原因： 导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。 ![image](https://private-user-images.githubusercontent.com/42952901/340162761-026f8f0a-5f41-484e-9f2e-ffabcfd3de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTA0OTgsIm5iZiI6MTcxOTkxMDE5OCwicGF0aCI6Ii80Mjk1MjkwMS8zNDAxNjI3NjEtMDI2ZjhmMGEtNWY0MS00ODRlLTlmMmUtZmZhYmNmZDNkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA4NDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWU3NTMwNjQxNDkzMjhlNGYzNjdhMjYzNzQxYjM1ZDAzMTRlYTIxMzBmY2MyODM5Nzk4MDM0ZGY0MjYxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6a_hw2qNlFHIwQTuld_fj3qeActZfk4WuX-ErUZZT_8)

请问你使用的版本号是多少？

**Comment by fangjianchao** [comment]
> > > 同样遇到这个问题。
> > > 操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。 原因： 导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。 ![image](https://private-user-images.githubusercontent.com/42952901/340162761-026f8f0a-5f41-484e-9f2e-ffabcfd3de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM0MzMsIm5iZiI6MTcxODg1MzEzMywicGF0aCI6Ii80Mjk1MjkwMS8zNDAxNjI3NjEtMDI2ZjhmMGEtNWY0MS00ODRlLTlmMmUtZmZhYmNmZDNkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YmU3MzJhODVmNTY4N2Q0ZmYxZDc0MzUyNjRiYTYzNzZiY2I1OTYxYTBlYzExNjUxZjY2MjcyZDE3N2QwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yesV4TlmrtL92nhk92NlLb7zVE-FkxSzFdkSK7oSCes)
> > 
> > 
> > 大家有没有遇到编辑器展开折叠卡死的问题
> 
> 建议您使用v3.0，我们对编辑器使用了新的组件

v.2.10.x 这个性能bug我自己修复了

**Comment by vilian00** [comment]
> > 同样遇到这个问题。
> > 操作：在已经有了一些步骤的场景用例里面导入另一个场景，概率性出现。 原因： 导入步骤的resourceId和脚本原有的resourceId重复，在数据库中api_scenario.scenario_definition复制出json，并修改掉重复的resourId，保存后场景可正常打开。 ![image](https://private-user-images.githubusercontent.com/42952901/340162761-026f8f0a-5f41-484e-9f2e-ffabcfd3de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTA0OTgsIm5iZiI6MTcxOTkxMDE5OCwicGF0aCI6Ii80Mjk1MjkwMS8zNDAxNjI3NjEtMDI2ZjhmMGEtNWY0MS00ODRlLTlmMmUtZmZhYmNmZDNkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA4NDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWU3NTMwNjQxNDkzMjhlNGYzNjdhMjYzNzQxYjM1ZDAzMTRlYTIxMzBmY2MyODM5Nzk4MDM0ZGY0MjYxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6a_hw2qNlFHIwQTuld_fj3qeActZfk4WuX-ErUZZT_8)
> 
> 请问你使用的版本号是多少？

版本:   v2.10.14-lts-a7298117

**Comment by youliyuan-fit2cloud** [comment]
该问题最新版本无法复现，请大家升级到最新版本尝试一下，如果再次出现请重新提issue，感谢理解和支持。
