### ISSUE TITLE
[FEATURE]  多选 api 想要导出成html 文档提供给讲部分提供给别人，目前翻页多选然后切换到文档，展示的不是选中的接口，导致无法按需导出接口文档，希望能补齐勾选接口导出的能力

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#30566]
### MeterSphere 版本

2.10.13

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/43202800/be5fd7a1-85a1-4fe3-9399-a3f5d2ea71b3)

背景：多选 api 想要导出成html 文档提供给讲部分提供给别人，

问题：目前翻页多选然后切换到文档，展示的不是选中的接口，导致无法按需导出接口文档，希望能补齐勾选接口导出的能力

### 请描述你建议的实现方案

 翻页多选api后，切换到文档展示为选择的api ，然后批量导出api文档

**Comment by luty2018** [comment]
好的， 已加入规划。
