### ISSUE TITLE
[BUG]功能用例回收站彻底删除用例，选择了全选所有页彻底删除所有用例，删除提示不对

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#30567]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

功能用例回收站彻底删除用例，选择了全选所有页彻底删除所有用例，删除提示不对

### 重现步骤

1. 删除所有用例至回收站
2. 到回收站，选择了全选所有页彻底删除所有用例
3. 删除提示的数量不正确

### 期待的正确结果

删除提示的数量正确

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/df600d99-23eb-49ad-ad93-4b3fb3fad482)

**Comment by LukaDoncic-Magic** [comment]
未复现该问题，请升级到v2.10.14-lts版本后操作

**Comment by LukaDoncic-Magic** [comment]
感谢反馈，已复现，后续版本修复

**Comment by zrfit** [comment]
v2.10.20已修复该问题，建议升级验证。
