### ISSUE TITLE
[FEATURE]cloud版本功能用例-用例名称字符长度希望不要做限制

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#30564]
### MeterSphere 版本

cloud

### 联系方式

张树彬

### 请描述您的需求或者改进建议

cloud下单客户反馈，cloud版本功能用例-用例名称字符长度有限制，导致导入用列失败，客户觉得是个bug，希望不要做长度限制，或者限制为1000个字符。该需求客户反馈优先级高，麻烦尽快反馈一下，谢谢。

### 附加信息

<img width="471" alt="10456a162647675d386cbfd1930ca6e" src="https://github.com/metersphere/metersphere/assets/77324661/6a8418fd-fc68-4068-a932-b7559ab11267">

**Comment by luty2018** [comment]
用例名称目前是255字符， 这样都不够吗？
