### ISSUE TITLE
[FEATURE]测试计划的执行报告中,对失败用例可以进行备注

### ISSUE THREAD

**Issue by chenjinmingd** [metersphere/metersphere#30578]
### MeterSphere 版本

v1.20.x-lts 

### 请描述您的需求或者改进建议

![WechatIMG28](https://github.com/metersphere/metersphere/assets/167962398/2247ba1c-90fb-49fa-a2bd-d91133d53c39)

### 请描述你建议的实现方案

测试计划的执行报告中,对失败用例可以进行备注

**Comment by luty2018** [comment]
请问这里的使用场景是什么样的，是否可以在测试总结里面进行统一描述?

**Comment by luty2018** [comment]
建议您升级到v3.0使用，报告中可以单独加富文本，对失败用例进行统一描述。
