### ISSUE TITLE
[BUG]  当接口返回是空的数组的时候，进行断言，断言没有加“\”，导致断言失败。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#30572]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

当接口返回是空的数组的时候，进行断言，断言没有加“\”，导致断言失败。

### 重现步骤

https://github.com/metersphere/metersphere/assets/33945037/e32f1c99-4251-4e53-bec6-9a3eec0a2e82

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.15-lts版本修复这个问题

**Comment by LukaDoncic-Magic** [comment]
您好，感谢您的反馈，使用正则匹配需要加转译，请您加上转译操作一下。
