### ISSUE TITLE
[BUG] 性能测试脚本中事务控制器勾选了generate parent sample，测试报告-测试详情没有数据

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#30575]
### MeterSphere 版本

2.10.13-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/43202800/8eb9cf21-fd26-4190-a0b8-67b8edbad8f8)
性能测试脚本中事务控制器勾选了generate parent sample，测试报告-测试详情没有数据

### 重现步骤

性能测试脚本中事务控制器勾选了generate parent sample，测试报告-测试详情没有数据

### 期待的正确结果

展示数据

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请升级到v2.10.14-lts再做操作。
