### ISSUE TITLE
[BUG]   接口场景模块展示问题。1.  修改时无法直接定位到当前模块，需要一层一层打开 。 2 . 当有多层级目录是，无法展示完整

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#30574]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

接口场景模块展示问题。
1.  修改时无法直接定位到当前模块，需要一层一层打开 。 
2. 当有多层级目录是，无法展示完整

### 重现步骤

1. 创建接口场景目录多个层级，选择目录展示补全
<img width="822" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/beb36280-553d-4b30-89ba-cd5aa7436887">
2. 当前选择的模块，再次打开无法定位当前的模块，需要一层一层打开。
<img width="622" alt="image" src="https://github.com/metersphere/metersphere/assets/33945037/8e102312-79c6-4260-b275-e7bfb68b1549">

https://github.com/metersphere/metersphere/assets/33945037/18dc6683-d7a8-436e-999c-6970a9dfd821

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.15-lts版本修复这个问题。

**Comment by Hyyfit** [comment]
v3 已覆盖该功能

**Comment by 13290445582** [comment]
您好，V2.10.17版本已优化，实际使用上十几层没有问题，目前优化至此，暂且不做左右滚动条，感谢理解。
