### ISSUE TITLE
[FEATURE]性能测试执行结果页，希望在测试报告页只显示事务的结果，非事务结果不显示

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#3057]
**两种情况，
1. 脚本里只有请求，没有事务，希望在报告页不显示结果；
2. 脚本里即包含事务，又包含事务外请求，希望在报告页只显示事务结果，不显示请求结果
**

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by wangzhen-fit2cloud** [comment]
在 1.11 版本性能测试报告增加了测试详情tab页,可以自己选择展示那些信息
