### ISSUE TITLE
[FEATURE]在测试计划执行功能用列，建议也能编辑用例，并且同步更新用例

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#30573]
### MeterSphere 版本

版本:   v2.10.7-lts-7f7afdc5

### 联系方式

MeterSphere 微信 31群

### 请描述您的需求或者改进建议

在测试计划执行功能用列，建议也能编辑用例，并且同步更新用例

**Comment by luty2018** [comment]
这个功能在v3.0已经支持了哈， 可以关注一下发布时间
