### ISSUE TITLE
[BUG]接口post请求参数是json格式的，请求后发现请求记录会自动带上空格，导致请求失败

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#30589]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

接口post请求参数是json格式的，请求后发现请求记录会自动带上空格，导致请求失败

### 重现步骤

1. 创建接口，post 请求，添加json 请求参数不带空格
2. 调试接口，查看请求内容发现会自动带上空格，导致请求失败

### 期待的正确结果

不要自动带上空格，请求成功

### 相关日志输出

```shell
无
```

### 附加信息

<img width="900" alt="企业微信截图_17139491992384" src="https://github.com/metersphere/metersphere/assets/50016789/9e1e9a67-25b5-4b46-89a9-bf9a6263b5ce">
<img width="598" alt="企业微信截图_17139492406621" src="https://github.com/metersphere/metersphere/assets/50016789/05234115-800d-47dc-ad1d-130b80e10593">

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请您升级到最新版本再做操作

**Comment by spritelyl** [comment]
最新版也有空格：
<img width="742" alt="企业微信截图_17142968808376" src="https://github.com/metersphere/metersphere/assets/50016789/b31d898d-07e3-49a2-805a-8bc30d589e85">

**Comment by Hyyfit** [comment]
实际发出的请求是没有带上空格的，ms平台上只是做了格式化的展示，不改变请求实际发送的内容；
