### ISSUE TITLE
[BUG][接口自动化][变更记录]场景下接口较多时 变更记录无法加载

### ISSUE THREAD

**Issue by zhanghao1225** [metersphere/metersphere#30586]
### 联系方式

17683985095

### MeterSphere 版本

 v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

[接口自动化][变更记录]场景下接口较多时 变更记录无法加载

### 重现步骤

1.打开接口自动化模块，
2.选择一个有600个接口的场景，点击变更记录

### 期待的正确结果

2.正常显示

### 附加信息

![微信图片_20240424160003](https://github.com/metersphere/metersphere/assets/24429206/72171202-e9d8-4fd9-ac69-84ebb43d78c1)
![微信图片_20240424155957](https://github.com/metersphere/metersphere/assets/24429206/0a28523e-837a-4f63-bfb6-a021b61c877e)
![微信图片_20240424155948](https://github.com/metersphere/metersphere/assets/24429206/fda5e900-7504-4aea-9a7f-1c533da3757f)

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现，请您升级到最新版本后再做操作

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/8296e6cc-aa9d-4135-8e29-125302d4be2a)

你好，参考上图，修改安装目录yaml文件的内存上限大一些，重启服务。再尝试是否还会出现这个问题。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
