### ISSUE TITLE
[BUG]  超级管理员角色执行功能用例，没有更新执行人、

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#30599]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

超级管理员角色执行功能用例，没有更新执行人、

![image](https://github.com/metersphere/metersphere/assets/33945037/a477a036-669c-4624-8129-72b973e2cc23)
![image](https://github.com/metersphere/metersphere/assets/33945037/ca84b9ce-e06b-4ce8-b806-a8437143ccd3)

### 重现步骤

1. 创建用户授权超级管理员
2. 创建测试计划添加功能用例并执行，会看到没有执行人

**Comment by Zhuzhiming123zhu** [comment]
您好，在最新版本没有复现,请您升级到最新版本后再做操作

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，v2.10.21版本已修复，请升级。
