### ISSUE TITLE
[BUG] 循环控制器 foreach 上一个接口提取的数组，在控制器里面的接口 不是循环运行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#30591]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

1、接口提取数组 
2、循环控制器 foreach 上一个接口提取的数组，在控制器里面的接口 不循环运行

3、如果打印 数组，关闭接口那个请求可以循环起来，开启了就不能循环了
 数据是qa环境造的

![启用接口](https://github.com/metersphere/metersphere/assets/43202800/2489e16e-6e16-4730-9ff6-ebb664b6099c)

### 重现步骤

1、接口提取数组 
2、循环控制器 foreach 上一个接口提取的数组，在控制器里面的接口 不循环运行

3、如果打印 数组，关闭接口那个请求可以循环起来，开启了就不能循环了
 数据是qa环境造的

### 期待的正确结果

接口应该可以循环

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/06082a31-492b-4084-8e6c-a560609723af)

你好，非问题，禁用的步骤里面有提取参数同名id导致的。
