### ISSUE TITLE
[BUG]接口api导出成swagger格式时候，json-schema中填写的必填和字段描述不能被导出来

### ISSUE THREAD

**Issue by yxz312** [metersphere/metersphere#3059]
**MeterSphere 版本**
v1.9.3-a124268c

**Bug 描述**
接口api导出成swagger格式时候，json-schema中填写的必填和字段描述不能被导出来

**Bug 重现步骤**
1.  新建一个接口，请求体点击json，打开json-schema，填写字段如下：
![image](https://user-images.githubusercontent.com/49225469/119246476-86806180-bbb4-11eb-9a31-b22f728aa25a.png)

2.  保存接口
3.  选中这个接口，点击导出成swagger格式
4. 导出的json文件中没有字段是否必填和描述信息
![image](https://user-images.githubusercontent.com/49225469/119246502-b2034c00-bbb4-11eb-8db3-9964399c58c1.png)

**期待的正确结果**
期望导出的swagger文件中有请求体字段是否必填和描述的信息

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复

**Comment by zyyfit** [comment]
1.13.0已修复
