### ISSUE TITLE
[BUG] 性能测试上传1个 jmx  1个 csv脚本，列表绑定展示了两个csv文件

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#30603]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

![24c89df85c959102564b16185f73e39](https://github.com/metersphere/metersphere/assets/43202800/ce9e660e-1e2b-4a09-a993-6d63285606c3)
性能测试上传1个 jmx  1个 csv脚本，列表绑定展示了两个csv文件，高级设置处也有两个

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/43202800/d8aff905-0e60-4c88-90ef-a32b9764bb39)

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.15-lts版本修复这个问题。

**Comment by liuruibin** [comment]
场景列表里的csv是解析jmx出现的，需要用户自行上传。

当然如果这个csv在jmx中出现了但不去使用也是可以正常执行性能测试的，此时就不需要手动上传csv。

我们无法预知jmx对csv实际使用情况，列出所有的csv是保底策略。

无需解决
