### ISSUE TITLE
[BUG]删除自动化场景报错

### ISSUE THREAD

**Issue by Xingac1999** [metersphere/metersphere#30614]
### 联系方式

2280930812@qq.com

### MeterSphere 版本

v2.10.11-lts

### 使用外置数据库

否

### 问题描述

在将备份数据还原后，创建新场景后删除报错
![metersphere](https://github.com/metersphere/metersphere/assets/45863249/6da66039-1fd7-4e8f-b825-41287d59154b)
查看ms-server日志，删除的时候没有对应报错日志产生

### 重现步骤

1. 接口自动化中创建场景
2. 删除该场景

### 期待的正确结果

期望知道在哪个服务中可以看到具体报错日志与原因

**Comment by fit2-zhao** [comment]
看一下 api-test 这个服务的日志，默认位置：/opt/metersphere/logs/api-test/ 。

**Comment by Xingac1999** [comment]
抱歉之前的信息有误，使用的是v2.1.1版本，里面没有api-test服务
![e3b7f8e06c2f014779d51cae42210d8](https://github.com/metersphere/metersphere/assets/45863249/f8f2f44f-9874-446b-b25a-dffc956f2843)
服务状态如图
![b539793e403e388af8d906b0f7228b4](https://github.com/metersphere/metersphere/assets/45863249/da811b61-e8c2-42a3-91e6-fa971149a5c2)

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现,请您升级到最新版本再做操作
