### ISSUE TITLE
[BUG] Administrator进入系统管理-成员，报权限错

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#30613]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

Administrator进入系统管理-成员，报权限错

### 重现步骤

1. Administrator进入系统管理
2. 点击系统设置-工作空间-成员
3. 越权报错

### 期待的正确结果

不会越权报错

### 相关日志输出

```shell
无
```

### 附加信息

<img width="402" alt="27436063cada7bc9e7aab6d9568aa52" src="https://github.com/metersphere/metersphere/assets/50016789/6092c526-14c8-4cf5-b57b-eddbbb8dff73">

**Comment by youliyuan-fit2cloud** [comment]
已修复
