### ISSUE TITLE
[BUG] 上传了mango-dbjar包，开启接口测试，使用groovy脚本引用提示找不到jar包 

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#30625]
### MeterSphere 版本

2.10.12

### 使用外置数据库

否

### 问题描述

上传了mango-dbjar包，开启接口测试，使用groovy脚本引用提示找不到jar包 

![image](https://github.com/metersphere/metersphere/assets/43202800/71f718d7-abae-4285-a2c8-f3912e11015c)

![image](https://github.com/metersphere/metersphere/assets/43202800/a2eb65e7-2e20-4c1d-a2e8-12e3eeae4c57)

### 重现步骤

上传了mango-dbjar包，开启接口测试，使用groovy脚本引用提示找不到jar包

**Comment by xhy12** [comment]
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import org.bson.BsonDocument;
import org.bson.BsonString;
import org.bson.Document;

**Comment by LukaDoncic-Magic** [comment]
您好，在最新版本没有复现这个问题，您上传了jar包后需要手动重启一下所使用的资源池
