### ISSUE TITLE
[BUG]node-controller模式下，配置完node节点定时同步jar包后，node节点jar包实际无同步

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#30621]
### 联系方式

13716054767

### MeterSphere 版本

 v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

配置node-controller模式，勾选定时同步jar包，但是节点node下同步的目录为空
/data/metersphere/metersphere/data/api-folder/jar/node/847f9a75-a4ae-47c8-8a41-f046ffef196d 麻烦问下，我资源池选择定时同步jar包了，但是发现node节点下的目录只有更新文件夹了，没有把jar包同步过去

### 重现步骤

1. 主服务建立测试资源池
2. 资源池配置好node和定时同步jar包
3. 运行程序报错
4. 发现node节点下的/data/metersphere/metersphere/data/api-folder/jar/node/847f9a75-a4ae-47c8-8a41-f046ffef196d 目录为空，jar包未同步

### 期待的正确结果

node节点正确同步获取主服务的jar包

**Comment by fit2-zhao** [comment]
目前并未做热加载，插件包上传后需要重启 api-test 和 node-controller 服务。

**Comment by lol666666** [comment]
重启后也未同步到node的目录下

**Comment by lol666666** [comment]
重启后当时node节点目录下会存在同步的jar包，但是执行node的资源池时会被程序删除

**Comment by fit2-zhao** [comment]
`/data/metersphere/metersphere/data/api-folder/jar/node/ ` 这个目录下存放是文件管理中上传的函数包，当有jar变更时每次执行都会同步最新包，您把错误信息发出来看看。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
