### ISSUE TITLE
自定义代码片段只能复制使用,缺少能引用使用的

### ISSUE THREAD

**Issue by chenjinmingd** [metersphere/metersphere#30637]
### MeterSphere 版本

v1.20.x-lts 

### 请描述您的需求或者改进建议

自定义代码片段只能复制使用,缺少能引用使用的,要使用外部的方法只能 通过jar 实现

### 请描述你建议的实现方案

可以引用自定义外部脚本,如python ,自身的beanshell

### 附加信息

无

**Comment by luty2018** [comment]
这个已经在v3.0支持了哈， 可以关注后续版本发布。
