### ISSUE TITLE
[BUG]本地化语言支持不友好

### ISSUE THREAD

**Issue by BlessBei** [metersphere/metersphere#3063]
**MeterSphere 版本**
版本: v1.9.3-a124268c

**Bug 描述**
本地化非常不友好；需要英文版本，出来的报告相关指标全部是中文

**Bug 重现步骤**
打开MS  查看报告

**期待的正确结果**
对应英文版本展示英文的title

**截图**
![1621819071](https://user-images.githubusercontent.com/45033719/119285597-f5bd8a80-bc74-11eb-9012-edd31cd63d4a.png)
![1621905216](https://user-images.githubusercontent.com/45033719/119425380-d2104800-bd39-11eb-87d9-cb7752031367.png)
![1621905216](https://user-images.githubusercontent.com/45033719/119425396-d9375600-bd39-11eb-8376-5661496aa021.png)

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复

**Comment by zyyfit** [comment]
最新版已修复
