### ISSUE TITLE
[BUG]【测试计划】功能用例关联接口用例，在测试计划里关联该功能用例后，将功能用例里增加或减少关联的接口用例，该测试计划里并没有随之更新。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#30632]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

【测试计划】功能用例关联接口用例，在测试计划里关联该功能用例后，将功能用例里增加或减少关联的接口用例，该测试计划里并没有随之更新。

### 重现步骤

【测试计划】功能用例关联接口用例，在测试计划里关联该功能用例后，将功能用例里增加或减少关联的接口用例，该测试计划里的接口用例并没有相应增加或减少。
![image](https://github.com/metersphere/metersphere/assets/104960608/4e6f1aef-c478-4559-86f3-985e49faf891)
![image](https://github.com/metersphere/metersphere/assets/104960608/1692f14d-10a7-4f69-8eef-29c8b25d8f4f)

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划-功能用例tab页-功能用例详情页查看关联的接口用例数没有更新的情况没有复现。
ps：在测试计划-接口测试用例tab页，接口用例不会随之功能用例的新增/取消 关联而更新这个列表。
