### ISSUE TITLE
[BUG]【接口测试】文档结构断言，导入1.00 不能正常显示小数点

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30644]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

接口测试断言处，使用文档结构断言，导入json，包含期望值为1.00，导入后没有正常显示小数点

### 重现步骤

接口测试断言处，使用文档结构断言，导入json，包含期望值为1.00，导入后没有正常显示小数点

### 期待的正确结果

可以正常显示小数点

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/b7861176-bd8d-4f11-8503-b178891e8c23)
![image](https://github.com/metersphere/metersphere/assets/145318182/2e1476ed-c85d-4342-81cb-ce4370f22ed2)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #30642
