### ISSUE TITLE
[BUG]接口用例，断言，文档结构校验，导入number类型带小数的值，平台会把小数抹掉，比如1.00导入后变成1，导致校验不通过

### ISSUE THREAD

**Issue by shenxingqi** [metersphere/metersphere#30642]
### 联系方式

867296882@qq.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

[BUG]接口用例，断言，文档结构校验，导入number类型带小数的值，平台会把小数抹掉，比如1.00导入后变成1，导致校验不通过

### 重现步骤

导入前netWeight值为1.000,导入后变成1

![6391714348219_ pic](https://github.com/metersphere/metersphere/assets/32626470/f90a3259-a407-4d5f-b4fe-f59a6f52405f)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续版本修复该问题。

**Comment by luty2018** [comment]
建议升级到v2.10.16，我在最新版本中没有复现这个问题。
