### ISSUE TITLE
[BUG]查看testcase，移动鼠标hover查看testcase的详细信息，没有详细信息展示

### ISSUE THREAD

**Issue by BlessBei** [metersphere/metersphere#3064]
**MeterSphere 版本**
版本: v1.9.3-a124268c

**Bug 描述**
查看testcase，没有mouse hover的tips，以前版本hover上去可以查看case的详细描述

**Bug 重现步骤**
1.  打开测试计划
2.  mouse hover查看详细信息
 

**期待的正确结果**
显示详细信息

**截图**

![1621821700](https://user-images.githubusercontent.com/45033719/119286502-0e2ea480-bc77-11eb-8f84-cab983a99bab.png)

**Comment by zyyfit** [comment]
您好，现在这个地方的设计改掉了，不会显示详情了，需要打开详情页查看

**Comment by BlessBei** [comment]
这点进去查看过后，case状态就会变成进行中了呀。。。只是想查看一下case而已

**Comment by zyyfit** [comment]
> 这点进去查看过后，case状态就会变成进行中了呀。。。只是想查看一下case而已

目前最新版点开后不点下一条直接关闭是不会变成进行中的
