### ISSUE TITLE
[FEATURE]improvements，Please  confirm.

### ISSUE THREAD

**Issue by BlessBei** [metersphere/metersphere#3065]
**请描述您的需求或者改进建议.**
1.到处case的时候只能到处所有的case--》希望支持到处部分case的功能：根据文件模块的选择到处部分case
2.到处case的数量有限制--》希望能够扩大导入case数据量
3.在关联case到执行任务的时候，关联的case数量过大时，无法正常关联，需要每个文件去逐个关联
4.增加批量用例一键统一更改所属模块的方法，现在需要从根目录开始调整非常不方便
5.增加不同计划一键导出用例集合到其他计划中的方法
6.测试报告中除了各模块的通过率结果外，在前面最好加上总表通过率表
7.测试报告中 失败列表中既然没有ID列表，可以加上缺陷记录，保证每个失败或者堵塞案例都有迹可循，方便测试员添加忘记记录/缺失的缺陷
8. 接口测试、功能测试UI 希望能够优化一下，出现很多本地化翻译不对，字符溢出button框的现象

**Comment by xulinde** [comment]
1.目前是支持导出部分case，操作如图；
![Uploading image.png…]()

2.目前是限制了导入case文件大小是20M，后面可以修改下限制范围；
3.您case数量一共多少，我这边测试1500+没有该问题；
4.这个场景您可以选择批量移动；
5.目前不支持，但是支持，一个测试计划关联不同项目的用例，是否满足您需求；
6.测试计划列表是有“通过率”这个字段的

**Comment by xulinde** [comment]
7.测试报告是有缺陷列表的
![image](https://user-images.githubusercontent.com/64065190/119332835-b9f9e380-bcbb-11eb-9cbf-2b6fca9c8102.png)
8.能简单说明几点嘛

**Comment by BlessBei** [comment]
issue： # 3064  这个你们看看吧 。。hover挺好用的
8.  已经有issue单  #3063

**Comment by zyyfit** [comment]
> 如下，谢谢：
> 1.我看不到您给的截图
> 2. 导入case可以考虑500M吗？ 我们最大40000条
> issue： # 3064 这个你们看看吧 。。hover挺好用的
> 8. 已经有issue单 #3063

1、导出部分case：勾选要导出的case后再导出即可
2、这个功能我们会考虑优化一下
3、3064这个问题目前是这样设计的
4、3063这个问题将在后续版本修复
