### ISSUE TITLE
[BUG] ms- beanshell调用三方jar包删除Redis数据失败，jmeter可成功

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30656]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

ms- beanshell调用三方jar包删除Redis数据失败，jmeter可成功

### 重现步骤

已封装好的三方jar包，jmeter调用可成功（jar包私聊可发）
metersphere调用控制台报错

### 期待的正确结果

已封装好的三方jar包，jmeter调用可成功
![image](https://github.com/metersphere/metersphere/assets/103925124/860ab52e-fb04-4941-b97a-057a1a74eb46)
metersphere调用控制台报错
![image](https://github.com/metersphere/metersphere/assets/103925124/cd513ea1-a4a5-4550-bc6a-b48430ec0f9e)

============================================================================

import redis.clients.jedis.Jedis;
import test.metersphere.tools.Tools;
String redisString="10.1.13.68:6379";
String dbindex="1";
String password = "Password123@redis";
String key ="checkIdface:key1_value1;";
log.info("put结果："+Tools.PutRedisValues(redisString,dbindex,password,key));
Map a = Tools.GetRedisValues(redisString, dbindex, password, "checkIdface:key1");
log.info(a.toString());
log.info("del结果："+Tools.DelRedisValues(redisString,dbindex,password,key));

Jedis jedis = new Jedis("10.1.13.68",Integer.parseInt("6379"));
jedis.auth(password);
jedis.connect();
jedis.select(Integer.parseInt(dbindex));
// jedis.del("checkIdface:key1");
log.info("del结果："+jedis.del("checkIdface:key1"));

**Comment by youliyuan-fit2cloud** [comment]
最新版本未复现。
