### ISSUE TITLE
[BUG]自定义插件断言，影响下一步自定义请求

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30655]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

依据自定义插件开发文档，https://metersphere.io/docs/v2.x/automation_plugin_dev/ ，开发的ssh插件，在场景中使用该插件，其断言影响到下一个场景步骤

### 重现步骤

1.依据自定义插件开发文档，https://metersphere.io/docs/v2.x/automation_plugin_dev/ ，开发的ssh插件，设置断言后，断言失败
2. 场景添加下一步自定义请求，不设置断言，请求结束后，发现断言处显示了上一步的断言

### 期待的正确结果

不同步骤的断言不能互相影响

### 附加信息

![1714459518560](https://github.com/metersphere/metersphere/assets/145318182/a51178f3-d00f-4eb8-9045-0f4179e3c330)
![1714459555324](https://github.com/metersphere/metersphere/assets/145318182/a1e1c798-fa4c-4f98-bd85-bd703a52ce4a)

**Comment by fit2cloud-lijiaxin** [comment]
使用官方插件：https://github.com/metersphere/metersphere-plugin-DummySampler，仍然存在上述问题
![1714462812791](https://github.com/metersphere/metersphere/assets/145318182/f8f1b7cb-357d-4b52-be2d-5d23159f94e6)

![1714462794815](https://github.com/metersphere/metersphere/assets/145318182/c8377340-7705-43dd-b02b-fd37934cbbdf)

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.16-lts版本修复这个问题。

**Comment by LukaDoncic-Magic** [comment]
您好，问题已修复，官方插件已更新，请您升级到v2.10.15-lts版本
