### ISSUE TITLE
[BUG]  个人信息-第三方平台账号，删除其中的账号，保存不生效

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#30659]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

对接了第三方平台，删除任何一个平台的账号密码，保存不生效

https://github.com/metersphere/metersphere/assets/33945037/ffa2110c-1a29-4e26-9923-fb061ef39cdf

### 重现步骤

对接了第三方平台，删除任何一个平台的账号密码，保存不生效

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.16-lts版本修复这个问题。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
