### ISSUE TITLE
[BUG]jmeter内置函数${__time}在生成测试数据失败

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30657]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

内置函数${__time}在生成测试数据功能不能成功返回当前时间戳

### 重现步骤

1.在接口请求参数，使用jmeter内置函数${__time} ，点击生成测试数据，生成浮点数
2.若在接口请求参数处，填写${__time}，点击测试，查看请求内容，可以成功返回时间戳

### 期待的正确结果

在接口请求参数，使用jmeter内置函数${__time} ，点击生成测试数据，可成功生成时间戳

### 附加信息

![企业微信截图_87020ec2-ddd1-45ea-9a07-260cec56bdc0](https://github.com/metersphere/metersphere/assets/145318182/054c21c4-c4f0-4acd-af10-b7ce83c4880b)
![1714465250598](https://github.com/metersphere/metersphere/assets/145318182/8124281e-2503-4c3
![1714465222198](https://github.com/metersphere/metersphere/assets/145318182/855c939c-94e1-4fb9-bb36-0f7aec80e7cf)
8-b257-3118fe20b1d1)

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，jmeter内置函数只有在点击测试的时候才会触发并执行
