### ISSUE TITLE
[BUG]【缺陷管理】关联jira平台，使用jira模板的项目，从其他页面切到缺陷管理，缺陷管理列表页面加载很慢。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#30664]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

【缺陷管理】关联jira平台，使用jira模板的项目，从其他页面切到缺陷管理，缺陷管理列表页面加载很慢。

### 重现步骤

【缺陷管理】关联jira平台，使用jira模板的项目，从其他页面切到缺陷管理，缺陷管理列表页面加载很慢。

**Comment by 13290445582** [comment]
您好，请问用的哪个版本的jira插件与jira平台，可将jira缺陷内容导出下，本地测试没有出现加载很慢，感谢理解。

**Comment by 2lipan** [comment]
使用的 v2.10.14-lts版本，勾选了 jira模板，然后切到 缺陷管理 页面，页面会加载转圈。我这边数据也就18条，转圈需要等6秒左右，客户那边数据量多，转圈时间更长。
![1715235560432](https://github.com/metersphere/metersphere/assets/104960608/90e05d10-6034-4b17-af05-6d2550200794)

![image](https://github.com/metersphere/metersphere/assets/104960608/5eec4d81-dbd3-4478-8fc8-26d4bc00ce57)

**Comment by 13290445582** [comment]
已反馈至tapd，后续是否优化会及时告知。

**Comment by 13290445582** [comment]
您好，如果配置了使用jira模板，加载列表的时候会调用jira的接口获取表头字段，目前看是请求jira耗时太长，因为目前配置的sass版的jira是国外的网址，访问起来是会比较慢，建议配置代理，如果是私有化部署的应该就比较快，感谢理解与支持。
