### ISSUE TITLE
[BUG]接口转性能测试，全局断言影响结果

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#30679]
### MeterSphere 版本

v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

[BUG]接口转性能测试，全局断言影响结果

### 重现步骤

1、接口测试case使用全局断言
2、转性能测试case
3、执行性能测试事务全失败（之前有个开发让上传一个jar包）

### 期待的正确结果

优化，减少这个全局断言影响

### 附加信息

import org.json.*;

//获取上一个请求的返回
String jsonString = prev.getResponseDataAsString();
JSONObject responseJson = new JSONObject(jsonString);

String fbpcontent = responseJson.getString("message");

value = fbpcontent;
//result = value.contains("成功");
result = value.contains("成功")||value.contains("已下发")||value.contains("已修改")||value.contains("新的事件待审批")||value.contains("已提交")||value.contains("运行或稽查部门无查看权限")||value.contains("一条工单只能延期一次")||value.contains("终止任务失败")||value.contains("已全部")||value.contains("审核完成");
if (!result){
    
	msg = "assertion [" + value + " contains '成功']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
// else if
}

**Comment by 13290445582** [comment]
您好，上传jar包是无法解决此问题了吗？可以提供下您的jmx文件吗。

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
