### ISSUE TITLE
[BUG]SQL查询结果切换table模式展示异常

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#30688]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

SQL查询结果使用table模式展示异常，没有数据或切换无效

### 重现步骤

1、创建任意一个SQL查询场景，在场景中点调试，然后切换table展示，实际无效，数据都没有了
<img width="911" alt="6e8fda9e96887b3914097e999714d26" src="https://github.com/metersphere/metersphere/assets/88763608/8e1f9e5f-3def-4e29-bea9-e178c04bf610">
2、在场景列表点击执行，切换table展示，实际无效
<img width="909" alt="4302b1ca3820fcbc47d0601f3fa9d5c" src="https://github.com/metersphere/metersphere/assets/88763608/00f8abca-c2fa-4169-ba9c-cfd5f7888ac9">
3、历史版本正确的效果是这样的
<img width="828" alt="e7660c69e04082c0c6b936d0f3b84ba" src="https://github.com/metersphere/metersphere/assets/88763608/10fe189e-1042-49c3-b470-2f84d1d36291">

### 期待的正确结果

<img width="828" alt="e7660c69e04082c0c6b936d0f3b84ba" src="https://github.com/metersphere/metersphere/assets/88763608/bf113920-7e5b-43f2-85e9-5666448f7cbe">

**Comment by 13290445582** [comment]
已有重复issue。https://github.com/metersphere/metersphere/issues/29194
