### ISSUE TITLE
[BUG]接口自动化场景执行，其中某些接口报错（单独调试运行是正常得，导出jmeter脚本运行也是好的），影响自动化得核心功能

### ISSUE THREAD

**Issue by youngkevin1** [metersphere/metersphere#3068]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题

<pre>SyntaxError: Unexpected token W in JSON at position 107<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/opt/node_modules/_body-parser@1.19.0@body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /opt/node_modules/_body-parser@1.19.0@body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/opt/node_modules/_raw-body@2.4.0@raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/opt/node_modules/_raw-body@2.4.0@raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/opt/node_modules/_raw-body@2.4.0@raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:314:20)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1244:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:80:21)</pre>
**Bug 重现步骤**
1.  多接口串联自动化场景执行
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/56627749/119287997-500d1a00-bc7a-11eb-8039-15bca8441e6e.png)
![image](https://user-images.githubusercontent.com/56627749/119288040-65824400-bc7a-11eb-83fa-082185fe20a0.png)
![image](https://user-images.githubusercontent.com/56627749/119288073-729f3300-bc7a-11eb-81d5-44c05eea0552.png)
![image](https://user-images.githubusercontent.com/56627749/119288133-8f3b6b00-bc7a-11eb-9eea-eb77f5065536.png)

**Comment by zyyfit** [comment]
您好，看这个报错是token的问题，是否是由于token获取或者是引用导致的问题呢？

**Comment by zyyfit** [comment]
或者是否勾选了共享cookie之类的影响了token的取值？

**Comment by youngkevin1** [comment]
并非token的问题，本身这几个接口都没有用到token，单独跑都是通过的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口自动化场景执行，其中某些接口报错（单独调试运行是正常得，导出jmeter脚本运行也是好的），影响自动化得核心功能 (#3068)





 
您好，看这个报错是token的问题，是否是由于token获取或者是引用导致的问题呢？

**Comment by youngkevin1** [comment]
> 或者是否勾选了共享cookie之类的影响了token的取值？

也并未勾选共享cookie

**Comment by youngkevin1** [comment]
应该是参数的转义错误导致解析错误产生的异常，看了下请求的data，应该是数组的转义异常导致，有的数据转义给加了双引号，有的转义没加，加了双引号的case就会报该异常，请具体排查请求体带[]的转义代码块逻辑谢谢！ @zyyfit

**Comment by youngkevin1** [comment]
> 应该是参数的转义错误导致解析错误产生的异常，看了下请求的data，应该是数组的转义异常导致，有的数据转义给加了双引号，有的转义没加，加了双引号的case就会报该异常，请具体排查请求体带[]的转义代码块逻辑谢谢！ @zyyfit

json.parse()识别不了导致的报错

**Comment by zyyfit** [comment]
好的，我们排查一下问题

**Comment by zyyfit** [comment]
您好，1.10.1版本已修复，请升级使用最新版
