### ISSUE TITLE
[BUG]切换至英文版有些展示还是中文

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#30695]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

切换至英文版本，但是页面上有些提示还是中文的

### 重现步骤

切换至英文版本，点击操作

### 期待的正确结果

切换至英文版本，都是英文展示

### 相关日志输出

```shell
无
```

### 附加信息

[metersphere英文版问题.docx](https://github.com/metersphere/metersphere/files/15245797/metersphere.docx)

**Comment by youliyuan-fit2cloud** [comment]
非常感谢您反馈，后续版本优化～

**Comment by song-cc-rock** [comment]
多谢提供文档, 我们会修复其中大部分, 由于有部分是系统内置的数据, 无法国际化.

**Comment by 13290445582** [comment]
您好，非常抱歉，暂不处理该情况了。
