### ISSUE TITLE
[FEATURE]当接口返回类型为文件时，应能显示出正确的文件内容或者允许将文件下载到本地。

### ISSUE THREAD

**Issue by xuri422** [metersphere/metersphere#3069]
**请描述您的需求或者改进建议.**
比如当某个接口返回的响应体为文件类型时，例如excel文件、pdf文件或其他类型的文件。这个在很多项目的接口应用上非常常见。应允许使用者下载接口返回响应体内的文件。

**请描述你建议的实现方案**
目前【响应内容】-->【响应体】只有4种格式：json/text/html/xml，如果对于结构性文件来说，当前这4种显示的结果都是乱码，且无法下载到本地。建议增加一种file类型，允许使用者直接将接口返回的文件下载到本地，方法查看文件内容。

**Comment by xulinde** [comment]
感谢反馈，后续版本可以添加该功能

**Comment by luty2018** [comment]
抱歉长时间未回复， 这个功能我们计划放到v3.0做，为了安全起见，可能会把字节码存到文件管理里面去，然后引导用户去那里下载。
