### ISSUE TITLE
[BUG] 【测试跟踪】用例评审时，点击上一条、下一条切换用例，前置条件没有切换。

### ISSUE THREAD

**Issue by Test-Alan** [metersphere/metersphere#30708]
### MeterSphere 版本

 v2.10.12-lts

### 使用外置数据库

否

### 问题描述

上一条的前置条件中有内容，下一条的前置条件没有内容
点击下一条用例，会将上一条用例的前置条件带入到下一条用例的前置条件中
类似这个bug #26420

### 重现步骤

类似这个bug #26420

**Comment by 13290445582** [comment]
您好，在最新的本地环境未复现该问题，是如何复现的这个问题，升级到最新的还会有这个问题嘛？
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/f4eec7bd-ef1b-4e7a-8a5e-c841e2586b45">
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/8859b19d-9571-4a06-b720-b8dbc6685cb8">

**Comment by Test-Alan** [comment]
你好，需要是当前用例有写前置条件，后一条用例前置条件为空的情况下。点击下一条用例才能复现。
如果后一条用例也有前置条件是正常的。
@13290445582

**Comment by 13290445582** [comment]
您好，的确是无法复现，您可以将您这两条功能用例导出提供给我，我复现下。
<img width="1284" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/405d851b-e376-498d-970d-f179e2c461ba">
<img width="1271" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/23e3cae1-a846-4d12-9081-42aa73fa5d0f">

**Comment by Test-Alan** [comment]
@13290445582 
你好，你两次的评审界面都不一样，用你上次的评审界面复现一下。
我使用的版本是： v2.10.12-lts
你最新截图的使用的是什么版本？

**Comment by 13290445582** [comment]
你好，我本地环境是v2.10.14，不清楚你这里是什么原因导致的。建议可以：1、切换无痕浏览器，并且新建用例和评审再次测试下是否有此问题。2、可以升级最新版本v2.10.14版本测试下本问题是否可以解决3、可以将你的用例导出，在我的环境看看是否有问题，不清楚是不是因为某字段影响。
<img width="1439" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/94b6e9ac-f546-436f-8693-a1b5cb5af309">
<img width="1439" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/a13ca709-8f7a-47e4-b91e-7d082be21c70">
