### ISSUE TITLE
[FEATURE] 环境配置期望增加批量更新环境域名的操作，变通达到 postman 全局变量的效果

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#30719]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/79577571/3f5d0b74-20c7-4707-98b1-185d3ef916ec)

### 请描述你建议的实现方案

期望增加批量更新环境域名的操作

**Comment by luty2018** [comment]
你好， 我们会在v3后续版本中同步支持全局变量。

**Comment by qian-kui** [comment]
**跟进：不是让整个项目使用全局变量。**
eg：一个项目下有环境变量：A1、A2、A3 ; B1、B2
期望: 可以自行选择一个项目下的环境变量A1、A2、A3 的全局变量是 Q；B1、B2的全局变量是 X
![image](https://github.com/metersphere/metersphere/assets/79577571/8eaaebd6-d72d-411a-a2bd-f0f23d45ce08)
