### ISSUE TITLE
[BUG]测试计划的场景用例如果步骤是SQL类型，测试计划运行生成的报告状态一直是pending

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#30714]
### MeterSphere 版本

2.10.10

### 使用外置数据库

否

### 问题描述

同样的场景用例，如果在详情页面调试，生成的报告是成功，但是在测试计划中点执行，该步骤就是pending，同样在场景列表中点执行按钮，也是pending，但实际上这个步骤是执行了的

### 重现步骤

1.新建三个步骤的场景，步骤1是HTTP，步骤2是SQL，步骤3随便写个自定义脚本print吧
2.点击调试-生成报告
3.回到列表页面，点击执行按钮

### 期待的正确结果

不管怎么执行，都不要丢失结果

**Comment by zcyuefan** [comment]
是只有生成报告就会丢失，如果直接在编辑页面点调试按钮，是可以看到运行结果的

**Comment by 13290445582** [comment]
您好，未复现您所描述的情况，正常来说是不会有问题的，可以检查替换下数据源尝试，或者升级至最新版本使用。可将场景导出提供下。
<img width="1122" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/0b5c1432-9278-4141-87b6-1760e294612f">

**Comment by zcyuefan** [comment]
数据库是pg试一试

**Comment by 13290445582** [comment]
您好，测试了下也是可以的。
<img width="904" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/d37e3d2d-9af1-4eab-8b24-aa6a627dd16e">
<img width="1263" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/87566025-f403-47eb-950b-50ba66941b38">

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
