### ISSUE TITLE
[BUG]修改API 参数后保存，未开启【一键同步case】，该 API 下的 CASE 没有到【工作台-我的待办-接口用例-待更新】列表

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#30715]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.14

### 使用外置数据库

否

### 问题描述

修改API 参数后保存，未开启【一键同步case】，该 API 下的 CASE 没有到【工作台-我的待办-接口用例-待更新】列表

### 重现步骤

1 修改 api 参数，不开启【一键同步case】，点击保存
![image](https://github.com/metersphere/metersphere/assets/30038088/e4e6057e-a2dc-4184-b931-71f2c0b1342a)
2 到【工作台-我的待办-接口用例-待更新】列表查看 ，没有待更新的用例信息。
![image](https://github.com/metersphere/metersphere/assets/30038088/66c4ec8e-8a82-444e-9a6f-5ebc3f50a5da)

### 期待的正确结果

不开启【一键同步case】，修改 api 后，在【工作台-我的待办-接口用例-待更新】列表可以查看待更新的用例信息。

**Comment by 13290445582** [comment]
请检查所变更的API、CASE创建人是否为当然用户。接口用例进入待更新的规则是：查询所选项目下接口用例中创建人包含自己且接口过去3天有更新的用例 或 执行结果为失败的用例。

**Comment by shenkaibo** [comment]
验证后可以了，感谢回复。
还有一个问题，超过3天 未更新用例，就不在这个 「待更新」列表了么？

**Comment by 13290445582** [comment]
是的，超过3天 未更新用例，就不在这个 「待更新」列表了。

**Comment by shenkaibo** [comment]
好的 ，感谢回复！
