### ISSUE TITLE
[FEATURE]建议在测试计划列表 增加执行标签并可支持筛选 等列表标记或备注测试计划执行情况的功能

### ISSUE THREAD

**Issue by chenyiming04** [metersphere/metersphere#30735]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 联系方式

563405011@qq.com

### 请描述您的需求或者改进建议

我们的项目 同一用例同时适用多端，执行时需要同一用例多端各执行一次，故测试计划是需要同一用例关联多次，但执行时目前无法标记这条案例是在哪端执行了。（执行评论无法解决我的问题，经测试执行评论归属于用例，测试计划中无法区分）

### 请描述你建议的实现方案

在测试计划列表 增加执行标签并可支持筛选

**Comment by luty2018** [comment]
感谢建议， 这个在v3.0 版本已经规划了
