### ISSUE TITLE
[BUG]查询数据库，字段里存的是段json字符串，取出来打印时报错

### ISSUE THREAD

**Issue by goodboyxzmkk** [metersphere/metersphere#30745]
### 联系方式

346315670@qq.com

### MeterSphere 版本

v2.10

### 使用外置数据库

否

### 问题描述

查询数据库，字段里存的是段json字符串，取出来打印时报错

详情看截图

### 重现步骤

数据库出来的数据：

createTime	TokenSessionJson
1715321398	{"ksMerchantId":"210000510000787497","access_token":"ChFvYXV0aC5hY2Nlc3NUb2tlbhJg1d2uZev6HJN2Zk_BXaB6iQM-g6glW8OLBjZxmuSNluh_chVANiuEQBTd-HoDzDTcbQVFKUvg3Dg7TEcimNeLmhkHH39SHl8Zzb6kkwA8LQXRRogmZ876vZfkjQKNXA6qGhJeYh3ez_1OmqcJLgWXKJeQiGEiIMbMI6_g21vyOAXjw3eYcHsBabXcBEmeC9Mg63Bt3X5lKAUwAQ","refresh_token":"ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAG0C3mHUPIlchSf-2WjR-QwVokUso4MMDuHnfDidlFZ4s70L_ICa7HiFNJbztlRkDR343_vL1Em9ha73WuVnjgbG6PMeiS4aLfip0eF5w53JEVRXwERvfMwbOMaKPWgJOsnNniUneqPRMJOkbyqiMZ40E4Zv1Q2jS5K6MoPXd7Cy-OMgufhU3EomC5axjcozFowIyrF4R768cQL0tImDJoeG_7cOF9efbpAceGl6iC-iBoSuymAGzap50-BticZqUGVlxofIiBVT0GcxKnp6pNNe9SKC0kY2o0ACffx13RmfNT8TGKl8igFMAE","open_id":"f18b4f029a2a16e614bf5724d23d124b","scopes":["life.capacity.fulfilment","life.capacity.product","life.capacity.shop","user_info","life.capacity.order.query","life.capacity.bill","life.capacity.distribution"],"expires_in":172800,"refresh_token_expires_in":15552000,"expTime":"2024-05-11 18:09:58","refreshTokenExpTime":"2024-11-06 06:09:58"}

### 附加信息

![1b7c7ccaa7acf105067a754987bd4309](https://github.com/metersphere/metersphere/assets/43720321/43b526cc-3f58-4330-8b00-cf5663765759)
![880c997aad774b5763f9f1ecdcd20b7](https://github.com/metersphere/metersphere/assets/43720321/9afe2ae9-7730-40dc-b3a6-7c1f70489029)

**Comment by 13290445582** [comment]
您好，打印请使用获取变量这种用法:log.info(vars.get("variable_name"))。
![image](https://github.com/metersphere/metersphere/assets/128017892/bcd16834-f08e-4f9b-b54d-fafe69be6d19)
