### ISSUE TITLE
微信群满员，请求增加2 3 4 5 6 7 8 群 祝越做越好

### ISSUE THREAD

**Issue by 494009061** [metersphere/metersphere#30747]
### 请描述您的问题

微信群满员，请求增加2 3 4 5 6 7 8 群 祝越做越好

**Comment by fit2-zhao** [comment]
https://metersphere.io/docs/v2.x/about/contact/#1

您好，你可以打开链接添加小助手微信，他将会将您拉进 MeterSphere 交流群中。
