### ISSUE TITLE
[BUG]接口测试环境配置页面复制原来环境变量后，更新名称进行保存，将xxxcopy的也会保存一份

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#30759]
### 联系方式

wannaspace@163.com

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

复制原来的环境，保存时候提示名称重复（实际未重复）
这时候把 ”xxxcopy“-->更新为“xxxcopy更新名称”，保存后即把 ”xxxcopy“又把“xxxcopy更新名称”这俩环境变量都给保存了

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/79577571/46800927-54a7-427a-a5b8-9319d0d1db3b)
![image](https://github.com/metersphere/metersphere/assets/79577571/ea87c052-3231-4e45-995e-5a358c585b68)

**Comment by youliyuan-fit2cloud** [comment]
你好，应该是第一次复制之后，没有立即显示，然后再次复制了吧。后续版本会优化一下。

**Comment by 13290445582** [comment]
您好，v2.10.21版本已修复，请升级。
