### ISSUE TITLE
[FEATURE]支持接口批量创建用例

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#3076]
**请描述您的需求或者改进建议.**
希望支持一键自动生成用例，生成的用例里面的请求数据和接口录入的时候一模一样，或者按照一定策略生成

**Comment by xulinde** [comment]
目前是支持的，接口定义列表直接点case会自动创建一条用例，批量的话，支持复制用例

**Comment by Dyc2333** [comment]
指的是能够批量生成多个接口的各1条用例，不是一个接口的多个用例。
