### ISSUE TITLE
[BUG]SQL CASE自动保存后没有变更记录

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#30764]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

SQL CASE自动保存后没有变更记录

### 重现步骤

1、原来的内容如下
![image](https://github.com/metersphere/metersphere/assets/88763608/f998dcc8-5324-49ad-822d-4d565270d24c)
2、在 SQL CASE中修改SQL脚本，并执行
![image](https://github.com/metersphere/metersphere/assets/88763608/53dae2aa-2ea5-43af-84e1-1d532fc19a42)

3、将SQL CASE关闭再重新打开，发现SQL脚本已经是修改过的内容
![image](https://github.com/metersphere/metersphere/assets/88763608/326bd89a-5ebc-41ef-9e34-caf9286e0e53)

4、但是变更记录中没有内容
![image](https://github.com/metersphere/metersphere/assets/88763608/4b4062d4-71ce-47de-b494-e9ba4e94e914)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，如果修改后没点 “保存”确实存在该问题。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
