### ISSUE TITLE
[BUG] 循环控制器条件为对象非空，未执行

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30788]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

循环控制器条件为对象非空，未执行

### 重现步骤

提取响应体中的一个对象和字符串
![image](https://github.com/metersphere/metersphere/assets/103925124/22eb6f8c-5525-447b-af01-37575b5bd767)
![image](https://github.com/metersphere/metersphere/assets/103925124/263c1a78-28e7-43e0-9748-7294d6f54515)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
