### ISSUE TITLE
[BUG]发现请求可篡改异常

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#30789]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

通过安全部门扫描出来的漏洞。

### 重现步骤

发现CORS，可通过篡改HTTP请求头，获取请求信息。
请求地址是http://ms服务器ip:8081

### 期待的正确结果

修复这个安全漏洞

**Comment by fit2-zhao** [comment]
感谢反馈，目前应用代码层面不会做限制，用户可以通过部署 Nginx 解决跨域资源共享（CORS）问题，可以通过配置 Nginx 代理服务器来统一添加和管理 CORS 相关的 HTTP 头部。在 Nginx 配置中，设置特定的 HTTP 头部以允许跨域请求。
