### ISSUE TITLE
[BUG]接口返回的数据没有做转义，导致实际返回的数据有问题

### ISSUE THREAD

**Issue by qingqingguan** [metersphere/metersphere#30797]
### 联系方式

18229918212@163.com

### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

接口本应返回的数据格式是个json格式，但是metersphere这边返回的数据是个错误的json，metersphere这边返回的数据为{"error_info":{"errno":1,"error":"程序正常执行"},"data":{"addtime":1715584513,"alias":0,"file":"{"sourceId":9054932,"eeoFileType":"eeo-image","scheduleType":"eeoconv-img","output":{"IMAGE":{"thumbnail":"thumb/20240513/vfXM2jq3uD3QUtx6.jpg","midsize":"midsize/20240513/vfXM2jq3uD3QUtx6.jpg","large":"large/20240513/vfXM2jq3uD3QUtx6.jpg"},"width":1920,"height":1080}}","fileExtension":"jpg","fileName":"??1","fileSize":151,"path":"upload/trans//","resourceFileType":0,"resourceId":9054932,"resourceType":3,"shareId":8143050,"shareUid":460278}}                                                                                                                
 

同样的参数postman和apifox返回的数据就是正常的经过转义后的json格式，正常的json数据为
{
    "error_info": {
        "errno": 1,
        "error": "程序正常执行"
    },
    "data": {
        "addtime": 1715584550,
        "alias": 0,
        "file": "{\"sourceId\":9054932,\"eeoFileType\":\"eeo-image\",\"scheduleType\":\"eeoconv-img\",\"output\":{\"IMAGE\":{\"thumbnail\":\"thumb/20240513/vfXM2jq3uD3QUtx6.jpg\",\"midsize\":\"midsize/20240513/vfXM2jq3uD3QUtx6.jpg\",\"large\":\"large/20240513/vfXM2jq3uD3QUtx6.jpg\"},\"width\":1920,\"height\":1080}}",
        "fileExtension": "jpg",
        "fileName": "??1",
        "fileSize": 151,
        "path": "upload/trans//",
        "resourceFileType": 0,
        "resourceId": 9054932,
        "resourceType": 3,
        "shareId": 8024332,
        "shareUid": 117456
    }
}

### 重现步骤

{"error_info":{"errno":1,"error":"程序正常执行"},"data":{"addtime":1715584513,"alias":0,"file":"{"sourceId":9054932,"eeoFileType":"eeo-image","scheduleType":"eeoconv-img","output":{"IMAGE":{"thumbnail":"thumb/20240513/vfXM2jq3uD3QUtx6.jpg","midsize":"midsize/20240513/vfXM2jq3uD3QUtx6.jpg","large":"large/20240513/vfXM2jq3uD3QUtx6.jpg"},"width":1920,"height":1080}}","fileExtension":"jpg","fileName":"??1","fileSize":151,"path":"upload/trans//","resourceFileType":0,"resourceId":9054932,"resourceType":3,"shareId":8143050,"shareUid":460278}}               

### 期待的正确结果

{
    "error_info": {
        "errno": 1,
        "error": "程序正常执行"
    },
    "data": {
        "addtime": 1715584550,
        "alias": 0,
        "file": "{\"sourceId\":9054932,\"eeoFileType\":\"eeo-image\",\"scheduleType\":\"eeoconv-img\",\"output\":{\"IMAGE\":{\"thumbnail\":\"thumb/20240513/vfXM2jq3uD3QUtx6.jpg\",\"midsize\":\"midsize/20240513/vfXM2jq3uD3QUtx6.jpg\",\"large\":\"large/20240513/vfXM2jq3uD3QUtx6.jpg\"},\"width\":1920,\"height\":1080}}",
        "fileExtension": "jpg",
        "fileName": "??1",
        "fileSize": 151,
        "path": "upload/trans//",
        "resourceFileType": 0,
        "resourceId": 9054932,
        "resourceType": 3,
        "shareId": 8024332,
        "shareUid": 117456
    }
}

**Comment by 13290445582** [comment]
您好，您给出的这两段json，看起来是一样的，没看到转义内容。建议使用Jmeter 5.5测试下，我们与Jmeter 5.5保持一致。也可以提供下您测试所用的接口、参数、环境，帮助我们复现下。
![image](https://github.com/metersphere/metersphere/assets/128017892/8d6f656c-c3a6-43e1-b510-4866a6e6024f)

**Comment by qingqingguan** [comment]
辛苦再帮忙看看。
metersphere返回的：
{"error_info":{"errno":1,"error":"程序正常执行"},"data":{"addtime":1715592516,"alias":0,"file":"{"sourceId":9079191,"eeoFileType":"eeo-image","scheduleType":"eeoconv-img","output":{"IMAGE":{"thumbnail":"thumb/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png","midsize":"midsize/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png","large":"large/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png"},"width":2521,"height":1107}}","fileExtension":"png","fileName":"1","fileSize":186,"path":"upload/trans//","resourceFileType":0,"resourceId":9079191,"resourceType":3,"shareId":8024342,"shareUid":460278}}
 metersphere返回的到json.cn解析之后会变成这样：

![image](https://github.com/metersphere/metersphere/assets/18351268/d05fd099-70e2-43e3-b49b-92e64c36da6f)




正常的json：
{
    "error_info": {
        "errno": 1,
        "error": "程序正常执行"
    },
    "data": {
        "addtime": 1715592317,
        "alias": 0,
        "file": "{\"sourceId\":9079191,\"eeoFileType\":\"eeo-image\",\"scheduleType\":\"eeoconv-img\",\"output\":{\"IMAGE\":{\"thumbnail\":\"thumb/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\",\"midsize\":\"midsize/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\",\"large\":\"large/20240508/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\"},\"width\":2521,\"height\":1107}}",
        "fileExtension": "png",
        "fileName": "1",
        "fileSize": 186,
        "path": "upload/trans//",
        "resourceFileType": 0,
        "resourceId": 9079191,
        "resourceType": 3,
        "shareId": 8053568,
        "shareUid": 460278
    }
}

**Comment by qingqingguan** [comment]
postman返回之后是这样的，请参考下
![image](https://github.com/metersphere/metersphere/assets/18351268/fa97c1f3-0187-49e6-8ff0-c5c58e80da69)

**Comment by 13290445582** [comment]
您好，将测试接口、参数、环境导出提供下吧，单看响应体也无法找到问题所在。或者您可以在JMeter上试一下，看下JMeter返回的响应体是什么样子的。

**Comment by qingqingguan** [comment]
Jmeter返回结果：
{"error_info":{"errno":1,"error":"程序正常执行"},"data":{"addtime":1715594391,"alias":0,"file":"{\"sourceId\":9079191,\"eeoFileType\":\"eeo-image\",\"scheduleType\":\"eeoconv-img\",\"output\":{\"IMAGE\":{\"thumbnail\":\"thumb\/20240508\/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\",\"midsize\":\"midsize\/20240508\/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\",\"large\":\"large\/20240508\/00_01_82e4699-cf15-4047-981a-1f5a10ddf1d.png\"},\"width\":2521,\"height\":1107}}","fileExtension":"png","fileName":"1","fileSize":186,"path":"upload\/trans\/\/","resourceFileType":0,"resourceId":9079191,"resourceType":3,"shareId":8143077,"shareUid":460278}}


![image](https://github.com/metersphere/metersphere/assets/18351268/1711ff44-9ce9-4b10-b386-0d8d19308f89)

**Comment by 13290445582** [comment]
jmx文件方便提供吗，仅测试复现用。

**Comment by qingqingguan** [comment]
[im聊天.zip](https://github.com/metersphere/metersphere/files/15293795/im.zip)

**Comment by qingqingguan** [comment]
@13290445582  jmx文件已提供，辛苦查看。

**Comment by 13290445582** [comment]
您好，根据您提供的文件，在MeterSphere内测试与Jmeter的返回结果一致。
<img width="1313" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/871a628a-6063-4e8c-9c8b-0cb2566018f5">
<img width="1318" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/b4c91f44-89d8-4f34-904e-e601a826672c">
<img width="598" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/35f90dfa-7d4f-4511-9434-4f4b1e0f4682">

**Comment by qingqingguan** [comment]
![image](https://github.com/metersphere/metersphere/assets/18351268/f9c5cb59-61eb-4593-aa91-af59b3b94e33)

**Comment by qingqingguan** [comment]
![image](https://github.com/metersphere/metersphere/assets/18351268/6cfb0f8a-6a16-4b16-9ff5-e76544048d91)
我们用的这个版本有问题。

**Comment by qingqingguan** [comment]
![image](https://github.com/metersphere/metersphere/assets/18351268/a685c8a6-58eb-420d-b76c-92d25c9bc837)

**Comment by 13290445582** [comment]
您好，经过多次尝试，本地测试一直是正常的。建议您新建个空的工作空间、项目测试下或者弄个新的环境测试下，后续我们仍会留意这种问题， 有反馈会同步给您，感谢理解与支持。
