### ISSUE TITLE
[BUG]当参数为${__RandomString}点调试，报空错

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#308]
![image](https://user-images.githubusercontent.com/12756697/91702125-d93f6680-ebaa-11ea-81b2-9b997c6555cb.png)
![image](https://user-images.githubusercontent.com/12756697/91702323-27ed0080-ebab-11ea-8953-bafaf23923b4.png)

**Comment by liuruibin** [comment]
![image](https://user-images.githubusercontent.com/23045261/91707045-d85e0300-ebb1-11ea-8369-336769278071.png)
