### ISSUE TITLE
[FEATURE]支持被引用case或者场景执行后更新接口列表中case的状态

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#30800]
### MeterSphere 版本

2.10.10企业版

### 请描述您的需求或者改进建议

通常情况下用例都是放在场景中执行了，但是场景执行成功了，case的状态还是pending

### 请描述你建议的实现方案

场景执行后更新被引用case或者场景的状态

**Comment by luty2018** [comment]
但是引用的环境和case自身保存的环境可能不一致， 直接更新运行结果可能不太合适哦
