### ISSUE TITLE
[BUG]【接口测试】域名过长，在绑定域名时提示域名不合法

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#30802]
### MeterSphere 版本

v2.10.14

### 使用外置数据库

否

### 问题描述

 生产环境的域名有点长，在环境配置中绑定域名时，提示域名不合法,减少域名的长度，可以正常绑定

### 重现步骤

1、进行环境配置
2、绑定域名

### 期待的正确结果

可以正常绑定域名

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/45531073/a60a9db2-c053-4ad7-a130-e9f988a98710)

域名
mno-e2e-public-nlb-5f0a072c51681998.ebb.cn-north-1.amqqonaws.com.cn

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
