### ISSUE TITLE
[FEATURE]模版字段支持结构化数据

### ISSUE THREAD

**Issue by lvluostudio** [metersphere/metersphere#30804]
### MeterSphere 版本

v2.10.14-lts

### 联系方式

wingle@qq.com

### 请描述您的需求或者改进建议

模版字段支持结构化的数据，在可选择很多的场景下，更方便管理 。比如：
字段名称：供应商
值展示如下（可多选，可以单选）:
-屏幕供应商
--平面屏供应商
---京东方
---富士康
--曲面屏供应商
---京东方
---比亚迪
-键盘供应商
--富士康
--台积电

### 请描述你建议的实现方案

存储用json来格式化树状结构的值。每个节点key=>value的形式，便于前端展示和选择。用例记录扩展字段的Key。
前端根据json定义的数据关系展示可选值。

**Comment by luty2018** [comment]
感谢建议， 这个目前还不是通用需求，短期内还不会做呢。
