### ISSUE TITLE
[BUG]测试计划中，配置执行完成时，发送钉钉群消息 测试计划中用例都执行完成后，保存，，没有接收到消息

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#30814]
### 联系方式

hujirong@patsnap.com

### MeterSphere 版本

版本:   v2.10.5-lts-0ba6e94d

### 使用外置数据库

否

### 问题描述

测试计划中，配置执行完成时，发送钉钉群消息
测试计划中用例都执行完成后，保存，，没有接收到消息
![20240513151154](https://github.com/metersphere/metersphere/assets/50876029/efb82655-5d63-497c-8160-c5950430ffbd)

### 重现步骤

测试计划中，配置执行完成时，发送钉钉群消息
新建测试计划，关联测试用例，切换到脑图，一个一个执行完成，然后保存

### 期待的正确结果

接受到钉钉群消息（这种情况下，站内消息也收不到）

**Comment by 13290445582** [comment]
您好，测试计划内仅关联功能用例，无法触发执行成功/失败/完成的消息通知。因为仅关联功能用例的测试计划，被认为是无法触发执行的，需要有添加接口测试用例/UI测试用例/性能测试用例，才可正确的收到执行完成的消息通知。
<img width="664" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/d6e78cdc-aae2-4037-a7f2-1b314d17b735">
<img width="654" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/bbc8bc97-b667-4a48-b6ce-0e1b57dabfc1">
