### ISSUE TITLE
[BUG]同一个创建一个快捷调试，创建一个接口，快捷调试里可以正常访问，在创建的接口里是错误的

### ISSUE THREAD

**Issue by wallaceok** [metersphere/metersphere#3081]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
在快捷调试里可以正常访问，在创建的接口里不能正常访问。postman里也能执行
**Bug 重现步骤**
1.  同一个创建一个快捷调试，创建一个接口，快捷调试里可以正常访问，在创建的接口里是错误 的 
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/4089901/119325040-0c82d200-bcb3-11eb-99fa-24e567a3da89.png)

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/119325354-5ff52000-bcb3-11eb-9cfe-a606a90ec926.png)
快捷调试进行了转义所以能执行成功，测试接口的页面也需要加自动转义

**Comment by zyyfit** [comment]
v1.10.0 版本已修复
