### ISSUE TITLE
[FEATURE]支持全局断言部分接口过滤，不使用，因为有的接口返回结果不一定使用全局断言

### ISSUE THREAD

**Issue by luogan1502** [metersphere/metersphere#30834]
### MeterSphere 版本

 v2.10.14-lts-a7298117

### 联系方式

60群 昵称：Sunny

### 请描述您的需求或者改进建议

全局断言可以选择使用接口

### 请描述你建议的实现方案

全局断言可以选择使用接口，

**Comment by luty2018** [comment]
感谢建议， 这个功能已经在v3.0实现了， 下个月就可以和大家见面了。
