### ISSUE TITLE
源码部署的无法调用资源池

### ISSUE THREAD

**Issue by CcPersion** [metersphere/metersphere#30837]
### 请描述您的问题

版本号：metersphere-2.10.13-lts
项目是源码本地启动的，ms-node-controller是部署到虚拟机linux中的（虚拟机ip是8.36），并且虚拟机和本机ip可以互相ping通，资源池可以正常启动，检查状态时也可以通过。但是在执行接口测试时，提示‘调用资源池执行失败，请检查资源池配置’
![69EFA906-AC03-431b-89AB-49022B239EFF](https://github.com/metersphere/metersphere/assets/100368287/a430fcd4-c19e-4d72-9340-042422300681)
![0E10C9D5-D46B-47cf-820D-95DAAB62CE60](https://github.com/metersphere/metersphere/assets/100368287/2fe7b94a-2953-44e0-915e-a391bec09ec9)
![5A4E4CD6-EFDE-43cb-9F39-D5BEE2FD4AE2](https://github.com/metersphere/metersphere/assets/100368287/e10ced3b-3898-4242-8aaa-701a58edd9be)
![8F955181-9096-4965-ADEB-EB2F77982BA3](https://github.com/metersphere/metersphere/assets/100368287/9836fc07-b788-4f4d-be94-bddab341492a)
![719E9ED0-77C8-4c27-ADD2-13AF37D52FD6](https://github.com/metersphere/metersphere/assets/100368287/a583f1ed-d1d0-4f90-9774-47433223b430)

**Comment by liuruibin** [comment]
建议使用官方提供的包进行部署，可以选择node-controller模式
