### ISSUE TITLE
[BUG]http请求的响应体xml 编码为GBK中文乱码

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30838]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

http请求，响应体为xml 格式，编码为GBK ,响应体中文乱码

### 重现步骤

MS http请求，响应体为xml 格式，编码为GBK ,响应体中文乱码
使用jmeter5.5，中文显示正常 

### 期待的正确结果

MS http请求，响应体为xml 格式，编码为GBK ,响应体中文正常

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/c5f3b029-187f-401e-9224-9efaa779b1a2)
<img width="849" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/20dc34d5-7410-4f0f-bec3-3c765df34346">
<img width="813" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/564acab3-d0fb-4f80-bc1a-cf2c5aa65262">
![image](https://github.com/metersphere/metersphere/assets/145318182/760e1832-658f-416c-8d32-a9b81c15a614)

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/6ba1b364-7e83-48ee-83c2-a84d8e5631ad)

**Comment by 13290445582** [comment]
<img width="890" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/76b1dc4d-3d5c-46df-833b-bb95b07bf1e1">
您好，请提供下api接口与相关参数。

**Comment by 13290445582** [comment]
您好，已得知该情况，V2暂不支持，在V3支持您选择编码，Jmeter默认为GBK编码，所以是正常的，V2采用的UTF-8，感谢您的理解与支持。V3将支持选择编码，见截图。
<img width="270" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/bd93877b-56c7-41d9-a06c-5b9abaf86883">
