### ISSUE TITLE
[BUG] 用例评审，关联用例时用例列表和关联后用例列表顺序不一致

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30849]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

用例评审，关联用例时用例列表和关联后用例列表顺序不一致

### 重现步骤
选择某模块的全部数据进行关联
![image](https://github.com/metersphere/metersphere/assets/103925124/3f19a1ba-d468-4517-b9fb-fc06d8b04827)
![image](https://github.com/metersphere/metersphere/assets/103925124/b16714df-ece7-408a-90c8-5a8f96a99b7b)

**Comment by youliyuan-fit2cloud** [comment]
你好，关联后的 截图看着经过ID 排序了。不是问题。
