### ISSUE TITLE
[FEATURE]建议考虑人员可以作为集合，在项目分配的时候进行勾选

### ISSUE THREAD

**Issue by qian-kui** [metersphere/metersphere#30852]
### MeterSphere 版本

v2.10.6

### 联系方式

wannaspace@163.com

### 请描述您的需求或者改进建议

当前一个个人员勾选，大几十人、上百人啊手都点麻了
![image](https://github.com/metersphere/metersphere/assets/79577571/21825b24-9be6-4bf0-b1f7-9f463ced74a8)

### 请描述你建议的实现方案

建议考虑人员可以作为集合，在项目分配的时候进行勾选

**Comment by qian-kui** [comment]
有点像微信的标签，这一类是标签是A，另一类人标签是B。A和B 也有重叠部分人员。
在发朋友圈可以快速的只给/不给标签为A的人看，意思大概就是这样。

**Comment by luty2018** [comment]
我们有规划这个功能， 可以关注后续版本规划
