### ISSUE TITLE
[FEATURE]性能测试高级配置中设置结果文件格式为xml不生效

### ISSUE THREAD

**Issue by olivia2046** [metersphere/metersphere#30876]
### MeterSphere 版本

v2.9.1-32da5112

### 使用外置数据库

是

### 问题描述

在性能测试高级配置中，自定义变量和jmeter properties里都试了设置jmeter.save.saveservice.output_format为xml，保存并执行后，下载JTL文件，未生效，仍然是CSV格式

### 重现步骤

在性能测试高级配置中，jmeter properties里设置jmeter.save.saveservice.output_format为xml，保存并执行后，下载JTL文件，文件仍为CSV格式

### 期待的正确结果

文件为XML格式

**Comment by liuruibin** [comment]
性能测试仅支持输出csv格式，请见谅

**Comment by olivia2046** [comment]
> 性能测试仅支持输出csv格式，请见谅

能否在后续版本中添加支持，因需要在非企业版中查看请求、响应的详细内容，而CSV格式不支持记录响应数据

**Comment by liuruibin** [comment]
很遗憾，我们不会再社区版中进行优化。您可以试用企业版，在资源池关闭后置监听器后执行可以查看采样统计
<img width="1937" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/8119f894-e643-49c7-8489-7d665a4dbcb7">
