### ISSUE TITLE
[BUG] 在非metersphere平台调用mock接口，响应体中的变量未解析出来

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30875]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

 在非metersphere平台调用mock接口，响应体中的变量未解析出来

### 重现步骤

mock接口的设置：：：
![image](https://github.com/metersphere/metersphere/assets/103925124/81a6a0f0-c5d8-4fbe-9fc4-34c45567de8b)
![image](https://github.com/metersphere/metersphere/assets/103925124/998684c8-7822-4c0e-a1cb-63ee081cf439)
在metersphere平台执行正常：
![image](https://github.com/metersphere/metersphere/assets/103925124/63ad63e3-429c-4cfd-a380-d787df205e73)
在fei非metersphere平台执行响应体的变量未解析：：
![image](https://github.com/metersphere/metersphere/assets/103925124/4a5afdbc-3f52-4944-ad27-955a782aa09d)

**Comment by fit2cloud-yaochunrong** [comment]
设置请求体为json格式
![image](https://github.com/metersphere/metersphere/assets/103925124/be6356b6-5625-4c45-b279-64ff48757fa7)
添加后置脚本，获取json请求体后放置为变量用于响应体
![image](https://github.com/metersphere/metersphere/assets/103925124/e840a5b1-9c13-41d2-a8bb-9ed15379f5be)
在metersphere执行正常：
![image](https://github.com/metersphere/metersphere/assets/103925124/39e31a9b-94fd-4450-a6ee-8e4ef0730472)
在非metersphere平台执行异常：
![image](https://github.com/metersphere/metersphere/assets/103925124/cc288c75-1482-40b9-9bc4-67845538c7f6)

**Comment by youliyuan-fit2cloud** [comment]
v2.10.15-lts已修复
