### ISSUE TITLE
[BUG]测试计划关联UI用例时，无法选择环境

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#30898]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

测试计划关联UI用例时，选择新环境，环境列表不显示

### 重现步骤

测试计划关联UI用例时，选择新环境，环境列表不显示
<img width="1423" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/b99375bd-8b10-4694-9a5e-a12db8de9959">

### 期待的正确结果

测试计划关联UI用例时，选择新环境，正常显示环境列表

### 附加信息

<img width="1415" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/f4205fbd-1770-4671-af98-78039ba904aa">

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/3a7d2a3d-5e0b-4f06-909b-c395263f3956)

**Comment by fit2cloud-lijiaxin** [comment]
建议加一个 请先选择用例的提示
