### ISSUE TITLE
[BUG]当参数为@integer时，值显示为科学计数法

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#309]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2

**Bug 描述**
简要描述您碰到的问题
当参数为@integer时，值显示为科学计数法

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/91702453-54a11800-ebab-11ea-99c7-62f58a505930.png)

**Comment by liuruibin** [comment]
如果需要给定值的范围可以参考mock.js官网的例子 http://mockjs.com/examples.html ，例如@integer(1000,2000)表示生成一个范围在1000到2000的随机数

**Comment by popolyj** [comment]
系统里并没有任何提示说要去官网哦~
