### ISSUE TITLE
[BUG][p3]导入用例时报失败（模板字段写的有问题），然后再点继续导入会提示导入成功

### ISSUE THREAD

**Issue by yuanweihuaskhb** [metersphere/metersphere#30910]
### 联系方式

18291878104

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

导入用例时报失败（模板字段写的有问题），然后再点继续导入会提示导入成功

### 重现步骤

1、模板字段不正确的excel，导入用例，提示失败
2、然后点击继续导入，又会提示成功（实际未导入）

**Comment by youliyuan-fit2cloud** [comment]
v2.10.15-lts中已修复。
