### ISSUE TITLE
[BUG] 新建场景并发操作时。num非唯一值

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#30916]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

新建场景并发操作时。num非唯一值
如此num出现了重复值：：
![1715939658286](https://github.com/metersphere/metersphere/assets/103925124/b8d6fb70-4323-45c1-a88a-bc48a8a2f382)
![image](https://github.com/metersphere/metersphere/assets/103925124/d2ed9a8f-4491-4d3d-aeb7-8bcfd09045ea)

### 重现步骤

俩人在一个项目里同时点了创建场景

**Comment by liuruibin** [comment]
已知问题，其中一条重新复制一遍就可以

**Comment by fit2cloud-yaochunrong** [comment]
已知问题的话，是计划修复嘛？什么时候修呢@liuruibin
