### ISSUE TITLE
[FEATURE]场景编辑页面右上角增加一个“重新加载”的按钮，让用户不用保存之后离开编辑页面，才能把其他场景加载进来

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#30928]
### MeterSphere 版本

v2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

[FEATURE]场景编辑页面右上角增加一个“重新加载”的按钮，让用户不用保存之后离开编辑页面，才能把其他场景加载进来

**Comment by luty2018** [comment]
这个功能已经有了哦
<img width="1095" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/25ca7502-d0c7-465d-b73d-74f42e95352f">
