### ISSUE TITLE
[BUG]接口测试-接口定义-API中，json格式请求体重新打开json-schema开关会导致之前保存的描述丢失

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#30926]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

接口测试-接口定义-API中，json格式请求体,不小心关掉了json-schema开关,重新打开后之前保存的描述丢失

### 重现步骤

1.在接口测试-接口定义-API中，json格式请求体，打开json-schema开关，添加描述并保存；
2.关掉json-schema开关，并重新打开，之前保存的描述内容丢失；

### 期待的正确结果

重复打开json-schema开关，不丢失保存的内容

### 附加信息

<img width="860" alt="image" src="https://github.com/metersphere/metersphere/assets/89773363/0ce59002-d6fc-4f72-a6b3-a186e4322f89">

**Comment by youliyuan-fit2cloud** [comment]
你好，经开发同事最后确认，JSON 和 JSON Schema 本身是两种格式，JSON只是 k,v； Schema属于自定义格式相互转后只能保留基础 k，v 了，目前我们还没有解决方案，暂时不解决，感谢理解和支持。
