### ISSUE TITLE
[BUG]当协议是https时，环境变量中配置证书，接口概率性报错误：Non HTTP response code: javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by Wiweny** [metersphere/metersphere#30957]
### MeterSphere 版本

 v2.10.13-lts-163a8232

### 使用外置数据库

否

### 问题描述

https协议
对应的个别接口需要ssl证书鉴权
调用其他接口时，概率性报Non HTTP response code: javax.net.ssl.SSLException
在配置证书的情况下，一直调用不了接口

### 重现步骤

https协议
对应的个别接口需要ssl证书鉴权
调用其他接口时，概率性报Non HTTP response code: javax.net.ssl.SSLException
在配置证书的情况下，一直调用不了接口

### 期待的正确结果

需要鉴权的接口，进行鉴权，不需要鉴权的接口，不鉴权，连接稳定

### 附加信息

<img width="557" alt="微信图片_20240520183741" src="https://github.com/metersphere/metersphere/assets/170320766/5dce0afd-5164-484d-b9ff-b744f65ce039">
<img width="589" alt="微信图片_20240520183754" src="https://github.com/metersphere/metersphere/assets/170320766/29f25af3-1f52-4b3b-a57a-4cd3d684d0d6">
<img width="524" alt="微信图片_20240520183814" src="https://github.com/metersphere/metersphere/assets/170320766/a092b60c-7869-464c-8f84-68bea168031b">
<img width="830" alt="微信图片_20240520183804" src="https://github.com/metersphere/metersphere/assets/170320766/9ed1d4be-ce0e-46c4-b9b8-124bd4626f39">

**Comment by Wiweny** [comment]
接口调试时，问题毕现

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复下。

**Comment by 13290445582** [comment]
您好，研发反馈未复现，建议您自行检查下证书，感谢理解与支持。
