### ISSUE TITLE
[BUG]接口自动化，用“推荐jsonpath断言”功能，当选择的字段参数带有“/”时，系统自动会变成“\/”

### ISSUE THREAD

**Issue by shenxingqi** [metersphere/metersphere#30961]
### 联系方式

867296882@qq.com

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

[BUG]接口自动化，用“推荐jsonpath断言”功能，当选择的字段参数带有“/”时，系统自动会变成“\/”

### 重现步骤

<img width="1385" alt="image" src="https://github.com/metersphere/metersphere/assets/32626470/6be695f9-ba04-4723-b1d5-ec5b55cb8e84">
<img width="578" alt="image" src="https://github.com/metersphere/metersphere/assets/32626470/0018bdc6-8686-42dd-b040-2df1f194918a">

**Comment by fit2-zhao** [comment]
感谢反馈，推荐表达式系统默认会补充上转译符，对于有特殊字符的表达式建议根据自己实际需求调整。
