### ISSUE TITLE
[BUG] 批量执行场景，部分报告一直处于running状态

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#3096]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.9.3

**Bug 描述**
简要描述您碰到的问题
批量执行接口自动化，当某个场景里所有请求都被禁止时，会导致部分测试报告一直处于running状态；
**Bug 重现步骤**
1.  将某个场景的所有请求都设置为”禁止状态“；
2. 批量执行场景，包含上一步设置好的场景；
3. 查看报告可看到有的报告一直处于running状态

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
<img width="1440" alt="截屏2021-05-24 下午11 44 37" src="https://user-images.githubusercontent.com/34637801/119373141-ad40b400-bcea-11eb-98b7-8e7f6d96d87a.png">
<img width="1440" alt="截屏2021-05-24 下午11 45 13" src="https://user-images.githubusercontent.com/34637801/119373152-b29dfe80-bcea-11eb-8a02-9f44f3782b81.png">
<img width="1440" alt="截屏2021-05-24 下午11 45 20" src="https://user-images.githubusercontent.com/34637801/119373173-b7fb4900-bcea-11eb-97ca-fd9a97a2df5b.png">
<img width="1440" alt="截屏2021-05-24 下午11 45 30" src="https://user-images.githubusercontent.com/34637801/119373222-c5183800-bcea-11eb-9f97-ea33f43c0c60.png">

**Comment by luty2018** [comment]
1.批量执行，独立报告，全部禁用的场景状态为completed 打开报告和调试看到的结构一致，没有请求数据
2.批量执行，集合报告，包含全部禁用的场景则跳过，全部运行成功状态为success，运行失败状态为error

**Comment by xulinde** [comment]
1.10已修复
