### ISSUE TITLE
[v1.6]我是真的忍不住吐槽啊，这个新版真的太难用了，上下滑动，导出找按钮，设计的时候不知道ue是不是真的测试

### ISSUE THREAD

**Issue by zhaoxing-cyy** [metersphere/metersphere#3097]
**问题/需求描述**
[v1.6]我是真的忍不住吐槽啊，这个新版真的太难用了，上下滑动，到处按钮，设计的时候不知道ue是不是真的测试，也许真的是单纯的为了开发而开发，丝毫不考虑体验，公司还是用的你们的这个平台，真的是巨难用

**截图**
如果有截图，请附上截图.

**Comment by xianshancom** [comment]
帮助文档长期不更新
