### ISSUE TITLE
[BUG] Oracle11环境中 用例的前置SQL、后置SQL、SQL类型的接口中执行报错问题

### ISSUE THREAD

**Issue by gy0302** [metersphere/metersphere#30980]
### 联系方式

13671015112@139.com

### MeterSphere 版本

v2.10.13-lts-163a8232、v2.10.14

### 使用外置数据库

否

### 问题描述

1. 接口的sql执行，在下图 sql类型的接口中就正常能执行，在http接口的前置和后置sql中都有报错问题；（完整的复制sql在数据库客户端中也执行正常）
![image](https://github.com/metersphere/metersphere/assets/13193269/2dc8982e-f39b-474a-bd9e-cc0f4b8f71f1)
![image](https://github.com/metersphere/metersphere/assets/13193269/d1cb6707-f2ea-4cc5-9d2e-3363effbc1f4)

2.在以上两个位置中的sql，后面加上；就会报ORA-00911: invalid character
![image](https://github.com/metersphere/metersphere/assets/13193269/eb2e6375-571c-4ebe-9c20-8f47124e811c)
![image](https://github.com/metersphere/metersphere/assets/13193269/d541de21-3f10-47b8-8f99-4347da843ac1)

### 重现步骤

测试环境为oracle11，重现步骤如问题说明中的图中所示

### 期待的正确结果

oracle11g的环境中，可以在用例中正常使用前置SQL、后置SQL； 输入SQL的位置都可以支持多条语句同时执行

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by 13290445582** [comment]
ORA-00911: invalid character 是 Oracle 数据库常见的错误，如果你在 SQL 语句中使用了分号，会导致该错误。Oracle 不需要在 SQL 语句末尾使用分号。
