### ISSUE TITLE
[BUG]使用postman导出的Postman Collection v2.1 格式的 json 文件再导入时界面提示格式错误

### ISSUE THREAD

**Issue by zijia511** [metersphere/metersphere#30990]
### 联系方式

chenzijia511@163.com

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

![273ee17f6090691c7d2bc52137f2cd6](https://github.com/metersphere/metersphere/assets/123070895/ed1fdceb-717f-4339-9b4c-708b0a6d7b29)

### 重现步骤

1、通过postman将接口文档【api文件】导出成为Postman Collection v2.1 格式的 json 文件
2、进入MeterSphere上---【接口定义】界面
3、点击【更多操作】-【导入】
4、将步骤1的json文件导入

**Comment by 13290445582** [comment]
您好，根据您的步骤，未复现该情况。可以将您的原文件导出提供下，帮助复现，感谢支持。

**Comment by zijia511** [comment]
在api module这个表里把name的长度改成255即可解决
