### ISSUE TITLE
[BUG]用例名称中带（）时搜不到

### ISSUE THREAD

**Issue by yuanweihuaskhb** [metersphere/metersphere#30994]
### 联系方式

18291878104

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

用例名称中带（）时搜不到

### 重现步骤

用例中搜索”按样本查看删除不同状态的测试（待测试）“搜不到，去掉括号后可以模糊查询到所有相关”按样本查看删除不同状态的测试“的用例
![image](https://github.com/metersphere/metersphere/assets/109717634/21700240-b5b6-4b4c-b5a6-6bc7cedaa7f2)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本无法复现，建议升级一下吧。
![image](https://github.com/metersphere/metersphere/assets/54612864/f40f43bc-4b16-4d7d-8683-3ff2f345fc1a)
