### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by cxltsui** [metersphere/metersphere#31014]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

交流群57-崔崔

### 请描述您的需求或者改进建议

缺陷定时任务建议功能图形化，现在无法对同步第三方平台的定时任务进行开关控制，也无法查看任务执行情况，无法修改定时任务执行时间

**Comment by luty2018** [comment]
在v3版本中有放开配置， 可以关注后续版本。
