### ISSUE TITLE
[BUG]  人员a 做性能测试，产生的性能测试报告，管理员把人员a 删除，同一个项目下查看报告，提示报告不存在

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31040]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

人员a 做性能测试，产生的性能测试报告，

管理员把人员a 账号删除，进入原来的项目下查看报告，提示报告不存在

### 重现步骤

人员a 做性能测试，产生的性能测试报告，

问题：管理员把人员a 账号删除，进入原来的项目下查看报告，提示报告不存在

检查数据库字段，userid可以展示出来

![ae35da46014349df4507c2940ed0ee0](https://github.com/metersphere/metersphere/assets/43202800/9fb94600-2869-44fb-ac05-8c22a508eb63)

录制文件：https://meeting.tencent.com/crm/NbZnYk5Ne3

### 期待的正确结果

报告正常展示

**Comment by youliyuan-fit2cloud** [comment]
计划下个月的版本中修复。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
