### ISSUE TITLE
[FEATURE]  性能测试报告-测试详情，希望把响应，写成响应时间。更直观写

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31041]
### MeterSphere 版本

2.10.13

### 请描述您的需求或者改进建议

E]  性能测试报告-测试详情，希望把响应，写成响应时间。更直观写
![image](https://github.com/metersphere/metersphere/assets/43202800/e44e8c60-9174-4596-9783-d5c4206eb1fe)

**Comment by luty2018** [comment]
你这个图看不清，麻烦重新贴图

**Comment by xhy12** [comment]
<img width="982" alt="4e8a4eb4291c984bbb607f581161947" src="https://github.com/metersphere/metersphere/assets/43202800/e975dde6-a905-41bf-b1f9-12977510f254">

**Comment by luty2018** [comment]
在下个小版本优化。

**Comment by 13290445582** [comment]
<img width="488" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/7930c17d-2946-4e31-b89b-7d9b223bae88">
您好，最终确定实现效果，该问题已修复，请升级至v2.10.16版本使用。
