### ISSUE TITLE
[测试跟踪-功能用例] macbook 用edge 浏览器访问，功能用例排序功能不显示，无法拖动

### ISSUE THREAD

**Issue by xiaohouzi2466** [metersphere/metersphere#31053]
### 联系方式

18909479317

### MeterSphere 版本

V2.10.14-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/122156922/40bd9350-ba3f-4be7-a87b-895255c7b2a4)

### 重现步骤

点击查看功能用例，功能用例不显示拖拽

**Comment by xiaohouzi2466** [comment]
edge 版本：
![image](https://github.com/metersphere/metersphere/assets/122156922/0dacfddf-1394-4cb6-bda3-1b07d57a283d)

**Comment by liuruibin** [comment]
<img width="983" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/b88e3c8c-7e4b-4a61-a075-fa3ca6e392e0">
<img width="242" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/4fa223b6-de0a-4597-9d4d-b046bf03915d">
