### ISSUE TITLE
[BUG] 接口自动化测试，导入用例时，当用例较多时，报错    Connection prematurely closed BEFORE response  

### ISSUE THREAD

**Issue by mingliang1859** [metersphere/metersphere#31070]
### 联系方式

1594768701@qq.com

### MeterSphere 版本

2.10.4

### 使用外置数据库

否

### 问题描述

[BUG] 接口自动化测试，导入用例时，当用例较多时，报错    Connection prematurely closed BEFORE response  

### 重现步骤

[BUG] 接口自动化测试，导入用例时，当用例较多时，报错    Connection prematurely closed BEFORE response

**Comment by youliyuan-fit2cloud** [comment]
你好，
这种情况建议增加 接口测试模块的内存限制，即修改 docker-compose-api-test.yml 文件中mem_limit

**Comment by mingliang1859** [comment]
你好
已经设置了3GB，并重启了整个服务，还是报同样的错误
![image](https://github.com/metersphere/metersphere/assets/84176890/c26c2859-45d6-485d-95f1-ce0bb16b561b)

**Comment by youliyuan-fit2cloud** [comment]
> Author
docker stats 查看下是否生效，未生效执行如下命令
msctl reload

**Comment by mingliang1859** [comment]
查看后未生效，可以直接命令行修改 sudo docker update --memory="3g" --memory-swap="3g" api-test，修改之后保存可以，就是接口慢了点
![b3b385870eaa303a4e05cfdd7d4e9ee8](https://github.com/metersphere/metersphere/assets/84176890/afba79aa-c350-4267-bf40-2b4db9300300)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，导入的数据较多确实会慢一点～
