### ISSUE TITLE
[FEATURE]一点小建议

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#31080]
### MeterSphere 版本

v2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

1.在输入框，按住鼠标左键，多选中文字，ms会识别为你要拖拽输入框
2.场景测试里，点击保存，会自动刷新页面，且接口返回值会消失，保存是写场景使用最多的功能了
3.场景测试里，点击保存，会对body参数进行自动格式化，是否可以改成手动格式化
4.断言判断里，是否可以将失败的断言排在最上面显示
5.场景测试和接口case，请求后，返回栏是否可以默认展开，每次要点击一下才能看到返回接口

**Comment by fit2-zhao** [comment]
感谢建议，1，2，5 在 v2 最新版本中已经优化过，升级就可以；3，4 已经规划在v3版本中处理。
