### ISSUE TITLE
[FEATURE]希望能通过curl的方式，在场景那边能直接导入。导入的时候能自动关联到接口定义

### ISSUE THREAD

**Issue by liaolongfei** [metersphere/metersphere#31095]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 请描述您的需求或者改进建议

希望能通过curl的方式，在场景那边能直接导入。导入的时候能自动关联到接口定义。因为curl的话可以很方便从浏览器那边复制过来，一粘贴就能新增一个步骤，会很方便
![image](https://github.com/metersphere/metersphere/assets/6407371/7a261a61-db7e-44d8-a119-d25816bebaf5)

**Comment by luty2018** [comment]
v3版本定义支持curl导入，场景在后续版本也会支持
