### ISSUE TITLE
[FEATURE]mock参数的内容没有提示可以传入参数

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#311]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/12756697/91702802-d5f8aa80-ebab-11ea-956f-d2e09ece0108.png)

**请描述你建议的实现方案**
mock参数的内容没有提示可以传入参数，应提示可以传入参数，如@integer(60,100)

**Comment by zyyfit** [comment]
query参数已支持mock参数并有相关提示
