### ISSUE TITLE
[QUESTION] 本地启动依赖缺失-版本3-x

### ISSUE THREAD

**Issue by yangrm-tester** [metersphere/metersphere#31107]
### 请描述您的问题

缺失以来 metersphere-jmeter-functions:jar:3.0  metersphere-jmeter-assertions:jar:1.0.2  io.metersphere:dingtalk:jar:2.0.77   辛苦帮忙看看怎么下载这个依赖

**Comment by liuruibin** [comment]
这些jar上传到了我们nexus，是公开的。你检查pom是不是改了默认的配置

**Comment by yangrm-tester** [comment]
意思我本地maven的加载仓库要换成你们的仓库地址吗？
