### ISSUE TITLE
[BUG]性能测试，测试报告问题

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#31108]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

性能测试，在使用的资源池关闭后置监听器后，使用该资源池进行压力测试，如果发生错误请求，在错误记录里面没有查看到，需要退出报告后，再次进入才可以查看。

### 重现步骤

1、打开测试资源池后置监听器。
2、使用该资源池进行压力测试并发生报错
3、进入该测试报告，打开错误记录（偶现），发现错误记录空白

### 期待的正确结果

可以实时正常返回错误记录

**Comment by 13290445582** [comment]
您好，本地测试打开/关闭后置监听器均未复现该问题，建议先将测试环境与资源池升级至最新版本，后续有稳定复现步骤时可以再次反馈，感谢理解与支持。
