### ISSUE TITLE
[BUG]接口自动化，高级搜索列表后，切换页面，再回到列表页，会刷新页面

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31100]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

接口自动化，高级搜索列表后，切换页面，再回到列表页，会刷新页面

### 重现步骤

在接口自动化模块，高级搜索列表后，切换页面，再回到列表页，会刷新页面

### 期待的正确结果

在接口自动化模块，高级搜索列表后，切换页面，再回到列表页，展示之前的搜索结果

### 附加信息

https://github.com/metersphere/metersphere/assets/145318182/aa0b7775-3a7a-465a-9519-0fb8e8406d14

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在v2.10.16-lts版本修复这个问题。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
