### ISSUE TITLE
[QUESTION]Excel用例导入，代码怎么请求接口成功

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#31102]
### 请描述您的问题

我通过代码上传Excel用例文件，接口请求有两个参数如图一个是实际上传的文件，一个是request参数，文件名为“blob”
不知道怎么构造参数才能上传文件成功，下面是我的代码，请求200，但是文件没有上传上
代码片段如下：request_data = {
    'filename': 'blob'
}

# 上传请求
upload_url = 'https://metersphere.innosnap.com/track/test/case/import'
headers = {
    'Content-Type': 'multipart/form-data',
    'Accept': 'application/json',
    'CSRF-TOKEN': csrfToken,
    'X-AUTH-TOKEN': sessionId
}
response = session.post(upload_url, files=files, data={'request': json.dumps(request_data)}, headers=headers)
![20240524171327](https://github.com/metersphere/metersphere/assets/50876029/01faa88e-cefb-4b90-9ddd-83bbd6d226c8)

**Comment by luty2018** [comment]
您可以查看我们的api文档

**Comment by hujirong521317** [comment]
我看了你们的api文档，找不到这个接口
