### ISSUE TITLE
[FEATURE] 消息通知 -缺陷管理， 期望可以展示  local 模板缺陷状态字段——目前。staus platformstatus 均不行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31109]
### MeterSphere 版本

2.10.13

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/43202800/d466c80e-739f-486a-b529-894944bd891c)
![Uploading image.png…]()
消息通知 -缺陷管理， 期望可以展示  local 模板缺陷状态字段——目前。staus platformstatus 均不行

### 请描述你建议的实现方案

可以展示 缺陷列表字段

**Comment by xhy12** [comment]
![image](https://github.com/metersphere/metersphere/assets/43202800/668b7944-ad90-48ef-800b-4e0c776fd42c)

**Comment by luty2018** [comment]
第三方模板字段的问题整理到tapd统一和莹莹对接吧

**Comment by xhy12** [comment]
这个是 local 模板，ms自带的，不是三方模板 @luty2018
