### ISSUE TITLE
[FEATURE] 建议左上角的项目名称下拉框加长，目前大部分项目名称都显示不全，查询时看不全。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31113]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/44999044/18bd49bc-b10c-4be6-b34e-07e747050d15)

![image](https://github.com/metersphere/metersphere/assets/44999044/a99a38aa-93c2-48f9-ac28-4a8fc68cebd7)

### 请描述你建议的实现方案

加长显示区域，加长查询区域。

### 附加信息

目前大部分项目名在16字左右。

**Comment by luty2018** [comment]
感谢建议， 我们会在后续版本中优化。
