### ISSUE TITLE
[BUG]  企业版的jmeter镜像里面，请 加一个“查看结果树”的开关

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31120]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

背景：有个企业客户压测，测试脚本中有js css 请求导致data-streaming  oom ,没目前处理方法是 押司 打了个镜像把查看结果树关闭后正常
https://wiki.fit2cloud.com/pages/viewpage.action?pageId=148242884

期望：企业版的jmeter镜像里面，请 加一个“查看结果树”的开关

### 重现步骤

![0ba76562cabf76275d88e5d28bad203](https://github.com/metersphere/metersphere/assets/43202800/c3928f9f-c1a6-496e-8eac-8104fcca1ad8)

**Comment by liuruibin** [comment]
企业版我们提供了每个label3个采样，不会保留所有的结果。
