### ISSUE TITLE
[BUG]    接口测试放置为变量的值，接下来的测试使用变量异常

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#31124]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

接口测试放置为变量的值，接下来的测试使用变量异常

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/103925124/de9c5615-d25c-4e35-b8df-226a0fbea3e1)
![image](https://github.com/metersphere/metersphere/assets/103925124/3901ef39-5767-42fc-b228-821fbf89507f)
![image](https://github.com/metersphere/metersphere/assets/103925124/72f3cf8a-ac9e-4de3-bc06-f7b1f1d801f9)

### 期待的正确结果

使用场景背景：同样的接口提取出了的变量值不一样，放置为新变量后，用于接下来得接口测试

jmeter验证结果和metersphere一致，希望此缺陷被修改

**Comment by fit2-zhao** [comment]
应该是你某一步使用有问题，我理解你的步骤正确使用应该是：
![image](https://github.com/metersphere/metersphere/assets/70558837/5f6558aa-485f-42bf-abe9-b4d3592e4ef1)


按照上述使用流程都可以正常取值。

**Comment by fit2cloud-yaochunrong** [comment]
步骤和你一样的了，我这边取值失败的原因是重新起变量名的时候使用了name_1，name_2

**Comment by fit2-zhao** [comment]
name_index 这种命名方式可能和上下文变量冲突，换一个名字试试。

**Comment by fit2cloud-yaochunrong** [comment]
嗯，换一个好了
