### ISSUE TITLE
[FEATURE]步骤描述中是否能像文本描述一样支持富文本

### ISSUE THREAD

**Issue by zhangyanxs** [metersphere/metersphere#31168]
### MeterSphere 版本

v2.10.6-lts

### 联系方式

1130057248@qq.com

### 请描述您的需求或者改进建议

场景1：
由其他测试平台迁移用例至metersphere，想依然沿用步骤描述，但是之前的步骤中存在超链接/链接，在metersphere上无法点击跳转，步骤描述不支持富文本
场景2：
新增测试用例，想使用步骤描述风格，但是步骤中需要跳转至知识平台查看命令或者跳转至其他模板用例

### 请描述你建议的实现方案

步骤描述中支持富文本

**Comment by luty2018** [comment]
感谢建议， 这个我们可以优化。

**Comment by luty2018** [comment]
如果是新项目投入使用， 过几天我们会发布全新的v3.0Beta版本， 你可以先下载使用，后续直接在新版本上面开展工作。
