### ISSUE TITLE
[FEATURE]希望能做一个模板用例的功能

### ISSUE THREAD

**Issue by zhangyanxs** [metersphere/metersphere#31167]
### MeterSphere 版本

v2.10.13-lts

### 联系方式

1130057248@qq.com

### 请描述您的需求或者改进建议

在实际编写前端测试用例的过程中，会有很多相同的测试方法（测试步骤）例如对于列表的测试、对于输入框的测试

### 请描述你建议的实现方案

是否能做一个全局用例模板的功能
实现功能：
1、全局都能引用此模板用例
2、模板用例支持修改，支持不同版本与适配不同的产品（每个项目内也支持创建模板用例）

下图是在testlink中的实现
![图片](https://github.com/metersphere/metersphere/assets/52528415/77dd5eef-6581-4474-9e78-d1e4187d1e20)

**Comment by luty2018** [comment]
我们在v3版本中支持了组织模板和项目模板， 可以覆盖你的需求，可以月底下载v3beta版本先试用

**Comment by zhangyanxs** [comment]
这个功能是付费功能吗

**Comment by luty2018** [comment]
> 这个功能是付费功能吗

开源的

**Comment by zhangyanxs** [comment]
好的，那我等beta版本上线后，体验一下

**Comment by zhangyanxs** [comment]
我部署了v3，在组织模版和项目模板，没有发现能操作的模板呢，也没办法新建模板，模板中不支持创建步骤，能满分介绍一下新的模板功能吗

**Comment by luty2018** [comment]
> 我部署了v3，在组织模版和项目模板，没有发现能操作的模板呢，也没办法新建模板，模板中不支持创建步骤，能满分介绍一下新的模板功能吗
目前beta版本中缺陷支持创建多套模板
<img width="1275" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/d4c39905-719c-444a-b2ac-356d272d3008">
用例只有一个默认模板（暂时），但是支持编辑
<img width="1231" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/2bb85dc1-0265-4e4c-a6dd-756e9a5583ec">
系统默认是组织模板， 启用项目模板后，在项目模块下会显示模板菜单
<img width="986" alt="image" src="https://github.com/metersphere/metersphere/assets/36292514/3c006899-e2c9-495a-bd46-4649bfca278a">
