### ISSUE TITLE
[FEATURE]接口自动化json参数自行引用

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3116]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/40912823/119462197-09e7b180-bd73-11eb-99fe-e5ccc7da7d2a.png)
json模型建立array时会自动带出子项items，导致无法整个子项参数化，我的整个子项是一个变量，建议创建array是不要自动创建子项items，这样就可以直接将参数填在value处，
object时value无法填写，可以放开写操作，也能进行参数的引用

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化
