### ISSUE TITLE
[BUG]项目关联jira 平台并同步缺陷后，取消关联，删除缺陷，将jira 缺陷也被删除

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31171]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

项目关联jira 平台并同步缺陷后，取消项目关联，删除MS缺陷，发现jira 缺陷也被删除

### 重现步骤

1.新建项目关联jira 平台，同步缺陷成功。
2. 更改项目设置，集成第三方平台为local
3. 在缺陷管理，选择之前同步的缺陷进行删除操作
4. MS 平台提示删除成功，查看jira 那边缺陷同样也被删除

### 期待的正确结果

项目与jira取消关联后，在MS 平台删除缺陷成功，不影响jira 缺陷，以便于，后续MS 项目与其他jira 项目关联，同步缺陷

### 附加信息

![企业微信截图_9e0c7f43-8b93-439e-868f-f4da607c29a1](https://github.com/metersphere/metersphere/assets/145318182/a8c54cfd-ff64-4570-9216-83db41b4a866)
![企业微信截图_695be4c8-847c-47cc-afd4-578625358c34
![企业微信截图_36d7ab8b-5793-462c-a198-77e4ec433f1b](https://github.com/metersphere/metersphere/assets/145318182/26abe5f8-3821-4260-96d0-f46a6df913ba)
](https://github.com/metersphere/metersphere/assets/145318182/decf5187-5ae3-4010-a601-7de941d9bc02)

**Comment by fit2cloud-lijiaxin** [comment]
![企业微信截图_36d7ab8b-5793-462c-a198-77e4ec433f1b](https://github.com/metersphere/metersphere/assets/145318182/55b20ef8-9d9a-41b8-b2a1-f20d8e1d516a)

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/2540c82c-17ba-4528-ae5e-e64e23c982cb)

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/690dfb6e-5dca-4721-ac58-dc2b87527c7b)

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/68a5b175-5956-45bf-ac5c-c7b379ed5278)

**Comment by youliyuan-fit2cloud** [comment]
你好，该删除逻辑是这样的。如果觉得不合理，有其他建议提个需求吧。

**Comment by fit2cloud-lijiaxin** [comment]
好的

**Comment by fit2cloud-lijiaxin** [comment]
MS项目和jira取消关联后，逻辑上可以理解为两个平台项目的缺陷已断开 同步功能，缺陷管理页面也没有【同步缺陷】按钮，在MS项目删除缺陷后，不应该同步删除jira缺陷

**Comment by fit2cloud-lijiaxin** [comment]
如果有的业务一分为二，一方同步缺陷后取消关联jira项目，删除部分缺陷，按照目前的逻辑，将会影响jira ，以及与jira关联的其他MS项目的缺陷
