### ISSUE TITLE
[BUG]接口引用变量时未带双引号格式校验报错

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3117]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
json中body引用未带双引号提示格式错误，但实际是可以这样进行引用的，很多变量的引用是不要双引号的

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应该在引用未加双引号时不提示格式错误
**截图**
![image](https://user-images.githubusercontent.com/40912823/119463554-744d2180-bd74-11eb-8d7c-68bc69fa957c.png)

**Comment by zyyfit** [comment]
您好，目前格式化校验是这样的，但是不影响使用
