### ISSUE TITLE
[BUG] 浏览器间隔较长时间打开ms平台时，打不开循环闪烁，见视频附件。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31189]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

https://github.com/metersphere/metersphere/assets/44999044/dc4130fb-891a-4e51-971c-15cb38b39608

### 重现步骤

1. 首先打开浏览器，正常登录ms平台
2. 关闭ms的标签页
3. 保持浏览器不要关闭
4. 等待较长时间（2-3小时？）
5. 再次在浏览器打开ms的主页，此时url无限闪烁。

**Comment by LukaDoncic-Magic** [comment]
您好，根据您提供的步骤，在最新环境未复现该问题，请您升级到最新版本，感谢理解
