### ISSUE TITLE
[BUG] 脑图编辑用例；脑图下 存在的用户，互相修改用例名称，会提示用例已存在

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31185]
### MeterSphere 版本

2.10.13

### 使用外置数据库

否

### 问题描述

脑图编辑用例；脑图下 存在的用户，互相修改用例名称，会提示用例已存在

### 重现步骤

脑图编辑用例；脑图下 存在的用户，互相修改用例名称，会提示用例已存在
ru如图：新建用例的如图，保存，然后重新进入脑图，交互修改用例名称。
![8effb75eebc24afbc58bb04c669edb2](https://github.com/metersphere/metersphere/assets/43202800/33a5bc0c-a310-4cef-81a0-2ecc89842d19)

### 期待的正确结果

没有重复，应该可以保存

**Comment by LukaDoncic-Magic** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
