### ISSUE TITLE
[BUG]MS与禅道集成后，从禅道提交缺陷，缺陷内容中带图片，提交后同步到MS后 缺陷中图片无法正常显示

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#31193]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.14lts

### 使用外置数据库

否

### 问题描述

MS与禅道集成后同步时，从禅道提交缺陷，缺陷内容中带图片，提交后同步到MS后缺陷中图片无法正常显示。MS禅道插件是最新的2.10.10，禅道版本18.10。但是从MS提交的包含图片内容的缺陷，同步到禅道是可以正常显示的。
![3adb9a82eec4a70d0461e9920f50024](https://github.com/metersphere/metersphere/assets/83771182/66367282-70a5-48c4-ad7b-2c79f3c727e3)

### 重现步骤

MS与禅道集成后同步时，从禅道提交缺陷，缺陷内容中带图片，提交后同步到MS后缺陷中图片无法正常显示。

### 期待的正确结果

MS与禅道集成后同步时，从禅道提交缺陷，缺陷内容中带图片，提交后同步到MS后缺陷中图片能正常显示。

### 相关日志输出

```shell
日志见附件
```

### 附加信息

[info (system-seting).log](https://github.com/metersphere/metersphere/files/15493211/info.system-seting.log)
[info（test-track）.log](https://github.com/metersphere/metersphere/files/15493213/info.test-track.log)

**Comment by 13290445582** [comment]
您好，低版本支持双向图片同步，18.10不支持禅道直接上传图片同步至MS，图片链接可以同步过来。

**Comment by 13290445582** [comment]
您好，高版本禅道在图片预览这里做了处理， 通过Http链接已经无法访问了，这里就不支持高版本图片同步至MS了， V2的插件就支持我们原本的V12.5.3及之前版本就行。
