### ISSUE TITLE
[BUG]接口自动化中单步骤调试循环控制器，不显示循环结果

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31192]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

接口自动化中单步骤调试循环控制器，不显示循环结果

### 重现步骤

1.新建接口场景，添加场景列表1,2,3
2. 添加循环控制器及自定义脚本打印，使用foreach 循环控制器，遍历list，
3. 使用单步骤调试循环控制器，显示success ，但是没有遍历结果。
![image](https://github.com/metersphere/metersphere/assets/145318182/9420cd1b-5b8b-4a51-8400-31aa90c7175e)
4. 使用场景调试，可以正常看到循环结果
![image](https://github.com/metersphere/metersphere/assets/145318182/42cada3f-fd57-4762-b649-9e6c6c69c91e)

### 期待的正确结果

步骤三操作，可以正常看到循环结果

**Comment by fit2cloud-lijiaxin** [comment]
如果因为场景变量的问题，循环失败，是否可以给个提示

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
你好，这个改动影响范围比较大，不再处理了，感谢理解与支持。
