### ISSUE TITLE
[BUG]  测试计划-测试用例执行，添加评论上传图片，有的图片可以展示，有的图片不能展示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31198]
### MeterSphere 版本

2.10.14

### 使用外置数据库

否

### 问题描述

测试计划-测试用例执行，添加评论上传图片，有的图片可以展示，有的图片不能展示

### 重现步骤

测试计划-测试用例执行，添加评论上传图片，有的图片可以展示，有的图片不能展示

![Uploading a8c8844c5da8c0582536eaaf3e66e99.png…]()
![Uploading 338935432e369ade654c8325ce8a61e.png…]()

### 期待的正确结果

展示图片

**Comment by 13290445582** [comment]
您好，有复现一种情况，同一条用例上传多张图片，第二张图片上传成功时，第一张图片无法显示。请问您还有其他复现情况嘛，请补充。

**Comment by xhy12** [comment]
我是执行多条用例并评论上传图片保存后 再进入测试用例看的， 有的可以展示有的不能，不太规律。但比较容易复现

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级至v2.10.16版本使用。
