### ISSUE TITLE
[QUESTION]离线安装部署完成之后，服务器里只展示了一个UI测试，之前的接口测试菜单

### ISSUE THREAD

**Issue by zhouchengzhi1** [metersphere/metersphere#31195]
### 请描述您的问题

![image](https://github.com/metersphere/metersphere/assets/96609594/55667c67-3327-4889-a39c-6401ae8fdaa5)

安装完成后可以正常访问，但访问展示的菜单只有一个UI测试

**Comment by liuruibin** [comment]
后台有日志输出吗

**Comment by zhouchengzhi1** [comment]
重新装了一遍，现在前台无法访问 gateway、system-setting及其相关服务 起不来，system-setting的报错信息如下

![image](https://github.com/metersphere/metersphere/assets/96609594/35b3d6a5-c6d3-436a-85d8-ea38f041999d)

**Comment by zhouchengzhi1** [comment]
修改了version92的sql，reload之后，还是setting下的几个服务启动的时候报错，但是进报错容器，没有error日志，前端打开，只展示两个菜单，其他菜单不展示
![image](https://github.com/metersphere/metersphere/assets/96609594/e27e99d1-01e8-4ca6-8c86-e2043073e918)
