### ISSUE TITLE
[BUG]项目中的自定义代码无法引用自定jar包，需要自动化测试场景调试一遍才能正常使用

### ISSUE THREAD

**Issue by weixiao12345** [metersphere/metersphere#31196]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

项目中的自定义代码无法引用自定jar包，需要自动化测试场景调试一遍才能正常使用

### 重现步骤

项目设置->文件管理上传自定义jar包并开启接口测试，项目设置->自定代码片段调用上传jar包的内容

**Comment by 13290445582** [comment]
您好，请提供下jar包和代码片段。

**Comment by weixiao12345** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]项目中的自定义代码无法引用自定jar包，需要自动化测试场景调试一遍才能正常使用 (Issue #31196)





 
您好，请提供下jar包和代码片段。

**Comment by 13290445582** [comment]
您好，未收到您的信息，您可以做个压缩包发送到我的邮箱。

**Comment by weixiao12345** [comment]
附近内容收不到吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月30日(周四) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]项目中的自定义代码无法引用自定jar包，需要自动化测试场景调试一遍才能正常使用 (Issue #31196)




 
您好，未收到您的信息，您可以做个压缩包发送到我的邮箱。

**Comment by 13290445582** [comment]
没收到，看不到内容。

**Comment by weixiao12345** [comment]
脚本跟jar包都在附件里



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月30日(周四) 晚上6:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]项目中的自定义代码无法引用自定jar包，需要自动化测试场景调试一遍才能正常使用 (Issue #31196)




 
您好，未收到您的信息，您可以做个压缩包发送到我的邮箱。

**Comment by 13290445582** [comment]
方便添加下企业微信吗，还是不显示附件。
<img width="714" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/460059ff-4aa7-44ed-8c87-8667b8b7dc0d">

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
