### ISSUE TITLE
[BUG]无法通过删去https改变请求类型，必须输入http才行

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#312]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/91703076-3c7dc880-ebac-11ea-8159-234186ec2632.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们这里是这么处理的，对于不带协议的地址默认按 https 来处理
