### ISSUE TITLE
跟2.0相比，3.0的变更记录，无法查看变更明细了么？

### ISSUE THREAD

**Issue by chenyiming04** [metersphere/metersphere#31205]
### 请描述您的问题

3.0：
![image](https://github.com/metersphere/metersphere/assets/26685669/5ca5e18a-7040-4f9e-8c29-6c8a2d81d283)
2.0：
![image](https://github.com/metersphere/metersphere/assets/26685669/489d03a5-7f38-49ac-9ac2-488bf1ddaf2a)

跟2.0相比，3.0的变更记录，无法查看变更明细了么？

**Comment by youliyuan-fit2cloud** [comment]
你好，当前版本还没来得及做这块，后续版本会有的。

**Comment by chenyiming04** [comment]
3.0 用例导出成 excel 和 xmind 案例导入也不再支持了么？

**Comment by luty2018** [comment]
> 3.0 用例导出成 excel 和 xmind 案例导入也不再支持了么？

会支持的，依然是每月发布一个版本来迭代。
