### ISSUE TITLE
[BUG]【UI测试】设置场景变量后，在场景步骤名称处 引用变量，运行后场景步骤名称变量不生效。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31218]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

【UI测试】设置场景变量后，在场景步骤名称处 引用变量，运行后场景步骤名称变量不生效。

### 重现步骤

【UI测试】设置场景变量后，在场景步骤名称处 引用变量，运行后场景步骤名称变量不生效。
![image](https://github.com/metersphere/metersphere/assets/104960608/b30ccdee-2669-4160-b0e4-1be794d1c940)
![image](https://github.com/metersphere/metersphere/assets/104960608/a3524c2c-9bbc-47cd-9f33-9176727b3089)
![image](https://github.com/metersphere/metersphere/assets/104960608/3d0b285a-4f5e-456d-81b7-dacf72ac888c)

**Comment by 13290445582** [comment]
感谢反馈，计划在V3正式版发布后，再修复该问题。

**Comment by 13290445582** [comment]
您好，经过反馈，非问题，设计如此，步骤名称不支持变量的使用。若您有需要，请提需求，感谢支持。
