### ISSUE TITLE
[BUG]测试计划有等待控制器的场景步骤超时

### ISSUE THREAD

**Issue by karhow** [metersphere/metersphere#31213]
### MeterSphere 版本

2.1.1

### 使用外置数据库

是

### 问题描述

测试计划中，第一个场景用例使用了等待控制器，等待1000s，然后第一个步骤过就超时了，且下面的场景步骤正常运行，按照下面的场景的开始时间推算，是超过了2分钟超时？

### 重现步骤

![image](https://github.com/metersphere/metersphere/assets/32405381/6b5648f5-fb84-439e-9667-d94d78cedf3e)
![image](https://github.com/metersphere/metersphere/assets/32405381/12cbcc91-86ef-49d0-a45f-e6f3ba99aef7)

### 期待的正确结果

等待控制器的场景步骤正常运行

**Comment by 13290445582** [comment]
您好，在最新版本未复现该问题，您可以将出问题的场景导出提供下，看您的版本较低，建议升级至最新版本使用，最新版本上未发现该问题。

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
