### ISSUE TITLE
[BUG]引用其他项目的用例，在选择变量的时候 要求选择当前项目及引用项目的环境配置，还是必选

### ISSUE THREAD

**Issue by nakaDH** [metersphere/metersphere#31227]
### 联系方式

1512751410@qq.com

### MeterSphere 版本

 v2.10.8-lts-313def9d

### 使用外置数据库

是

### 问题描述

# 引用其他项目的用例，在选择变量的时候 要求选择当前项目及引用项目的环境配置，还是必选

## 存在两个项目A,B，也有对应的环境配置 Env_A，Env_B
![image](https://github.com/metersphere/metersphere/assets/42402315/fb52bdbd-6f30-4d45-9e0f-d20f73d69b10)

项目B的接口场景从项目A复制到项目B，在执行的时候要求我选择两个项目的环境，必填，而我不需要选择Env_A

### 期待的正确结果

希望只可以选择当前项目的环境变量。或者是可以优先执行当前项目的环境变量

### 相关日志输出

```shell
1
```

### 附加信息

1

**Comment by nakaDH** [comment]
![image](https://github.com/metersphere/metersphere/assets/42402315/f1037ac2-5f09-4383-b996-184d83786236)


已经选择一个环境变量，提示错误

**Comment by 13290445582** [comment]
您好，接口场景处关于环境的选择，在最新版本上已经是优化过的，您可以升级最新版使用。测试计划批量编辑环境问题已复现，后续版本优化。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级至v2.10.16版本使用。
