### ISSUE TITLE
[BUG] 当响应体过大时，使用正则断言后，该接口无法调试，一直转圈。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31232]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

前提条件：
1. access_tk是之前的步骤提取 的变量。
2. 被断言的接口返回值特别大，本例中返回值大小为：249295bytes，响应体请见附件。
[响应体.json](https://github.com/user-attachments/files/15521122/default.json)

![image](https://github.com/metersphere/metersphere/assets/44999044/a89450ab-3433-49cf-a2c5-b5e83faf886d)

如下图中，配置断言规则时，这个接口调试一直转圈。
![image](https://github.com/metersphere/metersphere/assets/44999044/eb4b986e-ec5b-401f-ac7f-992bf6746c02)

![image](https://github.com/metersphere/metersphere/assets/44999044/f0e3f0b5-cc71-413c-a6b5-599a455127dc)

### 重现步骤

如问题描述。

### 期待的正确结果

能够正常调试成功！

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，这个是因为生成的正则表达式有误，导致死循环了，建议修改正则表达式，增加转译符号，这个推荐生成的并不是就是正确的，只是提供一个大概思路，正则表达式多种多样，并不可能直接生成的就是可用的，如果包含特殊符号需要转译。
