### ISSUE TITLE
[BUG] 接口自动化中，导入其他场景B时，B场景的场景变量没有带过来，建议给个提示问用户是否带过来。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31231]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/44999044/aacdc80b-3860-4e14-a9cd-f8358d974f72)

![image](https://github.com/metersphere/metersphere/assets/44999044/be8fb4c9-fdb4-4041-8f1a-939da19b3bcf)

### 重现步骤

1. 创建一个有场景变量的场景B
2. 创建场景A，然后导入场景B
3. 此时A场景没有自动导入B场景的场景变量。

### 期待的正确结果

建议给用户提示选择，保留哪些场景变量。

**Comment by 13290445582** [comment]
您好，导入场景并不会将场景变量直接导入过来，您可以点击导入场景步骤的「...」按钮，查看场景变量或者设置场景变量。
<img width="1062" alt="image" src="https://github.com/metersphere/metersphere/assets/128017892/5b6c2aa7-158c-41d5-a683-acf46dbc1ab0">
