### ISSUE TITLE
[BUG]【个人信息-API文档】点击API文档，无法加载跳转的swagger页面。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31258]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

【个人信息-API文档】点击API文档，无法加载跳转的swagger页面。

### 重现步骤

【个人信息-API文档】点击API文档，无法加载跳转的swagger页面。
![1717483571384](https://github.com/metersphere/metersphere/assets/104960608/c1a83c54-2915-4a5d-8683-c637f4f8c416)
![image](https://github.com/metersphere/metersphere/assets/104960608/75e940fb-884a-43d2-9d47-75f3ff789958)

**Comment by youliyuan-fit2cloud** [comment]
经沟通确认，用户环境的自定义jar冲突，需要自己处理下。感谢理解和支持。
