### ISSUE TITLE
[BUG]新建场景-设置csv参数，选择作用域，页面崩溃

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31257]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.0.0-beta-e556dc2f

### 使用外置数据库

否

### 问题描述

接口场景，设置CSV 参数，未填写名称，直接选择作用域为步骤，页面卡主，选择退出网页后，页面崩溃

### 重现步骤

新建接口场景，设置CSV 参数，未填写名称，直接选择作用域为步骤，页面卡主，选择退出网页后，页面崩溃

### 期待的正确结果

上述情况，页面不会崩溃，可以提示，名称不能为空

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/145318182/bd84265e-9328-4437-82ca-92cdbbd2596c)

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/8030ed5c-2189-4f2e-9ec1-ccec37ee247d)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v3.0.1中已修复该文件，升级一下吧～
