### ISSUE TITLE
[BUG]批量导入的功能用例，再次编辑更新时，没有变更记录

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#31266]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

批量导入一个功能用例，导入完成后编辑改功能用例，保存退出后，查看对应的变更记录，没有变更记录
<img width="1365" alt="截屏2024-06-04 下午5 19 38" src="https://github.com/metersphere/metersphere/assets/34637801/dbc6d4f6-2b64-441f-a150-1ba3486e0ac5">

### 重现步骤

1.批量导入功能用例，导入文件如下
[Metersphere_case_J6X解决方案 (3).xlsx](https://github.com/user-attachments/files/15545834/Metersphere_case_J6X.3.xlsx)
2.导入完成后，点击“查看”-“编辑"，修改功能用例内容
3.保存修改内容
4.点击”变更内容“，无法查看到变更记录

### 期待的正确结果

能查看到对应的变更记录

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，计划后续版本修复。

**Comment by wangyynn** [comment]
> 感谢反馈，问题已复现，计划后续版本修复。

这个问题目前对们使用影响较大，可以出一个临时patch或者有其他临时规避方案吗？

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
