### ISSUE TITLE
[FEATURE]一点小建议

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#31278]
### MeterSphere 版本

2.7.1

### 请描述您的需求或者改进建议

测试计划的自动重试能否改成失败重试的模式？
1.出现失败后，整个测试用例重试
2. 测试计划跑完后，失败的测试用例重试

**Comment by luty2018** [comment]
好的， 已收到反馈，第1点在v3正式版会覆盖。

**Comment by luty2018** [comment]
已线下沟通需求
