### ISSUE TITLE
[BUG]  数据库源只有mysql了

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#31279]
### MeterSphere 版本

3.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/26613645/51df5159-d375-4c41-836e-ce8f7a72f959)

### 重现步骤

必现， 之前的版本可不是这样的

**Comment by liuruibin** [comment]
您好，我们不再内置各个驱动，您可以自行上传
<img width="1907" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/366f806e-c4bd-4b6f-b5e9-d0c1a212482d">

**Comment by Stephen0910** [comment]
数据库驱动也要自己上传嘛。。

**Comment by Stephen0910** [comment]
自己上传
pgsql: https://jdbc.postgresql.org/download/

**Comment by liuruibin** [comment]
驱动上传之后就可以正常配置了
<img width="710" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/9bbb2b8b-fae0-4023-8160-2eb8925027e5">

**Comment by Stephen0910** [comment]
嗯 可以了
