### ISSUE TITLE
[QUESTION]离线升级kafka启动失败

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#31283]
### 请描述您的问题

原版本为2.10.13，按照教程离线升级到2.10.15，kafka容器启动失败，查看docker log提示
`
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
===> User
uid=1000(appuser) gid=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
/opt/kafka/config/ file not writable
`

查看docker compose并没有连接到/opt/kafka/config/ 不知为何

以下是我的install.conf
`# 基础配置
## 安装路径, MeterSphere 配置及数据文件默认将安装在 ${MS_BASE}/metersphere 目录下
MS_BASE=/opt
## MeterSphere 使用的 docker 网络网段信息
MS_DOCKER_SUBNET=172.30.10.0/24
## 镜像前缀, MeterSphere 相关组件使用的 Docker 镜像前缀, 例如 registry.cn-qingdao.aliyuncs.com/metersphere
MS_IMAGE_PREFIX=registry.cn-qingdao.aliyuncs.com/metersphere
## 镜像标签, MeterSphere 相关组件使用的 Docker 镜像标签
MS_IMAGE_TAG=v2.10.15-lts
## 性能测试使用的 JMeter 镜像
MS_JMETER_IMAGE=${MS_IMAGE_PREFIX}/jmeter-master:5.5-ms11-jdk17
## 安装模式 allinone | server | node-controller | selenium-hub | middleware | task-runner
MS_INSTALL_MODE=allinone
## MeterSphere 主程序的 HTTP 服务监听端口
MS_SERVER_PORT=8081
## MeterSphere Node-Controller 组件的 HTTP 服务监听端口
MS_NODE_CONTROLLER_PORT=8082
MS_NODE_EXPORTER_PORT=9100

# 数据库配置
## 是否使用外部数据库
MS_EXTERNAL_MYSQL=false
## 数据库地址
MS_MYSQL_HOST=$(hostname -I|cut -d" " -f 1)
## 数据库端口
MS_MYSQL_PORT=3306
## 数据库库名
MS_MYSQL_DB=metersphere
## 数据库用户名
MS_MYSQL_USER=root
## 数据库密码
MS_MYSQL_PASSWORD=Password123@mysql

# Prometheus 配置
## 是否使用外部Prometheus
MS_EXTERNAL_PROM=false
MS_PROMETHEUS_PORT=9090

# Redis 配置
## 是否使用外部Redis
MS_EXTERNAL_REDIS=false
## Redis 端口
MS_REDIS_PORT=6379
## Redis 密码
MS_REDIS_PASSWORD=Password123@redis
## Redis地址
MS_REDIS_HOST=$(hostname -I|cut -d" " -f 1)

# Kafka 配置
## 是否使用外部 Kafka
MS_EXTERNAL_KAFKA=false
## Kafka 地址
MS_KAFKA_HOST=10.86.55.210
## Kafka 端口
MS_KAFKA_PORT=9092
## 性能测试结果数据使用的 Kafka Topic
MS_KAFKA_TOPIC=JMETER_METRICS
## 性能测试日志数据使用的 Kafka Topic
MS_KAFKA_LOG_TOPIC=JMETER_LOGS
## 性能测试定时任务通知使用的 Kafka Topic
MS_KAFKA_TEST_TOPIC=LOAD_TESTS
## 重构后性能测试结果数据使用的 Kafka Topic
MS_KAFKA_REPORT_TOPIC=JMETER_REPORTS

# TCP MOCK 端口范围
MS_TCP_MOCK_PORT=10000-10010

# UI容器配置
## 是否启动UI模块
MS_UI_ENABLED=false
## 是否使用外部grid
MS_EXTERNAL_SELENIUM=false

# minio 配置
## 是否使用外部minio
MS_EXTERNAL_MINIO=false
## minio 地址
MS_MINIO_ENDPOINT=http://minio:9000
## minio access
MS_MINIO_ACCESS_KEY=admin
## minio 密码
MS_MINIO_SECRET_KEY=Password123@minio

## docker gid
MS_DOCKER_GID=$(getent group docker | cut -f3 -d:)`

**Comment by liuruibin** [comment]
在这个版本中我们升级了kafka版本，你可以执行
```
docker stop kafka
docker rm kafka

msctl reload
```

**Comment by ijwstl** [comment]
![image](https://github.com/metersphere/metersphere/assets/71215012/a10431fc-36fa-48cb-a53d-cd572dfd97e1)
依旧失败
![image](https://github.com/metersphere/metersphere/assets/71215012/88ce56eb-7742-4ba5-9ab9-f6a62d5a4d36)

**Comment by ijwstl** [comment]
> 在这个版本中我们升级了kafka版本，你可以执行
> 
> ```
> docker stop kafka
> docker rm kafka
> 
> msctl reload
> ```

![image](https://github.com/metersphere/metersphere/assets/71215012/de62c3c7-70b0-4659-bef2-f7458b3ab1c2)
![image](https://github.com/metersphere/metersphere/assets/71215012/1a2d8c15-f65b-4a4a-a43f-dbd82c47f384)
依旧失败

**Comment by liuruibin** [comment]
docker ps 看看每个容器的状态

**Comment by ijwstl** [comment]
> docker ps 看看每个容器的状态
我目前退回了13版本，docker ps的状态大概是data-stream容器不存在，kafka为restart，其余正常，稍晚我再升级一下截图给您

**Comment by mocuishlelin** [comment]
docker rm -f kafka
docker-compose-kafka.yml 中加入 privileged: true 使用特权模式
msctl reload
就可以啦
