### ISSUE TITLE
[BUG]自动化场景中，http接口出现java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#31286]
### MeterSphere 版本

v2.10.13-lts

### 使用外置数据库

否

### 问题描述

在循环中请求一个post接口，该接口的请求体包含变量，运行时出现java.net.SocketException: Broken pipe错误，具体报错如下图
![Snipaste_2024-06-05_10-50-47](https://github.com/metersphere/metersphere/assets/71215012/d6628ba8-e6b3-4e31-8a73-4c4e6f5bf8c3)

但是将该接口的请求内容拷贝成一个自定义请求，该请求可以正常发出，不会出现该问题
ps：该请求体较大，200k+

### 重现步骤

![Snipaste_2024-06-05_10-52-18](https://github.com/metersphere/metersphere/assets/71215012/8a9d1fe9-1e8f-494c-bcab-14a45ff1ad9b)

当把循环内第二个请求内容变拷贝出来，手工包装成自定义请求时，可以正常发出

**Comment by liuruibin** [comment]
调整 server.jetty.max-http-form-post-size 参数试试

/opt/metersphere/conf/metersphere.properties

**Comment by ijwstl** [comment]
> 调整 server.jetty.max-http-form-post-size 参数试试
> 
> /opt/metersphere/conf/metersphere.properties

![image](https://github.com/metersphere/metersphere/assets/71215012/89eeac67-98e1-435f-b7a4-a4e2e71b23ca)
以尝试，不能解决，只有加大两个请求之间等待时间才行

**Comment by 13290445582** [comment]
问题方法已解决，issue关闭。
