### ISSUE TITLE
[FEATURE]  v3 导入curl无效

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#31282]
### MeterSphere 版本

3.0

### 使用外置数据库

否

### 问题描述

同样的curl 导入postman 是可以的， 但是使用导入是无效的
'''js
curl --request GET \
  --url https://www.baidu.com/
'''
![image](https://github.com/metersphere/metersphere/assets/26613645/69b664eb-247c-41af-be79-a87a22149d3e)

### 重现步骤

rt

**Comment by fit2-zhao** [comment]
感谢反馈，当前版本仅兼容浏览器上的 Copy as cURL 复制的格式，其他方式复制的 cURL内容会在后续版本逐渐完善。
