### ISSUE TITLE
[BUG]功能用例，预期结果使用文本描述，<*>内容编排混乱

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31293]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

功能用例，预期结果使用文本描述，内容乱码

### 重现步骤

如图，编辑预期结果![image](https://github.com/metersphere/metersphere/assets/145318182/3f7a441b-ab97-4fe7-a104-4d524e4bf2b6)
点击保存后，内容编排混乱
![Uploading image.png…]()

### 期待的正确结果

文本内容正常显示

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/metersphere/metersphere/assets/145318182/ad609a1b-5820-4171-a99b-6fc219539324)
编辑状态如上图所示

**Comment by 13290445582** [comment]
您好，预期结果处输入的原内容文本请提供下。

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化。

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
