### ISSUE TITLE
[BUG]接口测试，偶现，读取本地问题有时会出现读取不成功情况

### ISSUE THREAD

**Issue by Beibei1206** [metersphere/metersphere#31309]
### 联系方式

32群，贝贝

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

读取服务器指定目录文件，有时候会出现读取不成功情况

### 重现步骤

执行接口进行加解密，读取本地js脚本，执行多次，存在失败情况

文件权限已经放开，且SELINUX=disabled；api-test容器和ms-node-controller容器对应路径文件处女座

### 期待的正确结果

每次都读取成功

### 附加信息

![企业微信截图_17176413601842](https://github.com/metersphere/metersphere/assets/171893189/c903004c-80a4-4122-8d19-521105fd7e2a)

![企业微信截图_1717641566380](https://github.com/metersphere/metersphere/assets/171893189/ee545b6d-3147-44e4-a9dd-db42cd78ff78)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，方便把你这个场景发出来吗？

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
