### ISSUE TITLE
[BUG]评论裂图

### ISSUE THREAD

**Issue by cixiafeibixia** [metersphere/metersphere#31310]
### 联系方式

xyy915921533@sina.com

### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

执行测试计划，评论贴图 保存后再打开图片都显示损坏了
![image](https://github.com/metersphere/metersphere/assets/32405820/8f98036b-b1d9-4bd7-b444-87a007c2a525)

### 重现步骤

执行计划，评论中贴图保存后打开，大概率 打不开图片

**Comment by 13290445582** [comment]
您好，已知问题，相关issue关联，请关注该issue。https://github.com/metersphere/metersphere/issues/31198
