### ISSUE TITLE
[BUG]用包含 "L" 或者 “LL”查询一些测试用例字段，查询结果中包含该字段值为空的用例

### ISSUE THREAD

**Issue by wangyynn** [metersphere/metersphere#31317]
### 联系方式

拉不拉宁

### MeterSphere 版本

v2.10.15-lts-45100cee

### 使用外置数据库

否

### 问题描述

用包含 "L" 或者 “LL”查询一些测试用例字段，查询结果中包含该字段值为空的用例

### 重现步骤

1. 测试用例自定义一个扩展字段“提测版本”，不填入任何值
2. 在前台界面通过前台界面查询，“功能用例” -> “筛选” 选择 “包含”  "L" 或者 “LL”进行查询
3. “提测版本”没有值的用例也会被查出来
![bug](https://github.com/metersphere/metersphere/assets/98017620/f1c4634a-d8ea-439d-bccb-61d3c1fa6995)

### 期待的正确结果

为空的字段不应该出现在查询结果里

### 附加信息

应该是为空的字段在数据库被写成null导致

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，截图无法查看，请重新上传详细截图。

**Comment by wangyynn** [comment]
> 你好，没有复现该问题，截图无法查看，请重新上传详细截图。

已上传

**Comment by youliyuan-fit2cloud** [comment]
感谢积极反馈，问题已复现，应该是ID或名称字段也包括L 导致，后续版本会继续优化。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.22-lts 版中已修改。
