### ISSUE TITLE
[FEATURE] 3.0 接口统计信息没了

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#31324]
### MeterSphere 版本

3.0

### 请描述您的需求或者改进建议

3.0 精简咋把接口统计信息精简没了。
覆盖率， 总数之类的

**Comment by luty2018** [comment]
您好， 这些会在后续的版本中上的， v3.0依然是每月一个迭代来发布新功能。

**Comment by Stephen0910** [comment]
还是没有啊
