### ISSUE TITLE
[FEATURE] 新用户自动加到一个组，以便权限管理

### ISSUE THREAD

**Issue by donhui** [metersphere/metersphere#31320]
### MeterSphere 版本

v2.10.14

### 请描述您的需求或者改进建议

目前 metersphere 权限需要手动管理
当用户比较多时，权限管理比较麻烦
希望能够默认将新用户加个一个组
这样权限管理会很方便，事半功倍

<img width="608" alt="image" src="https://github.com/metersphere/metersphere/assets/5702065/afceac14-9f12-47fa-a8dc-cf69c97f5491">

jfrog 有类似的功能

<img width="637" alt="image" src="https://github.com/metersphere/metersphere/assets/5702065/27caec6d-0feb-48e6-8bd9-2eac3407c6a3">

jenkins 有个内置的【Authenticated Users】用户组

**Comment by liuruibin** [comment]
<img width="152" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/61ae1ad9-1114-43ae-bb34-e297a53d282a">
系统管理员可以进行批量操作

**Comment by donhui** [comment]
批量操作这个功能挺好的，能解放一部分繁琐的权限管理工作
但是批量操作的前提是用户在 metersphere 里
但是如果用户还不再 metersphere 里，或者手动导入下用户，或者让他们登陆下
如果新用户自动加到一个组，就不用考虑用户是否登陆过，是否在 metersphere 存在过，这样是不是更便捷呢
