### ISSUE TITLE
关于接口请求参数引用自定义脚本返回值的问题

### ISSUE THREAD

**Issue by wangsilei09** [metersphere/metersphere#31325]
### MeterSphere 版本

版本:   v2.10.13-lts-163a8232

### 联系方式

18033551998

### 请描述您的需求或者改进建议

这个功能很常见，建议增加~

**Comment by liuruibin** [comment]
自定义脚本并不是一个function，本身的返回值很难界定。

脚本内可以通过vars.put("k", "v")的方式将需要的值保存下来。

使用的时候可以再后续的脚本中用vars.get("k")或${k}来得到前面脚本设置的值

**Comment by wangsilei09** [comment]
3q，已了解

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月06日 17:22 |
| 收件人 | metersphere/metersphere ***@***.***> |
| 抄送人 | wangsilei09 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [metersphere/metersphere] 关于接口请求参数引用自定义脚本返回值的问题 (Issue #31325) |

自定义脚本并不是一个function，本身的返回值很难界定。

脚本内可以通过vars.put("k", "v")的方式将需要的值保存下来。

使用的时候可以再后续的脚本中用vars.get("k")或${k}来得到前面脚本设置的值
