### ISSUE TITLE
[BUG]环境中修改全局断言-文档结构断言后，保存无效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#31327]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

环境中修改全局断言-文档结构断言期望值后，保存无效

### 重现步骤

1、修改并保存
![image](https://github.com/metersphere/metersphere/assets/88763608/7e2f7a66-bdc7-4756-8334-e4dbabff0f61)
2、再打开还是未修改
![image](https://github.com/metersphere/metersphere/assets/88763608/e1b14be1-6110-4d5f-92d3-da16ee357482)

### 期待的正确结果

成功修改

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试环境无法复现，请提供必现的步骤。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
