### ISSUE TITLE
[BUG] 3.0从swagger 同步，headers 没有同步过来

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#31323]
### MeterSphere 版本

3.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/26613645/ea16134d-7959-4c41-a385-f81ac5a30b98)
![image](https://github.com/metersphere/metersphere/assets/26613645/f65b3c5d-fd1d-4144-941f-b2ecc0867255)

### 重现步骤

swagger 中有  同步过来没有

**Comment by youliyuan-fit2cloud** [comment]
你好，定时同步导入 是吗？是覆盖导入还是不覆盖？
![image](https://github.com/metersphere/metersphere/assets/54612864/306545ad-f2a6-40be-a127-6caac458f322)

**Comment by Stephen0910** [comment]
> 你好，定时同步导入 是吗？是覆盖导入还是不覆盖？
> 
> ![image](https://github.com/metersphere/metersphere/assets/54612864/306545ad-f2a6-40be-a127-6caac458f322)
> 
> 

定时和手动都试了， 覆盖

**Comment by Stephen0910** [comment]
另外， 如果content-type 为 text/plain， body 没有参数

**Comment by Stephen0910** [comment]
![image](https://github.com/metersphere/metersphere/assets/26613645/cecb8717-6588-4955-b409-bed9e0aa2bbe)
![image](https://github.com/metersphere/metersphere/assets/26613645/8af14157-8c5c-4143-be56-eb80c4194416)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没复现该问题，方便把接口文件发出来吗？

**Comment by Stephen0910** [comment]
[test.json](https://github.com/user-attachments/files/15710073/test.json)
swagger ui 的示例文件也不行啊
https://petstore.swagger.io/v2/swagger.json

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v3.0.1中已修复该文件，升级一下吧～
