### ISSUE TITLE
[BUG][BUG]使用离线安装包v3.0.0-beta安装后，各服务状态正常，登录界面后，无法使用测试用例和缺陷管理

### ISSUE THREAD

**Issue by berserkerwsc** [metersphere/metersphere#31341]
### 联系方式

微信交流群灬灬

### MeterSphere 版本

3.0.0-beta

### 使用外置数据库

否

### 问题描述

登录后，切换到测试用例和缺陷管理标签页，右边展示的仍旧是上个标签页内容

### 重现步骤

登录后，点击测试用例或者缺陷管理

### 期待的正确结果

能正常创建用例和缺陷

### 附加信息

![IMG_5529](https://github.com/metersphere/metersphere/assets/172011320/3929b8d2-6847-41a2-9bc8-9a40cbeeecf7)
![IMG_5528](https://github.com/metersphere/metersphere/assets/172011320/7807d2eb-252b-47e4-907d-08d4e6487c67)
![IMG_5527](https://github.com/metersphere/metersphere/assets/172011320/9ec9507d-b3a2-4405-885b-2b1b8433dbc0)

**Comment by liuruibin** [comment]
chrome 什么版本？

**Comment by berserkerwsc** [comment]
Chrome 版本 91.0.4472.77

**Comment by liuruibin** [comment]
升级试试看现在最新的chrome是125.0.6422.142

**Comment by berserkerwsc** [comment]
![IMG_5536](https://github.com/metersphere/metersphere/assets/172011320/f14103a0-085e-4e1b-830e-363b1d974511)
目前升级后，功能可以使用了，但是控制台打印这个，这个代表啥呢？对整个功能使用会有啥影响嘛？

**Comment by youliyuan-fit2cloud** [comment]
看起来无影响，后续有遇到问题请随时反馈，感谢～
