### ISSUE TITLE
[BUG]社区版v3.x 关联禅道同步缺陷失败，ee版创建缺陷失败

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31343]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.0.0-beta

### 使用外置数据库

否

### 问题描述

社区版v3.x 关联禅道，同步缺陷，提示成功，列表不展示缺陷
ee版同步缺陷成功，没有生成缺陷模版

### 重现步骤

社区版v3.x 关联禅道，项目设置仅能增量同步，点击同步缺陷，提示成功，列表不展示缺陷
![image](https://github.com/metersphere/metersphere/assets/145318182/7e3e7422-f04f-4732-bb69-5c5d1a72752a)

ee版全量同步缺陷成功，点击创建缺陷，没有可选择的缺陷模版，所以无法创建禅道缺陷模版
![image](https://github.com/metersphere/metersphere/assets/145318182/75393f85-429b-4145-bc47-dcd76b7c63a7)

![image](https://github.com/metersphere/metersphere/assets/145318182/1315c8f2-ecb3-4340-8380-f4df5eefc719)

### 期待的正确结果

社区版是否开放全量同步缺陷，也可以在MS 创建禅道缺陷并同步到禅道（企业版亦可）

**Comment by luty2018** [comment]
1.社区版会在v3.1正式版本放开全量同步
2.配置成功后，创建缺陷用的是系统默认模板， 需要使用禅道模板，需要在模板管理中配置。

**Comment by fit2cloud-lijiaxin** [comment]
1.好的
2. 后续版本会支持，禅道缺陷模板像jira模版 一样，自动生成吗？

**Comment by youliyuan-fit2cloud** [comment]
2. 后续版本会支持，禅道缺陷模板像jira模版 一样，自动生成吗？
    ---->后续版本计划支持
