### ISSUE TITLE
[FEATURE]json文件结构校验有没有可能对返回值中的新增字段进行测试？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#31358]
### MeterSphere 版本

v2.7.1

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

比如我一个接口以前返回
{“user”:"zhangshi"}
现在返回{"user":"zhangshi","age":"18"}
目前的功能去断言，接口是完全可以通过的，测试用例无法感知到新增了一个age字段

**Comment by luty2018** [comment]
感谢建议， 这个我们需要调研一下。
