### ISSUE TITLE
[BUG]性能测试-原生jmeter脚本请求体中的//注释，导致在metersphere平台上执行压测场景异常

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#31359]
### MeterSphere 版本

v2.1.12-lts

### 使用外置数据库

是

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/82088551/c57137b4-4477-42f9-b159-0da10a4ced50)
原生jmeter脚本请求体中的//注释，导致在metersphere平台上执行压测场景异常

### 重现步骤

1、准备原生本地jmeter调试ok的脚本，请求体中带// 注释信息

### 期待的正确结果

期望请求体中带注释的jmx脚本可以正常在metersphere中压测场景执行

**Comment by 13290445582** [comment]
您好，麻烦提供下复现的jmx文件。

**Comment by zhangzhaox** [comment]
@13290445582 你好麻烦提供个邮箱，我发你邮件  我已经邮件案例了

**Comment by 13290445582** [comment]
邮箱：yicheng.wang@fit2cloud.com

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
