### ISSUE TITLE
[QUESTION]测试跟踪模块，导入用例找不到开放的open API

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#31363]
### 请描述您的问题

![20240611105305](https://github.com/metersphere/metersphere/assets/50876029/6e117559-8e83-497f-935d-83213ca16042)
测试跟踪模块，导入用例找不到开放的open API，我需要本地用例直接api对接，，但是找不到导入接口api ,,或者创建case接口的api

**Comment by liuruibin** [comment]
<img width="733" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/2de6a2e9-7bd9-4606-97ca-6b258c864f46">
