### ISSUE TITLE
[FEATURE]请求体/响应体中期望加上JSON-SCHEMA

### ISSUE THREAD

**Issue by CooyNinjia** [metersphere/metersphere#31371]
### MeterSphere 版本

v3.0.0-beta-5f013526

### 联系方式

1146528750@qq.com

### 请描述您的需求或者改进建议

希望V3版本能够加上请求体/响应体的JSON-SCHEMA功能，降低沟通成本，一切尽在描述中。

### 请描述你建议的实现方案

![9FD61891-8EEB-4198-9720-A9C949573C98](https://github.com/metersphere/metersphere/assets/61719711/2408bea2-0b56-4b16-86e0-9f2ba2c38cfe)

**Comment by luty2018** [comment]
这个已经规划在v3后面的版本中了哈。

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已支持。
