### ISSUE TITLE
[BUG] 接口自动化场景里面使用自定义请求，使用DELETE请求url中会出现重复http

### ISSUE THREAD

**Issue by chiehfeng** [metersphere/metersphere#31375]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/50366083/81ef3873-37e5-49a3-a39d-b9822ccfda42)
添加自定义请求后，请求方式修改为delete之后，发送请求会提示URI does not specify a valid host name，出现了重复的https。自定义请求切换至get/post之后发送的url是正常的，切换回来delete之后仍出现重复的url

### 重现步骤

1.添加自定义请求后，请求方式修改为delete发送请求

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
