### ISSUE TITLE
[BUG]接口测试_场景步骤_右侧执行结果预览_断言缺少滚动条

### ISSUE THREAD

**Issue by huodan** [metersphere/metersphere#31380]
### MeterSphere 版本

v3

### 使用外置数据库

否

### 问题描述

接口测试_场景步骤_右侧执行结果预览_断言缺少滚动条

### 重现步骤

接口测试》场景》点击特定场景》执行》切至步骤，鼠标停留在执行结果，点击弹出页断言

### 期待的正确结果

可以拖动滚动条看到全部断言内容

### 附加信息

![13131718105380_ pic](https://github.com/metersphere/metersphere/assets/26067881/e5f3070e-5c6a-4418-a582-d975440c78bb)

**Comment by 13290445582** [comment]
感谢反馈，计划v3.0正式版优化。

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v3.0.1中已修复该文件，升级一下吧～
