### ISSUE TITLE
[BUG] 测试用例评审，第一条评审第二条不评审，然后退出测试计划重新进入，查看评论切换用例，评论不刷新展示

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31383]
### MeterSphere 版本

2.10.14

### 使用外置数据库

否

### 问题描述

测试用例评审，第一条评审第二条不评审，然后退出测试计划重新进入，

查看第一条评论，然后切换用例看第二条，第二条用例没有评论，但是展示了第一条的数据——问题：评论不刷新展示
![image](https://github.com/metersphere/metersphere/assets/43202800/93e0fb76-c685-489a-b9ed-febe60d30153)

### 重现步骤

测试用例评审，第一条评审第二条不评审，然后退出测试计划重新进入，

查看第一条评论，然后切换用例看第二条，第二条用例没有评论，但是展示了第一条的数据——问题：评论不刷新展示

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，计划在V3正式版发布后的版本内修复。

**Comment by xhy12** [comment]
请问不能提前到2.10.16修复呢，客户那边使用有阻塞，工作进展比较麻烦

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级至v2.10.16版本使用。
