### ISSUE TITLE
[BUG]：通过MS推送TAPD自定义字段的缺陷时，推送内容不完整

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#3138]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是v1.9.3-a124268c

**Bug 描述**
通过TAPD为缺陷新增了项目名称和所属模块两个自定义字段，在ms上关联了对应tapd的项目，并在模版管理中同步为ms的缺陷模版添加了自定义字段，同时为项目重新指定关联了tapd的缺陷模版，然后通过MS推送缺陷，发现缺陷推送过去后丢失了项目名称和所属模块等字段信息，同时推送过去的缺陷无法查看截图内容

**Bug 重现步骤**
1.  tapd自定义字段
2. MS修改缺陷模版添加自定义字段
3. 通过MS提交缺陷
4. MS推送到TAPD的缺陷展示内容错误，无项目信息、无所属模块信息

**期待的正确结果**
正确推送缺陷到TAPD平台

**截图**
tapd自定义字段：
![image](https://user-images.githubusercontent.com/60059766/119590510-78764f00-be07-11eb-82d5-227ce2548727.png)

MS设置缺陷模版：
![image](https://user-images.githubusercontent.com/60059766/119590578-99d73b00-be07-11eb-8ead-2d447420e5f4.png)

MS提交缺陷：
![image](https://user-images.githubusercontent.com/60059766/119590699-d60a9b80-be07-11eb-8695-2cb4c4e70486.png)

推送到MS的缺陷：
![image](https://user-images.githubusercontent.com/60059766/119590447-5f6d9e00-be07-11eb-99b0-74ba4674cf24.png)

**Comment by zyyfit** [comment]
您好，1.9版本暂时不支持推送自定义字段，1.10版本将会增加这个功能

**Comment by zyyfit** [comment]
v1.10.0 已发布
