### ISSUE TITLE
[FEATURE]接口场景中，当使用 CSV 作为参数来源测试时发生了错误后，再次执行时从错误的地方开始执行

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#3142]
**请描述您的需求或者改进建议.**
希望在场景中使用 CSV 表格作为参数来源进行某个测试时，希望当遇到执行错误时，能将错误执行的参数标记出来或者导出来，并在再次执行时能从错误的开始，而不是重新开始；因为如果有一千行参数需要执行，其中只有四五十行参数执行失败时，需花费较多时间去进行统计，希望系统支持自动从错误的参数开始执行或者能将错误参数导出为CSV 文件；

**请描述你建议的实现方案**
经了解，想着 Jmeter 使用 CSV 文件进行执行时，是用一次 Jmeter ，将 CSV 文件传给 Jmeter，
方式一：如果上述调用Jmeter这种方式不进行改动的情况下，建议在测试报告地方提供一个根据请求错误返回，提供导出执行错误参数的方法，这样便于统计；
优点：改动小，便于实现；
缺点：功能局限性太大，无法为后续其它功能需求实现提供便利；
方式二：修改调用 Jmeter 方式，将 CSV 文件每行记录都读取出来，然后按正常请求来逐条发送请求至 Jmeter 根据返回情况，对CSV 中每行参数进行标记，当再次执行时按照标记失败的参数进行执行；
缺点：改动工作量相对较多；
优点：功能可扩展性相对较强；

**Comment by zhangzhaox** [comment]
在线展示或手动编辑CSV文件也可部分满足要求，类似与LR参数化文件设置从第几行开始读取数据
