### ISSUE TITLE
[BUG]加载python 扩展包，task-running 自动重启

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31433]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.0.0-beta-e556dc2f

### 使用外置数据库

否

### 问题描述

加载python 扩展包后，task-running 自动重启

### 重现步骤

1. task-running宿主机上安装python3.9.8
2. 参考 文章https://kb.fit2cloud.com/?p=105，安装虚拟环境，并将/opt/metersphere/data 目录挂载进task-running容器后，重建容器
3. 接口场景新建Python3脚本，点击服务端执行，一直在执行中：
![image](https://github.com/metersphere/metersphere/assets/145318182/61d89aaf-8dd9-422b-966a-4d22c1cd8d93)

查看task-running 日志，发现服务重启：
<img width="1158" alt="image" src="https://github.com/metersphere/metersphere/assets/145318182/e28ac0af-92c4-43fd-819c-1e73861d02bf">

### 期待的正确结果

服务正常返回结果

**Comment by liuruibin** [comment]
python包消耗内存非常大，建议先将 .env里的1g改成2g

挂载python lib
<img width="629" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/3b4a9e13-7f1e-41c3-a3c7-eba29735141f">

加载
<img width="517" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/45f2a5cc-e33d-4529-8e05-87443abb5552">

正常执行
<img width="1767" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/a8e6fa60-3fcc-4943-b783-09332544ddd0">
