### ISSUE TITLE
[FEATURE]一个小小的建议

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#31448]
### MeterSphere 版本

v3.0.0

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

能不能把ui自动化和性能测试功能在3.0以后的版本里加回去，毕竟ms是一个全面的测试平台啊

**Comment by liuruibin** [comment]
感谢使用，v3是一个全新的产品属于战略层面上的变更。

短期内不会加入性能测试和UI测试
