### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by karhow** [metersphere/metersphere#31452]
### 请描述您的问题

定时任务执行测试计划，计划中有很多场景，有一些场景用例超时，请问场景用例的超时时间是多少？，多久就会被判断为超时，哪里可以设置单个场景用例的超时时间？

**Comment by fit2-zhao** [comment]
可以参考下：
https://mp.weixin.qq.com/s/L2fSFciVoU-d9WoxIqjE6Q

![image](https://github.com/metersphere/metersphere/assets/70558837/0313aafc-4d1e-4a7e-a50e-5426eda1821f)

**Comment by karhow** [comment]
> 可以参考下： https://mp.weixin.qq.com/s/L2fSFciVoU-d9WoxIqjE6Q
> 
> ![image](https://private-user-images.githubusercontent.com/70558837/339637124-0313aafc-4d1e-4a7e-a50e-5426eda1821f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDY5NTAsIm5iZiI6MTcxODM0NjY1MCwicGF0aCI6Ii83MDU1ODgzNy8zMzk2MzcxMjQtMDMxM2FhZmMtNGQxZS00YTdlLWE1MGUtNTQyNmVkYTE4MjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA2MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODcwZTBkNGQ0M2NkM2MwZTZkNTAzYzRmNTQ5ZWMxOTlhZWFmMjYyZTkzMDcyMmRiMzQ2ZTZlN2FlMjZkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvLbVo6DV1ox5Fm7bxLhDOi-kdfkjxABxG84HbyzaJk)

这套机制我明白了，场景中有循环控制器，while循环控制器的超时时间比较长，你圈的timeout的监听机制好像不生效？
![image](https://github.com/metersphere/metersphere/assets/32405381/28d53f2d-e4d1-43e4-af38-0a414afcd9a2)
所以为什么这些有循环控制器的，是本地节点运行的，会都不符合这些条件？
![image](https://github.com/metersphere/metersphere/assets/32405381/c601359b-fedf-4796-9515-8b5953785ff8)
这是出问题吧？照理说一直在循环或者sleep，也应该属于在执行状态的

**Comment by karhow** [comment]
我观看时间，的确是大于60分钟的报告，但是为什么这些报告会不存在着四种情况中呢？本地运行不在kafka中我可以理解，但是为什么会不在执行线程中呢？

**Comment by fit2-zhao** [comment]
如果在循环中执行是不会被判定超时的，此时属于还在执行机的线程中存活；除非是执行机重启了；你检查一下你的服务状态。
