### ISSUE TITLE
[BUG]Swagger 导入报格式错误

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#31466]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

Swagger 导入报格式错误
![image](https://github.com/metersphere/metersphere/assets/103627487/a2e6e407-6058-44be-bc56-cb2c508b0808)
![img_v3_02br_624a0db4-0994-4c9a-b66a-5d3e71cea2cg](https://github.com/metersphere/metersphere/assets/103627487/8c4cb683-e6dc-40b7-b816-8e81d7b45794)

### 重现步骤

接口 Swagger 导入
![img_v3_02br_624a0db4-0994-4c9a-b66a-5d3e71cea2cg](https://github.com/metersphere/metersphere/assets/103627487/310b6708-0f16-4e20-94b2-99c90b15e17f)

**Comment by 13290445582** [comment]
您好，查看到后台报错信息是由于api_moudle的name过长导致，加大api_moudle的name字段长度即可解决该问题。可使用以下SQL解决：ALTER TABLE api_module MODIFY COLUMN name VARCHAR(255);

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
