### ISSUE TITLE
[FEATURE] v3.0 

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#31478]
### MeterSphere 版本

3.0

### 请描述您的需求或者改进建议

测试计划不能关联接口用例了吗

### 请描述你建议的实现方案

v2是可以的
![image](https://github.com/metersphere/metersphere/assets/26613645/d5c77ca2-ad40-47c3-9b0c-d98d0bceb601)

**Comment by luty2018** [comment]
月底正式版会支持关联接口测试哈。
