### ISSUE TITLE
[BUG] 控制台打印其他jmeter线程的日志

### ISSUE THREAD

**Issue by karhow** [metersphere/metersphere#31470]
### MeterSphere 版本

2.0

### 使用外置数据库

是

### 问题描述

和这个issue的问题是一样的：https://github.com/metersphere/metersphere/issues/23589
在一些循环控制器运行后，stop了是没有用的，还有就是循环超时了也是一样，依然会在后台运行，然后日志被其他jmeter运行的控制台捕获

### 重现步骤

可以试试使用循环控制器，超过一个小时（例如2小时）的循环，配合其他场景运行，就能看到前一个场景的打印日志

### 期待的正确结果

日志不会被其他jmeter运行捕获，然后测试计划在这些超过一小时的运行结果的正常获取到线程

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，但目前日志无法隔离，执行日志是获取jmeter 自身打印的日志。

**Comment by karhow** [comment]
为什么你们这家公司喜欢用户都没解决完问题，就关闭issue，你们是这样做开源社区的？这里的问题还存在与jmeter停止失败，你们使用一个小时作为测试报告的超时状态处理，然后其实后台jmeter是没有停止的，还有就是上面提到的运行场景，点击了停止，其实也是没有停止，jmeter还在运行这个循环。包括这个issue：https://github.com/metersphere/metersphere/issues/23589
证明你们场景的停止逻辑也是有问题的，循环不能正确停止

**Comment by youliyuan-fit2cloud** [comment]
> 为什么你们这家公司喜欢用户都没解决完问题，就关闭issue，你们是这样做开源社区的？这里的问题还存在与jmeter停止失败，你们使用一个小时作为测试报告的超时状态处理，然后其实后台jmeter是没有停止的，还有就是上面提到的运行场景，点击了停止，其实也是没有停止，jmeter还在运行这个循环。包括这个issue：#23589 证明你们场景的停止逻辑也是有问题的，循环不能正确停止

非常抱歉，之前的回复有误。你当前这个版本v2.0 确实不支持，后续版本v2.10.x以上版本修复了提到的2个问题，建议升级到最新版。

**Comment by karhow** [comment]
> > 为什么你们这家公司喜欢用户都没解决完问题，就关闭issue，你们是这样做开源社区的？这里的问题还存在与jmeter停止失败，你们使用一个小时作为测试报告的超时状态处理，然后其实后台jmeter是没有停止的，还有就是上面提到的运行场景，点击了停止，其实也是没有停止，jmeter还在运行这个循环。包括这个issue：#23589 证明你们场景的停止逻辑也是有问题的，循环不能正确停止
> 
> 非常抱歉，之前的回复有误。你当前这个版本v2.0 确实不支持，后续版本v2.10.x以上版本修复了提到的2个问题，建议升级到最新版。

有无关联的pr合并的链接?想要看看

**Comment by youliyuan-fit2cloud** [comment]
@karhow
抱歉，具体的pr目前无法提供，建议升级版本。
