### ISSUE TITLE
[BUG]接口定义_调试_实际发送的请求与定义不一致

### ISSUE THREAD

**Issue by huodan** [metersphere/metersphere#31476]
### MeterSphere 版本

v3

### 使用外置数据库

否

### 问题描述

![20240614-181640](https://github.com/metersphere/metersphere/assets/26067881/42d2a517-bfa0-4a7b-a7ec-245a977905ae)
![20240614-181856](https://github.com/metersphere/metersphere/assets/26067881/ca141563-32df-46f8-b272-4e213f295a76)

在自建挡板112环境下
1. 发送的请求应该是POST，实际为GET
2. body体应该为设置的json，实际为空

切换换其他环境，无此问题，环境不应该影响报文发送。

### 重现步骤

未找到规律和复现路径，在我本地跑遇到的这个问题，会稳定重复出现

**Comment by youliyuan-fit2cloud** [comment]
你好，是否使用的最新release版本？我们有改过类似问题。

**Comment by luty2018** [comment]
1.如果是请求类型不对，可能是进行了重定向
2.检查您的请求域名，是否是https://
3.建议你升级到最新版本，如果还能重现请和我们联系
