### ISSUE TITLE
[BUG] 3.0 离线版安装问题。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31487]
### MeterSphere 版本

3.0-beta

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/44999044/f33f0c91-be36-41ab-9f8b-de7323a2e3bb)
![image](https://github.com/metersphere/metersphere/assets/44999044/8760e556-aa73-4653-902a-5f973cd4dd60)

### 重现步骤

前置条件：服务器上已经安装好了docker Server Version: 19.03.8
1. 下载离线包
2. 解压，并修改MS_BASE为/home
3. 修改mysql、redis、主程序默认端口
4. 执行./install.sh

**Comment by youliyuan-fit2cloud** [comment]
你好，docker版本升级到v25以上试试呢？
