### ISSUE TITLE
[FEATURE]小小的建议：添加一个自动生成接口case的功能

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#31501]
### MeterSphere 版本

v3.0.0

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

在接口文档能被ms读取的情况下，ms能对接口的入参的必填项之类的能生成接口case，比如user字段必填，那么生成一个user传空的用例

**Comment by luty2018** [comment]
感谢建议， 我们调研一下
