### ISSUE TITLE
[BUG]接口使用文档断言时，若含有其他类型断言并勾选了“忽略状态”会影响最终执行结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#31528]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

接口步骤有多个类型的断言，其中使用文档断言时，若含有其他类型断言并勾选了“忽略状态”会影响最终执行结果

### 重现步骤

1、接口步骤添加文件断言，并使某一个步骤为ERROR
2、添加文本类型断言或者带有“忽略状态”选项的断言，并勾选“忽略状态”，观察执行结果
3、不勾选“忽略状态”，观察执行结果

### 附加信息

断言内容：
<img width="1460" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/9bae409d-8b78-4ac6-a892-04ddbc085d94">

执行结果：
<img width="1470" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/50855251-9836-41d5-bc14-750b4f7f45c8">

不勾选“忽略状态”：
<img width="1465" alt="image" src="https://github.com/metersphere/metersphere/assets/32027713/042b10ef-d788-464e-aba3-942609071058">

**Comment by 13290445582** [comment]
您好，可提供下您的复现环境。

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
