### ISSUE TITLE
[BUG]metersphere的jenkins插件执行接口场景用例时 测试报告显示通过，Jenkins上显示该测试请求未能通过

### ISSUE THREAD

**Issue by wangufeng** [metersphere/metersphere#31569]
### 联系方式

419937444@qq.com

### MeterSphere 版本

v2.10.15-lts-1e4e1f7b

### 使用外置数据库

否

### 问题描述

metersphere的jenkins插件执行接口场景用例时 测试报告显示通过，Jenkins上显示该测试请求未能通过
执行单个接口测试用例时是正常的

### 重现步骤

准备一个接口场景测试case 
在jenkins 执行这个场景用例
预期结果 jenkins的执行结果和测试报告中的结果一致

**Comment by wangufeng** [comment]
![image](https://github.com/metersphere/metersphere/assets/173153354/9db5728b-92fc-4747-9144-63adb5d03349)
![image](https://github.com/metersphere/metersphere/assets/173153354/1fde3f6a-823e-4848-b664-95d926d5baea)

**Comment by wangufeng** [comment]
![image](https://github.com/metersphere/metersphere/assets/173153354/cf384f9e-8db4-4bbc-bbbd-274877fbdecf)

**Comment by youliyuan-fit2cloud** [comment]
你好，Jenkins插件是哪个版本？

**Comment by YeungHoiChiu** [comment]
link https://github.com/metersphere/metersphere/issues/31267 删除镜像重新拉

**Comment by wangufeng** [comment]
Jenkins插件 2.10版本

**Comment by wangufeng** [comment]
升级新版本 已解决
