### ISSUE TITLE
[BUG]xmind导入meterSphere的后模块顺序和源文件不一致

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#3156]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.9.3

**Bug 描述**
简要描述您碰到的问题
xmind导入的后模块顺序和源文件不一致

**Bug 重现步骤**
1.  xmind导入用例

**期待的正确结果**
正确情况下应该是什么样的？
导入meterSphere后的模块顺序和原来xmind一致
**截图**
如果有截图，请附上截图.
xmind顺序：
![image](https://user-images.githubusercontent.com/49704984/119610398-c0a76880-be2b-11eb-9352-8efcb21cd8c6.png)

导入后：
![image](https://user-images.githubusercontent.com/49704984/119610215-76be8280-be2b-11eb-8dbd-57a38f8b95ef.png)

**Comment by zyyfit** [comment]
您好，xmind文件顺序问题将在后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
