### ISSUE TITLE
[FEATURE]希望测试计划的搜索中增加筛选自定义字段的功能

### ISSUE THREAD

**Issue by dreamerwyx** [metersphere/metersphere#31561]
### MeterSphere 版本

v2.10.15-lts

### 联系方式

wyxleft@163.com

### 请描述您的需求或者改进建议
![微信图片_20240618141957](https://github.com/metersphere/metersphere/assets/71875709/dc0684fc-d3dd-4bfb-a344-4a2703dffa02)

在测试计划中，当用例数量很多时，需要搜索自定义的字段来筛选用例。目前只能筛选系统自有的几个字段，使用起来很不方便。

### 请描述你建议的实现方案

希望可以做成在功能测试用例中筛选的样子，可以筛选自定义字段。

**Comment by luty2018** [comment]
这个我们已经规划到v3.0了哈

**Comment by dreamerwyx** [comment]
请问3.0大概什么时间发布？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月18日 16:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [metersphere/metersphere] [FEATURE]希望测试计划的搜索中增加筛选自定义字段的功能 (Issue #31561) |

这个我们已经规划到v3.0了哈

**Comment by dreamerwyx** [comment]
> 这个我们已经规划到v3.0了哈

已经3.0了，这个功能还没实现呢

**Comment by luty2018** [comment]
> > 这个我们已经规划到v3.0了哈
> 
> 已经3.0了，这个功能还没实现呢

v3.3哈，9月底的版本，因为整个系统的列表都会支持高级搜索，所以时间回稍微久一点。
