### ISSUE TITLE
[BUG]版本升级后，xmind导入用例，步骤-预期结果导入失败

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#3158]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题
xmind导入用例，步骤-预期结果导入失败
**Bug 重现步骤**
1.  xmind导入用例
2. 查看用例，发现步骤-预期结果导入失败
3. 同一份用例在1.9.0版本导入成功。

**期待的正确结果**
正确情况下应该是什么样的？
xmind导入用例，步骤-预期结果导入成功
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/49704984/119612793-e6823c80-be2e-11eb-9fb2-68e60c579dee.png)

![image](https://user-images.githubusercontent.com/49704984/119612515-8f7c6780-be2e-11eb-8445-04b56dfaf63a.png)

**Comment by zyyfit** [comment]
您好，没有复现呢，方便提供一下xmind文件吗

**Comment by liAnita** [comment]
> 您好，没有复现呢，方便提供一下xmind文件吗？顺便问一下，是1.9.0版本中已经有这些用例了，然后升级到1.9.3，然后又导入了一次吗

 我部署了两套环境（一套是没有升级的（1.9.0），一套是部署的是1.9.3）。
 已经升级到1.10. 看到提示错误：
![image](https://user-images.githubusercontent.com/49704984/119787642-ff105680-bf03-11eb-9ab7-0124311d6da9.png)
xmind：
![image](https://user-images.githubusercontent.com/49704984/119787774-2404c980-bf04-11eb-9705-3578b2a39966.png)
不太明白是什么问题导致的。

**Comment by xulinde** [comment]
v1.12.1已修复
