### ISSUE TITLE
[BUG] 表格跨页全选bug，点击跨页全选后再取消选中，期望为所有勾选都清空，实际还有3条在勾选状态

### ISSUE THREAD

**Issue by RubyLiuBlog** [metersphere/metersphere#31585]
### 联系方式

刀弟

### MeterSphere 版本

v3.0.0-beta-5f013526

### 使用外置数据库

否

### 问题描述

如 title 描述

### 重现步骤

1. 点击测试用例模块
2. 点击全部用例的表格全选按钮
3. 点击跨页全选 默认13条数据，当页条数10条，第二页3条全部选中
4. 点击复选框，取消勾选，复选框状态错误，下方显示已勾选3条。

### 期待的正确结果

期望跨页全选取消时，复选框展示初始状态，并关闭批量操作

### 附加信息

<img width="1784" alt="image" src="https://github.com/metersphere/metersphere/assets/73574219/a322e492-b4c5-4cba-9b5a-ba7589e25d37">

<img width="1281" alt="image" src="https://github.com/metersphere/metersphere/assets/73574219/82f32b2d-c251-4f14-ae6e-f0a56d4e0807">
<img width="1276" alt="image" src="https://github.com/metersphere/metersphere/assets/73574219/d01432e0-cc07-4c64-aa0a-efbaeeb57764">

**Comment by luty2018** [comment]
这里缺了一个取消全选所有页的功能， 所以造成了使用上的误导。我们后面可以优化这个地方。
刀弟可以先建议同事们点击右下角的清空来达到取消全选所有页的效果。

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已修复。
