### ISSUE TITLE
[BUG]接口自动化选择多个场景批量执行时，指定集合报告，数据库报错，也未执行

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3159]
**MeterSphere 版本**
V1.9.3

**Bug 描述**
接口自动化选择多个场景批量执行时，指定集合报告，数据库报错，场景也未执行
![WechatIMG876](https://user-images.githubusercontent.com/32027713/119613432-9d7eb800-be2f-11eb-947c-dd8ac5b32438.png)

**Bug 重现步骤**
1.  场景自动化
2. 选择所有场景
3. 点击批量执行
4. 报告类型选择“集合”

**截图**
数据库报错
![WechatIMG872](https://user-images.githubusercontent.com/32027713/119613548-c8690c00-be2f-11eb-9ccc-192ac1523ed7.jpeg)

**Comment by zyyfit** [comment]
您好，看报错像是有个scenario_id太长了，旧版的ID长度比现在版本的要长，修改一下ID试试？

**Comment by dashenyucainiao** [comment]
这个不应该产品去兼容吗？数据库去改Id长度？

**Comment by dashenyucainiao** [comment]
而且我怎么查找哪个scenario_id长度是超长的呢？

**Comment by zyyfit** [comment]
我们也会优化这种情况的，请问是第一次出现这种情况吗？是旧版转换的接口吗？

**Comment by dashenyucainiao** [comment]
选的报告类型为：独立报告就没这个问题，选集合报告就会出现上面的这个错误

**Comment by zyyfit** [comment]
> 选的报告类型为：独立报告就没这个问题，选集合报告就会出现上面的这个错误

您好，今天会发布1.10.1版本，请升级新版本试试

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.10.1 已修复，请升级到该版本。
