### ISSUE TITLE
接口测试对于MD5等加密时，缺少引入三方jar包功能

### ISSUE THREAD

**Issue by qiuquanzhi** [metersphere/metersphere#316]
**请描述您的需求或者改进建议.**

接口测试对于MD5等加密时，缺少引入三方jar包功能

**请描述你建议的实现方案**
引入三方jar包功能

**Comment by wangzhen-fit2cloud** [comment]
你好，如果是试用 MD5 加密的话，现在可以试用内置函数的方式来完成。
如果需要用到自定义的方法引入jar包，这个需要我们进一步规划下。

**Comment by qiuquanzhi** [comment]
内置函数在哪？没找到

发自我的iPhone

**Comment by wangzhen-fit2cloud** [comment]
你好，可以在前后置脚本中使用内置的库来进行 md5 加密，例如使用 beanshell 脚本
```java
import org.apache.commons.codec.digest.DigestUtils;
System.out.println("md5 digest of hello is: "+DigestUtils.md5Hex("hello"));
```
