### ISSUE TITLE
[QUESTION]我接口写入用例为啥会概率性写入成功

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#31619]
### 请描述您的问题

执行一次请求，成功，再次执行就提示这个：<!doctype html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" href="/display/file/logo" type="image/x-icon"><script defer="defer" src="/js/fortawesome.38fc435e.js"></script><script defer="defer" src="/js/jsencrypt.736caa73.js"></script><script defer="defer" src="/js/pinia.0d3c3705.js"></script><script defer="defer" src="/js/jspdf.9a32b13c.js"></script><script defer="defer" src="/js/html2canvas.94141076.js"></script><script defer="defer" src="/js/chunk-vendors.aa8fd6ec.js"></script><script defer="defer" src="/js/app.e92475e3.js"></script><link href="/css/app.e4d9054a.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but metersphere-frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div></body></html>

**Comment by fit2-zhao** [comment]
为了更好的解决你的困惑，麻烦把问题再描述详细些。

**Comment by hujirong521317** [comment]
我测试脚本，执行这个接口，循环写入测试用例例"https://metersphere.innosnap.com/track/test/case/minder/edit"，，
![20240620125050](https://github.com/metersphere/metersphere/assets/50876029/ed15f15c-8d37-41b7-8271-dc4685cb6c4d)
但是执行一次成功写入，再次执行，无法成功写入，给我返回的是<!doctype html><script defer="defer" src="/js/fortawesome.38fc435e.js"></script><script defer="defer" src="/js/jsencrypt.736caa73.js"></script><script defer="defer" src="/js/pinia.0d3c3705.js"></script><script defer="defer" src="/js/jspdf.9a32b13c.js"></script><script defer="defer" src="/js/html2canvas.94141076.js"></script><script defer="defer" src="/js/chunk-vendors.aa8fd6ec.js"></script><script defer="defer" src="/js/app.e92475e3.js"></script>We're sorry but metersphere-frontend doesn't work properly without JavaScript enabled. Please enable it to continue.

是接口有什么安全性设置吗

**Comment by fit2-zhao** [comment]
默认安装并未做限制，如果你是循环调用，建议加点间隔时间，或者对请求加个失败重试。

**Comment by fit2-zhao** [comment]
如果只是导入用例可以用 track/test/case/add 这个接口试试看； 或者用平台提供的脑图导入功能。

**Comment by hujirong521317** [comment]
我是利用AI生成，然后循环用这个接口写入，请求头信息就是API文档要求的那几个参数吧，，，但是postman执行就没有问题，很困惑

**Comment by fit2-zhao** [comment]
建议加点间隔时间，或者对请求加个失败重试就行。
