### ISSUE TITLE
[BUG] 三方接口插件导入后，新建定义，保存后，页面数据为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#31636]
### 联系方式

姚春荣

### MeterSphere 版本

v3

### 使用外置数据库

否

### 问题描述

三方接口插件导入后，新建定义，保存后，页面数据为空

### 重现步骤

新建TCP定义
![image](https://github.com/metersphere/metersphere/assets/103925124/27d86327-d2d1-47e6-8d4d-cfe3506e2e7b)
新建成功后，页面回显都是空值
![image](https://github.com/metersphere/metersphere/assets/103925124/1617b73e-6f78-4762-a410-c8f531e1388d)

**Comment by 13290445582** [comment]
您好，最新环境v3.0.1已发布，未复现该问题，建议升级使用，若升级后依旧有问题，请继续反馈。
