### ISSUE TITLE
[QUESTION] 后期2.x版本JDK会升级到21版吗？

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#31648]
### 请描述您的问题

由于我们有要求统一升级JDK21版本，不知贵公司在2.x版本后期是否会使用JDK21？我看3.x当前使用的是JDK21

**Comment by fit2-zhao** [comment]
v2.x 版本的JDK暂时不考虑升级，可以使用我们 v3.x 的版本。

**Comment by SloanGao** [comment]
> v2.x 版本的JDK暂时不考虑升级，可以使用我们 v3.x 的版本。

那2.x版本的用例支持迁移3.x吗？如果不支持根本用不了3.x，所有用例都在2.x上
