### ISSUE TITLE
[BUG]当运行环境中有不同类型的数据源时，切换自运行环境SQL步骤没有切换到对应环境的同名数据源

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#31645]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

当运行环境中有不同类型的数据源时，切换自运行环境SQL步骤没有切换到对应环境的同名数据源（切换环境，数据源要保持同名原则）

### 重现步骤

1、准备两个运行环境，环境中分别有
环境A：有数据库： MySQL-m，Oracle-o
环境B： 有数据库： MySQL-m，Oracle-o
2、场景中在case中添加前后置SQL，并选择环境A选MySQL-m保存
![image](https://github.com/metersphere/metersphere/assets/88763608/ed0c401c-41d1-4534-8fc4-5fcebfaa67be)

3、切换环境B，结果case中数据源变成了Oracle-o
![image](https://github.com/metersphere/metersphere/assets/88763608/31c4faae-5123-43ae-a7d0-ec26ddfb0179)

4、复现环境https://qa-release.fit2cloud.com/  南区MS成功组（工作空间）》UIshow（项目）》SQL修改（场景）》步骤3

### 期待的正确结果

切换环境后，应该继续保持为数据源MySQL-m

**Comment by youliyuan-fit2cloud** [comment]
你好，用你这个环境没复现了。。。

**Comment by 13290445582** [comment]
请检查操作是否无误，相同环境未复现，暂且关闭该issue，感谢理解与支持。
