### ISSUE TITLE
[BUG]Metersphere 的jenkins 插件当两个不同项目的job同时运行时，后面运行的job 会打印前面运行的job 日志

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#31654]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

Metersphere 的jenkins 插件当两个不同项目的job同时运行时，后面运行的job 会打印前面运行的job 日志

### 重现步骤

1. 下载Jenkins 最新版本的插件
2. Jenkins里面当两个不同项目的job同时运行
3. 发现后面运行的job 会打印前面运行的job 日志

### 期待的正确结果

后面运行的job 不打印前面运行的job 日志，两个日志独立展示

### 相关日志输出

```shell
无
```

### 附加信息

<img width="1181" alt="d651f0427ff73a4c9fc47f9b77ab749" src="https://github.com/metersphere/metersphere/assets/50016789/f8218d6f-8dea-4990-8191-648cbdbd744a">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
