### ISSUE TITLE
[FEATURE]推荐JSONPath断言断言列表的时候可以带上转义符号吗

### ISSUE THREAD

**Issue by chiehfeng** [metersphere/metersphere#31664]
### MeterSphere 版本

v2.10.15-lts

### 请描述您的需求或者改进建议

点击推荐JSONPath断言，选择列表进行断言的时候。默认生成的正则匹配没有带上转义符号，这个时候直接使用该断言就会断言失败，可以默认生成的时候就带上转义符号吗
![image](https://github.com/metersphere/metersphere/assets/50366083/b70d67ce-b417-4e93-a8b0-60d4f1f32a71)
![image](https://github.com/metersphere/metersphere/assets/50366083/b74277b3-764f-4b76-8939-1ee050ecdc6c)

**Comment by luty2018** [comment]
这个需要用户手动转义
