### ISSUE TITLE
[BUG]3.0邮箱和消息通知只有场景执行能收到通知

### ISSUE THREAD

**Issue by yangweijuan980616** [metersphere/metersphere#31660]
### 联系方式

vx：xiaoyutoucom

### MeterSphere 版本

v3.0

### 使用外置数据库

否

### 问题描述

邮箱和消息通知只有场景执行能收到通知
![1718888380197](https://github.com/metersphere/metersphere/assets/156180702/edd3e205-c97e-4cdd-9851-cbfdd8fdfcd8)

### 重现步骤

接口新增、修改、执行没有通知，只有场景测试执行的通知

### 期待的正确结果

接口测试的其他操作也应该会有消息通知

**Comment by Hyyfit** [comment]
您看一下，接口测试相关的通知是否配上了？
另外如果操作人和配置通知的接收人是同一个的话，是不会发送通知的。
![image](https://github.com/metersphere/metersphere/assets/95834771/8d2ddabd-1564-43c7-bf58-abdf7846e950)

**Comment by yangweijuan980616** [comment]
均配置上了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]3.0邮箱和消息通知只有场景执行能收到通知 (Issue #31660)




 
您看一下，接口测试相关的通知是否配上了
 image.png (view on web)

**Comment by luty2018** [comment]
> 均配置上了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月27日(周四) 中午12:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [metersphere/metersphere] [BUG]3.0邮箱和消息通知只有场景执行能收到通知 (Issue #31660) 您看一下，接口测试相关的通知是否配上了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请提供一下您的版本号
![image](https://github.com/metersphere/metersphere/assets/36292514/4a45bad5-66a5-4e0d-b72c-ea0408f4fc3b)

**Comment by luty2018** [comment]
> 均配置上了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月27日(周四) 中午12:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [metersphere/metersphere] [BUG]3.0邮箱和消息通知只有场景执行能收到通知 (Issue #31660) 您看一下，接口测试相关的通知是否配上了 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

麻烦提供您的配置页面截图， 另外注意，如果配置的接收人是操作人自己，是不会触发通知的

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
