### ISSUE TITLE
[BUG]【模板管理】将default模板改为 文本描述 保存，在项目中使用该模板，新建功能用例时，页面并没有显示 文本描述，仍是步骤描述。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31688]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

【模板管理】将default模板改为 文本描述 保存，在项目中使用该模板，新建功能用例时，页面并没有显示 文本描述，仍是步骤描述。

### 重现步骤

【模板管理】将default模板改为 文本描述 保存，在项目中使用该模板，新建功能用例时，页面并没有显示 文本描述，仍是步骤描述。
![image](https://github.com/metersphere/metersphere/assets/104960608/be3b862f-ddca-45f7-a6e8-f90ce0dd9b4f)
![image](https://github.com/metersphere/metersphere/assets/104960608/1ee23c23-517d-46b3-b151-8520e9411d34)
![image](https://github.com/metersphere/metersphere/assets/104960608/36de3cdc-50f7-45b0-858e-2c7de2af0b1f)

**Comment by luty2018** [comment]
已确认问题，会在v2.10.17版本修复

**Comment by 13290445582** [comment]
您好，问题已修复，请升级至v2.10.16版本使用。
