### ISSUE TITLE
[BUG]导入 POSTMAN 脚本无法直接新增请求参数、请求头等

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#317]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.2.0-b610

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  导入Postman脚本
2. 请求参数，请求头，请求内容，无法新增参数
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
导入Postman脚本后 请求参数，请求头，请求内容，可以新增参数

**截图**
如果有截图，请附上截图.
![2](https://user-images.githubusercontent.com/29306248/91812892-62ff3a80-ec64-11ea-8579-de162ab7c78a.png)

**Comment by zhao103804** [comment]
只有修改了最后一行的数据才会在最下面新增一行出来

**Comment by wangzhen-fit2cloud** [comment]
新版本中已解决
