### ISSUE TITLE
[BUG] 场景用例覆盖率计算错误，覆盖了的接口，却在未覆盖中。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31704]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/44999044/82730745-5578-4834-86ef-5bf6a68d74e0)

### 重现步骤

1. 从接口测试首页点进去，未覆盖626
![image](https://github.com/metersphere/metersphere/assets/44999044/b759ed42-5902-4cdc-a0dd-ebad0058f1c7)

2. 该接口已在场景中覆盖，但是被统计到了
![image](https://github.com/metersphere/metersphere/assets/44999044/9523d038-b623-49bd-8c69-496f2bf274fa)

查看引用：

![image](https://github.com/metersphere/metersphere/assets/44999044/6073caa4-f7c4-479f-8080-3f4c2d5093ee)

### 期待的正确结果

场景用例覆盖率统计正确。

**Comment by LimonFHM** [comment]
有人吗。

**Comment by Hyyfit** [comment]
您好，问题复现了。
非常感谢您的反馈，我们会在后续的版本修复该问题。

**Comment by wangufeng** [comment]
这个问题修复了吗 我也遇到了同样的问题 sql类型的API 已经在场景中了 但系统在计算场景覆盖率的时候却被忽略掉了
刚刚又试了下 sql类型的api 在场景复制了对应api是会被计算到覆盖率里面的，若引用对于的case是不会被计算到覆盖率里面的

**Comment by LimonFHM** [comment]
还未修复。

**Comment by Somebody-JIAN** [comment]
我只有在跨项目的情况下（别的项目关联了接口，但是本项目没有操作）才出现了您说的情况。

返回查看您在issue中的贴图，不知道是不是跨项目关联。

如果是跨项目引用，很抱歉，我们认为这样是没必要进行统计的。我们认为这个统计功能是在项目中的，并非系统视角。那么它的统计范围我们也会固定在当前项目内。

**Comment by Somebody-JIAN** [comment]
> 这个问题修复了吗 我也遇到了同样的问题 sql类型的API 已经在场景中了 但系统在计算场景覆盖率的时候却被忽略掉了 刚刚又试了下 sql类型的api 在场景复制了对应api是会被计算到覆盖率里面的，若引用对于的case是不会被计算到覆盖率里面的

针对http的覆盖算法规则，是通过请求方法、请求路径来进行匹配的。 所以直接关联http接口下的用例，只要没有修改过用例的路径，也是会被算法覆盖。

我们做这种算法的最初目的是希望能解析场景里的“自定义http请求”。

非http的请求，我们并没有做这种规则校验。 所以您这种情况是不会统计的。

**Comment by Somebody-JIAN** [comment]
> 有人吗。

使用版本v2.10.19


我在接口定义路径后有空格的情况下复现了这个问题，刚刚提了pr修复。

还在跨项目的情况下（别的项目关联了接口，但是本项目没有操作）复现了这种情况。不过这种方式不考虑修复。原因如下：
我们认为这个统计功能是在项目中的，并非系统视角。那么它的统计范围我们也会固定在当前项目内。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
