### ISSUE TITLE
[BUG]接口自动化出现数据库死锁问题

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#31701]
### 联系方式

张树彬

### MeterSphere 版本

2.10.5

### 使用外置数据库

否

### 问题描述

接口自动化出现数据库死锁问题，发现此问题在旧版本也反馈并修复过
https://github.com/metersphere/metersphere/issues/18502
https://wiki.fit2cloud.com/pages/viewpage.action?pageId=100074770

### 重现步骤

操作接口自动化侧功能，偶发出现此问题，重启后可以恢复。

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/77324661/9efc9499-0613-4eb0-a8ca-1a5d9fb54f4a)

**Comment by youliyuan-fit2cloud** [comment]
确定下是哪个版本？v2.10.5-lts?

**Comment by binbin0406** [comment]
是的
----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："MatataYou ***@***.***&gt;;
发送时间：2024年6月27日(星期四) 中午1:53
收件人："metersphere/metersphere" ***@***.***&gt;;
抄送："张树彬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [metersphere/metersphere] [BUG]接口自动化出现数据库死锁问题 (Issue #31701)
-----------------------------------

 

 
确定下是哪个版本？v2.10.5-lts?

**Comment by youliyuan-fit2cloud** [comment]
> 是的 ---------- 该邮件从移动设备发送
> […](#)
> --------------原始邮件-------------- 发件人："MatataYou ***@***.***&gt;; 发送时间：2024年6月27日(星期四) 中午1:53 收件人："metersphere/metersphere" ***@***.***&gt;; 抄送："张树彬 ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [metersphere/metersphere] [BUG]接口自动化出现数据库死锁问题 (Issue #31701) ----------------------------------- 确定下是哪个版本？v2.10.5-lts? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

如果是v2.10.5-lts 版本，建议升级到最新版本吧，毕竟版本有点老旧了。感谢理解和支持。

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
