### ISSUE TITLE
[BUG] 测试计划定时任务，配置了执行失败钉钉消息通知，勾选了失败停止，钉钉产生两条消息，不勾选则正常

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#31724]
### MeterSphere 版本

2.10.7

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/43202800/421fe790-7f4f-4ad1-9688-5e5e172bc4e6)
测试计划定时任务，配置了执行失败钉钉消息通知，勾选了失败停止，钉钉产生两条消息，不勾选则正常

### 重现步骤

测试计划定时任务，配置了执行失败钉钉消息通知，勾选了失败停止，钉钉产生两条消息，不勾选则正常，如上图

### 期待的正确结果

发一条消息

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试用最新版本的环境没有复现该问题，建议升级一下吧。感谢理解和支持。

**Comment by 13290445582** [comment]
建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
