### ISSUE TITLE
[BUG] API-TEST服务频繁出现OOM现象。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#31744]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

api-test服务经常发生oom，导致自动重启，无法执行接口测试。
![企业微信截图_17192777667341](https://github.com/metersphere/metersphere/assets/44999044/3663c42a-763c-4c8e-9fbf-ab6d642c28a3)

### 重现步骤

1. 执行一个测试计划，测试计划里的接口可能比较多，本例中有1300接口用例（全是场景用例）

### 期待的正确结果

不要OOM

### 相关日志输出

```shell
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

**Comment by liuruibin** [comment]
手动调整api-test yml文件的内存限制

**Comment by LimonFHM** [comment]
> 手动调整api-test yml文件的内存限制

![image](https://github.com/metersphere/metersphere/assets/44999044/b91e8b15-e52d-4c61-b7bb-6de003a7e44d)



shizh是这个吗？install.conf加，然后reload？

**Comment by liuruibin** [comment]
是的

**Comment by LimonFHM** [comment]
已解决。
