### ISSUE TITLE
[BUG]【性能测试】文件管理-对接第三方仓库，如gitea仓库，将csv文件关联到性能测试场景中，运行场景时，容器内存会飙升，且运行完成后一直不释放。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31769]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

【性能测试】文件管理-对接第三方仓库，如gitea仓库，将csv文件关联到性能测试场景中，运行场景时，容器内存会飙升，且运行完成后一直不释放。

### 重现步骤

【性能测试】文件管理-对接第三方仓库，如gitea仓库，将csv文件关联到性能测试场景中，运行场景完成后，容器内存一直不释放。
![1719308788426](https://github.com/metersphere/metersphere/assets/104960608/505ca65c-fda6-4d4c-8797-0c904849300d)
![1719308788415](https://github.com/metersphere/metersphere/assets/104960608/43b91bf2-a823-46dc-9716-11cfe12d2e9b)

运行场景之前
![1719308788448](https://github.com/metersphere/metersphere/assets/104960608/7c6da327-30a3-4e19-86c9-860dcd745dc1)
运行场景时
![1719308788452](https://github.com/metersphere/metersphere/assets/104960608/810a3f6a-540c-41b3-a6e7-5a14ad4500b7)
场景运行完成之后，内存一直不释放
![1719308788457](https://github.com/metersphere/metersphere/assets/104960608/91fbe607-ded9-49f6-af5d-425f2bfd9fc6)
此时再去运行另外场景，性能测试页面很容易就挂。
![1719308788436](https://github.com/metersphere/metersphere/assets/104960608/9041f9d2-61d3-4a89-be39-6dcb32a332b7)

一模一样的csv文件，直接在文件管理处上传，将csv文件关联到性能测试场景中，运行场景时，容器内存并没有上升很多。
![image](https://github.com/metersphere/metersphere/assets/104960608/f3567900-db9c-464d-bb81-0b3f7f4454bf)
![image](https://github.com/metersphere/metersphere/assets/104960608/ede87f13-2b45-4e3e-99cc-9e136d7fcfdb)
运行场景时
![1719309067258](https://github.com/metersphere/metersphere/assets/104960608/d14ea390-a21d-44a0-a510-920b6b3ecb06)
场景运行完成后
![1719309158861](https://github.com/metersphere/metersphere/assets/104960608/b3e119ea-6867-4e64-8def-710ff08a8ff2)

### 期待的正确结果
希望对接第三方仓库 和 在文件管理处上传的文件，关联到场景里运行时，内存一样低。
_No response_

**Comment by luty2018** [comment]
收到， 感谢反馈， 我们测试一下

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，已提交tapd交由开发人员查看问题，后续版本修复。

**Comment by Somebody-JIAN** [comment]
2.10.17在性能测试这里改了下载方式，已经进行了优化

而且我们对git仓库的设计，**为了支持多个Git仓库，我们不会在服务器的硬盘上维护repository，是加载内存里获取对应的文件**。

然后demo里拿到的是150多M的Git库里的文件

如果2.10.17还不支持的话，就把文件上传到文件管理用， 或者继续加大performance-test服务的内存

不建议使用git repository 维护的大文件。
