### ISSUE TITLE
[BUG]v3 插件一次解析失败，后续上传失败提示插件id 已存在

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31768]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.0.0-ee

### 使用外置数据库

否

### 问题描述

第一次上传自定义插件解析失败后，修改插件再上传就会提示插件id 已存在

### 重现步骤

第一次上传自定义插件解析失败后，修改插件在上传就会提示插件id 已存在
![1718852428219](https://github.com/metersphere/metersphere/assets/145318182/3e48e7cf-4a9b-4814-9ce6-8ebdcaaa1c4b)
![1718852229094](https://github.com/metersphere/metersphere/assets/145318182/c5ebae8a-6a2b-4ce0-9f47-e78d05d5bd54)

### 期待的正确结果

插件解析失败，或者网络超时造成上传失败，可以自动删除缓存文件，无需重启metersphere 服务，继续上传相同插件进行调试

**Comment by 13290445582** [comment]
感谢反馈，会在后续版本修复。

**Comment by 13290445582** [comment]
未再复现过该问题，最新版本还遇到过这个情况嘛。

**Comment by youliyuan-fit2cloud** [comment]
长时间未反馈，关闭该问题，如果再次遇到请重新提issue。
