### ISSUE TITLE
[BUG]建议请求协议名称过长，鼠标聚焦时，可以显示全称

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#31773]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.x-ee

### 使用外置数据库

否

### 问题描述

接口场景，添加自定义请求页面，切换协议时，协议名称过长，鼠标聚焦，无法看到协议全称

### 重现步骤

接口场景，添加自定义请求页面，切换协议时，协议名称过长，鼠标聚焦，无法看到协议全称
![image](https://github.com/metersphere/metersphere/assets/145318182/ab94d2f2-f300-4146-98c4-c6bfb3a00ef6)

### 期待的正确结果

希望鼠标聚焦，悬浮，可以小窗口显示协议名称全称

**Comment by Hyyfit** [comment]
感谢反馈，会在后续版本优化。

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已优化。
