### ISSUE TITLE
[FEATURE]前端编译使用内存过大，本地无法编译通过

### ISSUE THREAD

**Issue by xiaojin2015** [metersphere/metersphere#31784]
### MeterSphere 版本

v3.x

### 联系方式

memoryxjin@163.com , 微信号： 18626872106 津津

### 请描述您的需求或者改进建议

![image](https://github.com/metersphere/metersphere/assets/16068838/8f8c67b0-1840-4740-82cf-956ee3bc2326)
编译使用内存过大，超过2G，本地编译失败

### 请描述你建议的实现方案

建议优化内存使用

**Comment by liuruibin** [comment]
建议加大内存后重试
