### ISSUE TITLE
[BUG]v2.10.15-lts-1e4e1f7版本项目成员及管理员无法查询测试报告，权限有bug

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#31794]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.15-lts-1e4e1f7

### 使用外置数据库

否

### 问题描述

升级前往为v2.10.11-lts版本，对接devops执行测试计划，查询测试报告正常。升级v2.10.15-lts-1e4e1f7后执行测试计划正常，查询报告报错
<img width="963" alt="测试报告查询报错" src="https://github.com/metersphere/metersphere/assets/51410548/7ee5a5c3-2dc1-4798-afb1-337e75b7d009">

查看版本更新日志，v.2.10.14存在fix 查询越权的缺陷，可能引入了问题

### 重现步骤

1、执行测试计划，生成测试报告记录id
2、平台调试接口查询报告状态/track/test/plan/report/status/{id}
![重现步骤接口](https://github.com/metersphere/metersphere/assets/51410548/4313cf2d-b0ac-4868-b09f-aace7c3b49d0)

### 期待的正确结果

项目成员可有权限查询测试报告

**Comment by Hyyfit** [comment]
感谢反馈，会在后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级至v2.10.16版本使用。
