### ISSUE TITLE
[BUG] 性能测试设置了自动停止，还是不停止，一直执行测试任务

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#31793]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

性能测试设置了自动停止，还是不停止，一直执行测试任务

### 重现步骤

1. 性能测试压测前端静态资源文件（包含css、js 等文件），并设置了自动停止，压测时长5分钟
2. 保存执行，发现测试任务不能停止，超过了设置的时间还是一直执行

### 期待的正确结果

设置了自动停止后，测试任务可以自动停止

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/6ce6db4c-05d9-431d-b65a-f572c903f11d)
查看后台Jmeter日志，一直在执行，且服务都健康
<img width="700" alt="1719372693700" src="https://github.com/metersphere/metersphere/assets/50016789/b15d903f-29f2-4ce0-b53c-7890052270f5">

**Comment by luty2018** [comment]
好的， 我们复测一下

**Comment by youliyuan-fit2cloud** [comment]
@spritelyl 你好 ，我们测试环境没有复现，方便把复现的场景发我们试试吗？

**Comment by liuruibin** [comment]
当jmeter容器还running的时候 docker exec -it xxx sh

使用jstack pid > test.dump

用分析工具看看这个dump到底咋回事

**Comment by 13290445582** [comment]
您好，经过测试一个执行时间较长的性能测试，设置自动停止，有复现到未自动停止问题，已提交问题，后续版本修复。

**Comment by 13290445582** [comment]
使用最新的镜像，部署最新的node-controller
增加环境变量 SUMMARY_SAMPLES_ENABLE: 'false'  关闭采样即可
核心原因是dataStreaming干挂了，自动重启了，然后接不上了。这样dataStreaming不容易挂掉，就可以用了。
当数据量过大时，自动停止回收数据也需要时间，不会精确的立马停止，是正常现象，目前已优化，但数据回收所需要的时间也是正常的，所以时间不一定会精确的停止。
