### ISSUE TITLE
MeterSphere v3.0已经支持Python3，关于Python3引入第三方包的操作说明

### ISSUE THREAD

**Issue by berserkerwsc** [metersphere/metersphere#31811]
### 请描述您的问题

想请问一下，接口测试添加后置脚本，使用python脚本 建立ssh链接，做一些操作，我导入paramiko，提示不存在，如何安装paramiko来使用呢？

**Comment by liuruibin** [comment]
什么版本？

**Comment by berserkerwsc** [comment]
v3.0-beta版本

**Comment by berserkerwsc** [comment]
请问一下，这个有什么好的方法可以解决执行python脚本需要引用第三方库的问题吗？感谢

**Comment by liuruibin** [comment]
今天会发布v3.0.1正式版，会有更好的方案

**Comment by berserkerwsc** [comment]
好的，那相关的步骤等版本发布后，可以简单的发一下嘛？

**Comment by liuruibin** [comment]
制作python环境
```
FROM registry.fit2cloud.com/metersphere/python:3.10-alpine
 
RUN pip install requests pinyin
 
VOLUME ["/usr/local/lib/python3.10/site-packages"]
```
使用上面的dockerfile制作镜像 

```
docker build -t python:3.10 .
```

修改task-runner的yml 共享python目录

```
version: "3"
services:
  python:
    container_name: python
    image: python:3.10
    command: sh -c "tail -f /dev/null"  # 保持容器运行
 
  task-runner:
    image: ${MS_IMAGE_PREFIX}/metersphere-ce:${MS_IMAGE_TAG}
    container_name: task-runner
    deploy:
      resources:
        limits:
          memory: ${MS_RUNNER_MEM_LIMIT}
    entrypoint:
      - sh
      - -c
      - |
        sh /shells/task-runner.sh
    environment:
      TOTP_ENABLED: ${MS_TOTP_ENABLED}
      TOTP_SECRET: ${MS_TOTP_SECRET}
    ports:
      - ${MS_TASK_RUNNER_PORT}:8000
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8000" ]
      interval: 6s
      timeout: 5s
      retries: 50
    volumes:
      - ${MS_BASE}/metersphere/logs/task-runner:/opt/metersphere/logs/task-runner
    volumes_from:
      - python
    restart: always
    networks:
      - ms-network

```

重载环境

```
msctl reload
```

**Comment by berserkerwsc** [comment]
FROM registry.fit2cloud.com/metersphere/python:3.10-alpine，这个是必须添加的嘛？我这边是离线环境

**Comment by liuruibin** [comment]
部署task-runner的机器上安装好3.10环境，三方包也一起安装好。通过volume的方式挂载到task-runner的/usr/local/lib/python3.10/site-packages上

**Comment by berserkerwsc** [comment]
![IMG_5588](https://github.com/metersphere/metersphere/assets/172011320/7ccd4064-dc55-4e50-a770-97ab9a4cad3f)
![IMG_5587](https://github.com/metersphere/metersphere/assets/172011320/33210413-9ede-446a-8af5-32a8b53767cc)
![IMG_5586](https://github.com/metersphere/metersphere/assets/172011320/1fec6677-e729-4ea6-8461-2daf4a313ac9)
我这样挂载的，但是明明docker路径下已经有相应的包了，但是执行脚本的时候，还是报错，不知道哪里有问题

**Comment by berserkerwsc** [comment]
版本已经是3.0.1了

**Comment by liuruibin** [comment]
https://github.com/pyca/cryptography/issues/9060 看起来是包版本不匹配导致的

**Comment by berserkerwsc** [comment]
我这边在宿主机上能执行相同的代码，无报错。然后使用接口测试时，后置脚本执行时就报这个错误了，这个可能出现的原因是啥呢？

**Comment by liuruibin** [comment]
具体原因我也不知道，现在给graalpy提了issue https://github.com/oracle/graalpython/issues/404

**Comment by berserkerwsc** [comment]
你们有尝试过这样操作嘛？没有出现这个问题的话，可以告诉我一下使用的库的版本吗？

**Comment by liuruibin** [comment]
> 你们有尝试过这样操作嘛？没有出现这个问题的话，可以告诉我一下使用的库的版本吗？

我们内置python是3.10，安装版本pip install paramiko==2.12.0

**Comment by berserkerwsc** [comment]
我这边也是按照的python3.10.0，并且paramiko已经重新安装成2.12.0版本了，还是仍旧报错之前的错误

**Comment by berserkerwsc** [comment]
![IMG_5589](https://github.com/metersphere/metersphere/assets/172011320/65b7b92d-1d8d-48ec-8b2a-524e62c39f19)
我这边的各个依赖库的版本，和你那边的有什么不一样的地方嘛？

**Comment by liuruibin** [comment]
> ![IMG_5589](https://private-user-images.githubusercontent.com/172011320/344081275-65b7b92d-1d8d-48ec-8b2a-524e62c39f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NjcxNjYsIm5iZiI6MTcxOTU2Njg2NiwicGF0aCI6Ii8xNzIwMTEzMjAvMzQ0MDgxMjc1LTY1YjdiOTJkLTFkOGQtNDhlYy04YjJhLTUyNGU2MmMzOWYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQwOTI3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjA1NTdjZWU2OTM2OTg1ZmFkMGJjNzkzMTk0YWNmMjdiNDJkM2ZkOTYzMDg4ZTA0NjRhMTZlYWU5NDFjZGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-LveDsIpkcpV8T2zRmI9KEZ_VhCJL33jNdftBMaf_-c) 我这边的各个依赖库的版本，和你那边的有什么不一样的地方嘛？

基本一样，我用graalpy本地执行也是同样的错误

**Comment by berserkerwsc** [comment]
metersphere内置的是不是不是python 3.10.0的版本呢？这个能在确认一下嘛？

**Comment by liuruibin** [comment]
> metersphere内置的是不是不是python 3.10.0的版本呢？这个能在确认一下嘛？

<img width="1146" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/5f009a64-492e-4704-b0c4-006244418997">
<img width="1134" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/d9287648-6ba5-4de2-9d01-d6b17c4ca5bc">

3.10.x 小版本影响不大

<img width="834" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/5541640c-9808-425c-8852-53032bf3412a">
上面的是graalpy给的回复

**Comment by berserkerwsc** [comment]
那这边你尝试他上面的版本，还会有问题吗？

**Comment by liuruibin** [comment]
> 那这边你尝试他上面的版本，还会有问题吗？

~~我用graalpy 也是同样的问题。暂时没找到原因~~

**Comment by berserkerwsc** [comment]
> > metersphere内置的是不是不是python 3.10.0的版本呢？这个能在确认一下嘛？
> 
> <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/23045261/344175157-5f009a64-492e-4704-b0c4-006244418997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUxNTctNWYwMDlhNjQtNDkyZS00NzA0LWIwYzQtMDA2MjQ0NDE4OTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjhiMjYxNzNmOTkyMWUxMTQzOGMyMWUxNTY0MmJmMGJiYWJiY2IwM2RiMjIyNWQ4YmViODUzNjc5ODg2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbO1QZP7AnYbJYVX7Rv5nn_qxGjp0D3lQ7O-BGdwynw"> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/23045261/344175229-d9287648-6ba5-4de2-9d01-d6b17c4ca5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUyMjktZDkyODc2NDgtNmJhNS00ZGUyLTlkMDEtZDZiMTdjNGNhNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTMxMGVhODM2ODk3YmEyNzJkNDY2NDJmNmQ0NzU3NDJkZDJkZmM3MmY4MzRjMjExNWY0YjEyNDZmZDVlNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYUP5NxNk1s-40xB1lo5JThyuqfsTBOdJGebawDPF6A">
> 3.10.x 小版本影响不大
> 
> <img alt="image" width="834" src="https://private-user-images.githubusercontent.com/23045261/344179068-5541640c-9808-425c-8852-53032bf3412a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzkwNjgtNTU0MTY0MGMtOTgwOC00MjVjLTg4NTItNTMwMzJiZjM0MTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2Q2ZGNhM2Q3NDA0MjJkNzc3YzBhOTAyNGRhNzZlMmUxNzhkOTNmMTZlYWU3Y2MzOTBhYjNmMTJmOTBhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4gjxlb5dVc3hIUIzPe-cZgyUaKbIvlhTUE2VVkNPpg"> 上面的是graalpy给的回复

![IMG_5591](https://github.com/metersphere/metersphere/assets/172011320/e0b58db0-f802-4cc6-9ba5-a8ffb9d94739)
我这边也按照他回复的安装的版本，也还是不行，还能有其他的办法来解决这个问题嘛？

**Comment by berserkerwsc** [comment]
> > metersphere内置的是不是不是python 3.10.0的版本呢？这个能在确认一下嘛？
> 
> <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/23045261/344175157-5f009a64-492e-4704-b0c4-006244418997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUxNTctNWYwMDlhNjQtNDkyZS00NzA0LWIwYzQtMDA2MjQ0NDE4OTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjhiMjYxNzNmOTkyMWUxMTQzOGMyMWUxNTY0MmJmMGJiYWJiY2IwM2RiMjIyNWQ4YmViODUzNjc5ODg2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbO1QZP7AnYbJYVX7Rv5nn_qxGjp0D3lQ7O-BGdwynw"> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/23045261/344175229-d9287648-6ba5-4de2-9d01-d6b17c4ca5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUyMjktZDkyODc2NDgtNmJhNS00ZGUyLTlkMDEtZDZiMTdjNGNhNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTMxMGVhODM2ODk3YmEyNzJkNDY2NDJmNmQ0NzU3NDJkZDJkZmM3MmY4MzRjMjExNWY0YjEyNDZmZDVlNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYUP5NxNk1s-40xB1lo5JThyuqfsTBOdJGebawDPF6A">
> 3.10.x 小版本影响不大
> 
> <img alt="image" width="834" src="https://private-user-images.githubusercontent.com/23045261/344179068-5541640c-9808-425c-8852-53032bf3412a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzkwNjgtNTU0MTY0MGMtOTgwOC00MjVjLTg4NTItNTMwMzJiZjM0MTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2Q2ZGNhM2Q3NDA0MjJkNzc3YzBhOTAyNGRhNzZlMmUxNzhkOTNmMTZlYWU3Y2MzOTBhYjNmMTJmOTBhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4gjxlb5dVc3hIUIzPe-cZgyUaKbIvlhTUE2VVkNPpg"> 上面的是graalpy给的回复

![IMG_5591](https://github.com/metersphere/metersphere/assets/172011320/e0b58db0-f802-4cc6-9ba5-a8ffb9d94739)
我这边也按照他回复的安装的版本，也还是不行，还能有其他的办法来解决这个问题嘛？

**Comment by liuruibin** [comment]
> > > metersphere内置的是不是不是python 3.10.0的版本呢？这个能在确认一下嘛？
> > 
> > 
> > <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/23045261/344175157-5f009a64-492e-4704-b0c4-006244418997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUxNTctNWYwMDlhNjQtNDkyZS00NzA0LWIwYzQtMDA2MjQ0NDE4OTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjhiMjYxNzNmOTkyMWUxMTQzOGMyMWUxNTY0MmJmMGJiYWJiY2IwM2RiMjIyNWQ4YmViODUzNjc5ODg2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hbO1QZP7AnYbJYVX7Rv5nn_qxGjp0D3lQ7O-BGdwynw"> <img alt="image" width="1134" src="https://private-user-images.githubusercontent.com/23045261/344175229-d9287648-6ba5-4de2-9d01-d6b17c4ca5bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzUyMjktZDkyODc2NDgtNmJhNS00ZGUyLTlkMDEtZDZiMTdjNGNhNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTMxMGVhODM2ODk3YmEyNzJkNDY2NDJmNmQ0NzU3NDJkZDJkZmM3MmY4MzRjMjExNWY0YjEyNDZmZDVlNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYUP5NxNk1s-40xB1lo5JThyuqfsTBOdJGebawDPF6A">
> > 3.10.x 小版本影响不大
> > <img alt="image" width="834" src="https://private-user-images.githubusercontent.com/23045261/344179068-5541640c-9808-425c-8852-53032bf3412a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ2NzUsIm5iZiI6MTcxOTgxNDM3NSwicGF0aCI6Ii8yMzA0NTI2MS8zNDQxNzkwNjgtNTU0MTY0MGMtOTgwOC00MjVjLTg4NTItNTMwMzJiZjM0MTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmN2Q2ZGNhM2Q3NDA0MjJkNzc3YzBhOTAyNGRhNzZlMmUxNzhkOTNmMTZlYWU3Y2MzOTBhYjNmMTJmOTBhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4gjxlb5dVc3hIUIzPe-cZgyUaKbIvlhTUE2VVkNPpg"> 上面的是graalpy给的回复
> 
> ![IMG_5591](https://private-user-images.githubusercontent.com/172011320/344563230-e0b58db0-f802-4cc6-9ba5-a8ffb9d94739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTg1NjMsIm5iZiI6MTcxOTgxODI2MywicGF0aCI6Ii8xNzIwMTEzMjAvMzQ0NTYzMjMwLWUwYjU4ZGIwLWY4MDItNGNjNi05YmE1LWE4ZmZiOWQ5NDczOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzE3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODk5YTA4NTViNDJmZTdiYzZkNWY5ZGY0YzAyYjY0YWE4ZmFhNDI0NjM2MGI5ODZhNGMyYzAwMjQ1MDNmMTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e_QPfIefeIh_FaDKLAGjt5YCa4vWE5pPZMKqNdqEwAQ) 我这边也按照他回复的安装的版本，也还是不行，还能有其他的办法来解决这个问题嘛？

很遗憾，暂时没有方案

**Comment by berserkerwsc** [comment]
好的，那后续还是会持续跟踪解决吧？我这边重新提成bug来跟踪？

**Comment by liuruibin** [comment]
> 好的，那后续还是会持续跟踪解决吧？我这边重新提成bug来跟踪？

我们没有方案，如果graalpy升级的话，我们会先尝试。不确保一定能解决

**Comment by liuruibin** [comment]
> > 那这边你尝试他上面的版本，还会有问题吗？
> 
> ~我用graalpy 也是同样的问题。暂时没找到原因~

原因是我们用alpine当作基础镜像，缺少很多基础的lib，而有些三方包依赖这些lib导致不能正常执行。我们会继续探索

**Comment by berserkerwsc** [comment]
好的，你们加油

**Comment by berserkerwsc** [comment]
我这边又尝试使用subprocess，内置库来进行ssh登录，遇到一个问题，这个docker内访问另外一台linux怎么实现免密登录呢？宿主机到另外一台linux已经实现了免密登录了

**Comment by liuruibin** [comment]
> 我这边又尝试使用subprocess，内置库来进行ssh登录，遇到一个问题，这个docker内访问另外一台linux怎么实现免密登录呢？宿主机到另外一台linux已经实现了免密登录了

docker容器内生成公钥，保存在目标机器上呢

**Comment by berserkerwsc** [comment]
主要进入docker后，执行ssh都没有，没有办法进行操作

**Comment by liuruibin** [comment]
> 主要进入docker后，执行ssh都没有，没有办法进行操作

你可以重新制作一个完整的linux镜像

```
ARG IMG_TAG=v3.x

FROM registry.fit2cloud.com/metersphere/metersphere-ce:${IMG_TAG} as task-runner


FROM registry.fit2cloud.com/metersphere/graalpy-community:3.10

COPY --from=task-runner /metersphere /metersphere
COPY --from=task-runner /task-runner /task-runner
COPY --from=task-runner /result-hub  /result-hub
COPY --from=task-runner /shells      /shells
COPY --from=task-runner /standalone  /standalone
COPY --from=task-runner /deployments /deployments
COPY --from=task-runner /opt/jmeter  /opt/jmeter

RUN yum install -y java-21-openjdk

RUN useradd -m appuser
RUN echo 'appuser:appuser' | chpasswd
```

**Comment by liuruibin** [comment]
制作镜像后替换task-runner的image 部分

进容器里 
1. 切换成appuser用户 
2. 生成一个sshkey
3. 复制到远程服务器上即可

<img width="1148" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/ff9865bf-2da1-42bc-9ea8-b27e038ac4cf">
执行成功
<img width="1238" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/e6a8a027-79d4-45e8-903d-de0529dcce4b">

**Comment by berserkerwsc** [comment]
好的，感谢，随便把docker-compose-task-runner.yml文件也发一下把，我怕弄错了路径

**Comment by liuruibin** [comment]
> 好的，感谢，随便把docker-compose-task-runner.yml文件也发一下把，我怕弄错了路径

```
version: "3"
services:
  task-runner:
    image: registry.fit2cloud.com/metersphere/task-runner:v3.x-python
    container_name: task-runner
      #deploy:
      #  resources:
      #    limits:
      #      memory: ${MS_RUNNER_MEM_LIMIT}
    entrypoint:
      - sh
      - -c
      - |
        sh /shells/task-runner.sh
    environment:
      TOTP_ENABLED: ${MS_TOTP_ENABLED}
      TOTP_SECRET: ${MS_TOTP_SECRET}
      PYTHONPATH: '/app/graalenv/lib/python3.10/site-packages'
    ports:
      - ${MS_TASK_RUNNER_PORT}:8000
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/8000"  ]
      interval: 6s
      timeout: 5s
      retries: 50
    volumes:
      - ${MS_BASE}/metersphere/logs/task-runner:/opt/metersphere/logs/task-runner
    restart: always
    networks:
      - ms-network


```

这个镜像包括了python环境，如果需要安装外部的包可以 `docker exec -it task-runner bash` 进容器执行 `pip install`

**Comment by berserkerwsc** [comment]
好的，那进入docker 内，安装paramiko可以用了吗？我这边试了一下，不行

**Comment by liuruibin** [comment]
> 好的，那进入docker 内，安装paramiko可以用了吗？我这边试了一下，不行

确实不行，还有其他方面的限制
<img width="900" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/ae3c03cb-fabc-43d5-b78b-69f7ad270cdd">

**Comment by kennykai** [comment]
咨询下3.0版本的返回heards 参数里面没有set-Cookie参数了要怎么设置呢？ @liuruibin

**Comment by Stephen0910** [comment]
官方啊， 置顶啊，写的是个啥。 专业一点？
