### ISSUE TITLE
[FEATURE]3.x版本，helm安装到k8s环境的脚本什么时候能支持？

### ISSUE THREAD

**Issue by hclzm** [metersphere/metersphere#31821]
### MeterSphere 版本

v3.0.1

### 联系方式

微信群metersphere交流群58 

### 请描述您的需求或者改进建议

针对v3.x的版本在k8s环境部署，什么时候能提供helm的安装包呢？另外，v3.0.1的镜像什么时候能提供呢？谢谢

**Comment by liuruibin** [comment]
短期内不再提供k8s上的部署，我们会在合适的时机来做这个功能

**Comment by hclzm** [comment]
> 短期内不再提供k8s上的部署，我们会在合适的时机来做这个功能

好吧，另外多实例部署，现在平台会有什么问题或注意的配置事项没？

**Comment by liuruibin** [comment]
中间件链接保持一致
