### ISSUE TITLE
[BUG]【测试用例】脑图模式下，剪切用例到其他模块下粘贴，保存成功后，点击用例详情，页面提示"功能用例不存在"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31827]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

【测试用例】脑图模式下，剪切用例到其他模块下粘贴，保存成功后，点击用例详情，页面提示"功能用例不存在"

### 重现步骤

【测试用例】脑图模式下，剪切用例到其他模块下粘贴，保存成功后，点击用例详情，页面提示"功能用例不存在"
![1719546311123](https://github.com/metersphere/metersphere/assets/104960608/f1ee0ec0-736e-423c-9fc9-50cda29d517c)
![1719546342478](https://github.com/metersphere/metersphere/assets/104960608/e89786c5-78a1-4a80-860e-35a3588c9eff)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，请把控制台日志和后台日志都发一下？是否还有其他特殊操作？

**Comment by youliyuan-fit2cloud** [comment]
已复现，但是步骤不太一样，如果有请补充说明其他操作步骤。谢谢～

**Comment by 2lipan** [comment]
复现步骤就如缺陷描述一样。
https://github.com/metersphere/metersphere/assets/104960608/5bb6d9a0-909c-4c54-a041-40cd7ce7cfcc

**Comment by youliyuan-fit2cloud** [comment]
> 复现步骤就如缺陷描述一样。 https://github.com/metersphere/metersphere/assets/104960608/5bb6d9a0-909c-4c54-a041-40cd7ce7cfcc
感谢反馈，同类问题，下个版本修复。
ps：剪切-复制后，不保存，直接查看详情后再保存不会出现异常

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已修复。
