### ISSUE TITLE
[BUG]项目级别的用户组权限设置未生效

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#31836]
### 联系方式

songbing@fit2cloud.com

### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

以下的截图，有详细的操作过程
![WechatIMG173](https://github.com/metersphere/metersphere/assets/18387151/db5a061e-6a93-4b07-b815-ae8d626be746)
![WechatIMG174](https://github.com/metersphere/metersphere/assets/18387151/1c55bdde-a7f8-4cb0-87d2-49f3dee512a3)
![WechatIMG595](https://github.com/metersphere/metersphere/assets/18387151/508d629f-0e59-4330-908a-b265d365c22b)

### 重现步骤

同上

### 期待的正确结果

当项目级别的用户组权限，只设置了“接口测试”模块的权限，此用户组下的用户登录后，应该只能看到“接口测试”模块

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/a8d8e365-34f4-486d-b754-40bb0fc90473)

这不是还有项目成员的用户组权限吗？

**Comment by songbing0312** [comment]
![WechatIMG596](https://github.com/metersphere/metersphere/assets/18387151/8800eaa2-8de7-4367-8155-daabcc8f2e82)
![WechatIMG597](https://github.com/metersphere/metersphere/assets/18387151/fd86af32-acd9-449e-bd8f-50880c651a03)

**Comment by youliyuan-fit2cloud** [comment]
项目的任何权限都没也不行。。。至少开启项目的查询权限。
![image](https://github.com/metersphere/metersphere/assets/54612864/0582c1df-3cd0-426b-9ca2-f3ba86985cbe)

**Comment by songbing0312** [comment]
![WechatIMG598](https://github.com/metersphere/metersphere/assets/18387151/b1715a66-3147-48ea-bcaa-b355ff740590)
![WechatIMG599](https://github.com/metersphere/metersphere/assets/18387151/de80d16e-4d86-43e8-ad27-d5b5fbaf6309)
在用户组权限只加上项目的“查询”权限，就可以正常使用了，谢谢
