### ISSUE TITLE
[BUG]测试计划中场景处于 Pending 状态，但是测试计划已经结束

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#31831]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.6

### 使用外置数据库

否

### 问题描述

<img width="956" alt="image" src="https://github.com/metersphere/metersphere/assets/30038088/352c15f2-24a5-4a8a-8ae7-f41361816a26">

### 重现步骤

资源池使用 k8s 资源池

node-controller  的 iofo 和 ms-jmeter-run.log 都正常，且显示已经执行完成，并推送kafka 完成。「同步发送报告信息到KAFKA完成」
api-test 的 ms-jmeter-run.log 如下
<img width="1440" alt="image" src="https://github.com/metersphere/metersphere/assets/30038088/6319340e-098e-408d-a088-872b12a021fb">

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题在最近发布的版本中未能复现，请将必现的这个接口场景用例发我们看一下，方便快速复现。
ps：当前您使用的版本是v2.10.6-lts，距离最新版本有十个版本了，即使要解决我们也得基于 最新已发布的版本解决，所以建议升级到最新版本后尝试复现一下，感谢理解和支持。
