### ISSUE TITLE
[BUG]【测试计划】计划详情里，点击复制按钮，出现的是更新计划的页面，这与编辑按钮打开的页面一样

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31835]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

【测试计划】计划详情里，点击复制按钮，出现的是更新计划的页面，这与编辑按钮打开的页面一样

### 重现步骤

【测试计划】计划详情里，点击复制按钮，出现的是更新计划的页面，这与编辑按钮打开的页面一样
![image](https://github.com/metersphere/metersphere/assets/104960608/8898bf67-dd12-4076-957c-26ebcb666ed0)
![image](https://github.com/metersphere/metersphere/assets/104960608/b9325fe1-4f35-48c5-8340-409a68e732c3)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这里的“复制”下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已修复。
