### ISSUE TITLE
[FEATURE]【测试计划】详情页面，点击生成报告没触发用例执行，如果该计划里 既有 接口用例又有场景用例，执行该测试计划时，需要返回到计划列表页面，感觉太麻烦了。希望能在测试计划详情页面，“生成报告”可以触发执行或者加个"执行"按钮。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31838]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

【测试计划】详情页面，点击生成报告没触发用例执行，如果该计划里 既有 接口用例又有场景用例，执行该测试计划时，需要返回到计划列表页面，感觉太麻烦了。希望能在测试计划详情页面，“生成报告”可以触发执行或者加个"执行"按钮。

### 重现步骤

【测试计划】详情页面，点击生成报告没触发用例执行，如果该计划里 既有 接口用例又有场景用例，执行该测试计划时，需要返回到计划列表页面，感觉太麻烦了。希望能在测试计划详情页面，“生成报告”可以触发执行或者加个"执行"按钮。
![image](https://github.com/metersphere/metersphere/assets/104960608/64368c3b-e874-4636-b74e-d7b5830c7653)

![image](https://github.com/metersphere/metersphere/assets/104960608/6bb87f66-9e1c-4b07-87a5-6a6164ec0228)

**Comment by Somebody-JIAN** [comment]
这不是Bug吧。 我们交互方面的设计方式是这样的。

我看了您描述的，感觉您说的这些其实是一种需求。这种情况下提Feature更合适。 

因为不同的标题我们会对应不同的处理人。如果需求提成了Bug，会走错流程，导致您的需求可能会在很久之后才被看到

**Comment by Hyyfit** [comment]
已规划在详情页内直接执行的功能，将在后续的版本里实现。
