### ISSUE TITLE
[BUG]【测试计划】选择并行进行保存，提示保存成功后，还是显示串行。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31839]
### MeterSphere 版本

v3

### 使用外置数据库

否

### 问题描述

【测试计划】选择并行进行保存，提示保存成功后，还是显示串行。

### 重现步骤

【测试计划】选择并行进行保存，提示保存成功后，还是显示串行。
![image](https://github.com/metersphere/metersphere/assets/104960608/15b5c597-5a98-4472-8d9b-154a602e57ac)
![image](https://github.com/metersphere/metersphere/assets/104960608/d6fbd670-a77c-4cc7-9a0a-3ca7d607dc30)

**Comment by Somebody-JIAN** [comment]
![image](https://github.com/metersphere/metersphere/assets/75963100/88e5a016-2f1f-4024-b585-0b6e28130a5a)
把这里关了就可以了。

**Comment by 2lipan** [comment]
试了，关掉，也是一样  不太行。
![image](https://github.com/metersphere/metersphere/assets/104960608/337db3fe-2052-4875-94e1-9e20abf4b148)
![image](https://github.com/metersphere/metersphere/assets/104960608/a30a5b9f-c36c-4adb-a2b8-0b1d19fb2629)

**Comment by youliyuan-fit2cloud** [comment]
已复现，下个版本修复，感谢反馈～

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已修复。
