### ISSUE TITLE
[BUG]接口调试时，front/api/debug/debug这个接口是有响应，但是没有我的接口请求数据，前端还在转圈

### ISSUE THREAD

**Issue by wangbingfei** [metersphere/metersphere#31862]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

接口调试时，front/api/debug/debug这个接口是有响应，但是没有我的接口请求数据，前端还在转圈

### 重现步骤

我的部署场景为：task-runner和其他的redis、kafka等所有的都部署在服务器，前后端部署在本地，单个接口调试时出现该问题
![Uploading 1719905275569.jpg…]()

**Comment by youliyuan-fit2cloud** [comment]
你好，截图无法查看，请重新上传

**Comment by fit2-zhao** [comment]
task-runner 需要从 metersphere-backend 服务拉取执行脚本，所以至少需要保证 task-runner 能访问到 metersphere-backend 服务。

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
