### ISSUE TITLE
[BUG]项目管理中的缺陷配置，提示图片无法看清

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#31876]
### 联系方式

15275908957

### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

项目管理中的缺陷配置，提示图片无法看清。

### 重现步骤

在项目的应用设置里，使用缺陷管理或测试用例的关联需求，给出的提示图片看不清且无法放大，插件中是可以看清的。
配置项目图：
![image](https://github.com/metersphere/metersphere/assets/66937739/353faa28-79c7-4b75-b332-0b553f9ca89b)
插件里原图：
![image](https://github.com/metersphere/metersphere/assets/66937739/757be78e-fd81-4cf5-8dd5-54e4d5c482c8)

### 期待的正确结果

提供可以放大的功能，或者点击时，使用原图全屏展示。

**Comment by youliyuan-fit2cloud** [comment]
说的有道理，后续版本优化下。
