### ISSUE TITLE
[BUG]metershpere 插件1.2.8版本在intellij中填写key及密钥后，测试验证失败

### ISSUE THREAD

**Issue by hclzm** [metersphere/metersphere#31874]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

是

### 问题描述

在metersphere 平台上本地验证是通过的，我看平台上是把这个上报的api接口是转发到后端8000端口，没有任何请求的url前缀；
<img width="571" alt="image" src="https://github.com/metersphere/metersphere/assets/11730466/a4f65251-cc55-4c25-a452-88f3d7a6b5a3">
在intellij里调用是失败的，根据抓包结果，调用的是currentUser这个接口，错误信息如下：{"code":-1,"message":"100500","data":null,"messageDetail":"No static resource currentUser."}；接口返回http500错误; 是现在的插件还不支持v3.0.1吗？

### 重现步骤

通过nginx配置域名，定义一个前缀sync,通过这个http://xxx.xxx.com.cn/sync 重定向到服务端8000端口，同时把sync前缀在nginx转发时去除；在metersphere搭建的平台本地验证是通过的，在intellij里安装插件1.2.8版本，验证失败。

### 相关日志输出

```shell
这是根据抓包工具抓的intellij发出的请求报文及错误信息：
010.000.018.086.44626-172.030.010.003.08000: GET /currentUser HTTP/1.0
Host: metersphere.chinahuanong.com.cn
X-Real-IP: 10.0.18.89
X-Forwarded-For: 10.0.22.131, 10.0.22.16, 10.0.18.89
Connection: close
Accept: application/json;charset=UTF-8
accessKey: 0dPoL6WZO1GoyRS4
signature: Z+udSnDHBYRiirqwX8AGXZjiiL/t+t49e4DuG0sZUz1ornecK1r8NZCaBLZ8n/PBqHxXvccoRrFstPvXZjTY4wWO7USX8oG/rGAJ43za1k0=
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Accept-Encoding: gzip,deflate


172.030.010.003.08000-010.000.018.086.44626: HTTP/1.1 500 Server Error
Date: Tue, 02 Jul 2024 15:21:51 GMT
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json;charset=utf-8

{"code":-1,"message":"100500","data":null,"messageDetail":"No static resource currentUser."}
```

**Comment by fit2-zhao** [comment]
目前 idea 插件只适配 v2 版本，暂时不适配 v3 版本，请关注后续插件更新。
