### ISSUE TITLE
[BUG]新增用户登录后无法找到被授权的项目

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#31871]
### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

系统管理员新添加用户后，切换为无痕浏览器，用新用户在同一电脑端登录，登录后无法查看该新用户被授权的项目，需要用该新用户切换到系统管理中的项目管理，然后通过项目列表【进入项目】后，方能从切换项目中找到新用户授权的项目

### 重现步骤

步骤一：admin用户登录创建新用户test1，并为其设置为系统管理员角色，同时通过项目列表将test1用户添加到项目A中；
步骤二：同一台电脑用谷歌无痕浏览器的test1用户登录平台，登录后无法通过项目切换列表找到新授权的项目A；
步骤三：test1用户在系统管理中的项目列表处点击【进入项目】，切换进入了该项目。
步骤四：再重新通过项目切换列表切换项目，发现列表正常了

### 期待的正确结果

新用户被授权后首次登录能够通过项目列表直接切换项目。

### 相关日志输出

```shell
无
```

### 附加信息

项目切换列表附图：
<img width="472" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/3962b2c9-6494-47d3-aaca-8a704f98aea6">

进入项目附图：
<img width="1408" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/f2291105-9227-4cc1-be9c-182b4e16cc47">

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。如果新建的用户所属的用户组是系统管理员，默认是有所有项目的权限的。
建议查看该用户所属用户组是否是系统管理员，然后确认下是否有网络延时？刷新网页 ？稍等1分钟之后再看看，感谢理解和支持。

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。
