### ISSUE TITLE
[QUESTION]新增误报规则最后面的开关按钮时干什么的？

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#31872]
### 请描述您的问题

如下图所示：添加新增误报规则，最后的开关按钮时是否启用的意思吗？
![image](https://github.com/metersphere/metersphere/assets/60059766/e596b9e6-7115-4b73-be27-a75b1633c022)

**Comment by luty2018** [comment]
开关开启，规则就会生效，接口执行时匹配到这个响应了就会处理成误报，开关关闭，规则就不会生效。
