### ISSUE TITLE
[BUG]测试跟踪删除模块里面的测试计划，项目日志记录里面没有操作记录

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#31888]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

测试跟踪里面，操作模块里面的删除，项目日志记录里面没有删除的操作记录

### 重现步骤

操作模块里面的删除，删除成功，但是查看项目日志记录，没有删除的操作记录

### 期待的正确结果

操作模块里面的删除，删除成功，但是查看项目日志记录，有删除的操作记录，这样方便排查删除情况

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/1a7ad363-6122-48c6-a022-70c32639007e)
![image](https://github.com/metersphere/metersphere/assets/50016789/9d74fe55-2ef9-44a3-a9d4-19c13242cd5f)

**Comment by 13290445582** [comment]
您好，V2这里未记录到日志，暂时未计划补充操作日志记录，建议使用V3版本。
