### ISSUE TITLE
[BUG]数据库备份还原报错

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#31889]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

使用mysqldump命令或者手动通过navicat工具导出，然后再还原报错，备份脚本未更改过，v2.10.14-lts版本之前一直正常。
![749c31e5f0dd34e1863896d1163e73d](https://github.com/metersphere/metersphere/assets/37204403/2567955b-e1fb-405b-a6be-d9563d2fd598)

![1720000397994](https://github.com/metersphere/metersphere/assets/37204403/c97294f5-968d-4563-8a37-57fe63e7c11f)

### 重现步骤

使用mysqldump命令或者手动通过navicat工具导出，进行数据备份，备份成功后再还原

**Comment by 13290445582** [comment]
您好，可参考我们提供的帮助文档重新试下解决问题。https://metersphere.io/docs/v2.x/installation/backup_data/

**Comment by SloanGao** [comment]
> 您好，可参考我们提供的帮助文档重新试下解决问题。https://metersphere.io/docs/v2.x/installation/backup_data/

已按照官方文檔重寫備份腳本，結果還是不能還原
![image](https://github.com/metersphere/metersphere/assets/37204403/37bfa1c3-cbe0-4642-ac67-24dda787ad26)

**Comment by 13290445582** [comment]
您好，官方提供的文档是没有问题的，请根据报错日志自行检查是否为表结构问题或数据问题。
