### ISSUE TITLE
[BUG]UI测试下发场景复杂且庞大的脚本时服务崩溃

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#31885]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.16

### 使用外置数据库

否

### 问题描述

下发UI测试场景时，ui-test服务崩溃。

### 重现步骤

1、创建一个大约700个步骤的场景，其中包含多个打开网页，切换窗口，逻辑判断控制等
2、执行该场景，使用docker stats发现ui-test升至 900%左右，然后ui-test崩溃重启
3、查看error.log 
![image](https://github.com/metersphere/metersphere/assets/66937739/f5e9c165-b45f-43bf-994a-e53579cb0b7f)

### 期待的正确结果

可以正常执行

**Comment by 13290445582** [comment]
您好，劳烦将该场景导出提供下，以便于复现该情况。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
