### ISSUE TITLE
MeterSphere v3.0 beta版本 配置了群机器人后，提了缺陷后无法通过机器人@到相关的处理缺陷的人，只能指定一个人不是很灵活

### ISSUE THREAD

**Issue by yaowenjie0329** [metersphere/metersphere#31884]
### MeterSphere 版本

MeterSphere v3.0 beta版本

### 请描述您的需求或者改进建议

MeterSphere v3.0 beta版本 配置了群机器人后，提了缺陷后无法通过机器人@到相关的处理缺陷的人，没有这个功能现在，只能指定一个人不是很灵活

**Comment by luty2018** [comment]
我们已经规划了，会在v3.2版本增加处理人选项

**Comment by 13290445582** [comment]
您好，需求已实现，V3.2.0已发布，请升级使用。

**Comment by yaowenjie0329** [comment]
更新到最新的了，但是这个需求没有实现。

**Comment by yaowenjie0329** [comment]
![image](https://github.com/user-attachments/assets/95ed8eab-0118-4388-bb3d-caad200f160a)

**Comment by 13290445582** [comment]
创建和同步缺陷是不会有这个字段通知的，更新/删除/评论才会有处理人字段通知。
<img width="820" alt="image" src="https://github.com/user-attachments/assets/3ce35561-96de-4aa0-b03f-e8529f1ebb90">
