### ISSUE TITLE
[BUG]【测试计划】测试计划里有场景用例，运行测试计划，消息中心处没有显示 场景任务。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31895]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【测试计划】测试计划里有场景用例，运行测试计划，消息中心处没有显示 场景任务。

### 重现步骤

【测试计划】测试计划里有场景用例，运行测试计划，消息中心处没有显示 场景任务。
![image](https://github.com/metersphere/metersphere/assets/104960608/574bf309-08f0-4b01-9a8e-04597609e6ab)
![image](https://github.com/metersphere/metersphere/assets/104960608/e902f984-376b-416a-a344-96b4966064ae)

**Comment by 13290445582** [comment]
您好，本地环境未复现该问题，在你的环境上看起来确实是未显示，建议使用新的其他环境再测试下。

**Comment by 13290445582** [comment]
非问题，已在该环境测试。
