### ISSUE TITLE
【接口定义】api修改请求头的值，点击保存 case同步更新，打开case，发现值并没有更新。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31903]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【接口定义】api修改请求头的值，点击保存 case同步更新，打开case，发现值并没有更新。

### 重现步骤

【接口定义】api修改请求头的值，点击保存 case同步更新，打开case，发现值并没有更新。
![image](https://github.com/metersphere/metersphere/assets/104960608/b3ef82d7-d346-47c4-a4ae-cd2a6989eb36)
![image](https://github.com/metersphere/metersphere/assets/104960608/55672e48-548d-4a1e-9b70-b8c7836c707b)
![image](https://github.com/metersphere/metersphere/assets/104960608/9bda4dc0-2c79-4413-a584-646a9e461422)

api修改请求参数值，同步更新后，case里还是之前的值
![image](https://github.com/metersphere/metersphere/assets/104960608/6c4b85d9-606e-49c1-817e-93d057960457)
![image](https://github.com/metersphere/metersphere/assets/104960608/bbc0e7f5-a1c1-447d-a10b-541ffd053464)

**Comment by 13290445582** [comment]
您好，当前设计逻辑是：需要修改请求参数名称和值，才会覆盖，仅修改参数值不修改参数名称，不会覆盖到CASE，感谢理解。
