### ISSUE TITLE
[v3.x]不支持场景用例的设计

### ISSUE THREAD

**Issue by huanrenwang** [metersphere/metersphere#31912]
### MeterSphere 版本

v3.0.1

### 联系方式

whrgxl8687@126.com

### 请描述您的需求或者改进建议

测试用例这块儿没有场景用例设计的概念，会影响用例的管理。

**Comment by luty2018** [comment]
v3也是有场景的，对应v2的接口自动化。
不知道您具体是说什么功能不支持？

**Comment by huanrenwang** [comment]
您好，不是自动化，是要写场景测试用例
















在 2024-07-05 11:02:42，"LuoTing" ***@***.***> 写道：

v3也是有场景的，对应v2的接口自动化。
不知道您具体是说什么功能不支持？

**Comment by luty2018** [comment]
请您描述一下您期待的功能，谢谢！

**Comment by huanrenwang** [comment]
我期待的功能是这样的,例如我有一个购物的场景。那我就可以设计如下的场景用例
①登录购物网站
②选择商品
③下单
④支付
⑤订单完成返回
以上①~⑤是一个场景，以目前我们用例以模块这种管理的如果组合场景用例的话就太难了

**Comment by huanrenwang** [comment]
我在issue 里面回复您了。










在 2024-07-18 14:37:33，"LuoTing" ***@***.***> 写道：

请您描述一下您期待的功能，谢谢！

**Comment by luty2018** [comment]
模块的命名可以自定义的，您不一定要当模块使用的，或者您有什么更好的建议吗？

**Comment by Hyyfit** [comment]
用例的管理 还是通过模块来进行管理，当某次迭代，需要覆盖购物场景的时候，可以通过选择具体的用例来组合覆盖，这样可以满足你的需求吗？

![image](https://github.com/user-attachments/assets/44451dc1-ba91-4e56-afb0-8dd03e006b1a)
