### ISSUE TITLE
[BUG]修改API时，保存&同步设置功能优化

### ISSUE THREAD

**Issue by 15275908957** [metersphere/metersphere#31918]
### 联系方式

15275908957

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

修改API时，如果有大量的case，需要进行同步，但是在保存&同步设置，有个删除用例中无法与API文档对应的参数，这个默认是选中的，这相当于默认替用户做了删除参数的设置，在实际使用中，经常因为漏取消掉设置，导致大量的case做了删除参数，建议改为默认不勾选。
![image](https://github.com/metersphere/metersphere/assets/66937739/4755ada0-1b52-4caa-9cab-8efb2c333c45)

### 重现步骤

默认不勾选删除参数

**Comment by youliyuan-fit2cloud** [comment]
感谢您的建议，后续版本会优化一下。

**Comment by 13290445582** [comment]
您好，v2.10.21版本已修复，请升级。历史数据不处理。
