### ISSUE TITLE
建议可以配置功能用例脑图模式打开时只显示当前模块的下级节点

### ISSUE THREAD

**Issue by heavenlyye** [metersphere/metersphere#31937]
### MeterSphere 版本

v2.10.11

### 联系方式

QQ：357861578

### 请描述您的需求或者改进建议

目前以脑力模式打开功能用例，默认展开显示当前模块下级、下下级等所有子节点，不方便查看该模块下用例概况

### 请描述你建议的实现方案

建议可以配置显示当前节点下的几级节点

### 附加信息

没有上传截图的按钮

**Comment by heavenlyye** [comment]
![TestCase](https://github.com/metersphere/metersphere/assets/130725706/e81bec21-273c-4757-a2f7-eea3643c29b3)

**Comment by Hyyfit** [comment]
v3.1 已覆盖。
默认展示模块下的节点，用例也只展示到用例名称。需要手动点击用例的展开，才会展示用例的步骤及预期结果；
