### ISSUE TITLE
[FEATURE] UI 测试模块，当步骤错误处理设置为“忽略异常并继续执行”，可以自定义报告中该步骤不计入失败

### ISSUE THREAD

**Issue by shimengqiao** [metersphere/metersphere#31943]
### MeterSphere 版本

v2.10.13-lts

### 联系方式

shimengqiao

### 请描述您的需求或者改进建议

1、在用例的后置操作-错误处理中，修改为“忽略异常并继续执行”
![image](https://github.com/metersphere/metersphere/assets/104493699/c457dfed-dd96-43be-b6bd-3fd34aec2e1c)
2、执行用例，如果该步骤失败了，在测试报告中改步骤不计入失败用例
![image](https://github.com/metersphere/metersphere/assets/104493699/8b961854-337a-44a2-bc12-c99affabb3dd)

**Comment by luty2018** [comment]
这个不是通用需求。不予支持。
