### ISSUE TITLE
[BUG]定义及调试更新请求参数后，未直接关闭该接口，重新打开请求参数不更新

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#31958]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

定义及调试更新请求参数后，未直接关闭该接口，重新打开请求参数不更新;关闭该定义或者调试，重新打开后才可以查看更新后的内容

### 重现步骤

如附件内容

### 附加信息

https://github.com/metersphere/metersphere/assets/32027713/0c96ccef-85f5-4115-b1b4-01bc8cc46846

**Comment by fit2-zhao** [comment]
已经修复此问题：https://github.com/metersphere/metersphere/commit/4ed3cf4ee2b60a9ac2e270f92e14f0319e16b871

**Comment by youliyuan-fit2cloud** [comment]
v3.1 中已修复。
