### ISSUE TITLE
[BUG]swagger导入的接口，第一次打开该接口的编辑页面的“Header”和“QUERY”不会显示参数

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#31950]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

swagger导入的接口，第一次打开该接口的编辑页面的“Header”和“QUERY”不会显示参数，需要手动点击一下“QUERY”和“HEADER”才会显示具体的参数内容

### 重现步骤

1、导入swagger接口
2、编辑某个带有header和query参数的接口
3、多次点击“HEADER”和"QUERY"，观察现象

### 附加信息

操作如下：

https://github.com/metersphere/metersphere/assets/32027713/e7677ad8-1e5b-40a9-90d3-e8ff2502e3f5

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by 13290445582** [comment]
您好，v2.10.21版本已修复，请升级。
