### ISSUE TITLE
【测试跟踪】用例根据标签进行筛选，选择筛选后的数据，全选所有页，点击移动到其他目录，页面提示保存成功，但实际并没有移动。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#31979]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】用例根据标签进行筛选，选择筛选后的数据，全选所有页，点击移动到其他目录，页面提示保存成功，但实际并没有移动。

### 重现步骤

【测试跟踪】用例根据标签进行筛选，选择筛选后的数据，全选所有页，点击移动到其他目录，页面提示保存成功，但实际并没有移动。
![image](https://github.com/metersphere/metersphere/assets/104960608/dc808e75-8a0f-45ea-9af1-4c7e6506de94)
![image](https://github.com/metersphere/metersphere/assets/104960608/b0e2a151-9958-400b-a6fe-12a31963d61e)
![image](https://github.com/metersphere/metersphere/assets/104960608/0a6626dd-cbed-4238-ad0e-fe14d76cc02a)
![image](https://github.com/metersphere/metersphere/assets/104960608/98e4545e-7abd-47ea-b473-8a837e732874)

**Comment by 13290445582** [comment]
您好，已规划至v2.10.17版本新需求。

**Comment by 13290445582** [comment]
您好，已解决问题。请升级v2.10.17版本使用。
