### ISSUE TITLE
[BUG] 提取参数获取的数据里有转义符“\”，在下面的接口引用自动去掉了“\”

### ISSUE THREAD

**Issue by H-loyal** [metersphere/metersphere#31971]
### 联系方式

MeterSphere 交流群68、愿兮、huangz@hustcad.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

接口自动化提取参数获取到的数据包含转义字符“\”，下面的接口引用变量自动去掉了转义字符“\”，如图：
![image](https://github.com/metersphere/metersphere/assets/175104132/91fbbad1-e86b-4934-8cfc-cb234f9503d6)

### 重现步骤

1、提取参数获取到的数据包含转义字符“\”;
2、下面的接口引用提取的参数。

### 期待的正确结果

提取到的值不应该去掉转义字符

**Comment by youliyuan-fit2cloud** [comment]
你好，这个情况是提取时显示了转义字符（按逻辑不应该显示），实际上使用不需要转义字符。这样处理是正确的。在JsonPath提取的显示转义字符问题我们在V3版本做了优化。感谢理解和支持。

**Comment by H-loyal** [comment]
但是我们下一个接口的入参需要传转义字符，不然就会报错，这种情况需要怎么处理呢？

**Comment by youliyuan-fit2cloud** [comment]
可以使用正则表达方提取出来再使用。

**Comment by H-loyal** [comment]
已解决，谢谢。
