### ISSUE TITLE
[BUG]创建bug的时候填写的联接的问题字段，关联对应jira，jira必须用我的账号打卡一下才能搜得到

### ISSUE THREAD

**Issue by sara199119** [metersphere/metersphere#31981]
### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

否

### 问题描述

[BUG]创建bug的时候填写的联接的问题字段，关联对应jira，jira必须用我的账号打卡一下才能搜得到

### 重现步骤

[BUG]创建bug的时候填写的联接的问题字段，关联对应jira，jira必须用我的账号打卡一下才能搜得到，如图，要在jira平台上打开一下752这个jira才能在ms上搜索到
![ms1](https://github.com/metersphere/metersphere/assets/77042928/0a995a22-2dd9-4288-a117-41b1fd0f6431)
![ms2](https://github.com/metersphere/metersphere/assets/77042928/431569e6-4750-431f-9a48-e71ea4e64868)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题。Jira版本是多少？Jira的缺陷是刚刚创建的吗？同步缺陷下试试是否还会出现？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，故关闭该问题，如果有新发现或问题请重新提issue。感谢理解和支持。

**Comment by sara199119** [comment]
JIRA v7.6.1

不是刚创建的，同步缺陷后也还是有问题

在 2024-07-10 14:20:08，"MatataYou" ***@***.***> 写道：

你好，没有复现该问题。Jira版本是多少？Jira的缺陷是刚刚创建的吗？同步缺陷下试试是否还会出现？
