### ISSUE TITLE
[QUESTION]如果已经导入了接口，请问如何再进行url去重？

### ISSUE THREAD

**Issue by damonwong19990909** [metersphere/metersphere#31986]
### 请描述您的问题

如果已经导入了接口定义，如何再去进行url去重？

**Comment by luty2018** [comment]
使用的哪个版本？
导入时会提供覆盖模式，如果选择了覆盖，会根据URL去覆盖，如果选择不覆盖，则不会导入。

**Comment by damonwong19990909** [comment]
版本:   v2.10.14-lts-a7298117
目前遇到的问题是，选择了不覆盖，已经全部导入完成，现在需要对已经导入的接口进行去重，有解决方案吗？

**Comment by luty2018** [comment]
只能是在数据库层面操作了。
