### ISSUE TITLE
[Feature]导出附件时候，ID带有超级链接

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#31996]
### MeterSphere 版本

2.10.16

### 联系方式

13735892260

### 请描述您的需求或者改进建议

导出测试用例时候，表格中的 ID 有超级链接，点击可以跳转到平台对应的地方

**Comment by youliyuan-fit2cloud** [comment]
你好，按照这个描述没有复现问题。是导出功能用例Excel格式，ID是超链接？
方便把导出文件发一下？也可以把文件内容截图看一下。

**Comment by hztony** [comment]
是导出的 csv 表格，ID 那列有超级链接，这样看表的人，点那个 ID 就可以快速定位到平台的某条用例里

**Comment by hztony** [comment]
是一个需求，不是 bug

**Comment by luty2018** [comment]
好的， 感谢反馈， 这个需求我们会规划到v3.2

**Comment by 13290445582** [comment]
您好，需求已实现，V3.2.0已发布，请升级使用。
