### ISSUE TITLE
[BUG]公共脚本测试时，报错‘参数校验失败’

### ISSUE THREAD

**Issue by changxuejie123445667** [metersphere/metersphere#32007]
### 联系方式

63

### MeterSphere 版本

v3.0.1-080e6767

### 使用外置数据库

否

### 问题描述

设置了一个公共脚本，用来生成随机姓名。
公共脚本测试时报错‘参数校验失败’
这个公共脚本的变量没有生效，目前无法引用生成随机姓名

### 重现步骤

1. 创建一个公共脚本，引用随机生成姓名的函数
2. 进入该脚本页面，点击测试

### 期待的正确结果

1. 成功生成该脚本运行结果，不会报错
2. 项目内可以成功引用该脚本

**Comment by liuruibin** [comment]
具体脚本内容呢？

**Comment by changxuejie123445667** [comment]
设置一个公共脚本，用来生成随机姓名。
公共脚本测试时报错‘参数校验失败’
这个公共脚本的变量没有生效，目前无法引用生成随机姓名

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Jul 10, 2024 05:41 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] [BUG]公共脚本测试时，报错‘参数校验失败’ (Issue #32007)

&nbsp;



 
具体脚本内容呢？

**Comment by youliyuan-fit2cloud** [comment]
你好，我们自己写了类似生成随机姓名的公共脚本，测试成功。
方便把你写的脚本贴上出来吗？看下是否是脚本哪里不太对。

**Comment by changxuejie123445667** [comment]
参数名：randomLongName
***@***.***|concat(123456789000)
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jul 11, 2024 04:03 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] [BUG]公共脚本测试时，报错‘参数校验失败’ (Issue #32007)

&nbsp;



 
你好，我们自己写了类似生成随机姓名的公共脚本，测试成功。
 方便把你写的脚本贴上出来吗？看下是否是脚本哪里不太对。

**Comment by liuruibin** [comment]
<img width="789" alt="image" src="https://github.com/metersphere/metersphere/assets/23045261/1978f93f-e78a-4b8f-99ac-38e28352184b">
我无法从这里看出来真实脚本

**Comment by youliyuan-fit2cloud** [comment]
抱歉，因为长时间未回复关闭该问题，如果有任何疑问请随时回复我们，感谢理解和支持～
