### ISSUE TITLE
[FEATURE]建议系统管理员通过【切换组织】和点击【组织】按钮进入组织时能均展示组织管理页面

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#32001]
### MeterSphere 版本

v3.0.1

### 联系方式

无

### 请描述您的需求或者改进建议

场景一：系统管理员通过切换组织按钮切换组织后进入项目管理页面
图1:切换组织操作页面
<img width="542" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/d34e6bed-f38a-4086-bd39-dc7c835cfe21">
图2:切换后进入的页面为项目管理页面
<img width="1168" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/4ec49a97-c342-4a1f-be80-46ef8bcd2057">
场景二：系统管理员通过点击【系统】/【组织】菜单后进入了组织管理页面
图3:点击组织按钮
![image](https://github.com/metersphere/metersphere/assets/60059766/8187f682-1a98-4504-85c9-cd909c918893)
图4：点击后进入的页面为组织管理页面
<img width="1077" alt="image" src="https://github.com/metersphere/metersphere/assets/60059766/35044082-960b-46a4-b6d5-92ca76790f71">

### 请描述你建议的实现方案

优化建议：
1、建议两者均切换到组织管理页面，因为存在部分组织管理员首次被创建后无任何项目，场景一中切入到项目管理页面不合适。
2、建议点击个人中的切换组织功能去除，如果是被授权组织管理员而非系统管理员的用户，可以通过权限控制将【组织】菜单展示给用户即可。

**Comment by luty2018** [comment]
组织的切换入口会下掉，展示当前组织的名称。
