### ISSUE TITLE
[BUG]测试计划执行用例后，修改用例，步骤执行结果会错乱

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#32006]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

测试计划执行用例后，修改用例，步骤执行结果会错乱优化

### 重现步骤

1. 功能用例添加到测试计划中执行
![image](https://github.com/metersphere/metersphere/assets/103627487/87a00bca-8e4b-4fc0-a913-bc66b1b2ae3c)
![image](https://github.com/metersphere/metersphere/assets/103627487/be48a759-6cca-4915-b75f-35afbca9b65f)
2.测试用例步骤中间增加步骤（第二步），测试计划中步骤执行结果错乱，步骤执行结果显示最后一行未执行，其实是第二行未执行
![image](https://github.com/metersphere/metersphere/assets/103627487/c0259bd3-63f1-4f7c-8f81-7411c3c6f1d0)
![image](https://github.com/metersphere/metersphere/assets/103627487/0b9f7a18-d5b1-464a-9ef4-d1fa0ee20e93)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复，具体版本等待后面排期，感谢理解。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
