### ISSUE TITLE
[BUG]邮箱或密码不正确

### ISSUE THREAD

**Issue by gallopor** [metersphere/metersphere#32013]
### 联系方式

gallopor

### MeterSphere 版本

v3.0.1

### 使用外置数据库

否

### 问题描述

采用如下在线安装方式安装完成后，
打开浏览器，访问应用登录界面，输入用户名/密码，但提示邮箱或密码不正确
# 用户名: admin
# 密码: metersphere

### 重现步骤

docker run -d -p 8081:8081 --name=metersphere -v ~/.metersphere/data:/opt/metersphere/data cr2.fit2cloud.com/metersphere/metersphere-ce-allinone

**Comment by youliyuan-fit2cloud** [comment]
你好，这个情况没复现，请检查输入的是否正确，用户名或密码前后有没有空格，msctl status 查看下服务状态是否正常？
![image](https://github.com/metersphere/metersphere/assets/54612864/52a8294a-16aa-4eb8-a129-85fa4f333813)
