### ISSUE TITLE
批量执行自动化场景时间过长导致删除后续任务

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32037]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

批量执行自动化场景，并且选择集合报告，如果任务较多耗时较长会导致到达ApiExecutionQueueListener检测时间时，会通过如图所示中的代码将队列任务删除掉，这里应该加个判断，如果是metersphere.api_execution_queue表中的字段为集合报告，则jMeterService.getRunningQueue方法应该传入的是集合报告的id，而不是子任务的id。
![image](https://github.com/user-attachments/assets/a6a093bb-cc88-43ca-a743-762f74afa4fd)

### 重现步骤

如上所示

### 期待的正确结果

如上所示

**Comment by ijwstl** [comment]
![image](https://github.com/user-attachments/assets/c7697811-91ff-4826-966a-04f5a636c892)
感觉这样可以

**Comment by fit2-zhao** [comment]
感谢建议，我们再确认下。

**Comment by ijwstl** [comment]
下方的集成报告超时也应该加运行判断
![image](https://github.com/user-attachments/assets/c143eaef-a17c-4254-90bd-73d39bae3368)


并且在任务中心停止任务时也应该判断report id是存在于api_execution_queue还是api_execution_queue_detail，因为集合报告停止时回传的是集合报告的id，但是stop里用集合报告的id去api_execution_queue_detail查任务是查不到的，所以导致其实后台还在继续运行用例
io.metersphere.service.ApiExecutionQueueService#stop(java.lang.String)
![image](https://github.com/user-attachments/assets/d966a6e6-07bd-45f2-ab4d-48a0b745cb56)
建议先查询api_execution_queue确认是否为集合报告，如果是则要按照api_execution_queue表里的id去api_execution_queue_detail删除任务，即为
`public void stop(String reportId) {
        ApiExecutionQueueExample apiExecutionQueueExample = new ApiExecutionQueueExample();
        apiExecutionQueueExample.createCriteria().andReportIdEqualTo(reportId);
        List<ApiExecutionQueue> apiExecutionQueues = apiExecutionQueueMapper.selectByExample(apiExecutionQueueExample);
        if (apiExecutionQueues.size() != 0 && apiExecutionQueues.get(0).getReportType().equals(RunModeConstants.SET_REPORT.toString())){
            apiExecutionQueues.forEach(detail -> {
                ApiExecutionQueueDetailExample example = new ApiExecutionQueueDetailExample();
                example.createCriteria().andQueueIdEqualTo(detail.getId());
                executionQueueDetailMapper.deleteByExample(example);
                ApiExecutionQueueDetailExample queueDetailExample = new ApiExecutionQueueDetailExample();
                queueDetailExample.createCriteria().andQueueIdEqualTo(detail.getId());
                long queueDetailSize = executionQueueDetailMapper.countByExample(queueDetailExample);
                if (queueDetailSize <= 1) {
                    ApiExecutionQueue queue = queueMapper.selectByPrimaryKey(detail.getId());
                    // 更新测试计划报告
                    if (queue != null && StringUtils.isNotEmpty(queue.getReportId())) {
                        checkTestPlanCaseTestEnd(null, null, queue.getReportId());
                    }
                }
            });
        }else{
            ApiExecutionQueueDetailExample example = new ApiExecutionQueueDetailExample();
            example.createCriteria().andReportIdEqualTo(reportId);
            List<ApiExecutionQueueDetail> details = executionQueueDetailMapper.selectByExample(example);
            details.forEach(detail -> {
                executionQueueDetailMapper.deleteByPrimaryKey(detail.getId());

                ApiExecutionQueueDetailExample queueDetailExample = new ApiExecutionQueueDetailExample();
                queueDetailExample.createCriteria().andQueueIdEqualTo(detail.getQueueId());
                long queueDetailSize = executionQueueDetailMapper.countByExample(queueDetailExample);
                if (queueDetailSize <= 1) {
                    ApiExecutionQueue queue = queueMapper.selectByPrimaryKey(detail.getQueueId());
                    // 更新测试计划报告
                    if (queue != null && StringUtils.isNotEmpty(queue.getReportId())) {
                        checkTestPlanCaseTestEnd(null, null, queue.getReportId());
                    }
                }
            });
        }
    }`

**Comment by youliyuan-fit2cloud** [comment]
v2.10.17中已优化。
