### ISSUE TITLE
[BUG]【测试跟踪】选中某节点后，点击公共用例库，点击返回，光标还是在某节点处停留，但是右侧用例显示的是所有用例。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32043]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【测试跟踪】选中某节点后，点击公共用例库，点击返回，光标还是在某节点处停留，但是右侧用例显示的是所有用例。

### 重现步骤

【测试跟踪】选中某节点后，点击公共用例库，点击返回，光标还是在某节点处停留，但是右侧用例显示的是所有用例。
![image](https://github.com/user-attachments/assets/9c882ddf-d4e9-42e2-9440-70058329a74d)
![image](https://github.com/user-attachments/assets/fcf05eda-69b5-4d96-b69e-72b44f02a328)
![image](https://github.com/user-attachments/assets/418a0f84-cde7-4a63-80d0-66575d97329e)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化。

**Comment by 13290445582** [comment]
您好，问题已修复，请升级v2.10.18版本使用。
