### ISSUE TITLE
[BUG]先创建缺陷在关联用例，最后测试计划统计不到这个缺陷的用例，只有在执行用例的时候提出的缺陷才可以在最后的报告中统计出来

### ISSUE THREAD

**Issue by yaowenjie0329** [metersphere/metersphere#32047]
### MeterSphere 版本

MeterSphere v3.0 beta版本

### 使用外置数据库

否

### 问题描述

先创建缺陷在关联用例，最后测试计划统计不到这个缺陷的用例，只有在执行用例的时候提出的缺陷才可以在最后的报告中统计出来，3.0版本

### 重现步骤

1.创建缺陷并创建成功到缺陷列表
2.关联缺陷涉及到的用例
3.根据创建的测试计划进行生成报告
4.报告中没有显示先创建缺陷后关联用例的缺陷，直接在执行用例的时候创建的缺陷可以正常统计

**Comment by youliyuan-fit2cloud** [comment]
你好，看描述理解，步骤 是：1、在缺陷管理-创建的缺陷A，2、在缺陷A里面关联用例case1，3、测试计划里面关联用例 case1 ，4、测试计划里面查看报告 
如果是这样操作，不是缺陷。当前实现的逻辑是只有 测试计划里面关联或创建的缺陷才会统计到测试报告。除了这以外的情况不统计，即，在缺陷管理模块-缺陷A详情中关联的用例，之后用例被关联到测试计划是不会同步关联缺陷A，感谢理解和支持。
