### ISSUE TITLE
[BUG]测试计划下功能用例提交执行评论，如果不输入内容直接点击保存会将之前添加的图片清空

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32049]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

测试计划下功能用例提交执行评论，如果不输入内容直接点击保存会将之前添加的图片清空

### 重现步骤

参考附件

### 附加信息

https://github.com/user-attachments/assets/3fb6e68c-32ea-4306-a1c9-4e9f42405e86

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，看视频信息，不是删除了，像是网络问题显示异常。该问题是否必现？

**Comment by dashenyucainiao** [comment]
该问题必现，且/opt/metersphere/data/images/markdown下面相关的图片文件被清除

**Comment by dashenyucainiao** [comment]
v2.10.16-lts版本已修复此问题，关闭
