### ISSUE TITLE
[FEATURE]建议前置中SQL可选择在整个场景中执行一次或每个步骤前执行一次

### ISSUE THREAD

**Issue by AbpFan** [metersphere/metersphere#32066]
### MeterSphere 版本

3.0.1

### 联系方式

2337729@qq.com

### 请描述您的需求或者改进建议

建议前置中SQL可选择在整个场景中执行一次或每个步骤前执行一次，每个步骤前执行一次且同一条SQL的场景很少，或者SQL可以作为步骤，这样更灵活

**Comment by fit2-zhao** [comment]
您的这个需求可以通过插件方式去实现，v3.0.1 版本已经支持了 TCP 插件，后续会逐渐丰富插件库，更多插件请持续关注：[插件列表](https://metersphere.io/docs/v3.x/plugin/)；

您也可以参照我们的插件开发文档，一起快速去构建自己所需插件：[开发文档](https://metersphere.io/docs/v3.x/dev_manual/api_plugin_dev/)

**Comment by rbsrcy** [comment]
![WechatIMG8883](https://github.com/user-attachments/assets/dd762b4d-2951-4086-bc62-7bc74eb09a9a)

@fit2-zhao 我理解这个和插件没有关系吧，@AbpFan 说的是我截图这个功能，建议场景中的前/后置配置能不能加个开关，用来控制是场景前后执行一次还是每个步骤前后执行一次。我们其实很多时候要的是每个场景前后执行一次即可

**Comment by fit2-zhao** [comment]
![image](https://github.com/user-attachments/assets/0dda624e-76b5-44ca-b772-66c25db95c66)
可以使用环境中的前后置操作。
@rbsrcy

**Comment by rbsrcy** [comment]
我们只想在加到某个场景的前后，如果这个放到环境，那是使用这个环境所有场景都会自行这个前后置操作，这个不是我们希望看到的。我理解这种前后置应该分为环境级别，场景级别，用例（接口）级别。 @fit2-zhao

**Comment by fit2-zhao** [comment]
如果你只是想作为一个步骤级存在，参照这种就行，就和默认 HTTP 协议的步骤相似，你在场景第一步放一个，最后一步放一个就行。

> 您的这个需求可以通过插件方式去实现，v3.0.1 版本已经支持了 TCP 插件，后续会逐渐丰富插件库，更多插件请持续关注：[插件列表](https://metersphere.io/docs/v3.x/plugin/)；
> 
> 您也可以参照我们的插件开发文档，一起快速去构建自己所需插件：[开发文档](https://metersphere.io/docs/v3.x/dev_manual/api_plugin_dev/)
