### ISSUE TITLE
[需求]希望v3版本恢复v2版本中“接口定义URL可重复”的设置

### ISSUE THREAD

**Issue by AbpFan** [metersphere/metersphere#32068]
### MeterSphere 版本

3.0.1

### 联系方式

2337729@qq.com

### 请描述您的需求或者改进建议

我的需求是同一个路径的接口需要提供多套参数，我试了两种办法，一是创建多个同一路径的接口，发现相同路径不能保存，二是创建多个用例，又发现引用时不能选择某一用例，引用的目的是方便修改，达到全局修改的目的。

### 附加信息

![1](https://github.com/user-attachments/assets/ecabf911-1923-4edc-ab07-4c1e4b61ff31)

**Comment by luty2018** [comment]
这个已经在规划中了

**Comment by Stephen0910** [comment]
没找到啊。 v3 哪里有。 @luty2018
