### ISSUE TITLE
[FEATURE]功能用例列表页，希望记忆筛选条件及页页显示用例条数的设置，即使切换页面后也能记忆该操作

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#32074]
### MeterSphere 版本

2.10.15

### 联系方式

张树彬

### 请描述您的需求或者改进建议

功能用例列表页，添加筛选条件、更改每页显示的用例条数后，切换到其他页面，再切换回来，之前的操作就清除了，客户希望能够记忆住筛选条件和每页显示用例条数的操作。（其他页面也可以同步优化）

**Comment by luty2018** [comment]
这个会在v3.3支持

**Comment by binbin0406** [comment]
> 这个会在v3.3支持

v2还会支持吗，因为客户要用UI测试，所以用v2版本。（意向下单客户）

**Comment by luty2018** [comment]
已线下沟通
