### ISSUE TITLE
[BUG] UI脚本获取时间失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#32078]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

JavaScript 脚本获取 当前时间失败

### 重现步骤

![image](https://github.com/user-attachments/assets/2c2b870e-87fe-49cc-a1f2-a3063b609f93)
![image](https://github.com/user-attachments/assets/3807d645-0b04-4735-9197-742c9e311f13)

**Comment by liuruibin** [comment]
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/6f5167ad-69fa-47f9-9847-7fff9a30401d">

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/fc32abdf-a742-42c4-8a81-c49b16945e01">
