### ISSUE TITLE
[BUG]v3.0.1导入v2的接口提示导入成功，但是只导入了目录结构

### ISSUE THREAD

**Issue by chiehfeng** [metersphere/metersphere#32084]
### MeterSphere 版本

v3.0.1-080e6767

### 使用外置数据库

否

### 问题描述

v3.0.1导入v2的接口提示导入成功，但是只导入了目录结构

### 重现步骤

1.使用v2.10.16-lts接口定义里面的导出，导出swagger3.0格式
![image](https://github.com/user-attachments/assets/29ce5038-620e-4429-aee1-ea2416cff39e)
2.在v3.0.1版本里面导入v2导出的文件
![image](https://github.com/user-attachments/assets/127c9808-4fc2-4e1b-b7d0-1c95cf8decd9)
3.提示导入成功，但是只有目录导进去了，接口没有导进去
![image](https://github.com/user-attachments/assets/d99b53d4-0912-4494-a89d-893026f49438)

**Comment by luty2018** [comment]
<img width="514" alt="image" src="https://github.com/user-attachments/assets/a6aedda2-2e46-44d7-98ee-6a4af89529d9">
请确认这里是否选中了HTTP

**Comment by chiehfeng** [comment]
![image](https://github.com/user-attachments/assets/ddca4e52-5f00-44e4-bb39-7c2b5c11c6ce)
没有选中，这个不应该是默认选中才对么

**Comment by luty2018** [comment]
是的， 应该默认选中， 我们会在下个版本优化，您先手动选中，确保功能可以正常使用哈。
