### ISSUE TITLE
[API-TEST 批量复制、批量移动带文件夹路径过去]目前api-test服务下的接口复制和移动没有带文件夹路径过去，复制过去后会导致用例需要重新分类

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#32082]
### MeterSphere 版本

v2.10.15-lts-1e4e1f7b

### 联系方式

13716054767

### 请描述您的需求或者改进建议

目前api-test服务下的接口复制和移动没有带文件夹路径过去，复制过去后会导致用例需要重新分类
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/2f7cf9ae-993a-47f6-8610-3c141e4cc59d">

### 请描述你建议的实现方案

带对应的文件夹和路径过去

**Comment by lol666666** [comment]
批量移动和批量复制后效果:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/e12b3e22-9391-4274-9726-92814074ab5f">

**Comment by youliyuan-fit2cloud** [comment]
你好，看描述意思是假如 接口A的模块路径是/测试模块A/测试子模块A，然后移动接口A到 模块/test后，最后的接口A的 模块路径是/test/测试子模块A 吗？
如果是，暂不支持这种复制和移动。感谢理解和支持。

**Comment by lol666666** [comment]
何时会开发支持这块？有计划吗？建议尽快其实工作中这个功能能节省大量时间，提高效率
