### ISSUE TITLE
[FEATURE]接口场景中引用API,目前无法添加断言、前置、后置。

### ISSUE THREAD

**Issue by elevemonkey** [metersphere/metersphere#32097]
### MeterSphere 版本

 v3.x和v2.10.11-lts-a580bd0a

### 请描述您的需求或者改进建议

**在实际进行场景编排中，接口场景去引用API，会需要加一些特点针对场景的断言，或者参数提取（后置）和前置；**
目前的**迂回**的解决方案：
1.需要去创建好多个相同的api
2.创建很多用例，但是这些用例直接在定义的tab去看，可读性差（因为是针对特点场景的），编排的过程中需要修改还要回到定义tab栏修改，再回来编排，特别麻烦耗时。
如果官方有更好的解决方案可以回复下，或者进行上述建议去修改
目前v3.x只支持到了更改参数值，断言、前置、后置无法增加

**Comment by ywang9-12** [comment]
为什么不去复制api呢？引用是无法对原api进行修改的，复制可修改

**Comment by elevemonkey** [comment]
复制后，和原本的api就没有关联关系了，如果api 的url路径修改，那我就需要到全部复制的场景里面去逐个更改了
上次的沟通结果是可以支持的
![image](https://github.com/user-attachments/assets/fd69f959-7c65-43d2-84ab-591b031f6f5f)
![image](https://github.com/user-attachments/assets/59063766-130a-4e3e-9888-f274b5c81a6d)

**Comment by luty2018** [comment]
您好， 这个需求我们预计会在v3.6以后的版本支持。
