### ISSUE TITLE
[BUG]接口CASE使用环境变量更新脚本更新环境通用变量值，将其放在测试计划内执行时对应环境的通用配置变量更新错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32100]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

CASE使用环境变量更新脚本更新变量值，其放在测试计划内执行时更新的仍然是原CASE内保存对应环境内的变量值，而不是执行测试计划时选择的新环境

### 重现步骤

1、找到某个接口的CASE，创建如下后置脚本并保存
String date="${__time(yyyy-MM-dd HH:mm:ss,)}";
vars.put(${__metersphere_env_id}+"testVar",date);
vars.put("testVar",date);

2、创建新测试计划关联该接口CASE

3、执行测试计划并选择不同环境，查看不同环境的testVar通用配置

4、比对通用配置testVar的变量值

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by luty2018** [comment]
v2.17已修复， 可以验证看看。
