### ISSUE TITLE
[QUESTION]python脚本中需要获取切换环境对应模块启动的http域名  ，如${__metersphere_env_id}可以获取环境号 那怎么才能获取这个环境号下面的http配置域名

### ISSUE THREAD

**Issue by maryine** [metersphere/metersphere#32122]
### 请描述您的问题

python脚本中需要获取切换环境对应模块启动的http域名
 
如${__metersphere_env_id}可以获取环境号
那怎么才能获取这个环境号下面的http配置域名

**Comment by liuruibin** [comment]
使用的是哪个版本呢？

**Comment by maryine** [comment]
v1.20.21-lts

**Comment by maryine** [comment]
> 使用的是哪个版本呢？

v1.20.21-lts

**Comment by liuruibin** [comment]
很遗憾，不支持

**Comment by maryine** [comment]
> 很遗憾，不支持

那高版本的支持？

**Comment by liuruibin** [comment]
也不支持，新版本中我们可以考虑能否实现

**Comment by maryine** [comment]
> 也不支持，新版本中我们可以考虑能否实现

这样，好的，感谢回复
