### ISSUE TITLE
[BUG]乌班图系统安装提示mysql以及redis连接不上问题

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#32135]
### MeterSphere 版本

3.0.1

### 使用外置数据库

否

### 问题描述

乌班图系统安装提示mysql以及redis连接不上问题

### 重现步骤

乌班图系统安装提示mysql以及redis连接不上问题
将ip配置文件ip改成mysql与redis就ok
后面接口测试的时候，kafka也是此问题。 应该是缺陷么

### 附加信息

论坛反馈问题https://bbs.fit2cloud.com/t/topic/6473/4

**Comment by legend818** [comment]
31233 的问题 我初步怀疑也可能是这块问题。

**Comment by liuruibin** [comment]
防火墙和selinux关了后重启docker试试

**Comment by legend818** [comment]
![QQ_1721206782080](https://github.com/user-attachments/assets/146c2a93-9b3b-49c8-bd33-a262e7d24801)

重启docker 还是不行
sudo systemctl restart docker

**Comment by liuruibin** [comment]
3306 6379 9000 9001 9092 都需要放开

**Comment by legend818** [comment]
理解不了， 我把配置文件的IP改成redis，mysql，kafka就OK 了。我现在也没有打算把配置文件改回IP再去试一下。我已经把防火墙关闭了。其实过程当中我印象是关闭了防火墙还不行。          我个人判断不是这个问题。    容器生成都是你们安装包自动产生的，包含配置文件，理论上都在一台pc按我理解，配置文件使用名称不是最佳方案么？？？

**Comment by legend818** [comment]
理解不了， 我把配置文件的IP改成redis，mysql，kafka就OK 了。我现在也没有打算把配置文件改回IP再去试一下。我已经把防火墙关闭了。其实过程当中我印象是关闭了防火墙还不行。          我个人判断不是这个问题。    容器生成都是你们安装包自动产生的，包含配置文件，理论上都在一台pc按我理解，配置文件使用名称不是最佳方案么？？？

**Comment by liuruibin** [comment]
单机部署确实使用容器名更为方便，考虑到分散部署、以及外置资源池需要获取主节点的局域网ip，这里使用ip更为稳妥。
