### ISSUE TITLE
[BUG]测试计划定时任务不可修改

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#32134]
### MeterSphere 版本

3.0.1

### 使用外置数据库

否

### 问题描述

测试计划定时任务不可修改

### 重现步骤

测试计划定时任务不可修改，我想改成每天晚上的22点

### 附加信息

![QQ_1721197738484](https://github.com/user-attachments/assets/c7dc43cb-55bb-41f9-9047-0535a181eb16)

**Comment by liuruibin** [comment]
这里我们会不断优化的，敬请期待

**Comment by youliyuan-fit2cloud** [comment]
下个版本 v3.1 支持手动输入了。

**Comment by legend818** [comment]
![image](https://github.com/user-attachments/assets/b929a81d-a708-4146-a705-db2133429142)

还是不支持啊 升级到了3.1.0

Cron表达式需要自己手动输入哈，不是v2的那个组件。。。
