### ISSUE TITLE
[BUG]【接口测试】环境变量里设置csv, 新建场景-导入场景-复制，复制case和引用case拖拽进循环控制器里，点击调试，引用csv都是使用同一个数据

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32144]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【接口测试】环境变量里设置csv, 新建场景-导入场景-复制，复制case和引用case拖拽进循环控制器里，点击调试，引用csv都是使用同一个数据

### 重现步骤

【接口测试】环境变量里设置csv, 场景里含有循环控制器，请求参数和自定义脚本里引用csv变量。
![image](https://github.com/user-attachments/assets/f4f39d1b-6a19-447b-92a9-d87841808ac9)
![image](https://github.com/user-attachments/assets/a7ac5226-baf5-4793-8b53-26c8bcf9972f)

另外新建场景-导入场景-复制，再复制一个case和引用一个case，然后将复制的case和引用的case拖拽进循环控制器里
![image](https://github.com/user-attachments/assets/dd77a075-cb19-4cd1-97ef-250b74023a98)

点击调试，发现引用csv的地方都是使用同一个数据
![image](https://github.com/user-attachments/assets/799f0ecc-d84b-4c47-99b4-b86e662f633a)
![image](https://github.com/user-attachments/assets/d77aab26-720e-46cb-bba3-ee125855b0df)
![image](https://github.com/user-attachments/assets/ecdb70d3-7410-4078-b10c-cdf4d5eb19f5)
![image](https://github.com/user-attachments/assets/2d25aba9-8e98-47c9-9b0b-91242cde8b67)

https://github.com/user-attachments/assets/41c65dac-fde1-4699-98e7-ecad04e52345

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会修复该问题

**Comment by shenkaibo** [comment]
只要是 csv 在环境变量里，手动在新场景里添加循环控制器，然后在循环控制器里添加case ,往下多复制几个接口case之后有时候也会出现这个问题

**Comment by youliyuan-fit2cloud** [comment]
v2 版本环境上的csv 会在每个请求下自动生成一份，每个请求默认就会占用一个值，这样如果有三个请求，那默认就会从第三个值开始，想要达到缺陷中要求的效果把CSV放场景变量即可。
