### ISSUE TITLE
[FEATURE] 批量执行接口自动化场景时，希望可以显示执行的进度，否则只能到测试报告中去查看

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3214]
**请描述您的需求或者改进建议.**

批量执行接口自动化场景时，希望可以显示执行的进度，否则只能到测试报告中去查看

![WechatIMG116](https://user-images.githubusercontent.com/32027713/119763218-b3e54c00-bee1-11eb-8420-7e161fe18074.jpeg)

**Comment by xulinde** [comment]
感谢反馈，这个可以优化下

**Comment by xulinde** [comment]
感谢反馈，这个可以优化下

**Comment by xulinde** [comment]
v1.11已添加任务中心功能，批量执行可以看到进度
