### ISSUE TITLE
[FEATURE]接口定义下的测试用例，可以拖动调换顺序

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3215]
**请描述您的需求或者改进建议.**

接口定义下的测试用例Case，可以拖动调换顺序

![WechatIMG117](https://user-images.githubusercontent.com/32027713/119763590-6a493100-bee2-11eb-8f91-036d4a5f2bed.png)

**Comment by xulinde** [comment]
感谢反馈，我们先内部讨论下

**Comment by xulinde** [comment]
v1.13已支持自定义排序
