### ISSUE TITLE
[BUG][测试跟踪]测试计划未设置“允许关联重复用例”，在关联功能用例时仍可重复且无法筛选出已关联用例

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#32168]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

是

### 问题描述

1、建立了一个测试计划，不开启“允许关联重复用例”。
![测试计划设置不允许关联重复用例](https://github.com/user-attachments/assets/a468fd3e-5e04-4096-937f-26093b1d06a6)
2、进入计划关联功能用例176个，这176个用例均关联了场景自动化，共关联导入了67个场景。
![已关联176个用例](https://github.com/user-attachments/assets/f7e1755c-4048-462f-b813-211b26ca71db)
3、后续想往计划里继续补充功能用例，点击关联用例后按用例状态筛选，符合条件的为181个功能用例。
![继续关联功能用例目录有问题](https://github.com/user-attachments/assets/633286b0-bd68-4454-9e29-f12a3747b189)
此处存在两个问题：
（1）筛选后左侧目录用例数显示不正确，仍为全部用例数，右侧用例列表数量正确（仅【测试跟踪】的用例有此问题，【功能用例】模块正常）；
（2）选中这181个功能用例后，无法自动筛选剔除已关联的176个用例，导致关联用例重复，用例总量为357。在接口测试用例处导入场景可不重复关联，筛选正常。

### 重现步骤

1、录入3个功能用例，并关联3个场景自动化，用例状态标志“已自动化”。
2、建立测试计划，不开启“允许关联重复用例”。
3、功能用例关联步骤1的其中1个用例，正常显示并关联导入一个场景。
4、功能用例继续关联，按用例状态“已自动化”进行筛选，目录和用例列表应显示2个用例。**当前问题目录显示全部用例，用例列表显示3个。**
5、选择步骤4筛选后的用例进行关联，功能用例会重复，结果变为4个用例

### 期待的正确结果

【测试跟踪】模块，测试计划不开启“允许关联重复用例”时，关联功能用例应对目录和用例列表进行已关联筛选，显示未关联用例数据，且避免重复关联

**Comment by 13290445582** [comment]
您好，未复现该问题，请问描述的按照「用例状态」筛选，指的是「高级搜索」吗？

**Comment by ywang9-12** [comment]
> 您好，未复现该问题，请问描述的按照「用例状态」筛选，指的是「高级搜索」吗

是的，「高级搜索」中筛选用例状态
![Uploading 高级搜索.jpg…]()

**Comment by ywang9-12** [comment]
![高级搜索](https://github.com/user-attachments/assets/3db588a0-6c73-42be-878a-72b14024a16f)

**Comment by 13290445582** [comment]
您好，未复现该情况，高级搜索后显示正确，请您检查下是不是数据问题，换个工作空间项目试下高级搜索好用吗？
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/f684123f-4ab1-4a15-be84-685452e5d750">

**Comment by ywang9-12** [comment]
您好，下周是否可以约个腾讯会议共享屏幕演示？除了筛选显示问题其他都正常，测试计划执行后场景自动化结果也可回填到功能用例，不像是数据问题

**Comment by ywang9-12** [comment]
找到问题了，非bug
