### ISSUE TITLE
[BUG]【接口定义】swagger2 文件导入平台，jsonSchame处没数据

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32160]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【接口定义】swagger2 文件导入平台，jsonSchame处没数据

### 重现步骤

【接口定义】swagger2 文件导入平台，jsonSchame处没数据
<img width="1702" alt="b8d3a733-7e68-4689-b401-986286837d6e" src="https://github.com/user-attachments/assets/38cabd0c-17b7-4395-b3a1-feafa96a9add">
![image](https://github.com/user-attachments/assets/a6987f7f-7936-4586-8649-2cde9415a494)

json文件如下
[swagger2.json](https://github.com/user-attachments/files/16264197/swagger2.json)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，问题已复现，后续是否优化我们需要讨论后确定，感谢理解和支持。

**Comment by luty2018** [comment]
这个问题在v3修复了， v2只保存了JSON数据。
