### ISSUE TITLE
[FEATURE]对于场景新增参数变量值时，如果值为列表，一个为列表的值，会因为逗号被分成2个值，不管是在常规参数还是CSV参数

### ISSUE THREAD

**Issue by berserkerwsc** [metersphere/metersphere#32177]
### MeterSphere 版本

3.0.1

### 使用外置数据库

否

### 问题描述

对于场景新增参数变量值时，如果值为列表，一个为列表的值，会因为逗号被分成2个值，不管是在常规参数还是CSV参数

### 重现步骤

接口测试中场景测试，新增参数，不管是在常规参数还是CSV参数，值为列表，一个为列表的值，会因为逗号被分成2个值。在csv值设置时，即使设置分割符合不为逗号，但是整个值会变成字符串，非列表或者数组

### 期待的正确结果

值如果设置的是列表或者数组，传入接口的参数应该也是列表或者数组

### 相关日志输出

```shell
例如：参数input_id为[],[1,2]。最终传入input会变成3个数
```

**Comment by 13290445582** [comment]
您好，我们对于列表的值就是采用逗号作为分割符的，值中出现了逗号就是会被分割成多个值，所以值中若非作为分割符使用，尽量避免使用逗号作为值的一部分，感谢您的理解与支持。

**Comment by berserkerwsc** [comment]
那万一值就是一个列表或者数组，避免不了存在逗号的情况呢？而且我看CSV配置里面有设置分隔符，设置成其他分割符号如#后，列表会自动变成字符串，建议能否在CSV不设置分隔符的情况下保持数据的原格式作为变量输入呢？

**Comment by 13290445582** [comment]
您好，已收到您的建议，先转为需求我们评审下，感谢反馈。

**Comment by luty2018** [comment]
> 那万一值就是一个列表或者数组，避免不了存在逗号的情况呢？而且我看CSV配置里面有设置分隔符，设置成其他分割符号如#后，列表会自动变成字符串，建议能否在CSV不设置分隔符的情况下保持数据的原格式作为变量输入呢？

1.常规参数我们会修改代码，修改之后当“,”作为值时需要在前面带上“/”转义

**Comment by 13290445582** [comment]
您好，需求已在V3.4实现，V3.4已发布，请升级。
