### ISSUE TITLE
[BUG]【接口自动化】场景详情里，自定义请求，点击&取消url后面的引用环境，query参数会重复添加，场景是postman文件导入的

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32188]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

是

### 问题描述

在接口自定义里使用Postman文件导入到场景，在场景详情里，点击&取消url后面的引用环境，query参数会重复添加
注：导入的postman文件里， url地址后面带了参数

### 重现步骤

1.在接口自定义界面导入postman文件，postman文件 url地址后面带参数
2.进入场景详情，点击或取消 url 后面的引用环境
3.可以看到下方的query参数新增了一组参数

### 期待的正确结果

点击&取消url后面的引用环境，query参数不重复添加

**Comment by 13290445582** [comment]
您好，可以提供下复现的Postman文件。

**Comment by zuoqiaoling** [comment]
{
	"info": {
		"_postman_id": "4a698677-648c-4ca2-95f9-e9a914945b86",
		"name": "测试数据",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "15440186"
	},
	"item": [
		{
			"name": "测试属性数据",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "http://localhost.eniot.io/business-object-service/model/v3.0/model?action=create&orgId=999",
					"protocol": "http",
					"host": [
						"localhost",
						"eniot",
						"io"
					],
					"path": [
						"business-object-service",
						"model",
						"v3.0",
						"model"
					],
					"query": [
						{
							"key": "action",
							"value": "create"
						},
						{
							"key": "orgId",
							"value": "999"
						}
					]
				}
			},
			"response": []
		}
	]
}

**Comment by 13290445582** [comment]
感谢提供复现数据，问题已复现，等待排期中，后续版本修复，确定修复版本后会同步github上显示。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
