### ISSUE TITLE
[BUG]【浏览器插件】chrome浏览器录制插件录制接口完成后，点击下载图标，页面无反应。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32199]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【浏览器插件】chrome浏览器录制插件录制接口完成后，点击下载图标，页面无反应。

### 重现步骤

【浏览器插件】chrome浏览器录制插件录制接口完成后，点击下载图标，页面无反应。
![2e3b0fd9-1b59-46e5-889a-3d7f77d994f2](https://github.com/user-attachments/assets/f1763f6e-691d-415e-a27d-da7938dbd9f7)

**Comment by luty2018** [comment]
应该是版本不兼容导致的，浏览器录制插件我们短时间还不能支持上升级， 非常抱歉。着急的话，可以使用[BlazeMeter]插件来替代一下。
