### ISSUE TITLE
[BUG]版本版本:   v2.10.15-lts-1e4e1f7b，新建项目，选择使用禅道的缺陷模版，其中有自定义的字段，选择使用该模版新建BUG时，无法显示自定义的字段

### ISSUE THREAD

**Issue by huyongqing** [metersphere/metersphere#32201]
### 联系方式

402249283@qq.com

### MeterSphere 版本

版本:   v2.10.15-lts-1e4e1f7b

### 使用外置数据库

否

### 问题描述

版本版本:   v2.10.15-lts-1e4e1f7b，新建项目，选择使用禅道的缺陷模版，其中有自定义的字段，选择使用该模版新建BUG时，无法显示自定义的字段

### 重现步骤

1、项目管理中新建一个名字是禅道对接的项目，集成三方平台选禅道，选择禅道的缺陷模版，模版中有自定义缺陷字段
2、在禅道对接这个项目下，点击新建缺陷，查看是否显示自定义的缺陷字段

### 期待的正确结果

可以显示

**Comment by youliyuan-fit2cloud** [comment]
你好，我们环境没有复现改问题，请把具体配置截图发出来看看，还有zentao的版本，感谢～

**Comment by huyongqing** [comment]
metersphere 配置：
![1](https://github.com/user-attachments/assets/fb27b578-e675-40b2-bf25-9dbce1ff9b5d)
对接禅道缺陷模版配置：
![3](https://github.com/user-attachments/assets/3688fb74-08ff-435a-baa8-c96671d65ee3)
使用禅道缺陷模版建缺陷：
![4](https://github.com/user-attachments/assets/dfc8936c-c3a8-480d-aa0a-ba68bf5036d6)
没有有关模版中字段

禅道版本：
![image](https://github.com/user-attachments/assets/41fe30b4-ea4e-476d-b691-0fc75ab9c099)

**Comment by huyongqing** [comment]
项目配置：
![image](https://github.com/user-attachments/assets/3b2d1d9f-ff81-473c-ae82-9ad04dc016a2)

**Comment by youliyuan-fit2cloud** [comment]
> metersphere 配置： ![1](https://private-user-images.githubusercontent.com/37175151/350822050-fb27b578-e675-40b2-bf25-9dbce1ff9b5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjM2NjUsIm5iZiI6MTcyMTYyMzM2NSwicGF0aCI6Ii8zNzE3NTE1MS8zNTA4MjIwNTAtZmIyN2I1NzgtZTY3NS00MGIyLWJmMjUtOWRiY2UxZmY5YjVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjN2E4N2VjMGUzYzQ2NzkwM2Q5MmQxMjg0MDQwMGY5MWVjYjlhZDk3NmY0MzhmMWIwNzg0Nzc3MmMyZWY4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lYjS6SPfURMth7LwnLubCIvRT7BKbGHWAlZe1thWqXA) 对接禅道缺陷模版配置： ![3](https://private-user-images.githubusercontent.com/37175151/350823573-3688fb74-08ff-435a-baa8-c96671d65ee3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjM2NjUsIm5iZiI6MTcyMTYyMzM2NSwicGF0aCI6Ii8zNzE3NTE1MS8zNTA4MjM1NzMtMzY4OGZiNzQtMDhmZi00MzVhLWJhYTgtYzk2NjcxZDY1ZWUzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDhkMDIyYzI4YzlkMTg1NjEyN2NlMjAxYTgxOWVhNTNkMjE0OTRkNDFiOTY3NWJjZDBkZTM1ZDQ1OWZhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wUjaF7tnAOiLmjeMstUFwJbPBtK1DSjIS6onrcJa_iA) 使用禅道缺陷模版建缺陷： ![4](https://private-user-images.githubusercontent.com/37175151/350823637-dfc8936c-c3a8-480d-aa0a-ba68bf5036d6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjM2NjUsIm5iZiI6MTcyMTYyMzM2NSwicGF0aCI6Ii8zNzE3NTE1MS8zNTA4MjM2MzctZGZjODkzNmMtYzNhOC00ODBkLWFhMGEtYmE2OGJmNTAzNmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWU2MGEwZGU5MmVkNTczYTg4MGVmZWFhYjE3NmE4ODYxY2NhNmQ4MTU3NThhMTVmMmY5ZTFiMmNkMjBiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u8uMjtcnT6n7c3z2m6DcVD_wZFJ79jZPTtnIIlurGB4) 没有有关模版中字段
> 
> 禅道版本： ![image](https://private-user-images.githubusercontent.com/37175151/350822210-41fe30b4-ea4e-476d-b691-0fc75ab9c099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjM2NjUsIm5iZiI6MTcyMTYyMzM2NSwicGF0aCI6Ii8zNzE3NTE1MS8zNTA4MjIyMTAtNDFmZTMwYjQtZWE0ZS00NzZkLWI2OTEtMGZjNzVhYjljMDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA0NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTZhOGQzNTYyZWY5MTdjMGUxYTExYjNiODA2ZjMwNzM4MGIzNWMyZTQxZDMxM2ViYTgwYmYyZjE3YzBiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GD4erSGds7uETDtOglcjVM-MjlzoIkp39pzYy9nHNW0)

从这个 禅道缺陷模版截图，没有自定义字段，如果想和禅道系统里面的缺陷模版字段一样，需要手动在MS系统里面添加对应的字段名称和API字段名，查看如下：
![image](https://github.com/user-attachments/assets/fe8772b0-a970-4900-ab3d-e023f2b7a184)

**Comment by youliyuan-fit2cloud** [comment]
https://kb.fit2cloud.com/?p=257
这个帮助文档，写的比较详细，可以参考配置一下。
