### ISSUE TITLE
[BUG]metersphere 1.2.8插件同步接口到metersphere平台时，注解全部为空

### ISSUE THREAD

**Issue by hclzm** [metersphere/metersphere#32202]
### MeterSphere 版本

v.2.10.16

### 使用外置数据库

是

### 问题描述

metersphere 1.2.8插件同步接口到metersphere平台时，注解全部为空, 不能把字段的注解同步到接口定义中

### 重现步骤

同步任何一个接口，在平台上查看相关字段的描述信息，都为空

**Comment by luty2018** [comment]
v2版本确实不支持同步注解，下周四我们会发布v3.1版本以及v3的IDEA插件，已经支持注解的同步。
