### ISSUE TITLE
[QUESTION]空间管理员不能给项目添加成员吗

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32207]
### 请描述您的问题

空间管理员给项目添加成员时，跳出提示框“请先添加该项目权限”，只有超管和项目管理员项目成员可以添加成员。在权限那里，工作空间下的项目管理-添加成员权限是勾选上的

**Comment by luty2018** [comment]
空间管理员的添加成员权限是只将成员添加到当前空间， 要给项目添加成员需要进入项目且有项目添加成员的权限才行。
