### ISSUE TITLE
[BUG]邮箱或密码不正确 

### ISSUE THREAD

**Issue by lanya16** [metersphere/metersphere#32219]
### MeterSphere 版本

3.0.1

### 使用外置数据库

否

### 问题描述

1、官方安装包离线方式安装, 
2、使用admin进入系统
3、创建新用户
4、使用新用户登录提示“邮箱或密码不正确 ”

### 重现步骤

1、创建新用户abc, 邮箱abc@a.com
2、重置abc用户密码，系统提示以邮箱作为登录密码
3、使用abc/abc@a.com登录，提示邮箱或密码不正确

### 相关日志输出

```shell
metersphere日志无错误信息
```

**Comment by liuruibin** [comment]
用户名输入 abc@a.com
密码输入 abc@a.com
