### ISSUE TITLE
[BUG]循环控制器里面的自定义请求sql如果有三个，那第二个的SQL请求会查不到数据

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3221]
**MeterSphere 版本**
V1.9.3
**Bug 描述**
1、循环控制器里面的自定义请求sql如果有三个，那第二个的SQL请求会查不到数据
2、将其调换顺序也一样 ，处在中间的那个sql请求仍然查不到数据

**Comment by zyyfit** [comment]
您好，没有复现呢，能描述一下具体操作步骤吗？循环使用的是哪种循环方式呀

**Comment by dashenyucainiao** [comment]
次数循环

**Comment by dashenyucainiao** [comment]
升级到1.10.0之后发现可以了
