### ISSUE TITLE
[BUG]同一接口请求poatman、Jmeter 都请求成功，但是在MS上面请求返回302

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32226]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

同一接口请求poatman、Jmeter 都请求成功，但是在MS上面请求返回302

### 重现步骤

postman 导出接口导入到MS 接口定义中，执行返回状态码302，但是在postman、Jmeter 上面调用成功

### 期待的正确结果

同一接口请求poatman、Jmeter 都请求成功，但是在MS上面请求也成功

### 相关日志输出

```shell
无
```

### 附加信息

![image](https://github.com/user-attachments/assets/005e7ba6-b518-4602-83ba-d0b322a1b565)

<img width="826" alt="1721383533135" src="https://github.com/user-attachments/assets/0795c617-ec9a-4ad9-b190-e5a74d24cfab">
![image](https://github.com/user-attachments/assets/f89ef7bc-de72-4f85-90f9-9ffdb5ca626d)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们的环境没有复现该问题，如果是必现的请把接口  文件发出来，谢谢
