### ISSUE TITLE
[BUG]【接口测试】mock请求，响应体里引用 mock环境变量里的变量，最终运行mock请求，变量没有引用成功

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32273]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

【接口测试】mock请求，响应体里引用 mock环境变量里的变量，最终运行mock请求，变量没有引用成功

### 重现步骤

【接口测试】mock请求，响应体里引用 mock环境变量里的变量，最终运行mock请求，变量没有引用成功
![image](https://github.com/user-attachments/assets/1cd6622e-ee7b-4736-8e32-e01cb1d975c5)
![image](https://github.com/user-attachments/assets/d1e2157b-969b-44c7-b173-1e23fb0c361c)
![image](https://github.com/user-attachments/assets/ec7a947c-e6b4-480b-9b58-ae8d0cfb34dd)

**Comment by Somebody-JIAN** [comment]
不支持。

而且这是两个环境：发请求收请求的测试执行环境、 接收请求去数据库查找返回内容的服务器运行环境，
两个环境数据不互通、逻辑不互通，后期也无法支持。
