### ISSUE TITLE
接口导入时重复接口会覆盖case名称

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32277]
### MeterSphere 版本

v2.10.16-lts

### 请描述您的需求或者改进建议

当导入postman文件到接口定义是，代码里会将postman中定义的接口解析为api和case，但是后边检测到有重复接口时，只是将重复接口作为case存入map当中，后续为这些case命名为了case123456，丢失了原来的case名称，建议直接将重复接口的case添加到case列表中即可，这样不会丢失case原本的名字。具体代码位置为io.metersphere.service.definition.ApiDefinitionImportUtilService#setRepeatApiToCase

![image](https://github.com/user-attachments/assets/64d9fc2e-5cc9-481f-a761-b6a148152412)

### 请描述你建议的实现方案

如上

**Comment by ijwstl** [comment]
后修改两处，第一处为无论系统是否存在重复资源均对导入的资源进行整合，即如果导入资源的接口存在重复，则将重复接口的case添加到唯一接口的list里，后续在做处理，这样不会丢失重复接口的case。

io.metersphere.service.definition.ApiDefinitionImportUtilService#dealHttpUrlNoRepeat
![image](https://github.com/user-attachments/assets/abc6d880-ae41-4b6f-84db-62a46017d704)


io.metersphere.service.definition.ApiDefinitionImportUtilService#setRepeatApiToCase
![image](https://github.com/user-attachments/assets/c6276f1b-1479-4445-88e4-e5a40ac5059f)

**Comment by luty2018** [comment]
我们会在v2.10.18 修复这个问题。

**Comment by Somebody-JIAN** [comment]
修复方案如下：

postman导入，不会再自动生成接口用例。上图中的问题也就不会出现。

同时改变了postman文件格式的解析方式：支持postman的example数据格式解析， 接口的example会作为用例进行存储。

如果同一份文件有请求方式+请求路径相同的接口，解析完后只会留1个，它们的example会合并（以name为唯一标识，若出现相同的name，会再第二个级以后用“_{n}”的命名格式存储。

解析结果与metersphere中已存在的数据判断逻辑不变。

2.10.18测试时间紧张，跳票到2.10.19版本上线

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
