### ISSUE TITLE
[QUESTION]请问下安装部署时，报错误：Caused by: java.sql.SQLException: Access denied for user 'root'@'172.30.10.1' (using password: YES) ，有什么方法可以解决吗

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32270]
### 请描述您的问题

<img width="646" alt="企业微信截图_17217249882057" src="https://github.com/user-attachments/assets/5726a655-fcb5-40d4-a02b-4926728b083a">

Caused by: java.sql.SQLException: Access denied for user 'root'@'172.30.10.1' (using password: YES)

**Comment by liuruibin** [comment]
请问是如何安装的呢，这个看起来是密码验证不通过

**Comment by zuoqiaoling** [comment]
https://github.com/metersphere/installer/tree/v2.10
用的这个安装脚本
可以看是哪个模块的密码验证不通过吗？是mysql吗

**Comment by Somebody-JIAN** [comment]
是mysql。 你用的是外部数据库吗？

**Comment by Somebody-JIAN** [comment]
> https://github.com/metersphere/installer/tree/v2.10 用的这个安装脚本 可以看是哪个模块的密码验证不通过吗？是mysql吗

是
