### ISSUE TITLE
[BUG]接口自定义请求接口发现会自动发两遍接口请求

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#32279]
### 联系方式

13716054767

### MeterSphere 版本

v2.10.15-lts-1e4e1f7b

### 使用外置数据库

否

### 问题描述

在接口测试流程中创建自定义接口请求发现会发两遍请求，具体现象，点击调试后，自定义接口请求发送请求到服务端，24s后发现又重新发送了请求到服务端，总共发送了两次请求

### 重现步骤

在接口测试流程中创建自定义接口请求发现会发两遍请求，具体现象，点击调试后，自定义接口请求发送请求到服务端，24s后发现又重新发送了请求到服务端，总共发送了两次请求

### 期待的正确结果

发送一次，或者可以控制发送几次，不要自动重新发送请求

### 附加信息

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/ea6f27f0-a25d-4a07-a711-1f807b97117e">
日志如下：
第一次
<img width="1317" alt="企业微信截图_e1990b91-a8f8-4725-a6df-335af6c30a92" src="https://github.com/user-attachments/assets/346ad12b-8616-4ef7-b187-7d4832979449">
第二次
<img width="1336" alt="企业微信截图_f3e882bb-ae83-46a3-a508-19e306603eb0" src="https://github.com/user-attachments/assets/85e714b7-a037-4823-81db-ffa8dceef3d4">

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，方便的话把场景文件发给我们看看。

**Comment by lol666666** [comment]
那个请求的接口服务是我自己的服务，发过去 你也没办法debug，建议你们最好找个能看接口请求日志的服务就会发现了，平台是无法直接看出来的

**Comment by youliyuan-fit2cloud** [comment]
我们是看了服务端的日志和接口的控制台日志都没有复现该问题。只是想看下你这个场景有没有配置类似循环控制器的步骤，或者脚本。

**Comment by youliyuan-fit2cloud** [comment]
建议升级到最新v2.10.17-lts版本。
我们MeterSphere v3.1版本也发布了，强烈建议使用v3版本。
