### ISSUE TITLE
[QUESTION]修改了登录页后，重新构建framework，但是登录页修改的地方没有构建上去，使用的 mvn clean install命令构建的framwork

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32271]
### 请描述您的问题

修改了登录页后，重新构建framework，但是登录页修改的地方没有构建上去，使用的 mvn clean install命令构建的framwork,  请问下登录页修改后，怎么把修改的内容构建并发布上去

**Comment by liuruibin** [comment]
整体编译试试看

**Comment by zuoqiaoling** [comment]
整体编译也试过了

**Comment by zuoqiaoling** [comment]
整体编译用的这个命令：mvn clean install package
我尝试改了好几次登录页，最后，把整个登录页面的html部分注释了，编译构建后，登录页还是在的
看着像是没构建上去，有什么方法可以解决吗

**Comment by liuruibin** [comment]
这个需要你自己研究了
