### ISSUE TITLE
[FEATURE]编辑用例时，可以类似评审用例一样有【下一条】【上一条】按钮，可以快速的进入用例中

### ISSUE THREAD

**Issue by vilian00** [metersphere/metersphere#32281]
### MeterSphere 版本

v2.10.14-lts

### 联系方式

MeterSphere 交流群63：vilian

### 请描述您的需求或者改进建议

前置：用例已经写了大部分，但是发现有许多条用例需要重新编辑
需求：对A用例编辑完后，保存成功，进入到查看页面，建议在该页面增加【下一条】【上一条】这样的按钮，可以快速的进入用例中

**Comment by luty2018** [comment]
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/e403a0c3-d07c-4b30-b689-fd8ad02ae011">

我们在v3支持了这个功能， 建议您使用v3版本。
