### ISSUE TITLE
[BUG]自动化场景导入jmx文件，提示解析数据出错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3229]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题
自动化场景导入jmx文件，提示解析数据出错
**Bug 重现步骤**
1.  自动化场景导入jmx文件 文件见附件
2. 提示解析数据出错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
导入成功
**截图**
如果有截图，请附上截图.
<img width="828" alt="11" src="https://user-images.githubusercontent.com/83771182/119769899-f0b74000-beed-11eb-9e16-16f31273fa82.png">

[View Lenovo Website_Search DeskTop.zip](https://github.com/metersphere/metersphere/files/6551263/View.Lenovo.Website_Search.DeskTop.zip)

**Comment by zyyfit** [comment]
您好，目前不支持导入压缩文件，请导入原始jmx文件

**Comment by yaoyi111** [comment]
我导入的就是jmx文件，不是压缩文件。



***@***.***
 
发件人： zyyfit
发送时间： 2021-05-27 18:24
收件人： metersphere/metersphere
抄送： yaoyi111; Author
主题： Re: [metersphere/metersphere] [BUG]自动化场景导入jmx文件，提示解析数据出错 (#3229)
您好，目前不支持导入压缩文件，请导入原始jmx文件
―

**Comment by wangzhen-fit2cloud** [comment]
由于jmx中使用了额外的插件，该插件未包含在我们的依赖中导致的报错。

**Comment by eosclover** [comment]
> 由于jmx中使用了额外的插件，该插件未包含在我们的依赖中导致的报错。

@wangzhen-fit2cloud 
目前有解决方案吗？我的jmx文件确实依赖了很多额外的插件 
![image](https://user-images.githubusercontent.com/25951682/142818574-2d43dd26-2ba7-456c-acc4-00c80a21409f.png)
