### ISSUE TITLE
[QUESTION] V3.0.1无禅道默认缺陷模板，缺陷同步至禅道时，如何设置“影响版本”

### ISSUE THREAD

**Issue by XiaoHuiZhuang** [metersphere/metersphere#32291]
### 请描述您的问题

V3.0.1无禅道默认缺陷模板，缺陷同步至禅道时，如何设置“影响版本”

**Comment by song-cc-rock** [comment]
> ### 请描述您的问题
> V3.0.1无禅道默认缺陷模板，缺陷同步至禅道时，如何设置“影响版本”

目前V3.0.1版本不支持默认模板, 只支持在模板中手动配置 “影响版本” 字段, 参考配置如下: 
![image](https://github.com/user-attachments/assets/52ad72d0-0fcc-4a13-a90d-b621d6bc84f0)
![image](https://github.com/user-attachments/assets/f5f7b84e-b2c8-4799-8ce3-ca4faea78786)

**Comment by XiaoHuiZhuang** [comment]
谢谢
