### ISSUE TITLE
[BUG]通过xmind或excel导入用例，如果用例里包含同名的用例，而用例ID不同，可以保存成功

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#32296]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

1、在脑图模式和非脑图模式下新建同名用例都保存不成功
2、导入文件，如果文件里同名用例的用例ID也相同，会提示重复；如果同名用例的ID不同，会都保存（缺陷）。

### 重现步骤

1、在脑图和非脑图模式下的同一个目录下面创建同名用例是不允许的。
<img width="952" alt="e9d594a43b699658f4b7cc7817e7ebd" src="https://github.com/user-attachments/assets/bd092f48-965d-4eb1-8f07-3ba58ecc02b2">

2、使用excel或xmind导入新建，这样可以在同一个模块下保存同名的功能用例，这样是有问题的。
![image](https://github.com/user-attachments/assets/b5f91b11-48a2-4403-b5ee-678ff92eedc0)
![image](https://github.com/user-attachments/assets/961d5c40-023e-4c4e-b113-e78184a0fc41)

### 期待的正确结果

同一个目录下不允许有同名的用例，这个规则要对所有创建用例的途径保持一致。

**Comment by youliyuan-fit2cloud** [comment]
你好，ID 唯一，允许用例名称同名。脑图的重名提示有没有可能是点击了两次导致的？

**Comment by linfengjjj** [comment]
由老师，情况是这样的：
1、目前同一个目录，手动添加用例的时候非脑图模式下是不允许名字重复的，如果导入的时候重复了，以后再手动修改用例内容的时候又会提示用例名重复，这样会让用户觉得很矛盾，标准不一致。
2、“脑图的重名提示有没有可能是点击了两次导致的”，这个我在最新版本里试过，没有重复点击，只要我在脑图里同一个模块下新增一个同名用例，一定会提示重复，无法保存。
3、用户是希望标准统一，如果同一个目录下不允许用例名重复，那么非脑图、脑图、文件导入这些渠道都应该不允许用例名重复，保持统一，不然他们用户会觉得一定是哪一边有bug。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/7a957ccc-d711-4b6d-bbe2-072ccc9f29c0)
你好，经过最终确认，判断重复的规则是 ：同时判断模块，名字，用例等级，步骤，备注一样才算重复。
xmind导入确实存在判断错误的问题，后续版本解决；
excel没有此问题，请检查下导入的文件是否满足上述判断条件。

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
