### ISSUE TITLE
[BUG]菜单显示有问题

### ISSUE THREAD

**Issue by alexwishes** [metersphere/metersphere#323]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.0-b610

**Bug 描述**
简要描述您碰到的问题
给自己授权所有类型的测试角色后, 无法看到测试的菜单, 需要退出登录再进来才能看到

**Bug 重现步骤**
1. LDAP配置成功
2. 通过admin帐号给LDAP账号授权系统管理员
3. 切换该LDAP帐号登录
4. 给自己授权测试经理/测试人员等角色, 提交
5. 无法看到测试菜单

**期待的正确结果**
正确情况下应该是什么样的？
授权完角色后, 刷新页面即可看到菜单

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前新增角色的话确实是需要重新登录才会生效的
