### ISSUE TITLE
[BUG]接口场景引用，被引用场景不显示编程类型

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#32317]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

接口场景引用带脚本的场景，被引用场景不显示编程类型
![image](https://github.com/user-attachments/assets/d1dd6918-22de-443e-b803-e5551aed5bbe)
![image](https://github.com/user-attachments/assets/2e30f60f-1a06-4c50-a25a-8e4221300a02)

### 重现步骤

接口场景引用带脚本的场景，被引用场景不显示编程类型

### 期待的正确结果

接口场景引用带脚本的场景，被引用场景正常显示右边侧边栏,或者显示脚本语言类型

**Comment by 13290445582** [comment]
您好，已知问题，正在讨论是否需要优化，等待排期中，感谢理解。

**Comment by youliyuan-fit2cloud** [comment]
不做处理，感谢理解和支持。
