### ISSUE TITLE
[BUG]环境配置下通用配置的CSV类型变量，若接口自动化内只是自定义脚本，那么该变量无法在接口自动化中被使用

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32312]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

环境配置下通用配置的CSV类型变量，在接口自动化（只有循环控制器与自定义脚本步骤）中无法读取csv中定义好的值，若添加到环境变量内是可以使用的。

### 重现步骤

1、在某个环境下的通用配置，创建CSV类型的接口变量

2、接口自动化内只添加自定义脚本与循环控制器

3、执行查看结果

4、循环外添加一个HTTP请求，循环下的脚本中只能使用csv中第一个变量值

### 附加信息

添加变量：
<img width="698" alt="image" src="https://github.com/user-attachments/assets/beccb899-4866-4250-8a11-7c1887d9b664">
循环打印：
<img width="982" alt="image" src="https://github.com/user-attachments/assets/0eb42a3f-1231-4f6b-9163-97ca8df363c2">

**Comment by 13290445582** [comment]
您好，问题已复现并提交，等待排期修复中，感谢理解。

**Comment by luty2018** [comment]
这个问题v2不做修改，可以提需求在v3实现。
v2建议用文件管理来绕过。
