### ISSUE TITLE
[BUG]【接口自动化】新导入的接口场景，环境配置不可用

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32321]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

是

### 问题描述

项目A: 导出接口自动化，接口自动化文件A； 导出接口定义，接口定义文件B；环境配置设置了多个模块的http配置
项目B：导入A文件，导入B文件
在项目B查看接口自动化A文件，使用环境变量，发现接口的域名没按环境配置来显示
原因：导入的接口定义文件B 接口ID 跟 接口场景A文件里的 接口ID 不一致
有什么方法可以解决吗

### 重现步骤

项目A: 导出接口自动化，接口自动化文件A； 导出接口定义，接口定义文件B；环境配置设置了多个模块的http配置
项目B：导入A文件，导入B文件
在项目B查看接口自动化A文件，使用环境变量，发现接口的域名没按环境配置来显示
原因：导入的接口定义文件B 接口ID 跟 接口场景A文件里的 接口ID 不一致
有什么方法可以解决吗

**Comment by youliyuan-fit2cloud** [comment]
你好，环境配置导入目前是不支持模块的配置导入，因为考虑到项目之间的模块信息不一致，导入后也会有问题。
关于导入场景用例（接口自动化）逻辑是这样的，接口自动化的场景用例导入时如果场景有引用的接口CASE，我们会同步导入接口case及其接口定义到接口定义模块（相当于复制一份出来），不需要再次手动导入项目A中的接口定义。所以不会有接口ID不一致的问题。
