### ISSUE TITLE
[BUG]环境通用配置下配置CSV类型变量，接口自动化的循环控制器下有几个步骤，取值就是跳过几行数据

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32323]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

环境通用配置下配置CSV类型变量，接口自动化的循环控制器下有几个步骤，取值就是跳过几行数据。如果将通用配置修改为场景变量则没有这个问题。

### 重现步骤

1、环境通用配置下配置CSV类型变量
2、接口自动化加循环控制器，并在循环控制器下添加三个步骤
3、第一个步骤使用csv里面的变量，其他两个是否使用不影响
4、观察执行结果
5、将通用配置的csv变量改为场景csv变量，执行观察结果。

### 附加信息

步骤内容：
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/d5860bb0-fc59-4b2c-ab23-fee595365071">

<img width="975" alt="image" src="https://github.com/user-attachments/assets/5aa88b0c-8509-47ce-ba80-69c872d96cbf">

**Comment by 13290445582** [comment]
您好，问题已复现并提交，等待排期后续版本修复，感谢理解。

**Comment by luty2018** [comment]
这个问题v2不做修改，可以提需求在v3实现。
