### ISSUE TITLE
[BUG]【测试用例-评审】系统预有的评审里，默认是有评审人，进入评审内容里，没有显示评审人。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32332]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

【测试用例-评审】系统预有的评审里，默认是有评审人，进入评审内容里，没有显示评审人。

### 重现步骤

【测试用例-评审】系统预有的评审里，默认是有评审人，进入评审内容里，没有显示评审人。
![image](https://github.com/user-attachments/assets/20c14425-d565-44ff-be1a-26d03379692f)
![image](https://github.com/user-attachments/assets/36df19eb-6d46-419a-8bab-d6c60efb178f)

**Comment by youliyuan-fit2cloud** [comment]
你好，示例项目中数据仅作参考，新数据没有该问题。后续考虑优化一下。

**Comment by 13290445582** [comment]
您好，该问题已修复，请升级。
