### ISSUE TITLE
[FEATURE] 测试计划执行，消息配置模板，没有测试报告链接配置

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#32335]
### MeterSphere 版本

3.0.1

### 请描述您的需求或者改进建议

测试计划执行，消息配置模板，没有测试报告链接配置

![image](https://github.com/user-attachments/assets/419cfb1b-cd1a-4a43-a2a7-52e63b2069cb)

### 请描述你建议的实现方案

增加消息通知报告链接，同v2

![image](https://github.com/user-attachments/assets/46e9b293-bf9f-40e5-aa1a-bcfac8c96fe1)

**Comment by xhy12** [comment]
配置项没有报告链接选项，

**Comment by youliyuan-fit2cloud** [comment]
后续版本会支持。

**Comment by youliyuan-fit2cloud** [comment]
最新发布的v3.2 中已支持配置报告链接
