### ISSUE TITLE
[BUG]接口同步时，1.不能正常识别get ,post模式，2. 接口字段注解变更后，不能同步到平台上；

### ISSUE THREAD

**Issue by hclzm** [metersphere/metersphere#32339]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

是

### 问题描述

如果接口注解是RequestMapping的情况下，默认是get方式，而接口中类型是requestbody，导致字段注解不能正常同步；改成postmapping后，requestbody类型的参数注解能正常，但修改字段注解内容后，或原来没有注解，增加注解后，同步在覆盖模式下，接口字段注解未更新；

### 重现步骤

如果接口注解是RequestMapping的情况下，默认是get方式，而接口中类型是requestbody，导致字段注解不能正常同步；改成postmapping后，requestbody类型的参数注解能正常，但修改字段注解内容后，或原来没有注解，增加注解后，同步在覆盖模式下，接口字段注解未更新；

**Comment by fit2-zhao** [comment]
@RequestMapping 没有指定具体的HTTP方法时，默认接收所有类型的请求，这种是无法准确识别到具体类型的。

**Comment by hclzm** [comment]
那第二个问题，就是修改注解后或增加新字段后，接口同步显示是覆盖，但是实际情况是接口没有更新，这个问题什么时候能解决呢？

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把你这个文件截图发一下？不确定你这个注释内容是指哪里？ 我们目前版本导入的时候，请求体body中不支持json中带注释。。。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
