### ISSUE TITLE
[BUG]用例excel导入,文件中同时存在两种编辑模式时，TEXT模式的用例导入后，步骤描述和预期结果的内容为空

### ISSUE THREAD

**Issue by LiuMei1** [metersphere/metersphere#32338]
### 联系方式

1812446981@qq.com

### MeterSphere 版本

v3.0

### 使用外置数据库

是

### 问题描述

描述：用例-excel导入,导入的文件中同时存在编辑模式为STEP和TEXT的数据，导入完成后，查看用例，TEXT模式的导入的案例，步骤描述和预期结果的内容为空，文件内大约只有150左右的用例，两种模式各占一半

![text](https://github.com/user-attachments/assets/02b74be4-29c1-4e27-b63d-7ef472bd4f05)

### 重现步骤

操作步骤:
1、第一次新增导入时，导入的文件中同时存在编辑模式为STEP和TEXT的数据，TEXT模式的案例的编辑模式不填为空（因为表头写了为空默认为TEXT模式），导入后STEP的用例展示正常，TEXT模式的用例步骤描述和预期结果内容为空，异常
2、后续ID覆盖导入时，编辑模式填写了TEXT，但是导入数据依旧异常
3、只有TEXT模式的案例，且编辑模式不填为空,覆盖导入，数据依旧异常
4、只有TEXT模式的案例，且编辑模式填入TEXT,覆盖导入，数据正常

### 期待的正确结果

可以混合导入两种编辑模式的案例

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，导入文件默认为空时，导入用例错误。下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
