### ISSUE TITLE
[BUG]【测试用例-评审】切到脑图模式，登录-退出登录或其他用例，页面将描述内容的 html标签也显示出来了

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32333]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

【测试用例-评审】切到脑图模式，登录-退出登录或其他用例，页面将描述内容的 html标签也显示出来了

### 重现步骤

【测试用例-评审】切到脑图模式，登录-退出登录或其他用例，页面将描述内容的 html标签也显示出来了
![image](https://github.com/user-attachments/assets/ef87eb6c-d3dc-4d6b-9bbd-3f755f346ed2)

**Comment by youliyuan-fit2cloud** [comment]
你好，已知问题，前置条件和备注是文本框格式，后续会优化

**Comment by luty2018** [comment]
现在只保留了<P>标签， 做不到完全不展示，否则富文本内容无法还原展示。
