### ISSUE TITLE
接口自动化中引入的请求方法都被写死 get

### ISSUE THREAD

**Issue by hztony** [metersphere/metersphere#32343]
### 联系方式

13735892260

### MeterSphere 版本

2.10.16

### 使用外置数据库

否

### 问题描述

接口自动化场景，新增的脚本使用的方法都被写 Get，导致引用的 Post 之类的接口全部无效

### 重现步骤

1、创建接口自动化场景；
2、引入 Post 方法的接口 或者 使用自定义接口 ；
3、保存运行。

### 期待的正确结果

1、操作日志中应该是 Post 方法

### 相关日志输出

```shell
1、日志输出的是 Get 方法，导致请求异常。
```

**Comment by 13290445582** [comment]
您好，在本地测试测试环境复现了下，导入的API/CASE/自定义请求/脚本中的API定义导入都是正常的，后台日志也是POST方法，未遇到该问题。请提供下具体的场景和接口环境复现的录屏也可以看看。

**Comment by hztony** [comment]
![协议方法](https://github.com/user-attachments/assets/2480685f-1b11-48e2-98ae-708874665189)
运行截图

**Comment by 13290445582** [comment]
您好，非常抱歉，未复现该问题。请问所用环境是如何配置的，是不是设置重定向了。麻烦可以新创建一个环境，新建接口，新建接口场景导入下，查看是任何接口都会被从post修改为get嘛。

**Comment by hztony** [comment]
1、安装方式，按照你们官方文档部署的，没有使用任何外部中间件；
2、这个问题在是 2.10.16 版本上遇到的，以前的版本（2.10.8）是正常的；
3、因为好久没升级，最近做了一次升级，发现这情况

**Comment by 13290445582** [comment]
![image](https://github.com/user-attachments/assets/55ac3170-1bce-42fa-b029-412022772a92)
您好，从请求上看起来，如上图箭头所示，应该是接口重定向了。

**Comment by hztony** [comment]
遇到这种情况，如何处理

**Comment by 13290445582** [comment]
您好，重定向是您自己对接口的处理，需要您解除掉您当前使用接口的重定向。

**Comment by hztony** [comment]
好的
