### ISSUE TITLE
[BUG] 同一个模板的本地用例在a项目能导入，在b项目不能导入

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#32347]
### MeterSphere 版本

3.0.1

### 使用外置数据库

否

### 问题描述

同一个模板的本地用例在a项目能导入，在b项目不能导入
[Metersphere_case_测试项目.xlsx](https://github.com/user-attachments/files/16406969/Metersphere_case_.xlsx)

### 重现步骤

1、qa环境在项目：PDC 导入用例能够正常导入
2、在项目：Youly测试项目导入，提示成功，但是页面不展示用例
![image](https://github.com/user-attachments/assets/c12c0e9a-c566-47ec-b00a-d9fda66b5e4e)

### 期待的正确结果

应该能够能够顺利导入用例

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/8c2acd78-2f72-4061-b85a-5e8c5c39d110)

你好，请按照上诉提示说明检查下。
