### ISSUE TITLE
[BUG]API-TEST 批量复制、批量移动带文件夹路径过去,目前api-test服务下的接口复制和移动没有带文件夹路径过去，复制过去后会导致用例需要重新分类

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#32349]
### 联系方式

13716054767

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

<img width="1400" alt="image" src="https://github.com/user-attachments/assets/1ca014a3-7bd8-4e57-87e2-999bcbd5f215">
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/c7bf4a33-e5f9-45de-9cfb-d93d3e0dbc85">
<img width="560" alt="image" src="https://github.com/user-attachments/assets/dfb058c8-b3f8-43ec-9523-2ffb83f2c4ef">

### 重现步骤

第一步选择批量复制指定目录
第二步选择全部可见测试用例，然后选择批量复制
第三步在复制的弹窗下，选择指定文件夹，点击确定
第四步检查复制到指定文件夹下是否存在复制过去的目录，检查后发现文件夹用例数增加但是没有复制过去的目录，复制过去的用例都在一块，没有按复制目录的层级结构展示例如a-->b 复制b到c 没展示成c->b 而是所有用例都在c下面，b目录丢失

### 期待的正确结果

复制过去后，被复制的测试用例可以按复制的文件夹层级结构展示，主要作用：当用例比较多的时候，会花大量时间筛选，增加了测试用例编写的耗时

### 相关日志输出

```shell
暂无
```

### 附加信息

暂无

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前还不支持带文件夹的移动和复制，只是单纯的移动和复制接口，感谢理解和支持。

**Comment by lol666666** [comment]
有支持的时间表吗

**Comment by youliyuan-fit2cloud** [comment]
> 有支持的时间表吗

抱歉，v2版本没有规划。
