### ISSUE TITLE
[BUG]接口扩展协议添加断言时，场景无法保存断言且前端异常

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32348]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

接口扩展协议添加断言时，场景无法保存断言且前端异常

### 重现步骤

如附件

### 附加信息

https://github.com/user-attachments/assets/5cee07a6-962a-4037-8f0b-15c7fffac654

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，Redis插件版本是哪个？

**Comment by youliyuan-fit2cloud** [comment]
下个版本中修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
