### ISSUE TITLE
接口自动化，复制过来的接口，及自定义的接口都是get请求，无法改变请求方式

### ISSUE THREAD

**Issue by ttllong** [metersphere/metersphere#32342]
### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

否

### 问题描述

接口自动化，接口导入的接口，及自定义的接口都是get请求，无法改变请求方式

### 重现步骤

接口自动化，接口导入的接口，及自定义的接口都是get请求，无法改变请求方式

**Comment by 13290445582** [comment]
您好，在本地测试测试环境复现了下，导入的API/CASE/自定义请求/脚本中的API定义导入都是正常的，后台日志也是POST方法，未遇到该问题。请提供下具体的场景和接口环境复现的录屏也可以看看。
