### ISSUE TITLE
[BUG]点击复制一个至少有5个场景数据，然后在复制的新用例上保存，保存会失败

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#32354]
### 联系方式

13716054767

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

第一步复制：
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/24c35240-41d8-4e7b-8d78-f7fa1a1b6585">
第二步在复制后的新用例点击保存，create接口总是失败
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/c71f68b6-52bb-4ded-abf5-e9e230ee1cca">

### 重现步骤

第一步复制：
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/24c35240-41d8-4e7b-8d78-f7fa1a1b6585">
第二步在复制后的新用例点击保存，create接口总是失败
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/c71f68b6-52bb-4ded-abf5-e9e230ee1cca">

### 期待的正确结果

点击保存后，立即保存成功

**Comment by lol666666** [comment]
点击多次保存总是失败<img width="1248" alt="image" src="https://github.com/user-attachments/assets/b98d9b3f-de26-4662-a7b5-5fd225ae569a">

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，是所有场景都复制失败吗？如果只是这个场景失败，请把场景文件发一下，感谢理解和支持。

**Comment by lol666666** [comment]
所有场景都会复制失败，你没有复现是不是你的用例没有引用其他用例？我的用例都是引用其他公共用例，2.17版本只优化了update慢的问题，应该没有优化create这个接口
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/dbf9e437-f6bf-4f8e-9966-db4effbc91ff">
未优化的create代码,由于复制调用的是create接口所以，走的是未优化的代码就存在保存满的问题：
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/8c0d7aa1-d8b9-459c-98ec-6518b0c26a06">

优化的update代码,update不存在保存慢的问题
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/79a65133-5934-4d2f-b71f-252ce9518a17">

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/ddf10b4d-76d3-4ca9-b220-7764be403cac)
场景中引用的情况都有，确实没有复现。

**Comment by Somebody-JIAN** [comment]
场景里有多少步骤？ 套了有多少层？    

create接口报错，有没有比较具体的报错信息？

**Comment by lol666666** [comment]
总共5个大场景，每个场景不超过5层

**Comment by lol666666** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/353295735-ddf10b4d-76d3-4ca9-b220-7764be403cac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDYzNTMsIm5iZiI6MTcyMjM0NjA1MywicGF0aCI6Ii81NDYxMjg2NC8zNTMyOTU3MzUtZGRmMTBiNGQtNzZkMy00Y2E5LWIyMjAtNzc2NGJlNDAzY2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEzMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZGRiNGUwMWJiOGZhMTI3MzM4NWE2NzEwYWYyZDI5NDI1Y2U4NmU5MmJkYjE0OTQ0N2RhNTdkOWNkOWFhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qwjX0NyfP--Vu3StBHms4hmn9hwwUgPa6mOXU2bGsLE) 场景中引用的情况都有，确实没有复现。

你的导入的引用的方法，是否为公共方法，并且为多个流程引用这些公共场景，这样relationship_edge的依赖关系节点才会多，才会大量查询relationship_edge的数据

**Comment by Somebody-JIAN** [comment]
我明白您的意思了。

目前确实没有针对这种类型以及这种量级的数据做优化。并且受限于2.10的业务架构和数据结构，我们也没有好的优化方案。

如果您有好的修改方案，欢迎提pr

您也可以试试在v3.1版本中操作一下。v3.1版本我们重构了很多，包括但不限于数据库表结构、存储格式、存储方式等。
虽然不保证v3.1版本不会出现您的问题，但是在v3的架构中，我们优化起来会相对容易得多

**Comment by Somebody-JIAN** [comment]
当然，由于v2.10和v3.1的数据库结构有差异，无法通过正常升级到v3.1

如果您v2.10中有很多重要的数据导致无法正常体验v3.1,  您也可以通过企业微信群联系一下我们的工作人员，看看有什么更好的办法

v3.1版本吸取了v2.10及以前版本中的教训，重新设计并进行开发。 

站在我们开发者角度上，我们是特别希望您能体验一下v3.1版本，给出宝贵意见。
