### ISSUE TITLE
[FEATURE]归档怎么权限控制

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#32367]
### MeterSphere 版本

3.1.0

### 请描述您的需求或者改进建议

归档怎么权限控制

### 请描述你建议的实现方案

这个不是谨慎操作的么是不是有权限控制一下

### 附加信息

![image](https://github.com/user-attachments/assets/5136d27b-9bbc-40af-8491-4dedec393d05)
![image](https://github.com/user-attachments/assets/ff247d8c-363f-4905-986f-8fb96e019842)

**Comment by liuruibin** [comment]
目前没有单独设置权限位，和编辑操作共用同一个

**Comment by Hyyfit** [comment]
对于计划而已，状态的变更也是一种编辑，所以归档是通过编辑的权限来控制的。
设计是 “已完成”状态的计划，才会显示归档的操作；归档的操作有确认弹窗，已经提示用户需要谨慎操作了。
