### ISSUE TITLE
[BUG]测试计划报告保留时间范围未启用

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#32364]
### MeterSphere 版本

3.1.0

### 使用外置数据库

否

### 问题描述

测试计划报告保留时间范围未启用，设置是保留3天，实际报告都是10几天前的

### 重现步骤

测试计划报告保留时间范围未启用，设置是保留3天，实际报告都是10几天前的

### 期待的正确结果

正确删除报告

### 附加信息

![image](https://github.com/user-attachments/assets/be8cd778-1982-47ff-8eb0-e38550766fe0)
![image](https://github.com/user-attachments/assets/e6df59f4-4a91-4dc8-9bf1-53b751b271eb)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个报告保留时间范围修改后，第二天凌晨才会执行该清理过期的报告。请问下是否还未到生效时间？

**Comment by legend818** [comment]
设置好几天了，你看看你们测试环境的

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，复现了，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
