### ISSUE TITLE
[BUG]XMl响应体，断言数组中对象属性不准确

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#32373]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

响应体为xml,数组下包含多个对象，对于对象属性断言不准确

### 重现步骤

1.设置mock 响应体为：
<?xml version="1.0" encoding="UTF-8"?>

<students>
 <student>
   <name>张三</name>
   <age>20</age>
    <grade>A</grade>
 </student>
 <student>
  <name>李四</name>
  <age>21</age>
  <grade>B</grade>
 </student>
</students>
2.使用文档结构断言xml ,断言张三 age 等于21 成功了

![image](https://github.com/user-attachments/assets/b623196c-9ebb-4dfa-8fbe-96e1d3ab675a)

### 期待的正确结果

期望断言张三 age等于21 是失败的

**Comment by fit2cloud-lijiaxin** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<students>
 <student>
   <name>张三</name>
   <age>20</age>
    <grade>A</grade>
 </student>
 <student>
  <name>李四</name>
  <age>21</age>
  <grade>B</grade>
 </student>
</students>`

**Comment by fit2cloud-lijiaxin** [comment]
响应体：
<?xml version="1.0" encoding="UTF-8"?>

<students>
 <student>
   <name>张三</name>
   <age>20</age>
    <grade>A</grade>
 </student>
 <student>
  <name>李四</name>
  <age>21</age>
  <grade>B</grade>
 </student>
</students>

**Comment by 13290445582** [comment]
您好，问题已复现并提交，等待排期，后续版本修复。

**Comment by 13290445582** [comment]
![image](https://github.com/user-attachments/assets/3e4f2411-790a-4c37-9c6d-c860843f3495)
您好，目前的实现是数组如果没有写参数名的话，会匹配所有选项，如果要实现匹配对应下标的选项，可以参数名写上 [下标]
