### ISSUE TITLE
[BUG]编辑接口自动化的时候，打开多个接口的入参，会出现滚动条乱滚，而且大片空白的情况

### ISSUE THREAD

**Issue by damonwong19990909** [metersphere/metersphere#32370]
### MeterSphere 版本

版本:   v2.10.14-lts-a7298117

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/0d7995da-2808-46d1-a016-6f4a969311a6)

### 重现步骤

展开多个接口的请求入参

**Comment by liuruibin** [comment]
您好，我们已收到您的问题，并尝试复现，很遗憾的是并没有复现成功

之前我们曾经遇到过类似的问题，但是碍于技术选型的局限性，以及出现这种问题的概率偏低，所以我们最终的方案是不处理

您可以尝试使用我们的v3.1。 我们在v3.1带来了许多激动人心的新功能和改进

欢迎您体验v3.1并提出宝贵意见
