### ISSUE TITLE
[QUESTION]测试计划执行时，有概率卡住

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32381]
### 请描述您的问题

我遇见过几次，测试计划执行过程中一条用例一直在running状态，例如
查看日志：
api-test的日志如下，可以看到7da0146c-1456-477e-8a01-4e6af1f740d9已经下发给node-controller了
![image](https://github.com/user-attachments/assets/9ce39093-4361-4997-a7a4-59081bca7963)

node-controller日志
![image](https://github.com/user-attachments/assets/668c1146-5fb8-4be6-8d07-a7e06aa0df7b)

可看到node也接受到了任务，执行完毕进行了kafka回传，但是apitest好像丢失了这条kafka消息，并没有执行下一条用例，导致当前用例一直为running状态

**Comment by ijwstl** [comment]
版本为10.16-lts

**Comment by fit2-zhao** [comment]
从日志来看像是结果内容比较大推送到KAFKA 失败了，可以尝试修改下 “/opt/metersphere/docker-compose-kafka.yml” 如图中所示参数：

![image](https://github.com/user-attachments/assets/22797e3c-7a47-47ff-98a5-93505acf882e)
