### ISSUE TITLE
[FEATURE]不同模块新增相同url接口失败，接口重复判断有缺陷，需要按模块区分判断是否重复

### ISSUE THREAD

**Issue by tencen8888** [metersphere/metersphere#32387]
### MeterSphere 版本

v3.0.1-080e6767

### 使用外置数据库

否

### 问题描述

需要按模块区分判断是否重复。不同模块，相同url接口可新增。
![image](https://github.com/user-attachments/assets/227f6b43-efa7-4b6a-84b5-9c9d172ea436)

### 重现步骤

1 接口测试，多个不同模块都使用相同url接口，但请求参数不同，保存接口失败。
2 这个bug 需要判断是否是否是相同模块的接口。存在不同场景使用相同接口，传参不同
麻烦尽快修复下，接口测试走不通了

**Comment by youliyuan-fit2cloud** [comment]
你好，这个功能后续版本有规划的，敬请期待～
