### ISSUE TITLE
[BUG]【接口自动化】场景测试 请求地址多了https://null

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32395]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

是

### 问题描述

![c84444db-673c-4200-b4c1-aad07b14549a](https://github.com/user-attachments/assets/bcf5b4bc-0a8d-475e-8e9e-be6d1609313d)

![935069c6-6f4b-4d6c-bc5a-6fbdbe15a504](https://github.com/user-attachments/assets/45cf98fe-2b9f-4a4c-a2cc-62918d405c77)

### 重现步骤

接口自动化场景测试 请求地址多了https://null

**Comment by zuoqiaoling** [comment]
你好，请问下这条问题可以删掉或者重新编辑吗？问题描述需要再改一下，谢谢了

**Comment by 13290445582** [comment]
您好，本地测试未发现该情况，请提供下复现的场景帮助复现下，感谢。
