### ISSUE TITLE
[FEATURE]建议考虑一下用户的实际使用场景，缺陷管理中支持常用附件类型预览，以及附件支持上传到第三方 OSS

### ISSUE THREAD

**Issue by Moon-du** [metersphere/metersphere#32391]
### MeterSphere 版本

v3.1.0-a8910b83

### 联系方式

MeterSphere 交流群26 昵称:长安

### 请描述您的需求或者改进建议

需求 1：建议缺陷管理中支持常用附件类型预览,mp4 格式是上报 bug时最常见的附件格式，不支持在线预览，每次开发改 bug还要下载到本次才能看会很麻烦。
需求 2：附件支持上传到第三方 oss,在bug 数量比较多的时候（拿我们公司举例目前一个项目的 bug 数已经超过十几万个了）其中附件所占用的硬盘会非常大，去扩容机器的硬盘会很麻烦，如果能支持上传到第三方 oss动态扩容会很方便

### 请描述你建议的实现方案

1.支持常见附件类型在线预览
2.缺陷上传附件时支持上传到关联的第三方 oss

**Comment by liuruibin** [comment]
1. 支持常见类型预览我们后续会陆续实现
2. 三方oss我们现在仅支持minio，minio支持s3协议。你可以把minio配置直接改成s3相关的即可

**Comment by Moon-du** [comment]
收到谢谢
