### ISSUE TITLE
[BUG]OAUTH2 建议用 OAuth 2.0 规范命名

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#32397]
### 联系方式

shenkaibo

### MeterSphere 版本

v3.1

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/21a74feb-0b26-4ade-a7d4-846914330b3c)

### 重现步骤

OAUTH2 建议用 OAuth 2.0 规范命名

### 期待的正确结果

![image](https://github.com/user-attachments/assets/81964dc7-0a73-45a3-8650-32d42b8bede6)

**Comment by liuruibin** [comment]
你说的有道理

**Comment by 13290445582** [comment]
感谢反馈，V3.2版本优化下。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
