### ISSUE TITLE
[QUESTION]看的官网介绍的社区版也是支持自定义用例和缺陷模板的，但是实际在缺陷模板页面并没有看到可以新建和编辑的功能

### ISSUE THREAD

**Issue by Moon-du** [metersphere/metersphere#32398]
### 请描述您的问题

看的官网介绍的社区版也是支持自定义用例和缺陷模板的，但是实际在缺陷模板页面并没有看到可以新建和编辑的功能，是现在版本还不支持， 后续版本支持吗
![WX20240802-113955](https://github.com/user-attachments/assets/fc6f0395-c09c-484e-a12b-45628bb7359e)
![WX20240802-114210](https://github.com/user-attachments/assets/1de3f13d-afd7-4e06-bc95-4b88531c6215)

**Comment by song-cc-rock** [comment]
> ### 请描述您的问题
> 看的官网介绍的社区版也是支持自定义用例和缺陷模板的，但是实际在缺陷模板页面并没有看到可以新建和编辑的功能，是现在版本还不支持， 后续版本支持吗 ![WX20240802-113955](https://private-user-images.githubusercontent.com/69743019/354454572-fc6f0395-c09c-484e-a12b-45628bb7359e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Nzc1ODQsIm5iZiI6MTcyMjU3NzI4NCwicGF0aCI6Ii82OTc0MzAxOS8zNTQ0NTQ1NzItZmM2ZjAzOTUtYzA5Yy00ODRlLWExMmItNDU2MjhiYjczNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODczYmU4NDQzYTRjMTdhZWUzZDNkOTY3MzMwMjMzZGJjN2YzYTliMTkyMTRjM2FjYjViYzM3YzZkYzQwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HXAh0pW_7tIIlRpkVeoWwaG3HM99EtukqDT2tEM4zxg) ![WX20240802-114210](https://private-user-images.githubusercontent.com/69743019/354454872-1de3f13d-afd7-4e06-bc95-4b88531c6215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Nzc1ODQsIm5iZiI6MTcyMjU3NzI4NCwicGF0aCI6Ii82OTc0MzAxOS8zNTQ0NTQ4NzItMWRlM2YxM2QtYWZkNy00ZTA2LWJjOTUtNGI4ODUzMWM2MjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1NDEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYWViMWU5YzMxZGRjNjJmNWRjMDM5OTViZDA4ZGIzZDQ5NjNlMDczZWI5ZWMyNmE0ZWNhYTUxNGY5MzA1OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HV6QlmSTUlg6rdPk0ShU49s4BBhWlL7wAjY_OG3r2-8)

"示例项目" 的项目模板开关并未启用, 所以无法在项目模板页面编辑, 需在组织模板页面开启项目模板后才能编辑, 或者统一用一套组织模板来维护项目模板
![image](https://github.com/user-attachments/assets/e0c5f598-77cf-4dff-84ac-737133acfcf7)

**Comment by Moon-du** [comment]
好的谢谢
