### ISSUE TITLE
[BUG]执行性能测试时会有部分请求报错Non HTTP response code: org.apache.http.conn.ConnectTimeoutException

### ISSUE THREAD

**Issue by fairyflying** [metersphere/metersphere#324]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.1
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  并发100，压测时长1分钟，未设置RPS上限，资源池为LOCAL
2. 执行性能测试
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
不应该有Non HTTP response code: [org.apache.http.conn.ConnectTimeoutException]
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44046698/91926820-af9d5100-ed0a-11ea-8263-54251867d65f.png)
![image](https://user-images.githubusercontent.com/44046698/91926854-c774d500-ed0a-11ea-8617-ff0389b6f975.png)
![image](https://user-images.githubusercontent.com/44046698/91926902-e2dfe000-ed0a-11ea-9930-e87415c52ccd.png)

**Comment by wangzhen-fit2cloud** [comment]
出现该问题可以能是服务端在较大压力下响应超时了，可以在性能测试的高级配置中修改下超时时间配置后再进行测试

**Comment by fairyflying** [comment]
谢谢您的回复。配置和先前一样，超时时间我设置了10000ms但仍然有这个报错，麻烦看下
![111](https://user-images.githubusercontent.com/44046698/92320740-4002cb00-f056-11ea-96c9-fe1ed5922dbf.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，最新版本中已修改，请升级验证。

**Comment by jia9iZhang** [comment]
我也遇到了这个问题？请问如何解决？
版本：v2.9.0-426de152
