### ISSUE TITLE
[FEATURE]使用Metersphere的Jenkins插件创建接口自动化流水线执行报错，但是报错信息不明确，希望可以抛出明确的报错信息，方便排查

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32404]
### MeterSphere 版本

v2.10.17-lts

### 联系方式

14707070227

### 请描述您的需求或者改进建议

1. 使用最新版本的Metersphere和最新版本的Jenkins插件，并创建接口自动化流水线
2. 执行流水线发现如下报错：
![989f795b2b25924de3be982e36bd1d1](https://github.com/user-attachments/assets/dbad7da6-a500-454f-b510-d85fe2dade2e)
3. 查看后台日志也没有看到对应的报错信息
![1722584358099](https://github.com/user-attachments/assets/c4815eef-1220-4866-a452-d849541e9d5b)
4. 排查了很久之后才发现是客户权限不够

### 请描述你建议的实现方案

流水线执行报错，希望可以抛出明确的报错信息，日志能打印出来，方便排查

**Comment by liuruibin** [comment]
日志都有只是你没找到

**Comment by liuruibin** [comment]
权限问题属于一上来就应该排除的
