### ISSUE TITLE
[FEATURE]swagger导入接口时，建议增加contextPath

### ISSUE THREAD

**Issue by mjshusheng** [metersphere/metersphere#32407]
### MeterSphere 版本

v2.10.0-lts

### 请描述您的需求或者改进建议

项目上swagger导入的接口都缺少了前缀contextPath，希望导入的时候增加输入contextPath。

**Comment by luty2018** [comment]
您好， 请问可以提供Swagger文件给我们验证吗

**Comment by mjshusheng** [comment]
微服务接口分了很多组，导入的时候缺少了图片上的路径。













在 2024-08-08 12:58:30，"LuoTing" ***@***.***> 写

您好， 请问可以提供Swagger文件给我们验证吗

**Comment by luty2018** [comment]
> 微服务接口分了很多组，导入的时候缺少了图片上的路径。 在 2024-08-08 12:58:30，"LuoTing" ***@***.***> 写 您好， 请问可以提供Swagger文件给我们验证吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

没有看到图， 重新上传一下吧

github在进行贴图时会上传图片。可能是这一步操作出了问题，导致图片没看到
