### ISSUE TITLE
[BUG]当foreach循环的列表值是字符串时，使用计数器失效

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#32418]
### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

从前一个接口接收到的列表如["1232","12323","234324"]，在后续使用foreach和counter计数器，foreach遍历正常，但是counter计算器的值始终不变，不会递增

### 重现步骤

从前一个接口接收到的列表如["1232","12323","234324"]，在后续使用foreach和counter计数器，foreach遍历正常，但是counter计算器的值始终不变

**Comment by SloanGao** [comment]
![image](https://github.com/user-attachments/assets/027afde9-185d-46b9-a62e-064778bd53c8)
使用计数器取列表的值时，计数器的值一直不变

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/e33c9143-72b9-4ade-8c15-55133a9bd3ad)
你好，没有复现该问题，请检查下 计数器这里要输入默认开始/结束/增量的默认值。

**Comment by SloanGao** [comment]
試了不行，我的列表是從上一個接口提取的參數。如果是直接在場景變量裡面定義的我試了試OK
![image](https://github.com/user-attachments/assets/0b4cd93c-c087-4ea9-89a9-5168ef411c4c)
![image](https://github.com/user-attachments/assets/65f7887b-f415-4d35-aac1-ec065cf54c9d)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/0e70f50e-7027-4421-9189-9ac90f8ce4da)
我们也是这个场景，这是我们的测试结果。方便的话把具体场景发一下吧。

**Comment by SloanGao** [comment]
刚才我看了一下使用计数器变量的地方是当前场景引用的场景里面。我试着直接在被引用的场景100431里面的场景变量添加计数器就可以了
![image](https://github.com/user-attachments/assets/4dcdff5f-46a0-4f30-a812-1da9c14c091a)

另外还有一个问题项咨询一下，之前我场景变量计数器配置起始是从0开始，执行脚本后发现可以获取到值，现在从0开始不行，只能从1开始。这个计数器正常是从0开始还是1开始？

**Comment by youliyuan-fit2cloud** [comment]
> 刚才我看了一下使用计数器变量的地方是当前场景引用的场景里面。我试着直接在被引用的场景100431里面的场景变量添加计数器就可以了 ![image](https://private-user-images.githubusercontent.com/37204403/355405603-4dcdff5f-46a0-4f30-a812-1da9c14c091a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDA1NTMsIm5iZiI6MTcyMjk0MDI1MywicGF0aCI6Ii8zNzIwNDQwMy8zNTU0MDU2MDMtNGRjZGZmNWYtNDZhMC00ZjMwLWE4MTItMWRhOWMxNGMwOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDM2YTlmZmI0NGVhZmEyMzQ5YjNjNjUzNDE3Y2Q2Yzk0Y2RmYjQ4NmM0NDY1MGI4NGI2YTlmMGQ4NjBlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8E3OfUrTtL1Dhv6cQGNqxGliggbh4M1I1mG2wE-ib30)
> 
> 另外还有一个问题项咨询一下，之前我场景变量计数器配置起始是从0开始，执行脚本后发现可以获取到值，现在从0开始不行，只能从1开始。这个计数器正常是从0开始还是1开始？
0 开始的。
