### ISSUE TITLE
[FEATURE] 接口自动化的添加步骤按钮影响到了删除操作，希望可以优化一下

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32428]
### MeterSphere 版本

v2.10.17-lts

### 联系方式

14707070227

### 请描述您的需求或者改进建议

接口自动化的添加步骤按钮影响到了删除操作，导致想删除其中的用例删除不了，希望可以优化一下
![f208bcf2dea64f05a1fc4481d80d1ad](https://github.com/user-attachments/assets/a62001b6-f525-4f6b-8139-85cd9db35ecc)
添加步骤按钮当中的用例的这些操作都实现不了 
![image](https://github.com/user-attachments/assets/649d47b2-4c9f-49fd-85ac-ecb3ec8db4b3)

**Comment by luty2018** [comment]
感谢建议。我们优化一下。
