### ISSUE TITLE
[BUG]新建测试计划的【更多设置】中显示  UI/性能测试用例

### ISSUE THREAD

**Issue by xusongtao** [metersphere/metersphere#32424]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

新建测试计划的更多设置中显示UI/性能测试用例
![1722912518327](https://github.com/user-attachments/assets/c49b80a9-9f50-4982-991a-b088034f0015)

### 重现步骤

新建测试计划的更多设置中显示UI/性能测试用例

**Comment by liuruibin** [comment]
感谢提醒

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
