### ISSUE TITLE
[FEATURE]测试计划名称比较长时，计划内计划名称展示不全，建议优化

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#32435]
### MeterSphere 版本

v2.10.17-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

测试计划名称比较长时，计划内计划名称展示不全，建议优化为鼠标悬浮可展示全名或可以拉长展示框
![image](https://github.com/user-attachments/assets/37edb9ef-2d42-4f6a-887b-3f398181fbd7)

### 请描述你建议的实现方案

建议优化为鼠标悬浮可展示全名或可以拉长展示框

**Comment by liuruibin** [comment]
感谢提醒
