### ISSUE TITLE
[FEATURE]idea 插件 增加外层的公共返回响应 Response 泛型支持

### ISSUE THREAD

**Issue by wpcaishaoyu** [metersphere/metersphere#32438]
### MeterSphere 版本

v3.0

### 联系方式

15734080618@163.com

### 请描述您的需求或者改进建议

idea 插件解析代码，增加外层的公共返回响应 Response 泛型支持

**Comment by fit2-zhao** [comment]
具体参数格式是什么样的 发出来看一下。

**Comment by wpcaishaoyu** [comment]
就是一般公共的返回值，但是这个是统一在spring拦截返回处理，直接解析Controller获取不到这个最外层的返回值

**Comment by fit2-zhao** [comment]
了解了，这种不支持。

**Comment by fit2-zhao** [comment]
对于 Spring 里面常用实现接口 ResponseBodyAdvice 或 其他切面方式 去包装响应结果的并没有统一格式规范，暂时不会支持这部分解析。

**Comment by fit2-zhao** [comment]
暂时关闭此 Issues ，如果您有更好的解决方案也欢迎给我们提PR：https://github.com/metersphere/metersphere-idea-plugin
