### ISSUE TITLE
[BUG]swagger 定时同步 api ，该 api 下的 case 在工作台「待更新」列表处无法同步。

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#32441]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

swagger 定时同步 api ，该 api 下的 case 在工作台接口用例「待更新」列表处无法同步。

### 重现步骤

1.导入 ms swagger ,给 /signin 接口创建 case 
2.修改  /signin 接口，比如 添加 header 字段，保存时开启同步case并保存 
3.定时同步 swagger 
4.在 我的工作台，在工作台接口用例「待更新」列表能看到 待更新的 case ,但是 无法点击同步。
![image](https://github.com/user-attachments/assets/1aadd475-80d7-4f8d-be49-e7ad75b416f1)

另外，可以点击 批量同步，而且 批量同步是生效的，但是批量同步完 依然在 「待更新」列表。

### 期待的正确结果
1.在工作台接口用例「待更新」列表 可以点击同步。
2. 批量同步和单个用例同步 权限应该保持一致。
_No response_

**Comment by 13290445582** [comment]
您好，本地测试未复现该问题，在原环境查看访问时报错，请检查是否环境异常或使用其他环境测试，按照步骤操作当前还未在本地复现该问题。
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/d0523e9a-2db5-4d0f-9a9f-554253af90a4">

**Comment by shenkaibo** [comment]
那个环境出问题了，可以在你们自己的环境复现。

**Comment by shenkaibo** [comment]
> 您好，本地测试未复现该问题，在原环境查看访问时报错，请检查是否环境异常或使用其他环境测试，按照步骤操作当前还未在本地复现该问题。 <img alt="image" width="1207" src="https://private-user-images.githubusercontent.com/128017892/356090404-d0523e9a-2db5-4d0f-9a9f-554253af90a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTg2NDksIm5iZiI6MTcyMzA5ODM0OSwicGF0aCI6Ii8xMjgwMTc4OTIvMzU2MDkwNDA0LWQwNTIzZTlhLTJkYjUtNGQwZi05YTlmLTU1NDI1M2FmOTBhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNjI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzI1ZGI5MmFjZDAxMzc3MjFhMGNmOWJkZjc1ZDVkNDBmOTQzMjQyZTEwNGI4NzM1YTE4MjAxNzQzNjIwNWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eUNwERZQ1rozvS7LjyaonQZv8MDzBrHofRZyK45lpfw">

这个环境好了，可以继续验证

**Comment by 13290445582** [comment]
已找到复现问题的必要条件，后续版本修复。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
