### ISSUE TITLE
[BUG]测试报告中的富文本框不支持插入或者贴入表格

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32456]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/bc907bfe-891c-490e-a4ae-b113a331684a)
测试报告中的富文本框不支持插入或者贴入表格

### 重现步骤

1、在测试报告中编辑富文本框
2、插入或者粘贴一个表格

### 期待的正确结果

支持表格编辑

**Comment by 13290445582** [comment]
您好，暂不支持插入或者贴入表格，后续待讨论是否支持该功能。

**Comment by henbell2** [comment]
收到，谢谢！

**Comment by luty2018** [comment]
> 收到，谢谢！

我们在v3.3版本加一下。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
