### ISSUE TITLE
[BUG]最新版本测试计划无法关联测试用例

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32452]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

最新版本测试计划无法关联测试用例
![image](https://github.com/user-attachments/assets/27ec6be5-981f-467b-9aed-2b1db4029c29)

### 重现步骤

1、新建项目
2、正常导入测试用例
3、创建测试计划

### 期待的正确结果

关联项目内已有的测试用例

**Comment by henbell2** [comment]
![image](https://github.com/user-attachments/assets/79398724-c10e-4199-8806-ef7ea5f9405c)

**Comment by fit2-zhao** [comment]
问题1 ：创建测试计划成功后---> 点击进入测试计划 ---->在“测试规划” 页面关联用例&设置环境&规划运行模式 等；如图：

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/b70646a9-45f4-4fb1-96bd-e2568d72fffe">

**Comment by fit2-zhao** [comment]
> ![image](https://private-user-images.githubusercontent.com/125845113/355811304-79398724-c10e-4199-8806-ef7ea5f9405c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODE2NjgsIm5iZiI6MTcyMzA4MTM2OCwicGF0aCI6Ii8xMjU4NDUxMTMvMzU1ODExMzA0LTc5Mzk4NzI0LWMxMGUtNDE5OS04ODA2LWVmN2VhNWY5NDA1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMTQyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjU5MjRkMDVmMmVkZmM2MTcyMDk1YWJjZTgxZjljYTEzZTI5NWIxMmMzZjQxMjljOTU0YWJkM2M5NWU1NmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmM7iAR6s47B0sEAcJ7FKzyQ2wyq69hv4ToEKc-jzRM)

请描述一下这个问题的具体复现步骤，便于快速定位并解决此问题，感谢。

**Comment by henbell2** [comment]
非常感谢！帮忙找到了这个入口

**Comment by 13290445582** [comment]
您好，您第二个问题是否还存在，具体是如何操作步骤复现，请反馈；若无问题将关闭该issue。
![image](https://github.com/user-attachments/assets/af623661-916c-4195-9d5a-fa604cfb66cb)

**Comment by henbell2** [comment]
> 您好，您第二个问题是否还存在，具体是如何操作步骤复现，请反馈；若无问题将关闭该issue。 ![image](https://private-user-images.githubusercontent.com/128017892/356074175-af623661-916c-4195-9d5a-fa604cfb66cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODkzMDQsIm5iZiI6MTcyMzA4OTAwNCwicGF0aCI6Ii8xMjgwMTc4OTIvMzU2MDc0MTc1LWFmNjIzNjYxLTkxNmMtNDE5NS05ZDVhLWZhNjA0Y2ZiNjZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwMzUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTUxMzUyODNlZmZiNTJiYmMzMmE3MjNhZTZkNmIzMzM1MzcxNzIzNTlmMDU4MDNhYmIzZGY5ZTI0MDlmYWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H5Ll9GxYKxxr9yrY83zk-xehUdH6Alm45d3mYV8YHRQ)

进入一条测试用例，点击“测试计划”，就报错了。必现

**Comment by 13290445582** [comment]
您好，本地没复现这个问题，建议检查下是否本身环境问题，新建项目、测试计划、用例测试是否报错或新搭建环境试下。

**Comment by 13290445582** [comment]
您好，问题二本地已复现，v3.2版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
