### ISSUE TITLE
[FEATURE]在测试计划中，测试用例通常几百/几千条，但是“执行人”不能快速定位自己的测试任务，建议增加筛选，或增加一个“执行人”的快捷工作面板

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32465]
### MeterSphere 版本

v3.1.0-a8910b83

### 联系方式

henbell2@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/961d7271-ca3f-41f4-9aa8-b1221cddc231)
“执行人”不能快速定位自己的测试任务

### 请描述你建议的实现方案

建议增加筛选，或增加一个“执行人”的快捷工作面板，“执行人”能够快速定位自己的任务

**Comment by liuruibin** [comment]
感谢您的宝贵意见

**Comment by henbell2** [comment]
> 感谢您的宝贵意见

类似用例评审下的这个开关，挺好用的，直接查看自己的评审任务。
![image](https://github.com/user-attachments/assets/a9f140fc-21dd-4a41-9a3a-0145ce62cb28)

**Comment by henbell2** [comment]
还有一个小建议就是：对于manager，没有一个页面能够以人的维度，统计测试工作的效能或者每个人的测试进度，比如饼图或者柱状图。参考哈

**Comment by luty2018** [comment]
> 还有一个小建议就是：对于manager，没有一个页面能够以人的维度，统计测试工作的效能或者每个人的测试进度，比如饼图或者柱状图。参考哈

感谢您的建议，这个我们有规划的哈！另外您提到的根据“执行人”筛选会在月底v3.2上线。

**Comment by henbell2** [comment]
谢谢，收到！

**Comment by luty2018** [comment]
v3.2 已发布， 可以更新使用。
