### ISSUE TITLE
[BUG]性能测试页面按迭代次数按钮和RPS按钮异常

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32469]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

在性能测试页面，选择按迭代次数后，通过el-input-number组件修改RAMP-UP值，箭头卡顿，修改数值异常，点击变大时只能增加1，点击变小时一次性减少2.开启RPS后，后边的RPS上线调整也是同样的问题

![image](https://github.com/user-attachments/assets/9a95849b-9a49-4e1a-93d6-c442f0588730)

### 重现步骤

如上所述

### 期待的正确结果

正确调整

### 附加信息

我查看了源码，没看出什么问题，通过v-model绑定属性，不知道为什么出现这个问题。
![image](https://github.com/user-attachments/assets/26417e21-73fa-47e3-93f0-cbc6764db597)

另外提个优化意见，如果加入的性能测试场景较多的话，一个一个调整参数很麻烦，后面我添加了新的按钮，可以实现修改一个的同时将其他场景配置同步修改。具体实现如下

新增方法
![image](https://github.com/user-attachments/assets/ea89c19a-decf-4322-beed-5cb05c3091c5)

包裹原来的calculateTotalChart
![image](https://github.com/user-attachments/assets/4f42079c-5652-4c91-bc3d-cc07fa42adc5)

组件调用
![image](https://github.com/user-attachments/assets/c2f19000-803d-48ac-b49f-9e6d4adc9294)

**Comment by 13290445582** [comment]
感谢反馈，按钮异常问题已复现并提交，等待排期修复。若有需求或者建议请提FEATURE交由产品老师评估，感谢理解。
