### ISSUE TITLE
[FEATURE]在用例库中选择测试用例，更多操作中没有“导出Excel表格”或“导出思维导图”选项了

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32473]
### MeterSphere 版本

v3.1.0-a8910b83

### 联系方式

henbell2@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/b34195be-c8a3-4238-b907-cb3890772709)
在用例库中选择测试用例，更多操作中没有“导出Excel表格”或“导出思维导图”选项了

### 请描述你建议的实现方案

增加“导出Excel表格”或“导出思维导图”选项

**Comment by liuruibin** [comment]
感谢您的宝贵意见，请期待后续版本

**Comment by luty2018** [comment]
导出功能在月底v3.2版本上哦。

**Comment by henbell2** [comment]
收到，谢谢！

**Comment by luty2018** [comment]
v3.2 已发布， 可以更新了哈。
