### ISSUE TITLE
[BUG] 无法查看CASE批量执行的集合报告

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#32488]
### MeterSphere 版本

v2.10-16-lts

### 使用外置数据库

否

### 问题描述

批量执行接口定义中多个CASE，在选择“集合报告”，执行成功后再查看报告，提示

请求URL
http://17.6.104.151:8081/api/api/scenario/report/get/4aac3e7e-e7ed-472f-8807-07dc2ca3dbd4
返回结果
{"success":false,"message":"当前用户没有操作此用例的权限","data":null}

### 重现步骤

步骤：
1. 进入API定义，选择CASE
2. 选择多个CASE，选择批量执行
3. 在弹出页面，选择“集合报告 ”
4. 执行成功后，直接查看报告

### 期待的正确结果

可以正常查看报告

**Comment by 13290445582** [comment]
感谢反馈，问题已复现并提交，等待排期修复。

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
