### ISSUE TITLE
[FEATURE]测试用例不支持思维脑图模式去执行，编写用例时不能像xmind一样使用键盘快捷键新增下一个节点

### ISSUE THREAD

**Issue by qiulanggit** [metersphere/metersphere#32481]
### MeterSphere 版本

v3.1

### 联系方式

vx：WH-LANG

### 请描述您的需求或者改进建议

目前使用了v3.1版本感觉轻量了许多比较喜欢，
**执行用例的时候没有思维脑图的模式去执行用例看着比较不习惯，现在大部分用例平台都是思维脑图的模式去写用例和执行用例比较快捷方便。**希望能后期优化一下
参考下面这种效果
![IMG20240808181806](https://github.com/user-attachments/assets/efb6ccbe-d78e-4f72-9bca-96eeab51c995)

**Comment by qiulanggit** [comment]
现在大部分人写用例都是xmind 希望能导入和导出 xmind

**Comment by liuruibin** [comment]
感谢您提的宝贵意见，请关注后续版本
