### ISSUE TITLE
[QUESTION] 安装之后，如何进行升级，数据是否有损

### ISSUE THREAD

**Issue by yujinguo0930** [metersphere/metersphere#325]
想采用metersphere用作测试管理，但是担心版本后续升级，请问下，后续升级数据如何保存，有无操作指南

**Comment by wangzhen-fit2cloud** [comment]
你好，我们的数据都保存在数据库里，升级过程中会自动更新数据库表结构，同时保留数据库中已有的数据，如果长期使用的话，建议对数据库做好备份
