### ISSUE TITLE
[BUG] 测试计划失败重试失效

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32501]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

当测试步骤被循环控制器包裹时，该步骤失败后不会进行重试，单独的步骤没有问题

未重试
![image](https://github.com/user-attachments/assets/46833fbe-3ec8-4d55-b948-7d3918575ea5)

正确重试
![image](https://github.com/user-attachments/assets/9bf5ba9e-9437-4256-8809-7e3559195bed)

### 重现步骤

如上所述

**Comment by 13290445582** [comment]
您好，循环控制器内失败的请求不会进行失败重试操作，设计上就是这样的，避免造成死循环，感谢理解与支持。
