### ISSUE TITLE
[BUG]组织管理员无法给项目成员赋予项目管理员角色，只有系统管理员角色的用户才可以

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32514]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

组织管理员无法给项目成员赋予项目管理员角色，只有系统管理员角色的用户才可以

### 重现步骤

1、创建一个用户，授予组织管理员角色
2、用该用户登录给自己赋予项目的项目管理员角色

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，已规划为3.3需求。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，v3.2版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
