### ISSUE TITLE
[BUG]请求体内使用Mock的@integer函数并指定类型为integer，请求参数仍然是字符串类型

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32536]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

接口请求体内使用Mock的@integer函数并指定类型为integer，请求参数仍然是字符串类型

### 重现步骤

如附件截图

### 附加信息

<img width="994" alt="image" src="https://github.com/user-attachments/assets/c739c5af-8ba8-4985-b428-47b86a8f77cd">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会修复该问题。

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
