### ISSUE TITLE
[BUG]之前在v3测试通过的接口插件，在v3.1.0 版本场景点击保存失败

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#32537]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

之前在v3测试通过的接口插件，在v3.1.0 场景点击保存，页面没反应，控制台报错

### 重现步骤

![image](https://github.com/user-attachments/assets/4afa90c6-ec37-4be0-a8bb-9e659cacf76c)
之前在v3企业版测试通过的接口插件，现在v3.1.0 场景，使用自定义请求，点击保存，页面没反应，控制台报错，保存场景失败

### 期待的正确结果

接口场景可以保存自定义协议的接口插件

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #32348
