### ISSUE TITLE
[BUG]前提条件：新的项目，仅仅创建了测试用例。操作：在测试用例列表选择用例，在右侧测试用例明细信息中，选择上部的“测试计划”，系统提示JSON异常信息。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#32542]
### 联系方式

lisa.huang@fit2cloud.com

### MeterSphere 版本

V3.1.0

### 使用外置数据库

否

### 问题描述

前提条件：新的项目，仅仅创建了测试用例。
操作：在测试用例列表选择用例，在右侧测试用例明细信息中，选择上部的“测试计划”，
系统错误：系统提示JSON异常信息。
期待结果：能正常显示该用例的测试计划列表页面

### 重现步骤

前提条件：新的项目，仅仅创建了测试用例。
操作：在测试用例列表选择用例，在右侧测试用例明细信息中，选择上部的“测试计划”，
系统错误：系统提示JSON异常信息。
期待结果：能正常显示该用例的测试计划列表页面

### 附加信息

![image](https://github.com/user-attachments/assets/206af5bc-a5dc-4737-ac19-3b4f48d6f367)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #32452
