### ISSUE TITLE
[FEATURE]功能测试用例执行失败或者阻塞的时候，没有地方设置为“必填”备注（评审失败的时候会弹出必填框）

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32540]
### MeterSphere 版本

v3.1.0-a8910b83

### 联系方式

henbell2@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/dc538409-0278-4b38-9a63-fea53124bb6f)
功能测试用例执行失败或者阻塞的时候，没有地方设置为“必填”备注（评审失败的时候会弹出必填框）

### 请描述你建议的实现方案

用例执行失败或者阻塞时，应该弹出必填框，确保执行结果的准确性、和执行过程的严谨性

**Comment by luty2018** [comment]
步骤的实际结果已经记录了，这时候强制备注可能不太好

**Comment by henbell2** [comment]
> 步骤的实际结果已经记录了，这时候强制备注可能不太好

Get！
