### ISSUE TITLE
[BUG]和禅道对接后，在测试计划里创建缺陷，无法保存，并且缺陷模板也不对。在测试计划里创建缺陷的模板不是自定义的禅道缺陷模板。这个和在缺陷管理模块>>创建缺陷完全不一样。要求：计划里创建缺陷，和在缺陷管理模块创建缺陷一致，并且能正常保存

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#32543]
### 联系方式

lisa.huang@fit2cloud.com

### MeterSphere 版本

V3.1.0

### 使用外置数据库

否

### 问题描述

[BUG]和禅道对接后，在测试计划里创建缺陷，无法保存，并且缺陷模板也不对。在测试计划里创建缺陷的模板不是自定义的禅道缺陷模板。这个和在缺陷管理模块>>创建缺陷完全不一样。要求：计划里创建缺陷，和在缺陷管理模块创建缺陷一致，并且能正常保存

### 重现步骤

[BUG]和禅道对接后，在测试计划里创建缺陷，无法保存，并且缺陷模板也不对。在测试计划里创建缺陷的模板不是自定义的禅道缺陷模板。这个和在缺陷管理模块>>创建缺陷完全不一样。要求：计划里创建缺陷，和在缺陷管理模块创建缺陷一致，并且能正常保存

### 附加信息

![2f7f123f6c3c4fdffc83185d3167ef5](https://github.com/user-attachments/assets/311d93a5-3e64-47d2-a5e8-ab8973204371)
![509443145042e24dc924ce92204030c](https://github.com/user-attachments/assets/9c2af6bc-6417-4c06-8805-2a076bf54623)

**Comment by luty2018** [comment]
我们会在v3.3修复

**Comment by henbell2** [comment]
+1，遇到同样问题
