### ISSUE TITLE
[BUG]测试计划加入的测试场景用例过多、过大的时候，从测试计划下面的报告可以查看到结果，但是从报告tab下无法查看测试计划运行的结果报告

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#32557]
### 联系方式

13716054767

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 测试计划加入的测试用例多的时候，从测试计划下面的报告可以查看到结果，但是从报告tab下无法查看结果
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/b8e54915-1448-4aac-904b-6d118c9a02ec">
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e631020a-b9cc-42e1-9437-939d82b4d029">
### **但是从报告tab下进入无法查看，如下**
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/a11ff83f-3a91-40a4-a5b6-fbce430c57e6">
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/214b3458-ffb4-4827-99b3-14a4b78ee17b">

### 重现步骤

测试计划放入大量的的测试用例，达到一定数量后，测试跟踪报告模块tab下的测试计划运行结果报告无法同步测试计划的运行结果
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/b98c7b5b-e902-4387-bea3-eeae1e45e24a">

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/ef3141cc-37f0-426d-a50e-87f71438e461">

### 期待的正确结果

测试计划下的报告模块tab能够正常展示测试计划的运行结果报告

**Comment by lol666666** [comment]
跟这个https://github.com/metersphere/metersphere/issues/31848 一个问题

**Comment by Somebody-JIAN** [comment]
> 跟这个#31848 一个问题

所以那个问题修改了配置之后，执行还会报之前报的错误吗？

**Comment by lol666666** [comment]
> > 跟这个#31848 一个问题
> 
> 所以那个问题修改了配置之后，执行还会报之前报的错误吗？

对的，稳定复现,现象就是测试跟踪--》报告模块下对应测试计划的结果无展示

**Comment by Somebody-JIAN** [comment]
意思就是修改了配置不管用是吧？

**Comment by lol666666** [comment]
> 意思就是修改了配置不管用是吧？

对的 没有效果

**Comment by liuruibin** [comment]
改properties没效果的话试试改 /opt/metersphere/docker-compose-gateway.yml
<img width="977" alt="image" src="https://github.com/user-attachments/assets/283c77e4-f0a7-49f7-9d94-225e00543b92">

```
SPRING_CLOUD_GATEWAY_HTTPCLIENT_CONNECT_TIMEOUT: 300000
SPRING_CLOUD_GATEWAY_HTTPCLIENT_RESPONSE_TIMEOUT: 300000
```
数值你自行调整单位是耗秒

**Comment by SloanGao** [comment]
按要求配置后还是执行自动停止
![1724754437849](https://github.com/user-attachments/assets/77481dfd-1cd1-4fc0-89a3-425f6e5e59f2)
![0c3c8cb78a4a4e27dc0eac0827816aa](https://github.com/user-attachments/assets/87522f8c-6d1f-4457-b25f-8fbd93353662)

![00e46cf21185dff0cf6fee0f84d819a](https://github.com/user-attachments/assets/c2b8500e-5151-426f-b2d4-ba2b4b89d21b)

**Comment by liuruibin** [comment]
我也看不出来了

**Comment by fit2-zhao** [comment]
把你的部署情况详细描述一下，比如：
1 各服务所占资源比例
2 资源池执行并发数量
3 执行策略（并行｜串行）

**Comment by lol666666** [comment]
> 把你的部署情况详细描述一下，比如： 1 各服务所占资源比例 2 资源池执行并发数量 3 执行策略（并行｜串行）
<br/>
1.各个服务所占比例，机器内存为124gb的物理机
<img width="988" alt="image" src="https://github.com/user-attachments/assets/a2727719-69c4-4a8d-9235-fd2c2d011e73">


2.资源池并发数为100左右<br/>
3执行策略为并行执行，测试用例多为场景用例，场景用例数量700条左右，每个场景至少5个步骤即包含5个其他场景

**Comment by fit2-zhao** [comment]
应该是服务之间调用超时导致的（观察各服务状态是否有重启），我们会在后续版本进行优化这部分，建议你先把测试计划拆一拆。

**Comment by fit2-zhao** [comment]
如果有二开，你可以尝试调整 MicroService 中的 RestTemplate 超时时间试试看。

**Comment by lol666666** [comment]
> MicroService

这个在代码的哪个工程下？哪个配置文件方便告诉下吗

**Comment by fit2-zhao** [comment]
源码都是开源的，你 SearchEveryWhere 查找下就能找到。

**Comment by fit2-zhao** [comment]
暂时关闭这个 issues 了，如果二开可以参照我们官方提供的开发文档处理；还有我看你服务器资源挺大的，可以针对每个服务合理分配内存；7000多执行场景 建议：
api-test，test-track，node-controller 这几个关键服务内存都分配 到 10G 左右；
文档地址：https://metersphere.io/docs/v2.x/ 。

**Comment by lol666666** [comment]
> 暂时关闭这个 issues 了，如果二开可以参照我们官方提供的开发文档处理；还有我看你服务器资源挺大的，可以针对每个服务合理分配内存；7000多执行场景 建议： api-test，test-track，node-controller 这几个关键服务内存都分配 到 10G 左右； 文档地址：https://metersphere.io/docs/v2.x/ 。

都配置在10gb以上 不管事的，不修复吗？加了后也没效果

**Comment by fit2-zhao** [comment]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/d1474a15-3043-45c8-8116-5a45d9008ade">

请问交流群这个是你吗，是否同一问题。

**Comment by lol666666** [comment]
> <img alt="image" width="731" src="https://private-user-images.githubusercontent.com/70558837/364610395-d1474a15-3043-45c8-8116-5a45d9008ade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjM4MzAsIm5iZiI6MTcyNjAyMzUzMCwicGF0aCI6Ii83MDU1ODgzNy8zNjQ2MTAzOTUtZDE0NzRhMTUtMzA0My00NWM4LTgxMTYtNWE0NWQ5MDA4YWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyNTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTg3NDlmNTk3OTMyN2FhN2RhOTBmMWIzOTFlNzFkZWIwZDliMTU5ZWNjOTMyZDM5NTIzMGEwYjdjOWQyNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkP7qH9dtipY9jMSM68h5G8J-XlbLXaZjgTZ8-g_U-0">
> 请问交流群这个是你吗，是否同一问题。

不是我，请问他调大的啥可以了？

**Comment by youliyuan-fit2cloud** [comment]
暂时关闭这个 issues 了，如果二开可以参照我们官方提供的开发文档处理；还有我看你服务器资源挺大的，可以针对每个服务合理分配内存；7000多执行场景 建议：
**api-test，test-track，node-controller 这几个关键服务内存都分配 到 10G 左右；**
文档地址：https://metersphere.io/docs/v2.x/ 。
1、修改上诉提到的模块docker 文件，在 安装目录下docker -compose文件中内存最大值，
2、执行 msctl reload
3、执行docker stats 查看是否修改生效
4、尝试是否还会复现。
