### ISSUE TITLE
[BUG]Jenkins 执行接口自动化流水线，脚本中设置了域名，但是报告链接还是ip显示

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32553]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

Jenkins 执行接口自动化流水线，脚本中设置了域名，但是报告链接还是ip显示

### 重现步骤

1. 在Jenkins 执行接口自动化流水线，脚本中设置了域名，
2.Jenkins 控制台查看，发现报告链接是ip显示

### 期待的正确结果

Jenkins 执行接口自动化流水线，脚本中设置了域名，但是报告链接显示的也是域名

### 相关日志输出

```shell
无
```

### 附加信息

<img width="484" alt="1723455405731" src="https://github.com/user-attachments/assets/29fd3221-f910-480d-8e4d-ca25efabac8d">

![image](https://github.com/user-attachments/assets/f637c9bb-8ce6-4532-99bc-2c6981ec7ae5)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个得改MS系统参数设置的当前URL站点。

**Comment by spritelyl** [comment]
好的，我看下
