### ISSUE TITLE
[BUG]在缺陷模板中，对状态字段进行修改新增了枚举值，保存模版后。缺陷管理中已提交缺陷的状态字段全部失效。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#32558]
### 联系方式

god47@qq.com

### MeterSphere 版本

2.10.14lts

### 使用外置数据库

否

### 问题描述

1、原始缺陷保存后的状态
![2090f98a7756fb3444069aaf010c293](https://github.com/user-attachments/assets/7a3b8a21-f1a2-4e2b-bb12-6882dd7eff68)
2、在缺陷模板中，对状态字段进行修改新增了枚举值，保存模版
![0ecbb93e5fee9abaac766eab77a0d83](https://github.com/user-attachments/assets/772b8dcb-cbae-4deb-8501-d93dce34c476)
3、缺陷管理中已提交缺陷的状态字段全部失效
![f8867c2fd09ebbd426bb6b68c3c93a6](https://github.com/user-attachments/assets/749146cb-7391-4644-8b0e-51038c14b11f)

### 重现步骤

在缺陷模板中，对状态字段进行修改新增了枚举值，保存模版后。缺陷管理中已提交缺陷的状态字段全部失效。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
