### ISSUE TITLE
[BUG]quartz 配置独立数据源没有生效，还是采用 spring.datasource 前缀的数据源配置

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#32560]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

客户红区/绿区 2套环境，共用1套数据库，资源池分别在各自网络区域内，配置定时任务时，如果 绿区的任务 由红区来触发，就下发不到 绿区的 执行机，导致定时任务出错概率很大。

### 重现步骤

quartz 配置独立数据源没有生效，还是采用 spring.datasource.* 前缀的数据源配置

### 期待的正确结果

支持在 metersphere.properties 配置文件中配置 spring.datasource.quartz.* 来单独配置 quartz 数据源。

![image](https://github.com/user-attachments/assets/fa9d48a8-400a-4c22-89ee-9b377ba9471c)
![image](https://github.com/user-attachments/assets/0b29449a-f897-4859-bc23-21e57e0dab4c)

**Comment by liuruibin** [comment]
感谢提醒
