### ISSUE TITLE
[BUG]接口定义导出swagger格式的JSON文件不包含定义的响应体信息

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32576]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

接口定义导出swagger格式的JSON文件不包含定义的响应体信息，而导出MeterSphere格式的JSON是包含响应体信息的

### 重现步骤

1、选择某个已经添加响应信息的接口定义，然后导出swagger格式
2、打开导出JSON文件，查看response信息

### 附加信息

界面定义：
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/f9713c23-d6ee-440a-8ea7-b955526ea575">

swagger：
<img width="723" alt="image" src="https://github.com/user-attachments/assets/c8906fc0-b0c1-46ac-b1ab-c00fc3cd3714">

MeterSphere:
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/3eead4fb-f630-446c-962e-e35a8acb4caa">

**Comment by luty2018** [comment]
已复现，会在下个小版本修复

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
