### ISSUE TITLE
[FEATURE]功能用例的自定义字段，关联用例时不能筛选掉不适用的用例，到测试计划里也不能筛选再反向操作(取消被关联的不适用用例)，用处好像不太大，用例关联不灵活

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32575]
### MeterSphere 版本

v3.1.0-a8910b83

### 联系方式

henbell2@163.com

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/94c67583-2082-4a47-8be9-98b3a7001df4)
功能用例的自定义字段，关联用例时不能筛选掉不适用的用例，到测试计划里也不能筛选再反向操作(取消被关联的不适用用例)，用处好像不太大

### 请描述你建议的实现方案

自定义的属性字段，起码在关联用例的时候要支持筛选，能够区别适用/不适用的测试用例

**Comment by Hyyfit** [comment]
测试计划会支持高级搜索，可以通过高级搜索检索自定义字段。
已规划在3.3的版本里了。
关联弹窗也会支持高级搜索，规划在3.4的版本。
