### ISSUE TITLE
[BUG]【接口测试-接口定义】case-批量执行，生成集合报告，在报告处查看，提示没有权限。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32596]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

【接口测试-接口定义】case-批量执行，生成集合报告，在报告处查看，提示没有权限

### 重现步骤

【接口测试-接口定义】case-批量执行，生成集合报告，在报告处查看，提示没有权限。当前用户是具有项目管理员-项目所有权限
![image](https://github.com/user-attachments/assets/04dfd95e-7522-4137-835a-927f02804fb5)
![image](https://github.com/user-attachments/assets/b761e8f4-5f42-4b96-ae8a-bc4ba3b9f3e0)
![image](https://github.com/user-attachments/assets/a8ede1c1-2665-4931-aee1-20d40678c37d)
![image](https://github.com/user-attachments/assets/1f459944-8557-4118-98e6-1d8923171769)

**Comment by AgAngle** [comment]
![image](https://github.com/user-attachments/assets/16bd6c0f-46cc-46f8-8b25-f3d1aca8fd9e)
你好，还麻烦确认下项目管理员的用户组里是否包含当前的项目，确保用户在当前项目是项目管理员；另外能否打开浏览器的调试模式，查看下具体是哪个接口报错，谢谢

**Comment by ijwstl** [comment]
> ![image](https://private-user-images.githubusercontent.com/41557596/357692041-16bd6c0f-46cc-46f8-8b25-f3d1aca8fd9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTU4MzksIm5iZiI6MTcyMzYxNTUzOSwicGF0aCI6Ii80MTU1NzU5Ni8zNTc2OTIwNDEtMTZiZDZjMGYtNDZjYy00NmY4LThiMjUtZjNkMWFjYThmZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2MDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzNiYzM4NTM4ZWE3OTY5OWRlODU4YTlhZDA2MDllNTkyMzYwYmY2ZTA5Y2RlNDA4ZGFmNWY3ODM2MzNhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6x552S-QIfGAzsaImomquTv7OrIW-s4WwA9p3SE9HP8) 你好，还麻烦确认下项目管理员的用户组里是否包含当前的项目，确保用户在当前项目是项目管理员；另外能否打开浏览器的调试模式，查看下具体是哪个接口报错，谢谢

我也复现了该bug，/api/scenario/report/get/接口报错，返回为{"success":false,"message":"当前用户没有操作此用例的权限","data":null}，使用超级管理员账号无错误，疑似为@CheckOwner注解的问题

**Comment by 2lipan** [comment]
![企业微信截图_17236154631563](https://github.com/user-attachments/assets/92bdc031-5d77-44e4-aed9-bb97e5519621)

![image](https://github.com/user-attachments/assets/0c6a87d8-e641-44cf-a7cd-f4c41df83ad7)

![image](https://github.com/user-attachments/assets/d59e3985-afd7-49b7-8a0f-4dc65dd65783)

**Comment by 13290445582** [comment]
您好，已知问题，已有其他issue提出，已关联。https://github.com/metersphere/metersphere/issues/32488
