### ISSUE TITLE
[BUG]接口上传文件报错

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#326]
**MeterSphere 版本**
1.2.1

**Bug 描述**
接口上传文件报错

**截图**
![image](https://user-images.githubusercontent.com/13564069/91939758-f437e500-ed28-11ea-8aae-0e42ea61a61f.png)

**期待的正确结果**
postman相同请求接口正常

**Comment by AgAngle** [comment]
请问是否手动添加了Content-Type multipart/form-data ，如果加了去掉试试，这个请求头不能手动添加
