### ISSUE TITLE
[BUG] 令人迷惑的UI设计的两个小建议

### ISSUE THREAD

**Issue by jeffcaiz** [metersphere/metersphere#32602]
### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

1. 二级导航位置或呈现方式不合理

譬如，左下，系统设置-》系统， 然后就目光就被白色区域吸引了。一眼看到【新建】之类的按钮，但是！其实，顶部还藏着个二级导航。 元素呈现很弱，很容易被忽略。第一次用，找了半天其他功能怎么去，最后要看帮助文档。还有一个小问题，就是没对齐展开状态的sidebar，反正不太好看。

建议：调整设计，人的注意力左侧菜单，点了，要扫到刷新的白色区域，顶部这个没刷的很容易被忽略的。

<img width="977" alt="image" src="https://github.com/user-attachments/assets/820409a9-61c4-4a55-abf0-59577c6a3ecf">

2. 用例管理，【新增/导入】按钮位置令人迷惑。 按直觉，应该如下图布局才对。你看，左上，是对【子模块】的过滤，作用是【子模块】，然后那两个大按钮，不是对子模块的管理，而是某个具体子模块的作用。真正增加，放在了下面的小小按钮上。非常迷惑和反人类，个人认为。

<img width="648" alt="image" src="https://github.com/user-attachments/assets/2dcaac78-a3e9-48f1-aedf-b0d4c60901a9">

### 重现步骤

问题描述里面有图，看

### 期待的正确结果

![image](https://github.com/user-attachments/assets/997a6dfb-dcde-49e1-b916-37ecd71a9b76)

**Comment by jeffcaiz** [comment]
想了一下，关于问题2，可能明白原来设计思路。毕竟新建，其实可以选其他模块来做新建，不是说选了模块A，就只能创建模块A下的用例，只不过你选了模块A，默认帮你填好分类到模块A下。同理，而且更强烈的，是导入。导入更可能是跨模块的。

但是，还是建议移动过去，连同导入，会显得更合理。毕竟直觉上：左侧，是目录；右侧，是用例清单。

**Comment by luty2018** [comment]
感谢您的建议， 我们调整一下

**Comment by jeffcaiz** [comment]
更新了我心目中的样子，不是特别好看，不过逻辑比较符合直觉。

可以随时关闭这个issue，或者，如果真决定要改，就给个正式编号留着tracking

**Comment by luty2018** [comment]
首先非常感谢您的反馈，MeterSphere一直秉承“从用户出发”，交互升级的最终目的也是为了提升用户体验。
先解答您的2个问题：
问题1：
由于产品复杂且功能较多的特性，重点信息聚焦在内容区，所以顶部做了降噪处理
针对您的这个困惑，对于首次使用的用户，我们可以加个提示，这样是否能解决呢？
问题2：
确实一个是考虑到创建和模块之间的联动;另一个是右侧列表还有高级搜索、版本的切换功能没有上，位置上不太够，所以放到了左侧。
根据您的建议，我们做了如下调整，看看是否能降低新用户在这块的理解成本呢？
将模块搜索框弱化成icon，新建用例强化展示，导入按钮也前置出来。
<img width="256" alt="image" src="https://github.com/user-attachments/assets/48aa8828-7477-42de-86da-dc042ecbce4b">
搜索模块时，隐藏新建和导入按钮。
<img width="264" alt="image" src="https://github.com/user-attachments/assets/08aa6d36-e4e6-4d2a-885f-d8b1d3e9c486">
新建模块增加hover提示
<img width="248" alt="image" src="https://github.com/user-attachments/assets/35274612-8940-45b4-9424-c37b2bf4ab5b">

**Comment by jeffcaiz** [comment]
个人意见，不过还是你们自己决定。

1. 不太赞同降噪这个说法。因为，这个二级导航其实是**重要的内容**，特别是点了一级菜单，看到纷繁复杂的内容（其实不是我要的tab），这个时候，我非常需要的是这个【菜单入口内容】，而不是其他任何呈现。我就是找不到这个内容。只有这个导航(tab)点了之后，用户已经找到地方了，作用就没那么大了。 

怎么解决好我也不知道。

2. 布局表意个人感觉改了更别扭。贴个隔壁PingCode的，我觉得更顺眼。

- 列表顶部，能找到新建，导入等主操作按钮，而不是任何其他block，符合用户习惯和心智。
- 复杂的高级筛选和排序，是默认折叠起来的，Hover才出来。
- PingCode他们的编辑/新增/查看，都是弹窗overlay，完成后无缝回到列表原来状态；MS的新增/编辑是完全换页，最坑爹的是，我创建完毕了，原来的选择状态就丢了。譬如我原来选A模块，创建完毕，又要再选一次。查看则是抽屉，显示区域可以自己调整，拉大了基本就是弹窗，一半状态感觉有利于快速切不同case查看。


<img width="1853" alt="image" src="https://github.com/user-attachments/assets/f8654984-a291-4514-805f-ed6653cba792">

**Comment by Hyyfit** [comment]
关于第二点，根据您的建议改成下图：

![image](https://github.com/user-attachments/assets/51ec78d9-ade8-4b53-90e2-9c3c0ca91ca7)

创建/编辑完毕，应该是要保留选择的状态的，这个在v3.3版本里已规划修改了。

**Comment by jeffcaiz** [comment]
looks much better, thanks, close as planned in future version.

**Comment by jeffcaiz** [comment]
reopen for tracking

**Comment by youliyuan-fit2cloud** [comment]
v3.3版本中已优化
