### ISSUE TITLE
[BUG] 运行环境中不配置数据源链接或配错误的链接并且用例中写了SQL脚本时，执行用例会卡死。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#32619]
### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

运行环境中不配置数据源链接或配错误的链接并且用例中写了SQL脚本时，执行用例会卡死。

### 重现步骤

![image](https://github.com/user-attachments/assets/44a879a6-db2a-486b-a516-e558a3742716)
![企业微信截图_1723624362856](https://github.com/user-attachments/assets/d6d6280e-0d38-4fe0-a0e7-e835597ca5cf)

### 期待的正确结果

这种情况建议直接跳过？还是用例标记为失败！

### 相关日志输出
ms-node-controller报错信息：
![企业微信截图_17236239347424](https://github.com/user-attachments/assets/d938be3f-77a7-4623-98e3-ee04de9b06b6)
_No response_

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化。

**Comment by LimonFHM** [comment]
会导致OOM

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
