### ISSUE TITLE
[BUG]关联禅道后，在MeterSphere下创建Bug失败

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32634]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/6ff4339e-6799-444b-bb1a-b69cf64aeb7d)
[BUG]关联禅道后，在MeterSphere下创建Bug失败

### 重现步骤

1、关联禅道(同步禅道bug到MeterSphere正常)
2、MeterSphere下登录个人禅道账号
3、MeterSphere创建Bug

### 期待的正确结果

创建Bug成功；
问题1：创建bug失败，提示“优先级”不能为空
问题2：已创建的禅道模板无效

**Comment by song-cc-rock** [comment]
可否提供一下 `禅道Bug模板` 优先级字段的配置截图

**Comment by henbell2** [comment]
> 可否提供一下 `禅道Bug模板` 优先级字段的配置截图

![image](https://github.com/user-attachments/assets/fa59f0f0-00fe-47aa-8f7f-33b14673c051)

**Comment by song-cc-rock** [comment]
> > 可否提供一下 `禅道Bug模板` 优先级字段的配置截图
> 
> ![image](https://private-user-images.githubusercontent.com/125845113/358103296-fa59f0f0-00fe-47aa-8f7f-33b14673c051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTEwNzIsIm5iZiI6MTcyMzcxMDc3MiwicGF0aCI6Ii8xMjU4NDUxMTMvMzU4MTAzMjk2LWZhNTlmMGYwLTAwZmUtNDdhYS04ZjdmLTMzYjE0NjczYzA1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwODMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTdhYTdiN2JkZTY5NTYyNjU3NzBhMjk5YWU5OTk5NWM5MjAzOTIwZDUyNGEyMGI4N2JhNDEyMGRmYjUxNTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF3WsDBvvToTzlwA6kz9m6_hieerA17zR0yJbHNqV7w)
可参考下面截图中的对接字段来进行配置, **选项值** 可以在禅道页面表单进行抓取, **API对接字段名** 可参考官网API , 地址为: https://www.zentao.net/book/api/721.html, 并且我们马上会在下版本支持禅道默认模板, 到时可升级体验!!
![image](https://github.com/user-attachments/assets/f5bfceb3-7ddc-456f-8674-7250d0b9591d)
![image](https://github.com/user-attachments/assets/6c0c4766-af05-4a4d-a838-0d03b3e146aa)
![image](https://github.com/user-attachments/assets/642afdf6-2807-4333-8751-979320afb3bb)

**Comment by henbell2** [comment]
> > > 可否提供一下 `禅道Bug模板` 优先级字段的配置截图
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/125845113/358103296-fa59f0f0-00fe-47aa-8f7f-33b14673c051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTEwNzIsIm5iZiI6MTcyMzcxMDc3MiwicGF0aCI6Ii8xMjU4NDUxMTMvMzU4MTAzMjk2LWZhNTlmMGYwLTAwZmUtNDdhYS04ZjdmLTMzYjE0NjczYzA1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwODMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTdhYTdiN2JkZTY5NTYyNjU3NzBhMjk5YWU5OTk5NWM5MjAzOTIwZDUyNGEyMGI4N2JhNDEyMGRmYjUxNTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF3WsDBvvToTzlwA6kz9m6_hieerA17zR0yJbHNqV7w)
> > 可参考下面截图中的对接字段来进行配置, **选项值** 可以在禅道页面表单进行抓取, **API对接字段名** 可参考官网API , 地址为: https://www.zentao.net/book/api/721.html, 并且我们马上会在下版本支持禅道默认模板, 到时可升级体验!!
> > ![image](https://private-user-images.githubusercontent.com/40567414/358167154-f5bfceb3-7ddc-456f-8674-7250d0b9591d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzNjYsIm5iZiI6MTcyMzcxNTA2NiwicGF0aCI6Ii80MDU2NzQxNC8zNTgxNjcxNTQtZjViZmNlYjMtN2RkYy00NTZmLTg2NzQtNzI1MGQwYjk1OTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTc1MWY3NGUzNTEyZGFkZjhmNTQ3N2I2ZTU1MzQzOTBjY2M3ZThiZTRhNDYzNjQwOGFjOGRhNTA1MmI4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWnZwI3PobgSVUOjheBRewJG5_CPGc52CqMdkBD0ecY)
> > ![image](https://private-user-images.githubusercontent.com/40567414/358169080-6c0c4766-af05-4a4d-a838-0d03b3e146aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzNjYsIm5iZiI6MTcyMzcxNTA2NiwicGF0aCI6Ii80MDU2NzQxNC8zNTgxNjkwODAtNmMwYzQ3NjYtYWYwNS00YTRkLWE4MzgtMGQwM2IzZTE0NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3Yjg4ZTk2MjUzYmE5NDg1Njk2MjdmYTMwNjk3N2Y2Nzc3MjI2OGNlOGNkZTBjOTA2MDM4ZTFkMjU0ZTllMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wR7veFbe5VZctA7PTMNx9fdoSQhtUcLPqWnIVz1PN6k)
> > ![image](https://private-user-images.githubusercontent.com/40567414/358169268-642afdf6-2807-4333-8751-979320afb3bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzNjYsIm5iZiI6MTcyMzcxNTA2NiwicGF0aCI6Ii80MDU2NzQxNC8zNTgxNjkyNjgtNjQyYWZkZjYtMjgwNy00MzMzLTg3NTEtOTc5MzIwYWZiM2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MTMzMjQ3YjA5MGM5NjZiMzQyNjg5NDhmNWVlYmEwNDkzNTYxMTdiMmVmYTU1Y2EyYzM1NjRhODM2ZDAxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5UqOfz5390vtz7ymE-yTTVNFXl8_2tQ5LQO35ud0QXw)

收到，谢谢！
