### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 15068870403** [metersphere/metersphere#32633]
### 联系方式

MeterSphere 交流群40

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

jmeter的接口自动化脚本直接导入到MS的【接口自动化】，“引入环境”默认是不勾选的  ，导致MS右上角切换环境后接口请求地址不能自动切换ip。

### 重现步骤

1、jmeter的接口自动化测试jmx脚本 导入到MS【接口自动化】
2、导入进去的脚本请求地址默认不勾选“引入环境”
3、切换界面右上角的“运行环境”，请求地址不能自动切换环境地址

### 期待的正确结果

1、jmeter的接口自动化测试jmx脚本 导入到MS【接口自动化】
2、导入进去的脚本请求地址默认勾选“引入环境”
3、切换界面右上角的“运行环境”，请求地址可以自动切换环境地址

### 附加信息

![Uploading 2.png…]()

**Comment by luty2018** [comment]
这是设计如此呢，jmeter导入的脚本统一处理为自定义请求，使用的是请求内的完整域名，确保导入即可运行。

**Comment by 15068870403** [comment]
但这样会让jmeter脚本适配MS很麻烦，想切换MS的环境还得手动勾选“引入环境”，很是浪费时间（这样做的目的是放弃jmeter写自动化脚本，后续转到MS维护脚本）
