### ISSUE TITLE
[BUG]【系统参数-认证配置】cas 认证这，配置提示不对，suthId 建议改为 ${authId}

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32644]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

【系统参数-认证配置】cas 认证这，配置提示不对，suthId 建议改为 ${authId}

### 重现步骤

【系统参数-认证配置】cas 认证这，配置提示不对，suthId 建议改为 ${authId}
![image](https://github.com/user-attachments/assets/7c8e1f19-4270-4a1b-b6e8-48d6a244e1bf)

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
