### ISSUE TITLE
[FEATURE] 我怎么感觉你们这个版本越更新 功能越来越少了（指接口测试这块）

### ISSUE THREAD

**Issue by KnightBlood** [metersphere/metersphere#32640]
### MeterSphere 版本

3.1.0

### 请描述您的需求或者改进建议

1.支持的的组件越来越少了，比如 计数器（1.x的版本还有，2.x没有了） 
2.导入jmeter脚本的能力没有了

**Comment by luty2018** [comment]
首先非常抱歉给您造成的困扰！v3版本是全新设计和开发的，刚发布两个版本，所以和v2对比起来，略显单薄。但是每月一个迭代，功能会深度覆盖的。
1.计数器在v2是有的，但是在场景运行中并没有发挥计数器的效果， 加上用户没有反馈这个需求，因此v3就下掉了。可以描述一下您的应用场景吗？
2.导入jmeter脚本会在v3.3版本上线。

**Comment by KnightBlood** [comment]
> 首先非常抱歉给您造成的困扰！v3版本是全新设计和开发的，刚发布两个版本，所以和v2对比起来，略显单薄。但是每月一个迭代，功能会深度覆盖的。 1.计数器在v2是有的，但是在场景运行中并没有发挥计数器的效果， 加上用户没有反馈这个需求，因此v3就下掉了。可以描述一下您的应用场景吗？ 2.导入jmeter脚本会在v3.3版本上线。

简单描述下 接口测试过程中对某个字段 需要各种不同的数据来测试，我们把这些数据存到了表里，使用时通过数据查询出来，这时候是一个列表（多个列），通过循环控制器+计数器实现取参的目的 通过这种格式来取参${__V(value_${counter})}

**Comment by KnightBlood** [comment]
> 首先非常抱歉给您造成的困扰！v3版本是全新设计和开发的，刚发布两个版本，所以和v2对比起来，略显单薄。但是每月一个迭代，功能会深度覆盖的。 1.计数器在v2是有的，但是在场景运行中并没有发挥计数器的效果， 加上用户没有反馈这个需求，因此v3就下掉了。可以描述一下您的应用场景吗？ 2.导入jmeter脚本会在v3.3版本上线。

当然对于这种场景 如果你们能实现一个工具 给一个标准的参数（json）然后通过笛卡尔积来生成各种 不同的入参（有些入参可能会有20-30个 靠人来太难了），实现快速创建测试请求 ，那当然是最好了

**Comment by luty2018** [comment]
好的， 那我们加一下计数器
