### ISSUE TITLE
[BUG]【系统设置-认证设置】OAuth2的授权端地址、Token 端点地址、用户信息端点地址提示信息不对。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32648]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

【系统设置-认证设置】OAuth2的授权端地址、Token 端点地址、用户信息端点地址提示信息不对。

### 重现步骤

【系统设置-认证设置】OAuth2和OIDC的授权端地址、Token 端点地址、用户信息端点地址等提示信息内容一样，OAuth2的提示信息不应该是这样。
![image](https://github.com/user-attachments/assets/347c36c2-5a39-49a5-9434-fc1b0b6c84db)
![image](https://github.com/user-attachments/assets/7154965c-91ce-4e99-a9f5-422c028a6fa6)

v2版本
![image](https://github.com/user-attachments/assets/fd6a0d0d-d82c-4f64-9387-ec8d485f2501)

**Comment by 13290445582** [comment]
您好，问题已修复，V3.2.0已发布，请升级使用。
