### ISSUE TITLE
[BUG]接口自动化自定义请求对应的保存按钮无功能

### ISSUE THREAD

**Issue by kxzonly** [metersphere/metersphere#3265]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10

**Bug 描述**
接口自动化自定义请求对应的保存按钮无功能

**Bug 重现步骤**
1.  接口测试-接口自动化
2. 打开日报自动化，选择一个自定义请求，点击右下角的保存

**期待的正确结果**
正确情况下应该是什么样的？
提示保存成功

**截图**
![image](https://user-images.githubusercontent.com/37934520/119825467-8cb26d00-bf29-11eb-9517-f80f5e5e3b45.png)
![image](https://user-images.githubusercontent.com/37934520/119825498-963bd500-bf29-11eb-8d27-26dda7827291.png)

**Comment by zyyfit** [comment]
您好，是在场景里添加自定义请求吗？没有复现这个问题呢，是不是因为登录超时了？

**Comment by kxzonly** [comment]
> 您好，是在场景里添加自定义请求吗？没有复现这个问题呢，是不是因为登录超时了？
![image](https://user-images.githubusercontent.com/37934520/120138465-1eabc580-c209-11eb-819c-5c8832055ffe.png)

是自定义请求的，只不过这些请求是导入进去的，用jmeter和postman导出的文件都会这么，提示
版本是用安装文件进行安装的，理论上不会有配置的问题的

**Comment by xulinde** [comment]
v1.12.1已修复
