### ISSUE TITLE
[BUG]接口脚本中添加了后置脚本，如果不写内容的话，控制台会报错

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32654]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

接口脚本中添加了后置脚本，如果不写内容的话，控制台会报错

### 重现步骤

1. 创建接口，添加前后置脚本，前置脚本写了内容，后置脚本没有填写内容
2. 调试接口，发现控制台执行报错
<img width="641" alt="1723714125674" src="https://github.com/user-attachments/assets/ae5025d1-b322-4e42-875a-63c61c0b3798">

### 期待的正确结果

接口脚本中添加了后置脚本，如果不写内容的话，控制台也不会报错

### 相关日志输出

```shell
无
```

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
