### ISSUE TITLE
[BUG] JSON结构校验异常

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32662]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

当使用JSON结构校验时，不勾选必含，只勾选类型校验，意思是若存在这个字段，才进行校验，但实际上是无论这个字段是否出现，都会进行类型校验

<img width="988" alt="Screenshot 2024-08-15 at 22 53 12" src="https://github.com/user-attachments/assets/2e941968-ddc2-4359-82f0-a29ad61a3ceb">

### 重现步骤

如上

### 期待的正确结果

只有字段存在时才进行校验

**Comment by fit2-zhao** [comment]
如果勾选了类型校验，默认就会验证属性是否存在 & 类型是否一致。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
