### ISSUE TITLE
[FEATURE]性能测试报告展示，若数据量特别庞大，页面会非常卡

### ISSUE THREAD

**Issue by kxzonly** [metersphere/metersphere#3266]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/37934520/119825721-d733e980-bf29-11eb-9cf7-ac872f4a1450.png)
如上图所示，点数太多导致页面已经拖不动了

**请描述你建议的实现方案**
减少显示点数（画图采样点更少）或支持手动选择在图形中展示的接口情况

**Comment by xulinde** [comment]
感谢反馈，后续版本优化下

**Comment by liuruibin** [comment]
编辑性能测试的高级设置有个聚合时间，默认会根据时间长短来确定采样点
