### ISSUE TITLE
[FEATURE] 场景用例增加一个回退功能（有时候修改参数的时候，保存后，执行错误。想回退到之前的样子。）

### ISSUE THREAD

**Issue by zeqiyang** [metersphere/metersphere#32678]
### MeterSphere 版本

v2.0.0-81da75b6

### 联系方式

1215326987@qq.com

### 请描述您的需求或者改进建议

场景用例增加一个回退功能（有时候修改参数的时候，保存后，执行错误。想回退到之前的样子。）

**Comment by luty2018** [comment]
这个功能我们规划到v3了， 每次修改都有变更历史，同时也可以恢复到前一次的变更，可以关注我们的发布计划！

**Comment by zeqiyang** [comment]
> 这个功能我们规划到v3了， 每次修改都有变更历史，同时也可以恢复到前一次的变更，可以关注我们的发布计划！

可以回退多次吗？一次作用不大

**Comment by luty2018** [comment]
> > 这个功能我们规划到v3了， 每次修改都有变更历史，同时也可以恢复到前一次的变更，可以关注我们的发布计划！
> 
> 可以回退多次吗？一次作用不大

每次保存都会生成一条变更记录，可以指定回退到某一次的修改。
