### ISSUE TITLE
[BUG]性能测试输出报告的折线图为所有接口的数据（在减少部分接口数据的前提下）

### ISSUE THREAD

**Issue by kxzonly** [metersphere/metersphere#3267]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10

**Bug 描述**
输出的pdf折线图不是减少后的折线图

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
按照页面展示的结果进行输出，因为有的时候这个结果比较多，但全展示太乱，实际只需要展示一些重要接口

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37934520/119826578-bfa93080-bf2a-11eb-8c6d-e5296ee406e4.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后面版本修复

**Comment by liuruibin** [comment]
我们会根据测试市场来控制点位，单位如果选择了分钟或小时的时候这个有一点问题。现在已经修复。
