### ISSUE TITLE
[QUESTION]咨询一下，如果测试计划是[已完成]状态，相关联的测试用例执行结果是否会锁定？（建议对执行人锁定，仅保留计划创建人或者项目管理员编辑，确保后续回溯的准确性）

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32671]
### 请描述您的问题

![image](https://github.com/user-attachments/assets/69a50896-6ab6-48a3-8d50-d001b1663265)
[QUESTION]咨询一下，如果测试计划是[已完成]状态，相关联的测试用例执行结果是否会锁定？（建议对执行人锁定，仅保留计划创建人或者项目管理员编辑，确保后续回溯的准确性）

**Comment by Hyyfit** [comment]
[已完成]状态还是可以执行、可以关联/取消关联用例，不会锁定。
测试计划的状态是根据计划内关联的用例是否执行，系统实时计算的。状态更新逻辑为：
 - 计划内所有用例都有结果---[已完成]
 - 计划内所有用例都没有结果---[未开始]
 - 计划内部分用例有结果---[进行中]

您可以对[已完成的]计划，手动更新状态为[已归档]，归档后的计划就不会再出现变更，也不会再执行了。

**Comment by henbell2** [comment]
> [已完成]状态还是可以执行、可以关联/取消关联用例，不会锁定。 测试计划的状态是根据计划内关联的用例是否执行，系统实时计算的。状态更新逻辑为：
> 
> * 计划内所有用例都有结果---[已完成]
> * 计划内所有用例都没有结果---[未开始]
> * 计划内部分用例有结果---[进行中]
> 
> 您可以对[已完成的]计划，手动更新状态为[已归档]，归档后的计划就不会再出现变更，也不会再执行了。

明白了，谢谢！
