### ISSUE TITLE
[FEATURE]缺陷管理增加按照不同字段搜索的功能

### ISSUE THREAD

**Issue by yxz312** [metersphere/metersphere#3268]
**请描述您的需求或者改进建议.**
缺陷管理增加按照不同字段搜索的功能，能根据创建人、处理人、bug标题和bug状态进行搜索

![image](https://user-images.githubusercontent.com/49225469/119852591-00f90a80-bf42-11eb-9523-3150e70c9de4.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
后面版本会支持

**Comment by xulinde** [comment]
v10.5已支持
