### ISSUE TITLE
[BUG]新增参数时在高级参数设置页面，如果添加了一个函数就无法取消选中

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#327]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.2.0-b610

**Bug 描述**
简要描述您碰到的问题
新增参数时在高级参数设置页面，如果添加了一个函数就无法取消选中

**Bug 重现步骤**
1.  新增参数
2. 点击高级参数设置
3. 点击添加函数
4. 

**期待的正确结果**
正确情况下应该是什么样的？
只剩下一个函数的时候可以取消选中

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
你好，这里为啥需要取消选中呢？不需要的话，不保存直接关闭页面就可以的
