### ISSUE TITLE
[FEATURE]3.0编辑用例的界面建议功能区支持放开

### ISSUE THREAD

**Issue by river891105** [metersphere/metersphere#32709]
### MeterSphere 版本

3.0

### 联系方式

xuzheng@patsnap.com

### 请描述您的需求或者改进建议

<img width="596" alt="截屏2024-08-19 15 25 48" src="https://github.com/user-attachments/assets/5d5f6248-0eb7-415a-b5e7-9ee5a1d26aa8">

3.0 版本在编辑用例时，是隐藏式的点选节点，添加下级用例或者模块，同时需要点选优先级“P”, 然后弹出 p1,p2
个人建议能够支持像 2.0 一样的顶部功能区，有些添加操作完全不需要操作两次，比如添加优先级

<img width="795" alt="截屏2024-08-19 15 27 47" src="https://github.com/user-attachments/assets/cce69eb6-dd94-4e33-97cc-90d1c0b0f26c">

**Comment by luty2018** [comment]
感谢建议， 我们优化一下
