### ISSUE TITLE
[SQL查询建议增加执行多条查询语句获取结果变量的功能]

### ISSUE THREAD

**Issue by LuxTong** [metersphere/metersphere#32712]
### MeterSphere 版本

2.10.17-lts

### 联系方式

MeterSphere交流群46，阿汤锅

### 请描述您的需求或者改进建议

使用的postgresql数据库。
建议前置SQL和后置SQL支持多条查询SQL语句执行，并将结果添加到变量中。
目前前后置SQL步骤都只会将最后一条查询语句的结果存入变量。

### 请描述你建议的实现方案

![Snipaste_2024-08-19_15-50-45](https://github.com/user-attachments/assets/f130a95b-4939-499d-be8b-e8df208fd8cb)

**Comment by fit2-zhao** [comment]
是支持的，和你的JDBC 配置有关系。
<img width="913" alt="image" src="https://github.com/user-attachments/assets/128b087c-7b11-43f6-bca1-abc407f45c1a">

**Comment by fit2-zhao** [comment]
不支持这种用法，可以尝试用 JOIN 。
