### ISSUE TITLE
[BUG]【系统-资源池】新增资源池，切到"项目管理-应用设置-执行资源池"下拉框，并没有出现新增的资源池选项。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32718]
### MeterSphere 版本

v3.1.0

### 使用外置数据库

否

### 问题描述

【系统-资源池】是企业版，新增使用范围为"所有组织"的资源池，切到"项目管理-应用设置-执行资源池"下拉框，并没有出现新增的资源池选项。

### 重现步骤

【系统-资源池】是企业版，新增使用范围为"所有组织"的资源池，切到"项目管理-应用设置-执行资源池"下拉框，并没有出现新增的资源池选项。
![image](https://github.com/user-attachments/assets/91ce3c36-3c8b-4bcf-8134-1078bf2da935)
![image](https://github.com/user-attachments/assets/8eb4ee6e-5366-449d-90ea-2b09c019a774)
![image](https://github.com/user-attachments/assets/1ae48173-ac5a-425d-b7e5-21473ad3de55)

**Comment by fit2-zhao** [comment]
感觉你应该是项目上没选择吧，如下图：

<img width="958" alt="image" src="https://github.com/user-attachments/assets/ffadca49-c883-4fa7-bb48-290f568f3cc9">
