### ISSUE TITLE
[BUG]接口定义swagger导入后，该接口新增用例，然后再次导入覆盖后，打开报错

### ISSUE THREAD

**Issue by ltt12345** [metersphere/metersphere#32724]
### MeterSphere 版本

v3.0

### 使用外置数据库

否

### 问题描述

"com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `io.metersphere.api.dto.schema.JsonSchemaItem` from Array value (token `JsonToken.START_ARRAY`)\n at [Source: (String)\"{\"polymorphicName\":\"MsHTTPElement\",\"stepId\":null,\"resourceId\":null,\"projectId\":null,\"name\":\"新增故障类型\",\"enable\":true,\"children\":[{\"polymorphicName\":\"MsCommonElement\",\"stepId\":null,\"resourceId\":null,\"projectId\":null,\"name\":null,\"enable\":true,\"children\":null,\"parent\":null,\"csvIds\":null,\"preProcessorConfig\":{\"enableGlobal\":true,\"processors\":[]},\"postProcessorConfig\":{\"enableGlobal\":true,\"processors\":[]},\"assertionConfig\":{\"enableGlobal\":true,\"assertions\":[]}}],\"parent\":null,\"csvIds\":null,\"customizeReq\"[truncated 20811 chars]; line: 1, column: 4873] (through reference chain: io.metersphere.api.dto.request.http.MsHTTPElement[\"body\"]->io.metersphere.api.dto.request.http.body.Body[\"jsonBody\"]->io.metersphere.api.dto.request.http.body.JsonBody[\"jsonSchema\"]->io.metersphere.api.dto.schema.JsonSchemaItem[\"properties\"]->java.util.LinkedHashMap[\"orderPost\"]->io.metersphere.api.dto.schema.JsonSchemaItem[\"items\"])"

### 重现步骤

1、swagger导入接口定义
2、增加接口用例
3、接口定义变更，覆盖导入
4、点击接口定义详情，报错

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v3.1没有复现，建议升级一下
