### ISSUE TITLE
[BUG] v3.1 curl无法导入body

### ISSUE THREAD

**Issue by tshch1989** [metersphere/metersphere#32742]
### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

接口测试功能中调试模式使用curl导入请求时，无法导入body，并且请求方法默认解析为GET
尝试指定为POST请求后，请求方法可以正确解析
但是，body仍然无法导入

### 重现步骤

1. 登录metersphere
2. 点击【接口测试】
3. 点击【调试】
4. 点击【新建 按钮后的 下拉按钮】
5. 点击【导入请求】
6. 在弹出窗口中填充（url部分做了变更）：
curl 'https://mytest.baidu.com/api/my-api' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'X-XSRF-TOKEN: KilNEGF8Te6vqOsVtxMUlQ' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: https://www.liepin.com/' \
  -H 'X-Requested-With: XMLHttpRequest' \
  --data-raw 'opCode=lp_c_5110&adIds=16099%2C16869%2C16867%2C17287&type=1'
7. 点击【确认】

### 期待的正确结果

![image](https://github.com/user-attachments/assets/b9d28f87-18d4-410a-aa3e-0b974db8bee0)

**Comment by fit2-zhao** [comment]
有个相同问题已经在规划中了，请关注后续版本。
https://github.com/metersphere/metersphere/issues/31282
