### ISSUE TITLE
[BUG] Jmeter请求body中的注释// 导致在平台上压测执行异常

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#32758]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

是

### 问题描述

https://github.com/metersphere/metersphere/issues/31359#issue-2341531147

脚本案例已邮件@yicheng.wang@fit2cloud.com，谢谢

### 重现步骤

https://github.com/metersphere/metersphere/issues/31359#issue-2341531147

**Comment by 13290445582** [comment]
您好，看了下您的Jmeter版本是5.6.2，MeterSphere的V2版本使用的Jmeter版本为5.5。在Jmeter5.5中请求body中有注释存在，执行会失败，所以在您的Jmeter上执行成功的jmx导入到V2版本的MeterSphere内压测时会错误。

**Comment by zhangzhaox** [comment]
> 您好，看了下您的Jmeter版本是5.6.2，MeterSphere的V2版本使用的Jmeter版本为5.5。在Jmeter5.5中请求body中有注释存在，执行会失败，所以在您的Jmeter上执行成功的jmx导入到V2版本的MeterSphere内压测时会错误。

1、即时使用5.6版本的脚本  删除// 注释后  是可以正常压测运行的
2、切换成5.5版本的脚本后  依然不能在保留// 保留注释的情况下正常运行
3、你那边用我的案例案例执行 可以在保留//注释的情况下正常运行？

**Comment by 13290445582** [comment]
您好，Jmeter5.5中请求体带注释，本身就会执行失败，所以MeterSphereV2肯定也是失败的，V2暂不支持请求体带注释。
