### ISSUE TITLE
[BUG]场景变量中配置 csv，导出的 jmx 没有 csv data set 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#32755]
### 联系方式

shenkaibo

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

场景变量中配置 csv，导出的 jmx 没有 csv data set 

### 重现步骤

场景变量中配置 csv，导出的 jmx 没有 csv data set 
<img width="740" alt="image" src="https://github.com/user-attachments/assets/e797966b-a630-4fdb-9c4e-8bcf0624664f">
![image](https://github.com/user-attachments/assets/7e862454-4a59-4787-88d1-c0cb0256bbdd)

**Comment by youliyuan-fit2cloud** [comment]
你好，一直以来不支持导出csv。

**Comment by shenkaibo** [comment]
不是 csv , csv data set 这个设置组件也不支持么？
