### ISSUE TITLE
[BUG]【接口自动化】接口场景相互引用问题

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#32772]
### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

是

### 问题描述

两个接口场景：场景A和场景B
在场景A里引用了场景B，场景B里又引用了场景A，结果造成了场景之间的相互引用，测试时，cpu过载，页面加载不出来

### 重现步骤

两个接口场景：场景A和场景B
在场景A里引用了场景B，场景B里又引用了场景A，结果造成了场景之间的相互引用，测试时，cpu过载，页面加载不出来

### 期待的正确结果

如何规避这样的问题；若造成了相互引用，如果解决这个问题

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续会优化这里。

**Comment by 13290445582** [comment]
感谢反馈，问题已修复，请升级v2.10.18版本使用。
