### ISSUE TITLE
[BUG]导出jmeter脚本，脚本相关的控制名称会变成脚本内容，而不是设置好的脚本名称。

### ISSUE THREAD

**Issue by KnightBlood** [metersphere/metersphere#32788]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

导出jmeter脚本，脚本相关的控制名称会变成脚本内容，而不是设置好的脚本名称

例如 JSSR223断言，在metersphere设置名称，导出脚本后，名称变成了实际脚本内容

### 重现步骤

1.在接口场景中增加jssr223断言，并正确输入脚本
2.导出为jmeter脚本
3.用jmeter打开该脚本

### 期待的正确结果

jssr223断言 的名称就应该时场景中设好的名称

### 附加信息

希望在v2版本中修复该问题

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
