### ISSUE TITLE
[BUG]场景断言被计算为步骤，执行场景时场景断言被作为被当作未执行的步骤导致执行结果为error

### ISSUE THREAD

**Issue by KnightBlood** [metersphere/metersphere#32787]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

场景断言被计算为步骤，执行场景时场景断言被作为被当作未执行的步骤导致执行结果为error

### 重现步骤

1.场景断言中增加场景断言
2.在场景列表中执行场景

### 期待的正确结果

场景断言不应该被计算为步骤，或者统计结果时不应该统计场景断言

### 附加信息

希望能够在v2版本中修改，不要放到v3毕竟功能不完善

**Comment by youliyuan-fit2cloud** [comment]
你好，没有太理解这个问题，截图看下你这个场景断言的报告。

**Comment by KnightBlood** [comment]
> 你好，没有太理解这个问题，截图看下你这个场景断言的报告。

![微信图片_20240822152557](https://github.com/user-attachments/assets/38252745-aa0a-46cf-805d-664842103be2)

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，没有太理解这个问题，截图看下你这个场景断言的报告。
> 
> ![微信图片_20240822152557](https://private-user-images.githubusercontent.com/14256591/360329120-38252745-aa0a-46cf-805d-664842103be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI2NTksIm5iZiI6MTcyNDMxMjM1OSwicGF0aCI6Ii8xNDI1NjU5MS8zNjAzMjkxMjAtMzgyNTI3NDUtYWEwYS00NmNmLTgwNWQtNjY0ODQyMTAzYmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDcyZjZjOGE0YzlkZTllYjFlMjgxODg3MjFiNDk2ZWIzMzFiY2ZhMTljMGJhYzIyOGQ0OWE0NGI5MjE3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8n2vkZk_FJC-QoEsCSIzrfZlqD5Mn_RGgXP77-nOKQ8)

看这个图中的 80% 通过率的报告时间 和 最新上面 报告时间不一致，建议检查下是否是相同场景配置。我们测试环境没有复现该问题。

**Comment by KnightBlood** [comment]
> > > 你好，没有太理解这个问题，截图看下你这个场景断言的报告。
> > 
> > 
> > ![微信图片_20240822152557](https://private-user-images.githubusercontent.com/14256591/360329120-38252745-aa0a-46cf-805d-664842103be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI2NTksIm5iZiI6MTcyNDMxMjM1OSwicGF0aCI6Ii8xNDI1NjU5MS8zNjAzMjkxMjAtMzgyNTI3NDUtYWEwYS00NmNmLTgwNWQtNjY0ODQyMTAzYmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDcyZjZjOGE0YzlkZTllYjFlMjgxODg3MjFiNDk2ZWIzMzFiY2ZhMTljMGJhYzIyOGQ0OWE0NGI5MjE3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8n2vkZk_FJC-QoEsCSIzrfZlqD5Mn_RGgXP77-nOKQ8)
> 
> 看这个图中的 80% 通过率的报告时间 和 最新上面 报告时间不一致，建议检查下是否是相同场景配置。我们测试环境没有复现该问题。

就是同一个 ，只不过我执行了好多次

**Comment by KnightBlood** [comment]
> > > 你好，没有太理解这个问题，截图看下你这个场景断言的报告。
> > 
> > 
> > ![微信图片_20240822152557](https://private-user-images.githubusercontent.com/14256591/360329120-38252745-aa0a-46cf-805d-664842103be2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI2NTksIm5iZiI6MTcyNDMxMjM1OSwicGF0aCI6Ii8xNDI1NjU5MS8zNjAzMjkxMjAtMzgyNTI3NDUtYWEwYS00NmNmLTgwNWQtNjY0ODQyMTAzYmUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNDcyZjZjOGE0YzlkZTllYjFlMjgxODg3MjFiNDk2ZWIzMzFiY2ZhMTljMGJhYzIyOGQ0OWE0NGI5MjE3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8n2vkZk_FJC-QoEsCSIzrfZlqD5Mn_RGgXP77-nOKQ8)
> 
> 看这个图中的 80% 通过率的报告时间 和 最新上面 报告时间不一致，建议检查下是否是相同场景配置。我们测试环境没有复现该问题。

看看你们的测试结果

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/40183417-d705-46d4-951d-93054280ab6c)

查看 接口测试-测试报告tab结果，和场景中执行结果对比。

**Comment by KnightBlood** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/360344096-40183417-d705-46d4-951d-93054280ab6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTQ1OTQsIm5iZiI6MTcyNDMxNDI5NCwicGF0aCI6Ii81NDYxMjg2NC8zNjAzNDQwOTYtNDAxODM0MTctZDcwNS00NmQ0LTk1MWQtOTMwNTQyODBhYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxM2U3MTM4ZDMyZmM5OGNlYWE5YzVkN2I5NGMzNTI2NmFhNjg0MTVjZjM5ODRmODQ2ZTVjZmVlMDAzYjJlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WWMjKfjZACvktuKuGIxFRYlsju6poe3V_YHHcb7dJpE)
> 
> 查看 接口测试-测试报告tab结果，和场景中执行结果对比。

你的场景断言里加断言内容了么?

**Comment by KnightBlood** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/360344096-40183417-d705-46d4-951d-93054280ab6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTUxMjksIm5iZiI6MTcyNDMxNDgyOSwicGF0aCI6Ii81NDYxMjg2NC8zNjAzNDQwOTYtNDAxODM0MTctZDcwNS00NmQ0LTk1MWQtOTMwNTQyODBhYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MjAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MzkzMzM1YWM2N2NjYmYzZWZlYWJmNTZiYzY1YjhlMzU2OWExOWQzYjZlMTQ1MmYzNjQ3ZmQyN2YyNDdhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LciWDkg7rBi85eSr0ttE4MsL18sv_4Q7-HmDejbhgb8)
> 
> 查看 接口测试-测试报告tab结果，和场景中执行结果对比。

有没有你们的环境能够测试下

**Comment by KnightBlood** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/360344096-40183417-d705-46d4-951d-93054280ab6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTU1NjIsIm5iZiI6MTcyNDMxNTI2MiwicGF0aCI6Ii81NDYxMjg2NC8zNjAzNDQwOTYtNDAxODM0MTctZDcwNS00NmQ0LTk1MWQtOTMwNTQyODBhYjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4Mjc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZjgyMTkzYWIyNjg3ZjU1MTZkYTM3ODliZGY1YTlmMGI1Yzk1ZTk1N2UyODlmOTcxOGJhODJjYTY2NTUwM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FjXhGtYd7qrS9dHamvdTlzDo3ZJy9q2CGaNV3gwBfiA)
> 
> 查看 接口测试-测试报告tab结果，和场景中执行结果对比。
emmm [你们线上的测试环境居然是好的](https://cloud2.metersphere.com/#/api/automation)

不过这个环境是2.10.16版本的，你们试验的版本也是2.10.17么

**Comment by youliyuan-fit2cloud** [comment]
是的，最新版本。场景断言有添加响应时间和响应码断言。

**Comment by KnightBlood** [comment]
> 是的，最新版本。场景断言有添加响应时间和响应码断言。

![image](https://github.com/user-attachments/assets/559b5a86-01b7-41fa-8272-278dc0888682)

我找到原因了，是因为这个引起的，这是bug么

**Comment by youliyuan-fit2cloud** [comment]
这不是bug，开启了关联场景结果了。

**Comment by KnightBlood** [comment]
> 这不是bug，开启了关联场景结果了。

好的
