### ISSUE TITLE
[BUG] 集成Jira平台传递附件接口报错

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32785]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

metersphere集成jira的插件，调用jira上传附件接口时提示缺失content-length请求头，当我手动添加头时，又提示流传递不对，具体函数在io.metersphere.platform.client.JiraAbstractClient#uploadAttachment

插件报错如下
![image](https://github.com/user-attachments/assets/bdcbd7b7-b883-4e71-8b87-913bcfe4ddb6)

我经过测试，应该是和restemplate有关，方法里的代码没问题，我使用sprintboot2.x相应的resttemplate没有问题，严重怀疑为
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.1.4</version>
        </dependency>
版本造成的

### 重现步骤

如上

**Comment by ijwstl** [comment]
看起来与这个有关
https://stackoverflow.com/questions/77658440/springboot-3-2-0-custom-resttemplate-doesnt-send-content-length

https://github.com/spring-projects/spring-framework/issues/32678

https://github.com/spring-projects/spring-boot/issues/38841

**Comment by ijwstl** [comment]
升级3.3.x会导致springcloud和springboot版本不兼容，建议在这个方法里使用client5原生方法上传文件，即可解决该问题

**Comment by song-cc-rock** [comment]
@ijwstl  我本地使用的Content-Length为空的文件, 在`ms 2.10.7` 版本并未复现, 可以正常上传, 并未出现`HttpClentErrorException 
 411`的情况;        `ms 2.10.7`的版本springboot版本也并未升级至`3.3.x`, 一直都是`3.2.x`,

**Comment by song-cc-rock** [comment]
@ijwstl 看看是不是jira插件版本不太对
![image](https://github.com/user-attachments/assets/7ef7f419-3c75-41fa-a9a4-03d718fe759c)

**Comment by ijwstl** [comment]
> @ijwstl 看看是不是jira插件版本不太对 ![image](https://private-user-images.githubusercontent.com/40567414/360333927-7ef7f419-3c75-41fa-a9a4-03d718fe759c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI5MTAsIm5iZiI6MTcyNDMxMjYxMCwicGF0aCI6Ii80MDU2NzQxNC8zNjAzMzM5MjctN2VmN2Y0MTktM2M3NS00MWZhLWE5YTQtMDNkNzE4ZmU3NTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYTBkZTZmZDdmMDBlMTA4MjZhNjUzMWE0NmVhZTJlMDRmYTZjZDI0MzA4ZTZkYjQyZmRmYWNkZGQ4OTUyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.phSPPHqnvi417gMp9ydzaMjxqOKq-d85UY193JZ3EiE)

现在暴露的问题是restemplate不会在上传文件时自动设置Content-Length导致的报错

您使用的是包含依赖的程序包，我使用的是不包含依赖的，我看插件包里spring-web版本为6.0.4，项目主体为6.1.10，为了防止个别类冲突，所以我选择了不包含依赖包的，建议可以尝试下不包含依赖的，对于该段代码应该是会造成影响的，估计可以复现该问题。不过问题不大，可以当作业余研究，测试下正常大小的文件。

分享一下后续解决的过程，升级springboot失败后，我选择了引入httpclient5core的依赖，企图通过使用httpclint5单独实现文件同步，后续发现httpclient5在处理中文文件名时无论如何设置编码都在传递到jira时显示乱码，而5.x版本又去掉了兼容模式的设置，最后只能引入okhttp3，解决了该问题

**Comment by song-cc-rock** [comment]
> > @ijwstl 看看是不是jira插件版本不太对 ![image](https://private-user-images.githubusercontent.com/40567414/360333927-7ef7f419-3c75-41fa-a9a4-03d718fe759c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTI5MTAsIm5iZiI6MTcyNDMxMjYxMCwicGF0aCI6Ii80MDU2NzQxNC8zNjAzMzM5MjctN2VmN2Y0MTktM2M3NS00MWZhLWE5YTQtMDNkNzE4ZmU3NTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYTBkZTZmZDdmMDBlMTA4MjZhNjUzMWE0NmVhZTJlMDRmYTZjZDI0MzA4ZTZkYjQyZmRmYWNkZGQ4OTUyMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.phSPPHqnvi417gMp9ydzaMjxqOKq-d85UY193JZ3EiE)
> 
> 现在暴露的问题是restemplate不会在上传文件时自动设置Content-Length导致的报错
> 
> 您使用的是包含依赖的程序包，我使用的是不包含依赖的，我看插件包里spring-web版本为6.0.4，项目主体为6.1.10，为了防止个别类冲突，所以我选择了不包含依赖包的，建议可以尝试下不包含依赖的，对于该段代码应该是会造成影响的，估计可以复现该问题。不过问题不大，可以当作业余研究，测试下正常大小的文件。
> 
> 分享一下后续解决的过程，升级springboot失败后，我选择了引入httpclient5core的依赖，企图通过使用httpclint5单独实现文件同步，后续发现httpclient5在处理中文文件名时无论如何设置编码都在传递到jira时显示乱码，而5.x版本又去掉了兼容模式的设置，最后只能引入okhttp3，解决了该问题

好的, 我试下排除插件的spring-web依赖, 尝试复现该问题
