### ISSUE TITLE
[BUG]自建项目用户组取消“邀请用户”权限，但是“邮件邀请”权限任然存在

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32783]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/ea9a419f-0ce0-4959-9b47-b7720fd6a538)
自建项目用户组取消“邀请用户”权限，但是“邮件邀请”权限任然存在

### 重现步骤

1、自建项目用户组取消“邀请用户”权限
2、登录一个项目用户
3、查看邀请成员权限，“邮件邀请”任然存在

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，建议检查该用户是否还有其他用户组，权限是开启的。
