### ISSUE TITLE
[BUG]导入postman接口 如果body的mode为raw，如果缺少raw字段，时导入postman接口失败

### ISSUE THREAD

**Issue by KnightBlood** [metersphere/metersphere#32790]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

导入postman接口 如果body的mode为raw，如果缺少raw字段，时导入postman接口失败
比如
`"request":{
	"body"{
		"mode":"raw",
		"raw":"{}"
	}
}`

如果此时缺少“raw”:"{}",那么导入就会失败，而postman导出的json文件就有可能会缺少“raw”:"{}"

### 重现步骤

导入缺少“raw”:"{}"的postman json文件（接口测试）

### 期待的正确结果

应该能够导入，只不过 缺少时你们应该将raw 视为空

### 附加信息

希望在v2版本中修复

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题后续版本会修复。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
