### ISSUE TITLE
[FEATURE]缺陷管理建议支持点击“缺陷ID”或“缺陷标题”，只读跳转到具体的详情（类似编辑的页面内容）

### ISSUE THREAD

**Issue by gocho** [metersphere/metersphere#32798]
### MeterSphere 版本

v2.10.16-lts

### 请描述您的需求或者改进建议

建议支持点击“缺陷ID”或“缺陷标题”，只读跳转到具体的详情（类似编辑的页面内容）

**Comment by Hyyfit** [comment]
您好，我们v3 已实现 点击ID，显示缺陷详情
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/330ed9a2-0e27-450b-8e05-90e51f3f3336">
