### ISSUE TITLE
[BUG]在接口测试的接口编辑页面下，切换组织会导致项目名称显示为uuid

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#328]
**MeterSphere 版本**
1.2.1

**Bug 描述**
在接口测试的接口编辑页面下，切换组织会导致项目名称显示为uuid

**截图**
如果有截图，请附上截图.
<img width="876" alt="WechatIMG1204" src="https://user-images.githubusercontent.com/21210217/91975199-9b307700-ed51-11ea-9b3d-c6fff6d83287.png">

**Comment by AgAngle** [comment]
你好，该问题是权限问题，切换组织应无权限访问该测试，目前该问题已修复，请升级验证
