### ISSUE TITLE
[BUG]v3.0 版本的接口请求成功后 ，返回头字段缺失 setCookie 相对比老版本遇到的问题

### ISSUE THREAD

**Issue by kennykai** [metersphere/metersphere#32809]
### MeterSphere 版本

V3.0 

### 使用外置数据库

否

### 问题描述

v3.0 版本的接口请求成功后 ，返回头字段缺失 setCookie 相对比老版本遇到的问题

### 重现步骤

1、同接口请求 新版本和老版本 请求成功后 查看返回头参数。
【结果】缺失  setCookie 参数  提取的时候 正则提取 拿不到这个字段

### 期待的正确结果

setcookie 可以正常提取 对应的value值

**Comment by youliyuan-fit2cloud** [comment]
你好，请先检查自身接口问题。或者把接口具体信息发一下我们再看看。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
