### ISSUE TITLE
[BUG] 通过资源池修改最大并发数，但控制测试计划并行用例数量的操作未生效

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#32800]
### MeterSphere 版本

v1.20.17-lts

### 使用外置数据库

否

### 问题描述

1、通过修改资源池最大并发数2，测试计划中加入20个场景用例，每个场景用例执行时间需要花费2分钟，选择并行时，报告显示所有用例是一起执行的，该配置未生效

### 重现步骤

1、修改资源池并发数
2、创建测试计划
3、在测试计划中加入场景用例
4、并行执行测试计划

### 期待的正确结果

测试计划并行执行时，能按照资源池最大并发数执行用例

### 附加信息

![1724314380101](https://github.com/user-attachments/assets/56fbd995-d20c-419b-8825-d2f559fbd77e)
![image](https://github.com/user-attachments/assets/8ee618c5-829a-4a2d-a16d-055d76be4b47)

![image](https://github.com/user-attachments/assets/4dda851c-314e-44ac-a31f-786e98a5c651)

**Comment by youliyuan-fit2cloud** [comment]
你好，这个并发数是资源池的执行并发数，可以理解为处理任务的线程数量，不是任务并发数。
