### ISSUE TITLE
[BUG]同步缺陷机制选择全量同步后，再次查看自动选择了增量同步

### ISSUE THREAD

**Issue by donkey88888** [metersphere/metersphere#32803]
### 联系方式

交流群名：metersphere交流群50 昵称：await

### MeterSphere 版本

v3.2.0-d6ba97e1

### 使用外置数据库

否

### 问题描述

选择全量同步后，点击确定，再次查看时自动选择了增量同步

### 重现步骤

选择同步缺陷机制为全量同步
点击确定
再次查看同步缺陷机制

### 期待的正确结果

展示正确的同步缺陷机制

### 附加信息

![image](https://github.com/user-attachments/assets/00e4ab1a-a116-4c82-b3d3-87688087f206)

**Comment by song-cc-rock** [comment]
已复现, 这个是前端数据展示的BUG, 下个版本修复

![image](https://github.com/user-attachments/assets/b19a3580-cacc-40e4-b095-a6c60515621a)

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
