### ISSUE TITLE
[BUG]在3.2.0版本上恢复3.1.0版本备份的数据，同步缺陷后，metersphere系统崩溃无法自动恢复

### ISSUE THREAD

**Issue by donkey88888** [metersphere/metersphere#32801]
### 联系方式

交流群名：metersphere交流群50 昵称：await

### MeterSphere 版本

v3.2.0-d6ba97e1

### 使用外置数据库

否

### 问题描述

①在3.2.0版本上恢复3.1.0版本备份的数据，同步缺陷后，metersphere系统崩溃无法自动恢复
②因无法自动恢复，我把数据库的表全部删除，重新source了xxx.sql文件，重启服务成功
③从禅道同步缺陷（大量120条），服务崩溃重启，可以自动重启成功
④从禅道同步缺陷（大概20条），服务没有崩溃，但是没有同步成功

### 重现步骤

3.1.0版本上备份数据库，得到xxx.sql文件
安装3.2.0版本，使用xxx.sql恢复数据库
点击同步缺陷按钮

### 期待的正确结果

成功同步缺陷，结果metersphere微服务崩溃不断重启，但无法自动重启成功

### 附加信息

![微信图片_20240822161329](https://github.com/user-attachments/assets/23f767fa-5b84-4123-af61-9ed856fbd6aa)
![微信图片_20240822161335](https://github.com/user-attachments/assets/de226527-ea48-41f4-b976-75b7ed212941)
![微信图片_20240822161339](https://github.com/user-attachments/assets/89302990-db00-4094-b5a3-7de758a229aa)
![image](https://github.com/user-attachments/assets/4596b3e6-4bc6-4596-ab9c-171c0b9ed55c)

**Comment by song-cc-rock** [comment]
@donkey88888  如下图, 这个报错是平台插件删除接口参数改动导致的, 重新上传一下最新的插件试试.   [禅道3.2.0插件下载地址](https://github.com/metersphere/metersphere-platform-plugin/releases/tag/v3.2.0),  还需要把禅道配置项: $config -> features -> apiGetModel=true 打开,  堆内存溢出问题我来来复现试试. 
![image](https://github.com/user-attachments/assets/3eade4ae-90c4-4183-89a7-bf90f1fe1396)

**Comment by donkey88888** [comment]
已更换禅道插件，并且我已确认禅道开通了超级model权限
①在全量同步时出现崩溃，日志如下
![image](https://github.com/user-attachments/assets/c3732cab-07de-476f-9f77-f8759439ae72)
②选择少量权限同步，提示同步成功，实际没有

**Comment by song-cc-rock** [comment]
> 已更换禅道插件，并且我已确认禅道开通了超级model权限 ①在全量同步时出现崩溃，日志如下 ![image](https://private-user-images.githubusercontent.com/69466069/361389241-c3732cab-07de-476f-9f77-f8759439ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTY5NTQsIm5iZiI6MTcyNDgxNjY1NCwicGF0aCI6Ii82OTQ2NjA2OS8zNjEzODkyNDEtYzM3MzJjYWItMDdkZS00NzZmLTlmNzctZjg3NTk0MzlhZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzNDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZDkyYjIzMjlhMjc4MTYxNjExNjNjYmNkNmMyOWZlMDhjMmEyZTE5OWZhYjNiMzdiMjllYzdmZWM0ZGIzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFy6mIpH0odYeRF3jR_9S-ZflvprREy5WGIFk6zgrZ0) ②选择少量权限同步，提示同步成功，实际没有

少量数据全量同步是正常的, 如下图, 你看看②中是不是有报错日志, 能够帮助排查一下, 感觉是插件中处理禅道字段逻辑中有遗漏的地方 ①中的120条缺陷数据全量同步内存溢出正在尝试复现

![image](https://github.com/user-attachments/assets/cd04558d-a81e-4ffc-8e55-8df9f387dbb6)

**Comment by song-cc-rock** [comment]
这个产品ID也看看是否正确

![image](https://github.com/user-attachments/assets/3fc1d9e8-e8a4-4d33-8305-16da0eae8157)

**Comment by donkey88888** [comment]
产品ID是正确的，除了下图的failed，就是内存溢出
![image](https://github.com/user-attachments/assets/d3657572-c51a-4a79-9e80-a63adc5e9318)

**Comment by song-cc-rock** [comment]
> 产品ID是正确的，除了下图的failed，就是内存溢出 ![image](https://private-user-images.githubusercontent.com/69466069/362222532-d3657572-c51a-4a79-9e80-a63adc5e9318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDEwMDMsIm5iZiI6MTcyNDg0MDcwMywicGF0aCI6Ii82OTQ2NjA2OS8zNjIyMjI1MzItZDM2NTc1NzItYzUxYS00YTc5LTllODAtYTYzYWRjNWU5MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwMjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMzVhMjE4NzFhMDAxY2YzYzVmNWQ4ZDk5ODJkYjlkODZkNDI2OWI5MGJkODM1NzlkY2UyZmFjYTBkMzgxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XoWjLhj4uIBij_HWhs0YG5e7PyQz4YVjrswEKiunyGE)

应该跟这个报错无关, 这是定时任务的报错, 由于本地暂时没有复现少量数据, 全量同步失败的场景, 能否在页面上点击同步时, debug一下插件源码看看具体报错原因. 或者提供一个测试环境复现一下.

**Comment by donkey88888** [comment]
我用新建的项目，同步几十条缺陷已经成功了，但同步几百条权限还是会内存溢出。但是用之前3.1.0版本创建的项目去同步缺陷还是不行的。建议先尝试复现内存溢出的问题，旧项目同步不了不影响我这边使用

**Comment by song-cc-rock** [comment]
> 我用新建的项目，同步几十条缺陷已经成功了，但同步几百条权限还是会内存溢出。但是用之前3.1.0版本创建的项目去同步缺陷还是不行的。建议先尝试复现内存溢出的问题，旧项目同步不了不影响我这边使用

OK, 空余时间来看看
