### ISSUE TITLE
[BUG]【接口同步】页面显示信息[5] 建议改成和提示信息里【5】保持一致

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32805]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【接口同步】页面显示信息[5] 建议改成和提示信息里【5】保持一致
![image](https://github.com/user-attachments/assets/a56f88ae-ccb4-4f01-ad07-7c93096e966a)

### 重现步骤

【接口同步】页面显示信息[5] 建议改成和提示信息里【5】保持一致
![image](https://github.com/user-attachments/assets/a56f88ae-ccb4-4f01-ad07-7c93096e966a)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本优化一下。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
