### ISSUE TITLE
[QUESTION]本地windows部署开发环境的时候，拉取的是V2.2版本分支，登录接口提示“SQL error happened, please check logs”

### ISSUE THREAD

**Issue by jeremyliu17** [metersphere/metersphere#32807]
### 请描述您的问题

前后端都跑起来了，使用账号密码，用户名:admin 密码:metersphere，登录的时候提示错误，看数据库里有amdin的数据，根据这篇博主的[解决方法](https://blog.csdn.net/m0_49925323/article/details/136501430)，说还是数据库字段缺失的问题，但是这篇博主没说清怎么生成SQL脚本，重新运行，所以来这请教一下，希望问题能够解决，感谢
![image](https://github.com/user-attachments/assets/43b8ed05-9a96-4407-9109-57143fd05287)
![image](https://github.com/user-attachments/assets/c786e860-fa44-4102-ac04-51c4d99b90ae)

**Comment by liuruibin** [comment]
由于每个人部署的环境存在差异，源码部署的服务需要自行排查

**Comment by jeremyliu17** [comment]
好的，已经解决了，要排查表字段和实体类对应的字段是否一致
