### ISSUE TITLE
[BUG]导出的用例中，即时勾选所属模块，导出的excel用例所属模块也是为空

### ISSUE THREAD

**Issue by liunamexx** [metersphere/metersphere#32808]
### 联系方式

1149048605@qq.com

### MeterSphere 版本

3.20

### 使用外置数据库

否

### 问题描述

导出的用例中，即时勾选所属模块，导出的excel用例所属模块也是为空

### 重现步骤

导出用例为excel格式

### 期待的正确结果

导出excel的格式中，勾选的导出字段里面，该有的内容都需要有，方便大规模导出导入

**Comment by 13290445582** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
