### ISSUE TITLE
[FEATURE]测试计划/测试规划Tab页，从使用体验上，超级难用

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32802]
### MeterSphere 版本

v3.2.0-d6ba97e1

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/a372058a-4c73-4720-a174-bddb7f64849d)
难用，操作相当不便

**Comment by Somebody-JIAN** [comment]
感谢您的批评，为您带来了不好的使用体验，深感抱歉。

这块业务上我们也在探索怎么样能让他更好用更舒心。 

如果您有什么建设性的意见欢迎告诉我们。 我们也会认真落实。

**Comment by henbell2** [comment]
建议，仅供参考哈！
现在这个页面不知道初衷是啥？没体会到有啥突出价值。跳转到的编辑有全页面、也有右侧半页面，show/hide也感觉不到一致的思路，导图/右侧半页面经常重叠，要命的是导图还不好拖动，只能点中某个元素拖动，但点中某个元素又很容易出发子UI弹出。总之感觉欠思考、欠体验。
建议如果想用思维导图展示测试框架/测试思路，那就聚焦思维导图的展示，清清爽爽。
如果一定要在这里体现测试用例关联或者测试配置，可以切成文字清单模式，每一行加个编辑的跳转，跳转到独立的编辑页，也是清清爽爽，和MeterSphere总体风格相符。
另外 功能用例/场景用例/接口用例，不同阶段、不同项目类型，不一定都是绑定关系，测试规划里面强行把三类测试加入，不可移除，也不太合理

**Comment by Hyyfit** [comment]
非常感谢您的建议，需要再跟您确认一下：
1.导图还不好拖动，指的是，画布不好拖动？还是测试点的节点不好拖动？
2.点中某个元素又很容易出发子UI弹出，指的是节点下的浮窗，还是右侧的配置页面？

**Comment by henbell2** [comment]
导图一般使用习惯画布就可以拖，但是此处设计默认根节点才可以拖。
点一个子节点，一下子弹出N多控件，UI布局也比较乱，感觉哪哪都能操作，但又处处都是干扰。
比如右侧视图hide，要点一个小小的设置ICON才能隐藏。
总之个人感觉UI也好、操作布局也好、workflow也好，都比较凌乱，供参考！
![image](https://github.com/user-attachments/assets/7301ad61-5b7a-4883-a1cb-6b02c4b8b5e2)

**Comment by henbell2** [comment]
看这个界面设计：上下左右区域、各个节点/子节点区域、以及节点弹出的功能bar、右侧小弹框，哪哪都能操作，UI还有相互叠加，个人感觉，所以会觉得一个字形容的话，“乱”
![image](https://github.com/user-attachments/assets/208bd365-281a-4936-8dae-242eaa7f96d3)

**Comment by Hyyfit** [comment]
非常抱歉给您带来了不好的使用体验。

我们会在后续的版本优化测试规划的操作
1.测试点的子节点：用例数、环境、资源池，可以直接在节点上更新，减少右侧抽屉的弹出。
2.右侧抽屉目前是点击测试节点就自动弹出了，会优化成需要主动点击节点下的【设置】才弹出；
3.当操作脑图时，收起测试计划的概览信息，增大脑图的可视范围，以此避免右上角的三个固定按钮遮挡脑图信息。
再次感谢您的反馈～！
