### ISSUE TITLE
[BUG]接口插件步骤导入场景后字段应该按 apiDefinitionFields的字段显示

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#32806]
### 联系方式

shenkaibo

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/3116a847-4e9d-42a6-bbd1-30e634a1c394)
目前环境里的参数在接口步骤里展示了，但是没有回显值，应该按照  apiDefinitionFields的字段显示

### 重现步骤

接口插件步骤导入场景后字段应该按 apiDefinitionFields 的字段显示

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
