### ISSUE TITLE
[BUG]接口自动化测试时，每次跑到一半就会报错。而单独执行接口没有问题。

### ISSUE THREAD

**Issue by fanglx** [metersphere/metersphere#32812]
### 联系方式

metersphere交流群62，宅，kenan2002flx@qq.com

### MeterSphere 版本

v2.10.1-lts-65fad062、 v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

接口自动化场景，里面加入近20个接口，
每个接口都做了前置脚本，脚本内容主要是一些参数赋值。
赋值后，我使用公共前置脚本对参数进行了组装和加密、签名。
接口单独执行都没有问题，可以通过。
但是只要是执行接口自动化场景，每次到第14、15个以后，后面的接口就跑不动了。
现象就是：
![1](https://github.com/user-attachments/assets/b6474345-8092-4b2a-8a5c-f67371f13d43)
看后台日志提示：
![2](https://github.com/user-attachments/assets/918d0e24-c401-44cf-8266-3a2c8b190069)

在交流群里请教后，获知可能是由于版本的问题导致。这个错误的版本是v2.10.1-lts-65fad062。

### 重现步骤

于是，去换到了另一个版本v2.10.17-lts-53992bfb
结果同样的操作，现象基本差不多，也是跑着跑着就跑不动了。
![3](https://github.com/user-attachments/assets/e290d004-06ed-4e9d-a04c-d49faffe7f44)

看后台日志提示：
![4](https://github.com/user-attachments/assets/66241fc7-ec69-41fa-af09-55f7c3d7a5ad)

最终还是提个bug，请各位开发大佬给看看吧。

**Comment by youliyuan-fit2cloud** [comment]
你好，请先检查一下这几个失败的接口请求内容信息是否正确，日志信息也不全，没有看到错误信息。

**Comment by fanglx** [comment]
此问题已解决，是我这边脚本的处理问题，导致请求的内容过大。
现已处理，关闭即可。
