### ISSUE TITLE
[BUG]自定义插件，在场景选择环境引用的情况下，仍然会显示环境配置

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#32817]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.2.0-ee

### 使用外置数据库

否

### 问题描述

1. 使用自定义插件，在接口场景中设置只展示环境设置中的部分字段，并选择环境引用，保存场景 
2. 从场景列表，进入场景，打开上述插件的自定义请求，页面 显示“环境引用”，仍然展示空的环境字段

### 重现步骤

1. 使用自定义插件，在接口场景中设置只展示环境设置中的部分字段，并选择环境引用，保存场景 
2. 从场景列表，进入场景，打开上述插件的自定义请求，页面 显示“环境引用”，仍然展示空的环境字段
![image](https://github.com/user-attachments/assets/0c568a3d-2de0-430d-a54d-63f6e7ed76d0)
![image](https://github.com/user-attachments/assets/d155382d-61ac-43e5-8a2d-54d1f171533b)

### 期待的正确结果

步骤二，从场景列表，进入场景，打开上述插件的自定义请求，页面 显示“环境引用”，不展示环境字段

**Comment by youliyuan-fit2cloud** [comment]
你好，请将插件发出来方便我们验证问题。

**Comment by fit2cloud-lijiaxin** [comment]
企业版插件，已发

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
