### ISSUE TITLE
metersphere V3在页面执行脚本一直在loading，查看task-runner/info.log又没有打印报错，应该怎么处理

### ISSUE THREAD

**Issue by qiuxue-boop** [metersphere/metersphere#32813]
### 请描述您的问题

我的metersphere版本是这个 v3.1.0-a8910b83 。本地机器部署的社区版。
![image](https://github.com/user-attachments/assets/18bf6c7a-0453-41a9-b6c6-41086c07adc2)
我在项目管理-公共脚本模块，点【测试】脚本，页面一直在loading，查看/opt/metersphere/logs/task-runner/info.log 不知道为什么没跟其他脚本一样执行到“清理执行器”。task-runner/info.log日志附上
![image](https://github.com/user-attachments/assets/f5dd1934-be1f-4b2d-b103-eaba70ce2b64)
[task_runner_info.log](https://github.com/user-attachments/files/16725305/task_runner_info.log)

**Comment by youliyuan-fit2cloud** [comment]
你好，这是bug下个版本修复，建议先使用其他的脚本语言。

**Comment by qiuxue-boop** [comment]
好的谢谢

**Comment by liuruibin** [comment]
<img width="915" alt="image" src="https://github.com/user-attachments/assets/d8d251a2-00d6-411a-824e-4e367cec6274">
这些python的包本身就很大

我们初始的限制是1g，你可以自行修改
<img width="617" alt="image" src="https://github.com/user-attachments/assets/e39b9ff7-d9c2-41d4-8fca-17578476443e">

**Comment by qiuxue-boop** [comment]
好的，按你建议修改了，我再观察一段时间看看是否还有出现。谢谢
