### ISSUE TITLE
[BUG]环境的前置里引入了全局脚本，全局脚本变更后，环境里的未变更

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#32810]
### MeterSphere 版本

V3.2.0

### 使用外置数据库

否

### 问题描述

环境的前置里引入了全局脚本，全局脚本变更后，环境里的未变更

### 重现步骤

环境的前置里引入了全局脚本，全局脚本变更后，环境里的未变更

### 附加信息

<img width="1048" alt="a791a9c2f609443bc1155459e127647" src="https://github.com/user-attachments/assets/99ae0230-d9ac-45bc-8da2-2301b1ecc99a">

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
