### ISSUE TITLE
[QUESTION] 是否可以在报告部分加快捷提交缺陷按钮

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32828]
### 请描述您的问题

目前我使用的是v2.10.17-lts版本

在使用过程中，我发现如果在查看报告时发现某个用例检出了缺陷，需要复制该用例信息去新建缺陷，所以我尝试在用例处展示提缺陷按钮，可以自动将请求信息填入缺陷单的描述字段，简单效果如下：
![image](https://github.com/user-attachments/assets/5064e0c4-4c5e-4451-9ae6-628e7f85cfd3)

查看代码发现，测试计划的场景用例展示部分是通过qiankun跳转到了api前端服务上，故我只能模仿源码在在track服务上将IssueEditDetail组件封装成micro-app组件，后发现可以点击时貌似只能展示，但是组件的表单的选项什么的都无法进行选择，并且原本的关联用例功能什么的都不能正常执行，并且console报错
![image](https://github.com/user-attachments/assets/1b90b8eb-8e32-4dbf-a632-de45f3227f04)
![image](https://github.com/user-attachments/assets/a9894a67-284a-49e4-8c17-ab9330b481f6)

这是我封装的micro组件
![image](https://github.com/user-attachments/assets/b2f1a593-eb47-43d8-8ef0-49fc39ddeb2b)

对RequestResultTail.vue的修改
![image](https://github.com/user-attachments/assets/433fa448-b5d5-4c76-8b36-b46af0232852)

![image](https://github.com/user-attachments/assets/26a83f34-3fb8-4839-854c-33a976aa2586)

通过qiankun调用track的缺陷编辑组件
![image](https://github.com/user-attachments/assets/c6b9f201-d866-49eb-9e16-53870be169f6)

我感觉我这种实现方式有点将api和track前端组件耦合起来了，而且来回跳有点呆，并且浮窗的关闭不能直接通过ref调用，我想了一种其他方案：就是将·api展示场景这部分组件复制一份到track里，这样不走qiankun转发就可以完全在track里实现，但是这样改动有些大，组件太多了，想问下是否有更好的解决方案

以下是我目前

**Comment by ijwstl** [comment]
关联用例等问题是浮窗嵌套显示层级的问题，目前就是表单组件比如select等不能正常显示选项的问题了

**Comment by luty2018** [comment]
首先给您点赞！
我们在v3.3也确实规划了这个功能。是否考虑升级到v3
![image](https://github.com/user-attachments/assets/5907951a-63ea-4f61-a0d6-1ca941f6e056)

**Comment by ijwstl** [comment]
> 首先给您点赞！ 我们在v3.3也确实规划了这个功能。是否考虑升级到v3 ![image](https://private-user-images.githubusercontent.com/36292514/361382776-5907951a-63ea-4f61-a0d6-1ca941f6e056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzcxMjIsIm5iZiI6MTcyNDc3NjgyMiwicGF0aCI6Ii8zNjI5MjUxNC8zNjEzODI3NzYtNTkwNzk1MWEtNjNlYS00ZjYxLWEwZDYtMWNhOTQxZjZlMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE2NDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjUzYzQ5NWM4OWI5N2VmMzU1YTg0NTg2ZjZlNzU0MTE1ODdhZjc0OTZhZTA5ZmM4NTdkY2NjMzU0M2Y1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_qK3eKQiZlH-WALapsKnbjPzrF3ajR_0TJd_G93a-Y)

嗯嗯，经过一天的摸索，我已经实现了之前想要的效果，就是多层浮窗嵌套导致的z-index重叠问题有点麻烦。目前由于v3不支持直接升级，所以想在观望一下
