### ISSUE TITLE
[BUG]绑定禅道成功，同步缺陷的时候，要么一直“同步缺陷”不返回，要么同步成功之后缺陷列表空白，啥也没有

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32830]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.2.0-d6ba97e1

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/d7df02d5-fbf3-46f5-aaa6-016045eb5122)
绑定禅道成功，同步缺陷的时候，要么一直“同步缺陷”不返回，要么同步成功之后缺陷列表空白，啥也没有

### 重现步骤

1、绑定禅道，检测绑定成功
2、同步缺陷

### 期待的正确结果

正常同步缺陷

**Comment by youliyuan-fit2cloud** [comment]
你好，同步缺陷配置的是增量同步还是全量同步？
全量同步是可以双向同步缺陷，增量同步只同步MS系统创建的缺陷。

**Comment by henbell2** [comment]
问题发生时所选择的配置：
![image](https://github.com/user-attachments/assets/03d856c1-aefa-4a6a-b54c-d1fd801b72da)

![image](https://github.com/user-attachments/assets/018514b3-db6c-413b-a3a5-b23561b6053c)

**Comment by henbell2** [comment]
反正成功，或者不成功，啥也没有，没有缺陷列表，也没有报error
这个功能应该是改坏了，v3.1是可用的

**Comment by youliyuan-fit2cloud** [comment]
我的意思是 你应该选 全量同步，再试试吧。
![image](https://github.com/user-attachments/assets/43776a00-ff71-497b-9d5c-39edb351e716)

**Comment by henbell2** [comment]
![image](https://github.com/user-attachments/assets/b99968ae-d1d3-4b88-a498-b7206a0852e2)

**Comment by henbell2** [comment]
参考这个：
https://github.com/metersphere/metersphere/issues/32803
感觉是个必现问题，近期改出来的

**Comment by song-cc-rock** [comment]
> 参考这个： #32803 感觉是个必现问题，近期改出来的

这是两个问题, #32803 这个是前端展示问题

**Comment by song-cc-rock** [comment]
> 反正成功，或者不成功，啥也没有，没有缺陷列表，也没有报error 这个功能应该是改坏了，v3.1是可用的

有同步时的后台日志吗, 或者看看禅道 产品/项目ID下 是不是挂有缺陷

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
