### ISSUE TITLE
[BUG] 调用接口mock，返回的响应内容不是mock里面定义的响应内容，而是接口定义里面定义的响应内容。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#32832]
### MeterSphere 版本

V2.10.17

### 使用外置数据库

否

### 问题描述

调用接口mock，返回的响应内容不是mock里面定义的响应内容，而是接口定义里面定义的响应内容。

https://github.com/user-attachments/assets/1b53fe87-4f6d-477c-9175-f4dabf96ab1e

### 重现步骤

同上

### 期待的正确结果

应该是mock里面定义的内容

**Comment by youliyuan-fit2cloud** [comment]
最新v2.10.19-lts没有复现，升级一下？

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
