### ISSUE TITLE
[QUESTION]配置禅道

### ISSUE THREAD

**Issue by zz80900** [metersphere/metersphere#32837]
### 请描述您的问题

![image](https://github.com/user-attachments/assets/578a95ae-8be9-498f-b1e5-e89cd39f18c9)

**Comment by song-cc-rock** [comment]
感觉是这个获取Token的认证接口, NotFound, 你抓取这里看看, 又或者确认看看你的禅道版本, 禅道16.x以后才支持上述的Rest-API
, 插件这边下版本优化一下HttpClientErrorException的报错处理提示逻辑

![image](https://github.com/user-attachments/assets/1fce111d-3735-4141-8ee9-71565dcb6207)
