### ISSUE TITLE
[BUG]接口测试后置格式检验时，勾选包含，但响应中没有对应字段时，断言仍然是成功

### ISSUE THREAD

**Issue by found1025** [metersphere/metersphere#32840]
### 联系方式

found1025@163.com

### MeterSphere 版本

 v2.10.12-lts-a7d7c194

### 使用外置数据库

否

### 问题描述

接口测试后置格式检验时，勾选包含，但响应中没有对应字段时，断言仍然是成功

### 重现步骤

勾选了必含，响应中没有该字段时，断言应该失败

### 期待的正确结果

勾选了必含，响应中没有该字段时，断言应该失败

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本中没有复现该问题，建议升级一下，或者把复现场景发出来，或截图看一下 。

**Comment by found1025** [comment]
升级到2.10.19也存在该问题。


断言检查包含aabbcc， 响应不存在该字段
![image](https://github.com/user-attachments/assets/f889f330-a04d-44c5-9470-5652905a14e8)
但断言成功
![image](https://github.com/user-attachments/assets/0377f318-6d58-41a5-bca2-ce480d7cb6a5)

**Comment by youliyuan-fit2cloud** [comment]
你好，
![image](https://github.com/user-attachments/assets/fd5c3b08-57f5-47b7-b877-966da0da3a91)
参考上图添加个参数名，你这个场景我们尝试优化一下。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
