### ISSUE TITLE
[QUESTION]接口自动化的场景中包含多个接口步骤，如何批量将这些步骤移动到最外层啊？

### ISSUE THREAD

**Issue by damonWongTest** [metersphere/metersphere#32844]
### 请描述您的问题

版本:   v2.10.14-lts-a7298117

接口自动化的场景中包含多个接口步骤，如何批量将这些步骤移动到最外层啊？
![image](https://github.com/user-attachments/assets/98e9f571-85fb-4a7b-afe6-e6c83ad3e164)

**Comment by luty2018** [comment]
不好意思，现在确实没有这个功能。

**Comment by damonWongTest** [comment]
好的，谢谢啦
