### ISSUE TITLE
[FEATURE]建议脑图模式的用例文字可以局部上色，同时支持导入的Xmind文件的颜色也带入

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#32859]
### MeterSphere 版本

v2.10..18-lts

### 联系方式

蒋林峰

### 请描述您的需求或者改进建议

建议脑图模式的用例文字可以局部上色，同时支持导入的Xmind文件的颜色也带入，因为这个可以标记关键字，有时候更有利于执行测试用例。
该用户深度使用功能用例和测试计划功能，习惯于使用脑图模式编辑用例，因为效率更高，并且引入了jira代理商开发jira插件对接MS的测试计划和用例，提出此需求也是基于长时间使用MS功能用例脑图模式总结出的经验，希望考虑下。
<img width="686" alt="企业微信截图_17248392876137" src="https://github.com/user-attachments/assets/f9e763bf-2ece-435e-8f6a-827999f54f07">

**Comment by luty2018** [comment]
好的， 我们调研一下
