### ISSUE TITLE
[BUG] V3.2.0安装后，服务状态正常，菜单栏从其他功能切换至测试用例或缺陷管理，右侧功能页面异常仍停留在上一功能页面

### ISSUE THREAD

**Issue by Char-WangXu** [metersphere/metersphere#32851]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

V3.2.0安装后，服务状态正常，菜单栏从其他功能切换至测试用例或缺陷管理，右侧功能页面异常仍停留在上一功能页面
服务状态：
![image](https://github.com/user-attachments/assets/8a14aa8c-d468-4545-931f-9aebc2bad090)

### 重现步骤

1. 从“测试计划”菜单切换至”测试用例“菜单，右侧功能页面异常仍停留在”测试用例“功能页面，刷新后页面返回到”测试用例“功能页面
![image](https://github.com/user-attachments/assets/d65140af-c6ae-491d-ae27-578769ccf5dc)

2. 其他菜单切到“缺陷管理”，现象相同
切换菜单时，F12发现前端有如下两个报错
![image](https://github.com/user-attachments/assets/9bc3d5af-8dc4-4e57-8b0d-9a6ad39ad95a)

**Comment by liuruibin** [comment]
升级个浏览器，以前有过类似的issue

**Comment by Char-WangXu** [comment]
> 升级个浏览器，以前有过类似的issue

确实是浏览器版本问题，升级后已解决，谢谢
