### ISSUE TITLE
[FEATURE]筛选器的“确认”应该放在侧面或者上面，现在都是被盖住的

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#32858]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.2.0-d6ba97e1

### 使用外置数据库

否

### 问题描述

[BUG]筛选器的“确认”应该放在侧面或者上面，现在都是被盖住的

### 重现步骤

[BUG]筛选器的“确认”应该放在侧面或者上面，现在都是被盖住的

**Comment by henbell2** [comment]
![image](https://github.com/user-attachments/assets/697476e1-4e44-4cca-b1bd-53e6a0863644)

**Comment by Hyyfit** [comment]
感谢反馈，优化已规划 v3.4
