### ISSUE TITLE
[BUG] idea upload接口成功，ms上未找到接口

### ISSUE THREAD

**Issue by ye0061** [metersphere/metersphere#32853]
### MeterSphere 版本

V3.2

### 使用外置数据库

否

### 问题描述

idea这边已经显示接口upload成功了，平台这边没有找到这个接口

### 重现步骤

idea这边已经显示接口upload成功了，平台这边没有找到这个接口

**Comment by fit2-zhao** [comment]
并未复现，打开 idea.log 查看一下是否有错误信息。

**Comment by ye0061** [comment]
![1724840010445](https://github.com/user-attachments/assets/e63138a4-b613-41fc-b961-6c10af3ad697)
idea上还是显示upload成功，但是ms上找不到接口，日志帮忙看看

**Comment by fit2-zhao** [comment]
这个错误信息是这个 https://github.com/metersphere/metersphere/issues/32845 问题，应该和上传没关系；如果方便可以把点 Upload 后的完整日志发出来我看下。

**Comment by fit2-zhao** [comment]
![image](https://github.com/user-attachments/assets/24748e71-4aab-4656-bc52-9972bf2aa610)

IDEA 页面是否有这种错误提示框。

**Comment by ye0061** [comment]
单个接口upload的话，是显示success。
![image](https://github.com/user-attachments/assets/ef18f5f9-b570-4357-a5f8-7163531d5cd3)
如果批量upload的话有这个报错。
![image](https://github.com/user-attachments/assets/32a1b963-440a-45a4-b8a3-e2f395ea80a7)
![00e531b9fa0aa3df8379fd37b342b5a](https://github.com/user-attachments/assets/79335412-784f-4790-b21d-961337291bd3)

**Comment by fit2-zhao** [comment]
能否提供一份完整的 idea.log

**Comment by ye0061** [comment]
[idea.log](https://github.com/user-attachments/files/16790964/idea.log)

**Comment by fit2-zhao** [comment]
从日志来看像是 和 MeterSphere 平台连接不通，检查一下配置是否正确。

**Comment by fit2-zhao** [comment]
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

还有一种可能性，你批量时接口过多超过了服务端请求参数的大小限制，可以尝试更改这两个参数。

**Comment by fit2-zhao** [comment]
https://plugins.jetbrains.com/plugin/24867-metersphere-api-debugger/edit/versions/stable/600994
https://github.com/metersphere/metersphere-idea-plugin/releases/tag/v3.2.0
@ye0061  可以下载这个版本试试是否解决了你的问题。
