### ISSUE TITLE
[BUG]自定义HTTP请求，DELETE类型时，会自带https:/的URL参数，导致URL地址拼接有误

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#32855]
### MeterSphere 版本

V2.10.17lts

### 使用外置数据库

否

### 问题描述

接口自动化中添加自定义请求，选择delete类型，进行调试，发现url请求地址有误

### 重现步骤

见问题描述

### 附加信息

![image](https://github.com/user-attachments/assets/854df90c-a598-4720-a250-8f0c53ee5d83)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
