### ISSUE TITLE
[BUG] 禅道同步到ms上的bug会重复同步

### ISSUE THREAD

**Issue by ye0061** [metersphere/metersphere#32857]
### MeterSphere 版本

V3.2

### 使用外置数据库

否

### 问题描述

禅道同步到ms上的bug会重复同步

### 重现步骤

1.选择全量同步
2.手动同步
![微信截图_20240828173731](https://github.com/user-attachments/assets/4223857c-1398-4430-bdac-97be2a5fa5e7)
缺陷

**Comment by youliyuan-fit2cloud** [comment]
你好， 没有复现你这个问题，建议在zentao中检查缺陷列表信息，确认是否是重复的。如果确认是重复的，请将zentao截图信息，同步缺陷时日志信息发一下方便我们排查问题。

**Comment by ye0061** [comment]
还是显示上传成功，ms上没法找到接口
![1724840010445](https://github.com/user-attachments/assets/1fab312a-1f8f-4c69-8796-97b8b085723d)

**Comment by ye0061** [comment]
![image](https://github.com/user-attachments/assets/82fce9aa-d1c2-457e-a6cd-e6b7605d72ab)
确认是有部分重复，我这边试了2个项目，固定重复的数量为200个。也就是说同步过来的bug数比禅道上的多200个。
同步的日志信息需要在哪里查看？

**Comment by ye0061** [comment]
![image](https://github.com/user-attachments/assets/a0f9eb38-8143-4e3a-9b52-1fcd2a38a35d)
![image](https://github.com/user-attachments/assets/42d5953e-db59-4172-ac4e-e75e505944aa)
确认是重复的。并且只会重复200个，也就是说，同步到ms上的 bug比禅道上固定多200个，我试了2个项目都这样。
还发现一个问题，ms做一次手动全量同步以后，再手动全量同步，无法实现缺陷同步。
缺陷日志需要在哪里查看？

**Comment by ye0061** [comment]
{
    "code": 100200,
    "message": null,
    "messageDetail": null,
    "data": {
        "complete": false,
        "msg": ""
    }
}

同步缺陷请求接口报文

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们尝试下同步超过200条的缺陷情况，有结果会再回复。

**Comment by youliyuan-fit2cloud** [comment]
已复现该问题，下个版本修复。

**Comment by ye0061** [comment]
好的谢谢

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级并重新上传新的禅道插件，感谢支持。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级并重新上传新的禅道插件，感谢支持。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级并重新上传新的禅道插件，感谢支持。
