### ISSUE TITLE
[BUG]V3.2.0 测试计划执行的时候通过率不变一直到超过第一次的通过率才会变化

### ISSUE THREAD

**Issue by ly761645472** [metersphere/metersphere#32852]
### MeterSphere 版本

V3.2.0

### 使用外置数据库

是

### 问题描述

测试计划执行的时候通过率不变一直到超过第一次的通过率才会变化

### 重现步骤

1.确保计划通过率能够不一样
2.正常执行测试计划

**Comment by youliyuan-fit2cloud** [comment]
你好，没有理解你说的这个场景，请详细描述一下复现步骤，方便的话把具体配置截图贴一下吧。

**Comment by xueqidove** [comment]
> 你好，没有理解你说的这个场景，请详细描述一下复现步骤，方便的话把具体配置截图贴一下吧。

在测试计划列表中会展示测试计划的通过率，如下图所示，当第一次执行该测试计划时，测试计划通过率为60%，进度条会调整到60%，第二次再次执行当前测试计划，如果通过率不足60%，在截图中通过率进度条不更新，如果通过率超过60%，该通过率进度条才会更新。
我们预期的是无论通过率是否超过第一次执行的通过率，通过率应该都更新。
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/4569ae15-eb15-42d5-872e-8a4617af9f05">

**Comment by youliyuan-fit2cloud** [comment]
按照你这个描述没有复现问题，测试计划中有关联功能用例，接口用例和场景用例。第一次执行通过率时75% ，第二次执行通过率时50%，测试计划列表的通过率有正确更新。

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/be2a163c-5a16-4d95-8ce8-da63a0c6517b)

![image](https://github.com/user-attachments/assets/668a59dc-2cac-4379-8269-25d7d645a262)

请看下 测试计划-报告的结果通过率是否一致。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
