### ISSUE TITLE
[BUG]升级新版本后，登录的提示语变成英文了

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32867]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

升级新版本后，登录的提示语变成英文了

### 重现步骤

登录MeterSphere，发现一些提示语是英文，登录后页面其实是中文的

### 期待的正确结果

登录的提示语显示正确

### 相关日志输出

```shell
无
```

### 附加信息

<img width="735" alt="企业微信截图_17249001594537" src="https://github.com/user-attachments/assets/785a17d8-3d61-4f39-8d52-ab61a9ed4aa9">
<img width="924" alt="企业微信截图_17249001869286" src="https://github.com/user-attachments/assets/4b9218d4-0480-4594-ab2a-a99c13cb8af9">

**Comment by fit2-zhao** [comment]
感谢反馈，会在下版本优化处理。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
