### ISSUE TITLE
[BUG]【接口测试】公共脚本处设置环境参数，在用例前置里引用报错。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32861]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【接口测试】公共脚本处设置环境参数，在用例前置里引用报错。

### 重现步骤

【接口测试】公共脚本处设置环境参数，在用例前置里引用报错。
1. 在 项目管理-公共脚本处，点击"设置环境参数"，设置环境变量aa值为123456
![image](https://github.com/user-attachments/assets/ee93c3f4-82dd-4425-8439-d2da8e4a4ca7)
在接口测试-用例处，前置脚本处引用 公共脚本，进行测试，控制台打印报错。
![image](https://github.com/user-attachments/assets/d58e1f17-be6f-423c-b356-fbe69010e6c9)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
