### ISSUE TITLE
[BUG]接口测试>>API导入：swagger3.0版本json在MS V3版本导入时提示格式异常，但是此JSON文件在MS V2版本能正常导入

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#32865]
### 联系方式

lisa.huang@fit2cloud.com

### MeterSphere 版本

V3.2

### 使用外置数据库

否

### 问题描述

[BUG]接口测试>>API导入：swagger3.0版本json在MS V3版本导入时提示格式异常，但是此JSON文件在MS V2版本能正常导入。具体json文件查看附件

### 重现步骤

[BUG]接口测试>>API导入：swagger3.0版本json在MS V3版本导入时提示格式异常，但是此JSON文件在MS V2版本能正常导入。具体json文件查看附件

### 附加信息

[api-def.json](https://github.com/user-attachments/files/16791043/api-def.json)

**Comment by luty2018** [comment]
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/e5cc119c-330a-43fa-b718-a775c0abca76">
我试了一下， 用这个文件可以正常导入哦

**Comment by huangxine** [comment]
MeterSphere V3.2版本，客户下载源码debug了，发现我们的导入，校验了tag（tag根据发音拼写的有可能不对）不能为空，但是这个文件里没有这个字段，所以不能导入。

**Comment by youliyuan-fit2cloud** [comment]
> MeterSphere V3.2版本，客户下载源码debug了，发现我们的导入，校验了tag（tag根据发育拼写的有可能不对）不能为空，但是这个文件里没有这个字段，所以不能导入。

下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v3.3版本中已修复。
