### ISSUE TITLE
[BUG]metersphere V3，接口测试-调试-导入请求，从浏览器F12 copy了CURL[bash]，导入后请求体内容没解析到

### ISSUE THREAD

**Issue by qiuxue-boop** [metersphere/metersphere#32864]
### 联系方式

1342730319@qq.com

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

CURL[bash]导入到系统里，请求体内容没解析到

### 重现步骤

在Chrome F12，选中接口，右键选择copy - copy as curl(bash)，然后导入到MS系统中，发现没有解析到请求体
![image](https://github.com/user-attachments/assets/05d1278b-c433-4cec-a20b-a5f595687d46)
![image](https://github.com/user-attachments/assets/8752033b-f208-4cec-98e7-9b5146499582)

CURL如下：
curl 'http://xx:xx/test/tst1/orderAction/tes' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: _ati=4621860983598; saas_oms_session=hhh%3D' \
  -H 'Origin: http://xx:xx' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://xx:xx/order/eCommerceBus/b2cOrder' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'token: xx.yy.hh' \
  --data-raw 'channel_type=1&channel_id=84&action_type=1&tid=44444' \
  --insecure

**Comment by fit2-zhao** [comment]
感谢反馈，第一版本支持的比较单一我们会在 3.3 版本进行丰富。

**Comment by youliyuan-fit2cloud** [comment]
v3.3版本中已修复。
