### ISSUE TITLE
[BUG]【测试计划】测试计划关联功能用例，在执行过程中，实际结果处，当填写大json串时(文件大小大概180KB)，页面提示“Internal exception occured, please check logs or contactadministrator”

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32868]
### MeterSphere 版本

v2.10.15-lts

### 使用外置数据库

否

### 问题描述

【测试计划】测试计划关联功能用例，在执行过程中，实际结果处，当填写大json串时(文件大小大概180KB)，页面提示“Internal exception occured, please check logs or contactadministrator”

### 重现步骤

【测试计划】测试计划关联功能用例，在执行过程中，实际结果处，当填写大json串时(文件大小大概180KB)，页面提示“Internal exception occured, please check logs or contactadministrator”

![image](https://github.com/user-attachments/assets/7f542e0d-7937-46b4-8ecc-d74a9ef904bd)

![image](https://github.com/user-attachments/assets/af6ce669-62ed-4336-9983-ab7daadde559)

**Comment by 13290445582** [comment]
感谢反馈，问题已提交，后续版本修复。

**Comment by 13290445582** [comment]
你好，目前该字段在数据库的存储类型为 TEXT，具体长度限制可以参考下图。
![image](https://github.com/user-attachments/assets/13c466ee-9804-4350-868c-53690b059510)
当前的 TEXT 类型应该满足大部分的使用场景，如果更改类型的话，数据库大字段的表结构修改，需要处理历史数据，非常耗时，故产品层面，不做修改；
如果确实有大文本的需求，建议可以作为附件上传，或者手动执行下一下 SQL 修改下字段类型。
-- 修改测试计划实际结果字段
ALTER TABLE test_plan_test_case MODIFY COLUMN actual_result longtext;
-- 修改评论内容字段
ALTER TABLE test_case_comment MODIFY COLUMN description longtext;
