### ISSUE TITLE
[BUG]UI自动化-场景步骤参数传递无法通过${}取值

### ISSUE THREAD

**Issue by wzxdeveloper** [metersphere/metersphere#32871]
### 联系方式

63群 昵称：好久不见

### MeterSphere 版本

v2.10.19-lts-e2eb0a0c

### 使用外置数据库

否

### 问题描述

后置脚本设置变量有返回值无法在下一个场景步骤输入内容中通过${}方式获取

### 重现步骤

![20240829-131249](https://github.com/user-attachments/assets/f23966bc-db1a-4c8d-81f5-17699473abbf)
![20240829-131255](https://github.com/user-attachments/assets/2bf3f182-1767-48d9-8f28-3972e9395387)
![20240829-131259](https://github.com/user-attachments/assets/dfe50d0f-1c33-4030-84ec-0b08d0b81c3c)
![20240829-131309](https://github.com/user-attachments/assets/10ca8947-aa98-4e33-bfdf-39ae67f3196a)

### 期待的正确结果

验证码值${s} 应该为设置的值true

**Comment by orient1100** [comment]
尽快解决哈 我也遇到这个问题了

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现。

**Comment by youliyuan-fit2cloud** [comment]
你好，经过开发同学确认上诉脚本中要去掉 window  ，因为当属性挂载到 window 上时，它会成为全局变量，可以在任何地方访问。window 是 JavaScript 中的全局对象，所有挂载到 window 上的变量都能在整个应用程序中访问。这种方式会污染全局命名空间，并且容易导致命名冲突，尤其是在大型项目中。所以请自行处理一下脚本，感谢理解和支持。
