### ISSUE TITLE
[BUG]__metersphere_env_id 设置全局变量，无法写入环境

### ISSUE THREAD

**Issue by cs6636563** [metersphere/metersphere#32880]
### 联系方式

cs6636563@outlook.com

### MeterSphere 版本

v2.10.19-lts-90463ffd

### 使用外置数据库

否

### 问题描述

<img width="1033" alt="截屏2024-08-29 19 58 20" src="https://github.com/user-attachments/assets/9b64334e-07eb-42db-bffe-761cb57a91b8">
<img width="562" alt="截屏2024-08-29 19 59 24" src="https://github.com/user-attachments/assets/a7acd885-3c05-428e-8549-561889ab6236">

### 重现步骤

之前的脚本都没有问题，升级到17后发现大量测试计划token没有写入全局变量，经过手动测试__metersphere_env_id无法生效，新建了一个项目可以写入，当前项目无法生效，当前项目1000多个场景，定时任务跑的全部是因为token没有写入全局变量导致的失败

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/143298d9-0430-4898-8536-7263c8962591)

你好，请参考上图的脚本，再尝试是否能复现。

**Comment by cs6636563** [comment]
不行～ 我其他的项目是可以的 这个就是最基本的语法～就场景最多的项目不行 用你这个也没有办法写入项目通用变量，
脚本代码。 vars.put(${__metersphere_env_id}+"字符串","字符串");
预期 项目通用变量有   字符串 =字符串
实际 项目通用变量  没有这个变量

**Comment by cs6636563** [comment]
除此之外 我用另外一个项目 是可以写入字符串=字符串的。十万火急 拜托拜托🙏

**Comment by youliyuan-fit2cloud** [comment]
vars.put(${__metersphere_env_id}+"字符串","字符串");--------->这里的后面的字符串 不应该是提取出来的变量名吗？ 如果是变量应该加上 ${字符串}吧，然后检查下变量提取是否成功。
如果只是 如上 字符串=字符串，后端日志看看？api-test 模块下的日志。

**Comment by youliyuan-fit2cloud** [comment]
还有一个可能，这个场景步骤是被引用的场景 吗？被引用的场景可以单独设置使用原场景环境的。
![image](https://github.com/user-attachments/assets/2fc4cd98-abda-4d53-ac3e-281c5d029ba6)

**Comment by cs6636563** [comment]
vars.put(${__metersphere_env_id}+"字符串","字符串");--------->这里的后面的字符串 不应该是提取出来的变量名吗？

我的意思就是我设置一个全局变量 比如a=1 那么应该写vars.put(${__metersphere_env_id}+"a","1") 然后脚本运行成功后我这边 项目环境变量里面没有a
如果有a 没有value (也就是1)  才是你这说的vars.put(${__metersphere_env_id}+"a","${a}") a的变量没有获取到
我这边看下日志 然后看看下面的可能。因为在这之前 都是可以更新a和a的值的

**Comment by youliyuan-fit2cloud** [comment]
很遗憾，所有情况都尝试了，历史数据执行场景用例，执行测试计划，执行测试计划时切换新环境都正确写入了。。。
建议再看看你的环境配置。

**Comment by LimonFHM** [comment]
看下这个：https://github.com/metersphere/metersphere/issues/32999

是不是跟我们一样情况，写到别的环境里去了。

**Comment by cs6636563** [comment]
@LimonFHM 非常感谢 是这样的问题

**Comment by 13290445582** [comment]
您好，该问题在v2.10.20版本已修复，请升级。
