### ISSUE TITLE
[QUESTION]api_load_test表数据来源疑问

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32887]
### 请描述您的问题

版本为v2.10.18-lts

发现存储性能测试引用关系的表api_load_test只有在接口测试中批量添加到性能测试的时候才会存储关系，而在性能测试引用场景自动化的时候就不会插入，导致整个数据表里的数据不全，并且当进行更新性能测试计划时走的是edit的url，里边也不会更新引用关系，这一条是否为逻辑处理遗漏呢？

**Comment by Somebody-JIAN** [comment]
远古代码，困难度你懂得

Be like:
![image](https://github.com/user-attachments/assets/0624da61-eb56-4d97-a3ee-99da25b927af)


  --------------------------------------

我们在V3重构了很多东西，不论是运行还是阅读，都会更加直观和简洁。

性能测试也在排期中。
