### ISSUE TITLE
[FEATURE]测试计划或者测试计划组执行过程中无法实时查看测试报告，须等到执行完成才可以查看执行结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32881]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

测试计划或者测试计划组执行过程中无法实时查看测试报告，须等到执行完成才可以查看执行结果

### 重现步骤

1、创建具有20个场景的串行执行的测试计划
2、点击执行并切换到报告页面，点击刚才执行的报告进行查看
3、观察页面数据

**Comment by 13290445582** [comment]
您好，需求已在V3.4实现，V3.4已发布，请升级。
