### ISSUE TITLE
[BUG]自定义webhook没有返回接收者信息

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#32888]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

客户配置单点登录后，通过自定义webhook 发送消息，需要通知到MS 指定的接收人，MS没有返回接收人信息

### 重现步骤

客户自定义webhook 发送消息，需要通知到MS 指定的接收人，MS没有返回接收人信息
![image](https://github.com/user-attachments/assets/b3e92712-a0e8-4f05-a0ee-aff1fddac48a)

### 期待的正确结果

客户自定义webhook 发送消息，希望收到接收人信息，方便通知到指定人员

**Comment by youliyuan-fit2cloud** [comment]
你好，单点登录是指哪一种？ 配置单点登录后，用户有登录过MS系统吗？这个 接收人 下拉列表是没有显示非local来源的用户吗？

**Comment by fit2cloud-lijiaxin** [comment]
使用oauth2单点登录，用户登录成功，设置了接收人，对方自定义webhook接口中 只接收到了 消息模版配置 的内容，没有接收人相关信息

**Comment by youliyuan-fit2cloud** [comment]
> 使用oauth2单点登录，用户登录成功，设置了接收人，对方自定义webhook接口中 只接收到了 消息模版配置 的内容，没有接收人相关信息
![image](https://github.com/user-attachments/assets/a0c7fbc9-5118-4d97-a8bd-a5a753f771fc)

意思是上面的消息通知没有 @接收人名字？ 
如果是，是因为飞书不支持...

**Comment by fit2cloud-lijiaxin** [comment]
客户集成了单点登录后，消息配置使用的是自定义webhook ，不是飞书，是客户自己研发的webhook, 希望达到的效果是，MS 调用webhook ，发送请求内容包含接收人的id ，对方去实现通知指定人员的功能，MS 这边只传了消息模版 没有传递id  username邮箱，手机号等接收人信息

**Comment by youliyuan-fit2cloud** [comment]
> 客户集成了单点登录后，消息配置使用的是自定义webhook ，不是飞书，是客户自己研发的webhook, 希望达到的效果是，MS 调用webhook ，发送请求内容包含接收人的id ，对方去实现通知指定人员的功能，MS 这边只传了消息模版 没有传递id username邮箱，手机号等接收人信息

暂不支持，感谢理解和支持。
