### ISSUE TITLE
[FEATURE]接口测试用例自动生成。

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#3289]
**请描述您的需求或者改进建议.**
作为接口测试人员，我希望 MeterSphere 支持接口根据接口参数，按照一定法则，自动生成测试用例，以最大程度减少工作量，提高工作效率

**请描述你建议的实现方案**
1、可参考微软的 PICT 工具的实现方式。

**Comment by seasoncool** [comment]
我们尝试过用脚本来实现 这个设想，苦于水平有限 没做出来。
主要卡在了 请求参数的获取和生成这块了。
要是真的能做出来，直接导入接口，生成出对应规则的接口用例，那就太棒了。

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中啦

**Comment by seasoncool** [comment]
@xulinde  这个功能要出来了，要逆天。。。。能节约大量的开发API脚本时间。。。感谢 感谢，多反馈下请愿啊。

**Comment by pencui** [comment]
这PICT和Api脚本有啥关系？PICT不是正交分解吗

**Comment by xulinde** [comment]
v1.13已支持自动生成测试数据，您可以升级体验下
