### ISSUE TITLE
[FEATURE]MS V3.2：编辑计划脑图时，右上角固定按钮非常碍事，并且遮挡脑图信息。请优化这三个固定按钮

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#32899]
### MeterSphere 版本

v3.2

### 请描述您的需求或者改进建议

[FEATURE]MS V3.2：编辑计划脑图时，右上角固定按钮非常碍事，并且遮挡脑图信息。请优化这三个固定按钮

### 附加信息

![image](https://github.com/user-attachments/assets/44f6f12c-dfe1-423e-b2fe-fe519e8682b3)

**Comment by henbell2** [comment]
同样的感觉https://github.com/metersphere/metersphere/issues/32802

**Comment by Hyyfit** [comment]
感谢反馈，优化已规划在 v3.4。
