### ISSUE TITLE
[FEATURE] 希望不局限于jmeter，能支持locust

### ISSUE THREAD

**Issue by FrancisJen** [metersphere/metersphere#329]
**请描述您的需求或者改进建议.**

locust的单机并发是jmeter的好几倍

**请描述你建议的实现方案**
希望可以增加对locust的支持

**Comment by fuzecheng** [comment]
原谅我无法理解觉得locust比jmeter性能要好

**Comment by wangzhen-fit2cloud** [comment]
你好，目前还是计划优先以增加功能支持为主，会考虑在 2.0 版本中进行重构，优化整体架构，支持不同的测试引擎

**Comment by del-zhenwu** [comment]
any update?

**Comment by liqiang-fit2cloud** [comment]
暂时没计划。
