### ISSUE TITLE
[BUG]测试报告免登陆，无法修改logo

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#32909]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

系统设置中自定义了logo后，测试计划执行完成后，分享报告后，免密登录时无法logo依然是默认的，不是自定义的logo
<img width="998" alt="截屏2024-09-02 下午4 43 19" src="https://github.com/user-attachments/assets/df0c62fc-bdb7-436b-a2e5-0c5d8d1bea22">

### 重现步骤

1.在系统设置，显示设置中，修改logo
2.准备一个可执行测试计划
3.执行测试计划完成后，进入测试计划报告中，点击“分享”生成报告链接
4.访问链接，可查看到浏览器上logo依然为默认的。

### 期待的正确结果

免密访问报告的页面的logo是自定义的

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
