### ISSUE TITLE
[BUG]接口测试-根据执行结果筛选 case 数据后，选择所有数据，会把所有case 都执行

### ISSUE THREAD

**Issue by meijieDouDou** [metersphere/metersphere#32905]
### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

接口测试-根据执行结果筛选 case 数据后，选择所有数据，会把所有case 都执行

### 重现步骤

某接口根据执行结果筛选 case，再选择所有数据，选择批量执行，实际执行的是所有状态的测试用例
![image](https://github.com/user-attachments/assets/5a8939cc-0ab8-4b1a-afc7-15ab5bea38a5)
![image](https://github.com/user-attachments/assets/670e35e6-052d-47c9-b71a-9c6feae9aa6e)
![image](https://github.com/user-attachments/assets/f30476e9-46c1-4424-8f43-2478bec0ad35)
![image](https://github.com/user-attachments/assets/50825a72-9c77-47ac-9f6e-589724d97088)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
