### ISSUE TITLE
[FEATURE]API/文档变更通知 

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#3290]
**请描述您的需求或者改进建议.**
1、作为研发人员，我希望当对API接口或对应的文档进行变更时，可以选择是否需要通知相关人员。
2、作为用例维编写人员，我希望可以第一时间收到用例变更的通知。

**请描述你建议的实现方案**
1、API变更时可以选择是否需要通知对应的角色人员或指定人员。
2、支持不同版本之间的对比。
3、可根据变更对所有用例进行全面扫描，并自动过滤受变更影响的关联用例，以针对性进行修改。

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by xulinde** [comment]
v1.13已支持
