### ISSUE TITLE
[BUG]测试计划报告中的单场景报告中的“报告总耗时”指标统计错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32918]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

测试计划报告中的单场景报告中的“报告总耗时”指标与实际该场景的执行总耗时指标不符

### 重现步骤

1、批量选择多个自动化场景加入到测试计划
2、并发执行该测试计划
3、执行后查看测试计划报告下的单场景测试报告，比对“报告总耗时”指标

### 附加信息

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/48af2c07-eb7a-4f13-bf92-b61ef90f8fd6">

**Comment by youliyuan-fit2cloud** [comment]
已确认是bug，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
