### ISSUE TITLE
[FEATURE] 脑图，用例 tab 快捷键添加步骤节点，期望定位再步骤描述

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#32919]
### MeterSphere 版本

3.2

### 请描述您的需求或者改进建议

脑图，用例 tab 快捷键添加步骤节点，期望定位再步骤描述

### 请描述你建议的实现方案

按照写用例习惯是写步骤再写预期
![快捷键添加步骤节点，期望定位再步骤描述](https://github.com/user-attachments/assets/f1e22e54-b8e2-4eaf-a25f-aa73ad8cdccf)

**Comment by Hyyfit** [comment]
感谢反馈，已规划3.4
