### ISSUE TITLE
[BUG]接口测试设计场景用例时，设置场景变量请求头优先级小于环境变量的请求头

### ISSUE THREAD

**Issue by wanhx829** [metersphere/metersphere#32922]
### 联系方式

wanhx1324@163.com

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

1、设置场景变量请求头：Sciyon-Auth：bearer e8bf583c-e029-47e3-89b4-b2d3fc76e71e
![image](https://github.com/user-attachments/assets/eb126a0b-a337-4cd5-88aa-87186cbe00d3)

2、设置环境变量的请求头：Sciyon-Auth：bearer 591755ac-f36c-40ee-9f42-aad3d7a607cb
![image](https://github.com/user-attachments/assets/ecb47da3-99ce-48f6-b17c-c528e2d1f263)

进行调试，查看请求头，为环境变量的请求头
![image](https://github.com/user-attachments/assets/cd8b25f4-4706-40f8-b974-5bd30e315a04)

### 重现步骤

见问题描述。
重命名（删除）环境变量的请求头，接口调试可以正常获取场景变量的请求头
![image](https://github.com/user-attachments/assets/adad2901-e084-45f1-ae00-78c99148041c)
![image](https://github.com/user-attachments/assets/890561bf-95e8-4898-949d-7891c5e230f3)

### 期待的正确结果

理论上，接口请求头优先级>场景变量请求头优先级>环境变量请求头优先级

### 附加信息

反观场景变量，是正常的
设置一个环境变量
![image](https://github.com/user-attachments/assets/9eedd248-e5b9-4652-a366-498214531617)
再设置同名的一个场景变量
![image](https://github.com/user-attachments/assets/bd58c07d-ca0c-4301-862d-66f6a858c0ba)
调试调用
![image](https://github.com/user-attachments/assets/fe9434eb-d18b-46b9-a89b-625b4e58741a)

结果发现场景变量优先级大于环境变量的优先级，是正常的

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化。

**Comment by youliyuan-fit2cloud** [comment]
你好，和开发确认，请求头的优先级是环境请求体>场景的，所以不是缺陷。
