### ISSUE TITLE
[BUG]管理台->组织->操作日志，提示SQL error happened, please check logs.

### ISSUE THREAD

**Issue by jancee** [metersphere/metersphere#3292]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.10.0

**Bug 描述**
进入管理台->组织->操作日志页面，提示SQL error happened, please check logs.

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12582402/119937324-2b3bde00-bfbd-11eb-9f32-56006e122692.png)

**Comment by zyyfit** [comment]
您好，1.10.0版本应该是没有这个菜单的，请问您是用什么方式部署的？是获取的1.10.0最新release版吗？

**Comment by jancee** [comment]
是升级上来的

**Comment by jancee** [comment]
![image](https://user-images.githubusercontent.com/12582402/120458239-b2c48b00-c3c9-11eb-99bb-88324adb1506.png)

**Comment by jancee** [comment]
![image](https://user-images.githubusercontent.com/12582402/120458318-c2dc6a80-c3c9-11eb-8a63-7337f8b93a11.png)
菜单是这样的

**Comment by xulinde** [comment]
v1.10.2版本已修复
