### ISSUE TITLE
[FEATURE] 脑图展开编辑用例，点击保存后缩回根节点了，不方便使用

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#32920]
### MeterSphere 版本

3。2

### 请描述您的需求或者改进建议

脑图展开编辑用例，点击保存后缩回根节点了，不方便使用

### 请描述你建议的实现方案

脑图展开编辑用例，点击保存后缩回根节点了，不方便使用

![脑图展开编辑用例，点击保存后缩回根节点了，不方便](https://github.com/user-attachments/assets/1e95bb61-369b-4360-9282-fe2ebd13f62d)

保存停留当前位置

**Comment by Hyyfit** [comment]
感谢反馈，已规划 v3.4

**Comment by 13290445582** [comment]
您好，需求已在V3.4实现，V3.4已发布，请升级。
