### ISSUE TITLE
[BUG] 修改Bug模板新增status的状态值reopen保存后原有的bug状态均被设置为新建同时过滤时显示为空

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#32927]
### MeterSphere 版本

v2.10.18-lts

### 使用外置数据库

否

### 问题描述

在项目管理的缺陷模板中，对‘状态’字段，新增下拉列表值保存后，现有的项目缺陷列表中，所有的Bug的状态均被设置为‘新建'。
同时问题2：
当在此基础上再创建缺陷后，过滤现有缺陷状态’新建'，只有新创建的缺陷返回，原有的缺陷不在过滤的列表中。
设置的字段如下图所示：
![image](https://github.com/user-attachments/assets/6d6d3262-270d-494a-86d8-ae21cba19364)

![image](https://github.com/user-attachments/assets/4964a095-e45e-4a10-81ab-c05c36b177da)

![image](https://github.com/user-attachments/assets/f764c9f7-2fe2-45b3-a93d-a800eac4f077)

### 重现步骤

如描述

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题已在最新版本v2.10.19-lts中修复，升级一下吧
