### ISSUE TITLE
[BUG] 超级管理员无法编辑测试计划中的用例

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#32931]
### MeterSphere 版本

v2.10.18-lts

### 使用外置数据库

否

### 问题描述

打开测试计划后，打开任一计划中的用例，提示无操作权限。
用户已经设置为系统管理员。

/track/test/plan/case/get/0af35749-8d21-4b2b-94af-23bf332bd812

{"success":false,"message":"当前用户没有操作此用例的权限","data":null}
![image](https://github.com/user-attachments/assets/15147765-6774-4496-8ad0-7c3500d070b7)
![image](https://github.com/user-attachments/assets/9d2c7e25-60a8-4ab0-a3bb-ea3c7e9c46ca)

### 重现步骤

见问题描述

**Comment by youliyuan-fit2cloud** [comment]
你好，测试环境暂时未复现，请看下当前用户在这个项目中的权限是什么？确认下当前项目的所属用户组是否有用例的权限

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现该问题，后续版本修复。可以把这个用户添加到项目中解决当前问题，

**Comment by alisam1189** [comment]
عزیزم تو عالی هستی .nice to met you bebe

**Comment by 13290445582** [comment]
您好，v2.10.22版本已修复此问题，请升级。
