### ISSUE TITLE
[BUG]用例的断言规则保存不下来

### ISSUE THREAD

**Issue by lufeifeiya** [metersphere/metersphere#3293]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.10
**Bug 描述**
简要描述您碰到的问题
从接口定义列表点击case进入用例编辑页面，添加断言，保存。再次打开发现断言规则没有保存下来

**Bug 重现步骤**
1.  从接口定义列表点击case进入用例编辑页面
2. 添加断言，保存
3. 再次打开用例页面

实际结果
只保留了断言规则名称，实际上断言规则没有保存

**期待的正确结果**
保留之前编辑的断言结果

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现呢，能描述一下具体操作步骤吗？

**Comment by lufeifeiya** [comment]
![image](https://user-images.githubusercontent.com/24427113/120132586-2bc2b780-c1fd-11eb-97bf-487ff794bf36.png)

**Comment by lufeifeiya** [comment]
![image](https://user-images.githubusercontent.com/24427113/120132672-5c0a5600-c1fd-11eb-959b-d0450f00b9dc.png)

**Comment by lufeifeiya** [comment]
无法重现了。。。
