### ISSUE TITLE
[BUG]测试计划报告总结中的代码块部分选择不了语言

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32934]
### 联系方式

14707070227

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

测试计划报告总结中的代码块部分选择不了语言

### 重现步骤

1. 打开测试计划报告，填写报告总结
2. 添加代码块内容，发现选择不了语言
![image](https://github.com/user-attachments/assets/320b0b12-2143-4d9a-9714-51641fe3e4b8)

### 期待的正确结果

测试计划报告总结中的代码块部分可以选择语言

### 相关日志输出

```shell
无
```

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。。。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
