### ISSUE TITLE
[BUG]V3.2版本导出excle格式的用例，导出是选择了所属模块，但是excle中所属模块内容为空

### ISSUE THREAD

**Issue by jialiangding** [metersphere/metersphere#32941]
### MeterSphere 版本

V3.2

### 使用外置数据库

否

### 问题描述

V3.2版本导出excle格式的用例，导出是选择了所属模块，但是excle中所属模块内容为空

### 重现步骤

V3.2版本导出excle格式的用例，导出是选择了所属模块，但是excle中所属模块内容为空

### 期待的正确结果

excle中所属模块内容导出结果正确

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，如果用例所属模块是多层子模块会出现该问题，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
