### ISSUE TITLE
[FEATURE]Jenkins插件缺少[运行环境][失败重跑]参数，希望能加上

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#32949]
### MeterSphere 版本

v2.10.19-lts-90463ffd

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/2352a962-ef24-4962-b183-a80e599d3001)

![image](https://github.com/user-attachments/assets/6234e496-6a86-4541-afde-5118d17c1141)

**Comment by liuruibin** [comment]
感谢使用我们的产品，我们暂时没有扩展jenkins插件的计划。尽管如此，您仍然可以重制插件来满足需求
https://github.com/metersphere/jenkins-plugin
