### ISSUE TITLE
[FEATURE]1个ip对应多个域名功能丢失

### ISSUE THREAD

**Issue by ZZCchuan** [metersphere/metersphere#32940]
### MeterSphere 版本

v3.2.0-89e02f6f

### 联系方式

MeterSphere 交流群31

### 请描述您的需求或者改进建议

**无法添加相同ip，提示重复，实际上v2.x版本是支持的，大部分群体也是比较依赖这个功能的**
![image](https://github.com/user-attachments/assets/43d06204-3bcf-4e0d-b9aa-f6a0990a20dc)

### 请描述你建议的实现方案

麻烦支持下添加相同ip的场景

**Comment by luty2018** [comment]
好的， 我们改一下， 会在月底的v3.3版本发布。

**Comment by ZZCchuan** [comment]
静等佳音
