### ISSUE TITLE
[BUG]【接口自动化】从一个项目导出场景后，导入另外一个项目，选择了不覆盖，但仍可以重复多次导入。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32948]
### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】从一个项目导出场景后，导入另外一个项目，选择了不覆盖，但仍可以重复多次导入。

### 重现步骤

【接口自动化】从一个项目导出场景后，导入另外一个项目，选择了不覆盖，但仍可以重复多次导入。
![image](https://github.com/user-attachments/assets/0970bcbf-3b95-4ed4-be97-1a760cef30f2)

![image](https://github.com/user-attachments/assets/f2cc417d-b6e7-465f-a257-357439eb1957)

**Comment by youliyuan-fit2cloud** [comment]
你好，不覆盖导入时不要选中模块再导入。
按照你这个操作，
1、你这个文件从项目中导出来的，肯定有模块名称；

2、选了模块会校验当前模块下是否存在该场景用例，不存在导入
3、再次导入-仍选中 未规划场景，校验 这个根模块是否有同名的场景，不存在导入。

所有你这个会导入多个，实际上是因为选中的模块下不存在同名场景，只是其子模块存在同名的。
