### ISSUE TITLE
[BUG]接口自动化任务通知报告地址不正确

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3294]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.3
**Bug 描述**
简要描述您碰到的问题
测试报告的地址url没有获取到本机ip地址，环境为docker安装
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/40912823/119940243-7eb02b00-bfc1-11eb-9c1e-bd63f4f092d6.png)

**Comment by xulinde** [comment]
这个需要在  系统设置-基本设置-当前站点URL，设置成部署metersphere服务的地址
