### ISSUE TITLE
[BUG] 开启测试计划失败重试，kafka回传卡住

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#32953]
### 联系方式

asiaw159753@outlook.com

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

我在测试计划中添加了一条场景用例，发现只要开启失败重试，那么该用例执行完毕会在回传kafka时卡住。

该用例调试时全部请求成功，按理说不会有失败，不开启失败重试，全部请求也都是成功的。

node-controller日志
开启失败重试：ms-log
![image](https://github.com/user-attachments/assets/578b1832-28be-45d1-8eb5-dbf60ea63f60)

执行log
![image](https://github.com/user-attachments/assets/9cb3a97d-7754-4982-8049-844d066aac7b)

api-test日志：
![image](https://github.com/user-attachments/assets/2076b76b-087a-4f53-bf87-07a47f91e5f8)

不开启失败重试：
![image](https://github.com/user-attachments/assets/2cf6a8cc-bc11-4fac-840c-10abd19f3d99)

不开启失败重试的执行记录
![image](https://github.com/user-attachments/assets/e48c316f-f656-412b-a1f2-5ef7e8be17f5)

### 重现步骤

脚本内容
如果是由于请求体base64过大的话，为什么调试和单独执行都可以成功呢

![image](https://github.com/user-attachments/assets/e32d4fdd-106c-4ca7-9763-846a32f6d74a)

我看了下base64消息体大概30MB+,如果是勾选失败重试，场景请求消息一起回传的话可能在50-60MB，远小于目前kafka的设置

### 附加信息

kafka配置
![image](https://github.com/user-attachments/assets/7b33a2fe-de18-424b-b0fc-f18e44336ca1)

**Comment by ijwstl** [comment]
今天早上又试了一下，貌似node节点貌似卡一会会将数据传入到kafka内，我目前不确认日志打印的回传完成是由于超时自动打印了日志还是真的回传到kafka了已经
日志如下
![image](https://github.com/user-attachments/assets/9b23e88e-01f5-4f95-ab66-e30a1faa3f1b)

然后我看了下kafka消费信息
报告没有消息阻塞
![image](https://github.com/user-attachments/assets/5fec64d1-da02-4421-95b1-65c30840af99)

![image](https://github.com/user-attachments/assets/fded6549-c3f4-43ea-af8a-38f0a72fc07b)


api日志，没有后续接收到报告的日志打印
![image](https://github.com/user-attachments/assets/2b323abd-b10e-4411-b187-55ef298b6bca)

**Comment by youliyuan-fit2cloud** [comment]
你好，看这个最新反馈是没有复现了是吧？我们测试环境没有复现，那先close issue 了，如果再出现随时联系我们，感谢理解和支持。

**Comment by ijwstl** [comment]
> 你好，看这个最新反馈是没有复现了是吧？我们测试环境没有复现，那先close issue 了，如果再出现随时联系我们，感谢理解和支持。

复现了的，虽然打印了发送kafka消息完成，但是kafka貌似没有收到找个消息，还是会有这个问题，请问您的返回kafka消息大小是多少，我昨天以为是默认的common.propertries里设置的spring.kafka.consumer.properties.max.partition.fetch.bytes为50MB的原因导致消费者拉取消息失败。但是我又做了下实验，node节点打印发送kafka消息完成，监控kafka消费组  metersphere_group_id，该消费组里的消费的TOPIC ms-api-exec-topic并没有收到消息，我感觉是node节点没有回传kafka消息成功


我的脚本会包含一个请求体为一张36MB的图片转成的base64字符串的POST请求和一个请求体为15MB左右图片转成的base64字符串的POST请求，如果使用失败重试，则该请求会作为一条消息回传到kafka，可能会出现这种情况吧


36MB的图片的Base64 大小为49MB
15MB的图片的Base64大小为20MB
