### ISSUE TITLE
[BUG]系统设置中的环境管理，当只有工作空间管理员权限访问时，点击报错没有权限，并闪一下，回到个人信息，此时的界面渲染有点问题

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#32957]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

系统设置中的环境管理，当只有工作空间管理员权限访问时，点击报错没有权限，并闪一下，回到个人信息，此时的界面渲染有点问题
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/c33f9270-95f6-4e06-937b-f8a8166ff767">

### 重现步骤

配置一个只有工作空间管理员权限的用户，登录并点击环境管理。

### 期待的正确结果

直接报错没有对应权限，不进行界面跳转。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本尽量优化一下样式闪显不全的问题。页面跳转问题暂时不做处理，感谢理解和支持。
