### ISSUE TITLE
[BUG][系统设置]系统参数设置中的显示设置支持设置系统名称，但是对应的新手教程中的系统名称没改

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#32955]
### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

系统参数设置中的显示设置支持设置系统名称，但是对应的新手教程中的系统名称没改
![image](https://github.com/user-attachments/assets/a204145d-1575-4c88-aff1-29e47c05f7fe)

### 重现步骤

设置新的系统名称，创建新用户并登录。

### 期待的正确结果

新用户登录时展示的是新的系统名称

**Comment by youliyuan-fit2cloud** [comment]
emmm...后续版本优化。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
