### ISSUE TITLE
[BUG]A指令中复制了B指令，B指令里有引用的C指令和其他步骤，在其他步骤下新增步骤，新的步骤不显示页面

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#32963]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

A指令中复制了B指令，B指令里有引用的C指令和其他步骤，在其他步骤下新增步骤，新的步骤显示的是上一个步骤的内容，无法填写新步骤内容。

### 重现步骤

1、创建指令C
2、创建指令B，指令B中引用指令C，并且添加一些其他步骤
3、创建指令A，在指令A中复制指令B
![image](https://github.com/user-attachments/assets/b9520a3d-6135-48aa-8cda-ab4df76301c9)
4、在指令A中新增一个步骤，会显示上一个步骤的内容A指令中复制了B指令，B指令里有引用的C指令和其他步骤，在其他步骤下新增步骤，新的步骤不显示页面
![image](https://github.com/user-attachments/assets/c759e53a-2dd1-4cce-bf00-d1dd1c49c296)
![image](https://github.com/user-attachments/assets/c47a405b-5bcc-4727-b55e-75d06c46d1f5)

### 期待的正确结果

新增正常

**Comment by 13290445582** [comment]
您好，在您提供的环境内已复现该情况，但是同样的数据内容在本地最新测试环境未复现，建议您先升级最新版本尝试下是否可正常使用，同时我们也会在本地继续查看是否可复现该情况，感谢理解。
