### ISSUE TITLE
[BUG]v3.2, 缺陷模板，新曾字段 如果选择“成员”类型，并且开启容许添加多个成员，会导致出现提交缺陷页面 基础信息无法显示。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#32979]
### 联系方式

王进

### MeterSphere 版本

v3.2

### 使用外置数据库

否

### 问题描述

v3.2, 缺陷模板，新曾字段 如果选择“成员”类型，并且开启容许添加多个成员，会导致出现提交缺陷页面 基础信息无法显示。

### 重现步骤

1. 打开缺陷模板，添加如下“成员”类型字段，并且开启容许添加多个成员。见下图
![8e626f0814b710dafc2772e7e69d3c0](https://github.com/user-attachments/assets/1d615cb3-8f56-4f67-a847-0b7a434dd4ad)
2. 保存缺陷模板，然后点击左侧导航栏“缺陷管理”，点击【创建缺陷】，问题出现
<img width="1271" alt="1725588660358" src="https://github.com/user-attachments/assets/b81b657f-9ba6-4500-aced-c7f1ae26768b">

### 期待的正确结果

用户可以正常提交缺陷

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
