### ISSUE TITLE
[BUG]接口自动化提取参数规则没有保存下来

### ISSUE THREAD

**Issue by lufeifeiya** [metersphere/metersphere#3297]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.10
**Bug 描述**
简要描述您碰到的问题
接口自动化的用例提取参数规则没有保存下来

**Bug 重现步骤**
1.  接口自动化-场景新建-导入接口列表
2. 继续编辑接口，添加提取参数
3. 编辑提取参数名称,提取规则
4. 保存再次打开用例

实际结果
提取参数规则没有保存下来，页面上看不到

**期待的正确结果**
保存下提取参数规则

**截图**
如果有截图，请附上截图.
![无标题](https://user-images.githubusercontent.com/24427113/119940883-68ef3580-bfc2-11eb-8c29-6250afa57587.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
是用的1.10.0版本吗，没有复现该问题呢

**Comment by lufeifeiya** [comment]
无法重现了。。。
