### ISSUE TITLE
[BUG]测试计划中关联用例时部分数据查询不到

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3298]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0
**Bug 描述**
简要描述您碰到的问题
测试计划中关联接口用例部分内容列表中有数量显示，但实际数据无法在结果列表中显示
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
能够正常显示
**截图**
![image](https://user-images.githubusercontent.com/40912823/119946046-c2f2f980-bfc8-11eb-88f6-a9fabfc88644.png)

**Comment by zyyfit** [comment]
您好，这个地方显示的是接口数量，但是接口需要有用例才能被测试计划关联的，我们会考虑优化一下这个问题
