### ISSUE TITLE
[BUG] ui 自动化输入操作中 Tab 功能键不生效

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32988]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

ui 自动化输入操作中 Tab 功能键不生效

### 重现步骤

输入操作中使用Tab 功能键，发现未生效

### 期待的正确结果

ui 自动化输入操作中 Tab 功能键生效

### 相关日志输出

```shell
无
```

### 附加信息

<img width="668" alt="1725605858865" src="https://github.com/user-attachments/assets/082da1a5-fdac-4b3a-8476-356c1def7034">

<img width="549" alt="企业微信截图_17256059802473" src="https://github.com/user-attachments/assets/1e7adacf-7c6d-4f81-92d9-43177891878d">

**Comment by 13290445582** [comment]
您好，不支持这样使用，元素定位始终是在账号框，所以按tab后输入框内容还是回找到账号框去输入。
