### ISSUE TITLE
[BUG]测试计划规划页面，调整测试点顺序不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32983]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

测试计划规划页面，调整测试点顺序不生效

### 重现步骤

编辑某个测试计划，调整测试点顺序，保存后又变成调整之前的顺序

**Comment by youliyuan-fit2cloud** [comment]
你好，是调整 功能用例，接口用例，场景用例之间的顺序吗？调整这个顺序确实没有作用，实际使用场景是什么？调整顺序也没啥意义吧？

**Comment by dashenyucainiao** [comment]
已找到生效方式
