### ISSUE TITLE
[FEATURE]v3.2，项目管理？消息通知》缺陷管理》创建缺陷 ，“创建”对应的通知接收人 不支持选择“处理人”，需要支持“处理人”

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#32980]
### MeterSphere 版本

v3.2

### 联系方式

王进

### 请描述您的需求或者改进建议

[FEATURE]v3.2，项目管理？消息通知》缺陷管理》创建缺陷 ，“创建”对应的通知接收人 不支持选择“处理人”，需要支持“处理人”

### 请描述你建议的实现方案

提交缺陷，通常肯定会指定“处理人”。

**Comment by luty2018** [comment]
已排期v3.3
