### ISSUE TITLE
[BUG]UI测试场景中引用指令，在场景中修改指令的入参，目前无法修改

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#32992]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.18-lts

### 使用外置数据库

否

### 问题描述

UI测试场景中引用指令，在场景中修改指令的入参，目前无法修改。
指令在设计的时候，是允许在场景中修改指令的入参的，现在出现了问题，没法修改。

### 重现步骤

1、在场景中引用一个指令，在场景中无法修改指令的入参
<img width="941" alt="94b3487a7ddd34f139cb65f4aa70d86" src="https://github.com/user-attachments/assets/f866d182-9786-4d90-86ef-17a50e37a639">

### 期待的正确结果

允许修改

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复该问题。

**Comment by zrfit** [comment]
您好，v2.10.20已修复该问题，建议升级验证。
