### ISSUE TITLE
[BUG] 复制的场景用例在复制的环境下执行时，变量 __metersphere_env_id 取到的环境ID不正确

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#32999]
### MeterSphere 版本

v2.10.19-lts-90463ffd

### 使用外置数据库

否

### 问题描述

如下图：
![image](https://github.com/user-attachments/assets/a761e3e4-a71e-4a7e-be1f-e323986c5509)

在本例中，取得的access_token为：346aef8f-ccc1-40e7-88e7-6b63e73d0680

结果：
在数据库中查询该ID对应的环境是错误的。
![image](https://github.com/user-attachments/assets/a881a315-8318-4461-bfb3-17522096da7b)

写入到了错误的环境中：

![image](https://github.com/user-attachments/assets/be5357f1-a9c8-4351-875d-0892f632f2dc)

### 重现步骤

1. 创建一个环境A
2. 创建一个场景用例a，并编写后置脚本，脚本中需要用到__metersphere_env_id 这个变量
> 本例中beanshell脚本为：
String access_tk = “xxxxxxxxxxxxxxxxxxxxxxx”;
log.info("环境ID查看："+${__metersphere_env_id});
vars.put(${__metersphere_env_id}+"access_token",access_tk);
4. 执行场景用例a，并选择环境A，此时环境A正确写入access_token
5. 复制场景a为b，复制环境A为B，将B的环境地址（URL）修改一下
6. 修改b场景的运行环境为B，执行，此时ID就不对了，取到了环境A的ID，然后写到了环境A中

**Comment by 13290445582** [comment]
您好，暂未复现该复制后取值错误问题，是复制场景作为步骤执行，还是直接复制出一个新的场景和环境。

**Comment by LimonFHM** [comment]
是复制一个场景作为一个新场景用例~。可能不一定是必现（比如可能老数据的问题？），但是上面的图中确实有错误客观存在，且我们有至少4个环境是取值错误，很困扰。

**Comment by LimonFHM** [comment]
> 是复制一个场景作为一个新场景用例~。可能不一定是必现（比如可能老数据的问题？），但是上面的图中确实有错误客观存在，且我们有至少4个环境是取值错误，很困扰。

**Comment by LimonFHM** [comment]
你好，这是重现视频，用户是这么操作的。
但是问题的本质在于接口定义和接口用例曾经存储过环境~，请见下方补充的两点复现思路。

https://github.com/user-attachments/assets/d5178b87-daba-4123-be7c-186e33013a67

**Comment by LimonFHM** [comment]
> 你好，这是操作视频，请见补充。
> 
>  MS.mp4


补充：操作虽然是这么操作，但是问题的本质可能不是上述的操作所导致的，经反复验证，确定问题在接口定义那边。

复现1：接口CASE中曾经保存过环境的情况：
![image](https://github.com/user-attachments/assets/cad6f14d-079a-4da5-a35a-3eba517c3067)

复现2：接口定义中调试过环境的情况：
![image](https://github.com/user-attachments/assets/02c7725c-00c8-4b49-8c43-056d14acffbe)


总结：请按照实际执行环境来生成环境ID，优先级应该为：

测试计划中的环境选择>场景的环境选择>接口用例的环境选择>接口定义的环境选择（接口定义本身可以不保存执行环境）

**Comment by 13290445582** [comment]
感谢支持，问题已复现，后续版本修复。

**Comment by cs6636563** [comment]
还得是我们伟大的用户能解决问题

**Comment by LimonFHM** [comment]
请问下个版本能解决吗？

**Comment by LimonFHM** [comment]
> 感谢支持，问题已复现，后续版本修复。



> 感谢支持，问题已复现，后续版本修复。

请问呢下个版本可以解决吗？

**Comment by youliyuan-fit2cloud** [comment]
> > 感谢支持，问题已复现，后续版本修复。
> 
> > 感谢支持，问题已复现，后续版本修复。
> 
> 请问呢下个版本可以解决吗？

会的。这个月底发布。

**Comment by llzhou1229** [comment]
我们也遇到了相同的问题，在测试计划中执行场景时，只要场景调试时引用过环境，测试计划执行时选择的环境是不生效的，执行的永远是场景调试时引用 的那个环境。

**Comment by 13290445582** [comment]
问题已修复，请升级。
