### ISSUE TITLE
[BUG]【接口调试】请求体-json 处没有Schema/Json切换，建议和接口定义页面处保存一致。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32996]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【接口调试】请求体-json 处没有Schema/Json切换，建议和接口定义页面处保存一致。

### 重现步骤

【接口调试】请求体-json 处没有Schema/Json切换，建议和接口定义页面处保存一致。
![image](https://github.com/user-attachments/assets/d4ebc775-7abe-405c-9f83-a8df4c374ee7)

![image](https://github.com/user-attachments/assets/c38ed72f-bc3c-443f-8b87-247e04502e68)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这里还没做，后续版本会支持，敬请期待～
