### ISSUE TITLE
[BUG] 脑图 用例文字的选中复制粘贴用不了，也无法换行

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#32990]
### MeterSphere 版本

3.2

### 请描述您的需求或者改进建议

 脑图 用例文字的选中复制粘贴用不了
![用例文字的选中复制粘贴用不了](https://github.com/user-attachments/assets/44f7a9b3-831e-4d2e-b8c8-cb7b47b46ebe)

### 请描述你建议的实现方案

文字可以 选中 复制粘贴。 换行操作atl+enter?

 ctrl   c v

**Comment by xhy12** [comment]
![0c5aa014e31514e21815065faf2853b](https://github.com/user-attachments/assets/b6015e1e-29ca-4b50-b0e6-cf4b34ffa729)

**Comment by Hyyfit** [comment]
文字的复制（ctrl+c ）、粘贴（ctrl+v），3.3已支持；
脑图里的输入框，是普通的输入框，不带格式的，也不支持换行；
