### ISSUE TITLE
[BUG]对于多测试集并行的情况下，测试计划的“场景用例“设置失败停止不生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#32993]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

对于多测试集并行的情况下，测试计划的“场景用例“设置失败停止不生效，虽然有失败的场景，但是各个测试集下的场景都会被执行。

### 重现步骤

按附件中的图规划测试计划，场景用例设置失败停止。添加肯定会失败的场景，观察配置是否会生效

### 附加信息

<img width="962" alt="image" src="https://github.com/user-attachments/assets/11265679-5e21-4b26-acc9-5ea2ce7427e9">

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，执行是以测试集为单位的，失败停止之后是不会影响其余测试集的。而且之前的需求中要求的是：父类节点的设置只是为了子节点的“使用父节点设置”使用。若有此场景需要，可提FEATURE以供调研。
