### ISSUE TITLE
[BUG]【接口调试】浏览器post请求的 cURL 格式进行导出后，导入到MS里，请求类型不对，请求体数据也没有显示。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32995]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【接口调试】浏览器post请求的 cURL 格式进行导出后，导入到MS里，请求类型不对，请求体数据也没有显示。

### 重现步骤

【接口调试】浏览器post请求的 cURL 格式进行导出后，导入到MS里，请求类型不对，请求体数据也没有显示。
![image](https://github.com/user-attachments/assets/b10586f8-0902-41c9-bd18-7c62471db913)
![image](https://github.com/user-attachments/assets/b0f963ff-8041-409c-acf5-396c8b6d471b)

将该 cURL 格式导入 postman 中，都能正常展示。
![image](https://github.com/user-attachments/assets/9d5634c4-ac20-4fb0-8ea3-ae9985f0f619)

**Comment by youliyuan-fit2cloud** [comment]
你好，
请把 cURL地址发出来看看有没有post 方法信息？

**Comment by 2lipan** [comment]
cURL 地址如下:
[测试.txt](https://github.com/user-attachments/files/16906083/default.txt)

**Comment by youliyuan-fit2cloud** [comment]
v3.3已解决
