### ISSUE TITLE
[BUG]【接口调试】get请求带一个query参数，cURL导出后，再进行导入，显示请求地址处有个参数，query处有参数，最终发出去的参数有两个。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#32998]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【接口调试】get请求带一个query参数，cURL导出后，再进行导入，显示请求地址处有个参数，query处有参数，最终发出去的参数有两个。

### 重现步骤

【接口调试】get请求带一个query参数，cURL导出后，再进行导入，显示请求地址处有个参数，query处有参数，最终发出去的参数有两个。
![image](https://github.com/user-attachments/assets/e32fae06-3c27-49e0-9826-51db8e5c395a)
![image](https://github.com/user-attachments/assets/ed07d46a-c3c1-43cf-95f9-74b55dbf70d8)
![image](https://github.com/user-attachments/assets/7e858b55-7a00-48ab-86d6-bc1079e2948b)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
