### ISSUE TITLE
[BUG] kafka配置问题

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33006]
### 联系方式

70群，ijwstl

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

链接我之前提过的问题:https://github.com/metersphere/metersphere/issues/32953,
这个问题之所以在接口调试时没有出现，只在勾选错误重试时出现的原因为，当勾选了错误重试，每个场景的请求回传会合并在一个kafka消息里，这样就导致如果这个场景的部分请求回传消息本身就比较大，这么一叠加，就会超出100MB，为什么kafka各项设置了500Mb没有生效，原因我写在下边了。

### 重现步骤

1、准备一张大于30MB的图片，
2、准备一个测试接口，该接口内容如下,该接口很简单，就是将一个图片的base64值作为返回值。
<img width="948" alt="image" src="https://github.com/user-attachments/assets/ac785076-9aae-4f28-90d6-3afa5a4917f2">

3、准备一个自动化场景
将这请求引入自动化场景，并且多复制几步，保证这个场景最后回传值会大于100MB即可
4、将这个自动化场景引入测试计划
5、执行测试计划，并且勾选失败重试。

### 相关日志输出

```shell
这时候监看kafka的server.log,位置在/opt/kafka/logs, 可以看到如下报错
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 111338035 larger than 104857600)
```

### 附加信息

经过今天一天的排查，如果按照目前kafka的配置，虽然配置了message.max.bytes等为500MB，但是受限于socket.request.max.bytes，该项配置默认为100MB，所以整个kafka消息最大被限制到100MB，才会出现这种问题

建议修改Kafka配置，增大socket.request.max.bytes与其他项保持一致

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈， 这个socket.request.max.bytes 配置根据用户需求来自己手动修改，我们暂时不做变更，非常感谢您的理解和支持～

**Comment by ijwstl** [comment]
> 感谢您的反馈， 这个socket.request.max.bytes 配置根据用户需求来自己手动修改，我们暂时不做变更，非常感谢您的理解和支持～

嗯嗯，可以的
