### ISSUE TITLE
[FEATURE]Jenkins插件建议增加运行环境选择

### ISSUE THREAD

**Issue by LuxTong** [metersphere/metersphere#33018]
### MeterSphere 版本

v2.10.17-lts

### 联系方式

MeterSphere 交流群46 阿汤锅

### 请描述您的需求或者改进建议

目前jenkins插件中执行测试计划，无法选择运行环境，只能使用默认的运行环境运行。希望可以增加运行环境选择，这样一个计划可以在不同环境的pipeline里使用。

**Comment by luty2018** [comment]
Jenkins中增加环境选择会有一些限制存在，可以考虑复制多个测试计划才对应不同的pipeline。
