### ISSUE TITLE
[BUG] 接口定义中对请求体数据类型变更[String-number]变更记录中无对应的记录显示

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#33019]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

接口定义中对请求体（json[json-schema]）中数据类型做出改变后变更记录与该页面均不会产生变更。具体有如下类型转换的问题：String->number后保存显示任然是String类型，变更记录中也无对应的操作变更记录。除此还有String->Object/array等。

### 重现步骤

点击接口定义-点击新建-API-请求体-json-打开JSON-SCHEMA-对参数的属性由String修改为number。

### 期待的正确结果

显示参数属性为number，且变更记录中拥有对应的操作变更记录

### 附加信息

![微信图片_20240909160441](https://github.com/user-attachments/assets/52fd009c-5093-45cc-b60e-c919a63d726a)
![微信图片_20240909160638](https://github.com/user-attachments/assets/a1d2af46-e53a-4908-963c-3ce8ae8fb8ac)
![微信图片_20240909160738](https://github.com/user-attachments/assets/7fbfe00a-4df6-4892-8dc6-9343b40bac25)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
