### ISSUE TITLE
[BUG]【接口测试】接口定义处-json-schame 处，填写了描述信息，点击关闭后再开启，描述信息就不见了。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#33010]
### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

【接口测试】接口定义处-json-schame 处，填写了描述信息，点击关闭后再开启，描述信息就不见了。

### 重现步骤

【接口测试】接口定义处-json-schame 处，填写了描述信息，点击关闭后再开启，描述信息就不见了。
![image](https://github.com/user-attachments/assets/38e1ad03-799a-4c4a-a7dc-963308ca3946)
![image](https://github.com/user-attachments/assets/b08d3f9d-3bd3-4c77-8f0c-4f7a5e8ed4fc)

**Comment by youliyuan-fit2cloud** [comment]
你好，json-schema 关闭再开启不会保存除了参数和参数值的信息，鉴于v2版本只修复优先级较高的问题，这个问题不再优化，感谢理解和支持。
