### ISSUE TITLE
[QUESTION] 登录页面语言问题

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33027]
### 请描述您的问题

默认界面语言设置，我看对国际化设置是通过请求后端获取的，但是在上次版本更新将await关键字去掉了，这样会导致函数异步执行，其实最后locale获取不到getLanguage函数的值，只能走自动获取，默认就是En-US的。

![image](https://github.com/user-attachments/assets/4c8e2baf-946a-411c-8d5e-66127b8deaf9)

**Comment by fit2-zhao** [comment]
更新代码

**Comment by ijwstl** [comment]
> 更新代码

gateway的前端代码就是这样啊
![image](https://github.com/user-attachments/assets/ddd6c418-1737-4789-8bd4-90d1ffd994b5)
