### ISSUE TITLE
[BUG]接口定义通过swagger导入，swagger中ResponseResult中有《》这个符号就会报错，报数据解析错误，V2和V3的最新版本均有这个问题

### ISSUE THREAD

**Issue by llzhou1229** [metersphere/metersphere#33025]
### 联系方式

zll_881229@163.com

### MeterSphere 版本

v2.10.17-lts、v3.2.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/81f257f1-c4ed-41c9-ae9a-9a76a0ec2f97)
![image](https://github.com/user-attachments/assets/ac34a72f-3dad-42c0-895e-4c42cadaffc8)
![image](https://github.com/user-attachments/assets/dca97733-8b5e-4191-9415-39b46fe6e233)
![image](https://github.com/user-attachments/assets/abf570ff-3c7e-4d42-ac86-3d33722d15e6)

### 重现步骤

后端日志报错：
![5b7676845ee5aba1262dbfc8d06bc808](https://github.com/user-attachments/assets/c64b8f94-fd4b-40c5-889f-4a8e96fdc0bf)

### 期待的正确结果

能正常导入不丢失，不报错

**Comment by 13290445582** [comment]
您好，麻烦提供下swagger文件，感谢支持。

**Comment by llzhou1229** [comment]
> 您好，麻烦提供下swagger文件，感谢支持。

[api-docs (3).json](https://github.com/user-attachments/files/16978143/api-docs.3.json)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by luty2018** [comment]
为什么一定要用这个《》符号？XML不支持这个符合的展示

**Comment by llzhou1229** [comment]
> 为什么一定要用这个《》符号？XML不支持这个符合的展示
研发代码中返回的是泛型的格式，swagger生成后就是带《》，如果能支持直接解析swagger生成json文件那是不是就解决了这个问题？现在是不是工具侧将json转换成了xml，然后xml不支持这个符号所以报错呢？

**Comment by 13290445582** [comment]
您好，我们发现是有一些特殊字符导致的错误。 这些特殊字符«»不是简单的英文输入法<> 或者中文输入法 《 》。也就是说可能还会出现更多的特殊字符影响导入。 目前我们没有做这种特殊字符库的打算
所以我们采取的方案是尽可能把接口信息导入过来，这种情况会直接把报错信息贴到内容中提示。若后续有其他需求或其他想法请反馈FEATURE我们评估下，感谢您的理解与支持。
<img width="619" alt="image" src="https://github.com/user-attachments/assets/9a14ec4e-8b3e-40bc-b23e-29a5415ade08">
