### ISSUE TITLE
[FEATURE]系统设置模块，添加成员时，能不能新增可以通过id筛选或者列表展示多了id属性展示

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#33026]
### MeterSphere 版本

v2.10.17-lts

### 请描述您的需求或者改进建议

目前遇到了有很多用户重名的场景，用户都是通过单点对接过来的，对应的id就是工号，用户提供工号给管理员进行权限的配置，但是目前不支持通过搜索工号来筛选用户，导致管理员只能通过邮箱进行匹配。
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/f06683ce-6cd4-4c1f-a2ee-5fbbd46c3c24">

### 请描述你建议的实现方案

希望系统设置模块，添加成员时，新增可以通过id进行筛选或者列表展示多了id属性展示，方便管理员进行权限的配置。

**Comment by luty2018** [comment]
v2.10.22

**Comment by 13290445582** [comment]
您好，v2.10.22版本已实现需求成员下拉框显示成员ID，请升级。
