### ISSUE TITLE
[BUG]资源池调整node的并发数不生效，需要重启task-runner后才会生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#33024]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

资源池调整node的并发数不生效，启动的worker线程仍然为之前设定的10，需要重启task-runner后，在日志中才会看到重置的并发数

### 重现步骤

1、给资源池的node节点设定固定的10个并发，批量选择场景或者用例进行并发执行，观察日志打印；
3、给资源池node重新设定并发数，批量选择场景或者用例进行并发执行，观察日志打印。

### 相关日志输出

```shell

```

### 附加信息
资源池设定的是33并发：
重启task-runner之前：
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/0289ea98-586e-4335-b847-9b391ed8e38b">

重启task-runner之后：
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/2a515f1a-f708-4dcd-a28a-b8beeb62fd8f">
_No response_

**Comment by fit2-zhao** [comment]
已经处理过，等下版本。

**Comment by youliyuan-fit2cloud** [comment]
v3.3 版中已修复
