### ISSUE TITLE
[BUG]【接口测试】接口脚本中引用js文件，执行接口测试报错TypeError: Cannot set property "ASN1Util" of undefined to "[object Object]" (/opt/metersphere/data/body/jsrsasign-all-min.min.js#1) 

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#33030]
### MeterSphere 版本

v2.10.19

### 使用外置数据库

否

### 问题描述

引用外部js 文件做加密操作，执行接口报TypeError: Cannot set property "ASN1Util" of undefined to "[object Object]" (/opt/metersphere/data/body/jsrsasign-all-min.min.js#1) 错，同样的代码放在jmeter中是可以执行的

### 重现步骤

1、将附件的js文件上传到服务
2、执行附件的代码

### 期待的正确结果

js代码能正常执行

### 相关日志输出

```shell
TypeError: Cannot set property "ASN1Util" of undefined to "[object Object]" (/opt/metersphere/data/body/jsrsasign-all-min.min.js#1)
```

### 附加信息

1、js文件
[js文件.zip](https://github.com/user-attachments/files/16939664/js.zip)
2、接口脚本代码：

var navigator = this;
var window = this;
g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load; 
var aes = load("/opt/metersphere/data/body/crypto-js.js");
var rsa = load("/opt/metersphere/data/body/jsrsasign-all-min.min.js");

   log.info("私钥解密：" + 111);
    var keyPri = "-----BEGIN PRIVATE KEY-----\n" +
        "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANgoMoiwPKSdMfrx\n" +
        "AvqBIMF8e2GMx1NLc7PBC3hZIPloekW8xEKcxk+uB/v3VHxDfOPNVqX9cW3uxJLG\n" +
        "nOle1gvRi2+sY5jXa1nlkvnIAp5pccCQXxjqsPqIZGNCORbILZkzY0SiC34WZg3c\n" +
        "jhXkyagwpzjNUsbx4cTrai5UjQznAgMBAAECgYBU0ilKVAXn/rtfInYtwMAOzP9J\n" +
        "f0m0WNZVQjpzBl6XIDVi6jkFfqmfGMaPTDW98WmvpqMKzdJV9izy/7cRKKLLFdTd\n" +
        "AY9LwPtAWGz9Mv6AFclfFso/U8N9HpyY3B91M7tmTqaUyw+xdMazh4sqBQKrBOP3\n" +
        "XjF4SY3PSz3W87KMeQJBAO3jsESxbVlt0TorEkab44sKpddB7rYqanOLKmnPE8UY\n" +
        "ogwXJwfY4UrX2rkQZ/XD1I162I1G5uSLxZHTOW775s0CQQDonPVnbyShd9oARk/E\n" +
        "5VSfiRceMtWr4cl88hLhtV03xmn/hS4uHebm2WISWjIq5veqyedIDSodBfRt6lqB\n" +
        "ybqDAkEAlDxbbJK7NwzNYdfRDZq6UbwS123IWE9aAiHoDgLxqNHOuIX81lD5InAb\n" +
        "ZVKp1WVwH7E7G93gpu3J8TKUCWqCyQJATsGdwPh7cYPvtnoX1fVDcoRq5FmXyIs4\n" +
        "ueoIBI1wU0sFZnMEEK8lF3HwZ4BMTgRHRHb5rIZwhMUYXgKjxB+12wJBAM+pf/DG\n" +
        "Qr8fYKubE0444Hz/RTeQgcpxpp7xWbKutFap6tIZAZnKlyYjDKAbNCbDMLjg/zii\n" +
        "kDgsl2WXNRUK4hE=\n" +
        "-----END PRIVATE KEY-----";

    var keyPub = "-----BEGIN PUBLIC KEY-----\n" +
        "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYKDKIsDyknTH68QL6gSDBfHth\n" +
        "jMdTS3OzwQt4WSD5aHpFvMRCnMZPrgf791R8Q3zjzVal/XFt7sSSxpzpXtYL0Ytv\n" +
        "rGOY12tZ5ZL5yAKeaXHAkF8Y6rD6iGRjQjkWyC2ZM2NEogt+FmYN3I4V5MmoMKc4\n" +
        "zVLG8eHE62ouVI0M5wIDAQAB\n" +
        "-----END PUBLIC KEY-----";

    // 私钥加签
    function signatureToBase64(data) {
        // data: 原始数据

        // 创建秘钥实例
        var key = KEYUTIL.getKey(keyPri);
        // 指定签名算法 sha1对原文哈希
        var signature = new KJUR.crypto.Signature({alg: "SHA1withRSA"});
        // 传入秘钥实例, 初始化
        signature.init(key);
        // 传入待签明文
        signature.updateString(data);
        // 签名, 得到16进制字符结果
        var signResult = signature.sign();
        // 签名hex转base64
        return hextob64(signResult);
    }

    // 公钥验签
    function verifySignature(signBase64, data) {
        // signBase64: 签名（已转base64）
        // data: 原始数据
        try {
            // 公钥验签
            var signatureVf = new KJUR.crypto.Signature({alg: "SHA1withRSA", prvkeypem: keyPub});
            signatureVf.updateString(data);
            return signatureVf.verify(b64tohex(signBase64));
        } catch (e) {
            log.error(e);
        }
    }

    // 公钥加密
    function encryptToBase64(data) {
        // 读取解析pem格式的秘钥, 生成秘钥实例 (RSAKey)
        var pub = KEYUTIL.getKey(keyPub);
        var enc = KJUR.crypto.Cipher.encrypt(data, pub);
        return hextob64(enc);
    }

    //私钥解密
    function decryptData(dataBase64) {
        var prv = KEYUTIL.getKey(keyPri);
        return KJUR.crypto.Cipher.decrypt(b64utohex(dataBase64), prv);
    }

    var data = "abcdefg";
    log.info("原始数据：" + data);

    //私钥加签
    var signBase64 = signatureToBase64(data);
   log.info("私钥加签：" + signBase64);

    //公钥验签
    var verifyResult = verifySignature(signBase64, data);
    log.info("公钥验签：" + verifyResult);

    //公钥加密
    var encryptDataBase64 = encryptToBase64(data);
    log.info("公钥加密：" + encryptDataBase64);

    //私钥解密
    var decryptDataStr = decryptData(encryptDataBase64);
   log.info("私钥解密：" + decryptDataStr);

3、jmeter 脚本代码：

var navigator = this;
var window = this;
var aes = load("./crypto-js.js");
var rsa = load("./jsrsasign-all-min.min.js");

   log.info("私钥解密：" + 111);
    var keyPri = "-----BEGIN PRIVATE KEY-----\n" +
        "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANgoMoiwPKSdMfrx\n" +
        "AvqBIMF8e2GMx1NLc7PBC3hZIPloekW8xEKcxk+uB/v3VHxDfOPNVqX9cW3uxJLG\n" +
        "nOle1gvRi2+sY5jXa1nlkvnIAp5pccCQXxjqsPqIZGNCORbILZkzY0SiC34WZg3c\n" +
        "jhXkyagwpzjNUsbx4cTrai5UjQznAgMBAAECgYBU0ilKVAXn/rtfInYtwMAOzP9J\n" +
        "f0m0WNZVQjpzBl6XIDVi6jkFfqmfGMaPTDW98WmvpqMKzdJV9izy/7cRKKLLFdTd\n" +
        "AY9LwPtAWGz9Mv6AFclfFso/U8N9HpyY3B91M7tmTqaUyw+xdMazh4sqBQKrBOP3\n" +
        "XjF4SY3PSz3W87KMeQJBAO3jsESxbVlt0TorEkab44sKpddB7rYqanOLKmnPE8UY\n" +
        "ogwXJwfY4UrX2rkQZ/XD1I162I1G5uSLxZHTOW775s0CQQDonPVnbyShd9oARk/E\n" +
        "5VSfiRceMtWr4cl88hLhtV03xmn/hS4uHebm2WISWjIq5veqyedIDSodBfRt6lqB\n" +
        "ybqDAkEAlDxbbJK7NwzNYdfRDZq6UbwS123IWE9aAiHoDgLxqNHOuIX81lD5InAb\n" +
        "ZVKp1WVwH7E7G93gpu3J8TKUCWqCyQJATsGdwPh7cYPvtnoX1fVDcoRq5FmXyIs4\n" +
        "ueoIBI1wU0sFZnMEEK8lF3HwZ4BMTgRHRHb5rIZwhMUYXgKjxB+12wJBAM+pf/DG\n" +
        "Qr8fYKubE0444Hz/RTeQgcpxpp7xWbKutFap6tIZAZnKlyYjDKAbNCbDMLjg/zii\n" +
        "kDgsl2WXNRUK4hE=\n" +
        "-----END PRIVATE KEY-----";

    var keyPub = "-----BEGIN PUBLIC KEY-----\n" +
        "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYKDKIsDyknTH68QL6gSDBfHth\n" +
        "jMdTS3OzwQt4WSD5aHpFvMRCnMZPrgf791R8Q3zjzVal/XFt7sSSxpzpXtYL0Ytv\n" +
        "rGOY12tZ5ZL5yAKeaXHAkF8Y6rD6iGRjQjkWyC2ZM2NEogt+FmYN3I4V5MmoMKc4\n" +
        "zVLG8eHE62ouVI0M5wIDAQAB\n" +
        "-----END PUBLIC KEY-----";

    // 私钥加签
    function signatureToBase64(data) {
        // data: 原始数据

        // 创建秘钥实例
        var key = KEYUTIL.getKey(keyPri);
        // 指定签名算法 sha1对原文哈希
        var signature = new KJUR.crypto.Signature({alg: "SHA1withRSA"});
        // 传入秘钥实例, 初始化
        signature.init(key);
        // 传入待签明文
        signature.updateString(data);
        // 签名, 得到16进制字符结果
        var signResult = signature.sign();
        // 签名hex转base64
        return hextob64(signResult);
    }

    // 公钥验签
    function verifySignature(signBase64, data) {
        // signBase64: 签名（已转base64）
        // data: 原始数据
        try {
            // 公钥验签
            var signatureVf = new KJUR.crypto.Signature({alg: "SHA1withRSA", prvkeypem: keyPub});
            signatureVf.updateString(data);
            return signatureVf.verify(b64tohex(signBase64));
        } catch (e) {
            log.error(e);
        }
    }

    // 公钥加密
    function encryptToBase64(data) {
        // 读取解析pem格式的秘钥, 生成秘钥实例 (RSAKey)
        var pub = KEYUTIL.getKey(keyPub);
        var enc = KJUR.crypto.Cipher.encrypt(data, pub);
        return hextob64(enc);
    }

    //私钥解密
    function decryptData(dataBase64) {
        var prv = KEYUTIL.getKey(keyPri);
        return KJUR.crypto.Cipher.decrypt(b64utohex(dataBase64), prv);
    }

    var data = "abcdefg";
    log.info("原始数据：" + data);

    //私钥加签
    var signBase64 = signatureToBase64(data);
   log.info("私钥加签：" + signBase64);

    //公钥验签
    var verifyResult = verifySignature(signBase64, data);
    log.info("公钥验签：" + verifyResult);

    //公钥加密
    var encryptDataBase64 = encryptToBase64(data);
    log.info("公钥加密：" + encryptDataBase64);

    //私钥解密
    var decryptDataStr = decryptData(encryptDataBase64);
   log.info("私钥解密：" + decryptDataStr);

4、ms 接口报错信息
![image](https://github.com/user-attachments/assets/0ea7b071-36ca-4da1-99a1-d1b749ff5cf5)

5、 jmeter 执行脚本信息
![image](https://github.com/user-attachments/assets/266dde54-cc09-42fd-a349-62e548d2d98a)

**Comment by fit2-zhao** [comment]
从你的图5可见你用的 js 引擎还是 jdk 自带的 Nashorn ，从 jdk 15 之后已经弃用了这个引擎，MeterSphere 平台使用的 jdk 17，js 引擎使用的是 Rhino ，这两个使用语法上会有些许差异，你可以尝试以下调整：

```
g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;
load("xx js");
```
