### ISSUE TITLE
[BUG]测试计划中只关联功能用例无法生成报告

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#33039]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

v2.10.17-lts-53992bfb

### 使用外置数据库

否

### 问题描述

MS2.0中测试计划只关联功能用例后，手动执行无论功能用例是否通过、是否评审均无法生成报告。

### 重现步骤

新建测试计划-只关联功能用例-点击执行-查看报告

### 期待的正确结果

可以产生测试执行的报告

**Comment by youliyuan-fit2cloud** [comment]
你好，如果只有功能用例，在测试计划列表执行该计划会跳转到功能用例列表去手动执行功能用例，然后在报告统计里面保存当前报告结果。不会自动生成报告。感谢理解和支持。
