### ISSUE TITLE
[BUG]【安装部署】修改install.conf里的安装模式，MS_INSTALL_MODE改为middleware后，执行/bin/bash install.sh 安装不成功。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#33036]
### MeterSphere 版本

v3.2.0

### 使用外置数据库

否

### 问题描述

【安装部署】修改install.conf里的安装模式，MS_INSTALL_MODE改为middleware后，执行/bin/bash install.sh 安装不成功。

### 重现步骤

【安装部署】修改install.conf里的安装模式，MS_INSTALL_MODE改为middleware后，执行/bin/bash install.sh安装不成功，出现 'services.mysql.volumes must be a list' 错误。
![image](https://github.com/user-attachments/assets/2af7f2b7-40de-4e56-8d63-f4bc5e168244)
![image](https://github.com/user-attachments/assets/0b6d184d-9347-45a2-a22b-9080f5b0528a)

之后查看安装目录下的 docker-compose-mysql.yml 和  docker-compose-redis.yml 文件，发现volumn和network部分都不对。
![image](https://github.com/user-attachments/assets/c35291f8-1f3d-487d-8ba6-90fbafc9a4f3)
![image](https://github.com/user-attachments/assets/3b3a40f2-29eb-4d0e-be02-cdcd53fa8ede)

**Comment by liuruibin** [comment]
感谢提醒，我们后续会修复这个问题

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
