### ISSUE TITLE
[BUG] 生成校验结果的时候，为数字2.0应该是2.0为啥是Number(2.0)?

### ISSUE THREAD

**Issue by peng7432720** [metersphere/metersphere#33042]
### 联系方式

崔鹏 微信14727136596

### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/8621d571-1e6b-4578-8728-7ae4574342bb">
生成校验结果的时候，我点这里再生成结果应该是2.0为啥是Number(2.0)?

### 重现步骤

可以使用能返回数字类型的后端接口复现这个问题

### 期待的正确结果

返回2.0而不是Number(2.0)

**Comment by youliyuan-fit2cloud** [comment]
你好，Number表示提取的参数类型，看下提取结果是正常的。
