### ISSUE TITLE
[BUG] 场景api用例引用了环境之后，只有第一个接口会引用环境，其他的接口都不会

### ISSUE THREAD

**Issue by peng7432720** [metersphere/metersphere#33040]
### MeterSphere 版本

v3.1.0-a8910b83

### 使用外置数据库

否

### 问题描述

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/b1c6017e-0c96-4cea-9144-25a4c8c48148">
场景用例引用了环境，但是只有第一个接口会引用环境，其他的接口都不会
<img width="962" alt="image" src="https://github.com/user-attachments/assets/e1e460b9-718a-44d0-ae42-de288a192227">
从第二个接口就不会了
<img width="933" alt="image" src="https://github.com/user-attachments/assets/5269a7a6-2e8c-4afe-a90d-29f08e705880">

### 重现步骤

API场景用例里，用循环控制器包装自定义请求，添加环境引用，就可以复现

### 期待的正确结果

添加环境后，原来的URL的前缀要根据引用的环境变化
https://tidy3d-api.uat-simulation.cloud/tidy3d/openai/chat

**Comment by peng7432720** [comment]
崔鹏 微信14727136596

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/40378380-6207-45b1-9424-cfaef904b8d9)
你好，请参考截图，自定义请求自己要设置下 是否引用当前场景的环境。
