### ISSUE TITLE
[BUG] 缺陷导出，列表创建人是姓名，但是导出excel展示的是id

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#33055]
### MeterSphere 版本

2.10.19

### 使用外置数据库

否

### 问题描述

问题 ：缺陷导出，列表创建人是姓名，但是导出excel展示的是id
![image](https://github.com/user-attachments/assets/21460e94-eb64-42d1-a878-3618e595d1d0)

### 重现步骤

缺陷导出，列表创建人是姓名，但是导出excel展示的是id

### 期待的正确结果

展示为姓名，所见所得

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，集成哪个三方平台？

**Comment by youliyuan-fit2cloud** [comment]
已复现该问题，后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
