### ISSUE TITLE
[QUESTION] 接口响应体太大，执行后会一直卡在 running

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#33053]
### 请描述您的问题

https://github.com/metersphere/metersphere/issues/27479

这是之前有人提的相同问题，说是可以通过调大kafka消息大小配置解决一下，所以想咨询下配置kafka哪些参数，改哪个topic，谢谢

**Comment by fit2-zhao** [comment]
可以参照这个配置：
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/17fae6c9-417a-4dab-9b68-4aae65bc2cb3">

https://github.com/metersphere/metersphere/issues/32953


配置位置在：/opt/metersphere/docker-compose-kafka.yml  中；修改后 msctl reload 一下就行。
