### ISSUE TITLE
[BUG]v3.2, 用户环境里出现 缺陷ID重复的情况。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#33068]
### 联系方式

王进

### MeterSphere 版本

v3.2

### 使用外置数据库

否

### 问题描述

v3.2, 用户环境里出现 缺陷ID重复的情况。

### 重现步骤

1. 这个问题客户报上来的，见下面的截图：
![7a8ffcaa8dcb0f88be49bb72347b139](https://github.com/user-attachments/assets/db677d90-2805-4ca5-8ff4-125671c302c3)

2. 这个问题我在测试环境尝试复现没有复现出来。

3. 客户的配置环境是4C 16G。

### 期待的正确结果

这种ID重复的事情，在以往性能测试工作中经常遇到，尤其是并发大的时候。通常解决办法都是优化ID生成算法。

客户这边10来个人用。

建议开发看一下缺陷ID生成算法，尽量优化一下。

**Comment by 35plus** [comment]
刚刚进一步排查，发现是 之前社区版 迁移 到企业版，导致的。无效bug。我们再跟进一下。

**Comment by liuruibin** [comment]
迁移数据不单单是指mysql，redis minio这些也需要一起做迁移处理，不然的话上传的文件，数据的ID编号都会出现问题

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
