### ISSUE TITLE
[BUG]v3.2, 缺陷通知模板中配置的${status}字段，在实际邮件中值不是status值，变成了id

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#33067]
### 联系方式

王进

### MeterSphere 版本

v3.2

### 使用外置数据库

否

### 问题描述

v3.2, 缺陷通知模板中配置的${status}字段，在实际邮件中值不是status值，变成了id

### 重现步骤

1. 缺陷模板配置如下：
<img width="1119" alt="1726105179783" src="https://github.com/user-attachments/assets/9f409c11-bfc2-4ea3-81ce-858d4b9ba72f">

2. 实际邮件内容如下：
<img width="587" alt="1726105008988" src="https://github.com/user-attachments/assets/c3171aea-df03-4de0-8c13-687bf5bab51e">

3. 分析如下：
![f5bc2de66294fe4f3d16ffcb65a8e0a](https://github.com/user-attachments/assets/3265fa67-e6ec-4463-b2ff-f764ac4abc00)

### 期待的正确结果

${status}应该被缺陷状态值替换。

**Comment by youliyuan-fit2cloud** [comment]
下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已修复，V3.3版本已发布，请升级，感谢支持。
