### ISSUE TITLE
[BUG]admin账号修改邮箱，对于xxx@faw-vw.com的邮箱格式校验不通过

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#3307]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0-lts
**Bug 描述**
简要描述您碰到的问题
admin账号修改邮箱，对于xxx@faw-vw.com的邮箱格式校验不通过
**Bug 重现步骤**
1.  个人信息
2. 个人设置
3. 修改信息
4. 输入邮箱

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/119955967-2bdf6f00-bfd3-11eb-8f70-ce8ae523b900.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后面版本修复一下这个问题

**Comment by zyyfit** [comment]
您好，1.10.1版本已修复，请升级后使用
