### ISSUE TITLE
[BUG] 安装模式为server，已开启UI开关，msctl reload没有UI相关容器被创建

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#33084]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

安装模式为server，已开启UI开关，msctl reload没有UI相关容器被创建

### 重现步骤

![image](https://github.com/user-attachments/assets/15b1f182-4c1c-41a6-be5e-c1fb7835bccc)
![image](https://github.com/user-attachments/assets/30e67ac6-3233-4da7-9f62-086f4ac97f14)

**Comment by liuruibin** [comment]
<img width="2254" alt="image" src="https://github.com/user-attachments/assets/52956d20-29d2-486c-82ca-445043d48884">

**Comment by liuruibin** [comment]
具体安装流程呢？

**Comment by fit2cloud-yaochunrong** [comment]
1、将UI测试的容器手动停掉，并rm删除
2、在.env里修改安装模式allinone手动改为server
其余不改（保持UI测试开关开启）
3、msctl reload

**Comment by liuruibin** [comment]
<img width="520" alt="image" src="https://github.com/user-attachments/assets/fd29c215-0042-4d44-8bce-d7b88127cb80">

**Comment by fit2cloud-yaochunrong** [comment]
在.env里修改安装模式allinone手动改为server

**Comment by liuruibin** [comment]
MS_INSTALL_MODE=allinone
<img width="355" alt="image" src="https://github.com/user-attachments/assets/7d400782-4874-4e94-889a-ddfbb46647f4">

MS_INSTALL_MODE=server
<img width="368" alt="image" src="https://github.com/user-attachments/assets/e3bfa56d-32b4-4cbc-a607-e168699bde40">


anything else？

**Comment by fit2cloud-yaochunrong** [comment]
离线安装包修改 vim install.conf文件 UI开关为开，安装模式为server
![image](https://github.com/user-attachments/assets/18f26f12-cdaa-4ab7-aabe-ce3c602be84a)
![image](https://github.com/user-attachments/assets/5c5fc0d4-ef02-4a51-a203-95d03fe6d9fc)
安装成功后么有ui测试容器
![image](https://github.com/user-attachments/assets/ff802522-fc9c-4807-9b9d-270ebcda2cf5)

原因：：vim /usr/local/bin/msctl条件控制器判断是否创建UI容器异常
![image](https://github.com/user-attachments/assets/8ee743e4-9dea-49e3-8d6c-bfe54cc52cfc)

**Comment by liuruibin** [comment]
你先手动操作，下次发布时修复
