### ISSUE TITLE
[BUG]缺陷绑定禅道成功后，页面拉取的缺陷不是相关配置的项目id

### ISSUE THREAD

**Issue by perry-perry-perry** [metersphere/metersphere#33081]
### 联系方式

1176209663@qq.com

### MeterSphere 版本

V3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

缺陷绑定禅道成功后，页面拉取的缺陷不是相关配置的项目id

### 重现步骤

缺陷绑定禅道成功后，页面拉取的缺陷不是相关配置的项目id
配置项目B的id,拉取结果是项目A的数据

### 期待的正确结果

缺陷数据拉取成功，且是配置的项目id下数据

**Comment by youliyuan-fit2cloud** [comment]
你好，请把同步缺陷的配置截图看，可能是项目id和产品id写的不对。

**Comment by perry-perry-perry** [comment]
![278](https://github.com/user-attachments/assets/1ce7b142-ac5d-483c-90d8-1a26d5899ced)
![061](https://github.com/user-attachments/assets/693fecff-6713-495f-8ef3-dc85158a40a7)
![061缺陷](https://github.com/user-attachments/assets/5215dc60-a860-416d-9b5d-4aca12dac468)

**Comment by perry-perry-perry** [comment]
禅道版本：18.7

**Comment by perry-perry-perry** [comment]
![061缺陷](https://github.com/user-attachments/assets/fc540294-95d6-4495-99f1-5bfe70928d29)
![278](https://github.com/user-attachments/assets/c015082f-1c61-4bbc-b968-d6d7e6fd10d0)
![061](https://github.com/user-attachments/assets/47d94a2c-3aef-41e4-8a10-73018b6337df)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/48851c50-f143-43d6-be61-9dd6a8f06048)

你好，你写的是产品ID，参考提示截图修改下看看

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
