### ISSUE TITLE
[BUG] Node节点同步自定义Jar异常

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33098]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

您好，我在项目文件种上传了自定义jar包，并且开启了加载Jar包，执行是node节点报错Minio里找不到这个jar，已经重启过Node节点，自动化所用的插件是可以正常加载的
![image](https://github.com/user-attachments/assets/4d39e00c-ee36-4d72-900d-0051b98facd7)

Node节点日志
![image](https://github.com/user-attachments/assets/f21d2115-c4c4-4c8c-9789-51654536e14e)

minio目录  minio里确实存在这个jar包，是不是node节点下载加载jar的时候bucket写死了为meterpshere而没有用传过来的bucket，因为我们修改过ms的bucket配置
![image](https://github.com/user-attachments/assets/5d601470-14f9-40ba-acd8-627c6af808c9)

经过实验，我新建名为metersphere的bucket后，将该包放入bucket为metersphere的文件路径中后，恢复正常，希望可以修复这个问题，允许用户可自定义bucket名称

### 重现步骤

如上所示

### 期待的正确结果

可以正确加载Jar

**Comment by fit2-zhao** [comment]
暂不支持自定义 BUCKET。
