### ISSUE TITLE
[QUESTION]v3.x拉下来安装运行后输入，用户名admin，密码metersphere，点击登录，提示“检测到用户创建途径异常，禁止登录！“，这该怎么解决啊

### ISSUE THREAD

**Issue by jeremyliu17** [metersphere/metersphere#33096]
### 请描述您的问题

![image](https://github.com/user-attachments/assets/0556e1af-7d31-4fd2-b0e9-6302da5775ab)
![image](https://github.com/user-attachments/assets/8896278a-b303-4b05-a6b8-26c5b4384781)
![image](https://github.com/user-attachments/assets/b3728f0d-5568-471b-9fec-7372fb4d2c0f)
还有一个这个get-list的报错
![image](https://github.com/user-attachments/assets/52598086-4c7f-4219-9f1e-ba1a452ece3c)
![image](https://github.com/user-attachments/assets/7ccd1b9c-c221-4f0d-9025-989d216f065f)

**Comment by fit2-zhao** [comment]
源码启动的吗，可以尝试执行 SQL：
`UPDATE `user` SET cft_token = '/sU3a0dtnm5Ykmyj8LfCjA==' WHERE id = 'admin';`

**Comment by jeremyliu17** [comment]
牛逼，感谢老哥！

**Comment by HutchB** [comment]
你好请问，我这边二开做些调整，admin添加新用户，新用户不能登录，也是出现户创建途径异常，禁止登录
有什么解决的办法？

<img width="602" height="219" alt="Image" src="https://github.com/user-attachments/assets/4b0d6635-ca47-4a32-b051-d5b18d9fadbb" />

<img width="801" height="441" alt="Image" src="https://github.com/user-attachments/assets/a67009e6-06c4-406b-9cc2-96e79898b42f" />
