### ISSUE TITLE
[QUESTION]V3.x拉下来本地安装后运行，用postman调试接口，为什么返回响应均是"message": "No static resource index.html.",   

### ISSUE THREAD

**Issue by jeremyliu17** [metersphere/metersphere#33094]
### 请描述您的问题

响应结果为
 "code": 100500,
    "message": "No static resource index.html.",
    "messageDetail": "org.springframework.web.servlet.resource.NoResourceFoundException: No static resource index.html.\r\n\tat org.springframework.web.servlet.resource.
![image](https://github.com/user-attachments/assets/aab1e181-46e8-494c-8be8-7982da95ff0d)
在swagger中执行也是这个效果，想问问怎么解决
![image](https://github.com/user-attachments/assets/238c5a9d-cbe4-4694-87fd-790281121607)

**Comment by fit2-zhao** [comment]
应该是被拦截了，看参数应该少了 组织 ID 和项目 ID。

**Comment by jeremyliu17** [comment]
跟那个登录问题一样，是权限问题，增加cft_token就解决了，感谢感谢
