### ISSUE TITLE
[BUG]创建案例-保存并继续创建，内容继承了不需要的步骤，基本信息和标题却不继承

### ISSUE THREAD

**Issue by chenyiming04** [metersphere/metersphere#33092]
### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/c416afae-2060-4069-8f03-e8711546210a)

### 重现步骤

创建案例-保存并继续创建，内容继承了不需要的步骤，基本信息和标题却不继承

### 期待的正确结果

创建案例-保存并继续创建，内容继承基本信息

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，下个版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
