### ISSUE TITLE
[BUG] v3 swagger导入接口解析成功但是内容不对

### ISSUE THREAD

**Issue by FzjQWQ** [metersphere/metersphere#33108]
### 联系方式

962700455@qq.com

### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

使用`导入接口` 接口功能填入swagger的url点击导入，导入成功但是内容和实际不符合
![WechatIMG151265](https://github.com/user-attachments/assets/0f9745a2-f5cf-4eff-9291-f4248f5728a1)

导入显示该目录有24个接口，项目内swagger+knife4j显示30个接口
![WX20240913-180200@2x](https://github.com/user-attachments/assets/18f7827a-420d-4851-9d02-d44f93827b03)

### 重现步骤

传入文件
[swagger.json](https://github.com/user-attachments/files/16992256/swagger.json)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/0c8f8e2d-82f2-47ca-98ce-e096e98255f3)
有相同接口，不会重复导入。其他数据请先自行检查下是否是重复的接口，感谢理解和支持。

**Comment by FzjQWQ** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/368389369-0c8f8e2d-82f2-47ca-98ce-e096e98255f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjYyMDcsIm5iZiI6MTcyNjYyNTkwNywicGF0aCI6Ii81NDYxMjg2NC8zNjgzODkzNjktMGM4ZjhlMmQtODJmMi00N2NhLTk4Y2UtZTA5NmU5ODI1NWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAyMTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZTcyYzFlYjFkOTQyMDhhZjBiMTVjNjcwY2NlODUwMzk2OGI2ZmRjMWJkZTJlNzMwZWI0OGY5ZTk3OGViODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uoxdHDrwuVf2K0z0mnUYyyeuFR-EZxjpH7Yr1Y_oqqQ) 有相同接口，不会重复导入。其他数据请先自行检查下是否是重复的接口，感谢理解和支持。

非常感谢您的回复。
确实如您所说，一个接口不会重复的在两个tag里出现，在knife4j就会重复显示。
比如`/device/page` 接口在文档里有两个tag进行描述，metersphere只会在第一个tag里进行展示，而knife4j会在两个tag里都展示。
![1](https://github.com/user-attachments/assets/41bf666c-9e98-4c7d-b58e-e1ab0204c0b9)
![2](https://github.com/user-attachments/assets/7f4bdc59-2976-4176-978a-67e2bcce8017)
![3](https://github.com/user-attachments/assets/3a8ff553-e83f-4fa5-b78e-1b9326b041a0)
![4](https://github.com/user-attachments/assets/616265f7-d3ef-45a9-9b41-adf972082cde)
