### ISSUE TITLE
离线部署后访问不了

### ISSUE THREAD

**Issue by ZZCchuan** [metersphere/metersphere#33116]
### 请描述您的问题

部署后没连网络，访问不了，要连上网络才能正常使用，是要设置什么嘛

**Comment by youliyuan-fit2cloud** [comment]
你好，没网络是指外网访问不了部署的服务器吗？---》需要配置个对外的域名
内网ip也没有吗？还是本地机器访问不了服务器的内网IP ？---〉这种情况必须网络是通的才行，找运维同学看看？
如果有其他问题请提新issue，感谢理解和支持。

**Comment by ZZCchuan** [comment]
> 你好，没网络是指外网访问不了部署的服务器吗？---》需要配置个对外的域名
> 内网ip也没有吗？还是本地机器访问不了服务器的内网IP ？---〉这种情况必须网络是通的才行，找运维同学看看？
> 如果有其他问题请提新issue，感谢理解和支持。

- 宿主机是windows11,连接的路由器
- 我是在VMware安装的ubuntu
- 网络模式用的桥接网络
- ubuntu成功部署了ms，宿主机正常访问
- 断开路由器的网络后，宿主机访问ms失败了


**疑问：是需要连上互联网才能使用的么？**

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，没网络是指外网访问不了部署的服务器吗？---》需要配置个对外的域名
> > 内网ip也没有吗？还是本地机器访问不了服务器的内网IP ？---〉这种情况必须网络是通的才行，找运维同学看看？
> > 如果有其他问题请提新issue，感谢理解和支持。
> 
> * 宿主机是windows11,连接的路由器
> * 我是在VMware安装的ubuntu
> * 网络模式用的桥接网络
> * ubuntu成功部署了ms，宿主机正常访问
> * 断开路由器的网络后，宿主机访问ms失败了
> 
> **疑问：是需要连上互联网才能使用的么？**

你这个情况至少宿主机和 ubuntu之间至少内网肯定要网络联通的。
