### ISSUE TITLE
[BUG]项目管理员无法删除Mock环境

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#3311]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0-lts
**Bug 描述**
简要描述您碰到的问题
项目管理员，删除Mock环境后，创建接口，再回到项目管理，Mock环境又出现
**Bug 重现步骤**
1.  系统设置-项目-环境配置
2. 删除Mock环境
3. 创建一个接口
4. 回到环境配置，Mock环境复现

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/119961060-36503780-bfd8-11eb-814f-2deabd959fc3.png)

**Comment by zyyfit** [comment]
您好，我们的mock环境目前是这样设置的，为了防止用户误删（删除后就无法使用mock相关功能了），在删除后，只要用户使用接口定义相关功能，就会自动创建一个新的环境
