### ISSUE TITLE
[QUESTION] DataStreaming卡住

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33138]
### 请描述您的问题

您好，我在2.10.16-lts使用压力测试时，发现如果data-streaming意外重启的话，重启后会导致消息消费一直卡住，出现如下日志，请问这种情况该怎么解决
![image](https://github.com/user-attachments/assets/8665b0ce-cc5b-43a6-9b45-b333e95ae1e1)

界面上报告会处于收集状态
![image](https://github.com/user-attachments/assets/11df2ad3-c1c2-43f9-ac83-9d354e4852b7)

**Comment by liuruibin** [comment]
首先避免重启，单独部署data-streaming，加大mem_limit
其次万一出现这种情况需要手动将状态改成error

**Comment by ijwstl** [comment]
> 首先避免重启，单独部署data-streaming，加大mem_limit 其次万一出现这种情况需要手动将状态改成error

好的，我再尝试下
