### ISSUE TITLE
[FEATURE]断言添加一个过滤失败的断言功能

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#33147]
### MeterSphere 版本

3.2

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

v3是断言列表会排在响应内容的第一个，但是断言列表还是按照添加的顺序展示的，我希望失败的断言可以排在最前面，希望增加过滤失败断言的功能

**Comment by luty2018** [comment]
感谢反馈， 我们调研一下， 预计在v3.5支持。

**Comment by luty2018** [comment]
已在v3.5支持，可以升级使用。
