### ISSUE TITLE
[BUG] 接口自动化数据表死锁

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33164]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

您好，最近发现了一起数据库锁死的问题，查看进程后发现如下执行请求

LOCK TABLES api_case_execution_info READ /*!32311 LOCAL /,api_data_view READ /!32311 LOCAL /,api_definition READ /!32311 LOCAL /,api_definition_env READ /!32311 LOCAL /,api_definition_exec_result READ /!32311 LOCAL /,api_definition_follow READ /!32311 LOCAL /,api_execution_info READ /!32311 LOCAL /,api_execution_queue READ /!32311 LOCAL /,api_execution_queue_detail READ /!32311 LOCAL /,api_load_test READ /!32311 LOCAL /,api_module READ /!32311 LOCAL /,api_scenario READ /!32311 LOCAL /,api_scenario_follow READ /!32311 LOCAL /,api_scenario_module READ /!32311 LOCAL /,api_scenario_reference_id READ /!32311 LOCAL /,api_scenario_report READ /!32311 LOCAL /,api_scenario_report_detail READ /!32311 LOCAL /,api_scenario_report_result READ /!32311 LOCAL /,api_scenario_report_structure READ /!32311 LOCAL /,api_sync_rule_relation READ /!32311 LOCAL /,api_template READ /!32311 LOCAL /,api_test READ /!32311 LOCAL /,api_test_case READ /!32311 LOCAL /,api_test_case_follow READ /!32311 LOCAL /,api_test_environment READ /!32311 LOCAL /,api_test_file READ /!32311 LOCAL /,api_test_report READ /!32311 LOCAL /,api_test_report_detail READ /!32311 LOCAL /,api_version READ /!32311 LOCAL /,attachment_module_relation READ /!32311 LOCAL /,auth_source READ /!32311 LOCAL /,custom_field READ /!32311 LOCAL /,custom_field_api READ /!32311 LOCAL /,custom_field_issues READ /!32311 LOCAL /,custom_field_template READ /!32311 LOCAL /,custom_field_test_case READ /!32311 LOCAL /,custom_function READ /!32311 LOCAL /,enterprise_test_report READ /!32311 LOCAL /,enterprise_test_report_send_record READ /!32311 LOCAL /,environment_group READ /!32311 LOCAL /,environment_group_project READ /!32311 LOCAL /,error_report_library READ /!32311 LOCAL /,esb_api_params READ /!32311 LOCAL /,file_association READ /!32311 LOCAL /,file_attachment_metadata READ /!32311 LOCAL /,file_content READ /!32311 LOCAL /,file_metadata READ /!32311 LOCAL /,file_module READ /!32311 LOCAL /,function_case_execution_info READ /!32311 LOCAL /,group READ /!32311 LOCAL /,issue_comment READ /!32311 LOCAL /,issue_follow READ /!32311 LOCAL /,issue_template READ /!32311 LOCAL /,issues READ /!32311 LOCAL /,jar_config READ /!32311 LOCAL /,license READ /!32311 LOCAL /,load_test READ /!32311 LOCAL /,load_test_file READ /!32311 LOCAL /,load_test_follow READ /!32311 LOCAL /,load_test_report READ /!32311 LOCAL /,load_test_report_detail READ /!32311 LOCAL /,load_test_report_file READ /!32311 LOCAL /,load_test_report_log READ /!32311 LOCAL /,load_test_report_result READ /!32311 LOCAL /,load_test_report_result_part READ /!32311 LOCAL /,load_test_report_result_realtime READ /!32311 LOCAL /,message_task READ /!32311 LOCAL /,metersphere_version READ /!32311 LOCAL /,minder_extra_node READ /!32311 LOCAL /,mock_config READ /!32311 LOCAL /,mock_expect_config READ /!32311 LOCAL /,notification READ /!32311 LOCAL /,novice_statistics READ /!32311 LOCAL /,operating_log READ /!32311 LOCAL /,operating_log_resource READ /!32311 LOCAL /,organization READ /!32311 LOCAL /,performance_version READ /!32311 LOCAL /,plugin READ /!32311 LOCAL /,project READ /!32311 LOCAL /,project_application READ /!32311 LOCAL /,project_automation_info READ /!32311 LOCAL /,project_management_version READ /!32311 LOCAL /,project_version READ /!32311 LOCAL /,publish_log READ /!32311 LOCAL /,qrtz_blob_triggers READ /!32311 LOCAL /,qrtz_calendars READ /!32311 LOCAL /,qrtz_cron_triggers READ /!32311 LOCAL /,qrtz_fired_triggers READ /!32311 LOCAL /,qrtz_job_details READ /!32311 LOCAL /,qrtz_locks READ /!32311 LOCAL /,qrtz_paused_trigger_grps READ /!32311 LOCAL /,qrtz_scheduler_state READ /!32311 LOCAL /,qrtz_simple_triggers READ /!32311 LOCAL /,qrtz_simprop_triggers READ /!32311 LOCAL /,qrtz_triggers READ /!32311 LOCAL /,quota READ /!32311 LOCAL /,relationship_edge READ /!32311 LOCAL /,report_statistics READ /!32311 LOCAL /,report_version READ /!32311 LOCAL /,role READ /!32311 LOCAL /,scenario_execution_info READ /!32311 LOCAL /,schedule READ /!32311 LOCAL /,service_integration READ /!32311 LOCAL /,share_info READ /!32311 LOCAL /,swagger_url_project READ /!32311 LOCAL /,system_header READ /!32311 LOCAL /,system_parameter READ /!32311 LOCAL /,test_case READ /!32311 LOCAL /,test_case_comment READ /!32311 LOCAL /,test_case_file READ /!32311 LOCAL /,test_case_follow READ /!32311 LOCAL /,test_case_issues READ /!32311 LOCAL /,test_case_node READ /!32311 LOCAL /,test_case_report READ /!32311 LOCAL /,test_case_report_template READ /!32311 LOCAL /,test_case_review READ /!32311 LOCAL /,test_case_review_api_case READ /!32311 LOCAL /,test_case_review_follow READ /!32311 LOCAL /,test_case_review_load READ /!32311 LOCAL /,test_case_review_node READ /!32311 LOCAL /,test_case_review_project READ /!32311 LOCAL /,test_case_review_scenario READ /!32311 LOCAL /,test_case_review_test_case READ /!32311 LOCAL /,test_case_review_test_case_users READ /!32311 LOCAL /,test_case_review_users READ /!32311 LOCAL /,test_case_template READ /!32311 LOCAL /,test_case_test READ /!32311 LOCAL /,test_plan READ /!32311 LOCAL /,test_plan_api_case READ /!32311 LOCAL /,test_plan_api_scenario READ /!32311 LOCAL /,test_plan_execution_queue READ /!32311 LOCAL /,test_plan_follow READ /!32311 LOCAL /,test_plan_load_case READ /!32311 LOCAL /,test_plan_node READ /!32311 LOCAL /,test_plan_principal READ /!32311 LOCAL /,test_plan_project READ /!32311 LOCAL /,test_plan_report READ /!32311 LOCAL /,test_plan_report_content READ /!32311 LOCAL /,test_plan_report_data READ /!32311 LOCAL /,test_plan_test_case READ /!32311 LOCAL /,test_plan_ui_scenario READ /!32311 LOCAL /,test_resource READ /!32311 LOCAL /,test_resource_pool READ /!32311 LOCAL /,track_version READ /!32311 LOCAL /,ui_element READ /!32311 LOCAL /,ui_element_module READ /!32311 LOCAL /,ui_element_reference READ /!32311 LOCAL /,ui_scenario READ /!32311 LOCAL /,ui_scenario_module READ /!32311 LOCAL /,ui_scenario_reference READ /!32311 LOCAL /,ui_task_refresh READ /!32311 LOCAL /,user READ /!32311 LOCAL /,user_group READ /!32311 LOCAL /,user_group_permission READ /!32311 LOCAL /,user_header READ /!32311 LOCAL /,user_key READ /!32311 LOCAL /,user_role READ /!32311 LOCAL /,workspace READ /!32311 LOCAL */

由于没有开启死锁日志，并且进行了停止测试计划的操作，可能innodb里的最近一条死锁日志被覆盖，如下

死锁日志

*** (1) TRANSACTION:
TRANSACTION 22011094, ACTIVE 1 sec fetching rows
mysql tables in use 1, locked 1
LOCK WAIT 27 lock struct(s), heap size 3488, 2 row lock(s)
MySQL thread id 138677, OS thread handle 139782074783488, query id 5799714 10.86.33.215 root updating
UPDATE api_scenario_report SET status ='STOPPED' WHERE status IN ("running","starting","pending") AND
        project_id IN
         (  
            '99d9a564-085a-405c-9216-e722f548aa6c'
         , 
            'd1202112-6d8d-4bfd-b905-ed7128e015c8'
         ) 
         
            and user_id = 'xxx'

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 109 page no 589 n bits 280 index projectIdIndex of table metersphere.api_scenario_report trx id 22011094 lock_mode X locks rec but not gap
Record lock, heap no 149 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
0: len 30; hex 39396439613536342d303835612d343035632d393231362d653732326635; asc 99d9a564-085a-405c-9216-e722f5; (total 36 bytes);
1: len 30; hex 30373830653839622d323134662d343634642d623566392d366339383333; asc 0780e89b-214f-464d-b5f9-6c9833; (total 36 bytes);

*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 109 page no 2227 n bits 88 index PRIMARY of table metersphere.api_scenario_report trx id 22011094 lock_mode X locks rec but not gap waiting
Record lock, heap no 16 PHYSICAL RECORD: n_fields 22; compact format; info bits 96

DELETE FROM api_scenario_report WHERE id IN
         (  
            '0780e89b-214f-464d-b5f9-6c98332aeb1a'
         , 
            '1126f12f-b518-4070-945b-4555470ce631'
         , 
            '181bab87-6327-4ecc-b41c-8890da90a75f'
         , 
            '1ee44e9f-bca4-4e02-a754-eee693bd29d9'
         , 
            '24f34146-8e1c-42be-ac75-b351b46b7228'
         , 
            '2e6ec1d0-ffc2-42d6-b0c6-23e8149dd099'
         , 
            '4b5a9ace-1c87-43c7-88db-46fb80b9fdd5'
         , 
            '4e416ebc-06db-4c18-9734-665a08f7a763'
         , 
            '58072e5e-8960-457e-9bad-56fda35895fe'
         , 
            '67c79240-8783-47f7-a81f-687bcd6ff59f'
         , 
            '68d977a4-a003-4913-887c-c101e84b3b31'
         , 
            '6953f645-ca9f-40b7-ad57-bbe16d7e0d9a'
         , 
            '6fd3602e-b6c2-4235-bb5a-4e8f70875c95'
         , 
            '730205f7-1d8e-47f5-9be3-5cb519309509'
         , 
            '8614b487-e7ee-4441-95a1-c97a1e18ff34'
         , 
            '91acdaea-992e-490a-829b-b1f73231270c'
         , 
            '98039dfe-a57d-48ed-8e51-e18a5e4dc7e6'
         , 
            '9853140d-9ad3-45b9-b3cc-251570d722c9'
         , 
            '98de5074-1a5c-4ee4-9a53-ff8d770512a7'
         , 
            'bd125078-b32b-45c5-a10c-ee52cfad369a'
         , 
            'c1c740ec-45d8-4bce-b1ea-ddcc601576a8'
         , 
            'c587a6b7-4ef4-4bc3-bf21-f34fb7ad0875'
         , 
            'ca08d417-05aa-47e0-83b8-236a9cb919cf'
         , 
            'db7e7ab3-8df0-4357-a6f6-2eca534a296c'
         , 
            'dbce0d35-2ec9-43e4-8ac3-f9d51bea5944'
         , 
            'e99126d9-3377-4cc7-be8a-d7cc584c3970'
         , 
            'f09ca594-4900-4a8a-9aca-f02d978ca2e3'
         , 
            'f1525dd6-1349-4852-84e7-e6a90ebe681f'
         , 
            'ff808563-88c0-487b-bd08-7627f1779f94'
         )

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 109 page no 2227 n bits 88 index PRIMARY of table metersphere.api_scenario_report trx id 22010857 lock_mode X locks rec but not gap
Record lock, heap no 16 PHYSICAL RECORD: n_fields 22; compact format; info bits 96

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 109 page no 589 n bits 280 index projectIdIndex of table metersphere.api_scenario_report trx id 22010857 lock_mode X locks rec but not gap waiting
Record lock, heap no 149 PHYSICAL RECORD: n_fields 2; compact format; info bits 0

### 重现步骤

正常定时任务进行执行，同时设置了定时清理

**Comment by fit2-zhao** [comment]
如果确认定时清理和定时执行同时触发导致，可以先把定时清理时间错开，正常业务中应该也很少对一个执行中的报告进行清理吧。

**Comment by ijwstl** [comment]
> 如果确认定时清理和定时执行同时触发导致，可以先把定时清理时间错开，正常业务中应该也很少对一个执行中的报告进行清理吧。

好的，我加了死锁日志，看看是否会复现
