### ISSUE TITLE
[BUG]jenkins配置任务构建失败，但metersphere实际是成功的

### ISSUE THREAD

**Issue by YouAreOK** [metersphere/metersphere#33176]
### 联系方式

892135367@qq.com

### MeterSphere 版本

3.2

### 使用外置数据库

否

### 问题描述

jenkins配置任务构建失败，但metersphere实际是成功的](https://bbs.fit2cloud.com/t/topic/8065)

### 重现步骤

![image](https://github.com/user-attachments/assets/58eb2a62-e675-425f-a8f7-98957761e731)
![image](https://github.com/user-attachments/assets/8495c1fd-4092-40d6-898c-601cebf45f21)

### 期待的正确结果

jenkins与metersphere结果一致

**Comment by youliyuan-fit2cloud** [comment]
你好，jenkins插件是不是最新的？

**Comment by YouAreOK** [comment]
![image](https://github.com/user-attachments/assets/d611efaa-4fc8-42ba-976a-7fa902948b42)
我下载的时候是最新的呢

**Comment by youliyuan-fit2cloud** [comment]
之前用过jenkins 旧版本吗？感觉版本不是最新的。之前确实修改过这个问题。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
