### ISSUE TITLE
[BUG] 接口自动化 引用环境后链接拼接异常

### ISSUE THREAD

**Issue by wzj1695224** [metersphere/metersphere#3318]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0

**Bug 描述**
从JMX导入的接口 “接口自动化” “自定义请求 ” 勾选“引用环境”后执行时 链接拼接异常

**Bug 重现步骤**
1. 浏览器录制并导出JMX然后在接口自动化中导入
2. 接口自动化编辑接口
3. 在某一请求后勾选引用环境
4. 点击调试，发现结果中请求链接异常

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/8291615/119968541-35bb9f00-bfe0-11eb-9345-71c91213a19f.png)
![image](https://user-images.githubusercontent.com/8291615/119969391-14a77e00-bfe1-11eb-85e6-1eef57484f4e.png)
![image](https://user-images.githubusercontent.com/8291615/119968956-8f23ce00-bfe0-11eb-9b9e-b4359cdb3572.png)

**Comment by zyyfit** [comment]
您好，这个是已知问题，会在后面的版本修复

**Comment by wzj1695224** [comment]
好的，谢谢
那么我需要关闭它吗

**Comment by zyyfit** [comment]
> 好的，谢谢
> 那么我需要关闭它吗

没关系，等修复后我会在这里评论一下然后关闭的

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.10.1 已修复，请升级到该版本。
