### ISSUE TITLE
[BUG]接口自动化的【断言规则】使用脚本断言时，断言结果不匹配时，MS却显示断言成功。

### ISSUE THREAD

**Issue by 15068870403** [metersphere/metersphere#33182]
### 联系方式

MeterSphere 交流群40

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

 v2.10.17接口自动化的【断言规则】使用脚本断言时，断言结果不匹配时，MS却显示断言成功。
![1](https://github.com/user-attachments/assets/9021ef4f-0a1e-4d4d-ae6a-f88cf8a72e6a)

### 重现步骤

 v2.10.17接口自动化的【断言规则】使用脚本断言时，一个返回值为100，另一方返回值返回600，两者进行断言

### 期待的正确结果

断言失败

**Comment by youliyuan-fit2cloud** [comment]
你好，脚本方便贴一下吗？方便复现，感谢～

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
