### ISSUE TITLE
[QUESTION]maven构建时报错：Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 

### ISSUE THREAD

**Issue by zuoqiaoling** [metersphere/metersphere#33187]
### 请描述您的问题

在升级到v2.10.19-lts版本时，node版本也做了升级v20.8.1,maven构建时，报了npm install错误，想咨询下怎么解决这个问题
<img width="684" alt="企业微信截图_172673465332" src="https://github.com/user-attachments/assets/cc3c7979-e665-4651-a815-4b4c384ccc02">

**Comment by fit2-zhao** [comment]
https://github.com/metersphere/metersphere/blob/v2.10/build.md
按照这个过程试试看。

Node 和 npm 对应这个版本
<node.version>v20.8.1</node.version>
 <npm.version>8.4.0</npm.version>

**Comment by zuoqiaoling** [comment]
版本是对的 ，https改成了http
<frontend-maven-plugin.version>1.12.1</frontend-maven-plugin.version>
<node.version>v20.8.1</node.version>
<npm.version>8.4.0</npm.version>
<nodeDownloadRoot>http://nodejs.org/dist/</nodeDownloadRoot>
因为原先用https下载不下来，后改成了http

我这边构建用的是mvn clean install package

https://github.com/metersphere/metersphere/blob/v2.10/build.md 按照这个教程不行，提示-bash: ./mvnw: No such file or directory

**Comment by fit2-zhao** [comment]
你应该是开代理魔法了吧，关了就好。
