### ISSUE TITLE
[BUG]测试计划中在脑图中已经关联的用例无法编辑

### ISSUE THREAD

**Issue by YouAreOK** [metersphere/metersphere#33192]
### 联系方式

892135367@qq.com

### MeterSphere 版本

3.2

### 使用外置数据库

否

### 问题描述

https://github.com/user-attachments/assets/21d1b241-c8fa-4776-81cd-e7f3749fc2db

### 重现步骤

前提条件：已经关联了2条用例
测试计划-测试规划-功能用例-点击 用例数

### 期待的正确结果

可以编辑已经关联的用例记录

**Comment by wardahub-design** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by youliyuan-fit2cloud** [comment]
你好，在功能用例 标签页编辑已关联用例，测试规划这里只可以关联操作。
![image](https://github.com/user-attachments/assets/c5cb3405-9743-49f8-9552-b19b4fa7471e)
