### ISSUE TITLE
[FEATURE] 建议适当扩充metersphere.api_module表 name 字段的长度

### ISSUE THREAD

**Issue by victoryxing126** [metersphere/metersphere#3319]
**请描述您的需求或者改进建议.**
如题，目前 name 是VARCHAR(50)，对于API对应服务名较长的项目、不太友好

**请描述你建议的实现方案**
扩充metersphere.api_module表 name 字段的长度

**Comment by xulinde** [comment]
长度限制多少，能满足您的需求呢
