### ISSUE TITLE
[FEATURE] Headers 希望增加 内置函数引用

### ISSUE THREAD

**Issue by KiraChen1985** [metersphere/metersphere#332]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，目前 header 里面是可以引用函数的，只是没有加类似请求参数里那样的提示

**Comment by KiraChen1985** [comment]
xxxx|base64 这个函数在query和body都可以，headers里面就不能用，我的版本是v1.2.0-b610，是因为版本问题？

**Comment by wangzhen-fit2cloud** [comment]
除了请求参数和body里的 mockjs，其他地方的也处理下吧 @liuruibin

**Comment by wangzhen-fit2cloud** [comment]
> xxxx|base64 这个函数在query和body都可以，headers里面就不能用，我的版本是v1.2.0-b610，是因为版本问题？

mockjs 的函数在这里确实用不了

**Comment by KiraChen1985** [comment]
那以后是不是可以考虑加一下呢？
