### ISSUE TITLE
[BUG]正则断言通过，JSONPath 断言 失败

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#33200]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/be04b8a8-1fcd-4a5d-80fd-eb886b56a1c6)
![image](https://github.com/user-attachments/assets/7300e7db-77a0-4f84-bb15-cd1a22988a36)
![image](https://github.com/user-attachments/assets/58bb4110-a76a-4b40-9ac5-bbdc044f0e89)

### 重现步骤

响应体返回数字，如上述响应截图，通过jsonPath断言，无论是否加\  转义都断言失败，正则断言成功

### 期待的正确结果

希望JSONPath 断言成功

**Comment by youliyuan-fit2cloud** [comment]
你好，json的断言正则表达式看起来不对哇，建议自行校验下这个表达式。感谢理解和支持。

**Comment by fit2cloud-lijiaxin** [comment]
请看【问题描述】两个截图中，使用普通正则匹配是断言通过的，而json 无论是使用与普通正则使用相同表达式，还是 按照json 正则提示 为特殊字符添加转义，都是失败的，应该给正则表达式没关系吧

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/6a0bf3db-517f-46c9-86ef-870d797473e9)
有些符号确实不需要转义了。

**Comment by youliyuan-fit2cloud** [comment]
当前参数值很大值可以复现，下个版本优化

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
