### ISSUE TITLE
[BUG]环境配置中分模块配置了多个地址，调试接口的时候获取的URL跟请求头都是空的

### ISSUE THREAD

**Issue by cxh622** [metersphere/metersphere#3320]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.10.0-93f6870d
**Bug 描述**
简要描述您碰到的问题
环境配置中按模块配置了多个地址，调试接口的时候获取的URL跟请求头是空的
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84970914/119978908-cc8e5880-bfec-11eb-8c80-450ebf00fa95.png)
![image](https://user-images.githubusercontent.com/84970914/119978976-e29c1900-bfec-11eb-8631-f9b720e27849.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您的接口定义信息和环境信息导出提供一下吗

**Comment by memoriesoffkid** [comment]
6.4下午在demo网站成功复现,明确为用例无法匹配启用条件为模块的http配置,接口定义可以正常匹配到
尝试从接口定义模块通过测试-》另存为新用例的步骤添加或者直接在case列表新建用例即可复现

**Comment by cxh622** [comment]
抱歉，没留意邮件，能复现就好，忘贵公司能及时修复这个问题，谢谢！



***@***.***
 
发件人： memoriesoffkid
发送时间： 2021-06-04 22:49
收件人： metersphere/metersphere
抄送： cxh622; Author
主题： Re: [metersphere/metersphere] [BUG]环境配置中分模块配置了多个地址，调试接口的时候获取的URL跟请求头都是空的 (#3320)
6.4下午在demo网站成功复现,明确为用例无法匹配启用条件为模块的http配置,接口定义可以正常匹配到
尝试从接口定义模块通过测试-》另存为新用例的步骤添加或者直接在case列表新建用例即可复现

**Comment by zyyfit** [comment]
您好，新版修复了case和引用环境的问题，您看看最新版还有这个问题吗？
