### ISSUE TITLE
[FEATURE]表单格式的参数建议参考jmeter支持多行复制粘贴

### ISSUE THREAD

**Issue by cxh622** [metersphere/metersphere#3321]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/84970914/119979449-8f769600-bfed-11eb-888a-904d837da91d.png)

**请描述你建议的实现方案**
参考jmeter的实现方式
![image](https://user-images.githubusercontent.com/84970914/119979570-b5039f80-bfed-11eb-9984-01d0caee6510.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化
