### ISSUE TITLE
[FEATURE]JSON-文档结构校验保留提交的内容和它的正则表达式修改

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#33213]
### MeterSphere 版本

3.2

### 请描述您的需求或者改进建议

JSON-文档结构校验保留提交的内容，以备后续修改，
它的正则表达式修改，在导入的时候让用户选择，是否正则表达断言

**Comment by luty2018** [comment]
不好意思， 短期内规划不上。
