### ISSUE TITLE
[BUG]2个全局断言成功+1个接口用例本身断言失败 = 最终结果为成功

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33222]
### 联系方式

727803257@qq.com

### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

如图所示。
![图片1](https://github.com/user-attachments/assets/151f4c4b-170f-4214-95bd-ff894f3ffb63)

### 重现步骤

无。

### 期待的正确结果

无。

### 相关日志输出

```shell
无。
```

### 附加信息

无。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
