### ISSUE TITLE
[BUG]接口测试：场景自动化，循环控制器下有条件控制器时，接口请求提取变量值的显示有误

### ISSUE THREAD

**Issue by llzhou1229** [metersphere/metersphere#33227]
### 联系方式

llzhou@wisedu.com

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

次数循环控制器--条件控制器--接口请求
场景是：循环取需要创建的组织机构，当组织机构不存在时，需要创建。
判断机构存不存在时，需要提取查询机构的名称是否存在，在提取机构名称时，控制台显示的提示变量值有误，不同的循环显示的提示值是一样的。

### 重现步骤

正常返回详情：![image](https://github.com/user-attachments/assets/60e26041-a379-414b-a811-fc9ee10bbcb8)
提取的值回显为：![image](https://github.com/user-attachments/assets/fb3cd1dd-964f-452d-a53e-c00db5002ae7)
脚本日志打印输出：![image](https://github.com/user-attachments/assets/5f35f223-6cce-4e6b-82a3-4804cf55dc5b)

### 期待的正确结果

提取的值与实际返回的变量值一致

### 附加信息

https://github.com/user-attachments/assets/a09c5f53-38e8-478c-809c-ada85960c3f0

**Comment by 13290445582** [comment]
您好，创建了一个次数循环控制器--条件控制器--接口请求场景，未复现到该问题，可导出您的场景提供下。

**Comment by llzhou1229** [comment]
https://github.com/user-attachments/assets/e4368640-c378-4fdb-959c-16941da46b00


https://github.com/user-attachments/assets/f17b1dce-c5c8-4325-ba89-b280c09c70e0

**Comment by llzhou1229** [comment]
补充：场景变量的csv文件是引用的文件管理中的csv文件，使用次数循环读取csv文件行数据，然后判断csv文件中deptName值存不存在，存在就提取名称和id（名称使用正则提取，id使用jsonpath提取），不存在则创建；提取后控制台打印提取的日志值是正确的，是返回的response里对应 的值，但在”提取“tab页中，显示的值一直是同一个。

https://github.com/user-attachments/assets/bab2c5e2-7b6d-42a3-a339-ea62a008ab26

**Comment by 13290445582** [comment]
感谢您的协助，已经将问题反馈给开发人员，待确认后给您回复。

**Comment by 13290445582** [comment]
您好，在提取变量时，当前值应保留在上下文中。在第一次循环到请求时，获取到的值将是第一个值；如果后续请求没有提取到新值，则变量仍然保留为第一个值，以此类推。有后续可继续反馈。可检查下正则的写法是不是匹配的指定值未匹配到。
