### ISSUE TITLE
[FEATURE]希望断言能支持过滤失败的字段

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#33238]
### MeterSphere 版本

3.2

### 请描述您的需求或者改进建议

希望断言能支持过滤失败的字段

原因：断言内容可能非常多，修改中需要把失败的字段断言挑出来，反正需要翻特别长的内容去看

**Comment by luty2018** [comment]
这个功能我们会在v3.5支持

**Comment by 13290445582** [comment]
您好，V3.5已实现该需求，请升级。
