### ISSUE TITLE
[FEATURE] 希望可以增加用例名称的默认列宽

### ISSUE THREAD

**Issue by Jinpeng07** [metersphere/metersphere#33239]
### MeterSphere 版本

v3.2.0-89e02f6f

### 请描述您的需求或者改进建议

测试用例模块，用例名称列默认列宽太短，无法看全用例名称，希望可以增加默认列宽

**Comment by Hyyfit** [comment]
感谢反馈，这里我们会优化成 “调整了列宽后，记住用户的操作”，可以关注后续的版本发布。
