### ISSUE TITLE
[FEATURE]测试计划执行推送太多的微信机器人消息，容易造成炸群。

### ISSUE THREAD

**Issue by warmmilk** [metersphere/metersphere#3324]
**请描述您的需求或者改进建议.**
当前v1.10.0的测试计划定时任务，按条执行成功后推送消息，当关联的用例较多的情况下，消息推送的太多，容易造成炸群。

**请描述你建议的实现方案**
测试计划的定时任务，建议执行之后只推送一条消息。

**Comment by xulinde** [comment]
您可以设置事件，比如只有执行成功/失败再发通知
