### ISSUE TITLE
[FEATURE]在“提取参数”区域里建议新增1个列表展示字段“参数中文名称”

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33245]
### MeterSphere 版本

v3.2.0-89e02f6f

### 请描述您的需求或者改进建议

能否加一个列表展示字段比如为”参数中文名称”，这样就能直观看出来这个参数名称对应的中文含义是什么了。
![Uploading 新增1个列表展示字段.png…]()

**Comment by XiamenHongjingsheng** [comment]
![新增1个列表展示字段](https://github.com/user-attachments/assets/ac3141f4-380a-475a-92a3-306ac677e6ed)

**Comment by luty2018** [comment]
那就加一个描述字段吧

**Comment by XiamenHongjingsheng** [comment]
> 那就加一个描述字段吧

谢谢作者大大！

**Comment by 13290445582** [comment]
您好，V3.5已实现该需求，请升级。
