### ISSUE TITLE
[BUG]原服务器上的MS场景导入新部署MS平台上，对导入的场景配置机器人消息，会导致定时任务执行后，发送不出消息

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#3325]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10版本

**Bug 描述**
原服务器上的MS场景导入新部署MS平台上，对导入的场景配置机器人消息，会导致定时任务执行后，发送不出消息
注：服务器迁移后，将原服务器的场景导入新部署的场景，配置定时任务 发不出信息（可能和模板中取不到创建人字段有关）

**Comment by zyyfit** [comment]
您好，请问是从哪个版本导出的数据呢

**Comment by 2115055005** [comment]
1.093版本

**Comment by 2115055005** [comment]
> 您好，请问是从哪个版本导出的数据呢

1.093
