### ISSUE TITLE
[FEATURE]接口定时任务，现有机器人信息过于累赘，且内容拥挤，只需展示展示关键信息就好

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#3326]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
接口测试定时任务通知
任务场景：XXXXX
执行环境：xxxxxxx
执行结果：成功/失败（2021-05-28 08:48:42）
请点击下面链接查看测试报告
http://XXXXXXXX/#/api/automation/report/view/35f82f4e-97df-4821-bbbc-c8739600242c

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下

**Comment by 2115055005** [comment]
> 感谢反馈，后面版本可以优化下

收到 多谢

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/3327
