### ISSUE TITLE
[FEATURE]希望不要限制创建“脚本操作”的个数

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33291]
### MeterSphere 版本

v3.2.0-89e02f6f

### 请描述您的需求或者改进建议

具体内容看截图里的文案描述哦。
![图片1](https://github.com/user-attachments/assets/67081f26-d295-4ae0-8f48-9abfd7ec1ed1)

**Comment by luty2018** [comment]
原来还有这样的场景， 那我们后续放开限制。

**Comment by luty2018** [comment]
已放开， 升级到v3.5 哈
