### ISSUE TITLE
[BUG][Highest]因业务需要beanshell断言，编写后在jmeter测试正常，meterSphere平台不生效。

### ISSUE THREAD

**Issue by zhangxia11** [metersphere/metersphere#3329]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.11

**Bug 描述**
简要描述您碰到的问题
beanshell断言，编写后在jmeter测试正常，meterSphere平台不生效。

**Bug 重现步骤**
1.  新建请求
2. 断言方式选择脚本--》beanshell断言，断言脚本如下：
beanshell断言脚本如下：
int a = 10;
log.info("====================" + a);
if(a == 10){
    Failure = false;
}
else
{
    Failure = true;
    FailureMessage = "beanshell断言失败.";
}

3. 执行用例场景
4. 查看断言结果

**期待的正确结果**
正确情况下应该是什么样的？
正确进行beanshell断言

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，您可以先用下面这种写法，后续我们会优化这个问题的
AssertionResult.setFailure(true);
AssertionResult.setFailureMessage("beanshell断言失败.");

**Comment by wangzhen-fit2cloud** [comment]
你好，我们使用的并不是 beanshell 断言，而是 JSR223 断言，与 JMeter 的表现是一致的。
如上述回复，建议修改成 AssertionResult.setFailure(true) 这样的形式。
