### ISSUE TITLE
[FEATURE] 期待所有请求方式添加body，这个对于真正编写用例至关重要，PostMan也是这样的，希望对齐

### ISSUE THREAD

**Issue by Jacksonluang** [metersphere/metersphere#333]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/22166503/92068687-27867c80-edda-11ea-8b40-720ad573524c.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已增加该功能
