### ISSUE TITLE
[BUG]【接口测试】导入 swagger 接口，body 是有值的，但是没导入进来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#33300]
### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

【接口测试】导入 swagger 接口，body 是有值的，但是没导入进来

### 重现步骤

【接口测试】导入 swagger 接口，body 是有值的，但是没导入进来
![f5f1aaa9-a263-4d7a-99d2-633d212fd015](https://github.com/user-attachments/assets/1ff51c56-e9cb-4a06-b349-aa9a3760b0ac)
![b7dcac5f-3ee0-4337-b971-17fba260b13a](https://github.com/user-attachments/assets/511b7642-35bd-4788-8e4e-946d965b6a44)

**Comment by youliyuan-fit2cloud** [comment]
你好，swagger文件发一下吧，方便我们复现问题。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
