### ISSUE TITLE
[BUG]拿存在的一个接口名称A进行搜索，但搜索结果为空

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33301]
### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

具体内容看截图哦！

### 重现步骤

是必现的问题。

**Comment by XiamenHongjingsheng** [comment]
具体截图补充如下：
![图片1-1](https://github.com/user-attachments/assets/e6beca6a-186d-4879-ab78-675c7e32e21a)
![图片1-2](https://github.com/user-attachments/assets/1fb6b095-6a52-431c-9593-6a2f25cfdf82)

**Comment by youliyuan-fit2cloud** [comment]
你好，左上角的搜索是搜索模块名称，接口名称搜索在右边。

**Comment by youliyuan-fit2cloud** [comment]
<img width="511" alt="image" src="https://github.com/user-attachments/assets/039a3c92-0514-4138-a7ca-1c01d9947fa1">
全部接口中选中 关闭隐藏和展开全部接口
