### ISSUE TITLE
[BUG] 项目TCP接口编辑时无法展示参数页面

### ISSUE THREAD

**Issue by tangw-github** [metersphere/metersphere#3331]
**MeterSphere 版本**
v1.10.0-lts-93f6870d

**Bug 描述**
项目TCP接口编辑时无法展示参数页面

**Bug 重现步骤**
1.  编辑TCP接口，选择ESB

**期待的正确结果**
如demo环境可打开参数配置界面

**截图**
![image](https://user-images.githubusercontent.com/8164903/120133873-80673200-c1ff-11eb-8f9f-7090a7eea495.png)

**Comment by tangw-github** [comment]
为什么不回复喃，难道没有复现吗？  1.10

**Comment by wangzhen-fit2cloud** [comment]
你好，该问题会在 v1.10.1 修复。

**Comment by xulinde** [comment]
v1.10.1 版本已修复
