### ISSUE TITLE
[BUG]  UI模版在前置脚本当中使用场景变量，赋值到 "输入操作" 当中，赋值失败。

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#33314]
### MeterSphere 版本

V2.10.19

### 使用外置数据库

否

### 问题描述

1. 创建UI场景，比如访问百度:
2. 设置一个场景变量 
3. 在输入操作当中的前置脚本使用变量，并且赋值给返回值。
4. 执行，页面截图拿不到值。报：arguments[0]
![image](https://github.com/user-attachments/assets/7467a115-8284-494b-840a-b72f9577d4dc)

![image](https://github.com/user-attachments/assets/e1ad3454-cb0f-40bb-831c-0349afb8b5a7)

![image](https://github.com/user-attachments/assets/d1ae2d70-e14d-489a-bc56-b22b3ac0f2cf)

### 重现步骤

同上

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
你好，经再次确认，不是缺陷，是前置脚本需要修改，参考如下：
var url = ${name};

return url ;
