### ISSUE TITLE
[BUG]接口测试请求地址域名中带有特殊字符@时无法正确识别

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#33319]
### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

当接口请求地址域名中带有@特殊字符时，无法识别，如下图所示：采用测试地址https://cesfdasafd@fadfasfaerfe.com/test123，使用快捷调试的方式，可看到会将域名分割。
<img width="1044" alt="截屏2024-09-26 上午10 45 38" src="https://github.com/user-attachments/assets/f2cdad4b-896e-4537-8133-b1ae28062310">

### 重现步骤

1.准备一个MeterSphere v2.10.19-lts环境
2.进入接口测试模块，打开快捷调试
3.将请求地址https://cesfdasafd@fadfasfaerfe.com/test123填入，采用post
4.执行请求

### 期待的正确结果

能正确识别请求地址域名

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。全路径已经处理过了，环境暂不处理了，使用正常域名就可以；域名带特殊字符不多。
