### ISSUE TITLE
[FEATURE] 优化建议：脑图快捷键添加步骤、用例、模块等，都需要再快捷键之后 再重新点下节点才可以操作，交互麻烦，期望直接可以操作，而不是再点击一下

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#33322]
### MeterSphere 版本

3.3

### 请描述您的需求或者改进建议

优化建议：脑图快捷键添加步骤、用例、模块等，都需要再快捷键之后 再重新点下节点才可以操作，交互麻烦，期望直接可以操作，而不是再点击一下

### 请描述你建议的实现方案

期望增加的脑图节点，可以直接操作，而不是再点击一下
![image](https://github.com/user-attachments/assets/442f8ac5-c087-4501-b035-a7c206b602d4)

**Comment by luty2018** [comment]
这个可以和莹莹沟通一下你的目前觉得不顺畅的地方
