### ISSUE TITLE
[BUG] 脑图步骤编辑，回车步骤描述后面追加了步骤描述

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#33324]
### MeterSphere 版本

3.3

### 使用外置数据库

否

### 问题描述

问题：脑图步骤编辑，回车步骤描述后面追加了步骤描述

### 重现步骤

问题：脑图步骤编辑，回车步骤描述后面追加了步骤描述

![0d5ba63b585ffd258a7f575df17af50](https://github.com/user-attachments/assets/684b1501-3395-4168-8b1a-6c86774fe1a7)

### 期待的正确结果

回车应该 步骤描述应该是同级节点，目前位置很奇怪

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
