### ISSUE TITLE
[FEATURE] 脑图， 快捷键增加一个节点，用例、模块可以使用快捷键shift+M 这样

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#33323]
### MeterSphere 版本

3.3

### 请描述您的需求或者改进建议

脑图， 快捷键增加一个节点，用例、模块可以使用快捷键shift+M 这样

目前是caps lock  + 大写，常用快捷键是组合键操作。

**Comment by luty2018** [comment]
啥意思， 现在增加用例和模块都已经支持快捷键操作了。是说要改成按两个键吗？

**Comment by xhy12** [comment]
windows 现在是分的两步， 先锁定 再输入字母m 操作两次
期望是连着直接shift +m  一步操作完成。 主要反馈点是操作上的使用体验，不是说要一定要改成两个键位

**Comment by luty2018** [comment]
已支持。
