### ISSUE TITLE
[BUG]测试form-data接口上传文件时，设置文件content-type 后未生效

### ISSUE THREAD

**Issue by wmguoo** [metersphere/metersphere#33334]
### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

在测试form-data接口上传文件时，设置文件content-type 后未生效，导致接口无法调通。
![0E88626A-ACFD-4213-A3C3-A64C5E24643E](https://github.com/user-attachments/assets/1d450402-2e16-4af3-89e1-8aecb9a9088d)

### 重现步骤

1. 填写接口路径，设置请求体为form-data 格式；
2. 参数类型选择为 file, 上传本地文件；
3. 设置参数的content-type 为excel文件类型 application/vnd.openxmlformats-officedocument.spreadsheetml.sheet；
4. 点击服务器调试，查看实际请求body中的content-Type 字段，与设置不符。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
