### ISSUE TITLE
[BUG]切换项目时项目管理下的项目与权限下项目基本信息显示错误

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#33333]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

切换项目时项目管理下的项目与权限下项目基本信息显示错误

### 重现步骤

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/2a078db7-8ead-4c24-bb11-c5992081b35c">

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
