### ISSUE TITLE
[BUG]【测试跟踪】全选所有测试计划，批量执行未生效

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#33336]
### MeterSphere 版本

v2.10.19

### 使用外置数据库

否

### 问题描述

全选所有的测试计划，点击批量执行，选择并行，点击确定，页面执行成功，但没有报告

### 重现步骤

1、进入测试跟踪-测试计划页面
2、全选所有的测试计划，比如总共有11个测试计划，全部选中
3、点击批量执行，选择并行
4、点击确定
5、查看是否生能报告

### 期待的正确结果

批量执行能正常生成报告

### 附加信息

1、复现动态图片
![bycpo-068hl](https://github.com/user-attachments/assets/e9f4c92a-324a-4026-ac7f-a6bc07d0b5ba)

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
问题已修复，请升级最新版本使用。
