### ISSUE TITLE
[BUG]场景A中引用了指令，场景B中复制或引用场景A，修改指令的网页url，没有自动同步到场景B中

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33337]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.19-lts

### 使用外置数据库

否

### 问题描述

场景A中引用了指令A，场景B中复制或引用场景A，修改指令A的网页url，没有自动同步到场景B中

### 重现步骤

1、场景A中引用了指令
![image](https://github.com/user-attachments/assets/802425d3-33f4-4ce1-81a5-d888433e1905)
2、场景B中复制或引用场景A
![image](https://github.com/user-attachments/assets/4f3b0c6a-6c0d-4377-8892-06feba6f7379)
3、修改指令的url
![image](https://github.com/user-attachments/assets/4a593e11-cab9-4658-befd-db7c0fb14bf7)
4、执行场景B，结果还是访问之前的url
![image](https://github.com/user-attachments/assets/054c9c3d-10d0-4f0a-9a84-b3d992c367bb)

### 期待的正确结果

应该自动同步新的url

**Comment by 13290445582** [comment]
您好，本地未复现该情况，麻烦提供下复现环境或可复现场景。

**Comment by linfengjjj** [comment]
环境：https://qa-release.fit2cloud.com/
工作空间：南区MS成功组
项目：0802演示
复现操作：执行“场景B”，可以看到报告里截图是淘宝，但是我指令里地址是https://qa-release.fit2cloud.com/
这个问题需要执行，肉眼看起来是同步过来了的，执行后看报告才会发现没有同步
![image](https://github.com/user-attachments/assets/5cab9f81-5aa0-4cf8-aa16-dfde6d496dce)

**Comment by 13290445582** [comment]
问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
