### ISSUE TITLE
[BUG]测试计划报告按照执行状态搜索的状态选项展示不全

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#33338]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

测试计划报告按照执行状态搜索的状态选项展示不全

### 重现步骤

如下图，应该有未执行的状态在列表中用于搜索：
![image](https://github.com/user-attachments/assets/82bcd41c-8e88-4a26-b767-6a23e9da49cc)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
