### ISSUE TITLE
[BUG]在特定按钮的操作下，控制台区域里的底部日志展示不全

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33339]
### MeterSphere 版本

v3.3.0-9cc056be

### 使用外置数据库

否

### 问题描述

具体内容看截图里的文案描述哦。
![图片7-1](https://github.com/user-attachments/assets/75e69b24-4937-4686-879c-d6029b410053)

### 重现步骤

必现，

**Comment by XiamenHongjingsheng** [comment]
补充一张截图~
![图片7-2](https://github.com/user-attachments/assets/c4482221-dba6-411e-ba44-aedaa470d539)

**Comment by youliyuan-fit2cloud** [comment]
你好，有没有可能 滑动右侧的滚动条就好了。
![image](https://github.com/user-attachments/assets/4f13c814-6acf-4100-84af-59bb884f4f76)

**Comment by youliyuan-fit2cloud** [comment]
> 你好，有没有可能 滑动右侧的滚动条就好了。 ![image](https://private-user-images.githubusercontent.com/54612864/371819063-4f13c814-6acf-4100-84af-59bb884f4f76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMwNDMsIm5iZiI6MTcyODM4Mjc0MywicGF0aCI6Ii81NDYxMjg2NC8zNzE4MTkwNjMtNGYxM2M4MTQtNmFjZi00MTAwLTg0YWYtNTliYjg4NGY0Zjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMmU3ODY4NmQ5ZTRhOGJlOWY4NTUzYzAxM2NkODJjOTJjYzBiYzJkMWE0YTllNzBjYWQ1MmFhODM3MzEwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lS3msJz8YO2X2DBhHA8su90tcyPyW-FnihgIXW24_Rs)

@XiamenHongjingsheng

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
