### ISSUE TITLE
[QUESTION]V3版本的（最新版本）的公开API地址在哪里

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#33353]
### 请描述您的问题

V3版本的（最新版本）的公开API地址在哪里

**Comment by hujirong521317** [comment]
我这边接口请求登录接口， login_data = {
            "username": ' XXX',
            "password": 'XXX',
            "authenticate": "LOCAL"
        }
提示：{'success': False, 'message': '401 UNAUTHORIZED "Not found session, Please Login again."', 'data': None}
所以我还需要什么header头吗，是这个吗x-auth-token:
那这个参数又是哪里来的

**Comment by fit2-zhao** [comment]
<img width="915" alt="image" src="https://github.com/user-attachments/assets/4a0dd395-dc83-41be-9e9a-b9ef3ec6eccc">

<img width="928" alt="image" src="https://github.com/user-attachments/assets/25f4a00e-c41d-4a99-baf5-b92c0f14ca77">


参照这个参数试试
