### ISSUE TITLE
[BUG]退出用户、切换项目等不触发网页自动刷新(要手动刷新一下)

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33363]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/936f40a3-8181-4e9f-9035-ff2732848b2a)

### 重现步骤

退出用户、切换项目等不触发网页自动刷新(要手动刷新一下)

### 期待的正确结果

触发自动刷新

**Comment by youliyuan-fit2cloud** [comment]
你好，切换项目时是指在默认页面“项目与权限”的信息不更新吗？-----该问题已知
"退出系统“还是登录状态？

**Comment by henbell2** [comment]
不是登录状态，网页元素都还在，点开弹框（比如用例导出）都是空的。手动刷一下，会回到登录首页

**Comment by henbell2** [comment]
”项目与权限“页，左上角切换项目，当前页项目信息不刷新，手动刷新一下，正常更新

**Comment by youliyuan-fit2cloud** [comment]
> ”项目与权限“页，左上角切换项目，当前页项目信息不刷新，手动刷新一下，正常更新

这个已致问题，下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
> 不是登录状态，网页元素都还在，点开弹框（比如用例导出）都是空的。手动刷一下，会回到登录首页
是打开了多个tab页签，其中一个退出登录，其他tab页 可以操作 的意思吗？方便的话录个视频，感谢。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
