### ISSUE TITLE
[BUG]同一个用户，上传文件列表无法关联到文件管理中已上传的文件。

### ISSUE THREAD

**Issue by wmguoo** [metersphere/metersphere#33361]
### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/f328405e-0a73-4237-99ea-5994300bf78a)

![image](https://github.com/user-attachments/assets/9e224b20-29b2-4eab-9667-8865a7136f79)

### 重现步骤

1. 权限配置中 对当前用户 所在组仅授予 接口测试和项目管理 两个菜单权限；
2. 在文件管理中上传文件；
3. 进入接口定义中 选择post接口参数为 file上传，选择关联文件；
4. 查看文件列表（此时无法显示已上传的文件，但是却能看到统计数据）

### 期待的正确结果

能够正确显示已上传的文件列表

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题，只能临时使用本地文件上传了，或者开启测试用例模块的权限。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
