### ISSUE TITLE
[FEATURE]增加1个【重试控制器】（与循环控制器不同的是，只要最后1个是成功状态，则判定成功）

### ISSUE THREAD

**Issue by mengshuai85** [metersphere/metersphere#33368]
### MeterSphere 版本

v2.10.19-lts

### 请描述您的需求或者改进建议

现在有循环控制器，但是循环控制器下步骤中含有失败步骤，则最终结果是失败状态

实际上有一些 等待场景，比如一些服务执行需要等待一些时间，这时候会定时做一些 状态判断，如果服务正常了，再执行后续用例。
或者一些 超时任务，也需要循环去判断 接口状态，只要有1个成果，则停止，说明这个用例 ok了。

但是现在的 循环控制器 ，只要有失败步骤，整个测试场景都判定失败了。

现在处理方式是 增加等待控制，等20s等，但是 多了之后，比较浪费时间，不如每隔2s去判断一次，只要成果就向后执行，这样整个测试场景时间也会缩短一些。

**Comment by luty2018** [comment]
不好意思，暂时没有这个规划。
