### ISSUE TITLE
[BUG]导出pdf报告时，用例并不是筛选后的list，把无关的用例也导出到pdf报告里了

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33362]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/108722e4-cfe2-413b-99dd-a3d70fa4ef53)

### 重现步骤

测试报告中筛选用例，然后导出pdf测试报告

### 期待的正确结果

导出有用的测试用例，非全部测试用例

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，当前版本导出报告会确实是导出全部数据，不会根据筛选结果导出。如果有实际需求，请提个Feature，感谢理解和支持～
