### ISSUE TITLE
[BUG]用例评审记得之前说评审人可以是空，以识别哪些用例还未指派，但是在创建评审计划的时候，默认评审人又是必填项，麻烦确认下；左侧按模块/子模块的复选框，以模块维度先择用例集，也没加，参考

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33365]
### 联系方式

henbell2@163.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/58b81ffb-32aa-4097-a61f-b993be2396a2)

### 重现步骤

用例评审记得之前说评审人可以是空，以识别哪些用例还未指派，但是在创建评审计划的时候，默认评审人又是必填项，麻烦确认下

### 期待的正确结果

默认评审人可以是空，以便可以识别在指派评审的时候可以识别哪些还未指派评审

**Comment by youliyuan-fit2cloud** [comment]
你好，创建评审时，默认评审人是必填项。

**Comment by henbell2** [comment]
OK！
