### ISSUE TITLE
[BUG]测试计划-场景用例的顺序调整，提示成功但是实际没变。

### ISSUE THREAD

**Issue by BIGMK365** [metersphere/metersphere#33372]
### 联系方式

1620736018@qq.com

### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

测试计划-场景用例的顺序调整，提示成功但是实际没变。

### 重现步骤

![image](https://github.com/user-attachments/assets/99881a20-d2f3-4dc6-a0d6-0444ebe2be2b)

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题在v3.3 中已修复。
