### ISSUE TITLE
[BUG]【测试用例】选择用例点击剪切，在其他模块下点击粘贴，数据没有粘贴过来

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#33375]
### MeterSphere 版本

v3.3

### 使用外置数据库

否

### 问题描述

【测试用例】选择用例点击剪切，在其他模块下点击粘贴，数据没有粘贴过来。

### 重现步骤

【测试用例】选择用例点击剪切，在其他模块下点击粘贴，数据没有粘贴过来。
![image](https://github.com/user-attachments/assets/31dbf47d-a24b-4168-8a6c-8e9dceaf13cc)
![image](https://github.com/user-attachments/assets/7a09eb75-58a7-428b-805a-ba10afa06aa4)

**Comment by youliyuan-fit2cloud** [comment]
你好，已复现，使用快捷键没问题，先用快捷键吧。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。非https协议浏览器限制访问剪贴板，增加了此类场景的错误提示。
