### ISSUE TITLE
[QUESTION]能否提供v2.x版本的docker安装方式？

### ISSUE THREAD

**Issue by ansonliao** [metersphere/metersphere#33376]
### 请描述您的问题

通过docker安装了最新v3.x版本（命令：`docker run -d -p 8081:8081 --name=metersphere -v ~/.metersphere/data:/opt/metersphere/data cr2.fit2cloud.com/metersphere/metersphere-ce-allinone`），但没有了UI测试方面的内容，因为我们对这块需求比较重，所以请问能否提供v2.x（最新lts的）docker安装的方式？
谢谢！

**Comment by liuruibin** [comment]
v3是一个全新的产品，还没有性能测试和UI测试相关的功能呢。如果需要使用这两个功能的话建议采用v2的安装方式https://metersphere.io/docs/v2.x/
