### ISSUE TITLE
[BUG]次数循环嵌套后读取csv文件内容时，内循环重新迭代时未重置从csv第一行读取内容，外循环迭代时未根据上一次外循环迭代的行数继续读取csv内容，取的是内循环迭代后的行值。

### ISSUE THREAD

**Issue by llzhou1229** [metersphere/metersphere#33377]
### 联系方式

zll_881229@163.com

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

次数循环嵌套，外循环与内循环在读取csv文件内容行时相互影响了，内循环时没有重置从csv第一行开始读取，是接着外循环的行数读取的csv内容，同样外循环迭代也是接着内循环迭代后读取的csv内容。
![image](https://github.com/user-attachments/assets/fb6b7b2d-5285-416d-b0df-f5c3b553137c)

### 重现步骤

https://github.com/user-attachments/assets/4c3cc3f6-8c5b-48d1-a82c-4c1d7802d5a4

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这个问题已知问题，v2版本目前暂时没有解决方案，建议使用v3版本，感谢理解和支持。
