### ISSUE TITLE
[BUG] MeterSphere提交工单到jira,文字描述部分异常

### ISSUE THREAD

**Issue by shane-hub** [metersphere/metersphere#33381]
### MeterSphere 版本

v3.0.1-080e6767

### 使用外置数据库

否

### 问题描述

MeterSphere输入文本到jira异常

### 重现步骤

MeterSphere提交工单到jira

### 期待的正确结果

正常

### 附加信息

<img width="493" alt="image" src="https://github.com/user-attachments/assets/6ec98d6f-86b1-47ad-bd9d-c8ef091ae840">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，当前实现确实是这样，后续版本会优化。

**Comment by shane-hub** [comment]
![image](https://github.com/user-attachments/assets/22648f1c-c30b-437a-9afe-ab9ed4048c4c)
更新v3.4.0版本问题仍然存在

**Comment by youliyuan-fit2cloud** [comment]
是用的最新jira插件吗？不是的话更新下插件试试吧。

**Comment by shane-hub** [comment]
metersphere-jira-plugin-3.0.0-beta 用的这个版本插件

MatataYou ***@***.***> 于2024年11月4日周一 17:25写道：

**Comment by shane-hub** [comment]
如果有更新的插件,可以发我么,感谢

Rio ***@***.***> 于2024年11月4日周一 17:28写道：

**Comment by fit2-zhao** [comment]
可以通过 [插件应用市场](https://apps.fit2cloud.com/metersphere) 下载，或者联系我们的支持人员获取最新插件。

**Comment by youliyuan-fit2cloud** [comment]
已修复，在v3.4版使用最新的JIRA插件

**Comment by shane-hub** [comment]
问题并未解决,最新插件就是出问题的3.0beta插件

MatataYou ***@***.***> 于2024年11月4日周一 17:43写道：

**Comment by shane-hub** [comment]
未修复,已使用细心插件3.0beta版本

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/1acae5ae-2cdb-4521-a4bc-52f7d4414342)

请认真看下这个回复。。。

> 未修复,已使用细心插件3.0beta版本
