### ISSUE TITLE
[BUG] 测试计划，关联功能用例，按照标签搜索，连续关联两次用例 第一次3条第二次4条最终展示了29条

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#33397]
### MeterSphere 版本

3.3

### 使用外置数据库

否

### 问题描述

测试计划，关联功能用例，按照标签搜索，连续关联两次用例 第一次3条第二次4条最终展示了29条
![关联3 条 +4 条，最终有27条](https://github.com/user-attachments/assets/cdb3e5d0-d883-4c82-8c49-4f82760ddafa)

### 重现步骤

1、测试计划，关联功能用例，按照标签搜索，第一次3条，然后再次点击关联4条，
问题：第二次关联之后，总用例数为17条
数据不对

**Comment by xhy12** [comment]
按标签搜索翻页，选择用例关联 也会关联到多余的的用例

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
