### ISSUE TITLE
[FEATURE] 只安装node节点的机器，不用把其他服务的镜像pull 或者 load下来，浪费资源

### ISSUE THREAD

**Issue by xiangziyun2009** [metersphere/metersphere#334]
**请描述您的需求或者改进建议.**

只安装node节点的机器，不用把其他服务的镜像pull 或者 load下来，浪费资源

**请描述你建议的实现方案**
安装node节点的机器，只安装相关的服务，无关服务的镜像不用加载

**Comment by wangzhen-fit2cloud** [comment]
你好，目前是不会 pull 镜像的，只有离线包的时候是把所有需要的内容打包在了一个包里
