### ISSUE TITLE
[BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人

### ISSUE THREAD

**Issue by ythouc** [metersphere/metersphere#33403]
### MeterSphere 版本

v3.3

### 使用外置数据库

否

### 问题描述

缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人

### 重现步骤

1.集成禅道；
2.配置项目ID；
3.新增缺陷，“当前指派”未根据配置的项目ID显示对应人

### 期待的正确结果

根据配置的项目，显示禅道项目配置的团队人员

**Comment by youliyuan-fit2cloud** [comment]
你好，当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表有什么区别？不是全部还是不是当前项目的成员？

**Comment by ythouc** [comment]
您好：

    当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表中，不是全部成员也不是项目成员，只显示了部分成员，禅道插件版本是3.3.0，MS版本为3.3.0



***@***.***
 
发件人： MatataYou
发送时间： 2024-10-09 14:03
收件人： metersphere/metersphere
抄送： ythouc; Author
主题： Re: [metersphere/metersphere] [BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人 (Issue #33403)
你好，当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表有什么区别？不是全部还是不是当前项目的成员？

**Comment by 13290445582** [comment]
您好，请问所用禅道平台版本为多少，V3最低支持禅道v18.10版本。

**Comment by ythouc** [comment]
您好：

        禅道版本17.2



***@***.***
 
发件人： wangyicheng
发送时间： 2024-10-10 15:54
收件人： metersphere/metersphere
抄送： ythouc; Author
主题： Re: [metersphere/metersphere] [BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人 (Issue #33403)
您好，请问所用禅道平台版本为多少，V3最低支持禅道v16.5版本。

**Comment by 13290445582** [comment]
您好，暂时未复现这种情况，后续会继续关注测试环境是否会出现此情况，感谢理解。

**Comment by Halecoder** [comment]
> 您好： 当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表中，不是全部成员也不是项目成员，只显示了部分成员，禅道插件版本是3.3.0，MS版本为3.3.0 ***@***.*** 发件人： MatataYou 发送时间： 2024-10-09 14:03 收件人： metersphere/metersphere 抄送： ythouc; Author 主题： Re: [metersphere/metersphere] [BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人 (Issue #33403) 你好，当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表有什么区别？不是全部还是不是当前项目的成员？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

请问解决了吗，我ms v3.4.0，禅道v18.0，也遇到了当前指派人不全，展示部分人员，如何才能展示全部人员

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by ythouc** [comment]
您好：

    MS平台老师已复现该问题，等待后续版本吧



***@***.***
 
发件人： Halecoder
发送时间： 2024-11-07 21:44
收件人： metersphere/metersphere
抄送： ythouc; Author
主题： Re: [metersphere/metersphere] [BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人 (Issue #33403)
您好： 当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表中，不是全部成员也不是项目成员，只显示了部分成员，禅道插件版本是3.3.0，MS版本为3.3.0 @.*** 发件人： MatataYou 发送时间： 2024-10-09 14:03 收件人： metersphere/metersphere 抄送： ythouc; Author 主题： Re: [metersphere/metersphere] [BUG]缺陷集成至禅道，新增缺陷时“当前指派”未根据配置的项目ID显示对应人 (Issue #33403) 你好，当前集成的zentao项目成员列表和MeterSphere系统里面获取的列表有什么区别？不是全部还是不是当前项目的成员？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>
请问解决了吗，我ms v3.4.0，禅道v18.0，也遇到了当前指派人不全，展示部分人员，如何才能展示全部人员

**Comment by Halecoder** [comment]
打扰了，请问这个问题修复了吗，我看有些PR好像已经合并了

**Comment by 13290445582** [comment]
您好，本次要发布的v3.5版本修复了这个问题，等待发布后升级即可。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
