### ISSUE TITLE
[BUG]对接jira获取的jira账号不全

### ISSUE THREAD

**Issue by shane-hub** [metersphere/metersphere#33404]
### MeterSphere 版本

v3.0.1-080e6767

### 使用外置数据库

否

### 问题描述

对接jira获取的jira账号不全,jira有30个账号,metersphere只能获取十几个
jira插件版本3.0.0-beta

### 重现步骤

对接jira获取的jira账号不全,jira有30个账号,metersphere只能获取十几个

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试环境没有出现这个问题，账号列表是集成的jira项目Key对应的账号吗？请将项目管理-应用设置的缺陷管理-集成jira配置参数发一下？再查看下Jira项目中账号列表。感谢～

**Comment by shane-hub** [comment]
按照提示的操作填写的关键字，查看jira账号列表确实不同步

MatataYou ***@***.***>于2024年10月9日 周三14:01写道：

**Comment by shane-hub** [comment]
Rio ***@***.***>于2024年10月9日 周三16:27写道：

**Comment by 13290445582** [comment]
您好，请问所用jira平台的版本是多少？非SaaS环境jira建议使用v9.x以下版本。已上传最新jira插件，使用新插件查看账号显示是否完整。
[metersphere-jira-plugin-3.1.0-jar-with-dependencies.jar.zip](https://github.com/user-attachments/files/17324423/metersphere-jira-plugin-3.1.0-jar-with-dependencies.jar.zip)

**Comment by shane-hub** [comment]
[image: image.png]
更新了插件,现在缺陷管理进不去了

wangyicheng ***@***.***> 于2024年10月10日周四 15:51写道：

**Comment by 13290445582** [comment]
您好，将MS也更新到最新版本。

**Comment by shane-hub** [comment]
v3.0.1-080e6767版本还需要更新么

wangyicheng ***@***.***> 于2024年10月10日周四 17:04写道：

**Comment by shane-hub** [comment]
[image: image.png]
最新版本就是3.0?


Rio ***@***.***> 于2024年10月10日周四 17:28写道：

**Comment by 13290445582** [comment]
您好，最新版本是v3.3.0

**Comment by shane-hub** [comment]
已经更新了系统版本及插件版本,但是问题仍存在

wangyicheng ***@***.***> 于2024年10月12日周六 10:09写道：

**Comment by 13290445582** [comment]
您好，暂时未复现这种情况，后续会继续关注测试环境是否会出现此情况，感谢理解。

**Comment by 13290445582** [comment]
您好，检查下所对接的jira项目内是否将所有的成员都添加进去了，若jira的项目内未添加到该成员，那么在metersphere对接到该项目后也是获取不到这些成员的，这样就可能会出现获取账号不全的问题。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
