### ISSUE TITLE
[BUG]测试计划报告的测试点展示顺序与测试计划规划页面的顺序不一致

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#33407]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

测试计划报告的测试点展示顺序与测试计划规划页面的顺序不一致

### 重现步骤

1、测试计划报告测试点展示的顺序
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/88cc2e53-edfb-4fe3-9aad-71b6b08894ed">

2、测试规划的展示顺序
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/010b2af9-c6c8-4cb5-bc15-00dd3a8764b4">

**Comment by 13290445582** [comment]
您好，已知问题，下个版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
