### ISSUE TITLE
[BUG]jenkins 中选择单个场景执行后，测试跟踪->报告中无此场景报告

### ISSUE THREAD

**Issue by shuyuntang** [metersphere/metersphere#3341]
**MeterSphere 版本**
V1.10.0

**Bug 描述**
jenkins 中选择单个场景执行后，测试跟踪->报告中无此场景报告
**Bug 重现步骤**
1. jenkins中配置单个场景，如景区资源测试
2. 构建执行
3. Metersphere中测试跟踪-》报告 中查看报告
**期待的正确结果**
可以查看刚选择并执行的测试场景报告

**截图**
![image](https://user-images.githubusercontent.com/66454651/120144932-5ae52300-c215-11eb-9ce3-f6f8fb16975f.png)
![image](https://user-images.githubusercontent.com/66454651/120144970-66d0e500-c215-11eb-9f4d-a5c05d7ae55f.png)

**Comment by zyyfit** [comment]
请问接口测试的报告中有执行结果吗？单独执行场景是不会在测试跟踪中生成报告的，会在接口测试中生成报告

**Comment by shuyuntang** [comment]
单个场景执行在接口测试下的测试报告中有结果
