### ISSUE TITLE
[FEATURE]接口测试导入postman文件时，能否提供版本的选项，并兼容其他版本的postman导入

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#33436]
### MeterSphere 版本

v2.10.17-lts

### 请描述您的需求或者改进建议

目前有客户反馈说接口测试导入postman文件时，由于测试人员比较多，并且使用的postman版本不统一，然而目前平台只支持Postman Collection v2.1 格式的 json 文件，有很多测试人员都没法使用该功能。

### 请描述你建议的实现方案

接口测试导入postman文件时，提供版本的选项，并兼容其他常见版本的postman导入

**Comment by luty2018** [comment]
Postman的新版本直接兼容旧版本的数据， 通过新版本可以导出为v2.1 格式。处理Postman文件版本差异的问题交给Postman来做是不是更合理呢。
