### ISSUE TITLE
[BUG]测试计划报告中返回的数据，无法选择按照json展示（偶现）

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#33430]
### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

打开测试计划报告，展示的数据有时候无法选择按照json展示<img width="1368" alt="image" src="https://github.com/user-attachments/assets/51b649c0-f77e-4a7b-acdd-f02ed215374d">

### 重现步骤

1.生成测试计划报告
2.进入测试计划报告后点击场景用例
3.切换响应体格式，有时候会选择不了
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/51b649c0-f77e-4a7b-acdd-f02ed215374d">

**Comment by 13290445582** [comment]
问题已复现，后续版本修复，待排期中。

**Comment by 13290445582** [comment]
您好，想到这个地方使用的是qiankun组件，内部加载了接口报告的页面，这个组件总有些奇奇怪怪的问题，这是技术选型的局限性，暂不处理感谢理解。
