### ISSUE TITLE
[BUG]接口自动化测试模块通过列表执行一个配置了循环控制器的自动化测试场景，开始后，刷新了列表或者退出登录重新登录，场景的STOP按钮状态丢失了，又变成了开始执行按钮，导致之前的执行不能停止了

### ISSUE THREAD

**Issue by Yo00Yo** [metersphere/metersphere#33433]
### 联系方式

425242756@qq.com

### MeterSphere 版本

 v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

前置条件：自动化场景里面配置了循环控制器，短时间内不会执行完毕。
接口自动化测试模块通过列表执行一个配置了循环控制器的自动化测试场景，开始后，刷新了列表或者退出登录重新登录后，场景的STOP按钮状态丢失了，又变成了开始执行按钮，导致之前的执行不能停止。

### 重现步骤

1、配置一个自动化测试场景
2、场景里面配置循环控制器，循环次数比较长，如：大于100次
3、通过列表点击执行
4、刷新列表或者退出登录重新登录
5、检查场景 是否还能停止之前执行的

实际结果：
不能停止执行中的场景，按钮状态丢失
重启服务与删除场景 也不能停止后台继续发请求

### 期待的正确结果

刷新或者退出登录后，执行中的场景状态不会丢失，能够手动操作停止

### 附加信息

![image](https://github.com/user-attachments/assets/8e832568-46e6-4fcd-8dcb-bb5b203e784b)
![image](https://github.com/user-attachments/assets/e2a1ff8c-51b1-4640-821b-7cb3d47440e7)
![image](https://github.com/user-attachments/assets/c191260d-5565-43e8-a1f4-d8ef3620e239)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/b195566b-ee67-458b-ae61-5274831f6155)

有个任务中心，场景用例列表中可以停止。

**Comment by youliyuan-fit2cloud** [comment]
如果还有其他问题请随时反馈，感谢～

**Comment by Yo00Yo** [comment]
在列表开启的执行,在列表刷新或者退出后,在任务中心里面是没有记录的,你可以试一下

**Comment by Yo00Yo** [comment]
> ![image](https://private-user-images.githubusercontent.com/54612864/375713141-b195566b-ee67-458b-ae61-5274831f6155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDUzMzQsIm5iZiI6MTcyOTE0NTAzNCwicGF0aCI6Ii81NDYxMjg2NC8zNzU3MTMxNDEtYjE5NTU2NmItZWU2Ny00NThiLWFlNjEtNTI3NDgzMWY2MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA2MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDY2MmVkNzM1ZGFmMzM2ZWYxODgzMGNmNzgxMDRhMGYzYWU2MWE1N2JiZDA1MzliZDMyMDRlOGY0Yzc2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q7hrEIcXC6Xw-N3W2F40qlcjOnUL8n8P6Hvc_tuAxOQ)
> 
> 有个任务中心，场景用例列表中可以停止。


在列表开启的执行,在列表刷新或者退出后,在任务中心里面是没有记录的,你可以试一下
