### ISSUE TITLE
[BUG]【接口定义】前置脚本中，设置环境参数，控制台报错；操作环境变量时，缺少一些选项（获取环境参数、删除环境参数、获取所有环境参数）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#3344]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/120150737-01352680-c21e-11eb-8fa0-3a03d9e8dbdc.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，截图中的脚本第三行应该是
```print("${my_name}");```
或
```print(vars.get("my_name"));```
与设置环境参数这一行无关。

**Comment by jhong123** [comment]
> 你好，截图中的脚本第三行应该是
> `print("${my_name}");`
> 或
> `print(vars.get("my_name"));`
> 与设置环境参数这一行无关。

好的  谢谢
