### ISSUE TITLE
[FEATURE]性能测试阶梯式加压参数设置后续是否有规划与jmeter对齐

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#33440]
### MeterSphere 版本

v2.10.17-lts

### 请描述您的需求或者改进建议

目前客户反馈说性能测试阶梯式加压参数设置比jmeter插件少，用户启动过程的方式不灵活，多种定义阶梯式不能实现。我们提出了一个解决方案：可以在jmeter写好脚本后导出，直接在ms导入。但是客户不接受这种方案。理由是：他们公司后续规划是不使用jmeter这些开源软件了，只能使用MS平台。

### 请描述你建议的实现方案

想咨询一下性能测试阶梯式加压参数设置后续是否有规划与jmeter对齐

**Comment by liuruibin** [comment]
没有计划
