### ISSUE TITLE
[BUG]导入swagger3.0版本错误

### ISSUE THREAD

**Issue by waitingSunset** [metersphere/metersphere#33458]
### MeterSphere 版本

3.3.0

### 使用外置数据库

是

### 问题描述

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/ac03d8f2-01ac-4af1-a0c0-10fc2f9e25a5">
系统错误的log ,  
该接口文档通过swaggger官网验证后, 导入ms 平台失败, 分析一下上述日志 , 应该是针对枚举类型没有做兼容处理, 

![1e10b38c-f453-47ba-94e0-2e8ccfb334e4](https://github.com/user-attachments/assets/b34373d1-bf0d-41c4-85a7-1a28ee00e288)

 后续请求 将上述enum改为[] , 成功导入

### 重现步骤

步骤如上, 该接口文档通过swaggger官网验证后, 导入ms 平台失败, 分析一下上述日志 , 应该是针对枚举类型没有做兼容处理,

**Comment by 13290445582** [comment]
您好，请提供下swagger文件。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
