### ISSUE TITLE
[BUG]【接口定义】编辑用例中的前置脚本，无法保存成功，需要重新编辑，再次保存才会成功

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#3345]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/120151120-786aba80-c21e-11eb-9497-41c8f42bf172.png)

**Comment by zyyfit** [comment]
您好，这边没有复现呢，是有什么其他复杂的操作吗？
