### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by waitingSunset** [metersphere/metersphere#33459]
### MeterSphere 版本

3.3.0

### 请描述您的需求或者改进建议

是否可以支持批量修改api的责任人 or(创建人)

### 请描述你建议的实现方案

1. 希望api 添加 负责人 的字段, 并支持批量修改负责人, 功能类似2.x版本

**Comment by luty2018** [comment]
感谢建议。接口也是有规划要做自定义字段的，可以关注我们的排期计划， 谢谢！
