### ISSUE TITLE
[BUG]接口后置提取的列表类型参数值，在环境变量中显示错误，无法引用到具体的值。

### ISSUE THREAD

**Issue by wmguoo** [metersphere/metersphere#33463]
### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

接口调测时，我在后置提取器中使用JSONPATH 表达式 提取了一个JSONArray，参数名称为dataList、并设置为环境变量，在调试控制台上可以正确看到提取的值。但是在项目管理>环境管理>环境变量中值却显示为 ${dataList}， 无法通过vars.get("dataList") 获取到提取的数据。 

### 重现步骤

![image](https://github.com/user-attachments/assets/3ddc858e-8993-40d8-a601-e09fbe626728)
![image](https://github.com/user-attachments/assets/b51ed112-b946-49d8-9434-6c1218f2f1b0)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请把复现场景再详细描述一下，例如接口定义，接口用例还是场景用例的后置脚本配置截图 ？

**Comment by wmguoo** [comment]
该问题在接口用例和场景用例中均有此问题，具体配置如下：
![image](https://github.com/user-attachments/assets/48f6fad9-c2cf-41cd-be3e-39b84db3c6a3)
查看控制台发现报错信息如下：
![image](https://github.com/user-attachments/assets/11b71edd-085e-4d2a-a54e-2ece50e15add)

**Comment by youliyuan-fit2cloud** [comment]
你好，因为提取的值是json，需要用户先手动写个脚本做转译处理，暂时不支持直接使用，感谢理解和支持。
