### ISSUE TITLE
【接口定义】请问升级到 1.10 后，没有看到「复制」按钮呢？（功能清单上，说有复制功能了）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#3346]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/11580681/120151383-c5e72780-c21e-11eb-8088-0eea4be6f9a7.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
这里有点问题，导致按钮消失了，1.10.1修复

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.10.1 已经解决该问题，可以升级到该版本。
