### ISSUE TITLE
[BUG]缺陷和禅道同步后，在ms中的图片无法再禅道中显示

### ISSUE THREAD

**Issue by zhonghuaen** [metersphere/metersphere#33488]
### 联系方式

交流群40，昵称：人民广场吃炸鸡

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

缺陷管理对接禅道后，在缺陷中插入的图片在禅道无法显示

### 重现步骤

新建缺陷，在缺陷重现步骤输出框结果下面插入图片，提交后禅道无法显示
![1728897736518](https://github.com/user-attachments/assets/92140159-925b-48cd-a060-06f6a39255d8)
![73da74713ecef42b7dc72c1f368db76](https://github.com/user-attachments/assets/1a1f2f5c-6952-4e27-b067-b9b5cc679185)

### 期待的正确结果

同步禅道后能显示出图片信息

**Comment by 13290445582** [comment]
您好，测试环境未复现该问题。MeterSphere V3版本对接禅道最低支持V16.5版本，低于V16.5的版本不会完美兼容，若使用版本低于V16.5建议升级，感谢理解与支持。

**Comment by zhonghuaen** [comment]
你好，禅道使用的是企业版8.12，企业版最新才10.6.1
![image](https://github.com/user-attachments/assets/9c24bf7d-8452-4cbe-bc39-da70b66ab8c7)

**Comment by 13290445582** [comment]
企业版8.12应该是没有问题的，上传图片后在metersphere平台查看正常嘛？是按照图中方式上传嘛？
<img width="836" alt="image" src="https://github.com/user-attachments/assets/2aa805c8-41f8-4974-beff-d2ed09fc11fa">

**Comment by zhonghuaen** [comment]
![image](https://github.com/user-attachments/assets/d13f383a-65ce-4d24-9129-96e52b3c58c6)
通过截图粘贴的在ms中能看见，禅道中看不到，通过插入图片(输入链接)禅道能看见，但是工作中提bug都是截图当前问题直接复制的

**Comment by zhonghuaen** [comment]
如同是通过插入图片的方式，插入是输入的链接，等于还需要将我的截图上传服务器后才能插入，有一点麻烦

**Comment by 13290445582** [comment]
您好，我们在开发时是使用的开源版禅道V18.10。对于企业版或者开源版的低版本可能并不完全兼容，建议先提升下企业版禅道道最新版本，看是否可以解决问题。

**Comment by zhonghuaen** [comment]
你们那边通过截图的方式而不是插入图片到缺陷内容中，然后在禅道能看见截图的图片吗

**Comment by 13290445582** [comment]
可以看到的，我们使用的是开源版V18.10版本，现在不能确定是不是版本导致的出现该问题。

**Comment by zhonghuaen** [comment]
我使用的是企业版8.12，使用插入图片的方式没问题，截图后禅道显示有问题，不知道后面能不能修复下，感谢

**Comment by zhonghuaen** [comment]
![image](https://github.com/user-attachments/assets/4549fb5f-7b9e-4611-9e06-df347a36cd0b)
禅道数据库的结果

**Comment by zhonghuaen** [comment]
![image](https://github.com/user-attachments/assets/ccb24b50-33c6-4721-b364-83190c6eab78)
ms数据库的数据，通过截图粘贴后的原始数据就是这种

**Comment by 13290445582** [comment]
您好，那可以将您的禅道环境提供下吗，我们本地连接下，没有与您对应的环境进行测试。

**Comment by zhonghuaen** [comment]
可以的，需要提供些什么数据

**Comment by 13290445582** [comment]
可以将图中连接禅道的信息发送至我的邮箱yicheng.wang@fit2cloud.com
![image](https://github.com/user-attachments/assets/fcdbaa93-0a14-4c57-8da9-dc7e1d95486f)

**Comment by zhonghuaen** [comment]
禅道信息已发送到邮箱

**Comment by 13290445582** [comment]
感谢支持，问题已反馈，后续版本修复。

**Comment by 13290445582** [comment]
插件已更新，已解决问题，issue关闭，感谢理解。
