### ISSUE TITLE
[BUG]在接口自动化测试报告详情页面，通过关键字搜索搜索不到存在的数据

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#33482]
### MeterSphere 版本

v2.10.19-lts-90463ffd

### 使用外置数据库

否

### 问题描述

作者您好，具体问题麻烦您抽空看下截图呢。
![问题1](https://github.com/user-attachments/assets/989bb235-18fb-40d1-ab8b-ac30ad4aa3d6)

### 重现步骤

在谷歌浏览器上进行操作是必现该问题的。其他浏览器我们测试团队不使用。

### 期待的正确结果

能搜索到存在的数据。

**Comment by 13290445582** [comment]
您好，暂不支持，command+F 浏览器搜索，检索不到编辑器里面的内容的，浏览器的搜索我们也无法修改，感谢理解。
