### ISSUE TITLE
[BUG]接口测试-定义，选择所有页数据，点击删除，实际未刹删除数据。

### ISSUE THREAD

**Issue by BIGMK365** [metersphere/metersphere#33498]
### 联系方式

1620736018@qq.com

### MeterSphere 版本

v3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

[BUG]接口测试-定义，选择所有页数据，点击删除，实际未刹删除数据。

### 重现步骤

1.
![image](https://github.com/user-attachments/assets/f1048675-1d6e-4794-8321-63091e8ca0c9)

2.
![image](https://github.com/user-attachments/assets/ee224e52-09c7-4c71-9b64-8dc965f5c384)

### 期待的正确结果

可以正常删除所选数据，实际未能删除。

**Comment by 13290445582** [comment]
您好，最新环境未复现，建议升级至V3.3版本使用。

**Comment by BIGMK365** [comment]
前面少了一步操作，需要先筛选出部分接口，再走下面的删除流程，删不掉
![image](https://github.com/user-attachments/assets/827b13ef-b6eb-4f18-9952-beb86d90a06b)

**Comment by BIGMK365** [comment]
不好意思，前面少写了一步操作，需要先筛选出部分接口，再走下面的全选所有分页和删除操作，删不掉。
![image](https://github.com/user-attachments/assets/827b13ef-b6eb-4f18-9952-beb86d90a06b)

**Comment by 13290445582** [comment]
您好，V3.3版本先筛选出部分接口后，再全选所有页也可删除成功，建议升级至v3.3版本试下。

**Comment by BIGMK365** [comment]
更新到3.3.版本后该问题未能复现。

**Comment by 13290445582** [comment]
您好，最新版本无此问题，关闭issue，后续发现问题可重新打开该issue，感谢理解与支持。
