### ISSUE TITLE
[BUG] 测试计划报告统计打开异常

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#33499]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.14-lts

### 使用外置数据库

否

### 问题描述

测试计划报告统计打开异常

### 重现步骤

测试计划关联 8 千case，几百场景用例，共9千多用例，执行多次后，打开报告统计异常
![企业微信截图_17286171565643](https://github.com/user-attachments/assets/c3436388-7e22-4bdd-9e6b-d445349e2bac)
![企业微信截图_17286171232673](https://github.com/user-attachments/assets/0c785992-3cd0-4f14-aeb3-dbda4725c163)

### 期待的正确结果

日志报错
![企业微信截图_17289631079824](https://github.com/user-attachments/assets/0214690c-8b63-4fa9-a954-bbec2c5c03b2)
![image](https://github.com/user-attachments/assets/88580dbf-2318-4979-b4cf-4ae92976ddef)

**Comment by youliyuan-fit2cloud** [comment]
后续版本有优化相同问题，建议升级到最新版本。
这种问题issue提到过多次，通用的优化方案也比较明确，请再自行查看下。
