### ISSUE TITLE
[FEATURE]需要保存每次搜索用例的filter，以免每次都要重新输入filter

### ISSUE THREAD

**Issue by zhongyuan515** [metersphere/metersphere#33500]
### MeterSphere 版本

2.10.0

### 联系方式
交流群29 昵称：逍遥
xuzhongyuan@aliyun.com

### 请描述您的需求或者改进建议

每次搜索用例的时候，都要输入搜索的条件，现在需求是可以将这些条件保存，每次搜索时直接选择保存的filter就可以直接搜索了，不用每次都去选择filter, jira就有这个功能

### 请描述你建议的实现方案

在用户选择filter的界面，除了重置和查询按钮以外，增加保存按钮，将选择的filter保存
![image](https://github.com/user-attachments/assets/ba698f3d-f19e-40bc-ace0-39089ec10997)

**Comment by luty2018** [comment]
您好，这个功能我们已经规划在v3.4版本了。

**Comment by zhongyuan515** [comment]
那我的2.10.0的版本是不是不能用了？2.10.0好像不能直接升级到3.x以上的版本吧

**Comment by liuruibin** [comment]
v3是一个全新的产品，支持一键安装你可以亲身体验一下。
v2.10LTS目前仅支持有限优化和bug修复

**Comment by zhongyuan515** [comment]
> v3是一个全新的产品，支持一键安装你可以亲身体验一下。 v2.10LTS目前仅支持有限优化和bug修复

主要是我们用例数量太大，安装V3，数据库没法升级

**Comment by 13290445582** [comment]
您好，需求已在V3.4实现，V3.4已发布，若有此需要可使用V3.4版本，感谢您的理解。
