### ISSUE TITLE
[BUG]【接口测试】CASE-前置脚本，设置环境参数，运行后控制台报错（实际环境参数设置成功）

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#3351]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11580681/120154449-7b67aa00-c222-11eb-898c-db87d7f566df.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这个问题已经在 #3344 这里进行了回复。

**Comment by jhong123** [comment]
> 你好，这个问题已经在 #3344 这里进行了回复。

收到   你们答复太快了  我以为问题单没提交成功  。。
