### ISSUE TITLE
[BUG]【V1.11】断言中写的是不等于，满足条件后依旧断言失败。

### ISSUE THREAD

**Issue by zhangxia11** [metersphere/metersphere#3352]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
![image](https://user-images.githubusercontent.com/49543870/120156027-1745e580-c224-11eb-84ec-31c0c3e4cd4f.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/49543870/120156035-1a40d600-c224-11eb-899b-5d62739ea6ee.png)

**Comment by zyyfit** [comment]
您好，这个问题也有其他用户反馈，但是我们这边没有复现，我们再排查一下

**Comment by pptech-dev** [comment]
> 您好，这个问题也有其他用户反馈，但是我们这边没有复现，我们再排查一下

node-controller我看新提交的代码里面已经修复这个问题
