### ISSUE TITLE
[FEATURE]接口请求里面可以支持设置proxy

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#33535]
### MeterSphere 版本

v2.10.14-lts-a7298117

### 请描述您的需求或者改进建议

接口请求里面可以支持设置proxy吗？比如下图JMETER这种设置
![image](https://github.com/user-attachments/assets/05d879a0-2474-4ca9-bd51-684dd10704c6)

**Comment by luty2018** [comment]
感谢您的建议， 目前确实没有这个功能， 我们需要进一步调研， 预计会规划在v3版本中。

**Comment by SloanGao** [comment]
后期v2版本不会在新增或者优化功能了吗？另外后期会支持v2升级到v3版本吗？如果后期不在维护v2版本，又不支持v2迁移到v3版本需要重头开始，成本真的太大了。

**Comment by goreycn** [comment]
基于 v3.2.0 解决临时方案：
backend/services/api-test/src/main/java/io/metersphere/api/parser/jmeter/MsHTTPElementConverter.java

        // 找到这里：
        HeaderManager httpHeader = getHttpHeader(msHTTPElement, apiParamConfig, httpConfig);
        Optional.ofNullable(httpHeader).ifPresent(httpTree::add);
        
        // 添加这些
        if (httpHeader != null) {
            for (JMeterProperty header : httpHeader.getHeaders()) {
                if (header.getName().equals("use_https_proxy")) {
                    sampler.setProperty("HTTPSampler.proxyHost", "172.18.18.18");
                    sampler.setProperty("HTTPSampler.proxyPort", "443");
                }
                if (header.getName().equals("use_http_proxy")) {
                    sampler.setProperty("HTTPSampler.proxyHost", "172.18.18.18");
                    sampler.setProperty("HTTPSampler.proxyPort", "80");
                }
            }
        }

使用时，在测试case 按需配置 header参数, 值任意

1、需要 http 代理里，添加key：use_http_proxy
2、需要 https 代理里，添加key：use_https_proxy
3、默认情况下，不使用http代理

**Comment by wt0215** [comment]
> 基于 v3.2.0 解决临时方案： backend/services/api-test/src/main/java/io/metersphere/api/parser/jmeter/MsHTTPElementConverter.java
> 
> ```
>     // 找到这里：
>     HeaderManager httpHeader = getHttpHeader(msHTTPElement, apiParamConfig, httpConfig);
>     Optional.ofNullable(httpHeader).ifPresent(httpTree::add);
>     
>     // 添加这些
>     if (httpHeader != null) {
>         for (JMeterProperty header : httpHeader.getHeaders()) {
>             if (header.getName().equals("use_https_proxy")) {
>                 sampler.setProperty("HTTPSampler.proxyHost", "172.18.18.18");
>                 sampler.setProperty("HTTPSampler.proxyPort", "443");
>             }
>             if (header.getName().equals("use_http_proxy")) {
>                 sampler.setProperty("HTTPSampler.proxyHost", "172.18.18.18");
>                 sampler.setProperty("HTTPSampler.proxyPort", "80");
>             }
>         }
>     }
> ```
> 
> 使用时，在测试case 按需配置 header参数, 值任意
> 
> 1、需要 http 代理里，添加key：use_http_proxy 2、需要 https 代理里，添加key：use_https_proxy 3、默认情况下，不使用http代理

请问v2版本可以使用这种方式设置proxy吗，如果可以的话应该在哪儿设置呢

**Comment by tinyleelee** [comment]
@SloanGao 兄弟  v2.3.0-f7d4cc4e 这个版本支持他说的这种方法么？ 目前有什么办法 请求+代理
