### ISSUE TITLE
[Feature]测试计划执行过程中，已经生成的测试报告不自动刷新（需要重新生成报告，里面的内容才是最新的）

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33531]
### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

测试报告自动刷新

### 重现步骤

测试计划执行过程中，生成测试报告，测试内容有更新时，查看已经生成的测试报告

### 期待的正确结果

测试计划执行过程中，已经生成的测试报告不自动刷新（需要重新生成报告，里面的内容才是最新的）

**Comment by youliyuan-fit2cloud** [comment]
你好，没有非常理解你的意思，是执行测试计划，这个测试计划的报告不会实时更新每个用例的执行结果吗？
如果是，下个版本有优化这里，会实时显示结果的。
如果是其他问题请补充。

**Comment by henbell2** [comment]
对的，测试报告里的信息就是不能实时更新。包括报告中的bug list，也不能实时更新Bug的变更(比如关联的bug增加/减少，已关联的bug标题修改等，都不能同步到测试报告里)。

**Comment by youliyuan-fit2cloud** [comment]
> Author

了解，我们需要内部讨论下如何优化。当前实现是本次生成的测试报告仅是当时的报告结果，后续的用例/缺陷的变更不会同步，即不是实时的更新。
