### ISSUE TITLE
[BUG]接口导入弹窗，选项连成一行，观感不好

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#33537]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

接口导入弹窗，选项连成一行，观感不好
![image](https://github.com/user-attachments/assets/076988ad-a221-425a-a87e-c922184b0b54)

### 重现步骤

接口导入弹窗，选项连成一行，观感不好

### 期待的正确结果

希望 不同选项之前用距离 隔开

**Comment by 13290445582** [comment]
感谢反馈，后续版本优化下。

**Comment by 13290445582** [comment]
您好，该问题v2.10.21版本已修复，请升级。
