### ISSUE TITLE
[FEATURE]JSON文件结构校验增加正则表达式断言

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#33545]
### MeterSphere 版本

2.7

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

JSON文件结构校验内容比较多，希望能添加正则表达式断言或者有一个按钮可以切换成正则表达式，不使用等于

**Comment by luty2018** [comment]
非常抱歉，短期规划不上了。
