### ISSUE TITLE
[BUG] API Definition接口中包括路径参数时，home页面的场景：接口覆盖率未统计在内

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#33548]
### MeterSphere 版本

v1.20.19-lts

### 使用外置数据库

否

### 问题描述

1. 接口定义中，使用了参数路径  ${siteId}
2. 场景中引用了该接口

问题：
在场景中引用了接口，替换了路径 参数变量，但是在Home页面的统计数据中，接口覆盖率数据不正确
请见以下图片：

![API-Definition-With-Path-Parameter](https://github.com/user-attachments/assets/3dd5f6e7-69cc-49d4-aac7-913a698c8964)
![API-By-Scenario-Coverage](https://github.com/user-attachments/assets/19fd081c-bca5-4116-a12d-868419d3c4de)

### 重现步骤

如上

**Comment by 13290445582** [comment]
您好，没太清楚这个步骤导致接口覆盖率不正确是什么情况。可以具体描述下复现的步骤以及接口覆盖率正确的数值嘛或者提供录屏。在最新版本上测试了下路径包括参数的情况，未发现接口覆盖率统计错误的情况，看您的版本较低，建议升级至最新版本V2.10.20版本测试下。

**Comment by xchnshi** [comment]
重新测试了一下，正在使用的版本也没问题，路径参数添加了${}，这样统计就不会纳入

**Comment by youliyuan-fit2cloud** [comment]
看起来没问题了，close 啦
