### ISSUE TITLE
[BUG]测试计划里 ，批量编辑场景用例的环境变量未生效

### ISSUE THREAD

**Issue by wj395318624** [metersphere/metersphere#3357]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.10.0-93f6870d
**Bug 描述**
简要描述您碰到的问题
在测试计划里 ，批量编辑场景用例的环境变量，界面显示成功，但实际未成功，执行测试计划的场景用例时候报错无环境变量
**Bug 重现步骤**
1.  新建测试计划，关联场景用例10条，并选择运行环境
2. 测试计划里选中所有场景用例，批量编辑，更新运行环境
3. 测试计划里，点击运行其中一个场景用例，报错“运行环境未配置”
4. 在接口测试-接口自动化”里检查对应场景，未配置运行环境，给此场景用例配置运行环境
5.再次去测试计划里点击对应的场景用例，远程成功。

**期待的正确结果**
正确情况下应该是什么样的？
测试计划里批量更新场景用例的运行环境生效（PS：1.9版本此功能是可用的）
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/85099025/120156484-99cea500-c224-11eb-9677-927442990a5f.png)

**Comment by zyyfit** [comment]
您好，能稳定复现吗？这边没有复现呢

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by xulinde** [comment]
v1.10.2版本已修复
