### ISSUE TITLE
[BUG] 禅道第三方配置及缺陷同步无法正常使用

### ISSUE THREAD

**Issue by cllover2410** [metersphere/metersphere#33599]
### 联系方式

345765558@163.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

1、在缺陷同步设置中。设置项目id后点击确定。再次进入该配置，之前未填写的产品id也显示了项目id。
2、缺陷管理点击同步缺陷后无效。已设置全量同步
3、创建缺陷，点击提示创建失败。但是在禅道的项目动态中可看到该缺陷创建记录，点击可访问其详情。但禅道的bug列表看不到

### 重现步骤

……

**Comment by 13290445582** [comment]
您好，请问所对接禅道为哪个版本，可以更新禅道插件为最新版本测试下。检查下在metersphere内填写的对接平台信息是否正确，在禅道的项目动态中可看到该缺陷创建记录，点击可访问其详情，但禅道的bug列表看不到的情况可能是在禅道内没找对该bug存在的产品或项目，正常来说禅道内是可以正常显示的。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
