### ISSUE TITLE
[FEATURE]功能测试用例不能跨项目共享

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33604]
### MeterSphere 版本

v3.3.0-c48b9fb2

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/7b32afbe-022e-4f71-b809-37773d106072)

### 请描述你建议的实现方案

功能测试用例支持跨项目共享

**Comment by luty2018** [comment]
可以描述一下你的使用场景， 以便我们更好的规划这个功能。

**Comment by henbell2** [comment]
平行项目/衍生项目，需要分开管理的，既有项目的知识积累/用例可以无缝过渡，省的再来一遍

**Comment by luty2018** [comment]
那你是要复制到跨项目？ 还是说做成公共用例，所有项目都能看？

**Comment by henbell2** [comment]
可以跨项目复制更直接一点，和实际需求匹配度更高。公共用例库随着项目数量增加、用例规模变大，越来越难以维护，当新项目需要，也不太容易匹配。个人建议哈

**Comment by luty2018** [comment]
> 可以跨项目复制更直接一点，和实际需求匹配度更高。公共用例库随着项目数量增加、用例规模变大，越来越难以维护，当新项目需要，也不太容易匹配。个人建议哈

收到， 我这边已记录！
