### ISSUE TITLE
[BUG] 长时间停留页面不动，会报错，504 GATEWAY_TIMEOUT "Response took longer than timeout: PT5M"

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#33601]
### 联系方式

chase001@qq.com

### MeterSphere 版本

版本:   v2.10.20-lts-9feb97b3

### 使用外置数据库

否

### 问题描述

[BUG] 长时间停留页面不动，会报错，504 GATEWAY_TIMEOUT "Response took longer than timeout: PT5M"

### 重现步骤

504 GATEWAY_TIMEOUT "Response took longer than timeout: PT5M"

![image](https://github.com/user-attachments/assets/acd04ccd-9238-48d2-8ac5-febccd19d168)

**Comment by 13290445582** [comment]
你好， 导致该问题的原因可能是当时服务器的负载过高，内存/网络状况比较差，再次遇到请及时查看服务器状况，或者可以在该配置文件下添加，如下超时时间配置，单位毫秒，看看是否可解决该问题。SPRING_CLOUD_GATEWAY_HTTPCLIENT_RESPONSE-TIMEOUT=600000
<img width="701" alt="image" src="https://github.com/user-attachments/assets/443de46a-8058-4a04-9c7f-179452511265">

**Comment by chase001** [comment]
按照配置失败，请看
[root@metersphere msadmin]# msctl reload
yaml: line 29: could not find expected ':'
[root@metersphere msadmin]# vi /opt/metersphere/docker-compose-gateway.yml


以 下详细配置
![image](https://github.com/user-attachments/assets/54e50e79-e6c9-4ff6-9cc4-5481d100a745)

**Comment by youliyuan-fit2cloud** [comment]
请修复参考如下：
SPRING_CLOUD_GATEWAY_HTTPCLIENT_RESPONSE-TIMEOUT : 600000

**Comment by chase001** [comment]
设置 了还是会报错

**Comment by youliyuan-fit2cloud** [comment]
说下报什么错误哇？配置截图看看吧

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
