### ISSUE TITLE
[QUESTION]系统参数里面有些选项社区版本中没有，咨询下是配置问题还是需要企业版本才支持的？

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33607]
### 请描述您的问题

![image](https://github.com/user-attachments/assets/660b45ce-d5c3-4a40-9032-63efa03e80d9)
系统参数里面不少选项社区版本中没有，咨询下是配置问题还是需要企业版本才支持的？

**Comment by luty2018** [comment]
您好， 扫码登录是企业版功能。

**Comment by henbell2** [comment]
Get！
