### ISSUE TITLE
[FEATURE]测试计划是否能添加对结束时间的预估

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#33602]
### MeterSphere 版本

2.7

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

测试计划是否能添加对结束时间的预估，比如我跑了一个测试计划，我需要知道它大概需要跑多少时间，什么时间能结束

**Comment by luty2018** [comment]
测试计划的执行时间受计划内的用例大小以及资源池的容量影响，这个没有办法预估。
