### ISSUE TITLE
[BUG]【接口自动化】case的前置操作-等待时间在第一个步骤，然后场景里引用该case。之后case里将等待时间拖拽到第三个步骤进行保存，打开场景发现该case的等待控制器并未发生改变。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#33614]
### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】case的前置操作-等待时间在第一个步骤，然后场景里引用该case。之后case里将等待时间拖拽到第三个步骤进行保存，打开场景发现该case的等待控制器并未发生改变。

### 重现步骤

【接口自动化】case的前置操作-等待时间在第一个步骤，然后场景里引用该case。之后case里将等待时间拖拽到第三个步骤进行保存，打开场景发现该case的等待控制器并未发生改变。
![image](https://github.com/user-attachments/assets/a65100dd-21cd-4acb-8b0e-b172a8d084d8)
![image](https://github.com/user-attachments/assets/00767d96-2478-4fef-92ba-049f95a14d6d)
![image](https://github.com/user-attachments/assets/44fcdac3-9388-49c0-b395-7589fd9f641e)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题。

**Comment by fit2-zhao** [comment]
就是这样设计的呀，场景中也是可以添加和排序的。
