### ISSUE TITLE
[QUESTION][MS V3]一个环境下有多个数据源，当切换到另一套环境的时候，是怎么确定要查哪个库？

### ISSUE THREAD

**Issue by qiuxue-boop** [metersphere/metersphere#33623]
### 一个环境下有多个数据源，当切换到另一套环境的时候，是怎么确定要查哪个库？

你好，对系统功能使用有些疑问，希望能帮忙解答下~
安装的是metersphere 社区版  版本是v3.3.0-c48b9fb2

每套环境可以配置多个数据源（不同环境的数据库明细不一样，但是用途一样），然后在前置脚本中添加SQL操作。
比如：
环境A：数据库test_bus  和数据库test_saas
环境B：数据库test_bus_2  和数据库test_saas_n

我在某个用例里，前置脚本添加SQL操作，要选择引用的数据源，我调式用例的时候，在环境A，选择引用的是数据库test_bus。
调试完后，我想切换到环境B执行这条用例，那这个时候，是怎么对应上用环境B的哪个数据库的？

![image](https://github.com/user-attachments/assets/bf56869f-3311-4f32-800f-6a54f98551d7)
![image](https://github.com/user-attachments/assets/e6be6510-c27b-4f2e-9fac-cbf8a4c010d2)

**Comment by luty2018** [comment]
根据数据源名称去匹配， 如果匹配不上就取第一个数据源。

**Comment by qiuxue-boop** [comment]
好的了解，那我只能把每个环境的主库、业务库，配置到环境变量里了
话说这里功能设计上还有优化空间吗？
实际上，切换环境后，库的名字可能会发生变化，因为机器资源等情况，会在同一个机器部署多套环境，所以数据库名字会不同。比如我这个场景
环境A：数据库test_bus 和数据库test_saas
环境B：数据库test_bus_2 和数据库test_saas_2

仅建议：可以给数据源加一个配置，比如类型或者说用途，添加SQL操作的时候，自行选择某个类型的库。切换环境的时候，如果另一套环境有配置相同类型的数据源，则选择这个数据源；如果没有，则选择第一个；如果有多个，则选择第一个（或者功能上不允许一个类型有多个数据源）。然后类型是自定义的文本
