### ISSUE TITLE
[BUG]无法导入Swagger中的接口

### ISSUE THREAD

**Issue by kanna001** [metersphere/metersphere#33628]
### MeterSphere 版本

V3.2.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/b3d11279-b8a7-424c-a7d6-61ebe8ca4751)
导入Swagger中的接口时，提示解析数据出错

### 重现步骤

![image](https://github.com/user-attachments/assets/f6d37bf7-a791-4c51-a066-6b63e529c858)
1.接口测试->定义->新建旁边的按钮->导入接口

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，下个版本修复。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。

**Comment by Stephen0910** [comment]
![image](https://github.com/user-attachments/assets/99fd2618-87ad-4d36-a474-26f671f07f54)
v3.4 也报错啊

**Comment by 13290445582** [comment]
您好，请提供导入的swagger文件。

**Comment by Stephen0910** [comment]
> 您好，请提供导入的swagger文件。

文件错了， 忽略
