### ISSUE TITLE
[BUG] 脑图保存提示【该模块下已存在该测试用例】，提示不明确使用不友好

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#33630]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

脑图保存提示【该模块下已存在该测试用例】，提示不明确使用不友好

使用背景：脑图页面，操作较多，添加之后又编辑了其他模块，涉及模块很多，不知道提示说的是【该模块】是哪个模块

### 重现步骤

![image](https://github.com/user-attachments/assets/1a38a866-ed58-4818-b7fb-2880122ff23c)

### 期待的正确结果

**提示用例已存在时，说明是哪个模块下面的哪个用例**

**Comment by youliyuan-fit2cloud** [comment]
意思是：实际不是当前选中的模块有已存在的用例？

**Comment by fit2cloud-yaochunrong** [comment]
是的，脑图编辑的特征是进行了很多操作，保存的时候报错需要明确下，用户才能有效修改保存

**Comment by youliyuan-fit2cloud** [comment]
后续版本优化一下。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。仅提示重复的用例名称，没有模块信息。
