### ISSUE TITLE
[BUG]生成报告统计的缺陷个数错误，应该用缺陷条数，而不是用关联用例加和

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33641]
### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/21215771-0fae-45e6-928c-8f1ef66cb5eb)
生成报告统计的缺陷个数错误，应该用缺陷条数，而不是用关联用例加和

### 重现步骤

执行一个测试计划，新建一条缺陷，关联多个用例，查看测试报告中统计的缺陷条数

### 期待的正确结果

应该用缺陷条数，而不是用关联用例加和

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，已转V3.5需求。

**Comment by 13290445582** [comment]
您好，V3.5已实现该需求，请升级。
