### ISSUE TITLE
[BUG]筛选器选择上层节点，下层子节点不能自动选中，需要一个一个勾选，否则筛选不到任何内容

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33663]
### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/49a48f23-2aa8-45e0-b91f-ed6a5bb4b39d)
筛选器选择上层节点，下层子节点不能自动选中，需要一个一个勾选，否则筛选不到任何内容

### 重现步骤

筛选器选择上层节点，下层子节点不能自动选中，需要一个一个勾选，否则筛选不到任何内容

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续版本会优化这里。

**Comment by luty2018** [comment]
<img width="638" alt="image" src="https://github.com/user-attachments/assets/d8354ba7-f4bd-4ecd-adbc-6e392c4b5a0f">
v3.5已支持
