### ISSUE TITLE
[BUG]admin账号登录，系统设置-系统-用户组与权限-组织管理员（系统）-设置权限，组织功能菜单为什么会出现‘用户组与权限’的操作对象？

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#3368]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0-LTS
**Bug 描述**
简要描述您碰到的问题
admin账号登录，系统设置-系统-用户组与权限-**_组织管理员（系统）_**-设置权限，组织功能菜单为什么会出现‘用户组与权限’的操作对象？本身组织菜单中就没有用户组与权限这个子菜单啊！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/120168888-f8e6e680-c231-11eb-9300-387fd5088576.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
目前就是这样设计的哦～
