### ISSUE TITLE
[BUG]接口后置脚本读取文件报错，文件在服务器路径中存在，但还是报文件不存在的错误

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#33697]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

接口后置脚本读取文件报错，文件在服务器路径中存在，但还是报文件不存在的错误

### 重现步骤

1. 创建接口，添加后置脚本，运行调试报错文件不存在
<img width="628" alt="4b7055ae68811bce699927f4f57c78d" src="https://github.com/user-attachments/assets/be86f496-acca-49c0-a6b5-fae31ac3489e">
2. 在服务器中明明存在此文件
<img width="272" alt="c462367af7fd481754a0024bd3be20a" src="https://github.com/user-attachments/assets/88ee8fde-92f2-4a0d-8248-a85124d3f8e5">

### 期待的正确结果

接口后置脚本读取文件正常

### 相关日志输出

```shell
无
```

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现，这个文件 test.csv 读写权限加上试试

**Comment by youliyuan-fit2cloud** [comment]
经过沟通确认，安装目录不是默认的/opt下，但是node-controller执行机中文件存储目录仍是默认的/opt，所以接口中后置脚本中应该使用容器中的文件所属目录 即/opt /xxxxx 。
可以通过手动修改上述容器的 yaml配置文件。参考下图中配置
![image](https://github.com/user-attachments/assets/df70ae65-6105-4d11-a82e-1b510bf9c7e1)
