### ISSUE TITLE
[BUG]操作日志报错：SQL error happened, please check logs.

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#3369]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0-LTS
**Bug 描述**
简要描述您碰到的问题
安装完毕，admin登录，系统设置-所有菜单中的操作日志，第一次点击，报错
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/120169261-57ac6000-c232-11eb-80c9-c95d811e10e9.png)

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/3368
