### ISSUE TITLE
[FEATURE] beanshell和python的调试信息输出到页面上

### ISSUE THREAD

**Issue by assilzm** [metersphere/metersphere#337]
**请描述您的需求或者改进建议.**
在使用beanshell和python编写脚本时，免不了要调试，但是使用print或者System.out.println输出的信息只会输出到控制台，只能在容器里的console查看，非常不方便。普通用户看不到console无法进行调试。

**请描述你建议的实现方案**
希望能把调试信息输出到页面上，方便在编写测试时进行调试。

**Comment by Dyc2333** [comment]
我们也有相同的需求

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by xulinde** [comment]
您好，新版本在响应模块增加控制台功能，您可以升级到最新版本体验下
