### ISSUE TITLE
[BUG]自动化场景中JS脚本转换性能测试格式异常导致执行错误

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33714]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

自动化场景中JS脚本转换性能测试格式异常导致执行错误

### 重现步骤

1、创建一个自动化场景，包含JS脚本，执行成功
![image](https://github.com/user-attachments/assets/daab23c9-d219-4d1c-90f8-dc78bcfc7405)

2、一键将场景转为性能测试，并执行，执行异常
![image](https://github.com/user-attachments/assets/d318c53c-caec-448f-b73f-90d01eb0a02a)

3、从性能测试报告中下载执行文件导入接口自动化，发现脚本格式变化了，在自动化这边也执行错误
![image](https://github.com/user-attachments/assets/5738a61a-1ca9-4232-bfd9-8a37e06f3b7e)
4、脚本是客户真实数据，不方便贴在这里，复现地址如下：
![image](https://github.com/user-attachments/assets/d59b0b10-f0dc-4294-97b3-681f119843b1)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by liuruibin** [comment]
这个和js内容有关，我自己写了一个脚本正常执行

<img width="656" alt="image" src="https://github.com/user-attachments/assets/6ba06a23-381b-4e4a-a0d4-f72e492c6c25">

<img width="649" alt="image" src="https://github.com/user-attachments/assets/cef0d520-64b7-4570-acb6-a3df478a446c">

**Comment by linfengjjj** [comment]
是跟内容有关的，简单的内容还正常，脚本内容比较大的时候会这样，那个QA环境的复现脚本里定义了一个json请求体，请求体比较复杂，转换性能测试就会出现异常。
![image](https://github.com/user-attachments/assets/9ea376fd-d7f2-4a98-894d-6b6476f401e5)

**Comment by youliyuan-fit2cloud** [comment]
你好，需要自行调整js脚本，感谢理解和支持。
