### ISSUE TITLE
[BUG]在文件管理中重新上传文件后UI自动化无法刷新文件

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#33736]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

v2.10.20-lts-5b97a029

### 使用外置数据库

否

### 问题描述

在UI自动化中对重新上传的文件进行关联时其文件的缓存不会刷新。其文件内容仍然是最开始上传的内容。

### 重现步骤

1.文件管理中上传文件。
2.UI自动化中关联文件。
3.执行UI自动化。
4文件管理中重新上传文件。
5.再次执行UI自动化

### 附加信息

由于视频23M无法上传，如果需要原视频信息请联系我。

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把这个场景的具体配置截图吗？日志信息也发出来看看。重新上传文件内容有变更，名称没有变是吧？

**Comment by B14Lettingo** [comment]
是的，重新上传后文件名称没有改变。场景的配置是使用东区MaxKB环境中知识库上传文档。
![image](https://github.com/user-attachments/assets/28255013-573d-489c-b974-39631348d0fd)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已复现，后续版本优化
