### ISSUE TITLE
[FEATURE] 建议在“测试”功能里可以直接上传文件

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#3374]
**请描述您的需求或者改进建议.**
（1）如图中所示，如果Jmx文件或CSV文件需要更新，现在是需要在“加载JMX文件”和“加载文件”里重新上传或替换的，但是场景多了以后，尤其是需要复测的，上传文件的步骤比较繁琐，还容易更新错文件，这里既然能下载文件，那能不能也支持上传文件更新呢？（**重要**）
![image](https://user-images.githubusercontent.com/42863606/120175123-701f7900-c238-11eb-9915-c512db0e63b2.png)

（2）如果可以直接上传，文件名是以新文件名为准还是以旧文件名为准，以及是否可以更新文件名，涉及到文件名更新还要考虑JMX文件里引用的文件名，还是需要你们调研一下。（**次要**）

**请描述你建议的实现方案**
（1）在“下载”按钮附近增加一个“上传”按钮

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by zyyfit** [comment]
您好，第一个问题，这里可以支持上传文件的，上传操作在 “加载文件” 按钮里面
![图片](https://user-images.githubusercontent.com/73461316/123749269-d0f9aa00-d8e7-11eb-8c8c-b474ee58005c.png)

第二个问题，更新文件的话最好使用同名文件，或者修改脚本里的文件名
