### ISSUE TITLE
[QUESTION] 站点URL信息用途

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#33755]
### 请描述您的问题

Metersphere部署后，申请了单独的内部域名来访问，在站点URL中也配置为该域名。
但是在执行接口自动化过程中，经常会出现“调用资源池执行失败，请检查资源池是否配置正常"（再次调用可能会成功）
所以想请教：
1. 此处站点URL的配置用例是用来自动化调用的吗？如果是，是否可以配置成VM的IP地址，不使用域名地址？（在怀疑走了域名导致接口自动化失败）
2. 如果不仅提供给自动化测试（性能？），还有哪些模块涉及到此处站点URL信息？

![image](https://github.com/user-attachments/assets/17894215-7e7a-4859-97c7-c1bbeac8e2ca)
![image](https://github.com/user-attachments/assets/7a73c850-d759-40b4-bded-4b9916a1ceb8)

谢谢

**Comment by fit2-zhao** [comment]
可以使用 IP 地址，站点地址将用于接口测试和性能测试执行机的资源获取，以及发送通知和分享报告等操作的 URL 地址组装。
