### ISSUE TITLE
[BUG]接口测试响应体断言使用JSONPath时，点击“测试”按钮有时无法获取值

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#33757]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

接口测试响应体断言使用JSONPath时，点击“测试”按钮有时无法获取值，显示无法获取内容，实际是完全符合JSON格式

### 重现步骤

可以创建HTTP的MOCK,响应体设置如下：

{"id":"12777458987368448","reportId":"172975868247200000","environmentId":"8106046397464577","name":"tst","moduleId":"root","num":100002,"tags":[],"description":"","status":"PROCESSING","response":[{"id":"12777476167237632","statusCode":"200","defaultFlag":true,"name":"apiTestManagement.response","headers":[],"body":{"bodyType":"JSON","jsonBody":{"jsonValue":"","enableJsonSchema":true,"jsonSchema":{"type":"object","enable":true,"properties":{},"description":null}},"xmlBody":{"value":""},"rawBody":{"value":""},"binaryBody":{"sendAsBody":false,"description":"","file":null}},"responseActiveTab":"BODY"}],"protocol":"HTTP","method":"POST","path":"/order/order","request":{"authConfig":{"authType":"NONE","basicAuth":{"userName":"","password":"","valid":false},"digestAuth":{"userName":"","password":"","valid":false},"httpauthValid":false},"body":{"bodyType":"FORM_DATA","binaryBody":{"description":"","file":null},"rawBody":{"value":""},"xmlBody":{"value":""},"wwwFormBody":{"formValues":[]},"jsonBody":{"jsonValue":"","enableJsonSchema":true},"formDataBody":{"formValues":[]}},"headers":[],"method":"POST","otherConfig":{"connectTimeout":60000,"responseTimeout":60000,"certificateAlias":"","followRedirects":true,"autoRedirects":false},"path":"/order/order","query":[],"rest":[],"url":"/order/order","polymorphicName":"MsHTTPElement","name":"tst","children":[{"polymorphicName":"MsCommonElement","assertionConfig":{"enableGlobal":true,"assertions":[{"name":"响应体","assertionType":"RESPONSE_BODY","id":"1729758620384","enable":true,"assertionBodyType":"JSON_PATH","jsonPathAssertion":{"assertions":[]},"xpathAssertion":{"responseFormat":"XML","assertions":[]},"regexAssertion":{"assertions":[]}}]},"postProcessorConfig":{"enableGlobal":true,"processors":[]},"preProcessorConfig":{"enableGlobal":true,"processors":[]}}]},"uploadFileIds":[],"linkFileIds":[],"deleteFileIds":[],"unLinkFileIds":[],"projectId":"8106046397464576","frontendDebug":false,"isNew":false}

### 附加信息

如图：
<img width="994" alt="image" src="https://github.com/user-attachments/assets/3e428708-5c71-4c4a-99c5-89d7b846fc76">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已修复，请关注发布信息。

**Comment by 13290445582** [comment]
您好，问题已在V3.4版本修复，V3.4已发布，请升级。
