### ISSUE TITLE
[FEATURE]2.10.21版本中，接口测试选择jsonpath提取器提取出的网址中的字符被自动加上转义字符，导致正则匹配等断言不能快捷的填写

### ISSUE THREAD

**Issue by liangsc-test** [metersphere/metersphere#33770]
### MeterSphere 版本

v2.10.20-lts

### 联系方式

MeterSphere 交流群49（梁世聪）

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/f7ed571e-281b-433a-9c9a-efd19eb7e1ec)
如图所示，这里无法快捷的进行断言，始终都影响效率

### 请描述你建议的实现方案

在提取旁边加一个【无需转义】的按钮，或者其他地方做此类设置，给用户选择的机会，能提高一些工作效率

**Comment by luty2018** [comment]
好的， 这个我们转bug处理
