### ISSUE TITLE
[BUG]接口定义或Case请求中上传到Minio中异常

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#33788]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

如果在接口定义中选择form-data，并且进行了文件上传，在服务器本地的文件没有问题，但是在上传文件到Minio这段代码中，如果我在一个key中上传两个文件，则只会有一个文件被上传，原因为都将其名称设置了为了requestId导致

io.metersphere.commons.utils.ApiFileUtil#createBodyFiles(java.lang.String, java.util.List<org.springframework.web.multipart.MultipartFile>)

![image](https://github.com/user-attachments/assets/7373299d-4a05-4da9-bb5f-82a406b53e0e)

![image](https://github.com/user-attachments/assets/33ffb1ba-b9a1-45ab-bca6-a54406d533ac)

![image](https://github.com/user-attachments/assets/ba7b93ea-5b77-475c-8f45-b320910851e4)

### 重现步骤

如上所述

### 期待的正确结果

建议新增方法
![image](https://github.com/user-attachments/assets/1d564bbf-1723-418a-a71d-9deeacf78fae)

**Comment by fit2-zhao** [comment]
后续版本修复此问题，感谢。

**Comment by ijwstl** [comment]
> 后续版本修复此问题，感谢。

好的感谢，不过我看了下您的提交，可能没有解决该问题，就比如说在场景中的HTTP请求中已FormData形式同一个key中添加多个文件，他们的bodyFileRequestIds是相同的，根据update接口的调用关系

io.metersphere.service.scenario.ApiScenarioService#update  ->  io/metersphere/service/scenario/ApiScenarioService.java:331这里，因为id是同一个，其实这里会进行文件的覆盖，并且您提交的后的变更里io.metersphere.commons.utils.ApiFileUtil#createBodyFiles(java.lang.String, java.util.List<org.springframework.web.multipart.MultipartFile>)好像并不能解决该问题，您可以再看下

![image](https://github.com/user-attachments/assets/3ee32478-7188-45cf-a09b-ee118a156932)

![image](https://github.com/user-attachments/assets/3153ec8c-c8b9-43bd-a851-2bb089d8d3fb)

**Comment by fit2-zhao** [comment]
已经处理了，这里我们分两种情况，分多个PR 处理的：

第一种是你提的 API-Case｜API 附件存储会根据（/请求id/文件名）方式存储；
第二种是场景 csv ｜ 环境 csv 附件存储会根据附件 ID 命名存储。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
