### ISSUE TITLE
[BUG] v2.10.20-lts 执行接口自动化场景请求地址出现多余的 http://null

### ISSUE THREAD

**Issue by blackfoamm** [metersphere/metersphere#33797]
### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

执行接口自动化场景，请求地址出现多余的 http://null 导致执行失败

![image](https://github.com/user-attachments/assets/64ad5f87-22d1-468a-a954-a829b000ad02)

### 重现步骤

在场景中使用【接口列表导入】，并复制 API（只有复制才会出现该错误信息）

![image](https://github.com/user-attachments/assets/641555a4-ce70-4dd2-942f-cb4887fd7723)

### 期待的正确结果

不在请求地址中添加其他元素

**Comment by youliyuan-fit2cloud** [comment]
你好，我们测试环境没办法复现，请把你的环境配置，和场景配置截图看看

**Comment by blackfoamm** [comment]
感谢回复，这是我的相关配置

### 场景配置
![image](https://github.com/user-attachments/assets/8c12ec7e-b2bb-4e05-93ac-bfa0d2283ad8)

### 环境配置
环境组中没有配置任何 http，只配置了 MySQL 连接
![image](https://github.com/user-attachments/assets/c948db05-4bbe-43a0-b5a6-eada01cd46b0)

![image](https://github.com/user-attachments/assets/8afb6ce7-ae25-4c0b-bd28-e2db6842e984)

![image](https://github.com/user-attachments/assets/b71ef712-a70a-484b-abd9-006a454194f2)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，环境里面没有http配置，添加个http配置吧，因为场景中从接口导入的复制/引用的api接口不带url地址的（即使复制的可以手动加个地址，这个不是常规用法）。感谢理解和支持。
