### ISSUE TITLE
[BUG]websocket插件在步骤中无法查看响应内容

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33795]
### 联系方式

蒋林峰

### MeterSphere 版本

v3.3.0

### 使用外置数据库

否

### 问题描述

websocket插件在步骤中无法查看响应内容

### 重现步骤

1、在V3版本中使用websocket插件
2、在接口测试步骤中分别执行websocket请求和http请求，只有websocket请求在步骤中看不到响应内容
<img width="936" alt="46c701b234b4fcb22984a7d29fb238c" src="https://github.com/user-attachments/assets/750e50ee-a8d4-4e35-85ee-6938879bbf81">
<img width="960" alt="add0a24faf81b8bbc32ccca7cf789c4" src="https://github.com/user-attachments/assets/20743c21-c0a2-450a-999e-d5bf8060cd26">

**Comment by luty2018** [comment]
会在3.4版本修复
