### ISSUE TITLE
[FEATURE] 编写接口测试调试时的提取到的数据能存入变量在接下来的接口中使用

### ISSUE THREAD

**Issue by assilzm** [metersphere/metersphere#338]
**请描述您的需求或者改进建议.**
在编写接口测试时，免不了要调试，但是调试的时候，"提取"功能中得到的数据实际上并没有存入变量中。每次在接下来的接口编写中要使用事前提取到的数据得手动设置一下变量值，非常不便。

**请描述你建议的实现方案**
期望提取功能能和正常执行时一样，每次执行完成后设置变量的值以便接下来使用。

**Comment by zyyfit** [comment]
后续版本支持
