### ISSUE TITLE
v3.2.0 版本创建POST接口的Mock控制台稳定js报错：TypeError: cyclic object value

### ISSUE THREAD

**Issue by baishui2004** [metersphere/metersphere#33822]
v3.2.0版本：点击“创建”或“保存并继续创建”都会报该错误，且不会发起Network网络请求，创建GET、PUT接口的Mock可以正常保存成功。
补充：v3.0.1保存POST接口Mock可以成功，可以正常访问该Mock。

v3.2.0 js报错截图：
![image](https://github.com/user-attachments/assets/a196bf80-6a36-4485-8d27-b2f21430a03a)

**Comment by 13290445582** [comment]
您好，最新版本未复现，建议升级至最新版本使用。

**Comment by baishui2004** [comment]
> 您好，最新版本未复现，建议升级至最新版本使用。

好的，我试试，谢谢

**Comment by baishui2004** [comment]
@13290445582 您好，测试了docker hub中的metersphere/metersphere-ce-allinone:v3.5.0版本，仍然有该问题
具体版本号：v3.5.0-c3ad9f70

**Comment by 13290445582** [comment]
您好，可以在我们的demo环境：https://demo.metersphere.com测试下，在demo环境有此问题吗，我们这没复现。
