### ISSUE TITLE
[BUG]MOCK配置跟随API定义后，会在MOCK不匹配的时候也生效，取消跟随API定义也取消不了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33831]
### 联系方式

蒋林峰

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

MOCK配置跟随API定义后再取消，实际上还会在MOCK不匹配的时候生效

### 重现步骤

1、首先给一个接口设置MOCK匹配条件，并且设置响应体为“跟随API定义”，当请求参数不匹配时也返回了响应体
![image](https://github.com/user-attachments/assets/28beb4ec-4eb1-4c45-b708-3b29e87615f2)
![image](https://github.com/user-attachments/assets/3b6bbdf6-ea24-4836-a12c-dc9f23cebe9a)
2、取消“跟随API定义‘，设置”json’，再执行请求，参数不匹配时还是会返回API定义的响应体
![image](https://github.com/user-attachments/assets/94f8a391-93e5-4fde-ac7e-e30599c1f8dd)
![image](https://github.com/user-attachments/assets/dbd9a509-7275-488e-85a5-9d1db8200af1)
![image](https://github.com/user-attachments/assets/74814a78-5ed6-4da4-8583-3faef6ec09aa)

### 期待的正确结果

MOCK参数不匹配时不应该返回任何响应体

**Comment by Somebody-JIAN** [comment]
mock配置的匹配方式：

a).匹配Mock期望，然后返回匹配到的mock期望的设置

b).不满足a的情况下， 返回api配置的响应信息。


看你的情况，应该是触发了逻辑b

**Comment by linfengjjj** [comment]
1
