### ISSUE TITLE
[FEATURE]做为测试过程管理工具功能弱了一点，不能清晰识别过程风险

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33843]
### MeterSphere 版本

v3.3.0-c48b9fb2

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/1f7b3156-8ac8-41cb-970c-518cdd80527d)

### 请描述你建议的实现方案
如果能有个独立的页面衡量效率、或者有一键效率监控，这样最好！
通过完善筛选或许也可实现，但是现在字段属性中没有“执行时间”，也没有看到按照时间区间筛选的方式。目前实现不了过程管理。

_No response_

**Comment by luty2018** [comment]
已经在规划了， 预计v3.5

**Comment by Hyyfit** [comment]
您好，感谢您的反馈。
我们有规划测试计划的实时报告，实时统计用例的执行结果分布和执行频次、人员执行的进度。在后续的版本里会上线。
