### ISSUE TITLE
[BUG]首次进入接口调试页，会自动触发一次接口调用

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#3385]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
调试接口时，首次进入接口调试页（从接口编辑页进入），会触发一次请求，此时会post请求会变成get请求

**截图**
![image](https://user-images.githubusercontent.com/49089965/120187214-1e321f80-c247-11eb-867a-523a5af0034f.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，目前已经发布了1.10版本，请升级到最新版试一下
