### ISSUE TITLE
[BUG]接口状态未正确展示

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#3386]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
【接口自动化页面-》选择【从接口列表导入】，此时导入列表没有接口状态

**截图**
![image](https://user-images.githubusercontent.com/49089965/120187351-415ccf00-c247-11eb-8654-b4d2e829145c.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by zyyfit** [comment]
1.10.1版本去掉了接口状态这个字段
