### ISSUE TITLE
[QUESTION] Jmeter镜像无法下载

### ISSUE THREAD

**Issue by yangzhao0520** [metersphere/metersphere#3387]
mac在搭建本地开发环境时，配置文件指定的registry.fit2cloud.com/metersphere/jmeter-master:0.0.6无法获取，使用了registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master地址仍然不可用。

<img width="678" alt="WechatIMG201" src="https://user-images.githubusercontent.com/56626774/120257777-6b53d700-c2c3-11eb-811c-60947b19872e.png">

**Comment by pptech-dev** [comment]
遇到同样的问题
```
 docker pull registry.fit2cloud.com/metersphere/jmeter-master:0.0.6
```
然后提示
```
Error response from daemon: pull access denied for registry.fit2cloud.com/metersphere/jmeter-master, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by wangzhen-fit2cloud** [comment]
> 遇到同样的问题
> 
> ```
>  docker pull registry.fit2cloud.com/metersphere/jmeter-master:0.0.6
> ```
> 
> 然后提示
> 
> ```
> Error response from daemon: pull access denied for registry.fit2cloud.com/metersphere/jmeter-master, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ```
你好，请参考下我们最新安装包里使用的jmeter镜像，目前的最新镜像如下
```docker pull registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms4-jdk8```

**Comment by wangzhen-fit2cloud** [comment]
> mac在搭建本地开发环境时，配置文件指定的registry.fit2cloud.com/metersphere/jmeter-master:0.0.6无法获取，使用了registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master地址仍然不可用。
> 
> <img alt="WechatIMG201" width="678" src="https://user-images.githubusercontent.com/56626774/120257777-6b53d700-c2c3-11eb-811c-60947b19872e.png">

目前我们没有打 latest 标签，需要指定下镜像具体的标签
```docker pull registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms4-jdk8```
