### ISSUE TITLE
[BUG] UI测试报告结果统计有异常：UI测试脚本里，有一些步骤没有执行，但是定时任务的测试报告显示执行成功

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#33885]
### MeterSphere 版本

v2.10.20

### 使用外置数据库

否

### 问题描述

UI测试报告结果统计有异常：UI测试脚本里，有一些步骤没有执行，但是定时任务的测试报告显示执行成功
1、在UI测试报告列表中报告执行状态为成功
2、打开报告明细，最后一些节点为未执行

### 重现步骤

UI测试报告结果统计有异常：UI测试脚本里，有一些步骤没有执行，但是定时任务的测试报告显示执行成功
1、在UI测试报告列表中报告执行状态为成功
2、打开报告明细，最后一些节点为未执行

### 附加信息

![image](https://github.com/user-attachments/assets/dabdeb30-bdf1-4d32-9d13-cbc63f41771f)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，请把场景详细信息发一下。感谢理解和支持。

**Comment by youliyuan-fit2cloud** [comment]
控制台日志：
2024-11-06 01:00:05 INFO 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1 Thread started: 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1
2024-11-06 01:17:52 INFO 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1 Thread is done: 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1
2024-11-06 01:17:52 INFO 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1 Thread finished: 5a57ecfc-586e-454e-ae1c-797a1e39bddd 1-1
org.openqa.selenium.WebDriverException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.105.1.el7.x86_64', java.version: '17.0.10'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [ba09033f-fb87-4d93-860f-8fb71f65bbf5, getCurrentWindowHandle {}]
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:bidiEnabled: false, se:cdpEnabled: false, se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.edgechromium: false, ie.edgepath: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ie.ignoreprocessmatch: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: false, initialBrowserUrl: , nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: ba09033f-fb87-4d93-860f-8fb71f65bbf5

**Comment by xiaomeinvG** [comment]
从执行日志看未执行的步骤是由于webdriver已经执行结束，报告对于没有结果的步骤不做判断，那么当前的报告结构是正确的。
