### ISSUE TITLE
[BUG]admin上传了一个文件，在api的用例中引用到该文件，实际项目的普通成员去使用时，提示没有权限

### ISSUE THREAD

**Issue by liangsc-test** [metersphere/metersphere#33919]
### 联系方式

MeterSphere 交流群49：梁世聪

### MeterSphere 版本

 v2.10.20-lts

### 使用外置数据库

否

### 问题描述

admin上传了一个文件，在api的用例中引用到该文件，实际项目的普通成员去使用时，提示没有权限
必须得把普通成员设置为管理员才能用这个用例

### 重现步骤

1、在一个接口项目中，admin上传一个pdf文件，然后在测试用例中引用该文件
2、项目的普通成员进入到这个用例中，点击编辑，展开步骤设置，确保能看到这个请求参数中的文件
3、报错了
![image](https://github.com/user-attachments/assets/3242d77b-1a91-4599-ad48-45671c333c81)

### 期待的正确结果

实际上项目的普通成员已经具备对用例的增删改查功能，并不需要超管权限。麻烦确认一下

**Comment by 13290445582** [comment]
您好，请检查下您所登录用户的用户组是否有文件的查询权限。
<img width="934" alt="image" src="https://github.com/user-attachments/assets/567a4f16-46ac-4dbd-89c9-b14907ccb7c1">

**Comment by liangsc-test** [comment]
已确认，由于版本差异的原因，之前的【项目成员（系统）】不保留有文件查询的权限，需要手动编辑新增。
