### ISSUE TITLE
[BUG]自建筛选器的结果没有模块视图了，筛选结果无法初步评估

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33925]
### MeterSphere 版本

v3.4.0-17680ae6

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/0d8c629f-f357-4c5d-85df-911029ce2fd8)

### 重现步骤

[BUG]自建筛选器的结果没有模块视图了，筛选结果无法初步评估

**Comment by henbell2** [comment]
另外自建筛选title显示不全，但是所在区域留空白又很大，此处可以优化

**Comment by 13290445582** [comment]
您好，目前的设计实现就是筛选后不显示左侧模块。若您有好的建议可提FEATURE给产品同事调研评估下，感谢您的支持！
