### ISSUE TITLE
[FEATURE]actuator未授权访问漏洞

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33927]
### MeterSphere 版本

v2.10.20-lts

### 请描述您的需求或者改进建议

访问http://ip:8082/actuator/prometheus等actuator端点可以查看应用敏感信息，建议引入相关安全配置。
参考配置：
![6347215b530b50c07898edabf820d31](https://github.com/user-attachments/assets/415ccfdf-491b-49a9-a409-49c152b38870)
![image](https://github.com/user-attachments/assets/753cdbc0-4976-46c3-b23e-1f34753bdae5)

### 请描述你建议的实现方案

![6347215b530b50c07898edabf820d31](https://github.com/user-attachments/assets/19ddc69e-eb5b-4a21-a924-92d978bd9ec7)

**Comment by fit2-zhao** [comment]
修改 
docker-compose-node-controller.yml 
添加
MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=false
