### ISSUE TITLE
[BUG]测试计划中页面展示有效面积太小，页面空间规划不合理的问题还在

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33921]
### MeterSphere 版本

v3.4.0-17680ae6

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/e9a3be18-aae3-4cac-b99a-287cdfa51e7b)

### 重现步骤

[BUG]测试计划中页面展示有效面积太小，页面空间规划不合理的问题还在

**Comment by henbell2** [comment]
关联的Issue：https://github.com/metersphere/metersphere/issues/33639

**Comment by luty2018** [comment]
已确认是bug， 我们尽快修复

**Comment by luty2018** [comment]
已经更新了， 可以升级试试哈！

**Comment by henbell2** [comment]
在线升级吗，啥命令啊？有离线包不？

**Comment by liuruibin** [comment]
https://community.fit2cloud.com/#/products/metersphere/downloads

**Comment by henbell2** [comment]
包已经替换是吧，OK
