### ISSUE TITLE
[BUG]k8s部署MeterSphere v3版本，websocket连接容易异常响应

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33939]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

k8s部署MeterSphere v3版本，websocket连接异常响应。
例如导出功能用例和接口场景调试会用到websocket，执行三五次可能才会出现一次成功的结果。

![image](https://github.com/user-attachments/assets/0c54c5ea-19e0-49f2-9e66-72e7e6134211)

### 重现步骤

1、客户环境异常时
![image](https://github.com/user-attachments/assets/ea1e9495-bf97-4732-84d6-589a86d16108)
{"fileId":"173042782822000000","taskId":"","count":0,"isSuccessful":false,"msgType":"EXEC_RESULT","successful":false}
2、客户环境正常时
![68ea0f89aa2b533dd180839a0b39a57](https://github.com/user-attachments/assets/0c9a8d55-b05a-4851-9490-801e1cc27a45)
3、异常日志
[info.zip](https://github.com/user-attachments/files/17595375/info.zip)

**Comment by liuruibin** [comment]
当前站点配置的地址可以在task-runner pod访问到吗？

**Comment by shenshu0** [comment]
您好，请问问题解决了吗，我也遇到了这个问题，我的版本是3.3.0
java.nio.channels.ClosedChannelException: null

**Comment by youliyuan-fit2cloud** [comment]
> 您好，请问问题解决了吗，我也遇到了这个问题，我的版本是3.3.0 java.nio.channels.ClosedChannelException: null

你好，我们没有复现，上诉用户反馈大概率是k8s 环境配置问题，请先自行检查一下哈。

**Comment by shenshu0** [comment]
谢谢，修改 Docker配置，后我解决了问题：Insecure Registries:0.0.0.0:8081

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
