### ISSUE TITLE
[FEATURE功能测试用例执行的统计情况，建议可以和模块选择联动

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33936]
### MeterSphere 版本

v3.4.0-17680ae6

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/4274f015-f80a-4b5c-8edd-64dd2b687c85)

**Comment by sunnyIsBC2** [comment]
这个建议不太好，显示逻辑太混乱了

我觉得不如做个报表视图之类的页面来实现

**Comment by henbell2** [comment]
收到，报表当然更好！

**Comment by luty2018** [comment]
两位的建议我这边都收到了，已纳入规划哈！
