### ISSUE TITLE
[FEATURE]web浏览器上传文件后，无法找到对应路径，需要从日志里面获取，不方便引用文件

### ISSUE THREAD

**Issue by kaypan2020** [metersphere/metersphere#33952]
### MeterSphere 版本

 v2.9.0-426de152

### 请描述您的需求或者改进建议

在接口调试过程中，上传了CSV文件，后续在自定义脚本时候需要引用文件获取CSV的行数。但是路径一直没有找到，项目文件里面的路径http://minio:9000/metersphere/f7ddd9a7-fadc-4bda-8d87-c93ea970123/XXX.csv 也是错误的。后续了解到web上传文件后，会生产随机前缀，例如：上传的文件名称是 spusub，上传后，完整的名称变成了 1a928d6e-a49_spusub.csv   ，导致每次传文件后都需要去日志拿到正确的路径，不方便实际项目使用

### 请描述你建议的实现方案

文件上传后，希望页面能显示该文件的正确路径地址，方便引用

**Comment by fit2-zhao** [comment]
从文件安全的角度来看，目前脚本不支持直接读取系统中上传的 CSV 文件。若需使用自定义文件，请采用自定义挂载方式。
