### ISSUE TITLE
[BUG]关联用例时弹出显示鼠标滑到的模块名称没有意义(没有带来更多的信息展示或者操作)，并且明显干扰查看上下模块名称，干扰checkbox勾选

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33957]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/f92db665-ffd9-404b-a1a0-2f6a4e14ef55)

### 重现步骤

[BUG]关联用例时弹出显示鼠标滑到的模块名称没有意义(没有带来更多的信息展示或者操作)，并且明显干扰查看上下模块名称，干扰checkbox勾选

**Comment by luty2018** [comment]
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/2eaeec69-e3e6-4aa3-b7cc-7b3d57b08e12">
请问是在哪个页面？系统正常是在右上方展示名称，不会造成干扰，如果模块名称较长或者层级较深，还是非常需要这个功能的。

**Comment by henbell2** [comment]
右侧小弹窗区域，浮动字符串都是盖住下方元素的
![image](https://github.com/user-attachments/assets/e87f12c1-ea32-4984-a6e3-8a5ce6df12a5)

**Comment by henbell2** [comment]
或者用例筛选的时候使用“所属模块”，下图

**Comment by henbell2** [comment]
或者用例筛选的时候使用“所属模块”，下图
![image](https://github.com/user-attachments/assets/7a703c81-ac1f-43c4-8110-0f205862d85c)

**Comment by luty2018** [comment]
收到， 我们改成在中间展示，下个版本哈。

**Comment by henbell2** [comment]
收到，还有这里，Case的ID号也会弹个浮窗，感觉此处着实没啥必要，参考哈
![image](https://github.com/user-attachments/assets/0179cfc6-c187-431f-bed3-83eb64d01228)

**Comment by 13290445582** [comment]
您好，V3.5已优化该问题，请升级。
