### ISSUE TITLE
[FEATURE]空白区域上滚触发时机不合理(见图)

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#33986]
### MeterSphere 版本

v3.4.0-5291ac9a

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/c6ef227a-19e5-4e1d-8cae-282ce7af76b3)

**Comment by luty2018** [comment]
这里涉及到表格展示10条以上数据时也会产生滚动条，所以选择了目前这种方案。
