### ISSUE TITLE
[BUG] 麻烦问一下，升级到3.4.0以后，同步到禅道的图片还是无法显示，要怎么解决

### ISSUE THREAD

**Issue by ye0061** [metersphere/metersphere#33997]
### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

bug同步禅道以后图片还是无法显示
![317a0425703379dc5ddefe90f623021](https://github.com/user-attachments/assets/7e89f979-70d6-4568-a94c-13d4722d6d89)

### 重现步骤

在metersphere新建bug，并包含图片，同步到禅道

### 期待的正确结果

图片正常显示

**Comment by youliyuan-fit2cloud** [comment]
https://github.com/metersphere/metersphere-platform-plugin/releases
下载最新的zentao插件试试吧，我们测试没问题。
