### ISSUE TITLE
[BUG]功能用例导出为xmind再导入会报错 “Index 1 out of bounds for length 1”

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#33991]
### 联系方式

蒋林峰

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

功能用例导出为xmind再导入会报错 “Index 1 out of bounds for length 1”

### 重现步骤

1、将功能用例导出为xmind，勾选所有字段。
![image](https://github.com/user-attachments/assets/a9a6196c-8f8c-4904-bf70-87225129f545)
2、再将功能用例导入MeterSphere，报错校验失败。
![image](https://github.com/user-attachments/assets/0de47210-62a0-4d51-bca1-56ac6316b131)

### 期待的正确结果

导入成功

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，v3.5版本已修复，请升级。
