### ISSUE TITLE
[BUG]系统设置-系统-资源池-编辑，顶部的菜单栏会显示License按钮

### ISSUE THREAD

**Issue by zxz0x01** [metersphere/metersphere#33996]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

是

### 问题描述

系统设置-系统-资源池-编辑，顶部的菜单栏会显示License按钮
![image](https://github.com/user-attachments/assets/e0f2de3c-673d-429d-a456-f4e6f462f6a0)

### 重现步骤

系统设置-系统-资源池-编辑

### 期待的正确结果

要么其他地方也一起把License按钮放出来，要么都藏起来

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
