### ISSUE TITLE
[BUG]关联测试用例时，用例数量多时会导致崩溃

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#340]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.2.0

**Bug 描述**
简要描述您碰到的问题
在测试计划中关联测试用例，如果该项目中的测试用例太多，系统会假死然后指向错误页面（测试数据是2万多个用例），建议此处不要直接加载全部用例，选择模块时才加载对应模块的用例

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
建议此处不要直接加载全部用例，选择模块时才加载对应模块的用例

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
你好，1.4版本已修复，请升级验证
