### ISSUE TITLE
[FEATURE]导入swagger是否可以根据请求类型和路径判断唯一？因为接口名称是有会变更

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#34000]
### MeterSphere 版本

v2.10.14-lts

### 请描述您的需求或者改进建议

导入swagger是否可以根据请求类型和路径判断唯一？因为接口名称是有会变更
当接口名称变，请求类型和路径不变情况下，会被当成新的接口创建

**Comment by luty2018** [comment]
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/9089f2d4-fe0b-4749-809f-9f90a5fc6f00">
检查这个配置是否关闭状态， 关闭状态时是根据请求类型和路径来判断唯一。

**Comment by SloanGao** [comment]
好的，謝謝
