### ISSUE TITLE
[BUG]用例详情页点击上一个/下一个按钮，用例标题和编号有更新，但详情内容还是上一个用例的内容，没有更新显示

### ISSUE THREAD

**Issue by shuiniwa** [metersphere/metersphere#34004]
### 联系方式

z13542825587@163.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

[BUG]用例详情页点击上一个/下一个按钮，用例标题和编号有更新，但详情内容还是上一个用例的内容，没有更新显示

### 重现步骤

用例列表，点击某个用例，右侧展开用例详情，详情页点击上一个/下一个按钮，用例标题和编号有更新，但详情内容还是上一个用例的内容，没有更新显示

### 期待的正确结果

标题，编号，内容，都应更新

### 附加信息

![20241105163832](https://github.com/user-attachments/assets/468f75a9-562a-4354-9adf-2d2fdeecd41b)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现。升级到最新版本v3.4，

**Comment by shuiniwa** [comment]
> 你好，没有复现。升级到最新版本v3.4，

![20241106173318](https://github.com/user-attachments/assets/e2caaf44-81a1-45b5-891b-46f2f1052ed1)
是v3.4版本的
