### ISSUE TITLE
[BUG]性能测试报告测试概览的TPS值跟Jmeter 运行日志的值不一致，慢一拍

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#34003]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

性能测试报告测试概览的TPS值跟Jmeter 运行日志的值不一致，慢一拍

### 重现步骤

1、执行性能测试，生成最新的性能测试报告，查看性能测试报告测试概览中某一时刻的TPS值
<img width="415" alt="6f68cf5d86e237916839b7115846e69" src="https://github.com/user-attachments/assets/01e242ec-be85-4528-93c0-d367c8e445c1">

2、查看性能测试日志的值，发现不一致，慢一拍
<img width="842" alt="cee59f10cd8932e419e4b575a04dbc1" src="https://github.com/user-attachments/assets/50f2a4cd-a79f-4679-baec-13313ad2944c">

### 期待的正确结果

性能测试报告测试概览的TPS值跟Jmeter 运行日志一致

**Comment by liuruibin** [comment]
控制台日志输出的时间间隔不齐，不是严格按照0 5 10 这样格式的。我们处理数据的时候会把时间拟合到0 5 10 这样的点上


设计如此
