### ISSUE TITLE
[BUG]创建测试计划时，重复关联同一个场景，应该显示用例数为1条，而不是关联几次就显示几条

### ISSUE THREAD

**Issue by kanna001** [metersphere/metersphere#34011]
### MeterSphere 版本

V3.3.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/6a1aa2dc-e653-44ce-a5a3-17c24b982dc0)
![image](https://github.com/user-attachments/assets/70e526ed-4513-46d2-bb2a-04b196fc437f)

### 重现步骤

1. 【测试计划】->【计划】tab页签->【新建】
2. 填写【计划名称】，【创建】
3. 【测试规划】->【场景用例】->【业务流程验证】->点击【0条 用例数】
4. 选择A场景，点击【关联】
5. 【0条 用例数】变为【1条 用例数】
6. 再次点击【1条 用例数】，再次选择A场景，点击【关联】
7. 【1条 用例数】变为**【2条 用例数】**

### 期待的正确结果

6. 再次点击【1条 用例数】，**期望已经被关联的A场景显示已被勾选**
![image](https://github.com/user-attachments/assets/bcdbba0f-5b22-46b4-8df0-a01a75fa4a1f)
7. 仍然显示【1条 用例数】，两次都是关联的A场景，应该显示**【1条 用例数】**

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划未开启可重复关联用例时，再次点击关联用例，关联列表中不会显示已关联的。测试规划页面的关联用例是已关联的所有用例，不是本次点击关联的。
如果测试计划开启了可重复关联用例，可以多次关联同一用例，统计时不会去重。

**Comment by kanna001** [comment]
好的，了解了，谢谢
