### ISSUE TITLE
[FEATURE]测试报告中场景明细表格设置里是否可以添加耗时统计？

### ISSUE THREAD

**Issue by YellCatt** [metersphere/metersphere#34018]
### MeterSphere 版本

3.3

### 联系方式

768305875@qq.com

### 请描述您的需求或者改进建议

问题：测试报告中场景明细表格设置里是否可以添加耗时统计？
理由：测试用例耗时需要一直优化，有些时间太长的，不用通过点击详情里就可以知道

**Comment by luty2018** [comment]
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/a4f23431-1bd7-4545-b78a-a18350807479">
是指测试计划报告这里吗？

**Comment by YellCatt** [comment]
> <img alt="image" width="1265" src="https://private-user-images.githubusercontent.com/36292514/383448210-a4f23431-1bd7-4545-b78a-a18350807479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODE5ODcsIm5iZiI6MTczMDg4MTY4NywicGF0aCI6Ii8zNjI5MjUxNC8zODM0NDgyMTAtYTRmMjM0MzEtMWJkNy00NTQ1LWI3OGEtYTE4MzUwODA3NDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA4MjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YTUyZGI4ZTMwMTk1ZDU5NjdkNjVmMDY2OGU5ODUwY2EzZWVkZmMxMDI1NmM1ZTVjY2ZiNGQyZDE1ZjY1MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ax6E2hLbhID3meWYVkLvDv13zgWmj5YbS97Fn8yUFSk"> 是指测试计划报告这里吗？

是的，就是下面的场景明细的列表，添加一个耗时统计。

**Comment by luty2018** [comment]
已规划到v3.6

**Comment by youliyuan-fit2cloud** [comment]
v3.6已发布，升级一下试试吧。
