### ISSUE TITLE
[BUG]接口自动化场景步骤较多时存在无法关闭场景或显示异常情况

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#34010]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

是

### 问题描述

1、创建场景自动化，最外层步骤20个，包括事务控制器、循环控制器，执行正常。
2、运行一段时间过后再次打开场景，无法完整显示场景步骤，复制场景后问题相同。
![场景显示异常](https://github.com/user-attachments/assets/613eaafd-c5bb-42ec-a838-f185a89d4b57)
3、异常场景打开后点击左上角关闭无响应，控制台报错。
![控制台报错](https://github.com/user-attachments/assets/4ece047e-8353-4e62-b483-0fd610ea2aab)
4、访问异常场景时控制台报错
![访问异常场景时控制台报错](https://github.com/user-attachments/assets/67c2852e-4e9b-40ec-8d59-217e419095e8)
5、异常场景偶尔页面显示正常，但添加步骤、保存、关闭场景等操作均无响应，添加到测试计划中可正常执行场景。

### 重现步骤

建议构建事务控制器、循环控制器，且步骤超20步，目前仅复杂场景遇到这个问题

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现该问题，建议升级一下哈，感谢理解和支持。还本地机器、服务器配置都有关系，api-test容器的可以使用最大内存有限制，可以改大一些。然后尝试否是仍会遇到这种问题。

**Comment by youliyuan-fit2cloud** [comment]
/
Duplicate of #30531

**Comment by ywang9-12** [comment]
> 你好，最新版本没有复现该问题，建议升级一下哈，感谢理解和支持。还本地机器、服务器配置都有关系，api-test容器的可以使用最大内存有限制，可以改大一些。然后尝试否是仍会遇到这种问题。

你好，已升级至v2.10.21-lts版本，并修改api-test容器最大内存为3G（已使用828M），仍存在此问题，查看控制台js报错TypeError: Cannot read properties of undefined (reading 'key')
