### ISSUE TITLE
[BUG]接口和用例参数没有差异的时候，不应该显示[接口参数发生变更 接口与用例差异对比]

### ISSUE THREAD

**Issue by kanna001** [metersphere/metersphere#34022]
### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

接口和用例参数没有差异的时候，**不显示**[接口参数发生变更 接口与用例差异对比]
![image](https://github.com/user-attachments/assets/d03c1856-2997-48b2-a978-f0fe4382b295)
![image](https://github.com/user-attachments/assets/e1e571ea-268a-4d6b-9e21-ffe09932b79e)

### 重现步骤

1.创建一个接口A，请求头不维护数据
2.在这个接口下创建用例a，请求头增加2个参数
3.维护接口A中的请求头中的参数
4.用例ID后面显示[接口参数发生变更 接口与用例差异对比]

### 期待的正确结果

4.如果接口和用例参数没有差异的时候，用例ID后面**不显示**[接口参数发生变更 接口与用例差异对比]

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
你好，经研发确认，该提示表示, 接口定义存在变更, 并不是定义与用例有差异.

所以就算用例参数补充一致, 也会存在提示, 点进去对比差异后会清除该标识.感谢理解和支持。
