### ISSUE TITLE
[BUG]编辑测试用例，服务端执行时，断言状态码重复了

### ISSUE THREAD

**Issue by kanna001** [metersphere/metersphere#34044]
### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/d588f9fd-df51-4117-9aeb-4d3c5aa97134)
![image](https://github.com/user-attachments/assets/6286de14-1310-4154-bf39-cfb8d135420d)

### 重现步骤

1.编辑测试用例，设置状态码断言200
2.点击服务端执行
3.查看响应内容-断言
      实际结果：状态码断言显示了2次(不知道是断言了2次，还是页面数据重复显示)

### 期待的正确结果

3.查看响应内容-断言
      预期结果：状态码断言只断言1次，且页面也只显示断言1次

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/01e50f67-53c8-45e8-83f8-50efe783c194)

请检查下你的环境里面是否配置同样的状态码断言。

**Comment by kanna001** [comment]
![image](https://github.com/user-attachments/assets/90d483a4-1c90-47a2-af04-1d94b64fe634)
配置了
