### ISSUE TITLE
[BUG] 更改安装路径不生效

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34043]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

我同时安装v2和v3，已安装了v2版本，更改install.conf里安装路径，然后运行install.sh脚本，还是提示在/opt/metersphere进行升级

### 重现步骤

![image](https://github.com/user-attachments/assets/3da08ad8-7270-4155-b1d4-a75bdcb5d8a8)

![image](https://github.com/user-attachments/assets/0c92760a-c8fc-4a7d-8acb-29080b8d32c1)

### 期待的正确结果

不提示升级

**Comment by youliyuan-fit2cloud** [comment]
你好，建议先把v2卸载之后再安装v3版本。
