### ISSUE TITLE
[BUG]  移动用例到其他目录操作， 保存使用不方便（目录层级很多，每次都需要滚到最底下才能点确定）

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34042]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

移动用例到其他目录操作， 保存使用不方便（目录层级很多，每次都需要滚到最底下才能点确定）

### 重现步骤

![企业微信截图_17307054324058](https://github.com/user-attachments/assets/e3bb83d9-746a-4839-9e2a-82a5ef3f6493)
**目录层级很多，每次都需要滚到最底下才能点确定**
![企业微信截图_17307014926370](https://github.com/user-attachments/assets/e1f2c152-048f-4cf0-b929-2fbc76eb1123)

**Comment by youliyuan-fit2cloud** [comment]
你好，有搜索功能可以用，先关键字搜索会好多吧。
