### ISSUE TITLE
[BUG]任务中心中的系统即时任务ID重复，当前每天都会从100001编号重新开始编号

### ISSUE THREAD

**Issue by xueqidove** [metersphere/metersphere#34056]
### 联系方式

无

### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

任务中心/系统即时任务中的任务ID存在重复，自从平台升级后，貌似是每天都从100001重新开始编号，如下图所示：
![image](https://github.com/user-attachments/assets/1e5ac7a4-422c-45db-85b5-2e0ab7d20edf)

### 重现步骤

每天执行一次测试任务即可。

### 期待的正确结果

任务ID在平台中保持唯一

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
