### ISSUE TITLE
[BUG] 禅道关联项目配置时，产品key未作校验

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34052]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/6d0f035b-6bc8-4a05-8d48-e646c96e5229)

### 重现步骤

如图所示，当修改产品key后，鼠标离开未发送网络请求进行验证，需要修改一下项目key才会发起网络验证

**Comment by 13290445582** [comment]
您好，当范围选择产品时，是会验证的。您上图显示范围选择的项目，有的项目就没有产品key，所以这里并未进行验证，感谢您的理解与支持。
