### ISSUE TITLE
[BUG]引用用例时，提取参数内容和断言没有实时生效

### ISSUE THREAD

**Issue by kanna001** [metersphere/metersphere#34068]
### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

引用用例时，提取参数内容和断言没有实时生效

### 重现步骤

1.创建接口A，且在接口A下创建用例a(用例a未加提取参数和断言)
2.创建场景AA，引用用例a
3.修改用例a，增加提取参数和断言内容
4.执行场景AA

### 期待的正确结果

预期结果：执行的场景AA后，报告中可以看到提取的参数内容和断言内容
实际结果：执行的场景AA后，报告中没有看到提取的参数内容和断言内容。需要删掉引用的用例a，再重新引用用例a才可以
![image](https://github.com/user-attachments/assets/8427d06f-185f-4767-8c8f-75f610baa2e9)
![image](https://github.com/user-attachments/assets/15de357d-44db-4855-a7af-b09a2be5710a)

**Comment by 13290445582** [comment]
您好，按照您描述的操作未复现该问题，麻烦自行检查下：用例增加提取和断言后，查看场景处步骤是否更新，用例增加提取和断言后是否保存成功。可提供下完整录屏看下。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
