### ISSUE TITLE
[BUG] 集成禅道后，自动获取的禅道模板里当前指派列表用户不全

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34063]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

集成禅道后，自动获取的禅道模板里当前指派列表用户不全
![image](https://github.com/user-attachments/assets/135f5e00-a77e-48f8-8b17-1036bb3c99f2)

### 重现步骤

禅道插件版本：
![image](https://github.com/user-attachments/assets/ec264ee1-bebc-4808-84ba-5a9eee5b60a9)

集成禅道，创建权限，选择禅道默认模板，点击当前指派

**Comment by 13290445582** [comment]
您好，已有用户反馈，issue关联https://github.com/metersphere/metersphere/issues/33403
