### ISSUE TITLE
[BUG]接口列表的case列表样式问题

### ISSUE THREAD

**Issue by Triangel1314** [metersphere/metersphere#3407]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.0
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/56533158/120276856-d1515600-c2e5-11eb-8782-16c40e4cf52c.png)
前半段和后半段的“操作”错位
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by xulinde** [comment]
v1.10.2版本已修复
