### ISSUE TITLE
[BUG] 从测试报告处跳转自动化用例后 切换项目会出现用例不消失

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34072]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

一个空间下有两项目，从其中一个项目的测试计划报告处点击连接跳转到编辑页面
![image](https://github.com/user-attachments/assets/638270f2-82c7-465c-81d3-6de09abbb495)

这时候如果点击左上角切换项目
![image](https://github.com/user-attachments/assets/3d514fe1-0570-4b12-9a9d-473cc7c5c905)

这个用例所属模块等信息就被《带到》了另一个项目里

![image](https://github.com/user-attachments/assets/f84799e2-1564-4c16-9f1e-2b82f141d9f6)

如果这时候重新选模块 点击保存，则一些信息就会被错误的更新到当前用例里

### 重现步骤

如上所述

### 期待的正确结果

建议重置页面信息，并且关闭多余tab

**Comment by 13290445582** [comment]
感谢反馈。后续版本修复。

**Comment by 13290445582** [comment]
这种跳转的页面，要保证表格那边的自动刷新、浏览器自动刷新之后依然展示跳转后的内容，都会在url上留有查询条件
这种查询条件是不会被切换项目清空的。
有很多操作（包括但不限于切换项目、F5重置搜索条件等）在这个tab上都无法操作。这是V2的局限性。
非常抱歉不再处理这里了。
