### ISSUE TITLE
[BUG]创建缺陷，编辑缺陷内容时粘贴图片，图片变模糊，保存之后打开查看也很模糊

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#34077]
### 联系方式

jianmin.pu@fit2cloud.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

创建缺陷，编辑缺陷内容时粘贴图片，图片变模糊，保存之后打开查看也很模糊

### 重现步骤

1.创建缺陷，编辑缺陷内容，粘贴图片，图片变模糊
![image](https://github.com/user-attachments/assets/259e130d-aee4-41cc-bf6b-1f86bf0600b2)
2. 保存后，点击图片打开链接查看，图片也很模糊
![image](https://github.com/user-attachments/assets/36cf53d0-2af8-499f-95c4-8cf3921f2005)

### 期待的正确结果

编辑缺陷内容时粘贴图片以及后续打开图片，能保持图片原来的清晰度

**Comment by 13290445582** [comment]
您好，您这图片是截屏的图片吗，可以发来帮助下复现，我们本地截取的图片上传上去还是很清晰的。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～

**Comment by lyons-hz** [comment]
不是上传哦，是直接在内容里面ctrl+V粘贴图片
