### ISSUE TITLE
[BUG]进入消息通知全部消息显示为0，需要点击一次全部消息才能展示消息通知

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#34075]
### 联系方式

jianmin.pu@fit2cloud.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

进入消息通知全部消息显示为0，需要点击一次全部消息才能展示消息通知

### 重现步骤

1.进入消息管理，全部消息显示为0
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/56aaa4ce-c66f-436e-b2c6-83f530e1f37b">

2.管理员修改处理人
![image](https://github.com/user-attachments/assets/ab228616-8ad6-4b93-8f7f-d71b613bb234)

3.被指定责任人未收到消息通知
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/fb3194ca-2ba9-4708-b82e-f173969de8cd">

4.被指定责任人点击全部消息，才能收到消息通知
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/59d7cd5b-754b-4720-8525-70623163b70e">

### 期待的正确结果

打开消息通知可以正常展示全部消息及未读消息

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
