### ISSUE TITLE
[FEATURE]缺陷管理权限需要设置的更精细，需要设置角色只能编辑缺陷中指定的内容。如：研发不能修改缺陷内容，只能修改自己所负责缺陷的状态，其他人员只能评论。

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#34082]
### MeterSphere 版本

v3.4.0

### 联系方式

jianmin.pu@fit2cloud.com

### 请描述您的需求或者改进建议

缺陷管理权限需要设置的更精细，需要设置角色只能编辑缺陷中指定的内容。如：研发不能修改测试人员创建的缺陷内容，只能修改自己所负责缺陷的状态。类似禅道。

### 请描述你建议的实现方案

缺陷管理-编辑权限下可以选择更细分的权限，指定角色可以编辑缺陷中的哪些模块。

**Comment by luty2018** [comment]
暂时没有这个规划哦。
