### ISSUE TITLE
[BUG]【接口自动化】外部挂载python后，自定义脚本引用python中requests包，经常出现异常情况。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34081]
### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】外部挂载python后，自定义脚本引用python中requests包，经常出现异常情况。

### 重现步骤

【接口自动化】外部挂载python后，自定义脚本引用python中requests包，经常出现异常情况。
![image](https://github.com/user-attachments/assets/658efc72-601b-4912-bea2-1209fe4ea4ce)
![1731061037347](https://github.com/user-attachments/assets/228f677f-641a-4027-9bb8-c92c60f91e41)

**Comment by fit2-zhao** [comment]
挂载的环境需要自行排查一下，这种三方包情况比较多很难一一帮助排查，也可以参照这个有没有帮助：
https://github.com/metersphere/metersphere/issues/31811
