### ISSUE TITLE
[FEATURE]缺陷管理中设置的视图筛选条件需要可以保存，用户切换页面，甚至重新登录后仍然保持自己设置的筛选条件。

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#34083]
### MeterSphere 版本

v3.4.0

### 联系方式

jianmin.pu@fit2cloud.com

### 请描述您的需求或者改进建议

设置的视图筛选条件需要可以保存，用户切换页面，甚至重新登录后仍然保持自己设置的筛选条件。目前比如在缺陷管理设置的视图筛选条件在切换页面或者重新登录后，会自动切回全部数据视图。

**Comment by youliyuan-fit2cloud** [comment]
你好，当前版本已支持啦，创建新视图选中保存后会记录当前选择
![image](https://github.com/user-attachments/assets/8da8c1be-293c-427a-86af-c3c4c2ed543e)
