### ISSUE TITLE
[QUESTION] Gitlab CI/CD如何集成V3版本？

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34086]
### 请描述您的问题

我看网上都是V2版本，请问V3版本有相关操作教程吗？需要注意什么事项？

https://zhuanlan.zhihu.com/p/542035632

**Comment by liuruibin** [comment]
差别不大，把接口导入到v3里。脚本几乎一致

**Comment by 2lipan** [comment]
https://kb.fit2cloud.com/?p=f734b32b-e799-4709-b8cd-44a03bff2e73 参考这个试试
