### ISSUE TITLE
[BUG] 角色列表没有国际化

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#34089]
### MeterSphere 版本

v1.20.20-lts

### 使用外置数据库

否

### 问题描述

角色列表没有国际化，在其他s页面与角色相关的，也就没有国际化了，比如空间成员列表和项目成员列表中的成员角色。

![image](https://github.com/user-attachments/assets/88d171f0-165b-4e74-abc1-c278c2df5ed8)

### 重现步骤

查看角色列表

**Comment by liuruibin** [comment]
抱歉，系统内置的角色通过初始化脚本写入数据库并没有考虑到这里

**Comment by youliyuan-fit2cloud** [comment]
暂不支持，感谢理解和支持。
