### ISSUE TITLE
[BUG] 测试用例进行接口关联，不展示相关模块下的接口

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34091]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

如图，接口全部为0

![image](https://github.com/user-attachments/assets/c3644a53-ac80-455a-b380-f462e075127d)

实际接口：
![image](https://github.com/user-attachments/assets/019e5678-7218-4b29-8e7a-388b5f7b7638)

### 重现步骤

点击测试用例，新建测试用例，保存成功，然后编辑，点击用例选项卡，关联用例，选择接口用例

**Comment by youliyuan-fit2cloud** [comment]
你好，你的第二个截图是接口的列表，不是接口用例。请再看下接口下是否存在接口用例。
![Uploading image.png…]()

测试用例关联接口用例页面是关联接口用例，不能关联接口。
