### ISSUE TITLE
[BUG]其中一个项目下测试用例已经建了很多模块，但在创建测试计划时，一个模块都关联不上(另一个项目下正常)---貌似是手动创建的，该Issue可关闭

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34098]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/cb7f6828-ce1c-4ed1-9e19-533f36510d22)

### 重现步骤

[BUG]其中一个项目下测试用例已经建了很多模块，但在创建测试计划时，一个模块都关联不上(另一个项目下正常)

**Comment by youliyuan-fit2cloud** [comment]
你好，创建测试计划的模块是测试计划页面 存在的“测试计划”的模块 ，和测试用例页面下的模块没有关联关系。
