### ISSUE TITLE
[BUG] Mock环境配置多了个https://，但是展示框又不能编辑，无法修改导致mock时候会报错

### ISSUE THREAD

**Issue by xhy12** [metersphere/metersphere#34090]
### MeterSphere 版本

2.10.19

### 使用外置数据库

否

### 问题描述

  Mock环境配置多了个https://，但是展示框又不能编辑，无法修改导致mock时候会报错

### 重现步骤

 Mock环境配置多了个https://，但是展示框又不能编辑，无法修改导致mock时候会报错
)
![image](https://github.com/user-attachments/assets/9a91aa14-a379-4918-8ba2-96201bb26db3)
![image](https://github.com/user-attachments/assets/8c8dbe65-fd07-419d-a8c3-14b5fe5f2541)

### 期待的正确结果

mock 不会重复展示https

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现，可以删掉MOCK环境，然后接口测试TEST接口会自动创建新的。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
