### ISSUE TITLE
[BUG]测试跟踪-测试计划，目录树没有了

### ISSUE THREAD

**Issue by fizzhu97** [metersphere/metersphere#34099]
### 联系方式

89010345@qq.com

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

如图，2.10.16版本，测试跟踪-测试计划是有一个目录树的，升级到2.10.21版本后，目录树没有了
![image](https://github.com/user-attachments/assets/089f6094-7fb9-4ae9-a969-7750be2810e0)

### 重现步骤

1、进入测试跟踪
2、点击测试计划

### 相关日志输出

```shell
跟2.10.16版本一样，保留测试计划的目录树
```

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请把打开控制台看看有没有报错？升级到版本号也发出来看看。还有如何升级的？

**Comment by henbell2** [comment]
v3.x版本也遇到过，目录树展开的小开关不见了。规律未知

**Comment by fizzhu97** [comment]
> 你好，没有复现该问题，请把打开控制台看看有没有报错？升级到版本号也发出来看看。还有如何升级的？

直接在线升级2.10.16到2.10.21

**Comment by fizzhu97** [comment]
![image](https://github.com/user-attachments/assets/3f930d3b-dc9c-4686-9dba-a87f1b46bffb)

**Comment by fizzhu97** [comment]
> > 你好，没有复现该问题，请把打开控制台看看有没有报错？升级到版本号也发出来看看。还有如何升级的？
> 
> 直接在线升级2.10.16到2.10.21，升级后是必现的
@youliyuan-fit2cloud

**Comment by youliyuan-fit2cloud** [comment]
> > > 你好，没有复现该问题，请把打开控制台看看有没有报错？升级到版本号也发出来看看。还有如何升级的？
> > 
> > 
> > 直接在线升级2.10.16到2.10.21，升级后是必现的
> > @youliyuan-fit2cloud

再换个浏览器，重启服务 尝试是否解决？如果仍然存在，要看看具体环境了，可以加我们企业微信远程看看，企业微信码：
<img width="387" alt="image" src="https://github.com/user-attachments/assets/63fd7475-b904-488d-8f22-a767b0fa4695">

**Comment by fizzhu97** [comment]
重新reload后解决。reload之前status显示的各服务版本是2.10.7（最早完整安装的版本），reload之后显示的是2.10.21，也不存在上述问题了。
