### ISSUE TITLE
[FEATURE]非常希望脑图模式下的用例编写支持添加图片信息，本地xmind是支持图片的

### ISSUE THREAD

**Issue by awqinqing** [metersphere/metersphere#34108]
### MeterSphere 版本

v3.4.0

### 联系方式

awqinqing@163.com

### 请描述您的需求或者改进建议

![脑图模式编写用例支持图片](https://github.com/user-attachments/assets/f26f2194-7608-4bb2-beef-e46975122e3f)

**Comment by luty2018** [comment]
感谢您的建议，我们需要调研一下目前是用的脑图是否支持这个功能。
