### ISSUE TITLE
[BUG]Jenkins生成的报告链接在MS平台中调整报告有效时间后无法生效

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#34111]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

否

### 问题描述

在Jenkins中使用自由风格或者管道风格创建对应的脚本后，所生成的报告时效性无法修改。
且在MS平台中若对相应的报告有效时长进行修改会自动生成新的连接，并不是延长对应的报告连接时长。

### 重现步骤

1.先在Jenkins中新建item并选择Freestyle project或者Pipeline，选定测试计划后执行。
2.点击生成的测试报告。
3.设置MS平台中date时间，并调整为报告过期时间。
4.调整报告有效时长，并对其进行有效性的延长。
5.点击生成的报告，发现报告无法查看。(主要表现为：报告连接失效、页面相应404)

### 期待的正确结果

在MS平台中修改报告失效之后对应的报告连接应不变，而是直接延长报告的有效时间。

### 附加信息

![image](https://github.com/user-attachments/assets/85fb9f19-90c5-4c50-9099-1ef19777b902)
![image](https://github.com/user-attachments/assets/7448f42f-9964-4454-b1fe-e1a6ffc4b6c8)
![image](https://github.com/user-attachments/assets/9aa50019-e37a-4b06-85a7-f4fa6416e3fa)

**Comment by youliyuan-fit2cloud** [comment]
你好，看起来是在Jenkins生成报告之后，再修改的链接有效时长，这种情况已生成的报告不会延长有效时长，只对修改后的再生成的报告有效，感谢理解和支持。
