### ISSUE TITLE
[QUESTION] 导出接口测试用例的时候，怎么才能将api接口信息以及详细运行结果也导出？

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34119]
### 请描述您的问题

如图：

![image](https://github.com/user-attachments/assets/29021f62-ab4d-43a3-bc71-e324b26e5cc9)

我想导出相关的接口以及详细接口执行结果
![image](https://github.com/user-attachments/assets/0e18fb43-f80c-4648-b112-af3c59c65409)

**Comment by luty2018** [comment]
接口执行结果可以通过导出接口报告的方式
