### ISSUE TITLE
[FEATURE]MS平台证书配置中无法上传证书链文件

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#34113]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

否

### 问题描述

在MS2.0中无法上传证书链，在项目环境中不支持上传.pem格式的文件，导致证书链无法上传。

### 重现步骤

无

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题已转需求，待调研后回复。

**Comment by luty2018** [comment]
非常抱歉，短期规划不上了。
