### ISSUE TITLE
[BUG]MeterSphere 数据还原后, 新建任务ID会从100001编号重新开始

### ISSUE THREAD

**Issue by wangzhihaocom** [metersphere/metersphere#34118]
### 联系方式

wangzhihaocom@hotmail.com

### MeterSphere 版本

版本： v3.2.0

### 使用外置数据库

是

### 问题描述

Hello, 你好， 我有一个有关MeterSphere 数据备份与还原的问题， 我用的是MySQL外置数据库.. 我安装的是v3.2.0 EC2
我把现在的EC2 安装的MeteSphere 的MySQL外置数据库 与 /opt/metersphere/data 里面的 minio redis folder都备份了，

下面是我还原数据的Steps:

在一个新的 EC2 安装同一个版的MY SQL 和 安装了同一版的MeteSphere
用 mysql -u metersphere -p metersphere < metersphere.sql 把之前备份的metersphere.sql 导入mysql
tar -cvf ms_data_backup.tar
然后把整个 minio redis folder要都copy到 /opt/metersphere/data 来还原 minio 和 redis 目录数据
############
上面的都做完了 原来的所有 数据都在新的MeteSphere里，但是有一个问题
之前已经有写了很多测试用例（比如有10个）， 当我新建一个测试用例的时候， 新的用例的ID会再从 100001 来重头开始， 而不是从100011 开始，因为我之前已经有10个了， 所以现在搞到有很多ID是重复的，。 请问这个问题要怎样决解。。。请帮忙

<img width="1604" alt="image" src="https://github.com/user-attachments/assets/97129f82-6d9b-4b64-8738-29eb272f9947">

### 重现步骤

下面是我还原数据的Steps:

1. 在一个新的 EC2 安装同一个版的MY SQL 和 安装了同一版的MeteSphere
2. mysql -u metersphere -p metersphere < metersphere.sql 把之前备份的metersphere.sql 导入mysql
3. tar -cvf ms_data_backup.tar. 然后把整个 minio redis folder要都copy到 /opt/metersphere/data 来还原 minio 和 redis 目录数据

############
上面的都做完了 原来的所有 数据都在新的MeteSphere里，但是有一个问题
之前已经有写了很多测试用例（比如有10个）， 当我新建一个测试用例的时候， 新的用例的ID会再从 100001 来重头开始， 而不是从100011 开始， 所以新建测试用例 ID 重头开始， 我原来的数据里有好几百好的测试用例，。现在有很多测试用例的ID都是重复的

### 期待的正确结果

期待的正确结果是：

如果之前的MYSQL里的备份里有 100个任务ID到 100100 ， 那么我把原有的MYSQL里的数据import后  ， 然后我新建一个任务， 那么ID应该是从100101 开始， 不应该从100001编号重新开始

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/03cec674-7e7f-4388-a49c-bc46e4de363d">

**Comment by fit2-zhao** [comment]
用 Redis client 连接 查询一下数据是否还存在；如果外置的 Redis 启动时是否挂载了文件目录：

`docker run --name redis -d -v /opt/metersphere/data/redis:/data -p 6379:6379 redis`

**Comment by wangzhihaocom** [comment]
@fit2-zhao  请问要怎样查询数据。 
以前的数据是存在的，我已经import 到mysql里。而Redis，我没有用外置的， 我是直接用docker里面的。 只是mysql用的个外置。
当我做数据备份的时候， 我把整个data的数据做备份的 （我是按这里讲的做 https://metersphere.io/docs/v3.x/installation/backup_data/#12）

`tar -cvf ms_data_backup.tar /opt/metersphere/data`

然后当我数据还原的时候， 我就 tar -xvf ms_data_backup.tar

我后把解压后的folder直接 copy到 `/opt/metersphere/data`

然后运行 msctl restart

请问这样做是否正确。，Redis 是否要重新挂载了文件目录  `/opt/metersphere/data/redis`

**Comment by fit2-zhao** [comment]
`docker exec -it redis redis-cli -a Password123@redis` 如果密码有改 替换成自己密码

查看 API 计数器：`get 100001100001_API_DEFINITION `

查看场景计数器：`get 100001100001_API_SCENARIO`

100001100001 是默认项目 ID ，要查其他项目替换对应 ID 就行。

**Comment by wangzhihaocom** [comment]
@fit2-zhao  我做了上面几步， 但是没有项目 ID， 是有什么不对吗

```
docker exec -it redis redis-cli -a Password123@redis
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> get 100001100001_API_DEFINITION
(nil)
127.0.0.1:6379> get 100001100001_API_SCENARIO
(nil)
127.0.0.1:6379>
```

<img width="823" alt="image" src="https://github.com/user-attachments/assets/e537275e-acda-4a3b-88f8-3c79f682d013">

我也试了一下重新安装一个全新的， 没有做数据还原， 是空的数据， 我运行
`get 100001100001_API_DEFINITION ` and  `get 100001100001_API_SCENARIO`

也是return (nil)

**Comment by fit2-zhao** [comment]
看样子原数据并未迁移成功，如果原数据环境还存在可以查一下原数据，然后重新迁移；如果已经清理了可以手动设置 计数器：

`docker exec -it redis redis-cli -a Password123@redis `
`set 100001100001_API_DEFINITION  10`  （ 比如当前你的项目下接口最大id 是 10 ）
`set 100001100001_API_SCENARIO 10 ` （ 比如当前你的项目下场景最大id 是 10 ）

**Comment by fit2-zhao** [comment]
注意： 100001100001 是默认项目id 你一定要换成 当前你自身项目id。

**Comment by wangzhihaocom** [comment]
@fit2-zhao  多谢回复 。 我按你说的去做，不成功。 

我还是有几个问题：

1. 我的原数据备份和迁移不成功。 我是按这里的文挡做的， https://metersphere.io/docs/v3.x/installation/backup_data/ 

下面是我的步骤：
1. backup mysql `mysqldump -u metersphere -p metersphere > metersphere.sql`
2. 打包 `/opt/metersphere/data  tar -cvf ms_data_backup.tar /opt/metersphere/data`
3. 把 metersphere.sql 和 ms_data_backup.tar 上传到某一个机里。 
3. 在新的机器上安装同一个版的Metersphere
4. 还原 sql 数据  `mysql -u metersphere -p metersphere < metersphere.sql` (下载在第一步里产生的 metersphere.sql到新的机里)
5. 解压 ms_data_backup.tar (下载在第二步里产生的 ms_data_backup.tar 到新的机里)
6. 还原 /data 目录数据
   `cp data/minio /opt/metersphere/data/minio`
   `cp data/redis /opt/metersphere/data/redis` 

===============
请问我上面的步骤是否正确？

2. 当我迁移完数据后， 我重新login metersphere 界面， 全部的用例都在如下图。 最新的ID是 100828. 然后我再
查看 API 计数器：get 100001100001_API_DEFINITION   和 
查看场景计数器：get 100001100001_API_SCENARIO

两个都是 (nil)

然后我手动设置 计数器
docker exec -it redis redis-cli -a Password123@redis 
set 100001100001_API_DEFINITION  100828 （当前的用例ID 是 100828 ） 
set 100001100001_API_SCENARIO 100828  （当前的用例ID 是 100828 ）


请问我应该设置 100828 还是 786 （全部用例 7867）
你说的计数器 ID 和我说的 用例 ID 是不是同一个东西，。 我感觉不是同一个ID

![image](https://github.com/user-attachments/assets/16236b53-acd0-4e6f-b90b-57033149a79e)

3. 我感觉这个用例 ID 是不是应该在 mysql 里设置的 ，我查看了一下MYSQL。是不是在 `functional_case` 的`table`里的 `num`， 如下图


<img width="911" alt="image" src="https://github.com/user-attachments/assets/ead71bf1-34b1-4f18-a6c2-b16f4026032a">

4. 然后当我新建一条新的用例， 它的ID又从100001 重头开始。 如图  ，我是想新的用例ID 应该从 100829 开始

请求帮忙。。。

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/d84033d5-9cae-47ad-b490-d2890c8cd4ad">

**Comment by fit2-zhao** [comment]
```
docker exec -it redis redis-cli -a Password123@redis
SELECT 1 
SETNX 3584339187081216_CASE_MANAGEMENT:allocation 100829


get {3584339187081216_CASE_MANAGEMENT}:allocation
查询到就不要执行下面命令 ：
 INCRBY {3584339187081216_CASE_MANAGEMENT}:allocation 1 
```

**Comment by wangzhihaocom** [comment]
@fit2-zhao  你好， 还是不行， 你可以看一下我的图。 哪里没有做对啊

![image](https://github.com/user-attachments/assets/de1f91f7-912f-41e0-9e82-48fdd146e257)

我按你说的去运行， 但是我新建一个新的用例，但是ID还是重头开始， 是哪里没有做对吗？ 

![image](https://github.com/user-attachments/assets/ac2b6373-170b-4fef-95c9-adff37178008)

**Comment by fit2-zhao** [comment]
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/ed807153-a499-4a8b-bd48-1bc8e885ecb2">

在你的系统中如图 pid 复制下来替换下面步骤的 pid 

1. **系统迁移后的初始化操作**  
   系统迁移后，为了确保一条新的记录被创建，首先需要手动创建一条用例，此时看到重复的 100001 。

2. **连接到 Redis 容器**  
   首先，使用 `docker exec` 命令连接到 Redis 容器：
   ```bash
   docker exec -it redis redis-cli -a Password123@redis
   ```

3. **选择数据库 0**  
   如果需要查询数据库 0，使用 `SELECT` 命令：
   ```bash
   SELECT 0
   ```

4. **查询 `pid_CASE_MANAGEMENT` 键**  
   使用 `KEYS` 命令查询是否存在 `pid_CASE_MANAGEMENT` 键：
   ```bash
   KEYS pid_CASE_MANAGEMENT
   ```
   如果该键不存在，切换到数据库 1，并执行相同的命令：
   ```bash
   SELECT 1
   KEYS pid_CASE_MANAGEMENT
   ```

5. **检查 `pid_CASE_MANAGEMENT` 的值**  
   如果找到了键 `pid_CASE_MANAGEMENT`，用 `GET` 命令获取它的值：
   ```bash
   GET pid_CASE_MANAGEMENT
   ```
   如果值不等于 `100829`，则更新该键的值为 `100829`：
   ```bash
   SET pid_CASE_MANAGEMENT 100829
   ```

6. **验证更新后的值**  
   执行 `GET` 命令再次检查值是否已经更新：
   ```bash
   GET pid_CASE_MANAGEMENT
   ```

**Comment by wangzhihaocom** [comment]
@fit2-zhao 我按你上面的去做。 还是不行， 请看对不对。

1. 我做系统数据迁移后 ， 如下图

![image](https://github.com/user-attachments/assets/3e35b4b0-cfc2-48d0-ac8a-bded0180cd64)

2.我新建一条新的用例。 如下图    新的用例ID是 100001 。
![image](https://github.com/user-attachments/assets/50bab278-0311-4e16-893c-9eee2a371a8e)

![image](https://github.com/user-attachments/assets/23f375d7-75b9-411d-84e0-dcb6642e1953)

3. 连接到 Redis 容器， 运行下面的命令

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/bcae28ea-d13b-4cb0-979a-1113e7618ceb">

###################

运行完上面的步骤后后，之前手动创建第一条用例，ID还是 `100001` ， 没有改成 100829  （我是想应该是ID： 100829， 当我创建新的用例的时候， 

然后我手动再创建一条新的， ID是`100002`。  （ID应该： 100830， 当我创建新的用例的时候 ）

如下图 

还是不行啊。， 是不是哪一步不对啊，：(  你是可以的吗？ 能麻烦您重新做一下， 把每一步都给我一个图， 行吗？ 真的不好意思，麻烦啊。。。。


![image](https://github.com/user-attachments/assets/d50df280-c982-488c-9caa-d6a9de933406)

**Comment by fit2-zhao** [comment]
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/98e720bc-f499-4194-aa1f-c604c573f5aa">

**其他步骤中 pid 一样操作**

**Comment by wangzhihaocom** [comment]
@fit2-zhao  不好意思， 之前是我的搞错了PID， 我没有替换PID， 替换后确实可以了，新的用例 ID从100829开始

谢了， 这个可以关了
