### ISSUE TITLE
[BUG]当嵌套两层及以上事务控制器时，循环控制器不再显示多次的循环结果

### ISSUE THREAD

**Issue by TingZhongMu** [metersphere/metersphere#34122]
### 联系方式

MeterSphere交流群42

### MeterSphere 版本

v2.10.12-Its-a7d7c194

### 使用外置数据库

否

### 问题描述

当循环体控制器嵌套在两层的事务控制器里时，循环体走多次循环时，不显示循环结果；当只有一层事务控制器时，可以显示循环结果

### 重现步骤

![64ae7cc0c5f07dd501a8d7b955eb6d3](https://github.com/user-attachments/assets/53792f0d-0eb3-4a3c-9381-9e91414511fd)
![000d79d3bee0335261aef26024c83eb](https://github.com/user-attachments/assets/572af956-5b37-40c8-a3f3-59b67422bdf7)

### 期待的正确结果

可以多次显示循环结果

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
经研发最终确认，目前的设计逻辑 事务是作为一个整体出结果的，不会有多次结果，保持现状。感谢理解和支持。
