### ISSUE TITLE
[BUG]【资源池】k8s资源池，下载 Role.yml，在k8s上执行，出现error: unable to recognize "Role.yml": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34127]
### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

【资源池】k8s资源池，下载 Role.yml，在k8s上执行，出现error: unable to recognize "Role.yml": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"

### 重现步骤

【资源池】k8s资源池，下载 Role.yml，在k8s上执行，出现error: unable to recognize "Role.yml": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"
![1731487121378](https://github.com/user-attachments/assets/269de238-6d28-4b0e-b9f6-e5cd5dd52904)
![1731487215649](https://github.com/user-attachments/assets/7cef192a-cd4e-43b7-b65e-2b701af0b1e6)

**Comment by liuruibin** [comment]
v1beta1 是不是和 k8s 版本不匹配了，你自行检查k8s 版本对应的api ，调整版本 v1 或者v1beta2 等等
