### ISSUE TITLE
[BUG]脑图模式下编辑用例，第二次调整用例顺序时，会导致第一次调整的用例顺序错乱

### ISSUE THREAD

**Issue by awqinqing** [metersphere/metersphere#34139]
### 联系方式

awqinqing@163.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

在脑图模式下，调整模块和用例顺序，第一次调整是正常的，比如我把第三条用例调整到第一条，保存后正常。但是我第二次调整时，把第5条用例调整到第二条时，再保存就出现问题了，第一次调整的用例原本已经调到第一行位置，但是保存了第二次调整操作后，第一次调整的用例位置变了。用列表模式调整是正常的。

### 重现步骤

1、写5个用例，先把把用例3调整第一行，保存，刷新看一下第一行用例是不是用例3，应该是的，顺序调整生效
2、然后把用例5调整到第二行保存，再刷新观察第一行用例是不是用例3，第二行用例是不是用例5，目前第一行用例应该不是用例3了，有问题

### 期待的正确结果

第一行时用例3，第二行是用例5

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
