### ISSUE TITLE
[FEATURE]脑图模式编辑用例时，每个节点需要输入空格键就可以进入文本编辑状态，当前必须得用鼠标双击才能编辑文本，非常不方便

### ISSUE THREAD

**Issue by awqinqing** [metersphere/metersphere#34135]
### MeterSphere 版本

v3.4.0

### 联系方式

awqinqing@163.com

### 请描述您的需求或者改进建议

脑图模式下编写测试用例时，模块名称、用例名称、步骤和预期结果等文本信息，必须得鼠标双击该节点才能编辑文本，非常不方便，需要输入空格键就进入文本编辑状态，在新增节点时最好也默认进入文本编辑状态。

**Comment by luty2018** [comment]
v3.5 已支持
