### ISSUE TITLE
[BUG] 对接第三方平台时，缺陷和需求类型打开时被置为空

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34138]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

处理v2.10(#33288)提交时src/components/template/CustomFiledComponent.vue，取消了对默认值的检测，导致对接第三方平台时，缺陷和需求类型打开时被置为空

![image](https://github.com/user-attachments/assets/f93b8b44-566a-4eab-8fc1-674e44d98fa3)

![image](https://github.com/user-attachments/assets/b9bd6387-4ac6-4de2-a866-703ab5ba1c53)

原因为初次select选项进入时，default为空字符串，取消了判断后，会导致被设置为空

### 重现步骤

如上所示

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.22版本已修复该问题，请升级。
