### ISSUE TITLE
[BUG]【接口场景】csv处-本地上传文件后，点击删除(X)后，再次本地上传，页面提示重复，上传不上去。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34144]
### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

【接口场景】csv处-本地上传文件后，点击删除(X)后，再次本地上传，页面提示重复，上传不上去。

### 重现步骤

【接口场景】csv处-本地上传文件后，点击删除(X)后，再次本地上传，页面提示重复，上传不上去。
![1731567289580](https://github.com/user-attachments/assets/d531ab5c-cec0-4f3d-85ba-124b20504f40)
![1731567322765](https://github.com/user-attachments/assets/20f09e47-9630-4a74-bb27-f1fd24fcbb29)

**Comment by 13290445582** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
