### ISSUE TITLE
[BUG]xml格式的response，脚本断言无法通过，javax.script.ScriptException异常

### ISSUE THREAD

**Issue by zangxiaobo0107** [metersphere/metersphere#3415]
**MeterSphere 版本**
版本: v1.9.3-a124268c

**Bug 描述**
xml接口，获取到response之后，
1、通过xpath方式进行参数提取，提取结果["value"],而不是value
2、使用提取后的参数进行断言，断言无法通过，meterSphere/info.log中出现
ERROR o.a.j.assertions.JSR223Assertion ? - Problem in JSR223 script: ["2"] == '2'
javax.script.ScriptException: In file: inline evaluation of: ``value = vars.get("statusId"); result = "2".equals(value); if (!result){ 	msg = " . . . '' Encountered "2" at line 4, column 29.
 in inline evaluation of: ``value = vars.get("statusId"); result = "2".equals(value); if (!result){ 	msg = " . . . '' at line number 4
的错误
其中log 中的msg“...”与脚本中的实际内容不一致
**Bug 重现步骤**
1.  接口定义-CASE中调用xml格式接口
2. xpath方式进行参数提取   xpath参数提取：/cfx/body/statusId[1]    （开发者如有其他更好方式可以自行处理）
3. 脚本方式进行断言（多种组合情况下断言失败，开发者可根据规则自行编辑断言脚本）
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
附接口入参、返参作为bug定位使用
[request.txt](https://github.com/metersphere/metersphere/files/6574451/request.txt)
[response.txt](https://github.com/metersphere/metersphere/files/6574455/response.txt)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复这个问题

**Comment by xulinde** [comment]
v1.13.1已修复
