### ISSUE TITLE
[QUESTION]v3.x 不允许创建新用户了吗？界面上的导入、手动创建都是报错的。

### ISSUE THREAD

**Issue by t880216t** [metersphere/metersphere#34159]
### 请描述您的问题

1.从数据库里新增的非admin账户，点击登录，提示“检测到用户创建途径异常，禁止登录！“
2.从界面上创建用户也是失败的，接口500，没有userXpackService相关的依赖服务。

**Comment by fit2-zhao** [comment]
1. 禁止直接从数据库进行插入操作。
2. 你是通过源代码启动的吧？这个问题我们会在后续处理，你可以先使用我们的安装包进行部署。

**Comment by t880216t** [comment]
> 1. 禁止直接从数据库进行插入操作。
> 2. 你是通过源代码启动的吧？这个问题我们会在后续处理，你可以先使用我们的安装包进行部署。

感谢回复，还请处理下。做了些自定义的开发，期待与新版本的融合。

**Comment by am6737** [comment]
> ### 请描述您的问题
> 1.从数据库里新增的非admin账户，点击登录，提示“检测到用户创建途径异常，禁止登录！“ 2.从界面上创建用户也是失败的，接口500，没有userXpackService相关的依赖服务。

+1

**Comment by tomman2012** [comment]
有确切的解决时间吗？ 没有的话部署起来也不能试用，总不能大家都使用admin账号吧

**Comment by YeungHoiChiu** [comment]
> 2. 你是通过源代码启动的吧？这个问题我们会在后续处理，你可以先使用我们的安装包进行部署。

这个问题还有关注吗？期待你的回复 @fit2-zhao

**Comment by t880216t** [comment]
> > 2. 你是通过源代码启动的吧？这个问题我们会在后续处理，你可以先使用我们的安装包进行部署。
> 
> 这个问题还有关注吗？期待你的回复 [@fit2-zhao](https://github.com/fit2-zhao)

放弃吧，v3这个不修复，基本等于闭源了，我已经回退到v2。

**Comment by lsy-g** [comment]
我也是3.6.*版本遇到不能新增用户的问题，从metersphere-ce容器中提取general-xpack-impl-3.6.7-lts.jar 包，然后本地引入，引入之后新增用户就没问题了
