### ISSUE TITLE
[FEATURE]增加日志存储配置

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#3416]
**请描述您的需求或者改进建议.**
作为MeterSphere管理员，我希望MeterSphere可以增加最系统日志存储配置，以减少因为 MS 日益增长的日志文件导致系统磁盘空间不足引起其它问题。
备注：安装MS之后，数据和操作比较少，40天左右的时间，logs目录下的日志文件大小近 12 GB……
![image](https://user-images.githubusercontent.com/46042812/120289454-e46b2280-c2f3-11eb-9ea8-396043a11703.png)

**请描述你建议的实现方案**
增加系统日志存储周期配置，当超过此周期时，自动删除日期最早的日志文件。

**Comment by xulinde** [comment]
现在策略是，日志会保存30天

**Comment by Andyguo5891** [comment]
这个参数暴露出来了么？

**Comment by xulinde** [comment]
没有

**Comment by Andyguo5891** [comment]
既然是这样，强烈建议还是暴露出来吧。
这些参数对于平台使用者来说，应该是透明、公开的。
