### ISSUE TITLE
[BUG]场景存在无法关闭或显示异常情况

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#34160]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

是

### 问题描述

部分场景打开时卡顿，显示步骤异常，且无法关闭场景。重新进入场景查看控制台报错。
报错场景一般步骤较多且复制了其他场景
![报错](https://github.com/user-attachments/assets/b84e1b1c-bbb6-4ebf-9b04-e0d67e8f9788)

### 重现步骤

相同问题，
#34010 
#30531
目前已升级至最新版并修改api-test容器最大内存为3G（已使用828M），仍存在此问题，
![增加api-test无法解决](https://github.com/user-attachments/assets/6b717428-5100-4387-8197-4972f20f509e)
查看控制台js报错TypeError: Cannot read properties of undefined (reading 'key')。
**尝试将场景导出为metershper格式，再导入，可解决此问题。**

### 期待的正确结果

原场景可修复

**Comment by youliyuan-fit2cloud** [comment]
请告知你的本地机器的配置 ？

**Comment by ywang9-12** [comment]
> 请告知你的本地机器的配置 ？

硬盘200G，内存58G
![硬盘容量](https://github.com/user-attachments/assets/755d2102-ed77-4694-a1ae-0fb297c371d8)
![内存配置](https://github.com/user-attachments/assets/35af3d06-d534-45c8-a0d8-6060e7684528)
![容器配置](https://github.com/user-attachments/assets/bbb5192b-fed7-4c1e-835a-7f7de7cbecb3)

**Comment by youliyuan-fit2cloud** [comment]
不是安装MeterSphere 的服务器。是指通过你的本地电脑（windows or Macbook ）的配置，通过本地电脑 打开MeterSphere。

**Comment by ywang9-12** [comment]
WIN10版本 500G硬盘，16G内存。这个也有影响吗？
![win10_16G](https://github.com/user-attachments/assets/af344438-44df-490a-b0f4-1cef476a722e)
![win10_性能](https://github.com/user-attachments/assets/bdfd4271-a51f-4074-8306-21743cf4e865)

**Comment by youliyuan-fit2cloud** [comment]
了解了，出现这个问题的接口场景方便发一份吗？

**Comment by ywang9-12** [comment]
> 了解了，出现这个问题的接口场景方便发一份吗？

可以，但这个场景里复制了其他场景，只需要导出异常场景就行吗？

**Comment by youliyuan-fit2cloud** [comment]
> > 了解了，出现这个问题的接口场景方便发一份吗？
> 
> 可以，但这个场景里复制了其他场景，只需要导出异常场景就行吗？

可以。

**Comment by ywang9-12** [comment]
异常场景数据附件
[Metersphere_Scenario_SDWAN.json](https://github.com/user-attachments/files/17797421/Metersphere_Scenario_SDWAN.json)

**Comment by youliyuan-fit2cloud** [comment]
很遗憾，这个场景导入到测试环境没有复现。。。你这个场景是100%出现吗？

**Comment by ywang9-12** [comment]
> 很遗憾，这个场景导入到测试环境没有复现。。。你这个场景是100%出现吗？

是的，我的问题里也提到了，暂时解决场景异常的方法就是导出再导入，新场景是正常的，所以你导入我的场景估计也复现不了。看能不能远程吧。

**Comment by ywang9-12** [comment]
我又试了一下导出JMeter格式，导出的文件有点问题，文件名是另一个场景，实际场景名是文件夹的名字。
[场景JMX文件集.zip](https://github.com/user-attachments/files/17798403/JMX.zip)

**Comment by 13290445582** [comment]
万分抱歉，未复现到此问题，暂时也无其他用户反馈该情况，给您的使用带来了不便，后续我们还会测试到这里，感谢您的理解与支持。
