### ISSUE TITLE
[BUG] 场景里引用了用例，运行场景，报告里出现提取和断言在用例里设置了，但是场景运行报告里没有，或者有提取没有断言；多次运行，每次出问题的接口不固定，有些接口这次运行出现问题，下次运行可能又没问题了

### ISSUE THREAD

**Issue by zizi457** [metersphere/metersphere#34174]
### MeterSphere 版本

 v2.10.21-lts-f65e0842版本

### 使用外置数据库

否

### 问题描述

 场景里引用了用例，运行场景，报告里出现提取和断言在用例里设置了，但是场景运行报告里没有，或者有提取没有断言；
现在很影响我接下来的创建场景 引用用例了。如果不采用引用用例，那我每个场景都要去维护自定义请求，工作量增大了很多

### 重现步骤

1.在接口定义里定义了一些接口，断言和提取都设置好了
2.在接口自动化模块里创建场景，然后引用了步骤1中的接口，进行运行
3.查看运行报告里，接口运行成功，但是出现提取和断言都为空；或者有提取没断言

### 附加信息

Uploading Video_2024-11-15_172911.mp4…

**Comment by youliyuan-fit2cloud** [comment]
你好，附件视频无法查看，请重新上传

**Comment by zizi457** [comment]
不用附件的视频，按照我的操作步骤试下

**Comment by zizi457** [comment]
问题希望能快点解决，要不然接下来的任务都卡住了

**Comment by youliyuan-fit2cloud** [comment]
仍然没复现，请检查一下你的脚本断言怎么写的？
![image](https://github.com/user-attachments/assets/a35828ff-bfdb-4525-a8b3-4a5ff338ddc4)

**Comment by zizi457** [comment]
断言是脚本。提取用的是jsonpath
断言现在只有code码  200不出现问题，自己写的脚本断言会出问题

**Comment by zizi457** [comment]
问题已解决，脚本断言写的有问题。
