### ISSUE TITLE
[FEATURE]测试用例脑图编辑增加自动保存功能

### ISSUE THREAD

**Issue by slowant** [metersphere/metersphere#3418]
**请描述您的需求或者改进建议.**

测试用例xmind编辑增加自动保存功能

**请描述你建议的实现方案**
脑图编辑时，切换时没有自动保存，导致测试案例丢失。
建议完成必填项时自动保存，或者，退出切换时，弹对话框提示保存

**Comment by xulinde** [comment]
后面版本可以加个提示

**Comment by xulinde** [comment]
v1.13已支持
