### ISSUE TITLE
[BUG] 2.10.21这个版本,自定义配置的字段,在功能用例高级筛选,筛不出内容

### ISSUE THREAD

**Issue by yiguming** [metersphere/metersphere#34187]
### MeterSphere 版本

 2.10.21

### 使用外置数据库

否

### 问题描述

 2.10.21这个版本,自定义配置的字段,在功能用例高级筛选,筛不出内容

### 重现步骤

 2.10.21这个版本,自定义配置的字段,在功能用例高级筛选,筛不出内容，v2.10.10这个功能是好

### 期待的正确结果

v2.10.10这个功能是好

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.22-lts版中已修复。
