### ISSUE TITLE
[BUG]多资源池节点执行测试计划会导致报告显示步骤重复多次及测试执行时间翻倍

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#34183]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

是

### 问题描述

1、测试计划使用两节点资源池执行
2、task-runner 、result-hub、metersphere（用做工作节点下发）各外置一个
3、执行结果显示步骤重复，并且测试计划的执行时间翻倍

### 重现步骤

1、测试计划使用两节点资源池执行
2、task-runner 、result-hub、metersphere（用做工作节点下发）各外置一个
3、执行结果显示步骤重复，并且测试计划的执行时间翻倍

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
