### ISSUE TITLE
[BUG]MS中创建的同一个Bug，在生成的测试报告中会重复关联

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34207]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/65f0007a-d248-4851-bd31-74e8aa81f541)

### 重现步骤

[BUG]MS中创建的同一个Bug，在生成的测试报告中会重复关联

**Comment by henbell2** [comment]
![image](https://github.com/user-attachments/assets/253436a4-bcf9-427b-af25-aff5cbf42c97)

**Comment by 13290445582** [comment]
您好，一个缺陷对应一个缺陷ID，您这种两个同样ID的缺陷是如何创建的？

**Comment by henbell2** [comment]
缺陷是同一个，在测试报告的bug列表中多次被list出来

**Comment by 13290445582** [comment]
你好，你这个报告是不是计划组的报告，计划的报告没有这个问题吧，是不是只有计划组的报告有这个问题。

**Comment by henbell2** [comment]
不是计划组报告，就是普通的测试计划生成的报告

**Comment by henbell2** [comment]
看截图貌似和数字8、81有什么关系？

**Comment by 13290445582** [comment]
测试计划报告没遇到这情况，计划组的倒是遇到了，在v3.5版本会修复计划组报告缺陷明细显示重复问题，可以在v3.5发布后使用下，新生成下计划报告看看你这个问题还存不存在吧。

**Comment by henbell2** [comment]
ok

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
