### ISSUE TITLE
[BUG]导出测试报告的Bug Title，大范围丢字

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34208]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/7c309cf0-d2e3-4530-8cbc-f7795d891e01)

### 重现步骤

[BUG]导出测试报告的Bug Title，大范围丢字

**Comment by henbell2** [comment]
![image](https://github.com/user-attachments/assets/c9983f82-4331-4cca-938f-17bf34acdbca)

**Comment by 13290445582** [comment]
<img width="755" alt="image" src="https://github.com/user-attachments/assets/e4a1d9e5-c96c-41d7-ad89-aa9f56d53588">
您好，导出未发现问题，请提供下您的测试报告。

**Comment by henbell2** [comment]
几条或者十几级条OK的，多一点就不行了
![image](https://github.com/user-attachments/assets/fa67258f-7c00-47eb-a95f-9c0b75dae9b4)

**Comment by 13290445582** [comment]
万分抱歉，未复现到此问题，暂时也无其他用户反馈该情况，给您的使用带来了不便，后续我们还会测试到这里，也希望发现问题原因后可给出具体的可复现情况，感谢您的理解与支持。
