### ISSUE TITLE
[BUG]评审计划中批量选择待评审用例，追加评审人，只在第一条用例中追加，其它用例均无法追加评审人

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34264]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/fdb10522-2c97-48b2-bf9f-f822796283f8)

### 重现步骤

[BUG]评审计划中批量选择待评审用例，追加评审人，只在第一条用例中追加，其它用例均无法追加评审人

**Comment by luty2018** [comment]
没有复现这个问题，或者你可以等下周升级到v3.5试试。

**Comment by henbell2** [comment]
OK!

**Comment by 13290445582** [comment]
您好，问题暂时关闭，待v3.5发布后测试若问题仍存在，可提供具体步骤的录屏并提issue，感谢您的理解与支持。
