### ISSUE TITLE
[BUG]接口路径最前面使用变量不使用斜杆，get请求不会携带query参数

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#34262]
### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

接口路径最前面使用变量不使用斜杆，get请求不会携带query参数，反而post请求会携带query参数

### 重现步骤

1、创建一个环境，不添加域名，只添加一个host变量
![image](https://github.com/user-attachments/assets/492b5753-1193-411a-ae8c-deb5238a16b6)
2、创建一个接口，接口路径为${host}/test/login，添加query参数
![image](https://github.com/user-attachments/assets/33487880-40eb-4905-9a86-39f0f9e118f4)
3、选择该环境，执行这个接口，get请求不会携带query参数，反而post请求会携带query参数
![image](https://github.com/user-attachments/assets/9b1a8eab-9442-4189-83f5-748e99e0c6ad)
![image](https://github.com/user-attachments/assets/71f9460a-4124-4679-836c-62d32b91e476)

**Comment by 13290445582** [comment]
您好，路径的正确规则写法就是要带斜杠的，只是我们没有过多限制路径内容，在路径的默认提示文案有写提示。
<img width="916" alt="image" src="https://github.com/user-attachments/assets/79267f34-8c7d-4ec8-9a5e-b1885b317f30">

**Comment by testerjl** [comment]
> 您好，路径的正确规则写法就是要带斜杠的，只是我们没有过多限制路径内容，在路径的默认提示文案有写提示。 <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/128017892/388383750-79267f34-8c7d-4ec8-9a5e-b1885b317f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDU1MDMsIm5iZiI6MTczMjg0NTIwMywicGF0aCI6Ii8xMjgwMTc4OTIvMzg4MzgzNzUwLTc5MjY3ZjM0LThjN2QtNGVjOC05YTVlLWIxODg1YjMxN2YzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwMTUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmEyMGQyZDk4MjA5NGExNDJiMDE3MjQxZTQ3OTcwMTNiYWRjZWVhZmVjY2NlN2QxM2RiOTVjY2YzNGMyNWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CRjG1jLo7TqzJxzkjz4gBkUG0QN3kSsn_wASIaOMi6Q">

如果在前面加上/  是就get方法加，还是所有的方法都要加。如果都要加的话其他方法你试下会不会有问题？  带/杠的话 设置的变量里面的URl不管带不带http://协议头，发起实际请求都会有问题。 变量不带http://协议头的话，实际请求就是http:/  ；变量带http://协议头的话，实际请求就是http:/http://  请求响应直接解析失败。所有能不能给出你那边重现没有问题的截图 。  不要来不来就直接给个显示描述 直接关闭问题嘛，

**Comment by 13290445582** [comment]
你好，我们在接口路径输入写的就是要以“/”开始。你说的这种不配置HTTP，在环境变量配置的情况，暂不支持。建议正常配置HTTP，接口路径以“/”开始，使用起来是没有问题的。
