### ISSUE TITLE
[BUG]接口测试场景目录，目录的移动未生效

### ISSUE THREAD

**Issue by jeremyliu17** [metersphere/metersphere#34276]
### 联系方式

836615163@qq.com

### MeterSphere 版本

https://demo.metersphere.com/ 体验环境

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/57e1ea12-0cbb-4ca1-ab51-0888a25e5008)
ru't如图，将测试3目录移动到测试1目录上，但移动后，排序未生效，仍为图中的状态，不是稳定复现，但大概率是能复现出来的。

### 重现步骤

1.在接口测试场景页面，新建测试目录
2.测试目录下，新建测试1、测试2、测试3子目录；
3.将测试3子目录移动到测试1前面；
期望结果：目录排序为测试3，测试1，测试2；
实际结果：目录排序仍为测试1，测试2，测试3

### 附加信息

涉及两个接口，移动和获取目录树
https://demo.metersphere.com/api/scenario/module/move
https://demo.metersphere.com/api/scenario/module/tree
查看代码，应该是移动目录的时候，更新的子目录pos比父级目录顺序还低，导致在查询目录树接口的时候，这个子目录在buildTreeAndCountResource函数中首先被分配为notMatchedList，然后这个子目录最后再进入列表中，导致查询的结果还是不变

**Comment by 13290445582** [comment]
您好，在v3.4版本确实复现了此问题，即将发布的v3.5未发现此问题，请等待v3.5发布后再使用下该功能，后续有问题再持续反馈，先关闭该issue，感谢您的理解与支持。

**Comment by jeremyliu17** [comment]
https://demo.metersphere.com/ 体验环境 显示的V3.5版本，仍然出现了这个问题
![image](https://github.com/user-attachments/assets/4e34ad7a-acb0-4ad6-afd6-48d159ed2477)
