### ISSUE TITLE
[BUG] 接口自动化场景里面使用自定义GET请求，请求url里面使用变量会导致url出现重复http错误

### ISSUE THREAD

**Issue by chiehfeng** [metersphere/metersphere#34275]
### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

添加自定义GET请求后，url中的域名设置为变量，同一个url的请求会出现第一条可以访问成功，但是后面同样url的请求会报错

### 重现步骤

添加自定义GET请求后，url中的域名设置为变量，同一个url的请求会出现第一条可以访问成功，但是后面同样url的请求都会报错（请求是连着的）
第一个请求的url是正常的：
![image](https://github.com/user-attachments/assets/3e9d35a5-5211-469b-9a00-f132ad5c8c43)
后面跟着的请求url是一样的，但是会出现重复的http；请求是连着的中间没有变量的修改
![image](https://github.com/user-attachments/assets/11734f52-5db0-41ea-9c3d-72c397fc4861)

**Comment by chiehfeng** [comment]
是因为空格的问题
![image](https://github.com/user-attachments/assets/cb56d853-0c97-4647-9812-748e8a146c84)

**Comment by 13290445582** [comment]
您好，空格也是字符，在路径中被转义了，路径填写不正确导致的http错误，去掉空格就好了。
