### ISSUE TITLE
[BUG]使用metersphere-jenkins-plugin 时候jenkins连接metersphere失败( MeterSphere 版本 应该是v2.10.18-lts-9188df0e ，后面写错了）

### ISSUE THREAD

**Issue by gtyaA7DS** [metersphere/metersphere#34280]
### 联系方式

1936691271@qq.com

### MeterSphere 版本

v1.20.9-lts

### 使用外置数据库

否

### 问题描述

jenkins 版本 2.4.8 , 使用了metersphere-jenkins-plugin-v2.10.19-lts.hpi  ,  配置号api key 之后出现报错：
验证MeterSphere帐号失败！java.lang.NullPointerException: Cannot invoke "io.metersphere.ResultHolder.isSuccess()" because "result" is null,Cannot invoke "io.metersphere.ResultHolder.isSuccess()" because "result" is null

### 重现步骤

无

### 相关日志输出

```shell
验证MeterSphere帐号失败！java.lang.NullPointerException: Cannot invoke "io.metersphere.ResultHolder.isSuccess()" because "result" is null,Cannot invoke "io.metersphere.ResultHolder.isSuccess()" because "result" is null
```

### 附加信息

<img width="885" alt="{62DC5951-1D5B-4cc4-A7C9-CE42FDA5BCD2}" src="https://github.com/user-attachments/assets/e01621fb-45ca-42a9-b216-83452d346807">

**Comment by 13290445582** [comment]
您好，未复现该问题，建议在github下载我们最新的metersphere-jenkins-plugin-v2.10.21-lts.hpi并且将metersphere版本升级到v2.10.21测试下是否可正常使用，也请再次核对下验证账户时所填写的各类信息是否正确。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
