### ISSUE TITLE
[BUG]无法删除项目

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#3429]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.1

**Bug 描述**
简要描述您碰到的问题
系统管理员角色、工作空间管理员角色，均无法删除项目。提示“当前用户没有操作此项目的权限”

**Bug 重现步骤**
1.  新建项目
2. 删除项目

**期待的正确结果**
正确情况下应该是什么样的？
正常删除

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前最新版本还是 v1.10.0 而非 v1.10.1。
该问题为已知问题，将在 v1.10.1 版本修复。

**Comment by xulinde** [comment]
v1.10.1 版本已修复
