### ISSUE TITLE
[BUG] api调用查询metersphere所有分页列表，页码超过存在页码，返回的数据仍然是最后一页的

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34292]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

api调用查询metersphere所有分页列表，页码超过存在页码，返回的数据仍然是最后一页的

### 重现步骤

z总共有7页
![image](https://github.com/user-attachments/assets/f21c1ecf-dd95-42b4-9224-46f31970823a)
api调用传了第8页，响应体显示的是第七页数据；
![image](https://github.com/user-attachments/assets/534fae00-2233-45c5-9b9a-a393b652eb6a)
![企业微信截图_1732159650943](https://github.com/user-attachments/assets/5522b8c7-c60e-436d-9839-3c862db0a975)

### 期待的正确结果

传第8页，响应体为第8页，数据为空

**Comment by 13290445582** [comment]
您好，API 上有 分页的最大页码验证，超过则无效返回最后一页。
