### ISSUE TITLE
[BUG]数字类型字段的JSONPath推荐断言值不正确导致断言失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#34294]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

数字类型字段的JSONPath推荐断言值不正确导致断言失败

### 重现步骤

如下图：
<img width="623" alt="image" src="https://github.com/user-attachments/assets/83b7a795-b81c-4d5c-a96b-d2ca8fc0c1ea">

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by 13290445582** [comment]
您好，V3.5已修复该问题，请升级。
