### ISSUE TITLE
[FEATURE]对接企业微信或钉钉进行消息通知

### ISSUE THREAD

**Issue by wenkejiang** [metersphere/metersphere#343]
**请描述您的需求或者改进建议.**
定时执行接口任务或者性能任务,能否实现通过企业微信或者钉钉进行推送,根据不同组织创建对应的告警组,然后在告警组中维护对应的需要收到告警的人,然后当接口或者性能执行失败的是进行告警,这就能及时的完成业务监控

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，平台已经增加该功能，您可以升级到最新版本体验
