### ISSUE TITLE
[BUG]merersphere集成禅道，创建缺陷时一直提示“影响版本不能为空”

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34307]
### 联系方式

403637897@qq.com

### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

按照metersphere集成禅道的操作说明配置，并新增字段应用于禅道缺陷模板，新增缺陷，提示“影响版本不能为空”，缺陷类型等未报错

### 重现步骤

1.按照metersphere集成禅道的操作说明配置，禅道版本V18.10
2.并新增字段应用于禅道缺陷模板，新增缺陷，提示“影响版本不能为空”，缺陷类型等未报错

### 期待的正确结果

可以成功提交缺陷并同步到禅道上

### 附加信息

![Uploading IMG_20241118_162304.jpg…]()
### 
![Uploading IMG_20241118_162325.jpg…]()
![Uploading IMG_20241118_162335.jpg…]()

**Comment by michellefan123** [comment]
![Uploading IMG_20241118_163411.jpg…]()

**Comment by 13290445582** [comment]
您好，你上传的图片都失败了，看不到图片内容。听描述像是模板配置的问题，添加个影响版本字段看是否能解决问题。
<img width="483" alt="image" src="https://github.com/user-attachments/assets/0fcddc1c-8e03-4330-96a8-0c98bb533ce4">

**Comment by michellefan123** [comment]
我字段里面影响版本是这样添加的，集成禅道的插件版本现在更新至V3.4.0现象也是一样的，测试与禅道连接是成功的
![Uploading IMG_20241118_163411.jpg…]()

**Comment by michellefan123** [comment]
![IMG_20241118_162335](https://github.com/user-attachments/assets/423852c1-855e-45c2-ae88-fc6183e3b512)

> 
![IMG_20241118_163411](https://github.com/user-attachments/assets/71f6dfd3-45ed-48ec-8eac-bae19ee6d338)
![IMG_20241118_162304](https://github.com/user-attachments/assets/acad2431-8c72-49fc-a01f-3a83f637bf49)
![IMG_20241118_162325](https://github.com/user-attachments/assets/beb206dc-6e59-4678-b267-ae883dbd2af4)
![Uploading IMG_20241118_162335.jpg…]()

**Comment by 13290445582** [comment]
您好，影响版本字段是多选下拉框，上图中创建的是单选下拉框类型的，你新建一个多选下拉框类型的影响版本字段使用就可以了。

**Comment by michellefan123** [comment]
修改后缺陷创建成功了
