### ISSUE TITLE
[BUG]接口请求不引用场景环境时，前置、后置中添加的SQL脚本，在切换场景环境后，预期前置、后置的SQL脚本不跟随主环境变化，实际跟随主环境变化了，导致执行报错报表不存在

### ISSUE THREAD

**Issue by llzhou1229** [metersphere/metersphere#34304]
### 联系方式

llzhou@wisedu.com

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

![ebd02a07ae2c289e68faa261ff673a9](https://github.com/user-attachments/assets/07100153-415c-464a-8f19-d2b580220e74)

### 重现步骤

接口请求不勾选引用环境
添加前置或后置的SQL脚本，选择运行环境，配置SQL执行脚本
切换场景运行环境后，预期前置或后置的SQL脚本不跟随场景环境变化，实际跟随场景环境变化，导致前置或后置的SQL脚本执行报错，报找不到对应的表

**Comment by 13290445582** [comment]
您好，无论是否勾选引用环境，切换环境时，前后置SQL环境都会跟随切换。
