### ISSUE TITLE
[FEATURE]强烈建议接口定义更新后，测试用例自动同步更新！

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#3430]
**请描述您的需求或者改进建议.**
开发过程中，存在修改接口定义的情况，可能会涉及header或body的修改，如果没有自动同步机制的话，需要人工手动维护所有引用该接口的用例，工作量较大。
建议在接口定义更新后，同步更新所有引用该接口的单接口用例、场景自动化用例。

**请描述你建议的实现方案**
对于接口定义中新增某个字段，自动在用例中增加该字段，可无赋值，且不影响用例中其他设置；
对于接口定义中删除某个字段，自动在用例中删除该字段，且不影响用例中其他设置。

**Comment by luisxiaomai** [comment]
同意，场景接口用例导入接口的时候添加引用选项，目前只有复制功能，接口变了所有用例都需要修改，很麻烦

**Comment by pptech-dev** [comment]
+10086

**Comment by zhangzhaox** [comment]
这个需求确实非常重要，对于API自动化测试而言不可缺。

**Comment by GITMrzk** [comment]
你好，麻烦关注一下这个需求。

**Comment by xulinde** [comment]
感谢反馈，目前是这样设计的，我们后续再规划下这里

**Comment by dudiao** [comment]
请问这个功能计划什么时候出？

**Comment by xulinde** [comment]
v1.13已支持
