### ISSUE TITLE
[BUG] 接口自动化执行时页面一直在Pending，实际执行成功

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#34311]
### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

执行自动化场景时（从列表处直接点击运行），页面一直显示PENDING，会有消息通知执行成功。同时进入报告查看，执行已经完成，报告内容是完整的。
第一次运行正常，第二次大概率不正常，再执行就都不正常了。

此处开始运行：
![image](https://github.com/user-attachments/assets/2d8fe345-73c8-4175-8939-965216ed5346)
执行页面：
![image](https://github.com/user-attachments/assets/2f56fa1b-1b6a-4c3e-8115-a071bd4768af)
日志信息：
![企业微信截图_17321752461148](https://github.com/user-attachments/assets/631acf2b-0d61-47e0-b105-d452eb7966b3)
执行结果：（即使显示stopped，进入查看也是正常执行成功的）
![image](https://github.com/user-attachments/assets/21db26cf-669a-4554-9001-7f827023e066)

脚本：
[Metersphere_Scenario_默认项目0.json](https://github.com/user-attachments/files/17842436/Metersphere_Scenario_.0.json)

### 重现步骤

如上

**Comment by 13290445582** [comment]
您好，已导入您提供的场景未发现此问题。请问您执行异常的时候是否有日志提供，可检查下环境是否正常。

**Comment by xchnshi** [comment]
从列表触发执行，自动化运行与socket通信是并行执行的。而进入自动化场景详情，再点击debug或执行，是正常的。
不确定下面的修改是否是合理的，
![image](https://github.com/user-attachments/assets/e61327fc-46e6-42c2-9262-a5c11001fd64)

**Comment by 13290445582** [comment]
万分抱歉，未复现到此问题，暂时也无其他用户反馈该情况，给您的使用带来了不便，后续我们还会测试到这里，感谢您的理解与支持。
