### ISSUE TITLE
这个漏洞我就是没找到才问你们的

### ISSUE THREAD

**Issue by gouheizi** [metersphere/metersphere#34328]
### 请描述您的问题

能详细说一下漏洞的位置吗

**Comment by liuruibin** [comment]
这个是漏洞内容
![image](https://github.com/user-attachments/assets/195337df-9864-4cab-8023-3ab27c6e8216)

这个是代码位置
![image](https://github.com/user-attachments/assets/e6382ee9-5e83-42d9-b9ef-6ef18ddbfce4)
