### ISSUE TITLE
[BUG]测试计划列表页，操作按钮 列折行，观感不好

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#34320]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

[BUG]测试计划列表页，操作按钮 列折行，观感不好

### 重现步骤

[BUG]测试计划列表页，操作按钮 列折行，观感不好
![image](https://github.com/user-attachments/assets/f2f8e51a-7ab5-4a9d-b201-63fe5bb30aff)

### 期待的正确结果

[BUG]测试计划列表页，操作按钮 成一行

**Comment by luty2018** [comment]
暂无排期计划
