### ISSUE TITLE
[BUG] 接口测试 json-schema 自动生成数据，根据参数格式化生成错误

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34339]
### 联系方式

姚春荣

### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

接口测试 json-schema 自动生成数据，邮箱格式生成错误

### 重现步骤

![image](https://github.com/user-attachments/assets/68beace9-5457-4e39-b893-6953576c4122)
![image](https://github.com/user-attachments/assets/35899356-e006-4e70-8206-94ec673855ea)

### 期待的正确结果

自动生成邮箱格式正确

**Comment by 13290445582** [comment]
![image](https://github.com/user-attachments/assets/96ebeeb9-35af-4abe-a095-b1eac9a07abc)
您好，未复现此问题。

**Comment by fit2cloud-yaochunrong** [comment]
啊？我的截图是参数高级配置里面的格式化：邮箱

**Comment by 13290445582** [comment]
<img width="910" alt="image" src="https://github.com/user-attachments/assets/d9939d9c-1069-4f9d-b97b-ed7c465ca859">
<img width="588" alt="image" src="https://github.com/user-attachments/assets/c8e75dc7-ad97-4ec4-9ccc-3a0ea10c8ff3">
<img width="914" alt="image" src="https://github.com/user-attachments/assets/150c6632-8ad4-44c4-8244-0ecc089077ce">
你好，不是特别清楚什么操作，就我图中这样的操作，自动生成就要生成email格式数据？是这个意思吗？

**Comment by fit2cloud-yaochunrong** [comment]
是的
其它枚举，最大值最小值等都是可以的

**Comment by 13290445582** [comment]
你好，研发反馈：这个需要在参数值填写。格式化不是处理自动生成的数据的，非bug。

**Comment by fit2cloud-yaochunrong** [comment]
其它枚举，最大值最小值，正则等都是可以生成的！！！！！，只有格式化不行
