### ISSUE TITLE
[BUG]1.10新版创建的用户  配置了所有权限，依旧在各个模块负责人、关注人、评审人等选不到此人

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#3434]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这个是已知问题，将在1.10.1版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
