### ISSUE TITLE
[BUG] 环境配置，http配置，启用条件为模块，筛选模块后选择失败

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34341]
### 联系方式

姚春荣

### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

环境配置，http配置，启用条件为模块，筛选模块后选择失败

### 重现步骤

选择不上，还是空的
![image](https://github.com/user-attachments/assets/8d4ba638-14a3-4b5e-8ca6-27a19e8a8341)

**Comment by 13290445582** [comment]
未复现搜索模块后勾选失败问题，可开无痕再试下是否问题仍存在。v3.5这里会做优化，待v3.5发布后升级使用看是否还存在该问题。
