### ISSUE TITLE
[FEATURE]用例标题展示空间设计不合理，建议优化

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34387]
### MeterSphere 版本

v3.4.0-5291ac9a

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/b0246813-efaf-4ee2-9601-e75afc3312c0)

**Comment by Somebody-JIAN** [comment]
感谢您的建议！

这种场景在我们使用过程中很少遇到，也可能是因为这个原因，这种小细节并没有考虑到

感谢您的支持!

**Comment by youliyuan-fit2cloud** [comment]
v3.6已优化。
