### ISSUE TITLE
[FEATURE]【缺陷服务集成】使用过程中有二个痛点

### ISSUE THREAD

**Issue by zhj001** [metersphere/metersphere#344]
一、bug管理工具服务集成账号是全局、这样一个10人测试团队都在执行用例分别在提交缺陷、bug创建者都是同一个人这样研发和创建bug的人很难沟通，回归bug也很不方便。

二、提交缺陷的时候字段太少、比如：bug提交分配给研发也只能去jira再次修改（建议可以增加一个自定义字段提交bug的时候根据公司需求自行添加）

**Comment by edensummer** [comment]
建议先增加 被指派人 【经办人】

**Comment by youliyuan-fit2cloud** [comment]
您好，感谢您的反馈，我们后续会优化缺陷集成服务，请您持续关注～

**Comment by youliyuan-fit2cloud** [comment]
#415 问题相同，请持续关注～
