### ISSUE TITLE
[BUG]http post请求，返回的 响应头 里没有带上cookie显示出来

### ISSUE THREAD

**Issue by LeungJingna** [metersphere/metersphere#34403]
### 联系方式

jingnan.liang@xgo.one

### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

否

### 问题描述

http post请求，返回的 响应头 里没有带上cookie显示出来
![image](https://github.com/user-attachments/assets/09630d28-9f1c-422b-84b9-5e684a19e4a3)

同样的请求参数，在postman里请求，postman的响应头部是带有cookie的
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/21ed7d56-224b-44f1-8037-7ac42bd13a04">

### 重现步骤

http post请求

### 期待的正确结果

响应的头部里带有cookie显示出来

### 附加信息

![image](https://github.com/user-attachments/assets/eaabb3fa-1e7d-4ff7-8065-6fb9e937eb53)

**Comment by 13290445582** [comment]
您好，通过MOCK了一个接口，未复现此问题，麻烦提供下相应的可操作的复现接口。

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。
