### ISSUE TITLE
[QUESTION]源码告诉我吧

### ISSUE THREAD

**Issue by gouheizi** [metersphere/metersphere#34409]
### 请描述您的问题

我源码没找到，求你了，我给你跪下了，你给我说是哪个函数的问题吧

**Comment by liuruibin** [comment]
我们这边还是建议直接使用发行版：v2.10.21-lts 其中包括最新的bugfix和功能增强

**Comment by Somebody-JIAN** [comment]
修改的时间距今太久了，具体的内容我们也记不清了。

现在找起来费时费力，而且我们V3版本的开发压力还很大，暂时没有额外的精力帮您找。

况且，后面的日子也有零星的漏洞修复，建议您使用最新发行版的代码。

感谢您的支持与谅解  : p
