### ISSUE TITLE
[BUG]场景步骤中点击点击运行环境报错Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by kouzhijian** [metersphere/metersphere#3441]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**
简要描述您碰到的问题
场景步骤中点击点击运行环境报错Cannot read property 'type' of undefined
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
[如果有截图，请附上截图.]
![QQ截图20210602145907](https://user-images.githubusercontent.com/33210000/120438017-69694100-c3b3-11eb-8799-74bde62408e8.png)

**Comment by zyyfit** [comment]
您好，没有复现呢，请问有什么特殊操作吗

**Comment by kouzhijian** [comment]
新建一个场景，不加任何场景步骤，直接点运行步骤，就可以复现

**Comment by xulinde** [comment]
没有步骤，是无法进行调试的
![image](https://user-images.githubusercontent.com/64065190/122501985-48962200-d028-11eb-8e96-9027016daf3e.png)
