### ISSUE TITLE
[BUG]使用xmind模板导入测试用例，在xmind中，只要包含了http://xxxxxx.com时，导入系统中，测试用例http后面的内容就被截取了

### ISSUE THREAD

**Issue by miraitowa000** [metersphere/metersphere#34429]
### 联系方式

miraitowa0805@gmail.com

### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

使用xmind模板导入测试用例，在xmind中，只要包含了http://xxxxxx.com时，导入系统中，测试用例http后面的内容就被截取了，没有显示http后面的内容

### 重现步骤

使用xmind模板导入测试用例，在xmind中，只要包含了http://xxxxxx.com时，导入系统中，测试用例http后面的内容就被截取了，没有显示http后面的内容

### 期待的正确结果

可以正确导入全部的内容

### 附加信息

![Uploading e8d0440912086876ba1c4063dc8f48f.png…]()
![Uploading f42ca8ea2b23599ecd103366a4d248c.png…]()

**Comment by 13290445582** [comment]
您好，请提供下您的导入Xmind文件。

**Comment by miraitowa000** [comment]
由于工作性质的原因，不能提供完整的xmind文件，可以提供一个demo

**Comment by miraitowa000** [comment]
[测试demo.zip](https://github.com/user-attachments/files/17943150/demo.zip)

**Comment by 13290445582** [comment]
您好，已收到您提供的demo文件，导入测试未发现问题。
![image](https://github.com/user-attachments/assets/71d7ed0f-cf16-47ec-940c-634377a04540)

**Comment by miraitowa000** [comment]
我们这边几个同事都试过了，在mac和windows上都测试过，还是不行，还需要提供什么信息吗？系统对应版本：v3.4.0-5291ac9a   这个和xmind的版本有没有关系呢？xmind版本：版本24.10.011013

**Comment by miraitowa000** [comment]
在https://demo.metersphere.com/这个环境也上传了文件，还是被截断了，可以上demo环境看

**Comment by 13290445582** [comment]
您好，我在V3.4环境测试了下，确实有这个情况，升级下V3.5吧，V3.5是可以正常导入的。

**Comment by miraitowa000** [comment]
升级之后，问题解决
