### ISSUE TITLE
[BUG]【接口场景】在场景里引用其他场景，设置使用原场景参数后，下面的步骤也是使用引用场景设置的变量值。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34436]
### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

【接口场景】在场景里引用其他场景，设置使用原场景参数后，下面的步骤也是使用引用场景设置的变量值。

### 重现步骤

【接口场景】在场景里引用其他场景，设置使用原场景参数后，下面的步骤也是使用引用场景设置的变量值。
![image](https://github.com/user-attachments/assets/afa3a163-4b73-473c-95f6-7ca22644b417)
![image](https://github.com/user-attachments/assets/a8539c6f-7697-47df-b42e-4b6d2bf00bde)
![image](https://github.com/user-attachments/assets/c0edc03b-9c2d-4de6-ba94-907165732a1a)

**Comment by 13290445582** [comment]
你好，这个不是缺陷，下面的步骤变量使用的是该场景内上下文的值，你上一个步骤的变量取的就是你所引用场景的参数值，且未发生改变。所以你这个步骤取的上一个步骤的值，就是那个引用场景的场景参数值。
