### ISSUE TITLE
[BUG] 场景前后步骤，设置前后置脚本打印，结果在每个步骤前后都执行打印

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34447]
### 联系方式

姚春荣

### MeterSphere 版本

v3.4

### 使用外置数据库

否

### 问题描述

场景前后步骤，设置前后置脚本打印，结果在每个步骤前后都执行打印

### 重现步骤

![af27ae1158293bc9b7729ffab812602](https://github.com/user-attachments/assets/e5cae850-84b8-4ad0-ae87-504aced5c44c)
![f58bfe30850ceaa67c8b7ab270fac92](https://github.com/user-attachments/assets/2d070435-92f7-4cd6-b1fa-926dfb4d8619)

**Comment by 13290445582** [comment]
1.场景步骤前后置脚本：在场景步骤前分别执行一次/在场景步骤后分别执行一次，这个就是每个场景步骤前后都会打印啊。
2.控制台显示的打印内容，是会包含显示该步骤之前的所有步骤的打印内容的。
