### ISSUE TITLE
[QUESTION]项目设置中功能有缺失

### ISSUE THREAD

**Issue by MaxLyl** [metersphere/metersphere#34450]
### 请描述您的问题

位置【项目设置】-》【消息设置】页面中没有机器人列表的tab，无法新增自定义机器人，使用的版本是 v2.10.21-lts

**Comment by luty2018** [comment]
自定义机器人是企业版功能哈。

**Comment by MaxLyl** [comment]
这个功能在3.0版本里是开放的，另外消息设置中钉钉机器人那个webhook设置，设置了能不能推送钉钉消息？
