### ISSUE TITLE
[BUG]性能测试脚本有多个线程组，顺序执行线程组，前后两个线程组之间无法实现csv文件关联，性能自动化无法实现

### ISSUE THREAD

**Issue by yiran-13** [metersphere/metersphere#34457]
### 联系方式

MeterSphere交流群19，依然，邮箱347102412@qq.com

### MeterSphere 版本

v2.10.15-lts,v2.10.21-lts

### 使用外置数据库

否

### 问题描述

性能测试脚本有多个线程组，顺序执行线程组，前后两个线程组之间无法实现csv文件关联，性能自动化无法实现
beanshell写入路径为/jmeter-log/xx.csv,读取路径为/test/xx.csv,复制都没有权限，也不可以在脚本里把两个路径设置成相同
![d6a310daff3ff68076281599b349c048](https://github.com/user-attachments/assets/a7fc44c3-48f4-4809-a32f-a1745464dfd6)

### 重现步骤

执行性能测试

**Comment by liuruibin** [comment]
性能测试执行处于沙箱状态权限很小，可以通过全局变量代替csv

**Comment by yiran-13** [comment]
不同线程组使用的csv文件不一样，后面的线程组使用的csv文件是从前面的执行线程组生成的

**Comment by yiran-13** [comment]
> 性能测试执行处于沙箱状态权限很小，可以通过全局变量代替csv

可否加微信聊下问题

**Comment by liuruibin** [comment]
很遗憾，设计上我们不支持输出文件和读取文件

**Comment by yiran-13** [comment]
可以把源码放开，我们自己改下代码

**Comment by yiran-13** [comment]
可以把源代码放开，我们自己二开一下吗

**Comment by liuruibin** [comment]
这个属于企业版功能了

**Comment by yiran-13** [comment]
只买这个功能怎么收费

**Comment by liqiang-fit2cloud** [comment]
功能不单独卖，只能买整个企业版，https://metersphere.io/enterprise.html

**Comment by yiran-13** [comment]
可以试用多少天

**Comment by liqiang-fit2cloud** [comment]
你去申请问问，有商务对接。不过企业版也不给源码。
