### ISSUE TITLE
[BUG]新建测试测试计划中关联测试用例，点击高级搜索，选择自定义字段需求ID进行筛选报错

### ISSUE THREAD

**Issue by a760097644** [metersphere/metersphere#34453]
### 联系方式

微信号：Asd-8998001  metersphere 交流群64 昵称：p

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

![微信图片_20241129100330](https://github.com/user-attachments/assets/a768a6a1-9b95-4f53-a590-f58d8d071016)
![微信图片_20241129100346](https://github.com/user-attachments/assets/f5f638ce-404d-40c5-a18c-057f85a6eca3)

### 重现步骤

新建测试计划中关联测试用例，点击高级搜索，选择自定义字段需求ID进行筛选报错

### 期待的正确结果

可筛选成功
v2.10.20-lts版本没有这个问题 升级新版本后才有这个问题

### 相关日志输出

```shell
/opt/metersphere/logs/test-track/info.log
```

### 附加信息

![image](https://github.com/user-attachments/assets/f9e4156a-4508-418c-9cca-23b23a959650)
![Uploading 微信图片_20241129100629.png…]()

**Comment by 13290445582** [comment]
您好，截图看下自定义字段需求ID。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
