### ISSUE TITLE
[BUG]MS集成禅道，缺陷同步后字段信息显示错误

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34452]
### 联系方式

M，403637897@qq.com

### MeterSphere 版本

3.4.0

### 使用外置数据库

否

### 问题描述

MS集成禅道，都是3.4.0版本，禅道18.10版本
MS创建缺陷同步至禅道后，禅道上查看缺陷字段信息不正确，包括bug类型，影响版本，优先级，严重程度

### 重现步骤

缺陷同步成功后查看禅道缺陷字段

### 期待的正确结果

字段同步成功，信息跟MS设置一致
![IMG_20241128_194806](https://github.com/user-attachments/assets/dbedfa84-9675-4d9b-bda3-38c174929e62)
![IMG_20241128_194822](https://github.com/user-attachments/assets/508dc025-7db6-4312-820f-c82c96300f37)
![IMG_20241128_194850](https://github.com/user-attachments/assets/b46acab8-5ec5-454b-a224-42f5a0d3d7d6)

**Comment by song-cc-rock** [comment]
MS模板里面这几个字段的选项值配置发出来看看, 有可能与禅道的页面给的这几个字段选项值不一致.
或者用禅道默认模板提缺陷试试, 这几个字段是否正确同步提交.

**Comment by michellefan123** [comment]
![Uploading IMG_20241128_194850.jpg…]()

**Comment by michellefan123** [comment]
这个是MS上模板配置

**Comment by michellefan123** [comment]
![Uploading IMG_20241129_143236.jpg…]()

**Comment by michellefan123** [comment]
![Uploading IMG_20241129_143243.jpg…]()

**Comment by michellefan123** [comment]
![Uploading IMG_20241129_143254.jpg…]()

**Comment by michellefan123** [comment]
![Uploading IMG_20241129_143534.jpg…]()

**Comment by michellefan123** [comment]
自定义字段设置key值就成功了
