### ISSUE TITLE
[QUESTION]metersphere3版本中，缺陷管理有一个所属平台字段的用处以及修改方式是什么

### ISSUE THREAD

**Issue by zxz0x01** [metersphere/metersphere#34468]
### 请描述您的问题

metersphere3版本中，缺陷管理有一个所属平台字段，默认是Loacl。
请问这个字段作用是什么，在哪里可以修改这个字段的值
![image](https://github.com/user-attachments/assets/e4133eb4-a6dc-4d64-8099-d6c198f2f32c)

**Comment by song-cc-rock** [comment]
MS缺陷管理模块可以与第三方项目管理平台进行对接, 只需上传平台插件即可, 该字段的值为新建缺陷时当前项目配置中对接的平台. 无法修改. 默认不对接为`Local`, 表示为本地(MS)缺陷

#### 参考如下:
=> **上传集成插件**
![image](https://github.com/user-attachments/assets/578263b0-7fcb-4e1b-a7f5-b95c1f1435ec)
=> **项目配置对接**
![image](https://github.com/user-attachments/assets/0bb17ed7-5a6c-458c-8b61-28d151da70ce)
