### ISSUE TITLE
[BUG] CSV参数预览异常

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34463]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

在自动化场景中本地上传一个csv，然后关闭参数页面，这时候去修改刚才上传的本地CSV文件，再次打开参数页面的预览，无法正常预览CSV文件。一直转圈。

![image](https://github.com/user-attachments/assets/922275a7-ab4b-496e-b955-3ef38f488e19)

### 重现步骤

如上所述

### 期待的正确结果

正确 预览

**Comment by 13290445582** [comment]
您好，最新版本未复现此问题，请提供下您的csv文件，建议使用最新版本测试。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
