### ISSUE TITLE
[QUESTION] helm 安装，外部数据库，需要按照官网提供的my.cnf 配置mysql

### ISSUE THREAD

**Issue by hichenxinyu** [metersphere/metersphere#34478]
### 请描述您的问题

![image](https://github.com/user-attachments/assets/b881abdc-0489-48c0-ad15-9283ad2573e6)

版本 v3.4.0-5291ac9a
helm 安装，外部数据库，报错如下，麻烦看下原因

### Error querying database. Cause: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'metersphere.u.create_time' which is not in SELECT list; this is incompatible with DISTINCT ### The error may exist in io/metersphere/system/mapper/ExtUserMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT DISTINCT u.id, u.NAME, u.email FROM `user` u LEFT JOIN user_role_relation urr ON u.id = urr.user_id WHERE urr.source_id = ? and u.deleted = false order by u.create_time desc limit 1000 ### Cause: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'metersphere.u.create_time' which is not in SELECT list; this is incompatible with DISTINCT ; uncategorized SQLException; SQL state [HY000]; error code [3065]; Expression #1 of ORDER BY clause is not in SELECT list, references column 'metersphere.u.create_time' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by liuruibin** [comment]
外置数据库是按照我们官网给的my.cnf部署的吗
https://metersphere.io/docs/v3.x/installation/offline_installation/#42

```
[mysqld]
datadir=/var/lib/mysql

default-storage-engine=INNODB
character_set_server=utf8mb4
lower_case_table_names=1
performance_schema=off
table_open_cache=128
transaction_isolation=READ-COMMITTED
max_connections=1000
max_connect_errors=6000
max_allowed_packet=64M
innodb_file_per_table=1
innodb_buffer_pool_size=512M
innodb_flush_method=O_DIRECT
innodb_lock_wait_timeout=1800

server-id=1
log-bin=mysql-bin
expire_logs_days = 2
binlog_format=mixed

character-set-client-handshake = FALSE
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
init_connect='SET default_collation_for_utf8mb4=utf8mb4_general_ci'

sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

skip-name-resolve

[mysql]
default-character-set=utf8mb4

[mysql.server]
default-character-set=utf8mb4
```

**Comment by hichenxinyu** [comment]
按照这个参数修改后，重新部署了 metersphere 报错
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 3.0.0.2 !

![image](https://github.com/user-attachments/assets/0d98130c-2918-4dce-91f5-e24c47f3c58d)

**Comment by liuruibin** [comment]
https://metersphere.io/docs/v3.x/ask_question/install_question/#3-metersphere-schema-metersphere-contains-a-failed-migration-to-version-3202

按照这个文档操作
