### ISSUE TITLE
[BUG]功能用例自定义字段和自定义ID筛选存在问题

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#34489]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

是

### 问题描述

用例模板新增自定义字段【自动化】，功能用例添加筛选条件时此字段时存在问题，v2.10.16版本使用无此问题
![image](https://github.com/user-attachments/assets/e9624363-10db-467f-9abb-7ab2257a09a9)
用例开启自定义ID，筛选ID包含关键字，结果存在问题。
![image](https://github.com/user-attachments/assets/dd4cd4ea-8a9e-4c96-9c9d-410f2307ee76)
![image](https://github.com/user-attachments/assets/f12b2d83-58c6-48b2-a286-a075214c875b)

### 重现步骤

1、用例模板添加新增自定义字段【自动化】；
2、上传用例，字段【自动化】部分填写’是‘，部分填写’否‘；
3、添加筛选条件，选择 自动化 属于 是 ；
![image](https://github.com/user-attachments/assets/ac0f61dc-e031-4a6c-81f5-716e350cf871)
![image](https://github.com/user-attachments/assets/2466c539-24fa-4b2f-9da4-270d21b3c82e)
4、重置筛选条件，在用例内容页面根据下拉框筛选字段【自动化】，可正常显示
![image](https://github.com/user-attachments/assets/ec84dee3-b4a1-4a23-98df-32d7c4537dd6)
5、重置步骤4下拉框，重复步骤3的添加筛选条件，改为筛选内置字段如【用例状态】，可正常筛选
![image](https://github.com/user-attachments/assets/832eb4c3-b6de-4e0a-912e-a8970e6d47b1)
![image](https://github.com/user-attachments/assets/c35b0c87-1e21-46f6-92dc-fd6bbc640f1a)

### 期待的正确结果

功能用例可正常通过自定义字段和自定义ID进行筛选

**Comment by 13290445582** [comment]
您好，自定义ID问题已复现；未复现自定义字段高级搜索的问题，请使用无痕浏览器再次测试下是否还能复现问题，可以提供下具体自定义字段的模板配置。

**Comment by 13290445582** [comment]
您好，自定义字段问题已经有用户提过了，在即将发布的v2.10.22版本修复，自定义ID问题后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
