### ISSUE TITLE
[BUG]运行场景时，状态一直是stop，几个小时了都还是这个状态

### ISSUE THREAD

**Issue by zizi457** [metersphere/metersphere#34485]
### 联系方式

253774710@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

否

### 问题描述

创建了一个场景，该场景引用了9个场景，这9个场景又引用了用例。大概300多条用例，运行场景，状态一直stop
![Snipaste_2024-12-03_15-31-32](https://github.com/user-attachments/assets/8a0e6a58-aecf-4a03-b143-ec8b37fa92cd)

### 重现步骤

见上面

### 附加信息

![Uploading Snipaste_2024-12-03_15-31-32.jpeg…]()

**Comment by zizi457** [comment]
刚复现了，因为有一条用例一直在跑，
![Uploading Snipaste_2024-12-03_17-24-45.jpeg…]()

**Comment by 13290445582** [comment]
你好，图片未上传成功，异常用例移除掉执行场景应该就没问题了。
