### ISSUE TITLE
[BUG] swagger 导入请求体为空

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34491]
### 联系方式

姚春荣

### MeterSphere 版本

v3.5.0

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/866c50c6-9edd-47c8-b366-2e35a3c6a58d)

### 重现步骤

swagger文件只能私发
![image](https://github.com/user-attachments/assets/1c5c897d-ccb6-48a8-a174-334167573504)

补充：postman导入请求体不能null，是有值的

**Comment by liuruibin** [comment]
如果不是标准swagger3我们这里很难预测

文件不能上传直接找qa发

**Comment by Somebody-JIAN** [comment]
你上次给的文件中，

swagger2说是swagger3，

并且  "$ref"  引用的对象整个上下文中也没找到，不规范。

这次你先自己检查一遍吧。 确定这是规范的swagger3文件，直接企业微信发给我。
