### ISSUE TITLE
[BUG]配置环境保存提示-->finish Connect(..) failed: Connection refused:

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#34494]
### 联系方式

chase001@qq.com

### MeterSphere 版本

版本:   v2.10.20-lts-9feb97b3

### 使用外置数据库

是

### 问题描述

[BUG]配置环境保存提示-->finish Connect(..) failed: Connection refused:

### 重现步骤

[BUG]配置环境保存提示-->finish Connect(..) failed: Connection refused:

![image](https://github.com/user-attachments/assets/ccaa8a5f-579a-4704-a19e-9a974ea8009e)

**Comment by liuruibin** [comment]
后台有啥日志，是否有容器重启

**Comment by chase001** [comment]
有重启日志
![image](https://github.com/user-attachments/assets/134862fa-3a10-4ffc-9090-442ecd3f78b9)

**Comment by 13290445582** [comment]
你好，升级下最新环境吧，没出现过这个问题。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
