### ISSUE TITLE
[QUESTION]接口测试场景与集合执行的问题

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#345]
**请描述您的问题.**

请问每个场景以及每个集合一起执行时，是并行执行的吗？

问题现象：目前并行执行存在问题，比如我们所有接口的请求都需要带token认证信息，token会过期，目前想要每个场景去调用接口获取token并存入到全局变量，但是全局变量产生的值每个场景不能共用，导致批量执行接口总因为Token过期执行不了

**Comment by wangzhen-fit2cloud** [comment]
你好，目前多个场景是按顺序执行的，变量全局通用的场景我们会在后续的版本中支持
