### ISSUE TITLE
[FEATURE]MS集成禅道，MS能否将bug对应用例的所属模块信息一起同步至禅道

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34509]
### MeterSphere 版本

3.4.0

### 联系方式

M，403637897@qq.com

### 请描述您的需求或者改进建议

MS禅道模板如果新增所属模块字段，对应选项会比较多
MS新增缺陷是对应用例的，能否将对应用例的所属模块信息一起同步至禅道

### 请描述你建议的实现方案

MS新增缺陷是对应用例的，能否将对应用例的所属模块信息一起同步至禅道
![IMG_20241204_155121](https://github.com/user-attachments/assets/75bb8631-f459-4e69-b663-0e5bc103522f)

**Comment by song-cc-rock** [comment]
两边数据未打通, 暂时无法同步过去. 
可以理解在MS禅道模板新增所属模块字段就是与第三方平台打通并同步. 如果觉得配置字段麻烦可以使用系统给你生成的禅道默认模板来对接.
