### ISSUE TITLE
[BUG]MS集成禅道，禅道上修改同步的缺陷，发现影响版本显示为空

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34504]
### 联系方式

M，403637897@qq.com

### MeterSphere 版本

V3.4.0

### 使用外置数据库

否

### 问题描述

MS3.4.0集成禅道，禅道18.10，MS上缺陷同步至禅道成功，禅道缺陷列表影响版本显示正确，修改缺陷提交影响版本显示为空，需要重新选择影响版本

### 重现步骤

禅道查看同步后的缺陷列表
![mmexport1733277873729](https://github.com/user-attachments/assets/0aeb1904-3cc7-4293-87d9-7f0f0b9b51f9)
查看缺陷详情时影响版本正确
![mmexport1733277876857](https://github.com/user-attachments/assets/035a0435-e8cc-40c4-a0ab-046e33585a02)
修改缺陷，影响版本显示为空
![mmexport1733277879784](https://github.com/user-attachments/assets/eaff70de-8f6d-426d-85c2-dee3cec923b7)

**Comment by song-cc-rock** [comment]
是否手动配置的模板中**影响版本**字段选项值未与禅道的字段对应, 也可以考虑使用自动生成的禅道默认模板.
![image](https://github.com/user-attachments/assets/eb5cdb4b-d9d0-407f-a35e-1060b7890a13)
![image](https://github.com/user-attachments/assets/02393499-a2d6-4b3f-9d02-9db1c5cb85b2)

**Comment by michellefan123** [comment]
是对应的，禅道上bug列表显示的影响版本正确，详情里面也正确，就是修改缺陷时显示为空

默认禅道模板也是一样的
影响版本的key值要像这样设置吗？我没查到对应key值就直接没选key值

**Comment by song-cc-rock** [comment]
> 是对应的，禅道上bug列表显示的影响版本正确，详情里面也正确，就是修改缺陷时显示为空
> 
> 默认禅道模板也是一样的 影响版本的key值要像这样设置吗？我没查到对应key值就直接没选key值

要设置key值, 同步到禅道就是提交key值, 没有key就无法对应.

**Comment by song-cc-rock** [comment]
> 是对应的，禅道上bug列表显示的影响版本正确，详情里面也正确，就是修改缺陷时显示为空
> 
> 默认禅道模板也是一样的 影响版本的key值要像这样设置吗？我没查到对应key值就直接没选key值

自动生成的禅道默认模板应该不会没对应吧, 会自动生成影响版本的选项值key, value.

**Comment by song-cc-rock** [comment]
配置选项字段key值的时候可以去禅道页面f12抓一下, 一般是有的.
![image](https://github.com/user-attachments/assets/70e0cbd4-275f-421d-9cd6-f4e9cbe81acd)

**Comment by michellefan123** [comment]
MS上现在有三个模板，自己建的禅道，还有一个默认，另一个禅道默认模板只有提交的时候看得到，
项目1使用禅道默认模板可以显示影响版本，但是影响版本只显示项目2的版本号，未显示项目1版本号，项目2使用禅道默认模板很多字段显示不出来，使用默认模板可以显示，效果同自己建的模板一样

**Comment by song-cc-rock** [comment]
> MS上现在有三个模板，自己建的禅道，还有一个默认，另一个禅道默认模板只有提交的时候看得到， 项目1使用禅道默认模板可以显示影响版本，但是影响版本只显示项目2的版本号，未显示项目1版本号，项目2使用禅道默认模板很多字段显示不出来，使用默认模板可以显示，效果同自己建的模板一样

是说生成的禅道默认模板中版本号不是所对接的项目版本号是吧, 我来排查一下

> 注: 禅道默认模板是不给看的, 自动生成的

**Comment by song-cc-rock** [comment]
> MS上现在有三个模板，自己建的禅道，还有一个默认，另一个禅道默认模板只有提交的时候看得到， 项目1使用禅道默认模板可以显示影响版本，但是影响版本只显示项目2的版本号，未显示项目1版本号，项目2使用禅道默认模板很多字段显示不出来，使用默认模板可以显示，效果同自己建的模板一样

**根据禅道官方的API, 目前MS只能使用项目配置中的对接项目Key(不是产品Key)来生成禅道默认模板, 并获取版本号的, 看是否项目Key填错了.**
![image](https://github.com/user-attachments/assets/f9400820-5208-4e56-a07a-f0b84476b388)


**正常的禅道项目对接步骤如下:**

1. 拿到禅道项目Key 001
    ![image](https://github.com/user-attachments/assets/63e399db-990b-42af-a5b9-8f93602b871e)

2. MS项目对接配置
    ![image](https://github.com/user-attachments/assets/40d55aa2-9070-4fc9-9ea8-776369345495)

3. MS项目模板如下
    ![image](https://github.com/user-attachments/assets/c3bbcaee-0a2a-4e99-896a-f9af3809ccd2)

4. 提缺陷测试 (禅道默认模板可获取对接禅道001的版本, 无需手动配置字段及选项值)
    ![image](https://github.com/user-attachments/assets/08f20b87-fe79-44a9-b286-efb264b520fc)

> 由于禅道官方的API缺少支持部分字段, 自动生成的禅道默认模板暂时不能全部字段.

**Comment by michellefan123** [comment]
改成项目key值使用禅道默认模板解决问题了，之前用的是产品key
