### ISSUE TITLE
[BUG]MS 使用p12证书，测试双向认证接口失败，提示No var called 'User-Defined-KeyStore-47证书' found

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#34519]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

MS 使用p12证书，测试双向认证接口失败，提示No var called 'User-Defined-KeyStore-47证书' found，同样的证书，同样的接口，jmeter测试通过
![image](https://github.com/user-attachments/assets/89f004f3-641c-4067-88f5-8985106beacb)
![image](https://github.com/user-attachments/assets/41989e0f-cd18-4144-ab70-756ff7beef53)
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/fedd6f6b-833a-42e8-bd6e-c94c81db0f90">
<img width="804" alt="image" src="https://github.com/user-attachments/assets/2fd801ce-b5f7-4811-a351-106adb5593b6">

### 重现步骤

MS 使用p12证书，测试双向认证接口失败，提示No var called 'User-Defined-KeyStore-47证书' found，同样的证书，同样的接口，jmeter测试通过

### 期待的正确结果

MS 使用p12证书，测试双向认证接口成功

**Comment by fit2cloud-lijiaxin** [comment]
![image](https://github.com/user-attachments/assets/ccd4ea74-be94-4d79-8334-5040bcf99915)
MS 环境配置

**Comment by fit2-zhao** [comment]
把别名去掉。

**Comment by fit2cloud-lijiaxin** [comment]
多谢，解决了，可否加个提示噻！

**Comment by fit2-zhao** [comment]
提示你不都写了吗 ：
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/82f295e7-96ad-4ad7-aac1-50433e0ba4c6">
