### ISSUE TITLE
接口测试模块，导入jmeter格式的文件，生成的接口，请求头中参数值中包含参数名。

### ISSUE THREAD

**Issue by pengfei999** [metersphere/metersphere#34511]
### 联系方式

875184828@qq.com

### MeterSphere 版本

v3.3.0-c48b9fb2

### 使用外置数据库

否

### 问题描述

接口测试模块，导入jmeter格式的文件，生成的接口，请求头中参数值中包含参数名。

### 重现步骤

步骤1：登陆系统
步骤2：选择接口测试-定义
步骤3：点击导入接口，选择jmeter选项，点击导入
![b6f61d10b023bb11f3c93192083db07](https://github.com/user-attachments/assets/f8879c28-8084-4f7c-880d-584f18d1f74e)

### 期待的正确结果

导入jmeter文件后的接口请求头，参数值的内容不包含参数名

**Comment by Somebody-JIAN** [comment]
![image](https://github.com/user-attachments/assets/daf1ec53-1226-4b4a-8c78-2bdf8bc35517)
![image](https://github.com/user-attachments/assets/3b765c60-949f-4c2b-be50-cfdc1f1cc2c6)
![image](https://github.com/user-attachments/assets/05cd13fa-f06c-4083-8e4c-2c892334f5a0)

在v3.5以及更新的版本里我们没有发现这个问题。  希望您能提供一下更多的复现步骤

**Comment by pengfei999** [comment]
您好：
使用&nbsp;docker run -d -p 8081:8081 --name=metersphere -v ~/.metersphere/data:/opt/metersphere/data metersphere/metersphere-ce-allinone
在线升级到v3.5版本后还是存在这个问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 接口测试模块，导入jmeter格式的文件，生成的接口，请求头中参数值中包含参数名。 (Issue #34511)





 
image.png (view on web)
 image.png (view on web)
 image.png (view on web)
 
在v3.5以及更新的版本里我们没有发现这个问题。  希望您能提供一下更多的复现步骤

**Comment by hao65103940** [comment]
[9999.txt](https://github.com/user-attachments/files/18019117/9999.txt)

原文件如上，下载之后，把后缀改成jmx格式，然后导入到MS里面即可。


![image](https://github.com/user-attachments/assets/727e9444-4bf0-4abb-8986-d617aecc942e)

**Comment by Somebody-JIAN** [comment]
收到，经过对比之后发现了问题，这个月的版本中会包含此次修复

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。
