### ISSUE TITLE
[BUG] OIDC 相关问题

### ISSUE THREAD

**Issue by leshalv** [metersphere/metersphere#34523]
### 联系方式

2689170096@qq.com

### MeterSphere 版本

3.5.0

### 使用外置数据库

否

### 问题描述

1. 使用OIDC 单点登录，登录后发现采用sub作为用户名，在OIDC标准中，sub应该是用户id，preferred_username 是用户名，这里存在使用错误。
<img width="505" alt="image" src="https://github.com/user-attachments/assets/a4859d54-4285-461d-9606-8792bd0227ed">

2. OIDC 配置回调地址的时候，需要用户来进行设置（正常这个回调地址是固定的 ），而且需要使用${authId}这个占位符，在实际应用的时候，并不知道这个authId到底是多少，没有地方展示，SSO服务端配置也是问题，所以产品设计上并不那么合理。后来我有一种猜想，这里是不是可以自定义配置，于是我改成了一个固定值，在回调的时候提示，该身份源已删除
<img width="1888" alt="image" src="https://github.com/user-attachments/assets/f8a71b53-a1aa-4c76-a608-c11ecaf120a5">

### 重现步骤

在后台管理即可查看

**Comment by liuruibin** [comment]
preferred_username 不一定每个server都会提供，我们采用保守方式，先将用户加入。进入系统可以自行修改

${authId} 并不需要知道，我们页面跳转时会解析出来实际值

**Comment by leshalv** [comment]
SSO 服务端需要配置重定向url，你可以理解为是白名单，因此需要知道${authId}值

**Comment by leshalv** [comment]
具体这里可以参考一些其他平台的oauth2认证逻辑，我认为username映射这里，可以做成可选，比如是用sub还是preferred_username @liuruibin

**Comment by leshalv** [comment]
我在测试不使用${authId}变量的时候，比如固定一个值写死，重定向过来会提示认证源已被删除，我想应该是通过authId查询的

**Comment by liuruibin** [comment]
<img width="1783" alt="image" src="https://github.com/user-attachments/assets/93484459-106e-431f-9fe4-1e99bcc6d735">
在你的OIDC登录页面会看到这个实际的authId
