### ISSUE TITLE
[BUG]【接口定义】将swagger的json文件导入接口定义处，将postman里的脚本导入场景里，自定义请求都勾选了使用环境，但是场景覆盖率统计不对。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34530]
### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

【接口定义】将swagger的json文件导入接口定义处，将postman里的脚本导入场景里，自定义请求都勾选了使用环境，但是场景覆盖率统计不对。显示只覆盖了3个请求，实际上至少十几个。

### 重现步骤

【接口定义】将swagger的json文件导入接口定义处，将postman里的脚本导入场景里，自定义请求都勾选了使用环境，但是场景覆盖率统计不对。显示只覆盖了3个请求，实际上至少十几个。
![image](https://github.com/user-attachments/assets/a75c6bb9-126d-46b6-ae13-f6b4d938d961)

![image](https://github.com/user-attachments/assets/5f176018-0503-492f-95f5-b0eee1a9d7fa)

接口定义数据
[Swagger_Api_共享平台-协同工作台.json]
(https://github.com/user-attachments/files/18022448/Swagger_Api_.-.json)

场景数据
[Metersphere_Scenario_共享平台-协同工作台.json]
[Metersphere_Scenario_共享平台-协同工作台.json](https://github.com/user-attachments/files/18022493/Metersphere_Scenario_.-.json)

**Comment by Somebody-JIAN** [comment]
场景文件中的部分步骤缺少这个属性：

![image](https://github.com/user-attachments/assets/b7e67245-4b65-4ac7-af1b-452e7a1a5a41)

有些步骤比如/card/add存在这个属性，有些比如/card/page没有这个属性。
在保存时用这个属性判断是否需要记录路径等信息。

我尝试创建了一下自定义步骤，是不会缺少这个的。

所以你文件中的缺少这些属性的数据是怎么操作出来的? 这个属性不应该缺少的。

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
