### ISSUE TITLE
[BUG]高亮移动到模块上时，模块的用例数就看不见了

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34542]
### MeterSphere 版本

v3.5.0-c3ad9f70

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/6b47acfe-25b2-481a-8940-b99548ef136c)

### 重现步骤

![image](https://github.com/user-attachments/assets/ddffb5e6-ca56-41c4-9970-ad562336ff1d)

**Comment by 13290445582** [comment]
您好，MeterSphere的V3版本我们现在设计上就是不显示的，因为hover模块时后面有「选择当前」等操作，且个别模块名可能存在很长的情况，导致若再要显示用例数量，会显得混乱拥挤，若有好的方案也建议您后面提出，感谢您的理解与支持。
