### ISSUE TITLE
[BUG]【接口自动化】自定义请求的请求执行后，改成其他地址，点击保存后再次运行，请求内容显示发送的地址还是原本的。

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34568]
### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

【接口自动化】自定义请求的请求执行后，改成其他地址，点击保存后再次运行，请求内容显示发送的地址还是原本的。

### 重现步骤

【接口自动化】自定义请求的请求执行后，改成其他地址，点击保存后再次运行，请求内容显示发送的地址还是原本的。
![image](https://github.com/user-attachments/assets/3187b0e0-e963-4ffb-91af-073eeeeb62fc)
![image](https://github.com/user-attachments/assets/defb7e97-2050-43e3-a0df-536c0fca928a)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
