### ISSUE TITLE
[QUESTION]我执行jmeter文件提示：Error: 无法解析JMX文件，请确认是否缺少执行需要的 jar 等文件

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#34565]
### 请描述您的问题

我的metersphere是2.0版本的
上传jmeter文件后提示缺失jar包，怎么处理呢
我的jmeter是5.6
![B4135792-6688-4D3C-A37F-C3CA736F4F2A](https://github.com/user-attachments/assets/9b3476d3-833a-4c30-90f8-1cf1f9bb2171)

**Comment by liuruibin** [comment]
编辑性能测试上传缺少的jar

**Comment by hujirong521317** [comment]
![image](https://github.com/user-attachments/assets/c5d184af-3f04-45cf-a1c8-9036f56227c2)
这个也没有提醒缺失什么jar包，我把ext下的jar包都上传了，还是有问题呢

**Comment by liuruibin** [comment]
打开你的jmx看看引入了哪些文件，上传这些文件。你上传的ext文件是系统自带的不需要上传。

**Comment by hujirong521317** [comment]
嗯好的，现在看时可以了
