### ISSUE TITLE
[BUG]MS集成禅道，服务器重启后，MS连接禅道失败

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34564]
### 联系方式

M，403637897@qq.com

### MeterSphere 版本

3.4.0

### 使用外置数据库

否

### 问题描述

MS服务器重启后，登录MS界面，禅道连接测试，超时后提示禅道地址错误或用户名密码错误

### 重现步骤

MS集成禅道功能正常；
MS服务器重启；
MS服务器启动后，登录MS，禅道连接测试失败
errlog日志上报resource-ID不能为空

**Comment by michellefan123** [comment]
![Uploading IMG_20241209_174532.jpg…]()

**Comment by liuruibin** [comment]
图片上传失败了，请重新上传

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
