### ISSUE TITLE
[BUG] 批量执行自动化场景无法完全停止

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34563]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

如果选择批量执行自动化场景，选择集合报告，在任务中心处点击停止后，只有当前执行的场景会被停掉，但是队列后边的用例还是会执行，无法完全停止。
![image](https://github.com/user-attachments/assets/b72cb166-9546-4d0e-9eb2-002708b2a72f)

这里虽然更新了集合报告的状态，但是后续的场景会把报告的状态由STOP改为SUCCESS或ERROR
io.metersphere.service.ext.ExtApiTaskService#apiStop
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/5ac93b48-dc3d-43c5-b9a0-a491dbd48c64">

### 重现步骤

如上所述。

### 期待的正确结果

期望一次停止。

**Comment by fit2-zhao** [comment]
报告的停止机制与执行机制类似，均为异步操作。在以下情况下，部分任务可能无法被强制终止：

结果未消费：执行结果已推送至 Kafka，但客户端尚未消费，此时无法强制终止；
资源池任务：任务已在资源池中执行，强制停止仅能终止部分任务，无法完全停止；
分布式执行：在多个执行机上分散执行的任务，由于分布于不同资源池，停止操作可能无法完全终止。此时，停止效果与停止指令推送的先后顺序有关。

**Comment by ijwstl** [comment]
> 报告的停止机制与执行机制类似，均为异步操作。在以下情况下，部分任务可能无法被强制终止：
> 
> 结果未消费：执行结果已推送至 Kafka，但客户端尚未消费，此时无法强制终止； 资源池任务：任务已在资源池中执行，强制停止仅能终止部分任务，无法完全停止； 分布式执行：在多个执行机上分散执行的任务，由于分布于不同资源池，停止操作可能无法完全终止。此时，停止效果与停止指令推送的先后顺序有关。

可能我没描述清楚，比如有a ,b ,c三个用例，当前执行的是用例a（串行+集合报告），我点击停止，只删掉了api_execution_queue_detail表里当前执行a的记录，没有把后续的队列删掉，导致a回传时还会执行queue.next，导致后续执行

![image](https://github.com/user-attachments/assets/6f4eb2fa-22d7-42e0-9e0a-609024f13c17)

**Comment by fit2-zhao** [comment]
后续版本修复此问题，感谢。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
