### ISSUE TITLE
[BUG]创建接口自动化场景用例很慢，后台查看存在慢sql

### ISSUE THREAD

**Issue by H-loyal** [metersphere/metersphere#34583]
### 联系方式

MeterSphere 交流群68、愿兮、huangz@hustcad.com

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

创建接口自动化场景用例需要3-5分钟，查看存在慢sql如下：
select * from api_scenario where api_scenario.project_id = 'b16bd49c-b9d1-11ee-b2f6-0242ac110003' ORDER BY num DESC LIMIT 1;

- 创建接口自动化场景用例接口响应：
![f06b0152b69aeeb9621ddd4bbe73069](https://github.com/user-attachments/assets/2fd30640-8563-4e5c-9dd6-bebe71cf7fcf)

- 数据库执行慢sql
![25b27057cc382fb92d26a528c5d8408](https://github.com/user-attachments/assets/19e3cb01-b76f-49d7-8ea2-844f26990fdf)

### 重现步骤

1、登录数据库，开启慢sql日志；
2、创建接口自动化场景用例，点击保存；

**Comment by fit2-zhao** [comment]
加个索引试试看：

`CREATE INDEX idx_num ON api_scenario (num DESC);`

**Comment by H-loyal** [comment]
问题解决关闭，谢谢！
![image](https://github.com/user-attachments/assets/a7741b14-6b47-4ea8-9043-f94825ecd0c5)
