### ISSUE TITLE
[BUG]接口自动化中后置脚本执行时有概率导致同一脚本执行出不同结果

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#34598]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

否

### 问题描述

接口自动化中在后置脚本中我添加了一个脚本并执行，发现脚本无法得到我想要的结果。但是相同的脚本我在其他的场景中执行时没有问题的。

### 重现步骤

1.新建接口自动化并复制一个带有后置脚本的接口
2.执行
3.观察执行结果

### 附加信息

下面一张图是脚本执行前的图片
![脚本执行前的截图](https://github.com/user-attachments/assets/6384e139-daf5-48c9-98b6-cafa0070923b)
下面一张是脚本执行结果图
![脚本执行结果图](https://github.com/user-attachments/assets/cffea1f0-2e01-483b-ba8a-cd4d61ce4dd8)
下面一张是脚本执行后图
![脚本执行后的图](https://github.com/user-attachments/assets/8d1c2568-57a1-4ff6-bb8c-97205e6178cd)
在上述中脚本执行结果的异常难以复现，但是脚本序号的变更是必现的。此处未添加任何全局后置脚本。

**Comment by 13290445582** [comment]
您好，脚本序号变更问题已复现，后续版本修复。脚本执行结果问题未复现，后续有必现步骤请反馈，感谢。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
