### ISSUE TITLE
[FEATURE]测试用例执行接口测试之后，希望能在当前测试页面查看失败的具体原因，而非去接口测试页面查看失败原因

### ISSUE THREAD

**Issue by Guanyan1996** [metersphere/metersphere#346]
**请描述您的需求或者改进建议.**

在尝试使用的时候发现，在测试用例执行页面中，无法查看每条接口测试结果的详细信息，需要到接口测试页面中才能查看，希望不 需要经过跳转。

**Comment by wangzhen-fit2cloud** [comment]
你好，在这个页面里是有显示测试结果的啊
![image](https://user-images.githubusercontent.com/27671436/92341723-282c5500-f0f1-11ea-987b-92861210bd9d.png)
