### ISSUE TITLE
[FEATURE]希望metersphere v2版本性能压测能支持dubbo2.7以下版本

### ISSUE THREAD

**Issue by wangxingxi** [metersphere/metersphere#34618]
### MeterSphere 版本

v2.10.17-lts

### 联系方式

MeterSphere交流群69  淡定 277618103@qq.com

### 请描述您的需求或者改进建议

metersphere v2版本性能压测支持了dubbo协议，但是使用的jmeter插件版本太高，压测dubbo 2.7以下版本时，qps压不上去：
1. metersphere v2在性能压测dubbo接口时，会动态拉起一个jmeter容器，里面使用了jmeter插件jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar，该插件在压测2.7版本以下的接口时，存在问题，导致qps压不上去
2. 为了验证是插件版本问题，我们将jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar该插件下载到了本地的jmeter中，相同条件下通jmeter的低版本插件进行了对比：
将metersphere自带的dubbo压测插件jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar下载到本地，使用本地jmeter压测，100并发下，平均rt45，qps 21.8，且存在异常1.55%
![image](https://github.com/user-attachments/assets/85966407-bc57-487c-91e1-f0f62b0633fe)
同样dubbo接口，同样并发下，压测同样时间，使用官网下载的插件jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar，本地jmeter压测，100并发下，平均rt13，qps 7234.7，成功率100%：
![image](https://github.com/user-attachments/assets/cadbd7af-553a-431f-bcfd-8f83c32df972)
3. 我们也同样从jmeter插件官网下载了jmeter-plugins-dubbo-2.7.4.1-jar-with-dependencies.jar进行验证，同样存在压不上去的问题

### 请描述你建议的实现方案

我们也尝试在压测时拉起的jemter容器中更换插件为jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar，但是更换后，压测时直接提示解析失败：Error: 无法解析JMX文件，请确认是否缺少执行需要的 jar 等文件
对应日志：
![image](https://github.com/user-attachments/assets/06c6613f-3538-4601-8d95-9c1cad7c9df4)
猜测应该是内置的jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar插件并非原生的，应该metersphere在原生的基础上做了封装，现在希望能提供一份基于jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar版本的插件封装，以支持低版本dubb接口的压测，不需要重度集成，只是多封装一个版本插件，可以让用户自己在镜像中进行替换

**Comment by liuruibin** [comment]
很抱歉，我们没有计划修改这里

**Comment by wangxingxi** [comment]
能用jmeter-plugins-dubbo-1.3.8-jar-with-dependencies.jar替换jmeter-plugins-dubbo-2.7.14-jar-with-dependencies.jar重新打包个插件吗，我们自己去容器中替换，或者告诉我们该怎么封装这个插件也行，我们的业务中dubbo接口有很大一部分，无法绕过这个使用场景

**Comment by liuruibin** [comment]
https://github.com/metersphere/jmeter-plugins/tree/main/jmeter-plugins-for-apache-dubbo

代码在这里，你可以自己修改

**Comment by wangxingxi** [comment]
好的，多谢，我们看下，另外方便简单介绍下，主要改了哪些地方吗

**Comment by wangxingxi** [comment]
> https://github.com/metersphere/jmeter-plugins/tree/main/jmeter-plugins-for-apache-dubbo
> 
> 代码在这里，你可以自己修改

你好，我按照这个工程，修改了里面依赖的dubbo2.7.12， 换成了2.6.4版本，重新打包成jar包，在本地jmeter已经可以正常压测，但是上传到metersphere压测时，报错解析失败“Error: 无法解析JMX文件，请确认是否缺少执行需要的 jar 等文件”：
![image](https://github.com/user-attachments/assets/9c31d73b-ca75-4ec2-b74f-4ed156bb59bb)
ClassNotFoundException: org.apache.dubbo.config.ReferenceConfig，这个类还是2.7的，2.6的路径不同，是com.alibaba.dubbo.config.ReferenceConfig，请教下这里解析是在哪一部分，我本地jmeter压已经没问题了，修改主要是pom里易用的dubbo版本和几个类中对应依赖
