### ISSUE TITLE
[QUESTION]为什么执行API case，没有运用到环境前置脚本的token信息，但是在接口自动化中场景里就可以运用全局前置呢

### ISSUE THREAD

**Issue by hujirong521317** [metersphere/metersphere#34623]
### 请描述您的问题

为什么执行API case，没有运用到环境前置脚本的token信息，但是在接口自动化中场景里就可以运用全局前置呢
![image](https://github.com/user-attachments/assets/9e5db8e8-3cd6-48c4-9ace-018809f01266)
![Uploading image.png…]()

**Comment by fit2-zhao** [comment]
<img width="901" alt="image" src="https://github.com/user-attachments/assets/1784f527-c000-48bb-b0fa-12a3f33d4bcf" />

有一张图上传失败了，你是在环境中的："单个请求步骤前执行" 中写的脚本吗？

**Comment by hujirong521317** [comment]
![image](https://github.com/user-attachments/assets/ba6e3f3c-c0fe-4f42-90ba-1a52c55401a4)
是在环境配置这边写的全局前置脚本，但是在单个case执行时候，引用不到这个全局前置

**Comment by fit2-zhao** [comment]
<img width="914" alt="image" src="https://github.com/user-attachments/assets/a07b03a2-a6c3-455f-be48-8bf5c053c690" />

图中所示是适用场景步骤的，如果单个 API Case 使用就放到 "单个请求步骤前执行" 这个里面。

**Comment by hujirong521317** [comment]
那这边case的使用场景是什么，平时想多个case执行，岂不是每个case都要去写前置，好麻烦

这边的应用场景是，将case引用到场景去跑，这样来使用是吗

**Comment by fit2-zhao** [comment]
流程建议使用场景。
