### ISSUE TITLE
[BUG]创建缺陷，编辑缺陷内容时粘贴图片，图片变模糊，保存之后打开查看也很模糊

### ISSUE THREAD

**Issue by lyons-hz** [metersphere/metersphere#34620]
### 联系方式

jianmin.pu@fit2cloud.com

### MeterSphere 版本

v3.4.0

### 使用外置数据库

否

### 问题描述

见issue#34077，创建缺陷，编辑缺陷内容时粘贴图片，图片变模糊，保存之后打开查看也很模糊

### 重现步骤

1.创建缺陷，编辑缺陷内容，使用ctrl+V在内容中粘贴图片，图片变模糊。（**注意不是上传**图片）
2.点击打开链接按钮，展示的图片是模糊的
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/805af44e-3067-4321-9189-2716608dc71b" />

### 期待的正确结果

编辑缺陷内容时粘贴图片以及后续打开图片，能保持图片原来的清晰度

**Comment by 13290445582** [comment]
你好，对比了下截屏下来的图片和ctrl+v粘贴的图片，没什么清晰度上面的变化啊。
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/4d3696ba-1900-44d5-b7f2-2aa8ed26b4bc" />

**Comment by lyons-hz** [comment]
可以试试Excel表格，将图片放大，效果会比较明显，截图文件放大依旧很清晰
![image](https://github.com/user-attachments/assets/7b174fd8-ce9a-41c2-bbde-5755ec213675)

**Comment by 13290445582** [comment]
你好，把你这个原截图发过来吧，后面看看能不能优化下。

**Comment by lyons-hz** [comment]
<img width="1090" alt="WechatIMG479" src="https://github.com/user-attachments/assets/9f0412a3-3be4-4929-aa8a-11b2b7b964bb" />

**Comment by 13290445582** [comment]
好的，感谢，我先提交看看后续如何优化下。

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。
