### ISSUE TITLE
[QUESTION]集成第三方平台，当不使用第三方模板同步缺陷的时候，我设置的自定义字段如何同步过来

### ISSUE THREAD

**Issue by sxykeeptrying** [metersphere/metersphere#34634]
### 请描述您的问题

集成第三方平台，当不使用第三方模板同步缺陷的时候，我设置的自定义字段如何同步过来，需要填写哪些字段才能同步，请求帮助，感谢各位大哥！！！！！！

**Comment by liuruibin** [comment]
使用的是什么版本？

**Comment by sxykeeptrying** [comment]
我是使用的官网提供的3.3.0的版本，集成的redmine，新增和编辑缺陷一切正常，但是同步的时候redmine的一些自定义字段同步不过来，我是使用反射设置的自定义字段

**Comment by song-cc-rock** [comment]
需要在插件同步逻辑实现时设置该属性, 主工程才能获取值入库.
![image](https://github.com/user-attachments/assets/1f028e20-e834-4e07-8650-971913ecfc35)

> 参考插件代码: [禅道插件同步解析自定义字段=>MS自定义字段属性](https://github.com/metersphere/metersphere-platform-plugin/blob/ce6d53f96bbe059a0ed37e3a6ec8350015b92719/metersphere-zentao-plugin/src/main/java/io/metersphere/plugin/zentao/impl/ZentaoPlatform.java#L799)

**Comment by sxykeeptrying** [comment]
![捕获](https://github.com/user-attachments/assets/2edef209-c466-4a05-b30a-23ec451b80ce)
![捕获1](https://github.com/user-attachments/assets/7f2316c3-5042-4b11-b357-db7d11eb4144)
我在同步的时候已经设置了这个字段，但是还是同步不过来，这是我的代码和我的自定义字段

**Comment by sxykeeptrying** [comment]
这是我的部分代码

**Comment by sxykeeptrying** [comment]
![Uploading PixPin_2024-12-13_11-14-44.png…]()

**Comment by sxykeeptrying** [comment]
![PixPin_2024-12-13_11-14-44](https://github.com/user-attachments/assets/ffbd2136-1a23-48d5-8af8-e639e8fdc55b)
这是我的部分代码

**Comment by song-cc-rock** [comment]
使用的MS模板中需要配置API, 并且与PlatformCustomFieldItemDTO的id属性一致, 才能将插件中处理的自定义字段映射到MS中.
默认只会同步配置API的自定义字段, 下面是处理自定义字段入库的代码
![image](https://github.com/user-attachments/assets/d18e0826-fd7f-4459-bc3d-9a6fdd6f080e)
![image](https://github.com/user-attachments/assets/847ff81b-73fe-49d9-8453-c0f04c5f2adb)


模板配置自定义字段参考(第三方属性ID一致):  
![image](https://github.com/user-attachments/assets/f69ccace-1fcf-4193-b81f-131933ced9a2)

**Comment by sxykeeptrying** [comment]
请问只有这一种方式可以实现嘛 ,因为我现在用的是系统默认的模板，而且我的新增字段都是通过反射来增加的，不是通过这个界面的新增字段来添加的，那么我应该如何同步呢，我这种情况有没有解决方法呢
![PixPin_2024-12-13_12-29-01](https://github.com/user-attachments/assets/74bf1364-1c4c-4b89-a4ff-dae70df13a0a)

**Comment by song-cc-rock** [comment]
缺陷是要绑定模板的, 页面通过模板来展示具体缺陷, 上图应该是因为没有开启项目模板, 所以在项目下默认模板配置不了字段, 去组织模板里看看应该可以配置.

**Comment by song-cc-rock** [comment]
通过模板来配置API或者实现一下插件平台的这两个方法来自动生成平台默认模板(反射获取的字段写在插件第二个方法里即可) 该方式不需要配置API
[平台是否支持默认模板](https://github.com/metersphere/metersphere-platform-plugin/blob/ce6d53f96bbe059a0ed37e3a6ec8350015b92719/metersphere-zentao-plugin/src/main/java/io/metersphere/plugin/zentao/impl/ZentaoPlatform.java#L185)
[获取平台默认模板自定义字段](https://github.com/metersphere/metersphere-platform-plugin/blob/ce6d53f96bbe059a0ed37e3a6ec8350015b92719/metersphere-zentao-plugin/src/main/java/io/metersphere/plugin/zentao/impl/ZentaoPlatform.java#L196)

实现后启用自动生成的三方默认模板来同步缺陷
![image](https://github.com/user-attachments/assets/b2551994-3c1a-4f43-97d9-1649283f18ad)

**Comment by song-cc-rock** [comment]
通过反射获取的新增字段不要写死在新增逻辑里, 不太好兼容同步的逻辑. 同步只会处理开启模板中可与第三方正常对接的字段, 并最终用该模板展示缺陷.

**Comment by sxykeeptrying** [comment]
我本来是想要实现自己的模板的，但是在测试计划里面，没有办法像默认模板一样生成自动生成这些东西
![PixPin_2024-12-13_13-49-55](https://github.com/user-attachments/assets/76fc4f45-b0e9-45fe-a7ce-f2b1a70ac4b3)
![PixPin_2024-12-13_13-50-23](https://github.com/user-attachments/assets/b9ad5e56-0273-4956-ba91-6733466849a4)
请问如果使用我自己设计的模板的话有方法自动生成这些东西嘛

**Comment by song-cc-rock** [comment]
可以的, 插件返回所有模板字段属性有个默认值你看看
![image](https://github.com/user-attachments/assets/78cbbb52-8d70-46bc-ba53-23e8a4d7e015)

**Comment by song-cc-rock** [comment]
可以的, 插件返回所有模板字段属性有个默认值你看看, 可根据需要设置上. 
![image](https://private-user-images.githubusercontent.com/40567414/395446111-78cbbb52-8d70-46bc-ba53-23e8a4d7e015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjk2NTUsIm5iZiI6MTczNDA2OTM1NSwicGF0aCI6Ii80MDU2NzQxNC8zOTU0NDYxMTEtNzhjYmJiNTItOGQ3MC00NmJjLWJhNTMtMjNlOGE0ZDdlMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA1NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzcwNDIwNTQyNTIyN2RlNDFmOWNlNmE2MmFkZGMwYTVkNmFkNDc5NzVlMWVhMTc5ZGM0MGRmNjAxNDY5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4e1_ES6TIwiQoUiQ3YagUr8bp_cf2fe8baKm-z11LMY)

![image](https://github.com/user-attachments/assets/85ce3a5d-1c9b-49ae-9202-7e4e9d848c3f)

**Comment by sxykeeptrying** [comment]
我知道有这个默认值，我也明白您的意思，我的意思是我新增缺陷的时候怎么可以像这种把这个详情里的内容默认到新增缺陷里面
![PixPin_2024-12-13_13-59-19](https://github.com/user-attachments/assets/0ae9c65e-d3dc-4f43-835c-4f7e420ec1f4)
![PixPin_2024-12-13_13-59-39](https://github.com/user-attachments/assets/f457d6e5-7e56-43a3-b6f3-b31d6ff204c2)

**Comment by sxykeeptrying** [comment]
如果使用自己创建的模板的话好像做不到这种效果

**Comment by song-cc-rock** [comment]
我明白你的意思啦, 这个是前端从用例步骤带过去的, 如果是平台默认模板的字段对内置的缺陷内容字段做了替换, 好像没支持, 可以提一个issue来支持一下.

**Comment by sxykeeptrying** [comment]
好的感谢，就是因为这个原因所以不太想要配置自己的模板

**Comment by song-cc-rock** [comment]
> 好的感谢，就是因为这个原因所以不太想要配置自己的模板

目前看, 只能通过系统模板配置字段API来满足你了.

**Comment by sxykeeptrying** [comment]
您的这个意思是创建一个新的模板是吗，不使用那个默认模板是吧，然后创建新的字段，那我的反射里面那个是不是就不用了

**Comment by song-cc-rock** [comment]
不是, 不用区分哪个模板, 只要是MS的模板对接第三方配置API都可以, 不太明白你的反射字段怎么设置到模板里去的, 如果不通过页面手动配置. 代码写死的嘛?

**Comment by sxykeeptrying** [comment]
就是通过这个方法，然后我的代码里会查Redmine里面的列表来获取
![PixPin_2024-12-13_14-17-50](https://github.com/user-attachments/assets/1c6f3825-912d-49bf-9a37-0181a6a76bdb)
![PixPin_2024-12-13_14-18-18](https://github.com/user-attachments/assets/cfab54d0-44db-49ed-b821-e12b59a066aa)
![PixPin_2024-12-13_14-19-01](https://github.com/user-attachments/assets/2ee617f3-6dab-49c7-93ee-115ea8824b9d)

**Comment by song-cc-rock** [comment]
你把你反射的字段, 在页面上配置一下然后把API对应与也能满足新增和编辑和同步. 这种方式就是选项值你得配置死, 不能通过optionMethod来反射动态获取,
![image](https://github.com/user-attachments/assets/849bdf2f-3df2-476b-b65a-748f552a4244)

**Comment by sxykeeptrying** [comment]
那如果单纯是反射的话，反射里面的id表示的是什么呢，在数据库里会有字段嘛

**Comment by song-cc-rock** [comment]
> 那如果单纯是反射的话，反射里面的id表示的是什么呢，在数据库里会有字段嘛

你这种反射不会入库, 模板配置的才会入库.

**Comment by song-cc-rock** [comment]
你这些是前端写死的吧
![image](https://github.com/user-attachments/assets/d6fe92b5-217f-4b6a-a833-b2a4b5bf8f05)

**Comment by sxykeeptrying** [comment]
好的了解了，非常感谢您，那我试一下配置API的方式，对，我是写死在JSON里面的

**Comment by sxykeeptrying** [comment]
您好，这里我还有一个问题，就是我通过反射设置的自定义字段，像您说的如果没有入库的话，那我编辑这个缺陷的时候应该是显示不出来的自定义字段的呀，我编辑的时候显示的和我输入的一样的，只是同步的时候没有同步过来，这是怎么回事呢 @song-cc-rock

**Comment by song-cc-rock** [comment]
> 您好，这里我还有一个问题，就是我通过反射设置的自定义字段，像您说的如果没有入库的话，那我编辑这个缺陷的时候应该是显示不出来的自定义字段的呀，我编辑的时候显示的和我输入的一样的，只是同步的时候没有同步过来，这是怎么回事呢 @song-cc-rock

新增保存后你的缺陷自定义字段值入库了, 但是字段没入库, 因为你前端写死了, 而不是绑定在模板上, 所以新增编辑都能获取到写死的字段, 再加上值入库了, 所编辑时候能正常复显. 同步只处理模板字段, 这个需要字段配置入库.

> 参考表: bug_custom_field

**Comment by sxykeeptrying** [comment]
非常感谢，明白了！！！

**Comment by bangbangDong** [comment]
您好，您是如何实现metersphere集成redmine的，能上传一下您的插件代码参考一下吗？

**Comment by sxykeeptrying** [comment]
不好意思哈，公司保密的，没有办法上传

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月18日 18:35 |
| 收件人 | metersphere/metersphere ***@***.***> |
| 抄送人 | HaHaHa ***@***.***>,
State ***@***.***> |
| 主题 | Re: [metersphere/metersphere] [QUESTION]集成第三方平台，当不使用第三方模板同步缺陷的时候，我设置的自定义字段如何同步过来 (Issue #34634) |

您好，您是如何实现metersphere集成redmine的，能上传一下您的插件代码参考一下吗？
