### ISSUE TITLE
[FEATURE]集成第三方平台可以和默认模板相同的默认值

### ISSUE THREAD

**Issue by sxykeeptrying** [metersphere/metersphere#34645]
### MeterSphere 版本

V3

### 请描述您的需求或者改进建议

集成第三方平台可以和默认模板相同的默认值，当使用第三方平台的时候，执行测试计划可以生成和默认模板一样的默认值，方便创建缺陷

**Comment by liuruibin** [comment]
感谢使用，没有计划改这里
