### ISSUE TITLE
[BUG]测试计划执行时，有时候步骤会执行多次

### ISSUE THREAD

**Issue by frc-71** [metersphere/metersphere#34649]
### MeterSphere 版本

v3.5

### 使用外置数据库

是

### 问题描述

测试计划执行时，有时候步骤会执行多次

### 重现步骤

具体重现步骤没仔细看，但是问题代码我这边已经定位到了

```
存在问题的方法：io.metersphere.api.service.scenario.ApiScenarioService#getAllStepsByScenarioIds

private List<ApiScenarioStepDTO> getStepDTOByScenarioIds(List<String> scenarioIds) {
    if (CollectionUtils.isEmpty(scenarioIds)) {
        return Collections.emptyList();
    }
    return extApiScenarioStepMapper.getStepDTOByScenarioIds(scenarioIds);
}

/**
 * 递归获取所有的场景步骤
 */
public List<ApiScenarioStepDTO> getAllStepsByScenarioIds(List<String> scenarioIds) {
    List<ApiScenarioStepDTO> steps = getStepDTOByScenarioIds(scenarioIds); 
    if (CollectionUtils.isEmpty(steps)) {
        return steps;
    }

    // 将 config 转换成对象
    steps.forEach(step -> {
        if (step.getConfig() != null && StringUtils.isNotBlank(step.getConfig().toString())) {
            if (step.getConfig() instanceof String configVal) {
                step.setConfig(JSON.parseObject(configVal));
            }
        }
    });

    // 获取步骤中引用的场景ID
    List<String> childScenarioIds = steps.stream()
            .filter(this::isRefOrPartialScenario)
            .map(ApiScenarioStepDTO::getResourceId)
            .collect(Collectors.toList());

    // 嵌套获取引用的场景步骤
    steps.addAll(getAllStepsByScenarioIds(childScenarioIds));
    return steps;
}
```
```List<ApiScenarioStepDTO> steps = getStepDTOByScenarioIds(scenarioIds); ```这行，```steps```是通过```extApiScenarioStepMapper```查出来的，然后```steps.addAll(getAllStepsByScenarioIds(childScenarioIds));```在这行，又会对这个引用对象进行修改（后续逻辑其实还有其他修改）。

测试计划执行时，会开启事务，在一个事务中这段代码会执行两次。而同一个事务中是存在缓存的，第二次通过```extApiScenarioStepMapper```查询```steps```的时候，实际上是从缓存中取的，但是缓存的数据其实在第一次查询之后就已经被篡改了，导致出现多余数据。

建议将```steps```拷贝一份再进行修改
```
/**
 * 递归获取所有的场景步骤
 */
public List<ApiScenarioStepDTO> getAllStepsByScenarioIds(List<String> scenarioIds) {
    List<ApiScenarioStepDTO> steps = getStepDTOByScenarioIds(scenarioIds);
    if (CollectionUtils.isEmpty(steps)) {
        return steps;
    }

    List<ApiScenarioStepDTO> result = Lists.newArrayList();
    steps.forEach(step -> result.add(BeanUtils.copyBean(new ApiScenarioStepDTO(), step)));

    // 将 config 转换成对象
    result.forEach(step -> {
        if (step.getConfig() != null && StringUtils.isNotBlank(step.getConfig().toString())) {
            if (step.getConfig() instanceof String configVal) {
                step.setConfig(JSON.parseObject(configVal));
            }
        }
    });

    // 获取步骤中引用的场景ID
    List<String> childScenarioIds = result.stream()
            .filter(this::isRefOrPartialScenario)
            .map(ApiScenarioStepDTO::getResourceId)
            .collect(Collectors.toList());

    // 嵌套获取引用的场景步骤
    result.addAll(getAllStepsByScenarioIds(childScenarioIds));
    return result;
}
```

**Comment by fit2-zhao** [comment]
@frc-71  感谢建议，我们会确认下这块逻辑。

**Comment by AgAngle** [comment]
你好，感觉反馈，我确认了下代码逻辑，getAllStepsByScenarioIds 这个是根据场景 ID 获取对应的步骤，并且递归获取当前步骤引用的场景的步骤，它调用的次数，取决于引用场景的深度，相同的场景ID并不会调用多次；另外你如果你是打断点调试，task-runner 执行机会响应超时，然后进行重试，所以可能会调用多次，当然如果不是打断点调试也

**Comment by AgAngle** [comment]
@frc-71 你好，感谢反馈，我确认了下代码逻辑，getAllStepsByScenarioIds 这个是根据场景 ID 获取对应的步骤，并且递归获取当前步骤引用的场景的步骤，它调用的次数，取决于引用场景的深度，相同的场景ID并不会调用多次；
另外你如果你是断点调试，task-runner 执行机会响应超时，然后进行 http 的请求重试，所以可能会调用多次，当然如果不是断点调试，当服务负载较大的时候，也有可能响应超时，调用多次，这个问题在 3.4 的版本出现过，3.5 已经修复过了，利用数据库 ID 的主键唯一来实现接口的幂等，代码如下：
![image](https://github.com/user-attachments/assets/3ed19e8a-a0ce-4f45-8997-063cd8956a6a)
最后还麻烦确认下 3.5 版本还存在这个问题吗，能否尝试下总结下复现的步骤，十分感谢！

**Comment by frc-71** [comment]
抱歉，前面可能说的不是很清楚。
可以看一下这个方法```io.metersphere.api.controller.ApiExecuteResourceController#getScript```，执行的时候task-runner会回调到这里。

然后后面会执行到这个地方：```io.metersphere.plan.service.PlanRunApiScenarioExecuteCallbackService#getRunScript```，这个Service是加了@Transactiona注解的

![事务](https://github.com/user-attachments/assets/68dbeb61-5fd4-4f29-a094-4f8c050ccb70)

这里面我标出来的这两行代码都会走到前面说的那段代码逻辑，最终导致```GetRunScriptResult result = planRunTestPlanApiScenarioService.getRunScript(request);```这行代码的结果有时候会有问题。

如果还是有疑问的话我抽时间看一下复现步骤，这部分逻辑比较复杂，我不是很熟悉，搞明白重新步骤需要一些时间。

**Comment by AgAngle** [comment]
@frc-71 你好，你反馈的问题确实存在，同一个事务中确实有 MyBatis 的缓存，你反馈的这两处调用，不仅导致了数据有误，也影响了性能，这个问题将在 3.6  版本修复，感谢你提供的有效信息！

**Comment by AgAngle** [comment]
@frc-71 你好，虽然这是个bug，会进行修复；但目前看来，这个bug应该不会导致重复执行，因为在外层会对步骤去重，请问步骤是否确实重复执行了呢？另外报告是否重复显示了步骤？
![1d87f6dfc566ab7be34bb106237e7ad](https://github.com/user-attachments/assets/9ebfc8d3-2afa-4c79-ab86-e7568ec8554e)
![1734430689667](https://github.com/user-attachments/assets/0a206314-83aa-47d9-b053-4b9975f578b8)

**Comment by frc-71** [comment]
确实遇到了重复执行的case，报告里面也显示了重复的步骤。我这边是大多数场景是正常的，但是有一个的场景下面的步骤每次都会执行2遍。之前看了挺久没找出来规律。
我调试的时候，你截图的这个地方，两次计算出来的allSteps长度是不一样的，怀疑可能跟ApiScenarioStepDTO的children字段有关系，第二次走到这里的时候，children是有值的，但是数据库里面新查出来的是没值的，不清楚会不会是因为这个导致distinct去重失败

**Comment by AgAngle** [comment]
我也调试了下，第二次走到这里的时候，children 是有值，但是数据库里面新查的也有值，目前复现不出来你的场景，可能跟你这个场景的结构也有关系，总之下个版本会避免两次调用，以及执行该 sql 时清理一级缓存来解决你的问题，感谢你的反馈！

**Comment by frc-71** [comment]
这段逻辑似乎还有其他问题。
按照前面的改法修改完之后，我这边似乎所有任务的场景用例，执行结果均变成了未执行。
我这边排查发现api_scenario_report_step表中的step_id字段与api_scenario_report_detail字段不一致导致的，但是不一致原因还没有查到。

辛苦确认下你们那边有没有这个问题？

**Comment by AgAngle** [comment]
这个改法确实会有问题，需要保证生成报告和执行的场景详情是相同，每个步骤执行时都会生成一个唯一的ID（不用步骤本身的ID是因为可能会引用多次导致ID重复），报告的步骤需要跟这个唯一ID匹配，才能更新报告的结果；
可以参考这两个 commit 进行修复：
https://github.com/metersphere/metersphere/commit/80be2bb3437150c076d776490673588f2669c17e
https://github.com/metersphere/metersphere/commit/bff7c3ad7854999ac73187012a1a96ff4e1f54de

**Comment by frc-71** [comment]
已经可以了，感谢~

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。
