### ISSUE TITLE
[QUESTION]关联DataEase，“功能测试用例”的“最后执行时间”在哪个表里，找不到这个属性

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34657]
### 请描述您的问题

[QUESTION]关联DataEase，“功能测试用例”的“最后执行时间”在哪个表里，找不到这个属性

**Comment by fit2-zhao** [comment]
加到计划中执行后：test_plan_functional_case 表的 last_exec_time  属性就是。

**Comment by henbell2** [comment]
谢谢，收到！

**Comment by henbell2** [comment]
这个时间是错的，不是“最后执行时间”（即：最后修改执行结果的时间），好像是把访问时间戳写进来了，以至于一天能有几千条
![image](https://github.com/user-attachments/assets/c950503a-eca3-44ce-ba8c-b5d843408540)
