### ISSUE TITLE
[BUG]  在接口定义里面，当把接口响应参数定义有多个对象并且有object 值，在导出swagger 格式的时候，导出不了

### ISSUE THREAD

**Issue by hao65103940** [metersphere/metersphere#34654]
### MeterSphere 版本

V2.10.21

### 使用外置数据库

否

### 问题描述

在接口定义里面，当把接口响应参数定义有多个对象并且有object 值，在导出swagger 格式的时候，导出不了

![image](https://github.com/user-attachments/assets/0b8ab343-1144-4aeb-8a52-d864aea39079)
![image](https://github.com/user-attachments/assets/77c6011e-b707-4996-9e71-378e85fa50d4)
![image](https://github.com/user-attachments/assets/f8f14b61-f769-4026-90e5-88c718c8a2cf)

### 重现步骤

随便定义一个接口定义，然后设置响应参数如下图：
![image](https://github.com/user-attachments/assets/b9c6e108-6e61-4172-8c42-be6d388df046)

### 期待的正确结果

能够正常导出对应的值。即使为空对象，也能够导出才对

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
