### ISSUE TITLE
[BUG] 在定义界面，无法保存两个URL相同，方法相同，但是请求体不同的接口

### ISSUE THREAD

**Issue by yinzhouzhou** [metersphere/metersphere#34660]
### 联系方式

yinzhou_aha@163.com

### MeterSphere 版本

v3.5.0

### 使用外置数据库

否

### 问题描述

我创建了两个相同的URL，但body不一样，如图。但是保存时报错接口已存在，我理解这种场景在实际使用中很常见。

![image](https://github.com/user-attachments/assets/6b2beb21-79df-40cf-a622-2cd9b3e65724)

![image](https://github.com/user-attachments/assets/72e4c4ed-98f1-4bed-88e9-5b17171b42f4)

### 重现步骤

在接口-定义界面，创建两个相同的URL，但body不一样。无法保存第二个接口，显示**接口已存在**。

### 期待的正确结果

可以保存两个相同的URL，但body不一样的接口。

**Comment by liuruibin** [comment]
你这是一个接口多个用例吧
