### ISSUE TITLE
[BUG]升级到3.5，接口测试选择本地执行时 报错信息 200001

### ISSUE THREAD

**Issue by EwanAntel** [metersphere/metersphere#34663]
### 联系方式

交流群66 昵称 胖咕咕，邮箱109998498@qq.com

### MeterSphere 版本

v3.5.0-c3ad9f70

### 使用外置数据库

否

### 问题描述

新安装的3.5，使用1panel，安装。Windows11 安装的Docker，并且下载的3.5对应的task-runner。进入MS后，接口测试的本地执行报错200001，以前3.3时同样步骤是没问题的

### 重现步骤

![1](https://github.com/user-attachments/assets/39bfcd61-ab5b-4934-a361-d7810df7121e)
![2](https://github.com/user-attachments/assets/c6a747f4-a0d8-4313-8056-ad9f4ae2ad03)
![3](https://github.com/user-attachments/assets/63156f6b-bd52-4039-afcd-a676ff741774)
![4](https://github.com/user-attachments/assets/0d00f311-1faa-4231-a81a-1ef91817c400)

**Comment by AgAngle** [comment]
你好，感谢反馈，这个响应是 task-runner 调用 ms 获取测试资源时失败，无法访问到 ms ，请检查下容器是否能访问到当前配置的 ms 地址；
ms 地址配置的优先级为：资源池配置的工作节点 URL 优先，系统参数中的当前站点 URL 其次
![1734334884977](https://github.com/user-attachments/assets/e6118ac5-5179-4ea1-9c60-75812e7b8ede)
![1734334915729](https://github.com/user-attachments/assets/e6bb3701-fd49-488e-8b3c-a8b0ffe96f54)
如果还有问题，可以重新打开 issue，十分感谢！
