### ISSUE TITLE
[QUESTION]批量执行接口的场景用例时跑两条后续就不执行了

### ISSUE THREAD

**Issue by zhou-weijie** [metersphere/metersphere#34665]
### 请描述您的问题

使用社区版的v3.3.0-c48b9fb2，批量执行场景测试用例时用例未执行，查看日志显示：
![image](https://github.com/user-attachments/assets/f4b3459c-7a7d-40a6-8280-4b0baf71c9e4)
想要咨询下是什么原因导致的此问题，又该如何避免后续出现？

**Comment by liuruibin** [comment]
<img width="913" alt="image" src="https://github.com/user-attachments/assets/6cf1cd0e-75f4-411a-9424-4dbf6ba3231b" />
全都是INFO正常日志，你所说的问题具体是指什么呢

**Comment by zhou-weijie** [comment]
![image](https://github.com/user-attachments/assets/e727a58d-0e2f-4687-a57b-96d520a7ee06)
问题就是这个用例不执行了，也没任何报错信息

**Comment by liuruibin** [comment]
部署方式是allinone吗

**Comment by zhou-weijie** [comment]
下载安装包离线安装的

**Comment by liuruibin** [comment]
task-runner是不是OOM重启了

调整/opt/metersphere/.env
```
MS_RUNNER_MEM_LIMIT=2g
```

改完执行 
```
msctl reload
```

**Comment by zhou-weijie** [comment]
目前看起来是没问题了，多谢~
