### ISSUE TITLE
[BUG]新建用户授权项目成员角色不生效

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#3467]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**
简要描述您碰到的问题
创建项目成员不生效
**Bug 重现步骤**
1.  新建用户，给这个用户赋予项目成员角色
2. 点击测试跟踪，编辑测试用例，选择责任人没有刚才新建的用户，进行用例评审也是无法指定评审人
3. 登录新建的用户，点击测试跟踪，点击项目结果没有项目
4. 点击接口用例，也没有项目，但是可以看到项目所有接口

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/35896106/120483804-08f2f780-c3e5-11eb-85c7-62626c86dde0.png)

![image](https://user-images.githubusercontent.com/35896106/120483712-f4166400-c3e4-11eb-8d76-00f7d1a98b60.png)

![image](https://user-images.githubusercontent.com/35896106/120483912-232cd580-c3e5-11eb-9728-842688c4df02.png)
![image](https://user-images.githubusercontent.com/35896106/120484475-b108c080-c3e5-11eb-8a59-9e873b2dc4ff.png)

**Comment by xulinde** [comment]
已知问题，1.10.1修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
