### ISSUE TITLE
[BUG]数据库里最后执行时间貌似是错的，一天几千条，两天能有上万条（几秒钟就一条记录，貌似把访问时间写进来了？）

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34678]
### MeterSphere 版本

v3.5.0-c3ad9f70

### 使用外置数据库

否

### 问题描述

详见：https://github.com/metersphere/metersphere/issues/34657
字段：
![image](https://github.com/user-attachments/assets/bb2217ab-ff27-4f55-be53-0db8032e8089)

### 重现步骤

详见：https://github.com/metersphere/metersphere/issues/34657
字段：
![image](https://github.com/user-attachments/assets/bb2217ab-ff27-4f55-be53-0db8032e8089)

**Comment by liuruibin** [comment]
你这个功能用例表，是人为控制的

**Comment by henbell2** [comment]
没太懂，访问用例是人为，保存数据库是系统。没有执行几千上万条用例时，按照执行时间筛选的话，会出现几千上万条。现在问题是：怀疑写入数据库的“最后执行时间”，不是真正的“执行”时间，而是把其它什么操作的时间戳，错误的写道“最后执行时间”这个字段上了。

**Comment by liuruibin** [comment]
功能用例就是人工参与的，人工输入步骤和结果。人工标记成功和失败

**Comment by fit2-zhao** [comment]
这是关联到测试计划中的执行记录，测试计划每次执行都会产生执行信息；你取最后执行时间只需要进行分组取最后一条记录即可。
