### ISSUE TITLE
[BUG]在接口自动化页面，修改名称，会有出现报错的可能

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#3468]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
在接口自动化页面，修改名称，会有出现报错的可能

**Bug 重现步骤**
1.  可能存在不同的类里面和其他类型里存在相同名称
2. 修改出现报错
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/80370956/120570370-8f8df000-c44a-11eb-8d46-45a6204ed512.png)

**Comment by zyyfit** [comment]
您好，目前没有复现，我们跟踪关注一下这个问题
