### ISSUE TITLE
[BUG]dataease使用数据库，“测试计划状态”无法关联筛选，且手输无效

### ISSUE THREAD

**Issue by henbell2** [metersphere/metersphere#34683]
### MeterSphere 版本

v3.5.0-c3ad9f70

### 使用外置数据库

否

### 问题描述

![image](https://github.com/user-attachments/assets/00395360-f9ea-4b03-a253-7acebe1f69ae)

### 重现步骤

![image](https://github.com/user-attachments/assets/27d99d19-d86c-41c8-a341-5755cc4b1798)

**Comment by liuruibin** [comment]
这字段保存在JSON里，关联在自定义字段里，你自己找表找关联自己写SQL
