### ISSUE TITLE
[BUG] 环境变量中的部分类型参数不生效

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34692]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述
![image](https://github.com/user-attachments/assets/35556e69-6a83-41a5-b3aa-b72d3f5f5bcb)

在环境变量中设置随机数计数器
![image](https://github.com/user-attachments/assets/a954df2b-c054-421a-82ed-649d18e8ccdd)
执行时获取不到值

### 重现步骤

如上所述。
我分析了下，应该问题出在io.metersphere.api.dto.definition.request.MsScenario#toHashTree
![image](https://github.com/user-attachments/assets/735409c4-80f8-4d8d-9246-d9cd04a37bd3)

### 期待的正确结果

如上

**Comment by fit2-zhao** [comment]
是的，目前这块的逻辑设计是这样，如果有其他方面问题，欢迎提出来；

同名变量优先级：临时参数 > 场景参数 > 环境参数；注: 避免使用同名变量，同名变量时场景级 CSV 优先级最高。

这个非问题暂时关闭。

**Comment by ijwstl** [comment]
> 是的，目前这块的逻辑设计是这样，如果有其他方面问题，欢迎提出来；
> 
> 同名变量优先级：临时参数 > 场景参数 > 环境参数；注: 避免使用同名变量，同名变量时场景级 CSV 优先级最高。
> 
> 这个非问题暂时关闭。

请问环境变量里的随机数和计数器这些参数主要用于哪些场景呢？这里不添加到参数里的设计原因是否是因为如果添加了会造成一些bug呢？

**Comment by fit2-zhao** [comment]
像计数器，CSV 变量 和 随机数控制器 等控制器类变量通常都是作用于某个循环之下，或场景级别公共变量。
