### ISSUE TITLE
[BUG]接口定义页面创建接口会报错，但点击2次可以成功

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#3469]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
接口定义页面创建接口会报错，但点击2次可以成功

**Bug 重现步骤**
1.  进入创建接口页面
2. 输入url、 的 MeterSphere 版本是？

**Bug 描述**
接口定义页面创建接口会报错，但点击2次可以成功

**Bug 重现步骤**
1.  进入创建接口页面
2. 输入url、 名称、选择模块
3. 点击测试或保存
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/80370956/120570613-19d65400-c44b-11eb-86e4-f1bd75c80db6.png)

**Comment by zyyfit** [comment]
您好，能稳定复现吗？这边没有复现出来呢
