### ISSUE TITLE
[FEATURE]集成缺陷管理平台密码可见打开，保存后建议不显示

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#347]
![1599198502995](https://user-images.githubusercontent.com/29306248/92204166-76551480-eeb5-11ea-9d73-ced41179ce08.jpg)
**请描述您的需求或者改进建议.**
服务集成时如果点了密码显示，在点保存后密码依旧是显示，这样不够安全，希望在点击保存后默认是***

**请描述你建议的实现方案**
服务集成时如果点了密码显示，在点保存后密码显示*****

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，计划1.8版本中修复该问题，请持续关注
