### ISSUE TITLE
[BUG]MS集成禅道17.8，缺陷反向（禅道-MS）同步失败

### ISSUE THREAD

**Issue by michellefan123** [metersphere/metersphere#34704]
### 联系方式

M，403637897@qq.com

### MeterSphere 版本

3.4.0

### 使用外置数据库

否

### 问题描述

1.MS集成禅道，禅道版本17.8，MS创建缺陷同步至禅道成功，禅道修改缺陷状态或者创建缺陷同步至MS失败；
2.MS集成禅道，项目内缺陷管理配置全量同步时，禅道并未缺陷同步至MS
3.MS使用默认模板或者禅道默认模板，获取禅道的指派人不全，仅显示部分

### 重现步骤

见问题描述

### 期待的正确结果

MS提交缺陷时，指派人可获取禅道所有指派人
禅道针对缺陷修改时可反向同步MS

**Comment by song-cc-rock** [comment]
同步禅道=>MS时后台有错误日志吗,  又或者是产品Key下不存在存在缺陷.
指派人不全的问题, 已在这次commit修复: https://github.com/metersphere/metersphere-platform-plugin/commit/953518d3606959177e7cde303313de1e23244d9f, 可以下载最新的禅道插件替换.

**Comment by michellefan123** [comment]
更新3.5.0插件，指派人不全问题已解决，MS3.4.0
反向同步问题仍然存在
![IMG_20241220_171320](https://github.com/user-attachments/assets/15a09365-eee3-415c-bd35-0103b6a49559)
![IMG_20241220_171349](https://github.com/user-attachments/assets/ce0ea8ce-58ed-4ed9-80f7-4717a266444d)
![IMG_20241220_171409](https://github.com/user-attachments/assets/301a8e29-6b61-4b51-8987-3073f66516a2)
![IMG_20241220_171457](https://github.com/user-attachments/assets/ab395f49-f2ae-4736-b12b-a12ccdedbe3a)

**Comment by michellefan123** [comment]
已在禅道建立缺陷，在MS上未查询到同步的缺陷

**Comment by michellefan123** [comment]
刚上面项目缺陷同步设置的是增量，改成全量后又在禅道新增缺陷后错误日志新增内容也传上来，麻烦看一下是什么问题
![IMG_20241220_172714](https://github.com/user-attachments/assets/93d7bbc2-f9b2-46ed-a4e5-110624dd33d5)
![IMG_20241220_172733](https://github.com/user-attachments/assets/65a97640-05f5-46d8-a164-8fd7b76900ac)
![IMG_20241220_172758](https://github.com/user-attachments/assets/4f908523-76c2-4ebf-89fb-4471a7270783)

**Comment by song-cc-rock** [comment]
看日志还是进入的增量同步的方法, 看看项目是怎么配置的

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～

**Comment by michellefan123** [comment]
禅道18.10版本，项目设置增量同步，禅道更新缺陷状态也是可以同步到MS的
需要确认项目哪些设置呢

**Comment by song-cc-rock** [comment]
> 禅道18.10版本，项目设置增量同步，禅道更新缺陷状态也是可以同步到MS的 需要确认项目哪些设置呢

过了好久, 确认一下, 你的问题是说项目配置都是增量, 17.8版本禅道缺陷修改后无法同步至MS, 18.10版本又是Ok的
是这个问题吧? 还是说其他问题 @michellefan123
