### ISSUE TITLE
[BUG]接口请求URL自动转码导致不成功

### ISSUE THREAD

**Issue by kuanglei1986** [metersphere/metersphere#3470]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版本

**Bug 描述**
简要描述您碰到的问题
新增接口请求，发现请求url自动转码了，无论输入编码前和编码后的url，请求都失败。
本问题已在微信群与陈建新先生确认了，希望能优先解决。
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
是否可以不进行自动转码的操作
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
收到，会在下一个版本中解决
