### ISSUE TITLE
[BUG] 创建python前置脚本，复制调试好的python脚本进行编辑框中，在保存脚本后执行脚本，系统提示 : mismatched input "mport" expecting NEWLINE in <script> at line number 1 at column number 27

### ISSUE THREAD

**Issue by yuanlei520xxy** [metersphere/metersphere#34712]
### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

[BUG] 创建python前置脚本，复制调试好的python脚本进行编辑框中，在保存脚本后执行脚本，系统提示 : mismatched input "mport" expecting NEWLINE in <script> at line number 1 at column number 27
贴上前置脚本：
from random import choice
import random

v_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
          't', 'o', 'v', 'w', 'x', 'y', 'z',
          'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
          'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
    , '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
v_list2 = random.sample(v_list, 8)
email = '@qq.com'
for x in v_list2:
    email = x + email
print(email)

vars.put("email", email)

![1](https://github.com/user-attachments/assets/57c8348d-5285-4e02-8e46-7a7b507515a5)

### 重现步骤

1、新建接口；
2、添加案例；
3、新增前置脚本，添加断言，保存脚本；
4、执行脚本；

### 期待的正确结果

正确执行脚本得到随机邮箱名称

**Comment by liuruibin** [comment]
```
from random import choice
import random

v_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
't', 'o', 'v', 'w', 'x', 'y', 'z',
'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
, '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
v_list2 = random.sample(v_list, 8)
email = '@qq.com'
for x in v_list2:
    email = x + email
print(email)

vars.put("email", email)
```

没有复现

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
