### ISSUE TITLE
[BUG]JsonPath 表达式包含indexOf方法，测试表达式成功，执行请求控制台报错Arguments to function: 'indexOf' are not closed properly.

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#34717]
### 联系方式

李佳鑫

### MeterSphere 版本

v3.5

### 使用外置数据库

否

### 问题描述

sonPath 表达式包含indexOf方法，测试表达式成功，执行请求控制台报错Arguments to function: 'indexOf' are not closed properly.

### 重现步骤

[响应体.txt](https://github.com/user-attachments/files/18191670/default.txt)
表达式：$.rows[?(@.devIp == "10.6.1.15" && @.ruleName.indexOf('DCS控制器') != -1)].port

**Comment by fit2cloud-lijiaxin** [comment]
1.测试表达式成功
![image](https://github.com/user-attachments/assets/886a5323-ff6a-42fc-ab63-d31693db4b23)

2. 执行请求，提取失败，控制台报错
![image](https://github.com/user-attachments/assets/4ae96ab4-569a-4689-a8c0-59dfa4abe5fe)

**Comment by liuruibin** [comment]
我们后台用的jayway作为提取引擎，和页面js预览有些不同，不过你仍然可以用下面的表达式提取出来
```
$.rows[?(@.devIp == "10.6.1.15" && @.ruleName =~ /.*DCS控制器.*/)].port

```
<img width="1868" alt="image" src="https://github.com/user-attachments/assets/c2437771-f7c9-43f6-8490-7073dcb2ee43" />

我们建议你尽量使用通用规则来提取
