### ISSUE TITLE
[FEATURE]接口场景 的 添加步骤 能加个 SQL 脚本吗？我们有些场景需要在过程中加个SQL操作(目前的全局后置SQL操作无法满足我们的需求 )

### ISSUE THREAD

**Issue by LeungJingna** [metersphere/metersphere#34718]
### MeterSphere 版本

v3.5.0-c3ad9f70

### 联系方式

jingnan.liang@xgo.one

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/b4656ce3-252d-4c8c-8eef-60b21d49766c)
接口场景 的 添加步骤 能加个 SQL 脚本吗？我们有些场景需要在过程中加个SQL操作(目前的全局后置SQL操作无法满足我们的需求 )

**Comment by fit2-zhao** [comment]
接口测试已全面支持插件体系。如果需要，可以通过以下方式扩展插件功能：  

1. **下载现有插件**  
   在 https://metersphere.io/docs/v3.x/plugin/ 中查找并安装适合的插件。  

2. **自定义开发插件**  
   如果现有插件不能满足需求，可参考以下文档，自定义开发接口测试插件：  
    插件开发文档：https://metersphere.io/docs/v3.x/dev_manual/api_plugin_dev
