### ISSUE TITLE
[BUG]环境管理，通过搜索环境变量进行编辑保存操作之后，会把之前的内容直接覆盖掉

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [metersphere/metersphere#34721]
### 联系方式

zaopeng.guo@fit2cloud.com

### MeterSphere 版本

3.5

### 使用外置数据库

否

### 问题描述

项目管理-环境管理，通过搜索环境变量，然后进行环境变量的编辑保存操作之后，会只保存搜索出来的变量，之前的内容直接覆盖掉了。

### 重现步骤

1、项目管理-环境管理，当前有三个环境变量：id 、ids、test
![image](https://github.com/user-attachments/assets/a1644c2c-4032-4ea4-a4d7-eaed229a0768)

2、搜索框输入 id ,进行搜索。
![image](https://github.com/user-attachments/assets/b7d326fb-ebbf-4cdb-ad2f-d1dbdf15cffe)

3、编辑 id 这个变量的默认值保存，清空搜索框，发现 test 这个变量没了。
![image](https://github.com/user-attachments/assets/d0454181-429a-42b5-930e-c98afa38e8f8)

**Comment by 13290445582** [comment]
感谢反馈，下个版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。
