### ISSUE TITLE
[BUG] 重新导入场景，全局前置脚本不执行

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34733]
### MeterSphere 版本

v2.10.20-lts

### 使用外置数据库

否

### 问题描述

导出导入场景用例后，发现全局前置脚本失效，必须重新保存该用例才可以。

### 重现步骤

第一步，准备好两个环境，分别是原生和选择环境
其内容如下，主要区别为打印的内容分别为数字1和数字2
原生环境：
![image](https://github.com/user-attachments/assets/7c10df52-4dbd-4f96-8786-ebf456dcb147)
![image](https://github.com/user-attachments/assets/ef85ba35-4a10-44bb-ba39-9b027833b2d7)
选择环境：
![image](https://github.com/user-attachments/assets/87b84abc-e432-412e-80cd-6ded2c0ab551)
![image](https://github.com/user-attachments/assets/fcbb9b38-67e2-42ac-9acf-081203fef258)

第二步，准备一个场景用例，调试结果如下，一切正常。
![image](https://github.com/user-attachments/assets/545c41c4-9925-4e42-b5d6-9566331943f7)

第三步，导出这个场景，使用MS格式。

第四步，删除旧场景，并导入刚才这个场景。

第五步，准备一个测试计划，关联导入的场景。

第六步，执行该计划，环境选择另外一个”选择环境“
![image](https://github.com/user-attachments/assets/8131603e-acbe-4c5c-bf56-f6c287f51d27)

第七步，查看执行结果：
![image](https://github.com/user-attachments/assets/11945acb-941b-481e-8efa-87b4b01dcbeb)

发现该用例没有执行全局前置脚本，debug后查看jmx，并没有加入全局前置脚本，至此Bug已复现

第八步，重新保存场景用例

第九步，再次执行计划，恢复正常
![image](https://github.com/user-attachments/assets/672ec0f3-2fde-4220-affd-9595dd9e168d)

**Comment by ijwstl** [comment]
您好，貌似是因为导出时布尔值默认为false导致variableEnable导入时为false导致的，另外请问该字段和mixEnable字段的作用是什么呢，我看在MsScenario组件里应用大量判断
![image](https://github.com/user-attachments/assets/5b460f62-f624-4c49-9bc7-ca57e699d86c)

**Comment by 13290445582** [comment]
感谢反馈，后续版本修复。

**Comment by Somebody-JIAN** [comment]
分析的很对

**Comment by 13290445582** [comment]
您好，v2.10.23版本已修复该问题，请升级。
