### ISSUE TITLE
[BUG]接口分享后的描述在接口定义里面移动目录后不能带出

### ISSUE THREAD

**Issue by setyg** [metersphere/metersphere#34743]
### MeterSphere 版本

metersphere/metersphere-ce-allinone:latest

### 使用外置数据库

否

### 问题描述

分享后的接口描述在接口定义里面，把接口移动一个目录目录后不能带出之前写入的描述信息

### 重现步骤

1.先定义一个接口，然后写入描述
2.分享该接口
3.回到接口定义，然后对已经分享的接口移动一个目录
4.在编辑该接口，之前写入的接口描述，现在看不见了

### 期待的正确结果

应该移动目录后仍能看见之前写入的接口描述信息

**Comment by 13290445582** [comment]
您好，这个情况没太理解是如何复现出来的，可以提供下完整操作的录屏吗。

**Comment by setyg** [comment]
不好意思，重新操作没有复现出来。。。
