### ISSUE TITLE
[BUG]接口分享后弹出密码输入框，直接按Esc键，仍能查看该文档所有内容

### ISSUE THREAD

**Issue by setyg** [metersphere/metersphere#34746]
### MeterSphere 版本

metersphere/metersphere-ce-allinone:latest

### 使用外置数据库

否

### 问题描述

接口分享后弹出密码输入框，直接按Esc键，仍能查看该文档所有内容

### 重现步骤

接口分享后
访问分享页面，弹出密码输入框，直接按Esc键
仍能查看该文档所有内容

**Comment by 13290445582** [comment]
感谢反馈，问题已复现，下个版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v3.6版本中已修复。

**Comment by setyg** [comment]
已解决
