### ISSUE TITLE
[BUG]  项目配额管理-同一时段最大并发数设置后不生效

### ISSUE THREAD

**Issue by fit2cloud-yaochunrong** [metersphere/metersphere#34761]
### 联系方式

姚春荣

### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

项目配额管理-同一时段最大并发数设置后不生效

### 重现步骤

![image](https://github.com/user-attachments/assets/7936e865-b0b4-4e9c-88ca-b0d69ee3c22a)
![image](https://github.com/user-attachments/assets/e9076344-b3fe-4bd3-95f5-59b54ca8f662)
![image](https://github.com/user-attachments/assets/d5ad4eec-16ca-427a-9875-46db374bbaae)
![image](https://github.com/user-attachments/assets/5114e4ae-b2ba-4150-9056-2a9f6607aafa)
此时执行用例，还是可以执行，也没有pendimg，不知道-同一时段最大并发数 设置的意义
![image](https://github.com/user-attachments/assets/04e2576f-c0e7-4ceb-9b30-290e423e3905)

**Comment by liuruibin** [comment]
性能测试啊。。。
