### ISSUE TITLE
[BUG]【接口测试】提取的变量放到环境全局变量或全局header中，却不能跨场景使用

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#348]
**MeterSphere 版本**
V1.2.1

**Bug 描述**
提取的变量放到环境全局变量或全局header中，却不能跨场景使用

**Bug 重现步骤**
1.  前提：测试集合A中存在场景1和场景2
2. 场景1中登陆后提取返回的token
3. 用beanshell提起值，并存在环境管理中的header中
4. 执行集合A-查看执行情况

**期待的正确结果**
所有接口都可以正常请求，存在环境中的变量可以全局调用，

**截图**
场景1获取的值
![image](https://user-images.githubusercontent.com/13564069/92205337-0bf1a380-eeb8-11ea-98ad-acf0b9317213.png)

场景2获取的值
![image](https://user-images.githubusercontent.com/13564069/92205345-101dc100-eeb8-11ea-97aa-3a890311cf34.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，目前变量是不能跨场景使用的，将在后续的版本中增加该场景的支持

**Comment by Ammyz** [comment]
已支持

**Comment by allinone-1** [comment]
@Ammyz   请教下，在beanshell中如何提取的变量放到环境全局变量中？
