### ISSUE TITLE
[BUG] 对接第三方平台时，下拉框没有选项

### ISSUE THREAD

**Issue by ijwstl** [metersphere/metersphere#34811]
### 联系方式

交流群 70 ijwtsl

### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

我记得之前选择JIRA后，填写了项目KEY后是会展示下拉框选项的，现在无法选择具体的问题类型等。
之前绑定过JIRA的项目没有问题，新建的项目会有问题

### 重现步骤
异常情况
![image](https://github.com/user-attachments/assets/5aeeafa4-2b76-4704-8a11-c7793a177d40)

正常情况
![image](https://github.com/user-attachments/assets/cc11bb84-63f6-45c6-9323-ee778c111dcf)

**Comment by 13290445582** [comment]
您好，最新环境未复现此问题，建议升级至最新环境使用。
