### ISSUE TITLE
[BUG]test-track模块，当test_case数据达到20w条时，查询耗时非常长，mysql和test-track模块CPU达到100%多

### ISSUE THREAD

**Issue by AIysl** [metersphere/metersphere#34827]
### 联系方式

18892682440

### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

是

### 问题描述

v2.10.22-lts
内置和外置都试过了，都很慢
当test_case数据达到20w条时，查询耗时非常长，mysql和test-track模块CPU达到100%多

### 重现步骤

当test_case数据达到20w条时，查询耗时非常长，mysql和test-track模块CPU达到100%多

**Comment by 13290445582** [comment]
您好，v2.10.23已经优化了下索引，希望可以解决您的问题，请更新。
