### ISSUE TITLE
[BUG]测试计划配置定时任务执行失败的消息通知，偶现 同一条消息发送两次的问题

### ISSUE THREAD

**Issue by fit2cloud-lijiaxin** [metersphere/metersphere#34828]
### 联系方式

李佳鑫

### MeterSphere 版本

v2.10.21-lts

### 使用外置数据库

否

### 问题描述

测试计划配置定时任务执行失败的消息通知，偶现 同一条消息发送两次的问题

### 重现步骤

测试计划配置定时任务执行失败的消息通知，偶现 同一条消息发送两次的问题，只在定时任务配置了消息通知，没有设置失败重试，项目管理-消息配置处没有配置消息通知，
排查test-track 日志，发现测试报告处理了两次，中间相差了两秒
![image](https://github.com/user-attachments/assets/65edb1f9-17dc-4279-9d99-ba178637f04d)

### 期待的正确结果

正常测试报告只处理一次，只发送一次消息

**Comment by 13290445582** [comment]
您好，不清楚是哪里出现的问题，最好把定时任务的配置和测试计划内关联了什么样的用例提供下，偶现情况的话现在还未复现也没有具体的可复现步骤，无法排查是哪里的问题。

**Comment by 13290445582** [comment]
您好，该情况暂无其他用户反馈，偶现情况也不一定可复现，待有可复现的具体步骤，非常欢迎您再次提供，该情况看起来也不影响操作，建议无可复现具体步骤提供的话，可检查下自身环境配置或更新到最新版本，暂无复现思路，感谢您的理解与支持！
