### ISSUE TITLE
[BUG]自定义代码片段执行第三方jar包失败

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#34845]
### MeterSphere 版本

v2.10.23-lts

### 使用外置数据库

否

### 问题描述

在"v2.10.20-lts"版本里提到的"Bug修复-fix(项目管理): 修复自定义代码片段执行第三方jar包失败的缺陷"，在这2个版本里都验证失败，仍然存在调用第三方jar包失败的bug；
https://github.com/metersphere/metersphere/releases/tag/v2.10.20-lts
https://github.com/metersphere/metersphere/releases/tag/v2.10.23-lts

### 重现步骤

就是正常的操作，10次里大概有5次报错。

### 期待的正确结果

10次都成功。

**Comment by XiamenHongjingsheng** [comment]
这是正常的时候。
![图片](https://github.com/user-attachments/assets/8b5311bf-1405-4dcd-a14d-199951012158)

**Comment by 13290445582** [comment]
您好，请问出问题的场景所使用的资源池是不是有多个节点。

**Comment by XiamenHongjingsheng** [comment]
> 您好，请问出问题的场景所使用的资源池是不是有多个节点。

@13290445582 您好，我出问题的场景所使用的资源池的确存在3个节点(1个本机ip+2个丛机ip)。我按照您给的思路，只保留了1个本机ip的节点，就能正常执行了，感谢您，您这定位问题的能力太厉害了。
@13290445582 但还有1个新的“问题”，假如我使用这3个节点来做性能分布式测试，那么调用第三方jar包是否会存在问题呢？因为我目前的性能测试用例里目前不需要调用第三方jar包，所以我自己这边无法验证，就想着咨询下您。

**Comment by 13290445582** [comment]
您好，可以将其他节点也升级为我们最新的Node，都使用最新Node就没有这个情况了。

**Comment by XiamenHongjingsheng** [comment]
> 您好，可以将其他节点也升级为我们最新的Node，都使用最新Node就没有这个情况了。

好勒好勒，感谢您！
