### ISSUE TITLE
[BUG]【测试计划】失败重试功能，请求重试几次后是成功的，但请求这显示Error，应该显示Success才对

### ISSUE THREAD

**Issue by 2lipan** [metersphere/metersphere#34846]
### MeterSphere 版本

v2.10.22-lts

### 使用外置数据库

否

### 问题描述

【测试计划】失败重试功能，请求重试几次后是成功的，但请求这显示Error，应该显示Success才对

### 重现步骤

【测试计划】失败重试功能，请求重试几次后是成功的，但请求这显示Error，应该显示Success才对
![091680e7fc6bc7073cf5f9c35ead7de](https://github.com/user-attachments/assets/33ef9cf1-127e-4022-8bcb-10d8ce0a0332)

**Comment by fit2-zhao** [comment]
目前确实是这样实现的，步骤上的状态是根据步骤下的请求状态计算上去的，目前无法区分是重跑步骤还是普通循环步骤，我们会在 v3 考虑这个问题。
