### ISSUE TITLE
[BUG]新的接口自动化场景引用其他场景，执行时其他场景的原场景变量不会生效

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#34841]
### 联系方式

1370296886@qq.com

### MeterSphere 版本

v3.6-lts

### 使用外置数据库

否

### 问题描述

新的接口自动化场景引用其他场景，执行时其他场景的原场景变量不会生效

### 重现步骤

1、创建新的接口自动化场景并引用其他场景（包含场景变量）
2、观察该场景执行时，被引用的场景的原场景变量是否会生效

**Comment by 13290445582** [comment]
您好，请问是否已经勾选「优先原场景参数」呢？
<img width="679" alt="image" src="https://github.com/user-attachments/assets/b56b955d-6c7a-41e5-a1f1-eb4c9a4954ff" />

**Comment by dashenyucainiao** [comment]
忽略此问题
