### ISSUE TITLE
[BUG]接口主流程里的接口用例名长度过长时，接口用例ID值就没展示出来

### ISSUE THREAD

**Issue by XiamenHongjingsheng** [metersphere/metersphere#34852]
### MeterSphere 版本

 v2.10.23-lts-41fd63d5

### 使用外置数据库

否

### 问题描述

您好，这问题是必现的。
![bug1 jpg](https://github.com/user-attachments/assets/c2503683-9001-4553-b4c5-7e023cc51ebb)

### 重现步骤

按截图里的内容进行造数据就行了呢。

**Comment by 13290445582** [comment]
您好，这里是支持滚动显示的，在步骤名称处左右滚动即可看到完整内容，当前的设计是这样子的，暂时没有其他改变的计划，感谢理解。
