### ISSUE TITLE
[BUG]用例后置操作的提取参数表单，更新操作会保存2个一样的参数名称，再次编辑操作最后一行时，会自动复制一行

### ISSUE THREAD

**Issue by enjoylifeo** [metersphere/metersphere#34855]
### 联系方式

enjoylifeo@126.com

### MeterSphere 版本

3.5.0

### 使用外置数据库

否

### 问题描述

用例后置操作的提取参数表单，更新操作会保存2个一样的参数名称，再次编辑操作最后一行时，会自动复制一行

### 重现步骤

![image](https://github.com/user-attachments/assets/082ba6e0-3d0d-4572-9dbc-5c620ff95ba9)
![image](https://github.com/user-attachments/assets/f6a53911-30c6-4010-ba11-479e641da61b)
![image](https://github.com/user-attachments/assets/65f8830c-069f-4b6b-bd95-6ac342b9d9f3)

### 期待的正确结果

1、仅保存填写的2个参数
2、自动新增1行空行，不是复制一行

**Comment by 13290445582** [comment]
您好，请升级最新的v3.6版本，在v3.6版本中已经修复过此问题。
