### ISSUE TITLE
[BUG]节点机器执行，报错，【请进】有日志截图。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#3487]
**MeterSphere 版本**
1.10

**Bug 描述**
分别用了2台节点机器，报出了不同的错误。（节点配置正常）

错误1 ： Error: Check node-controller /etc/hosts, `127.0.0.1 ${hostname}` must be contained. Please delete the report and rerun.
截图1 ：
![image](https://user-images.githubusercontent.com/6467295/120609190-8b7ec400-c484-11eb-940a-e65e787b4c00.png)

错误2：Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms3-jdk8
![image](https://user-images.githubusercontent.com/6467295/120609704-0811a280-c485-11eb-8b2d-2b72220687bb.png)

**Comment by liuruibin** [comment]
https://github.com/metersphere/metersphere/issues/1711

**Comment by liuruibin** [comment]
到部署node-controller的机器上下载这个镜像

**Comment by seasoncool** [comment]
@liuruibin  感谢您的回复，我机器里面已经有了 下面的容器：还需要下 额外的吗？
registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.10.0   "/deployments/run-ja…"   6 days ago          Up 6 days (healthy)         0.0.0.0:8082->8082/tcp, 0.0.0.0:9100->9100/tcp

我在docker 里面有搜寻到 node-controller 这个容器，是不是节点机器，只用起这个容器就可以了啊？它的端口是8082？

**Comment by liuruibin** [comment]
ms-node-controller 是一个调度器，这个容器收到性能测试任务会创建新的容器出来。使用的镜像就是registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms4-jdk8
