### ISSUE TITLE
[BUG]引用多个场景，被引用的场景存在相同名称的场景变量时，场景变量没有正确获取

### ISSUE THREAD

**Issue by zengjin55** [metersphere/metersphere#3494]
**MeterSphere 版本**
v1.9.2

**Bug 描述**
引用多个场景，被引用的场景存在相同名称的场景变量时，场景变量只会获取第一个场景变量

**Bug 重现步骤**
1.  创建接口测试场景1，其中场景变量：param=1
2. 创建接口测试场景2，其中场景变量：param=2
3. 创建接口测试场景3，引用测试场景1和测试场景2
4. 执行接口测试场景3

**期待的正确结果**
当执行到测试场景2时，param应为2，当前为1

**Comment by zyyfit** [comment]
重复bug
https://github.com/metersphere/metersphere/issues/3019

**Comment by SloanGao** [comment]
@zyyfit ，請問這個問題是在哪個版本已經修復了？我看問題已經closed
