### ISSUE TITLE
[BUG]禅道关联需求未看到对应的需求

### ISSUE THREAD

**Issue by houye111677** [metersphere/metersphere#3495]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.9.2
**Bug 描述**
简要描述您碰到的问题
系统设置里面进行服务集成关联禅道，在项目管理里面关联对应的禅道以及对应的项目
新建对应的项目，新建用例关联需求的时候关联不上对应的项目需求
**Bug 重现步骤**
1.  组织-服务集成，集成禅道信息并测试连接通过
2. 项目-项目管管理-新建项目，关联对应的禅道项目ID、缺陷模板-点击确定
3. 新建功能测试用例-关联需求未看到对应的需求出来

**期待的正确结果**
正确情况下应该是什么样的？
正常情况新建用例应该是可以关联对应的需求的
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.9.3 和 1.10.0版本都没有复现这个问题，建议升级使用最新版

**Comment by zyyfit** [comment]
您好，1.9.3 和 1.10.0版本都没有复现这个问题，建议升级使用最新版

**Comment by houye111677** [comment]
![image](https://user-images.githubusercontent.com/72909658/120777325-bf76e980-c557-11eb-9e9b-92343e3643f2.png)
![image](https://user-images.githubusercontent.com/72909658/120777391-cf8ec900-c557-11eb-9531-f003dbe15a6c.png)
已经g更新了最新的版本

**Comment by zyyfit** [comment]
您好，您使用的版本是release版1.9.3吗？这边应该是没有  【需求ID/名称】这个字段的

![image](https://user-images.githubusercontent.com/73461316/121028171-2a375780-c7da-11eb-83ae-26bf1c921df7.png)
