### ISSUE TITLE
[FEATURE]集成jira后无法知道是谁提的bug

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#350]
**请描述您的需求或者改进建议.**
集成jira后无法知道是谁提的bug

**请描述你建议的实现方案**
jira集成绑定账号的功能应该是 测试平台账号与jira账号关联，这样谁提的bug就很清晰了

**Comment by zhao103804** [comment]
建议在这里加
![11111](https://user-images.githubusercontent.com/29306248/92208563-09924800-eebe-11ea-9d63-0cb2527378b8.jpg)

**Comment by youliyuan-fit2cloud** [comment]
#415 问题相同，请持续关注～
