### ISSUE TITLE
[FEATURE]“构建后操作”也需要跑一下，但是在步骤里没有metersphere可选，考虑优化吗？

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#351]
**请描述您的需求或者改进建议.**
我想“构建后操作”也需要跑一下，但是在步骤里没有metersphere可选，考虑优化吗？
![image](https://user-images.githubusercontent.com/37016695/92344599-7a717400-f0f9-11ea-8e70-1e04619b44db.png)

**请描述你建议的实现方案**
 
![image](https://user-images.githubusercontent.com/37016695/92344624-8a895380-f0f9-11ea-9122-46bae1b3c903.png)

**Comment by xulinde** [comment]
最新版的jenkins插件支持Pipeline方式调用，您可以通过在Pipeline脚本中增加Metersphere Step的方式更灵活地组织自己的持续测试任务
![image](https://user-images.githubusercontent.com/64065190/107328863-5112a500-6aea-11eb-82a4-63e9f0d3653c.png)
