### ISSUE TITLE
[BUG]接口自动化场景下调试，使用场景变量时，当变量类型为列表时，在脚本中无法被引用

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3512]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.10.0

**Bug 描述**
接口自动化场景下调试，使用场景变量时，当变量类型为列表时，在前后置脚本中无法被引用

**Bug 重现步骤**

**截图**
<img width="1439" alt="WechatIMG125" src="https://user-images.githubusercontent.com/32027713/120742522-9b041880-c529-11eb-8afb-9fc68f45410d.png">
<img width="1439" alt="WechatIMG126" src="https://user-images.githubusercontent.com/32027713/120742666-e5859500-c529-11eb-9a12-b5b027493353.png">
<img width="1439" alt="WechatIMG127" src="https://user-images.githubusercontent.com/32027713/120742682-ec140c80-c529-11eb-9bcb-ed2b13f0cc7b.png">

**Comment by zyyfit** [comment]
您好，不在循环中引用列表变量的话需要使用下标标注引用的第几个变量，如 test_1
