### ISSUE TITLE
[BUG]当项目下新增数据库时，原来接口自动化场景下保存的自定义请求的所选的数据库就变成新加的那个数据库

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3516]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.10.0-LTS

**Bug 描述**
当项目下新增数据库时，原来接口自动化场景下保存的自定义请求的所选的数据库就变成新加的那个数据库，导致调试的结果为失败
注：1.9.3升级到V1.10.0-LTS就变成这样

**Bug 重现步骤**
1.  新增数据库

**期待的正确结果**
   原来保存的自定义请求的数据库不变

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，最新版已修复，请升级使用
