### ISSUE TITLE
[FEATURE]所有相关日志是否能够提供页面级查看，有时候运行不知道哪里出错，日志又比较分散

### ISSUE THREAD

**Issue by fangyuanrui** [metersphere/metersphere#352]
**请描述您的需求或者改进建议.**

需要一个快速友好的日志查询功能

**请描述你建议的实现方案**
提供页面展示所有相关日志（尤其是错误日志）

**Comment by zyyfit** [comment]
现在（v1.7.2）接口测试和性能测试已支持查看日志
