### ISSUE TITLE
[BUG]自动化测试-csv文件使用循环控制器，第二次迭代的参数仍为第一行内容

### ISSUE THREAD

**Issue by yeohjesus** [metersphere/metersphere#3520]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.10

**Bug 描述**
简要描述您碰到的问题
自动化测试-csv文件使用循环控制器，第二次迭代的参数仍为第一行内容
**Bug 重现步骤**
1.  点击接口自动化 上传两行内容的csv
2. 添加脚本，设置循环两次
3. 第二次执行仍为第一行参数
4. 

**期待的正确结果**
正确情况下应该是什么样的？
第二次正常迭代第二行参数
**截图**
如果有截图，请附上截图.
[
<img width="860" alt="循环器迭代每次取第一行值3" src="https://user-images.githubusercontent.com/18098023/120770810-1e853000-c551-11eb-8984-6fd1a96f4a66.png">
<img width="950" alt="循环器迭代每次取第一行值2" src="https://user-images.githubusercontent.com/18098023/120770815-1fb65d00-c551-11eb-879c-196f915779b2.png">
<img width="765" alt="循环器迭代每次取第一行值" src="https://user-images.githubusercontent.com/18098023/120770816-204ef380-c551-11eb-8e73-67e8bca5221a.png">

](url)

**Comment by zyyfit** [comment]
您好，请问是必现的吗？这边没有复现呢，操作中有什么特殊步骤吗？
