### ISSUE TITLE
[BUG]用户状态关闭后，切换到测试计划页面，会自动退出

### ISSUE THREAD

**Issue by xue2018** [metersphere/metersphere#3524]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版

**Bug 描述**
用户状态关闭后，切换到测试计划页面，会自动退出

**Bug 重现步骤**
1.  测试计划有该用户创建的记录
2. 系统设置，关闭用户状态，
3. 其他用户切换进入测试计划页面
4. 会自动退出系统

**期待的正确结果**
正常访问

**截图**

![image](https://user-images.githubusercontent.com/31928521/120775220-95242c80-c555-11eb-847e-a6d7e54a7e0a.png)
![image](https://user-images.githubusercontent.com/31928521/120775269-a0775800-c555-11eb-9c82-eef116f7dff9.png)

**Comment by zyyfit** [comment]
您好，使用最新版没有复现，请问您使用的哪个版本？
