### ISSUE TITLE
[BUG]【测试跟踪】脑图-测试步骤中包含某些特定字母时导入失败【必现bug】

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#3526]
**MeterSphere 版本**
1.10

**Bug 描述**
测试步骤中包含某些特定字母时导入失败
![image](https://user-images.githubusercontent.com/49704984/120775570-e7654d80-c555-11eb-9811-83be3e7ba4a5.png)

![image](https://user-images.githubusercontent.com/49704984/120775571-e7654d80-c555-11eb-953f-20fe39a64853.png)

**Bug 重现步骤**
1.  因为代码中使用正则匹配，某条用例步骤中包含字母tc pc rc id tag 时，步骤会导入失败。
![image](https://user-images.githubusercontent.com/49704984/120787586-18e41600-c562-11eb-8f64-c8df7eb90099.png)

3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
用例导入成功

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，因为需要区分用例，步骤等信息，如果不是必要的话建议您不要在步骤中使用这些信息，我们后续也会讨论一下是否优化这个问题

**Comment by liAnita** [comment]
> 您好，因为需要区分用例，步骤等信息，如果不是必要的话建议您不要在步骤中使用这些信息，我们后续也会讨论一下是否优化这个问题

您好，实际在使用过程中不是单独使用到'id' 'rc'，而是某些单词中如果包含了 就无法导入,比如在验证接口字段：目前公司测试人员已经遇见了大量这样的问题。导致用例无法导入
![image](https://user-images.githubusercontent.com/49704984/122023315-ff608b00-cdf9-11eb-8ac8-bf477b80deb9.png)

**Comment by zyyfit** [comment]
> > 您好，因为需要区分用例，步骤等信息，如果不是必要的话建议您不要在步骤中使用这些信息，我们后续也会讨论一下是否优化这个问题
> 
> 您好，实际在使用过程中不是单独使用到'id' 'rc'，而是某些单词中如果包含了该四组词， 就无法导入 。
> id这样常用的单词在步骤中出现频率极高,
> 目前公司测试人员已经遇见了大量这样的问题，导致用例无法导入。
> ![image](https://user-images.githubusercontent.com/49704984/122023315-ff608b00-cdf9-11eb-8ac8-bf477b80deb9.png)
> 
> 建议正则匹配前两个规则即可：
> ![image](https://user-images.githubusercontent.com/49704984/122023847-8281e100-cdfa-11eb-8054-e572c9465c9c.png)

您好，已经修复了这个问题，会在1.10.2版本发布

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
