### ISSUE TITLE
[FEATURE]建议增加多一层测试用例，使在创建测试时，可共用接口基本信息

### ISSUE THREAD

**Issue by msnshow** [metersphere/metersphere#353]
目前项目下直接是测试，没有用例维护的概念，对于同一个接口有多种参数值需要覆盖测试，目前只能复制多份请求来实现，这样不方便后期维护；

--------------------------------------
建议修改接口测试结构，分为 接口信息维护，接口用例 两个模块，最终结构为
项目--接口集合--测试用例

一个接口可以有多个测试用例，共用接口基础信息，可以有不同的参数输入，不同的响应值判断，以满足接口测试覆盖度的需求

**Comment by zyyfit** [comment]
v1.6改版后的 新版接口测试 应该是满足此需求的
