### ISSUE TITLE
[BUG]请求体中字段值含有 '%' 传入平台后变成 undefined

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#3534]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.10.0-93f6870d

**Bug 描述**
请求体中字段值含有 '%' 传入平台后变成 undefined

**Bug 重现步骤**
1.  json body 体中含有 字段"table_tag": "'%'", 调试执行；控制台中显示"table_tag": "undefined"
(尝试过 "''" 和 “%”是没问题的，但是 "'%'" 不行)

**期待的正确结果**
json body 体中含有 字段"table_tag": "'%'", 调试执行；控制台中显示"table_tag": "'%'"

**截图**
如果有截图，请附上截图.

**Comment by Amber1700** [comment]
尝试过 "''" 和 “%”是没问题的，但是 "'%'" 不行

**Comment by xulinde** [comment]
1.11已修复
