### ISSUE TITLE
[BUG]断言 “不等于” 不生效

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#3535]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是  v1.10.0-93f6870d

**Bug 描述**
响应 断言 “不等于” 不生效
请同步盘查其他断言

**Bug 重现步骤**
1.    断言总数 不等于 0    实际： "total": 103  ；错误信息：Value expected to be '0', but found '103'

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，也有其他用户反馈这个问题，但是我们这边暂时没有复现，我们会再排查一下这个问题的
