### ISSUE TITLE
[BUG]接口测试上传文件类型测试失败

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#354]
**MeterSphere 版本**
1.21

**Bug 描述**
目前接口测试中需要上传文件，且Content-Type: multipart/form-data; 的接口测试会报错

**Bug 重现步骤**
1.  填写header中Content-Type: multipart/form-data;  boundary=----xxxxx...,以及其他header值
2. 填写接口参数，并上传文件
3. 请求接口
**期待的正确结果**
获取接口结果

**截图**
![image](https://user-images.githubusercontent.com/13564069/92367307-d30c3580-f128-11ea-845b-03ac1d1b373a.png)

**Comment by seasoncool** [comment]
同样有该问题，报错还不一样。

我们这边测试了2种情况：
1. 【正常】没有请求头的，可以成功发送 附件。
2.【报错】带有请求头的，附件格式为.mp4格式 和 .zip 格式 均有报错。
报错内容如下：
前提：Content-Type ：multipart/form-data


{
	"message": "Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",
	"error": {
		"reason": "Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",
		"code": "",
		"uri": "XXXXXXXXX",
		"timestamp": "2020-09-08T01:12:26.811+0000"
	}
}

**Comment by AgAngle** [comment]
multipart/form-data 不能显示添加，会自动根据请求添加，请把Content-Type删了再试试吧

**Comment by Ammyz** [comment]
已支持
