### ISSUE TITLE
[BUG] 一键安装脚本无法在mac上运行

### ISSUE THREAD

**Issue by chenjienn** [metersphere/metersphere#3544]
mac 版本  10.14.6

运行 sh quick_start.sh 后报如下错误

<img width="876" alt="一键安装错误" src="https://user-images.githubusercontent.com/13412289/120878464-3c08d700-c5ef-11eb-9a47-281263c9f3eb.png">

**Comment by shenkaibo** [comment]
这个可以 把 install 脚本里的 校验 docker-compose 版本 那段去掉

**Comment by chenjienn** [comment]
> 这个可以 把 install 脚本里的 校验 docker-compose 版本 那段去掉

去掉之后仍无法正常运行   希望能提供一个针对macOS可用的安装脚本

**Comment by xulinde** [comment]
使用最新脚本还有此问题吗
