### ISSUE TITLE
[BUG]接口一键运行无法找到上传文件

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#355]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.2.0

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口案例，请求参数上传文件
2. 全部测试界面-选择测试，点击一键运行
测试结果：提示找不到**文件

备注：通过保存并执行按钮执行案例，不会出现文件找不到问题

**期待的正确结果**
正确情况下应该是什么样的？正确执行

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
已修复，请等待1.3.1之后的版本发布

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue
