### ISSUE TITLE
[QUESTION]为什么接口测试方式为自动时，必须要关联测试呢？

### ISSUE THREAD

**Issue by sunskblue** [metersphere/metersphere#356]
**请描述您的问题.**
为什么接口测试方式为自动时，必须要关联测试呢？
登陆测试理论上来说不需要关联其他用例，而是其他用例关联登陆。
所以当设置测试方式为“自动”时，关联测试为必填项是不是不太合适

![image](https://user-images.githubusercontent.com/23308774/92374808-d6a4ba00-f132-11ea-820c-761140d8325c.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这里的关联含义为关联一个平台当中的接口测试脚本
