### ISSUE TITLE
[BUG] 测试用例字段信息不统一。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3562]
**MeterSphere 版本**
1.10.0

3个地方：
1. 批量编辑用例时，选择的字段名称为“维护人”
2. 用例详情页的字段为“责任人”
3. 列表筛选条件的字段又叫“创建人”

请问到底是什么人？？
1. 
![image](https://user-images.githubusercontent.com/44999044/120946530-65507100-c76f-11eb-980c-2feaafc6e49e.png)

2.
![image](https://user-images.githubusercontent.com/44999044/120946559-7b5e3180-c76f-11eb-92ca-78915ae2d45c.png)

3.
![image](https://user-images.githubusercontent.com/44999044/120946506-58338200-c76f-11eb-9666-7a4c620f96d5.png)

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本统一字段名称

**Comment by zyyfit** [comment]
1.10.2版本会将列表的 维护人 统一成 责任人，责任人和创建人是不一样的，不做统一

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
