### ISSUE TITLE
[BUG] 用例列表中，自定义字段顺序不正确

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3563]
**MeterSphere 版本**
1.10.0

偶现，不知如何重现：
![image](https://user-images.githubusercontent.com/44999044/120946661-c2e4bd80-c76f-11eb-82b2-901266b2e6e4.png)

**Comment by zyyfit** [comment]
感谢反馈，我们会关注这个问题的

**Comment by zyyfit** [comment]
您好，我们对表头的排序方式做了优化，我用最新版1.13测试正常，您可以等今天13版本发布后试一下，也可以在1.12版本测试一下，应该都是正常的了
