### ISSUE TITLE
[BUG] 测试用例导入步骤与预期结果对不上号。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3564]
**MeterSphere 版本**
1.10.0

如下图：
![QQ图片20210607091807](https://user-images.githubusercontent.com/44999044/120947117-4e128300-c771-11eb-82a5-50cefdcde47a.png)

另：1.8版本的测试用例模板的体验要比1.10的好些。当前版本的模板表头不美观，且字段排列很乱，建议把重点放前面，且步骤对不上。

**Comment by zyyfit** [comment]
感谢反馈，我们内部讨论一下这个问题

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
