### ISSUE TITLE
[BUG] 测试计划中用例比较多，全部显示会导致浏览器非常卡。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3565]
**MeterSphere 版本**
1.10.0 

1. 用例很多，图中92条
2. 所有用例都标了执行结果的情况下
3. 列显示调为100

![image](https://user-images.githubusercontent.com/44999044/120947480-4a333080-c772-11eb-90e5-0ce945887d87.png)

**Comment by zyyfit** [comment]
您好，我们测试了600多条用例的情况，没有出现特别卡顿的现象，请问您那边具体是什么情况？方便上传个录屏吗？

**Comment by LimonFHM** [comment]
> 您好，我们测试了600多条用例的情况，没有出现特别卡顿的现象，请问您那边具体是什么情况？方便上传个录屏吗？

@zyyfit 
![卡顿录屏](https://user-images.githubusercontent.com/44999044/121107658-e1fc5180-c83a-11eb-8eea-b2c88094767a.gif)

**Comment by xulinde** [comment]
v1.10.2版本已优化性能

**Comment by LimonFHM** [comment]
@xulinde 未解决。现象依旧存在。
