### ISSUE TITLE
[BUG]测试跟踪中，左边树节点名称显示的字太少。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3566]
**MeterSphere 版本**
1.10.0

![image](https://user-images.githubusercontent.com/44999044/120947630-aac26d80-c772-11eb-970a-11a800f7478c.png)

补充：我知道可以拖动，但是总共没几个字要拖那么大，且每次进来都要拖，体验不好。

**Comment by zyyfit** [comment]
您好，后续版本会优化这个问题

**Comment by zyyfit** [comment]
您好，1.10.1版本已发布，已优化这个问题
