### ISSUE TITLE
[BUG]测试用例列表中的字段宽度优化或自定义。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3567]
**MeterSphere 版本**
1.10.0

比如用例的名称字段，一般还是有点长度的，但是进入列表后，默认给的宽度很短，需要手动拖大才能看全了。但是一刷新，或者退出重新登录，这个字段宽度又会变得很小，导致每次都要去拉，易用性不佳。

![image](https://user-images.githubusercontent.com/44999044/120947788-2ae8d300-c773-11eb-985e-1c7e341072b0.png)

建议：宽度出厂默认优化，且支持自定义就好了，谢谢了。

**Comment by xulinde** [comment]
后面版本这里会优化成，调整列宽后保持调整后的宽度，刷新或者重新登录都不会恢复。

**Comment by xulinde** [comment]
已实现：调整列宽后保持调整后的宽度，刷新或者重新登录都不会恢复
