### ISSUE TITLE
[BUG]缺陷管理对接禅道，禅道中删掉BUG，ms平台中存在的数据无法删除。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3568]
**MeterSphere 版本**
1.10.0

1. 在metersphere中提的BUG 
2. 在禅道中将BUG删掉

![image](https://user-images.githubusercontent.com/44999044/120948286-7ea7ec00-c774-11eb-9318-3892e1cc0522.png)

如图ms这边这些数据无法删除，也无法预览、

**Comment by zyyfit** [comment]
感谢反馈，会在下个版本修复这个问题

**Comment by xulinde** [comment]
v10.5已修复
