### ISSUE TITLE
[QUESTION]请求响应中带有中文，MS返回响应显示的是编码号，是否可配置直接显示中文

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#3575]
**请描述您的问题.**
请求响应中带有中文，MS返回响应显示的是中文编码号，是否可配置直接显示中文？还是需要代码支持？

**Comment by xulinde** [comment]
请求头加utf-8了吗

**Comment by Amber1700** [comment]
> 请求头加utf-8了吗，加了的话会自动转码的

响应的请求头Content-Type是application/json，用postman调用显示的就是中文，用MS就是中文编码
