### ISSUE TITLE
[BUG] 接口测试中PUT、DELETE请求不支持'application/x-www-form-urlencoded'类型表单

### ISSUE THREAD

**Issue by valsong** [metersphere/metersphere#358]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2.0
**Bug 描述**
简要描述您碰到的问题
接口测试中PUT、DELETE请求不支持'application/x-www-form-urlencoded'类型表单
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，能否再详细描述下是怎么得出不支持的判断的？
