### ISSUE TITLE
[BUG]场景测试：被引用场景下的步骤可以被拖拽出场景外，但又被限制拖拽回去，应该被限制拖拽

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#3581]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.10.0-93f6870d

**Bug 描述**
被引用场景下的步骤可以被拖拽出场景外，但又被限制拖拽回去，应该被限制拖拽

**Bug 重现步骤**
1.  引用已有场景，将引用的步骤拖拽至场景外，再拖拽至场景内

**期待的正确结果**
当前场景 引用 其他场景，其他场景不能在当前场景被修改，应该被限制拖拽

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我这边测试可以拖回去，我们会讨论一下您这个提议的
