### ISSUE TITLE
[BUG]使用jenkins插件时，admin账号只有默认工作空间，其它账号无工作空间。

### ISSUE THREAD

**Issue by qiaoshengyu** [metersphere/metersphere#3582]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
**V1.10**

**Bug 描述**
简要描述您碰到的问题
使用jenkins插件时，admin账号只有默认工作空间，其它账号无工作空间，以致无法使用空间下的项目。

**Bug 重现步骤**
1.test账号与admin账号同在默认工作空间，同为工作空间管理员。
![image](https://user-images.githubusercontent.com/41959940/120961152-d273fe80-c78f-11eb-93e6-359d34ba415b.png)
2.jenkins中使用test账号，无法获取工作空间信息。
![image](https://user-images.githubusercontent.com/41959940/120960917-60031e80-c78f-11eb-9010-52cf02309023.png)

**期待的正确结果**
正确情况下应该是什么样的？
可以获得关联该账号的所有工作空间、项目、计划等。

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您使用的jenkins插件版本是多少呢

**Comment by qiaoshengyu** [comment]
> 您使用的jenkins插件版本是多少呢
V1.10.0
metersphere-jenkins-plugin-v1.10.0.hpi

**Comment by zyyfit** [comment]
相关bug https://github.com/metersphere/metersphere/issues/4058

**Comment by zyyfit** [comment]
您好，最新版未复现，您可以升级到最新版再试一下，注意要保持ms版本和插件版本一致

**Comment by xulinde** [comment]
1.10.4已修复，您可以升级到最新版1.10.4再试一下，注意要保持ms版本和插件版本一致
