### ISSUE TITLE
[BUG]条件控制语句 非空 判断不正确

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#3587]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.10.0-93f6870d

**Bug 描述**
条件控制语句 非空 判断不正确

**Bug 重现步骤**
1.  条件控制语句 ：定义任意变量，选择非空，if下配置多个步骤，执行。变量不存在，if下的步骤会执行
2. 条件控制语句 ：定义已有变量，选择非空，if下配置多个步骤，执行。变量未设置值，if下的步骤会执行

**期待的正确结果**
1.  条件控制语句 ：定义任意变量，选择非空，if下配置多个步骤，执行。变量不存在，if下的步骤不执行
2. 条件控制语句 ：定义已有变量，选择非空，if下配置多个步骤，执行。变量未设置值，if下的步骤不执行

**截图**

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.10.2已修复
