### ISSUE TITLE
[BUG]接口自动化下，按照MS格式导出JSON之后，在按照MS导入到另外一个模块下，不覆盖，新导入JSON后没有内容

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3588]
**MeterSphere 版本**
V1.10.0

**Bug 描述**
接口自动化下，按照MS格式导出JSON之后，在按照MS导入到另外一个模块下，不覆盖，则目标模块下没有内容
**Bug 重现步骤**
1.  接口自动化
2. 导出MeterSphere格式的文件
3. 同一项目下新建模块
4. 再导入到新建的模块下

**期待的正确结果**
新建的模块下和之前的内容一样

**截图**
![WechatIMG128](https://user-images.githubusercontent.com/32027713/120971228-f854cf80-c79e-11eb-97e5-0382e6fa0f0a.png)

**Comment by zyyfit** [comment]
您好，是必现的吗？这边没有复现呢，能描述一下具体复现步骤吗

**Comment by dashenyucainiao** [comment]
必现的，在某个项目下选择一个模块导出MS格式场景，再换个模块如导入这个MS格式的数据，就会发现新导入的为空

**Comment by dashenyucainiao** [comment]
[Metersphere_Scenario_test.json.zip](https://github.com/metersphere/metersphere/files/6613151/Metersphere_Scenario_test.json.zip)

**Comment by zyyfit** [comment]
> 必现的，在某个项目下选择一个模块导出MS格式场景，再换个模块如导入这个MS格式的数据，就会发现新导入的为空

是这样的，选择不覆盖后，不会更新接口的模块信息，也不会更新接口信息
