### ISSUE TITLE
[BUG]https://demo.metersphere.com/#/api/home页面无法正常渲染

### ISSUE THREAD

**Issue by sunskblue** [metersphere/metersphere#359]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
https://demo.metersphere.com/#/api/home页面无法正常渲染
显示 jdbc 连接数据库超时
**Bug 重现步骤**
1.  访问https://demo.metersphere.com/#/api/home

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/23308774/92380466-ccd38480-f13b-11ea-95c6-41805edeaf11.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这个 demo 环境问题，已恢复正常
