### ISSUE TITLE
[BUG]接口自动化下调试某一个场景，场景报告和步骤里的结果显示不一样，且所有非自定义请求步骤里面的报告内容和最后一个请求的内容一致

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3601]
**MeterSphere 版本**
V1.10.0

**Bug 描述**
接口自动化下调试某一个场景，场景报告和步骤里的结果显示不一样，且所有非自定义请求步骤里面的报告内容和最后一个请求的内容一致

**Bug 重现步骤**
1.  自动化场景
2. 选择其中一个场景
3. 调试
4. 观察场景报告和步骤里面的报告是否一致

**期待的正确结果**
场景报告和每个步骤里面的报告应该一致

**截图**

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.10.1 已修复，请升级到该版本。
