### ISSUE TITLE
[BUG]用WebForm开发的网站，提交的请求都是同一个URL，接口定义只能添加一个，添加其他提示接口请求地址已经存在

### ISSUE THREAD

**Issue by wkj002** [metersphere/metersphere#3609]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.10.0
**Bug 描述**
简要描述您碰到的问题
用WebForm开发的网站，提交的请求都是同一个URL，接口定义只能添加一个，添加其他提示接口请求地址已经存在
**Bug 重现步骤**
1.  在接口定义创建一个和之前相同URL，请求体json数据包不同的接口
2. 提示接口请求地址已存在，无法添加
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
能添加多个URL相同，但json数据包不同的接口
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，您可以在系统项目设置中开启url可重复（但是接口名称不能重复，否则还是添加不上），或者在一个接口中，添加不用的用例
![image](https://user-images.githubusercontent.com/73461316/121050831-7e970300-c7eb-11eb-8b74-fda25fa4bb73.png)

**Comment by wkj002** [comment]
谢谢，可以添加了
