### ISSUE TITLE
[FEATURE]接口测试支持从测试集合跳转到测试报告

### ISSUE THREAD

**Issue by Bearzzzzz** [metersphere/metersphere#361]
**请描述您的需求或者改进建议.**
接口测试：很多时候看测试报告都是以测试集合为单位的，建议在测试集合的操作列加上跳转报告的按钮，点击之后能跳转到报告页面并仅展示该集合的历史报告。另外当前的报告页面展示的是工作空间下所有项目的测试报告，太杂了，对于测试来说很多报告都是不需要看的。当前的项目搜索入口隐藏的太深，能否直接将项目搜索条件放在报告页面上呢

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 接口测试：很多时候看测试报告都是以测试集合为单位的，建议在测试集合的操作列加上跳转报告的按钮，点击之后能跳转到报告页面并仅展示该集合的历史报告。另外当前的报告页面展示的是工作空间下所有项目的测试报告，太杂了，对于测试来说很多报告都是不需要看的。当前的项目搜索入口隐藏的太深，能否直接将项目搜索条件放在报告页面上呢
> 
> **请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/36292514/94647941-1de22d00-0324-11eb-98f5-9dfd35e6f323.png)
这里可以查看哦，入口确实有些隐蔽 ，这里可以优化一下
