### ISSUE TITLE
[QUESTION]小白提问

### ISSUE THREAD

**Issue by zhuzhuxing** [metersphere/metersphere#3619]
请问第一次使用admin账号登录进入系统只有系统设置吗。测试跟踪和接口测试菜单位置在什么地方？
![image](https://user-images.githubusercontent.com/48397809/121003998-bb99d000-c7c0-11eb-943f-cdc28111394b.png)

**Comment by xulinde** [comment]
您用的哪个版本呢，清理下浏览器缓存试下

**Comment by zhuzhuxing** [comment]
是因为没有创建项目的缘故吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 晚上7:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]小白提问 (#3619)





 
您用的哪个版本呢，清理下浏览器缓存试下

**Comment by xulinde** [comment]
1.10.1版本会创建默认项目并添加权限，您可以升级下1.10.1

**Comment by zhuzhuxing** [comment]
好的，我升级下试试，感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]小白提问 (#3619)





 
1.10.1版本会创建默认项目并添加权限，您可以升级下1.10.1

**Comment by zhuzhuxing** [comment]
如图：升级到最新版本，清理缓存之后，重新用admin账号登录，还是只有一个系统设置菜单。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION]小白提问 (#3619)





 
1.10.1版本会创建默认项目并添加权限，您可以升级下1.10.1

**Comment by zhuzhuxing** [comment]
已解决，感觉您的耐心指导 @xulinde
