### ISSUE TITLE
[BUG]使用一键安装脚本配置好以后，以默认的管理账号进入，在未配置角色的情况下，有接口报404，并且使用手册里面没有任何说明

### ISSUE THREAD

**Issue by jerrychen777** [metersphere/metersphere#3620]
**MeterSphere 版本**
1.10
**Bug 描述**
1、使用一键配置脚本部署好以后，以默认的管理员账号进入，未配置角色的情况下，系统只能进到系统设置页面，缺少任何的提示，要设置什么角色？手册里面也没有说明
2、这种情况下，点击回到新版，页面接口报错
**Bug 重现步骤**
1.  使用一键配置脚本，配置该系统
2. 使用默认的管理员账户进入系统，并且没有配置角色的情况下，点击administrator--回到新版，此时能看到接口返回404

**期待的正确结果**
1、部署好后，如果必须要配置角色，需要在手册里面说明
2、没有配置角色的情况下，接口也不该报404吧

**截图**
![image](https://user-images.githubusercontent.com/43308983/121108182-e37a4980-c83b-11eb-8314-fd747043a6c5.png)

**Comment by zyyfit** [comment]
您好，1.10.1版本已经添加了默认项目，admin登陆可以看到所有页面了
