### ISSUE TITLE
[BUG]测试计划中无法添加场景用例

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3621]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**
简要描述您碰到的问题
选择场景用例，页面空白，上个版本是好的，更新新版后页面无法显示了
**Bug 重现步骤**
1.  创建测试计划
2. 进入测试计划，选择接口测试用例
3. 选择场景用例

**期待的正确结果**
能够查询到相关场景用例

**截图**
![image](https://user-images.githubusercontent.com/40912823/121112465-078d5900-c843-11eb-84a9-ba3293b8a1d0.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.10.2已修复
