### ISSUE TITLE
[BUG]自动化场景下，有多个接口一起调试，其中某一个接口的后置脚本发生语法错误，整个页面一直处于转圈中。。。

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3622]
**MeterSphere 版本**
V1.10.0

**Bug 描述**
自动化场景下，有多个接口一起调试，其中某一个接口的后置（script类型）脚本有语法错误，点击调试之后整个页面一直处于转圈中，用户无法判别到底是啥问题

**期待的正确结果**
不要一直处于转圈之中，有错误在结束之后，用户可以自己在报告中调查

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我这边脚本报错后后面的步骤还是可以执行的
![图片](https://user-images.githubusercontent.com/73461316/121625450-145db700-caa6-11eb-8f18-fb99a5b6caf3.png)
