### ISSUE TITLE
[BUG]接口自动化流程中，无法保存第二条数据库源名称记录

### ISSUE THREAD

**Issue by Wwwmwwm0** [metersphere/metersphere#3623]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.接口自定义中，选择SQL，创建一个查询接口A，环境选择 环境A，环境A配置两条数据库源名称 a，b（a在第一行，b在第二行），选择数据库记录b
2.接口自动化中创建场景，导入查询接口A，流程中运行环境也选择环境A，选择数据库源名称b，点击流程保存
3.接口自动化流程启动，报错，原因是数据库源名称a 中无该表
4.重新编辑该流程，发现数据库源名称选中的默认是数据库源名称a，而不是之前保存的数据库源名称b(修改流程中的运行环境也会重置选中第一条数据库源名称a)

**期待的正确结果**
正确情况下应该是什么样的？
流程中，查询接口A，选择的数据库源名称b，保存，再次编辑时，应该还是选中的数据库源名称b，也不会因为编辑运行环境重新选中第一条数据库源名称a
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，会在后续版本修复这个问题

**Comment by zyyfit** [comment]
您好，最新版已修复，请升级使用
