### ISSUE TITLE
[BUG]直接编辑脑图信息并点击保存按钮，未成功保存

### ISSUE THREAD

**Issue by Arkycher** [metersphere/metersphere#3625]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
metersphere v1.10.0-b2

**Bug 描述**
简要描述您碰到的问题
1. 直接编辑脑图信息并点击保存按钮，未成功保存

**Bug 重现步骤**
1.  打开metersphere-测试跟踪-测试用例-用例列表-脑图页面
2.  直接编辑脑图信息并点击保存按钮
3.  此时弹出了保存成功的提示，但实际并未保存
4. 

**期待的正确结果**
正确情况下应该是什么样的？
1. 根据用户填写的内容，保存到脑图上

**截图**
如果有截图，请附上截图.
1. 简单看了下接口，目测是前端没有传参过来
![image](https://user-images.githubusercontent.com/50068735/121144333-77fe9f00-c870-11eb-8df7-ad93d8ebbc5f.png)
![image](https://user-images.githubusercontent.com/50068735/121144319-746b1800-c870-11eb-9eb1-f45d400910a3.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by Arkycher** [comment]
> 模块是不支持编辑的，用例才可以编辑

希望能够支持任意层级脑图的新增编辑功能，谢谢
