### ISSUE TITLE
[BUG]测试计划功能测试用例列表，点击“我的用例”后，按钮消失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3626]
**MeterSphere 版本**
v1.10.1

**Bug 描述**
测试计划的功能测试用例列表，点击“我的用例”后，按钮都消失了，切换菜单后，按钮又出来了

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
<img width="1439" alt="WechatIMG130" src="https://user-images.githubusercontent.com/32027713/121145380-7a152d80-c871-11eb-9a81-f1f9b7893137.png">

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
