### ISSUE TITLE
[FEATURE] 接口自动化下调试之后，显示内容会重叠

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3629]
**请描述您的需求或者改进建议.**
接口自动化下调试之后，显示内容会重叠
![WechatIMG875](https://user-images.githubusercontent.com/32027713/121150676-4f79a380-c876-11eb-8506-a4d5c7ba4e3d.png)

**请描述你建议的实现方案**
名称或者接口URL长度太长的可以做一下隐藏，显示错开一下

**Comment by xulinde** [comment]
感谢反馈，后面版本优化下

**Comment by xulinde** [comment]
10.3版本已优化
