### ISSUE TITLE
接口测试编辑界面，不能批量执行用例，只能单个调试，对有上下接口关联的场景不适用

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#363]
**请描述您的需求或者改进建议.**

写接口做调试 不适合页面来回跳转建议在接口执行界面上，直接选择场景下一键运行
另外在接口测试列表上新增执行入口，和报告入口。方便外面执行

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
v1.7.2 已支持场景一键运行，批量场景运行，报告单独入口查看
