### ISSUE TITLE
[BUG]定时任务创建后，操作按钮不显示

### ISSUE THREAD

**Issue by linch0312** [metersphere/metersphere#3631]
**MeterSphere 版本**
v1.10.1

**Bug 描述**
定时任务创建后，操作按钮不显示

**Bug 重现步骤**
1.  进行性能测试
2. 选择任意项目，任意测试
3. 点击SCHEDULER进入设置定时任务界面
4. 在任务通知中创建新通知

**期待的正确结果**
操作按钮可见，能够修改或删除（定时任务的按钮权限只控制到外层，当前界面未控制到）

**截图**

![image](https://user-images.githubusercontent.com/85554382/121163610-84d7be80-c881-11eb-92b6-c89429a7f59f.png)

**Comment by zyyfit** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
未复现该问题，建议您升级到最新版本在看下
