### ISSUE TITLE
[BUG]节点机，执行接口测试，出现异常，有截图。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#3640]
**MeterSphere 版本**
1.10.1

**Bug 描述**
2个场景接口，执行了30分钟，依然没有结果，**请问哪里可以看到 节点机器 执行的 日志状态？**

![image](https://user-images.githubusercontent.com/6467295/121278886-1f79e100-c906-11eb-83a8-0c95a9d48e49.png)

**Comment by seasoncool** [comment]
日志错误截图：
![image](https://user-images.githubusercontent.com/6467295/121616018-ab217800-ca94-11eb-9bb2-42d129a7a05b.png)

**Comment by seasoncool** [comment]
@xulinde 能帮忙看下 这个问题吗？ 如果是bug，请帮忙确认下就好，我们等下版本，如果有办法解决，也请告知呀。

**Comment by xulinde** [comment]
并行还是串行，大概有多少个请求，版本号是多少

**Comment by seasoncool** [comment]
@xulinde  谢谢您的回复。
并行与串行都有尝试过，结果一样，测试报告中的状态始终为：“Running”
请求数量为节点默认配置：“100”，也尝试过修改为：“1”，测试结果一样 ： “Runing”
测试： v1.10.1-60cc5c55

**Comment by xulinde** [comment]
v1.10.2版本已修复
