### ISSUE TITLE
认证方法增加aws认证

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#3642]
**请描述您的需求或者改进建议.**
postman包含众多的认证方法,目前ms只支持两种,希望能增加aws的支持
![image](https://user-images.githubusercontent.com/6682310/121286147-02e3a600-c912-11eb-978f-dc138a474210.png)

**请描述你建议的实现方案**
参考postman的实现

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by luty2018** [comment]
抱歉长时间未回复，扩展认证这块的功能我们计划放到v3.0做，可以继续关注哈。

**Comment by luty2018** [comment]
请问是否还有在继续使用， 是否还有这个认证需求？

**Comment by swpu-cxm** [comment]
请问有扩展认证有在v3.0开发计划中吗，现阶段的认证方式支持有点太少了，我这里也有aws认证功能的需求，谢谢
