### ISSUE TITLE
对接jira的问题，请帮忙看一下

### ISSUE THREAD

**Issue by yinmin2020** [metersphere/metersphere#3643]
**请描述您的问题.**
1.已经配置好jira并通过测试连接，但是添加缺陷后平台这里还是显示LOCAL是什么原因？
2.请问配置jira时需求类型选什么？
![image](https://user-images.githubusercontent.com/65068467/121286067-e6e00480-c911-11eb-8bdc-215143d3da4f.png)
**步骤复现：**
1.ms平台版本 V1.10.0
2.配置jira参数并通过测试，见图：
![image](https://user-images.githubusercontent.com/65068467/121286252-273f8280-c912-11eb-86fe-7fc0e089b8a2.png)
3.关联项目并添加权限，并在项目中正确配置了jira中的key值。但由于平台这里没有显示jira所以jira平台中并没有关联过去

**Comment by wangzhen-fit2cloud** [comment]
你好，请在编辑项目信息的位置，修改项目使用的缺陷模板选择对应的Jira缺陷模板。
