### ISSUE TITLE
[BUG] ！！带有自定义ID的用例，在测试计划中关联用例会报错。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3648]
**MeterSphere 版本**
1.10.1

用例中有自定义ID字段，且字段格式为：ABC-ABC-001  ，这种情况下关联测试用例，列表会报错。

![image](https://user-images.githubusercontent.com/44999044/121299970-beafd000-c928-11eb-8b3f-51d84a4bad39.png)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
