### ISSUE TITLE
[BUG]资源池不可用下无法停用性能测试任务

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#365]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
压测状态因某种测试一直在running中，对应的资源池被关闭后，去关停性能任务，无法关停
**Bug 重现步骤**
1.  压测执行
2. 手动关闭资源池上的node-controller
3. 页面上去停止性能任务
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by liuruibin** [comment]
停用性能测试会根据资源池的配置来关闭相关的容器
