### ISSUE TITLE
[BUG]跨項目引用場景時，導出自動化接口腳本用例到MeterSphere格式，然後再重新導入，引用的場景變成了複製，且運行環境缺少跨項目的環境

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#3650]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是 v1.10

**Bug 描述**
  跨項目引用場景時，導出自動化接口腳本用例到MeterSphere格式，然後再重新導入，引用的場景變成了複製，且運行環境缺少跨項目環境

**Bug 重现步骤**
1.  項目A 中的場景1引用了項目B中的場景2
2.  導出接口腳本用例到MeterSphere格式后，重新導入

**期待的正确结果** 
  重新導入后，項目A 中的場景應保持引用項目B中場景，且運行環境包含項目B的運行環境

**截图**
![image](https://user-images.githubusercontent.com/37204403/121304528-0a657800-c92f-11eb-918a-abe265ede830.png)

**Comment by zyyfit** [comment]
您好，由于导入功能不一定会导入同一个环境，所以我们修改了导入逻辑，如果您需要引用的话可以直接引用
