### ISSUE TITLE
[BUG]自动化测试数据源bug 

### ISSUE THREAD

**Issue by lishiyi11** [metersphere/metersphere#3657]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.0和1.10.1
**Bug 描述**
两个数据源选第二个一个执行，执行结束自动切换成第一个数据源了
简要描述您碰到的问题

**Bug 重现步骤**

1.  环境下设置两个数据源
2. 选择第二个点击保存--》执行
3. 
4. 

**期待的正确结果**
执行后依然是第二盒数据源
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，下个版本修复

**Comment by zyyfit** [comment]
最新版已修复
