### ISSUE TITLE
[FEATURE]测试用例能否从测集集合中抽离出来单独维护

### ISSUE THREAD

**Issue by Bearzzzzz** [metersphere/metersphere#366]
**请描述您的需求或者改进建议.**
测试场景：我们有开发、研发测试、测试三套环境要在流水线中运行同一批测试用例
按照当前metersphere的设计模式，我需要为三套环境维护三个测试集合，每个集合中的用例相同，然后将三个集合分别配置到三套环境对应的流水线中。在这种情况下，假如有接口变更了，需要修改用例，那么需要到三个测试集合中分别修改测试用例，使工作量加大。所以可否将用例单独维护呢。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
v1.6 新版接口测试  可分开维护接口、用例、测试场景，后续将会增加用例批量编辑功能
