### ISSUE TITLE
测试计划中场景自动化要支持串行和并行选择，手动批量执行是可选的，定时任务就不行

### ISSUE THREAD

**Issue by lxh3145** [metersphere/metersphere#3669]
**请描述您的需求或者改进建议.**

测试计划中场景自动化定时执行要支持串行和并行选择，因为测试计划才是实际应用中对用力进行管理、执行的主要功能，现在一直让自动化集成cicd，只有手动执行可选串并行明显不合适

**请描述你建议的实现方案**
串并行方法都已经有了，这里引用过来应该很好实现

**Comment by xulinde** [comment]
最新版本是支持该功能的，建议升级下版本～
![image](https://user-images.githubusercontent.com/64065190/121620801-88e02800-ca9d-11eb-81e2-2da3173186ed.png)
