### ISSUE TITLE
[BUG]后端服务 500 的情况下，前端提示为空

### ISSUE THREAD

**Issue by sunskblue** [metersphere/metersphere#367]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
本地启动的 MeterSphere，拉取的 master 代码

**Bug 描述**
简要描述您碰到的问题
后端服务 500 的情况下，前端提示为空
**Bug 重现步骤**
1.  启动前端，不启动后端
2. 访问http://localhost:8080/login
3. 报错 500，但是提示不直观

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/23308774/92430681-12d62a00-f1c8-11ea-9373-25765495522a.png)

**Comment by AgAngle** [comment]
最新代码已优化
