### ISSUE TITLE
[BUG]快速连续点击浏览器左上角的重新加载页面按钮（刷新），会出现错误提示“request aborted”

### ISSUE THREAD

**Issue by harry666666** [metersphere/metersphere#368]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
metersphere-chrome-plugin-v1.2.0
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
快速连续点击浏览器左上角的重新加载页面按钮（刷新），会出现错误提示“request aborted”

**期待的正确结果**
正确情况下应该是什么样的？
不要弹出这种提示，最好用户无感知。
**截图**
如果有截图，请
![request aborted](https://user-images.githubusercontent.com/39684915/92438001-97ca3f00-f1da-11ea-824f-e421a4f5e68c.jpg)
附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue
