### ISSUE TITLE
接口自动化--批量执行时，选择串行 独立展示报告，执行完了 查看报告详情报错 提示“Unexpected end of JSON input”

### ISSUE THREAD

**Issue by liangweijie99** [metersphere/metersphere#3680]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

版本:   v1.10.1-60cc5c55

**Bug 描述**

接口自动化--批量执行时，选择串行 独立展示报告，执行完了 查看报告详情报错 提示“Unexpected end of JSON input”

**Bug 重现步骤**

1.  进入接口自动化栏
2.  选择多个接口自动化场景
3.  批量执行
4.  选择串行 独立报告方式展示
5. 执行完毕后 查看报告详情

**期待的正确结果**

期待能正常查看报告详情。

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/74578958/121460213-288ab100-c9df-11eb-9d05-ee6dd0d608f2.png)

![image](https://user-images.githubusercontent.com/74578958/121460377-6d164c80-c9df-11eb-8e02-c2046e033c30.png)

![image](https://user-images.githubusercontent.com/74578958/121460453-85866700-c9df-11eb-8ab9-bf528b2aaa15.png)

![image](https://user-images.githubusercontent.com/74578958/121460542-a77fe980-c9df-11eb-9eda-b8c83a7e021f.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好。没有复现呢，请问是必现的吗

**Comment by liangweijie99** [comment]
是必现的

![image](https://user-images.githubusercontent.com/74578958/122008088-33807f80-cdeb-11eb-8e5e-0dd100251648.png)

**Comment by xulinde** [comment]
v1.10.2版本已修复
