### ISSUE TITLE
[BUG]接口定义中按钮点击位置偏移

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3681]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**
接口定义创建时保存、测试按钮点击范围偏移，鼠标放按钮正中间无法识别到按钮。
简要描述您碰到的问题

**Bug 重现步骤**

1.  进入接口点击保存按钮
2. 
3. 
4. 

**期待的正确结果**
按钮能够很容易被点击。

**Comment by zyyfit** [comment]
您好，请问您使用的是什么浏览器？推荐使用chrome浏览器，其他浏览器可能会出现兼容性问题
