### ISSUE TITLE
[BUG] MS安装过程中，因使用的是第三方数据库，第三方数据库表明加了区分大小写的限制，导致安装失败

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#3689]
**MeterSphere 版本**
V1.10.1

**Bug 描述**
安装过程中，因使用的是第三方数据库，第三方数据库表明加了区分大小写的限制，导致安装失败
1、比如最明显的USER这张表，创建的时候表名是小写的，实际在xml中SQL是大写的，
2、flyway 执行过程中调用存储过程，出现字符集问题
3、定时任务的表qrtz_开头的表名，系统默认调用为大写表名，实际创建表的时候却是小写的表名，导致系统启动失败
4、希望开发同学在开发过程中，尽可能规范一下，表名的大小写一致问题，字符集问题等等

随着用户越来越多，出现的情况也会越来越多，规范一点会减少很多不必要的问题，谢谢！！！

如果有截图，请附上截图.
<img width="1154" alt="WechatIMG1135" src="https://user-images.githubusercontent.com/32027713/121473319-1287eb00-c9f5-11eb-9ddc-cf86915aa691.png">

**Comment by wangzhen-fit2cloud** [comment]
你好，我们会规范下SQL的大小写。
同时在部署时请参考下文档中对于数据库配置的要求。
https://metersphere.io/docs/installation/online_installation/
![image](https://user-images.githubusercontent.com/27671436/121473922-ed47ac80-c9f5-11eb-875a-6e7506070adc.png)
