### ISSUE TITLE
[FEATURE]新建用例时，因为该弹出页面不是全屏的，很容易因为误点 弹窗以外的区域导致，用例输入框消失，用例白写了。

### ISSUE THREAD

**Issue by harry666666** [metersphere/metersphere#369]
**请描述您的需求或者改进建议.**
RT：新建用例时，因为该弹出页面不是全屏的，很容易因为误点 弹窗以外的区域导致，用例输入框消失，用例白写了

**请描述你建议的实现方案**
这个应该好实现哈。
![新建用例时，因为该弹出页面不是全屏的，很容易因为误点 弹窗以外的区域导致，用例输入框消失，用例白写了](https://user-images.githubusercontent.com/39684915/92438086-c47e5680-f1da-11ea-9108-012ca23ae5c0.jpg)

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> RT：新建用例时，因为该弹出页面不是全屏的，很容易因为误点 弹窗以外的区域导致，用例输入框消失，用例白写了
> 
> **请描述你建议的实现方案**
> 这个应该好实现哈。
> ![新建用例时，因为该弹出页面不是全屏的，很容易因为误点 弹窗以外的区域导致，用例输入框消失，用例白写了](https://user-images.githubusercontent.com/39684915/92438086-c47e5680-f1da-11ea-9108-012ca23ae5c0.jpg)

1.3版本已修复，请更新使用
