### ISSUE TITLE
接口定义中的入参及返参，能复制到mock设置里，避免每个mock都需要手动填入参和返参，感觉工作量好大

### ISSUE THREAD

**Issue by 342690538** [metersphere/metersphere#3693]
**请描述您的需求或者改进建议.**

接口定义中的入参及返参，希望能复制到mock设置里，避免每个mock都需要手动填入参和返参

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前支持复制的
![image](https://user-images.githubusercontent.com/64065190/121622529-c0040880-caa0-11eb-8631-ef38a48aa514.png)
