### ISSUE TITLE
关联jira 自定义字段支持修改

### ISSUE THREAD

**Issue by ali10180209** [metersphere/metersphere#3694]
关联Jira缺陷 自定义字段增加后不支持编辑

**Comment by xulinde** [comment]
后面版本可以优化下

**Comment by xulinde** [comment]
模版管理-自定义字段，是可以编辑的
![image](https://user-images.githubusercontent.com/64065190/121622298-58e65400-caa0-11eb-9fdb-c9a7c5e47187.png)
