### ISSUE TITLE
[FEATURE]增加角色权限对应关系

### ISSUE THREAD

**Issue by shorile** [metersphere/metersphere#37]
**请描述您的需求或者改进建议.**

几个角色和所对应的权限不明确，且中英文(viewer)混杂，需要提供响应的对应说明

**请描述你建议的实现方案**

建议设置页面中增加角色页，包含角色和权限对应的关系，并把角色名统一中文

**Comment by wangzhen-fit2cloud** [comment]
你好，已在文档中增加说明
