### ISSUE TITLE
[FEATURE]目前不支持基线测试用例和迭代更新测试用例

### ISSUE THREAD

**Issue by kouzhijian** [metersphere/metersphere#370]
**请描述您的需求或者改进建议.**
功能测试用例在迭代过程中，会形成基线测试用例和迭代测试用例。当版本代码合入主线后，功能测试用例应当能够合并，形成基线版本的测试用例。目前metersphere是按照项目划分，没有形成基线版本

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 功能测试用例在迭代过程中，会形成基线测试用例和迭代测试用例。当版本代码合入主线后，功能测试用例应当能够合并，形成基线版本的测试用例。目前metersphere是按照项目划分，没有形成基线版本
> 
> **请描述你建议的实现方案**

麻烦加入我们的交流群添加我的企业微信，可以跟你深入讨论一下这块的需求
