### ISSUE TITLE
[BUG]接口测试JSON-SCHEMA，array数据无法配置多个items

### ISSUE THREAD

**Issue by heshaol** [metersphere/metersphere#3730]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口测试-接口定义，请求体使用JSON-SCHEMA
2. 数据类型选择 array
3. 只能配置一个items

**期待的正确结果**

正确情况下应该是什么样的？
可以配置以下格式
"array": [
    {
      "id": "1",
      "name": "兴安盟"
    },
    {
      "id": "2",
      "name": "兴安盟"
    }
  ]

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前暂时不支持json-schema的多个array参数，后续版本是否支持还未确定
