### ISSUE TITLE
[FEATURE]测试用例导入时步骤信息中是否可以更改默认步骤描述

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3731]
**请描述您的需求或者改进建议.**
测试用例导入时步骤信息中默认为步骤描述，希望可以选择导入后是文本描述，现阶段只能手动更改后重新填写。
![image](https://user-images.githubusercontent.com/40912823/121627804-a36cce00-caaa-11eb-9659-8430ba133149.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
导出的时候是什么类型，默认导入的时候就是什么类型
