### ISSUE TITLE
[BUG]环境配置url无法配置包含参数的请求路径

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#3736]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**
系统--项目--环境配置url无法配置包含参数的请求路径，1.10.0版本可以正常使用
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问您环境配置是如何设置的，这边没有复现呢

![图片](https://user-images.githubusercontent.com/73461316/121642276-e3d84600-cac2-11eb-9c01-545bda9053af.png)

![图片](https://user-images.githubusercontent.com/73461316/121642200-c60ae100-cac2-11eb-923e-8b20fcc65cab.png)

**Comment by fangqiuhong** [comment]
![image](https://user-images.githubusercontent.com/18163887/122006702-b7d20300-cde9-11eb-9147-1032a87f9673.png)
原先是可以按照上图来做配置，现在输入这串地址后，鼠标离开输入框，问号之后的内容都会消失

**Comment by zyyfit** [comment]
> ![image](https://user-images.githubusercontent.com/18163887/122006702-b7d20300-cde9-11eb-9147-1032a87f9673.png)
> 原先是可以按照上图来做配置，现在输入这串地址后，鼠标离开输入框，问号之后的内容都会消失

您好，我看了1.10.0版本也是问号后面会消失的，环境域名暂时不支持带参数

**Comment by fangqiuhong** [comment]
这个功能后续能支持下？
