### ISSUE TITLE
[BUG] 升级至v1.2.1-b82后如果不清缓存登录admin用户会循环跳转

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#374]
**MeterSphere 版本**
升级前：v1.1.2-b76
升级后：v1.2.1-b82

**Bug 描述**
升级完成后刷新页面，通过admin管理员账号登录（该账号改过密码），登录后页面一直在/login/ 和/setting/personsetting/ 路径间切换，页面一直不停跳转

**Bug 重现步骤**
1.  确认升级完成
2. 输入本地部署域名，能正常打开登录页面，输入正确的admin用户名密码，点击【登录】
3.  登录成功，但页面一直在跳转，无法正常显示
4.  当通过浏览器把站点缓存清除后，页面才能正常展示

**期待的正确结果**
无需人为手动清空缓存，也能正常展示页面

**截图**
无法录屏，所以没有动图

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue

**Comment by pcc426** [comment]
> 你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue

已升级至1.4.0版本，暂时没有再复现，谢谢~
