### ISSUE TITLE
[FEATURE] 提交JIRA bug后缺陷ID应展示JIRA对应的Key-issueId

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#375]
**请描述您的需求或者改进建议.**
现在通过metersphere关联提交Jira bug后，metersphere这边显示的是创建成功后一个类似transaction-id之类的id，通过这个id很难在jira上找到对应的Issue, 如下图
![image](https://user-images.githubusercontent.com/11419548/92452289-72483000-f1f0-11ea-909e-1859e99da063.png)

**请描述你建议的实现方案**
希望能在ms这边也显示“projectKey-issueId" 这样结构的bug-id, 比如”**BSS-156**“， 这样能通过copyID直接到jira那边找到对应的bugIssue.

**Comment by zyyfit** [comment]
已优化
