### ISSUE TITLE
[FEATURE]平台集成的jira提交缺陷，当公司jira平台必填字段超出标题、描述和问题类型这三个字段时，提交缺陷失败

### ISSUE THREAD

**Issue by taoxuFreedomUP** [metersphere/metersphere#376]
**请描述您的需求或者改进建议.**
当前平台集成jira只支持标题、描述和问题类型这三个字段，如果公司jira平台的必传字段超过这个范围，会导致提交缺陷失败。

_**平台创建缺陷失败**_
![image](https://user-images.githubusercontent.com/45415529/92451866-e46c4500-f1ef-11ea-9c1d-60ef795ebaf9.png)

_**metersphere报错日志**_
![image](https://user-images.githubusercontent.com/45415529/92451818-d28aa200-f1ef-11ea-9f7f-7a72dc6b2341.png)

_**公司jira创建缺陷必填字段**_
![image](https://user-images.githubusercontent.com/45415529/92451905-f221ca80-f1ef-11ea-835a-ac07cc8be493.png)

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/45415529/92547211-fbaa4180-f286-11ea-9acf-327c02516afc.png)
![image](https://user-images.githubusercontent.com/45415529/92547267-18467980-f287-11ea-90ba-903a45dbdafb.png)

**Comment by youliyuan-fit2cloud** [comment]
和 #1102 问题相同，请持续关注～
