### ISSUE TITLE
[BUG]API中是否必填值在生成文档时为空

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#3764]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.1
**Bug 描述**

API中非必填值在生成文档时为空

**Bug 重现步骤**

1
填参数是选择非必填
![image](https://user-images.githubusercontent.com/6682310/121985660-c0194680-cdc7-11eb-9f18-dc9a53591346.png)

![image](https://user-images.githubusercontent.com/6682310/121985596-a11ab480-cdc7-11eb-9154-59b8d51b8f7b.png)

2. 
3. 
4. 

**期待的正确结果**
在生成文档时填否
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，下个版本修复

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
