### ISSUE TITLE
[BUG]开放配置如果选择jenkins 的话，正常是与插件运行的结果是没有关系的，但是应用却发布不了

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#377]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/37016695/92453223-935d5080-f1f1-11ea-98d2-5d6114239626.png)
![image](https://user-images.githubusercontent.com/37016695/92453236-96584100-f1f1-11ea-87ff-29e6256dc8c5.png)
![image](https://user-images.githubusercontent.com/37016695/92453251-9bb58b80-f1f1-11ea-9966-a5cd5f85b316.png)

**Bug 重现步骤**
1.  如图示，配置Jenkins后，运行结果和配置不一致
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue
