### ISSUE TITLE
[BUG]测试计划中选择接口测试用例，点击左侧场景用例单选框，该功能无法查询到用例数据，并且点击后该选项显示异常

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3771]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
1.10
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试计划中选择接口测试用例，点击左侧场景用例单选框
2. 该功能无法查询到用例数据，并且点击后该选项显示异常
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
正常查到场景用例数据
**截图**

如果有截图，请附上截图.
<img width="935" alt="11" src="https://user-images.githubusercontent.com/83771182/122011612-ddadd680-cdee-11eb-997a-b9cffe5a3ddf.png">

**Comment by zyyfit** [comment]
已知问题，下个版本修复

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用

**Comment by xulinde** [comment]
v1.10.2版本已修复
