### ISSUE TITLE
[BUG] 自定义目录安装meterSphere，升级v1.9.0-rc1版本时，挂在分区错误，致使所有用户，项目，用例，权限，接口定义的应用数据空白

### ISSUE THREAD

**Issue by RenZhiJu** [metersphere/metersphere#3773]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.0-93f6870d
**Bug 描述**

简要描述您碰到的问题
自定义目录安装meterSphere后，升级v1.9.0-rc1版本时，因MySQL的镜像由5.7.25升级至5.7.33版本，docker的volume加载分区未读取MS_BASE变量，致使挂载至空白分区，所有用户，项目，用例，权限，接口定义的应用数据空白
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
upgrade时，正确读取全局环境变量MS_BASE，兼容自定义安装目录的部署升级

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![WechatIMG1](https://user-images.githubusercontent.com/28860098/122014103-6b8ac100-cdf1-11eb-8912-39402d5d539f.png)
<img width="1126" alt="WechatIMG18" src="https://user-images.githubusercontent.com/28860098/122014181-7f362780-cdf1-11eb-8cce-13690bbd03a0.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，1.10.4版本已修复
