### ISSUE TITLE
[BUG] 测试报告没有按照执行顺序显示

### ISSUE THREAD

**Issue by HenryChen20181219** [metersphere/metersphere#3774]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建了两个场景，里面都是同一个test接口
2. 场景里引用了场景，有同名的场景时（因为有时候需要第二次执行该场景的相关接口）
3. 报告输出是同名的场景为一个总的，合并了前面执行和后面执行时的接口
4. 结果是：第一个引用 （里面两个test），第二个引用

**期待的正确结果**

正确情况下应该是什么样的？
应该按照执行顺序显示报告： 第一个引用 ，第二个引用， 第一个引用
**截图**
![1](https://user-images.githubusercontent.com/46012369/122014347-a7be2180-cdf1-11eb-821c-74b88dd7f977.png)
![2](https://user-images.githubusercontent.com/46012369/122014345-a7be2180-cdf1-11eb-896d-dca6ef4d0d23.png)
![3](https://user-images.githubusercontent.com/46012369/122014346-a7be2180-cdf1-11eb-8b2e-7b418465429a.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问您使用的是哪个版本？最新版1.10.1版本中已经修复了这个问题

**Comment by HenryChen20181219** [comment]
1.10.0

**Comment by zyyfit** [comment]
> 1.10.0

请升级一下试试

**Comment by zyyfit** [comment]
> 1.10.0

请升级一下试试，或者等1.10.2版本发布后升级到1.10.2

**Comment by zyyfit** [comment]
1.10.2版本已修复，请升级使用
