### ISSUE TITLE
[BUG]台发送得邮件中测试报告的链接需要登录账号后才能查看，期望链接可以免登录直接查看报告

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3780]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  平台发送得邮件中测试报告的链接需要登录账号后才能查看
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
期望链接可以免登录直接查看报告
**截图**

如果有截图，请附上截图.
<img width="784" alt="22" src="https://user-images.githubusercontent.com/83771182/122031737-8c5b1280-ce01-11eb-90b2-7419d2ab02d4.png">

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/2054 ，后续版本考虑一下解决方案
