### ISSUE TITLE
[BUG] 导入脚本中有setup线程组和tearDown线程组时候，设置的压测时长和实际差距太大

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3781]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 导入脚本中有setup线程组和tearDown线程组 时候，设置的压测时长和实际差距太大
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
运行时间应该和设置的时长一直

**截图**

如果有截图，请附上截图.
<img width="550" alt="33" src="https://user-images.githubusercontent.com/83771182/122035591-31c3b580-ce05-11eb-8529-681c79adde3a.png">
<img width="535" alt="44" src="https://user-images.githubusercontent.com/83771182/122035609-37b99680-ce05-11eb-856f-730a06e487aa.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，1.10.3版本已修复，请升级使用
