### ISSUE TITLE
[FEATURE]设置了邮箱SMTP后，建议支持自动发Jenkins构建的metersphere测试报告邮件给项目人员

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#379]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/37016695/92455237-010a7c00-f1f4-11ea-95de-b0368eb7c2fc.png)

![image](https://user-images.githubusercontent.com/37016695/92455254-0962b700-f1f4-11ea-8505-0c34b8e42812.png)

**请描述你建议的实现方案**
如图示

**Comment by xulinde** [comment]
您好，该需求已实现
![image](https://user-images.githubusercontent.com/64065190/107308486-b0a98a00-6ac3-11eb-9d78-f68c01378fda.png)
