### ISSUE TITLE
[FEATURE]接口测试能否支持rap2或者postman导入？

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#38]
**请描述您的需求或者改进建议.**
接口测试能否支持rap2或者postman导入？公司的接口都是在rap2上面，postman可以直接导入rap2的接口信息

**请描述你建议的实现方案**
接口测试支持rap2或者postman导入，rap2的格式为json

**Comment by wangzhen-fit2cloud** [comment]

Duplicate of #26

**Comment by wangzhen-fit2cloud** [comment]
从 postman 中导入功能将在 v1.1 中支持，rap2 的导入待规划。

**Comment by luty2018** [comment]
1.1 postman 导入已发布 请更新体验 rap2 的已规划待排期。
