### ISSUE TITLE
[BUG]使用源码安装，点击右上角关于，版本号不显示

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#380]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.1
**Bug 描述**
使用源码安装，点击右上角关于，版本号不显示

**Bug 重现步骤**
wget https://github.com/metersphere/metersphere/archive/master.zip
unzip master.zip
cd metersphere-master
mvn clean package
java -jar backend/target/backend-1.1.jar
java -jar 
然后访问 :8081口，发现
关于

https://metersphere.io
https://github.com/metersphere/metersphere
版本:
版本号没有显示

**期待的正确结果**
显示出版本号

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，该版本号信息是读取环境变量得到的，在我们打包的时候会将版本号写入部署包的环境变量配置中，源码部署的确实不会显示该版本号
