### ISSUE TITLE
[BUG]接口自动化报告接口顺序未一一对应

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3802]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**
口自动化报告接口顺序未一一对应如下图
循环控制器报告中的层级显示位置不正确
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/40912823/122186934-1cac5c80-cec1-11eb-932d-66467c8f655b.png)
![image](https://user-images.githubusercontent.com/40912823/122184633-feddf800-cebe-11eb-8c9f-bbed624c1ec0.png)
![image](https://user-images.githubusercontent.com/40912823/122187510-abb97480-cec1-11eb-8cfd-2e8c8b4ddd71.png)
![image](https://user-images.githubusercontent.com/40912823/122187729-e3c0b780-cec1-11eb-849a-4b37276ea8af.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
