### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#381]
**请描述您的问题.**
使用源码安装，功能测试能通过，但是性能测试中选择不了资源池，列表为空，在资源池页中点击启用禁用，提示，请问大概什么问题，怎么解决呢？
![状态校验失败](https://user-images.githubusercontent.com/6682310/92476991-6b321980-f212-11ea-889c-342e1ed78eaa.png)

**Comment by zyx2075257** [comment]
服务没连接上，看日志
