### ISSUE TITLE
[BUG]【测试跟踪】用例评审-脑图中不显示前置条件

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#3826]
您所使用的 MeterSphere 版本是？
v1.10

**Bug 描述**
用例评审-脑图中不显示前置条件

简要描述您碰到的问题

**Bug 重现步骤**
1.  创建用例评审
2. 添加用例
3. 脑图查看

**期待的正确结果**
脑图中展示的用例的全部信息（前置条件、步骤、备注等）

**截图**
![image](https://user-images.githubusercontent.com/49704984/122210579-605e9080-ced8-11eb-8544-c6a5b77249f1.png)

![image](https://user-images.githubusercontent.com/49704984/122210468-43c25880-ced8-11eb-96e2-16c7048b6500.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.10.2版本已修复
