### ISSUE TITLE
[FEATURE]测试用例支持添加自定义字段，备注里支持上传截图

### ISSUE THREAD

**Issue by xiangziyun2009** [metersphere/metersphere#383]
**请描述您的需求或者改进建议.**
1、测试用例支持扩展添加自定义字段配置，
2、测试用例备注里支持上传截图

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
您好，
1、测试用例支持扩展添加自定义字段配置----计划下个版本v1.8中支持该功能
2、测试用例备注里支持上传截图--最新版本中已实现
请您持续关注～
