### ISSUE TITLE
在项目管理页面点击项目跳转到对应的项目首页[FEATURE]

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#3832]
**请描述您的需求或者改进建议.**

项目管理页面点击项目跳转到对应的项目首页

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/80370956/122319282-fcc57900-cf52-11eb-8c55-23215e1b40f4.png)

**Comment by xulinde** [comment]
后面版本会加

**Comment by xulinde** [comment]
v1.11.0已支持
