### ISSUE TITLE
[BUG]修改用户报错：空指针

### ISSUE THREAD

**Issue by kouzhijian** [metersphere/metersphere#3834]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.0
**Bug 描述**
系统-用户中修改用户时，报错，如图，见详细日志
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![QQ截图20210617103118](https://user-images.githubusercontent.com/33210000/122322055-69db0d80-cf57-11eb-9284-86b609afecb2.png)
![QQ截图20210617103100](https://user-images.githubusercontent.com/33210000/122322062-6b0c3a80-cf57-11eb-94e9-fe6f9040f182.png)

如果有截图，请附上截图.

**Comment by kouzhijian** [comment]
[error.log](https://github.com/metersphere/metersphere/files/6666960/error.log)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我们先根据错误日志定位一下问题

**Comment by zyyfit** [comment]
您好，没有复现这个问题，我们先根据错误日志定位一下问题

**Comment by zyyfit** [comment]
您好，最新版1.10.6已修复，请升级到最新版使用
