### ISSUE TITLE
[QUESTION] 使用JMeter工具与MeterShpere 性能测试结果差异很大？

### ISSUE THREAD

**Issue by mcjoshua** [metersphere/metersphere#384]
**请描述您的问题.**

同样的脚本，在本地的Jmeter工具运行没有错误；但在metershpere中运行中失败率高了很多，性能也相对较差。

请问是什么情况

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前v1.7版本已有很大改进，请您更新到最新版本~
