### ISSUE TITLE
[QUESTION] Postgres support

### ISSUE THREAD

**Issue by eucariop** [metersphere/metersphere#3845]
will it be possible to support Postgres?

**Comment by eucariop** [comment]
something new db connection in postgres support?

**Comment by eucariop** [comment]
some news?

一些新闻？

**Comment by wangzhen-fit2cloud** [comment]
Sorry for the delay of replying, and we'll consider to add Postgres support in our next release.

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/145319301-a76af24d-ebd8-4429-ac06-3629de6cbbe5.png)
postgresql has been added as a database driver in the API Testing module.
If you want to use postgresql while installation, sorry we have no plan to do this by now.
