### ISSUE TITLE
[BUG]现在脚本是按事务名去存的，会出现重名就覆盖的情况，需要改为按脚本名去存储。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#3846]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**上传jmeter脚本到MS平台，会自动按事务名去存储，导致如果不去修改jmeter默认的事务名，新上传脚本后，旧的脚本就会被覆盖**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**
![image](https://user-images.githubusercontent.com/77324661/122326807-6e0b2900-cf5f-11eb-8b54-5a8c6e9add03.png)
![image](https://user-images.githubusercontent.com/77324661/122326906-9e52c780-cf5f-11eb-9ea0-3775258a3a0f.png)
![image](https://user-images.githubusercontent.com/77324661/122326985-baeeff80-cf5f-11eb-9271-f85fba2265a8.png)
![image](https://user-images.githubusercontent.com/77324661/122326983-ba566900-cf5f-11eb-96d0-7e6389590eb3.png)
![image](https://user-images.githubusercontent.com/77324661/122327000-c0e4e080-cf5f-11eb-8f57-c66138943c57.png)
**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，目前是按照测试计划名称创建的场景，由于考虑到改为按照脚本名称创建场景也会出现这种问题，我们内部讨论了一下暂时决定不修改这个问题
