### ISSUE TITLE
[BUG]性能测试开启RPS限制开关，刷新当前界面或再次重新进入界面，按钮为关闭状态

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#385]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  性能测试脚本开启RPS限制开关，刷新当前界面或做其他保存操作再次重新进入该脚本界面，按钮为关闭状态

**期待的正确结果**
正确情况下应该是什么样的？--按钮应该为保存后的开启状态

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，修改的配置变更需要点击保存按钮后才会保存下来。
