### ISSUE TITLE
[BUG]Jenkins执行测试计划，最后返回结果没有测试计划报告链接

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#3854]
**请描述您的需求或者改进建议.**
希望Jenkins运行完成后，返回结果有测试计划报告链接

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
后面可以优化

**Comment by xulinde** [comment]
最新版本的jenkins插件已支持，建议您将插件版本更新到最新版本体验下
