### ISSUE TITLE
[BUG]场景添加事务控制器，执行报错

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#3855]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
  v1.10.1
**Bug 描述**

简要描述您碰到的问题
    场景添加事务控制器，执行报错
**Bug 重现步骤**
1.  场景添加中添加事务控制器 运行脚本

**期待的正确结果**
运行成功

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/37204403/122348849-29db5100-cf7e-11eb-811d-1aec588b6952.png)
![image](https://user-images.githubusercontent.com/37204403/122348873-319af580-cf7e-11eb-9060-7ef54014fdef.png)

**Comment by xulinde** [comment]
v1.10.2版本已修复
