### ISSUE TITLE
[BUG]场景自动化，导入sql用例，一个环境中指定了两个数据源，场景中有sql接口，选择了第二个数据源，场景运行后，sql的数据源选择会被清空，或者被选择成第一个数据源。没有正确保存上

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#3857]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.1

**Bug 描述**

场景自动化，导入sql用例，一个环境中指定了两个数据源，场景中有sql接口，选择了第二个数据源，场景运行后，sql的数据源选择会被清空，或者被选择成第一个数据源。没有正确保存上

简要描述您碰到的问题

**Bug 重现步骤**
1.  场景自动化，导入sql用例
2. 一个环境中指定了两个数据源，场景中有sql接口，选择了第二个数据源，场景运行后，sql的数据源选择会被清空，或者被选择成第一个数据源。没有正确保存上
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
切换的第二个数据源 应该能保存上。
**截图**
![image](https://user-images.githubusercontent.com/30038088/122354109-45952600-cf83-11eb-9150-0487e47e298f.png)

点击保存

再点击刷新，数据源 又变成 原先的了
![image](https://user-images.githubusercontent.com/30038088/122354325-77a68800-cf83-11eb-9782-5e5a008844f3.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.10.2版本中已修复这个问题，请升级使用，另外，现在的版本调试不会自动保存了，需要手动保存一下脚本

**Comment by shenkaibo** [comment]
赞
