### ISSUE TITLE
[BUG]性能测试报告不准确

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#386]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
性能测试报告不准确
**Bug 重现步骤**
1.  完成性能测试，请求统计、错误记录中记录的请求数量不一致
如图所示：请求统计一栏中没有包含所有的请求

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33714230/92561884-9d418b00-f2a7-11ea-91c3-63c2649eb638.png)
![image](https://user-images.githubusercontent.com/33714230/92561909-a7638980-f2a7-11ea-85c2-61015bbc36a2.png)

**Comment by liuruibin** [comment]
看图片显示开始时间为0，显示成了1970年，能不能把jmx文件提供给我们
