### ISSUE TITLE
[FEATURE]接口测试这块不支持jmeter 脚本的上传

### ISSUE THREAD

**Issue by paul-wanghr** [metersphere/metersphere#389]
**请描述您的需求或者改进建议.**
接口测试这块不支持jmeter 脚本的上传
理由:项目的历史脚本不能使用平台进行维护，所以最好提供上传jmx上传的口，这样就能新旧脚本公用一个管理平台了

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已采纳您的建议，计划下个版本实现，请您持续关注～

**Comment by xulinde** [comment]
v1.8已实现
