### ISSUE TITLE
[BUG]测试计划与测试报告的问题合集

### ISSUE THREAD

**Issue by TaoJiandong** [metersphere/metersphere#3892]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**

简要描述您碰到的问题

**1**.测试计划模块用户名相关字段显示不统一的问题：
1）负责人字段，在测试计划列表中显示的userName,在测试报告中显示userId，建议全部统一成显示userName
2）测试计划关联的测试用例列表，执行人字段显示userName，测试报告中执行人显示userId，建议全部统一成显示userName
3）测试计划关联的测试用例列表，责任人字段显示userId，测试用例详情中责任人字段显示“userId(userName)”，建议全部统一成显示userName
**2**.测试计划关联测试用例流程，发现现在的行为是谁执行关联操作，谁就是执行人，按照常理，执行人应当默认是用例的责任人
**3**.测试评审模块→测试用例列表→测试用例详情页面，用例状态取错了值，展示了评审结果'Pass,Unpass(通过，未通过)，请明确这里展示的是用例状态还是评审结果
**4**.测试计划列表会针对每一条记录去调用测试计划创建人对应的用户信息，记录一多会暴露接口性能问题，导致测试计划列表创建人字段的值不能及时刷新，建议在测试计划列表接口中直接返回creatorName

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化，其中第2条可能会有用例责任人不执行用例的情况，我们内部讨论一下该怎么优化
