### ISSUE TITLE
[BUG] 升级1.10.2后，发现用例评审、测试计划的内容丢失

### ISSUE THREAD

**Issue by Hitoria** [metersphere/metersphere#3893]
**MeterSphere 版本**
1.10.2-b5

您所使用的 MeterSphere 版本是？
v1.10.2-b5

**Bug 描述**

从之前的版本通过执行  msctl ugrade  命令进行升级，升级后发现”用例评审“、”测试计划“的各项内容为空

**Bug 重现步骤**

1.  在服务器执行  msctl ugrade  命令
2. 升级完成后，版本为1.10.2
3. 进入系统，进入之前发起、执行过的”用例评审“和”测试计划“项
4. 此时发现，先前关联过的用例消失，内容为空
5. 另外，”测试计划“的结束时间被置为了升级结束时间。

**期待的正确结果**
升级后可以正常显示以前的评审内容、关联的用例、执行的进度等

**截图**
![image](https://user-images.githubusercontent.com/39207507/122501905-26040900-d028-11eb-9294-fef80ea51586.png)
![image](https://user-images.githubusercontent.com/39207507/122501992-5055c680-d028-11eb-9aa4-d582665d5eb9.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这边没有复现这个问题，我们会继续跟踪一下这个问题的
