### ISSUE TITLE
[BUG]测试评审流程问题合集

### ISSUE THREAD

**Issue by TaoJiandong** [metersphere/metersphere#3894]
**MeterSphere 版本**

>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1

以下问题在交流群里提出过，提个issue作为留档
**Bug 重现步骤**

**1**.测试评审任务通知配置中把评论通知的接收人设置为了维护人，发现无论是谁发起了评论，评论通知邮件里都显示是用例维护人发起了评论。预期是评论通知邮件中显示**评论人**发起了评论。
 
**2**.在测试用例模块针对评审不通过的用例做修改，然后直接在编辑用例页面发评论，发现发送的通知邮件里，给出的链接是http://{host}/#/track/review/view/未设置,如果在用例编辑页面取不到reviewId，应当直接留空，即http://{host}/#/track/review/view/。
 
**3**.能否澄清一下现在用例评审的状态翻转，什么时候会翻到已完成，目前观察的现象是，所有的评审用例都有评审结果(通过，不通过)，整个评审状态就会翻转到已完成并发出用例评审完成的通知。但是在这种情况下后续更新未通过评审的用例状态，会重复发已完成通知。
**两种修复方案：**
1.类似于测试计划的状态翻转，只有评审全部通过才翻转成已完成，如果有通过+不通过=用例总数，状态可以翻成已结束。做出区分
2.简单屏蔽掉已完成消息的重复发送，如果这个状态是一个终态的话。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
