### ISSUE TITLE
[FEATURE]【接口测试】批量执行建议

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#390]
**请描述您的需求或者改进建议.**
接口测试批量执行后的集合场景，不要和原来的接口放在一起，或者只生成报告，不生成新的集合用例，目前每次都会生成在列表，但是又不会随着接口变动更新，每次执行还是会重新选择，单独放在一个地方作为版本记录还可以，但是放在接口里面会干扰操作

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，建议已采纳，请更新到较新版本～
