### ISSUE TITLE
[BUG] 性能测试自定义变量没有正确被替换

### ISSUE THREAD

**Issue by vision-ken** [metersphere/metersphere#391]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.0
**Bug 描述**
简要描述您碰到的问题
单笔的接口测试，能自动生成随机借据号。但是根据这个接口测试用例生成的性能测试，这个变量就没有正确替换，还是代码本身。

**Bug 重现步骤**
1.  在接口测试中新建一个场景和一个接口测试用例（POST）。
2. 在该场景中新建一个自定义变量dueNum，值为@string("number", 30, 30)。
3. 在接口测试用例的json请求报文里面引用该自定义变量："dueNum": "${dueNum}",
4. 运行该接口测试用例，测试可以成功，${dueNum}被替换为随机数字。
5. 根据接口测试场景新建性能测试。
6. 运行该性能测试，发现接口调用时，没有正确生成dueNum的自定义变量值，json请求报文中该值为：
"dueNum": "@string("number", 30, 30)",

**期待的正确结果**
正确情况下应该是什么样的？
在性能测试的json请求报文中正确生成自定义变量值。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/24715266/92614334-83776680-f2ee-11ea-8989-a932a03e4ff3.png)

![image](https://user-images.githubusercontent.com/24715266/92614415-99852700-f2ee-11ea-87f3-d410ffae12d6.png)

性能测试时服务端接收到的报文：
![image](https://user-images.githubusercontent.com/24715266/92614944-2cbe5c80-f2ef-11ea-955b-044d6eda0023.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，目前 @string 形式的方法只可以在接口测试中使用，如果需要运行性能测试，建议使用类似 ${__Random}形式的 JMeter 内置函数
