### ISSUE TITLE
[BUG]jira中已关联的issue删除后报错

### ISSUE THREAD

**Issue by HaneWu** [metersphere/metersphere#3910]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 关联jira项目
2. 在用例中创建缺陷，并提交至jira
3. 在jira中删除已关联的缺陷
4. 在缺陷列表 or 用例模块查询缺陷列表 报错

**期待的正确结果**

正确情况下应该是什么样的？
metersphere中删除这条关联记录

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/50281663/122531385-04b81280-d052-11eb-8fc9-c2f6329823c6.png)
日志：
![image](https://user-images.githubusercontent.com/50281663/122531433-113c6b00-d052-11eb-9c66-0e272422744d.png)
![image](https://user-images.githubusercontent.com/50281663/122531455-17324c00-d052-11eb-98a2-7eafc1453224.png)

**Comment by zyyfit** [comment]
相似问题：
https://github.com/metersphere/metersphere/issues/3568

**Comment by xulinde** [comment]
v1.11.0已修复
