### ISSUE TITLE
测试用例无法批量移动

### ISSUE THREAD

**Issue by XinqiYu** [metersphere/metersphere#3919]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.2-abc39884
**Bug 描述**

测试用例无法批量移动到其他目录下面
**Bug 重现步骤**

1.  全选测试用例
2. 点击批量移动
3. 选择对应文件夹，报错

**期待的正确结果**

正确情况下应该是什么样的？
移动成功
**截图**
![image](https://user-images.githubusercontent.com/26948634/122536291-f5879380-d056-11eb-8b20-449ffb963445.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4已修复
