### ISSUE TITLE
[FEATURE]测试计划明细表格中支持按照所属模块和执行人筛选

### ISSUE THREAD

**Issue by eixxie** [metersphere/metersphere#392]
**请描述您的需求或者改进建议.**
测试计划明细表格中支持按照所属模块和执行人筛选，特别是按执行人筛选是经常用到的

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已实现该需求，请更新到较新版本～
