### ISSUE TITLE
[BUG] 3.0 openapi 导入报解析错误

### ISSUE THREAD

**Issue by phpmaple** [metersphere/metersphere#3923]
这边是 json 文件
[ada.json.zip](https://github.com/metersphere/metersphere/files/6676240/ada.json.zip)

**Comment by zyyfit** [comment]
您好，请问这是postman文件还是swagger文件？是导入接口定义还是场景？这边导入postman文件和swagger文件都没有报错

**Comment by phpmaple** [comment]
swagger 3.0, @zyyfit 我 metersphere 版本是 v1.10.1-60cc5c55

**Comment by xulinde** [comment]
我试了下是可以导入成功，导入不成功应该是接口重复了，这几个是 petstroe的接口，可能跟当前项目的重复了
