### ISSUE TITLE
[BUG] 接口自动化测试-前一个接口提取的参数 未在下面的条件控制器中生效

### ISSUE THREAD

**Issue by Shorelinewang** [metersphere/metersphere#3927]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在接口自动化中创建一个场景
2. 复制了一个登录接口，并且参数提取token
3. 然后添加了一个条件控制器 条件是判断 ${token} 非空的话 就执行条件控制器中的内容

**期待的正确结果**
执行条件控制器中的内容

**截图**
![image](https://user-images.githubusercontent.com/45869515/122549297-e90a3780-d064-11eb-949b-d5f879ebff9d.png)

![image](https://user-images.githubusercontent.com/45869515/122549402-0212e880-d065-11eb-9ea2-901ba964c3f9.png)
![image](https://user-images.githubusercontent.com/45869515/122549445-10f99b00-d065-11eb-9342-721b2d4bfb89.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by zyyfit** [comment]
1.10.3已修复，请升级使用
