### ISSUE TITLE
[BUG]1：:测试跟踪->用例评审→关联用例界面，评审结果无法筛选出“未评审”、“未通过”状态的用例 

### ISSUE THREAD

**Issue by niu378875091** [metersphere/metersphere#3933]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  进入测试跟踪 用例评审模块
2. 点击关联用例
3. 搜索模式按照评审结果筛选
4. 结果并不能按照选择的评审结果进行筛选

**期待的正确结果**
能按照所选择的筛选条件，进行查询

**截图**
![image](https://user-images.githubusercontent.com/86141364/122632154-89af3480-d103-11eb-8525-ca6def4fdf59.png)

**Comment by niu378875091** [comment]
> 您所使用的 MeterSphere 版本是？
>   v1.10.2-abc39884


> **Bug 描述**
> 测试跟踪->用例评审→关联用例界面，评审结果无法筛选出“未评审”、“未通过”状态的用例

> **Bug 重现步骤**
> 1. 进入测试跟踪 用例评审模块
> 2. 点击关联用例
> 3. 搜索模式按照评审结果筛选
> 4. 结果并不能按照选择的评审结果进行筛选
> 
> **期待的正确结果**
> 能按照所选择的筛选条件，进行查询
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/86141364/122632154-89af3480-d103-11eb-8525-ca6def4fdf59.png)

**Comment by zyyfit** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
1.10.4已修复
