### ISSUE TITLE
[FEATURE]接口测试报告和调试结果中看不到提取变量返回的值

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#394]
**请描述您的需求或者改进建议.**
接口测试报告和调试结果中看不到提取变量返回的值

**请描述你建议的实现方案**
建议在结果中增加提取变量的查看，否则调试时无法确认，提取到的值是否正确

**Comment by xulinde** [comment]
您好，平台已经优化了这里，响应中可以看到提取的值，您可以升级到最新版本体验下
