### ISSUE TITLE
[BUG]用例评审，点击ID排序报错

### ISSUE THREAD

**Issue by 462548187** [metersphere/metersphere#3940]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**
创建用例评审，点击ID排序报错
注：我创建的用例中有自定义字段

**截图**
![image](https://user-images.githubusercontent.com/23581094/122677596-93c15800-d215-11eb-915c-80dc8774aed6.png)

![image](https://user-images.githubusercontent.com/23581094/122677579-8310e200-d215-11eb-8594-a8d43601395c.png)

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，下个版本修复

**Comment by zyyfit** [comment]
1.10.3已修复，请升级使用
