### ISSUE TITLE
[BUG]脚本提供的vars.put(${__metersphere_env_id}+"key","value")，在使用的时候不是最新值

### ISSUE THREAD

**Issue by sky1984** [metersphere/metersphere#3941]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建登录接口，获取返回的token
2. 通过后置脚本设置token为环境参数new_token
3. 创建场景1，里面的接口是登录和查询
4. 查询的请求头使用环境参数token
5. 执行场景1

测试结果：
查询接口查询失败，原因token不正确，从运行结果得知，查询使用的是上个保存的token不是每次场景中登录生成的新token
（同理放在http默认请求头通过$(new_token)）,这样的引用形式token值也不是最新的

**期待的正确结果**
每次运行，都是使用最新的值

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5已修复
