### ISSUE TITLE
[BUG]swagger2.0导入到metersphere后格式信息有丢失

### ISSUE THREAD

**Issue by lcwus2** [metersphere/metersphere#3948]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2

**Bug 描述**

简要描述您碰到的问题
swagger2.0导入到metersphere里遇到两个问题：
1.接口信息里query参数有必填和非必填，选择了必填后在文档里并没有标示
2.原接口中返回数据里有部分结构，导入到ms之后就丢失了

**Bug 重现步骤**
1.接口信息里query参数有必填和非必填，选择了必填后在文档里并没有标示
![企业微信截图_16242449825228](https://user-images.githubusercontent.com/30100640/122702049-2fd47900-d281-11eb-91e9-c03d1b5053a3.png)
![image](https://user-images.githubusercontent.com/30100640/122702076-3b27a480-d281-11eb-87cf-8ce2478dea5d.png)

2.原接口中返回数据里有部分结构，导入到ms之后就丢失了
![image](https://user-images.githubusercontent.com/30100640/122702148-585c7300-d281-11eb-861c-12973666cbab.png)
![企业微信截图_16242441214242](https://user-images.githubusercontent.com/30100640/122702163-5f838100-d281-11eb-9043-1a7638f77a5e.png)

**期待的正确结果**

导入之后能正确显示

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，第1 个问题1.10.2已经修复过了，可以清缓存再试一下，第2个问题后续版本修复

**Comment by AgAngle** [comment]
swagger 文件里有这个响应的详细数据吗？我看导进来这个响应体有一些结构了，是否方便将swagger文件发来看下，可以交流群联系

**Comment by syq7970** [comment]
我也遇到导入swagger后响应体丢失的问题，版本1.10.2，之前的版本不会丢失。

**Comment by lcwus2** [comment]
> swagger 文件里有这个响应的详细数据吗？我看导进来这个响应体有一些结构了，是否方便将swagger文件发来看下，可以交流群联系

有一定的结构，但丢失了一部分。

"responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "object",
              "properties": {
                "data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "comment": {
                        "type": "null"
                      },
                      "component": {
                        "type": "string"
                      },
                      "created_date": {
                        "type": "string"
                      },
                      "filename": {
                        "type": "string"
                      },
                      "id": {
                        "type": "number"
                      },
                      "install_type": {
                        "type": "string"
                      },
                      "last_updated_date": {
                        "type": "string"
                      },
                      "md5": {
                        "type": "string"
                      },
                      "size_unzip": {
                        "type": "number"
                      },
                      "size_zip": {
                        "type": "number"
                      },
                      "version_new": {
                        "type": "string"
                      },
                      "version_old": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "comment",
                      "component",
                      "created_date",
                      "filename",
                      "id",
                      "install_type",
                      "last_updated_date",
                      "md5",
                      "size_unzip",
                      "size_zip",
                      "version_new",
                      "version_old"
                    ]
                  }
                },
                "error_code": {
                  "type": "number"
                },
                "error_msg": {
                  "type": "string"
                },
                "timestamp": {
                  "type": "number"
                }
              },
              "required": [
                "data",
                "error_code",
                "error_msg",
                "timestamp"
              ]
            }
          }
        }

**Comment by xulinde** [comment]
1.10.4版本已修复
