### ISSUE TITLE
[BUG] 性能测试报告无法删除

### ISSUE THREAD

**Issue by kpswen** [metersphere/metersphere#3949]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  删除性能测试任务
2. 删除测试任务对应的测试报告
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/47204651/122702492-1253df00-d282-11eb-95e1-e9463cd525a3.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.10.3版本已修复，请升级使用
