### ISSUE TITLE
[BUG]接口转性能测试，执行异常

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#395]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
接口配置的是一个场景里面有两个接口有上下接口参数引用，创建性能测试 一直100%error 拿出来jmx看下 直接是异常的

**Bug 重现步骤**
1.  接口里配置一个场景下两个接口，接口之间有参数传递
2. 创建性能测试 执行性能测试
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70927987/92693962-e9103500-f378-11ea-8331-5c9c81237cc1.png)

**Comment by kevinlee114** [comment]
另外jmx已经异常下 ，执行性能测试没有报错，而是错误率100%。建议执行时前需要判断脚本文件是否正常

**Comment by nawentao** [comment]
> 另外jmx已经异常下 ，执行性能测试没有报错，而是错误率100%。建议执行时前需要判断脚本文件是否正常

你的jmx脚本是自己写的，还是平台生成的，看提示像是较老的jmeter版本没有包含json提取器导致

**Comment by kevinlee114** [comment]
> > 另外jmx已经异常下 ，执行性能测试没有报错，而是错误率100%。建议执行时前需要判断脚本文件是否正常
> 
> 你的jmx脚本是自己写的，还是平台生成的，看提示像是较老的jmeter版本没有包含json提取器导致

脚本是通过平台接口测试配置生成的

**Comment by nawentao** [comment]
> > > 另外jmx已经异常下 ，执行性能测试没有报错，而是错误率100%。建议执行时前需要判断脚本文件是否正常
> > 
> > 
> > 你的jmx脚本是自己写的，还是平台生成的，看提示像是较老的jmeter版本没有包含json提取器导致
> 
> 脚本是通过平台接口测试配置生成的

你截图是在自己服务器上单独部署的jmeter吧，3.2版本估计太老，换下5.0.0以上版本试试(测试平台默认集成5.2.1的jmeter)

**Comment by kevinlee114** [comment]
额 这个是从你们容器里拷贝出来的的 之前说用0.0.8版本用的就是这个
![image](https://user-images.githubusercontent.com/70927987/92697692-27f4b980-f37e-11ea-8c37-23a0ef5f9a17.png)

**Comment by wangzhen-fit2cloud** [comment]
在平台报告的错误记录中的错误信息是什么呢

**Comment by kevinlee114** [comment]
Non HTTP response code: org.apache.http.conn.HttpHostConnectException  都是这种错误

**Comment by kevinlee114** [comment]
Non HTTP response code: org.apache.http.conn.HttpHostConnectException

**Comment by kevinlee114** [comment]
根源是你们给的jmeter镜像里jmeter版本是3版本的，不是5以上的版本

**Comment by kevinlee114** [comment]
Non HTTP response code: org.apache.http.conn.HttpHostConnectException

**Comment by JFRabbit** [comment]
> Non HTTP response code: org.apache.http.conn.HttpHostConnectException

@kevinlee114 这个报错应该是你接口调用的网络不通
