### ISSUE TITLE
[BUG]用户不绑定项目时，点击操作日志按钮，界面报错

### ISSUE THREAD

**Issue by gaoqijun** [metersphere/metersphere#3952]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by gaoqijun** [comment]
![image](https://user-images.githubusercontent.com/19400069/122704292-f3efe280-d285-11eb-8a30-dd6778ec8daa.png)

**Comment by zyyfit** [comment]
您好，没有复现呢，这个用户都有什么权限呀？

**Comment by zyyfit** [comment]
您好，没有复现呢，这个用户都有什么权限呀？

**Comment by gaoqijun** [comment]
这个问题是由于我下载的Dev代码，当时，Realese版本已解决

在 2021-06-21 20:05:16，zyyfit ***@***.***> 写道：


您好，没有复现呢，这个用户都有什么权限呀？
