### ISSUE TITLE
jmeter脚本登录用户名的或者密码使用特殊字符时，导入后不能自动自动转码

### ISSUE THREAD

**Issue by gaoqijun** [metersphere/metersphere#3955]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没太理解您的意思，能截图说明一下吗？是jmeter里写的特殊字符，导入后变成乱码了吗？

**Comment by gaoqijun** [comment]
你好，导入后不会乱码

在 2021-06-22 17:29:25，zyyfit ***@***.***> 写道：


您好，没太理解您的意思，能截图说明一下吗？是jmeter里写的特殊字符，导入后变成乱码了吗？

**Comment by zyyfit** [comment]
> 你好，导入后不会乱码 在 2021-06-22 17:29:25，zyyfit ***@***.***> 写道： 您好，没太理解您的意思，能截图说明一下吗？是jmeter里写的特殊字符，导入后变成乱码了吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

现在是没有问题了吗？还有问题的话可以截图说明一下
