### ISSUE TITLE
[BUG]浏览器插件录制的脚本导入到测试平台后，接口顺序发生变化

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#396]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
浏览器插件录制的脚本导入到测试平台后，接口顺序发生变化

**Bug 重现步骤**
1.  用浏览器录入多个http请求操作并保存为json
2. 查看json请求中的接口顺序，然后导入到测试平台，观察顺序

**期待的正确结果**
接口顺序与录制时保持一致

**截图**
如果有截图，请附上截图.

**Comment by q4speed** [comment]
插件导出的顺序没有变化，修复了接口测试的导入时顺序错误的bug
