### ISSUE TITLE
[BUG] 测试跟踪三个用例列表，使用ID排序时，报错。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#3960]
**MeterSphere 版本**
1.10.2

自定义ID：格式为   ABC-ABC-001

![image](https://user-images.githubusercontent.com/44999044/122714212-8948a200-d299-11eb-8371-abaf5cce7f69.png)

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/3960，下个版本修复

**Comment by zyyfit** [comment]
1.10.3已修复，请升级使用
