### ISSUE TITLE
[BUG]脚本包含setUp与tearDown线程组运行时，平台页面上线程组设置的参数与info.log下载下来的jmx不一致

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3961]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
1.10.2
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
脚本包含setUp与tearDown线程组运行时，平台页面上线程组设置的参数与info.log下载下来的jmx不一致
设置自动停止开启也无法自动停止脚本
**Bug 重现步骤**

1.  脚本包含setUp与tearDown线程组运行时
2. 平台页面上setUp、tearDown线程组与线程组，都设置的在1秒内增加并发用户开始运行
3. node-controller的info.log下载jmx
4. 发现setUp线程组设置与页面一致，但是tearDown线程组与线程组的Ramp-up时间页面设置的1，下载的jmx里面显示的是10
5.设置自动停止开启也无法自动停止脚本
**期待的正确结果**

正确情况下应该是什么样的？
但是tearDown线程组与线程组的Ramp-up时间应与页面设置的值一致
设置自动停止开启后脚本能自动停止
**截图**
<img width="896" alt="111" src="https://user-images.githubusercontent.com/83771182/122714738-61a60980-d29a-11eb-8182-f19260ffd381.png">
如果有截图，请附上截图.
脚本附件
[线程组实验.zip](https://github.com/metersphere/metersphere/files/6684425/default.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.10.3版本已修复
