### ISSUE TITLE
[BUG]接口编辑页面无法保存

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#397]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
接口编辑页面无法保存，js报错

**Bug 重现步骤**
1.  从测试报告的接口链接进入接口编辑页面
2. 直接点击保存按钮

**期待的正确结果**
能够保存成功

**截图**
<img width="827" alt="WechatIMG1455" src="https://user-images.githubusercontent.com/21210217/92856611-37c7d880-f426-11ea-977a-7971b23f488b.png">

**Comment by AgAngle** [comment]
该问题已修复，请升级至1.3以上版本
