### ISSUE TITLE
[BUG] 响应时间图时间横轴刻度不匀

### ISSUE THREAD

**Issue by goteen** [metersphere/metersphere#3972]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.0-93f6870d
如果没有处理过这个问题，估计最新的版本也有。

**Bug 描述**
有次压测，发现响应时间图（4个图都有这个问题，这里只举例响应时间图）时间横轴刻度不匀。
1、MeterSphere显示：
![image](https://user-images.githubusercontent.com/42863606/122731122-8e175100-d2ad-11eb-87ea-b999f4770e63.png)
2、Jmeter显示：
![image](https://user-images.githubusercontent.com/42863606/122731159-94a5c880-d2ad-11eb-9190-97b685d70a9a.png)
3、在MeterSphere的图里，最后3个点，从 14:32:45 到 14:35:30，共165秒，而前面几十个点是从 14:29:50 到 14:32:45，共175秒，最终得到的报告容易让人忽略这个问题。
4、你们这个很像是根据请求数的分布来设置时间横轴的刻度的，从每段时间间隔里的请求数量来看，是比较均匀的，但从时间来看，就不均匀了，因为有的请求在经过一段时间的连续请求后，响应时间上升，TPS下降是比较正常的情况，这次是因为出现了一个比较极端例子，才发现这个刻度问题影响很大。

**Bug 重现步骤**
1、设计一个请求，正常情况下响应时间为3秒，但在某个时间段的响应时间为60秒，压测的时候覆盖这两种时间段（猜想的，我没有时间单独设计这种请求）

**期待的正确结果**
1、如果横轴是根据请求数在时间上的分布均匀划分的话，希望增加一个选项，可以选择按照时间均匀分布，这两种情况感觉可能都用得到。

**Comment by zyyfit** [comment]
感谢反馈，我们内部讨论一下处理方案

**Comment by zyyfit** [comment]
您好，ms的报告是根据最终的jtl计算的，中间有可能某个时刻没有数据，显示结果图形是图是echart根据测试结果自动计算的，而jmeter自己的实时报告会把当前时刻保留下来 即使这个时刻没有采样结果。

**Comment by goteen** [comment]
这样的话，虽然图看起来更均匀，更美观，但是容易让我们忽略中间的长时间响应的情况，容易当成偶发情况，加上Jmeter本身就容易出现一组压测快结束时响应时间突然上升的情况，和这个容易混淆。现在还需要我们仔细检查报告是否存在时间轴刻度不匀的情况，然后在报文里单独说明，就比较麻烦。
