### ISSUE TITLE
[BUG]联想项目单个脚本执行结果错误率明显高于单机jmeter的错误率，多个脚本一起执行时错误率会更高

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#3987]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2
**Bug 描述**

简要描述您碰到的问题
联想单个脚本执行结果错误率明显高于单机jmeter的错误率，多个脚本一起执行时错误率会更高
**Bug 重现步骤**

1.  执行单个脚本，错误率明显高于单机jmeter的错误率，脚本见附件
2. 多个脚本一起执行时错误率会更高
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
执行单个脚本，或多个脚本执行时，错误率应跟jmeter相当
**截图**
<img width="954" alt="1" src="https://user-images.githubusercontent.com/83771182/122747471-ac854880-d2bd-11eb-8eac-b7ba9e206ad8.png">
<img width="550" alt="2" src="https://user-images.githubusercontent.com/83771182/122747709-f53d0180-d2bd-11eb-8e77-2a1b95f78e49.png">
<img width="946" alt="3" src="https://user-images.githubusercontent.com/83771182/122747723-fa01b580-d2bd-11eb-9f36-c299f7ae5c7c.png">
<img width="548" alt="4" src="https://user-images.githubusercontent.com/83771182/122747733-fd953c80-d2bd-11eb-8cef-4a644d705562.png">

如果有截图，请附上截图.
[问题.zip](https://github.com/metersphere/metersphere/files/6685976/default.zip)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下原因

**Comment by liuruibin** [comment]
我们生成报告的方式是用 jmeter -g jtl 的方式生成的，请自行下载jtl并用jmeter的本地工具生成进行对比
