### ISSUE TITLE
[BUG]定时器执行测试计划接口场景失败，无法通过测试

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#3988]
**MeterSphere 版本**
>v1.10.2

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
## 定时器执行接口场景失败，无法通过测试。只能手动执行太累了，做不到自动化接口测试母的。
**Bug 重现步骤**

1.  在测试计划中放了几个场景，设置定时运行
2. 在运行时，不同的场景有相互依赖，运行顺序不是按照依赖的先后顺序运行，场景无法运行成功。需要手动一个一个场景点击运行。失去了自动化测试意义。
3. 建议在测试计划页面展示的场景列表上添加自定义运行顺序设置。通过设置运行顺序保证多个场景运行正常。
4. 

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/34681889/122752269-4e5b6400-d2c3-11eb-96dd-1e0b1fa7be8a.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by xulinde** [comment]
v1.13已支持自定义排序
