### ISSUE TITLE
[BUG]性能测试还需优化，9月7日开始的性能测试，截止到9月11日还是starting状态

### ISSUE THREAD

**Issue by wuha07456** [metersphere/metersphere#399]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.2
**Bug 描述**
简要描述您碰到的问题
性能测试还需优化，9月7日开始的性能测试，截止到9月11日还是starting状态
**Bug 重现步骤**
1.  选择某个测试进行性能测试
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
测试完成生成报告
**截图**
如果有截图，请附上截图.
![1223](https://user-images.githubusercontent.com/55642264/92891276-68ba0480-f44a-11ea-83de-c9810563eaf0.jpg)

**Comment by wangzhen-fit2cloud** [comment]
可能是镜像不存在导致的问题，类似这种尽量改一下抛异常然后运行状态 error 掉吧 @liuruibin

**Comment by liuruibin** [comment]
已处理
