### ISSUE TITLE
[BUG]x-www-form-urlencoded参数格式场景接口，场景导出jmeter格式，然后再导入，接口参数格式变为QUERY格式，接口请求失败

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#3991]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.2
**Bug 描述**
x-www-form-urlencoded参数格式场景接口，场景导出jmeter格式，然后再导入，接口参数格式变为QUERY格式，接口请求失败
简要描述您碰到的问题

**Bug 重现步骤**

1.  创建场景，引入x-www-form-urlencoded参数格式接口
![image](https://user-images.githubusercontent.com/30038088/122787925-67c2d700-d2e8-11eb-8e58-6c26fb4b4ad1.png)
2.请求参数如下
![image](https://user-images.githubusercontent.com/30038088/122787983-73160280-d2e8-11eb-99e4-9336364727c1.png)
3. 导出jmeter格式，再导入场景，接口参数如下
![image](https://user-images.githubusercontent.com/30038088/122788127-9b9dfc80-d2e8-11eb-9b17-a8c86779644f.png)

4. 请求参数如下
![image](https://user-images.githubusercontent.com/30038088/122788096-93de5800-d2e8-11eb-8741-cd56a48e9b93.png)

**期待的正确结果**

正确情况下应该是什么样的？
x-www-form-urlencoded参数格式场景接口，场景导出jmeter格式，然后再导入，接口参数及格式不变，接口请求成功。
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5已修复
