### ISSUE TITLE
[BUG]缺陷提交关联jira数组格式数据无法匹配传输

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#3996]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2
**Bug 描述**
多选下拉列表以及多选框都无法传输数组类型数据，如下文截图

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
能够多选传输数组格式数据，正确创建bug
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/40912823/122855981-a6887980-d348-11eb-9df2-1a49ed507f34.png)
![image](https://user-images.githubusercontent.com/40912823/122856016-af794b00-d348-11eb-8e1e-de250c25811d.png)

**Comment by xulinde** [comment]
使用最新版本还有此问题吗
