### ISSUE TITLE
mock的请求Body 是数组形式，请求会报错

### ISSUE THREAD

**Issue by yang12389** [metersphere/metersphere#3999]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.1-60cc5c55

**Bug 描述**

简要描述您碰到的问题
mock的请求Body 是数组形式，请求会报错

**Bug 重现步骤**

1.  [
    {
        "depositNo": "YJ2103091325118371",
        "auditStatus": 0,
        "refundPrice": 275
    }
]
2. 
3. 
4. 

**期待的正确结果**

正常请求

**截图**

![image](https://user-images.githubusercontent.com/56618708/122859142-18af8d00-d34e-11eb-805f-55bb26a4ea3d.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4已修复
