### ISSUE TITLE
演示视频的oss地址访问报错

### ISSUE THREAD

**Issue by jokimina** [metersphere/metersphere#4]
![image](https://user-images.githubusercontent.com/11460661/84612438-4409cb80-aef3-11ea-878c-dffccd4d426e.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢反馈。
请问这个视频你是通过哪里访问？网站上的我试了下都是正常的。

**Comment by wangzhen-fit2cloud** [comment]
@jokimina 已修复，请再试下吧。
