### ISSUE TITLE
接口响应体不支持json备注

### ISSUE THREAD

**Issue by yang12389** [metersphere/metersphere#4000]
**请描述您的需求或者改进建议.**

编写接口文档时，为了方便前后端人员沟通，接口返回值应允许添加各类值的备注信息，方便前端人员查看及mock

**请描述你建议的实现方案**
接口返回值支持json备注并能在接口文档中查看

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研

**Comment by zyyfit** [comment]
您好，接口定义的响应中可以开启json-schema格式来添加备注，不知道是否满足您的需求
![图片](https://user-images.githubusercontent.com/73461316/123748728-2a150e00-d8e7-11eb-89fa-f1d64882516e.png)
