### ISSUE TITLE
[FEATURE]希望可以支持接口测试项目中的各个场景中的接口可以相互打通

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#401]
**请描述您的需求或者改进建议.**
希望可以支持接口测试项目中的各个场景中的接口可以相互打通，
1、目前因为没有统一的接口管理平台，如果需要测试不同场景 里面有相同的接口就要反复的写
2、不能指定某些场景运行，想要指定某些场景运行，只能反向禁止其他场景，超级不方便
3、测试用例中只是纯粹的记录，不知道具体是哪个被测试了，如果是接口测试是否能够和指定的场景或者测试报告关联起来

**请描述你建议的实现方案**
1、同一个项目下不同的场景的接口不能相互打通（希望支持拖拽），这样就可以解决要不要停写重复接口的问题
2、可以像postMan那样指定某些场景里面的接口运行，支持正向选择和反向选择 需要的接口进行测试
3、测试用例中是否可以与接口测试中场景结合起来

**Comment by wangzhen-fit2cloud** [comment]
你好, 跨测试引用/复制场景的功能正在开发中, 将在 1.3 版本提供

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，新版本中已实现，请持续关注～
