### ISSUE TITLE
[FEATURE]请增加用例强制停止执行功能

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4016]
**请描述您的需求或者改进建议.**
版本：
v1.10.2
在web页面上看不到正在运行的用例，shell下tailf /opt/metersphere/logs/metersphere/info.log看到用例确实还在执行（陷入一个死循环），请增加强制停止用例执行的功能

**请描述你建议的实现方案**
web页面增加强制停止用例执行的功能

**Comment by xulinde** [comment]
场景那里有“失败继续”的功能，可以关闭该按钮，则失败后不再继续往下执行
