### ISSUE TITLE
[FEATURE]请在web页面上增加用例运行的实时log打印

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4017]
**请描述您的需求或者改进建议.**
版本v1.10.2
现在运行场景用例时只能看着大白屏上旋转的圈圈发呆，能不能实时显示当前运行到哪一个用例？运行到用例的哪一步了？能不能把/opt/metersphere/logs/metersphere/info.log打印到运行页面上？

**请描述你建议的实现方案**
请实时显示当前运行到哪一个用例，或者运行到哪一步，或者执行页面页面实时显示log

**Comment by xulinde** [comment]
后面版本会优化

**Comment by xulinde** [comment]
v1.13已支持控制台
