### ISSUE TITLE
[BUG]测试用例删除后的刷新问题

### ISSUE THREAD

**Issue by elviszy** [metersphere/metersphere#4020]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10
**Bug 描述**
测试用例模块,在某个节点下删除一条用例后,页面应仅刷新该节点下的用例信息,不能刷新至展示整个项目的测试用例

**截图**
删除前截图
![image](https://user-images.githubusercontent.com/26116509/122888628-9b4b4300-d374-11eb-94c9-34304086f258.png)

删除后跳转截图
![image](https://user-images.githubusercontent.com/26116509/122888627-9b4b4300-d374-11eb-8c28-f8159d40580d.png)

如果有截图，请附上截图.

**Comment by elviszy** [comment]
图反了

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4已修复
