### ISSUE TITLE
[BUG] 定时器错误导致不能添加定时器

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#4021]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  定时器不支持多个时间段设置，例如设置一天运行两次。
2. 这个定时器格式是正确的，在平台上就提示错误，且不能保存。0 0 18,9 * * ? *
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/34681889/122892658-2974f880-d378-11eb-87f5-3bd8b9f26d3b.png)

**Comment by zyyfit** [comment]
您好，您使用的表达式格式是否跟ms系统里不太一样，我试了一下，系统里  0 0 9,18 * * ?  这样写是正常的

**Comment by xiaoguiliu** [comment]
使用ms生成定时任务，就出错。不是我手动写的。




| |
brucedalong
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年06月25日 10:34，zyyfit 写道：

您好，您使用的表达式格式是否跟ms系统里不太一样，我试了一下，系统里 0 0 9,18 * * ? 这样写是正常的

**Comment by zyyfit** [comment]
> 使用ms生成定时任务，就出错。不是我手动写的。 | | brucedalong | | ***@***.*** | Signature is customized by Netease Mail Master 在2021年06月25日 10:34，zyyfit 写道： 您好，您使用的表达式格式是否跟ms系统里不太一样，我试了一下，系统里 0 0 9,18 * * ? 这样写是正常的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，知道问题在哪里了，这里18在9前面会报错，我们后续会优化一下这个问题的

**Comment by xiaoguiliu** [comment]
好的




| |
brucedalong
|
|
***@***.***
|

Signature is customized by Netease Mail Master

在2021年06月29日 15:19，zyyfit 写道：

使用ms生成定时任务，就出错。不是我手动写的。 | | brucedalong | | @.*** | Signature is customized by Netease Mail Master 在2021年06月25日 10:34，zyyfit 写道： 您好，您使用的表达式格式是否跟ms系统里不太一样，我试了一下，系统里 0 0 9,18 * * ? 这样写是正常的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，知道问题在哪里了，这里18在9前面会报错，我们后续会优化一下这个问题的

**Comment by xulinde** [comment]
v10.5已修复
