### ISSUE TITLE
测试用例脑图排序bug

### ISSUE THREAD

**Issue by linyuantang001** [metersphere/metersphere#4024]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.2
**Bug 描述**

测试用例脑图管理，通过调整用例的位置，即上移下移之后保存不生效，测试用例列表中的顺序没变

**Bug 重现步骤**

1.  “测试跟踪”--“测试用例”
2. 测试用例脑图管理，通过调整用例的位置，即上移下移之后保存不生效，测试用例列表中的顺序没变

**期待的正确结果**

调整用例的位置，保存后用例列表顺序随之改变

**截图**
![image](https://user-images.githubusercontent.com/39185981/122903555-17985300-d382-11eb-9123-7f04576d3abc.png)

![image](https://user-images.githubusercontent.com/39185981/122903588-2121bb00-d382-11eb-964a-f7fc867f35a8.png)

顺序修改了还是没有变化

**Comment by daijinp** [comment]
你是这个公司的tester吗？我发现的很多问题和痛点你都提了issue，这个产品设计的非常好，但是问题太太太多了

**Comment by linyuantang001** [comment]
> 你是这个公司的tester吗？我发现的很多问题和痛点你都提了issue，这个产品设计的非常好，但是问题太太太多了

他们产品迭代很快，相信MS团队会都一一解决，一起支持下像他们这样的开源项目吧。

**Comment by zyyfit** [comment]
您好，目前是不支持调整用例顺序的，后续版本可能会考虑调整

**Comment by lingrance** [comment]
> 您好，目前是不支持调整用例顺序的，后续版本可能会考虑调整

后续脑图能支持上传图片吗？类其他的思维导入是可以的
![image](https://user-images.githubusercontent.com/44960709/123382653-c4621280-d5c4-11eb-96ce-edadfd27d35a.png)

**Comment by xulinde** [comment]
v1.12已支持
