### ISSUE TITLE
默认模块支持改名

### ISSUE THREAD

**Issue by linyuantang001** [metersphere/metersphere#4025]
这个「默认模块」建议可以删除，或者至少可以更改名称

![image](https://user-images.githubusercontent.com/39185981/122904572-0dc31f80-d383-11eb-8697-d7ac44d8b0bc.png)

**Comment by xulinde** [comment]
因为我们有些初始化的数据会放默认模块里，类似tapd 这个未分类，也是不能改不能删
![image](https://user-images.githubusercontent.com/64065190/122913719-5fbc7300-d38c-11eb-928a-ecef3dcb25b1.png)

**Comment by linyuantang001** [comment]
不能删倒是有些技术需要，可以理解，不能更改是不是不合理

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by xulinde** [comment]
和#5203重复
