### ISSUE TITLE
增加消息通知提醒建议

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#403]
测试经理角色进行测试计划执行人分配后，建议计划执行人可以收到消息通知，提升测试计划执行速度！

**Comment by wangzhen-fit2cloud** [comment]
你好, 该功能正在开发中, 将在 1.3 版本提供

**Comment by pcc426** [comment]
还希望能支持@用户 功能，这样比如在用例评审时可以直接在备注中添加意见，然后用例维护人和被@ 的用户都能收到通知

**Comment by wangzhen-fit2cloud** [comment]
你好，在最新版本中已提供相关功能
