### ISSUE TITLE
[BUG]性能测试，执行时间错误，有截图

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#4035]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2

**Bug 描述**

1. 用节点执行性能测试时，执行时间不正确
2. 节点机器的监控时间范围太广了

![image](https://user-images.githubusercontent.com/6467295/123024017-ff204b00-d40a-11eb-8f6e-62b84e539c32.png)

**Comment by liuruibin** [comment]
执行开始是早上2点，执行时长是477分钟并且没有结束，请检查测试时间的配置和测试容器是否正常退出。如果测试时间很短但是容器没有退出，请考虑选中自动停止的配置

**Comment by seasoncool** [comment]
@liuruibin  感谢您的回复。
我们早上并没有在 2点的时候做性能测试，我们也尝试重启所有的节点服务，我们也没有在跑任何性能测试，再次执行还是会出现 时间上的问题。
请问还有什么办法 ，可以解决吗 ？

**Comment by liuruibin** [comment]
1. 是不是定时任务出发的测试
2. 部署节点的时区是不是国内时区
3. 测试的压力配置上有个到时自动停止的选项，可以在测试结束后强制停止测试

**Comment by seasoncool** [comment]
@liuruibin ， 刚刚按您的提示检查了一番，如下：
1. 我们没有定时任务，夜间也没有
2. 部署的节点机器，包括宿主机器，时区都是正常且统一（Wed Jun 23 15:14:16 CST 2021）
3. 过滤了所有的性能测试报告，也没有再running状态的脚本

**Comment by liuruibin** [comment]
![image](https://user-images.githubusercontent.com/23045261/123053523-8e8f2380-d436-11eb-8dbf-20b04af2058a.png)

**Comment by seasoncool** [comment]
忘记补充一句： local 的执行时间正常，只有用节点执行才会有这个问题。
