### ISSUE TITLE
[BUG]改过参数后执行用例，执行成功后，body内的参数还是上次的内容，没同步更新

### ISSUE THREAD

**Issue by zmm23sdo** [metersphere/metersphere#4038]
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/64508210/123043571-12431300-d42b-11eb-9731-c8865d8acb4c.png)
![image](https://user-images.githubusercontent.com/64508210/123043595-1b33e480-d42b-11eb-90c6-2040fc33b038.png)

**Comment by zyyfit** [comment]
请问是场景中吗？目前场景中调试不会自动保存了，需要手动保存一下
