### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#404]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.2.1-b623
**Bug 描述**
简要描述您碰到的问题
系统管理->组织->成员，【添加成员】弹窗页面，“角色”字段下拉框只有“组织管理员”一个选项
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应该展示系统有的所有角色（除“系统管理员”）
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/92991440-5ad1b580-f516-11ea-91eb-6eda712a5331.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，目前设计就是这样的，在该页面添加成员时是为某个用户添加该组织的组织级角色，目前组织级角色只有组织管理员一种
