### ISSUE TITLE
api启动测试计划并发数量过大，请重新选择！[BUG]

### ISSUE THREAD

**Issue by eechenyi** [metersphere/metersphere#4040]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口调用/test/plan/testplan/jenkins  启动测试计划报并发量过大
2. 查源码 代码写错了
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/67175449/123045758-df4e4e80-d42d-11eb-9313-7ea875c86902.png)
TestPlanService.run

![image](https://user-images.githubusercontent.com/67175449/123045944-1886be80-d42e-11eb-9cdf-87d1383f962d.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是否在系统设置中配置了并发限制等信息？
