### ISSUE TITLE
[QUESTION] 接口测试 无法保存运行环境

### ISSUE THREAD

**Issue by nankangerzhong** [metersphere/metersphere#4051]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/40852135/123063490-09a90780-d440-11eb-9436-56ae21d09205.png)
请知道的回复一下。谢谢

**Comment by xulinde** [comment]
您用的是哪个环境，我用最新版本没复现这个问题

**Comment by nankangerzhong** [comment]
我说的是环境配置里面的 http配置&nbsp; &nbsp;填写后没法保存&nbsp; ，你的这边可以吗？我的是上周安装的版本





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION] 接口测试 无法保存运行环境 (#4051)





 
您用的是哪个环境，我用最新版本没复现这个问题

**Comment by nankangerzhong** [comment]
已解决问题，我的用法不对。感谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "李标明"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 上午9:14
***@***.***&gt;;

主题:&nbsp;回复： [metersphere/metersphere] [QUESTION] 接口测试 无法保存运行环境 (#4051)





我说的是环境配置里面的 http配置&nbsp; &nbsp;填写后没法保存&nbsp; ，你的这边可以吗？我的是上周安装的版本





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [QUESTION] 接口测试 无法保存运行环境 (#4051)





 
您用的是哪个环境，我用最新版本没复现这个问题
