### ISSUE TITLE
[BUG]在jenkins上非admin账号，看不到工作空间，工作空间选框为空

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4058]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
ms：v1.10.2
jenkins插件：metersphere-jenkins-plugin-v1.10.2.hpi
**Bug 描述**

在jenkins上非admin账号，看不到工作空间，工作空间选框为空

**Bug 重现步骤**

1.  如题，在jenkins上非admin账号，看不到工作空间，工作空间选框为空
2. 更换为admin账号的api key，工作空间就可以选择了。
3. 
4. 

**期待的正确结果**

应该能看到工作空间才对

**截图**

![企业微信截图_1624440650207](https://user-images.githubusercontent.com/5140999/123074961-598ccc00-d44a-11eb-819c-cd090b4de258.png)

**Comment by zyyfit** [comment]
您好，这边没有复现，是否是所填的key没有权限呢？目前有新版的jenkins插件了，也可以更新一下插件版本试试

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，您可以升级到最新版1.10.3再试一下，注意要保持ms版本和插件版本一致

**Comment by xulinde** [comment]
1.10.4已修复，您可以升级到最新版1.10.4再试一下，注意要保持ms版本和插件版本一致
