### ISSUE TITLE
[BUG]测试计划列表页面，“负责人”应展示成员姓名，非展示成员ID

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#406]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.2.1-b623
**Bug 描述**
简要描述您碰到的问题
测试计划列表页面，“负责人”应展示成员姓名，非展示成员ID
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已解决
