### ISSUE TITLE
[BUG]关联JIRA缺陷失败，jira7.4 版本没有, "path": "/issues/add"  接口路径

### ISSUE THREAD

**Issue by ZheErMao** [metersphere/metersphere#4063]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.3
**Bug 描述**

关联JIRA缺陷失败，jira7.4 版本没有, "path": "/issues/add"  接口路径

**Bug 重现步骤**

1.  系统这是 jira 缺陷，测试连通成功
2. 用例管理中管理缺陷，失败 提示：
3. { "timestamp": "2021-06-23T10:27:56.215+00:00", "status": 500, "error": "Internal Server Error", "path": "/issues/add" }

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/6259419/123081821-f5213b00-d450-11eb-9731-c654b76b12b4.png)

![image](https://user-images.githubusercontent.com/6259419/123081713-d4f17c00-d450-11eb-8a5a-90743ac2f484.png)

**Comment by xulinde** [comment]
未复现该问题，使用最新版本还有复现吗
