### ISSUE TITLE
平台界面上长时间未操作不会弹出登录，再次操作需要手动刷新界面才生效

### ISSUE THREAD

**Issue by gaoqijun** [metersphere/metersphere#4066]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，这个问题可能后面会优化

**Comment by xulinde** [comment]
v10.5已优化
