### ISSUE TITLE
[BUG]测试跟踪-测试评审里关联的用例无法添加到测试计划里

### ISSUE THREAD

**Issue by txc1192** [metersphere/metersphere#4067]
**MeterSphere 版本**
>v1.10.3 

**Bug 描述**

简要描述您碰到的问题
【测试跟踪】-【测试计划】添加用例

已经评审完的用例无法添加到测试计划里，导致无法对评审完的用例及时执行测试

目前要往测试计划添加用例只能从用例集合里去选，如果用例有几百条比较多的话相当于我评审时要把几百条用例从用例集合里挑出来放到评审里，然后执行测试计划时又要重新把这几百条用例再挑选一次，工作量巨大，使用上非常麻烦

**期待的正确结果**

测试计划里关联测试用例时可以从创建评审里去选择用例或者直接从评审生成一个测试计划，带出来里面所有的用例

**截图**
![image](https://user-images.githubusercontent.com/62461301/123193579-9fdc3c80-d4d7-11eb-9603-39fc589b6000.png)

**Comment by xulinde** [comment]
后续版本会优化这里

**Comment by txc1192** [comment]
好的好的，请问大概时候呢？有个预计上线日期么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 下午5:32
***@***.***&gt;;
抄送:&nbsp;"♀  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]测试跟踪-测试评审里关联的用例无法添加到测试计划里 (#4067)





 
后续版本会优化这里
