### ISSUE TITLE
[BUG] 创建workspace接口，入参organizationId未生效，工作空间没有创建在对应的organization下

### ISSUE THREAD

**Issue by hu666hu** [metersphere/metersphere#4072]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

> v1.10

**Bug 描述**

> 1. 创建workspace接口，入参organizationId未生效，工作空间没有创建在指定的organization下

	path：/workspace/add

功能块 | 描述 | 期望

> 创建workspace| body入参"organizationId"未生效，工作空间没有创建在该organization下 | 工作空间创建在传入的参数 
   organizationId下，与该organization绑定

</body>
</html>

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这个问题没有复现呢，方便把您的入参提供一下吗？这边填写的入参是这样的
![图片](https://user-images.githubusercontent.com/73461316/123587575-0edbcd00-d819-11eb-80fd-8fc01078e4ea.png)
