### ISSUE TITLE
[BUG]创建project接口，入参workspaceId未生效，项目没有创建在指定的workspace下

### ISSUE THREAD

**Issue by hu666hu** [metersphere/metersphere#4073]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

> 1.10

**Bug 描述**

> 创建project接口，入参workspaceId未生效，项目没有创建在对应的workspace下

> path：/project/add

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

> 入参workspaceId，项目创建在其对应的workspace下，项目与workspace绑定

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4版本已修复
