### ISSUE TITLE
[BUG]superAdmin登录，没有支持查询组织下所有工作空间的项目列表的 API

### ISSUE THREAD

**Issue by hu666hu** [metersphere/metersphere#4074]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

> 1.10

**Bug 描述**

> superAdmin登录，没有支持查询组织下所有工作空间的项目列表的 API
	

> path：/project/listAll/{workspaceId}

> 或 /project/list/{pageNo}/{pageNum}

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

> superAdmin登录，提供支持查询组织下所有工作空间的项目列表的 API

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是没有直接查询所有项目的api的，如果需要的话后续版本可能会增加
