### ISSUE TITLE
[BUG]查询项目成员的接口，需要再调API查询成员项目角色，但是查询项目角色API不能支持批量查

### ISSUE THREAD

**Issue by hu666hu** [metersphere/metersphere#4075]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

> 1.10

**Bug 描述**

> 查询项目成员的接口，需要再调API查询成员项目角色，但是查询项目角色API不能支持批量查（提供的API只能查单个用户项目角色）
	
> 项目成员API  path：/user/project/member/list/{pageNo}/{pageNum}

> 项目成员角色API  path：/user/group/list/project/{projectId}/{userId}

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

> 查询项目角色API能支持批量查

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们调研一下相关需求
