### ISSUE TITLE
[接口测试]键值对的输入支持由文本转为键值对，类似于postman有一个bulk Edit功能

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#409]
**请描述您的需求或者改进建议.**
键值对的输入支持由文本转为键值对，类似于postman有一个bulk Edit功能

该方式有利于接口参数较多的场景，不需要一个一个的去输入参数，可以直接从其他地方复制后用

**Comment by xulinde** [comment]
您好，平台已新增批量添加请求参数的功能，您可以升级到最新版本体验下
