### ISSUE TITLE
[BUG]测试计划的定时任务设置资源池执行，报错

### ISSUE THREAD

**Issue by wjtlt3** [metersphere/metersphere#4094]
**MeterSphere 版本**
v1.10.3

**Bug 描述**
资源池节点状态正常，但是无法用来设置执行定时任务，会报错

![image](https://user-images.githubusercontent.com/49089965/123242282-7261b400-d514-11eb-8f80-d183cb07f35b.png)

![image](https://user-images.githubusercontent.com/49089965/123242201-5e1db700-d514-11eb-9451-75ae5ab5ff29.png)

![image](https://user-images.githubusercontent.com/49089965/123242248-6970e280-d514-11eb-9133-eed705865504.png)

**Comment by xulinde** [comment]
未复现该问题，建议您升级到最新版本试下
