### ISSUE TITLE
Jenkins触发的测试计划报告和手动执行的不一致[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4096]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10
**Bug 描述**
Jenkins触发的测试计划报告和手动执行的不一致

正确情况下应该是什么样的？
Jenkins触发如下：
![image](https://user-images.githubusercontent.com/30932762/123261546-777d2e00-d529-11eb-8942-bb79c4914590.png)
手动执行报告如下：
![image](https://user-images.githubusercontent.com/30932762/123261606-8a8ffe00-d529-11eb-9e82-89e6b1bef2b9.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，jenkins触发的报告由于只执行接口和性能测试，所以没有功能测试部分
