### ISSUE TITLE
测试计划报告优化

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4097]
**请描述您的需求或者改进建议.**
目前测试计划中的报告只有功能测试进行了表格化的统计，对于接口测试和性能测试没有统计。如下图
测试结果只有功能测试的，但是测试结果统计包含了所有的测试类型，这个不合理
![image](https://user-images.githubusercontent.com/30932762/123261933-efe3ef00-d529-11eb-8c7d-ac936eb9e9c4.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
只有关联的接口和性能测试，执行才会统计结果
