### ISSUE TITLE
[BUG]用例ID重复，用例数量统计错误

### ISSUE THREAD

**Issue by kouzhijian** [metersphere/metersphere#4104]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用例统计数量错误，本来10个，数量显示5
2. 同一级目录下，用例ID发生重复
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![用例统计错误](https://user-images.githubusercontent.com/33210000/123359161-5eaf5f80-d59f-11eb-89a4-61294e25f9b1.png)
![用例ID重复](https://user-images.githubusercontent.com/33210000/123359170-6242e680-d59f-11eb-86a3-d3d2adc8458b.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前最新版已经是1.10.3了，在1.10.3版本没有复现这个问题，建议您升级后看一下

**Comment by xulinde** [comment]
用例重复那个问题1.10.4已修复，数量显示错误未复现
