### ISSUE TITLE
给的权限是多个项目，但项目显示只显示了一个，建议多个项目一起显示[BUG]

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#4107]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.3
**Bug 描述**

给的权限是多个项目，但项目显示只显示了一个，建议多个项目一起显示

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/80370956/123366706-3e859d80-d5ab-11eb-96ee-f995a9dac699.png)

**Comment by zyyfit** [comment]
您好，在工作空间下的项目管理模块可以看到所有有权限的项目的，您看一下是您想要的结果吗
![图片](https://user-images.githubusercontent.com/73461316/123597559-12298580-d826-11eb-82ed-eb238382bb4d.png)
