### ISSUE TITLE
[BUG]mock中入参含有数组，mock报错

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#4111]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.3
**Bug 描述**
mock接口中创建一个期望，请求参数选择json，当json中含有数组时，无法返回正常响应数据，后台报错
去掉json中数组部分，mock接口返回正常。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/40912823/123380797-7815d300-d5c2-11eb-935f-c6d18f218283.png)

![image](https://user-images.githubusercontent.com/40912823/123380911-9976bf00-d5c2-11eb-8090-afd4aa55b334.png)

**Comment by zyyfit** [comment]
重复bug https://github.com/metersphere/metersphere/issues/3999

**Comment by wszbc** [comment]
> 重复bug #3999

貌似不是一个问题我看3999 1.10.4已经被修复了，我在1.10.5依旧会报上图的错误信息

**Comment by xulinde** [comment]
现在还有此问题吗

**Comment by wszbc** [comment]
> 现在还有此问题吗

新版本已经修复了
