### ISSUE TITLE
[BUG]测试计划场景执行失败没有发送邮件

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#4112]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.2
**Bug 描述**
1.创建测试计划，在测试计划中包含多个接口用例场景。
2.设置定时任务消息类型时执行失败发送邮件
3.实际上场景有成功和失败，失败的没有发送邮件。

**期待的正确结果**
1.在一个测试计划中包含多个场景时，执行失败了发送邮件。
2.发送邮件应该值发送执行失败场景的邮件，不是全部场景都发送邮件造成邮件一堆一堆。分不清哪个是重点要看的邮件。

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
使用最新版本未复现该问题，建议您升级到最新版本在试下
