### ISSUE TITLE
[BUG]性能测试-测试概念页，运行中的任务，图表设置不展示折线后，会自动恢复显示折线

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#4113]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**![image](https://user-images.githubusercontent.com/77324661/123385555-40aa2500-d5c8-11eb-8dac-965f2ffc6098.png)
![image](https://user-images.githubusercontent.com/77324661/123385775-81a23980-d5c8-11eb-9dd1-cb7fe2a0defc.png)

**

如果有，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by xulinde** [comment]
目前就是这样设计的哦～
