### ISSUE TITLE
[BUG]点击测试报告中的用例报错

### ISSUE THREAD

**Issue by 15708416734** [metersphere/metersphere#4117]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.3-10ac86a0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  收到测试计划邮件
2. 打开邮件进入测试报告界面
3. 点击测试用例，报错

**期待的正确结果**

正确情况下应该是什么样的？
正确跳转到对应用例

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/37166279/123402002-e3b76a80-d5d9-11eb-8283-30437d15965c.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
测试报告已改版，建议您升级到最新版本体验下
