### ISSUE TITLE
[BUG]测试通过，但邮件中提示测试失败

### ISSUE THREAD

**Issue by 15708416734** [metersphere/metersphere#4118]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.3-10ac86a0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  定时执行测试计划，选择邮件发送
2. 测试通过后提示测试失败

**期待的正确结果**
测试通过提示测试成功
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/37166279/123402469-59233b00-d5da-11eb-84ea-c0f1ad3f947e.png)
![image](https://user-images.githubusercontent.com/37166279/123402558-71935580-d5da-11eb-8723-f5a947870bd4.png)
![image](https://user-images.githubusercontent.com/37166279/123402630-8374f880-d5da-11eb-94a0-64cd3d991f5b.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这边没有复现呢，您是否配置了自定义通知格式之类的？
![image](https://user-images.githubusercontent.com/73461316/123670226-8f2d1d00-d86f-11eb-939e-d230885ca5ba.png)

**Comment by 15708416734** [comment]
请问自定义通知格式在哪看呢，没有找到

**Comment by lxh3145** [comment]
> 您好，这边没有复现呢，您是否配置了自定义通知格式之类的？
> ![image](https://user-images.githubusercontent.com/73461316/123670226-8f2d1d00-d86f-11eb-939e-d230885ca5ba.png)

这个问题我这里也有，群里提过了，我也提了另一个bug

**Comment by 15708416734** [comment]
> > 您好，这边没有复现呢，您是否配置了自定义通知格式之类的？
> > ![image](https://user-images.githubusercontent.com/73461316/123670226-8f2d1d00-d86f-11eb-939e-d230885ca5ba.png)
> 
> 这个问题我这里也有，群里提过了，我也提了另一个bug

你解决了吗

**Comment by xulinde** [comment]
名字显示已经可以了，状态这个没有复现出来
