### ISSUE TITLE
[FEATURE]创建用例时需要增加标签属性，可以自定义多个标签，方便通过标签筛选用例

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#413]
**请描述您的需求或者改进建议.**
创建用例时需要增加标签属性，可以自定义多个标签，方便通过标签筛选用例

**请描述你建议的实现方案**
标签可以采用后台配置和自由定制两种模式，后台配置的标签可以从标签列表中选择，避免由于手误打错字而导致没有过滤到相应用例。用例可以定制多个标签，方便从不同维度进行筛查
在测试计划筛查用例时，可以通过标签进行筛查，筛查出来的用例自动分配到测试计划树中的相应模块

**Comment by wangzhen-fit2cloud** [comment]
你好, 标签功能之前有想过, 具体实现方式及时间还在规划中

**Comment by youliyuan-fit2cloud** [comment]
您好，v1.7版本中已实现该功能，请持续关注！
