### ISSUE TITLE
[FEATURE]设置全局登录的入口，可以在不同场景用例里共享cookies

### ISSUE THREAD

**Issue by linda0007** [metersphere/metersphere#4138]
**目前的痛点**
需要在每个场景用例里都放置一个登录接口，用来获取cookies传递给后面的接口，很累赘

**请描述您的需求或者改进建议.**

设置全局登录的入口，可以在不同场景用例里共享cookies

**请描述你建议的实现方案**
设置全局登录的入口，可以在不同场景用例里共享cookies，可以设置全局登录的自动登录频次功能，保证cookies一直有效

**Comment by xulinde** [comment]
可以设置环境参数，只要选择同一个环境的场景，都可以使用该变量
![image](https://user-images.githubusercontent.com/64065190/123573905-74bc5a80-d801-11eb-90db-cec207a70e3e.png)

**Comment by sky1984** [comment]
环境参数有bug，不能获取到最新的值

**Comment by pencui** [comment]
> 环境参数有bug，不能获取到最新的值

我这边正好做了个全局登录的patch，不过是适应我们自己特色的，你们的登录是怎么样的？我看能否通用化改造？加WX 14727136596 可以联系我

**Comment by xulinde** [comment]
环境参数有bug，v10.5已修复了
