### ISSUE TITLE
[FEATURE]jira集成：允许每个人配置jira账号；上传附件；主键冲突解决。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#415]
**请描述您的需求或者改进建议.**
### 1. jira账号配置

> 配置jira账号时，现在一个组织只能配置一个账号，会导致该组织下所有项目、所有测试人员提的任务推送到jira平台之后，“报告人”都是同一个，不便于任务跟踪。

### 2. metersphere提缺陷时，无法上传附件

> 希望添加上传附件的功能。

### 3.jira项目关联时，主键冲突

> 当关联的jira项目发生变更时，任务id会重新从10001开始，导致主键冲突。

**请描述你建议的实现方案**
### 1. jira账号配置

> 允许每个人独立配置jira账号，便于jira平台的任务跟踪。

### 2、metersphere提缺陷时，无法上传附件

> 在“转缺陷”时，提供上传附件功能。

### 3.jira项目关联时，主键冲突
     

>  1）建议增加联合主键，数据库新增字段保存jira平台的项目主键，避免冲突。

    

>   2）或主键自增，不要每个项目都从10001开始，避免冲突。

**Comment by seasoncool** [comment]
顶顶顶，允许每个人配置自己的jira账号。。。

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续已计划优化这部分功能，请持续关注～
