### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#4156]
**请描述您的需求或者改进建议.**
某项目下的接口用例数量有5000多个，当管理员进行以下操作时，系统设置-项目管理-编辑项目-开启时自定义ID，保存，反应很慢（关闭时正常）

**请描述你建议的实现方案**
metersphere与后台数据库的操作要优化

**Comment by songbing0312** [comment]
![图片 1](https://user-images.githubusercontent.com/18387151/123593335-f8397400-d820-11eb-9427-ecb44641bb2a.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本优化下性能

**Comment by xulinde** [comment]
v10.5已优化
