### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#4157]
**请描述您的需求或者改进建议.**
一个接口场景下的测试步骤有600多个，/api/automation/getApiScenarioEnv 请求数据冗余较大，里面还有关键字触发了防火墙的策略

**请描述你建议的实现方案**
metersphere与后台数据库的操作要优化

**Comment by songbing0312** [comment]
![图片 3](https://user-images.githubusercontent.com/18387151/123593428-17380600-d821-11eb-977b-d51dc7146dc9.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本优化下性能

**Comment by xulinde** [comment]
1.10.4版本已优化
