### ISSUE TITLE
[BUG]引用窗口中，切换每页显示条数后，就显示空白了

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#4158]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.3-lts

**Bug 描述**
引用窗口中，切换每页显示条数后，就显示空白了

简要描述您碰到的问题

**Bug 重现步骤**
回显步骤：
1、A项目中接口场景详情中选择场景导入
2、场景导入弹出框中，左上角选择B项目
3、在B项目中选择任意模块目录，切换下方每页显示条数

目前的现象是：切换每页显示条数后，就显示空白了

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="415" alt="图片 2" src="https://user-images.githubusercontent.com/18387151/123593256-e1931d00-d820-11eb-9a14-34562f72dd99.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4已修复
