### ISSUE TITLE
[BUG]串行执行用例速度太慢

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4159]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.10.2

**Bug 描述**

串行执行用例速度远低于预期，有一个三步骤的用例，计算得出三个步骤仅需要10秒左右，但实际上从按下执行按钮到生成报告页面用时两分半

**Bug 重现步骤**
如题

**期待的正确结果**

场景用例执行时间需要跟实际上调用rest api耗时保持一致

**截图**

**Comment by zyyfit** [comment]
感谢反馈，我们排查优化一下这个问题

**Comment by jjjttp** [comment]
> 感谢反馈，我们排查优化一下这个问题

经过排查，是等待控制器作用范围设置不合理导致的，有三个步骤，我在步骤1中设置了等待控制器，但是其作用域步骤2和3，导致用例执行时长比预期要长很多

**Comment by xulinde** [comment]
目前设计如此，等待控制器是全局生效的
