### ISSUE TITLE
把接口的返回值，设置为全局变量调用

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#416]
**请描述您的需求或者改进建议.**

把接口的返回值，设置为全局变量调用

**请描述你建议的实现方案**

把接口的返回值，设置为全局变量调用

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈, 正在规划该功能

**Comment by wangzhen-fit2cloud** [comment]
你好，目前可以通过后置脚本方式来使用，将 var_name 变量的值赋给 prop_name ，在后续的脚本中通过 ${__P(prop_name)} 引用。更方便的配置及引用方式我们将在后续版本中进行优化。
python 脚本参考
```python
props.put("prop_name", vars.get("var_name")）
```

**Comment by Sylvie1222** [comment]
这个变量赋值方式，可以支持跨场景调用了是吧？

**Comment by wangzhen-fit2cloud** [comment]
是的，在其他场景的请求里可以通过这种形式引用  ${__P(prop_name)}
