### ISSUE TITLE
[BUG]多个用例并行执行，控制台同时输出两个用例的运行log，查找自定义脚本运行结果困难

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4161]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.10.2
**Bug 描述**
如题，多个用例并行执行，控制台同时输出两个用例的运行log，查找自定义脚本运行结果困难

**Bug 重现步骤**
1、用例中含有自定义脚本且有print输出，
2、同时运行多个用例

**期待的正确结果**

每个用例的自定义脚本运行结果print输出有单独的窗口显示，而不是跟其他用例混合在一起

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
目前还没有好的解决方法，
相关问题 https://github.com/metersphere/metersphere/issues/2024

**Comment by zyyfit** [comment]
目前还没有好的解决方法，
相关问题 https://github.com/metersphere/metersphere/issues/2024

**Comment by xulinde** [comment]
暂时没想到好的解决方法，日志无法按照请求分离。
