### ISSUE TITLE
类似jmeter的定时器元件，等待一段时间再执行接口

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#418]
**请描述您的需求或者改进建议.**

类似jmeter的定时器元件，等待一段时间再执行接口

**请描述你建议的实现方案**
类似jmeter的定时器元件，等待一段时间再执行接口

**Comment by wangzhen-fit2cloud** [comment]
你好, 该功能将在 1.3 版本提供

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经提供该功能。
