### ISSUE TITLE
性能测试：是否能提供插件，实时监控服务器的性能

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#419]
**请描述您的需求或者改进建议.**
性能测试：是否能提供插件，实时监控服务器的性能

**请描述你建议的实现方案**
性能测试：是否能提供插件，实时监控服务器的性能

**Comment by wangzhen-fit2cloud** [comment]
你好，监控相关功能我们计划通过与现有的监控系统进行集成的方式提供，具体实现方式及实现版本还待规划，欢迎持续关注。
