### ISSUE TITLE
[BUG]数据库报source_id过长错误

### ISSUE THREAD

**Issue by jjjttp** [metersphere/metersphere#4197]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.10.2

**Bug 描述**
在info.log中有如下打印：
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'source_id' at row                                                                  1
; Data truncation: Data too long for column 'source_id' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDa                                                                 taTruncation: Data truncation: Data too long for column 'source_id' at row 1]

**Bug 重现步骤**

**期待的正确结果**

没有报错

**截图**

无

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
1.10.4版本已修复
