### ISSUE TITLE
[FEATURE]产品迭代涉及到多端情况下，测试计划无法关联多端

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#42]
**请描述您的需求或者改进建议.**
产品迭代涉及到多端，一个迭代的测试计划无法关联多端，需要新建多个测试计划，否则产品类的迭代测试时需要切换多个测试计划才能执行一条完整的业务流程

**请描述你建议的实现方案**
在新建测试计划的时候不选择项目归属，在关联测试用例时再选择项目归属

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 产品迭代涉及到多端，一个迭代的测试计划无法关联多端，需要新建多个测试计划，否则产品类的迭代测试时需要切换多个测试计划才能执行一条完整的业务流程
> 
> **请描述你建议的实现方案**
> 在新建测试计划的时候不选择项目归属，在关联测试用例时再选择项目归属

测试计划不归属项目不方便测试计划的管理，在关联的时候加一个切换项目来支持添加用例是否可以解决你的问题呢？

**Comment by zhao103804** [comment]
也是可以的，切换项目主要是为了好跟踪

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中测试计划已可以关联多个项目
