### ISSUE TITLE
[BUG]把mockjs的内置函数设为变量，接口调试界面可以执行成功，但执行接口测试时，报告里该变量调用失败

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#420]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.2.1-b623

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  把mockjs的内置函数设为变量
2. 接口调试界面可以执行成功
3. 执行接口测试时
4. 报告里该变量调用失败

**期待的正确结果**
正确情况下应该是什么样的？
接口调试或者执行接口测试，都应该调用成功

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70245535/93286755-83a1c580-f80a-11ea-862e-6c61ee537e3e.png)

**Comment by wangzhen-fit2cloud** [comment]
你好, 能否补充下请求配置页面的截图
