### ISSUE TITLE
[FEATURE]操作日志占用表空间太大，建议增加 最大日志保留时长设置，或者 直接存到es 里

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#4200]
**请描述您的需求或者改进建议.**
操作日志占用表空间太大，建议增加 最大日志保留时长设置，或者 直接存到es 里

**请描述你建议的实现方案**操作
![wecom-temp-240d1822c852ff04dd0d2944fc534fc3](https://user-images.githubusercontent.com/30038088/123903071-8ee06f00-d9a0-11eb-98e0-43d57f35294c.png)
日志占用表空间太大，建议增加 最大日志保留时长设置，或者 直接存到es 里

**Comment by xulinde** [comment]
现在策略是，默认保存30天。对于您的建议，我们会认真考虑并评估下的
