### ISSUE TITLE
测试计划中两个接口场景用例都执行成功了，结果还是发了执行失败的邮件

### ISSUE THREAD

**Issue by lxh3145** [metersphere/metersphere#4202]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
最新版本
您所使用的 MeterSphere 版本是？
最新版本源码
**Bug 描述**
测试计划中两个接口场景用例都执行成功了，结果还是发了执行失败的邮件
简要描述您碰到的问题
测试计划中两个接口场景用例都执行成功了，结果还是发了执行失败的邮件
**Bug 重现步骤**
测试计划中两个接口场景用例都执行成功了，结果还是发了执行失败的邮件
1.  
2. 
3. 
4. 

**期待的正确结果**
测试计划中多个场景用例执行后，如果没有一个失败案例，那么发成功的邮件，如果有失败案例，则发失败邮件，现在是配置了成功和失败的邮件，结果无论何时都发失败的邮件
正确情况下应该是什么样的？
**如果没有一个失败案例，那么发成功的邮件，如果有失败案例，则发失败邮件，现在是配置了成功和失败的邮件，结果无论何时都发失败的邮件**
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
重复bug https://github.com/metersphere/metersphere/issues/4080
