### ISSUE TITLE
[FEATURE] 支持UDF(用户自定义函数)

### ISSUE THREAD

**Issue by JFRabbit** [metersphere/metersphere#421]
**请描述您的需求或者改进建议.**

有些场景, 用户可能需要生成随机数据, 或是固定结构体:

比如业务场景: 生成随机中文名, 手机号, 邮箱, 身份证号等

比如生成随机数据的请求body: 

- 生成以Test_开头, _Entity结尾的, 中间8位随机的字符串
- 随机从数组中获取一个值
``` json
{
  "name": "randomStr({prefix='Test_', suffix='_Entity', length=8})",
  "country": "randomListOne(['中国', '美国', '加拿大'])" 
}
```

比如返回一个固定的response body
``` json
{
  "code": 0,
  "message": "ok"
}
```

**请描述你建议的实现方案**

支持UDF(用户自定义函数)来满足, 可以以插件等形式集成

设计上可以参考 https://insomnia.rest/ 的插件形式

之前写过的一个插件 https://github.com/JFRabbit/insomnia-plugin-chinese-items

<img width="407" alt="截屏2020-09-16 上午11 47 00" src="https://user-images.githubusercontent.com/22906174/93290056-72f54d80-f812-11ea-8d4b-13168b7d0827.png">
<img width="781" alt="截屏2020-09-16 上午11 47 09" src="https://user-images.githubusercontent.com/22906174/93290060-74bf1100-f812-11ea-92c5-31e7d58bf717.png">

如果要支持的话, 需要考虑支持哪些语言, 函数如何调用, 参数如何传递, 返回值支持的类型等

**Comment by wangzhen-fit2cloud** [comment]
感谢您的反馈, 我们先调研一下
