### ISSUE TITLE
[BUG]项目引用自定义用例模板后，导入时下载用例模板还是默认模板应该是自定义模板；

### ISSUE THREAD

**Issue by TTtesting** [metersphere/metersphere#4211]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.3

**Bug 描述**

项目引用自定义用例模板后，导入时下载用例模板还是默认模板应该是自定义模板；

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

项目引用自定义用例模板后，导入时下载用例模板还是默认模板应该是自定义模板；（下载下来的用例也是一样的问题）

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
