### ISSUE TITLE
[BUG]用例步骤有换行，导入后没有换行

### ISSUE THREAD

**Issue by szfreewalk** [metersphere/metersphere#4212]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10

**Bug 描述**

如题

**Bug 重现步骤**

1.  导入用例的步骤中存在换行
2. 导入平台，换行消失，对应步骤合并成一行了

**期待的正确结果**

导入后保持换行

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
