### ISSUE TITLE
[FEATURE]建议可以新增个能支持oceanbase数据库

### ISSUE THREAD

**Issue by liyunfeng666** [metersphere/metersphere#4217]
**请描述您的需求或者改进建议.**

现在用这个蚂蚁ob数据库的越来越多，应该也会有不少和我一样的需求用户

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
抱歉，长时间未回复。经调研，jmeter是有提供oceanbase驱动的，所以理论上我们也能支持。
数据库插件化这块我们会放到v3.0去做。

**Comment by fit2-zhao** [comment]
重复类需求，请关注 #2914 后续。
