### ISSUE TITLE
[QUESTION] 怎么进行离线升级

### ISSUE THREAD

**Issue by ygqygq2** [metersphere/metersphere#422]
请问怎么进行离线安装包升级，官方文档没看到升级方面的文档。

**Comment by wangzhen-fit2cloud** [comment]
你好, 在我们官网文档的安装部分有升级步骤的描述
https://metersphere.io/docs/installation/offline_installation/#_6

**Comment by ygqygq2** [comment]
多谢。将旧版本的 `install.conf` 里的配置，修改到新版本的 `install.conf` 内，再使用 `install.sh` 安装。
