### ISSUE TITLE
[FEATURE]建议查看报告无需登录

### ISSUE THREAD

**Issue by liyunfeng666** [metersphere/metersphere#4221]
**请描述您的需求或者改进建议.**

从钉钉的告警，查看报告的可能是开发同学，并没有这个平台账号，现在都要一个个添加会比较麻烦

**请描述你建议的实现方案**
报告详情接口可以把登录限制去掉

**Comment by seasoncool** [comment]
这个问题，提的太好了，直击痛点，我们也出现这个问题，只看报告的人其实它不需要这个账号。

**Comment by Jingjingxiang** [comment]
我们也有这个情况，急需这个功能，谢谢

**Comment by muxi12345** [comment]
我们希望Jenkins的报告能从邮件里面，直接打开查看，不用登录。

**Comment by xulinde** [comment]
v1.13 xpack已支持该功能。直接在模板添加变量 ${planShareUrl} , 就可以使用分享链接
