### ISSUE TITLE
[BUG]用例列表复制后，多次保存，用例id重复

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#4229]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪下，用例列表复制后，多次保存，用例id重复
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
1.10.4版本已修复
