### ISSUE TITLE
v1.4 版本功能需求调研结果

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [metersphere/metersphere#424]
https://jinshuju.net/f/CWcGXn/r/dwINKr

**Comment by maninhill** [comment]
![image](https://user-images.githubusercontent.com/41712985/93415480-2e32ea80-f8d6-11ea-9e4d-be3273a2c762.png)

**Comment by smooth00** [comment]
能这能在github上同步提供最新的SQL脚本，源码更新后数据库就报缺表
