### ISSUE TITLE
[BUG]安装node-controller将kafka地址修改为ms-server的地址后安装时会自动修改回本机地址，且启动时候node-controller还是会连接本地的19092端口

### ISSUE THREAD

**Issue by dbxiaoGit** [metersphere/metersphere#4249]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 
v1.10.3

**Bug 描述**

在另一台机上安装node-controller将kafka地址修改为ms-server的地址后安装时会自动修改回本机地址，且修改ms的.env文件中kafka地址为外部地址后重新启动node-controller还是会连接本地的19092端口

**Bug 重现步骤**

1.  修改install.conf中kafka使用外部kafka
2. 修改install.conf中kafka使用外部ip
3. sh install.sh
4. 查看node-controller日志

**期待的正确结果**
node-controller连接外部kafka

**截图**

如果有截图，请附上截图.

**Comment by dbxiaoGit** [comment]
![mmexport1625125209194](https://user-images.githubusercontent.com/18097602/124085495-b9204400-da15-11eb-9a4c-da970e169b98.png)
![mmexport1625125207156](https://user-images.githubusercontent.com/18097602/124085501-baea0780-da15-11eb-9641-2033aaaa6676.png)
![mmexport1625125205178](https://user-images.githubusercontent.com/18097602/124085504-bb829e00-da15-11eb-8c14-5e233a3b2d1c.png)

**Comment by dbxiaoGit** [comment]
![mmexport1625125209194](https://user-images.githubusercontent.com/18097602/124085495-b9204400-da15-11eb-9a4c-da970e169b98.png)
![mmexport1625125207156](https://user-images.githubusercontent.com/18097602/124085501-baea0780-da15-11eb-9641-2033aaaa6676.png)
![mmexport1625125205178](https://user-images.githubusercontent.com/18097602/124085504-bb829e00-da15-11eb-8c14-5e233a3b2d1c.png)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
执行性能测试时使用的 kafka 地址目前是通过 server 传过来的，跟本地配置文件中的配置无关
