### ISSUE TITLE
[BUG]用例自定义字段导出或者导入都没有

### ISSUE THREAD

**Issue by szfreewalk** [metersphere/metersphere#4252]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10

**Bug 描述**

用例自定义字段，导出时没有自定义字段，excel中填写了自定义字段，导入后自定义字段也没有excel中填写的值

**Bug 重现步骤**

1.  在用例模板中增加自定义字段
2. 编写用例，填写自定义字段的值，导出该用例，导出的excel中没有自定义字段
3. 在本地excel中增加自定义字段，并填写自定义字段的值，导入该用例，导入的用例自定义字段没有excel中填写的值

**期待的正确结果**
导出的excel中带自定义字段及值；
本地excel中自定义字段的值能正确导入

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，相关问题https://github.com/metersphere/metersphere/issues/4211

**Comment by xulinde** [comment]
v10.5版本已修复
