### ISSUE TITLE
[BUG]jmx导入的http请求的post表单不对

### ISSUE THREAD

**Issue by dbxiaoGit** [metersphere/metersphere#4253]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 
v1.10.3

**Bug 描述**

jmx导入脚本中http请求post表单数据导入进metersphere之后表单出现在QUERY参数里面
**Bug 重现步骤**

1.  创建一个包含http POST表单的jmx脚本
2. 导入metershphere

**期待的正确结果**
post表单出现在请求体中，目前是放在QUERY参数，需要人工挪到请求体里面去，请求数量多了极不方便

**截图**

如果有截图，请附上截图.
![mmexport1625122703506](https://user-images.githubusercontent.com/18097602/124080598-29c46200-da10-11eb-8a55-b67d932fd8a9.png)
![mmexport1625122700353](https://user-images.githubusercontent.com/18097602/124080605-2b8e2580-da10-11eb-86b1-b2ac35211d0c.png)
![mmexport1625122696974](https://user-images.githubusercontent.com/18097602/124080607-2c26bc00-da10-11eb-8452-5c54d6268235.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我看您这个没有勾选 对POST使用multipart / from-data，您放到请求体里是用的什么格式呢？

**Comment by dbxiaoGit** [comment]
> 您好，我看您这个没有勾选 对POST使用multipart / from-data，您放到请求体里是用的什么格式呢？

在本地用jmeter确实不用勾选multipart / from-data，它发出去的就是一个经过urlencoder的普通的表单，Content-Type: application/x-www-form-urlencoded

**Comment by zyyfit** [comment]
> > 您好，我看您这个没有勾选 对POST使用multipart / from-data，您放到请求体里是用的什么格式呢？
> 
> 在本地用jmeter确实不用勾选multipart / from-data，它发出去的就是一个经过urlencoder的普通的表单，Content-Type: application/x-www-form-urlencoded

收到
