### ISSUE TITLE
[BUG]jmx导入的http cookie管理器无法使用

### ISSUE THREAD

**Issue by dbxiaoGit** [metersphere/metersphere#4254]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 
v1.10.3

**Bug 描述**

jmx导入的cookie管理器在平台查看后保存会失去作用
**Bug 重现步骤**

1.  jmx导入一个带cookie管理器的脚本
2. 平台上查看cookie管理器后保存
3.  执行该脚本，检查cookie有无生效

**期待的正确结果**
查看cookie管理器后保存，脚本不应被修改，cookie管理器的domain和path都保持原样

**截图**

如果有截图，请附上截图.
![mmexport1625122710840](https://user-images.githubusercontent.com/18097602/124081034-a8b99a80-da10-11eb-8def-4cc56091f3a3.png)
![mmexport1625122713792](https://user-images.githubusercontent.com/18097602/124081079-b66f2000-da10-11eb-8fd9-e496f8b5fcd0.png)
![mmexport1625122724475](https://user-images.githubusercontent.com/18097602/124081084-b7a04d00-da10-11eb-9d2e-449ca40056cc.png)
![mmexport1625122720961](https://user-images.githubusercontent.com/18097602/124081087-b838e380-da10-11eb-92d4-4a1a9c8fa5f9.png)
![mmexport1625122716792](https://user-images.githubusercontent.com/18097602/124081089-b8d17a00-da10-11eb-9a9a-0e20514f0513.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
