### ISSUE TITLE
[BUG]jmx导入http请求端口号不能引用变量

### ISSUE THREAD

**Issue by dbxiaoGit** [metersphere/metersphere#4257]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 
v1.10.3

**Bug 描述**

jmx导入脚本中端口号引用变量报错
**Bug 重现步骤**

1.  jmx导入一个端口号引用变量的脚本
2. 平台上执行该脚本

**期待的正确结果**
可以执行该脚本，期待端口号可以引用变量，不然太难用了

**截图**

如果有截图，请附上截图.

![Uploading mmexport1625123243930.png…]()

**Comment by dbxiaoGit** [comment]
![mmexport1625123243930](https://user-images.githubusercontent.com/18097602/124082583-7d37af80-da12-11eb-9fb3-b310b9652f77.png)
![mmexport1625123242883](https://user-images.githubusercontent.com/18097602/124082593-7f017300-da12-11eb-9cfa-809319007757.png)
![mmexport1625123241523](https://user-images.githubusercontent.com/18097602/124082599-8032a000-da12-11eb-8fe1-e2d4d7ccde6b.png)

**Comment by xulinde** [comment]
现在还有此问题吗
