### ISSUE TITLE
[BUG]接口定义请求参数，转换成json格式的请求体，预览内容比模板里显示的少，且实际请求内容和预览一致

### ISSUE THREAD

**Issue by Joemong** [metersphere/metersphere#4261]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

版本: v1.10.0-93f6870d

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口定义，写入字段非常多的请求体
2. 在请求体下点击json，然后下面菜单点击json-schema
3. 分别点击其下的模板和预览
4. 点击调试

**期待的正确结果**

模板和预览内容一致，且实际请求的内容也应该与此对应

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，这个问题目前不太好解决，我们先内部讨论一下

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/4300

**Comment by xulinde** [comment]
v10.5版本已修复
