### ISSUE TITLE
[BUG]接口测试的时候 在利用JSONPath断言的时候，“0”识别成“['0']”

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#427]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.2.1-b623
**Bug 描述**
简要描述您碰到的问题
接口测试的时候 在利用JSONPATH断言的时候，“0”识别成“['0']”
**Bug 重现步骤**
1. 调用一个接口
2. 断言
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
断言通过
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44960709/93438355-c6919500-f8ff-11ea-8a5e-c50d7f4892be.png)

图二：
![image](https://user-images.githubusercontent.com/44960709/93438651-2ee07680-f900-11ea-9ef1-f47c9c0b8b99.png)

**Comment by lingrance** [comment]
是不是JsonPath提取的都是Json字符串，所以断言的时候只要填写0，不用“”

**Comment by wangzhen-fit2cloud** [comment]
是的, 不需要加引号

**Comment by lingrance** [comment]
谢谢，问题已解决
