### ISSUE TITLE
The file /test/*.jmx doesn't exist or can't be opened

### ISSUE THREAD

**Issue by Shorelinewang** [metersphere/metersphere#4277]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.10.3
**Bug 描述**
性能测试，执行之后，状态一直是Starting，查看日志 显示“The file /test/*.jmx doesn't exist or can't be opened”
简要描述您碰到的问题

**Bug 重现步骤**

1.  第一次使用性能测试，在执行时提示我“无法运行测试，请前往 [系统设置-系统-系统参数设置] 检查当前站点配置”
2. 然后我就去更改了当前站点URL  写了 192.168.0.23:8182(这个是在浏览器中访问成功的)
3. 再去执行性能测试 还是跟刚才一样的提示
4. 然后我就把 当前站点URL 192.168.0.23:8182 改成了  http:ms.xxx.xxx(我们给配置好的域名)
5. 此时再次执行性能测试，发现 之前的报错提示没有了  但是状态一直是“starting”  而且查看日志，发现有一句提示“The file /test/*.jmx doesn't exist or can't be opened”

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![1](https://user-images.githubusercontent.com/45869515/124100890-6edca880-da91-11eb-9a1c-5750c6a619d3.jpg)
<img width="1092" alt="2" src="https://user-images.githubusercontent.com/45869515/124100915-73a15c80-da91-11eb-853e-3fcbe63a8db5.png">
<img width="923" alt="3" src="https://user-images.githubusercontent.com/45869515/124100931-7734e380-da91-11eb-887b-b7a1df09baf0.png">

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by liuruibin** [comment]
1. 在后台打开/opt/metersphere/logs/node-controller/info.log里找到
![image](https://user-images.githubusercontent.com/23045261/124456829-be86e100-ddbd-11eb-84ce-ed4e29c9aab2.png)
这样的信息
2. 直接下载看看是否能把执行需要的zip下载下来
3. 检查容器里的网络能否正常访问到这个地址
