### ISSUE TITLE
api启动测试计划，执行完成 取测试报告失败[BUG]

### ISSUE THREAD

**Issue by eechenyi** [metersphere/metersphere#4284]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  通过/test/plan/testplan/jenkins 接口去启动的测试计划
2. 测试计划返回状态为COMPLETED，且测试执行进度100%
3. 用返回报告ID 取测试报告结果 http://10.2.56.120:8081/test/plan/report/getMetric/502ca288-c3c0-401c-9c9f-b512f3051ae8  报错
4. 当测试计划有测试用例未执行(不知道何种原因未执行)时就取测试报告失败。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
测试计划执行jin进度
![image](https://user-images.githubusercontent.com/67175449/124107319-b23a1580-da97-11eb-82e3-8647db952e4a.png)
取测试报告界面有未执行测试用例就会报错
![image](https://user-images.githubusercontent.com/67175449/124107441-d0077a80-da97-11eb-8a67-7364277b0c86.png)
![image](https://user-images.githubusercontent.com/67175449/124107471-d85fb580-da97-11eb-96ed-79bb863cc1a9.png)
![image](https://user-images.githubusercontent.com/67175449/124107490-dc8bd300-da97-11eb-8865-a53b99040973.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.11已修复，建议您升级到最新版本在试下
