### ISSUE TITLE
[FEATURE]请求体中变量的类型支持数组、列表、JsonObject等的传递

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#4297]
**请描述您的需求或者改进建议.**
请求体中变量的类型是否能支持列表、JsonObject等； 满足一整个对象的传递，而不是一个个字段的传递
![image](https://user-images.githubusercontent.com/76902625/124114943-caae2e00-da9f-11eb-8779-9fda9462368d.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
收到，感谢您的建议，我们内部讨论下再反馈。

**Comment by Faerie1999** [comment]
> 收到，感谢您的建议，我们内部讨论下再反馈。

你好，请问这个需求目前可以实现吗？
