### ISSUE TITLE
[FEATURE]测试跟踪->测试计划 下面需要有测试套的子集，可以设置 测试套的执行顺序

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#4298]
**请描述您的需求或者改进建议.**

测试跟踪->测试计划 下面需要有测试套的子集，可以设置 测试套的执行顺序

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
可以选择串行执行

**Comment by Amber1700** [comment]
> 可以选择串行执行

我的使用场景是这样的：测试套内的用例需要并行执行，测试套之间能够串行
