### ISSUE TITLE
断言逻辑错误[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4299]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.3
**Bug 描述**
json断言，选择不等于断言，判断逻辑不对

**Bug 重现步骤**

1.  如下图进行断言判断，响应体返回值是123456，断言为不等于12345
![image](https://user-images.githubusercontent.com/30932762/124125876-a7d64680-daac-11eb-8c4b-de04be467969.png)
2. 按照断言结果应该为真，通过，但是结果显示断言失败
![image](https://user-images.githubusercontent.com/30932762/124125956-bfadca80-daac-11eb-86dc-42ed7bca2556.png)

**期待的正确结果**
断言正确

**Comment by zyyfit** [comment]
您好，这个问题也有其他用户提过，但是我们没有复现，能提供一下稳定复现方法吗

**Comment by plateauandsp** [comment]
我是用了MS的mock伪造了接口，接口里面有123456这个数值，然后用断言是判断不等于12345  从断言角度应该是OK的
