### ISSUE TITLE
json转json-schema丢数据[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4300]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.3
**Bug 描述**
json转json-schema丢数据

报文体如下：
{
    "APEListObject": {
        "APEObject": [
            {
                "ApeID": "31000000001190000001",
                "Name": "采集设备-1",
                "Model": "AP01",
                "IPAddr": "192.168.1.99",
                "IPV6Addr": "2001:0db8:0000:0042:0000:8a2e:0370:7334",
                "Port": 1000,
                "Longitude": 78.69,
                "Latitude": 63.59,
                "PlaceCode": "310000",
                "Place": "上海市虹梅路1",
                "OrgCode": "021",
                "CapDirection": "1",
                "MonitorDirection": "1",
                "MonitorAreaDesc": "监视区域",
                "IsOnline": "1",
                "OwnerApsID": "31000000005030000001",
                "UserId": "admin",
                "Password": "kedacom",
                "FunctionType": "2",
                "PositionType": "22"
            },
            {
                "ApeID": "31000000001190000002",
                "Name": "采集设备-2",
                "Model": "AP01",
                "IPAddr": "192.168.2.99",
                "IPV6Addr": "2001:0db8:0000:0042:0000:8a2e:0370:7334",
                "Port": 1000,
                "Longitude": 78.69,
                "Latitude": 63.59,
                "PlaceCode": "310000",
                "Place": "上海市虹梅路2",
                "OrgCode": "021",
                "CapDirection": "1",
                "MonitorDirection": "1",
                "MonitorAreaDesc": "监视区域",
                "IsOnline": "1",
                "OwnerApsID": "31000000005030000001",
                "UserId": "admin",
                "Password": "kedacom",
                "FunctionType": "2",
                "PositionType": "22"
            }
        ]
    }
}
**Bug 重现步骤**

1.  选择json导入后，在转为json-schema
![image](https://user-images.githubusercontent.com/30932762/124126186-013e7580-daad-11eb-9526-86e39d1f3251.png)

2.会丢掉第二个子集数据
![image](https://user-images.githubusercontent.com/30932762/124126248-11565500-daad-11eb-83e4-768e3fdfdd65.png)

**期待的正确结果**
在转化前应该先提示为json-schema格式不正确，如下图
![image](https://user-images.githubusercontent.com/30932762/124126342-29c66f80-daad-11eb-9140-556998615058.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
