### ISSUE TITLE
[BUG]接口定义查看api列表，提示 ：SQL error happened, please check logs.

### ISSUE THREAD

**Issue by newgrand-test** [metersphere/metersphere#4309]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.10.3-10ac86a0
**Bug 描述**

简要描述您碰到的问题
接口定义查看api列表，提示 ：SQL error happened, please check logs.
**Bug 重现步骤**

1.  登录
2. 点击 接口测试-接口定义-API tab页
3. 报 ：SQL error happened, please check logs. 异常。
4. 对应请求为 ：/api/definition/list/1/10

**期待的正确结果**
正常显示api 接口列表
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

![api](https://user-images.githubusercontent.com/51692013/124211317-7cd90a80-db1f-11eb-8ea2-2b6536132e05.png)

**Comment by xulinde** [comment]
您使用的是哪个版本呢，我用10.4版本没复现

**Comment by newgrand-test** [comment]
> 您使用的是哪个版本呢，我用10.4版本没复现

已经找群里的大佬解决了，version表升级有问题，缺少了字段。 这个可以关闭了
