### ISSUE TITLE
[BUG]JSON格式化时，值100.0会被格式化为100

### ISSUE THREAD

**Issue by assilzm** [metersphere/metersphere#431]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.2.1

**Bug 描述**
调试接口时，对返回的json文本格式化为json格式，如果一个值是"a":100.0，格式化以后会显示为"a":100

**期待的正确结果**
期望格式化以后正确显示为"a":100.0，不然以此为参考进行断言会导致出错

**Comment by xulinde2** [comment]
您好，v1.4.1版本该问题已修复，您升级到最新版本即可。
