### ISSUE TITLE
[BUG]接口测试，上传文件，content-type，被替换，有截图【新问题】

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#4310]
您所使用的 MeterSphere 版本是？
1.10.3

**Bug 描述**

**引用的场景接口**，上传文件失败，原来是 content-type被替换掉了

**Bug 重现步骤**

1.  新建一个场景（场景1），该场景可以上传文件
2.  新建一个场景（场景2），在场景2中，引用场景1
3.  执行场景2

**期待的正确结果**
场景2中引用的场景1，也能被成功执行

如果有截图，请附上截图.

成功截图：
**场景1的 content-type正常为：multipart/form-data，能够上传成功**
![image](https://user-images.githubusercontent.com/6467295/124211000-01775900-db1f-11eb-9c16-86d072eea599.png)

失败截图：

场景2中，**引用的场景1的上传接口**，它的content-type被修改成了 **application/json**
![image](https://user-images.githubusercontent.com/6467295/124210907-d7be3200-db1e-11eb-904a-33ff447ae9b2.png)

**Comment by xulinde** [comment]
感谢反馈，我们先复现下

**Comment by xulinde** [comment]
无法复现该问题
