### ISSUE TITLE
[BUG]设置环境参数：参数值的接在末尾的等号会被去掉

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#4311]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是  v1.10.3-10ac86a0

**Bug 描述**

设置环境参数：参数值的接在末尾的等号会被去掉

**Bug 重现步骤**

1.  vars.put(${__metersphere_env_id}+"token","=3=3==");
2. token的值为"=3=3"

**期待的正确结果**

2. token的值为"=3=3=="

**截图**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
