### ISSUE TITLE
[BUG]测试计划执行失败后没有二次执行的功能

### ISSUE THREAD

**Issue by nan1jueze** [metersphere/metersphere#4318]
您所使用的 MeterSphere 版本是？ v1.10.3

**Bug 描述**
测试计划执行失败后 没有 二次执行的功能，通过率大打折扣

简要描述您碰到的问题
**Bug 重现步骤**

1.  配置测试计划
2. 定时任务触发测试计划
3. 测试计划中不通过的较多
4. 二次执行可以通过，但是咱们系统没有二次执行失败的功能

**期待的正确结果**
增加测试计划执行失败的场景自动化加二次执行的能力

**Comment by zyyfit** [comment]
感谢反馈，我们调研一下相关需求
