### ISSUE TITLE
[BUG] 通过url导入swagger2.x解析数据出错，但是json文件可以

### ISSUE THREAD

**Issue by lovelivestyle1102** [metersphere/metersphere#432]
**MeterSphere 版本**
1.2.0
**Bug 描述**
不能解析swagger2.x

**Bug 重现步骤**
这是swagger的具体内容 {"openapi":"3.0.1","info":{"title":"质检api接口文档","description":"质检系统相关接口","version":"1.0"},"externalDocs":{"description":"参考文档","url":"https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations"},"servers":[{"url":"http://10.0.10.114:8888","description":"Generated server url"}],"paths":{"/student":{"post":{"summary":"新增学生信息接口","description":"新增学生信息接口","operationId":"createStudent","requestBody":{"description":"学生信息新增请求实体类","content":{"application/json":{"schema":{"$ref":"#/components/schemas/StudentBean"}}},"required":true},"responses":{"2000":{"description":"请求成功！","content":{"application/json":{"schema":{"$ref":"#/components/schemas/CommonResponse"}}}}}}},"/student/{id}":{"get":{"summary":"学生信息查询接口","description":"根据学生编号查询学生信息接口","operationId":"selectStudent","parameters":[{"name":"id","in":"path","description":"学生编号","required":true,"schema":{"type":"integer","format":"int32"}}],"responses":{"2000":{"description":"请求成功！","content":{"application/json":{"schema":{"$ref":"#/components/schemas/CommonResponse"}}}}}}},"/student/update":{"post":{"summary":"学生信息更新接口","description":"学生信息更新接口","operationId":"updateStudent","requestBody":{"description":"学生信息更新请求实体类","content":{"application/json":{"schema":{"$ref":"#/components/schemas/StudentUpdateBean"}}},"required":true},"responses":{"2000":{"description":"请求成功！","content":{"application/json":{"schema":{"$ref":"#/components/schemas/CommonResponse"}}}}}}}},"components":{"schemas":{"CommonResponse":{"type":"object","properties":{"code":{"type":"integer","description":"请求响应编码","format":"int32"},"message":{"type":"string","description":"请求响应消息"},"data":{"type":"object","description":"该次请求的真实结果实体类"},"count":{"type":"integer","description":"当请求接口为列表是，该字段才会有意义。该字段代表总数","format":"int32"}},"description":"封装统一返回实体类"},"StudentBean":{"required":["name"],"type":"object","properties":{"id":{"type":"integer","description":"学生编号","format":"int32"},"name":{"maxLength":20,"type":"string","description":"pet status in the store"},"age":{"maximum":200,"minimum":0,"type":"integer","description":"年龄","format":"int32"},"address":{"maxLength":500,"type":"string","description":"pet status in the store"}},"description":"学生信息请求bean"},"StudentUpdateBean":{"required":["id","name"],"type":"object","properties":{"id":{"type":"integer","description":"学生编号","format":"int32"},"name":{"maxLength":20,"type":"string","description":"学生信息"},"age":{"maximum":200,"minimum":0,"type":"integer","description":"年龄","format":"int32"},"address":{"maxLength":500,"type":"string","description":"地址"}}}}}}

**期待的正确结果**
能正确解析

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
你好，你这个好像不是 swagger2.x 的版本，应该是 3.x 吧
![image](https://user-images.githubusercontent.com/41557596/95820810-643f7f00-0d5b-11eb-9b40-976370773217.png)
