### ISSUE TITLE
[BUG]测试计划设置为串行执行，但是Jenkins调用测试计划的时候还是并行执行

### ISSUE THREAD

**Issue by nan1jueze** [metersphere/metersphere#4321]
您所使用的 MeterSphere 版本是？ v1.10.3

**Bug 描述**
测试计划设置为串行执行，但是Jenkins调用测试计划的时候还是并行执行

**Bug 重现步骤**
1.  配置测试计划为串行执行
2.  使用jenkins插件执行测试计划
3.  测试计划跑场景自动化还是并行

**期待的正确结果**
jenkins调用测试计划执行场景自动化应该按照测试计划的设置串行执行

**Comment by seasoncool** [comment]
我们也发现了这个问题，不知道在【批量执行】里面修改 【运行模式】（串行），能否起效？（目测没有生效。）

**Comment by five3** [comment]
插件和 ms服务都升级到v1.10.4试试

**Comment by nan1jueze** [comment]
已经修复
