### ISSUE TITLE
[BUG]建了用例评审，但是在首页的报表中，没有体现

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4332]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
v1.10.3-lts
您所使用的 MeterSphere 版本是？
v1.10.3-lts
**Bug 描述**

简要描述您碰到的问题
建了用例评审，但是在首页的报表中，没有体现，无论是我创建的，还是需要我评审的，都没有
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/84962582/124224084-95edb580-db37-11eb-90e0-776da6342ce0.png)
![image](https://user-images.githubusercontent.com/84962582/124224108-9d14c380-db37-11eb-814c-3f6280267ebf.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
