### ISSUE TITLE
[BUG]环境配置-http 配置启用条件是模板，接口测试的 CASE 中选择环境取不到 IP 和端口

### ISSUE THREAD

**Issue by EthanKk** [metersphere/metersphere#4344]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 1.10

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.设置环境
![image](https://user-images.githubusercontent.com/6426859/124233290-457d5480-db45-11eb-9c70-61e9ef06ae9b.png)

2. 接口测试-CASE-选择环境执行，发送的地址为空
![image](https://user-images.githubusercontent.com/6426859/124233498-79587a00-db45-11eb-94bf-40f15617a94f.png)

3. 但在接口测试-API-执行中直接调试没有问题
![image](https://user-images.githubusercontent.com/6426859/124233738-b7559e00-db45-11eb-8cfa-8ae578faf4a1.png)

**Comment by zyyfit** [comment]
您好，1.10.4版本已发布，请升级后试一下
