### ISSUE TITLE
[FEATURE]希望能在不同项目之间可以复制或移动用例

### ISSUE THREAD

**Issue by szfreewalk** [metersphere/metersphere#4345]
**请描述您的需求或者改进建议.**
当前不同项目之间不能复制或者移动用例，希望能在不同项目之间复制或移动用例

**请描述你建议的实现方案**
1、对于用例的复制，可以有两种方式：一是直接复制过去，二是只是建立映射关系，实际用例还在原来的项目
2、对于用例的移动，直接从原项目移动到目的项目，编号可以重新生成

**Comment by xulinde** [comment]
目前测试计划支持跨项目关联测试用例，您可以尝试操作下，看是否能满足您当前需求

**Comment by szfreewalk** [comment]
> 目前测试计划支持跨项目关联测试用例，您可以尝试操作下，看是否能满足您当前需求

这个需求本身不是测试计划管理方面的，而是测试用例管理方面的，类似有个测试用例基线一样，不同项目或版本只是从基线中引入，虽然导出再导入可以达成目的，但还是有点麻烦。

**Comment by xulinde** [comment]
收到，我们规划下
