### ISSUE TITLE
[BUG]性能测试报告概览和详情中的吞吐量/秒结果数据差距较大

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#435]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
性能测试报告概览和详情中的吞吐量/秒结果数据差距较大
如下图所示1为详细结果3935/s，2为概览结果1735.66/s，差距超过1倍

**截图**
<img width="1125" alt="111111" src="https://user-images.githubusercontent.com/21210217/93603397-8a8d2b80-f9f6-11ea-95d5-63e37c92df8d.png">

**Comment by liuruibin** [comment]
我们使用jmeter自己的generator来生成数据，你可使用 jmeter -g test.jtl -o ./test 来对比结果
