### ISSUE TITLE
[BUG]接口自动化的测试报告时间显示不一致

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#4355]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.3
**Bug 描述**

简要描述您碰到的问题
当接口自动化的场景步骤数量很多时，比如步骤数量达到几百时，测试报告的页面上显示的时间不致。步骤数量越多，时间相差越大。

**Bug 重现步骤**

1.  “接口测试”-》“测试报告”
2. 
3. 
4. 

**期待的正确结果**
每个步骤的测试报告应该是整个场景测试完成后，再
<img width="415" alt="图片 1" src="https://user-images.githubusercontent.com/18387151/124252236-533cd500-db59-11eb-95dc-0881398bf2ae.png">
批量写入到数据库，如果每个测试步骤单独写入，可能是导致报告时间不一致的原因

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
平台执行有自身数据组装，发送，和存储消耗，有时资源不足情况还会处理的慢。现在的计算是根据请求的发起时间到 结束时间 的时间差，统计出来的时间可能会跟实际运行的时间差有些差距，后续会优化

**Comment by xulinde** [comment]
1.12已优化
