### ISSUE TITLE
[BUG]性能测试-平台运行结果与jmeter运行结果存在较大差距

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#436]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
平台运行结果与jmeter运行结果存在较大差距

**Bug 重现步骤**
1.  在平台上执行一个dubbo接口的性能测试
2. 在同一个压测节点中直接使用jmeter执行同一个性能测试脚本
3. 观察两种方式的运行结果
4. 

**期待的正确结果**
结果应该接近，但实际结果差距接近3倍

**截图**
如果有截图，请附上截图.
<img width="1054" alt="5555" src="https://user-images.githubusercontent.com/21210217/93603942-4d756900-f9f7-11ea-9fae-2db393d5c15c.png">

**Comment by wangzhen-fit2cloud** [comment]
你好, 这个问题应该与我们使用了容器网桥网络来运行 jmeter 有关, 网桥网络相较于直接使用虚拟机网络会有一定的损耗, 目前我们正在研究怎么来解决这个问题

**Comment by rzsp8552** [comment]
> 你好, 这个问题应该与我们使用了容器网桥网络来运行 jmeter 有关, 网桥网络相较于直接使用虚拟机网络会有一定的损耗, 目前我们正在研究怎么来解决这个问题

这个问题在新版本中解决了么？

**Comment by wangzhen-fit2cloud** [comment]
你好，你可以修改下 node-controller 节点使用的镜像，改为下面这个镜像再试一下
registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.4.0-host

**Comment by nawentao** [comment]
> 你好，你可以修改下 node-controller 节点使用的镜像，改为下面这个镜像再试一下
> registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.4.0-host

请问是修改docker-compose-node-controller.yml文件中的以下配置配置么， image: ${MS_PREFIX}/ms-node-controller:v1.4.0-host
我修改成这个配置后，测试结果仍不理想，跟以前一样

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue #384  重复
