### ISSUE TITLE
[BUG]前端-接口请求路径中包含#时会被前端直接过滤掉，无法保存

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#437]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
创建一个接口请求，请求路径中包含#

**Bug 重现步骤**
1.  创建一个接口请求，请求路径中包含#，如：http://localhost:8081/#/api/test/edit?id=f0a102da-8f5b-4520-8cb3-029ff23f000c
2. url输入后会被前端自动过滤为http://localhost:8081/

**期待的正确结果**
建议#关键字能够正常输入并保存

**Comment by AgAngle** [comment]
你好，这个#是前端表示路由的路径，http请求是没有#的
