### ISSUE TITLE
[FEATURE] 测试计划中的功能测试用例列表页面，高级搜索条件支持测试用例状态，希望能查出失败的、阻塞的、跳过的

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#4371]
**请描述您的需求或者改进建议.**

高级搜索条件支持查找测试用例状态是失败的、阻塞的、跳过的

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
后面版本可以优化

**Comment by xulinde** [comment]
执行结果表头支持直接进行筛选
![image](https://user-images.githubusercontent.com/64065190/126744861-f51a2a14-3df0-425e-b7b9-279b9c6c1177.png)
