### ISSUE TITLE
[FEATURE]接口定义（批量添加header，query)操作简化一点

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4372]
**请描述您的需求或者改进建议.**

接口定义（批量添加header，query)，
1、需要能够复制粘贴；
2、必填之类的字段无需填写；
3、分隔符换一下，很多参数是带逗号的，导致解析失败
4、可以按照导入的顺序添加

![WechatIMG139](https://user-images.githubusercontent.com/32027713/124409825-b5752000-dd7b-11eb-9c21-514c6adefd56.png)

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下

**Comment by xulinde** [comment]
v1.13已优化
