### ISSUE TITLE
[BUG]接口设置JSON-SCHEMA，参数内容被转码

### ISSUE THREAD

**Issue by sky1984** [metersphere/metersphere#4374]
您所使用的 MeterSphere 版本是？
v1.10.4-221f275f
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建接口，录入参数内容（请求体是json），点击保存，点击
{
    "uuid": "test1",
    "password": "B6s+lezXo1Xh//IQ=="
}
2. 点击JSON-SCHEMA，在取消

测试结果：
请求体内容变成
{
    "password": "B6s+lezXo1Xh//IQ\u003d\u003d",
    "uuid": "test1"
}

期望结果：
请体参数内容不变

备注：转码后的接口可以测试通过，只是内容转码了

**Comment by zyyfit** [comment]
感谢反馈，相关问题 https://github.com/metersphere/metersphere/issues/4261

**Comment by xulinde** [comment]
v10.5版本已修复
