### ISSUE TITLE
[BUG]dubbo接口测试-Get Provider List功能无法使用

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#438]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
dubbo接口测试注册中心配置使用zk，Get Provider List功能无法使用

**Bug 重现步骤**
1.  填写完注册中心配置(zk)后，点击Get Provider List按钮

**期待的正确结果**
应该能够获取到接口服务信息(使用jmeter打开相同导出脚本，功能可以使用)

**截图**
如果有截图，请附上截图.
<img width="755" alt="22222" src="https://user-images.githubusercontent.com/21210217/93605842-db525380-f9f9-11ea-8267-d78de4a8d442.png">
![1600437043176](https://user-images.githubusercontent.com/21210217/93605846-ddb4ad80-f9f9-11ea-90f7-3333f6b21685.jpg)

**Comment by wangzhen-fit2cloud** [comment]
你好, 部署 metersphere 的服务器到 zookeeper 网络是否是通的呢

**Comment by nawentao** [comment]
> 你好, 部署 metersphere 的服务器到 zookeeper 网络是否是通的呢

网络是通的，目前问题没有再现
