### ISSUE TITLE
[BUG]dubbo接口测试-注册中心地址错误时，点击调试后导致后台一直重复请求

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#439]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
注册中心地址错误时，点击调试后导致后台一直重复请求

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
地址错误时直接返回请求失败信息，后台不应该一直重试

**截图**
<img width="1093" alt="33333" src="https://user-images.githubusercontent.com/21210217/93606809-1ef98d00-f9fb-11ea-8828-802ef4f38b21.png">

**Comment by q4speed** [comment]
已修复Dubbo插件
