### ISSUE TITLE
[BUG]使用嵌套的内建jmeter函数保存后请求body被隐藏

### ISSUE THREAD

**Issue by gongshengguang** [metersphere/metersphere#4392]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.0-93f6870d
**Bug 描述**
POST请求，body里面使用了${__RandomString(5,atoz1-0,NAME)}，且使用了两个内建函数进行嵌套如：${__longSum(${__time(/1000)},-86400)}，保存后再打开，body内容显示为空。

**Bug 重现步骤**

1.  新建一个步骤
2. 使用post请求，body格式如：
{
    "a": "自动化测试${__RandomString(5,abcdefghijklmnopwrstuvwxyz1234567890, NAME)}",
    "b": "200-310/1000",
    "start_time": ${__longSum(${__time(/1000)},-86400)},
    "end_time": ${__longSum(${__time(/1000)},+86400)}
}
3. 调式完后关闭
4. 再打开场景，打开新建的步骤

**期待的正确结果**

请求报文能正常显示

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们复现下

**Comment by xulinde** [comment]
JSON 格式错误正确应该是

{
    "a": "自动化测试${__RandomString(5,abcdefghijklmnopwrstuvwxyz1234567890, NAME)}",
    "b": "200-310/1000",
    "start_time": "${__longSum(${__time(/1000)},-86400)}",
    "end_time": "${__longSum(${__time(/1000)},+86400)}"
}
