### ISSUE TITLE
[FEATURE]Mock 服务自定义响应体，支持内置函数或者变量

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#4393]
**请描述您的需求或者改进建议.**

Mock 服务自定义响应体，支持内置函数或者变量

**请描述你建议的实现方案**
Mock 服务自定义响应体，支持内置函数或者变量
![wecom-temp-f5475f902dc6810656395675dc9836b0](https://user-images.githubusercontent.com/30038088/124470938-d7e45900-ddce-11eb-8dab-85f5342b2ac3.png)

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by zyyfit** [comment]
最新版已支持自定义脚本

**Comment by shenkaibo** [comment]
后续会支持么
