### ISSUE TITLE
[BUG]关联issue时提示 project issue template id is null.

### ISSUE THREAD

**Issue by Escape147** [metersphere/metersphere#4398]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.9.3

**Bug 描述**
关联issue时提示 project issue template id is null.

简要描述您碰到的问题

**Bug 重现步骤**

1. 测试计划-功能测试用例-选择并执行测试用例
2. 点击关联缺陷-添加缺陷
3. 输入相关信息
4. 点击确定

**期待的正确结果**
issue关联成功

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/86993268/124530782-bff8ed80-de3f-11eb-891b-d9be1733623c.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
使用10.4版本未复现该问题，您这边是必现的吗
