### ISSUE TITLE
[BUG]用户登录前端页面报错

### ISSUE THREAD

**Issue by kuangsumeng** [metersphere/metersphere#44]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.0.2-b357
**Bug 描述**
简要描述您碰到的问题
登录后系统会弹出
![image](https://user-images.githubusercontent.com/38234675/85939067-1423e480-b945-11ea-8f61-6f0a46eb0fba.png)

**Bug 重现步骤**
1.  登录系统，登录成功后提示如标题的错误
2. 团队空间中添加成员也会出现同一个错误
3. 团队、系统模块中均存在“工作空间”
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你这边是使用的外部数据库吗？ @kuangsumeng
