### ISSUE TITLE
[BUG] 配置环境中的header没有被实际使用

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#440]
**MeterSphere 版本**
版本: v1.2.1-b623

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  配置环境
![image](https://user-images.githubusercontent.com/6682310/93729306-862f6100-fbf6-11ea-970a-00172e009b26.png)

2. 在q请求中选择这个环境，但是请求发出时候，没有带这个header
![image](https://user-images.githubusercontent.com/6682310/93729357-baa31d00-fbf6-11ea-823f-a20c786b632d.png)

3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
1.3以上版本已修复，请升级验证
