### ISSUE TITLE
[BUG]接口场景中，某接口的断言是“不包含”，调试执行后发现只执行了部分接口，接口断言为“不包含”及其后面的接口未执行

### ISSUE THREAD

**Issue by zhangxia11** [metersphere/metersphere#4401]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.10.4-221f275f
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  场景中不包含的断言如下：
![image](https://user-images.githubusercontent.com/49543870/124532907-06e8e200-de44-11eb-994a-e65e386d3079.png)

2. 实际步骤数：
![image](https://user-images.githubusercontent.com/49543870/124532949-18ca8500-de44-11eb-8432-d8cf6b2a1693.png)

3. 调试执行后显示的结果：
![image](https://user-images.githubusercontent.com/49543870/124533006-2b44be80-de44-11eb-877a-41039c7c7357.png)

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
请问您是否开启了失败继续？如果没开启的话请查看一下是否断言失败了，有用户提过断言这个问题（断言不包含会断言失败）

**Comment by zhangxia11** [comment]
我是勾选了“失败继续”的

**Comment by xulinde** [comment]
未复现该问题，使用最新版本还会有此问题吗
