### ISSUE TITLE
定时同步页面样式优化

### ISSUE THREAD

**Issue by SCF123** [metersphere/metersphere#4402]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.4-221f275f
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  进入【接口测试】-【接口定义】-【更多操作】-【定时同步】页面，如下图
![image](https://user-images.githubusercontent.com/29427570/124534415-ce96d300-de46-11eb-95c0-290281500d8d.png)

**期待的正确结果**

正确情况下应该是什么样的？
框出的字段建议一行展示，会更美观些

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本优化下

**Comment by xulinde** [comment]
v10.5版本已优化
