### ISSUE TITLE
[BUG]个人信息中无法设置jira账户信息

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4407]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4/1.10.4-lts
**Bug 描述**
个人信息中无法设置jira账户信息
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/84962582/124543044-1cb3d280-de57-11eb-9eee-082cf5dfb72c.png)

**截图**
![image](https://user-images.githubusercontent.com/84962582/124543070-263d3a80-de57-11eb-8276-c9afc0b08a11.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
您是使用的10.4版本吗

**Comment by locust-zhang** [comment]
> 您是使用的10.4版本吗

是的，10.4和10.4-lts，都是新安装的，都有这个问题

**Comment by locust-zhang** [comment]
> 您是使用的10.4版本吗

问题复现了吗？

**Comment by xulinde** [comment]
未复现该问题，您是在线还是离线升级的
