### ISSUE TITLE
[BUG]自定义的接口，创建完后会有默认6s的超时时间，（导入的接口没有）

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#4408]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
升级遇到问题，还没有升级

您所使用的 MeterSphere 版本是？
 v1.8.2-d59d4b5f
**Bug 描述**

简要描述您碰到的问题
自定义的接口，创建完后会有默认6s的超时时间，（导入的接口没有）
![image](https://user-images.githubusercontent.com/77233754/124544038-f2fbab00-de58-11eb-9ca9-844e221c5f18.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
自定义的接口，创建完后会有没有默认的超时时间
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本优化下
