### ISSUE TITLE
[BUG]场景用例调试框的文字按钮信息堆积显示

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#4409]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

![image](https://user-images.githubusercontent.com/76902625/124545658-06f4dc00-de5c-11eb-9056-5617ebbdc22a.png)

**Bug 重现步骤**

1.  编辑场景用例-调试-编辑

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
怎么能稳定复现呢

**Comment by Amber1700** [comment]
> 怎么能稳定复现呢

同时打开多个场景用例，浏览其中一个用例步骤，再切换至其他场景用例 就能复现

**Comment by xulinde** [comment]
v10.5版本已修复
