### ISSUE TITLE
[FEATURE]报告优化

### ISSUE THREAD

**Issue by lilin-m** [metersphere/metersphere#441]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  看报告时，如果请求过多，导致看响应结果不好看（期望：请求过多时，添加滚动条）
2. 看报告时，如果请求过多，期望选中高亮显示；
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好, 能否贴以下截图

**Comment by lilin-m** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 中午1:48
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"李玲霞"<625734691@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]报告优化 (#441)





 
你好, 能否贴以下截图
