### ISSUE TITLE
[FEATURE]希望测试计划中负责人可以选择多人

### ISSUE THREAD

**Issue by liAnita** [metersphere/metersphere#4419]
**请描述您的需求或者改进建议.**
目前测试计划中的负责人只能选择一人，实际使用时可以会有多个人来执行该测试计划，所以希望可以支持负责人选择多人。
![image](https://user-images.githubusercontent.com/49704984/124568786-e470bc00-de77-11eb-82c6-d0634b5fe877.png)

**请描述你建议的实现方案**
1.支持负责人选择多人 或者 新增其他的字段，比如：相关人员，可以让测试计划关联到多人

**Comment by xulinde** [comment]
和#5542重复
