### ISSUE TITLE
[BUG]接口测试-接口自动化-多窗口下滑动，展示问题。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4428]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.4

**Bug 描述**接口测试-接口自动化-多窗口下滑动，展示问题。

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![微信图片_20210706174916](https://user-images.githubusercontent.com/14307013/124580396-a62cca00-de82-11eb-9e1a-854ecb712c01.png)

如果有截图，请附上截图.

**Comment by AgAngle** [comment]
已复现，下个版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
