### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#443]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.2.1-b623

**Bug 描述**
简要描述您碰到的问题
接口测试中点击“测试”模块中，保存和保存并执行，报错。

**Bug 重现步骤**
1. 从某个测试报告，点击某个“测试”业务
2. 再次点击“保存或保存并执行”

**期待的正确结果**
正确情况下应该是什么样的？
正常执行

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33744331/93751885-63ba3980-fc30-11ea-8223-91b909c123f6.png)

**Comment by AgAngle** [comment]
已修复，请升级至1.3以上版本
