### ISSUE TITLE
[BUG] 多页面编辑用例错乱

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4431]
**MeterSphere 版本**
 V1.10.3
**Bug 描述**

简要描述您碰到的问题
A页面在编辑用例的时候，B页面切换工作空间。再在A页面上保存用例，会把用例保存到切换后的工作空间。原工作空间里用例会被删除

.**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本修复
