### ISSUE TITLE
[FEATURE]针对测试计划、测试自动化场景，定时任务提供停止功能

### ISSUE THREAD

**Issue by sky1984** [metersphere/metersphere#4435]
测试步骤
1、创建A场景，里面放100个接口
2、执行A场景，等待了1个小时还没有跑完

期望结果：
测试计划、测试自动化场景，定时任务提供停止功能，这样可不需要等待，可以重新调试场景或者测试计划

备注：很急很关键的功能

**Comment by xulinde** [comment]
接口自动化有“失败继续”的功能，你可以取消勾选，如有失败的接口会停止测试

**Comment by sky1984** [comment]
> 接口自动化有“失败继续”的功能，你可以取消勾选，如有失败的接口会停止测试

需要的是随时可以终止执行的“功能”，不是要等待接口自己报错然后停止

**Comment by xulinde** [comment]
1.12已支持该功能，您可以升级版本体验下
