### ISSUE TITLE
[BUG]创建的场景接口测试，执行的时候，请求参数没有发送

### ISSUE THREAD

**Issue by yuanrong01** [metersphere/metersphere#4437]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.3v

**Bug 描述**
创建的场景接口测试，不知道什么原因，突然 发送请求的时候，请求参数是空的
简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景测试，并且都已经调试通过了，也都能执行
2. 过了一段时间，我也不知道操作了什么导致，再次执行的时候 一直报 没有拿到请求参数
3. 我重新将这个不能执行的场景复制了一份，执行还是不行
4. 我又重新创建了一个新的其他的场景，重新手动录入接口，用同样的接口，参数什么都相同，能执行通过
5. 就是老的那个再获取不到请求参数了

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/71748061/124585874-551fd480-de88-11eb-904a-ea134b22581d.png)
![image](https://user-images.githubusercontent.com/71748061/124585911-5d780f80-de88-11eb-96fc-c491f75242aa.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
收到，我们先复现下

**Comment by xulinde** [comment]
未复现该问题
