### ISSUE TITLE
[BUG] JSON-SCHEMA解析报错

### ISSUE THREAD

**Issue by anjun** [metersphere/metersphere#4443]
您所使用的 MeterSphere 版本是？

> v1.10.4-b2，v1.10.4-lts

**Bug 描述**
切换JSON-SCHEMA时候报

**Bug 重现步骤**

1.  任意接口编辑页面，从json格式数据切换到JSON-SCHEMA，再关闭JSON-SCHEMA必定报错

**期待的正确结果**

正确情况下应该是什么样的？
无报错

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/5170495/124692277-e0907880-df0f-11eb-93e4-0232f9cce78d.png)
![image](https://user-images.githubusercontent.com/5170495/124692296-ed14d100-df0f-11eb-9f55-5663874d1f7a.png)

**Comment by anjun** [comment]
查看了容器里面的这个类是存在的，本地开发环境是正常的。

**Comment by xulinde** [comment]
未复现该问题
