### ISSUE TITLE
[FEATURE]测试用例评审活动中，测试用例的预期结果实际结果的区域非常小，若测试用例内容较多时，还需要上下拉动，建议调整。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4446]
**请描述您的需求或者改进建议.**
测试用例评审活动中，测试用例的预期结果实际结果的区域非常小，若测试用例内容较多时，还需要上下拉动。见下图。

**请描述你建议的实现方案**
调整大一些测试用例评审的内容。
![微信图片_20210707111206](https://user-images.githubusercontent.com/14307013/124694677-5565b180-df14-11eb-88ed-17ffa68940b4.png)

**Comment by xulinde** [comment]
您可以修改类型为文本描述
![image](https://user-images.githubusercontent.com/64065190/124729358-f5d2ca80-df42-11eb-9120-2105a56e9f9c.png)

**Comment by billguo** [comment]
1， 导入的测试用例，默认为步骤方式，若修改为文本描述，内容丢失。
2， 测试用例评审中，无法修改为文本描述，见下图。
请问，应该如何操作。谢谢。
![导入测试用例，默认是步骤方式，测试计划中评审无法更改展示方式](https://user-images.githubusercontent.com/14307013/124737250-59142b00-df4a-11eb-9eee-aeeefc9437d8.png)
