### ISSUE TITLE
[BUG]测试用例评审活动中，需要修改测试用例内容，没有入口实现，只能写备注，二次进行修改

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4447]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.4

**Bug 描述**
![微信图片_20210707111206](https://user-images.githubusercontent.com/14307013/124694780-85ad5000-df14-11eb-8885-45343b5f0d13.png)。见下图。

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们内部讨论下后续是否支持该功能

**Comment by billguo** [comment]
1.10.5版本上还没有该功能。
