### ISSUE TITLE
[BUG]测试用例导入的原Excel文件是带有换行符，导入后换行符没有了，全部内容都在一起。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4448]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.4

**Bug 描述**测试用例导入的原Excel文件是带有换行符，导入后换行符没有了，全部内容都在一起。见下图。
![微信图片_20210707111511](https://user-images.githubusercontent.com/14307013/124694886-b7261b80-df14-11eb-9fc3-b049913219e7.png)

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
已知问题，下个版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
