### ISSUE TITLE
[FEATURE]改进权限管理模型，合理放置各项设置的入口

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4461]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
能否详细描述下

**Comment by locust-zhang** [comment]
> 能否详细描述下
1，不明白为什么要有组织-工作空间-项目这么多级别，而按照官方的建议，组织对应部门，工作空间对应项目组，又支持不了我们的现状：有多套的jira，一个项目里有多个测试，各自有自己的jira账号，想做到ms跟jira的集成
2，新建账号，需要配每个级别的权限角色，比较麻烦
3，能否，只有一个项目级别，项目的管理员能配置跟这个项目相关的所有设置，也能管理项目的账号，项目成员，就使用所有跟测试相关的功能就好

**Comment by locust-zhang** [comment]
消息设置放在组织层级下，如果有多个项目，每个项目都有个性化的消息设置，那就每个项目都必须有自己单独的组织-工作空间-项目这3级租户，这样感觉很奇怪

**Comment by locust-zhang** [comment]
另外，我提了好多权限相关的bug，总之，目前，这套权限管理模型在我司基本不可用，这也是我司没有购买企业版的一个重要原因

**Comment by wangzhen-fit2cloud** [comment]
> > 能否详细描述下
> > 1，不明白为什么要有组织-工作空间-项目这么多级别，而按照官方的建议，组织对应部门，工作空间对应项目组，又支持不了我们的现状：有多套的jira，一个项目里有多个测试，各自有自己的jira账号，想做到ms跟jira的集成
> > 2，新建账号，需要配每个级别的权限角色，比较麻烦
> > 3，能否，只有一个项目级别，项目的管理员能配置跟这个项目相关的所有设置，也能管理项目的账号，项目成员，就使用所有跟测试相关的功能就好

1. 在最新的版本的版本中优化了这个地方，每个用户可以在个人信息中配置 Jira 账号，提交缺陷时用各自配置的账号来调用接口。
目前组织-工作空间的层级是多了些，部分设置也存在不合理的地方，我们会持续优化这部分功能。
