### ISSUE TITLE
[BUG]【接口测试】从测试报告进入测试用例后点击保存和执行等操作没有反应，不能保存更新操作，需要刷新网页

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#447]
**MeterSphere 版本**
1.2.1

**Bug 描述**
执行接口测试查看报告后，再次进入测试界面，点击保存等操作无反应

**Bug 重现步骤**
1.  执行测试集合A
2. 查看生产的测试报告
3. 点击接口测试-》进入上一步执行的接口用例
4. 更新内容-》点击保存

**期待的正确结果**
保存更新操作并提示保存成功

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好, 将在 1.3 版本中解决该问题

**Comment by AgAngle** [comment]
已修复，请更新至1.3以上版本
