### ISSUE TITLE
[BUG]【ubuntu】docker-compose 版本与配置文件不兼容，请重新安装最新版本的 docker-compose

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#4480]
**MeterSphere 版本**
版本:   v1.10.4-221f275f

您所使用的 MeterSphere 版本是？
版本:   v1.10.4-221f275f

**Bug 描述**
在 Ubuntu 18.04.4 LTS 系统下，安装报错。

![image](https://user-images.githubusercontent.com/6467295/124852670-3b40d780-dfd7-11eb-88f4-7a78488dff37.png)

**Comment by seasoncool** [comment]
已解决。
如果出现docker-compose文件版本不正确导致安装失败，需要将安装包metersphere下的所有docker-compose文件，复制到安装目录下 如：sudo cp ./metersphere/docker-compose-* /opt/metersphere/,最后再 msctl config一下

**Comment by snowyfang** [comment]
> 已解决。
> 如果出现docker-compose文件版本不正确导致安装失败，需要将安装包metersphere下的所有docker-compose文件，复制到安装目录下 如：sudo cp ./metersphere/docker-compose-* /opt/metersphere/,最后再 msctl config一下

你好，想请教一下，这个问题出现的原因是什么呢？是需要复制整个tmp/metersphere-v1.x/docker整个文件夹到/opt/metersphere/下么？

**Comment by seasoncool** [comment]
你好，@snowyfang 。
我们也不确定什么原因出现的。
先复制 docker-compose-*的文件，再config 下，如果还有报错，就把其它的文件夹也复制进去 再 config 下，应该有改善。
