### ISSUE TITLE
[BUG] 测试跟踪>>测试用例列表，其创建人读取的是ID不是人员名字。显示同负责人为人员名字

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#4481]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？V1.10.4

**Bug 描述**
测试跟踪>>测试用例列表，其创建人读取的是ID不是人员名字。显示同负责人为人员名字

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

创建人显示为人员姓名而不是ID，同负责人显示。

**截图**

![image](https://user-images.githubusercontent.com/78218624/124853151-ff5a4200-dfd7-11eb-8c08-e1797aa5c270.png)

**Comment by xulinde** [comment]
后边版本统一下

**Comment by xulinde** [comment]
v10.5版本已统一显示成名称
