### ISSUE TITLE
[BUG]工作空间管理员，向工作空间中，添加成员，自动跳转至个人信息页面

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4482]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**
新建了账号，授予工作空间管理员角色，再用这个账号，向工作空间中，添加成员时，自动跳转至个人信息页面
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by locust-zhang** [comment]
不止上面这一种情况，还有，新建了账号，授予组织管理员角色，再用这个账号，向组织中，添加成员时，自动跳转至个人信息页面

**Comment by xulinde** [comment]
v10.5版本已修复
