### ISSUE TITLE
[FEATURE]建议增加常用脚本收藏功能

### ISSUE THREAD

**Issue by TaoJiandong** [metersphere/metersphere#4484]
**请描述您的需求或者改进建议.**
针对整个项目通用的脚本，单个接口测试的时候重复复制粘贴使用体验不佳。建议能够添加一个常用脚本收藏功能。

**请描述你建议的实现方案**
用户能够保存常用的脚本，并在前置脚本，后置脚本等模块中可以通过选中该脚本直接带入，简化操作，提升用户体验。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by Amber1700** [comment]
> 感谢反馈，我们先进行下相关调研。

建议+1

**Comment by xulinde** [comment]
v1.13已支持 创建代码片段，在场景中可以插入
