### ISSUE TITLE
[FEATURE]接口测试或接口自动化测试中，自定义的变量能在一个页面上显示或管理，能查看或看到都定义了哪些变量

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#4485]
**请描述您的需求或者改进建议.**

接口测试或接口自动化测试中，自定义的变量能在一个页面上显示或管理，在一个地方能查看或看到都定义了哪些变量

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您可以把变量统一设置到环境里
