### ISSUE TITLE
[BUG]系统设置，用户组与权限中，取消组织/工作空间管理员的添加/编辑/移除成员权限，只保留查询成员，但是在组织->工作空间/工作空间->项目管理菜单中，从成员数量进入后的页面里，还有能够添加/编辑/移除成员

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4488]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**
[BUG]系统设置，用户组与权限中，取消组织/工作空间管理员的添加/编辑/移除成员权限，只保留查询成员，但是在组织->工作空间/工作空间->项目管理菜单中，从成员数量进入后的页面里，还有能够添加/编辑/移除成员
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/124865855-055b1d80-dfee-11eb-9ebf-b226c4870e4a.png)

![image](https://user-images.githubusercontent.com/84962582/124865815-f70d0180-dfed-11eb-8916-5f70050f3c69.png)

![image](https://user-images.githubusercontent.com/84962582/124866260-b5c92180-dfee-11eb-8627-25c93748440e.png)

**Comment by locust-zhang** [comment]
而在系统设置，用户组与权限中，修改组织“成员”的权限，如附件1，再从组织->工作空间->成员数量进入后的页面里，这个情况就是正常的，对应的，修改工作空间“成员”的权限，如附件2，再从工作空间->项目管理->成员数量进入后的页面里，这个情况就如同上面说的管理员的权限bug一样，又是不正常的了，
![image](https://user-images.githubusercontent.com/84962582/124868662-a3e97d80-dff2-11eb-8353-594702dc3af1.png)
![image](https://user-images.githubusercontent.com/84962582/124868766-d3988580-dff2-11eb-846f-5935c86762aa.png)

**Comment by xulinde** [comment]
10.6已修复
