### ISSUE TITLE
[BUG]编辑工作空间成员的权限角色，取消服务集成和消息设置的编辑权限，并授权给用户，但该用户，还是可以编辑

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4489]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**

简要描述您碰到的问题
编辑工作空间成员的权限角色，取消服务集成和消息设置的编辑权限，并授权给用户，但该用户，还是可以编辑
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/124869457-d47de700-dff3-11eb-9940-e529d2644572.png)
![image](https://user-images.githubusercontent.com/84962582/124869548-f2e3e280-dff3-11eb-8d48-5a32c3aab483.png)

**Comment by xulinde** [comment]
感谢反馈，下个小版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
