### ISSUE TITLE
[BUG]编辑了工作空间成员权限，模板设置仅保留了查看权限，并授权给用户，但该用户，系统设置-工作空间下，看不到模板

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4490]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**
编辑了工作空间成员权限，模板设置仅保留了查看权限，并授权给用户，但该用户，系统设置-工作空间下，看不到模板
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/124869769-422a1300-dff4-11eb-8c31-b951a5bf546e.png)
![image](https://user-images.githubusercontent.com/84962582/124869930-83babe00-dff4-11eb-9424-fa870c0c5e37.png)

**Comment by xulinde** [comment]
感谢反馈，我们现复现下

**Comment by xulinde** [comment]
v10.5版本已修复
