### ISSUE TITLE
[BUG]在接口定义下，删除接口，再在回收站内恢复，发现回收的那个接口丢了，数量也对不上

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4493]
**MeterSphere 版本**
V1.10.4

简要描述您碰到的问题

在接口定义下，删除接口，再在回收站内恢复，发现回收的那个接口丢了，数量也对不上

**Bug 重现步骤**

1.  
2. 
3. 
4. 
**截图**

<img width="1439" alt="WechatIMG143" src="https://user-images.githubusercontent.com/32027713/124870913-fbd5b380-dff5-11eb-890b-6ac463990a8e.png">

**Comment by xulinde** [comment]
问题复现，下个版本修复

**Comment by xulinde** [comment]
问题复现，下个版本修复

**Comment by xulinde** [comment]
v10.5版本已修复
