### ISSUE TITLE
[BUG] 仅修改mysql端口，ms-server 启动异常

### ISSUE THREAD

**Issue by woo-yun** [metersphere/metersphere#45]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是  V1.0.2

**Bug 描述**
修改  install.conf   中 mysql 端口为3308，执行install.sh 脚本, ms-server 启动异常。

**Bug 重现步骤**
1.  修改  install.conf   中 mysql 端口为3308;
2. 将docker-compose-mysql.yml 的端口也修改为3308
3. 执行install.sh 脚本;
4. msctl status;

**期待的正确结果**
服务正常启动

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/40296884/85940490-45091700-b94f-11ea-97ef-200293d784cb.png)
![image](https://user-images.githubusercontent.com/40296884/85940506-6964f380-b94f-11ea-9937-acfa75f73b4a.png)

**Comment by wangzhen-fit2cloud** [comment]
已确认，将在下个版本中修复

**Comment by AgAngle** [comment]
install.conf 里默认是连容器内部的 3306 端口，如果 MS_MYSQL_HOST 用的是容器名称 mysql ，MS_MYSQL_PORT 就不要改，如果 3306 端口跟宿主机冲突了，就改下 docker-compose-mysql.yml 里的宿主机的端口，或者直接去掉端口映射，不影响服务的数据库访问，下个版本就不爆露 3306 了，有需要再自行添加映射。
## 数据库地址
MS_MYSQL_HOST=mysql
## 数据库端口
MS_MYSQL_PORT=3306
