### ISSUE TITLE
[BUG] 从postman导入用例后，预、后执行脚本缺失

### ISSUE THREAD

**Issue by wonderfulwxw** [metersphere/metersphere#450]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.2.1-b623

**Bug 描述**
从postman导入用例后，预、后执行脚本缺失

**Bug 重现步骤**
1.  新建接口测试
2.  导入
3. 从postman文件导入（v2.1 collection file）
4. 导入成功后，查看预执行脚本和后执行脚本

**期待的正确结果**
预执行脚本和后执行脚本都应该被成功导入

**截图**
metersphere: 
![image](https://user-images.githubusercontent.com/38770463/93868827-9b42e780-fcfd-11ea-9e34-91072f398ff5.png)

postman:
![image](https://user-images.githubusercontent.com/38770463/93868869-a7c74000-fcfd-11ea-9c40-e7e0031a25b6.png)
![image](https://user-images.githubusercontent.com/38770463/93868900-aeee4e00-fcfd-11ea-8ca6-4fa6ea59f749.png)

**Comment by wangzhen-fit2cloud** [comment]
你好, 目前导入 postman 脚本的方式不支持导入前后置脚本, 同时由于我们平台与 postman 前后置脚本的实现方式不一样, 即使保留了前后置脚本内容也无法正常执行

**Comment by wonderfulwxw** [comment]
oh 这样真的太可惜了。
