### ISSUE TITLE
由当前工作空间切换到其他工作空间,无法返回到初始工作空间[BUG]

### ISSUE THREAD

**Issue by shisanTJ** [metersphere/metersphere#4505]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.4-221f275f
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  登录自己账号所在的工作空间
2. 点击工作空间下拉选择切换到其他的工作空间
3. 此时工作空间选择项消失,需要退出账号,在重新登录才会回到初始工作空间
4. 

**期待的正确结果**
工作空间不消失,在不需要退出账号的前提下,可自由切换工作空间
正确情况下应该是什么样的？

**截图**

**Comment by xulinde** [comment]
未复现该问题，您是用的最新版本吗

**Comment by Amber1700** [comment]
> 未复现该问题，您是用的最新版本吗

我司也是用的v1.10.4， 这个问题的关键 在于 这个账号没有这个工作空间的权限，但是在空间切换的时候又可以看到所有工作空间并且切换，切换之后组织和工作空间的选择空间都会消失
![image](https://user-images.githubusercontent.com/76902625/125032339-681ce980-e0c0-11eb-8e11-73628a2d1312.png)

**Comment by zyyfit** [comment]
您好，1.10后面的版本对用户组权限进行了一些bug修复和优化，我用1.12.3看着没有这个问题了，您可以看看最新版还有没有这个问题

**Comment by shisanTJ** [comment]
好的  辛苦优化


| |
十三画一个我
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年9月23日 ***@***.***> 写道：

您好，1.10后面的版本对用户组权限进行了一些bug修复和优化，我用1.12.3看着没有这个问题了，您可以看看最新版还有没有这个问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
