### ISSUE TITLE
[FEATURE]接口定义中，切换协议，模块需要重新创建；貌似应该反过来，模块对于业务模块，在业务下，区分不同的协议，所以在切换协议的时候，已经存在的模块是可以共享的，不需要再次创建

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#4509]
**请描述您的需求或者改进建议.**

接口定义中，切换协议，模块需要重新创建；貌似应该反过来，模块对于业务模块，在业务下，区分不同的协议，所以在切换协议的时候，已经存在的模块是可以共享的，不需要再次创建

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
这里目前是是这样设计的，后面看下能否优化

**Comment by xulinde** [comment]
这里目前是是这样设计的，后面看下能否优化
