### ISSUE TITLE
[BUG]启动后 ms-data-streaming无法启动

### ISSUE THREAD

**Issue by mazl** [metersphere/metersphere#453]
**MeterSphere 版本**
1.2.1

**Bug 描述**
启动后  ms-data-streaming无法启动

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/3139609/93876298-35f4f380-fd09-11ea-9314-acbbc73271fd.png)

**Comment by wangzhen-fit2cloud** [comment]
你好, 请问现在状态是否正常?
data-streaming 启动需要依赖 kafka 正常运行, 造成该问题原因可能是 kafka 启动较慢, 在检测时间内未正常运行, 可以等待一段时间后执行 msctl status 命令再次查看服务状态

**Comment by mazl** [comment]
> 你好, 请问现在状态是否正常?
> data-streaming 启动需要依赖 kafka 正常运行, 造成该问题原因可能是 kafka 启动较慢, 在检测时间内未正常运行, 可以等待一段时间后执行 msctl status 命令再次查看服务状态
