### ISSUE TITLE
[BUG]接口自动化中引用了接口case或接口场景，导出后再导入，引用会变成复制

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#4544]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.4
**Bug 描述**
接口自动化导出之前如果是引用关系，那么再次导入到原路径，希望保留引用关系

现状是导出再导入后，引用关系都变成了复制

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
接口自动化中引用了接口case或接口场景，先导出再导入后，能保持原先的引用关系

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1146" alt="1" src="https://user-images.githubusercontent.com/18387151/125024943-4fa6d200-e0b4-11eb-9b18-dd2cf2748f79.png">
<img width="1120" alt="2" src="https://user-images.githubusercontent.com/18387151/125024989-664d2900-e0b4-11eb-939f-d518505f5ffb.png">

**Comment by zyyfit** [comment]
重复bug
