### ISSUE TITLE
从已执行自动化测试报告再次返回接口测试页面，点击保存无效

### ISSUE THREAD

**Issue by peterzhanghao** [metersphere/metersphere#455]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  点击保存并执行，生成测试报告
2. 点击测试报告页面的接口项目，返回接口页面
3. 再次点击保存或保存并执行，没有反应
4. 

**期待的正确结果**
正确情况下应该是什么样的？
可以正常保存或保存并执行
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/61137241/93955205-cbcc6500-fd81-11ea-9ecb-dfd762695460.png)

**Comment by fit2-zhao** [comment]
已经修复该缺陷
