### ISSUE TITLE
[BUG]性能测试：包含断言在性能测试的条件下不能正常判断，在场景用例中连跑是正常

### ISSUE THREAD

**Issue by Amber1700** [metersphere/metersphere#4550]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.4
**Bug 描述**

用例在场景中执行正常，以该场景用例创建性能测试，断言中的包含逻辑判断不正确

**Bug 重现步骤**

1.  场景中的用例断言含有 包含断言 ，以此创建性能测试
 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这边没有复现，具体是什么断言呢？方便截图看一下吗

**Comment by Amber1700** [comment]
> 您好，这边没有复现，具体是什么断言呢？方便截图看一下吗

![image](https://user-images.githubusercontent.com/76902625/125718079-dcca7af5-fc79-4a82-b642-4afff6438f65.png)
