### ISSUE TITLE
[需求]【接口】报告支持批量删除，接口测试和性能测试生产的报告可以批量删除

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#456]
因为接口和性能经常使用的情况下，报告会非常多，一个一个删除不是很方便

![image](https://user-images.githubusercontent.com/13564069/93962591-beb57300-fd8d-11ea-8c93-3fa4e57e6cfc.png)

**Comment by wangzhen-fit2cloud** [comment]
将在 1.3.0 中支持

**Comment by Ammyz** [comment]
已支持
