### ISSUE TITLE
[BUG]通过json提取的值，被转义了，和原始返回值不一致

### ISSUE THREAD

**Issue by sky1984** [metersphere/metersphere#4565]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1

测试步骤：
1、测试接口A，返回值
{\"code\":0,\"data\":{\"documentId\":\"60e812938199645dbaea7638\",\"processDefId\":\"SupplierBargain:5:f67f309e-da0e-11eb-adaa-72b08565c54e\",\"processKey\":\"SupplierBargain\",\"processInstId\":\"8a0deff3-e095-11eb-90e4-3e24868e4a7e\",\"processVariables\":{\"route\":\"submit\",\"supplierQuotation\":[{\"code\":\"PA100219\",\"name\":\"B508\",\"type\":1}],\"adjustPriceApprove\":[{\"code\":\"PA100219\",\"name\":\"SRM\",\"type\":1}],\"adjustPriceApprove_cc\":[]},\"route\":\"submit\",\"title\":\"B508 3878000 调价申请 20210708\",\"docNum\":\"GYSXZ0-2021070900019-YJ001\",\"securityLevel\":\"绝密\",\"ver\":1,\"configVersion\":5,\"issuerCode\":\"CN3102396\",\"issuerName\":\"A095-3\",\"currentHandlerCode\":\"PA100219\",\"currentHandlerName\":\"SRM\",\"docState\":\"adjustPriceApprove\",\"docStateCn\":\"调价审批\",\"docStateEn\":\"adjustPriceApprove\",\"checkout\":false,\"url\":\"http://arm-uat.com/#/adjustPriceApply/${tsupplierOptionId}\",\"createdBy\":\"CN3102396\",\"updatedBy\":\"CN3102396\",\"createdByName\":\"A095-3\",\"updatedByName\":\"A095-3\",\"host\":\"192.16.73.130\",\"sendTodo\":false},\"message\":\"Request Success\"}

2、通过接口获取改返回值，从页面看到的返回值为
{"code":0,"data":{"documentId":"60e812938199645dbaea7638","processDefId":"SupplierBargain:5:f67f309e-da0e-11eb-adaa-72b08565c54e","processKey":"SupplierBargain","processInstId":"8a0deff3-e095-11eb-90e4-3e24868e4a7e","processVariables":{"route":"submit","supplierQuotation":[{"code":"PA100219","name":"B508","type":1}],"adjustPriceApprove":[{"code":"PA100219","name":"SRM","type":1}],"adjustPriceApprove_cc":[]},"route":"submit","title":"B508 3878000 调价申请 20210708","docNum":"GYSXZ0-2021070900019-YJ001","securityLevel":"绝密","ver":1,"configVersion":5,"issuerCode":"CN3102396","issuerName":"A095-3","currentHandlerCode":"PA100219","currentHandlerName":"SRM","docState":"adjustPriceApprove","docStateCn":"调价审批","docStateEn":"adjustPriceApprove","checkout":false,"url":"http://arm-uat.com/#/adjustPriceApply/${tsupplierOptionId}","createdBy":"CN3102396","updatedBy":"CN3102396","createdByName":"A095-3","updatedByName":"A095-3","host":"192.16.73.130","sendTodo":false},"message":"Request Success"}

**Comment by sky1984** [comment]
原始返回值
{
 "status": true,
 "data": "{\"code\":0,\"data\":{\"documentId\":\"60e821688199645dbaea76cb\",\"processDefId\":\"SupplierBargain:5:f67f309e-da0e-11eb-adaa-72b08565c54e\",\"processKey\":\"SupplierBargain\",\"processInstId\":\"61287cec-e09e-11eb-90e4-3e24868e4a7e\",\"processVariables\":{\"route\":\"submit\",\"supplierQuotation\":[{\"code\":\"PA100219\",\"name\":\"B508\",\"type\":1}],\"adjustPriceApprove\":[{\"code\":\"PA100219\",\"name\":\"SRM\",\"type\":1}],\"adjustPriceApprove_cc\":[]},\"route\":\"submit\",\"title\":\"B508 3878000 调价申请 20210708\",\"docNum\":\"GYSXZ0-2021070900023-YJ001\",\"securityLevel\":\"绝密\",\"ver\":1,\"configVersion\":5,\"issuerCode\":\"CN3102396\",\"issuerName\":\"A095-3\",\"currentHandlerCode\":\"PA100219\",\"currentHandlerName\":\"SRM\",\"docState\":\"adjustPriceApprove\",\"docStateCn\":\"调价审批\",\"docStateEn\":\"adjustPriceApprove\",\"checkout\":false,\"url\":\"http://arm-uat.com/#/adjustPriceApply/${tsupplierOptionId}\",\"createdBy\":\"CN3102396\",\"updatedBy\":\"CN3102396\",\"createdByName\":\"A095-3\",\"updatedByName\":\"A095-3\",\"host\":\"172.16.73.130\",\"sendTodo\":false},\"message\":\"Request Success\"}",
 "msg": "操作成功",
 "code": 200,
 "reportTitleList": null,
 "errorList": null
}

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，您使用的版本是1.9.1吗？目前最新版已经是1.10.4了，请先升级后试一下还有没有问题

**Comment by zyyfit** [comment]
您好，我这边试过了，是没有问题的，这是原始页面和chrome里的返回值
![image](https://user-images.githubusercontent.com/73461316/125555811-b13dfa54-7c3a-4de1-8555-a2253c9f24c5.png)

这是ms里的返回值
![image](https://user-images.githubusercontent.com/73461316/125555901-1cea8f98-a08b-4507-bdda-fb11b82294ae.png)
