### ISSUE TITLE
[BUG]接口测试，不知道什么情况下，执行接口测试的时候，路径上自动带了/mock/8d771957-e411-4360-b061-38e7d5e84db6

### ISSUE THREAD

**Issue by liyunfeng666** [metersphere/metersphere#4566]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本: v1.10.0-93f6870d
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，您选择环境时是否选择了mock环境？或者您使用的环境是是直接复制的mock环境吗？
