### ISSUE TITLE
[BUG]普通用户（项目管理员分组权限）点击“添加成员”，在闪出“添加用户”之后，就会跳转到个人中心。

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#4572]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v10.4
**Bug 描述**
**普通用户（**项目管理员分组权限**）点击“添加成员”，在闪出“添加用户”之后，就会跳转到个人中心。**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
<img width="934" alt="wecom-temp-67880d72daf4c63940524faa4b90da3b" src="https://user-images.githubusercontent.com/30038088/125075875-c2826e00-e0f1-11eb-8220-1d4c9da250ab.png">
2.
<img width="889" alt="wecom-temp-d8a8b87c751db658f82c6b509db7bf77" src="https://user-images.githubusercontent.com/30038088/125075902-cb733f80-e0f1-11eb-90ed-284a2aa4754d.png">

3.
<img width="902" alt="wecom-temp-8dac1c4f4c4e483f77e25134a5f187d2" src="https://user-images.githubusercontent.com/30038088/125075922-d1692080-e0f1-11eb-9780-8d6713b00b23.png">

4. 

**期待的正确结果**

正确情况下应该是什么样的？
正常添加用户，不会跳到个人中心
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是必现的吗？这边没有复现呢

**Comment by shenkaibo** [comment]
用只有项目管理员的权限 用户 复现此问题

**Comment by xulinde** [comment]
10.6已修复
