### ISSUE TITLE
接口定义-用例导出为MS格式，然后再导入，模块中的内容是空的[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4574]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.4
**Bug 描述**
接口定义-用例导出为MS格式，然后再导入，模块中的内容是空的

**Bug 重现步骤**

1.  选择接口批量导出MS格式
2. 选择其他模块导入
3. 只导入了目录，接口为空

**Comment by zyyfit** [comment]
您好，在同一个项目下导入的话，重复的接口不会导入到新模块中的，
