### ISSUE TITLE
新建接口，选择状态是未开始，保存完成之后，查看接口列表中状态是进行中[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#4575]
您所使用的 MeterSphere 版本是？
v1.10.4
**Bug 描述**
新建接口，选择状态是未开始，保存完成之后，查看接口列表中状态是进行中

**Bug 重现步骤**

1.  新建接口，选择状态是未开始
2. 保存完成之后，查看接口列表中状态是进行中

**Comment by zyyfit** [comment]
您好，目前的逻辑是这样的，新建完接口后回变成进行中，除非新建完后再把状态修改回去
