### ISSUE TITLE
[BUG]用项目本身swagger url导入接口失败

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4577]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**

简要描述您碰到的问题
用项目本身swagger url导入接口失败
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/84962582/125150624-ceaf0f80-e173-11eb-96fc-06cca90d770f.png)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
未复现该问题
