### ISSUE TITLE
[BUG]接口定义，在模块树中，删除某个整个的模块，删除内容在回收站里中没有，只有在右侧区域中的删除，才会出现在回收站中

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4578]
**MeterSphere 版本**!>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**

简要描述您碰到的问题
接口定义，在模块树中，删除某个整个的模块，删除内容在回收站里中没有，只有在右侧区域中的删除，才会出现在回收站中
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/125154334-248fb180-e18c-11eb-960e-d4e4ea64a607.png)
![image](https://user-images.githubusercontent.com/84962582/125154347-31140a00-e18c-11eb-88d7-ad8dd60fcfb7.png)
![Snipaste_2021-07-10_14-39-21](https://user-images.githubusercontent.com/84962582/125154650-93213f00-e18d-11eb-8b2b-4ecadda170b7.jpg)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您多点几下回收站试试，这个地方刷新不太及时
