### ISSUE TITLE
[FEATURE]接口测试希望增加全局添加同一个断言的操作

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#458]
**请描述您的需求或者改进建议.**

swagger导入批量接口，一个业务的接口的业务code标识都是一样的，再加断言是需要一个个接口加，非常不方便

**请描述你建议的实现方案**
建议添加一个全局断言加入功能，弹出界面输入断言配置，点击确定后这个界面上的所有接口都加上该断言

**Comment by xulinde** [comment]
您好，我们目前是支持场景级别断言的，您可以升级到最新版本体验下
