### ISSUE TITLE
[BUG]测试评审任务消息通知，谁删除评审就给谁发邮件，与消息设置不符

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4580]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.4-lts
**Bug 描述**

简要描述您碰到的问题
测试评审任务消息通知，谁删除评审就给谁发邮件，与消息设置不符
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/125157727-1dbe6a00-e19f-11eb-9c19-824e3a2a5060.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.11.0版本已修复
