### ISSUE TITLE
[BUG] 用例备注里有json字符串，测试计划，标记用例测试结果时报错“ SQL error happened, please check logs.”

### ISSUE THREAD

**Issue by SmallLeafW** [metersphere/metersphere#4585]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.10.5-678b9a6a

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用例备注里有代码块，Json格式字符串
2. 测试计划，标记用例测试结果

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
10.6已修复
