### ISSUE TITLE
[BUG]批量运行场景任务时，平台报错

### ISSUE THREAD

**Issue by CodeMagicL** [metersphere/metersphere#4596]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  批量运行场景任务（包含200条场景）
2. 查看能否正常运行
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/42262211/125249490-dfa08200-e327-11eb-8496-d7969141951c.png)

如果有截图，请附上截图.

**Comment by CodeMagicL** [comment]
修改建议：将数据库 表api_scenario_report 字段scenario_id 修改为text

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
10.6已修复
