### ISSUE TITLE
[FEATURE]能否增加操作日志

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#46]
**请描述您的需求或者改进建议.**
能否增加操作日志，系统管理员权限可查看，自己新建的测试用例被人删除了，没有操作日志可查看

**请描述你建议的实现方案**
方案1：增加操作日志
方案2：增加权限管理，自己只能删除自己的测试用例，管理员可以修改删除别人的测试用例，但必须有操作日志记录

**Comment by xchnshi** [comment]
1. 审计功能缺失，如删除类操作，需要大权限的人才可以，现在测试人员就可以删除，找不到审计记录
2. 现在删除不是软删除，测试人员误删除，数据找回靠binlog比较麻烦
3. 如方案2，可以进行菜单和角色的配置管理（其他的issue也有提到）

**Comment by maninhill** [comment]
感谢反馈，我们先对操作日志做排期。

**Comment by xulinde** [comment]
1.10版本已实现
