### ISSUE TITLE
[BUG]  服务集成禅道，提示“zentao login fail”

### ISSUE THREAD

**Issue by Betrayme** [metersphere/metersphere#4604]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.10.5

**Bug 描述**

简要描述您碰到的问题
禅道服务集成，提示“zentao login fail”

正确情况下应该是什么样的？
MS接口请求禅道登录接口不符合接口定义，请将请求参数放到path中而不是请求体
禅道官方给的api调用步骤
PATH_INFO方式
1、访问 http://x.com/api-getsessionid.json获取禅道session信息
2、使用上一步获取的session作为url参数访问 http://x.com/user-login.json?account=account&password=123456&zentaosid=6v9bl9hp3o5chvdd46u5fg36g4

**Comment by zyyfit** [comment]
您好，这边没有复现您的问题，能否详细描述一下或者截图看一下？

**Comment by Betrayme** [comment]
![image](https://user-images.githubusercontent.com/41469910/125553081-2ddd358d-d801-42d9-9fba-612152e5e17e.png)
![image](https://user-images.githubusercontent.com/41469910/125553225-aa7337ba-43f6-480c-a911-028698cf97f0.png)
![image](https://user-images.githubusercontent.com/41469910/125553272-8a8ca027-2ba9-4058-9c74-434c2f4864fb.png)

**Comment by xulinde** [comment]
现在还有此问题吗

**Comment by Betrayme** [comment]
> 现在还有此问题吗

升级到版本：v1.12.0-b4
选择禅道集成PATH_INFO与禅道配置对应
通过抓包，仍然没有按照官方的调用方式进行
![image](https://user-images.githubusercontent.com/41469910/131646331-e13cc44a-e9eb-4a29-a885-3facaa5b2d69.png)
![image](https://user-images.githubusercontent.com/41469910/131646381-d1b4f320-bc55-45a9-8f98-c5be91ad239e.png)
![image](https://user-images.githubusercontent.com/41469910/131646666-8ff7a975-61aa-4ea3-9447-bcb8dcff0176.png)

**Comment by zyyfit** [comment]
您好，我们这边还是没有复现这个问题，您可以升级到最新版再试试，还是不行的话可以在我们的用户交流群里反馈一下，我们可以及时的帮您排查一下问题

![图片](https://user-images.githubusercontent.com/73461316/144178346-18afa599-3dea-4bb5-88c3-363004ac088d.png)

**Comment by Betrayme** [comment]
升级到最新版本：v1.15.1-7769e696
验证通过
感谢！

**Comment by andi-souwer** [comment]
1.20.0和1.20.1均出现该报错 “zentao login fail, user null”。

![image](https://user-images.githubusercontent.com/59073235/167250814-8d2fb0a7-b920-4a7d-99a3-1d7679034684.png)


![image](https://user-images.githubusercontent.com/59073235/167250838-999c9877-0484-4b09-b17a-0658b0d18c22.png)
