### ISSUE TITLE
[FEATURE] 测试计划在创建和维护的时候，必填字段【测试阶段】改为选填，或者提供测试计划模版，这样字段自定义就方便了

### ISSUE THREAD

**Issue by davidwangxiaolei** [metersphere/metersphere#4605]
测试计划的字段类型【测试阶段】：冒烟，回归，系统。
实际上是限制死了计划的功能，强制将规划单元硬性的塞到研发过程中的某个阶段。
这样做实际上给研发过程造成了麻烦，一个版本迭代需要新建三个测试计划？

 我觉得这个选填即可。因为不同的用例既然可以复用，那么计划也无需强制规定生命周期。

或者说可以提供测试计划模版，这样对测试计划来说，试用范围更大

**Comment by wangzhen-fit2cloud** [comment]
@luty2018
