### ISSUE TITLE
[BUG]测试报告列表中，建议这里修改成中文，不要显示为英文。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4611]
![Uploading 更改类型文本类型后，内容为空。.png…]()
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.12.0版测试报告已重构
