### ISSUE TITLE
[BUG]性能测试的定时任务消息接收人被覆盖

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4621]
**MeterSphere 版本**
   
  V1.10.5

**Bug 描述**

简要描述您碰到的问题

性能测试定时任务的通知接收人，只要有一个测试任务改了，其他测试任务的消息接收人也会被改掉

**截图**

如果有截图，请附上截图.
<img width="1440" alt="WechatIMG2130" src="https://user-images.githubusercontent.com/32027713/125397593-babc1580-e3e0-11eb-9b92-4c13752b0d46.png">

**Comment by xulinde** [comment]
感谢反馈，下个版本修复
