### ISSUE TITLE
[BUG]性能测试jmx文件内容解析缺失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4622]
**MeterSphere 版本**

 V1.10.5

**Bug 描述**

性能测试上传jmx文件之后，文件内的有些需要上传的文件被禁止了，但是我们解析的时候没有过滤出被禁用的文件，导致在做性能测试的时候，出现错误，一直处于starting状态

**截图**

如果有截图，请附上截图.
<img width="974" alt="WechatIMG146" src="https://user-images.githubusercontent.com/32027713/125398705-3bc7dc80-e3e2-11eb-8d13-f2ac42eb4188.png">
![WechatIMG194](https://user-images.githubusercontent.com/32027713/125398787-539f6080-e3e2-11eb-9861-ac705879c9b0.png)
jmx文件：
[获取日工时表盘数据.jmx.zip](https://github.com/metersphere/metersphere/files/6806242/jmx.zip)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.11.0已修复
