### ISSUE TITLE
[FEATURE]首行的上，建议增加快速切换项目和创建项目下拉框，不然需要很多步才能切换项目。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4623]
**请描述您的需求或者改进建议.**
首行的上，建议增加快速切换项目和创建项目下拉框，不然需要很多步才能切换项目。
![快速切换项目](https://user-images.githubusercontent.com/14307013/125399419-27d0aa80-e3e3-11eb-86c2-ca8173797783.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前是有入口的
![image](https://user-images.githubusercontent.com/64065190/125402985-944da880-e3e7-11eb-97b3-ce4fad728f61.png)

**Comment by billguo** [comment]
见下图，如果当前我在系统设置，我很难快速的切换项目和回到首页。
![回到首页](https://user-images.githubusercontent.com/14307013/125405802-b268d800-e3ea-11eb-91b3-b9753c9cd120.png)
