### ISSUE TITLE
[BUG]测试跟踪>>测试用例：脑图模式下，编辑一个测试用例，点击保存。此没有变更历史

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#4631]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.5

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪>>测试用例：脑图模式下，编辑测试用例A,修改步骤或期望结果，点击保存。
2.  测试跟踪>>测试用例：列表模式，打开测试用例A，进入用例详情页。点击“变更历史”
3. 变更历史里，没有刚才脑图模式下的变更信息
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，目前脑图编辑暂时不支持在用例的操作记录里记录操作历史，在系统日志里会记录用例名称，也暂时不支持详细信息

**Comment by zyyfit** [comment]
最新版已增加脑图编辑日志
