### ISSUE TITLE
[FEATURE]平台的页面建议都设计一下吧。感觉没有啥布局，谢谢。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4632]
**请描述您的需求或者改进建议.**
平台的页面建议都设计一下吧。感觉没有啥布局，谢谢。

**请描述你建议的实现方案**
![Uploading 页面的部署建议设计一下吧.png…]()

**Comment by xulinde** [comment]
是metersphere页面吗，您贴的这个图打不开

**Comment by billguo** [comment]
![页面的部署建议设计一下吧](https://user-images.githubusercontent.com/14307013/125723941-b0580c10-c393-4345-9a68-9a8bab86907d.png)

**Comment by billguo** [comment]
能不能设置成自适应，包括字体，图标这些。
