### ISSUE TITLE
[BUG]性能测试用例执行时一直显示starting,手动停止测试报告中无法看到开始时间及正常的结果信息

### ISSUE THREAD

**Issue by mexth** [metersphere/metersphere#4643]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10.5
**Bug 描述**
jmx及csv文件加载后,性能测试执行状态一直是starting,如果手动结束,
1.测试报告里面就是无内容的,并且看不到测试开始时间
2.通过日志查看jmeter容器日志发现jmeter是正常触发任务并执行了的.
简要描述您碰到的问题

**Bug 重现步骤**

1.  jmeter5.4.1创建测试计划,伴随着额外的测试资源csv文件
2. metersphere中加载jmx文件和csv文件并创建压测用例
3. 保存并执行用例,尝试查看测试报告

**期待的正确结果**
在设定的测试条件满足后正常停止测试并可以查看测试结果

**截图**

如果有截图，请附上截图.
![jmeter docker日志](https://user-images.githubusercontent.com/18657844/125426931-10bcccd6-0777-4e9d-8887-32280460676f.png)
![测试结果为空](https://user-images.githubusercontent.com/18657844/125427683-4cdd70f9-18c4-4331-a01f-1b80b0e669c6.png)

**Comment by mexth** [comment]
[info.log](https://github.com/metersphere/metersphere/files/6813356/info.log)
node-controller的info日志,warn和debug,error级的日志中没有有效信息,只有info.log里面有相关信息

**Comment by mexth** [comment]
配置问题,调整install.conf并且重新reload后解决

**Comment by huhui** [comment]
请问这是如何解决的？现在遇到同样的问题
