### ISSUE TITLE
[FEATURE]性能监控agent支持安装至云环境中

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#4644]
**请描述您的需求或者改进建议.**
现在很多测试环境都是云上的，目前机器资源监控agent仅支持安装至虚拟机中，无法有效部署到云环境中监控namespace、node、pod等云环境的使用率。

**请描述你建议的实现方案**
建议增加云上环境机器资源监控，并展示在性能测试报告中。

**Comment by GITMrzk** [comment]
1

**Comment by luty2018** [comment]
非常抱歉长时间未回复。
您这边指的云环境是指K8S集群吧，目前我们的prometheus方案支持监控这些信息的。
可能页面交互有些误导，页面交互会在v3.0进行优化。
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/36292514/221748691-a926adac-9f72-44ea-a0e9-460e059af071.png">

**Comment by zhangzhaox** [comment]
PromQL最好是能支持导入一些常规的模板，测试同学大多数都不会这个
