### ISSUE TITLE
[BUG]jira平台定义字段类型为 array 时创建issue失败

### ISSUE THREAD

**Issue by ZheErMao** [metersphere/metersphere#4647]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.10.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 使用jira 平台接收缺陷
2. 设置 jira 模板， 自定义字段，类型为：多选下拉列表 ， 
3. 在缺陷中新建缺陷，前端http 请求：http://xxx/issues/add，body ： {"title":"标题","description":"多选下拉列表","creator":"chenzl","customFields":"[{\"id\":\"71589d17-bff7-4475-889b-f8e5f4595998\",\"name\":\"客户名称\",\"value\":[\"兴业 \",\"中金 \"],\"type\":\"multipleSelect\",\"customData\":\"customfield_10277\"},{\"id\":\"7563bc26-53de-4d20-a3bc-808cc898902d\",\"name\":\"状态\",\"value\":\"new\",\"type\":\"select\",\"customData\":null},{\"id\":\"874cf40d-b681-407e-b512-ba496c7d986d\",\"name\":\"严重程度\",\"value\":\"P1\",\"type\":\"select\",\"customData\":null},{\"id\":\"ede5db37-7361-4268-ad7e-c559ccbd5a75\",\"name\":\"处理人\",\"value\":\"joan\",\"type\":\"member\",\"customData\":null}]","projectId":"032dc05a-dfc7-4a66-bfd5-2acf55b9e943","organizationId":"4d562674-3942-4834-a4c4-0c98e485f479","testCaseIds":[],"status":"new"}
4.接口返回异常：
{"success":false,"message":"400 : [{\"errorMessages\":[],\"errors\":{\"customfield_10277\":\"data was not an array\"}}]","data":null}
5、服务器日志：
2021-07-13 17:20:07,917 [qtp328241052-1001] INFO  i.m.t.i.client.JiraAbstractClient ? - Method[addIssue][addIssue: {"fields":{"summary":"test","issuetype":{"name":"缺陷"},"project":{"key":"OPZ"},"description":"中金","customfield_10277":{"id":"[\"兴业\",\"中金\"]"}}}]
2021-07-13 17:20:08,223 [qtp328241052-1001] ERROR i.m.t.i.client.JiraAbstractClient ? - Method[addIssue][400 : [{"errorMessages":[],"errors":{"customfield_10277":"data was not an array"}}]]
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 : [{"errorMessages":[],"errors":{"customfield_10277":"data was not an array"}}]

**期待的正确结果**

正确情况下应该是什么样的？

1、支持 自定义字段的字段类型为 array 的数据传参

**截图**

如果有截图，请附上截图.
设置 自定义字段
![image](https://user-images.githubusercontent.com/6259419/125428002-bf79a5ce-3a5c-4414-9a12-06c1adcd599f.png)
jira模板应用

请求接口
![image](https://user-images.githubusercontent.com/6259419/125428171-be902c63-6648-4339-ae5e-9a38dd136f09.png)

**Comment by xulinde** [comment]
v1.12.2已修复
