### ISSUE TITLE
[FEATURE]多环境配置的建议

### ISSUE THREAD

**Issue by feilang864** [metersphere/metersphere#465]
**请描述您的需求或者改进建议.**
目前的多环境配置，是在每一个接口上配置的，实际场景都是dev，stg，uat，pro的版本的接口都是一致的

**请描述你建议的实现方案**
建议是否可以把多环境的配置外移，可以配置接口测试的测试计划，选择不同的环境后创建相应的计划，这样不同的环境可以复制之前的某一次计划，更改多环境变量就可以

**Comment by zyyfit** [comment]
将在1.8版本中优化这个问题

**Comment by xulinde** [comment]
1.10版本已实现该功能
