### ISSUE TITLE
[BUG] 通过浏览器插件录制的json文件导入平台，部分接口参数类型错误

### ISSUE THREAD

**Issue by dengying721** [metersphere/metersphere#4656]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.10.5

**Bug 描述**

通过浏览器插件录制接口，保存为json文件后，导入到metersphere平台，部分接口参数原本是 `application/x-www-form-urlencoded` 格式，导入后变成了`raw` 格式，参数类型错误，导致接口无法正常调试。

**Bug 重现步骤**

1.  通过浏览器插件进行系统或项目的接口录制。
2.  将录制结果导出为json文件
3.  在metersphere平台将json里的接口导入。
4.  检查导入的接口，发现部分接口导入后参数类型从 `application/x-www-form-urlencoded`  变成了 `raw` 格式。

**期待的正确结果**
接口参数类型不变。

**截图**

录制的接口数据：
![image](https://user-images.githubusercontent.com/17683756/129652702-2e27945d-1a93-487d-8ce0-069d3373cc6b.png)

导入后的接口：
![image](https://user-images.githubusercontent.com/17683756/129652691-32b8d09a-26bc-41ee-9a09-35c3cdee1187.png)

**Comment by xulinde** [comment]
v1.12.2已修复
