### ISSUE TITLE
[BUG]接口自动化设置CSV参数时，若CSV字段内容带有逗号则数据读取错误

### ISSUE THREAD

**Issue by longxiong1991** [metersphere/metersphere#4657]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.10

**Bug 描述**
接口自动化设置CSV参数时，若CSV字段内容带有逗号则数据读取错误，把本该一个字段的内容以逗号分割成了两个字段读取

**Bug 重现步骤**
1.准备CSV数据，如图，addressCodeList中含有逗号的数据
![image](https://user-images.githubusercontent.com/39517745/125552723-96af27d1-fac6-4bbb-aab4-85f0b6c38f7f.png)
2.上传该CSV文件
![image](https://user-images.githubusercontent.com/39517745/125552641-7668e3bc-8d10-4870-bd1c-2c29d715902c.png)
3. 读取addressCodeList变量时，只读取了逗号左边的内容，

**期待的正确结果**
读取addressCodeList变量时，读取整个addressCodeList下的内容

**Comment by zyyfit** [comment]
您好，这是csv文件定义的，设置逗号分隔遇到逗号就会算这一个变量完成了，您可以设置其他标点符号分割，同时需要修改一下csv文件

**Comment by zyyfit** [comment]
我们后面会优化一下，添加一个csv的参数
![图片](https://user-images.githubusercontent.com/73461316/125718203-b107127c-53ff-4c1d-aa5a-c554d91cd51f.png)

**Comment by xulinde** [comment]
v1.11.0已修复
