### ISSUE TITLE
[BUG]接口自动化定时任务完成后 没有发送邮件通知

### ISSUE THREAD

**Issue by bahaodegun** [metersphere/metersphere#4659]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.4-221f275f
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  设置邮箱 收到测试邮件
![image](https://user-images.githubusercontent.com/44808314/125553994-0181f83b-64ef-4738-b0e1-6b04b984a528.png)
2. 创建接口自动化定时任务 
![image](https://user-images.githubusercontent.com/44808314/125554155-d9a79ed5-0c55-4f17-83f9-77a4f69863b8.png)

3. 任务按设定时间开启
![image](https://user-images.githubusercontent.com/44808314/125554133-09e7c33f-8f4c-493f-9cdb-06771af6487f.png)

4. 但不管成功或失败 都没有邮件通知
![image](https://user-images.githubusercontent.com/44808314/125554191-18feae0d-2bc2-481b-8929-db52894091d6.png)

**期待的正确结果**
收到邮件

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我在1.10.5版本没有复现，您升级到1.10.5试一下？

**Comment by bahaodegun** [comment]
升级后收到报告完成邮件了
