### ISSUE TITLE
[BUG] 通过列表形式添加用例时，“标签”不是必填项，但通过思维导图创建时，提示没有添加标签无法保存。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#4668]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.5
**Bug 描述**

简要描述您碰到的问题
<img width="764" alt="2" src="https://user-images.githubusercontent.com/71361375/125575728-e4b21afb-d0d6-45c0-b17c-e71feecdcdbd.png">
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
思维导图的标签和用例列表的标签不是一个标签，思维导图的标签是标记当前层是用例还是步骤的，用例不打标签目前思维导图无法判断是否为用例标题等信息
![图片](https://user-images.githubusercontent.com/73461316/125765629-b20b449a-73e8-47d0-946a-75fe00f1382f.png)
