### ISSUE TITLE
[BUG]测试跟踪，首页：用例评审率计算有误。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#4673]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.5
**Bug 描述**

简要描述您碰到的问题
测试跟踪，首页：用例评审率计算有误。公式显示的是：评审通过的用例数/用例总数。  
但总用例数3，未通过1，通过2。  评审率显示的是100%。
<img width="572" alt="1" src="https://user-images.githubusercontent.com/71361375/125586607-3afa67b6-7206-4db5-87e1-8fa7e9299656.png">

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
10.6版本已修复
