### ISSUE TITLE
[BUG]接口自动化下，导入的场景步骤无法删除

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4680]
**MeterSphere 版本**

  V1.10.5

**Bug 描述**
接口自动化下，导入的场景步骤无法删除
1. 编辑某一个接口自动化场景
2. 导入另外一个引用的场景
3. 将引用的场景下某一个接口移动到外部
4. 此时该外部的接口无法删除，且原来引用的场景被删除后，该移入至外部的接口，不会被同时删除也无法操作

**截图**

如果有截图，请附上截图.
<img width="1438" alt="WechatIMG147" src="https://user-images.githubusercontent.com/32027713/125591612-d2333af7-9aa4-4c13-8c5e-796567b69271.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.11.0已修复
