### ISSUE TITLE
[BUG]接口自动化编辑场景时，引用其他场景，其他场景的场景变量不会被带过来

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4683]
**MeterSphere 版本**
 V1.10.5

**Bug 描述**
接口自动化编辑场景时，引用其他场景，其他场景的场景变量不会被带过来

**截图**

如果有截图，请附上截图.
<img width="1439" alt="WechatIMG148" src="https://user-images.githubusercontent.com/32027713/125592386-47aa20bc-192a-47d9-b9c5-fab1bbab00a7.png">

**Comment by elviszy** [comment]
建议把引用场景的场景变量带过来, 并给与一定的标识, 标识为引用场景的场景变量,且不可以编辑状态

**Comment by zyyfit** [comment]
虽然没有显示出来，但是实际上是带过来了的，也可以继续使用
