### ISSUE TITLE
[FEATURE]接口和性能测试增加预热时间，测试周期，线程数，测试机

### ISSUE THREAD

**Issue by feilang864** [metersphere/metersphere#469]
**请描述您的需求或者改进建议.**
可指定线程数、预热时间、测试周期和测试机等，可以自动切分数据，分布式执行

**请描述你建议的实现方案**
维护压测机集群，保证压测机是可供测试的；测试期间产生的冷数据(用例数据、结果数据)持久化至MongoDB，热数据(实时数据)持久化至InfluxDB并定期清理

**Comment by zhangzhaox** [comment]
分布式集群压测 ，对于要求唯一性取值的参数化文件，目前是会自动分割的吗？根据分布式设置并发用户数的权重分割参数化文件？
目前也未见 手动上传分割后的参数化文件
