### ISSUE TITLE
[BUG]jmeter脚本中有中文上传后显示乱码

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#47]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.1-b352
**Bug 描述**
简要描述您碰到的问题
1.jmeter脚本中有中文上传后显示乱码

**Bug 重现步骤**
1.  在线程组中添加操作步骤，并修改名称为中文
2. 上传脚本 

**期待的正确结果**
正确情况下应该是什么样的？
显示正确的中文

**截图**
如果有截图，请附上截图.

![bug1](https://user-images.githubusercontent.com/29306248/85941606-7a653300-b956-11ea-9b0c-3e69f1adfefa.png)
![bug11](https://user-images.githubusercontent.com/29306248/85941621-805b1400-b956-11ea-9aba-8602d83f3c29.png)

**Comment by wangzhen-fit2cloud** [comment]
该问题已在 v1.0.2 中修复，可以升级一下
