### ISSUE TITLE
[BUG]性能测试执行bug

### ISSUE THREAD

**Issue by sky1984** [metersphere/metersphere#4700]
1.10.5

测试步骤
1、在jmeter正常执行的性能脚本（没有依赖外部数据问题），只是增加了一些随机函数生成变量引用
如下：
//生成18随机数字串
vars.put("id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("customer_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成11随机字符串
vars.put("customer_warehouse_number","${__RandomString(5,ABCDEFGHIJKLMNOPQRSTUVWXYZ,)}${__Random(100000,999999,)}");
//生成11随机数字串
vars.put("customer_account_id","${__Random(10000000000,99999999999,)}");
//生成9随机数字串
vars.put("product_sku_code","${__Random(100000000,999999999,)}");
//生成18随机数字串
vars.put("product_category_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("buyer_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("seller_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("buyer_wh_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("buyer_shop_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("seller_shop_id","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("quyuid","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成15随机数字串
vars.put("sales_hierarchy_code1","${__Random(10,99,)}${__time(,)}");
//生成18随机数字串
vars.put("sales_hierarchy_code2","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("sales_hierarchy_code3","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
//生成18随机数字串
vars.put("sales_hierarchy_code4","${__Random(100,999,)}${__time(,)}${__Random(10,99,)}");
2、把jmete脚本放到平台执行，执行报错，提示：无法解析JMX文件，请确认是否缺少执行需要的 jar 等文件
3、在平台创建接口，内容一致，把上面的内容放到前置脚本里
4、创建测试场景A,接口复制进来，场景可以正常执行，返回成功
4、在平台创建性能测试，选择场景A，执行性能测试

测试结果：
1、通过jmeter导入的脚本，执行失败
2、通过平台转脚本的，执行成

备注：接口一致，内容一致

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by sky1984** [comment]
回复楼上，我看了和前置脚本没有任何问题
我用原生JM脚本，就一个简单查询 也是报错

**Comment by zyyfit** [comment]
> 回复楼上，我看了和前置脚本没有任何问题 我用原生JM脚本，就一个简单查询 也是报错

您好，这个问题是因为 上传的jmx里有个插件虽然禁用掉了，但是我们的镜像里没有这个插件
