### ISSUE TITLE
[BUG]项目关联的是自定义用例模板，导入用例后，选择用例进行导出，导出的用例中字段还是老的模板

### ISSUE THREAD

**Issue by TTtesting** [metersphere/metersphere#4701]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？V1.10.5

**Bug 描述**

项目关联的是自定义用例模板，导入用例后，选择用例进行导出，导出的用例中字段还是老的模板【重要，希望能早点解决】

**Bug 重现步骤**

项目关联的是自定义用例模板，导入用例后，选择用例进行导出，导出的用例中字段还是老的模板

**期待的正确结果**

期望导出用例是按照自定义用例模板导出用例

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
相关bug
https://github.com/metersphere/metersphere/issues/4211
https://github.com/metersphere/metersphere/issues/4252

后续版本修复

**Comment by zyyfit** [comment]
最新版已修复
