### ISSUE TITLE
[BUG]针对mock，建议增加功能，包括模板配置，超时返回，错误返回，正确返回，多返回，定时返回，统一放到系统设置-项目管理中吧。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4713]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.5

**Bug 描述**
针对mock，建议增加功能，包括模板配置，超时返回，错误返回，正确返回，多返回，定时返回，统一放到系统设置-项目管理中吧。

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，后面版本会逐一优化
