### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#4717]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.3
**Bug 描述**

在后置脚本（BeanShell）中对数据进行处理，结果报错了

**Bug 重现步骤**

1.  
从上一个接口中获取到值，设置为全局变量，在后置脚本（BeanShell）中对数据进行处理，结果报错了
```
print(${availableAmount});
long less(long a,long b ) {
return a - b;
}
long amount=less(${availableAmount},100);
print(amount);
vars.put("amount", amount.toString());
```
![image](https://user-images.githubusercontent.com/42166114/125738576-e6bbfca7-8146-4450-aae2-9130793fe71e.png)
![image](https://user-images.githubusercontent.com/42166114/125738638-f70b1ce8-6615-4f91-8fe5-d84ec278b95e.png)
**期待的正确结果**

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
用最新版本还有此问题吗
