### ISSUE TITLE
[FEATURE]url地址栏编辑主键参数携带

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#4718]
**需求.**
在编辑相关的接口测试时，希望能够将编辑主键携带在url地址栏，编辑文档记录或者内部沟通时使用链接传递；
在旧版本中是支持的，到新版本以后，url在内部沟通传递无法携带。
![image](https://user-images.githubusercontent.com/22386206/127444884-a723b083-f913-4141-8b68-a6f79d73cd76.png)

**建议的实现方案**
希望在url参数增加主键，实现url链接参数传递

**Comment by zh417233956** [comment]
求关注~

**Comment by luty2018** [comment]
> 求关注~

可以加

**Comment by zh417233956** [comment]
@luty2018 这个有迭代计划吗

**Comment by zh417233956** [comment]
![image](https://user-images.githubusercontent.com/22386206/127444811-bd2ab103-c3e9-4ec7-aa63-9ba4c82f51ff.png)

**Comment by zh417233956** [comment]
#1465

**Comment by zh417233956** [comment]
> > 求关注~
> 
> 可以加

跟进下，这个有进度吗

**Comment by luty2018** [comment]
v2.7已经实现了测试跟踪打开功能用例新窗口的方式， 后续接口也会改造成这样。
不好意思，现在才回复，预计今年内会进行交互改造实现这个效果。
