### ISSUE TITLE
[FEATURE]搜索用例，有一些目录下没有满足条件的用例，建议连目录一起隐藏

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#4719]
**请描述您的需求或者改进建议.**
搜索用例，有一些目录下没有满足条件的用例，建议连目录一起隐藏。
现状是有一些目录没有满足条件的用例，但没有特殊标识，所以看用例时，还是需要每个目录都点击进去看。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后续可以优化下这里
