### ISSUE TITLE
在设置-组织-服务集成，希望添加对禅道的集成。

### ISSUE THREAD

**Issue by liuneng613** [metersphere/metersphere#472]
**请描述您的需求或者改进建议.**
在设置-组织-服务集成，希望添加对禅道的集成。
![image](https://user-images.githubusercontent.com/32347059/94218812-dfa9cf80-ff17-11ea-8a56-cd759a5e7872.png)

**请描述你建议的实现方案**
神道有对应的api。

**Comment by skywolf123** [comment]
确实，太多国内公司用的禅道，至少用了禅道的缺陷管理部分，希望能集成
