### ISSUE TITLE
[FEATURE]导入Excel用例，用例模块在目录里显示的顺序是倒序，没有按excel的顺序

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#4720]
**请描述您的需求或者改进建议.**
导入Excel用例，用例模块在目录里显示的顺序是倒序，没有按excel的顺序
在本地写excel用例时，会按模块之间的关联来整理这个顺序，倒入到平台后，在目录树里显示的是倒序

**请描述你建议的实现方案**

**Comment by jhong123** [comment]
有相同需求

**Comment by xulinde** [comment]
后续可以优化下

**Comment by xulinde** [comment]
v1.13已优化
