### ISSUE TITLE
[FEATURE]期望有复制测试计划功能，不要带执行状态

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#4721]
**请描述您的需求或者改进建议.**
背景：我们使用平台的测试计划，主要是每次发版时的基础用例回归计划。每个版本基本都一样的用例范围。
现状：没有复制功能，导致我2周一迭代的发版回归，每次都要重新建计划，很麻烦。
期望：增加复制测试计划功能，自动去除执行状态，我每2周发版时，复制测试计划就行。
**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们会考虑您的建议，尽快排期

**Comment by xulinde** [comment]
1.12已支持该功能
