### ISSUE TITLE
[BUG]执行测试计划中的接口测试用例，提示重新选择环境，然后就执行状态栏就一直转圈

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4727]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.5-lts
**Bug 描述**
执行测试计划中的接口测试用例，提示重新选择环境，但又没有重选环境的入口，然后执行状态栏就一直转圈，其实在接口测试-接口用例里，环境已经选好
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/125756176-cb1bc013-5604-4083-ab60-92f5f71178c9.png)
![image](https://user-images.githubusercontent.com/84962582/125756517-c88ba596-6c2b-498b-a232-6dcc36761986.png)

**Comment by zyyfit** [comment]
您好，是引用前在接口测试模块中选好的环境吗？引用的时候有没有选择环境呢？这里其实有更新环境的入口的，只是比较隐蔽
![2561626832589_ pic](https://user-images.githubusercontent.com/73461316/126423385-edc6cbdd-49c3-4746-b0a3-d3686ce422da.jpg)
![2551626832557_ pic_hd](https://user-images.githubusercontent.com/73461316/126423396-032a3ee1-c71c-4cf8-8d57-e67f7bfbad04.jpg)
