### ISSUE TITLE
[BUG]测试跟踪-缺陷管理无法从jira同步缺陷状态

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4728]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.5-lts
**Bug 描述**
包括无法同步在jira上建的缺陷、ms上同步到jira上的缺陷，在jira上状态改变后，ms无法同步
简要描述您碰到的问题
测试跟踪-缺陷管理无法从jira同步缺陷状态，但是可以向jira同步缺陷
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/125757088-4e442f18-2eba-4e08-ae81-8136c09ea5a3.png)
![image](https://user-images.githubusercontent.com/84962582/125757130-9a22a9c7-27bd-402a-a4d0-99ebc0b53972.png)

**Comment by xulinde** [comment]
使用最新版本未复现该问题，建议您升级到最新版本在试下
