### ISSUE TITLE
[FEATURE] 接口测试中 响应的内容能够支持记住上一次的格式选择

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#473]
**请描述您的需求或者改进建议.**
每次看到响应内容是一条数据就想提优化，希望响应的内容能够支持记住上一次的格式选择，方便使用💗
![image](https://user-images.githubusercontent.com/44960709/94221081-facb0e00-ff1c-11ea-8f24-aaeae46ec3ed.png)

**请描述你建议的实现方案**
接口测试中 响应的内容能够支持记住上一次的格式选择，像请求内容一样
![image](https://user-images.githubusercontent.com/44960709/94221003-d7a05e80-ff1c-11ea-919e-39dd238fa379.png)

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 每次看到响应内容是一条数据就想提优化，希望响应的内容能够支持记住上一次的格式选择，方便使用💗
> ![image](https://user-images.githubusercontent.com/44960709/94221081-facb0e00-ff1c-11ea-8f24-aaeae46ec3ed.png)
> 
> **请描述你建议的实现方案**
> 接口测试中 响应的内容能够支持记住上一次的格式选择，像请求内容一样
> ![image](https://user-images.githubusercontent.com/44960709/94221003-d7a05e80-ff1c-11ea-919e-39dd238fa379.png)

会按响应类型自动格式化，大概1.4版本，请关注
