### ISSUE TITLE
[BUG]1.10.5 1， 接口测试-接口自动化，2， 选择某个场景。3， 场景导入。 应该去掉 复制 和 编辑 按钮。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4732]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.5
![场景导入](https://user-images.githubusercontent.com/14307013/125762701-300be07e-a56f-4c3e-af04-ebf70752cb14.png)
![编辑和删除](https://user-images.githubusercontent.com/14307013/125762723-e1385a63-ef41-4a33-ba80-29ef6dfd8081.png)

**Bug 描述**
1， 接口测试-接口自动化，
2， 选择某个场景。
3， 场景导入。 应该去掉 复制 和 编辑 按钮。

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
1.10.6会去掉操作项

**Comment by billguo** [comment]
该问题已解决在1.10.6版本。
