### ISSUE TITLE
[FEATURE]接口测试希望添加对测试场景的执行顺序的设置支持

### ISSUE THREAD

**Issue by ratel-liu** [metersphere/metersphere#474]
**请描述您的需求或者改进建议.**
接口测试希望添加对测试场景的执行顺序的设置支持

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 接口测试希望添加对测试场景的执行顺序的设置支持
> 
> **请描述你建议的实现方案**

1.3版本已支持，请更新使用
