### ISSUE TITLE
[BUG]接口测试-接口定义导入数据失败。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4747]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.5

接口定义中，创建多个平级的模块。A模块，B模块，C模块。（三个模块平级）
1， 导入接口定义，选择A模块，导入测试用的POSTMAN的Json数据。--------------》成功。
2， 选择B模块，再次导入导入测试用的POSTMAN的Json数据。--------------》失败。只能带出目录名字。
3， 选择C模块，再次导入导入测试用的POSTMAN的Json数据。--------------》失败。只能带出目录名字。
见下图。无论覆盖或不覆盖都有问题。
![postman导入](https://user-images.githubusercontent.com/14307013/125877690-4b866307-6a22-447b-94db-5419d2d70c48.png)

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，使用最最新版本未复现该问题，建议您升级下在试下

**Comment by billguo** [comment]
复现了的。。。我直接给罗婷总说吧。

**Comment by billguo** [comment]
建星还在团建么，就是导入postman的json数据的问题。

**Comment by billguo** [comment]
我已升级到1.10.6的版本，还有这问题，麻烦再次确认下。

**Comment by billguo** [comment]
![json导入](https://user-images.githubusercontent.com/14307013/125924031-2ad1e015-39a9-499c-b15f-bf6f177eb1c0.png)
1.10.6的版本。

**Comment by zyyfit** [comment]
您好，如果是在同一个项目下，有重复的接口，是不会移动模块的，也就是会保留在原来的模块下，新模块只是会生成一个模块，但是不会把接口导入进去
