### ISSUE TITLE
[FEATURE]bug管理弱了点，没有状态变更的记录，也没有备注（主要用于开发如何修复的bug的描述）

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#4759]
**请描述您的需求或者改进建议.**
bug管理弱了点，没有状态变更的记录，也没有备注（主要用于开发如何修复的bug的描述）

**请描述你建议的实现方案**
bug管理弱了点，没有状态变更的记录，也没有备注（主要用于开发如何修复的bug的描述）

**Comment by xulinde** [comment]
后面版本会逐一优化，请持续关注～
