### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#476]
**请描述您的需求或者改进建议.**
响应结果的格式没有document   导出文件看到的都会是乱码
![image](https://user-images.githubusercontent.com/30932762/94225441-88136000-ff27-11ea-80f5-c0bb3869e7fd.png)

**请描述你建议的实现方案**
建议支持document的响应结果

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，没有复制该问题，请更新到最新版本～
