### ISSUE TITLE
[BUG]添加定时导入swagger url报错

### ISSUE THREAD

**Issue by jerry-li** [metersphere/metersphere#4762]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.6
**Bug 描述**

添加定时导入swagger url报错
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/3286238/125916895-56913ecf-9d86-4051-ac84-0ebbb88c514e.png)
![image](https://user-images.githubusercontent.com/3286238/125916935-24c04512-d3de-45a3-94e9-70300fad7bbc.png)
如果有截图，请附上截图.

**Comment by xulinde** [comment]
该问题已修复，您直接输入msctl pull && msctl reload，更新到最新镜像即可
