### ISSUE TITLE
[BUG] 接口 /user/list 不应当返回password字段

### ISSUE THREAD

**Issue by JFRabbit** [metersphere/metersphere#477]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？  v1.2.1-b623

**Bug 描述**

接口 /user/list 返回的response body中, 包含有password字段

**Bug 重现步骤**
1.  调用 MeterSphere 内部接口 /user/list
2. 接口返回了password字段

**期待的正确结果**
接口返回password字段是不安全, 虽然加密了, 但是产品本身是开源的, 有被破解的风险

**截图**
<img width="747" alt="截屏2020-09-25 下午1 24 07" src="https://user-images.githubusercontent.com/22906174/94229690-d843ef80-ff32-11ea-8a37-8b98e8e3f616.png">

**Comment by liuruibin** [comment]
已修改，🙏
