### ISSUE TITLE
[BUG]项目启用自定义用例ID，脑图中创建用例后，用例ID缺失

### ISSUE THREAD

**Issue by PolkFan** [metersphere/metersphere#4771]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本:   v1.10.4-221f275f

**Bug 描述**
项目启用自定义用例ID，脑图中创建用例后，用例ID缺失

**Bug 重现步骤**

1.  项目开启用例ID自定义
2. 使用脑图模式创建用例

**期待的正确结果**
项目启用自定义用例ID，脑图中创建可自动生成或可配置输入

**截图**
![image](https://user-images.githubusercontent.com/24569669/125930791-0ff1eb4d-0c67-4bba-b3e0-65950d68b725.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.11.0已修复
