### ISSUE TITLE
Tapd平台处理人下拉框优化建议

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#478]
**请描述您的需求或者改进建议.**
Tapd平台处理人下拉框优化建议：建议下拉框支持输入模糊匹配，平台处理人数据较多的情况下，只支持下拉选择的话，检索效率比较低！

**请描述你建议的实现方案**
支持输入，按输入关键字模糊匹配 过滤结果集

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该建议已采纳，请更新到最新版本～
