### ISSUE TITLE
[BUG]接口自动化-场景列表，出现三个默认模块

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#4781]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.6-53a8890e
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口自动化-场景列表，出现三个默认模块
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/42727151/126021885-cec75d40-b564-48db-b532-6f86315ff989.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是什么场景下出现的这个问题呢
