### ISSUE TITLE
[FEATURE]建议项目下面的默认模块可以修改，或者可以删除

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#4782]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/42727151/126021970-c081591d-bccd-41e8-8a75-6c161f81f13b.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
因为我们有些初始化的数据 会放默认模块里。类似tapd 这个未分类，也是不能改不能删的
![image](https://user-images.githubusercontent.com/64065190/126250806-5de8d3c3-d664-4ede-bb58-cef8d5d6970c.png)

**Comment by xulinde** [comment]
和#5203重复
