### ISSUE TITLE
[BUG]系统设置-环境配置，设置没保存上，再次查看还是空的（只会修改环境名称）

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#4783]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.6
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  HTTP设置，选择环境域名为https ，输入域名，请求头，进行保存
2. 再次查看环境配置
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/42727151/126022151-6c02f814-34cb-4c59-a756-8dedbd98686c.png)

![image](https://user-images.githubusercontent.com/42727151/126022151-6c02f814-34cb-4c59-a756-8dedbd98686c.png)

![image](https://user-images.githubusercontent.com/42727151/126022160-b883c4fe-8a50-4873-b8fb-a242cc6dac90.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
您是从哪个入口进入的环境配置呢
