### ISSUE TITLE
[BUG]接口定义-case，编辑，用例名称没有回显，并且修改名称后保存，每次都会新增一条用例，应该是更新用例

### ISSUE THREAD

**Issue by luman2013** [metersphere/metersphere#4784]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/42727151/126022313-26be8eb1-b5f7-4532-badb-2a96a757cf84.png)
![image](https://user-images.githubusercontent.com/42727151/126022344-d49e5f89-680b-455c-987b-99c8ae000811.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
该问题已修复，您直接输入msctl pull && msctl reload，更新到最新镜像即可
