### ISSUE TITLE
[BUG]按文档离线安装的但是 ms-server启动不了

### ISSUE THREAD

**Issue by uniplore-chenz** [metersphere/metersphere#4788]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.6

**Bug 描述**
ms-server exit状态
![image](https://user-images.githubusercontent.com/85154234/126030367-8b4adcc1-070e-4fd1-a74f-ab80aa05e66d.png)
docker日志报错如下：
![image](https://user-images.githubusercontent.com/85154234/126030427-492fff82-54f0-4fe5-8d6e-61e62a3ab1c6.png)

报错的目录是这样的，没有配置文件，是一个空的文件夹
![image](https://user-images.githubusercontent.com/85154234/126031163-c7043e2d-b016-49df-a8b4-fbb3f91442c8.png)

**Comment by xulinde** [comment]
最新版本离线包还有此问题吗

**Comment by snowyfang** [comment]
> 最新版本离线包还有此问题吗
仍然有此问题，请问该如何解决呢？

**Comment by snowyfang** [comment]
> > 最新版本离线包还有此问题吗
> > 仍然有此问题，请问该如何解决呢？

已解决，copy data和prometheus文件到安装目录下即可
