### ISSUE TITLE
[BUG]json-schema勾选必填后切回json报错

### ISSUE THREAD

**Issue by wanglp9235** [metersphere/metersphere#4790]
**MeterSphere 版本**
`v1.10.5-b1`

**Bug 描述**
请求体选择 `json`----`JSON-SCHEMA`,模板字段`是否必修`打勾,然后点击预览或者或 `JSON-SCHEMA 滑条`移动到 `左边`,返回错误 `Internal Server Error`

**Bug 重现步骤**

1.  选择项目
2. 点击接口测试
3. 点击接口定义
4. 选择创建接口
5. 到请求参数区域，点击请求体
6. 选择 `Json`
7. JSON-SCHEMA滑块右移
8. 选中模板页
9. 是否必须 复选框  打勾
10.  点击预览  或者 JSON-SCHEMA 滑块左移

**期待的正确结果**
可以正常预览 模板所填的参数

**截图**
请求：
![image](https://user-images.githubusercontent.com/49949035/126058064-813d8678-1f7a-4aaf-9bb3-eae6418e3b40.png)
返回：
![image](https://user-images.githubusercontent.com/49949035/126058088-ff9d52af-14f8-42e0-a6bf-12179df57c16.png)

服务报错日志：
![image](https://user-images.githubusercontent.com/49949035/126058120-e8d1d91b-bd5b-47de-ad1b-58c4e3335c71.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v11.2已修复
