### ISSUE TITLE
[BUG]压测结果与jmeter结果不一致

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#48]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.1-b352

**Bug 描述**
简要描述您碰到的问题
压测结果与jmeter结果不一致

**Bug 重现步骤**
1.  上传jmeter脚本
2.  执行脚本
3. 查看结果
4. 

**期待的正确结果**
正确情况下应该是什么样的？
与jmeter结果一致

**截图**
如果有截图，请附上截图.

![bug2](https://user-images.githubusercontent.com/29306248/85941674-c7490980-b956-11ea-80e0-92e8728625b1.png)
![bug22](https://user-images.githubusercontent.com/29306248/85941677-cb752700-b956-11ea-89f9-aadbbb067274.png)

**Comment by wangzhen-fit2cloud** [comment]
我们在压力配置这里我们使用了一些其他插件，最后运行的脚本跟上传时候的脚本是有区别的
