### ISSUE TITLE
[FEATURE]建议[接口]参数增加启用/禁用勾选项，默认全部启用，自定义去除不需要勾选的项，便于实际场景操作

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#480]
**请描述您的需求或者改进建议.**

建议[接口]参数增加启用/禁用勾选项，默认全部启用，自定义去除不需要勾选的项，便于实际场景操作

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 建议[接口]参数增加启用/禁用勾选项，默认全部启用，自定义去除不需要勾选的项，便于实际场景操作
> 
> **请描述你建议的实现方案**

已支持，请更新致1.3版本
