### ISSUE TITLE
[FEATURE]接口定义和接口自动化模块收起只能从最小子模块逐级收起

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#4800]
**请描述您的需求或者改进建议.**
目前接口定义和接口自动化模块均有八级模块，当在日常工作中查看对应模块的接口时，逐级张开子模块，当展开模块较多时，前端响应较慢，但收起模块时需要逐级从第八级子模块逐级收起才能关闭，给工作带来较大的不便

**请描述你建议的实现方案**
提供在任意层级一键收起的功能

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下

**Comment by xulinde** [comment]
v1.13已支持
