### ISSUE TITLE
[FEATURE]创建接口自动化时环境配置很复杂

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#4801]
**请描述您的需求或者改进建议.**
目前项目中不同功能对应的接口定义的模块，每个模块使用的环境可能达到三四种，当我们在编写接口case调试完成之后，依然还需要在接口自动化那边再次进行一次环境的配置，大大增加了接口自动化的工作量；

**请描述你建议的实现方案**
能否提供根据接口定义中调试成功的case，在导入场景时自动在环境中选择成功case的环境，根据对应的匹配规则，给每一个导入的接口或者case提供一个默认的环境；

**Comment by xulinde** [comment]
环境配置那里可以设置不同的启用条件，会根据对应的规则匹配环境
