### ISSUE TITLE
[FEATURE]可配置的模块层级配置；

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#4803]
**请描述您的需求或者改进建议.**
目前项目中模块层级已经超过8级，但是目前只支持8级，导致超过8级的模块智能通过特殊命名的方式来解决，增加了场景创建的工作量；

**请描述你建议的实现方案**
提供可配置层级的功能

**Comment by xulinde** [comment]
您的模块层级大概有多少级呢
