### ISSUE TITLE
[BUG]Jenkins插件执行有失败用例的测试计划时Jenkins插件会一直死循环

### ISSUE THREAD

**Issue by five3** [metersphere/metersphere#4809]
**MeterSphere 版本**
> v1.10.4 
> 插件同步为v1.10.4版本

**Bug 描述**

当使用新升级的插件执行有失败用例的测试计划时，Jenkins插件会一直死循环

**Bug 重现步骤**

1.  升级Jenkins插件和ms服务至v1.10.4版本
2.  创建一个有失败用例的测试计划
3.  Jenkins中通过插件调用此测试计划
4.  通过Jenkins插件启动执行

**期待的正确结果**

正常调用测试计划并正常获取结果

**原因分析**

由于Jenkins调用的的ms接口中默认设置为 执行错误时停止测试，
此设置会导致测试计划提前中断，而没有更新测试计划的状态为Failed
因此Jenkins插件由于获取不到有效的测试计划结束状态而一直轮询测试计划状态

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
v11.2已修复
