### ISSUE TITLE
[BUG]测试用例关联接口用例失败

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4818]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.6-lts
**Bug 描述**

简要描述您碰到的问题
选了接口用例，在下方窗口中也不显示，再打开，还是没有
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/126123300-ed8db4fd-93fe-4fe2-bc60-7b518089d685.png)

**Comment by zyyfit** [comment]
您好，关联用例需要接口定义下面有写好的接口用例，您选择的接口是否没有创建用例呢？

**Comment by zyyfit** [comment]
您好，关联用例需要接口定义下面有写好的接口用例，您选择的接口是否没有创建用例呢？

**Comment by locust-zhang** [comment]
是的，我反应的问题是，选了关联的接口用例，但是在下面的展示框中，没有出现这个被选中的，总之解释选取不是100%生效

**Comment by zyyfit** [comment]
这边没有复现这个问题呢，请问您选择的这个接口用例有什么特殊之处吗？有稳定复现的操作步骤吗？
