### ISSUE TITLE
[BUG]提示语文字错误

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4825]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.6-lts
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
有用例的接口/接口总数*100%
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/126130391-279ee327-736e-4b89-b5d7-c68b7f870758.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.11.1已修复
