### ISSUE TITLE
[BUG]接口定义导入MeterSphere.json文件无法解析

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#4827]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.5-lts-678b9a6a
**Bug 描述**

简要描述您碰到的问题
当接口定义的模块层级为第八级的时，且接口模块名称包含"/"时，创建模块和导出模块均正常，但是导入模块则报"数据解析错误"，查看后台代码，提示超过8个层级的错误；

**Bug 重现步骤**

1.  创建八级模块，模块名称包含"/"；
2. 在第八级模块下创建对应的接口定义；
3. 导出模块文件，文件格式为MeterSphere.json
4. 导入到新的项目中；

**期待的正确结果**

正确情况下应该是什么样的？
正确的结果是能正常导入，同时第八级的模块名称不发生变化，包含"/"
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by AgAngle** [comment]
1.11已修复
