### ISSUE TITLE
[BUG]变量名较长时，会出现重叠问题

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#483]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.0
**Bug 描述**
变量名较长时，会出现重叠问题
![image](https://user-images.githubusercontent.com/53041390/94335831-d4869a80-0010-11eb-8d3b-d33c9d006092.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
这个缺陷已经修复，会随着1.4版本发布
