### ISSUE TITLE
[FETURE]接口测试，单个场景接口较多时，在某个接口后面增加接口较麻烦

### ISSUE THREAD

**Issue by shiyanan0915** [metersphere/metersphere#484]
**请描述您的需求或者改进建议.**
1、接口测试，单个场景接口较多时，在某个接口后面增加接口较麻烦，需要添加接口，然后一步一步拖到指定的位置
2、多个场景之间，接口不能切换场景

**请描述你建议的实现方案**
1、单个场景中，在某个接口可以选择，增加接口（在此接口后面）
2、多场景中，接口可以拖动切换

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 1、接口测试，单个场景接口较多时，在某个接口后面增加接口较麻烦，需要添加接口，然后一步一步拖到指定的位置
> 2、多个场景之间，接口不能切换场景
> 
> **请描述你建议的实现方案**
> 1、单个场景中，在某个接口可以选择，增加接口（在此接口后面）
> 2、多场景中，接口可以拖动切换

目前已经支持了哦，请更新到1.3版本
