### ISSUE TITLE
[BUG]安装后第一次加载速度特别慢

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#4843]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.6

**Bug 描述**
安装部署后，在浏览器输入 MS URL，需要等待2-3分钟才能完成加载，并显示登陆页面。如果清除浏览器缓存后，也会存在这个现象。

简要描述您碰到的问题

**Bug 重现步骤**

1.  完成 MS 安装部署，启动服务 
2.  在浏览器中输入 MS URL
3. 等待页面显示

**期待的正确结果**
在 10秒内完成所有资源加载，并正常显示登陆页面。

正确情况下应该是什么样的？
浏览器快速加载资源，并正常显示登陆页面。建议在10秒内完成。

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/46042812/126266486-cac5a853-d0c5-4e93-9553-02c9501c8a37.png)

**Comment by zyyfit** [comment]
您好，我们对前端展示做了优化，您可以升到最新版体验一下
