### ISSUE TITLE
[BUG]1.10.6 接口测试中上传文件名长的文件会失败，一直处于死锁的状态。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4844]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.6
![Uploading 上传文件名长的文件会失败.png…]()

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
您的文件名长度大概是多少个字符

**Comment by billguo** [comment]
文件名大概40个中文字左右。如果超长，前端入口做限制，后端要报错，不能一直卡着吧。或者增加些备注的地方。谢谢
已在1.11.0版本上验证。
