### ISSUE TITLE
[BUG]1.10.6 两个相同用户（姓名相同），一个是系统设置中创建，一个是域账号注册创建，删除系统设置创建，两个渠道账号都失效无法登录。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4845]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.6

**Bug 描述**  两个相同用户（姓名相同），一个是系统设置中创建，一个是域账号注册创建，删除系统设置创建，两个渠道账号都失效。

简要描述您碰到的问题

**Bug 重现步骤**

1.  在系统设置中创建一个账号叫张三，成功。
2. 第二天，张三通过LADP登录成功，就有两个张三账号。
3. 管理员权限，搜索张三，删除该账号。
4. 张三无论用普通账号登录，还是LADP登录都失败。

**重点：**  删除该用户时，是不是where条件没有带渠道到底是普通用户还是LADP用户。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
目前就是这样设计的～

**Comment by zyyfit** [comment]
现在是系统中有local的张三后，LDAP登录会直接使用LOCAL张三的信息登录，但是选择LDAP方式登录时密码是用LDAP的密码，然后只有一个LOCAL用户，删除的时候就会把这个唯一的用户删掉，但是LDAP登录还是可以登录的，登录后会再生成一个LDAP的张三用好
