### ISSUE TITLE
[FEATURE]接口测试请求名称显示不全，而且无法拖动查看

### ISSUE THREAD

**Issue by shiyanan0915** [metersphere/metersphere#485]
**请描述您的需求或者改进建议.**
接口测试中，请求名称显示不全，而且无法拖动查看

**请描述你建议的实现方案**
建议可以增加向左向右拖动查看滚动条

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 接口测试中，请求名称显示不全，而且无法拖动查看
> 
> **请描述你建议的实现方案**
> 建议可以增加向左向右拖动查看滚动条

麻烦提供一下截图 不清楚你说的哪个地方呢

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，请更新到最新版本～
