### ISSUE TITLE
[FEATURE]用例状态可以改为非必填项吗？有些公司并没有应用

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#4857]
**请描述您的需求或者改进建议.**
1、用例状态可以改为非必填项吗？有些公司并没有应用。
2、另外如果这个用例状态是为了追踪所有用例在不同迭代版本里的执行状态，建议值改为未执行，成功，失败，堵塞，无须执行，是否更合理？

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们内部讨论下再给反馈

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 1、用例状态可以改为非必填项吗？有些公司并没有应用。
> 2、另外如果这个用例状态是为了追踪所有用例在不同迭代版本里的执行状态，建议值改为未执行，成功，失败，堵塞，无须执行，是否更合理？
> 
> **请描述你建议的实现方案**

用例状态是当前用例是否设计完成的一个状态，不是执行状态。 会有默认值，这个状态可以统计出大家设计用例花费的时间。
