### ISSUE TITLE
[FEATURE]测试计划关联测试用例，不能同时关联多个模块里的用例

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#4858]
**请描述您的需求或者改进建议.**
假设用例的目录层级如下：
-A 
  --A1
  --A2
测试计划关联测试用例，当我选择A1的用例后，切换到A2的用例时，A1选择的用例会被清空，我不能同时关联多个模块的用例。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您用的哪个版本，正常是不会被清空的，您可以关联完再看下测试计划列表
