### ISSUE TITLE
[FEATURE]接口测试报告建议可以生成html文档

### ISSUE THREAD

**Issue by shiyanan0915** [metersphere/metersphere#486]
**请描述您的需求或者改进建议.**

接口测试执行后，并不能生成测试报告，用来发送邮件

**请描述你建议的实现方案**
建议可以生成html文档报告

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 接口测试执行后，并不能生成测试报告，用来发送邮件
> 
> **请描述你建议的实现方案**
> 建议可以生成html文档报告

已经支持导出PDF了，更新到1.3版本使用
