### ISSUE TITLE
上传文件的接口，批量执行时，报错：Non HTTP response code: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by grily** [metersphere/metersphere#487]
1.上传文件的接口，单独执行，或者保存并执行，可以执行成功。
2.在批量执行时，上传文件的接口会报错
![image](https://user-images.githubusercontent.com/19886445/94353910-b9676980-00a8-11eb-8284-5d974930131b.png)
![image](https://user-images.githubusercontent.com/19886445/94353918-c97f4900-00a8-11eb-9004-bca29834a12c.png)
查看这个路径下确实没找到该文件

**Comment by fit2-zhao** [comment]
发现类似的一个缺陷已经修复，和这条相同的缺陷未能复现出来。
