### ISSUE TITLE
请求正则提取时望能取多个

### ISSUE THREAD

**Issue by LJH20200323** [metersphere/metersphere#488]
**请描述您的需求或者改进建议.**

请求正则提取希望可以提取多个：如存在多个cookie
![image](https://user-images.githubusercontent.com/62527960/94355519-3d285280-00b7-11eb-8d48-97bccd8dd84f.png)
目前是不能取到所有cookie，只会取最后一个;但这种场景要使用的cookie是所有

**Comment by xulinde** [comment]
您好，我们平台现在是支持正则提取多个值的，您可以升级到最新版本体验下
