### ISSUE TITLE
[BUG]接口场景详情操作

### ISSUE THREAD

**Issue by MetalHead77** [metersphere/metersphere#4888]
**MeterSphere 版本**
1.10.5-lts

**Bug 描述**

在接口测试-接口自动化-场景列表中，批量操作以下步骤：
复制一下，场景全部收起;
删除一下，场景全部收起；
移动一下，场景全部收起；
展开一个场景，场景全部收起。
操作体验感特别差。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.13已优化
