### ISSUE TITLE
[BUG]在最近报告中点击已删除的报告名称会跳转到未删除的报告中

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#49]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.2-b357

**Bug 描述**
简要描述您碰到的问题
在最近报告中点击已删除的报告名称会跳转到未删除的报告中

**Bug 重现步骤**
1.  新建2个测试报告
2. 删除一个报告
3. 在最近报告中点击删除的报告

**期待的正确结果**
正确情况下应该是什么样的？
提示已删除或无跳转

**截图**
如果有截图，请附上截图.
![bug3](https://user-images.githubusercontent.com/29306248/85941980-eba5e580-b958-11ea-803e-106d3bd1a6f9.png)

**Comment by wangzhen-fit2cloud** [comment]
Duplicate of #40
