### ISSUE TITLE
[FEATURE]测试报告，支持导出

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#490]
**请描述您的需求或者改进建议.**
生成的测试报告，支持导出到本地。

**请描述你建议的实现方案**
生成的测试报告，支持导出到本地。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 生成的测试报告，支持导出到本地。
> 
> **请描述你建议的实现方案**
> 生成的测试报告，支持导出到本地。

已支持，请更新到1.3版本
