### ISSUE TITLE
[BUG]1.10.6， 选择组织，选择工作空间，登录A用户，选择该组织下，该工作空间下， 导入测试用例失败。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#4905]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.6， 
 1， 选择组织。
2， 选择工作空间。
3， 登录A用户。 
4， 选择该组织下。
5， 该工作空间下。 
6， 导入测试用例失败。
![权限控制](https://user-images.githubusercontent.com/14307013/126450800-968a556a-ea39-49b9-b53a-8d1e0f75dc20.png)

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
请问这个用户有项目权限吗？没有项目权限的话现在也会这样提示，后面会修复这个提示问题的

**Comment by billguo** [comment]
这个项目创建的这个项目，肯定具备访问操作该项目的权限。

**Comment by zyyfit** [comment]
请问您这个用户的ID也是 陈红英 吗？这里是需要填id的，不能填姓名

**Comment by billguo** [comment]
那你的模板就有问题，为啥模板上写的是 责任人

**Comment by billguo** [comment]
模板应该修改为责任人ID，就好了。
