### ISSUE TITLE
场景变量解析csv类型变量时，单元格内容本事有逗号时解析结果不正确，预览是正常的

### ISSUE THREAD

**Issue by zcyuefan** [metersphere/metersphere#4909]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  进入接口测试-接口自动化-场景变量
2. 添加csv变量，其中单元格内容本身就包含逗号
3. 运行场景
4. 

**期待的正确结果**

正确情况下应该是什么样的？
正确解析，可对比环境变量时csv文件预览的效果

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已支持配置分隔符
![图片](https://user-images.githubusercontent.com/73461316/144348448-125dfadd-ff52-4d18-b8bc-60fac77146d3.png)
