### ISSUE TITLE
[FEATURE] 希望MS中对jmeter自带的MD5 等函数增加支持

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4917]
**请描述您的需求或者改进建议.**
希望MS中对jmeter自带的MD5 等函数增加支持

**请描述你建议的实现方案**
希望MS中对jmeter自带的MD5 等函数增加支持

**Comment by zhangzhaox** [comment]
MD5是插件函数的引用后的结果，不是原生自带的
性能测试可以自定义包 或上传jar  可正常使用
jmeter-plugins-functions-2.1.jar

**Comment by dashenyucainiao** [comment]
如果是接口测试的话，该如何使用？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE] 希望MS中对jmeter自带的MD5 等函数增加支持 (#4917)





 
MD5是插件函数的引用后的结果，不是原生自带的
 性能测试可以自定义包 或上传jar  可正常使用
 jmeter-plugins-functions-2.1.jar

**Comment by zhangzhaox** [comment]
接口测试自动化   使用方法
import org.apache.commons.codec.digest.DigestUtils;     内置的方法直接引用  

String ABC=DigestUtils.md5Hex("d01a0e48a1e4a5a9563bbec60500b9dc")+"16235048142897868";
String BCD=DigestUtils.md5Hex(ABC);

**Comment by dashenyucainiao** [comment]
我试试，谢谢了
