### ISSUE TITLE
[FEATURE] 提交api后，如果返回是json，body中应该默认改成 json

### ISSUE THREAD

**Issue by ibuler** [metersphere/metersphere#492]
**请描述您的需求或者改进建议.**

提交api后，如果返回是application/json，body中应该默认改成 json，不要再让用户去选

![image](https://user-images.githubusercontent.com/17382885/94364732-1f321080-00fe-11eb-9c1f-e81a391065fe.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，这里已经优化过了，您可以升级到最新版本体验下
