### ISSUE TITLE
[BUG]接口自动化下，事务控制器增加子事务控制器，子控制器下调试结果未显示

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#4920]
**MeterSphere 版本**
V1.10.5

**Bug 描述**

接口自动化下，事务控制器增加子事务控制器，子控制器下调试状态是有的，但是调试的具体内容没有

**截图**

**Comment by xulinde** [comment]
感谢反馈，我们先排查下

**Comment by xulinde** [comment]
11.1版本已修复
