### ISSUE TITLE
[BUG]脑图模式下用例调整顺序保存无效

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#4929]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.10.5-678b9a6a

**Bug 描述**

脑图模式下用例调整顺序保存无效，调整好后刷新又乱了

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

可以正常保存，保存后列表里用例的顺序也按脑图进行排序

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
目前还不支持用例顺序调整

**Comment by zhoujimin** [comment]
> 目前还不支持用例顺序调整

能否支持下，脑图很难避免在一些节点添加修改新的用例，如果无法调整，会很乱

**Comment by zyyfit** [comment]
> > 目前还不支持用例顺序调整
> 
> 能否支持下，脑图很难避免在一些节点添加修改新的用例，如果无法调整，会很乱

我们内部规划一下，可能后期会支持

**Comment by xulinde** [comment]
1.12已支持该功能
