### ISSUE TITLE
[BUG]往JIRA提交bug时，key值只能使用id，不能使用name或value等

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#4930]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.10.5-678b9a6a

**Bug 描述**

由于jira自定义字段原因，key值通常使用的是name或者value，metersphere写死用id传，不符合接口要求

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/67677349/126472970-4e6d4597-28f0-43d3-a225-9c8a7cdfdc5f.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
请问您是说只能使用 选项 2 这种形式 ，不能使用 选项 1 这种形式吗？
![图片](https://user-images.githubusercontent.com/73461316/126954694-16f96d2f-70a3-488c-8087-10f4ac0a5744.png)

**Comment by zyyfit** [comment]
请问您是说只能使用 选项 2 这种形式 ，不能使用 选项 1 这种形式吗？
![图片](https://user-images.githubusercontent.com/73461316/126954694-16f96d2f-70a3-488c-8087-10f4ac0a5744.png)
