### ISSUE TITLE
[FEATURE] 环境域名不应该强制(自动) / 结尾

### ISSUE THREAD

**Issue by ibuler** [metersphere/metersphere#494]
**请描述您的需求或者改进建议.**

这样我的地址需要写成没有前面  / 的，太丑了

![image](https://user-images.githubusercontent.com/17382885/94389896-a9708800-0183-11eb-95bd-ba2051b8ee81.png)

![image](https://user-images.githubusercontent.com/17382885/94389937-cad17400-0183-11eb-9c7a-0468625bfa26.png)

**请描述你建议的实现方案**

如果没有足够好处，不要帮用户做选择

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已实现，请更新
