### ISSUE TITLE
[FEATURE]我们测试团队 积累了多个项目的性能测试脚本，报告，希望Metersphere能在性能测试模块 提供 类似 仓库中心 功能，可以批量上传，删除，替换批量脚本，报告，pdf

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#4940]
**请描述您的需求或者改进建议.**
我们测试团队 积累了多个项目的性能测试脚本，报告，测试技术文档，希望Metersphere能在性能测试模块 提供 类似 仓库中心 功能，可以批量上传，删除，替换批量脚本，报告，pdf等。

**请描述你建议的实现方案**
现在 虽然可以上传jmx文件，但是是列表形式，不方便管理。希望能提供树状结构，用户可以自己自定义文件。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。
