### ISSUE TITLE
[BUG]swagger接口导入提示成功，但是只把模块的目录接口导入了，没有导入接口定义

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4946]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.6-lts
**Bug 描述**

简要描述您碰到的问题
用url导入ms项目本身的swagger接口，或者是json文件导入，都有一定概率出现这样的现象：
提示导入成功，但是只把模块的目录接口导入了，没有导入接口定义，导入其他swagger接口也出现同样的状况

我的安装环境就是一台机器，allinone安装

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/84962582/126598635-ec1922fb-39ee-44d9-808b-75b0c5c62b83.png)

**Comment by zyyfit** [comment]
您好，目前重复接口的话不会重复导入的，也不会修改接口所属的模块信息

**Comment by locust-zhang** [comment]
> 您好，目前重复接口的话不会重复导入的，也不会修改接口所属的模块信息

没理解，现在是全新url导入也提示成功，但是实际并没有成功，而通过json文件可以导入
![image](https://user-images.githubusercontent.com/84962582/126620547-3369730e-b7a8-4fd0-aee7-559f2ee88d0d.png)
![image](https://user-images.githubusercontent.com/84962582/126620597-a986b117-39dc-4c5d-9907-1e076bdfced8.png)
![image](https://user-images.githubusercontent.com/84962582/126620668-f538f8ce-3bc6-4b58-8101-807ffaf13ec7.png)

**Comment by zyyfit** [comment]
哦哦，您使用的是swagger 3 版本吗

**Comment by locust-zhang** [comment]
> 哦哦，您使用的是swagger 3 版本吗

是的，我导入的就是咱们metersphere的swagger url地址，而且并非每次都不行，导入成功过，但更多的是提示成功，但实际导入不成功，不成功的表现也不一样，上面的2种情况都有

**Comment by billguo** [comment]
我专门咨询过，**_设计如此_**，具体内容不会导入进来---》所以为0，但会把模块名字导入进来，所以有多个重复的模块名字----》很迷惑的操作。。哈哈哈哈哈哈哈哈。
