### ISSUE TITLE
[BUG] 接口测试中 api 中带了参数，转换过去不对

### ISSUE THREAD

**Issue by ibuler** [metersphere/metersphere#495]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
rd

**Bug 描述**
接口测试中 api 中带了参数，转换过去不对，如 请求
```
/api/v1/users/users/?limit=10
```
结果为

![image](https://user-images.githubusercontent.com/17382885/94390085-361b4600-0184-11eb-993d-9c2e51dfd1e9.png)

再次修改 url

![image](https://user-images.githubusercontent.com/17382885/94390117-4af7d980-0184-11eb-8956-1d9c42b2b105.png)

**Bug 重现步骤**
如上

**期待的正确结果**
不要帮我整理url地址，有时还以为出错了呢，可以在请求参数中有。

另外整理出来的请求参数还是错的，还整理了多次

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
请求参数提取错误已修改
