### ISSUE TITLE
[FEATURE]集成JIRA时，添加自定义字段，希望可以使用除ID以外的字段进行关联。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#4957]
**请描述您的需求或者改进建议.**
集成JIRA时，添加自定义字段，希望可以使用除ID以外的字段进行关联，有客户反应他们用的不是ID

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/77324661/126612040-087e5890-ff02-476f-a424-9584a360c4d3.png)

**Comment by xulinde** [comment]
选项值填的对吗
![Uploading image.png…]()

**Comment by binbin0406** [comment]
已确认可以使用其他key
