### ISSUE TITLE
[BUG]导入的用例无责任人时无法在计划中进行关联

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#4960]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.0
**Bug 描述**
测试用例模版中去掉了责任人字段，导入时责任人字段为空，导致测试计划中无法加入该测试用例，手动在数据库中加入责任人字段maintainer后，该用例可以添加到计划中了

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
责任人字段可以被去掉，那么添加用例到计划中时应不去做责任人的判断，为空时也能正常添加。
![image](https://user-images.githubusercontent.com/40912823/126618105-44970868-ac69-4535-9033-143c2fdcfd6f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v11.2已修复
