### ISSUE TITLE
[FEATURE] 与禅道对接，建议增加“动态字段”的配置

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#4966]
**请描述您的需求或者改进建议.**

何为“动态字段”：这个字段在禅道中没有固定的值，他的值来源于其他模块的数据，譬如“所属模块”，“所属迭代”，“所属版本”等

**请描述你建议的实现方案**

希望加上这样的字段配置功能。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 何为“动态字段”：这个字段在禅道中没有固定的值，他的值来源于其他模块的数据，譬如“所属模块”，“所属迭代”，“所属版本”等
> 
> **请描述你建议的实现方案**
> 
> 希望加上这样的字段配置功能。

目前系统设置里面也可以添加自定义字段
