### ISSUE TITLE
[BUG]自动化实时报告数据显示错误

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#4969]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.0

**Bug 描述**
如下图中，报告结果应该是有1、2、3 ，3个对应的流程，但是报告中逻辑判断执行到3流程，但是2流程也显示的3流程的内容

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/40912823/126624205-17dff50e-4592-4dfc-b60e-4d4e96b656bc.png)

![image](https://user-images.githubusercontent.com/40912823/126623992-cbafe8dd-cca7-4e65-b3b2-236666eef988.png)

**Comment by xulinde** [comment]
用最新版本还有此问题吗
