### ISSUE TITLE
[FEATURE]建议增加导出用例或者复制用例的功能

### ISSUE THREAD

**Issue by huguangya** [metersphere/metersphere#497]
**请描述您的需求或者改进建议.**

建议增加导出用例或者复制用例的功能，比如在一个项目中已经维护好了用例，另一个项目的用例类似，就可以导出或者复用之前项目的用例再做微调即可。

**请描述你建议的实现方案**
（1）增加导出用例的功能，导出的excel和导入模板格式一致；
（2）增加复制/引用其他项目用例的功能。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 建议增加导出用例或者复制用例的功能，比如在一个项目中已经维护好了用例，另一个项目的用例类似，就可以导出或者复用之前项目的用例再做微调即可。
> 
> **请描述你建议的实现方案**
> （1）增加导出用例的功能，导出的excel和导入模板格式一致；
> （2）增加复制/引用其他项目用例的功能。

已经有导出用例的功能了，复制用例的也有了，可以复制之后通过修改模块来转移到其他项目
