### ISSUE TITLE
[BUG]测试跟踪模块，在线编辑脑图后，无法修改排序。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#4977]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

在线编辑脑图，更改排序，保存后刷新页面后，排序未更新

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

支持自定义排序，这个功能很常用

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
脑图暂不支持排序，后续版本可能会支持

**Comment by xulinde** [comment]
1.12已支持该功能
