### ISSUE TITLE
[BUG]jenkins触发测试计划执行，实际是触发了执行，在ms上看执行也成功了，但是jenkins控制台循环提示“测试计划开始执行”，无法finish，并显示构建结果

### ISSUE THREAD

**Issue by locust-zhang** [metersphere/metersphere#4979]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.6-lts，及对应jenkins插件
**Bug 描述**
jenkins触发测试计划执行，实际是触发了执行，在ms上看执行也成功了，但是jenkins控制台循环提示“测试计划开始执行”，无法finish，并显示构建结果
简要描述您碰到的问题
jenkins触发测试计划执行，实际是触发了执行，在ms上看执行也成功了，但是jenkins控制台循环提示“测试计划开始执行”，无法finish，并显示构建结果
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/84962582/126730234-976eddc4-76bd-4b48-a927-160fb76b997a.png)

![image](https://user-images.githubusercontent.com/84962582/126730193-8faa6221-a67a-435f-8372-71c16be59710.png)

如果有截图，请附上截图.

**Comment by locust-zhang** [comment]
如果执行方式选择单独选择测试执行，则可以正常出发测试，及finish并返回结果

**Comment by xulinde** [comment]
使用最新版本还有问题吗

**Comment by xulinde** [comment]
v1.12.1已修复
