### ISSUE TITLE
建议在测试跟踪模块添加整个模块复制的功能[FEATURE]

### ISSUE THREAD

**Issue by JasonWurunfei** [metersphere/metersphere#4982]
**请描述您的需求或者改进建议.**
建议在测试跟踪模块添加整个模块复制粘贴的功能

**请描述你建议的实现方案**
1、右击模块树模块后可以选择复制并在别的模块或是当前模块下粘贴复制的模块
例如在Quality Center中可以直接复制粘贴模块模块树的模块
![复制粘贴](https://user-images.githubusercontent.com/47469275/126734035-11a35588-6ee0-4422-9216-f43beac01e45.png)

2、在脑图中实现对整个模块的复制粘贴（ctrl-c, ctrl-v）
目前是可以在脑图中复制粘贴但是无法正常保存

**Comment by xulinde** [comment]
1.后续版本可以添加此功能；
2.无法正常保存，是指保存不生效，还是保存会报错呢

**Comment by shuowu1jin** [comment]
> 1.后续版本可以添加此功能；
> 2.无法正常保存，是指保存不生效，还是保存会报错呢

不生效
是不是因为case名字不能重复？不能模块复制感觉很不方便

**Comment by luty2018** [comment]
非常抱歉现在才回复。
脑图模式下已经支持整个模块复制了，可以更新到v2.7版本使用。
