### ISSUE TITLE
[FEATURE]增加排序功能

### ISSUE THREAD

**Issue by huguangya** [metersphere/metersphere#499]
**请描述您的需求或者改进建议.**
测试用例增加排序功能。
场景：目前excel编写用例时时维护好顺序的，但是导入系统后顺序全乱了。

**请描述你建议的实现方案**
建议测试用例根据导入的顺序进行排列，或导入模板增加排序字段支持用户自定义排序。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 测试用例增加排序功能。
> 场景：目前excel编写用例时时维护好顺序的，但是导入系统后顺序全乱了。
> 
> **请描述你建议的实现方案**
> 建议测试用例根据导入的顺序进行排列，或导入模板增加排序字段支持用户自定义排序。

目前是按Excel顺序排的哦，请更新到1.3版本使用，如有问题继续反馈哈
