### ISSUE TITLE
[BUG]场景回收站无法批量恢复

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#4993]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.10.5-lts-678b9a6a

**Bug 描述**

简要描述您碰到的问题
批量误删了接口自动化中的场景，在回收站中选择全部批量恢复时只能恢复默认的10条，无法一次恢复全部

**Bug 重现步骤**

1.  将超过十个接口自动化场景放入回收站
2. 点击回收站，选择全部场景，点击批量恢复
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.11.0已修复
