### ISSUE TITLE
[BUG]展开已有模块时添加/修改模块会整体刷新收起

### ISSUE THREAD

**Issue by Michomzhudaisheng** [metersphere/metersphere#50]
**MeterSphere 版本**
v1.0.1-b352

**Bug 描述**
维护测试用例得时候，管理模块 操作新增或者编辑模块时，即使展开了其他模块，也会自动刷新收起，操作体验差

**Bug 重现步骤**
1.  测试跟踪-选择项目，展开已有模块，操作任意模块得添加/修改

**期待的正确结果**
1. 已展开得模块继续保持展开

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> v1.0.1-b352
> 
> **Bug 描述**
> 维护测试用例得时候，管理模块 操作新增或者编辑模块时，即使展开了其他模块，也会自动刷新收起，操作体验差
> 
> **Bug 重现步骤**
> 
> 1. 测试跟踪-选择项目，展开已有模块，操作任意模块得添加/修改
> 
> **期待的正确结果**
> 
> 1. 已展开得模块继续保持展开

请更新至v1.0.2 版本查看哈
