### ISSUE TITLE
[FEATURE]支持拖拽调整列宽

### ISSUE THREAD

**Issue by huguangya** [metersphere/metersphere#500]
**请描述您的需求或者改进建议.**
建议：测试用例列表支持拖拽调整列宽。
场景：目前列表宽度固定，有些字段内容较多显示不全。

**请描述你建议的实现方案**
列表支持拖拽调整列宽。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 建议：测试用例列表支持拖拽调整列宽。
> 场景：目前列表宽度固定，有些字段内容较多显示不全。
> 
> **请描述你建议的实现方案**
> 列表支持拖拽调整列宽。

已经支持了，请更新到1.3版本使用哦
