### ISSUE TITLE
[BUG]切换上一条下一条时测试结果没有获取最新记录

### ISSUE THREAD

**Issue by huguangya** [metersphere/metersphere#502]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.1-b352
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  选择测试计划
2. 选择测试用例
3. 选中一条用例点击编辑，维护测试结果，选择通过后保存；
4. 切换到上一条再切换回来刚刚编辑的这条，看到并没有标记通过，则测试结果是空的，但是返回列表页面看到是通过的。

**期待的正确结果**
正确情况下应该是什么样的？
主要测试结果保存后，无论如何切换都应该加载最新结果。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54281046/94421386-0b4ae500-01b8-11eb-9fee-15d920e4979b.png)

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 您所使用的 MeterSphere 版本是？
> v1.0.1-b352
> **Bug 描述**
> 简要描述您碰到的问题
> 
> **Bug 重现步骤**
> 
> 1. 选择测试计划
> 2. 选择测试用例
> 3. 选中一条用例点击编辑，维护测试结果，选择通过后保存；
> 4. 切换到上一条再切换回来刚刚编辑的这条，看到并没有标记通过，则测试结果是空的，但是返回列表页面看到是通过的。
> 
> **期待的正确结果**
> 正确情况下应该是什么样的？
> 主要测试结果保存后，无论如何切换都应该加载最新结果。
> 
> **截图**
> 如果有截图，请附上截图.
> ![image](https://user-images.githubusercontent.com/54281046/94421386-0b4ae500-01b8-11eb-9fee-15d920e4979b.png)

建议更新到1.3版本看看是否存在问题哈
