### ISSUE TITLE
[FEATURE]希望提供场景、接口定义、接口case的自动保存功能

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5029]
**请描述您的需求或者改进建议.**
当做场景设计时，设计的接口和逻辑比较复杂时，需要经常切换到接口定义处修改提取的参数，当切换过去时，如果忘记保存场景时，则需要重做整个场景，非常不便，同时接口定义和接口case也存在相同的情况；

**请描述你建议的实现方案**
提供类似wiki一样的草稿的功能，当修改后自动保存，当全部调试完成后，提供类似正式发布的功能，来进行持久存储

**Comment by xulinde** [comment]
感谢反馈，后续可以优化下这里

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 当做场景设计时，设计的接口和逻辑比较复杂时，需要经常切换到接口定义处修改提取的参数，当切换过去时，如果忘记保存场景时，则需要重做整个场景，非常不便，同时接口定义和接口case也存在相同的情况；
> 
> **请描述你建议的实现方案**
> 提供类似wiki一样的草稿的功能，当修改后自动保存，当全部调试完成后，提供类似正式发布的功能，来进行持久存储

点关闭会提示是否需要保存 1.13版本
