### ISSUE TITLE
[FEATURE]能否添加在线编辑脑图呢？上传的脑图可以不用转成文档或者同时兼容脑图和文档查看模式

### ISSUE THREAD

**Issue by jennyjane** [metersphere/metersphere#503]
**请描述您的需求或者改进建议.**
能否添加在线编辑脑图呢？
上传的脑图可以不用转成文档或者同时兼容脑图和文档查看模式
因为目前大家写用例都不用一条条写，都是脑图的模式；在线编辑体验更好

**请描述你建议的实现方案**
可以参考石墨文档：脑图和文档多模式兼容；
wiki的easymind支持在线编辑脑图，但是不能转文档

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，已有计划实现该需求，请关注后续版本～

**Comment by youliyuan-fit2cloud** [comment]
v1.8已实现
