### ISSUE TITLE
[FEATURE]批量执行接口定义的case

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5030]
**请描述您的需求或者改进建议.**
目前我需要制作场景的接口case有四千多条，一个接口定义对应一个case，如果手动一个一个选择环境去点击执行然后再写断言，这个过程比较繁琐，执行效率会非常低下，希望提供批量执行接口定义case的功能，只需要去填写想要的断言或其它的脚本等工作即可，这样效率会大幅提升；

**请描述你建议的实现方案**
提供类似场景那样的批量执行功能；

**Comment by xulinde** [comment]
接口用例目前是支持批量执行的
![image](https://user-images.githubusercontent.com/64065190/126974697-7415baa4-dcac-471d-b279-710efda36424.png)
