### ISSUE TITLE
[BUG]进入MeterSphere，后台报错

### ISSUE THREAD

**Issue by hexinyu1900** [metersphere/metersphere#5031]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ v1.11.0-4118f8c7

**Bug 描述**

进入MeterSphere，后台报错

**Bug 重现步骤**

1.  访问网站

**期待的正确结果**

无报错，接口测试能正常使用

**截图**

![image](https://user-images.githubusercontent.com/75720587/126860404-d0d4b64c-4dba-4b89-a39f-55890754c1c6.png)

**Comment by zyyfit** [comment]
您好，能稳定复现吗？这边没有复现呢

**Comment by billguo** [comment]
1.11.0创建数据库连接的问题了。。tail -200f opt/metersphere/logs/info.log， 里面有各种报错。

**Comment by hexinyu1900** [comment]
> 您好，能稳定复现吗？这边没有复现呢

能

**Comment by xulinde** [comment]
用最新版本还有此问题吗
