### ISSUE TITLE
[BUG]性能测试上传脚本附件资源 xxxx.tar.gz包附件不能上传

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#5033]
您所使用的 MeterSphere 版本是？
1.10.6LTS版本
**Bug 描述**
性能测试上传脚本附件资源 xxxx.tar.gz包附件不能上传

简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/82088551/126924641-af2edd35-928a-4c98-917d-402f5296c4b3.png)

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的，如果您有需要的话我们后续版本可以增加上传文件的种类

**Comment by zhangzhaox** [comment]
可以手动上传附件到opt 下的body目录 然后在脚本中指定绝对路径 是暂时规避使用的
