### ISSUE TITLE
[BUG]node负载节点监控的网络指标与Jmeter上的网络指标  相差较大

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#5035]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？  V1.10.6 LTS版本

**Bug 描述**
[BUG]node负载节点监控的网络指标与Jmeter上的网络指标  相差较大

node负载节点上的网络指标监控 具体含义是啥  想表达什么

简要描述您碰到的问题

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？
![lALPBFf_-rQNYBLNA0fNBxc_1815_839](https://user-images.githubusercontent.com/82088551/126927596-5f622ffd-ef93-456d-a711-227b37a54833.png)
![lALPBGnDc-vp0DvMy80HfA_1916_203](https://user-images.githubusercontent.com/82088551/126927615-8dbafac4-0cd0-45bc-9c47-d6aed2666721.png)

**截图**

如果有截图，请附上截图.

**Comment by seasoncool** [comment]
我们也出现了这个情况：

节点机器的，内存使用率，在metersphere的内置监控上，显示过高。

我们用普罗米修斯监控，显示正常，和PC在top下，使用的情况差不多。

**Comment by liuruibin** [comment]
我们使用(node_memory_MemTotal_bytes{instance='%1$s'} - node_memory_MemFree_bytes{instance='%1$s'}) / node_memory_MemTotal_bytes{instance='%1$s'} * 100 这个promql查询内存使用率，你可以检查一下

**Comment by zhangzhaox** [comment]
> 节点机器的，内存使用率，在metersphere的内置监控上，显示过高。
liunx下的内存使用率 基本上是无意义的，一个正常的持续运行服务器内存使用率高是正常的，内存是否不足主要指标是看swap的使用多少和是否存在频繁的变动交换

**Comment by xulinde** [comment]
v11.2已优化
