### ISSUE TITLE
[BUG] 接口请求里面的，前后置 sql，切换「运行环境」后无法随之切换

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#5037]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的，如果您有需求的话可以将bug改成enhancement

**Comment by jhong123** [comment]
> 您好，目前是这样设计的，如果您有需求的话可以将bug改成enhancement
好的，这个单可以关闭

https://github.com/metersphere/metersphere/issues/5121
