### ISSUE TITLE
[FEATURE]缺陷管理-建议增加高级查询-或者增加我的bug

### ISSUE THREAD

**Issue by jcma2021** [metersphere/metersphere#5043]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
创建人这里jia加个筛选，能满足您的需求吗
![image](https://user-images.githubusercontent.com/64065190/126975089-22371ac4-04f2-416b-b601-e6c07cdc3de8.png)
