### ISSUE TITLE
[FEATURE]消息通知-建议增加精准消息通知，而非现在的群发

### ISSUE THREAD

**Issue by jcma2021** [metersphere/metersphere#5044]
**请描述您的需求或者改进建议.**
基于事件的触发，例如bug ，就是群发
而不能提交给谁，就发给谁，减少打扰

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
消息设置这里，可以指定接收人
![image](https://user-images.githubusercontent.com/64065190/126975221-59819095-e477-43d3-aa85-dfb1fa797704.png)

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 基于事件的触发，例如bug ，就是群发
> 而不能提交给谁，就发给谁，减少打扰
> 
> **请描述你建议的实现方案**

1.目前机器人只能加入到群，所以只能群发，但是会@接收人，如果没有@请检查个人信息中是否绑定了手机号
2.单独给个人发不是机器人可以做的，需要开发第三方应用，这个还在规划中
