### ISSUE TITLE
[FEATURE]建议优化 测试跟踪-首页-遗留缺陷统计 块的数据加载速度，目前加载非常慢~

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5050]
**请描述您的需求或者改进建议.**
建议优化 测试跟踪-首页-遗留缺陷统计 块的数据加载速度，目前加载非常慢~

**请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/54024064/126952767-25651707-fb8e-495e-b9d3-84b76f4c2d61.png)

**Comment by xulinde** [comment]
您使用的是哪个版本，缺陷大概有多少条呢
