### ISSUE TITLE
[FEATURE] 接口自动化场景步骤都执行完后，【调试】按钮还一直显示“执行中”状态

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5052]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
接口自动化场景步骤都执行完后，【调试】按钮还一直显示“执行中”状态
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/54024064/126954003-92d5e70e-e144-4017-8ab2-e6f004c4d5ce.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是否是有接口在执行过程中卡主了？或者稍微等几秒钟看一下执行按钮状态？

**Comment by billguo** [comment]
这个是1.11.0的严重创建数据库连接池的问题，导致一直执行卡住了。只能每十五分钟重启一下镜像服务。已反馈给MS的开发了。。

**Comment by xulinde** [comment]
v11.2已修复
