### ISSUE TITLE
[BUG]测试计划>>关联场景测试用例>>多项目环境列表信息错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5053]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？V1.11

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试计划>>关联场景测试用例>>
2. 选择场景测试用例。其中一个场景用例是跨项目了。
2. 指定场景测试环境时，另外一个项目环境没有取到，依旧是上一个项目的环境列表
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/126954296-c115c444-7aaf-443a-a513-a761173ec59c.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现呢，能详细描述一下复现步骤吗
![图片](https://user-images.githubusercontent.com/73461316/127422592-f18cab62-5897-4400-83dc-19657b6fbec6.png)
