### ISSUE TITLE
[BUG] MYSQL8.0 not allowed NO_AUTO_CREATE_USER

### ISSUE THREAD

**Issue by lazychanger** [metersphere/metersphere#5054]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.0

**Bug 描述**
Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'

**Bug 重现步骤**
1. 本地使用Mysql8.0
2. 配置使用外部MYSQL，并且指向到mysql:8.0
**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/20916944/126963109-ef91d2dd-19f6-4e4f-ae0b-2286d37c259b.png)

**Comment by zhangzhaox** [comment]
不要使用8.0版本， 后面还有别的问题 造成升级脚本不成功，导致升级失败。 建议按照官方的要求5.7.33

Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'  这个问题在数据库配置文件里把这个mode删除即可
