### ISSUE TITLE
[FEATURE]首页布局，各模块的大小自适应

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#506]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.3
**Bug 描述**
简要描述您碰到的问题
首页规划的是四个区域，模块之间的行高是一样的，如果右侧的“最近测试”数据多，整体行高会变高，“用例评审”的内容会偏下，查看不便。见附件1和2

**Bug 重现步骤**
1.  首页规划的是四个区域，模块之间的行高是一样的，如果右侧的“最近测试”数据多，整体行高会变高，“用例评审”的内容会偏下，查看不便。

**期待的正确结果**
正确情况下应该是什么样的？
希望模块大小可以自适应，便于查看。

**截图**
如果有截图，请附上截图.
<img width="950" alt="附件2" src="https://user-images.githubusercontent.com/71361375/94633332-88cd3d00-02ff-11eb-88c3-21c19385518e.png">

**Comment by fit2-zhao** [comment]
问题已经修复
