### ISSUE TITLE
ms接口自动化点击运行的时候出来的报告显示未运行，点击编辑进去然后点击调试会一直显示执行中[BUG]

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#5072]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
 
您所使用的 MeterSphere 版本是？
v1.11.0-4118f8c7
**Bug 描述**

简要描述您碰到的问题
ms接口自动化点击运行的时候出来的报告显示未运行，点击编辑进去然后点击调试会一直显示执行中
更新到最新版本后就这样了
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
正确运行且出来报告结果
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/85992665/127087562-fc6ae83b-fbe4-470b-b53b-63b321f14ea4.png)
![image](https://user-images.githubusercontent.com/85992665/127087576-4b4e7555-e32d-4be5-9e93-ea1d54dfff60.png)

**Comment by billguo** [comment]
1.11.0的严重问题了。。老早就确定了。

**Comment by billguo** [comment]
我刚升级到1.11.1版本上，看到该问题已修改了。

**Comment by zyyfit** [comment]
您好，请问升级到1.11.1还会出现吗 @billguo

**Comment by Sensivitiry** [comment]
还会有，没解决
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Jul 29, 2021 10:40 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [metersphere/metersphere] ms接口自动化点击运行的时候出来的报告显示未运行，点击编辑进去然后点击调试会一直显示执行中[BUG] (#5072)

&nbsp;



 
您好，请问升级到1.11.1还会出现吗 @billguo

**Comment by zyyfit** [comment]
您好，点击运行的时候显示未执行这个是新改的，这个页面会一直刷新，同时更新每个用例的执行结果，
关于点进去一直是执行中的问题这边还是没有复现，您方便发一下接口脚本吗？ 或者是否是每个场景都这样？会出现这种情况的脚本里有什么特殊内容？

**Comment by xulinde** [comment]
有使用nginx吗，建议按以下方法，配下nginx支持websock
![image](https://user-images.githubusercontent.com/64065190/127814874-4ba0b70b-8c33-4151-af27-0fa6f565e54e.png)
