### ISSUE TITLE
[BUG]1.11.0 重大问题，使用一段时间后，首页一片空白，日志报数据库连接池错误，无法正常使用，已两天无法使用。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#5077]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.11.0

**Bug 描述**
重大问题，使用一段时间后，首页一片空白，日志报数据库连接池错误，无法正常使用，已两天无法使用。 
![日志报错](https://user-images.githubusercontent.com/14307013/127101896-315a7509-1d6e-4e74-ada0-02b9fa29d9b9.png)
![首页空白](https://user-images.githubusercontent.com/14307013/127101991-1c463bbc-ca67-4ef6-b817-7373d3e0abb4.png)

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
请问是这个问题吗
https://github.com/metersphere/metersphere/issues/5052

**Comment by xulinde** [comment]
建议关闭高频定时任务，看下是否还有此问题

**Comment by billguo** [comment]
关闭高频定时任务暂时解决了，但不是根本的解决之道呀。。数据库连接不释放，仍然要解决。

**Comment by xulinde** [comment]
1.11.2版本已经优化，把定时任务的数据库连接隔离开了，有问题也不会影响其他功能。到时候您可以升级体验下

**Comment by billguo** [comment]
1.11.2版本啥时候出来。
