### ISSUE TITLE
[BUG]接口导入 使用swagger2.0的方式，swagger已经定义了header的变量和默认值，而导入后 接口没有默认值

### ISSUE THREAD

**Issue by tanglingyu** [metersphere/metersphere#5081]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
接口导入 使用swagger2.0的方式，swagger已经定义了header的变量和默认值，而导入后 接口没有默认值

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
导入接口后，对应的默认值也设置好
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13已修复
