### ISSUE TITLE
[FEATURE]希望能增加下请求内容及响应结果中报文的搜索功能

### ISSUE THREAD

**Issue by liyunfeng666** [metersphere/metersphere#5086]
**请描述您的需求或者改进建议.**

希望能增加下请求内容及响应结果中报文的搜索功能，浏览器搜索当太长的时候，有时候搜索不到

**请描述你建议的实现方案**
希望能增加下请求内容及响应结果中报文的搜索功能，浏览器搜索当太长的时候，有时候搜索不到

**Comment by xulinde** [comment]
感谢反馈，后面版本可以支持
