### ISSUE TITLE
[BUG] 配置无误的情况下，带有图片的缺陷提交至禅道后，创建人不正确。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#5088]
**MeterSphere 版本**
V1.11.1

如下图配置了禅道账号，校验通过：

![8e6d519e-3d1f-4f4f-b465-324c4701cb1c](https://user-images.githubusercontent.com/44999044/127136337-ae7772d2-296c-4650-bee9-f2333cd6e94c.png)

如下图提交后的缺陷（包含图片的缺陷）创建人还是admin：

![afb2c053-0f09-48e9-af2e-7207cdbd5ef7](https://user-images.githubusercontent.com/44999044/127136323-31e09953-3863-4ef6-9cb1-5cd2d4b0567d.png)

补充：如果不包含图片，则创建人是正常的。

**Comment by xulinde** [comment]
v11.2已修复
