### ISSUE TITLE
[FEATURE]测试用例建议增加支持导出功能

### ISSUE THREAD

**Issue by Michomzhudaisheng** [metersphere/metersphere#51]
**请描述您的需求或者改进建议.**
测试用例建议增加支持导出功能

**请描述你建议的实现方案**
可以导出为 Excel 或者 脑图

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 测试用例建议增加支持导出功能
> 
> **请描述你建议的实现方案**
> 可以导出为 Excel 或者 脑图

想问下导出的使用场景是什么呢？

**Comment by mengshuai85** [comment]
有些需要提交给第三方的用例，需要导出Excel吧

**Comment by luty2018** [comment]
月底的版本会有导出功能------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;风无语&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月9日(星期四) 下午5:16
收件人:&nbsp;&quot;metersphere/metersphere&quot;<metersphere@noreply.github.com&gt;;
抄送:&nbsp;&quot;LuoTing&quot;<334631085@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]测试用例建议增加支持导出功能 (#51)

**Comment by luty2018** [comment]
1.1 已支持用例导出功能，请更新体验

**Comment by mengshuai85** [comment]
> 1.1 已支持用例导出功能，请更新体验

我试用了一下导出功能，比较简陋，只有清单列表

我理解的导出，是 把用例名称，步骤，（测试结果）等都可以导出来的，得有关联关系，而不是 单纯的一个 case名称列表，这样 没有多大实际效果

**Comment by chyhant** [comment]
建议增加测试用例导出为word文档方式，有时需要导出用例供验收用途！！
