### ISSUE TITLE
[FEATURE]测试用例：允许上传附件

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#510]
**请描述您的需求或者改进建议.**

测试用例允许上传附件，可以上传测试脚本、需求等附件。

**请描述你建议的实现方案**

测试用例允许上传附件，可以上传测试脚本、需求等附件。

**Comment by xulinde** [comment]
您好，目前测试用例是可以上传附件的
![image](https://user-images.githubusercontent.com/64065190/107309113-cbc8c980-6ac4-11eb-97a0-93d5e3d03b9e.png)
