### ISSUE TITLE
[FEATURE]提供案例统计，执行 统计功能，能方便按月、季、年查询统计

### ISSUE THREAD

**Issue by cds322** [metersphere/metersphere#5102]
**请描述您的需求或者改进建议.**
1、提供案例统计，执行 统计功能，能方便按月、季、年查询统计；总共修改的案例数、案例执行数数据；
2、BUG统计功能也需要。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by zhangzhaox** [comment]
部分的统计功能确实是需要的，尤其是自动化部分，不能直观的统计一段时间内的工作量，在考虑使用贵公司的另外一款开源产品DataEase来做这部分的需求，可视化统计分析功能
