### ISSUE TITLE
[FEATURE]针对测试案例审核，增加一键审批功能

### ISSUE THREAD

**Issue by cds322** [metersphere/metersphere#5103]
**请描述您的需求或者改进建议.**
针对测试案例审核，增加一键审批功能

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 针对测试案例审核，增加一键审批功能
> 
> **请描述你建议的实现方案**
批量修改评审结果即可
![image](https://user-images.githubusercontent.com/36292514/127440870-49e78313-9985-476b-ba45-1583419b8be6.png)
