### ISSUE TITLE
[FEATURE]强烈请愿！希望Jenkins插件支持查看当前运行MS内的结果

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#511]
**请描述您的需求或者改进建议.**

希望将jenkins自动触发后所产生的测试结果，反馈到jenkins中。

**请描述你建议的实现方案**
1. 直接将MS内执行的测试结果链接，追加到jenkins的console中(执行日志)，可匿名直接访问该测试报告。
或
2. 当jenkins运行完后，把MS内的导出结果（PDF格式），直接存放到jenkins的workspace下，并可以直接访问。
或
3. 如果能结合 jenkins的email notification 的插件，将测试结果输出到模板中，一步到位那就更好了。

谢谢。该功能对CI/CD 流程很重要，非测试人员会看这些报告，希望能增强一下，感谢。

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，目前问题1 已实现，2和3需要调研一下在做后续规划，请您持续关注～

**Comment by youliyuan-fit2cloud** [comment]
不考虑了，感谢理解~
