### ISSUE TITLE
[BUG]【接口定义】无法上传文件

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#5119]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.11.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/11580681/127304498-1c334551-5663-499d-90f8-f11edd43dbdb.png)

**Comment by xulinde** [comment]
感谢反馈，我们先排查下问题

**Comment by xulinde** [comment]
您是用的最新版本吗，文件重新上传下可以吗，我这边试了下没问题

**Comment by jhong123** [comment]
> 您是用的最新版本吗，文件重新上传下可以吗，我这边试了下没问题

重新上传文件后，没有报这个错了

**Comment by jhong123** [comment]
> 您是用的最新版本吗，文件重新上传下可以吗，我这边试了下没问题

补充一下，编辑接口后，文件上传，会报错（文件不存在）
