### ISSUE TITLE
支持页面测试的录制快速生成测试用例

### ISSUE THREAD

**Issue by sdwtao** [metersphere/metersphere#512]
**请描述您的需求或者改进建议.**
页面测试自动化的开发和维护工作量很大，如果能够实现录制即可生成用例，略作修改就可以反复执行回归，测试效率和用例生成效率会大幅的提升，请考虑

**请描述你建议的实现方案**
常见的录制工具以录制鼠标位置和动作为主，如果可以录制id或者xpath位置，执行可靠性可以有较大提升。

**Comment by wangzhen-fit2cloud** [comment]
你好，针对 web 页面的自动化测试功能目前还在规划中，欢迎持续关注
