### ISSUE TITLE
[BUG]上传文件，请求内容为binary，请求内容上传方式为form-data

### ISSUE THREAD

**Issue by RookieRoll** [metersphere/metersphere#5136]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
最新版本

**Bug 描述**
上传文件的接口时，请求体内容选择binary，当我从响应结果页面查看请求内容时，请求内容始终存在  form-data，这种传参方式会导致我上传的文件下载下来后无法打开

简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/18344470/127451999-aae70113-c828-4f15-a1c2-b7356bdaf948.png)

![image](https://user-images.githubusercontent.com/18344470/127452062-abdf5c95-c357-4cf0-95e4-a8aed0fe3270.png)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，请问您是在什么地方下载的这个文件呢？我们系统中目前上传的文件没有设置下载功能

**Comment by RookieRoll** [comment]
我的文件上传接口，body内容不是用form表单这种形式上传文件的，我选择的是binary二进制形式上传，但是请求body还是用的from表单，上传的文件就有问题

**Comment by zyyfit** [comment]
> 我的文件上传接口，body内容不是用form表单这种形式上传文件的，我选择的是binary二进制形式上传，但是请求body还是用的from表单，上传的文件就有问题

您好，我们正在排查问题，想跟您确认一下您使用postman或者jmeter是正常的吗？

**Comment by RookieRoll** [comment]
![5b964ee4-dbf1-443a-8df5-d00c3bea9387](https://user-images.githubusercontent.com/18344470/128654921-fad0426e-607b-4134-90a3-09748e47f12d.jpg) jmeter是正常的

**Comment by warmmilk** [comment]
遇到同样的问题，oss签名方式上传文件，必须是binary形式，但是metersphere强行转了一下，导致上传失败
postman也是正常的

**Comment by warmmilk** [comment]
![image](https://user-images.githubusercontent.com/51286902/130531269-33c8f9ff-6103-4158-a45e-e1873918748f.png)

**Comment by xulinde** [comment]
JMeter  本身机制就这样～暂时无法处理
