### ISSUE TITLE
[FEATURE]接口测试全局进行环境选择

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#514]
**请描述您的需求或者改进建议.**

多场景运行时，切换环境是否可以统一切换，如：dev环境跟sit环境的切换，现在是一个个场景去切换到同一个环境才能运行

**请描述你建议的实现方案**
能不能勾选多个场景后，切换一次就可以全部切换成功

**Comment by zyyfit** [comment]
与 https://github.com/metersphere/metersphere/issues/465 类似，将于1.8版本中优化
