### ISSUE TITLE
[FEATURE] 关于测试跟踪中功能用例功能的体验优化。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#5141]
**请描述您的需求或者改进建议.**

遇到的场景： 在一个复杂功能的项目中，功能测试用例写起来非常的多，在设计用例的过程中为了前后逻辑清晰且避免冗余的步骤，固在编写用例时用例与用例之间是有执行前后关系的，比如销假必须在请假流程通过后才能发起，这时发起销假业务的用例(ID: XJ001)的前提条件就会是请假流程的用例（ID：QJ001），即XJ001的前提条件是QJ001。这么写解决了引用问题。但是在评审用例时比较痛苦，尤其是用例几百上千条时，我在评审XJ001用例时，需要翻到QJ001作为背景介绍。然后此时就会在一堆用例里面翻找..比较麻烦。

**请描述你建议的实现方案**
在测试用例中的前提条件中 可添加其他用例的ID，在查看详情时可以通过超链接的方式直接点击并以弹框形式查看。

当然这只是我的建议，产品经理可以基于我的场景重新设计并给出解决方案。在此感谢。

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈
