### ISSUE TITLE
[BUG]测试报告场景顺序与编辑测试时顺序不一致

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#515]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.0-b805
**Bug 描述**
简要描述您碰到的问题
报告的场景顺序，跟接口的顺序不一致

**Bug 重现步骤**
1.  同一个测试下，有89个请求，15个场景
2. 全部执行
3. 报告的场景顺序和接口的顺序不一致
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望顺序一致

**截图**
如果有截图，请附上截图.
接口场景顺序：
![image](https://user-images.githubusercontent.com/70245535/95533381-98dad000-0a15-11eb-97fb-006053ea77cb.png)
报告的场景顺序
![image](https://user-images.githubusercontent.com/70245535/95533404-a4c69200-0a15-11eb-918f-bde3756afb67.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，未复现该问题，请尝试下清掉缓存之后再次执行

**Comment by Sylvie1222** [comment]
清了缓存，还是不行，录了一个视频，不知道如何发给你呢？

**Comment by AgAngle** [comment]
你好，我们还是没有复现，你可以先扫码加入下我们的微信群沟通反馈

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？

**Comment by Sylvie1222** [comment]
存在呢。我有视频可以发你哈

**Comment by Sylvie1222** [comment]
存在的，录了个视频，但是没办法发出去

**Comment by wangzhen-fit2cloud** [comment]
可以在我们的微信交流群里发一下。

**Comment by wangzhen-fit2cloud** [comment]
你好，请在新版本中验证该问题是否存在。我们将先关闭该问题，如果问题还存在请重新打开该问题。
