### ISSUE TITLE
[BUG]jenkins执行测试计划无故停止，报告卡在running

### ISSUE THREAD

**Issue by nan1jueze** [metersphere/metersphere#5156]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**

通过jenkins最新插件，插件版本1.11.1，MS版本1.11.1，通过jenkins插件执行测试计划，总共321条自动化，执行几十条后停止了，接口测试->测试报告中的waiting消失，但是测试跟踪->报告总还卡在running
通过测试计划的定时任务或者手动执行 不会有这个问题

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
收到，已经在排查问题了

**Comment by xulinde** [comment]
v11.2已修复，建议您升级ms版本在试下

**Comment by nan1jueze** [comment]
根本问题没有解决，测试计划中的场景化 执行一段时间后就莫名停了，没有全部执行完，依然running

**Comment by nan1jueze** [comment]
![image](https://user-images.githubusercontent.com/37619640/128498320-c9100bfe-6f9a-4b08-a3f6-427402f9bc10.png)
![image](https://user-images.githubusercontent.com/37619640/128498339-adb434f2-707b-4f4e-b4a3-9ff6224af626.png)
![image](https://user-images.githubusercontent.com/37619640/128498360-63c86053-47b1-45bb-a09b-93403c6481e3.png)

一个多小时没有运行了@xulinde

**Comment by xulinde** [comment]
是最新的11.2版本吗，测试计划里大概有几个场景呢，场景里有多少个步骤

**Comment by nan1jueze** [comment]
> 是最新的11.2版本吗，测试计划里大概有几个场景呢，场景里有多少个步骤

是11.2版本，测试计划里面有340个场景，场景步骤不好停机，平均大概4-5个吧
问题 定时任务的测试计划可以正常跑完
