### ISSUE TITLE
[BUG]测试报告的图表异常

### ISSUE THREAD

**Issue by nan1jueze** [metersphere/metersphere#5157]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
通过测试计划定时任务执行自动化场景，查看测试跟踪->报告，报告中的图表是异常的
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
<img width="360" alt="9a7af109e365f9b63dc3db1954618e3" src="https://user-images.githubusercontent.com/37619640/127597659-ef737dca-84e5-4584-807a-c5c3e0a51ae0.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
未复现该问题，用最新版本还有此问题吗
