### ISSUE TITLE
[FEATURE]增加错误判断与处理机制

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#5159]
**请描述您的需求或者改进建议.**

增加错误判断与处理机制，比如某一步骤执行错误，可以预先制定条件让它再执行一遍，再次错误再判定该用例执行失败

**请描述你建议的实现方案**
1.自动化重试机制
![image](https://user-images.githubusercontent.com/30932762/127607238-ece9495c-48c5-4a24-a19d-3fee3d38669a.png)
2.自动化内步骤重试机制
![image](https://user-images.githubusercontent.com/30932762/127607423-9cbda915-a629-4266-9165-f308cb809f58.png)

**Comment by xulinde** [comment]
感谢反馈，后续版本可以考虑支持
