### ISSUE TITLE
[BUG] 执行条件“等于”的场景不生效

### ISSUE THREAD

**Issue by luojiangnan88** [metersphere/metersphere#516]
**MeterSphere 版本**
版本: v1.3.0-b842

**Bug 描述**
执行条件“等于”的场景不生效

**Bug 重现步骤**
https://demo.metersphere.com/#/api/test/edit?id=e40695d5-6655-4c45-b543-01d986ba7f1a
1.  新建接口1，后执行脚本设置全局变量 ${__setProperty("value1",1,)};
2. 新建接口2，设置执行条件${value1}==1
3. 保存执行，发现第二个接口没有执行
4. 

**期待的正确结果**
第二个接口执行条件生效，应该执行

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，通过 ${__setProperty("value1",1,)} 方式设置的变量需要通过 ${__P("values1")} 引用
