### ISSUE TITLE
[BUG]V1.10.3通过命令msctl upgrade一键升级，最终升级后的版本还是V1.10.3

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#5161]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.10.3
**Bug 描述**

我当前版本是V1.10.3，然后我通过命令msctl upgrade一键升级，最终升级后的版本还是V1.10.3 不是官网最新的V1.11.1

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/42166114/127609994-468c999d-da90-4300-b05f-81560208dd75.png)
![image](https://user-images.githubusercontent.com/42166114/127610009-c8261296-2e63-4fcf-b518-f2fc99e663f7.png)
![image](https://user-images.githubusercontent.com/42166114/127610033-b709caa8-bc34-4ff2-a44e-14df620cebd1.png)

**Comment by zyyfit** [comment]
您好，您是在1.7.0的离线包文件夹下执行的 ./msctl upgrade 命令吗？您在其他目录下直接执行 msctl upgrade 试一下呢？
