### ISSUE TITLE
[BUG] jmeter导入MS中的模块控制器不执行

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5169]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.11.1

**Bug 描述**

简要描述您碰到的问题
 jmeter导入MS中的模块控制器 ，MS可以识别，但是内容显示不全，而且不执行

**Bug 重现步骤**

1.  
2. 

**期待的正确结果**

可以正确显示，并执行

**Comment by zyyfit** [comment]
您好，目前还不支持模块控制器

**Comment by zyyfit** [comment]
最新版已支持
