### ISSUE TITLE
[BUG]接口测试导入功能，swagger不可用

### ISSUE THREAD

**Issue by momo050200** [metersphere/metersphere#517]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.3

**Bug 描述**
在接口测试--导入功能中，选择swagger来源，导入json文件，提示解析数据错误

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/25170667/95537091-54543200-0a1f-11eb-8590-88da9be6b41a.png)

**Comment by AgAngle** [comment]
1.3.1已修复，请升级验证，若还出现问题，请截图下日志的报错 /opt/meterpshere/logs/meterspere/xx，方便的话可以提供下json文件，谢谢
