### ISSUE TITLE
[BUG] 自动化场景列表中执行结束的时候，会出现页面出错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5170]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 V1.11.1

**Bug 描述**

      自动化场景列表中执行结束的时候，会出现页面出错，刚开始执行的时候页面没有问题，结束的时候突然显示错误，但是下面的结果显示的没有问题

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![WechatIMG164](https://user-images.githubusercontent.com/32027713/127637811-3f347c19-d21c-4077-a3c2-dcf24f34f1c7.png)

**Comment by xulinde** [comment]
未复现该问题，方便把您的场景导出发给我们试下吗

**Comment by xulinde** [comment]
v11.2已修复
