### ISSUE TITLE
[FEATURE] 用例列表页面，支持批量删除用例、批量移动用例到指定模块目录下

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#5178]
**请描述您的需求或者改进建议.**
为了能方便调整一批用例的归属分类模块，不断调整按照更优的分类组织管理用例

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前就是支持的
![image](https://user-images.githubusercontent.com/64065190/127794608-eed47a1b-ad4e-4766-a8d1-7df5c6d453f2.png)
