### ISSUE TITLE
[BUG]用户在性能测试模块的上传jms有依赖的jar包，jar上传后执行时与MS的docker images 不兼容无法正常执行

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5179]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用户在性能测试模块的上传jms有依赖的jar包，jar上传后执行时与MS的docker images 不兼容无法正常执行
2. 其中jmeter-parallel-0.10.jar与5.4.1-ms6-jdk8不兼容  
3. mymd5.jar与5.4.1-ms7-jdk8不兼容
4. 必须在发压机指定容器版本为5.4.1-ms4-jdk8后才可正常执行。jar包见附件

**期待的正确结果**

正确情况下应该是什么样的？
上传jar包后可以正常运行
**截图**

如果有截图，请附上截图.
[jmeter-parallel-0.10.zip](https://github.com/metersphere/metersphere/files/6913985/jmeter-parallel-0.10.zip)
[mymd5.zip](https://github.com/metersphere/metersphere/files/6914000/mymd5.zip)

**Comment by wangzhen-fit2cloud** [comment]
新版本已解决该问题。
