### ISSUE TITLE
[FEATURE] Bug追踪详情应该就是编辑

### ISSUE THREAD

**Issue by ibuler** [metersphere/metersphere#518]
**请描述您的需求或者改进建议.**

编辑和详情中的的内容是完全一致的，没有必要保留详情，编辑就是详情。大部分产品也都是这么设计的。
退一步讲，哪怕不能编辑，上面的通过、失败 等按钮，应该算是快捷操作，应该是能点的

补充：显然点击详情比点那个编辑按钮也容易的多，并且编辑的概率远超查看详情的概率
补充：详情页增加快速切换到编辑状态的内容也可以

**请描述你建议的实现方案**
干掉详情页 或 详情页 将 保存按钮改为 快速编辑按钮

![image](https://user-images.githubusercontent.com/17382885/95553892-e2411480-0a41-11eb-860d-1da304fa1b37.png)

@wangzhen-fit2cloud

**Comment by xulinde** [comment]
已优化
