### ISSUE TITLE
[BUG]死循环导致服务不可用

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5182]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.1

**Bug 描述**

简要描述您碰到的问题
在场景中，循环控制器中输入无意义的字符，会导致死循环,如果不选择条件则会进入死循环

**Bug 重现步骤**

1.  创建一个场景
2. 添加一个循环控制器
3. 选择while循环模式
4. 随意填写两个无实际意义参数
5. 后台陷入死循环，一段时间，服务无法使用

**期待的正确结果**
提示参数有误
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
已知问题，11.2已修复

**Comment by xulinde** [comment]
v11.2已修复
