### ISSUE TITLE
[BUG]场景步骤无法拖动

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5183]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.1

**Bug 描述**

简要描述您碰到的问题
创建场景，保存好了后，编辑场景时无法将场景步骤进行拖动
**Bug 重现步骤**

1.  创建一个场景
2. 引入多个接口作为场景步骤
3. 点击保存
4. 点击编辑场景，发现无法拖动步骤修改顺序

**期待的正确结果**
能正常拖动步骤修改执行顺序
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
引用的接口无法拖动是已知问题，11.2修复。

**Comment by xulinde** [comment]
v11.2已修复
