### ISSUE TITLE
[BUG]接口自动化批量并行执行，报告一直处于RUNNNING状态

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5184]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.1
**Bug 描述**

简要描述您碰到的问题
将场景进行批量并行执行时，测试报告一直处于running状态
**Bug 重现步骤**

1.  批量选择场景
2. 点击批量执行
3. 选择并行和聚合报告
4. 点击确认，执行，发现测试报告一直处于RUNNNING状态

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="977" alt="截屏2021-08-02 上午10 28 15" src="https://user-images.githubusercontent.com/34637801/127803298-bdbc6f21-e520-47da-9524-8545b6db803f.png">

**Comment by zyyfit** [comment]
您好，这边没有复现呢，方便上传一下脚本文件或者截取一下详细报错信息吗

**Comment by rayshen3** [comment]
v1.12 一样的报错
![image](https://user-images.githubusercontent.com/9734936/132469463-087fb50a-5e76-452c-948a-6cc704e3448f.png)

**Comment by xulinde** [comment]
v1.13已修复
