### ISSUE TITLE
[BUG]场景无法批量迁移

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5185]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.1

**Bug 描述**

简要描述您碰到的问题
场景从测试环境导出后，导入生产环境中发现所有的请求全部变成自定义接口
**Bug 重现步骤**

1.  批量选择测试环境的接口定义后导出，导入生产环境；
2. 批量选择测试环境的接口自动化导出，导入生产环境；
3. 发现生产环境中导入的场景的步骤全部变成自定义请求；
4. 导致引用接口全部失效

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的，如果需要切换环境可以编辑环境信息或者直接引用场景
