### ISSUE TITLE
[BUG]循环控制器无法拖入条件控制器

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5186]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.1
**Bug 描述**

简要描述您碰到的问题
当条件控制器中不存在步骤时，无法将循环控制器拖入条件控制器
**Bug 重现步骤**

1.  创建一个场景
2. 创建一个条件控制器
3. 创建一个循环控制器
4. 将循环控制器拖入条件控制器中，无法拖入

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，我们先排查下问题

**Comment by xulinde** [comment]
v11.2已修复
