### ISSUE TITLE
[FEATURE]接口自动化测试报告展示步骤断言的详情

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5187]
**请描述您的需求或者改进建议.**
由于需要查看大量的场景的接口断言，是否正确，如果从接口case去查看，效率非常低下，接口自动化报告中包含了场景名称但是无法显示脚本断言的详情，希望能提供查看脚本断言的详情，这样工作效率将大幅提升；

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您可以设置场景级别的断言，然后测试报告会展示断言成功数量和总数
![image](https://user-images.githubusercontent.com/64065190/127814227-ebb9bb54-72f9-41bb-9951-50570cdbc92c.png)

**Comment by zyyfit** [comment]
1.15.2会增加这个功能
