### ISSUE TITLE
[FEATURE]JSONpath 断言提供大于和小于功能

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5188]
**请描述您的需求或者改进建议.**

断言 jsonpath 类型，由于jsonpath能获取list，且有.length方法自动算出长度，但无大于和小的比较方法，导致有list结果需断言时依然需要其它方式来进行断言；

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
这种情况建议您使用脚本断言
![image](https://user-images.githubusercontent.com/64065190/127813979-a297b0c6-c483-49ec-b33f-a3c7dbd1e181.png)

**Comment by xulinde** [comment]
v11.2已支持
