### ISSUE TITLE
[FEATURE]希望内置 markdown功能，用于存储性能测试计划等文档。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#5189]
**请描述您的需求或者改进建议.**

每个项目都有各种文档，如功能测试计划，性能测试计划，接口测试计划，这些文档需要归档。

**请描述你建议的实现方案**
希望能够 内置一个 markdown的编辑器，把项目文档，都保存在每个项目里面，这样更好。

**Comment by zhangzhaox** [comment]
性能测试部分希望有记录 性能测试需求调研  和性能测试计划 的地方   一站式追溯性能测试过程

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个建议很好，但是目前还是会聚焦在测试能力方面，短期都不会规划这个功能。
