### ISSUE TITLE
[FEATURE]测试报告页面，建议增加批量删除测试报告功能

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#519]
**请描述您的需求或者改进建议.**测试报告页面，建议增加批量删除测试报告功能
![image](https://user-images.githubusercontent.com/69206282/95554445-c5591100-0a42-11eb-9191-1f474e947ac4.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/95558645-271c7980-0a49-11eb-95a3-95a7527bca2e.png)
你好，在最新发布的 1.3 版本中，可以通过如图方式批量删除报告
