### ISSUE TITLE
[BUG]Xmind导入用例 弹框提示导入成功，MS用例管理页面并未展示导入的用例

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#520]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3
**Bug 描述**
简要描述您碰到的问题
Xmind导入用例 弹框提示导入成功，MS用例管理页面并未展示导入的用例
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
未能复现这个问题，如果方便请把您使用的 xmind 模版给我发一份；
您这种问题可能由于以下原因导致：
1，xmind 是否有版本问题，目前支持xmind 8 以上 及 zen 版
2，xmind 模版内容可能是空的或者是不符合导入规范的，这个问题已经修复
3，未知的缺陷导致
