### ISSUE TITLE
[FEATURE]在测试报告明细里，除了有下载功能，能否提供发送功能。点击发送，可以直接把该报告通过邮件的形式发送给其他人，而不是先下载然后在发送，从而提高效率。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5214]
**请描述您的需求或者改进建议.**

[FEATURE]在测试报告明细里，除了有下载功能，能否提供发送功能。点击发送，可以直接把该报告通过邮件的形式发送给其他人，而不是先下载然后在发送，从而提高效率。
目前只能定时任务产生的报告是可以发邮件的。 但是手动的，或者是测试跟踪里 的测试报告，只能先下载，然后在发送特别麻烦。
能否减少测试人员的操作和提高测试效率，在测试报告明细页面，提供一个发送的功能。发送邮件就行。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
已在后续版本规划中
