### ISSUE TITLE
[FEATURE]缺陷明细页面地址中支持带有缺陷id，或者提供分享功能。这样就比较方便快捷的把缺陷分享给其他人

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5216]
**请描述您的需求或者改进建议.**

[FEATURE]缺陷明细页面地址中支持带有缺陷id，或者提供分享功能。这样就比较方便快捷的把缺陷分享给其他人

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈
