### ISSUE TITLE
[FEATURE]在平台上是否考虑 提测信息管理。比如由研发人员填写提测的相关信息，测试人员可以根据提测内容，启动自动化测试。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5217]
**请描述您的需求或者改进建议.**

[FEATURE]在平台上是否考虑 提测信息管理。比如由研发人员填写提测的相关信息，测试人员可以根据提测内容，启动自动化测试。
**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前接口测试这块已经支持。研发人员把已经开发完成的接口导入，测试人员根据接口定义编写接口用例，然后把用例组合成自动化场景，进行测试

**Comment by huangxine** [comment]
比如一下场景：第一种：研发也使用该平台进行接口调试，所以在提测前，接口都是要同步到ms系统的；第二种，本次需求只是修改了部分接口的逻辑或者其他信息，这些接口是需要测试的，这些接口都是已经存在ms系统里。还有很多类似的业务场景。
另外提测信息除了包含接口等信息，一般还包含关联的需求、数据库、研发建议的复测流程、备注等等。
