### ISSUE TITLE
[BUG]【UI】全局变量处的名称显示有重叠

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#524]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.0

**Bug 描述**
全局变量显示遮挡

**截图**
![image](https://user-images.githubusercontent.com/13564069/95641557-b40d1480-0ad5-11eb-81f5-7ed167c424a2.png)

**Comment by fit2-zhao** [comment]
已修复该缺陷
