### ISSUE TITLE
[BUG]测试计划里运行的场景用例，获取的数据库配置不应该是“接口测试-接口自动化”对应场景用例环境配置里的数据库配置

### ISSUE THREAD

**Issue by wj395318624** [metersphere/metersphere#5254]
**MeterSphere 版本**
v1.11.0-4118f8c7

**Bug 描述**
测试计划里运行的场景用例，获取的数据库配置不应该是“接口测试-接口自动化”对应场景用例环境配置里的数据库配置

**Bug 重现步骤**

1.  有环境配置A和环境配置B，A和B的数据库配置除密码外完全一致（A为正确密码，B为错误密码）
2. 接口测试-接口自动化里，场景用例的环境配置为A，保存用例。
3. 测试计划关联此场景用例，环境配置为A。
4. 在测试计划里运行此场景用例（用例里有接口去连接PG数据库），运行成功
5. 接口测试-接口自动化里，切换场景用例的环境配置为B并保存用例。
6. 在测试计划里运行此场景用例（测试计划里的环境配置不变，还是环境A），连接数据库失败，报错数据库密码错误（FATAL: password authentication failed for user "xxx")）

**期待的正确结果**
6.测试计划里运行的场景用例，获取的是环境A的数据库配置，连接数据库成功
**截图**

如果有截图，请附上截图.

**Comment by wj395318624** [comment]
有环境配置A和环境配置B，A和B的数据库配置除密码外完全一致（A为正确密码，B为错误密码）

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
