### ISSUE TITLE
[QUESTION]请问场景变量怎么在前后/置脚本中使用呢「用的beanShell」

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5259]
**请描述您的问题.**
研究了一天发现不会控制器中使用场景变量，按照推理场景变量应该是全局/局部变量，应该可以正常引用才对🤔，
不知道是不是方向错了，还请大佬帮忙
请问场景变量怎么在前后/置脚本中使用呢「用的beanShell」？

**Comment by zyyfit** [comment]
正常的引用就可以了 ${变量名}
