### ISSUE TITLE
[QUESTION]按照项目启动说明的那一行命令进行启动的时候报错

### ISSUE THREAD

**Issue by littlelilyjiang** [metersphere/metersphere#526]
**请描述您的问题.**
按照快速开始的步骤进行部署
执行完了curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh命令后 查看容器内日志发现有报错
![image](https://user-images.githubusercontent.com/21242743/95647302-ec761800-0b00-11eb-9b26-f399953897e9.png)

registry.cn-qingdao.aliyuncs.com/metersphere/ms-data-streaming:v1.3.0
registry.cn-qingdao.aliyuncs.com/metersphere/metersphere:v1.3.0  
registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.3.0
这三个镜像都提示这些日志文件找不到  但是我手动添加了并且给了777的权限也依然不能找到

**Comment by wangzhen-fit2cloud** [comment]
请问你的操作系统版本是什么？

**Comment by littlelilyjiang** [comment]
您好 操作系统是
CentOS Linux release 7.8.2003 (Core)

**Comment by wangzhen-fit2cloud** [comment]
请检查下 selinux 的状态，如果是开启状态，请尝试关掉 selinux 再重启 docker 服务并重启 metersphere 试一下

**Comment by littlelilyjiang** [comment]
selinux关闭之后可以了
感谢~
