### ISSUE TITLE
[FEATURE] 建议平台和teambution打通，这样平台就可以从teambution上拉取需求和同步bug

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5263]
**请描述您的需求或者改进建议.**

 建议平台和teambution打通，这样平台就可以从teambution上拉取需求和同步bug

**请描述你建议的实现方案**
 建议平台和teambution打通，这样平台就可以从teambution上拉取需求和同步bug

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by nevertokeep** [comment]
我们也是用的teambition，希望可以同步缺陷或者用例
