### ISSUE TITLE
[FEATURE][接口测试]-[接口自动化]-[接口列表导入]-[case]搜索功能建议添加API路径搜索条件

### ISSUE THREAD

**Issue by muchild** [metersphere/metersphere#5264]
**建议：**
[接口测试]-[接口自动化]接口列表导入-case-搜索，建议添加API路径搜索条件

**原因：**
_当前使用版本：  v1.11.1-0f3be78c_
1、当前[接口测试-][接口自动化]接口列表导入-case-搜索，只支持按id/名称搜索
2、比如一个API接口，包含了30个用例，列表内N个API接口(case名没有包含API接口名)，此时要批量选择case会搜索不到需要的

**Comment by xulinde** [comment]
目前就是支持的
![image](https://user-images.githubusercontent.com/64065190/128279739-ca1565a9-442c-4af2-9799-c0232c1c8b6b.png)

**Comment by muchild** [comment]
> 目前就是支持的
> ![image](https://user-images.githubusercontent.com/64065190/128279739-ca1565a9-442c-4af2-9799-c0232c1c8b6b.png)

你好哦，issue里说的case tab
![image.png](https://i.loli.net/2021/08/06/Bb9nhcHapjTPsZ1.png)
