### ISSUE TITLE
[FEATURE][接口测试]-[接口自动化]-新增/编辑场景case，建议添加批量删除case功能

### ISSUE THREAD

**Issue by muchild** [metersphere/metersphere#5265]
**建议：**
[接口测试]-[接口自动化]-新增/编辑场景case，建议添加批量删除case功能

**原因：**
一个场景里添加了36个case，发现要删除部分或者全部删除，需要手工一个一个操作删除(删除按钮还一不小心就点框外，消失了)，操作异常麻烦，最后只好把场景删除，重新创建

**当前使用版本：**v1.11.1-0f3be78c

**Comment by xulinde** [comment]
感谢您的建议，该功能已在后续版本规划中了
