### ISSUE TITLE
[FEATURE]批量编辑希望增加“标签”字段

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#5267]
**请描述您的需求或者改进建议.**
背景：一部分P0用例希望给开发做冒烟测试，所以希望用标签来把这些用例区分开来，现在没有批量修改标签的功能，就只能一个一个改。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以优化
