### ISSUE TITLE
[BUG]测试用例列表页面，统计的测试用例总数不一致。左侧模块上显示的用例总数和列表中显示的总数不一样。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5268]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试用例列表页面，统计的测试用例总数不一致。左侧模块上显示的用例总数和列表中显示的总数不一样。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/128157554-2985138e-1ad2-47eb-9b46-4efaea7892d6.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是不是有删除用例然后页面没刷新呢？或者方便把您的用例导出来给我们看一下吗？
