### ISSUE TITLE
[BUG]测试计划列表页面，修改‘当前状态’后，列表页面未自动刷新显示

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#527]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.3.0-b842
**Bug 描述**
简要描述您碰到的问题
测试计划列表页面，修改‘当前状态’后，列表页面未自动刷新显示，需要手工刷新后‘实际开始’字段信息才会刷新显示！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
[
![image](https://user-images.githubusercontent.com/54024064/95647648-b8e8bd00-0b03-11eb-8a2f-c18b46596cc7.png)
](url)

**Comment by fit2-zhao** [comment]
问题已经修复
