### ISSUE TITLE
[BUG]metersphere  太耗服务器性能了，自从升到1.10后，  4核8G的很卡，经常挂，java进程损耗CPU太大了，需要优化

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#5282]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

自从升到1.10后，  4核8G的很卡，经常挂，java进程损耗CPU太大了，需要优化

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

降低服务器的资源消耗

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by Evan-guo131** [comment]
解决不了 可以换一个大神
