### ISSUE TITLE
[FEATURE]1.11.1， 接口测试-接口自动化，针对每条接口自动化场景，建议增加注释区域，接口自动化场景一多，根本看不懂啥逻辑。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#5283]
**请描述您的需求或者改进建议.**
1.11.1， 接口测试-接口自动化，针对每条接口自动化场景，建议增加注释区域，接口自动化场景一多，根本看不懂啥逻辑。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，我们会尽快排期
