### ISSUE TITLE
一键安装找不到install.conf 文件，手动安装解压后目录也没这个文件

### ISSUE THREAD

**Issue by longlizl** [metersphere/metersphere#5285]
sh: 第 15 行:cd: metersphere-release-v1.11.1: 没有那个文件或目录
sed：无法读取 install.conf：没有那个文件或目录
sed：无法读取 install.conf：没有那个文件或目录
/bin/bash: install.sh: 没有那个文件或目录

**Comment by xulinde** [comment]
使用最新版本还有此问题吗
