### ISSUE TITLE
[BUG]1.11.1 系统创建账号和LDAP渠道的账号，删除其中一方，另一方都无法正常使用。账号体系是否有问题。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#5295]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.11.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
1， 我在系统中人肉创建一个人叫张三，存在一个张三账号。
2，张三通过LADP方式登录系统，又存在一个张三的账号。
3， 我搜索张三，删除张三账号。
4， 无论是人肉创建的张三 还是LADP渠道来的张三，都无法继续使用，包括系统人肉创建张三，还是LADP渠道再次进来的张三。

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前ldap用户和已有用户id一致，不会在本地新建用户，还是原来的那个本地用户

但是我测试了一下，删除本地用户后LDAP用户还是可以正常登录的，请问您具体是怎么操作的呢？
