### ISSUE TITLE
[FEATURE]接口定义输入框较小，编辑比较长的json内容时操作困难，希望能弹出单独文本框呈现所有文本并编辑

### ISSUE THREAD

**Issue by wkj002** [metersphere/metersphere#5296]
**请描述您的需求或者改进建议.**
接口定义输入框编辑json（较长）参数操作困难

**请描述你建议的实现方案**
希望能弹出单独文本框呈现所有文本并编辑
![捕获123](https://user-images.githubusercontent.com/16718309/128328783-7d2f95de-6605-4017-ae49-d4254e9fd6b3.PNG)

**Comment by xulinde** [comment]
感谢您的建议，后面可以考虑优化下
