### ISSUE TITLE
[BUG] 【接口测试】多次转义后的入参，参数化变量后发送请求，请求体中的入参 json 没有正确转义，导致接口请求失败

### ISSUE THREAD

**Issue by jhong123** [metersphere/metersphere#5297]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  常规请求接口，接口入参多次转义
2. 参数化其中一个入参
3. 发送请求，检查请求结果
4. 

**期待的正确结果**

正确情况下应该是什么样的？
请求成功。

**截图**

如果有截图，请附上截图.

请求入参：
{
    "name": "",
    "params": "{\"cmd\":\"echo \\\"123\\\"\"}",
    "workspaceId":"35"
}

请求：
![image](https://user-images.githubusercontent.com/11580681/128330045-4fe85573-5036-4fba-8dfb-d7ef4c76d61a.png)

参数化之前，发送的请求入参是正确的：

![image](https://user-images.githubusercontent.com/11580681/128330686-37537582-7c45-4b91-9049-02869d4d4f3a.png)

将 workspaceId 参数化之后，发送的请求入参 json 不合法，导致请求失败：
![image](https://user-images.githubusercontent.com/11580681/128328126-e0379174-5d5d-4da1-aed0-badb2e7803ce.png)

json 错误如下：
![image](https://user-images.githubusercontent.com/11580681/128328907-cb0bdf8a-9fad-42ce-bcbc-88731007315b.png)

**Comment by xulinde** [comment]
请输入准确json，示例中的json本身是错误的
输入时平台有提示，按照提示修改。

**Comment by xulinde** [comment]
jmeter 目前处理机制就是这样
