### ISSUE TITLE
[BUG]修改密码的页面多次打开，页面上的内容没有刷新

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#53]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？版本: v1.0.2-b357

**Bug 描述**
多次打开密码修改的页面，上次修改的页面内容没有被刷新

**Bug 重现步骤**
1.  打开修改密码页面，尝试输入旧密码，关闭页面
2. 再次打开修改密码页面，上次输入的密码仍然存在
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
刷新页面，每次进去都是新的页面

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/86090449-af9b8d80-badc-11ea-902f-1e07fff5d8a8.png)

**Comment by AgAngle** [comment]
v1.0.3版本已修复
