### ISSUE TITLE
[FEATURE]后期有规划对接postman和swagger导入json格式接口吗？

### ISSUE THREAD

**Issue by ratel-liu** [metersphere/metersphere#530]
**请描述您的需求或者改进建议.**
希望能直接从postman已有的脚本或swagger的json导入到平台进行接口测试。同时还能把接口进行管理。

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，如图所示现在可以导入 postman 和 swagger 格式的接口。接口管理的相关功能正在规划中
![image](https://user-images.githubusercontent.com/27671436/95649275-55648c80-0b0f-11eb-9be4-0972c7aff6b8.png)
![image](https://user-images.githubusercontent.com/27671436/95649284-5b5a6d80-0b0f-11eb-8b3e-a9983aff65e8.png)

**Comment by ratel-liu** [comment]
真棒！
