### ISSUE TITLE
[BUG]新建用例时提示维护人字段过长

### ISSUE THREAD

**Issue by caichangchun** [metersphere/metersphere#531]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.3.0-b842

**Bug 描述**
测试跟踪-测试用例，新建用例
保存时数据库报错，原因是因为维护人字段太长

**截图**
<img width="1029" alt="WechatIMG20" src="https://user-images.githubusercontent.com/26024107/95651700-acbe2900-0b1e-11eb-8908-03cda8219533.png">

**Comment by liuruibin** [comment]
会在下一个小版本中修复
