### ISSUE TITLE
[FEATURE]环境域名配置:443保存会自动去掉：443

### ISSUE THREAD

**Issue by shiyanan0915** [metersphere/metersphere#532]
**请描述您的需求或者改进建议.**
1.环境域名配置:443保存会自动去掉：443，我们的接口域名必现配置，不然会报错，希望能修改
2.接口结果查看，左边的所有接口结果和右边的单个接口详细结果，滑动鼠标时，应该分开，不然每次都要重新在左测找接口

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.10测试无该问题，建议您升级到最新版本在试下
