### ISSUE TITLE
[BUG] 平台上提交的缺陷，在禅道上不换行显示

### ISSUE THREAD

**Issue by mxw0201** [metersphere/metersphere#5324]
**MeterSphere 版本**
v1.10.5
禅道版本：12.5.3
**Bug 描述**
1、项目关联禅道系统
2、平台上提交缺陷，缺陷内容存在换行
3、提交后禅道系统上查看该缺陷，内容都显示在同一行，没有换行显示
![image](https://user-images.githubusercontent.com/52606874/128453417-3602265e-7e26-428d-96fb-60b68b8b6f8d.jpg)
![image](https://user-images.githubusercontent.com/52606874/128453435-bc729908-fdeb-4246-bcec-cf4d984f91d2.jpg)

**Comment by xulinde** [comment]
v11.2已修复
