### ISSUE TITLE
[BUG]测试跟踪首页统计用例总数与当前拥有的测试用例数不一致，新增测试用例总数会新增，删除却不会减少。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5330]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1版本

**Bug 描述**

测试跟踪首页统计用例总数与当前拥有的测试用例数不一致，新增测试用例总数会会新增，删除却不会减少。

**Bug 重现步骤**

1.  新增测试用例总数会新增，删除却不会减少。
2. 
3. 
4. 

**期待的正确结果**

测试跟踪首页统计用例总数与当前拥有的测试用例数一致

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，下个版本会修复

**Comment by xulinde** [comment]
v11.3已修复
