### ISSUE TITLE
[BUG]定时任务稍微多一点（13个大概 ），MS就会经常出现连不上数据库的问题。建议优化一下。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5331]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

定时任务稍微多一点（13个大概 ），MS就会经常出现连不上数据库的问题。建议优化一下。好像是定时任务没有释放数据库连接的问题。

**Bug 重现步骤**

1.  定时任务稍微多一点（13个大概 ），MS就会经常出现连不上数据库的问题。建议优化一下。
2. 
3. 
4. 

**期待的正确结果**

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
定时任务设置的间隔时间是多久呢

**Comment by xulinde** [comment]
这个问题11.2优化过了，您可以升级到最新版本在看下

**Comment by liuhansong** [comment]
好的

**Comment by xulinde** [comment]
v10.8也已优化
