### ISSUE TITLE
并发用户数100 提示并发数超额

### ISSUE THREAD

**Issue by itlidaye** [metersphere/metersphere#534]
并发用户数100 提示并发数超额

**Comment by itlidaye** [comment]
@wangzhen-fit2cloud @fit2cloudrd

**Comment by wangzhen-fit2cloud** [comment]
你好，可以在系统设置的测试资源池中配置支持的并发上限
![image](https://user-images.githubusercontent.com/27671436/95822740-12005d00-0d5f-11eb-8da9-89752f757386.png)
