### ISSUE TITLE
[FEATURE]postman接口导入MS，post接口会多出来一个请求头，建议优化。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5341]
**请描述您的需求或者改进建议.**
postman接口导入MS，post接口会多出来一个请求头（Content-Type），建议优化。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
请求体是json格式吗，json格式会自动添加Content-Type请求头

**Comment by liuhansong** [comment]
发自我的华为手机是json格式-------- 原始邮件 --------发件人： xulinde ***@***.***>日期： 2021年8月6日周五 17:47收件人： metersphere/metersphere ***@***.***>抄送： liuhansong ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [FEATURE]postman接口导入MS，post接口会多出来一个请求头，建议优化。 (#5341)

请求体是json格式吗，json格式会自动添加Content-Type请求头
