### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by kelay1984** [metersphere/metersphere#5343]
**请描述您的需求或者改进建议.**

接口框架设置了自定义异常，场景自动化测试的时候，需要添加断言 判断接口返回的code来决定是否成功，而不是httpcode是200，每个接口都增加同一个断言比较麻烦。

**请描述你建议的实现方案**
系统有个场景的通用断言来解决这个问题。

**Comment by xulinde** [comment]
目前是支持场景级别断言的，您可以先在一个请求里添加断言，然后拖到场景中，就是场景断言了
