### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by cuixinzhou** [metersphere/metersphere#5346]
您好：
安装好之后性能测试jmter会报这个错误 请问如何解决
Error filtering class com.google.common.collect.MapMakerInternalMap$WeakValueReferenceImpl, it will be ignored java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]

**Comment by xulinde** [comment]
使用最新版本还有此问题吗
