### ISSUE TITLE
[FEATURE]把测试用例上的标签也显示在测试评审列表中，方便去查找需求

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5349]
**请描述您的需求或者改进建议.**
把测试用例上的标签也显示在测试评审列表中，评审的时候就可以根据这个去jira上找到相应的需求了

![WechatIMG352](https://user-images.githubusercontent.com/32027713/128659547-5c3ad579-f1ed-467d-b1b7-cf8df49bbdb9.png)

下面的列表中，加一列内容

![WechatIMG353](https://user-images.githubusercontent.com/32027713/128659552-7ffc272e-af41-4b7a-8330-acc9eeadd046.jpeg)

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个优化我们计划在v2.8版本支持。
