### ISSUE TITLE
[BUG] 场景中调试TCP接口及生成报告，不显示接口返回内容，无法查看

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#5351]
**MeterSphere 版本**
>v1.11.2

**Bug 描述**

场景中引用或者复制TCP接口，在调试及生成报告两个选项中，不显示接口返回内容，无法查看调试结果

**Bug 重现步骤**

1.  

**期待的正确结果**

与http接口一致，展示返回内容

**Comment by tangw-github** [comment]
![d78bcdb84b7c9e387185af226368065](https://user-images.githubusercontent.com/8164903/128690876-4c3a2f37-ec2f-4302-a094-313528ce95eb.jpg)

**Comment by tangw-github** [comment]
请问这个缺陷能修改吗？有没有排期？

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，您可以升级看看
