### ISSUE TITLE
[FEATURE] 缺陷管理增加根据缺陷状态筛选和根据处理人筛选

### ISSUE THREAD

**Issue by 18378333917** [metersphere/metersphere#5356]
**请描述您的需求或者改进建议.**

目前缺陷管理缺少缺陷状态筛选功能，开发和测试要查找未关闭的缺陷很麻烦，随着缺陷越来越多，经常要漏掉一些未关闭的缺陷。还有缺陷管理不能根据处理人进行筛选，对应的开发也很难找到自己所负责的缺陷，使用起来很不方便。希望能增加缺陷状态的筛选和根据处理人进行筛选

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/7194694/128681009-0030477e-4d41-4f99-b4b7-b2312c45e1ec.png)

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以支持

**Comment by Evan-guo131** [comment]
这个FEATURE计划什么时候处理
