### ISSUE TITLE
[FEATURE]缺陷管理增加快速修改的缺陷的状态的入口

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5363]
**请描述您的需求或者改进建议.**
需求：缺陷管理增加快速修改的缺陷的状态的入口
需求源：当缺陷修复后需要进入缺陷页面一个个修改耗时耗力，最好是有一个快捷的修改状态入口以便能够修改对应的缺陷状态
![image](https://user-images.githubusercontent.com/44960709/128709922-5ea97397-d6f0-4f56-b7f4-57f53a47bfa3.png)

**请描述你建议的实现方案**
在缺陷管理增加快速修改的缺陷的状态的入口
![image](https://user-images.githubusercontent.com/44960709/128710181-57bebc6a-05cc-4a7c-989e-daf2cedb519c.png)

**Comment by xulinde** [comment]
目前可以同步第三方平台的状态，local的不支持同步
