### ISSUE TITLE
[BUG]导入接口定义MeterSphere.json无法修改case参数

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5364]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2
**Bug 描述**

简要描述您碰到的问题
导出接口定义的MeterSphere.json文件，修改接口定义和case的部分参数，采用覆盖的模式重新导入到对应的模块中时，只有接口定义的参数进行了修改，case的参数未进行修改，给批量修改参数带来较大麻烦（如批量修改用户验证信息为引用的参数）
**Bug 重现步骤**

1.  导出某模块部分已创建case的接口定义；
2. 修改MeterSphere.json文件中接口定义和case的部分参数
3. 选择对应的模块和覆盖模式导入

**期待的正确结果**
接口定义的case的对应的参数也会进行相应的修改（目前只会修改接口定义中的参数）
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
v1.11.3 已解决
