### ISSUE TITLE
[FEATURE]左侧用例模块，浮框显示全名

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#5367]
**请描述您的需求或者改进建议.**
模块层级太深且名称比较长时，会显示不全，需要拖拽界面分割框。建议鼠标挪到用例模块文件夹上，浮标提示文件夹的全名

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以优化下

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
