### ISSUE TITLE
[QUESTION]怎么没有卸载命令？

### ISSUE THREAD

**Issue by cikichen** [metersphere/metersphere#5368]
**请描述您的问题.**
安装后发现机器性能不行，想卸载，发现没有相关文档

**Comment by dashenyucainiao** [comment]
msctl uninstall -v

具体命令查看如下：

![WechatIMG155](https://user-images.githubusercontent.com/32027713/128820378-fc4b512f-ae32-4386-916a-8b558cc000de.png)
