### ISSUE TITLE
[FEATURE]在接口下的case及场景测试下添加 前置SQL或者后置SQL，无法看到执行结果

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5369]
**请描述您的需求或者改进建议.**

在接口下的case及场景测试下添加 前置SQL或者后置SQL，无法看到执行结果，希望可以显示其执行结果，以便进行参数利用赋值等操作

<img width="1148" alt="WechatIMG154" src="https://user-images.githubusercontent.com/32027713/128819875-18702edc-0681-45cd-b5af-92f985ccdee8.png">

**Comment by xulinde** [comment]
感谢您的建议，后续版本可以优化

**Comment by xulinde** [comment]
可以在后置脚本里，log.info();
