### ISSUE TITLE
[BUG]循环控制器的计数没有从0开始，出现两个1

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5370]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
![image](https://user-images.githubusercontent.com/44960709/128823462-c90e9d67-e3d3-4051-852e-53df4b17cb84.png)

**Bug 描述**

简要描述您碰到的问题
循环控制器的计数没有从0开始，出现两个1
**Bug 重现步骤**

1.  建一个循环计数器
2. 运行结果能看见的
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
从0开始
**截图**
![image](https://user-images.githubusercontent.com/44960709/128823348-f601f0da-c58b-4b60-a1ec-3fb2a2477f01.png)

![image](https://user-images.githubusercontent.com/44960709/128823457-68ed4891-036e-4989-b776-3ea4ba256396.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有理解您说的什么意思，是循环中引用的变量出现了2个1吗？具体是哪种循环呢？（次数？foreach？while?）怎样使用的循环呢？

**Comment by lingrance** [comment]
foreach？

> 您好，没有理解您说的什么意思，是循环中引用的变量出现了2个1吗？具体是哪种循环呢？（次数？foreach？while?）怎样使用的循环呢？

运行结果应该是从0 开始的吧？是次数循环

**Comment by zyyfit** [comment]
最新版已修复
