### ISSUE TITLE
[BUG]接口case断言名称不显示

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5375]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2
**Bug 描述**
接口case断言编写了名字，但执行时只显示断言规则，不显示断言名称
简要描述您碰到的问题

**Bug 重现步骤**

1.  接口case中添加一个断言
2. 选择JSONPath的方式进行断言
3. 填好断言名称
4. 执行case

**期待的正确结果**
不仅展示断言规则，同时展示填写的断言名称
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
1.12已支持该功能
