### ISSUE TITLE
[QUESTION]连接mysql5.6报CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by annechn** [metersphere/metersphere#5377]
**请描述您的问题.**
在metersphere的环境变量里添加数据库连接，连接mysql5.6报CLIENT_PLUGIN_AUTH is required，
除了把metersphere的mysql-connector-java版本从8.0改到5.1重新打包部署，还有其他解决方法吗？

**Comment by SnowMastercx** [comment]
想知道这个问题最后是如何解决的呢

**Comment by wangzhen-fit2cloud** [comment]
建议直接使用 MySQL 5.7 版本，其他版本或多或少会存在兼容性问题。

**Comment by SnowMastercx** [comment]
连接mysql 5.7.26也有遇到这种问题，主要数据库得和生产保持一致，有些不能乱升级，看来只能看如何自己打包了
