### ISSUE TITLE
[FEATURE]建议在压测报告中添加响应时间的TP999和TP9999统计数据

### ISSUE THREAD

**Issue by huangliqiao** [metersphere/metersphere#5379]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/26709150/128960180-6d602379-a558-4c3e-8b72-52970b83e15f.png)

如上图，当前响应时间统计最高只计算到99，一般来说企业级的服务可用率要求都在999甚至9999以上，故建议添加999和9999的统计值

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
