### ISSUE TITLE
[FEATURE] 针对错误场景测试的测试结果问题

### ISSUE THREAD

**Issue by MignonZhang** [metersphere/metersphere#538]
**请描述您的需求或者改进建议.**
针对错误场景的测试，测试结果是失败
比如说登陆功能，测试正常登陆和密码错误登陆2中情况，密码错误时虽然接口返回的状态码不是200，但是对于这个测试场景来说，我们期望的返回值确实不是200，并且返回状态码和返回信息与预期一致时，这个用例应该算是测试通过（否则就无法判断是接口本身有问题还是异常场景测试了）

**请描述你建议的实现方案**
针对错误场景的测试，返回结果与预期一致时，测试结果应该是通过
可参考JMeter（预期状态码不是200时，可勾选一个忽略状态码的选项）或者postman

**Comment by zyyfit** [comment]
已优化此功能
