### ISSUE TITLE
[BUG]接口参数值为文件时，运行系统报错，提示有空指针

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5380]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？V1.11

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  参数类型为jmeter里面的上传文件时的MIME类型的参数
2. 在MS系统使用formdata 参数选择文件类型
3. 运行时，系统报错，查看日志是有空指针，这里是不是有bug
4. 错误日志如下：
【黄新娥:
[图片]

黄新娥:
2021-08-11 14:44:28,944 [qtp74783955-17982] WARN  org.eclipse.jetty.server.HttpChannel 677 - /api/definition/run
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
】

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/78218624/128993079-18ea48cc-9731-4cf4-86d4-517ff96ee1ee.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请检查一下是否是参数类型填写错误呢？请求头里不需要填写参数类型，请求体里上传文件的参数需要填写一个application/octet-stream的参数类型，但是一般系统会自己生成的
![image](https://user-images.githubusercontent.com/73461316/129064457-3f0b06d4-5de6-4b2a-ab00-7a54c9f8674d.png)

**Comment by huangxine** [comment]
此值使用的是系统默认的：application/octet-stream； 这个是否要修改？如何修改？上传的文件为excel文件。

（更正一下：系统版本是1.10.6版本）
![易车1](https://user-images.githubusercontent.com/78218624/129326287-8f935e8d-087a-450a-8178-d10e053acdf2.png)
![易车2](https://user-images.githubusercontent.com/78218624/129326300-a9b5a6f9-226e-4924-ab57-3dfb499c3c05.png)

**Comment by xulinde** [comment]
v1.12未复现该问题
