### ISSUE TITLE
[FEATURE]测试计划定时任务缺少单条测试结果告警

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5382]
**请描述您的需求或者改进建议.**

测试计划设置了告警条件，在执行的过程中，每次发送告警都是在定时任务周期的时间点发送告警，无法实时发送通知，建议在测试执行过程中，当某个测试项执行失败时，实时发送该项测试的通知；

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这种可以在接口测试配置执行失败的消息通知。
