### ISSUE TITLE
[FEATURE]测试报告提供测试执行结束时间的列

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5383]
**请描述您的需求或者改进建议.**

测试计划测试报告、接口自动化测试报告，只有创建时间，没有整个测试执行结束的时间，这样不便于判断测试计划和接口测试、接口自动化测试，执行时长是多久，对于列如证券行业，对测试时间比较敏感的行业，使用不便

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以优化

**Comment by xulinde** [comment]
v1.12已优化
