### ISSUE TITLE
[FEATURE] Jenkins的job跑的接口自动化的报告链接，希望不需要登录就能查看

### ISSUE THREAD

**Issue by 462548187** [metersphere/metersphere#5384]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
v1.12会支持

**Comment by 462548187** [comment]
> v1.12会支持

未支持，目前Jenkins运行结束后，仍然需要登录才能查看结果

**Comment by xulinde** [comment]
v1.13 xpack已支持该功能。直接在模板添加变量 ${planShareUrl} , 就可以使用分享链接
