### ISSUE TITLE
是否支持针对单个接口创建性能测试

### ISSUE THREAD

**Issue by itlidaye** [metersphere/metersphere#539]
目前只看到针对场景创建性能测试，如何针对单个接口创建性能测试

**Comment by itlidaye** [comment]
@wangzhen-fit2cloud

**Comment by wangzhen-fit2cloud** [comment]
你好，目前没有完全针对单接口的功能提供，但是在场景中只添加一个 HTTP 请求效果上是一样的

**Comment by itlidaye** [comment]
希望未来能够提供这个功能，swagger 批量导入的比较有用
