### ISSUE TITLE
[QUESTION]本地windows环境怎么跑起来node-controller代码

### ISSUE THREAD

**Issue by LittleJZ** [metersphere/metersphere#5392]
你好，想在本地win10环境下调试性能测试模块，资源池节点也想使用本地的节点，怎么在本地启动node-controller.
谢谢

**Comment by wangzhen-fit2cloud** [comment]
你好，windows 启动需要修改启动 JMeter 容器相关代码。

**Comment by huhui** [comment]
1、首先win10上安装Desktop Docker
2、右键窗口右下角Docker图标进入设置，勾选settings->General->Expose daemon on tcp://localhost:2375 without TLS
3、下载jmeter-image代码，然后自己打镜像；或者使用已经打好的镜像，使用docker import命令导入即可
4、下载node-controller代码，idea打开
5、修改DockerClientService.java连接docker代码如下
` public static DockerClient connectDocker() {
        return DockerClientBuilder.getInstance("tcp://localhost:2375").build();
    }`
6、修改Applicatiion主程序metersphere.properties路径
7、启动即可
