### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by echo1024** [metersphere/metersphere#5393]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
metersphere-release-v1.11.1
**Bug 描述**

创建缺陷时提示
“400 Bad Request: [{"errorMessages":[],"errors":{"issuetype":"选择的事务类型无效。"}}]”

**Bug 重现步骤**

1.  admin 登陆系统--服务集成。
2. 选择jira。配置账号，auth相关信息，直到测试成功。如图
![jira_conf](https://user-images.githubusercontent.com/19204311/129132179-b773468a-52ec-45bc-9466-af2a6d931c93.png)
3. 登陆项目管理员权限---进入系统设置---项目管理---编辑项目---选择jira中可以提交缺陷项目的key。
如图
![project_conf](https://user-images.githubusercontent.com/19204311/129133339-38d6f66e-e6d2-4b17-9305-e3ccff128cac.png)

4. 配置完成后进入测试跟踪---缺陷管理---创建缺陷----添加标题，缺陷内容后点击保存后报400
日志如图
![error_log](https://user-images.githubusercontent.com/19204311/129133737-1180046c-82a6-40d8-bcfe-b531bf7098d7.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by echo1024** [comment]
<img width="772" alt="project_comm" src="https://user-images.githubusercontent.com/19204311/129134508-56038196-6439-492a-a77f-2d0e600c77af.png">

**Comment by zyyfit** [comment]
您好，请核对 jira 项目 key 是否正确？如果各项检查都没问题的话您可以进我们的交流群找工作人员远程查看一下

**Comment by echo1024** [comment]
> key
确定是正确的

**Comment by xulinde** [comment]
用最新版本还有此问题吗
