### ISSUE TITLE
[BUG]无法引用前置脚本的内容

### ISSUE THREAD

**Issue by tanxiao133** [metersphere/metersphere#5397]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.1

**Bug 描述**
前置脚本概率性无效，无法将值推入变量中使用（上个版本能够正常使用）

简要描述您碰到的问题
目前是通过前置脚本调用jar包计算签名，计算完成后放入header中，跑case时发现部分请求header中签名值有效，部分请求header中签名依旧为${sign}，查看签名为${sign}的请求的控制台信息，前置脚本计算出了sign值，但是未放入header中

**Bug 重现步骤**

1.  创建一个请求，header引用前置脚本中的内容
2. 复制多个该请求
3. 查看请求内容，部分请求header中内容替换成功，部分请求header中内容并未替换

**期待的正确结果**
全都替换
正确情况下应该是什么样的？
全都替换
**截图**

如果有截图，请附上截图.

一模一样的请求及脚本
![一模一样的请求及脚本](https://user-images.githubusercontent.com/68689218/129155802-faa116ed-0493-44b9-894e-25a8aa26d677.png)

第一个的内容，未引用到sign
![第一个的内容，未引用到sign](https://user-images.githubusercontent.com/68689218/129155820-54e7ff5d-7076-484c-a847-b9fd32f13b52.png)

第二个成功了，引用到了sign
![第二个成功了，引用到了sign](https://user-images.githubusercontent.com/68689218/129155824-20088289-6c3d-40fe-a8f2-be059ddacd0f.png)

**Comment by tanxiao133** [comment]
这个问题非常影响使用，能否看一下呢？

**Comment by tanxiao133** [comment]
提供一些信息~我在前置脚本中计算完了，打印出来确定没问题，但是header中就是无法引用该变量，详细请看图：
![1](https://user-images.githubusercontent.com/68689218/129432055-66016f66-9b73-4732-8fbe-9fd5e0fb27cd.png)
![2](https://user-images.githubusercontent.com/68689218/129432057-52038e71-aa33-456b-8184-115c9ddfff02.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我看11.2已经没有这个问题了，但是如果环境中有设置header的话还是会引用不到，正在解决，您可以先升级11.2使用

**Comment by tanxiao133** [comment]
> 您好，我看11.2已经没有这个问题了，但是如果环境中有设置header的话还是会引用不到，正在解决，您可以先升级11.2使用

是的，讨论了一下，根因是环境中设置了header导致的

**Comment by zyyfit** [comment]
> > 您好，我看11.2已经没有这个问题了，但是如果环境中有设置header的话还是会引用不到，正在解决，您可以先升级11.2使用
> 
> 是的，讨论了一下，根因是环境中设置了header导致的

您好，1.11.3版本已经修复了这个问题，您可以升级到1.11.3使用
