### ISSUE TITLE
[BUG]控制台提供的信息无法对应，一个请求的控制台输出了所有请求的前置脚本的打印信息

### ISSUE THREAD

**Issue by tanxiao133** [metersphere/metersphere#5402]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**

简要描述您碰到的问题
一个请求的控制台输出了所有请求的前置脚本的打印信息，并且上版本控制台可以输出脚本的错误信息，还可以输出jar包的打印内容，这个版本都不输出了。

**Bug 重现步骤**

**期待的正确结果**
单个请求控制台输出单个请求的结果

正确情况下应该是什么样的？

**截图**

![一个请求的控制台打出多个请求脚本中的内容](https://user-images.githubusercontent.com/68689218/129161973-f5d384d4-dff4-441f-b092-5812362a80c7.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，目前控制台无法区分是哪个请求产生的日志，暂时不进行修改
