### ISSUE TITLE
[BUG]一键收起功能概率性无法使用

### ISSUE THREAD

**Issue by tanxiao133** [metersphere/metersphere#5403]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**
上版本一键收起从没出过问题，该版本经常性出现脚本、部分请求无法收起的情况

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
一共多少个场景，多少个步骤呢

**Comment by tanxiao133** [comment]
> 一共多少个场景，多少个步骤呢

更新到1.11.2后没有该问题了
