### ISSUE TITLE
[BUG]在测试跟踪的测试用例列表，选中单个测试用例编辑时，后台有大量的list请求，导致编辑页面加载很慢

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#5408]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.7-lts-b06d5a2f版本，v1.11.2-854acb67版本

**Bug 描述**
在测试跟踪的测试用例列表，选中单个测试用例编辑时，后台有大量的list请求，导致编辑页面加载很慢

简要描述您碰到的问题

**Bug 重现步骤**
步骤如截图所示
1.  
2. 
3. 
4. 

**期待的正确结果**
测试跟踪的测试用例编辑页面能快速打开

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1226" alt="WechatIMG696" src="https://user-images.githubusercontent.com/18387151/129174695-bde057ba-5024-41b3-b914-13d86a0bb192.png">
<img width="934" alt="WechatIMG695" src="https://user-images.githubusercontent.com/18387151/129174827-6f43f661-9013-41e5-bf42-8aa22862263d.png">

**Comment by xulinde** [comment]
已知问题，下个版本会优化

**Comment by xulinde** [comment]
v10.8已优化
