### ISSUE TITLE
[FEATURE]目前接口测试中只有if逻辑判断，希望加上jmeter中的其他判断条件。包含循环等。

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#541]
**请描述您的需求或者改进建议.**
目前接口测试中只有if逻辑判断，希望加上jmeter中的其他判断条件。包含循环等。

**请描述你建议的实现方案**
目前接口测试中只有if逻辑判断，希望加上jmeter中的其他判断条件。包含循环等。

**Comment by xulinde** [comment]
您好，该需求已实现
