### ISSUE TITLE
[BUG]数据源连接不稳定，导致服务不可用

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5410]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2
**Bug 描述**

简要描述您碰到的问题
创建一个测试计划，关联接口或者接口场景，当请求总数超过300时，且执行方式选
择并行，资源池，选择本地资源池，执行一天后，发现后台日志会报java.sql.SQLTransientConnectionException: DatebookHikariCP - Connection is not available, request timed out after 30014ms.
的错误，导致服务不可用；
**Bug 重现步骤**

1.  创建一个测试计划
2. 关联300+接口或者场景
3. 定时任务设定5分钟并行执行一次
4. 

**期待的正确结果**
服务正常
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
已知问题，已经大概找到原因了，下个版本尽快修复

**Comment by xulinde** [comment]
v11.3已修复
