### ISSUE TITLE
[BUG]接口自动化场景变量引用错乱

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5411]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2
**Bug 描述**

简要描述您碰到的问题
当场景采用并发执行时，当多个场景中引用同一个变量时，可能会存在数据引用错误，同时给场景用例维护带来较大的不便
**Bug 重现步骤**

1.  创建多个场景，在场景步骤的后置脚本中生成多个同名的环境变量；
2. 创建一个测试计划，关联全部场景，并制定1分钟高频的并发执行的定时任务
3. 日志中报变量引用错误
4. 

**期待的正确结果**
各场景步骤中获取的变量值正确，建议变量生成时自动加上对应的场景ID
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这个问题暂时不太好解决，我们后续会关注的
相关问题 https://github.com/metersphere/metersphere/issues/2578

**Comment by xulinde** [comment]
v1.12.1已修复
