### ISSUE TITLE
[FEATURE] 不知道有没有兴趣开发出8583相关测试标准

### ISSUE THREAD

**Issue by zzq1314zll** [metersphere/metersphere#5413]
## **请描述您的需求或者改进建议.**
1. 支持8583报文的拼装发送
2. 支持8583报文的解析展示
3. 执行结果可能要数据库校验数据
4. 相同数据但是不同格式发送（一键切换）
.....
## **请描述你建议的实现方案**
1. 支持8583报文的拼装发送
![image](https://user-images.githubusercontent.com/33930711/129295278-faac2b50-3559-46e5-9861-dbd762b169a9.png)
2. 支持8583报文的解析展示
![image](https://user-images.githubusercontent.com/33930711/129295405-86a05d07-228b-4967-b2de-cdc61319440f.png)
 根据不同渠道的规则，去解析拼装报文
![image](https://user-images.githubusercontent.com/33930711/129295459-36e084ab-82ac-479f-abd1-c97b37e1cb91.png)

3. 断言可能需要查询数据库数据做校验
![image](https://user-images.githubusercontent.com/33930711/129294927-539bc601-5399-43bb-9ee6-9ec19fda81d1.png)
有些请求发送成功之后，我可能需要校验数据库表中的数据来确定请求的正确性，在平台增加数据库配置，然后结果可以通过sql脚本查询结果集校验
4. 相同数据但是不同的报文协议发送
![image](https://user-images.githubusercontent.com/33930711/129294754-d6e52671-4cf0-4a6e-90ef-c3b69bd9db76.png)
新建的时候去选择为什么不是发送的时候去选择协议呢，平台提供标准的报文组装

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
企业版支持8583报文，你可以先申请试用看看是否满足需求
