### ISSUE TITLE
[FEATURE]缺陷管理能够筛选负责人，能够按照当前登陆的账号优先显示自己负责的缺陷，能够按照负责人筛选出对应人负责的缺陷

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5414]
**请描述您的需求或者改进建议.**
现在所有的缺陷混在一起，大部分负责人其实上不能很好的找到自己负责的缺陷，有待优化

![image](https://user-images.githubusercontent.com/44960709/129296841-c74b5e1f-6b2c-4dcb-8f3f-59dc8d42a9c8.png)

**请描述你建议的实现方案**
缺陷管理能够筛选负责人，能够按照当前登陆的账号优先显示自己负责的缺陷，能够按照负责人筛选出对应人负责的缺陷

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化下

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
