### ISSUE TITLE
[FEATURE]接口自动化内的控制器能否加上备注或者说明字段，用于标识作用

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5416]
**请描述您的需求或者改进建议.**

接口自动化内的控制器能否加上备注或者说明字段，用于标识作用，方便团队协作是能够明白其具体作用或者业务逻辑

![image](https://user-images.githubusercontent.com/32027713/129309640-3d2bb7ce-f07e-44c0-8c4e-b42cf15b7d6c.png)

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化下

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个建议已经转交给交互同学，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
