### ISSUE TITLE
[FEATURE]测试管理-提交缺陷建议支持创建人、优先级的设置，目前无法设置优先级、创建的bug都是集成的管理员账号

### ISSUE THREAD

**Issue by goodzydxn** [metersphere/metersphere#5417]
**请描述您的需求或者改进建议.**

测试管理-提交缺陷建议支持创建人、优先级的设置

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1.个人信息可以配置自己第三方平台账号，如下图
![image](https://user-images.githubusercontent.com/64065190/129326333-fad950f9-db40-4a55-b2e0-5bb764d634fe.png)
2.优先级可以设置自定义字段，如下图
![image](https://user-images.githubusercontent.com/64065190/129326515-77d4af8c-3e0e-41b6-8eb9-f1c55f5ce6ec.png)

**Comment by goodzydxn** [comment]
谢谢你百忙之中回复我的问题，我还有一个疑问和一个问题
2.优先级可以设置自定义字段，如下图
这个入口在哪里？
我这边点击创建缺陷会提示时间戳问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]测试管理-提交缺陷建议支持创建人、优先级的设置，目前无法设置优先级、创建的bug都是集成的管理员账号 (#5417)





 
1.个人信息可以配置自己第三方平台账号，如下图
 
 2.优先级可以设置自定义字段，如下图
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by goodzydxn** [comment]
谢谢你百忙之中回复我的问题，我还有一个问题



我这边点击创建缺陷会提示时间戳问题




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]测试管理-提交缺陷建议支持创建人、优先级的设置，目前无法设置优先级、创建的bug都是集成的管理员账号 (#5417)





 
1.个人信息可以配置自己第三方平台账号，如下图
 
 2.优先级可以设置自定义字段，如下图
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 谢谢你百忙之中回复我的问题，我还有一个疑问和一个问题 2.优先级可以设置自定义字段，如下图 这个入口在哪里？ 我这边点击创建缺陷会提示时间戳问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年8月13日(星期五) 下午4:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]测试管理-提交缺陷建议支持创建人、优先级的设置，目前无法设置优先级、创建的bug都是集成的管理员账号 (#5417) 1.个人信息可以配置自己第三方平台账号，如下图 2.优先级可以设置自定义字段，如下图 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这个是在系统设置-工作空间-模板  模块下面添加的，时间戳问题具体是什么问题呢
