### ISSUE TITLE
[BUG]接口场景自动化应用csv变量，循环时仅取了第一行数据循环

### ISSUE THREAD

**Issue by goodzydxn** [metersphere/metersphere#5418]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问您使用的是哪种循环方式呢？怎样引用的变量呀？
