### ISSUE TITLE
[FEATURE]提交BUG到jira 缺少附件选择

### ISSUE THREAD

**Issue by ali10180209** [metersphere/metersphere#5419]
**请描述您的需求或者改进建议.**
1、提交BUG到jira 缺少附件选择
2、我在正文内添加得图片，提交到JIRA 并没有用

**请描述你建议的实现方案**
1、增加附件字段 对接jira端附件 或者帮忙瞅瞅 为何正文添加图片不能正常发送请求

**Comment by xulinde** [comment]
“2、我在正文内添加得图片，提交到JIRA 并没有用”，不能正常发送请求，又具体报错日志吗，我这边试了下可以发送图片到jira
![image](https://user-images.githubusercontent.com/64065190/129326868-31b8049d-23c7-478d-8b88-acdecea04c8b.png)
