### ISSUE TITLE
[BUG]v1.10.1升级到v1.11.2，执行性能测试，状态一直是Reporting

### ISSUE THREAD

**Issue by zhangfeilynu** [metersphere/metersphere#5420]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2
**Bug 描述**

v1.10.1升级到v1.11.2，执行性能测试，状态一直是Reporting

**Bug 重现步骤**

1.  共有6台机器（230、121、122、123、124、125），其中230安装模式是allinone，另外5台安装模式是node-controller
2. 目前版本是v1.10.1
3. 将6台机器版本升级到v1.11.2
4. 执行性能测试
[error.log](https://github.com/metersphere/metersphere/files/6980633/error.log)

[zk.log](https://github.com/metersphere/metersphere/files/6980632/zk.log)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，我们没有复现这个问题，然后新版本对性能测试也做了一部分优化，您可以升级到1.13看一下还有没有这个问题
