### ISSUE TITLE
[BUG]导出测试报告的缺陷列表处理人丢失

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5421]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
![image](https://user-images.githubusercontent.com/44960709/129321835-27159af9-3c5b-40af-a905-b174ed592527.png)

**Bug 描述**
导出测试报告的缺陷列表处理人丢失
简要描述您碰到的问题
1、本来有的
![image](https://user-images.githubusercontent.com/44960709/129321739-914cabbc-e1ee-44ff-84f2-a1b62b6e9948.png)
2、导出没有了
![image](https://user-images.githubusercontent.com/44960709/129321231-58e60404-9c08-4f74-bdc4-11b2c749ac12.png)
**Bug 重现步骤**

1.  在执行计划处创建测试报告
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
要有处理人信息
**截图**
![image](https://user-images.githubusercontent.com/44960709/129321955-49a3e6aa-6af0-41fb-8297-6ea1e3624e71.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，1.12.0版本将会重构测试报告，目前新版的测试报告中缺陷列表没有展示处理人，如果您需要查看处理人可以提一个enhancement
