### ISSUE TITLE
建议邮件主题以测试名称显示，邮件内容下方直接贴测试报告内容[FEATURE]

### ISSUE THREAD

**Issue by wuha07456** [metersphere/metersphere#543]
**请描述您的需求或者改进建议.**

建议邮件主题以测试名称显示，邮件内容下方直接贴测试报告内容

**请描述你建议的实现方案**
建议邮件主题以测试名称显示，邮件内容下方直接贴测试报告内容

**Comment by wuha07456** [comment]
邮件里链接跳转页面不是报告页面

**Comment by chujidiy** [comment]
本人也提一下这个建议：希望能发送的邮件中，展示报告的内容。

**Comment by xulinde** [comment]
感谢反馈，已在后续版本规划中
