### ISSUE TITLE
[FEATURE]导入用例支持xmind ，导出用例希望也能支持xmind 

### ISSUE THREAD

**Issue by zyan112** [metersphere/metersphere#5437]
**请描述您的需求或者改进建议.**
导出用例希望也能支持xmind 

**请描述你建议的实现方案**
因为导入用例支持xmind ，所以导出用例希望也能支持xmind

**Comment by xulinde** [comment]
v1.12会支持

**Comment by xulinde** [comment]
1.12已支持该功能
