### ISSUE TITLE
接口自动化中上传文件接口调用失败

### ISSUE THREAD

**Issue by verna111** [metersphere/metersphere#5438]
接口自动化中，上传文件接口调用失败，报错。postman测试可成功调通。
沟通确认为bug![011](https://user-images.githubusercontent.com/71637053/129536648-7d9307f9-af69-45d1-9c31-e2e55f8a59ce.png)
![010](https://user-images.githubusercontent.com/71637053/129536646-d1c40e4b-59db-4534-aa02-d83e95d4658c.png)
![014](https://user-images.githubusercontent.com/71637053/129536992-2dd7d614-6470-4e8d-8306-d67bd9f039c6.jpg)

**Comment by zyyfit** [comment]
您好，您这个地址里有变量，在场景或者环境中这个变量能取到这个变量值吗？如果取不到的话，是这个请求地址有问题
