### ISSUE TITLE
[BUG] 通过复制修改新增的接口，保存后的接口url错误

### ISSUE THREAD

**Issue by dengying721** [metersphere/metersphere#5441]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.11.2

**Bug 描述**

已经存在接口A，通过复制A进行修改，新增了接口B，此时接口B在数据库中存放的url仍然是A的，不是B里新修改的

**Bug 重现步骤**

1.  通过手工或者录制的方式，新增接口A
2. 复制接口A，修改地址和请求参数后，保存为接口B
3. 将B的case添加到场景中运行，发现B请求的地址是A接口的，而不是B接口的 

**期待的正确结果**

通过复制新增的接口，和原来接口不应该有关系。

**截图**
下图中，通过复制新增生成的接口，path的值和url的值不匹配，导致执行用例的时候，无法执行path路径的请求。
且通过系统操作无法查看和修改该url，只能改数据库。

![image](https://user-images.githubusercontent.com/17683756/129651646-aefbcd90-4631-4c24-8eb8-efc70b267ab1.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问您是修改接口B的路径之前创建的case还是修改接口B的路径之后呢？如果先创建了case，再修改接口信息的话，case的信息是不会跟着接口信息变更的
