### ISSUE TITLE
[BUG] case和接口中设置的超时时间无效，仍然是默认6秒超时。

### ISSUE THREAD

**Issue by dengying721** [metersphere/metersphere#5442]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

v1.11.2

**Bug 描述**

case和接口中设置的超时时间无效，仍然是默认6秒超时。

**Bug 重现步骤**

1.  在接口和用例的超时配置中，设置超时时间60000ms
2.  在场景中执行该接口，发现超过6000ms就报超时错误。超时时间设置无效。

**期待的正确结果**

超时时间配置有效。

**截图**

![image](https://user-images.githubusercontent.com/17683756/129654207-49c7c8fe-7a57-4dd2-bb41-1bc4b7e755ac.png)

**Comment by xulinde** [comment]
使用最新版本还有此问题吗
