### ISSUE TITLE
[FEATURE]优化swagger手动导入接口方式

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#5443]
**请描述您的需求或者改进建议.**
目前手动同步swagger接口，需要选择“更多操作>导入>swagger>勾选swagger导入>配置swagger url>点击保存”才能进行手动同步。
建议优化手动同步swagger步骤，减少繁琐操作。

**请描述你建议的实现方案**
比如在“更多操作>定时同步（可改名为swagger同步）”页面中添加手动同步按钮。

**Comment by xulinde** [comment]
您用的是哪个版本，这里已经优化过了
![image](https://user-images.githubusercontent.com/64065190/129689464-fe94fd01-0146-4915-a737-377b49fbe3d7.png)
