### ISSUE TITLE
[FEATURE]建议新增接口评论功能

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#5444]
**请描述您的需求或者改进建议.**
建议新增接口评论功能，可让前后端开发分别对具体接口展开在线评论

**请描述你建议的实现方案**
接口定义界面中，支持对具体接口提供在线评论功能

**Comment by xulinde** [comment]
感谢您的建议，我们先进行下相关调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
