### ISSUE TITLE
[FEATURE]Swagger导入接口缺少部分参数，优化导入后接口展示页面

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#5445]
**请描述您的需求或者改进建议.**
swagger导入接口缺少部分参数，如请求头缺少描述字段
![image](https://user-images.githubusercontent.com/34565342/129659698-ced98b21-1b1d-4f45-aa51-ac9218f770be.png)
![image](https://user-images.githubusercontent.com/34565342/129659826-c2dc403e-b99a-4066-bfa2-261548230e69.png)

**请描述你建议的实现方案**
优化swagger导入接口后的展示页面

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/7060
