### ISSUE TITLE
[FEATURE]优化API更新相关功能

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#5446]
**请描述您的需求或者改进建议.**
建议优化API更新相关功能：

1. API更新通知对应人员，如通过飞书通知
2. API更新对受影响的case提供提醒功能，并支持一键式快捷更新关联的case
3. API历史变更，优化展示方式，类似git提交代码后新旧版本对比展示方式

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
1和2，v1.12版本会支持；3后续可以优化

**Comment by zyyfit** [comment]
1和2在最新版已支持

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
