### ISSUE TITLE
[FEATURE]如果MS系统关联了Jira，提交的bug在ms上不能在编辑了，希望这类的bug能再二次编辑，要不测试人员要到jira系统进行修改，会造成测试人员维护系统过多

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5448]
**请描述您的需求或者改进建议.**
目前如果MS系统关联了Jira，提交的bug在ms上不能在编辑了，希望这类的bug能再二次编辑，要不测试人员要到jira系统进行修改，会造成测试人员维护系统过多

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，我们先进行下相关调研

**Comment by xulinde** [comment]
v1.13已支持，编辑第三方平台的缺陷
