### ISSUE TITLE
[BUG] 选择 ldap 方式可以使用空密码登录，导致账号越权

### ISSUE THREAD

**Issue by Smallrole** [metersphere/metersphere#5456]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 1.10.7

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
1.  填字正确账号，但密码为空，调用/ldap/signin接口，返回登录成功结果。

**期待的正确结果**
密码为空时不能登录

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，另外，现在已经发布1.10.11 / 1.13.0版本了，您可以升级试试

**Comment by Smallrole** [comment]
重现步骤，通过接口工具直接调整api
![图片1](https://user-images.githubusercontent.com/20022472/139800841-5ee89488-b634-4fde-b8de-0fff72308a56.png)
