### ISSUE TITLE
[FEATURE]设置发送消息如何该如何设置？ 比如：提缺陷的时候发送邮件给研发，在MS组织里面有一个消息设置，这里可以指定具体的研发。但是实际情况是，不同的业务线有不同的研发，或者同一个项目不同的模块，研发人员也是不一样的，这个问题MS该怎么解决？

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5457]
**请描述您的需求或者改进建议.**

设置发送消息如何该如何设置？
比如：提缺陷的时候发送邮件给研发，在MS组织里面有一个消息设置，这里可以指定具体的研发。但是实际情况是，不同的业务线有不同的研发，或者同一个项目不同的模块，研发人员也是不一样的，这个问题MS该怎么解决？

**请描述你建议的实现方案**
实现方案比较多比如：新建bug时候指定bug修改人，保存bug时候直接邮件给修改人，当然系统也可以设置不发送邮件。

**Comment by zyyfit** [comment]
您好，现在缺陷可以发送给处理人了
