### ISSUE TITLE
[FEATURE]编写测试用例增加排序功能

### ISSUE THREAD

**Issue by yangxe2021** [metersphere/metersphere#5458]
**请描述您的需求或者改进建议.**

当前编写测试用例，用例排序根据最后修改时间排序，没有调整排序功能，不符合实际使用场景。
同时导入用例后，顺序与原文档也不一致。

**请描述你建议的实现方案**
建议增加可调整排序的功能。导入用例后顺序与文档一致。

**Comment by xulinde** [comment]
默认是按照更新时间降序排序的，您还可以按照创建时间排序。您是希望可以自定义排序吗
![Uploading image.png…]()

**Comment by xulinde** [comment]
默认是按照更新时间降序排序的，您还可以按照创建时间排序。您是希望可以自定义排序吗
![Uploading image.png…]()
