### ISSUE TITLE
[BUG]测试计划定时任务执行失败，报错空指针异常

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#5463]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建测试计划
2.  新建定时任务
3.  执行几天后（期间可能新增用例，修改环境变量内容）
4. 定时任务执行报错空指针异常

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/26110332/129697602-a3c400df-d7fe-4998-8404-e82288137068.png)

如果有截图，请附上截图.

**Comment by JackieShangJie** [comment]
版本v1.10.3

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题，然后现在最新版已经是1.10.8/1.11.2了，您可以升级一下看看还有没有这个问题
