### ISSUE TITLE
[BUG]接口定义的文档分享链接需要用无痕浏览器打开，否则如果之前登陆过的话，会显示所有的接口文档

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5468]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.11.2

**Bug 描述**

在接口定义列表下，切换到文档，点击分享，该链接给其他用户后，如果用户登陆过，则会显示该用户的所有接口文档，必须要打开无痕浏览器去查看，才会显示目前文档

![image](https://user-images.githubusercontent.com/32027713/129825503-8ce04406-a79b-4c3b-a7d0-6c37a7e2fa54.png)

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/32027713/129825555-3bc616c5-e0bb-47bf-b635-553f0576642d.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
