### ISSUE TITLE
[BUG]测试跟踪->项目 中展示的案例“状态”字段未更新，测试计划中案例的“执行结果”字段未同步给项目中案例的“状态”字段！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#547]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1
**Bug 描述**
简要描述您碰到的问题
测试跟踪->项目 中展示的案例“状态”字段未更新，测试计划中案例的“执行结果”字段未同步给项目中案例的“状态”字段！
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前这里展示的是评审状态而非测试计划中的执行结果，新版本中将把列名改为‘评审状态’，避免歧义。
