### ISSUE TITLE
[BUG]接口定义的模块内搜索目标模块，点击编辑目标模块时模块页面会跳出，又要重新往下拉寻找目标模块才能编辑

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5477]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V.1.11.2

**Bug 描述**

简要描述您碰到的问题

接口定义的模块内搜索目标模块，点击编辑目标模块时模块页面会跳出，又要重新找目标模块才能编辑

**Bug 重现步骤**

搜索到目标模块后编辑保存，模块列表闪跳
**截图**

![image](https://user-images.githubusercontent.com/32027713/129848951-0c75b403-c23f-4d6e-a3f4-2cf1b673a77f.png)
点击编辑时，模块列表又会出现
![image](https://user-images.githubusercontent.com/32027713/129849058-c2a4979e-ceff-402b-9453-267b0544621e.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
