### ISSUE TITLE
[BUG]jenkins执行只有接口用例的测试计划可以，执行只有场景的测试计划一直卡着。

### ISSUE THREAD

**Issue by qiaoshengyu** [metersphere/metersphere#5480]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 meterphere版本v1.11.2-b2，jenkins插件版本v1.11.2
**Bug 描述**
jenkins执行只有接口用例的测试计划可以，执行只有场景的测试计划一直卡着。
![image](https://user-images.githubusercontent.com/41959940/129859326-05e60de9-63c9-42b8-b936-e4abd71ef5a5.png)
简要描述您碰到的问题
**Bug 重现步骤**
1.  
2. 
3. 
4. 
**期待的正确结果**
测试计划均可正常运行。
正确情况下应该是什么样的？
测试计划均可正常运行。
**截图**

如果有截图，请附上截图.

**Comment by qiaoshengyu** [comment]
已升级测试，1.11.3版本将未修复这个问题

**Comment by qiaoshengyu** [comment]
> 你好，1.11.3版本会修复这个问题

已升级测试，1.11.3版本将未解决这个问题

**Comment by xulinde** [comment]
用最新版本还有此问题吗
