### ISSUE TITLE
[BUG]jenkins插件运行结果取得不是本次成功与否的结果（猜测取的上次运行的结果）。

### ISSUE THREAD

**Issue by qiaoshengyu** [metersphere/metersphere#5481]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
meterphere版本v1.11.2-b2，jenkins插件版本v1.11.2
**Bug 描述**
jenkins插件运行结果取得不是本次成功与否的结果（猜测取的上次运行的结果）。
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/41959940/129860401-ecf93bfa-4d95-4238-88c9-01154929d0a4.png)
![image](https://user-images.githubusercontent.com/41959940/129859882-cec1ddae-0072-4002-adbf-98b20c1c4681.png)
![image](https://user-images.githubusercontent.com/41959940/129859946-d10965d3-5c16-4f4b-b485-4a06135b2b17.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
取本次测试用例运行的结果
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
使用最新版本还有此问题吗
