### ISSUE TITLE
添加更多断言方式，比如Beanshell断言

### ISSUE THREAD

**Issue by majiashuo** [metersphere/metersphere#549]
**请描述您的需求或者改进建议.**

一些特殊接口断言不仅是判断响应字段，还有一些自定义的处理数据，希望添加更多的断言方式，比如Beanshell断言

**请描述你建议的实现方案**
参照jmeter的Beanshell断言。

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，目前已实现该需求，请更新到最新版本～
