### ISSUE TITLE
[BUG]测试跟踪-测试计划设置定时任务执行通知出错

### ISSUE THREAD

**Issue by 13072124817** [metersphere/metersphere#5496]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪-测试计划设置定时任务-任务通知
2. 仅设置执行失败发送邮件通知

实际定时任务执行成功也发送邮件

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.11.3没有复现这个问题，请问您使用的是哪个版本呢？如果不是最新版请升级到最新版试试

**Comment by 13072124817** [comment]
版本是：v1.11.2-854acb67

**Comment by xulinde** [comment]
用最新版本还有此问题吗
