### ISSUE TITLE
[BUG]测试跟踪-测试计划-定时任务仅执行第一次关联的测试场景用例

### ISSUE THREAD

**Issue by 13072124817** [metersphere/metersphere#5497]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.2-854acb67

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪-测试计划-接口测试用例【场景用例】-关联测试用例7条
2. 设置定时任务
3. 场景用例中新增关联5条，共12条
4. 定时任务执行，仅发送了7条成功邮件

另外：不确定是否与【https://github.com/metersphere/metersphere/issues/5496】bug有关联，请排查
比如：新增时设置了执行成功发送邮件；后更新为仅执行失败发送邮件，后又新增了5条场景用例；导致原7条时执行了成功即发送邮件，后新增的发送失败才会发送，所以成功没有发送

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，这个问题复现了，我们将在后续版本进行修复

**Comment by zyyfit** [comment]
感谢反馈，这个问题复现了，我们将在后续版本进行修复

**Comment by xulinde** [comment]
1.12版本已修复
