### ISSUE TITLE
[FEATURE]接口case脚本中引用了jar包执行失败时无提示

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5500]
**请描述您的需求或者改进建议.**
在接口定义中的接口case，当引用的jar包路径或者方法存在问题时，点击执行时执行结果不会更新，也无任何提示，只能去服务端后台看日志才发现是jar包的引入问题

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先内部讨论一下

**Comment by luty2018** [comment]
非常抱歉现在才回复。
目前这种问题出在JMeter 那里执行直接无结果，所以平台也给不了提示。
