### ISSUE TITLE
[FEATURE]场景变量csv变量删除无提示容易导致误删

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5501]
**请描述您的需求或者改进建议.**
在接口自动化中，在场景变量中如果是CSV类型的变量，删除上传的CSV文件无提示，容易导致误删；

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后续版本，可以优化下这里

**Comment by zyyfit** [comment]
已增加删除确认提示
