### ISSUE TITLE
[FEATURE]测试报告希望提供重复执行的功能

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5503]
**请描述您的需求或者改进建议.**
当选择了一部分接口自动化场景，选择批量执行时，当发现测试报告有报错时，修改完相关参数后，希望再次执行一次时，如果测试报告提供可重复执行的功能，则会便捷很多；

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by luty2018** [comment]
已支持， 请更新到v2.7版本使用。
