### ISSUE TITLE
[FEATURE]场景导出和导入希望将CSV场景变量能导出和导入

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#5505]
**请描述您的需求或者改进建议.**
当接口自动化中，场景变量中部分变量采用CSV文件时，当导出场景，导入到另外一个环境时，会导致找不到CSV文件，建议可以将CSV文件的数据放入数据库中，便于场景的导出和导入

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后续版本可以优化

**Comment by luty2018** [comment]
已支持变量的导入导出， 请更新到v2.7版本使用。
