### ISSUE TITLE
[BUG]项目设置中：配置了多域，同时也设置了host，在执行接口测试用例时，取不到请求头。==如果把host关闭就没有问题

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5508]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.11

**Bug 描述**

项目设置中：配置了多域，同时也设置了host，在执行接口测试用例时，取不到请求头。

**Bug 重现步骤**

1.  项目环境配置>>通用配置：打开host，配置host相关信息
2. 项目环境配置>>http配置：设置多域
3. 执行接口测试用例，失败，请求头无信息
4. ===尝试了一下，如果关闭host，执行接口测试用例就没有问题。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/130027373-f187a154-5bb7-4a61-824c-22cba5b9d406.png)
![image](https://user-images.githubusercontent.com/78218624/130027488-afc6777c-b52c-4677-9217-41808a620274.png)
![image](https://user-images.githubusercontent.com/78218624/130027635-a9f35fd3-0743-49ad-a998-d75934606a83.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
