### ISSUE TITLE
[BUG]Jira 创建 缺陷，设置自定义字段 支持多选输入框

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#5518]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
Jira 创建 缺陷，设置自定义字段 支持多选输入框
**Bug 重现步骤**

1. 在jira 里模版添加 标签 字段，标签为多选
2. 真实api传的值为 一个数组 
![WechatIMG297](https://user-images.githubusercontent.com/30038088/130053283-5d016125-aa4f-4630-b1b9-0209a28850c8.png)

3. 目前ms里可设置的自定义字段 不支持 多选输入框
4. 需增加一个“多选输入框” 的 自定义字段的类型 

**期待的正确结果**

正确情况下应该是什么样的？
能够正常创建 输入多个 自定义值的 缺陷
**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
error信息： labels:data was not an array

**Comment by zyyfit** [comment]
您好，请问您使用的jira是哪个版本的？我们测试用的jira版本中lable标签是这样的
![图片](https://user-images.githubusercontent.com/73461316/130547605-f1dab88a-a7a3-47a9-9430-f45e39b4eec8.png)
