### ISSUE TITLE
[BUG]入参类型为file，添加多个文件，删除后面的文件，从第一个文件删除

### ISSUE THREAD

**Issue by majiashuo** [metersphere/metersphere#552]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1
**Bug 描述**
简要描述您碰到的问题
1.入参类型为file，添加多个文件
2.点击删除第一个文件外的文件
**Bug 重现步骤**
1.入参类型为file，添加多个文件
2.点击删除第一个文件外的文件
3.文件列表，删除的第一个文件

**期待的正确结果**
删除当前点击删除的文件

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/27984385/95974563-b9f15580-0e47-11eb-8289-51bbed30c3eb.png)
![image](https://user-images.githubusercontent.com/27984385/95974584-c1186380-0e47-11eb-9247-7db48c10ff4c.png)

**Comment by AgAngle** [comment]
你好，1.4版本已修复，请升级验证
