### ISSUE TITLE
接口自动化重试机制，执行失败的场景可以自动重试2~3次

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#5526]
**请描述您的需求或者改进建议.**

接口自动化有些时候会因为环境等原因导致接口自动化执行失败

**请描述你建议的实现方案**

期望可以添加接口自动化重试功能

**Comment by xulinde** [comment]
感谢您的建议，后面版本这里会优化的

**Comment by luty2018** [comment]
已支持， 请升级到v2.7 版本使用。
