### ISSUE TITLE
测试计划报告模板手动保存与定时生成的模板不一致[BUG]

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#5532]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**

简要描述您碰到的问题
同一个测试计划,手动保存的报告模板是对的,但是定时执行完成自动保存的报告,只有'测试结果统计'和'失败用例',没有模板里的测试结果和缺陷列表这两项.
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
定时运行的测试报告应该和手动保存的一致.
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，定时任务只执行接口和性能测试，所以报告中不体现功能测试的项目
