### ISSUE TITLE
[BUG]接口自动化编辑脚本运行保存会出现内存益出

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#5535]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

接口自动化编辑脚本运行保存会出现内存益出

**Bug 重现步骤**

1.  在列表运行完成后进入编辑页面
2. 点击调试
3. 调试完成后点击保存
4. 
![image](https://user-images.githubusercontent.com/80370956/130196108-0500cc8a-c18e-4d2a-be80-940de416e49e.png)
![image](https://user-images.githubusercontent.com/80370956/130196164-50446c42-43f6-483d-bd4e-9329ca2e5206.png)
![image](https://user-images.githubusercontent.com/80370956/130196180-dc7a1e0f-4bbf-46f8-8112-915ff5aa2ced.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/80370956/130195940-e5bf517f-edd4-4a16-a2ef-50a99ba19a04.png)
![image](https://user-images.githubusercontent.com/80370956/130195964-a49a8a96-2386-4ddc-b5fb-3ca72a4afb75.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是任意一个场景都会出现吗？或者这个场景有什么特殊的吗？

**Comment by Evan-guo131** [comment]
一直出现，都没法使用了，有办法解决这个问题吗




发自我的iPhone

**Comment by wangzhen-fit2cloud** [comment]
你好，可以调整下 /opt/metersphere/docker-compose-server.yml 中的内存限制
![image](https://user-images.githubusercontent.com/27671436/130783113-64f98b20-fafe-4f9e-ac81-74032b672aad.png)
调整后执行 msctl reload

**Comment by Evan-guo131** [comment]
解决不了 可以换一个大神

**Comment by xulinde** [comment]
您好，使用最新版本还有这个问题吗
