### ISSUE TITLE
[BUG]测试跟踪-测试计划，新增测试计划可以正常新增保存，新增成功后对该记录操作【编辑】，弹出编辑窗口，未修改任何信息直接点击【确定】按钮，系统提示计划名称重复！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5538]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.11.3-8e3889e3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
测试跟踪-测试计划，新增测试计划可以正常新增保存，新增成功后对该记录操作【编辑】，弹出编辑窗口，未修改任何信息直接点击【确定】按钮，系统提示计划名称重复！

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/54024064/130203852-9ea25dfd-2486-4b1e-9e5a-03604bd883b8.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，可以稳定复现吗？我没有复现这个问题
