### ISSUE TITLE
[FEATURE]建议增加定义任务的统一维护入口，之前旧版本有添加了接口自动化的定时任务，后续接口自动化场景越来越多，需要移除一些定时任务，已经找不到具体是哪个场景接口自动化案例里面有定时任务了！

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5539]
**请描述您的需求或者改进建议.**

建议增加定义任务的统一维护入口，之前旧版本有添加了接口自动化的定时任务，后续接口自动化场景越来越多，需要移除一些定时任务，已经找不到具体是哪个场景接口自动化案例里面有定时任务了！

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先内部讨论一下

**Comment by zyyfit** [comment]
另外，我们现在接口定义首页和测试跟踪首页都有相关的当前运行中的定时任务展示，您看这个功能可以满足您的需求吗

**Comment by allinone-1** [comment]
@zyyfit  你好，我这边也有类似诉求，需要统一对定时任务管理，目前没有看到metersphere上面有入口，现在想要管理的话很麻烦，需要去测试报告中搜索所有的定时任务报告，然后再到对应的接口中去修改或清除定时任务

**Comment by zyyfit** [comment]
@feiyu0316  @allinone-1   你们看这里的定时任务列表符合你们的需求吗？测试跟踪、接口测试、性能测试首页都有的，会显示当前项目下的定时任务

![图片](https://user-images.githubusercontent.com/73461316/143406196-9ca2940c-4522-4467-903d-6a6a07ad55eb.png)

接口定义中的swagger定时任务可以在这里看
![图片](https://user-images.githubusercontent.com/73461316/143406567-70ce6052-a2d0-417e-9caa-1136b7e28f04.png)

**Comment by feiyu0316** [comment]
可以看到
