### ISSUE TITLE
[BUG]测试用例导出全部，接口报错

### ISSUE THREAD

**Issue by zhoufan55** [metersphere/metersphere#554]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.3.0

**Bug 描述**
测试跟踪中，将编写的测试用例，不勾选，直接点击导出，无法导出，接口报错

**Bug 重现步骤**
1.  测试跟踪，导出全部测试用例，不勾选任何一条用例
2. 
3. 
4. 

**期待的正确结果**
导出全部测试用例即可

**截图**
![image](https://user-images.githubusercontent.com/16551365/95980745-30925100-0e50-11eb-8312-2f3fb9304e84.png)

**Comment by AgAngle** [comment]
你好，该问题是由于1.1版本创建的用例格式与之后版本格式有差异，1.1版本创建的用例，若测试步骤未填写导出会报错，1.2之后创建的用例导出正常，目前该问题不好兼容，还请检查下具体是哪个用例的测试步骤未填写，填写完保存即可正常
