### ISSUE TITLE
[BUG]测试计划入口操作执行案例，案例详情页面中的“关联缺陷”记录展示的“平台状态”未同步更新为tapd中缺陷的实际状态。

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5541]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.11.3-8e3889e3

**Bug 描述**

简要描述您碰到的问题：测试计划入口操作执行案例，案例详情页面中的“关联缺陷”记录展示的“平台状态”未同步更新为tapd中缺陷的实际状态。

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/130205229-a9848117-8e82-4c37-9968-e63c76c0c630.png)

**Comment by xulinde** [comment]
需要手动同步的
![image](https://user-images.githubusercontent.com/64065190/130211943-3b858be1-efa3-4870-8bde-e680a1169479.png)
