### ISSUE TITLE
[BUG]与jira集成时，如果jira的事务类型方案是自定义的方案，在缺陷管理提交bug同步到jira时会报选择问题类型错误。

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5543]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.2
**Bug 描述**

简要描述您碰到的问题
与jira集成时，如果jira的事务类型方案是自定义的方案，在缺陷管理提交bug同步到jira时会报选择问题类型错误。
**Bug 重现步骤**

1.  与jira集成时，如果jira的事务类型方案是自定义的方案
3. 在缺陷管理提交bug同步到jira时会报选择问题类型错误。
2. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
正常同步缺陷
**截图**

如果有截图，请附上截图.
<img width="406" alt="1" src="https://user-images.githubusercontent.com/83771182/130205508-39178cdf-2e0e-4f58-a022-c70194654645.png">
<img width="863" alt="2" src="https://user-images.githubusercontent.com/83771182/130205627-98ddf583-23a4-4cc2-b397-33f44b5397bc.png">

**Comment by zyyfit** [comment]
您好，我这边没有复现这个问题，也可能是因为使用的jira版本和你不一样，你是用的哪个版本呢

**Comment by zcyuefan** [comment]
能不能提供一下和testlink一样的功能，直接输入jira issue 的对外ID就能同步到ms啊？jira上面自定义字段经常变，现在弄起来也异常麻烦，目前缺陷主要就用在报告里面做统计。能像testlink一样方便就足够了

**Comment by xulinde** [comment]
您好，使用最新版本还有这个问题吗
