### ISSUE TITLE
[FEATURE]执行msctl upgrade升级成功后，还要手动修改配置文件的访问权限

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#5544]
**请描述您的需求或者改进建议.**
每次升级生成的配置文件，权限不够，需要后面手动添加文件权限

**请描述你建议的实现方案**
希望在安装脚本中创建文件的时候，自动给文件加上使用权限

**Comment by xulinde** [comment]
具体指哪个文件？

**Comment by hu-shuli** [comment]
主要是/opt/metersphere/conf目录下的文件这几个文件，还有prometheus下的的文件






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月23日(星期一) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]执行msctl upgrade升级成功后，还要手动修改配置文件的访问权限 (#5544)





 
具体指哪个文件？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuruibin** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
