### ISSUE TITLE
[FEATURE]如果多个场景并入一个定时场景任务，建议将各个场景的执行结果在通知中展示出来，更加直观查看各个场景的执行情况

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#5546]
**请描述您的需求或者改进建议.**
版本1.13
如果多个场景并入一个定时场景任务，建议将各个场景的执行结果在通知中展示出来，更加直观查看各个场景的执行情况
![image](https://user-images.githubusercontent.com/69206282/130308865-7cb82372-c7df-4e08-ae89-38d69e685c08.png)

**请描述你建议的实现方案**

接口测试定时任务通知:定时任务所执行的【XXX】-2021-08-21 08:43:09'执行结果如下
场景1：成功
场景2：失败
场景3：成功
执行环境:Test
[接口定义暂无报告链接]
请点击下面链接进入测试报告页面
接口测试路径：XXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
我们有提供生成独立报告或集合报告， 你可以更新版本试试独立报告是否可以覆盖你的需求。
