### ISSUE TITLE
[BUG]新建测试，选择已有场景，引用OR复制后，无法保存或执行该测试

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#555]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.0-b805
**Bug 描述**
简要描述您碰到的问题
新建测试，选择已有场景，引用OR复制后，无法保存或执行该测试了，点击保存或保存执行，界面没反应，控制台没有接口调用信息
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70245535/96066415-39743880-0ecb-11eb-92ea-6525ae6637cb.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问升级 1.4.0 后该问题还存在吗？如果问题还存在请重新开下该 issue
