### ISSUE TITLE
[BUG]jenkins调用执行测试计划执行失败

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#5555]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.3
**Bug 描述**
Jenkins调用执行测试计划执行失败，后台日志报错ERROR i.m.api.service.TestResultService ? - Method[saveResult][null]
java.lang.NullPointerException: null
简要描述您碰到的问题
升级到1.11.3后过了一段时间，Jenkins调用执行测试计划执行失败
**Bug 重现步骤**

1.  升级到1.11.3后，过一段时间（第一次出现间隔时间十多个小时，第二次重启所有服务，间隔时间超过24小时以后）
2. 通jenkins调用执行测试计划，测试用例执行全部失败，邮箱没有收到测试报告邮件
3. 查看/opt/metersphere/logs/metersphere/error.log 文件又报错信息
4. 

**期待的正确结果**

正确情况下应该是什么样的？
用例能够正常执行，生成测试报告，并发送到相关邮箱
**截图**
![image](https://user-images.githubusercontent.com/66474661/130378038-99bf8b04-ab52-4657-9b2d-95b324824e39.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问jenkins是设置了定时调用吗？还有什么其他配置需要注意吗？我们先排查一下问题
