### ISSUE TITLE
[BUG]批量执行后，测试执行人不会和当前登录的帐号绑定

### ISSUE THREAD

**Issue by xiaoma2014** [metersphere/metersphere#5556]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.5-678b9a6a
**Bug 描述**
批量执行后，测试执行人不会和当前登录的帐号绑定
**Bug 重现步骤**

1、A分一批用例 给B执行
2、B执行通过后，批量编辑测试结果为通过
3、测试执行人默认为A

**期待的正确结果**  
期望是B，单个用例单个用例执行通过的话，这个测试执行人会默认为当前登录的帐户B。批量编辑不行，会有问题。
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.11.3没有复现这个问题，lts版也已经更新到1.10.8了，建议您升级到最新版试一下
