### ISSUE TITLE
[BUG]Jenkins 插件结果问题

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#556]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/37016695/96069386-b35af080-0ed0-11eb-8adc-f1b6a28f7ad0.png)
metersphere出现这个问题导致Jenkins构建应用failed，这感觉不应该呀，我已经在插件里设置了以Jenkins结果为准

**Bug 重现步骤**
1.  如上图示
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
正确应该是，Jenkins构建成功

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
能否发下 jenkins 任务的配置接结果日志的截图

**Comment by AgAngle** [comment]
你好，你这个是docker没启动，请执行systemctl restart docker , msctl reload 重启下docker和服务
