### ISSUE TITLE
CSV参数，使用函数，无法读取

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#5568]
**请描述您的问题.**
经测试，目前无法使用csv中的函数，进行参数化测试，但使用jmeter可以支持。

请教如何使用csv文件中，使用jmeter内置的函数方法，进行取值循环？

![csv函数](https://user-images.githubusercontent.com/6467295/130408634-88d9b96d-2ddf-458c-848a-886c1717cf40.png)

**Comment by zyyfit** [comment]
您好，可以看一下这个
https://mp.csdn.net/mp_blog/creation/editor/115512966

**Comment by seasoncool** [comment]
@zyyfit  谢谢您的回复，这个帖子我查到过，该贴的CSV里面都是常量，并没有用 时间戳函数来进行遍历。

它解决不了我的问题： 我们现在是 CSV 文件里面放 时间戳函数 作为变量，在MS里面用while去循环，无法得到结果。

**Comment by zyyfit** [comment]
你可以使用 ${__eval(${变量名})} 这个函数，来引用你csv里的变量
