### ISSUE TITLE
从接口定义入口上传的jmeter脚本，断言数据丢失，未上传

### ISSUE THREAD

**Issue by caijuzhu** [metersphere/metersphere#5575]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本：V1.11.2

**Bug 描述**

1.从接口定义入口上传jemter脚本后，发现断言数据未传入系统中

**Bug 重现步骤**

1.  从接口定义入口上传有断言的jmeter脚本
2. 上传脚本后，未找到断言内容

**期待的正确结果**

有断言结果

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
