### ISSUE TITLE
从接口自动化入口上传jmeter脚本，执行后断言不通过

### ISSUE THREAD

**Issue by caijuzhu** [metersphere/metersphere#5576]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.11.2

**Bug 描述**

本地jmeter脚本执行正常，但在metersphere平台接口自动化入口上传jmeter脚本，执行后断言不通过

**Bug 重现步骤**

1.  在metersphere平台上上传jmeter脚本，其中断言是匹配文本，包含整个返回的json串
2. 执行脚本失败（备注：本地执行是成功的）

**期待的正确结果**

脚本执行通过

**截图**
断言部分见附件
![image](https://user-images.githubusercontent.com/54243033/130416907-691b33a5-029b-4930-b326-667fb155bd6f.png)

**Comment by xulinde** [comment]
使用最新版本未复现该问题，您版本太老了，建议升级下
<img width="963" alt="image" src="https://user-images.githubusercontent.com/64065190/170432950-5e1ab612-94ac-4776-83fb-902b63380ede.png">
