### ISSUE TITLE
[QUESTION]while 或 foreach 循环可以自动读取到文件结尾吗？CSV文件

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#5577]
请问下，我们使用逻辑控制器，无法如预期的获取执行的次数。

我们想自动根据 CSV文件的行数 来进行循环，也查了几个[帖子](https://blog.csdn.net/jierxiaoyao/article/details/115512966?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-2.control&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromMachineLearnPai2%7Edefault-2.control)，不太符合预期。

请教下 如何实现，根据csv文件行数来进行遍历？

**Comment by wangzhen-fit2cloud** [comment]
你好，目前不太支持这种方式。csv 文件的行数基本都是已知的，针对这种情况可以先使用次数循环来处理。
