### ISSUE TITLE
[BUG]导入xmind用例时，提示“所属模块不能为空格”

### ISSUE THREAD

**Issue by wuqifan1988** [metersphere/metersphere#558]
**MeterSphere 版本**
1.3

**Bug 描述**
导入xmind用例时，提示“所属模块不能为空格”，未知原因，且没有日志输出，不方便定位问题

**Bug 重现步骤**
1.  导入xmind用例

**期待的正确结果**
所属模块不能为空格，输出为空格的节点路径

**Comment by fit2-zhao** [comment]
1.4 版本修复
