### ISSUE TITLE
[FEATURE]缺陷管理查询列表中bug状态建议增加排序，bug的状态最好用不同颜色展示

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5584]
**请描述您的需求或者改进建议.**
缺陷管理查询列表中bug状态建议增加排序，bug的状态最好用不同颜色展示

**请描述你建议的实现方案**
缺陷管理查询列表中bug状态建议增加排序，bug的状态最好用不同颜色展示

**Comment by xulinde** [comment]
感谢您的建议，缺陷管理模块会持续优化

**Comment by xulinde** [comment]
缺陷状态已支持排序功能
![image](https://user-images.githubusercontent.com/64065190/134482962-7bf37dd7-7af7-406d-b8ac-83b63f8313f1.png)
