### ISSUE TITLE
[FEATURE]用户管理导入用户时候用户的密码必须要大小写都有才能成功，但是导入时并没有提，建议增加

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5586]
**请描述您的需求或者改进建议.**

用户管理导入用户时候用户的密码必须要大小写都有才能成功，但是导入时并没有提，建议增加
**请描述你建议的实现方案**
用户管理导入用户时候用户的密码必须要大小写都有才能成功，但是导入时并没有提，建议增加

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化

**Comment by luty2018** [comment]
已支持。
