### ISSUE TITLE
在脑图里面新建一个子模块，然后保存，会说没有给case的标签[BUG]

### ISSUE THREAD

**Issue by shuowu1jin** [metersphere/metersphere#5594]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
![image](https://user-images.githubusercontent.com/86592078/130451063-8dc1259c-c69a-4c61-9803-6231e54620e1.png)

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/86592078/130451187-61a1af1f-340c-49fb-8689-ddb49dfb992d.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，脑图里目前不支持添加模块，添加用例和步骤是需要打标签的
