### ISSUE TITLE
接口自动化-测试场景列表针对一个场景进行编辑,编辑页面已配置测试环境点调试,一直转圈,页面没有请求数据和响应数据[BUG]

### ISSUE THREAD

**Issue by Ggangwang21** [metersphere/metersphere#5596]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.3
**Bug 描述**

简要描述您碰到的问题
测试场景编辑页面,点调试,一直转圈,且各个接口没有请求入参和响应数据

**Bug 重现步骤**

1.  测试场景列表-点编辑
2. 编辑页面配置环境设置
3. 点调试
4. 调试成功-有请求有响应,可以获取变量--实际上一直转圈无法查看也没有请求/响应

**期待的正确结果**
调试成功,可以查看请求的所有信息和返回的所有数据,并且可以正常设置断言和提取返回参数
正确情况下应该是什么样的？
之前是:调试成功,可以查看请求的所有信息和返回的所有数据,并且可以正常设置断言和提取返回参数

![微信图片_20210823210711](https://user-images.githubusercontent.com/89377465/130452494-3c987d76-2466-4726-b0dd-267bdadf51b5.png)

**截图**
相关脚本 已有技术老师远程确认过 没有问题,之前都还是好的,估计期间哪个版本改动影响
如果有截图，请附上截图.

**Comment by xulinde** [comment]
有配置nginx吗？有的话，nginx要加下支持websock的配置

**Comment by xulinde** [comment]
![b40ca6ac17f5531a3b34f98bd528613](https://user-images.githubusercontent.com/64065190/131314787-bee1fdc3-3f16-45ca-b5cb-ab7026d69eca.png)
