### ISSUE TITLE
[BUG]正确配置邮件服务后，点击测试连接，不可用，无线转圈没有返回结果

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#56]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.0.2-b357

**Bug 描述**
简要描述您碰到的问题
正确配置邮件服务后，点击测试连接，不可用，无线转圈没有返回结果

**Bug 重现步骤**
1.  正确配置邮件服务
2. 点击测试连接
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
及时给出测试结果

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/86091779-0bffac80-badf-11ea-98d9-cfe4e86059de.png)

**Comment by wangzhen-fit2cloud** [comment]
@wenyann 超时改成 30s 吧，现在超时太长了

**Comment by AgAngle** [comment]
v1.0.3版本已优化
