### ISSUE TITLE
缩小放大按钮的颜色，实在很难看出来，应该加深些颜色，加强视觉效果

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#560]
![image](https://user-images.githubusercontent.com/37016695/96225149-3ceaeb00-0fc3-11eb-82c8-3138a5801dbf.png)

**Comment by xxi0907** [comment]
给你闲的

**Comment by G291131988** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xxi0907 <notifications@github.com&gt;
发送时间: 2020年10月16日 16:45
收件人: metersphere/metersphere <metersphere@noreply.github.com&gt;
抄送: G291131988 <291131988@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[metersphere/metersphere] 缩小放大按钮的颜色，实在很难看出来，应该加深些颜色，加强视觉效果 (#560)





 
给你闲的
