### ISSUE TITLE
场景用例数量统计[FEATURE]

### ISSUE THREAD

**Issue by kuma-z** [metersphere/metersphere#5600]
**请描述您的需求或者改进建议.**
在【接口测试-首页】的【场景用例数量通级】中，是否可以添加一个显示场景用例未覆盖的连接。

**请描述你建议的实现方案**
可以模仿【接口用例数量统计】中，点击【未覆盖】就可显示接口用例未覆盖的接口列表。

**Comment by xulinde** [comment]
这些数据能否满足您的需求
![image](https://user-images.githubusercontent.com/64065190/134482692-a51d2c97-6d6a-4ed4-9820-f1be1df7fcc8.png)
