### ISSUE TITLE
[bug]定时任务指定按周/星期的某一天执行不正确

### ISSUE THREAD

**Issue by five3** [metersphere/metersphere#5608]
**MeterSphere 版本**
>v1.11.2。

**Bug 描述**

设置测试计划定时任务为每周2,4执行，实际上是每周1,3执行

**Bug 重现步骤**

1.  创建测试计划
2.  设置定时任务为每周2,4执行

**期待的正确结果**

每周二、四执行

**截图**

![image](https://user-images.githubusercontent.com/1296223/130565509-4a48c2e1-428b-4bab-8c24-2ccd88557b4a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
