### ISSUE TITLE
[FEATURE]接口请求里面的执行器希望能支持python 自带的库跟第三方库导入使用

### ISSUE THREAD

**Issue by lehmannluo123** [metersphere/metersphere#561]
**请描述您的需求或者改进建议.**
[FEATURE]接口请求里面的执行器希望能支持python 自带的库跟第三方库导入使用

**请描述你建议的实现方案**
[FEATURE]接口请求里面的执行器希望能支持python 自带的库跟第三方库导入使用

**Comment by Dyc2333** [comment]
我们也有这个需求，希望支持python3，并且支持自定义类库，可以考虑单独启动一个执行容器用来和ms-server进行交互，所有的python内容在这个容器中运行，对于变量赋值之类的，可以暴露一个内部类库，用来和现有的jython交互。

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by chujidiy** [comment]
我们也有这个需求，希望能支持 python3，且能import python库
