### ISSUE TITLE
[接口自动化]在录入接口时，点击右侧的前后置脚本等操作后，左边应该把接口收起，并定位到最新添加的组件，不然添加了都看不见，以为点击了没反应

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#5611]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/13564069/130571505-f038cc99-e0b4-4dab-b2bf-09aca11be980.png)

**请描述你建议的实现方案**
点击右侧按钮后，左侧接口收起，并跳转到最新添加的组件处

**Comment by Ammyz** [comment]
现在本来页面就只那么大，交互体验上很重要，现在我点了右侧都觉得是没加上，因为左侧我都看不见我加上了

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
