### ISSUE TITLE
[FEATURE]建议在项目集的设置里面也做一个定时任务设置功能，项目设置了定时任务后，项目下面所有测试集里面的测试方法都执行一遍生成相应的报告

### ISSUE THREAD

**Issue by sunxueli** [metersphere/metersphere#562]
**请描述您的需求或者改进建议.**

目前定时任务只能在一个测试集里设置，如果一个项目有N个测试集，就需要每个测试集都设置一遍，建议在项目集的设置里面也做一个定时任务设置功能，项目设置了定时任务后，项目下面所有测试集里面的测试方法都执行一遍生成相应的报告

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，目前还没有这个计划，请持续关注后续版本～
