### ISSUE TITLE
禅道关联缺陷创建问题

### ISSUE THREAD

**Issue by pptech-dev** [metersphere/metersphere#5626]
https://github.com/metersphere/metersphere/blob/023960c0960c5ed74c70606c00fc57b4932d4a3e/backend/src/main/java/io/metersphere/track/issue/ZentaoPlatform.java#L166

这里应该是
```
paramMap.add("project", projectId);
```
才对吧

**Comment by pptech-dev** [comment]
经过调试，metersphere在这一块有些问题

禅道12.4.1

禅道创建bug的接口，product(产品)和project(项目)都需要传递的，而metersphere只能设置项目id。这里的代码却把他赋值给product字段，就导致了创建不成功而报错了

需要改进的地方
![image](https://user-images.githubusercontent.com/84951843/130598915-ba4a5958-d872-45b5-85fa-0647be543c4a.png)

**Comment by shiziyuan9527** [comment]
> 经过调试，metersphere在这一块有些问题
> 
> 禅道12.4.1
> 
> 禅道创建bug的接口，product(产品)和project(项目)都需要传递的，而metersphere只能设置项目id。这里的代码却把他赋值给product字段，就导致了创建不成功而报错了
> 
> 需要改进的地方
> ![image](https://user-images.githubusercontent.com/84951843/130598915-ba4a5958-d872-45b5-85fa-0647be543c4a.png)

什么报错呢，可以贴下日志截图

**Comment by pptech-dev** [comment]
> > 经过调试，metersphere在这一块有些问题
> > 禅道12.4.1
> > 禅道创建bug的接口，product(产品)和project(项目)都需要传递的，而metersphere只能设置项目id。这里的代码却把他赋值给product字段，就导致了创建不成功而报错了
> > 需要改进的地方
> > ![image](https://user-images.githubusercontent.com/84951843/130598915-ba4a5958-d872-45b5-85fa-0647be543c4a.png)
> 
> 什么报错呢，可以贴下日志截图


这里禅道返回的报错信息
{"project":["\u300e\u6240\u5c5e\u9879\u76ee\u300f\u4e0d\u80fd\u4e3a\u7a7a\u3002"]}

![image](https://user-images.githubusercontent.com/84951843/130602008-9a29e735-4912-4349-8c38-a6dbf1d5e5b0.png)

**Comment by pptech-dev** [comment]
下面是网页端创建bug截图
![image](https://user-images.githubusercontent.com/84951843/130602142-622bd7a9-bcfb-4ae1-9a69-3475bd09eade.png)


下面是禅道创建bug的接口代码
![image](https://user-images.githubusercontent.com/84951843/130602399-46e847ac-f4ce-4c26-a692-eba208de4575.png)

**Comment by pptech-dev** [comment]
![image](https://user-images.githubusercontent.com/84951843/130602790-d8c71719-b1cf-479d-9879-5201f2dacf22.png)

**Comment by pptech-dev** [comment]
![image](https://user-images.githubusercontent.com/84951843/130603084-d0f94524-2020-4ca7-9501-d90988307f39.png)

**Comment by shiziyuan9527** [comment]
![image](https://user-images.githubusercontent.com/58418919/130605312-86a3fd29-ec0b-45ef-b02b-35d1972e1e96.png)
这个必填应该是你们自己设置的
![image](https://user-images.githubusercontent.com/58418919/130605502-c5264b61-803a-4090-9232-76af0820b81f.png)
变量名确实有些误导，你可以看下禅道的自定义流程，那个必填项现在还不支持。

**Comment by pptech-dev** [comment]
> ![image](https://user-images.githubusercontent.com/58418919/130605312-86a3fd29-ec0b-45ef-b02b-35d1972e1e96.png)
> 这个必填应该是你们自己设置的
> ![image](https://user-images.githubusercontent.com/58418919/130605502-c5264b61-803a-4090-9232-76af0820b81f.png)
> 变量名确实有些误导，你可以看下禅道的自定义流程，那个必填项现在还不支持。

牛逼！果然按照你所说的解决了！
