### ISSUE TITLE
[FEATURE]测试结果的response里面XML格式的响应文本建议做一下转义

### ISSUE THREAD

**Issue by sunxueli** [metersphere/metersphere#563]
**请描述您的需求或者改进建议.**

测试结果的response里面XML格式的响应文本建议做一下转义
![image](https://user-images.githubusercontent.com/6119570/96392557-11e4df00-11ef-11eb-97a8-9f3edec2896e.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，我们会计划排期优化下
