### ISSUE TITLE
[BUG]性能测试时，data-streaming在TestResultService.java:92行报错，无法保存中间数据到load_test_report_detail

### ISSUE THREAD

**Issue by huhui** [metersphere/metersphere#5634]
**data-streaming组件在接收kafka性能测试数据时，在TestResultService.java:92行报错，使用的data-streaming是master分支代码。最直观的表现就是性能测试报告的测试概览没有数据，具体报错如下**

![image](https://user-images.githubusercontent.com/6800925/130599880-22a7349e-71c3-4830-aeb5-092c40026444.png)

代码修改如下：
![image](https://user-images.githubusercontent.com/6800925/130600491-f6517a0f-facb-4c7b-9860-76c061efeb85.png)
修改后测试概览有数据
![1629800760(1)](https://user-images.githubusercontent.com/6800925/130601125-8dd5b775-96f3-49e1-93a8-ff347dd5f396.jpg)

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下这个问题

**Comment by liuruibin** [comment]
数据库这个表重建了，需要自己执行sql，查看具体的flyway版本操作
