### ISSUE TITLE
征集丨申报MeterSphere优秀案例，赢取MTSC大会门票！

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [metersphere/metersphere#564]
![微信图片_20201019170306](https://user-images.githubusercontent.com/27671436/96424214-fd273c00-122c-11eb-87ab-ce02e68de200.jpg)

**Comment by maninhill** [comment]
88完美邮箱全面提升产品质量的落地指南: https://metersphere.io/docs/case_studies/88com/

**Comment by maninhill** [comment]
蔚澜环保基于MeterSphere的自动化测试实践: https://metersphere.io/docs/case_studies/weilanep/

**Comment by maninhill** [comment]
易盛信息MeterSphere接口测试使用经验: https://metersphere.io/docs/case_studies/esunny/

**Comment by maninhill** [comment]
奈雪の茶-交易营销测试团队--基于MeterSphere持续交付测试: https://mp.weixin.qq.com/s/JKJcnAjE0O5hsrPYpO7_FA
