### ISSUE TITLE
[BUG]测试跟踪里展示的测试用例标题展示不全

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5649]
**MeterSphere 版本**
1.11.3

**Bug 描述**
测试跟踪里展示的测试用例标题展示不全

**Bug 重现步骤**

1.  进入测试跟踪-->测试用例
2. 名称部分明明有很大空间但依然展示有缺失
3. 需要拖动评审结果左侧拉大名称展示空间或点击一下才能展示更多

**期待的正确结果**

测试跟踪里展示的测试用例标题在展示空间正常的情况下展示齐全

**截图**

![企业微信截图_16298045988280](https://user-images.githubusercontent.com/87106917/130718468-8cf6c74e-969c-4d89-a66f-bbc5870934a3.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
