### ISSUE TITLE
[BUG]编辑mock期望，当请求参数为空，此时自定义返回body不生效

### ISSUE THREAD

**Issue by linl12138** [metersphere/metersphere#5653]
metersphere:1.11.1版本

问题：编辑mock期望，当请求参数为空（部分接口不需要请求参数），此时自定义返回body不生效

![image](https://user-images.githubusercontent.com/42909446/130720356-eab2823f-5389-4e93-9ce4-fdaa6545ea52.png)

**Comment by zyyfit** [comment]
您好，请问接口定义中是否参数为空并且设置了response信息呢?
