### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by maverickPIG** [metersphere/metersphere#5654]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
master-529a8b74

**Bug 描述**

简要描述您碰到的问题

无法发送json入参请求， 测试的使用请求体选中json的时候，参入会失效

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![1629861622(1)](https://user-images.githubusercontent.com/9714332/130720942-0df9e0fc-3981-420b-adf3-86367951a7b1.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，另外，我们不建议使用master分支，建议使用最新release版本
