### ISSUE TITLE
[BUG]postman文件导入，内容文本文件格式未保留xml格式

### ISSUE THREAD

**Issue by quyuqi** [metersphere/metersphere#566]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/34157405/96559037-1ee8f780-12ef-11eb-9c60-276c42f772e3.png)
**Bug 重现步骤**
1.  导入postman文件，
2. 内容为raw下文本格式xml
3. 平台导入后，显示默认text格式
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望可以保留原有的格式类型
**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
你好，我测试没有复现这个问题，可以提供下json文件吗

**Comment by wangzhen-fit2cloud** [comment]
你好，请在新版本中验证该问题是否存在。我们将先关闭该问题，如果问题还存在请重新打开该问题。
