### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by zlj1124** [metersphere/metersphere#568]
**部署环境的时候报这个错，怎么解决额，报错信息和版本信息如下图：.**
![报错信息](https://user-images.githubusercontent.com/43691164/96670316-9cfdda80-1391-11eb-9f64-71ed1931897b.png)
![版本信息](https://user-images.githubusercontent.com/43691164/96670318-9ec79e00-1391-11eb-8cdf-02867bc3dc69.png)

**Comment by wangzhen-fit2cloud** [comment]
你好， RedHat 8 版本系统我们没有验证过，建议先使用 7.x 版本进行安装，我们会看下对于 8 版本安装的兼容问题

**Comment by zlj1124** [comment]
> 你好， RedHat 8 版本系统我们没有验证过，建议先使用 7.x 版本进行安装，我们会看下对于 8 版本安装的兼容问题

我换成7.x的版本还是同样报错==
![image](https://user-images.githubusercontent.com/43691164/96806243-1eaf4000-1446-11eb-8b38-963c02425951.png)
