### ISSUE TITLE
mac快速安装后，使用性能测试功能，提示Kafka 不可用，请检查配置

### ISSUE THREAD

**Issue by fuzecheng** [metersphere/metersphere#569]
docker logs kafka 错误日志如下

[2020-10-17 16:52:44,423] WARN Session 0x10000005cfe884f for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.lang.IllegalArgumentException: Unable to canonicalize address zookeeper:2181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:71)
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:39)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1087)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1139)
[2020-10-17 16:52:45,528] ERROR Unable to resolve address: zookeeper:2181 (org.apache.zookeeper.client.StaticHostProvider)
java.net.UnknownHostException: zookeeper
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)

.env 文件配置如下 ：
MS_MODE=allinone
MS_KAFKA_TOPIC=JMETER_METRICS
MS_MYSQL_HOST=mysql
MS_KAFKA_LOG_TOPIC=JMETER_LOGS
MS_KAFKA_EXT_HOST=
MS_NODE_CONTROLLER_PORT=8082
MS_TAG=v1.3.1
MS_KAFKA_HOST=192.168.1.82
MS_BASE=/Users/admin
MS_EXTERNAL_KAFKA=false
MS_KAFKA_PORT=19092
MS_MYSQL_USER=root
MS_EXTERNAL_MYSQL=false
MS_KAFKA_EXT_PORT=19092
MS_PREFIX=registry.cn-qingdao.aliyuncs.com/metersphere
MS_MYSQL_DB=metersphere
MS_MYSQL_PASSWORD=Password123@mysql
MS_JMETER_TAG=5.3-ms11
MS_PORT=8081
MS_MYSQL_PORT=3306

本地静态ip如下 ：
192.168.1.82

**Comment by wangzhen-fit2cloud** [comment]
你好， 请执行下 msctl status 命令看下各个组件的状态是否正常。
另外请详细描述下具体的安装过程

**Comment by fuzecheng** [comment]
状态如下：
       Name                     Command                  State                              Ports                        
-------------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:19092->19092/tcp, 9092/tcp                  
ms-data-streaming    /deployments/run-java.sh         Up (healthy)   0.0.0.0:8084->8084/tcp, 0.0.0.0:8085->8085/tcp      
ms-node-controller   /deployments/run-java.sh         Up (healthy)   0.0.0.0:8082->8082/tcp                              
ms-server            /deployments/run-java.sh         Up (healthy)   0.0.0.0:8081->8081/tcp                              
mysql                docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3307->3306/tcp, 33060/tcp                   
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)   0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp


安装过程是 ：使用1.3.0 msctl upgrade 后 升级1.3.1 发现升级失败，于是先remove 在重新安装1.3.1 发现可以正常升级成功。目前就性能测试整个模块的功能无法正常启动测试

**Comment by fuzecheng** [comment]
docker exec ms-server nc -zv 192.168.1.82:19092
192.168.1.82:19092 (192.168.1.82:19092) open

端口是打开的

**Comment by fuzecheng** [comment]
附上zookeeper logs:
2020-10-15 10:10:42,397 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000005cfe0b1f, timeout of 30000ms exceeded
2020-10-15 10:10:45,273 [myid:1] - WARN  [NIOWorkerThread-3:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:50766, session = 0x10000005cfe0b29
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by fuzecheng** [comment]
有点疑惑，进入下载的docker镜像之后，发现没有命名 ：I have no name! 
root# docker exec -it 2c55b5f4e219 /bin/bash
I have no name!@2c55b5f4e219:/$ 


会不会是因为某些配置文件不是以IP命名而是以这类HOSTNAME命名的 ，导致出错

**Comment by fuzecheng** [comment]
kafka server.properties

############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from 
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
#     listeners = listener_name://host_name:port
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
listeners=INTERNAL://:9092,EXTERNAL://:19092

# Hostname and port the broker will advertise to producers and consumers. If not set, 
# it uses the value for "listeners" if configured.  Otherwise, it will use the value
# returned from java.net.InetAddress.getCanonicalHostName().
advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://:19092

**Comment by fuzecheng** [comment]
### ############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from 
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
#     listeners = listener_name://host_name:port
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
listeners=INTERNAL://:9092,EXTERNAL://:19092

# Hostname and port the broker will advertise to producers and consumers. If not set, 
# it uses the value for "listeners" if configured.  Otherwise, it will use the value
# returned from java.net.InetAddress.getCanonicalHostName().
advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://:19092

**Comment by fuzecheng** [comment]
目前remove后，再次重装，网络ip 在.env中设置正常，功能上使用性能测试，在保存并执行中依然提示kafka不可用，但查看kafka日志已经没有报错信息，但是zk依然报错，报错信息如下：
2020-10-22 07:59:11,500 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800004, timeout of 30000ms exceeded
2020-10-22 07:59:14,209 [myid:1] - WARN  [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56780, session = 0x10000db4d80000b
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-22 07:59:19,499 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800006, timeout of 30000ms exceeded
2020-10-22 07:59:22,834 [myid:1] - WARN  [NIOWorkerThread-7:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56842, session = 0x10000db4d80000d
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by xin7c** [comment]
没人回答么

**Comment by xin7c** [comment]
> 目前remove后，再次重装，网络ip 在.env中设置正常，功能上使用性能测试，在保存并执行中依然提示kafka不可用，但查看kafka日志已经没有报错信息，但是zk依然报错，报错信息如下：
> 2020-10-22 07:59:11,500 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800004, timeout of 30000ms exceeded
> 2020-10-22 07:59:14,209 [myid:1] - WARN [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
> EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56780, session = 0x10000db4d80000b
> at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:834)
> 2020-10-22 07:59:19,499 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800006, timeout of 30000ms exceeded
> 2020-10-22 07:59:22,834 [myid:1] - WARN [NIOWorkerThread-7:NIOServerCnxn@364] - Unexpected exception
> EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56842, session = 0x10000db4d80000d
> at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:834)

我和你遇到的问题一样啊

**Comment by wangzhen-fit2cloud** [comment]
> > 目前remove后，再次重装，网络ip 在.env中设置正常，功能上使用性能测试，在保存并执行中依然提示kafka不可用，但查看kafka日志已经没有报错信息，但是zk依然报错，报错信息如下：
> > 2020-10-22 07:59:11,500 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800004, timeout of 30000ms exceeded
> > 2020-10-22 07:59:14,209 [myid:1] - WARN [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
> > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56780, session = 0x10000db4d80000b
> > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > at java.base/java.lang.Thread.run(Thread.java:834)
> > 2020-10-22 07:59:19,499 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800006, timeout of 30000ms exceeded
> > 2020-10-22 07:59:22,834 [myid:1] - WARN [NIOWorkerThread-7:NIOServerCnxn@364] - Unexpected exception
> > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56842, session = 0x10000db4d80000d
> > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > at java.base/java.lang.Thread.run(Thread.java:834)
> 
> 我和你遇到的问题一样啊

请问你也是在 mac 上安装出现这样的问题吗？

**Comment by xin7c** [comment]
> > > 目前remove后，再次重装，网络ip 在.env中设置正常，功能上使用性能测试，在保存并执行中依然提示kafka不可用，但查看kafka日志已经没有报错信息，但是zk依然报错，报错信息如下：
> > > 2020-10-22 07:59:11,500 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800004, timeout of 30000ms exceeded
> > > 2020-10-22 07:59:14,209 [myid:1] - WARN [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
> > > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56780, session = 0x10000db4d80000b
> > > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > > at java.base/java.lang.Thread.run(Thread.java:834)
> > > 2020-10-22 07:59:19,499 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800006, timeout of 30000ms exceeded
> > > 2020-10-22 07:59:22,834 [myid:1] - WARN [NIOWorkerThread-7:NIOServerCnxn@364] - Unexpected exception
> > > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56842, session = 0x10000db4d80000d
> > > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > > at java.base/java.lang.Thread.run(Thread.java:834)
> > 
> > 
> > 我和你遇到的问题一样啊
> 
> 请问你也是在 mac 上安装出现这样的问题吗？

我在manjaro上，一直zk报错，配ip也不行，服务器上配kafka的host也不行

**Comment by xin7c** [comment]
`       Name                     Command                  State                             Ports                       
-----------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:19092->19092/tcp, 9092/tcp                
ms-data-streaming    /deployments/run-java.sh         Up (healthy)   0.0.0.0:8084->8084/tcp, 0.0.0.0:8085->8085/tcp    
ms-node-controller   /deployments/run-java.sh         Up (healthy)   0.0.0.0:8082->8082/tcp                            
ms-server            /deployments/run-java.sh         Up (healthy)   0.0.0.0:8081->8081/tcp                            
mysql                docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3307->3306/tcp, 33060/tcp                 
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)   0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp,       
                                                                     8080/tcp  `

**Comment by xin7c** [comment]
> > > 目前remove后，再次重装，网络ip 在.env中设置正常，功能上使用性能测试，在保存并执行中依然提示kafka不可用，但查看kafka日志已经没有报错信息，但是zk依然报错，报错信息如下：
> > > 2020-10-22 07:59:11,500 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800004, timeout of 30000ms exceeded
> > > 2020-10-22 07:59:14,209 [myid:1] - WARN [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
> > > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56780, session = 0x10000db4d80000b
> > > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > > at java.base/java.lang.Thread.run(Thread.java:834)
> > > 2020-10-22 07:59:19,499 [myid:1] - INFO [SessionTracker:ZooKeeperServer@600] - Expiring session 0x10000db4d800006, timeout of 30000ms exceeded
> > > 2020-10-22 07:59:22,834 [myid:1] - WARN [NIOWorkerThread-7:NIOServerCnxn@364] - Unexpected exception
> > > EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56842, session = 0x10000db4d80000d
> > > at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
> > > at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
> > > at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
> > > at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> > > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> > > at java.base/java.lang.Thread.run(Thread.java:834)
> > 
> > 
> > 我和你遇到的问题一样啊
> 
> 请问你也是在 mac 上安装出现这样的问题吗？

```
       Name                     Command                  State                             Ports                       
-----------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:19092->19092/tcp, 9092/tcp                
ms-data-streaming    /deployments/run-java.sh         Up (healthy)   0.0.0.0:8084->8084/tcp, 0.0.0.0:8085->8085/tcp    
ms-node-controller   /deployments/run-java.sh         Up (healthy)   0.0.0.0:8082->8082/tcp                            
ms-server            /deployments/run-java.sh         Up (healthy)   0.0.0.0:8081->8081/tcp                            
mysql                docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3307->3306/tcp, 33060/tcp                 
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)   0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp,       
                                                                     8080/tcp  
```

**Comment by a252937166** [comment]
mac同样问题，有人成功解决了吗

**Comment by fuzecheng** [comment]
remove掉所有docker的镜像配置， 用最新的版本，把.env中缺失的kafka host补上就可以用了。之前运维同学说了 在容器中的kafka zk经常会遇到各种各样的问题，建议中间件不要用容器部署

**Comment by wangzhen-fit2cloud** [comment]
> remove掉所有docker的镜像配置， 用最新的版本，把.env中缺失的kafka host补上就可以用了。之前运维同学说了 在容器中的kafka zk经常会遇到各种各样的问题，建议中间件不要用容器部署

嗯，我们的安装包为了安装方便都用了容器进行部署，实际、长期使用的话建议使用独立部署的中间件
