### ISSUE TITLE
[BUG]控制台未输出错误信息及jar包内打印的信息

### ISSUE THREAD

**Issue by tanxiao133** [metersphere/metersphere#5690]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.3
**Bug 描述**

简要描述您碰到的问题

1.11.1之前的版本都支持控制台输出错误信息、及jar包内打印的信息；
升级到1.11.1后就不支持输出这些信息了，但是这些信息对于调试非常重要，如果不输出就没法知道详细的错误信息，调试起来困难重重。

**Comment by wangzhen-fit2cloud** [comment]
你好，1.11.3 解决了这个问题，请问你现在用的是什么版本呢？

**Comment by tanxiao133** [comment]
> 你好，v1.11.3 解决了这个问题，请问你现在用的是什么版本呢？

验证了一下，确实11.3解决了控制台无法输出错误信息的问题~但是jar包内使用System.out.println打印的内容没有打印在控制台上~之前的版本是可以滴~

**Comment by zyyfit** [comment]
> > 你好，v1.11.3 解决了这个问题，请问你现在用的是什么版本呢？
> 
> 验证了一下，确实11.3解决了控制台无法输出错误信息的问题，但是jar包内使用System.out.println打印的内容没有打印在控制台上，之前的版本是可以滴

现在控制台打印是使用 log.info();
