### ISSUE TITLE
[BUG] 测试用例页面鼠标滑动到测试用例就直接跳出弹框，交互有问题

### ISSUE THREAD

**Issue by cl-leichen** [metersphere/metersphere#570]
**MeterSphere 版本**
v1.4.0-rc1

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  进入测试用例，鼠标滑动到测试用例会跳出弹窗，不太合适。
2. 
3. 
4. 

**期待的正确结果**
这个场景不合适应该要，最好是点击，不然总是会误操作到，然后要点击x关闭，非常麻烦。不好用

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/58057327/96680297-d3deeb00-13a7-11eb-8cc5-4a0db712d341.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请升级到 1.4.0 后验证下该问题是否还存在。如果问题还存在请重新开下该 issue
