### ISSUE TITLE
[BUG]测试用例 把所有模块删除后 在去回收站删除用例  然后模块位置会显示-1

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5710]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.11.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试用例 把所有模块删除后 在去回收站删除用例  然后模块位置会显示-1
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![微信图片_20210826100132](https://user-images.githubusercontent.com/83771182/130888268-5cefa1c3-8ce9-4e88-975d-a8ddc92d9fcd.png)

**Comment by xulinde** [comment]
使用最新版本未复现该问题，您用的是哪个版本

**Comment by yaoyi111** [comment]
应该是1.11.3版本



***@***.***
 
发件人： xulinde
发送时间： 2021-08-30 18:56
收件人： metersphere/metersphere
抄送： yaoyi111; Author
主题： Re: [metersphere/metersphere] [BUG]测试用例 把所有模块删除后 在去回收站删除用例 然后模块位置会显示-1 (#5710)
使用最新版本未复现该问题，您用的是哪个版本
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
v1.12.2仍未复现
