### ISSUE TITLE
[BUG]选择模块后，在右侧列表选择所有数据，数据条数不正确，且为上一次选择模块下的条数。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5711]
**MeterSphere 版本**
1.11.3

**Bug 描述**

选择模块后，在右侧列表选择所有数据，数据条数不正确，且为上一次选择模块下的条数。

**Bug 重现步骤**

测试步骤：
1、点击状态获取模块，右边场景列表中显示4条场景。
2、点击MediaServer模块，右边场景列表依然显示4条。
3、再次点击MediaServer模块，右边显示正确的68条。

**期待的正确结果**

**截图**

![企业微信截图_16299440556566](https://user-images.githubusercontent.com/87106917/130889238-9f86e4de-b4bc-4d93-92ec-ccef3c2eadf9.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
