### ISSUE TITLE
如何确保对load_test_report_detail的写入顺序呢？

### ISSUE THREAD

**Issue by waitshang** [metersphere/metersphere#572]
我看了一下，对load_test_report_detail的写入顺序是ms-server端同步请求启动DockerEngine，启动后ms-server端写入一条load_test_report_detail记录，后续的对load_test_report_detail的写入发生在data-streaming中，如何确保DockerEngine启动后data-streaming端写入的操作不会发生在ms-server端之前？

**Comment by liuruibin** [comment]
ms-server 插入一条初始值，并生成load_test_report记录之后启动测试，后续测试数据上传到kafka，data-streaming通过消费者模式获取到测试结果，不存在data-streaming写入在ms-server之前的情况。

**Comment by waitshang** [comment]
> ms-server 插入一条初始值，并生成load_test_report记录之后启动测试，后续测试数据上传到kafka，data-streaming通过消费者模式获取到测试结果，不存在data-streaming写入在ms-server之前的情况。
![image](https://user-images.githubusercontent.com/11643284/96701194-e6b2e900-13c2-11eb-9ca7-a525ea1c60dd.png)
代码中的逻辑如图所示，我表示对report_detail的生成顺序仍有疑问。

**Comment by waitshang** [comment]
> ms-server 插入一条初始值，并生成load_test_report记录之后启动测试，后续测试数据上传到kafka，data-streaming通过消费者模式获取到测试结果，不存在data-streaming写入在ms-server之前的情况。
![image](https://user-images.githubusercontent.com/11643284/96701194-e6b2e900-13c2-11eb-9ca7-a525ea1c60dd.png)
代码中的逻辑如图所示，我表示对report_detail的生成顺序仍有疑问。

**Comment by waitshang** [comment]
@liuruibin
