### ISSUE TITLE
[BUG]测试跟踪-测试用例-批量编辑，自定义字段无法批量编辑

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#5726]
**MeterSphere 版本**
>V1.11
**Bug 描述**
测试跟踪-测试用例-批量编辑，更新用例属性下拉框内容重复，更新后的属性值只是下拉列表框，自定义属性很多是文本框等其它格式，无法实现批量编辑

**Comment by zyyfit** [comment]
您好，属性下拉框重复的问题会在后续版本修复，目前批量编辑只支持几个特定的字段，不支持所有字段，后续版本可能会考虑支持

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
