### ISSUE TITLE
[BUG]接口数据填写完成，点击保存并执行按钮，偶尔会出现 接口没更新，还是旧数据的情况

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#573]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.1-b875
**Bug 描述**
简要描述您碰到的问题
接口数据填写完成，点击保存并执行按钮，偶尔会出现 接口没更新，还是旧数据的情况
**Bug 重现步骤**
1.  填写接口
2. 点击保存并执行按钮
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
点击保存并执行按钮，可更新最新的接口数据

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
具体是哪些地方没更新？添加断言提取吗？断言和提取需要点击Add添加才会生效，请确认下是不是这个问题，谢谢

**Comment by Sylvie1222** [comment]
是接口的请求参，内容，断言，提取等信息全部都没有更新，相当于点击保存并执行按钮，保存功能没有起作用。这个场景是偶尔发生的，不是必现

**Comment by AgAngle** [comment]
你好，我们测试没遇到你这种情况，您看看能不能稳定复现，如果可以复现，还麻烦描述一下步骤，重新打开 issues ，十分感谢！

**Comment by Sylvie1222** [comment]
当前是不能稳定复现的，但团队很多人都反馈了这个问题
