### ISSUE TITLE
[BUG]测试用例列表中，同一用例多次打开时，会出现多个tab，且每个tab都可以编辑保存。保存后，系统保存最后一次编辑的内容。很容易造成数据冲突或覆盖。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#5744]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
v1.12
您所使用的 MeterSphere 版本是？

**Bug 描述**
[BUG]测试用例列表中，同一用例多次打开时，会出现多个tab，且每个tab都可以分别编辑保存。保存后，系统会保存最后一次编辑的内容。
很容易造成数据冲突或覆盖。
简要描述您碰到的问题

**Bug 重现步骤**
<img width="853" alt="1" src="https://user-images.githubusercontent.com/71361375/130928821-ea46bb44-3ca9-4018-87af-bf5fab0dd998.png">
<img width="826" alt="2" src="https://user-images.githubusercontent.com/71361375/130928842-dc0eefb2-2efe-4e1e-800d-4a04165a37b5.png">
<img width="814" alt="3" src="https://user-images.githubusercontent.com/71361375/130928855-935ddd9d-037a-4d09-bc24-2fba880ac08a.png">
<img width="829" alt="4" src="https://user-images.githubusercontent.com/71361375/130929069-7410e3f8-90d3-4773-a6d4-3ff2fcebcc9e.png">

**期待的正确结果**
1、同一用例，应只允许打开一个tab页。当重复打开时，直接跳转到正在打开的用例tab，而非再打开一个tab。

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，后面版本可以优化下

**Comment by zyyfit** [comment]
最新版1.14.3已修复
