### ISSUE TITLE
之前的jenkins接口调用任务通知，现在去那里设置

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#5749]
**请描述您的问题.**
现在1.12.0没有找之前的jenkins接口调用任务通知
![image](https://user-images.githubusercontent.com/66474661/130940680-78df7f98-e4c3-486f-b4d5-1268328c3d55.png)

**Comment by xulinde** [comment]
可以设置接口/性能执行结果事件，通过jenkins触发完成，就会发通知
![image](https://user-images.githubusercontent.com/64065190/131308428-905be240-91cc-49fa-bde9-c3c64008b2d7.png)

**Comment by hu-shuli** [comment]
设置了执行失败和执行成功都收不到邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 之前的jenkins接口调用任务通知，现在去那里设置 (#5749)





 
可以设置接口/性能执行结果事件，通过jenkins触发完成，就会发通知
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 设置了执行失败和执行成功都收不到邮件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年8月30日(星期一) 下午4:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 之前的jenkins接口调用任务通知，现在去那里设置 (#5749) 可以设置接口/性能执行结果事件，通过jenkins触发完成，就会发通知 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

1.12.0版本如果jenkins的用户key和消息接收是一个人的话，暂时收不到通知，下个小版本将会优化这个问题

**Comment by hu-shuli** [comment]
我设置了两个用户，都没收到，jenkins的用户key和消息接收人不是一个人，jenkins用户key是admin，消息接收是另一个用户


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 之前的jenkins接口调用任务通知，现在去那里设置 (#5749)





  
设置了执行失败和执行成功都收不到邮件
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" @.&gt;; 发送时间:&nbsp;2021年8月30日(星期一) 下午4:17 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 之前的jenkins接口调用任务通知，现在去那里设置 (#5749) 可以设置接口/性能执行结果事件，通过jenkins触发完成，就会发通知 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
1.12.0版本如果jenkins的用户key和消息接收是一个人的话，暂时收不到通知，下个小版本将会优化这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
最新版已增加Jenkins任务通知，已修复收不到消息的问题
