### ISSUE TITLE
[BUG]应用系统发版后，在平台上跑其接口，全部报500

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#575]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.1-b875

**Bug 描述**
简要描述您碰到的问题
应用系统发版后，在平台上跑其接口，全部报500，在postman上可以跑成功。需要等待一段时间后，该平台上的接口才能正常跑通

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70245535/96806046-9b8dea00-1445-11eb-885b-25e473efcd52.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问后端被测系统的部署架构是怎样的？这个看起来不像是我们这边的问题引起的。

**Comment by wangzhen-fit2cloud** [comment]
你好，请问该问题还存在吗？如果问题还存在请重新开下该 issue
