### ISSUE TITLE
[BUG]权限问题：用户组和权限只配置缺陷相关权限，无法查看

### ISSUE THREAD

**Issue by heshaol** [metersphere/metersphere#5753]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用户组和权限只配置缺陷相关权限
2. 配置用户权限后，登录不展示缺陷页面
3. 再加上查看用例权限后，显示了测试跟踪相关的首页、测试用例、缺陷、报告 4个页面

**期待的正确结果**

正确情况下应该是什么样的？
根据配置的权限显示相关页面

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/72126159/130966796-719d1dac-d813-454c-96d9-7ee1b1577ba7.png)
![image](https://user-images.githubusercontent.com/72126159/130966912-9fd624fb-0be2-4af2-9153-6204cb613ee3.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
