### ISSUE TITLE
权限控制BUG

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#5754]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.12
**Bug 重现步骤**
1.设置缺陷管理员权限，只赋予了缺陷管理权限
![image](https://user-images.githubusercontent.com/30932762/130971331-0b6046be-6dfa-4f54-8aec-4c30b62787cc.png)
2.创建用户，赋予此权限组
![image](https://user-images.githubusercontent.com/30932762/130971426-4c6681ae-6af5-4acd-a343-178fa6dd3efe.png)
3.账号登陆后，查看不到任何菜单
![image](https://user-images.githubusercontent.com/30932762/130971700-3e6c17a1-3d32-4793-b82f-3252e24139a5.png)
4.给此用户加上用例查看权限，然后在登陆，发现可以查看首页，可以批量删除报告
![image](https://user-images.githubusercontent.com/30932762/130973059-ab4aba12-af0a-40dd-880f-3cbb37754890.png)
![image](https://user-images.githubusercontent.com/30932762/130973208-21ff2463-460e-447c-b553-6a5e651fedf2.png)
![image](https://user-images.githubusercontent.com/30932762/130973257-bbc9b932-8722-4b5c-be1c-28a55e59e2cc.png)

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/5753

**Comment by xulinde** [comment]
重复 #5753
