### ISSUE TITLE
[BUG]接口定义中的case，无法使用form-data上传文件，报错文件找不到

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#5755]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**
接口定义中的case，无法使用form-data上传文件，报错文件找不到
![image](https://user-images.githubusercontent.com/77233754/131058894-07755b2c-150e-460d-a797-11f80c47eae1.png)

简要描述您碰到的问题
无法使用form-data上传文件，报错文件找不到，在postman里可以成功上传
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by lishushi-310** [comment]
您好：


1、我这边使用的版本：


2.具体是使用ms往阿里云服务器上传文件会报错 找不到文件，但是使用postman就能正常上传
ms的上传的相关参数如下：
（1）headers


（2）请求体


（3）接口响应






确认问题后，还请及时联系下我，这边着急用，谢谢了！






| |
李姝适
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年8月31日 ***@***.***> 写道：

您好，请问您使用的是哪个版本呀？我没有复现出来，能再详细描述一下操作步骤吗？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 您好： 1、我这边使用的版本： 2.具体是使用ms往阿里云服务器上传文件会报错 找不到文件，但是使用postman就能正常上传 ms的上传的相关参数如下： （1）headers （2）请求体 （3）接口响应 确认问题后，还请及时联系下我，这边着急用，谢谢了！ | | 李姝适 | | ***@***.*** | 签名由网易邮箱大师定制 在2021年8月31日 ***@***.***> 写道： 您好，请问您使用的是哪个版本呀？我没有复现出来，能再详细描述一下操作步骤吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

您好，您回复的内容这边看不到，您可以加入企业微信交流群，方便我们及时响应和远程协助排查问题
![图片](https://user-images.githubusercontent.com/73461316/131656019-b6438911-9b0d-42d2-8477-5c8651433d2a.png)
