### ISSUE TITLE
测试计划发送邮件能够聚合结果

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#5765]
**请描述您的需求或者改进建议.**
1.测试计划邮件通知，测试计划关联了多个接口测试场景，发送邮件时可以通知整体测试情况，而并非把每个场景都用邮寄通知。

**请描述你建议的实现方案**
更好的发送是测试计划配置发送邮件是聚合邮件和每个场景或者性能测试都发送邮件

**Comment by xulinde** [comment]
通知时间是通过这里设置的吗，执行完是会发聚合报告的
![image](https://user-images.githubusercontent.com/64065190/131329385-b5c88190-ea6e-4e80-8364-3991c2601be0.png)
