### ISSUE TITLE
[BUG]用例中的缺陷列表乱序

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#5766]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
![image](https://user-images.githubusercontent.com/44960709/131079985-e65dda5f-5093-4c18-9a93-d33e3adaaf3d.png)

**Bug 描述**
用例中的缺陷列表乱序

**Bug 重现步骤**

1.  增加多一点的缺陷
2. 出现乱序
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
可按照更新时间排序或者按照id排序
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44960709/131079823-998fbefc-2f8a-47c5-878a-28fba480993d.png)

**Comment by xulinde** [comment]
v1.13已支持自定义排序
