### ISSUE TITLE
[BUG] 1.12.0测试计划执行后生成的测试报告数据不对

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#5770]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**
测试计划执行后生成的测试报告数据不对
简要描述您碰到的问题
生成的测试报告数据和实际理论数据不一致，测试报告拿的数据不对（个人感觉取的是前面几次执行结果数据）
**Bug 重现步骤**

1.  清理测试垃圾（不清测试数据，测试计划里面有部分接口执行会失败）
2. 执行测试计划
3. 等待一段时间（让测试计划执行完成），再次执行测试计划
4. 查看两次执行测试报告，（测试结果是一样的）

**期待的正确结果**
正常情况，第一次执行的结果全部通过；第二次执行后的结果是部分不通过

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问能稳定复现吗？我没有复现这个问题，或者您的测试计划都关联了什么用例呢？有没有什么特别的配置？

**Comment by hu-shuli** [comment]
可以啊，你手动去测试计划里面执行一条用例，让他执行失败，然后再去执行测试计划，发现测试报告里面的数据就显示那条数据执行失败了，
观察测试计划里面的用例执行情况，发现用例的执行时间与测试计划的执行时间对不上，个人怀疑测试报告里面的数据是直接取的测试计划里面用例的执行情况，没有取测试计划的直接执行结果


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 凌晨1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG] 1.12.0测试计划执行后生成的测试报告数据不对 (#5770)





 
您好，请问能稳定复现吗？我没有复现这个问题，或者您的测试计划都关联了什么用例呢？有没有什么特别的配置？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
您好，我还是没有复现，第一次在测试计划里执行了一个场景，执行结果如下
![图片](https://user-images.githubusercontent.com/73461316/131634282-a0ac4e02-1afd-4715-9a24-4e2e5cd19754.png)


然后执行了整个测试计划，执行结果如下
![图片](https://user-images.githubusercontent.com/73461316/131634977-5ef6b351-93ab-483c-9b92-ef14baf96573.png)

**Comment by hu-shuli** [comment]
我的是1.12.0版本，还有不是场景测试用例，就是测试计划里面的用例


测试计划里面用例执行的结果时间

测试计划执行的时间



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG] 1.12.0测试计划执行后生成的测试报告数据不对 (#5770)





 
您好，我还是没有复现，第一次在测试计划里执行了一个场景，执行结果如下
 
 
然后执行了整个测试计划，执行结果如下
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
好的，复现了，感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.13.0已修复

**Comment by zyyfit** [comment]
1.13.0已修复
