### ISSUE TITLE
[FEATURE]郵件設置指定發件人

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#5777]
**请描述您的需求或者改进建议.**
    建議郵件設置支持指定發送人，當前如果郵件服務器賬戶不包含@的時，默認是使用郵件主機服務器第一個.後面做為domainName ，最後發送人格式：用戶名@domainName，但是這種郵件格式是不存在的，導致發送郵件報錯：
    如：郵件主機服務器：non-business.mail.corp.com，賬戶：mail100000000，此時發件人默認是：mail100000000@mail.corp.com，這種格式郵件不存在
    Caused by: org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
        com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <appmail100000000@mail.corp.com>: Sender address rejected: Access denied

    代碼：
     if (javaMailSender.getUsername().contains("@")) {
                    helper.setFrom(javaMailSender.getUsername());
                } else {
                    String mailHost = javaMailSender.getHost();
                    String domainName = mailHost.substring(mailHost.indexOf(".") + 1, mailHost.length());
                    helper.setFrom(javaMailSender.getUsername() + "@" + domainName);

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。
