### ISSUE TITLE
[BUG]断言规则中，脚本示例执行异常，示例代码不正确

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#5787]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

v1.12

**Bug 描述**

简要描述您碰到的问题

断言规则中，脚本示例执行异常，示例代码不正确

**Bug 重现步骤**

1.  创建断言，选中脚本方式，进行编辑
2.  脚本选择python语言
3. 配置判断条件，查看自动生成的示例
4. 保存并执行，查看断言信息

**期待的正确结果**

正确情况下应该是什么样的？
示例代码中AssertionResult.setFailure(true)中的true应为大写True

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/34565342/131255778-22180a6b-a6d0-4387-93aa-48df7a4d6bf3.png)
![image](https://user-images.githubusercontent.com/34565342/131255824-1a7a4544-c931-47e1-9b70-c1d7f45e22a9.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.1已修复
