### ISSUE TITLE
[BUG]接口定义使用swagger URL导入，导入成功之后的接口未对deleted状态的接口定义进行区分

### ISSUE THREAD

**Issue by PIDAN524** [metersphere/metersphere#5789]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.8

**Bug 描述**
swagger URL导入接口定义未过滤deleted状态的接口定义

**Bug 重现步骤**

1.接口定义使用swagger URL导入 
2.swagger url 接口定义文档中存在deleted状态的接口定义
3.metersphere导入成功之后存在 deleted状态的接口，且和其他接口无任何差别区分

**期待的正确结果**

metersphere 不必导入deleted状态的接口定义，或者对于deleted状态的接口定义做一个标签区分

**截图**

![image](https://user-images.githubusercontent.com/54307955/131277733-3dbaa626-b9c7-427a-adcc-6ab706c578bc.png)
![image](https://user-images.githubusercontent.com/54307955/131277881-bac47c16-caff-49bb-b755-5ae50dcecb75.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先讨论一下解决方案

**Comment by AgAngle** [comment]
1.12.2 版本优化，弃用的接口打上Deleted标签
