### ISSUE TITLE
[BUG]任务中心没有显示手动触发执行的测试用例

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#5792]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**
手动执行测试计划，任务中心测试没有显示测试用例执行记录
简要描述您碰到的问题
任务中心手动触发用例执行记录列表为空
**Bug 重现步骤**

1.  选择一个测试计划点击执行
2. 点击任务中心按键
3. 选择筛选条件“手动触发”，查看用例执行情况
4. 

**期待的正确结果**
任务中心能够完整的显示，手动执行触发测试用例的执行情况
正确情况下应该是什么样的？

**截图**
点击执行测试计划
![image](https://user-images.githubusercontent.com/66474661/131279227-27be08eb-3ffe-4d0d-b3b7-01d5884dd452.png)
点击任务中心
![image](https://user-images.githubusercontent.com/66474661/131279138-b9c9a75d-1e5e-4ce0-bce5-4018846973ea.png)
选择过滤条件手动触发
![image](https://user-images.githubusercontent.com/66474661/131279179-639a1667-3266-4e8e-a39b-423b0a925358.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题，你是使用的最新版本吗，是否能稳定复现
![image](https://user-images.githubusercontent.com/64065190/131329249-097ca77d-4047-46c0-845c-bf4853d3d433.png)

**Comment by hu-shuli** [comment]
我这可以复现啊，我这是1.12.0的，是最新的版本啊，我感觉你们都没用心测，单子上都有明确的描述


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
未复现该问题，你是使用的最新版本吗，是否能稳定复现
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
我们确实是按照您的描述来复现的，您的测试计划里是不是没关联接口/场景用例，只有功能用例的话，任务中心是不会显示的

**Comment by hu-shuli** [comment]
是只有功能，没有场景，为什么不显示啊，这不合常理啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
我们确实是按照您的描述来复现的，您的测试计划里是不是没关联接口/场景用例，只有功能用例的话，任务中心是不会显示的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
目前就是这样设计的哦～

**Comment by hu-shuli** [comment]
为什么我看见上一个版本是有的啊，那为什么批量操作有记录呢，其他几个都没记录了，你们这设计……
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
目前就是这样设计的哦～
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
批量操作有记录，也必须是测试计划有关联接口/性能用例才行

**Comment by hu-shuli** [comment]
手动执行也是和测试计划关联了，api，定时任务都是关联了测试计划；任务中心都没有执行记录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
批量操作有记录，也必须是测试计划有关联接口/性能用例才行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
只要您测试计划里有接口/性能用例，不管哪种触发方式，任务中心都会记录的～

**Comment by hu-shuli** [comment]
现在就是只有批量执行的，其他三种都没有


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
只要您测试计划里有接口/性能用例，不管哪种触发方式，任务中心都会记录的～
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
升级到最新版本还有此问题吗

**Comment by hu-shuli** [comment]
没有了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]任务中心没有显示手动触发执行的测试用例 (#5792)





 
升级到最新版本还有此问题吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
