### ISSUE TITLE
[FEATURE] 性能测试报告的链接中带空间名字等信息，确保链接点进去可以查看

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5796]
**请描述您的需求或者改进建议.**

性能测试报告的链接中带空间名字等信息，确保链接点进去可以查看

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
