### ISSUE TITLE
[FEATURE] 希望性能测试报告可以增加链接分享功能

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#5797]
**请描述您的需求或者改进建议.**

希望性能测试报告可以增加链接分享功能

**请描述你建议的实现方案**

**Comment by seasoncool** [comment]
支持下，这个报告分享功能太重要了。
无需登录，即可打开，分享出的各种报告。

**Comment by seasoncool** [comment]
已经有了。

![image](https://user-images.githubusercontent.com/6467295/131298302-3ec830e6-93bf-4cc4-9a01-e0a2c964496e.png)

**Comment by seasoncool** [comment]
顶顶顶！

**Comment by xulinde** [comment]
后面版本会支持

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
