### ISSUE TITLE
[BUG]提取值为含有反斜杠的内容，赋值后，发现会被转义成正常的json格式，不是按照提取格式为什么赋值就是什么。

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#581]
**MeterSphere 版本**
1.3.1

**Bug 描述**
提取值为含有反斜杠的内容，赋值后，发现会被转义成正常的json格式，不是按照提取格式为什么赋值就是什么。

**Bug 重现步骤**
1.  接口提取返回值，返回值为含有反斜杠的字符格式。
![image](https://user-images.githubusercontent.com/53041390/96851389-8d15f180-148a-11eb-976e-c2d4ab4ccd55.png)

2. 赋值到下一个接口后，格式变成标准的json格式
![image](https://user-images.githubusercontent.com/53041390/96851500-ac148380-148a-11eb-8b1e-d398f376b538.png)

3. 
4. 

**期待的正确结果**
应该提取的内容是什么格式的，赋值到其他接口时也是什么格式的

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
JSONpath 提取会自动转义，这种情况，请用正则提取吧
