### ISSUE TITLE
【bug】v1.10.5-lts-678b9a6a 版本，接口定义中接口用例的变更历史加载需要1min左右，很慢

### ISSUE THREAD

**Issue by lishushi-310** [metersphere/metersphere#5822]
![image](https://user-images.githubusercontent.com/77233754/131430906-d0de0f56-b61e-40d2-8154-564a6f7f6af5.png)

点击完变更历史，会在这个页面加载比较久的时间。

**Comment by xulinde** [comment]
升级到v1.10.9-lts版本还有此问题吗

**Comment by lishushi-310** [comment]
你们的公开demo，版本都 v1.12.0-a8cbf128  也有这个问题，是你那个版本没有复现吗？


怎么这么轻易关闭bug


https://demo.metersphere.com/#/api/definition






| |
李姝适
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年8月31日 ***@***.***> 写道：

升级到v1.10.9-lts版本还有此问题吗

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
