### ISSUE TITLE
[BUG]请求头在多个地方配置后会重复添加

### ISSUE THREAD

**Issue by 13072124817** [metersphere/metersphere#5827]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.0-a8cbf128

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  设置全局变量Authorization
2. 接口请求头上设置Authorization，不通知
3. 接口运行时，获取到2个Authorization，接口报400

4. 测试计划运行后，邮件模块错误

**期待的正确结果**
接口运行时，请求头中未配置Authorization，获取全局变量中；
请求头中配置Authorization，只获取接口请求头中的Authorization；

正确情况下应该是什么样的？

**截图**
接口运行报错截图
![image](https://user-images.githubusercontent.com/82364618/131447709-b9f1ecd8-c926-4dfd-b8ab-359ca908fd5d.png)
![image](https://user-images.githubusercontent.com/82364618/131447764-2794263a-45f7-47d9-91d1-69ae1a25d83b.png)
![image](https://user-images.githubusercontent.com/82364618/131447765-2e07d156-fe35-4156-b687-520ae8ac16b0.png)

邮件模板：
![image](https://user-images.githubusercontent.com/82364618/131448156-7db9b1b7-eb8f-4384-832c-9256b919882e.png)

实际收到邮件
![image](https://user-images.githubusercontent.com/82364618/131448107-7c11a9a3-2c65-4619-8bca-d31b13e1e4e2.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的，如果您配置了多个请求头的话会重复添加，后面可以优化一下这个问题

**Comment by weishuo6** [comment]
遇到同样的问题了，之前1.11是好的，升级之后现在接口都不同了，希望能尽快修复下。不然请求头里带Authorization、token这种认证的接口都不通

**Comment by xulinde** [comment]
1.12.1已修复
