### ISSUE TITLE
[BUG]测试计划后邮件、微信通知始终为成功

### ISSUE THREAD

**Issue by five3** [metersphere/metersphere#5829]
**MeterSphere 版本**
>v1.12

**Bug 描述**

测试计划后邮件、微信通知始终为成功。即使测试计划中有失败的用例

**Bug 重现步骤**

1.  创建一个包含失败用例的测试计划
2.  设置定时任务并配置邮件通知
3.  执行测试计划
4.  收到邮件提示测试执行成功

**期待的正确结果**

收到的测试计划执行结果应该为失败。
具体原因是因为 test_plan_report_data.failur_test_cases字段统计的失败用例始终为0，导致统计结果一直是成功

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现这个问题，您这边是哪个版本
![image](https://user-images.githubusercontent.com/64065190/131481823-b9f7ec3b-b9cd-4fa8-b1a3-5ac0d6fcd1db.png)

![image](https://user-images.githubusercontent.com/64065190/131481857-1a302033-3426-482e-a910-e9144f6708f1.png)
