### ISSUE TITLE
[FEATURE]建议接口测试增加csv配置文件和循环次数

### ISSUE THREAD

**Issue by wangchy0927** [metersphere/metersphere#583]
**请描述您的需求或者改进建议.**

在接口测试中经常需要初始化一堆数据，比如100个用户，建议接口测试增加csv配置文件和循环次数

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，最新版本应该可以满足您的需求，您可以升级到最新版本体验下
![image](https://user-images.githubusercontent.com/64065190/107309492-8062eb00-6ac5-11eb-9115-20774f120785.png)
![image](https://user-images.githubusercontent.com/64065190/107309523-8b1d8000-6ac5-11eb-878f-863f39f2a353.png)
