### ISSUE TITLE
[FEATURE]请问现在有全局的搜索项目的功能吗？ 因为有时候不太确定项目是在哪个组织、工作空间下，只能一个个的查看。

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#5839]
**请描述您的需求或者改进建议.**

请问现在有全局的搜索项目的功能吗？ 因为有时候不太确定项目是在哪个组织、工作空间下，只能一个个的查看。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前还没有哦

**Comment by zyy2721** [comment]
> 
> 
> 目前还没有哦

可以添加吗

**Comment by zyyfit** [comment]
> > 目前还没有哦
> 
> 可以添加吗

我们先调研一下需求
