### ISSUE TITLE
[BUG]无法录制到基于HTTP POST的上传文件操作

### ISSUE THREAD

**Issue by Ianthexiong** [metersphere/metersphere#584]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.1.0

**Bug 描述**
简要描述您碰到的问题
基于Chrome 72版本，使用MeterSphere录制HTTP页面流程，其中涉及到从本地加载excel附件，上传到服务器的操作时，录制后的jmx脚本中没有该附件（详见附件word文档）

**Bug 重现步骤**
1.  使用MeterSphere录制，录制中操作可以成功，但是回放时脚本失败，原因见附件word截图
2.  使用Jmeter5.1.1原生录制方法，在MeterSphere出问题的url请求中，可以录制到该文件上传信息，见附件word截图

**期待的正确结果**
正确情况下应该是什么样的？
见附件结果

**截图**
如果有截图，请附上截图.

[使用原生录制和MeterSphere问题20201023.docx](https://github.com/metersphere/metersphere/files/5427060/MeterSphere.20201023.docx)

**Comment by q4speed** [comment]
最新版chrome插件已增加记录上传文件操作。
