### ISSUE TITLE
[BUG]执行单个场景用例，每次直接展开的步骤里面，第二条始终都是显示 未执行，需要重新查看报告才显示正常

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#5840]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
    v1.12.0-a8cbf128
**Bug 描述**
    执行单个场景用例，每次直接展开的步骤里面，第二条始终都是显示 未执行，需要重新查看报告才显示正常

**Bug 重现步骤**
1.  在場景列表執行單個用例

**期待的正确结果**
1.  執行報告展示正確

實際展示的報告中每次都有一條步驟展示未執行，實際已執行成功

**截图**
![image](https://user-images.githubusercontent.com/37204403/131463239-c1c35456-3893-44bf-b456-e32457d9bd14.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问您的场景中是否有加入控制器之类的组件呢？或者是否有其他配置？
![图片](https://user-images.githubusercontent.com/73461316/131659543-bc011b5c-3c6f-43d6-9ae7-d1cbacf8ee1c.png)
