### ISSUE TITLE
[FEATURE]关于param参数变量是否可以支持jsonpath直接提取。暂时只是支持返回结果的提取。

### ISSUE THREAD

**Issue by chenbingjie-98** [metersphere/metersphere#5845]
**请描述您的需求或者改进建议.**
1.是否可以支持param参数的提取。
2.是否可以支持返回结果的全部提取

**请描述你建议的实现方案**

**Comment by chenbingjie-98** [comment]
只是建议

**Comment by xulinde** [comment]
感谢您的建议，我们先调研下

**Comment by luty2018** [comment]
非常抱歉现在才回复。
麻烦进一步描述你的需求， 目前这个描述我不太清楚你具体要解决什么问题。

**Comment by luty2018** [comment]
由于时间比较久， 如果您还有这个需求可以重新打开issue。
