### ISSUE TITLE
[BUG]目前Python语言的输出信息不能输出到控制台

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#5854]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

![image](https://user-images.githubusercontent.com/13564069/131499964-a350dedb-96c9-4d70-bb33-281853508fff.png)

**Bug 重现步骤**

1.  添加后置脚本
2. 选择Python
3. 输出信息
4. 执行，查看控制台日志

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by Ammyz** [comment]
目前是最新版本，1.12

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
使用 log.info() 方法打印
