### ISSUE TITLE
[BUG]创建的时候有选择自动更新状态，案例执行完状态不会更新已结束

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#5855]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？版本:   v1.12.0-a8cbf128

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
创建的时候有选择自动更新状态，案例执行完状态不会更新已结束

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/131594251-42c0376f-0cf8-4aa3-955b-69dee5c8c18a.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问测试计划里都关联了什么类型的用例呀？我再根据您的计划试一下
