### ISSUE TITLE
[BUG]接口测试-快速调试，删除接口请求失败，参数未自动带入请求接口中

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5856]
刘韩松 9-1 09:33:22
[自定义表情]

王萌萌 9-1 09:37:43
[自定义表情]

刘韩松 9-1 09:45:35
**MeterSphere 版本**1.12.0版本
**Bug 描述**

接口测试-快速调试，delete接口：http://ip:端口/VIID/Dispositions?IDList=1345675432454
删除失败，返回400Invalid Operation，请求接口中未包含IDList=1345675432454

**Bug 重现步骤**

1.  接口测试-快速调试，delete接口：http://ip:端口/VIID/Dispositions?IDList=1345675432454
删除失败，返回400Invalid Operation，请求接口中未包含IDList=1345675432454
2. 
3. 
4. 

**期待的正确结果**

**截图**

**Comment by zyyfit** [comment]
您好，没有复现这个问题
![图片](https://user-images.githubusercontent.com/73461316/131775792-72ee3db5-6125-405d-b48a-a15f2453f84a.png)

**Comment by liuhansong** [comment]
在快捷调试中delete  不是api接口定义里边-------- 原始邮件 --------发件人： zyyfit ***@***.***>日期： 2021年9月2日周四 11:15收件人： metersphere/metersphere ***@***.***>抄送： liuhansong ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [BUG]接口测试-快速调试，删除接口请求失败，参数未自动带入请求接口中 (#5856)

您好，没有复现这个问题

**Comment by zyyfit** [comment]
> 在快捷调试中delete  不是api接口定义里边-------- 原始邮件 --------发件人： zyyfit ***@***.***>日期： 2021年9月2日周四 11:15收件人： metersphere/metersphere ***@***.***>抄送： liuhansong ***@***.***>, Author ***@***.***>主 题： Re: [metersphere/metersphere] [BUG]接口测试-快速调试，删除接口请求失败，参数未自动带入请求接口中 (#5856) 您好，没有复现这个问题 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

您好，快捷调试也没有复现这个问题，您可以升级最新版1.14.0试试
![image](https://user-images.githubusercontent.com/73461316/139575242-59f88abd-35d7-404a-b61c-250986d0ca1f.png)
