### ISSUE TITLE
[BUG]请求内容，选择键值对，第一项选择FILE，就无法继续添加键值对了

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#586]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
请求内容，选择键值对，第一项选择FILE，就无法继续添加键值对了
**Bug 重现步骤**
1.  请求内容，选择键值对，第一项选择FILE，就无法继续添加键值对了
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望能继续添加键值对
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70245535/96954274-9f913900-1525-11eb-9e2c-93969d6252cd.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你们使用的是什么版本。在我们的环境中把第一行信息补充完整后会自动添加新行，未复现该问题。
