### ISSUE TITLE
[接口自动化]自动化场景处，添加批量新增请求头，断言操作

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#5862]
**请描述您的需求或者改进建议.**
场景中有些接口需要添加请求头信息或，基本断言，很多都是一样的断言，想批量修改

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
批量添加请求头，已支持
![image](https://user-images.githubusercontent.com/64065190/131770214-b185b69e-c5f9-4511-983e-4b836fddb47e.png)
