### ISSUE TITLE
[BUG]运行环境中显示为空

### ISSUE THREAD

**Issue by lczhuyeqing** [metersphere/metersphere#5868]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.11.1-0f3be78c

**Bug 描述**

简要描述您碰到的问题
![微信图片_20210901161516](https://user-images.githubusercontent.com/88369896/131636841-da5c3cb2-4122-488f-aa32-64dba83a08e5.png)

运行环境中显示为空

**Bug 重现步骤**

1.  打开一个窗口A
2. 新打开窗口B，把组织切换到别的组织去
3. 在窗口A中打开一个场景
4. 运行环境为空

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.12.0已经没有这个问题了，建议您升级到最新版使用
