### ISSUE TITLE
[QUESTION]如何在接口上传附件呢？

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#587]
**请描述您的问题.**
如何在接口上传附件呢？
我上传了一个附件，响应提示这不是multipart request格式
![image](https://user-images.githubusercontent.com/70245535/96955094-6659c880-1527-11eb-9e47-6f73de979d45.png)
![image](https://user-images.githubusercontent.com/70245535/96955033-3ca0a180-1527-11eb-92b0-ac748ddde90c.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，试一下在请求头里加一个 Content-Type=multipart/form-data 的请求头试一下？
如果还是不行的话可以等一下我们新发布的 1.4 版本再试下

**Comment by Sylvie1222** [comment]
还是不行哦
{
	"status": false,
	"data": null,
	"msg": "Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found",
	"code": 202,
	"reportTitleList": null,
	"errorList": null
}

**Comment by wangzhen-fit2cloud** [comment]
你好，请在新版本中验证该问题是否存在。我们将先关闭该问题，如果问题还存在请重新打开该问题。
