### ISSUE TITLE
[BUG]循环控制器的次数不支持变量

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#5872]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建循环控制器
2. 使用次数循环
3. 只能填写数字
4. 填写${变量}保存后，不能保存，变为0

**期待的正确结果**
![image](https://user-images.githubusercontent.com/88763608/131650495-5f1cb594-fbf6-4612-9f15-15eaf7f5a23f.png)
![image](https://user-images.githubusercontent.com/88763608/131650584-4e73ad6b-4b7f-42fc-a06a-08cc657713bf.png)

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前次数循环是只支持输入数字的，后续版本可能会考虑优化一下这个地方

**Comment by luty2018** [comment]
已支持，请更新版本使用。
