### ISSUE TITLE
如何配置jira集成，没看到相关文档

### ISSUE THREAD

**Issue by tinagongtester** [metersphere/metersphere#588]
![image](https://user-images.githubusercontent.com/54583220/96964759-9ad87f00-153d-11eb-81cd-837b6c33c0c7.png)
求助：可否给下指导？

**Comment by shiziyuan9527** [comment]
Jira software server 认证信息为 账号密码,如果是Jira software cloud 的认证信息为 账号+令牌(账户设置-安全-创建API令牌)，jira地址就是你们的服务器地址，问题类型和jira的事务类型中缺陷的名称保持一致
