### ISSUE TITLE
[BUG]测试计划的测试用例里关联了缺陷，在测试计划的测试用例里关闭了缺陷，但是缺陷管理中对应的缺陷id状态还是新建

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#5881]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**

简要描述您碰到的问题
测试计划的测试用例里关联了缺陷，在测试计划的测试用例里关闭了缺陷，但是缺陷管理中对应的缺陷id状态还是新建
**Bug 重现步骤**

1.  测试计划的测试用例里关联了缺陷，在测试计划的测试用例里关闭了缺陷，但是缺陷管理中对应的缺陷id状态还是新建
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
