### ISSUE TITLE
[接口测试]场景支持设置前一个场景执行完成后再开始执行。目前是1s启动一个场景进行执行，相当于并发执行，批量执行时不太友好

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#589]
**请描述您的需求或者改进建议.**

接口测试往往需要到用户的验证信息，或多个交互数据，一起执行时很难避免信息的冲突，所以希望支持前一个场景执行完成后再启动下一个场景
**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你那边使用的是什么版本？在最新的版本中我们已经把接口测试场景的执行顺序改为了按顺序执行
