### ISSUE TITLE
[FEATURE]测试计划关联测试用例时展示优先级信息

### ISSUE THREAD

**Issue by Michomzhudaisheng** [metersphere/metersphere#59]
**请描述您的需求或者改进建议.**
建议测试计划里面操作关联用例得时候，关联测试用例得弹窗可以顺便把用例得优先级捞出来展示一下，方便调用例出来做冒烟用例，

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 建议测试计划里面操作关联用例得时候，关联测试用例得弹窗可以顺便把用例得优先级捞出来展示一下，方便调用例出来做冒烟用例，
> 
> **请描述你建议的实现方案**

已规划，谢谢！

**Comment by luty2018** [comment]
1.1 版本已支持，请更新体验
