### ISSUE TITLE
[QUESTION]如何把登录接口的多个返回值（比token:A, authorization:B），拼接成一个新值（AB）作为全局变量调用呢？

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#590]
**请描述您的问题.**

如何把登录接口的多个返回值（比token:A, authorization:B），拼接成一个新值（AB）作为全局变量调用呢？

**Comment by Dyc2333** [comment]
可以在后置脚本中获取变量后进行字符串拼接，然后赋值给全局变量，前后置脚本功能的右侧有示例代码
