### ISSUE TITLE
[BUG]测试跟踪》首页》用例维护人 显示不正确

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#5902]
**MeterSphere 版本**
>V1.12.0

**Bug 描述**

excel导入用例后，测试跟踪》首页》用例维护人 显示不正确，并没有将导入用例的维护人贡献展示出来
查看后台数据，发现test_case表找中maintainer字段值为空，补充maintainer后，维护人贡献可显示。
bug出现原因，导入用例时，test_case没有insert maintainer

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
