### ISSUE TITLE
[FEATURE]关联jira问题

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#5904]
**请描述您的需求或者改进建议.**
测试跟踪》测试用例》测试用例编辑页面》关联测缺陷处，希望可以搜索到jira问题

**请描述你建议的实现方案**
实现直接关联jira现有缺陷，在jira中做相关插件，两个系统间关联，做到用例和问题相互有显示可直接跳转

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by luty2018** [comment]
目前企业版已经实现jira缺陷双向同步， 可以申请试用哈。
