### ISSUE TITLE
[BUG]请求参数没有默认自动勾选

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#591]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.1-b875
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  在场景里的请求头OR请求里的请求参数，请求头，请求内容（键值对）中，
2. 输入的参数和值后，左侧的框框没有自动勾选上
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
希望输入了参数和值后，左侧的框框默认自动勾选上
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/70245535/97066640-80f47600-15e9-11eb-95d9-0b54e6bc40f1.png)

![image](https://user-images.githubusercontent.com/70245535/97066627-6c17e280-15e9-11eb-9f9b-897bc906ec7f.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在我们环境中没有复现该问题，请 1.4.0 发布后升级下再试一下
