### ISSUE TITLE
[FEATURE]接口测试，希望支持单场景调试，而不是保存并运行

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#592]
**请描述您的需求或者改进建议.**
一次测试可以创建多个场景，希望可以单场景级别调试，有些依赖于上文请求的情况，一次一个接口的调试没法满足，每次串起来跑之后又要打开报告看情况，然后再回到编辑页面继续调整，不甚方便

**请描述你建议的实现方案**
在左侧列表中的场景栏的右侧展开菜单给个调试的菜单按钮，考虑到调试次数会比较频繁，可以考虑把这个按钮放在场景名的前面，这样可以少点击一层。

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by pcc426** [comment]
有类似的需求，希望能独立场景执行调试。
目前1.4版本还是仅支持一键多场景同时执行。。。

**Comment by xulinde** [comment]
您好，该需求已实现
![image](https://user-images.githubusercontent.com/64065190/107309361-409c0380-6ac5-11eb-8a88-31dcdd0db4ee.png)

**Comment by pcc426** [comment]
> 您好，该需求已实现
> ![image](https://user-images.githubusercontent.com/64065190/107309361-409c0380-6ac5-11eb-8a88-31dcdd0db4ee.png)

这个是单接口调试吧。。希望要的是针对单场景的调试。。。

**Comment by xulinde** [comment]
单场景也支持的哦
![image](https://user-images.githubusercontent.com/64065190/107320388-911e5b80-6adb-11eb-89d2-95e4fff8bc1c.png)
