### ISSUE TITLE
[BUG]【接口列表】修改接口的路径后未同步到对应的CASE路径里

### ISSUE THREAD

**Issue by shihuijuan712** [metersphere/metersphere#5928]
您所使用的 MeterSphere 版本是？
v1.10.5-lts-678b9a6a
**Bug 描述**
【接口列表】修改接口的路径后未同步到对应的CASE路径里
**Bug 重现步骤**

1.  接口测试--接口定义-接口列表API，点击编辑按钮
2. 修改接口路径
3. 检查该接口下的CASE路径
4. CASE路径未同步更新

**期待的正确结果**
修改接口的路径后同步到对应的CASE路径里

**Comment by zyyfit** [comment]
您好，1.10版还没有这个功能，1.12版有这个功能
