### ISSUE TITLE
[FEATURE]及时更新官方文档内容~

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#593]
**请描述您的需求或者改进建议.**
官方文档中关于新版本的诸如SQL，python等没有描述，很多刚接触的小伙伴不知道有这些功能呀，另外即使有这些功能，没有详细的文档和示例，还要一步一步探索出来，极大增加上手难度~，如果文档能及时维护就好啦！

**请描述你建议的实现方案**

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by wangzhen-fit2cloud** [comment]
你好，希望能进一步反馈下希望在文档中能看到哪些内容，或是否有建议、参考的文档组织形式，按我们现在的文档组织形式，感谢。

**Comment by Dyc2333** [comment]
比如以接口测试为例，希望能说明界面上各个配置和功能区域的功能，比如，对于SQL类型，解释一下变量提取和按列存储，其实只需要给个示例就可以。其实文档不及时更新的话，会给想上手的人一些阻碍的，看了文档，发现没有想要的功能，但实际上系统是有的，可能在这一步就流失了一个潜在的客户了。
这部分并不着急，按照官方的文档更新计划来即可。

**Comment by xuewuhe** [comment]
SQL的请求可以参考jmeter的jdbc request,meterSphere的测试引擎是jmeter
