### ISSUE TITLE
[BUG]多个测试多选后一键执行会报错，单个执行则正常

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#594]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.1-b97
**Bug 描述**
接口测试，我分别创建了测试ABCD，ABCD中有部分场景名称是一样的，写了一些断言，单独运行ABCD每一个都是全部正确，但是勾选ABCD测试批量运行，新创建了一个 X，X跑完就会有错
特别的，我发现错误集中在Oracle的SQL查询上，SQL语句串了，比如A中场景1的SQL跑到了B中场景2的SQL里。
我的接口命名中是含有变量的，比如“测试${tablename}数据行数”

**Bug 重现步骤**
1.  新建接口测试并配置环境，环境中使用了Oracle数据库
2. 创建测试A，新增SQL类型请求，新增HTTP类型请求，调试通过后保存
3. 从测试A复制而来测试B，修改B中SQL请求的表和字段，修改HTTP请求，调试通过后保存
4. 单独运行A和B，结果都是通过的
5.勾选AB，然后点击一键运行，发现B的SQL的内容跑到A里执行了，导致A出错

**期待的正确结果**
正确情况下应该是什么样的？
单独跑都正确，批量应该也正确才对，单个场景依赖与SQL上下文，但是整体来说各个场景是独立的
**截图**
如果有截图，请附上截图.
内网环境截图不方便提供，如有详细沟通需要可以在企业微信群或邮件进一步联系

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by AgAngle** [comment]
你好，合并后场景中的内容一般不会错乱，请问是不是因为都使用了变量 ${tablename}，冲突了？

**Comment by Dyc2333** [comment]
每个测试下包含四个场景，每个场景的命名并未使用变量且名称均不同，场景中的接口名称使用了变量，内容为 向${tablename}请求数据  和 请求${tablename}接口 这两个。如果是按照场景合并的话，不应该会错乱的才对。

另外，又发现一个问题，我的各个场景通过引用环境是已经配置了数据源的，批量执行自动创建的测试点进去，然后点击保存并执行，提示sql请求数据源不能为空，但实际上各个场景通过引用环境已经配置了数据源信息了，这里的检查是不是也有问题呢？
