### ISSUE TITLE
[QUESTION]接口测试，body内包含其它IP，无法测试成功（POSTMAN 可以）

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#5940]
**请描述您的问题.**

您好，我们有一个接口如 IP/testconnection，要去 做【连线】测试。
连线的地址如下图，我们放在body里面，它返回的错误也很奇怪。
（不是网络问题，换了2台机器都是这个情况）

![image](https://user-images.githubusercontent.com/6467295/131971317-4124196d-cfdd-4887-ab94-e69568e0ed4f.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，该问题看起来确实为网络问题，请问该问题是否解决了呢？
