### ISSUE TITLE
[BUG]接口参数中有空值的话，json-schema一下，就会变成乱码

### ISSUE THREAD

**Issue by lczhuyeqing** [metersphere/metersphere#5943]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  输入参数，如图
![QQ截图20210903170837](https://user-images.githubusercontent.com/88369896/131980623-e31f3e6a-6c2f-439b-9ffd-09c63b943c65.png)

2. dian点一下json-schema，格式变成如下：
![QQ截图20210903170919](https://user-images.githubusercontent.com/88369896/131980705-b67c7d04-3060-4ab4-be82-07d7d2565f9c.png)

2. 再点一下json-schema，格式变成如下：
![QQ截图20210903170946](https://user-images.githubusercontent.com/88369896/131980763-993867e6-0b1f-4a87-aa23-5c641b35f530.png)

3. 重新复制参数，删掉为空值的参数，如下：
![QQ截图20210903171036](https://user-images.githubusercontent.com/88369896/131980878-581a3f51-3ac3-44db-9777-4e4f98a05404.png)

4. 点一下json-schema，是正常的，
5. 再点一下json-schema，也是正常的

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
