### ISSUE TITLE
[QUESTION]对于接口测试来说，断言，提取，后执行脚本 这三个步骤的顺序是怎么样的

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#595]
**请描述您的问题.**

如题，对于接口测试来说，断言，提取，后执行脚本 这三个步骤的顺序是怎么样的，我目前试出来的是先执行提取，然后执行后执行脚本，最后是断言。如果是这样的话，界面上可以有所体现，或者在文档中告诉用户？（似乎也不是很必要，毕竟能试出来...）

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们可以现在文档中增加下相关的说明。
