### ISSUE TITLE
测试计划关联接口测试用例， 点击模块查询当前项目的所有接口测试列表为空

### ISSUE THREAD

**Issue by wangly0122** [metersphere/metersphere#5954]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

 v1.11.1-0f3be78c

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建接口测试
2. 新建测试计划
3. 在测试计划关联接口测试用例
4. 点击关联测试用例
5. 原本会出现需要关联的接口测试列表，但是现在没出现，始终为空列表
接口地址： http://192.168.2.5:8081/api/definition/list/relevance/1/10
查看了后台对应查询的sql地址：

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/37285439/132089337-a7d520e7-ed9a-45ec-8d06-fbf4fb1cc52f.png)
![image](https://user-images.githubusercontent.com/37285439/132089371-2a5c2b71-439a-43fc-b087-0a8f93c7e958.png)
![image](https://user-images.githubusercontent.com/37285439/132089383-2ea5e1c4-8ac5-4178-9354-d319569dbb98.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，关联接口用例的话需要接口定义有对应的case，您的接口现在有case吗？
