### ISSUE TITLE
[FEATURE]【急需!!!】接口测试，支持自定义变量的断言

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#596]
**请描述您的需求或者改进建议.**
希望断言的时候能够自由比较，目前断言的话，支持的值只能是当前请求的结果的各种提取，然后和一个变量或者文本值做对比.
我希望实现的是，接口请求完成后，可以由后执行脚本对数据进行预处理，将处理后的数据赋值给变量a，然后在断言的地方使用这个处理过的变量a和其他变量（比如之前步骤提取的变量）进行对比.

一个接口会返回一个json数组，这个数组结构略微复杂，中间某一层有一个交type_id的键，我想统计这个type_id的键出现了多少次。从而和上一步请求数据库后提取出来的结果行数进行一个判断，断言应该相等

**请描述你建议的实现方案**
其实只要断言中再多一个类型，自定义变量比较，就OK了.
也可以支持在jython中捕获AssertError但这样不利于统一管理，所以不是很建议。

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢反馈，目前计划在 1.4.1 版本中支持该功能
