### ISSUE TITLE
[BUG]场景中引用CASE无法直接拖拽到无子步骤的循环控制器下，设为子步骤。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5962]
**MeterSphere 版本**
1.12.1

您所使用的 MeterSphere 版本是？

**Bug 描述**

场景中引用CASE无法直接拖拽到无子步骤的循环控制器下，设为子步骤。

**Bug 重现步骤**

1.  创建空的循环体
2.  将单个引用的用例尝试拖动到循环体内 

**期待的正确结果**

可以拖拽

**截图**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
