### ISSUE TITLE
[BUG]引用的场景中添加一个复制的用例，执行的时候到这个位置就停住不往下执行了，保存时提示保存成功，但实际未保存。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#5963]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.12.1

**Bug 描述**

引用的场景中添加一个复制的用例，执行的时候到这个位置就停住不往下执行了，保存时提示保存成功，但实际未保存。

**Bug 重现步骤**

1、新建一个场景，在场景中添加一个引用场景
2、添加一个复制方式的用例
3、将复制用例拖入引用场景
4、执行，保存

**期待的正确结果**

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
