### ISSUE TITLE
[FEATURE]接口测试，支持变量来控制复杂流程，并且能够可视化

### ISSUE THREAD

**Issue by Dyc2333** [metersphere/metersphere#597]
**请描述您的需求或者改进建议.**
金融行业对于流程性接口的场景比较多，总会有丰富的上下文关系和条件判断来决定后续请求哪个接口，目前简单的变量控制不够直观，希望能控制复杂流程并实现可视化

**请描述你建议的实现方案**
可以使用可视化流程图类库结合自定义变量的方式，用户手动创建流程并指定变量，之后可以天机流程的环节去进一步填写接口信息，等，

diyuchen@esunny.cc
郑州易盛信息技术有限公司 测试中心 效能组 狄雨晨

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，流程可视化是个比较麻烦的功能，我们先内部评估下如何实现，具体版本规划待定。
