### ISSUE TITLE
[FEATURE]  多个试用客户相关优化需求

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#5979]
**请描述您的需求或者改进建议.**

1、安装的时候有选择是否分布式部署；把所有的服务安装在一个docker里而不是每一个都是一个docker；====安装部署特别困难，很多错误也没有相关文档，是否可以和jmeter一样，如果要做群压，则会配置和安装很多东西，否则就是最轻量级的安装。

2、错误提示，不直观，只是说失败，是否可以在提示中添加类似：“详情可查看日志，路径：***”。

3、在发压机上nodecontroller不能单独安装。====是否能提供只安装nodecontroller的安装包，目前提供的是整个MS安装包。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by zyyfit** [comment]
您好，我们虽然没有单独安装nodecontroller的安装包，但是可以单独安装nodecontaoller，您是希望有一个更小的只包含nodecontroller的安装包吗？

**Comment by huangxine** [comment]
目前安装MS服务端和安装nodecontroller是同一个安装包，需要修改一下配置文件。
这里需要最理想的结果：在MS服务端的资料配置里，设置了ip和端口号，能自动安装；
或者提供单独的nodecontroller的包进行安装，不需要修改任何配置文件，直接安装。

**Comment by liuruibin** [comment]
非常抱歉现在才回复。
安装包只有一个，您可以选择安装模式 MS_INSTALL_MODE=allinone 或者 node-controller
