### ISSUE TITLE
[QUESTION]SQL请求里的按列存储，这里是填写SQL查询出来的列名吗？

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#598]
**请描述您的问题.**
按列存储，这里是填写SQL查询出来的列名吗？
![image](https://user-images.githubusercontent.com/70245535/97078903-393e1080-1622-11eb-8bfd-96843a3b66cd.png)

**Comment by wangzhen-fit2cloud** [comment]
将查询结果指定列的值分派到变量当中去，例如在你发送的截图中，可以通过 ${ORGANIZATION_CODE_1} 这样的格式，引用返回结果的第一列第一行的值
