### ISSUE TITLE
[BUG]场景中新增步骤名不能编辑

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#5983]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.1
**Bug 描述**

场景中新增步骤名不能编辑

![wecom-temp-967d21031aa48c8203b2a6dde64bad7b](https://user-images.githubusercontent.com/10218415/132201487-d27f2ee9-486d-44f8-b92c-1bf666404bad.png)

**Comment by xulinde** [comment]
您用的哪个版本，我刚用v1.12.1未复现该问题

**Comment by congim** [comment]
我用的v1.12.1，源码checkout的编译的版本，你们Releases分支是不是又有问题

**Comment by xulinde** [comment]
我就是用release版本测试的，没有复现您说的问题

**Comment by congim** [comment]
那算了， 我直接关闭吧
