### ISSUE TITLE
[FEATURE] 在服务集成配置中为需求添加过滤可选项

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#5984]
**请描述您的需求或者改进建议.**
在像JIRA等第三方平台管理需求时，需求的粒度是逐渐细化的，有粒度大的Epic，Feature，最后细化分解到User Story。
它们之间的关系靠链接(link)来维护，形成“父子”关系。
同时，在研发过程中，大的Epic或Feature可能会对应到“项目”。

因此，建议在MS的“服务集成”进行配置时，为“需求”添加过滤可选项，即：
在需求类型中，再添加一个单选项“过滤”，选中后，管理员可以添加key/value作为过滤功能。

比如输入：parent=Epic-1，则只会将所有以Epic-1 为父亲的User Story查询出来，供MS关联。

**请描述你建议的实现方案**

**Comment by shenkaibo** [comment]
查询链接接口 可参考 
https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query-by-wiql?view=azure-devops-rest-6.0
例如：
https://dev.azure.com/kaibo0633/ms2/_apis/wit/wiql?api-version=6.0

Body 参数如下 ：
{
  "query": "SELECT [System.Id],[System.WorkItemType],[System.Title],[System.AssignedTo],[System.State],[System.Tags] FROM workitemLinks WHERE ([Source].[System.TeamProject] = @project AND [Source].[System.Id] = 155) AND ([System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Forward') AND ([Target].[System.TeamProject] = @project AND [Target].[System.WorkItemType] = 'Product Backlog Item') ORDER BY [System.WorkItemType],[System.Id] MODE (Recursive) "
}

响应结果如下：
{
    "queryType": "tree",
    "queryResultType": "workItemLink",
    "asOf": "2021-09-06T15:29:24.7Z",
    "columns": [
        {
            "referenceName": "System.Id",
            "name": "ID",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.Id"
        },
        {
            "referenceName": "System.WorkItemType",
            "name": "Work Item Type",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.WorkItemType"
        },
        {
            "referenceName": "System.Title",
            "name": "Title",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.Title"
        },
        {
            "referenceName": "System.AssignedTo",
            "name": "Assigned To",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.AssignedTo"
        },
        {
            "referenceName": "System.State",
            "name": "State",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.State"
        },
        {
            "referenceName": "System.Tags",
            "name": "Tags",
            "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.Tags"
        }
    ],
    "sortColumns": [
        {
            "field": {
                "referenceName": "System.WorkItemType",
                "name": "Work Item Type",
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.WorkItemType"
            },
            "descending": false
        },
        {
            "field": {
                "referenceName": "System.Id",
                "name": "ID",
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/fields/System.Id"
            },
            "descending": false
        }
    ],
    "workItemRelations": [
        {
            "rel": null,
            "source": null,
            "target": {
                "id": 155,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/155"
            }
        },
        {
            "rel": "System.LinkTypes.Hierarchy-Forward",
            "source": {
                "id": 155,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/155"
            },
            "target": {
                "id": 157,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/157"
            }
        },
        {
            "rel": "System.LinkTypes.Hierarchy-Forward",
            "source": {
                "id": 157,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/157"
            },
            "target": {
                "id": 158,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/158"
            }
        },
        {
            "rel": "System.LinkTypes.Hierarchy-Forward",
            "source": {
                "id": 155,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/155"
            },
            "target": {
                "id": 165,
                "url": "https://dev.azure.com/kaibo0633/_apis/wit/workItems/165"
            }
        }
    ]
}

**Comment by xyziven** [comment]
补充更新：
跟JIRA类似的平台，需求是逐层分解的，从Epic--Feature--User Story。Epic相对比较大，甚至可以对应到MeterSphere一个项目，按Epic-Feature->Story的层级进行对应和关联 ：
      a) Epic对应到项目（在MS服务集成里设），通过在集成配置里增加选项进行过滤，MS项目能与指定的Epic关联。
      b) 但是Epic下还有Feature，用例真正要关联的是Feature或User Story, 在关联用例时按Feature--> User Stroy的层级进行显示、组织和关联

**Comment by luty2018** [comment]
目前jira对接的功能已经插件化并开源了， 用户可以自行定制自己的查询需求哈。
