### ISSUE TITLE
[BUG]测试资源节点自动掉线

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#5987]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10.8-lts
**Bug 描述**
测试资源节点无缘无故掉线，需要在系统设置中重新启用。
具有随机性，系统会不定时自动禁用某个资源节点。
简要描述您碰到的问题

**Bug 重现步骤**

1.  新增资源节点
2.  在测试中使用节点
3.  系统自动禁用
4.  在系统设置中点击启用，可重新连接

**期待的正确结果**

非人为禁用某资源节点，系统不应该自动禁用

**截图**

![image](https://user-images.githubusercontent.com/88763608/132277680-dc86455b-d3ed-46ae-bf40-f7f8320c85dc.png)

**Comment by liuruibin** [comment]
在编辑测试或其他显示资源池选择的页面中会自动校验资源池的可连接性，当资源池不可用的时候会自动将状态修改成禁用。这样可以避免将测试发送到不可用的资源池上导致测试无法启动

**Comment by linfengjjj** [comment]
> 在编辑测试或其他显示资源池选择的页面中会自动校验资源池的可连接性，当资源池不可用的时候会自动将状态修改成禁用。这样可以避免将测试发送到不可用的资源池上导致测试无法启动

可用的资源池状态为什么会自动发生变化呢，自动禁用后再手动打开时可以的

**Comment by liuruibin** [comment]
只会自动禁用不会自动打开

**Comment by linfengjjj** [comment]
> 只会自动禁用不会自动打开

状态为什么会不稳定呢，可能有什么原因导致资源池不可用    既然可以手动打开，说明资源池是可用的吧

**Comment by liuruibin** [comment]
比如你的资源池重启了，在重启期间打开了编辑性能测试页面。这时候就会校验所有启用的资源池，资源池校验失败就会修改状态

**Comment by linfengjjj** [comment]
学到了 谢谢
