### ISSUE TITLE
[BUG]等待控制器实际等待时间比设置时间慢很多

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#5989]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

同样的场景，使用了等待控制器2000，比自定义脚本sleep(2000)  更慢

**Bug 重现步骤**

1.  自定义两个请求，记录总耗时
2.  增加等待控制器，记录总耗时
3.  增加自定义脚本，记录总耗时
4.  结果显示，自定义等待耗时比较准确，等待控制器耗时太久

**期待的正确结果**

等待控制器跟自定义脚本耗时应该基本差不多
![0932daf5c11af266bd49830daef58dd](https://user-images.githubusercontent.com/88763608/132280208-fe7df323-0e9f-4e37-9ab6-5c98bd175cd8.png)
![ec3661ec5c68fc2fc8ccc350f1390eb](https://user-images.githubusercontent.com/88763608/132280218-14443e58-e2d2-45f8-be2b-0143011e0728.png)
![a115a75f8d2b16c42f204b12ab13e43](https://user-images.githubusercontent.com/88763608/132280255-4202976c-9e2b-453a-ba76-2ebe8eef7c54.png)
![4b5e798b9ac7aae74a9a9dfbe5cd953](https://user-images.githubusercontent.com/88763608/132280279-1b51c5e0-5510-4edc-9e7e-b3688c63d1db.png)
![169f11590fbe6d09a2ae7e32d5401bc](https://user-images.githubusercontent.com/88763608/132280292-a5df1b73-f7e7-402f-820e-6413dc658c5f.png)
![94d511751c7273f77d4b952497282ec](https://user-images.githubusercontent.com/88763608/132280312-ca18004c-aab8-478b-9ea3-f29db868806c.png)

**Comment by zyyfit** [comment]
您好，我在1.10.9版本和1.12版本测试了一下，感觉虽然从开始点击到出报告整体还是比2m要多一点，但是没有这么慢了，而且执行完结果显示也已经正常了，建议您升级一下使用最新版

**Comment by linfengjjj** [comment]
> 等待控制器需要添加到特定请求的下级，与请求平级则所有请求都会进行等待。
> 同时我们这边会内置一些处理步骤，也会受等待时间影响，导致总体时间过长。

王工 如果等待控制器添加到特定请求的下级，那么等待时间只会影响该请求吗，内置的处理步骤不会受到影响？

**Comment by linfengjjj** [comment]
为什么使用脚本做等待，时间会更准确呢？
