### ISSUE TITLE
[BUG]多个步骤的场景测试，失败后继续，报告只显示成功的步骤，结果也显示成功

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#5992]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

失败后继续功能，现状是报告仅显示成功的步骤，且结果也显示成功

问题在于无法分析失败原因，且没有提示遇到的第一个报错信息
偶现的Bug,1.10.5-lts出现过，修复后，10.8-lts依然偶发

**Bug 重现步骤**

1.  执行场景，选择失败后继续
2.  场景中某个步骤失败
3.  偶现报告只显示成功的步骤，结果也显示成功

**期待的正确结果**

1、显示出遇到的第一个错误步骤
2、报告应该显示为失败，而不是成功

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
未复现该问题
