### ISSUE TITLE
[BUG]主机捕获节点机接口执行返回结果不正确

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#5993]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

主机捕获节点机接口执行返回结果，很慢。并发时会导致：
1、isRuning超时
2、捕获不到测试成功的状态，提示执行失败，但穿透url却显示成功

**Bug 重现步骤**

使用如下脚本获取状态：
meterSphereClient.getApiScenario(reportId)
public String getApiScenario(String id) {
    if (id.equals("") || id == null) {
        id = UUID.randomUUID().toString();
    }
    ResultHolder result = call(ApiUrlConstants.API_AUTOMATION_GET_API_SCENARIO + "/" + id.replace('"', ' ').trim());
    String listJson = JSON.toJSONString(result.getData());
    JSONObject jsonObject = JSONObject.parseObject(listJson);
    return jsonObject.getString("status");
}

**期待的正确结果**

1.正确捕获执行状态

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，已经修复了这个问题，会随着新版本一起发布的

**Comment by linfengjjj** [comment]
> 感谢反馈，已经修复了这个问题，会随着新版本一起发布的

谢谢 请问下新版本号和时间节点？

**Comment by xulinde** [comment]
v1.12.2已修复
