### ISSUE TITLE
[FEATURE]在测试用例的脑图中增加标签字段的显示和编辑功能

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#5994]
**请描述您的需求或者改进建议.**

期望在测试用例的脑图中增加标签tag的显示和编辑功能

**请描述你建议的实现方案**

在测试用例的脑图中增加标签的显示和编辑功能

**Comment by xulinde** [comment]
感谢您的建议，后面版本可以优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by luty2018** [comment]
https://github.com/metersphere/metersphere/issues/6698
重复issue，我们将关闭这个issue，您可以继续关注关联issue的跟进情况。
