### ISSUE TITLE
[BUG]测试计划中第二次关联测试计划，左边的测试模块不展示了。

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#5998]
您所使用的 MeterSphere 版本是？
v1.12.1
**Bug 描述**
测试计划中第二次关联测试计划，左边的测试模块不展示了。

**Bug 重现步骤**

1.  第一次关联
![image](https://user-images.githubusercontent.com/20573589/132298320-73a15236-0575-4939-8c43-c41c6e36300f.png)

2. 第二次点击关联测试用例，模块消失了。
3. 
![image](https://user-images.githubusercontent.com/20573589/132298443-4e89833e-7ece-4afc-a981-1cb9b06fe7ef.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

多次点击关联测试用例，正确展示模块
![image](https://user-images.githubusercontent.com/20573589/132298320-73a15236-0575-4939-8c43-c41c6e36300f.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复

**Comment by mileslian** [comment]
谢谢
