### ISSUE TITLE
用户改密码后无法登陆

### ISSUE THREAD

**Issue by hoiwanchang** [metersphere/metersphere#6]
无论是变更admin用户密码，还是新建用户然后改密码，都会出现用户改密后无法登陆的情况，只能修改数据库。
请核实。

**Comment by wangzhen-fit2cloud** [comment]
你好，我们试了下没有复现你说的问题。
可以再补充下截图信息吗？

**Comment by hoiwanchang** [comment]
应该是密码复杂度导致不能改密码的问题，我们以为修改成功了。
