### ISSUE TITLE
[FEATURE]可以对不同的角色定义不用的功能权限

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#60]
**请描述您的需求或者改进建议.**
    目前测试人员、测试经理都可以常见项目、模块、用例。需要对不同的角色定义相关的增删改查权限

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，暂时会保持现有的角色权限设定，可以在 2.0 版本是考虑重构该功能
