### ISSUE TITLE
[FEATURE]swagger导入接口，接口的请求名称建议用 summary （接口中文名称）方便接口识别

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#600]
**请描述您的需求或者改进建议.**

swagger导入接口，接口的请求名称建议用 summary ，现在用的是operationId
如果summary为空下可以用operationId

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，在 1.4.0 版本中已修改，请升级验证
