### ISSUE TITLE
提供批量删除或批量修改的功能

### ISSUE THREAD

**Issue by lczhuyeqing** [metersphere/metersphere#6002]
**请描述您的需求或者改进建议.**
现在全选接口或者场景之后，并没有任何可以操作的按钮
这个全选功能是否是个鸡肋
能否提供批量删除或者批量修改的功能
能批量修改模块，状态等等

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
目前是支持的
![image](https://user-images.githubusercontent.com/64065190/132311116-8980dbc7-65c3-49f1-a82d-6a1d2f1b9731.png)
![image](https://user-images.githubusercontent.com/64065190/132311157-ea310159-8903-4873-be95-bd8e7c0bd929.png)
