### ISSUE TITLE
[FEATURE]支持集成碎片化其他服务或若干在线文档

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6005]
**请描述您的需求或者改进建议.**

测试使用过程中存在很多碎片化其他服务或若干在线文档，希望ms能有可配置展现的看板页面，通过配置url，跳转打开展现汇总碎片化服务

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
暂无计划，可以看看文件管理是否能满足需求。
