### ISSUE TITLE
[FEATURE]希望增加文件管理，管理测试中需要的团队文档

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6006]
**请描述您的需求或者改进建议.**

Cucumber自动化框架，会使用到featrue的文件。
希望在MS上有类似用例管理一样的文件管理功能。
1、可以设置文件夹，分类管理
2、列表展显示名称
3、可导入导出
4、放开api接口可获取featrue文件详情

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
