### ISSUE TITLE
[BUG]接口场景-导出json文件会触发两次下载

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6010]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

接口场景-导出json文件会触发两次下载

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

只下载一次

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.10.11已修复
