### ISSUE TITLE
[FEATURE]测试用例评审的脑图中可以进行备注或者评价

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6011]
**请描述您的需求或者改进建议.**
测试用例评审的脑图中可以进行备注或者评价。

**请描述你建议的实现方案**
测试用例评审的脑图中可以进行备注或者评价，来快速说明不通过的原因，以便评审后进行修改。

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
