### ISSUE TITLE
[BUG]使用两层事务控制器，内层事务控制器下复制或引用的场景在报告中查看不了具体内容

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6014]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

两层事务控制器，第二层事务控制器中放一个引用或者复制的场景，跑出来的报告不能具体查看引用或者复制场景的每一个请求的详细报告
![image](https://user-images.githubusercontent.com/88763608/132322237-23c5686b-2428-474b-8ec8-f5ef31fdae34.png)

![image](https://user-images.githubusercontent.com/88763608/132322045-dc55f7cd-b4db-497f-96f6-e847a5d81219.png)

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
