### ISSUE TITLE
[BUG]接口场景中拖动步骤，页面滚动条不能向上随拖动步骤而滚动了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6015]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

![image](https://user-images.githubusercontent.com/88763608/132322800-b71ad4f7-2a8e-44c7-a879-c613e9bd8a9b.png)

**Bug 重现步骤**

使用场景：
1、当步骤数量较多，一屏显示不全，有滚动条。
2、拖动最后一个步骤，拖到第一个

现象：拖动步骤，页面滚动条不能向上随拖动步骤而滚动了

很不方便，对于步骤顺序调整。
注意，是不能向上

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
未复现该问题
