### ISSUE TITLE
[FEATURE]希望场景能有更好的展开或收起的展现形式

### ISSUE THREAD

**Issue by lczhuyeqing** [metersphere/metersphere#6017]
**请描述您的需求或者改进建议.**
如果一个接口下有多个参数或者sql时，整个列表会变得非常繁琐
展开和收起变得非常麻烦
找不到对应的接口

**请描述你建议的实现方案**
能否做成类似下图的形式，以便于更快速的展开和收起
![微信截图_20210907180105](https://user-images.githubusercontent.com/88369896/132326368-3c8c8633-e804-4d21-a3e8-63c484275bf5.png)

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化下

**Comment by xulinde** [comment]
v1.13已优化。改成外层收起时收起全部
