### ISSUE TITLE
[BUG]同步的swagget文档缺失响应体内容

### ISSUE THREAD

**Issue by fupeng1313** [metersphere/metersphere#6018]
版本是  v1.12.1

同步的swagget文档缺失响应体内容

1.  添加一个项目
2. 接口测试>更多操作>导入>导入swagger文件

期望metersphere中显示接口文档和原swagger接口文档内容一致

原swagger文档如下图
![image](https://user-images.githubusercontent.com/52022712/132332247-6f3ae5c5-8485-43af-8805-52dfcf970a2b.png)

meterspere显示的接口文档如下图
![image](https://user-images.githubusercontent.com/52022712/132332433-f1a8b0be-4065-45b6-a529-5a061e7a050d.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我使用swagger2和swagger3都没有复现这个问题
![图片](https://user-images.githubusercontent.com/73461316/132634851-90c56ce7-b06b-4165-9534-f7b0adca71cb.png)
