### ISSUE TITLE
[BUG]调试的时候，在次数循环第五次失败了，但接口还是显示成功。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6020]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.12.0

**Bug 描述**

调试的时候，在次数循环第五次失败了，但接口还是显示成功。

**Bug 重现步骤**

1.  创建场景，添加次数循环
2. 次数循环第五次失败了，但接口还是显示成功。
3. 
4. 

**期待的正确结果**
调试的时候循环中有失败，接口也提示失败。

**截图**
![企业微信截图_16310022711639](https://user-images.githubusercontent.com/87106917/132433039-78c8c6e0-c489-40c7-b757-35c6dd172cdd.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
