### ISSUE TITLE
[BUG]CASE复制，会出现无法查看到测试用例的请求参数，也没有复制url。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6021]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 1.12.1

**Bug 描述**

CASE复制，会出现无法查看到测试用例的请求参数，也没有复制url。

**Bug 重现步骤**

1.  进入接口定义，点击CASE,进入用例列表。
2. 直接点击用例后的复制
3. 
![image](https://user-images.githubusercontent.com/87106917/132435190-5d6c32f1-6789-427a-9f84-0443ce8a3b57.png)

**期待的正确结果**
支持复制
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
