### ISSUE TITLE
[BUG]接口测试-接口用例数量统计-已覆盖接口数 统计错误，已删除的接口用例，应该过滤掉

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6022]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.0-a8cbf128
**Bug 描述**
接口测试-接口用例数量统计-已覆盖接口数 统计错误，已删除的接口用例，应该过滤掉
简要描述您碰到的问题

**Bug 重现步骤**

1.  接口测试-接口用例数量统计-已覆盖接口数 统计错误
2. 
![image](https://user-images.githubusercontent.com/30038088/132435718-b9ddd9e6-d50d-4f1d-b8d2-30387c0abb04.png)
3.
![image](https://user-images.githubusercontent.com/30038088/132435788-5e68ae40-a0e6-44c4-893c-ea47c8d54140.png)
4. 

**期待的正确结果**

正确情况下应该是什么样的？
已删除的接口用例，应该过滤掉
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.13.0已修复
