### ISSUE TITLE
[BUG]创建接口会跳转至CASE列表，无法创建。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6023]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 1.12.0

**Bug 描述**

创建接口会跳转至CASE列表，无法创建。

**Bug 重现步骤**

1.  进入接口定义
2. 点击某一条API后的CASE按键跳转至测试用例列表
![image](https://user-images.githubusercontent.com/87106917/132436020-40bc0cda-9f16-4150-acac-fcc609bd5630.png)

3. 关闭测试用例列表
![image](https://user-images.githubusercontent.com/87106917/132436064-c6ff869f-4ecb-4978-8da1-b166f4e7496c.png)

4. 直接创建接口
![image](https://user-images.githubusercontent.com/87106917/132436114-2439e8c1-515b-4eaa-a8f1-74e463621792.png)
![image](https://user-images.githubusercontent.com/87106917/132436142-23e86383-b8bc-41d3-9c30-5c3008dfd6d3.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.12.2已修复
