### ISSUE TITLE
[BUG]导出sql协议接口（metersphere格式），导入到其他项目，报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6024]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.12.0-a8cbf128**Bug 描述**

简要描述您碰到的问题
导出sql协议接口（metersphere格式），导入到其他项目，报错
**Bug 重现步骤**

1.
![image](https://user-images.githubusercontent.com/30038088/132437838-4968e063-d9eb-48b3-925f-396210efae6f.png)
2.导入报错
![image](https://user-images.githubusercontent.com/30038088/132437929-64923f40-38a7-49e6-a14b-1aedc91b8ff4.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我用1.12.1没有复现这个问题，请升级到1.12.1试一下

**Comment by shenkaibo** [comment]
12.2 已测试，无此问题

**Comment by shenkaibo** [comment]
导入到 其他 工作空间 的 项目里，会报错

**Comment by shenkaibo** [comment]
导入时候建一个模块，然后 导入的时候 选择那个模块，未导入到对应模块里

**Comment by zyyfit** [comment]
1.14.1已修复
