### ISSUE TITLE
[BUG]接口测试用例批量执行会有个别用例一直显示在测试中。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6025]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.1版本

**Bug 描述**
接口测试用例批量执行会有个别用例一直显示在测试中。

**Bug 重现步骤**

1.  批量执行CASE 
2. 
![image](https://user-images.githubusercontent.com/87106917/132440262-1787872d-c9e6-41b6-841e-51122e3d709e.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
v1.13已修复
