### ISSUE TITLE
自定义字段支持排序及高级搜索筛选

### ISSUE THREAD

**Issue by chihaifeng1** [metersphere/metersphere#6029]
1.“测试字段”为新增自定义字段
2.点击组合查询，没有此字段展示
3.无法在列表页对自定义字段进行排序
![ms-测试字段](https://user-images.githubusercontent.com/8275478/132487481-4690a625-bd39-463c-8624-6ead4d1b635a.png)
![ms-组合筛选](https://user-images.githubusercontent.com/8275478/132487486-d171ef2f-1a46-4f12-9cfd-de0faac6bb1a.png)

**Comment by zyyfit** [comment]
您好，目前组合查询还不支持自定义字段，后续版本可能会考虑支持

**Comment by xulinde** [comment]
v1.20.4支持该功能
