### ISSUE TITLE
[BUG]当请求头中定义了content-type的类型时，其值不应该跟随请求内容的格式变化

### ISSUE THREAD

**Issue by lixuelan** [metersphere/metersphere#603]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.3.1-b875
**Bug 描述**
简要描述您碰到的问题
模块：接口测试
请求头中，content-type 值设置为：text/x-json
请求内容使用json格式的话，该接口执行后，content-type的值会被更改为：application/json
导致接口执行失败
![image](https://user-images.githubusercontent.com/36878518/97170905-78599680-17c7-11eb-91ad-e4c8a0487dd3.png)

将请求内容的格式修改为text，执行后，结果正常

**Bug 重现步骤**
无

**期待的正确结果**
当请求头中定义了content-type的类型时，其值不应该跟随请求内容的格式变化，否则不好排查问题

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本中已修改，请升级验证
