### ISSUE TITLE
[BUG]提交缺陷关联jira时自定义字段key值问题

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#6037]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.1
**Bug 描述**
提交缺陷关联jira时发现部分jira接收的自定义字段的key不是id，是name，但是现阶段系统所有自定义字段传递都是以id为key值，导致无法正常创建

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
希望能够修改自定义字段传递的key值，可默认为id，但可编辑

**截图**

![image](https://user-images.githubusercontent.com/40912823/132468127-a908051c-7afd-43be-ab45-9e6a718f9e45.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
现已支持自动读取模板
