### ISSUE TITLE
[FEATURE]建议支持场景化调用

### ISSUE THREAD

**Issue by lixuelan** [metersphere/metersphere#604]
**请描述您的需求或者改进建议.**
场景案例：
【创建商品】流程内包含3个接口（登录、查商品、添加商品）
 
删除商品、修改商品、购买商品是其他流程，但都需要先【创建商品】

目前在后续的场景中，【创建商品】的操作需要在每个场景里面重复添加，如果把【创建商品】做成可调用的一个场景，就可以直接复用了。

**请描述你建议的实现方案**
接口测试，支持按场景添加，添加一个场景，即是将该场景中的接口全部添加到新的场景中，这样避免重复的人工添加的公做量，而且多个场景可组合复用，增加用例的扩展性

**Comment by wangzhen-fit2cloud** [comment]
你好，现在在一个接口测试中是可以复制或引用其他测试中的场景的，可以试一下看能否满足你的需求。
![image](https://user-images.githubusercontent.com/27671436/97673147-3fbb0500-1ac6-11eb-960a-4795d1f2daee.png)
