### ISSUE TITLE
测试用例步骤增加步骤描述字段

### ISSUE THREAD

**Issue by linyuantang001** [metersphere/metersphere#6041]
根据国家制造业生产线标准规范要求
在测试用例中，步骤描述增加一个列，叫做步骤描述
位置如下

![测试用例字段增加](https://user-images.githubusercontent.com/39185981/132478502-2e0b9239-393c-4981-b67f-7af2c4c09bd9.png)

**Comment by luty2018** [comment]
建议你可以自定义富文本的模板来实现这个需求呢。
