### ISSUE TITLE
[BUG] 场景引用场景，变量被覆盖问题

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#6043]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.1
**Bug 描述**

父场景A，子场景B、C（B、C相对于A是同级别的子场景）

**Bug 重现步骤**

如果A、B、C共同拥有变量value，对于变量value的执行顺序是A->B->C，最终结果发现ABC三个使用的都是C的变量。也就是说A、B的场景都被覆盖了。

预期&希望：
父场景的变量覆盖子场景变量（不管子场景嵌套多少层都应该是以父场景为主），如果父场景没有定义该变量，可以使用子场景的变量。（以测试的角度：场景复用出发）

**Comment by zyyfit** [comment]
已知问题，可能后续版本会进行修复
相关问题：https://github.com/metersphere/metersphere/issues/1620

**Comment by xulinde** [comment]
和issue#1620重复
