### ISSUE TITLE
[BUG]【接口测试】接口定义页面，变更API的URL信息后，对应API的CASE中URL信息不会自动修改，且无法手动修改

### ISSUE THREAD

**Issue by gongbaojid** [metersphere/metersphere#6044]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是 v1.11.3-8e3889e3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  进入接口定义页面
2. 修改API的URL信息
3. 查看API对应CASE中的URL信息显示
4. 仍显示为变更前的URL，且无法手动修改，导致必须删掉CASE再创建新的CASE

**期待的正确结果**

修改API的URL信息后，对应CASE中的URL信息自动变更为修改后的值

**截图**

如果有截图，请附上截图.

**Comment by linl12138** [comment]
如果修改了接口信息，场景中引入这个接口就会变的话，涉及到多个场景同时引入了这个接口，有的需要变更，有的不需要变更那这样的需求就是不合理的。

**Comment by gongbaojid** [comment]
> 
> 
> 如果修改了接口信息，场景中引入这个接口就会变的话，涉及到多个场景同时引入了这个接口，有的需要变更，有的不需要变更那这样的需求就是不合理的。

我针对只是url，接口的url应该所有地方都保持一致吧

**Comment by luty2018** [comment]
v1.12 已经优化成 修改API 请求类型和路径 那么CASE也会自定更新

**Comment by gongbaojid** [comment]
> 
> 
> v1.12 已经优化成 修改API 请求类型和路径 那么CASE也会自定更新

好的，多谢，我们更新后验证下
