### ISSUE TITLE
[BUG]多线程，调用接口场景执行/api/automation/run/jenkins，节点机异常

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6050]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

30线程出现过
5个jenkins任务并发，3线程调用执行 15线程出现过  

[MeterSphere，代码测试]ERROR_CODE_502：syntax error, expect {, actual error, pos 0, fastjson-version 1.2.51
[MeterSphere，代码测试]ERROR_CODE_501：null（不确定原因）

**Bug 重现步骤**

1.  多线程调用/api/automation/run/jenkins
2. 可能是并发时，kafka丢包，是否可以通过配置解决？

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，我们这边没有复现您的问题，建议升级到最新版本试试~！
