### ISSUE TITLE
[BUG]安装节点资源时，没有自动生成/data/body 目录

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6051]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

安装节点资源时，没有自动生成/data/body 目录

**Bug 重现步骤**

1.  安装节点资源
2.  查看/data/body目录
3. 
4. 

**期待的正确结果**

自动生成目录

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，安装节点资源是不生成这个目录的
