### ISSUE TITLE
[BUG]安装节点资源时，及时配置了kafka主机IP，但安装后还是显示的本机IP

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6052]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

安装节点资源时，即使配置了kafka主机IP，但安装后还是显示的本机IP

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题~

**Comment by youliyuan-fit2cloud** [comment]
v1.10.11-lts以上版本已解决该问题

**Comment by youliyuan-fit2cloud** [comment]
升级的话是需要改安装目录里的这个：/opt/metersphere/install.conf
