### ISSUE TITLE
[BUG]子模块下快速调试后，点击另存为新用例，用例保存在默认模块，而不是对应模块

### ISSUE THREAD

**Issue by angusyin** [metersphere/metersphere#6055]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.12.1

**Bug 描述**

子模块下快速调试后，点击另存为新用例，用例保存在默认模块，而不是对应模块

**Bug 重现步骤**

1.  接口测试页面-接口定义--全部模块-添加子模块【测试】
2. 选择子模块【测试】
3. 点击+，快速调试，完成后，
4. 点击 另存为新用例，保存

**期待的正确结果**
api和case都保存在 子模块【测试】下

正确情况下应该是什么样的？
限制都保存到默认模块了；多人操作的话，保存后还要一个一个找自己创建的api和case，在移动到对应模块
**截图**
![Uploading 1.jpg…]()

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
目前就是这样设计的～
