### ISSUE TITLE
[BUG] 缺陷自定义字段同步

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6058]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.12

**Bug 描述**

与JIRA/TFS等第三方平台同步缺陷时，缺陷的自定义字段不会同步。

**Bug 重现步骤**

1.  创建缺陷模版，增加自定义字段
2. 基于缺陷模版创建缺陷，（同步至第三方缺陷管理平台）
3. 在第三方缺陷管理平台更新自定义字段

**期待的正确结果**

MS里的自定义字段应该能进行同步更新。

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
