### ISSUE TITLE
[BUG]删除case后，新增同名的case无法保存，提示异常“测试名称不能重复”.

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6059]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**
删除case后，新增同名的case无法保存，提示异常“测试名称不能重复”

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by rayshen3** [comment]
我是性能压测压倒瓶颈开始报错，结束后修改压力参数再执行，性能报告中如果有相同名字的报告，一个已完成，一个执行中，删除已完成的，然后点击查看执行中的，显示的是已完成的报告...      
还有各种各样的js弹窗报错.....  
ms server端  error log 各种空指针error....   

无力吐槽，都想卸载了

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
> 我是性能压测压到瓶颈后，结束当前压测，修改压力参数再执行，性能报告中如果有相同名字的报告，一个已完成，一个执行中，删除已完成的，然后点击查看执行中的，显示的是已完成的报告...
> 还有各种各样的js弹窗报错.....
> ms server端 error log 各种空指针error....
> 
> 哎，无力吐槽

您好，您说的这个测试报告的问题我用最新版没有复现，请问您使用的是什么版本呀？还有其他问题也可以给我们提issue，我们都会一一排查修复的

**Comment by xulinde** [comment]
v1.12.2已修复
