### ISSUE TITLE
[QUESTION] 登录接口作为全局变量使用

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#606]
**请描述您的问题.**
1、先把登录接口作为全局变量使用     
2、中途切换了登录账号，不引用全局登录的变量        
3、后面引用了全局登录变量的接口，是以1的账号登录，还是2呢？（目前的测试反馈好像是不会再引用1了）
![image](https://user-images.githubusercontent.com/70245535/97246813-35380b80-1839-11eb-8f02-a87b7a058654.png)

**Comment by wangzhen-fit2cloud** [comment]
是通过什么样的方式进行引用的呢？

**Comment by Sylvie1222** [comment]
1、第1个接口（登录），登录A账号，把返回的token和id，放在环境中设置为全局请求头
2、第4个请求（登录），一个新的登录接口，切换了账号登录，比如登录了B账号
3、第5个请求（批准同意），如果没有引用环境，是否会用的新登录接口B账号？
4、第6个请求（查询数据），如果引用了环境，是否会用旧登录接口A账号？

**Comment by wangzhen-fit2cloud** [comment]
通过提取功能获得的变量只可以在当前场景中引用成功

**Comment by Sylvie1222** [comment]
没有跨场景。
3、第5个请求（批准同意），如果没有引用环境，是否会用的新登录接口B账号？---同场景下有一个区别于全局登录的新登录接口
4、第6个请求（查询数据），如果引用了环境，是否会用旧登录接口A账号？

**Comment by wangzhen-fit2cloud** [comment]
3. 取决于是否在该请求或该请求所在场景中配置了请求头，如果配置了就会使用新登录接口获取的 token
4. 不会，因为旧登录接口不在同一个场景中，起提取到的值无法被引用到

**Comment by Sylvie1222** [comment]
4、不会，因为旧登录接口不在同一个场景中，起提取到的值无法被引用到------------我是把提取了第一个登录接口的响应值，脚本设为全局变量，放在了环境设置中的全局请求头。后面的接口引用了环境，即引用了环境中的请求头呀

**Comment by wangzhen-fit2cloud** [comment]
那在第三个场景中对应请求头的值是什么呢？

**Comment by Sylvie1222** [comment]
写的是新接口的请求头。
现在的问题是：后面引用环境---全局登录的接口，貌似不成功。因为我一旦把新的登录接口禁用了，后面所有接口都报错，提示无权限，也就是登录失败了

**Comment by wangzhen-fit2cloud** [comment]
不知道你具体是怎么配置的，能否提供几个关键位置的截图
