### ISSUE TITLE
[BUG]安装了开源版本后用了1-2天，发现无法新建用户了。附上截图

### ISSUE THREAD

**Issue by chengdu-li** [metersphere/metersphere#6064]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

安装了开源版本后用了1-2天，发现无法新建用户了。附上截图

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/68626737/132640387-e99a503e-df1c-4b4c-8398-acd05d83b4fa.png)

如果有截图，请附上截图.

**Comment by chengdu-li** [comment]
版本是1.12

**Comment by xulinde** [comment]
是不是禁用了“添加成员”的权限
![image](https://user-images.githubusercontent.com/64065190/132669976-ee82e022-5745-44f3-8d91-7eb30608f3bd.png)
