### ISSUE TITLE
[BUG]测试跟踪-Excel测试用例导入测试步骤多于9行时不能继续新增明细行

### ISSUE THREAD

**Issue by huguangya** [metersphere/metersphere#6065]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**
![image](https://user-images.githubusercontent.com/54281046/132647318-bafd0f32-c5fb-4acc-9a20-c1c766a513db.png)

![image](https://user-images.githubusercontent.com/54281046/132647062-438e9346-701c-458a-8e5b-2875fcba6374.png)

简要描述您碰到的问题

**Bug 重现步骤**

1.  如图所示
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13已修复
