### ISSUE TITLE
[QUESTION]SQL请求的提取或者断言怎么写呢？

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#607]
**请描述您的问题.**
SQL请求的提取或者断言怎么写呢？

**Comment by wangzhen-fit2cloud** [comment]
提取功能可以在请求配置页面设置按列存储，配置后每一列的内容将会存在对应变量中，如下图所示，可以使用 ${id_1} 的方式引用到 id 列的第一个值
![image](https://user-images.githubusercontent.com/27671436/97672576-3da47680-1ac5-11eb-8000-e23ec10aae19.png)

**Comment by Sylvie1222** [comment]
断言怎么取呢？因为断言里是用JSON，正则提取的

**Comment by wangzhen-fit2cloud** [comment]
断言可以等我们发布 1.4.1 以后，使用变量/脚本断言的方式
![image](https://user-images.githubusercontent.com/27671436/97673292-7db82900-1ac6-11eb-9c03-02c096cfc42d.png)
