### ISSUE TITLE
[BUG]在一个测试计划执行中，前置场景中提取并存储的环境变量，无法被后续场景读取到（所有场景均在同一环境下）

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#6071]
> MeterSphere版本：1.12.0
### 前置条件

- 存在环境OpenAPI，环境中无环境变量
- 在场景“获取OpenAPI测试准备”中，已配置后置脚本：

```
log.info(u"执行【后置脚本】")

#Python脚本开始
import json
content = json.loads(prev.getResponseDataAsString())
vars.put(${__metersphere_env_id}+"accessToken",content["data"]["accessToken"]);
#Python脚本结束

log.info(u"【后置脚本】执行完毕")
```
- 在场景“批量新增...”中，已配置参数${accessToken}
- 在测试计划中，配置“获取OpenAPI测试准备”先执行，“批量新增...”后执行

### 操作过程

- 执行计划
- 查看报告
### 结果
>**_获取OpenAPI测试准备先执行_**
![1D252C368962ED56A3EC17505388AFBC](https://user-images.githubusercontent.com/34698664/132659881-ef49237b-9ea5-402d-bbb5-cc5fde8ee040.jpg)

> **_“批量新增...”后执行，且无法获取到${accessToken}_**
![image](https://user-images.githubusercontent.com/34698664/132662172-67c1fc4b-7dc6-4173-88a0-c8710e08ccfb.png)

> _**环境中已存入变量${accessToken}**_
![image](https://user-images.githubusercontent.com/34698664/132662573-3e4b2971-1fcf-42ec-a1fa-a3275af3252c.png)

**Comment by zyyfit** [comment]
您好，最新版已经没有这个问题了，您可以升级试试
