### ISSUE TITLE
[BUG]任务通知

### ISSUE THREAD

**Issue by niu378875091** [metersphere/metersphere#6074]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.12.1-6bcee557
**Bug 描述**

变量没有生效
![1631242599(1)](https://user-images.githubusercontent.com/86141364/132792179-d8b6da88-cbee-418c-933a-8c149fdd2eb6.jpg)

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
变量解析成功
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问这是测试计划通知吗？开源版的不支持自定义通知的
