### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by apple006** [metersphere/metersphere#6076]
请问一下，
在用python前置脚本编写接口自动化时，当输入import requests后，点击“测试”按钮，控制台报错：javax.script.ScriptException: ImportError: No module named requests in <script> at line number 3，现在是不支持用这些导入的库吗

**Comment by wangzhen-fit2cloud** [comment]
你好，目前使用python第三方库需要在 ms-server 容器中存在 python 第三方库，并且在脚本中通过 sys.path.append() 的方式增加引用路径。
