### ISSUE TITLE
[BUG]缺陷管理的图片查看功能体验变烂了

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#6079]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.12.1
![image](https://user-images.githubusercontent.com/44960709/132814046-60415bcd-1c34-407c-8a0a-57529e06adc8.png)

**Bug 描述**

简要描述您碰到的问题
缺陷管理的预览看图片变得不能看完整的图片了，之前是可以看略缩图的
还有就是缺陷详情里的略缩图查看体验有问题
**Bug 重现步骤**

1.  在缺陷管理里面截图放一张大图
2. 你会发现体验糟糕极了😰
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
有略缩图，有略缩图
**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢反馈，后面版本优化下

**Comment by xulinde** [comment]
之前的版本也没有缩略图，图片上传多大查看就需要加载多大的哦～
