### ISSUE TITLE
[BUG] 自定义脚本中录入以上脚本后会导致调试时任务一直处于running状态

### ISSUE THREAD

**Issue by tangw-github** [metersphere/metersphere#6080]
**MeterSphere 版本**
1.12.1

**Bug 描述**
![47f5fa8d886e1e9e3a5bbf27e1629f3](https://user-images.githubusercontent.com/8164903/132814275-f2ac0c3b-87d6-48ad-a857-2a8168ddba96.png)
自定义脚本中录入以上脚本后会导致调试时任务一直处于running状态。后台不报错

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by xulinde** [comment]
目前jmeter的机制是这样的哦～
