### ISSUE TITLE
[BUG]测试用例导入，使用xmind格式，模块名中带有英文字母会导入失败。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6083]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？  1.12.0

**Bug 描述**

测试用例导入，使用xmind格式，模块名中带有英文字母会导入失败。

**Bug 重现步骤**

1.  导入用例，选择脑图模式
2. 导入的用例模块名中带英文字母

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

**Comment by zyyfit** [comment]
您好，我使用1.12.1版本没有复现这个问题，您可以升级试试，如果还不行的话能否上传一份您导入的xmind用例？
