### ISSUE TITLE
[BUG]无法进行性能测试

### ISSUE THREAD

**Issue by DragonBowers** [metersphere/metersphere#6089]
您所使用的 MeterSphere 版本是？
v1.12.1
![Snipaste_2021-09-11_15-21-05](https://user-images.githubusercontent.com/26021348/132940030-80e1eb17-9fc3-451a-a81e-401220e21711.png)

**Bug 描述**
对接口进行性能测试，报告的状态一直是Reporting，metersphere的error日志如下图
![81E5EE77-CB4D-4f4a-BD32-82BCB3EE0128](https://user-images.githubusercontent.com/26021348/132939968-2d1b5a70-4f99-4bc2-a84e-adc3f743c03c.png)

**Comment by GITMrzk** [comment]
同遇到，升级1.12之后发现性能测试经常就挂掉了，重启ms服务能好使一阵，再过几天又跑不了了。

**Comment by xiaoyong10000** [comment]
我也遇到了，新部署的服务也一样报错

**Comment by xiaoyong10000** [comment]
v1.12.3-27e6d479还是有问题
