### ISSUE TITLE
[BUG]系统设置-项目-环境配置-http-模块类型匹配host，选择父模块，子模块不会生效，需要在子模块重新勾选

### ISSUE THREAD

**Issue by hank5566devAB** [metersphere/metersphere#6090]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
系统设置-项目-环境配置-http-模块类型匹配host，选择父模块，子模块不会生效，需要在子模块重新勾选
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前我们的设计是这样的
