### ISSUE TITLE
[BUG]场景引用场景，当多个场景，出现相同变量，但是值不一样时，不能根据各自场景设置的变量值获取

### ISSUE THREAD

**Issue by hank5566devAB** [metersphere/metersphere#6091]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
场景引用场景，当多个场景，出现相同变量，但是值不一样时，不能根据各自场景设置的变量值获取
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，暂时不好修复
https://github.com/metersphere/metersphere/issues/1620

**Comment by xulinde** [comment]
和issue#1620重复
