### ISSUE TITLE
[BUG]修改MeterSphere JSON文件接口定义或case名称，导入后无法修改对应的接口定义或case

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#6092]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.1
**Bug 描述**
MeterSphere 导出接口定义后，修改接口定义或者case的名称，重新导入，被修改的接口定义或者case，变成新增接口定义或case，原接口不会进行更新;
简要描述您碰到的问题

**Bug 重现步骤**

1.  系统设置，设置项目允许重复URL；
2. 批量导出接口定义；
3. 使用文件工具修改部分接口定义或case的名称；
4. 重新导入MeterSphere同一个项目；

**期待的正确结果**
对应的接口定义或者case的名称发生相应变化
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我看您开启了url可重复，
1、如果您没选择覆盖，并且url、接口名称都不相同的话，会生成一个新的接口，不会更新之前的接口，
2、如果您选择了覆盖，并且url、接口名称等与原接口信息一致，才会更新之前的接口
