### ISSUE TITLE
[FEATURE] - 建议在优化断言、提参、判断等功能的备注内容。

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#6093]
1、建议在每一条断言、每一天提参后面增加备注内容显示字段，可自定义添加备注信息，方便后续查阅。
2、建议在条件控制器以及循环控制器中增加名称备注内容，如case名称、自定义脚本名称等。
3、建议优化条件控制器中可增加多个判断条件表达式简化多条件判断场景下需要添加多个条件表达式的情况。

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/5255

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
