### ISSUE TITLE
[BUG] 接口TEST后点击更新接口内容，页面显示内容异常

### ISSUE THREAD

**Issue by tangw-github** [metersphere/metersphere#6094]
**MeterSphere 版本**
V1.12.1

**Bug 描述**
在调试接口后选择更新接口，先跳转到API，再点击TEST会导致调试接口中改动的内容消失，需要刷新页面后才正常显示

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13已修复
