### ISSUE TITLE
测试用例使用excel模板导入，标签只要是使用纯数字，会显示成序列，而不是单个标签

### ISSUE THREAD

**Issue by linl12138** [metersphere/metersphere#6097]
**MeterSphere 版本**
v1.12

**Bug 描述**

测试用例使用excel模板导入，标签只要是使用纯数字，会显示成序列，而不是单个标签

**Bug 重现步骤**

1.  下载用例导入的excel模板，标签只要是使用纯数字，会依次显示为序列，而不是单个的标签，截图如下：

![image](https://user-images.githubusercontent.com/42909446/133014394-61a12b58-8ec9-4436-b0f7-46f1220d052d.png)
![image](https://user-images.githubusercontent.com/42909446/133015000-4c36ea5d-bb36-4e67-b9db-d33e9657e2fd.png)

**期待的正确结果**
![image](https://user-images.githubusercontent.com/42909446/133014930-43a862b1-2080-480e-9299-fd8ee2f04535.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13已修复
