### ISSUE TITLE
[BUG]测试资源池，无法进行分布式测试

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#6098]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.1
**Bug 描述**

简要描述您碰到的问题
当配置多个测试资源池时，并且批量并发执行接口自动化场景时，所有的请求都集中在资源池中某一个节点上，并未按照并发限制的比列进行分配执行
**Bug 重现步骤**

1.  配置多个节点的资源池；
2. 批量选择场景；
3. 勾选已配置资源池
4. 选择并发执行

**期待的正确结果**
资源池每个节点按照配置比例分布请求
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
新版本已解决
