### ISSUE TITLE
[FEATURE]增加一些比较常用的函数或者提供一个接口可以调用一些外部函数

### ISSUE THREAD

**Issue by yangjourney** [metersphere/metersphere#61]
**请描述您的需求或者改进建议.**
在试用过程中发现，针对具有有唯一索引的字段，在执行测试的时候，需要手动去调整参数值，比较影响后期的持续集成效率

**请描述你建议的实现方案**
1、在接口内容中增加一些常用的函数
2、增加自定义函数，以便于针对特殊接口要求，可以通过调用第三方函数来解决，比如说涉及到接口数据加密传递和解码的时候。有点类似于jmeter里面的调用外部方法吧。

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
