### ISSUE TITLE
[BUG]测试计划定时任务无法关闭

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#6100]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.1
**Bug 描述**
在测试跟踪模块中，创建一个测试计划，关联部分接口和场景，设置定时任务，当点击关闭定时任务并保存后，依然会产生新的定时任务；
简要描述您碰到的问题

**Bug 重现步骤**

1.  在测试计划中开启一个定时任务
2. 执行一段时间后，手动关闭定时任务
3. 定时任务关闭后重新编辑时发现定时任务依然是开启状态了；
4. 测试报告中依然有新的定时任务报告；

**期待的正确结果**

正确情况下应该是什么样的？
关闭后测试计划的定时任务关闭，无新的定时任务的报告出现
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问您关闭定时任务开关后，是否点击了这个保存按钮？
这个保存按钮是保存定时任务设置并开启定时任务用的，关闭定时任务的时候不要点保存哦
![图片](https://user-images.githubusercontent.com/73461316/133726519-4bf3af96-8c1f-4d45-b7e3-108e63ff1110.png)
