### ISSUE TITLE
[BUG]测试计划并行执行定时任务和接口自动化并行执行，测试报告一直处于running状态

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#6101]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.1
**Bug 描述**

简要描述您碰到的问题
在测试计划中设置定时任务，选择并行或串行执行，选择本地资源池，或者在接口自动化批量选择场景，进行并行或串行执行时，存在测试报告一直处于running状态的情况；
**Bug 重现步骤**

1.  在测试计划或者在接口自动化列表
2. 批量选择场景；
3. 并发执行；
4. 测试报告一直处于running的状态

**期待的正确结果**
不管正确与否能及时进行状态变化
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by hefeixiao** [comment]
使用v1.12.2也有个类似的问题，采用jenkins插件，调用接口自动化测试任务，也会一直处于running：
![ff9f4760f59d5c18b96c2fa9abaf25a](https://user-images.githubusercontent.com/59219621/133383233-e3f95146-ab52-4c02-9acc-e6a7f3b4772a.png)

![83bad6e837835b30918d04eafb976a4](https://user-images.githubusercontent.com/59219621/133383203-c7b9d072-c13c-4d9a-909c-aab009f82e00.png)

**Comment by zyyfit** [comment]
您好，我在1.12.3版本没有复现这个问题，您可以升级一下试试
