### ISSUE TITLE
[BUG]测试跟踪-->首页，未评审数量统计异常。比实际用例数多，应该是实际用例删除后未评审中的数量没有删除。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6107]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**

测试跟踪-->首页，未评审数量统计异常。比实际用例数多，应该是实际用例删除后未评审中的数量没有删除。

**Bug 重现步骤**

1.  测试跟踪-->首页，未评审数量统计异常。比当前用例数多，应该是功能用例删除添加后又删除后未评审中的数量没有删除。
2. 
3.

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![企业微信截图_16315099072338](https://user-images.githubusercontent.com/87106917/133027843-a31935bd-7a79-44e3-b78f-b48a8ab8cf00.png)

**Comment by hefeixiao** [comment]
用例删除后，未评审用例数仍包含删除用例数
![image](https://user-images.githubusercontent.com/59219621/133064009-899a72e8-ed64-4c4a-bf18-1dcee41cbac1.png)

**Comment by xulinde** [comment]
v1.12.2已修复
