### ISSUE TITLE
[BUG] jenkins调用metersphere测试计划， 查看报告，发现有部分接口测试一直处于running状态

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#612]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  jenkins调用metersphere测试计划
2. 查看报告，发现有部分接口测试一直处于running状态
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/3426719/97261525-f8c8d780-1859-11eb-9dab-771f1c6c97cd.png)

**Comment by xulinde** [comment]
您好，感谢您的反馈。已知问题，预计月底发布的v1.5.0版本会修复，您到时候直接升级下就可以了。
