### ISSUE TITLE
[BUG] 使用 metersphere使用swagger导入接口用例的时候，超过一定数量再导入接口，就只能产生空的文件夹，接口用例无法正常导入

### ISSUE THREAD

**Issue by zhangxk123** [metersphere/metersphere#6120]
**MeterSphere 版本**
v1.12.0

**Bug 描述**
使用 metersphere使用swagger导入接口用例的时候，超过一定数量，比如66个接口，之后再导入接口，就只能产生空的文件夹，接口用例无法正常导入

**Bug 重现步骤**

1.  登陆系统
2.  选择接口测试-接口定义(已经导入了66个接口定义)
3.  点击更多操作-导入
4.  选择swagger方式导入,选择接口文档导入
5.  页面显示导入成功,但是左侧列表只显示空的文件夹,没有真正导入接口

**期待的正确结果**
希望可以无数量限制的正常导入接口定义

**截图**
<img width="767" alt="wecom-temp-26157ae5b3d46211ba43df04b0efab86" src="https://user-images.githubusercontent.com/22310847/133041670-fdf6bf15-9e14-48e7-a5bd-0b8f4b4a203c.png">
<img width="851" alt="wecom-temp-ab599ba96c3f8cb2ffba80c906f2f0b1" src="https://user-images.githubusercontent.com/22310847/133041687-5821440f-0dd7-4cfd-af9f-c686ba8b8b24.png">
<img width="968" alt="wecom-temp-ed928360115d1024107949862e82ea51" src="https://user-images.githubusercontent.com/22310847/133041693-d37fe2bb-1ddd-4247-ab8f-62544e3a02c2.png">

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把swagger文件上传一下吗？或者您可以加入我们的交流群讨论一下

**Comment by zhangxk123** [comment]
已导入模块中如果有重名的子模块,那么导入新模块的同名子模块就会变成空文件,但是里面的接口没有导入,图片更新在最后一张

**Comment by zyyfit** [comment]
请问同名子模块里的接口是否与已有的接口相同呢？如果接口也是已有的话，是不会显示在新产生的模块里的，会在原来的模块中，根据您的选择覆盖或者不覆盖
