### ISSUE TITLE
[BUG]测试跟踪-->测试用例中在思维导图模式调整优先级选择P1，实际上是选择了P0.

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6126]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**

简要描述您碰到的问题
测试跟踪-->测试用例中在思维导图模式调整优先级选择P1，实际上是选择了P0.
**Bug 重现步骤**

1.  
2. 
![image](https://user-images.githubusercontent.com/87106917/133051941-ff49f10a-e425-47c5-9a88-2be83e2f9fe7.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问您是从P0调整为P1吗？调整后有没有保存脑图呢？

**Comment by liuhansong** [comment]
不是 就是选择P1优先级  用例旁边展示的是P0 
![123](https://user-images.githubusercontent.com/87106917/134318863-75be0744-4511-40bb-a499-b92f9884b50f.gif)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
