### ISSUE TITLE
功能用例在思维导图中支持添加标签。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6129]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**

功能用例在思维导图中不能添加标签。

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/87106917/133052503-a97d916d-5db7-487f-80a8-ae02f5583a5e.png)

2. 
![image](https://user-images.githubusercontent.com/87106917/133052537-ac77dbcb-b395-4cf7-a27d-43379f678555.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前脑图还不支持添加标签，后续版本会考虑支持的

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/5994
