### ISSUE TITLE
[FEATURE]API调用完了，还是要到metersphere来看报告才知道结果是吧，感觉有些不好用，要是日志里有一条条的PASS/FAIL总结就好了

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#613]
**请描述您的需求或者改进建议.**

API调用完了，还是要到metersphere来看报告才知道结果是吧，感觉有些不好用，要是日志里有一条条的PASS/FAIL总结就好了

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，请问是指的 jenkins 插件的控制台输出吗？

**Comment by hanbi** [comment]
是的，这样我在Jenkins那边就很直观看到结果统计
包括跑了几个，以及成功失败结果
