### ISSUE TITLE
[BUG]删除测试用例后无法恢复，只能看到删除记录。建议删除后能看到用例详情描述且用例可恢复

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6141]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  用例列表中点击一条用例右侧的删除按钮，删除用例
2. 在系统设置-项目-操作日志列表中只能看到用例的删除记录，无法看到用例详情，描述等信息
3. 
4. 

**期待的正确结果**

建议删除后能看到用例详情描述且用例可恢复

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/90616297/133073979-3968f32b-8df6-46d7-ae86-8ae5f80d9848.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.11测试用例支持回收站功能，您可以下载体验下
