### ISSUE TITLE
测试用例导入-xmind模式优化

### ISSUE THREAD

**Issue by liuyuzhu1Q84** [metersphere/metersphere#6143]
**请描述您的需求或者改进建议.**
用例导入以“tc:”来标记，在实际编写用例的时候其实不是很方便，建议可以采用打标记的方式来进行。比如：
标记旗帜的分支为用例，标记优先级的为优先级

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
暂无计划。
