### ISSUE TITLE
[BUG]接口自动化，选择一个或多个场景，批量执行，模式：串行，独立报告，本地资源池，确定后，在测试报告中看到执行记录的状态一直是“Running”

### ISSUE THREAD

**Issue by TTtesting** [metersphere/metersphere#6144]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.10.10-lts-2d49ae77
**Bug 描述**

接口自动化，选择一个或多个场景，批量执行，模式：串行，独立报告，本地资源池，确定后，在测试报告中看到执行记录的状态一直是“Running”

**Bug 重现步骤**

接口自动化，选择一个或多个场景，批量执行，模式：串行，独立报告，本地资源池，确定后，在测试报告中看到执行记录的状态一直是“Running”

**期待的正确结果**

执行完成后状态变成success

**截图**

如果有截图，请附上截图.

**Comment by Sensivitiry** [comment]
升级下版本应该就没问题了
