### ISSUE TITLE
[BUG]测试计划-查看测试报告-缺陷统计错误

### ISSUE THREAD

**Issue by nnnnnma** [metersphere/metersphere#6146]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v.1.10.9

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建测试计划a，关联用例1，在执行测试计划，打开用例的时候，关联bug1，执行完毕，结束测试计划a
2. 创建测试计划b，关联用例1，在执行测试计划，打开用例的时候，关联bug2
3. 此时查看测试计划b，选择查看报告，这时候缺陷统计的时候，同时统计到bug1 和 bug2

使用的metersphere 自带的缺陷管理
4. 

**期待的正确结果**

正确情况下应该是什么样的？
测试用例是用例库，缺陷的统计应该是基于计划，而不是关联的用例，否则用例反复执行的时候，报告永远都关联出之前提的bug

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
下个版本会增加的版本管理功能，能解决这个问题
和#7341相同
