### ISSUE TITLE
jenkins插件使用自由风格job执行测试计划，构建日志无法正常显示中文，但是使用pipeline是正常的

### ISSUE THREAD

**Issue by linl12138** [metersphere/metersphere#6149]
**MeterSphere 版本**
>v1.12.2

jenkins插件版本：v1.12.2，jenkins版本：使用jenkins/jenkins:lts镜像运行
无法正常显示的日志如图：
![image](https://user-images.githubusercontent.com/42909446/133200542-3d528fda-2d31-4760-b0b4-87e40059e6be.png)
正常显示的pipeline构建日志为：
![image](https://user-images.githubusercontent.com/42909446/133200628-f4f63179-87c4-42af-863d-837be6f1d7a7.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，ms jenkins插件升级到最新版本试试呢?
