### ISSUE TITLE
[FEATURE]接口测试页面，需要直观看到每个接口测试的最后一次执行结果，是PASS还是FAIL

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#615]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
接口测试列表增加上次执行结果列

**Comment by hanbi** [comment]
![image](https://user-images.githubusercontent.com/3426719/100729790-30e8aa80-3404-11eb-88cc-ae9e593f51c9.png)

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已提供新版接口测试功能
