### ISSUE TITLE
接口响应支持展示返回图片

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6158]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.2-67c53caa
**Bug 描述**
接口响应不支持 返回图片
简要描述您碰到的问题

**Bug 重现步骤**

1.
![wecom-temp-2901a60c57b043ac0d32060b2bdfc359](https://user-images.githubusercontent.com/30038088/133234249-191fb26e-8c05-40be-868d-a4b455401bed.png)
2.

3. 
4. 

**期待的正确结果**
![image](https://user-images.githubusercontent.com/30038088/133234316-5676a5d7-7d4f-4ad6-8dea-91595c507e09.png)

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue 重复，请关注 #3069 并在该 issue 下讨论。
