### ISSUE TITLE
[FEATURE]接口测试页面，在项目视图页面，需要直观看到接口测试的执行结果统计，XX个PASS，XX个FAIL，XX个未执行，总多少个

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#616]
**请描述您的需求或者改进建议.**

[FEATURE]接口测试页面，在项目视图页面，需要直观看到接口测试的执行结果统计，XX个PASS，XX个FAIL，XX个未执行，总多少个

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，计划在接口管理功能上线后再统一规划该功能
