### ISSUE TITLE
[BUG]接口自动化导入的jmx中自定义请求端口参数解析出错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6169]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.12.2

**Bug 描述**
接口自动化导入的jmx中自定义请求端口参数解析出错

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

${port}参数可以正确解析，且导入的jmx可以直接执行

**截图**
![image](https://user-images.githubusercontent.com/32027713/133363363-38b08c9f-cea2-4fb2-9e62-2b672d7de627.png)
![image](https://user-images.githubusercontent.com/32027713/133363423-d3ce3ed8-69f7-4221-861c-d0b1d67c462c.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
