### ISSUE TITLE
关于swagger书写与倒入ms平台

### ISSUE THREAD

**Issue by kuma-z** [metersphere/metersphere#6170]
**请描述您的需求或者改进建议.**
我发现，我们这边研发对某个接口使用@ApiModelProperty进行声明，定义value值，在@ ApiModelProperty中value是字段声明的意思，而非key-value中的value。
但是倒入到ms平台后，发现定义该接口的请求参数里，直接将这个描述当作了key-value中的value值，而不是类似于描述字段的意思。

**请描述你建议的实现方案**
建议优化

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/7060
