### ISSUE TITLE
jmeter正常引用自定义jar包，同样的脚本在metersphere里面执行报错

### ISSUE THREAD

**Issue by nullapi** [metersphere/metersphere#6172]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.11.2-854acb67

**Bug 描述**

jmeter正常引用自定义jar包，同样的脚本在metersphere里面执行报错

**Bug 重现步骤**

1.  系统设置-jar包管理，导入自定义jar包
2. 接口case里面添加前置脚本，引用jar包，脚本复制的jmeter里的
3. 运行case

**期待的正确结果**
1，可以正常引用自定义脚本
正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/62641393/133366204-dbbace6e-dcf4-4808-bbb7-8bc1d1615a35.png)
![image](https://user-images.githubusercontent.com/62641393/133366225-cdac4ee0-ce53-4f57-bf76-bd0a2a015432.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，方便把自定义的jar包发我们试一下吗?我们的环境没有复现
