### ISSUE TITLE
[BUG]接口自动化执行调试之后，再点击终止过程中，出现页面报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6175]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

V1.12.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

**截图**

![image](https://user-images.githubusercontent.com/32027713/133367311-3fccfdd4-be04-4acd-9696-84de9977584f.png)

**Comment by xulinde** [comment]
未复现该问题，您能提供下稳定复现的方法吗
![image](https://user-images.githubusercontent.com/64065190/133545308-a86f1286-92a1-4059-8037-28265c977a6d.png)

**Comment by xulinde** [comment]
v1.13.1已修复
