### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by xioayihe** [metersphere/metersphere#6176]
**请描述您的问题.**clone 项目代码使用 admin : metersphere 登录只有系统设置一个菜单，如何查看其他菜单？
![image](https://user-images.githubusercontent.com/39754016/133367407-7fd4db23-2093-40ec-bbca-6537d2a13638.png)

**Comment by wangzhen-fit2cloud** [comment]
默认admin用户没有只有系统管理员权限，请参照默认安装包安装之后的admin用户权限，为admin用户添加工作空间及项目相关的角色。
