### ISSUE TITLE
[BUG]性能测试加载文件过程中，上传js文件出现页面报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6177]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.12.2

**Bug 描述**

简要描述您碰到的问题

性能测试加载文件过程中，上传js文件出现页面报错，哪怕文件类型不支持应该给个提示，而不是直接报错，这样太简单粗暴，用户很懵

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/32027713/133367534-2cd4d721-1e9e-4cc9-985f-c0688b1a6ff5.png)
后台出现枚举类型报错
![image](https://user-images.githubusercontent.com/32027713/133367594-4f89e143-0809-4850-a85d-74177a521966.png)

**Comment by xulinde** [comment]
已知问题，下个版本修复

**Comment by xulinde** [comment]
v1.12.3已修复
