### ISSUE TITLE
[FEATURE]Jenkins 插件测试计划支持选择和输入两种模式

### ISSUE THREAD

**Issue by zhangzhiganggit** [metersphere/metersphere#6178]
**请描述您的需求或者改进建议.**
因为大部分CI流水线中，测试计划是跟随着发布的分支来动态的选择测试计划，或者传入参数作为要执行的测试计划，总之是动态的。但是在meterSphere-jenkins插件中，测试计划是下拉框固定式的，这就需要运维人员不停的修改jenkins配置。

虽然用jenkins-pipline能解决问题，但是老项目都是自由风格的，他们切换成pipline项目是需要成本的

**请描述你建议的实现方案**
将测试计划的控件类型改为固定和动态传参两种模式，固定的话就是原来的方式。而如果选择动态传参就输入变量就行

**Comment by zyyfit** [comment]
最新版已支持
