### ISSUE TITLE
[BUG]mock接口填不同参数，没有按设置的期望返回结果，返回

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6183]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.2-67c53caa

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.
创建mock接口
![image](https://user-images.githubusercontent.com/30038088/133400340-f1131183-73de-4b40-b4e3-5af617b06915.png)
2.设置mock参数及返回结果
case1 设置如下
![image](https://user-images.githubusercontent.com/30038088/133400612-9a496ede-2dff-4661-985a-4cd00895b553.png)
case2 设置如下
![image](https://user-images.githubusercontent.com/30038088/133400705-371c1e81-7797-42a5-921d-0e25a5e2ccff.png)
3.
按照case1 请求参数，返回结果正确
![image](https://user-images.githubusercontent.com/30038088/133401215-f3898688-3185-4965-80dc-fb0c37bcc266.png)

4. 
按照case2 请求参数，返回结果不是期望设置的 
![image](https://user-images.githubusercontent.com/30038088/133401355-48e54a65-48aa-4f15-8821-a1563c61e498.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.12.3版本没有复现，您可以升级试试

**Comment by zyyfit** [comment]
复现了，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
