### ISSUE TITLE
[BUG]接口自动化执行的时候body的顺序不是用户case中输入的顺序

### ISSUE THREAD

**Issue by ggping66** [metersphere/metersphere#6187]
**MeterSphere 版本**
v1.12.0-a8cbf128

**Bug 描述**
接口自动化执行的时候这个body的顺序不是我case输入的顺序

**Bug 重现步骤**

1.  case输入顺序1
2. 自动化执行，查看顺序
3. 
4. 

**期待的正确结果**
按照用户case的顺序执行

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/23469661/133413682-f2559c7b-a178-46d0-81b9-a1ad896bf194.png)
![image](https://user-images.githubusercontent.com/23469661/133413701-052b2274-afee-4c52-acf3-bf3b9c51cec2.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
您好，排查发现发送后显示的顺序是jmeter控制的，考虑到json的顺序不影响请求结果，我们暂时不对这个地方进行修改
