### ISSUE TITLE
[BUG]【v1.12.2】采用jenkins插件，调用接口自动化测试场景用例，会一直处于running

### ISSUE THREAD

**Issue by hefeixiao** [metersphere/metersphere#6188]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.12.2
**Bug 描述**
采用jenkins插件，调用接口自动化测试场景用例，会一直处于running：
![image](https://user-images.githubusercontent.com/59219621/133422009-45fd3410-c24e-4fc9-8150-09388adbd576.png)

![image](https://user-images.githubusercontent.com/59219621/133422323-c3842076-3993-4cbd-a609-cf03e2f922cd.png)

![image](https://user-images.githubusercontent.com/59219621/133422442-098bcd62-9370-4d14-94b1-d4407baa6f9e.png)

简要描述您碰到的问题
测试报告显示，测试场景一直在Running

**Bug 重现步骤**

1.  jenkins 配置job
2. ms配置接口场景用例
3. 构建
4. 查看构建日志及ms平台测试报告

**期待的正确结果**

正确情况下应该是什么样的？
正确应该是跟手动执行一样，出测试报告
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.12.3已修改，请升级后试试
