### ISSUE TITLE
[BUG]测试计划里面的用例（API调用方式触发的接口测试）无法查看测试结果

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#619]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1

**Bug 描述**
简要描述您碰到的问题

在用例这边，为啥不能直接查看接口测试的执行结果呢。。。
用例是选择的接口测试，自动
执行方式是通过Jenkins调用，API调用方式触发的

对于一个失败用例，状态是失败那里点击
![image](https://user-images.githubusercontent.com/3426719/97271513-9bd61d00-186b-11eb-9e4d-33e038dddd86.png)

这里点进去，看接口测试的详细信息好像没啥用呀，我需要看到这次执行的错误信息
点击到测试结果，显示尚未执行

![image](https://user-images.githubusercontent.com/3426719/97271915-2c146200-186c-11eb-9833-5d00dbda9c11.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by yanghuizhi** [comment]
hi，兄弟，我也遇到了这个问题，我想请教一下你 @hanbi ，是怎么操作的，我找了整个api，都不知道要怎么操作，希望你看到可以联系我
