### ISSUE TITLE
[BUG] 【V1.12.2】集合跑接口自动化测试报告一只处于Running 状态！复现率较高 备注：已经选资源池

### ISSUE THREAD

**Issue by yuanhongda** [metersphere/metersphere#6191]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  批量执行接口自动化
![image](https://user-images.githubusercontent.com/22175969/133435750-c66bd5a0-0c75-4877-8cda-6b2b06955a17.png)

2. 生成报告一只处于Runing

**期待的正确结果**
正常执行完成，测试报告结果为Success

正确情况下应该是什么样的？
正常执行完成，测试报告结果为Success

**截图**
![image](https://user-images.githubusercontent.com/22175969/133436006-9c074af7-923b-430a-8fde-d0f4adc950ad.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.12.3针对这类问题进行了修复，请升级后试试
