### ISSUE TITLE
[BUG]测试用例模板增加自定义字段后，创建测试用例保存不了

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#6195]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
1.12.2
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
测试用例模板增加自定义字段后，创建测试用例保存不了
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="959" alt="6c41656a8cd1b32286a88062d63309c" src="https://user-images.githubusercontent.com/85992665/133537634-1833bae5-515d-4a04-ad0b-879a0a745a8b.png">

**Comment by xulinde** [comment]
前端有报错信息吗，发一下

**Comment by Sensivitiry** [comment]
> 前端有报错信息吗，发一下

没有报错信息，点了没有反应，已经反馈过了

**Comment by zyyfit** [comment]
最新版还有这个问题吗

**Comment by Sensivitiry** [comment]
> 最新版还有这个问题吗

没有了
