### ISSUE TITLE
[BUG]恢复接口用例失败

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6196]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

简要描述您碰到的问题
恢复接口用例失败
**Bug 重现步骤**

1.  一个接口，在接口下有一个用例
2. 删除用例
3. 删除接口
4. 恢复接口
5. 恢复接口对应用例

**期待的正确结果**

正确情况下应该是什么样的？
用例从回收站移除恢复到CASE列表
**截图**

如果有截图，请附上截图.
[
<img width="1437" alt="截屏2021-09-16 10 19 54" src="https://user-images.githubusercontent.com/36387811/133539425-d4861285-6fa2-4032-a1c1-49fe05c500c3.png">
](url)

**Comment by xulinde** [comment]
感谢反馈，下个版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
