### ISSUE TITLE
[BUG]Ubuntu1804离线安装MeterSphere需要修改install.sh脚本，不能与Ubuntu1804适配

### ISSUE THREAD

**Issue by AsDuang** [metersphere/metersphere#6198]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.12.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
Ubuntu1804离线安装MeterSphere-v1.12.1

![截图01](https://user-images.githubusercontent.com/22571568/133543272-8e33e4cd-02d2-4b1b-a101-77d48bb1f13b.png)

在安装时修改了安装脚本，将/usr/bin/cp --> cp .  

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by yuanhongda** [comment]
我每次都修改因为在ubuntu 下载cp 是在/bin/cp

**Comment by zyyfit** [comment]
1.12.3版本已修复
