### ISSUE TITLE
[FEATURE]添加全局断言

### ISSUE THREAD

**Issue by lulucky515a** [metersphere/metersphere#6203]
**请描述您的需求或者改进建议.**
现在的metersphere中，只有针对于单个接口的断言，无法实现针对于场景的全局断言。
就是针对一个场景的每个接口只要输入一次断言规则，就可以对每个接口实现断言，这样可以简化很多操作步骤。

**请描述你建议的实现方案**
希望能添加针对于场景的全局断言，就像postman或者jmeter那样的全局断言。

**Comment by xulinde** [comment]
目前是支持场景级别断言的，您可以现在步骤里加断言，然后拖拽到步骤外，就是场景级别的了

**Comment by lulucky515a** [comment]
好的，我试试👌
