### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6207]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.10.4-221f275f

**Bug 描述**
复制本地的Xmind用例到脑图时有丢失   且  脑图中用例后的二级节点有多个分支时，保存后合并成了一个分支

**Bug 重现步骤**
1.  复制一个包含三级节点的思维导图用例
2. 粘贴在MeterSphere 上
3. 添加对应的标签之后保存
4. 查询保存结果

**期待的正确结果**
保存复制的原格式

正确情况下应该是什么样的？
**截图**
![image](https://user-images.githubusercontent.com/90616297/133547755-62326c22-ab3d-43fd-b5ae-dd90f69c142d.png)

**Comment by zyyfit** [comment]
您好，打上P0标签后就表示这一级是用例标题了，然后只能再有两个下层，也就是 【标题 - 用例步骤 -用例预期结果】 这样，然后多的步骤会被合并或者保存不上，建议您根据我们的模板格式编写用例
