### ISSUE TITLE
[FEATURE]新建用例入口固定展示，打开用例比较多的时候，新建入口不方便查找

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6214]
**请描述您的需求或者改进建议.**

建议：新建用例入口固定展示，打开用例比较多的时候，新建入口不方便查找
![image](https://user-images.githubusercontent.com/90616297/133555806-5da33057-78df-40c2-be3f-25a5d7249ff5.png)

**Comment by xulinde** [comment]
收到，可以优化

**Comment by luty2018** [comment]
已实现，请更新到v2.7使用。
