### ISSUE TITLE
[FEATURE]应该是保存而不是添加

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6215]
**请描述您的需求或者改进建议.**

点击编辑后，按钮的功能时保存，按钮上的文字是添加

**请描述你建议的实现方案**
将添加改为保存
步骤
1接口定义
2定时同步
3任务通知
4编辑
<img width="851" alt="截屏2021-09-16 11 20 35" src="https://user-images.githubusercontent.com/36387811/133556396-e4fcd3e5-bf00-4ec3-971f-4bd1edc113df.png">

**Comment by xulinde** [comment]
v1.12.3提示就是“保存成功”，您用的是哪个版本
![image](https://user-images.githubusercontent.com/64065190/133717656-6cca2697-efba-41eb-bcae-582875a1a4d6.png)

**Comment by pb123abc** [comment]
1.12.2

**Comment by xulinde** [comment]
建议您升级下版本
