### ISSUE TITLE
[BUG]测试计划的用例列表，分页选择100条/页，页面要卡住10s以上

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#622]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1

**Bug 描述**
简要描述您碰到的问题
[BUG]测试计划的用例列表，进入这个页面就很卡，选择的分页是100条/页
一共160个接口

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
3s内正常

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，1.4.1 中已优化，请升级验证
