### ISSUE TITLE
[BUG] 响应体是html格式，用相同的方法在jmeter里可以提取到信息，在MS无法提取信息。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6222]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.11.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/133564478-ce2e5cf5-7367-42c1-9957-a2bfbb3180fb.png)
![image](https://user-images.githubusercontent.com/78218624/133564540-3e0ee402-11dd-44d1-be17-2d2be2707cbd.png)
![image](https://user-images.githubusercontent.com/78218624/133564697-4663cf03-7ff4-4678-89fe-8078f5d7b925.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
目前不支持提取html

**Comment by zyyfit** [comment]
1.14.2已支持
