### ISSUE TITLE
[FEATURE]用例中上传附件支持直接复制粘贴

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6224]
**请描述您的需求或者改进建议.**

建议：用例中上传附件建议能直接复制粘贴的方式会更方便些，类似运营活动类项目需要大量截图
![image](https://user-images.githubusercontent.com/90616297/133568559-a161026b-c00a-4b89-b81e-a38548559e21.png)

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
