### ISSUE TITLE
[FEATURE]执行用例时编辑实际结果&步骤执行结果时页面抖动优化

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6225]
**请描述您的需求或者改进建议.**

问题：执行用例时编辑实际结果&步骤执行结果时，页面抖动，建议优化

![image](https://user-images.githubusercontent.com/90616297/133569762-46bdef69-a382-4af0-9d9c-605ebfcd7a05.png)

**Comment by xulinde** [comment]
感谢您的反馈，后面版本优化

**Comment by zyyfit** [comment]
您好，最近几个版本优化了这个问题，请问还有复现吗
