### ISSUE TITLE
[BUG]xmind格式导入用例超过800条提示不一致

### ISSUE THREAD

**Issue by liumei2016** [metersphere/metersphere#6226]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**
上传测试用例时，报错提示导入用例量不能超过500（但是提示告知支持导入800条测试用例）

**Bug 重现步骤**
1.  导入脑图用例
2. 查看提示信息

正确情况下应该是什么样的？
实际支持上传条数与文案一致

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/90616297/133571116-c1a4852a-67ea-4f4e-be3f-1b280b2cfb0f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
