### ISSUE TITLE
[FEATURE]接口测试增加编码设置

### ISSUE THREAD

**Issue by wxcen** [metersphere/metersphere#6228]
**请描述您的需求或者改进建议.**
在接口定义或case等页面，在其他设置 TAB 选项增加选择编码。

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/40848979/133574051-55281724-a519-4ef5-9100-e0c83e464693.png)

**Comment by xulinde** [comment]
已在后续版本规划中

**Comment by wxcen** [comment]
有规划到具体哪个版本中吗？

**Comment by 35plus** [comment]
会有哪些编码类型呢？UTF8?

**Comment by wxcen** [comment]
编码的类型其实就那么多，UTF-8.GBK等
