### ISSUE TITLE
[BUG]通过Jenkins调用测试计划执行接口测试，用的环境配置还是旧的，环境配置更新以后，不会跟着更新

### ISSUE THREAD

**Issue by hanbi** [metersphere/metersphere#623]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1

**Bug 描述**
简要描述您碰到的问题
通过Jenkins调用测试计划执行接口测试，用的环境配置还是旧的，环境配置更新以后，不会跟着更新

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，感谢您的反馈。已知问题，预计v1.5.0版本或者v1.6.0会修复，您到时候直接升级下就可以了。
