### ISSUE TITLE
[QUESTION]如何能自动设置同一个工作空间下所有项目的权限？

### ISSUE THREAD

**Issue by qiaolb** [metersphere/metersphere#6232]
**如何能自动设置同一个工作空间下所有项目的权限？**

我的需求是在同一个工作空间，任何用户对所有项目权限相同。我们希望将我们测试团队的人增加到工作空间中，给他们指定好角色，那么在未来当在这个工作空间中新增项目时，这些成员对新项目的权限自动和之前老项目相同，无需再进行设置。也就是可以将用户的权限指定到工作空间。
目前系统是必须将权限按照项目指定，这样当我增加项目时，就必须给每个人重新设置一次权限。

另外，目前我们的用法是，在同一个工作空间中，将产品的不同版本作为不同的项目，这样对测试用例只包含本版本的用例，测试计划可以跨项目进行规划。使用有更好的做法。

谢谢！

**Comment by zyyfit** [comment]
现在有将用户批量添加到工作空间或者项目的选项了，不知道能否满足您的需要
![图片](https://user-images.githubusercontent.com/73461316/140028552-7a0e701d-310b-48a7-bf40-855f6976a60f.png)
