### ISSUE TITLE
[BUG] 项目环境配置：设置host后，在域名里直接配置ip（此不在host配置列表里），此域名下的接口，运行系统返回空指针；关闭host，此接口就能正常执行

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6234]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.12

**Bug 描述**

项目环境配置：设置host后，在域名里直接配置ip（此不在host配置列表里），此域名下的接口，运行系统返回空指针

**Bug 重现步骤**

1.   项目设置>>通用配置：打开host设置相关信息
2.  项目设置>>http配置：添加域A，地址设置为ip地址，此ip不在host配置里。
3.  A域下的接口，运行都会报空指针。关闭host，然后在运行此接口，都能正常运行
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/133588075-52b62261-8ccf-47a0-bdb4-9fa23f4ab103.png)

![image](https://user-images.githubusercontent.com/78218624/133589144-f2915cec-b3e3-4335-8c04-354887634c47.png)

如果有截图，请附上截图.

**Comment by huangxine** [comment]
缺少两个图
![1631785397(1)](https://user-images.githubusercontent.com/78218624/133590092-5175e632-fe8c-4249-ab2c-42fa0bb272b1.png)
![1631785484(3)](https://user-images.githubusercontent.com/78218624/133590138-14131351-8126-4a49-965f-8b10ff153165.png)

**Comment by zyyfit** [comment]
您好，之前确实有过这个问题，但是后来修复了，最新版和1.12.1都未复现这个问题，您可以升级试试
