### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by wangwl1203** [metersphere/metersphere#6238]
1. 针对性能测试，jmeter支持使用自定义函数(比如：${__createRandomString(32,)}) 来赋予某个字段值，在metersphere是否支持自定义函数，或者要怎么设置？
2. 性能测试，发起测试后，请求的报文是否会记录到文件或者落表？

**Comment by wangzhen-fit2cloud** [comment]
1. 性能测试支持自定义函数需要将自定义函数的jar包上传到系统上。
