### ISSUE TITLE
[FEATURE] 支持项目的复制操作

### ISSUE THREAD

**Issue by gongbaojid** [metersphere/metersphere#6241]
**请描述您的需求或者改进建议.**

存在同时需要维护多个版本的场景，每个版本对应不同项目，但是如果将前一个项目的测试用例导出后，导入到另外一个项目，所有之前引用的用例都显示为复制，不方便用例维护

**请描述你建议的实现方案**
建议支持复制项目，包括项目里面的case以及场景的引用关系

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下

**Comment by luty2018** [comment]
已实现，导入会保留引用关系，请更新到v2.7使用。
