### ISSUE TITLE
[BUG]从1.8升级到1.12.2之后在接口测试页面的控制台不打印自定义日志

### ISSUE THREAD

**Issue by zhao103804** [metersphere/metersphere#6244]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**
从1.8升级到1.12.2之后在接口测试页面的控制台里面怎么不打印自己加的日志信息了？

**Bug 重现步骤**

1.  使用python前置脚本时，写print("xx")  或者 logging.info("xxx") 这种打印在控制台都不显示

[](url)

**期待的正确结果**

正确情况下应该是什么样的？

控制台显示自定义打印日志

**截图**

如果有截图，请附上截图
![123](https://user-images.githubusercontent.com/29306248/133712090-41915fb0-79ed-4b5b-ad44-030faf5cdb09.png)

.

**Comment by xulinde** [comment]
使用log.info()
