### ISSUE TITLE
[FEATURE]测试计划关联测试用例时，希望能支持：根据关联的jira需求/任务、或bug，进行筛选出对应的测试用例。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6247]
**请描述您的需求或者改进建议.**

测试计划关联测试用例时，希望能支持：根据关联的jira需求/任务、或bug，进行筛选出对应的测试用例。

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已实现，在高级搜索中添加了，请更新到v2.7使用。
