### ISSUE TITLE
[FEATURE]测试用例列表搜索结果和脑图展示一致

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6259]
**请描述您的需求或者改进建议.**
如：在测试用例搜索中搜索标签“消息”，搜索结果有20个。那切换到脑图后，脑图也只显示对应20个的用例。
在用例评审和测试计划中可以应用同样的形式

**请描述你建议的实现方案**
如：在测试用例搜索中搜索标签“消息”，搜索结果有20个。那切换到脑图后，脑图也只显示对应20个的用例。
在用例评审和测试计划中可以应用同样的形式

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估涉及到脑图的相关变更，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
