### ISSUE TITLE
[BUG]性能压测kafka下会产生超多的压测记录log且没有清理

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#626]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/70927987/97388762-b5cb3a80-1913-11eb-8552-3a77079d6cf7.png)
metersphere/data/kafka/kafka/data/JMETER_METRICS-0下有压测的log日志没有清理，且这个文件很大

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by rzsp8552** [comment]
也遇到这个情况，是不是最多存了几十G

**Comment by wangzhen-fit2cloud** [comment]
你好，1.4.1 之后修改了默认的日志留存时长，请升级验证

**Comment by Anduin-Zhu** [comment]
我的做了个长时间压测，晚上18:00-2:00kafka打满了700G的空间，
