### ISSUE TITLE
[BUG]jmeter创建的jmx接口文件导入MS，请求头没有导进来。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6267]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

jmeter创建的jmx接口文件导入MeterSphere，请求头没有导进来。
jmeter中的Http信息头管理器为全局变量，如下图这种，HTTP信息头管理器和HTTP请求同级。
![image](https://user-images.githubusercontent.com/87106917/133746557-11de17c4-35b9-421e-bd2e-72323d487ad1.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是导入场景中吗？jmx导入场景中后请求头管理器会在场景中的，不会单独提取到场景中的场景变量中
![image](https://user-images.githubusercontent.com/73461316/134535515-94a17ba6-e5df-455b-a8a7-df86c53bb374.png)

**Comment by liuhansong** [comment]
是导入到接口列表中发自我的华为手机

**Comment by zyyfit** [comment]
导入接口列表的话需要将 http头管理器。放到 接口下面。放到线程组下会导入到场景，不会导入到单个接口
