### ISSUE TITLE
【建议】测试计划内关联的用例，分组后展示对应的用例数量

### ISSUE THREAD

**Issue by nevertokeep** [metersphere/metersphere#6269]
**请描述您的需求或者改进建议.**
测试跟踪-测试计划，关联测试用例后，希望显示用例数量

**请描述你建议的实现方案**
希望能同测试跟踪-测试用例，用例数量展示一致

**附件**
![image](https://user-images.githubusercontent.com/59011106/133748326-ecf14db5-6152-49ee-82b3-e8e64c623a5d.png)
![image](https://user-images.githubusercontent.com/59011106/133748429-05e72d61-d9fd-462f-9178-2adbb72a514a.png)

**Comment by xulinde** [comment]
感谢您的建议，后面会优化这里

**Comment by luty2018** [comment]
已实现，请更新到v2.7使用。
