### ISSUE TITLE
[BUG][接口测试]接口测试中涉及上传文件的接口，点击批量执行时会抱错找不到文件

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#627]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.3.1

**Bug 描述**
接口测试中涉及上传文件的接口，点击批量执行时会抱错找不到文件，批量执行相当于生成了一个新的场景，就有一个新的id了，文件在这个路径下就会找不到

**Bug 重现步骤**
1.  新建场景1，有上传文件的接口
2. 新建场景2
3. 选择场景1和2点击批量执行

**期待的正确结果**
可以正确执行

**截图**

**Comment by AgAngle** [comment]
1.4版本已修复，请升级验证
