### ISSUE TITLE
【建议】用例列表，增加分组层级

### ISSUE THREAD

**Issue by nevertokeep** [metersphere/metersphere#6270]
**请描述您的需求或者改进建议.**

用例右侧列表，展示分组层级，目前有点乱

**请描述你建议的实现方案**
<img width="1004" alt="wecom-temp-7de5082ed5ec5c89b3b669ca2cafd369" src="https://user-images.githubusercontent.com/59011106/133749037-270be5f2-c849-4d2f-885a-51fc03cb4900.png">

**Comment by xulinde** [comment]
目前这样，您觉得哪里不合理呢
![image](https://user-images.githubusercontent.com/64065190/134484149-c0101b12-d256-499e-98ce-c6114be95a1f.png)

**Comment by nevertokeep** [comment]
> 目前这样，您觉得哪里不合理呢
> ![image](https://user-images.githubusercontent.com/64065190/134484149-c0101b12-d256-499e-98ce-c6114be95a1f.png)

您好，您的截图是左侧用例分组菜单，我指的是右侧用例列表，我期望右侧yo用例列表页显示分组，像tb那样
![image](https://user-images.githubusercontent.com/59011106/134609622-9736ccaa-4980-4c4f-a4b4-2890d1331ced.png)

**Comment by zyyfit** [comment]
您是指这个吗
![image](https://user-images.githubusercontent.com/73461316/140087931-b9cfb892-3773-4614-aeb4-58397f8fc19d.png)
