### ISSUE TITLE
[BUG]测试计划关联测试用例，先勾选，查询后清空勾选状态再次勾选，出现重复关联测试用例

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6271]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.0
**Bug 描述**

测试计划关联测试用例，先勾选，查询后清空勾选状态再次勾选，出现重复关联测试用例
**Bug 重现步骤**
1、测试计划-关联测试用例
2、先勾选一条测试用例，然后点击查询或者以20条/页显示，会清空勾选状态
3、重复勾选上次勾选的测试用例

**期待的正确结果**

正确情况下应该是什么样的？

截图
![image](https://user-images.githubusercontent.com/87106917/133749335-0a185607-9676-4fcd-aef0-3d89dfb40ec2.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
已知问题，下个版本会修复

**Comment by xulinde** [comment]
v1.13已修复
