### ISSUE TITLE
【建议】用例执行页，评论增加图片后的提示，不要遮挡操作栏

### ISSUE THREAD

**Issue by nevertokeep** [metersphere/metersphere#6272]
**请描述您的需求或者改进建议.**

用例执行页，评论增加图片后，toast提示不要遮挡操作栏

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/59011106/133749509-6c3a5ca7-dfe4-419e-9164-36d9b49dae27.png)

**Comment by xulinde** [comment]
感谢您的建议，可以优化下这里

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
