### ISSUE TITLE
[FEATURE] 测试用例的链接不能精确定位到某个模块。

### ISSUE THREAD

**Issue by yangjing1981** [metersphere/metersphere#6273]
**请描述您的需求或者改进建议.**
1.  我在Auth下写了2个测试用例，我再提交测试报告的时候，希望可以给别人别人看到Auth路径下的测试用例。
![image](https://user-images.githubusercontent.com/24752474/133749060-97ad2d69-3fc6-40e1-8c39-bce2c51d4f02.png)

2. 实际情况是，拷贝url链接，再打开，只会显示这个项目的所有测试用例。
![image](https://user-images.githubusercontent.com/24752474/133749361-f08c196a-ee3f-4b99-a90a-17249b2b14ff.png)

**请描述你建议的实现方案**
我希望链接可以精确定位到项目下的某个模块。
![image](https://user-images.githubusercontent.com/24752474/133749060-97ad2d69-3fc6-40e1-8c39-bce2c51d4f02.png)

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，计划在v2.7.1版本发布（计划发布时间2023.3.3）。

**Comment by zrfit** [comment]
您好，v2.7.1已修复该问题，待发布后可升级验证。
