### ISSUE TITLE
【建议】用例批量操作层级太深，希望提高操作效率，实现批量的意义

### ISSUE THREAD

**Issue by nevertokeep** [metersphere/metersphere#6274]
**请描述您的需求或者改进建议.**
希望选中用例的chekbox，操作栏自动显示，一键批量操作成功
目前metersphere需要8步，teambition仅需3步

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/59011106/133750112-0e2cd06a-2663-4d3f-940b-f511b4940a98.png)
![image](https://user-images.githubusercontent.com/59011106/133750111-599fd15f-9756-4eb8-86ec-135277806ada.png)

**Comment by xulinde** [comment]
感谢您的建议，这里会持续优化～

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
