### ISSUE TITLE
[FEATURE] “计划名称“和”评审名称“限制是30，完全不够用，修改到255，对使用者会比较友好。

### ISSUE THREAD

**Issue by yangjing1981** [metersphere/metersphere#6275]
**请描述您的需求或者改进建议.**
1. 测试用例的名字限制是255，比较合理。
![image](https://user-images.githubusercontent.com/24752474/133750510-4d34cbd4-d3c1-401b-978a-aa189771e9c3.png)
2. 测试计划的“计划名称“限制是30，完全不够用。
![image](https://user-images.githubusercontent.com/24752474/133750740-33fad3bf-ef8c-4bab-a836-78791fafac25.png)
3. 评审名称也是限制的30，完全不够用。
![image](https://user-images.githubusercontent.com/24752474/133752181-2e70a5b7-be62-404a-ae08-38105603a9d8.png)

**请描述你建议的实现方案**
如果测试计划的“计划名称“限制修改到255，对使用者会比较友好。

**Comment by xulinde** [comment]
感谢您的建议，我们先调研下

**Comment by xulinde** [comment]
最新版本v1.20.4已做优化
1.测试用例的名字限制是225；
2.测试计划的“计划名称“限制是128
