### ISSUE TITLE
[BUG]【接口测试】环境变量里面通用配置的名称显示异常

### ISSUE THREAD

**Issue by Ammyz** [metersphere/metersphere#628]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4.0
**Bug 描述**
环境变量里面通用配置的名称显示异常，有部分白色的遮挡区域，没有内容也不能展示现在的名称（且没有直接复制变量按钮了，建议还是加上）

**截图**
![image](https://user-images.githubusercontent.com/13564069/97404452-187eff00-1931-11eb-8a19-fcab2579615f.png)

**Comment by wangzhen-fit2cloud** [comment]
1.4.1 中已解决，请升级验证
