### ISSUE TITLE
[BUG]快捷调试和自动化里添加自定义请求，QUERY 和 REST 参数没有生效，在编辑api 处调试是可以的

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6280]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.2-67c53caa
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个快捷调试 或者 场景里添加一个自定义请求，设置QUERY或者REST参数
![image](https://user-images.githubusercontent.com/30038088/133755226-6c285c97-0e50-4092-a621-6ee9b54dc8db.png)
2. 请求结果中 参数未设置在url
![image](https://user-images.githubusercontent.com/30038088/133755438-9eaeb14f-7e8d-4c3d-bab1-44d52784ec19.png)
3. 在编辑api 处调试是可以的
![image](https://user-images.githubusercontent.com/30038088/133755589-c6321adb-9f55-4f67-ab93-59320eb752f1.png)

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，不过看您 2 中的这个截图，像是自动跳转到登录了，您可以添加上token试一下

**Comment by shenkaibo** [comment]
刚试了下，新版本没有这个问题了
