### ISSUE TITLE
[BUG]postman上选择的body格式为json,但postman接口导出后导入MS平台，body格式变为raw。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6281]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

postman上接口用例选择的body格式为json,但postman接口导出后导入MS平台，body格式变为raw。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/87106917/133756505-7ee6798e-513d-46cc-8ad6-b49f73830166.png)

![image](https://user-images.githubusercontent.com/87106917/133756484-859a51c7-5265-40fa-a3a5-c43566fd2c23.png)

如果有截图，请附上截图.

**Comment by yaming116** [comment]
json 是 raw 数据的一种格式
