### ISSUE TITLE
[BUG]性能测试报告多了之后，删除报告会一直显示在加载中，删不掉。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6283]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

简要描述您碰到的问题
load_test_report_detail 有很多脏数据
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
是批量删除吗，大概多少条数据呢

**Comment by liuhansong** [comment]
单条删除

**Comment by xulinde** [comment]
未复现该问题
