### ISSUE TITLE
[BUG]JsonPath 断言报错

### ISSUE THREAD

**Issue by xu6han** [metersphere/metersphere#6290]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**JsonPath 断言失败**

**Bug 重现步骤**

1.  正确返回json，不过json中list包含list
2. 选择JsonPath 断言失败 窗口正常弹出
3. 选择key和value 报错
4.结构如下：{
    "code": 0,
    "data": {
        "rows": [
            [
                {
                    "key": "quality_group.customer_external_id",
                    "value": "1630704716602"
                },
                {
                    "key": "quality_group.customer_name",
                    "value": "客户_1630704716602"
                },
                {
                    "key": "quality_group.staff_id",
                    "value": "222222"
                },
                {
                    "key": "quality_group.staff_name",
                    "value": "王广福—001"
                },
                {
                    "key": "quality.last_contact_time",
                    "value": "2021-09-04 05:31:57"
                },
                {
                    "key": "quality.last_upload_time",
                    "value": "2021-09-04 05:31:57"
                },
                {
                    "key": "quality_group.conversation_count",
                    "value": 2
                },
                {
                    "key": "quality.is_qualified",
                    "value": "合格"
                },
                {
                    "key": "quality.qualified_score",
                    "value": 95
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "1111",
                            "rule_name": "沟通"
                        },
                        {
                            "rule_id": "2222",
                            "rule_name": "微信"
                        },
                        {
                            "rule_id": "3333",
                            "rule_name": "爸爸"
                        },
                        {
                            "rule_id": "4444",
                            "rule_name": "妈妈"
                        },
                        {
                            "rule_id": "55555",
                            "rule_name": "加分1"
                        },
                        {
                            "rule_id": "6666",
                            "rule_name": "噢"
                        },
                        {
                            "rule_id": "7777",
                            "rule_name": "没空"
                        }
                    ]
                },
                {
                    "key": "quality.complex",
                    "value": [
                        {
                            "complex_rule_id": "1111",
                            "complex_rule_name": "关：沟通&爸爸=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "22222",
                            "complex_rule_name": "关：年份不等于1&加分2=合规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality.id",
                    "value": "11111"
                },
                {
                    "key": "quality.last_upload_time",
                    "value": "2021-09-04 05:31:57"
                }
            ],
            [
                {
                    "key": "quality_group.customer_external_id",
                    "value": "1630669890263"
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "1111",
                            "rule_name": "妈妈"
                        }
                    ]
                },
                {
                    "key": "quality_group.complex_entity",
                    "value": [
                        {
                            "complex_rule_id": "33333",
                            "complex_rule_name": "关：沟通&爸爸=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "333333",
                            "complex_rule_name": "关：通话时长大于等于30&请问=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "33333",
                            "complex_rule_name": "关：噢&加分1=合规",
                            "qualified": false
                        },
                        {
                            "complex_rule_id": "33333",
                            "complex_rule_name": "关：妈妈&没空=违规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality_group.id",
                    "value": "e0c25593-12d6-4764-af3f-ab817f59629a"
                },
                {
                    "key": "user_defined_values.4",
                    "value": "12.00"
                },
                {
                    "key": "user_defined_values.5",
                    "value": "王武"
                },
                {
                    "key": "quality_upload_time",
                    "value": "2021-09-03 19:51:31"
                },
                {
                    "key": "quality_group.verify_status",
                    "value": "未复检"
                },
                {
                    "key": "quality_group.verify_time",
                    "value": ""
                },
                {
                    "key": "quality_group.verify_staff_name",
                    "value": ""
                }
            ],
            [
                {
                    "key": "quality_group.customer_external_id",
                    "value": "234234"
                },
                {
                    "key": "quality_group.customer_name",
                    "value": "客户_1630667125606"
                },
                {
                    "key": "quality_group.staff_id",
                    "value": "23234"
                },
                {
                    "key": "quality_group.staff_name",
                    "value": "王广福—001"
                },
                {
                    "key": "quality.last_contact_time",
                    "value": "2021-09-03 19:05:26"
                },
                {
                    "key": "quality.last_upload_time",
                    "value": "2021-09-03 19:05:27"
                },
                {
                    "key": "quality_group.rule_group_id",
                    "value": "234234"
                },
                {
                    "key": "quality_group.rule_group_name",
                    "value": "多：关联"
                },
                {
                    "key": "quality_group.conversation_count",
                    "value": 1
                },
                {
                    "key": "quality.is_qualified",
                    "value": "合格"
                },
                {
                    "key": "quality.qualified_score",
                    "value": 95
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "234234",
                            "rule_name": "爸爸"
                        },
                        {
                            "rule_id": "234234",
                            "rule_name": "妈妈"
                        },
                        {
                            "rule_id": "234234",
                            "rule_name": "微信"
                        },
                        {
                            "rule_id": "234234",
                            "rule_name": "噢"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "沟通"
                        },
                        {
                            "rule_id": "234234234",
                            "rule_name": "没空"
                        }
                    ]
                },
                {
                    "key": "quality_group.complex_entity",
                    "value": [
                        {
                            "complex_rule_id": "234234",
                            "complex_rule_name": "关：通话时长大于等于30&请问=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "234234234",
                            "complex_rule_name": "关：噢&加分1=合规",
                            "qualified": false
                        },
                        {
                            "complex_rule_id": "234324324",
                            "complex_rule_name": "关：爸爸&妈妈=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "234234",
                            "complex_rule_name": "关：妈妈&没空=违规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality_group.id",
                    "value": "7fd9"
                },
                {
                    "key": "quality_group.last_upload_time",
                    "value": "2021-09-03 19:05:27"
                },
                {
                    "key": "quality_group.verify_status",
                    "value": "未复检"
                },
                {
                    "key": "quality_group.verify_time",
                    "value": ""
                },
                {
                    "key": "quality_group.verify_staff_name",
                    "value": ""
                }
            ],
            [
                {
                    "key": "quality_group.customer_external_id",
                    "value": "1630667123023"
                },
                {
                    "key": "quality_group.customer_name",
                    "value": "客户_1630667123023"
                },
                {
                    "key": "quality_group.staff_id",
                    "value": "234324"
                },
                {
                    "key": "quality_group.staff_name",
                    "value": "王广福—001"
                },
                {
                    "key": "quality.last_contact_time",
                    "value": "2021-09-03 19:05:24"
                },
                {
                    "key": "quality.last_upload_time",
                    "value": "2021-09-03 19:05:24"
                },
                {
                    "key": "quality_group.rule_group_id",
                    "value": "234234"
                },
                {
                    "key": "quality_group.rule_group_name",
                    "value": "多：关联"
                },
                {
                    "key": "quality_group.conversation_count",
                    "value": 1
                },
                {
                    "key": "quality.is_qualified",
                    "value": "合格"
                },
                {
                    "key": "quality.qualified_score",
                    "value": 95
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "234",
                            "rule_name": "沟通"
                        },
                        {
                            "rule_id": "9590001f8fdfe",
                            "rule_name": "噢"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "爸爸"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "微信"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "妈妈"
                        },
                        {
                            "rule_id": "324324",
                            "rule_name": "加分1"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "没空"
                        }
                    ]
                },
                {
                    "key": "quality_group.complex_entity",
                    "value": [
                        {
                            "complex_rule_id": "234324",
                            "complex_rule_name": "关：年份不等于1&加分2=合规",
                            "qualified": false
                        },
                        {
                            "complex_rule_id": "234324",
                            "complex_rule_name": "关：通话时长大于等于30&请问=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "234234",
                            "complex_rule_name": "关：噢&2341=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "234324",
                            "complex_rule_name": "关：爸爸&妈妈=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "234234",
                            "complex_rule_name": "关：妈妈&没空=违规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality_group.id",
                    "value": "52-b402-23"
                },
                {
                    "key": "quality_group.last_upload_time",
                    "value": "2021-09-03 19:05:24"
                },
                {
                    "key": "quality_group.verify_status",
                    "value": "未复检"
                },
                {
                    "key": "quality_group.verify_time",
                    "value": ""
                },
                {
                    "key": "quality_group.verify_staff_name",
                    "value": ""
                }
            ],
            [
                {
                    "key": "quality_group.customer_external_id",
                    "value": "23423"
                },
                {
                    "key": "quality_group.customer_name",
                    "value": "客户2342342"
                },
                {
                    "key": "quality_group.staff_id",
                    "value": "234324"
                },
                {
                    "key": "quality_group.staff_name",
                    "value": "王广福—001"
                },
                {
                    "key": "quality.last_contact_time",
                    "value": "2021-09-03 18:54:59"
                },
                {
                    "key": "quality.last_upload_time",
                    "value": "2021-09-03 18:54:59"
                },
                {
                    "key": "quality_group.rule_group_id",
                    "value": "234"
                },
                {
                    "key": "quality_group.rule_group_name",
                    "value": "多：关联"
                },
                {
                    "key": "quality_group.conversation_count",
                    "value": 1
                },
                {
                    "key": "quality.is_qualified",
                    "value": "合格"
                },
                {
                    "key": "quality.qualified_score",
                    "value": 90
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "234324",
                            "rule_name": "妈妈"
                        },
                        {
                            "rule_id": "234234",
                            "rule_name": "微信"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "噢"
                        },
                        {
                            "rule_id": "234234",
                            "rule_name": "沟通"
                        },
                        {
                            "rule_id": "324234",
                            "rule_name": "没空"
                        },
                        {
                            "rule_id": "234324",
                            "rule_name": "爸爸"
                        }
                    ]
                },
                {
                    "key": "quality_entity",
                    "value": [
                        {
                            "complex_rule_id": "11111",
                            "complex_rule_name": "关：通话时长大于等于30&请问=合规",
                            "qualified": true
                        },
                        {
                            "complex_rule_id": "22222",
                            "complex_rule_name": "关：噢&加分1=合规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality_status",
                    "value": "未复检"
                },
                {
                    "key": "quality_time",
                    "value": ""
                },
                {
                    "key": "quality_name",
                    "value": ""
                }
            ],
            [
                {
                    "key": "qualitygroup_id",
                    "value": "22222"
                },
                {
                    "key": "quality.rule_name",
                    "value": "多：关联"
                },
                {
                    "key": "quality.conversation",
                    "value": 1
                },
                {
                    "key": "quality.qualified",
                    "value": "合格"
                },
                {
                    "key": "quality.score",
                    "value": 95
                },
                {
                    "key": "quality_group.rule",
                    "value": [
                        {
                            "rule_id": "7777",
                            "rule_name": "爸爸"
                        },
                        {
                            "rule_id": "666666",
                            "rule_name": "妈妈"
                        },
                        {
                            "rule_id": "555555",
                            "rule_name": "加分1"
                        },
                        {
                            "rule_id": "4444",
                            "rule_name": "没空"
                        },
                        {
                            "rule_id": "33333",
                            "rule_name": "噢"
                        },
                        {
                            "rule_id": "22222",
                            "rule_name": "沟通"
                        }
                    ]
                },
                {
                    "key": "quality.entity",
                    "value": [
                        {
                            "complex_id": "1111",
                            "complex_name": "关：爸爸&妈妈=合规",
                            "qualified": true
                        },
                        {
                            "complex_id": "222222222222",
                            "complex_name": "关：妈妈&没空=违规",
                            "qualified": false
                        }
                    ]
                },
                {
                    "key": "quality_group.id",
                    "value": "e7c50893"
                }
            ]
        ],
        "total": 6
    },
    "message": "success"
}

**期待的正确结果**

正确情况下应该是什么样的？
正确解析
**截图**
![image](https://user-images.githubusercontent.com/11645593/133765035-427793f8-2e1c-4ea2-aa72-15b1c4296ebb.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
