### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#63]
**请描述您的需求或者改进建议.**
1.接口测试可以转成性能测试，进行对接口压测
2.压测支持脚本变量，支持在线编辑
3.压测显示被压测机的CPU、内存、IO等参数
4.支持显示自定义目标机的消耗等参数
5.robotfromwork接口兼容，支持导入robotfromwork用例

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 1.接口测试可以转成性能测试，进行对接口压测
> 2.压测支持脚本变量，支持在线编辑
> 3.压测显示被压测机的CPU、内存、IO等参数
> 4.支持显示自定义目标机的消耗等参数
> 5.robotfromwork接口兼容，支持导入robotfromwork用例
> 
> **请描述你建议的实现方案**

1已支持
2已支持脚本变量，在线编辑也在规划中
3、4 、5 都在调研

**Comment by wangzhen-fit2cloud** [comment]
@plateauandsp 感谢提出的这些建议，建议您这边后续提 issue 的时候多个需求可以分成多个 issue，这样可以方便大家进行跟踪。
