### ISSUE TITLE
[BUG]自定义消息通知模板提供的参数，部分用不了，获取不到值

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6325]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

v1.12.3

**Bug 描述**

消息通知自定义模板使用部分变量参数，实际上未获取到正确的值

**Bug 重现步骤**

1、配置邮件通知自定义模板，使用默认模板提供的参数
2、触发消息通知
3、邮件中部分内容为${xxx}，为获取到值

**期待的正确结果**

能正确获取变量值

**截图**

![image](https://user-images.githubusercontent.com/88763608/134270188-e694178a-a7fd-41a4-9ef5-61ae2f5efe4c.png)
![image](https://user-images.githubusercontent.com/88763608/134270231-c543921d-acc5-4de7-9a75-74c5c059aeb9.png)
![image](https://user-images.githubusercontent.com/88763608/134270291-da390935-1e0b-4c91-9d12-d29124f85b64.png)
![image](https://user-images.githubusercontent.com/88763608/134270333-218a0f35-40ba-451c-8e74-701d6537ad17.png)
![image](https://user-images.githubusercontent.com/88763608/134270364-68a45e10-072e-487c-ad96-1d6f2aee319a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
