### ISSUE TITLE
[BUG]快捷调试另存为用例不会更新用例状态

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6340]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.3
**Bug 描述**

简要描述您碰到的问题
使用快捷调试创建的用例执行后执行结果不会更新
**Bug 重现步骤**
1点击快捷调试

2输入内容调试成功

3另存为新用例

4输入用例名称，点击任意位置提示保存成功

5点击CASE执行用例，成功执行状态不更新

**期待的正确结果**

正确情况下应该是什么样的？
用例成功执行，执行结果为通过
**截图**

如果有截图，请附上截图.
![1632292130776](https://user-images.githubusercontent.com/36387811/134293773-a2fecce7-c6ab-4f04-a7ff-dc400a66fb35.jpg)

**Comment by xulinde** [comment]
感谢您的反馈，我们复现下

**Comment by zyyfit** [comment]
您好，最新版没有复现，您可以升级到1.13.0试试

**Comment by pb123abc** [comment]
升级到1.3 问题还在，1快捷调试接口2生成用例3执行用例。 用例执行完通过率是100%，但执行结果显示未执行。

**Comment by zyyfit** [comment]
> 升级到1.13 问题还在，1快捷调试接口2生成用例3执行用例。 用例执行完通过率是100%，但执行结果显示未执行。

哦哦，知道了，感谢反馈

**Comment by xulinde** [comment]
v1.13.1已修复
