### ISSUE TITLE
[BUG]文档与消息中心重叠

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6343]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.3
**Bug 描述**

简要描述您碰到的问题
在文档页面，点击消息中心，页面出现错误
**Bug 重现步骤**

1.  点击接口测试-接口定义-文档
2. 点击消息中心
![1632294088466](https://user-images.githubusercontent.com/36387811/134298031-c1cd900b-d692-4bdf-b026-e2642e87f7dd.jpg)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
感谢您的反馈，我们尽快优化下这里

**Comment by xulinde** [comment]
v1.13.1已修复
