### ISSUE TITLE
[BUG]场景里引用两个子场景，如果有两个子场景的变量名是一样的，值不同，那么这个变量就只会引用一个值

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6350]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.3-27e6d479
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建A场景，导入接口，创建场景变量 email,在接口参数中引用变量${email}=123
2. 创建B场景，导入接口，创建场景变量 email,在接口参数中引用变量${email}=456
3. 创建C场景，导入 A 和 B 场景，点击调试，A和B场景中的email 参数都是 456
4. 
![image](https://user-images.githubusercontent.com/30038088/134308072-efc54585-a056-4283-8ff5-fa2821497960.png)

![image](https://user-images.githubusercontent.com/30038088/134308021-520d930c-ffbd-43a3-b98c-b411f408e608.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，暂时不好处理，后期会处理这个问题的
https://github.com/metersphere/metersphere/issues/1620

**Comment by yangshiyu** [comment]
什么时候解决啊
