### ISSUE TITLE
[FEATURE]建议支持在测试计划中修改测试用例

### ISSUE THREAD

**Issue by heshiqi1** [metersphere/metersphere#6358]
**请描述您的需求或者改进建议.**
建议支持在测试计划中修改测试用例，每次在测试计划执行用例遇到用例问题时，都要再返回用例管理修改用例，比较麻烦

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
执行测试计划时，点击用例标题是会跳转到用例详情，可以编辑用例，您看是否能满足您的需求

**Comment by heshiqi1** [comment]
可以满足




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 下午5:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]建议支持在测试计划中修改测试用例 (#6358)





 
执行测试计划时，点击用例标题是会跳转到用例详情，可以编辑用例，您看是否能满足您的需求
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
