### ISSUE TITLE
[FEATURE]建议增加项目需求管理的功能，方便测试用例关联项目需求

### ISSUE THREAD

**Issue by heshiqi1** [metersphere/metersphere#6359]
**请描述您的需求或者改进建议.**
建议增加项目需求管理的功能，方便测试用例关联项目需求

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
v1.13会加此功能

**Comment by zyyfit** [comment]
您好，我们目前可以关联第三方平台的需求，您是想要metersphere中单独做一个需求管理模块吗

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
