### ISSUE TITLE
[BUG][接口测试]点击创建接口，显示的case列表

### ISSUE THREAD

**Issue by muchild** [metersphere/metersphere#6372]
metersphere版本：v1.12.1-6bcee557
问题描述：
【前提条件】已有api，且有对应case
【复现步骤】
1、api列表，点击case按钮
2、关闭新打开的case tab
3、悬浮+，点击创建接口
【预期结果】步骤3后，可打开创建接口tab
【实际结果】步骤3后，打开的case列表
【操作附件】![屏幕录制2021-09-22 下午11.39.18.gif](https://i.loli.net/2021/09/22/3qsFDeuhTmaJKyv.gif)

**Comment by zyyfit** [comment]
您好，最新版已经修复了这个问题，您可以升级到1.13.0
