### ISSUE TITLE
[BUG]首页-用例数量统计中的数据统计不正确

### ISSUE THREAD

**Issue by Ybump14** [metersphere/metersphere#6373]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.3-27e6d479

**Bug 描述**

用例数量统计中的数据统计不正确, 用例被删除后, 评审率/未评审/已通过等数据是包含了已删除的

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

**截图**

![image](https://user-images.githubusercontent.com/22122213/134442092-c0aa1fb1-4ec9-4a32-bc0f-a3e4b73d3d1d.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
