### ISSUE TITLE
[BUG]接口定义请求参数请求体切换类型时请求头的参数会无故变更

### ISSUE THREAD

**Issue by shenjiesheng** [metersphere/metersphere#6374]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.12.0-a8cbf128
**Bug 描述**

接口定义请求参数请求体切换类型时请求头的参数会无故变更

**Bug 重现步骤**

1.  接口定义编辑接口
2. 创建3个请求头参数
3. 请求体格式间切换
4. 

**期待的正确结果**
不会影响请求头的参数设置
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
请问请求头变更具体是怎样变的，如果是自动添加或者去掉了contetn-type是正常的，其他的变动我这边没有复现呢
