### ISSUE TITLE
[FEATURE]接口测试请求类型增加wireformat

### ISSUE THREAD

**Issue by 15708416734** [metersphere/metersphere#6384]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/37166279/134449267-63c887f6-bc9b-4bde-851f-b7098f5ebd1c.png)
除了json，xml等格式，能否支持wireformat呢
**请描述你建议的实现方案**
希望接口测试的请求类型增加wireformat

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by 15708416734** [comment]
> 感谢反馈，我们先进行下相关调查。

lz4也可以支持一下，比如大于多少某个值就可以用lz4压缩

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
