### ISSUE TITLE
[QUESTION] metersphere 测试的结果 和 命令行下测试的结果差距太多

### ISSUE THREAD

**Issue by lx308033262** [metersphere/metersphere#639]
**请描述您的问题.**

metersphere 测试的结果 和 命令行下测试的结果差距太多
机器配置
4核16G 
metersphere 和 jmter再同一台机器

jmeter测试结果如下
+ jmeter -n -t 测试-登陆.jmx -l result.jtl
Creating summariser <summary>
Created the tree successfully using 测试-登陆.jmx
Starting the test @ Thu Oct 29 09:56:58 CST 2020 (1603936618344)
Waiting for possible shutdown message on port 4445
summary +      1 in     1s =    1.0/s Avg:   989 Min:   989 Max:   989 Err:     0 (0.00%) Active: 157 Started: 157 Finished: 0
summary + 161892 in    32s = 5135.7/s Avg:    48 Min:     3 Max:  5325 Err:     0 (0.00%) Active: 300 Started: 300 Finished: 0
summary = 161893 in    32s = 5135.7/s Avg:    48 Min:     3 Max:  5325 Err:     0 (0.00%)
summary + 195750 in    31s = 6384.7/s Avg:    45 Min:     3 Max:  1211 Err:     0 (0.00%) Active: 300 Started: 300 Finished: 0
summary = 357643 in    62s = 5813.1/s Avg:    47 Min:     3 Max:  5325 Err:     0 (0.00%)
summary + 193892 in    31s = 6334.7/s Avg:    46 Min:     3 Max:  1389 Err:     0 (0.00%) Active: 300 Started: 300 Finished: 0
summary = 551535 in    92s = 6026.2/s Avg:    46 Min:     3 Max:  5325 Err:     0 (0.00%)

metersphere测试结果如下
300 VU
Max Users

1262.63 Hits/s
Avg.Throughput

2.70 %
Errors

0.0063 s
Avg.Response Time

0.0150 s
90% Response Time

1398.56 KiB/s
Avg.Bandwidth

**Comment by rzsp8552** [comment]
也遇到类似的问题，期望能快速解决

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue #384  重复
