### ISSUE TITLE
接口自动化场景转性能测试去掉自动增加的DebugSampler

### ISSUE THREAD

**Issue by 15708416734** [metersphere/metersphere#6391]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/37166279/134452114-0a32abb3-3b7e-4b48-af93-9f8d15c8a890.png)
压测结果的请求统计中怎么会多了一个RunningDebugSampler请求，这个会造成发压端压力增大吗，能否去掉呢

**Comment by rayshen3** [comment]
+1
可以看看jmeter的压测报告，也是有这个的

**Comment by 15708416734** [comment]
> +1 压测报告的文档几乎为0
> 可以看看jmeter的压测报告，也是有这个的

懂得都懂，不懂的我也不会解释，哈哈哈哈

**Comment by wangzhen-fit2cloud** [comment]
你好，自动添加的这个 DebugSampler 会在后续版本中去掉，请持续关注我们的更新日志。
