### ISSUE TITLE
[FEATURE] 希望可以添加一个 none 请求体

### ISSUE THREAD

**Issue by FlyingBreeze** [metersphere/metersphere#6394]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/32080333/134460655-d3ec72fe-b110-4048-8ae6-9fd9feb12a0f.png)

none 代表请求体为空，防止误操作点击其他请求体类型时无法更改为空的情况。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
