### ISSUE TITLE
请求上传csv文件，读取需要的字段下数据，如何实现？

### ISSUE THREAD

**Issue by miocoo** [metersphere/metersphere#640]
**请描述您的问题.**
请求上传csv文件，读取需要的字段下数据，如何实现？

**Comment by wangzhen-fit2cloud** [comment]
你好，目前在接口测试中暂不支持上传csv 文件；在性能测试上传的 jmx 文件中需要将引用 csv 文件的路径改为当前路径，例如 ./test.csv，将 csv 和 jmx 同时上传到性能测试中执行就可以正常引用到 csv 内的数据
