### ISSUE TITLE
[BUG]用例等级没有展示用户定义模板的值

### ISSUE THREAD

**Issue by keaizou** [metersphere/metersphere#6406]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
metersphere v1.10.0-b2

**Bug 描述**

简要描述您碰到的问题
测试跟踪-测试用例-新建用例；用例等级没有展示用户定义模板的值

**Bug 重现步骤**

1.  定义测试用例模版：用户等级默认值设为：P1，保存
2. 项目关联该用例模板
3. 在相关项目新建用例
4. 查看用例等级

**期待的正确结果**
与用例模板设置的用例等级一：p1

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
看起来是展示有问题，返回了P1，但仍然展示了P0
![image](https://user-images.githubusercontent.com/40739350/134474095-038540d7-3408-4fed-93d9-0edd553bf783.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.13.2以上版本已修复
