### ISSUE TITLE
[BUG] jenkins调用测试计划执行后，收到的邮件内容显示有变量名称

### ISSUE THREAD

**Issue by hu-shuli** [metersphere/metersphere#6424]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.0，从之前的1.11.3开始一直有这个问题，jenkins插件也同步升级
**Bug 描述**
jenkins调用测试计划执行后，收到的邮件内容显示有变量名称
简要描述您碰到的问题
jenkins调用测试计划执行后，收到的邮件内容显示有变量名称
**Bug 重现步骤**

1.  设置jenkins消息通知
2. jenkins调用测试计划执行
3. 测试计划执行完成后，查看邮件通知
4. 

**期待的正确结果**
邮件内容能显示完整的测试计划名称
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/66474661/134507813-579035d2-579a-4207-86ed-e38069d00b43.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
