### ISSUE TITLE
[FEATURE]老版本的接口自动化希望能加入一键切环境

### ISSUE THREAD

**Issue by songxt01** [metersphere/metersphere#6425]
**请描述您的需求或者改进建议.**
数据都在老版本上，新版本团队不愿意用，老版本场景自动化过多时，切环境很麻烦，要每个场景切一边

**请描述你建议的实现方案**
现需要针对老版本的自动化加入一键切全部场景的环境功能，比较着急 谢谢了 如果觉得麻烦 可以只针对1.5.1版本做下适配，太感谢了

**Comment by wangzhen-fit2cloud** [comment]
你好，很抱歉旧版本的接口测试我们没有计划进行修改了，还是希望你们能够切换到新版本进行使用。
