### ISSUE TITLE
[BUG]测试计划存在没有执行的案例

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#6432]
**MeterSphere 版本**
>v1.13.0

您所使用的 MeterSphere 版本是？
v1.13.0

**Bug 描述**

测试计划存在没有执行的案例

**Bug 重现步骤**

1.我在测试计划中有12条案例
2.执行测试计划的时候，如果卡住，主要原因是因为程序制运行了其中几条
3.然后判断是否执行成功的进程回查的时候只发现了运行了那几个案例状态是成功的，其余一直状态一直是runinng
4.过了差不多5分钟以后，没有运行的就全部是faild的状态了，并且日志中，没有任何case执行的情况
5.但是，测试报告的页面又全部都是正常的状态

**期待的正确结果**

没有执行的测试案例可以正常执行或者重复执行，而不是卡住，最后给出一个运行正常的状态
**截图**

![image](https://user-images.githubusercontent.com/31123121/134610253-171c491b-c55d-4865-81d5-f1542cce8ade.png)
![image](https://user-images.githubusercontent.com/31123121/134610265-98e48c58-b151-4117-9330-91922c732883.png)
![image](https://user-images.githubusercontent.com/31123121/134610279-c876f2c5-0b9d-47b8-9f14-0726b7ccedb4.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题呢，是必现的吗？是的话能否提供一下详细步骤？

**Comment by Svlang** [comment]
> 您好，没有复现这个问题呢，是必现的吗？是的话能否提供一下详细步骤？

这个就是很详细的步骤了，就是执行测试计划，如果需要的话，我给可以提供对应的日志，你们需要什么日志呢？我发邮箱给你们，谢谢

**Comment by Svlang** [comment]
谢谢修复
