### ISSUE TITLE
[BUG] 执行接口测试报错空指针

### ISSUE THREAD

**Issue by idonoty** [metersphere/metersphere#6438]
**MeterSphere 版本**
>v1.12.1到V1.13都有这个问题

**Bug 描述**
执行接口测试报错，空指针
![image](https://user-images.githubusercontent.com/39904206/134613511-2d79a657-3be2-46b6-9a6b-888807a04d87.png)
[error.txt](https://github.com/metersphere/metersphere/files/7222061/error.txt)

执行case也是一样，请尽快处理
![image](https://user-images.githubusercontent.com/39904206/134613624-0d37fa03-4f74-4586-96cd-b30c6f4095ab.png)

**Comment by idonoty** [comment]
报错的日志已经提在单子里面了，请自行下载查看

**Comment by xulinde** [comment]
v1.13.1已修复
