### ISSUE TITLE
[BUG]接口列表选择所有数据翻页后多选消失

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6449]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.3
**Bug 描述**

简要描述您碰到的问题
删除接口全选，想保留部分接口，翻页找到，点选取消，但是翻页后全选消失
**Bug 重现步骤**

1.  全选所有数据
2. 任意翻页操作

**期待的正确结果**

正确情况下应该是什么样的？
翻页后数据依旧全选
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先内部讨论一下这个问题

**Comment by zyyfit** [comment]
您好，考虑到 翻页后保留勾选的数据，在数据较多的情况下，可能会出现勾选后记不清勾选了哪些数据 或者 误勾选 的情况，这种时候进行批量操作，会有一定的风险，所以我们先不进行这个功能的修改

**Comment by pb123abc** [comment]
当有1000条接口，只有20条很重要，其他的都要删除的时候，20条遍布，全选之后必须翻页查找取消勾选

**Comment by zyyfit** [comment]
这里如果加上这个功能的话，假设这样一个场景，需要删除少部分的接口，这几个接口分布不在同一页，然后您在第一页勾选了几个，第二页勾选了几个，第三个勾选了几个，这样的话，您只能看到当前页面勾选的是哪几个，如果之前几页的勾选有不小心选错了的，在最后一页是看不到的，执行删除会直接把勾选的都删掉。而如果需要返回检查是否勾选正确的话，还不如单页删除当前页的操作方便。

您可以考虑一下，如果依然觉得这个风险性 小于 翻页不取消勾选的方便性，可以给我们回复，然后让我们产品经理进行一下需求调研

**Comment by pb123abc** [comment]
如果有不小心删错的不是还有回收站吗
