### ISSUE TITLE
[FEATURE]xmind测试用例导入存在相同用例时失败，不能更新操作

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#645]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
在1.7 版本修复这个问题
