### ISSUE TITLE
[BUG]场景的步骤展开后，无法“一键收起”

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6454]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
1.12.3
您所使用的 MeterSphere 版本是？

**Bug 描述**

场景的步骤展开后，无法“一键收起”
![image](https://user-images.githubusercontent.com/87106917/134627598-bef01847-fa90-4d4b-8d58-45192d605e35.png)
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
大概多少个步骤，无法收起是否有报错信息

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by liuhansong** [comment]
就是一键展开 然后点击一键收起 实际上步骤没有收起。发自我的华为手机

**Comment by xulinde** [comment]
v1.13.1已修复
