### ISSUE TITLE
[FEATURE]希望模块有快速展开的功能。

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6455]
**请描述您的需求或者改进建议.**

在模块层级较多时，需要一级一级展开，效率不高。
希望模块有快速展开的功能
![image](https://user-images.githubusercontent.com/20573589/134628219-aee0bd2c-3f55-41a5-b95c-fb9428253f79.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，后续可以优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
