### ISSUE TITLE
[BUG]升级1.13版本后，浏览器插件录制的接口脚本（json格式），导入平台会提示500报错

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#6459]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![9ff736eb3f74c40af0d57e7bf6fda36](https://user-images.githubusercontent.com/18163887/134631643-d347f5a0-3539-4dc0-8119-a0d6c3757d46.png)
![0311676832a4cfcd4f970c0fefade20](https://user-images.githubusercontent.com/18163887/134631666-b06a11b0-5a10-42a6-b9ca-f5aa84e950fe.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
