### ISSUE TITLE
[QUESTION]msctl是干啥的

### ISSUE THREAD

**Issue by xin7c** [metersphere/metersphere#646]
**请描述您的问题.**

**### msctl是干啥的，为啥出现在全局命令里呢，请教一下~~~**

**Comment by wangzhen-fit2cloud** [comment]
包装了一下我们各个服务组件的控制命令，可以通告该命令来启动、停止、升级我们的服务

**Comment by xin7c** [comment]
> 包装了一下我们各个服务组件的控制命令，可以通告该命令来启动、停止、升级我们的服务

这个是如何实现的呢，安装过程体现在哪个脚本或者配置文件里呢？

**Comment by wangzhen-fit2cloud** [comment]
建议看下我们的 install.sh 脚本，及 msctl 脚本内容
