### ISSUE TITLE
版本升级到最新版本时，导入之前版本导出的接口失败

### ISSUE THREAD

**Issue by nullapi** [metersphere/metersphere#6462]
**MeterSphere 版本**
>v1.13.0

**Bug 描述**

版本升级到最新版本时，导入之前版本导出的接口失败
**Bug 重现步骤**
1、导出v1.12.0版本的接口定义数据
2、导入到v1.13.0版本会提示解析失败

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把导入报错的数据给我们发送一份吗？

**Comment by nullapi** [comment]
当导出接口数据很多时会出现，我导入的是90个接口就报错了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 版本升级到最新版本时，导入之前版本导出的接口失败 (#6462)





 
您好，没有复现这个问题，方便把导入报错的数据给我们发送一份吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 当导出接口数据很多时会出现，我导入的是90个接口就报错了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年9月24日(星期五) 下午5:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 版本升级到最新版本时，导入之前版本导出的接口失败 (#6462) 您好，没有复现这个问题，方便把导入报错的数据给我们发送一份吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我导入了124个接口，但是没有报错，可能是有特定的数据会报错吧，您方便排查一下的话可以把报错的接口发给我们
![image](https://user-images.githubusercontent.com/73461316/134651604-1d73d24e-4ab3-415d-a8a3-ee4ec7f72748.png)

**Comment by nullapi** [comment]
导入这个就会报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 版本升级到最新版本时，导入之前版本导出的接口失败 (#6462)





  
当导出接口数据很多时会出现，我导入的是90个接口就报错了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" @.&gt;; 发送时间:&nbsp;2021年9月24日(星期五) 下午5:09 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 版本升级到最新版本时，导入之前版本导出的接口失败 (#6462) 您好，没有复现这个问题，方便把导入报错的数据给我们发送一份吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
我导入了124个接口，但是没有报错，可能是有特定的数据会报错吧，您方便排查一下的话可以把报错的接口发给我们
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xulinde** [comment]
v1.13.1已修复
