### ISSUE TITLE
[BUG]升级1.13后很多功能不能正常使用

### ISSUE THREAD

**Issue by rayshen3** [metersphere/metersphere#6465]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.13
**Bug 描述**
自动化接口场景创建，无法debug，也无法保存
![image](https://user-images.githubusercontent.com/9734936/134637453-19ce1e35-9c38-4ffb-be24-0c0e0ec31225.png)

![image](https://user-images.githubusercontent.com/9734936/134637811-28d8abe7-23a6-4adc-9752-d55f29bdfc54.png)

从已有的场景创建性能压测，创建后，无压力配置
![image](https://user-images.githubusercontent.com/9734936/134636736-eb27378f-5a1b-40d9-a631-7a76b15e7f57.png)
手动"引入接口自动化场景"，点击没反应
![image](https://user-images.githubusercontent.com/9734936/134636918-035a5509-e8c9-4c4f-9157-90cfa42691ab.png)

**Comment by zyyfit** [comment]
您好，第一个问题没有复现，请问有什么特殊的操作步骤吗？
后面的问题会在小版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
