### ISSUE TITLE
[FEATURE]希望平台能跟禅道打通

### ISSUE THREAD

**Issue by Sylvie1222** [metersphere/metersphere#647]
**请描述您的需求或者改进建议.**
希望平台能跟禅道打通。
禅道偏向于项目跟踪系统，给需求，开发，测试使用。同时MS更偏向测试执行，因此希望测试的全流程：测试计划，测试任务分派，测试用例执行，提Bug，希望能打通

**请描述你建议的实现方案**
1.MS的工作空间和项目2个菜单类型，同步禅道的项目。目前我们使用的原理是：组织----部门，工作空间---系统，项目---系统，测试---系统模块
2.MS的测试用例和禅道用例同步。无论在禅道还是MS平台，单个建用例OR批量导入用例，都能互通
3.MS的测试计划和禅道测试单同步。MS的测试计划关联了测试用例后，也会同步到禅道测试单中
4.MS的测试计划里的提缺陷功能，与禅道的BUG同步。也希望MS的提缺陷功能可以抽出来，放到测试跟踪下作为二级菜单。
目前MS的提缺陷页面，希望能增加：模块（必填）、迭代、版本、指派给（必填）、bug类型，字段类型都可为下拉框选项。
也希望MS能支持批量提BUG，包含模块（必填），迭代，版本，Bug标题（必填），重现步骤（富文本框支持复制粘贴图片，必填），指派给（单选OR权限OR多选，必填），BUG类型。
PS：以上几点，需支持互通，即从禅道增删改，MS也同步更新，反之亦然。

5.MS的接口测试和性能测试，能否作为任务关联到禅道的【任务】呢？通过禅道量化和下发测试工作，测试人员可在MS执行操作

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈， 平台已集成禅道，可以直接提缺陷到禅道，其他需求后续考虑优化，请持续关注～
