### ISSUE TITLE
[BUG]功能用例中，如果该模块下一级中包含测试用例，则这个模块的移动会报错

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6474]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  功能用例中，如果该模块下一级中包含测试用例，则这个模块的移动会报错
2. 
![image](https://user-images.githubusercontent.com/20573589/134652082-0ce9c5f7-6f91-4ff7-b5ca-5ca50fa5b6c0.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
和issue#6426同类问题，已修复，下个版本发布您再试试
