### ISSUE TITLE
[BUG]功能用例的模块下一级有包含测试用例，则移动该模块会报错。

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6477]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.0
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  如果移动的模块下一子级包含测试用例，则移动该模块会报错
2. 
![image](https://user-images.githubusercontent.com/20573589/134656491-d6c9235b-441d-4571-8a39-1e44dbed3e67.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
和issue#6426问题重复
