### ISSUE TITLE
[BUG] 使用helm 方式布置k8s之后在创建压力测试时无法启动jmeter，提示无法找到镜像，但是实际宿主机是拉取了镜像的

### ISSUE THREAD

**Issue by ahua-chen** [metersphere/metersphere#6478]
您所使用的 MeterSphere 版本是？
1.13
Bug 描述
使用helm 方式布置k8s之后在创建压力测试时无法启动jmeter，提示无法找到镜像，但是实际宿主机是拉取了镜像的，而且使用k8s方式怎么能让node-controller 再拉起一个docker镜像？

**Comment by linl12138** [comment]
测试资源池添加正确吗

**Comment by 15708416734** [comment]
> 测试资源池添加正确吗

资源池可以正确添加，在执行压测的时候提示找不到镜像

**Comment by ahua-chen** [comment]
> > 测试资源池添加正确吗
> 
> 资源池可以正确添加，在执行压测的时候提示找不到镜像

和这位大佬说的完全一致

**Comment by wangzhen-fit2cloud** [comment]
你好，请简单描述下环境是如何部署的，以及 node-controller 节点是如何部署及添加的。
