### ISSUE TITLE
[BUG]测试跟踪-测试计划-测试报告的缺陷列表没有数据

### ISSUE THREAD

**Issue by zhanggefei** [metersphere/metersphere#6488]
**MeterSphere 版本**
>v1.13
<img width="1196" alt="WechatIMG3" src="https://user-images.githubusercontent.com/37612532/134696898-8dd3f215-67d2-4a05-b56e-b39a798ae316.png">
<img width="1435" alt="WechatIMG4" src="https://user-images.githubusercontent.com/37612532/134696923-a4337742-df5a-4305-8fbc-b49223e4eaa2.png">

**Comment by youliyuan-fit2cloud** [comment]
你这两个“缺陷来源”是在缺陷管理模块添加的，测试计划里面只是关联 这个缺陷的话不会统计到报告，测试计划里面新建的缺陷才会统计到报告

**Comment by zhanggefei** [comment]
get
