### ISSUE TITLE
[FEATURE]功能测试用例，脑图可否支持当前保存顺序排序

### ISSUE THREAD

**Issue by adadale** [metersphere/metersphere#6489]
**请描述您的需求或者改进建议.**
功能测试用例，脑图可否支持当前保存顺序排序
1.我在脑图中第三条和第四条之间插入了一条用例
2.点击保存
3.重新加载脑图发现是以createtime desc排序的

**请描述你建议的实现方案**
1.能否支持按照保存时用例的排列顺序排序

**Comment by wangzhen-fit2cloud** [comment]
你好，在最新版本中已进行优化，可以升级一下。
