### ISSUE TITLE
[FEATURE]关于性能测试报告的需求建议

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#6490]
**请描述您的需求或者改进建议.**
1、目前的性能测试报告，在线预览和导出 都是针对单个场景的，确认项目级的包含所有的测试场景展示（可勾选场景自定义生成项目级场景性能测试报告较好）

**Comment by luty2018** [comment]
可以加入到测试计划，在测试计划执行后生成整体的测试报告。
