### ISSUE TITLE
[FEATURE]希望可以对接本地部署的rap2来导入接口

### ISSUE THREAD

**Issue by Dz-fanzhi** [metersphere/metersphere#650]
**请描述您的需求或者改进建议.**

希望可以对接本地部署的rap2来导入接口来减少测试人员对接口录入的工作，并且避免因录入错误产生的bug。

**请描述你建议的实现方案**
1.提供一键导入rap2接口功能。
2.提供一个插件 填入rap2的访问链接以及登录信息。以后可以一键同步。保证开发接口改动之后测试可以实时同步。

**Comment by wangzhen-fit2cloud** [comment]
你好，目前我们正在规划开发接口管理功能，计划 swagger 及 rap2 等导入跟同步功能放在接口管理功能模块中提供，请持续关注。
