### ISSUE TITLE
[BUG]升级到v1.13.0-b3版本后，接口定义页面出现多个接口出现500报错。

### ISSUE THREAD

**Issue by ZHIGAOwang** [metersphere/metersphere#6505]
**MeterSphere 版本**
v1.13.0-b3

**Bug 描述**

升级到v1.13.0-b3版本后，接口定义页面出现多个接口出现500报错。

/project/get/53583aa6-6101-4846-9dc8-4a2dbb82c30b
/api/definition/list/1/10

**Bug 重现步骤**

1. 升级版本
2. 接口定义页面随便点击一个模块都有报错。
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33215154/134793049-9a41d48b-9e38-4d1c-937e-0858cd2f52a4.png)
![image](https://user-images.githubusercontent.com/33215154/134793058-30f78450-bbbd-43c0-9579-35d0e1c87fb0.png)
![image](https://user-images.githubusercontent.com/33215154/134793107-4946316e-40cc-44b6-9314-c4552ca7e2e7.png)

**Comment by rayshen3** [comment]
微信群里问过了，说下个小版本修复，哎

**Comment by ZHIGAOwang** [comment]
升级版本就好了。
