### ISSUE TITLE
[BUG]修改用例名称不能成功显示

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6506]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13
**Bug 描述**

简要描述您碰到的问题
修改用例名称在列表不能立即显示修改后的名称
**Bug 重现步骤**

1.  在接口列表点击指定接口列的CASE弹出新窗口
2. 在新窗口中点击编辑用例
3. 修改用例名称
4. 点击保存

**期待的正确结果**

正确情况下应该是什么样的？
显示保存成功，在新弹出的窗口下用例的名称显示修改后的
**截图**

如果有截图，请附上截图.
![1632636097166](https://user-images.githubusercontent.com/36387811/134795861-6f3ef058-ef78-4b1a-8f6d-e03bf5b12435.jpg)
![1632636466489](https://user-images.githubusercontent.com/36387811/134795869-fa053708-3edf-4918-910b-b7a481aa51cd.jpg)
![1632636019831](https://user-images.githubusercontent.com/36387811/134795876-6bba6e21-1041-4741-b4cc-c8fcba74de49.jpg)

**Comment by pb123abc** [comment]
closed是因为今天偶然出现更改后会立即保存显示更该后的名称，经过反复验证后发现还是存在这个问题

**Comment by pb123abc** [comment]
在用例页面修改名称，保存后，页面不自动刷新，导致数据还是修改前的，在保存之后自动刷新数据就可以了

**Comment by zyyfit** [comment]
您可以升级到最新版看看，最新版编辑用例名称后case列表也会更新了
