### ISSUE TITLE
[FEATURE]配置全局变量、场景变量或提参之后，用户在引用变量时可以像内置参数一样，通过下拉框的方式进行选择

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6512]
**请描述您的需求或者改进建议.**

配置全局变量、场景变量或提参之后，用户在引用变量时可以像内置参数一样，通过下拉框的方式进行选择。实现如下效果；
![image](https://user-images.githubusercontent.com/34565342/134798354-fb19d584-4e0e-4adb-ab44-17302f3f50ed.png)

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
考虑到下拉框数据较多是体验不好。
这里已经支持提取出有提取参数的步骤， 用户可以选择相应的提取参数使用。
