### ISSUE TITLE
[FEATURE]接口自动化，在查看或编辑场景步骤过程中，展开操作繁琐建议优化

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6513]
**请描述您的需求或者改进建议.**
接口自动化，在查看或编辑场景步骤过程中，展开操作繁琐建议优化。
在查看或编辑场景的过程中，点击“一键展开”或着单个场景步骤展开时，不会自动展开“响应内容”，需要再次点击“响应内容”，才能查看接口调用响应详情。如图所示：
![image](https://user-images.githubusercontent.com/34565342/134798722-04eb66d3-46d7-4933-84f0-90964ce5598c.png)

**请描述你建议的实现方案**
建议提供按键实现真正的详情展开。或者，在点开单个场景步骤时，默认打开响应内容

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
