### ISSUE TITLE
[BUG]测试计划邮件模板中执行人、执行环境、执行时间相关字段获取不到

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#6516]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.13
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/85992665/134798938-9dfe3cee-7f5b-4ae5-8202-bb36c6da6e77.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复

https://github.com/metersphere/metersphere/issues/6325
