### ISSUE TITLE
[BUG]接口测试中，批量添加请求体时，给出示例格式描述不正确

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6518]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

v1.13.0

**Bug 描述**

接口测试中，批量添加请求体时，给出示例格式描述不正确
批量添加请求体的格式应该为逗号分隔开，而不是“参数名：参数值”的格式
![image](https://user-images.githubusercontent.com/34565342/134799450-2508d1a5-b1c8-4129-9b28-a54c284675e5.png)

**Bug 重现步骤**

1.  进入“接口自动化”
2. 点击某一场景步骤
3. 选择“请求参数>请求体>批量添加”
4. 可以看到给出的示例格式不正确

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
