### ISSUE TITLE
[FEATURE]在同一个meter sphere不同工作空间，不能存在同一个场景

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6529]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.3
**Bug 描述**

简要描述您碰到的问题
在不同工作空间，不能存在同一个场景
**Bug 重现步骤**

1.  在一个工作空间导出场景
2. 在另一个工作空间导入场景

**期待的正确结果**

正确情况下应该是什么样的？
在另一个工作空间能正常导入
**截图**
Method[sqlExceptionHandler][Duplicate entry 'cb45e209-7cba-45ed-afee-10330d083e8f' for key 'PRIMARY']
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
