### ISSUE TITLE
[BUG]接口自动化场景中，导入接口case，翻页后之前勾选的API会自动去勾，但实际导入时又能正常导入

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6533]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

v1.13.0

**Bug 描述**

接口自动化场景中，导入接口case，翻页后之前勾选的API会自动去勾，但实际导入时又能正常导入

**Bug 重现步骤**

1.  进入“接口测试>接口自动化”，选择某一场景，选择“接口列表导入”；
2. 切换case，勾选某一case；
3. 翻页，翻到到下一页再回到当前页
4. 之前勾选的case已去勾
5. 点击复制或引用，实际上时能够正常导入的

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/34565342/134801903-8a970f37-d992-41b8-afbd-257e681090cf.png)
![image](https://user-images.githubusercontent.com/34565342/134801976-7814838f-e3d3-4746-b8c9-4ab1923af05a.png)

**Comment by zyyfit** [comment]
您好，请问是必现的吗？这边没有复现呢，也可以清缓存再试试

**Comment by zyyfit** [comment]
最新版已修复
