### ISSUE TITLE
[FEATURE]case复制能跨模块，点击复制时能够相当于新建一个case，同时在case上支持配置模块和api

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6535]
**请描述您的需求或者改进建议.**

case复制能跨模块，点击复制时能够相当于新建一个case，同时在case上支持配置模块和api

**请描述你建议的实现方案**

提升易用性

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
