### ISSUE TITLE
[BUG]条件控制器添加接口步骤，从接口列表中复制的case可以拖动到条件控制器下，引用的case不可以

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#6537]
**MeterSphere 版本**

>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

v1.13.0

**Bug 描述**

简要描述您碰到的问题

条件控制器添加接口步骤，从接口列表中复制的case可以拖动到条件控制器下，引用的case不可以
**Bug 重现步骤**

1.  在接口自动化场景下，添加条件控制器
2. 将复制的步骤拖动到条件控制器下成功
3. 将引用的步骤拖动到条件控制器下不成功
4. 先拖动复制的步骤拖动到条件控制器下，再将引用的步骤拖动到条件控制器下又可以成功

**期待的正确结果**

正确情况下应该是什么样的？
无论复制还是引用的步骤应该都能正常拖动到条件控制器下

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/34565342/134803447-12ffaffa-b197-4825-87f3-bcca9d637300.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.14.0已修复
