### ISSUE TITLE
[BUG] 脑图中，删除多个分支，实际只删除了一个。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#6549]
版本：1.13.0

步骤：
脑图中，删除多个分支，实际只删除了一个。

动图：
![30d873cc-d05c-47e1-9a0d-a2117f05f264](https://user-images.githubusercontent.com/44999044/134836669-5c3c3a23-1c43-480c-a132-6d13caf6a52d.gif)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
