### ISSUE TITLE
[QUESTION] 如果将登陆token设置为环境变量

### ISSUE THREAD

**Issue by modelsex** [metersphere/metersphere#655]
如题，在一些case中需要测试登陆条件下的接口，如果将登陆后获取的token设置为环境变量？

**Comment by wangzhen-fit2cloud** [comment]
你好，可以通过提取功能将登录接口返回的 token 提取为变量在后续接口中使用，具体可参考下该教程
https://metersphere.io/docs/tutorial/api_testing/
