### ISSUE TITLE
[BUG]场景测试不能自动创建JMX文件

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6552]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13
**Bug 描述**

简要描述您碰到的问题
场景用例创建性能测试不能自动生成JMX文件
**Bug 重现步骤**

1.  在接口自动化的场景列表页面
2. 点击“...”
3. 点击创建性能测试

**期待的正确结果**

正确情况下应该是什么样的？
自动生成场景的JMX文件
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，1.13.1修复

**Comment by xulinde** [comment]
v1.13.1已修复
