### ISSUE TITLE
[BUG]性能测试引用自动化场景失败

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6554]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v.1.13
**Bug 描述**

简要描述您碰到的问题
性能测试引用自动化场景，点击确定无响应
<img width="1060" alt="截屏2021-09-27 10 59 39" src="https://user-images.githubusercontent.com/36387811/134839914-c9347b7f-7ab7-46c7-93b5-8cfe2c85bbb7.png">

**Bug 重现步骤**

1.  在创建性能测试界面
2. 点击引用接口自动化场景
3. 选择场景
4. 点击确定

**期待的正确结果**

正确情况下应该是什么样的？
生成JMX文件
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，1.13.1修复

**Comment by xulinde** [comment]
v1.13.1已修复
