### ISSUE TITLE
[BUG]  测试计划执行定时任务邮件模板变量取值错误

### ISSUE THREAD

**Issue by TaoJiandong** [metersphere/metersphere#6557]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.3
**Bug 描述**
测试计划执行定时任务邮件模板错误
简要描述您碰到的问题

**Bug 重现步骤**

TestPlanFailedNotification.html
TestPlanSuccessNotification.html
两个文件的下列文案中变量没能取到
您所执行的 ${testName} 测试计划运行成功/失败
**期待的正确结果**

正确情况下应该是什么样的？
这里的变量应该用${testPlanName}或者${name}才对

如果有截图，请附上截图.
![1632716877(1)](https://user-images.githubusercontent.com/86087324/134845446-ae94a991-64f5-4b16-9363-9e01622ea73e.png)

**Comment by zyyfit** [comment]
已知问题，1.13.1版本修复

**Comment by xulinde** [comment]
v1.13.1已修复
