### ISSUE TITLE
安装部署完成后，ms-server 状态为unhealthy，其他服务状态异常

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#6558]
ms-server            /deployments/run-java.sh         Up (unhealthy)   0.0.0.0:8089->8089/tcp
部署完成后 ms-server   unhealthy，应该怎么排查问题？
查看logs日志，也没有特别的错误信息（本次部署就修改了默认端口8081为8089）
ms-server             | ================= 应用启动 =================
ms-server             | sys.path: /opt/jmeter
ms-server             | 2021-09-27 12:25:08,947  INFO ion.mgt.AbstractValidatingSessionManager: 233 - Enabling session validation scheduler...
ms-server             | 2021-09-27 12:25:45,423  INFO cheduling.quartz.LocalDataSourceJobStore:3644 - ClusterManager: detected 1 failed or restarted instances.
ms-server             | 2021-09-27 12:25:45,423  INFO cheduling.quartz.LocalDataSourceJobStore:3503 - ClusterManager: Scanning for instance "f50e3beeb2381632714750797"'s failed in-progress jobs.
ms-server             | 2021-09-27 12:25:45,424  INFO k.scheduling.quartz.SchedulerFactoryBean: 748 - Starting Quartz Scheduler now, after delay of 60 seconds
ms-server             | 2021-09-27 12:25:45,424  INFO          org.quartz.core.QuartzScheduler: 547 - Scheduler clusterScheduler_$_f50e3beeb2381632716650850 started.
ms-server             | 2021-09-27 12:25:45,428  INFO          org.quartz.core.QuartzScheduler: 547 - Scheduler clusterScheduler_$_f50e3beeb2381632716650850 started.
ms-server             | 2021-09-27 12:25:45,555  INFO          org.quartz.core.QuartzScheduler: 547 - Scheduler clusterScheduler_$_f50e3beeb2381632716650850 started.
ms-server             | 初始化任务：{"createTime":1632711593000,"enable":true,"group":"ISSUE_SYNC","id":"7a23d4db-9909-438d-9e36-58e432c8c4ae","job":"io.metersphere.job.sechedule.IssueSyncJob","key":"ISSUE_SYNC","name":"ISSUE_SYNC","projectId":"system","resourceId":"system","type":"CRON","updateTime":1632711593000,"userId":"admin","value":"0 0 3 * * ?","workspaceId":"system"}
ms-server             | AddOrUpdateCronJob: ISSUE_SYNC,ISSUE_SYNC
ms-server             | addCronJob: ISSUE_SYNC,ISSUE_SYNC

**Comment by xulinde** [comment]
新版本还有此问题吗
