### ISSUE TITLE
[BUG]http请求，get中带有body的请求执行后，后台服务收到的请求里没有请求体。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6559]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

http请求，get中带有body的请求执行后，后台服务收到的请求里没有请求体。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
请问是您工作的真实环境中get接口需要带body吗？

**Comment by zyyfit** [comment]
1.13.2已修复
