### ISSUE TITLE
[BUG]while循环条件没生效

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6566]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13
**Bug 描述**

简要描述您碰到的问题
在接口自动化中使用while条件不能按照条件判断，该退出循环却不断循环直至时间结束
**Bug 重现步骤**

1.  在场景变量中设置CSV变量
2. while条件设置为name值不等于CSV中第三个值
 

**期待的正确结果**

正确情况下应该是什么样的？
在第三个值处停止循环
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现您这个问题，方便把您的场景和csv文件导出ms格式给我们看一下吗

**Comment by pb123abc** [comment]
CSV有三个值，条件是不等于CSV第二个值，循环一为true，到循环二为false，应该不执行循环二，可是循环二执行了第二个取值

**Comment by zyyfit** [comment]
> CSV有三个值，条件是不等于CSV第二个值，循环一为true，到循环二为false，应该不执行循环二，可是循环二执行了第二个取值

哦哦，1.13.1修复了这个问题，您可以等13.1发布后进行升级
