### ISSUE TITLE
[BUG]接口定义中，先点文档再点击API就会大概率报错：Cannot read property 'scrollTop' of undefined

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6569]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

接口定义中，先点文档再点击API就会大概率报错：Cannot read property 'scrollTop' of undefined

**Bug 重现步骤**

1. 进入接口定义 
2. 先点文档再点击API
3. 
![image](https://user-images.githubusercontent.com/87106917/134865509-b3e0cbf5-0ae8-4ae6-861f-d03493fbf59d.png)
![image](https://user-images.githubusercontent.com/87106917/134865536-ca3ad463-a7ca-443e-b3d7-ffcefda2c7b8.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.13.0已修复
