### ISSUE TITLE
[BUG]有引用关系的自动化场景，导入导出后引用关系就没了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6570]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.8-lts

**Bug 描述**

在同一个工作空间下，某个场景有引用其他项目的场景，改场景导出后再导入其他项目，引用关系就消失了

**Bug 重现步骤**

1.  在同一个工作空间下，有ABCD四个项目，每一个项目都有一个自动化场景，其中，B项目的场景引用了C项目和D项目的场景
2. 将B项目的自动化场景导出为metersphere格式
3. 将导出的metersphere格式数据，导入到A项目
4. 导入后该场景中不再具有引用C、D项目的关系

**期待的正确结果**

导入导出后要继续保持引用关系
![image](https://user-images.githubusercontent.com/88763608/134865876-af8aa8a5-8422-47f4-8f83-245966019a3b.png)

![image](https://user-images.githubusercontent.com/88763608/134865613-803b2e33-3a53-478e-8807-4b138186ada1.png)
![image](https://user-images.githubusercontent.com/88763608/134865749-dea0d073-e379-4f7a-b73e-c6230456b2a1.png)

**Comment by zyyfit** [comment]
您好，是这样设计的，导入的脚本是不带引用关系的
