### ISSUE TITLE
[BUG]运行状态显示错误

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6574]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v.1.13
**Bug 描述**

简要描述您碰到的问题
测试通过，应该显示success却显示error
**Bug 重现步骤**

1.  while循环多次
<img width="941" alt="截屏2021-09-27 17 49 01" src="https://user-images.githubusercontent.com/36387811/134886652-25a5c1fc-656f-4fe2-9d11-d2f3afcf6fb4.png">

**期待的正确结果**

正确情况下应该是什么样的？
显示success
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问是每次循环都成功了吗？有一次循环不成功就会判定为失败的
