### ISSUE TITLE
[FEATURE]测试用例和评审两个地方的小优化。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6575]
**请描述您的需求或者改进建议.**
1、测试用例附件，希望能支持上传zip文件、视频文件--有时候问题不好描述，都是录屏
2、MS分配的测试用例自定义ID，没有显示在评审用例的详情里

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/78218624/134886316-d8fd0351-f34a-4cd4-96dc-c8d5710355b4.png)
![image](https://user-images.githubusercontent.com/78218624/134886797-7dc2a4c6-4822-4eb8-8bce-21ab39a50703.png)

**Comment by xulinde** [comment]
感谢您的建议，我们先内部讨论下再给反馈

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
