### ISSUE TITLE
[BUG]拖动API会产生一个新标签

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6586]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13
**Bug 描述**

简要描述您碰到的问题
API列表页面拖动API会产生一个新标签页，目前只有火狐浏览器有
**Bug 重现步骤**

1.  拖动API列表API

**期待的正确结果**

正确情况下应该是什么样的？
API交换顺序

**截图**

如果有截图，请附上截图.
![1632796877461](https://user-images.githubusercontent.com/36387811/135013829-6693a968-0b28-4388-9f3d-02675f59b397.jpg)

**Comment by zyyfit** [comment]
这个是火狐浏览器的功能，可以禁用这个插件，在 设置 - 扩展和主题 中

![图片](https://user-images.githubusercontent.com/73461316/135073602-78aaf218-047f-4f8b-ab10-c8c3b36d3ea1.png)

![图片](https://user-images.githubusercontent.com/73461316/135073571-6954de64-1797-4def-a330-dcb6cf1b7cf5.png)
