### ISSUE TITLE
[BUG]在case列表拖动case不能交换顺序

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6587]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13
**Bug 描述**

简要描述您碰到的问题
在case列表拖动case不能交换顺序
**Bug 重现步骤**

1.  在case列表拖动case不能交换顺序

**期待的正确结果**

正确情况下应该是什么样的？
交换两个case顺序
**截图**

如果有截图，请附上截图.
![1632796314428](https://user-images.githubusercontent.com/36387811/135014245-dd1cd5c9-72b6-4d44-83ec-4c2ff0f2fae2.jpg)

**Comment by xulinde** [comment]
已知问题，13.1小版本会修复

**Comment by xulinde** [comment]
v1.13.1已修复
