### ISSUE TITLE
[FEATURE]上传的思维导图中tc:后面不能再次出现冒号：

### ISSUE THREAD

**Issue by jsmier666** [metersphere/metersphere#659]
**请描述您的需求或者改进建议.**
用例中tc:后面的文字不能再出现:符号，出现将上传用例失败，建议用例中可同时存在多个：

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，计划下个版本优化，请持续关注～
