### ISSUE TITLE
[BUG]在场景列表交换场景顺序会产生新标签页

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6595]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13
**Bug 描述**

简要描述您碰到的问题
在场景列表交换场景顺序会产生新标签页
**Bug 重现步骤**

1.  在场景列表点击按钮交换场景顺序

**期待的正确结果**

正确情况下应该是什么样的？
场景顺序改变，不会产生新标签
**截图**

如果有截图，请附上截图.
![1632796452426](https://user-images.githubusercontent.com/36387811/135015410-dad7dd45-02ec-4eaa-a238-3841576f157c.jpg)

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/6586
