### ISSUE TITLE
[BUG]在接口定义中文档显示错误

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6600]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13
**Bug 描述**

简要描述您碰到的问题
在接口定义中选中的是SQL协议，API和CASE显示正常，文档却显示的http协议的接口文档
**Bug 重现步骤**

1.  选中SQL协议，点击文档

**期待的正确结果**

正确情况下应该是什么样的？
显示SQL接口文档
<img width="762" alt="截屏2021-09-28 11 04 43" src="https://user-images.githubusercontent.com/36387811/135016461-9a54afe0-4ebe-43b1-bf74-6ca01049c4df.png">

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.13.2已修复
