### ISSUE TITLE
[BUG]接口列表快速切换文档和CASE按钮会报错

### ISSUE THREAD

**Issue by Kyrie890514** [metersphere/metersphere#6603]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

简要描述您碰到的问题
[BUG]接口列表快速切换文档和CASE按钮会报错
**Bug 重现步骤**

1.  进入接口测试的接口定义模块
2. 在接口列表中快速切换文档和CASE按钮
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
无报错
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/62082661/135027639-efb334f0-f6a0-4615-adab-7b413e6957a0.png)

**Comment by xulinde** [comment]
v1.13.1已修复
