### ISSUE TITLE
[FEATURE]建议增加接口自动化场景批量复制或者移动到另一个项目的功能（非场景导入）

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6605]
**请描述您的需求或者改进建议.**
在大型项目中微服务，合并拆分很常见
微服务就是独立的项目，所以MS现在缺跨项目移动的功能。
比如：A项目和B项目需要合并，B项目所有的接口自动化场景需要合并到A项目。
现有的跨项目引用或复制功能导入后会多出一个复制或引用的步骤，手动去掉多出的步骤不现实，因为场景太多了。从B项目导出JMX再导入A项目又会丢掉场景中的引用关系

所以需要把B项目中的场景原封不动转移到A项目的功能

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
