### ISSUE TITLE
[BUG]jmeter场景导入到MS，HTTP请求默认值中的端口识别不到。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6606]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**

jmeter场景导入到MS，HTTP请求默认值中的端口识别不到。

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/87106917/135033610-1c18eba5-c137-4738-9995-7c0f2a07a7eb.png)
![image](https://user-images.githubusercontent.com/87106917/135033672-8cc44b0d-5295-48e9-ba66-dd5de7878396.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.13.1版本已修复了这个问题，请升级使用
