### ISSUE TITLE
上传本地的CSV文件到场景变量里面，过一天后会提示CSV文件不存在

### ISSUE THREAD

**Issue by nullapi** [metersphere/metersphere#6607]
**MeterSphere 版本**
13.0

您所使用的 MeterSphere 版本是？

**Bug 描述**
上传本地的CSV文件到场景变量里面，过一天后会提示CSV文件不存在

**Bug 重现步骤**

1.  设计接口自动化场景，添加本地桌面CSV文件作为场景变量
2. 正常保存，执行接口自动化可正常执行
3. 第二天再次执行该接口自动化，提示csv文件不存在

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/62641393/135036237-d97c8436-b4f7-434a-9bf2-56905abf9cf4.png)
![image](https://user-images.githubusercontent.com/62641393/135036272-370f62b0-fd90-4617-a5e2-4c3a56d7fa34.png)

**Comment by zyyfit** [comment]
您好，没有出现过这个问题，您可以看一下ms服务器里，metersphere/data目录下是否还有这个文件，如果能稳定复现的话您可以加一下ms交流群，让我们的同事帮您查看一下

**Comment by nullapi** [comment]
csv文件是放在本地的，不是服务器上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] 上传本地的CSV文件到场景变量里面，过一天后会提示CSV文件不存在 (#6607)





 
您好，没有出现过这个问题，您可以看一下ms服务器里，metersphere/data目录下是否还有这个文件，如果能稳定复现的话您可以加一下ms交流群，让我们的同事帮您查看一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> csv文件是放在本地的，不是服务器上
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2021年9月29日(星期三) 上午10:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] 上传本地的CSV文件到场景变量里面，过一天后会提示CSV文件不存在 (#6607) 您好，没有出现过这个问题，您可以看一下ms服务器里，metersphere/data目录下是否还有这个文件，如果能稳定复现的话您可以加一下ms交流群，让我们的同事帮您查看一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

在场景中添加csv后，会在服务器上保存一份文件，执行场景的时候读取的是服务器上的文件
