### ISSUE TITLE
[BUG]邮件通知里的链接，无法定位到对应的用例评审

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#661]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
当一个人有多个组织、工作空间的权限时，并且当前登录的组织和工作空间和邮件通知的不一致时，点击邮件里的链接无法访问到对应的测试计划或用例评审，会跳转到系统设置--个人设置页面。
**Bug 重现步骤**
1.  当一个人有多个组织、工作空间的权限时，并且当前登录的组织和工作空间和邮件通知的不一致时
2. 点击邮件里的链接无法访问到对应的测试计划或用例评审，会跳转到系统设置--个人设置页面。
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
应该能定位到该评审。

**截图**
如果有截图，请附上截图.
<img width="515" alt="邮件链接" src="https://user-images.githubusercontent.com/71361375/97938317-16e38a00-1dbc-11eb-986e-e50361820919.png">
<img width="499" alt="跳转到用例评审" src="https://user-images.githubusercontent.com/71361375/97938325-1a771100-1dbc-11eb-814d-32b903efc5c1.png">

**Comment by xulinde2** [comment]
您好，测试计划或用例评审都是有权限限制的，只能是当前组织空间下的人可以访问，其他组织是没办法访问到的

**Comment by zyy2721** [comment]
> 您好，测试计划或用例评审都是有权限限制的，只能是当前组织空间下的人可以访问，其他组织是没办法访问到的

你好，该评审人有多个组织空间的权限，需要评审的这个组织也是有权限的。
