### ISSUE TITLE
[BUG]场景详情页面右下角多了个任务中心的按键。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6611]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.12.2
**Bug 描述**
场景详情页面右下角多了个任务中心的按键。

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/87106917/135042379-00d09de0-df81-407c-9baa-0b7b4fca65d6.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，这个是我们隐藏的任务中心部分，点击右上角的任务中心时会弹框出来的
