### ISSUE TITLE
[FEATURE]jmeter调试好的场景，有环境变量，导入MS还提示要选择场景变量。并且还识别不到HTTP请求头中的端口。

### ISSUE THREAD

**Issue by liuhansong** [metersphere/metersphere#6612]
**请描述您的需求或者改进建议.**

jmeter调试好的场景，有环境变量，导入MS还提示要选择场景变量。并且还识别不到HTTP请求头中的端口。

**请描述你建议的实现方案**
jmeter场景导入 可以直接运行。

**Comment by zyyfit** [comment]
1.15.3已修复
