### ISSUE TITLE
[FEATURE]测试用例的备注、用例评审的描述，需要增加字数

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#662]
**请描述您的需求或者改进建议.**
测试用例的备注，现在限制字数是500字，希望能增加，允许输入更多的内容。
用例评审的描述，现在限制字数是200字，希望能增加，允许输入更多的内容。

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，感觉目前的限制已满足大多数要求啦～
