### ISSUE TITLE
[FEATURE]脑图中可否显示添加的图片，现在只是显示一个链接

### ISSUE THREAD

**Issue by adadale** [metersphere/metersphere#6631]
**请描述您的需求或者改进建议.**

脑图中可否显示添加的图片，现在只是这样的一个链接![xiao.jpg](/resource/md/get/7190f60f_xiao.jpg)，希望能以图片展示

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by stubbornrock** [comment]
想请教一下，这个功能已经实现了嘛？
![image](https://user-images.githubusercontent.com/7532609/220867831-91cc1bb2-c930-4abb-b798-4f79ac33f97f.png)

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
