### ISSUE TITLE
[BUG] 缺陷管理中预览缺陷，图片不显示。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#6635]
版本：1.13.1

现象：缺陷管理中提交带有图片的缺陷（对接的禅道），然后同步缺陷后，图片无法预览。

截图：
![image](https://user-images.githubusercontent.com/44999044/135193406-db49d2a3-c7da-489c-88ef-b14fa296a92f.png)

**Comment by xulinde** [comment]
目前不支持禅道图片回显

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，v1.15.0以上版本修复这个问题，升级到新版本吧
