### ISSUE TITLE
[FEATURE] 测试用例（功能）数统计功能需求。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#6636]
当前版本：1.13.1

背景：
在研发管理过程中，我们会使用一个指标（缺陷率）来体现产品提测的质量，缺陷率算法（缺陷数/实际用例执行数）。
那么问题来了，这个实际用例执行数到底是怎么算的。正规标准的用例是一条只有一个预期结果。但是在实际项目中，创建一条用例时，这条用例里可能涉及多个步骤和多个预期结果（即多个功能小点），我认为这个用例里有几个“预期结果”就相当于有几条用例。固有以下建议，希望贵司考虑一下。

PS：还有一种情况，一些通用性的用例，在项目中可能会执行多次，比如验证输入框可输入长度、输入特殊字符等，这种用例只写一遍，但是执行多次，如何统计执行的次数也是一个问题。

建议：

1. 基于用例的预期结果数量来统计实际用例数。
2. 对于已经执行（测试计划中对某一个小步骤标识过用例执行结果）的预期结果，可以再统计一个实际执行用例数。
3. 自动核算当前缺陷率（缺陷数/实际用例执行数）
4. 对一条用例（预期结果）执行多次的情况，可以通过执行次数来进行乘法运算，得出最终执行的次数。

**Comment by xulinde** [comment]
感谢反馈，我们先进行下相关调研。

**Comment by LimonFHM** [comment]
1

**Comment by LimonFHM** [comment]
啥时候才能有动静呢？

**Comment by luty2018** [comment]
我们会优先做功能性的需求，再做管理类的需求。另外这个拆开统计成用例会跟系统实际用例数对不上，这样不会影响你做统计吗？

**Comment by LimonFHM** [comment]
> 


> 我们会优先做功能性的需求，再做管理类的需求。另外这个拆开统计成用例会跟系统实际用例数对不上，这样不会影响你做统计吗？

目前系统中的用例数对我们来说是用例组数，真正的执行条数还是要看有预期结果的步骤的。我觉得这也不是什么管理需求，我也认为用例数该这么统计。毕竟现在写用例不会一个标题就一个步骤了。

**Comment by LimonFHM** [comment]
咋关闭了。这个我一直比较期待。

**Comment by luty2018** [comment]
> 步骤



> > 
> 
> > 我们会优先做功能性的需求，再做管理类的需求。另外这个拆开统计成用例会跟系统实际用例数对不上，这样不会影响你做统计吗？
> 
> 目前系统中的用例数对我们来说是用例组数，真正的执行条数还是要看有预期结果的步骤的。我觉得这也不是什么管理需求，我也认为用例数该这么统计。毕竟现在写用例不会一个标题就一个步骤了。

你这个统计方式比较定制化，不是通用需求，建议你可以走我们的api来统计
