### ISSUE TITLE
[FEATURE]覆盖导入接口定义，涉及更新的接口标识一下new

### ISSUE THREAD

**Issue by GITMrzk** [metersphere/metersphere#6638]
**请描述您的需求或者改进建议.**
swagger导入接口定义，选择覆盖模式，接口更新时间会全部刷新，无法看出哪些接口是本次涉及更改的，不利于测试人员定位到对应接口并更新测试用例。

**请描述你建议的实现方案**
1、建议进行接口定义的比对（如mac值校验等），对于涉及更改的接口，给出明显的【new】标签提示。
2、对于未涉及更改的接口，不更新 “最后更新时间”字段。

**Comment by xulinde** [comment]
下个版本会优化这里

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
