### ISSUE TITLE
[BUG] 钉钉机器人推送消息中显示的是用户id，建议显示用户名称

### ISSUE THREAD

**Issue by nawentao** [metersphere/metersphere#664]
**MeterSphere 版本**
v1.4.1

**Bug 描述**
钉钉机器人推送消息中显示的是用户id，建议显示用户名称(邮件和企业微信未测试，可能也有这个问题)
**Bug 重现步骤**
1.  触发一个钉钉机器人的人消息推送(使用的用户为ldap用户，id和用户名在后台成员列表中可以正常显示)
2. 在钉钉中查看推送消息，消息为"测试计划任务通知：1232131231创建的'钉钉机器人推送测试'已完成，计划开始时间是2020-11-02 00:00:00计划结束时间为2020-11-03 00:00:00已完成"

**期待的正确结果**
1232131231为用户id，应该显示用户名称

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，本月26号发布的v1.5.0版本会优化这里，您到时候直接升级到最新版本就可以了。
