### ISSUE TITLE
[BUG]阿里云数据库连接报错。

### ISSUE THREAD

**Issue by ZHIGAOwang** [metersphere/metersphere#6642]
您所使用的 MeterSphere 版本是？
MeterSphere  版本 ：v1.13.1-22e8e5f0
**Bug 描述**

正确填写数据库连接信息，连接阿里云数据库连接报错。

简要描述您碰到的问题
MySQL版本：Server version: 8.0.13
jar包版本：mysql-connector-java-8.0.26.jar
本台机器可以连接上阿里云数据库，但是用metersphere就提示：Could not create connection to database server。
![image](https://user-images.githubusercontent.com/33215154/135200976-b606fc57-8919-42d0-9e26-f0f60d690e7f.png)
![C%R A%@ `B%}F) GXSS4NLK](https://user-images.githubusercontent.com/33215154/135200743-fb3302b1-003e-465c-af31-4ebe100ebf35.png)
![RK ND5D3GNYB2GH)$8)CWXW](https://user-images.githubusercontent.com/33215154/135200781-b2eca24f-548a-46cb-93b7-f415edbd1d0a.png)
![HKTZ`AIDZWD001$D1R}G $S](https://user-images.githubusercontent.com/33215154/135200810-ffdda456-d268-416d-bd0d-a55797699dab.png)

**Comment by zyyfit** [comment]
您好，ms暂时不支持mysql-8.0.x，建议您按照官方文档要求的版本进行配置
