### ISSUE TITLE
[BUG]复制用例出现错误

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#6643]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13
**Bug 描述**

简要描述您碰到的问题
复制用例出现错误的用例等级和错误的状态，
**Bug 重现步骤**

1.  在一个空模块
2. 添加俩条用例
3. 复制第二条用例出错

**期待的正确结果**

正确情况下应该是什么样的？
用例等级不带引号，状态是三个备用状态之一
**截图**

如果有截图，请附上截图.
<img width="940" alt="截屏2021-09-29 13 51 13" src="https://user-images.githubusercontent.com/36387811/135211302-08d464ef-0808-4118-8e49-7b91d64c1891.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
