### ISSUE TITLE
[FEATURE]项目下的自定义代码片段目前只能复制，能否添加一个引用的功能，让普通用户无法修改，方便部分固定代码脚本统一标准化

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6649]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/32027713/135377081-269fd76d-b57f-4585-a6a2-443e982ddf63.png)

项目下的自定义代码片段目前只能复制，能否添加一个引用的功能，让普通用户无法修改，方便部分固定代码脚本统一标准化

**Comment by zyyfit** [comment]
感谢反馈，我们进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。主要是脚本里的内容不好控制，这个更多依赖使用规范了。
