### ISSUE TITLE
[FEATURE]新增测试跟踪用例模块可以整个复制

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#6651]
**请描述您的需求或者改进建议.**

有很多用例可以重复放到其他模块使用，一条一条复制，移动，修改名称太慢了，希望增加模块复制功能，提高用例的重用。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
感谢您的建议，后面可以优化

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/2722

https://github.com/metersphere/metersphere/issues/4982

**Comment by zyyfit** [comment]
https://github.com/metersphere/metersphere/issues/7537

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，可以切换到脑图模式下进行整个模块的复制，建议更新到v2.7版本使用。
