### ISSUE TITLE
[FEATURE]建议在metersphere默认缺陷模板中加入状态列，并在查询列表增加对状态列的排序功能

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6653]
**请描述您的需求或者改进建议.**
建议在metersphere默认缺陷模板中加入状态列，并在查询列表增加对状态列的排序功能

**请描述你建议的实现方案**
目前在列表里只能对平台状态列进行排序，无法对在MS中提交的状态进行排序
![5](https://user-images.githubusercontent.com/83771182/135393676-c68cd26c-429f-4f05-a58b-20ebe097a9f2.jpg)

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
1.默认模板中已添加了状态列。
2.状态列增加排序计划在v2.9发布
