### ISSUE TITLE
[FEATURE]编写测试用例时，希望能以表格的形式编辑测试用例：从excel复制到MS，并进一步编辑

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6654]
**请描述您的需求或者改进建议.**

[FEATURE]编写测试用例时，希望能以表格的形式编辑测试用例：从excel复制到MS，并进一步编辑

**请描述你建议的实现方案**
类似wiki的编辑

**Comment by xulinde** [comment]
感谢您的建议，我们先讨论下再给反馈

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
