### ISSUE TITLE
[FEATURE] 与jira集成后，测试用例希望能关联多个JIRA需求，有可能一个测试用例关联多个相关联的需求

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6655]
**请描述您的需求或者改进建议.**

与jira集成后，测试用例希望能关联多个JIRA需求，有可能一个测试用例关联多个相关联的需求

**请描述你建议的实现方案**
希望一条测试用例能关联多个jira需求

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
