### ISSUE TITLE
[BUG] V1.13.0接口定义和接口场景模块名称失败，提示sql  error happen

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#6656]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  修改模块名称，保存时，提示异常
2. 
3. 
4. 
![image](https://user-images.githubusercontent.com/26110332/135396239-b5e0096a-416e-4b89-b2a4-5d1fda1881ad.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/26110332/135396244-a6ac349a-fade-4d11-ae55-55a842af0d48.png)

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.13.1已修复
