### ISSUE TITLE
[BUG] 接口测试中通过JMeter函数获取线程编号失败

### ISSUE THREAD

**Issue by jason-fit2cloud** [metersphere/metersphere#6663]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.10.3-10ac86a0

**Bug 描述**
做性能测试时，使用每个线程模拟一个监控采集客户端发送某台虚拟机的CPU监控数据到监控写入接口，
在场景变量中添加了变量threadNo，值使用JMeter 函数S{__threadNum}，在接口用例的前置脚本中，获取threadNo值，
获取到的不是线程编号，而是StandardJMeterEngine

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景，循环10次调用某接口用例
2. 在场景变量中添加了变量threadNo，值使用JMeter 函数S{__threadNum}
3. 导入一个接口测试用例
4. 测试用例前置脚本内容为
#验证JMeter函数
threadNo=vars.get("threadNo")
print('threadNo=%s' % threadNo)
strUUID=vars.get("UUID")
print('strUUID=%s' % strUUID)
4. 调试执行场景，并到控制台输出查看前置脚本获取打印出来的线程编号threadNo和UUID，
线程编号未获取到预期正确的编号，UUID获取正确
以上步骤的截图见下方

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图
<img width="1280" alt="Screen Shot 2021-10-05 at 12 20 30 PM" src="https://user-images.githubusercontent.com/9998431/135960549-0f12d146-c40b-4674-b5d7-78c09faa4de5.png">

<img width="1024" alt="Screen Shot 2021-10-05 at 12 20 46 PM" src="https://user-images.githubusercontent.com/9998431/135960568-7d0c2622-b90c-41bc-a1ae-da24468dbc79.png">
<img width="942" alt="Screen Shot 2021-10-05 at 12 21 28 PM" src="https://user-images.githubusercontent.com/9998431/135960575-720ac690-383f-4760-b003-140f7836522d.png">
<img width="1069" alt="Screen Shot 2021-10-05 at 12 22 05 PM" src="https://user-images.githubusercontent.com/9998431/135960590-0558b4bb-15b5-4f53-bfc4-5a1fba58e466.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，这个返回值是对的，jmeter里面测试也是返回的这个StandardJMeterEngine
