### ISSUE TITLE
[BUG]使用接口文档导入接口，已编写的api的状态变成已完成后，又恢复进行中了

### ISSUE THREAD

**Issue by 462548187** [metersphere/metersphere#6666]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

使用swagger文档导入接口，已变成过接口case后，并标注接口状态为已结束。在导入接口文档，以前选择的已结束的状态也变成进行中

![image](https://user-images.githubusercontent.com/23581094/136496288-55a7c8db-03a9-43bc-ae5f-d411d21c9e81.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by 462548187** [comment]
那原有已编辑的接口并修改状态为已完成的，我怎么导入而不影响这些接口的状态呢？？？

**Comment by zyyfit** [comment]
> 那原有已编辑的接口并修改状态为已完成的，我怎么导入而不影响这些接口的状态呢？？？

不太明白您的意思，为什么接口有变动还不修改接口状态呢？

**Comment by 462548187** [comment]
好的，谢谢

**Comment by zyyfit** [comment]
最新版已修复
