### ISSUE TITLE
[FEATURE]希望可以自动把导入的场景中的场景变量设置到主场景的场景变量中

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#6668]
**请描述您的需求或者改进建议.**

场景导入时，场景变量应该需要自动设置到主场景的场景变量吧，不然的话，变量比较难进行统一管理。如图所示。
![image](https://user-images.githubusercontent.com/62236451/136505430-6cf87836-14a0-4b15-aa79-d806ada17464.png)

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
最新版本v1.20.5已优化，建议升级
