### ISSUE TITLE
[FEATURE]场景变量编辑时希望可以新增一列描述

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#6669]
**请描述您的需求或者改进建议.**
场景变量的显示应该显示多一列描述的
![image](https://user-images.githubusercontent.com/62236451/136508479-147b7624-0651-4a8e-81d5-c0a1f71f2139.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，会在v2.9发布。
