### ISSUE TITLE
[FEATURE]编辑csv格式的场景变量时，希望可以新增一个下载csv文件的功能。

### ISSUE THREAD

**Issue by guoyang-fit2cloud** [metersphere/metersphere#6670]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/62236451/136509193-2984358f-5bcc-4801-8181-77c8a6ccd232.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
最新版 1.15.1 已增加下载功能
