### ISSUE TITLE
[FEATURE]性能测试列表页面希望与接口列表一样，有执行按钮

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6676]
**请描述您的需求或者改进建议.**

性能测试列表页面希望与接口列表一样，有执行按钮

![image](https://user-images.githubusercontent.com/88763608/136527357-ac4f6628-a7e0-4eb3-9804-5e1664a99f1f.png)

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
