### ISSUE TITLE
[BUG]修改模块名称或者场景名称报错，创建场景，点击“+”号，不能添加成功。前端console报错

### ISSUE THREAD

**Issue by fan1992619** [metersphere/metersphere#6695]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.13.0-1e92a35d
**Bug 描述**
修改模块名称或者场景名称报错，创建场景，点击“+”号，不能添加成功。前端console报错
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37108251/136650502-1d3fd7fb-f67f-4ae3-8724-f412a4822788.png)
![image](https://user-images.githubusercontent.com/37108251/136650508-079145e0-edb2-422d-9542-d297f22b4b46.png)

**Comment by zyyfit** [comment]
您好，第二个是已知问题，会在后续版本修复，第一个没有复现，能描述一下详细操作步骤吗

**Comment by zyyfit** [comment]
1.13.2已修复第二个问题
