### ISSUE TITLE
[FEATURE]在思维脑图中-编辑复制用例，也可以增加打标签功能（维护用例迭代版本）

### ISSUE THREAD

**Issue by Wind-Liv5** [metersphere/metersphere#6698]
**请描述您的需求或者改进建议.**

现状：
目前测试用例维护是以迭代版本来维护，即在每一个模块下对应的测试用例增加**标签**标记迭代版本
在创建测试评审 测试计划时，通过本次**迭代标签**过滤出需要执行的用例进行执行
![图片](https://user-images.githubusercontent.com/70939960/136680624-8f1a8ba6-a9e2-4497-b0fb-34ed7abd811f.png)

我们想：
1、能够在思维脑图中-编辑复制用例，也可以增加打标签（维护用例迭代版本）的功能
2、思维脑图/列表模式-复制用例的时候也希望可以复制对应的标签（目前无法复制标签）
2、在创建用例评审-关联执行-筛选列表上也展示标签字段（目前高级搜索可以筛选，但是列表展示没有对应标签字段，展示不够直观，测试计划中是有的）

**请描述你建议的实现方案**
方案如上

**Comment by Wind-Liv5** [comment]
没人吗？

**Comment by wangzhen-fit2cloud** [comment]
@luty2018

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 现状： 目前测试用例维护是以迭代版本来维护，即在每一个模块下对应的测试用例增加**标签**标记迭代版本 在创建测试评审 测试计划时，通过本次**迭代标签**过滤出需要执行的用例进行执行 ![图片](https://user-images.githubusercontent.com/70939960/136680624-8f1a8ba6-a9e2-4497-b0fb-34ed7abd811f.png)
> 
> 我们想： 1、能够在思维脑图中-编辑复制用例，也可以增加打标签（维护用例迭代版本）的功能 2、思维脑图/列表模式-复制用例的时候也希望可以复制对应的标签（目前无法复制标签） 2、在创建用例评审-关联执行-筛选列表上也展示标签字段（目前高级搜索可以筛选，但是列表展示没有对应标签字段，展示不够直观，测试计划中是有的）
> 
> **请描述你建议的实现方案** 方案如上

会在最近的版本中安排优化

**Comment by luty2018** [comment]
1、能够在思维脑图中-编辑复制用例，也可以增加打标签（维护用例迭代版本）的功能
-- 这个会在v3.0执行
2、思维脑图/列表模式-复制用例的时候也希望可以复制对应的标签（目前无法复制标签）
-- 这个会在v3.0执行
3、在创建用例评审-关联执行-筛选列表上也展示标签字段（目前高级搜索可以筛选，但是列表展示没有对应标签字段，展示不够直观，测试计划中是有的）
-- 这个会在v2.8执行

**Comment by Wind-Liv5** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我有事不在，无法亲自回复您的邮件。我将在阅读后，尽快给您回复。

**Comment by Wind-Liv5** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我有事不在，无法亲自回复您的邮件。我将在阅读后，尽快给您回复。
