### ISSUE TITLE
[ENHANCEMENT]添加用例步骤时，点击+号后新出现一行，点击该行显示输入框时没有获得焦点，建议输入框自动获取到输入焦点

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#67]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by shiziyuan9527** [comment]
双击新建行的步骤描述或预期结果获取输入框焦点
