### ISSUE TITLE
[FEATURE]缺陷管理增加缺陷状态筛选功能

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#6704]
**请描述您的需求或者改进建议.**

根据缺陷状态筛选

**请描述你建议的实现方案**
![截屏2021-10-11 14 05 00](https://user-images.githubusercontent.com/36387811/136742351-cfb8b195-cbdf-4a6f-aa85-6a7f95f234a2.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化
