### ISSUE TITLE
[FEATURE]缺陷管理增加高级搜索功能

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#6705]
**请描述您的需求或者改进建议.**

缺陷管理增加高级搜索功能

**请描述你建议的实现方案**
![截屏2021-10-11 14 25 51](https://user-images.githubusercontent.com/36387811/136742524-428348d6-d2da-4395-a522-28c0639baad7.png)

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
