### ISSUE TITLE
[BUG]接口测试test中，通过api导入有提取变量值的api，导进来的数据未显示提取值

### ISSUE THREAD

**Issue by leeliangstudy** [metersphere/metersphere#6708]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  导入api里含有提取值
![bcba5defdd207796fe02dfeaef129d3](https://user-images.githubusercontent.com/89442766/136757755-cffc3799-4510-442b-b6b3-a83d33ba432a.png)

2. 第二个接口新增前置脚本，导入API定义
![13e563365b0de50f122167e09807f61](https://user-images.githubusercontent.com/89442766/136757843-ead2416b-d628-414a-84e2-2bdf863b6509.png)

3. 没有提取值那个字段
4. 
![image](https://user-images.githubusercontent.com/89442766/136758453-f776d8fd-4787-4c69-b674-69c4877467be.png)

4. 

**期待的正确结果**

正确情况下应该是什么样的？
应该有提取值的字段，且可以作为本接口的传参

**截图**

如果有截图，请附上截图.

**Comment by leeliangstudy** [comment]
@shenkaibo

**Comment by shenkaibo** [comment]
应该是 导入 的 case

**Comment by zyyfit** [comment]
那应该是正常的，case是支持添加提取的，接口定义是不支持添加提取的，所以引用接口定义是不会带提取的
