### ISSUE TITLE
[BUG]通过execl导入测试用例，在测试计划中执行是显示多个空格操作步骤

### ISSUE THREAD

**Issue by leeliangstudy** [metersphere/metersphere#6709]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  通过execl导入功能测试用例，执行测试计划时发现多个空白的操作步骤
![2fef77b44c04c1ba112eab8fdb6ccbb](https://user-images.githubusercontent.com/89442766/136759022-6da9bc7e-8e2f-4b16-a7b6-844c57b31b28.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，方便上传一下原始Excel文件给我们看看吗

**Comment by shenkaibo** [comment]
[Metersphere_case_Databuff.xlsx](https://github.com/metersphere/metersphere/files/7334391/Metersphere_case_Databuff.xlsx)
