### ISSUE TITLE
[BUG]在用例列表页面中，如果用例显示条数设置为100条/页，或50条/页时，点击全选选框，页面反应卡顿，响应时间较久

### ISSUE THREAD

**Issue by qierzhen** [metersphere/metersphere#6710]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1-22e8e5f0

**Bug 描述**
简要描述您碰到的问题
在用例列表页面中，如果用例显示条数设置为100条/页，或50条/页时，点击全选选框，页面反应卡顿，响应时间较久

**Bug 重现步骤**

1.  打开测试跟踪-功能用例页面
2. 选中一个测试用例大于100条模块，点击全选选框，页面反应卡顿，响应时间较久

**期待的正确结果**
页面不卡顿
正确情况下应该是什么样的？
页面不卡顿
**截图**
![Uploading image.png…]()

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.14.2做了一部分优化，目前稍微快一些了
