### ISSUE TITLE
[BUG]Mysql自定义请求添加JSONPath断言失败（实际应该是成功的）

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6723]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.1

**Bug 描述**

简要描述您碰到的问题

自动化场景下添加sql自定义请求，然后按列存储，添加JSONPath断言，调试后发现断言失败，实际是应该成功的，后改为脚本断言成功

**截图**

如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/32027713/136887903-184c683a-e5c4-4168-872b-1f7373847735.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，响应结果不是json格式，不能使用jsonpath
