### ISSUE TITLE
[BUG]拖动功能用例之后，脑图的顺序还是按照最后更新时间进行排序的，并非按照实际拖动的顺序排列的

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6725]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.1
**Bug 描述**
拖动功能用例之后，脑图的顺序还是按照最后更新时间进行排序的，并非按照实际拖动的顺序进行排列的

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.13.1版本应该是排序有点问题，下个版本会修复的

**Comment by zyyfit** [comment]
1.13.2已修复
