### ISSUE TITLE
[FEATURE] 在环境配置中添加的HTTP请求头能够自动显示在API页面里（包括API/TEST/CASE/文档各个页面）

### ISSUE THREAD

**Issue by dronl** [metersphere/metersphere#6730]
**请描述您的需求或者改进建议.**

目前在环境配置中添加的HTTP请求，并不会呈现在对应的API页面里，对于不了解环境配置的普通用户，会导致困惑和误解

**请描述你建议的实现方案**

在所有适用的API页面里展示该请求头，并显示为不可编辑状态（可参考POSTMAN设计），包括API/TEST/CASE页面。如果可以，文档页面也可以加上。
![image](https://user-images.githubusercontent.com/82429708/136905212-3dd31b46-27a6-4832-b691-470108fb67f2.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求
