### ISSUE TITLE
[BUG]在功能用例的脑图操作中，发现无法新增和修改测试用例，如果在同级有模块的情况下。

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#6732]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在功能用例的脑图操作中，发现无法新增和修改测试用例，如果在同级有模块的情况下。
2. 
![bb03785bb51753fe583461c35415952](https://user-images.githubusercontent.com/20573589/136906702-13b2f405-0135-4522-aa6b-43c7bb16cb76.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，不过1.13.2版本修复了几个脑图的问题，您可以升级看看

**Comment by mileslian** [comment]
在v1.13.2已解决
