### ISSUE TITLE
[BUG]测试计划

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#6743]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.0
**Bug 描述**

简要描述您碰到的问题
测试计划关联场景用例，执行测试计划状态为“completed”，查看测试报告场景用例的执行结果为“未开始”

**Bug 重现步骤**

1. 测试计划关联1条场景用例  
2. 在测试计划手动触发执行
3. 待测试报告Completed查看测试计划报告 
4. 查看场景用例执行结果为“未开始”

**期待的正确结果**

正确情况下应该是什么样的？

当测试计划显示执行完成时，用例应该为执行“成功”或者“失败”

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/89765365/136928930-135e57b9-9a3e-4d1e-a6a8-d839f74f27c4.png)
![image](https://user-images.githubusercontent.com/89765365/136929137-4e7c7cd8-2535-46d3-bbf2-0af5d0c16598.png)

**Comment by youliyuan-fit2cloud** [comment]
你执行的场景用例，上图是功能用例结果，请查看 “接口用例测试结果”
