### ISSUE TITLE
[QUESTION]性能测试页面提示“Cannot read properties of undefined (reading 'graphic')”

### ISSUE THREAD

**Issue by fairyflying** [metersphere/metersphere#6750]
**请描述您的问题.**
开始压测时，页面提示性能测试页面提示：“Cannot read properties of undefined (reading 'graphic')”
请问这是什么原因呢？

**Comment by wangzhen-fit2cloud** [comment]
你好，请清空缓存重试一下或者升级到最新版本使用。如果问题仍然存在，请提供下详细的版本信息及报错日志。
