### ISSUE TITLE
[BUG]通过脑图写的用例，在左侧模块的数量统计没有实时更新

### ISSUE THREAD

**Issue by zhuifengshen** [metersphere/metersphere#6761]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ v1.13.1

**Bug 描述**

如下图所示

**期待的正确结果**

自动更新测试用例数据

**截图**

![image](https://user-images.githubusercontent.com/6891304/137096158-d0a74678-5982-423c-a537-5587a2805bb0.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
