### ISSUE TITLE
[BUG]批量添加测试场景用例，在弹出层创建测试计划报错500

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#6762]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1
**Bug 描述**

简要描述您碰到的问题

批量添加测试场景创建测试计划报错500

**Bug 重现步骤**

1.接口测试--接口自动化--勾选多个场景列表--批量操作添加到测试计划
2.在弹出层左上角点击“创建测试计划”
3.输入“计划名称” 点击“确定”  报500错误(后台报空指针)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/89765365/137097626-da2b7a70-a982-4cd6-8423-85f82ec88286.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版没有复现创建报错的问题，您可以升级到最新版试试
负责人的问题后面的版本优化

**Comment by zyyfit** [comment]
1.16.0已修复在接口模块创建测试计划时，负责人是单选的问题
