### ISSUE TITLE
[BUG]按住鼠标左键批量「圈选」用例并删除，然后点击「保存」，提示「保存成功」，刷新页面发现删除的用例又回来了

### ISSUE THREAD

**Issue by zhuifengshen** [metersphere/metersphere#6763]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.13.1

**Bug 描述**

如截图所示

**期待的正确结果**

正确删除已圈选的用例

**截图**

![image](https://user-images.githubusercontent.com/6891304/137100589-5d11d901-193b-41f1-b67a-9efe3f073852.png)

**Comment by zyyfit** [comment]
1.13.2已修复
