### ISSUE TITLE
[BUG]复制用例到其他模块中，然后点击保存，复制过来的用例消失了

### ISSUE THREAD

**Issue by zhuifengshen** [metersphere/metersphere#6764]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？v1.13.1

**Bug 描述**

如截图所示

**期待的正确结果**

复制过来的用例可以正常保存

**截图**
![image](https://user-images.githubusercontent.com/6891304/137098981-92cb8ce3-27de-4fc9-93ec-73a2362b43ff.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
