### ISSUE TITLE
[BUG]接口自动化中，请求URL ？后面的参数会添加多次参数在query 内,导致请求参数重复

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#6773]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.3.2
**Bug 描述**

简要描述您碰到的问题
接口自动化中，请求URL ？后面的参数会添加多次参数在query 内,导致请求参数重复

具体步骤请查看下放视频
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

https://user-images.githubusercontent.com/32027713/137263802-38773b01-4c16-41e2-8ce6-879b498f785c.mp4

**Comment by zyyfit** [comment]
1.14.2已优化
