### ISSUE TITLE
[FEATURE] 同步缺陷的同时希望能把禅道已创建bug也同步到MeterSphere平台

### ISSUE THREAD

**Issue by Wind-Liv5** [metersphere/metersphere#6774]
**请描述您的需求或者改进建议.**

同步缺陷的同时希望能把禅道已创建bug也同步到MeterSphere平台

![图片](https://user-images.githubusercontent.com/70939960/137263979-13f2563e-7a06-4e03-977b-7dc3af5ca231.png)

**请描述你建议的实现方案**

同步缺陷接口，可以支持拉取禅道已创建的历史bug

**Comment by zyyfit** [comment]
1.15.1已增加这个功能，这是我们企业版的功能
