### ISSUE TITLE
飞书通知提醒升级后不能使用

### ISSUE THREAD

**Issue by hchangfa** [metersphere/metersphere#6776]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**
metersphere从1.10升级到1.13.2版本，飞书通知提醒不能使用
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
升级不影响以前的功能
正确情况下应该是什么样的？
飞书通知提醒可以正常使用
**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没复现该问题，请详细描述下哪个类型事件通知，是接口还是性能测试，还是Jenkins任务通知？
