### ISSUE TITLE
[BUG]Chrome导出jmx文件，导入metersphere，API可以调试，API对应的case不能调试，原因是case发送求情${BASE_URL_0}（录制的参数）没有被“环境信息”替换

### ISSUE THREAD

**Issue by swmvp** [metersphere/metersphere#6783]
**MeterSphere 版本**
>v1.10.11-lts-c237e249。

**Bug 描述**

metersphere Chrome插件导出jmx文件，导入metersphere，API可以调试，API对应的case不能调试，原因是case发送求情${BASE_URL_0}（录制的参数）没有被“环境信息”替换

**Bug 重现步骤**

1.  Chrome导出jmx文件
2. 导入metersphere中
3. 确保API能跑通，进行case测试

**期待的正确结果**

case测试也能正常跑通

**截图**

![case调试-请求](https://user-images.githubusercontent.com/5661341/137298522-498c4712-b923-4948-8b37-9985e1be626a.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题~

**Comment by fit2-zhao** [comment]
@swmvp 感谢反馈，目前场景中单请求调试只支持从场景变量或执行环境 变量中获取；BASE_URL_0 这个变量目前看是在其他步骤中出现，如果想生效 需要整体调试。
