### ISSUE TITLE
[BUG]接口用例，form-data里接口参数里，选择file类型，上传文件，调试接口报找不到文件

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6784]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题
1.接口用例，form-data里接口参数里，选择file类型，上传文件，调试接口报找不到文件
![image](https://user-images.githubusercontent.com/30038088/137298653-c2709e07-86ce-4c10-bf40-ba39a8fbcdea.png)

2.到服务器的 /opt/metersphere/data/body/ 目录下 ，找不到这个文件
**Bug 重现步骤**

1.
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
/opt/metersphere/data/ 目录的id 不是 接口用例的id

**Comment by shenkaibo** [comment]
@Dyc2333

**Comment by zyyfit** [comment]
1.14.1已修复
