### ISSUE TITLE
[BUG]从一个模块A复制一个场景01，并移动该场景01到另一个模块B，运行B模块的场景01后，无法获取运行环境的ip地址

### ISSUE THREAD

**Issue by scl95tx** [metersphere/metersphere#6788]
您所使用的 MeterSphere 版本是？
V1.9

**Bug 描述**
自动化场景，运行时，拿不到运行环境的ip地址

**Bug 重现步骤**

1. 新建接口，添加到接口模块A
2. 在接口自动化部分，新建场景模块A和场景模块B
3. 接口自动化场景模块A中，新建场景A，并且为场景A设置运行环境，运行环境配置的url启用条件为：接口模块A
4. 复制场景A，名为场景AA，并改变场景AA运行环境（换个ip地址），并移动场景AA到场景模块B
5. 在场景模块B中，运行场景AA

**期待的正确结果**
可以拿到ip地址，并正确执行测试
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by scl95tx** [comment]
![image](https://user-images.githubusercontent.com/92519146/137303144-c65c7943-3efd-42b6-9758-0a4f10a90f53.png)

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，您可以升级到最新版试试，另外，模块匹配针对的是接口模块，不包括场景模块
