### ISSUE TITLE
【功能测试】测试用例设计中的前置条件的上传图片，表格，复制粘贴图片功能体验不佳

### ISSUE THREAD

**Issue by candicexm** [metersphere/metersphere#6792]
**请描述您的需求或者改进建议.**
![1634263554(1)](https://user-images.githubusercontent.com/92559536/137421591-34d2318c-2cc9-4df3-bbb0-f66173dc32e9.jpg)

在补充一点：
表格如果有合并单元格，取消合并单元格功能就更好了

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求
