### ISSUE TITLE
[Feature]集成jira后，新增缺陷模版多值输入框不支持传入对象

### ISSUE THREAD

**Issue by wangchen1204** [metersphere/metersphere#6794]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1-b4
**Bug 描述**

简要描述您碰到的问题
集成jira后，新增缺陷模版多值输入框不支持传入对象
**Bug 重现步骤**

1.  集成jira
2. 新增多值输入框字段
3. jira模版添加自定义的多值输入框字段
4. 保存模版，新建缺陷
5. 保存

**期待的正确结果**

正确情况下应该是什么样的？
缺陷保存成功
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/48349088/137423075-02de53a7-534d-4498-a4cb-a12b502686e4.png)

@shenkaibo

**Comment by shenkaibo** [comment]
![901634266024_ pic_hd](https://user-images.githubusercontent.com/30038088/137424757-1108ba60-4ac5-4957-9424-7b9e2eec7c25.jpg)
