### ISSUE TITLE
[FEATURE]前置SQL优化

### ISSUE THREAD

**Issue by hexiaomiao** [metersphere/metersphere#6795]
**请描述您的需求或者改进建议.**

前置SQL如果能引用就好了，使用中发现高频率的SQL就那几个，然后每执行一条用例都要写重复的SQL，很不方便

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
请问您是在场景中使用呢还是在单个的用例中使用呢？
我们有sql类型的请求，如果您是在场景中使用，可以直接引用sql类型的请求的
