### ISSUE TITLE
[FEATURE]接口自动化全屏编辑页面，接口名称显示不全，单条运行时，不显示运行结果，比较不方便

### ISSUE THREAD

**Issue by moli3913** [metersphere/metersphere#6798]
**请描述您的需求或者改进建议.**

![18afea4f5cf463b41514bc019fe55f7](https://user-images.githubusercontent.com/92572683/137454480-8d25b557-5b4d-44ae-872f-daeb327fb715.png)

**请描述你建议的实现方案**
1. 有足够的空间显示的，建议显示完整
2. 单条执行也能像批量执行那样，在左边直接显示最终结果，方便知道案例是否执行失败。

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
