### ISSUE TITLE
[BUG]新建用例勾选保存并继续创建后，新的用例内容没有清空

### ISSUE THREAD

**Issue by zhoujimin** [metersphere/metersphere#68]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
新用例的编辑页面清空前置条件，执行步骤及备注信息
@shiziyuan9527
