### ISSUE TITLE
[BUG]接口测试：请求参数如果存在相同的变量，mock会识别不到，报404

### ISSUE THREAD

**Issue by moli3913** [metersphere/metersphere#6800]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ V1.13.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 添加一个接口，设置请求参数存在重复参数：如：
"detail": [
        {
            "contract_id": 20178,
            "amount": 100000
        },
        {
            "contract_id": 20156,
            "amount": 100000
        }
2. mock环境配置一样的请求参数后，保存，在mock环境请求接口报404；

**期待的正确结果**

正确情况下应该是什么样的？mock正常响应。

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
最新版没有复现这个问题，我们也修改了一些mock相关的问题，您可以升级到最新版试试
