### ISSUE TITLE
[BUG] 脑图功能，用着用着，经常出现重复的用例。

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#6801]
1.13.1 

脑图功能，用着用着，经常出现重复的用例。目前在公司组内试用，5个人全部出现此情况，频率较高。

![企业微信截图_16342865547871](https://user-images.githubusercontent.com/44999044/137457257-03d75f8a-fd94-4e91-882e-84ceb3ce489a.png)

![image](https://user-images.githubusercontent.com/44999044/137457059-43e27f2c-f74d-4f33-abf1-d4a8a46240b4.png)

**Comment by zyyfit** [comment]
您好，能详细说一下在什么情况下会这样吗

**Comment by LimonFHM** [comment]
> 您好，能详细说一下在什么情况下会这样吗

比如我现创建了10个用例，保存，然后继续写 11  12   13 ，这时我发现第 1   3  5  需要修改，我直接在脑图上回头修改步骤或者标题，然后一起保存一下，这时整个列表就会刷新一下，然后就出现了重复的情况。【注意这个场景要放到实际工作中，写用例是一个比较长时间的过程，重现时慢一些】

**Comment by zyyfit** [comment]
您好，最新版我试了一下没有出现这种情况了，您如果后面使用再出现这种情况的话可以把这个问题重新打开或者再提一个issue
