### ISSUE TITLE
[BUG] postman格式接口导入url路径大写字母全变成了小写字母

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#6802]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
 v1.13.1-22e8e5f0

**Bug 描述**

postman格式接口导入url路径大写字母全变成了小写字母

**Bug 重现步骤**

1.  postman格式里有这个 "path":["/system/user/pageByKeyword"]
2. 导入之后接口定义url就都变成小写的"path":["/system/user/pagebykeyword"]
3. 
4. 

**期待的正确结果**

保留正确的url

![Uploading image.png…]()

**Comment by youliyuan-fit2cloud** [comment]
你好,v1.13.2版本没复现该问题，你升级到最新版本试试哈
