### ISSUE TITLE
[BUG]性能测试时的资源文件无法正常删除

### ISSUE THREAD

**Issue by fairyflying** [metersphere/metersphere#6803]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v13.1
**Bug 描述**
压测时的资源文件删除了刷新页面又出现
简要描述您碰到的问题

**Bug 重现步骤**

1.  建立性能测试
2. 在资源文件处上传文件
3. 执行压测后前往资源文件处删除文件
4. 删除后刷新页面

**期待的正确结果**
删除后刷新页面文件已删除，但实际刷新页面仍存在
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您删除文件后保存了吗？
