### ISSUE TITLE
[BUG]将项目A的场景1导入项目B的场景时，如何设置可以在调试时A使用B的运行环境？

### ISSUE THREAD

**Issue by lihuan222** [metersphere/metersphere#6808]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.13.2
**Bug 描述**

将项目A的场景1导入项目B的场景时，在场景详情调试时必须要设置A的运行环境，但在项目B的场景列表直接执行是可以的

**Bug 重现步骤**

1.  项目A存在下单功能，已添加为场景1
2. 新建项目B，A/B两个项目域名不一样，但存在相同的下单功能
3. 在项目B中新建场景，通过“场景导入”导入项目A的场景1
4. 在新建场景的详情页面，点击调试

**期待的正确结果**
导入进来的场景可以使用项目B的运行环境进行调试

**截图**
![image](https://user-images.githubusercontent.com/48313039/137577212-5e6b8ccb-a3c0-4bb9-9f43-35967cf16500.png)

现在调试失败，提示“请为当前场景选择一个运行环境！”；但如果为两个项目都设置了运行环境，那导入的场景就按项目A的运行环境执行；

但在项目B的场景列表执行，导入进来的项目A的场景1是用项目B的运行环境执行了

**Comment by zyyfit** [comment]
目前引用的场景只能选择他之前所在项目的环境，不过环境是可以添加配置的，您可以在被引用的项目中配置一个项目B的环境，引用过来之后选择对应的环境就可以了

或者您是想要引用其他项目的场景后可以选择当前项目的环境？这样的话我们需要内部评估一下这个需求

**Comment by zyyfit** [comment]
最新版已增加这个功能
![图片](https://user-images.githubusercontent.com/73461316/144183427-02f93dc2-9d67-40d3-9a05-5c949ea085c3.png)
