### ISSUE TITLE
[BUG]一键安装报错

### ISSUE THREAD

**Issue by jerometang** [metersphere/metersphere#6809]
**Bug 重现步骤**

1.全新安装centos 7  
2. 运行一键安装脚本
3. curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh
4. 显示的错误结果
sh:行12: wget: 未找到命令
tar (child): metersphere-online-installer-v1.13.2.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sh: 第 15 行:cd: metersphere-online-installer-v1.13.2: 没有那个文件或目录
sed：无法读取 install.conf：没有那个文件或目录
sed：无法读取 install.conf：没有那个文件或目录
/bin/bash: install.sh: 没有那个文件或目录

**Comment by zyyfit** [comment]
您好，您的机器是否没有安装wget命令呢？可以用yum命令安装一下再执行一键安装脚本：yum install wget -y

**Comment by jerometang** [comment]
多谢
