### ISSUE TITLE
[FEATURE]希望用例评审UI界面优化，试用投频显示

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#681]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/26785348/98078230-a9fbed00-1eac-11eb-978d-27e21ea9bc46.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，能否详细描述下期望的显示方式

**Comment by leosrzheng** [comment]
评审时步骤要全部打开



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 中午11:29
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]希望用例评审UI界面优化，试用投频显示 (#681)





 
你好，能否详细描述下期望的显示方式
