### ISSUE TITLE
[BUG]启动之后，数据库所有连接都被占满！

### ISSUE THREAD

**Issue by happywzy** [metersphere/metersphere#6810]
**MeterSphere 版本**
>v1.13.2

启动之后，数据库所有连接都被占满，太夸张了。
![image](https://user-images.githubusercontent.com/26290710/137652934-e209d0fb-95b4-406a-97fd-0dcaf0d34781.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，建议升级到较新版本试试吧，我们有优化这里
