### ISSUE TITLE
[BUG]页面场景过大，导致打开场景网页崩溃out of memory

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6811]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.10.10-lts

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题
