### ISSUE TITLE
[FEATURE]项目管理-建议增加各批量移除成员，每个项目中进行批量调整权限时就繁琐了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#6814]
**请描述您的需求或者改进建议.**

项目管理-建议增加各批量移除成员，每个项目中进行批量调整权限时就繁琐了

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by luty2018** [comment]
v3.0已规划
