### ISSUE TITLE
[FEATURE] Add dynamic mock function

### ISSUE THREAD

**Issue by maojunxyz** [metersphere/metersphere#6816]
**请描述您的需求或者改进建议.**

When I request an interface, I need to return different response content depending on the request.

For example, when I request to get person information based on id, I want to be able to follow a generic Mock dynamic template (like [mockjs](https://github.com/nuysoft/Mock/tree/refactoring)) and return a random name when I use `@name` and a random Chinese name when I use `@cname`.

**请描述你建议的实现方案**

Add a dynamic data function instead of a single static data return. Users can use the agreed dynamic data template on the page, parse and generate dynamic data return on the server side.

**Comment by zyyfit** [comment]
Thanks for your feedback, we will optimize it in future releases
