### ISSUE TITLE
[FEATURE]邮件报告参数获取全局变量

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#6818]
**请描述您的需求或者改进建议.**
因为我们的邮件报告需要的参数包含 执行时长、API平均响应时间、API请求总数、API请求通过率，希望能把这些参数设置成全局变量，因为我们自己无法实现。

<img width="244" alt="cc642c1189faa0ae5120bece1aff6cb" src="https://user-images.githubusercontent.com/85992665/137674929-e9b7c07d-768e-463d-8d69-badb6bef7260.png">

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议申请企业版使用。
