### ISSUE TITLE
[FEATURE]需要更多的参数

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#6819]
**请描述您的需求或者改进建议.**

比如，执行时长、执行环境、API平均响应时间、API请求总数、API请求通过率、测试时间、执行率、场景用例数、步骤用例数、失败的场景用例数、失败的步骤用例数这些参数都是会用到的，希望可以加到全局变量，到时候可以调用。

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能在企业版已经支持了，可以申请企业版使用。
