### ISSUE TITLE
[FEATURE]希望测试用例可以批量复制

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#682]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by pcc426** [comment]
我有类似的需求，场景大概是这样：之前测过某个A服务，写了一批用例在A/list模块下，然后新有一个B服务准备测试，它也有个很类似A的list模块，所以希望能把A/list模块下的所有用例一次性都复制到B/list模块下，然后我作为维护人再修改每个用例的一些细微差别就行了。
目前只支持从A/list模块批量移动到B/list，但如果是移动的话A模块下面就没这批用例了，后续可能还是要执行的，所以希望有个批量复制并移动的功能

**Comment by leosrzheng** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pcc426"<notifications@github.com&gt;; 
发送时间: 2020年11月10日(星期二) 中午1:49
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]希望测试用例可以批量复制 (#682)





 
我有类似的需求，场景大概是这样：之前测过某个A服务，写了一批用例在A/list模块下，然后新有一个B服务准备测试，它也有个很类似A的list模块，所以希望能把A/list模块下的所有用例一次性都复制到B/list模块下，然后我作为维护人再修改每个用例的一些细微差别就行了。
 目前只支持从A/list模块批量移动到B/list，但如果是移动的话A模块下面就没这批用例了，后续可能还是要执行的，所以希望有个批量复制并移动的功能
