### ISSUE TITLE
[BUG]API接口在上传附件并保存后，点击TEST功能，查看部分附件显示为空白，且实际未上传生效

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#6821]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a

**Bug 描述**
API接口在上传附件并保存后，直接打开test页面时，附件数据显示不完整(实际可能为控件未能及时刷新数据，导致test页面的附件均显示为空白)。需要关闭当前API页面，重新进入API页面--TEST模块，才能正确显示，这个时候点击保存为新用例，附件是能正常同步的

**Bug 重现步骤**

1.  打开1个API接口，在请求体中选择file格式，并上传附件后，点击保存；
2.  打开TEST模块，查看API接口保存的附件显示情况；

**期待的正确结果**

2.附件名称显示完整，并且在测试时，查看日志能体现出附件已成功上传生效。

**截图**
![Uploading 06bde042f754ab0a0110297dee5859f.png…]()
![Uploading 6a8a3f3f488b9a5514666e08296cba2.png…]()

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
