### ISSUE TITLE
[BUG] 场景里不能引用比较老的tcp接口case，引入后会导致保存报错

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#6825]
**MeterSphere 版本**
1.13.2

**Bug 描述**

 场景里不能引用比较老的tcp接口case，引入后会导致保存报错

**截图**
![微信图片_20211018182303](https://user-images.githubusercontent.com/8164903/137713543-c9f5b9c7-a443-4090-bb36-6cb5e9759bd4.jpg)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们这边没有复现这个问题，建议升级到较新的的版本试试 ？

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/144563129-d638fdc9-0d04-49f6-a237-f68c9c4c2563.png)
