### ISSUE TITLE
[FEATURE]希望SQL断言可以一次性判定多列变量与对应值是否等于

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#683]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，可以使用‘按列存储’至变量及新增的脚本断言功能来实现该效果
![image](https://user-images.githubusercontent.com/27671436/98193993-5b585c80-1f59-11eb-92c2-f30d13e3b326.png)
