### ISSUE TITLE
[BUG]dubbo接口，配置超时时间不生效

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#6832]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.0-a8cbf128
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  前提：dubbo接口，代码中已设置超时10000ms
2. 在Consumer&Server中配置超时时间10000ms，请求接口，实际仍1s超时

**期待的正确结果**

**正确应该是10s以内都不超时**

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/42166114/137834650-9ff107df-a4f3-4f00-912b-24b7e509fe8b.png)
![image](https://user-images.githubusercontent.com/42166114/137834979-d38f49df-c2da-41dd-8810-29166102ed92.png)

**Comment by zyyfit** [comment]
重复 https://github.com/metersphere/metersphere/issues/6673
