### ISSUE TITLE
[BUG]接口导出后导入，响应内容中的描述信息没有了，同时请求参数中的值没有了

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#6835]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。
您所使用的 MeterSphere 版本是？
版本:   v1.13.1-22e8e5f0
**Bug 描述**
希望接口导入时，能保留参数的描述和参数的参考值，但是目前响应参数导入无法保留参数描述信息，请求参数无法保留参数值，能保留描述信息

简要描述您碰到的问题

**Bug 重现步骤**

1.  在一个已经定义的接口A中，输入请求参数、响应体的参数值和参数描述信息
2. 导出接口A swagger文件，修改URL后，再导入到平台
3. 检查接口响应体的参数值，和参数描述信息
4. 

**期待的正确结果**
3.保留的接口原本的参数值和参数描述信息

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/81950749/137838945-45a2acb4-585f-4190-a1b3-755f18520b82.png)

如果有截图，请附上截图.

**Comment by allinone-1** [comment]
paths中的url，这个修改只是避免重复的URL，模拟一个新的URL而已

**Comment by allinone-1** [comment]
可以使用线上环境进行复现：这个接口已经写好了参数值和描述信息，导出后修改成新的接口，再导入这些参数值和描述信息就会缺失
![image](https://user-images.githubusercontent.com/81950749/137840977-d51ef212-8fb2-4110-bc2d-fed96b0b4326.png)

**Comment by youliyuan-fit2cloud** [comment]
收到，复现...已提交bug系统，下个版本修复~（预计下周四^ ^）

**Comment by zyyfit** [comment]
1.15.0已修复
