### ISSUE TITLE
相同脚本在jmeter中能执行，在ms平台执行报错

### ISSUE THREAD

**Issue by nullapi** [metersphere/metersphere#6838]
**MeterSphere 版本**
13.1

您所使用的 MeterSphere 版本是？

**Bug 描述**
相同脚本在jmeter中能执行，在ms平台执行报错

**Bug 重现步骤**

1.  jmeter中编写的beanshell脚本复制到ms平台执行

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

**Comment by zyyfit** [comment]
您好，方便把报错脚本粘贴一下吗？我们好排查一下问题
