### ISSUE TITLE
[FEATURE] 支持用户环境变量

### ISSUE THREAD

**Issue by dronl** [metersphere/metersphere#6839]
**请描述您的需求或者改进建议.**

目前Metersphere只支持单个api内的自定义变量以及环境级别的全局变量，但在手工测试api的情况下没法满足协同工作的需求，比如说api需要一个session或者是token，如果设成一个环境的全局变量的话，其他用户在运行的时候也只会使用甚至修改这个变量，导致大家的测试冲突。

**请描述你建议的实现方案**
在保留全局变量的情况下，增加用户设置用户环境变量的功能，权限为项目用户的都可以设置。具体设计可以参考windows操作系统的用户变量和系统变量：https://www.itechtics.com/user-vs-system-environment-variables/, 并且在变量名相同的情况下，参考windows的设计，用户变量会覆盖系统变量

**Comment by dronl** [comment]
或者可以使用postman的做法，允许一个变量有init value和current value，每个用户可以设置它的current value

**Comment by luty2018** [comment]
已纳入规划
