### ISSUE TITLE
接口测试场景可以按需导入API对应的case

### ISSUE THREAD

**Issue by swmvp** [metersphere/metersphere#6845]
**请描述您的需求或者改进建议.**
需求：场景有独立API，这些API有多个case，目前无法把API对应的CASE导入到场景中去

**请描述你建议的实现方案**
建议：场景从接口列表导入API时可以选择是否导入对应的case

**Comment by zyyfit** [comment]
您好，没有理解您的意思，目前场景中可以复制API定义本身，也可以复制或者引用API对应的case
![图片](https://user-images.githubusercontent.com/73461316/144170282-164f9b9b-36a7-45d6-b23a-ec2de971218f.png)

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
