### ISSUE TITLE
[FEATURE]希望接口测试列表实现一个光标交互，使光标移动之处可以显示全称

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#685]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/26785348/98076979-4670c000-1eaa-11eb-93db-22b8bd5206c5.png)

**请描述你建议的实现方案**
光标放上去可以显示全部名称

**Comment by pcc426** [comment]
同有需求，否则名字比较长都无法显示全，必须点开才能看到。。。
或者建议把列表导航边栏改成可调节宽度的，这样向右拉伸也能展示出全称。。（当然可能对右半边页面的展示调整会有要求）

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改页面样式，请升级在新版本中尝试下
