### ISSUE TITLE
[FEATURE] 独占或锁定压力机

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6852]
**请描述您的需求或者改进建议.**

目前发压机设置只能按资源池分配（一个资源池对应N台压力机），无法根据目前压力机使用情况自动分配发压资源。
期望：监控资源并标记占用情况，在多个项目/任务选择同一个资源池时，实现自动分配或手动分配压力机，保证所有资源不会相互交叉且利用率达到最高

**请描述你建议的实现方案**

**Comment by xyziven** [comment]
k8s只是其中一个选择，考虑损耗的因素，有很多性能测试、压力测试或负载测试都需要扰动最少的物理机或虚拟机执行。

**Comment by liuruibin** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
