### ISSUE TITLE
[FEATURE]性能缺陷管理

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6854]
**请描述您的需求或者改进建议.**

缺陷管理模块未关联项目和场景，目前只支持关联功能用例，无法对应到性能测试场景

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
