### ISSUE TITLE
[BUG]通过XMIND导入用例时，生成的用例ID与实际XMIND编排的用例顺序不符，为倒序ID，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#6867]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a

**Bug 描述**
通过XMIND导入用例时，生成的用例ID与实际XMIND编排的用例顺序不符，为倒序ID，请修改

**Bug 重现步骤**

1.  通过XMIND编写多条用例的情况下，导入至MS功能用例中，查看新增用例生成的ID排序情况；

**期待的正确结果**

1.安装XMIND中添加的用例顺序依次排序，生成ID

**截图**
<img width="960" alt="72e20307d3093715536fb8710de7607" src="https://user-images.githubusercontent.com/92150453/138066694-a8a3385e-824a-46a4-bd88-4d0130d4fcc2.png">
<img width="960" alt="dfd6ea4be85fcc49cf10a9c3fe34d2e" src="https://user-images.githubusercontent.com/92150453/138066727-5077ac83-1da0-4f0d-971b-39e0dbf77b81.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，我们考虑后续版本优化下~

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4版本已修复
