### ISSUE TITLE
[FEATURE]希望可以自定义设定登录页面失效时间，同时退出时要自动保存编辑的内容，以免内容丢失

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#687]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，可以通过在 /opt/metersphere/conf/metersphere.properties 中增加 session.timeout 配置设定超时时间

**Comment by leosrzheng** [comment]
设置时间计算单位多少 ，秒还是毫秒



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 上午10:57
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]希望可以自定义设定登录页面失效时间，同时退出时要自动保存编辑的内容，以免内容丢失 (#687)





 
你好，可以通过在 /opt/metersphere/conf/metersphere.properties 中增加 session.timeout 配置设定超时时间
