### ISSUE TITLE
[FEATURE]导入后metersphere中用例和模块和顺序是颠倒的--希望能按照Excel的顺序显示模块和用例

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6874]
**请描述您的需求或者改进建议.**
导入后metersphere中用例和模块和顺序是颠倒的--

**请描述你建议的实现方案**
希望能按照Excel的顺序显示模块和用例

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
