### ISSUE TITLE
[FEATURE]用例编辑页面，希望能前后切换用例，现在编辑完一条再编辑下一条的时候需要回到列表页再打开另一条，不太方便

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6875]
**请描述您的需求或者改进建议.**

用例编辑页面，希望能前后切换用例，现在编辑完一条再编辑下一条的时候需要回到列表页再打开另一条，不太方便

**请描述你建议的实现方案**
用例编辑页面，希望能前后切换用例，现在编辑完一条再编辑下一条的时候需要回到列表页再打开另一条，不太方便

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
