### ISSUE TITLE
[FEATURE]用例编辑页面希望展示用例ID，这样在打开多个编辑页签时避免混淆

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6876]
**请描述您的需求或者改进建议.**

用例编辑页面希望展示用例ID，这样在打开多个编辑页签时避免混淆

**请描述你建议的实现方案**
用例编辑页面希望展示用例ID，这样在打开多个编辑页签时避免混淆

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
