### ISSUE TITLE
[FEATURE]导出用例，建议可以勾选，想要的模块进行导出 

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6877]
**请描述您的需求或者改进建议.**

导出用例，建议可以勾选，想要的模块进行导出

**请描述你建议的实现方案**
例如：要回归消息tab和消息两个模块，可以一起勾选这两个模块，一同导出
目前是切换模块，勾选会被取消，想要导出多个模块，需要多次导出

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
