### ISSUE TITLE
[FEATURE]新建用例基础信息中的责任人每一条用例都需要手动填写，希望能够自动关联登录用户，并设置开关控制

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6878]
**请描述您的需求或者改进建议.**

新建用例基础信息中的责任人每一条用例都需要手动填写，希望能够自动关联登录用户，并设置开关控制

**请描述你建议的实现方案**
希望能够自动关联登录用户，并设置开关控制

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，在模板中设置一下默认值。
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/36292514/221806567-7ffaa32a-354e-47e9-9832-abbab82cf852.png">
