### ISSUE TITLE
[FEATURE]插入一条用例的时候，没办法插入在想要的位置

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#6879]
**请描述您的需求或者改进建议.**
插入一条用例的时候，没办法插入在想要的位置
**请描述你建议的实现方案**
例如：用例a和用例b之间，类似于excel直接在某行之间直接插入一行

**Comment by zyyfit** [comment]
现在用例支持排序了，创建完成之后可以对用例进行排序，直接在指定位置插入目前还不支持
