### ISSUE TITLE
[FEATURE]希望可以增加请求头默认值

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#688]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，可以在场景或环境中配置默认的请求头
![image](https://user-images.githubusercontent.com/27671436/98191781-dff4ac00-1f54-11eb-9c50-d875188d4fd6.png)

**Comment by leosrzheng** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 上午10:51
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]希望可以增加请求头默认值 (#688)





 
你好，可以在场景或环境中配置默认的请求头
