### ISSUE TITLE
[FEATURE]希望增加cookice管理器

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#689]
**请描述您的需求或者改进建议.**
类似jmeter里的cookice管理器

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，能否描述下具体的使用场景

**Comment by leosrzheng** [comment]
xxl-job(调度中心)根据cookice来保存登录状态，类似jmeter里面增加了一个cookice管理器来保存这个cookice，后续的接口不需要考虑提取cookice的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 上午10:50
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [FEATURE]希望增加cookice管理器 (#689)





 
你好，能否描述下具体的使用场景

**Comment by wangzhen-fit2cloud** [comment]
你好，我们这边在场景中勾选 ‘共享cookie’ 后就是这样的效果
![image](https://user-images.githubusercontent.com/27671436/98193881-1b917500-1f59-11eb-96f2-f0b8818b50d2.png)
