### ISSUE TITLE
[FEATURE] [性能测试] 显示结果树日志报错

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6897]
**请描述您的需求或者改进建议.**

现在虽然有错误统计，但是看不到请求具体内容，不知道出错的请求是什么原因导致。
在日常测试中，测试人员更关注错误，希望可以显示结果树，更加方便排查错误。

**请描述你建议的实现方案**

**Comment by xyziven** [comment]
https://blog.csdn.net/weixin_39961522/article/details/111857378

解决办法：
在jmeter bin目录中，打开jmeter.properties 修改内容如下：

jmeter.save.saveservice.output_format=xml
jmeter.save.saveservice.response_data=true
jmeter.save.saveservice.samplerData=true
jmeter.save.saveservice.requestHeaders=true
jmeter.save.saveservice.url=true
jmeter.save.saveservice.responseHeaders=true

**Comment by xyziven** [comment]
还有另外一个分享
https://blog.csdn.net/qq_23150755/article/details/112637091

**Comment by liuruibin** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
