### ISSUE TITLE
[BUG]性能压测-上传的jmeter文件有异常，状态一直在starting，无法停止压测，只能删除报告重来

### ISSUE THREAD

**Issue by kevinlee114** [metersphere/metersphere#690]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  上传的jmeter文件异常，点击压测，压测报告处一直显示starting，点击提示【报告正在生成中】无法进入报告界面，停止压测
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
可以再报告列表界面增加停止压测入口，或者starting下可以进入报告界面，可执行停止压测操作。
另外上传的jmeter有异常，jmeter压测没有启动，应该有通知并错误提示才对
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，该问题将在 1.5.0 版本中进行处理
