### ISSUE TITLE
[FEATURE] [性能测试]监控配置可复用

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6900]
**请描述您的需求或者改进建议.**

同一项目下压力机和被测系统通常是一样的，每次测试都要手动填一遍很麻烦。
希望有一种机制可以复用，只要选择相应的机器即可。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by zhangzhaox** [comment]
这个需求是有必要的，添加过的机器 最后能有一段时间内的记忆功能，方便添加
