### ISSUE TITLE
[FEATURE] [性能测试] 图表Y轴显示单位

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6904]
**请描述您的需求或者改进建议.**

希望Y轴显示单位，不然很难读懂图表含义

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，会在v2.9发布。
