### ISSUE TITLE
[FEATURE] [性能测试] X轴显示相对时间

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6905]
**请描述您的需求或者改进建议.**

X轴显示相对时间，以方便对比。
比如多次跑一个测试场景，每次跑5分钟，对比结果时，可以对比跑了2分钟的同一时刻的指标值

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
