### ISSUE TITLE
[FEATURE]测试跟踪>>测试用例：表格用例，新增用例可以直接 “保存并关闭”、用例步骤可以设置分组

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6907]
**请描述您的需求或者改进建议.**
测试跟踪>>测试用例：表格用例，新增用例可以直接 “保存并关闭”、用例步骤可以设置分组

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
