### ISSUE TITLE
[FEATURE]测试计划，功能测试用例，列表中如果失败的用例，增加直接链接至缺陷的按钮；失败的步骤提交缺陷，能否自动将失败的步骤转为缺陷描述

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#6908]
**请描述您的需求或者改进建议.**

[FEATURE]测试计划，功能测试用例，列表中如果失败的用例，增加直接链接至缺陷的按钮

**请描述你建议的实现方案**

**Comment by huangxine** [comment]
失败的步骤提交缺陷，能否自动将失败的步骤转为缺陷描述

**Comment by zyyfit** [comment]
直接链接至缺陷是什么意思呢？我们的测试用例可以关联缺陷

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经规划了，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
