### ISSUE TITLE
[FEATURE] [性能测试]报告自定义: 从多个不同的测试结果中选择不同指标组成最终测试报告

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6911]
**请描述您的需求或者改进建议.**

在实际测试中，一个系统或模块一般由多个测试场景组成，一个测试场景也需要跑很多次。在不断优化之后，得到某一场景关于某一指标或多个指标的最佳结果。
一份最终的性能测试报告需要从多个多轮测试结果中，选择不同的合理指标和最佳结果，组成完整的性能测试报告。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by zhangzhaox** [comment]
一份最终的性能测试报告需要从多个多轮测试结果中（测试场景报告中选择），选择不同的合理指标和最佳结果，组成完整的性能测试报告
