### ISSUE TITLE
[FEATURE] [接口测试] 测试数据跨接口跨场景引用

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#6916]
**请描述您的需求或者改进建议.**

目前的测试数据自动生成，只能在单接口内部使用。每个接口都需要去设置。
希望可以把测试数据生成提取出来做成公共的，各个接口或场景可以引用，方便统一维护测试数据。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复，场景直接引用单接口的case不就可以复用了吗？ 麻烦进一步描述你的需求，谢谢。
