### ISSUE TITLE
[BUG]请求的body里面增加变量显示报错

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#692]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/26785348/98079138-4f639080-1eae-11eb-8e09-b18f3b96cede.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，因为的变量不符合 json 的语法格式，所以会有语法检查的报错，实际上不影响使用

**Comment by leosrzheng** [comment]
好的多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 上午10:53
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "我以为你不一样"<972197622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] [BUG]请求的body里面增加变量显示报错 (#692)





 
你好，因为添加的变量不符合 json 的语法格式，所以会有语法检查的报错，实际上不影响使用
