### ISSUE TITLE
MS无法与swagger定时同步

### ISSUE THREAD

**Issue by liujunpei** [metersphere/metersphere#6925]
版本:   v1.11.2-854acb67

MS无法与swagger定时同步，每次需要手工配置一遍才能更新接口，操作非常繁琐。
对应的swagger接口比较多时，一个一个手工配置更新，将很难用。

**Comment by zyyfit** [comment]
您好，我们有定时同步功能，您是需要什么功能呢？
![image](https://user-images.githubusercontent.com/73461316/140093005-2fabc062-b819-4c2d-819d-a6c84182edb5.png)
