### ISSUE TITLE
[FEATURE]性能测试关联接口自动化场景的时候没有筛选功能

### ISSUE THREAD

**Issue by xusongtao** [metersphere/metersphere#6933]
**请描述您的需求或者改进建议.**

如果接口自动化场景很多的话，需要一条一条的去筛选，会很麻烦

**请描述你建议的实现方案**
建议在性能测试关联接口自动化场景的时候添加筛选功能
![ms_bug](https://user-images.githubusercontent.com/40846859/138252698-a870f25a-a8bb-4aab-b2d1-4f6e99132434.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
