### ISSUE TITLE
[FEATURE]用例增加标签以及搜索功能

### ISSUE THREAD

**Issue by 474241558** [metersphere/metersphere#694]
**请描述您的需求或者改进建议.**
1、建议用例添加标签功能，根据现在用例表单提供的几个属性，很难满足各种对用例管理有特殊要求的情况，例如有些用例我可以标注为“冒烟用例”、“涉及到金额”、“tag1”、“tag2”等等，这样我在进行用例查找等操作时，就很容易根据需要筛选出各种带有特殊标签的用例，仅仅靠优先级、类型等很难满足这类标记需求。
2、可以根据标签搜索，选择多个标签搜索
3、执行计划里同样可以根据标签筛选，并加入到执行列表中
4、执行计划中执行用例时同样可以跟根据标签进行过滤
5、一个用例可以关联多个标签

**请描述你建议的实现方案**
1、增加标签管理功能
2、增加标签与用例关联表
3、删除标签时，若该标签存在关联用例，则不允许删除

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢你的反馈建议，便签功能有考虑过，还请持续关注

**Comment by 474241558** [comment]
用例会添加标签功能么

**Comment by xulinde** [comment]
新版本已经增加了便签功能
![image](https://user-images.githubusercontent.com/64065190/107458332-d5b6ff00-6b8e-11eb-8bf7-84b16f5b37b2.png)
