### ISSUE TITLE
[BUG]Get请求类型的接口测试中，当query参数中带有”|“等特殊字符时，请求失败

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#6949]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.3.2

**Bug 描述**

简要描述您碰到的问题
需要手动调整参数编码，例如把”|“替换为”%7C“再进行请求

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1080" alt="WX20211021-234642@2x" src="https://user-images.githubusercontent.com/18387151/138312410-00780657-c361-4540-9bb4-6fbc4ee706a4.png">

**Comment by zyyfit** [comment]
您好，jmeter也是报这个错误，我们近期应该不会修改jmeter的源码，后期可能会修复这些问题

**Comment by zyyfit** [comment]
您好，jmeter也是报这个错误，我们近期应该不会修改jmeter的源码，后期可能会修复这些问题
