### ISSUE TITLE
[FEATURE]：工作空间下添加成员，希望能够通过组织节点实现批量添加

### ISSUE THREAD

**Issue by Jangbulake** [metersphere/metersphere#695]
目前成员只能一个一个添加  成员多了后很不方便

**Comment by wangzhen-fit2cloud** [comment]
你好，你指的组织节点是什么意思呢

**Comment by Jangbulake** [comment]
就是该用户所在的组织或者工作空间，可以批量把工作空间下的人员一次加进来



---原始邮件---
发件人: "BugKing"<notifications@github.com&gt;
发送时间: 2020年11月5日(周四) 上午10:33
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送: "Jangbulake"<287552138@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [metersphere/metersphere] [FEATURE]：工作空间下添加成员，希望能够通过组织节点实现批量添加 (#695)




 
你好，你指的组织节点是什么意思呢

**Comment by xulinde** [comment]
和#1477重复
