### ISSUE TITLE
[BUG]环境配置的全局变量名称要去重

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#6950]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.3.2

**Bug 描述**
环境配置的全局变量名称要去重

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="991" alt="WX20211021-235312@2x" src="https://user-images.githubusercontent.com/18387151/138313540-f6a56024-8e67-4b1c-81f7-0307cefda297.png">

**Comment by zyyfit** [comment]
目前是这样设计的
