### ISSUE TITLE
[BUG]接口自动化中，场景复制sql脚本，保存时选择A环境，在测试计划中关联该脚本，选择B环境执行时，执行sql没有在B环境下执行SQL语句

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#6955]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
**v1.12.0-a8cbf128**
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.例如我配置如图 test5环境
![image](https://user-images.githubusercontent.com/42166114/138379309-f77378aa-3037-4f7a-98f5-c0dd19eb7c9d.png)

2.  实际在测试计划中我选择stable2环境执行自动化，sql语句部分一定会失败
![image](https://user-images.githubusercontent.com/42166114/138379618-1e2ccd79-b9c3-4c6e-87cb-9d94d4e7f032.png)

3. 我在原自动化脚本中变更环境为stable2后保存，再次执行测试计划，就成功了
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.15.1已修复

**Comment by JennyHuangMZ** [comment]
在1.17的版本上了，问题仍然存在
