### ISSUE TITLE
ms对接jira问题类型能否可以配置多个

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#6958]
**请描述您的需求或者改进建议.**
目前ms对接jira问题类型能否可以配置多个，因为有的缺陷有多个熟悉
![image](https://user-images.githubusercontent.com/30932762/138382399-d7753afd-89e5-440b-b102-46f6f72640d7.png)

**请描述你建议的实现方案**

**Comment by plateauandsp** [comment]
不是的，主要在JIRA里面BUG默认叫缺陷，但是有的时候可以有多个熟悉，比如“问题”，

**Comment by luty2018** [comment]
你的意思是jira有多个项目，有的项目问题类型叫bug，有的项目问题类型叫问题 是这个意思吗？
