### ISSUE TITLE
[BUG]返回的请求体中的body中不支持中文

### ISSUE THREAD

**Issue by chenbingjie-98** [metersphere/metersphere#6959]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.3

**Bug 描述**

返回的请求体中的body中不支持中文
**Bug 重现步骤**

1.  正常提交接口请求
2. 查看返回结果的body为json格式

**期待的正确结果**
中文正常显示

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/63558318/138383130-d443f793-ed66-4f0d-a02b-a26565dbd91e.png)

**Comment by allinone-1** [comment]
> 如果是您的接口返回数据有编码问题的话，可以使用后设置脚本处理一下

@zyyfit  你好，我也遇到这问题了，你们后台是有单独配置的地方吗？ postman返回的数据中就是UTF-8的，但是你们平台返回就是Unicode格式的

**Comment by chenbingjie-98** [comment]
@allinone-1 我是自己加了一个字符转码的方法，自己手动转了，我看了后台默认都是使用的utf-8的，jmeter也是。但就是二进制byte[]字节流经过UTF-8解码出来还是UNICODE。postman和yapi都是正常的

**Comment by zyyfit** [comment]
是的，我们暂时不支持自动转码，暂时先手动处理吧
