### ISSUE TITLE
性能测试无法结束

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#7]
1.16:39提交的性能测试（采用的chrom插件录制的脚本）
![image](https://user-images.githubusercontent.com/30932762/84640231-fcebfc80-af2b-11ea-9ee8-485cbbb10b1f.png)
2.17:16分钟依旧无法结束与无报告
![image](https://user-images.githubusercontent.com/30932762/84640325-1b51f800-af2c-11ea-813d-f10dc06e548b.png)

**Comment by wangzhen-fit2cloud** [comment]
@plateauandsp 如果测试执行节点无法正常连接 Kfaka，JMeter 进程就会一直等待，不会超时。
我们会在后面的版本优化、修复这个问题。

**Comment by liuruibin** [comment]
考虑通过执行前检查Kafka的连通性处理这个问题

**Comment by wangzhen-fit2cloud** [comment]
v1.0.1 版本中已解决
