### ISSUE TITLE
[BUG]不同场景中同名变量相互覆盖

### ISSUE THREAD

**Issue by tonytommy1** [metersphere/metersphere#700]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.3.1-b875
**Bug 描述**
接口测试的时候，每个场景设置了相同名称的参数，点击保存并执行的时候，每个场景的参数都取到了第一个场景的参数

**Bug 重现步骤**
1.  接口测试，新建接口测试，设置自定义变量，比如 name =“abc”，在该测试场景里，添加请求，请求参数里使用 name，并保存
2. 再创建接口测试，新建接口测试，设置自定义变量，比如 name =“cde”，在该测试场景里，添加请求，请求参数里使用 name，并保存
3. 点击保存并执行
4. 在执行结果里，发现第二个测试场景里的name =“abc”

**期待的正确结果**
正常情况下，第二个测试场景里的name =“cde”
**截图**
![image](https://user-images.githubusercontent.com/73465502/98208998-31169700-1f79-11eb-9011-b3122534cdde.png)
![image](https://user-images.githubusercontent.com/73465502/98209095-4ee3fc00-1f79-11eb-8257-962e47c60b97.png)
![image](https://user-images.githubusercontent.com/73465502/98209247-8f437a00-1f79-11eb-847a-85fa3536f776.png)
![image](https://user-images.githubusercontent.com/73465502/98209181-76d35f80-1f79-11eb-9b56-34afad248c37.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这个我们我们计划在 1.6 版本解决，现在可以先通过使用不同变量名的方式规避下

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已提供新版的接口测试，请使用新版本验证下
