### ISSUE TITLE
[BUG]安装metersphere时，docker和metersphere服务启动成功，无法访问网页

### ISSUE THREAD

**Issue by dingxinwen** [metersphere/metersphere#7002]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
 安装metersphere时，docker和metersphere服务启动成功，无法访问网页
**Bug 重现步骤**

1.  安装metersphere时，docker和metersphere服务启动成功，无法访问网页，重新reload会报错
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![B N~@P(S899ZUZSJU5E$U82](https://user-images.githubusercontent.com/67307791/138431873-c6837b96-0c47-47ed-a66e-fa3bf88dc51b.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，使用新版本试试看呢？
