### ISSUE TITLE
[QUESTION]镜像zookeeper拉取失败，其他镜像都正常

### ISSUE THREAD

**Issue by rayxo** [metersphere/metersphere#7009]
**请描述您的问题.**
多次尝试都异常received unexpected HTTP status: 503 Service Unavailable中断
其他镜像拉取成功

docker pull registry.cn-qingdao.aliyuncs.com/metersphere/zookeeper:3
3: Pulling from metersphere/zookeeper
f741ee3cf64f: Already exists
186d31caf60b: Pull complete
8a5d40e02b51: Pull complete
d78c693b516c: Downloading  46.88MB/198MB
065f38452934: Downloading
49ea1b7fe72a: Download complete
a636ca2f17c4: Download complete
5b6ba0489725: Download complete
1aeec4089ee5: Download complete
452ff4f071c3: Download complete
9c674dc3059b: Download complete
b42c72f209e0: Download complete
received unexpected HTTP status: 503 Service Unavailable

**Comment by wangzhen-fit2cloud** [comment]
大部分情况为网络问题，可以换一下网络环境再试一下，或者在可以正常拉取的网络里 save 下镜像再导入到该环境。
