### ISSUE TITLE
[FEATURE]测试跟踪-功能用例-脑图-标签 可以自定义增加

### ISSUE THREAD

**Issue by wangwl1203** [metersphere/metersphere#7012]
**请描述您的需求或者改进建议.**

目前 P0到P3 不够用, 包括后面的几个标签， 建议可以自定义创建标签。 目前p0-p4后台代码很多地方也都是写死的。 

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/73059288/138483205-7ea16eeb-68e2-491e-a70d-6f993a4e9bf2.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。

**Comment by Hyyfit** [comment]
v3.0 已规划，用例等级的标签支持自定义，请关注后续发布说明，谢谢！
