### ISSUE TITLE
[BUG]MAC 命令行安装metersphere后，执行性能测试提示：kafka 不可用，请检查配置

### ISSUE THREAD

**Issue by holysor** [metersphere/metersphere#703]
**Mac 系统**
![image](https://user-images.githubusercontent.com/17400810/98234286-308ef800-1f9b-11eb-9b65-a38d83706fc8.png)

**MeterSphere 版本**
1.4.2

**Bug 重现步骤**
1.执行命令安装：curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh
2.打开web，创建测试脚本，执行性能测试

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/17400810/98233853-8c0cb600-1f9a-11eb-85be-d1e4623e7562.png)

![image](https://user-images.githubusercontent.com/17400810/98233799-7dbe9a00-1f9a-11eb-9ecd-ca55bfc4c82b.png)

**Comment by xulinde** [comment]
您好，参照文档：https://metersphere.io/docs/faq/#qkafka
