### ISSUE TITLE
[BUG]1.11.2版本通过容器单机部署的环境，压力测试时nodeContraller生成的容器并没有和其他的容器在同一个network里，请问下这个配置如何修改

### ISSUE THREAD

**Issue by cverdela** [metersphere/metersphere#7033]
**MeterSphere 版本**
>v1.11.2

您所使用的 MeterSphere 版本是？

**Bug 描述**

1.11.2版本通过容器单机部署的环境，压力测试时nodeContraller生成的容器并没有和其他的容器在同一个network里，请问下这个配置如何修改

**Bug 重现步骤**

1.  单机部署
2. 压力测试

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by allinone-1** [comment]
> metersphere 部署的时候各个组件在同一个network下，性能测试创建出来的容器是单独的并不是docker-compose管理。这个新创建的容器可以通过宿主机的地址和端口访问到其他组件，也可以通过宿主机所在的dns配置来实现网络连接

请教下在ms-server配置的DNS，容器重启后就不在，这个可以再哪儿配置，让他永久生效？

**Comment by zyyfit** [comment]
> > metersphere 部署的时候各个组件在同一个network下，性能测试创建出来的容器是单独的并不是docker-compose管理。这个新创建的容器可以通过宿主机的地址和端口访问到其他组件，也可以通过宿主机所在的dns配置来实现网络连接
> 
> 请教下在ms-server配置的DNS，容器重启后就不在，这个可以再哪儿配置，让他永久生效？

可以通过docker挂在volume把hosts挂到容器里
