### ISSUE TITLE
[BUG]大并发下，测试无法结束

### ISSUE THREAD

**Issue by rzsp8552** [metersphere/metersphere#704]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题
高并发下（3000vu，6台node-controller），执行超过时间，但是测试不会结束。
data-streaming一直报截图的信息

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/20183045/98250732-c97d3d80-1fb2-11eb-99e0-5bf25db86719.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问最终结束了吗？
