### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by wencyGit** [metersphere/metersphere#7040]
- 接口测试 -> 接口定义中有定时同步接口文档的操作，我想有时候指定同步文档的时间未到，需要手动请求同步

![image](https://user-images.githubusercontent.com/21151964/138628454-69554c97-a618-494a-8258-549530e4718e.png)

**Comment by zyyfit** [comment]
您是想swagger定时同步任务增加手动执行功能吗？

**Comment by wencyGit** [comment]
@zyyfit 是的，主动去拉取文档，以为定时任务肯定是在指定时间内才去拉取文档，我修改了，不可能要等到定时任务触发

**Comment by wencyGit** [comment]
这项目团队真牛比，接近两个月才有人回复
