### ISSUE TITLE
[FEATURE]缺陷管理模块，没有筛选统计的功能；

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7058]
**请描述您的需求或者改进建议.**

缺陷管理模块，没有筛选统计的功能；
1）比如，统计某个人在某段时间内提交了多少某个优先级的bug，并且生成相应的图表，便于汇报。
2）比如，查询某个人名下处于某个状态下的jira，便于集中关闭处理

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
