### ISSUE TITLE
[BUG] swagger接口导入，接口定义中备注信息都没有被导入到Metersphere系统中。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7060]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.13.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  比如swagger备注里的信息如下图格式，此备注信息无法导入到Metersphere接口里。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![超境汽车1](https://user-images.githubusercontent.com/78218624/138641676-95e4861e-f226-428a-a487-cf1c52f9d51b.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.15.0已修复
