### ISSUE TITLE
[FEATURE]测试用例关联jira中的需求：下拉列表中带出来的是该项目下所有的需求，应该加筛选，筛选出本次迭代的需求，历史需求可以过滤掉

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7062]
**请描述您的需求或者改进建议.**
测试用例关联jira中的需求：下拉列表中带出来的是该项目下所有的需求，应该加筛选，筛选出本次迭代的需求，历史需求可以过滤掉

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
