### ISSUE TITLE
[FEATURE]脑图方式执行测试计划时，验证testcase时发现缺陷后没有提交的入口，需要切换到列表才可以提bug

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7064]
**请描述您的需求或者改进建议.**

脑图方式执行测试计划时，验证testcase时发现缺陷后没有提交的入口，需要切换到列表才可以提bug

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，点击右键可以添加缺陷。
