### ISSUE TITLE
[BUG]Jenkins插件控制台打印的报告链接，没有带报告的后缀id， 点进去不是报告页面

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7065]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/30038088/138642960-68406495-3464-4c09-9b14-ff7b1e758673.png)

**期待的正确结果**
![image](https://user-images.githubusercontent.com/30038088/138642893-0e8c7c42-3074-40c4-b0d3-d6b40b5363d6.png)

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
最新版已修复
