### ISSUE TITLE
[BUG]Jenkins 插件版本 没有按照 release 版本 更新

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7069]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

![5311635141804_ pic](https://user-images.githubusercontent.com/30038088/138645954-e569d011-dbac-48d5-b6fb-72cc587ef133.jpg)

![5321635141813_ pic](https://user-images.githubusercontent.com/30038088/138645957-223fe610-1187-4302-976e-57d291f4ec9b.jpg)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.14.0已修复
