### ISSUE TITLE
[BUG]测试用例高级搜索条件筛选存在bug

### ISSUE THREAD

**Issue by lakelee88** [metersphere/metersphere#7084]
您所使用的 MeterSphere 版本是？
 v1.10.11-lts-c237e249
**Bug 描述**

简要描述您碰到的问题
测试用例界面高级搜索，选择筛选条件，创建人实际筛选的是责任人，执行人没有筛选结果
**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/93119462/138655695-31149cc4-9e27-4c8d-bcc2-1d245f8b588b.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
