### ISSUE TITLE
[FEATURE]  测试跟踪测试用例优化意见：1.“用例步骤可以设置分组”：类似禅道里测试用例步骤 2.测试用例提供公共用例集，并且引用此用例时，可以进行参数化设置，类似：alm/QC—调用时参数化设置。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7089]
**请描述您的需求或者改进建议.**

1.“用例步骤可以设置分组”：类似禅道里测试用例步骤
2.测试用例提供公共用例集，并且引用此用例时，可以进行参数化设置，类似：alm/QC—调用时参数化设置。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
公共用例下个版本会加，用例步骤子步骤先进行一下需求调研
