### ISSUE TITLE
[BUG]V1.12升级V1.13.2后，测试计划，列表中 “执行次数” 列一直显示为0，没有计数

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7094]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  V1.12升级V1.13.2后，测试计划，列表中 “执行次数” 列一直显示为0，没有计数
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.14.0没有复现这个问题，另外，您的测试计划里如果没有接口或者性能用例的话，执行次数是不会增加的

**Comment by huangxine** [comment]
在1.12版本里此计划是由执行次数的，系统从1.12升级到1.13后，此计划的执行次数为零。同一个计划，在不同版本里，执行次数不一样。

**Comment by zyyfit** [comment]
最新版已修复
