### ISSUE TITLE
[BUG]删除与测试计划中测试用例关联的接口/性能测试后，测试用例中关联的测试显示 uuid

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [metersphere/metersphere#71]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.2
**Bug 描述**
删除与测试计划中测试用例关联的接口/性能测试后，测试用例中关联的测试显示 uuid

**Bug 重现步骤**
1.  创建一个接口测试
2. 在测试用例管理中创建与上述接口测试关联的测试用例
3. 删除步骤1中创建的接口测试
4. 查看步骤2中创建的测试用例

**期待的正确结果**
接口测试被测试用例关联时，无法进行删除，提示需要先解除关联

**Comment by AgAngle** [comment]
v1.0.3版本已修复
