### ISSUE TITLE
[FEATURE]测试计划执行后，建议可以按照测试结果进行排序，并且最好可以提供对测试用例的编辑功能。

### ISSUE THREAD

**Issue by 1067511899** [metersphere/metersphere#7103]
**请描述您的需求或者改进建议.**
测试计划执行后（这里特指接口测试），建议可以按照测试结果进行排序。否在当测试用例过多的时候，只能一页页翻找 执行结果为 “未通过”的 测试用例。（测试跟踪-》测试计划-》接口测试用例）
另外，当发现测试用例 未通过的时候，只能进入 接口测试-》接口定义-》case 那里，找到要编辑的测试用例进行编辑。非常不方便。

**请描述你建议的实现方案**
参考ID、用例等级、用例名称、创建人 等进行排序的方法，在“执行结果” 旁边 也添加一个排序按钮。当点击这个按钮的时候，可以把“未通过”的测试用例显示在最前列。
每一行测试用例，目前只有“执行”和“取消用例关联”两个按钮，建议增加“编辑”按钮。

谢谢

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研
