### ISSUE TITLE
[FEATURE]接口场景全屏编辑时，右侧编辑页面的信息展示空间太小

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#7114]
**请描述您的需求或者改进建议.**
接口场景全屏编辑时，右侧编辑页面的信息展示空间太小

**请描述你建议的实现方案**
截图中的拖动栏应该可以向左拖动，或者拖动栏做成直接收起和展开
<img width="1007" alt="WX20211025-220736@2x" src="https://user-images.githubusercontent.com/18387151/138711414-aa47510a-0553-470d-99e2-7721e5c19cd0.png">

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
