### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#712]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？ 1.4.0

**Bug 描述**
在请求中引用mock变量，但发现变量名没有替换为值

**Bug 重现步骤**
1.  在请求参数处配置一个参数为随机Mock的日期：@date
2. 发起请求
3. 观察到实际请求时参数传的还是“@date”变量名，而没替换为Mock值

**期待的正确结果**
实际请求时@date传mock值，如2010-09-10

**截图**
![bug-mock数据无替换](https://user-images.githubusercontent.com/11419548/98332827-66cf8480-203a-11eb-83ca-36013698902a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请升级到最新版本进行验证。
