### ISSUE TITLE
[BUG]测试计划中关联的性能测试用例，配压力配置未自动带入，功能实现不合理，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7120]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a

**Bug 描述**
测试计划中关联的性能测试用例，配压力配置未自动带入，功能实现不合理，请修改

**Bug 重现步骤**

1.  在测试计划中关联性能测试用例，查看对应性能测试用例的默认配置；

**期待的正确结果**
1.  与原性能测试的配置保持一致；

**截图**
<img width="960" alt="915a1733daa8799ada70a84b353affe" src="https://user-images.githubusercontent.com/92150453/138801815-7d4035f0-1c37-4532-8407-54c1ed8751a3.png">
<img width="960" alt="f9462d21c92573e7d7daee91d34e06c" src="https://user-images.githubusercontent.com/92150453/138801827-6234d18a-f540-4aff-9e58-5e1287fb9160.png">

**Comment by youliyuan-fit2cloud** [comment]
v1.14以上版本已修复该问题，建议升级一下吧
