### ISSUE TITLE
[BUG]1.13.2 接口定义中配置的环境配置 ，接口自动化 的环境配置 与系统设置-项目-环境配置 数据不同享，要分别创建保存。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#7123]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.13.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**在接口定义中配置的环境配置 ，接口自动化 的环境配置 与系统设置-项目-环境配置 数据不同享，要分别创建保存。

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您是说在接口模块中添加了环境信息，项目管理模块没有显示吗？
![image](https://user-images.githubusercontent.com/73461316/139576473-717a0e5d-9c68-44c7-961c-ed196b17623f.png)

**Comment by billguo** [comment]
已知问题了。。环境配置没有进行引用相同的源数据。。修改任何地方都不能统一修改。
