### ISSUE TITLE
[BUG]接口导入不能使用之前的环境地址，需要重新创建环境地址，才能使用

### ISSUE THREAD

**Issue by YellowFly2** [metersphere/metersphere#7130]
**MeterSphere 版本**
>v1.13.2

**Bug 描述**

接口导入后，之前环境模块地址无法使用，需要重新创建运行环境地址才能使用

**Comment by zyyfit** [comment]
您好，如果是文件导入的，目前是这样设计的，
如果是场景引用的，引用其他项目的场景是可以选择其他项目的环境的
