### ISSUE TITLE
[BUG]接口自动化测试场景中，1个场景有多TCP请求，执行过程中一直转圈

### ISSUE THREAD

**Issue by chencherry123** [metersphere/metersphere#7133]
**MeterSphere 版本**
 v1.10.11-lts-c237e249

**Bug 描述**
接口自动化测试场景中，1个场景有多TCP请求，执行过程中一直转圈

**Bug 重现步骤**

1.  接口自动化测试场景，1个场景录入多个自定义的TCP请求，每个请求端口号不同
2.  录入保存后点击执行

**实际结果**
1、执行过程中一直转圈，谷歌浏览器F12显示一直往后台服务发送重复请求。
2、转圈过程中查看被测试的TCP服务端接收的数据，除了第1个TCP请求实际成功外，其余均未成功未接收到数据

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题呢，是否能发一下log 分析一下 ？
