### ISSUE TITLE
metersphere和jira集成问题类型和需求类型问题

### ISSUE THREAD

**Issue by hchangfa** [metersphere/metersphere#7139]
**请描述您的需求或者改进建议.**

metersphere和jira集成问题类型和需求类型只能填写一个类型，希望可以填写多个类型，比方说：问题类型：bug，BUG，缺陷

**请描述你建议的实现方案**
问题类型和需求类型可以填写多个。

**Comment by luty2018** [comment]
非常抱歉现在才回复。
对接第三方平台已经插件化了， 如果有这方面需求的话可以参考 https://github.com/metersphere/metersphere-platform-plugin 进行改造。
