### ISSUE TITLE
[BUG]并发执行时一直转圈圈

### ISSUE THREAD

**Issue by tonytommy1** [metersphere/metersphere#714]
**MeterSphere 版本**
 v1.3.1-b875

**Bug 描述**
并发执行的时候，场景也不多，3个场景，页面一直转圈圈，很久很久都没结果
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
尽快出结果
**截图**
![image](https://user-images.githubusercontent.com/73465502/98352903-95108c80-2059-11eb-8cb2-26fba5b952bb.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请升级到最新版本进行验证
