### ISSUE TITLE
[BUG]API文档查阅，选的某个API文档后，在进行上下滚动时，出现某两个文档间滚动跳转失败的现象，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7140]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a

**Bug 描述**
API文档查阅，选的某个API文档后，在进行上下滚动时，出现某两个文档间滚动跳转失败的现象，请修改

**Bug 重现步骤**

1.  在API文档页面，点击查看文档6后，向上滚动至文档5，查看操作情况；

**期待的正确结果**

1.  正确滚动到API文档5的查看页面；

**截图**
![image](https://user-images.githubusercontent.com/92150453/138821896-cc04ea2a-7655-4555-9e1d-7be7523f52a5.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
