### ISSUE TITLE
[BUG]测试计划创建定时任务，通过CRON表达式生成器生成之后页面报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#7141]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

V1.13.2

**Bug 描述**

简要描述您碰到的问题
测试计划创建定时任务，通过CRON表达式生成器生成之后页面报错

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/32027713/138824624-271ec0bb-3b32-4f6e-82b2-a5e62afa7b5c.png)

![image](https://user-images.githubusercontent.com/32027713/138824496-3c3ae715-0f01-4782-bf32-2bc03d41de42.png)

cron表达式手动改为：0 0 8 ? * *  之后就可以保存成功了

**Comment by zyyfit** [comment]
你这个表达式有点问题。。。从8点开始每24个小时执行一次不就是每天的8点开始吗，我们看看能不能优化一下这里吧

**Comment by zyyfit** [comment]
1.14.1已修复
