### ISSUE TITLE
[BUG]缺陷状态国际化

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#715]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.4.3
**Bug 描述**
简要描述您碰到的问题
测试报告中，缺陷列表-缺陷“状态”字段未转义
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/54024064/98352892-917d0580-2059-11eb-8821-58b2d4446310.png)

**Comment by xulinde** [comment]
已知问题，下个版本会修改
