### ISSUE TITLE
[BUG][BUG]v1.13.2测试跟踪-用例评审-截止时间-此刻无法选中

### ISSUE THREAD

**Issue by shancuser** [metersphere/metersphere#7150]
**Bug 描述**

1、在测试跟踪，新建用例评审，勾选截止时间，选中此刻，该评审无法报错，并提示不能早于当前时间
2、该功能设计场景、用途是什么？

**Bug 重现步骤**

![1dbee88bc190fb5a9629e8dd5157e83](https://user-images.githubusercontent.com/86365242/138834701-9a3e5adb-5fcd-4431-ab2b-30122e3ad633.png)

**Comment by zyyfit** [comment]
是提示 截止时间不能早于当前时间吗？截止时间的话是这样设计的
![image](https://user-images.githubusercontent.com/73461316/139576835-fb54e191-a6a3-4787-82a1-2b277c450f4c.png)
