### ISSUE TITLE
[BUG]使用最新的master分支的代码，无法正常进行构建

### ISSUE THREAD

**Issue by lingsoul** [metersphere/metersphere#7190]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

master分支最新版，分支id：d13d33b ，分支提交记录：wangzhen-fit2cloud Merge branch 'dev'

问题：使用这个分支的代码，无法正常进行构建，运行npm run build 后，报错信息如图

![image](https://user-images.githubusercontent.com/22099083/139005629-b80a5a05-433f-4e3a-b61e-3abd6efd94ce.png)

**Comment by zyyfit** [comment]
您好，建议您使用最新release版本进行安装部署，master分支可能存在问题
