### ISSUE TITLE
[QUESTION]请问前置和后置脚本中使用Python的话可以使用哪些内置变量或函数？ 

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7202]
**请描述您的问题.**
前置脚本如果是使用Python编写的话，有哪些内置函数可以调用？ 有么有例子？
例如：如何获取环境变量，或设置全局变量，或修改请求头、响应等
同时控制也没有看到Python相关的脚本的输出，请问有没有什么指导？

**Comment by allinone-1** [comment]
@wangzhen-fit2cloud  请问能解答一下吗

**Comment by wangzhen-fit2cloud** [comment]
在右侧有提供一些代码模板
![image](https://user-images.githubusercontent.com/27671436/145330591-09ce666c-d5cd-47b5-bac1-2baea9f84b3c.png)
同时可以使用 log.info() 方法向控制台打印输出。
