### ISSUE TITLE
[BUG]lts版本，集成禅道模块未放开请求方式功能，导致默认GET请求的禅道用户无法对接MS，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7231]
**MeterSphere 版本**
版本： ALL lts版本 

**Bug 描述**
lts版本，集成禅道模块未放开请求方式功能，导致默认GET请求的禅道用户无法对接MS，请修改

**截图**
<img width="860" alt="8e37e73e02bcfceb44496a1f3a97735" src="https://user-images.githubusercontent.com/92150453/139046171-859baba2-4775-472b-9955-23f4a3073519.png">
<img width="960" alt="75eb82fc9401c7826b94c9e420287d4" src="https://user-images.githubusercontent.com/92150453/139046250-62275243-ce32-4eee-bb06-886a01c400e7.png">

**Comment by zyyfit** [comment]
感谢反馈，原则上lts版本是不新增功能只修复bug的，我们先内部讨论一下这个问题

**Comment by youliyuan-fit2cloud** [comment]
已修复，待发布最新LTS版本

**Comment by youliyuan-fit2cloud** [comment]
最新版本v1.20.0-lts中已修复
