### ISSUE TITLE
[BUG]jsonp格式的返回数据会导致接口一直在测试中，不会自动化停止

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7240]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  jsonp格式的返回数据会导致接口一直在测试中，不会自动化停止
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

能够正常返回并结束测试

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by fit2-zhao** [comment]
@allinone-1  请描述一下你的接口，如果方便可以贴出来看一下，我们模拟了jsonp 格式的接口 并未复现这个问题。

**Comment by allinone-1** [comment]
数据返回（用postman没有这个问题）：
jQuery360042644146160121243_1635757109178({"message": "\u7cfb\u7edf\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5", "extras": {}, "errcode": 503, "success": 0})

**Comment by zyyfit** [comment]
> @fit2-zhao 数据返回（用postman没有这个问题）： jQuery360042644146160121243_1635757109178({"message": "\u7cfb\u7edf\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5", "extras": {}, "errcode": 503, "success": 0})

您好，我们模拟了一下，没有复现这个问题，方便把您接口的返回值给我们吗？
![图片](https://user-images.githubusercontent.com/73461316/143562211-26b83f72-ec79-4bbd-ae3c-1f32a71624f2.png)

**Comment by allinone-1** [comment]
> > @fit2-zhao 数据返回（用postman没有这个问题）： jQuery360042644146160121243_1635757109178({"message": "\u7cfb\u7edf\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5", "extras": {}, "errcode": 503, "success": 0})
> 
> 您好，我们模拟了一下，没有复现这个问题，方便把您接口的返回值给我们吗？ ![图片](https://user-images.githubusercontent.com/73461316/143562211-26b83f72-ec79-4bbd-ae3c-1f32a71624f2.png)

jQuery360042644146160121243_1635757109178({"message": "\u7cfb\u7edf\u7e41\u5fd9\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5", "extras": {}, "errcode": 503, "success": 0})

**Comment by zyyfit** [comment]
还是没有复现这个问题，如果你那边还有问题的话可以在企业微信交流群里问问，我们的同事也可以更方便的帮你排查一下问题
