### ISSUE TITLE
导入swagger的路径，metersphere没带出“API”，而eolinker带出了“API”

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#725]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.0

**Bug 描述**
简要描述您碰到的问题
导入swagger的路径，metersphere没带出“API”，而eolinker带出了“API”

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
导入swagger的路径，metersphere带出“API”

**截图**
如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/74084897/98431309-17975b80-20ef-11eb-9d0f-7d1acb5afeb6.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.6.0 版本提供接口定义中增加了 REST参数的支持
