### ISSUE TITLE
接口测试用例转到性能测试，目前只进行第一组场景的性能测试

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#726]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.0

**Bug 描述**
简要描述您碰到的问题

接口测试用例转到性能测试，目前只进行第一组场景的性能测试

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

接口测试用例转到性能测试，实现当前JMX所有场景的性能测试
因为jmeter做接口性能测试时，业务要涉及多个线程组，而不是单线程组

**截图**
如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/74084897/98431372-b3c16280-20ef-11eb-8238-7cc1ebf5956a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，由于设置了多个线程组顺序执行，在转换为性能测试时，多个线程组也会是顺序执行的状态。
