### ISSUE TITLE
有部分测试报告导不出，而且一直处于转圈状态

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#727]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.0

**Bug 描述**
简要描述您碰到的问题

有部分测试报告导不出，而且一直处于转圈状态

**Bug 重现步骤**
1.  接口测试完成后，导出测试报告
2. 性能测试完成后，导出测试报告
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
所有测试报告能导出

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，请求数大概多少个
