### ISSUE TITLE
[BUG]jsonpath匹配到多个数据时，想要输出全部的值，jmeter中可以输入-1，但是metersphere不支持

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7270]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  jsonpath匹配到多个数据时，想要输出全部的值，jmeter中可以输入-1，但是metersphere不支持
2. 
3. 
4. 

**期待的正确结果**

能够使用变量输出匹配到的所有值

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
提取多个变量的话不需要输入-1，勾选匹配多条就可以了
![image](https://user-images.githubusercontent.com/73461316/139578145-deaf3788-4e1e-4099-86ea-602d674dd5cd.png)

**Comment by allinone-1** [comment]
@zyyfit  我需要的是不是匹配多条，是希望用一个变量输出匹配到的多条数据，而不是每次只能输出一条数据，如${name_1}、${name_2}这种，我需要输出name这个变量匹配到的所有数据

**Comment by ryanrain2016** [comment]
@allinone-1 我最近也遇到这个问题，再加个后置处理器可以解决：
整数的：
```
import java.util.ArrayList;

varName = "varName"

varList = new ArrayList();
int cnt = Integer.parseInt(vars.get(varName+"_matchNr"));

for (int i=1; i <= cnt;i++) {
    varName = varName+"_"+i;
    var = vars.get(varName);
    varList.add(var);
}
items = String.join(", ", varList);
items = "[" + items + "]";
vars.put(varName, items);
```
字符串的：
```
import java.util.ArrayList;

varName = "varName"

varList = new ArrayList();
int cnt = Integer.parseInt(vars.get(varName+"_matchNr"));

for (int i=1; i <= cnt;i++) {
    varNameN = varName+"_"+i;
    var = vars.get(varNameN);
    varList.add("\"" + var + "\"");
}
items = String.join(", ", varList);
items = "[" + items + "]";
vars.put(varName, items);
```
