### ISSUE TITLE
[BUG]场景接口中上传的文件，在过了一段时间之后（经历过一两次版本升级），在执行时报错找不到文件。

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7273]
**MeterSphere 版本**

> v1.13.2-6ac3675a

**Bug 描述**

> 场景接口中上传的文件，在过了一段时间之后（经历过一两次版本升级），在执行时报错找不到文件。

_刚才又遇到一次，没有更新过版本就出现了我找不到文件的错误。_

**Bug 重现步骤**

1.  维护场景接口用例，上传测试用文件：申报数据校验错误数据.xlsx。
2. 过了一两周，其中经历过一次或两次版本升级（1.13.0、1.13.1）。
3. 通过Jenkins触发测试计划，执行场景测试用例。

**期待的正确结果**

> 使用上传文件进行接口测试。

**截图**

![image](https://user-images.githubusercontent.com/34698664/139194956-996f797d-80c3-472d-84b3-299795a893ec.png)

**Comment by Saco93** [comment]
> 楼上这个问题我遇到
> 楼主其实和你升级没有多大关系
> 你设置测试计划，把上传接口拉进去，设置5分钟运行一次，你自然会看到失败的测试计划
知道原因了，由于Helm上没有对数据文件路径做持久化导致每次遇到容器重启就会丢失文件

**Comment by zyyfit** [comment]
感谢反馈，我们看能不能优化一下这里

**Comment by zyyfit** [comment]
> > 楼上这个问题我遇到
> > 楼主其实和你升级没有多大关系
> > 你设置测试计划，把上传接口拉进去，设置5分钟运行一次，你自然会看到失败的测试计划
> 
> 知道原因了，由于Helm上没有对数据文件路径做持久化导致每次遇到容器重启就会丢失文件

后面的 helm 增加了对这个目录的持久化处理，升级下 helm chart 或者手动加一下卷就好了
