### ISSUE TITLE
[BUG]前置或后置SQL中，如果操作的数据表中数据较大，测试执行卡死。

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7280]
**MeterSphere 版本**

> v1.13.2-6ac3675a

**Bug 描述**

> 前置或后置SQL中，如果操作的数据表中数据较大，测试执行卡死。

**Bug 重现步骤**

1.  维护单接口测试用例，包括前置SQL和后置SQL，且SQL操作的数据表中数据较大。
2. 未单独维护每个SQL的数据源，而是在环境中维护了一个唯一的数据源。

> _如果给每个SQL单独配置数据源，则不会执行卡死。_

3. 执行单接口测试用例。

**期待的正确结果**

> SQL执行成功。

**截图**

（无）

**Comment by zyyfit** [comment]
是不是数据库卡住了呢？

**Comment by Saco93** [comment]
> 是不是数据库卡住了呢？

单个SQL步骤中如果不指定数据库的话，有时候就会出现这个情况，不是必然的，目前遇到的是在SQL执行比较久的时候会有这种情况；
如果给每个SQL步骤指定数据库的话，同一个执行比较久的SQL，就可以成功执行。

**我们这边没有给每个SQL步骤指定数据库是因为这样在切换环境执行的时候，需要每个SQL单独去切换，非常不方便，也无法做到自动化。**

**Comment by youliyuan-fit2cloud** [comment]
目前还没太好的办法，后续版本我们尽量优化下这里~
