### ISSUE TITLE
[BUG]断言脚本里，终止测试的代码放在if判断内会报错

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#7289]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

1.13.2

**Bug 描述**

断言脚本里，终止测试的代码放在if判断内会报错，放在判断外可以正常运行

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/88763608/139215400-3480c324-572a-4cc6-8bf2-0bd586640cf1.png)
![image](https://user-images.githubusercontent.com/88763608/139215482-ccf7ac25-0d93-429e-9600-e09db1265cfb.png)
![Uploading image.png…]()

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，看起来是这行脚本没加分号，加个分号试试
