### ISSUE TITLE
接口的定时功能有问题，目前的现象是，执行5次，但前四次都是失败的，提示：Non HTTP response code: java.net.SocketException；

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#729]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.0

**Bug 描述**
简要描述您碰到的问题

接口的定时功能有问题，目前的现象是，执行5次，但前四次都是失败的，提示：Non HTTP response code: java.net.SocketException；

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

接口的定时功能加以完善

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请提供下完整的日志信息
