### ISSUE TITLE
版本升级目前较大的问题

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#731]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.0

**Bug 描述**
简要描述您碰到的问题

版本升级目前较大的问题
1.4.1升级到1.4.2需要sed参数位置
1.4.2升级到1.4.3启用服务容易出错，而且重启docker服务可能就好了

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

完善升级功能

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
在新版本中已修改相关脚本
