### ISSUE TITLE
目前metersphere未实现，但又有市场需求的建议

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#732]
**请描述您的需求或者改进建议.**

建议类问题：
1、	接口之间的数据关联方式，弹框选择上一接口返回的结果值；
2、	目前针对组织和工作空间不能转换，建议能转换；
3、	建议支持MQTT、Websocket协议；
4、	增加需求管理，并与研发任务和故事进行关联，可参考Jira；
5、	增加服务端监控，比如kube-prometheus；
6、	增加APP在线测试，并产生测试报告、错误日志等；
7、	性能测试能查看执行测试的测试用例集及测试用例，用于用户查看具体的性能测试参数；

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续我们会调研一下，请持续关注～
