### ISSUE TITLE
[BUG]mock功能设置通用返回失效

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#7324]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.14.0
**Bug 描述**
接口配置返回信息，未配置mock，调用mock地址，返回404

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
能够正常返回配置的返回信息

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前还没有这个功能，后续版本会考虑增加的

**Comment by wszbc** [comment]
> 您好，目前还没有这个功能，后续版本会考虑增加的

你们内部对功能理解都不同频
![image](https://user-images.githubusercontent.com/40912823/139612272-417c89e1-d14f-40da-a875-4cdb536da538.png)

**Comment by zyyfit** [comment]
现在去掉了这个功能，实际请求里的信息只要包含mock就可以返回，
比如说如果你的入参有多个参数，你在mock里不填订单号，在实际请求里填了，也会返回mock信息的
