### ISSUE TITLE
[BUG]内存溢出问题。

### ISSUE THREAD

**Issue by chenbingjie-98** [metersphere/metersphere#7329]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.10.3

**Bug 描述**
在接口自动化的场景下，运行多个场景，产生内存溢出
简要描述您碰到的问题

**Bug 重现步骤**

1.  批量运行多个测试场景（多一点，多个用户最好）

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/63558318/139395984-3c9ad83a-3e82-4cea-867b-231423dee82e.png)

**Comment by fit2-zhao** [comment]
@chenbingjie-98  请问目前你的环境配置是什么样的，有多少个场景，每个场景的请求数量是多少，是否有个别请求返回内容过大。

**Comment by chenbingjie-98** [comment]
@fit2-zhao 目前场景大约500多吗，每个场景平均大约20个左右吧，多个有30几个，返回内容有长有段。环境配置：堆空间配置了1G。垃圾回收期1.8默认。PS+PO

**Comment by youliyuan-fit2cloud** [comment]
在 v1.14.4以上版本我们优化这里，建议升级下吧

**Comment by chenbingjie-98** [comment]
> 在 v1.14.4以上版本我们优化这里，建议升级下吧

老铁，14.4关于这块做了哪些优化啊，我去排过这些问题，想知道你们做了什么优化

**Comment by fit2-zhao** [comment]
@chenbingjie-98 执行相关优化大致 四点 如下：
1 优化了定时任务执行 修改代码处理逻辑，针对需要更新配置信息的定时任务，采用初始化一个新定时任务的方式。
2 针对node节点执行优化 修改代码处理逻辑，每次执行任务时根据 server 传递的参数重新初始化 kafka。
3 执行过程中批量入库优化 修改代码处理逻辑，将涉及的相关代码，统一处理，关闭数据库连接。释放资源。
4 执行线程优化 及时释放执行队列。
