### ISSUE TITLE
[BUG]关联测试用例ID排序按钮不生效

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#7338]
**MeterSphere 版本**
>v1.14.0
**Bug 描述**
测试跟踪》测试计划》关联测试用例
一般关联用例时会根据id顺序进行，但是点击id按钮，并不能实现排序功能，反而很混论

**截图**

![第二页](https://user-images.githubusercontent.com/88697123/139406291-7c0ef0c6-e979-4418-96d5-29514cfb62ab.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
