### ISSUE TITLE
[BUG]保存用例报错

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#7340]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？V1.14.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪
2. 新增用例
3. 保存

报错
{ "timestamp": "2021-10-29T08:25:53.313+00:00", "status": 500, "error": "Internal Server Error", "path": "/test/case/add" }
![保存报错](https://user-images.githubusercontent.com/88697123/139407837-989c95be-75ad-40c7-be74-cf99ac809e87.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，不过我看您的用例等级是空的，请问是怎么操作导致用例等级为空了呢？
