### ISSUE TITLE
[FEATURE]测试计划模块希望增加按照sprint冲刺分类的功能

### ISSUE THREAD

**Issue by zyyfit** [metersphere/metersphere#7344]
**请描述您的需求或者改进建议.**

测试计划模块希望增加按照sprint冲刺分类的功能，目前所有的sprint对应的冒烟测试计划、系统测试计划、回归测试计划都混在一起，数据多了就不好区分哪些是某一个冲刺中的测试计划（缺陷管理也存在同样的问题，实际中需要统计某个sprint中的缺陷数）

**请描述你建议的实现方案**

**Comment by Andrew-Oyang** [comment]
这个单为什么CLOSE了呢？

**Comment by luty2018** [comment]
不好意思，现在才回复你的issue，同事手误点了close，已经重现打开。
目前的版本支持自定义测试阶段，也可以先进行简单区分。
你提的这个需求会在我们v3.0版本中实现，测试计划可以拆分为多个阶段，每个测试计划会有独立的缺陷统计。

**Comment by Hyyfit** [comment]
v3.0 已规划，请关注后续发布说明，谢谢！
