### ISSUE TITLE
[BUG]同一个JMX脚本中，如果有多个线程组，有关闭的线程组的话，执行性能测试报“压力配置参数不能为空!”

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7346]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**

简要描述您碰到的问题
同一个JMX脚本中，如果有多个线程组，有关闭的线程组的话，执行性能测试报“压力配置参数不能为空!”
**Bug 重现步骤**

1.  准备一个包含多个线程组的JMX脚本
2. 创建性能测试任务，上传性能测试脚本
3. 关闭一个线程组
4. 设置压力机参数，然后点击 执行，报 “压力配置参数不能为空!”

**期待的正确结果**

![image](https://user-images.githubusercontent.com/30038088/139409924-30e5b7d5-3caa-46a8-a917-6505b62ec613.png)

![image](https://user-images.githubusercontent.com/30038088/139409878-18ce6191-8cf4-4e42-95b0-5339d10fc6fa.png)

正确情况下应该是什么样的？
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，后面小版本修复

**Comment by zyyfit** [comment]
已修复
