### ISSUE TITLE
[FEATURE]希望在接口自动化下的场景内新增选择某些步骤进行批量删除，批量关闭及打开步骤等批量操作的功能

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#7348]
**请描述您的需求或者改进建议.**

希望在接口自动化下的场景内新增选择某些步骤进行批量删除，批量关闭及打开步骤等批量操作的功能

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
