### ISSUE TITLE
[FEATURE]接口设置的 域名地址 应该作为一个参数项可以独立设置并且支持变量方式引用${xx}

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#7355]
**请描述您的需求或者改进建议.**

因环境设置中的域名条件匹配不能满足实际Cas、Oauth对接应用是多域名多路径的需求

**请描述你建议的实现方案**
接口设置的 域名地址 应该作为一个参数项可以独立设置并且支持变量方式引用${xx}

**Comment by zyyfit** [comment]
您好，我们目前支持使用变量的，您是希望怎么使用呢？
![图片](https://user-images.githubusercontent.com/73461316/144195782-512ac0c8-2ec4-45f2-a2f3-590257fb76c9.png)


![图片](https://user-images.githubusercontent.com/73461316/144195740-c37e37ed-2aa1-49ca-a895-500fe1d1fe3e.png)

**Comment by lgs3137** [comment]
好的，可惜http、https应该不能包含在变量里面吧？

**Comment by zyyfit** [comment]
> 好的，可惜http、https应该不能包含在变量里面吧？

是的，http、https是在环境里选的
