### ISSUE TITLE
[BUG]jmeter5.4.1 导入的用例中，如果正则提取器中包含从 响应头 中提取时，用例中提取器 response headers 无法自动选中，且选中后点击 更新接口 也保存无效，每次调用接口还得手动选中

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#7356]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

v1.14.0

**Bug 描述**

jmeter5.4.1 导入的用例中，如果正则提取器中包含从 响应头 中提取时，用例中提取器  respon headers 无法自动选中，且选中后点击 更新接口 也保存无效，每次调用接口还得手动选中

**Bug 重现步骤**

jmeter5.4.1 导入的用例中，如果正则提取器中包含从 响应头 中提取时，用例中提取器  respon headers 无法自动选中，且选中后点击 更新接口 也保存无效，每次调用接口还得手动选中

**期待的正确结果**

正确情况下应该是什么样的？

1、正确加载 response headers

2、选中 response headers 后 更新接口 能正确保存成功

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，第一个问题复现了，更新接口后无法保存这个问题没复现，更新用例后要保存用例，不是保存接口

**Comment by lgs3137** [comment]
的确，无法保存的问题，是先要 保存用例 后再 更新接口 就能保存了

**Comment by zyyfit** [comment]
1.14.2已修复
