### ISSUE TITLE
[BUG] 长密码在登录时被截断

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#736]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是v1.4.3-b1050

**Bug 描述**
修改密码提示8-30长度，设置了一个长度23的密码，退出重新登录，输入密码被截断，登录密码的长度限制实际只有20；

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，感谢您的反馈，我们这边复现下

**Comment by xulinde** [comment]
您好，问题复现。本月26号发布的v1.5.0版本会修复，您到时候升级到最新版本就可以了。
