### ISSUE TITLE
[BUG]手动创建接口，出现重复数据

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7361]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ 1.13.2版本

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 手动创建接口，出现重复数据
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/139610792-f8c98805-0c54-47fc-9ec3-a9ec3be6b20f.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能描述一下详细操作步骤吗
