### ISSUE TITLE
[FEATURE] 自定义字段,不能用于高级搜索可筛选条件

### ISSUE THREAD

**Issue by honglianglv0917** [metersphere/metersphere#7366]
**请描述您的需求或者改进建议.**
用例模版添加自定义字段,但是在测试用例选择,高级筛选不能使用该字段的条件

**请描述你建议的实现方案**
高级筛选的字段可以包括自定义

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/6029
