### ISSUE TITLE
[BUG]跨項目引用場景，查看引用展示為空

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#7373]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
    版本:   v1.12.3

**Bug 描述**
    跨項目引用場景，查看引用展示為空

**期待的正确结果**
  展示引用該項目的場景
**截图**
![image](https://user-images.githubusercontent.com/37204403/139629233-638d1aca-e22c-4338-bcdb-7eddff1a4018.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
