### ISSUE TITLE
[BUG]线程数一致增加，没有回收

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#7375]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，能明确一下您说的问题吗？

**Comment by youliyuan-fit2cloud** [comment]
由于长时间没有反馈详细的复现信息，关闭该问题
