### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#739]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4.0
**Bug 描述**
简要描述您碰到的问题
环境配置中添加数据库配置，sql请求引用环境，无法找到添加的数据源
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中没有复现该问题，请升级新版本验证下，如果问题依然存在，请重新打开该 issue
