### ISSUE TITLE
测试报告-自定义模块里插入了表格，建议在报告中展示表格线，优化界面展示

### ISSUE THREAD

**Issue by lanye1990** [metersphere/metersphere#74]
**请描述您的需求或者改进建议.**
测试报告-自定义模块，建议使文本的编辑更加丰富一些，当前加入了表格后，表格线在生产的测试报告中没有展示，使模块的展示显得很怪异。

**请描述你建议的实现方案**
自定义模块的编辑加入富文本模块，使文本编辑更加丰富化

**Comment by youliyuan-fit2cloud** [comment]
该问题已修改，感谢您的反馈，请持续关注～
