### ISSUE TITLE
[BUG]接口测试报告批量删除是展示数量与选中数量不一致

### ISSUE THREAD

**Issue by zhangjiya** [metersphere/metersphere#740]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4。0
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1. 选中 每页展示10条接口报告，全选，点击批量删除
2. 批量删除按钮显示选中了20条

**期待的正确结果**
正确情况下应该是什么样的？实际选中数量与展示的数值应该一致

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33714230/98641011-0b690380-2366-11eb-927e-dc344d06f953.png)

**Comment by xulinde** [comment]
您好，本月26号发布的v1.5.0版本会修复该问题，您到时候直接升级到最新版本就可以了。
