### ISSUE TITLE
[BUG] 请求头配置多个不同值的Cookie，执行测试后发现请求头信息中没有自动合并多个Cookie的值

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#7410]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

v1.14.0

**Bug 描述**

![image](https://user-images.githubusercontent.com/1278141/139664441-1198f079-c181-4665-b245-ff36a73f7dc0.png)

请求头配置多个不同值的Cookie，执行测试后发现请求头信息中没有自动合并多个Cookie的值，而是只取第一个，这个应该是个BUG(Jmeter正常的)

**Bug 重现步骤**

请求头配置多个不同值的Cookie，然后执行测试

**期待的正确结果**

请求头应该自动合并多个Cookie的值

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化一下

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4版本已修复
