### ISSUE TITLE
条件控制器中添加一个等待控制器，导致条件控制器中每个接口执行都需等待设置的时间才执行

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#7411]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**
接口自动化场景，条件控制器批量接口中添加一个等待控制器，导致条件控制器中每一个接口执行都需等待设置的时间才能执行，在等待控制器之前的接口也需等待设置的时间后才执行；
简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个场景
2. 添加一个条件控制器，条件可设置为1=1
3. 在条件控制器中添加多个接口
4. 在条件控制器中添加一个等待控制器
5. 执行场景

**期待的正确结果**

正确情况下应该是什么样的？
只有等待控制器后面的第一个接口才需要等待设定的时间再执行，其它接口均无需等待
**截图**
<img width="1282" alt="截屏2021-11-01 下午8 59 20" src="https://user-images.githubusercontent.com/34637801/139675420-c06b4152-dc1e-4525-9fea-c524dc54076d.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by zyyfit** [comment]
您好，等待控制器放在条件控制器下面，和接口请求同级的话，是会每个接口都执行等待的，如果想要单独一个接口等待，需要放在这个接口下面
