### ISSUE TITLE
[BUG]将接口自动化用例添加到测试计划中，并设置定时任务后，接口自动化的测试报告中显示用例一直为running状态

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7412]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
版本:   v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  将接口自动化用例添加到测试计划中，并设置定时任务后，接口自动化的测试报告中显示用例一直未running状态
2. 
3. 
4. 

**期待的正确结果**
1.在测试跟踪目录下查看测试报告是已经结束了的，但是接口测试中的测试报告中测试计划的用例一直为running状态

正确情况下应该是什么样的？

**截图**
接口测试中的测试报告：
2021-11-02 08:00:00
定时任务
Running

测试跟踪中的报告：
2021-11-02 08:00:00
定时任务
Completed

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问，请问是必现的吗？场景中有什么特别的步骤吗？

**Comment by allinone-1** [comment]
> 你好，没有复现的问题，请问是必现的吗？

非必现

**Comment by youliyuan-fit2cloud** [comment]
建议到较新版本吧，我们有修改一波测试计划的定时任务的问题~
