### ISSUE TITLE
[FEATURE]导入xmind前每条用例前都要加序号ID，用例多的情况下不好维护，可否按照实际用例的顺序导入，去掉加序号这步操作，可节省很多时间。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7415]
**请描述您的需求或者改进建议.**

导入xmind前每条用例前都要加序号ID，用例多的情况下不好维护，可否按照实际用例的顺序导入，去掉加序号这步操作，可节省很多时间。

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
您好，不开启用例自定义ID功能的时候，xmind不需要填写ID
