### ISSUE TITLE
[BUG]接口测试：API上传的附件，切换到TEST之后不显示

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#7417]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**
接口测试：api上传的附件，切换到test之后不显示。
简要描述您碰到的问题

**Bug 重现步骤**

1.  
<img width="866" alt="1" src="https://user-images.githubusercontent.com/71361375/139774904-09716c5b-2623-405a-9f7f-4cf1a68778c4.png">
<img width="699" alt="2" src="https://user-images.githubusercontent.com/71361375/139774914-15b2a85e-6ad9-4cfa-af11-e97d9bce5cf6.png">
<img width="690" alt="3" src="https://user-images.githubusercontent.com/71361375/139774915-778fe963-02fd-422b-a2b1-7b484d88aaf3.png">

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.14.0没有复现这个问题，建议您升级到最新版试试
