### ISSUE TITLE
[BUG] Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.3-ms11

### ISSUE THREAD

**Issue by hakeedra** [metersphere/metersphere#742]
**MeterSphere 版本**
v1.3.1

**Bug 描述**
性能测试里面点击执行，会提示 
Image Not Found: registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.3-ms11
遇到这个问题去对应服务器上面 pull这个镜像，然后再执行可以成功；但是成功之后过段时间再执行又会报同样的错误

**期待的正确结果**
pull之后下次应该不会出现这个问题了

**Comment by wangzhen-fit2cloud** [comment]
你好，出现该问题时请在资源池对应节点上检查下镜像是否真的存在，如果确认镜像存在同时还提示该错误，请重新打开该 issue
