### ISSUE TITLE
接口自动化场景的等待控制器需放入引用的接口

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#7421]
**请描述您的需求或者改进建议.**
接口自动化场景中，等待控制器只能放入复制或者自定义的接口中，因此导致引用的接口无法做单接口的等待控制

**请描述你建议的实现方案**
让引用的接口可以添加等待控制器

**Comment by xulinde** [comment]
最新版本v1.20.4已支持，建议升级
