### ISSUE TITLE
[FEATURE]功能用例关联的其他平台的缺陷能点击缺陷跳转到缺陷所在平台

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#7431]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
![1635835687150](https://user-images.githubusercontent.com/36387811/139799089-40d8fbed-ed92-4f92-aacf-35e8a9537088.jpg)

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
对接第三方平台已经插件化了， 如果有这方面需求的话可以参考 https://github.com/metersphere/metersphere-platform-plugin 进行改造。
