### ISSUE TITLE
[BUG]1.14.0 测试报告导出为空白。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#7433]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.14.0

**Bug 描述**

简要描述您碰到的问题 测试跟踪-测试计划，查看测试报告-右上角导出，导出的文件打开，就是空白的。

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
