### ISSUE TITLE
[BUG]做接口测试时候，from-data请求体，添加字段类型file，上传文件。请求报错Broken pipe

### ISSUE THREAD

**Issue by caozhumin** [metersphere/metersphere#7434]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1-b4

**Bug 描述**
POST类型接口请求，请求体为from-data，添加字段类型为file，并且上传xxx.mp4文件（文件大小26M），系统报错

**Bug 重现步骤**

1.  新增一个POST接口，并且请求头信息为
 Accept-Encoding：gzip, deflate,br
Content-Type：multipart/form-data
 Accept：*/*
2.请求体格式选form-data
其中一个字段类型选择file，并添加一个xxx.mp4文件 
其他接口字段信息正常填写，选择好测试环境，send请求，系统报错：java.net.SocketException: Broken pipe (Write failed)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![1](https://user-images.githubusercontent.com/23714204/139813014-5ba30c87-b134-443b-817c-bdf982a473a2.png)
![2](https://user-images.githubusercontent.com/23714204/139813021-0b3b5ba3-226f-404b-9291-cae258fe76cf.png)

**Comment by caozhumin** [comment]
您好，删掉content-type也是不行，你们自己验证一下看看是不是跟我一样的情
![33](https://user-images.githubusercontent.com/23714204/140008116-fbc67d6e-f1ac-4731-8d7c-af7af8d613df.png)

**Comment by zyyfit** [comment]
收到，下个版本修复

**Comment by zyyfit** [comment]
您好，我们后来测试发现没有复现这个问题了，您在最新版再试试，或者看看jmeter是不是正常的
