### ISSUE TITLE
[FEATURE]无法对接使用自签名证书的 OIDC 服务器

### ISSUE THREAD

**Issue by wisonic-s** [metersphere/metersphere#7439]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
1.13.2
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  无法对接使用自签名证书的 OIDC 服务器，不使用 SSL/TLS 则可以正常对接，在 ms-server 容器中用 keytool 将证书添加信任之后可以正常使用 SSL/TLS。

**期待的正确结果**

可以正常对接使用自签名证书的 OIDC 服务器

**Comment by luty2018** [comment]
非常抱歉现在才回复。
由于您的版本比较旧，建议升级到最新版本使用。
如果问题依然存在可以重新打开issue或新创建issue。
