### ISSUE TITLE
场景设置的全局变量，使用时未生效

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#744]
**MeterSphere 版本**
1.4.3

**Bug 描述**
场景设置全局变量，单接口调式使用时未生效

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
单接口调式使用时生效

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/33744331/98762073-ce5a4b00-2411-11eb-9f16-6a9201c5d337.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，未复现该问题，请检查下场景中的自定义变量是否是勾选启用状态

**Comment by AshuaiNe** [comment]
我理解错误，使用方法了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BugKing"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 下午3:23
收件人: "metersphere/metersphere"<metersphere@noreply.github.com&gt;; 
抄送: "2818820548"<2818820548@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [metersphere/metersphere] 场景设置的全局变量，使用时未生效 (#744)





 
你好，未复现该问题，请检查下场景中的自定义变量是否是勾选启用状态
