### ISSUE TITLE
[BUG]环境配置了域名，执行场景的时候，控制台会有报错(unKnowHostException)，但是不影响正常执行 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7440]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**
环境配置了域名以百度为例（www.baidu.com），执行场景的时候，控制台会有报错，但是不影响正常执行 
简要描述您碰到的问题

**Bug 重现步骤**

1.  环境配置域名
2. 执行场景，控制台报错
![image](https://user-images.githubusercontent.com/30038088/139831237-e93cc674-e9ce-42e7-93dc-be1de0b2ec36.png)

3.场景执行结果 正常
**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
@Dyc2333

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
