### ISSUE TITLE
[FEATURE]接口的域名能不能像jemter一样放开由自己定义，做多角色用户的组合场景时，由于URL不一样就很难实现

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7443]
**请描述您的需求或者改进建议.**

1.接口自动化中的接口请求URL建议放开，可以由用户自己修改定义

为什么有这个需求：
1.我们有比较多的场景是需要切换角色完成的，切换角色时用的是不同的域名或者不同端口，这样在一套环境中就无法满足
，如果用你们提供的环境配置中按模块去匹配URL，那有的接口是多个角色都会有的，相当于同一个接口我还需要复制多个到不同角色模块下，不方便，也会造成URL的冗余。

**请描述你建议的实现方案**
1.参考jmeter放开

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。建议你可以使用自定义请求，自定义请求是可以自主输入域名的。
