### ISSUE TITLE
[BUG]如果json里面存在boolean类型使用json-schema会导致对应boolean类型转换为string

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#7448]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2-b3

**Bug 描述**

如果json里面存在boolean类型使用json-schema会导致对应boolean类型转换为string

**Bug 重现步骤**

1.  先传入json字符串
2. 点击json-schema切换按钮
![image](https://user-images.githubusercontent.com/31123121/139867582-1b8415de-8166-4e8d-9278-0eaa428032d2.png)
3. 从模板切换到预览页面，查看内容，发现对应字段由boolean转换为string
![image](https://user-images.githubusercontent.com/31123121/139867811-ec85a8b8-6d2f-4a83-9086-578cb0a6ea43.png)
4. 请求接口，报错
![image](https://user-images.githubusercontent.com/31123121/139868007-a1edf178-530a-4ec8-bf82-8047944a188d.png)

**期待的正确结果**

不应该转换，应该保持boolean的实际类型

**截图**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.14.1版本已修复
