### ISSUE TITLE
测试计划报告提供高级搜索的功能

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#7449]
**请描述您的需求或者改进建议.**
由于想批量删除测试计划的报告，但想保留最近七天的报告，希望能提供如接口测试报告的高级搜索功能，能按照日期进行筛选

**请描述你建议的实现方案**
按照接口测试报告那样提供高级搜索的功能，这样就可以按照日期筛选出超出最近7天的报告，进性批量删除

**Comment by zyyfit** [comment]
1.15.0已增加
