### ISSUE TITLE
性能测试用户数无法按照多个线程组分组

### ISSUE THREAD

**Issue by popppo321** [metersphere/metersphere#745]
![image](https://user-images.githubusercontent.com/9740714/98762116-e5993880-2411-11eb-9199-29bb5b292e23.png)

压力场景配置中，如存在多个线程组，无法按模型比例分配用户，如8:2 比例分配到2个线程组

**Comment by wangzhen-fit2cloud** [comment]
你好，分线程组配置并发功能将在 1.5 版本中提供
