### ISSUE TITLE
[BUG]performance test添加超过10个资源文件时保存报错

### ISSUE THREAD

**Issue by eddiexu-crypto** [metersphere/metersphere#7452]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题
performance test 添加超过10个资源文件时保存报错: 文件个数超出限制！ 看了代码是前端写死了文件个数限制为10个，无法通过配置修改。

**Bug 重现步骤**

1.  上传超过10个资源文件（如csv)
2. 添加到压测场景的资源文件列表 
3. 保存
4. 

**期待的正确结果**

正确情况下应该是什么样的？
保存成功
**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
是有限制了，最多上传十个文件

**Comment by eddiexu-crypto** [comment]
10个不够呀，复杂一点的压测场景支持不了。
