### ISSUE TITLE
[FEATURE]每个接口测试用例几乎都会定义变量，当接口用例不断增加时，想用一个变量，需要先去接口里找到他，时间长了就忘记哪个接口，找起来特别挺费劲的。咱们有计划把接口测试用例里定义的变量做统一展示管理吗，不同接口需要其他接口定义的变量，只需点开页面勾勾选选就行

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7455]
**请描述您的需求或者改进建议.**
接口测试>>>每个接口测试用例几乎都会定义变量，当接口用例不断增加时，想用一个变量，需要先去接口里找到他，时间长了就忘记哪个接口，找起来特别挺费劲的。咱们有计划把接口测试用例里定义的变量做统一展示管理吗，不同接口需要其他接口定义的变量，只需点开页面勾勾选选就行

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。我们有这个计划， 但是还没有比较好的解决方案。
