### ISSUE TITLE
[FEATURE]接口测试报告中能否加入提交缺陷或者标签之类的功能

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#7464]
**请描述您的需求或者改进建议.**

接口测试报告不能自己添加信息，如造成接口错误的原因等等

**请描述你建议的实现方案**
接口测试报告中能否加入提交缺陷或者标签之类的功能

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
