### ISSUE TITLE
接口测试时点击保存并执行后，再次点击接口测试，再进入对应测试，再次点击保存并执行，测试报告一直running

### ISSUE THREAD

**Issue by AshuaiNe** [metersphere/metersphere#747]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
14.3

**Bug 描述**
接口测试时点击保存并执行后，再次点击接口测试，再进入对应测试，再次点击保存并执行，测试报告一直running

**Bug 重现步骤**
1.  点击保存并执行
2. 再次点击接口测试
3. 再进入对应测试
4. 再次点击保存并执行
5、测试报告一直running

**期待的正确结果**
正常执行完毕测试报告

**截图**
![image](https://user-images.githubusercontent.com/33744331/98779456-da083a80-242e-11eb-8cf4-011c443cef41.png)

**Comment by liuruibin** [comment]
这个问题我在1.4.3的环境里没有复现，现在的实现是当同一个测试在执行的时候，再次点击运行会跳到上测执行的报告页面，也就是说，同时只能执行一次
