### ISSUE TITLE
[BUG]执行快速安装脚本，脚本运行报错

### ISSUE THREAD

**Issue by XFriday** [metersphere/metersphere#7472]
**Bug 描述**
运行报错：
sh: 5: Syntax error: "(" unexpected

**Bug 重现步骤**

1.   sudo curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh

**Comment by youliyuan-fit2cloud** [comment]
你好，这个 错误太少了，请提供详细的log

**Comment by XFriday** [comment]
使用Bash就可以运行了，sh会报错，你可以试试

**Comment by youliyuan-fit2cloud** [comment]
测试了两台机器没复现，应该你的系统问题哈，
