### ISSUE TITLE
[BUG]进入测试计划页面报错

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#748]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4.3
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  进入测试跟踪的测试计划页面
2. 
3. 
4. 
![image](https://user-images.githubusercontent.com/53041390/98792213-1fcdfe80-2441-11eb-810a-7d95bdc3cbc7.png)

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
您好，我们这边没复现，请详细描述下必现步骤
