### ISSUE TITLE
[BUG]MeterSphere使用jenkins执行测试计划有测试案例一直处于running状态，并且直到超时，返回上次案例的执行状态

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#7489]
**MeterSphere 版本**
>metersphere版本:1.14.0-b2
>metersphere-jenkins-plugin版本:1.14

您所使用的 MeterSphere 版本是？
>metersphere版本:1.14.0-b2
>metersphere-jenkins-plugin版本:1.14
**Bug 描述**

简要描述您碰到的问题
[BUG]MeterSphere使用jenkins执行测试计划有测试案例一直处于running状态，并且直到超时，返回上次案例的执行状态，然后错误日志如下：
![image](https://user-images.githubusercontent.com/31123121/140248396-0f83b3d3-75ab-48ab-b45a-6df499dac14d.png)

**Bug 重现步骤**

1.  使用jenkins调用测试计划，测试计划的案例尽量多一点（50条以上），所有案例执行时间最好超过30s
2. 执行中查看testPlan/info日志,发现有些测试案例一直处于running状态，并且在6分钟以后自动变成FAILD状态
![image](https://user-images.githubusercontent.com/31123121/140248994-b8bd1a67-d77e-4598-b705-1d1798038251.png)
![image](https://user-images.githubusercontent.com/31123121/140249074-5f450c1b-e056-47aa-9f95-7551ba1d62fa.png)

**期待的正确结果**
期望能够正常执行测试案例，并且返回正确的测试结果

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，问下 测试计划的案例尽量多一点（50条以上）？是仅包括性能测试还是接口和场景用例都包括超过50条？

**Comment by Svlang** [comment]
你好，是接口和场景的测试用例，没有包括性能的测试用例


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]MeterSphere使用jenkins执行测试计划有测试案例一直处于running状态，并且直到超时，返回上次案例的执行状态 (Issue #7489)





 
你好，问下 测试计划的案例尽量多一点（50条以上）？是仅包括性能测试还是接口和场景用例都包括超过50条？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
