### ISSUE TITLE
[BUG]使用jenkins-plugin插件，用pipeline项目的生成对应的pipeline的语法，执行测试计划，有错误，缺少参数

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#7493]
**MeterSphere 版本**
>v1.14.0-b2
>jenkins-plugin版本：1.14

您所使用的 MeterSphere 版本是？
>v1.14.0-b2

**Bug 描述**

简要描述您碰到的问题
[BUG]使用jenkins-plugin插件，用pipeline项目的生成对应的pipeline的语法，执行测试计划，有错误，缺少参数
![image](https://user-images.githubusercontent.com/31123121/140255217-3a5f18d3-ab08-4da6-92ed-7eda7c22794d.png)

**Bug 重现步骤**

1.  通过流水线语法工具生成对应的流水线语法
![image](https://user-images.githubusercontent.com/31123121/140255575-979a6e76-7d16-45ae-9e3e-8e976712d0ea.png)

2.复制流水线语法到对应的流水线工程下面
![image](https://user-images.githubusercontent.com/31123121/140255672-2a9de6ab-e098-42f5-b62c-7bfd41d462c4.png)
 
3.执行l流水线工程，报错，查看错误信息
![image](https://user-images.githubusercontent.com/31123121/140255729-f3f31ced-1d7f-47e4-a55d-8949e4b631bc.png)

**期待的正确结果**
参数应该完善，不应该提示对应错误，不然会导致需要去猜测需要传递什么参数

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前这个插件对声明式 pipeline 语法支持有问题。可以先用脚本式 pipeline ，或者在声明式 pipeline 中增加 script 步骤。
参考如下
```
pipeline {
  stages {
    stage("xxx") {
      steps{
        script {
          metersphere xxxxxxx
        }
      }
    }
```

**Comment by Svlang** [comment]
> 你好，目前这个插件对声明式 pipeline 语法支持有问题。可以先用脚本式 pipeline ，或者在声明式 pipeline 中增加 script 步骤。 参考如下
> 
> ```
> pipeline {
>   stages {
>     stage("xxx") {
>       steps{
>         script {
>           metersphere xxxxxxx
>         }
>       }
>     }
> ```

你好，我只是meterphere加了括号，为了方便查看，流水线语法是没有问题，你可以自己尝试一下在说，因为我一直用，我如果把这4个参数给的值哪怕是null，都可以执行的，现在不是语法的问题，报错很明显了，是metersphere-plugin的插件抛出的异常，你可以最上面的错误截图，谢谢
![image](https://user-images.githubusercontent.com/31123121/140264232-fb1b3716-2239-417e-bf9e-511d21a82dea.png)
申明肯定是没有问题的，我自己本身就一种用jenkins的pipeline，项目也很多，所以不会写错的，一直都在用，所以不会有低级错误
![image](https://user-images.githubusercontent.com/31123121/140264387-00e57966-d73a-4809-ba70-8b8505a76a27.png)
我用在这个项目都可以执行，唯一就是testId:null,logger:null,testCaseNodeId:null这样就可以
![image](https://user-images.githubusercontent.com/31123121/140264506-5851caa5-2542-4b8f-9e34-f05db0c42e46.png)
![image](https://user-images.githubusercontent.com/31123121/140264919-98005528-b2b4-4f93-9faa-8c1f81b72d48.png)
但是这本身是一个问题，所以我还是希望解决，而不是我随便给一个，而且我也不知道这样对不对

**Comment by Svlang** [comment]
> 你好，目前这个插件对声明式 pipeline 语法支持有问题。可以先用脚本式 pipeline ，或者在声明式 pipeline 中增加 script 步骤。 参考如下
> 
> ```
> pipeline {
>   stages {
>     stage("xxx") {
>       steps{
>         script {
>           metersphere xxxxxxx
>         }
>       }
>     }
> ```

您好，我这还有就是按照你的想法生成的样子，没有做格式变化的错误结果，效果其实是一样的
![image](https://user-images.githubusercontent.com/31123121/140266308-655fd688-1f79-4642-bb00-900b9066d267.png)

**Comment by linl12138** [comment]
1.14.0版本后取消了组织概念，所以会缺少orgid参数，需要把jenkins插件版本更新不低于1.14版本

**Comment by Svlang** [comment]
> 1.14.0版本后取消了组织概念，所以会缺少orgid参数，需要把jenkins插件版本更新不低于1.14版本

您好，我已经升级到了最新版本的1.15了，依然存在参数空的情况，还存在下面三个参数
logger
testCaseNodeId
testId

所以我上面的截图的表述不仅仅是orgid参数

错误日志：
![image](https://user-images.githubusercontent.com/31123121/144824040-f7803003-cbbb-4f5d-a0ce-deb95ad6ca88.png)

Jenkins plugin版本号：
![image](https://user-images.githubusercontent.com/31123121/144823661-e00a83e1-92af-4c04-9bb0-39a21a8c5b11.png)

pipeline生成的语句：
![image](https://user-images.githubusercontent.com/31123121/144824606-f92b467a-f1dc-4bad-bb95-9dbbc4dbce9b.png)

**Comment by xulinde** [comment]
使用最新版本插件未复现该问题，建议您升级下
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/64065190/170932543-398691b1-df02-49eb-93e0-51c29318f84f.png">
