### ISSUE TITLE
[FEATURE]逻辑处理器中，目前只有if逻辑判断，不能满足当前的业务需求。希望加上循环等多种判断。

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#750]
**请描述您的需求或者改进建议.**
逻辑处理器中，目前只有if逻辑判断，不能满足当前的业务需求。希望加上循环等多种判断。
![image](https://user-images.githubusercontent.com/53041390/98792670-cca87b80-2441-11eb-9031-a03605cf3152.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，目前正在对接口测试相关功能进行重构改写，预计 1.6 版本完成，请持续关注

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 版本已增加循环控制器
