### ISSUE TITLE
[BUG]缺陷管理 关联 禅道的缺陷删除报错

### ISSUE THREAD

**Issue by cnbizhh** [metersphere/metersphere#7500]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14.0-42d99ed2
**Bug 描述**
缺陷管理 关联 禅道的缺陷删除报错

**Bug 重现步骤**
1.  测试跟踪
2.  缺陷管理
3.  删除缺陷
4. 

**期待的正确结果**

正常删除

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/7309951/140269161-95de8edd-2c3c-40cd-bf37-ca892b5a3040.png)
![image](https://user-images.githubusercontent.com/7309951/140269200-55cb1bee-8d39-4787-b93b-b8481381bf19.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，该问题已修复，请关注后续版本
