### ISSUE TITLE
[FEATURE] xml格式响应体中增加格式化选项

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#7507]
**请描述您的需求或者改进建议.**
xml格式响应体中增加格式化选项。
响应报文体中，现在有text json xml等，在以前版本中如果时xml报文，当切换到xml时报文会自动格式化。
现在已经不会再格式化，建议重新增加该功能。

**Comment by zyyfit** [comment]
请问您使用的是什么版本呢？我这里没有复现（最新版1.14.0）
![图片](https://user-images.githubusercontent.com/73461316/140496041-8ff321bb-a714-4be9-aefd-deedd4a62256.png)

**Comment by tangw1257** [comment]
> 请问您使用的是什么版本呢？我这里没有复现（最新版1.14.0） ![图片](https://user-images.githubusercontent.com/73461316/140496041-8ff321bb-a714-4be9-aefd-deedd4a62256.png)
最新版本1.14.1

**Comment by zyyfit** [comment]
最新版1.15.0已发布，您可以升级到最新版看看，如果还不行的话，方便把您的操作录屏给我们吗？

**Comment by tangw1257** [comment]
> 最新版1.15.0已发布，您可以升级到最新版看看，如果还不行的话，方便把您的操作录屏给我们吗？

这个是1.15.0的
https://user-images.githubusercontent.com/8164903/143551423-fed91212-5764-4283-9e79-7b6b8aaa60eb.mp4

**Comment by zyyfit** [comment]
你这个的返回格式是xml吗？我还是没复现，要不你在交流群里问问工作人员吧
