### ISSUE TITLE
[BUG]返回值无法展示openapi3.0.3

### ISSUE THREAD

**Issue by fanpocha** [metersphere/metersphere#7508]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
官网测试网站

**Bug 描述**

简要描述您碰到的问题：

导入Swagger3("openapi": "3.0.3",)的json文件 ，返回值无法展示

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.15.0版本已优化
