### ISSUE TITLE
[FEATURE]测试计划页面或者运行中的定时任务

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#7514]
**请描述您的需求或者改进建议.**
能不能在测试计划页面或者运行中的定时任务不用点进去直接看到关联了多少用例
![image](https://user-images.githubusercontent.com/85992665/140282125-3c5f0a5c-5094-47d7-873b-6f9a2feeb376.png)

或者执行中的定时任务可以直接点进去看到多少用例。
![image](https://user-images.githubusercontent.com/85992665/140282092-fc3f302d-2fb6-4741-ad40-9ba51251899b.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
