### ISSUE TITLE
[BUG]环境配置的全局前置脚本或者HTTP请求，用代码模版 生成的 “报文头添加长度” 代码块，执行报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7525]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**
1.环境配置的全局前置脚本或者HTTP请求，代码模版 生成的 “报文头添加长度” 代码块，执行报错，（该代码块只对TCP协议生效）
2.环境配置的全局前置脚本 涉及到 接口相关的 代码块提示应该隐藏掉。
3.HTTP协议的前后置脚本，涉及到 TCP 相关的代码块 也应该 隐藏掉。
简要描述您碰到的问题

**Bug 重现步骤**

1.
![image](https://user-images.githubusercontent.com/30038088/140296045-10b7a73e-2ba4-424f-8d89-4aa248d0910c.png)
2.
![image](https://user-images.githubusercontent.com/30038088/140296102-92ba9cf8-a004-48d2-952a-7630eebea5f7.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
