### ISSUE TITLE
[BUG]从场景测试 创建 性能测试，设置完压力参数，还是提示 “压力配置参数不能为空!”

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7529]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.14
**Bug 描述**
从场景测试 创建 性能测试，设置完压力参数，还是提示 “压力配置参数不能为空!”
从场景里导出jmx文件，再导入到 性能测试，也有这个问题。
应该和有禁用线程组的情况是一个问题。

简要描述您碰到的问题

**Bug 重现步骤**

1.
![image](https://user-images.githubusercontent.com/30038088/140309257-4e47f748-8f01-4680-ae2c-08e79005124d.png)
2.
![image](https://user-images.githubusercontent.com/30038088/140309319-8e6abbe8-255f-42d2-a395-58441cd37caa.png)

3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，1.14.1修复

**Comment by zyyfit** [comment]
已修复
