### ISSUE TITLE
[BUG]场景报告中循环控制器展示的顺序是乱的

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7531]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**
场景报告中循环控制器展示的顺序是乱的
简要描述您碰到的问题

**Bug 重现步骤**

1.
![1931635493377_ pic_hd](https://user-images.githubusercontent.com/30038088/140448491-373448a7-2331-43e0-b934-d996f1946c7c.jpg)
2.
![1981635493477_ pic](https://user-images.githubusercontent.com/30038088/140448515-d8491ae0-b967-43ef-a0c8-fc65b802b738.jpg)
3.
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
