### ISSUE TITLE
[BUG]接口定义中，选择SQL，创建接口，自定义变量修改后，会把原有case的内容全部清空

### ISSUE THREAD

**Issue by kingfocus31** [metersphere/metersphere#7532]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.12.0有
v1.13.0也有

**Bug 描述**

接口定义中，选择SQL，创建接口，自定义变量修改后，会把原有case的内容全部清空

**Bug 重现步骤**

1.  接口定义——> 选择sql-->创建接口-->添加一个自定义变量
2. 然后给刚刚创建的接口，添加case，查看自定义变量，添加SQL脚本
3. 切回接口API，修改自定义变量（变量key值）
4. 切回case，发现case中自定义变量和sql脚本全部清空

**期待的正确结果**
case中自定义变量同步变更

**截图**
![image](https://user-images.githubusercontent.com/20938619/140450343-02187776-c833-4953-a273-a915c1a79658.png)
![image](https://user-images.githubusercontent.com/20938619/140450528-17635fe5-6c6f-415f-85ec-2c105c306e35.png)
![image](https://user-images.githubusercontent.com/20938619/140450553-31775cf4-e9b5-4809-b254-91f9dd42b557.png)
![image](https://user-images.githubusercontent.com/20938619/140450631-220dfd9a-5e28-4552-99de-c601a6ffca7c.png)
![image](https://user-images.githubusercontent.com/20938619/140450663-51cf8c00-3b7a-416a-b658-b1c02905f93b.png)
![image](https://user-images.githubusercontent.com/20938619/140450693-767490fc-16d1-46a1-a868-646ac25df6f7.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.14.0没有复现，请升级试试

**Comment by zyyfit** [comment]
复现了，后续版本修复

**Comment by zyyfit** [comment]
1.15.2已修复
