### ISSUE TITLE
[FEATURE] 接口自动化没有结束时，无法查看已经成功的接口响应，非常不友好

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7543]
**请描述您的需求或者改进建议.**
接口自动化没有结束时，无法查看已经成功的接口响应，非常不友好

**请描述你建议的实现方案**
接口自动化没有结束时，无法查看已经成功的接口响应，非常不友好

**Comment by wangzhen-fit2cloud** [comment]
请问是用的什么版本呢？

**Comment by allinone-1** [comment]
> 请问是用的什么版本呢？

版本:   v1.13.2-6ac3675a

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
