### ISSUE TITLE
[BUG]单接口调试，控制台不显示日志等信息

### ISSUE THREAD

**Issue by Luyan518** [metersphere/metersphere#7544]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  单接口调试，控制台无法显示信息；
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![24b85db478641f99b2624f4c7f0f6ec](https://user-images.githubusercontent.com/58943460/140473226-74840050-2ace-43d6-9463-1eb49304eb36.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
没有复现您的问题，使用的是哪个版本？
