### ISSUE TITLE
[BUG]在测试计划中，只给用户查询和关联测试用例的权限，用户有执行测试用例的权限；给了用户执行测试用例的权限，用户反而不能执行测试用例

### ISSUE THREAD

**Issue by Mokwang** [metersphere/metersphere#7554]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.1-b4
**Bug 描述**
在测试计划中，只给用户查询和关联测试用例的权限，用户有执行测试用例的权限，给了用户执行测试用例的权限，用户反而不能执行测试用例
简要描述您碰到的问题
在测试计划中，只给用户查询和关联测试用例的权限，用户有执行测试用例的权限，给了用户执行测试用例的权限，用户反而不能执行测试用例
**Bug 重现步骤**

1.  给建立的组分配测试计划查询和关联\取消关联测试用例的权限
2. 在执行测试计划时，发现对应组的用户有执行测试用例的权限
3. 如果给了用户执行测试用例的权限，用户反而不能执行测试用例

**期待的正确结果**

正确情况下应该是什么样的？
给用户执行测试用例/计划的权限，用户能执行测试用例
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/18331284/140479956-9424374f-28ac-49b7-b9e8-4e4a81c150a2.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们复现的结果是这样，
1.没有执行测试计划和批量执行用例的权限的话，是不可以执行接口和性能测试用例，也包括执行整个测试计划，但是是可以执行功能测试用例，这块没有限制。
2.如果授权了可以执行测试计划和批量执行的权限，确实执行失败了。。。跳转到个人信息页，下个版本会修复~

**Comment by zyyfit** [comment]
最新版已修复
