### ISSUE TITLE
[BUG]测试计划中拖拽编排场景用例，只能调整显示顺序，但无法作用于执行顺序

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7579]
**MeterSphere 版本**
>v1.14.0

**Bug 描述**

测试计划中拖拽编排场景用例，只能调整显示顺序，但无法作用于执行顺序

**Bug 重现步骤**

1.  有场景用例A、B
2. 在测试计划中拖拽A到B之前
3. 执行测试计划（串行）
4. B依然先于A执行

**期待的正确结果**

A先执行，B再执行（排序在前的用例先执行）

**截图**
![image](https://user-images.githubusercontent.com/34698664/140672722-e26fc9de-8ee5-48b8-94ee-3df65ee78a9b.png)
![image](https://user-images.githubusercontent.com/34698664/140672831-a3f0a10e-a84d-48a9-b942-a9c65fde1fe4.png)
![image](https://user-images.githubusercontent.com/34698664/140672871-416ba4c4-da64-4615-b0b9-14d1b2845596.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化！

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修改该问题

**Comment by Saco93** [comment]
> v1.14.2已修改该问题

请注意我这个Bug填写的版本号。1.14.2仅修复了场景自动化用例在测试计划中的执行顺序控制，但上面的这个Bug说的是接口自动化，麻烦再次确认。
我的截图都是在1.14.3版本下截取的。
