### ISSUE TITLE
[BUG]在API一级菜单下，切换Api Definition和Api Automation，无法保留已打开的标签（1.13.2尚且有此特性）

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7580]
**MeterSphere 版本**
>v1.14.0

**Bug 描述**

在API一级菜单下，切换Api Definition和Api Automation，无法保留已打开的标签

**Bug 重现步骤**

1.  在Api Automation中编辑一个场景用例A
2. 在同一个页面下切换到Api Definition
3. 切换回Api Automation，原本打开的场景用例A编辑标签自动关闭（_从接口上观察可能是切换后自动刷新了页面_）

**期待的正确结果**

保留场景用例A的编辑标签（1.13.2尚且有此特性）

**截图**
![image](https://user-images.githubusercontent.com/34698664/140673977-33c40463-0bba-4e5d-9a1f-9d40e49ce0e8.png)
![image](https://user-images.githubusercontent.com/34698664/140674020-6e7c0abe-d973-4eb3-979b-fde6381f5f79.png)
![image](https://user-images.githubusercontent.com/34698664/140674060-2769c0d6-71f7-404f-96ea-a995f12e023e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会优化~

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修改该问题
