### ISSUE TITLE
建议接口测试树型列表中同时显示接口数量和测试用例数量

### ISSUE THREAD

**Issue by malinpop** [metersphere/metersphere#7591]
**请描述您的需求或者改进建议.**

接口测试，左侧树型列表。 文件夹右侧目前只显示了当前文件夹下的API接口数量， 如：【XXXX项目    14】，实际我们更关注接口测试用例的数量和覆盖情况。

**请描述你建议的实现方案**

建议：右边的数字显示改为： 用例数 / 接口数  的呈现方式，如： 【XXXX项目    32/14】 ，表示当前定义了14个接口，编写了32个用例，一目了然

![接口](https://user-images.githubusercontent.com/16314637/140703332-aab400d1-7538-4cb0-b8db-62c48a4cbc1f.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
按你说的这样也无法体现出覆盖的情况吧， 你可以关注接口测试首页接口覆盖率这个指标。如果想看各个模块的覆盖率，这个可以提个报表需求。
