### ISSUE TITLE
[FEATURE]不同测试阶段的测试计划，能否允许名称一致？

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#7594]
**请描述您的需求或者改进建议.**
同一版本，会有冒烟测试、回归测试等。但系统不允许创建同名的测试计划，只能手动加后缀予以区分。
希望判断测试计划是否重名的时候，可以加上测试阶段这个值，允许创建不同阶段的同名测试计划。

**请描述你建议的实现方案**
<img width="786" alt="1" src="https://user-images.githubusercontent.com/71361375/140705627-5697c43f-013c-45fd-b9d0-ed20184e1db7.png">

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
可以关注我们后续版本的父子测试计划的设计。
