### ISSUE TITLE
[BUG]【偶发】在操作过程中出现闪退，直接退回到登陆页面

### ISSUE THREAD

**Issue by zhaoxu5534** [metersphere/metersphere#76]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.0
**Bug 描述**
简要描述您碰到的问题
在操作过程中出现闪退，直接退回到登陆页面
**Bug 重现步骤**
1.  登陆后，切换组织
2.  出现闪退，退回到了登陆页面（偶发）
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
不会退到登陆页面
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，已发布 v1.1.0 版本，欢迎下载试用
