### ISSUE TITLE
现有的Jmeter脚本，转为Json后还是无法导入

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#760]
**请描述您的需求或者改进建议.**

现有的Jmeter脚本，转为Json后还是无法导入。也不知道为什么无法导入，建议有说明或者导入要求等

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
目前支持的 json 格式为 MeterSphere 浏览器插件导出的 JSON 及 MeterSphere 接口测试导出的 JSON
