### ISSUE TITLE
[FEATURE][企业用户]自定义代码片段目前不支持跨项目调用，请优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7600]
**MeterSphere 版本**
版本:   v1.14.0-42d99ed2

**Bug 描述**

自定义代码片段目前不支持跨项目调用，请优化

**截图**
![image](https://user-images.githubusercontent.com/92150453/140710774-db9b1f31-36d3-4f5e-8e09-ded1c232c163.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
