### ISSUE TITLE
[BUG]当Swagger URL存在登录验证或其它认证机制时，通过Swagger URL的方式导入API接口，报错解析失败，请优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7602]
**MeterSphere 版本**
版本:   v1.14.0-42d99ed2

**Bug 描述**
当Swagger URL存在登录验证或其它认证机制时，通过Swagger URL的方式导入API接口，报错解析失败，请优化

**截图**
![image](https://user-images.githubusercontent.com/92150453/140712557-591d4e1d-f419-4391-87c6-427179751663.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，大概率是下个版本优化~
