### ISSUE TITLE
[BUG]接口测试--首页：接口统计错误，统计的不是当前项目下的接口数量，应该是当前工作空间的。但是其他统计数据是当前项目的

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7603]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？1.14

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG]接口测试--首页：接口统计错误，统计的不是当前项目下的接口数量，应该是当前工作空间的。但是其他统计数据是当前项目的
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/140719973-b468b518-1d26-4ada-a745-3d797eccc7af.png)

**Comment by youliyuan-fit2cloud** [comment]
您好，没有复现这个问题，建议清一下缓存试试？
