### ISSUE TITLE
[FEATURE]xmind模板能不能自己定义必填项

### ISSUE THREAD

**Issue by kellysi** [metersphere/metersphere#7604]
现在导出的xinmd模板是固定的，新增必填字段后，模板里无对应的标签，无法填写需要的字段。希望xmind模板可以根据自己的需求定义

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
