### ISSUE TITLE
[BUG][企业用户]Swagger上非string字符类型的参数，存在文字描述时，该文字描述无法同步至MS的API接口中，需优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7611]
**MeterSphere 版本**
版本:   v1.14.0-42d99ed2

**Bug 描述**
Swagger上非string字符类型的参数，存在文字描述时，该文字描述无法同步至MS的API接口中，需优化

**截图**
![23a0cc6211b9a83f184b571476fbcbc](https://user-images.githubusercontent.com/92150453/140883814-ba05645a-057e-443e-8c36-7bfb3acc6f7d.jpg)
![344e8e4275a6dcae17bf7636c614390](https://user-images.githubusercontent.com/92150453/140883829-2342902a-af8c-4a01-959e-39d0024bbec9.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本优化下

**Comment by youliyuan-fit2cloud** [comment]
1.18.3版本已修复
