### ISSUE TITLE
[BUG]接口测试里 响应体Body的Json格式不支持中文了

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#762]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
 v1.4.2-b1039
**Bug 描述**
简要描述您碰到的问题
之前响应体里Json格式如果出现中文是可以显示的，现在变成Unicode无法显示中文了
**Bug 重现步骤**
1. 接口返回数据为 一个包含中文的JSON数据

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44960709/98909393-bad7de80-24fc-11eb-980e-7029de538aaf.png)
![image](https://user-images.githubusercontent.com/44960709/98909625-0ab6a580-24fd-11eb-99c8-c2c2ff8f1139.png)

**Comment by wangzhen-fit2cloud** [comment]
是不是服务端得返回就是这样呢？
我这边测试返回中文数据是没问题的。
![image](https://user-images.githubusercontent.com/27671436/98921725-9683fe00-250c-11eb-9b76-2a8bbb115664.png)

**Comment by lingrance** [comment]
问题已解决，已经向后台小伙伴确认，的确是后台的问题

**Comment by chenbingjie-98** [comment]
解决了吗？现在的版本还有这个问题吗
