### ISSUE TITLE
[BUG]接口及自动化调试中，URL参数中的中文并没有自动转义或者提供转义的方式，导致发出去的参数为明文

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#7621]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.14.0

**Bug 描述**
接口及自动化调试中，URL参数中的中文并没有自动转义或者提供转义的方式，但是发出去的参数为明文
![image](https://user-images.githubusercontent.com/32027713/140903378-dd80fc03-4531-47d7-8ea3-f792e10b528b.png)

而jmeter是提供这种转义方式的
![image](https://user-images.githubusercontent.com/32027713/140903317-8c166448-2e66-45f4-8fed-2424af613ffd.png)

**否则每次修改参数都要去找URL转化工具去转，然后再贴到MS中**

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化一下

**Comment by zyyfit** [comment]
1.14.2已修复
