### ISSUE TITLE
[BUG]接口mock函数 不生效了

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7626]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.14
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/30038088/140910247-d626ead9-5f24-426d-94e7-c24821d70816.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
应该是  @a|md5
