### ISSUE TITLE
[BUG]脑图标签，点击“模块” 没反应 

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7629]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/30038088/140911274-9cf63894-03f9-4786-a4dc-6e0290b74e7b.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
这个 模块是这样，v1.15的时候可以用了
