### ISSUE TITLE
[BUG]新建场景后没有填写接口信息，禁用后保存提交没有校验Url为空。执行时，会导致程序报空字符串

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#765]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4.3
**Bug 描述**
简要描述您碰到的问题

![image](https://user-images.githubusercontent.com/53041390/98915887-7735a280-2505-11eb-8648-9f968a7c4b98.png)

![image](https://user-images.githubusercontent.com/53041390/98916186-ced40e00-2505-11eb-94e7-c8ce1e9d5904.png)
**Bug 重现步骤**
1.  新建场景和接口，不录入任何信息
2. 禁用该新建的场景和接口
3. 单击《保存》
4. 单击《保存并执行》
5.程序报错

**期待的正确结果**
正确情况下应该是什么样的？
应该在保存时校验所有的接口不为空
**截图**
如果有截图，请附上截图.

**Comment by liuruibin** [comment]
没有复现
