### ISSUE TITLE
[BUG] 新建用户或LDAP用户登录报错

### ISSUE THREAD

**Issue by rechardwang** [metersphere/metersphere#7652]
**MeterSphere 版本**

1.14.1 

**Bug 描述**

使用新建用户登录后 有报错

**Bug 重现步骤**

1.  新建用户
2.  用新用户账号登录
3.  登录即看到报错
4. 

**截图**

![image](https://user-images.githubusercontent.com/43982436/141099145-8bb14c36-1151-442f-b6ab-f4ff8e9a377d.png)

**Comment by rechardwang** [comment]
我这边测试了下 如果新建的用户没有选择项目 就会复现
![image](https://user-images.githubusercontent.com/43982436/141099923-094af626-4320-43d8-b331-0e9d999b7cf6.png)

**Comment by rechardwang** [comment]
而且这个选择项目 必须选择2个用户组

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈,下个版本修复该问题。

问题：“而且这个选择项目 必须选择2个用户组”--->不是必须选俩，上图中可删除用户组0，系统管理员用户组是不需要再选择项目的，
项目管理员用户组必须选一个项目

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修改该问题
