### ISSUE TITLE
[BUG]MeterSphere接口自动化在一个场景运行没有完全结束时，无法查看已经成功的接口响应

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#7653]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14
**Bug 描述**
[BUG]MeterSphere接口自动化在一个场景运行没有完全结束时，无法查看已经成功的接口响应
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
<img width="672" alt="067ac2750fcbc2538176ca1412f6789" src="https://user-images.githubusercontent.com/85992665/141222576-2e617a5d-9c49-48c5-89cc-31267818aa01.png">

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，这位同学，不算是非常不友好吧，一个场景执行一般几秒钟，查看不差这一会儿

**Comment by Sensivitiry** [comment]
> 你好，这位同学，不算是非常不友好吧，一个场景执行一般几秒钟，查看不差这一会儿

因为这个是之前没有的，而且我也反馈过，你说的也对，执行一般几秒钟，但是导入导出呢，可就不止几秒钟了或者是一个场景里面用例比较多也挺麻烦的。

**Comment by allinone-1** [comment]
> 算是非常不

有的时候调试过程中有可能出现部分接口请求卡死，不会停止的情况，或者使用了循环控制器这种，就想看下之前的传参信息这种，就无法查看，而且当一个测试场景比较复杂时，十几个请求，一起的话应该都要20几秒了，也会有查看之前成功的请求的需求
