### ISSUE TITLE
[BUG]json参数怎无法传空值。

### ISSUE THREAD

**Issue by qiaoshengyu** [metersphere/metersphere#7658]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14.1
**Bug 描述**

简要描述您碰到的问题
json参数怎无法传空值。
**Bug 重现步骤**

1.参数不填值还是传了""，怎么填写才能传null
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
参数不填值还是传了""，怎么填写才能传null
**截图**

如果有截图，请附上截图.
![6_%{B)B)WVDUL5%1~OT ZMA](https://user-images.githubusercontent.com/41959940/141244388-bb2a4615-ed85-4598-be33-6120b01681bf.png)

**Comment by zyyfit** [comment]
您好，可以直接不填这个字段，或者不用json-schema，使用json格式，直接填null（注意不要加引号）
![图片](https://user-images.githubusercontent.com/73461316/141399751-8b8993f2-4fe5-40a1-a84a-afd5f9f2d207.png)
