### ISSUE TITLE
能不能把已经写好的jmeter脚本上传到平台，自动生成接口测试案例

### ISSUE THREAD

**Issue by Samercc** [metersphere/metersphere#766]
**请描述您的需求或者改进建议.**
背景：
公司已经写好太多Jmeter脚本，重新录入到平台，时间成本太高了，所以有以下的需求

1、能不能把已经写好的jmeter脚本上传到平台，自动生成接口测试案例？

**请描述你建议的实现方案**
实现方案：A
遍历jmx脚本内容，提取每个请求的相关参数，存储到接口案例list中，再把整个list关联到metersphere的项目对象

**Comment by wangzhen-fit2cloud** [comment]
你好，目前我们正在重构改写接口测试相关功能，计划在 1.6 版本完成，将在改写后考虑该场景，请持续关注。
