### ISSUE TITLE
[BUG]Mock服务页面，打开编辑接口有时候关闭不了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#7660]
**MeterSphere 版本**

1.14.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 
<img width="739" alt="微信图片_20211111144523" src="https://user-images.githubusercontent.com/88763608/141250807-9b29852d-9218-4457-ade9-b2d767569e9b.png">

**Comment by zyyfit** [comment]
已知问题，正在优化

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修改该问题

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修改该问题
