### ISSUE TITLE
创建新的项目并正常配置了环境，创建接口用例执行时一直加载中

### ISSUE THREAD

**Issue by fengchen18** [metersphere/metersphere#7665]
**MeterSphere 版本**

v1.13.2

**Bug 描述**
创建新的项目并正常配置了环境，创建接口用例执行时一直加载中

**Bug 重现步骤**

1.  首页左上角下拉直接创建新项目
2. 在环境配置目录中正常配置项目得环境
3. 创建接口和用例并执行用例

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![1636621028(1)](https://user-images.githubusercontent.com/83397037/141268429-7923a7e0-7455-418f-9732-dd62364456f2.jpg)
![1636620871(1)](https://user-images.githubusercontent.com/83397037/141268484-b89b1404-a3a4-4cc7-b38f-7c70a58179a0.jpg)

**Comment by zyyfit** [comment]
您好，最新班已经是1.14.1了，没有复现这个问题，建议您升级版本使用

**Comment by fengchen18** [comment]
升级使用不会影响我的接口定义里的数据嘛



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月12日 11:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [metersphere/metersphere] 创建新的项目并正常配置了环境，创建接口用例执行时一直加载中 (Issue #7665) |

您好，最新班已经是1.14.1了，没有复现这个问题，建议您升级版本使用

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
您要升级的话可以先备份一下数据库，然后升级试试，不过我们修复的问题只会在新版本发布，不会再维护除lts版本之外的旧版本的

**Comment by fengchen18** [comment]
你们没解决为什么要关闭bug



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月02日 18:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [metersphere/metersphere] 创建新的项目并正常配置了环境，创建接口用例执行时一直加载中 (Issue #7665) |

Closed #7665.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
> 你们没解决为什么要关闭bug 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年12月02日 18:32 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [metersphere/metersphere] 创建新的项目并正常配置了环境，创建接口用例执行时一直加载中 (Issue #7665) | Closed #7665. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

因为我们最新版已经没有复现这个问题了，而且要修复的话我们会在新版修复的，不会在1.13修复再发1.13.3了
