### ISSUE TITLE
[BUG]TCP mock的json raw点击无响应

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#7666]
**MeterSphere 版本**

1.14.1

**Bug 描述**

![image](https://user-images.githubusercontent.com/88763608/141269547-7b4d01bf-16c0-4b97-9a9e-e070ee9b8986.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.14.2已修复
