### ISSUE TITLE
[BUG]接口用例修改后，未能在测试计划执行时生效（非必现）。

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7667]
**MeterSphere 版本**

v1.14.1-12036e57

**Bug 描述**

[BUG]接口用例修改后，未能在测试计划执行时生效（非必现）。

**Bug 重现步骤**

1.  测试计划A中有接口用例a
2. 修改a后保存
3. 通过Jenkins触发执行A
4. a在执行时依旧使用的是修改前的参数

**期待的正确结果**

a在执行时使用修改后的参数

**截图**

![wecom-temp-abd8962deaee1c232c4974fac3341e37](https://user-images.githubusercontent.com/34698664/141275168-201ed68a-1d1a-4448-b435-0f08b0f3f30c.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，新版本没复现该问题，建议升级到最新版本试试吧~
