### ISSUE TITLE
执行性能测试时报错"java.net.SocketException: No such file or directory"

### ISSUE THREAD

**Issue by Aaron-23** [metersphere/metersphere#767]
执行性能测试时报错"java.net.SocketException: No such file or directory"

![image](https://user-images.githubusercontent.com/50609288/98925122-971e9380-2510-11eb-8be8-5372c7ab3d3d.png)
![image](https://user-images.githubusercontent.com/50609288/98925139-9be34780-2510-11eb-982a-d9693960957d.png)

node-controller日志
![image](https://user-images.githubusercontent.com/50609288/98925199-ab629080-2510-11eb-9ad4-e752597dbf86.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问 node-controller 的运行环境是怎么样的，是怎么部署的？

**Comment by Aaron-23** [comment]
通过`docker run -it registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.4.3`运行部署
挂载了以下存储

**Comment by wangzhen-fit2cloud** [comment]
你好，是部署在 windows 上的吗，目前 node-controller 在 windows 上运行未经过验证
