### ISSUE TITLE
[BUG]新增用例后-责任人是Code-测试跟踪-首页-本周新增仍显示0个需要编辑后,责任人更新为姓名,本周新增也更新

### ISSUE THREAD

**Issue by Ggangwang21** [metersphere/metersphere#7673]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
 v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题

新增用例后-责任人是Code-测试跟踪-首页-本周新增仍显示0个需要编辑后,责任人更新为姓名,本周新增也更新

**Bug 重现步骤**

1.  新增用例后,不编辑查看用例列表-确认责任人为新增人姓名----实际责任人显示code
2. 新增用户后,不编辑查看测试跟踪-首页-确认本周新增更新----实际本周新增更新仍显示0
3. 
如上实际结果,编辑用例,不修改点保存,用例列表责任人更新为新增人姓名,测试跟踪-首页-本周新增才更新数据

**期待的正确结果**

正确情况下应该是什么样的？
1.新增后,用例列表责任人就为姓名
2.新增后,测试跟踪-首页本周新增更新数据统计

**截图**
![image](https://user-images.githubusercontent.com/89377465/141321267-d7fb4913-3427-4b63-9e5b-84c0a722629b.png)
![image](https://user-images.githubusercontent.com/89377465/141321295-5c9b9688-9220-4eee-b7a1-7bee2289cdb4.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版没有复现这两个问题，可能是已经修复过了，建议您使用最新版（目前最新版是 1.14.1）
