### ISSUE TITLE
[BUG]接口自动化场景里面存在引用场景时,调试/运行时引用场景的控制台&提取没有信息,导致场景报错时,无法准确定位问题

### ISSUE THREAD

**Issue by Ggangwang21** [metersphere/metersphere#7674]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题
接口自动化场景里面存在引用场景时,引用场景的控制台&提取没有信息,导致场景报错时,无法准确定位问题
![图片1](https://user-images.githubusercontent.com/89377465/141323105-c2222a0e-e040-4544-a1ea-beab7beffc68.png)

**Bug 重现步骤**

1.  接口自动化场景中存在引用场景/引用场景A-场景A又有引用场景B--在调试/运行时----确认引用场景中的接口可以查看控制台和提取信息-----实际控制台和提取均为空无法查看
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

期望  引用的场景也可以查看控制台和提取信息

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版没有复现这个问题，建议您升级到最新版使用
