### ISSUE TITLE
[FEATURE]Jmeter导入的脚本到MS平台,脚本的标识均是自定义请求,是否可以自动匹配到接口列表,标识成接口列表导入

### ISSUE THREAD

**Issue by Ggangwang21** [metersphere/metersphere#7676]
**请描述您的需求或者改进建议.**

Jmeter导入的脚本到MS平台中,脚本导入到接口用例和接口自动化场景中,脚本对应的接口都是自定义请求,脚本的标识均是自定义请求,是否可以自动匹配到接口列表,能匹配到的标识成接口列表导入,能够匹配到接口用例的,算上接口用例的覆盖率,以及算上场景用例的接口覆盖率

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
