### ISSUE TITLE
[BUG]在数据库配置中，发现数据库账号密码明文返回给前端了，这样不太安全。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#7680]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.14

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在数据库配置中，发现数据库账号密码明文返回给前端了，这样不太安全。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/141403081-054d981d-5e9a-425e-a09d-220f082680f0.png)

**Comment by zyyfit** [comment]
感谢反馈
