### ISSUE TITLE
[BUG]mac 离线运行，报错

### ISSUE THREAD

**Issue by junjunsay** [metersphere/metersphere#7688]
**MeterSphere 版本**

最新版1.14.1

**Bug 描述**

mac 离线下载安装

**Bug 重现步骤**

1. 下载包，解包
2. 去掉docker-compose 版本验证
3. 运行 install.sh
4. 报错
[MeterSphere Log]: 启动服务 

.FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-base.yml'

.FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-base.yml'

.FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-base.yml'
======================= 安装完成 =======================

请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
您可以使用命令 'msctl status' 检查服务运行情况.

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

<img width="722" alt="截屏2021-11-12 下午3 41 05" src="https://user-images.githubusercontent.com/31124195/141428961-333d59ba-3ef7-4a97-9c42-4f776d42cc18.png">

**Comment by zyyfit** [comment]
您好，我们的一键安装脚本目前不支持mac安装，您可以参考一下这几个问题的处理方式
https://github.com/metersphere/metersphere/issues/657
https://github.com/metersphere/metersphere/issues/3544
