### ISSUE TITLE
[FEATURE]用例自定义字段在功能用例、测试计划模块下高级搜索中条件中，没有展示出来，不方便过滤用例

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7690]
**请描述您的需求或者改进建议.**
用例自定义字段在功能用例、测试计划模块下高级搜索中条件中，没有展示出来，不方便过滤用例

![image](https://user-images.githubusercontent.com/7023291/141432098-d358246f-7c4e-432c-bebc-e073fec353c8.png)
![image](https://user-images.githubusercontent.com/7023291/141432131-7ec83228-218b-4c90-8560-baf73f777f4e.png)

**请描述你建议的实现方案**
1、用户自定义字段，可以在功能用例、测试计划模块下的高级搜索中展示
2、并且高级搜索条件类型和自定义字段类型一致，比如自定义字段为下拉选项，那么高级搜索中也是下拉选项且值集一致

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。
