### ISSUE TITLE
[FEATURE]测试跟踪-首页页面，建议增加同一个项目下，不同版本的质量趋势（按用例失败数量、缺陷维度）

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7691]
**请描述您的需求或者改进建议.**
测试跟踪-首页页面，建议增加同一个项目下，不同版本的质量趋势（按用例失败数量、缺陷维度）

**请描述你建议的实现方案**
建议在缺陷跟踪的首页中，增加展示当前项目下，不同版本的质量趋势图，可以按用例失败数量、缺陷数量等维度

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
