### ISSUE TITLE
[FEATURE]功能用例中的变更，不应该直接同步到已经关联到测试计划的用例中（因为当前执行的用例可能和下一个迭代同步进行，下一个迭代对用例可能做修改，但是当前执行的用例不应受到影响）

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7692]
**MeterSphere 版本**
1.14
**Bug 描述**
功能用例中的变更，不应该直接同步到测试计划中（因为当前执行的用例可能和下一个迭代同步进行，下一个迭代对用例可能做修改，但是当前执行的用例不应受到影响）

**Bug 重现步骤**

1. 创建测试计划，然后关联用例
2. 在功能用例中修改被关联的用例（修改名称、步骤信息）
3. 测试计划中已经关联的用例也被同步修改

**期待的正确结果**
功能用例中的变更，不应该直接同步到当前已经关联到测试计划的用例

**截图**
无

**Comment by zyyfit** [comment]
您好，目前我们还没有对用例做版本管理，后续会考虑这块优化的

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个我们通过版本去解决，版本功能已经支持了，建议更新到v2.7版本使用。
