### ISSUE TITLE
[FEATURE]建议测试报告中，增加按执行人、标签、自定义字段维度，展示测试进度图表

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7693]
**请描述您的需求或者改进建议.**
测试计划中可以查看测试报告，但是测试报告中仅仅展示了整体用例按状态饼状图，所有用例清单、失败的用例，建议体现当前计划每个执行人各自的进度统计（可参考testlink的测试报告），按标签维度进行统计
另外，testlink中的测试报告还体现当前测试计划关联的用例，按自定义字段统计

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能经评估，整体工作量较大，我们会放到v3.0版本中，请关注后续的版本发布，谢谢。
