### ISSUE TITLE
[FEATURE]目前用例的修改记录以字段修改前后标注，非常不清晰，而且格式不方便查看。建议参考testlink的版本展示方式，每个版本能看到完整用例信息

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7694]
**请描述您的需求或者改进建议.**
目前用例的修改记录以字段修改前后标注，非常不清晰，而且格式不方便查看。建议参考testlink的版本展示方式，每个版本能看到完整用例信息
![image](https://user-images.githubusercontent.com/7023291/141433486-b02e4e84-2a6c-464c-88d5-027c0f217de8.png)

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研
