### ISSUE TITLE
[FEATURE]因为一个用例可以打多个标签， 功能用例和测试计划查询用例时，高级搜索对标签查询支持不灵活，目前仅有包含或不包含，希望能实现包含、不包含 加上 且、或的逻辑关系

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7695]
**请描述您的需求或者改进建议.**
因为一个用例可以打多个标签，
功能用例和测试计划查询用例时，高级搜索对标签查询支持不灵活，目前仅有包含或不包含，希望能实现包含、不包含 加上 且、或的逻辑关系

**请描述你建议的实现方案**

**Comment by zyyfit** [comment]
感谢反馈，我们进行一下需求调研

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
