### ISSUE TITLE
[BUG]在功能用例模块批量更新用例的输入框类型自定义字段时，“更新后属性值为”为空下拉框，也无法编辑

### ISSUE THREAD

**Issue by LinRang** [metersphere/metersphere#7696]
**MeterSphere 版本**
1.14.1

**Bug 描述**
在功能用例模块批量更新用例的输入框类型的自定义字段时，“更新后属性值为”为空下拉框，也无法编辑

**Bug 重现步骤**

1.  给用例模板添加输入框类型自定义字段
2. 在功能用例模块选中多个用例
3. 点击...进行批量更新用例
4. 更新字段选择自定义字段，检查“更新后属性值为”为空下拉框，也无法编辑

**期待的正确结果**
自定义字段进行批量修改时，“更新后属性值为”类型应该和自定义字段类型保持一致，例如自定义字段为下拉框，那么批量编辑时也是下拉，且下拉值集一致

**截图**

![image](https://user-images.githubusercontent.com/7023291/141436367-ed03b860-3237-4c2e-9762-1ea648ced00e.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您批量更新所选的这个 “自定义字段” 是下拉框类型的还是输入框类型的呢？
![图片](https://user-images.githubusercontent.com/73461316/141709303-929b0143-e379-46e2-98b6-bab4e70a9505.png)

**Comment by LinRang** [comment]
> 您好，没有复现这个问题，您批量更新所选的这个 “自定义字段” 是下拉框类型的还是输入框类型的呢？ ![图片](https://user-images.githubusercontent.com/73461316/141709303-929b0143-e379-46e2-98b6-bab4e70a9505.png)

问题的步骤里面有描述，是输入框类型的自定义字段呢

**Comment by zyyfit** [comment]
好的，后面的版本修复

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
