### ISSUE TITLE
[QUESTION]ms-data-streaming没有正常启动

### ISSUE THREAD

**Issue by Dz-fanzhi** [metersphere/metersphere#771]
**请描述您的问题.**
使用性能测试是报错 提示  Kafka 不可用，请检查配置
检查服务器发现是ms-data-streaming起不来。
ERROR: for ms-data-streaming  Container "235d12870c53" is unhealthy.

![image](https://user-images.githubusercontent.com/26322606/99036693-1ec1dc00-25bd-11eb-9707-4ad48f569a67.png)
希望能帮忙解决下

**Comment by wangzhen-fit2cloud** [comment]
请查看下相关组件的日志
docker logs ms-data-streaming

可以参考 https://metersphere.io/docs/faq/#qkafka
