### ISSUE TITLE
[BUG]测试计划中添加有关联接口测试的手工用例，并勾选同步添加关联的接口和性能测试时，添加的接口测试，运行环境为空，无法运行

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7727]
**MeterSphere 版本**

版本:   v1.14.1-12036e57

**Bug 描述**

测试计划中添加有关联接口测试的手工用例，并勾选同步添加关联的接口和性能测试时，添加的接口测试，运行环境为空，无法运行

**期待的正确结果**

关联同步的接口测试用例，运行环境默认为原用例的运行环境，或者支持手动修改

**截图**
<img width="960" alt="d4fef613464ce31c888f61869a2d822" src="https://user-images.githubusercontent.com/92150453/141729575-1843a614-6362-4582-93cc-bdf09098806b.png">
<img width="960" alt="d2f878695b6e468623bac5242537737" src="https://user-images.githubusercontent.com/92150453/141729585-7b522d7d-3f70-49f7-bedc-1619694d0227.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
