### ISSUE TITLE
[BUG]oracle数据库连不上去

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#773]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
最新版本
**Bug 描述**
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/26785348/99226459-ca209a00-2824-11eb-80e3-88ad34a224dc.png)

**Bug 重现步骤**
1.  连接oracle数据库，当sql有错误后，再次修改正确后再也连接不上了
2. 比如说两个sql请求，Asql请求结尾少了个 ；报错是正常，添加后再次执行无法成功
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by AgAngle** [comment]
![image](https://user-images.githubusercontent.com/41557596/100079784-0cc71f80-2e80-11eb-9ab2-c4994ec85e91.png)
你好，这个情况我也调研了一下 jmeter ，这个是最大连接数设置过大导致的，建议设置小一点，我这边也加个限制
