### ISSUE TITLE
[BUG]将接口场景添加到测试计划中，然后删除测试计划，重新创建测试计划时，接口场景列表就少了之前添加过的场景了

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#7733]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  添加A、B、C接口场景到测试计划中
2. 删除该测试计划
3. 重新创建测试计划，添加A、B、C接口场景
4. 

**期待的正确结果**
3.能正常添加接口场景A、B、C，实际接口场景列表中没有接口场景A、B、C
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.14.1没有复现这个问题，建议您升级到最新版使用
