### ISSUE TITLE
[BUG]推荐JSONPath断言的时候提示：“响应结果不是json格式”

### ISSUE THREAD

**Issue by Jetdachui** [metersphere/metersphere#7738]
**MeterSphere 版本**
v1.14.1-b10

**Bug 描述**

**正确情况下应该是什么样的？**
格式应该是json但是似乎是嵌套太多/太长导致格式识别不了，因为我在响应结果返回较短的时候使用的正常的

**截图**
![image](https://user-images.githubusercontent.com/74963743/141749352-035c5cdb-3533-4a72-9c48-35972d9e55f1.png)

**响应结果**
[识别不了是json.log](https://github.com/metersphere/metersphere/files/7537174/json.log)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by Jetdachui** [comment]
客气



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月15日(周一) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]推荐JSONPath断言的时候提示：“响应结果不是json格式” (Issue #7738)




 
感谢反馈，后续版本修复
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youliyuan-fit2cloud** [comment]
v1.14.2已修复

**Comment by Jetdachui** [comment]
好的 谢谢！
