### ISSUE TITLE
[需求]在功能用例模块-用例列表栏下，建议新增用例结果字段，能够正常回写测试计划执行后对应用例的执行结果，并在用例详情页显示最近几次该用例的执行结果

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7739]
**MeterSphere 版本**

v1.14.1-12036e57

**需求描述**

在功能用例模块-用例列表栏下，建议新增用例结果字段，能够正常回写测试计划执行后对应用例的执行结果，并在用例详情页显示最近几次该用例的执行结果

**截图**

<img width="960" alt="fbb9b064f3ca74bc6bc84b1cd3a0b63" src="https://user-images.githubusercontent.com/92150453/141751029-7247cfe6-da99-4b6f-bf29-80bf8cdf768a.png">

**Comment by zyyfit** [comment]
感谢反馈，我们先调研一下需求

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
