### ISSUE TITLE
[FEATURE]希望一个SQL请求可以执行多条语句

### ISSUE THREAD

**Issue by leosrzheng** [metersphere/metersphere#774]
**请描述您的需求或者改进建议.**
数据初始化及清理数据会涉及到多张表

![image](https://user-images.githubusercontent.com/26785348/99360816-1e428180-28ec-11eb-8ef4-7b57a27ec709.png)

![image](https://user-images.githubusercontent.com/26785348/99360967-5a75e200-28ec-11eb-8691-bd6d6a6c53e1.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，现在是支持多条语句的，有什么具体的报错信息吗

**Comment by leosrzheng** [comment]
数据库执行










工具执行



You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from store where code=1000' at line 2



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 下午3:05
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774)





 
你好，现在是支持多条语句的，有什么具体的报错信息吗

**Comment by wangzhen-fit2cloud** [comment]
> 数据库执行 工具执行 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from store where code=1000' at line 2
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月17日(星期二) 下午3:05 收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;; 抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774) 你好，现在是支持多条语句的，有什么具体的报错信息吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有看到上传的图片

**Comment by leosrzheng** [comment]
数据库执行










工具执行



You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from store where code=1000' at line 2



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 下午3:05
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774)





 
你好，现在是支持多条语句的，有什么具体的报错信息吗

**Comment by leosrzheng** [comment]
后面发的收到图片没


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 下午3:25
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774)





  
数据库执行 工具执行 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from store where code=1000' at line 2
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月17日(星期二) 下午3:05 收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;; 抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774) 你好，现在是支持多条语句的，有什么具体的报错信息吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没有看到上传的图片

**Comment by Ybump14** [comment]
jdbc:mysql://192.168.1.110:3306?allowMultiQueries=true&serverTimezone=UTC

加入allowMultiQueries=true这段就行，必须放在serverTimezone=UTC前面

**Comment by leosrzheng** [comment]
收到多谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 下午2:38
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774)





 
jdbc:mysql://192.168.1.110:3306?allowMultiQueries=true&amp;serverTimezone=UTC
 
加入allowMultiQueries=true这段就行，必须放在serverTimezone=UTC前面

**Comment by leosrzheng** [comment]
有空帮忙看看那个连接oracle数据库的问题，单号773




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 下午2:38
收件人:&nbsp;"metersphere/metersphere"<metersphere@noreply.github.com&gt;;
抄送:&nbsp;"我以为你不一样"<972197622@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [FEATURE]希望一个SQL请求可以执行多条语句 (#774)





 
jdbc:mysql://192.168.1.110:3306?allowMultiQueries=true&amp;serverTimezone=UTC
 
加入allowMultiQueries=true这段就行，必须放在serverTimezone=UTC前面
