### ISSUE TITLE
[BUG]缺陷bug关联测试用例后，如果关联的测试用例被删除（回收站中也删除），缺陷bug也会被删除。

### ISSUE THREAD

**Issue by mileslian** [metersphere/metersphere#7742]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  缺陷bug关联测试用例后，如果关联的测试用例被删除（回收站中也删除），缺陷bug也会被删除。
2. 我关联的是jira平台
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您是说ms上的缺陷会被删除吗？我看jira上的用例还是在的

**Comment by mileslian** [comment]
是的，jira上的缺陷还在，ms上的缺陷会被删除。
此外，如果ms上的缺陷关联两个测试用例，彻底删除其中一个测试用例，ms上的缺陷也会被删除。

**Comment by zyyfit** [comment]
> 是的，jira上的缺陷还在，ms上的缺陷会被删除。 此外，如果ms上的缺陷关联两个测试用例，彻底删除其中一个测试用例，ms上的缺陷也会被删除。

好的，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
