### ISSUE TITLE
[BUG]使用脑图新建用例时，无法创建模块，功能实现不完整，请优化

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#7748]
**MeterSphere 版本**

版本:   v1.14.1-12036e57

**Bug 描述**

功能用例-脑图模块，使用脑图新建用例时，无法创建模块，功能实现不完整，请优化

**截图**

![image](https://user-images.githubusercontent.com/92150453/141761032-d54f2367-9266-4087-beed-9276780b7e9d.png)

**Comment by zyyfit** [comment]
您好，这是1.15的新功能，1.14还不支持创建模块
