### ISSUE TITLE
调用MS接口的时候，在API key界面能够有地址和使用示例

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#777]
**请描述您的需求或者改进建议.**
如下图
![image](https://user-images.githubusercontent.com/30932762/99357071-40d19c00-28e6-11eb-9312-f14a5f0e0e6f.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，右上角增加了 API 文档跳转链接。
