### ISSUE TITLE
[BUG]响应体中文未正常显示

### ISSUE THREAD

**Issue by XHC-XHC** [metersphere/metersphere#7794]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
  v1.14.0-42d99ed2
**Bug 描述**
响应体中的中文展示问题

**Bug 重现步骤**

1.  接口返回中带有中文信息。
2. 在响应体中查看返回信息，中文未正常展示

**期待的正确结果**
中英文、特殊字符应正常展示、
正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/52186469/141954646-865da94b-f7b8-43d7-85bb-ae64cdeb30c3.png)

**截图**
![image](https://user-images.githubusercontent.com/52186469/141954733-7e34512f-975c-4185-a215-2038c523c517.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，这个接口是否有什么编码之类的设置呢？

![图片](https://user-images.githubusercontent.com/73461316/142096729-a227122b-576a-4490-b993-915228eff692.png)

**Comment by XHC-XHC** [comment]
没有其他特殊设置了，就响应体中没正常展示，在提取参数中看到中文是正常展示的。

**Comment by XHC-XHC** [comment]
问题已解决，解决方式如下：
![image](https://user-images.githubusercontent.com/52186469/142347733-36c37b57-02ae-4689-beee-6ae77a41822b.png)
