### ISSUE TITLE
断言设置规则JSONPath设置为不等于，性能测试的时候只判断了等于

### ISSUE THREAD

**Issue by pptech-dev** [metersphere/metersphere#7795]
version: 1.10.0
接口用例设置如下图
![image](https://user-images.githubusercontent.com/84951843/120153577-79e9b200-c221-11eb-94e1-ec6e8087d64d.png)

性能测试时，却报以下错误
![image](https://user-images.githubusercontent.com/84951843/120153740-ad2c4100-c221-11eb-99eb-8318f0aa64a6.png)

生成的jmx文件是正确的
![image](https://user-images.githubusercontent.com/84951843/120153956-e9f83800-c221-11eb-890b-4b6c9d348542.png)

研究了一下源码，发现这里只判断了是否使用了JSONVALIDATION，但没判断设置的是“等于”还是“不等于”
![image](https://user-images.githubusercontent.com/84951843/120154082-101dd800-c222-11eb-88db-e47cd983d5a4.png)

**Comment by youliyuan-fit2cloud** [comment]
最新版本已解决
