### ISSUE TITLE
节点上运行场景，报kafaka，最大请求超过1M错误

### ISSUE THREAD

**Issue by zero654321** [metersphere/metersphere#7796]
版本：v1.10.5
问题描述： 测试计划-接口测试用例-场景用例，一个很大的场景， 节点执行， 执行完之后发送结果到kafka 出现问题，
![image](https://user-images.githubusercontent.com/74335133/125715365-45a71c43-9eb5-4d95-aa46-e95a1b03b087.png)
建议： 不是执行完整个记录返回，是否可考虑按照大小可以拆分一下分段返回

**Comment by xulinde** [comment]
最新版本v1.20.4是否还有此问题？
