### ISSUE TITLE
导入测试用例错误提示信息优化

### ISSUE THREAD

**Issue by youliyuan-fit2cloud** [metersphere/metersphere#78]
问题描述：
导入的测试用例如果该工作空间下无该用户，错误提示信息列出所有用例，每一用例显示一行，导致显示几百行信息

预期结果
建议修改为提示信息为 一行即可。

**Comment by youliyuan-fit2cloud** [comment]
![图片](https://user-images.githubusercontent.com/54612864/86335886-ab5ca500-bc81-11ea-8ab3-103e610ae280.png)

**Comment by wangzhen-fit2cloud** [comment]
我觉得这个固定最大高度，增加一个滚动条会更好一些
