### ISSUE TITLE
[FEATURE]测试报告查看区域较小，滚动条过多查看不便

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#7801]
**请描述您的需求或者改进建议.**
### 在查看测试报告的时候，这个报告的区域高度限制得太小了，而且里面有三根滚动条，不便于上下滚动。类似的高度和滚动的问题在配置场景用例和接口用例的时候也有。
![image](https://user-images.githubusercontent.com/34698664/142128959-bd22c57d-a5af-4010-b508-f4ed27b6da59.png)

**请描述你建议的实现方案**
### 建议主要的报告详情区域改为自适应高度，单个步骤展开详情可以全量展开；或者提供详情区域的手动拉伸功能。

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
