### ISSUE TITLE
[BUG]接口未正确请求及响应

### ISSUE THREAD

**Issue by XHC-XHC** [metersphere/metersphere#7811]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.1-12036e57
**Bug 描述**
在编辑接口和接口自动化中，接口无法正常执行，请求头数据丢失，在快速调试中正常。

简要描述您碰到的问题

**Bug 重现步骤**

1.  同样的请求接口在快速调试中执行，请求体的用户账号完全一致。
2. 快速调试可以正常返回执行，在接口自动化和编辑接口中无法正常执行。
3. 在接口自动化和编辑接口中请求头数据丢失

**期待的正确结果**
接口均可正常执行，并返回
正确情况下应该是什么样的？
正常的请求数据如下：
![image](https://user-images.githubusercontent.com/52186469/142149075-2b89854e-cfc9-4c79-b109-c51b6859ec24.png)
异常的请求数据如下：
![image](https://user-images.githubusercontent.com/52186469/142149280-5bbceebf-6504-4c95-812e-5095eaee81ae.png)

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有遇到过这种问题，是每个接口都这样吗？方便把报错的接口导出来发给我们吗？

**Comment by XHC-XHC** [comment]
可以，不过你们可能无法访问 ，我把导出的文件改成.docx格式了，你们下载后改成.JSON格式再导入
[Metersphere_Api_默认项目.docx](https://github.com/metersphere/metersphere/files/7560233/Metersphere_Api_.docx)

**Comment by XHC-XHC** [comment]
问题原因已找到：是环境配置界面的认证配置引起的：
![image](https://user-images.githubusercontent.com/52186469/142373943-40566b3d-ccb6-4df6-a999-8a7dd2915ddf.png)

**Comment by zyyfit** [comment]
1.14.3已修复
