### ISSUE TITLE
[BUG]mock自定义脚本匹配成功后未生效

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#7812]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14.2
**Bug 描述**
设置mock期望代码定义中设置返回请求变量，调用mock匹配成功，返回的消息体为空，未返回请求变量中的内容

**Bug 重现步骤**

1.  创建接口，设置mock期望代码定义返回请求变量
2. 
3. 
4. 

**期待的正确结果**

能够正确获取请求内容并返回。

**截图**

![A $@OEL1IJ910LCYNX5{0W](https://user-images.githubusercontent.com/40912823/142149177-8babc714-4737-4a0a-8d8f-2cdbe5640e12.png)

**Comment by zyyfit** [comment]
您好，这个使用的时候要把  ${param} 替换成对应的变量名
