### ISSUE TITLE
前置脚本中使用函数，动态取值

### ISSUE THREAD

**Issue by chenbingjie-98** [metersphere/metersphere#7814]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/63558318/142158201-bf51ee49-4e76-45e7-ab96-36657e5de501.png)

2. 
3. 
4. 

**期待的正确结果**
可以正确的显示我想要的动态值。
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by chenbingjie-98** [comment]
解析的时候一直都是那+tokenStr+去做MD5解析

**Comment by liuruibin** [comment]
在JMeter中，类似${}中的值会被优先解析。文本中想使用md5的话可以用groovy脚本

def value = '123456'
 
def md5 = value.md5()
log.info(md5)
