### ISSUE TITLE
postman导入的接口无法正确请求结果[BUG]

### ISSUE THREAD

**Issue by derekzhan** [metersphere/metersphere#7815]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
用户订阅关系同步， 在沃家云视客户端登录成功后 静默调用接口用来同步设备信息
**Bug 描述**

postman导入的接口无法正确请求结果

**Bug 重现步骤**

1.  导出postman
2. 导入到ms中
3. 点击测试
4. 

**期待的正确结果**
![image](https://user-images.githubusercontent.com/2375460/142163718-dc5b20c5-4f65-48b6-bb21-2fa07716fa54.png)

相同的参数放到ms中返回错误，如下图
**截图**
![image](https://user-images.githubusercontent.com/2375460/142163943-b764233d-cf79-4fcd-a3de-9800df2f9e2b.png)

**Comment by zyyfit** [comment]
您好，方便把ms的请求内容和postman的请求内容（控制台里的）截图对比一下吗？
