### ISSUE TITLE
[BUG]进入【测试跟踪】-【测试计划】，标记用例执行结果，点击其他窗口，未提示保存，导致用例执行结果记录丢失。

### ISSUE THREAD

**Issue by MoliTest** [metersphere/metersphere#7831]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.14.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  进入【测试跟踪】-【测试计划】
2.  进入脑图用例，标记用例执行结果
3.  点击其他窗口，未提示保存，导致用例执行结果记录丢失。
4. 

**期待的正确结果**

正确情况下应该是什么样的？能自动保存执行结果，或者未保存，进入其他页面、退出等都要有保存提示。

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4版本已修复
