### ISSUE TITLE
[BUG] 设计脑图用例时，写好三条用例，复制第一条用例到底部，或者拖动用例顺序，有很大概率会导致用例丢失。

### ISSUE THREAD

**Issue by MoliTest** [metersphere/metersphere#7832]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.14.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG] 设计脑图用例时，写好三条用例，复制第一条用例到底部，或者拖动用例顺序，有很大概率会导致用例丢失。

**期待的正确结果**

正确情况下应该是什么样的？能自动保存执行结果，或者未保存，进入其他页面、退出等都要有保存提示。

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，复现概率有多大呢？
