### ISSUE TITLE
[BUG]json入参含数组时mock自定义脚本匹配成功后无返回值

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#7835]
**MeterSphere 版本**
1.14.2

**Bug 描述**

设置好mock脚本返回入参中数组部分的值，调用mock匹配成功返回值为空。尝试过不含数组时这个功能是正常的

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

能够正常获取数组中的参数

**截图**
![image](https://user-images.githubusercontent.com/40912823/142363743-d38d0e35-9683-4389-9d8d-8d7e0df3646c.png)入参
![image](https://user-images.githubusercontent.com/40912823/142363817-3b14fe90-08a2-47b0-82a9-7078b6b89705.png)
自定义脚本

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.1已修复

**Comment by wszbc** [comment]
> 1.15.1已修复

rows数组可以输出出来了，但是rows[0].whouse依旧无法获取到

**Comment by zyyfit** [comment]
> > 1.15.1已修复
> 
> rows数组可以输出出来了，但是rows[0].whouse依旧无法获取到

您好，您这个请求体是多层json，我们的示例代码已经进行了变更，获取多层json的变量需要这样写 
![图片](https://user-images.githubusercontent.com/73461316/146865470-b817399a-0740-4351-a3fd-8805e4578d07.png)
