### ISSUE TITLE
[BUG]新增一个接口，点击测试后，界面一直 load，也未提示超时

### ISSUE THREAD

**Issue by JimmyWm0517** [metersphere/metersphere#7848]
**MeterSphere 版本**

版本:   v1.14.2-524673ad

**Bug 描述**

WebSocket connection to 'ws://XXXX/api/definition/run/report/2e29c9c2/run' failed:
![image](https://user-images.githubusercontent.com/94614101/142409248-eef0c520-5e79-4b5d-9e02-39068bb48f5d.png)

**Bug 重现步骤**

1.  配置了项目域名
2. 编辑一个接口
3. 选择 "TEST" tab
4. 点击测试
5. 
![image](https://user-images.githubusercontent.com/94614101/142409461-1f9cd494-0b09-44fd-b810-f41106768e13.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们使用了 websocket 来传输结果数据，该问题大概率是由于使用了 nginx、haproxy 等反向代理但没有配置 websocket 支持。
请参考文档 https://metersphere.io/docs/installation/online_installation/#_2 修改下对应配置后再试一下。

**Comment by JimmyWm0517** [comment]
> 你好，我们使用了 websocket 来传输结果数据，该问题大概率是由于使用了 nginx、haproxy 等反向代理但没有配置 websocket 支持。 请参考文档 https://metersphere.io/docs/installation/online_installation/#_2 修改下对应配置后再试一下。

多谢回复，我看下文档

**Comment by windyoung1990** [comment]
@JimmyWm0517 老哥  websocket连接失败的问题解决了没？我们现在把项目做了前后端分离，devServer代理的websocket，在快速调试和编辑运行的时候都可以正常连接返回。直接连webSocket的只有快速调试能连通，编辑下不行。
