### ISSUE TITLE
[BUG]Json 提取出数组，用${XX_ALL} 无法引用

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7849]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.2
**Bug 描述**
son 提取出数组，用${XX_ALL} 无法引用
简要描述您碰到的问题

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/30038088/142410450-ed12003e-39b6-4da8-b4f5-66151fbd5017.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
@wangzhen-fit2cloud

**Comment by zyyfit** [comment]
您好，目前不支持全部引用，只支持id_1这种单个变量引用

**Comment by zyyfit** [comment]
1.15.0已修复
