### ISSUE TITLE
[BUG]接口测试批量添加参数请求会带%0D或换行导致请求失败

### ISSUE THREAD

**Issue by mbsunflower** [metersphere/metersphere#7853]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14.2

**Bug 描述**
接口测试post和get请求批量添加参数，发送请求时在请求内容中查看，请求参数会带%0D或换行，导致请求失败

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口测试，传递post请求，请求体x-www-form-urlencoded，选择批量添加参数，发送请求后，在请求内容中查看，post data包含了%0D。响应代码返回500,。如果不使用批量添加参数，逐个添加参数时，发送请求响应正常。
![1](https://user-images.githubusercontent.com/48192187/142525539-8e39e1cc-187b-4134-9474-96625d66ad30.png)
![2](https://user-images.githubusercontent.com/48192187/142526744-92cb295c-5486-4a5c-9d2f-920dc1e02dad.png)

2.接口测试中，传递get请求，在 QUERY参数中选择批量添加参数，有同样的问题，发送请求后在请求内容中可以看到，请求url中有换行。如果不使用批量添加参数，逐个添加参数时，发送请求响应正常。

**期待的正确结果**
批量添加的参数应该处理换行符，发送请求时不应该受到换行符的影响
正确情况下应该是什么样的？
![3](https://user-images.githubusercontent.com/48192187/142528934-a3dc6f5f-d07b-4f98-96e0-5f751e63ebf9.png)

**Comment by mbsunflower** [comment]
您好，批量添加时通过键盘输入回车发送请求没有问题。通过编辑器如：记事本，notpad等批量复制粘贴进去，发送请求后有问题。
详细请见附件录屏


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 晚上6:48
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口测试批量添加参数请求会带%0D或换行导致请求失败 (Issue #7853)





 
您好，没有复现这个问题，请问能稳定复现吗？方便把您批量添加时填写的参数复制过来吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mbsunflower** [comment]
您好，和请求的参数没有关系，批量添加时在批量添加的窗口里通过键盘输入回车发送请求没有问题。通过编辑器如：记事本，notpad等批量复制粘贴进去，发送请求后有问题。

**Comment by zyyfit** [comment]
好的，感谢反馈

**Comment by zyyfit** [comment]
1.15.0已修复
