### ISSUE TITLE
[BUG]嵌套引用场景案例测试计划执行步骤有缺失，引用和复制，禁用和启用都反过来了

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#7854]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

v1.14.2-524673ad

**Bug 描述**
在列表里点执行，执行步骤有缺失，引用的变成了可编辑，复制的变成不可编辑；
禁用的启用了，没禁用的缺失了。具体的见下面截图

但在场景里面点调试执行，结果是正确的

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

如果有截图，请附上截图.
1.场景列表点执行，步骤缺失，且禁用的被启用了
![image](https://user-images.githubusercontent.com/86302975/142537957-b4032078-509f-40b6-a625-3e9938bdf18c.png)

2. 场景里面点调试执行是对的
![image](https://user-images.githubusercontent.com/86302975/142539154-2d6505ce-3f38-43d4-855e-7e1c188cc421.png)

**Comment by youliyuan-fit2cloud** [comment]
您好，没有复现该问题，请尝试下是否必现？谢谢
