### ISSUE TITLE
[FEATURE]同步Jira的测试用例到MS平台

### ISSUE THREAD

**Issue by xiongxiaoqing0614** [metersphere/metersphere#7860]
**请描述您的需求或者改进建议.**
同步Jira的测试用例到MS平台，可以导入Jira上的测试用例到MS并保持同步，测试计划，执行状态等信息也可以同步

**请描述你建议的实现方案**
调用Jira API实现同步

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研
