### ISSUE TITLE
[BUG]修改执行失败的通知人邮箱后，试了下还是发给了旧的接收人

### ISSUE THREAD

**Issue by lingsoul** [metersphere/metersphere#7867]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.1-22e8e5f0

**Bug 描述**
组织-消息设置-接口自动化，新增事件：执行失败的通知人邮箱后，试了下还是发给了旧的接收人

简要描述您碰到的问题

**Bug 重现步骤**

1、接口自动化事件，配置执行失败、邮件通知从A、B修改成A、B、C，只会通知A、B；
2、再修改配置执行失败、站内通知从A、B修改成A、B、C后，才会正常邮件通知A、B、C；

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/22099083/142570993-64aeaebb-d5ec-4aed-8dfd-5b4e4c0a84f5.png)

**Comment by zyyfit** [comment]
您好，最新版1.14.2没有复现这个问题，建议您升级到最新版使用
