### ISSUE TITLE
在功能用例下的回收站删除一条记录，全部记录下的数量也减1

### ISSUE THREAD

**Issue by longjdong** [metersphere/metersphere#7869]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.4.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  测试跟踪->功能用例，进入功能测试用例页
2. 点击回收站，选择一条记录删除

**期待的正确结果**

正确情况下应该是什么样的？
删除回收站下的记录，不应该影响到全部用例的数量的

**截图**
![1637301403(1)](https://user-images.githubusercontent.com/61893209/142572829-eed4dcd3-914a-43b6-9fe8-163e0474dd15.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，会尽快修复该问题
