### ISSUE TITLE
[BUG]接口测试中key-value形式的请求体，发送请求数据不正常

### ISSUE THREAD

**Issue by heartsmoking** [metersphere/metersphere#787]
**MeterSphere 版本**
版本: v1.4.2-b1039

**Bug 描述**
接口测试中key-value形式的请求体，发送请求数据不正常

**Bug 重现步骤**
1.  添加接口测试
2. 添加key-value形式的请求体
3. 调试，发起请求

**期待的正确结果**
能正常发送请求体类似于key1=value1&key2=value2这样的形式

**实际结果**
目前发送的请求体是value1value2

**截图**
![image](https://user-images.githubusercontent.com/28750741/99754848-461c2a00-2b24-11eb-8f06-bee7f04a3e64.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中未复现该问题，请升级到 1.4.3 版本验证下，如果问题仍然存在，请重新打开下该 issue
