### ISSUE TITLE
[BUG]脑图形式导入的功能用例，导入正常，创建测试计划，关联 脑图导入的用例，在测试计划-功能用例列表显示为空，脑图显示正常，点击执行报告信息无用例信息。

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7871]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.2
**Bug 描述**

简要描述您碰到的问题
脑图形式导入的功能用例，导入正常，创建测试计划，关联 脑图导入的用例，在测试计划-功能用例列表显示为空，脑图显示正常，点击执行报告信息无用例信息。
**Bug 重现步骤**

1.  脑图形式导入的功能用例，导入正常
2. 创建测试计划，关联 脑图导入的用例，在测试计划-功能用例列表显示为空，脑图显示正常
![image](https://user-images.githubusercontent.com/30038088/142573735-d76d11c2-0142-4662-9bcf-88f0f4ecbffc.png)
![image](https://user-images.githubusercontent.com/30038088/142573734-8672557c-d5c4-4e4d-adba-2d4efaa84083.png)

3.执行报告信息无用例信息
![image](https://user-images.githubusercontent.com/30038088/142573776-66949ac4-fd47-4367-aaa9-f03133c4aa5f.png)

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
[Uploading Metersphere_case_33333 (2).xmind.zip…]()

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/7818

**Comment by zyyfit** [comment]
1.14.3已修复

**Comment by longjdong** [comment]
此BUG在后面的最新版本中（1.14.3, 1.15.1, 1.15.2）都复现，是否真处理好

**Comment by youliyuan-fit2cloud** [comment]
v1.15.2 真没复现，

> 



> 此BUG在后面的最新版本中（1.14.3, 1.15.1, 1.15.2）都复现，是否真处理好

我们没复现，方便把xmind用例文件发一下吗?

**Comment by zeeyuyang** [comment]
我也遇到相同的问题了
![image](https://user-images.githubusercontent.com/38879921/144958649-811d755b-8274-405d-b09f-81f6ccaf637d.png)
![image](https://user-images.githubusercontent.com/38879921/144958726-e112a34b-f13e-4203-a856-c98b5541c2fa.png)

**Comment by zyyfit** [comment]
@zeeyuyang  你这个是哪个版本呀？方便把用例导出来给我们看一下吗？导一份excel一份xmind吧

**Comment by zeeyuyang** [comment]
[测试用例.zip](https://github.com/metersphere/metersphere/files/7666478/default.zip)

我批量xmind导入的测试用例关联到测试计划中列表模式不显示，但是我刚才试了一次用表单格式新增一条测试用例再关联到测试计划中，新增的这条是可以展示的，用例都放在压缩文件中了，期待回复

**Comment by zeeyuyang** [comment]
检测当前版本为v1.15.3
重新升级了应用至最新版本，依然有这个问题

> [测试用例.zip](https://github.com/metersphere/metersphere/files/7666478/default.zip) 版本是v1.14.2 我批量xmind导入的测试用例关联到测试计划中列表模式不显示，但是我刚才试了一次用表单格式新增一条测试用例再关联到测试计划中，新增的这条是可以展示的，用例都放在压缩文件中了，期待回复

**Comment by zyyfit** [comment]
> 检测当前版本为v1.15.3 重新升级了应用至最新版本，依然有这个问题
> 
> > [测试用例.zip](https://github.com/metersphere/metersphere/files/7666478/default.zip) 版本是v1.14.2 我批量xmind导入的测试用例关联到测试计划中列表模式不显示，但是我刚才试了一次用表单格式新增一条测试用例再关联到测试计划中，新增的这条是可以展示的，用例都放在压缩文件中了，期待回复

您好，我导入后没有出现这个问题，您重新导入一下试试？

**Comment by zeeyuyang** [comment]
> 您好，我导入后没有出现这个问题，您重新导入一下试试？

升级后把原来的用例移除，重新导入用例，就没有这个问题了

**Comment by zyyfit** [comment]
> 

收到，感谢
