### ISSUE TITLE
[BUG] “同步缺陷”导致bug数据丢失

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#7877]
**MeterSphere 版本**

 1.14.2

**Bug 描述**

点击“同步缺陷”，同步禅道的缺陷，发现metersphere的缺陷的描述会丢失。

**Bug 重现步骤**

（1）在metersphere新建缺陷，推送禅道，正常；
（2）在禅道修改缺陷；
（3）在metersphere点击同步缺陷，打开缺陷，里面的描述为空；

正确情况下应该是什么样的？

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复

**Comment by zyyfit** [comment]
1.14.3已修复

**Comment by chenlq618** [comment]
刚测试了，缺陷仍存在

**Comment by youliyuan-fit2cloud** [comment]
v1.16.0版本已修复
