### ISSUE TITLE
[FEATURE]测试用例的思维导图，希望能实时同步

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#7878]
**请描述您的需求或者改进建议.**
测试用例的思维导图，希望能实时同步；
有时，写了一天的测试用例，忘记点击保存（或者刷新了浏览器），那一天的成果就会丢失

**请描述你建议的实现方案**

**Comment by chenlq618** [comment]
![image](https://user-images.githubusercontent.com/7685661/142718441-10020bb3-d946-4729-be42-3b8318dba652.png)
我通过脑图写测试用例，如果忘记点击保存，刷新页面/关闭浏览器/电脑没电等都会导致数据丢失。
希望每个操作都自动保存，而不是等点击保存才触发保存

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。目前我们在切换页面会检测当前页面是否未保存并提示。
