### ISSUE TITLE
[FEATURE]缺陷管理增加状态和评论功能

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#7879]
**请描述您的需求或者改进建议.**

1、在缺陷管理页面新增bug状态筛选功能；
2、在缺陷管理列表页面修改BUG状态；
3、在缺陷管理里面增加评论功能；
4、在缺陷管理页面增加BUG重复打开的次数统计；

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/80370956/142585006-e824725c-f56d-4c42-9a98-f3dfe6410ee5.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下调研
