### ISSUE TITLE
[FEATURE]接口测试编辑场景时，添加自定义变量希望能通过脚本添加

### ISSUE THREAD

**Issue by heartsmoking** [metersphere/metersphere#788]
**请描述您的需求或者改进建议.**
希望自定义变量可以编写一个脚本（py或者beanshell都可以）来添加一些需要通过内置变量无法取得的变量值

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，现在可以通过前后置脚本的方式来设置变量的
