### ISSUE TITLE
[BUG]发起的通过url传参的get请求时，有多出了"content-type":"text/plain; charset=UTF-8"这一个请求头

### ISSUE THREAD

**Issue by z-yuxie** [metersphere/metersphere#7881]
**MeterSphere 版本**
v1.14.1-811e3e3b、v1.14.2-524673ad

**Bug 描述**
界面位置："接口测试">"接口定义">"快捷调试"
通过上述界面创建的http GET请求，并使用类似https://a.b.c/api?aa=param1&ab=param2&ac=param3&ad=param4&ae=param5 的格式传参，发起测试后，该请求实际到达被测接口时，被测接口接到的http请求头中多出了"content-type":"text/plain; charset=UTF-8"这一个请求头

**Bug 重现步骤**

1.  进入到界面的如下位置："接口测试">"接口定义">"快捷调试"
![image](https://user-images.githubusercontent.com/28329410/142585128-4b7ebf37-fdd5-43eb-878e-386c58dca8fe.png)
2.  选择“GET”请求，并填入类似如下URL：https://a.b.c/api?aa=param1&ab=param2&ac=param3&ad=param4&ae=param5
3.  界面自动对第2步的URL解析后
![image](https://user-images.githubusercontent.com/28329410/142585732-390133f2-71ac-4edd-9235-0a5a04499c2c.png)
4. 点击界面的“测试”按钮发起测试，界面显示的实际发起的请求信息如下：
![image](https://user-images.githubusercontent.com/28329410/142587963-2bb4293b-9131-46a3-bcda-d97464f9eedc.png)

期望结果：
通过该界面定义的通过URL传参的GET请求，不会被添加额外的请求头

**Comment by youliyuan-fit2cloud** [comment]
没有复现这个问题呢

**Comment by z-yuxie** [comment]
@youliyuan-fit2cloud 我这边重新用抓包工具试了下，发现问题等位的有点问题，就实际上确实并没有添加“application/json”，但问题实际上确实也和Content-Type这个请求头有关系，目前我用postman模拟了一下，发现是meterSphere的界面在发起请求的时候默认带的"Content-Type":"text/plain; charset=UTF-8"导致的，我是用postman或者curl命令发起Get请求的时候，都是没有这个请求头的，这种情况下我们的被测接口（后台springboot工程）是不会提示错误的，但一旦把这个请求头加上，就会提示错误

**Comment by youliyuan-fit2cloud** [comment]
v1.14.3版本已修复

**Comment by z-yuxie** [comment]
谢谢，辛苦了~~
