### ISSUE TITLE
[BUG] 接口测试下出现页面错乱

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#7884]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

V1.14.2

**Bug 描述**
点击接口测试下的测试报告，然后再刷新整个页面 ，就会出现下方截图中的内容：

![image](https://user-images.githubusercontent.com/32027713/142600479-eb56ec2a-163e-4ee2-8d20-f2777e1aef03.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
