### ISSUE TITLE
[BUG] 采用插件管理下的插件编辑好的场景批量执行放入Node-controller，出现不执行的状况

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#7885]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.14.2

**Bug 描述**
采用插件管理下的插件编辑好的场景批量执行放入Node-controller，出现不执行的状况， 报告内容也为空

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/32027713/142601087-5f144887-79de-466f-920c-c84c36c6324b.png)

![image](https://user-images.githubusercontent.com/32027713/142601194-3d79869c-6b7e-40e8-9ccc-8eb188a6e411.png)

![image](https://user-images.githubusercontent.com/32027713/142601240-a2f16429-1ad6-437d-ab59-2f1134531ca8.png)

**Comment by fit2-zhao** [comment]
下个小版本修复
