### ISSUE TITLE
[BUG]接口测试-接口自动化：接口使用参数提取 正则：Response Headers 提取的参数，无法传递到一下一个步骤

### ISSUE THREAD

**Issue by tuheishan** [metersphere/metersphere#7886]
**MeterSphere 版本**
版本:   v1.14.2-524673ad
您所使用的 MeterSphere 版本是？
版本:   v1.14.2-524673ad
**Bug 描述**
接口测试-接口自动化：接口使用参数提取 正则：Response Headers 提取的参数，无法传递到一下一个步骤

**Bug 重现步骤**

1.  新建场景用例
2. 导入接口
3. 添加提取参数
4. 选择正则，选择 Response Headers 提取 Set-Cookie 列表
5. 再添加一个接口步骤（需要传入4步骤提取的变量才可以调用成功）
6. 接口调用成功

**期待的正确结果**

正确情况下应该是什么样的？

步骤中使用参数提取的变量，应该在场景用例所有步骤中都可以使用

**截图**
![image](https://user-images.githubusercontent.com/48342319/142601418-c3552c59-bf61-4882-a1a0-16fe43985564.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，正则提取后，下一个步骤中引用正确吗？

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，正则提取后，下一个步骤中引用正确吗？

**Comment by tuheishan** [comment]
补上细节：
1、在场景变量里设置全局请求头：
![image](https://user-images.githubusercontent.com/48342319/142711387-1a9362e7-6b01-4550-ad8a-565fadd8098e.png)
2、第1个步骤提取 Response Headers 中的参数，勾选匹配多条
![image](https://user-images.githubusercontent.com/48342319/142711261-8d07ff4c-0ac2-4fc0-9da9-88dbc02b6ba4.png)
3、下一个步骤调用（请求失败，这里使用的是场景变量的值，也可以直接在请求赋值变量不使用场景变量，效果一致）
![image](https://user-images.githubusercontent.com/48342319/142711372-42efd000-4d3b-4c1b-8889-396e5734795b.png)

**Comment by youliyuan-fit2cloud** [comment]
请看下步骤1中是否提取到了这个cookie，提取表达式不太对吧

**Comment by fit2-zhao** [comment]
@tuheishan  你好，匹配多条是个变量数组应该是 a_1 || a_2 这种使用方式。

**Comment by tuheishan** [comment]
> @tuheishan 你好，匹配多条是个变量数组应该是a_1 || a_2我们使用方式。

我需要拿取一个数组，用什么语法呢

**Comment by tuheishan** [comment]
> > @tuheishan 你好，匹配多条是个变量数组应该是a_1 || a_2我们使用方式。
> 
> 我需要拿取一个数组，用什么语法呢

因为这个问题是在升级1.14.2后产生的，在1.12.1 中的用例执行失败了，排查后发现是这个问题导致的。

**Comment by youliyuan-fit2cloud** [comment]
> > > @tuheishan 你好，匹配多条是个变量数组应该是a_1 || a_2我们使用方式。
> > 
> > 
> > 我需要拿取一个数组，用什么语法呢
> 
> 因为这个问题是在升级1.14.2后产生的，在1.12.1 中的用例执行失败了，排查后发现是这个问题导致的。
类似这样 ${cookie_1}
