### ISSUE TITLE
[BUG]点开执行中的测试计划日志，展示的是之前的旧数据

### ISSUE THREAD

**Issue by tuheishan** [metersphere/metersphere#7888]
**MeterSphere 版本**

 v1.14.2-524673ad

**Bug 描述**

简要描述您碰到的问题

点开执行中的测试计划日志，展示的是之前的旧数据

**截图**
![image](https://user-images.githubusercontent.com/48342319/142611246-227bbbee-ec87-40bf-b467-e3054df43cf9.png)
![image](https://user-images.githubusercontent.com/48342319/142611376-d1130dd6-75f5-45c5-918e-73a525723ff7.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.0已修复
