### ISSUE TITLE
[FEATURE]管理列表的分页默认5条/页太不友好了

### ISSUE THREAD

**Issue by zh417233956** [metersphere/metersphere#789]
**改进建议**
列表分页默认:5条/页体验太不友好了.能否默认设置为20条/页

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你那边是什么版本，现在默认是 10条/页的，可以升级下版本再试下

**Comment by zh417233956** [comment]
@wangzhen-fit2cloud 我用的是当前的最新版本:v1.4.3

**Comment by zh417233956** [comment]
> 你好，请问你那边是什么版本，现在默认是 10条/页的，可以升级下版本再试下

用的最新版本:v1.4.3

**Comment by wangzhen-fit2cloud** [comment]
> > 你好，请问你那边是什么版本，现在默认是 10条/页的，可以升级下版本再试下
> 
> 用的最新版本:v1.4.3

具体是哪个页面呢，可以截图看一下吗

**Comment by zh417233956** [comment]
> > > 你好，请问你那边是什么版本，现在默认是 10条/页的，可以升级下版本再试下
> > 
> > 
> > 用的最新版本:v1.4.3
> 
> 具体是哪个页面呢，可以截图看一下吗
接口测试/性能测试/系统设置下的列表几乎都是5条/页
![metersphere-pagesize-issue](https://user-images.githubusercontent.com/22386206/100405145-f8f90480-309d-11eb-9ece-ef2eb51e3805.png)
