### ISSUE TITLE
[BUG]添加断言时选择文本，增加后的断言类型为正则

### ISSUE THREAD

**Issue by zhaoxu5534** [metersphere/metersphere#79]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.0
**Bug 描述**
简要描述您碰到的问题
添加断言时选择文本，增加后的断言类型为正则
**Bug 重现步骤**
1.  接口测试，添加断言
2. 选择文本，点击加号
3.  添加后的断言类型为正则
4. 

**期待的正确结果**
正确情况下应该是什么样的？
选择文本，则增加的断言类型为文本
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/66238336/86339693-7737b300-bc86-11ea-9fd8-3431fc22b0f1.png)
![image](https://user-images.githubusercontent.com/66238336/86339703-7c94fd80-bc86-11ea-9d9a-1a5ee0967095.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，这里的功能就是这样设计的，提供文本的方式方便对正则表达式不熟悉的人来添加断言，但是实际生效的化也是通过正则的方式来进行文本匹配。
