### ISSUE TITLE
[性能测试]建议增加与断言不一致的响应数据内容显示

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#792]
**请描述您的需求或者改进建议.**
断言是jmx里面的断言设置
1.压测中发生错误码：20500，或20001，504，空指针等异常的错误信息不能直观在线查看，根本不知道具体错误是什么；
如果能直观查看，那么解决很多时间来分析，性能测试灵魂重要指标信息，建议尽快加上吧！

**请描述你建议的实现方案**
脚本jmx不一致的断言响应返回打印显示在type of erro处
![image](https://user-images.githubusercontent.com/43331464/99766865-ed0cc000-2b3c-11eb-80fe-63a0c9bec066.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，目前这里担心将所有错误信息都上传处理的话数据量会比较大，我们需要再想一下如何处理比较好。

**Comment by 52testing** [comment]
@wangzhen-fit2cloud 想了解一下现在是什么情况了，比较关心，因为压测时候不能看到与预期不一样的错误信息返回，已经无法在ms上测试了。

**Comment by 52testing** [comment]
我们在使用jmeter压测负载测试时候，使用beanshell判断输出不一样的断言到text时候，压力机请求性能会下降30%；

**Comment by wangzhen-fit2cloud** [comment]
这里可能会考虑增加采样日志的方式来支持查看某些请求详情的场景
