### ISSUE TITLE
[FEATURE]接口测试可优化

### ISSUE THREAD

**Issue by Neil521** [metersphere/metersphere#7926]
**请描述您的需求或者改进建议.**

接口测试新建时默认get方法,body为text格式,需支持用户自定义方案,按用户自定义喜好新增.比如新增时设置post方法,json格式

**请描述你建议的实现方案**
设置中 可以加一个对新增接口时的内容

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能我们暂时没有规划。
