### ISSUE TITLE
[BUG]新建接口的编辑模块无法关闭关闭

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#7933]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
14.2
**Bug 描述**

简要描述您碰到的问题
新建接口的编辑模块无法关闭关闭
**Bug 重现步骤**

1.  新建接口，点击保存
2. 切换到其他窗口5分钟
3. 再切回新建接口窗口
4. 点击关闭标签

**期待的正确结果**

正确情况下应该是什么样的？
标签关闭
**截图**

如果有截图，请附上截图.
![图片](https://user-images.githubusercontent.com/36387811/142796738-9f4854b6-fc70-497f-944f-97bdaa80f88a.png)

**Comment by zyyfit** [comment]
您好，这个是已知问题，正在修复中
相关问题 https://github.com/metersphere/metersphere/issues/7660

**Comment by zyyfit** [comment]
1.15.1已修复
