### ISSUE TITLE
[FEATURE]消息邮件通知优化

### ISSUE THREAD

**Issue by littlelilyjiang** [metersphere/metersphere#7934]
**请描述您的需求或者改进建议.**
消息邮件通知希望能优化
1. 邮件只在内容部分说明了接口测试的成功失败，希望可以在标题提供成功失败的说明
2. 邮件内容可以更具体一点，而不是只有一个成功失败的说明，可以精确到一共多少个接口，成功多少个失败多少个，可以把测试报告附在邮件之中，而不是每次必须要跳转到MS系统去进行查看

**Comment by zyyfit** [comment]
感谢反馈，我们先内部讨论一下这个问题，另外 我们的企业版中有消息通知模板配置功能，支持自定义配置消息通知模板

**Comment by luty2018** [comment]
非常抱歉现在才回复。
这个功能已经支持了，建议更新到v2.7版本使用。

**Comment by littlelilyjiang** [comment]
@luty2018 已经更新到v2.7了 但是具体怎么使用有路径说明或者文档说明吗  暂时没有找到具体的入口 可以麻烦告知一下吗 感谢
