### ISSUE TITLE
[性能测试]压力配置中的运行模式

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#794]
版本: v1.4.3-b1050
一.目前测试过程中只有负载测试设置，不能进行多场景设置；
我的常用jmx需求场景：
1.按照线程组顺序执行并发测试（按照用户行为操作）
2.负载测试（已有）
3.只并发测试一次，并发为1秒，没有1s的，并不需要运行xx分钟；如秒杀系统，电商等大压力系统；
目前感觉并发的能力运行很慢？感觉运行，测试，收集信息后，感受不到平台是否是在时间内做到了真正的压力负载？
可能目前的性能方面需要优化，快速度的机制；不能让平台消耗资源太大，卡壳影响了实际测试场景真实性！

二.要么有个选择的模式，直接按照我的jmx运行顺序和模式场景运行，meterspere只管调用。

![image](https://user-images.githubusercontent.com/43331464/99767825-ac15ab00-2b3e-11eb-94c6-7eb9abe9b363.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在 v1.5 版本中会有如下修改
- 压力配置时间单位改为秒
- 分线程组(场景)设置并发参数
