### ISSUE TITLE
[FEATURE] 通过增加筛选功能优化缺陷列表展示

### ISSUE THREAD

**Issue by vast0906** [metersphere/metersphere#7957]
**请描述您的需求或者改进建议.**
增强缺陷管理列表筛选功能

**请描述你建议的实现方案**

![image](https://user-images.githubusercontent.com/18095287/142829860-d2a0a501-ab13-4251-bc57-0a2bac055798.png)

默认打开缺陷管理后  会有大量的缺陷列表展示，随着时间的推移会越来越多，是否有更高效的一些过滤手段进行筛选呢？
项目 A 下有 abc 三个模板  每个模块上线前都需要  123 轮测试，如果只能通过名称进行筛选较为低效
是否可以把用户自定义的字段 (绿框的内容) 可以像 平台字段 (红框的内容 )一样 进行筛选

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by luty2018** [comment]
有规划的，目前的设计方案不太好实现，需要整体优化
