### ISSUE TITLE
[BUG]测试跟踪及测试计划页面不响应

### ISSUE THREAD

**Issue by nuanyangxiademao** [metersphere/metersphere#796]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  登录测试平台，点击测试跟踪，查看已维护的用例，多次点击会出现用例无法展示问题（可以重新登录解决这个问题）
2. 登录测试平台，点击测试计划，选择显示全部项目，查询功能的“高级搜索”有时候会不展示（点点其他功能菜单，就会这样。重新登录可以解决这个问题）

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/46918134/99774525-db311a00-2b48-11eb-9a96-40b54d7dae28.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请提供下版本信息，及前后台相关日志
