### ISSUE TITLE
[BUG] tcp接口的请求时间和响应时间不起作用

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#7974]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**
tcp接口的请求时间和响应时间不起作用
<img width="819" alt="2" src="https://user-images.githubusercontent.com/71361375/142958594-63ac1251-cd4e-4387-8574-83332493e080.png">

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.16.0已修复
