### ISSUE TITLE
[BUG]linux关机重启后测试资源池不可用报错“状态修改失败, 校验不通过!”

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#798]
版本: v1.4.3-b1050
1.之前是正常使用的，关闭linux主机虚拟机重启后发生的。
2.操作如下
systemctl restart docker
msctl reload
msctl start
msctl status

3.即时删除了重新来也不行，即时重新安装metersphere服务也不行。
无法开启测试资源池

服务状态如下：
![image](https://user-images.githubusercontent.com/43331464/99783880-fd7d6480-2b55-11eb-9668-c85f3a1ecb38.png)

**Comment by 52testing** [comment]
已解决：填写问题，本机填写ms-node-controller
填写IP也可以
![image](https://user-images.githubusercontent.com/43331464/99786976-1be55f00-2b5a-11eb-8505-41e9816dee59.png)

**Comment by Jayla110** [comment]
我也遇到了这个问题，改了ip和port同样解决了，感谢！
