### ISSUE TITLE
[BUG]同步缺陷功能（同步禅道的缺陷）会导致缺陷数据丢失

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#7982]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
metersphere版本：v1.14.3
禅道版本： 12.5.3 开源版

**Bug 描述**

简要描述您碰到的问题
同步禅道的缺陷，导致数据丢失（特别是有图片的情况）

**Bug 重现步骤**

1.  在metershpere新增缺陷，能同步的禅道
2.  点击同步缺陷后，图片不见了

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/7685661/142966898-df520c9e-570b-4faf-bfaa-1f08500e03f4.png)
![image](https://user-images.githubusercontent.com/7685661/142966956-ada5249f-06f6-470b-8571-184f3c4acc37.png)

**Comment by youliyuan-fit2cloud** [comment]
已知问题，后续版本会优化

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
