### ISSUE TITLE
[BUG]功能用例中同时打开多个用例,保存最开始打开的用例时,页面渲染标题重复

### ISSUE THREAD

**Issue by elviszy** [metersphere/metersphere#7986]
**MeterSphere 版本**

1.14.3

**Bug 描述**

功能用例中同时打开多个用例,保存最开始打开的用例时,页面渲染标题重复

**Bug 重现步骤**

1.  进入功能用例页面
2. 同时打开2个用例编辑
3. 回到最开始打开的用例,按CTRL+S保存
4. 页签头渲染不正确

![image](https://user-images.githubusercontent.com/26116509/142969315-e72f81de-1df3-4274-a47e-68d4f6e54567.png)
![Uploading image.png…]()

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
发现了。。。下个版本修复，感谢👍

**Comment by zyyfit** [comment]
1.15.0已修复
