### ISSUE TITLE
[BUG]面包屑导航栏点击全部用例之后，显示不正常。

### ISSUE THREAD

**Issue by hongjojjay** [metersphere/metersphere#799]
**MeterSphere 版本**
1.4.3

**Bug 描述**
面包屑导航栏点击全部用例之后，显示不正常。

**Bug 重现步骤**
1.  点击菜单栏--->测试用例\显示全部
2.  创建模块USB
3.  创建USB子模块USB_tg1
4.  创建USB_tg1子模块USB_tp1
5.  给USB_tp1创建两条用例，play和previous
6.  创建USB_tp1子模块USB_tp1_tc1
7.  给USB_tp1_tc1创建五条用例
8.  面包屑导航栏点击全部用例，显示的是USB_tp1_tc1的五条用例。再点击一次全部用例，才显示真正的7条用例。

**期待的正确结果**
在面包屑导航栏第一次点击全部用例，显示的应该是所有的用例，而不是USB_tp1_tc1的五条用例。

**截图**
如果有截图，请附上截图.

**Comment by shiziyuan9527** [comment]
已修复
