### ISSUE TITLE
[QUESTION] 接口自动化里if及while判断中是否有in选项？

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#7990]
接口自动化里if及while判断中的**“包含”**选项和in是否一致？
比如判断参数 a 是否是1，2，3中的一个值 ${a} in ('1','2','3') 。
 如果含义不一致，应该如何写if及while条件表达式？

**Comment by wangzhen-fit2cloud** [comment]
你好，包含指的是字符串包含，例如 a="hello" 包含 "el"。
目前还不能直接提供类似 python 中的 in 语法。

**Comment by tangw1257** [comment]
后续是否可以增加这种类型，   同时还包括大于等于 、小于等于
