### ISSUE TITLE
接口测试测试项多了后无报告

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#8]
1.测试接口如图
![image](https://user-images.githubusercontent.com/30932762/84640481-505e4a80-af2c-11ea-85dc-594853540565.png)
2.无返回界面
![image](https://user-images.githubusercontent.com/30932762/84640422-3d4b7a80-af2c-11ea-95e0-c2cf2140b57d.png)
3.实际接口测试已经生效

**Comment by q4speed** [comment]
浏览器的控制台是否有错误信息，如果有，打出来看一下。
