### ISSUE TITLE
[QUESTION]我们准备使用MeterSphere接入API测试的CI遇到的一些困惑，求推荐用法。

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#801]
metersphere使用api测试，MS是否有推荐的CI用法。（我们项目的case量会比较大）
我个人觉得api测试应该是：
1，每个项目有很多测试用例和用例集，放在用例库中。比如一个项目有2000个case，其中有单接口用例，有场景用例等
2，可以创建某些测试聚合规则，从测试用例库中选一批用例、用例集。比如 CI-测试环境测试， CI-预发布环境测试
3，真正运行测试用例或者用例集后，会生成测试历史。
我现在的困惑：
1， MS好像没有用例库的概念，一键执行后，一键执行的内容成了一个用例集了。
2，MS接CI这块，用例是否有推荐做法。
3，好像没有整体状态，比如一共有多少项目，每个项目有多少API，有多少case，历史测试信息不同维度的统计
4，测试场景B，引入的已有测试A，测试A修改后，好像场景B中引用的内容不会跟着变。如果有很多场景引用的测试A，测试A有调整，这些场景可能会有问题吧。

**Comment by wangzhen-fit2cloud** [comment]
你好，我们在 12月底的 v1.6 版本中会进行比较大的改动，会区分单接口用例、接口自动化场景，目前可以通过创建多个接口测试，在测试计划中添加用例关联接口测试，在 Jenkins 任务中选择测试计划执行的方式。
