### ISSUE TITLE
[BUG] 添加sql自定义请求-》未保存状态下，无法引用环境里配置的全局变量

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#8016]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.14.3

**Bug 描述**

添加sql自定义请求-》未保存状态下，无法引用环境里配置的全局变量

**截图**

![image](https://user-images.githubusercontent.com/32027713/142998241-e838a303-4b40-4577-b656-515e91a4af14.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.2已修复
