### ISSUE TITLE
[BUG]操作一个用例失败后会导致其他没有操作过的用例也是失败状态

### ISSUE THREAD

**Issue by zhu026** [metersphere/metersphere#803]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.4.3-b1050
**Bug 描述**
简要描述您碰到的问题
当一个测试计划包含两个用例的时候，将其中一个用例操作【失败】并提交一个问题。再次进入这个测试计划，看到两个用例都是失败状态
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
没有操作过的用例应该保持初始的状态
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/74893957/99936642-956d8f00-2d9e-11eb-8439-a2f895b58a66.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，我们这边没有复现该问题
