### ISSUE TITLE
[BUG]用例评审模块，测试用例责任人应该展示用户名称，实际展示用户ID

### ISSUE THREAD

**Issue by tianpeng007** [metersphere/metersphere#8045]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

 v1.14.1-12036e57

**Bug 描述**

用例评审模块，测试用例责任人应该展示用户名称，实际展示用户ID

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/68412709/143156105-256fbec3-8963-453e-9c65-2d940c4d2d58.png)

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/68412709/143156187-cb9b1cad-6b47-4e37-9e72-8ab2d98141bb.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化下！

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4版本已修复
