### ISSUE TITLE
分布式部署node压测机，关联的场景接口用例，配置的host解析未生效[BUG]

### ISSUE THREAD

**Issue by chaochaogege** [metersphere/metersphere#8054]
**MeterSphere 版本**
1.14.2
您所使用的 MeterSphere 版本是？

**Bug 描述**
分布式部署node压测机，关联的场景接口用例，配置的host解析未生效
简要描述您碰到的问题

**Bug 重现步骤**

1.  关联接口场景用例
2. 进行压测
3. 高级配置，域名绑定

**期待的正确结果**
不需要配置node节点的host解析
正确情况下应该是什么样的？

结果：
jmeter容器 DNScachemanager 报错
**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，具体是哪个页面的域名绑定，哪个地方不能解析呢？方便发一下截图吗？
