### ISSUE TITLE
[BUG]存量的测试计划在升级新版本之后无法关联测试用例，由“允许关联重复用例”按钮未设置初始化值导致空指针异常

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#8057]
**MeterSphere 版本**

V1.14.3

**Bug 描述**

简要描述您碰到的问题

存量的测试计划在升级新版本之后无法关联测试用例，由“允许关联重复用例”按钮未设置初始化值导致空指针异常

**截图**

![企业微信截图_16376411258637](https://user-images.githubusercontent.com/32027713/143173527-f2470247-e4ba-487a-bcae-ad74c346646f.png)

![image](https://user-images.githubusercontent.com/32027713/143173544-06886168-b262-450d-a337-b18c2e790622.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，没有复现您的问题，请详细描述下是从哪个版本升级到v1.14.3 ？现在是否还存在这个问题？
