### ISSUE TITLE
[BUG] 接口场景下对包含变量的参数进行编码，发现实际发出去的请求并没有吧参数替换后转码，而是直接当做参数了

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#8066]
**MeterSphere 版本**

V1.14.3

**Bug 描述**

接口场景下对包含变量的参数进行编码，发现实际发出去的请求并没有把参数替换后转码，而是直接当做参数了，不编码的话就会替换成实际值

**截图**

如果有截图，请附上截图.
编码：
![image](https://user-images.githubusercontent.com/32027713/143186976-950db67a-2232-4537-b8d5-334196017d6e.png)

未编码：
![image](https://user-images.githubusercontent.com/32027713/143187080-e7a278c7-5ba2-4ad2-8249-a5fb48865468.png)

**Comment by zyyfit** [comment]
1.15.0已修复
