### ISSUE TITLE
[BUG]sql接口定义添加变量和sql，创建用例时显示正常，更新接口变量后，在用例中查看变量和sql丢失

### ISSUE THREAD

**Issue by mbsunflower** [metersphere/metersphere#8082]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14.3

**Bug 描述**

简要描述您碰到的问题
问题及步骤同以往缺陷：
https://github.com/metersphere/metersphere/issues/7532

F12查看有js报错
![js报错](https://user-images.githubusercontent.com/48192187/143196737-905a3009-46db-445f-93b3-e3b28b9bb185.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.2已修复
