### ISSUE TITLE
[BUG][接口测试]sql类型的接口测试，场景中批量选择测试环境后，场景中的sql接口数据源丢失

### ISSUE THREAD

**Issue by mbsunflower** [metersphere/metersphere#8086]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.14.3

**Bug 描述**
sql类型的接口测试，场景中批量选择测试环境后，场景中的sql接口数据源丢失。

简要描述您碰到的问题

**Bug 重现步骤**

1.  项目环境中添加了一个测试环境A，测试环境A中添加了数据源B
2. 新增接口定义SQL类型，选择测试环境A，数据源B，创建用例w
3. 创建场景，引用用例w
4. 在场景中批量选择测试环境A
5. 执行测试error
6. 查看是场景中引用的用例w，数据源为空

正确情况下应该是什么样的？
批量选择测试环境A时，数据源应该自动带出B

**Comment by zyyfit** [comment]
您好，最新版1.15.1没有复现这个问题（虽然数据源名称是空的，但是执行的时候是可以执行的，数据源为空这个问题我们下个版本优化）

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4版本已修复
