### ISSUE TITLE
[FEATURE]希望支持用例评审的评论删除

### ISSUE THREAD

**Issue by pcc426** [metersphere/metersphere#809]
**请描述您的需求或者改进建议.**
目前用例评审时发布的评论不支持发布者删除，希望提供至少让发布者本人删除的功能，这样万一发错了还能及时删除

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，在 v1.4.1 版本中已提供该功能，请升级验证。
