### ISSUE TITLE
[BUG]按场景执行的接口测试，页面不停转圈无响应

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#81]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.0.2

**Bug 描述**
简要描述您碰到的问题
按场景执行的接口测试，页面不停转圈无响应

**Bug 重现步骤**
1.  一个场景一个接口，在场景页面点击保存并执行，页面开始转圈，然后一直转圈
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
正常完成请求

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/86344222-9a656100-bc8c-11ea-8fd9-69a21b7e8af6.png)

**Comment by popolyj** [comment]
![image](https://user-images.githubusercontent.com/12756697/86344420-d7315800-bc8c-11ea-9df7-a75cca2c6f08.png)
最后查看报告，显示的错误信息是超时

**Comment by wangzhen-fit2cloud** [comment]
这个问题有可能是部署 metersphere 的服务器到脚本里指定的 url 网络不通，你可以在服务器上后台测试一下。
我们会在后续的版本中优化一下测试执行时间较长时的页面展示信息。

**Comment by popolyj** [comment]
单接口的，是可以访问通的，只有在这个场景下不行，应该不是网络不通的原因吧
