### ISSUE TITLE
现在测试平台不支持发送测试报告时，把接口的运行结果直观的显示出来

### ISSUE THREAD

**Issue by yangxuepi** [metersphere/metersphere#8109]
**请描述您的需求或者改进建议.**
现在测试平台不支持发送测试报告时，把运行问题直观的显示出来，而不是需要点击链接，并在平台登录后才能看到对应的测试结果呢[FEATURE]

**请描述你建议的实现方案**
建议测试平台能支持发送测试报告时，把运行问题直观的显示出来，而不是需要点击链接，并在平台登录后才能看到对应的测试结果呢[FEATURE]

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研
