### ISSUE TITLE
[BUG]浏览器插件录制的 PATCH 请求缺少 body

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#811]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本1.4.2
**Bug 描述**
简要描述您碰到的问题
在使用插件MeterSphere JMX Recorder 的时候发现获取的Patch请求没有Body
**Bug 重现步骤**
1.  一个Post请求和Patch请求
2. 发现Post能够获取到Body而Patch请求没有Body

**期待的正确结果**
正确情况下应该是什么样的？
Patch和Post都能够获取到Body请求数据
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44960709/100080732-261c9b80-2e81-11eb-8aa1-a3df28d515fb.png)

![image](https://user-images.githubusercontent.com/44960709/100081275-ca064700-2e81-11eb-828e-441dc993d460.png)

**Comment by lingrance** [comment]
![image](https://user-images.githubusercontent.com/44960709/100081247-c4a8fc80-2e81-11eb-90c7-cd15ea6bf2bf.png)

**Comment by q4speed** [comment]
经查询和测试Chrome WebRequest API，目前POST和PUT是可以获取到body的，PATCH无法获取body，因此暂时无法实现这个功能。
