### ISSUE TITLE
用jenkins插件，触发时测试执行方式为执行测试计划中用例测试报告显示不正常

### ISSUE THREAD

**Issue by wangjb0718** [metersphere/metersphere#8128]
**请描述您的问题.**
用jenkins插件，触发时测试执行方式为执行测试计划中用例测试报告，执行完毕，进入jenkins的console查看日志，track/testPlan/reportList链接打开，点击刚构建的那条测试报告，发现html中显示数据都不正常，数据执行为0
 #ps:jenkins的metersphere插件版本为1.11.1
以下为附件截图
<img width="652" alt="883af2d4f34fe5f614a17e3ff578d32" src="https://user-images.githubusercontent.com/94847127/143392579-9b74e7b6-397d-48c5-81a5-955986ea0f0c.png">
<img width="666" alt="32f927605ed7324a912ab98f19d37d6" src="https://user-images.githubusercontent.com/94847127/143392602-10ad3872-ee66-425b-8361-375dd76a6d0a.png">
<img width="579" alt="0d9fa30eec77003fe73f4b03b96a447" src="https://user-images.githubusercontent.com/94847127/143392638-4e9d1bbe-117d-447c-8012-34cc969c7563.png">
<img width="871" alt="0f97fd82ee11c3abcbd7892a00f0f6a" src="https://user-images.githubusercontent.com/94847127/143392655-64b4ce85-4589-4a8b-9d6f-4009617be87d.png">
<img width="838" alt="8cbdcf3c3e50b84b58be9b97b55784a" src="https://user-images.githubusercontent.com/94847127/143392670-772da0d4-c605-4b12-a13a-ba2a8c257dfa.png">

**Comment by zyyfit** [comment]
您好，我们在1.11-1.15版本中修复了一些Jenkins相关的问题，测试报告的样式也进行了改版，最新版没有复现您说的这个问题，您可以升级到最新版试试
