### ISSUE TITLE
[BUG] openapi3.0.3 文件解析出来的返回值展示不是正确的JON格式

### ISSUE THREAD

**Issue by fanpocha** [metersphere/metersphere#8133]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
管网测试环境最新环境

**Bug 描述**

openapi3.0.3 文件解析出来的返回值展示不是正确的JON格式

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/26472353/143398906-7fe40ffd-c4f4-4ad2-b0ba-2a74538749ee.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.16.5已修复
