### ISSUE TITLE
[BUG]用jenkins插件，触发时测试执行方式为执行测试计划中用例测试报告显示不正常

### ISSUE THREAD

**Issue by wangjb0718** [metersphere/metersphere#8138]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.11.1
**Bug 描述**

简要描述您碰到的问题
用jenkins插件，触发时测试执行方式为执行测试计划中用例测试报告，执行完毕，进入jenkins的console查看日志，track/testPlan/reportList链接打开，点击刚构建的那条测试报告，发现html中显示数据都不正常，数据执行为0
**Bug 重现步骤**
首先声明一下我是执行接口测试用例中的场景用例，并没有功能案例
![1637829097(1)](https://user-images.githubusercontent.com/94847127/143406521-0cfd0673-7314-4740-a6ad-7e84816b2c70.jpg)
1.jenkins上配置执行方式为执行测试计划中用例
![1637827915(1)](https://user-images.githubusercontent.com/94847127/143403862-e4ccf15d-668a-42f2-944c-12a96b518b3e.jpg)
<img width="666" alt="32f927605ed7324a912ab98f19d37d6" src="https://user-images.githubusercontent.com/94847127/143402715-de889ade-f4eb-497e-864e-f914c719a850.png">
2. 点击构建jenkins，完毕之后查看console日志，获取报告页面地址
![1637827491(1)](https://user-images.githubusercontent.com/94847127/143402896-1c61bf9a-a81f-4ec8-8746-03204593729f.jpg)
3. 进入地址查看，点击刚生成那条测试计划案例
<img width="871" alt="0f97fd82ee11c3abcbd7892a00f0f6a" src="https://user-images.githubusercontent.com/94847127/143403090-5418a523-4863-4546-aa1a-4d2ab6130573.png">
4. 查看html样式测试报告，显示数据都为0
![1637827602(1)](https://user-images.githubusercontent.com/94847127/143403151-5696cade-c6ed-423e-8ce5-de1c10d12c7d.jpg)
**期待的正确结果**
应该有执行的明细，执行几条，正确几条，错误几条
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前最新版已经是1.15.1了，有些bug已经被修复，建议您升级到最新版使用
