### ISSUE TITLE
[QUESTION]接口测试或者接口性能测试支持类似TestNg的dataprovider的功能吗

### ISSUE THREAD

**Issue by peterjaycn** [metersphere/metersphere#814]
**请描述您的问题.**

接口测试或者接口性能测试支持类似TestNg的dataprovider的功能吗

**Comment by wangzhen-fit2cloud** [comment]
你好，我们后续调研一下这个功能

**Comment by peterjaycn** [comment]
好的，谢谢您的回答，在日常测试接口过程中有这样的场景：通一个接口，需要多个不同的request，将这些request存储到Excel、xml、json文件或者CSV里，然后一行一行的调用接口来验证接口的正确性，之前我都是自己用httpclient和testng来测试的，数据都存放到了Excel中，使用testng的dataprovider，一行一行的来执行测试！
