### ISSUE TITLE
[BUG]Plan - Api Case中，分页不为10/page时，拖动调整用例顺序操作会导致前端报错。

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8141]
**MeterSphere 版本**

1.14.3

**Bug 描述**

Plan - Api Case中，分页**不为**10条/页时，拖动调整用例顺序操作会导致前端报错。

**Bug 重现步骤**

1.  进入Plan - Api Case列表页面
2. 切换分页为：100/page
3. 拖动任意一条用例到另一个位置

**期待的正确结果**

被拖动的用例应正确地被排序到对应的位置。

**截图**

![image](https://user-images.githubusercontent.com/34698664/143408019-6f7511f2-9fbf-4f34-8511-b01dc26c7ea2.png)
![image](https://user-images.githubusercontent.com/34698664/143408178-4b42dce4-2a23-43be-9055-db16db1ba1a5.png)

**Comment by zyyfit** [comment]
感谢反馈，这是个偶发问题，我们先排查一下问题

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.14.4以上版本没有复现这个问题了，建议升级下吧
