### ISSUE TITLE
[BUG]测试计划中拖拽编排接口用例，只能调整显示顺序，但无法作用于执行顺序

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8144]
**MeterSphere 版本**

>v1.14.3

**Bug 描述**

测试计划中拖拽编排接口用例，只能调整显示顺序，但无法作用于执行顺序

**Bug 重现步骤**

1.  有接口用例A、B
2. 在测试计划中拖拽A到B之前
3. 执行测试计划（串行）
4. B依然先于A执行

**期待的正确结果**

A先执行，B再执行（排序在前的用例先执行）

**截图**

![image](https://user-images.githubusercontent.com/34698664/143425260-4ac091d4-e038-47a5-82f0-5e89c01fc811.png)
![image](https://user-images.githubusercontent.com/34698664/143425498-f22d916f-9578-426d-96d4-13001826ecb9.png)
![image](https://user-images.githubusercontent.com/34698664/143425653-8054986c-3251-4c81-a5b8-97474bb3e009.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.15.3版本以上修复该问题，建议升级下吧
