### ISSUE TITLE
[BUG]用jenkins的metersphere插件单独运行测试，选择的运行环境为A，但是实际运行的还是在场景案例中设置的环境B

### ISSUE THREAD

**Issue by wangjb0718** [metersphere/metersphere#8145]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.11.1

**Bug 描述**

简要描述您碰到的问题
用jenkins的metersphere插件单独运行测试，选择的运行环境为A，但是实际运行的还是在场景案例中设置的环境B
**Bug 重现步骤**

1.  在场景案例中设置的环境为121
<img width="738" alt="962cebae4cb535f75914c2004cd0169" src="https://user-images.githubusercontent.com/94847127/143425717-fce34d9d-3b79-4a46-b551-99a2fb6a10d1.png">
2. 在jenkins中的环境设置为90
<img width="702" alt="3b2a14bf7c415406e803834ff9b9052" src="https://user-images.githubusercontent.com/94847127/143425950-0307e9f0-f7fa-42b0-a050-786809964e65.png">
3. 运行完毕，查看console
<img width="573" alt="43f29793d9906236cfaff2354b0bdb0" src="https://user-images.githubusercontent.com/94847127/143426030-c1ca7071-4f5f-4ee4-939e-e5283342e7ca.png">
<img width="712" alt="ddf987bb17d268fca6bbfd1336481c3" src="https://user-images.githubusercontent.com/94847127/143426060-63ee6851-7914-45e0-9883-296ccb6ad7ac.png">
**期待的正确结果**

正确情况下应该是什么样的？
应该在jenkins上设置的90环境运行

**Comment by zyyfit** [comment]
您好，jenkins选择环境这里最新版（1.15.1）做了改动，目前只支持接口用例选择环境，不支持场景、性能、测试计划选择环境
