### ISSUE TITLE
[BUG]GET请求参数直接放URL有时候会请求不到数据

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#815]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.4.2-b1039
**Bug 描述**
简要描述您碰到的问题
GET请求直接放URL有时候会请求不到数据
**Bug 重现步骤**
1.  通过MeterSphere Recorder 获取的请求导出的JSON文件
2. 导入的接口测试调用，发现参数在URL没有加上
3. MeterSphere服务没有报错，后台服务也是正确的
4. Postman调用有数据返回

**期待的正确结果**
正确情况下应该是什么样的？
导入的请求参数直接放URL应该自动到Query参数，正确请求接口才对
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/44960709/100110495-f634be80-2ea7-11eb-9dd6-bd352be75e82.png)
-----
![image](https://user-images.githubusercontent.com/44960709/100110767-4f045700-2ea8-11eb-8516-543ab5739191.png)

**Comment by AgAngle** [comment]
该问题是，返回结果后，页面数据没有及时渲染，已修复，请升级至1.5版本验证

**Comment by lingrance** [comment]
好的，谢谢
