### ISSUE TITLE
[FEATURE]API自动化失败添加失败原因，失败用例自动提交bug

### ISSUE THREAD

**Issue by xchnshi** [metersphere/metersphere#8150]
**请描述您的需求或者改进建议.**
API自动化执行在CICD体系中，如果失败了可以提供人工输入失败原因，进行失败分析。
同时，对于失败的API可自动提交bug，带上用例名称，请求信息，失败返回信息等内容。

**请描述你建议的实现方案**
无

**Comment by zyyfit** [comment]
可是失败原因有很多，比如环境问题，比如脚本本身的问题，如果都提bug的话，会造成很多无效bug吧？

**Comment by xchnshi** [comment]
期望，
初级阶段：可以自动手动填写失败原因，作为后续分析使用
第二阶段：创建bug按钮，自动带上信息
成熟阶段：用例稳定，或系统有分析后，自动创建bug

初始的手工加上bug原因，留作分析使用的，希望可以有。

**Comment by luty2018** [comment]
这个有规划的，但是要基于我们1.16的自动读取缺陷模版才比较好做，因为目前提交缺陷会涉及第三方平台

**Comment by xchnshi** [comment]
好的
可以直接在API自动化失败的结果上，手动打上失败原因的吗？
