### ISSUE TITLE
[BUG]接口定义-test页面，点击【测试】想要调试接口，但是页面一直处于【处理中】状态。

### ISSUE THREAD

**Issue by kkz9527** [metersphere/metersphere#8155]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？v1.15.0-a1807c06

**Bug 描述**

在写入一个接口准备基本调试的时候：
操作步骤
进入接口定义-test页面中，在接口信息没问题的情况下，
点击【测试】想要调试接口，但是页面一直处于【处理中】状态。
用户不知道接口调试是否成功
**Bug 重现步骤**

1.  

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
<img width="1417" alt="图片1" src="https://user-images.githubusercontent.com/59471772/143521557-882de7bb-5139-4a90-80b8-a64dc08b68c4.png">

<img width="1439" alt="图片2" src="https://user-images.githubusercontent.com/59471772/143521572-c318fd10-2a67-475f-91e8-7a2d83a3814d.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把这个接口和对应的环境信息导出来发给我们吗？f12或者日志里有什么报错信息吗？

**Comment by zyyfit** [comment]
另外，如果是ms服务器和你发的请求地址不通的话，要等超时才有结果，可以手动修改超时时间
![图片](https://user-images.githubusercontent.com/73461316/143559303-2c215072-266a-4aa7-ab07-17a58951e9ea.png)

**Comment by Snuger** [comment]
我们也遇到这个问题，升级了之后就不行了

**Comment by zyyfit** [comment]
> 我们也遇到这个问题，升级了之后就不行了

方便把您的接口导出来吗？还有，选择的环境中有没有配置脚本之类的？
