### ISSUE TITLE
[BUG]新增单接口case的时候，点击【调试】按钮想要调试接口，但是页面一直处于【处理中】状态。查看【执行历史】实际上该接口已经执行成功

### ISSUE THREAD

**Issue by kkz9527** [metersphere/metersphere#8156]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.15.0

**Bug 描述**

在确定一个接口可以调试没问题，准备新增单接口case的时候：
操作步骤：
进入接口定义-case-点击添加，进入添加case页面后，添加好新的case。
点击【调试】按钮想要调试接口，但是页面一直处于【处理中】状态。查看【执行历史】实际上该接口已经执行成功.
用户不知道接口调试是否成功，但是可以从执行历史中看见

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
<img width="351" alt="image" src="https://user-images.githubusercontent.com/59471772/143521813-899ce3d6-b1fe-4318-be42-24b3fd893d3d.png">
<img width="351" alt="image" src="https://user-images.githubusercontent.com/59471772/143521812-371ce5a0-c4b9-454c-9775-85d4c37c6233.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/8155
