### ISSUE TITLE
[Feature]测试报告的展示页面，建议能直接显示出当前测试计划的执行率、通过率

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#8159]
**MeterSphere 版本**

v1.15.0-a1807c06

**Bug 描述**

测试报告的展示页面，建议能直接显示出当前测试计划的执行率、通过率

**截图**

![image](https://user-images.githubusercontent.com/92150453/143523536-047d4e11-7bb3-4c6b-bd80-3d03812d2241.png)

**Comment by sageonedream** [comment]
补充报告内的信息：
![image](https://user-images.githubusercontent.com/92150453/143523732-e70c4519-7c82-4144-a153-6d00f5d622df.png)

**Comment by xulinde** [comment]
最新版本v1.20.4已优化，建议升级
