### ISSUE TITLE
[FEATURE]测试跟踪-报告，建议新增一栏 “测试成功率”的展示。

### ISSUE THREAD

**Issue by lingsoul** [metersphere/metersphere#8168]
**请描述您的需求或者改进建议.**

**请描述你建议的实现方案**
测试跟踪-报告，建议新增一栏 “测试成功率”的展示，方便直观查看结果，而不用再点一次查看具体报告。

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
1.17
