### ISSUE TITLE
[BUG]user bind Jira id with 'not_authorized' error 用户绑定JIRA账号报未授权错误

### ISSUE THREAD

**Issue by zhouwenblog** [metersphere/metersphere#8173]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15.0
**Bug 描述**
个人中心里面设置JIRA账号保存报未经授权错误
简要描述您碰到的问题

**Bug 重现步骤**

1.  使用非admin用户登录
2. 点击个人中心
3. 直接选择第三方平台账号tab
4. 输入JIRA账号和密码，点击验证，验证成功
5. 点击确定，提示“未经授权”

**期待的正确结果**
保存成功

经分析，由于未在"选择第三方平台账号"之前未点击“个人设置”的确认按钮，导致后台io.metersphere.service.UserService方法updateCurrentUser无法找到currentUserId，故提示报错。
临时解决办法，先点击个人设置的确认按钮保存了currentUserId再切换到“第三方平台账号”输入JIRA用户ID和账号才能保存成功。
![image](https://user-images.githubusercontent.com/31482780/143538564-6b1b0ba1-7d7c-43fa-bc2c-15fa6ec62672.png)
![image](https://user-images.githubusercontent.com/31482780/143538617-c0b1a0b2-0333-448b-8578-3ff1721e2f88.png)
![image](https://user-images.githubusercontent.com/31482780/143538663-2b7f1173-6436-4e5e-a137-34d7e71c4580.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.15.2已修复
