### ISSUE TITLE
[BUG]创建用户时，电话号码不支持199段

### ISSUE THREAD

**Issue by Andyguo5891** [metersphere/metersphere#818]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.4.0-b995

**Bug 描述**
简要描述您碰到的问题
创建用户时，电话号码不支持199段

**Bug 重现步骤**
1.  使用管理员登录MeterSphere系统
2. 在系统设置-系统-用户页面中点击创建用户
3. 输入创建用户所需的必要信息，电话输入199段11位号码
4. 页面提示「手机号码格式不正确」

**期待的正确结果**
正确情况下应该是什么样的？
创建用户应该支持199段手机号码

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/46042812/100174544-9968f080-2f07-11eb-922f-59506aaa6afc.png)

**Comment by shiziyuan9527** [comment]
已修复
