### ISSUE TITLE
[BUG]Pyhon后置脚本无法保存环境变量

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8198]
**MeterSphere 版本**

1.15.1

**Bug 描述**

Pyhon后置脚本无法保存环境变量

**Bug 重现步骤**

1.  清空环境变量中accessToken的值
2.  执行接口
3. Python后置脚本执行
```python
log.info(u"执行【后置脚本：提取accessToken，保存至环境变量accessToken】")

#Python脚本开始
import json
content = json.loads(prev.getResponseDataAsString())
vars.put(${__metersphere_env_id}+"accessToken",content["data"]["tokenVo"]["accessToken"]);
#Python脚本结束

log.info(u"【后置脚本：提取accessToken，保存至环境变量accessToken】执行完毕")
```

**期待的正确结果**

环境变量中accessToken保存为获取到的值

**截图**

![image](https://user-images.githubusercontent.com/34698664/143559557-859748cd-dc9a-426d-a6bd-aa98017d23e2.png)
![image](https://user-images.githubusercontent.com/34698664/143559609-96e4f1fb-96f2-4897-9683-5de25dd353b3.png)
![image](https://user-images.githubusercontent.com/34698664/143559656-46893989-9959-4848-90b0-139449c476b9.png)

**Comment by Saco93** [comment]
> 您好，使用您的脚本，我这边可以成功保存环境变量 ![图片](https://user-images.githubusercontent.com/73461316/143563257-277a0363-eb8d-4b22-aa7b-0e57e8ee0f51.png)

我这边回退到1.14.3也可以成功保存了，我可以再升级到1.15.1试一试，但如果还是不行，希望你们可以在深入调查一下

**Comment by Saco93** [comment]
> 您好，使用您的脚本，我这边可以成功保存环境变量 ![图片](https://user-images.githubusercontent.com/73461316/143563257-277a0363-eb8d-4b22-aa7b-0e57e8ee0f51.png)

经过验证的确无法在1.15.1版本下保存

**Comment by Saco93** [comment]
@zyyfit 升级到最新的15.3依然无法保存，无论是已有的脚本，还是新建脚本都无法保存

**Comment by zyyfit** [comment]
您好，我这边还是没有复现，您把您的场景和场景所使用的环境导出来给我们看看吧

**Comment by Saco93** [comment]
> 您好，我这边还是没有复现，您把您的场景和场景所使用的环境导出来给我们看看吧

麻烦提供一个联系方式吧，邮箱、即时通讯之类的都可以，我这边的环境配置不希望暴露在评论当中

**Comment by zyyfit** [comment]
> > 您好，我这边还是没有复现，您把您的场景和场景所使用的环境导出来给我们看看吧
> 
> 麻烦提供一个联系方式吧，邮箱、即时通讯之类的都可以，我这边的环境配置不希望暴露在评论当中

您可以进我们的企业微信交流群
![图片](https://user-images.githubusercontent.com/73461316/145525461-ac5a8b7a-630d-4f78-9fee-98587f57a0a2.png)

**Comment by Saco93** [comment]
> > > 您好，我这边还是没有复现，您把您的场景和场景所使用的环境导出来给我们看看吧
> > 
> > 
> > 麻烦提供一个联系方式吧，邮箱、即时通讯之类的都可以，我这边的环境配置不希望暴露在评论当中
> 
> 您可以进我们的企业微信交流群 ![图片](https://user-images.githubusercontent.com/73461316/145525461-ac5a8b7a-630d-4f78-9fee-98587f57a0a2.png)

我已经在里面了，要怎么提供给你我的场景和环境

**Comment by zyyfit** [comment]
你在几群？我去找你

**Comment by Saco93** [comment]
> 你在几群？我去找你

![image](https://user-images.githubusercontent.com/34698664/145526591-7c129d3a-3448-4c1d-bf19-9f6f08767e57.png)

**Comment by zyyfit** [comment]
已定位问题，后续版本修复

**Comment by zyyfit** [comment]
我们目前的导出机制，只有在全部结束之后才能拿到设置的环境变量结果，来写进数据库里
暂时不对这个地方进行修改

**Comment by zyyfit** [comment]
目前暂时不能做到取消失败继续后保存变量。

我们保存环境变量是基于给场景最后添加一个“调试取样器”来获取需要保存的变量的。
如果不勾选”失败继续“，在场景步骤失败之后，就不会继续下面的步骤，也就不会有调试取样器返回过来。
拿不到调试取样器，我们也没办法得到有哪些变量需要保存。

**Comment by Saco93** [comment]
> 目前暂时不能做到取消失败继续后保存变量。
> 
> 我们保存环境变量是基于给场景最后添加一个“调试取样器”来获取需要保存的变量的。 如果不勾选”失败继续“，在场景步骤失败之后，就不会继续下面的步骤，也就不会有调试取样器返回过来。 拿不到调试取样器，我们也没办法得到有哪些变量需要保存。

如果是设计如此，或不得不保留这个缺陷，建议提供一个可参考的说明或者文档，否则这对于使用者来说非常容易造成困惑。
