### ISSUE TITLE
[BUG]断言jsonpath返回值时，会把数字转成浮点型导致断言失败

### ISSUE THREAD

**Issue by elviszy** [metersphere/metersphere#820]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.4.3
**Bug 描述**
简要描述您碰到的问题
断言jsonpath返回值时，会把数字转成浮点型导致断言失败
**Bug 重现步骤**
1.  发生post请求，
2. 添加sonpath断言，断言返回值为14
3. 断言失败，接口返回14，预期值14，但断言中会将返回值改为浮点型数字14.0

**期待的正确结果**
正确情况下应该是什么样的？
应该按照实际值返回

**截图**

![image](https://user-images.githubusercontent.com/26116509/100196933-90424880-2f34-11eb-9bde-975c2108394d.png)
![image](https://user-images.githubusercontent.com/26116509/100196958-99331a00-2f34-11eb-82c2-b62c9b80796f.png)

**Comment by xulinde** [comment]
v1.5版本已修复，您直接升级到最新版本即可。
