### ISSUE TITLE
[BUG]环境域名-->启用和件：无，运行接口时，域名和路径之间节会自动生成多一个“/”

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#8206]
**MeterSphere 版本**

版本:   v1.15.0-a1807c06

**Bug 描述**
环境域名-->启用和件：无，运行接口时，域名和路径之间节会自动生成多一个“/”

备注：相关设置
环境配置 -->HTTP配置--环境域名-->启用和件：无

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/23476281/143775195-8a851ef5-b5d8-46b2-91c6-483d52a9b000.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您这个url变量是否带了一个/ 呢？我们在url中如果检测不到变量，是会自动在url里加上一个的，因为您的url使用的是变量，所以检测不到里面的 / ，所以自动增加了一个

**Comment by chase001** [comment]
> 您这个url变量是否带了一个/ 呢？我们在url中如果检测不到变量，是会自动在url里加上一个的，因为您的url使用的是变量，所以检测不到里面的 / ，所以自动增加了一个
你们1.5之前是没有这个问题的，还有请重视用户的问题，这个问题阻塞我的用例。你们不解决我真的没法搞了。

**Comment by chase001** [comment]
path路径你们平台默认也是“/”开头
![image](https://user-images.githubusercontent.com/23476281/143903286-6b68e17c-f7ab-4258-be18-0e6c7abd1846.png)

**Comment by youliyuan-fit2cloud** [comment]
今天发布的v1.15.2修复这个问题，升级下吧~
