### ISSUE TITLE
[BUG]json入参含数组时mock自定义脚本匹配成功后无返回值

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#8215]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15.1
**Bug 描述**

设置好mock脚本返回入参中数组部分的值，调用mock匹配成功返回值为空，修改过后可以输出到body.rows这一层完整数据，数组里面的项任然无法单独获取

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
能够正常获取数组中的参数body.rows[0].whouse

**截图**
![image](https://user-images.githubusercontent.com/40912823/142363743-d38d0e35-9683-4389-9d8d-8d7e0df3646c.png)
![image](https://user-images.githubusercontent.com/40912823/142363817-3b14fe90-08a2-47b0-82a9-7078b6b89705.png)

**Comment by zyyfit** [comment]
您好，针对数组的变量，我们修改了mock模板，您用新的模板试一下看看能不能获取到

**Comment by wszbc** [comment]
> 您好，针对数组的变量，我们修改了mock模板，您用新的模板试一下看看能不能获取到

哦哦是的新版的写法可以成功了
