### ISSUE TITLE
[FEATURE] SAML SSO 支持

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#8216]
**请描述您的需求或者改进建议.**
支持SAML单点登录

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
这个已经包括在企业版 X-Pack 中，详情见：https://metersphere.io/enterprise.html

**Comment by xyziven** [comment]
> 这个已经包括在企业版 X-Pack 中，详情见：https://metersphere.io/enterprise.html

在目前的CAS与OIDC之外，增加SAML

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
已规划到1.16企业版本中
