### ISSUE TITLE
[FEATURE] 建议增加测试用例指定多人执行功能

### ISSUE THREAD

**Issue by everiori** [metersphere/metersphere#8229]
**请描述您的需求或者改进建议.**
目前测试用例只能指定给测试用例负责人执行，建议实现类似TestLink的指定多人执行的功能

**请描述你建议的实现方案**
在将测试用例关联到测试计划时，可以多选执行人

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.** 目前测试用例只能指定给测试用例负责人执行，建议实现类似TestLink的指定多人执行的功能
> 
> **请描述你建议的实现方案** 在将测试用例关联到测试计划时，可以多选执行人

麻烦详细描述多人执行的场景，也可以直接企业微信与我沟通，想了解具体的执行过程多人怎么交互的。
