### ISSUE TITLE
[BUG] url不能完全使用环境变量或参数形式

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#8244]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

v1.15.1

**Bug 描述**

比如调用地址是由上一个case提取的参数，包含完整url的，这种情况就会出现。因为这个提取的参数是完整url，且域名是不固定的。。。查看日志显示会在完整参数url前强制加上 `http:/` 导致报错

简要描述您碰到的问题

**Bug 重现步骤**

比如调用地址是由上一个case提取的参数，包含完整url的，这种情况就会出现。因为这个提取的参数是完整url，且域名是不固定的。。。查看日志显示会在完整参数url前强制加上 `http:/` 导致报错

**期待的正确结果**

判断url参数或路径变量是否是完整url，如果是完整url则按照参数url调用

**截图**

![f5ba72fcc160845ebc1eeacf153a329](https://user-images.githubusercontent.com/1278141/144035462-8bdf9a5c-c6ae-427e-bf25-847b99a2f661.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，会加上 http:/ 是场景里面运行环境的http配置是空的，建议把这个接口用例用 自定义请求方式写一个吧，
我们目前处理方案只能是判断运行环境的http配置如果是空的，不自动加上 http:/

**Comment by lgs3137** [comment]
好的~
