### ISSUE TITLE
[BUG] 缺陷的自定义字段在从TFS中同步回来后显示为一串id编号

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#8251]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是 1.5.1

**Bug 描述**

缺陷的自定义字段在从TFS中同步回来后显示为一串id编号

**Bug 重现步骤**

1.  在缺陷模版中创建自定义字段“**指派给**”，类型为文本框
2.  MS创建bug，同步到TFS ，该字段显示正常的中文名
3.  MS中点击“同步缺陷”，该字段在同步后，在ms页面显示为一串id

**期待的正确结果**

应该跟一开始创建时一样，显示中文名

**截图**

![image](https://user-images.githubusercontent.com/24548477/144080700-2651cbfa-6fa1-4052-be98-dc727bd8a77e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本考虑优化下~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4以上版本已修复，升级下吧
