### ISSUE TITLE
[BUG]请求图片资源响应时间很慢，且后台日志有报错

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#8254]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.3-a3ef2834

**Bug 描述**

图片资源： http://maas-hdp.yscredit.com/static/img/maas-logo1.8304e1fd.png
请求图片资源响应时间很慢，且后台日志有报错

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:628)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:605)

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/86302975/144168497-731e8678-2114-475e-a2ad-64d91f021d37.png)

**Comment by zyyfit** [comment]
您好，请问是在哪里请求图片呢？接口定义吗？还是缺陷或者哪里？
