### ISSUE TITLE
[BUG]自动化场景包含一个csv文件，创建性能测试时会生成两个相同的csv文件

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8257]
**MeterSphere 版本**

1.10.8-lts

**Bug 描述**

自动化场景包含一个csv文件，使用该自动化场景，创建性能测试时会生成两个相同的csv文件

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
最新版本v1.20.0-lts中已修复
