### ISSUE TITLE
[BUG] 项目选择框太短，看不清项目名

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#8262]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

1.15.1

**Bug 描述**

简要描述您碰到的问题

项目选择框太短，看不清项目名，右侧的菜单可以整体右移一下。

![image](https://user-images.githubusercontent.com/41712985/144189630-dbff4cc9-7a7c-40b5-becb-019c07e8036d.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
