### ISSUE TITLE
[FEATURE]接口自动化模块，建议增加跨场景复制场景用例步骤的功能

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#8268]
**请描述您的需求或者改进建议.**
接口自动化模块，建议增加跨场景复制场景用例步骤的功能
比如01场景中的几个用例步骤我想复制到02场景中，因为如果接口自动化按业务场景去覆盖的话，其中会存在不同场景中有部分步骤是一样的情况。

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已规划，待排期
