### ISSUE TITLE
[BUG]sql语句limit限制查询无结果返回

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#8276]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.3-a3ef2834

**Bug 描述**
1. 待查询数据库的某张表有50W数据
2. 查询sql为： select name from table limit 120000,1  -> 该语句执行无结果返回
3. 查询sql为： select name from table limit 110000,1  -> 该语句执行有结果返回

测试返现只要limit  12W  之后的数据都是无结果返回的

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈， 后续版本优化下

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/144970129-58258df6-d0c6-4834-9ead-6938a1b20691.png)

![image](https://user-images.githubusercontent.com/54612864/144970186-029f6d2d-5e2e-4520-97fc-71360336d23d.png)

你好，我们找两个500w的大数据表，没有复现这个问题 ，是不是你的数据库有什么限制？
