### ISSUE TITLE
【企业版】接口自动化中创建mqtt连接可以正常执行，但是通过这个场景转成性能测试运行返回缺少jar包

### ISSUE THREAD

**Issue by ghost** [metersphere/metersphere#8277]
接口自动化中创建mqtt连接可以正常执行，但是通过这个场景转成性能测试运行返回缺少jar包
![image](https://user-images.githubusercontent.com/42909446/144348934-31cc56f3-8d46-408a-b580-6ed0588fc04f.png)
![image](https://user-images.githubusercontent.com/42909446/144348966-b31e8153-9234-4d52-9cc1-e2d1c2f75dbc.png)
![image](https://user-images.githubusercontent.com/42909446/144349017-7721f03d-ffc5-4b07-9091-2343417cc4b5.png)
上传mqtt-xmeter的jar包可以解决这个问题，但是为什么这个地方还要自己上传

**Comment by wangzhen-fit2cloud** [comment]
创建性能测试的时候没有将插件jar包添加进来，可以先手动添加一下
