### ISSUE TITLE
[BUG] 响应体是300行的json数据，如果关闭响应体的JSON-SCHEMA类型，就会导致接口文档页面卡死，怀疑是接口文档中的接口范例导致的

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#8278]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
版本:   v1.13.2-6ac3675a

**Bug 描述**

简要描述您碰到的问题
响应体是300行的json数据，如果关闭响应体的JSON-SCHEMA类型，就会导致接口文档页面卡死

**Bug 重现步骤**

1. 构造接口的响应体为300行的数据，关闭JSON-SCHEMA
2. 查看接口的文档
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
2.正常查看文档

**截图**
2.实际情况是直接文档页面直接卡死了，浏览器网页崩溃

如果有截图，请附上截图.

如果关闭JSON-SCHEMA，接口文档会显示范例，所以怀疑这里有问题

**Comment by allinone-1** [comment]
在线环境也有这个问题，见截图
![image](https://user-images.githubusercontent.com/81950749/144351745-c23ad71d-658d-48b0-8d18-5531b9190ec6.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您的响应json复制过来给我们看一下吗

**Comment by allinone-1** [comment]
> 您好，没有复现这个问题，方便把您的响应json复制过来给我们看一下吗

在线环境也有这个问题，文档页面卡死

**Comment by zyyfit** [comment]
> > 您好，没有复现这个问题，方便把您的响应json复制过来给我们看一下吗
> 
> 在线环境也有这个问题，文档页面卡死

在线环境的哪个工作空间和项目呢？

**Comment by allinone-1** [comment]
> 
看截图，神州飞船项目

**Comment by zyyfit** [comment]
> > 
> 
> 看截图，神州飞船项目

您好，我这边确实是没有出现卡死的问题，不过确实有点慢，我们先优化一下加载速度吧

![图片](https://user-images.githubusercontent.com/73461316/144533547-7fe4924b-92a3-43c4-8e41-8a0ca5acaf34.png)

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
