### ISSUE TITLE
[BUG]接口自动化场景id自定义命名报重名，但是找不到存在的重名场景

### ISSUE THREAD

**Issue by Jetdachui** [metersphere/metersphere#8284]
**MeterSphere 版本**
v1.15.1-b4

**Bug 描述**
提示重名，但是并没有重复的id

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/74963743/144374615-c243f512-1c48-4469-a496-2ef047c5955d.png)
![image](https://user-images.githubusercontent.com/74963743/144374668-e7f8c294-b056-4877-8585-b09dcde6df75.png)

**Comment by zyyfit** [comment]
您好，您看是不是回收站里有场景ID重复了呢？如果有的话把回收站里的场景删除就可以了

**Comment by Jetdachui** [comment]
是的 已经OK了
感谢****
