### ISSUE TITLE
提交缺陷到jira时需再增加几个字段及字段自定义

### ISSUE THREAD

**Issue by heyan527** [metersphere/metersphere#831]
**请描述您的需求或者改进建议.**
1.提交缺陷到jira现在的字段太少，需要再增加几个必要字段（经办人、优先级、严重程度）
2.增加自定义字段（每个公司的jira字段都不一定一致，可以增加输入框让使用者自己输入）

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
和 #1102 问题相同，请持续关注后续版本～
