### ISSUE TITLE
[BUG]post请求中，实际发送的请求体多了未定义的字符串

### ISSUE THREAD

**Issue by Jetdachui** [metersphere/metersphere#8313]
**MeterSphere 版本**
v1.15.2-b3

**Bug 描述**
请求体多了这个 --dy_Utt7qJyDMrWzG7NOUp32DR1gUlxSO7

**Bug 重现步骤**

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![企业微信截图_16385218706436](https://user-images.githubusercontent.com/74963743/144574979-d5c04657-ad70-47c1-8ee9-edb1c853990b.png)
![企业微信截图_16385218763016](https://user-images.githubusercontent.com/74963743/144574997-0a0aba24-0cd7-411b-b9a9-cba478cbeb8c.png)

**Comment by zyyfit** [comment]
您好，query参数要填在【query参数】tab页下面，请求体下的form-data是body参数，然后form-data类型的参数都会自动带上这种字符串的

**Comment by Jetdachui** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月3日(周五) 晚上6:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]post请求中，实际发送的请求体多了未定义的字符串 (Issue #8313)




 
您好，query参数要填在【query参数】tab页下面，请求体下的form-data是body参数，然后form-data类型的参数都会自动带上这种字符串的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
