### ISSUE TITLE
[BUG]性能压测负载中经常时常出现无测试结果的情况

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#8319]
**MeterSphere 版本*   V1.15.2
**Bug 描述**
性能压测负载中经常出现无测试结果的情况，时好时坏。
12月3号下午经刘工腾讯会议视频远程分析确认，基本确认是data-streaming消费计算结果时出现异常。

![image](https://user-images.githubusercontent.com/82088551/144772646-ef9237fd-8023-4863-b57d-63ab54b9f3ea.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，下个版本修复该问题，请关注下最近发布的版本
