### ISSUE TITLE
测试计划关联测试用例，页面没有展示用例，需退出重新登录系统

### ISSUE THREAD

**Issue by nuanyangxiademao** [metersphere/metersphere#832]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  新建测试计划
2. 关联用例，选择用例模块
3. 查看计划下的用例

**期待的正确结果**
可以展示用例

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/46918134/100312115-59c80480-2fec-11eb-83df-5af7713e2501.png)

**Comment by nuanyangxiademao** [comment]
![image](https://user-images.githubusercontent.com/46918134/100312167-7e23e100-2fec-11eb-8bb9-3b8ed8efb25d.png)
第一步选择用例图

**Comment by xulinde** [comment]
您好，未复现问题。是必现的吗？
