### ISSUE TITLE
[BUG]dubbo接口返回参数类型为BigDecimal时，断言结果有精度偏差

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#8329]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.2-03d7c58b
**Bug 描述**

简要描述您碰到的问题

dubbo接口返回参数类型为BigDecimal时，断言结果有精度偏差，比如接口返回的是2.00，在JSONPath或者JSON-文档结构校验时，总是按照2.0进行校验

**Bug 重现步骤**

1 响应结果及断言结果如图：
![image](https://user-images.githubusercontent.com/42166114/144800983-9e12f723-c585-4f38-82ea-1445df265798.png)

![image](https://user-images.githubusercontent.com/42166114/144800716-c6fbb802-3261-4582-8488-c93412e4cebb.png)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题~

**Comment by fanyulei1223** [comment]
已经更新到V1.16.0版本了，但是还是t有该缺陷
![image](https://user-images.githubusercontent.com/42166114/147323028-017557bb-e3e8-433b-97e3-05d75bb3d357.png)

**Comment by youliyuan-fit2cloud** [comment]
还没有解决，计划下个小版本解决掉

**Comment by zyyfit** [comment]
1.17.0已修复

**Comment by fanyulei1223** [comment]
1.17.2版本
经验证，断言使用「等于」，可断言成功，使用「正则匹配」仍报错
![image](https://user-images.githubusercontent.com/42166114/153566846-099bae86-00e9-4ac2-a62e-570afe61d864.png)
![image](https://user-images.githubusercontent.com/42166114/153566920-12612673-0037-4556-bcea-a9083da467a2.png)
