### ISSUE TITLE
[BUG] MS登录token失效后执行测试提示Network Error没有跳转到登录页

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#833]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本：v1.4.3-b105
**Bug 描述**
登录MS后过段时间没有使用，此时登录的token失效。但是点击保存并执行用例提示网络异常Network Error，没有跳转到登录页

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/34681889/100315279-5dab5500-2ff3-11eb-9241-b0c8449bf6b5.png)

**Comment by xulinde** [comment]
已知问题，后面版本会修复
