### ISSUE TITLE
[BUG] 场景公参里上传csv文件，超过2M的文件，直接卡死

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#8338]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
您好，我们这边超过2m的文件预览暂时没有出现卡顿的情况，8m的文件预览会有一点卡顿，是因为浏览器解析数据需要时间，不过没有出现浏览器崩溃的情况，方便把您的csv文件给我们看看吗

**Comment by meihaoyidian** [comment]
你好，我怎么传给你呢？貌似不能发送文件

**Comment by youliyuan-fit2cloud** [comment]
> 你好，我怎么传给你呢？貌似不能发送文件

你在哪个企业微信用户群里面啊？我找下你

**Comment by meihaoyidian** [comment]
> 用户群里面啊？我找下你

微信号：chendb112728

**Comment by youliyuan-fit2cloud** [comment]
好的，已经复现这个问题，我们研究优化一下

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5已修复该问题~
