### ISSUE TITLE
[BUG]文件管理缺少下载功能

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#8339]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

文件管理缺少下载功能

简要描述您碰到的问题

**Bug 重现步骤**

1.  上传
2. 下载
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
![image](https://user-images.githubusercontent.com/80370956/144815101-e95f067d-8d35-4d6e-a9f2-e95c2212312c.png)

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
已实现， 请更新到v2.7使用。
