### ISSUE TITLE
[FEATURE]缺陷管理列表增加处理人和状态的筛选

### ISSUE THREAD

**Issue by Evan-guo131** [metersphere/metersphere#8340]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
缺陷管理列表增加处理人和状态的筛选

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/80370956/144821235-921162e7-abff-4690-9920-2b70cb6333de.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先进行一下需求调研

**Comment by luty2018** [comment]
已排期处理
