### ISSUE TITLE
[FEATURE]性能测试导入jmx建议支持读取原jmx文件中的线程参数相关配置

### ISSUE THREAD

**Issue by chenxin2001** [metersphere/metersphere#8342]
**请描述您的需求或者改进建议.**

性能测试导入jmx建议支持读取原jmx文件中的线程参数相关配置，无需在MS前台在重新对每个线程组进行配置。
![image](https://user-images.githubusercontent.com/34565342/144824494-44d25fe9-ebcb-47b7-8c87-cbe10c868407.png)

**请描述你建议的实现方案**
目前版本会忽略jmx配置文件中的线程参数相关配置，建议MS读取线程参数相关配置后，在MS前台“压力配置”中显示jmx脚本中的线程参数值，用户可根据自身需求在页面自行修改。

**Comment by luty2018** [comment]
暂无计划。
