### ISSUE TITLE
[BUG] jmx文件导入到接口场景中时不支持调用另外的jmx文件

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#8351]
**MeterSphere 版本**

1.13-1.15

**Bug 描述**

jmx文件可以调用另外的jmx文件,导入后不能实现调用 

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

  实现场景嵌套或场景调用

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
这种情况，建议把要调用的jmx文件 导入接口自动化-场景，然后前面的jmx 场景引用，可以满足你的需求吧 ？
