### ISSUE TITLE
[BUG]测试跟踪定时任务邮件模板变量部分获取不到

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#8353]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15.2
**Bug 描述**

简要描述您碰到的问题
在接口自动化定时任务邮件可以获取到，测试跟踪获取不到。
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="521" alt="13bbb6ec9ceaeb6cb7048024fed2f4f" src="https://user-images.githubusercontent.com/85992665/144950416-3d6fb957-5679-42a0-bd44-583a1f6b3187.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化这些问题~
