### ISSUE TITLE
[BUG]登录页面图片不加载

### ISSUE THREAD

**Issue by fengyubiao** [metersphere/metersphere#837]
**MeterSphere 版本**
1.5.0
**Bug 描述**
自编译1.5.0所有组件，启动后登录页面图片缺失
![图片](https://user-images.githubusercontent.com/6871534/100402325-ec24e280-3096-11eb-8951-00ef08f8d936.png)
![图片](https://user-images.githubusercontent.com/6871534/100402332-efb86980-3096-11eb-9694-65e838fb7dc7.png)

**Bug 重现步骤**
自编译然后启动

**期待的正确结果**
图片可以显示

**截图**

![图片](https://user-images.githubusercontent.com/6871534/100402325-ec24e280-3096-11eb-8951-00ef08f8d936.png)
![图片](https://user-images.githubusercontent.com/6871534/100402332-efb86980-3096-11eb-9694-65e838fb7dc7.png)

**Comment by xulinde** [comment]
已知问题，源码打包会导致图片缺失。后边会修改
