### ISSUE TITLE
[QUESTION]为什么调试报告，不支持展开Beanshell

### ISSUE THREAD

**Issue by Laimf1995** [metersphere/metersphere#8372]
**请描述您的问题.**
请问，为什么调试报告，不支持展开Beanshell
在src/business/components/api/automation/report/SysnApiReportDetail.vue

if (this.stepFilter.get("AllSamplerProxy").indexOf(item.type) !== -1) {
              //限制"JSR223Processor"，不展示
              obj.unsolicited = false;
              obj.type = item.type;
            }

**Comment by fit2-zhao** [comment]
@Laimf1995 这应该是个缺陷，正常使用自定义脚本 是有结果展示的，后续版本修复。

**Comment by Laimf1995** [comment]
那我关闭这个提问，转为详细的bug步骤。
