### ISSUE TITLE
[BUG]15.2 版本，导入的测试用例显示为remove，应该正确显示。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#8382]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？15.2

**Bug 描述**

简要描述您碰到的问题导入的测试用例显示为remove，应该正确显示。见下图。
![测试用例remove](https://user-images.githubusercontent.com/14307013/145137426-46e23f28-64fb-4930-b6b9-069e47653767.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，方便把你的用例文档发一下我们尝试复现？
