### ISSUE TITLE
[BUG]v1.15.3-db00e436 连接mysql数据库时报错：CLIENT_PLUGIN_AUTH is required；mysql版本：5.6.20

### ISSUE THREAD

**Issue by mrxuying** [metersphere/metersphere#8383]
**MeterSphere 版本**

v1.15.3-db00e436

**Bug 描述**

连接mysql数据库时报错：CLIENT_PLUGIN_AUTH is required；
mysql版本：5.6.20

**Bug 重现步骤**

1.  在项目环境中添加数据库配置后点击校验，报错：CLIENT_PLUGIN_AUTH is required；

**期待的正确结果**

应该是可以正常连接的

**截图**
![image](https://user-images.githubusercontent.com/43841144/145139128-31b7a9bc-5e56-4c70-95fc-104377ab6138.png)

**Comment by youliyuan-fit2cloud** [comment]
你好， mysql 5.6 版本有点低，我们支持5.7 以上的，建议升级下mysql 版本吧
