### ISSUE TITLE
[FEATURE] 接口定义发生变更后（如URL变更等），接口自动化中的接口没有对应更新

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#8386]
**请描述您的需求或者改进建议.**
接口定义发生变更后（如URL变更等），接口自动化中的接口没有对应更新

如果用例较多，那么维护成本就很大，建议使用接口引用的方式

**请描述你建议的实现方案**

**Comment by allinone-1** [comment]
> 你好，请问是使用的哪个版本呢？在较新的版本中我们已经针对URL更新进行了处理，接口下的 case 也会更新。 针对请求参数等内容，目前还没有比较明确的自动更新机制，会在后续版本中再去优化。

版本: v1.13.2-6ac3675a


这里说的是接口自动化那边没有更新，在接口自动化用例规模较大的情况下，如果用例的URL变更了，接口自动化那边对应接口的URL更新

**Comment by Hyyfit** [comment]
> > 你好，请问是使用的哪个版本呢？在较新的版本中我们已经针对URL更新进行了处理，接口下的 case 也会更新。 针对请求参数等内容，目前还没有比较明确的自动更新机制，会在后续版本中再去优化。
> 
> 版本: v1.13.2-6ac3675a
> 
> 这里说的是接口自动化那边没有更新，在接口自动化用例规模较大的情况下，如果用例的URL变更了，接口自动化那边对应接口的URL更新

接口自动化如果是复制接口的用例，当接口定义发生变更，是不会同步的。只有引用的用例，才会同步变更。
