### ISSUE TITLE
[BUG]JDBCDataSource在节点机执行时多次初始化

### ISSUE THREAD

**Issue by Laimf1995** [metersphere/metersphere#8395]
**MeterSphere 版本**

node-controller 1.15

**Bug 描述**

ERROR r.protocol.jdbc.config.DataSourceElement: 120 - JDBC data source already defined for

**Bug 重现步骤**

1.  用例包含SQL接口，会附带数据库配置（相关配置存在多个）
2. 节点进行执行任务
3. 出现大量 JDBC data source already defined for

**期待的正确结果**
Tips：
该问题，不影响用例执行，可能存在潜在资源多消耗。

这些配置元件会一起初始化， 而且变量是全局共享，不是属于自己threadgroup 独立使用的。  
期望：数据库只初始化一次

**截图**

如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
@Laimf1995  请把步骤配置详细说明一下。

**Comment by Laimf1995** [comment]
具体场景为：场景包含引用SQL用例多个
改用例具体JMX表现为出现多组树结构，JDBCDataSource相同配置出现多个，所以导致加载多次
![image](https://user-images.githubusercontent.com/32592646/145369617-3865a1d5-6d25-41d2-9160-4ef75ad9e109.png)

**Comment by fit2-zhao** [comment]
@Laimf1995  这个是因为 每个请求都是可以选择环境及不同数据源，所以针对每个请求单独初始化一个，后续版本优化一下，相同数据源看看能否合并掉。
