### ISSUE TITLE
[BUG]性能测试报告，请求统计部分字段小数点没有格式化

### ISSUE THREAD

**Issue by popolyj** [metersphere/metersphere#84]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.02

**Bug 描述**
简要描述您碰到的问题
性能测试报告，请求统计部分字段小数点没有格式化，小数点后位数太多了，

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
精确到小数点后2位？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/12756697/86436226-7198a680-bd34-11ea-81c0-909bc2314002.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，已在 v1.0.3 中修改
