### ISSUE TITLE
[建议]使用文档尽量详细

### ISSUE THREAD

**Issue by lede-zr** [metersphere/metersphere#840]
**请描述您的需求或者改进建议.**

很多功能不太会用，学习成本比较高，没有详细的功能介绍和操作说明

**请描述你建议的实现方案**
特别是接口测试这块，执行后，会新增一个测试模块（概念比较模糊）

**Comment by 52testing** [comment]
点个赞！good，正好我也想说，虽然官网有文档介绍，但是太笼统了；
没有一个详细的案例 -举例说明，这是非常重要的；
或者功能上有个？导引说明这是什么效果，使用说明指南！
