### ISSUE TITLE
[BUG] 在脑图上修改模块名称，保存时候提示保存成功，实际并未保存成功，还是原来的模块名称（仅限在这个模块为根节点的图上

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#8400]
1.15.2版本

![1c8223d1-a8f9-4c75-b5b0-adecfe83a46a](https://user-images.githubusercontent.com/44999044/145346450-d029ace7-6e24-419c-b727-7fdbe869f207.gif)

**Comment by zyyfit** [comment]
您好，1.15.3没有复现这个问题，建议您升级到最新版试试
