### ISSUE TITLE
[BUG]调试生成报告，不能展开Beanshell详情和状态

### ISSUE THREAD

**Issue by Laimf1995** [metersphere/metersphere#8402]
**MeterSphere 版本**

1.15

**Bug 描述**

调试——生成报告——不能展开Beanshell详情

**Bug 重现步骤**

1.  点击接口自动化用例编辑
2. 调试——鼠标悬浮，选中生成报告，执行
3. 侧边出现调试报告页面，进行运行
4. Beanshell用例不能展开，查看不了状态

**期待的正确结果**

Beanshell用例可以正常展开

Tips：
如果修改前端，在src/business/components/api/automation/report/SysnApiReportDetail.vue，不限制"JSR223Processor"，单Beanshell则可以展开，但是场景包含的Beanshell依旧没有状态，不能进行展开。

if (this.stepFilter.get("AllSamplerProxy").indexOf(item.type) !== -1) {
//限制"JSR223Processor"，不展示
obj.unsolicited = false;
obj.type = item.type;
}
**截图**

![image](https://user-images.githubusercontent.com/32592646/145371516-cddbccea-72a5-41d7-a6b5-b3135e8c0f34.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题

**Comment by youliyuan-fit2cloud** [comment]
v1.15.4已修复
