### ISSUE TITLE
[BUG]调试生成报告，提取的数据不展示

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#8403]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，请详细描述一下复现步骤，你这样我没发入手复现，多谢~

**Comment by youliyuan-fit2cloud** [comment]
我们没复现这个问题，你这个截图提取的参数名都看不到，是不是你场景里面提取的参数没添加成功啊？
建议先在场景里面单独执行这个接口看看有没有提取出来 ，如果有的话调试生成报告也应该有

**Comment by meihaoyidian** [comment]
单独调试的话会有提取参数的数据，只要点调试生成报告，报告中不展示提取参数

MatataYou ***@***.***> 于2021年12月10日周五 12:44写道：

**Comment by youliyuan-fit2cloud** [comment]
复现了。。是只有事务控制器里面的提取结果确实没有，后续版本修复，感谢~

**Comment by meihaoyidian** [comment]
好的

MatataYou ***@***.***> 于2021年12月10日周五 14:32写道：

**Comment by meihaoyidian** [comment]
请问下这个问题，最新代码里解决了么？如果解决了，我想更新下

**Comment by youliyuan-fit2cloud** [comment]
> 请问下这个问题，最新代码里解决了么？如果解决了，我想更新下

还没有哦，最晚在下周四发布的大版本修改~

**Comment by meihaoyidian** [comment]
貌似最新的版本这个问题还存在

**Comment by youliyuan-fit2cloud** [comment]
> 貌似最新的版本这个问题还存在

抱歉，这个bug 推迟到下个小版本解决了。再等等哈

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.16.2终于解决了。。。升级下吧
