### ISSUE TITLE
[性能测试]每个场景单独每次导入jar包不方便

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#841]
1.每次每个场景都要导入jar包，还要理清需要哪些jar，很花时候精力，建议搞一个系统设置，直接一次性添加到jmeter的空间里面配置，永久使用，测试时候直接调用引用就是了。
2.每个都添加占用空间
3.太多jar看着难受，导致工作效率十分不高效

**Comment by Anduin-Zhu** [comment]
附议，

**Comment by wangzhen-fit2cloud** [comment]
你好，在最新 1.8 版本中已经进行了修改，已经上传地 jar 包、jmx 等文件在创建性能测试时可以选择复用，欢迎更新升级。
