### ISSUE TITLE
[BUG]性能测试 测试详情页面  事务详细列表未展示

### ISSUE THREAD

**Issue by yangfan112** [metersphere/metersphere#8417]
**MeterSphere 版本**
 v1.15.3-db00e436
您所使用的 MeterSphere 版本是？
 v1.15.3-db00e436
**Bug 描述**
![lALPJx8ZubxpNnjNAePNBQs_1291_483](https://user-images.githubusercontent.com/48746721/145531337-98a52495-bc41-45ab-a1b1-c3a237adcab3.png)
测试详情中-事务详细列表未展示

**Comment by zyyfit** [comment]
您好，我们这里默认是不展示的，需要手动勾选

**Comment by zhangzhaox** [comment]
我看错了，不好意思
