### ISSUE TITLE
[BUG]在脑图中新增用例时未打用例标签直接保存，提示保存成功后再次编辑该条未打标签的用例并保存，系统报错

### ISSUE THREAD

**Issue by wangjqi** [metersphere/metersphere#8424]
**MeterSphere 版本**

V1.15.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在脑图中新增用例，但该用例未打上用例标签，点击【保存】
![image](https://user-images.githubusercontent.com/50005529/145539304-5c54ecd8-95fe-4e76-9219-3fd273455e64.png)
2. 再次对该条用例进行编辑，并保存，此时系统报错
![image](https://user-images.githubusercontent.com/50005529/145539467-0bffe059-1364-4c89-86d8-18d8e33a11e5.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.16.0已修复
