### ISSUE TITLE
【接口测试】请求体选择文本模式，建议默认是json格式不是text格式

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#843]
**请描述您的需求或者改进建议.**
## 请求体选择文本模式，建议默认是json格式不是text格式

> 一般选择文本格式请求体使用json格式是大多数人的选择，使用text的非常少。在这种情况下每次都要选择json很繁琐。建议要改成json

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
