### ISSUE TITLE
[BUG] API接口自动化测试中， 场景导入中， 选择复制，变量还是会使用旧场景的值，导致新场景中定义的变量无效

### ISSUE THREAD

**Issue by jason-000** [metersphere/metersphere#8432]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.15.4版本

**Bug 描述**

简要描述您碰到的问题

 API接口自动化测试中， 场景导入中， 选择复制，变量还是会使用旧场景的值，导致新场景中定义的变量无效

**Bug 重现步骤**

1.  在新的API自动化场景中，点场景导入，选择复制
2. 选择一个已经存在的场景，带场景变量的
3. 新场景中也定义了同名的变量
4. 执行结果发现新场景中使用的还是旧的场景变量值。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5已修复该问题~
