### ISSUE TITLE
[FEATURE]测试跟踪测试计划“创建测试计划页”建议允许自定义字段，参考用例模板设计

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#8446]
**请描述您的需求或者改进建议.**
创建测试计划时，现有的字段内容不完全满足计划内容，；
因需要根据不同的维度去做“测试任务统计”，故需要测试计划中增加自定义字段。

**请描述你建议的实现方案**
参考测试用例、缺陷模板，允许创建测试计划时自定义字段及码值。

**Comment by luty2018** [comment]
可以列举下具体的使用场景 想要支持的字段吗，目前其实是没有计划对测试计划做模版配置，所以想了解清楚需求

**Comment by wangjiaxin1100** [comment]
比如是否计划内，上线投产日期，花费工时数、测试需求类型等
