### ISSUE TITLE
[BUG]测试跟踪，用例执行页面评论框中的图片加载失败

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#8449]
**MeterSphere 版本**
v1.15.4.tar
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  创建测试计划
2. 关联用例
3. 执行用例并在页面右侧评论上传图片
4. 查看图片

**期待的正确结果**
正常展示已上传的图片
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![Uploading image.png…]()

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复

**Comment by schnell18** [comment]
我也碰到相同的问题。我用的版本是1.15.3。另外，是否可以支持上传视频？

**Comment by youliyuan-fit2cloud** [comment]
> 我也碰到相同的问题。我用的版本是1.15.3。另外，是否可以支持上传视频？

后续版本会考虑的~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.0版本已修复
