### ISSUE TITLE
[FEATURE] 接口请求体json格式希望能够用代码格式化显示

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#845]
**请描述您的需求或者改进建议.**
## 接口请求体json格式希望能够用代码格式化显示
> 当json非常长，而且嵌套特别多的时候，修改数据出现格式错误，找到问题的地方总是非常耗时间。希望能够用代码格式化方式显示，方便对定位json格式错误的位置

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，请问你指的是测试报告当中展示的请求内容吗？
