### ISSUE TITLE
[BUG] MS 发送 POST 请求后，无法正常返回响应体

### ISSUE THREAD

**Issue by lvxiaohu** [metersphere/metersphere#8450]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本:   v1.15.3-db00e436

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  先使用 curl 测试该接口是否正常： 「正常返回」
![image](https://user-images.githubusercontent.com/29087369/145928427-b9c03ef9-6dbd-43ab-ada5-807d264d00a0.png)

2.  使用 MS 的接口测试对相同接口进行测试，响应体为空 「307」
![image](https://user-images.githubusercontent.com/29087369/145927791-5739bc42-9138-4f7e-9202-5bbae14ab1a0.png)

3. 使用 MS 的接口测试对相同接口进行测试，请求内容如下
![image](https://user-images.githubusercontent.com/29087369/145927879-c2072713-b982-4a98-808a-0d086e9e588f.png)

**期待的正确结果**

正确情况下应该是什么样的？
可正常返回响应体：
![image](https://user-images.githubusercontent.com/29087369/145928068-ccd12c8f-fa06-403b-aea6-12a408fb21d5.png)

**截图**

如果有截图，请附上截图.
推测，是否跟这个接口返回了2个头字段有关系，使用其他工具测试都是正常
使用 RESTClient 测试，可以看到有两个 HTTP 头字段，第一个也是307，但是响应体也是正常返回的：
![image](https://user-images.githubusercontent.com/29087369/145928253-36edc37c-8169-4e08-8c19-ccacb95f8e6e.png)
![image](https://user-images.githubusercontent.com/29087369/145928324-49672729-653b-421d-afcb-fc057337d6a7.png)

**Comment by youliyuan-fit2cloud** [comment]
导入的swagger 文件没有处理 路径最后的" / "，后续版本优化下~
