### ISSUE TITLE
[FEATURE]性能测试场景设置使用体验细节避免在使用过程中重复的上传脚本文件和参数化文件

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#8451]
**请描述您的需求或者改进建议.**
1、读写并可编辑CSVDataSet的文件名
2、读取jmx脚本中的自定义变量名称，方便在高级里调整环境信息

![image](https://user-images.githubusercontent.com/82088551/145927786-1bf18d15-279e-45a3-b054-35950e265d32.png)
![image](https://user-images.githubusercontent.com/82088551/145928020-2eeda6f7-341c-410d-9ce2-e600da8feb16.png)

**Comment by luty2018** [comment]
谢谢反馈，待排期处理
