### ISSUE TITLE
[BUG]用例名称过长，执行该用例实际已经成功，页面显示在执行中

### ISSUE THREAD

**Issue by PIDAN524** [metersphere/metersphere#8459]
**MeterSphere 版本**

1.14

**Bug 描述**

用例名称非常长，执行用例实际已经成功，但是页面显示在执行中

**Bug 重现步骤**

1.  编写一个用例，输入很长的用例名称
2. 执行该用例
3. 很久以后，用例仍然显示在执行中
4. 

**期待的正确结果**

 执行成功以后用例正确展示执行成功

**截图**

**Comment by youliyuan-fit2cloud** [comment]
你好，请详细说明下，用例是指接口CASE 用例？还是场景用例？ 名称有多长？

**Comment by PIDAN524** [comment]
接口CASE

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4以上版本已修复~
