### ISSUE TITLE
性能测试-报告-测试概览页，用户数描述不准确，如果统计的是峰值，希望在描述里添加“峰值”，现在有用户以为这里统计的是总数或平均值，觉得是BUG

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#8463]
**测试概览页，用户数描述不准确**

**如果统计的是峰值，希望在描述里添加“峰值”，现在有用户以为这里统计的是总数或平均值，觉得是BUG**

**Comment by zhangzhaox** [comment]
不是统计的，这个应该是实时的负载用户数

**Comment by binbin0406** [comment]
结束的时候，图上并发数不到8，但用户数却为17
![622464d3b51a260afef3bc648cefb87](https://user-images.githubusercontent.com/77324661/146320267-954dd9dc-6ce9-4b83-9b05-f28278886593.jpg)

**Comment by zhangzhaox** [comment]
场景结束时就对应时这个场景的概要结果，这个地方不能完全和时间线对应，如果是0更不好理解了

**Comment by binbin0406** [comment]
如果是实时数值，是否可以在页面添加说明，不然也很容易误解。

**Comment by luty2018** [comment]
已排期优化
