### ISSUE TITLE
[FEATURE]禅道集成增加更多字段支持

### ISSUE THREAD

**Issue by ErvinChiu** [metersphere/metersphere#847]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？ v1.5.0-b1192

**Bug 描述**
简要描述您碰到的问题
集成禅道-Bug 提交缺少Bug等级、优先级、Bug 类型、附件等自定义字段且无法正确同步禅道，禅道项目下无法查看bug

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
添加Bug 自定义字段，
添加附件上传
禅道bug 处理人，根据实际配置项目团队人员展示

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
v10.5已支持
