### ISSUE TITLE
[FEATURE]性能测试报告错误记录页签改善建议

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#8485]
**请描述您的需求或者改进建议.**

断言失败打印自定义错误详细的信息应该在TOP 5 ERROR  链接后面的统计数字链接，当前展示篇幅过大，且稳定性场景下的该页签矛盾更突出

![image](https://user-images.githubusercontent.com/82088551/146298459-9cd69aff-e7b5-4d36-a875-a995ac87e3ad.png)
![image](https://user-images.githubusercontent.com/82088551/146298495-4bead936-df1c-4cf7-895a-1470f1cfcbe7.png)

**Comment by luty2018** [comment]
待排期处理
