### ISSUE TITLE
[BUG]  自定义的请求没有使用运行环境的环境，而是使用了自定中的环境（没有勾选引用环境）

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#8499]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
自定义的请求没有使用运行环境的环境，而是使用了自定中的环境（没有勾选引用环境）

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，是这样设计的，不勾选引用环境就会使用自己的环境
