### ISSUE TITLE
关联用例顺序错乱，需要与现有用例顺序一致

### ISSUE THREAD

**Issue by nuanyangxiademao** [metersphere/metersphere#850]
**请描述您的需求或者改进建议.**

在测试计划关联用例的时候，关联某一个用例模块下的用例，用例顺序错乱

**请描述你建议的实现方案**
可以按照模块原有用例顺序的基础上排序，至少保证关联的用例顺序不错乱。

![image](https://user-images.githubusercontent.com/46918134/100561647-656d4100-32f4-11eb-9f13-98aa1d54b11d.png)
![image](https://user-images.githubusercontent.com/46918134/100561677-77e77a80-32f4-11eb-9f01-1a15318d77e0.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.8版本已修复
