### ISSUE TITLE
[BUG]复制case后路径显示不一致

### ISSUE THREAD

**Issue by PIDAN524** [metersphere/metersphere#8504]
**MeterSphere 版本**

v1.14

**Bug 描述**

复制用例接口路径显示不正确

**Bug 重现步骤**

1.  选择一个接口case，点击复制
2. 选择复制的用例点击编辑查看详情
3. 路径展示不正确  见图

**期待的正确结果**

复制的用例详细页，路径显示一致

![image](https://user-images.githubusercontent.com/54307955/146351945-42a651b4-b065-4833-b819-809500074ed7.png)

**Comment by zyyfit** [comment]
收到，不过我看我们 1.14 版本和你这个界面不一样呢，你是1.14.几呀，我这边问题的表现和你这里也不太一样，我是复制完后没显示路径 
![图片](https://user-images.githubusercontent.com/73461316/146483566-42215105-d864-4f4f-9f80-b94214435f83.png)

**Comment by zyyfit** [comment]
1.16.0已修复
