### ISSUE TITLE
目前对接jira中，所有测试人员提交的bug在jira中显示的都是唯一的 Basic Auth用户

### ISSUE THREAD

**Issue by kobe2016** [metersphere/metersphere#851]
建议：
A用户提交BUG后，在jira中显示的是A提交的；
B用户提交BUG后，在jira中显示的是B提交的

方案：
可以像集成禅道一样， 在提交BUG时，能取到 jira中的其他用户进行选择。

**Comment by zhaoshiwei1** [comment]
该问题在1.7.0的版本中依然存在。

**Comment by zhaoshiwei1** [comment]
该问题在1.7.0的版本中依然存在。

**Comment by wangzhen-fit2cloud** [comment]
你好，我们计划在 1.8 版本着重优化下测试跟踪模块，计划在 1.8 版本解决该问题。

**Comment by xulinde** [comment]
v10.4已优化，支持个人信息中配置jira信息
