### ISSUE TITLE
[BUG]性能测试到处报告导致浏览器崩溃

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8520]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.4
**Bug 描述**

简要描述您碰到的问题
性能测试模块，性能测试报告导出，点击导出时，有部分接口调用一直处于pending状态，同时页面卡住，导致浏览器崩溃，此处需要优化
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化
