### ISSUE TITLE
[BUG]场景共享cookie单步执行不生效

### ISSUE THREAD

**Issue by pb123abc** [metersphere/metersphere#8521]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.1
**Bug 描述**

简要描述您碰到的问题

需要重定向的登录接口，涉及到cookie验证时，在场景步骤中勾选的：共享cookie功能，在单步执行时无法生效

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
共享cookie是基于前面的步骤有cookie之后，才能共享给其他步骤，单独执行就是没有呀
