### ISSUE TITLE
[BUG]测试报告不显示结果

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8522]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.1
**Bug 描述**

简要描述您碰到的问题
重定向的接口用例，在实时接口调测页面有显示请求结果-断言的情况下，在试报告中无断言结果显示
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.15.4没有复现这个问题，请升级后再试试
