### ISSUE TITLE
[BUG]查看变更历史速度很慢

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8523]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.1
**Bug 描述**

简要描述您碰到的问题
查看接口自动化-场景用例的变更历史，响应时间过长，20-30S（30条左右变更历史）
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.16.0已经进行了优化
