### ISSUE TITLE
[BUG]引入场景生成报告会生成一个同名场景

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8529]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.10.1-lts
**Bug 描述**

简要描述您碰到的问题
被引入的场景中如果有多个自定义脚本步骤，则在生成测试报告的时候会全部单独出来生成一个与所在场景同名的场景步骤
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，最新版lts版本已经是 1.10.11了，请升级后再试试
![图片](https://user-images.githubusercontent.com/73461316/146495478-3442ef92-ba6e-4302-8504-54a62f2012d2.png)
