### ISSUE TITLE
[FEATURE]性能测试列表页面希望与接口列表一样，有执行按钮

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8534]
**请描述您的需求或者改进建议.**
性能测试列表页面希望与接口列表一样，有执行按钮

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.** 性能测试列表页面希望与接口列表一样，有执行按钮
> 
> **请描述你建议的实现方案**

请提到metersphere战区
