### ISSUE TITLE
[FEATURE]性能测试报告页面增加看到场景执行结果的功能

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8535]
**请描述您的需求或者改进建议.**

性能测试报告页面，不能全局的看测试结果，场景是成功还是失败，都要点到每个报告里面自己去看。希望可以增加类似可以在测试报告列表看到场景执行结果的功能

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 性能测试报告页面，不能全局的看测试结果，场景是成功还是失败，都要点到每个报告里面自己去看。希望可以增加类似可以在测试报告列表看到场景执行结果的功能
> 
> **请描述你建议的实现方案**

请提到metersphere战区
