### ISSUE TITLE
[BUG]通过swagger同步的接口，响应体的描述不能同步到metersphere

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8536]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.3
**Bug 描述**

简要描述您碰到的问题
通过swagger同步的接口，响应体的描述不能同步到metersphere
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，请问swagger文件导入能同步吗？
