### ISSUE TITLE
[BUG]脑图用例中删除内容提示是：取消缺陷关联成功

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8537]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.1
**Bug 描述**

简要描述您碰到的问题
脑图用例中删除内容提示是：取消缺陷关联成功
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by zyyfit** [comment]
1.16.0已修复
