### ISSUE TITLE
[FEATURE]性能测试增加设置迭代次数的执行时间功能

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8541]
**请描述您的需求或者改进建议.**
性能测试，场景设置10次迭代，在点击运行后，很长时间后，首页这个场景一直是starting，不能再次运行，建议设置个时间，让迭代次数的场景到时间后自动停止

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.** 性能测试，场景设置10次迭代，在点击运行后，很长时间后，首页这个场景一直是starting，不能再次运行，建议设置个时间，让迭代次数的场景到时间后自动停止
> 
> **请描述你建议的实现方案**

请提到metersphere战区
