### ISSUE TITLE
[FEATURE]文本框自动调整间隔

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8543]
**请描述您的需求或者改进建议.**

脑图编写用例，文字过多时，不会自动调整文本框之间的间隔，导致文案重叠

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 脑图编写用例，文字过多时，不会自动调整文本框之间的间隔，导致文案重叠
> 
> **请描述你建议的实现方案**

请提到metersphere战区
