### ISSUE TITLE
[FEATURE]脑图增加富文本功能

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8544]
**请描述您的需求或者改进建议.**

脑图编写用例富文本功能匮乏，比如标注字体颜色（醒目，方便注意）

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 脑图编写用例富文本功能匮乏，比如标注字体颜色（醒目，方便注意）
> 
> **请描述你建议的实现方案**

请提到metersphere战区
