### ISSUE TITLE
[FEATURE]接口自动化场景列表，创建人表头，创建人过多不容易找到，建议放到搜索栏

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8545]
**请描述您的需求或者改进建议.**

接口自动化场景列表，创建人表头，创建人过多不容易找到，建议放到搜索栏

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 接口自动化场景列表，创建人表头，创建人过多不容易找到，建议放到搜索栏
> 
> **请描述你建议的实现方案**

请提到metersphere战区
