### ISSUE TITLE
[FEATURE]功能用例-关联需求增加搜索栏，需求多不方便找

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8547]
**请描述您的需求或者改进建议.**

功能用例-关联需求增加搜索栏，需求多不方便找

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 功能用例-关联需求增加搜索栏，需求多不方便找
> 
> **请描述你建议的实现方案**

请提到metetsphere战区
