### ISSUE TITLE
[BUG]json传参“//”注释会自动换行到下一行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8548]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题
json传参“//”注释会自动换行到下一行
**Bug 重现步骤**

1.  请求体输入json参数
2. 点击xml
3. 点击json
![image](https://user-images.githubusercontent.com/36387811/146494726-cebcc2a7-40f8-4ebb-b794-2c3d238450e7.png)
![image](https://user-images.githubusercontent.com/36387811/146494767-27dd9674-ffb1-438f-8d3c-b7d9760ef87a.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，json 不支持注释，格式化 是我们使用的插件自动进行的格式化，暂时无法修改这个问题
