### ISSUE TITLE
[BUG]接口自动化转性能测试，断言中的“不等于”变成“等于”

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8550]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**

简要描述您碰到的问题
断言“不等于”在性能测试的时候为“等于”
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/146495971-7c27283f-b40d-422b-ad33-ed3f15efce8c.png)
![image](https://user-images.githubusercontent.com/36387811/146496007-535c2cce-2978-4eac-8d9f-f7a1924effd7.png)
![image](https://user-images.githubusercontent.com/36387811/146496079-8826008d-6fbf-4953-88db-6242f1056e8a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
