### ISSUE TITLE
[FEATURE]合并性能测试报告

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8552]
**请描述您的需求或者改进建议.**
性能测试报告只是一次的压测情况，同一个场景不同并发数的性能测试不能合并成一个报告。

**请描述你建议的实现方案**

**Comment by zhangzhaox** [comment]
选择性的场景合并，合并的内容已请求统计内容为基础即可，完成自定义事务测试报告展现的最终呈现形式
