### ISSUE TITLE
[FEATURE]场景中一键展开、一键收起改为悬浮状态

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8554]
**请描述您的需求或者改进建议.**
当场景很多的时候，想要一键收缩，要往上翻很久才能点击

**请描述你建议的实现方案**

![1639720951119](https://user-images.githubusercontent.com/36387811/146497058-b3f8be15-598b-4d2c-8362-dc59bcd25430.jpg)

**Comment by luty2018** [comment]
已提tapd 不要重复反馈
