### ISSUE TITLE
测试计划关联测试用例时应该可以指定执行人

### ISSUE THREAD

**Issue by zhu026** [metersphere/metersphere#856]
**请描述您的需求或者改进建议.**
现在测试计划在关联测试用例时，执行人是系统自动取操作这个关联用例的登录人员。建议在关联测试用例时可以指定执行人，这样测试经理在操作时可以将大的测试任务分不同用例给到不同的执行人

**请描述你建议的实现方案**
建议在关联测试用例时可以指定执行人

**Comment by wangzhen-fit2cloud** [comment]
你好，在关联用例页面去选择执行人操作不是很友好，可以在关联添加用例之后再去批量修改执行人
