### ISSUE TITLE
[QUESTION]使用portainer stack 创建完全控制的docker

### ISSUE THREAD

**Issue by wang-qa** [metersphere/metersphere#8570]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/58168764/146520323-a7e49498-f63e-4d74-8001-b0cd566574b8.png)
![image](https://user-images.githubusercontent.com/58168764/146520308-1fa623ec-4d23-4401-a5c2-52ffdad1014d.png)
![image](https://user-images.githubusercontent.com/58168764/146520349-58409382-3a0a-4c8d-9886-1d649fa56286.png)
我发现有多个 docker-compose*  我不知道如何配置，使其自动更新

![image](https://user-images.githubusercontent.com/58168764/146520800-1c0db97c-3775-4426-a7c3-990f5b881e39.png)

**Comment by wangzhen-fit2cloud** [comment]
由于存在多个可选的安装组件，目前我们是使用脚本拼接了多个 compose 文件，如果需要生成一个完整 compose 文件的话，可以修改完配置参数后，执行 msctl config 命令，生成最终的 compose 文件
