### ISSUE TITLE
[BUG]控制器不满足时，测试报告状态为error

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8572]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.4
**Bug 描述**

简要描述您碰到的问题
当场景中步骤是控制器，且当控制器条件不满足时，后续步骤无法执行时，测试报告状态为error
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，是添加条件控制器后，条件不满足，然后生成的测试报告状态是error ？
如果是这个步骤使用1.15.4版本没有这个问题，建议升级到新版本试试~
