### ISSUE TITLE
[BUG]测试计划配置定时任务后，部分测试计划重复执行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8574]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.4
**Bug 描述**

简要描述您碰到的问题
测试计划配置定时任务后，存在部分测试计划在同一个时间节点重复执行的情况，生成两份相同报告
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复
