### ISSUE TITLE
[BUG]测试计划执行报告中用例数与关联数不匹配

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8576]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.4
**Bug 描述**

简要描述您碰到的问题
测试计划执行完成后，测试计划中关联了1700+的用例，但是测试报告中只有500+ 用例
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
没有复现该问题，升级到较新版本试试吧，
