### ISSUE TITLE
[BUG]测试计划执行后错误用例数量错误

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8577]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.4
**Bug 描述**

简要描述您碰到的问题
测试计划选择资源池并发执行完成后：

1.测试计划报告中统计的错误用例 tab页数据统计不准确

2.测试计划报告中的用例状态与实际不符
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
没有复现了，升级到较新版本试试吧
