### ISSUE TITLE
[FEATURE]增加测试计划报告执行时间列

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8580]
**请描述您的需求或者改进建议.**
测试计划报告列表中只展示了结束时间，查看执行时长需要每个报告都得点进去，不太方便，也无法快速过滤出明显超时的测试计划，因此需要加一个测试计划报告执行时间列

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已排期 1.17 不要重复反馈
