### ISSUE TITLE
[BUG] 项目成员在项目中可以把项目管理员删除了

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8590]
**MeterSphere 版本**

1.15.4

**Bug 描述**

项目成员可以把项目管理员删除了

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by liuqiao1995** [comment]
正确情况应该是项目成员无法删除项目管理员

**Comment by zyyfit** [comment]
您好，请问您的 系统管理 - 系统 - 用户组与权限 页面，是否给项目成员配置了 可移除其他成员的权限？

**Comment by liuqiao1995** [comment]
> 您好，请问您的 系统管理 - 系统 - 用户组与权限 页面，是否给项目成员配置了 可移除其他成员的权限？

是的，里面有，虽然有，但是我觉得不管怎么样，不能把管理员本身删除掉的，管理员只能自己退出，或者系统管理员设置的。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会考虑优化一下

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6以上版本有控制删除的权限
