### ISSUE TITLE
[FEATURE]Jenkins插件场景测试执行失败无法终止执行过程

### ISSUE THREAD

**Issue by BigbigY** [metersphere/metersphere#8595]
**请描述您的需求或者改进建议.**
我有2个环境，一个测试，一个生产
jenkins job执行过程：
1、测试环境发布后，进行测试接口场景测试：如果失败就终止执行并退出，如果成功则继续执行生产环境发布部分
2、生产环境发布后，进行生产接口回归测试

还有一个问题是：
我场景测试选择返回结果是MeterSphere插件返回后，执行测试错误后，jenkins返回还是正常的

**请描述你建议的实现方案**
能否提供一个方法在MeterSphere进行场景测试后如果返回失败我们可以根据这个结果做下一步是否继续操作

**Comment by luty2018** [comment]
Jenkins配置的时候，你选择插件结果

**Comment by BigbigY** [comment]
![20220129131129](https://user-images.githubusercontent.com/16998173/151648358-122bd953-ef2f-48c0-8bbf-d5d671cc2192.jpg)
@luty2018 选择插件结果和jenkins结果都是一样的
