### ISSUE TITLE
[BUG] 性能测试 修改测试场景，会初始化启用已被禁用的线程组

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#8599]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.15.4
1、原始JMX线程组禁用时，创建场景初始化启用， 这点可接受，但第2点就体验不好
2、修改测试场景，会初始化启用已被禁用的线程组

![image](https://user-images.githubusercontent.com/82088551/146698516-edf3cbb0-6f51-4752-9144-53699b6bc15a.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没看懂你的复现步骤，请详细说明下吧~
1.创建性能测试perf001，
2.然后在perf001 中引用接口自动化场景A和场景B
3.禁用场景B，保存perf001
4.再次编辑perf001，引用接口自动化场景C
5. 场景B 的禁用状态被开启了 ？？？
是否是以上复现步骤？

**Comment by zhangzhaox** [comment]
一个JMX文件中有3个线程组，禁用其中的一个，2个启用。
1、第一次创建性能测试场景 导入的JMX文件解析后在MS上全部是启用的，   可接受
2、已保存好的场景2个启用一个禁用，再次编辑场景其他配置时 再次保存场景 会全部启用3个线程组

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，最新版本v1.16修复了这个问题，建议升级下吧
