### ISSUE TITLE
接口报告增加返回测试的功能

### ISSUE THREAD

**Issue by Ariel20180710** [metersphere/metersphere#86]
接口报告查看详情后想返回到测试编辑页面得重新搜索，能否在报告上面直接返回到测试编辑呢

**Comment by wangzhen-fit2cloud** [comment]
你好，通过截图所示的问题可以返回到接口测试编辑页面。
![image](https://user-images.githubusercontent.com/27671436/86549015-fbcd4e80-bf70-11ea-9df3-fb8d1ab79720.png)
