### ISSUE TITLE
[FEATURE]测试用例界面，模块所在的asider区域建议可拖放。

### ISSUE THREAD

**Issue by hongjojjay** [metersphere/metersphere#860]
**请描述您的需求或者改进建议.**
测试用例界面，模块所在的asider区域建议可左右拖放。

**请描述你建议的实现方案**
当模块层级比较多时，模块所在的asider显示不全，能否做成可左右拖放。

![image](https://user-images.githubusercontent.com/3347879/100710843-51583b00-33eb-11eb-9ceb-9f911a9b151a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，左侧树状列表拖动功能已实现，请更新试用。
