### ISSUE TITLE
[BUG] 自动化场景变更历史非常的慢，慢查询日志找到该SQL，有抑制索引的情况

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#8600]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？V1.15.4
 
![image](https://user-images.githubusercontent.com/82088551/146699505-79277396-6afe-4c27-918e-ad99b26acbdd.png)

**Comment by GITMrzk** [comment]
不止这个，还有性能变更历史、接口变更历史、单接口用例变更历史，都慢，请一起优化吧。
@zhangzhaox

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本已优化了，好很多，敬请期待！
