### ISSUE TITLE
[BUG]报告总结里面编辑完之后，无法保存到报告里面。

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8603]
**MeterSphere 版本**

v1.15.4-a1b8953b

**Bug 描述**

报告总结里面编辑完之后，无法保存到报告里面。

**Bug 重现步骤**

1.  报告总结编辑，随便写东西
2. 保存
3. 打开保存的报告
4. 

**期待的正确结果**

预期结果应该是报告里面有总结的数据。

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，请详细描述下你的问题，
我们这边相同的版本尝试复现步骤
1.创建报告
2.输入名称和收件人，
3.输入报告内容，添加报告内容的方式 ，输入一些问题，或者图片
4.保存草稿或者发送
5.报告列表页面 “预览“，正确显示输入的报告内容

![image](https://user-images.githubusercontent.com/54612864/146719926-82ee279e-24a4-4ddb-8085-916e2eb50581.png)
![image](https://user-images.githubusercontent.com/54612864/146719974-5ec20200-512c-485f-9a82-7a7765d72a90.png)

![image](https://user-images.githubusercontent.com/54612864/146720015-5534be7b-66c7-4ce5-aa8b-1f0d352b94f7.png)

**Comment by liuqiao1995** [comment]
@youliyuan-fit2cloud 你好，他是这样的，编辑之后无法保存
![image](https://user-images.githubusercontent.com/22763910/146866679-0152937e-aac5-4f65-8c21-e0999a5506ee.png)
![image](https://user-images.githubusercontent.com/22763910/146866732-aa646988-971a-4209-a86e-16c026214de5.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，是编辑测试计划的报告确实有问题，之前以为是项目报告那里

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
