### ISSUE TITLE
[FEATURE] 生成报告的时候，可以给报告重命名

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8604]
**请描述您的需求或者改进建议.**

生成报告的时候，可以给报告重命名

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
请列明是哪里的报告

**Comment by liuqiao1995** [comment]
> 请列明是哪里的报告

你好，是测试计划里面导出来的测试报告可以重命名吗
![image](https://user-images.githubusercontent.com/22763910/146866479-e47ac0d6-4f8e-4496-a91f-68149c292310.png)

**Comment by luty2018** [comment]
可以，已排期1.18版本
