### ISSUE TITLE
Helm 安装失败

### ISSUE THREAD

**Issue by FatuityCookie** [metersphere/metersphere#8605]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

1.30.0

**Bug 描述**

Error: error while running post render on files: error while running command /tmp/helm-operator/demo-project_metersp-av8wmq_jymx96p88z9q7p/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 97: mapping key "env" already defined at line 82 : exit status 1 

**Bug 重现步骤**

1.基础k8s平台，kubesphere  
2. 出现以上异常

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/46119806/146708483-852cbd04-a0f9-4410-ab22-4fc9c6b9d99b.png)

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，请问是使用的默认 values 进行安装的吗？
