### ISSUE TITLE
[FEATURE]用例评审中，建议在评论时可同时选择评审状态，这样在评审的消息推送中可以正确查看到对应的状态。

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8616]
### 使用难点
当前用例评审的功能中，无法在留评论之前标记评审状态（通过/不通过）。在这个前提下，如果配置了评论的消息推送，则在评审发出之后，推送消息中的评审状态会显示为Prepare，无法显示为Pass或Unpass。
![wecom-temp-d0d0674b37eb3855e566f7a2b1f9ecc9](https://user-images.githubusercontent.com/34698664/146731262-616bc8a0-a5db-466d-b6d1-744637d83cad.png)
<img width="319" alt="wecom-temp-b7ce60caa24ac0835c2b51d11dd912fa" src="https://user-images.githubusercontent.com/34698664/146731270-e08ee3a4-ec70-4fe5-82eb-508bff4be3bc.png">

### 建议方案
在评审的同时可以选择对应的评审状态，同步提交。并且在消息推送中显示评论所对应的评审状态。即将评论和评审状态绑定。

**Comment by luty2018** [comment]
待排期优化
