### ISSUE TITLE
采用双标签过长后，显示BUG[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#8617]
**MeterSphere 版本**
 v1.15.4

**Bug 描述**
1.  编辑任意一个接口，采用双标签，标签长度超过10位以上，如下图
![image](https://user-images.githubusercontent.com/30932762/146732758-c1134934-78f4-4a18-8dba-8b0568b7d73c.png)
2. 预览显示的时候，标签重叠合并了
![image](https://user-images.githubusercontent.com/30932762/146732861-63ebd882-0f40-4b69-896b-e870c196fd5e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，发现了,后续版本优化下！

**Comment by youliyuan-fit2cloud** [comment]
v1.16.2已解决
