### ISSUE TITLE
[FEATURE]消息模板中建议增加额外的变量

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8618]
### Jenkins消息
因为不是所有人都会点开报告来一个个看，通知里面如果有一个总览可能会比较直观一点
- 执行环境
- 接口用例数（成功/失败/总数）
- 场景用例数（成功/失败/总数）
- 开始时间
- 结束时间
### 用例评审的评论消息
- 评论内容

**Comment by luty2018** [comment]
目前企业版已经支持自定义通知内容

**Comment by Saco93** [comment]
> 目前企业版已经支持自定义通知内容

我这边指的是**额外的**变量，而不是自定义模板这个功能。你可以对照消息模板中已有的变量来看一下我的优化建议。
