### ISSUE TITLE
断言JSONPath中如果包含 ==会丢失

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#8619]
**MeterSphere 版本**

V1.15.4

**Bug 重现步骤**

1.  在接口断言中写入如下带有“==”断言：
![image](https://user-images.githubusercontent.com/30932762/146733962-2c2ffe24-db6f-4957-9fab-69b944b8a9a1.png)

2. 最后控制台断言，显示“==”被替换没了

![image](https://user-images.githubusercontent.com/30932762/146734045-6126b8be-628f-4d91-890d-9a5a81ccd709.png)

**Comment by zyyfit** [comment]
您好，我这边测试的是等号丢失了，但是断言结果是正确的，您的断言结果是正确的吗

**Comment by plateauandsp** [comment]
验证了下，确实断言结果还是OK的，就是显示上的问题。
![image](https://user-images.githubusercontent.com/30932762/146789065-c6fb0578-fa1e-45a2-b542-c61b2671354a.png)

![image](https://user-images.githubusercontent.com/30932762/146789055-1736d4c7-eab5-4b48-ab0d-e60da93a6a90.png)

**Comment by zyyfit** [comment]
好的，下个版本修复

**Comment by zyyfit** [comment]
1.16.0已修复
