### ISSUE TITLE
[FEATURE]SQL的查询结果，默认为table展示更加美观，同时table中字段和值存在错位的现象，见截图

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#862]
**请描述您的需求或者改进建议.**
1、SQL的查询结果，默认为table展示更加美观，
2、table中字段和值存在错位的现象
![image](https://user-images.githubusercontent.com/69206282/100714688-0fca8e80-33f1-11eb-9526-8f98fe4776ad.png)

**请描述你建议的实现方案**

**Comment by AgAngle** [comment]
你好，请问你使用的是什么浏览器？我这里用谷歌和火狐都是可以的
