### ISSUE TITLE
接口测试和用例全局环境选择逻辑混乱[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#8623]
**MeterSphere 版本**
V1.54.

简要描述您碰到的问题
接口用例测试时，如果这个用例没选择过环境，右上角上面选择了没用，必须手动选择一次。只有选择过环境的用例，后续执行的环境会和上面一样。批量执行接口用例时，环境必须选择，和右上角没有任何关系

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
