### ISSUE TITLE
[BUG] 性能测试导出的pdf有误

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#8625]
**MeterSphere 版本**
1.15.4

**Bug 描述**
性能测试在高级配置中添加被测系统监控，测试完成后导出性能测试报告，报告中有两个相同的服务器监控内容。

**截图**
![037ddf0558876ffe2fdcaec03308f7d](https://user-images.githubusercontent.com/8164903/146738790-55825532-c8ca-431b-9d5b-89487da14c85.png)
![123bc153c3bd0f20205bd88561da6f3](https://user-images.githubusercontent.com/8164903/146738834-5afa6114-9806-4a85-a462-0da13e813e02.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
导出pdf由于浏览器限制有很多问题，在1.18版本增加了性能测试报告分享功能，用来代替导出功能
