### ISSUE TITLE
[FEATURE]考虑增加钉钉登录集成

### ISSUE THREAD

**Issue by scott-wong** [metersphere/metersphere#8629]
**请描述您的需求或者改进建议.**
目前已支持LDAP，建议增加钉钉登录集成，或支持OAuth/OIDC集成。

**请描述你建议的实现方案**
可考虑同时支持企业微信、钉钉、飞书，或优先支持标准OAuth/OIDC

**Comment by plateauandsp** [comment]
看官网说企业版本是支持OAuth/OIDC单点登录的，你可以联系MeterSphere官网看看

**Comment by luty2018** [comment]
这个已经规划在我们企业版本了， 可以联系商务试用
