### ISSUE TITLE
[FEATURE]很多公司连接数据库前 需要连接跳板机或者沙箱，希望增加连接连接跳板机或者沙箱的功能，然后可以畅通的链接数据库

### ISSUE THREAD

**Issue by 2115055005** [metersphere/metersphere#863]
**请描述您的需求或者改进建议.**
很多公司连接数据库前 需要连接跳板机或者沙箱，希望增加连接连接跳板机或者沙箱的功能，然后可以畅通的链接数据库

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，目前该问题没有很好的解决方案，请问你们目前是如何解决的，有什么建议吗？
