### ISSUE TITLE
[BUG]mock匹配请求头校验问题

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#8638]
**MeterSphere 版本**

1.15.4

**Bug 描述**

发送的入参请求为xml文本，无请求头，mock中未设置请求头，结果无法找到匹配的Mock期望，但入参中添加上请求头Content-Type-text/xml，mock匹配成功

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
mock中未设置请求头，应该不校验请求头中的内容，任何请求头均可以匹配

**截图**
无请求头
![image](https://user-images.githubusercontent.com/40912823/146750690-f198b3c3-31eb-4112-92d4-ee7c19bb8eef.png)
加入请求头text/xml
![image](https://user-images.githubusercontent.com/40912823/146750860-0befd157-2363-4bcf-be53-a13ffe6bc92f.png)
mock配置
![image](https://user-images.githubusercontent.com/40912823/146751005-e853f3d7-60a8-48ab-b29f-e5baf08ec9ef.png)

**Comment by zyyfit** [comment]
您好，发送xml的请求体默认是需要带content-type请求头的，但是我们的mock没有默认添加content-type请求头，我们会优化一下这个地方

**Comment by wszbc** [comment]
> 您好，发送xml的请求体默认是需要带content-type请求头的，但是我们的mock没有默认添加content-type请求头，我们会优化一下这个地方

问题就在这里，这个是第三方接口他传的数据是个xml但请求头是text/plain，生产上已经是正常运行的接口，再不改代码情况下所以希望的是mock不填的时候能够不校验请求头，我试过mock请求头加上text/plain，这样也无法匹配到

**Comment by wszbc** [comment]
> 您好，发送xml的请求体默认是需要带content-type请求头的，但是我们的mock没有默认添加content-type请求头，我们会优化一下这个地方

问题就在这里，这个是第三方接口他传的数据是个xml但请求头是text/plain，生产上已经是正常运行的接口，再不改代码情况下所以希望的是mock不填的时候能够不校验请求头，我试过mock请求头加上text/plain，这样也无法匹配到

**Comment by zyyfit** [comment]
> > 您好，发送xml的请求体默认是需要带content-type请求头的，但是我们的mock没有默认添加content-type请求头，我们会优化一下这个地方
> 
> 问题就在这里，这个是第三方接口他传的数据是个xml但请求头是text/plain，生产上已经是正常运行的接口，再不改代码情况下所以希望的是mock不填的时候能够不校验请求头，我试过mock请求头加上text/plain，这样也无法匹配到

咦？我这里测试的是，

mock里不加请求头，实际请求也不加，返回匹配不到

mock里不加请求头，实际请求加请求头，可以匹配到

mock里加请求头，实际请求加请求头，可以匹配到

如果您那边和这个结果不一致的话，方便把带mock的接口信息导出来给我们看看吗？

**Comment by wszbc** [comment]
> plain
[Metersphere_Api_POS系统.json.zip](https://github.com/metersphere/metersphere/files/7749406/Metersphere_Api_POS.json.zip)去掉.zip
我感觉是请求头和实际内容是不是做了处理，传的是xml 但是请求头是text/plain，mock里面入参校验了是否是xml内部自动锁定了请求头要是xml，其实我希望的是不填就不校验请求头了

**Comment by zyyfit** [comment]
> 我感觉是请求头和实际内容是不是做了处理，传的是xml 但是请求头是text/plain，mock里面入参校验了是否是xml内部自动锁定了请求头要是xml，其实我希望的是不填就不校验请求头了

mock匹配里，我们是通过请求头来寻找合适的mock匹配的。 比如请求头中传入text/xml，那么就会寻找请求格式为xml的mock匹配，这个时候是能匹配到的。请求头中传入text/plain，就不会寻找请求体是xml的mock匹配了，所以会匹配不到。

如果您是xml的请求头匹配不到xml的mock请求，我们会修复一下这个问题，如果是其他请求头如plain、json等，匹配不到xml的mock请求，我们目前就是这样设计的

**Comment by wszbc** [comment]
> > 我感觉是请求头和实际内容是不是做了处理，传的是xml 但是请求头是text/plain，mock里面入参校验了是否是xml内部自动锁定了请求头要是xml，其实我希望的是不填就不校验请求头了
> 
> mock匹配里，我们是通过请求头来寻找合适的mock匹配的。 比如请求头中传入text/xml，那么就会寻找请求格式为xml的mock匹配，这个时候是能匹配到的。请求头中传入text/plain，就不会寻找请求体是xml的mock匹配了，所以会匹配不到。
> 
> 如果您是xml的请求头匹配不到xml的mock请求，我们会修复一下这个问题，如果是其他请求头如plain、json等，匹配不到xml的mock请求，我们目前就是这样设计的

了解了，那text/plain请求头我要怎么去写mock，我在raw里面mock也无法匹配出数据

**Comment by wszbc** [comment]
> > 我感觉是请求头和实际内容是不是做了处理，传的是xml 但是请求头是text/plain，mock里面入参校验了是否是xml内部自动锁定了请求头要是xml，其实我希望的是不填就不校验请求头了
> 
> mock匹配里，我们是通过请求头来寻找合适的mock匹配的。 比如请求头中传入text/xml，那么就会寻找请求格式为xml的mock匹配，这个时候是能匹配到的。请求头中传入text/plain，就不会寻找请求体是xml的mock匹配了，所以会匹配不到。
> 
> 如果您是xml的请求头匹配不到xml的mock请求，我们会修复一下这个问题，如果是其他请求头如plain、json等，匹配不到xml的mock请求，我们目前就是这样设计的

了解了，那text/plain请求头如何设置mock，我将消息改成在raw中也是无法匹配到的

**Comment by zyyfit** [comment]
text/plain的使用raw就可以，不过raw需要完全匹配，不是标签匹配，这个版本可能是有bug，1.16.0修复

**Comment by zyyfit** [comment]
1.16已修复
