### ISSUE TITLE
[BUG] jmeter-functions中的mock无效

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#8642]
**MeterSphere 版本**
1.15.4

**Bug 描述**
jmeter-functions中的${__Mock(@integer)}无效

**截图**
![image](https://user-images.githubusercontent.com/8164903/146757557-fb305b27-4e93-40c8-85e2-dd900b817291.png)

**Comment by zyyfit** [comment]
您好，这种写法jmeter也不支持的，ms里可以直接使用@xxx
![图片](https://user-images.githubusercontent.com/73461316/146763106-a4f3caf5-7058-4146-b178-55e7ec4a4ca3.png)

**Comment by tangw1257** [comment]
jmeter-functions是你们自己提供的包呀，你需要导入到jmeter中
我昨天又试了试，${__Mock(@integer)} 是可以的。
上面图片的内容中如果${__Mock(@integer)}排在第一个是可以的，但是${__Mock(@pick)}无法解析，如果还有其他的${__Mock(xxx)}在这个恩无法解析的 ${__Mock(@pick)}之后，那么即便能解析也会导致无法解析出。

**Comment by zyyfit** [comment]
> jmeter-functions是你们自己提供的包呀，你需要导入到jmeter中 我昨天又试了试，${__Mock(@integer)} 是可以的。 上面图片的内容中如果${__Mock(@integer)}排在第一个是可以的，但是${__Mock(@pick)}无法解析，如果还有其他的${__Mock(xxx)}在这个恩无法解析的 ${__Mock(@pick)}之后，那么即便能解析也会导致无法解析出。

哦不好意思，我们这个包里的函数可以在jmeter里查看写法的，pick要这样使用
![图片](https://user-images.githubusercontent.com/73461316/146882300-359405a1-3774-4b6f-b296-468558e0e50d.png)

**Comment by tangw1257** [comment]
感谢
