### ISSUE TITLE
长JSON请求用例和接口自动化测试成功，但是实际保存丢失[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [metersphere/metersphere#8650]
**MeterSphere 版本**
V1.5.4

**Bug 描述**
一个长格式的JSON进行接口用例测试通过，保存后丢失。JSON体说明：
1.因为涉及到数字，key-vlau的vlau不能加“”号，所以MeterSphere的会提示JSON格式错误；
2.这个类型的JSON必须为长JSON才会出现，短的不会，所以项目组验证的时候参考下面JSON：
{

    "clientRequestId":"${__eval(${clientRequestId})}",

    "clientRequestTime":"${__eval(${clientRequestTime})}",

    "serviceReqTime":${__eval(${serviceReqTime})},

    "calculatePolicy":{

        "extFields":{

            "countLA":${__eval(${calculatePolicy_extFields_countLA})},

            "floaterPlanIndi":${__eval(${calculatePolicy_extFields_floaterPlanIndi})},

            "indexRate":${__eval(${calculatePolicy_extFields_indexRate})}

        },

        "inceptionDate":"${__eval(${inceptionDate})}",

        "coverages":[

                {

                "extFields":{

                    "deductibleOption":${__eval(${coverages1_extFields_coverMultiplevalue})},

                    "coverMultiplevalue":"${__eval(${coverages1_extFields_coverMultiplevalue})}",

                    "premType":${__eval(${coverages1_extFields_premType})}

                },

                "coverageId":${__eval(${coverages1_coverageId})},

                "masterCoverageId":${__eval(${coverages1_masterCoverageId})},

                "chargePeriod":"${__eval(${coverages1_chargePeriod})}",

                "chargeYear":${__eval(${coverages1_chargeYear})},

                "coveragePeriod":"${__eval(${coverages1_coveragePeriod})}",

                "coverageYear":${__eval(${coverages1_coverageYear})},

                "productCode":"${__eval(${coverages1_productCode})}",

                "calculatePremium":{

                    "extFields":${__eval(${coverages1_calculatePremium_extFields})},

                    "paymentFreq":${__eval(${coverages1_calcP_Freq})},

                    "sumAssured":${__eval(${coverages1_calculatePremium_sumAssured})},

                    "premium":${__eval(${coverages1_calculatePremium_premium})},

                    "unit":${__eval(${coverages1_calculatePremium_unit})},

                    "benefitLevel":${__eval(${coverages1_calculatePremium_benefitLevel})}

                },

                "waivedSa":${__eval(${coverages1_waivedSa})},

                "insureds":[

                    {

                        "extFields":${__eval(${coverages1_insureds1_extFields})},

                        "orderId":${__eval(${coverages1_insureds1_orderId})},

                        "gender":"${__eval(${coverages1_insureds1_gender})}",

                        "birthdate":"${__eval(${coverages1_insureds1_birthdate})}",

                        "age":${__eval(${coverages1_insureds1_age})},

                        "smoking":"${__eval(${coverages1_insureds1_smoking})}",

                        "occupationCode":${__eval(${coverages1_insureds1_occupationCode})},

                        "occupationClass":${__eval(${coverages1_insureds1_occupationClass})},

                        "medicalIndi":"${__eval(${coverages1_insureds1_medicalIndi})}",

                        "socialSecurityIndi":"${__eval(${coverages1_insureds1_socialSecurityIndi})}"

                    }

                ],

                "annuity":${__eval(${coverages1_annuity})},

                "funds":${__eval(${coverages1_funds})},

                "topupWithdrawns":${__eval(${coverages1_topupWithdrawns})},

                "mortgageRates":${__eval(${coverages1_mortgageRates})}

            }

        ]

    }

}

**Bug 重现步骤**

1.  随便创建一个接口CASE，请求体选择JSON，复制上面JSON报文
![image](https://user-images.githubusercontent.com/30932762/146796711-9b7f7ec4-e15a-4acb-a322-ad16fdce5219.png)

2. 选择运行用例，用例可以正常运行，点击保存用例，提示保存成功。但是这时点击下xml格式或者raw格式，后在切换为JSON格式，发现请求体丢失，保存后关闭用例，然后重新打开也是丢失。
![image](https://user-images.githubusercontent.com/30932762/146796881-dd3a9565-4658-4bbe-8d55-52654704252e.png)

3.个人也验证了，如下这种小的JSON请求体不会丢失，所以感觉很奇怪，不知道为什么
{
   “key01”:01,
   "key02":02
}

**期待的正确结果**
JSON格式校验只是辅助手动，应该不能影响强制保存等，不管大小JSON应该都可以保存

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/146855074-86784b08-5335-4161-be38-63507c1f67cc.png)

加上”“ 号吧，不然json校验失败

**Comment by plateauandsp** [comment]
我知道加上可以保存，但是不能加上“”，因为加上后变成了字符串，服务端要求的是数字。而且此问题和加不加“”没关系，因为我已经验证厂商了在小的不规范的JSON（如下）其实是可以保存和运行的。但是我上面贴的JSON就不能保存。所以不能保存丢失的BUG和JSON是否通过检验没有关系。
{
“key01”:01,
"key02":02
}
希望项目组按照我给的方案进行验证

**Comment by youliyuan-fit2cloud** [comment]
了解了，后续版本优化下这里，感谢~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本已修复~
