### ISSUE TITLE
[BUG]Arbitrary File Read Vulnerability in v1.15.4

### ISSUE THREAD

**Issue by rainmanzzz** [metersphere/metersphere#8652]
# Version
v1.15.4

# Description
Authenticated users can read arbitrary file on the server with the file download funtion.

API: /api/automation/file/download 

Vulnerable source code:
ApiAutomationService.java
```
    public byte[] loadFileAsBytes(FileOperationRequest fileOperationRequest) {
        File file = new File(FileUtils.BODY_FILE_DIR + "/" + fileOperationRequest.getId() + "_" + fileOperationRequest.getName());
        try (FileInputStream fis = new FileInputStream(file);
             ByteArrayOutputStream bos = new ByteArrayOutputStream(1000);) {
            byte[] b = new byte[1000];
            int n;
            while ((n = fis.read(b)) != -1) {
                bos.write(b, 0, n);
            }
            return bos.toByteArray();
        } catch (Exception ex) {
            LogUtil.error(ex);
        }
        return null;
    }
```

# To Reproduce
I have tested this vulnerability on the demo website https://demo.metersphere.com/.
Use the payload below and we successfully read the /etc/passwd
![image](https://user-images.githubusercontent.com/26007706/146804175-926ab422-3f5d-45d2-8d28-4163f2e33185.png)

**Comment by youliyuan-fit2cloud** [comment]
Thanks very much for your discovery，we will fixed it within next version.
