### ISSUE TITLE
[BUG]场景用例里切换数据库名-保存，再进来看数据库名不是上次保存的数据库名

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#8654]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.15.4

**Bug 描述**
场景用例里切换数据库名-保存，再进来看数据库名不是上次保存的数据库名

**截图**

![image](https://user-images.githubusercontent.com/32027713/146859130-5ad81c22-6033-448e-b11a-9aae98b26795.png)
![gif(2)](https://user-images.githubusercontent.com/32027713/146859137-8d497d9a-e9bb-4840-acc0-8ca8be89363d.gif)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.16.0已修复
