### ISSUE TITLE
[BUG]测试计划部分接口用例未执行

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8659]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.5
**Bug 描述**

简要描述您碰到的问题
测试计划中部分接口用例未执行
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/146864100-0ca075be-7da2-418c-86db-c6bd8a030143.png)

**Comment by youliyuan-fit2cloud** [comment]
下个版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本测试计划优化了之后没有复现了，升级一下吧
