### ISSUE TITLE
[BUG]测试计划场景用例执行了报告为空

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8660]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.5
**Bug 描述**

简要描述您碰到的问题
测试计划中的场景用例执行了，但是点击报告查看，内容为空。

**Bug 重现步骤**

1.  创建一个测试计划
2. 添加多个场景
3. 执行
4. 查看报告

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="1332" alt="截屏2021-12-20 下午10 27 45" src="https://user-images.githubusercontent.com/36387811/146864564-76b724fb-f966-4399-b4af-391631310dec.png">

**Comment by zyyfit** [comment]
您好，1.15.4没有复现这个问题，建议升级后试试
