### ISSUE TITLE
[BUG]失败后不继续，在性能测试中不生效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8663]
**MeterSphere 版本**
1.10.8-lts  1.10.11-lts

**Bug 描述**

在场景中不勾选失败继续，然后创建性能测试，在性能测试中，失败后的步骤也执行了

**Bug 重现步骤**

<img width="635" alt="1111111111" src="https://user-images.githubusercontent.com/88763608/146866340-64f461c5-bf95-4ae1-8284-ab6cb1a5dbe4.png">
<img width="913" alt="2222222222222" src="https://user-images.githubusercontent.com/88763608/146866353-e98400ab-cd8f-4f7b-b3ea-84d0b5a92a0c.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复~
