### ISSUE TITLE
API 定时任务执行中  等待时间不生效，但是在单独调试时等待时间是生效的

### ISSUE THREAD

**Issue by jason-000** [metersphere/metersphere#8668]
**MeterSphere 版本**

版本:   v1.15.4-a1b8953b

**Bug 描述**

简要描述您碰到的问题

API 定时任务执行中  等待时间不生效，但是在单独调试时等待时间是生效的

**Bug 重现步骤**

1.  给一个请求加等待时间
2. 添加到定时任务里
3. 跑完后查看请求发送时间间隔
4. 注意的是 添加了4个合单的任务，前面3个等待时间没有生效，最后1个却生效了

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/43231635/146869076-4b7dc541-16ee-4800-865a-b7609e8a8211.png)

实际上等待时间不生效，如下：
![image](https://user-images.githubusercontent.com/43231635/146869386-16c1d4b7-2207-4468-a337-829f0b358e13.png)

定时任务中有4个脚本，最后1个脚本等待时间生效了
![image](https://user-images.githubusercontent.com/43231635/146869685-00ccb2a9-b42c-466a-9102-e1db4232aecd.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by jason-000** [comment]
补充一个新的issue  

状态不一致,如下图：
![image](https://user-images.githubusercontent.com/43231635/147176046-adf92d73-204d-4af0-8afc-b3d4be084359.png)

**Comment by youliyuan-fit2cloud** [comment]
> 补充一个新的issue
> 
> 状态不一致,如下图： ![image](https://user-images.githubusercontent.com/43231635/147176046-adf92d73-204d-4af0-8afc-b3d4be084359.png)

最新版有优化这里，建议升级下

**Comment by zyyfit** [comment]
1.16.0已修复
