### ISSUE TITLE
[BUG]性能测试导出报告请求统计数据不全

### ISSUE THREAD

**Issue by chaoxyCode** [metersphere/metersphere#8677]
**MeterSphere 版本**
15.4
您所使用的 MeterSphere 版本是？
v1.15.4-b3
**Bug 描述**

简要描述您碰到的问题
 性能测试导出报告请求统计数据不全，测试请求数一共28个，导出为8个
**Bug 重现步骤**
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by chaoxyCode** [comment]
<img width="1393" alt="1" src="https://user-images.githubusercontent.com/18453166/146884187-ad7c312b-7339-4448-92ae-556cdb037c29.png">
<img width="1431" alt="2" src="https://user-images.githubusercontent.com/18453166/146884219-81771c1d-76d9-4250-ab3b-b83114858eaa.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个小版本修复这个问题了~

**Comment by zyyfit** [comment]
导出pdf由于浏览器限制有很多问题，1.18有分享功能代替这个
