### ISSUE TITLE
[FEATURE] 记住上一次运行api或者case时使用的环境

### ISSUE THREAD

**Issue by dronl** [metersphere/metersphere#8704]
**请描述您的需求或者改进建议.**

目前每次执行一个api都需要自己选择运行环境，非常不方便

**请描述你建议的实现方案**

建议用户在选择一次环境并执行以后，下次打开一个新的api就默认选中这个环境（用户如果需要切换可以再换）

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/147552108-19e135cd-d52c-4bfc-aa4f-b6df1c62f605.png)
目前已经实现了
