### ISSUE TITLE
[FEATURE]默认使用之前的环境

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8718]
**请描述您的需求或者改进建议.**

已经选择了某个环境，下次打开一个新api或者用例运行的时候，能不能就默认使用之前的环境

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/147552802-c0ea8427-d2f0-4803-8aa0-746508776d59.png)
用这个
