### ISSUE TITLE
[FEATURE]容器最好在前面都加一下ms的标识

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8721]
**请描述您的需求或者改进建议.**

容器最好在前面都加一下ms的标识可能会好一点。要不同一台机器我们安装了其他的应用容器同名的话就不太好辨认。类似jumpserver的话他们会再他们的容器前面加一个jms_mysql 这样的

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> 容器最好在前面都加一下ms的标识可能会好一点。要不同一台机器我们安装了其他的应用容器同名的话就不太好辨认。类似jumpserver的话他们会再他们的容器前面加一个jms_mysql 这样的
> 
> **请描述你建议的实现方案**

请提到metershpere战区
