### ISSUE TITLE
[BUG] 集成 jira 创建任务失败

### ISSUE THREAD

**Issue by vast0906** [metersphere/metersphere#8731]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.12.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
0. JIRA 侧找到对应字段
![image](https://user-images.githubusercontent.com/18095287/147050353-4e5cca0c-3915-438e-9be1-426f72ba9860.png)

1.  添加自定义字段 
![image](https://user-images.githubusercontent.com/18095287/147050047-d117e739-338d-4c6c-8656-d50d998d5260.png)
2. 默认模板
![image](https://user-images.githubusercontent.com/18095287/147050130-68783d73-d3e0-4330-a36d-d43322613979.png)
3.  创建缺陷
![image](https://user-images.githubusercontent.com/18095287/147050438-bcfa1cad-6b21-4ef7-8ce3-28027b6e6aa1.png)

![image](https://user-images.githubusercontent.com/18095287/147050507-ba8dfa9c-f5b0-4e51-941f-b09b9f9df1cd.png)
通过  JIRA 搜索  spint id 是存在的  但是   metersphere 创建 issus 的时候   会提示 
400 : [{"errorMessages":["数字值预期为Sprint ID。"],"errors":{}}]

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化

**Comment by luty2018** [comment]
建议更新到最新版本 目前已经支持直接读取jira模板
