### ISSUE TITLE
[BUG]系统设置、环境管理、创建环境组选择项目后，然后X掉就不能再次选择了

### ISSUE THREAD

**Issue by Sensivitiry** [metersphere/metersphere#8735]
**MeterSphere 版本**
1.15.4
您所使用的 MeterSphere 版本是？

**Bug 描述**
系统设置环境管理创建环境组的时候，选择项目，然后X掉，就不能再次选择了，就是只能选择一次。
简要描述您碰到的问题

**Bug 重现步骤**

1.  点击系统设置 
2. 然后点击环境管理
3. 创建环境组
4. 选择项目，然后X掉

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="736" alt="8f4da024ba22cff65df8e7215098eb7" src="https://user-images.githubusercontent.com/85992665/147056989-12328c7a-742a-4249-a3ef-c7d4f44faa0e.png">
<img width="644" alt="d3c4215223ead0eab25f3c1030ca5d1" src="https://user-images.githubusercontent.com/85992665/147057016-d6ee0c52-b60a-4438-9fff-bf61d254105a.png">
<img width="657" alt="991520bfcfd58eab971bf0c632384ff" src="https://user-images.githubusercontent.com/85992665/147057034-feb5f832-a17b-4344-a396-082decf10344.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下，
你可以重新编辑这个环境组就可以添加了

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本中已修复~
