### ISSUE TITLE
Jmeter脚本迁移到MS平台以后，无法识别到从"Response Headers"中获取字符串。[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#8739]
**MeterSphere 版本**
1.5.4

**Bug 描述**

1.通过Regular Expression Extractor去获取Response Headers中的某个字符串。
2.将该Jmeter脚本迁移到MS平台以后，无法识别到我是要从"Response Headers"中获取字符串。

**截图**

![image](https://user-images.githubusercontent.com/35896106/147060083-ce6733c4-1688-4cf8-9271-363218485ddf.png)

![image](https://user-images.githubusercontent.com/35896106/147060336-ca564301-8bb2-4238-a77e-b57ecf959299.png)

**Comment by weishuo6** [comment]
1.15.4版本

**Comment by youliyuan-fit2cloud** [comment]
你好，1.15.4版本没有复现这个问题，建议检查jmx脚本

**Comment by weishuo6** [comment]
1.16.1版本测试已经解决
