### ISSUE TITLE
[BUG]重定向问题

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8740]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.4
**Bug 描述**

简要描述您碰到的问题
http请求使用postman重定向成功，使用Metersphere返回308，使用https才能返回正确响应结果
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![1640161989606](https://user-images.githubusercontent.com/36387811/147062207-395d8665-6db5-465b-8d8a-91adaa95932c.jpg)
![1640162038586](https://user-images.githubusercontent.com/36387811/147062215-ecbe5a80-53f5-4615-9e5b-6d39744b5d41.jpg)

**Comment by zyyfit** [comment]
您好，接口编辑页面里-其他设置，有设置是否自动跟随重定向的地方，您勾选自动重定向试试？
