### ISSUE TITLE
[BUG]接口列表ID出现重复值

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#8745]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15.4

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  可能是在并发场景下触发的BUG

**期待的正确结果**

正确情况下应该是什么样的？
  接口列表ID（api_definition.num）字段值需要添加唯一约束

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/89765365/147067331-ba3e15cb-333d-45e6-94d9-2900a2528730.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by luty2018** [comment]
未重现 建议更新至最新版本 如有问题再反馈 谢谢
