### ISSUE TITLE
[BUG]接口自动化共享cookie会丢失引号

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8768]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
原本cookie是带引号的，但是在场景中点击了共享cookie，执行时会报错，因为cookie少了引号，通过浏览器抓包，cookie是有引号的
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，请附上截图吧，没办法复现

**Comment by happyend1709** [comment]
> 你好，请附上截图吧，没办法复现

![image](https://user-images.githubusercontent.com/36387811/147327687-55f1db46-966d-4ef9-87e0-375ca1814df3.png)
这是抓包的，
![image](https://user-images.githubusercontent.com/36387811/147327915-2ee7142c-6b51-4bfa-bbdd-48a41041c507.png)
这是Metersphere的，然后报错
![image](https://user-images.githubusercontent.com/36387811/147327972-3b3eeca6-0d57-43f2-bb57-75656bb23368.png)

**Comment by youliyuan-fit2cloud** [comment]
收到，后续版本优化下，token带引号也是比较少见的场景。

**Comment by youliyuan-fit2cloud** [comment]
你好，Jmeter 的bug，我们下提交给Jmeter了 ~~
