### ISSUE TITLE
查看用例的交互

### ISSUE THREAD

**Issue by cyt68** [metersphere/metersphere#877]
**请描述您的需求或者改进建议.**

查看用例是鼠标放上去显示这个交互也太反人类了啊，而且里面文字多一点就要手动去拖动，这个真的无语。。。

**请描述你建议的实现方案**
查看用例要点击弹窗显示，并且有上一条下一条选项，里面的文字框默认高一点不要每次都需要拖动

**Comment by wangzhen-fit2cloud** [comment]
你好，鼠标悬停在用例名称上时是预览用例内容，点击用例ID及编辑按钮均可进入用例编辑页面。
