### ISSUE TITLE
[BUG]API Case执行人错误

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8774]
**MeterSphere 版本**

1.16.0

**Bug 描述**

Case执行人错误

**Bug 重现步骤**

1.  用户Saco执行API Case A
2. 执行完成后查看执行历史，结果显示是Grace执行了Case A

**期待的正确结果**

显示正确的执行人

**截图**

![image](https://user-images.githubusercontent.com/34698664/147203679-2bd04c8a-8f98-491b-a022-6ba15279f423.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，看你这个截图 Grace 用户执行的定时任务，不是Saco用户手动执行的该api case，请确认下吧

**Comment by Saco93** [comment]
> 你好，看你这个截图 Grace 用户执行的定时任务，不是Saco用户手动执行的该api case，请确认下吧

报的就是这个问题啊，因为就是Saco用户执行的

**Comment by youliyuan-fit2cloud** [comment]
> > 你好，看你这个截图 Grace 用户执行的定时任务，不是Saco用户手动执行的该api case，请确认下吧
> 
> 报的就是这个问题啊，因为就是Saco用户执行的

这个定时任务 是不是Grace 创建的啊 ？如果是执行人就是他啊。。
![image](https://user-images.githubusercontent.com/54612864/147211793-ec9447d4-2420-47e8-874d-7bcc295c0411.png)

**Comment by youliyuan-fit2cloud** [comment]
貌似确实有问题，这个定时任务是测试计划里面添加的吧，如果这个测试计划的创建人是GraceGu，即是创建定时任务的是Saco，任务通知里面也是GraceGu。。。后续版本优化下

**Comment by Saco93** [comment]
> 貌似确实有问题，这个定时任务是测试计划里面添加的吧，如果这个测试计划的创建人是GraceGu，即是创建定时任务的是Saco，任务通知里面也是GraceGu。。。后续版本优化下

本来想再复现一下这个问题来提供更多信息，但是被下面这个Bug阻塞了：
https://github.com/metersphere/metersphere/issues/8807#issue-1088124030

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已解决
