### ISSUE TITLE
[BUG]脑图界面添加模块和用例保存成功后，切换到列表界面，新添加的模块和用例未查询出来，再切换到脑图界面后之前新添加的模块和用例均看不见，重新添加时提示模块名已存在的

### ISSUE THREAD

**Issue by wjjoai** [metersphere/metersphere#8775]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15.4及以前版本

**Bug 描述**

脑图界面添加模块和用例保存成功后，切换到列表界面，新添加的模块和用例未查询出来，再切换到脑图界面后之前新添加的模块和用例均看不见，重新添加时提示模块名已存在的

**Bug 重现步骤**

1.  脑图界面添加模块一
2. 模块一下添加用例1和用例2后保存
3. 切换到列表界面
4. 再切换到脑图界面

**期待的正确结果**
切换到列表界面后新添加的模块和用例均可以刷新出来
于切换到脑图界面后可以正常看见新添加的用例

**实际结果**
脑图界面保存成功后左边导航栏会同时刷新用例数
切换到列表界面后未刷新出新用例，导致列表的用例数和导航栏的用例数不一样
再切换到脑图界面后之前新添加的模块和用例均看不见，再重新添加时提示模块名已存在
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/28913533/147204224-02e77b12-9f60-4f5b-aa73-23cf20a21a7b.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题

切换到列表页面，是否点击下模块名，这样列表会更新下，怀疑没有立即更新
