### ISSUE TITLE
[BUG]接口详情-变更历史无变更详情日志

### ISSUE THREAD

**Issue by hzhfit2cloud** [metersphere/metersphere#8776]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
    版本:   v1.15.4-a1b8953b

**Bug 描述**

简要描述您碰到的问题
    接口详情--变更历史，TCP\DUBBO类型接口修改请求参数在查看详情的日志详情中看不到变更记录
    接口详情--变更历史，TCP\HTTP\SQL\DUBBO类型接口修改"其他信息"，不会录入到变更历史中
**Bug 重现步骤**

1.  接口测试--接口定义
2. 点击接口进入接口详情
3. 修改请求参数，点击保存
4. 点击“变更历史”，“查看详情”，“日志详情”中的内容为空
5. 修改“其他信息”中的“备注”
6. 点击“变更历史”，未出现新的变更记录

**期待的正确结果**

正确情况下应该是什么样的？
1. HTTP、SQL协议修改请求参数能查看到变更日志详情，是正常情况
2. 修改其他信息应该也要能看到变更日志详情

**截图**
![image](https://user-images.githubusercontent.com/89765365/147204571-cd03c932-61d8-446e-8946-8a8d1a8a405e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复

**Comment by zyyfit** [comment]
1.19.2已修复
