### ISSUE TITLE
[FEATURE]系统设置->服务集成中配置jira集成，建议支持配置问题类型的自定义字段及默认值

### ISSUE THREAD

**Issue by CarlJChen** [metersphere/metersphere#879]
**请描述您的需求或者改进建议.**

建议支持配置问题类型的自定义字段及默认值

**请描述你建议的实现方案**
提供配置除title，操作步骤、预期结果、实际结果之外的自定义必填项以及默认值的json对象

**Comment by wangzhen-fit2cloud** [comment]
你好，请问是否有可参考的支持使用自定义模板创建 jira issue 的实现？

**Comment by youliyuan-fit2cloud** [comment]
和 #1102 问题相同，关闭该issue，请持续关注后续版本～
