### ISSUE TITLE
[BUG]集成jira时选择使用jira模板复选框，创建缺陷时报错

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#8793]
**MeterSphere 版本**
1.16。0
您所使用的 MeterSphere 版本是？
1.16.0
**Bug 描述**
集成jira时选择使用jira模板复选框，创建缺陷时报错
简要描述您碰到的问题

**Bug 重现步骤**

1.  集成jira时选择使用jira模板复选框
2. 创建缺陷时报错
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
创建缺陷正常
**截图**
<img width="405" alt="11" src="https://user-images.githubusercontent.com/83771182/147221682-3b5c0104-0de6-47bf-b0a6-fa30904a6f07.png">
<img width="943" alt="22" src="https://user-images.githubusercontent.com/83771182/147221705-fbf5bdae-aea5-4c7c-a1ea-67374178c83c.png">

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题 ，您jira的复选框是什么样的，方便截图看一下吗？
![图片](https://user-images.githubusercontent.com/73461316/147228765-e4653c73-4d77-4ff4-9bdb-abf91fe023b7.png)
![图片](https://user-images.githubusercontent.com/73461316/147228824-3a888116-33aa-4428-ba44-617baca652af.png)

**Comment by yaoyi111** [comment]
您好，是使用jira权限模板后，缺陷管理报的问题。
地址http://democenter.fit2cloud.com:2708/#/track/issue   admin   metersphere




姚祎
北区解决方案架构师，FIT2CLOUD 飞致云
Mobile: 18901309700
北京市朝阳区东三环中路7号财富中心写字楼 A 座 715 室

中国领先的多云管理平台软件及服务提供商
Gartner 2018 Cool Vendor
***@***.***
 
发件人： zyyfit
发送时间： 2021-12-23 18:41
收件人： metersphere/metersphere
抄送： yaoyi111; Author
主题： Re: [metersphere/metersphere] [BUG]集成jira时选择使用jira模板复选框，创建缺陷时报错 (Issue #8793)
您好，没有复现这个问题 ，您jira的复选框是什么样的，方便截图看一下吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zyyfit** [comment]
这个问题是缺陷类型填错了，要填Bug，不是填缺陷，已经在你们的环境里改了
