### ISSUE TITLE
[QUESTION]如何根据测试报告id在测试报告列表中查看指定的测试报告？

### ISSUE THREAD

**Issue by hangxunZ** [metersphere/metersphere#8803]
**请描述您的问题.**
我使用的1.15.3版本时发现了如下问题。
我使用jenkins构建触发执行Metersphere中的测试计划，构建完成后在jenkins中会生成测试报告id，并提供了测试报告列表的链接，点击链接进入测试报告列表后我无法根据测试报告id来查找对应的测试报告。metersphere发送的测试报告邮件中有报告的链接，但是我发现链接中的测试报告id和jenkins中的并不一致。

请问在大量测试之后如何根据测试报告id查看对应的测试报告？

**Comment by wangzhen-fit2cloud** [comment]
你好，我们在 1.16.1 版本对 jenkins 生成的报告链接进行了优化，可以升级到该版本看能否满足需求。

**Comment by hangxunZ** [comment]
你好，1.16.1 版本依然无法满足要求。无法通过生成测试报告的id来访问测试报告。建议将测试报告id添加到测试报告界面的url中。我已经在微信群里和贵公司的员工沟通交流过，确实存在这个问题，他也建议我提个issue，后续版本进行优化处理。我已经提了issue：#8852。还望及时处理，在后续版本中进行修复优化。谢谢！
