### ISSUE TITLE
[BUG] msctl脚本提示语法错误

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#8804]
**MeterSphere 版本**

v1.16.0

**Bug 描述**

安装脚本提示语法错误：
请通过以下方式访问:
 URL: http://$LOCAL_IP:8081
 用户名: admin
 初始密码: metersphere
您可以使用命令 'msctl status' 检查服务运行情况.

**/usr/local/bin/msctl: line 258: syntax error near unexpected token `;;'
/usr/local/bin/msctl: line 258: ` ;;'**

![image](https://user-images.githubusercontent.com/24548477/147271724-b3cfb288-aebe-46f0-8084-238d35443480.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，在我们环境中没有复现这个问题，如果方便的话请在我们的微信交流群里联系下同事远程看一下。
![image](https://user-images.githubusercontent.com/27671436/147427732-548d58ec-2269-4119-ab3f-5a173aee0d31.png)
