### ISSUE TITLE
[BUG]使用jira模版选择数据异常

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#8805]
**MeterSphere 版本**

1.16.0

**Bug 描述**

1、获取到的人员名单不全，只有部分数据，100多人只查出了人
2、获取到的名字只有名字信息，应该名字下面是还有工号作为唯一匹配的，应该是没获取到对应关系，提交的时候应该是需要用工号提交的名字只是展示
3、选择任意数据，都会自动填充为列表最后一个数据

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
能够获取全部数据，选择的数据就是最后需要的数据

**截图**
![image](https://user-images.githubusercontent.com/40912823/147310572-580dbd47-e447-4fac-8446-d2b5d9fe498b.png)
平台中获取到的信息![image](https://user-images.githubusercontent.com/40912823/147311542-717a6656-d3c3-4fea-8b08-77c8ca1182d3.png)
jira中获取到的数据
![image](https://user-images.githubusercontent.com/40912823/147311781-9965bc34-9f8e-4848-b6f0-7bc2dab8ba76.png)

**Comment by locust-zhang** [comment]
同样的问题，而且点击保存后，提示“报告人不能为空”
![image](https://user-images.githubusercontent.com/84962582/147340976-4cc071ee-98be-4b85-8b35-5326288d8b5f.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复

**Comment by wszbc** [comment]
> v1.16.4版本已修复

1.16.5都还有这些问题，并未被修复
