### ISSUE TITLE
[BUG]JSON-schema中使用number超出限制导致报错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8806]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
请求体，JSON-SCHEMA格式当日期是毫秒时使用number会超过限制，导致实际发送的时候变成负数，建议换成long类型
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化
