### ISSUE TITLE
[FEATURE]测试跟踪->报告->查看测试报告，分享的链接能不能自定义有效期，默认24小时有点短了

### ISSUE THREAD

**Issue by fanyulei1223** [metersphere/metersphere#8812]
**请描述您的需求或者改进建议.**

**测试跟踪->报告->查看测试报告，分享的链接能不能自定义有效期，默认24小时有点短了**

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
可以自定义，预计1.19版本
