### ISSUE TITLE
[BUG]插件加载websocket插件之后创建的场景jmx与jmeter的生成的参数一样，但是没法在MS上单独运行而且运行一直处于测试中，只能整体调试

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#8813]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.0

**Bug 描述**
插件加载websocket插件之后创建的场景jmx与jmeter的生成的参数一样，但是没法在MS上单独运行而且运行一直处于测试中，只能整体调试，而且不能正确返回结果

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/32027713/147320945-138fcf02-6cf5-4a86-86ec-985bd8abb141.png)

![image](https://user-images.githubusercontent.com/32027713/147320819-702e3520-34e6-4e08-9325-ab79c5d44563.png)
![image](https://user-images.githubusercontent.com/32027713/147320834-44f13136-2082-4fc4-93ea-1ab58f92fa1f.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下。

**Comment by youliyuan-fit2cloud** [comment]
v1.16.3版本已修复
