### ISSUE TITLE
[BUG]复制可重复用例的测试计划，带copy名称的测试计划的可重复按钮是关闭的

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8814]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/147332782-6982bf7a-9cda-47ca-a97f-afa7f35ed7ca.png)

是指这里吗？原测试计划开启 “允许关联重复用例” ？然后复制的测试计划这里没开启？

**Comment by happyend1709** [comment]
> ![image](https://user-images.githubusercontent.com/54612864/147332782-6982bf7a-9cda-47ca-a97f-afa7f35ed7ca.png)
> 
> 是指这里吗？原测试计划开启 “允许关联重复用例” ？然后复制的测试计划这里没开启？

是

**Comment by youliyuan-fit2cloud** [comment]
没有复现这个问题~，再试试吧，或者详细描述下步骤？
