### ISSUE TITLE
[BUG]如果接口步骤的参数很多，在接口场景中来回切换步骤时，浏览器占用内存增长过快而导致崩溃

### ISSUE THREAD

**Issue by songbing0312** [metersphere/metersphere#8815]
**MeterSphere 版本**
v1.15.4

您所使用的 MeterSphere 版本是？
v1.15.4

**Bug 描述**
接口场景中单个接口接口步骤的请求参数很多，当点击其中某个接口步骤查看详细信息时，浏览器内存增长过快
来回切换不同的接口步骤，经过几个来回后，浏览器会直接崩溃

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
截图1: 点击第一个接口步骤，浏览器内存暂时只有300M多一点
<img width="1156" alt="1" src="https://user-images.githubusercontent.com/18387151/147325505-df6e5af4-2b05-4559-8bae-cd00800c046b.png">

截图2: 当在第一个接口步骤和第二个接口步骤来回切换两三次后，浏览器内存会很快涨到900M多
<img width="1116" alt="2" src="https://user-images.githubusercontent.com/18387151/147325557-5a84a731-023f-4152-8f47-5981bd64fda7.png">

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本有优化接口自动化，升级到1.16版本试试吧
