### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by shiyong1989** [metersphere/metersphere#8816]
**请描述您的问题.**
Warning  ProvisioningFailed  2m43s (x79351 over 13d)  persistentvolume-controller  storageclass.storage.k8s.io "vsan" not found

PV storage class 的类型可以改成别的吗

**Comment by wangzhen-fit2cloud** [comment]
你好，可以通过修改 values 文件中 `common.storageClass` 的值来指定。
