### ISSUE TITLE
[BUG]引用的场景，响应内容无显示，实际上执行了

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8821]
**MeterSphere 版本**

1.16.0

**Bug 描述**

场景内引用场景，引用的场景下的请求没有响应内容，实际上执行了

**Bug 重现步骤**

<img width="705" alt="01" src="https://user-images.githubusercontent.com/88763608/147325941-2d5310dc-c6fb-4447-9a9c-5a9ea3cf3939.png">
<img width="530" alt="02" src="https://user-images.githubusercontent.com/88763608/147325948-ad734d94-32e4-4534-a643-31af368dd159.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，试了多次暂时没有复现，你这个是必现的吗？

**Comment by wszbc** [comment]
> 你好，试了多次暂时没有复现，你这个是必现的吗？

我也有这个问题，部分场景会这样以前都是好的从16的版本才这样的
![image](https://user-images.githubusercontent.com/40912823/147428789-7b432e63-3ad4-430c-9b67-af87a8e61193.png)
实际上接口被执行了
