### ISSUE TITLE
[BUG]测试跟踪-测试计划-报告统计导出的html报告无法打开

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#8822]
**MeterSphere 版本**
v.1.6.0 v.1.5.4都存在
您所使用的 MeterSphere 版本是？

**Bug 描述**
html报告正常下载，无法打开
简要描述您碰到的问题

**Bug 重现步骤**

1.  下载报告
2. 在本地打开查看
3. 
4. 

**期待的正确结果**
正常展示html报告内容
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/46660929/147326415-1fb82740-08fc-4aad-901d-9a15ed9430f6.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复~

**Comment by youliyuan-fit2cloud** [comment]
可以先换种方式查看，报告-选择“分享”链接可以打开，
