### ISSUE TITLE
[BUG] 测试报告界面中查看接口用例断言弹窗中无法完整显示断言代码

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#8828]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

# v1.16.0

**Bug 描述**

# 测试报告界面中查看接口用例断言弹窗中无法完整显示断言代码

**Bug 重现步骤**

接口用例中的断言脚本超过`200`行

(接口测试、测试计划)生成报告后在测试报告中查询接口断言

**期待的正确结果**

# 完整展示断言脚本代码

**截图**

![1735036885663910599b5c592d87cfc](https://user-images.githubusercontent.com/1278141/147332287-9c7cfbdb-b37e-4419-afd7-7e25bb8363c5.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化下~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复
