### ISSUE TITLE
[BUG]接口参数 JSON-SCHEMA 转换失败

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#8832]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口 json 参数，转换成 JSON-SCHEMA 后，表单里数据变为空
2. json 参数如下

**期待的正确结果**

正确情况下应该是什么样的？

**Comment by shenkaibo** [comment]
[test.txt](https://github.com/metersphere/metersphere/files/7773438/test.txt)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~
