### ISSUE TITLE
[FEATURE] 测试跟踪-测试计划 中添加的 关联接口用例 建议默认（串行）应该按照添加后的ID顺序执行且同一个测试计划（选了同1环境）环境变量应该公用互通

### ISSUE THREAD

**Issue by lgs3137** [metersphere/metersphere#8840]
**请描述您的需求或者改进建议.**

测试跟踪-测试计划 中添加的 关联接口用例 建议默认（串行）应该按照添加后的ID顺序执行且同一个测试计划（选了同1环境）环境变量应该公用互通

**请描述你建议的实现方案**

1、选择 串行 执行 测试计划时，按照 测试计划中关联的ID升序执行

2、当测试计划选中同一个测试环境时，测试计划中所有用例执行均公用一个环境变量（vars.get()、vars.put()互通）

**Comment by luty2018** [comment]
> **请描述您的需求或者改进建议.**
> 
> 测试跟踪-测试计划 中添加的 关联接口用例 建议默认（串行）应该按照添加后的ID顺序执行且同一个测试计划（选了同1环境）环境变量应该公用互通
> 
> **请描述你建议的实现方案**
> 
> 1、选择 串行 执行 测试计划时，按照 测试计划中关联的ID升序执行
目前就是这个顺序  你升级版本试试
> 2、当测试计划选中同一个测试环境时，测试计划中所有用例执行均公用一个环境变量（vars.get()、vars.put()互通）
这个没看太懂，你可以在微信群和我具体描述下哈
