### ISSUE TITLE
[BUG]场景内不执行所有步骤时，有时候后面的步骤会先执行

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8841]
**MeterSphere 版本**

1.16.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

<img width="678" alt="07" src="https://user-images.githubusercontent.com/88763608/147342348-f5ed4670-f155-4b26-96b9-1a3e7e83dee5.png">

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，方便把整个场景导出来，我们复现一下吗？
