### ISSUE TITLE
数据部分，为什么不在POST.data下，反而在URL里

### ISSUE THREAD

**Issue by wuxinping418** [metersphere/metersphere#885]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

V1.5.0

**Bug 描述**
简要描述您碰到的问题
数据部分，都在URL里，不在POST.data下

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
数据部分在POST.data下

**截图**
![图片](https://user-images.githubusercontent.com/74084897/101128899-8c50ad80-363b-11eb-9ed6-b2c30248cb4b.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请问请求内容是如何定义的
