### ISSUE TITLE
[FEATURE] 希望在执行测试计划的时候，给每条用例添加一个备注字段，可以把失败原因写上去，同时可以上传失败日志或者截图等文件

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8850]
**请描述您的需求或者改进建议.**
1、希望在执行测试计划的时候，给每条用例添加一个备注字段，可以把失败原因写上去，同时可以上传失败日志或者截图等文件
2、每条用例可以查看历史失败记录和原因

**请描述你建议的实现方案**
1、给每条用例添加一个备注字段，可以把失败原因写上去
2、每条用例可以查看历史失败记录和原因

**Comment by luty2018** [comment]
执行测试计划在右侧评论里面是支持发图片和文本的

**Comment by liuqiao1995** [comment]
> 执行测试计划在右侧评论里面是支持发图片和文本的

这个评论直接就修改到原始用例里面了，并不能和测试计划区分开来。
