### ISSUE TITLE
[BUG]jenkins插件触发测试计划执行后，无法通过生成的测试报告id访问测试报告

### ISSUE THREAD

**Issue by hangxunZ** [metersphere/metersphere#8852]
我使用的1.15.3版本时发现了如下问题。
我使用jenkins构建触发执行Metersphere中的测试计划，构建完成后在jenkins中会生成测试报告id，并提供了测试报告列表的链接，点击链接进入测试报告列表后我无法根据测试报告id来查找对应的测试报告。metersphere发送的测试报告邮件中有报告的链接，但是我发现链接中的测试报告id和jenkins中的并不一致。

**Comment by hangxunZ** [comment]
在1.16.1最新版本上依旧没有处理这个问题

**Comment by hangxunZ** [comment]
jenkins触发执行测试计划后，可配置发送邮件通知。

尊敬的用户：

               您好：
                 
                          Adminnistrator执行的Verify_test 测试计划与逆行成功
                          请点击下面链接进入测试报告页面
                           http://192.168.30.237:8081/sharePlanReport?shardID=333a2712-dsdf-dfhv-weer-dhjkweudxhj7

上述邮件通知中使用的是共享的id，和jenkins报告中的生成测试报告id不同。
批量测试后根本无法通过通过邮件来判断jenkins构建中的每个报告id和测试邮件的对应关系。

我理解应该可以通过类似下面的接口来访问测试报告：其中reportID就是生成的测试报告ID
http://192.168.30.237:8081/#/track/testPlan/reportList?reportID=asdjhsiadjek-sfhj-sdjj-sadf-sadfjhsuffds

谢谢！
期待贵公司的处理。

**Comment by zyyfit** [comment]
您好，我们在邮件里的报告是可以直接通过链接免登录查看报告的，所以ID和测试跟踪里的报告ID是不一样的，您可以通过测试计划名称和执行时间来判断报告的对应关系，如果您希望我们的分享ID和报告ID有一定的关联性的话，我们需要先进行一下需求调研，然后讨论一下处理方案

**Comment by hangxunZ** [comment]
邮件里分享的id有有效时间的，几天后无法再访问

**Comment by Hyyfit** [comment]
感谢反馈，1.18版本将上线 【自定义测试报告分析链接的有效时间】
