### ISSUE TITLE
[BUG] 普通用户无法创建缺陷

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8853]
**MeterSphere 版本**

1.16.0

**Bug 描述**

普通用户无法创建缺陷

**Bug 重现步骤**

1.  测试跟踪
2. 缺陷管理
3. 创建缺陷，保存
4. 显示配置为空

**期待的正确结果**

应该可以创建缺陷

**截图**
![飞书20211225-180932](https://user-images.githubusercontent.com/22763910/147382906-c8b3c799-7414-4cfd-8591-aa66c3fa98ff.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题
.请检查下系统设置-工作空间-项目管理-项目-编辑-集成第三方平台是什么，以及缺陷模板是否能正常查看，如果使用第三方平台是JIRA或者禅道等，请检查下是否添加了 第三方项目的ID ？

**Comment by liuqiao1995** [comment]
不好意思，没有设置模板
