### ISSUE TITLE
[BUG] 测试跟踪首页的“遗留缺陷”统计与测试计划统计的缺陷数量不一致

### ISSUE THREAD

**Issue by xyziven** [metersphere/metersphere#8854]
**MeterSphere 版本**

v1.16.1

**Bug 描述**

测试计划1关联功能用例1，并且在下面关联了2个缺陷。
新创建测试计划2再关联测试用例1，在测试计划2的列表中显示当前计划没有缺陷；
但在首页的“遗留缺陷”统计里会显示测试计划1和2都有2个缺陷

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
首页的统计信息显示，plan002有2个遗留缺陷
![image](https://user-images.githubusercontent.com/24548477/147415566-7fd3f8d3-1b4d-45ab-bcc6-12aa253f8102.png)

但plan002的测试报告显示无缺陷
![image](https://user-images.githubusercontent.com/24548477/147415573-81c2f900-7ef3-4eab-b5d6-75fcf51307d7.png)

**Comment by youliyuan-fit2cloud** [comment]
下个版本会增加的版本管理功能，能解决这个问题
和#7341相同
