### ISSUE TITLE
[BUG]使用MQTT插件做性能测试，测试结束后，jmeter容器未释放

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8855]
**MeterSphere 版本**

1.15.4
jmeter版本：目前jmeter5.4.1  5.4.2版本镜像都存在该问题

**Bug 描述**
<img width="929" alt="报告时间" src="https://user-images.githubusercontent.com/88763608/147426925-abb47a72-099b-40ef-bcc7-9a0502d09620.png">
<img width="658" alt="容器释放" src="https://user-images.githubusercontent.com/88763608/147426931-397a05a9-c6a0-47d7-821e-1e7a8599f647.png">

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们研究一下后续版本优化下这里

**Comment by zyyfit** [comment]
相关问题 https://github.com/metersphere/metersphere/issues/8517
