### ISSUE TITLE
[BUG]报告分享页面缺陷描述预览不生效

### ISSUE THREAD

**Issue by liudezhi2098** [metersphere/metersphere#8856]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是v1.16.1 

**Bug 描述**
sharePlanReport分享后【功能用例统计分析】->【缺陷列表】-> 【缺陷描述】->【预览】不生效。

![image](https://user-images.githubusercontent.com/33149602/147426842-79154e1e-dd84-4663-88b6-57d212a4daa2.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.0版本已修复
