### ISSUE TITLE
[BUG]接口测试响应体中的“<”">"被转译成UNICODE字符

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8857]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.5
**Bug 描述**

简要描述您碰到的问题
接口测试响应体中的“<”">"被转译成UNICODE字符
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![WechatIMG96](https://user-images.githubusercontent.com/36387811/147427027-78d32deb-72d4-42e8-82a4-00cb0bb4fd4f.png)
![WechatIMG27](https://user-images.githubusercontent.com/36387811/147427030-e4bbfd1b-d871-4bda-aa8f-64824b1aea6b.jpeg)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，这场景里面没有单独设置转义吧？比如后置脚本中设置了默认编码 ？或者方便把这个场景导出来我们试试啊
