### ISSUE TITLE
[BUG]Swagger导入的接口请求头被自动加上Content-type

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8858]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.5

**Bug 描述**

简要描述您碰到的问题
Swagger导入的接口请求头被自动加上Content-type application/json
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![WechatIMG114](https://user-images.githubusercontent.com/36387811/147427122-dde86742-279c-4b4c-9703-29ce4b1db4ed.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，1.14版本没有复现这个问题，把swagger文件发一下，我们试试？
