### ISSUE TITLE
[FEATURE]能不能提供一个接口汇总的地方可以自由组合场景

### ISSUE THREAD

**Issue by lingrance** [metersphere/metersphere#886]
**请描述您的需求或者改进建议.**
每次接口测试遇到一个很繁琐的操作就是需要将已经存在的接口在N个场景中使用则需要填写N次
接口A在场景B、C、D、E中都使用到那就要重新填写4次，类推工作量极大
建议类似post 可以针对模块内的接口组合

**请描述你建议的实现方案**
1、能将已有接口测试的接口按照模块汇总在接口列表中
2、能够按照已有的接口来组建场景

![image](https://user-images.githubusercontent.com/44960709/101128925-9b376000-363b-11eb-832b-69bfbd7596cf.png)

**Comment by lingrance** [comment]
![image](https://user-images.githubusercontent.com/44960709/101128967-af7b5d00-363b-11eb-9163-978e1680d635.png)

**Comment by lcwus2** [comment]
在同一个测试里，接口请求貌似是可以复制和移动的
我觉得不光是场景内的一些接口组合，最好是能把所有接口都列出来，创建一个测试之后可以自由组合所需要的接口
