### ISSUE TITLE
[BUG]当请求返回数据过大，构建触发后获取的报告地址无法正常打开

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8861]
**MeterSphere 版本**

1.10.8-lts

**Bug 描述**

当请求返回数据过大，构建触发后获取的报告地址无法正常打开

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好， 是通过jenkins构建的测试报告链接无法打开？
