### ISSUE TITLE
[BUG]对接jira填完了但是报“报告人不能为空”

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#8862]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.1

**Bug 描述**
ms对接了jira之后，用例关联需求可以关联到jira中的项目，关联缺陷的时候信息都填全了，但是还是报“报告人不能为空”

**Bug 重现步骤**

1.  工作空间、项目、个人信息都绑定了jira（不支持中文，必须要英文，比如故障-Bug，故事Story），jira版本7.8.1

**期待的正确结果**

正确情况下应该是什么样的？

![image](https://user-images.githubusercontent.com/66759501/147428214-a67b62b5-980f-45b7-85bf-2202fa7cf481.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本jira会继续优化一下~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
