### ISSUE TITLE
[BUG]监控node-exporter节点，提示no route to host / connection refused

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8863]
**MeterSphere 版本**

1.15.4

**Bug 描述**
![连接](https://user-images.githubusercontent.com/88763608/147428607-928c4210-4e82-434b-83f8-a9b9ba2f08ae.jpg)

**Bug 重现步骤**

1.  node-exporter状态正常
2. 防火墙已关闭
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，建议检查下MS系统和这个node节点网络是否是通的
