### ISSUE TITLE
[BUG]性能测试报告显示事务名称乱码

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8866]
**MeterSphere 版本**

1.15.4

**Bug 描述**

![JMX](https://user-images.githubusercontent.com/88763608/147429219-04791bb8-12af-4092-9b57-469f99471db6.jpg)
![事务明](https://user-images.githubusercontent.com/88763608/147429227-cec3e537-e180-45da-b427-d90c0647a6fb.jpg)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，v1.16.1版本没有这个问题，建议升级下

**Comment by youliyuan-fit2cloud** [comment]
v1.17.0版本已修复
