### ISSUE TITLE
[BUG] V1.16.1版本，匹配多条方式提取的参数，无法在脚本中被直接引用

### ISSUE THREAD

**Issue by gongbaojid** [metersphere/metersphere#8871]
**MeterSphere 版本**

版本:   v1.16.1-1d2ed0d0

**Bug 描述**

V1.16.1版本，匹配多条方式提取的参数，无法在脚本中被直接引用

**Bug 重现步骤**

1.  升级metersphere到版本:   v1.16.1-1d2ed0d0
2. 使用jsonpath提取的参数（勾选匹配多条）
3. 直接在脚本中用var.get()获取上面提取到的变量的值
4. 获取变量失败，脚本报错“TypeError: cannot concatenate 'str' and 'NoneType' objects in <script> at line number”

**期待的正确结果**

可直接引用提取的匹配的多条结果

**截图**
![图片](https://user-images.githubusercontent.com/8509250/147430553-742581d4-fa7b-40a2-9b7b-23ed4e0aad2e.png)
![图片](https://user-images.githubusercontent.com/8509250/147430576-f13b8a82-c25f-475e-98ad-a40b1b5b7bee.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，匹配多条是数组了，提取的时候加上索引就可以了，例如 ${app_name_1}

**Comment by gongbaojid** [comment]
> 

我想匹配所有数据，而不是任意一条数据，之前是可以的，现在为什么要去掉呢？

**Comment by gongbaojid** [comment]
> 你好，匹配多条是数组了，提取的时候加上索引就可以了，例如 ${app_name_1}

因为如果不取整个数组，用户可能连索引选择多少都不知道的
