### ISSUE TITLE
[BUG]测试跟踪，测试计划，执行功能测试用例，无法上传附件，+号这个图标被disable了。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#8872]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
最新版本1.16.1
**Bug 描述**

简要描述您碰到的问题
试跟踪，测试计划，执行功能测试用例，无法上传附件，+号这个图标被disable了。
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，测试计划里面是这样限制的，不能直接修改用例，可以在评论里面上传图片等信息
