### ISSUE TITLE
[BUG] 新建场景，导入接口用例时，全选将回收站的用例也导入进来 

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#8886]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是  v1.16.0-b4ed25de

**Bug 描述**

新建场景，导入接口用例时，全选将回收站的接口用例也导入进来 [](url)

**Bug 重现步骤**

1.  接口测试-接口定义模块， 保证回收站里面有一个接口用例（case）, “未规划接口” 有多个接口用例（case）
2.  接口自动化， 新建场景，选择 接口列表导入
3.  选择CASE， 在“未规划接口”下， 全选右侧的列表， 点击“选择所有数据“ ，见图1
<img width="854" alt="图1" src="https://user-images.githubusercontent.com/30264974/147446563-edb2c0af-c858-40ab-9504-6ce403a4b47d.png">
4. 点击“复制”， 可以看到把回收站的用例也导入进来，见图2
<img width="636" alt="图2" src="https://user-images.githubusercontent.com/30264974/147446599-4f98e975-60f0-4484-922e-6403e4873d31.png">

**期待的正确结果**

正确情况下应该是什么样的？
不应该导入回收站下的接口用例

**截图**

如果有截图，请附上截图.

**Comment by fitcloud-zaopengguo** [comment]
需要重现，联系内部 灶鹏

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题~
