### ISSUE TITLE
测试计划包含接口测试时，执行测试计划会出现接口执行一直是运行中状态，而且执行方式也有问题[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#8888]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.6.1
**Bug 描述**

简要描述您碰到的问题
1、创建测试计划，打开自动更新状态
2、添加功能用例，功能用例包含接口及接口场景用例
3、手动执行测试计划，任务中心查看执行状态，发现有些接口执行状态一直是运行中
4、发现每次执行的时候执行方式会有变化，有时候是手动、有时候是定时、有时候是批量执行，其实都是手动执行的，而且如果显示执行方式是手动执行和定时执行可以正常执行通过，如果是批量执行就会有问题，如下图

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35896106/147451352-587f31e4-2292-4e19-9973-c4a93cccbefd.png)

![image](https://user-images.githubusercontent.com/35896106/147451181-c0f3f5de-c364-4271-bea8-c49948e7cd88.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复~
