### ISSUE TITLE
[QUESTION]Helm安装metersphere，出现couldn't find key kafka.bootstrap-servers in ConfigMap default/metersphere-config问题

### ISSUE THREAD

**Issue by shiyong1989** [metersphere/metersphere#8889]
第一个问题： helm 中新加的env log4j2的漏洞 true应该加上双引号。在线安装会报错。
第二个问题：pv需要自己创建。所以直接执行在线安装的命令会报错。
第三个问题：
NAME                                                                            READY       STATUS                                                   RESTARTS    AGE
metersphere-data-streaming-6996859d4d-bbstf              0/1               Init:1/2                                                      0                107s
metersphere-helm-chart-master-585b8dcdc6-hmmcj      1/1               Running                                                    0                107s
metersphere-node-controller-d855d88df-mm9ws            0/1               Init:0/1                                                       0                107s
metersphere-server-dfc5f75df-crtv8                                 0/1              Init:CreateContainerConfigError                0                107s
mysql-0                                                                            1/1               Running                                                     0                107s

安装后是这个状态
describe po  metersphere-server-dfc5f75df-crtv8 后的错误是
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m34s                   default-scheduler  Successfully assigned default/metersphere-server-dfc5f75df-crtv8 to uat-node02
  Normal   Pulled     9m33s                   kubelet            Container image "busybox:latest" already present on machine
  Normal   Created    9m33s                   kubelet            Created container wait-mysql
  Normal   Started    9m33s                   kubelet            Started container wait-mysql
  Warning  Failed     4m44s (x11 over 6m57s)  kubelet            Error: couldn't find key kafka.bootstrap-servers in ConfigMap default/metersphere-config
  Normal   Pulled     4m32s (x12 over 6m57s)  kubelet            Container image "busybox:latest" already present on machine

kafka实例并没有启动是为什么？

**Comment by wangzhen-fit2cloud** [comment]
你好，helm chart 已更新 1.0.9 版本。
针对提到的几个问题：
1. 在新版本中已进行处理
2. 默认通过 pvc 来自动创建 pv，pvc 使用的 storageclass 为 vsan，如果没有修改这个参数的话，可能导致 pvc 处于 pending 状态而没有创建出 pv，可以通过 get pvc 来确认具体原因。在新的 chart 版本中将 `common.storageClass` 的默认值修改成了 `default`
3. 在新版本中已进行处理
