### ISSUE TITLE
v1.17.0 版本规划和发布时间 

### ISSUE THREAD

**Issue by Hyyfit** [metersphere/metersphere#8890]
请描述您的问题.
v1.17.0 版本规划和发布时间

**Comment by Hyyfit** [comment]
v1.17.0 计划于 2022 年 1 月 27 日发布，该版本的计划内容有：

新增：

1. 定时清理系统报告&日志功能

2. 版本管理&版本比对功能(X-Pack)

> - 版本管理(X-Pack)测试跟踪、接口测试、性能测试及测试计划支持新增版本和关联版本的操作
> - 版本比对(X-Pack)测试跟踪，接口测试，性能测试支持不同版本的内容比对
> - 功能用例公共用例库(X-Pack)关联版本


优化：

1. 内置函数构造器优化

2. LDAP用户登录优化

3. 场景变量优先级优化

**Comment by congim** [comment]
场景变量优先级优化 这条是上层变量优先级最高吗，因为场景包含场景，只有上层优先级最高（外层覆盖底层）才能做到方便调试

**Comment by maninhill** [comment]
https://github.com/metersphere/metersphere/releases/tag/v1.17.0

已经发布。
