### ISSUE TITLE
[FEATURE] 前置或者后置脚本中导入api定义时自动生成的代码中建议直接使用host变量而不是每次都需要自己选环境

### ISSUE THREAD

**Issue by dronl** [metersphere/metersphere#8898]
**请描述您的需求或者改进建议.**

目前在脚本中选择导入API定义时，需要选择api的环境，这样非常不方便，而且自动生成的代码hardcode了host，切换到其他环境时还要改

**请描述你建议的实现方案**
在选择API定义的时候不需要勾选环境，在自动生成的代码中直接用host变量(比如python脚本的话，即为host=vars.get("host"))，这样脚本也可以支持在各个环境中运行

**Comment by luty2018** [comment]
谢谢反馈，待排期处理
