### ISSUE TITLE
[BUG]接口自动化测试报告数据统计错误

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8899]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.0
**Bug 描述**

简要描述您碰到的问题
场景中添加其他场景，其他场景中也引用别的场景，测试报告中存在场景数统计错误，失败数统计错误
**Bug 重现步骤**

1.  新建一个场景
2. 在场景里引用4个场景， 在四个场景中存在引用其他场景
3.执行场景

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![WechatIMG452](https://user-images.githubusercontent.com/36387811/147458715-8b27b7b5-23dc-4fb4-836c-88112c4937d3.png)
![1640598535618](https://user-images.githubusercontent.com/36387811/147461377-6b2f6334-cd79-4ba1-b763-2c6d99b04e38.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，已知问题，后续小版本修复

**Comment by zyyfit** [comment]
1.16.5已修复
