### ISSUE TITLE
[BUG]接口自动化中部分引用场景会存在执行后无执行记录

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#8902]
**MeterSphere 版本**
1.16.1

**Bug 描述**

用例中含有引用的部分用例执行后没有响应数据，实际上是执行成功了，若将所有用例展开，执行后响应数据会正常出现，升级1.16后就开始有这个问题了

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正常显示执行记录

**截图**
![image](https://user-images.githubusercontent.com/40912823/147520346-6d33891f-d871-4a93-9ebf-540cd1d49ea1.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.16.2中已解决

**Comment by wszbc** [comment]
> v1.16.2中已解决

更新后仍然有此问题

**Comment by youliyuan-fit2cloud** [comment]
啊，能提供下详细的描述吗，比如这个引用里面的请求是不是禁用的，log有没有 错误日志啥的？

**Comment by wszbc** [comment]
> 啊，能提供下详细的描述吗，比如这个引用里面的请求是不是禁用的，log有没有 错误日志啥的？

我总结了下看有帮助不，不是所有的都会有，包含引用的就很容易出现这个问题，全部收起的情况下去执行，用例通过，然后你展开一些数据，你会发现如下图
![image](https://user-images.githubusercontent.com/40912823/147732626-bccfea26-4570-47a0-a1ac-0349857127e8.png)
有的接口就像没执行，什么数据都没有，没有禁用，但是实际是执行过了，我的用例都是一步步的很多都有关联前面不跑后面肯定过不了。我看了下报告模式也是一样会有一些接口没有数据，不知道是不是嵌套引用层数过多，看起来都是2层以上都有这个问题 例如a引用b，b引用c，我执行的a，场景不展开。
如果执行前全部展开再去执行就会所有数据都显示了，再收起后执行也是有数据的，重新保存退出，再打开执行就又跟开始一样不出现的接口还是不出现，但实际是可以执行成功

**Comment by youliyuan-fit2cloud** [comment]
非常感谢，我们再优化一下这里

**Comment by youliyuan-fit2cloud** [comment]
v1.17.0版本没有复现了，升级下？
