### ISSUE TITLE
[BUG]对接jira模板后，提单时候选择人员不论怎么选择都会变成最后当前下拉框的最后一个人，其它字段正常

### ISSUE THREAD

**Issue by break002** [metersphere/metersphere#8905]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？版本:   v1.16.1-b81189dd

**Bug 描述**

对接jira后提单，所有涉及到人员的，不管如何选择，最后都会变成最后一个人
![image](https://user-images.githubusercontent.com/47669234/147524443-348dc094-54dd-4eab-9d90-94f44e223b70.png)

**Bug 重现步骤**

1.  对接jira平台
2. 使用jira模板
3. 创建问题
4. 选择报告人，归属人等字段

**期待的正确结果**

正确选择人员

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
和#8805 相同
