### ISSUE TITLE
[BUG] V1.16.1版本，导入接口接口定义，关联的CASE导入后无法显示出来，新增相同名的CASE报错用例名称已存在

### ISSUE THREAD

**Issue by gongbaojid** [metersphere/metersphere#8906]
**MeterSphere 版本**

V1.16.1

**Bug 描述**

导入API接口定义，关联的CASE导入后无法显示出来，新增相同名的CASE报错用例名称已存在

**Bug 重现步骤**

1.  从系统导出一个接口定义
2.  将接口定义导入到另外一个项目
3.  查看导入的结果

**期待的正确结果**

可正常导入接口关联的case；
实际情况是关联case不显示，新建相同名称的case接口报错

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，
1.导出的是MeterSphere格式 ？
2.这些接口和导入的项目中接口有一样的吗？如果有一样的接口，导入时选择“导入模式”不覆盖，接口用例不会导入

**Comment by gongbaojid** [comment]
> 你好，没有复现这个问题， 1.导出的是MeterSphere格式 ？ 2.这些接口和导入的项目中接口有一样的吗？如果有一样的接口，导入时选择“导入模式”不覆盖，接口用例不会导入

是的，导入的metersphere格式的，不同项目之间的导出、导入，那我再复现看看
