### ISSUE TITLE
[BUG]接口测试环境配置默认带出的项不起作用，需要重新通过下来框选择环境后才能正常执行

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#8911]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16
**Bug 描述**
接口测试环境配置默认带出的项不起作用，需要重新通过下来框选择环境后才能正常执行
简要描述您碰到的问题

**Bug 重现步骤**

1.  进入接口测试test，环境配置自动默认带出
2. 执行接口测试失败
3. 重新选择环境列表，还选默认带出的那个配置
4. 再次执行接口，执行成功

**期待的正确结果**

正确情况下应该是什么样的？
默认带出的环境即可执行成功
**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本解决
