### ISSUE TITLE
[BUG]通过定时任务执行接口自动化场景，同一个接口执行时偶尔正常，偶尔失败

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#8912]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16
**Bug 描述**
[BUG]通过定时任务执行接口自动化场景，同一个接口执行时偶尔正常，偶尔失败
简要描述您碰到的问题

**Bug 重现步骤**

1.  通过定时任务执行接口自动化场景
2. 同一个接口执行时偶尔正常，偶尔失败
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
应该每次定时任务执行都正常
**截图**

如果有截图，请附上截图.
<img width="624" alt="1" src="https://user-images.githubusercontent.com/83771182/147532123-79e71f2b-9c18-4b28-9389-fc342cfa0a32.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现，建议排查一下网络问题
