### ISSUE TITLE
[BUG] helm部署metersphere(helm 1.6.0+)报错

### ISSUE THREAD

**Issue by xmacr** [metersphere/metersphere#8918]
**MeterSphere 版本**

**您所使用的 MeterSphere 版本是？**
helm 1.6.0+

**Bug 描述**
helm执行报错

**报错信息：**
[root@k8s-master01 data]# helm install metersphere metersphere
W1228 13:57:17.881078   99939 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
**Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS","value":true}],"image":"registry.cn-qingdao.aliyuncs.com/me|...**

```
修改以下文件的env值添加双引号：
templates/03-modules/metersphere-data-streaming.yaml:            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
templates/03-modules/metersphere-node-controller.yaml:            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
templates/03-modules/metersphere-server.yaml:            - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
values.yaml:    - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS

修改前：
  extraEnvVars:
    - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
      value: true
修改后：
  extraEnvVars:
    - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
      value: "true"
```

**截图**
修改后似乎就可以正常执行
![image](https://user-images.githubusercontent.com/96763904/147535439-27eacd68-edde-46a6-b5bf-22c254ca514e.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，chart 已更新 1.0.9 版本解决了该问题。
