### ISSUE TITLE
[BUG]脑图用例里模块点了上移把某个模块移到顶端之后保存，重新打开怎么排序还是以前的样子没有更新

### ISSUE THREAD

**Issue by diaohanji** [metersphere/metersphere#8920]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.4-a1b8953b

**Bug 描述**

脑图用例里模块点了上移把某个模块移到顶端之后保存，重新打开怎么排序还是以前的样子没有更新

**Bug 重现步骤**

1.  打开脑图用例
2. 修改模块顺序
3. 点击保存
4. 重新打开脑图用例

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![d347726fb1b5413a488ebfe582692ed](https://user-images.githubusercontent.com/43695413/147536675-f87ad0b9-0d5b-4f73-982d-e3f6e2c75dec.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，目前还不支持￣□￣｜｜

**Comment by diaohanji** [comment]
有后续的计划 ？

**Comment by youliyuan-fit2cloud** [comment]
> 有后续的计划 ？

后续有计划支持
