### ISSUE TITLE
[FEATURE]邮箱编辑只能到用户页面才能够正常编辑，个人信息页不能编辑邮箱

### ISSUE THREAD

**Issue by yundafu** [metersphere/metersphere#8921]
**MeterSphere 版本**

metersphere-offline-installer-v1.16.1

**Bug 描述**

邮箱编辑只能到用户页面才能够正常编辑；

**Bug 重现步骤**

1.  登录后点击个人信息
2. 点击编辑邮箱信息

**期待的正确结果**

任何可以编辑邮箱的地方应当都能够修改；

![image](https://user-images.githubusercontent.com/85158686/147536841-3de433f0-de0c-4627-b49c-4f0af3bc7dd8.png)

**Comment by luty2018** [comment]
已排期
