### ISSUE TITLE
[BUG] 主分支前端工程下，xpack依赖仍然会导致打包失败

### ISSUE THREAD

**Issue by Siiyoung** [metersphere/metersphere#8928]
**截图**
![image](https://user-images.githubusercontent.com/14232955/147546908-81320a7e-c498-44fb-be13-65c5c2ed9410.png)

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，master 分支的代码已经更新了，请更新下再构建看下吧
