### ISSUE TITLE
[BUG]接口文件上传，没有自动把文件同步到节点机

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#8931]
**MeterSphere 版本**

1.10.8-lts

**Bug 描述**
![上传](https://user-images.githubusercontent.com/88763608/147555790-93f71c5a-8d38-407a-9eae-4d7500059266.png)
![报错](https://user-images.githubusercontent.com/88763608/147555801-af0fd113-47f4-48b7-9cc6-b5e3122aa04d.png)

**Bug 重现步骤**

1.  使用本地local执行文件上传的接口自动化场景，执行成功
2. 选择其他资源池节点执行接口自动化场景，执行失败
3. 报错找不到文件
4. 上传的文件没有自动同步到节点机

**期待的正确结果**

自动同步到资源池节点

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复该问题

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复
