### ISSUE TITLE
[BUG]性能测试启动后，前端无法停止

### ISSUE THREAD

**Issue by rzsp8552** [metersphere/metersphere#894]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.0

**Bug 描述**
简要描述您碰到的问题
性能测试，启动后，无法点击立即停止， 似乎状态反了。
![image](https://user-images.githubusercontent.com/20183045/101235417-6f7fad00-3703-11eb-8c36-a343e323edd8.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，显示这个按钮是测试已经结束了，是页面上没有数据吗？
