### ISSUE TITLE
[BUG][企业用户-大通和亿]接口测试运行环境包含有多个模块启用条件和启用条件为无的情况下，在测试计划中执行接口用例时，部分应执行启用条件为模块的接口请求指向至启用条件为无的请求中，指向有误，需定位并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#8942]
**MeterSphere 版本**

v1.16.1-b81189dd

**Bug 描述**

接口测试运行环境包含有多个模块启用条件和启用条件为无的情况下，在测试计划中执行接口用例时，部分应执行启用条件为模块的接口请求指向至启用条件为无的请求中，指向有误，需定位并修改

备注：概率性问题，个人环境未复现，用户环境当前为必现

**截图**
![image](https://user-images.githubusercontent.com/92150453/147638054-6c88d267-8bd4-4864-91ff-2fb9712141fc.png)
<img width="960" alt="00efee6b38233a409b4d68c4348e8c6" src="https://user-images.githubusercontent.com/92150453/147639970-ea797480-6cb2-4e7b-baeb-b150c579826e.png">
<img width="960" alt="4e6f4f6d2aa00060c50e2d00aba7b5d" src="https://user-images.githubusercontent.com/92150453/147639987-1492c12f-b564-4cef-8171-ff8cf2033150.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，我这边也没复现，后续会继续尝试复现~

**Comment by sageonedream** [comment]
这个当前在用户环境是必现的，方便远程定位下吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG][企业用户-大通和亿]接口测试运行环境包含有多个模块启用条件和启用条件为无的情况下，在测试计划中执行接口用例时，部分应执行启用条件为模块的接口请求指向至启用条件为无的请求中，指向有误，需定位并修改 (Issue #8942)





 
你好，我这边也没复现，后续会继续尝试复现~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youliyuan-fit2cloud** [comment]
最新版本已修复！请升级下吧
