### ISSUE TITLE
[FEATURE]接口自动化CSV Data Set Config组件

### ISSUE THREAD

**Issue by wuyue1989** [metersphere/metersphere#8945]
**请描述您的需求或者改进建议.**
自动化和压测过程中使用CSV Data Set Config的场景会很多，没有使用上不太方便

**请描述你建议的实现方案**
按照jmeter实现即可，但建议只支持固定格式文件上传，前端可配置 变量名、上传文件等关键信息即可。

**Comment by luty2018** [comment]
已采纳待排期
