### ISSUE TITLE
[FEATURE]性能测试加载文件建议丰富一下支持的格式

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#8946]
**请描述您的需求或者改进建议.**

业务需要，在性能压测的时候需要调用zip格式的文件，但是ms目前上传的文件从日志看都压缩成了zip（或许这是不支持zip格式的原因之一？），所以希望再丰富一下支持上传的文件格式，比如说zip。通过dockerfile下载jmeter镜像太麻烦了，用jmeter就很方便，直接调用本地的文件了

**请描述你建议的实现方案**

**Comment by liuruibin** [comment]
多谢提示，我们会开放更多格式出来
