### ISSUE TITLE
[BUG]在Metersphere添加缺陷上传图片到缺陷，Metersphere上的图片可以显示，同步缺陷在tapd无法显示缺陷的图片

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8947]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.1
**Bug 描述**

简要描述您碰到的问题
在Metersphere添加缺陷上传图片到缺陷，Metersphere上的图片可以显示，同步缺陷在tapd无法显示缺陷的图片
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![1640745254719](https://user-images.githubusercontent.com/36387811/147623140-1a3279d6-5ddc-4402-9072-b6b4e83386c5.jpg)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
tapd 要求当前站点必须是 https 的地址才能访问到，所以MS系统设置中请将当前站点URL设置为HTTPS的地址
