### ISSUE TITLE
[BUG]客户那边 从yapi导出一个 swagger 2.0规范的文档，导入MS提示解析错误，postman导入是ok的。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#8948]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题
客户那边 从yapi导出一个 swagger 2.0规范的文档，导入MS提示解析错误，postman导入是ok的。
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复
