### ISSUE TITLE
[BUG]CASE复制，去掉前面的copy_后，鼠标失去焦点，提示名称不能相同，再次编辑后，无法保存

### ISSUE THREAD

**Issue by qiuximei** [metersphere/metersphere#8954]
**MeterSphere 版本**--v1.15.4-a1b8953b

**Bug 描述**
复制CASE后，编辑标题，偶现保存不生效

**Bug 重现步骤**

1.  选择一个用例，点击复制，弹出用例编辑窗口
2. 删除前面的copy_，失去焦点，提示名称不能相同
3. 再次编辑名称后，失去焦点，无法保存，点击保存按钮也是无法保存；

**期待的正确结果**
每次编辑后，都可以保存成功

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，1.15.4版本确实有复现，新版本没有这个问题，升级下吧
