### ISSUE TITLE
[FEATURE]接口用例里定义的变量，在使用时，能否提供一个变量列表，让大家勾选来决定使用哪个变量。类似eolinker等接口测试工具。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8960]
**请描述您的需求或者改进建议.**

[FEATURE]接口用例里定义的变量，在使用时，能否提供一个变量列表，让大家勾选来决定使用哪个变量。类似eolinker接口测试工具里面的变量管理。

变量管理list里可以看到此变量是哪个接口用例定义的

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
1.17 会支持
