### ISSUE TITLE
[BUG] 关联的用例已被删除   在执行这个计划时就报系统SQL错误了

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8961]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  关联的用例已被删除   在执行这个计划时就报系统SQL错误了
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/147632348-95007c29-b4b4-4dc7-8588-e81bdcca1e96.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现这个问题，升级下吧
