### ISSUE TITLE
[BUG] 测试计划里，都是手动执行，并且都是执行完成100%，执行次数统计却不一样。 另外执行次数是如何统计的？

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8963]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 测试计划里，都是手动执行，并且都是执行完成100%，执行次数统计却不一样。 另外执行次数是如何统计的？
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
测试计划里，都是手动执行，并且都是执行完成100%，执行次数统计却不一样。 另外执行次数是如何统计的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/147632464-7dd70b5c-1bf2-4d79-896b-2192b32ad21e.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，执行次数包括测试计划 列表页执行整个测试计划+定时任务执行的测试计划次数+jenkins api 调用执行次数
你的情况是不是进入测试计划里面单独执行的某个接口或者场景用例啊？这个不算在测试计划执行次数
