### ISSUE TITLE
[BUG] 接口测试：新建接口，没有保存前点击关系依赖视图，系统报错误

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8965]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口测试：新建接口，没有保存前点击关系依赖视图，系统报错误
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/147632726-48ff0f0c-db3c-4e61-9894-f6c7e89c0300.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，这个问题1.16.2 版本没问题了。建议升级下吧
