### ISSUE TITLE
[FEATURE] 测试用例维护时，希望系统提供自动保存功能。类似其他测试用例管理工具如testcase，xmindtestcase等。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8966]
**请描述您的需求或者改进建议.**

测试用例维护时，希望系统提供自动保存功能。类似其他测试用例管理工具如testcase，xmindtestcase等。

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
目前我们支持快捷键ctrl+s 保存，自动保存还有一些问题需要克服
