### ISSUE TITLE
[BUG]接口导入：swagger 2.0 json文件导入后，有些接口参数没有导入到MeterSphere系统里。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#8970]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.1

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  接口导入：swagger 2.0 json文件导入后，有些接口参数没有导入到MeterSphere系统里。
2. 如果需要接口文件到时候可以直接给我发微信。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/147634072-d5e96e07-f2bd-4ac0-8a04-74ae082b51fe.png)
![image](https://user-images.githubusercontent.com/78218624/147634097-21165acd-04e7-4ede-b19d-62fa5479fe26.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
文件发一下吧 ，感谢

**Comment by huangxine** [comment]
请查收附件为swagger导出的文件


我是飞致云的黄新娥，如果有问题也可以微信直接交流


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]接口导入：swagger 2.0 json文件导入后，有些接口参数没有导入到MeterSphere系统里。 (Issue #8970)





 
文件发一下吧 ，感谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youliyuan-fit2cloud** [comment]
感谢，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本已修复，升级下吧
