### ISSUE TITLE
[BUG]测试计划报告场景有很多结果显示未开始，查到接口场景处于waiting中

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#8971]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.1
**Bug 描述**

简要描述您碰到的问题
测试计划报告场景有很多结果显示未开始，查到接口场景处于waiting中
**Bug 重现步骤**

1.  测试计划设置每天定时跑
2. 查看测试计划执行报告
3. 
4. 

**期待的正确结果**
所有测试用例执行成功
正确情况下应该是什么样的？
执行成功或者失败
**截图**

![1](https://user-images.githubusercontent.com/45531073/147635115-a878605d-eb62-46b9-a5cd-e22bf9eda64c.png)
![2](https://user-images.githubusercontent.com/45531073/147635119-c7228627-c386-4e9e-8e5c-bb104a574e93.png)

如果有截图，请附上截图.

**Comment by liushuneng** [comment]
在客户环境必现问题

**Comment by liushuneng** [comment]
客户环境没有用nginx

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6版本以上没有复现这个问题了，升级一下吧
