### ISSUE TITLE
[BUG]接口自动化点击调试，测试结果未同步

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#8972]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.1
**Bug 描述**

简要描述您碰到的问题
接口自动化点击调试，测试结果未同步
**Bug 重现步骤**

1.  打开创建的接口自动化场景
2. 点击调试
3. 
4. 

**期待的正确结果**
接口执行完，同步测试结果
正确情况下应该是什么样的？
显示执行成功或者失败
**截图**
![3](https://user-images.githubusercontent.com/45531073/147635260-5e4a75f1-6fa7-4fa4-b0fc-5d75f1056c2c.png)

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
初步排查发现更新结果的 websocket 连接超时断掉了，建议先增加前端 nginx 或其他负载均衡的超时时间。
后续版本通过增加保持连接机制解决此问题。

**Comment by liushuneng** [comment]
在客户环境必现问题

**Comment by liushuneng** [comment]
客户环境没有用nginx

**Comment by youliyuan-fit2cloud** [comment]
和#8902 相同所以close该issue
Duplicate of #8902
