### ISSUE TITLE
[BUG]在接口自动化功能项，场景步骤里面的禁用按钮，点击禁用之后，状态无法保存。

### ISSUE THREAD

**Issue by Eric-Hyiboo** [metersphere/metersphere#8973]
**MeterSphere 版本**

1.16.1

**Bug 描述**

在接口自动化功能项，场景步骤里面的禁用按钮，点击禁用之后，状态无法保存。

**Bug 重现步骤**

1.  点击禁用，禁用所有步骤
2. 保存，退出
3. 重新打开场景，场景步骤中的状态不一致

![image](https://user-images.githubusercontent.com/83943743/147635402-f8c202ab-f4eb-444b-9edd-7ab2b6ed0fea.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
这都被你发现了，👍 
后续版本优化下

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
