### ISSUE TITLE
[BUG]接口自动化场景，点击生成报告，测试结果未同步更新

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#8974]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.1
**Bug 描述**

简要描述您碰到的问题
接口自动化场景，点击生成报告，测试结果未同步更新
**Bug 重现步骤**

1.  打开创建的自动化场景
2. 点击生成报告
3. 
4. 

**期待的正确结果**
同步测试结果
正确情况下应该是什么样的？
同步测试结果
**截图**
![4](https://user-images.githubusercontent.com/45531073/147635438-3a22f022-9540-4669-9821-ef637a39238f.png)

如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
同 #8972 
初步排查发现更新结果的 websocket 连接超时断掉了，建议先增加前端 nginx 或其他负载均衡的超时时间。
后续版本通过增加保持连接机制解决此问题。

**Comment by liushuneng** [comment]
在客户环境必现问题

**Comment by liushuneng** [comment]
没有使用nginx

**Comment by liushuneng** [comment]
客户环境没有用nginx

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6版本已修复
