### ISSUE TITLE
[FEATURE]测试跟踪测试报告显示条目

### ISSUE THREAD

**Issue by Eric-Hyiboo** [metersphere/metersphere#8975]
**请描述您的需求或者改进建议.**

测试跟踪--->报告，这里面的报告列表是否可以添加两个条目，pass多少，fail多少？

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/83943743/147635661-ef9f0686-5210-4b6f-95b3-344970f72893.png)

**Comment by luty2018** [comment]
1.17会增加成功率
