### ISSUE TITLE
[BUG]接口定义--测试单接口，首次执行测试，都会卡主，停止后，重新运行，才正常

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#8984]
**MeterSphere 版本**
1.16.1
您所使用的 MeterSphere 版本是？
1.16.1
**Bug 描述**
接口定义--测试单接口，首次执行测试，都会卡主，停止后，重新运行，才正常
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
执行单接口测试，功能正常
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/18163887/147640553-16704ace-1a6d-400a-8d6c-d590f30f6993.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，今天下午发布的v1.16.2已经修复这个问题，升级下吧
