### ISSUE TITLE
[BUG] 接口正常执行，返回200。而且没配置断言，但显示是执行失败

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#8985]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/7685661/147641144-22ecc2e6-569d-41e4-9842-0321716d88c9.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，没有遇到过这个问题，方便把这个接口用例文件发我们试试吗？
