### ISSUE TITLE
[BUG]jmv文件导入到接口自动化里，无法显示接口的路径

### ISSUE THREAD

**Issue by liaopeng-lp** [metersphere/metersphere#8992]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.1

**Bug 描述**

把jmeter的jmv文件导入到metersphere的接口自动化里，无法显示接口的路径

**Bug 重现步骤**

1. 利用jmeter编写一个正常的请求 
2. 导入到metersphere接口自动化里
3. 对比两个接口的路径
4. 

**期待的正确结果**

正确情况下应该是什么样的？
两个的接口应该是一致的
**截图**

如果有截图，请附上截图.
![ef0a989232f2d921986546f4ea92d24](https://user-images.githubusercontent.com/96818997/147647504-5a956a9c-edb1-42be-9221-db00908b45a0.png)
![55251e462aa0746cfd7e09af192d57e](https://user-images.githubusercontent.com/96818997/147647520-06a04d00-9c80-4723-8f12-8e49bf38e611.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复一下

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本已修复
