### ISSUE TITLE
[FEATURE] 执行测试计划的时候，可以提交用例失败原因，日志

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#8998]
**请描述您的需求或者改进建议.**
执行测试计划的时候，可以提交用例失败原因，日志

**请描述你建议的实现方案**
执行测试计划的时候，可以提交用例失败原因，日志

**Comment by AgAngle** [comment]
你好，我们在执行过程中可以写评论，这个不能满足您的需求吗
