### ISSUE TITLE
[BUG]测试计划执行效率逐步降低

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#8999]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.5
**Bug 描述**

简要描述您碰到的问题
测试计划定时运行一段时间后，重复执行该计划，执行时间逐步拉长，执行效率逐步降低
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
收到，我们尽量再再再优化一下~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6版本已优化，期待您的反馈！
