### ISSUE TITLE
[FEATURE]关联用例可以不做已选排除处理

### ISSUE THREAD

**Issue by wszbc** [metersphere/metersphere#9004]
**请描述您的需求或者改进建议.**
测试用例关联自动化用例时，希望可以不做已选就排除处理，比如我的手工用例有个入库场景一个出库场景，入库以后才能去出库，我写自动化的时候就是将入库和出库写在一起是一个场景，如果分开就是要执行一次入库，又要执行一次入库出库，这样其实场景重复了，所以合在一起可以提高执行效率，可能还有很多这种流程性的场景都可以一个完整的自动化涵盖好几条手工测试用例。

**请描述你建议的实现方案**
本身就是关联测试用例，那么测试用例只要选择被覆盖到的自动化用例就可以了，不需要被选过的自动化用例就不能再被选了，自动化用例可以被手工用例一对多

**Comment by luty2018** [comment]
已排期
