### ISSUE TITLE
[BUG]公共用例库的的id不显示

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9005]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
16.1
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  项目1添加多个功能用例至公共用例库
2. 切换到项目2
3. 公共用例库中的id和当前项目2id重复，不显示id
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![用例无id](https://user-images.githubusercontent.com/36387811/147716269-d85526bc-c6ff-4cdb-b75e-4c0673415c3c.jpg)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现这个问题，如果id相同可以重复显示的，还没有做限制
