### ISSUE TITLE
[FEATURE]在执行用例处新增缺陷时，同步用例内容，避免二次填写。

### ISSUE THREAD

**Issue by break002** [metersphere/metersphere#9011]
**请描述您的需求或者改进建议.**
在执行用例处新增缺陷时如果需要同步到jira或者禅道之类平台，需要自己填写用例的操作过程，建议可以直接把用例内容关联到缺陷详情内，减少缺陷时对操作步骤的描述

**请描述你建议的实现方案**
在执行用例处新增缺陷时如果需要同步到jira或者禅道之类平台，需要自己填写用例的操作过程，建议可以直接把用例内容关联到缺陷详情内，减少缺陷时对操作步骤的描述

**Comment by luty2018** [comment]
已排期
