### ISSUE TITLE
[BUG]接口测试>>接口定义>>编辑接口>>【TEST】页签：测试完成后，点击“另存为测试用例”，系统特别慢，点击网页的刷新，生成了两条一样的测试用例

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9012]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.2

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [接口测试>>接口定义>>编辑接口>>【TEST】页签：测试完成后，点击“另存为测试用例”，系统特别慢，点击网页的刷新，生成了两条一样的测试用例
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![另存测试用例1](https://user-images.githubusercontent.com/78218624/147720739-5a2b0ee0-0df2-42c2-ae0b-be7a3db93c0f.png)
![另存测试用例2](https://user-images.githubusercontent.com/78218624/147720748-58266b02-24be-433f-9ef4-de6ace34e7cb.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，这个情况看起来和当时的网络状况，环境运行状态有关系，是必现的问题吗？
