### ISSUE TITLE
[BUG]接口的case的执行和api的调试都一直没有结果

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9014]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.1
**Bug 描述**

简要描述您碰到的问题
更新到v1.16.1接口的case的执行和api的调试都一直没有结果
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
正在努力解决中。。。。
