### ISSUE TITLE
[BUG]接口测试模块，添加了定时任务，且执行完成后，在首页-场景定时任务数量统计栏未显示对应的本周执行、历史总执行、成功率等数据，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9018]
**MeterSphere 版本**

v1.16.1-b81189dd

**Bug 描述**

接口测试模块，添加了定时任务，且执行完成后，在首页-场景定时任务数量统计栏未显示对应的本周执行、历史总执行、成功率等数据，请修改

**截图**
![image](https://user-images.githubusercontent.com/92150453/147727042-76a1bbc8-6bbb-49de-a7fe-4614a8bf95ae.png)
![image](https://user-images.githubusercontent.com/92150453/147727235-3c624660-5d32-4448-a06f-61b4a6d7b929.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4 版本已修复
