### ISSUE TITLE
[FEATURE]场景自动化增加仅一次事务控制器

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#9019]
**请描述您的需求或者改进建议.**
首先非常感谢贵公司，以及平台的开发人员开发如此优秀的平台，并与大家分享

目前公司使用metersphere接口自动化平台半年，从参与人数的增加，到用例数的增加，算是小有成效，合计已经编写2409个用例，步骤总数15000步；

未来也希望接口自动化用例能够直接转性能测试脚本在平台运行，但是有如下痛点

痛点一：从场景自动化用例转性能测试时，部分接口在整个线程中只需要调用一次，但是场景菜单中没有仅一次事务控制器可以调用
测试单个接口性能时，部分前提需要准备的数据量较大，需要重数据库连表查询获得，该类脚本只需要执行一次，或者登陆接口

痛点二：
线上接口自动化用例集，运行偶现告警（阿里云服务器dns解析异常，偶现次数较少），报错在允许范围内，但是线上自动化是24小时执行，夜间此类不友好的告警，严重影响维护人的体验
建议增加场景失败重试机制，第二次还是失败才是真的失败

**请描述你建议的实现方案**
痛点一：场景自动化增加仅一次事务控制器
痛点二：增加失败重试机制（一般优秀的测试框架都有该机制），当然针对该场景也有其他解决方案，但是还是希望告警是真实告警，减小容许的误告警

**Comment by luty2018** [comment]
非常感谢对metersphere的支持，针对你提的两个建议，我们已经采纳，待排期处理，请关注后续版本规划！
