### ISSUE TITLE
[BUG]脑图编写用例的时候，不能修改模块下面的用例，修改后会报错

### ISSUE THREAD

**Issue by diaohanji** [metersphere/metersphere#9020]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.2-0b7d1ab8

**Bug 描述**

简要描述您碰到的问题
脑图编写用例的时候，不能修改模块下面的用例，修改后会报错

**Bug 重现步骤**

1、新增节点，标记为“模块”，保存
2、在新增的节点下新增用例节点，保存

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![lQLPDhsCH-3baZLNAz_NAwSwFikwa8xyRUUB1CeC3cAcAA_772_831](https://user-images.githubusercontent.com/43695413/147729084-739686e1-aca9-4024-9b38-0b0dbd97a45b.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by luty2018** [comment]
建议更新版本，目前在1.16.5无法重现

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
