### ISSUE TITLE
[FEATURE]跟踪测试关联缺陷，缺陷用例可以按id自动排序

### ISSUE THREAD

**Issue by jstbw** [metersphere/metersphere#9022]
**请描述您的需求或者改进建议.**
跟踪测试关联缺陷，目前缺陷用例不能自动排序，不方便查找
![5401066be18e71be9ca85def47f7254](https://user-images.githubusercontent.com/66759501/147730477-58641d67-c4b4-4bea-a400-e3594fc4b9ba.png)
![image](https://user-images.githubusercontent.com/66759501/147730507-5ff9a7c0-ab9f-4c74-b05a-89abf65f6354.png)

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.** 跟踪测试关联缺陷，目前缺陷用例不能自动排序，不方便查找 ![5401066be18e71be9ca85def47f7254](https://user-images.githubusercontent.com/66759501/147730477-58641d67-c4b4-4bea-a400-e3594fc4b9ba.png) ![image](https://user-images.githubusercontent.com/66759501/147730507-5ff9a7c0-ab9f-4c74-b05a-89abf65f6354.png)

已规划，等待排期
