### ISSUE TITLE
[BUG] 报文体中增加参数引用后导致报文出错

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#9024]
**MeterSphere 版本**
1.16.2 

**Bug 描述**

![image](https://user-images.githubusercontent.com/8164903/147734973-f063c580-22ad-44b2-a4ab-7a7d2ed695e6.png)
![image](https://user-images.githubusercontent.com/8164903/147734985-fe56b671-5655-4d37-862f-0ede29ae4103.png)

![image](https://user-images.githubusercontent.com/8164903/147734897-79be7719-ba0f-4a04-bdba-32068104eb4f.png)
![image](https://user-images.githubusercontent.com/8164903/147734919-210a5038-b799-4d1b-a3a1-2c478f02dfd2.png)

**Comment by tangw1257** [comment]
如上图， 当报文中不设置变量，报文以原报文方式进行发送。
当设置变量后，报文被转换，改变了\\ 为\

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本会优化下

**Comment by zyyfit** [comment]
目前我们定位是jmeter的一个问题，使用的时候可以先不设置变量，等jmeter修复
