### ISSUE TITLE
[BUG] HTTP接口测试中前置脚本中无法获取报文

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#9025]
**MeterSphere 版本**
1.16.2

**Bug 描述**
![image](https://user-images.githubusercontent.com/8164903/147735591-f78fd51e-267d-431c-b725-fd3e873a4921.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，你当前选中的groovy和报文头添加长度的脚本不匹配，这个默认的脚本是beanshell 下的，如果要用groovy的要自己写下

**Comment by tangw1257** [comment]
选择beanshell也是一样的 错误不一样。  这个同样的脚本在tcp中可以使用，建议试一试

**Comment by tangw1257** [comment]
选择beanshell也是一样的 错误不一样。  这个同样的脚本在tcp中可以使用
