### ISSUE TITLE
[BUG] 场景调试历史显示问题

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#9028]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.2
**Bug 描述**

简要描述您碰到的问题
场景调试历史，点开报告里面是空
 
**期待的正确结果**
期待打版本的时候多回归一下
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by congim** [comment]
![image](https://user-images.githubusercontent.com/10218415/147798453-5d1b89dd-5c99-4194-9219-a4728cb7bf85.png)

**Comment by congim** [comment]
历史测试的调试数据也不兼容
![image](https://user-images.githubusercontent.com/10218415/147798495-4b6e423b-2961-4cca-bd73-f7eb803f9099.png)

**Comment by congim** [comment]
![image](https://user-images.githubusercontent.com/10218415/147798507-df58db03-f514-4edf-8a9b-d8ca3ba08f3b.png)

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #8974

**Comment by congim** [comment]
@youliyuan-fit2cloud  我这个是新的调试历史显示为空 & 历史数据不兼容 问题，怎么就关了，看描述也不像是同一个问题啊
