### ISSUE TITLE
[BUG] api url修改之后，case等显示都正常，在实际的场景中发出去的请求url还是老的

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#9029]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
所有版本都有这个问题
**Bug 描述**

简要描述您碰到的问题
api url修改之后，case等显示都正常，在实际的场景中发出去的请求url还是老的

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本没有复现这个问题，场景中是“引用”的CASE 吗？复制接口或接口CASE到场景是不能同步修改的

**Comment by youliyuan-fit2cloud** [comment]
而且在场景里面引用接口CASE只能用场景里面的运行环境即URL，接口CASE的路径是会同步的

**Comment by congim** [comment]
引用的case，不是复制的；在场景中显示是正确的url，实际发出去的请求还是未修改的

**Comment by congim** [comment]
我在1.16.2上面测试了 这个问题一直没修改；

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/147810082-dbde3da0-37b6-4637-8256-09c32f222b65.png)

建议把你的截图发一下哈

**Comment by congim** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/10218415/147816374-fda0cfe0-7f10-4ac8-b218-4c2532ef9036.png">

**Comment by congim** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/10218415/147816416-afe6db32-dc37-46db-bf46-5e7b2fc3895e.png">

**Comment by congim** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/10218415/147816464-de683518-512e-4a5d-8dfa-09bfd61a96fb.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/10218415/147816504-5932cd78-964f-4926-9e37-0ce8a9532632.png">

**Comment by congim** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/10218415/147816576-63f43eda-88f9-4cfa-b7b4-ed4aca46ba9c.png">

**Comment by youliyuan-fit2cloud** [comment]
非常感谢 你的反馈截图，看了你的这个大场景是 引用场景+复制场景+引用接口CASE，确实有这个问题，之前没有验证这种情况，再次感谢~，下个版本修复~~~~~~
