### ISSUE TITLE
[BUG] 接口测试json格式没有转换

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#903]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.5

**Bug 描述**
在接口请求中，传入参数类型是json格式，将一条json格式内容复制进去，没有转为json格式。
![image](https://user-images.githubusercontent.com/34681889/101451036-73f7d000-3966-11eb-979e-b43c6d7b5e0c.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，当前版本把自动格式化功能暂时去掉了，后续会增加单独的格式化按钮
