### ISSUE TITLE
[BUG]导入的jmx文件，执行用例一直在执行中

### ISSUE THREAD

**Issue by PIDAN524** [metersphere/metersphere#9031]
**MeterSphere 版本**
1.14
**Bug 描述**

导入jmx文件，执行jmx用例，一直处于执行中

**Bug 重现步骤**

1.  接口定义-更多操作-导入
2. 选择jmx文件导入
3. 选择导入的case 点击执行
4. 用例处于执行中

**期待的正确结果**

显示操作成功

**截图**
![image](https://user-images.githubusercontent.com/54307955/147798760-560158fa-173e-4452-bc12-f613e22efaee.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本会修复该问题~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.4版本没有复现该问题了
