### ISSUE TITLE
[BUG] V1.16.1 版本，环境配置中设置的请求头会覆盖场景 case 中定义的请求头参数

### ISSUE THREAD

**Issue by gongbaojid** [metersphere/metersphere#9038]
**MeterSphere 版本**

V1.16.1

**Bug 描述**

环境配置中设置的请求头会覆盖场景 case 中定义的请求头

**Bug 重现步骤**

1.  在环境配置中设置请求头参数
2.  在场景 case 中配置一个相同名称的header参数
3.  执行用例
4.  查看执行结果

**期待的正确结果**

环境配置中设置的请求头不会覆盖场景case中配置的相同名称的请求头参数

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这里我们计划优化优先级了，请关注后续版本~

**Comment by youliyuan-fit2cloud** [comment]
请升级到最新版本试试吧，环境变量和场景变量同名时，场景变量优先
