### ISSUE TITLE
[BUG] cpu莫名跑满一个核或者多个核 v1.16.2

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#9042]
**MeterSphere 版本**
 v1.16.2

没有任务在跑就这个样子

![image](https://user-images.githubusercontent.com/10218415/147805760-e7e9a688-cc34-4d3d-8ce3-31f391aca57d.png)

**Comment by congim** [comment]
然后页面就白屏了，半天才能反应过来

**Comment by youliyuan-fit2cloud** [comment]
你好，我们需要研究下什么原因再优化一下

**Comment by congim** [comment]
这种问题只能你们多回归测试了，我也只是部署了 跑了几个任务就这样了 然后就回滚了

**Comment by youliyuan-fit2cloud** [comment]
> 这种问题只能你们多回归测试了，我也只是部署了 跑了几个任务就这样了 然后就回滚了

感谢，是回滚到1.16.1版本不会出现这个问题了吗？
