### ISSUE TITLE
[BUG]接口请求条件中条件表达式没有跟随选择项切换

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#905]
**MeterSphere 版本**
您所使用的 MeterSphere 版本1.5

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  点击请求接口的条件，内容输入要用引用变量方式，例如 ${myid}
2. 点击条件中的几种表达关系，页面没有跟随改变。
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/34681889/101458983-9b549a00-3972-11eb-8cf4-d3b66d9b785f.png)

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
