### ISSUE TITLE
[FEATURE]计划测试报告中的测试用例列表，希望点击用例能查看用例的明细信息，而不是要重新打开页面，查找用例，然后才能查看用例明细，操作特别繁琐，效率不高

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9050]
**请描述您的需求或者改进建议.**

[FEATURE]计划测试报告中的测试用例列表，希望点击用例能查看用例的明细信息，而不是要重新打开页面，查找用例，然后才能查看用例明细，操作特别繁琐，效率不高

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/78218624/147807510-a8676e3c-4d3e-40f6-bb0b-5bced39e7fc9.png)

**Comment by luty2018** [comment]
已采纳，待排期
