### ISSUE TITLE
[QUESTION] 目前稳定版本停止更新了吗？

### ISSUE THREAD

**Issue by congim** [metersphere/metersphere#9058]
**请描述您的问题.**
目前稳定版本停止更新了吗？tags里面只打到v1.10.11-lts版本，是只打算发布商业稳定版本了吗？

**Comment by wangzhen-fit2cloud** [comment]
你好，1.10 lts 版本是不定期按需更新的，针对该版本短时间内只会进行问题修复，不会增加新的功能。
