### ISSUE TITLE
[BUG]接口测试GET请求的json请求体没有正确发送

### ISSUE THREAD

**Issue by vision-ken** [metersphere/metersphere#906]
**MeterSphere 版本**
版本: v1.5-0abd7209

**Bug 描述**
接口测试GET请求的json请求体没有正确发送。

**Bug 重现步骤**
1.  在接口测试新建一个GET请求。
2. 请求体为一个json。
3. 点击”调试“发送请求。

**期待的正确结果**
预期GET请求能正确发送json请求体，但是实际没有。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/24715266/101469209-68fd6980-397f-11eb-976e-86d32336d571.png)
![image](https://user-images.githubusercontent.com/24715266/101469380-a5c96080-397f-11eb-9ae1-f5ba28948640.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请使用新版的接口测试重新试一下
