### ISSUE TITLE
[BUG]选择不同的测试环境执行接口用例时，报如图所示错误

### ISSUE THREAD

**Issue by diaohanji** [metersphere/metersphere#9068]
**MeterSphere 版本**
1.16

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  执行接口用例
2. 切换到某一个环境
3. 点击执行，报截图所示错误

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/43695413/147813951-1a524a75-d5c7-47e4-a18d-f059563a88d3.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，复现了，下个版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.3无法复现，建议升级下
