### ISSUE TITLE
分布式测试环境部署文档不全

### ISSUE THREAD

**Issue by dengfuxing** [metersphere/metersphere#907]
目前要部署一套分布式测试环境，但是不知道如何下手，node-controller和master节点需要哪些组件都不清楚，急需一套完整文档，细化到每个节点如何部署，该部署哪些组件

**Comment by wangzhen-fit2cloud** [comment]
1. 先使用默认的安装脚本部署一套环境
2. 参考文档 FAQ 部分部署额外的 node-controller 节点
3. 在系统设置资源池中添加新部署的节点
