### ISSUE TITLE
[QUESTION]k8s helm 部署，压力测试jmeter没有启动

### ISSUE THREAD

**Issue by mfanoffice** [metersphere/metersphere#9076]
**请描述您的问题.**
k8s helm 部署metersphere, 页面调试测试脚本都通过了，但是压力测试start，没有任何反应，jmeter也没有启动，日志：
kubectl logs -f metersphere-node-controller-77765bdc44-hwswl

2022-01-01 17:01:36,711  WARN thub.dockerjava.core.DockerClientBuilder:  96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.
---
请问如何排查？下面是相关的配置截图：

测试页面显示：
![image](https://user-images.githubusercontent.com/48307752/147847542-6fbe1c10-a320-48f5-88d2-a2a4f5325468.png)
系统参数：
![image](https://user-images.githubusercontent.com/48307752/147847548-fa102752-65de-4367-aa4a-75743af6947f.png)
环境管理：
![image](https://user-images.githubusercontent.com/48307752/147847551-75761a3f-2606-44c0-a75c-12701b9ae89b.png)

**Comment by wangzhen-fit2cloud** [comment]
请看下 metersphere-node-controller 这个 pod 中 /opt/metersphere/logs/node-controller/info.log 中的日志

**Comment by heshaol** [comment]
我也有类似的问题。
node日志：2022-08-12 14:07:26,906  WARN thub.dockerjava.core.DockerClientBuilder:  96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.


2022-08-12 14:12:07,078  WARN thub.dockerjava.core.DockerClientBuilder:  96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.

**Comment by wan92hen** [comment]
> 我也有类似的问题。 node日志：2022-08-12 14:07:26,906 WARN thub.dockerjava.core.DockerClientBuilder: 96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.
> 
> 2022-08-12 14:12:07,078 WARN thub.dockerjava.core.DockerClientBuilder: 96 - 'dockerHttpClient' should be set.Falling back to Jersey, will be an error in future releases.

metersphere-server pod 中的日志 /opt/metersphere/logs/metersphere/info.log 也看下哈。
