### ISSUE TITLE
[FEATURE]建议接口测试中增加请求体如果为json格式参数时候，自动将json参数格式化显示

### ISSUE THREAD

**Issue by feiyu0316** [metersphere/metersphere#909]
**请描述您的需求或者改进建议.**

建议接口测试中增加请求体如果为json格式参数时候，自动将json参数格式化显示

**请描述你建议的实现方案**
建议接口测试中增加请求体如果为json格式参数时候，自动将json参数格式化显示，从外部复制json串黏贴进请求体的时候，自动格式化显示json串

**Comment by wangzhen-fit2cloud** [comment]
目前自动格式化存在一个问题，如果在其中使用了 ${var1} 这样的变量，这个变量的 {} 也会被格式化换行，导致变量不能成功解析。这个问题不是很好处理所以先暂时去掉了自动格式化功能，计划在这里加一个整理格式的按钮，点击后才进行格式化

**Comment by zyyfit** [comment]
已优化
