### ISSUE TITLE
[BUG]JSONPath提取器数据精度丢失

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#9090]
**MeterSphere 版本**

1.15.4

**Bug 描述**

JSONPath提取器数据精度丢失

**Bug 重现步骤**

1.  接口返回结果"tenantId":891743020427247616
2. 通过JSONPath提取器获取结果显示：891743020427247600

**期待的正确结果**

显示精确的数字结果（"tenantId":891743020427247616）

**截图**

![wecom-temp-d0c7c53d0c778ee8c150e892373acb20](https://user-images.githubusercontent.com/34698664/148002643-83b89431-1723-413b-a054-5a67f92019cc.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5已解决，升级下吧
