### ISSUE TITLE
[BUG]接口自动化模块页签关不掉

### ISSUE THREAD

**Issue by PIDAN524** [metersphere/metersphere#9100]
v1.14
 接口测试-接口自动化模块打开的页面无法关闭

**Bug 重现步骤**

1.  点击【接口测试】-【接口自动化】
2. 选择一个场景，点击编辑
3. 页面增加一个页签，点击【x】按钮，试图关闭页签
4. 无法关闭

**期待的正确结果**

正确情况下应该是什么样的？
点击【X】按钮，页签关闭

![image](https://user-images.githubusercontent.com/54307955/148018405-16a428e7-4612-4601-a6ca-ffde1fdc1235.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，升级一下吧，新版本有解决这个问题
