### ISSUE TITLE
[BUG]接口测试，有多个场景，每个场景间的变量冲突了，所有场景里用的变量都是其中一个场景的。该问题麻烦尽快解决，要不然接口自动化进行不下去了

### ISSUE THREAD

**Issue by tomato111-liu** [metersphere/metersphere#911]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.5.0-b1192
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  接口测试里，一条用例里有多个场景，每个场景都设置了变量。
2. 每个场景里设置了多条用例
3. 执行时，各个场景的变量会冲突。其他的场景也用的其中一个场景的变量
4. 

**期待的正确结果**
正确情况下应该是什么样的？
单独每个场景的接口都用该场景里设置的变量，各个场景间不搭嘎。
这个问题可能需要很多场景才出现，最开始的时候我设置了9个场景都没问题。后面可能删了场景又加场景，就出现该问题。
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，目前该问题可以先通过不同场景使用不同变量名的方式规避下，我们会在后续的版本中来解决该问题

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.6 之后的接口测试修改了场景的编辑方式，请升级验证
