### ISSUE TITLE
[需求]测试计划报告列表建议增加成功/失败的状态筛选以及历史报告提供编辑保存功能

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#9111]
**请描述您的需求或者改进建议.**
实际场景中我们要求对失败的测试计划有一个处置措施，并且能保存跟踪这个处置。
所以建议：
1.测试跟踪-报告列表中增加 成功/失败 的状态筛选
2.历史报告详情页里提供编辑保存功能

 建议一 成功/失败 的状态筛选用以筛选出历史失败的测试计划。
 建议二 历史报告详情页里提供编辑保存功能，用以保存失败的处理措施，方便以后跟踪统计。

**请描述你建议的实现方案**

![Uploading 54299929-82E3-4ebb-B588-EA26A836E7BF.png…]()

**Comment by qingmu2633** [comment]
![C0A71204-3351-475f-A978-166CE793126B](https://user-images.githubusercontent.com/86302975/148035796-6d5e65f7-6115-4716-9399-5be82fc48c10.png)

**Comment by qingmu2633** [comment]
![54299929-82E3-4ebb-B588-EA26A836E7BF](https://user-images.githubusercontent.com/86302975/148153402-020fa6bb-e5c2-4407-a19c-99827c532ba2.png)

**Comment by Hyyfit** [comment]
已规划，待排期。
