### ISSUE TITLE
[FEATURE]用例详情中，添加关联缺陷的搜索功能

### ISSUE THREAD

**Issue by lulucky515a** [metersphere/metersphere#9114]
**请描述您的需求或者改进建议.**
1、根据测试用例创建测试计划
2、进入测试用例详情中，关联bug
3、搜索现存的bug，只有一个个搜索，效率太低了

**请描述你建议的实现方案**
建议在关联bug中可以添加搜索功能，方便搜索
![截屏2022-01-04 下午5 56 09](https://user-images.githubusercontent.com/45556675/148042113-ff00ce73-d7dc-4f99-b14f-c399e7394849.png)

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.** 1、根据测试用例创建测试计划 2、进入测试用例详情中，关联bug 3、搜索现存的bug，只有一个个搜索，效率太低了
> 
> **请描述你建议的实现方案** 建议在关联bug中可以添加搜索功能，方便搜索 ![截屏2022-01-04 下午5 56 09](https://user-images.githubusercontent.com/45556675/148042113-ff00ce73-d7dc-4f99-b14f-c399e7394849.png)

已规划，等待排期
