### ISSUE TITLE
[FEATURE]允许每个人配置禅道账号

### ISSUE THREAD

**Issue by zyy2721** [metersphere/metersphere#912]
**请描述您的需求或者改进建议.**
从MeterSphere推送过来的所有bug提出人都是同一个，但禅道无法修改bug的提出人，不便使用。
希望可以允许每个人配置禅道账号，方便区分bug提出人。

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢你的反馈，这个我们需要调研下具体如何实现，如果你有比较好的想法也可以再反馈下。

**Comment by xulinde** [comment]
与issue#1524重复
