### ISSUE TITLE
[FEATURE]建议断言脚本编辑功能，提供一个确认保存的功能

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#9121]
**请描述您的需求或者改进建议.**
接口自动化--断言--脚本方式，编辑断言脚本，没有保存确认功能，现在编辑后，即保存，有时候误操作，导致原来的脚本丢失

**请描述你建议的实现方案**
建议断言脚本编辑，增加一个保存确认的操作

**Comment by Hyyfit** [comment]
> 断言脚

未复现，目前是点击最外层的保存才会实现保存，没有自动保存。
