### ISSUE TITLE
[BUG]在自动化场景内，log.info显示的有问题

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9122]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.2

**Bug 描述**

在自动化场景内，如果把自定义脚本放到接口之前，log.info的打印是可以显示在控制台的，放在接口之后就显示不出来
但是在自动化列表中点击运行，都可以在控制台显示出来

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，确实存在这个问题，我们后续版本优化一下~

**Comment by zyyfit** [comment]
已修复，1.16发布，给自定义脚本步骤也添加了执行结果展示
![图片](https://user-images.githubusercontent.com/73461316/150266233-b2a1c550-ebec-4d9d-9436-2cb6538a1a72.png)

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
