### ISSUE TITLE
[BUG]接口自动化列表点击运行的报告与最后在测试报告内显示的统计数据不一致

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9123]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.2

**Bug 描述**

简要描述您碰到的问题
接口自动化列表点击运行的报告与最后在测试报告内显示的统计数据不一致

**期待的正确结果**

如果有截图，请附上截图.
列表运行结果：
![image](https://user-images.githubusercontent.com/32027713/148151096-fde688c1-2c72-428a-a3eb-588e71fc12f5.png)
最后报告结果：
![image](https://user-images.githubusercontent.com/32027713/148151131-2b331682-125e-49bb-a0e7-310427069fb2.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，建议升级到最新版本v1.16.4，我们又优化了一下....
