### ISSUE TITLE
[BUG]Metersphere的企业版License经常丢失

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9124]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.2

**Bug 描述**

升级到1.16.2版本之后，经常遇到刷新页面之后，license丢失，我的工作台及自定义主题设置之类的xpack功能按钮丢失

![image](https://user-images.githubusercontent.com/32027713/148151471-5afdaaa8-fd2b-4106-9618-aae21c94e14a.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，升级到1.16.4吧，已经修复了
