### ISSUE TITLE
[BUG]测试报告中的缺陷列表的平台状态显示异常

### ISSUE THREAD

**Issue by liudezhi2098** [metersphere/metersphere#9125]
**MeterSphere 版本**

1.16.3

**Bug 描述**

![image](https://user-images.githubusercontent.com/33149602/148157969-ee957f9c-bb1c-4c5e-bd4a-2388e8fc7d2d.png)

不能正确显示和筛选

**期待的正确结果**

希望可以筛选

**Comment by youliyuan-fit2cloud** [comment]
你好，这种情况是不是使用缺陷模板（MeterSphere的默认模板）中“ 状态”字段不是必填项，然后你创建的缺陷没有选择这个字段，创建完成后默认显示这个状态了。
