### ISSUE TITLE
[BUG]Api Test Case中，提示必填后，再次点击“save”按钮页面无反应

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#9128]
**MeterSphere 版本**

1.15.4

**Bug 描述**

添加Api Test Case时，未填写用例名称点击“save”按钮，提示“Please enter the test name”后，填写用例名称再次点击“save”页面无反应。

**Bug 重现步骤**

1. 选择任意接口添加Case  
2. 不填写Case名称，直接点击“save”按钮
3. 提示“Please enter the test name”
4. 填写Case名称，再次点击“save”按钮
5. 页面无反应（前端未报错，未调用后端接口）

**期待的正确结果**

正确保存

**截图**

<img width="1102" alt="wecom-temp-e08ef5856783c8b0ea9aa424387dcce1" src="https://user-images.githubusercontent.com/34698664/148169831-50955877-81ca-417b-ad48-66b5b0870a7b.png">
<img width="1346" alt="wecom-temp-1aed38ebe28031b899dc0363bc891969" src="https://user-images.githubusercontent.com/34698664/148169859-03953991-d1e9-4905-80c8-8aa1c8d7b6ac.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，升级一下？ 最新版本没有这个问题~

**Comment by Saco93** [comment]
1.18.1 确认已修复。
