### ISSUE TITLE
[BUG]接口测试定时执行飞书通知，打开测试报告没内容

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9129]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.2
**Bug 描述**

简要描述您碰到的问题
测试报告没内容，有字段未显示

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/148188194-0c99203e-a64d-4307-9d84-4121acb19629.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，报告没内容 请上传个截图详细说明下吧，
还有上图中的字段 确定是1.16.2版本支持的字段吗？在消息通知模板里有列出支持的变量字段
