### ISSUE TITLE
[BUG]测试跟踪中新建功能用例的前置条件中“< >”无法写入

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9130]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.3
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/148189528-18c6736e-f82e-46c7-a35f-30f877af1487.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，这是把  < 和 > 转义了，保存后显示应该正常的。
