### ISSUE TITLE
[BUG]场景定时任务执行，偶现数据库异常

### ISSUE THREAD

**Issue by JackieShangJie** [metersphere/metersphere#9131]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**
场景定时任务执行，偶现数据库异常
简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/26110332/148192204-d480e66a-64b2-440b-aa04-aee40c354226.png)

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们要花点时间排查一下根本原因
建议升级到较新版本试试看呢，目前最新的版本是v1.16.4了
