### ISSUE TITLE
使用metersphere发送报文指定编码集为GBK，但是通过metersphere发送出来的编码集为UTF-8

### ISSUE THREAD

**Issue by sakdafkasdfhkasd** [metersphere/metersphere#9133]
**MeterSphere 版本**

版本：1.13.1
问题：使用metersphere发送报文指定编码集为GBK，但是通过metersphere发送出来的编码集为UTF-8

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**，能够通过meterspher发送gbk编码集报文。

正确情况下应该是什么样的？

![微信图片_20220105180346](https://user-images.githubusercontent.com/89764725/148199312-6be80915-cf9a-4a64-9782-dc7a06ebe503.png)
![微信图片_20220105180405](https://user-images.githubusercontent.com/89764725/148199320-163617fc-3a4a-4441-b380-929b9d3d29d4.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我们默认的编码是utf-8的，如果您想使用其他编码，可以在前置脚本中转化一下编码格式
