### ISSUE TITLE
[QUESTION]helm 1.0.10版本安装metersphere 启动了两个kafka实例造成冲突

### ISSUE THREAD

**Issue by shiyong1989** [metersphere/metersphere#9136]
1.0.10版本helm安装metersphere

 **describe metersphere-server-bbb689df7-ltklr**             0/1     Init:CrashLoopBackOff   174        14h

Volumes:
  opt-metersphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metersphere-config
    Optional:  false
  metersphere-logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  metersphere-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  metersphere-data-pvc
    ReadOnly:   false
  scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metersphere-scripts
    Optional:  false
  metersphere-token-w289c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metersphere-token-w289c
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                         From     Message
  ----     ------   ----                        ----     -------
  Normal   Pulled   14m (x172 over 14h)         kubelet  Container image "mirror.uat.k8s.com:8989/jt-edu-test/kafka:2" already present on machine
  Warning  BackOff  <invalid> (x4020 over 14h)  kubelet  Back-off restarting failed container

**docker ps -a | grep kafka**

8f4b386341b4   491198851f0c                                                                               "sh -c 'set -ex\nunti…"   14 hours ago         Exited (0) 14 hours ago                                                                                            k8s_wait-kafka_metersphere-node-controller-6c9cb68fd7-lj8cq_default_68184dff-bf7e-4726-95ff-75cf9a6b9480_0
b437ea1934b9   491198851f0c                                                                               "sh -c 'set -ex\nunti…"   15 hours ago         Exited (0) 14 hours ago                                                                                            k8s_wait-kafka_metersphere-data-streaming-75ff6c56f6-f85rb_default_3ecafa59-1d09-44c6-990e-9b6a6cc40f80_0

**启动了两个kafka**

**Comment by liuruibin** [comment]
我们自己测试没有遇到这种情况
