### ISSUE TITLE
[FEATURE]如果接口返回的是一个文件，建议增加另存为文件的功能

### ISSUE THREAD

**Issue by 1067511899** [metersphere/metersphere#9139]
**请描述您的需求或者改进建议.**
问题：我们的一个接口，返回的是一个Excel文件。在metersphere的响应体看到的是乱码，无法通过拷贝或者其他方式，保存成文件。我们使用postman进行这个接口测试的时候，它可以在save response的地方，save to a file。

希望：能够增加一个功能，把响应体直接保存成文件。

**请描述你建议的实现方案**
参考postman，save response 可以 save to a file。
实现方案（建议）：
1、在metersphere的响应内容的响应体那里，在格式选项，增加一个“保存为文件”的选项。
![1](https://user-images.githubusercontent.com/21253207/148323267-a9dc860b-2a1c-430a-ad4c-26acdce506d1.png)
![2](https://user-images.githubusercontent.com/21253207/148323278-8c0e2ab7-8567-4d81-851f-31fa29b8fdd2.png)

谢谢。

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.** 问题：我们的一个接口，返回的是一个Excel文件。在metersphere的响应体看到的是乱码，无法通过拷贝或者其他方式，保存成文件。我们使用postman进行这个接口测试的时候，它可以在save response的地方，save to a file。
> 
> 希望：能够增加一个功能，把响应体直接保存成文件。
> 
> **请描述你建议的实现方案** 参考postman，save response 可以 save to a file。 实现方案（建议）： 1、在metersphere的响应内容的响应体那里，在格式选项，增加一个“保存为文件”的选项。 ![1](https://user-images.githubusercontent.com/21253207/148323267-a9dc860b-2a1c-430a-ad4c-26acdce506d1.png) ![2](https://user-images.githubusercontent.com/21253207/148323278-8c0e2ab7-8567-4d81-851f-31fa29b8fdd2.png)
> 
> 谢谢。

已规划，等待排期
