### ISSUE TITLE
idea导出接口到metersphere会出现部分接口名称中文乱码的情况

### ISSUE THREAD

**Issue by qiuweikangdev** [metersphere/metersphere#9143]
**MeterSphere 版本**

MeterSphere 版本 1.0.3

**Bug 描述**
idea导出接口到metersphere会出现部分接口名称中文乱码的情况

**Bug 重现步骤**

![image](https://user-images.githubusercontent.com/44153172/148379257-e481bd3d-c764-4975-b495-3395b5a3d691.png)

**期待的正确结果**
不出现中文乱码

**截图**

![image](https://user-images.githubusercontent.com/44153172/148379257-e481bd3d-c764-4975-b495-3395b5a3d691.png)

**Comment by zyyfit** [comment]
您好，我们这边没有复现这个问题，您是否使用了其他工具打开或编辑了代码？或者切换过代码编码？您可以在idea里重新编辑保存，然后导入试试

**Comment by zyyfit** [comment]
您好，我们这边最新复现了这个问题，使用这种方式解决了，您可以参考一下

在idea里 ，help->edit custom vmoption -> 增加一行 -Dfile.encoding=UTF-8 再重启 idea，再删掉之前乱码的重新导入
![image](https://user-images.githubusercontent.com/73461316/155045051-51fcd9c2-0736-4c91-accc-6455fa4bdbb6.png)
