### ISSUE TITLE
[FEATURE] 使用禅道的模板，创建缺陷，影响版本不能同步禅道定义的版本

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#9144]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
metersphere：1.16.4
禅道：12.5.3

**Bug 描述**
禅道影响版本字段，只有主干
实际上，禅道上定义了很多个版本

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/7685661/148477836-a1d4f2e8-48af-4d85-a8dd-047763fb088a.png)

**Comment by luty2018** [comment]
加个企业微信 我们远程帮你看看
