### ISSUE TITLE
[FEATURE]希望支持消息通知Jenkins消息配置，区分项目权限配置

### ISSUE THREAD

**Issue by fangqiuhong** [metersphere/metersphere#9145]
**请描述您的需求或者改进建议.**
希望支持消息通知Jenkins消息配置，区分项目权限配置，不同的项目，Jenkins运行结束后，推送到不同的钉钉群

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
已排期 消息配置会放到项目级别
