### ISSUE TITLE
[BUG] jmeter 文件处理有逻辑问题

### ISSUE THREAD

**Issue by Y4er** [metersphere/metersphere#9146]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.4

**Bug 描述**

简要描述您碰到的问题

在`io.metersphere.api.controller.ApiJmeterFileController#downloadBodyFiles`中downloadJmeterFiles函数在处理文件时进入`io.metersphere.api.service.ApiJmeterFileService#getMultipartFiles(java.util.List<io.metersphere.api.dto.scenario.request.BodyFile>)`函数

![image](https://user-images.githubusercontent.com/40487319/148506604-ede3956c-2cf2-4f68-9ac2-c7b70465178f.png)

其中`if (file != null && !file.exists())` 该if判断和`FileUtils.fileToByte(file)`中的代码逻辑不符

![image](https://user-images.githubusercontent.com/40487319/148506689-45273031-738f-4c0e-a3a6-c7a05180b13f.png)

如果满足`!file.exists()`会导致`new FileInputStream(tradeFile)`报错抛出异常

**期待的正确结果**

正确情况下应该是什么样的？

if条件应修改为`if (file != null && file.exists())`

**Comment by fit2-zhao** [comment]
@Y4er 感谢，后续版本会修复此处逻辑问题。

**Comment by zyyfit** [comment]
1.17.0已修复
