### ISSUE TITLE
[BUG]循环读取csv变量，读取csv文件里的值，都是重复的，并且不是逐条读取

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9147]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1. 循环读取csv变量，读取csv文件里的值，都是重复的，并且不是逐条读取
2. 清除缓存后，执行第一次正常了，再执行一次结果又异常了。
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/148543696-62d1b5d0-331c-4e1c-a2a4-7e35654d63f1.png)
![image](https://user-images.githubusercontent.com/78218624/148544125-97521974-dd4c-49c0-a043-ef72ef555224.png)

![image](https://user-images.githubusercontent.com/78218624/148543626-263ef888-dbf6-43f9-9803-0441a15ab586.png)
![image](https://user-images.githubusercontent.com/78218624/148543914-506f2338-35bd-4a54-8036-d8b57556f29e.png)
![image](https://user-images.githubusercontent.com/78218624/148544036-6144635c-ba7b-43d8-ba9d-147eb042ae21.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
同 https://github.com/metersphere/metersphere/issues/9149

**Comment by zyyfit** [comment]
重复问题保留一个
