### ISSUE TITLE
[BUG] 接口自动化脚本，添加了循环，点击多次“调试”、“调试生成报告”，系统报告为空白，显示未执行，打开日志发现有错误日志。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9148]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.3

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  [BUG] 接口自动化脚本，添加了循环，点击多次“调试”、“调试生成报告”，系统报告为空白，显示未执行，打开日志发现有错误日志。
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/148545808-5440927c-d2b5-41be-935d-f230fb447fac.png)
![image](https://user-images.githubusercontent.com/78218624/148545954-9c268cd4-09e7-498e-b273-5ac7e135bbe0.png)
![image](https://user-images.githubusercontent.com/78218624/148546033-50c6c70b-8b98-455a-8d65-3b9960c9e9f9.png)
![image](https://user-images.githubusercontent.com/78218624/148546167-f3c29076-19f9-4b9d-801d-a6ba8d8b210d.png)

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复这个问题

**Comment by youliyuan-fit2cloud** [comment]
1.16.6以上版本没有复现这个问题了，升级一下吧
