### ISSUE TITLE
[BUG]while循环读取CSV文件，只有第一次循环取值正常，之后的循环取值都是错误的，都是while条件中设置的值

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9149]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  while循环读取CSV文件，只有第一次循环取值正常，之后的循环取值都是错误的，都是while条件中设置的值
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/148547253-df364d38-39f4-4024-960f-82ff5955f070.png)
![image](https://user-images.githubusercontent.com/78218624/148547311-b7bab171-c75b-479f-9c14-c02b93bd386a.png)
![image](https://user-images.githubusercontent.com/78218624/148547657-1b1a9f2c-f33e-48c9-ad21-568e5492708e.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
这个问题暂时不好处理，是因为我们之前设计的csv文件放的位置影响了他的取值，暂时计划在1.18版本解决
