### ISSUE TITLE
[缺陷管理]跑测试用例时，关联缺陷，希望增加搜索功能

### ISSUE THREAD

**Issue by chenlq618** [metersphere/metersphere#9150]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/7685661/148627424-55bc70c7-b97d-4058-8193-1ca92f9ae4ea.png)

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
> **请描述您的需求或者改进建议.**
> 
> ![image](https://user-images.githubusercontent.com/7685661/148627424-55bc70c7-b97d-4058-8193-1ca92f9ae4ea.png)
> 
> **请描述你建议的实现方案**

已规划，等待排期
