### ISSUE TITLE
[BUG] 权限设置项目成员不允许修改测试用例的情况下，用例状态，责任人，等级，都可以修改，而且页面输入 Ctrl + S 还能保存用例

### ISSUE THREAD

**Issue by liuqiao1995** [metersphere/metersphere#9151]
**MeterSphere 版本**

1.16.0

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  设置项目成员只能查看用例，不能修改，编辑，新增用例
2.  用项目成员账号登录
3.  用例状态，责任人，等级，都可以修改，而且页面输入 Ctrl + S 还能保存用例
4. 

**期待的正确结果**

正确的话，应该无论如何，都不能修改测试用例

**截图**

![I9gbrC0SvF](https://user-images.githubusercontent.com/22763910/148638209-1a33a670-4f15-4aa5-a901-5c4f2e31732c.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复
