### ISSUE TITLE
[BUG]数据库内存在慢SQL急需优化

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9154]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.7
**Bug 描述**

简要描述您碰到的问题
数据库内部存在慢SQL，具体SQL如下：​
​​SELECT r.name AS test_name,r.end_time,        r.name, r.description, r.id, r.project_id, r.create_time, r.update_time, r.status, r.trigger_mode,IfNULL(s.name,r.scenario_name) as scenario_name,        project.name AS project_name, user.name AS user_name        FROM api_scenario_report r        LEFT JOIN api_scenario s on r.scenario_id = s.id        LEFT JOIN project ON project.id = r.project_id        LEFT JOIN user ON user.id = r.user_id         WHERE  project.id = '8359b209-cf33-11eb-a483-0242ac130005'            AND r.execute_type = 'Saved'             order by                   r.update_time desc LIMIT 669100,100;
数据库负载很高，每分钟执行该SQL语句27次，平均每次耗时7秒
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我测试了一下这个sql查询时间应该没有这么慢，可能是因为你数据量比较多的原因，我们先排查一下问题

**Comment by zyyfit** [comment]
1.16.5已优化
