### ISSUE TITLE
[BUG]接口自动化复制case之后保存失败并抛出异常

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9155]
**MeterSphere 版本**
V1.16.4

**Bug 描述**

接口自动化复制case之后保存失败并抛出异常

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/32027713/148714276-3ffdf769-f42a-4cf5-820c-9e8ca5684039.png)

![image](https://user-images.githubusercontent.com/32027713/148710962-a12f2085-e0fc-427c-8bec-b9a1cbf42690.png)

![image](https://user-images.githubusercontent.com/32027713/148710982-551b03a2-0d62-46c0-aa93-343faa5a56e5.png)

![image](https://user-images.githubusercontent.com/32027713/148711014-d021db09-f200-453b-926f-93320d1d3be5.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，复制其他case报错吗？如果是复制每个case都报错的话，麻烦您上传一下这个场景我们看看，如果是复制特定的case报错的话，麻烦您把case所在的接口导出ms格式给我们看看

**Comment by zyyfit** [comment]
已经修复了这个问题，下个版本发布

**Comment by youliyuan-fit2cloud** [comment]
V1.16.5已修复
