### ISSUE TITLE
[BUG]引用场景变量出错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9158]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.2
**Bug 描述**

简要描述您碰到的问题
一个场景中包含多个场景，多个场景中有同名变量，执行时变量取值是第一个场景的值而不是 引用场景的变量值
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
已知遗留问题，暂时不好处理

**Comment by zyyfit** [comment]
计划1.18版本处理这个问题
