### ISSUE TITLE
[BUG]接口用例添加前置sql，无响应内容

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9160]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.2
**Bug 描述**

简要描述您碰到的问题
接口case中加了一个前置SQL，执行后发现SQL已经成功修改到数据库了，但是MS的界面上提示操作成功,但是响应内容一直没结果
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，1.16.4没有复现这个问题，请升级到最新版试试
