### ISSUE TITLE
[BUG]测试计划报告批量删除功能bug

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9167]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.14.6
**Bug 描述**

简要描述您碰到的问题
使用高级搜索时，按照日期搜索出报告列表，批量选择报告列表中的报告后，点击批量删除时会将所有的报告全部删除
**Bug 重现步骤**

1.  高级搜索按照日期搜索
2. 批量选择报告
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
删除选中的报告
**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
