### ISSUE TITLE
导入JMX脚本进行接口自动化测试无法使用场景变量自定义变量常量[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#9171]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4
**Bug 描述**
1、在接口场景自动化中导入JMX脚本
2、把依赖的CSV文件上传到/opt/metersphere/data/body目录
![image](https://user-images.githubusercontent.com/35896106/148722622-754206e0-e060-4801-9703-e14d2448b0cb.png)

3、场景变量中设置自定义变量
![image](https://user-images.githubusercontent.com/35896106/148722757-8fd006db-834e-41e4-8ebc-9a71046e18a7.png)

4、修改CSV Data Set Config中路径为
![image](https://user-images.githubusercontent.com/35896106/148722735-4398d179-f9b9-4325-91bf-3313ab7aa5e5.png)

5、执行报错csv文件找不到
![image](https://user-images.githubusercontent.com/35896106/148722843-ad0706fd-dcda-4b96-8bb7-ffa9751db383.png)

**期待的正确结果**

之前版本是可以的，试了1.16.2和1.16.4都不行了

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，由于我们目前的机制是jmx里的csv文件和环境变量同时解析，所以csv文件中的变量存在解析不出来的情况，
您可直接使用绝对路径，
也可以直接将csv文件上传到这个场景的场景变量中，保持场景里引用的csv文件和场景变量里的csv文件名称一致，就可以被引用到（我们会自动识别的，路径不需要修改）
