### ISSUE TITLE
[BUG]选择【运行环境】直接报接口异常，导致无法运行接口自动化。有截图。

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#9173]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

  v1.16.3-5a4ca0db

**Bug 描述**

在接口自动化中，进入一个场景接口，选择【运行环境】，直接报错（network error），接口也报错。

无法加载【环境列表】，一直在打转转。。。

![接口报错](https://user-images.githubusercontent.com/6467295/148729890-650d40a3-3e59-42e0-b602-354fa817c7b3.jpg)

日志错误：
![日志错误](https://user-images.githubusercontent.com/6467295/148730191-9d3f0c33-18a0-45eb-a1d9-a07dba137e79.jpg)
![日志错误2](https://user-images.githubusercontent.com/6467295/148730181-2feae1fb-fdef-4cc9-ae96-d2b53cdf2036.jpg)

**Comment by zyyfit** [comment]
您好，我们没有复现这个问题，请问是每个场景都会报错吗？方便把报错的场景和这个项目下的环境列表到出来给我们看看吗

**Comment by zyyfit** [comment]
您好，我们没有复现这个问题，请问是每个场景都会报错吗？方便把报错的场景和这个项目下的环境列表到出来给我们看看吗
