### ISSUE TITLE
[BUG]【对接jira】创建jira缺陷时，ms系统里面的描述字段粘贴图片，但jira系统没有展示图片出来

### ISSUE THREAD

**Issue by hefeixiao** [metersphere/metersphere#9176]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4

**Bug 描述**

建jira缺陷时，上传图片到ms系统，但jira系统没有展示图片出来

简要描述您碰到的问题

建jira缺陷时，上传图片到ms系统，但jira系统没有展示图片出来

**Bug 重现步骤**

1.  测试跟踪-缺陷管理-创建缺陷，描述字段，粘贴缺陷截图
![6a33e9c71ea0704c9a0dc4d77caa70c](https://user-images.githubusercontent.com/59219621/148737979-d0800a30-dec2-4911-8ff9-66b044fa9856.png)

2. 查看jira的缺陷内容，描述栏里面没有图片，而是这样：
![647f3808c8cc48271b8562646d39a40](https://user-images.githubusercontent.com/59219621/148738044-1d5986bc-4072-4b15-82da-fd1e227477cb.png)

**期待的正确结果**

正确情况下应该是什么样的？
跟ms平台的预览一样，在jira 的描述字段能正常预览截图

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复

**Comment by hefeixiao** [comment]
问题并没有解决。然后我看了源码，创建缺陷时，描述字段，直接把图片删了（removeImg），然后使用jira的上传附件接口单独上传附件，这样的话，描述字段仍然是文字，附件是附件，不能对应起来，如果直接在jira提单，效果，应该如下：
描述里面有附件的缩略图：

![image](https://user-images.githubusercontent.com/59219621/153363553-c99ba9d8-d27f-4312-9b24-31d821df7d56.png)
