### ISSUE TITLE
[BUG]接口自动化在调试的时候，状态显示有问题

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9177]
**MeterSphere 版本**

V1.16.4

**Bug 描述**

简要描述您碰到的问题
接口自动化在调试的时候，状态显示有问题 ，明明所有请求都成功了，循环下面接口的状态显示为error

**截图**

如果有截图，请附上截图.
![调试01](https://user-images.githubusercontent.com/32027713/148740508-553d31ad-d1ee-4acb-9fb4-ac7b8cadaf07.gif)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本已修复~
