### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wx-collab** [metersphere/metersphere#918]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是 v1.5.0-b1192

在用列评审过程中勾选了其中一条之后点击打开，打开的页面不是显示所勾选的案列评审
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

我勾选的是那个要评审的就应该打开是那个用例评审
正确情况下应该是什么样的？

**截图**

![微信图片_20201210095807](https://user-images.githubusercontent.com/75721076/101711313-4e85d600-3ace-11eb-878d-4565189ec2b0.png)
![微信图片_20201210095818](https://user-images.githubusercontent.com/75721076/101711318-504f9980-3ace-11eb-97a1-3ea3da6617b7.png)
![微信图片_20201210095824](https://user-images.githubusercontent.com/75721076/101711320-50e83000-3ace-11eb-81ea-01b2a407b53d.png)

**Comment by wangzhen-fit2cloud** [comment]
勾选是进行批量操作的，点击展示的内容与点击那一条有关，与勾选了哪一条无关
