### ISSUE TITLE
[BUG]api_scenario_report_result 出现慢查询，请给 report_id 加个索引

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9190]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/30038088/148763590-f268226c-72e9-48e0-860f-2f23ada200e9.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by shenkaibo** [comment]
@AgAngle

**Comment by zyyfit** [comment]
感谢反馈，我们先内部讨论一下解决方案，相关问题 
https://github.com/metersphere/metersphere/issues/9154

**Comment by shenkaibo** [comment]
这个在客户环境给report_id加了索引，好使

**Comment by zyyfit** [comment]
> 这个在客户环境给report_id加了索引，好使

收到，已经加上了，下个版本更新

**Comment by zyyfit** [comment]
1.16.5已优化
