### ISSUE TITLE
[BUG]所在项目集成有禅道，并设置为禅道缺陷模板的情况下，更改集成平台为metersphere并设置缺陷模板为default时，查看缺陷模板仍报错为集成禅道时的url无法访问，请定位并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9193]
**MeterSphere 版本**

v1.16.4-07155cf8

**Bug 描述**

所在项目集成有禅道，并设置为禅道缺陷模板的情况下，更改集成平台为metersphere并设置缺陷模板为default时，查看缺陷模板仍报错为集成禅道时的url无法访问，请定位并修改

**截图**
![ecdcc518f460ad70a3bc44a908d0193](https://user-images.githubusercontent.com/92150453/148869194-95b8f798-a853-4301-bff8-c1974a2d4737.png)
![384620e69459ac0bca2f8f7976fe8b2](https://user-images.githubusercontent.com/92150453/148869233-6997d993-9d0b-4510-ad45-e6dc1736c47a.png)
![f75ccfc08fb6dd0101b16415f5a19ab](https://user-images.githubusercontent.com/92150453/148869241-3c6ddb59-7faf-456d-a74f-023f5d94c0dc.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，是必现的吗？有没有集成其他平台呢？禅道缺陷模板有没有配置自定义字段呀？
