### ISSUE TITLE
[BUG]Jenkins 直接跳转到测试计划报告链接，目前只能跳转到 测试计划报告列表

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9196]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.4
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by luty2018** [comment]
已转需求处理

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 
> 您所使用的 MeterSphere 版本是？ v1.16.4 **Bug 描述**
> 
> 简要描述您碰到的问题
> 
> **Bug 重现步骤**
> 
> 
> **期待的正确结果**
> 
> 正确情况下应该是什么样的？
> 
> **截图**
> 
> 如果有截图，请附上截图.

1.18

**Comment by luty2018** [comment]
![image](https://user-images.githubusercontent.com/36292514/148896321-bf8ccb91-9b87-4bd9-ac29-22e326c3d66e.png)
