### ISSUE TITLE
[FEATURE]Jenkins插件支持选择环境

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9206]
**MeterSphere 版本**
v1.16.4
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by luty2018** [comment]
已反馈 待排期
