### ISSUE TITLE
[BUG]取消集成禅道后，更改项目集成平台为MeterSphere，缺陷模板为default后，查看缺陷管理页面报错提示：配置为空，且原有metersphere平台缺陷被清空，功能实现异常，请定位并修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9209]
**MeterSphere 版本**

v1.16.4-07155cf8

**Bug 描述**

取消集成禅道后，更改项目集成平台为MeterSphere，缺陷模板为default后，查看缺陷管理页面报错提示：配置为空，且原有metersphere平台缺陷被清空，功能实现异常，请定位并修改

**截图**
![ec48dcf0f8d1d2e08da73814823aac0](https://user-images.githubusercontent.com/92150453/148888838-52088eb7-3afe-4f70-b95c-12eecd1f65fe.jpg)
![dc6a2aaf0a66ef6776f02938dfe8d73](https://user-images.githubusercontent.com/92150453/148888872-d49686d1-a00a-44e8-a5d9-16dd931eefe3.jpg)
![009c04f5cef8f5dc16a70f690c74a54](https://user-images.githubusercontent.com/92150453/148888882-3712ff17-d5b3-4df9-aa3c-a8bdbdeb7e08.jpg)

**Comment by zyyfit** [comment]
重复问题 https://github.com/metersphere/metersphere/issues/9193
