### ISSUE TITLE
[BUG]导入metersphere格式的接口场景用例时，再次编辑无法选择运行环境，导致用例无法执行，请修复

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9212]
**MeterSphere 版本**

v1.16.4-07155cf8

**Bug 描述**

导入metersphere格式的接口场景用例时，再次编辑无法选择运行环境，导致用例无法执行，请修复

**截图**
![269cf1d885074c7590a2f5c9c1a64ba](https://user-images.githubusercontent.com/92150453/148889443-aea0108d-74a5-4fa2-9563-48fd8e8d440b.png)
![image](https://user-images.githubusercontent.com/92150453/148889454-013374e6-007f-4d9e-833e-0f556e36f27d.png)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，方便把您的场景上传一下给我们看看吗

**Comment by sageonedream** [comment]
问题出现时，已联系李玉号远程定位



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月11日(周二) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [metersphere/metersphere] [BUG]导入metersphere格式的接口场景用例时，再次编辑无法选择运行环境，导致用例无法执行，请修复 (Issue #9212)




 
您好，没有复现这个问题，方便把您的场景上传一下给我们看看吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5版本已修复该问题
