### ISSUE TITLE
[BUG]Azure Devops 创建缺陷报错

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9213]
**MeterSphere 版本**
v1.16.4

![1301641881830_ pic_hd](https://user-images.githubusercontent.com/30038088/148891143-cdb51bfe-b6aa-49c1-a183-5addba9a177b.jpg)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我这边没有复现这个问题，看起来像是模版有字段没按azure的要求填写？

**Comment by shenkaibo** [comment]
刷模版导致，已解决
