### ISSUE TITLE
[BUG]jira 使用 同步的缺陷模版，有自定义字段，里边有值，但是仍提示 必填

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9214]
**MeterSphere 版本**
V1.16.4
您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，如果是必现的话请详细描述一下操作步骤
