### ISSUE TITLE
[BUG]报表统计模块-项目报表-测试用例统计，使用创建人字段筛选，切换到饼状图时，图形展示不全，且创建人员与筛选条件不一致。

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#9215]
**MeterSphere 版本1.16.4**

您所使用的 MeterSphere 版本是？

**报表统计模块-项目报表-测试用例统计，使用创建人字段筛选，切换到饼状图时，图形展示不全，且创建人员与筛选条件不一致。**

简要描述您碰到的问题

**Bug 重现步骤**

1. 水平轴选择“创建人”字段
2. 默认选择柱状图，点击确定按钮，查询后切换成饼状图查询
3. 设置更多选项，选择一个创建人
4. 再次点击确定按钮查询
**期待的正确结果**

正确情况下应该是什么样的？
正确结果应该：1. 应该只显示我筛选的创建人的数据，但是现在同时还显示了其他账号的数据
                          2. 饼状图应显示完整，现在显示不完整，需要再次点击才能执行正确
**
![image](https://user-images.githubusercontent.com/77324661/148892752-04ee0615-7211-4c76-bd5a-b33f704d8f26.png)
**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
