### ISSUE TITLE
[BUG]创建人会自动修改

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9217]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.16.4
**Bug 描述**

简要描述您碰到的问题
所有创建的用例（功能、接口、接口用例、场景用例等有创建人列的数据）等内容被别的用户修改后创建人会变为新修改的用户而不是最开始创建用例的人
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，只有场景用例复现了，其他用例都没有复现，其他用例是必现的吗？是需要修改特定的字段才会变更创建人吗？

**Comment by happyend1709** [comment]
> 您好，只有场景用例复现了，其他用例都没有复现，其他用例是必现的吗？是需要修改特定的字段才会变更创建人吗？

创建的项目也会这样

**Comment by zyyfit** [comment]
> > 您好，只有场景用例复现了，其他用例都没有复现，其他用例是必现的吗？是需要修改特定的字段才会变更创建人吗？
> 
> 创建的项目也会这样

收到

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5已修复该问题~
