### ISSUE TITLE
【BUG】场景A引用场景B，如果场景B用例有修改，执行场景A还是旧的场景B，需要重新编辑保存一次场景A才可以

### ISSUE THREAD

**Issue by SloanGao** [metersphere/metersphere#9235]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
   V1.14.3

**Bug 描述**
    场景A引用场景B，如果场景B用例有修改，执行场景A还是旧的场景B，需要重新编辑保存一次场景A才可以

**Bug 重现步骤**
1.  場景A引用場景B
2.  修改場景B
3.  執行場景A

**期待的正确结果**
  執行結果正常，實際執行結果失敗，場景A裡面引用的仍是舊的場景B，需要重新編輯 並保存場景A，才會更新引用的場景B

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，最新版1.16.4没有复现这个问题，建议您升级到最新版使用

**Comment by SloanGao** [comment]
好的，謝謝
