### ISSUE TITLE
[BUG]接口测试-接口自动化-回收站：有一个自动化场景删不掉，其他的都能删掉

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#9259]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.4
**Bug 描述**

简要描述您碰到的问题
有一个自动化场景删不掉，其他的都能删掉
**Bug 重现步骤**

1.  删除接口自动化回收站的场景
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![80906050c3b4592eecb0fb41c44eebb](https://user-images.githubusercontent.com/97216833/149049216-b010796b-da82-494f-b079-57225fa779a4.png)

**Comment by youliyuan-fit2cloud** [comment]
请发一下log日志信息吧
