### ISSUE TITLE
[FEATURE]消息邮件通知优化3点

### ISSUE THREAD

**Issue by yicuiping** [metersphere/metersphere#926]
**请描述您的需求或者改进建议.**

1、邮件事件区分了成功失败，邮件标题最好区分下成功还是失败的，否则需要点击邮件内容的报告链接才清楚
2、邮件内容能不能完善一下，最起码说一下执行的数量情况，失败多少条，成功多少条等等，具体的执行情况可以点击报告链接查看
3、邮件事件现在只能选择失败、成功之一，可以改为多选吗，因为我们不关心失败还是成功的事件，我们是想看到所有接口的执行结果

**请描述你建议的实现方案**

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，后续考虑优化这部分功能，请持续关注！
