### ISSUE TITLE
用户组-【查看接口】 权限控制异常

### ISSUE THREAD

**Issue by fitcloud-zaopengguo** [metersphere/metersphere#9264]
**MeterSphere 版本**

MeterSphere 版本是1.16.4

**Bug 描述**

1、新建一个用户组， 只配置查看接口的权限
![1641955370(1)](https://user-images.githubusercontent.com/30264974/149054550-f1f153df-3699-4036-9b75-0b377934a233.jpg)

2、新建用户，配置这个用户组

3、 登陆用户， 可以看到在调试接口-环境选择-环境设置，可以对全局前置脚本、全局后置脚本、认证设置、TCP 设置， 能够进行修改。 这个跟权限控制的不符合。

<img width="863" alt="1" src="https://user-images.githubusercontent.com/30264974/149055058-ceaa5fce-efb2-448f-8276-4663084d97bb.png">
<img width="749" alt="2" src="https://user-images.githubusercontent.com/30264974/149055082-8e18ed15-b3c3-4748-9141-c6e05fee1ae4.png">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
