### ISSUE TITLE
[BUG]Test Plan的Scheduled Task的Task Notification配置为Mail时，未收到对应邮件

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#9267]
**MeterSphere 版本**

1.15.4

**Bug 描述**

Test Plan的Scheduled Task的Task Notification配置为Mail时，未收到对应邮件。

**Bug 重现步骤**

1.  为Test Plan A配置Scheduled Task
2. 配置Task notification中Receiver为Saco、mailbox为mail
3. 配置Saco的邮箱为sacosmailbox@mailserver.com
4. 待Scheduled Task执行后，查看sacosmailbox@mailserver.com
5. 未收到邮件

**期待的正确结果**

能够在sacosmailbox@mailserver.com中收到Scheduled Task 的执行邮件

**截图**

<img width="1425" alt="wecom-temp-fc44ccd54bf23741d869d1a2df11d9cd" src="https://user-images.githubusercontent.com/34698664/149058624-49046168-cdad-4c6a-a5f0-0f624b9081d8.png">

**Comment by youliyuan-fit2cloud** [comment]
你好，我这边没复现呢。。
![image](https://user-images.githubusercontent.com/54612864/149098646-7a8a5477-417a-4e5e-a464-7c983a074292.png)

**Comment by youliyuan-fit2cloud** [comment]
1.系统参数设置-邮件设置-测试连接是否成功？
2.任务通知的用户 对应的个人信息里面的邮箱地址信息是否填写正确

**Comment by Saco93** [comment]
> 1.系统参数设置-邮件设置-测试连接是否成功？ 2.任务通知的用户 对应的个人信息里面的邮箱地址信息是否填写正确

是我这边系统参数设置问题，已经配置好了，谢谢！
