### ISSUE TITLE
[BUG]创建接口GET请求参数不能正确显示在QUERY区域

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9268]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.4

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  复制接口地址/getControlAndDispatchLog?stationId=&stationBranchId=&controlMode=&logType=&pageIndex=1&pageSize=20&sortName=&sortType=&beginDate=2022-01-09&endDate=2022-01-12
2. 粘贴到GET请求
3.查看QUERY参数区域
结果：
pageIndex=1参数类型可以正确显示在QUERY参数区域，这种的logType=不显示

**期待的正确结果**

正确将浏览器参数全部自动显示在QUERY区域

**截图**

![image](https://user-images.githubusercontent.com/19423100/149062767-db03a896-e525-4b23-b55b-b32549400b6d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们下版本修复这个问题

**Comment by youliyuan-fit2cloud** [comment]
v1.16.5已修复该问题~
