### ISSUE TITLE
[FEATURE]接口测试在认证配置模块选择认证方式为Basic Auth时，建议增加用户名、密码填写提示，且为空时进行弹窗提示

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9278]
**MeterSphere 版本**

v1.16.4-07155cf8

**Bug 描述**

接口测试在认证配置模块选择认证方式为Basic Auth时，建议增加用户名、密码填写提示，且为空时进行弹窗提示

**截图**
![image](https://user-images.githubusercontent.com/92150453/149090098-1345786b-490e-4867-9e2e-ecda14fbd81a.png)

**Comment by luty2018** [comment]
已排期
