### ISSUE TITLE
[BUG]在用户进行过编辑接口、接口用例、接口自动化用例操作，且未保存的情况下，点击关闭按钮时，建议新增弹窗提示

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9279]
**MeterSphere 版本**

v1.16.4-07155cf8

**Bug 描述**

在用户进行过编辑接口、接口用例、接口自动化用例操作，且未保存的情况下，点击关闭按钮时，建议新增弹窗提示

**截图**
![image](https://user-images.githubusercontent.com/92150453/149091799-11b5f301-6e83-4670-9b04-79c38755a8ab.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，我们编辑的时候未保存关闭会弹窗提示的，你的环境没有提示？
新创建的接口 未保存关闭 不支持弹窗提示，你是不是新创建的？
![image](https://user-images.githubusercontent.com/54612864/149099537-fa76b067-2ecb-4575-bd6d-cca705f63fd7.png)

**Comment by sageonedream** [comment]
已实现
