### ISSUE TITLE
针对接口响应提取

### ISSUE THREAD

**Issue by zhouping-zp** [metersphere/metersphere#9281]
**请描述您的需求或者改进建议.**
在使用的过程中有用到正则响应提取，结果发现没有说明文档或操作手册，一直无法提取参数。

**请描述你建议的实现方案**
操作方面：可以有一个响应提取的小窗口  快捷看是否提取成功
用户体验/用户交互： 这种操作旁边可以有一个帮助文档的按钮

**Comment by luty2018** [comment]
这个正则就是通用标准的正则呢 可以自己百度的哈
