### ISSUE TITLE
接口测试失败

### ISSUE THREAD

**Issue by orjuly** [metersphere/metersphere#9287]
按照部署教程执行完之后，接口测试失败
![image](https://user-images.githubusercontent.com/3078164/149118170-9e33165e-364a-4ee9-9113-fe959e2b7553.png)

**Comment by youliyuan-fit2cloud** [comment]
请求地址不对

**Comment by orjuly** [comment]
测试baidu不成功，docker的网段需要单独配置吗？
![image](https://user-images.githubusercontent.com/3078164/149122653-7f02c32e-cb27-4477-b868-e4d85277690f.png)
