### ISSUE TITLE
[FEATURE]测试结果中显示各个模块通过、失败、阻塞、跳过用例的具体数量；

### ISSUE THREAD

**Issue by xmyemail** [metersphere/metersphere#93]
**MeterSphere 版本**
v1.0.2-b357

**Bug 描述**
测试结果中不能显示各个模块通过、失败、阻塞、跳过、未执行用例的具体数量；

**Bug 重现步骤**
1.  测试计划->查看测试报告->测试结果；

**期待的正确结果**
测试结果统计中显示通过率的同时，也分别显示各个模块通过、失败、阻塞、跳过、未执行用例的具体数量；

**截图**

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
