### ISSUE TITLE
[BUG]get请求==自定义query区域第一个参数会默认必填

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9301]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.4

**Bug 描述**
get请求自定义query第一个参数会默认必填

**Bug 重现步骤**

1、创建接口
2、get请求浏览器传参 /findss?lat=31.835171978102156&lng=117.23738099999993&distance=2000000
3、查看QUERY区域，参数显示正常
4、新增一个参数 new,默认必填
5、再新增一个参数fd，无默认值

**期待的正确结果**

新增的参数应该都是默认空白，至少一致性，不应该第一个默认必填，后面的都是空白

**截图**

![image](https://user-images.githubusercontent.com/19423100/149248097-b2144b2c-39c3-43ad-91e1-884f9379e5eb.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
