### ISSUE TITLE
[BUG]添加接口用例会弹出两个相同提示语

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9304]
**MeterSphere 版本**
1.16.4

**Bug 描述**

加接口用例会弹出两个相同提示语【保存成功】

**Bug 重现步骤**

1.  接口测试-接口定义-创建接口
2. 输入正确接口api保存成功
3. 点击case-点击添加--输入接口用例名称
4. 点击保存，结果中间提示语出现2个成功提示弹出框【保存成功】

**期待的正确结果**

只有一个正常提示语

**截图**

![image](https://user-images.githubusercontent.com/19423100/149252581-226becf1-46de-46bb-a743-4a0e9649874c.png)

**Comment by zyyfit** [comment]
您好，我们之前修复过这个问题，目前没有复现，您那边是必现的吗？如果是的话麻烦截图一下浏览器的开发者工具里，保存时发送的请求

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/149311334-96d64943-1b93-4940-bec7-07b30d7bda55.png)
需要你多试几次就会出现

**Comment by legend818** [comment]
> **MeterSphere 版本** 1.16.4
> 
> **Bug 描述**
> 
> 加接口用例会弹出两个相同提示语【保存成功】
> 
> **Bug 重现步骤**
> 
> 1. 接口测试-接口定义-创建接口
> 2. 输入正确接口api保存成功
> 3. 点击case-点击添加--输入接口用例名称
> 4. 点击保存，结果中间提示语出现2个成功提示弹出框【保存成功】
> 
> **期待的正确结果**
> 
> 只有一个正常提示语
> 
> **截图**
> 
> ![image](https://user-images.githubusercontent.com/19423100/149252581-226becf1-46de-46bb-a743-4a0e9649874c.png)

![image](https://user-images.githubusercontent.com/19423100/149312586-5d689fd4-563a-4e4d-9bde-8bf2855ab22b.png)多试几次

**Comment by zyyfit** [comment]
您方便看一下开发者工具里的请求吗？看看是不是一个create接口和一个update接口，如果点击保存点的快的话，是会保存后再进行一次更新的，这是正常的

**Comment by legend818** [comment]
> **MeterSphere 版本** 1.16.4
> 
> **Bug 描述**
> 
> 加接口用例会弹出两个相同提示语【保存成功】
> 
> **Bug 重现步骤**
> 
> 1. 接口测试-接口定义-创建接口
> 2. 输入正确接口api保存成功
> 3. 点击case-点击添加--输入接口用例名称
> 4. 点击保存，结果中间提示语出现2个成功提示弹出框【保存成功】
> 
> **期待的正确结果**
> 
> 只有一个正常提示语
> 
> **截图**
> 
> ![image](https://user-images.githubusercontent.com/19423100/149252581-226becf1-46de-46bb-a743-4a0e9649874c.png)
这个是你说的tan弹两个出现的。但是他不是每次都会有update
这个是只有一个弹窗的
![image](https://user-images.githubusercontent.com/19423100/149439415-b0323d9e-ab9d-419a-be80-dbfb36c1faa1.png)

**Comment by legend818** [comment]
补弹出两个提示语的图
![image](https://user-images.githubusercontent.com/19423100/149439489-1cec2b63-f591-4896-90ba-25b2e3c79fab.png)

**Comment by zyyfit** [comment]
收到

**Comment by zyyfit** [comment]
1.17.0已修复
