### ISSUE TITLE
[BUG] 性能测试，并发用户上去之后，会抛出大量的Non HTTP response code: java.net.ConnectException

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#931]
**MeterSphere 版本**
v1.5.1

**Bug 描述**
同样的用例，用原生的jmeter直接跑一点问题没有（linux参数都调好了），用metersphere跑，好多报错

**Bug 重现步骤**
执行性能测试 , 用户超过100，时间超过5分钟。

**期待的正确结果**
与jmeter测试结果保持一致

**截图**
![image](https://user-images.githubusercontent.com/44999044/102050913-a437e680-3e1e-11eb-8849-4a8e4896dd51.png)

**Comment by LimonFHM** [comment]
http实现使用的是 java，如果用httpclient4，是另外一种同类型的错。

**Comment by liuruibin** [comment]
我们使用的线程组bzm - Concurrency Thread Group进行性能测试，这个线程组和jmeter原版线程组在相同配置下执行有差异，你可以自行测试对比
