### ISSUE TITLE
[BUG]接收不到邮件

### ISSUE THREAD

**Issue by chujidiy** [metersphere/metersphere#933]
**MeterSphere 版本**
1.5.0

**Bug 描述**
接收不到邮件

**Bug 重现步骤**
1，系统设置-邮件设置-填写邮箱相关信息
2，点击测试连接，提示连接成功
3，系统设置-消息设置-Jenkins接口调用任务通知 中增加失败和成功的邮件接收人员

**期待的正确结果**
jenkins 插件启动的测试执行后，会发送到相关人员

**Comment by wangzhen-fit2cloud** [comment]
你好，请问使用的是非 SSL 的邮箱服务器吗？

**Comment by wangzhen-fit2cloud** [comment]
非 SSL 邮箱服务器目前存在问题，将在 1.6.0 版本解决

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
