### ISSUE TITLE
[FEATURE]版本: v1.5-0abd7209，ui排版建议

### ISSUE THREAD

**Issue by barbie-workhard** [metersphere/metersphere#934]
**请描述您的需求或者改进建议.**

查看接口测试报告，左侧是所有跑完的接口列表，有时候接口很多，需要下拉很长去找一个接口，然后点击该接口查看详情，右边的详情显示在最顶端。又得上拉很长去查看详情，操作不方便。

**请描述你建议的实现方案**
将左侧接口列表设置成滚动，顶部和右侧接口详情窗口设置为固定，不随着接口列表滚动。

**Comment by barbie-workhard** [comment]
接口测试报告中，点击列表中的某一个接口，请让接口颜色变重或加上背景色，表示定位到这个接口了。

**Comment by wangzhen-fit2cloud** [comment]
感谢您的反馈，v1.6.0 版本中修改了报告的展示形式，请升级后再体验下
