### ISSUE TITLE
[FEATURE]前后置脚本支持groovy

### ISSUE THREAD

**Issue by xianwq** [metersphere/metersphere#935]
**请描述您的需求或者改进建议.**

目前前后置支持beanshell和python，不支持groovy

**请描述你建议的实现方案**

辛苦能够支持groovy，相对beanshell来说，groovy语法更强大一些；
原生的jmeter是支持的，辛苦添加一下

**Comment by maninhill** [comment]
收到，排期 1.7 版本解决。

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 已支持。
