### ISSUE TITLE
[FEATURE]集成禅道建议将禅道缺陷的所属模块同步过来

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9351]
**请描述您的需求或者改进建议.**

集成禅道之后，建议将禅道缺陷的所属模块字段同步过来，
![image](https://user-images.githubusercontent.com/19423100/149308994-29401647-a36d-4737-bd2b-71cbdea8e86d.png)

**请描述你建议的实现方案**
与禅道影响版本、禅道处理人一样
![image](https://user-images.githubusercontent.com/19423100/149309134-2f4115c5-e6c4-40f2-842e-412ab887ac9b.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/149443689-8b7afd87-8088-4866-b7ca-ff9afc546434.png)
所属项目、相关需求、相关任务 这些都可以同步过来

**Comment by Hyyfit** [comment]
感谢您的反馈，我们目前已经实现了jira的同步，后面也会实现禅道的同步～
已规划，待排期。
