### ISSUE TITLE
Git下来后使用空间几百M，占用空间几十个G

### ISSUE THREAD

**Issue by MyKays** [metersphere/metersphere#9361]
**请描述您的问题.**
win11环境，下拉代码后使用空间100多M，占用空间4G；
装了依赖后，占用空间飙升到50G。
win10确没有这个问题，求大佬解答一下！

**Comment by Hyyfit** [comment]
正常是没有这个问题的，要不你加一下我的企业微信，具体看一下问题？
<img width="314" alt="image" src="https://user-images.githubusercontent.com/95834771/153349861-5b9c0853-cbad-4e25-b95a-9c01b479ed9c.png">
