### ISSUE TITLE
[BUG]功能测试用例大于和小于号脑图无法正确展示

### ISSUE THREAD

**Issue by pengzhengyou** [metersphere/metersphere#9367]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5
**Bug 描述**
功能用例步骤选用文本框的形式描述，当输入“<”和“>”号时  脑图中无法正确展示
简要描述您碰到的问题

**Bug 重现步骤**

1.  创建一个功能用例
2. 步骤选用“文本”
3. 输入“<”和“>”
4. 保存
5. 查看脑图
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
<img width="499" alt="截屏2022-01-14 上午11 04 15" src="https://use
<img width="483" alt="截屏2022-01-14 上午11 04 44" src="https://user-images.githubusercontent.com/34637801/149444560-51853100-e0db-4d5e-a9fe-b5c39d36607f.png">
r-images.githubusercontent.com/34637801/149444507-4c719a04-fa4e-4b12-b54b-ebb31275d755.png">

**Comment by zyyfit** [comment]
您好，这个问题是因为文本编辑的格式是markdown，而脑图不是markdown编辑器，所以无法显示这些符号，目前不太好修改，可能会在后面的版本进行优化

**Comment by zyyfit** [comment]
脑图暂不支持markdom的编辑器，只做简单的编辑，这里markdown的转义内容会原样显示，需要查看完整显示请从用例列表查看
