### ISSUE TITLE
[BUG]集成禅道创建缺陷时影响版本字段加载排序不正确

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9368]
**MeterSphere 版本**

1.16.4

**Bug 描述**
集成禅道创建缺陷时影响版本字段加载排序不正确

**Bug 重现步骤**

1.  测试跟踪-缺陷管理-创建缺陷
2. 查看影响版本
3. 影响版本排序无规则
4. 

**期待的正确结果**

排序与禅道一致，最新的版本在上面见图

**截图**
![image](https://user-images.githubusercontent.com/19423100/149445860-a6b574d5-de94-4bbf-ade9-6561ca55dbaa.png)

上面是禅道的，这个是MS的
![image](https://user-images.githubusercontent.com/19423100/149446034-e9de6ac7-c5c0-45cd-8d1e-4694811bfedf.png)

**Comment by youliyuan-fit2cloud** [comment]
目前版本没有处理这个顺序，后续考虑优化一下~
