### ISSUE TITLE
[BUG]接口测试环境配置，环境列表样式问题

### ISSUE THREAD

**Issue by geaizhen21** [metersphere/metersphere#937]
**MeterSphere 版本**
v1.5.1-b120

**Bug 描述**
添加若干个环境，直到出现滚动条，样式异常

**Bug 重现步骤**
1.  依次进入，接口测试 》创建测试 》点击环境选择框 》环境配置
2. 点击环境列表右上角的 + 号，添加若干个环境，直到出现滚动条

**期待的正确结果**
样式保持正常

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/24629821/102157991-7359bf00-3ebb-11eb-8310-80561dac8ec1.png)

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
