### ISSUE TITLE
[BUG]mock函数选择了右侧的具体函数后，此想取消是无法取消的。如图

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9371]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.4

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  mock函数选择了右侧的具体函数后，如果想取消是无法取消的，必须关闭当前页，重新打开业务进行设置。如图
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/149447151-15b5cc2c-1c20-4f4e-9e15-5916c25f87d0.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已修复
