### ISSUE TITLE
[BUG]dubbo接口传参是整数，查看日志提交的是浮点数

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9372]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
v1.15.4
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  dubbo接口传参输入整数，查看请求内容是整数，查看日志实际是浮点数
2. dubbo接口传参输入长整型变成了科学计数法
3. dubbo接口传参输入整型，日志中提交的后几位发生了改变

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/149448808-be8c3dde-ed52-449c-a8f3-d0283e33c723.png)
![image](https://user-images.githubusercontent.com/36387811/149448973-d7718122-c3e1-4573-ad4f-e0548490d3b1.png)
![image](https://user-images.githubusercontent.com/36387811/149705062-c7bb50d9-3fce-46ac-8562-2c8cb648701d.png)
![image](https://user-images.githubusercontent.com/36387811/149705109-0c55be35-1c53-49d3-bdce-ba8ab43c3545.png)
![image](https://user-images.githubusercontent.com/36387811/149748155-f0ee0cca-0f3f-47ac-8762-2ac22c6b17e2.png)

**Comment by zyyfit** [comment]
您好，请问这个参数的类型是定义的浮点型吗？如果本来的参数类型就是浮点型的话，我们是不会控制接口本身的类型转换的

**Comment by zyyfit** [comment]
您好，请问这个参数的类型是定义的浮点型吗？如果本来的参数类型就是浮点型的话，我们是不会控制接口本身的类型转换的

**Comment by liuruibin** [comment]
定义接口没有指定类型的话会被dubbo强制转换，如果指定了类型就是正常的

**Comment by happyend1709** [comment]
dubbo接口传参输入整数，查看请求内容是整数，查看日志实际是浮点数
这个还存在

**Comment by liuruibin** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/23045261/154007666-7fd2326e-ddcf-4027-84c8-31792f4e9c3f.png">
别用map当参数，用自定义类，属性固定类型这样才好使
