### ISSUE TITLE
[FEATURE]请问最新的源代码在哪个分支下？

### ISSUE THREAD

**Issue by 2858917634** [metersphere/metersphere#9380]
**请描述您的需求或者改进建议.**
另外请更新主分支的https://github.com/metersphere/metersphere/blob/master/backend/src/main/java/io/metersphere/api/dto/definition/request/extract/MsExtract.java
文件第69行代码prev.hashCode()为prev.ResourceId()
否则将无法提取到参数

**请描述你建议的实现方案**

**Comment by luty2018** [comment]
master是我们正在开发的分支，目前1.16最新

**Comment by 2858917634** [comment]
> master是我们正在开发的分支，目前1.16最新

但是master分支的代码已经很久没有更新了，最新的1.16.5的代码并没有在master分支
