### ISSUE TITLE
性能测试执行页面文描不准确[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#939]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5
**Bug 描述**
简要描述您碰到的问题
持续时间
开始时间
结束时间

改成
开始执行时间
计划结束时间
当前执行时长 或者 当前执行时间

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by maninhill** [comment]
收到。
