### ISSUE TITLE
在功能用例录入使用脑图的时候，可以选择多个节点，但是实际只能保留2个[BUG]

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#9391]
**MeterSphere 版本**

1.65

**Bug 描述**

内容同标题，原因（猜测）：前端脑图节点没有做限制，但是后端限制了长度，导致前端显示保存成功，实际保存失败；

**Bug 重现步骤**

1.  功能用例脑图录入多个节点
2. 点击保存后，再次打开

**期待的正确结果**

应该保存上，或者提示无法保存

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您是模块没保存上还是用例没保存上呢？有没有什么特殊操作呀
