### ISSUE TITLE
对接禅道无法获取到创建者，创建人都是点同步的人[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#9419]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4

**Bug 重现步骤**

1. 正确对接禅道
2. 点击同步缺陷按钮，创建人都是MS里面点同步的人
3. 尝试添加自定义字段，也无法获取到对应的创建人

**期待的正确结果**
创建人和禅道里面的创建人一一对应

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/35896106/149692311-1f7ba2ab-bf00-408f-b845-58f2bc58825d.png)
![image](https://user-images.githubusercontent.com/35896106/149693093-915b473d-46a4-4831-bfbe-a5176864ad2d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，ms系统里的创建人和禅道不一样，可以添加自定义字段进行同步，字段的值需要对应禅道里的登录账号，API字段名也需要填写禅道里的创建人字段，如图，您试一下是否可以同步成功

![图片](https://user-images.githubusercontent.com/73461316/151322386-ff967277-c7b4-4f27-9507-69cf9baa3f47.png)
