### ISSUE TITLE
[BUG]使用JSONPath的$..xx的语法匹配多个值时，提取出来的值不应该只有一个

### ISSUE THREAD

**Issue by Tomorrow1993** [metersphere/metersphere#942]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
官方demo版本
https://demo.metersphere.com/

**Bug 描述**
简要描述您碰到的问题
接口提取功能使用JSONPath的`$..xx`语法匹配多个值时，提取出来的值不应该只有一个
**Bug 重现步骤**
1.  在提取tab中使用JSONPath语法，语法值为：`$..type`
2. 点击调试，查看返回的提取值

**期待的正确结果**
正确情况下应该是什么样的？
按照JSONPath的语法，此表达式取出来的值应该是多个值拼到一起的，而不应该只提取了一个值

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/22310427/102197735-82ad2c80-3efc-11eb-81a9-e343d674feb0.png)

**Comment by wangzhen-fit2cloud** [comment]
v1.6.2 已修改
