### ISSUE TITLE
[BUG]IDEA插件导入的接口信息，没有swagger导入的全，有一部分信息swagger可以导入，但是idea插件导入接口为空。如图

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9432]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.5

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  IDEA插件导入的接口信息，没有swagger导入的全，有一部分信息swagger可以导入，但是idea插件导入接口为空
2. 【中科曙光】
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/78218624/149706879-eb212178-434e-4a8e-9568-0d4861dd7912.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by xulinde** [comment]
这个功能后面版本会支持

**Comment by luty2018** [comment]
可以更新插件版本，已经实现了这个功能。
