### ISSUE TITLE
[FEATURE]能否提供bearer token认证方式。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9433]
**请描述您的需求或者改进建议.**

能否提供bearer token认证方式。

**请描述你建议的实现方案**
![image](https://user-images.githubusercontent.com/78218624/149710263-668541e1-d6bf-4492-8020-1bbd1d34d0d3.png)

**Comment by Hyyfit** [comment]
已规划，待排期。

**Comment by iamshen** [comment]
> 已规划，待排期。

大半年了...
