### ISSUE TITLE
[BUG] 调试任务生成jmeter脚本无法用jmeter打开

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#944]
**MeterSphere 版本**
1.5

**Bug 描述**
在 reuqest  body 中 使用 ${req_data}
在JSR223PreProcessor中使用 
vars.put("req_data","{
 "test":"value"
}")

`注意: 这句代码是错误的`
调试时发现发出的请求body没有被替换。
于是修改源码保存jmx脚本
![image](https://user-images.githubusercontent.com/5517369/102290353-dad74380-3f7b-11eb-8745-3d34bfda6cda.png)

使用jmeter  GUI打开脚本,脚本报错
```
Problem loading XML from:'/Users/qiantao/tmp/jmeter/test2.jmx'. 
Cause:
NullPointerException: 

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree/hashTree[3]/JSR223PostProcessor
line number         : 117
version             : 5.2
-------------------------------
```
对应117行
![image](https://user-images.githubusercontent.com/5517369/102290515-2853b080-3f7c-11eb-88df-b936a1d7bd2f.png)
与正常jmeter脚本对比
缺少
`guiclass="TestBeanGUI" testclass="JSR223PreProcessor" testname="JSR223 PreProcessor"`
正常如下
![image](https://user-images.githubusercontent.com/5517369/102290599-520cd780-3f7c-11eb-80b7-dbdfe31cf660.png)
添加对应属性值到test2.jmx
重新打开报错
<BackendListener testname="f1e1b7cb-4031-418d-b229-b188c161683f">
同样缺少
`guiclass="BackendListenerGui" testclass="BackendListener" `
添加后可以正常打开

经过调试发现是对应的前置脚本错误，（换行符和引号问题）
```
vars.put("req_data","{
 "test":"value"
}")
```
此bug在jmeter gui的日志里面是可以看到异常日志。

**期待的正确结果**
1. 如果添加改行代码保存的jmx文件能正常被打开。
2. 如果前置脚本执行失败应该能提示前端页面，**（最起码在调试接口的时候能看到对应的错误）**

**Comment by maninhill** [comment]
收到，排期 v1.6.1 版本解决。

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
