### ISSUE TITLE
[BUG]性能测试报告SQL查询频繁、而且查询很慢

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#9445]
**MeterSphere 版本**

1.10.8-lts

**Bug 描述**

SELECT report_id AS reportId, content, part
FROM load_test_report_detail
WHERE report_id = ?
 AND part > ?
ORDER BY part
这条SQL查询很慢且频繁，

使用以下SQL给report_id加上索引
create index load_test_report_detail_report_id_index
    on load_test_report_detail (report_id);  
加上索引之后索引有优化效果

解决方法：后续lts版本，给report_id加上索引

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化

**Comment by zhangzhaox** [comment]
这个SQL得优化加上索引，目前而已优化明显，但该SQL的返回结果集也是比较大，常规10分钟场景 结果集大于300M，对数据库的磁盘IO开销依然很大，建议part 部分异步请求展示，前面页面实时展示实际每次仅只需一个part 部分的数据，根本上减少结果集的大小优化

**Comment by youliyuan-fit2cloud** [comment]
建议升级到最新版本v1.20.0-lts
