### ISSUE TITLE
[BUG]直接导入或转换成性能测试用例时，没有上传过csv文件，后续编辑的时候再加载csv，此时csv文件未生效，请修改

### ISSUE THREAD

**Issue by sageonedream** [metersphere/metersphere#9456]
**MeterSphere 版本**

v1.16.5-57db8ebd

**Bug 描述**

直接导入或转换成性能测试用例时，没有上传过csv文件，后续编辑的时候再加载csv，此时csv文件未生效，请修改

**截图**

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
