### ISSUE TITLE
[FEATURE]graphql的支持

### ISSUE THREAD

**Issue by xialeiCP9** [metersphere/metersphere#9462]
**请描述您的需求或者改进建议.**
能否在目前版本的基础上，增加对graphql请求的支持？就像Postman一样，增加一个页签，graphql，可以录入query和variables的

**请描述你建议的实现方案**

**Comment by Hyyfit** [comment]
已规划，待排期

**Comment by garycncf** [comment]
现在很多项目都在用graphql借口开发了，希望社区可以支持graphql，谢谢
