### ISSUE TITLE
[BUG]测试跟踪首页用例数量统计显示不全

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9466]
**MeterSphere 版本**

1.16.4

**Bug 描述**
测试跟踪首页用例数量统计显示不全

**Bug 重现步骤**

1.  测试跟踪-首页
2. 查看用例数控统计圆环图
3. 显示不完整
4. 

**期待的正确结果**

应当显示完整，利用好这个显示区域，右边还要很多空白

**截图**
![image](https://user-images.githubusercontent.com/19423100/149740319-723edb05-b653-4c6c-962a-ddc89eedbb2b.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们下个版本优化下

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已优化
