### ISSUE TITLE
[BUG]删除用例页面进行了整体刷新未定位在当前删除目录

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9467]
**MeterSphere 版本**

1.16.4

**Bug 描述**

删除用例页面进行了整体刷新未定位在当前删除目录

**Bug 重现步骤**

1.  测试跟踪--功能用例--选择左侧某个用例目录（假设A）--点击
2. 删除右侧某条用例
3. 用例删除，但是页面整体刷新，未定位在之前目录 A
4. 

**期待的正确结果**

删除只刷新当前目录下数据，光标定位在选择的目录A

**截图**

**Comment by zyyfit** [comment]
1.17.0已修复
