### ISSUE TITLE
[BUG] 批量执行场景后的报告显示异常

### ISSUE THREAD

**Issue by tangw1257** [metersphere/metersphere#9469]
**MeterSphere 版本**
1.16.5

**Bug 描述**
在场景中引入其他场景，单独执行后报告正常。 但是当选择多条批量执行后，报告中整体显示成功，但该引入的场景显示失败。

**截图**
![image](https://user-images.githubusercontent.com/8164903/149746771-1c03007a-70cd-4c65-94a7-ee1e843fa009.png)
![1642412951(1)](https://user-images.githubusercontent.com/8164903/149746802-c2a7d32e-8ca3-4437-b8ef-95038a5afc52.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，目前我们没有复现，后续会持续关注这个问题
