### ISSUE TITLE
[BUG] JMX Recorder 浏览器插件录制的请求中，缺少部分请求头参数，导致无法正确的请求接口

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#947]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.5.1

**Bug 描述**
JMX Recorder 浏览器插件录制的请求中，缺少部分请求头参数，导致无法正确的请求接口

**Bug 重现步骤**
1.  用Jmeter自带的http代理服务器录制
2.  用metersphere的浏览器插件录制同样的请求

**期待的正确结果**
请求头，请求参数完全一致

**截图**
![image](https://user-images.githubusercontent.com/44999044/102311876-96ae6800-3fa8-11eb-8457-d05bdbca9e9e.png)

**Comment by LimonFHM** [comment]
该接口需要校验请求头中的Referer

**Comment by q4speed** [comment]
已修复，增加了获取extraHeaders内容，实现对不同版本的chrome兼容。

**Comment by wangzhen-fit2cloud** [comment]
@LimonFHM 你好，请升级下插件到最新版再试一下
