### ISSUE TITLE
[BUG]在测试用例脑图页面进行保存的时候，用例关键字后面的节点丢失 

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#9470]
**MeterSphere 版本**

1.65

**Bug 描述**

在测试用例脑图页面进行保存的时候，用例关键字或者p0关键字后面 显示保存成功实际未能保存成功

**Bug 重现步骤**

1.  脑图测试用例录入打开
2. 编辑用例在一个用例或者p0关键字节点后，加上超过两个节点
3. 点击保存 ，前端弹出保存成功提示
4. 切换页面再次打开原来模块

**期待的正确结果**
能够正常保存，实际超过两个节点的部分没有保存成功

**截图**
![Uploading 11.jpg…]()

**Comment by zyyfit** [comment]
您好，由于我们用例下的层级是用例步骤和用例步骤期望，所以不支持超过2层

![图片](https://user-images.githubusercontent.com/73461316/149926611-af851a63-4118-43d4-88aa-08a30e8005db.png)

**Comment by A616984934** [comment]
前端点击保存的时候 显示保存成功，希望加上提示 无法保存

**Comment by zyyfit** [comment]
> 前端点击保存的时候 显示保存成功，希望加上提示 无法保存

好的

**Comment by zyyfit** [comment]
1.20.5版本会增加无法保存的提示，请等待版本发布后验收
