### ISSUE TITLE
[FEATURE] 使用“提取”功能过程中的一项易用性优化

### ISSUE THREAD

**Issue by LimonFHM** [metersphere/metersphere#948]
**请描述您的需求或者改进建议.**
在原生Jmeter中，有JSON Path Tester等小工具，能够方便输入 表达式 得出结果，来测试我的表达式写法是否正确，如下图：
![image](https://user-images.githubusercontent.com/44999044/102313294-53092d80-3fab-11eb-89fa-8cfa9bb71796.png)

**请描述你建议的实现方案**
希望在metersphere中也加入类似功能，可以在调试后，或者运行后的body小窗口中加入类似工具。
![image](https://user-images.githubusercontent.com/44999044/102313505-b98e4b80-3fab-11eb-864d-392db873c617.png)

**Comment by LimonFHM** [comment]
这样测试好表达式，顺手就放到提取中了，体验很好，或者各位大佬有更好的实现手段也可以

**Comment by maninhill** [comment]
很赞的建议。

**Comment by wangzhen-fit2cloud** [comment]
感谢你的反馈，会考虑增加这样的测试工具，同时在考虑直接在响应体中选择某个值获取对应 jsonpath 的功能，类似下图这样
![image](https://user-images.githubusercontent.com/27671436/102320335-1c391480-3fb7-11eb-8ed9-bf161ef9582b.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，v1.7.0 中已增加推荐 jsonpath 断言功能。
