### ISSUE TITLE
[BUG]项目报表测试用例统计纵向轴系列参数切换查询需要第二次查询才正确

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9486]
**MeterSphere 版本**

1.16.4

**Bug 描述**

项目报表测试用例统计纵向轴系列参数切换查询需要第二次查询才正确

**Bug 重现步骤**

1.  项目报表--测试用例统计
2. 纵向轴系列选择功能测试用例查询--左侧柱图结果正确
3.  纵向轴系列新增一个接口用例--确定
4. 左侧柱图刷新不正确
5. 再次点击确定--左侧柱图才正确（数据也重叠了）

**期待的正确结果**

每次都按正确选择查询正常，同时多数据不要重叠

**截图**
![image](https://user-images.githubusercontent.com/19423100/149851557-3cbf3d5d-9e7a-4edc-af62-f5ddea37947e.png)

![image](https://user-images.githubusercontent.com/19423100/149851594-693f6317-c400-47d7-9bb7-05d74a85bceb.png)
![image](https://user-images.githubusercontent.com/19423100/149851625-b8688f62-8d57-4033-835c-1ffc22734236.png)

**Comment by zyyfit** [comment]
已知问题，后续版本修复

**Comment by zyyfit** [comment]
已修复
