### ISSUE TITLE
[BUG]通过LDAP方式登录后，修改个人信息中的姓名，重新登录后变回修改之前的姓名

### ISSUE THREAD

**Issue by Nemo1122** [metersphere/metersphere#9487]
**MeterSphere 版本**

 v1.16.5-57db8ebd

**Bug 描述**

通过LDAP方式登录后，修改个人信息中的姓名，重新登录后变回修改之前的姓名

**Bug 重现步骤**

1.  通过LDAP方式登录
2.  个人信息->修改名称
3.  退出系统重新登录
4.  名称回到修改之前的名称

**期待的正确结果**

姓名修改后，始终保持被修改的姓名。
估计是LDAP登录时始终重新从LDAP中取了名称去更新metersphere中的姓名

**截图**
![image](https://user-images.githubusercontent.com/19550404/149854385-5de48725-8d1d-45e2-8e93-a3f3af900e93.png)

**Comment by zyyfit** [comment]
您好，目前是这样设计的，如果要改名称需要去LDAP改
