### ISSUE TITLE
在现有基础上，增加实现迭代模式，然后再增加steping模式的--高优先级[FEATURE]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#949]
**请描述您的需求或者改进建议.**
在现有基础上，增加实现迭代模式，然后再增加steping模式的--高优先级[FEATURE]

**请描述你建议的实现方案**
在现有基础上，增加实现迭代模式，然后再增加steping模式的--高优先级[FEATURE]
1. 先实现迭代模式
2. 后实现steping模式，steping模式 在实际项目应用中 也常用，尤其是稳定性，混合场景

**Comment by wangzhen-fit2cloud** [comment]
v 1.7.0 已增加按迭代模式
