### ISSUE TITLE
backendlistener有问题，导致长期跑稳定性结果不准确--高优先级[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#950]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.0
**Bug 描述**
简要描述您碰到的问题
backendlistener有问题，导致长期跑稳定性结果不准确
**Bug 重现步骤**
1.  客户做了长跑性能测试
2.  跑了三四天，发现结果不准确
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
需要和在jmeter里跑的结果 完全类似
**截图**
如果有截图，请附上截图.

**Comment by maninhill** [comment]
收到，排期 1.6.1
