### ISSUE TITLE
[FEATURE]数据库环境没有随接口运行环境的更改而更改

### ISSUE THREAD

**Issue by zhanghuijian0215** [metersphere/metersphere#9507]
**MeterSphere 版本**

v1.16.5-57db8ebd

**Bug 前置条件**

1. 在一个测试项目中，创建<测试1> <测试2>两个测试环境
2. 已经创建【场景】用例<场景01>，<场景01>用例中包含前置SQL <前置SQL01>
3. <场景01>当前运行环境为<测试1> ,<前置SQL01>当前运行环境为<测试1>

**Bug 描述**

【接口自动化】场景测试过程中，将【运行环境】从<测试1>切换到<测试2>，前置SQL/后置SQL运行环境没有从<测试1>切换到<测试2>

**Bug 重现步骤**

1. 【接口测试】-【接口自动化】-【场景列表】-【编辑】<场景01>
2. 将<场景01>的测试环境切换到<测试2>

**当前结果**

<前置SQL01>当前运行环境为<测试1>

**期待的正确结果**

<前置SQL01>当前运行环境为<测试2>

**备注**

【场景】【运行环境】与 SQL【运行环境】无法统一的联动，对多测试环境切换带来大量的重复工作。
如存在其他更有效的方式实现【场景】与SQL 运行环境的联动，也请反馈。

**Comment by Hyyfit** [comment]
已规划，待排期。
