### ISSUE TITLE
支持一个性能测试里，包含多个脚本，压力配置里以多线程组展示[FEATURE]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#951]
**请描述您的需求或者改进建议.**

支持一个性能测试里，包含多个脚本，压力配置里以多线程组展示

目前只能上传一个脚本，需要实现一次上传多个脚本

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
收到，我们内部讨论下。

**Comment by youliyuan-fit2cloud** [comment]
1.8版本已实现
