### ISSUE TITLE
[BUG] MeterSphere 平台自带的缺陷管理下的预览功能，图片太大了

### ISSUE THREAD

**Issue by zhongfuchao** [metersphere/metersphere#9512]
**MeterSphere 版本**

v1.16.5-57db8ebd

**Bug 描述**

平台的缺陷管理，缺陷列表自带的预览功能，显示太大

**Bug 重现步骤**

1.  

**期待的正确结果**

可以正常预览

**截图**

**Comment by zhongfuchao** [comment]
![image](https://user-images.githubusercontent.com/45380139/149871546-ef21d7f0-b0a2-4f03-a303-90c118c2893e.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们后期优化一下

**Comment by youliyuan-fit2cloud** [comment]
你好，是你的图片比例问题，高度太高了
