### ISSUE TITLE
把测试概览里的图表布局改一下，一行一个图表，目前两个表 一行布局不好看[FEATURE]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#952]
**请描述您的需求或者改进建议.**

把测试概览里的图表布局改一下，一行一个图表，目前两个表 一行布局不好看

**请描述你建议的实现方案**
把测试概览里的图表布局改一下，一行一个图表，目前两个表 一行布局不好看

**Comment by maninhill** [comment]
收到，我们内部讨论下。

**Comment by youliyuan-fit2cloud** [comment]
1.8版本中已优化
