### ISSUE TITLE
[BUG]定时执行测试计划，测试完成发邮件报告的内容变量不生效

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#9523]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5

**Bug 描述**
定时执行测试计划，测试完成发邮件报告的内容变量不生效
简要描述您碰到的问题
邮件的变量不生效
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![Uploading 微信截图_20220118154542.png…]()

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
没有复现
