### ISSUE TITLE
把测试概览里User x Load Hits/s表去掉，换成User x transactions/sec 的图表[FEATURE]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#953]
**请描述您的需求或者改进建议.**
v把测试概览里User x Load Hits/s表去掉，换成User x transactions/sec 的图表

Hit/s和 transactions/sec还是有细微差别的。现在一般不用Hit/s

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
