### ISSUE TITLE
[BUG]自动化场景内的“生成报告”按钮点击之后不会在报告列表显示

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9533]
**MeterSphere 版本**

V1.16.5

**Bug 描述**
自动化场景内的生成报告按钮点击之后不会在报告列表显示

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/32027713/149905004-2993f749-df82-465b-a38f-af1a7cef2c9d.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，这里生成报告之后之前有保存才行，现在保存被优化没了，下个版本加上

**Comment by zyyfit** [comment]
1.17.0已修复
