### ISSUE TITLE
测试概览页reponse time的事务名称需要有过滤功能，只展现某些某个transactions[FEATURE]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#954]
**请描述您的需求或者改进建议.**

测试概览页reponse time的事务名称需要有过滤功能，只展现某些某个transactions

很多时候Labels会有几十个，用户只想看某个label，或者某几个labels的结果，应该提供类似check box或者其它的功能帮助用户去筛选想看的labels的响应时间

**请描述你建议的实现方案**

**Comment by maninhill** [comment]
收到，很有价值的建议，我们内部讨论下。
