### ISSUE TITLE
[BUG]小黑框自己不消失

### ISSUE THREAD

**Issue by barbie-workhard** [metersphere/metersphere#955]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  看图
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/24764542/102317995-8b146e80-3fb3-11eb-9794-a5842e333b88.png)
![1234](https://user-images.githubusercontent.com/24764542/102318484-5e148b80-3fb4-11eb-9833-67320e88f598.png)

**Comment by maninhill** [comment]
v1.6 版本将修复。
