### ISSUE TITLE
[BUG]在新建模块后，新建用例提示临时节点无法保存

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#9553]
**MeterSphere 版本**

1.65

**Bug 描述**

保存提示临时节点无法保存

**Bug 重现步骤**

1.  在新建模块后点击保存
2. 不切换页面在新模块后，加上子节点为用例，再次点击保存

**期待的正确结果**

保存成功

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #9020
