### ISSUE TITLE
[需求]建议增加其他数据库种类，比如MongoDB和Redis等主流数据库

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#9563]
**请描述您的需求或者改进建议.**

[需求]建议增加其他数据库种类，比如MongoDB和Redis等主流数据库

**请描述你建议的实现方案**
[需求]建议增加其他数据库种类，比如MongoDB和Redis等主流数据库

**Comment by Hyyfit** [comment]
已规划，待排期。
