### ISSUE TITLE
[FEATURE]海量用例当中插入一条用例体验极差【重要】

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9564]
**请描述您的需求或者改进建议.**
【场景】以功能测试用例编写为例，假设某模块一共100个用例，当前需要在54与55之前新增一个用例，目前都是新增一个，然后拖拽过去，使用便捷性很差。请注意这种操作场景是产品迭代过程当中会经常出现的，如果这个实现不好，会极大降低这个功能用例的推广，还不如excel维护
  此问题在系统自动生成ID和自定义用例ID都是一样的情况

**请描述你建议的实现方案**
【建议】按我推理，当前系统的设计，功能用例，后台应该有个默认排序的字段不可见。所以拖拽过来之后会在拖拽位置显示。那么优化的建议是：在需要插入的位置点上一条或者下一条用例 的【复制】按钮，然后新增的用例就在当前位置自动生成，后面的用例自动+1

![image](https://user-images.githubusercontent.com/19423100/150048219-f7f5a7a1-14dc-4351-8991-79405704bab7.png)

**2022-1-24新增：
    其实本质就是支持在任一位置插入一条用例**

**Comment by legend818** [comment]
2022-1-24新增：
其实本质就是支持在任一位置插入一条用例

**Comment by Hyyfit** [comment]
可以通过脑图的方式，在任意位置插入新的用例。

**Comment by legend818** [comment]
在列表页面任一位置插入一个用例是否支持下
