### ISSUE TITLE
[BUG]报表统计的时间控件现在今天查询无法满足

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9565]
**MeterSphere 版本**

1.16.5

**Bug 描述**

报表统计的时间控件现在今天查询无法满足

**Bug 重现步骤**

1.  报表统计--测试用例统计--创建时间固定时间  -选择今天
2. 选择今天00：00：00到今天当前时刻或者23：00：00
3. 无法点击确定查询
4. 

**期待的正确结果**

正确查询选择时间数据，同时动态时间最近1天是截至当前最近24小时还是昨天呢？我就想查今天，有没有快捷查询按钮？

**截图**

![image](https://user-images.githubusercontent.com/19423100/150049326-e6f1e755-d351-47e4-a644-a1bd4f67bbc4.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
