### ISSUE TITLE
[BUG]提示临时节点无法保存

### ISSUE THREAD

**Issue by A616984934** [metersphere/metersphere#9568]
**MeterSphere 版本**
最新1.65

**Bug 描述**

在脑图不切换的情况下，保存成功后，再次在此模块下，新建用例，提示临时节点无法保存

**Bug 重现步骤**

1.  脑图新建一个节点，选择成模块
2. 点击保存（提示保存成功不要切换页面）
3. 在此节点下，新建子节点选择为用例
4. 再次点击保存

**期待的正确结果**

能够保存成功
实际提示临时节点无法保存

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
Duplicate of #9020

**Comment by A616984934** [comment]
现在还有这个问题呢，照着步骤看一下？

**Comment by youliyuan-fit2cloud** [comment]
> 

你好，Duplicate of #9020 和这个问题重复了，我们在解决了，重复问题只会保留一个哈，新的直接close了
