### ISSUE TITLE
[BUG]使用dockerfile构建镜像时失败，backend下并无相应文件

### ISSUE THREAD

**Issue by lvbaocheng** [metersphere/metersphere#957]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.51
**Bug 描述**
简要描述您碰到的问题
使用dockerfile构建镜像时失败，backend下并无相应文件；COPY failed:backend/target/backend-1.5.jar: no such file or directory
**Bug 重现步骤**
1.  docker build -t metersphere:1.5.1 .
2. COPY failed: stat /var/lib/docker/tmp/docker-builder036840557/backend/target/backend-1.5.jar: no such file or directory
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
backend/target/backend-1.5.jar
backend/target/classes/jmeter/

这些文件应该存在backend目录下
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/6335294/102426113-aaf67180-4049-11eb-8d7b-e1962098ecd9.png)
![image](https://user-images.githubusercontent.com/6335294/102426179-cd888a80-4049-11eb-8896-6bd00f70e065.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，构建 docker 镜像前需要先 mvn package
请参考 https://metersphere.io/docs/dev_manual/

**Comment by lvbaocheng** [comment]
> 你好，构建 docker 镜像前需要先 mvn package
> 请参考 https://metersphere.io/docs/dev_manual/

你发的这个链接是开发配置的阿~配置的开发环境，有相关文档是讲怎么利用docker部署这个测试平台所需的服务么，官方文档翻了下没

**Comment by wangzhen-fit2cloud** [comment]
整体流程大概是
 - mvn 构建 jar 包
 - docker build 镜像
 - docker run 镜像

我们的安装包是包装了 docker-compose 进行部署运行的，可以看下 [metersphere/installer](https://github.com/metersphere/installer) 仓库中的相关脚本和文件

**Comment by lvbaocheng** [comment]
> 整体流程大概是
> 
> * mvn 构建 jar 包
> * docker build 镜像
> * docker run 镜像
> 
> 我们的安装包是包装了 docker-compose 进行部署运行的，可以看下 [metersphere/installer](https://github.com/metersphere/installer) 仓库中的相关脚本和文件

好的，非常感谢！！我先找找额外资料。或者说技术交流群吗

**Comment by wangzhen-fit2cloud** [comment]
仓库 readme 最下方有交流群的二维码

**Comment by lvbaocheng** [comment]
> 仓库 readme 最下方有交流群的二维码

非常感谢！！

**Comment by IrisChen522** [comment]
hi ,请问你构建镜像的问题最后怎么解决的，我也碰到了同样的问题
