### ISSUE TITLE
[BUG]线程组的并发用户数总和应该为开启的线程组的和，而不是所有的线程组

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#9571]
**MeterSphere 版本**
v1.16.5

**Bug 描述**
性能测试：
线程组的并发用户数总和应该为开启的线程组的和，而不是所有的线程组

**Bug 重现步骤**

1.  压力机设置最大并发用户数为100
2. 创建一个测试，假如有4个线程组，4个线程组分别设30，然后在关闭一个线程组，此时线程组并发用户数和应该为90
3. 点击保存并执行，仍然会提示“并发用户数超额”

**期待的正确结果**

可以正常运行性能测试

**截图**

<img width="1155" alt="1" src="https://user-images.githubusercontent.com/72729206/150056038-29aec407-67fd-403e-a325-882b94d8379f.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/72729206/150056056-c9676c8c-b1f5-468b-9f87-dba9afe7e026.png">
<img width="1436" alt="3" src="https://user-images.githubusercontent.com/72729206/150056058-5e2a32a2-cb0b-4454-8007-666141a9071a.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6 已修复
