### ISSUE TITLE
[BUG]如果场景最外层如果是控制器（比如 循环控制器），会导致“所有请求步骤前执行”的全局脚本 失效

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9572]
**MeterSphere 版本**
V1.16.5
您所使用的 MeterSphere 版本是？

**Bug 描述**
如果场景最外层如果是控制器（比如 循环控制器）的话，会导致“所有请求步骤前执行”的全局脚本 失效
简要描述您碰到的问题

**Bug 重现步骤**

1.  环境里配置“所有请求步骤前执行” 的 全局脚本
![image](https://user-images.githubusercontent.com/30038088/150056222-05338e4e-43cc-4be7-884b-0fb230f3fe61.png)

2. 场景最外层如果是循环控制器
![image](https://user-images.githubusercontent.com/30038088/150056266-c20f8fff-34eb-45b6-ad1a-fe1f00cb1a77.png)
3.控制器生效了
![image](https://user-images.githubusercontent.com/30038088/150056308-46280094-ea03-4565-a2f3-91477962b3b6.png)
4. 全局脚本未生效，控制台没打印出日志
![image](https://user-images.githubusercontent.com/30038088/150056362-51a3b68f-412b-4e8c-bef9-ffd929704363.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
