### ISSUE TITLE
[FEATURE] 计划执行后的报告，有办法自动发邮件或者配置钉钉提醒吗？

### ISSUE THREAD

**Issue by princ1** [metersphere/metersphere#958]
**请描述您的需求或者改进建议.**
计划执行结果每次都要登入查看，比较费劲，如果能对接邮件发送或者钉钉推送就完美了。

**请描述你建议的实现方案**

**Comment by xulinde** [comment]
您好，平台目前支持推送测试报告的链接，不是具体内容，是否能满足您需求
