### ISSUE TITLE
[BUG] jira集成，缺陷模版使用 jira 缺陷模版，字段没有同步全

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9580]
**MeterSphere 版本**
V1.16.5 
jira 使用saas 版本
您所使用的 MeterSphere 版本是？
V1.16.5 
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  
![image](https://user-images.githubusercontent.com/30038088/150057519-457b5dd8-5f16-4138-9acf-2f650191792e.png)
2.
![image](https://user-images.githubusercontent.com/30038088/150057551-cfd5e559-0825-470d-9b1f-2f16bc7c40f1.png)
3.
![image](https://user-images.githubusercontent.com/30038088/150057609-2ce7c731-7e52-48a5-8405-cbcab5b72f3e.png)

4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化一下
