### ISSUE TITLE
[BUG]场景中列表变量执行出错

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9582]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在场景变量中添加列表变量
2. 列表变量有3个值
3. 点击调试，查看响应内容列表变量正常取值
4. 点击生成报告，查看响应内容，列表变量取值为列表的值1，值3，值3，没有取到值2

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
