### ISSUE TITLE
[BUG]功能用例查看依赖关系图被前置条件覆盖

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9583]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新增一个功能用例
2. 输入前置条件
3. 添加依赖关系
4. 查看依赖关系拓扑图
5. 可以看到前置条件覆盖了依赖关系拓扑图

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
1.17.0已修复，等发版后再试试

**Comment by zyyfit** [comment]
1.16.6已修复
