### ISSUE TITLE
[BUG]接口测试-接口自动化：引用的场景无法禁用，禁用之后保存重新再进入又自动开启

### ISSUE THREAD

**Issue by zhangyafan188** [metersphere/metersphere#9596]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  引用场景
2. 禁用场景，点击”保存“按钮，关闭标签页
3. 重新进入场景页面
4. 

**期待的正确结果**

正确情况下应该是什么样的？
场景是禁用状态
**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/97216833/150078957-209a88cd-5401-44f0-b5fe-337d08f9695a.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，使用的是MS哪个版本？
