### ISSUE TITLE
[BUG] 页面上英文大小写规范不统一（见截图）

### ISSUE THREAD

**Issue by maninhill** [metersphere/metersphere#9601]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

1.16.5

**Bug 描述**

Mock -> MOCK

**截图**

![image](https://user-images.githubusercontent.com/41712985/150084245-7f7e18b9-7169-483c-a0e9-97fbc6a1562c.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，本周五发个小版本会修复~

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6已优化
