### ISSUE TITLE
[BUG]1.5.1的离线安装包，数据库驱动不可用

### ISSUE THREAD

**Issue by alontion** [metersphere/metersphere#961]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
       1.5.1的离线安装包（全新安装非升级）

**Bug 描述**
简要描述您碰到的问题
       接口测试中，连接mysql服务器，提示没有合适的数据库驱动

**Bug 重现步骤**
1.  点击“接口测试”
2. 选择一个测试场景
3. 点击“测试场景配置”
4. 选择“数据库配置”tab页
5. 输入数据库相关信息并保存
6. 点击“校验”

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/27013699/102461512-70a9c600-4083-11eb-8339-f8f2fab465b6.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，数据库连接 URL 需要使用类似这样的 JDBC URL 格式
```
jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
```
