### ISSUE TITLE
[BUG]项目环境配置HTTP配置请求头无法在创建接口时引用

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9614]
**MeterSphere 版本**

1.16.5

**Bug 描述**

项目环境配置HTTP配置请求头无法在创建接口时引用

**Bug 重现步骤**

1.  项目环境配置--HTTP配置---请求头设置
2. Content-Type application/json
3. 进入接口测试-接口定义-选择右上角刚才设置请求的环境  ----创建接口--
4. 查看-请求参数部分的请求头显示空白

**期待的正确结果**

正确加载该环境设置的http请求头

**截图**
![image](https://user-images.githubusercontent.com/19423100/150094849-a823eb4f-f597-48fb-af1e-9c14f8e24b92.png)
这里

![image](https://user-images.githubusercontent.com/19423100/150095636-23abf55f-0a0f-4009-b954-5e4ba6857212.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，环境配置的请求头 不会在接口请求头列表里面，你看看执行该接口后，请求内容是不是一致的？
![image](https://user-images.githubusercontent.com/54612864/150115714-b52e0ee5-dfa0-4a1f-857a-cef8d06ec771.png)

**Comment by legend818** [comment]
那如果我从上一接口获取token设置为环境变量，然后再这里再设置HTTP配置获取这个变量

或者说我在环境配置这里设置通用配置参数，然后再HTTP请求这里获取，是否在创建接口的时候能使用呢？

**Comment by youliyuan-fit2cloud** [comment]
你好，可以的，不需要单独设置，
1.在环境配置中加上通用配置信息：
![image](https://user-images.githubusercontent.com/54612864/150248469-2cee5e2a-b9b8-4617-80ae-9c865c08104e.png)

2.在接口A中提取token的值后，然后加个后置脚本参考下图：
![image](https://user-images.githubusercontent.com/54612864/150248165-44085f23-f879-4939-8939-b614f33387d0.png)

执行这个获取到token的接口之后，在全局通用配置里面会获取到token实际值 ，后面的接口可以直接使用了

**Comment by legend818** [comment]
我觉得你没有理解我意思，
环境变量设置通用配置我能明白，你上面说的接口A的目的两个
1）后置脚本第一句：从接口A的后置脚本，提取token设置位环境变量
2）后置脚本第二句：设置全局变量token

我现在要问的是接口B\C\D\E\F\G......这些接口时需要这个token的，是不是我需要在B\C\D\E\F\G.....每个http请求头调用这个全局参数，见下图
![image](https://user-images.githubusercontent.com/19423100/150444896-0894e655-982f-4bdf-866d-edf1cb5c0058.png)
所以我想在环境变量的 HTTP配置当中设置好，这样B\C\D\E\F\G..... 不需要每个都去设置了

**Comment by youliyuan-fit2cloud** [comment]
> 我觉得你没有理解我意思， 环境变量设置通用配置我能明白，你上面说的接口A的目的两个 1）后置脚本第一句：从接口A的后置脚本，提取token设置位环境变量 2）后置脚本第二句：设置全局变量token
> 
> 我现在要问的是接口B\C\D\E\F\G......这些接口时需要这个token的，是不是我需要在B\C\D\E\F\G.....每个http请求头调用这个全局参数，见下图 ![image](https://user-images.githubusercontent.com/19423100/150444896-0894e655-982f-4bdf-866d-edf1cb5c0058.png) 所以我想在环境变量的 HTTP配置当中设置好，这样B\C\D\E\F\G..... 不需要每个都去设置了
 
我上面的说明配置，a接口先执行，就不需要去单独设置B\C\D\E\F\G 了，你可以试试啊

**Comment by legend818** [comment]
> > 我觉得你没有理解我意思， 环境变量设置通用配置我能明白，你上面说的接口A的目的两个 1）后置脚本第一句：从接口A的后置脚本，提取token设置位环境变量 2）后置脚本第二句：设置全局变量token
> > 我现在要问的是接口B\C\D\E\F\G......这些接口时需要这个token的，是不是我需要在B\C\D\E\F\G.....每个http请求头调用这个全局参数，见下图 ![image](https://user-images.githubusercontent.com/19423100/150444896-0894e655-982f-4bdf-866d-edf1cb5c0058.png) 所以我想在环境变量的 HTTP配置当中设置好，这样B\C\D\E\F\G..... 不需要每个都去设置了
> 
> 我上面的说明配置，a接口先执行，就不需要去单独设置B\C\D\E\F\G 了，你可以试试啊



**我试了不行**
我按你思路来一下啊
第一步，提取token，设置为环境变量和全局变量
![image](https://user-images.githubusercontent.com/19423100/150469378-38f3e4c6-ece3-47e3-b1a5-91c047a5df17.png)
第二步：执行以下这个用例，检查环境变量是否成功，见下图：
![image](https://user-images.githubusercontent.com/19423100/150469407-3387fa9c-0d12-411e-81d6-763e411daedf.png)
第三步：这里就是我说的B\C\D\E\F\G ，也就是你说的后面可以引用
![image](https://user-images.githubusercontent.com/19423100/150469550-e0b90e8f-e950-469d-adb8-da393fbb7f92.png)
你是不是这个意思。


我的诉求就在这里，第三步B\C\D\E\F\G  。。。。。每个接口都这样设置一下太费劲所以我问能不能再这里设置，我缺陷提的是这个
![image](https://user-images.githubusercontent.com/19423100/150469675-ca50c232-b227-4bea-93f1-3b6956a5134d.png)

我按上图设置了一下，不行
![image](https://user-images.githubusercontent.com/19423100/150469748-b2d7b8c9-ffc7-4870-9adc-f7cb686679d9.png)

这个是对比图：我使用第三步的方式
![image](https://user-images.githubusercontent.com/19423100/150469898-4100c9fd-5fcb-4d28-8e73-03dc05e56376.png)


重点 重点就是，不要让我每个接口都去设置第三步

**Comment by legend818** [comment]
不是问题，正确，我按我步骤实现，可以应该是我少了，系统自带的设置环境变量模板是2个语句，我删除了设置为全局变量的那句
