### ISSUE TITLE
[BUG] jenkins触发测试计划，企业微信未收到消息通知

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#9615]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.17和1.16
**Bug 描述**

简要描述您碰到的问题
jenkins触发测试计划，企业微信未收到消息通知
**Bug 重现步骤**

1.
消息通知-测试计划-企业微信机器人
2.
通过jenkins调用测试计划
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
测试计划完成后，企业微信收到消息通知
**截图**

如果有截图，请附上截图.
![Uploading 323.png…]()
![Uploading 323.png…]()

**Comment by zyyfit** [comment]
通知配置错误
