### ISSUE TITLE
接口测试支持jmeter功能-csv参数化、循环控制器、简单控制器、计算器以及jmx脚本直接导入

### ISSUE THREAD

**Issue by mushankk** [metersphere/metersphere#962]
**请描述您的需求或者改进建议.**
接口测试支持jmeter功能-csv参数化、循环控制器、简单控制器、计算器以及jmx脚本直接导入

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢你的反馈，将在 1.6 发布后再逐步增加相关功能

**Comment by wangzhen-fit2cloud** [comment]
你好，循环控制器及 CSV、计数器已在 v1.7.0 中提供。
JMX 文件导入将在 1.8 版本提供。
