### ISSUE TITLE
[BUG] 性能测试上传需要的jar包后，没有生效，控制台还是报import失败，无法找到，本地jmx无问题

### ISSUE THREAD

**Issue by allinone-1** [metersphere/metersphere#9624]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本:   v1.16.4-07155cf8

**Bug 描述**
简要描述您碰到的问题
性能测试上传需要的jar包后，没有生效，控制台还是报import失败，无法找到，本地jmx无问题

**Bug 重现步骤**

1. 使用json.jar包
2.benshell脚本
import org.json.JSONObject;
import org.json.JSONArray;
2. 性能测试资源文件上传json.jar包
3. 运行性能测试
4. 

**期待的正确结果**
1.正常运行
正确情况下应该是什么样的？

**截图**
实际报错：Error invoking bsh method: eval Sourced file: inline evaluation of: ``import org.json.JSONObject; import org.json.JSONArray; //import java.util.ArrayL . . . '' : Typed variable declaration : Object constructor
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
您好，我们没有复现这个问题，现在最新版是1.17.0，您可以升级试试
