### ISSUE TITLE
[BUG]环境域名配置后没有保存

### ISSUE THREAD

**Issue by xiejzhou** [metersphere/metersphere#9625]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5
**Bug 描述**
环境域名配置后没有保存

**Bug 重现步骤**

1.  环境设置--》环境管理--》编辑--》填写环境域名
2. 点确定后没有保存成功
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/21076984/150108305-c3f6688b-0f81-4994-b931-75f720afe991.png)
![image](https://user-images.githubusercontent.com/21076984/150108348-79bc3189-76a7-483e-99ee-84aff02654ac.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，看起来你的步骤不太对，环境设置--》环境管理--》编辑-->>填写环境域名---》》点击“添加” 按钮-然后在 “确定” 试试看？

**Comment by xiejzhou** [comment]
> 你好，看起来你的步骤不太对，环境设置--》环境管理--》编辑-->>填写环境域名---》》点击“添加” 按钮-然后在 “确定” 试试看？

好的，已解决，原因是没有点击添加，直接点了确定
