### ISSUE TITLE
[BUG]条件控制器判断出问题

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9630]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
16.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  SQL请求的响应数据为空，但是添加的条件控制器都为success
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![wecom-temp-983e0dd93933ceea4f48c2630527786a](https://user-images.githubusercontent.com/36387811/150109606-d8bd3a0c-ec74-41fb-a35d-5b625275c870.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
