### ISSUE TITLE
[BUG]测试计划执行的返回不正常

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#9634]
**MeterSphere 版本**

1.16.5

**Bug 描述**

测试计划执行完成以后,执行状态为失败,但是定时任务通知企业微信和Jenkins触发收到的状态都是为成功.

**Bug 重现步骤**
定时任务执行情况
1.  设置测试计划定时任务,并且设置执行完成以后通知企业微信
2. 等待测试计划执行,测试计划执行属于**[失败]**状态
3. 查看企业微信收到的状态
4. 状态为成功

Jenkins执行情况
1.  设置Jenkins触发测试计划
2. Jenkins触发对应测试计划执行,并且测试计划执行属于**[失败]**状态
3. 查看Jenkins的状态
4. 状态为成功

**期待的正确结果**
期望企业微信收到的状态为失败
期望Jenknis的状态也为失败

正确情况下应该是什么样的？
失败
**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
你好，这个消息通知执行成功是指这个定时任务或jenkins的任务执行成功，不是判断这个测试计划里面的场景成功还是失败

**Comment by Svlang** [comment]
![image](https://user-images.githubusercontent.com/31123121/150339493-6354f7ec-743e-4210-8fd0-69d38cd78881.png)
这个是1.16.5metersphere执行的结果

![image](https://user-images.githubusercontent.com/31123121/150339562-a020d044-6c76-4c4b-a01d-9e1de94d1dac.png)
这个是1.16.5企业微信的通知的结果

![image](https://user-images.githubusercontent.com/31123121/150339894-bfdfc5c5-eb48-42c4-9efc-68768e48ba38.png)
这个是1.16.4企业微信的通知的结果

![image](https://user-images.githubusercontent.com/31123121/150340282-eef0135d-dd1f-497e-9e42-47bd7ee877f5.png)
这个是1.16.4Jenkins的结果

我想知道为什么消息通知不是场景失败和成功呢,以前的版本都是可以的呢,而且我们这边的场景是需要开发每次提交代码都会去执行接口测试案例,来保障程序的稳定性,所以要求就是如果案例执行报错就会通知这次提交是不通过,需要大家去关注,如果这个都取消了,那么开发和测试分离,其实是没办法去好好保障程序的稳定的

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已将测试计划通知统一为 执行完成，不再区分执行成功和执行失败

**Comment by warmmilk** [comment]
好好的功能为什么要砍掉呢，很是迷惑
