### ISSUE TITLE
[BUG] 需要SSL认证的接口，证书配置正确的情况下，有时候证书认证会失效

### ISSUE THREAD

**Issue by dengying721** [metersphere/metersphere#9639]
**MeterSphere 版本**

1.16.5

**Bug 描述**

需要SSL认证的接口，证书配置正确，但间隔一段时间后执行接口或者场景，首次执行总是失败，报 `Non HTTP response code: javax.net.ssl.SSLException`  错误

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/17683756/150246625-e1834fb2-73e3-4b82-ab1b-cf5a187f933c.png)

如上图，在接口用例和场景未做任何更改的情况下，定时任务每隔4小时执行一次自动化，但结果都是失败的，报错都是 Non HTTP response code: javax.net.ssl.SSLException
![image](https://user-images.githubusercontent.com/17683756/150246970-9e588b35-1f53-47e6-9517-0e14cdec9055.png)

人工进行验证，发现短时间内连续多次执行同一个场景自动化，只有第一次是全部失败的，后续两次全部都是成功的。
![image](https://user-images.githubusercontent.com/17683756/150246949-934c57dc-c1ec-43f3-9ee1-7fb8edcf2c72.png)

**期待的正确结果**

希望不管什么时候执行，证书都能生效并测试通过。

**截图**

看描述附图。

**Comment by zyyfit** [comment]
您好，目前不支持火狐浏览器，请使用chrome，火狐浏览器兼容性问题后面会优化

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
1.17.0已修复

**Comment by dengying721** [comment]
问题仍然存在：
![image](https://user-images.githubusercontent.com/17683756/153106807-4028f01f-a16a-4c04-95b6-b29fac7f7e6b.png)
明细如下：
![image](https://user-images.githubusercontent.com/17683756/153106837-a28a6ec1-1fcc-4dcb-b4b4-221d6ec2947b.png)

仍然是执行有概率全部接口报报证书错误，使用版本：v1.17.1

**Comment by zyyfit** [comment]
@dengying721 您好，最近这个问题还有出现过吗？清一下缓存试试呢？
