### ISSUE TITLE
[BUG]测试用例脑图显示功能，在火狐浏览器下展开到二级节点，显示时文字会出现重叠情况

### ISSUE THREAD

**Issue by yaoyi111** [metersphere/metersphere#9644]
**MeterSphere 版本**
1.1.6.5
您所使用的 MeterSphere 版本是？
1.1.6.5
**Bug 描述**
测试用例脑图显示功能，在火狐浏览器下展开到二级节点，显示时文字会出现重叠情况
简要描述您碰到的问题
火狐浏览器兼容问题
**Bug 重现步骤**

1.  在火狐浏览器下
2. 测试用例脑图显示功能
3. 展开到二级节点
4. 显示时文字会出现重叠情况

**期待的正确结果**

正确情况下应该是什么样的？
问题样式正确，不会出现重叠
**截图**

如果有截图，请附上截图.
![11111](https://user-images.githubusercontent.com/83771182/150264713-17bf9e61-da82-491f-8cde-3960f59886d0.jpg)

**Comment by zyyfit** [comment]
您好，目前不支持火狐浏览器，请使用chrome，火狐浏览器兼容性问题后面会优化
