### ISSUE TITLE
[BUG]获取JMeterHome错误，导致JMeter函数无法执行

### ISSUE THREAD

**Issue by miller-shan** [metersphere/metersphere#965]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
V1.5
**Bug 描述**
简要描述您碰到的问题
获取JMeterHome错误，导致JMeter函数无法执行。
**Bug 重现步骤**
1.  代码路径：src/main/java/io/metersphere/api/jmeter/JMeterService.java
2.    代码行数：
 public String getJmeterHome() {
        String home = getClass().getResource("/").getPath() + "jmeter";
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
从配置文件获取jmeter.home路径。
    @Value("${jmeter.home")
    private String home;

**截图**
![JMeterHome正确获取的方式](https://user-images.githubusercontent.com/66246797/102580494-998c9280-4139-11eb-99d5-83c9d3c9de3e.png)

**Comment by liuruibin** [comment]
本地执行先在parent工程执行一遍 mvn package 这样会把一些东西放到resources里

**Comment by miller-shan** [comment]
> 本地执行先在parent工程执行一遍 mvn package 这样会把一些东西放到resources里

只放了JMeter/bin下的配置文件。你可以试一下本地代码导入，写个JMeter函数执行下接口测试就能可复现
