### ISSUE TITLE
[BUG]功能测试用例点击编辑经常加载慢之后页面奔溃

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9651]
**MeterSphere 版本**

1.16.5

**Bug 描述**

功能测试用例点击编辑经常加载慢之后页面奔溃

**Bug 重现步骤**

1.  测试跟踪--功能用例（58780条）
2. 点击右侧编辑
3. 加载慢，有时候会奔溃，概率挺大，60%都是成空白页
4. 

**期待的正确结果**

正确打开页面

**截图**
![image](https://user-images.githubusercontent.com/19423100/150271551-ffb02e81-a1ee-4579-97bd-3573e0f1e0af.png)

![image](https://user-images.githubusercontent.com/19423100/150271107-806f0394-6c0c-4543-a4f0-92898cd3765c.png)
![image](https://user-images.githubusercontent.com/19423100/150271194-528e304b-d736-4e81-8904-ab66cae2c2a1.png)

这个浏览器
![image](https://user-images.githubusercontent.com/19423100/150273228-ea5c7478-0192-4ee0-a163-74a15179cd4f.png)

**Comment by zyyfit** [comment]
您好，我们1.17.0版本对性能做了优化，您如果升级的话可以看看还会不会卡
