### ISSUE TITLE
[QUESTION]断言时，返回值有个字段是可能存在2种返回结果，类似于jmeter的断言"或"有支持么，要怎么操作

### ISSUE THREAD

**Issue by ayqnb** [metersphere/metersphere#966]
**请描述您的问题.**
断言时，返回值有个字段是可能存在2种返回结果，我想在断言中判断这两个值只要有其中一个满足就pass。
（类似于jmeter的断言"或"），这个有支持么，若有有支持，请教下该怎么操作

**Comment by wangzhen-fit2cloud** [comment]
你好，断言预期值中可以使用正则来进行或的判断，或者使用脚本类型断言

**Comment by ayqnb** [comment]
能告知下怎么写么。
比如返回值有个msg字段，结果中返回值可能为success，也可能为ok，这两个只要有1个符合就断言成功。
 我不知道怎么写
