### ISSUE TITLE
[BUG]兼容性火狐浏览器功能用例页面鼠标滚动之后再编辑保存列表会错位

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9661]
**MeterSphere 版本**

1.16.5

**Bug 描述**

兼容性火狐浏览器功能用例页面鼠标滚动之后再编辑保存列表会错位【严重】

**Bug 重现步骤**

1.  测试跟踪--功能用例--再右侧列表上下滚动
2. 编辑用例，保存成功
3. 列表会错位
4. 

**期待的正确结果**

正常
注意 注意： 在此bug基础上，调整成不错位之后，再点击某个用例，用例打开内容也是错误的，是错位的
**截图**
![image](https://user-images.githubusercontent.com/19423100/150277547-acfd777e-988f-4092-a385-0838e2ee0f4a.png)

![image](https://user-images.githubusercontent.com/19423100/150277512-e07780e6-a158-4ec4-8a41-0f9dc65a3365.png)

**Comment by zyyfit** [comment]
您好，目前只支持chrome浏览器
