### ISSUE TITLE
[BUG]功能用例模板，更改用例状态字段的值后，在功能用例列表里该字段的值未更新

### ISSUE THREAD

**Issue by binbin0406** [metersphere/metersphere#9663]
**MeterSphere 版本1.16.5**

您所使用的 MeterSphere 版本是？

**Bug 描述**

功能用例模板，更改用例状态字段的值后，在功能用例列表里该字段的值未更新

**Bug 重现步骤**

1.  系统设置-自定义字段-更改用例状态字段的值
2.  测试跟踪模块-功能用例列表，用例状态字段的筛选值未更新

**期待的正确结果**

正确情况下应该显示该字段最新的值

****

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，我们的用例状态是系统字段，是无法更改的，您是怎么操作修改的呢

**Comment by binbin0406** [comment]
在自定义字段里就可以更改用例状态的值
