### ISSUE TITLE
测试概览页面 User Hits图表 替换成 User Transactions图表[BUG]

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#967]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.1
**Bug 描述**
简要描述您碰到的问题
测试概览页面 User Hits图表 替换成 User Transactions图表
**Bug 重现步骤**
1.  测试概览页面 User Hits图表 替换成 User Transactions图表
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
测试概览页面 User Hits图表 替换成 User Transactions图表，一般用户 关心transactions/s，dfmz需求
**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
v1.6.0 版本已修改
