### ISSUE TITLE
[BUG]浏览器录制插件生成脚本特殊字符转义bug

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#9679]
**MeterSphere 版本**
插件录制生成的脚本，url中”&”会被转译为”&amp;”,手动修改为&即可
![录制插件错误](https://user-images.githubusercontent.com/82088551/150288253-0158e8b3-566a-4c71-9688-df253e8c5205.jpg)
![Dingtalk_20210914170544](https://user-images.githubusercontent.com/82088551/150288677-70478b87-ad3f-410d-b5d3-24732983ade9.jpg)

![Dingtalk_20211227163212](https://user-images.githubusercontent.com/82088551/150288121-22218f4e-84d8-4985-8579-bcb474025a53.jpg)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by AgAngle** [comment]
你好，我测试了一下导出 jmx ，使用 jmeter 打开显示是正常的，jmx文件中确实是会转义保存，但是页面上显示是不会显示成 &amp;  格式
![image](https://user-images.githubusercontent.com/41557596/153323617-e31c6b56-ab4c-4a01-a705-2c23a3eb839a.png)
![image](https://user-images.githubusercontent.com/41557596/153323647-4d9ab99d-162c-4c71-b266-eedf0686d42f.png)

**Comment by AgAngle** [comment]
可以看下你的jmx文件里存储的是什么样的，怎么能复现你这个情况

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/153380230-d539db38-b0f6-4228-81bb-54e938defe39.png)

**Comment by zyyfit** [comment]
1.17.2已修复
