### ISSUE TITLE
[BUG]正则断言实际都不符合，系统判定一个断言成功

### ISSUE THREAD

**Issue by ayqnb** [metersphere/metersphere#968]
**MeterSphere 版本**
v1.4.3-b1050

**Bug 描述**
正则断言，维护了2个断言，返回结果没有一个符合断言，但是断言中确判断一个pass

**Bug 重现步骤**
1.  设置断言①.*success||该账号已经报名过，不能重复报名.*  
            断言②.*success .*
2. 执行接口，接口返回值为
{
    "code": 40003,
    "msg": "invalid authorization"
}
3.系统判断断言①是成功的 

**期待的正确结果**
断言结果应该是2个都fail

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/43698794/102764618-6571d580-43b6-11eb-8079-484a5fa86fae.png)

**Comment by ayqnb** [comment]
![meterSphere](https://user-images.githubusercontent.com/43698794/102765623-cfd74580-43b7-11eb-99fd-c00fb7687ec7.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，请截图看下结果中断言页面显示的内容

**Comment by ayqnb** [comment]
![image](https://user-images.githubusercontent.com/43698794/103185926-8b88ff80-48f9-11eb-9fc3-49a488e3f32e.png)


请参考截图

**Comment by wangzhen-fit2cloud** [comment]
你好，请升级到最新版进行验证
