### ISSUE TITLE
[BUG]关联本地部署的jira项目，提交缺陷的时候不能拉取jira中的数据

### ISSUE THREAD

**Issue by aragonqu** [metersphere/metersphere#9690]
**MeterSphere 版本**
V1.16.5
您所使用的 MeterSphere 版本是？

**Bug 描述**
关联本地部署的jira项目，提交缺陷的时候不能拉取jira中的数据
如，处理人不能拉取jira中的用户
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/20101789/150294511-3448348b-51d1-45c7-8572-2820f4aa77d5.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前我们支持自动同步jira平台的缺陷模板了，请问您是使用的平台模板还是自己添加的字段呢？自己添加的字段的话，字段的API字段名是否和jira里对应上了呢

**Comment by aragonqu** [comment]
> 您好，目前我们支持自动同步jira平台的缺陷模板了，请问您是使用的平台模板还是自己添加的字段呢？自己添加的字段的话，字段的API字段名是否和jira里对应上了呢

使用的平台模板，没有自定义字段，新建缺陷的时候，在处理人这里只能渠道metersphere中的用户，拉不到jira里的用户名

**Comment by AgAngle** [comment]
你好，要获取Jira的处理人需要配置自定义字段以及模板里对应字段的API字段名，或者项目配置那可以勾选Jira的模板
