### ISSUE TITLE
[FEATURE]自动化报告错乱

### ISSUE THREAD

**Issue by duanfan07** [metersphere/metersphere#9693]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4
**Bug 描述**
当接口自动化本项目有多业务场景时，每个业务场景都引用了其他项目的审核场景，然后将本项目的业务场景组成一个总的业务场景进行定时任务启动，然后对应的测试报告每个业务场景引用的其他项目的审核场景在每个业务场景下都出现，造成混乱
简要描述您碰到的问题
截图下 只有直入直出单的审核流程报错了，结果入库单等引用的地方也都有这个错误痕迹，其实没报错（这是报告失败筛选场景下，全部场景下所有的成功的不成功的 都出现了n次，非常难定位）
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**
每个业务场景引用的其他项目的审核场景的报告就在每个模块出现，别每个模块都是全量的
正确情况下应该是什么样的？

**截图**
![微信图片_20220120154509](https://user-images.githubusercontent.com/51906428/150295145-8d39943b-2587-4570-8a39-2ab6162b26f6.png)

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
从截图来看，感觉这个运行结果是正常的。
要不你加我企业微信吧，具体沟通一下是什么样的情况。

<img width="314" alt="image" src="https://user-images.githubusercontent.com/95834771/153186368-f3e4447e-db5c-4545-8b09-2e3d59a298c4.png">
