### ISSUE TITLE
[FEATURE]测试跟踪-新增用例，测试方式需增加“自动”或自定义功能

### ISSUE THREAD

**Issue by xmyemail** [metersphere/metersphere#97]
**MeterSphere 版本**
 v1.0.2-b357

**Bug 描述**
测试跟踪-新增用例，测试方式需增加“自动”或自定义功能

**Bug 重现步骤**

**期待的正确结果**
MeterSphere虽然支持自动化测试，但也只能支持HTTP API，实际项目中自动化的种类很多，比如电话通讯行业，往往是SIPP，根本就无法在MeterSphere执行这类自动化，而用例也无法标记成自动化；
一般类似情况都是自动化后，通过自动化脚本实时通过API提交至用例系统，所以用例测试方式需要增加“自动”或自定义功能，这样才能让人区分用例执行方式；

**截图**
如果有截图，请附上截图.

**Comment by wangzhen-fit2cloud** [comment]
你好，在新版本中已经支持该功能
