### ISSUE TITLE
鉴权方法建议增加通过token方式

### ISSUE THREAD

**Issue by ouyangwuhai** [metersphere/metersphere#971]
**请描述您的需求或者改进建议.**

鉴权仅支持账户密码鉴权，建议增加token鉴权方式

**请描述你建议的实现方案**
1、接口鉴权选项增加token选项，在鉴权上送时根据选项进行上送

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，鉴权部分功能会在后续完善
