### ISSUE TITLE
[BUG]性能测试，会报找不到ssl证书

### ISSUE THREAD

**Issue by daviadong** [metersphere/metersphere#9713]
**MeterSphere 版本**
1.16.5

您所使用的 MeterSphere 版本是？
1.16.5

**Bug 描述**
性能测试，会报找不到ssl证书

简要描述您碰到的问题
接口自动化的环境配置里上传证书了证书，在自动化跑通后，一键转性能，会报找不到ssl证书

**Bug 重现步骤**

1.  接口自动化的环境配置-证书配置里上传ssl证书
2. 运行接口自动化，正常跑通
3. 自动化一键转性能测试，ssl在性能测试的资源文件里也可以看见
4. 运行性能测试报找不到ssl证书，fail100%

**期待的正确结果**
在jmeter里的ssl管理器添加证书，就可以直接测试了，导出到metersphere后还是一样报找不到ssl证书

正确情况下应该是什么样的？

**截图**
![31642674145_ pic_hd](https://user-images.githubusercontent.com/51897467/150320446-30ecd998-9d8f-4c5d-bd35-5d59c7f9da4e.jpg)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by zyyfit** [comment]
1.17.0已修复
