### ISSUE TITLE
缺陷通知模板里面缺少处理人字段[BUG]

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#9718]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.6.5
**Bug 描述**

简要描述您碰到的问题
缺陷通知模板里面缺少处理人字段，处理人在缺陷里是必选项，如果能加上处理人字段，企业微信机器人通知就能看到谁来处理这个缺陷，提高协同效率 

![image](https://user-images.githubusercontent.com/35896106/150338950-6bf9da76-56c8-497e-891b-6dafec4ff454.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.17.1版本中优化了 metersphere 平台保存了处理人，第三方的没保存
