### ISSUE TITLE
[BUG]Jenkins API调用进程出现超时状况

### ISSUE THREAD

**Issue by Svlang** [metersphere/metersphere#9719]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.5

**Bug 描述**
Jenkins API调用进程出现超时状况

简要描述您碰到的问题
![image](https://user-images.githubusercontent.com/31123121/150341930-d6f2d3d5-733a-493f-8e17-939b07d26ab4.png)

**Bug 重现步骤**

1.  Jenkins调用测试计划执行
2. 会存在执行hang住的情况
![image](https://user-images.githubusercontent.com/31123121/150342090-099e8d91-3f70-4165-91a3-aba1895ad988.png)
而且hang住以后,API再次调用就不会执行测试计划了,日志也没有体现执行情况
![image](https://user-images.githubusercontent.com/31123121/150342276-1b35f14b-e0a0-45de-8750-726fed41dbbe.png)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，请问执行卡住的测试计划是接口、场景、性能用例都有吗？大概有多少个用例呢？有没有什么特殊的配置呢

**Comment by yanghuizhi** [comment]
@Svlang  hi,bro 我想请教下，api这个你怎么调用了，我也遇到了同样的问题，如有收到请回我，谢谢啦
