### ISSUE TITLE
[BUG] 测试用例执行页面，评论区富文本框展示过小

### ISSUE THREAD

**Issue by wangjiaxin1100** [metersphere/metersphere#9728]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.5及以前几个版本都存在
**Bug 描述**
页面展示问题，Chrome浏览器
简要描述您碰到的问题

**Bug 重现步骤**

1.  详见截图
2. 
3. 
4. 

**期待的正确结果**
完整展示评论区
正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/46660929/150455370-341e6240-ac86-4772-8b13-ae94ba4f160a.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本优化
