### ISSUE TITLE
[BUG]导入har包，出现异常。har如果需要可以微信传给你。

### ISSUE THREAD

**Issue by huangxine** [metersphere/metersphere#9732]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？1.16.5

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  导入har包，出现异常
2. har如果需要可以微信传给你。
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**
![image](https://user-images.githubusercontent.com/78218624/150455732-ff9a7838-ac47-4151-a1a1-2c8b62b0675f.png)

![image](https://user-images.githubusercontent.com/78218624/150455715-27207482-b52e-4bb1-a447-411d61568b53.png)

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.1已修复
