### ISSUE TITLE
[BUG] 系统设置-环境管理列表项目筛查选项重复数据

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9739]
**MeterSphere 版本**

1.16.5

**Bug 描述**

系统设置-环境管理列表项目筛查选项重复数据

**Bug 重现步骤**

1.  系统设置-环境管理---列表
2. 点击 项目  筛查
3. 选项重复数据
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

![image](https://user-images.githubusercontent.com/19423100/150463756-cb1e5c61-87db-48ec-b3f8-a9fdce7d1e6c.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复

**Comment by legend818** [comment]
正确
