### ISSUE TITLE
[FEATURE]场景中设置了断言，sql请求断言必然失败，建议修改

### ISSUE THREAD

**Issue by zengjin55** [metersphere/metersphere#974]
若场景设置了断言，如：场景设置msg=success断言
当有SQL请求时，也会进行msg=success断言，必然失败

**请描述你建议的实现方案**
2种方案：
1.若请求中设置了断言，则请求中的断言覆盖场景断言
2.非http请求时，不使用场景断言

**Comment by wangzhen-fit2cloud** [comment]
感谢反馈，我们会在后面的版本中处理下问题

**Comment by wangzhen-fit2cloud** [comment]
你好，请试用下 v1.7.0 版本更新后的接口自动化。
