### ISSUE TITLE
[需求]建议在MS维护API的时候，支持word或者PDF格式导出API数据，供交付件使用

### ISSUE THREAD

**Issue by xsjccit** [metersphere/metersphere#9744]
**请描述您的需求或者改进建议.**

[需求]建议在MS维护API的时候，支持word或者PDF格式导出API数据，供交付件使用

**请描述你建议的实现方案**
[需求]建议在MS维护API的时候，支持word或者PDF格式导出API数据，供交付件使用

**Comment by Hyyfit** [comment]
这是一个很好的建议，已规划，待排期。
