### ISSUE TITLE
[BUG] API接口粘贴POST请求会自动将浏览器参数复制到query参数区域

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9749]
**MeterSphere 版本**

1.16.5

**Bug 描述**

API接口粘贴POST请求会自动将浏览器参数复制到query参数区域

**Bug 重现步骤**

1.  接口测试--接口定义
2. --创建接口--选择POST
3. 请求区域  粘贴/oauth/token?grant_type=password&username=tes&pwd=12333&client_id=web 
4.  结果 ？之后得参数都自动再QUERY区域了

**期待的正确结果**
应该再请求体--X-WWW.FORM-URLENCODED 区域

**截图**
![image](https://user-images.githubusercontent.com/19423100/150484106-f385bc66-908f-46ea-8cc7-7931832d753a.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
目前我们对比了postman、eolink等产品，都是放在query参数里或者不做处理的，我们暂时保持现状，以兼容其他产品的用户
