### ISSUE TITLE
[BUG]接口测试断言的文档校验的 必含  和 类型校验无效

### ISSUE THREAD

**Issue by linfengjjj** [metersphere/metersphere#9750]
**MeterSphere 版本**

1.16.5

**Bug 描述**

文档校验的 必含  和 类型校验无效

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/88763608/150489510-058c84e5-5332-44c3-a5d2-9a8e621d6f47.png)
![image](https://user-images.githubusercontent.com/88763608/150489547-ae5c3f39-fdba-44dc-8b6d-eaf821ea4dbe.png)

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本优化

**Comment by zyyfit** [comment]
1.17.0已修复
