### ISSUE TITLE
标题换行展示重叠了[BUG]

### ISSUE THREAD

**Issue by G291131988** [metersphere/metersphere#976]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.0
**Bug 描述**
简要描述您碰到的问题
标题换行展示重叠了
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
换行的展示应不重叠
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37016695/102962472-e8636f00-4521-11eb-996e-8e9ab48d5009.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，新版本修改了报告的展示方式，请升级验证
