### ISSUE TITLE
[BUG]场景用例的测试报告无法显示

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9773]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
16.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  升级到16.5
2. 查看历史版本的测试报告
3. 只能看到名称，没有详情
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/150519822-9e98ccda-55c7-494a-b632-436482ef11dd.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，下个版本解决掉~

**Comment by youliyuan-fit2cloud** [comment]
v1.17.0版本已修复！
