### ISSUE TITLE
[BUG]调试-生成报告在接口测试-测试报告中没有产生报告

### ISSUE THREAD

**Issue by happyend1709** [metersphere/metersphere#9774]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
16.5
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  在场景列表
2. 选中场景，点击编辑
3. 点击调试-生成报告
4. 在接口测试-测试报告中没有报告

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/36387811/150520300-63aeeb1b-02d8-4e43-8afe-f337833f959e.png)
![image](https://user-images.githubusercontent.com/36387811/150520301-4a315259-3740-459b-9b4a-40d678c4d3e9.png)

**Comment by youliyuan-fit2cloud** [comment]
你好，最新版本v1.16.6没有复现，升级下吧
