### ISSUE TITLE
[性能测试]请问好久可以支持WebSocket性能测试

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#978]
请问好久可以支持WebSocket性能测试？
工作中使用的比较多
![image](https://user-images.githubusercontent.com/43331464/102983817-9a616200-4547-11eb-9930-040af4a871e0.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，目前还没有很明确的规划，暂定在下个版本 1.7 当中实现

**Comment by 52testing** [comment]
我一直有个疑问与想法。
这些插件使用，为什么不能用户自定义呢，他需要什么就自己加jar包插件调用就是。就像安装插件一样。因为可能涉及的类似插件可能也很多太多，一一这样去实现是不是太费开发成本和时间维护。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BugKing <notifications@github.com&gt;
发送时间: 2020年12月23日 22:23
收件人: metersphere/metersphere <metersphere@noreply.github.com&gt;
抄送: 52testing <547120698@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[metersphere/metersphere] [性能测试]请问好久可以支持WebSocket性能测试 (#978)





 
你好，目前还没有很明确的规划，暂定在下个版本 1.7 当中实现

**Comment by wangzhen-fit2cloud** [comment]
性能测试可以通过上传编辑好的 jmx 和 所需的 jar 包的方式进行。
接口测试的话现在有在线编辑的功能，对于每个支持的插件，都需要有对应的前端页面，目前还没想到有很灵活的方式可以解决这个问题。
