### ISSUE TITLE
预置变量和自定义变量无效[BUG]

### ISSUE THREAD

**Issue by wikeex** [metersphere/metersphere#979]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.1

**Bug 描述**
简要描述您碰到的问题
环境配置中的自定义变量和内置的变量在请求中没有替换成变量值（见截图），该问题在本地搭建的环境中存在，线上预览环境未发现，尚不清楚什么原因导致的。

**Bug 重现步骤**
1.
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
自定义变量名替换为变量值。

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/11536029/102996427-16ff3b00-455e-11eb-8dfe-de63b9515d48.png)
![image](https://user-images.githubusercontent.com/11536029/102996468-25e5ed80-455e-11eb-838f-1d7aa761329a.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，截图中的页面是还没正式发布的 1.6 版本的功能，请在 1.6 正式发布后再重试一下，如果问题还存在请再重新打开该 issue
