### ISSUE TITLE
[FEATURE]测试计划关联用例页面筛选条件优化

### ISSUE THREAD

**Issue by xmyemail** [metersphere/metersphere#98]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  测试跟踪->测试计划->选择一个具体测试计划->关联测试用例；
结论：无法根据用例的各个字段属性过滤用例，比如，有P0-P4等级用例，这个阶段仅需要测试P0-P1级别的用例，添加用例就是个噩梦；

**期待的正确结果**
可根据用例属性进行过滤，例如根据优先级、类型、测试方式等，凡用例所支持的类型，具可以通过过滤方式来至计划中；

**截图**
![2](https://user-images.githubusercontent.com/67886923/86578228-0d811700-bfae-11ea-9e1a-aa49316bbd34.png)

**Comment by wangzhen-fit2cloud** [comment]
与已有 issue #59 重复
