### ISSUE TITLE
修改自带的mysql端口后，不能打开metersphere

### ISSUE THREAD

**Issue by sunyn218** [metersphere/metersphere#980]
**请描述您的问题.**

在ubantu系统上使用tar包安装，修改了docker-compose-mysql.yml 文件中的端口号，安装完成 服务启动后，浏览器打不开地址，显示如图
![image](https://user-images.githubusercontent.com/30695349/103003687-300ee880-456c-11eb-84d3-de2dfb595a6b.png)
查看mactl status  ms-server 提示 Exit
![image](https://user-images.githubusercontent.com/30695349/103003885-7a906500-456c-11eb-9035-ba5342821d42.png)

**Comment by wangzhen-fit2cloud** [comment]
请问具体是如何修改的？ 可以通过如下命令查看容器日志
```bash
docker logs ms-server
```

**Comment by sunyn218** [comment]
报错：com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
把docker-compose-mysql.yml中的ports改成了 其他端口号

**Comment by wangzhen-fit2cloud** [comment]
请查看下这个配置文件
```bash
cat /opt/metersphere/.env
```

**Comment by youliyuan-fit2cloud** [comment]
您好，我们没有复现您的问题，如果有问题请联系我们～
