### ISSUE TITLE
[BUG]手动与jenkins同时触发接口自动化时，会出现一个报告同一个接口被执行两遍的情况。

### ISSUE THREAD

**Issue by chenqiunuan** [metersphere/metersphere#983]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.5.1
**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  同时手动和jenkins执行接口测试
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？
每一种触发都有相应的测试报告，不应该一起。
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/53041390/103048308-210a5380-45c9-11eb-85f9-c94c27d3c6cb.png)

**Comment by wangzhen-fit2cloud** [comment]
@fit2-zhao 勇哥 1.6 发布后看是否也有一样的问题，然后处理下吧
