### ISSUE TITLE
[性能测试]不支持多选模块压测

### ISSUE THREAD

**Issue by 52testing** [metersphere/metersphere#984]
我们性能测试按照模块编写jmx脚本；
除了压测一个还需要多个同时压测。

**Comment by wangzhen-fit2cloud** [comment]
你好，目前是否可以通过把多个脚本的内容拼成一个 jmx 来满足这个场景呢？

**Comment by 52testing** [comment]
对于负载测试应该可以。并发模式的话，场景组合应该不行了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BugKing <notifications@github.com&gt;
发送时间: 2020年12月24日 15:07
收件人: metersphere/metersphere <metersphere@noreply.github.com&gt;
抄送: 52testing <547120698@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[metersphere/metersphere] [性能测试]不支持多选模块压测 (#984)





 
你好，目前是否可以通过把多个脚本的内容拼成一个 jmx 来满足这个场景呢？

**Comment by xulinde** [comment]
v1.8性能测试新加的功能能否满足您的需求？
![image](https://user-images.githubusercontent.com/64065190/112445829-83bae900-8d8a-11eb-8761-868b1e76c4cc.png)
