### ISSUE TITLE
[BUG] case通过率计算不正确

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#9843]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16
**Bug 描述**

简要描述您碰到的问题
对一个case运行了3次，1次失败，2次成功，通过率显示57%
**Bug 重现步骤**

1.  case运行多次
2. 其中有失败的
3. 观察通过率
4. 

**期待的正确结果**

正确情况下应该是什么样的？
通过率计算正确
**截图**

如果有截图，请附上截图.
![微信图片_20220122201407](https://user-images.githubusercontent.com/45531073/150638249-627ab887-25fa-41ae-a686-d4cc81f45440.jpg)
![微信图片_20220122201358](https://user-images.githubusercontent.com/45531073/150638256-e6d58c15-554c-4696-aab9-939145e1be13.jpg)

**Comment by zyyfit** [comment]
您好，没有复现这个问题，您这个用例是否在之前也执行过呢？我们的通过率是统计所有的执行次数的，您可以查看一下用例的执行历史
