### ISSUE TITLE
[BUG]用例状态显示不正确

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#9844]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1，16
**Bug 描述**

简要描述您碰到的问题
1.用例执行后通过后，用例状态仍然显示未执行
**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？
用例执行通过后，用例状态改变完成
**截图**

如果有截图，请附上截图.
![微信图片_20220122202708](https://user-images.githubusercontent.com/45531073/150638913-b1f877ba-d7d5-4063-9a20-fcdf3ff4d221.jpg)

**Comment by zyyfit** [comment]
您好，没有复现这个问，您具体使用的版本是1.16.几呀，如果不是最新版的话建议您升级到1.16.6最新版试试
