### ISSUE TITLE
[BUG]场景里“复制”或者“引用”一个子场景的话，无论是否开启，“是否启用场景环境”都是优先使用子场景定义的变量

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#9878]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
V1.16.6
**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建一个场景，“复制“一个子场景（包含场景变量），在新场景中定义一个同名的 “场景变量”
2.子场景变量
![image](https://user-images.githubusercontent.com/30038088/150675160-7588f1dc-d469-4469-a532-35504e3c9f6b.png)
4. 新父场景  定义 和 子场景 同名的 变量，值不同
![image](https://user-images.githubusercontent.com/30038088/150675280-3190f1ba-2219-4cbb-93d5-c42082db7b51.png)

5.不开启 “启动场景环境”
![image](https://user-images.githubusercontent.com/30038088/150675246-9710fced-51e4-4870-880f-542ca861947d.png)
6.开启 “启动场景环境”
![image](https://user-images.githubusercontent.com/30038088/150675262-c0270eac-01fe-4435-97e9-8b9ff741d13a.png)
请求相同

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by luty2018** [comment]
引用变量跟是否启用场景环境没有关系，默认都是优先用原场景的变量， 1.17 会在变量引用有优化，关注直播
