### ISSUE TITLE
[FEATURE]集成jenkins后，无法选择多个测试计划，如果没有功能集成jenkins形同虚设

### ISSUE THREAD

**Issue by Bbbixia** [metersphere/metersphere#988]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/50947686/103052548-5cf6e600-45d4-11eb-86bb-88fbfe12e142.png)

**请描述你建议的实现方案**

**Comment by wangzhen-fit2cloud** [comment]
你好，感谢你的反馈，我们会考虑再后续的版本中优化下这部分功能，目前的话可以先通过添加多个 metersphere 构建环节的方式来使用
