### ISSUE TITLE
[BUG]配置 SMTP 密码为空时保存报错

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [metersphere/metersphere#99]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
v1.0.2
**Bug 描述**
在配置 SMTP 页面不填写密码进行保存时界面报错

**Bug 重现步骤**
1.  在配置 SMTP 的页面点击编辑
2. 填写主机、端口及用户名信息，密码不填写
3. 点击保存

**期待的正确结果**
可以正常保存

**截图**

**Comment by AgAngle** [comment]
v1.0.3版本已修复
