### ISSUE TITLE
[BUG]测试跟踪首页圆环图显示不全

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9903]
**MeterSphere 版本**

1.16.6

**Bug 描述**

测试跟踪首页圆环图显示不全

**Bug 重现步骤**

1.  测试跟踪--首页
2. 圆环图显示不全
3. 
4. 

**期待的正确结果**

之前做了一次调整，我认为修改zh者局限于在圆环图下去修改的，我觉得应该打破这个设计去展示数据。一定要使用圆环图？这个圆环图有百分比展示还是有什么其他优点呢？

**截图**

![image](https://user-images.githubusercontent.com/19423100/150716297-e8220a47-6358-4aaa-9412-8ef5064aeaf2.png)

**Comment by luty2018** [comment]
> **MeterSphere 版本**
> 
> 1.16.6
> 
> **Bug 描述**
> 
> 测试跟踪首页圆环图显示不全
> 
> **Bug 重现步骤**
> 
> 1. 测试跟踪--首页
> 2. 圆环图显示不全
> 
> **期待的正确结果**
> 
> 之前做了一次调整，我认为修改zh者局限于在圆环图下去修改的，我觉得应该打破这个设计去展示数据。一定要使用圆环图？这个圆环图有百分比展示还是有什么其他优点呢？
> 
> **截图**
> 
> ![image](https://user-images.githubusercontent.com/19423100/150716297-e8220a47-6358-4aaa-9412-8ef5064aeaf2.png)

![image](https://user-images.githubusercontent.com/36292514/150727629-cc151687-9351-49c3-a699-f5d28f78b967.png)
感谢你的反馈 麻烦在企业微信联系我沟通下使用问题哈，目前并不是因为这个圆环的设计有多好，而是还没有计划要对首页有大的布局调整。
