### ISSUE TITLE
[BUG]环境配置已经设置了通用的Token，但是接口请求无法使用，还需要再次设置

### ISSUE THREAD

**Issue by pengs** [metersphere/metersphere#991]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.6版本

**Bug 描述**
环境配置已经设置了通用的Token，但是在接口请求的时候，没有获取到值

**Bug 重现步骤**
1.  环境配置,配置token和请求方式
2. 请求接口或者调试，或者执行用例等都无法使用环境配置的数据

**期待的正确结果**
       配置通用tonken,接口直接取值使用；无法每个接口单独再去配置token

**截图**
![image](https://user-images.githubusercontent.com/8827875/103123606-e2a39000-46bf-11eb-96cd-d1e8864af065.png)
![image](https://user-images.githubusercontent.com/8827875/103123631-f2bb6f80-46bf-11eb-997d-6f57d3f738b4.png)

**Comment by wangzhen-fit2cloud** [comment]
你好，在最新版本中已经解决了该问题，请升级验证
