### ISSUE TITLE
[BUG]功能用例高级查询缺少前置条件、步骤和期望

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9911]
**MeterSphere 版本**

1.16.6

**Bug 描述**

功能用例高级查询缺少前置条件、步骤和期望

**Bug 重现步骤**

1.  测试跟踪--功能用例--高级查询
2. 缺少前置条件、步骤和期望
3. 
4. 

**期待的正确结果**

补充前置条件、步骤和期望的检索

**截图**

![image](https://user-images.githubusercontent.com/19423100/150718402-d9e45b92-559c-4bfe-9f30-2b1e323d6212.png)

**Comment by Hyyfit** [comment]
目前规划上是不考虑在高级搜索里增加这些搜索选项的。
但是后期会考虑，在搜索框搜索时增加前置条件、步骤和期望范围的模糊匹配。
