### ISSUE TITLE
[BUG]功能用例用例状态列筛选不正确

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9919]
**MeterSphere 版本**
1.16.6
9844 那个缺陷人家也出现了，你们以无法复现处理的，他出现我出现，肯定有问题，如果复选不了，试一下导入的数据查询
**Bug 描述**

功能用例用例状态列筛选不正确

**Bug 重现步骤**

1.  测试跟踪--功能用例--用例状态列选择
2. 未开始--点击筛选
3. 列表显示已完成 （选已完成筛选，列表展示无数据。目前系统都是已完成状态的用例  ，，进行中的没测试  ）
4. 

**期待的正确结果**

正确筛选

**截图**
![image](https://user-images.githubusercontent.com/19423100/150731572-06e196c4-2152-43c7-8b24-ad8ac010697b.png)

![image](https://user-images.githubusercontent.com/19423100/150732755-e24be89a-5179-4753-a65e-435175ab7608.png)

![image](https://user-images.githubusercontent.com/19423100/150732778-7f180bf6-e56f-430b-9888-4f84fa955675.png)

注意 注意，目前这种情况页面显示已完成，导出时这个，应该是相同问题
![image](https://user-images.githubusercontent.com/19423100/150733293-65335730-6cf2-4a11-846c-31ae2d715174.png)

**Comment by zyyfit** [comment]
1、9844是说的接口用例，我们无法复现可能是因为和用户的操作或者数据不同，所以我们需要用户进一步反馈来帮助我们排查定位问题，如果您能稳定复现或者复现概率较大的话可以给我们提供数据或复现方法。
2、关于您这个问题，方便把您的用例导出excel给我们看看吗？只导出一条有问题的用例也可以

**Comment by legend818** [comment]
找陈建星或者王进我录制了一个视频发他们了。。excel也发了，你告诉我数据库表这个用例状态是哪个字段

> 1、9844是说的接口用例，我们无法复现可能是因为和用户的操作或者数据不同，所以我们需要用户进一步反馈来帮助我们排查定位问题，如果您能稳定复现或者复现概率较大的话可以给我们提供数据或复现方法。 2、关于您这个问题，方便把您的用例导出excel给我们看看吗？只导出一条有问题的用例也可以

---------------

**Comment by legend818** [comment]
再提供一点数据啊
步骤，点击列表状态为已完成得用例，页面用例状态显示已完成，查看变更记录  无
![image](https://user-images.githubusercontent.com/19423100/150896927-cd48e761-c2d6-4bc6-ad40-db334cbaa6d5.png)
不做任何操作，保存，查看变更记录，这里竟然是未开始---》已完成

![image](https://user-images.githubusercontent.com/19423100/150897071-b9056a04-9203-4d3c-840f-e90b2b633674.png)

**Comment by legend818** [comment]
![image](https://user-images.githubusercontent.com/19423100/151089537-0b136533-5103-4b3e-9a99-0d106e156380.png)
test_case表这个字段存储错误，缺陷本质是批量导入的时候没有对这个字段做校验["Prepare","Underway","Completed"]，理论上只应该支持者三个字段，但是导入的时候没有做校验，告诉我怎么处理脏数据

**Comment by zyyfit** [comment]
收到，后续版本修复，关于处理数据的问题我们同事说跟您联系过了

**Comment by zyyfit** [comment]
1.17.0已修复
