### ISSUE TITLE
[BUG]jira同步缺陷经办人为空、创建和修改jira缺陷时经办人无论选谁都默认填入最后一个

### ISSUE THREAD

**Issue by igotyouu** [metersphere/metersphere#9928]
**MeterSphere 版本**

v1.16.5-57db8ebd

**Bug 描述**

1.集成jira同步缺陷时，经办人无法同步，同步过来经办人都是空的；
2.集成是使用jira模板情况下，创建或修改缺陷时，经办人一栏下拉确实展示jira系统中的人员，但不管选谁，都默认填入了最后一个人的名字；

**Bug 重现步骤**

1.  集成jira，点击同步缺陷，检查各个同步过来的缺陷数据中的经办人，都是空
2. 集成是使用jira模板情况下，创建或修改缺陷时，经办人一栏下拉确实展示jira系统中的人员，但不管选谁，都默认填入了最后一个人的名字；

**期待的正确结果**

1.正常同步并展示jira系统中的经办人；
2.创建和修改jira缺陷时，经办人能够正常选中任意想选的人；

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，使用1.16.6没有复现这个问题，您可以升级试试，还有问题的话可以再跟我们反馈

**Comment by igotyouu** [comment]
收到
