### ISSUE TITLE
[BUG]测试跟踪-功能用例初始化页面没有六个点点【兼容性问题】

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9959]
**MeterSphere 版本**

1.16.6

简要描述您碰到的问题
测试跟踪-功能用例初始化页面没有六个点点

**Bug 重现步骤**

1.  测试跟踪-功能用例--默认查询
2. 查看列表
3. 
4. 

**期待的正确结果**

有那六个点点

**截图**
这个是对比图：
没有那六个点的浏览器版本：

版本 97.0.4692.99（正式版本） （64 位）

这个是有六个点点的版本
版本 97.0.4692.71（正式版本） （64 位）

![image](https://user-images.githubusercontent.com/19423100/150764723-ee85ca1c-2743-43c9-a5dd-9fd03754106e.png)

**Comment by zyyfit** [comment]
您好，没有这个排序拖动按钮是因为您按照id排序了，如果列表有按照某个字段排序后，我们就会隐藏手动排序的按钮

**Comment by legend818** [comment]
功能操作太隐蔽，感觉还是哪个排序切换、刷新页面之后还是按之前的点击排序不发生改变导致
