### ISSUE TITLE
[BUG]批量用例审核通过不友好

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9984]
**MeterSphere 版本**
1.16.6
**场景**
第一次全系统用例导入，用例状态都是未评审，需要一次性批量评审通过
**Bug 描述**

批量用例审核通过不友好

**Bug 重现步骤**

1.  测试跟踪--用例评审-关联--通过上面的复选框选择全部用例
2. 点击任一用例的三个。。。
3. 编辑
4. 弹出页面显示：更新10个用例的属性
5. 设置为 通过
6. 全部用例都通过了

**期待的正确结果**

10应该是动态的

**截图**

![image](https://user-images.githubusercontent.com/19423100/150891435-83a89953-0ff5-4aec-affb-8dddb05cbc78.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.17.0已修复
