### ISSUE TITLE
[BUG]用例评审左侧模块加载慢

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9985]
**MeterSphere 版本**

1.16.6

**Bug 描述**

用例评审左侧模块加载慢
**前提**
已经关联过了用例，大概9万，模块比较多

**Bug 重现步骤**

1.  测试跟踪--用例评审--点击某个评审内容
2. 进入到具体得评审用例列表
3. 左侧模块加载很慢
4. 

**期待的正确结果**

5S以内吧

**截图**
左侧模块加载慢
![image](https://user-images.githubusercontent.com/19423100/150892778-a07ba43e-43ec-45c9-8343-ca1041a0017b.png)
时间
![image](https://user-images.githubusercontent.com/19423100/150892832-da355d32-e6dc-4407-9a09-14156813a6c3.png)
36S得方法
![image](https://user-images.githubusercontent.com/19423100/150892890-6c764e70-68b7-4933-a8dc-3c3a63bec737.png)

**Comment by zyyfit** [comment]
感谢反馈，我们先排查一下问题

**Comment by youliyuan-fit2cloud** [comment]
v1.17.0以上版本针对加载慢的问题专门做了优化，请升级一下吧
