### ISSUE TITLE
[FEATURE]评审通过得用例进行编辑时，状态未变更为未评审

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9986]
**MeterSphere 版本**

1.16.6

**Bug 描述**

评审通过得用例进行编辑时，状态未变更为未评审
**前提**
该用例当前状态未已评审

**Bug 重现步骤**

1.  对该用例进行编辑，修改之后，点击保存
2. 保存成功
3. 查看列表用例状态
4. 

**期待的正确结果**

评审通过的用例发生变更时，用例状态应该时未评审

**截图**

如果有截图，请附上截图.

**Comment by Hyyfit** [comment]
已规划，待排期。
