### ISSUE TITLE
[BUG]用例变更之后返回列表预览还是老的内容

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9987]
**MeterSphere 版本**

1.16.6

**Bug 描述**
用例变更之后返回列表预览还是老的内容

**Bug 重现步骤**

1.  测试跟踪--功能用例，找一条用例修改步骤或者期望，保存成功，关闭当前编辑页面
2. 在列表点击预览（或者切换模块，再来看此用例的预览）
3. 预览的还是修改之前内容
4. 

**期待的正确结果**

正确预览修改之后效果

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.0已修复
