### ISSUE TITLE
[BUG]项目勾选自动获取缺陷模板，创建JIRA缺陷时，发现字段的类型不对导致提交报错

### ISSUE THREAD

**Issue by dashenyucainiao** [metersphere/metersphere#9990]
**MeterSphere 版本**

V1.16.6

**Bug 描述**

客户的jira模板有个“抄送人”字段是数组，但是MS获取到的是单选下拉，所以提交的时候报数据类型不对的错误

**截图**
![image](https://user-images.githubusercontent.com/32027713/150899743-a98a13a2-cbc1-4c7d-886d-fabfc220b352.png)

JIRA上的字段类型：

![image](https://user-images.githubusercontent.com/32027713/150899647-6b69604d-de9a-4e87-9149-5b86e2fdc131.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
1.18.0已修复
