### ISSUE TITLE
[BUG]环境设置，建议模块匹配时模块和路径不允许为空

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#9994]
**MeterSphere 版本**

v1.16.5

**Bug 描述**

环境导入，一个环境下有多个域名，导出在导入后就只剩下一个了

**Bug 重现步骤**

1.  创建一个环境，添加多个域名
2. 导出json后，在换个项目导入
3. 发现只导入了启用条件为“无”的域名，但是启用条件为“模块”和“路径”的也允许为空

**期待的正确结果**

模块或路径为空的正常导入

**截图**

![1](https://user-images.githubusercontent.com/72729206/150901394-0e9cfe1c-f19b-4e3c-b970-01ac5e40ab3a.png)
![2](https://user-images.githubusercontent.com/72729206/150901443-ce3df938-f47d-45b8-8997-927a94f343a2.png)

**Comment by zyyfit** [comment]
您好，因为导入其他项目后，模块和原项目的模块不一样，所以我们去掉了模块的匹配地址，没有匹配条件的和路径匹配的地址都会保留的

**Comment by fit2cloud-yangxiaoyan** [comment]
但是模块和路径的值是允许为空的，值为空的应该保留啊

**Comment by zyyfit** [comment]
1.18.1已修复
