### ISSUE TITLE
[BUG]定时同步，任务保存后再编辑，添加请求参数开关会自动打开

### ISSUE THREAD

**Issue by jackelchen** [metersphere/metersphere#9997]
**MeterSphere 版本**
v1.16.6-637a179f

**Bug 描述**
定时同步，任务保存后再编辑，添加请求参数开关会自动打开

**Bug 重现步骤**
1.  接口测试-接口定义-更多操作-定时同步
2. 填写正常内容，添加
3. 点击刚添加的任务
4. 

**期待的正确结果**
添加保存时开关是关的，编辑时开关应该默认是关

**截图**
![image](https://user-images.githubusercontent.com/15845086/150901503-dc5115f5-a660-4760-8e9e-a18409941415.png)
![image](https://user-images.githubusercontent.com/15845086/150901533-30c2746b-3963-4ff4-9847-47d33338cbd9.png)

**Comment by zyyfit** [comment]
已知问题，1.17.0修复

**Comment by zyyfit** [comment]
1.17.0已修复
