### ISSUE TITLE
[BUG]功能用例列表排序在刷新页面切换菜单之后都不会发生变更

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#9998]
**MeterSphere 版本**

1.16.6

**Bug 描述**

功能用例列表排序在刷新页面切换菜单之后都不会发生变更

**Bug 重现步骤**

1.  测试跟踪--功能用例--点击某列（支持排序）进行排序
2. 切换项目或者切换其他页面（接口测试）或者刷新页面等
3. 再返回到功能用例
4. 排序结果还保留

**期待的正确结果**
要重置
个人觉得刷新，退出等操作这个排序不应该保留，例如那个列表的六个点就因为这个会隐藏，这样会导致新手都不知道这个隐藏逻辑
难道时特意这么设计的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，目前是这样设计的
